### ISSUE TITLE
can't fit table into x columns with padding = 0

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#10001]
### Describe the bug

@zhiburt I ran into another strange problem after `$env.config.table.padding = 0` is set. When padding is 0 I can't open a nuon file but when padding is 1, it opens fine.

![image](https://github.com/nushell/nushell/assets/343840/0cd05f02-bef2-44c0-bc93-14a254752d9a)

I'm attaching the file in the screenshot here. It should be renamed to .nuon after downloading.
[startup-times.txt](https://github.com/nushell/nushell/files/12333957/startup-times.txt)

### How to reproduce

1. download file
2. set `$env.config.table.padding = 0`
3. open file with `open /path/to/startup-times.nuon | where build == release`
4. get the `can't fit table into x columns` error
5. then set `$env.config.table.padding = 1`
6. open file again successfully

### Expected behavior

File should open with padding = 0

### Configuration

|key|value|
|-|-|
|version|0.83.2|
|branch|main|
|commit_hash|5d94b16d71c2e8bf8a98312ae92a7a78f5236804|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.69.0 (84c898d65 2023-04-16)|
|rust_channel|1.69.0-aarch64-apple-darwin|
|cargo_version|cargo 1.69.0 (6e9a83356 2023-04-12)|
|build_time|2023-08-14 05:42:41 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|dataframe, default, extra, sqlite, trash, which, zip|
|installed_plugins|emoji, from eml, from ics, from ini, from parquet, from plist, from vcf, gstat, highlight, hist, inc, json path, periodic-table, plot, pnet, query, query json, query web, query xml, regex, str bexpand, xyplot|

**Comment by amtoine** [comment]
i've seen that too :+1:

**Comment by zhiburt** [comment]
interesting.
