### ISSUE TITLE
How to set description for aliases?

### ISSUE THREAD

**Issue by MasterMach50** [nushell/nushell#10006]
### Question

How can I a set a description for my aliases that shows up in the autocomplete?

### Additional context and details

```nushell
alias cls = clear       # clear
alias nf = neofetch     # run neofetch
alias cdh = cd ~        # goto home directory
alias ll = ls --all     # list all files
alias sapt = sudo apt   # run apt as superuser
alias ssnap = sudo snap # run snap as superuser
alias awm-reload = awesome-client "awesome.restart()" # reload awesome
def   awm-autoreload [] { find ~/.config/awesome/ | entr -p bash awesome-client "awesome.restart()"} # automatically reload awesome
def   rgfind [file] { rg --files | rg $file } # find files using ripgrep
```

This is how I have defined my aliases. While trying to use autocomplete the comments I have written for the aliases made using functions appears as the description but the ones made using `alias` does not. Is there a simple fix for this?
![image](https://github.com/nushell/nushell/assets/64970593/8514b86b-f31f-4907-b0dc-2f1c0626f732)

**Comment by fdncred** [comment]
I think you have to:
1. have aliases defined in a file i.e. this won't work on the repl.
2. have the description comment above the alias, not to the right.

**Comment by MasterMach50** [comment]
@fdncred 
> I think you have to:
> 
>     1. have aliases defined in a file i.e. this won't work on the repl.
> 
>     2. have the description comment above the alias, not to the right.

The aliases are defined in my `config.nu`.
I changed `config.nu` file to the way you mentioned, yet the description only appears for the functions and not the aliases.
```nushell
# clear
alias cls = clear

# run neofetch
alias nf = neofetch

# goto home directory
alias cdh = cd ~

# list all files
alias ll = ls --all

# run apt as superuser
alias sapt = sudo apt

# run snap as superuser
alias ssnap = sudo snap 

# reload awesome
alias awm-reload = awesome-client "awesome.restart()"

# automatically reload awesome
def   awm-autoreload [] { find ~/.config/awesome/ | entr -p bash awesome-client "awesome.restart()"}

# find files using ripgrep
def   rgfind [file] { rg --files | rg $file }
```

**Comment by fdncred** [comment]
@MasterMach50 I think you're right. This is what mine looks like.

![image](https://github.com/nushell/nushell/assets/343840/9ed58079-b67e-459c-93e3-c89480a0e6d7)

All of the ones that have a "usage" in my setup are in modules.
