### ISSUE TITLE
`const` not allowed in pipeline

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#10008]
### Describe the bug

After https://github.com/nushell/nushell/pull/9499 is merged, constants are expected to support pipelines. Currently, it is not possible to write 
```nushell
const len = 'abc' | str length
```
while
```nushell
let len = 'abc' | str length
```
is possible

### How to reproduce

```
> const len = 'abc' | str length
Error: nu::parser::unexpected_keyword

  × const statement used in pipeline.
   ╭─[entry #1:1:1]
 1 │ const len = 'abc' | str length
   · ──┬──
   ·   ╰── 'const' in pipeline
   ╰────
  help: Assigning ''abc'' to 'len' does not produce a value to be piped. If the pipeline result is meant to be assigned to 'len', use 'const len = ('abc' | ...)'.
```

### Expected behavior

Should follow the same parsing rules as `let`.

### Configuration

| key                | value                                                                                                                      |
| ------------------ | -------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.83.2                                                                                                                     |
| branch             | main                                                                                                                       |
| commit_hash        | e77a0a48aacb1ed41da0d48ad7b2eefa5b3336b3                                                                                   |
| build_os           | linux-x86_64                                                                                                               |
| build_target       | x86_64-unknown-linux-gnu                                                                                                   |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)                                                                                        |
| rust_channel       | 1.69.0-x86_64-unknown-linux-gnu                                                                                            |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)                                                                                        |
| build_time         | 2023-08-12 19:02:04 +03:00                                                                                                 |
| build_rust_channel | release                                                                                                                    |
| allocator          | standard                                                                                                                   |
| features           | default, extra, sqlite, trash, which, zip                                                                                  |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, highlight, hist, inc, plot, query, query json, query web, query xml, xyplot |

**Comment by amtoine** [comment]
@kubouch, do you mean #9499 will allow the use of `const` in a pipeline?

**Comment by kubouch** [comment]
No, that's different. #9499 allows running pipelines at parse time. This issue is about the syntax where
```nushell
const len = 'abc' | str length
```
is not allowed but
```nushell
const len = ('abc' | str length)
```
is.

I guess the change that allowed `let` to not require parentheses was not propagated to `const`.

**Comment by amtoine** [comment]
ooh ok gotcha :ok_hand:

**Comment by jntrnr** [comment]
@kubouch it wasn't (yet). wasn't sure if you wanted it, but shouldn't be hard to fix.

**Comment by amtoine** [comment]
> @kubouch it wasn't (yet). wasn't sure if you wanted it, but shouldn't be hard to fix.
>
i would love to have it too :yum: 
for `mut`ables and `$env` as well :innocent:

**Comment by kubouch** [comment]
Yeah, I'd allow it for `const`, `mut` and mutable assignments (e.g., `$env`), just to be consistent. I don't think there is a downside to allowing it since it already works with `let`.
