### ISSUE TITLE
`update cells -c` cannot use any variables

### ISSUE THREAD

**Issue by astral-l** [nushell/nushell#10010]
### Describe the bug

Using any variable in the `--columns` flag for `update cells` produces a "variable not found" error, as if the variable was not in scope.

### How to reproduce

```
>> let table = [[a b c]; [1 3 5] [2 4 6]
>> let cols = [b c]
>> $table | update cells -c $cols {|v| $v * 2}
```

The error also occurs when:
- using any variable in a (command) pipeline with `--columns`, e.g. `update cells -c ($cols | skip 1)`
- using a variable in a list of columns, e.g. `update cells -c [b $other_col]`

### Expected behavior

`update cells` should be able to accept variables for the `--columns` flag.

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.83.1                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | linux-aarch64                                        |
| build_target       | aarch64-unknown-linux-gnu                            |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12)                  |
| rust_channel       | stable-aarch64-unknown-linux-gnu                     |
| cargo_version      | cargo 1.71.0 (cfd3bbd8f 2023-06-08)                  |
| build_time         | 2023-08-01 17:53:53 -04:00                           |
| build_rust_channel | release                                              |
| allocator          | standard                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by weirdan** [comment]
This works now:

```console
$ let table = [[a b c]; [1 3 5] [2 4 6]]

$ let cols = [ b c ]

$ $table | update cells -c $cols {|v| $v * 2}
╭───┬───┬───┬────╮
│ # │ a │ b │ c  │
├───┼───┼───┼────┤
│ 0 │ 1 │ 6 │ 10 │
│ 1 │ 2 │ 8 │ 12 │
╰───┴───┴───┴────╯

$table | update cells -c ($cols | skip 1) {|v| $v * 2}
╭───┬───┬───┬────╮
│ # │ a │ b │ c  │
├───┼───┼───┼────┤
│ 0 │ 1 │ 3 │ 10 │
│ 1 │ 2 │ 4 │ 12 │
╰───┴───┴───┴────╯

$table | update cells -c [a ...$cols] {|v| $v * 2}
╭───┬───┬───┬────╮
│ # │ a │ b │ c  │
├───┼───┼───┼────┤
│ 0 │ 2 │ 6 │ 10 │
│ 1 │ 4 │ 8 │ 12 │
╰───┴───┴───┴────╯
```
