### ISSUE TITLE
VIFM integration issue

### ISSUE THREAD

**Issue by ineu** [nushell/nushell#10015]
### Describe the bug

Vifm is a CLI file manager. I run nushell in the Alacritty term emulator in Xorg. From nushell I run vifm. When I need to run a shell command, I launch `:shell` from vifm which spawns a new instance of nu. When the nested shell is closed, it returns back to vifm.

The problem: since nushell version 0.83, when I close the internal shell, I'm no longer able to do anything in vifm: it doesn't react to the key presses at all (or maybe it does but cannot redraw itself). I downgraded nushell to 0.82, and with that version vifm works as expected.

I also tested it with a new system user, which I created for this very purpose. This user doesn't have nushell or vifm configuration files that could affect the behavior.

### How to reproduce

1. Launch nushell 0.83
2. Launch vifm in the shell
3. Run `:shell` in vifm to get a nested nushell 
4. Close the nested shell via `ctrl+d`

Actual result: vifm seems frozen

### Expected behavior

Expected result: vifm continues to work as before

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.83.1                                                           |
| branch             | makepkg                                                          |
| commit_hash        | bf5bd3ff102689a3cae78ea5dfe2e67dfa92f4cd                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12) (Arch Linux rust 1:1.71.0-1) |
| cargo_version      | cargo 1.71.0                                                     |
| build_time         | 2023-07-31 15:45:24 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by amtoine** [comment]
i was able to reproduce this on latest `main` :thinking:

**Comment by fdncred** [comment]
@IanManske Do you think this could be related to the complicated foreground process handling/signal handling PRs you've worked on?

**Comment by IanManske** [comment]
@fdncred Probably. My guess is that VIFM doesn't have job control, and so we need to restore control to it instead on our end. This will require us to keep track of the initial foreground process id and restore it on exit. For example, [how fish does it](https://github.com/fish-shell/fish-shell/blob/0874dd6a965a3baf160ef4c656d6635b92f87cdc/fish-rust/src/common.rs#L1634). Unfortunately, this means we cannot use `std::process::exit` for the `exit` command.

**Comment by fdncred** [comment]
Sounds complicated

**Comment by ineu** [comment]
Updated to 0.85, tested the fix, works great, thanks a lot!
