### ISSUE TITLE
Tab completion order of directories is inconsistent with order of files (doesn't always provide the lexicographically first name first)

### ISSUE THREAD

**Issue by cumber** [nushell/nushell#10020]
### Describe the bug

When I use tab completion to get a list of directories, it provides them in a different order than it would files with the same names.

For example, if there are files `foo`, `foo-bar` and `foobar`, then the tab completion menu will list them in lexicographic order as I expected:

1. foo
2. foo-bar
3. foobar

If those same names are used for directories instead, tab completion lists them in this order:

1. foo-bar
2. foo
3. foobar

It seems this happens because nushell is adding a trailing slash to the directory names and *then* lexicographically sorting the list of completion entries; `-` sorts before `/`, so `foo-bar/` sorts before `foo/`.

It makes perfect sense for an abstract completion system to sort its entries lexicographically, so this behaviour is arguably not even a bug; if you consider the `/` part of the completion entry then this is exactly what should happen. However I've been finding it very inconvenient when `<TAB>` `<ENTER>` is not reliably selecting the *shortest* matching path. The dependency on whether the relevant contents of my filesystem are files or folders (as well as which characters happen to have codes smaller than `/`) is just not sticking in my brain to make this behaviour intuitively predictable, despite understanding what is likely going on.

It is particularly jarring since the *prompt* has been filled in with the longest common prefix, i.e `foo`. If there is a possible match *with* that name I would expect to be what is selected when I hit `<ENTER>`; if I simply see the desired result filled in the prompt and so don't take the time to read the completion menu, then it's quite surprising when it then fills in a different folder name instead.

### How to reproduce

1. `mkdir /tmp/example; cd /tmp/example`
2. `touch foo foo-bar foobar`
3. type `ls f<TAB>`
    1. completion menu shows: `foo                 foo-bar             foobar`
    2. prompt has been filled to `ls foo`
    3. pressing `<ENTER>` will produce `ls foo`
5. `rm *`
6. `mkdir foo foo-bar foobar`
7. enter `ls f<TAB>`
    1. completion menu shows: `foo-bar/            foo/                foobar/`
    2. prompt has been filled to `ls foo`
    3. pressing `<ENTER>` will produce `ls foo-bar/`

### Expected behavior

The trailing slash shown for folder names in file completion menus should not affect the sorting of the completion options.

Alternatively, nushell could simply stop presumptively adding the trailing slash when completing directories. That's likely to break people's intuition and muscle memory in a different way, however. It could be configurable?

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.82.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31) (built from a source tarball) |
| cargo_version      | cargo 1.70.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
I thought they were sorted by Levenshtein distance. I think this is where it's changed. You may be able to experiment with it.
https://github.com/nushell/nushell/blob/696b2cda4afee607540336c688568bcfff97deac/crates/nu-cli/src/completions/command_completions.rs#L212-L213

**Comment by cumber** [comment]
@fdncred Levenshtein distance from the original input string being completed? Hmm; I wasn't aware you could get completions (of files, at least) to offer any set other than "everything of which the input is a prefix". That would make only the length of the suffix relevant, wouldn't it? (the only single character edits to be counted by Levenshtein would be adding each next character; no deletions or substitutions would ever be relevant)

So in that case Levenshtein distance would be minimum for the shortest completion, regardless of string ordering; i.e. when completing `a`, `az` (distance 1) would be a better completion than `aaa` (distance 2). That definitely doesn't seem to match what's happening:

```
/tmp/example
❯ | ls a
aaa                 az
```

Have I misunderstood what it would mean to be sorted by Levenshtein distance?

**Comment by cumber** [comment]
@fdncred Oh! You're talking about tab completion of *commands*. Yes, that does seem to prefer shortest suffix regardless of string order.

My issue is with tab completion of filesystem *arguments* to commands. They seem to use different sorting.

**Comment by fdncred** [comment]
> @fdncred Oh! You're talking about tab completion of commands.

ya

> My issue is with tab completion of filesystem arguments to commands. They seem to use different sorting.

Ah, ok. Sorry. They could be using an entirely different sorting methodology. You'd have to dig around in the code to see. I'm not sure.

**Comment by ito-hiroki** [comment]
I would like to address this issue if no one is in charge!

**Comment by fdncred** [comment]
@ito-hiroki go for it.
