### ISSUE TITLE
Function won't automatically cd into the specified directory

### ISSUE THREAD

**Issue by TheBearodactyl** [nushell/nushell#10028]
### Describe the bug

I have a function in my `env.nu` file called `mkcd` that is meant to make the specified directory if it doesn't exist, go into said directory, and reload the screen using a separate function called `rld`. When I run it, it only reproduces the first and last instructions, completely skipping the part where it should `cd` into the specified directory.

### How to reproduce

1. Add
```nu
def mkcd [dirname: string] {
  mkdir $dirname
  cd $dirname
  rld
}
```
to your `env.nu` file
2. Re-enter the shell
3. run `mkcd *any directory name*`

### Expected behavior

I expected it to make a directory, `cd` into that directory, and execute the function `rld`

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.83.1                                                           |
| branch             | makepkg                                                          |
| commit_hash        | bf5bd3ff102689a3cae78ea5dfe2e67dfa92f4cd                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12) (Arch Linux rust 1:1.71.0-1) |
| cargo_version      | cargo 1.71.0                                                     |
| build_time         | 2023-07-31 15:45:24 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

### Additional context

the `rld` function I mentioned before is as follows:
```nu
def rld [] {
  clear
  uwufetch
  exa -a --git --icons --group-directories-first
}
```

**Comment by amtoine** [comment]
@TheBearodactyl 

`cd` will try to mutate the environment.
to do so, you'd need to use `def-env` instead of `def` :yum: 

if the documentation is unclear about that, please feel free to open an issue on the website repo :blush:

**Comment by TheBearodactyl** [comment]
oh, thanks
