### ISSUE TITLE
`save` uses incorrect PWD if filename is a variable

### ISSUE THREAD

**Issue by mksinicus** [nushell/nushell#10044]
### Describe the bug

If the filename passed to `save` is a variable assigned before changing into current directory, `save` may incorrectly create the file in the previous directory.

This happens in scripts (both when run and used as a module), also in REPL **but only when multiple lines of code are pasted and run at once**, if you run them one by one it will work properly. (Very strange)

### How to reproduce

```nushell
> pwd
/home/marco/temp
> cat test.nu
export def main [] {
  let foo = "foo"
  mkdir bar
  cd bar
  'foo!' | save $foo
  'baz!' | save 'baz'
}
> use test.nu; test # or `nu test.nu`
> ls **/*
╭───┬─────────┬──────┬────────┬────────────────╮
│ # │  name   │ type │  size  │    modified    │
├───┼─────────┼──────┼────────┼────────────────┤
│ 0 │ bar     │ dir  │ 4.1 KB │ now            │
│ 1 │ bar/baz │ file │    4 B │ now            │
│ 2 │ foo     │ file │    4 B │ now            │
│ 3 │ test.nu │ file │  106 B │ 10 minutes ago │
╰───┴─────────┴──────┴────────┴────────────────╯
```

Also, this still happens even when `let foo = "foo"` is after `cd bar`.

### Expected behavior

Should've saved 'foo!' to `bar/foo` instead of `foo` in PWD.

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.83.1                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.68.1 (8460ca823 2023-03-20)                                             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                                                 |
| cargo_version      | cargo 1.68.1 (115f34552 2023-02-26)                                             |
| build_time         | 2023-08-02 01:47:13 +08:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | standard                                                                        |
| features           | dataframe, default, extra, sqlite, trash, which, zip                            |
| installed_plugins  | from eml, from ics, from ini, from vcf, query, query json, query web, query xml |

### Additional context

Quick fix: use `save (pwd | path join $foo)`

**Comment by kubouch** [comment]
This is probably the issue of auto-expanding paths of parameters with `SyntaxShape::Filepath` at parse-time. That's wrong and shouldn't happen because changes to the environment, such as `cd`, are not visible until after parsing is done.

**Comment by kubouch** [comment]
Actually, I don't see it happening at parse time but during eval. Not sure why it's giving the wrong PWD then...

**Comment by kubouch** [comment]
OK, so the problem is that inside the code of `save`, the path is fetched as a string but is not expanded using Nushell's PWD. Instead, it is implicitly expanded using the system's current directory which is the one Nushell was started from. In Nushell, all paths should be expanded Nushell's environment variables because we don't use system env vars at all except when talking to externals.
