### ISSUE TITLE
Resizing window does not reflect to shell

### ISSUE THREAD

**Issue by Hyouteki** [nushell/nushell#10059]
### Describe the bug

When resizing shell from floating window to full screen or vice versa. It does not reflect to shell. Shell still remains the same as it was previously. And in full screen mode a new prompt appears at bottom even though old prompt exists.

### How to reproduce

1. Try resizing the shell.

### Expected behavior

Shell should remain the same as it was previously.

### Screenshots

![Floating window shell](https://github.com/nushell/nushell/assets/108230497/6d5c62db-56d0-4f0a-ace1-b9dc42919c96)
![Full screen shell](https://github.com/nushell/nushell/assets/108230497/e311e770-e325-419f-be56-1de2a0738ea9)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.83.1                                   |
| branch             |                                          |
| commit_hash        | bf5bd3ff102689a3cae78ea5dfe2e67dfa92f4cd |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)      |
| rust_channel       | 1.69.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)      |
| build_time         | 2023-07-30 18:18:41 +00:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by amtoine** [comment]
could this be related to https://github.com/nushell/nushell/issues/8935?

**Comment by Hyouteki** [comment]
> could this be related to #8935?

Yes. also both the issues happen while resizing and are related to prompt dislocating.

**Comment by amtoine** [comment]
then let's close this in favor of #8935, thanks for the report :pray:

**Comment by Hyouteki** [comment]
The same issue is also occurring while changing the  font size using `CTRL/CMD + mouse wheel`.

- Normal font size
![Screenshot (26)](https://github.com/nushell/nushell/assets/108230497/9011b451-5e24-4236-8819-9a1c41a8a999)

- Decreasing the font size
![Screenshot (27)](https://github.com/nushell/nushell/assets/108230497/8c13f55b-3b43-487e-9dca-727217563298)

- Increasing the font size
![Screenshot (28)](https://github.com/nushell/nushell/assets/108230497/d3522b4d-2548-4a46-b9d7-5685e1748215)
