### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by JesterOrNot** [nushell/nushell#1007]
**Is your feature request related to a problem? Please describe.**
Yes #998 and https://github.com/nushell/nushell/issues/996 one thing that has prevented me from contributing is that it's hard to know what the code for nu shell does if you don't add comments
**Describe the solution you'd like**
I think we need to either
We need to give a tour of the source code in the new contributing.md or in the nu book (which is referenced in contributing.md)**
**Alternatives**
or we can add through comments in the code explaining how and why the third party dependencies are being used
**Additional context**
None, sorry 🙁

**Comment by jonathandturner** [comment]
That's definitely something I'd like to get better about as we move the code from "make it work" to "this is good enough for 1.0"

Somewhere I was hoping to put some information is the contributor book (https://github.com/nushell/contributor-book/tree/master/en)

**Comment by JesterOrNot** [comment]
@jonathandturner Maybe we should give "A Tour Through the Source Code" in contributing.md

**Comment by coolshaurya** [comment]
Or maybe we could use https://docs.rs/ and then add doc-comments to the source code. The advantage would be that then it would be easy to read the info in a comfortable manner.

**Comment by alexxbb** [comment]
I just stumbled upon this project and I must say it looks very interesting and I'd like to contribute, however as other mentioned the **absolute** lack of comments is a serious hindrance. A one sentence description for structs and traits will make a huge difference. Maybe prefer comment the code instead of writing the contributor book?

**Comment by jonathandturner** [comment]
Yeah, we definitely played a bit fast and loose with comments. I'd like to change that. I'll be spending time this week going through and documenting the code.

**Comment by thegedge** [comment]
I'll keep this issue open for now, but it's really hard to know when it's considered "done".

I think we should keep comments in mind moving forward, whenever the code itself is unclear. I myself have been doing a lot of refactoring of the codebase to make the code easier to follow, but I'm sure there are a few places where comments could improve understandability 🙂

**Comment by pwnorbitals** [comment]
To be honest, I’m not sure this issue is of any use : clean code (self-describing, commented, documented) is and will always be an issue, and it’s hard to track. Specific tools exist for this, though, if we really want to track something... but a generic issue doesn’t make a lot of sense imo
