### ISSUE TITLE
"length" command works insconsistently with a record

### ISSUE THREAD

**Issue by lrabbt** [nushell/nushell#10074]
### Describe the bug

When piping a record through the "length" command, it works on some cases, but not on others.

This works:
```
> echo {foo: bar} | length
1
```
This does not work (notice I just removed the "echo"):
```
> {foo: bar} | length
Error: nu::parser::input_type_mismatch

  × Command does not support record<foo: string> input.
   ╭─[entry #28:1:1]
 1 │ {foo: bar} | length
   ·              ───┬──
   ·                 ╰── command doesn't support record<foo: string> input
   ╰────
```
Records coming from commands seem to work too (I didn't test with many of them, though):
```
> '{"foo": "bar"}' | from json | length
1
```
Both records are the same for the "describe" command:
```
> echo {foo: bar} | describe
record<foo: string>

> {foo: bar} | describe
record<foo: string>
```

### How to reproduce

1. Run `echo {foo: bar} | length`
2. Notice it will return "1"
3. Run `{foo: bar} | length`
4. Notice it throws an error

### Expected behavior

The command "length" should work consistently on a record.

### Configuration

> version | transpose key value | to md --pretty

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.83.1                                                           |
| branch             | makepkg                                                          |
| commit_hash        | bf5bd3ff102689a3cae78ea5dfe2e67dfa92f4cd                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12) (Arch Linux rust 1:1.71.0-1) |
| cargo_version      | cargo 1.71.0                                                     |
| build_time         | 2023-07-31 15:45:24 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment]
I've made this work where both `{foo: bar} | length` and `echo {foo: bar} | length` return 1 but I'm not sure that's right. What should `length` return on records?

**Comment by bobhy** [comment]
`length` is documented to work on tables, where it returns the number of rows in the table.  That sounds reasonable.  So if we think that a record is the same as a table of 1 row, I'd expect `<record> | length` to return 1 for any record.  Kind of a degenerate case, but defensible.  
OTOH, if you didn't read the help (like I did not when first looking at this), you might expect `{foo:bar bas:gronk} | length` to return 2, the number of key/value pairs.  But `length` has a `--column` argument that, so you can get that answer, too (once the fix from @fncred is merged).

**Comment by lrabbt** [comment]
Sorry, I forgot to mention, but I did see on the signature that `length` does *not* accept a record.

The reason I'm even trying is just based on the [cookbook's direnv snippet](https://www.nushell.sh/cookbook/direnv.html), which pipes a record coming from direnv's json - which has only 1 depth -, to the `length` command.

And about the command working with the `echo`, but not without it is something I can consistently replicate, so I decided to report it.

When trying for the first time, I was expecting `length` to return the number of "fields" (or columns) of the record, but I totally understand if that's not how you think it should work.

**Comment by lrabbt** [comment]
@bobhy thank you, I didn't see the flag actually, but the problem persists even with `--column`
```
> {foo: bar bat: ban} | length -c
Error: nu::parser::input_type_mismatch

  × Command does not support record<foo: string, bat: string> input.
   ╭─[entry #9:1:1]
 1 │ {foo: bar bat: ban} | length -c
   ·                       ───┬──
   ·                          ╰── command doesn't support record<foo: string, bat: string> input
   ╰────
```
And as before, it works if I put an `echo`, except the number of columns is *wrong*, in this case, it should be 2:
```
> echo {foo: bar bat: ban} | length -c
1
```

**Comment by fdncred** [comment]
I think my point is that there is no point to always returning 1 on records regardless of how many key/value pairs a record has. That's what my PR does. It just allows records to pass into the `length` command, but I really see no value there.

**Comment by fdncred** [comment]
I'm not sure I agree with you @bobhy.
`length` is about lists. It works on tables because a table is a list of records. 
`--column` doesn't work on records (even with my PR), it returns 1 no matter what, but it does work on tables
```nushell
# record
❯ {a: 1 b: 2} | length --column
1
# table
❯ [{a: 1 b: 2}] | length --column
2
```
nushell can tell the difference between tables of 1 row and records
```nushell
❯ {a: 1 b: 2} | describe
record<a: int, b: int>
❯ [{a: 1 b: 2}] | describe
table<a: int, b: int>
```
if you want to know how many keys you can already do
```nushell
❯ {a: 1 b: 2} | columns | length
```

I'm leaning toward removing `--column` altogether. Not sure it has much value.

**Comment by bobhy** [comment]
You're right, I'm off on a tangent, as usual.  I now think removing `--columns` is the right way to resolve this issue.

And now I (think I) know why echo {..}` allowed length to work in the first place (before it supported record input)! I think echo is accepting its inputs as a `...rest <any>` parameter.  So perhaps it is producing its output as a stream of values even when there's only one argument?  `length` would see the stream as an input it can count the elements of.

If this is so, maybe we should document the use of `echo` to cast any single value into a stream of value for the contexts where you need a list-ish thing?
