### ISSUE TITLE
Calls to `into df` fails after building with `dataframe` feature

### ISSUE THREAD

**Issue by AntoineSebert** [nushell/nushell#10105]
### Describe the bug

When starting `nushell`, the screen shows:
```sh
Error: nu::parser::extra_positional

  × Extra positional argument.
    ╭─[/home/antoine/.config/nushell/modules/sockets.nu:30:1]
 30 │ export def join-table [table: table, left_on: string, right_on: string] {
 31 │   into df | join ($table | into df) $left_on $right_on | into nu
    ·        ─┬
    ·         ╰── extra positional argument
 32 │ }
    ╰────
  help: Usage: into
```
Furthermore, `into` produces:
```sh
Usage:
  > into 

Subcommands:
  into binary - Convert value to a binary primitive.
  into bits - Convert value to a binary primitive.
  into bool - Convert value to boolean.
  into datetime - Convert text or timestamp into a datetime.
  into decimal - Convert text into a decimal.
  into duration - Convert value to duration.
  into filesize - Convert value to filesize.
  into int - Convert value to integer.
  into record - Convert value to record.
  into sqlite - Convert table into a SQLite database.
  into string - Convert value to string.

Flags:
  -h, --help - Display the help message for this command

Input/output types:
  ╭───┬─────────┬────────╮
  │ # │  input  │ output │
  ├───┼─────────┼────────┤
  │ 0 │ nothing │ string │
  ╰───┴─────────┴────────╯
```

### How to reproduce

1. install nushell using `cargo install nu --force --locked --features=dataframe,extra,sqlite`
2. download https://github.com/nushell/nu_scripts/blob/main/modules/network/sockets/sockets.nu
3. import `sockets.nu` as a module
4. start nushell

### Expected behavior

Since it seems the feature is present, dataframes should be available.

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.84.0                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | linux-x86_64                                         |
| build_target       | x86_64-unknown-linux-gnu                             |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)                  |
| rust_channel       | stable-x86_64-unknown-linux-gnu                      |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)                  |
| build_time         | 2023-08-23 23:18:55 +02:00                           |
| build_rust_channel | release                                              |
| allocator          | standard                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by horasal** [comment]
I think convert to dataframe is [`dfr into df`](https://www.nushell.sh/commands/docs/dfr_into-df.html) from 0.76.
You can find the PR [here](https://github.com/nushell/nushell/pull/7998/files)

**Comment by fdncred** [comment]
yup, that's right. all dataframe commands were renamed with `dfr`. Please reopen if that's not the case.

**Comment by AntoineSebert** [comment]
That was indeed the issue, thanks for your help !
I have created a PR: https://github.com/nushell/nu_scripts/pull/585
