### ISSUE TITLE
Mistyping '$it' doesn't error

### ISSUE THREAD

**Issue by sebastian-xyz** [nushell/nushell#1010]
**Describe the bug**
Passing something else than `$it` after `$` doesn't error.

**To Reproduce**
1. `> ls | echo $ir`

**Expected behavior**
An error should be printed.

**Configuration:**
 - OS: Windows
 - Version 0.5.1

**Comment by quebin31** [comment]
This shouldn't report an error since `$ir` can actually be a defined variable, just like `$HOME`, `$PATH`, etc.

**Comment by sebastian-xyz** [comment]
Yes. Sorry I missed that :)

I'll close this.

**Comment by sebastian-xyz** [comment]
Yes. Sorry I missed that :)

I'll close this.
