### ISSUE TITLE
Expanding glob results inline on tab completion

### ISSUE THREAD

**Issue by Isti115** [nushell/nushell#10106]
### Related problem

I have been the odd developer in the last three or so years who kept using PowerShell as my default terminal environment despite of switching to Linux, because I found it vastly superior to any of the alternatives that I knew / heard about **until now**.

Yesterday just randomly I found a video mentioning `nushell` and the more I read about it the more I was convinced that this was what I needed to transition to. (My main issues with PowerShell being speed and some incompatibilities with certain tools due to weird encoding legacies and such.)

But after I tried switching over I have realized that there's something very crucial to my muscle memory / workflow that's not working as I'd like in `nushell`. This might be entirely missing, or maybe I just haven't looked hard enough through the docs to find it.

### Describe the solution you'd like

It's the ability to expand glob patterns inline and cycle between the results. An example use case can be seen below, where I have a folder with a bunch of files, some of them being `pcapng`'s produced by Wireshark. To view one of them as a hexdump, so I can simply type `hexyl *pca` and repeatedly hit `Tab` to cycle through the matching files:

https://github.com/nushell/nushell/assets/3758493/ed4539cf-495e-4dd2-83a3-0e73002c7e4f

This can also be used on folders, commands and who knows what else. I find it to be very convenient.

### Describe alternatives you've considered

I have managed to somewhat replicate the desired functionality (not the behavior though) by running `hexyl (fzf)` in the folder and typing in `pca`, at which point I can select the right file and accept it:

https://github.com/nushell/nushell/assets/3758493/886eed29-8b29-4088-9cc0-56afedaa6d16

This poses the problem of repeatability though, as I cannot simply just hit `Up, Enter` to rerun the previous command, and also is not convenient for commands with multiple files, file paths already partially entered and such.

### Additional context and details

I would be happy to contribute work towards this if it is deemed to be an accepted feature.

**Comment by fdncred** [comment]
I don't believe that functionality exists. However, you might be able to simulate it by making a menu and/or keybinding. There are some menus and keybindings in the default_config.nu as well as there are some in our nu_scripts repo here https://github.com/nushell/nu_scripts/tree/main/custom-menus

**Comment by Isti115** [comment]
That seems like a good approach, I'll try to come up with an implementation! Thanks @fdncred for pointing me in the direction of a possible solution!

**Comment by amtoine** [comment]
i'm closing this @Isti115 just to avoid forgetting it :relieved: 
please feel free to reopen this issue if the problem persists :wink:
