### ISSUE TITLE
polars-arrow 0.30.0 does not compile

### ISSUE THREAD

**Issue by PhilVince96** [nushell/nushell#10123]
### Describe the bug

If you build nu with the latest rust compiler 1.72.0 with "cargo install nu --all-features" it does not compile because of polars-arrow 0.30.0 crate which causes the E0034 error. I assume the same happens only with the data frames feature.

### How to reproduce

cargo install nu --all-features

### Expected behavior

Builds properly.

### Screenshots

<img width="1584" alt="Screenshot 2023-08-26 at 08 59 17" src="https://github.com/nushell/nushell/assets/29581161/61fd78db-9aeb-4366-a883-fed92afd12fd">

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.83.1                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | macos-aarch64                                                                   |
| build_target       | aarch64-apple-darwin                                                            |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12)                                             |
| rust_channel       | stable-aarch64-apple-darwin                                                     |
| cargo_version      | cargo 1.71.0 (cfd3bbd8f 2023-06-08)                                             |
| build_time         | 2023-08-03 15:39:17 +02:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | mimalloc                                                                        |
| features           | dataframe, default, extra, sqlite, static-link-openssl, trash, wasi, which, zip |
| installed_plugins  | periodic-table, pnet, regex                                                     |

That is the currently working version though.

**Comment by fdncred** [comment]
You have to add `--locked` to get it to compile.

**Comment by amtoine** [comment]
ooh that's true @fdncred 
closing this as it's already been seen in the issue tracker recently :+1: 

@PhilVince96 feel free to ping us again here if the `--locked` option does not work for you :relieved:
