### ISSUE TITLE
`from csv` does not accept escaped unicode separators

### ISSUE THREAD

**Issue by matthias-Q** [nushell/nushell#10132]
### Related problem

I work with a lot of CSV files which are separated by the unicode separator '\x1f' https://www.compart.com/en/unicode/U+001F

`from csv` only accepts single characters.

### Describe the solution you'd like

I would like to give `from csv` an escaped sequence of the unicode char.

### Describe alternatives you've considered

I tried to copy it via my shell (wezterm) but this did not work. I am not sure if this the right way (i.e. it this is a terminal emulator issue or a shell issue)

**Comment by fdncred** [comment]
Related https://github.com/nushell/nushell/issues/2557 - The upstream `csv` crate only support single character delimiters https://github.com/BurntSushi/rust-csv/issues/210 https://github.com/BurntSushi/rust-csv/issues/209

**Comment by fdncred** [comment]
There may be some hope though if someone wants to figure this out.

https://github.com/BurntSushi/rust-csv/blob/574ae1ff64693b42ae0ce153926d9a0a5d546936/csv-core/src/reader.rs#L241-L248

https://github.com/BurntSushi/rust-csv/blob/574ae1ff64693b42ae0ce153926d9a0a5d546936/src/reader.rs#L583-L615
