### ISSUE TITLE
History hints are inconsistent about case

### ISSUE THREAD

**Issue by cumber** [nushell/nushell#10131]
### Describe the bug

The history hint is a bit weird about case sensitivity.

(Because I'm not completely sure if this is the right terminology: by "history hint" I mean the feature where your prompt shows an inline completion for the last command from your history matching the prefix you've already entered. I'm not talking about opening up an explicit history completion menu)

It offers a suggestion based on a case *insensitive* match of what you've already typed with a prefix of a command from history. But when you press `<END>` to accept the suggestion, it simply adds on the rest of the command to what you already typed.

If the prefix you typed was not using the same case as the command used for the hint, this results in a **new** command rather than re-running a historical command. With case-insensitive file systems this new command *may* do the same thing as the historical command but still could fail or do something wrong (depending on whether any of the non-matching parts are data being provided to a command that *is* case sensitive), and on a case-sensitive file-system it's extremely unlikely to be correct.

### How to reproduce

1. Enter `nu --version` and press `<ENTER>`
2. Enter `NU --`
3. Observe that the history hint offered after the cursor is `version` to match the previous command
4. Press `<END>` to accept the hint
5. Observe that the prompt now contains `NU --version`, which is not the previous command

### Expected behavior

Accepting the hint should completely replace the prompt, so that it matches the completed command

### Screenshots

![history-hint](https://github.com/nushell/nushell/assets/63795/104425ca-c2cf-4be9-a0e5-49e65338b24a)

![history-hint-error](https://github.com/nushell/nushell/assets/63795/fdf634b2-9432-4078-b56c-889593bf5cdf)

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.83.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.1                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by sholderbach** [comment]
Did some basic digging, as we use the [`reedline::DefaultHinter`](https://docs.rs/reedline/latest/reedline/struct.DefaultHinter.html) directly I was surprised that this matches case insensitively. But apparently the search in the [`SqliteBackedHistory`](https://github.com/nushell/reedline/blob/main/src/history/sqlite_backed.rs) is case-insensitive by default. That may be convenient under some circumstances but I am not sure how great it is for the hints?

Assuming we want to keep the case-insensitive match around, you are correct that we should simply replace the buffer with the whole entry.
For the partial hint completion (Ctrl-RightArrow by default) this will require some care as Unicode allows characters that are upper/lowercase pairs with different possible encoding lengths in UTF-8 or even number of characters [^1]. While probably relatively straight forward for ANSI chars[^2] there are some edge cases to care for.

[^1]: https://doc.rust-lang.org/std/primitive.str.html#method.to_lowercase
[^2]: https://doc.rust-lang.org/std/primitive.str.html#method.to_ascii_uppercase

**Comment by cumber** [comment]
I can see it being handy to offer case-insensitive matching, but it's also going to be weird UX no matter what.

The current weird behaviour is that you can complete accept a history hint and get a command you've never run.

But if we follow my suggestion of completely replacing the buffer, then the UX is still weird as what it's showing you before accepting the hint is not what you will get when you accept it (and it *looks* like it's offering you a command you've never run). I don't see a reasonable way around that, as we shouldn't be altering the buffer to correct the case *before* the user accepts the hint, and in an inline hint system there's nowhere else to show what the hint actually is.

So if it's also tricky to get right in all cases with unicode, maybe it is better to just make hints strict about case and save more featureful searches for the explicit history completion menu?

**Comment by sholderbach** [comment]
Good point about the UX being confusing for the hints. While for something like powershell with its liberal use of CamelCase that might be convenient in the commands are lowercase world of unix and Nushell that is probably more funky then useful.
You are right that for the explicit search case insensitivity can be helpful the best way forward would be to make sure that the hints for the `history.file_format: "sqlite"`/`SqliteBackedHistory` should simply match case-sensitive/exact. This is also easier than having to deal with all the complexity for the word by word hint completion.

**Comment by cumber** [comment]
@jods4 Apparently the case-insensitive matching happens if `history.file_format` is `sqlite`; do you have it set to `plaintext`?

However I think ideally it *probably* should be case sensitive on Windows too, once this issue is resolved. History hinting is fundamentally just about matching your partial input against entire previous command lines. It's matching the whole string `cd \pro` against `cd \Projects\`, it's not looking at the `\pro` part separately and matching it against against paths that exist. That means that the *history* hint system (unlike the *completion* system) doesn't know which parts of the command (or your partial input) correspond to paths and which are some other data being supplied on the command line. So it has to apply the same logic to matching paths in history that it does to matching everything else.

Even on Windows commands can take arguments that are things like base-64 encoded strings, or bits of actual text (people's names, message strings, etc), URLs, etc, which all need to be case sensitive. Even paths are *sometimes* case sensitive! (If you've already created a file called `README`, you can open it again by opening the path `readme`, yes. But if you're supplying the path because you expect the command to *create* a file, then the case affects how e.g. Windows Explorer will list it. So it isn't a good idea to assume that case doesn't matter in things that look like paths in a Windows command line unless you know exactly what the command *will* do with that path in future)

Completion of path names *from the file system* (i.e. with tab completion) absolutely should be case-insensitive on Windows. When the completer is doing that it knows it's providing a string that could be used to open a given file. The history hinter doesn't know enough to do that, and in my opinion it's least surprising/dangerous to just use case sensitive matching on every system.
