### ISSUE TITLE
A newline appear when typing every stroke in VSCode Terminal

### ISSUE THREAD

**Issue by Mickychen00** [nushell/nushell#10130]
### Describe the bug

I use Windows 10. I want to use nushell as the default shell in VSCode Terminal. But I found every stroke typing in the Terminal, the nushell will create a new line but this phenomenon is not shown in cmd and powershell.

### How to reproduce

I use the settings.json with:
```
"terminal.integrated.profiles.windows": {
        "Nu": {
        "path": "C:\\Program Files\\nu\\bin\\nu.exe",
        }
    },
    "terminal.integrated.defaultProfile.windows": "Nu",
```

### Expected behavior

Don't show these redundancies.

### Screenshots

![image](https://github.com/nushell/nushell/assets/28621570/8740aa22-d6e0-4cd1-8d1d-98c2fb07e8d6)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.84.0                                   |
| branch             |                                          |
| commit_hash        | d2abb8603abab43ec4a6d4ed56f9018790b99dce |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)      |
| rust_channel       | 1.69.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)      |
| build_time         | 2023-08-22 21:20:58 +00:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by hustcer** [comment]
Try to edit the config of `$nu.config-path` and set `shell_integration` to `false`

**Comment by Mickychen00** [comment]
> shell_integration

![image](https://github.com/nushell/nushell/assets/28621570/e0879059-3b7d-49a2-8846-02132ec04234)

Hi. I have check the config file. It seems that shell_integration is setted to "false" by default.

**Comment by fdncred** [comment]
should we close this?
