### ISSUE TITLE
`inspect` output header may be misaligned

### ISSUE THREAD

**Issue by starthal** [nushell/nushell#10154]
### Describe the bug

When the data to be `inspect`ed exceeds a certain display width, the table appears to be misaligned.

### How to reproduce

```
# 20 chars
~ 
❯ '01234567890123456789' | inspect
╭─────────────┬────────╮
│ description │ string │
├─────────────┴────────┤
│                      │
├──────────────────────┤
│ 01234567890123456789 │
╰──────────────────────╯

01234567890123456789

# 21 chars
~ 
❯ '012345678901234567890' | inspect
╭─────────────┬───────────────────────────╮
│ description │ string                    │
├─────────────┴─────────┤
│                       │
├───────────────────────┤
│ 012345678901234567890 │
╰───────────────────────╯

012345678901234567890
```

### Expected behavior

Either:
- A single aligned table
- Separate tables for description and data

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.82.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25) |
| build_time         | 2023-07-13 10:02:20 -04:00          |
| build_rust_channel | release                             |
| allocator          | standard                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
That's weird. @zhiburt any ideas about this?

**Comment by zhiburt** [comment]
@starthal good catch;
