### ISSUE TITLE
Windows Terminal CWD Shell integration (OSC 9;9;)

### ISSUE THREAD

**Issue by meskill** [nushell/nushell#10166]
### Related problem

Windows Terminal for tracking the current dir in shell [supports only](https://github.com/microsoft/terminal/issues/3158) osc `9;9;` while nushell generates only osc 7 to track the cwd. 

### Describe the solution you'd like

Add output for osc `9;9;` in nushell based on the [docs](https://learn.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory) that will allow to track the cwd in Windows Terminal. 

Also, it should help with shell integration inside Vs Code that currently handles osc 7 differently that prevents from opening new instance completely on windows + nushell.

### Describe alternatives you've considered

Users can add custom hook to implement this, e.g.

```nu
if $env.config.shell_integration {
  $env.config.hooks.env_change = ($env.config.hooks.env_change | upsert PWD {|config|
    let val = $config.PWD? | default []

    $val | append {|_, after|
      mut val = $after

      if not ($env.IS_WSL? | is-empty) {
        $val = (wslpath -w $val)
      }

      print -n $"(ansi -o '9;9;')($val)(ansi "st")"
    }
  })
}

```

I've tested this and it works good in Windows Terminal and Vs code integrated terminal. But it requires additional setup from users while Windows Terminal will soon or already become default terminal on Windows.

### Additional context and details

I could make pr myself but I wanted to sure it is appropriate to add windows specific shell_integration (though, I believe many windows users will benefit from it). Also, it requires specific treatment for wsl shell i.e. converting path properly - it should be simple using embedded `wslpath` command but is it ok to call some external on every cwd change? (I haven't found any existing solution to convert path without utilizing call to the command)

**Comment by fdncred** [comment]
IIRC, we send OSC7 on every new prompt if shell_integration is enabled. I wouldn't want to shell out to wslpath on every prompt. I'd be interested if you plan on sending both OSC7 and OSC9 on each prompt? I think we'd probably be up for this, but we need to talk it through, either here or in Discord #design-discussion channel.

**Comment by meskill** [comment]
Regarding that it happens on every prompt you're right as it happens on every loop of the repl.
Different terminals supports different codes so we need to support both osc 7 and osc 9;9 here.

Meanwhile, I've started the discussion in Discord

**Comment by meskill** [comment]
I found another enhancement related to wsl - https://github.com/nushell/nushell/issues/6436 that could be done by using wslpath too.

**Comment by fdncred** [comment]
As a rule of thumb, I don't like shelling out for anything as it causes performance problems. Depending on the implementation, I could be convinced to ignore that rule.

Before calling out to `wslpath` we'd have to be sure that
1. We're running on Windows 10 1809 or newer. I don't think it existed before that.
2. We're actually in WSL2. I _think_ we could check for the existence of `WSLENV`.
3. Obviously `wslpath` has to exist. We could probably find that using `where` or if it's in a known location, just check there. Like mine is in /usr/bin.
4. Has to be an efficient implementation.

I found this that may be helpful. There may be other usages on github that may be more helpful. I just did a quick search.
https://github.com/microsoft/vscode/blob/2c021905ad67daf18551e06661f86a76e2c64129/src/vs/platform/terminal/node/ptyService.ts#L444-L484

So, if you want to take a swing at a PR, I'm up for it too.

**Comment by meskill** [comment]
I'll try to work on this when I have time.

Thanks for referencing example implementation. 

Current points I'm considering to make it efficient as much as possible:
1. cache the check that we are inside wsl. 
2. cache the path to wslpath executable
3. probably changing the output of cwd related osc to execute only on actual cwd change

If anyone has any additional thoughts, please spit them out.

**Comment by Araxeus** [comment]
Hey guys, not very proficient in the nu language, how would I implement shell integration for nushell like the powershell prompt in the links below? (assuming a normal windows machine without wsl)

https://learn.microsoft.com/en-us/windows/terminal/tutorials/shell-integration

https://devblogs.microsoft.com/commandline/shell-integration-in-the-windows-terminal/

(the info links are old, this feature is available on stable windows terminal builds, not only preview)

**Comment by fdncred** [comment]
@Araxeus I'd start by using nushell 0.94.0 and enabling the particular shell integration feature you wish to have from the nushell config.nu.

9;9 is implemented now so closing this issue.

**Comment by Araxeus** [comment]
cool timing, I have updated to 0.94.0, enabled all shell integrations available (including `osc9_9`) and sadly none of the Windows Terminal shell features seem to work

**Comment by fdncred** [comment]
Looks like you don't have something setup right. I'd guess how WT is launching nushell. I have all the shell_integration items enabled and don't have issues with nushell.

**Comment by Araxeus** [comment]
> * cannot copy command/output
> * checkmarks dont seem to work

resolved by itself, I just needed to completely close windows terminal apparently

> even duplicate tab fails because the current pwd is malformed:
![image](https://github.com/nushell/nushell/assets/78568641/28887f38-ef9b-43d5-ad5e-bb639aba60bb)

but that didn't resolve, could you check if duplicate tab works for you? there seems to be an extra trailing `/` at the beggining

**Comment by fdncred** [comment]
I get something similar with duplicate tab. Could be a bug, not sure.

**Comment by fdncred** [comment]
yup, it's a bug. i see it here.
```
2024-05-29 03:54:08.865 PM [WARN ] nu_cli::repl: "\u{1b}]9;9;/C:\\Users\\username\\source\\repos\\forks\\nushell\u{1b}\\"
```

**Comment by meskill** [comment]
Also, by default, it won't work for WSL tabs without wslpath conversion compared to the hook from the description.

**Comment by fdncred** [comment]
I'm not sure of all of the magic that is in wslpath. I wonder if it's open source?

**Comment by meskill** [comment]
> I'm not sure of all of the magic that is in wslpath. I wonder if it's open source?

no, it's a built-in tool in WSL. Another option could be to try open-source alternatives and I saw only [this one](https://github.com/kkysen/wslpath) for rust

**Comment by fdncred** [comment]
I can't get that one working.

**Comment by fdncred** [comment]
It looks like shelling out to wslpath may be the best way to do this for WSL but it's kind of niche, so I'm not sure it's worth it.

**Comment by fdncred** [comment]
After looking at this for a few hours, the version of WSL2 that I have is terribly buggy wrt OSC 9;9. I can't upgrade right now. So, this will have to wait.
