### ISSUE TITLE
Unnecessary global variables from config

### ISSUE THREAD

**Issue by sophiajt** [nushell/nushell#10183]
### Describe the bug

Was looking through the variables that are visible globally, and noticed the list was:

```
~/Source/nushell| $
$dark_theme         $env                $in                 $light_theme        
$nothing            $nu 
```

### How to reproduce

1. see above

### Expected behavior

`$nothing` - a duplicate we should probably remove
`$dark_theme` - a theme, but likely not necessary at global scope
`light_theme` - a theme, also likely not necessary at global scope

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.84.1                                   |
| branch             | main                                     |
| commit_hash        | fd4ba0443d01e67f6304b7220ef414a33287bdbe |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)      |
| rust_channel       | 1.70.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)      |
| build_time         | 2023-08-31 17:26:53 +12:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by sholderbach** [comment]
As long as `$nothing` is a valid alias for `null` I think the completions should still provide it for convenience.

Agree that the `$*_theme`'s are a bit polluting. If possible they could move into their own module that you could then `use` whenever you want to change your theme config live without modifying `config.nu`

**Comment by MarikaChlebowska** [comment]
Hello, this project seems interesting to join so I would like to pick up this issue as something easy. As I understand the scope of the issue is to move the global variables with themes to a new file which can then be used as a module, update the usage of them in  `default_config.nu` and probably update the documentation regarding the usage of these themes. I'm just making sure cause I'm new to nu.

**Comment by amtoine** [comment]
@MarikaChlebowska 
thanks for considering helping Nushell get better :pray: 

i'll assign you to this issue then :relieved: 

note that `$nothing` has been deprecated in `0.86` and will be removed next release, in `0.87`, so it's not used anymore in the default config and shouldn't be :wink: 

regarding the themes, they could be set in an `export-env` block i guess, this allows to do things like
```nushell
export-env {
    def foo [] {
        "this is foo"
    }
    $env.FOO = (foo)
}
```
which will define `$env.FOO` in the outer scope without exposing the inner `foo` command :smirk:

**Comment by MarikaChlebowska** [comment]
okay, I'll look some more at the examples in the cookbook and try to implement it :)

**Comment by cosineblast** [comment]
I think it would be nice to have a comment in the configuration file explaining why `export-env` is being used there, to aid beginners

**Comment by amtoine** [comment]
> I think it would be nice to have a comment in the configuration file explaining why `export-env` is being used there, to aid beginners
>
maybe rather point to the documentation, but yeah, i agree with the underlying idea of not letting beginners in the unknown :+1:

**Comment by rottencrown** [comment]
As of `0.87.1`, we now only have `$env`, `$in`, and `$nu`.

**Comment by TheKingdom36** [comment]
@MarikaChlebowska are you still looking at this one? Was going to take it up if not

**Comment by NotTheDr01ds** [comment]
In the current main, the #14249 changes mean that, by default:

```nushell
scope variables
# => ╭────────────╮
# => │ empty list │
# => ╰────────────╯
```

I think this can be closed?

**Comment by sholderbach** [comment]
Awesome thanks!
