### ISSUE TITLE
panic when calling custom command with file argument

### ISSUE THREAD

**Issue by aidalgol** [nushell/nushell#10184]
### Describe the bug

A Nushell script panics when calling a custom command that takes an argument of type `file`.
```console
thread 'main' panicked at 'Internal error: can't run a predeclaration without a body', crates/nu-protocol/src/signature.rs:644:9
stack backtrace:
   0:     0x55e9fbac0a06 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h63269f8f54853ab3
   1:     0x55e9faf6f15f - core::fmt::write::h250dd3fc350bbada
   2:     0x55e9fbad0991 - std::io::Write::write_fmt::h0fd841d7fefd9302
   3:     0x55e9fbac0805 - std::sys_common::backtrace::print::hc99c547a903c74f7
   4:     0x55e9fbadbc75 - std::panicking::default_hook::{{closure}}::h5bbb3f780658c969
   5:     0x55e9fbadb9b3 - std::panicking::default_hook::h1946653929a625f2
   6:     0x55e9fbadc0f9 - std::panicking::rust_panic_with_hook::h8216316e1970270b
   7:     0x55e9fbac0c84 - std::panicking::begin_panic_handler::{{closure}}::h45b7865605f63cc8
   8:     0x55e9fbac0ad6 - std::sys_common::backtrace::__rust_end_short_backtrace::h2efe3248368b98bf
   9:     0x55e9fbadbce2 - rust_begin_unwind
  10:     0x55e9faeef263 - core::panicking::panic_fmt::h90a1387c4eee835e
  11:     0x55e9fb8fbb01 - <nu_protocol::signature::Predeclaration as nu_protocol::engine::command::Command>::run::hcf0650133b43c86e
  12:     0x55e9fb4438fd - nu_engine::eval::eval_call::h4dbe1f2abf9a38a2
  13:     0x55e9fb44974e - nu_engine::eval::eval_expression_with_input::h410485afbabc01b8
  14:     0x55e9fb449d26 - nu_engine::eval::eval_element_with_input::h6376a31af5163b89
  15:     0x55e9fb44afad - nu_engine::eval::eval_block::h42d1849900714f06
  16:     0x55e9fb44ac5e - nu_engine::eval::eval_block_with_early_return::h48aea6f98c4de596
  17:     0x55e9fb444439 - nu_engine::eval::eval_call::h4dbe1f2abf9a38a2
  18:     0x55e9fb44974e - nu_engine::eval::eval_expression_with_input::h410485afbabc01b8
  19:     0x55e9fb449d26 - nu_engine::eval::eval_element_with_input::h6376a31af5163b89
  20:     0x55e9fb44afad - nu_engine::eval::eval_block::h42d1849900714f06
  21:     0x55e9fb44ac5e - nu_engine::eval::eval_block_with_early_return::h48aea6f98c4de596
  22:     0x55e9fb07ddc8 - nu_cli::util::eval_source::he5fefce78c942d30
  23:     0x55e9fb04d03b - nu_cli::eval_file::evaluate_file::h9f3d32681475b12d
  24:     0x55e9fb023985 - nu::run::run_file::h92f4db049085af77
  25:     0x55e9fb0328e2 - nu::main::h335c604ea4943b6b
  26:     0x55e9fb01fa7a - std::sys_common::backtrace::__rust_begin_short_backtrace::hccff6108e01f8ae1
  27:     0x55e9fb01fa85 - std::rt::lang_start::{{closure}}::h36b1955fce03ffb8
  28:     0x55e9fbabcf35 - std::rt::lang_start_internal::h8ab23524475b2279
  29:     0x55e9fb033675 - main
  30:     0x7fc5fc9edace - __libc_start_call_main
  31:     0x7fc5fc9edb89 - __libc_start_main@@GLIBC_2.34
  32:     0x55e9faf17565 - _start
  33:                0x0 - <unknown>
```

### How to reproduce

Write the following to a file called `repro.nu`
```nu
#!/usr/bin/env nu

def main [] {
  somefunc "foo"
}

def somefunc [
  somearg: file
] {
  echo $somearg
}
```

Run `./repro.nu`

### Expected behavior

The script to print the following and exit cleanly.
```console
foo
```

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.84.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.1                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by aidalgol** [comment]
I have since realised the type I meant is `path`, not `file`, but Nushell should not panic.

**Comment by aidalgol** [comment]
I think it might be the same bug.  Someone on the Nushell Discord server just reported getting this exact error from a Nushell script that should have produced an error.  It's starting to look like a bug in Nushell's error reporting.

**Comment by amtoine** [comment]
yeah, replacing the wrong `file` type with `path` fixes the issue :+1: 
but Nushell should not panic :ok_hand:
