### ISSUE TITLE
`glob *` expands the current directory's files.  `glob ./*` does not.

### ISSUE THREAD

**Issue by Taywee** [nushell/nushell#10181]
### Describe the bug

`glob ./*` always expands to nothing for me.

### How to reproduce

```nushell
> cd (mktemp -d)

> touch alpha beta gamma

> ls
╭───┬───────┬──────┬──────┬──────────╮
│ # │ name  │ type │ size │ modified │
├───┼───────┼──────┼──────┼──────────┤
│ 0 │ alpha │ file │  0 B │ now      │
│ 1 │ beta  │ file │  0 B │ now      │
│ 2 │ gamma │ file │  0 B │ now      │
╰───┴───────┴──────┴──────┴──────────╯

> glob *
╭───┬───────────────────────────╮
│ 0 │ /tmp/tmp.OiKXtVB65u/gamma │
│ 1 │ /tmp/tmp.OiKXtVB65u/beta  │
│ 2 │ /tmp/tmp.OiKXtVB65u/alpha │
╰───┴───────────────────────────╯

> glob ./*
╭────────────╮
│ empty list │
╰────────────╯
```

### Expected behavior

I expect `glob *` to be roughly the same output as `glob ./*`.

### Configuration

| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.84.1                                                     |
| branch             | main                                                       |
| commit_hash        | 7d6b23ee2fd8ce87cef2f28b241d834eb0022c43                   |
| build_os           | linux-x86_64                                               |
| build_target       | x86_64-unknown-linux-gnu                                   |
| rust_version       | rustc 1.72.0 (5680fa18f 2023-08-23) (Fedora 1.72.0-1.fc38) |
| cargo_version      | cargo 1.72.0                                               |
| build_time         | 2023-08-31 18:01:42 -06:00                                 |
| build_rust_channel | debug                                                      |
| allocator          | standard                                                   |
| features           | default, sqlite, trash, which, zip                         |
| installed_plugins  |                                                            |

**Comment by fdncred** [comment]
We'd accept a PR to help with this.

**Comment by bobhy** [comment]
Doesn't repro for me on linux with nu 85.1, not much newer than yours, @Taywee .
Could there be some other difference in environment?

**Comment by fdncred** [comment]
We also just upgraded the wax version that glob uses from 0.5 to 0.6 and this could've been fixed there as well.

**Comment by amtoine** [comment]
i can't repro this either, let's close this issue as completed then :pray: 

@Taywee, please reopen this issue if you happen to reproduce the bug on `0.85.1` :wink:
