### ISSUE TITLE
from-xlsx command

### ISSUE THREAD

**Issue by Tembocs** [nushell/nushell#1018]
The new Nushell 0.6.0 has the f`rom-xlsx` command. I tried to do the following.
`open some_excel_file.xlsx | from-xlsx`

I did get the following error message.
`error: Expected binary data from pipeline.`

What is the proper way to use it? I cannot find any documentation on the proper way to use it. I know this is an early release. I'm on Windows 10 x64.

**Comment by jonathandturner** [comment]
You can use `open some_excel_file.xlsx` and it will do the import automatically. `from-xslx` is the command it will call for you (rather than having to do it manually)

**Comment by jonathandturner** [comment]
Closing, though we probably want to give a better error message for the above case, as the auto-import is surprising if you're not expecting it.
