### ISSUE TITLE
Repology badge is out of date for crates.io

### ISSUE THREAD

**Issue by sagis-tikal** [nushell/nushell#1019]
**Describe the bug**
The Repology badge still shows that crates.io has version 0.5.0 even though it's been updated to 0.6.0.

![image](https://user-images.githubusercontent.com/46102019/69701121-d9c74000-10f4-11ea-8937-ce9c8c7b11fa.png)

I'm pretty sure you guys can't do anything to fix it, but maybe use a different provider who has better data :)

**Comment by jonathandturner** [comment]
Should be up to date now.
