### ISSUE TITLE
Generating plugin signature without running full nushell would be useful

### ISSUE THREAD

**Issue by viraptor** [nushell/nushell#10198]
### Related problem

I'm trying to create a configuration in nixpkgs/home-manager where I'd list both nushell and some plugins declaratively. Unfortunately it seems like the only way to register a plugin is to run `register ...` in `nu` itself. Alternatively, a slightly hacky workaround is `nu --plugin-config /tmp/some/path -c "register /plugin/path"` and merging those files. But if I understand correctly, that loads the whole usual user config/environment. I tried using `nu --no-config-file --plugin-config /tmp/some/path`, but that results in:
```
print $nu
...
│ plugin-path        │ IOError("Could not get plugin signature location")              │
```

### Describe the solution you'd like

Ideally, I'd like to be able to get the plugin signatures in a simpler way and just merge them into the config file automatically. For example:
`nu --plugin-signature /some/path/to/plugin`
Which would generate the signature on stdout for manual processing

**Comment by amtoine** [comment]
i see this error when looking at `$nu.plugin-path` :open_mouth: 

i think the plugin registration and loading might need a bit of love :thinking:

**Comment by fdncred** [comment]
I think that launching `nu -n --no-stdlib` and not being able to do `$nu.plugin-path` is a bug that needs to be fixed.

**Comment by fdncred** [comment]
I threw up this PR real quick if you want to test it https://github.com/nushell/nushell/pull/10201
