### ISSUE TITLE
commandline command not working in Alacritty

### ISSUE THREAD

**Issue by marwal-88** [nushell/nushell#10195]
### Describe the bug

The command 'commandline' is not sending any text to the command-line buffer when using Alacritty. Switching to xfce4-terminal solves that problem.

### How to reproduce

1. Open Alacritty terminal.
2. type: nu<enter>
3. type: commandline "nothing to see here"

### Expected behavior

Expected result is: "Nothing to see here" on the commandline.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.84.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | d2abb8603abab43ec4a6d4ed56f9018790b99dce                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (Arch Linux rust 1:1.71.1-1) |
| cargo_version      | cargo 1.71.1                                                     |
| build_time         | 2023-08-23 02:21:39 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment]
No issues for me with alacritty
<img width="992" alt="image" src="https://github.com/nushell/nushell/assets/343840/52d79829-8dca-4979-a9e8-2e6cb27d30ad">

**Comment by amtoine** [comment]
i cannot reproduce this either

## Nushell
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.84.1                                   |
| branch             | main                                     |
| commit_hash        | d28f728787897bd8656b3e829e02a6d2540ba5dc |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)      |
| rust_channel       | 1.70.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)      |
| build_time         | 2023-09-01 19:05:39 +02:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | explore                                  |

## alacritty
```
alacritty 0.13.0-dev (bd490672)
```

**Comment by marwal-88** [comment]
As of today: neither can I.
For two days it didn't work :)
