### ISSUE TITLE
query web seems to be returning some cells incorrectly

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#10194]
### Describe the bug

If you try this one-liner, you'll get an output that doesn't match the [web page](https://uutils.github.io/coreutils/book/platforms.html) quite right. Notice that some of the `ch*` commands on Windows have a 1, when they should have a 0. This may be a problem with `query web`.

```nushell
http get https://uutils.github.io/coreutils/book/platforms.html |
  query web -t [util Linux macOS Windows FreeBSD Android] |
  update cells -c [Linux macOS Windows FreeBSD Android] {|v|
    if ($v | str trim) =~ "✓" { 1 } else { 0 }
  }
╭─#─┬───util────┬Linux┬macOS┬Windows┬FreeBSD┬Android╮
│0  │arch       │    1│    1│      1│      1│      1│
│1  │b2sum      │    1│    1│      1│      1│      1│
│2  │b3sum      │    1│    1│      1│      1│      1│
│3  │base32     │    1│    1│      1│      1│      1│
│4  │base64     │    1│    1│      1│      1│      1│
│5  │basename   │    1│    1│      1│      1│      1│
│6  │basenc     │    1│    1│      1│      1│      1│
│7  │cat        │    1│    1│      1│      1│      1│
│8  │chcon      │    1│    0│      0│      0│      0│
│9  │chgrp      │    1│    1│      1│      1│      0│
│10 │chmod      │    1│    1│      1│      1│      0│
│11 │chown      │    1│    1│      1│      1│      0│
│12 │chroot     │    1│    1│      1│      1│      0│
...
```

### How to reproduce

See above

### Expected behavior

If the cell has "Missing blah blah" it should not be equal to "✓" and therefore should not be returned as a 1. This is what the table looks like before the `update cells`. The ch* for Windows commands are empty on the webpage. I'm not sure what is going on.

```nushell
http get https://uutils.github.io/coreutils/book/platforms.html | query web -t [util Linux macOS Windows FreeBSD Android]
╭─#─┬───util────┬Linux┬─────────macOS─────────┬─────────Windows─────────┬─────────FreeBSD─────────┬─────────Android─────────╮
│0  │arch       │✓    │✓                      │✓                        │✓                        │✓                        │
│1  │b2sum      │✓    │✓                      │✓                        │✓                        │✓                        │
│2  │b3sum      │✓    │✓                      │✓                        │✓                        │✓                        │
│3  │base32     │✓    │✓                      │✓                        │✓                        │✓                        │
│4  │base64     │✓    │✓                      │✓                        │✓                        │✓                        │
│5  │basename   │✓    │✓                      │✓                        │✓                        │✓                        │
│6  │basenc     │✓    │✓                      │✓                        │✓                        │✓                        │
│7  │cat        │✓    │✓                      │✓                        │✓                        │✓                        │
│8  │chcon      │✓    │Missing column: 'macOS'│Missing column: 'Windows'│Missing column: 'FreeBSD'│Missing column: 'Android'│
│9  │chgrp      │✓    │✓                      │✓                        │✓                        │Missing column: 'Android'│
│10 │chmod      │✓    │✓                      │✓                        │✓                        │Missing column: 'Android'│
│11 │chown      │✓    │✓                      │✓                        │✓                        │Missing column: 'Android'│
│12 │chroot     │✓    │✓                      │✓                        │✓                        │Missing column: 'Android'│
```

Oh, wait! There are checkmarks there. So maybe it's a `query web` problem?

### Configuration

|key|value|
|-|-|
|version|0.84.1|
|branch|main|
|commit_hash|d28f728787897bd8656b3e829e02a6d2540ba5dc|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.70.0 (90c541806 2023-05-31)|
|rust_channel|1.70.0-aarch64-apple-darwin|
|cargo_version|cargo 1.70.0 (ec8a8a0ca 2023-04-25)|
|build_time|2023-09-01 16:11:23 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|dataframe, default, extra, sqlite, trash, which, zip|
|installed_plugins|emoji, file, from eml, from ics, from ini, from parquet, from plist, from vcf, gstat, highlight, hist, inc, json path, periodic-table, plot, pnet, query, query json, query web, query xml, regex, str bexpand, str similarity, xyplot|

**Comment by fdncred** [comment]
It appears that what is going on is that the table code is returning wrong. You can see there that it says "Missing" in the Android column, but that's not right.

```
│8  │chcon      │✓    │Missing column: 'macOS'│Missing column: 'Windows'│Missing column: 'FreeBSD'│Missing column: 'Android'│
│9  │chgrp      │✓    │✓                      │✓                        │✓                        │Missing column: 'Android'│
│10 │chmod      │✓    │✓                      │✓                        │✓                        │Missing column: 'Android'│
│11 │chown      │✓    │✓                      │✓                        │✓                        │Missing column: 'Android'│
│12 │chroot     │✓    │✓                      │✓                        │✓                        │Missing column: 'Android'│
```

Using the `--inspect` flag, you can see that the table is returning this ```
Passed in Column Headers = [
    "util",
    "Linux",
    "macOS",
    "Windows",
    "FreeBSD",
    "Android",
]
Table Found = [
    WebTable {
        headers: {
            "macOS": 2,
            "Android": 5,
            "Windows": 3,
            "Linux": 1,
            "util": 0,
            "FreeBSD": 4,
        },
        data: [
            [
                "arch",
                "✓",
                "✓",
                "✓",
                "✓",
                "✓",
            ],
            [
                "b2sum",
                "✓",
                "✓",
                "✓",
                "✓",
                "✓",
            ],
            [
                "b3sum",
                "✓",
                "✓",
                "✓",
                "✓",
                "✓",
            ],
            [
                "base32",
                "✓",
                "✓",
                "✓",
                "✓",
                "✓",
            ],
            [
                "base64",
                "✓",
                "✓",
                "✓",
                "✓",
                "✓",
            ],
            [
                "basename",
                "✓",
                "✓",
                "✓",
                "✓",
                "✓",
            ],
            [
                "basenc",
                "✓",
                "✓",
                "✓",
                "✓",
                "✓",
            ],
            [
                "cat",
                "✓",
                "✓",
                "✓",
                "✓",
                "✓",
            ],
            [
                "chcon",
                "✓",
            ],
            [
                "chgrp",
                "✓",
                "✓",
                "✓",
                "✓",
            ],
            [
                "chmod",
                "✓",
                "✓",
                "✓",
                "✓",
            ],
            [
                "chown",
                "✓",
                "✓",
                "✓",
                "✓",
            ],
            [
                "chroot",
                "✓",
                "✓",
                "✓",
                "✓",
            ],
``` 
Notice that the ch* commands above, it has 4 checks in a row. It should 2 checks, one blank, 2 checks.

**Comment by jameschensmith** [comment]
@fdncred, I believe I'm running into this same issue. I believe the issue is that `query web` isn't handling empty `<td>` tags.

Here's a minimal reproducible example:

Happy path, where the table has data in every cell:

```
$ [[a b c]; [1 2 3] [4 5 6]] | to html --partial | query web --as-table [a b c]
╭───┬───┬───┬───╮
│ # │ a │ b │ c │
├───┼───┼───┼───┤
│ 0 │ 1 │ 2 │ 3 │
│ 1 │ 4 │ 5 │ 6 │
╰───┴───┴───┴───╯
```

Bug, where cell `b.0` is `null`:

```
$ [[a b c]; [1 null 3] [4 5 6]] | to html --partial | query web --as-table [a b c]
╭───┬───┬───┬─────────────────────╮
│ # │ a │ b │          c          │
├───┼───┼───┼─────────────────────┤
│ 0 │ 1 │ 3 │ Missing column: 'c' │
│ 1 │ 4 │ 5 │ 6                   │
╰───┴───┴───┴─────────────────────╯
```

Expected (or, at least desired) output:

```
$ [[a b c]; [1 null 3] [4 5 6]] | to html --partial | query web --as-table [a b c]
╭───┬───┬───┬───╮
│ # │ a │ b │ c │
├───┼───┼───┼───┤
│ 0 │ 1 │   │ 3 │
│ 1 │ 4 │ 5 │ 6 │
╰───┴───┴───┴───╯
```

Hopefully this can help figure out what's going on ☺️
