### ISSUE TITLE
`complete` give an error when given `null` as input in a hook

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#10204]
might be related to
- https://github.com/nushell/nushell/issues/9738

### Describe the bug
i mean, it's super weird, let me show you how to reproduce it :open_mouth:

### How to reproduce

1. save the following in a file called `foo.nu`
```nushell
def get-git-repo-dir [dir: path]: nothing -> path {
    do -i { git -C $dir rev-parse --show-toplevel } | complete | get stdout | str trim
}

$env.config.hooks = {
    env_change: {
        PWD: [
            {|before, _| get-git-repo-dir $before}
        ]
    }
}
```
2. run `nu --config foo.nu`
3. get the following error
```
Error:   × Complete only works with external streams
   ╭─[/home/amtoine/foo.nu:1:1]
 1 │ def get-git-repo-dir [dir: path]: nothing -> path {
 2 │     do -i { git -C $dir rev-parse --show-toplevel } | complete | get stdout | str trim
   ·                                                       ────┬───
   ·                                                           ╰── complete only works on external streams
 3 │ }
   ╰────
```
4. add a guard to not run `get-git-repo-dir` when the shell starts, i.e. the only time when `before` is `null`
```nushell
def get-git-repo-dir [dir: path]: nothing -> path {
    do -i { git -C $dir rev-parse --show-toplevel } | complete | get stdout | str trim
}

$env.config.hooks = {
    env_change: {
        PWD: [
            {|before, _|
                if $before == null {
                    return
                }

                get-git-repo-dir $before
            }
        ]
    }
}
```
5. it works fine

### Expected behavior

- the error looks like a runtime one because adding a dummy `print` before the call to `get-git-repo-dir` in the first failing case would print both the dummy thing and the error
- i get that this error comes from the fact that `before` is `null` when the shell starts but the error is a bit confusing :thinking: 

i expected something more like what one can get in the REPL
```
Error: nu::parser::type_mismatch

  × Type mismatch.
   ╭─[entry #3:1:1]
 1 │ get-git-repo-dir null
   ·                  ──┬─
   ·                    ╰── expected string, found nothing
   ╰────
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.84.1                                   |
| branch             | main                                     |
| commit_hash        | af79eb294333c09e464e099ffb19f2e000cd1d52 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)      |
| rust_channel       | 1.70.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)      |
| build_time         | 2023-09-03 12:03:46 +02:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | explore, gstat                           |

**Comment by KAAtheWiseGit** [comment]
This one is tricky.  The issue is that the error which happens inside `do` is suppressed with `-i`, which is `--ignore-errors`.  So, the `do` block returns the value `nothing`, which, of course, is not a raw input, which causes `complete` to send this error.

Removing `-i`, together with the fix I will submit in a moment, will fix the error:

```Nushell
Error: nu::shell::external_command

  × External command failed
   ╭─[/home/kaathewise/fork/nushell/foo.nu:1:1]
 1 │ def get-git-repo-dir [dir: path]: nothing -> path {
 2 │     do { git -C $dir rev-parse --show-toplevel } | complete | get stdout | str trim
   ·                 ──┬─
   ·                   ╰── Cannot convert nothing to a string
 3 │ }
   ╰────
  help: All arguments to an external command need to be string-compatible
```
