### ISSUE TITLE
`config nu` fails due to mysterious unquoted path

### ISSUE THREAD

**Issue by Poyo-SSB** [nushell/nushell#10205]
### Describe the bug

Running the `config nu` command fails because nushell appears to be looking for an executable in `C:/Program Files` or similar but parses the path incorrectly, or something like that.

### How to reproduce

1. Have an affected system?
2. Run `config nu`.

### Expected behavior

`config nu` should open `config.nu`.

### Screenshots

![image](https://github.com/nushell/nushell/assets/1782081/928cf6bf-f2ad-4cc4-903c-0c4112d835dd)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.84.0                                   |
| branch             |                                          |
| commit_hash        | d2abb8603abab43ec4a6d4ed56f9018790b99dce |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)      |
| rust_channel       | 1.69.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)      |
| build_time         | 2023-08-22 21:20:58 +00:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by Salted-Fish-Swimming** [comment]
It may be about space in your win's path , you can try make your default editor in a path without spaces and modify environment `$env.EDITOR` or `$env.VISUAL` like [this](http://www.nushell.sh/book/configuration.html#configurations-with-built-in-commands) .
