### ISSUE TITLE
Issue compiling heim-common

### ISSUE THREAD

**Issue by sagis-tikal** [nushell/nushell#1021]
**Describe the bug**
Nushell 0.6.0 doesn't compile because of heim-common

**To Reproduce**
1. Run the command `cargo install nu`
2. Wait.
3. Check out the compilation error

**Expected behavior**
I expected nushell to be successfully installed

**Screenshots**
![image](https://user-images.githubusercontent.com/46102019/69707041-a3dc8880-1101-11ea-91a7-0aee150fab0a.png)

**Configuration (please complete the following information):**
 - OS: Manjaro Linux
 - Version 0.6.0
 - No additional features activated

[Heim issue #182 ](https://github.com/heim-rs/heim/issues/182)

**Comment by alvitawa** [comment]
Same here, regardless of the features used (heim is actually only needed for the ps and sys features).

**Comment by est31** [comment]
Upstream rust issue: https://github.com/rust-lang/rust/issues/66757

**Comment by jonathandturner** [comment]
This was fixed a while ago, closing
