### ISSUE TITLE
Config & env not loaded when executing command via ssh on system with nushell as login shell

### ISSUE THREAD

**Issue by lizclipse** [nushell/nushell#10219]
### Describe the bug

If you set `nu` as the login shell on a system, then try to execute a command directly via ssh, then the config/env is seemingly not loaded, thus things like the PATH are not configured properly (meaning that all installed commands are not available).

This can be most easily seen when outputting the PATH when in an ssh session vs directly:

<details>
<summary>SSH Session</summary>

```
> ssh remote
> $env.PATH
╭────┬─────────────────────────────────────────────────────────────────╮
│  0 │ /opt/homebrew/bin                                               │
│  1 │ /Users/liz/.pnpm                                                │
│  2 │ /Users/liz/.go/bin                                              │
│  3 │ /Users/liz/.deno/bin                                            │
│  4 │ /Users/liz/.local/bin                                           │
│  5 │ /Users/liz/.cargo/bin                                           │
│  6 │ /Users/liz/.dotnet/tools                                        │
│  7 │ /Users/liz/.bun/bin                                             │
│  8 │ /Applications/Visual Studio Code.app/Contents/Resources/app/bin │
│  9 │ /usr/bin                                                        │
│ 10 │ /bin                                                            │
│ 11 │ /usr/sbin                                                       │
│ 12 │ /sbin                                                           │
╰────┴─────────────────────────────────────────────────────────────────╯
```

</details>

<details>
<summary>SSH command</summary>

```
> ssh remote '$env.PATH'
╭───┬───────────╮
│ 0 │ /usr/bin  │
│ 1 │ /bin      │
│ 2 │ /usr/sbin │
│ 3 │ /sbin     │
╰───┴───────────╯
```

</details>

Running the same command via `ssh remote -t '$env.PATH'` has the same result. This mostly causes issues when you have more modern versions of programs installed over the pre-existing ones, e.g. I have `rsync` installed via homebrew as the Mac-native one is woefully out of date, but when I have `nu` as my login shell, trying to run `rsync` between my local and remote machine results in weird errors, as it's using the older, pre-installed version instead of the one I actually want.

### How to reproduce

1. Have 2 machines
2. Set remote login shell to `nu`
3. From local machine, execute command on remote via `ssh remote <command>` that's only accessible via a custom PATH

### Expected behavior

The config and env should be loaded properly to allow access to commands via direct ssh.

### Configuration

Both machines are using `nu` as the current shell (local isn't set as login shell, but is the default in my terminal emulator).

# Local
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.84.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.2 (1a737af0c 2023-08-07)                               |
| build_time         | 2023-08-22 21:09:23 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | dataframe, default, sqlite, trash, which, zip                     |
| installed_plugins  |                                                                   |

# Remote
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.84.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.2 (1a737af0c 2023-08-07)                               |
| build_time         | 2023-08-22 21:09:23 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | dataframe, default, sqlite, trash, which, zip                     |
| installed_plugins  |                                                                   |

**Comment by amtoine** [comment]
this might be related to Nushell not loading the configuration when running scripts.
but here you might not be able to force the remote Nushell instance to load the config, right? :thinking: 

possibly related to
- https://github.com/nushell/nushell/issues/9833

**Comment by lizclipse** [comment]
Well, theoretically you can do something like 

```
ssh studio "/opt/homebrew/bin/nu --config $nu.config-path --env-config $nu.env-path -c 'print $env.PATH'"
```

but it doesn't support quite the same syntax and is not compatible with anything that's going to use ssh. You (or at least I) have to use the full path of `nu` because it's in a homebrew install, which isn't on the path due to this issue lol. Personally, I'd call it a 'fun side-track', but it's not a solution by any means.

**Comment by lizclipse** [comment]
I've just re-tested this, and it seems in the last version or 2 it's been fixed! At least on macOS & Arch Linux, nu seems to work fine as the login shell over SSH now.

**Comment by lizclipse** [comment]
I've tested this again and it looks like the explicit `ssh remote -t '$env.PATH'` is still broken (my mistake), but I can't figure out a way to force the new `-l` to be used when setting the login shell. You can now do `ssh remote -t '/opt/homebrew/bin/nu -l -c "$env.PATH"'`, which is much easier than before, but still not working and I'm not sure why. I remember reading somewhere that the env and config files aren't loaded when executing a command directly, but I'm not sure why or if there's a way around it, but it feels like there should be a way to configure the path when not in REPL mode.

**Comment by fdncred** [comment]
I believe `nu -l` loads configs now. You can see that doing something like `nu -l -c "ls" --log-level debug` and you'll see some log statements that show the config files being loaded.

**Comment by lizclipse** [comment]
The issue is that login shells are brought up without any arguments from my understanding, so there isn't a way to force the `-l` option when executing a command via ssh. I suppose the issue here is that when executing a command via `ssh remote '...cmd...'` you aren't actually opening a login shell experience, so it just doesn't load the env config. If there was a way to make nu always load some config regardless (similar to how bash always loads `.bashrc`) then you could workaround this issue.

**Comment by lizclipse** [comment]
I've written a little workaround for this in case someone else is having the same issue:
```nushell
export def ssh-exec [host: string, cmd: string --tty (-t), ...rest: string]: nothing -> string {
    let macNu = "/opt/homebrew/bin/nu"
    let linuxNu = "/home/linuxbrew/.linuxbrew/bin/nu"
    ssh $host ...$rest $"^$\"\(if \('($macNu)' | path exists) { '($macNu)' } else { '($linuxNu)' })\" -l -c '($cmd)'"
}
```

It is _very_ hacky, but does work. It's not perfect (nu swallows flags it seems, so you have to wrap them in strings), but it works.

I have had some ideas about this, though. I think some mechanism to specify default flags via either an env var like `NU_DEFAULT_FLAGS` or a file (`~/.config/nushell/default_flags`) would be the most generic solution, and allow for things like giving different config/env file locations, configuring the threads, always allows scripts to access stdin, and allowing for `-l` to always treat nu as a login shell. It could be really useful, and I'd be willing to try my hand at an implementation if this was something that seems like a good idea.

**Comment by ofek** [comment]
We are also encountering this with our new developer environments.

**Comment by ofek** [comment]
Has there been any update on this?

**Comment by theoparis** [comment]
I think I just encountered this issue with a remote builder using Nix when the login shell is set to nu on the remote machine 😕

**Comment by atahrijouti** [comment]
Could add to it that scripts in autoload folders don't seem to register either when `-l` is provided

**Comment by lizclipse** [comment]
A while ago I did figure out a better workaround that's still not ideal - I have a script called `~/.local/bin/nu-login` with the following contents:

```sh
#!/bin/sh
if [ -f "/opt/homebrew/bin/nu" ]; then
  exec /opt/homebrew/bin/nu -l "$@"
else
  exec /home/linuxbrew/.linuxbrew/bin/nu -l "$@"
fi
```

If I set that script as my login shell then nushell will always launch, even through SSH, with all the right configs loaded (including autoloads for me). I doubt this is secure in any way, but so far it's been working fairly well. My feeling is that if there was a way for nushell to detect that it's being run as a login shell then it should implicitly set `--login` (as that should just fix this issue entirely) but how to actually do that is beyond my Expertise. Bash seems to have a `--login` option similar to nushell that I assume is set implicitly when run as a login shell, so maybe checking the source of an implementation could lead to something useful.

**Comment by ofek** [comment]
For those looking to contribute, what is the root cause of this issue and the recommended fix?

**Comment by lizclipse** [comment]
While this might need input from others, my view is that the root cause is that nushell does not implicitly enable `--login` when run as the user's login shell, and the fix is for it to... do that.

I'm not quite a shell master so I dont know exactly how best to detect this case. In *nix systems, it seems that the `SHELL` envvar is always sat to the path of the current login shell, even when that's set to nu (or my wrapper script, ie I see `$env.SHELL == /Users/liz/.local/bin/nu-login`), but I'm not sure if there's anything else you can use to detect this case, it's not exactly something many programs are in the position of doing so I've struggled to find much documentation or examples. I also have literally no idea how the Windows case would work (and personally dont ever want to touch the OS ever again), but I dont even know if you can set a "login shell" on Windows like you can on *nix systems.

I would be a willing guinea pig if someone wanted to implement this and wanted testers. I use nu as login shells on pretty much all my machines, which span macOS and Fedora currently, so it should help make sure it's working as expected across envs. I have other machines that I dont use often but are other distros (at least 2 Raspbian ones), so I could set nu as login shells on them to test if needed.
