### ISSUE TITLE
Better handling multiline external commands

### ISSUE THREAD

**Issue by detrin** [nushell/nushell#10228]
### Describe the solution you'd like

Imagine we have simple bash script

```bash
# example.sh
#/bin/bash

echo "Hello World! "$1 
sleep 3
echo "Goodbye World! "$2
```

and we want to run it as multiline command in nushell. The only way I know we are supposed to do it is with `()`
```nushell
(./example 1
                   2)
```
however this execution will output everything only after the whole bash script is done. Which is not practical.

### Additional context and details

Why is this relevant? Well, yesterday I tried to use nushell for the whole day and I wanted to build python v3.12.0rc1 for testing. However I came across this inconvenience when executing
```nushell
(GDBM_CFLAGS="-I$(brew --prefix gdbm)/include" 
GDBM_LIBS="-L$(brew --prefix gdbm)/lib -lgdbm" 
./configure --with-pydebug --with-openssl="$(brew --prefix openssl@3.1)")
```
this simply won't show the whole output until the script is done. I think this issue is relevant for nushell to be adopted in industry.

**Comment by detrin** [comment]
@amtoine of course you are right and thank you I have learned something new about nushell again. However, when having multiline command (which is fairly common) it is still an issue.

**Comment by schrieveslaach** [comment]
Working with QEMU will get you into long list of arguments too. For example, [emulating a Raspberry PI](https://blog.ramdoot.in/emulating-raspberry-pi-on-with-qemu-951283daf2bd) will be harder to read if you don't be able to use multiline command in scripts.

```nu
qemu-system-aarch64 -M raspi3b -display none -append "rw earlyprintk loglevel=8 console=ttyAMA0,115200 dwc_otg.lpm_enable=0 root=/dev/mmcblk0p2 rootdelay=1" -dtb ./dtbs/bcm2710-rpi-3-b-plus.dtb -sd raspios.qcow -kernel kernel8.img -m 1G -smp 4 -serial mon:stdio -usb -device usb-mouse -device usb-kbd -device usb-net,netdev=net0 -netdev user,id=net0,hostfwd=tcp::5555-:22
```

**Comment by amtoine** [comment]
@schrieveslaach 
i learned not so long ago that you should be able to write something like the following :smirk:
```nushell
qemu-system-aarch64 [
    -M raspi3b
    -display none
    -append "rw earlyprintk loglevel=8 console=ttyAMA0,115200 dwc_otg.lpm_enable=0 root=/dev/mmcblk0p2 rootdelay=1"
    -dtb ./dtbs/bcm2710-rpi-3-b-plus.dtb
    -sd raspios.qcow
    -kernel kernel8.img
    -m 1G
    -smp 4
    -serial mon:stdio
    -usb
    -device usb-mouse
    -device usb-kbd
    -device usb-net,netdev=net0
    -netdev user,id=net0,hostfwd=tcp::5555-:22
]
```

> **Note**
> see [`nupm test`](https://github.com/nushell/nupm/blob/4f7c1013999e2a2544703c84ae811adcdca5776e/nupm/test.nu#L37-L41) for a real example

**Comment by schrieveslaach** [comment]
@amtoine, thanks for pointing out. However, this only works if I wrap all args inside the array as strings:

```nu
qemu-system-aarch64 [
    "-M" "raspi3b"
    "-display" "none"
    "-append" "rw earlyprintk loglevel=8 console=ttyAMA0,115200 dwc_otg.lpm_enable=0 root=/dev/mmcblk0p2 rootdelay=1"
    "-dtb" "./dtbs/bcm2710-rpi-3-b-plus.dtb"
    "-sd" "raspios.qcow"
    "-kernel" "kernel8.img"
    "-m" "1G"
    "-smp" "4"
    "-serial" "mon:stdio"
    "-usb"
    "-device" "usb-mouse"
    "-device" "usb-kbd"
    "-device" "usb-net,netdev=net0"
    "-netdev" "user,id=net0,hostfwd=tcp::5555-:22"
]
```

IMHO this is quite tedious to type.

**Comment by amtoine** [comment]
@schrieveslaach 
mm this is strange because the following works for me
```nushell
> nu [--no-config-file --no-std-lib --table-mode none --commands ls]
 #     name      type     size       modified
 0   LICENSE     file   34.3 KiB   9 months ago
 1   README.md   file    9.1 KiB   5 days ago
 2   documents   dir     4.0 KiB   a month ago
 3   downloads   dir     4.0 KiB   4 days ago
 4   media       dir     4.0 KiB   9 months ago
 5   snap        dir     4.0 KiB   9 months ago
```

does this work for you?

if not, what version are you using?
i'm on the latest revision of Nushell, from source :+1:

**Comment by schrieveslaach** [comment]
@amtoine, sorry for the late response (I was working on other stuff).

One thing I forgot in the example are the arguments `-serial null`

```
qemu-system-aarch64 [
    "-M" "raspi3b"
    "-display" "none"
    "-append" "rw earlyprintk loglevel=8 console=ttyAMA0,115200 dwc_otg.lpm_enable=0 root=/dev/mmcblk0p2 rootdelay=1"
    "-dtb" "./dtbs/bcm2710-rpi-3-b-plus.dtb"
    "-sd" "raspios.qcow"
    "-kernel" "kernel8.img"
    "-m" "1G"
    "-smp" "4"
    "-serial" "mon:stdio"
    "-usb"
    "-device" "usb-mouse"
    "-device" "usb-kbd"
    "-device" "usb-net,netdev=net0"
    "-netdev" "user,id=net0,hostfwd=tcp::5555-:22"
   -serial null
]
```

That fails with the recent nu release (0.89.0) telling me that null cannot be converted into string. Wrapping that into a string works then fine.

**Comment by IanManske** [comment]
In version 0.92, output from external commands wrapped in parentheses should be streamed where possible (instead of collected).
