### ISSUE TITLE
Make Github releases uniform

### ISSUE THREAD

**Issue by nightscape** [nushell/nushell#1023]
I've installed nushell via [scoop](http://scoop.sh/).
Scoop auto-updates packages when there's a new Github release, but in order to do so each package description makes some assumptions how the release page looks like.
Here's the relevant part of nushell's package description:

```json
{
    "checkver": {
        "github": "https://github.com/nushell/nushell",
        "regex": "([\\d.]+) Release</a>"
    },
    "autoupdate": {
        "url": "https://github.com/nushell/nushell/releases/download/$underscoreVersion/nu_$underscoreVersion_windows.zip",
        "extract_dir": "nushell_$underscoreVersion"
    }
}
```
You can see that the `checkver.regex` for matching a version used to be spelled with a capital `R` but in 0.6.0 it's written `0.6.0 release` with a small `r`. This is of course easy to fix in the regex.
What's harder to circumvent is that the download path changed from
```
https://github.com/nushell/nushell/releases/download/0_5_0/nu_0_5_0_windows.zip
```
to
```
https://github.com/nushell/nushell/releases/download/0.6.0/nu_0_6_0_windows.zip
```
(`.` instead of `_` as version separator).

It would be great if for releases a common spelling and download location schema could be used then the update process for Windows users will be fast and easy 😃

**Comment by jonathandturner** [comment]
I'll try to keep it consistently "<version> release" and name the releases with dots in the future.
