### ISSUE TITLE
the binary influxdb_iox crashes inside nushell when the nu-std lib is included

### ISSUE THREAD

**Issue by stormasm** [nushell/nushell#10248]
### Describe the bug

https://github.com/influxdata/influxdb_iox

influxdb_iox crashes inside nushell when log.nu is included in the std library...

something inside log.nu is causing the binary to crash and this will probably happen in other
rust binaries as well that have logging code...  there is some type of a clash in the way *log.nu*
sets up the logging system...

### How to reproduce

in *nu-std/src/lib.rs* comment out the loading of the files testing.nu and log.nu

in *nu-std/std/mod.nu* comment out in 2 spots
```rust
use log.nu
```

build influxdb_iox and you will note the binary runs

in a more simple fashion run nushell without the std-lib 
and you will note the influxdb_iox binary does not crash 

### Expected behavior

iox should not crash

### Configuration

on the nushell main branch

**Comment by stormasm** [comment]
https://github.com/stormasm/nushell/tree/stdlib_breaks_iox

This branch fixes the problem / no longer crashes

Note testing.nu is removed simply because it includes log.nu

But "I believe" the issue is probably located in log.nu.

But I am not 100% sure because both have to be removed at the moment.

**Comment by stormasm** [comment]
When iox crashes this is what you see hinting at a logging bug inside log.nu 😄 

```rust
error: invalid value '%ANSI_START%%DATE%|%LEVEL%|%MSG%%ANSI_STOP%' for '--log-format <LOG_FORMAT>': Invalid log format '%ANSI_START%%DATE%|%LEVEL%|%MSG%%ANSI_STOP%'. Valid options: full, pretty, json, logfmt

For more information, try 'help'.
```

**Comment by stormasm** [comment]
Another simple way to test that it crashes with *log.nu*

Is bring up nushell without the std-lib and then include the file

```rust
use log.nu
```

**Comment by fdncred** [comment]
I'm betting it's because we do this in log.nu
```nushell
    $env.LOG_FORMAT = $"%ANSI_START%%DATE%|%LEVEL%|(ansi u)%MSG%%ANSI_STOP%"
```
If we changed it from `$env.LOG_FORMAT` to `$env.NU_LOG_FORMAT` it probably won't error. I've found that this LOG_FORMAT messes some other stuff up too, even simply doing `$env` you can see that things are underlined that don't need to be. Or if you do `$env | to text` way too much stuff is underlined.

@amtoine Any thoughts on this?

**Comment by amtoine** [comment]
yeah we might want to change this very broad and general name to something more Nushelly :yum:
