### ISSUE TITLE
Pass the nushell environment to buffer editor

### ISSUE THREAD

**Issue by weirdan** [nushell/nushell#10241]
### Related problem

I have `$env.NVIM_APPNAME` set to a non-empty value (which makes Neovim use a different set of config directories). This is done in `$nu.env-path`:
```console
$ rg nvim $nu.env-path 

64:$env.NVIM_APPNAME = "lazynvim"
```

`$env.VISUAL`, `$env.EDITOR` and `$env.config.buffer_editor` are all set to `nvim`:

```console
$ [[VISUAL EDITOR buffer_editor NVIM_APPNAME]; [$env.VISUAL $env.EDITOR $env.config.buffer_editor $env.NVIM_APPNAME ]] 

╭───┬────────┬────────┬───────────────┬──────────────╮
│ # │ VISUAL │ EDITOR │ buffer_editor │ NVIM_APPNAME │
├───┼────────┼────────┼───────────────┼──────────────┤
│ 0 │ nvim   │ nvim   │ nvim          │ lazynvim     │
╰───┴────────┴────────┴───────────────┴──────────────╯
```

However, when I press `Ctrl-O`, Neovim starts with the environment inherited by Nushell from the parent process (which doesn't have `NVIM_APPNAME` set).

### Describe the solution you'd like

I believe the buffer editor should inherit Nushell's environment (as modified by Nushell startup scripts).

**Comment by fdncred** [comment]
I'm pretty sure that this is a reedline issue. Ah, @sholderbach has marked it as such. When you do `ctrl+o` it calls `ReedlineEvent::OpenEditor`. That would be a good place to start digging, for anyone who wants to try an implement a change here.

**Comment by crides** [comment]
@weirdan How do you reproduce this? I just tried and I don't seem to have the issue. I just did:
- add `$env.NVIM_APPNAME = "lazynvim"` to my `env.nu`
- start a new shell (in another pane)
- `c-o`
- `:echo $NVIM_APPNAME`: `lazynvim` is then shown

**Comment by fdncred** [comment]
I can't repro this either anymore. Please ping me if it's still an issue.

**Comment by weirdan** [comment]
This appears to be working in 0.88
