### ISSUE TITLE
Document Nu date usage in where

### ISSUE THREAD

**Issue by m-rutter** [nushell/nushell#1024]
**Is your feature request related to a problem? Please describe.**
It is possible to compare dates using `where`.

```sh
 ls | where accessed > 120d
```

However, it doesn't appear to be documented how dates are represented on the RHS of the expression.

**Describe the solution you'd like**
Document all of the ways of representing dates on the RHS

**Describe alternatives you've considered**
If invalid input on the RHS is used maybe list examples of possible input or suggest a help command to list possible options 

**Additional context**
Trying to figure out what is valid input by attempting to use ISO dates:
![Screenshot from 2019-11-27 19-01-51](https://user-images.githubusercontent.com/1534676/69752123-7666fd80-1148-11ea-8393-ebb1d5237d33.png)

**Comment by jonathandturner** [comment]
I've updated the where documentation to include more examples like this: https://github.com/nushell/nushell/blob/master/docs/commands/where.md

I'll close the issue, but please feel free to reopen if what we've added isn't sufficient.

We'd also like to fix being able to pass in date values, though we might want to track that as a separate issue.

**Comment by alex1yaremchuk** [comment]
> I've updated the where documentation to include more examples like this: https://github.com/nushell/nushell/blob/master/docs/commands/where.md
> 
> I'll close the issue, but please feel free to reopen if what we've added isn't sufficient.
> 
> We'd also like to fix being able to pass in date values, though we might want to track that as a separate issue.

The link is broken now, where did they move?
