### ISSUE TITLE
Unable to use css selector with query web + http get

### ISSUE THREAD

**Issue by detrin** [nushell/nushell#10251]
### Describe the bug

I am trying to go over different commands and adapt nushell in my daily life. However, I ran into this issue and since no one responded to my question on discord server I feel like opening the issue here is the right thing to do.

Here is the output from nushell
```
$ http get https://www.csfd.cz/film/1091993-oppenheimer/prehled/ | query web -q "#page-wrapper > div > div.main-movie > aside > div.box-rating-container > div.box-rating.box-rating-withtabs > div.film-rating-average" -m
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #37:1:1]
 1 │ http get https://www.csfd.cz/film/1091993-oppenheimer/prehled/ | query web -q "#page-wrapper > div > div.main-movie > aside > div.box-rating-container > div.box-rating.box-rating-withtabs > div.film-rating-average" -m
   ·                                                                  ──┬──
   ·                                                                    ╰── did you mean 'url join'?
   ╰────
  help: No such file or directory (os error 2)

```

### How to reproduce

1. Install nushell v0.84.0
2. Run command `http get https://www.csfd.cz/film/1091993-oppenheimer/prehled/ | query web -q "#page-wrapper > div > div.main-movie > aside > div.box-rating-container > div.box-rating.box-rating-withtabs > div.film-rating-average" -m`

The particular example doesn't matter so much. However, it was something that was relevant for me to test yesterday. I could do the same in python, however being able to test it directly in nushell would save me some overhead.

### Expected behavior

I just don't know how to use this command `query web` correctly.

### Configuration

```
$ version | transpose key value | to md --pretty                                                                                                 09/06/2023 11:48:57 AM
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.84.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.2 (1a737af0c 2023-08-07)                               |
| build_time         | 2023-08-22 21:09:23 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | dataframe, default, sqlite, trash, which, zip                     |
| installed_plugins  |                                                                   |
```

**Comment by fdncred** [comment]
I get this.
```
❯ http get https://www.csfd.cz/film/1091993-oppenheimer/prehled/ | query web -q "#page-wrapper > div > div.main-movie > aside > div.box-rating-container > div.box-rating.box-rating-withtabs > div.film-rating-average" -m
╭─┬─────────────────────────────────╮
│0│<div class="film-rating-average">│
│ │            87%                  │
│ │    </div>                       │
╰─┴─────────────────────────────────╯
```

It could be that you haven't installed `nu_plugin_query`. If you're running off the latest main, you might need to compile the plugins, install them, and register them.

There is some good information in our book about plugins https://www.nushell.sh/book/plugins.html.

You can also do `which query web` to see if it exists. Or `help commands | where name =~ query`, or even `help query web`.

**Comment by detrin** [comment]
Okay so `which query web` gives me empty list. I think here https://www.nushell.sh/commands/docs/query_web.html is no information about installing anything else. There was no way of knowing that unless I read the whole docs.

So, here https://www.nushell.sh/book/plugins.html I don't understand from where I can download the plugin or how can I install it. There is only register part. Bare in mind that I am new to nushell and I feel like docs could be better in this respect.

**Comment by fdncred** [comment]
You should feel free to update the docs so they're more helpful.

nu_plugin_query is in our repo under crates if you want to compile it manually. it's also published on crates.io with everything else in nushell.

> unless I read the whole docs.

This is good advice people should take. Reading the docs, especially the book, even with them not being perfect, will give you more knowledge about how nushell works.

**Comment by detrin** [comment]
> You should feel free to update the docs so they're more helpful.

Of course, once I know how am I supposed to work with nushell.

> nu_plugin_query is in our repo under crates if you want to compile it manually. it's also published on crates.io with everything else in nushell.

Okay so what is the simplest way how can I use 

> > unless I read the whole docs.
> 
> This is good advice people should take. Reading the docs, especially the book, even with them not being perfect, will give you more knowledge about how nushell works.

The reality is that I don't have 3 days needed for reading of the whole docs. I read the docs fourth day every day for 2-4 hours and I try slowly implements nushell into my daily routine for this week as test. If the docs are designed in a way that person need it read as whole in order to use it, I would suggest it is not ideal if nushell aims to increase the popularity.

**Comment by fdncred** [comment]
> Okay so what is the simplest way how can I use

1. If you have a fork or clone of the nushell repo, you can cd to one of the plugin dirs and do `cargo install --path .`
2. If you're installing from crates.io, you can do `cargo install nu_plugin_query`

> The reality is that I don't have 3 days needed for reading of the whole docs

Our book isn't that big. It wouldn't take 3 days to read it. We can't spoon feed people every answer they're looking for. They need to be able to learn from the docs, learn from others on discord, maybe learn from the source code that is published in our repo, and learn on their own. 

We have docs, they're not perfect. Nushell literally changes every day. If you're not getting what you need from the docs, you're probably not alone. So, instead of deferring until you know everything, you could submit small PRs with what you have learned, little by little. This way, others can benefit from your learning and your struggles.
