### ISSUE TITLE
Crash when running `ls` command

### ISSUE THREAD

**Issue by tchak** [nushell/nushell#1025]
**Describe the bug**

Crash when running `ls` command with the following message:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**To Reproduce**
1. start `nu`
2. run `ls`
3.  get the exception

**Expected behavior**
I expect to see a list of files/folders

**Configuration (please complete the following information):**
 - OS: MacOS
 - Version 10.15.1 (19B88)
 - installed with `cargo install nu --all-features`
 - nu 0.5 and 0.6
 - cargo 1.39.0 (1c6ec66d5 2019-09-30)
 - rustc 1.39.0 (4560ea788 2019-11-04)

I am sorry if this is something very obvious. I am quite new to rust. I tried to run `RUST_BACKTRACE=1 nu` to get a backtrace like the message invited me to do but without success.

**Comment by jonathandturner** [comment]
Does it happen in any directory or just that one?  If it's just that one, do you know if it has anything special in there?

**Comment by tchak** [comment]
I can execute `ls` in an empty folder. But I just tried in the same empty folder `config` and `ps` and got the same exception.

**Comment by tchak** [comment]
I am very confused now. I just started a new terminal and tried `nu` in there and all commands work. But now I have something similar to #1005 going on...

I am sorry, I understand this is not very helpful.

**Comment by jonathandturner** [comment]
No worries. It's possible the issue here was whether the plugins could be found in the path. I haven't seen it crash like that before, so that's strange. 

I'm glad it's working. *hopefully* we can figure out #1005, as I see a few people are hitting it.

**Comment by tchak** [comment]
I restarted my computer to be sure and  it still working. I did try several install methods before 0.6 (I wanted to have starship support) so maybe I messed up something. I guess we can close it for now and I will reopen if I can find a more stable reproduction.

**Comment by jonathandturner** [comment]
Sounds good. Thanks for investigating!
