### ISSUE TITLE
Simple value to control prompt length

### ISSUE THREAD

**Issue by geetmankar** [nushell/nushell#10261]
### Related problem

I am trying to reduce prompt length to show only the current and the parent directory, i.e.:

1. `cd ~/projects` should lead to the prompt: 
```nu
~/projects>
```
2. `cd ~\Desktop\Projects\Main\nbody-code-2\Python` should lead to:
```nu
~\...\nbody-code-2\Python>
``` 
or something else to reduce the length of the prompt

### Describe the solution you'd like

Something that leads to:

1. `cd ~/projects` should lead to the prompt: 
```nu
~/projects>
```
2. `cd ~\Desktop\Projects\Main\nbody-code-2\Python` should lead to:
```nu
~\...\nbody-code-2\Python>
``` 

It's not necessary that it show the full name of the parent folder, that can also have `~\...ody-code-2\Python` instead of `~\...\nbody-code-2\Python`.

### Describe alternatives you've considered

```nu
def create_left_prompt [] {
    mut home = ""
    try {
        if $nu.os-info.name == "windows" {
            $home = $env.USERPROFILE
        } else {
            $home = $env.HOME
        }
    }

    let clen = 10
    # let home_dir = $home

    let dir = ([
        ($env.PWD | str substring 0..($home | str length) | str replace $home "~"),
        ($env.PWD | str substring ($home | str length)..)
    ] 
    | str join
    | split row "\\" 
    | reverse 
    | take 2 
    | append "~\\..." 
    | reverse 
    | str join "\\")

    let path_color = (if (is-admin) { ansi red_bold } else { ansi green_bold })
    let separator_color = (if (is-admin) { ansi light_red_bold } else { ansi light_green_bold })
    let path_segment = $"($path_color)($dir)"

    $path_segment | str replace --all (char path_sep) $"($separator_color)/($path_color)"
}
```

This solution leads to the second requirement being fulfilled but in the home directory I see

```nu
~/.../~
```

That is, a "~/.../" is appended to all names even if they're small in length

### Additional context and details

I'm sure this would be easily solvable if I just learned the language, but an easier configuration for this would be nice for users who don't want/have the time to do this.

**Comment by fdncred** [comment]
I do something similar to this in the oh-my.nu script.
![image](https://github.com/nushell/nushell/assets/343840/d5bf5076-58d1-4862-af1f-3d0878a239c0)

As you have seen, you have direct control over your prompt styling with `create_left_prompt` and `create_right_prompt`, so you should feel free to change it. I'm not sure this abbreviated path is something that nushell should adopt.

**Comment by geetmankar** [comment]
I understand, could you share a relevant snippet of the code that would allow me to add `...` or the abbreviation conditionally if the string is longer than some arbitrary length? As I mentioned, I don't know the nu language, I just wrote that code from intuition.

**Comment by fdncred** [comment]
There's a variety of pormpts here, including oh-my-nu. https://github.com/nushell/nu_scripts/tree/main/modules/prompt

Here's one cross-platform custom command that creates an abberviated path. Someone wrote it, posted it on discord, and I tweaked it.
```nushell
# Get an abbreviated path
def spwd [] {
  let home = (if ($nu.os-info.name == windows) { $env.USERPROFILE } else { $env.HOME })
  let sep = (if ($nu.os-info.name == windows) { "\\" } else { "/" })
  let spwd_paths = (
  $"!/($env.PWD)" |
    str replace $"!/($home)" ~ |
    split row $sep
  )
  # Darren's hack to make all slashes point to the right
  let sep = '/'
  # end hack
  let spwd_len = (($spwd_paths | length) - 1)
  for -n i in $spwd_paths {
    let spwd_src = ($i.item | split chars)
    if ($i.index == $spwd_len) {
      print -n $i.item
    } else if ($spwd_src.0 == ".") {
      print -n $".($spwd_src.1)($sep)"
    } else {
      print -n $"($spwd_src.0)($sep)"
    }
  }
}
```
I just ran it in my nushell folder and this was the output
```
❯ spwd
~/s/r/f/nushell
```

**Comment by geetmankar** [comment]
Ah, thank you so much.
