### ISSUE TITLE
Question: How to change shell with command running?

### ISSUE THREAD

**Issue by brasilikum** [nushell/nushell#1027]
How can I switch shells while there is command running?
eg. a shell runs docker and I want to switch to another

**Comment by jonathandturner** [comment]
We don't currently support this, but we'd like to add support in a future version of Nu.

**Comment by brasilikum** [comment]
If someone is aware of a workaround for now I would be interested

**Comment by Aloso** [comment]
Note that in bash, you can append an `&` to start a command in a separate process:

```bash
$ python ./demon.py &
[1] 17459
$
```

17459 is the PID of the new process. When the shell is closed, this process is not terminated and becomes an orphan.

I would like to have something similar in nushell :)

**Comment by thegedge** [comment]
Closing in favour of https://github.com/nushell/nushell/issues/1329

Once we have background streams, we can also consider Ctrl-Z for putting a foreground pipeline into the background 🙂

**Comment by acxz** [comment]
This was the issue that I came across, when trying to figure out how to do this in nushell, hence listing the solution here for any other stragglers like me.

Practically (see caveat below) solved by https://github.com/nushell/nushell/pull/14883

Bash:
`python ./demon.py &`

Nushell:
`job spawn { python ./demon.py }`

Probably should add this to the "Coming From Bash" page: https://www.nushell.sh/book/coming_from_bash.html (even if its not exactly the same)

Caveat, as mentioned elsewhere `&` in bash and `job spawn` in nushell are not semantically the same, as `&` launches an independent process whereas `job spawn` launches a dependent process (you kill the shell, any jobs spawned with `job spawn` also get killed).

The current place where the semantically equivalent `&` feature is being tracked is https://github.com/nushell/nushell/issues/15193?issue=nushell%7Cnushell%7C15201

Practically for many usecases (such as mine) my shell typically outlives my `job spawn` processes so the current workaround/feature in nushell is appropriate for me.
