### ISSUE TITLE
allow redirection to append to files

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#10278]
### Related problem

i was trying to store the results of multiple benchmarks in the same file at my job.
we have `out>` which is great but it does not allow to append to a file, it only overwrites it :cry: 

### Describe the solution you'd like

in Bash, one can do
```bash
$ echo "foo" > foo.txt
$ echo "bar" > foo.txt
$ echo "baz" >> foo.txt
$ cat foo.txt
bar
baz
```
> **Note**
> `foo` has been overwritten, but not `bar`

in Nushell, i think it would be could to be able to
```nushell
> "foo" out> foo.txt
> "bar" out> foo.txt
> "baz" out>> foo.txt
> open foo.txt
bar
baz
```

currently, the third line of the Nushell proposition gives the following error
```nushell
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[entry #6:1:1]
 1 │ "baz" out>> foo.txt
   ·       ──┬──
   ·         ╰── expected operator
   ╰────
```

### Describe alternatives you've considered

using the `save --append` command.

the biggest downside of this is that it does not stream :thinking:

**Comment by Silentdoer** [comment]
up
