### ISSUE TITLE
Tab selection

### ISSUE THREAD

**Issue by alxpettit** [nushell/nushell#10284]
### Related problem

In Fish, you can hit `tab` repeatedly to step through the available completions. Although this is a small detail, it seems to make for a smoother completion experience in practice.

### Describe the solution you'd like

I'd like to see this implemented in Nushell! :D

**Comment by amtoine** [comment]
@alxpettit 
i'm wondering what version of Nushell you are running :yum: 

this should work on latest `main`, i've written the following PR to solve that issue with the default config files :wink: 
- https://github.com/nushell/nushell/pull/10199

this should be available next release :innocent: 


if the issue still persists by then, please reopen this issue, this would be a bug :relieved:

**Comment by alxpettit** [comment]
Ah, whoops! I had trouble guessing the right keywords for finding that commit, sorry. I'm running 0.84.0 right now.

I thought there was no way someone just happened to implement this before version bump. :laughing: 

Thank you for letting me know

**Comment by amtoine** [comment]
> Ah, whoops! I had trouble guessing the right keywords for finding that commit, sorry. I'm running 0.84.0 right now.
> 
yeah that's what i was thinking :yum: 
so it should be available next release in around 10 days or right now by building from source or with one of our nightly builds :relieved: 

> I thought there was no way someone just happened to implement this before version bump. 😆
> 
ehe, it was annoying, i got upset and made the change :laughing: 

> Thank you for letting me know
>
anytime :blush:
