### ISSUE TITLE
Make more fallible packages features

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1028]
As we try to grow our support to build on more platforms, one code cleanup step we need to do is to move any fallible packages (those that may fall when being built) to features. 

We can keep a healthy set of default features but it should be possible to turn off default features and get to a maximally portable Nu.

**Comment by thegedge** [comment]
@jonathandturner anything to action here? It's been a while, so I assume we're pretty good here, but I'll let you action this issue.
