### ISSUE TITLE
Is there a detach / disown equivalent for nushell?

### ISSUE THREAD

**Issue by alxpettit** [nushell/nushell#10295]
### Question

On other shells like Bash and Fish, I can detach programs from the shell, either _ahead_ of time (by appending `&`), or after the fact (by hitting Ctrl+Z). After detaching, I can then run it again, either in the foreground (`fg`) or background (`bg`). Is there any way to do this with Nushell? (Should mention I am already well aware of multiplexers, but unfortunately, they don't cover all potential use cases.)

### Additional context and details

Am using Nushell 0.84.0

**Comment by fdncred** [comment]
Not at this time. Nushell does not have job control yet. Pueue is a good alternative right now and I believe there is a script to help support it in our nu_scripts repo.

**Comment by alxpettit** [comment]
Ah, gotcha! Thanks for informing me. :)

**Comment by alxpettit** [comment]
@timxx

Yeeeeah, it is pretty frustrating sometimes. I've been making due with Zellij. But I'd miss structured data way more, so I just suffer for a detach feature. :P

Zellij actually supports moving panes into new tabs, which helps a fair bit with long running processes, if you're interested.

**Comment by fdncred** [comment]
Some people use pueue, like I mentioned above. We're hoping someone will miss this feature so much that they'll implement it and submit a PR. We all want it, it's just finding someone with the time and the skill to do it since we're all just volunteers around here.
