### ISSUE TITLE
Transform a "2 lines" format into a "2 columns" one

### ISSUE THREAD

**Issue by ShalokShalom** [nushell/nushell#10297]
### Question

The command `pacman -Ss package` gives me output in the following formatted way: 

```
chaotic-aur/firedragon 117.0-1 [installed]
    Librewolf fork build using custom branding, settings & KDE patches by OpenSUSE
chaotic-aur/firedragon-extension-plasma-integration 1.8.1-3.4 [installed]
    Plasma browser integration addon for FireDragon
chaotic-aur/firedragon-extension-xdm-browser-monitor 2.2-1.3
    xdm browser monitor addon for firedragon.
```

I try to figure out, how to split at certain characters, so we could format it into:

| chaotic-aur | firedragon | 117.0-1 (installed) | Librewolf fork .. |

The second line for the package description, does seem to be an additional challange. 

I would prefer that without regex, if possible.

Thanks a lot

### Additional context and details

I did look into the documentation, but did quit after 20 minutes looking for a solution.

Based on the overwhelming amounts of options, I am sure, there is some way to figure out, how to do this on my own. 

The documentation is vast, and I would add this example to the cookbook, if someone solves it, and if that is welcome. 

I think it would add to the examples, of how to do basic stuff.

**Comment by ShalokShalom** [comment]
As an extra step: I am sure, we could figure out, how to split at certain characters, so we could format it into: 

| chaotic-aur | firedragon | 117.0-1 (installed) | Librewolf fork .. |

I would prefer that without regex, if possible.

**Comment by amtoine** [comment]
@ShalokShalom 
this is a recurring question, i guess we should have a `nu_scripts` for this, if not already :open_mouth: 

for the `dragon` search, i came up with the following
```nushell
pacman -Ss dragon
    | lines
    | str trim
    | group 2
    | each {|it| { rest: $it.0, desc: $it.1 }}
    | update rest { parse "{repo}/{pkg} {version}" }
    | flatten --all
```
```
#┬repo─┬────────────pkg────────────┬──────────────────version──────────────────┬──────────────────────────────────desc───────────────────────────────────
0│extra│dragon                     │23.04.2-1 (kde-applications kde-multimedia)│A multimedia player where the focus is on simplicity, instead of features
1│extra│dragonfly-reverb           │3.2.10-2                                   │A concert hall reverb and a room reverb                                  
2│extra│dragonfly-reverb-clap      │3.2.10-2 (clap-plugins pro-audio)          │A concert hall reverb and a room reverb - CLAP plugin                    
3│extra│dragonfly-reverb-lv2       │3.2.10-2 (lv2-plugins pro-audio)           │A concert hall reverb and a room reverb - LV2 plugin                     
4│extra│dragonfly-reverb-standalone│3.2.10-2 (pro-audio)                       │A concert hall reverb and a room reverb - standalone                     
5│extra│dragonfly-reverb-vst       │3.2.10-2 (pro-audio vst-plugins)           │A concert hall reverb and a room reverb - VST plugin                     
6│extra│dragonfly-reverb-vst3      │3.2.10-2 (pro-audio vst3-plugins)          │A concert hall reverb and a room reverb - VST3 plugin                    
─┴─────┴───────────────────────────┴───────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────
```

**Comment by amtoine** [comment]
yeah no i do not think we have such a script in `nu_scripts` :thinking: 
```nushell
rg "pacman" **/*.nu
```
nor
```nushell
ls **/*.nu | find pacman
```
give anything apart from completion :thinking:

**Comment by ShalokShalom** [comment]
Hi, wonderful 

That works pretty great. 
My screen is relatively small, so the long description essentially creates a lot of space betwen the lines. 

![Screenshot_20230910_111912](https://github.com/nushell/nushell/assets/6344099/2e9fe039-360e-4ea3-bcc7-b6c1109130e0)

**Comment by amtoine** [comment]
> That works pretty great.
>
cool :yum: 

> My screen is relatively small, so the long description essentially creates a lot of space betwen the lines.
> 
yeah, you might want to `reject desc` temporarily to see the rest properly :yum:

**Comment by ShalokShalom** [comment]
I thought there may be a solution, to make the text expand beyond my screen, so that I can use a scrollbar to see it?

**Comment by amtoine** [comment]
@ShalokShalom 
not in the REPL, but you can pipe the table into `explore` to have the Nushell pager (or #ad use my `nu_plugin_explore` plugin :wink:)

**Comment by ShalokShalom** [comment]
Nu is very complicated to use, just as a heads-up 😅

**Comment by amtoine** [comment]
> Nu is very complicated to use, just as a heads-up 😅
>
what do you mean?
do you have examples? :yum:
