### ISSUE TITLE
better description how to build with statically linked openssl

### ISSUE THREAD

**Issue by dzorya** [nushell/nushell#10290]
### Describe the solution you'd like

Add to the comment https://github.com/nushell/nushell/blob/8501024546311ee86af50a2877d48584779d6dee/Cargo.toml#L120
that perl is required to statically link openssl

if you are ok with the suggestion I'm willing to prepare pull request. However, I'm not a professional programmer.

### Describe alternatives you've considered

maybe add description how to build statically linked nushell in Alpine to the documentation
alternatively a better error something like perl is missing 

### Additional context and details

if you try to build nushell with everything statically linked in Alpine container it will fail unless perl is installed. However it is not mentioned in nushell documentation or Cargo.toml
sudo podman run -it -v $(pwd):/mnt alpine:edge
apk add git
apk add rustup
rustup-init
source "$HOME/.cargo/env"
apk add pkgconf
apk add openssl-libs-static
apk add build-base
apk add perl #BUILD WON'T WORK WITHOUT IT AND ERROR IS NOT CLEAR
cd home
git clone https://github.com/nushell/nushell.git
cd nushell
cargo build --release --workspace --features="dataframe static-link-openssl"

**Comment by fdncred** [comment]
I'd be fine with more instructions, but they'd need to be cross-platform. i.e. I don't really want to say what you said in the "additional details" section, but you can say that you need perl.

I remember when this first landed, I had to get a buildable version of perl on Windows to make it work, and it was kind of a pain.
