### ISSUE TITLE
Add built-in job control support

### ISSUE THREAD

**Issue by alxpettit** [nushell/nushell#10296]
### Related problem

It's sometimes difficult to tell exactly how long a process will need to run for. In other shells like Fish and Bash, it's easy to deal with this -- just some combination of `Ctrl+Z`, `bg`, and `disown`. In Nushell, not so much.

### Describe the solution you'd like

Some implementation of job control that allows you to detach the running process from the terminal, and disown the process so that it isn't dependent on the terminal to stay alive.

### Describe alternatives you've considered

Terminal multiplexers like Zellij & Tmux, as well as Pueue. But these can cause issues with some unusual formatting (e.g., Tmux discards SIXEL data, Zellij causes trouble with underlined text in Helix, etc). There doesn't seem to be a way to actually _attach_ to external jobs in Pueue, so I can't deal with CLI-interactive longrunning processes that way.

**Comment by amtoine** [comment]
this looks like a duplicate of https://github.com/nushell/nushell/issues/247 to me, can you confirm it @alxpettit? :yum:

**Comment by alxpettit** [comment]
Oops! Yep, sorry!
