### ISSUE TITLE
help should use themes for coloring

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#10318]
### Related problem

Command help messages do not use the defined theme. Note how the green and dark cyan stand how here.
![image](https://github.com/nushell/nushell/assets/343840/8080b714-bb18-4128-a122-189ea3c14511)

I believe this is where the colors are being set https://github.com/fdncred/nushell/blob/main/crates/nu-engine/src/documentation.rs#L71-L76. It should be pretty easy to get the config from `engine_state` and use the color_config colors. Not sure exactly what colors should be used. We wouldn't want our defaults to change but they should change with a theme.

### Describe the solution you'd like

Instead of hard coding colors, help should follow whatever the defined theme is.

### Additional context and details

Nushell on 0.84.1 after sourcing this file. Assumes you have the external `vivid` already installed.
```nushell
let catppuccin_mocha = {
    rosewater: "#f5e0dc"
    flamingo: "#f2cdcd"
    pink: "#f5c2e7"
    mauve: "#cba6f7"
    red: "#f38ba8"
    maroon: "#eba0ac"
    peach: "#fab387"
    yellow: "#f9e2af"
    green: "#a6e3a1"
    teal: "#94e2d5"
    sky: "#89dceb"
    sapphire: "#74c7ec"
    blue: "#89b4fa"
    lavender: "#b4befe"
    text: "#cdd6f4"
    subtext1: "#bac2de"
    subtext0: "#a6adc8"
    overlay2: "#9399b2"
    overlay1: "#7f849c"
    overlay0: "#6c7086"
    surface2: "#585b70"
    surface1: "#45475a"
    surface0: "#313244"
    base: "#1e1e2e"
    mantle: "#181825"
    crust: "#11111b"
}

let catppuccin_theme = {
    separator: $catppuccin_mocha.overlay0
    # leading_trailing_space_bg: { attr: "n" }
    leading_trailing_space_bg: $catppuccin_mocha.overlay0
    header: { fg: $catppuccin_mocha.blue attr: "b" }
    empty: $catppuccin_mocha.lavender
    bool: $catppuccin_mocha.lavender
    int: $catppuccin_mocha.peach
    duration: $catppuccin_mocha.text
    filesize: {|size|
          if $size < 1mb {
            $catppuccin_mocha.green
        } else if $size < 100mb {
            $catppuccin_mocha.yellow
        } else if $size < 500mb {
            $catppuccin_mocha.peach
        } else if $size < 800mb {
            $catppuccin_mocha.maroon
        } else if $size > 800mb {
            $catppuccin_mocha.red
        }
    }
    date: {|| (date now) - $in |
        if $in < 1hr {
            $catppuccin_mocha.green
        } else if $in < 1day {
            $catppuccin_mocha.yellow
        } else if $in < 3day {
            $catppuccin_mocha.peach
        } else if $in < 1wk {
            $catppuccin_mocha.maroon
        } else if $in > 1wk {
            $catppuccin_mocha.red
        }
    }
    range: $catppuccin_mocha.text
    float: $catppuccin_mocha.text
    string: $catppuccin_mocha.text
    nothing: $catppuccin_mocha.text
    binary: $catppuccin_mocha.text
    cellpath: $catppuccin_mocha.text
    row_index: { fg: $catppuccin_mocha.mauve attr: "b" }
    record: $catppuccin_mocha.text
    list: $catppuccin_mocha.text
    block: $catppuccin_mocha.text
    hints: $catppuccin_mocha.overlay1
    search_result: { fg: $catppuccin_mocha.red bg: $catppuccin_mocha.text }
    shape_and: { fg: $catppuccin_mocha.pink attr: "b" }
    shape_binary: { fg: $catppuccin_mocha.pink attr: "b" }
    shape_block: { fg: $catppuccin_mocha.blue attr: "b" }
    shape_bool: $catppuccin_mocha.teal
    shape_custom: $catppuccin_mocha.green
    shape_datetime: { fg: $catppuccin_mocha.teal attr: "b" }
    shape_directory: $catppuccin_mocha.teal
    shape_external: $catppuccin_mocha.teal
    shape_externalarg: { fg: $catppuccin_mocha.green attr: "b" }
    shape_filepath: $catppuccin_mocha.teal
    shape_flag: { fg: $catppuccin_mocha.blue attr: "b" }
    shape_float: { fg: $catppuccin_mocha.pink attr: "b" }
    shape_garbage: { fg: $catppuccin_mocha.text bg: $catppuccin_mocha.red attr: "b" }
    shape_globpattern: { fg: $catppuccin_mocha.teal attr: "b" }
    shape_int: { fg: $catppuccin_mocha.pink attr: "b" }
    shape_internalcall: { fg: $catppuccin_mocha.teal attr: "b" }
    shape_list: { fg: $catppuccin_mocha.teal attr: "b" }
    shape_literal: $catppuccin_mocha.blue
    shape_match_pattern: $catppuccin_mocha.green
    shape_matching_brackets: { attr: "u" }
    shape_nothing: $catppuccin_mocha.teal
    shape_operator: $catppuccin_mocha.peach
    shape_or: { fg: $catppuccin_mocha.pink attr: "b" }
    shape_pipe: { fg: $catppuccin_mocha.pink attr: "b" }
    shape_range: { fg: $catppuccin_mocha.peach attr: "b" }
    shape_record: { fg: $catppuccin_mocha.teal attr: "b" }
    shape_redirection: { fg: $catppuccin_mocha.pink attr: "b" }
    shape_signature: { fg: $catppuccin_mocha.green attr: "b" }
    shape_string: $catppuccin_mocha.green
    shape_string_interpolation: { fg: $catppuccin_mocha.teal attr: "b" }
    shape_table: { fg: $catppuccin_mocha.blue attr: "b" }
    shape_variable: $catppuccin_mocha.pink

    background: $catppuccin_mocha.base
    foreground: $catppuccin_mocha.text
    cursor: $catppuccin_mocha.blue
}

$env.config.color_config = $catppuccin_theme
$env.LS_COLORS = (vivid generate catppuccin-mocha)
```

**Comment by DanyPDev** [comment]
Hello! I attempted to address this issue, but I encountered a few challenges. I was searching for a way to convert the color_config colors to ANSI colors. During my search, I came across a method in the nu-color-config crate that could potentially accomplish this task [https://github.com/nushell/nushell/blob/main/crates/nu-color-config/src/color_config.rs#L9C1-L20C2](https://github.com/nushell/nushell/blob/main/crates/nu-color-config/src/color_config.rs#L9C1-L20C2). However, I encountered an issue while trying to add nu-color-config as a dependency to nu-engine because it would lead to a circular dependency problem.
I'm wondering if I'm on the right track. 
Is there perhaps a better approach to convert the color_config colors to ANSI colors?

Looking forward for

**Comment by fdncred** [comment]
I haven't investigated this myself, but my first approach would look to see how colors are used in nu-engine. Maybe there's already a technique that someone else has used.

My second idea is, we know that nu-engine has access to the config via `get_config()`, so maybe the colors are already being translated and you just have to pass the config around to wherever the help function is that has the coloring.

My third idea is, that I wrote the coloring for help. Maybe I already discovered this isn't really easily possible without some changes and I just didn't document it? I don't remember though. 

You may need to dig a little deeper to work through this issue.

**Comment by DanyPDev** [comment]
Thanks for the help! This is a really interesting and fun first issue.

**Comment by DanyPDev** [comment]
How does it look?😊

![image](https://github.com/nushell/nushell/assets/96401568/30e74bae-1604-4cd3-930a-80e3a63d87d3)

**Comment by fdncred** [comment]
wonderful!
