### ISSUE TITLE
tables won't show leading and trailing spaces as configured

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#10317]
### Describe the bug

A long time ago I added `leading_trailing_space_bg` to the config in order to show table cells with leading and trailing spaces in a configured color. It used to work, now it doesn't.

### How to reproduce

With something like this (trying a few different ways to assign a color)
![image](https://github.com/nushell/nushell/assets/343840/330d9a56-4e5f-4246-8a50-3a0e259f0410)

You should be able to see that col2's value has leading and trailing spaces and they should be highlighted in the overlay0 color. This could be any color really.

I'm guessing this happened a some time ago because this feature isn't really useful until you need it.

### Expected behavior

highlight the leading and trailing space in the color configured

### Configuration

|key|value|
|-|-|
|version|0.84.1|
|branch|main|
|commit_hash|7b89fab3277ff11e7cf19a2feec63d3dd24ef010|
|build_os|windows-x86_64|
|build_target|x86_64-pc-windows-msvc|
|rust_version|rustc 1.70.0 (90c541806 2023-05-31)|
|rust_channel|1.70.0-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.70.0 (ec8a8a0ca 2023-04-25)|
|build_time|2023-09-11 07:27:33 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|dataframe, default, extra, sqlite, trash, which, zip|
|installed_plugins|emoji, file, from eml, from ics, from ini, from parquet, from vcf, gstat, highlight, hist, inc, json path, nu_plugin_explore, periodic-table, plot, pnet, query, query json, query web, query xml, regex, str similarity, xyplot|

### Additional context

/cc: @zhiburt

**Comment by amtoine** [comment]
we should probably have a test for this :+1:

**Comment by fdncred** [comment]
> we should probably have a test for this 👍

Unfortunately `nu!` removes ansi coloring. So testing for colors may not be possible.
