### ISSUE TITLE
Http-Post with "-t application/json" flag accepts records but not lists

### ISSUE THREAD

**Issue by juanmi108** [nushell/nushell#10319]
### Describe the bug

`http post -fe -t application/json https://google.com [{ field: value }]`

return this error:

```
Error: nu::shell::io_error
  × I/O error
  help: unsupported body input
```

### How to reproduce

`http post -fe -t application/json $anyServer []`

### Expected behavior

Sends the request and give the response back (should be a http-405 in this case)

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.84.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.2 (1a737af0c 2023-08-07)                               |
| build_time         | 2023-08-22 21:09:23 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | dataframe, default, sqlite, trash, which, zip                     |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
Seems like this is more of a feature request. Looks like `http post` is working as designed right now. Am I incorrect?
