### ISSUE TITLE
`help <module> <def>` doesn't display help

### ISSUE THREAD

**Issue by bobhy** [nushell/nushell#10311]
### Describe the bug

Pretty sure this was working a while ago.

### How to reproduce

```
> echo `export def foo [able baker="gronk" --charlie] {echo yes}` | save foo2.nu
> use foo2.nu
> help "foo2 foo"
Error: nu::parser::not_found

  × Not found.
   ╭─[entry #24:1:1]
 1 │ help "foo2 foo"
   ·      ─────┬────
   ·           ╰── did not find anything under this name
   ╰────

### But --help works
> foo2 foo --help
Usage:
  > foo {flags} <able> (baker) 

Flags:
  --charlie - 
  -h, --help - Display the help message for this command

Parameters:
  able <any>: 
  baker <string>:  (optional, default: 'gronk')

Input/output types:
  ╭───┬───────┬────────╮
  │ # │ input │ output │
  ├───┼───────┼────────┤
  │ 0 │ any   │ any    │
  ╰───┴───────┴────────╯

 ```

### Expected behavior

Expected user-defined function to be supported by `help` command.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.84.1                                   |
| branch             | main                                     |
| commit_hash        | 487f1a97ea7416366188e51934e48a239bec2ca6 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)      |
| rust_channel       | 1.70.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)      |
| build_time         | 2023-08-27 10:06:43 -07:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
interesting. maybe @kubouch has an idea of what's happening.

**Comment by fdncred** [comment]
closed by https://github.com/nushell/nushell/pull/14490
