### ISSUE TITLE
Parsing validation fails with bareword containing `#` in block

### ISSUE THREAD

**Issue by sholderbach** [nushell/nushell#10327]
### Describe the bug

On the REPL insert, and try to submit via enter.

```nushell
1..10 | each {echo nixpkgs#unzip }
```

This will continue to insert a new line as if the block was not closed.

The basic behavior that a string containing a `#` is not interpreted as a comment (commonly found in the nix context) still works outside the block:

```nushell
> echo nixpkgs#unzip
nixpkgs#unzip
```

The original problem was described in: (https://github.com/nushell/nushell/issues/6957, https://github.com/nushell/nushell/issues/6335, https://github.com/nushell/nushell/issues/8137)
The parsing/lexing change to make it possible came with https://github.com/nushell/nushell/pull/8151

### How to reproduce

1. In repl
2. Insert 
```nushell
1..10 | each {echo nixpkgs#unzip }
```
3. cursor at the end
4. Press enter

### Expected behavior

Should be a valid expression to submit

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.84.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.72.0 (5680fa18f 2023-08-23) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.72.0 (103a7ff2e 2023-08-15) |
| build_time         | 2023-09-11 22:00:27 +02:00          |
| build_rust_channel | release                             |
| allocator          | standard                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  |                                     |

**Comment by Eisfunke** [comment]
Can confirm. Also, still doesn't work if I try running via `nu -c` (so that the REPL not allowing me to submit the command doesn't play into it):

```
$> nu -c "nix run nixpkgs#hello"
Hello, world!

$> nu -c "echo (nix run nixpkgs#hello)"
Error: nu::parser::unexpected_eof

  × Unexpected end of code.
   ╭─[source:1:1]
 1 │ echo (nix run nixpkgs#hello)
   ╰────
```

(same with your example `each {echo nixpkgs#unzip }`)

So it seems this is not just a problem with the REPL not allowing you to submit the command, the `#` just seems to still be parsed incorrectly if inside a block.

**Comment by amtoine** [comment]
ooh i stumbled upon the same exact one when writing [this](https://github.com/amtoine/dotfiles/commit/98a7a951e03b001d17c4d43bf42aa7b3bfb1c582#diff-e2101a3dce60032de1621ecede0d58b51245f85a4996c68cc87c3c72b37d59bcR4), where i tried `nix run nixpkgs#opam` inside a `do` block

**Comment by RobbingDaHood** [comment]
Could I be assigned to this issue? 

I also have a suggested solution, please review that. 

<details>
<summary>Patch of suggested solution</summary>

```diff
Index: crates/nu-parser/src/lex.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/crates/nu-parser/src/lex.rs b/crates/nu-parser/src/lex.rs
--- a/crates/nu-parser/src/lex.rs	(revision Staged)
+++ b/crates/nu-parser/src/lex.rs	(date 1733255567176)
@@ -51,7 +51,7 @@
 }
 
 // A baseline token is terminated if it's not nested inside of a paired
-// delimiter and the next character is one of: `|`, `;`, `#` or any
+// delimiter and the next character is one of: `|`, `;` or any
 // whitespace.
 fn is_item_terminator(
     block_level: &[BlockKind],
@@ -115,6 +115,7 @@
     //   character (whitespace, `|`, `;` or `#`) is encountered, the baseline
     //   token is done.
     // - Otherwise, accumulate the character into the current baseline token.
+    let mut previous_char = None;
     while let Some(c) = input.get(*curr_offset) {
         let c = *c;
 
@@ -150,8 +151,11 @@
         } else if c == b'#' {
             if is_item_terminator(&block_level, c, additional_whitespace, special_tokens) {
                 break;
-            }
-            in_comment = true;
+            } else if previous_char.map(|c: char| c.is_alphabetic()).unwrap_or(false) {
+                in_comment = false;
+            } else {
+                in_comment = true;
+            }
         } else if c == b'\n' || c == b'\r' {
             in_comment = false;
             if is_item_terminator(&block_level, c, additional_whitespace, special_tokens) {
@@ -254,6 +258,7 @@
         }
 
         *curr_offset += 1;
+        previous_char = Some(c as char);
     }
 
     let span = Span::new(span_offset + token_start, span_offset + *curr_offset);
``` 

</details> 

I did test it manually: All current tests passes but I have not run any other checks. 

I also need to test if the condition also catches all letters or just the ASCII ones.

**Comment by sholderbach** [comment]
In the case if you have some working idea please open a draft PR directly, so we can discuss the necessary new tests or get folks to review the idea. Patch comments on GitHub are harder to work with than a quick `gh pr checkout <pr number>` or expanding the full diff view of a PR for context.

**Comment by RobbingDaHood** [comment]
> In the case if you have some working idea please open a draft PR directly, so we can discuss the necessary new tests or get folks to review the idea. Patch comments on GitHub are harder to work with than a quick `gh pr checkout <pr number>` or expanding the full diff view of a PR for context.

Here is a draft of the suggestion: https://github.com/nushell/nushell/pull/14523

**Comment by hustcer** [comment]
Closed by https://github.com/nushell/nushell/pull/14616
