### ISSUE TITLE
Release extra features and dataframes as official plugins

### ISSUE THREAD

**Issue by ryan-preble** [nushell/nushell#10322]
### Related problem

Compiling nushell from source is always a massive headache. While I can compile plugins and most smaller rust-based applications using the windows GNU toolchain without issue, I have only ever been able to successfully compile nushell using the MSVC toolchain. The binaries you guys distribute work well, but I would still like to have the choice of using any extra features or dataframes without having to build from source. The distributed binaries alone don't do that. 

### Describe the solution you'd like

Distribute dataframes and "extra" features as plugins, so that the end user can pick and choose what features they want without needing to compile any source code. I think this would also have benefits within shared systems where individual users would have different use cases and different needs.

**Comment by fdncred** [comment]
This would be a huge non-trivial undertaking. I think it would be easier to have release binaries of each feature flavor.

a. default features
b. extra
c. dataframe
d. extra,dataframe

**Comment by hustcer** [comment]
> This would be a huge non-trivial undertaking. I think it would be easier to have release binaries of each feature flavor.
> 
> a. default features b. extra c. dataframe d. extra,dataframe

I'd suggest simplify it as:
a. Default features as the standard release
b. All features as the full release

And we can create the above binaries with all the following release

**Comment by fdncred** [comment]
ya, I'd support that too.
