### ISSUE TITLE
[job control] putting vim in the background hangs nu

### ISSUE THREAD

**Issue by Dboy-Even** [nushell/nushell#10335]
### Describe the bug

Hi,

From within `vim`, pressing Ctrl+Z sends `vim` to the background, in wish case, you lose control of your terminal.

This behavior does not occur when using `bc` instead of vim (pressing `Ctrl + z` does nothing).

FYI: I am wholly new to `nu` and just discovered it !
I might have missed something.
If you need any additional information or testing, please, ask.

### How to reproduce

1. start nu
2. start vim
3. press `Ctrl + Z`
4. lose control of your terminal.

### Expected behavior

1. start `nu`
2. start `vim`
3. press `Ctrl + Z`
4. Either do nothing or return to `nu`.

### Screenshots

![image](https://github.com/nushell/nushell/assets/9354740/c1e8f466-c508-44d3-bb12-112951dc759a)

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.84.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | d2abb8603abab43ec4a6d4ed56f9018790b99dce                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (Arch Linux rust 1:1.71.1-1) |
| cargo_version      | cargo 1.71.1                                                     |
| build_time         | 2023-08-23 02:21:39 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

### Additional context

- kernel
```
~> uname -a                                               2023/09/12 04:48:37 PM
Linux tempy 6.1.52-1-lts #1 SMP PREEMPT_DYNAMIC Thu, 07 Sep 2023 05:17:41 +0000 x86_64 GNU/Linux
```
- OS
```
~> lsb_release -a                                        2023/09/12 04:48:40 PM
LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```
-  tested terminals
   - Guake
```
~> guake --version                                      2023/09/12 04:48:42 PM
Guake Terminal: 3.11.dev0
VTE: 0.72.2
VTE runtime: 0.72.2
Gtk: 3.24.38
```
   - alacritty
```
~> alacritty --version                                    2023/09/12 04:53:05 PM
alacritty 0.12.2 (9d9982df)
```

**Comment by fdncred** [comment]
Thanks for the detailed description and screenshots. We do not have any type of job control yet, which means, when you try to do it, bad things may happen. Hopefully a contributor will come along side us and implement something that works for nushell.

**Comment by weirdan** [comment]
This used to happen for me as well, but it seems that now pressing `Ctrl+Z` in nvim just doesn't do anything. I get a brief flash of the output I had before starting nvim and then the control is returned to nvim. There's no hang anymore.
