### ISSUE TITLE
Reconfiguring reedline / nushell to stop eating Ctrl+Q, so that I can replace Ctrl+C with Ctrl+Q

### ISSUE THREAD

**Issue by alxpettit** [nushell/nushell#10348]
### Question

Goal: make Nushell treat Ctrl+Q exactly as it treats Ctrl+C, and allow Ctrl+C key to pass through unharmed. But it's not working! Anyone know why?

Here's what I got so far:

```nu
$env.config.keybindings = [
    { name: no_ctrl_c modifier: control keycode: char_c mode: [emacs, vi_normal, vi_insert] event: null}
    { name: quit modifier: control keycode: char_q mode: [emacs, vi_normal, vi_insert] event: {send: CtrlC}}
];
stty intr ^Q
```

The problem is, it doesn't _actually_ treat Ctrl+Q the way I expect. If I set `stty intr ^E`, for instance, it works just fine -- but not with this.

### Additional context and details

Oddly enough, even if I do this:

```nu
$env.config.keybindings = [
    { name: no_ctrl_c modifier: control keycode: char_c mode: [emacs, vi_normal, vi_insert] event: null}
    # Note: event changed to null here
    { name: quit modifier: control keycode: char_q mode: [emacs, vi_normal, vi_insert] event: null}
];
stty intr ^Q
```

It still does not work, despite [the manual](https://www.nushell.sh/book/line_editor.html#removing-a-default-keybinding) saying that this is the correct way to disable a default keybinding. So, I think reedline is just eating these keybindings, and if there is a way to get it not to eat the characters, it seems hard to figure out from the manual.

Please let me know if anyone knows how to resolve this! :)

**Comment by sholderbach** [comment]
Do you want to remap the Ctrl-C behavior only while editing or also to stop it from terminating execution? The keybindings only affect the editing.

You can give `keybindings listen` a try to see if nushell can see the particular key combinations.

**Comment by alxpettit** [comment]
@sholderbach Doing both would be great! :) I actually already found and tried out the `keybindings listen` command, but it doesn't seem to be revealing anything noteworthy:

```nu
✨ ❯ keybindings listen
Type any key combination to see key details. Press ESC to abort.
char: c, code: 0x000063, modifier: CONTROL, flags: 0b000010, kind: Press, state: NONE
char: q, code: 0x000071, modifier: CONTROL, flags: 0b000010, kind: Press, state: NON
```

**Comment by alxpettit** [comment]
I figured it out! `XON` / `XOFF` control was already setup to interpret Ctrl+Q, which normally [resumes a stopped process](https://unix.stackexchange.com/questions/12107/how-to-unfreeze-after-accidentally-pressing-ctrl-s-in-a-terminal). For some unknown reason, this was affecting both child processes and internal commands in Nushell, but _not_ in Fish.

```nu
$env.config.keybindings = [
    { name: no_ctrl_c modifier: control keycode: char_c mode: [emacs, vi_normal, vi_insert] event: null}
    { name: quit modifier: control keycode: char_q mode: [emacs, vi_normal, vi_insert] event: {send: CtrlC}}
];
stty intr ^Q
stty -ixon
```
