### ISSUE TITLE
Nu panics when sourcing an empty file in a script

### ISSUE THREAD

**Issue by 13x1** [nushell/nushell#10366]
### Describe the bug

```
[lexi@nixos:/tmp]$ touch empty.nu

[lexi@nixos:/tmp]$ echo "source empty.nu" > program.nu

[lexi@nixos:/tmp]$ nu program.nu
thread 'main' panicked at 'internal error: missing span contents in file cache', crates/nu-protocol/src/engine/engine_state.rs:1391:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### How to reproduce

Run the above commands

### Expected behavior

Expect it to run and do nothing

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.84.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.72.0 (5680fa18f 2023-08-23) (built from a source tarball) |
| cargo_version      | cargo 1.72.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by amtoine** [comment]
i was able to reproduce :+1:

**Comment by carols10cents** [comment]
I just came here to report the same issue, only slightly simpler, just running an empty script file:

```
❯ touch script.nu
❯ nu script.nu
```

**Comment by 13x1** [comment]
Oh hey @carols10cents! I thought your name sounded familiar, and I was right! The Rust Programming Language book was a very good read :3

**Comment by carols10cents** [comment]
Hi @13x1!! Thank you so much, I'm glad you liked it!!! ❤️

**Comment by blueberrycarrot** [comment]
Still crashes in 0.90.1.

**Comment by weirdan** [comment]
This doesn't happen anymore (checked on 0.97.1)
