### ISSUE TITLE
nu -ic 'command' raises missing_flag_param

### ISSUE THREAD

**Issue by kucho** [nushell/nushell#10374]
### Describe the bug

I have VSCode extensions such as [Ruby LSP](https://github.com/Shopify/vscode-ruby-lsp) that runs commands with `-ic`. I noticed that only nu breaks it.

### How to reproduce

1. Run `nu -ic 'echo "hmm"'`

### Expected behavior

I expected nu to return the same output as bash or any other shell:

```
~> bash -ic 'echo "hmm"'                                                                                                                                   
hmm
```

### Configuration

 key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.84.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | d2abb8603abab43ec4a6d4ed56f9018790b99dce                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (Arch Linux rust 1:1.71.1-1) |
| cargo_version      | cargo 1.71.1                                                     |
| build_time         | 2023-08-23 02:21:39 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment]
I'm confused. Why would we start an interactive shell to run commands? The shell would just be lingering and never close.
