### ISSUE TITLE
Remove homebrew requirement for dependencies on macOS. I don't want to install it.

### ISSUE THREAD

**Issue by amichail** [nushell/nushell#1037]

**Comment by jonathandturner** [comment]
This repo is just for the Nushell project. Homebrew packages are handler by volunteers who work on homebrew. This issue is probably best filed on the homebrew repo.

**Comment by amichail** [comment]
I don't want to use homebrew at all. Why would I contact anyone in the homebrew repo?

**Comment by jonathandturner** [comment]
Ah, I misread your comment. I didn't understand what you meant.

**Comment by amichail** [comment]
So could you provide a way to install nushell on macOS without having to use homebrew for the dependencies?

**Comment by jonathandturner** [comment]
You can get pre-built binaries from our releases: https://github.com/nushell/nushell/releases/tag/0.6.1

Look under the assets link at the bottom

**Comment by amichail** [comment]
You also need to look at this for pre-built binaries:

`https://github.com/nushell/book/blob/master/en/installation.md#dependencies`

And there, it says you need homebrew to install the dependencies on macOS.

**Comment by amichail** [comment]
So I tried the pre-built binary and it worked without using homebrew to install the dependencies. So maybe remove the dependencies link for macOS as those dependencies seem to be already installed anyway?
