### ISSUE TITLE
Parser crashes when variable name in let expression is missing

### ISSUE THREAD

**Issue by anka-213** [nushell/nushell#10380]
### Describe the bug

I get index out of bounds crash when typing a program like this:
```
let = a | b
```

I ran into this when trying to rename a variable 

### How to reproduce

1. Launch nu
2. Write `let = a | b` in the terminal
3. nu immediately crashes

### Expected behavior

I expect the parser to not be partial or at least that any panic from the parser would be caught instead of crashing the full shell.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.83.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-x86_64                                                      |
| build_target       | x86_64-apple-darwin                                               |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.1                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

### Additional context

Stack trace:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', crates/nu-parser/src/parser.rs:3068:47                                                             09/15/2023 10:50:32 AM
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: nu_parser::parser::parse_var_with_opt_type
   4: nu_parser::parse_keywords::parse_let
   5: nu_parser::parser::parse_builtin_commands
   6: nu_parser::parser::parse_block
   7: nu_parser::parser::parse
   8: <nu_cli::syntax_highlight::NuHighlighter as reedline::highlighter::Highlighter>::highlight
   9: reedline::engine::Reedline::repaint
  10: reedline::engine::Reedline::read_line
  11: nu_cli::repl::evaluate_repl
  12: nu::run::run_repl
  13: nu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by anka-213** [comment]
Here is the line that the stack trace mentions: https://github.com/nushell/nushell/blob/bf5bd3ff102689a3cae78ea5dfe2e67dfa92f4cd/crates/nu-parser/src/parser.rs#L3068

It does indeed seem to index an array without checking that it's non-empty first.

**Comment by anka-213** [comment]
Oh, I see now that it has already been fixed in master, thanks to #9851.

**Comment by anka-213** [comment]
It would still be nice to do something systematic to prevent this kinds of errors from popping up though

**Comment by sholderbach** [comment]
Yeah more testing and also fuzzing of the parser would definitely be appreciated.

https://github.com/nushell/nushell/issues/9417#issuecomment-1591329813 proposed a fuzzing target, we should probably set up.

**Comment by anka-213** [comment]
@sholderbach I'm currently working on another way of making the parser code more robust by using primitives that cannot crash instead of sprinkling things like `spans[*span_idx]` all over the code. See #10381 for my current draft.

**Comment by tokatoka** [comment]
> https://github.com/nushell/nushell/issues/9417#issuecomment-1591329813 proposed a fuzzing target, we should probably set up.

i'll add it in #10376

**Comment by sholderbach** [comment]
Awesome thanks!
