### ISSUE TITLE
Nuscript's for Pacman

### ISSUE THREAD

**Issue by ShalokShalom** [nushell/nushell#10385]
### Related problem

Hi lovely folks 🌞 

So I had the joy to see Nushell in action for the first time recently, and I have to say, I am quite impressed with the neat output. 

What I am also impressed by, is the immense complication, it can bring, when I want to launch a command. 😄 

See this issue: https://github.com/nushell/nushell/issues/10297
As you can see, is it suggested, that we could have a script, that helps with common pacman queries. 

Next to the shown ones, I also like to introduce you to the pkgfile command, that helps with packaging. 

![Screenshot_20230915_223925](https://github.com/nushell/nushell/assets/6344099/50afefaf-a3cd-4c66-b721-5d37d2d054bc)

This could clearly take some order 😃 

### Describe the solution you'd like

Clear output for pacman out of the box

See the solution in the linked example 👍🏻 

### Describe alternatives you've considered

Doing it by hand 😉

**Comment by fdncred** [comment]
Hi 👋🏻.  What's the question? I must be missing it. I see custom completions in our nu_scripts repo for pacman and pkgfile.

**Comment by ShalokShalom** [comment]
Hi 👍🏻 

I am not really custom yet with the terminology here, it seems. 😅 

@amtoine said, there are no nu_scripts for pacman yet, and he assumed, they would be there. 
What I inferred from this, is that Nu has special scripts for commands, that are used often, and who format the output without special invention by the user. 

I am generally willing to implement them, but I would need to with the command arguments, since they puzzle me over a lot. 

This issue is mostly just for the creation of pacman scripts for Nu in general, no matter who ends up implementing it.

**Comment by amtoine** [comment]
@ShalokShalom 
maybe this is something more suited for the https://github.com/nushell/nu_scripts?

**Comment by ShalokShalom** [comment]
Can we move it there, please?

**Comment by ShalokShalom** [comment]
I moved it

https://github.com/nushell/nu_scripts/issues/608
