### ISSUE TITLE
add `--abbreviated` / `-a` to `table` output _OR_ `abbrev` command?

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#10393]
### Related problem

@zhiburt What do you think about this? Is there a way to add an abbreviated table output kind of similar to what dataframes does? like `pipeline | table -a 5` (first 5 and last 5) items.

![image](https://github.com/nushell/nushell/assets/343840/20d909fa-334f-4012-9100-cf47950708b3)

@maxim-uvarov wrote a script to do it too.
![image](https://github.com/nushell/nushell/assets/343840/703e8eea-6db9-4c33-866c-a0e79ca90052)

Or maybe this is better as a composable command like `ls | abbrev 5` which lists the first 5 and the last 5 items of a list.

I'm kind of leaning towards a separate command instead of a parameter on table. Of course, this wouldn't work with streaming data, it would have to be collected to get the first x and last x.

Thoughts and ideas welcome.

### Describe the solution you'd like

something like our current dataframe output but where you can control how many appear above and below.

### Describe alternatives you've considered

Two thoughts.
1. a parameter on table
2. a `abbrev` command

**Comment by amtoine** [comment]
that would be great for large tables when not using dataframes :+1:

**Comment by maxim-uvarov** [comment]
Also, if this feature is released, I would request an option in the config called something like `$nu.table.abbreviate_if_longer_than`.

When the output of a structure (list or table) is not redirected, this option would allow nu to check if the output (list or table) is longer than the `$nu.table.abbreviate_if_longer_than` setting.

If it is longer, only an abbreviated version of the output would be displayed in the terminal by default.

I'm not sure if this is technically feasible at the moment, but from my user perspective, it seems like a nice improvement.

**Comment by amtoine** [comment]
@maxim-uvarov 
i think having a config for such a thing would make perfect sense :ok_hand: 
maybe setting it to `0` or a negative value or `null` could mean "*do not truncate / abbreviate*" and it could be the default value to avoid breaking the REPL rendering :+1:

**Comment by fdncred** [comment]
if this is a separate command, those can be parameters. The question in my mind still is, which option this should be.

1. a separate command with parameters
2. a flag to the `table` command with parameter(s)
3. a configuration so that `table` always prints out this way

I'm still leaning toward number 1, but I can see the value in 2 or 3.

**Comment by maxim-uvarov** [comment]
A separate command or `table` with parameters both seem okay to me.

A separate command, `abbrev`, might include properly named parameters like `--include_pipe_command` and `--comment` with `--comment_indentation`.

![image](https://github.com/nushell/nushell/assets/4896754/bcbc6dce-2795-430d-b969-97232e4c648f)

I'm not sure about these parameters or if they are worth adding to NuShell, but they seem like nice things to have.

**Comment by fdncred** [comment]
Ya, I'm not sure about those. Agree that they're quite niche.

**Comment by fdncred** [comment]
![image](https://github.com/nushell/nushell/assets/343840/b350032a-5f35-474f-9197-c532974ac8f9)
