### ISSUE TITLE
ls doesn't hightlight .fb2 files like other text documents

### ISSUE THREAD

**Issue by 1256-bits** [nushell/nushell#10396]
### Describe the bug

ls command highlights all text document files (txt, epub, doc, pdf, etc.) yellow.
FB2 files on the other hand are highlighted white as generic files. 

### How to reproduce

Call ls in on a .fb2 file

### Expected behavior

highlight .fb2 files yellow

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.84.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | d2abb8603abab43ec4a6d4ed56f9018790b99dce                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (Arch Linux rust 1:1.71.1-1) |
| cargo_version      | cargo 1.71.1                                                     |
| build_time         | 2023-08-23 02:21:39 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by sholderbach** [comment]
This coloring depends on the `LS_COLORS` string. This can either be defined by the environment variable `LS_COLORS` or if this is unset Nushell has its own default here:
 https://github.com/nushell/nushell/blob/bc7736bc9965d2df2e406f0e4fe9f4fe0d8c29f7/crates/nu-utils/src/utils.rs#L62

**Comment by 1256-bits** [comment]
Fb2 doesn't seem to be included by default but I believe it should as it is still a rather common file type.
Although it's probably not something worth creating a PR over.

**Comment by sholderbach** [comment]
If you are happy with resolving it locally please feel free to close the issue. Else if no one opens a PR for it, we won't change the `LS_COLORS`
