### ISSUE TITLE
nu_plugin_formats: line breaks in .{ics,cvf} not honored

### ISSUE THREAD

**Issue by joergsch** [nushell/nushell#10398]
### Describe the bug

ics and vcf file lines could be broken into multiple lines (if they exceed a given length) and prepended by space (to indicate that they have to be merged into one line)

### How to reproduce

"BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//hacksw/handcal//NONSGML v1.0//EN\nBEGIN:VEVENT\nUID:19970610T172345Z-\n AF23B2@example.com\nDTSTAMP:19970610T172345Z\nDTSTART:19970714T170000Z\nEND:VEVENT\nEND:VCALENDAR" | save cal.ics

open cal.ics

input cannot be parsed as .ics (property error: Line 6: Missing property name.)

### Expected behavior

content is displayed

### Configuration

| key                | value                                                                                                                     |
| ------------------ | ------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.84.1                                                                                                                    |
| branch             | main                                                                                                                      |
| commit_hash        | a9a82de5c48b23958ead9d011765396d29217630                                                                                  |
| build_os           | linux-x86_64                                                                                                              |
| build_target       | x86_64-unknown-linux-gnu                                                                                                  |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)                                                                                       |
| rust_channel       | 1.70.0-x86_64-unknown-linux-gnu                                                                                           |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)                                                                                       |
| build_time         | 2023-09-16 20:48:53 +02:00                                                                                                |
| build_rust_channel | release                                                                                                                   |
| allocator          | mimalloc                                                                                                                  |
| features           | default, sqlite, trash, which, zip                                                                                        |
| installed_plugins  | file, from eml, from ics, from ini, from vcf, gstat, highlight, json path, query, query json, query web, query xml, regex |

**Comment by fdncred** [comment]
If someone wanted to help with this. They could start by making sure the crate that does this work `ical` for `from ics` and `from vcf` works as expected. e.g. Is the problem in the upstream crate or the nushell implementation. If it's the upstream crate, then either a new crate is needed or a PR to the upstream crate is needed. If it's the nushell implementation, they could submit a PR to fix it.

**Comment by sholderbach** [comment]
Closed by #10577
