### ISSUE TITLE
Cusom command: default value shouldn't restrict argument's type

### ISSUE THREAD

**Issue by WindSoilder** [nushell/nushell#10410]
### Describe the bug

Notice that when we define a custom command's argument with default value, the type of argument will be bounded.

### How to reproduce

Run the following script:
```nushell
def a [b: any = null] { print ($b == null) }
a 3
```

Then nushell throws the following error:
```nushell
Error: nu::parser::parse_mismatch_with_full_string_msg

  × Parse mismatch during operation.
   ╭─[entry #16:1:1]
 1 │ def a [b: any = null] { print ($b == null) }
 2 │ a 3
   ·   ┬
   ·   ╰── expected nothing
   ╰────
```

### Expected behavior

I expected nu to print `false`

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.84.1                                    |
| branch             | main                                      |
| commit_hash        | 715c15779d16ae7eba9a73c6262b7ce7bd956b84  |
| build_os           | macos-x86_64                              |
| build_target       | x86_64-apple-darwin                       |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)       |
| rust_channel       | stable-x86_64-apple-darwin                |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)       |
| build_time         | 2023-08-29 16:48:30 +08:00                |
| build_rust_channel | release                                   |
| allocator          | standard                                  |
| features           | default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                           |

**Comment by WindSoilder** [comment]
Should the following two things behave differently?
```nushell
def a [b: any = 3] { print ($b | describe) }
def a [b = 3] { print ($b | describe) }
```
Currently, they all bound the type of `$b` to `int`

**Comment by amtoine** [comment]
@WindSoilder 
my two :coin:, i think
```nushell
def a [b: any = 3] { print ($b | describe) }
a "foo"
```
should definitely work because both `3: int` and `"foo": string` are of type `any` :+1:
