### ISSUE TITLE
`save` fails with custom `to ndjson` command

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#10429]
### Describe the bug

we now have `std formats "from ndjson"` but what about `to ndjon` to be able to hopefully `save foo.ndjson`? :smirk: 

i wanted to try that but i get an error :thinking: 

first of all, here is the command
```nushell
def "to ndjson" []: any -> string {
    each { to json --raw } | to text
}
```

### How to reproduce

1. try to dump the output of `ls` as NDJSON
```nushell
ls | save foo.ndjson
```
2. see the following error
```
Error:   × Internal error: can't run custom command with 'run', use block_id
```

### Expected behavior

i expected this to give the same results as
```nushell
ls | to ndjson | save foo.ndjson
```
which gives
```nushell
> open --raw foo.ndjson
{"name": "CODE_OF_CONDUCT.md","type": "file","size": 3444,"modified": "2023-07-26 13:32:23.457762168 +02:00"}
{"name": "CONTRIBUTING.md","type": "file","size": 18786,"modified": "2023-08-29 12:25:05.674565615 +02:00"}
{"name": "Cargo.lock","type": "file","size": 148614,"modified": "2023-09-19 15:56:31.406434514 +02:00"}
{"name": "Cargo.toml","type": "file","size": 5839,"modified": "2023-09-19 15:56:31.406434514 +02:00"}
{"name": "Cross.toml","type": "file","size": 666,"modified": "2023-08-29 12:25:05.678565620 +02:00"}
{"name": "LICENSE","type": "file","size": 1094,"modified": "2023-07-26 13:32:23.461762176 +02:00"}
{"name": "README.md","type": "file","size": 11990,"modified": "2023-09-11 09:07:31.889059657 +02:00"}
{"name": "assets","type": "dir","size": 4096,"modified": "2023-07-26 13:32:23.473762197 +02:00"}
{"name": "benches","type": "dir","size": 4096,"modified": "2023-09-04 09:06:29.293266800 +02:00"}
{"name": "crates","type": "dir","size": 4096,"modified": "2023-07-26 13:32:23.473762197 +02:00"}
{"name": "docker","type": "dir","size": 4096,"modified": "2023-08-29 12:25:05.778565710 +02:00"}
{"name": "rust-toolchain.toml","type": "file","size": 1105,"modified": "2023-08-29 12:25:05.778565710 +02:00"}
{"name": "scripts","type": "dir","size": 4096,"modified": "2023-09-06 12:38:37.246512586 +02:00"}
{"name": "src","type": "dir","size": 4096,"modified": "2023-09-13 15:05:13.984557075 +02:00"}
{"name": "target","type": "dir","size": 4096,"modified": "2023-07-26 16:45:01.434444741 +02:00"}
{"name": "tests","type": "dir","size": 4096,"modified": "2023-07-26 13:32:23.805762779 +02:00"}
{"name": "toolkit.nu","type": "file","size": 14959,"modified": "2023-09-11 09:07:31.901059560 +02:00"}
{"name": "wix","type": "dir","size": 4096,"modified": "2023-07-26 13:32:23.821762807 +02:00"}
```
from the Nushell repo :ok_hand: 

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.84.1                                   |
| branch             | main                                     |
| commit_hash        | f8939de14fd5d74fa35299cb95e5c09ce016d05c |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)      |
| rust_channel       | 1.70.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)      |
| build_time         | 2023-09-19 18:39:26 +02:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | gstat, nu_plugin_explore                 |

**Comment by fdncred** [comment]
sounds good to me, as long as we can also have a `to jsonl` that works identically.

**Comment by amtoine** [comment]
> sounds good to me, as long as we can also have a `to jsonl` that works identically.
>
i mean, this is an issue with Nushell's `save` not working properly with user-defined `to ...`, right? :thinking:

**Comment by amtoine** [comment]
> Oh, you're saying that you want the implicit conversion by extension if there's a `to blah` command and the extension is `.blah`.
>
exactly, just as the symmetric of the behaviour between `from blah` and `save foo.blah` :+1: 

> Hmmm, I'm not sure where that's supposed to happen in save.
>
well apart from the only place in the source base where this error is returned, not sure myself either :thinking:

**Comment by sholderbach** [comment]
Reading the test failures from https://github.com/nushell/nushell/pull/10519 this maybe isn't as much a problem with `save` itself than the name resolution during parsing for the `to` stub command and its subcommands. Both `to` and `from` have the same signature so this is a bit surprising that things seem to go well with `from` and fail with `to`
