### ISSUE TITLE
Explore httpie for possible use cases

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1042]
We have some barebones fetch/post support, but it would be fun to explore a project like https://github.com/jakubroztocil/httpie to see what kind of fun features we could add that would fit well with nushell.

h/t @dherman

**Comment by tchak** [comment]
I was thinking that something like https://github.com/ericchiang/pup would make much easier to work with html. I was able to pipe `pup` json output in to nu json table and it is very cool.
