### ISSUE TITLE
`tee` command

### ISSUE THREAD

**Issue by Zoybean** [nushell/nushell#10422]
### Related problem

Have I missed an existing feature? If so, I'd love if it could be documented in [Coming from Bash](https://www.nushell.sh/book/coming_from_bash.html#coming-from-bash).
If it doesn't exist already, it seems like a very worthwhile feature.

### Describe the solution you'd like

in bash I can run `cmd0 | tee log.txt | cmd1` in order to write a command's output to a log file and to another command (or just to screen).
In nu, I would like to be able to something similar, e.g. `cmd0 | tee {save log.txt} | cmd1`.
I can already do `let output = (cmd0); $output | save log.txt; $output | cmd1`, but that requires the first command to complete before the other operations will run, whereas the `tee` version would run the commands in parallel.

Ideally, `tee` would take a list of blocks or closures, and run each of them in parallel on the input stream as it becomes available, and would output the same stream it received as input. I'm not sure what should happen to the output of the tee'd commands.

### Describe alternatives you've considered

The output of `tee` could instead be the output of the commands that were passed into `tee`, making the above example `cmd0 | tee {save log.txt} {cmd1}`, however this seems to complicate the simple case of `cmd0 | tee {cmd1}`, which would need to be something like `cmd0 | tee {cmd1 | ignore} {$in}`. It also raises questions of how to combine the output of multiple commands without producing nonsense. Given these complications, I think it would make sense to ignore the output of each tee'd operation

**Comment by amtoine** [comment]
@Zoybean 
i've opened a not-yet-merged PR a few weeks back :wink: 

- https://github.com/nushell/nushell/pull/10128

**Comment by IanManske** [comment]
The `tee` command was added in version [0.91.0](https://www.nushell.sh/blog/2024-03-05-nushell_0_91_0.html#tee) (docs have been updated) :smile:
