### ISSUE TITLE
hash files instead of filenames

### ISSUE THREAD

**Issue by FedericoMuciaccia** [nushell/nushell#10432]
### Related problem

I would like the following command
```ls *.txt | get name | hash md5```
 to return a table with FileName and FileHash.

What's at the moment actually happening is instead an implicit conversion from FileName to String, so the resulting hash is the hash of the FileName string and not the hash of the file content.

### Describe the solution you'd like

There should be a clear distinction between hashing a filename and hashing a file content.

To keep backward compatibility, we can have `ls *.txt | get name | hash md5` hashing the filenames while we can introduce a new command like `ls *.txt | get name | open-file-content-as-byte-array | hash md5` to hash the file content.

**Comment by fdncred** [comment]
What about this?
```nushell
ls *.toml | upsert md5hash {|r| open -r $r.name | hash md5}
╭#┬───────name────────┬type┬─size─┬─modified──┬────────────md5hash─────────────╮
│0│Cargo.toml         │file│5.8 KB│4 days ago │80c7cc5671e806d3eca27db093fd971f│
│1│Cross.toml         │file│ 666 B│a month ago│d56c0efda5f320e3461d5f748c94c050│
│2│rust-toolchain.toml│file│1.1 KB│2 weeks ago│3eaf32496df90d31b0c4e446fee05a49│
╰─┴───────────────────┴────┴──────┴───────────┴────────────────────────────────╯
```

**Comment by amtoine** [comment]
in addition to the answer of @fdncred, i have the following in my scripts to hash all the content of a directory :+1: 
 => [`hash dir`](https://github.com/goatfiles/scripts/blob/710ff008452fb1781ed188d1821e7c1041963239/nu_scripts/src/misc.nu#L636-L654)
