### ISSUE TITLE
Consider musl target for aarch64 release

### ISSUE THREAD

**Issue by 101313** [nushell/nushell#10444]
### Related problem

Hello, users of musl based distros on aarch64 platforms could make use of such an artifact.

I'm not sure if that's likely to assume considerable effort but in case it doesn't it would be really welcome.

### Describe the solution you'd like

Having a musl aarc64 artifact produced as well on each release.

**Comment by hustcer** [comment]
I'm afraid we won't include it until we can find a stable way to build `aarch64-unknown-linux-musl` target. 
Actually I have tried but failed here: https://github.com/nushell/nightly/actions/runs/6257184093/job/16989252616
The build script could be found here: https://github.com/nushell/nightly/blob/feature/aarch64-musl/.github/workflows/release-pkg.nu#L79
And there seem to be a related issue here: https://github.com/rust-lang/rust/issues/89626

**Comment by 101313** [comment]
> I'm afraid we won't include it until we can find a stable way to build `aarch64-unknown-linux-musl` target. Actually I have tried but failed here: https://github.com/nushell/nightly/actions/runs/6257184093/job/16989252616 The build script could be found here: https://github.com/nushell/nightly/blob/feature/aarch64-musl/.github/workflows/release-pkg.nu#L79 And there seem to be a related issue here: [rust-lang/rust#89626](https://github.com/rust-lang/rust/issues/89626)

I've got the same exact error when trying to build on aarch64 alpinelinux on apple silicon. So this has to be indeed the case.

**Comment by 101313** [comment]
> I'm afraid we won't include it until we can find a stable way to build `aarch64-unknown-linux-musl` target. Actually I have tried but failed here: https://github.com/nushell/nightly/actions/runs/6257184093/job/16989252616 The build script could be found here: https://github.com/nushell/nightly/blob/feature/aarch64-musl/.github/workflows/release-pkg.nu#L79 And there seem to be a related issue here: [rust-lang/rust#89626](https://github.com/rust-lang/rust/issues/89626)

Greetings, I happened to dig into it a little bit more and possibly came up with a solution, at least a downstream one which should be indicative of a possible solution.

In specific, alpinelinux has nushell packaged on their [aports](https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/testing/nushell) tree, which applies the following [patch](https://gitlab.alpinelinux.org/alpine/aports/-/raw/master/testing/nushell/system-deps.patch) and does the following modification in its prepare step.

```shell
prepare() {
	default_prepare

	# Rust target triple.
	local target=$(rustc -vV | sed -n 's/host: //p')

	# Build against system-provided libs
	mkdir -p .cargo
	cat >> .cargo/config.toml <<-EOF
		[target.$target]
		git2 = { rustc-link-lib = ["git2"] }
		rusqlite = { rustc-link-lib = ["sqlite3"] }
	EOF

	cargo fetch --target="$CTARGET" --locked
}```

With my limited understanding, the solution lies in replacing sqlite with the sqlite-dynlib version which as the name implies does dynamic linking instead. 

I've got no actual solution to propose as I'm not exactly familiar with the ecosystem but I hope this helps pinpoint the issue.

**Comment by hustcer** [comment]
@101313 Thanks for the response, It looks a bit complicated to handle and some what costly to maintain in the long run. It's found that the patch file was created by @nibon7 and I'm wondering if there is a better way?

**Comment by 101313** [comment]
> @101313 Thanks for the response, It looks a bit complicate to handle and some what costly to maintain in the long run. It's found that the patch file was created by @nibon7 and I'm wondering if there is a better way to fix it in nushell official repo?

Hey, unless its just me for some reason, the project builds successfully. 
I've just had it build with the release flag and extras included as a feature.

You can check if it is the case inside CI as well id you'd like

**Comment by 101313** [comment]
> How did you build it? Can you show me your build script?

Just reproduced it, just to be sure. You need no additional steps whatsoever to build it.

```nushell
git clone --depth=1 https://github.com/nushell/nushell
cd nushell
cargo build --release
```
This will just work, at least it does for me.
![image](https://github.com/nushell/nushell/assets/99167477/2226458a-e9e2-45c2-bda8-ae2d235bb03f)

**Comment by hustcer** [comment]
We need to build it in Github action, and they don't have aarch64 hosts

**Comment by hustcer** [comment]
New `musl` release targets have been added in the nightly release: 
https://github.com/nushell/nightly/releases/tag/nightly-2c827d2
Anyone interested can give it a try.
