### ISSUE TITLE
options are broken?

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#10450]
related to
- https://github.com/nushell/nushell/pull/10424
- https://github.com/nushell/nushell/issues/7260

### Describe the bug
@WindSoilder 
i think https://github.com/nushell/nushell/pull/10424 did break Nushell options :cry: 

### How to reproduce

1. define
```nushell
def foo [--option: bool = false] { $option }
```

## before
```nushell
> foo
false
```
```nushell
> foo --option
Error: nu::parser::missing_flag_param

  × Missing flag argument.
   ╭─[entry #8:1:1]
 1 │ foo --option
   ·     ────┬───
   ·         ╰── flag missing bool argument
   ╰────
```
```nushell
> foo --option true
true
```

## after
```nushell
> foo
false
```
```nushell
> foo --option
false
```
```nushell
> foo --option false
Error: nu::parser::extra_positional

  × Extra positional argument.
   ╭─[entry #4:1:1]
 1 │ foo --option false
   ·              ──┬──
   ·                ╰── extra positional argument
   ╰────
  help: Usage: foo {flags}
```

### Expected behavior

i think i expected
```nushell
foo --option
```
to give `true` and
```nushell
foo --option false
```
to not give an error

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.85.1                                   |
| branch             |                                          |
| commit_hash        | 989a14709c0492b37ee026303dcf49756ace80f4 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)      |
| rust_channel       | 1.70.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)      |
| build_time         | 2023-09-20 22:42:11 +02:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | gstat, nu_plugin_explore                 |

**Comment by amtoine** [comment]
looks to me it's only with `bool`ean options, because
```nushell
def foo [-x: string = "foo"] { $x }
```
works fine

**Comment by WindSoilder** [comment]
Oh....My bad, thanks for the issue.   I'll take a look into this

**Comment by amtoine** [comment]
we'll have a look shortly :relieved:
