### ISSUE TITLE
`datetime-diff` doesn't work

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#10455]
`datetime-diff` from the `dt` standard library module always errors out with:

EDIT from maintainer:
this error appears to come when the two dates are the same, e.g. with
```nushell
datetime-diff (date now) (date now)
```
which gives
```nushell
Error: nu::shell::name_not_found

  × Name not found
    ╭─[NU_STDLIB_VIRTUAL_DIR/std/dt.nu:81:1]
 81 │     mut current = $current
 82 │     $current.millisecond = $current.millisecond + 1_000
    ·                                     ─────┬─────
    ·                                          ╰── did you mean 'second'?
 83 │     $current.second = $current.second - 1
    ╰────
```

I looked at the source code, the issue seems to be caused by `datetime-diff` still using milliseconds and microseconds.  Whereas `date to-record` doesn't have them.

**Comment by KAAtheWiseGit** [comment]
And unsure if I should file a separate issue, but `pretty-print-duration` doesn't work either, as it is trying to access cell paths of duration type variable.

**Comment by fdncred** [comment]
datetime-diff was written to specifically do this
```nushell
❯ print (datetime-diff (date now) 2019-05-10T09:59:12-07:00)
╭───────────┬───╮
│year       │4  │
│month      │4  │
│day        │10 │
│hour       │18 │
│minute     │35 │
│second     │35 │
│nanosecond │0  │
│millisecond│175│
│microsecond│66 │
╰───────────┴───╯
❯ pretty-print-duration (datetime-diff (date now) 2019-05-10T09:59:12-07:00)
4yrs 4months 10days 18hrs 36mins 43secs 345ms 26
```

I'm not sure why `date to-record` doesn't have millis or micros. I think @bobhy made those changes with his duration overhaul. Maybe he can answer?

**Comment by amtoine** [comment]
@KAAtheWiseGit 
when you say "`pretty-print-duration` does not work" and "`datetime-diff` errors out", what is that you are trying to do that gives these behaviours? running some `std` command? just starting up Nushell? :yum:

**Comment by KAAtheWiseGit** [comment]
@amtoine I wanted to use `datetime-diff` in a script I was writing.  I tried calling it, but it gave me the above error.  I subsequently tried to run `pretty-print-duration` on several inputs, and it also terminated with an error.

**Comment by amtoine** [comment]
oooh ok gotcha :+1: 

but i'm quite confused, `std dt datetime-diff` is not exported outside of the standard library, is it?
so how are you guys able to use it like this? :open_mouth:

**Comment by KAAtheWiseGit** [comment]
With `use std dt *`.  I was surprised to find out there were 11 various modules not exported by default.

**Comment by amtoine** [comment]
i could do
```nushell
> use std dt
> let diff = dt datetime-diff 2023-05-07T04:08:45+12:00 2019-05-10T09:59:12+12:00
> $diff.millisecond
0
> dt pretty-print-duration $diff
3yrs 11months 27days 18hrs 9mins 33secs
```
without any issue, am i missing something?

maybe you have a REPL example that is simpler than a script to see what the issue is? :yum:

**Comment by KAAtheWiseGit** [comment]
This is bizarre.  I just ran `datetime-diff` again and it works fine.  But I can swear it threw an error in the morning on the same command.

**Comment by KAAtheWiseGit** [comment]
Ah, I know that the issue is.  `datetime-diff (date now) 2023-01-01` did not work in the morning, but works now, because time has passed.  `datetime-diff (date now) (date now)` still throws an error.

**Comment by amtoine** [comment]
ooh let me try that

**Comment by amtoine** [comment]
oh yeah now i have the same issue

**Comment by amtoine** [comment]
did update the PR description :wink:

**Comment by KAAtheWiseGit** [comment]
@amtoine I believe it still errors out for two different times, as it did in the morning.  But I haven't been able to replicate it so far.

**Comment by amtoine** [comment]
yeah, if you or someone else is able to reproduce the same error in another scenario, then we'll need to add that to the issue for sure :+1:

**Comment by KAAtheWiseGit** [comment]
After looking at the source, I think the issue is that `borrow-second` can access `millisecond` field, before `$result` gets those fields inside `datetime-diff`.

It seems it can be fixed either by giving `$result` this fields earlier on, or removing them in favor of nanoseconds-only, as `date to-record` does.  It seems a bit weird to me that these two commands have different record presentation.

**Comment by KAAtheWiseGit** [comment]
If the team has an opinion, I can make and submit a pull request with either fix.

**Comment by amtoine** [comment]
> If the team has an opinion, I can make and submit a pull request with either fix.
>
looks to me just updating the current date record representation might be a simpler fix?

anyways, please go ahead :innocent:

**Comment by amtoine** [comment]
maybe more adding them everywhere so that we have the most precision? :thinking:

**Comment by bobhy** [comment]
@fncred, re: https://github.com/nushell/nushell/issues/10455#issuecomment-1729394011, I changed `date to-record` to add a nanosecond field, but it never had millisecond or microsecond.
And `std dt pretty-print-duration` declares its parameter as type `duration`, but it should be a record (as returned by `dt datetime-diff`.  Somehow that's not generating a type mismatch error?

@KAAtheWiseGit, it sounds like you're working on a fix. LMK if I can help.

**Comment by fdncred** [comment]
@bobhy seems like `date to-record` should also include millis and micros
