### ISSUE TITLE
Add support for `str append`

### ISSUE THREAD

**Issue by savente93** [nushell/nushell#10486]
### Related problem

Because [text is the universal interface](https://en.wikipedia.org/wiki/Unix_philosophy#Origin) appending strings is a very common opperation when interacting with other systems. Currently, this is of course this is possible in nushell using regular `append` and `str join` but it feels a little clunky to me for how common of an opperation it is. 

### Describe the solution you'd like

I'd like a `str append` subcommand to be added so that we can more easily append text. It also makes sense imo to add a corresponding `str prepend` subcommand. 
For example consider I have a list of directories:
```nu
let dirs = ['foo','bar','baz']
```
Both pre/appending strings for single strings is quite combersome imo. For example if I want to append `/*` to `foo` make it into a glob is like so:
```nu
echo 'foo' | append '/*' | str join
```
What I'd like it to ideally be is like so:
```nu
echo 'foo' | str append '/*'
```

It might not look like a lot, but I find that especially in long command chains this can be quite cumbersome. 

Additionally the problem is even worse if I want to appply it to a list. Currently the only way (that I could find) to prepend for example `~/` to them is using a closure:
```nu
echo $dirs | each { |ls| echo $s | prepend '~/' | str join }
```
(inner str join is also necessary to not end up with nested lists.
I think it would be quite intutive to have the append command simply apply the appending to each record:
```nu
echo $dirs | str append '~/'
```

### Describe alternatives you've considered

As this is mostly a shortcut QoL function, I 've not really considered many alternatives, but this seems by far the simplest idea to me. 

### Additional context and details

If this idea gets a signoff from a core member, I would be happy to work on it, as it's not that complex of a feature.

**Comment by amtoine** [comment]
@savente93 
what one could do right now is something like the following, in pure Nushell :yum: 
```nushell
def "str append" [tail: string]: [string -> string, list<string> -> list<string>] {
    let input = $in
    match ($input | describe | str replace --regex '<.*' '') {
        "string" => { $input ++ $tail },
        "list" => { $input | each {|el| $el ++ $tail} },
    }
}
```
```nushell
#[test]
def append_to_string [] {
    use std assert

    assert equal ("foo" | str append "/") "foo/"
    assert equal (["foo", "bar", "baz"] | str append "/") ["foo/", "bar/", "baz/"]
}
```

**Comment by savente93** [comment]
That is definitely very cool, and I definitely will be using that, thank you! However, as it's quite a complicated definition, I'd still argue that there is value in adding this, or at least mentioning the definition you gave somewhere in the documentation. Perhaps in the cookbook? I'm happy to go with whatever a maintainer/core member thinks is best

**Comment by amtoine** [comment]
@savente93 
i see a few ways to include that, from least to most *invasive* :thinking: 
- add it to the [cookbook](https://www.nushell.sh/cookbook/) as you proposed
- add it to the [`nu_scripts`](https://github.com/nushell/nu_scripts)
- add it to the standard library in a new `std str` module
- add it as a new built-in subcommand to `str`

i do not think myself the last one is necessary right now, we could start with either
- the cookbook: good example of *vectorization* + `match` + type + string manipulation but less discoverability
- the standard library: more discoverability because almost built-in

i guess we could make that a built-in if performance becomes a concern, but i do not think it is right now, right? :innocent:

**Comment by savente93** [comment]
agreed with all of your points. I'd be happy to make a PR for either (or both) of the std or cookbook solutions you mention. Got a preference?

**Comment by amtoine** [comment]
@savente93 
ooh yeah, please go ahead, even with both :yum: 

feel free to ping me for review in either of them :wink:
i'll assign you to this issue so that others know there is someone on it :ok_hand:

**Comment by fdncred** [comment]
There are already multiple ways to append strings. I doubt a new command will make it into nushell. Documentation or cookbook examples sound good to me though.

We have:
* +
* ++
* string interpolation
* reduce
* str replace
* str append
* str prepend
* str join

There are probably more creative ways to do it too.

**Comment by amtoine** [comment]
@fdncred 
i'm not sure we have `str append` and `str prepend`, do we? :thinking:

**Comment by fdncred** [comment]
> @fdncred i'm not sure we have `str append` and `str prepend`, do we? 🤔

oops, fixed it.

**Comment by savente93** [comment]
Does that mean that adding it to the `std` is off the table? I agree that there are multiple other ways, but I see this more as a QoL for new users, myself included.

**Comment by savente93** [comment]
I've at least added the documentation as discussed where I could, Waiting on OK from member on whether PR adding it to the std would be accepted. If so, I'll open a PR for that one as well

**Comment by amtoine** [comment]
i don't mind either way personally :yum: 

`str append` feels close enough to built-in `str ...` command and sounds like something that folks might want to use :relieved: 

@fdncred 
why not extending `str ...` with a new `str append` in the standard library? :innocent:

**Comment by fdncred** [comment]
Seems like JT said that we didn't want it. My only concern is with adding anything to the stdlib, the performance of startup will decrease.

**Comment by amtoine** [comment]
i do not see JT in the discussion but ok :ok_hand: 

i'm not sure adding or not commands to the standard library should be dictated by the startup time... that sounds like a parser issue only, right? :confused:

**Comment by fdncred** [comment]
I think I'm thinking of your cartesian pr, sorry.

Yes, it's a parser/eval issue, but I don't want to add so much stuff in stdlib that it produces a worse startup. So, ya, I think it should dictate what goes in the stdlib or not, until it's fixed.

**Comment by savente93** [comment]
sounds like you're pretty ademant about it, so with the documentation already being merged and from your descriptions it sounds like the parser/eval improvement isn't imintent, I think we've done all we can on this issue, so I'll be closing it.

**Comment by fdncred** [comment]
The thing is, I'm not the only vote. The parser/eval may be fixed in the future. There's work happening in that area.

My vote would be to put `str append` into our nu_scripts repo. Maybe we should start a stlib-candidate folder, like I created a while back before we had the stdlib?

**Comment by savente93** [comment]
I'd be happy to make a PR to `nu_scripts` for this. Since it's a seperate repo and beyond that, there's nothing left for this issue I'll leave it closed. I can mark it as completed as opposed to wont-fix if you prefer though
