### ISSUE TITLE
`glob` command supports more metacharacters than filesystem commands like `cp` and `mv`

### ISSUE THREAD

**Issue by bobhy** [nushell/nushell#10498]
### Describe the bug

It looks like only the `glob` command supports the the csh-style `{}' metacharacters, the file utilities do not.

You could argue this is more of an enhancement request, but I think globbing is so fundamental a shell experience that it must be consistent across use cases. 

### How to reproduce

```
> touch a.foo a.bar
> ls
╭───┬───────┬──────┬──────┬──────────╮
│ # │ name  │ type │ size │ modified │
├───┼───────┼──────┼──────┼──────────┤
│ 0 │ a.bar │ file │  0 B │ now      │
│ 1 │ a.foo │ file │  0 B │ now      │
╰───┴───────┴──────┴──────┴──────────╯
> glob a.{foo,bar}
╭───┬────────────────────────────────────╮
│ 0 │ /home/bobhy/src/rust/work/r3/a.bar │
│ 1 │ /home/bobhy/src/rust/work/r3/a.foo │
╰───┴────────────────────────────────────╯
```
So `glob` supports `{}`.  Great!
```
> mkdir dir_a
> cp a.{foo,bar} dir_a
Error:   × No matches found
   ╭─[entry #187:1:1]
 1 │ cp a.{foo,bar} dir_a
   ·    ─────┬─────
   ·         ╰── no matches found
   ╰────

> ucp a.{foo,bar} dir_a
Error: nu::shell::file_not_found

  × File not found
   ╭─[entry #188:1:1]
 1 │ ucp a.{foo,bar} dir_a
   ·     ─────┬─────
   ·          ╰── file not found
   ╰────
```
`cp` and `ucp` do not.  Not shown here, but neither do `rm`, `mv`, `touch` .

### Expected behavior

I'd really like all Nu globbing to support '{}' metacharacters.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.85.1                                   |
| branch             | main                                     |
| commit_hash        | 95a4649cc9933045d275d508f33676da16159d18 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)      |
| rust_channel       | 1.70.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)      |
| build_time         | 2023-09-24 10:42:53 -07:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

### Additional context

Looking at the code, the filesystem utilities use crates/nu-glob, but `glob` uses `wax::Glob`.

Understood, I could do:
```
glob a.{foo,bar} | each {|p| cp $p dir_a}
```
with a minor loss of efficiency.  But that's just papering over the crack...

**Comment by fdncred** [comment]
We plan on replacing `rm`, `touch`, and `mv` like we're doing with `cp` with `ucp`. 

There is a `str expand` character that's supposed to help with the `{}` type of globbing. `help str expand` shows a bunch of examples.

**Comment by bobhy** [comment]
Yah, that's another workaround, I'm still advocating for using the same
glob everywhere in Nu.

Understood, uutils/ is the future.  and that's a good time to review
globbing for all the filesystem utilities.
I'd like to them all be clear on which arguments are `<glob>` and which are
`<path>`.   `ucp` help currently says ` ...paths <path>: Copy SRC file/s to
DEST`, which doesn't call out dest at all, and doesn't say that src can be
`<glob>` (which it can be).

Maybe Nushell needs a `leading...` argument type which is the reverse of
`...rest`?  It's the pattern many file system utilities have and there's no
clean way to express it in Nu.

**Comment by fdncred** [comment]
Yup, I'd like to have uniform globbing as well.

It looks like `ucp` takes `SyntaxShape::Filepath` and `cp` takes a `SyntaxShape::GlobPattern`. I'm not really sure what the opposite of `...rest` means. 

It is kind of weird that `ucp` has no dest though. @dmatos2012 Can you speak to this?

You should feel free to try and homogenize globbing via PRs.

**Comment by dmatos2012** [comment]
> It is kind of weird that `ucp` has no dest though. @dmatos2012 Can you speak to this?

Because in `ucp` , source can be either`cp src dst` or `ucp src1 src2 dst/`, or globbing as well `ucp src* dst/`, thus there needed to be a way to grab all of them and do the parsing via code, rather than with nushell parser. 

If specified separately then it made it much more difficult as to specify more than one source. For example, we would need to : `ucp [src1 src2] dst/`. 

Also, before we simplified the arguments, ucp also supported `--target-directory` which would invalidate having src and dst, as `ucp --target-directory dst src` would have `dst` first.

**Comment by bobhy** [comment]
I agree `ucp` is doing the parsing of its arguments correctly in code.  But it cannot express this pattern in the signature declaration, so the help will be wrong.
If there were a  `leading...` pattern, the help could look something like this:
```
Parameters:
  src...<glob>: SRC files to copy
 dest<path>: DEST directory to copy into, or, if SRC is a single file, DEST file to copy to.
```
In the code, there could be something like this:
```
let src: Vec<Spanned<String>> = call.leading(engine_state, stack, 0)?;
let dest: Spanned<String> = call.req(engine_state, stack, 1)?;
```        
        
This is technically elegant, and (I think) pretty straightforward to implement, but maybe not worth the additional maintenance complexity long term.  Of the file system utilities, I think only `cp` and `mv` have this pattern.  

Without it, these commands should just add some text to the signature declaration clarifying how the args are parsed.

If that seems like an ugly alternative, LMK, I'll take a deeper look at implementing this arg pattern.

**Comment by jntrnr** [comment]
This issue is not a bug. It's expected that `glob` supports more syntax than the commands. The idea was to have file utilities be more conservative because of what's supported in the various OSes for filenames. `glob` is there to allow for more creativity in globbing than we'd want to enable by default.

**Comment by bobhy** [comment]
Pretty subtle distinction to expect the user to make?  `glob` supports the negated matches,  explicit depth and type filters which seem like good reasons to have the separate command. But having 2 different glob patterns? Why would user want that, considering that even the more conservative pattern already causes unexpected behavior (#10571)?
From a team perspective, why would you want to support 2 glob libraries, one of which is unique to the project and so entirely on you to support?

**Comment by fdncred** [comment]
We have 2 glob libraries because we crippled nu-glob in order to avoid some of these errors, and one more powerful that really had nothing to do with `ls` and is strictly for searching a file system. 

I guess we should revert the changes I made to nu-glob to bubble up the errors, since we've been living with the errors for a while, and no one seems to be able to fix it without adding a --glob/--no-glob parameter and just live with 2 different globs.

I personally think we need a different solution for `ls`. Something that maybe uses something other than globs or handles escapes better. I think the problem is really just because we're cross-platform and it's difficult to please all file systems. Just my take.

**Comment by bobhy** [comment]
Looking more into what `wax` currently does, I agree nu should retain a different and simpler glob syntax for command line args.  

For an example of a shell trying to do too much with glob syntax at command line, see [zsh](https://wiki.zshell.dev/community/zsh_guide/roadmap/expansion).

But I opened this issue with the desire to support `{}` in command line globbing, and still think it makes sense.  

I'm going to change my PR to retain `nu_glob` but enhance it.  The PR already has a useful fix that's independent of the globbing library used...

`{}` has unexpected nuances!  It's not strictly a globbing pattern, at least the `bash` implementation of it can generate strings that don't exist as current files (and I remember `csh` did likewise, you could do `cp a.{out,new}`).  `wax` uses it strictly as a pattern matching construct.  Hmm?
So it's not strictly     `bash`, at least, doesn't consider this globbing, it has a whole separate option

**Comment by bobhy** [comment]
Closing this issue as "by design".  It's a difference in glob syntax that will confuse users and should be documented (with a justification that someone else will have to provide, since I can't).

**Comment by fdncred** [comment]
There's still `str expand`.

**Comment by bobhy** [comment]
Yah, though not built into my muscle memory (yet).
