### ISSUE TITLE
magenta_reverse and purple_reverse present different when used with a structured color

### ISSUE THREAD

**Issue by colemickens** [nushell/nushell#10490]
[As discussed with @fdncred in Discord](https://discord.com/channels/601130461678272522/601130461678272524/1155503705890771044):

It seems like that `magenta_reverse` and `purple_reverse` appear differently when used in a structured color. This is despite them appearing the same when used "naively" as a non-structured call to just `ansi purple_reverse` or `ansi magenta_reverse`.

![screenshot-1695563335](https://github.com/nushell/nu-ansi-term/assets/327028/0f63ecd1-3774-42ed-921e-51ca2760bb51)

This is also in contrast to when used in `ansi --list`:
![screenshot-1695563557](https://github.com/nushell/nu-ansi-term/assets/327028/ca2550ca-bccd-4435-bb95-36a435f9ba58)

@fdncred shared this:

![image](https://github.com/nushell/nu-ansi-term/assets/327028/2a879e1e-d7a0-43f9-9dda-93a123e847e3)

**Comment by fdncred** [comment]
figured it out. it was a nushell issue. thanks!
