### ISSUE TITLE
Crashes on Windows when Ctrl-L

### ISSUE THREAD

**Issue by mikheyevav** [nushell/nushell#1050]
Env: 
Win 10, v1803
NuShell 0.6.1

Nu shell crashes on ctrl -l.
With error message: 
Error: Io(Os { code: 87, kind: Other, message: "Paramètre incorrect." })

**Comment by jonathandturner** [comment]
I'm able to reproduce this when using the starship prompt. Ctrl-L should clear the screen, but with the starship prompt it looks like drawing takes just long enough to cause rustyline to fail.

Thanks for the report.

**Comment by steveklabnik** [comment]
I am also hitting this issue.
