### ISSUE TITLE
Nu panics when calling a function with an invalid signature with arguments

### ISSUE THREAD

**Issue by 13x1** [nushell/nushell#10530]
### Describe the bug

```
/tmp/nu> cat repr.nu                                                    09/28/2023 11:01:08 AM
def invalid_sig [bool: boolean] {
    print $bool
}

def main [] {
  invalid_sig 
}
/tmp/nu> nu repr.nu                                                     09/28/2023 11:01:11 AM
Error: nu::parser::unknown_type

  × Unknown type.
   ╭─[/tmp/nu/repr.nu:1:1]
 1 │ def invalid_sig [bool: boolean] {
   ·                        ───┬───
   ·                           ╰── unknown type
 2 │     print $bool
   ╰────

/tmp/nu> vim repr.nu                                                    09/28/2023 11:01:15 AM
/tmp/nu> cat repr.nu                                                    09/28/2023 11:01:29 AM
def invalid_sig [bool: boolean] {
    print $bool
}

def main [] {
  invalid_sig true # <-- added 
}
/tmp/nu> nu repr.nu                                                     09/28/2023 11:01:30 AM
thread 'main' panicked at 'Internal error: can't run a predeclaration without a body', crates/nu-protocol/src/signature.rs:644:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
/tmp/nu> RUST_BACKTRACE=1 nu repr.nu                                    09/28/2023 11:01:40 AM
thread 'main' panicked at 'Internal error: can't run a predeclaration without a body', crates/nu-protocol/src/signature.rs:644:9
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <nu_protocol::signature::Predeclaration as nu_protocol::engine::command::Command>::run
   3: nu_engine::eval::eval_call
   4: nu_engine::eval::eval_expression_with_input
   5: nu_engine::eval::eval_element_with_input
   6: nu_engine::eval::eval_block
   7: nu_engine::eval::eval_block_with_early_return
   8: nu_engine::eval::eval_call
   9: nu_engine::eval::eval_expression_with_input
  10: nu_engine::eval::eval_element_with_input
  11: nu_engine::eval::eval_block
  12: nu_engine::eval::eval_block_with_early_return
  13: nu_cli::util::eval_source
  14: nu_cli::eval_file::evaluate_file
  15: nu::run::run_file
  16: nu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### How to reproduce

Call this program:

```
def invalid_sig [bool: boolean] {
    print $bool
}

def main [] {
  invalid_sig true # <-- added 
}
```

### Expected behavior

It should report the error, like in the first invocation above

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.84.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.72.0 (5680fa18f 2023-08-23) (built from a source tarball) |
| cargo_version      | cargo 1.72.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by sholderbach** [comment]
This issue seems to be resolved by updating to `0.85.0`.

Can not directly identify which PR fixed this but there has been some work ongoing around the handling of type annotations.
