### ISSUE TITLE
Feature: Preview intermediate results

### ISSUE THREAD

**Issue by Aloso** [nushell/nushell#1053]
When building a more complex command, it would be very helpful if intermediate results were shown below the command line, **without needing to press Enter**.

Currently, when I type a complex command like this:

```bash
ls | where type == File | sort-by name | where modified < 4h
```

I usually press Enter after each step to inspect the intermediate result. Then I press ArrayUp to continue typing. The downside is that the intermediate results are visible when scrolling through the shell history, so it's hard to find anything.

What I would like is similar to how the console in Google Chrome works. When you type something, you see the result immediately, without pressing Enter:

![chrome](https://user-images.githubusercontent.com/15658558/70158915-59867900-16b8-11ea-9634-bf047f1157be.png)

When you continue to type, the preview disappears or is replaced with the next preview.

In nushell, this should be limited to commands without side effects. Note that most internal commands are side-effect free! The following commands could be whitelisted for previews:

```
add           help          shells
append        histogram     size
average       inc           sort-by
count         last          split-*
date          lines         str
echo          nth           sum
edit          pick          sys
env           pivot         tags
first         prepend       to-*
format        ps            trim
from-*        reject        version
get           reverse       where
group-by
```

**Comment by pwnorbitals** [comment]
What about a configurable preview shortcut instead of making it the default ? It could be pretty painful is the output is large, and the preview shortcut could be used with any command as long as the user is okay with the preview side-effects

**Comment by cauebs** [comment]
Maybe just a way to run that line and copy it to the next prompt, something like Alt+Enter?

**Comment by cauebs** [comment]
You're not being helpful, bot.

**Comment by jntrnr** [comment]
This will likely not be added as the commands may cause side effects (like removing files, renaming files, getting contents from a website, etc), so they aren't safe to preview until you say the command is ready to run and press enter.
