### ISSUE TITLE
Unhelpful error when assertion fails due to different data type

### ISSUE THREAD

**Issue by savente93** [nushell/nushell#10549]
### Describe the bug

When assert fails due to the data types of some recoords being different but the string representation are equivalent the assertion error is quite unhelpful isnce it shows the same string. This one had me tear my hair out for quite a while

### How to reproduce

```nu
use std assert
assert equal {one:1 two:2} {one:"1" two:"2"}
```

### Expected behavior

The error should incorporate at least some information about the datatype or make an effort to differentiate the string representation.  Ideally it would point out that the record fields have incompatible types, but even putting quotes around the string values would help. 

### Screenshots

![image](https://github.com/nushell/nushell/assets/17224168/f3ad7097-01c7-47ef-a2be-50b522453ccc)

### Configuration

| key                | value                                         |
| ------------------ | --------------------------------------------- |
| version            | 0.85.0                                        |
| branch             |                                               |
| commit_hash        |                                               |
| build_os           | linux-x86_64                                  |
| build_target       | x86_64-unknown-linux-gnu                      |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13)           |
| rust_channel       | stable-x86_64-unknown-linux-gnu               |
| cargo_version      | cargo 1.72.1 (103a7ff2e 2023-08-15)           |
| build_time         | 2023-09-25 16:17:07 +02:00                    |
| build_rust_channel | release                                       |
| allocator          | mimalloc                                      |
| features           | dataframe, default, sqlite, trash, which, zip |
| installed_plugins  |                                               |

**Comment by amtoine** [comment]
good catch :ok_hand:

when i look at all the following, it does not look like an issue with the conversion itself and the format, so that might just be an internal thing in the library :thinking:
```nushell
> {one:"1" two:"2"} | to json --raw
{"one": "1","two": "2"}
```
```nushell
> {one:1 two:2} | to json --raw
{"one": 1,"two": 2}
```
```nushell
> {one:1 two:2} | to nuon --raw
{one: 1, two: 2}
```
```nushell
> {one:"1" two:"2"} | to nuon --raw
{one: "1", two: "2"}
```

**Comment by amtoine** [comment]
ok @savente93 i found the culprit :smirk: 

```nushell
> print $'({one:"1" two:"2"})'
{one: 1, two: 2}
> print $'({one:1 two:2})'
{one: 1, two: 2}
```

will pull up a quick PR :+1:
