### ISSUE TITLE
How can I get current terminal size information?

### ISSUE THREAD

**Issue by nobiit** [nushell/nushell#10550]
### Related problem

The user wants to get information about the number of rows/columns of the terminal, so that they can adjust the output appropriately (for example, center it?)

### Describe the solution you'd like

Save the current terminal's line/column number information into $nu. For example $nu.cols and $nu.rows

**Comment by amtoine** [comment]
@nobiit 
this sounds like `term size` could be what you are looking for :yum:

**Comment by sholderbach** [comment]
We have the command [`term size`](https://www.nushell.sh/commands/docs/term_size.html) for that

**Comment by nobiit** [comment]
Thank @sholderbach , my shortcoming
