### ISSUE TITLE
Display all columns in JSON files with `open` command.

### ISSUE THREAD

**Issue by tm99hjkl** [nushell/nushell#10556]
### Question

Hi community,

I like and use the `open`, `select`, and `where` commands for analyzing JSON files.

However, when I use the `open` command on a JSON file with a high number of columns, those columns that do not fit within the screen get truncated and displayed as `…`.

Is there a way to display all columns by scrolling, perhaps with the use of left/right (or h/l) keys? (I‘m imaging something like the `—wrap never` mode in the [`bat` command](https://github.com/sharkdp/bat).)

**Comment by sholderbach** [comment]
We have `explore` as a pager that allows you to browse through the data

**Comment by tm99hjkl** [comment]
Thank you very much for the quick response. 

Is there a way to change the command-line operations for `explore`? 
I'd like to map `Up` to `Ctrl-p` and `Down` to `Ctrl-n`, for example.

**Comment by fdncred** [comment]
I think you can also do `open file.json | columns` and this will show you all of the columns.

I don't believe there is any way to change the keybindings in explore right now.

**Comment by tm99hjkl** [comment]
Understood, thank you for letting me know.
