### ISSUE TITLE
Would a url decode command be welcome?

### ISSUE THREAD

**Issue by lpchaim** [nushell/nushell#10563]
### Question

Hey all, I've been wondering if a PR implementing a `url decode` comand would be welcome, essentially doing the opposite of the existing `url encode` [implemented here](https://github.com/nushell/nushell/pull/7664). Unless I'm missing something, said feature doesn't exist yet so my intention is to go ahead and implement it if this sounds reasonable, as per the contribution guide.

**Comment by fdncred** [comment]
I wouldn't have a problem with it. Not sure what other maintainers think though. Seems complimentary to me.

**Comment by jntrnr** [comment]
This sounds similar to `from url`. It's this similar to that? If so, maybe the current command needs a better name

**Comment by amtoine** [comment]
then should `url decode` be called `to url`? :thinking: 
and what about the other `url ...` commands? :confused: 

maybe having all these in a special `url` command can still make sense :yum:

**Comment by fdncred** [comment]
if that's what `from url` does, then i'd support renaming it to `url decode`. Seems much more discoverable having it in the family of url commands.

**Comment by lpchaim** [comment]
> This sounds similar to `from url`. It's this similar to that? If so, maybe the current command needs a better name

I might be missing something but I can't find said `from url` command and going by #6854, it'd seem it was one of the proposed names for the final `url parse` command. Assuming that's what you're referring to, it's not quite the same. `url parse` creates a record from a ful URL, while the proposed `url decode` would simply transform an input string into a new, decoded string. In fact, I just checked and `from url` seems to break when supplied with URL encoded parameters, so it doesn't seem at all prepared to deal with that. Not that I'm trying to argue it should, necessarily, but maybe it's also something to consider.

> then should `url decode` be called `to url`? 🤔 and what about the other `url ...` commands? 😕
> 
> maybe having all these in a special `url` command can still make sense 😋

With the above context, I personally still believe `url decode` would be more appropriate and also more symmetrical with the existing commands. I might be biased since I'm a web developer by trade but having the url commands on their own namespace seemed like a natural fit when I learned about them, since URLs have quite unique, particular behavior.

**Comment by amtoine** [comment]
> With the above context, I personally still believe `url decode` would be more appropriate and also more symmetrical with the existing commands. I might be biased since I'm a web developer by trade but having the url commands on their own namespace seemed like a natural fit when I learned about them, since URLs have quite unique, particular behavior.
>
sounds fair to me :+1: 

also, i feel like `from ...` and `to ...` are mostly there for file formats, so one (me as well) could argue that URLs are not file formats and thus should not be added under these :smirk:

**Comment by lpchaim** [comment]
Had a free morning so I've come up with and performed initial tests on an implementation, I reckon I'm going to polish it some more then go ahead and make a PR within the next few days if no further issues are raised. Hopefully that's the right way to go about this, it's my first time contributing so I'm trying to be extra mindful and not too annoying 😅
