### ISSUE TITLE
explore misaligns columns/lines when hitting right arrow sometimes

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#10560]
### Describe the bug

When testing the `explore` command I like to do `$env | explore` because it can be complex. While doing this, I noticed that sometimes the alignment of lines can get off. Here is an example.

### How to reproduce

1. `$env | explore`
2. hit `t` (for table/transpose)
3. hit `e` (for expand)
4. Down-Arrow until you get to menus - alignment looks good (or page down/fn page down on mac)
![image](https://github.com/nushell/nushell/assets/343840/809cf472-7359-4dcb-b432-3690c4ff2573)
5. Hit right arrow - alignment looks good
![image](https://github.com/nushell/nushell/assets/343840/a45f3535-dbda-40f7-b8f8-7f55137bb4cb)
6. Hit right arrow again - alignment is messed up now
7. Notice how the lines of type, style, and source are now misaligned.
![image](https://github.com/nushell/nushell/assets/343840/e88f8715-2291-4d7b-a221-0d2e18212286)

### Expected behavior

lines stay aligned

### Configuration

|key|value|
|-|-|
|version|0.85.1|
|branch|main|
|commit_hash|fa2e6e5d5340ce0d12dca8218aae3561fb1d6231|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.70.0 (90c541806 2023-05-31)|
|rust_channel|1.70.0-aarch64-apple-darwin|
|cargo_version|cargo 1.70.0 (ec8a8a0ca 2023-04-25)|
|build_time|2023-09-30 09:49:00 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|dataframe, default, extra, sqlite, trash, which, zip|
|installed_plugins|emoji, file, from eml, from ics, from ini, from parquet, from plist, from vcf, gstat, highlight, hist, inc, json path, periodic-table, plot, pnet, query, query json, query web, query xml, regex, str bexpand, str similarity, xyplot|

### Additional context

/cc @zhiburt @rgwood

**Comment by zhiburt** [comment]
Hi there

> Notice how the lines of type, style, and source are now misaligned.

I am pretty sure,
It must be messed at step 5 already; you just don't see it.

Could you try to expand the term size and make a screenshot?

PS: Can't reproduce easily

**Comment by fdncred** [comment]
@zhiburt I made the font smaller and maximized the window. It seems like it's drawing ok when it fits on the window.
![image](https://github.com/nushell/nushell/assets/343840/a5a36fde-d83b-442d-8a85-67c9939f292d)
