### ISSUE TITLE
Completions from a quote don't show anything

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#10586]
### Describe the bug

Try typing `"<tab>` on any command that takes a directory for filepath.

I've seen folks do this in the first few seconds they use Nushell, so it's definitely muscle memory (I also find myself doing it from time to time). This shouldn't return zero results, we should just complete as normal.

### How to reproduce

1. See above

### Expected behavior

Hitting tab after typing a double quote should allow for completions as normal.

Unfortunately, currently you get no completions at all.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.85.1                                   |
| branch             | main                                     |
| commit_hash        | 5c15a4dd6e0c573ac7d902fe8af93e98f332f4ed |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)      |
| rust_channel       | 1.70.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)      |
| build_time         | 1980-01-01 00:00:00 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
unrelated - i wonder why your `build_time` is messed up in your version command

**Comment by bobhy** [comment]
Interesting!  `ls ""<tab>` (two  double or even single quotes) displays the expected completions, and accepting one rewrites the command without quotes.

**Comment by ericdching** [comment]
This is a workflow killer for me. On macOS anyway you can start tabbing through folders and if one of them contains a space it will convert to quotes then subsequent tab navigation fails.

It appears to have been introduced with this change:
```
5c15a4dd6 Fish-like completions for nested directories (#10543)
```
I could not reproduce with the previous commit.

**Comment by fdncred** [comment]
@lavafroth Would you be able to look at @ericdching's issue based on your PR? I'm wondering if we just didn't test enough with paths with spaces.

**Comment by lavafroth** [comment]
I'll look into the code shortly. Didn't know this feature existed. Should be an easy fix!

**Comment by ericdching** [comment]
A specific example that tripped me up:

```
.
├── a
└── a b
    └── c d
```

cd a`<tab>` cycle to `a b` and press `<enter>` to select it.
Press `<tab>` again - should complete to `a b/c d` instead I get `NO RECORDS FOUND`

I should also be able to enter a character of the next directory outside the quote and it should rewrite the line completing that match.
cd \`a b\`c`<tab>` -> should complete to `a b/c d` instead I get `NO RECORDS FOUND`

**Comment by jntrnr** [comment]
@ericdching - can you file a separate issue for what you found?
