### ISSUE TITLE
Introduce a spread operator

### ISSUE THREAD

**Issue by 101313** [nushell/nushell#10598]
### Related problem

Spread operator, the process of de-structuring as they call it in javascript.

Essentially, an elegant way to unpack objects, or records in our case, arrays and other data types which may be eligible without the need of introducing another component in the pipeline.

Destructuring record members
```nushell
let rec = {a: 1, b: 2} 
let updated_rec = {...$rec, c: 4 }
```
as an alternative to its counterpart
```nushell
let rec = {a: 1, b: 2}
let updated_rec = ($rec | merge {c: 4})
```

Example using a list:
```nushell
$env.config.keybindings = ($env.config.keybindings | append {
    name: delete_one_word_forward
    modifier: control
    keycode: char_d
    mode: emacs
    event: {edit: deleteword}
})
```

Could be written as:
```nushell
$env.config.keybindings =  [
    ...$env.config.keybindings
    {
        name: delete_one_word_forward
        modifier: control
        keycode: char_d
        mode: emacs
        event: {edit: deleteword}
     }
]
```

It allows for the omission of the pipe operator, hence the wrapping parentheses are omitted as well.

Another example of spreading into a list:
```nushell
[10..0] | reduce -f [] {|i,a| [...$a $"Ready in ($i)" }
```

### Describe the solution you'd like

There is already a similar [syntax](https://www.nushell.sh/book/custom_commands.html#rest-parameters) built in to the language, so using the triple dot operator seems to make sense as well, but its likely up for debate.

I composed the draft rather quickly so I didn't put a lot of thinking into demonstrating how it could improve the syntax amongst many cases but I'm sure there are better examples than the ones cited above.

### Describe alternatives you've considered

The de-facto append.

### Additional context and details

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

**Comment by fdncred** [comment]
We've talked about having a spread operator several times. The consensus, as I recall, was that we'd like to have one.

**Comment by 101313** [comment]
> We've talked about having a spread operator several times. The consensus, as I recall, was that we'd like to have one.

Glad its been a topic of discussion already, I didn't come up with anything relevant while skimming through the issues. I hope bringing it up as a standalone issue was the right thing to do.

In any other case, please let me know

**Comment by fdncred** [comment]
Yup, this was fine. Now we just need someone motivated enough by it to send in a PR.

**Comment by amtoine** [comment]
@101313 
correct me if i'm wrong but, because `$env.config.keybindings` is a `list<any>`, shouldn't the example you give above be the following instead? :open_mouth: 

```nushell
$env.config.keybindings =  [
    ...$env.config.keybindings
    {
        name: delete_one_word_forward
        modifier: control
        keycode: char_d
        mode: emacs
        event: {edit: deleteword}
     }
]
```

**Comment by 101313** [comment]
@amtoine 
Correct, obvious catch for anyone with more than a few days into the shell.. A bit embarrassing but thanks in any case =) 
I prepended another case for usage within a set as well. Thanks!

**Comment by amtoine** [comment]
> @amtoine Correct, obvious catch for anyone with more than a few days into the shell.. A bit embarrassing but thanks in any case =) I prepended another case for usage within a set as well. Thanks!
>
ehe no worries :relieved: 

i'm glad i understood the *spread operator* well :wink:

**Comment by ysthakur** [comment]
In case anyone wants to discuss this feature, I made a [HackMD](https://hackmd.io/@ysthakur/nu-spread) for sketching it out

**Comment by ysthakur** [comment]
I'm not sure this issue can be closed just yet, since it also asks for spreading in records and spreading arguments to commands.

**Comment by amtoine** [comment]
@ysthakur 
yeah the PR was just about lists it appears :+1:

**Comment by amtoine** [comment]
@ysthakur 
we just had a meeting and decided a few things, if you're still up to working on the spread operator :blush: 

- make the spread work on internals, e.g.
```nushell
let files = [a.txt, b.txt]
ls ...$files
```
- make the spread of arguments to externals explicit, e.g.
```nushell
let args = [--allow-empty, --no-gpg-sign]
git commit ...$args --message "foo"
```
instead of the current
```nushell
let args = [--allow-empty, --no-gpg-sign]
git commit $args --message "foo"
```

**Comment by 101313** [comment]
> I'm not sure this issue can be closed just yet, since it also asks for spreading in records and spreading arguments to commands.

Respect for the dedication man, truly appreciate it

**Comment by ysthakur** [comment]
> make the spread of arguments to externals explicit, e.g.

@amtoine Just to confirm, you want to completely disallow the current automatic spreading for externals, right? No deprecation warning? (or deprecation error, I guess, until Nushell gets warnings)

**Comment by amtoine** [comment]
@ysthakur 
this is a pretty big change, so for now, i think we should have a deprecation warning that does not change the current behaviour whilst also allowing the new one. then we can remove the deprecated behaviour :+1: 

i.e. for now both the following should be allowed and work the same
```nushell
let args = [--allow-empty, --no-gpg-sign]
git commit $args --message "foo"
# gives a deprecation warning but still works
```
and
```nushell
let args = [--allow-empty, --no-gpg-sign]
git commit ...$args --message "foo"
# works without any warning
```

we might want to spend more than one release with the deprecation warning just to let people update their scripts :relieved:

**Comment by ysthakur** [comment]
@amtoine Got it, I'll go add that deprecation warning now
