### ISSUE TITLE
Save after find inserts color escape sequences

### ISSUE THREAD

**Issue by yerlaser** [nushell/nushell#10608]
### Describe the bug

After using `find` command to find some text in cells I get a table where the searched text gets colored with red.
Now when I convert that to, e.g. csv using `to csv` and save to a file escape sequences for coloring get inserted which look like `[90m [0m`.
The problem with that is that it then makes it difficult to do further text operations.

So, would be good if one of the following is available:
1. a command like `to plaintext` that removes escape sequences from table
2. a command like `str plaintext` that removes escape sequences from strings
3. `save --plaintext` that removes colors

### How to reproduce

1. Run the following command:
```
[{one:sometext}] | find some | to csv | save aa.csv
```

2. Open the file with a text editor and observe that additional escape sequences are being added

### Expected behavior

The file should be saved in plain text without coloring either always or via a switch

### Configuration

Default

**Comment by fdncred** [comment]
This is one of the reasons why we have `ansi strip`. So, you'd want to do something like:
```nushell
[{one:sometext}] | find some | ansi strip col1 col3 col5 | to csv | save aa.csv
```
where col1, col3, col5 are columns that have ansi escapes in them

**Comment by yerlaser** [comment]
My bad, didn't know about this command.
