### ISSUE TITLE
Wrong signature parsing in predecl scan

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#10605]
related to
- https://github.com/nushell/nushell/pull/10566

cc/ @kubouch 

### Describe the bug
i have a script that broke when upgrading today.
i did bisect recent commits of Nushell and found the culprit :smirk:

it appears https://github.com/nushell/nushell/pull/10566 changed how order of definitions matter in a script :open_mouth:

when calling a command that is defined later in the script i get a confusing `missing_positional` error.
the only fix i found so far was to move the command definition above the command call and then it starts working as before :ok_hand:

### How to reproduce

1. save the following script as `foo.nu`
```nushell
def main [] {
    foo
}

def foo []: nothing -> nothing { }
```
2. run `nu foo.nu`
```
Error: nu::parser::missing_positional

  × Missing required positional argument.
   ╭─[foo.nu:1:1]
 1 │ def main [] {
 2 │     foo
   ·        ▲
   ·        ╰── missing ]
 3 │ }
   ╰────
  help: Usage: foo <]>
```
3. change the signature of `foo` to `[nothing -> nothing]`
4. run `nu foo.nu`
```
Error: nu::parser::missing_positional

  × Missing required positional argument.
   ╭─[foo.nu:1:1]
 1 │ def main [] {
 2 │     foo
   ·        ▲
   ·        ╰── missing nothing
 3 │ }
   ╰────
  help: Usage: foo <nothing> <nothing>
```

### Expected behavior

i expected one of the two following behaviours
- work as before https://github.com/nushell/nushell/pull/10566 without any error
- give a better error, maybe something like
```
Error: nu::shell::external_command

  × External command failed
   ╭─[foo.nu:1:1]
 1 │ def main [] {
 2 │     foo
   ·     ─┬─
   ·      ╰── executable was not found
 3 │ }
   ╰────
  help: No such file or directory (os error 2)
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.85.1                                   |
| branch             | main                                     |
| commit_hash        | 8c507dc984693c45b0440adf63a94e0410b4bc42 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)      |
| rust_channel       | 1.70.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)      |
| build_time         | 2023-10-04 18:35:49 +02:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | gstat, nu_plugin_explore                 |

**Comment by amtoine** [comment]
that's about what i understood yup, when you have time :relieved:

**Comment by amtoine** [comment]
@kubouch 
i do not think this issue has been fixed by https://github.com/nushell/nushell/pull/10637 :open_mouth: 

with [`tmux-sessionizer.nu`](https://github.com/goatfiles/scripts/blob/main/nu_scripts/scripts/tmux-sessionizer.nu) in my `$env.PATH`, i still get the same error :thinking: 

```nushell
> tmux-sessionizer.nu list-sessions
Error: nu::parser::missing_positional

  × Missing required positional argument.
    ╭─[/home/amtoine/.local/share/nupm/scripts/tmux-sessionizer.nu:20:1]
 20 │
 21 │     if $session.name not-in (list-sessions | get name) {
    ·                                           ▲
    ·                                           ╰── missing nothing
 22 │         log debug $"creating session ($session.name) at ($session.path)"
    ╰────
  help: Usage: list-sessions {flags} <nothing> <table> <nothing> <table>
```

my `nu-goat-scripts` have been installed with `nupm` and the script is in `$env.NUPM_HOME | path join "scripts"` :+1:

**Comment by amtoine** [comment]
and [`nuls`](https://github.com/jokeyrhyme/nuls) gives me two diagnostics
```
Diagnostics:
1. Missing required positional argument.
```
on lines `21` and `58` of `tmux-sessionizer.nu` which are the two only calls to `list-sessions` that are above the definition of the command itself :smirk:

**Comment by kubouch** [comment]
Could you create a minimal example that reproduces the error? The script is quite large and I also don't use tmux on this computer, I can't test it.

**Comment by amtoine** [comment]
> Could you create a minimal example that reproduces the error? The script is quite large and I also don't use tmux on this computer, I can't test it.
>
yes of course, my bad :relieved: 

i brought it down to the following script :smirk: 
```nushell
#!/usr/bin/env nu
def main [] {
    foo
}

def foo []: [nothing -> table, nothing -> table] {
    []
}
```
which gives me
```
Error: nu::parser::missing_positional

  × Missing required positional argument.
   ╭─[/home/amtoine/foo.nu:2:1]
 2 │ def main [] {
 3 │     foo
   ·        ▲
   ·        ╰── missing nothing
 4 │ }
   ╰────
  help: Usage: foo {flags} <nothing> <table> <nothing> <table>
```

**Comment by amtoine** [comment]
looks like it's the multi signature which gives an unhelpful error :open_mouth: 
```nushell
#!/usr/bin/env nu
def main [] {
    foo
}

def foo []: nothing -> table {
    []
}
```
returns an empty list as expected :thinking:

**Comment by amtoine** [comment]
even if i change the signature to something with different types, still the same error
```nushell
#!/usr/bin/env nu
def main [] {
    foo
}

def foo []: [nothing -> table, string -> list] {
    []
}
```

**Comment by amtoine** [comment]
and for each one of these examples, putting `foo` before `main` always solves the issue :+1:

**Comment by kubouch** [comment]
OK, the ordering matters in this case because before parsing `def foo`, `foo` is called whose signature is parsed by the predeclaration scan. If you put `def foo` to the top, it's parsed as a regular declaration which works fine.

The original error was present even before the def --env --wrapped PR btw.

**Comment by amtoine** [comment]
> OK, thanks. The ordering matters in this case because before parsing `def foo`, `foo` is called whose signature is parsed by the predeclaration scan. If you put `def foo` to the top, it's parsed as a regular declaration which works fine.
> 
ooh i see :+1: 

> The original error was present even before the def --env --wrapped PR btw.
>
strange because i use this script each time i open a terminal every day and never had this issue :thinking: 
and Git bisecting Nushell gave me #10566 :open_mouth:
