### ISSUE TITLE
`explore` shouldn't use white text with the light theme

### ISSUE THREAD

**Issue by stfacc** [nushell/nushell#10636]
### Describe the bug

In the screenshot the effect of `sys | explore`  with the default light theme.
White text is not readable.

I'm not sure if this is a problem with `explore` or with the light theme itself.

### How to reproduce

.

### Expected behavior

Use dark fg color with light theme

### Screenshots

![image](https://github.com/nushell/nushell/assets/1027829/c8b23027-e766-46ad-830c-b714c55f6c44)

### Configuration

| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.85.0                                                     |
| branch             |                                                            |
| commit_hash        |                                                            |
| build_os           | linux-x86_64                                               |
| build_target       | x86_64-unknown-linux-gnu                                   |
| rust_version       | rustc 1.72.0 (5680fa18f 2023-08-23) (Fedora 1.72.0-1.fc38) |
| cargo_version      | cargo 1.72.0                                               |
| build_time         | 2023-09-20 00:00:00 +00:00                                 |
| build_rust_channel | release                                                    |
| allocator          | mimalloc                                                   |
| features           | default, sqlite, trash, which, zip                         |
| installed_plugins  |                                                            |

**Comment by fdncred** [comment]
Thanks @stfacc for reporting this. One thing that you might try is to comment out the `explore` configuration section in the config.nu file and see if that improves things.

I know @rgwood has been working on `explore` quite a bit bringing QOL improvements to it and he and I have talked about inheriting the currently active nushell theme. `explore` is supposed to do that now but let us know how your testing goes.

**Comment by stfacc** [comment]
Commenting the `explore` section didn't work by itself, but looking inside the definition of the light_theme I found this and the following lines to be the culprit:

https://github.com/nushell/nushell/blob/d51e82f33b17ffc03550822c66025f25cdc1ca40/crates/nu-utils/src/sample_config/default_config.nu#L93

Changing them to `black` makes the text visible again.

**Comment by fdncred** [comment]
Ya, I think maybe it should be `default` vs `black`.
