### ISSUE TITLE
`let` assignment with type info does not accept pipeline without parentheses.

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#10643]
### Describe the bug

as in title

let's see a reproducible example :wink:

### How to reproduce

1.
```nushell
let foo: record = {foo: "foo"} | merge {bar: 123}
```
and
```nushell
let foo: record<> = {foo: "foo"} | merge {bar: 123}
```
give a similar error
```
Error: nu::parser::expected_keyword

  × Expected keyword.
   ╭─[entry #3:1:1]
 1 │ let foo: record<> = {foo: "foo"} | merge {bar: 123}
   ·                   ────────────────┬────────────────
   ·                                   ╰── expected =
   ╰────
```
2. `let foo: record<foo: string, bar: int> = {foo: "foo"} | merge_records {bar: 123}` does not even run and keeps inserting newlines, just as if you hadn't closed a delimiter

### Expected behavior

i expected any of
```nushell
let foo: record<foo: string, bar: int> = {foo: "foo"} | merge {bar: 123}
let foo: record<> = {foo: "foo"} | merge {bar: 123}
let foo: record = {foo: "foo"} | merge {bar: 123}
```

just as they do with `( ... )`
```nushell
let foo: record<foo: string, bar: int> = ({foo: "foo"} | merge {bar: 123})
let foo: record<> = ({foo: "foo"} | merge {bar: 123})
let foo: record = ({foo: "foo"} | merge {bar: 123})
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.85.1                                   |
| branch             | main                                     |
| commit_hash        | e427c687317edcb92683225c3d161925108599e0 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)      |
| rust_channel       | 1.71.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)      |
| build_time         | 2023-10-08 13:27:01 +02:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | gstat, nu_plugin_explore                 |

**Comment by sholderbach** [comment]
Doesn't seem to have something to do directly with the linked issues. 
I think here [`parse_collection_shape`](https://github.com/nushell/nushell/blob/9f144798d3f8244cbc324236dd4c546f749ec9d4/crates/nu-parser/src/parse_shape_specs.rs#L122) is incompatible with the hackery in parsing the pipeline inside the `SyntaxShape::MathExpression` without parens for the `let` etc. assignments.
