### ISSUE TITLE
output of external is not captured in loop unless collected explicitely

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#10647]
related to
- https://discord.com/channels/601130461678272522/614593951969574961/1160599034948489327
- https://discord.com/channels/601130461678272522/614593951969574961/1159904647352434822
 
### Describe the bug

as in title, external commands appear to require to be either
- collected with `( ... )`
- collected with `collect {}`
- transformed by some Nushell command, e.g. `| $in` or `| str trim`

### How to reproduce

1. run either
```nushell
> seq 1 3 | each {|i| ^echo $i}
```
or
```nushell
> seq 1 3 | each { ^echo $in }
```
and get the same output
```
1
2
3
────────────
 empty list
────────────
```
2. the same happens when trying to list the latest commit revisions of Nushell as a less toy example
```nushell
> seq 1 3 | each {|i| git rev-parse $"HEAD~($i)"}
ff6c0fcb81360d67fb74fe3c1df4b0ab227c39bf
bcf353739550b76d79776010e3aeef764f1b3a01
4efccb2b1c83ff78624a5c8849db30069db637c6
────────────
 empty list
────────────
```

### Expected behavior

i expected to get
1. the list of `i`s and no `stdout`
```nushell
─┬─
0│1
1│2
2│3
─┴─
```
2. the list of the three most recent commits except the `HEAD`
```nushell
─┬────────────────────────────────────────
0│ff6c0fcb81360d67fb74fe3c1df4b0ab227c39bf
1│bcf353739550b76d79776010e3aeef764f1b3a01
2│4efccb2b1c83ff78624a5c8849db30069db637c6
─┴────────────────────────────────────────
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.85.1                                   |
| branch             | main                                     |
| commit_hash        | e427c687317edcb92683225c3d161925108599e0 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)      |
| rust_channel       | 1.71.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)      |
| build_time         | 2023-10-08 13:27:01 +02:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | gstat, nu_plugin_explore                 |

### Additional context

not that doing either one of the following will fix all the external calls
- pipe the external to `$in`
- pipe the external to `collect {}`
- pipe the external to `str trim`
- wrap the external in `( ... )`

> **Note**
> only `str trim` will get the expected output, the other ones will keep the spurious newline inserted by the external calls, e.g.
> ```nushell
> ─┬─
> 0│1
>  │
> 1│2
>  │
> 2│3
>  │
> ─┴─
> ```
> instead of
> ```nushell
> ─┬─
> 0│1
> 1│2
> 2│3
> ─┴─
> ```
> => piping through `str trim` appears to be the best option there because it solves both issues :+1:

**Comment by IanManske** [comment]
Fixed in #11934 :smile:
