### ISSUE TITLE
Inconsistent flags for format commands

### ISSUE THREAD

**Issue by Hofer-Julian** [nushell/nushell#10644]
The format commands have inconsistent flags when it comes to indentation.

- to json has `--indent` https://www.nushell.sh/commands/docs/to_json.html
- to xml has `--pretty` https://www.nushell.sh/commands/docs/to_xml.html

I assume we should have only one of those, since they seem to mean the same thing.
`pretty` makes the intention clear, on the other hand `--pretty 2` is less obvious than `--indent 2`.
Which one do you prefer?

**Comment by amtoine** [comment]
good catch :ok_hand: 

`--indent` feels a bit more straightforward to me, and it's also called like this in other `to ...` commands, such as `to nuon` :yum:

**Comment by Hofer-Julian** [comment]
> `--indent` feels a bit more straightforward to me, and it's also called like this in other `to ...` commands, such as `to nuon` 😋

Agreed.

How does this typically work. Are you deprecating flags before you remove them?

**Comment by amtoine** [comment]
> How does this typically work. Are you deprecating flags before you remove them?
>
that's exactly it :+1: 

we've done quite a few deprecations alreay:
- `str replace --string` option: [deprecation](https://github.com/nushell/nushell/pull/10038) and [removal](https://github.com/nushell/nushell/pull/10064)
- `$nothing` variable: [deprecation](https://github.com/nushell/nushell/pull/10478) and [removal](https://github.com/nushell/nushell/pull/10567)

the idea is to use `report_error_new` with a warning message just as in the two deprecation PRs to avoid breaking, then the feature is removed in the next release :yum:
