### ISSUE TITLE
Completing local binary path removes relative path prefix

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#10649]
### Describe the bug

The new completions are great, but we've got a couple places we'll want to fix up. One I just found is if you build a local binary, say with a C compiler, and get a `a.out` file in the local directory.

If I type: `./a.<tab>` it completes to `a.out` instead of `./a.out`.  The latter is required in posix systems to run the local binary. The former will just give an error.

cc @lavafroth 

### How to reproduce

1. See above

### Expected behavior

Completions of relative paths should keep their relative path markers if the user typed them, so:

```
./a<tab>
```

Would only complete to paths that start with `./`

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.85.1                                   |
| branch             | main                                     |
| commit_hash        | 67b5e1bde9b196ec546e8400e6e057b71dd69309 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)      |
| rust_channel       | 1.70.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)      |
| build_time         | 1980-01-01 00:00:00 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by lavafroth** [comment]
On it.
