### ISSUE TITLE
`overlay` and `use`

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#10665]
### Question

What is the design idea behind having `overlay` as a separate command?

It looks similar to qualified imports, but is separate from `use`.  Is there a reason it was preferable to allowing `use ... as ...`?

**Comment by fdncred** [comment]
`overlay` allows you to overlay a new environment on top of the current one, and when it's done, remove it and restore the original.

https://www.nushell.sh/book/overlays.html#overlays
