### ISSUE TITLE
Consider supporting the DRIPS project to support maintainers of your dependencies

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [nushell/nushell#10664]
### Describe the solution you'd like

Take a look at the DRIPS project from Radworks at https://www.drips.network/ and consider claiming your projects and help support OSS maintainers of dependencies you reply on.

**Comment by andrewdavidmackenzie** [comment]
Completed? 
I don't see a FUNDING.json in the root to claim the project, so maybe should be "Closed as unplanned"?

**Comment by jntrnr** [comment]
Hit the wrong close - correct, we're not planning to use this funding source.
