### ISSUE TITLE
[Feature Request] Interpret `which` as a shell builtin

### ISSUE THREAD

**Issue by avandesa** [nushell/nushell#1067]
**Is your feature request related to a problem? Please describe.**

Unix systems and shells typically include a utility or command called `which`, which, quoting the manpage,

> For each of its arguments it prints to stdout the full path of the executables that would have been executed when this argument had been entered at the shell prompt.

GNU which also includes functionality to search shell aliases and functions.

Bash uses GNU `which`, while zsh ships its own version of `which` as a builtin command that searches builtin commands, aliases, shell functions, and then the path.

**Describe the solution you'd like**

I propose that `nu` defines its own builtin `which` command that has functionality similar to that of zsh's `which` implementation. This would make it easier for users to identify which commands are being modified/intercepted by `nu`. For each argument,

* If the argument is a builtin, identify it as such.
* If the argument is not found in an index of built-in commands, search the path for the argument (this can be delegated to the system-provided implementation of `which`, but a safe Rust implementation may be desirable). If the argument is found, print the full path to its executable.
* If the argument is not a built-in and is not found on the path, print an error message.

The command should allow for a `--all` argument that causes `which` to print all instances of each argument found on the path, as well as the argument's status as a builtin.

The command should also be able to identify escaped commands. For example `which ls` will identify the nu-builtin `ls`, but `which ^ls` should identify as `/usr/bin/ls`.

Should aliases or functions be added to `nu` (I don't think `nu` supports them as of yet?), the alias index should be searched before builtins.

**Describe alternatives you've considered**

Currently, `which` resolves to `/usr/bin/which` in `nu`, so you can reliably use it to identify executables on the system. However, the output of `which ls`, for example, is misleading, as `/usr/bin/ls` is not invoked when using `nu`.

**Comment by avandesa** [comment]
If the maintainers want this as a feature, this is something I'd like to work on once I get through exams next week. I would probably need some guidance on design and implementation, however.

**Comment by jonathandturner** [comment]
I like the idea of extending the internal `which` command to give more information if a command will resolve to an internal and also print an error message if it's not found.

I'm not sure if we want to print Rust-safe implementations (since we would have to curate that). That said, I like your idea of optionally printing all of the possible matches in a table so they know what it's resolving to and what the other ones might be.

+1 to pointing at aliases once we add them, too.

**Comment by jonathandturner** [comment]
If you want to chat about implementation, I'm on the discord regularly. Just stop by and say hi :) 

https://discord.gg/NtAbbGn

**Comment by avandesa** [comment]
Will do, thanks!

To clarify, by safe implementation, I meant a implementation of path searching in Rust, not looking for rust-safe implementations =)

**Comment by jonathandturner** [comment]
Oh, yes, makes sense now 😊

**Comment by quebin31** [comment]
This milestone would be a great start point to add aliases to the shell
