### ISSUE TITLE
How to join json tables while writing them to file

### ISSUE THREAD

**Issue by SebastianMpl** [nushell/nushell#10682]
### Question

I'm having a website that I want to take json data from. There are 3 pages so I use for for $page in 1..3 and then the data is saved to a json file. It works fine except that data from every page is saved to a file as a table [], so 3 pages in the file are saved as [][][] and when I open the file nu says that it cant open the file as json because:
```
Error:   �� Error while parsing JSON text
     ������[281:1]
 281 ���   }
 282 ��� ][
     ��  ���
     ��  ��������� "trailing characters" at line 282 column 2
 283 ���   {
     ���������������
```
What should I do to make nu save the json data from those 3 pages as one table []?

### Additional context and details

The code:
`for $x in 1..3 { http get $"the website($x)" | get something| reject something |  save --append ./a_file.json }
`
Using 
```
for $x in 1..3 { http get $"the website($x)" | get something| reject something | join | save --append ./a_file.json }
says that join is missing right table
```

**Comment by sholderbach** [comment]
`save --append foo.json` will not really reason about the overall structure of JSON in the output but just call `to json` to convert the data to json and then write to the file in an appending fashion. Sounds like we should warn about that.


For your problem the easiest way out (if you can keep the data in memory):

Something along the lines of 

```
1..$num_pages | each { get-data } | flatten | save combined.json
```

might work for you. In the future we will also have a way to allow you to merge the data explicitly with #10489 in a generator like fashion.

**Comment by SebastianMpl** [comment]
@sholderbach 
Thank you for your quick reply. I followed your advice to use each and it works perfectly.
Once again - Huge Thanks !
