### ISSUE TITLE
`cargo check`-parsing tests fail on Windows

### ISSUE THREAD

**Issue by quat1024** [nushell/nushell#10681]
### Describe the bug

The tests `test_known_external::known_external_aliased_subcommand_from_module` and `test_known_external::known_external_subcommand_from_module` work by running `cargo check -h` and searching for the string `cargo check`, typically printed in the usage message.

On windows `cargo check`'s usage message looks like this:

```
Usage: cargo.exe check [OPTIONS]
```

and the entire rest of the usage string just happens to not have any more "`cargo check`"s in it (there's a near-miss at the bottom with "`cargo help check`"). So these tests end up failing.

### How to reproduce

1. `toolkit check pr`

### Expected behavior

it should &nbsp;not do . the that

### Screenshots

<details><summary>Test output</summary>

```
running 531 tests
```
(snip)
```
failures:

---- tests::test_known_external::known_external_aliased_subcommand_from_module stdout ----
stdout: Check a local package and all of its dependencies for errors

Usage: cargo.exe check [OPTIONS]

Options:
  -q, --quiet                   Do not print cargo log messages
  -p, --package [<SPEC>]        Package(s) to check
      --workspace               Check all packages in the workspace
      --exclude <SPEC>          Exclude packages from the check
      --all                     Alias for --workspace (deprecated)
  -j, --jobs <N>                Number of parallel jobs, defaults to # of CPUs
      --keep-going              Do not abort the build as soon as there is an error (unstable)
      --lib                     Check only this package's library
      --bins                    Check all binaries
      --bin [<NAME>]            Check only the specified binary
      --examples                Check all examples
      --example [<NAME>]        Check only the specified example
      --tests                   Check all tests
      --test [<NAME>]           Check only the specified test target
      --benches                 Check all benches
      --bench [<NAME>]          Check only the specified bench target
      --all-targets             Check all targets
  -r, --release                 Check artifacts in release mode, with optimizations
      --profile <PROFILE-NAME>  Check artifacts with the specified profile
  -F, --features <FEATURES>     Space or comma separated list of features to activate
      --all-features            Activate all available features
      --no-default-features     Do not activate the `default` feature
      --target <TRIPLE>         Check for the target triple
      --target-dir <DIRECTORY>  Directory for all generated artifacts
      --manifest-path <PATH>    Path to Cargo.toml
      --ignore-rust-version     Ignore `rust-version` specification in packages
      --message-format <FMT>    Error format
      --unit-graph              Output build graph in JSON (unstable)
      --future-incompat-report  Outputs a future incompatibility report at the end of the build
      --timings[=<FMTS>]        Timing output formats (unstable) (comma separated): html, json
  -h, --help                    Print help
  -v, --verbose...              Use verbose output (-vv very verbose/build.rs output)
      --color <WHEN>            Coloring: auto, always, never
      --frozen                  Require Cargo.lock and cache are up to date
      --locked                  Require Cargo.lock is up to date
      --offline                 Run without accessing the network
      --config <KEY=VALUE>      Override a configuration value
  -Z <FLAG>                     Unstable (nightly-only) flags to Cargo, see 'cargo -Z help' for
                                details

Run `cargo help check` for more detailed information.

stderr:
Expected output to contain: cargo check
thread 'tests::test_known_external::known_external_aliased_subcommand_from_module' panicked at 'assertion failed: stdout.contains(expected)', src\tests.rs:122:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
failures:
    tests::test_known_external::known_external_aliased_subcommand_from_module
    tests::test_known_external::known_external_subcommand_from_module

test result: FAILED. 525 passed; 2 failed; 4 ignored; 0 measured; 0 filtered out; finished in 15.68s
```

</details>

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.85.1                                    |
| branch             | main                                      |
| commit_hash        | 0ba81f1d5125db00ea75f616bd66c172fe2781d2  |
| build_os           | windows-x86_64                            |
| build_target       | x86_64-pc-windows-msvc                    |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)       |
| rust_channel       | 1.71.1-x86_64-pc-windows-msvc             |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)       |
| build_time         | 2023-10-11 00:00:28 -04:00                |
| build_rust_channel | release                                   |
| allocator          | mimalloc                                  |
| features           | default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                           |

### Additional context

(just for fun i went looking around at Cargo's test suite and [they have to handle the exe suffix specially](https://github.com/rust-lang/cargo/blob/master/crates/cargo-test-support/src/compare.rs) 😭)

**Comment by fdncred** [comment]
Maybe we can check `$nu.os-info.name` and if it's "windows" do something different?

**Comment by fdncred** [comment]
i can't get it to fail on windows.

**Comment by AucaCoyan** [comment]
I checkout current `main` branch and ran `toolkit check pr`, all tests passed.
Is it ok to close this issue?

**Comment by fdncred** [comment]
ya, let's close. thanks.
