### ISSUE TITLE
Moving back to previous shell sometimes restores old directory

### ISSUE THREAD

**Issue by joostkremers** [nushell/nushell#10696]
### Describe the bug

Sometimes, when using multiple shells, moving to the previous shell with `p` puts me not in the directory I was in, but rather in the directory that I was in earlier in that shell. (If this sounds unclear, please check out the screen shots below. )

This doesn't happen every time, so I'm not sure what triggers it, but I've noticed it a couple of times now.

### How to reproduce

Unfortunately, I'm not able to reproduce this reliably, but in the screen shot below, I followed the following steps:

1. Have multiple shells open.
2. Do `cd <somedir>` in one shell.
3. Move to the next shell with `g <n>`.
4. Go back to the previous shell with `p`.
5. I'm back in the shell before `cd`.

I don't know if using `g <n>` is necessary to trigger the bug, or if using `n` can also trigger it.

If I find a reliable way to trigger this bug, I'll post it in the thread.

### Expected behavior

I expected Nu to go back to the directory I was in when I left the previous shell.

### Screenshots

NB: I've aliased `s` to `shells`.

![image](https://github.com/nushell/nushell/assets/191630/deb3c232-6fa4-45bc-b33b-1436ca3da79b)

In the final line, I expect to be back in `~/.emacs.d/lisp`, but I'm actually in `~/.emacs.d`.

Here's another example, now moving up a directory in the first shell:

![image](https://github.com/nushell/nushell/assets/191630/e8509d4d-ccdc-464e-8845-8f9b392be939)

### Configuration

```
> version | transpose key value | to md --pretty
| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.85.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | a6f62e05ae5b4e9ba4027fbfffd21025a898783e                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Arch Linux rust 1:1.72.1-1) |
| cargo_version      | cargo 1.72.1                                                     |
| build_time         | 2023-09-22 08:35:37 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |
```

**Comment by fdncred** [comment]
@bobhy iirc you wrote the shells replacement commands in the std-lib. Would you mind investigating this, if you have time?

**Comment by bobhy** [comment]
Yep, `dirs goto` was flat-out broken if you did a `cd` before doing a `goto`.
Thanks for noticing!
