### ISSUE TITLE
History for session not preserved in cases

### ISSUE THREAD

**Issue by ericdching** [nushell/nushell#10695]
### Question

With history setting `sync_on_enter` set to `false`, it appears when I close a tab in iTerm2 or Terminal the history for that session is not preserved. I have to issue the `exit` command. Notably, even an alias of `alias e = exit` won't work. I actually have to use `exit`. I am not running nushell as a login shell, but rather specified in iTerm2 and Terminal configs as the "starting" program. Is there a way to preserve session history when a tab is closed? Maybe there's a config I am missing, or just something fundamental to how history works I don't understand. Any help is appreciated, thanks!

### Additional context and details

Running on macOS 14 with nushell built of recent main (0ba81f1d5) - sorry not on my main machine at the moment.

**Comment by sholderbach** [comment]
Worth checking for related issues. `sync_on_enter` was initially introduced purely for the text based history as the poor mans `history_isolation` (That currently is built with `sqlite` in mind). Should probably not exist as such anymore.

**Comment by ericdching** [comment]
This doesn't reproduce with `sqlite` history. I wasn't really aware it exists. Given I have no rust experience, I'll probably not be able to spend the time to fix any issues with the text based history. Thanks for the info, I'll be switching over to `sqlite` based history :+1:

**Comment by ericdching** [comment]
Closing this issue.
