### ISSUE TITLE
Add new keybindings to `explore`'s command bar

### ISSUE THREAD

**Issue by tm99hjkl** [nushell/nushell#10697]
Hello community.

I would like to make the keyboard operation of the command bar of the explore command more comfortable. Here are the key bindings I would like to add.

* `Ctrl-h`: delete one character
* `Ctrl-w`: delete one word
* `Ctrl-u`: delete to the beginning of the line
* `Ctrl-p/n`: Search history up/down

I have added a prototype to the [fork repository](https://github.com/tm99hjkl/nushell/commit/aa43578e902dcefb0eea36dfe9842fc1a216be5c).
 I would appreciate your confirmation :)

**Comment by fdncred** [comment]
We're trying to move away from modal vim-like stuff in explore. However, as long as both existing and these new keybindings work, I'm not sure there's a problem with trying to do this. @rgwood has been doing a bit of work on explore recently. What are your thoughts Reilly?

**Comment by rgwood** [comment]
Hi, thanks for the suggestion.

Like fdncred mentioned, we are planning to remove the command bar and modes from `explore`. I don't think we should add more functionality to this area for now, but I appreciate the issue and prototype!

**Comment by tm99hjkl** [comment]
Understood. 
Thank you for the prompt confirmation and response :)
