### ISSUE TITLE
str replace parsing error? Unexpected scaped parenthesis

### ISSUE THREAD

**Issue by saona-raimundo** [nushell/nushell#10714]
### Describe the bug

There is an unexpected scaped parenthesis in strings when used in the `str replace` command.
Its behaviour does not match the one from `print`.

### How to reproduce

Consider the command
`"(" | str replace "(" "."`

it returns
```
Error: nu::shell::incorrect_value

  × Incorrect value.
   ╭─[entry #73:1:1]
 1 │ "(" | str replace "(" "."
   ·                   ─┬─
   ·                    ╰── Regex error: Parsing error at position 1: Opening parenthesis without closing parenthesis
   ╰────
```

### Expected behavior

I was expecting to replace `(` by `.`

Note that the command
`print "("`
works fine and returns `(`

I read [the documentation](https://www.nushell.sh/book/working_with_strings.html#string-formats-at-a-glance) and I do not find a description that the character `(` is used as grouping in strings with `"`.

### Configuration

| key                | value                                         |
| ------------------ | --------------------------------------------- |
| version            | 0.83.0                                        |
| branch             |                                               |
| commit_hash        |                                               |
| build_os           | windows-x86_64                                |
| build_target       | x86_64-pc-windows-msvc                        |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)           |
| rust_channel       | stable-x86_64-pc-windows-msvc                 |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)           |
| build_time         | 2023-07-26 11:22:51 +02:00                    |
| build_rust_channel | release                                       |
| allocator          | standard                                      |
| features           | dataframe, default, sqlite, trash, which, zip |
| installed_plugins  |                                               |

### Additional context

Thank you for developing the nu shell!

**Comment by amtoine** [comment]
@saona-raimundo 
the behaviour of `str replace` has changed recently, so i cannot reproduce the bug on 0.85.1 :open_mouth: 

before `str replace` would use *regex* by default, and `(` is an invalid *regex* which explains the error above => you'd have to use `str replace --string`

now, `str replace` uses the same behaviour as `--string` by default and you'd have to raise `--regex` explicitely otherwise :wink: 

please update your version of Nushell and the bug should be gone :relieved:
