### ISSUE TITLE
record tables don't follow configured coloring... sometimes, and `expand deep` may not be working

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#10712]
### Describe the bug

@zhiburt We've seen this problem before but you fixed it. It appears we've regressed somewhere. Would you please look into it when you get a chance?

1. Testing a new PR, I see this. The first thing I notice is that pid and ppid are not applying my int color, which is green in my case.
![image](https://github.com/nushell/nushell/assets/343840/79a3429b-3995-4fd9-91be-80a254684c15)

The same is true when you do it like this:
![image](https://github.com/nushell/nushell/assets/343840/2a2a1ba7-8faf-4583-ba34-e6f271ff3dbd)

2. Expand Deep doesn't seem to be working
![image](https://github.com/nushell/nushell/assets/343840/2f58dcfe-9b4a-4547-ba13-5a2321bf93be)
![image](https://github.com/nushell/nushell/assets/343840/09ef262a-e822-4dc7-b5d8-a0a004933ba7)

3. Now i try to `table --expand` - notice that all column headers are cyan now
![image](https://github.com/nushell/nushell/assets/343840/2cc33592-3619-40a6-92cd-fd157e793bba)

### How to reproduce

see above

### Expected behavior

It would be nice if all data type and column headers got their color information from the `$env.config.color_config` settings.

### Configuration

|key|value|
|-|-|
|version|0.85.1|
|branch|pr/fdncred/10711|
|commit_hash|56cb9e02ecd0fbb1afda70c901ca6497ec8f911d|
|build_os|windows-x86_64|
|build_target|x86_64-pc-windows-msvc|
|rust_version|rustc 1.71.1 (eb26296b5 2023-08-03)|
|rust_channel|1.71.1-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.71.1 (7f1d04c00 2023-07-29)|
|build_time|2023-10-13 15:26:01 -05:00|
|build_rust_channel|debug|
|allocator|mimalloc|
|features|default, sqlite, trash, which, zip|
|installed_plugins|emoji, file, from eml, from ics, from ini, from parquet, from vcf, gstat, highlight, hist, inc, json path, nu_plugin_explore, periodic-table, plot, pnet, query, query json, query web, query xml, regex, str similarity, xyplot|

**Comment by zhiburt** [comment]
Hi there

> points 1 and 3

So seems like `int`, `bool` etc. coloring was not working for `--expand` and `kv` tables for quite a while.
Must be fixed in #10720

> expand-deep

You just need to add `-e` argument to make a use of `--expand-deep`

**Comment by fdncred** [comment]
oh, i'm sorry about `-e --expand-deep` I must of forgotten.

I think it makes sense to assume --expand on those options if they're only applicable to --expand.

Also, thanks for 10720!
