### ISSUE TITLE
Accept empty list as an input to `group-by` (and return empty record)

### ISSUE THREAD

**Issue by Dimagog** [nushell/nushell#10713]
### Describe the bug

`group-by` fails with error if previous steps in a pipeline filter out all input and produce an empty list:
```
~> [] | group-by a
Error:   × expected table from pipeline
   ╭─[entry #14:1:1]
 1 │ [] | group-by a
   ·      ────┬───
   ·          ╰── requires a table input
   ╰────
```
instead it could behave similarly to `select` and return an empty record:
```
~> [] | select a
╭────────────╮
│ empty list │
╰────────────╯
```

### How to reproduce

Minimal repro:
`[] | group-by a`
 a more realistic one:
`[[a b]; [1 2]] | where false | group-by a`

### Expected behavior

return empty record `{}`

### Configuration

| key                | value                                         |
| ------------------ | --------------------------------------------- |
| version            | 0.85.0                                        |
| branch             |                                               |
| commit_hash        |                                               |
| build_os           | macos-aarch64                                 |
| build_target       | aarch64-apple-darwin                          |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)           |
| rust_channel       | stable-aarch64-apple-darwin                   |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)           |
| build_time         | 2023-10-12 22:36:58 -07:00                    |
| build_rust_channel | release                                       |
| allocator          | mimalloc                                      |
| features           | dataframe, default, sqlite, trash, which, zip |
| installed_plugins  |                                               |

**Comment by amtoine** [comment]
yeah, looks like `select` and `group-by` might want to have the same behaviour when the input is empty :+1:

**Comment by amtoine** [comment]
> I'd like to try working on this issue.
>
please go ahead and thanks for considering helping making Nushell better :pray: 
feel free to ask questions :wink:
