### ISSUE TITLE
Raspberry Pi 4 (Kali linux) - failed to compile `nu v0.85.0`

### ISSUE THREAD

**Issue by xbladesub** [nushell/nushell#10717]
`cargo install nu`
...

```
 run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `nu v0.85.0`, intermediate artifacts can be found at `/tmp/cargo-installXUG3DJ`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

Any thoughts?

**Comment by fdncred** [comment]
My guess is there are dependencies that are not installed. I don't use Linux that much so it's only a guess https://www.nushell.sh/book/installation.html#dependencies

**Comment by sholderbach** [comment]
Can you rerun with `RUST_BACKTRACE=1`?

**Comment by sholderbach** [comment]
Our nightly builds for armv7 and aarch64 pass without a problem at the moment: https://github.com/nushell/nushell/actions/runs/6514341801

**Comment by xbladesub** [comment]
> My guess is there are dependencies that are not installed. I don't use Linux that much so it's only a guess https://www.nushell.sh/book/installation.html#dependencies

thanks, this fixed the issue.
