### ISSUE TITLE
[Proposal] Rename `lazy make`

### ISSUE THREAD

**Issue by gaetschwartz** [nushell/nushell#10742]
While exploring an idea I recently had, I realized we might want to consider renaming `lazy make` to something that makes it clearer what it's actually making (a record). I find the current name quite ambiguous; Is it lazy make as in lazy `make` (the build tool `make`) ? Is it `lazy make` as in making whatever is `lazy` ? Then what is `lazy` ?

I would propose to deprecate the command in favor of something like `[a b c] | into record --lazy {|x| $x}` or similar, so that all record-creation methods are at one place. 

As for my aforementioned idea, I was exploring adding a new command to create hashmaps (through lazy records internally). That would allow the three 'types' of records to be created through the same command :

```nu
[a b c] | into record

[a b c] | into record --lazy {|x| computation $x}

[a b c] | into record --hashmap

```

**Comment by fdncred** [comment]
I had always considered `lazy make` akin to `error make`, although I've never personally used `lazy make`. I'm not opposed to renaming it something more intuitive.

**Comment by gaetschwartz** [comment]
To be honest, not a big fan of the `make` keyword as a whole, would rather use something like `new`.  Though I feel like for `error make` it's way less an issue than `error make` which is to me somewhat less ambiguous.

**Comment by amtoine** [comment]
as @fdncred said, i'm not opposed to that as well if it makes things more intuitive, i kinda like something like `into record --lazy` :ok_hand:

a note is that `lazy make` has `--columns` and `--get-value` :wink:

**Comment by fdncred** [comment]
one thing we probably want to stay away from is creating commands with many parameters. i'd rather have separate composable commands. that's the nushell way.

**Comment by gaetschwartz** [comment]
I agree, bloated methods are a bug no-no. What about something like `into lazy record` ?

**Comment by fdncred** [comment]
I could go with `into lazy-record` maybe?

**Comment by amtoine** [comment]
agree with @fdncred, `into` subcommands are types, so more `lazy-record` rather than `lazy record`, we try to avoid multi-word types :wink:

**Comment by fdncred** [comment]
We removed lazy records so this can be closed now. Thanks @NotTheDr01ds for the reminder.
