### ISSUE TITLE
Closures in `shape_` theme colors

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#10740]
### Related problem

I am trying to use a closure to define `shape_bool`, but it doesn't work:

```Nushell
let dark_theme = {
	bool: {|| if $in { "green" } else { "red" } }
	...
	shape_bool: {|| if $in { "green" } else { "red" } }
	...
}
```

Printed bools get highlighted properly, which bools in the command line are always light cyan.

### Describe the solution you'd like

Allow closures for `shape_` highlighters.

### Additional context and details

I am a bit confused by the difference between `type` and `shape_type`.  It seems the prior works in output tables, while the latter operates on command line.  What is the idea behind this split?

**Comment by fdncred** [comment]
I don't fully understand how it works myself. I think that `style_computer.rs` is what is in use here and also `syntax_highlight.rs`.

**Comment by KAAtheWiseGit** [comment]
Would the team be open to a PR, which tinkers with this and allows closures?

**Comment by amtoine** [comment]
> Would the team be open to a PR, which tinkers with this and allows closures?
>
i do not even see any colors in any of the two cases :cry: 

i personally would love to have closure for a better experience on that front :+1:

**Comment by fdncred** [comment]
> Would the team be open to a PR, which tinkers with this and allows closures?

It seems like a reasonable change to me. One thing we have to be careful about is performance. If adding closures to shapes slows down the repl, we probably won't accept it. So, having some benchmarks (if that's possible) with before and after would be great.

**Comment by KAAtheWiseGit** [comment]
I dug into the source, and I had the following thoughts:

Firstly, there is a way to pass the stack to `get_shape_color`.  It is called by `NuHighlighter`, which already holds an `Arc` of `EngineState`, and the function which created it has `Stack` passed to it too.  So the restructuring wouldn't need to be _that_ drastic.

Secondly, I was surprised to find out that most functions simply create a `StyleComputer` on the fly and use it.  This gave me a following idea: could `StyleComputer` include shapes?  I think the main difference between `shape_bool` and `bool` is technical.

It is much harder to implement, however.  `NuHighlighter` uses `FlatShape` from `nu-parser`, which in turn uses `Expr`.  Here a bit of data loss happens, because, for example,  `Expr::Bool` carries the value, while `FlatShape` drops it.  And because `FlatShape` is used for both highlighting and completion, this information cannot be just tucked on.

**Comment by fdncred** [comment]
Good research. Sounds like you're getting closer. I'm not sure familiar with `NuHighlighter` so I don't have much to offer here for alternatives. Maybe others will have helpful ideas?

**Comment by sholderbach** [comment]
See https://github.com/nushell/nushell/pull/10972#issuecomment-2047577999 for why I would prefer to close this and instead encourage to argue for specific added flat shapes. **TLDR:** complexity, risk of bugs, and performance implications seem to disfavor arbitrary configuration compared to parser provided things to style in the syntax highlighting.

**Comment by KAAtheWiseGit** [comment]
My primary rationale for this suggestion was the complexity behind themes.  The first time I saw all of the `shape_` keys I was quite confused.

I think that if merging the two types of highlighting is impractical, the shell highlights should inherit values from shapes.  This would enable simpler configurations, since one'd no longer need to track pairs of `shape_<type>` and `<type>` together, cutting the theme configuration from 54 elements, to 35.

I'll close this issue, and, if there's support for this kind of theme tweaking, will open a separate issue and a draft PR (it would be much simpler than crides' work, only an additional fetch in case `<type>` value is not present in the theme).

**Comment by fdncred** [comment]
@KAAtheWiseGit I've always kind of disliked that we couldn't change the color of certain things easily. I think your idea is probably a good one. At least, it could be a stopgap on the way to making everything configurable without making it so complex that no one can support it.
