### ISSUE TITLE
Allow to specify config dir with env var

### ISSUE THREAD

**Issue by bew** [nushell/nushell#10746]
### Related problem

On Windows (10), I want to put configuration of my tools on OneDrive and point the tools to it.

I've initially found #3883 which allowed to set `NU_CONFIG_DIR` env var to change this, but trying to use it now doesn't seem to work:
![image](https://github.com/nushell/nushell/assets/9730330/55d4ae51-f800-431d-820e-b7a65e211e74)

And since I can't find any mention to that env var in the docs I'm guessing it's not a bug, so I'm making a fresh feature request!

### Describe the solution you'd like

A solution like what was done in #3883 through the environment variable `NU_CONFIG_DIR` which I could set at the account level.

This env var would change the base directory where the config, env and the plugins are searched for.

**Comment by amtoine** [comment]
this looks related to
- https://github.com/nushell/nushell/issues/893
- https://github.com/nushell/nushell/pull/8682
- https://github.com/nushell/nushell/pull/10523
- https://github.com/nushell/nushell/pull/10524

**Comment by bew** [comment]
Setting `XDG_CONFIG_HOME` even on Windows would be ok for me.

**Comment by bew** [comment]
Was implemented in v0.92.0
https://github.com/nushell/nushell/issues/12103
