### ISSUE TITLE
Error: File(s) not found when the name contains square brackets

### ISSUE THREAD

**Issue by munzirtaha** [nushell/nushell#10749]
### Describe the bug

Using back-quoted filenames, I can use the `touch` command to create a file named `[23].txt` but I cannot remove it.

### How to reproduce

```
~> touch `[23].mp4`
~> rm `[23].mp4`
Error:   × File(s) not found
   ╭─[entry #52:1:1]
 1 │ rm `[23].mp4`
   ·    ─────┬────
   ·         ╰── File(s) not found
   ╰────
```

### Expected behavior

external commands should behave consistently with back-quoted strings

### Configuration

> version | transpose key value | to md --pretty                                                                                                             10/18/23 02:13:53 AM
| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.85.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | a6f62e05ae5b4e9ba4027fbfffd21025a898783e                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Arch Linux rust 1:1.72.1-1) |
| cargo_version      | cargo 1.72.1                                                     |
| build_time         | 2023-09-22 08:35:37 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins

**Comment by fdncred** [comment]
You have to escape glob characters. I think `rm '[[]23].mp4'` would probably work.

**Comment by fdncred** [comment]
No issues with the latest version.
![image](https://github.com/nushell/nushell/assets/343840/242f49c9-1fa5-4042-b43e-0431ed5a07ce)

**Comment by munzirtaha** [comment]
There is a new version 9  hours ago and I haven't tried it yet but still I see this as counter-intuitive.

First, according to the [documentation](https://www.nushell.sh/book/working_with_strings.html) backtick-quoted and single-quoted strings don't do anything to the text they're given and escapes are none for them. the square brackets are not even mentioned as escape characters there.

Second, this is counter-intuitive at least for Bourne-shell born human beings.

**Comment by bobhy** [comment]
I have PR #10571 pending which would work the way you want.
But before that PR is merged, @fncred is correct -- you must escape glob metacharacters using *glob* quoting (which is `[x]`, a character class that matches only 1 character).  This is different from bash, where the *shell* expands globs so you use *shell* escapes to quote metachars.  In nushell, it's the individual command that decides whether to treat its argument as a glob pattern, so the single quotes only ensured none of the metacharacters were treated as Nushell tokens and you still need to tell `rm` that you don't want the glob expanded.

**Comment by mb21** [comment]
Thansk @bobhy for your PR, that sounds indeed promising.
I also just ran into this. Where is it documented what globs there are and that you can escape them with `[]`? Didn't see anything here: https://www.nushell.sh/book/moving_around.html#glob-patterns-wildcards

**Comment by bobhy** [comment]
Yep, no glob documentation in the book, perhaps you'd like to take a crack at writing it?

Globbing for command arguments is done by an integrated fork of [crate glob](https://docs.rs/glob/latest/glob/), their documentation is here: https://docs.rs/glob/0.3.1/glob/struct.Pattern.html

FYI, and just to avoid potential confusion, the `glob` command uses a different, and more powerful, crate, [wax](https://docs.rs/crate/wax/latest).

**Comment by fdncred** [comment]
or our crate docs https://docs.rs/nu-glob/latest/nu_glob/struct.Pattern.html

**Comment by amtoine** [comment]
actually, PR is https://github.com/nushell/nushell/pull/10694 and issue is https://github.com/nushell/nushell/issues/10571 :wink:

**Comment by amtoine** [comment]
if https://github.com/nushell/nushell/issues/10694 does not solve this issue, please let me know :relieved:

**Comment by munzirtaha** [comment]
Thanks all for the constructive and quick responses

**Comment by mb21** [comment]
> Yep, no glob documentation in the book, perhaps you'd like to take a crack at writing it?

here you go :) https://github.com/nushell/nushell.github.io/pull/1125

**Comment by mb21** [comment]
@bobhy is it possible that https://github.com/nushell/nushell/pull/10694 omitted to fix the `ls` command? I just tried latest main and while I can `rm '[23].mp4'`, I cannot `ls '[23].mp4'`.

Also, tab-completion still completes to the wrong (unescaped) output (should I open a new issue for that?):

https://github.com/nushell/nushell/assets/157497/dd796720-c9b4-4707-9a39-383f358a9f88

**Comment by bobhy** [comment]
Yes, `ls` uses a slightly different glob than `rm`, `cp`, `mv`, and the
`glob` command itself!  I'm not sure this is best.  After all, traditional
shells have just one.  But I wanted to fix the`rm` scenario in particular,
so I left `ls` as is.
