### ISSUE TITLE
winget package submit for 0.86 failed

### ISSUE THREAD

**Issue by TechWatching** [nushell/nushell#10751]
### Describe the bug

The workflow "Submit Nushell package to Windows Package Manager Community Repository" failed for release 0.86.

Logs 
```
Run vedantmgoyal2009/winget-releaser@v2
Installing dependencies for running komac...
Updating manifests and creating pull request...
Cleaning up previous stale branches of merged pull requests on the fork...
undefined:1
A server error has occurred
^

SyntaxError: Unexpected token 'A', "A server e"... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:6662:19)
    at successSteps (node:internal/deps/undici/undici:6636:27)
    at node:internal/deps/undici/undici:1236:60
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.5.0
```

### How to reproduce

1. Create a release
2. The workflow "Submit Nushell package to Windows Package Manager Community Repository" will be executed

### Expected behavior

The Pull Request in created for the 0.86 release in the [Winget Packages repository](https://github.com/microsoft/winget-pkgs)

### Configuration

Concerns CI, so not applicable.

### Additional context

The pipeline file was recently modified: https://github.com/nushell/nushell/commit/95a4649cc9933045d275d508f33676da16159d18

**Comment by sitiom** [comment]
Package submission did succeed: https://github.com/microsoft/winget-pkgs/pull/122956. The failure is on post-cleanup. Upstream issue: https://github.com/vedantmgoyal2009/winget-releaser/issues/239.

**Comment by jntrnr** [comment]
Current submission is now green: https://github.com/microsoft/winget-pkgs/pull/122956

**Comment by sitiom** [comment]
> https://github.com/vedantmgoyal2009/winget-releaser/issues/239

The upstream issue has now been fixed as well.
