### ISSUE TITLE
Patching will be needed for FreeBSD and OpenBSD

### ISSUE THREAD

**Issue by 0323pin** [nushell/nushell#10750]
### Describe the bug

Just an heads-up!
Building the new release on FreeBSD or, OpenBSD will fail.

If anyone points this out, I've already commited a fix to the [`trash`](https://github.com/Byron/trash-rs/pull/87) crate.

See also issue https://github.com/Byron/trash-rs/issues/86

### How to reproduce

Build `nu` on FreeBSD or, OpenBSD.

### Expected behavior

NA

### Screenshots

NA

### Configuration

NA

### Additional context

NA

**Comment by sholderbach** [comment]
Thanks for the report!

Folks running `cargo install nu` without `--locked` should already benefit from your patch. 

Let's leave it open for the package maintainers, to weigh in or discover the workaround.

We had an independent issue with the Windows packaging pipeline so we may or may not ship a minimal point release.

**Comment by 0323pin** [comment]
**Disclaimer:** I use only NetBSD-current (dev-branch) and Void Linux (musl libc) but, I've realized that the issue will impact mainly FreeBSD.

OpenBSD build is already broken for other reasons, namely `uucore` not defining `target_os = openbsd` anywhere. But, that's a different problem with a different solution.

Just letting you know. The fix seems easy and straightforward but, it needs someone with a test environment to confirm. It shouldn't be too different from the fix I've pushed to `uucore` a month ago to add support for NetBSD.

**Comment by bbarker** [comment]
`uucore` seems to be long deprecated - I just ran into a likely related issue for building on illumos (SunOS). Is it worth opening a separate issue for this?

**Comment by 0323pin** [comment]
> uucore seems to be long deprecated ...

How is this? 0.0.22 was released 15 days ago.

> just ran into a likely related issue for building on illumos

Yes, Illumos is not defined either.

**Comment by 0323pin** [comment]
> Is it worth opening a separate issue for this?

Apply a patch adding the relevant definitions. If, it builds submit a pull-requst with `uucore`

**Comment by 0323pin** [comment]
Closing this now, as this is no longer an issue.
