### ISSUE TITLE
Directory completion doesn't work when triggering inside a command

### ISSUE THREAD

**Issue by csmoe** [nushell/nushell#10766]
### Describe the bug

Dir completion overrides the command contents after the cursor.

### How to reproduce

1. type a command with file path
2. try to change the prefix of the path with directory completion

### Expected behavior

nu's directory completion should behave as bash, preserve `src/lib.rs`

### Screenshots

https://github.com/nushell/nushell/assets/35686186/323824e0-26a3-4f83-b889-bf5afdc75497

https://github.com/nushell/nushell/assets/35686186/e0be818f-eda2-4ead-9baa-770c90979d57

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.84.0                                      |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | linux-x86_64                                |
| build_target       | x86_64-unknown-linux-gnu                    |
| rust_version       | rustc 1.74.0-nightly (8142a319e 2023-09-13) |
| rust_channel       | nightly-x86_64-unknown-linux-gnu            |
| cargo_version      | cargo 1.74.0-nightly (2fc85d15a 2023-09-09) |
| build_time         | 2023-09-19 11:35:09 +08:00                  |
| build_rust_channel | release                                     |
| allocator          | standard                                    |
| features           | default, sqlite, trash, which, zip          |
| installed_plugins  |                                             |

**Comment by fdncred** [comment]
Does this work the same on the latest release 0.86.0?

**Comment by dedebenui** [comment]
yes, trying to use autocomplete on an intermediate directory erases the rest of the path, like the video above

**Comment by fdncred** [comment]
@lavafroth When you have a free moment, would you mind looking into this?

**Comment by lavafroth** [comment]
This appears to be related to how the spans are handled. I'm actually going to be a little busy this week but I'll try my best to fix this.

**Comment by fdncred** [comment]
> This appears to be related to how the spans are handled. I'm actually going to be a little busy this week but I'll try my best to fix this.

Thank you for helping out so much. You work has made a huge difference in our completions.
