### ISSUE TITLE
Rename `unfold` to something more user-friendly

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#10760]
### Describe the bug

We're currently using a technical functional programming term in one of the newer commands: `unfold`.

We've traditionally tried to stay away from functional programming technical terms like `fold` and `map` in order to make something that's more user-friendly. `fold` is `reduce` and `map` is `each`.

We should find a new name for `unfold` that is more user-friendly.

### How to reproduce

1. see above

### Expected behavior

Perhaps `unfold` could be called `expand` or some synonym of that. We can always put `unfold` in one of the search terms for it for those folks with a functional programming background. We just don't want to assume people have that background.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.85.1                                   |
| branch             | main                                     |
| commit_hash        | ce09186e2ebc271e2147e0a504170434e00f0199 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)      |
| rust_channel       | 1.71.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)      |
| build_time         | 1980-01-01 00:00:00 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by hudclark** [comment]
Agree that `unfold` isn't a particularly user-friendly name. I imagine that virtually all users will find it through its search terms `generate` and `stream`.

Before deciding to implement `unfold`, I was searching for things like "stream", "generate", "lazy", "yield", etc, but couldn't find anything.

Other nushell users have used similar terms ("generate") when [discussing](https://stackoverflow.com/questions/72063354/while-until-loops-in-nushell/72063355#72063355) how to stream api responses in the past:
> Side-note: Personal opinion -- I envision that Nushell will eventually add a yield keyword to allow generator expressions. This will simply the above example further by allowing it inside a reduce that can accumulate the results.

Given folks, myself included, describe `unfold` as a function to generate streams, I think that it would make sense to rename the command `generate` or `generate stream`. It can then just use `unfold` as a search term.

**Comment by jntrnr** [comment]
The name `generate` seems more approachable to me :+1:

**Comment by jntrnr** [comment]
Some useful precedence here: a few languages have the concept of a "generator", which is a function that yields (generates) a stream of values and stops on some condition. This feels close to that concept, and using a name that helps folks unfamiliar with it get the right idea and also give people familiar with generators a good guess what it does seems like a good balance.

**Comment by amtoine** [comment]
for Python folks, i think `yield` would make a lot of sense :+1: 

i might have proposed `generate` and `stream` as well in the PR, so i'm fine with whatever feels more intuitive :relieved:
