### ISSUE TITLE
`str index-of` crashes on non-ascii range

### ISSUE THREAD

**Issue by UliTroyo** [nushell/nushell#10774]
### Describe the bug

Using the `--range` flag on `str index-of` crashes when passing non-ascii graphemes and ranges that fall within the bytes of those graphemes. For example, if I have the grapheme "💛", which is 4 bytes, and I try any of:
```nushell
"💛" | str index-of '' --range 0..1
```
```nushell
"💛" | str index-of '' --range 0..2
```
```nushell
"💛" | str index-of '' --range 0..3
```
it will crash, but the following won't:
```nushell
"💛" | str index-of '' --range 0..4
```
```nushell
"💛" | str index-of ''
```

### How to reproduce

Given that:
```nushell
"正" | size | select bytes
```
```nushell
╭───────┬───╮
│ bytes │ 3 │
╰───────┴───╯
```
and that:
```nushell
"💛" | size | select bytes
```
```nushell
╭───────┬───╮
│ bytes │ 4 │
╰───────┴───╯
```
This will result if you run the following:
| command | result |
| - | - |
| `"💛" \| str index-of '' -r 0..4` | no crash |
| `"正" \| str index-of '' -r 0..3` | no crash |
| `"💛" \| str index-of '' -r 0..3` | $${\color {red} CRASH}$$ |
| `"正" \| str index-of '' -r 0..2` | $${\color {red} CRASH}$$ |
| `"💛💛" \| str index-of '' -r 0..($in \| size \| get bytes)` | no crash |
| `"💛💛" \| str index-of '' -r 0..(($in \| size \| get bytes) - 1)` | $${\color {red} CRASH}$$ |
| `"💛" \| str index-of '' -r 0..3 --grapheme-clusters` | $${\color {red} CRASH}$$ |
| `"💛" \| str index-of '' -r 0..3 --utf-8-bytes` | $${\color {red} CRASH}$$ |
| `"💛" \| str index-of '' -r 0..3 --end` | $${\color {red} CRASH}$$ |

### Expected behavior

A return of `-1`, rather than a crash, I think. Unless it should be an error.

### Configuration

| key                | value                                                              |
| ------------------ | ------------------------------------------------------------------ |
| version            | 0.86.0                                                             |
| branch             |                                                                    |
| commit_hash        |                                                                    |
| build_os           | macos-x86_64                                                       |
| build_target       | x86_64-apple-darwin                                                |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                                |
| rust_channel       | stable-x86_64-apple-darwin                                         |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                                |
| build_time         | 2023-10-17 18:30:20 -04:00                                         |
| build_rust_channel | release                                                            |
| allocator          | mimalloc                                                           |
| features           | dataframe, default, extra, sqlite, trash, which, zip               |
| installed_plugins  | dns query, highlight, inc, query, query json, query web, query xml |

**Comment by amtoine** [comment]
good catch :open_mouth:
