### ISSUE TITLE
Run command on file changes

### ISSUE THREAD

**Issue by mrdgo** [nushell/nushell#10782]
### Related problem

This is purely a quality of life request, feel free to close.

Currently, if I want to run a command based on file changes, I use [entr](https://github.com/eradman/entr):
```nu
glob *.{tex,bib} | str join "\n" | entr tectonic paper-1.tex
```

### Describe the solution you'd like

This feels a bit cumbersome and I would love a `nu`-native approach to this problem. Maybe something like
```nu
glob *.{tex,bib} | if change { tectonic paper-1.tex }
```

**Comment by sholderbach** [comment]
We have the [`watch`](https://www.nushell.sh/commands/docs/watch.html) command to watch for file system changes

**Comment by mrdgo** [comment]
Thanks, I will take a closer look at it. So far, I could only watch a single file. But will dig into this

**Comment by amtoine** [comment]
@mrdgo 
in an empty directory, e.g. `/tmp/foo`, i was able to run
```nushell
> watch . --glob=* {|_, path| print $path }
Now watching files at "/tmp/foo". Press ctrl+c to abort.
```
to show all changes to any file in `/tmp/foo`.

then, when i touch a bunch of files in there, i see the output in the first instance of Nushell:
```
/tmp/foo/foo
/tmp/foo/foo
/tmp/foo/bar
/tmp/foo/bar
/tmp/foo/baz
```

> **Note**
> i'm using latest `0.86.1`

**Comment by mrdgo** [comment]
Alright. I can now watch _all_ files and I can watch files with _one_ particular file extension.
```nu
watch . {|_, path| foo }
```
or
```nu
watch --glob=*.tex . {|_,path| tectonic main.tex }
```
But how do I watch multiple extensions? Neither
```nu
watch --glob=*.{tex,bib} . {...}
```
nor
```nu
watch --glob=*.tex --glob=*.bib . {...}
```
do what I expect.
