### ISSUE TITLE
Can't `match` a `null` (but can using the deprecated `$nothing`)

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#10799]
### Describe the bug

`match` won't match a variable with `null`, but will match using `$nothing` (deprecated) as the pattern.

Ran into this in a real-world use-case that's a bit complex.  Took me the better part of a day (on and off) to figure out the root cause and get it into some minimal reproducible examples.  At the most basic:

### How to reproduce

```Nushell
match $a {
    null => true,
    _ => false
}
```

Outputs `false`

### Expected behavior

Outputs `true`

### Additional context

Note that this MRE works if matching against `$nothing`, but this workaround will fail as of 0.87 when that is removed:

```Nushell
match $a {
    $nothing => true,
    _ => false
}
```

Returns `true`

Of course, the above is far oversimplified and would be better as an `if` statement (which *does* work):

```Nushell
if $a == null { true } else { false }
```

My real world use-case is that I have a calc involving two values.  Consider it something like `distancePerHour`.  My `$hours` variable may be:

* `null`
* `0`
* Or a number (float or int)

If `$hours` is 0 or null, then I want the `distancePerHour` result to be `null` as well, since the source values are coming from a Nu table where I'll be `insert`ing the `distancePerHour` results.

Consider:

```Nushell
def distancePerHour [ distance: any hours: any ] {
    match $hours {
        0 => null,
        null => null,
        _ => ( $distance / $hours )
    }
}
```

* `distancePerHour 60 1` -> Works, returns 60
* `distancePerHour 60 0` -> Works, returns `null`
* `distancePerHour 60 null` -> Fails with `type mismatch for operator` since the `null` didn't match and it fell through to the catch-all

(Side-note: As a workaround, yes, I *could* massage the data in advance, but that's not as "clean")

Keep in mind that the following *works* as expected (for now):

```Nushell
def distancePerHour [ distance: any hours: any ] {
    match $hours {
        0 => null,
        $nothing => null,
        _ => ( $distance / $hours )
    }
}
```

Another workaround (but, IMHO, clunky) would be to `default` the `null` to some "magic" value:

```Nushell
def distancePerHour [ distance: any hours: any ] {
    let hours = ($hours | default "nada")
    match $hours {
        0 => null,
        "nada" => null,
        _ => ( $distance / $hours )
    }
}
```

Of course, for *this* MRE, I could also `default` to 0, but that only works if the desired match result is the same for both 0 and `null`.

### Configuration

| key                | value                                                                     |
| ------------------ | ------------------------------------------------------------------------- |
| version            | 0.86.0                                                                    |
| branch             |                                                                           |
| commit_hash        | 5d8763ed1d14048ac9fc09eb21be36e6e622f0d7                                  |
| build_os           | linux-x86_64                                                              |
| build_target       | x86_64-unknown-linux-gnu                                                  |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)                                       |
| rust_channel       | 1.71.1-x86_64-unknown-linux-gnu                                           |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)                                       |
| build_time         | 2023-10-17 17:14:05 +00:00                                                |
| build_rust_channel | release                                                                   |
| allocator          | mimalloc                                                                  |
| features           | dataframe, default, extra, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  |                                                                           |

**Comment by amtoine** [comment]
not sure it's in our issue tracker already but i'm quite sure i've seen that somewhere, good catch :pray:
