### ISSUE TITLE
Move `ansi link` from extra to `nu-command`

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#10792]
### Related problem

It's very common to Add a link to a given string in CLI, especially for long URLs, I'd recommend to move the `ansi link` command to default feature.
Although we have full releases now, `winget`,`scoop`,`brew` will install the default version

### Describe the solution you'd like

Use full release instead, however, not that convenient

**Comment by fdncred** [comment]
I wouldn't object to moving it back.
