### ISSUE TITLE
`scope` commands appear as `filter`s in `help`

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#10802]
### Describe the bug

Nitpick and minor, but while I'm writing up a few issues and thinking about it, I noticed that all of the `scope` commands are categorized as `filter`s in `help commands`.

### How to reproduce

```Nushell
help commands | where name =~ "scope" | select category
```

Returns:

|category|
|-|
|core|
|filters|
|filters|
|filters|
|filters|
|filters|
|filters|

### Expected behavior

Shouldn't all of these (including the root `scope`) be categorized as `debug`?

They definitely feel wrongly categorized as filters since not one of them takes any input on the pipeline.

### Configuration

| key                | value                                                                     |
| ------------------ | ------------------------------------------------------------------------- |
| version            | 0.86.0                                                                    |
| branch             |                                                                           |
| commit_hash        | 5d8763ed1d14048ac9fc09eb21be36e6e622f0d7                                  |
| build_os           | linux-x86_64                                                              |
| build_target       | x86_64-unknown-linux-gnu                                                  |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)                                       |
| rust_channel       | 1.71.1-x86_64-unknown-linux-gnu                                           |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)                                       |
| build_time         | 2023-10-17 17:14:05 +00:00                                                |
| build_rust_channel | release                                                                   |
| allocator          | mimalloc                                                                  |
| features           | dataframe, default, extra, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  |                                                                           |

**Comment by fdncred** [comment]
I'm not sure `debug` is the right category but I don't think `filter` is either. Maybe just `core`?

**Comment by amtoine** [comment]
maybe just core :+1:
