### ISSUE TITLE
`null | describe` still reports `nothing`

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#10800]
### Describe the bug

`describe` command still reports the type of `null` as `nothing`, even though, in my understanding, #9918 unified both to be `null`.

### How to reproduce

```Nushell
null | describe
```

Results: `nothing`

### Expected behavior

`null`

### Configuration

| key                | value                                                                     |
| ------------------ | ------------------------------------------------------------------------- |
| version            | 0.86.0                                                                    |
| branch             |                                                                           |
| commit_hash        | 5d8763ed1d14048ac9fc09eb21be36e6e622f0d7                                  |
| build_os           | linux-x86_64                                                              |
| build_target       | x86_64-unknown-linux-gnu                                                  |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)                                       |
| rust_channel       | 1.71.1-x86_64-unknown-linux-gnu                                           |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)                                       |
| build_time         | 2023-10-17 17:14:05 +00:00                                                |
| build_rust_channel | release                                                                   |
| allocator          | mimalloc                                                                  |
| features           | dataframe, default, extra, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  |                                                                           |

**Comment by amtoine** [comment]
actually #9918 has been closed without merging :wink: 

the `$nothing` variable has been removed in #10567, leaving `null` only as the value, but `nothing` is still the type, so it's expected there :yum:

**Comment by NotTheDr01ds** [comment]
@amtoine Oops!  Missed that - Thanks!
