### ISSUE TITLE
[FR] Multi-line comments

### ISSUE THREAD

**Issue by ImportTaste** [nushell/nushell#10817]
### Discussed in https://github.com/nushell/nushell/discussions/5734

> <sup>Originally posted by **ImportTaste**</ins> &nbsp; _June 7, 2022_</sup>
> I know you can comment with `#`, but is there a way to do a multi-line comment? Like this in PowerShell:
> ```powershell
> <#
> This
> is
> commented
> out
> #>
> Write-Host foobar
> ```

> <sup>Originally posted by **fdncred** &nbsp; _June 7, 2022_</sup>
> No. Nushell doesn't support multi line comments like that yet.

- - -

Please consider implementing this, it would make my life easier.

`<#` and `#>` (like the above example) would work best, in my opinion.

**Comment by WindSoilder** [comment]
Thanks for your issue, but it's duplicates of #10096, so I'll close it
