### ISSUE TITLE
history.max_size: 0 crashes nushell

### ISSUE THREAD

**Issue by Subtixx** [nushell/nushell#10826]
### Describe the bug

As I use atuin for shell history and use a git repository to keep my dotfiles in sync I wanted to configure that nushell doesn't update the history.txt. So I set max_size to 0, this results in nushell crashing after a single command is entered.

```
thread 'main' panicked at '`at` out of bounds', /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\alloc\src\collections\vec_deque\mod.rs:1873:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at '`at` out of bounds', /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\alloc\src\collections\vec_deque\mod.rs:1873:9
stack backtrace:
   0:     0x7ff7a961c941 - <unknown>
   1:     0x7ff7a898ac8b - <unknown>
   2:     0x7ff7a9616289 - <unknown>
   3:     0x7ff7a961c6eb - <unknown>
   4:     0x7ff7a961fd6f - <unknown>
   5:     0x7ff7a961f9f2 - <unknown>
   6:     0x7ff7a9620320 - <unknown>
   7:     0x7ff7a9620083 - <unknown>
   8:     0x7ff7a961ddd9 - <unknown>
   9:     0x7ff7a961fde4 - <unknown>
  10:     0x7ff7a9812795 - <unknown>
  11:     0x7ff7a954ca4c - <unknown>
  12:     0x7ff7a954ce2f - <unknown>
  13:     0x7ff7a8a9c62b - <unknown>
  14:     0x7ff7a89fa1ca - <unknown>
  15:     0x7ff7a8a9b0aa - <unknown>
  16:     0x7ff7a8aa8830 - <unknown>
  17:     0x7ff7a97fb950 - <unknown>
  18:     0x7ff7a97fb286 - <unknown>
  19:     0x7ff7a97f8588 - <unknown>
  20:     0x7ff7a97faced - <unknown>
  21:     0x7ff7a97f8a01 - <unknown>
  22:     0x7ffa39cf451f - _chkstk
  23:     0x7ffa39c6fd44 - RtlUnwindEx
  24:     0x7ff7a97f8892 - <unknown>
  25:     0x7ff7a97fa389 - <unknown>
  26:     0x7ff7a97fa6d2 - <unknown>
  27:     0x7ff7a97fade9 - <unknown>
  28:     0x7ff7a97f8a01 - <unknown>
  29:     0x7ffa39cf449f - _chkstk
  30:     0x7ffa39c6e456 - RtlFindCharInUnicodeString
  31:     0x7ffa39ca4465 - RtlRaiseException
  32:     0x7ffa37124ffc - RaiseException
  33:     0x7ff7a97f95ef - <unknown>
  34:     0x7ff7a950038e - <unknown>
  35:     0x7ff7a9620539 - <unknown>
  36:     0x7ff7a962035a - <unknown>
  37:     0x7ff7a9620083 - <unknown>
  38:     0x7ff7a961ddd9 - <unknown>
  39:     0x7ff7a961fde4 - <unknown>
  40:     0x7ff7a9812795 - <unknown>
  41:     0x7ff7a954ca4c - <unknown>
  42:     0x7ff7a8aa0457 - <unknown>
  43:     0x7ff7a8a5dc2e - <unknown>
  44:     0x7ff7a8a534da - <unknown>
  45:     0x7ff7a8a5e32e - <unknown>
  46:     0x7ff7a8a59e8f - <unknown>
  47:     0x7ff7a960ec58 - <unknown>
  48:     0x7ff7a8a5525c - <unknown>
  49:     0x7ff7a97f78cc - <unknown>
  50:     0x7ffa3923257d - BaseThreadInitThunk
  51:     0x7ffa39caaa78 - RtlUserThreadStart

[process exited with code 3221226505 (0xc0000409)]
```

### How to reproduce

1. Set max_size of history to 0
2. Open nushell
3. Enter command
4. Crash

### Expected behavior

Either an error that a history of 0 is not valid or just not crashing.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.86.0                                   |
| branch             |                                          |
| commit_hash        | 5d8763ed1d14048ac9fc09eb21be36e6e622f0d7 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)      |
| rust_channel       | 1.71.1-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)      |
| build_time         | 2023-10-18 07:39:55 -05:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
lol, you're right, it shouldn't crash. now i don't have to ask myself, "who would ever set their history size to 0", because now i know. 😆

**Comment by sholderbach** [comment]
Should be resolved by https://github.com/nushell/reedline/pull/701

**Comment by weirdan** [comment]
All linked PRs have been merged. Nushell 0.97.1 doesn't crash with history.max_size=0
