### ISSUE TITLE
a feature like auto title in zsh

### ISSUE THREAD

**Issue by flyinke** [nushell/nushell#10833]
### Related problem

The title of the terminal does not change in the current version.

### Describe the solution you'd like

would like to add a function like auto title in zsh to display the current directory name in the title when entering a different directory, or to display the current server name in the title when connecting to other servers with ssh.

**Comment by fdncred** [comment]
Mine shows the current directory when you cd in the title. You probably have to turn on `shell_integration` in the config.nu.
![image](https://github.com/nushell/nushell/assets/343840/4fbb4cc8-6f7c-4146-97da-ca001e346eba)

**Comment by drbrain** [comment]
This is possible with `PROMPT_COMMAND` with [the necessary escape codes](https://github.com/drbrain/nushell-config/blob/e073f292da5c842c8d5cfa519ed2bdbc50a519ad/starship.nu#L31) (works on iTerm)

**Comment by fdncred** [comment]
It already works in nushell. You just have to have `shell_integration: true` in your config. Nushell uses OSC7 for this.

**Comment by TheLostLambda** [comment]
I can confirm that this works with `shell_integration: true`, but it only seems to work after running a command / hitting enter — I think this feature should also run on shell startup when enabled! (That's what other shells like `fish` do!)

I'm happy to make a PR, but I might need a pointer or two as to where to find things!

I'm also interested in what terminals this causes issues with, and why this isn't enabled by default!
