### ISSUE TITLE
book website is down

### ISSUE THREAD

**Issue by Andrew-Webb** [nushell/nushell#1083]
https://book.nushell.sh/ is not responding

**Comment by sebastian-xyz** [comment]
The book moved to [nushell.sh/book](https://www.nushell.sh/book/).

https://book.nushell.sh/ does currently not redirect to the new page. 
  http://book.nushell.sh/ should work too :)

**Comment by Andrew-Webb** [comment]
Thanks; I created https://github.com/nushell/book/pull/54
