### ISSUE TITLE
Add --recursive flag to print

### ISSUE THREAD

**Issue by bfren** [nushell/nushell#10842]
### Related problem

When nu outputs a complex object it recurses through values, so e.g. nested lists and records are printed in full.

When we use `| print` though it prints (for example) `list<int>` instead of the actual values.

### Describe the solution you'd like

I would like `print` to have an option to show everything, rather than simply the first level of data.

### Describe alternatives you've considered

`debug`
`inspect`

### Additional context and details

Apologies if there is a way of doing this, I've been searching through the docs and can't find anything that does this.

**Comment by fdncred** [comment]
I thought this is what `table --expand` does. I thought you could put `| table -e` on most things to expand them.

**Comment by amtoine** [comment]
as @fdncred said, i thin you can use
```nushell
print ($something | table --expand)
```
to show the full data or
```nushell
print ($something | table --expand --expand-deep 2)
```
to show only a few depth level :yum: 

i'll close this issue because Nushell already offers a way to do that, feel free to reopen if you wanted more :relieved:
