### ISSUE TITLE
cd should optionally not resolve symlinks

### ISSUE THREAD

**Issue by himanss** [nushell/nushell#10849]
### Related problem

I use symlinks in my file organization, the `cd` command always resolves symlinks (similar to  bash's`cd -P` option). this behavior should be user configurable.

### Describe the solution you'd like

there should be an boolean possibly named `$env.config.cd.follow_symlinks` or `$env.config.cwd_follow_symlinks`. 
- when `false`, it should enter and travel symlinks (similar to bash's `cd -L`)
- when `true` it should do the current behavior (similar to bash's `cd -P`)

`cd` should have a `-P` option and `-L` option

### Describe alternatives you've considered

entering symlinks is the default behavior of bash and sh

**Comment by amtoine** [comment]
sounds related to https://github.com/nushell/nushell/issues/2175, right @himanss?

**Comment by himanss** [comment]
thanks!
