### ISSUE TITLE
add uutils/coreutils `mktemp` command into nushell

### ISSUE THREAD

**Issue by tskinn** [nushell/nushell#10845]
### Related problem

`mktemp` on macos and linux behave differently. It would be awesome to have a single cross platform implementation in nu. 

### Describe the solution you'd like

Create new nushell command `mktemp` using uutils/coreutils.

**Comment by fdncred** [comment]
Sounds good to me.

**Comment by tskinn** [comment]
Are there any barriers to implementing this? Would this be considered a breaking change? Does it matter at this point or should we make a command with a different name like `temp dir`  / `temp file` or something like that.

**Comment by fdncred** [comment]
I'd prefer to use the uu_mktemp crate. I'm not sure what parameters it has or if the coreutils team has exposed the proper functionality so we can use it. You may just have to give it a try.

**Comment by tskinn** [comment]
Linking to https://github.com/uutils/coreutils/issues/5465
