### ISSUE TITLE
Helix editing mode

### ISSUE THREAD

**Issue by mydumpfire** [nushell/nushell#10868]
### Related problem

We already have edit modes for vi(m), it would be nice if we can have one for [helix](https://github.com/helix-editor/helix) too.

### Describe the solution you'd like

An editing mode that emulates the Helix editor

**Comment by amtoine** [comment]
i think this is a Reedline thing and a duplicate of https://github.com/nushell/reedline/issues/639 :wink: 

closing in favor of https://github.com/nushell/reedline/issues/639

**Comment by luccahuguet** [comment]
I was in doubt whether to create the issue here or in reedline, looks like I did the right call, nice
