### ISSUE TITLE
Configuration or environment access for plugins

### ISSUE THREAD

**Issue by drbrain** [nushell/nushell#10867]
### Related problem

I am writing a plugin to query prometheus metrics. I have several prometheus servers that require mutual TLS auth and I want to supply a shorthand name to describe all the connection parameters so my command could look like this:

```nushell
'prometheus_metric{label="value"}' | prometheus query --source prom1
```

Instead of this:

```nushell
'prometheus_metric{label="value"}' | prometheus query --url https://observability.example/prometheus/prom1/ --cert ~/path/to/cert --key ~/path/to/key --cacert ~/path/to/cacert
```

The configuration to map the short "prom1" name to the URL, key, and certificates could be:

```nushell
let prometheus_sources = [
  prom1
] | each {|name|
    {
      name: $name
      url: $"https://observability.example/prometheus/($name)/"
      cert: ~/path/to/cert
      key: ~/path/to/key
      cacert: ~/path/to/cacert
    }
  }
```

The problem is there is not a way to let my plugin know what the configuration is, nor a portable way to let my plugin load configuration from the filesystem because [nu_plugin::EvaluatedCall](https://docs.rs/nu-plugin/latest/nu_plugin/struct.EvaluatedCall.html) does not forward the environment or the configuration.

### Describe the solution you'd like

My favorite solution is to have `$env.config` contain a `plugin` section that allows registered plugins to place arbitrary data inside. When the shell is executing a plugin it would forward the plugin's configuration data through `nu_plugin::EvaluatedCall` to the plugin.

So a nushell configuration that had `nu_plugin_prometheus` and another plugin with configuration could look like:

```nushell
# …

$env.config = {
  # …
  plugins: {
    prometheus: {
      sources: $prometheus_sources
      # …
    }
    other_plugin: {
    }
  }
}
```

When calling a command registered by the `nu_plugin_prometheus` plugin only the record inside `$env.config.plugins.prometheus` would be forwarded.

The plugin protocol can be updated to validate changes to its configuration

## Plugin-controlled configuration file

This option does not require changes to nushell (and will be my solution while we discuss this PR).

It requires that the plugin determine where the configuration file should live for the current platform.

It requires that the plugin handle deserialization of the configuration file which would involve additional error handling.

If a plugin wanted to support multiple configurations it would need to support an argument for multiple configuration files. With the plugin configuration solution this could be accomplished with different `config.nu` files.

## Shell config-controlled configuration file

Nushell could compute the path to a configuration file and send its path to the plugin as an argument to `EvaluatedCall`

The plugin would then have to load and deserialize it which would involve additional error handling in the plugin.

## Environment passing

`EvaluatedCall` could pass the nushell environment to the plugin when called.

This would contain the full configuration.

I don't like this solution as the environment may by very large or contain data where it would be safer for the user if the plugin couldn't see it (it violates the principle of least access)

### Additional context and details

This feature allows security-sensitive arguments to be hidden on the command line or want to condense many configuration options into a single short name.  An existing (but seemingly outdated) plugin that could use this feature is [nu_plugin_s3](https://crates.io/crates/nu_plugin_s3)

**Comment by amtoine** [comment]
i think it would be great to have that :+1: 

i would make [the config of my `nu_plugin_explore`](https://github.com/amtoine/nu_plugin_explore?tab=readme-ov-file#configuration) simpler as well :innocent:

**Comment by fdncred** [comment]
Currently, nushell plugins cannot reach then engine_state or stack. Those would have to be exposed to the plugins. We'd love to have someone contribute that functionality to plugins. However, I'm not sure adding arbitrary keys to plugins would work. 

One thing that could work is using the `$db` [functionality](https://github.com/nushell/nushell/pull/10691) that I've PR'd as an experiment. Then, on startup, you could populate that in-memory database with anything you want and use it throughout the session. You could probably do a similar thing with a datasource.nuon file.

**Comment by drbrain** [comment]
> Currently, nushell plugins cannot reach then engine_state or stack. Those would have to be exposed to the plugins.

Can you say more about this? I think my main proposal doesn't require this, but some alternates would.

I think it's a good thing that nushell plugins cannot access the engine state and I think this should be a design restriction of plugins. If a user has an AWS access key in their configuration for use with an S3 plugin they probably don't want any other plugin to have access to it. I see the engine state has both the environment variables and the configuration so providing all that information with every plugin invocation could be bad for a user's security. It may also be a lot of data.

My main proposal is that `PluginDeclaration::run()` extracts a plugin's configuration from the engine state and forwards only that as an `Option<Value>` in the `EvaluatedCall` that is serialized and sent to the plugin. This seems to run up against this concern you had:

> However, I'm not sure adding arbitrary keys to plugins would work.

By "arbitrary keys" do you mean an entry like `$env.config.plugins.nu_plugin_prometheus`, or adding an `Option<Value>` to `EvaluatedCall` or something else?

> One thing that could work is using the $db functionality that I've PR'd as an experiment. Then, on startup, you could populate that in-memory database with anything you want and use it throughout the session. You could probably do a similar thing with a datasource.nuon file.

I worry about a malicious plugin (or plugin update) gaining access to credentials that are stored in `$db`, `$env`, etc. that is not restricted when forwarded to the plugin.

**Comment by fdncred** [comment]
To get to the config, you need to have engine_state.

**Comment by drbrain** [comment]
> To get to the config, you need to have engine_state.

Yes, and we have it [here on the nushell side](https://github.com/nushell/nushell/blob/3dfe1a4f0eb3d82c8862667ff6063e6b7fc6f10c/crates/nu-plugin/src/plugin/declaration.rs#L60) of a plugin call which [creates the `CallInfo`](https://github.com/nushell/nushell/blob/3dfe1a4f0eb3d82c8862667ff6063e6b7fc6f10c/crates/nu-plugin/src/plugin/declaration.rs#L116-L120) so I think we could extract a subset of the configuration before [sending the `CallInfo` to the plugin](https://github.com/nushell/nushell/blob/3dfe1a4f0eb3d82c8862667ff6063e6b7fc6f10c/crates/nu-plugin/src/plugin/declaration.rs#L133)

Or am I missing something?

**Comment by fdncred** [comment]
Here's where we have to be careful, plugins are separate executables and the communication between nushell and plugins is via stdout serialization (json or msgpack). So, if we're serializing the entire engine_state back and forth, it may be noticeably slow. If we just pass some config values one way at one time, like maybe you're suggesting, it may be fine.

I don't confess to know everything about plugins but I know what I've mentioned is one limitation. I don't know everything that engine_state is needed for nor what everthing stack is needed for but when we talk about it, that's the synopsis, plugins don't have access to them because of serialization.

**Comment by drbrain** [comment]
> Here's where we have to be careful, plugins are separate executables and the communication between nushell and plugins is via stdout serialization (json or msgpack). So, if we're serializing the entire engine_state back and forth, it may be noticeably slow.

I believe we agree on this part.

> If we just pass some config values one way at one time, like maybe you're suggesting, it may be fine.

OK

> I don't confess to know everything about plugins but I know what I've mentioned is one limitation.

I know even less, so I brought this up here first to see if there were any traps that might get in the way

> I don't know everything that engine_state is needed for nor what everthing stack is needed for but when we talk about it, that's the synopsis, plugins don't have access to them because of serialization.

I think the serialization boundary is a good boundary and want to preserve it. Not only to keep plugin invocation as fast as possible through minimum serialization, but also as a security boundary.

It sounds like this is sufficient acceptance for me to create a PR where I implement a minimum solution for further approval.

**Comment by fdncred** [comment]
Definitely, please create a PR to try and make things better. We don't have to have make everything perfect in one PR. We're always good with "baby steps" making things better little by little.

**Comment by drbrain** [comment]
Let's continue discussion in #10955
