### ISSUE TITLE
nu does not properly display emoji(?)

### ISSUE THREAD

**Issue by steveklabnik** [nushell/nushell#1086]
**Describe the bug**

Strange characters happen at my prompt.

**To Reproduce**

Run `nu`. I've tested in both Alacritty and in Powershell's native terminal emulator.

**Expected behavior**

I think this is supposed to be emoji?

**Screenshots**

Alacritty:

![image](https://user-images.githubusercontent.com/27786/70946107-33e46280-201c-11ea-9cc5-57d53fdb0ff9.png)

Powershell:

![image](https://user-images.githubusercontent.com/27786/70946131-43fc4200-201c-11ea-80ff-566217d884c7.png)

**Configuration (please complete the following information):**
 - OS: Windows
 - Version `fa9329c8e3032d71912ac51e35634a548d13537f`
 - Optional features `stable`

**Comment by jonathandturner** [comment]
@steveklabnik we should document that - for Windows you'll probably want to use the new Windows Terminal https://github.com/microsoft/terminal/releases

**Comment by steveklabnik** [comment]
Ah okay; I am trying to keep it maximally Rust, so I haven't tried it yet. I've heard good things though!

**Comment by jonathandturner** [comment]
@steveklabnik if you want to keep what you have, you can configure starship.rs to be a bit less emoji-y

**Comment by thegedge** [comment]
I think the task here would be to simply document the recommendation.

If we wanted to get fancy, perhaps we _could_ detect the terminal's support for emoji and adjust the starship prompt accoridingly?
