### ISSUE TITLE
More Detail in Error Messages

### ISSUE THREAD

**Issue by stellarpower** [nushell/nushell#10863]
### Related problem

I have just had the following error returned to me:
```nushell
~> open $emplacementCSVFilePath | from csv                            10/28/23 19:07:35 PM
Error: nu::shell::type_mismatch

  × Type mismatch.
   ╭─[entry #36:1:1]
 1 │ open $emplacementCSVFilePath | from csv
   · ──┬─
   ·   ╰── string
   ╰────

~>  $emplacementCSVFilePath | describe                              1 10/28/23 19:07:39 PM
string
~>     
```

I have come across further examples - but will need to save them somewhere and add to the bug over time, as I don;t have them to hand right now.

### Describe the solution you'd like

The highlighting is great - visually very nice. But, in general, I'd like a bit more detail about what was found, and what was expected. "Type mismatch" and an underline is a start, but isn't really giving me what the problem is, or what I need to fix it. "This function needs this, but got this - this argument has this type" would be a typical sort of message to get back from a modern compiler.

In addition, this is [almost a verbatim example from the docs](
https://github.com/nushell/nushell.github.io/blob/10bde89fa8b91775d6538baa8b1e09bc196fffcd/commands/docs/from_csv.md?plain=1#L61
), so it's a bit confusing why it produces an error when it's as close as I can get to following the example. I assume `from csv` wants just one blob of text and `open` produced a `list<string>` - but the way it's highlighted implies that the problem is with the arguments to `open`.

As an aside, the Crystal compiler has some quite nice error reporting, if it helps to look at what another language kind of on some similar lines to nu has done. 

### Additional context and details

Version 0.85.0

**Comment by sholderbach** [comment]
Yeah, that is related to https://github.com/nushell/nushell/issues/10698

**Comment by stellarpower** [comment]
Sorry, GitHub search gets worse and worse over time. And so many occasions I can't exactly type "error" and expect to find what I am looking for 😂

Feel free to close.

**Comment by amtoine** [comment]
i wish we could link issues together so that linking one of them to a PR and then landing the PR would close both issues, but that's not possible afaik :cry:

**Comment by weirdan** [comment]
The error is a bit better now:

```console
$ open ~/Downloads/090620220820003456.csv | from csv
Error: nu::shell::only_supports_this_input_type

  × Input type not supported.
   ╭─[entry #208:1:1]
 1 │ open ~/Downloads/090620220820003456.csv | from csv
   · ──┬─                                      ────┬───
   ·   │                                           ╰── only string input data is supported
   ·   ╰── input type: list
   ╰────
```

**Comment by sholderbach** [comment]
Nice!
