### ISSUE TITLE
`out>` inconsestencies

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#10864]
### Describe the bug

Putting `out>` as a parameter in several places causes weird behavior.

### How to reproduce

1. `~> out>` is a no-op.
2. `help out>` prints the default help message.
3. When out is given as the last argument to a command, it is ignored:
    
    `git add out>` gives a `nothing specified` error, not a shell-level error. 

### Expected behavior

I'd expect errors in all cases.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.86.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2023-10-22 21:58:37 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

### Additional context

Same is true for `err>` and `out+err>`.

**Comment by sholderbach** [comment]
I think on the most recent main @WindSoilder's https://github.com/nushell/nushell/pull/10835 should fix them

**Comment by KAAtheWiseGit** [comment]
This is a dupe of #10830.

Additionally, I built the HEAD, and I can confirm that this issue is fixed there.

Closing.
