### ISSUE TITLE
Installing via homebrew installs rust as a dependency

### ISSUE THREAD

**Issue by TimDeve** [nushell/nushell#1088]
**Describe the bug**
Installing nushell via homebrew installs rust as a dependency.

**To Reproduce**
1. run `brew install nushell`

**Expected behavior**
I would expect only the binary to be installed as rust seems only needed to build.

**Configuration:**
 - OS: macOS
 - Version: Mojave 10.14.6

Having a quick look at the [fd recipe](https://github.com/Homebrew/homebrew-core/blob/926642831d7b4f8deaa9ccf23729fc9683c60167/Formula/fd.rb#L16) in homebrew, which is also rust project, the recipe needs to be updated to only require rust to build rather than all the time.
Having rust installed via brew is kinda annoying as the canonical way to handle rust installs is to use rustup.

**Comment by jonathandturner** [comment]
The homebrew package is maintained by some of the homebrew contributors rather than by us. You might have better luck on the homebrew repo.

**Comment by TimDeve** [comment]
Thanks, I'll close this issue.
