### ISSUE TITLE
+<number> arguments removes the + symbol

### ISSUE THREAD

**Issue by noverby** [nushell/nushell#10887]
### Describe the bug

When evaluating arguments passed to commands, the + symbol is removed.

### How to reproduce

```sh
echo +1 # outputs 1
```

### Expected behavior

```sh
echo +1 # outputs +1
```

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.85.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.72.0 (5680fa18f 2023-08-23) (built from a source tarball) |
| cargo_version      | cargo 1.72.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

### Additional context

Reading +<number> arguments is needed to create wrappers around vi editors.
E.g.
```sh
vi-wrapper-in-nushell +101 file # opens file on line 101
```

**Comment by WindSoilder** [comment]
It's because nushell have type, `+11` will be interpreted as `11`, if you want to pass `+11`, you can quote it.

```
echo "+11"
```

**Comment by noverby** [comment]
@WindSoilder I understand that, but it makes it impossible to write a vi wrapper like this, since the + is discarded:

```nushell
# vi-wrapper
def main [...args] {
    vi $args
}
```

**Comment by fdncred** [comment]
Will this work?
```nushell
def main [...args] {
  vi $'"($args)"'
}
```
Then all args should be double quoted. Not sure how that'll work though because $args is a list so you might need to do `($args | str join ' ')`. Either way, it's something to test/play around with.

**Comment by noverby** [comment]
@fdncred Unfortunately that does not work.
E.g.
```nushell
# vi
def main [...args] {
  echo $'"($args)"'
}

vi +10 file # returns "[10,file]"
```

**Comment by fdncred** [comment]
right, like i said above it returns a list so you may have to do `($args | str join ' ')`

**Comment by fdncred** [comment]
darn, that doesn't seem to work either. nushell is type-checking the +10 as a 10, which is right. You're trying to pass it as a string so you'll need to do `'+10'`.

```nushell
def t --wrapped [...args] {
  echo ($args | each {|r| $'"($r)"'} | str join ' ')
}
```
```
❯ t '+10' file
"+10" "file"

❯ t +10 file 
"10" "file"

**Comment by noverby** [comment]
@fdncred It just seems inconsistent:
```nushell
# Works
vi +10 file

# Doesn't work
def vi-wrapped [...args] { vi ($args) }
vi-wrapped +10 file
```

Why was it chosen to parse +<number> as numbers and not as strings?

Is there any specific use case for parsing +<number> as a number (compared with to having similar behavior of other shells)?

**Comment by fdncred** [comment]
> Is there any specific use case for parsing + as a number ...

math is the first thing that comes to mind

**Comment by amtoine** [comment]
maybe it's been said already but my input on this is that
```nushell
def nvim-wrapper [...args] { nvim $args }
```
will work but you just have to quote the options, e.g.
```nushell
nvim-wrapper "-u" NONE
```

**Comment by noverby** [comment]
@amtoine You can actually make that work with:
```nushell
def nvim-wrapper [-u] {
  let $args = if $u { "-u" } else { "" }
  nvim $args 
}
nvim-wrapper -u # Works as expected
```
The problem is, that there is no way to get something similar to work with a `+<number>` argument.

**Comment by noverby** [comment]
@amtoine Also, nvim-wrapper cannot be used as a replacment drop-in for nvim then, since it does not handle arguments in the same way as nvim.

**Comment by noverby** [comment]
A further example of what this prevents.

This script, that converts vi arguments to vscode arguments, cannot be ported to nushell:
```sh
#!/usr/bin/env sh
cmd=codium
files=()
args=()
line=0

for arg in "$@"; do
  case $arg in
  -*)
    args+=("$arg")
    ;;
  +*)
    line=("${arg:1}")
    ;;
  *)
    files+=("$arg")
    ;;
  esac
done

nfile=${#files[@]}
for file in "${files[@]}"; do
  if [[ "$file" = /* ]]; then
    file=$file
  else
    file="$PWD/$file"
  fi
  if [ $nfile -gt 1 ]; then
    $cmd -r $args "$file" &
  else
    if [ -d $file ];
    then
      $cmd -n $args "$file"
    else
      $cmd -rg $args "$file:$line"
    fi
  fi
done
```

My trial at porting it:
```nushell
#!/usr/bin/env nu
def main [...vargs,--wait,--diff] {
  mut args = $vargs
  mut files = []
  mut line = 0
  if $wait {
    $args = ($args | append "--wait")
  }
  if $diff {
    $args = ($args | append "--diff")
  }
  for arg in $args {
    # Hack to workaround that '+' is not properly forwarded
    if ($arg | describe) == "int" {
      $line = $arg
    } else {
      let file = if $arg =~ /.* {
        $arg
      } else {
        $"(pwd)/($arg)"
      }
      $files = ($files | append $file)
    }
  }

  let nfile = ($files | length)
  for file in $files {
    match [nfiles, ($file | path type)] {
      [1, "file"] => (codium --reuse-window --goto $args $"($file):($line)")
      [_, "file"] => (codium --reuse-window $args $file)
      [_, "dir"] => (codium --new-window $args $file)
    }
  }
```

**Comment by noverby** [comment]
@fdncred Oh yeah thank you, I never got to test the script, because of the `+<number>` behavior  :)

**Comment by fdncred** [comment]
does it work if you wrap the +number in quotes like `'+10'`?

**Comment by noverby** [comment]
@fdncred Yes, but that ruins the point.
The scripts and applications that run the script, are not going to add the quotes.

**Comment by noverby** [comment]
I solved the problem by adding the string type to the function definition:
```nushell
def main [...args: string] {
...
```
Then `+<number>` is parsed as a string with the `+` symbol.

**Comment by amtoine** [comment]
@noverby
this is very interesting :open_mouth: 
by default `..args` will be of type `any` and thus `+<number>` is a number!

we should have this in our documentation :thinking: 

would you mind adding a little section about all your findings to our book? :innocent:

**Comment by fdncred** [comment]
Oh, interesting. Nice fix. Agree, we should document this somewhere.

**Comment by noverby** [comment]
@amtoine @fdncred Sure, I will take a look at documenting it in the weekend. :)
