### ISSUE TITLE
Storing datetime in Nuon

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#10889]
### Related problem

It is currently impossible to store datetime in Nuon.  The `to nuon` command incorrectly serializes the format:

```Nushell
~> let datetime = 2023-10-10T16:00:00
~> {val: $datetime} | to nuon
{val: 2023-10-10T16:00:00+00:00}
~> {val: $datetime} | to nuon | from nuon 
Error:   × error when parsing nuon text
   ╭─[entry #11:1:1]
 1 │ {val: $datetime} | to nuon | from nuon 
   ·                              ────┬────
   ·                                  ╰── could not parse nuon text
   ╰────

Error:   × error when parsing
```

### Describe the solution you'd like

Allow datetimes in Nuon.  I presume this would either special-casing it or ignoring colons without spaces after them.

### Describe alternatives you've considered

Datetimes could be stored in string, but this requires separate handling for each script using the data.  This is also not a type-oriented approach.

### Additional context and details

I just realized this, but datetimes cannot be written manually in records either.  So `{val: 2023-10-10T16:00:00}` doesn't work.

**Comment by sholderbach** [comment]
Well spotted! 

`from nuon` just reuses our literal expression parsing. So the problem around the record `:` and the datetime `:` is universal.

**Comment by KAAtheWiseGit** [comment]
While browsing through the old issues I found a related one: #8257.  It contains a solution for records: using parentheses (`{val: (2023-10-10T16:00:00)}`).

**Comment by fdncred** [comment]
8601 can be stored without colons https://en.wikipedia.org/wiki/ISO_8601#Times, maybe we should support that in the parser.

**Comment by sholderbach** [comment]
Thanks for the link @KAAtheWiseGit !

Closing in favor of #8257
