### ISSUE TITLE
"can't convert cell-path to cell path" is Confusing Error Message

### ISSUE THREAD

**Issue by stellarpower** [nushell/nushell#10895]
### Describe the bug

Fun error message, migrated from #10698

```nu
~> $joined | reject ['uuid', $OriginalHeader] | rename $ReplacementHeader 'uuid'                                                                    10/29/23 00:40:14 AM
Error: nu::shell::cant_convert

  × Can't convert to cell path.
   ╭─[entry #86:1:1]
 1 │ $joined | reject ['uuid', $OriginalHeader] | rename $ReplacementHeader 'uuid'
   ·                   ───┬──
   ·                      ╰── can't convert cell-path to cell path
   ╰────

~>   
```

The problem in my code was that reject is variadic, and doesn't take a list. But this definitely produces a message that's a tad confusing!!

### How to reproduce

Will need to spend some time to see if I can work up an MRE. Would appreciate any guidance.

### Expected behavior

I guess "can't convert list<string> to cell-path" would make sense.

### Configuration

| key                | value                                                                     |
| ------------------ | ------------------------------------------------------------------------- |
| version            | 0.86.0                                                                    |
| branch             |                                                                           |
| commit_hash        | 5d8763ed1d14048ac9fc09eb21be36e6e622f0d7                                  |
| build_os           | linux-x86_64                                                              |
| build_target       | x86_64-unknown-linux-gnu                                                  |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)                                       |
| rust_channel       | 1.71.1-x86_64-unknown-linux-gnu                                           |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)                                       |
| build_time         | 2023-10-17 17:14:05 +00:00                                                |
| build_rust_channel | release                                                                   |
| allocator          | mimalloc                                                                  |
| features           | dataframe, default, extra, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  | py-quickstart                                                             |

**Comment by fdncred** [comment]
I believe that in order to use a list to reject columns, it needs to be a variable.
```nushell
let cols = [name size]
ls | reject $cols
```
otherwise, you just do `ls | reject name size`

**Comment by stellarpower** [comment]
Yep, in the end I just provided them as variadic arguments.

**Comment by stellarpower** [comment]
Awesome, thank you! Will try out on the next release. If this error message happens to come up in another context somehow, will re-open; otherwise will assume it's gone.
