### ISSUE TITLE
Use `span` in `error make`

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#10914]
### Related problem

Currently `error make` takes in a record, which has `start` and `end` fields.  I think this is somewhat unergonomic, as in majority of times some existing span is passed to it.  This would get rid of currently necessary patter of creating a temporary `span` variable.  And if a custom span has to be made (a rarer case, IMO), it can still be created manually, just with one more level of nesting.

### Describe the solution you'd like

Replace `label: {text: "...", start: ..., end: ...}` with `label: {text: "...", span: ...}`.

### Example

Currently (an example from `error make` docs):

```Nushell
    def foo [x] {
        let span = (metadata $x).span;
        error make {
            msg: "this is fishy"
            label: {
                text: "fish right here"
                start: $span.start
                end: $span.end
            }
        }
    }
```

With the proposed change:

```Nushell
    def foo [x] {
        error make {
            msg: "this is fishy"
            label: {
                text: "fish right here"
                span: (metadata $x).span
            }
        }
    }
```

**Comment by fdncred** [comment]
I wonder if we can use both? like if we detect a "span:" key, look for a span and if we see a "start:" and "end:" use the individual ones. I say that we probably want to keep start/end because sometimes you have to tweak the span's start or end. That probably doesn't happen that often but it may happen.

**Comment by KAAtheWiseGit** [comment]
@fdncred in theory, there are two ways to ways to tweak the ends with this proposal:

```Nushell
mut span = (metadata $x).span
span.end += 10
...
```

```Nushell
error make {
    label: {
        span: {
            start: 10
            end: 20
        }
    }
}
```

I didn't think about the idea to mix them, though, and I like it.  One thing which I worry about is the error message when the two get mixed.  If someone puts both `span` and `start/end`, what should the error say?

**Comment by fdncred** [comment]
It should be an error if someone puts both span and start/end stating that it's disallowed and to choose either span or start/end. One other benefit to doing it this way is that it keeps us from having a breaking-change.

**Comment by amtoine** [comment]
i think this would be quite cool to have :pray:

**Comment by fdncred** [comment]
Related/Unrelated, I was reminded again today that `error make` doesn't allow the addition of the `help:` line. It would be nice to have an optional `help:` key in the creation of `error make`.

Example
```nushell
❯ ls | into list -adfa
Error: nu::parser::unknown_flag

  × The `into list` command doesn't have flag `-a`.
   ╭─[entry #44:1:1]
 1 │ ls | into list -adfa
   ·                 ┬
   ·                 ╰── unknown flag
   ╰────
  help: Available flags: --help(-h). Use `--help` for more information.
```

In fact, I'd love to be able to optionally support every functionality that nushell supports with miette-style errors.

**Comment by KAAtheWiseGit** [comment]
@amtoine I checked it out and it turns out the help option was added to `GenericError` since then.  I think this means we could kill two birds with one stone here.

**Comment by amtoine** [comment]
@KAAtheWiseGit 
oh yeah, if we can kill these two birds at once, i'd be super happy to have a more powerful and easier to use `error make` :innocent:
