### ISSUE TITLE
Getting variable type

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#10924]
### Question

Is there a way to check variable type without `describe`?  `describe` returns a string.  This poses problem for composite types.  A record, for example, has to be checked with `| describe | str starts-with`.  And it gets more complicated with nested types.

**Comment by fdncred** [comment]
There's a new `describe --detailed` functionality. There's also `debug --raw`. Not sure either are what you're looking for though.

**Comment by KAAtheWiseGit** [comment]
@fdncred the new functionality was exactly what I had in mind, thanks!
