### ISSUE TITLE
`from json` doesn't work with `first` or `last`

### ISSUE THREAD

**Issue by nanoqsh** [nushell/nushell#10934]
### Describe the bug

For example, look at the file with json objects in each individual line:
```nu
> open jsons.txt
{"foo":"bar"}
{"num":12}
{"obj":{"type":"string"}}
```

This commands
```
open jsons.txt | lines | first | from json
open jsons.txt | lines | last | from json
```
will throw the following error:
```
Error: nu::parser::input_type_mismatch

  × Command does not support list<any> input.
   ╭─[entry #85:1:1]
 1 │ open jsons.txt | lines | first | from json
   ·                                  ────┬────
   ·                                      ╰── command doesn't support list<any> input
   ╰────
```

Although, this works great:
```nu
> open jsons.txt | lines | get 0 | from json
┏━━━━━┳━━━━━┓
┃ foo ┃ bar ┃
┗━━━━━┻━━━━━┛
> open jsons.txt | lines | reverse | get 0 | from json
┏━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃     ┃ ┏━━━━━━┳━━━━━━━━┓ ┃
┃ obj ┃ ┃ type ┃ string ┃ ┃
┃     ┃ ┗━━━━━━┻━━━━━━━━┛ ┃
┗━━━━━┻━━━━━━━━━━━━━━━━━━━┛
```

### How to reproduce

```nu
>
 :: '{"foo":"bar"}
 :: {"num":12}
 :: {"obj":{"type":"string"}}' | lines | last | from json
```

### Expected behavior

Should work the same as
```nu
.. | lines | get 0 | from json
```

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.86.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26) |
| build_time         | 2023-11-03 15:27:04 +06:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
I'm a little confused here. This is not valid json and therefore is not supposed to work.
```
{"foo":"bar"}
{"num":12}
{"obj":{"type":"string"}}
```
That is valid json per row, so that means you need to use `from json --objects` or the `from ndjson` or `from jsonl` in the std-lib.

**Comment by nanoqsh** [comment]
@fdncred 
I think the problem here is not with the file format, but with how `first`/`last` works with lists:
```nu
> ['{"foo":"bar"}', '{"num":12}', '{"obj":{"type":"string"}}'] | last
{"obj":{"type":"string"}}
> ['{"foo":"bar"}', '{"num":12}', '{"obj":{"type":"string"}}'] | last | from json
Error: nu::parser::input_type_mismatch

  × Command does not support list<any> input.
   ╭─[entry #2:1:1]
 1 │ ['{"foo":"bar"}', '{"num":12}', '{"obj":{"type":"string"}}'] | last | from json
   ·                                                                       ────┬────
   ·                                                                           ╰── command doesn't support list<any> input
   ╰────
```
In any case, `last` from a list of strings should be a string

**Comment by KAAtheWiseGit** [comment]
@fdncred its a weird issue:

```Nushell
~> ["{}", "{}"] | last | describe
string
~> ["{}", "{}"] | last | from json
Error: nu::parser::input_type_mismatch

  × Command does not support list<any> input.
   ╭─[entry #22:1:1]
 1 │ ["{}", "{}"] | last | from json
   ·                       ────┬────
   ·                           ╰── command doesn't support list<any> input
   ╰────
```

**Comment by hholst80** [comment]
The type should give a hit to whats going on: `from json` sees a List<any> but `first` should clearly return the same type as `get 0` which is not a list.  A minor thing perhaps, it should also not be Any since I suppose that `lines` returns a List<string>?

**Comment by weirdan** [comment]
This works now:

```console
$ let jsont = r#'{"foo":"bar"}
{"num":12}
{"obj":{"type":"string"}}'#

$ $jsont | lines | first | from json
╭─────┬─────╮
│ foo │ bar │
╰─────┴─────╯

$ $jsont | lines | last | from json
╭─────┬───────────────────╮
│     │ ╭──────┬────────╮ │
│ obj │ │ type │ string │ │
│     │ ╰──────┴────────╯ │
╰─────┴───────────────────╯
```
