### ISSUE TITLE
Nushell on NixOS: Unexpected spacing in terminal

### ISSUE THREAD

**Issue by W-Y-R** [nushell/nushell#10948]
### Question

I've recently switched from using Fish shell to Nushell, but I'm experiencing a strange issue. When I open a terminal window and enter a single character, the character automatically moves to the end of the terminal, leaving a large blank space in between. I'm guessing this isn't intentional behavior?

### Additional context and details

![20231104_18h07m54s_grim](https://github.com/nushell/nushell/assets/108990755/7526c8dd-1ad8-41ab-a4bb-ce41f7bdbae1)

I'm using the standard configuration file provided by the Nixos Wiki, specifically (https://nixos.wiki/wiki/Nushell). However, I'm uncertain about the origin of this behavior.

**Comment by amtoine** [comment]
i think this is a known (and annoying) bug that's caused by the interaction between the terminal and Reedline :cry:

**Comment by W-Y-R** [comment]
That's a shame. Oh well, I guess I'll close the issue.
