### ISSUE TITLE
`error make` uses `$.help` only when `$.label` is not set

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#10947]
Thanks for explaining @amtoine. It seems to work sometimes.
```nushell
error make {msg:foo help: `Custom help line`}
Error:   × foo
   ╭─[entry #14:1:1]
 1 │ error make {msg:foo help: `Custom help line`}
   · ─────┬────
   ·      ╰── originates from here
   ╰────
  help: Custom help line
```
Ah, @KAAtheWiseGit I think the example is wrong. `help` is inside the label.
![image](https://github.com/nushell/nushell/assets/343840/d239111f-a960-42c2-b4ff-dacf79ef2942)

_Originally posted by @fdncred in https://github.com/nushell/nushell/issues/10923#issuecomment-1793439863_

## steps to reproduce
- with a `$.label` => there is no help
```nushell
> error make {msg: "msg", label: {text: "text"}, help: "help"}
Error:   × msg
   ╭─[entry #6:1:1]
 1 │ error make {msg: "msg", label: {text: "text"}, help: "help"}
   · ─────┬────
   ·      ╰── text
   ╰────
```
- without `$.label` => `help: help` appears
```nushell
> error make {msg: "msg", help: "help"}
Error:   × msg
   ╭─[entry #7:1:1]
 1 │ error make {msg: "msg", help: "help"}
   · ─────┬────
   ·      ╰── originates from here
   ╰────
  help: help
```

**Comment by fdncred** [comment]
Well, it's not quite as described. This has a label and help and it works.
![image](https://github.com/nushell/nushell/assets/343840/5f5c05bd-6360-4ba4-b502-3225c16540fe)

**Comment by amtoine** [comment]
so when there is a `$.label` with text and span it works maybe?

**Comment by KAAtheWiseGit** [comment]
I must've mixed up the early returns somewhere, will send a PR soon.

**Comment by amtoine** [comment]
> I must've mixed up the early returns somewhere, will send a PR soon.
>
thanks for looking into this :pray:
