### ISSUE TITLE
run-external --redirect-stderr is confusing / there's no way to operate on stderr?

### ISSUE THREAD

**Issue by gandalf3** [nushell/nushell#10944]
### Describe the bug

[the documentation here](https://www.nushell.sh/commands/docs/run-external.html) says
> `--redirect-stderr, -`: redirect stderr to the pipeline

which lead me to believe this would work
```nu
>  run-external --redirect-stderr "python" "-c" "import sys; print('hello on stderr', file=sys.stderr)" | inspect
Error: nu::shell::pipeline_mismatch

  × Pipeline empty.
   ╭─[entry #1:1:1]
 1 │  run-external --redirect-stderr "python" "-c" "import sys; print('hello on stderr', file=sys.stderr)" | inspect
   ·                                                                                                         ───┬───
   ·                                                                                                            ╰── no input value was piped in
   ╰────
   ```

[if im understanding right](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/system/run_external.rs#L561), `--redirect stderr` does not mean "redirect stderr to the pipeline" (what i assumed to mean "the next command's stdin"), it currently means "redirect stderr to the *stderr stream* in the pipeline", which is ignored by most (all?) nu commands, and as far as i can tell from https://github.com/nushell/nushell/issues/4396, exists purely for use with `capture` or redirects.

trying to redirect stderr to stdout as follows kind of works, but rather than going into nu's pipeline as expected, it is written to the terminal.
```nu
> run-external --redirect-stderr "python" "-c" "import sys; print('hello on stderr', file=sys.stderr)" err> /dev/stdout | inspect
hello on stderr
Error: nu::shell::pipeline_mismatch

  × Pipeline empty.
   ╭─[entry #27:1:1]
 1 │ run-external --redirect-stderr "python" "-c" "import sys; print('hello on stderr', file=sys.stderr)" err> /dev/stdout | inspect
   ·                                                                                                                         ───┬───
   ·                                                                                                                            ╰── no input value was piped in
   ╰────
```

### How to reproduce

```nu
run-external --redirect-stderr "python" "-c" "import sys; print('hello on stderr', file=sys.stderr)" | inspect
```

### Expected behavior

I expected nu to have an easy way to read and operate on stderr, and in general manipulate io streams freely, since it is common functionality in posix/bash/zsh etc.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.86.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 5d8763ed1d14048ac9fc09eb21be36e6e622f0d7                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03) (Arch Linux rust 1:1.73.0-1) |
| cargo_version      | cargo 1.73.0                                                     |
| build_time         | 2023-10-18 08:45:09 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by MarikaChlebowska** [comment]
I agree, I think redirect-stderr should simply move stderr of the command to stdout so next command can use it as an input. I'm not sure if we should  keep stderr of the run-external empty or keep it as it is right now. If someone from the maintainers gives me a green light I think I can change it.
