### ISSUE TITLE
Add "Use '--help(-h)' for more information." to nu::parser::missing_positional error

### ISSUE THREAD

**Issue by dzorya** [nushell/nushell#10946]
### Describe the solution you'd like

Right now if user runs a command or script without required positional arguments, error message will display usage but won't suggest to use very nice --help (-h) flag.

At the same time Error: nu::parser::unknown_flag has text "Use `--help` for more information." in the help string.

I would like to suggest to add similar text to nu::parser::missing_positional error.

This way even if a user of .nu script don't know anything about Nushell he will be able to understand that script supports --help (-h) flag.

![image](https://github.com/nushell/nushell/assets/1835944/03cb8808-7e85-4ca0-8e58-e18fde369578)

I can prepare MR if I correctly identified place where the change is required.

### Describe alternatives you've considered

Maybe the change could be inside help. It might be not a bad idea to add '--help' mention to other errors as well

### Additional context and details

If I'm not mistaken, text could be added here:

    #[error("Missing required positional argument.")]
    #[diagnostic(code(nu::parser::missing_positional), help("Usage: {2}**. Use '--help(-h)' for more information.**"))]
    MissingPositional(String, #[label("missing {0}")] Span, String),

**Comment by fdncred** [comment]
Seems like a reasonable request that would make our help message for missing_positional more helpful.
