### ISSUE TITLE
alias foo=bar should work

### ISSUE THREAD

**Issue by hholst80** [nushell/nushell#10958]
### Related problem

This makes no sense to the user:

```
~> alias h=httpie
Error: nu::parser::incorrect_value

  × Incorrect value
   ╭─[entry #7:1:1]
 1 │ alias h=httpie
   · ──┬──
   ·   ╰── unexpected Incomplete alias
   ╰────
  help: incomplete alias

~>      
```

The "error" here is that the = token should be a separate command line argument.  The same requirement exists for 'expr' from the 1970s.  I think we can let that convention RIP with those legacy tools and adopt more modern notation where the space between operators are made optional.

### Describe the solution you'd like

Support either or both:

```
alias foo bar
```

```
alias foo=bar
```

**Comment by fdncred** [comment]
Nushell needs spaces like `alias h = httpie`. You can read about it in our book https://www.nushell.sh/book/aliases.html#aliases

**Comment by amtoine** [comment]
i guess the error here is unhelpful and should point towards the `=` with no space around :+1:

**Comment by hholst80** [comment]
All shells except nushell handles the convention that I outlined above.  This is a needless divergence from user experience.  Pointing to the divergence in a manual is not good UX.

![image](https://github.com/nushell/nushell/assets/6200749/1c098ffc-bfd9-45a8-9c51-64cec927c082)

**Comment by KAAtheWiseGit** [comment]
The problem is that `=` is an operator in Nushell.  So making parse without whitespace separation would cause issues for other commands, for example `go build -ldflags="-s -w" -tags release`.

In theory `alias` could be special-cased, but this feels like an inconsistent hack to me.

**Comment by KAAtheWiseGit** [comment]
As for the error, I'll create a PR soon:

```Nushell
Error: nu::parser::incorrect_value

  × Incorrect value
   ╭─[entry #2:1:1]
 1 │ alias foo=bar
   ·       ───┬───
   ·          ╰── unexpected alias argument
   ╰────
  help: Use `alias foo = bar` instead
```

**Comment by fdncred** [comment]
I like the error message that explains what the fix is. It's more helpful than what we have now.
