### ISSUE TITLE
`1..=1..` crashes nushell

### ISSUE THREAD

**Issue by IanManske** [nushell/nushell#10951]
### Describe the bug

Typing `1..=1..` crashes nushell with the panic message:
```
thread 'main' panicked at crates/nu-protocol/src/engine/state_working_set.rs:340:37:
slice index starts at 8 but ends at 7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### How to reproduce

Copy + paste or type:
```
1..=1..
```
directly into the prompt.

If anything else is already in the prompt, then the crash might not happen. E.g.:
```
sometext 1..=1..
```
does not trigger the panic.

### Expected behavior

Should not panic

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.86.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 5d8763ed1d14048ac9fc09eb21be36e6e622f0d7                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03) (Arch Linux rust 1:1.73.0-1) |
| cargo_version      | cargo 1.73.0                                                     |
| build_time         | 2023-10-18 08:45:09 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment]
We allow numbers in the middle of a range like this. I'm not sure what `1..=1..` is meant to express but it shouldn't crash.
```nushell
❯ 1..3..10
╭─┬─╮
│0│1│
│1│3│
│2│5│
│3│7│
│4│9│
╰─┴─╯
```

**Comment by hholst80** [comment]
Side note:  I do not think this was the expected result?

![image](https://github.com/nushell/nushell/assets/6200749/7e960e47-f561-4b6b-b9b7-ebad7dbd13d4)

**Comment by IanManske** [comment]
`1..=1..` doesn't mean anything; it happened while I was being confused by ranges with a number in the middle.

But yeah, I was expecting the range syntax to mean `start..step..end`, but it looks like it actually means `start..next..end` which is surprising to me. My expectations from F# are showing I guess. Anyways, this should probably be a separate issue.

**Comment by fdncred** [comment]
ya, i've always hated that syntax and thought it was wrong, but I got overruled when it was introduced. So, if I need to do this type of thing, I usually use `seq` which has a more "normal" syntax for my taste.

**Comment by IanManske** [comment]
Actually, looks like this is a duplicate of #9417.
