### ISSUE TITLE
Please update the trash crate to the latest version

### ISSUE THREAD

**Issue by yurivict** [nushell/nushell#10961]
### Describe the bug

nushell fails to build on FreeBSD with the older trash crate.
\

### How to reproduce

n/a

### Expected behavior

n/a

### Configuration

n/a

**Comment by fdncred** [comment]
Please feel free to submit a PR. Not sure if dependabot has one in the queue yet or not.

**Comment by amtoine** [comment]
i don't see one in the [`dependencies`](https://github.com/nushell/nushell/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies)

**Comment by yurivict** [comment]
@amtoine 
0.86.0 depends on trash.

**Comment by amtoine** [comment]
> 0.86.0 depends on trash.
>
i meant that there is no `dependabot` PR in the queue to update this crate

**Comment by fdncred** [comment]
looks like `cargo update -p trash` would update from 3.1.0 to 3.1.2. I don't see a newer version.

**Comment by fdncred** [comment]
I put up a PR to fix this
