### ISSUE TITLE
`alias` can take in more than three arguments

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#10978]
### Describe the bug

The following command is valid and creates an alias:

```Nushell
alias foo = bar a b c d e ...
```

### How to reproduce

Use the `alias` command with additional arguments after the first three.

### Expected behavior

An error.

### Configuration

| key                | value                                              |
| ------------------ | -------------------------------------------------- |
| version            | 0.86.1                                             |
| branch             | mkdir                                              |
| commit_hash        | 6b48486f268520a455eea4a302eddd7a5ec1ec63           |
| build_os           | linux-x86_64                                       |
| build_target       | x86_64-alpine-linux-musl                           |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (Alpine Linux) |
| cargo_version      | cargo 1.71.1                                       |
| build_time         | 2023-10-26 19:51:06 +03:00                         |
| build_rust_channel | debug                                              |
| allocator          | mimalloc                                           |
| features           | default, sqlite, trash, which, zip                 |
| installed_plugins  |                                                    |

**Comment by amtoine** [comment]
what would be the error @KAAtheWiseGit? :yum:

**Comment by KAAtheWiseGit** [comment]
Something akin to this, I think:

```Nushell
~> source foo.nu a
Error: nu::parser::extra_positional

  × Extra positional argument.
   ╭─[entry #11:1:1]
 1 │ source foo.nu a
   ·               ┬
   ·               ╰── extra positional argument
   ╰────
  help: Usage: source <filename>
```

**Comment by KAAtheWiseGit** [comment]
I think I can add it on the same forked branch after #10975 is merged or closed.

**Comment by amtoine** [comment]
i must be confused by the example above, why is the followin not valid?
```nushell
alias foo = bar a b c d e ...
```

**Comment by KAAtheWiseGit** [comment]
@amtoine nope, it is me who is confused.  I just realized that commands can have arguments, so this request is moot.  Sorry for the false alarm, closing the report.

P.S.
I think I got confused after doing this:

```Nushell
~> alias a = b b b b b
~> a
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #4:1:1]
 1 │ a
   · ┬
   · ╰── executable was not found
   ╰────
  help: No such file or directory (os error 2)
```

I'll close this issue and open a separate one, about the error clarity.
