### ISSUE TITLE
How to compare the difference between two sets?

### ISSUE THREAD

**Issue by 107295472** [nushell/nushell#10974]
### Question
```nushell
def excelfind [xl, path] {
  let fi = (open $"($xl).xlsx" | get Sheet0|get column0)
  
  cd $path
  
  let p = (ls *.pdf | get name)
  
  let pp = ($p | each {|it | str replace '.pdf'  '' })
  
  echo $pp

  echo $fi
}
```

The difference between pp and fi

**Comment by amtoine** [comment]
i don't think we have such a command in `std iter` but that could be a great addition :+1:

**Comment by 107295472** [comment]
amtoine Yes, it’s just you, finally write a command line in rust
Do you want to close this? Are you an administrator?

**Comment by amtoine** [comment]
i can close this if you think your question has been answered :yum:
