### ISSUE TITLE
Shell integration communicates wrong PWD to VS Code on Windows

### ISSUE THREAD

**Issue by CAD97** [nushell/nushell#10989]
### Describe the bug

If the PWD is `D:\git\nushell\nushell`, then VS Code thinks the shell session working directory is `/D:git\nushell\nushell`.

### How to reproduce

On Windows,

1. Enable shell integration for nu, e.g. with `if ($env.TERM_PROGRAM? == "vscode") { $env.config.shell_integration = true }` in your config.
2. Open an integrated nu shell in VS Code and hit enter at least once.
3. Use the [**Terminal: Go to Recent Directory**](https://code.visualstudio.com/docs/terminal/shell-integration#_go-to-recent-directory) intent (<kbd><kbd>CTRL</kbd>+<kbd>G</kbd></kbd> with the terminal focused).
4. Note that the shown directories for the current session are prefixed with a `/`.

### Expected behavior

I expected nu to report the PWD in a way recognized correctly by VS Code.

### Screenshots

![screenshot of vscode](https://github.com/nushell/nushell/assets/5992217/359b9b83-71d0-4866-915f-b7a4d2445625)

Current session: with just `$env.config.shell_integration = true`, which emits `(ansi osc)7;file://localhost/($env.PWD | str url-encode)(ansi st)`, the shell session directory is detected as `/D:\.config\nushell`.

Previous session: using an `env_change.PWD` hook which emits the [vscode-specific](https://code.visualstudio.com/docs/terminal/shell-integration#_supported-escape-sequences) `(ansi osc)633;P;Cwd=($env.PWD)(ansi st)`, the shell session directory is detected as `D:\.config\nushell`.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.86.0                                   |
| branch             |                                          |
| commit_hash        | 5d8763ed1d14048ac9fc09eb21be36e6e622f0d7 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)      |
| rust_channel       | 1.71.1-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)      |
| build_time         | 2023-10-18 07:39:55 -05:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
That's weird. Although I've never tried to use Ctrl-G either. I see this with some debug statements on run_ansi_sequence.
```
seq: "\u{1b}]133;C\u{1b}\\"
seq: "\u{1b}]133;D;0\u{1b}\\"
seq: "\u{1b}]7;file://MYHOSTNAME/D:\\nushell\u{1b}\\"
seq: "\u{1b}]2;D:\\nushell\u{7}"
seq: "\u{1b}[?1l"
```
I'm not sure what to change it to. Maybe change the backslashes into forward slashes?

**Comment by fdncred** [comment]
Forward slashes don't seem to make a difference. Could this be a vscode bug?

**Comment by fdncred** [comment]
We could do this. It seems to work but I'm not super keen on specific terminal ansi escape sequences.
```rust
                        if stack.get_env_var(engine_state, "TERM_PROGRAM")
                            == Some(Value::test_string("vscode"))
                        {
                            // vscode specific (ansi osc)633;P;Cwd=($env.PWD)(ansi st)
                            run_ansi_sequence(&format!("\x1b]633;P;Cwd={}\x1b\\", path))?;
                        } else {
                            // Communicate the path as OSC 7 (often used for spawning new tabs in the same dir)
                            run_ansi_sequence(&format!(
                                "\x1b]7;file://{}{}{}\x1b\\",
                                percent_encoding::utf8_percent_encode(
                                    &hostname.unwrap_or_else(|| "localhost".to_string()),
                                    percent_encoding::CONTROLS
                                ),
                                if path.starts_with('/') { "" } else { "/" },
                                percent_encoding::utf8_percent_encode(
                                    &path,
                                    percent_encoding::CONTROLS
                                )
                            ))?;
                        }
```

**Comment by CAD97** [comment]
(Ctrl+G is just the easiest way to see what vscode thinks here, it's also used for e.g. split terminal.)

It does seem like a VS Code bug in the handling of OSC 7, tbh. Their own `toFileUri` on a glance seems to produce `file:///D:/nushell`, but providing that still gets detected as `/D:/nushell`, and emitting `file://D:/nushell` gets detected as `/nushell`. There's an off-by-one somewhere.
