### ISSUE TITLE
Pasting with bracketed_paste creates escape codes that affect some programs

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [nushell/nushell#10982]
### Describe the bug

This is the continuing of the saga bracketed_paste saga, as can be seen followed here:

https://github.com/nushell/nushell/issues/9218
https://github.com/nushell/nushell/pull/9399
https://github.com/nushell/reedline/pull/598
https://github.com/nushell/reedline/issues/648
https://github.com/nushell/reedline/pull/657

With the merging of https://github.com/nushell/reedline/pull/657 multiline pasting should work again, with the exception of what used to be https://github.com/nushell/nushell/issues/9218.

Currently when bracketed_paste is enabled and something is copied over into a `curses` program, two escape characters are send as well and converted to strings.

`^[[200~ (actual content) ^[[201~`

Curses listens to raw keystrokes and attempts to convert them to strings. Apparently the bracketed paste sends two keys along with the actual content, resulting in this bug.

I have not yet been able to deduce what keys these are exactly. 

Edit: This doesn't happen in just curses. It happens everywhere except most programs ignore these escape codes. Because `bracketed_paste` means that the pasted content is send in between two brackets, which some programs pick up.

### How to reproduce

1. Compile `nushell` with the latest revision of reedshell's `main` branch. Using reedline from git should already be configured in `patch.crates.io` , so you just need to `cargo update`.
2. `cargo run`
3. `cat -`
4. Paste into the STDIN of cat
### How to reproduce (old)

1. Compile `nushell` with the latest revision of reedshell's `main` branch. Using reedline from git should already be configured in `patch.crates.io` , so you just need to `cargo update`.
2. `cargo run`
5. Execute the following python code or open another curses application:
```PYTHON
import curses

def main():
    # Initialize curses
    stdscr = curses.initscr()

    # Prompt for password
    stdscr.addstr("Paste text using bracketed_paste: ")
    password = ""
    while True:
        key = stdscr.getch()

        password += chr(key)

        stdscr.clear()  # Clear screen
        stdscr.addstr("Paste text using bracketed_paste: " + password)

if __name__ == "__main__":
    main()
```
6. Attempt to copy something into curses text prompt.

### Expected behavior

Nushell would be expected to insert the pasted content into curses without inserting these control keys.

### Screenshots

[![asciicast](https://asciinema.org/a/6oAm8SPCdDalgCXHW5ASGiXAK.svg)](https://asciinema.org/a/6oAm8SPCdDalgCXHW5ASGiXAK)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.86.1                                   |
| branch             | main                                     |
| commit_hash        | 51d5d0eac84ab883123eb0e621c8d71c396eb115 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)      |
| rust_channel       | 1.71.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)      |
| build_time         | 2023-11-06 22:13:06 +01:00               |
| build_rust_channel | debug                                    |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I believe bracketed_paste is a recent addition to crossterm. Have you looked into how it's implemented there yet? I'm guessing it may give some clue of what's going on. e.g. is crossterm doing the wrong thing or is curses hearing the wrong thing or are there issues already in crossterm's repo about this exact thing?

**Comment by LevitatingBusinessMan** [comment]
The bug can be traced to this function:

https://github.com/crossterm-rs/crossterm/blob/08762b3ef4519e7f834453bf91e3fe36f4c63fe7/src/event/sys/unix/parse.rs#L813-L823

**Comment by fdncred** [comment]
Nice! Glad you found it. Do you plan on submitting a PR to crossterm to fix the bug?

**Comment by LevitatingBusinessMan** [comment]
I still haven't figured out the ins and outs of out. It might not even be a "bug" per se, just an artifact from the way crossterm does bracketed pasting. It seems to wrap the content in two escape codes so it is handled differently, and applications like curses pick up these escape characters. 

This also isn't specific to curses at all. These codes are ALWAYS created, though ignored by most programs.

In this example, you can see that the characters are displayed when pasting into the STDIN of a program, and also read by said program. `-A` with cat makes it display all characters even non-visible ones.

[![asciicast](https://asciinema.org/a/S1Q7W18V96MqpRBA0yyz4RRCa.svg)](https://asciinema.org/a/S1Q7W18V96MqpRBA0yyz4RRCa)

**Comment by LevitatingBusinessMan** [comment]
I just realized, these escape characters are obviously the "brackets" of bracketed_pasting.

**Comment by fdncred** [comment]
I think `^` is the escape and `[[` are the brackets. I'm just not sure why there are two `[`'s.

**Comment by fdncred** [comment]
From what I can see in crossterm, it's not generating the `ESC[200~` or `ESC[201~`, only parsing them. So, if some other program is generating `ESC[[200~` and `ESC[[201~` I'm not sure how it's crossterm's fault. Maybe we can intercept the paste and replace `[[` with `[` under certain conditions?

**Comment by LevitatingBusinessMan** [comment]
> From what I can see in crossterm, it's not generating the `ESC[200~` or `ESC[201~`, only parsing them. So, if some other program is generating `ESC[[200~` and `ESC[[201~` I'm not sure how it's crossterm's fault. Maybe we can intercept the paste and replace `[[` with `[` under certain conditions?

Crostterm creates them, that's the point of bracketed paste. It tells the terminal emulator (traditionally xterm) to handle the text in between them differently (as a single line).

> I think ^ is the escape and [[ are the brackets. I'm just not sure why there are two ['s.

That's the syntax for these codes, if you open `cat` in nushell and start typing other control characters like the arrow keys they'll have a similar encoding.

https://en.wikipedia.org/wiki/Bracketed-paste#Description_of_bracketed-paste

This isn't a bug but an intended sideaffect. But I see an obvious solution which is to disable bracketed paste during the execution of the child process. Crossterm has no business altering that behaviour once your control has left the shell. It's only useful within the shell itself when reedline is used. If a child process wants bracketed paste they can configure that themselves.

@WindSoilder's solution https://github.com/nushell/nushell/pull/9399 was correct.

**Comment by LevitatingBusinessMan** [comment]
> From what I can see in crossterm, it's not generating the `ESC[200~` or `ESC[201~`, only parsing them. So, if some other program is generating `ESC[[200~` and `ESC[[201~` I'm not sure how it's crossterm's fault. Maybe we can intercept the paste and replace `[[` with `[` under certain conditions?

Correct, crossterm only tells the terminal emulator to enable it[1]. The terminal emulator (traditionally xterm) then inserts these control characters when the user pastes, so that the underlying process (in this case nushell/reedline) can handle these differently. Useful for text-editors, shells, other readline like implementations. But bad when working with raw characters. 

> I think ^ is the escape and [[ are the brackets. I'm just not sure why there are two ['s.

That's the syntax for these codes, if you open `cat` in nushell and start typing other control characters like the arrow keys they'll have a similar encoding.

https://en.wikipedia.org/wiki/Bracketed-paste#Description_of_bracketed-paste

This isn't a bug but an intended sideaffect. But I see an obvious solution which is to disable bracketed paste during the execution of the child process. Nushell shouldn't alter the behavior of the terminal once it has lost control to a child . It's only useful within the shell itself when reedline is used. If a child process wants bracketed paste they can configure that themselves.

@WindSoilder's solution https://github.com/nushell/nushell/pull/9399 was correct./

[1]: https://github.com/crossterm-rs/crossterm/blob/08762b3ef4519e7f834453bf91e3fe36f4c63fe7/src/event.rs#L381

**Comment by LevitatingBusinessMan** [comment]
I will make a new PR that disables bracketed paste from within nushell before it forks and executes a child. And re-enables it after nushell takes control back. We'll do the proper testing and if it works it's up to you guys to merge it.
