### ISSUE TITLE
There is no problem in cmd execution, but it is wrong to use nushell parameter path.

### ISSUE THREAD

**Issue by 107295472** [nushell/nushell#10994]
### Question
```
 rping -x "C:\da1.xlsx" -p "D:\work\rust\rping\target\release\files" -i 1           11/08/2023 02:52:35 PM
Error:   × Invalid literal
   ╭─[entry #9:1:1]
 1 │ rping -x "C:\da1.xlsx" -p "D:\work\rust\rping\target\release\files" -i 1
   ·              ────┬────
   ·                  ╰── unrecognized escape after '\' in string
   ╰────
```

**Comment by fdncred** [comment]
This is because you're using double quotes. Double quotes in nushell mean to interpret escapes. So, instead of seeing a path, it's seeing you trying to escape `\d`, `\w`, `\r`, etc. The solution is to use single quote or backtick quotes. Please reopen if this doesn't solve the problem.

**Comment by 107295472** [comment]
Thank you, single quotes are fine
