### ISSUE TITLE
$nu:path doesn't work as documented

### ISSUE THREAD

**Issue by ndarilek** [nushell/nushell#1099]
```
/home/nolan/src/nushell(master)> config --set [path $nu:path]
error: Parse Error
- shell:1:28
1 | config --set [path $nu:path]
  |              ^^^^^^^^^^^^^^^
```

Run on master as of 30 seconds ago.

Additionally, nothing I run seems to acknowledge that `$nu:path` is valid syntax.

Thanks for creating this--looking forward to learning to use it.

**Comment by miller-time** [comment]
I think the following commands work on Linux as temporary workaround.

instead of `config --set [path $nu:path]`:
```
> bash -c "echo $PATH" | trim | split-row ":" | config --set_into path
```

instead of `config --set [env $nu:env]`:
```
> env | get vars | config --set_into env
```

**Comment by jonathandturner** [comment]
`$nu:path` is now `$nu.path`, and similarly for env and config.  I'll go update the docs as well
