### ISSUE TITLE
Erroneous Size Calculation

### ISSUE THREAD

**Issue by UTFeight** [nushell/nushell#11009]
### Describe the bug

![grafik](https://github.com/nushell/nushell/assets/101834410/e6476fa3-de87-4866-986a-011c68746828)

nu thinks 1.023mb equals to `1mb` which is not the case!
`1023kb = 1mb`

### How to reproduce

simply type 1.023mb into shell repl

### Expected behavior

1.023mb = 1.023mb != 1mb

### Screenshots

![grafik](https://github.com/nushell/nushell/assets/101834410/bc9cad4f-5a95-4753-b25f-d78186e6ce16)

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.86.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 5d8763ed1d14048ac9fc09eb21be36e6e622f0d7                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03) (Arch Linux rust 1:1.73.0-1) |
| cargo_version      | cargo 1.73.0                                                     |
| build_time         | 2023-10-18 08:45:09 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by RGBCube** [comment]
kb here refers to KibiBytes

**Comment by RGBCube** [comment]
It is rounded down, it's an approximation, if you were to type 1100mb it would show 1.1gb

**Comment by fdncred** [comment]
This is the way the human readable numbers work. Just like when you do a `ls`.
```
❯ ls                                                                                                                                                0  06:27:02 AM
╭#─┬───────name────────┬type┬──size──┬──modified──╮
│0 │CODE_OF_CONDUCT.md │file│  3.4 KB│7 months ago│
│1 │CONTRIBUTING.md    │file│ 18.8 KB│2 days ago  │
│2 │Cargo.lock         │file│149.8 KB│12 hours ago│
│3 │Cargo.toml         │file│  6.0 KB│12 hours ago│
│4 │Cross.toml         │file│   666 B│2 months ago│
│5 │LICENSE            │file│  1.1 KB│7 months ago│
│6 │PLATFORM_SUPPORT.md│file│  3.9 KB│2 days ago  │
│7 │README.md          │file│ 12.2 KB│2 days ago  │
│8 │assets             │dir │   160 B│5 months ago│
│9 │benches            │dir │   128 B│2 months ago│
│10│crates             │dir │  1.1 KB│2 days ago  │
│11│docker             │dir │    96 B│12 hours ago│
│12│rust-toolchain.toml│file│  1.1 KB│2 days ago  │
│13│scripts            │dir │   448 B│2 days ago  │
│14│src                │dir │   448 B│12 hours ago│
│15│target             │dir │   224 B│2 weeks ago │
│16│tests              │dir │   480 B│7 months ago│
│17│toolkit.nu         │file│ 14.7 KB│2 days ago  │
│18│wix                │dir │   160 B│4 months ago│
╰#─┴───────name────────┴type┴──size──┴──modified──╯
```
if you want to see the actual bytes, you can change the filesize.format setting in the config.
```
❯ $env.config.filesize.format = b
❯ ls
╭#─┬───────name────────┬type┬─size──┬──modified──╮
│0 │CODE_OF_CONDUCT.md │file│  3,444│7 months ago│
│1 │CONTRIBUTING.md    │file│ 18,784│2 days ago  │
│2 │Cargo.lock         │file│149,806│12 hours ago│
│3 │Cargo.toml         │file│  6,019│12 hours ago│
│4 │Cross.toml         │file│    666│2 months ago│
│5 │LICENSE            │file│  1,094│7 months ago│
│6 │PLATFORM_SUPPORT.md│file│  3,854│2 days ago  │
│7 │README.md          │file│ 12,219│2 days ago  │
│8 │assets             │dir │    160│5 months ago│
│9 │benches            │dir │    128│2 months ago│
│10│crates             │dir │  1,056│2 days ago  │
│11│docker             │dir │     96│12 hours ago│
│12│rust-toolchain.toml│file│  1,106│2 days ago  │
│13│scripts            │dir │    448│2 days ago  │
│14│src                │dir │    448│12 hours ago│
│15│target             │dir │    224│2 weeks ago │
│16│tests              │dir │    480│7 months ago│
│17│toolkit.nu         │file│ 14,740│2 days ago  │
│18│wix                │dir │    160│4 months ago│
╰#─┴───────name────────┴type┴─size──┴──modified──╯
```
