### ISSUE TITLE
Rust backtrace output is mangled in Nushell

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#11029]
### Describe the bug

For some reason, when trying to catch Rust backtrace of Nushell with RUST_BACKTRACE in Nushell REPL, the output it mangled: It seems to contain extra whitespace without line breaks.

### How to reproduce

1. Clone Nushell repo
2. `RUST_BACKTRACE=1 cargo run`
3. Crash Nushell somehow (e.g., reproducing https://github.com/nushell/nushell/issues/11028)
4. Observe the mangled output: It's all in one line.

### Expected behavior

Expected each backtrace location on separate line.

### Configuration

| key                | value                                                                                                                      |
| ------------------ | -------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.86.1                                                                                                                     |
| branch             | main                                                                                                                       |
| commit_hash        | cd75640a90d5166ee529a8c1c49eb9d2ab34253a                                                                                   |
| build_os           | linux-x86_64                                                                                                               |
| build_target       | x86_64-unknown-linux-gnu                                                                                                   |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)                                                                                        |
| rust_channel       | 1.71.1-x86_64-unknown-linux-gnu                                                                                            |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)                                                                                        |
| build_time         | 2023-11-09 08:54:02 +02:00                                                                                                 |
| build_rust_channel | release                                                                                                                    |
| allocator          | mimalloc                                                                                                                   |
| features           | default, extra, sqlite, trash, which, zip                                                                                  |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, highlight, hist, inc, plot, query, query json, query web, query xml, xyplot |

**Comment by sholderbach** [comment]
When the completions crash this happens while reedline controls the terminal so the raw mode is still active.

#10942 added a different panic display handler, very possible that this does not reset the terminal properly before drawing. (In theory during unwinding `impl Drop for reedline::Reedline` should disable raw mode.)

**Comment by fdncred** [comment]
hmmm, i wonder if there's a way to switch back from raw from nushell before the panic handler runs?

**Comment by sholderbach** [comment]
Using `RUST_BACKTRACE=1 nu` with `nu` being the stable 0.86 build before the introduction of `color-backtrace` displays perfectly fine.

**Comment by fdncred** [comment]
"perfectly fine" is in the eye in the beholder. Rust has some of the worst backtraces I've ever seen. I rarely advocate for Microsoft but their C# backtraces are much easier to interpret. But you rarely need that type of thing in C# because Visual Studio debugging is so awesome. oh well, there's a few of these type of things for rust, maybe we'll find one that works better.

**Comment by kubouch** [comment]
It would be great to have a decent backtrace in Nushell, agreed. Not sure if we can fix the color backtrace somehow.

**Comment by fdncred** [comment]
Here's another few to try.

https://github.com/eyre-rs/color-eyre
https://github.com/bjorn3/pretty_backtrace <-- older, not sure it works.
https://github.com/mitsuhiko/better-panic

Would be nice to just fix this one somehow.
https://github.com/athre0z/color-backtrace
