### ISSUE TITLE
nushell 0.86 regression: command option type and value is incorrectly inferred from default value

### ISSUE THREAD

**Issue by srackham** [nushell/nushell#11033]
### Describe the bug

In the following tests, explicitly typing an `int` option (`--age`) causes the next option (`--name`) to default to `false` instead of `"foobar"`:

```nushell
#[test]
def test-cmd1 [] {
    assert equal (cmd1) "foobar" # PASS
}

def cmd1 [
    --age = 0
    --name = "foobar"
] {
    $name   # "foobar"
}

#[test]
def test-cmd2 [] {
    assert equal (cmd2) "foobar" # FAIL
}

def cmd2 [
    --age: int = 0
    --name = "foobar"
] {
    $name   # false
}

#[test]
def test-cmd3 [] {
    assert equal (cmd3) "foobar" # FAIL
}

def cmd3 [
    --age: int
    --name = "foobar"
] {
    $name   # false
}
```

### How to reproduce

Run the above tests.

### Expected behavior

The above tests should pass.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.86.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 5d8763ed1d14048ac9fc09eb21be36e6e622f0d7                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03) (Arch Linux rust 1:1.73.0-1) |
| cargo_version      | cargo 1.73.0                                                     |
| build_time         | 2023-10-18 08:45:09 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment]
Seems like a odd bug.

**Comment by amtoine** [comment]
no need to run tests or anything :wink: 
```nushell
def foo [
    --age = 0
    --name = "foobar"
] {
    print $"age: ($age)"
    print $"name: ($name)"
}
```
then
```
> foo
age: 0
name: false
```

> **Note**
> happens as long as there is a `: int` type annotation

**Comment by srackham** [comment]
@amtoine Should read `--age: int = 0` in above `foo` def.

**Comment by amtoine** [comment]
> @amtoine Should read `--age: int = 0` in above `foo` def.
>
wooopsie, wrong one :eyes: 
updated :wink: :pray:

**Comment by WindSoilder** [comment]
If we have one comma after `--age: int = 0`, it works fine again...
```nushell
def foo [
    --age: int = 0,     # one , here..
    --name = "foobar"
] {
    print $"age: ($age)"
    print $"name: ($name)"
}
```
