### ISSUE TITLE
`0.7.1` Installing nushell via cargo with `--features=stable` is missing several plugins 

### ISSUE THREAD

**Issue by notryanb** [nushell/nushell#1103]
**Describe the bug**
When I install nushell via cargo with `cargo install nu --features=stable --force`, version `0.7.1` is installed, but missing several plugins. When checking the `.cargo/bin` directory I see `inc`, `ps`, `str`, `sys`, `textview`, and `tree` executables. The other stable feature plugins are missing.

`help fetch` or any of the other missing plugins does not return anything and when I try to use the plugin, an error is thrown that nushell can't find it.

**To Reproduce Both Windows & MacOS**
1. `cargo install nu --features=stable --force`
2. Try to use plugins like `fetch`, `post`, `sum`, `average`.

**Expected behavior**
Nushell version `0.7.1` should be installed with all stable feature plugins listed in Cargo.toml.

**Configuration (please complete the following information):**
- Windows 10 / MacOS 10.13.6 (High Sierra)
- Nushell version `0.7.1`

I know this was fixed in `Cargo.toml`  for `0.7.1` and when I build nu from source with `cargo build --all --features=stable` it works fine. I'm assuming this is something to do with the cargo release itself.

**Comment by jonathandturner** [comment]
Now that you point this out, I think it's a known limitation of `cargo install` that your can't install more than one binary (unless they all come from the same crate)

Which leaves you having to manually install plugins. I wonder if we should work with the cargo folks in an rfc to improve this

**Comment by notryanb** [comment]
Is there a way to cargo install Nu with `--features=stable` when building it from source? I know I can either add the target dir to my path or manually copy the executables into one of them.

**Comment by jonathandturner** [comment]
Sadly not yet. We'd like to make `cargo install` with --features=stable to copy them in so you don't have to manually install, but for now the copying is manual

**Comment by jonathandturner** [comment]
This should be fixed in more recent releases.
