### ISSUE TITLE
Ctrl-l does not clear screen

### ISSUE THREAD

**Issue by eltonlaw** [nushell/nushell#1104]
**Probably related to this: https://github.com/nushell/nushell/issues/1050. Didn't know if I should make another issue since that one is Windows specific. Please feel free to close this as duplicate if you think this is unnecessary.

**Describe the bug**
Pressing Ctrl-l does not clear the screen

**Expected behavior**
Ctrl-l should clear the screen

**Configuration (please complete the following information):**
 - Version: Linux 5.4.3-arch1-1
 - nu v0.7.1 (`cargo run` on master; currently commit `f9da7f7d58da3ead2aaba6a519c554d1b199c158` is HEAD)

**Comment by jonathandturner** [comment]
This should work in master now as of a few hours ago. If it doesn't please re-open and let us know.
