### ISSUE TITLE
add curl -F functionality to http post

### ISSUE THREAD

**Issue by kurokirasama** [nushell/nushell#11046]
### Related problem

I haven't been able to a `curl` request like this:
 ```bash
 curl $url -H $header -F image="@file.png" -F size="1024x1024"
 ```
 with `http post`. Maybe it's possible but it should be more visible or be somewhere in the documentation.

### Describe the solution you'd like

the `curl` command should have an `http post` equivalent like:
```bash
http post -t application/x-www-form-urlencoded -H $header $site -F {image="@file.png", size="1024x1024"}
```

**Comment by amtoine** [comment]
what does `curl -F` do?

**Comment by KAAtheWiseGit** [comment]
@amtoine, it sends a multipart form.

**Comment by amtoine** [comment]
> @amtoine, it sends a multipart form.
>
no idea what this is but thanks for the pointer :wink: :pray:

**Comment by KAAtheWiseGit** [comment]
@amtoine MDN has a nice short overview: <https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST>
