### ISSUE TITLE
`std clip` does not work correctly in Linux (Wayland)

### ISSUE THREAD

**Issue by FMotalleb** [nushell/nushell#11041]
### Describe the bug

There are two issues
1. the `notify-send` is not found 
2. the `wl-clip` hangs until I open its application from taskbar

### How to reproduce

using this script on a Linux (Wayland) machine
```bash
~> use std clip
~> echo test | clip
```

### Expected behavior

to just copy the content to clipboard

### Configuration

| key                | value                                                                                                                                                                             |
| ------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.86.0                                                                                                                                                                            |
| branch             |                                                                                                                                                                                   |
| commit_hash        |                                                                                                                                                                                   |
| build_os           | linux-x86_64                                                                                                                                                                      |
| build_target       | x86_64-unknown-linux-gnu                                                                                                                                                          |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                                                                                                                                               |
| rust_channel       | stable-x86_64-unknown-linux-gnu                                                                                                                                                   |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                                                                                                                                               |
| build_time         | 2023-11-05 12:48:51 +03:30                                                                                                                                                        |
| build_rust_channel | release                                                                                                                                                                           |
| allocator          | mimalloc                                                                                                                                                                          |
| features           | dataframe, default, sqlite, trash, which, zip                                                                                                                                     |
| installed_plugins  | from eml, from ics, from ini, from vcf, notify, port list, port scan, scan port, scanport, sound, sound beep, sound make, sound meta, sound meta list, sound meta set, sound play |

**Comment by IanManske** [comment]
> 1. the notify-send is not found

Do you mean that `notify-send` from `libnotify` is not present on your system? If this is the case, then you can pass the `--no-notify` flag. Maybe `--no-notify` should be the default?

> 2. the wl-clip hangs until I open its application from taskbar

Sorry, could you explain further? It seems to work fine for me (I'm also on Wayland).

**Comment by FMotalleb** [comment]
Hi,

Unfortunately, for more information, I should direct you to a thread in [Discord](https://discord.com/channels/601130461678272522/1173534968673214514) with @amtoine 

This is a complex issue with various elements:

1. First of all, the clip command should not perform two actions (`copy`, `notify`). Users are capable of using pipelines.
2. It is problematic that a simple command forces me to either manually turn off its optional feature or install a library.
3. There are indeed multiple issues with the functionalities of `xclip` and `wl-clipboard`. They behave differently on each operating system.
> For instance, in my case, which involves `Debian 12.2` + `gnome 43`, `wl-clipboard` does not work, but `xclip` does. However, if I use `xclip` in a pipeline, it disrupts the pipeline (hangs until I change the clipboard), which prevents me from using the notify functionality in the first place.

Lastly, why would we define a command in the **`std`** library that relies on external optional components? This is a point that may need further discussion.

and at the end I created a [plugin for clipboard](https://github.com/FMotalleb/nu_plugin_clipboard) instead of using clip because of the issues listed above

**Comment by FMotalleb** [comment]
Hi, @IanManske 

Unfortunately, for more information, I should direct you to a thread in [Discord](https://discord.com/channels/601130461678272522/1173534968673214514) with @amtoine 

This is a complex issue with various elements:

1. First of all, the clip command should not perform two actions (`copy`, `notify`). Users are capable of using pipelines.
2. It is problematic that a simple command forces me to either manually turn off its optional feature or install a library.
3. There are indeed multiple issues with the functionalities of `xclip` and `wl-clipboard`. They behave differently on each operating system.
> For instance, in my case, which involves `Debian 12.2` + `gnome 43`, `wl-clipboard` does not work, but `xclip` does. However, if I use `xclip` in a pipeline, it disrupts the pipeline (hangs until I change the clipboard), which prevents me from using the notify functionality in the first place.

Lastly, why would we define a command in the **`std`** library that relies on external optional components? This is a point that may need further discussion.

and at the end I created a [plugin for clipboard](https://github.com/FMotalleb/nu_plugin_clipboard) instead of using clip because of the issues listed above

**Comment by FMotalleb** [comment]
If it were my decision to make, I’d prefer to write the `clip` command in pure Rust at `crates/nu-command`.

**Comment by IanManske** [comment]
> Lastly, why would we define a command in the std library that relies on external optional components? This is a point that may need further discussion.
> >EDIT: After checking the std library documents, I must assert that the clip command does not belong there, primarily due to the fact that neither of its functionalities are written in pure-nushell, and they are not basic operating system components.

I see, that makes sense. You're right, the `clip` functionality would be better suited as a plugin or separate script, and not part of `std`. Thanks for explaining! (Also, your plugin looks cool!)

**Comment by Lightfire228** [comment]
There is a rust crate specifically for handling clipboard actions in wayland

https://github.com/YaLTeR/wl-clipboard-rs
