### ISSUE TITLE
How to "unfold" the data structure view when calling nu with `nu -c`?

### ISSUE THREAD

**Issue by ohemelaar** [nushell/nushell#11050]
### Question

Hello,

Not yet ready to make a move to use `nu` as my everyday shell, I see a lot of potential in its features that I wish to use from my current shell. One of them is the rendering of the data structure that's done when using `open` or `from json` for example. I don't know if there is a specific term that needs to be used to describe this feature.

I thought I might be able to benefit from this outside of nu by simply piping my data to `nu -c "tee | from json"`, but it doesn't have the same behaviour. When piping to nu it keeps some parts of the structure "folded".

For example, in bash:
```prompt
$ echo '{1: {1: 2}}' | nu -c 'tee | from json'
╭───┬──────────────────╮
│ 1 │ {record 1 field} │
╰───┴──────────────────╯
```
while in nu:
```prompt
> echo '{1: {1:2}}' | from json
╭───┬───────────╮
│   │ ╭───┬───╮ │
│ 1 │ │ 1 │ 2 │ │
│   │ ╰───┴───╯ │
╰───┴───────────╯
```

I tried to find something in the docs about this but I struggle as I don't know what term is used talk about that table rendering feature. I didn't find something specific about this in the flags shown by `nu -h` either.

Is there a way to configure `nu` to show the full data structure when called with `nu -c`?

Thanks!

**Comment by fdncred** [comment]
This should work
```nushell
echo '{1: {1: 2}}' | nu -c 'tee | from json | table --expand'
```

**Comment by ohemelaar** [comment]
Amazing, thank you very much @fdncred!
