### ISSUE TITLE
Fail to start executable referenced via `~`

### ISSUE THREAD

**Issue by senden9** [nushell/nushell#1105]
**Describe the bug**
Can not start binaries that I locate via tilde (`~`) 

**To Reproduce**
1. Place a executable file somewhere under your home directory
2. Try to start it via a path that starts with `~/`
3. See how nu says `Command not found`
4. Start it via absolute path and see how it works.

**Expected behavior**
The executable file should be started.

**Example Session**
```
nushell on  master [?] is 📦 v0.7.1 via 🦀 v1.40.0 
❯ whoami
stefano

nushell on  master [?] is 📦 v0.7.1 via 🦀 v1.40.0 
❯ ls ~/bin | where created < 10h
━━━━━━━━━━━━━━━━━━━━━━━━━┯━━━━━━┯━━━━━━━┯━━━━━━━━━━━━━┯━━━━━━━━━━━━━┯━━━━━━━━━━━━━
 name                    │ type │ size  │ created     │ accessed    │ modified 
─────────────────────────┼──────┼───────┼─────────────┼─────────────┼─────────────
 /home/stefano/bin/clion │ File │ 176 B │ 6 hours ago │ 6 hours ago │ 6 hours ago 
━━━━━━━━━━━━━━━━━━━━━━━━━┷━━━━━━┷━━━━━━━┷━━━━━━━━━━━━━┷━━━━━━━━━━━━━┷━━━━━━━━━━━━━

nushell on  master [?] is 📦 v0.7.1 via 🦀 v1.40.0 
❯ ~/bin/clion
error: Command not found
- shell:1:11
1 | ~/bin/clion
  | ^^^^^^^^^^^ command not found

nushell on  master [?] is 📦 v0.7.1 via 🦀 v1.40.0 
❯ /home/stefano/bin/clion
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

nushell on  master [?] is 📦 v0.7.1 via 🦀 v1.40.0 
❯ nu --version
nushell 0.7.1

nushell on  master [?] is 📦 v0.7.1 via 🦀 v1.40.0 
❯ uname -a
Linux STEFANO-PC 5.4.5-arch1-1 #1 SMP PREEMPT Wed, 18 Dec 2019 19:48:51 +0000 x86_64 GNU/Linux
```

**Configuration (please complete the following information):**
 - OS: Linux (arch linux)
 - Version: 0.7.1
 - Optional features (if any):  `stable`

**Comment by sandorex** [comment]
I can confirm that this works on master using windows (stable features)

**Comment by nightscape** [comment]
I have the same problem on Windows.

**Comment by thegedge** [comment]
We have some things landing this week that should fix this issue. If not, I have another fix prepped and ready to go 🙂

**Comment by jonathandturner** [comment]
This should be working in master. I'll go ahead and close, but if you try master and still see the issue, please re-open.
