### ISSUE TITLE
Expose `argv[0]`

### ISSUE THREAD

**Issue by p00f** [nushell/nushell#11059]
### Related problem

I would like `argv[0]` ie the name the script was invoked with, exposed in scripts

### Describe the solution you'd like

`argv[0]` is available as the `path` argument here:

https://github.com/nushell/nushell/blob/77a1c3c7b2f3a110d48bcb792968e6b0d85d4bb7/crates/nu-cli/src/eval_file.rs#L19

The information is lost here:

https://github.com/nushell/nushell/blob/77a1c3c7b2f3a110d48bcb792968e6b0d85d4bb7/crates/nu-cli/src/eval_file.rs#L34-L44

https://github.com/nushell/nushell/blob/77a1c3c7b2f3a110d48bcb792968e6b0d85d4bb7/crates/nu-cli/src/eval_file.rs#L97-L100

### Describe alternatives you've considered

`$"./($env.CURRENT_FILE | path relative-to (pwd))"`, but this is not necessarily the same thing as `argv[0]` (an obvious exception is windows)

**Comment by p00f** [comment]
This should also be used when reporting usage errors:
```txt
> ./tools/build.nu
Error: nu::parser::missing_positional

  × Missing required positional argument.
   ╭─[<commandline>:1:1]
 1 │ main
   ·     ▲
   ·     ╰── missing src
   ╰────
  help: Usage: main <src> <dest> . Use `--help` for more information.
```

In the last line, instead of `main`, `./tools/build.nu` should be used.

**Comment by kubouch** [comment]
You can use `$env.CURRENT_FILE` (and `path basename` if you want just the filename). That should be sufficient.
