### ISSUE TITLE
aliases with `do` duplicates the help of `do`

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#11067]
### Describe the bug

as per title.

i could not reproduce with other commands.

### How to reproduce

1. run `nu -n` to have a fresh shell
2. run `help do` and see the examples at the bottom as expected
3. run `alias foo = do {}`
4. run `help do` again and see the the examples are not the last thing to be printed anymore => the usage + flags + parameters + i/o types are duplicated

### Expected behavior

i expected the `help do` to stay the same regardless of whether there is an alias set involving `do` or not.

### Screenshots

<details>
<summary>before setting the alias: normal help</summary>

```
Run a closure, providing it with the pipeline input.

Usage:
  > do {flags} <closure> ...(rest)

Flags:
  -h, --help - Display the help message for this command
  -i, --ignore-errors - ignore errors as the closure runs
  -s, --ignore-shell-errors - ignore shell errors as the closure runs
  -p, --ignore-program-errors - ignore external program errors as the closure runs
  -c, --capture-errors - catch errors as the closure runs, and return them
  --env - keep the environment defined inside the command

Parameters:
  closure <one_of(closure(), any)>: the closure to run
  ...rest <any>: the parameter(s) for the closure

Input/output types:
  ╭───┬───────┬────────╮
  │ # │ input │ output │
  ├───┼───────┼────────┤
  │ 0 │ any   │ any    │
  ╰───┴───────┴────────╯

Examples:
  Run the closure
  > do { echo hello }
  hello

  Run a stored first-class closure
  > let text = "I am enclosed"; let hello = {|| echo $text}; do $hello
  I am enclosed

  Run the closure and ignore both shell and external program errors
  > do --ignore-errors { thisisnotarealcommand }

  Run the closure and ignore shell errors
  > do --ignore-shell-errors { thisisnotarealcommand }

  Run the closure and ignore external program errors
  > do --ignore-program-errors { nu --commands 'exit 1' }; echo "I'll still run"

  Abort the pipeline if a program returns a non-zero exit code
  > do --capture-errors { nu --commands 'exit 1' } | myscarycommand

  Run the closure, with a positional parameter
  > do {|x| 100 + $x } 77
  177

  Run the closure, with input
  > 77 | do {|x| 100 + $in }

  Run the closure and keep changes to the environment
  > do --env { $env.foo = 'bar' }; $env.foo
  bar
```
</details>

<details>
<summary>after setting the alias: duplicated help</summary>

```
Run a closure, providing it with the pipeline input.

Usage:
  > do {flags} <closure> ...(rest)

Flags:
  -h, --help - Display the help message for this command
  -i, --ignore-errors - ignore errors as the closure runs
  -s, --ignore-shell-errors - ignore shell errors as the closure runs
  -p, --ignore-program-errors - ignore external program errors as the closure runs
  -c, --capture-errors - catch errors as the closure runs, and return them
  --env - keep the environment defined inside the command

Parameters:
  closure <one_of(closure(), any)>: the closure to run
  ...rest <any>: the parameter(s) for the closure

Input/output types:
  ╭───┬───────┬────────╮
  │ # │ input │ output │
  ├───┼───────┼────────┤
  │ 0 │ any   │ any    │
  ╰───┴───────┴────────╯

Examples:
  Run the closure
  > do { echo hello }
  hello

  Run a stored first-class closure
  > let text = "I am enclosed"; let hello = {|| echo $text}; do $hello
  I am enclosed

  Run the closure and ignore both shell and external program errors
  > do --ignore-errors { thisisnotarealcommand }

  Run the closure and ignore shell errors
  > do --ignore-shell-errors { thisisnotarealcommand }

  Run the closure and ignore external program errors
  > do --ignore-program-errors { nu --commands 'exit 1' }; echo "I'll still run"

  Abort the pipeline if a program returns a non-zero exit code
  > do --capture-errors { nu --commands 'exit 1' } | myscarycommand

  Run the closure, with a positional parameter
  > do {|x| 100 + $x } 77
  177

  Run the closure, with input
  > 77 | do {|x| 100 + $in }

  Run the closure and keep changes to the environment
  > do --env { $env.foo = 'bar' }; $env.foo
  bar

======================

Usage:
  > do {flags} <closure> ...(rest)

Flags:
  -h, --help - Display the help message for this command
  -i, --ignore-errors - ignore errors as the closure runs
  -s, --ignore-shell-errors - ignore shell errors as the closure runs
  -p, --ignore-program-errors - ignore external program errors as the closure runs
  -c, --capture-errors - catch errors as the closure runs, and return them
  --env - keep the environment defined inside the command

Parameters:
  closure <one_of(closure(), any)>: the closure to run
  ...rest <any>: the parameter(s) for the closure

Input/output types:
  ╭───┬───────┬────────╮
  │ # │ input │ output │
  ├───┼───────┼────────┤
  │ 0 │ any   │ any    │
  ╰───┴───────┴────────╯
```
</details>

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.87.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26) |
| build_time         | 2023-11-15 18:45:43 +01:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  | jwalk, nu_plugin_explore            |

**Comment by 132ikl** [comment]
I can't reproduce this on main (specifically, 3b0ba92)

**Comment by amtoine** [comment]
yeah i can't repro that either on the following version
| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.100.0                             |
| major              | 0                                   |
| minor              | 100                                 |
| patch              | 0                                   |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06) |
| rust_channel       | 1.80.1-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16) |
| build_time         | 2024-11-20 19:27:39 +01:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash              |
| installed_plugins  | clipboard 0.100.0, explore 0.99.1   |

i will close this then, thanks @132ikl :yum:
