### ISSUE TITLE
Deprecate `collect`?

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#11073]
### Related problem

In #6894, @rgwood mentions that:

> I suspect we don't need both `collect` and `do`, at least in their current forms. I brought that up on Discord and JT agrees.

The reason for this is that `collect` appears to be redundant with existing `do` functionality.  In both cases, the pipeline input is passed to the closure *as a whole*.  E.g., rewriting (and extending) the `collect` help example:

```Nushell
> [1 2 3] | collect { |x| $x.1 }
2
> [1 2 3] | do { $in.1 }
2
> [1 2 3] | collect {|x| $x | length }
3
> [1 2 3] | do { $in | length }
3
```

As you can see, in most cases it's also slightly more concise and readable.  The readability could be debated, but assumes that someone is already familiar with the mechanics of both closures and pipeline `$in` usage.  I feel this is a valid requirement - Some people might be more familiar with one over the other, but that's not a reason to keep a redundant command.  That road leads to Perl ([TMTOWTDI](https://en.wikipedia.org/wiki/wikt:TMTOWTDI)) 😉.

There are a few situations where you want or need to rename `$in`.  These started out as a possible counterpoint to removing `collect`:

* For clarity
* When you need to use the pipeline input in a closure-within-the-closure

However, as I started to write these examples, I realized that the `do` solution can still be just as clean/readable as `collect`:

```Nushell
# `collect` is "naturally" readable as-is
> [ 100 100 90 40 80 90 100 ] | collect {
  |homeworkScores|
  {
    avg: ($homeworkScores | math avg),
    max: ($homeworkScores | math max),
    min: ($homeworkScores | math min)
  }
}
╭─────┬───────╮
│ avg │ 85.71 │
│ max │ 100   │
│ min │ 40    │
╰─────┴───────╯

# `do`/`$in` can be less readable by default
> [ 100 100 90 40 80 90 100 ] | do {
  {
    avg: ($in | math avg),
    max: ($in | math max),
    min: ($in | math min)
  }
}
# Same result

# But can easily be made just as readable with good conventions:
> [ 100 100 90 40 80 90 100 ] | do {
  let homeworkScores = $in
  {
    avg: ($homeworkScores | math avg),
    max: ($homeworkScores | math max),
    min: ($homeworkScores | math min)
  }
}
```

### Describe the solution you'd like

Unless there's something I'm missing, I'd propose deprecating, then removing, `collect`.  There's always the chance there's going to be a more apt use of that command name in the future.

**Comment by sholderbach** [comment]
I don't think promoting a side effect in `do`'s behavior that we might want to get rid off in the future as the replacement of the feature that is written on `collect`s name, as @fdncred said, is a future-proof choice.

We may want to reconsider if `collect` should have any closure associated to it simplifying it.

**Comment by fdncred** [comment]
> We may want to reconsider if collect should have any closure associated to it simplifying it.

100% of the time when I use collect now it's `| collect {$in}`. So, that may be a good suggestion, or at least make it a `OneOf(closure, nothing)`.

**Comment by NotTheDr01ds** [comment]
> The main reason I use `collect` is for when slow tables are created, and I want all the output in one table.

As I said, I could be misunderstanding something, so perhaps I missed a use-case.

> "Slow" tables are tables that are rendering at native speed, but the source is slow and what happens is you end up having many 1 or 2 row tables. Using collect allows you to join these rows into one table.

It *sounds* like you are talking about something like (simplified/contrived example, but in the real-world it could be something like multiple calls to a REST API as well):

```nushell
> ls | each {|x| sleep 1sec ; { name: $x.name }}
╭───┬────────────╮
│ # │    name    │
├───┼────────────┤
│ 0 │ 3dprinting │
╰───┴────────────╯
╭───┬─────────╮
│ # │  name   │
├───┼─────────┤
│ 1 │ English │
╰───┴─────────╯
╭───┬──────────╮
│ # │   name   │
├───┼──────────┤
│ 2 │ academia │
╰───┴──────────╯
╭───┬──────╮
│ # │ name │
├───┼──────┤
│ 3 │ ai   │
╰───┴──────╯
╭───┬─────────╮
│ # │  name   │
├───┼─────────┤
│ 4 │ android │
╰───┴─────────╯
```

But I'm assuming that's *not* the use-case you're talking about, because you definitely don't need `collect` to solve that.  I mean, it *does* fix the problem:

```Nushell
> ls | first 5 | each {|x| sleep 1sec ; { name: $x.name }} | collect {$in}
╭───┬────────────╮
│ # │    name    │
├───┼────────────┤
│ 0 │ 3dprinting │
│ 1 │ English    │
│ 2 │ academia   │
│ 3 │ ai         │
│ 4 │ android    │
╰───┴────────────╯
```

But so, it *seems*, does pretty much *any* use of `$in` with the pipeline:

```Nushell
> ls | first 5 | each {|x| sleep 1sec ; { name: $x.name }} | $in
# Same result as `collect`, right?

# Or a (just as) pathological use of `do`
> ls | first 5 | each {|x| sleep 1sec ; { name: $x.name }} | do {$in} 
# Same result, right?
```

Again, I'm assuming that I'm still missing your real use-case for `collect` here, but I'd like to understand it for my own edification.

**Comment by sholderbach** [comment]
Again just because `$in` does that for technical reasons doesn't mean we want to commit to the fact that it is currently not streaming.

**Comment by NotTheDr01ds** [comment]
> I don't think promoting a side effect in `do`'s behavior that we might want to get rid off in the future ...

Can you help me understand that part?  It seems to me that use of the `$in` pipeline in a closure (with `do` or any other use) is pretty useful/important.  Why do you consider it a side effect?

`do {closure}` seems to me to be just the "anonymous" form of `def x {block}`, and having the ability to handle pipeline input in either seems pretty important.

**Comment by fdncred** [comment]
@NotTheDr01ds ya, https://github.com/nushell/nushell/issues/11073#issuecomment-1815136552 is a good (contrived) example of what I was calling "slow" tables.

**Comment by sholderbach** [comment]
Yes `$in` as a variable means we currently convert the `PipelineData` that is coming from the previous pipeline step to a `Value` which is the residence format for all other variables.
Thus we loose any streaming that would be provided by `PipelineData::ListStream`.

Directly taking the input in a closure should be faster/use less memory:

Instead of
```
> [1 2 3] | do { $in | length }
3
```
we currently would have to recommend
```
> [1 2 3] | do { length }
3
```

(haven't checked if `do` internally may also do something with the pipeline input)

**Comment by NotTheDr01ds** [comment]
@sholderbach Thanks - I *think* I'm getting closer to grokking it.  Still not there yet - I feel I'm kind of addicted to current behavior of `$in` as a `Value`.   I mean, I came across the `collect` command in the Help and said to myself, *"Why would I need that?  I've been getting along fine with `$in` for months"* 😉.

**Comment by NotTheDr01ds** [comment]
I'm going to close this for now.  To summarize what I think I now understand the situation to be:

* `collect` and a normal pipeline `$in` both *currently* seem to share the same behavior (counter-proofs welcome)
* As such, the only *current* value that `collect` has is future-proofing for a (hopefully) planned future when `$in` can process streaming data.

That's still valuable, and if that's the case, then I agree that `collect` probably shouldn't be deprecated *for now*.  However, when/if streaming is implemented, also consider whether you might want to use a different magic variable for streaming (e.g., `$s_in` could handle streaming, and `$in` could be the collected, non-streaming result of the previous command on the pipeline).

Either way, I think, works.  And you're right - There's no sense in deprecating `collect` in the present if you think you're going to need it in the future.

**Comment by NotTheDr01ds** [comment]
I'm going to close this for now.  To summarize what I think I now understand the situation to be:

* `collect` and a normal pipeline `$in` both *currently* seem to share the same behavior (counter-proofs welcome)
* As such, the only *current* value that `collect` has is future-proofing for a (hopefully) planned future when `$in` can process streaming data.

That's still valuable, and if that's the case, then I agree that `collect` probably shouldn't be deprecated *for now*.  However, when/if streaming is implemented, also consider whether you might want to use a different magic variable for streaming (e.g., `$s_in` could handle streaming, and `$in` could be the collected, non-streaming result of the previous command on the pipeline).

Either way, I think, works.  And you're right - There's no sense in deprecating `collect` in the present if you think you're going to need it in the future.
