### ISSUE TITLE
Should I expect my configuration to break when updating?

### ISSUE THREAD

**Issue by rafael-pinheiro** [nushell/nushell#11078]
### Question

I just updated nushell on my macbook and suddenly my shell was no longer configured how I had set it.
I tried to source my configuration by hand and I found out that "let-env" is no longer available.
Part of what broke seems to not even be configuration that I wrote, but default nushell config, such as:
```
let-env config = {
```

I double checked the version and it was a minor change, meaning it should not break backward compatibility.
Doesn't nu uses semver? Should I not expect that things continue to work after updating?

**Comment by amtoine** [comment]
for now, and probably until Nushell reaches 1.0, we do not use proper semver.
"*minor versions*" just follow a 4-week release cycle and will contain breaking changes :open_mouth: 

you can see the ones from the most recent release yesterday [in the release note of `0.87.0`](https://www.nushell.sh/blog/2023-11-14-nushell_0_87_0.html#breaking-changes-toc) :yum:
