### ISSUE TITLE
Current master does not build

### ISSUE THREAD

**Issue by AMNeumann** [nushell/nushell#1107]
**Description**
I cloned the repo at commit f9da7f7d58da3ead2aaba6a519c554d1b199c158, installed the dependencies and get an error immediately after starting the build:

```
$ cargo build 
error: failed to parse lock file at: /home/arne/devel/nushell/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
```
I am completely new to rust, maybe I am just too stupid to get this working, but I'd really like to try nu. I'd even be ready to extend the installation instructions accordingly.

**Configuration (please complete the following information):**
```
$ uname -a
Linux OPFER 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ cargo --version
cargo 1.37.0
```

**Comment by jonathandturner** [comment]
@AMNeumann - one possible problem may be that it looks like you're building with a version of rustc/cargo that's too old to build Nu. Make sure that you have at least version 1.39

**Comment by jonathandturner** [comment]
Going ahead and closing, but please re-open if you are still unable to build with a newer Rust version
