### ISSUE TITLE
`++=` operator doesn't work for single elements

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11087]
### Describe the bug

While `++` works for non-list right value (`[1] ++ 2 == [1 2]`), `++=` does not.

### How to reproduce

```Nushell
~> mut list = []
~> $list ++= 1
Error: nu::parser::type_mismatch

  × Type mismatch during operation.
   ╭─[entry #23:1:1]
 1 │ $list ++= 1
   ·           ┬
   ·           ╰── expected list<any>, found int
   ╰────
```

### Expected behavior

Appending the element.

### Configuration

| key                | value                                                                                                               |
| ------------------ | ------------------------------------------------------------------------------------------------------------------- |
| version            | 0.86.0                                                                                                              |
| branch             |                                                                                                                     |
| commit_hash        |                                                                                                                     |
| build_os           | linux-x86_64                                                                                                        |
| build_target       | x86_64-alpine-linux-musl                                                                                            |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0)                                                        |
| cargo_version      | cargo 1.72.1                                                                                                        |
| build_time         | 2023-10-22 21:58:37 +00:00                                                                                          |
| build_rust_channel | release                                                                                                             |
| allocator          | mimalloc                                                                                                            |
| features           | default, sqlite, trash, which, zip                                                                                  |
| installed_plugins  | custom-value generate, custom-value generate2, custom-value update, gstat, nu-example-1, nu-example-2, nu-example-3 |

**Comment by fdncred** [comment]
What is `++=` supposed to do? It's not in our list of `help operators`.

**Comment by KAAtheWiseGit** [comment]
@fdncred it is in my version of help:

```│  2 │ Assignment │ ++=         │ AppendAssign       │ Appends a list or a value to a variable.               │         10 │```

**Comment by fdncred** [comment]
oops, i missed it because i was expecting it to be next to ++, thanks.
