### ISSUE TITLE
Nested insert doesn't work

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11089]
### Describe the bug

An `insert` with a nested cell-path only creates the first element without an error.

### How to reproduce

```Nushell
~> {} | insert z.z 0
╭───┬───╮
│ z │ 0 │
╰───┴───╯
~> {} | insert $.z.z 0
╭───┬───╮
│ z │ 0 │
╰───┴───╯
```

### Expected behavior

I'd expect it to create `{z: {z: 0}}`.

### Configuration

| key                | value                                                                                                               |
| ------------------ | ------------------------------------------------------------------------------------------------------------------- |
| version            | 0.86.0                                                                                                              |
| branch             |                                                                                                                     |
| commit_hash        |                                                                                                                     |
| build_os           | linux-x86_64                                                                                                        |
| build_target       | x86_64-alpine-linux-musl                                                                                            |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0)                                                        |
| cargo_version      | cargo 1.72.1                                                                                                        |
| build_time         | 2023-10-22 21:58:37 +00:00                                                                                          |
| build_rust_channel | release                                                                                                             |
| allocator          | mimalloc                                                                                                            |
| features           | default, sqlite, trash, which, zip                                                                                  |
| installed_plugins  | custom-value generate, custom-value generate2, custom-value update, gstat, nu-example-1, nu-example-2, nu-example-3 |

**Comment by KAAtheWiseGit** [comment]
Oh, and this doesn't work either:

```Nushell
~> {z: 0} | insert z.z 0
Error: nu::shell::unsupported_input

  × Unsupported input
   ╭─[entry #91:1:1]
 1 │ {z: 0} | insert z.z 0
   ·          ───┬──   ┬
   ·             │     ╰── input type: input type: Int
   ·             ╰── table or record
```

**Comment by IanManske** [comment]
Coincidentally enough, I recently opened a PR (#11066) which fixes this.

**Comment by fdncred** [comment]
Not sure this is supposed to work after #11066 but it doesn't.
```nushell
{z: 0} | insert z.z 0
```

**Comment by IanManske** [comment]
It's not supposed to, since `insert` fails if it has to overwrite any values. The error message here could maybe use some work. Weirdly enough, `{z: 0} | upsert z.z 0` doesn't work either.
