### ISSUE TITLE
Aliases should have completions using the expansion of the aliases

### ISSUE THREAD

**Issue by crides** [nushell/nushell#11088]
### Related problem

For example, with an alias `gsw = git switch`, after `gsw ` is typed on the command line and pressing tab, the completions for `git switch` should be shown

### Describe the solution you'd like

When completing a command, if that command is an alias, Nu should expand the alias first, then start the completion

### Describe alternatives you've considered

It may be possible (~I haven't tried~ nope) to just define completions for the aliases, and then use the results from the original, but then it requires the user to do extra work

**Comment by sholderbach** [comment]
Still need to check the related issues, but...
...historically the naive implementation of that was an absolute bugfest as the indexing into the orginal and expanded source code broke a bunch of operations during completion.

**Comment by crides** [comment]
Interesting. Could you point me to a rough commit/version with those problems?

**Comment by crides** [comment]
The original intention of this issue was that my git aliases' completions were not working. However, after looking at the code, I found that the aliased command's flags and completions do get forwarded to the alias itself. The real problem is that, (completions provided by) `extern`s actually create a new definition, different from the actual/original external command, thus the alias must be after the definition of the completions.

**Comment by claymorwan** [comment]
yo im running into the same issue, i'm trying to use both the git aliases and completion from the nu_script repository but i can't get it to work. I tried sourcing the completion before the aliases like so:
```nu
source /path/to/repo/custom-completions/git/git-completions.nu
source /path/to/repo/aliases/git/git-aliases.nu
```
but the completion still doesn't work when i use the aliases
