### ISSUE TITLE
`def --wrapped` is not a suitable replacement for `extern-wrapped`

### ISSUE THREAD

**Issue by cjbayliss** [nushell/nushell#11096]
### Describe the bug

in Nushell 0.87 `extern-wrapped` is marked as deprecated in favour of `def --wrapped`, however `def --wrapped` is not a suitable replacement for `extern-wrapped` because it catches the `-h` and `--help` flags.

### How to reproduce

1. use `def --wrapped` instead of `extern-wrapped`

### Expected behavior

`def --wrapped` should match the behaviour of `extern-wrapped`

### Configuration

```
> version | transpose key value | to md --pretty
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.87.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03) (built from a source tarball) |
| cargo_version      | cargo 1.73.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |
```

### Additional context

```nu
> extern-wrapped foo [...rest] { echo $rest }
> foo -h
╭───┬────╮
│ 0 │ -h │
╰───┴────╯

> def --wrapped foo [...rest] { echo $rest }
> foo -h
Usage:
  > foo ...(rest) 

Flags:
  -h, --help - Display the help message for this command

Parameters:
  ...rest <any>: 

Input/output types:
  ╭───┬───────┬────────╮
  │ # │ input │ output │
  ├───┼───────┼────────┤
  │ 0 │ any   │ any    │
  ╰───┴───────┴────────╯


> 
```

**Comment by WindSoilder** [comment]
Currently nushell defines `-h` for commands.
For your use case, you can quoted -h, so everything will work fine: `foo "-h"`

**Comment by jewlexx** [comment]
Is there any workaround for this? This issue makes `def --wrapped` unusable for certain use cases, and when `extern-wrapped` gets deprecated, afaik there won't be another option.

**Comment by amtoine** [comment]
@jewlexx 
for now, the fix appears to quote `-h`, e.g. `foo "-h"` instead of `foo -h` in the example above.

this is not optimal, we could remove that `-h` default behaviour for `--wrapped` commands (@kubouch you'll probably know :innocent:)

**Comment by jewlexx** [comment]
@amtoine
Realistically, requiring users to quote `-h` isn't intuitive and most likely wouldn't think of it.

It would be good if this behaviour was disabled by default when using `--wrapped` because, while there is a place for it, I think that for most use cases of `--wrapped`, it would make more sense to not intercept the help flag.

**Comment by p00f** [comment]
also, `extern-wrapped` makes tab completion fall through to the command being wrapped:
1) ```
def --wrapped fzf [...argv] {
    if (darkman get) == "dark" {
        ^fzf --color dark $argv
    } else {
        ^fzf --color light $argv
    }
}
```
2) `fzf --`
3) press tab: it only completes `--help` defined by nushell
`~: fzf --help `

Now try this with extern-wrapped: it works
```
~| fzf --
--algo             Fuzzy matching algorithm
--ansi             Enable processing of ANSI color codes
--bind             Custom key bindings
--border           Draw border around the finder
--color            Base scheme
--cycle            Enable cyclic scroll
--delimiter        Field delimiter regex
--exact            Enable Exact-match
--exit-0           Exit immediately when there's no match
--expect           Comma-separated list of keys to complete fzf
--extended         Extended-search mode
--filepath-word    Make word-wise movements respect path separators
--filter           Filter mode
```

**Comment by kubouch** [comment]
We can make `def --wrapped` not define `-h` flag by default, same as `extern` or `extern-wrapped`. It should be an easy change because this behavior is already present in the `extern*` commands.
