### ISSUE TITLE
shell_andand produces an *incorrect* error instead of the expected behavior

### ISSUE THREAD

**Issue by thenorili** [nushell/nushell#11095]
### Describe the bug

nushell knows exactly what people mean when they type the && operator, demonstrated by the fact that they have a bespoke error informing you of the syntax they'd prefer you to use.

```
/mnt/c/Users/nori/dev/eyre: git fetch upstream && git checkout upstream/master -b dev
Error: nu::parser::shell_andand

  × The '&&' operator is not supported in Nushell
   ╭─[entry #3:1:1]
 1 │ git fetch upstream && git checkout upstream/master -b dev
   ·                    ─┬
   ·                     ╰── instead of '&&', use ';' or 'and'
   ╰────
  help: use ';' instead of the shell '&&', or 'and' instead of the boolean '&&'
  ```

'and' here is just unambiguously incorrect in the context of shell scripting. i assume it's the boolean and operator?

```
/mnt/c/Users/nori/dev/eyre: echo "nori" and echo "nori"                     11/18/23 16:33:09 PM
╭───┬──────╮
│ 0 │ nori │
│ 1 │ and  │
│ 2 │ echo │
│ 3 │ nori │
╰───┴──────╯
```

Why not allow it as an alias of `;`? That's what people have muscle memory for in scripting languages. I don't understand why you stub someone's toe and give them two solutions, one of them completely incorrect.

### How to reproduce

1. `commmand1 && command2`

### Expected behavior

run command 1; then run command 2

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.85.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.72.1 (103a7ff2e 2023-08-15) |
| build_time         | 2023-09-27 00:00:16 -07:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  |                                     |

**Comment by kubouch** [comment]
The error suggests exactly what the problem with `&&` is: It can be though of as a boolean operator and the shell `&&`. We tried adding `&&` before, but it didn't pair well with the rest of the language, so we decided to remove it. Currently, there are no plans to implement `&&` in Nushell.

If you find the error unclear, feel free to submit an improvement.

**Comment by thenorili** [comment]
suggested improvement: alias `&& ` to `; ` and leave an error if someone tries to use it as logical and.

I don't understand what you mean by "it didn't pair well". nushell is an interactive shell. People who have used interactive shells understand && means to execute another command in serial.

**Comment by fdncred** [comment]
I'm not sure this is super helpful since not much was said about it but here are the PRs.
added https://github.com/nushell/nushell/pull/7448
reverted https://github.com/nushell/nushell/pull/7452

**Comment by thenorili** [comment]
ah. so it was reverted after four commits before letting users try it on the assumption that it'd be too surprising for them.
