### ISSUE TITLE
How do I change the time format?

### ISSUE THREAD

**Issue by 107295472** [nushell/nushell#11106]
### Question

Need this format 2023/11/20/ 20:00:03   No am, pm

**Comment by WindSoilder** [comment]
You can config from `datetime_format` in your config file:
```nushell
$env.config = {
  datetime_format: {
      normal: "%Y/%m/%d %H:%M:%S"
  }
}
```

**Comment by 107295472** [comment]
def create_right_prompt [] {
    # create a right prompt in magenta with green separators and am/pm underlined
    let time_segment = ([
        (ansi reset)
        (ansi magenta)
        (date now | format date '%Y/%m/%d %r')
    ] | str join | str replace --regex --all "([/:])" $"(ansi green)${1}(ansi magenta)" |
        str replace --regex --all "([AP]M)" $"(ansi magenta_underline)${1}")

    let last_exit_code = if ($env.LAST_EXIT_CODE != 0) {([
        (ansi rb)
        ($env.LAST_EXIT_CODE)
    ] | str join)
    } else { "" }

    ([$last_exit_code, (char space), $time_segment] | str join)
}

**Comment by amtoine** [comment]
```nushell
> date now | format date "%Y/%m/%d %T"
2023/11/20 18:56:31
```
will work :yum: 

you can have a look at `format date --list` to see the available formats and feel free to drop in our Discord to ask simple questions like this one :innocent:
