### ISSUE TITLE
`format` falls back to `format.com` on invalid parameters

### ISSUE THREAD

**Issue by ite-klass** [nushell/nushell#11107]
### Describe the bug

When using `format` unhandled parameters fall back to `C:\Windows\System32\format.com`.

### How to reproduce

1. Run `date now | format datetime`

### Expected behavior

An error is returned because `format` is a nu command and `datetime` an invalid parameter.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.87.0                                   |
| branch             |                                          |
| commit_hash        | 77a1c3c7b2f3a110d48bcb792968e6b0d85d4bb7 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)      |
| rust_channel       | 1.71.1-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)      |
| build_time         | 2023-11-14 21:01:56 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

### Additional context

Instead, it prints `Invalid drive specification.` - a result, presumably, from `format.com`.

Because `format.com` (`format /?`: "Formats a disk for use with Windows.") is a potentially destructive operation depending on user parameters, this seems unnecessarily dangerous moreso than only confusing or error-prone.

**Comment by fdncred** [comment]
Seems like you don't have the `extra` features installed. You need to build/install with `--features=extra` to get `format`. It's not falling back per-se, it's finding the command you're asking for, which is `format`, and since you don't have it installed, it looks in your path and finds the executable format.

**Comment by ite-klass** [comment]
`format date` works though

**Comment by amtoine** [comment]
i don't have the _extra_ features and i get a proper error on Linux.

**Comment by fdncred** [comment]
@ite-klass My mistake. You're right, we have to get the command name right, lol. 
```nushell
date now | format date "%Y-%m-%d %H:%M:%S"
2023-11-20 13:09:47
```

**Comment by ixxie** [comment]
Would providing aliases for the nu commands (`fmt` or `nu-format` or both, for example) be a doable quick fix?

**Comment by sholderbach** [comment]
This issue should not persist as we have sunset the `--features extra` distinction. `format` is now the stub super command for all its subcommands and included by default.

If you want to access any preexisting commands on your system you can still run `^format`

**Comment by ixxie** [comment]
> This issue should not persist as we have sunset the `--features extra` distinction. `format` is now the stub super command for all its subcommands and included by default.
> 
> If you want to access any preexisting commands on your system you can still run `^format`

The issue persists on my system (Windows 10, Nushell 0.95.0):
```
> ls | format pattern '{name}: {size}'
Invalid parameter - pattern
```

**Comment by fdncred** [comment]
@ixxie I have no issues on Windows 10, Nushell 0.95.1.
```nushell
❯ ls | format pattern '{name}: {size}'
╭────┬─────────────────────────────╮
│  0 │ .cargo: 0 B                 │
│  1 │ .gitattributes: 113 B       │
│  2 │ .githooks: 0 B              │
│  3 │ .github: 4.1 KB             │
│  4 │ .gitignore: 712 B           │
│  5 │ .vscode: 0 B                │
│  6 │ CITATION.cff: 838 B         │
│  7 │ CODE_OF_CONDUCT.md: 3.5 KB  │
│  8 │ CONTRIBUTING.md: 11.5 KB    │
│  9 │ Cargo.lock: 182.7 KB        │
│ 10 │ Cargo.toml: 9.3 KB          │
│ 11 │ Cross.toml: 684 B           │
│ 12 │ LICENSE: 1.1 KB             │
│ 13 │ README.md: 12.5 KB          │
│ 14 │ assets: 0 B                 │
│ 15 │ benches: 0 B                │
│ 16 │ crates: 8.2 KB              │
│ 17 │ devdocs: 4.1 KB             │
│ 18 │ docker: 0 B                 │
│ 19 │ rust-toolchain.toml: 1.1 KB │
│ 20 │ scripts: 4.1 KB             │
│ 21 │ src: 4.1 KB                 │
│ 22 │ target: 0 B                 │
│ 23 │ tests: 4.1 KB               │
│ 24 │ toolkit.nu: 20.2 KB         │
│ 25 │ typos.toml: 527 B           │
│ 26 │ wix: 0 B                    │
╰────┴─────────────────────────────╯
```
Are you sure you're running 0.95.0?

**Comment by ixxie** [comment]
> Are you sure you're running 0.95.0?

Right, I just double checked and I am on an older version 🤔 I've had no luck reinstalling it seems. Thanks!

**Comment by fdncred** [comment]
> > Are you sure you're running 0.95.0?
> 
> Right, I just double checked and I am on an older version 🤔 I've had no luck reinstalling it seems. Thanks!

I think you need to be in an elevated window to use winget to reinstall. we changed the installer recently.

**Comment by ite-klass** [comment]
I'm pretty sure you don't have to be in an elevated window. But the installer changes broke the upgrade migration path. It installs to a different folder, and the previous install will remain and will remain usable as a second installation.

**Comment by fdncred** [comment]
> I'm pretty sure you don't have to be in an elevated window. 

There have been several people who have reported that they were required to use an elevated window with winget, simply because nushell wants to install to C:\Program Files. Once they elevate, it installs fine.

We may want to consider installing to AppData\Programs to prevent this need but I've had my fill of wix changes.

**Comment by ite-klass** [comment]
We're getting off-topic but the current installer, for a few versions now, *does* install to appdata local programs.

**Comment by fdncred** [comment]
Good. I'm the one who changed it. However, some people still need to be elevated. Not sure exactly what's going on. Maybe their UAC is set super high or they're using special options with winget. Not sure.
