### ISSUE TITLE
0.87.1 release or, not

### ISSUE THREAD

**Issue by 0323pin** [nushell/nushell#11111]
### Question

Is there a 0.87.1 release or not? The repology.org output looks weird, there's a tag but no release or release notes.

**Comment by amtoine** [comment]
there is a `0.xx.1` tag usually but no actual release!

this is the way used in Nushell to denote that the current version is the development version :yum: 
it's meant to mean the same as
- building from source
- the latest `main`
- one of the nighlty builds

hope that makes things clearer :innocent:

**Comment by 0323pin** [comment]
@amtoine thanks.

> there is a 0.xx.1 tag usually but no actual release!
this is the way used in Nushell to denote that the current version is the development version

I'm aware of this, I've been maintaining the NetBSD package for years.

The reason I've asked is [this](https://ports.macports.org/port/nushell/details/) which causes all other packages to be viewed as outdated.

I guess, MacPorts maintainer has made a mistake.

**Comment by fdncred** [comment]
yes, we need to do the release. there's a draft release right now, we just haven't finalized the notes yet.

**Comment by sholderbach** [comment]
Shipping the crates to crates.io at the moment. We had a hiccup in the state of our GitHub build workflow, so we wanted to validate that before going public but sadly the tag is already live at this point.

**Comment by sholderbach** [comment]
Resolved by https://github.com/nushell/nushell/releases/tag/0.87.1 @0323pin

**Comment by 0323pin** [comment]
> Resolved by https://github.com/nushell/nushell/releases/tag/0.87.1 @0323pin

Thanks! I'll update the NetBSD package early tomorrow morning CET
