### ISSUE TITLE
`mv` failed and doesn't stop command from running

### ISSUE THREAD

**Issue by WindSoilder** [nushell/nushell#11127]
### Describe the bug

I have the following custom command:
```nushell
def test [ ] {
    cd /tmp
    mv ("foo" | path join "bar")  ~
    print "cleaning"
}
```

And run `test` leads the following error:
```nushell
Error:   × Could not move "foo/bar" to "/Users/chenhongze/bar". Error Kind: Path "foo/bar" does not exist
   ╭─[entry #28:2:1]
 2 │     cd /tmp
 3 │     mv ("foo" | path join "bar")  ~
   ·        ────────────┬────────────
   ·                    ╰── could not move
 4 │     print "cleaning"
   ╰────

cleaning
```

I'm sure that relative file exists, think the error shouldn't happened.  And if it happened, the final `cleaning` shouldn't be printed.
But if we run `test` in `tmp` directory, it will success

### How to reproduce

1. mkdir /tmp/foo
2. touch /tmp/foo/bar
3. define the given `test` command
4. run `test` command in home directory.

### Expected behavior

I expect nu to copy file successfully.

### Configuration

| key                | value                                                                     |
| ------------------ | ------------------------------------------------------------------------- |
| version            | 0.87.2                                                                    |
| branch             | nightly                                                                   |
| commit_hash        | 8ad5d8bb6a2faba210d48cc3442317fd7512b2cb                                  |
| build_os           | macos-x86_64                                                              |
| build_target       | x86_64-apple-darwin                                                       |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13)                                       |
| rust_channel       | 1.72.1-x86_64-apple-darwin                                                |
| cargo_version      | cargo 1.72.1 (103a7ff2e 2023-08-15)                                       |
| build_time         | 2023-11-21 01:45:55 +00:00                                                |
| build_rust_channel | release                                                                   |
| allocator          | mimalloc                                                                  |
| features           | dataframe, default, extra, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  |                                                                           |

**Comment by WindSoilder** [comment]
Hope #10822 will solve this issue too

**Comment by hustcer** [comment]
The nightly build fails on Nu v0.87.1 due to this `mv` bug, more details could be found here: https://github.com/nushell/nightly/actions/runs/6964563750/job/18981885717
