### ISSUE TITLE
How to expand path?

### ISSUE THREAD

**Issue by SUPERCILEX** [nushell/nushell#11139]
### Question

In bash, you can do `echo *` to see how a path expression will be expanded. This is useful to see what rm/cp commands will receive for example.

How do you do this in nushell?

**Comment by amtoine** [comment]
with `path expand`?

**Comment by amtoine** [comment]
or maybe `ls * | get name`, which looks more close to what `echo *` does in Bash

**Comment by SUPERCILEX** [comment]
Can you re-open? I don't think this is solved and it's a pretty useful feature.

Path expand doesn't work:

```
~> * | path expand
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #1:1:1]
 1 │ * | path expand
   · ┬
   · ╰── did you mean 'math product'?
   ╰────
  help: No such file or directory (os error 2)
```

Echo doesn't do what you'd expect **(my vote is to make this work like in bash)**:

```
1 ~> echo *
*
```

The ls * version isn't adequate because it can't use multiple expansions.
```
ls Desktop/* *
Error: nu::parser::extra_positional

  × Extra positional argument.
   ╭─[entry #6:1:1]
 1 │ ls Desktop/* *
   ·              ┬
   ·              ╰── extra positional argument
   ╰────
  help: Usage: ls {flags} (pattern)
```

---

There should be a command that behaves _precisely_ how non-builtin command do with regards to path expansion.

**Comment by amtoine** [comment]
i can reopen, but i doubt making `echo *` work as in Bash will be a thing :open_mouth:

**Comment by SUPERCILEX** [comment]
Then perhaps path expand can take arguments?

**Comment by amtoine** [comment]
currently, `path` works only on paths, not *globbing*/*regex* patterns such as `*` or `**` :thinking: 
so
```nushell
"*" | path expand
```
gives me
```nushell
/home/amtoine/*
```

**Comment by amtoine** [comment]
@SUPERCILEX 
could the following be what you're looking for? :smirk: 
```nushell
# used as
# ```nushell
# bash-echo * documents/
# ```
def bash-echo [...paths: path] {
    $paths | each { ls $in } | flatten | get name
}
```

**Comment by fdncred** [comment]
@SUPERCILEX I don't get what you're wanting to do. This is what `echo *` does for me.
```bash
bash-3.2$ echo *
CODE_OF_CONDUCT.md CONTRIBUTING.md Cargo.lock Cargo.toml Cross.toml LICENSE README.md assets benches crates devdocs docker rust-toolchain.toml scripts src target tests toolkit.nu wix
```

**Comment by SUPERCILEX** [comment]
Sorry, I don't think I'm making my goal clear. I want to be able to see the results of a path expansion before I run a scary command. The formatting is irrelevant. `bash-echo` from above could be what I'm looking for, but I don't trust that `bath-echo ...` actually behaves the same as `scary-command ...`. @fdncred's ls examples don't actually do path expansion.

Here's an example of my use case in bash:
```bash
# Some very complicated path expression
$ echo x* *.md library/rustc-std-workspace-{alloc,core}/*.rs .github/**/*
x x.ps1 x.py CODE_OF_CONDUCT.md CONTRIBUTING.md README.md RELEASES.md library/rustc-std-workspace-alloc/lib.rs library/rustc-std-workspace-core/lib.rs .github/ISSUE_TEMPLATE/blank_issue.md .github/ISSUE_TEMPLATE/bug_report.md .github/ISSUE_TEMPLATE/config.yml .github/ISSUE_TEMPLATE/diagnostics.yaml .github/ISSUE_TEMPLATE/documentation.yaml .github/ISSUE_TEMPLATE/ice.md .github/ISSUE_TEMPLATE/ice.yaml .github/ISSUE_TEMPLATE/library_tracking_issue.md .github/ISSUE_TEMPLATE/regression.md .github/ISSUE_TEMPLATE/tracking_issue.md .github/workflows/ci.yml .github/workflows/dependencies.yml

# Yup, this all looks good
# Now I'm going to use the same paths but with a scary command
$ chmod +777 x* *.md library/rustc-std-workspace-{alloc,core}/*.rs .github/**/*
# The command could be scp, rmz, etc
```

**Comment by SUPERCILEX** [comment]
Maybe `ls` should just support multiple paths? Kinda weird that it doesn't honestly.

**Comment by SUPERCILEX** [comment]
And actually I just discovered the glob command: https://www.nushell.sh/commands/docs/glob.html

It's kind of what I'm looking for, but again it doesn't support multiple expressions so doesn't match the behavior of calling a random command.

**Comment by fdncred** [comment]
You could do this but not with bash syntax.
```nushell
[x* *.md library/rustc-std-workspace-{alloc,core}/*.rs .github/**/*] | each { glob $in } | flatten
```
This one would have to go through `str expand` first before `glob`
```nushell
'library/rustc-std-workspace-{alloc,core}/*.rs' | str expand
╭───┬────────────────────────────────────────╮
│ 0 │ library/rustc-std-workspace-alloc/*.rs │
│ 1 │ library/rustc-std-workspace-core/*.rs  │
╰───┴────────────────────────────────────────╯
```

**Comment by SUPERCILEX** [comment]
I guess that works, but it's a lot of effort when you just want to swap a scary command for a test command.

Come to think of it, I think the solution is to just use `/bin/echo`:
```bash
~/Desktop/rust> /bin/echo x* *.md library/rustc-std-workspace-{alloc,core}/*.rs .github/**/*
x x.ps1 x.py CODE_OF_CONDUCT.md CONTRIBUTING.md README.md RELEASES.md library/rustc-std-workspace-{alloc,core}/*.rs .github/ISSUE_TEMPLATE .github/ISSUE_TEMPLATE/blank_issue.md .github/ISSUE_TEMPLATE/bug_report.md .github/ISSUE_TEMPLATE/config.yml .github/ISSUE_TEMPLATE/diagnostics.yaml .github/ISSUE_TEMPLATE/documentation.yaml .github/ISSUE_TEMPLATE/ice.md .github/ISSUE_TEMPLATE/ice.yaml .github/ISSUE_TEMPLATE/library_tracking_issue.md .github/ISSUE_TEMPLATE/regression.md .github/ISSUE_TEMPLATE/tracking_issue.md .github/workflows .github/workflows/ci.yml .github/workflows/dependencies.yml
```

And then I can see that I need to do this:
```
/bin/echo x* *.md ("library/rustc-std-workspace-{alloc,core}/*.rs" | str expand) .github/**/*
x x.ps1 x.py CODE_OF_CONDUCT.md CONTRIBUTING.md README.md RELEASES.md library/rustc-std-workspace-alloc/lib.rs library/rustc-std-workspace-core/lib.rs .github/ISSUE_TEMPLATE .github/ISSUE_TEMPLATE/blank_issue.md .github/ISSUE_TEMPLATE/bug_report.md .github/ISSUE_TEMPLATE/config.yml .github/ISSUE_TEMPLATE/diagnostics.yaml .github/ISSUE_TEMPLATE/documentation.yaml .github/ISSUE_TEMPLATE/ice.md .github/ISSUE_TEMPLATE/ice.yaml .github/ISSUE_TEMPLATE/library_tracking_issue.md .github/ISSUE_TEMPLATE/regression.md .github/ISSUE_TEMPLATE/tracking_issue.md .github/workflows .github/workflows/ci.yml .github/workflows/dependencies.yml
```

Now I just swap `/bin/echo` for my real command.

**Comment by SUPERCILEX** [comment]
Why doesn't the built-in echo resolve paths again? That seems useful.

**Comment by fdncred** [comment]
Probably because no one has every complained about it.

**Comment by SUPERCILEX** [comment]
So I think making echo do multi-arg path resolution would be the request in this issue. Though using the system echo also works for me now that I remembered you can do that.

**Comment by amtoine** [comment]
my two cents: `echo` should stay the same, i'm not sure i understand why `echo` would expand _globs_ :open_mouth: 
and it's quite straightforward to write a custom Nushell command doing the same, right?

> **Note**
> i just found out that
> ```nushell
> ^echo *
> ```
> and
> ```nushell
> ls --all * | get name | str join " "
> ```
> will produce the same output :yum:

**Comment by fdncred** [comment]
I would support someone changing `glob` to take multiple inputs or a list of input globs and use the `any` functionality built into wax to match them.

**Comment by SUPERCILEX** [comment]
> I would support someone changing `glob` to take multiple inputs or a list of input globs and use the `any` functionality built into wax to match them.

Would that actually use the same code path as external command path expansion? That's a strict necessity for this issue's feature request.

---

I had no idea `^` escaped built in commands, so I'm going to close this as saying the answer is just use `^echo`.

**Comment by fdncred** [comment]
> Would that actually use the same code path as external command path expansion?

I'm not sure what that means. My comment isn't strictly related to this issue. I just think it would make `glob` better and it would expand paths since wax's glob syntax supports that.

**Comment by SUPERCILEX** [comment]
Yeah, that's a great idea but a separate request that should go in a different issue because it doesn't solve this problem. This issue is about ensuring path expansion occurs identically between a dummy command and a real one.
