### ISSUE TITLE
external command output type is not string?

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#11134]
### Describe the bug

it appears sometimes Nushell does not see the output of external commands as `string`... which is strange because they always return strings, apart from when you use things like `from json` on top of them :thinking: 

### How to reproduce

1. go to any Git repo
2. define
```nushell
def foo []: nothing -> string {
    let foo = ^git rev-list HEAD | lines | last
    print ($foo | describe)
    $foo
}
```
:point_right: it parses and runs fine
```
> foo
string
2ed2d875d80505d78423328c6b2a60522715fcdf
```
> **Note**
> in addition we see that the type is indeed a `string`
3. define
```nushell
def bar []: nothing -> string {
    ^git rev-list HEAD | lines | last
}
```
4. see the following error
```
Error: nu::parser::output_type_mismatch

  × Command output doesn't match string.
   ╭─[entry #15:1:1]
 1 │ def bar [ ]: nothing -> string {
 2 │     ^git rev-list HEAD | lines | last
   ·                                ───┬──
   ·                                   ╰── command doesn't output string
 3 │ }
   ╰────
```

### Expected behavior

i expected `bar` to parse and run just as `foo`, returning `2ed2d875d80505d78423328c6b2a60522715fcdf` in that case.

### Configuration

| key                | value                                                     |
| ------------------ | --------------------------------------------------------- |
| version            | 0.87.1                                                    |
| branch             |                                                           |
| commit_hash        |                                                           |
| build_os           | linux-x86_64                                              |
| build_target       | x86_64-unknown-linux-gnu                                  |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                       |
| rust_channel       | stable-x86_64-unknown-linux-gnu                           |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                       |
| build_time         | 2023-11-21 18:26:35 +01:00                                |
| build_rust_channel | release                                                   |
| allocator          | mimalloc                                                  |
| features           | default, sqlite, trash, which, zip                        |
| installed_plugins  | clipboard copy, clipboard paste, jwalk, nu_plugin_explore |

### Additional context

i tried running the Git command as a `(...)` subexpression or pipe it to `str trim`, but none of them worked...

only using a temporary variable worked
```nushell
def baz []: nothing -> string {
    let res = ^git rev-list HEAD | lines | last
    $res
}
```

**Comment by fdncred** [comment]
This is a little weird. In the repl it seems to work fine. At least this is what I get in Windows.
```nushell
❯ git rev-list HEAD | lines | last | debug -r
String {
    val: "8f3b273337b53bd86d5594d5edc9d4ad7242bd4c",
    internal_span: Span {
        start: 374281,
        end: 374284,
    },
}
```

**Comment by fdncred** [comment]
oh, wait, I bet this is an input_output issue. Either lines or last doesn't have string in their input_outputs?

**Comment by amtoine** [comment]
yeah it does, just as in `foo` above :yum:

**Comment by amtoine** [comment]
> oh, wait, I bet this is an input_output issue. Either lines or last doesn't have string in their input_outputs?
>
aah maybe :open_mouth:

**Comment by fdncred** [comment]
Yup, I think that's it. Here's the signature.
```rust
    fn signature(&self) -> Signature {
        Signature::build("last")
            .input_output_types(vec![
                (
                    // TODO: This variant duplicates the functionality of
                    // `take`. See #6611, #6611, #6893
                    // TODO: This is too permissive; if we could express this
                    // using a type parameter style it would be List<T> ->
                    // List<T>.
                    Type::List(Box::new(Type::Any)),
                    Type::List(Box::new(Type::Any)),
                ),
                (
                    // TODO: This is too permissive; if we could express this
                    // using a type parameter it would be List<T> -> T.
                    Type::List(Box::new(Type::Any)),
                    Type::Any,
                ),
                (Type::Binary, Type::Binary),
            ])
            .optional(
                "rows",
                SyntaxShape::Int,
                "starting from the back, the number of rows to return",
            )
            .category(Category::Filters)
    }
```

**Comment by amtoine** [comment]
but they have `any`, that should'nt count? :thinking:

**Comment by fdncred** [comment]
You should try adding `Type::List(Box::new(Type::Any)), Type::String` and see what it does. I bet it will work. I can't answer the `any` question though.

**Comment by amtoine** [comment]
i tried to add `list<string> -> string` but it didn't work :thinking: 

i think what's happening is that the `list<any> -> list<any>` and `list<any> -> any` i/o types are shadowing all the other more narrow ones, e.g. `list<string> -> string`...
when i remove them all and keep `list<string> -> string` alone, the command starts parsing and running fine
```nushell
def foo []: nothing -> string {
    ^git rev-list HEAD | lines | last
}
```

> **Note**
> i've made sure the culprit was indeed `last` by parsing the following command without issues
> ```nushell
> def bar []: nothing -> list<string> {
>     ^git rev-list HEAD | lines
> }
> ```

**Comment by fdncred** [comment]
>  i/o types are shadowing all the other more narrow ones

yes, this is a known bug and needs to be fixed. I confirmed with @sophiajt a few weeks ago that i/o types are processed from top to bottom and it picks the first one that is successful. So, in your instance, if you put that string one at the very top, I bet it would work.

**Comment by amtoine** [comment]
oooh that's smart :yum:
