### ISSUE TITLE
remove directory module autoexport

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#11133]
### Related problem

we've discussed this on Discord and in a Nushell meeting: directory module auto-exports are handy but sometimes annoying and force to do strange things
- to hide a module as internal, you'd have to put it inside a subdirectory without any `mod.nu`
- trying to export definitions manually produces duplicated objects, e.g. 4 times the same command in `help main-command`

it has been agreed in said meeting that this feature could be removed to allow more power when it comes to module architecture :yum: 

### Describe the solution you'd like

i think it would be great to remove the auto-export by default => users would have to export them manually, as in more traditional languages such as Rust or Python.

we could imagine a new syntax that would *export all from directory*, something like
```nushell
use dir/*
```

**Comment by texastoland** [comment]
> ```nushell
> use dir/*
> ```

@amtoine Would a new issue to implement `export use *` (other files in same directory) and `export module *` (other folders in same  directory) be helpful?
