### ISSUE TITLE
I want to contribute to this project. Any suggestions?

### ISSUE THREAD

**Issue by BogdanCiocea** [nushell/nushell#11141]
### Question

I am new in Rust and I want to contribute to your project. What should I start with here?
Something not very complicated for someone who's new to this language.

P.S: I have done Rust tour

**Comment by fdncred** [comment]
You should look for items labeled [good first issue](https://github.com/nushell/nushell/labels/good%20first%20issue). We're not super great labeling all the "starter/easy" things but you may find some and sometimes those issues can be harder than we expect, but it's at least a place to start.
