### ISSUE TITLE
autocd doesn't reset $env.LAST_EXIT_CODE

### ISSUE THREAD

**Issue by Zarel** [nushell/nushell#11159]
### Describe the bug

autocd doesn't reset $env.LAST_EXIT_CODE

### How to reproduce

```
❯ ^false

❯ cd Documents/

❯ $env.LAST_EXIT_CODE
0

❯ ..

❯ ^false

❯ ./Documents/

❯ $env.LAST_EXIT_CODE
1
```

### Expected behavior

`./Documents/` should set `$env.LAST_EXIT_CODE` back to `0`, like `cd Documents/`

### Configuration

| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.87.1                                         |
| branch             |                                                |
| commit_hash        |                                                |
| build_os           | macos-aarch64                                  |
| build_target       | aarch64-apple-darwin                           |
| rust_version       | rustc 1.74.0 (79e9716c9 2023-11-13) (Homebrew) |
| cargo_version      | cargo 1.74.0                                   |
| build_time         | 2023-11-18 17:46:36 +00:00                     |
| build_rust_channel | release                                        |
| allocator          | mimalloc                                       |
| features           | dataframe, default, sqlite, trash, which, zip  |
| installed_plugins  |                                                |

**Comment by amtoine** [comment]
yup, i think they should at least behave the same :+1:

**Comment by fdncred** [comment]
Agreed, autocd should work like cd with resetting exit code.
