### ISSUE TITLE
Environment variables on Windows need deterministic and documented behavior

### ISSUE THREAD

**Issue by raggi** [nushell/nushell#11154]
### Describe the bug

Environment variable functions (getenv, putenv, etc) on Windows are not case sensitive: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/getenv-s-wgetenv-s?view=msvc-170#remarks

Nushell presents and environment table that presents a case-sensitive world in the Unix style. Nushell configuration has a very nebulous comment in the default generated env file containing:

```
# To add entries to PATH (on Windows you might use Path), you can use the following pattern:
```

If you start nushell under most terminal emulators it will happen to observe an environment variable called `Path`, however, if you observe it running under a program that does for example `getenv("PATH"); ... putenv("PATH"...` then scripts using `Path` will fail.

The problem gets deeper when you set variables that overlap each other, as the actual value observed by programs launched from nushell becomes unpredictable:

- I set `$env.Foo = 1` and `$env.FOO = 2`, spawned program & process explorer showed `Foo = 2`
- I additionally set `$env.FoO = 3` and spawned a program & process explorer showed `FOO = 3`
- I updated `$env.Foo = 4` then a spawned program still saw `FOO = 3`

It is therefore not last-write-wins, nor is it a particular case wins, or any other immediately obvious rule.

### How to reproduce

Install https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer so that you can externally observe environment variables passed to programs.

Perform the following tests with an arbitrary program, nvim might be a reasonable choice:

- Set `$env.Foo = 1` and `$env.FOO = 2`, spawn a program & process explorer shows `Foo = 2`
- Set `$env.FoO = 3` spawn a program & process explorer shows `FOO = 3`
- Update `$env.Foo = 4` then a spawn a program, observe `FOO = 3`

Note the values shown in process explorer _might_ differ from the above if this happens to be ordered by the side effect of HashDOS guarded hashmap evaluation, which I'd guess this may well be.

The key observation is that it is not user-predictable what values the spawned child programs will observe, they do not see all of the values, nor do they see "last-write" or some similarly easy to understand or define pattern.

### Expected behavior

In order to better integrate with the Windows ecosystem, nushell should present a case-insensitive environment variable map on Windows. Reading/writing from `$env.Path` and `$env.PATH` should have identical behaviors in all regards.

If the above behavior is not selected, the behavior for _reading variables_ from the system, and the behavior for _writing variables_ for spawned programs should be _deterministic_ and _documented_.

The description text in the generated environment config should be clear, and not use "might" to partially describe the behavior.

### Configuration

Defaults.

### Additional context

The following bugs may be related:

- https://github.com/nushell/nushell/issues/7937
- https://github.com/nushell/nushell/issues/7741
- https://github.com/nushell/nushell/issues/6011
- https://github.com/nushell/nushell/issues/5811

https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/getenv-s-wgetenv-s?view=msvc-170#remarks

**Comment by fdncred** [comment]
Agreed. We'd probably accept a PR that fixes this.

**Comment by YizhePKU** [comment]
I think we can close this now because #12701.

**Comment by fdncred** [comment]
Thanks
