### ISSUE TITLE
Don't add commands to history unless they returned 0

### ISSUE THREAD

**Issue by MatrixManAtYrService** [nushell/nushell#11156]
Thanks for nushell, it's fantastic!

### Related problem

When I search history, it is cluttered up with commands that have typos in them.  I end up rerunning the flawed command and overlooking the correct one.

### Describe the solution you'd like

An option to enable this behavior.  I'd recommend defaulting it to true, but I could imagine others might disagree.

**Comment by amtoine** [comment]
would filter the bad commands every once in a while with a script be enough? :innocent: 

you can do things like
```nushell
open $nu.history-path | query db "SELECT * FROM history WHERE exit_status == 0"
```
so i'm sure you could write a command that `DELETE`s the history entries that have an `exit_status` different than `0`, assuming you are using the `SQL` history

**Comment by MatrixManAtYrService** [comment]
Oh interesting.  Ok yeah that would work.  I'm pretty new to nushell so I'm not yet comfortable thinking in its terms.  I already have a custom keybinding to run my history through fzf, so there's an obvious way place to put that code.

Thanks for the suggestion, I'll try that.

**Comment by amtoine** [comment]
> Oh interesting. Ok yeah that would work. I'm pretty new to nushell so I'm not yet comfortable thinking in its terms. I already have a custom keybinding to run my history through fzf, so there's an obvious way place to put that code.
> 
no worries at all :blush: 

> Thanks for the suggestion, I'll try that.
>
hope it will be enough for your use case :innocent:

**Comment by fdncred** [comment]
You could also do this:
```nushell
open $nu.history-path | query db "SELECT * FROM history WHERE exit_status == 0"
```
without resorting to opening the sqlite db file and using sql. Like this:
```nushell
history | where exit_status == 0
```

**Comment by Schweber** [comment]
Would it still be possible to add this to the list of future features? It would make using nushell more approachable and it should be easy to add this to the code.

Right now i'm using `def purge_history [] { open $nu.history-path | query db "delete from history where exit_status != 0" }` with
```
    hooks: {
        pre_prompt: [{ purge_history }] # run before the prompt is shown
...
    }

but i don't know if it is so smart to add this overhead before every redraw of the prompt. If the failed commands weren't saved in the first place there would be no overhead if i'm understanding it correctly.

**Comment by fdncred** [comment]
It's possible. I'm not sure if it would be better as a reedline PR or a nushell PR.
