### ISSUE TITLE
Navigating a large file is slow

### ISSUE THREAD

**Issue by marekdedic** [nushell/nushell#1115]
**Describe the bug**
Navigating a large file is very slow

**To Reproduce**
```sh
$ open large-file.jsonl
```
This opens the file and at the bottom writes "[ESC to quit, arrow keys to move]". However, doing any of that is extremely slow.

**Expected behavior**
Moving up and down the file would be instant, closing the file as well. This is what happens when I open the file with e. g. `less`.

**Configuration (please complete the following information):**
 - OS: Debian testing
 - Version 0.7.1

**Comment by kevlarr** [comment]
Not sure if it's related, but I have a 500 MB `.csv` file that I tried the following on..

```
> open some-big.csv | first 10 | histogram "pvalue"
```

I had to use kill the process because it was exhausting system resources (Activity Monitor on MacOS reported 26 GB) .

**Comment by marekdedic** [comment]
Still relevant...

**Comment by marekdedic** [comment]
Hi,
last time I checked, which was I think 2 months ago, the bug was still present.

However, I am closing this issue as I do not want to play this tug-of-war with the stale bot - I hate the bot with a burning passion. It is hostile to contributors and leads only to frustration and chaos in the issues in my opinion. I have no other issues open, nor will I be reporting any that I may find in the future if the bot is still active.

I wish you all the best with nushell and I am still rooting for it. If I could help with solving this issue in the future, let me know, I'd be glad to help.

**Comment by hustcer** [comment]
I dislike the bot either
