### ISSUE TITLE
Input of diacritics crashes the shell

### ISSUE THREAD

**Issue by marekdedic** [nushell/nushell#1116]
**Describe the bug**
When in nushell and I press for example the `ě` key on my keyboard (tried it with `ěščřžýáíé`), the shell crashes

**To Reproduce**
```sh
/home/user> thread 'main' panicked at 'byte index 1 is not a char boundary; it is inside 'ě' (bytes 0..2) of `ě`', src/libcore/str/mod.rs:2068:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Expected behavior**
I would get the character `ě` on the command line

**Configuration (please complete the following information):**
 - OS: Debian testing
 - Version 0.7.1

**Comment by sbstnzmr** [comment]
This is also true for the German special characters `ßüöä`

**Configuration**

- Windows 10
- PowerShell 6.2.3
- nushell 0.7.1

**Comment by jonathandturner** [comment]
This was fixed a while ago, but I forgot to close the bug. I went ahead and tried with the latest in master and both examples work.
