### ISSUE TITLE
Tab breaks `split words`

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11168]
### Describe the bug

When `split words` encounters a tab character, it stops.

### How to reproduce

```Nushell
~/compds/bioinf/homework-4> "ENSMUSG00000000001.4\t4507" | split words
╭───┬─────────╮
│ 0 │ ENSMUSG │
╰───┴─────────╯
```

### Expected behavior

I'd expect tabs to be treated as whitespace.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.86.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2023-10-22 21:58:37 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

**Comment by amtoine** [comment]
@KAAtheWiseGit 
i don't think this is the issue here :smirk: 
i think `00000000001.4\t4507` is just not a word, look at
```nushell
> "ENSMUSG00000000001.44507" | split words
─┬───────
0│ENSMUSG
─┴───────
```
and
```nushell
> "ENSMUSG00000000001.4\t4507foo" | split words
─┬───────
0│ENSMUSG
1│foo
─┴───────
```

**Comment by KAAtheWiseGit** [comment]
@amtoine, huh, right.  I am curious, why does `split words` operate on characters and not whitespace?

**Comment by amtoine** [comment]
> @amtoine, huh, right. I am curious, why does `split words` operate on characters and not whitespace?
>
i must admit i have no idea :thinking: 

you might have to dig into the code a bit to see where it comes from and why that definition of a "*word*" was chosen :yum:

**Comment by KAAtheWiseGit** [comment]
It has a lot of regex and uses alpha, which ignores numbers.  It seems they were used because they are faster than `split_whitespace`.  I wonder if `split_ascii_whitespace` would be faster.

**Comment by KAAtheWiseGit** [comment]
I think the custom logic should be replaced by `split_ascii_whitespace`.  I thought about suggesting `exec ($command | split words)` for #11199, but it doesn't work, because `-` is not an alpha character.

**Comment by amtoine** [comment]
@KAAtheWiseGit 
so you suggest to always split words on any ASCII whitespace, right?

**Comment by KAAtheWiseGit** [comment]
@amtoine yep, just spaces, tabs, and newlines.   Faster than both the regex and `split_whitespace`.  Although I don't know how important the speed for this command is.

**Comment by amtoine** [comment]
sounds fair to me, a word is a string of maximum size without any whitespace in it :ok_hand:

**Comment by weirdan** [comment]
With #13502 the output is:

```console
$ "ENSMUSG00000000001.4\t4507" | split words
╭───┬────────────────────╮
│ 0 │ ENSMUSG00000000001 │
│ 1 │ 4                  │
│ 2 │ 4507               │
╰───┴────────────────────╯
```
