### ISSUE TITLE
Cursor disappears depending on history and inline prediction

### ISSUE THREAD

**Issue by stax76** [nushell/nushell#11174]
### Describe the bug

Cursor disappears depending on history and inline prediction.

### How to reproduce

1. Move the config files config.nu, env.nu and history.txt somewhere else and let nu create default files.
2. Start a session, type `aaa` and press Enter, an error appears because there is no `aaa` command.
3. Type `a`, an `a` is seen but the cursor disappears.

So there is a severe bug and history and inline prediction play a role.

### Expected behavior

Cursor not disappearing.

### Configuration

Defaults.

**Comment by fdncred** [comment]
What version are you running?

I can't reproduce it. I'm wondering if your terminal is producing this affect.

**Comment by stax76** [comment]
Oh my god, it was my terminal background color being identical to a color nushell used. I don't know if I did something really stupid or if it was simply coincidence. I had a hard time finding it out, but I found it, accidentally by creating new terminal profiles, finally this problem is gone, it wasn't a bug after all, I'm sorry.

**Comment by fdncred** [comment]
LOL. I've done similar things.
