### ISSUE TITLE
externals incorrectly seen as internals by `complete`

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#11187]
### Describe the bug

when there is an error with an external command in a `do { ... } | complete` structure, the error is quite confusing.

### How to reproduce

# unhelpful error
- passing non-string to external without `complete`
```nushell
do { git [ null ] }
```
```
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #8:1:1]
 1 │ do { git [ null ] }
   ·            ──┬─
   ·              ╰── Cannot convert nothing to a string
   ╰────
  help: All arguments to an external command need to be string-compatible
```
- passing non-string to external with `complete`
```nushell
do { git [ null ] } | complete
```
```
Error:   × Complete only works with external streams
   ╭─[entry #7:1:1]
 1 │ do { git [ null ] } | complete
   ·                       ────┬───
   ·                           ╰── complete only works on external streams
   ╰────
```

### Expected behavior

i expected both errors to point to the incorrect `null` value, i.e.
- the first one is perfect
- the second one should be
```nushell
Error:   × Complete only works with external streams
   ╭─[entry #7:1:1]
 1 │ do { git [ null ] } | complete
   ·                       ────┬───
   ·                           ╰── complete only works on external streams
   ╰────
```

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.87.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                               |
| rust_channel       | stable-x86_64-unknown-linux-gnu                                   |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                               |
| build_time         | 2023-11-21 18:26:35 +01:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  | clipboard copy, clipboard paste, jwalk, notify, nu_plugin_explore |

**Comment by KAAtheWiseGit** [comment]
`complete` does that on any error:

```Nushell
~> do { not-found } | complete
Error:   × Complete only works with external streams
   ╭─[entry #12:1:1]
 1 │ do { not-found } | complete
   ·                    ────┬───
   ·                        ╰── complete only works on external streams
   ╰────
```

**Comment by amtoine** [comment]
> `complete` does that on any error
>
yeah, that's not great imo :thinking:

**Comment by KAAtheWiseGit** [comment]
@amtoine working on a fix.  I managed to fix this issue, but #9738 and #10204 still occur.  I'd like to fix all of them with one PR.

**Comment by amtoine** [comment]
@KAAtheWiseGit 
if you can keep the changes coherent and simple and kill three birds with one stone, pretty stonks :muscle: :wink:

**Comment by amtoine** [comment]
sounds quite related to https://github.com/nushell/nushell/issues/9738 now that i look at it :open_mouth:
