### ISSUE TITLE
Parse environment variables in env.nu

### ISSUE THREAD

**Issue by 1366613** [nushell/nushell#11184]
### Related problem

When I'm trying to add a relative path to env.nu, it's unable to process the $HOME environment variable and correctly add that directory to $PATH.
```shell
$env.PATH = ($env.PATH | split row (char esep) | prepend '$HOME/.bin')
```

### Describe the solution you'd like

Treat $HOME as an environment variable and resolve its absolute path

### Additional context and details

nu version: `0.87.1`
OS: `macOS Sonoma 14.2 Beta`

**Comment by fdncred** [comment]
`$HOME` is not known to nushell. If you want to access environment variables, you need to use `$env.HOME`.

**Comment by amtoine** [comment]
@1366613 
the command you want is
```nushell
$env.PATH = ($env.PATH | split row (char esep) | prepend ($env.HOME | path join ".bin"))
```
or
```nushell
$env.PATH = ($env.PATH | split row (char esep) | prepend ($nu.home-path | path join ".bin"))
```
