### ISSUE TITLE
cd with multiple dots to go up multiple levels

### ISSUE THREAD

**Issue by marekdedic** [nushell/nushell#1118]
**Is your feature request related to a problem? Please describe.**
I would like to navigate directories quicker.

**Describe the solution you'd like**
As `cd  ..` goes up one level in the directory tree, I would like `cd ...` to go up 2 levels, `cd ....` 3 levels etc. This is a feature of some shells (ZSH in my experience). Maybe even allow this in other places - e. g. `open .../file` to be equal to `open ../../file`. However, it is a trade-of between ease-of-use and potential for accidents.

**Comment by quebin31** [comment]
This can be introduced directly to Path arguments so, later on, can be canonicalized.

**Comment by marekdedic** [comment]
Thanks!
