### ISSUE TITLE
`input list` errors on lists with booleans

### ISSUE THREAD

**Issue by maxim-uvarov** [nushell/nushell#11181]
### Describe the bug

```
> [true false] | input list
Error: nu::shell::type_mismatch

  × Type mismatch.
   ╭─[entry #1:1:1]
 1 │ [true false] | input list
   ·                ─────┬────
   ·                     ╰── expected a list or table, it can also be a problem with the an inner type of your list.
```

### How to reproduce

`[true false] | input list`

### Expected behavior

I expect NuShell to allow the use of lists with booleans.

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.87.1                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | macos-aarch64                                        |
| build_target       | aarch64-apple-darwin                                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)                  |
| rust_channel       | stable-aarch64-apple-darwin                          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)                  |
| build_time         | 2023-11-21 06:42:01 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

### Additional context

This error just a minor glitch which can be easily overriden with:
```
['true' 'false'] | input list | into bool
```

Though I believe that it would be better to fix it, as input list already works with integers with no problems. 
```
> [1 2 3] | input list | describe
int
```

**Comment by KAAtheWiseGit** [comment]
`input list` ignores boolean values: `[1 a true] | input list` will only show `1` and `"a"`.  Bizarre.

**Comment by KAAtheWiseGit** [comment]
It also terminates after booleans.  The issue is `as_string`, I think.

**Comment by KAAtheWiseGit** [comment]
Yep.  All values without `as_string` or `as_record` terminate the processing.  And `as_string` only works for `Int`, `Float`, `String`, `Binary`, and `Date`.

This leaves out booleans, ranges, lists, null, filesizes, durations, cell paths, and custom values.

I suggest adding `Bool`, `Nothing`, and `Filesize`, and `Duration` to the `as_string` function.

**Comment by amtoine** [comment]
maybe for now we can start with simple types :+1:

**Comment by KAAtheWiseGit** [comment]
@amtoine, `Bool`, `Nothing`, `Filesize`, `Duration`, right?

**Comment by KAAtheWiseGit** [comment]
`as_string` a doc comment: "Converts into string values that can be changed into string natively".  What does "natively" mean?

There is also `as_spanned_string`, `into_string`, which converts all of the values (used by shell to print values, I think), `into_abbreviated_string`, and the debug one.

**Comment by amtoine** [comment]
comes from https://github.com/nushell/nushell/pull/4649 but i'm not sure what it means :thinking:

**Comment by KAAtheWiseGit** [comment]
I have a curious idea.  In theory, `into_string` could be used instead:

```Nushell
~/fork/nushell> [                                               11/29/2023 10:22:36 PM
::: 	-100
::: 	9.999
::: 	Infinity
::: 	"a string"
::: 	true
::: 	2000-01-01
::: 	(2min + 12sec)
::: 	64mb
::: 	0..10
::: 	-10..<5
::: 	0x[FE FF]
::: 	{name: "Nushell", lang: "Rust"}
::: 	[{x:12, y:15}, {x:8, y:9}]
::: 	[[x, y]; [12, 15], [8, 9]]
::: 	{|e| $e + 1 | into string }
::: 	if true { print "hello!" }
::: 	null
::: ] | input list
  -100
  9.999
  inf
  a string
  true
  Sat, 1 Jan 2000 00:00:00 +0000 (23 years ago)
  2min 12sec
> 61.0 MiB
  0..10
  -10..5
  [254, 255]
  {name: Nushell, lang: Rust}
  [{x: 12, y: 15}, {x: 8, y: 9}]
  [{x: 12, y: 15}, {x: 8, y: 9}]
  <Closure 1435>
  if
  true
  <Closure 1436>
```

**Comment by KAAtheWiseGit** [comment]
Oh, and `input list` code allows for ranges.  It is only blocked in signatures.

**Comment by amtoine** [comment]
i mean, more allowed inputs to `input list` sounds reasonable to me

**Comment by amtoine** [comment]
keep in mind tables are already allowed!
