### ISSUE TITLE
Long flags sometimes break path completion

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11186]
### Describe the bug

Some long flags (I can't determine the pattern) break path completion.

### How to reproduce

Type `ls --du ` and press <Tab>, this causes an error.  So do `--full-paths`, `--long`, `--mime-type`, and `--mime-type`, while `--all`, `--directory` work properly.

### Expected behavior

Complete paths as usual.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.86.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2023-10-22 21:58:37 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

**Comment by KAAtheWiseGit** [comment]
Can't replicate with `mv`, `cp`.

**Comment by KAAtheWiseGit** [comment]
My completer is:

```Nushell
# Completer
let carapace_completer = {|spans|
	let expanded_alias = (
		scope aliases
		| where name == $spans.0
		| get --ignore-errors 0
		| get --ignore-errors expansion
	)

	let spans = (
		if $expanded_alias != null {
			$spans
			| skip 1
			| prepend ($expanded_alias | split row " ")
		} else { $spans }
	)

	if ($spans | get 0) == "doas" {
		let spans = $spans | skip 1
		carapace $spans.0 nushell $spans | from json
	} else {
		carapace $spans.0 nushell $spans | from json
	}
}
```

**Comment by amtoine** [comment]
can you try with Nushell 0.87.1?
i don't get any error, just the list of files with `ls --du <tab here>`

**Comment by KAAtheWiseGit** [comment]
@amtoine I checked it without config, and it works.  Must be Carapace interfering, but I am unsure why exactly this happens (since flags are Nushell's).

**Comment by amtoine** [comment]
mm i'm also using `carapace` :thinking: 
see [my config](https://github.com/amtoine/dotfiles/blob/main/.config/nushell/completion.nu)
