### ISSUE TITLE
Auto-selecting completion when only one remains, sometimes doesn't work

### ISSUE THREAD

**Issue by k0ral** [nushell/nushell#11209]
### Describe the bug

The `completion.quick` configuration option doesn't seem to work in some cases (see scenario below.)

### How to reproduce

Let's say I have 2 files conveniently named `aaa` and `aba`:
```sh
$ touch aaa aba
```

The prefix `ab` has only one possible completion `aba`, however I observe distinct behaviors depending on how I reach that prefix.

## Working case
1. Type `ab`
```
$ cat ab
```
2. Trigger completion (`TAB`)
```
$ cat aba 
```

This correctly auto-selects the only remaining option.

## Failing case
1. Type `a`
```
$ cat a
```
2. Trigger completion (`TAB`)
```
$ | cat a
aaa                 aab                 aba
```
3. Type `b`
```
$ | cat ab
aba 
```
4. Trigger completion (`TAB`) => nothing happens/changes => that's the issue
```
$ | cat ab
aba 
```

### Expected behavior

In the last scenario described above, step (4) should auto-select the only remaining option and result in the following state:
```
$ cat aba 
```

## Environment
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.87.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (built from a source tarball) |
| cargo_version      | cargo 1.72.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

## `config.nu`
```
$env.config = {
  show_banner: false

  completions: {
    quick: true
  }

  history: {
    max_size: 0
    sync_on_enter: false
  }
}

use /home/koral/.cache/starship/init.nu

source /home/koral/.cache/carapace/init.nu

$env.config = ($env | default {} config).config
$env.config = ($env.config | default {} hooks)
$env.config = ($env.config | update hooks ($env.config.hooks | default [] pre_prompt))
$env.config = ($env.config | update hooks.pre_prompt ($env.config.hooks.pre_prompt | append {
  code: "
    let direnv = (/nix/store/83qm9rii0sd5251bjv8344bz9gg423a9-direnv-2.32.3/bin/direnv export json | from json)
    let direnv = if not ($direnv | is-empty) { $direnv } else { {} }
    $direnv | load-env
    "
}))
```

**Comment by fdncred** [comment]
I wonder if `carapace` is influencing this? Does the same thing happen if you comment out your source carapace line?

**Comment by k0ral** [comment]
I've just tested without `carapace` and the behavior is identical.

**Comment by nibon7** [comment]
Commenting out `ReedlineEvent::MenuNext` event may work.


```diff
--- config.nu.bak	2024-01-29 11:28:56.532057932 +0800
+++ config.nu	2024-01-29 11:28:34.726055903 +0800
@@ -336,7 +336,7 @@ $env.config = {
             event: {
                 until: [
                     { send: menu name: completion_menu }
-                    { send: menunext }
+                    # { send: menunext }
                     { edit: complete }
                 ]
             }
@@ -349,7 +349,7 @@ $env.config = {
             event: {
                 until: [
                     { send: menu name: ide_completion_menu }
-                    { send: menunext }
+                    # { send: menunext }
                     { edit: complete }
                 ]
             }

```

**Comment by nibon7** [comment]
A quick fix for reedline

```diff
diff --git a/src/engine.rs b/src/engine.rs
index 50f57ac..e7bcceb 100644
--- a/src/engine.rs
+++ b/src/engine.rs
@@ -937,13 +937,17 @@ impl Reedline {
                 }
                 Ok(EventStatus::Inapplicable)
             }
-            ReedlineEvent::MenuNext => {
-                self.active_menu()
-                    .map_or(Ok(EventStatus::Inapplicable), |menu| {
+            ReedlineEvent::MenuNext => match self.active_menu() {
+                None => Ok(EventStatus::Inapplicable),
+                Some(menu) => {
+                    if menu.get_values().len() == 1 && menu.can_quick_complete() {
+                        self.handle_editor_event(prompt, ReedlineEvent::Enter)
+                    } else {
                         menu.menu_event(MenuEvent::NextElement);
                         Ok(EventStatus::Handled)
-                    })
-            }
+                    }
+                }
+            },
             ReedlineEvent::MenuPrevious => {
                 self.active_menu()
                     .map_or(Ok(EventStatus::Inapplicable), |menu| {
``
