### ISSUE TITLE
`upsert` on lists with closure/block throws weird error

### ISSUE THREAD

**Issue by crides** [nushell/nushell#11204]
### Describe the bug

```
N  [1 2 3 4 5] | upsert 3 {|i| $i + 3 }
Error: nu::shell::not_a_list

  × Not a list value
   ╭─[entry #19:1:1]
 1 │ [1 2 3 4 5] | upsert 3 {|i| $i + 3 }
   ·  ┬                   ┬
   ·  │                   ╰── value not a list
   ·  ╰── value originates here
   ╰────
```

### How to reproduce

as above

### Expected behavior

return `[1 2 3 7 5]`

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.86.1                                                            |
| branch             | main                                                              |
| commit_hash        | 8560b9b90e078974f908c0a49ea8fedd3ab2ded4                          |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03) (built from a source tarball) |
| cargo_version      | cargo 1.71.2 (1a737af0c 2023-08-07)                               |
| build_time         | 2023-11-10 10:22:22 -08:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, extra, sqlite, trash, which, zip                         |
| installed_plugins  | from plist                                                        |

**Comment by fdncred** [comment]
I'm not sure this is supposed to work, update and upsert need a cell path and lists don't have cell paths. I think you'd have to do something like this to use update or upsert.
```nushell
❯ [1 2 3 4 5] | wrap a | update a {|r| $r.a + 3} 
╭─#─┬─a─╮
│ 0 │ 4 │
│ 1 │ 5 │
│ 2 │ 6 │
│ 3 │ 7 │
│ 4 │ 8 │
╰─#─┴─a─╯
```

**Comment by crides** [comment]
but when used without a closure, `[1 2 3 4 5] | upsert 3 7` does work, so I don't think it's a cell path issue.

also, [the book on cellpaths](https://www.nushell.sh/book/types_of_data.html#cell-paths) does use an example where the index indexes into a list (`.0.langs` is clearly a list)

**Comment by crides** [comment]
Also, regardless of whether lists are supported or not, the error is confusing

**Comment by fdncred** [comment]
`[1 2 3 4 5] | upsert 3 7` seems weird to me but it's cool that it works.

Also, I think I may be wrong, and lists do support cell-paths, as I was reminded about this earlier this week. Here's an example.
```nushell
❯ [1 2 3 4 5] | get $.3
4
```
`$.3` is a cell-path literal.

Someone would need to look at the code but I'm guessing when closures are used it's looking for a column for a cell-path. 

I 100% agree that the error is super-weird an unhelpful.

**Comment by amtoine** [comment]
i don't think `upsert` should work on lists :thinking: 
there is already `update` for that and the error would be an "invalid input type" if we restrict the i/o types of `upsert` :+1:

**Comment by crides** [comment]
Actually, having `upsert` for lists _is_ a weird idea, since it's hard to say what index exists in a list (outside of the indicies the list already has, i.e. anything between 0 and length). For example, for `[1 2 3]`, what should `upsert 4 ...` do? what should `upsert 5 ...` do?

However, `update` on lists with closures also doesn't work:

```
❯ [1 2] | update 0 {|i| $i + 3}
Error: nu::shell::incompatible_path_access

  × Data cannot be accessed with a cell path
   ╭─[entry #76:1:1]
 1 │ [1 2] | update 0 {|i| $i + 3}
   ·                ┬
   ·                ╰── int doesn't support cell paths
   ╰────
```

**Comment by IanManske** [comment]
> Actually, having `upsert` for lists *is* a weird idea, since it's hard to say what index exists in a list (outside of the indicies the list already has, i.e. anything between 0 and length). For example, for `[1 2 3]`, what should `upsert 4 ...` do?

Currently, insert and upsert only accept indices in the range `[0, length]`, where an index of `length` means to insert at the end. This is the same as `Vec::insert` in Rust, `List` insert in C#, etc. Indices out of this range give an error.

But yeah, the error for the closure is indeed not very helpful. Looking over the code, there's a few bugs in `insert`, `upsert`, and `update` which includes the closure handling.

**Comment by fdncred** [comment]
Ok, here's my 2 cents.
1. we want a more verbose error message that explains the error and how it works based on index vs value
2. i'm not sure if we need to support closures, it seems intuitive to me that we'd support closures here, but i'm not sure how others will feel.

**Comment by crides** [comment]
Fixed in PR, closing
