### ISSUE TITLE
`as_string` doesn't print binaries, which are not valid utf-8

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11200]
### Related problem

Currently as string will raise an error, if the binary is not a valid string.  This means, for example, that such binaries got ignored by `input list` before #11195.

### Describe the solution you'd like

Inserting some kind of special characters instead, maybe the way Vim does.

**Comment by amtoine** [comment]
> Currently as string will raise an error
> 
could you give an example of what "as string" is? :yum:

**Comment by KAAtheWiseGit** [comment]
Right!

`[1 0x[1F FF AA AA]] | input list` only yields one, while `[1 0x[23 45]] | input list` returns a list of `1` and `#E`.

This gets fixed for `input list` with #11195, but it is still an effect of `as_string()`.

**Comment by amtoine** [comment]
ooh okey, yeah i see :thinking: 

`0x[23 45]` is valid ASCII so it gets converted to a string, but not `1F FF AA AA` :open_mouth:

**Comment by KAAtheWiseGit** [comment]
This has been resolved at some point.
