### ISSUE TITLE
`get -i` doesn't ignore errors in ...rest cell paths

### ISSUE THREAD

**Issue by maxim-uvarov** [nushell/nushell#11212]
### Describe the bug

```nushell
> [[a];[c]] | get -i b a
╭───────╮
│ ╭──╮  │
│ │  │  │
│ ╰──╯  │
│ ╭───╮ │
│ │ b │ │
│ ╰───╯ │
╰───────╯

> [[a];[c]] | get -i a b
Error: nu::shell::column_not_found

  × Cannot find column
   ╭─[entry #15:1:1]
 1 │ [[a];[c]] | get -i a b
   · ────┬────            ┬
   ·     │                ╰── cannot find column 'b'
   ·     ╰── value originates here
   ╰────
```   

### How to reproduce

`> [[a];[c]] | get -i a b`

### Expected behavior

I expect nu to handle missing cell paths without error

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.87.1                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | macos-aarch64                                        |
| build_target       | aarch64-apple-darwin                                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)                  |
| rust_channel       | stable-aarch64-apple-darwin                          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)                  |
| build_time         | 2023-11-21 06:42:01 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

### Additional context

As a workaround it's possible to use question marks:
`[a];[c]] | get a? b?`

**Comment by sholderbach** [comment]
closed by #11213
