### ISSUE TITLE
Completion sometimes diverges from hints

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11237]
### Describe the bug

From time to time I see a shadow completion matching something I am typing and press the up arrow.  Rarely, the text appearing differs from what was shown in grey.

### How to reproduce

I can't find a way to reproduce this issue, as it seems to rely on my history.  So far this has only happened outside of my home directory (`~`), where I execute the majority of my command.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.87.1                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2023-11-27 13:49:51 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

### Additional context

The bug report isn't really actionable, but I decided to file it so that there is some information if a similar issue arises for someone else.

**Comment by fdncred** [comment]
Do you see this with sqlite or plaintext history? I thought you were talking about hints but maybe not?

**Comment by KAAtheWiseGit** [comment]
@fdncred sqlite.  I mean the suggestion like this one, I don't know the correct term:

![image](https://github.com/nushell/nushell/assets/97791001/98d98f8a-5180-4ca8-89d0-042e363a7a0f)

**Comment by fdncred** [comment]
Those are called hints in nushell and they come from the history, I believe.

**Comment by KAAtheWiseGit** [comment]
It got worse today, and it is quite annoying.  Is there a way to disable working directory-aware hints?

**Comment by KAAtheWiseGit** [comment]
Ah, got it, thanks!  I got into the habit of using the up arrow without knowing of the right way to do it, so that must've caused issues for me (I was sure it was the same thing, so I was caught off guard by the divergence).

Will close the issue, now that I understand the difference.

**Comment by fdncred** [comment]
thanks @p00f for jumping in
