### ISSUE TITLE
Q: Does benchmarking work?

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11236]
### Question

I tried to benchmark Nushell to investigate removing `hashbrown` dependency from `lru`, but couldn't get it to work.  It was throwing thousands of errors of `$nu.default-config-dir` not being included.

Is this a known problem, or something local on my end?

**Comment by fdncred** [comment]
Do you mean running our benchmarks like `cargo bench` which compiles and runs the benchmark.rs in our repo? If so, it should work. I even think @amtoine has a repo for these benchmarks https://github.com/amtoine/nu-criterion-tracker.

**Comment by KAAtheWiseGit** [comment]
I tried to copy it, but it broke my terminal
