### ISSUE TITLE
`def --wrapped` does not show tab completion for the wrapped command

### ISSUE THREAD

**Issue by dchinmay2** [nushell/nushell#11243]
### Describe the bug

[`def --wrapped` is not a suitable replacement for `extern-wrapped`](https://github.com/nushell/nushell/issues/11096) v2: `extern-wrapped` makes tab completion fall through to the command being wrapped, while `def --wrapped` does not

### How to reproduce
0) install fzf
1)
```
def --wrapped fzf [...argv] {
    if (darkman get) ==



 "dark" {
        ^fzf --color dark $argv
    } else {
        ^fzf --color light $argv
    }
}
```
2) `fzf --`
3) press tab: it only completes `--help` defined by nushell
`~: fzf --help `

Now try this with extern-wrapped: it works
```
~| fzf --
--algo             Fuzzy matching algorithm
--ansi             Enable processing of ANSI color codes
--bind             Custom key bindings
--border           Draw border around the finder
--color            Base scheme
--cycle            Enable cyclic scroll
--delimiter        Field delimiter regex
--exact            Enable Exact-match
--exit-0           Exit immediately when there's no match
--expect           Comma-separated list of keys to complete fzf
--extended         Extended-search mode
--filepath-word    Make word-wise movements respect path separators
--filter           Filter mode
```

### Expected behavior

`def --wrapped fzf []` shows completions for `/usr/bin/fzf` when tab is pressed

### Screenshots

https://github.com/nushell/nushell/assets/36493671/714d569e-119f-4f0c-b9e5-e9b78cd992c4

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.87.1                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 3d631490bc17cfef2944072f9b7869cd9cac1e7b                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.74.0 (79e9716c9 2023-11-13) (Arch Linux rust 1:1.74.0-1) |
| cargo_version      | cargo 1.74.0                                                     |
| build_time         | 2023-11-20 13:51:48 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  | gstat, highlight                                                 |

**Comment by fdncred** [comment]
We had a PR around this yesterday or maybe the day before. Can you please check a nightly or the latest main to see if this still exists?

**Comment by p00f** [comment]
wokrs on main, thanks!
