### ISSUE TITLE
Tab completion not working on directory for second argument of cp inside of a closure

### ISSUE THREAD

**Issue by lrdickson** [nushell/nushell#11242]
### Describe the bug

Tab completion not working on directory for second argument of cp inside of a closure.

### How to reproduce

1. Make a test directory (e.g. folder)
2. type `let cptest = {|in| cp $in fold`
3. Press tab

### Expected behavior

The command completes "fold" to "folder".

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.87.2                                                            |
| branch             | main                                                              |
| commit_hash        | 858c93d2e54bda4170b4fc7a7687a113da8366f0                          |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03) (built from a source tarball) |
| cargo_version      | cargo 1.73.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | debug                                                             |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |

**Comment by KAAtheWiseGit** [comment]
Sounds related to #11084, which also involves a closure.
