### ISSUE TITLE
Panic on sourcing empty file

### ISSUE THREAD

**Issue by blueberrycarrot** [nushell/nushell#11256]
### Describe the bug

Panic on sourcing empty file.

### How to reproduce

Create script `a`:
```
source b
```

Create empty file `b`.

Run `a`: `nu a`:
```
$ RUST_BACKTRACE=1 nu a
thread 'main' panicked at 'internal error: missing span contents in file cache', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-protocol-0.86.0/src/engine/state_working_set.rs:347:9
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: nu_protocol::engine::state_working_set::StateWorkingSet::get_span_contents
   3: nu_protocol::engine::state_working_set::StateWorkingSet::add_file
   4: nu_parser::parser::parse
   5: nu_parser::parse_keywords::parse_source
   6: nu_parser::parser::parse_builtin_commands
   7: nu_parser::parser::parse_block
   8: nu_parser::parser::parse
   9: nu_cli::util::eval_source
  10: nu_cli::eval_file::evaluate_file
  11: nu::run::run_file
  12: nu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Expected behavior

A non-panic.

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.86.0                                    |
| branch             |                                           |
| commit_hash        |                                           |
| build_os           | linux-x86_64                              |
| build_target       | x86_64-unknown-linux-gnu                  |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13)       |
| rust_channel       | stable-x86_64-unknown-linux-gnu           |
| cargo_version      | cargo 1.72.1 (103a7ff2e 2023-08-15)       |
| build_time         | 2023-10-31 16:53:44 +01:00                |
| build_rust_channel | release                                   |
| allocator          | mimalloc                                  |
| features           | default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                           |

**Comment by fdncred** [comment]
Thanks. We shouldn't panic here.

**Comment by tdchien** [comment]
I also got the problem like this
![image](https://github.com/nushell/nushell/assets/1614393/fd65cc70-107d-4ba1-bc6b-85bb55197ba7)
