### ISSUE TITLE
`bit-shl` silently overflows

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11267]
### Describe the bug

For big values `bit-shl` overflows, but doesn't return an error.

### How to reproduce

```Nushell
~> 9 bit-shl 1000000000000000000
9
```

### Expected behavior

An error, like for power:

```Nushell
~> 2 ** 1000000000000000000
Error: nu::shell::operator_overflow

  × Operator overflow.
   ╭─[entry #52:1:1]
 1 │ 2 ** 1000000000000000000
   · ────────────┬───────────
   ·             ╰── pow operation overflowed
   ╰────
  help: Consider using floating point values for increased range by promoting
        operand with 'into float'. Note: float has reduced precision!
```

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.87.1                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2023-11-27 13:49:51 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

**Comment by KAAtheWiseGit** [comment]
Also, something wacky happens when shifting by a negative amount:

```Nushell
~> 1 bit-shl -1
-9223372036854775808
~> 1 bit-shl -10
18014398509481984
~> 1 bit-shl -100
268435456
~> 1 bit-shl -1000
16777216
~> 1 bit-shl -10000
281474976710656
~> 1 bit-shl -100000
4294967296
~> 1 bit-shl -1000000
1
```

**Comment by sholderbach** [comment]
OK currently that is not a silent fail but runs into a panic

**Comment by sholderbach** [comment]
Ah got things, mixed up, panics generally with a debug build (the behavior of `<<`/`>>` in Rust in general) Affects both the `bit-shl`/`bit-shr` **operators** and the `bits shl` and `bits shr` **commands** (only the latter are affected by PR #11854 if I remember)
