### ISSUE TITLE
shell integration: prompt start & end markers not properly shown/overwritten

### ISSUE THREAD

**Issue by crides** [nushell/nushell#11260]
### Describe the bug

`nu` outputs `\x1b]133;*` escape sequences that mark start, end of prompt and command. However, it seems like in some situations the prompt start & end markers don't show up/gets overwritten.

There are 2 issues here:
1. When `PROMPT_COMMAND` is not set (i.e. default behavior), even with `shell_integration` turned on, the prompt start and end markers are not shown (`\x1b]133;A\x1b\` and `\x1b]133;B\x1b\`);
2. When `PROMPT_COMMAND` is set, and when the user finishes a command, the markers are also not shown. This ___only___ occurs as enter is pressed. At all instances before that the markers are properly output

### How to reproduce

issue 1 is easy. Just use default and record the output (I used `wezterm record`)
[wezterm-recording-Ysu6ad.cast.txt](https://github.com/nushell/nushell/files/13608996/wezterm-recording-Ysu6ad.cast.txt)
visual output:
![maim-2023 12 07 20 44 25](https://github.com/nushell/nushell/assets/15631555/27cb69e9-65fd-4f8f-9c26-08258b71bdd0)

It should be easy to see that no marker sequences are emitted at all (just search for `133`)

Issue 2 is slightly harder. Using the follow as the config file, again record the output:
```nu
$env.config = {
    show_banner: false
    shell_integration: true
}
$env.PROMPT_COMMAND = {|| "> " }
```
[wezterm-recording-li8YXW.cast.txt](https://github.com/nushell/nushell/files/13609019/wezterm-recording-li8YXW.cast.txt)
visual output: 
![maim-2023 12 07 20 47 12](https://github.com/nushell/nushell/assets/15631555/70babc51-c7d0-475d-a745-7b900081a077)

After the `cd` command is finished, right before the output, no marker sequences are output:
```json
[8.01423,"o","\u001b[?25l\u001b[43;1H\u001b[43;1H\u001b[J\u001b[38;5;10m\u001b]133;A\u001b\\> \u001b]133;B\u001b\\\u001b[38;5;14m\u001b[38;5;5m\u001b7\u001b[43;85H12/07/2023 08:19:46 PM\u001b8\u001b[0m\u001b[0m\u001b[1;36mcd\u001b[0m \u001b[36m~/gitproj/nushell\u001b[0m\u001b7\u001b8\u001b[?25h"]
[8.211831,"o","\u001b[?25l\u001b[43;1H\u001b[43;1H\u001b[J\u001b[38;5;10m> \u001b[38;5;14m\u001b[38;5;5m\u001b7\u001b[43;85H12/07/2023 08:19:46 PM\u001b8\u001b[0m\u001b[0m\u001b[1;36mcd\u001b[0m \u001b[36m~/gitproj/nushell\u001b[0m\u001b7\u001b8\u001b[?25h\u001b[43;1H\r\n\u001b[43;1H\u001b[?2004l"]
[8.211892,"o","\u001b]133;C\u001b\\"]
```
(notice that, the last line contains the "start output" marker. the first line contains the prompt start and end markers, however the second doesn't, and overwrites the sequences in the previous line)

### Expected behavior

marker sequences are always shown

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.86.1                                    |
| branch             | main                                      |
| commit_hash        | 8560b9b90e078974f908c0a49ea8fedd3ab2ded4  |
| build_os           | linux-x86_64                              |
| build_target       | x86_64-unknown-linux-gnu                  |
| rust_version       | rustc 1.71.1 (eb26296b5 2023-08-03)       |
| rust_channel       | 1.71.1-x86_64-unknown-linux-gnu           |
| cargo_version      | cargo 1.71.1 (7f1d04c00 2023-07-29)       |
| build_time         | 2023-11-14 23:19:33 -08:00                |
| build_rust_channel | release                                   |
| allocator          | mimalloc                                  |
| features           | default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                           |

**Comment by crides** [comment]
> Can you help educate me and let me know how to record the session with wezterm?

Included in the screenshot

**Comment by fdncred** [comment]
oof, I totally missed that. thanks!
