### ISSUE TITLE
Move the welcome banner to a separate file

### ISSUE THREAD

**Issue by danimesq** [nushell/nushell#11275]
### Related problem

Currently, I want to use Termux's own welcome message; however, I would have to modify a [whole Rust file](https://github.com/nushell/nushell/blob/8c82000c0b0b8f3cdd067dac8093ba532203d081/crates/nu-cli/src/repl.rs), download dev tools and compile in order to just change that welcome message.

### Describe the solution you'd like

Move to a separate file out of the Rust source, so it don't have to be compiled; and still supporting colouring syntax!

**Comment by fdncred** [comment]
I don't think your assertion is correct. I think all you have to do is change your config.nu to `show_banner: false` and then create a new banner custom command and call it at the end of your config.nu file. I believe our banner command is a nushell custom command just like what I'm saying and is the nushell stdlib.

**Comment by amtoine** [comment]
yeah, it can be turned off with `$env.show_banner = false` and can be used in the REPL with
```nushell
use std banner
banner
```

**Comment by amtoine** [comment]
@danimesq 
i'll close this issue but please feel free to reopen if we missed your point here :yum:

**Comment by danimesq** [comment]
> I don't think your assertion is correct. I think all you have to do is change your config.nu to `show_banner: false`

@amtoine @fdncred, how to do that via CLI/in a programmatic way?

**Comment by amtoine** [comment]
@danimesq 
to disable the banner, you could run something like
```nushell
"$env.config.show_banner = false" out> $nu.config-path
```
> **Note**
> use `out>>` coming next release tomorrow if you want to append to the config file instead of overwriting

to use the banner of the standard library, you can
```nushell
use std banner
banner
```

**Comment by danimesq** [comment]
@amtoine 
`"$env.config.show_banner = false" out> $nu.config-path` is creating a file called exactly `*nu.config-path` in `~/.config/nushell`.

However, when I use `"$env.config.show_banner = false" out> ~/.config/nushell/config.nu`, I do get a error:

> Error: 
>   × Permission denied
>      ╭─[/home/daniella/.config/nushell/config.nu:648:1]
>  648 │ #"$env.config.show_banner = false" out> $nu.config-path
>  649 │ "$env.config.show_banner = false" out> ~/.config/nushell/config.nu
>      ·                                        ─────────────┬─────────────

**Important**: my Nushell version is `0.76.0`.

**Comment by amtoine** [comment]
@danimesq 
you should update your installed Nushell :open_mouth: 
the command i provided works with 0.87.1 :yum: 

12 releases is one year, which is huge in the lifetime of Nushell :scream:
