### ISSUE TITLE
Can't make argument of type `date` in a custom command

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11294]
### Describe the bug

I tried to make a custom command with a date argument, but I got an "unknown type" error.

### How to reproduce

```Nushell
~/fork/nushell> def func [d: date] {}
Error: nu::parser::unknown_type

  × Unknown type.
   ╭─[entry #37:1:1]
 1 │ def func [d: date] {}
   ·              ──┬─
   ·                ╰── unknown type
   ╰────
```

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.87.1                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2023-11-27 13:49:51 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

**Comment by amtoine** [comment]
ooh yeah, that's quite annoying i agree :cry: 

this is already part of the meta issue https://github.com/nushell/nushell/issues/10332, so i'll close this issue in favor of https://github.com/nushell/nushell/issues/10332 :wink:

**Comment by amtoine** [comment]
@KAAtheWiseGit 
as for you custom command, the type is called `datetime` even though `date now | describe` tells `date` :eyes:

**Comment by KAAtheWiseGit** [comment]
Got it, thanks!
