### ISSUE TITLE
nushell cannot open tsv

### ISSUE THREAD

**Issue by wangjiawen2013** [nushell/nushell#11296]
### Question

Hi, I opened a tsv file with the following code:
`open betu.tsv | from tsv`
then the folllowing error occurred:
CSV error: record 1 (line: 2, byte: 3835): found record with 200 fields, but the previous record has 198 fields
is it a bug or there are some errors in my tsv file ?

And another question, here is a tsv file named test.tsv
|c1|c2|c3|
|--|---|--|
|1|2|3|

I cannot open it with `open test.tsv | from tsv`, the following error occurred:

Error: nu::shell::type_mismatch

  × Type mismatch.
   ╭─[entry #99:1:1]
 1 │ open test.tsv | from tsv
   · ──┬─
   ·   ╰── string
   ╰────

then I renamed test.tsv to test, then I can open it with `open test | from tsv`! It seems that `open test | from tsv` is not compatible with the file extension ".tsv". Finally, I rename test.tsv to test.txt, everything is fine !

**Comment by fdncred** [comment]
if there is a `from extension` command like `from tsv` it's called automatically. so, what you were doing reall acts like `open test.tsv | from tsv | from tsv`. what you should try is `open test.tsv` and that should work. if you want to use the parameters that `from tsv` offers you have to open it in raw mode like `open --raw test.tsv | from tsv --flexible` or whatever parameters you want to use.

**Comment by amtoine** [comment]
i did create a TSV file called `test.tsv`,
```
c1	c2	c3
1	2	3
```
and
```nushell
open test.tsv
```
works as expected :thinking: 

so yeah, as @fdncred said, you don't need `from tsv` here :yum:

**Comment by wangjiawen2013** [comment]
Yes, it is the case.
