### ISSUE TITLE
`stor` commands are in category `math`

### ISSUE THREAD

**Issue by Hofer-Julian** [nushell/nushell#11309]
I've noticed that the `stor` commands are in category `math`: https://www.nushell.sh/commands/categories/math.html

Was that a copy-paste mistake @fdncred? 🙂

**Comment by amtoine** [comment]
should it be `core`, `experimental`, `misc`?

**Comment by fdncred** [comment]
@Hofer-Julian LOL. Yup, that's a copy-n-paste mistake. I could live with `experimental`, `db`, `sqlite` or something in that vein.
