### ISSUE TITLE
un::parser::unknown_flag

### ISSUE THREAD

**Issue by wangjiawen2013** [nushell/nushell#11307]
### Question

Hi,
When I type "nu" in my bash terninal to use nushell, an error occurred:

![image](https://github.com/nushell/nushell/assets/29703450/a2907f96-4358-4200-ae7b-5d5ca87e3816)

What's wrong with it ?

**Comment by nibon7** [comment]
You need to update the config.

```nu
config reset
```

**Comment by wangjiawen2013** [comment]
It worked, Thanks!

**Comment by amtoine** [comment]
thanks @nibon7 :pray:
