### ISSUE TITLE
Enable only specific shell_integration features 

### ISSUE THREAD

**Issue by RGBCube** [nushell/nushell#11301]
### Describe the solution you'd like

As discussed in the Discord server:

```nu
shell_integration: {
  OSC7: true
  OSC8: true
  OSC2: true
  VSCODE: true
...
}
```

Maybe use readable names instead of the codenames as well?

### Additional context and details

To not be a breaking change and for ease of use, setting shell_integration to true or false would toggle all settings, and giving a record would toggle those specific features, if a features is omitted from that record it would default to false.

**Comment by TheLostLambda** [comment]
Additionally, if anyone knows which of these integrations are the ones that cause issues in some terminals, then perhaps we selectively enable a couple by default as well!

Especially things like setting the window title with OSC2 feel like they should be enabled by default, but I don't know if there is some wild Windows or MacOS stuff going on that I've not encountered. The window-title setting has always been enabled by default on the shells I've used in the past (like `fish`).

**Comment by fdncred** [comment]
If you want to try out the PR it's #12629
