### ISSUE TITLE
`format` has no meta command

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11332]
### Describe the bug

There is no unified `format` command, which means `help format` doesn't bring up the help for `format date/duration/filesize`.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.88.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2023-12-13 10:05:06 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

**Comment by amtoine** [comment]
good catch :+1:
