### ISSUE TITLE
Calling several external tools no longer works

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11347]
### Question

I have a password manager in Nushell, which uses `age` and `$env.EDITOR` to edit the password.  It worked fine some time age, but when I tried using it today, the editor stopped opening.

### Additional context and details

```Nushell
export def decrypt [] string -> string {
	age --decrypt --identity $env.NUPASS.IDENTITY
}

# Edit a secret using $EDITOR.
export def edit [
	name: string@get_names	# Name of the secret to edit
] {
        ...

	let tmp = mktemp --tmpdir "nupass.XXXXXX"
	mkdir ($path | path dirname)
	open $path | decrypt | save --append $tmp
	^$env.EDITOR $tmp
	open $tmp | encrypt | save --force $path
	rm --permanent $tmp

	...
}
```

After `age` finishes prompting for the password, the command hangs forever, unable to open Neovim.

**Comment by amtoine** [comment]
i think this has been fixed in the most recent hotfix release, i.e. `0.88.1`, could you try with that version? :innocent:

**Comment by amtoine** [comment]
this is the fix https://github.com/nushell/nushell/pull/11317

**Comment by KAAtheWiseGit** [comment]
@amtoine uhh, one moment, the new update broke `use` for me.

**Comment by amtoine** [comment]
> @amtoine uhh, one moment, the new update broke `use` for me.
>
there has been a change to `use` and how modules work on the latest `main` branch.
this time, when i said `0.88.1`, i meant the _crates.io_ release with version `0.88.1`, not the `main` branch :open_mouth:

**Comment by amtoine** [comment]
```nushell
cargo install nu@0.88.1
```
should be what you want to run :wink:

**Comment by KAAtheWiseGit** [comment]
Got it, thanks!  I'll don't have the time to tinker with it right now, but I'll get back to it and report the results.

Oh, is there a writeup on the `use` changes?  So I can future-proof the manager at the same time.

**Comment by amtoine** [comment]
> Got it, thanks! I'll don't have the time to tinker with it right now, but I'll get back to it and report the results.
> 
perfect, keep us updated :pray: 

> Oh, is there a writeup on the `use` changes? So I can future-proof the manager at the same time.
>
not at all for now.
i'll write the release note about that in a few weeks for the release on 2024-01-09, in the meantime, i have fixed a bunch of packages => you can have a look at them at the bottom of my description comment in https://github.com/nushell/nushell/pull/11157

**Comment by KAAtheWiseGit** [comment]
@amtoine I checked the latest release, it's perfect!  It fixes this issue and also resolves a gripe I had with the previous behavior of `use` in modules.

**Comment by amtoine** [comment]
amazing, glad it was already fix in the end :wink: :relieved:
