### ISSUE TITLE
nu does not build on *BSD

### ISSUE THREAD

**Issue by 0323pin** [nushell/nushell#11354]
### Describe the bug

This should be regarded as a serious regression.
After all the work done to have nu available on the three major BSDs, it's unfortunate to reach this point.

### How to reproduce

Build nu > 0.87.0 on any non-Linux/Android platform.

### Expected behavior

Should build on other *nix platforms.

### Screenshots

NA

### Configuration

NA

### Additional context

```
[...]
error: failed to run custom build command for `procfs v0.16.0`

Caused by:
  process didn't exit successfully: `/usr/pkgsrc/wip/nushell/work/nushell-0.88.1/target/release/build/procfs-39014a5d4cafb8e2/build-script-build` (exit status: 1)
  --- stderr
  Building procfs on an for a unsupported platform. Currently only linux and android are supported
  (Your current target_os is netbsd)
warning: build failed, waiting for other jobs to finish...
*** Error code 101

Stop.
[...]

**Comment by KAAtheWiseGit** [comment]
Between 0.87.0 and now, `procfs` got updated to 0.16.0.  It was also added to `nu-command`, in the `ps` command, whereas before it was contained with `#[cfg(any(target_os = "android", target_os = "linux"))]` inside the `linux` module in `nu-system`.

The `ps` command does this instead:

```Rust
#[cfg(all(
    unix,
    not(target_os = "macos"),
    not(target_os = "windows"),
    not(target_os = "android"),
    not(target_os = "ios")
))]
use procfs::WithCurrentSystemInfo;
```

Might be worth trying to build Nushell without the `ps` command to check if that's the cause.

**Comment by 0323pin** [comment]
> #[cfg(any(target_os = "android", target_os = "linux"))]

Which, it's how it should have remained.

> The ps command does this instead:

I'll try to add exceptions for BSD to the already existing exception list.

**Comment by fdncred** [comment]
I don't understand what this is about. We have nightlies https://github.com/nushell/nightly/releases on a bunch of different platforms. We've only had trouble with riscv64.

**Comment by 0323pin** [comment]
> I don't understand what this is about. We have nightlies https://github.com/nushell/nightly/releases on a bunch of different platforms. We've only had trouble with riscv64.
> 
> Maybe the title is just wrong.

There are no BSD builds in those, hence no failures. I've been maintaining `nu` on NetBSD since 0.34.0.

I didn't find the time to patch it according to the suggestion by @KAAtheWiseGit, yet.

**Comment by fdncred** [comment]
> There are no BSD builds in those, 

ok but the title says nu only builds on linux an android which is incorrect. perhaps the title should be something more like 'nu doesn't build in bsd' or something bsd related.

**Comment by 0323pin** [comment]
> > There are no BSD builds in those,
> 
> ok but the title says nu only builds on linux an android which is incorrect. perhaps the title should be something more like 'nu doesn't build in bsd' or something bsd related.

I've changed the title.

**Comment by 0323pin** [comment]
The following patches fix the build on NetBSD. Most probably they also apply to the other BSDs but, I have no way to test it.

```
$NetBSD$

Don't use procfs on NetBSD.

--- crates/nu-command/Cargo.toml.orig	2023-12-17 20:20:27.103974635 +0000
+++ crates/nu-command/Cargo.toml
@@ -106,7 +106,7 @@ libc = "0.2"
 umask = "2.1"
 nix = { version = "0.27", default-features = false, features = ["user"] }
 
-[target.'cfg(all(unix, not(target_os = "macos"), not(target_os = "android"), not(target_os = "ios")))'.dependencies]
+[target.'cfg(all(unix, not(target_os = "macos"), not(target_os = "android"), not(target_os = "ios"), not(target_os = "netbsd")))'.dependencies]
 procfs = "0.16.0"
 
 [target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies.trash]
```

and

```
$NetBSD$

Don't use procfs on NetBSD.

--- crates/nu-command/src/system/ps.rs.orig	2023-12-17 20:00:37.370631469 +0000
+++ crates/nu-command/src/system/ps.rs
@@ -5,7 +5,8 @@ use itertools::Itertools;
     not(target_os = "macos"),
     not(target_os = "windows"),
     not(target_os = "android"),
-    not(target_os = "ios")
+    not(target_os = "ios"),
+    not(target_os = "netbsd")
 ))]
 use nu_protocol::Span;
 use nu_protocol::{
@@ -19,7 +20,8 @@ use nu_protocol::{
     not(target_os = "macos"),
     not(target_os = "windows"),
     not(target_os = "android"),
-    not(target_os = "ios")
+    not(target_os = "ios"),
+    not(target_os = "netbsd")
 ))]
 use procfs::WithCurrentSystemInfo;
 
@@ -123,7 +125,8 @@ fn run_ps(engine_state: &EngineState, ca
                 not(target_os = "macos"),
                 not(target_os = "windows"),
                 not(target_os = "android"),
-                not(target_os = "ios")
+                not(target_os = "ios"),
+                not(target_os = "netbsd")
             ))]
             {
                 let proc_stat = proc
```

I'll try to submit a PR tomorrow.

![2023-12-17-213730_1055x523_scrot](https://github.com/nushell/nushell/assets/90570748/6c7463da-7136-4162-9fc5-66e3577c002f)

**Comment by hustcer** [comment]
If we can cross compile the NetBSD target in Github Ubuntu runners we will find this issue erarlier

**Comment by 0323pin** [comment]
> If we can cross compile the NetBSD target in Github Ubuntu runners we will find this issue erarlier

This was recently added to `trash-rs`, https://github.com/Byron/trash-rs/blob/master/.github/workflows/rust.yml
It would be great.
