### ISSUE TITLE
What is the key bindings to enter the completion hints?

### ISSUE THREAD

**Issue by tamlok** [nushell/nushell#11363]
### Question

Hi, I am using NU on Windows. How should I apply the history completion hints when typing a command? For example, after typing in "n", NU will hint the command "nvim". Then which key should I press to enter the "nvim"? Hitting <TAB> is not the case.

![image](https://github.com/nushell/nushell/assets/5763157/30a26dd0-7fea-46bf-9f22-4dccc9c1153b)

![image](https://github.com/nushell/nushell/assets/5763157/989ea9f4-8c1e-4a66-9344-6f88673151d5)

Thanks!

**Comment by tamlok** [comment]
Ah, finally I think I got the right answer: the UP key. :)

**Comment by fdncred** [comment]
right arrow completes hints, up arrow goes to the previous history entry.

**Comment by fdncred** [comment]
I'm not sure. You might find it by searching for hints.
