### ISSUE TITLE
issue with markdown formatting, maybe?

### ISSUE THREAD

**Issue by kurokirasama** [nushell/nushell#11369]
### Describe the bug

Hey, I've been playing with the note taking app called [joplin](https://joplinapp.org/help/apps/terminal), trying to automate some processes.
Let say I have 2 text files.
```
[text1.txt]
testing

set

body
```
and
```
[test2.txt]
**testing**

test

body
```
Joplin supports md formatting, so that's why I'm testing the second.

First we create a new note called `test`.
```nu
joplin mknote test
```
And see its content (empty so far) with:
```nu
joplin cat test
```

Now I want to add the content of the test1.txt file to the note:
```nu
joplin set test body (open test1.txt)
joplin cat test
```
And it works just fine. But if I try the same in the second file:
```nu
joplin set test body (open test2.txt)
joplin cat test
```
You will se an empty body.

In bash, this works just fine:
```bash
te=$(cat test2.txt)
joplin set test body "$te"
joplin cat test
```

### How to reproduce

already described

### Expected behavior

it should work jusk like with test1.txt

### Configuration

| key                | value                                                                                                                                                                                               |
| ------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.88.2                                                                                                                                                                                              |
| branch             | main                                                                                                                                                                                                |
| commit_hash        | 70f7db14d4141c4680fda82a5519fbcd4080bd1f                                                                                                                                                            |
| build_os           | linux-x86_64                                                                                                                                                                                        |
| build_target       | x86_64-unknown-linux-gnu                                                                                                                                                                            |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13)                                                                                                                                                                 |
| rust_channel       | 1.72.1-x86_64-unknown-linux-gnu                                                                                                                                                                     |
| cargo_version      | cargo 1.72.1 (103a7ff2e 2023-08-15)                                                                                                                                                                 |
| build_time         | 2023-12-18 14:11:32 -03:00                                                                                                                                                                          |
| build_rust_channel | release                                                                                                                                                                                             |
| allocator          | mimalloc                                                                                                                                                                                            |
| features           | dataframe, default, extra, sqlite, trash, which, zip                                                                                                                                                |
| installed_plugins  | custom-value generate, custom-value generate2, custom-value update, from eml, from ics, from ini, from vcf, gstat, hist, inc, net, plot, port scan, query, query json, query web, query xml, xyplot |

### Additional context

I think you need npm14+:
```bash
sudo apt install -y ca-certificates curl gnupg
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
NODE_MAJOR=20
echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
sudo apt-get update && sudo apt-get install nodejs -y
```
and here a script to install joplin:
```nu
def apps-update joplin [ ] {
  print ("updating joplin ui...")
  wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash

  print ("updating jopling cli...")
  bash -c "NPM_CONFIG_PREFIX=~/.joplin-bin npm install -g joplin"
  sudo rm -f /usr/bin/joplin
  bash -c "sudo ln -s ~/.joplin-bin/bin/joplin /usr/bin/joplin"
}
```

**Comment by IanManske** [comment]
For more context, here is the [discord discussion](https://discord.com/channels/601130461678272522/1186341530718445629).
It seems like nushell is handling the args wrong (probably trying to expand `**formatted md text**` as a glob).

**Comment by WindSoilder** [comment]
Hi, would you please try the following:
```bash
joplin set test body $"'(open test2.txt)'"
```
I think we need to quote around them to avoid glob expanding

**Comment by kurokirasama** [comment]
yup, that works! Thanks!

**Comment by amtoine** [comment]
@kurokirasama 
is there still an issue with the answer from @WindSoilder? :innocent:

**Comment by kurokirasama** [comment]
Nop, no issues so far

**Comment by amtoine** [comment]
cool, i'll close the issue then
