### ISSUE TITLE
Directory auto completion using Tab has a bug when path has `.` in its name.

### ISSUE THREAD

**Issue by baehyunsol** [nushell/nushell#11375]
### Describe the bug

The auto completion shows directories that are not supposed to be shown.

### How to reproduce

1. Make directories like below.

- `./a`
  - `./a/dist`
- `./a.b`
  - `./a.b/dist`

2. Goto `.`.

3. Type `cd ./a/d` and press Tab.

### Expected behavior

It should only suggest `./a/dist`, but it shows `./a/dist` and `./a.b/dist`.

### Screenshots

![20231219193341](https://github.com/nushell/nushell/assets/47506131/37fe28b2-1787-406b-b8c1-ebed6cd1ae4a)

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.88.1                                      |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | linux-x86_64                                |
| build_target       | x86_64-unknown-linux-gnu                    |
| rust_version       | rustc 1.76.0-nightly (21cce21d8 2023-12-11) |
| rust_channel       | nightly-x86_64-unknown-linux-gnu            |
| cargo_version      | cargo 1.76.0-nightly (978722961 2023-12-06) |
| build_time         | 2023-12-16 09:37:57 +09:00                  |
| build_rust_channel | release                                     |
| allocator          | mimalloc                                    |
| features           | default, sqlite, trash, which, zip          |
| installed_plugins  |                                             |

### Additional context

Is this intended?

**Comment by lavafroth** [comment]
I was under the impression that this was the intended way for tab completion. Please correct me if I'm getting something wrong.

**Comment by fdncred** [comment]
Wait, I think you're right. `cd /a/d` is really like `cd /a*/d*` where * expands to everything beginning with those letters. Is that right?

**Comment by fdncred** [comment]
closing this @baehyunsol because this is working as planned. Thanks @lavafroth for jumping in.
