### ISSUE TITLE
Add `|>` as alternate syntax for `| save`

### ISSUE THREAD

**Issue by darkwater4213** [nushell/nushell#11371]
### Related problem

Basically: `| save` feels really clunky. It's far from elegant, and `save` honestly feels like a totally unnecessary command.

### Describe the solution you'd like

`|>` as a "save" builtin. Neat thing about this is that Fira Code (among others) a ligature for this, so it looks nice.

### Describe alternatives you've considered

Perhaps `>>` instead? Discuss.

### Additional context and details

I'd really like to use nushell as my daily driver shell. But it needs to be more elegant! You simply can't beat `TARGET="target.d" tar c $TARGET | gzip > ${TARGET}.tar.gz` with `let target = "module.d"; tar c $target | gzip | save $target.tar.gz`. That's just _not elegant_.

**Comment by darkwater4213** [comment]
That being said...
`let target = "module.d"; tar c $target | gzip |> $target.tar.gz` is fine in terms of elegance.

**Comment by sophiajt** [comment]
There's `out>` which you can use to redirect to a file now. Does that work?

**Comment by amtoine** [comment]
`out>` and `out>>` should work :+1: 
combinations with `err` should also work, e.g. `out+err>`

**Comment by WindSoilder** [comment]
I think it's already answered, closing the issue for now
Feel free to reopen it if you still have questions.

**Comment by darkwater4213** [comment]
No, that's good. Not as elegant as `|>` though.

Perhaps:
| Current | possible |
|---|---|
| `out>`, `out>>` | `|>`, `|>>` |
| `err>`, `err>>` | `!>`, `!>>` |
| `out+err>`, `out+err>>` | `+>`, `+>>` |

`$>`, `<>`, `<|>`, `*>` are also available as common font ligatures. Again, my issue is less to do with ease or even characters, but elegance. I think one of the biggest reasons people tend to dislike, say, Java is its utter lack of elegance. People care about syntax. And a big part of syntax is elegance.

**Comment by hustcer** [comment]
These should work too:

| Current | 
|---|
| `o>`, `o>>` | 
| `e>`, `e>>` | 
| `o+e>`, `o+e>>` |

**Comment by darkwater4213** [comment]
An incidental: `find ~ -name init.lua -type f 2>/dev/null` is pretty clunky as far as bash syntax goes. Perhaps `ls **/ | where name = 'init.lua' and type = f !>/dev/null` is more elegant, if longer. But maybe there should be aliases for redirection to `/dev/null` and `/dev/zero`, say `!>0` (doesn't matter which one) or... gosh, I can't recall how to redirect stdin. But `<@` for directing `/dev/null` into stdin and `<0` for `/dev/zero` seem logical. Obviously, the actual syntax would be using whatever nushell does currently use.

What say you?

**Comment by darkwater4213** [comment]
> These should work too and maybe more readable:
> 
> | Current | 
> |---|
> | `o>`, `o>>` | 
> | `e>`, `e>>` | 
> | `o+e>`, `o+e>>` | 

A fair point, but letters are still inelegant, at least in my mind. Perhaps that's bash brain talking. But I don't usually like mixing letters and symbols in individual syntactic entities. It feels sort of like an esolang, if you get what I mean.
