### ISSUE TITLE
[Question] What is 0.7.1?

### ISSUE THREAD

**Issue by kbumsik** [nushell/nushell#1137]
Hi, I'm a maintainer of [one of the AUR packages](https://aur.archlinux.org/packages/nushell/). While updating the package to 0.7.0, I noticed that crates.io provides 0.7.1 when the repo's latest version is 0.7.0.

Could you tell me what is 0.7.1 about and if package maintainers should take care of it? Having all red signs in the package status may give false negative impressions to newbies though.

![image](https://user-images.githubusercontent.com/7823583/71569807-f6e89780-2b14-11ea-854a-fc6704e8e48d.png)

**Comment by jonathandturner** [comment]
@kbumsik 0.7.1 was a point release largely for crates.io users. I don't think there's enough there to warrant a new package release. 

Apologies for any confusion.

**Comment by kbumsik** [comment]
@jonathandturner No problem, I just wanted to make sure. Thanks for replying :)
