### ISSUE TITLE
How to understand the `echo` command's return value in the `each` command?

### ISSUE THREAD

**Issue by malongshuai** [nushell/nushell#11380]
### Question

The Nushell Book tells me `echo`  command return its parameters, but how to understand the different results about the following two command line:

```
~> [1 2 3] | each {|x| ($x + 2) }
╭───┬───╮
│ 0 │ 3 │
│ 1 │ 4 │
│ 2 │ 5 │
╰───┴───╯

~> [1 2 3] | each {|x| echo ($x + 2) }
3
4
5
╭────────────╮
│ empty list │
╰────────────╯
```

Thank you for your answer

**Comment by fdncred** [comment]
`echo` will return dumb strings like `print` unless it's piped into something. The top example will return nushell values, which is why its output is a list.

**Comment by malongshuai** [comment]
> `echo` will return dumb strings like `print` unless it's piped into something. The top example will return nushell values, which is why its output is a list.

Its seems to be easily misunderstood, normally, the command's return value will pipe into the missed `| table` if there is no value consumer，but  according to your explanation, it seems the `echo` has the side effect:
- sometimes `echo` will return its parameters
- sometimes `echo` will return nothing and output parameters to stdout

So, how to know `echo something` will output to stdout(return nothing) or write value into `| table`?

**Comment by aa1ss2** [comment]
[1 2 3] | each {|x| echo ($x + 2) } | to text

**Comment by fdncred** [comment]
This is without redirection.
```nushell
❯ [1 2 3] | each {|x| echo ($x + 2) } | to text
3
4
5
```
This is with redirection.
```nushell
❯ [1 2 3] | each {|x| echo ($x + 2) | to text }  
╭───┬───╮
│ 0 │ 3 │
│ 1 │ 4 │
│ 2 │ 5 │
╰───┴───╯
```

**Comment by NotTheDr01ds** [comment]
You could also wrap it as a [subexpression](https://www.nushell.sh/book/variables_and_subexpressions.html#subexpressions):

```Nu
> [1 2 3] | each {|x| (echo ($x + 2)) }
╭───┬───╮
│ 0 │ 3 │
│ 1 │ 4 │
│ 2 │ 5 │
╰───┴───╯
```

In general, though, I avoid `echo` and just use the implicit return value.

**Comment by weirdan** [comment]
This doesn't happen anymore:

```console
$ [1 2 3] | each {|x| echo ($x + 2) }
╭───┬───╮
│ 0 │ 3 │
│ 1 │ 4 │
│ 2 │ 5 │
╰───┴───╯
```
