### ISSUE TITLE
Strange behavior of completion.

### ISSUE THREAD

**Issue by MediosZ** [nushell/nushell#11396]
### Question

Suppose we have a folder like this:
```
.
├── dir
│   └── readme.md
├── dir_one
│   └── readme.md
├── dir_three
│   └── readme.md
└── dir_two
    └── readme.md
```
When I want to list all the files in `dir`, I will get all files in other folders like

```
~/code/nushell/completion_dir| ls dir/ 
dir/readme.md        dir_one/readme.md    dir_three/readme.md  dir_two/readme.md
```

I don't know how to trigger the completion for files in `dir` only. I think this is strange because I explicitly indicate that I want files in `dir` by pressing `Enter`.
Even I don't know if this is intended or it's a minor bug. Shells like `zsh` or `bash` don't have this behavior.

**Comment by amtoine** [comment]
@MediosZ 
i've seen that before and can reproduce with your example on the latest `main` :thinking: 

imo, this is quite annoying and looks like a bug

**Comment by MediosZ** [comment]
Good to know it's not an intended behavior. 
I will try to fix this.

**Comment by amtoine** [comment]
> Good to know it's not an intended behavior.
>
yeah, imo, `ls dir/<tab>` should directly complete to `ls dir/readme.md` in your example

> I will try to fix this.
>
amazing, thanks for willing to help :pray:

**Comment by amtoine** [comment]
i have the same issue with [NGM](https://github.com/amtoine/nu-git-manager)
```nushell
ls pkgs/nu-git-manager/<tab>
```
gives
```
pkgs/nu-git-manager-sugar/nu-git-manager-sugar/
pkgs/nu-git-manager-sugar/nupm.nuon
pkgs/nu-git-manager-sugar/tests/
pkgs/nu-git-manager/nu-git-manager/
pkgs/nu-git-manager/nupm.nuon
pkgs/nu-git-manager/tests/
```
instead of
```
pkgs/nu-git-manager/nu-git-manager/
pkgs/nu-git-manager/nupm.nuon
pkgs/nu-git-manager/tests/
```

**Comment by fdncred** [comment]
@lavafroth what do you think about this one? Do you have time to help investigate?

**Comment by lavafroth** [comment]
I'm quite busy right now. Will be looking into this after around a week.

**Comment by fdncred** [comment]
That's cool. Thanks for your help!

**Comment by bew** [comment]
This behavior is probably the greedy completions from the system that allows to expand-glob `f/b/` to `foo/bar/`.
It should instead be changed to try to expand-glob the prefix only if it doesn't exist, if it already exists there is no expansion needed.

**Comment by MediosZ** [comment]
I think this behavior is caused by the misconfigured matching strategy. https://github.com/nushell/nushell/blob/072ecec8ca648485f479575659dcc6382d960430/crates/nu-cli/src/completions/completion_common.rs#L22-L29

Completion for `dir` and `dir/` both trigger matching `dir` with all file entries because of the `prefix` matching algorithm. 
So I think adding a `exact` matching when getting completions for folders like `dir/` should fix this problem.
This fix doesn't break the tests. But I am not sure if there is a better solustion.

**Comment by MediosZ** [comment]
I missed something. My fix seems to break the `partial completion` feature.

**Comment by lavafroth** [comment]
I took some time out and checked the code, the linked PR should hopefully fix this.
