### ISSUE TITLE
Nushell reset `prompt_start_row` to 0 when opening a file without newline

### ISSUE THREAD

**Issue by nibon7** [nushell/nushell#11399]
### Describe the bug

When opening a file without newline, nushell reset `prompt_start_row` to 0, which behaves like `clear` command.
I bisect the reedline source code and found this issue was introduced by https://github.com/nushell/reedline/commit/a4bfaa512be8b7214b80c63327930155da86978a.

@fdncred @sholderbach 

### How to reproduce

1. `echo "hello" | save hello`
2. `open hello` (this reset `prompt_start_row` to 0)

### Expected behavior

I expect Nushell not reset `prompt_start_row` to 0 when opening a file without newline.

### Screenshots

[Screencast from 2023-12-23 00-03-03.webm](https://github.com/nushell/nushell/assets/15247421/8b899702-43d4-4915-b537-e6939abe6271)

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.88.2                                      |
| branch             | main                                        |
| commit_hash        | 072ecec8ca648485f479575659dcc6382d960430    |
| build_os           | linux-x86_64                                |
| build_target       | x86_64-unknown-linux-gnu                    |
| rust_version       | rustc 1.77.0-nightly (3d0e6bed6 2023-12-21) |
| rust_channel       | nightly-x86_64-unknown-linux-gnu            |
| cargo_version      | cargo 1.77.0-nightly (1a2666ddd 2023-12-17) |
| build_time         | 2023-12-23 00:00:02 +08:00                  |
| build_rust_channel | debug                                       |
| allocator          | mimalloc                                    |
| features           | default, sqlite, trash, which, zip          |
| installed_plugins  |                                             |

**Comment by fdncred** [comment]
interesting. @danielsomerfield - any thoughts on this?

**Comment by nibon7** [comment]
seems `is_reset()` always true, and ` self.prompt_start_row` is set to 0.
 
https://github.com/nushell/reedline/blob/a4bfaa512be8b7214b80c63327930155da86978a/src/painting/painter.rs#L155-L158

**Comment by fdncred** [comment]
nice research. We just need to make sure it doesn't mess up the reflowing/resizing stuff that daniel has been working on.

**Comment by nibon7** [comment]
The following patch works for me :rofl: 

```diff
diff --git a/src/painting/painter.rs b/src/painting/painter.rs
index bee8642..5c7e1d5 100644
--- a/src/painting/painter.rs
+++ b/src/painting/painter.rs
@@ -153,7 +153,7 @@ impl Painter {
 
         // This might not be terribly performant. Testing it out
         let is_reset = || match cursor::position() {
-            Ok(position) => position.1 < self.prompt_start_row,
+            Ok(position) => position.1 + 1 < self.prompt_start_row,
             Err(_) => false,
         };
```

**Comment by amtoine** [comment]
aaaah YES, i've seen that since a few days, pretty annoying :open_mouth: :scream:

**Comment by amtoine** [comment]
@nibon7 
do you think you'll be able to patch Reedline so that we can fix Nushell? :innocent:

**Comment by danielsomerfield** [comment]
Yup. I did that.

Happy to apply the patch locally and play with it for a bit to see if it introduces any other odd behaviours, but if you think you have it in hand, @nibon7, I'll just pull it down once a branch is up and keep testing.

**Comment by nibon7** [comment]
> @nibon7 do you think you'll be able to patch Reedline so that we can fix Nushell? 😇

I need to look at the code again :muscle:

**Comment by nibon7** [comment]
seems that `position.1` could be `euql`, `greater than` or `less than` `self.prompt_start_now`.

https://github.com/nushell/reedline/blob/a4bfaa512be8b7214b80c63327930155da86978a/src/painting/painter.rs#L106-L120

```diff
diff --git a/src/painting/painter.rs b/src/painting/painter.rs
index bee8642..4ee076e 100644
--- a/src/painting/painter.rs
+++ b/src/painting/painter.rs
@@ -153,7 +153,7 @@ impl Painter {
 
         // This might not be terribly performant. Testing it out
         let is_reset = || match cursor::position() {
-            Ok(position) => position.1 < self.prompt_start_row,
+            Ok(position) => position.1.abs_diff(self.prompt_start_row) > 1,
             Err(_) => false,
         };
 ```

**Comment by amtoine** [comment]
i'm able to reproduce with an even simpler example :open_mouth: 
```nushell
[] | each { echo }
```

**Comment by amtoine** [comment]
and the exact time when it appeared on the Nushell side is
- https://github.com/nushell/nushell/pull/11342

which follows
- https://github.com/nushell/nushell/pull/11339

**Comment by danielsomerfield** [comment]
Installed nu with the [patched reedline](https://github.com/nushell/reedline/pull/688) and so far so good. Resizing still working as expected. There is still some wackiness with the prompts a la https://github.com/nushell/reedline/issues/684, but that's pre-existing, so no surprise.

Looks good!

**Comment by nibon7** [comment]
Thanks for testing this :heart:

**Comment by WindSoilder** [comment]
Re-open it due to  #11425

**Comment by crides** [comment]
Building nushell locally with `reedline` @ `a4bfaa5` doesn't reproduce [the original issue](https://github.com/nushell/nushell/issues/11399#issue-2054143438) for me. I'm not sure what `prompt_start_row` is related to, but doing something like this certainly doesn't cause weird scrolls/clears:
![maim-2024 01 04 01 28 03](https://github.com/nushell/nushell/assets/15631555/2aa412b6-270c-4bfb-9797-bf5737384883)

I thought my custom configs are making things different, so I tried again with no config, still the same thing: 
![maim-2024 01 04 01 27 33](https://github.com/nushell/nushell/assets/15631555/0503032f-4fde-4003-8926-f60a65043e3b)

Note: using `cat` or `open -r` doesn't make a difference

**Comment by crides** [comment]
Oh, I found the phenomenon that causes the behavioural difference. The actual cause will have to be dug up by someone else/later for me.

Doing the same thing in Alacritty _does_ repro the original issue

Recording the session shows this at the end:

```json
[5.3496237,"o","\u001b[?2004l"]
[5.349849,"o","asdf"]
[5.3561435,"o","\u001b[?2004h"]
[5.3561554,"o","\u001b[6n"]
[5.359405,"o","\r\n"]
[5.3594985,"o","\u001b[?25l\u001b[26;1H\u001b[26;1H\u001b[J\u001b[38;5;10m/home/steven\u001b[38;5;14m\u001b[38;5;5m\u001b7\u001b[26;84H01/04/2024 01:41:54 AM\u001b8\u001b[0m\u001b[0m\u001b7\u001b8\u001b[?25h"]
[7.327404,"o","\u001b[26;1H\r\n\u001b[26;1H\u001b[?2004l"]
[7.327419,"o","\r\n"]
[7.3294454,"o","\u001b[0 q\u001b[?25h"]
```

Second line is the output (`asdf`). 4th last line are the left and right prompts. 3rd line is sus: it sets the cursor position at row 26, col 1 (this terminal pane is 26 lines, so this is the bottom left), then does a carriage return and line feed. The line feed is the sus part: Alacritty probably saw this and wrapped around immediately (which IIRC is the right thing to do (in raw mode?)), and wezterm probably saw nothing actually printed and did nothing. After that, I'm not sure what setting the cursor position a second time should do, in alacritty's case.
