### ISSUE TITLE
path separator causing parse errors

### ISSUE THREAD

**Issue by miller-time** [nushell/nushell#1140]
**Describe the bug**
if a path separator shows up in certain places it will cause an invalid parse error 

**To Reproduce**
```
> git clone git@github.com:foo/bar.git
error: Parse Error
- shell:1:36
1 | git clone git@github.com:foo/bar.git
  |                     ^^^^^^^^^^^^^^^^
```

possibly related... this works
```
> cd mysite.github.io
```

but **this** is what tab completion suggests (with trailing `/`):
```
> cd mysite.github.io/
error: Parse Error
- shell:1:27
1 | cd mysite.github.io/
  |          ^^^^^^^^^^^
```

**Expected behavior**
These commands work if they are double-quoted. The double quotes should not be required, though.

**Configuration (please complete the following information):**
 - OS: linux
 - Version: latest master
 - Features: `--features=stable`

**Comment by waldyrious** [comment]
Got the same issue when running a similar command:

```
> git -c core.editor=micro commit --allow-empty
error: Parse Error
- shell:1:45
1 | git -c core.editor=micro commit --allow-empty
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by iKadmium** [comment]
Just confirming that this happens for me in Windows, too.

**Comment by steveklabnik** [comment]
I have also run into this on Windows when trying to clone a git repository.
