### ISSUE TITLE
Inconsistency in representation of binary strings

### ISSUE THREAD

**Issue by nkarl** [nushell/nushell#11412]
### Describe the bug

- Format 1: `001b`
- Format 2: `0b01`

Only the second format is functional when used with `into bits`. In `help bits` the format used is the first format.

### How to reproduce

1. `010b | into bits`
2. `0b10 | into bits`

### Expected behavior

1. `010b | into bits` should evaluate to `00000010`.
2. Instead, it evaluates to `00001010`.

### Screenshots

![Untitled design](https://github.com/nushell/nushell/assets/21993921/b973aef4-3e66-4eb9-ba59-d63745fbe643)

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.88.1                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | linux-x86_64                                         |
| build_target       | x86_64-unknown-linux-gnu                             |
| rust_version       | rustc 1.74.1 (a28077b28 2023-12-04)                  |
| rust_channel       | stable-x86_64-unknown-linux-gnu                      |
| cargo_version      | cargo 1.74.1 (ecb9851af 2023-10-18)                  |
| build_time         | 2023-12-19 19:09:15 -08:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by fdncred** [comment]
I don't follow. 10 bytes is `0000 1010`. We don't have any bits representation in nushell. 10b and 10B are both bytes.

**Comment by IanManske** [comment]
The command's first example is probably confusing. It says:
> convert a binary value

but then uses a filesize, `01b` (1 byte), as input to the command. It should be a binary value: `0x[1]`.

**Comment by fdncred** [comment]
those changes seem reasonable.

**Comment by nkarl** [comment]
> I don't follow. 10 bytes is `0000 1010`. We don't have any bits representation in nushell. 10b and 10B are both bytes.

This was the source of my confusion. I assumed that B is for bytes and b is for bits and that is the general consensus. For example, in Vim the unit for characters is B for bytes.

**Comment by fdncred** [comment]
we have `0b`, `0x`, and `0o` as literal inputs but i believe the output is always in bytes for literals. If you want to force binary you can use `into binary`, which then gives a hexadecimal display since binary isn't represented well in a terminal.

**Comment by nkarl** [comment]
That makes sense now. Thanks.

**Comment by amtoine** [comment]
@nkarl 
i did not follow the whole discussion, is there still an issue to be addressed? :innocent:

**Comment by nkarl** [comment]
I was misunderstanding the behavior. It's all clear to me now. Thanks
