### ISSUE TITLE
`into sqlite` INSERT is based on column order rather than name

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#11429]
### Describe the bug

When inserting a table into a SQLite database, the column names are ignored.  Only the positional column values of the input are used.  This can lead to unexpected corruption of the table.

### How to reproduce

```Nu
> mkdir showme; cd showme; touch foo bar
> ls | select name modified size | into sqlite foo.sqlite
> ls | select name size modified | into sqlite foo.sqlite
> open foo.sqlite | get main
╭───┬────────────┬──────────────────────────────────────┬──────────────────────────────────────╮
│ # │    name    │               modified               │                 size                 │
├───┼────────────┼──────────────────────────────────────┼──────────────────────────────────────┤
│ 0 │ bar        │ 2023-12-27 10:32:40.227788746 -05:00 │                                    0 │
│ 1 │ foo        │ 2023-12-27 10:32:40.227788746 -05:00 │                                    0 │
│ 2 │ bar        │ 0                                    │ 2023-12-27 10:32:40.227788746 -05:00 │
│ 3 │ foo        │ 0                                    │ 2023-12-27 10:32:40.227788746 -05:00 │
│ 4 │ foo.sqlite │ 8192                                 │ 2023-12-27 10:32:49.408107839 -05:00 │
╰───┴────────────┴──────────────────────────────────────┴──────────────────────────────────────╯
```

While this particular example is simplified and contrived, this has happened to me in a real Nu script when the table structure changed.  Nu only seems to check the *number* of columns being inserted.

I see that this is because `into_sqlite.rs` parses the column names, but it only uses them for the `CREATE TABLE`.  When the `INSERT` is performed, only the positional values are used.

### Expected behavior

Use the column names of the Nushell records when performing the `INSERT`.  E.g.:

```SQL
INSERT INTO main (name, modified, size) VALUES
  ('foo', '2023-12-27 10:32:40.227788746 -05:00', 0),
  ('bar', '2023-12-27 10:32:40.227788746 -05:00', 0);
```

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.88.1                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.74.0 (79e9716c9 2023-11-13) (built from a source tarball)               |
| cargo_version      | cargo 1.74.0                                                                    |
| build_time         | 1980-01-01 00:00:00 +00:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | mimalloc                                                                        |
| features           | dataframe, default, extra, sqlite, trash, which, zip                            |
| installed_plugins  | from eml, from ics, from ini, from vcf, query, query json, query web, query xml |

**Comment by WindSoilder** [comment]
Reopen it due to: https://github.com/nushell/nushell/pull/12112
