### ISSUE TITLE
Cannot use an `AUTOINCREMENT` column in Sqlite

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#11430]
### Describe the bug

Attempting to pass a table `into sqlite` with a database with an `AUTOINCREMENT` column will fail.

### How to reproduce

```Nu
> [ 1 ] | into sqlite foo.sqlite -t foo
> open foo.sqlite | query db "CREATE TABLE main (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE); DROP TABLE foo"
> ls | select name | into sqlite foo.sqlite
Error:   × Failed to prepare SQLite statement
   ╭─[entry #102:1:1]
 1 │ ls | select name | into sqlite foo.sqlite
   ·                                ─────┬────
   ·                                     ╰── table main has 2 columns but 1 values were supplied
   ╰────
```

### Expected behavior

Related to #11429 and probably (mostly?) the same fix.

I'd expect/hope that an `into sqlite` that didn't provide a particular column as part of the input would not attempt to insert it, and let SQLite's handling take over.  This would:

* Allow SQLite to handle the `AUTOINCREMENT` values and
* Also allow SQLite to add `NULL` values otherwise (and when allowed by the `NOT NULL` constraint)

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.88.1                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.74.0 (79e9716c9 2023-11-13) (built from a source tarball)               |
| cargo_version      | cargo 1.74.0                                                                    |
| build_time         | 1980-01-01 00:00:00 +00:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | mimalloc                                                                        |
| features           | dataframe, default, extra, sqlite, trash, which, zip                            |
| installed_plugins  | from eml, from ics, from ini, from vcf, query, query json, query web, query xml |

**Comment by fdncred** [comment]
`into sqlite` was never meant to append to a database. It's just meant to create it initially. The `stor` family of commands is more powerful and let's you do more things and has an export command to save it to a sqlite3 file.

**Comment by NotTheDr01ds** [comment]
@fdncred Fair enough - But dang, it's so good at insertion, I never realized the "design limitation" :-).  I do see it in the implementation now that you mention it.

I've looked at `stor`, but it doesn't quite meet my needs in several areas, but most importantly regarding persistence.  I'm appending to a ~100MB SQLite file about once a minute.  Having to read the file into memory every minute, insert via `stor`, and then export it again seems unnecessarily expensive.  Or am I missing a simpler workflow?

**Comment by fdncred** [comment]
> Or am I missing a simpler workflow?

Theoretically, you could do it like this.
1. `stor import --file-name nudb.sqlite` <-- this db is now in memory and accessible via the stor commands
2. `stor insert --table-name nudb --data-record {bool1: true, int1: 5, float1: 1.1, str1: fdncred, datetime1: 2023-04-17}` <-- whatever your table name is and record of information you want to insert
3. `stor open | query db blah blah blah` <-- query the db whenever you like
4. when you're all done, and want to keep the changes you've made do `stor export --file-name nudb.sqlite`
5. reset the in-memory database `stor reset`

**Comment by weirdan** [comment]
It works now:

```console
$ open foo.sqlite | query db "CREATE TABLE main (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE); DROP TABLE foo"
╭────────────╮
│ empty list │
╰────────────╯

$ ls | select name | into sqlite foo.sqlite

$ open foo.sqlite | query db "select * from main"
╭────┬────┬─────────────────────────╮
│  # │ id │          name           │
├────┼────┼─────────────────────────┤
│  0 │  1 │ CITATION.cff            │
│  1 │  2 │ CODE_OF_CONDUCT.md      │
│  2 │  3 │ CONTRIBUTING.md         │
│  3 │  4 │ Cargo.lock              │
│  4 │  5 │ Cargo.toml              │
│  5 │  6 │ Cross.toml              │
│  6 │  7 │ LICENSE                 │
│  7 │  8 │ Movie (2023).mkv        │
│  8 │  9 │ README.md               │
│  9 │ 10 │ SECURITY.md             │
│ 10 │ 11 │ assets                  │
│ 11 │ 12 │ benches                 │
│ 12 │ 13 │ crates                  │
│ 13 │ 14 │ devdocs                 │
│ 14 │ 15 │ docker                  │
│ 15 │ 16 │ external-highlight.cast │
│ 16 │ 17 │ foo.sqlite              │
│ 17 │ 18 │ foo.txt                 │
│ 18 │ 19 │ repro                   │
│ 19 │ 20 │ rust-toolchain.toml     │
│ 20 │ 21 │ scripts                 │
│ 21 │ 22 │ shell-latency-test.py   │
│ 22 │ 23 │ src                     │
│ 23 │ 24 │ target                  │
│ 24 │ 25 │ tests                   │
│ 25 │ 26 │ todo.norg               │
│ 26 │ 27 │ toolkit.nu              │
│ 27 │ 28 │ typos.toml              │
│ 28 │ 29 │ wix                     │
├────┼────┼─────────────────────────┤
│  # │ id │          name           │
╰────┴────┴─────────────────────────╯
```
