### ISSUE TITLE
Will nushell support the language server protocol just like nvim-lsp ?

### ISSUE THREAD

**Issue by uuhan** [nushell/nushell#11439]
### Describe the solution you'd like

If nushell has language server support, then a lot of interesting thing can be integrated within nushell.
For example, currently I use [librime](https://github.com/rime/librime) as my neovim input method to input non-ascii characters (like this [rime-ls](https://github.com/wlh320/rime-ls)), I think It would be better to integrate this ability in the shell not just in neovim.

![non-ascii](https://github.com/nushell/nushell/assets/3286111/2281b2d5-8ccf-4380-9565-3a5128a5d56f)

The nushell with input method support is awesome.

**Comment by uuhan** [comment]
> Nushell has a LSP that we're [currently working on](https://github.com/nushell/nushell/tree/main/crates/nu-lsp). You can launch it with `nu --lsp`. I can't speak to the nvim tools you're using and whether it's compatible. The nushell LSP works in helix, vscode, and neovim if setup properly, although it's still unfinished.

`nu --lsp` is a client just like cland, rime-ls ... It just integrate the language of nu into something like nvim-lsp.

**Comment by ysthakur** [comment]
> `nu --lsp` is a client

I don't think so, it's a server.

To clarify, you want LSP-powered diagnostics and highlighting and stuff when you type in the shell? Which language's LSP server would be used? `nu --lsp`, or some other server?

**Comment by uuhan** [comment]
> > `nu --lsp` is a client
> 
> I don't think so, it's a server.
> 
> To clarify, you want LSP-powered diagnostics and highlighting and stuff when you type in the shell? Which language's LSP server would be used? `nu --lsp`, or some other server?

In neovim (nvim-lsp), many lsp (server) can be combined into one complement source.

Never mind with the the definition of client or server, I mean the many lsp tools that provides all kinds of completion suggestions.

In your question, I want to use the `rime-ls` lsp tool that provides input method completions and of course the `nu --lsp` completion suggest.

**Comment by alxpettit** [comment]
I actually do wonder how feasible it would be to show LSP data on-the-fly as the user types. I believe that's what @uuhan is saying -- correct me if I'm wrong.

Since the language server is already integrated into the binary, it seems entirely feasible to use the same mechanism to enhance live feedback as the user types into the REPL. Of course, doing it properly would likely require using a raw terminal mode -- which seems like a lot of implementation effort.

**Comment by uuhan** [comment]
> I actually do wonder how feasible it would be to show LSP data on-the-fly as the user types in the REPL. I believe that's what @uuhan is saying -- correct me if I'm wrong.
> 
> Since the language server is already integrated into the binary, it seems entirely feasible to use the same mechanism to enhance live feedback as the user types into the REPL. Of course, doing it properly would likely require using a raw terminal mode -- which seems like a lot of implementation effort.
> 
> Would be easier to have a raw terminal VT handle this, with its own terminal rendering engine. Such a project could also be extended to other REPLs with LSPs.

I think the on-the-fly lsp data popup menu may be only implemented in the raw terminal mode. 

Without raw mode, maybe the complement suggest menu is a good place to show up the lsp data, just like the complement suggest when you press <tab> key.

**Comment by MohsenNz** [comment]
> Nushell has a LSP that we're [currently working on](https://github.com/nushell/nushell/tree/main/crates/nu-lsp). You can launch it with `nu --lsp`. I can't speak to the nvim tools you're using and whether it's compatible. The nushell LSP works in helix, vscode, and neovim if setup properly, although it's still unfinished.

How can I use "nu --lsp" in my neovim ?
e.g I do this for rust: `require'lspconfig'.rust_analyzer.setup{}`

**Comment by MohsenNz** [comment]
Ah, I found :
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#nushell
It seems it has added 4 months ago.

**Comment by jweckman** [comment]
Yes it seems to work by adding this to nvim config:

require'lspconfig'.nushell.setup{}

As with any lsp that is built in to the language binary, setup responsibility should be on each editor separately. IMO this issue can be closed and new ones opened for fixing specific issues encountered using the LSP which is a different matter than having one. After testing it for a bit i think it works great. Go to definition works and any syntax errors show up right away in the editor.

**Comment by fdncred** [comment]
agreed. thanks.
