### ISSUE TITLE
Hello, I'm having an issue on Windows where I can't output using C++'s cout, though C is working normally.

### ISSUE THREAD

**Issue by xMonody** [nushell/nushell#11459]
### Question

Hello, I'm having an issue on Windows where I can't output using C++'s cout, though C is working normally.
![hello](https://github.com/nushell/nushell/assets/76483540/44046e32-9d94-44d2-9dc2-596db2269dba)

**Comment by alxpettit** [comment]
That's really bizarre. Can you post the exact C++ and C code, fenced by codeblocks? Having something easy to replicate and compare would be very useful.

Like so:
\`\`\`c
<your C code>
\`\`\`

**Comment by xMonody** [comment]
```c
#include <stdio.h>
int mian()
{
    printf("hello world");
    return 0;
}
```

**Comment by xMonody** [comment]
c```
#include <stdio.h>
int main()
{
    printf("hello world");
    return 0;
}
```

**Comment by xMonody** [comment]
```c
#include <stdio.h>
int main()
{
printf("hello world");
return 0;
}

**Comment by alxpettit** [comment]
Can I see the C++ code in text, too?

**Comment by xMonody** [comment]
> Can I see the C++ code in text, too?

Yes, it's the same code.
![)BYX78Z45SN1KX)TF K8`D9](https://github.com/nushell/nushell/assets/76483540/bacf5d9e-9b93-4c55-bd05-bfadfed4f40d)

**Comment by alxpettit** [comment]
It does seem like it should be logically equivalent. It's hard to copy-paste from the image, and I am on a totally different OS (NixOS) but I tried to replicate the issue and couldn't. If you were on a Linux system, I would be suggesting to try `strace` to list the system calls being performed by the binary, but I'm not sure how to do that on Windows.

I assume you've tried this same test with other shells and found that the command does what it's supposed to on other shells and terminal windows? You should note that information about the exact software stack is important to solving this. (e.g., is this WSL/WSL2 or Cygwin or something? Are you using Windows Terminal or some third party terminal?)

I don't have any Windows systems, so I don't think I'm gonna be able to test this, but maybe someone else can step up.

**Comment by fdncred** [comment]
I did this in a file called test.cpp and it works fine. Windows has CRLF's so it's good practice to use them both. Also, you may need to use `std::flush` as well. I didn't have to though.
```c++
#include <iostream>
int main(int argc, char** argv) {
    std::cout << "Hello, World!" << "\r\n";
    return 0;
}
```
```nushell
❯ clang++ test.cpp -o test.exe
❯ .\test.exe
Hello, World!
```

One thing I initially stumbled upon was I had another test.exe in my system. so, when i called `test` it was calling the wrong one.
