### ISSUE TITLE
For internal commands, do not attempt to glob expand if the file path is wrapped in quotes.

### ISSUE THREAD

**Issue by alxpettit** [nushell/nushell#11455]
### Describe the bug

For files/dirs named with brackets, I've observed the following characteristics:

`ls` command _without_ `-D` works fine on directories. (But only sometimes, not sure why)

`ls` command _with_ `-D` erroneously fails on directories.

`ls` command _with or without_ `-D` fails on files.

### How to reproduce

1. `touch '[uwu]'`

2. `ls -D '[uwu]'`

3. Observe:

```
Error:   × No matches found for [uwu]
   ╭─[entry #67:1:1]
 1 │ ls -D "[uwu]"
   ·       ───┬───
   ·          ╰── Pattern, file or folder not found
   ╰────
  help: no matches found
```

### Expected behavior

I expect brackets to not change the behavior of `ls`. 

### Configuration

| key                | value                                                                                              |
| ------------------ | -------------------------------------------------------------------------------------------------- |
| version            | 0.88.1                                                                                             |
| branch             |                                                                                                    |
| commit_hash        |                                                                                                    |
| build_os           | linux-x86_64                                                                                       |
| build_target       | x86_64-unknown-linux-gnu                                                                           |
| rust_version       | rustc 1.74.0 (79e9716c9 2023-11-13) (built from a source tarball)                                  |
| cargo_version      | cargo 1.74.0                                                                                       |
| build_time         | 1980-01-01 00:00:00 +00:00                                                                         |
| build_rust_channel | release                                                                                            |
| allocator          | mimalloc                                                                                           |
| features           | dataframe, default, extra, sqlite, trash, which, zip                                               |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, net, query, query json, query web, query xml, regex |

### Additional context

Note that this bug also affects `glob`, but strangely, doesn't affect `mv` or `cp`. Also, substituting single quotes with double quotes or backticks, seems to change nothing.

**Comment by fdncred** [comment]
it's been a known issue for a while now. it's because you're naming files with valid glob patterns. if you want to do that, you need to escape the glob pattern like `ls -D "[[]uwu]"`. I think that's the right syntax but haven't tried it.

**Comment by alxpettit** [comment]
It seems like a pretty big issue. Why is it difficult to fix?

**Comment by fdncred** [comment]
Because we want to use nu-glob globbing for ls. Feel free to dig in and try to change it.

**Comment by alxpettit** [comment]
Interesting. I didn't realize that Nushell applies special expansion logic to the raw string argument for internal commands, on top of the already existing stuff -- but it explains some of the unusual behavior I've noticed with some commands appearing to accept more arguments than they actually do.

I guess I can see the benefit, in that positional arguments cannot be accidentally clobbered. `mv *` in e.g. Bash can produce some maybe surprising behavior.

Seems like if it's going to be setup this way, there has to be some sort of escape hatch that tells the command _this input is wrapped in such and such type of quote, so do not try to expand it_.

**Comment by alxpettit** [comment]
This also should have the benefit of improving behavioral cohesion with external commands. For example, `^echo '*'` does *not* try to expand if it's wrapped in quotes -- only backticks are accepted.

**Comment by paranormal** [comment]
@fdncred I will demur this by pointing out that in 'usual' shell we have some kind of quotes (e.g. '') in which string interpolation is entirely exempted.

**Comment by alxpettit** [comment]
@paranormal Yup! Totally agree! We should be doing the same thing with our globs.

**Comment by fdncred** [comment]
> @fdncred I will demur this by pointing out that in 'usual' shell we have some kind of quotes (e.g. '') in which string interpolation is entirely exempted.

I believe we have backtick quotes that do not support string interpolation but single and double quotes do.
