### ISSUE TITLE
Disable term colors when it's not supported

### ISSUE THREAD

**Issue by baehyunsol** [nushell/nushell#11464]
### Related problem

I'm not sure whether it's a bug or a feature request. In some environments where term-colors are not supported, nushell should turn off term-colors.

Below are screenshots of [neovide](https://github.com/neovide/neovide) running cargo and nu. My neovide settings do not support term-coloring. Cargo and Nu both generate colored-outputs on other platforms like alacritty or gnome shell. In neovide, Cargo knows that it cannot use colors, so it outputs plain texts. But Nu still tries to color the outputs, which results hard-to-read texts.

![20240102113306](https://github.com/nushell/nushell/assets/47506131/f337db60-5bd7-4909-8217-44a64ed4fbc1)

![20240102113359](https://github.com/nushell/nushell/assets/47506131/169a0b2f-42f4-4121-ac65-e78c17003568)

### Describe the solution you'd like

Check whether the current environment supports term-coloring before coloring the output.

**Comment by baehyunsol** [comment]
It seems like [colored](https://github.com/colored-rs/colored) and [termcolor](https://github.com/BurntSushi/termcolor) check whether they're writing to a terminal or not. But I can't find that kind of check in [nu-ansi-term](https://github.com/nushell/nu-ansi-term).

I need further investigation...

**Comment by nibon7** [comment]
> They don't appear to be checking if they're writing to a terminal.

`supports-color`  does check the terminal.

https://github.com/zkat/supports-color/blob/dece38fdbc04d6c29cde18fc9303e6118db58ab4/src/lib.rs#L91-L119

**Comment by fdncred** [comment]
@nibon7 we could use something like that but it would also need to support NO_COLOR.

**Comment by nibon7** [comment]
It has checked `NO_COLOR` env in the `env_force_color`.

https://github.com/zkat/supports-color/blob/dece38fdbc04d6c29cde18fc9303e6118db58ab4/src/lib.rs#L92

**Comment by fdncred** [comment]
ah, i missed the env_nocolor() part. seems like that function and the collateral functions would work for us. the trick is calling it in the right places like in grid and all the other places.

**Comment by nibon7** [comment]
use `support_colors` to determine whether nushell should use ansi colors

![Screenshot from 2024-01-06 11-41-36](https://github.com/nushell/nushell/assets/15247421/da7cc446-1825-44c5-9c14-b4f49fd17ea5)

**Comment by klmcwhirter** [comment]
Note https://github.com/nushell/nushell/pull/11494#issuecomment-2480745176

I describe at some length what I am experiencing running standalone scripts in a terminal with a "light" theme. The output is unreadable.
