### ISSUE TITLE
list update index warning error "bug"

### ISSUE THREAD

**Issue by ZanovelloAlberto** [nushell/nushell#11462]
### Describe the bug

![image](https://github.com/nushell/nushell/assets/46749229/fe63bd41-6145-4d81-acde-e3f45d715c21)

### How to reproduce

`[0] | update 1 99`

### Expected behavior

if it tell you that the max value is 0 and i put 1 it should work
"the problem is probably just the number in the warning"

### Configuration

linux

**Comment by fdncred** [comment]
All of these fail in the latest main. To update something the column has to exist.

**Comment by ZanovelloAlberto** [comment]
> All of these fail in the latest main. To update something the column has to exist.

what do you mean? will it be impossible to use `update` with a `list` as input?

**Comment by fdncred** [comment]
Update currently works by index like this. i.e. for lists, the first argument after update is the index in the list, which is 0 on a list length of 1.
```nushell
❯ [1] | update 0 2
╭───┬───╮
│ 0 │ 2 │
╰───┴───╯
```
or this one that's listed in the help
```nushell
> [1 2 3] | update 1 {|i| $i + 2 }
  ╭───┬───╮
  │ 0 │ 1 │
  │ 1 │ 4 │
  │ 2 │ 3 │
  ╰───┴───╯
```

**Comment by ZanovelloAlberto** [comment]
this poin of the issue was this case 
```
[1] | update 1 2                                                                                                                                                                           
╭───┬───╮
│ 0     │ 1     │
│ 1     │ 2     │
╰───┴───╯
```
![image](https://github.com/nushell/nushell/assets/46749229/0c19fb22-25ce-4835-9eb0-eb7a8d2d851a)
you see work with (index = 1) even if the error says that the max is 0

![image](https://github.com/nushell/nushell/assets/46749229/d5bd826c-3562-47bf-863a-72335dd06c0d)

**Comment by fdncred** [comment]
> this poin of the issue was this case

```nushell
[1] | update 1 2 
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 2 │
╰───┴───╯
```

There is no `1` index, so it can't update it in the latest version.

This does not work any longer.
```nushell
❯ [1] | update 1 2 
Error: nu::shell::access_beyond_end

  × Row number too large (max: 0).
   ╭─[entry #51:1:1]
 1 │ [1] | update 1 2
   ·              ┬
   ·              ╰── index too large (max: 0)
   ╰────
```
It works in the latest version
```nushell
❯ nu -v
0.88.2
❯ [1 2 3] | update 1 {|i| $i + 2} 
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 4 │
│ 2 │ 3 │
╰───┴───╯
```
