### ISSUE TITLE
make `run-external` as `cargo run` like interface with `--` flag

### ISSUE THREAD

**Issue by TD-Sky** [nushell/nushell#11474]
### Related problem

When we wrap a command in `()` for writing it in multi lines in the middle part of statements, its output will be suppressed:

```nushell
def foo [] {
    (^echo
        bar)
    echo zoo
} # output: zoo
```

In practice, I wish the following long command  can print its output and error to current stdout and stderr:

```nushell
(docker run -it --rm
    -v $"(pwd):/workdir"
    -v $"($env.HOME)/.cargo/git:/root/.cargo/git"
    -v $"($env.HOME)/.cargo/registry:/root/.cargo/registry"
    $nightly_image
    cargo build --release -vv --target=x86_64-unknown-linux-musl)
```
 
but the only solution is `run-external` which looks unnatural.

```nushell
(run-external docker run '-it' '--rm'
    '-v' $"(pwd):/workdir"
    '-v' $"($env.HOME)/.cargo/git:/root/.cargo/git"
    '-v' $"($env.HOME)/.cargo/registry:/root/.cargo/registry"
    $nightly_image
    cargo build "--release" '-vv' '--target=x86_64-unknown-linux-musl')
```

### Describe the solution you'd like

Collects all arguments after `--` like `cargo run`:

```nushell
(run-external -- docker run -it --rm
    -v $"(pwd):/workdir"
    -v $"($env.HOME)/.cargo/git:/root/.cargo/git"
    -v $"($env.HOME)/.cargo/registry:/root/.cargo/registry"
    $nightly_image
    cargo build --release -vv --target=x86_64-unknown-linux-musl)
```

### Describe alternatives you've considered

We may also need the same effect for non-external command, so a multi-line-serving syntax would be better:

 ```nushell
^(docker run -it --rm
    -v $"(pwd):/workdir"
    -v $"($env.HOME)/.cargo/git:/root/.cargo/git"
    -v $"($env.HOME)/.cargo/registry:/root/.cargo/registry"
    $nightly_image
    cargo build --release -vv --target=x86_64-unknown-linux-musl)$
```

`^( )$` do nothing except extending command to multi-line.

### Additional context and details

Double dash support:
https://github.com/nushell/nushell/issues/10939

**Comment by texastoland** [comment]
I thought only `do` did this 🙀 Another alternative could be `do` consumes output but subexpressions don't.
