### ISSUE TITLE
Delete history entry

### ISSUE THREAD

**Issue by giggio** [nushell/nushell#11470]
### Related problem

We can't delete a specific history entry today, only clear it entirely.

### Describe the solution you'd like

Add subcommand to `history` that allows to delete a history entry.

### Describe alternatives you've considered

Use sqlite directly, which is not obvious, or create custom commands. I have done so: https://github.com/giggio/nuscripts/blob/main/scripts/history-command.nu

### Additional context and details

This is the clear history PR: #2720.

**Comment by fdncred** [comment]
> We can't delete a specific history entry today, only clear it entirely.

While we do not yet provide a command to do this, it's an overstatement to say that you can't delete an entry.

If you're using the sqlite history, you can always try and delete an entry with something like this.
```nushell
open $nu.history-path | query db "delete from history where id = 5"
```
where 5 is the id you wand to delete.
You can see the schema like this
```nushell
open $nu.history-path | schema | get tables | table -e
```
and see the last 5 entries like this
```nushell
open $nu.history-path | get history | last 5
```

**Comment by giggio** [comment]
That's really nice, I had no idea it was possible to manipulate sqlite like that with Nushell!
But this is not at all ergonomic, especially for new users, also because Nushell already has a `history` command. It feels incomplete.
As a temporary workaround it would be nice to add this to the `history` command docs.

**Comment by fdncred** [comment]
How would you use a `history delete` command? You'd have to know which item you want to delete which makes me think a custom command could be used.

**Comment by giggio** [comment]
I think that `history delete <id>` should be enough, it would solve my initial needs.

**Comment by fdncred** [comment]
Then it seems like this is pretty close to what you need. It just leaves the task of finding the id to you, which you could write another custom command if needed.

```nushell
# Delete a history item with the provided ID
def 'history delete' [id: int] {
  open $nu.history-path | query db "delete from history where id = ($id)"
}
```
I haven't tested it, but I think it should work.

**Comment by fdncred** [comment]
Here's a `history search` command that I've been using for a while. I tweaked it to have the id, which is listed here as item_id.
```nushell
def "history search" [
    str: string = '' # search string
    --cwd(-c) # Filter search result by directory
    --exit(-e): int = 0 # Filter search result by exit code
    --before(-b): datetime = 2100-01-01 #  Only include results added before this date
    --after(-a): datetime = 1970-01-01 # Only include results after this date
    --limit(-l): int = 25 # How many entries to return at most
    ] {
    if $cwd == false {
        history --long
        | where start_timestamp != ""
        | update start_timestamp {|r| $r.start_timestamp | into datetime}
        | where command =~ $str and exit_status == $exit and start_timestamp > $after and start_timestamp < $before
        | first $limit
        | select item_id command start_timestamp cwd duration exit_status
    } else {
        history --long
        | where start_timestamp != ""
        | update start_timestamp {|r| $r.start_timestamp | into datetime}
        | where command =~ $str and cwd == $env.PWD and exit_status == $exit and start_timestamp > $after and start_timestamp < $before
        | first $limit
        | select item_id command start_timestamp cwd duration exit_status
    }
}
```

**Comment by giggio** [comment]
Those are really cool.

> Then it seems like this is pretty close to what you need. It just leaves the task of finding the id to you, which you could write another custom command if needed.

You missed the interpolation. It should be:

```nushell
def 'history delete' [id: int] {
  open $nu.history-path | query db $"delete from history where id = ($id)"
}
```

But it doesn't work. `history` is currently showing an incorrect id. I guess it is generating them, instead of using the one from the db. So, when you do `history delete 455`, it will not necessarily delete the one you saw from `history`, which could be problematic.
You'd have to delete row 455, not id 455.

**Comment by giggio** [comment]
A quick fix. Still, maybe we should fix the id?

```nushell
def 'history delete' [id: int] {
  open $nu.history-path | query db $"delete from history where id = \(select id from history order by id LIMIT 1 OFFSET ($id))"
}
```

The problem is that if you manipulate the results, the id becomes incorrect. Like so:

```nushell
history | last 10
```

This will show you 10 lines in a table, with ids from 0 to 9.

If you then `history delete 8`, the incorrect item will be deleted from the table.

**Comment by fdncred** [comment]
I'm not sure I understand. If I do this,
```nushell
❯ history search ls
```
I get this. Then you can see that I did a query for item_id 75, which is the database id column.
![image](https://github.com/nushell/nushell/assets/343840/2f123396-be4a-409d-ac44-ad31f5996f1a)
So, it seems right to me.

**Comment by giggio** [comment]
I don't have the command `history search`. I'm on nushell 0.88.1.

**Comment by giggio** [comment]
Ok, right, the `#` is not the id column. This just makes it even more confusing. :)
So, I'd use `history --long` to get the id, then use `history delete` to delete it, right?
Also: I believe your `history search` should also be added to nushell, or some form of search like it.

**Comment by giggio** [comment]
@fdncred Thanks for the inspiration for the commands, I have added them to my files. If anyone is interested:
https://github.com/giggio/nuscripts/blob/main/scripts/history-command.nu

I still believe this should be in Nushell, not necessarily the implementation I just did.

**Comment by fdncred** [comment]
i agree, some form of history search should be in nushell. it'll probably get there someday. thanks.
