### ISSUE TITLE
Is it a feature or a bug? : "`which` ignores commands interpreted by cmd.exe on Windows"

### ISSUE THREAD

**Issue by yukitomoda** [nushell/nushell#11473]
### Question

`which` ignores commands which are specially interpreted by cmd.exe on Windows (e.g. `echo`, `mklink`).
Is it a feature or a bug?

I think `which` should list them because these commands run some program (cmd.exe). But I also think ignoring them is reasonable because these are netiher program file, alias nor custom command.

### Additional context and details

```nu
~\work\tmp
❯ which ^assoc ^cls ^echo ^ftype ^mklink ^pause ^start ^ver ^vol
╭────────────╮
│ empty list │
╰────────────╯
```

The full list of "commands which are specially interpreted by cmd.exe" is here: https://github.com/nushell/nushell/blob/49ab559992fa3c17a86a66c18b40fb8bb9c01859/crates/nu-command/src/system/run_external.rs#L206

**Comment by fdncred** [comment]
I'm pretty sure it's on purpose. Nushell wouldn't have no idea of cmd.exe built-in commands.

**Comment by yukitomoda** [comment]
> I'm pretty sure it's on purpose. Nushell wouldn't have no idea of cmd.exe built-in commands.

To my understanding, nushell determine wheter a command should be treated as a cmd.exe built-in command or not by `CMD_INTERNAL_COMMANDS`. Can we tell `which` about this?

**Comment by yukitomoda** [comment]
Hmm, it looks like pretty complicated catching commands executed via cmd.exe. (executing bat files, etc)
No now I agree with ignoring commands executed via cmd.exe...

**Comment by fdncred** [comment]
should we close this then?

**Comment by yukitomoda** [comment]
> should we close this then?

sorry, I forgot closing this.

thanks!
