### ISSUE TITLE
Nushell + Zoxide Bug

### ISSUE THREAD

**Issue by bootdme** [nushell/nushell#11482]
### Question

Terminal: kitty 0.31.0
Nu: 0.88.1
OS: MacOS 14.3 Beta (23D5033f)

Whenever I open up a new tab in my kitty terminal, my nushell works when I open a new tab from my home directory.

However, when it's not from the home directory, I get this error within the new tab:

```
Last login: Thu Jan  4 13:29:46 on ttys000
Error: nu::shell::external_command

  × External command failed
     ╭─[/Users/bootdme/Library/Application Support/nushell/env.nu:125:1]
 125 │
 126 │ zoxide init nushell | save -f ~/dotfiles/nushell/.zoxide.nu
     · ───┬──
     ·    ╰── did you mean 'hide'?
     ╰────
  help: No such file or directory (os error 2)

Error: nu::shell::external_command

  × External command failed
    ╭─[/Users/bootdme/dotfiles/nushell/.zoxide.nu:15:1]
 15 │   $env.config = ($env.config | update hooks.env_change.PWD ($env.config.hooks.env_change.PWD | append {|_, dir|
 16 │     zoxide add -- $dir
    ·     ───┬──
    ·        ╰── did you mean '__zoxide_z'?
 17 │   }))
    ╰────
  help: No such file or directory (os error 2)
```

Why does this happen and how do I approach this to fix?

Thank you

**Comment by ysthakur** [comment]
Are you making sure to add zoxide to your path before you do `zoxide init`?

**Comment by bootdme** [comment]
> Are you making sure to add zoxide to your path before you do `zoxide init`?

Do I need to specifically add zoxide to my path? I've installed zoxide via cargo and have `$env.PATH = ($env.PATH | split row (char esep) | prepend '.cargo/bin')` already added.

**Comment by fdncred** [comment]
looks like you're not setting the path correctly. `prepend '.cargo/bin'` looks wrong to me. It probably should be `~/.cargo/bin`.

**Comment by ysthakur** [comment]
Oh, then I guess it should be in your path. Just as a sanity check, though, could you print out the path before you run `zoxide init`? I guess you must have successfully run it at least once, because the `.zoxide.nu` file exists.

Also, are you sure it's supposed to be `./cargo/bin` and not `~/.cargo/bin` or something similar?

**Comment by bootdme** [comment]
Thank you @fdncred & @ysthakur.

Can't believe it was that easy...
