### ISSUE TITLE
history --clear crashes nu when isolation enabled

### ISSUE THREAD

**Issue by texastoland** [nushell/nushell#11502]
### Describe the bug

`history --clear` crashes `nu` on relaunch when isolation enabled in `config.nu`.

### How to reproduce

1. Enable SQLite history with isolation
2. `history --clear`
3. 1 DB file is deleted but not all
4. Relaunch Nushell
5. Immediately crashes
6. Delete DB artifacts
7. Relaunch successfully

### Expected behavior

No crash.

### Configuration

| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.88.1                                         |
| branch             |                                                |
| commit_hash        |                                                |
| build_os           | macos-x86_64                                   |
| build_target       | x86_64-apple-darwin                            |
| rust_version       | rustc 1.74.0 (79e9716c9 2023-11-13) (Homebrew) |
| cargo_version      | cargo 1.74.0                                   |
| build_time         | 2023-12-14 17:14:47 +00:00                     |
| build_rust_channel | release                                        |
| allocator          | mimalloc                                       |
| features           | dataframe, default, sqlite, trash, which, zip  |
| installed_plugins  |                                                |

**Comment by fdncred** [comment]
This is a known issue. I'd be surprised if there isn't an issue for it already.

**Comment by texastoland** [comment]
I searched but didn't find it. Happy to close as duplicate if you know?

**Comment by fdncred** [comment]
Maybe I'm thinking of these
https://github.com/nushell/nushell/pull/11049
https://github.com/nushell/nushell/pull/9575

**Comment by texastoland** [comment]
You found it #7991 again 👍🏼
