### ISSUE TITLE
How do I check how many files there are in a directory?

### ISSUE THREAD

**Issue by 107295472** [nushell/nushell#11506]
### Question

You can also check how many documents are there in which year?

**Comment by fdncred** [comment]
1. for one dir you can do `ls | length`.
2. for a recursive count you can do `ls **/* | length`
3. group by year `ls **/* | group-by --to-table { get modified | format date '%Y'}`

**Comment by 107295472** [comment]
Thanks

**Comment by 107295472** [comment]
rm | where type == file and modified < ((date now) - 80day)

**Comment by 107295472** [comment]
> 1. for one dir you can do `ls | length`.
> 2. for a recursive count you can do `ls **/* | length`
> 3. group by year `ls **/* | group-by --to-table { get modified | format date '%Y'}`
def dellog [d:int] {
    ls | where type == file and modified < ((date now) - $d) | each { rm $in.name } | null
}  How to splice this d variable?

**Comment by fdncred** [comment]
This is ambiguous. What is `- 5` supposed to mean? minus 5 days, 5 minutes, 5 years?d
```nushell
(date now) - 5
```

In order to do date math, you need to have a date or a duration.
```nushell
def test [d: int] {
  let duration = $"($d)day" | into duration
  (date now) - $duration
}
```

**Comment by 107295472** [comment]
Thanks
