### ISSUE TITLE
`(run-external "false" | complete)` broke, stared returning `nothing` between `0.87.1` and `0.88.0+`

### ISSUE THREAD

**Issue by Veetaha** [nushell/nushell#11518]
### Describe the bug

Behaviour on `0.87.1`:
```nushell
~/work/actions$ (run-external "false" | complete)
╭───────────┬───╮
│ exit_code │ 1 │
╰───────────┴───╯
```

Behavior of `0.88.0` and `0.89.0`:

```nushell
~/work/actions$ (run-external "false" | complete)
```
(`nothing` is returned)

### Expected behavior

I expected that the expression `(run-external "false" | complete)` always returns a table with `{ exit_code: 1 }`. It should do that for any subprocess. Not only `false` unix utility.

### Configuration

| key                | value                                                   |
| ------------------ | ------------------------------------------------------- |
| version            | 0.89.0                                                  |
| branch             |                                                         |
| commit_hash        | 2c1560e281d65a50d90b30c42006755b364b4928                |
| build_os           | linux-x86_64                                            |
| build_target       | x86_64-unknown-linux-gnu                                |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                     |
| rust_channel       | 1.73.0-x86_64-unknown-linux-gnu                         |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                     |
| build_time         | 2024-01-09 20:27:07 +00:00                              |
| build_rust_channel | release                                                 |
| allocator          | mimalloc                                                |
| features           | default, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  | from eml, from ics, from ini, from vcf                  |

### Additional context

Note that succesful command exit status works on every version consistently:

```nushell
~/work/actions$ (run-external "true" | complete)                                                                      
╭───────────┬───╮
│ exit_code │ 0 │
╰───────────┴───╯
```

**Comment by Veetaha** [comment]
This is blocking my update to the latest nutshell. Still an issue in 0.91

**Comment by IanManske** [comment]
This should be working on 0.92, feel free to reopen if there's still any issues.
