### ISSUE TITLE
Case insensitive sort 

### ISSUE THREAD

**Issue by charleschege** [nushell/nushell#1151]
Currently nu is sorting files or directories that begin with uppercase letter first then proceeds to sort those with lowercase letters. Make nu able to sort case insensitively like an OS sort

**Comment by Aloso** [comment]
The sorting is not only case insensitive, but also **language agnostic**. For instance, umlauts like äöüß appear _after_ English letters.

A better sort order would be:

```
<special characters>
0 1 2 3 4 5 6 7 8 9
A a Á á À à Å å Ä ä ... B b ... S s ẞ ß ...
Α α Β β Γ γ Δ δ ...
А а Б б В в Г г ...
...
```

It would be even better if the order was [natural](https://en.wikipedia.org/wiki/Natural_sort_order), e.g.

```
3/3
7/1
12/4
12/11
```

**Comment by JosephTLyons** [comment]
I'm going to go ahead and close this, since the original request has been merged in (https://github.com/nushell/nushell/pull/2225), but feel free to open a new issue if there are additional sorts wanted
