### ISSUE TITLE
Strange behavior when passing strings with double-asterisks to external commands

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#11517]
### Describe the bug

`"**"` and `$"**"` should, as far as I can tell, result in the same string result.  There's nothing there to be interpolated.  And that's true when working with Nu commands or a pipeline.  However, when the interpolated string is used as an argument to an external command, it passes an empty string instead.

This also seems to be triggered when storing even a non-interpolated string in a variable and then using the variable as the external argument.

Easier to understand via code ...

### How to reproduce

Commands below are on Linux (WSL/Ubuntu 22.04).  Not quite sure what external could be used to repro this on Nu-Windows.

```Nushell
> # Works
> ^echo "foo**bar"
foo**bar
> # Returns blank line
> ^echo $"foo**bar"

> # The linefeed is coming from the echo, of course.  The Nushell value seems completely empty:
> ^echo $"foo**bar" | hd
00000000  0a                                                |.|
00000001
```

The above examples behave the same with single quoted strings.

The behavior is also reproducible when storing even a non-interpolated string in a variable:

```Nushell
> let str1 = "foo********bar" # Doesn't work
> let str2 = $"foo********bar" # Doesn't work
> let str3 = $"foo*bar" # Works correctly
> (^echo $str1) == ""
true
> (^echo $str2) == ""
true
> (^echo $str3) == ""
false
> (^echo $str3) == "foo*bar"
true
```

Note that passing the string as part of the pipeline, or using it as an argument for a Nushell internal both work:

```Nushell
> let str1 = "foo********bar"
> let str2 = $"foo********bar"
> echo $str1
foo********bar
> echo $str2
foo********bar
> $str2 | ^cat
foo********bar
```

### Expected behavior

I expect to be able to pass a string with double-asterisks to an external command.  At the moment, I haven't found a workaround at all.

My primary use case here is to pass a Nushell table in WSL into Powershell to put it on the Windows clipboard.  The following works for anything without a double-asterisks:

```Nushell
def wslClipTable [ ] {

  pwsh.exe -c $"Set-Clipboard @'
($in | table | ansi strip)
'@"

}
```

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.88.1                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.74.0 (79e9716c9 2023-11-13) (built from a source tarball)               |
| cargo_version      | cargo 1.74.0                                                                    |
| build_time         | 1980-01-01 00:00:00 +00:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | mimalloc                                                                        |
| features           | dataframe, default, extra, sqlite, trash, which, zip                            |
| installed_plugins  | from eml, from ics, from ini, from vcf, query, query json, query web, query xml |

**Comment by fdncred** [comment]
My guess is that it's seeing ** and trying to do some globbing. I could be wrong. We'd have to look into string interpolation.

**Comment by weirdan** [comment]
Looks like it's fixed:

```console
$ ^echo "foo**bar"
foo**bar

$ ^echo $"foo**bar"
foo**bar

$ let str1 = "foo********bar"

$ let str2 = $"foo********bar"

$ let str3 = $"foo*bar"

$ ^echo $str1
foo********bar

$ ^echo $str2
foo********bar
$ ^echo $str3
foo*bar
```
