### ISSUE TITLE
`get` built-in is not case sensitive

### ISSUE THREAD

**Issue by Agent-E11** [nushell/nushell#11527]
### Describe the bug

If there are keys/columns that are the same but with different cases, the `get` command cannot distinguish them

### How to reproduce

```nu
> { ABC: 1 abc: 2 } | get ABC
2 # This is the wrong value
> { ABC: 1 abc: 2 } | get abc
2 # This is correct

# $in can distinguish between them

> { ABC: 1 abc: 2 } | $in.ABC
1 # Correct
> { ABC: 1 abc: 2 } | $in.abc
2 # Correct
```

### Expected behavior

`get ABC` and `get abc` should return different values in the example above (identical to `$in`)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.88.1                                   |
| branch             |                                          |
| commit_hash        | fd56768fdcc1acbebcb75745600fc7419f72833d |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13)      |
| rust_channel       | 1.72.1-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.72.1 (103a7ff2e 2023-08-15)      |
| build_time         | 2023-12-14 17:53:48 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
if we're going to make a change like this, we can't just do it to `get`, we've have to check what `select` does too for consistency and maybe other commands like `update`, `upsert` should be looked at too since they call out a named column. I'm guessing there are other commands.

**Comment by Agent-E11** [comment]
@fdncred I just realized that there is a `-s` flag for `get`, which makes it case sensitive. Does that mean the default case-insensitivity is intended? I might want to just close this issue

**Comment by fdncred** [comment]
> @fdncred I just realized that there is a `-s` flag for `get`, which makes it case sensitive. Does that mean the default case-insensitivity is intended? I might want to just close this issue

oh ya, i forgot about that too. LOL. unfortunately, the same -s doesn't exist on select.

we can close this for now since the original issue was about get. thanks!

**Comment by Agent-E11** [comment]
It looks like `select` works fine:

```nu
~> let t = [[abc ABC aBc]; [this is thing] [it isnt nothing]] ╭───┬──────┬──────┬─────────╮
│ # │ abc  │ ABC  │   aBc   │
├───┼──────┼──────┼─────────┤
│ 0 │ this │ is   │ thing   │
│ 1 │ it   │ isnt │ nothing │
╰───┴──────┴──────┴─────────╯
```
```
~> $t | select abc
╭───┬──────╮
│ # │ abc  │
├───┼──────┤
│ 0 │ this │
│ 1 │ it   │
╰───┴──────╯
~> $t | select ABC
╭───┬──────╮
│ # │ ABC  │
├───┼──────┤
│ 0 │ is   │
│ 1 │ isnt │
╰───┴──────╯
~> $t | select aBc
╭───┬─────────╮
│ # │   aBc   │
├───┼─────────┤
│ 0 │ thing   │
│ 1 │ nothing │
╰───┴─────────╯
```

**Comment by fdncred** [comment]
My point is that it doesn't work the same. By default, `get` seems case-insensitive and `select` seems case-sensitive. What makes it worse is that there may be no way to make `select` work insensitively.
