### ISSUE TITLE
Support for self-closed tags in `to xml`

### ISSUE THREAD

**Issue by jameschensmith** [nushell/nushell#11524]
### Related problem

As a C# developer, I deal with a fair share of XML files. There is quite a bit of self-closed tag usage in these XML files ([example](https://github.com/dotnet/sdk/blob/2b728f5335cd4f8d1f9f07e2c4e24e3e40e56054/Directory.Packages.props)). When making changes to these files with Nushell, these tags get converted to start & end tags. When using `to xml --indent {int}`, the file can get quite long.

### Describe the solution you'd like

1. Preserving existing self-closed tags would be great, but might not be feasible and would touch both `from xml` and `to xml`.
2. It would be nice if `to xml` had a flag which could convert all empty tags to self-closed.  I believe libxml2 has a configuration like this that is the _opposite_ (i.e., no empty tags).

### Describe alternatives you've considered

I've resorted to fixing the tags post-`to xml` with something like the following:
```nu
str replace -a -r -m '<([^!/>][^>]*)>\n\s+</[^>]+>' '<$1 />'
```

**Comment by fdncred** [comment]
Thanks for the issue.
/cc @NotLebedev
