### ISSUE TITLE
Need help uninstalling

### ISSUE THREAD

**Issue by darioque** [nushell/nushell#11543]
### Question

Noob here, installed nushell on windows 10 and found some things I didn't like so uninstalled (all with winget). Long story short, I'm trying to run some powershell scripts from my terminal and they seem to run with nushell
![image](https://github.com/nushell/nushell/assets/76440563/485af861-d3dc-4f42-ada6-39a43de04f3e)

This is terminal with the powershell profile and have tried directly running powershell. Already rebooted. Any help? Thanks

**Comment by fdncred** [comment]
it looks to me like you were using nushell when you uninstalled it, which doesn't work on windows because you can't remove a program that is in use. so now, you have some crippled half installed/uninstalled build of nushell.

You should find where nushell is installed and rename that folder, but of course, you can't be using nu.exe when that happens otherwise you'll get a sharing violation.

**Comment by darioque** [comment]
> it looks to me like you were using nushell when you uninstalled it, which doesn't work on windows because you can't remove a program that is in use. so now, you have some crippled half installed/uninstalled build of nushell.
> 
> You should find where nushell is installed and rename that folder, but of course, you can't be using nu.exe when that happens otherwise you'll get a sharing violation.

There's a small possibility that happened but I used search everything and deleted anything related to nushell and still nothing. I also tried installing and uninstalling nushell again (only using cmd) and same thing happens.

**Comment by hustcer** [comment]
Did you restart your terminal? How did you run your powershell script?

**Comment by darioque** [comment]
> Did you restart your terminal? How did you run your powershell script?

Restarted terminal and rebooted pc.

I have a directory with .ps1 scripts in my path so I can just run them by using their name from powershell. Up to today they worked perfectly. But even if I go to the folder and hit run with powershell on the .ps1 files they quickly open and close a pwsh and I can clearly see this nushell parser error.

**Comment by hustcer** [comment]
Does `pwsh your-script.ps1` work in your terminal?

**Comment by darioque** [comment]
> Does `pwsh your-script.ps1` work in your terminal?

![image](https://github.com/nushell/nushell/assets/76440563/204d05b3-5276-488b-9a16-05b1419fed98)

**Comment by darioque** [comment]
I have another windows 10 pc or an old backup of this one but I don't even know what to restore. Given that i already tried reinstalling powershell, I'm guessing the issue is somewhere else.

**Comment by hustcer** [comment]
I can try to do some help after 1.5 hours, please contact me from discord, username： hustcer

**Comment by fdncred** [comment]
it's pretty clear to me that nushell hasn't been uninstalled. if it were, you wouldn't be getting nushell errors. so nu.exe is still on your system. i use voidtools everything to find files throughout my system. perhaps you should use something like that to fine where nu.exe is at, then you can delete the folder.

**Comment by darioque** [comment]
> it's pretty clear to me that nushell hasn't been uninstalled. if it were, you wouldn't be getting nushell errors. so nu.exe is still on your system. i use voidtools everything to find files throughout my system. perhaps you should use something like that to fine where nu.exe is at, then you can delete the folder.

Hustcer cracked it, it was indeed uninstalled (so I had that right at least haha). The script that was failing was an ssh to a remote machine to send a command there. In that one I also had nu installed, so the message I was receiving locally was the ssh'd nu. Sorry!

**Comment by hustcer** [comment]
Never mind, It's really a very subtle imperceptible problem
