### ISSUE TITLE
ps accepts arguments but shouldn't

### ISSUE THREAD

**Issue by djc** [nushell/nushell#1154]
**Describe the bug**
The `ps` command appears to accept mode arguments even though they are not functional.

**To Reproduce**
1. Run `ps aux`
2. Run `ps`

**Expected behavior**
Expected output from 1. and 2. to differ by some metrics.

**Configuration (please complete the following information):**
 - OS: macOS
 - Version: master
 - Optional features (if any): `stable`

**Comment by jonathandturner** [comment]
This should be fixed in more recent versions
