### ISSUE TITLE
`from json` doesn't throw an error on invalid JSON

### ISSUE THREAD

**Issue by Veetaha** [nushell/nushell#11548]
### Describe the bug

The following explains it:
```nu
> '<blah $%}{o' | from json  
<blah $%}{o
```

### Actual behavior

`from json` above doesn't throw an error, but returns the input string 

### Expected behavior

I expected `from json` to throw an error when it receives non-JSON syntax.

## Use case

I want to rely on JSON parsing erroring behaviour to write a function that accepts a string, parses it as JSON if it is a valid JSON, and recurses down the JSON object to parse its properties as embedded JSON strings to eventually un-embed all strings from the object.

For example

I can't get even this part of the code in my script working, because it is stuck at re-parsing `foo` in an infinite recursion, though it should fail, go to `catch` block and terminate the recursion.

```nu
def unembed [] {
    let val  = $in
    let type = ($val | describe --detailed).type

    if $type == "string" {
        let val = try {
            print --stderr $"Parsing ($val)"
            $val | from json
        } catch {
            return $val
        }

        print --stderr  $"Parsed ($val)"

        return ($val | unembed)
    }

    # other code that iterates over a record or a list not relevant for the reproduction...
}

'foo' | unembed
```

### Configuration

| key                | value                                                   |
| ------------------ | ------------------------------------------------------- |
| version            | 0.89.0                                                  |
| branch             |                                                         |
| commit_hash        | 2c1560e281d65a50d90b30c42006755b364b4928                |
| build_os           | linux-x86_64                                            |
| build_target       | x86_64-unknown-linux-gnu                                |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                     |
| rust_channel       | 1.73.0-x86_64-unknown-linux-gnu                         |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                     |
| build_time         | 2024-01-09 20:27:07 +00:00                              |
| build_rust_channel | release                                                 |
| allocator          | mimalloc                                                |
| features           | default, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  | from eml, from ics, from ini, from vcf                  |

**Comment by Veetaha** [comment]
@fdncred 
Yeah, having `hjson` support is a good feature. However, having the strictness of JSON is also useful, just like in the use case that I mentioned in the issue body. Otherwise, I don't know a good solution for my use case. It's as if need to write my own JSON parser in `nushell` that throws an error on bare (unquoted) HJSON-like strings.

If backwards compatibility is a concern for `from json` consider adding a flag `from json --strict` that would parse the strict using the strict JSON specification (basically `serde_json`).

If backwards compatibility is not a concern we can make `from json` accept only strict JSON syntax. This is what one would expect, because by its name and docs there is no mentioning of HJSON, and when people think JSON they probably think "string JSON".

For the cases where some flexibility is allowed there can be a separate command `from hjson` or a flag `from json --human`

**Comment by fdncred** [comment]
I understand your points. I'd support having a `from json --strict` flag for people who need that functionality. I think the default should be like it is now, permissive. Bare words are a key concept in nushell that I don't want to see removed. It's just too convenient and I'd hate to see the default changed. 

There could also be a debate about having `from json` and `from hjson` but I think the flag above is better for now.

**Comment by IanManske** [comment]
`from json --strict` was just added in version `0.90.0` :)
