### ISSUE TITLE
"from json" does not take into account colors or special glyphs

### ISSUE THREAD

**Issue by heuristicAL** [nushell/nushell#11554]
### Related problem

I'm trying to read in the json output from an open branch of [eza](https://github.com/eza-community/eza/pull/783).

One peculiarity of it is that it includes coloring for the output as well as optional Nerd Font icons. The `from json` nushell command ignores both the color as well as the icons.

Example json output from eza:
<img width="1919" alt="image" src="https://github.com/nushell/nushell/assets/6423582/b0a20247-5e78-4130-aa1a-7754fada5ef6">

Result of importing that into nushell's `from json` (notice the missing colors and icons. The icons don't even show up as empty array elements, they are just stripped out entirely):
<img width="560" alt="image" src="https://github.com/nushell/nushell/assets/6423582/c3737b2d-e7eb-4151-b277-b4712211e6c5">

Example of my attempt to parse the data properly into a table (notice no coloring plus, as mentioned, no icons):
<img width="1280" alt="image" src="https://github.com/nushell/nushell/assets/6423582/cbb1593d-7c06-467f-bae2-491bdf92def4">

### Describe the solution you'd like

I have no idea how possible this is, but two improvements could be made:
1.  Keeping the color of the text that is input into `from json` so that it is still there in the output (or at least optionally available using a flag?)
2. Keeping non-standard glyphs as they go through the pipe.

**Comment by DonSheddow** [comment]
I think this is because eza disables color when it detects that stdout is a pipe. Have you tried using `--color=always`?

**Comment by fdncred** [comment]
yup, i just tested this @DonSheddow is correct. Thanks!!
![image](https://github.com/nushell/nushell/assets/343840/4bd8deaf-b6fa-438d-9ac7-3f3b70553bff)

**Comment by heuristicAL** [comment]
You 2 are legends! Thank you!
