### ISSUE TITLE
Can't `ls` named pipes on Windows due to metadata failures

### ISSUE THREAD

**Issue by pcwalton** [nushell/nushell#11563]
### Describe the bug

On Windows you can list all named pipes on the system with `ls \\.\pipe\`. But this doesn't work on Nushell 0.89.0:

```
nu> ls '\\.\pipe\'
Failed to read metadata for '\\.\pipe\uv\0000000000000000-21180'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000001-21180'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000002-21180'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000003-21180'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000006-21180'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000007-21180'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000008-21180'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\0000000000000009-21180'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000A-21180'. It may have an illegal filename
Failed to read metadata for '\\.\pipe\uv\000000000000000B-21180'. It may have an illegal filename
thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\chrono-0.4.31\src\offset\local\mod.rs:176:46:
No such local time
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### How to reproduce

1. On Windows, `ls \\.\pipe\`.

### Expected behavior

I want to see all the named pipes, like you can in PowerShell.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.89.0                                   |
| branch             |                                          |
| commit_hash        | 2c1560e281d65a50d90b30c42006755b364b4928 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)      |
| rust_channel       | 1.73.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)      |
| build_time         | 2024-01-09 20:28:44 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | win32-windows                            |

**Comment by ChrisDenton** [comment]
This is https://github.com/chronotope/chrono/issues/1364

**Comment by fdncred** [comment]
This works now. However, invalid dates will show up similar to this.
```
 {
    "name": "\\\\.\\pipe\\__rust_anonymous_pipe1__.26112.5913665420490596302",
    "type": "file",
    "size": 1,
    "modified": "1969-12-31 18:00:00 -06:00"
  },
```
![image](https://github.com/nushell/nushell/assets/343840/6ad3549c-f26b-4f63-82a7-6405a0b1a4a4)
