### ISSUE TITLE
Getting all command arguments

### ISSUE THREAD

**Issue by samoylovfp** [nushell/nushell#11560]
### Related problem

As discussed [here](https://github.com/nushell/nushell/discussions/7457)
when wrapping system commands it is helpful to be able to pass arguments to them and `...rest` parameter is helpful for this.
It breaks down on arguments starting with a `-` though.
I ran into this when parsing output of a `git branch` command.
I want to be able to pass the flags to it without explicitly listing them in the signature.

### Describe the solution you'd like

I want a dedicated way for capturing all the arguments passed to a custom command, capturing them in a list
e.g. 
```nushell
export def git-structured-branch [@args] {
   git branch $args 
}
```

I want the command defined this way to capture all of the flags, including `--help`.

### Describe alternatives you've considered

There is a more bash-friendly alternative of just using `$@` in the body, but as far as I understand this changes the way arguments are handled by the command, so I am assuming the indicator that the command behaves differently has to be as close to the signature as possible to be as visible as possible.

There is also a slightly awkward workaround of escaping the first `-`:
```nushell
def git-structured-branch [...args] {
   git branch ($args | str trim -c '\')
}

git-structured-branch \--merged
```

### Additional context and details

Thank you for developing and maintaining nushell!
It is such a pleasure to use and customize!

**Comment by fdncred** [comment]
have you tried `--wrapped` and does it help your scenario?
```nushell
def --wrapped git-structured-branch [...args] {
  print $args
}
```

**Comment by samoylovfp** [comment]
I haven't and it does exactly what I want. Thank you!
Does it make sense to mention the flag on this page?
http://www.nushell.sh/book/aliases.html#replacing-existing-commands-using-aliases

**Comment by fdncred** [comment]
I'd mention it where ever `def --env` is mentioned since `--wrapped` is just another parameter to `def`.
