### ISSUE TITLE
Have `ps` show the full command name

### ISSUE THREAD

**Issue by djc** [nushell/nushell#1157]
**Describe the bug**
ps output in my terminal does not seem to take advantage of the full width of my terminal window. This means it cuts off process titles even though they could easily fit into the window.

**To Reproduce**
1. Have a terminal width of ~80 characters
2. Run `ps`

**Expected behavior**
`ps` output tables use up to 80 characters of width to show as much of the process titles as feasible.

**Configuration (please complete the following information):**
 - OS: macOS
 - Version: master
 - Optional features (if any): `stable`

**Comment by JosephTLyons** [comment]
This may no longer be an issue; some of the members worked on building a new nu table in the recent months.  The current behavior for me is that it never cuts off titles, no matter the terminal width, and instead, begins to wrap them down a line only if it absolutely needs to.

@djc, if you are still using Nushell, can you double check the behavior with the newest releases and see if your issue is solved?

**Comment by djc** [comment]
Thanks for working on this! I just checked with 0.17.0 and it still shows what I would consider suboptimal behavior:

<img width="648" alt="Screen Shot 2020-07-30 at 11 19 58" src="https://user-images.githubusercontent.com/158471/88905445-9c541d00-d256-11ea-8249-4d68edc6eba9.png">

**Comment by djc** [comment]
(Also why is nu eating 9% CPU while idle?)

**Comment by thegedge** [comment]
I don't think this is an issue with not using terminal width, but rather `ps` itself. Just run `ps -f` to see what I mean. You'll see columns with full strings that get wrapped across multiple rows.

**Comment by djc** [comment]
Ah yes, you're right. Closing.

**Comment by thegedge** [comment]
@djc doesn't mean we can't keep this open and tweak the purpose. I don't think it's a bad idea to always show the full name here, or at least do so with a flag 🙂

**Comment by thegedge** [comment]
Tagged this as a "good first issue", because I _think_ it would be simple to fix, but I could be wrong there. It's possible that this isn't nu, but whichever library we're using to list the processes, so whoever picks this up should take that into consideration.

**Comment by JosephTLyons** [comment]
This is an issue with Heim.  Here was a fix they did for Linux specifically.

https://github.com/heim-rs/heim/issues/154
