### ISSUE TITLE
Increase signal/noise ratio in ls command output

### ISSUE THREAD

**Issue by djc** [nushell/nushell#1158]
**Is your feature request related to a problem? Please describe.**
The current output of the ls command is pretty inefficient in terms of information density.

To wit:

```
❯ ls
━━━━┯━━━━━━━━━━━━━━━┯━━━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━━━━┯━━━━━━━━━━━━┯━━━━━━━━━━━━
 #  │ name          │ type      │ size    │ created    │ accessed   │ modified 
────┼───────────────┼───────────┼─────────┼────────────┼────────────┼────────────
  0 │ CODE_OF_CONDU │ File      │  3.4 KB │ 32 minutes │ 32 minutes │ 32 minutes 
    │ CT.md         │           │         │ ago        │ ago        │ ago 
```

This shows the created and accessed timestamps, which are almost never relevant in my usage. (GNU ls -l doesn't show them by default.) The wording of `minutes ago`, multiplied by three columns, takes up a large amount of horizontal space. So does the word `Directory` in the `type` column (which conveys about 3-4 bits of information). All this leads to rows wrapping and/or file names getting cut off. (In this case, wrapping looks worse to me than cutting off values.)

**Describe the solution you'd like**
I would get rid of the created and accessed columns by default, replace `Directory` by `Dir` in the type column, potentially get rid of `ago` in time columns (since this will be the inevitable default in 99.9+% of cases) and maybe abbreviate the units in timestamp columns.

**Describe alternatives you've considered**
Potentially make the `ls` default columns easily configurable.

**Comment by sandorex** [comment]
I discussed with @jonathandturner and this will probably be done by reading width of the terminal and formatting the time to the shorter format if there isnt enough space, but to do this we need to fork one of crates for formatting time in a human readable format cause they dont seem to be maintained

**Comment by yoshuawuyts** [comment]
Perhaps a useful reference would be what other `ls` alternatives are doing:
- [exa](https://the.exa.website/)
- [broot](https://dystroy.org/broot/)

**Comment by djc** [comment]
Maybe in general it would be interesting to explore integrating exa (analogously to supporting starship as the prompt). I think it makes a lot of sense to leverage best-of-breed Rust CLIs for some of the more complex commands/features.

**Comment by djc** [comment]
In general I also really like the idea of showing more or less data (columns) depending on term width.

**Comment by jonathandturner** [comment]
I did a little simplifying of `ls` this morning. In taking with @sandorex, it does feel like tables should be smarter about the terminal width than we are now.

One way we could do this is to give columns priority. In `ls` name might get first priority, as one example. Then add we print the columns we can add the ones that fit comfortably.

There are still some open questions here because we don't know the size of the data before we print the table, but what we could do is grab the first 50 (or first 100) and then make the others match that. We could a assume that's a big enough sample to decide how to display the rest of the table as it streams out

**Comment by jonathandturner** [comment]
One thing I like about how `ls` works now is that it's an easy way to introduce people to tables.

I'm curious how you see `exa` integrated might look.

**Comment by djc** [comment]
exa's README starts out like this: "It uses colours to distinguish file types and metadata. It knows about symlinks, extended attributes, and Git." I think none of these currently implemented in nushell's `ls`? If you're pitching nushell as a modern shell, then including a modern `ls` (or making it easy to include) makes a lot of sense.

So in terms of integrating I was mostly thinking of mashing up exa's data model and coloring with nushell's tables and composability.

**Comment by jonathandturner** [comment]
We made the default `ls` output more compact, which should help here.  I'm going to close, but please re-open if the new design needs further improvement.
