### ISSUE TITLE
Plugins symlinked into ~/.config/nushell/plugins can't be registered

### ISSUE THREAD

**Issue by tesujimath** [nushell/nushell#11583]
### Describe the bug

My user configuration is all managed by Nix Home Manager, which means all dotfiles are symlinks into the Nix store.

Installing my `nu_plugin_bash_env` like this used to work, but no longer in Nu 0.89.0.

It seems that `register` expands symlinks and then fails because an absolute path cannot start `nu_plugin_`, which seems to be a recently added check.

This is a pretty severe limitation for anyone who uses Nix.

### How to reproduce

1. Symlink a Nu plugin into plugins directory
2. register plugin

### Expected behavior

Not care that it is a symlink, but just register whatever is found at that location in the plugins directory.

### Screenshots

```
aya> pwd
/home/sjg/.config/nushell/plugins
aya> ls -l | select name type target
╭───┬────────────────────┬─────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ # │        name        │  type   │                                                  target                                                   │
├───┼────────────────────┼─────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 0 │ nu_plugin_bash_env │ symlink │ /nix/store/mv49mb2w7gibn5w97ycgizng0pcx41k6-home-manager-files/.config/nushell/plugins/nu_plugin_bash_env │
╰───┴────────────────────┴─────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────╯
aya> register nu_plugin_bash_env
Error:   × Register plugin failed
   ╭─[entry #13:1:1]
 1 │ register nu_plugin_bash_env
   ·          ─────────┬────────
   ·                   ╰── plugin name must start with nu_plugin_
   ╰────

aya> mv nu_plugin_bash_env ../nu_plugin_bash_env-nix
aya> cp ../nu_plugin_bash_env-nix nu_plugin_bash_env
aya> ls -l | select name type target
╭───┬────────────────────┬──────┬────────╮
│ # │        name        │ type │ target │
├───┼────────────────────┼──────┼────────┤
│ 0 │ nu_plugin_bash_env │ file │        │
╰───┴────────────────────┴──────┴────────╯
aya> register nu_plugin_bash_env

# succeeds now
```

### Configuration

aya> version | transpose key value | to md --pretty
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.89.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball) |
| cargo_version      | cargo 1.75.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | dataframe, default, extra, sqlite, trash, which, zip              |
| installed_plugins  | bash-env                                                          |

### Additional context

Nu is wonderful and so is Nix.  They should be wonderful together. :smile:

**Comment by fdncred** [comment]
Plugins changed recently with https://github.com/nushell/nushell/pull/10955 and https://github.com/nushell/nushell/pull/10201. I don't see any others. You could do a git bisect to see where it stopped working if you have the source code.

**Comment by tesujimath** [comment]
Hmm, I did some investigating, and failed to find a recent version of Nu which worked for me.  I am wondering now whether what changed was how Nix Home Manager names its files, rather than something in Nu.

Having looked into this, I found that the ultimate file after expanding all the symlinks has some hash prefix on the name, and this is what is breaking the plugin validation.

```
aya> pwd
/home/sjg/.config/nushell/plugins
aya> ls -l nu_plugin_bash_env | select name type target
╭───┬────────────────────┬─────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ # │        name        │  type   │                                                  target                                                   │
├───┼────────────────────┼─────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 0 │ nu_plugin_bash_env │ symlink │ /nix/store/mv49mb2w7gibn5w97ycgizng0pcx41k6-home-manager-files/.config/nushell/plugins/nu_plugin_bash_env │
╰───┴────────────────────┴─────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────╯
aya> ls -l /nix/store/mv49mb2w7gibn5w97ycgizng0pcx41k6-home-manager-files/.config/nushell/plugins/nu_plugin_bash_env | select name type target
╭───┬───────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────┬───────────────────────────────────────────────────────────────────╮
│ # │                                                   name                                                    │  type   │                              target                               │
├───┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────┼───────────────────────────────────────────────────────────────────┤
│ 0 │ /nix/store/mv49mb2w7gibn5w97ycgizng0pcx41k6-home-manager-files/.config/nushell/plugins/nu_plugin_bash_env │ symlink │ /nix/store/4yjlh2icfnbg93s410wmyq0x75jrlar0-hm_nu_plugin_bash_env │
╰───┴───────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────┴───────────────────────────────────────────────────────────────────╯
aya> ls -l /nix/store/4yjlh2icfnbg93s410wmyq0x75jrlar0-hm_nu_plugin_bash_env | select name type target
╭───┬───────────────────────────────────────────────────────────────────┬──────┬────────╮
│ # │                               name                                │ type │ target │
├───┼───────────────────────────────────────────────────────────────────┼──────┼────────┤
│ 0 │ /nix/store/4yjlh2icfnbg93s410wmyq0x75jrlar0-hm_nu_plugin_bash_env │ file │        │
╰───┴───────────────────────────────────────────────────────────────────┴──────┴────────╯

```

I added some debug output around the plugin filename validation and saw this:
```
aya> register nu_plugin_bash_env
Error:   × Register plugin failed
   ╭─[entry #1:1:1]
 1 │ register nu_plugin_bash_env
   ·          ─────────┬────────
   ·                   ╰── plugin name must start with nu_plugin_ but Nu found "4yjlh2icfnbg93s410wmyq0x75jrlar0-hm_nu_plugin_bash_env"
   ╰────
```

I am inclined to submit a PR to allow plugins to have filenames which *contain* `nu_plugin_` rather than necessarily *start with it*.  And to change the filename to plugin name mapping accordingly.

This will allow for installing any Nu plugin executable using Nix, for which I'm sure others will be interested in too.

Does this sound OK?

**Comment by tesujimath** [comment]
The real bother here is that Nu insists on recursively expanding symlinks for plugins rather than just using them in place.  I am guessing this may be to support Python plugins which need to be able to find the rest of their files?

**Comment by fdncred** [comment]
I'm not sure if a PR would be accepted to change to support plugins named like "4yjlh2icfnbg93s410wmyq0x75jrlar0-hm_nu_plugin_bash_env".

When you say, "... Nu insists on recursively expanding symlinks ..." what exactly is doing this? Is this something in the register command or something else? If it's in register, it may be acceptable to add a --no-expand-symlink flag or something like that?

**Comment by tesujimath** [comment]
That's a good idea, I'll look into that.

**Comment by tesujimath** [comment]
Since updating to the latest NixOS and Nix Home Manager, this problem has gone away.
```
aya> ls -l ~/.config/nushell/plugins/ | select name type target
╭───┬──────────────────────────────────────────────────────┬─────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ # │                         name                         │  type   │                                                  target                                                   │
├───┼──────────────────────────────────────────────────────┼─────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 0 │ /home/sjg/.config/nushell/plugins/nu_plugin_bash_env │ symlink │ /nix/store/dj710j7qdz5594jymwskn5w040h9v614-home-manager-files/.config/nushell/plugins/nu_plugin_bash_env │
╰───┴──────────────────────────────────────────────────────┴─────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────╯
aya> ls -l /nix/store/dj710j7qdz5594jymwskn5w040h9v614-home-manager-files/.config/nushell/plugins/nu_plugin_bash_env | select name type target
╭───┬───────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────┬───────────────────────────────────────────────────────────────────────────────────────╮
│ # │                                                   name                                                    │  type   │                                        target                                         │
├───┼───────────────────────────────────────────────────────────────────────────────────────────────────────────┼─────────┼───────────────────────────────────────────────────────────────────────────────────────┤
│ 0 │ /nix/store/dj710j7qdz5594jymwskn5w040h9v614-home-manager-files/.config/nushell/plugins/nu_plugin_bash_env │ symlink │ /nix/store/k24g7nnmpd5827mfqz3z2673wvzfwyrp-nu_plugin_bash_env/bin/nu_plugin_bash_env │
╰───┴───────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────┴───────────────────────────────────────────────────────────────────────────────────────╯
aya> ls -l /nix/store/k24g7nnmpd5827mfqz3z2673wvzfwyrp-nu_plugin_bash_env/bin/nu_plugin_bash_env | select name type target
╭───┬───────────────────────────────────────────────────────────────────────────────────────┬──────┬────────╮
│ # │                                         name                                          │ type │ target │
├───┼───────────────────────────────────────────────────────────────────────────────────────┼──────┼────────┤
│ 0 │ /nix/store/k24g7nnmpd5827mfqz3z2673wvzfwyrp-nu_plugin_bash_env/bin/nu_plugin_bash_env │ file │        │
╰───┴───────────────────────────────────────────────────────────────────────────────────────┴──────┴────────╯
```

In my newly found happy state I am closing this.  (Would have been a bit challenging to fix in Nu I think, the canonicalising of file paths seems fairly deep-rooted.)
