### ISSUE TITLE
ctrl+c has stopped on tip, maybe related to reedline bump/feature

### ISSUE THREAD

**Issue by colemickens** [nushell/nushell#11600]
### Describe the bug

Hi,

recently ctrl+c does not behave as normally, and does not abandon the current line, like I've come to expect from all shells.

programs still get killed when I tap ctrl-c.

this issue is present in:
* c59d6d31bcb8828b56769de6dc9e13b103942ba8
* 4458aae3d41517d74ce1507ad3e8cd94021feb16

this issue is not present in:
* 90095c72f6702f88a0833df6ecbc16907bb75109

that's as far as I can bisect for now.

this happens in and outside of `zellij`, and repros in `alacritty` and `rio`.

### How to reproduce

1. open a term emu with tip
2. hit `ctrl-c`

### Expected behavior

it should give up on the current line and move me to a new fresh prompt

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.89.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball) |
| cargo_version      | cargo 1.75.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by colemickens** [comment]
It repros on e7a4af14cd8563d043690c613c7a5624fd0838ca

so I think it's e7a4af14cd8563d043690c613c7a5624fd0838ca.

cc: @Tastaturtaste

**Comment by Tastaturtaste** [comment]
I will look into it tomorrow when nobody else has done it by then.

**Comment by Tastaturtaste** [comment]
Could you please also provide your nu config in case its relevant? I guess it has to do with the keybindings.

**Comment by colemickens** [comment]
I use default keybindings. The current active config is here: https://github.com/colemickens/nixcfg/blob/2978faba3a450427b98f2418c3e148ccc38ce657/mixins/nushell-config.nu#L440-L541

**Comment by Tastaturtaste** [comment]
I have (probably) identified the issue to be the default keybindings set in reedline itself. I originally put ctrl+c for the copy operation there and forgot to update that place when we settled on ctrl+shift+c as the default in the config.nu. I will push a fix for that to reedline. 

On the larger issue, and already mentioned previously elsewhere, I would like to see nushell defining all default keybindings _only_ in the config.nu. There should, in my opinion, only be a single source of truth for them. And putting them all in the config.nu also aids understanding and discoverability for users.

**Comment by Tastaturtaste** [comment]
https://github.com/nushell/reedline/pull/715
