### ISSUE TITLE
How can I set the value of a record entry to the output of a command?

### ISSUE THREAD

**Issue by MichaelBrunn3r** [nushell/nushell#11614]
### Question

```nushell
{
   current_date: date now
}
```
I want `current_date` to have the value of the output of `date now`.
Of course I could do it like this:
```nushell
let current_date = date now
{
   current_date: $current_date 
}
```
But now I have to create a variable for every value I want to compute. This makes creating nested data cumbersome:
```nushell
let a = ...
let ba = ...
let c = ...
{
  a: $a
  b: {
    ba: $ba
  }
  c: $c
}
```
Is there some syntax I'm missing to get the value of `date now`?

**Comment by fdncred** [comment]
```nushell
{
   current_date: (date now)
}
```

**Comment by MichaelBrunn3r** [comment]
Oh, I get it now. I tested the `()` before, but my result was:
```nushell
> {current_date: (date now)}
╭──────────────┬─────╮
│ current_date │ now │
╰──────────────┴─────╯
```
I thought it just cut of the `date` part. This was further confusing, because this looks different:
```nushell
> let current_date = date now
> let test = {current_date: $current_date }
╭──────────────┬────────────────╮
│ current_date │ 11 seconds ago │
╰──────────────┴────────────────╯
```
Apparently the time gets pretty printed and only after ~10 seconds `now` becomes `x seconds ago`.
Thx for the help

**Comment by fdncred** [comment]
You can change the human readable date representation so that "date now" looks something similar to this.
```nushell
❯ {current_date: (date now)} 
╭──────────────┬──────────────────────╮
│ current_date │ 01/22/24 03:33:44 PM │
╰──────────────┴──────────────────────╯
```
This is the setting in the config.nu that controls that.
```nushell
  datetime_format: {
    # normal: '%a, %d %b %Y %H:%M:%S %z'    # shows up in displays of variables or other datetime's outside of tables
    table: '%m/%d/%y %I:%M:%S %p'          # generally shows up in tabular outputs such as ls. commenting this out will change it to the default human readable datetime format
  }
```

**Comment by MichaelBrunn3r** [comment]
Huge thanks again, I will consider changing it. But now I know that its not an error
