### ISSUE TITLE
from ssv: max matches

### ISSUE THREAD

**Issue by ineu** [nushell/nushell#11612]
### Related problem

There are programs that output data in columns where the last column means "everything else", including spaces. An example of such a program is `wmctrl -l`:
> 0x03600140  0 honor pr.nu – Doom Emacs

ATM it can not be parsed by `from ssv -m 1` because it produces 7 columns, splitting the actual window name into separate columns.

### Describe the solution you'd like

Add an option to `from ssv` to limit the columns. For the case above it could be something
```
wmctrl -l | from ssv -m 1 --max-columns 3
```
which will emit two columns with "0x03600140" and "0" respectively and put the remainder of the line into the third, last column.

### Describe alternatives you've considered

`parse`, but it's a heavy lifting for such a case

**Comment by fdncred** [comment]
Ya, I could see how this could help with `from ssv` or `detect columns`. I run into things like this and just switch to `parse --regex` usually.

**Comment by ineu** [comment]
I could try implementing it

**Comment by ineu** [comment]
Thanks for mentioning `detect columns`, I wasn't aware of it before. Actually it already does what I want, thanks to the open range: `wmctrl -l | detect columns -n -c 3..`.
Now I'm a bit confused: `detect columns` seems like a more powerful version of `from ssv`, so why having both?

**Comment by fdncred** [comment]
`detect columns` and `from ssv` work differently. Sometimes you'll think `detect columns` is more powerful. Other times you'll think `from ssv` is more powerful.

**Comment by ineu** [comment]
The reason I'm comparing them is the following: as I look at the `-c` option to `detect columns`, I find it a superior approach, compared to my initial `--max-columns` suggestion: `-c 3..` is the same as `--max-columns `, and it's only one of the possible ways of using ranges.

So now I don't think it's worth implementing an inferior option. On the other hand, if we just copy the `-c` option from `detect columns` to `from ssv`, then I don't really see much difference between `from ssv` and `detect columns`.

**Comment by fdncred** [comment]
> The reason I'm comparing them is the following: as I look at the -c option to detect columns, I find it a superior approach, compared to my initial --max-columns suggestion: -c 3.. is the same as --max-columns , and it's only one of the possible ways of using ranges.

yup, I wrote that so I like it but it's not perfect. There is still some work to do on `detect columns` for this to work flawlessly.

Ya, we don't want inferior options either. There is a great difference between `detect columns` and `from ssv`. You may not have been around long enough to witness it first hand. Some externals work better with one or the other.
