### ISSUE TITLE
`help p` always shows help for the `p` built-in

### ISSUE THREAD

**Issue by ineu** [nushell/nushell#11619]
### Describe the bug

I write scripts in Nu using such pattern:
```
#!/bin/nu
# the file is somewhere in PATH, called 'foo'

def 'main one' [] { print one }
def 'main two' [] { print two }
def main [] { help foo }
```

It allows to call `foo` without arguments and get a nice help:
```
Usage:
  > foo 

Subcommands:
  foo one - 
  foo two - 

Flags:
  -h, --help - Display the help message for this command

Input/output types:
  ╭───┬───────┬────────╮
  │ # │ input │ output │
  ├───┼───────┼────────┤
  │ 0 │ any   │ any    │
  ╰───┴───────┴────────╯


```

It works for scripts which don't collide with internal names. However, I also have a script called `p` (to manage packages). There I have
```
def main [] { help p }
```
which show me help for the built-in `p` alias. I tried `def main [] { help main }`, but it seems to only work for the specific script name

### How to reproduce

---

### Expected behavior

Help for the built-ins should not have priority over the script itself.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.89.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 2c1560e281d65a50d90b30c42006755b364b4928                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (Arch Linux rust 1:1.75.0-1) |
| cargo_version      | cargo 1.75.0                                                     |
| build_time         | 2024-01-09 23:05:05 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by kubouch** [comment]
Inside the script the `main` command is still called `main`. It only gets renamed to `p` when exported from the file. You should be able to call `help main`.

**Comment by fdncred** [comment]
What happens if you `hide p`? If built-ins don't have priority, you'll never be able to call them because there is not some syntax that always lets you call internal names.

**Comment by ineu** [comment]
I do have it hidden: my custom `p` was initially a module that I included via `use`. A piece of my my Nu config:
```
hide p
hide n
hide g
hide cal
hide sleep
```
And later in this file I have these `use`'s that the `p` was once in. `help p` works as expected in that case. It only references the built-in when used in a standalone script.
