### ISSUE TITLE
Ctrl+Left and Ctrl+Right does not work on OSX

### ISSUE THREAD

**Issue by mgattozzi** [nushell/nushell#1162]
**Describe the bug**
This is an OS specific bug due to conflicting key bindings. On OSX Ctrl+Left/Ctrl+Right are linked to switching workspaces and so the
behavior for shells such as zsh or bash is to use Meta+Left/Meta+Right
in order to move forward or back a word as was added in #1141. While
I did want to fix this behavior, Rustyline currently doesn't support
arbitrary sequences and only allows `Meta(char)` which means things
like `Meta(Left)` aren't a thing you can do since it's a multi char
sequence. I've opened up a ticket for Rustyline to support this and
I've linked it down below for tracking purposes.

**To Reproduce**
1. Type at least two words
2. Hit Ctrl+Left and if you have workspaces you'll move left in those not the words

**Expected behavior**
I would expect it to move the cursor over one word

**Configuration (please complete the following information):**
 - OS: OSX
 - Version: master branch

**Additional Context**
Original Nushell Issue: #441 
PR Fixing the Issue: #1141
Linked Rustyline Issue: https://github.com/kkawakam/rustyline/issues/318

**Comment by jonathandturner** [comment]
This seems to work with Alt+ArrowLeft and Alt+ArrowRight in macOS. Looks like the issue here might be to document the behavior and give the correct shortcuts for each OS?

**Comment by mgattozzi** [comment]
Yeah that seems reasonable to me!

**Comment by rgwood** [comment]
Bit more macOS info: Alt+ArrowLeft and Alt+ArrowRight work for me in Terminal.app but not iTerm2. iTerm2 seems to map those to hex codes for some reason:

![Screen Shot 2020-01-15 at 8 50 58 PM](https://user-images.githubusercontent.com/26268125/72494457-c83b1400-37d8-11ea-8df2-da238bbe6458.jpg)

However, the issue persists even after removing those mappings.

**Comment by fdncred** [comment]
customizable keybindings was implemented with the 0.17 release and may help this issue. please let us know.

**Comment by nickolay** [comment]
rgwood: iTerm2 [tries to be "standards-compliant" by treating the Option key as ALT](https://gitlab.com/gnachman/iterm2/-/issues/5451) and lets the user [pick one of bundled presets - "Natural Text Editing"/"Terminal.app compatibility" - or change the mappings to `ESC+b` and `ESC+f` manually](https://stackoverflow.com/a/22312856/1026).

fdncred: customizable keybindings only expose the knobs that rustyline makes available, I think, as the [sample config](https://github.com/nushell/nushell/blob/6202705eb621dc9edaec0eca2556d665bac9140e/docs/sample_config/keybindings.yml#L159) only has `Meta(char)`, as noted in the description of this issue.

So as far as I understand, this is blocked on https://github.com/kkawakam/rustyline/issues/318 , and after upgrading to a rustyline version with this feature, this can either become a documentation request, or a request to handle ALT+arrows out of the box.

**Comment by fdncred** [comment]
This was recommended by the rustyline folks https://superuser.com/questions/357355/how-can-i-get-controlleft-arrow-to-go-back-one-word-in-iterm2/357394#357394

**Comment by fdncred** [comment]
For anyone still following, I got this to work on BigSur with Apple's Terminal.
https://apple.stackexchange.com/a/4637
![image](https://user-images.githubusercontent.com/343840/126225865-c4e3c699-6925-4822-8b38-757c79fafe32.png)
