### ISSUE TITLE
Inconsistent path expansions between `ls`, `cp`, `mv`, `rm`, and `mkdir`

### ISSUE THREAD

**Issue by crides** [nushell/nushell#11626]
### Describe the bug

The source/target/destination arguments for all these commands (and maybe others as well) are not expanded correctly, or in the same way. This is fine on normal strings (probably due to some syntax shape magic on parse time), but doesn't on variables.

- `ls` somehow calls `expand_to_real_path` twice (idempotent, but more work than needed)
- `mkdir` doesn't expand at all, relying on `std::fs::create_dir_all` for the cwd
- `cp` (`ucp`, cuz that'ts the default) expands normally on destination, but only processes globs and not expand correctly for sources
- `rm` merely joins with cwd (wrong)
- `mv` merely joins cwd with destination, and has the same problem with `cp` for sources

The immediate issue would be to just fix the processing of these commands, but I think the actual issue could be the syntax shapes not processing correctly (considering everything here other than `ls` has the correct syntax shape, just globs and paths). The same thing can be easily tested using a custom command (see below)

### How to reproduce

```nu
let d = "~/testtest"
mkdir $d      # succeeds but creates a directory named `~` under cwd
cp $file $d   # succeeds correctly
cp $d $d      # fails, can't find source
mv $file $d   # fails
mv $d $d      # fails, can't find source either
rm $d         # fails
ls $d         # succeeds correctly

def test [p: path d: directory g: glob] { print $p; print $d; print $g }
test $d $d $d # nothing is expanded
```

### Expected behavior

All above 5 commands in the reproduction should succeed

### Configuration

| key                | value                                                                                  |
| ------------------ | -------------------------------------------------------------------------------------- |
| version            | 0.89.1                                                                                 |
| branch             | dev                                                                                    |
| commit_hash        | 739385b6494c6afbdf090f14accecfcb08d8bc40                                               |
| build_os           | linux-x86_64                                                                           |
| build_target       | x86_64-unknown-linux-gnu                                                               |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                                                    |
| rust_channel       | 1.73.0-x86_64-unknown-linux-gnu                                                        |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                                                    |
| build_time         | 2024-01-11 22:25:29 -08:00                                                             |
| build_rust_channel | debug                                                                                  |
| allocator          | mimalloc                                                                               |
| features           | default, sqlite, trash, which, zip                                                     |
| installed_plugins  | sound, sound beep, sound make, sound meta, sound meta list, sound meta set, sound play |

**Comment by fdncred** [comment]
There's a PR that could help with this https://github.com/nushell/nushell/pull/11621

**Comment by WindSoilder** [comment]
What's the value of `$file`?

**Comment by crides** [comment]
anything

**Comment by fdncred** [comment]
@WindSoilder does your PR close this one too?
