### ISSUE TITLE
Allow nu to be started with a certain directory

### ISSUE THREAD

**Issue by steveklabnik** [nushell/nushell#1163]
**Is your feature request related to a problem? Please describe.**

Windows Terminal lets you create profiles, and I'd like to make a `nu` profile. It needs a command to start up. `nu.exe` works great, but does not start me in my home directory.

**Describe the solution you'd like**

A command line flag or other argument to `nu.exe` would be fantastic.

**Describe alternatives you've considered**

I am not sure.

**Comment by sebastian-xyz** [comment]
You can configure the starting directory in each profile. You can set `"startingDirectory": "C:/Users/user/"` to open Nu in your home directory.

**Comment by steveklabnik** [comment]
Amazing, thank you!

I'll close this then, since my immediate need is taken care of.
