### ISSUE TITLE
Wrong hint message in `into record` call

### ISSUE THREAD

**Issue by antarktidi4** [nushell/nushell#11632]
### Describe the bug

When the script returns a record it converts the return type to a string (idk if this is expected behavior) so if I pipe it in `into record` (I know it shouldn't work) it will throw an error message `input type: string` with hint `only string input data is supported`, but if I pipe string in `into record` it will give different error `command doesn't support string input`.

### How to reproduce

1. create script with main function
```nu
def main [] {
  return {
    first: "a",
    second: "b",
  };
}

```
2. pipe output in `into record`
`test-bug.nu | into record`
3. get wrong hint

### Expected behavior

I think it should print `command doesn't support string input`.

### Screenshots

![image](https://github.com/nushell/nushell/assets/66149987/01d09ce9-6006-4a96-a91c-3e131b935179)

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.87.1                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | windows-x86_64                      |
| build_target       | x86_64-pc-windows-msvc              |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) |
| rust_channel       | 1.72.1-x86_64-pc-windows-msvc       |
| cargo_version      | cargo 1.72.1 (103a7ff2e 2023-08-15) |
| build_time         | 2023-11-23 12:36:00 -08:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  |                                     |

### Additional context

I also have a question about returning a record from a function in a script, why is it a string?

**Comment by antarktidi4** [comment]
upd: I updated nushell to the lattest 0.89.0 version and it still happening

**Comment by fdncred** [comment]
How would 'test string' be converted to a record, there is no key/value?

With your script, when you do `nu test-bug.nu | into record` that shouldn't work either because you're shelling out to a new instance of `nu`, running a script that returns a record but the the output is converted to a string and then you try to convert a string into a record which isn't supported.

**Comment by antarktidi4** [comment]
> How would 'test string' be converted to a record, there is no key/value?

I'm not saying it should work with strings, i'm saying the hint message is wrong, it shouldn't be a `only string input data is supported` because if I pass a string it throw `command doesn't support string input`.

**Comment by fdncred** [comment]
oh, i see what you're saying. i wonder why it says that? maybe it means that `nu test-bug.nu` only outputs strings?
