### ISSUE TITLE
modules don't have "extra usage" but commands do

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#11648]
### Describe the bug

as per title

### How to reproduce

- define a command with usage and extra usage
```nushell
# usage of cmd
#
# extra usage of cmd
def cmd [] {}
```
- look at the command
```
scope commands | where name == "cmd" | into record | select usage? extra_usage?
```
=> it does have an extra usage
```
───────────┬──────────────────
usage      │usage of cmd
extra_usage│extra usage of cmd
───────────┴──────────────────
```
- define a module with usage and extra usage
```nushell
# usage of mod
#
# extra usage of mod
module mod {}
```
- look at the module with `scope`
```
scope modules | where name == "mod" | into record | select usage? extra_usage?
```
=> it does NOT have an extra usage
```
───────────┬────────────
usage      │usage of mod
extra_usage│
───────────┴────────────
```

### Expected behavior

i expected the `scope modules` pipeline to give
```
───────────┬──────────────────
usage      │usage of mod
extra_usage│extra usage of mod
───────────┴──────────────────
```

### Configuration

| key                | value                                  |
| ------------------ | -------------------------------------- |
| version            | 0.89.0                                 |
| branch             |                                        |
| commit_hash        |                                        |
| build_os           | linux-x86_64                           |
| build_target       | x86_64-unknown-linux-gnu               |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)    |
| rust_channel       | stable-x86_64-unknown-linux-gnu        |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)    |
| build_time         | 2024-01-11 18:20:14 +01:00             |
| build_rust_channel | release                                |
| allocator          | mimalloc                               |
| features           | default, sqlite, trash, which, zip     |
| installed_plugins  | clipboard copy, clipboard paste, gstat |

**Comment by amtoine** [comment]
cc/ @kubouch ?

**Comment by kubouch** [comment]
Good catch. I don't think there is a reason for modules to not have extra usage. Anything that has a usage should support extra usage. This connects to the docstring format discussion that we started in nupm.

**Comment by amtoine** [comment]
yup, as you can see, the [`nu-git-manager` module has an extra usage](https://github.com/amtoine/nu-git-manager/blob/main/pkgs/nu-git-manager/nu-git-manager/mod.nu) but it does not appear in the [documentation](https://github.com/amtoine/nu-git-manager/blob/main/docs/nu-git-manager/index.md#description) :open_mouth:

**Comment by amtoine** [comment]
i'll try to fix this

**Comment by amtoine** [comment]
got it :ok_hand:
