### ISSUE TITLE
Add parameters to `query db`

### ISSUE THREAD

**Issue by giggio** [nushell/nushell#11643]
### Related problem

I'd like to be able to pass parameters to `query db`.

### Describe the solution you'd like

Something like:

```nushell
query db "INSERT INTO table (column_x, column_y) VALUES (?1, ?2)" --params $x $y
```

### Describe alternatives you've considered

Invoking sqlite directly.

### Additional context and details

Besides the problem of sql injection, this is cumbersome because you have to escape values when using string interpolation.

**Comment by fdncred** [comment]
You'd have to use string interpolation now, like you suggested.
```nushell
❯ let var = 75
❯ open $nu.history-path | query db $"select * from history where id = ($var)"
```

I'm not even sure if you can have multiple of the same parameter like that in nushell. If someone wanted to submit a PR with something like this, we'll look at it.

**Comment by giggio** [comment]
Interpolation is subject to sql injection and other problems (like escaping).
I'll update the description to one that fits the current language. But the idea to repeated params is something other shells use.

**Comment by fdncred** [comment]
If it were to take a list, that would work too like
```nushell
query db "INSERT INTO table (column_x, column_y) VALUES (?1, ?2)" --params [$x $y]
```

**Comment by d4h0** [comment]
For reference: https://owasp.org/www-community/attacks/SQL_Injection

Basically, `query db` currently shouldn't be used with any data that comes from an untrustworthy source, like the internet.
