### ISSUE TITLE
Name not found PATH

### ISSUE THREAD

**Issue by batmikun** [nushell/nushell#11651]
### Describe the bug

Hey guys, im following the config page on the website to setup my PATH environment variables. But is keeps throwing an error.

### How to reproduce

Install nushell
Go to editor $nu.env-path
Add this -> $env.PATH = ($env.PATH | split row (char esep) | append 'C:\Users\nstir\.cargo\bin')

### Expected behavior

To add this variables to my PATH 

### Screenshots

![C__Program Files_nu_bin_nu exe 1_27_2024 6_05_21 PM](https://github.com/nushell/nushell/assets/47833971/d65dbd13-fc6c-4aa2-8222-fd3570086315)
![C__Program Files_nu_bin_nu exe 1_27_2024 6_05_56 PM](https://github.com/nushell/nushell/assets/47833971/6ed9cc0e-7973-4db4-a9f0-2c47e4d26abe)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.89.0                                   |
| branch             |                                          |
| commit_hash        | 2c1560e281d65a50d90b30c42006755b364b4928 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)      |
| rust_channel       | 1.73.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)      |
| build_time         | 2024-01-09 20:28:44 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
You're apparently on Windows which does not have `PATH` but has `Path`. So, you'll need to use `$env.Path` on Windows.

**Comment by batmikun** [comment]
That was it. It has to be $env.Path = $env.Path
