### ISSUE TITLE
Pane/terminal based history

### ISSUE THREAD

**Issue by Feel-ix-343** [nushell/nushell#11659]
### Related problem

Often, I make new terminal panes/windows based on commands that I want to repetitively run. In one pane, I may run cargo build, and in another, cargo check. When I jump back a pane, I like to hit C-P to rerun the command that I previously used there. However, this doesn't work in the way I expect it to. After running cargo build in a different pane, I press C-P, and cargo build, instead of cargo check, fills. I would expect that cargo check would fill as this was the last used command in the *pane's* history. 

### Describe the solution you'd like

Track the history of each specific Nushell instance, and fill that before filling general nushell history.

**Comment by fdncred** [comment]
If C-P is supposed to be ctrl+p then I'm not sure it's assigned anything by default. You can see the default keybindings with `keybindings default` and looking at the config.nu file under keybindings.

Also, if you want history isolation, you need to enable it in your config.nu.

**Comment by Feel-ix-343** [comment]
Its move_up. Same as the up arrow. This is a common key binding so I just assumed ... my bad

**Comment by fdncred** [comment]
Never heard of it. You may be able assign a key binding to what up arrow does.

**Comment by Feel-ix-343** [comment]
Yes yes I did. ...Just for reference 

```
        {
            name: move_up
            modifier: control
            keycode: char_p
            mode: [emacs, vi_normal, vi_insert]
            event: {
                until: [
                    {send: menuup}
                    {send: up}
                ]
            }
        }

```

but this feature request has to do with how history items are filled. (I am almost positive it doesn't have to do with the keybinding)

**Comment by fdncred** [comment]
Are you using sqlite history and do you have history_isolation set to true?

from the default_config.nu
```
        isolation: false # only available with sqlite file_format. true enables history isolation, false disables it. true will allow the history to be isolated to the current session using up/down arrows. false will allow the history to be shared across all sessions.
```

**Comment by Feel-ix-343** [comment]
This is it! Thank you so very much. I totally should have checked in the config -- I just assumed that it was not supported!
