### ISSUE TITLE
commandline -e not working/crashing

### ISSUE THREAD

**Issue by JackalSix** [nushell/nushell#11653]
### Describe the bug

When using commandline -e with japanese characters, it will either only go partway to the end or crash the shell entirely.

### How to reproduce

commandline -i ああああああ;commandline -e will move to the third character.
commandline -i あああああああ;commandline -e will crash.

### Expected behavior

The cursor should move to the end of the prompt in the same way it does with english characters.
As a workaround using -c with a massive number works.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.89.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 2c1560e281d65a50d90b30c42006755b364b4928                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (Arch Linux rust 1:1.75.0-1) |
| cargo_version      | cargo 1.75.0                                                     |
| build_time         | 2024-01-09 23:05:05 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by crides** [comment]
I can't repro using your examples. Correct content is inserted, and cursors are at the end.

on nushell 0.89.1, based on `c371d1a53`

**Comment by JackalSix** [comment]
Well I'm not sure what particularity of my system would cause this. I've tried with different locales and still had the same issue. I ran nushell inside another shell so the crash wouldn't kill my terminal and I could see this error:

```
thread 'main' panicked at crates/nu-cli/src/syntax_highlight.rs:464:6:
byte index 7 is not a char boundary; it is inside 'あ' (bytes 6..9) of `あああああああ`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Running with that backtrace variable set to 1 gives me nothing, full just gives me this:

```
stack backtrace:
   0:     0x63ab40f8fa81 - <unknown>
   1:     0x63ab3f10c930 - <unknown>
   2:     0x63ab40f8a0fd - <unknown>
   3:     0x63ab40f8f865 - <unknown>
   4:     0x63ab40f91363 - <unknown>
   5:     0x63ab40f910b0 - <unknown>
   6:     0x63ab40f919d0 - <unknown>
   7:     0x63ab40f9176e - <unknown>
   8:     0x63ab40f8ff26 - <unknown>
   9:     0x63ab40f914f2 - <unknown>
  10:     0x63ab3efb6155 - <unknown>
  11:     0x63ab3f110353 - <unknown>
  12:     0x63ab3efb6937 - <unknown>
  13:     0x63ab3f26a928 - <unknown>
  14:     0x63ab3f26851d - <unknown>
  15:     0x63ab40debf2d - <unknown>
  16:     0x63ab40de8365 - <unknown>
  17:     0x63ab3f22bf6b - <unknown>
  18:     0x63ab3f213ff8 - <unknown>
  19:     0x63ab3f20838c - <unknown>
  20:     0x63ab3f217c5d - <unknown>
  21:     0x63ab3f21a17e - <unknown>
  22:     0x63ab40f8070d - <unknown>
  23:     0x63ab3f21a173 - <unknown>
  24:     0x79fb22a45cd0 - <unknown>
  25:     0x79fb22a45d8a - __libc_start_main
  26:     0x63ab3f05a135 - <unknown>
  27:                0x0 - <unknown>
```

I can try with 0.89.1 later today and see if that fixes it.

**Comment by crides** [comment]
Ahhh, looking at the commits, #11504 is what you're missing. Matches the panic exactly
