### ISSUE TITLE
Extraneous output on every keystroke

### ISSUE THREAD

**Issue by reillysiemens** [nushell/nushell#1165]
**Describe the bug**
On initial startup and on every keystroke thereafter I get extraneous output that looks to be extra debugging information or possibly some sort of error reporting. The output looks something like
```
forward    backward    : parser                                        : offset    : fragment
1                      : -> pipeline                                   : 0         :
2                      :  -> spaced_token_list                         : 0         :
...
```

**To Reproduce**
1. Install Nu on Windows with `cargo install -f nu --all-features`
2. Run `nu`
3. Type anything

**Expected behavior**
I expect the shell to read input normally and output only the requested information.

**Screenshots**

Windows Terminal (Preview) 0.7.3451.0
<img width="698" alt="nushell-possible-debugging-output" src="https://user-images.githubusercontent.com/3084059/71862673-7cd58700-30af-11ea-84cf-ddab81e1c512.png">

Powershell
<img width="661" alt="nushell-possible-debugging-output-powershell" src="https://user-images.githubusercontent.com/3084059/71863066-9925f380-30b0-11ea-87cd-7891582526cc.png">

**Configuration (please complete the following information):**
 - OS: Windows 10 Pro 1903 Build 188362.535
 - Version: 0.7.1
 - Features: All

**Comment by jonathandturner** [comment]
For 0.7.0 and later, you should use --features=stable instead of --all-features

**Comment by reillysiemens** [comment]
Ah, I missed that in the instructions. This fixes everything. Thank you! 😁
