### ISSUE TITLE
Why I can't modify $env.PATH in a custom command?

### ISSUE THREAD

**Issue by JasonMo1** [nushell/nushell#11665]
### Question

I wrote following script:
```nu
def patha [new_path: string] {
    $env.PATH = ($env.PATH | prepend $new_path)
    echo 'A path has been added to $env.PATH: ' $new_path | str join
}
```
and run it:
```nu
patha "/home/jasonmo/.local/bin"
```
but nothing happends. $env.PATH is the same as before.

**Comment by WindSoilder** [comment]
You need to use `def --env patha [new_path: string]`.   For more information, please check `help def`.

> --env - keep the environment defined inside the command
