### ISSUE TITLE
"detect columns" is 0-based

### ISSUE THREAD

**Issue by ineu** [nushell/nushell#11678]
### Describe the bug

`detect columns` names columns starting from index 0, which is inconsistent with `from` commands:
```
~ ❯ "foo bar baz" | detect columns -n
╭───┬─────────┬─────────┬─────────╮
│ # │ column0 │ column1 │ column2 │
├───┼─────────┼─────────┼─────────┤
│ 0 │ foo     │ bar     │ baz     │
╰───┴─────────┴─────────┴─────────╯
```
But all `from` commands are 1-based:
```
~ ❯ "foo bar baz" | from ssv -n -m 1
╭───┬─────────┬─────────┬─────────╮
│ # │ column1 │ column2 │ column3 │
├───┼─────────┼─────────┼─────────┤
│ 0 │ foo     │ bar     │ baz     │
╰───┴─────────┴─────────┴─────────╯
~ ❯ "foo,bar,baz" | from csv -n
╭───┬─────────┬─────────┬─────────╮
│ # │ column1 │ column2 │ column3 │
├───┼─────────┼─────────┼─────────┤
│ 0 │ foo     │ bar     │ baz     │
╰───┴─────────┴─────────┴─────────╯
~ ❯ "foo\tbar\tbaz" | from tsv -n
╭───┬─────────┬─────────┬─────────╮
│ # │ column1 │ column2 │ column3 │
├───┼─────────┼─────────┼─────────┤
│ 0 │ foo     │ bar     │ baz     │
╰───┴─────────┴─────────┴─────────╯
```

### How to reproduce

---

### Expected behavior

Parsing commands should be consistent. `detect columns` should start with `column1`, like the `from` subcommands.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.89.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 2c1560e281d65a50d90b30c42006755b364b4928                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (Arch Linux rust 1:1.75.0-1) |
| cargo_version      | cargo 1.75.0                                                     |
| build_time         | 2024-01-09 23:05:05 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment]
seems like it would be better for everything to be 0-indexed to me in order to stay consistent.

**Comment by ineu** [comment]
Probably yes, to me as a developer 0-based make more sense. The reason for 1-based is that more existing commands use it.

**Comment by NotTheDr01ds** [comment]
(Maybe) Related, from the help example for `parse`:

```Nushell
" @another(foo bar)   " | parse --regex '\s*(?<=[() ])(@\w+)(\([^)]*\))?\s*'
```

Results in `Capture0`, `Capture1` columns.  0-based, yes, but as long as this issue is pushing for consistency, perhaps it would make sense to make those `column0`/etc. as well?

It's minor, but it goes with the "consistency" theme here.

**Comment by ito-hiroki** [comment]
I'd like to address this if no one's in charge.
I'll make the subcommands (csv, tsv, ssv) 0-based.
Should I also fix the parse command to be `column0` from `capture0`?

**Comment by fdncred** [comment]
parse uses regex so I'd keep it capture0
