### ISSUE TITLE
Toml is incorrectly persisted with escaping

### ISSUE THREAD

**Issue by yoshuawuyts** [nushell/nushell#1167]
**Describe the bug**
Writing to toml, then reading back from it fails to parse. This is because the toml is persisted *with* escaping.

**To Reproduce**
Run
```sh
sys | get mem | to-toml | save /tmp/foob.toml
```

When inspecting the output, it's persisted as:

```toml
"free = 5975216000\n\"swap free\" = 2097148000\n\"swap total\" = 2097148000\ntotal = 16157468000\n"
```

**Expected behavior**
The toml should've been saved *without* escaping / as a string. Perhaps this is because of `"{:?}"` rather than `"{}"` formatting?

**Configuration (please complete the following information):**
 - OS: Linux
 - Version: latest
 - Optional features: none

**Comment by jonathandturner** [comment]
@yoshuawuyts - this isn't exactly discoverable, but the `save` command will do the conversion to toml for you automatically. The line above effectively is converting it twice. This ends up escaping the first string as it builds the second one.

**Comment by jonathandturner** [comment]
We should definitely detect this and warn about it

**Comment by yoshuawuyts** [comment]
@jonathandturner oh, I see! -- that's very neat!

Yeah a warning would be great, hah. I guess coming from older shells I'm very much used to every step in the pipeline requiring manual intervention rather than things "just working". Takes a while to get used to I guess 😅
