### ISSUE TITLE
Incongruity between `update cells --columns` and `update cells -c`

### ISSUE THREAD

**Issue by alxpettit** [nushell/nushell#11689]
### Describe the bug

When using `update cells -c`, the type table argument accepts lists (which was, for me, the expected behavior), but with `update cells --columns`, it does not. Note that the Nushell terminal acts as if both are using the same type:

```
/tmp/hi> update cells -c                                                                                                            01/30/2024 05:39:44 PM
Error: nu::parser::missing_flag_param

  × Missing flag argument.
   ╭─[entry #33:1:1]
 1 │ update cells -c
   ·              ─┬
   ·               ╰── flag missing table argument
   ╰────

/tmp/hi> update cells --columns                                                                                                     01/30/2024 05:39:46 PM
Error: nu::parser::missing_flag_param

  × Missing flag argument.
   ╭─[entry #34:1:1]
 1 │ update cells --columns
   ·              ────┬────
   ·                  ╰── flag missing table argument
   ╰────
```

### How to reproduce

1. `mkdir /tmp/hi`
2. `cd /tmp/hi`
3. `touch a b c d`
4. `ls | update cells --columns [ "name" ] { $in | str upcase }`

```
Error: nu::parser::type_mismatch

  × Type mismatch.
   ╭─[entry #25:1:1]
 1 │ ls | update cells --columns [ "name" ] { $in | str upcase }
   ·                             ─────┬────
   ·                                  ╰── expected table, found list<string>
   ╰────
```

### Expected behavior

I expected nu to correctly identify that the `[ "name" ]` argument is being applied to the columns flag variant of the command.

### Configuration

| key                | value                                                                                              |
| ------------------ | -------------------------------------------------------------------------------------------------- |
| version            | 0.89.0                                                                                             |
| branch             |                                                                                                    |
| commit_hash        |                                                                                                    |
| build_os           | linux-x86_64                                                                                       |
| build_target       | x86_64-unknown-linux-gnu                                                                           |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball)                                  |
| cargo_version      | cargo 1.75.0                                                                                       |
| build_time         | 1980-01-01 00:00:00 +00:00                                                                         |
| build_rust_channel | release                                                                                            |
| allocator          | mimalloc                                                                                           |
| features           | dataframe, default, extra, sqlite, trash, which, zip                                               |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, net, query, query json, query web, query xml, regex |

### Additional context

Contrast with `ls | update cells -c [ "name" ] { $in | str upcase }`

This produces expected output:

```
╭───┬──────┬──────┬──────┬───────────────╮
│ # │ name │ type │ size │   modified    │
├───┼──────┼──────┼──────┼───────────────┤
│ 0 │ A    │ file │  0 B │ 2 minutes ago │
│ 1 │ B    │ file │  0 B │ 2 minutes ago │
│ 2 │ C    │ file │  0 B │ 2 minutes ago │
╰───┴──────┴──────┴──────┴───────────────╯
```

**Comment by fdncred** [comment]
My guess is that the SyntaxShape for --columns/-c is set to Table when it should be a List.

**Comment by fdncred** [comment]
Yup, that's it. I'll put up a PR. Thanks!

**Comment by alxpettit** [comment]
Oh, awesome! I really didn't expect that quick a turnaround! :D Thanks!
