### ISSUE TITLE
`cp $file ~/path/` gives `is not a directory`

### ISSUE THREAD

**Issue by crides** [nushell/nushell#11683]
### Describe the bug

I haven yet to do any testing, but it _seems_ like after #11621, things like `cp $stuff ~/path/` doesn't work anymore:
```
Error:   × is not a directory
   ╭─[entry #12:1:1]
 1 │ cargo b -rFextra;cp target/release/nu ~/.local/bin/
   ·                                       ──────┬──────
   ·                                             ╰── is not a directory
   ╰────
```
However, the error is gone if the trailing `/` is removed. It's also fine if `~` is not included. This is a bit surprising because `~` isn't even a glob

### How to reproduce

shown above

### Expected behavior

treat `~/path/` and `~/path` the same for `cp` (and other FS commands if applicable)

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.89.1                                    |
| branch             | dev                                       |
| commit_hash        | 45af3de6ced6d291fa34b3e4a8c94d6e9ffff871  |
| build_os           | macos-aarch64                             |
| build_target       | aarch64-apple-darwin                      |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)       |
| rust_channel       | 1.73.0-aarch64-apple-darwin               |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)       |
| build_time         | 2024-01-29 10:28:03 -08:00                |
| build_rust_channel | release                                   |
| allocator          | mimalloc                                  |
| features           | default, extra, sqlite, trash, which, zip |
| installed_plugins  | from plist, to plist                      |

### Additional context

Last upstream I rebased to is <code>859f7b3dc add `$.extra_usage` to modules (#11649)</code>, and currently I'm on `c371d1a53 (upstream/main) fix exit_code handling when running a scripts with ctrlc (#11466)` to test that commit

**Comment by fdncred** [comment]
I noticed this with as well, that a trailing slash can confuse the operation. @WindSoilder can you take a look at this when you get a sec?

**Comment by crides** [comment]
Same problem with `../`

**Comment by WindSoilder** [comment]
Sure, I'll take a look today
