### ISSUE TITLE
Clear command should clear everything

### ISSUE THREAD

**Issue by stefnotch** [nushell/nushell#11693]
### Problem

The `clear` command only scrolls down, instead of clearing the history.
Tested with the Windows Terminal, and the VSCode Terminal.

### Describe the solution you'd like

I'd like it if the `clear` command fully cleared the history, just like it does in Git Bash. See also https://www.reddit.com/r/Nushell/comments/1ae7hmp/how_can_i_change_clear_behavior_like_bash_or_zsh/

Alternatively, a pull request that extends the `clear` command with a flag, like [`clear --all`, would be a solid way forward](https://github.com/nushell/nushell/issues/11693#issuecomment-1919635501).

### Describe alternatives you've considered

Opening my `config.nu` file (see `$nu.config-path`) and adding the following command to the end of the file

```nu
# Full term reset, cls, clear buffer, attributes off,
def clsterm [] {
$"(ansi esc)c(ansi clsb)(ansi cls)(ansi reset)(ansi home)"
}
```
Command is from [fdncred](https://www.reddit.com/user/fdncred/), at https://www.reddit.com/r/Nushell/comments/1ae7hmp/comment/kkc5tu8/?utm_source=share&utm_medium=web2x&context=3

### Additional context and details

```
~> version                                                                                          01/31/24 11:57:54 AM
╭────────────────────┬──────────────────────────────────────────╮
│ version            │ 0.88.1                                   │
│ branch             │                                          │
│ commit_hash        │ fd56768fdcc1acbebcb75745600fc7419f72833d │
│ build_os           │ windows-x86_64                           │
│ build_target       │ x86_64-pc-windows-msvc                   │
│ rust_version       │ rustc 1.72.1 (d5c2e9c34 2023-09-13)      │
│ rust_channel       │ 1.72.1-x86_64-pc-windows-msvc            │
│ cargo_version      │ cargo 1.72.1 (103a7ff2e 2023-08-15)      │
│ build_time         │ 2023-12-14 17:53:48 +00:00               │
│ build_rust_channel │ release                                  │
│ allocator          │ mimalloc                                 │
│ features           │ default, sqlite, trash, which, zip       │
│ installed_plugins  │                                          │
╰────────────────────┴──────────────────────────────────────────╯
```

**Comment by fdncred** [comment]
Did you try the suggestions I made in the /r/nushell?

**Comment by stefnotch** [comment]
@fdncred Oh lovely, I didn't expect to see the kind reddit commenter here as well. I tried the commands just now, and the results with the Windows Terminal are

- ansi cls: Adds a whole screen worth of new lines
- ansi clsb: Deletes everything that's offscreen
 - $"(ansi esc)c": Resets the screen (yay)

For completeness
- ansi esc: No effect?
- ansi reset: No effect?
- ansi home: Deletes the last few lines.

If you cannot seem to reproduce it, I'll happily hook you up with dev environment where you can reproduce it. (e.g. ssh or parsec or vscode live share) I'll also happily test whatever fixes you'd like me to try out.

**Comment by fdncred** [comment]
Maybe a gif that demonstrates what you're seeing would help. (ok, i see the pictures now)

I'm not sure what you mean under your completeness point. 
`ansi esc` is not intended to do anything by itself, nor is `ansi reset`. `ansi home` moves your cursor to the "home" position.

I don't see you running the custom command I posted.
```nushell
# Full term reset, cls, clear buffer, attributes off,
def clsterm [] {
  $"(ansi esc)c(ansi clsb)(ansi cls)(ansi reset)(ansi home)"
}
```
I'll post some comparisons on my system.

**Comment by fdncred** [comment]
starting position
![image](https://github.com/nushell/nushell/assets/343840/fc486504-865a-462f-a8ad-17b5b1aaa439)
after running the `clear` command
![image](https://github.com/nushell/nushell/assets/343840/fd9f27fe-f88c-476d-85d0-8725b31629fd)
after running the `ansi cls` command
![image](https://github.com/nushell/nushell/assets/343840/083ad218-aac1-4f83-8e70-3e52729cad16)
after running the `ansi clsb` command
![image](https://github.com/nushell/nushell/assets/343840/24f3da9e-538a-4ea7-803d-5cd9fc91ce57)
after running the `$"(ansi esc)c"` command
![image](https://github.com/nushell/nushell/assets/343840/08dc31b2-5693-424a-a029-e4151480b94f)
after running the `clsterm` custom command
![image](https://github.com/nushell/nushell/assets/343840/ad20153d-f1a8-4530-9eb8-90d0830b4898)

All these work the way I'd expect them to.

**Comment by stefnotch** [comment]
My expectation is that the `clear` command should work like the `clsterm` or `cls2` or `  $"(ansi esc)c"`.
As in, it should both clear the screen, and remove everything that is offscreen. After the clear command, I should no longer be able to scroll up.

The current behaviour is that it behaves like more like ansi cls. It's still possible to scroll back up to the old content.

**Comment by fdncred** [comment]
> My expectation is that the clear command should work like the clsterm or cls2 or   $"(ansi esc)c".
As in, it should both clear the screen, and remove everything that is offscreen. After the clear command, I should no longer be able to scroll up.

This is why nushell gives you the ability to create your own `clear` custom command to make it do exactly what you want. As it is now, I believe things are working as expected.

**Comment by fdncred** [comment]
You can write your own `clearall` custom command. I'm not sure why we need to add something else?

**Comment by fdncred** [comment]
I would not support adding a new command but I could see adding a parameter like `clear --all` to clear the screen and the back buffer. Crossterm has that functionality I believe that some motivated person could probably hook up.

**Comment by stefnotch** [comment]
`clear --all` sounds like an excellent option

**Comment by NotTheDr01ds** [comment]
Coming in late, but also see related [Discord question](https://discord.com/channels/601130461678272522/1194025952917856288/1194025952917856288).  My final solution there was:

```Nushell
print -n $"(ansi clear_entire_screen_plus_buffer)(ansi home)"
```

**Comment by NotTheDr01ds** [comment]
Slight improvement suggested.  Instead of:

```Nushell
def clsterm [] {
  $"(ansi esc)c(ansi clsb)(ansi cls)(ansi reset)(ansi home)"
}
```

It's a great use for an explicit `print` to avoid the extra newline that gets inserted at the top of the screen.  (Changing the name as well, while I'm at it):

```Nushell
def "clear all" [] {
  print -n $"(ansi esc)c(ansi clsb)(ansi cls)(ansi reset)(ansi home)"
}
```

Also, probably a bit of a long-term footgun (if/when other flags are added to `clear`), but:

```Nushell
def "clear --all" [] {
  print -n $"(ansi esc)c(ansi clsb)(ansi cls)(ansi reset)(ansi home)"
}
```

**Comment by ZzMzaw** [comment]
I was looking for this feature as well and I also think having it out of the box would help.
I just proposed a possible implementation in the PR if someone wants to have a look at it.

**Comment by T3sT3ro** [comment]
I also think `clear` should empty the scroll buffer by default. I got here exactly with the same issue: I used `clear` expecting it to clear my whole terminal, just like it does in other familiar shells. I don't think there is a workflow depending on the current default implementation of `clear`, or any advantage of going against the user expectations. Especially now, when `--all` has been added, I think it is safe to assume the more familiar and expected behavior is using it by default. Current default of scrolling could be moved to the `--scroll` flag if needed (so the same code just flipped logic and renamed flag).

I think the ultimate argument is user expectations. There is no advantage to sticking with the current default except the saving of time needed to correct this, while the new default would make it more familiar and intuitive to everybody.

**Comment by NotTheDr01ds** [comment]
@T3sT3ro I agree, and I was going to float a PR, but I see you've already done it - Thanks!

I'm all for being "different" when it's an improvement over other shells, but there doesn't seem to be any advantage here to the current behavior, so I also think we should match user-expectation.
