### ISSUE TITLE
Scoop error

### ISSUE THREAD

**Issue by Sevule** [nushell/nushell#11701]
### Describe the bug

When running "scoop update *", scoop treats all files in the current directory as packages to be checked for updates.

### How to reproduce

`scoop update *
`

### Expected behavior

I hope this can be fixed, "scoop update *" works fine in other shells.

### Screenshots

![image](https://github.com/nushell/nushell/assets/86825975/e9d97c46-146e-4637-b984-0750c61d30d4)

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.89.0                                               |
| branch             |                                                      |
| commit_hash        | 2c1560e281d65a50d90b30c42006755b364b4928             |
| build_os           | windows-x86_64                                       |
| build_target       | x86_64-pc-windows-msvc                               |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                  |
| rust_channel       | 1.73.0-x86_64-pc-windows-msvc                        |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                  |
| build_time         | 2024-01-09 20:24:38 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by WindSoilder** [comment]
By default, nushell will glob user input and pass them to external commands(scoop in your example).  You can try `scoop update "*"` to disable the behavior.

**Comment by Sevule** [comment]
> By default, nushell will glob user input and pass them to external commands(scoop in your example). You can try `scoop update "*"` to disable the behavior.

Thank you very much, this is very useful advice.
