### ISSUE TITLE
Missing links to website from repo and organization

### ISSUE THREAD

**Issue by yoshuawuyts** [nushell/nushell#1170]
I was trying to find the nushell website by looking at this repo, and subsequently the organization. But neither includes a link. Linking to the website from both would be valuable, and like, probably help people find their way around better (or at the least improve "SEO", hah).

## Screenshots

The repo doesn't have a link to the website.

![Screenshot 2020-01-08 16 11 39](https://user-images.githubusercontent.com/2467194/71989298-b46c3c80-3231-11ea-8627-f3117e0e180f.png)

The organization doesn't have a link to the website.

![Screenshot 2020-01-08 16 11 51](https://user-images.githubusercontent.com/2467194/71989321-bd5d0e00-3231-11ea-88dd-b49a1bfe7885.png)

**Comment by Delapouite** [comment]
I agree, adding a link to https://www.nushell.sh/ in the GitHub repo header would help newcomers

![image](https://user-images.githubusercontent.com/39315/77233036-138cec80-6ba5-11ea-8f8d-b7ec497c431c.png)

**Comment by jonathandturner** [comment]
Fixed!
