### ISSUE TITLE
Internal error: can't run a predeclaration without a body

### ISSUE THREAD

**Issue by nblumhardt** [nushell/nushell#11711]
### Describe the bug

Hi! If parens rather than braces are used to define the body of a `def`, NuShell 0.89 will panic when invoking it:

<img width="599" alt="Screenshot 2024-02-03 at 7 23 17 am" src="https://github.com/nushell/nushell/assets/342712/d3e98540-b959-4d28-8da2-f0a2e2197045">

### How to reproduce

```
def a () (echo 1)
a
```

Backtrace is:

```
thread 'main' panicked at /Users/nblumhardt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-protocol-0.89.0/src/signature.rs:650:9:
Internal error: can't run a predeclaration without a body
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <nu_protocol::signature::Predeclaration as nu_protocol::engine::command::Command>::run
   3: nu_engine::eval::eval_call
   4: nu_engine::eval::eval_expression_with_input
   5: nu_engine::eval::eval_element_with_input
   6: nu_engine::eval::eval_block
   7: nu_cli::util::eval_source
   8: nu_cli::repl::evaluate_repl
   9: nu::run::run_repl
  10: nu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Expected behavior

Either reject the `def` or succeed when calling it.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.89.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | macos-aarch64                       |
| build_target       | aarch64-apple-darwin                |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) |
| rust_channel       | stable-aarch64-apple-darwin         |
| cargo_version      | cargo 1.75.0 (1d8b05cdd 2023-11-20) |
| build_time         | 2024-01-10 08:51:16 +10:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
it shouldn't panic, i agree, but isn't that invalid syntax? the block part needs to be in braces like this.
```nushell
def a () {
  echo a
}
```

**Comment by nblumhardt** [comment]
@fdncred thanks for taking a look!

I don't have the syntax knowledge to be able to answer; I wrote the definition the way I did originally because NuShell seems to be fairly expression-oriented, and the command my `def` is wrapping was multiline and therefore already had `()` around it.

I took a guess at that syntax being accepted and it was; I'm presuming that the panic is a disagreement between the frontend and backend about this point :-)

Either the syntax being rejected, or the `def` working, would both be reasonable solutions from my outside point of view 👍

**Comment by nblumhardt** [comment]
(Also, think I'm nearly a year into using NuShell daily across three OSes, love this project! Thanks for all of your work on it!)

**Comment by fdncred** [comment]
> I don't have the syntax knowledge to be able to answer; 

ok, then let me explain. that syntax is not correct. you can do it in one of two ways.

```nushell
def a () {
  echo a
}
```
or
```nushell
def a [] {
  echo a
}
```

**Comment by kubouch** [comment]
Panics with `def a [] (echo 4)` as well. We somehow fail silently in the parser when `{`s are `(`.
