### ISSUE TITLE
interactive onboarding experience?

### ISSUE THREAD

**Issue by yoshuawuyts** [nushell/nushell#1172]
## Introduction
I didn't quite *get* `nu` until I tried it for the first time. I come from a background of more traditional (posix) shells, and it's hard to understand what "typed streams" really mean until trying it for the first time.

As I wrote in https://github.com/nushell/nushell/issues/930#issuecomment-572104930, my first attempt at using nu was to install it, boot it, and try things out. This wasn't exactly *smooth*, and after some failed attempts at getting things working I decided to actually follow [the book](https://www.nushell.sh/book/).

## The downsides of a book as a medium
The book is great, but context-switching between my browser and `nu` introduces some friction. And as much as I hate to admit it, I did get distracted with Twitter, chat, and other other things open in my browser in the process of it. I would imagine for anyone learning something new, especially after-hours, this might actually be a reason why they stop midway onboarding.

Or perhaps people, like me, have a tendency to try things out the second they have it installed, and forget that there's a book we're supposed to read -- and then miss out on discovering most of what sets `nu` apart.

## Proposition: include an interactive tutorial
Something that might be great is if when `nu` is freshly installed on a system, we prompt people to run an interactive tutorial first.

```txt
$ nu
Welcome to nu. If you're new to `nu` run `nututor` to get started.

>
```

The spirit of this tutorial would be similar to that of `vimtutor(1)`: learn the tool by spending 5-10 minutes using it without the chance for any distractions. Other tutorials in this tradition include [nodeschool](https://nodeschool.io/#workshopper-list) and [rustlings](https://github.com/rust-lang/rustlings), though they have the disadvantage of not being included by the runtimes they're trying to teach, increasing the barrier to using them.

## Example
I would imagine the first chapter of the nu book, in interactive form could start somewhat like this:

```txt
$ nu
Welcome to nu. If you're new to `nu` run `nututor` to get started.

>
```
```txt
> nututor
Hello, and welcome to the Nushell project. The goal of this project is to
take the Unix philosophy of shells, where pipes connect simple commands
together, and bring it to the modern style of development.

This is an interactive tutorial. You can move to the next part by typing:
    nututor next

>
```
```txt
> nututor next
The first thing you’ll notice when you run a command like ls is that
instead of a block of text coming back, you get a structured table.

Task: run the `ls` command.

>
```
```txt
> nututor next
The table is more than just showing the directory in a different way.
Just like tables in a spreadsheet, this table allows us to work with
the data more interactively.

The first thing we’ll do is to sort our table by the name. To do this,
we’ll take the output from ls and feed it into a command that can
sort tables based on the contents of a column. This is done using
the `sort-by-name` command:

Task: run `ls | sort-by-name`

>
```

## Drawbacks
This would need to be built, and maintained which can cause some extra overhead. I'd argue however that onboarding is probably one of the most important things to get right, so it might be worth it.

Also any form of `nututor` should probably start small. Perhaps including a few examples to get people started, and then point people towards the book. This would already give people a chance to get hands-on experience with `nu`, which is the main goal.

## Unresolved Questions
Something interesting to consider is: how long should the "hi, welcome to nu -- if you're new run nututor" text be displayed? I'd argue it probably shouldn't just be once. But apply a heuristic along the lines of:
- either someone's completed nututor
- booted nu 10 times
- or disabled it as part of some config

That way people don't miss it the first time they run `nu`. But also still get the chance to learn it if they it months ago, never finished (or even started) the tutorial, and try picking up `nu` again at some later point. This could be weeks, or even months later so applying a time-based heuristic would probably not be great.

An even more minimal version of this could be to point people to the book based on the heuristics outlined above, and introducing any form of `nututor` command at a later point, solely to reduce the friction of jumping between the book and shell.

**Comment by thegedge** [comment]
We've discussed this and think it would be nice to have.

For now, `help <cmd>` comes with examples of how to use commands, so hopefully that makes things a little easier 🙂
