### ISSUE TITLE
Predence of assignment over the pipe for mutable lists

### ISSUE THREAD

**Issue by blueberrycarrot** [nushell/nushell#11725]
### Describe the bug

Correct with an immutable list:
```
~: let list = [] | append '1'
~: $list
╭───┬───╮
│ 0 │ 1 │
╰───┴───╯
```

Incorrect with a mutable list:
```
~: mut list = []
~: $list = $list | append '1'
╭───┬───╮
│ 0 │ 1 │
╰───┴───╯
~: $list
╭────────────╮
│ empty list │
╰────────────╯
```
Putting `()` around the rhs expression solves it, but it's inconsistent with the immutable behaviour, therefore counter-intuitive, therefore a source of hard to find bugs. If left as-is, script devs will have to train themselves to always put `()` around the rhs value as "best practice", which makes the code less readable, harder to write, etc.

### How to reproduce

See description.

### Expected behavior

Consistent behaviour between mutable and immutable assignments in terms of operator precedence.

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.89.0                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | windows-x86_64                                                                  |
| build_target       | x86_64-pc-windows-msvc                                                          |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21)                                             |
| rust_channel       | stable-x86_64-pc-windows-msvc                                                   |
| cargo_version      | cargo 1.75.0 (1d8b05cdd 2023-11-20)                                             |
| build_time         | 2024-02-03 14:13:19 +00:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | mimalloc                                                                        |
| features           | dataframe, default, extra, sqlite, static-link-openssl, trash, wasi, which, zip |
| installed_plugins  |                                                                                 |

**Comment by sholderbach** [comment]
Thanks for reporting it, the issue currently runs deeper than operator precedence, we have a separate parsing logic for the name binding with `let` and `mut` (inconsistency with `const`) and the reassignment and shorthand operators like `+=` are all implemented as operators with a separate logic. There precedence comes into play but all operators expect either a value (literal/variable) or a parenthesized expression.

I will close this in favor of the somewhat more general report in #12956
