### ISSUE TITLE
I forgot to add esc to exit the nushell window

### ISSUE THREAD

**Issue by 107295472** [nushell/nushell#11728]
### Question

Like windows, press esc to close the window

**Comment by fdncred** [comment]
I'd be closing the window all the time then because I have esc mapped to clear the repl command line buffer. 
```
  {
    name: clear
    modifier: none
    keycode: esc
    mode: [emacs vi_normal vi_insert]
    event: { edit: clear }
  }
```

**Comment by 107295472** [comment]
Okay, I want to close the window
