### ISSUE TITLE
Can't run umask

### ISSUE THREAD

**Issue by Schweber** [nushell/nushell#11731]
### Describe the bug

I can run `umask` normally in other shells but in nushell i get

```
umask                                                                                                       
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #1:1:1]
 1 │ umask
   · ──┬──
   ·   ╰── executable was not found
   ╰────
  help: No such file or directory (os error 2)
```

### How to reproduce

Run `umask` in nushell 0.89.0 on Nixos unstable.

### Expected behavior

`umask` is run normally

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.89.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball) |
| cargo_version      | cargo 1.75.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
It's apparently not in your path. I just ran it on macos and it works fine.

**Comment by fdncred** [comment]
if it's built into the shell binary, i could see how that would be a problem. you'd probably have to do `bash -c umask` maybe?

On MacOS, it's separate.
```
❯ which umask 
╭─#─┬command┬──────path──────┬───type───╮
│ 0 │ umask │ /usr/bin/umask │ external │
╰───┴───────┴────────────────┴──────────╯
```

**Comment by fdncred** [comment]
> The strange thing is, that which umask fails in bash as well but i can still run umask in bash.

This is because it's a built-in command like nibon7 said. In this context, built-in means all the code for it is built into the bash binary so it is not an external executable. This is why I said to try `bash -c umask` to see if you get a result. As long as bash is in your path, it should work.

**Comment by nibon7** [comment]
> I guess it's related to Nixos. I've asked in the help forum there but haven't gotten an answer yet.
> 
> The strange thing is, that `which umask` fails in bash as well but i can still run `umask` in bash.

Seems like gnu `which` doesn't list built-in command, and you can use `bash -c help` to get built-in shell command list.

**Comment by liff** [comment]
It would be useful to have a umask command, though. Could/should this issue be considered a feature request?

**Comment by liff** [comment]
Probably the reason it isn’t in coreutils is that it cannot be implemented as an external command for the same reason as `cd`: it modifies the state of the running process. At least that’s the way it’s on Linux. No idea what `/usr/bin/umask` does on macOS 😅
