### ISSUE TITLE
Table of Contents for Nu Book? 

### ISSUE THREAD

**Issue by KSXGitHub** [nushell/nushell#1175]
**Is your feature request related to a problem? Please describe.**
I wanted to read documentation via Nu Book. After selecting a language, I expect a ToC but found none.

**Describe the solution you'd like**
A ToC at the top or sidebar of every article.

**Describe alternatives you've considered**

**Additional context**

**Comment by notryanb** [comment]
@KSXGitHub Can you add this issue to the [nushell book repo](https://github.com/nushell/book/issues)?

**Comment by KSXGitHub** [comment]
done: https://github.com/nushell/book/issues/58
