### ISSUE TITLE
Confusing error for a lazy record

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11750]
### Describe the bug

Using the same `get` command on regular records and lazy ones gives a different error.  Reporting, because this got me confused for some time.

### How to reproduce

```Nushell
~> let record = {a: value, b: value, c: value}
~> $record | get 1
Error: nu::shell::type_mismatch

  × Type mismatch.
   ╭─[entry #42:1:1]
 1 │ $record | get 1
   ·               ┬
   ·               ╰── Can't access record values with a row index. Try specifying a column name instead
   ╰────

~> let lazy_record = lazy make --columns [a b c] --get-value { "value" }
~> $lazy_record | get 1
Error: nu::shell::incompatible_path_access

  × Data cannot be accessed with a cell path
   ╭─[entry #44:1:1]
 1 │ $lazy_record | get 1
   ·                    ┬
   ·                    ╰── record<a: string, b: string, c: string> doesn't support cell paths
   ╰────
```

### Expected behavior

Some other error, because "Data cannot be accessed with a cell path" isn't true for a lazy record.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.89.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2024-01-13 03:02:49 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

**Comment by fdncred** [comment]
I'd guess that the error for the lazy record should be the same a record.

**Comment by KAAtheWiseGit** [comment]
Yeah.

I think it's because `Record` and `LazyRecord` are technically speaking different `Value` variants, and `follow_cell_path` doesn't account for it inside `PathMember::Int` checks (but does in `PathMember::String`, hence the fact that it works fine in `get a`).
