### ISSUE TITLE
`to/from toml` doesn't use native TOML date format

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11751]
### Describe the bug

When converting dates to toml, dates are converted to a string instead of the TOML dates.  The same applies to the `from` conversion.

### How to reproduce

```Nushell
~> {date: 2024-02-02} | to toml
date = "2024-02-02 00:00:00 +00:00"
~> "dob = 1979-05-27T07:32:00-08:00" | from toml
╭─────┬───────────────────────────╮
│ dob │ 1979-05-27T07:32:00-08:00 │
╰─────┴───────────────────────────╯
```

### Expected behavior

Converting Nushell dates to TOML dates and visa versa.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.89.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2024-01-13 03:02:49 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

**Comment by KAAtheWiseGit** [comment]
@fdncred, TOML has first-class date/time support: <https://toml.io/en/v1.0.0#offset-date-time>

This allows to store dates in TOML without converting them to and from strings.

**Comment by fdncred** [comment]
Ah, ok. So, it has to be RFC3339 format. That should be an easy update somewhere in the to/from toml code for anyone interested in changing it.

**Comment by VinciTec** [comment]
PR #11846  seems to have correctly parsed the datetime into the RFC3339 format and works correctly for reading (`from toml`). However, writing to a TOML string (`to toml`) the found string stores the datetime as a TOML string entry instead of as a Datetime because it is surrounded by quotation marks ( " ). As it seems to me, this is not the way datetime should be stored according to the TOML specifications [https://toml.io/en/v1.0.0](https://toml.io/en/v1.0.0#offset-date-time).

## Example
```
~> {date: 2024-05-13} | to toml
date = "2024-05-13T00:00:00+00:00"
```
While the expected behavior is;
```
~> {date: 2024-05-13} | to toml
date = 2024-05-13T00:00:00+00:00
```
so just removing the quotation marks. I image this would be an easy change.

**Comment by KAAtheWiseGit** [comment]
@fdncred can You reopen this issue to track the `to toml` part of it, please?
