### ISSUE TITLE
`select (-1)` hangs Nushell forever

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11756]
### Describe the bug

`select (-1)` hangs the shell.  Interrupt signals no longer work, nor does any other input do anything.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.89.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2024-01-13 03:02:49 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

**Comment by crides** [comment]
Caused by [silent conversion](https://github.com/nushell/nushell/blob/cb4ca157fde7e3bb458dce3a1760cf7f1df93625/crates/nu-command/src/filters/select.rs#L123)

**Comment by KAAtheWiseGit** [comment]
Ah, I see.

I am working on `propose select` at the moment and I feel like it'd make sense to forbid cell path arguments altogether and use ints and strings instead.  I need to do a write-up on it somewhere
