### ISSUE TITLE
Sort function doesn't error on bad column name

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1176]
**Describe the bug**
Passing a bad column name to `sort-by` does not give an error

**To Reproduce**
1. Run `ls | sort-by abc`
2. See that you still get a table and no error

**Expected behavior**
The command should do a "did-you-mean" style error on the column name(s) if none are found.

**Comment by shaaraddalvi** [comment]
HI @thegedge, I have gone ahead and tried to fix this as a first contribution. I am pretty new to Rust and nushell both, so feedback is welcome! 😄

**Comment by shaaraddalvi** [comment]
Should we close this issue?

**Comment by thegedge** [comment]
Ah, yes. Closed by https://github.com/nushell/nushell/pull/1880
