### ISSUE TITLE
`return` can affect parent block/closure

### ISSUE THREAD

**Issue by IanManske** [nushell/nushell#11761]
### Describe the bug

A `return` statement in a closure can trigger an early return for it's parent caller.

### How to reproduce

Run this script, `spooky_return_at_a_distance.nu`:
```nushell
let f = {|$it|
  $it
}

print (["a: this should not be returned"] | reduce -f null {|it, acc|
  let returned = (do $f $it)
  "a: this should be returned"
})

# only difference from $f is that there is a `return` now
let g = {|$it|
  return $it
}

print (["b: this should not be returned"] | reduce -f null {|it, acc|
  let returned = (do $g $it)
  "b: this should be returned"
})
```

It will print:
```
a: this should be returned
b: this should not be returned
```

### Expected behavior

The output of the code above should be:
```
a: this should be returned
b: this should be returned
```

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.89.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 2c1560e281d65a50d90b30c42006755b364b4928                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (Arch Linux rust 1:1.75.0-1) |
| cargo_version      | cargo 1.75.0                                                     |
| build_time         | 2024-01-09 23:05:05 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by mdrv** [comment]
I was developing a custom script (that involves multiple custom commands) and this issue also occured to me as well. In a few occasion, though, `return` did go back to the parent command.

Nushell is on the same version v0.89 — just different architecture (`aarch64`).

**Comment by weirdan** [comment]
Nushell 0.97.1:

```console
$ nu spooky.nu
a: this should be returned
b: this should be returned
```
