### ISSUE TITLE
json `to nuon` escapes quotes

### ISSUE THREAD

**Issue by tryoxiss** [nushell/nushell#11764]
### Describe the bug

Converting JSON to NUON will escape the quotes used in the JSON syntax, despite not being part of a key or value.

### How to reproduce

1. `{ a: 1, b: 2, c: "str" } | to json | to nuon` (example, any JSON works)
2. See escaped quotes

### Expected behavior

It would produce the original nuon. Process:

```
{
    a: 1,
    b: 2,
   c: "str"
}
```

It then gets converted to JSON, which necesitates adding quotes around the variable names.

```
{
    "a": 1,
    "b": 2,
   "c": "str"
}
```

This is all correct so far. But when we convert it back to nuon, one of two things should happen:

1. It stays the same, as this is valud nuon.
2. It converts all keys which do not need to be strings to standard keys. These all being valid identifiers, no quotes should be present except for the ones around `str`

```
{
    a: 1,
    b: 2,
   c: "str"
}
```

Instead, the quotes are taken as part of the key and escaped

```
{
    \"a\": 1,
    \"b\": 2,
   \"c\": \"str\"
}
```

This is not correct for any key or value, as now the key is `"a"` instead of `a`. 

### Screenshots

![image](https://github.com/nushell/nushell/assets/94419893/6b234678-132d-4e87-bc89-a725d92b04e4)
![image](https://github.com/nushell/nushell/assets/94419893/533759b0-9a65-4480-b45c-64a1b1c285bb)
![image](https://github.com/nushell/nushell/assets/94419893/b3428676-0472-4d7a-9c1e-5c501caba300)

### Configuration

| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.87.1                                         |
| branch             |                                                |
| commit_hash        |                                                |
| build_os           | linux-x86_64                                   |
| build_target       | x86_64-unknown-linux-gnu                       |
| rust_version       | rustc 1.74.0 (79e9716c9 2023-11-13) (Homebrew) |
| cargo_version      | cargo 1.74.0                                   |
| build_time         | 2023-11-18 17:46:36 +00:00                     |
| build_rust_channel | release                                        |
| allocator          | mimalloc                                       |
| features           | dataframe, default, sqlite, trash, which, zip  |
| installed_plugins  |                                                |

### Additional context

My guess is that it is interpriting the JSON as valid nuon and attempting to convert it again.

**Comment by crides** [comment]
I think this is correct behaviour. `{ a: 1, b: 2, c: "str" }` is a record literal (which is a record). It is in nuon format, but it is not a serialized nuon string.

Same distinction between a JSON string in Javascript and a Javascript object.

Here, `to nuon` just serializes the JSON _string_ into nuon format (as a string)

**Comment by IanManske** [comment]
Yep, see crides' explanation.

The following code can accomplish what you intended:
```nushell
{ a: 1, b: 2, c: "str" } | to json | from json | to nuon
```

**Comment by tryoxiss** [comment]
Ahh, thank you! I wasn't entirely sure if this is correct but it felt really weird to me so I decided to report it.
