### ISSUE TITLE
files name in the form "[a] b.c" can't be copied

### ISSUE THREAD

**Issue by kurokirasama** [nushell/nushell#11762]
### Describe the bug

```nu
touch "[a] b.c"
mv `[a] b.c` a.c
```
Gives the error:
```nu
Error: nu::shell::file_not_found

  × File not found
   ╭─[entry #8:1:1]
 1 │ mv `[a] b.c` a.c
   ·    ────┬────
   ·        ╰── file not found
   ╰────
```
doing
```nu
mv "[a] b.c" a.c
```
works.

Same thing with `cp` and `rm`

### How to reproduce

Already done

### Expected behavior

in should move, copy or remove as expected

### Configuration

| key                | value                                                                                                                                                                                               |
| ------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.89.1                                                                                                                                                                                              |
| branch             | main                                                                                                                                                                                                |
| commit_hash        | c371d1a53533d4f199f2776cfcc178d672243274                                                                                                                                                            |
| build_os           | linux-x86_64                                                                                                                                                                                        |
| build_target       | x86_64-unknown-linux-gnu                                                                                                                                                                            |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                                                                                                                                                                 |
| rust_channel       | 1.73.0-x86_64-unknown-linux-gnu                                                                                                                                                                     |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                                                                                                                                                                 |
| build_time         | 2024-01-30 18:25:53 -03:00                                                                                                                                                                          |
| build_rust_channel | release                                                                                                                                                                                             |
| allocator          | mimalloc                                                                                                                                                                                            |
| features           | dataframe, default, extra, sqlite, trash, which, zip                                                                                                                                                |
| installed_plugins  | custom-value generate, custom-value generate2, custom-value update, from eml, from ics, from ini, from vcf, gstat, hist, inc, net, plot, port scan, query, query json, query web, query xml, xyplot |

**Comment by WindSoilder** [comment]
The issue lays inside the auto-completion, not the glob rules.  We need to adjust auto-completion rules
