### ISSUE TITLE
Using terminal editors and then resizing, causes random nu prompt stuff to mash up randomly with the editor

### ISSUE THREAD

**Issue by coolshaurya** [nushell/nushell#1177]
**Describe the bug**
When using any terminal editor like vim or nano or [kakoune], and then resizing the terminal and then typing or scrolling results in random nu terminal stuff on the screen and the editor not responding (see screenshots). I've used kitty st and xterm and all three show this bug. Using nu installs both with or without `--features=stable` show this problem. This is _really really really_ frustrating and makes nu _unusable_ for me. Related to issue #1173. Probably caused by PR #1056.

**To Reproduce**
1. Open a terminal editor like  vi or vim or nano or [kakoune]
1. resize your terminal window to any other size
1. then do any action like typing or scrolling 
1. watch the the terminal carnage

**Expected behavior**
the editor to work naturally _without_ crazy `nu` prompts in the middle and no responsiveness.

**Screenshots**
All screenshots use the kitty terminal emulator with two kitty "windows" ( see https://sw.kovidgoyal.net/kitty/index.html#tabs-and-windows). 

example with two kitty "windows" of my whole screen : 
![example](https://user-images.githubusercontent.com/32027323/72043148-72e19d00-32d6-11ea-80a8-8f9678911934.png)

with [kakoune]:

 Immediately after terminal resize :
![a](https://user-images.githubusercontent.com/32027323/72043164-7aa14180-32d6-11ea-985d-f8604f501883.png)

Scrolling after resize:
![b](https://user-images.githubusercontent.com/32027323/72043179-80972280-32d6-11ea-8757-5feb3106593e.png)

Random typing after resize:
![c](https://user-images.githubusercontent.com/32027323/72043187-85f46d00-32d6-11ea-835b-1c2478cacb8c.png)

with vim:

Random typing after resize:
![e](https://user-images.githubusercontent.com/32027323/72043293-ceac2600-32d6-11ea-9fb9-d5cdacd2499d.png)

Scrolling after resize:
![2020-01-09_11-20](https://user-images.githubusercontent.com/32027323/72043196-8b51b780-32d6-11ea-8440-739dde3164d0.png)

with nano:

 Immediately after terminal resize :
![f](https://user-images.githubusercontent.com/32027323/72043221-9c022d80-32d6-11ea-810d-389eb491579b.png)

Random typing after resize:
![g](https://user-images.githubusercontent.com/32027323/72043232-a4f2ff00-32d6-11ea-8074-72f4c68155ad.png)

Scrolling after resize:
![h](https://user-images.githubusercontent.com/32027323/72043231-a45a6880-32d6-11ea-9ed5-345e273227d8.png)

in xterm : 
![xterm](https://user-images.githubusercontent.com/32027323/72043581-8c371900-32d7-11ea-84f0-e854b3af44cb.png)

in st : 
![st](https://user-images.githubusercontent.com/32027323/72043593-93f6bd80-32d7-11ea-9619-91f342ab38f1.png)

**Configuration :**
 - OS: Manjaro Linux
 - Version 0.8.0
 - Terminal emulator : `kitty` and `st` and `xterm`
 - Installed using `--features=stable`

[kakoune]: https://kakoune.org/

**Comment by jonathandturner** [comment]
@coolshaurya - just to confirm: do you only see this behavior when you're running those applications form inside of Nu?

If you run them through bash, and you do the same steps, do you see the same thing?

**Comment by jonathandturner** [comment]
Re-read the report. I see.

@thegedge - looks like it's possibly from redirecting stdin when we shouldn't. We might need to split "non-stdin" and "stdin" externals

**Comment by thegedge** [comment]
I'll verify that's the problem, and try to tackle that issue this evening.

**Comment by thegedge** [comment]
Okay, this is unrelated to https://github.com/nushell/nushell/pull/1056. I found it was still happening in 41ebc6b

**Comment by thegedge** [comment]
Okay, I've been digging around to try to understand what's happening. It's somehow related to `popen.wait()`. A polling loop + `thread::sleep` is fine. I think we should probably revert 8cadc5a for now, and come back to investigate why a simple `popen.wait` isn't working.

**Comment by thegedge** [comment]
Okay, this is more complex than I anticipated. There's also something weird happening because of the async stream. My brain is failing tonight, so I'll try to figure something out tomorrow.

**Comment by thegedge** [comment]
https://github.com/nushell/nushell/pull/1211 should fix this. Not sure why `popen.wait()` does this. Perhaps related to SIGWINCH, and how it signals get propagated with `poll` versus `wait`. Will add it to my list to investigate it a little deeper later.
