### ISSUE TITLE
Make debug pretty print with --pretty flag

### ISSUE THREAD

**Issue by coolshaurya** [nushell/nushell#1178]
**Is your feature request related to a problem? Please describe.**
 the `debug` command should be able to pretty print for more legible text (using `{:#?}` instead of  `{:?}` )

**Describe the solution you'd like**
Add a `--pretty` flag to the `debug` command that enables pretty print

**Describe alternatives you've considered**
`debug` maybe can pretty-print by default.

**Additional context**
none

**Comment by jonathandturner** [comment]
We could make that the default, and make a flag like `--compact` to go back to the smaller print out
