### ISSUE TITLE
`headers`: incorrect error

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11780]
### Describe the bug

When passing a list to the `headers` command, it gives a `type_mismatch` error with a label `record`, even though there are no records involved.

### How to reproduce

```Nushell
~> [1 2 3] | headers 
Error: nu::shell::type_mismatch

  × Type mismatch.
   ╭─[entry #5:1:1]
 1 │ [1 2 3] | headers 
   ·  ┬
   ·  ╰── record
   ╰────
~> [[a b c] [1 2 3] [4 5 6]] | headers
Error: nu::shell::type_mismatch

  × Type mismatch.
   ╭─[entry #5:1:1]
 1 │ [[a b c] [1 2 3] [4 5 6]] | headers
   ·   ┬
   ·   ╰── record
   ╰────
```

### Expected behavior

I expected `headers` to convert `[[a b c] [1 2 3] [4 5 6]]` into a table `[[a b c]; [1 2 3] [4 5 6]]`.  But if that's not allowed, there should be a different error.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.89.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.72.1 (d5c2e9c34 2023-09-13) (Alpine Linux 1.72.1-r0) |
| cargo_version      | cargo 1.72.1                                                 |
| build_time         | 2024-01-13 03:02:49 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

**Comment by fdncred** [comment]
It should probably only work on records and tables but a better error for lists would be appreciated.
