### ISSUE TITLE
Make all (applicable) filesystem command signatures accept `...(rest)` instead of `<filename> ...(rest)`

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#11796]
### Related problem

Currently, filesystem command signatures that accept a `...(rest)` are inconsistent:

1. Some take a `filename` followed by a `...(rest)`:
   * `touch {flags} <filename> ...(rest)`
   * `rm {flags} <filename> ...(rest)`

2. Some take only a `...(rest)`:
   * `mkdir {flags} ...(rest)` (and `umkdir`)
   * `cp {flags} ...(paths)`
   * `mv {flags} <source> <destination>` (to be replaced by `umv {flags} ...(paths)`, so I'll go ahead and count it)

3. And `ls`, which accepts multiple filenames in both Linux (`ls`) and Windows (`Get-ChildItem "a","b"`) native implementations can accept multiple paths, only accepts a single pattern at the moment:
   * `ls {flags} (pattern)`

The first and third versions are not (easily) list-spreadable.  E.g.:

```Nushell
> mkdir testing; cd testing
> touch foo foobar barfoo
> let g = (glob foo*)
> rm ...$g
# missing filename error
> rm foo foobar
> umkdir ...$g
# Works
```

Also, at times I've found it desirable to use `glob` with `ls`, such as:

```Nushell
> let g = (glob **/* --exclude [**/target/** **/.git/** */])
> ls ...$g | where modified >= ((date now) - 1day)
```

However, this is not currently possible since `ls` only accepts a single glob pattern.

### Describe the solution you'd like

The "only `...(rest)`" implementation seems desirable here, since it allows list spreading.  It would be nice if the remaining command (`ls`, `touch`, and `rm`) signatures were updated to match the others.

### Describe alternatives you've considered

* It's possible to fallback to `each`, of course, although this pattern doesn't work for an `ls | where` easily.
* And for `<filename> ...(rest)` commands, it's possible to `rm ($list | first) ...($list | skip 1)` (thanks @Dorumin on Discord)

**Comment by NotTheDr01ds** [comment]
As a nice alternative, perhaps change all of them to be `<filenames> ...(rest)` but detect if `<filenames>` is a list and automatically handle it if so.

**Comment by IanManske** [comment]
Yeah, I could get behind making the signatures more consistent and spreadable using form `2.`. This could also help simplify the code and avoid bugs as #11212 highlights.

One thing to keep in mind for any PRs is that `ls` lists the current directory when given no args. So, there would have to be a condition to check that if the rest args are empty, then double check that `call.arguments` actually has no positional arguments.

**Comment by kuchta** [comment]
Regarding <filename> ...(rest) vs ...(rest) and spreading I think it should be possible to define rest command arguments in more general way that would encode the required number of arguments in the type signature that would allow to generate correct syntax documentation. Something like array destructuring (in nu psedo-code):

```
def cp [[src, ...rest, dest]: string]
```
