### ISSUE TITLE
Text selection doesn't work (Windows)

### ISSUE THREAD

**Issue by suttonbradley** [nushell/nushell#11795]
### Describe the bug

Not able to select text at all. Any usage of the shift key doesn't yield anything (shift + arrow key, shift + ctrl + arrow key, shift + home/end).

Happens with Windows terminal as well as vscode integrated terminal. Happens when booting nushell executable directly as well as when entering through Powershell via the `nu` command.

### How to reproduce

1. winget install nushell

### Expected behavior

select text

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.89.0                                   |
| branch             |                                          |
| commit_hash        | 2c1560e281d65a50d90b30c42006755b364b4928 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)      |
| rust_channel       | 1.73.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)      |
| build_time         | 2024-01-09 20:28:44 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by suttonbradley** [comment]
Appears to have been a bug involving the winget install, as installing from the github release page msi directly worked. Previously on 0.89, now on 0.90.1

**Comment by fdncred** [comment]
the release isn't published on winget yet

**Comment by suttonbradley** [comment]
Wasn't aware until looking at the release notes that the shift support was just added. Just got into nushell right before the release of 0.90.1 so I assumed it was a bug, not a yet-to-be-released feature.

Either way, love nushell so far. Thanks!!
