### ISSUE TITLE
Publish to scoop.sh for easier installation on Windows

### ISSUE THREAD

**Issue by yoshuawuyts** [nushell/nushell#1179]
I've been thinking about ways to make it easier to install Nu on Windows, and of all options [scoop](https://scoop.sh/) seems to be the easiest to setup. The flow feels quite similar to Homebrew, which should provide a reasonable experience for most.

My understanding is that we'd need to create a [json manifest](https://github.com/ScoopInstaller/Main/blob/master/bucket/ripgrep.json), and PR it to either to the [main bucket](https://github.com/ScoopInstaller/Main/blob/master/bucket/ripgrep.json) or [extras bucket](https://github.com/lukesampson/scoop-extras/tree/master/bucket). Once merged folks should be able to install `nu` by writing:

```sh
scoop install nushell
```

I'm raising this because getting started on with Nu on Windows takes a few steps, and updating every 3 weeks means manually repeating those steps each time. If it becomes easier to install Nu, the overall onboarding experience becomes easier for people, which will likely help drive adoption (and in turn happy users). Hope this makes sense!

## Example manifest

```json
{
    "homepage": "https://github.com/BurntSushi/ripgrep",
    "description": "Recursively searches directories for a regex pattern.",
    "license": "MIT",
    "version": "11.0.2",
    "architecture": {
        "64bit": {
            "url": "https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep-11.0.2-x86_64-pc-windows-msvc.zip",
            "hash": "0be0279591412e12b0b92d5fda0707ebeceb9c6a51472e99b46fd4d25f13b6ef"
        },
        "32bit": {
            "url": "https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep-11.0.2-i686-pc-windows-msvc.zip",
            "hash": "9408d9a49abc38768377378aa70c0d6615c06bbd0fd959048e1bbb7b261c3fdd"
        }
    },
    "bin": "rg.exe",
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/BurntSushi/ripgrep/releases/download/$version/ripgrep-$version-x86_64-pc-windows-msvc.zip"
            },
            "32bit": {
                "url": "https://github.com/BurntSushi/ripgrep/releases/download/$version/ripgrep-$version-i686-pc-windows-msvc.zip"
            }
        }
    },
    "suggest": {
        "vcredist": "extras/vcredist2015"
    }
}
```

## References
- [App Manifests](https://github.com/lukesampson/scoop/wiki/App-Manifests)
- https://scoop.sh/
- [buckets overview](https://github.com/lukesampson/scoop/blob/master/buckets.json)
- [scoop on GitHub](https://github.com/lukesampson/scoop)

**Comment by jonathandturner** [comment]
Sounds good.

Some other Windows things we might also want to explore as we try to figure out better ways to support it:

* Chocolatey - I don't use it, but I have heard other folks talking about it. https://chocolatey.org/packages
* Installable .exe or .msi file that automates the steps you mention

**Comment by mborejdo** [comment]
Currently scoop seems not to work (without a full path) in nu, as it is a cmd-file.
Making (scoop.)cmd work first (https://github.com/nushell/nushell/issues/992) seems currently needed to offer better windows-integration (as many tools use the cmd extension)

**Comment by littleli** [comment]
I created scoop bucket [here](https://github.com/littleli/scoop-garage). I would like to promote this to at least to 'extras' bucket. Meanwhile open for evaluation if anyone wants.

**Comment by littleli** [comment]
It turns out [nushell](https://github.com/ScoopInstaller/Main/blob/master/bucket/nu.json) is already included in the official main scoop bucket.

**Comment by thegedge** [comment]
@littleli Since I know nothing about scoop, does that mean we can close this issue? 🙂

**Comment by mborejdo** [comment]
Since cmd files are supported now, I can use nushell daily. Installing and running nu on windows is a much better experience now
