### ISSUE TITLE
Panic when spreading a list to `mkdir`

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#11794]
### Describe the bug

`mkdir` is one of the few filesystem commands that seems to be defined such that *all* directory names are `...(rest)`.  But when spreading a list to `mkdir` Nu panics.

### How to reproduce

```Nushell
> mkdir testdir; cd testdir
> mkdir a b
> ls
╭───┬──────┬──────┬──────┬───────────────╮
│ # │ name │ type │ size │   modified    │
├───┼──────┼──────┼──────┼───────────────┤
│ 0 │ a    │ dir  │  0 B │ 3 minutes ago │
│ 1 │ b    │ dir  │  0 B │ 3 minutes ago │
╰───┴──────┴──────┴──────┴───────────────╯
> rm a b
> mkdir ...["a","b"]
thread 'main' panicked at crates\nu-command\src\filesystem\mkdir.rs:67:18:
already checked through directories
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected behavior

Create the directories in the list.

### Configuration

Originally found on 0.89 Linux.  Reproduced just now on:

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.90.1                                               |
| branch             |                                                      |
| commit_hash        | c2992d5d8b8541b64e9fc1440ed2917fc9b757f7             |
| build_os           | windows-x86_64                                       |
| build_target       | x86_64-pc-windows-msvc                               |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                  |
| rust_channel       | 1.73.0-x86_64-pc-windows-msvc                        |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                  |
| build_time         | 2024-02-07 02:25:54 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

### Additional context

Note that `cp` works correctly:

```Nushell
> mkdir testing; cd testing
> touch a b c
> mkdir d
> cp ...[a b c d]
╭───┬──────┬──────┬──────┬──────────────╮
│ # │ name │ type │ size │   modified   │
├───┼──────┼──────┼──────┼──────────────┤
│ 0 │ a    │ file │  0 B │ a minute ago │
│ 1 │ b    │ file │  0 B │ a minute ago │
│ 2 │ c    │ file │  0 B │ a minute ago │
│ 3 │ d    │ dir  │  0 B │ now          │
│ 4 │ d\a  │ file │  0 B │ a minute ago │
│ 5 │ d\b  │ file │  0 B │ a minute ago │
│ 6 │ d\c  │ file │  0 B │ a minute ago │
╰───┴──────┴──────┴──────┴──────────────╯
```

**Comment by NotTheDr01ds** [comment]
Ah, nevermind - This will be fixed when `umkdir` replaces `mkdir`.  Should I go ahead and close it?

**Comment by kubouch** [comment]
Let's not close it until the replacement is complete. AFAIK we don't have umkdir PR up yet, so fixing this would still help.

The `expect()` in the original code should not be there, and it should be an easy fix to replace it with ShellError.

**Comment by kubouch** [comment]
(Nevermind, we already have `umkdir` merged in, so we might as well remove the old `mkdir` soon.)

**Comment by fdncred** [comment]
Agreed. We should probably move mkdir to mkdir-old and umkdir to mkdir soon.

**Comment by NotTheDr01ds** [comment]
Given that, you might want to remove the good-first-issue tag?  And if you want to close it at the same time (given the "soon" transition), I don't mind either, of course.
