### ISSUE TITLE
the `$env.config.hooks.env_change.PWD` doesn't work on android

### ISSUE THREAD

**Issue by shenjiangqiu** [nushell/nushell#11805]
### Describe the bug

I was trying to use zoxide and nushell on android device. but that the `cd` command cannot add the directory into databse. then I find the `$env.config.hooks.env_change.PWD` didn't work because I can manually add the path using zoxide.

### How to reproduce

use cross to build nushell into android. (for openssl config. copy the example configure in cross.toml)

run nushell in termux.

### Expected behavior

when `$env.config.hooks.env_change.PWD` is set for zoxide add -- $path. for every time cd is called. zoxide should add the path to db.

### Configuration

~> version | transpose key value |to md --pretty
| key                | value                                                   |
| ------------------ | ------------------------------------------------------- |
| version            | 0.90.1                                                  |
| branch             |                                                         |
| commit_hash        |                                                         |
| build_os           | linux-x86_64                                            |
| build_target       | aarch64-linux-android                                   |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                     |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                     |
| build_time         | 2024-02-07 21:38:14 +00:00                              |
| build_rust_channel | release                                                 |
| allocator          | mimalloc                                                |
| features           | default, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  |                                                         |
~>

**Comment by fdncred** [comment]
I'm kind of skeptical about this. I think it's more likely a configuration problem. I've used zoxide for year, but I also don't run android. Why wouldn't it work I wonder?

**Comment by shenjiangqiu** [comment]
> I'm kind of skeptical about this. I think it's more likely a configuration problem. I've used zoxide for year, but I also don't run android. Why wouldn't it work I wonder?

I have been using nushell in windows and mac, everything works fine. I tried it in android yesterday and it fails to work.

Things I have tested:
$env.config.hooks.env_change.PWD is correctly set.
zoxide can correctly work in manual mode.

**Comment by shenjiangqiu** [comment]
> I'm kind of skeptical about this. I think it's more likely a configuration problem. I've used zoxide for year, but I also don't run android. Why wouldn't it work I wonder?

I found the reason. I'll try to figure out the solution

**Comment by fdncred** [comment]
Please share if you can. It could benefit others.
