### ISSUE TITLE
How to expand Windows Shell Shortcuts like `%LocalAppData%`?

### ISSUE THREAD

**Issue by ni554n** [nushell/nushell#11821]
### Additional context and details

```nu
~> nvim "%LocalAppData%\nvim\init.lua"                                                            1 02/10/24 02:44:03 AM
Error:   × Invalid literal
   ╭─[entry #6:1:1]
 1 │ nvim "%LocalAppData%\nvim\init.lua"
   ·                           ────┬────
   ·                               ╰── unrecognized escape after '\' in string
   ╰────
```

**Comment by maxomatic458** [comment]
@ni554n you can do ``$env.LOCALAPPDATA``
but im not sure how you would expand this to a path
``$env.LOCALAPPDATA\some\path`` does not seem to work

**Comment by fdncred** [comment]
The nushell equivalent is to use string interpolation.
```nushell
 nvim $"($env.LOCALAPPDATA)/nvim/init.lua"
```

**Comment by maxomatic458** [comment]
thats pretty confusing for such a basic thing in my opinion.
I think something like this ``$env.LOCALAPPDATA\some\path`` should also work.
