### ISSUE TITLE
`commandline --cursor` returns string

### ISSUE THREAD

**Issue by kit494way** [nushell/nushell#11825]
### Describe the bug

`commandline --cursor` returns the current cursor position, but its type is a string.

### How to reproduce

```nu
> commandline --cursor | describe
string
```

### Expected behavior

```nu
> commandline --cursor | describe
int
```

### Configuration

| key                | value                                                                     |
| ------------------ | ------------------------------------------------------------------------- |
| version            | 0.90.1                                                                    |
| branch             |                                                                           |
| commit_hash        | c2992d5d8b8541b64e9fc1440ed2917fc9b757f7                                  |
| build_os           | linux-x86_64                                                              |
| build_target       | x86_64-unknown-linux-musl                                                 |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                                       |
| rust_channel       | 1.73.0-x86_64-unknown-linux-gnu                                           |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                                       |
| build_time         | 2024-02-07 02:23:24 +00:00                                                |
| build_rust_channel | release                                                                   |
| allocator          | mimalloc                                                                  |
| features           | dataframe, default, extra, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  | query, query json, query web, query xml                                   |

**Comment by fdncred** [comment]
Interesting. Good catch. That should be an easy fix.
