### ISSUE TITLE
Nushell autocomplete interfering with commands autocomplete

### ISSUE THREAD

**Issue by dougg0k** [nushell/nushell#11828]
### Describe the bug

When I type a command expecting an auto complete, it offers me folders and files as auto complete, doesnt matter the command.

### How to reproduce

Type any command with an space and press tab.

### Expected behavior

If I type a command let's say `git `, I expect to show me the possible usage that comes after it. Like `commit` and else. 

### Screenshots

![2024-02-11_14-15](https://github.com/nushell/nushell/assets/10801221/095d751c-88ae-4a14-81a5-26486fca784f)

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.90.1                                    |
| branch             |                                           |
| commit_hash        |                                           |
| build_os           | linux-x86_64                              |
| build_target       | x86_64-unknown-linux-gnu                  |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21)       |
| rust_channel       | stable-x86_64-unknown-linux-gnu           |
| cargo_version      | cargo 1.75.0 (1d8b05cdd 2023-11-20)       |
| build_time         | 2024-02-07 22:41:27 -03:00                |
| build_rust_channel | release                                   |
| allocator          | mimalloc                                  |
| features           | default, extra, sqlite, trash, which, zip |
| installed_plugins  |

**Comment by maxomatic458** [comment]
You need to download and import completions to nushell first
https://github.com/nushell/nu_scripts/tree/main/custom-completions

**Comment by maxomatic458** [comment]
There should be completions for builtin commands

For external commands you need to get them from the repo above

**Comment by dougg0k** [comment]
Why nushell doesnt have out-of-the-box autocomplete for anything and everything? Even bash does, but just barebones.

**Comment by maxomatic458** [comment]
i think nushell aims to be as modular & "unbloated" as possible. Thats why the completions arent built in.
it might be cool to have the option to install completions for common tools when first starting nushell.

**Comment by dougg0k** [comment]
At least if there were an plugin that does all automatically rather than these custom completions that have to do all by hand.

Here is a reference to a similar idea https://github.com/marlonrichert/zsh-autocomplete/

**Comment by maxomatic458** [comment]
they dont actually need to be built by hand, they can be generated from a help page (i think the repo also includes a script for that and like hundreds of autogenerated completions)

**Comment by dougg0k** [comment]
Yeah, I just found that there seem to be a way to make use of a tool called carapace that does all the autocomplete.

https://github.com/nushell/nushell/blob/main/crates/nu-utils/src/sample_config/default_config.nu#L213C38-L213C56

https://github.com/rsteube/carapace-bin

**Comment by maxomatic458** [comment]
yea you can also use that.
But from my experience its a bit slower than using one of nushells completions.

**Comment by dougg0k** [comment]
Maybe if it were written in Rust, could be the solution, because still, thoise nushell completions are only a handful.

**Comment by maxomatic458** [comment]
there are quite a few if you also count the autogenerated ones: https://github.com/nushell/nu_scripts/tree/main/custom-completions/auto-generate/completions

but its possible that some of them dont work in the latest nushell version

**Comment by dougg0k** [comment]
Hm.

It seems that carapace are also doing all by hand.

**Comment by dougg0k** [comment]
Just to add, I got the completer working with no errors with

```
let external_completer = {|spans|
		let carapace_completer = {|spans|
				carapace $spans.0 nushell ...$spans
				| from json
				| if ($in | default [] | where value == $"($spans | last)ERR" | is-empty) { $in } else { null }
		}
		let zoxide_completer = {|spans|
			$spans | skip 1 | zoxide query -l $in | lines | where {|x| $x != $env.PWD}
		}

		let expanded_alias = scope aliases | where name == $spans.0 | get -i 0 | get -i expansion
		let spans = if $expanded_alias != null  {
				$spans | skip 1 | prepend ($expanded_alias | split row " " | take 1)
		} else {
			$spans
		}

		match $"($spans.0) " {
			__zoxide_z | __zoxide_zi => $zoxide_completer,
			_ => $carapace_completer
		} | do $in $spans
}
```

Example in the cookbook is not 100%. Their complete example didnt work, then I adapted some parts and removed deprecated errors from another and it worked.
