### ISSUE TITLE
External Shell Spawning Create Inconsistent Environment Variable Key

### ISSUE THREAD

**Issue by Embers-of-the-Fire** [nushell/nushell#11839]
### Describe the bug

I'm trying to use poetry, the Python env manager, with nushell on Windows. However, when I execute the `poetry shell` command (which theoretically spwans a new shell), the name of the `$env.Path` will change to `$env.PATH`.
Since windows' environment variable system is case-insensitive but nushell's is case-sensitive, this will throw an error in nushell but won't in other windows shell.

### How to reproduce

Run `poetry shell` in nushell.

### Expected behavior

The name of the environment variable key should be consistent.
Maybe nushell can allow insensitive call only on windows?

### Screenshots

With poetry shell:

![within-poetry](https://github.com/nushell/nushell/assets/106362488/18548e9f-92fd-4a90-9bcf-1060a76bffee)

Pure nushell:

![pure-nushell](https://github.com/nushell/nushell/assets/106362488/915b29cc-2570-49f0-8a69-131a8ff71d06)

### Configuration

❯ version | transpose key value | to md --pretty
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.90.1                                   |
| branch             |                                          |
| commit_hash        | c2992d5d8b8541b64e9fc1440ed2917fc9b757f7 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)      |
| rust_channel       | 1.73.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)      |
| build_time         | 2024-02-07 02:25:09 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
It kind of looks like poetry doesn't support or recognize nushell properly. There are some issues about nushell and commits that haven't landed like this one https://github.com/python-poetry/poetry/commit/ebb91e235eec67897ef44af532241055fb0f30be

You might have better luck asking for help on our discord.
