### ISSUE TITLE
inconsistent comparison or parsing of CRLF line endings

### ISSUE THREAD

**Issue by Zoybean** [nushell/nushell#11835]
### Describe the bug

I have a file with mixed line endings, and I want to check the line endings of each line. I have defined a simple function to classify the line endings in a given string:
```nu
> let file = "hello\r\nworld\nhi"
> def lines-end [] {
  parse -r '(?<line>.*)(?<end>\r?\n)?' | update cells -c [end] {|e|
    match $e {
    "\r\n" => "crlf"
    "\n"   => "lf"
    _      =>  ""
    }
  }
}
```
However, this function mis-classifies `crlf` line-endings as `lf`.

So far, the only way I've found to correctly check for `\r` is parsing the whole line-and-ending in a single capture, and using `str ends-with`:
```nu
> def lines-end [] {
  parse -r '(?<line>.*(?:\r?\n)?)' | insert end {|r|
    if ($r.line | str ends-with "\r\n") {
      "crlf"
    } else if ($r.line | str ends-with "\n") {
      "lf"
    } else {
      ""
    }
  } |
  update cells -c [line] {|l|
    $l | lines | first
  }
}
> $file | lines-end
─#─┬─line──┬─end──
 0 │ hello │ crlf
 1 │ world │ lf
 2 │ hi    │ 
─#─┴─line──┴─end──
```

I'm not sure if this is as a result of `parse` incorrectly capturing matches that include `\r`, or if it is something to do with the `==` / `match` operators.

### How to reproduce

```nu
> def lines-end [] {
  parse -r '(?<line>.*)(?<end>\r?\n)?' | update cells -c [end] {|e|
    match $e {
    "\r\n" => "crlf"
    "\n"   => "lf"
    _      =>  ""
    }
  }
}
> "hello\r\nworld\nhi" | line-ends
─#─┬─line──┬─end──
 0 │ hello │ lf
 1 │ world │ lf
 2 │ hi    │ 
─#─┴─line──┴─end──
```

### Expected behavior

```
─#─┬─line──┬─end──
 0 │ hello │ crlf
 1 │ world │ lf
 2 │ hi    │ 
─#─┴─line──┴─end──
```

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.90.2                                    |
| branch             | main                                      |
| commit_hash        | 005b8b02b221c5cc200443006b16608e110482ae  |
| build_os           | windows-x86_64                            |
| build_target       | x86_64-pc-windows-msvc                    |
| rust_version       | rustc 1.74.1 (a28077b28 2023-12-04)       |
| rust_channel       | 1.74.1-x86_64-pc-windows-msvc             |
| cargo_version      | cargo 1.74.1 (ecb9851af 2023-10-18)       |
| build_time         | 2024-02-12 09:47:08 +08:00                |
| build_rust_channel | release                                   |
| allocator          | mimalloc                                  |
| features           | default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                           |

### Additional context

I figure there's probably some magic happening here to make sure parsing operations "just work" cross-platform, but it would be nice to be able to turn that magic off, e.g. with a flag or something.

**Comment by fdncred** [comment]
I think it's your regex because you're telling it to look for \r or \n and both \n and \r\n end with \n. you might be able to change your regex to something like (\r\n|\n) and have better success.

**Comment by Zoybean** [comment]
Just to dump my thought process: all that changed about the regex, between the one that worked and the one that didn't, was the labels and bracketing (in a way that should only affect labelling, not the contents of the matched substring):
- `(?<line>.*(?:\r?\n)?)` - this one works, and ignoring labels it should be equivalent to `(.*(\r?\n)?)`
- `(?<line>.*)(?<end>\r?\n)?` - this one doesn't work, and ignoring labels it should be equivalent to `(.*)(\r?\n)?`
In both cases, the outer bracketing serves no purpose besides labelling, so the resulting regexes should both be equivalent to `.*(\r?\n)?`. Which should similarly be equivalent to `.*(\r\n|\n)` which you suggested.

I'll acknowledge though that I've said a lot of "should".
I tried your suggestion (if I've understood it) but the output is no different:
```nu
def lines-end [] {
  parse -r '(?<line>.*)(?<end>\r\n|\n)?' | update cells -c [end] {|e|
    match $e {
      "\r\n" => "crlf"
      "\n"   => "lf"
      _      =>  ""
    }
  }
}
```

**Comment by NotTheDr01ds** [comment]
It looks to me like your first one is greedy-matching up-to-and-including the `\r`, which is why you are never seeing it in the resulting `end` match-group.

This seems to work for me, at least for the test case you presented:

```Nushell
def lines-end [] {
  parse -r '(?<line>[^\r\n]*)(?<end>\r?\n)?' | update cells -c [end] {|e|
    match $e {
    "\r\n" => "crlf"
    "\n"   => "lf"
    _      =>  ""
    }
  }
}
```

```
> "hello\r\nworld\nhi" | lines-end
╭───┬───────┬──────╮
│ # │ line  │ end  │
├───┼───────┼──────┤
│ 0 │ hello │ crlf │
│ 1 │ world │ lf   │
│ 2 │ hi    │      │
╰───┴───────┴──────╯
```

**Comment by Zoybean** [comment]
I hadn't even stopped to remember that `.` can match `\r` - I'd forgotten that it only excludes `\n`, not all line-end markers.
I've devised a slightly more complex regex that allows lines to contain `\r` that aren't at the end:
```nu
def lines-end [] {
  parse -r "(?<line>(?:[^\n]*[^\r\n])?)(?<end>\r?\n)?" |
  update cells -c [end] {|e|
    match $e {
    "\r\n" => "crlf"
    "\n"   => "lf"
    _      =>  ""
    }
  }
}
```
(I've written it out using `[^\n]` instead of `.` mostly for my own sake)
