### ISSUE TITLE
`mv $path_containing_glob_chars /path/to/dest` not working 

### ISSUE THREAD

**Issue by klesh** [nushell/nushell#11838]
### Describe the bug

`mv` command reports `file not found` when the source path contains glob characters like `[`

### How to reproduce

1. touch a[b].txt
2. let $f = "a[b].txt"
3. mv $f ab.txt
  × File not found
   ╭─[entry #56:1:1]
 1 │ mv $f ab.txt
   ·    ─┬
   ·     ╰── file not found
   ╰────

### Expected behavior

The variable should be treated as a literal path or `--literal` should be offered as an optional flag.

### Screenshots

![image](https://github.com/nushell/nushell/assets/61080/89c441ef-8eed-4327-b021-bbe1757a08c0)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.90.1                                   |
| branch             |                                          |
| commit_hash        | c2992d5d8b8541b64e9fc1440ed2917fc9b757f7 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)      |
| rust_channel       | 1.73.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)      |
| build_time         | 2024-02-07 02:25:09 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I'm guessing this is because the let statement is removing the quotes and the quotes may be required to treat the string as literal. @WindSoilder any ideas about this?

**Comment by klesh** [comment]
Hi, @fdncred . Thanks for following up on the issue. Would you happen to know any workaround?

**Comment by klesh** [comment]
@fdncred  Aah, never mind, `str | escape-glob` seems to be working.
