### ISSUE TITLE
Dark mode Nu shell doesn't have while line numbers

### ISSUE THREAD

**Issue by jasikpark** [nushell/nushell#1184]
Is this the correct behavior? Shouldn't the line numbers be in high-contrast?

<img width="749" alt="Screen Shot 2020-01-09 at 9 40 05 PM" src="https://user-images.githubusercontent.com/10626596/72123977-b9f87e00-3328-11ea-8a96-e6ab8e12c919.png">

**Comment by jonathandturner** [comment]
Agreed.

We probably don't want to not use black as a color, and either use the same green we use for the headers or just use white.
