### ISSUE TITLE
Behavior of `~` is inconsistent with user expectation

### ISSUE THREAD

**Issue by alxpettit** [nushell/nushell#11887]
### Describe the bug

Glob expansion and path expansion of special characters like `~` are usually expected to behave the same way in a shell. That is, if you have a string literal, no expansion/substitution should happen. This is not how Nushell currently behaves.

### How to reproduce

1. Create a tilda file. 
```nu
^mkdir '/tmp/~'
^touch '/tmp/~/1' '/tmp/~/2'
```
2. CD to /tmp and try to observe it:

```nu
cd /tmp/
ls '~'
```

### Expected behavior

I expect path handling commands like `ls` / `rm` / `cp` to not expand the tilda if it's part of a string literal. This would make its behavior consistent with the recent glob changes.

### Configuration

| key                | value                                                                                              |
| ------------------ | -------------------------------------------------------------------------------------------------- |
| version            | 0.90.2                                                                                             |
| branch             |                                                                                                    |
| commit_hash        |                                                                                                    |
| build_os           | linux-x86_64                                                                                       |
| build_target       | x86_64-unknown-linux-gnu                                                                           |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball)                                  |
| cargo_version      | cargo 1.75.0                                                                                       |
| build_time         | 1980-01-01 00:00:00 +00:00                                                                         |
| build_rust_channel | release                                                                                            |
| allocator          | mimalloc                                                                                           |
| features           | dataframe, default, extra, sqlite, trash, which, zip                                               |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, net, query, query json, query web, query xml, regex |

**Comment by alxpettit** [comment]
Note also that, although as it stands, `'` and `"` currently behave the same way with respect to ignoring expansions, it may be a better idea to copy the way Bash, Fish and others handle expansion -- which is to still do expansion when using `"`, but not `'`. Otherwise, some other mechanism will be needed to allow multi-space arguments to be expanded, while also giving the option to avoid this expansion if desired.

**Comment by CAD97** [comment]
> we'll need some other solution to multi-space arguments that have full expansion features

That would be `` `quoted bareword` `` syntax, iiuc.

**Comment by NotTheDr01ds** [comment]
As a workaround, something like:

```Nu
ls `./~`
```

... will disambiguate and allow access to the file, rather than interpreting it as "HOME".
