### ISSUE TITLE
Can nu try to not print multiple tables?

### ISSUE THREAD

**Issue by KSXGitHub** [nushell/nushell#1189]
**Is your feature request related to a problem? Please describe.**
Sometimes, when a directory has many children, some have very long name while the others short, `ls` in that directory will result in multiple table being printed.

I suspect this is because `nu` wants to print every row as soon as input stream emits a chunk of data, but when a cell is longer than its column size, it must create a new table to fit the new cell?

**Describe the solution you'd like**
Is there a way to delete previously printed lines even if it does not appear in current page? I know TUI applications such as Htop, Vim, and Nano can delete printed characters in current page. However, If there's no way to fix this without waiting for stream to complete then I would prefer a flag or configuration that tell `autoview` to waits for input stream to complete.

**Describe alternatives you've considered**

**Additional context**

**Comment by dcarosone** [comment]
This is the "table streaming" feature, and it can be a bit awkward I agree. It's intended to give you "a screenful" of table data at a time, but it can make a bit of a mess in the middle of a pipeline.

I think the answer probably lives in table metadata, where downstream steps look for a metadata tag to decide whether to generate output per-chunk or all at once at the end, and perhaps an internal "| buffer |" command that sets this metadata as well as allows other buffering manipulations, sizes, etc.

In the other direction, similar metadata to let commands know whether their output is going to another pipeline stage, or to the terminal, would help pick better defaults

**Comment by KSXGitHub** [comment]
Another option is just not use table. I have difficulty reading information from a table, especially tables with too many columns:
* It's hard to infer which cell belongs to which column when the header row is far above.
* It's hard to infer which cell belongs to which row when it placed far in the right.
