### ISSUE TITLE
0.90.1 regression: alt+d throws an error message

### ISSUE THREAD

**Issue by ineu** [nushell/nushell#11907]
### Describe the bug

When `alt+d` is pressed in the middle of a command line, it shows the error: `cat: write error: Broken pipe`. I have not redefined the key, so the default value is used:
```
╭──────────┬──────────────────────╮
│ mode     │ emacs                │
│ modifier │ KeyModifiers(ALT)    │
│ code     │ Char('d')            │
│ event    │ Edit([CutWordRight]) │
╰──────────┴──────────────────────╯
```

### How to reproduce

1. Type two characters, e.g. 'ab'
2. Move the cursor back one character using `ctrl+b` or `Left`
3. Press `alt+d`

### Expected behavior

Expected: `b` is erased, no error message
Actual: `b` is erased with error message

### Screenshots

![image](https://github.com/nushell/nushell/assets/24980/0868533e-9008-4186-8f4a-ad6cd4c9e080)

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.90.1                                                           |
| branch             | makepkg                                                          |
| commit_hash        | c2992d5d8b8541b64e9fc1440ed2917fc9b757f7                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (Arch Linux rust 1:1.75.0-2) |
| cargo_version      | cargo 1.75.0                                                     |
| build_time         | 2024-02-09 11:43:38 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment]
I can't reproduce this on linux or windows with the latest main branch. I wonder if it's already been fixed?

**Comment by ineu** [comment]
No, if it was from history, then it would appear immediately after typing `a`. As I described, it happens specifically on alt+d.
Also, this `LANG= nu` is to show how it looks in the english locale. My system locale is russian and the error message is also in russian which proves that it's an external error indeed.

> I wonder if it's already been fixed?
I'll try to build the latest master

**Comment by ineu** [comment]
No, see the same on b23fe30530ec876fa500a6c4d142696a33d145ab. I blame Nu because 0.90.1 includes a lof of Reedline changes, and CutWordRight comes from reedline. 

Downgrading to 0.89 fixes the issue, so it is definitely related to Nu or Reedline. Though, if you can't reproduce it, there must be some external factor (a system package, libc version, whatever) that impacts it.

**Comment by ineu** [comment]
Bisected it: e7a4af14cd8563d043690c613c7a5624fd0838ca. This commit pulls a version of reedline which brings few clipboard-related libraries, which could be the suspects

**Comment by Tastaturtaste** [comment]
I guess the issue is related to the use of the system clipboard, whereas before a local clipboard was used. Though I don't know *why* the system clipboard causes the issue.

**Comment by fdncred** [comment]
Ugh, why are clipboard crates such a pain. lol.

**Comment by ineu** [comment]
Found the reason: I had `wl-paste --watch cliphist store` autostarted on login. I reinstalled the system but didn't install the `cliphist` binary, so it was this command throwing errors. After installing `cliphist` it's all fine.

But this reveals a much larger problem: every edit/cut in Nushell is now copied to the system clipboard. This is bad for a number of reasons:
1. Convenience. Actions to put data into a clipboard (especially the system clipboard) must be explicit. If I edit a command line in a shell, I don't want the pieces of the command to appear in my clipboard (and especially overwrite the previous value). If I'm using the clipboard history, I don't want the real data to be buried under numerous random words/chars cut from a shell.
2. Security: I could be dealing with some sensitive data on the command line, like passwords. For example, I copy a command containing a password from my notes into the command line, then I edit, removing the password, then press Enter. I think I'm safe because my password is not stored in the shell history, but I am not: the password is now in the system clipboard which is even worse.

I'm sure the "shift+navigation" feature can be useful, but changing the clipboard behavior this way is a disaster. If this feature can not be implemented without interacting with the system clipboard, then at least it should be configurable by a user and default to false, so a user will have to implicitly say "Yes, I realize the consequences and agree to copy anything cut in the shell to the system clipboard".

**Comment by fdncred** [comment]
> every edit/cut in Nushell is now copied to the system clipboard

I don't believe that's true in all cases. There is a local clipboard that is used and only if the system_clipboard feature is enabled or local clipboard failes do you get the system_clipboard (which is arboard). This is all in here. Let me know if you think I'm reading it wrong. https://github.com/nushell/reedline/blob/main/src/core_editor/clip_buffer.rs

Also, you should feel free to submit a PR based on your input.

**Comment by ineu** [comment]
> only if the system_clipboard feature is enabled 

I'm using the Arch package, and according to `version` it's not enabled. Yet I see the behavior I've described.
```
~ ❯ version | get features
dataframe, default, extra, sqlite, trash, which, zip
```

**Comment by ineu** [comment]
Here's the demo of the vulnerability
![image](https://github.com/nushell/nushell/assets/24980/fcc5c7a6-3f7f-4379-b461-279c6c9c54bc)

**Comment by Tastaturtaste** [comment]
As far as I am aware there is only either the local clipboard or the system_clipboard. Since nushell now uses the system_clipboard feature for reedline by default, it's the system clipboard by default. I remember asking if it could be enabled and got the go-ahead, although maybe it wasn't clear to everyone that it would change _all_ clipboard functionality. 

I can't really speak to the surprising behavior of alt + d. But for the ctrl + C, ctrl + x commands at least it was very surprising for me _before_ the system_clipboard feature was enabled.

**Comment by ineu** [comment]
`ctrl+c` is fine (I believe you use Windows because in *nix `ctrl+c` means "interrupt the process") because it is an *explicit* action. If a user does this, it's his responsibility. Copying the data to the system clipboard is not the problem. The problem is doing it *implicitly*.

**Comment by Tastaturtaste** [comment]
Yeah, I am on windows. I guess there should be two "clipboards" then? One local and one system?

**Comment by ineu** [comment]
There are even more: in X11 there are three system clipboards. Though I'm no expert on this.

What I know for sure is that CutWordRight should never use a system clipboard.

**Comment by WindSoilder** [comment]
I think it's already handled by [reedline/](https://github.com/nushell/nushell/pull/12179)
Can we close it?
