### ISSUE TITLE
panic when too many arguments to custom command?

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#11930]
### Describe the bug

i thought we had seen that before but i could reproduce it recently

### How to reproduce

1. define the following command
```nushell
def foo [a: float, b: float, c: float, d: float] {}
```
2. type `foo 1 2 3 4` and it works fine
3. type `foo 1. 2. 3. 4.` and it works fine
4. type `foo -1 1 -1 1` and it panics on the last `1` with
```
thread 'main' panicked at crates/nu-parser/src/parser.rs:777:28:
index out of bounds: the len is 2 but the index is 3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected behavior

i expected Nushell not to panic and the command to do nothing as the other calls

### Configuration

| key                | value                                                                |
| ------------------ | -------------------------------------------------------------------- |
| version            | 0.90.2                                                               |
| branch             |                                                                      |
| commit_hash        | cb67de675e69fb42d9ac6c9baa3f32c61dce9c26                             |
| build_os           | linux-x86_64                                                         |
| build_target       | x86_64-unknown-linux-gnu                                             |
| rust_version       | rustc 1.74.1 (a28077b28 2023-12-04)                                  |
| rust_channel       | 1.74.1-x86_64-unknown-linux-gnu                                      |
| cargo_version      | cargo 1.74.1 (ecb9851af 2023-10-18)                                  |
| build_time         | 2024-02-16 14:31:51 +01:00                                           |
| build_rust_channel | release                                                              |
| allocator          | mimalloc                                                             |
| features           | default, sqlite, trash, which, zip                                   |
| installed_plugins  | clipboard copy, clipboard paste, gstat, nu_plugin_explore, query git |

**Comment by weirdan** [comment]
It doesn't panic anymore.
