### ISSUE TITLE
cd to a directory by just typing its path

### ISSUE THREAD

**Issue by KSXGitHub** [nushell/nushell#1193]
**Is your feature request related to a problem? Please describe.**
ZSH allows me to `cd` to a directory by just typing its path (which starts with `~/`, `./`, or `/`). For example: Typing "`~/my-projects` <kbd>enter</kbd>" is equivalent to "`cd ~/my-projects` <kbd>enter</kbd>"

**Describe the solution you'd like**
When a command starts with either `~/`, `./`, or `/`, chdir to that path.

**Describe alternatives you've considered**

**Additional context**

**Comment by jonathandturner** [comment]
This is supported in 0.12.0 and later
