### ISSUE TITLE
Inconsistent external program execution

### ISSUE THREAD

**Issue by DoumanAsh** [nushell/nushell#11940]
### Describe the bug

When running command as:
```
^"C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe"
```

You're successful

If you attempt to add argument:
```
^"C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe" -products *
```

You get error for path to be too long
This actually makes no sense as this path doesn't even hit 255 characters

```

  × External command failed
   ╭─[entry #2:1:1]
 1 │ ^"C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe" -products *
   ·  ───────────────────────────────────┬──────────────────────────────────
   ·                                     ╰── can't run executable
   ╰────
  help: The filename or extension is too long. (os error 206)
```

### How to reproduce

Described above

### Expected behavior

Execute long commands with arguments successfully

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.90.1                                               |
| branch             |                                                      |
| commit_hash        | c2992d5d8b8541b64e9fc1440ed2917fc9b757f7             |
| build_os           | windows-x86_64                                       |
| build_target       | x86_64-pc-windows-msvc                               |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                  |
| rust_channel       | 1.73.0-x86_64-pc-windows-msvc                        |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                  |
| build_time         | 2024-02-07 02:25:54 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by DoumanAsh** [comment]
As work-around you can run this command in `cmd.exe` or any other shell

**Comment by WindSoilder** [comment]
I think it's because when you run an external command(vswhere.exe), `*` is auto-expand as a glob.

So to disable the globbing behavior, you need to quote around `*` using single quote or double quote.

I believe it works:
```
^"C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe" -products "*"
```

**Comment by DoumanAsh** [comment]
Huh I see, this is unexpected, but that explains my troubles trying to re-write powershell scripts
Thanks it indeed works
