### ISSUE TITLE
Crash when selecting second to last char of an CLI argument

### ISSUE THREAD

**Issue by matthias-buttgereit** [nushell/nushell#11959]
### Describe the bug

When writing any arbitrary word as an command and following it with a second word as an argument, moving the cursor (currently at the very end of the line) one to the left (via `arrow-key`) and trying to select the second to last character (via `shift + arrow-key`) results in nushell crashing.

### How to reproduce

1. Type in a word, e.x. `cargo`
2. Follow with a space and a second word, ex. `run`
3. Move the cursor one to the left, using the left `arrow-key`
4. Try to select the letter left of the cursor by using `shift + arrow-key`

### Expected behavior

I expected the second to last word to be highlighted and the cursor's position moved one to the left.

### Screenshots

![Screenshot 2024-02-24 134917](https://github.com/nushell/nushell/assets/65292669/5e126ca0-73ea-44ce-b4ef-28b956278a3a)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.90.1                                   |
| branch             |                                          |
| commit_hash        | c2992d5d8b8541b64e9fc1440ed2917fc9b757f7 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)      |
| rust_channel       | 1.73.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)      |
| build_time         | 2024-02-07 02:25:09 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
This has already been fixed.
