### ISSUE TITLE
Make err+out> output stderr before stdout

### ISSUE THREAD

**Issue by aaronliu0130** [nushell/nushell#11956]
### Related problem

Currently, despite how different out+err> and err+out> seem, they both output to a file: stdout first, stderr second

### Describe the solution you'd like

err+out> should put the stderr output in the file first before putting the stdout output

**Comment by fdncred** [comment]
I believe the point of the two names is so that you don't have to remember if it's o+e or e+o.

**Comment by aaronliu0130** [comment]
Probs, but it'd be more logical for them to output in a different order.

**Comment by WindSoilder** [comment]
Sorry, I don't think it's possible.  err+out is equal to out+err.  It just means that redirect both stdout and stderr to a file.  

I believe the order is depends on the external program itself

**Comment by aaronliu0130** [comment]
Hmm... I just tested this with a test program, and that's right, but contrary to what another program does... that program intersperses the output, yet nushell separates them, but doesn't do that for my test program. Weird.
