### ISSUE TITLE
mkdir does not error our when directory already exists

### ISSUE THREAD

**Issue by sandorex** [nushell/nushell#1196]
**Describe the bug**
Running `mkdir` on an existing directory does not throw an error

**To Reproduce**
1.  run `mkdir test`
2.  run `mkdir test` again

**Expected behavior**
It show throw an error saying the directory already exists

**Configuration (please complete the following information):**
 - OS: Windows
 - Version: 8.0 (master)

**Comment by alexxbb** [comment]
It doesn't raise an error in Linux either. I actually find this behaviour preferable, like why error out if you got what you asked - a directory. But maybe we could have an option like `mkdir foo --check` or something.
On the Rust side of things it calls to `std::fs::create_dir_all` and this one doesn't throw an error if directory exists.

**Comment by thegedge** [comment]
Yeah, I think I agree that this isn't a failure, or at least the default shouldn't be a failure. I'm also failing to see a good use case for this. Mind expanding on one?

If someone did care about it already existing, it would be better to first check if it exists. For example, in bash you could do something like this:

```bash
if [[ -e testdir ]]; then
  echo "already exists!"
  exit 1
end

mkdir testdir
```

If we had a way to fail a pipeline, it could look something like this in nu:

```
ls | where type == Dir && name == "testdir" | fail_if_no_results; mkdir testdir
```

And with aliases you would just do this:

```
alias my_mkdir [dirname] { ls | where type == Dir && name == $dirname | fail_if_no_results; mkdir $dirname }

my_mkdir testdir
```

And voila 🙂

**Comment by sandorex** [comment]
This issue is quite old so i am closing it, hell i don't even remember opening it
