### ISSUE TITLE
Updating values in a record

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#11965]
### Question

Is there a way to efficiently update values in a record?  I want to replace empty strings with nulls.  I wrote the following function:

```Nushell
def to_null [] {
	items {|key, value|
		if $value == "" or $value == "*n.a.*" {
			{$key: null}
		} else {
			{$key: $value}
		}
	}
	| reduce {|it, acc|
		$acc | merge $it
	}
}
```

Which is, while functional in both meanings of the word, is horribly slow.  Is there a better way to edit records or rows in a table?

**Comment by fdncred** [comment]
Does `update cells` help? You may also be able to do something with `reduce`.

**Comment by KAAtheWiseGit** [comment]
@fdncred the problem w/ reduce is that it creates tons of intermediate values, and thus slows the whole process down massively.

As for update, I can theoretically declare two variables:

```Nushell
let input = $in
mut output = $input

# iterate over $input and update $output
```

But this is very unergonomic and confusing to read and write, since the key/value pairs will be read from `input`, but will be written to `output`.  I'd love to have something akin to `each` for lists, where the values can simply be updated in a closure.  With `each` it's list in, list out without additional hassle.

**Comment by fdncred** [comment]
I wasn't talking about `update`, I was talking about `update cells` which is a different command. I think it's meant mostly or tables but it may work.

`each` doesn't already work on lists? Maybe you mean records? Have you looked at the `items` command?

**Comment by KAAtheWiseGit** [comment]
@fdncred I'm still on v0.90.1, so I don't have `update cells`, sorry for the confusion.

As for my `each` notes, I wonder if it's possible to emulate `each`, but for records.  For example, `$list | each {|value| $value * 2}` will maintain the list shape, while `$record | items {|key, value| {$key: $value}}` will return a table, which I can't figure out how to flatten.

The reason I'm doing all of this is because I have a big table, where some values are empty strings, and I want to convert them to null's.  But I can't find an ergonomic and efficient way to do that.

**Comment by NotTheDr01ds** [comment]
@KAAtheWiseGit `update cells` has been around for a few years.  Double-check `help update cells`.  Not sure if it's what you need here, but it should be there nonetheless ;-)

**Comment by NotTheDr01ds** [comment]
> The reason I'm doing all of this is because I have a big table, where some values are empty strings

Table? Or Record?

Can you provide a slimmed-down example for clarity?

**Comment by NotTheDr01ds** [comment]
If I understand correctly what you are looking for, try:

```Nushell
def to_null [] {
  transpose key value
  | update value {|record| 
      match $record.value {
        '' => null
        '*n.a.*' => null
        _ => $record.value
      }
    }
  | transpose -rd
}
```

```Nushell
> let rec = {
  a: foo
  b: ''
  c: '*n.a.*'
  d: bar
  e: 'Is this right?'
  f: ''
}

> $rec | to_null

╭───┬────────────────╮
│ a │ foo            │
│ b │                │
│ c │                │
│ d │ bar            │
│ e │ Is this right? │
│ f │                │
╰───┴────────────────╯

> $rec | to_null | describe

record<a: string, b: nothing, c: nothing, d: string, e: string, f: nothing>
```

**Comment by KAAtheWiseGit** [comment]
I looked into it, `update cells` is in extras, and Alpine compiles Nushell without them.

As for the transpose method, that's exactly what I've been searching for.  Thanks!

**Comment by NotTheDr01ds** [comment]
Ah, right - I tend to run with `full` from Nix, so I missed that.

And glad I could help!  (Don't forget to "Close" when you get a chance) ;-)

**Comment by KAAtheWiseGit** [comment]
Right, thanks again!

**Comment by nadapez** [comment]
I think this much simpler:
```
[ $record ] |update cells { |value| whatever  } | get 0  
```
Explanation: puting `$record` in a list creates a table. Then you can apply `update cells` subcommand  (it does not work with records).
`update cells` take a closure as an argument. The closure takes the value of the cell and ouputs the new value. Then just take the first (and only) record of the table with `get`.

**Comment by KAAtheWiseGit** [comment]
@nadapez You're right, that looks like a more concise version of two `transpose` commands.  I wonder if it'd make sense to allow `update cells` to be used on records.
