### ISSUE TITLE
panicked when selecting text in a multi line command

### ISSUE THREAD

**Issue by Jiogo18** [nushell/nushell#11973]
### Describe the bug

An error is raised when selecting text in a command with more than one line.
```
thread 'main' panicked at /usr/src/debug/rust/rustc-1.75.0-src/library/alloc/src/string.rs:1791:9:
assertion failed: self.is_char_boundary(at)
```

This error depends on the position where the selection begins.
For instance, it is possible to select everything by starting the selection from the beginning or the end of the command.

### How to reproduce

1. Write/Paste one of the following "command", i.e. `echo "tuv<Return>xyz"`
2. Place the cursor after the letter `v`
3. Try selecting `tuv` by pressing Shift+Left

## Examples

Start the selection between the first `"` and `x`:
```
echo "tuv
xyz"
```

Start the selection from the second line (the chain is `a\n\n`):
```
a


```

Start the selection before `b`:
```
a "
b
```

### Expected behavior

The text is selected, no error is raised.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.90.1                                                           |
| branch             | makepkg                                                          |
| commit_hash        | c2992d5d8b8541b64e9fc1440ed2917fc9b757f7                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (Arch Linux rust 1:1.75.0-2) |
| cargo_version      | cargo 1.75.0                                                     |
| build_time         | 2024-02-09 11:43:38 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment]
I'm pretty sure this has already been fixed on the latest main. You could try building yourself or trying a nightly to see if it's fixed.

**Comment by Jiogo18** [comment]
I just ran cargo and indeed it is fixed, that was quick :sweat_smile:
Thanks!
