### ISSUE TITLE
dfr: executable was not found

### ISSUE THREAD

**Issue by srasku** [nushell/nushell#11971]
### Describe the bug

Nushell cannot find `dfr` executable

### How to reproduce

1. `[[a b]; [1 2] [3 4]] | dfr into-df`

Result:
```
~ > [[a b];[1 2] [3 4]] | dfr into-df                     02/25/2024 09:43:26 AM
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #35:1:1]
 1 │ [[a b];[1 2] [3 4]] | dfr into-df
   ·                       ─┬─
   ·                        ╰── executable was not found
   ╰────
  help: No such file or directory (os error 2)

~ >                                                       02/25/2024 09:43:26 AM
```

### Expected behavior

Nushell should convert the table into a dataframe.  This is an example [from the manual](https://www.nushell.sh/commands/docs/dfr_into-df.html).

### Screenshots

![Nushell dfr bug](https://github.com/nushell/nushell/assets/2049005/6eab3e3c-4e3b-4446-a0b7-fa3426d321a0)

### Configuration

~ > version | transpose key value | to md --pretty        02/25/2024 09:47:31 AM
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.90.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball) |
| cargo_version      | cargo 1.75.0                                                      |
| build_time         | 2024-02-07 07:02:04 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, extra, sqlite, trash, which, zip                         |
| installed_plugins  |

### Additional context

Installed NuShell just before using MacPorts.

**Comment by devyn** [comment]
You need to compile Nushell with dataframe support, which is not enabled by default. Rather than using MacPorts, you can get a version of Nushell that has everything enabled from the [releases](https://github.com/nushell/nushell/releases/tag/0.90.1) page - look for the `-darwin-full` package for your architecture.

**Comment by srasku** [comment]
Yeah, that fixes it.  Thanks.
