### ISSUE TITLE
Is there a way to replace current command line buffer

### ISSUE THREAD

**Issue by sigoden** [nushell/nushell#11981]
### Question

![aichat-integration](https://github.com/sigoden/aichat/assets/4012553/873ebf23-226c-412e-a34f-c5aaa7017524)

When `ALT+E` is pressed, pass the current command line buffer to `aichat` and replace the command line buffer with the new command generated by `aichat`.

The feature have been successfully implemented on bash/zsh/fish/powershell. Can it be implemented on nushell?

### Additional context and details

refs:
- doc: https://github.com/sigoden/aichat?tab=readme-ov-file#shell-integration
- integration.bash: https://github.com/sigoden/aichat/blob/main/scripts/integration.bash

**Comment by NotTheDr01ds** [comment]
I think you are looking for [`commandline`](https://www.nushell.sh/commands/docs/commandline.html) inside a [keybinding](https://www.nushell.sh/book/line_editor.html#keybindings).

**Comment by sigoden** [comment]
I tried the following configuration, but the results were not ideal.

```
    keybindings: [
        {
            name: aichat_integration
            modifier: alt
            keycode: char_e
            mode: [emacs, vi_insert]
            event:[
                {
                    send: executehostcommand,
                    cmd: "_aichat_nushell"
                }
            ]
        }
    ]
```
```
def _aichat_nushell [] {
    let _prev = (commandline)
    if ($_prev != "") {
        commandline -r (aichat -e $_prev)
    }
}
```

![aichat-shell-integration](https://github.com/nushell/nushell/assets/4012553/9b761099-dae8-47cc-8787-a1020b29e652)

It start a newline instead of replacing the original command line.

**Comment by fdncred** [comment]
I wonder if this is a bug in command line or if there's just a newline being added somewhere. maybe executehostcommand adds a newline? you might try doing some `str trim`s in a variety of places to see if it makes any difference. but it seems like a bug to me.

**Comment by fdncred** [comment]
This PR _might_ fix this issue? https://github.com/nushell/reedline/pull/758

**Comment by sigoden** [comment]
I have tried the PR, it works.

The `_aichat_nushell ` need to modify.
```
def _aichat_nushell [] {
    let _prev = (commandline)
    if ($_prev != "") {
        commandline edit -r (aichat -e $_prev)
    }
}
```

![aichat-shell-integration](https://github.com/nushell/nushell/assets/4012553/3781a924-786b-474c-be72-38ede9c6ffe4)

**Comment by sigoden** [comment]
I would like to append a ⌛ symbol to the current command line buffer while `aichat` is fetching an answer.
Is there any way to trigger a repaint event (e.g. `commandline repaint`) in the host function? 

```
def _aichat_nushell [] {
    let _prev = (commandline)
    if ($_prev != "") {
        commandline edit -a "⌛"
        commandline repaint                                       # <- how to ?
        commandline edit -r (aichat -e $_prev)
    }
}
```

**Comment by fdncred** [comment]
There is a `repaint` event that you might could try. See all of this with `keybindings list`

**Comment by sigoden** [comment]
The `repaint` is off-topic. The PR does solve the problem. Thanks.
