### ISSUE TITLE
Incomplete parser of boolean expressions ending with bracket

### ISSUE THREAD

**Issue by DoumanAsh** [nushell/nushell#11982]
### Describe the bug

Following expression will evaluate incorrectly, without syntax error, even though syntax wise you have superfluous bracket at the end
```
if ((sys | get host | get name) == Windows)) { echo "WINDOWS" } else { echo "NOT WINDOWS" }
```

I did few experiments, and it seems parser just ignores trailing brackets, even if you put tons of them

Interestingly enough, extra bracket will reverse result of expression inside.
I.e. my example above will be `NOT WINDOWS` even on windows system

From my observation parser seems to mind brackets, but it seems to be pretty lax about its number, resulting in expression to become incorrect or outright not making any sense

### How to reproduce

Use above example in console

### Expected behavior

Indicate error in case of invalid number of brackets at the end

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.90.1                                               |
| branch             |                                                      |
| commit_hash        | c2992d5d8b8541b64e9fc1440ed2917fc9b757f7             |
| build_os           | windows-x86_64                                       |
| build_target       | x86_64-pc-windows-msvc                               |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                  |
| rust_channel       | 1.73.0-x86_64-pc-windows-msvc                        |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                  |
| build_time         | 2024-02-07 02:25:54 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by fdncred** [comment]
I agree that this should produce a parse error. However, it was confusing to figure out because there are no brackets in your example. There are parentheses `()` and braces `{}` but no brackets `[]`.

This has one extra closing parenthesis and it seems like it should produce an error, but does not.
```nushell
if ((sys | get host | get name) == Windows)) { echo "WINDOWS" } else { echo "NOT WINDOWS" }
                                          ^
                                          |
                                          -- should be removed and our parser should say that
```

**Comment by DoumanAsh** [comment]
Ah, sorry, yeah, I'm calling everything brackets, but it is indeed parentheses
On side note I didn't notice issues with `{}`

But expression like: `[1, 2]]` produces:
```
╭───┬────╮
│ 0 │  1 │
│ 1 │ 2] │
╰───┴────╯
```

This would produce `list<any>` due to nu interpreting `2]` as string
I'm not sure if it is intended behavior

**Comment by fdncred** [comment]
I think `[1, 2]]` is probably working as intended because `2]` is a bareword string in this instance.

**Comment by DoumanAsh** [comment]
Oh yeah, sorry I dont follow issues that I created, but there is commit refrencing this ticket with fix so it should be closed
