### ISSUE TITLE
Support "--" in argument parsing to consume the rest of arguments into ...args (or similar) without trying to handle arguments as flags

### ISSUE THREAD

**Issue by ddanier** [nushell/nushell#11980]
### Related problem

When defining custom commands you can use something like `...args` to consume any arguments. Sadly this currently only allows for arguments not starting with a `-` as then nu will try to handle those as arguments.

See the following shell session:

```
❯ def test [...args] { print $args }
❯ test foo bar bla
╭───┬─────╮
│ 0 │ foo │
│ 1 │ bar │
│ 2 │ bla │
╰───┴─────╯

❯ test foo bar -x bla
Error: nu::parser::unknown_flag

  × The `test` command doesn't have flag `-x`.
   ╭─[entry #69:1:1]
 1 │ test foo bar -x bla
   ·               ┬
   ·               ╰── unknown flag
   ╰────
  help: Available flags: --help(-h). Use `--help` for more information.
```

### Describe the solution you'd like

I would suggest that nu handles `--` like other shell commands would do.

Meaning the following command should then work like this:
```
❯ test foo bar -- -x bla
╭───┬─────╮
│ 0 │ foo │
│ 1 │ bar │
│ 2 │ -x  │
│ 3 │ bla │
╰───┴─────╯
```
(Note: `--` is not in the resulting list)

Currently it also produces this error:
```
❯ test foo bar -- -x bla
Error: nu::parser::unknown_flag

  × The `test` command doesn't have flag ``.
   ╭─[entry #70:1:1]
 1 │ test foo bar -- -x bla
   ·              ─┬
   ·               ╰── unknown flag
   ╰────
  help: Available flags: --help(-h). Use `--help` for more information.
```

### Describe alternatives you've considered

Actually I did not come up with any alternatives.

You might define all the arguments in your custom command - but then this might not be as generic as it could be.

Note that I know you can use quotes to mark the argument as a string, see the following:
```
❯ test foo bar "-x" bla
╭───┬─────╮
│ 0 │ foo │
│ 1 │ bar │
│ 2 │ -x  │
│ 3 │ bla │
╰───┴─────╯
```

BUT: This will not work for nu scripts you start using `nu some-script.nu args follow here`. When coming from another shell the quotes will not be passed to `nu` and thus nu can never  handle this as a string. I think using `--` would be nice addition to allow just for this to work.

### Additional context and details

This may allow for easier passing arbitrary arguments to other commands and allow for easier handling of string values beginning with `-`.

**Comment by NotTheDr01ds** [comment]
Looks like this may be a duplicate of #8323 and/or #10939?  If so, there's a [draft PR](https://github.com/nushell/nushell/pull/11435) that hasn't been able to land just yet.

**Comment by fdncred** [comment]
Agreed. It's a dupe.

If you want to pass parameters through, you can do this.
```nushell
❯ def --wrapped test [...args] { print $args }                                                                    0823  06:57:47 AM
❯ test foo bar bla                                                                                                   1  06:57:56 AM
╭───┬─────╮
│ 0 │ foo │
│ 1 │ bar │
│ 2 │ bla │
╰───┴─────╯

❯ test foo bar -x bla                                                                                                7  06:58:05 AM
╭───┬─────╮
│ 0 │ foo │
│ 1 │ bar │
│ 2 │ -x  │
│ 3 │ bla │
╰───┴─────╯
```

**Comment by ddanier** [comment]
Thanks for the replies. Somehow the search did not find those....
