### ISSUE TITLE
Add ability to access record via variable

### ISSUE THREAD

**Issue by DoumanAsh** [nushell/nushell#11989]
### Related problem

Given problem of accessing `PATH` in a cross platform way.
One would attempt to do something like:
```
let PATH = (
    if ($env._OS == "Windows") {
        "Path"
     } else {
        "PATH"
    }
)

$env.$PATH
```

But this doesn't work because bare `$PATH` when used in context of record access results in lookup as `$PATH`

Another potential way would be:
```
$env.$"($PATH)"`
```

But this doesn't work because `$"($PATH)"`` is not treated as string:

```
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[entry #9:1:1]
 1 │ $env.$"($PATH)"
   ·      ─────┬────
   ·           ╰── expected string
   ╰────

```

### Describe the solution you'd like

Any other way to get/set record way via variable as key would be useful as well

The only way I see right now would be to guard every `$env.PATH` access with `if else` which is not very nice for cross platform shell

**Comment by fdncred** [comment]
You can do something like this.
```nushell
let pathvar = if "PATH" in $env { "PATH" } else { "Path" }
load-env {
  $pathvar: (
    $env | get $pathvar |
    split row (char esep) |
    prepend 'some/path' |
    prepend 'c:\some\other\path' 
  )
}
```

**Comment by DoumanAsh** [comment]
Thanks, this is nice work-around, but it is not pretty that you cannot pass formatted string as key to record
But if it is not needed feature, then I can live with work around

**Comment by fdncred** [comment]
This is passing a formatted string as a key to the record. The format in the example is `PATH` or `Path`
