### ISSUE TITLE
entering a .csv file creates a shell for each line of the .csv

### ISSUE THREAD

**Issue by Amanita-muscaria** [nushell/nushell#1199]
**Describe the bug**
I created a csv file using the output from `ls` and then entered the csv. Instead of creating a single new shell from the csv, it seems to open a new shell for each line in the csv.

**To Reproduce**
1.  `ls | pick name type | save test.csv`
2. `enter test.csv`

**Expected behavior**
A single shell is created using the data from the .csv file

**Screenshots**
![setup](https://user-images.githubusercontent.com/4589044/72221850-05c34700-3524-11ea-98ee-5ee4ed9d4b7e.png)
![output](https://user-images.githubusercontent.com/4589044/72221853-0825a100-3524-11ea-9175-3ea6a25fec9f.png)

**Configuration (please complete the following information):**
 - OS: Arch 5.4.8-arch1-1
 - Version: 0.8.0
 - Optional features (if any): Starship

The output from `cat test.csv` (I made it from the root of the nushell repo)
```
name,type
rustfmt.toml,File
docs,Directory
features.toml,File
.git,Directory
crates,Directory
Cargo.toml,File
.vscode,Directory
assets,Directory
debian,Directory
.github,Directory
docker,Directory
src,Directory
.circleci,Directory
README.md,File
CODE_OF_CONDUCT.md,File
TODO.md,File
.azure,Directory
.gitpod.Dockerfile,File
target,Directory
.gitignore,File
.gitpod.yml,File
.editorconfig,File
test.csv,File
.idea,Directory
.cargo,Directory
tests,Directory
Makefile.toml,File
images,Directory
LICENSE,File
build.rs,File
Cargo.lock,File
```

**Comment by arnau** [comment]
Same behaviour with:

* OS: MacOS 10.15.7
* Version: 0.21.0
*  Features: default, clipboard, trash

**Comment by jeanga** [comment]
Surprised to see this issue labeled "enhancement" when it really looks like a bug... 
Am I missing something? 
Also, I am pretty sure this is a regression from previous versions.

**Comment by jeanga** [comment]
This issue is still very real and should really be treated as a bug and not an enhancement (IMHO)
Thanks!

**Comment by jonathandturner** [comment]
@jeanga - thanks! sorry for the news as the bot catches up :sweat_smile:
