### ISSUE TITLE
timeit captures stdout but not stderr

### ISSUE THREAD

**Issue by mattbettcher** [nushell/nushell#11996]
### Question

I'm trying to time an external command with 
`let time_taken = timeit ^command`
and then print out the time taken after a few other operations. I still want my command to output to stdout. It does output to stderr.
If this is expected behavior please let me know, I can't find any specific info on it. It seems very inconsistent to capture stdout but not stderr. I'm very new to Nushell and I'm certain I'm just doing something wrong.

**Comment by fdncred** [comment]
I'm guessing this could be changed pretty easily. No one has ever asked for this before though.

https://github.com/nushell/nushell/blob/ecaed7f0ae5f496a6dcaf3ec979e9bd8d78aa160/crates/nu-command/src/debug/timeit.rs#L61-L62

**Comment by mattbettcher** [comment]
I see it claims to capture both stdout and stderr? But I still get stderr output? 
So should I attempt a pull request to add a flag for no capture? I did a little searching and can't find any similar flags, I'm thinking --nocapture would be fine. If you know of any flags for other commands please let me know so this one can be consistent.

**Comment by fdncred** [comment]
> I see it claims to capture both stdout and stderr?

I don't think that's the case. It just takes the defaults which I think is true for stdout and false for stderr.

we have `--stderr` flags on a few commands and `--stdout` on one command
