### ISSUE TITLE
`to md` ignores columns with empty header

### ISSUE THREAD

**Issue by vwkd** [nushell/nushell#12006]
### Describe the bug

The command `to md` ignores columns with an empty column header, which results in silently losing columns. This doesn't match `to json` which doesn't lose columns. I haven't tested other `to` subcommands.

A temporary workaround is to set a column header, for example with `rename`.

### How to reproduce

1. Run

```sh
[["", "foo"]; [1, 2], [3, 4]] | to md
```

### Expected behavior

```md
||foo|
|-|-|
|1|2|
|3|4|
```

### Actual behavior

```md
|foo|
|-|
|2|
|4|
```

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.90.1                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | macos-aarch64                                        |
| build_target       | aarch64-apple-darwin                                 |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (Homebrew)       |
| cargo_version      | cargo 1.75.0                                         |
| build_time         | 2024-02-06 22:28:49 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by PanGan21** [comment]
Hey guys! I did some first fix implementation for this case in #12012
