### ISSUE TITLE
How to get the process ID occupying a certain network port ?

### ISSUE THREAD

**Issue by Jordan-Haidee** [nushell/nushell#12023]
### Question

Is there a command in Nushell works like: 
- netstat
- lsof -i
which get the process ID occupying a certain network port ?
I have checked docs but found nothing related to this issue. ❤️

**Comment by fdncred** [comment]
There's this plugin https://github.com/FMotalleb/nu_plugin_port_list

**Comment by devyn** [comment]
If you don't need it to be portable, you could also consider just using `lsof` with [`jc`](https://github.com/kellyjonbrazil/jc) which implements parsers to JSON for many common Unix tools

**Comment by Jordan-Haidee** [comment]
@fdncred Thank! It works well. 😊

**Comment by WindSoilder** [comment]
I think it's resolved :)
