### ISSUE TITLE
Starship(?) prompt shows a directory that isn't correct

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1202]
**Describe the bug**
In Windows, we show a path that you can't actually use (screenshot below)

**To Reproduce**
1. Just start Nu in Windows

**Expected behavior**
We should only show valid paths that the user can work with

**Screenshots**
![image](https://user-images.githubusercontent.com/547158/72222591-6063ae00-35cb-11ea-87ce-d5857f3045b2.png)

**Configuration (please complete the following information):**
 - OS: Windows
 - Version: 0.8.1
 - Optional features: stable

**Comment by yoshuawuyts** [comment]
I'm not able to reproduce, because instead my Windows installation doesn't show the starship prompt at all? On nu 0.8.0:

![Screenshot 2020-01-14 01 50 14](https://user-images.githubusercontent.com/2467194/72304232-3c0ddd00-3670-11ea-9255-2a769bba8685.png)

**Comment by jonathandturner** [comment]
@yoshuawuyts - starship is still off by default, so you'll need to install/build with the `--features=stable` flag to get it turned on (you can also turn on specifically the starship feature, but I generally just use stable)

**Comment by thegedge** [comment]
@jonathandturner is this just the way that starship displays the path, when it should perhaps show `C:\WINDOWS\system32` instead?

**Comment by jonathandturner** [comment]
@thegedge I suspect so. We should file an upstream issue to see if the can fix it on their end

**Comment by thegedge** [comment]
No need: https://github.com/starship/starship/issues/1106 😄

**Comment by nlbrown2** [comment]
I'm experiencing this on Linux. I think it has to do with nu's cd not updating the $PWD env variable. 
![nu_pwd](https://user-images.githubusercontent.com/28675731/82134960-301f5c80-97c3-11ea-8ed2-86686729fc4b.png)

**Comment by nlbrown2** [comment]
I was able to create a test that fails on [my fork](https://github.com/nlbrown2/nushell). I wasn't sure where to put the test, but hopefully that doesn't matter.
