### ISSUE TITLE
Win server 2012 graphics data cannot be seen

### ISSUE THREAD

**Issue by 107295472** [nushell/nushell#12034]
### Question

![image](https://github.com/nushell/nushell/assets/6436116/c89288e8-42bf-4ded-82ca-5d0df0163904)

**Comment by 107295472** [comment]
Execute the ls command, and the data will disappear after a flash.

**Comment by fdncred** [comment]
Does windows server 2012 cmd.exe support ansi escape sequences?

You may have to set ENABLE_VIRTUAL_TERMINAL_PROCESSING
https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling

**Comment by 107295472** [comment]
Thanks
