### ISSUE TITLE
Multiple executehostcommand events but only first one is executed

### ISSUE THREAD

**Issue by sigoden** [nushell/nushell#12045]
### Describe the bug

If there are multiple executehostcommand events for a keybinding, when triggered, only the first one is executed.

### How to reproduce

1. add keybinding `alt+e`
```
$env.config.keybindings = ($env.config.keybindings | append {
        name: aichat_integration
        modifier: alt
        keycode: char_e
        mode: [emacs, vi_insert]
        event:[
            {
                send: executehostcommand,
                cmd: "echo a"
            }
            {
                send: executehostcommand,
                cmd: "echo b"
            }
        ]
    }
)
```

2. trigger `alt+e`, only print `a`, not `ab`

### Expected behavior

All executehostcommand events should be executed.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.90.2                                   |
| branch             | main                                     |
| commit_hash        | 98525043edd20abb62da09726d75816d09d68f1e |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.74.1 (a28077b28 2023-12-04)      |
| rust_channel       | 1.74.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.74.1 (ecb9851af 2023-10-18)      |
| build_time         | 2024-03-02 03:42:03 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

### Additional context

Why multiple executehostcommand events are needed. Because I need to trigger repaint in the middle.

I hope to achieve the following keybinding:

![aichat-integration](https://github.com/sigoden/aichat/assets/4012553/873ebf23-226c-412e-a34f-c5aaa7017524)

```
        event:[
            {
                send: executehostcommand,
                cmd: "commandline edit --append '⌛'"
            }
            {
                send: repaint
            }
            {
                send: executehostcommand,
                cmd: "commandline edit -r (aichat -e (commandline))"
            }
        ]
```

**Comment by sholderbach** [comment]
Context: 

currently reedline will see the first `ReedlineEvent::ExecuteHostCommand` and return to nushells outer loop with the status as if the user had entered that text. The remaining events are not preserved. Only the manually entered text and other state on `reedline::Reedline` remains.

**Comment by kit494way** [comment]
How about using `print` instead of `commandline edit --append`?

```
event: [
    {
        send: executehostcommand
        cmd: "_aichat"
    }
]
```

```nu
def _aichat [] {
    print '⌛'
    commandline edit -r (aichat -e (commandline))
}
```

**Comment by sigoden** [comment]
@kit494way thanks, the problem solved.
