### ISSUE TITLE
crash on highlighting with shift-arrow

### ISSUE THREAD

**Issue by Zoybean** [nushell/nushell#12041]
### Describe the bug

Highlighting (using shift + arrow keys) from within a word crashes nu

```
thread 'main' panicked at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\alloc\src\string.rs:1641:9:
assertion failed: self.is_char_boundary(at)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

[process exited with code 101 (0x00000065)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

### How to reproduce

1. type `ls ~/.`
2. press the left arrow-key once
3. hold shift, and press the left arrow-key again

### Expected behavior

I expected it to highlight characters within the word. Instead it crashed the shell

### Screenshots

![image](https://github.com/nushell/nushell/assets/24929040/563fec4d-0d43-4769-a7ef-2a76eef301a9)

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.90.2                                    |
| branch             | main                                      |
| commit_hash        | 5042f19d1b4035b67b0fb58a95dd1784caeaf9ce  |
| build_os           | windows-x86_64                            |
| build_target       | x86_64-pc-windows-msvc                    |
| rust_version       | rustc 1.74.1 (a28077b28 2023-12-04)       |
| rust_channel       | 1.74.1-x86_64-pc-windows-msvc             |
| cargo_version      | cargo 1.74.1 (ecb9851af 2023-10-18)       |
| build_time         | 2024-02-10 10:54:23 +08:00                |
| build_rust_channel | release                                   |
| allocator          | mimalloc                                  |
| features           | default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                           |

**Comment by Zoybean** [comment]
I've also found a few 'rules' that seem to govern when the crash occurs.
- Selecting in the first word of the command pipeline doesn't cause a crash
- Selecting from or to a word-boundary or whitespace doesn't cause a crash 
- In a word like `1day` or `10wk`, when it is parsed as a duration (i.e. highlighted in 2 parts), selecting from the point between the quantity and the unit, doesn't cause a crash

Maybe it is something to do with syntax highlighting?

**Comment by fdncred** [comment]
I believe that bug is fixed. Can you test on the latest main?

**Comment by Zoybean** [comment]
Yep, that's on me, I got carried away investigating the symptoms and never searched for similar issues.
