### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#12058]
### Describe the bug

Crash

### How to reproduce

1. Write prompt `~> fs delete "Image (28).jpg" "Image (29).jpg"`
2. Put the cursor at the char `2` of `28`.
3. Shift+left arrow.

### Expected behavior

Not crash

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.90.1                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (Alpine Linux 1.76.0-r0) |
| cargo_version      | cargo 1.76.0                                                 |
| build_time         | 2024-02-14 02:25:04 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

### Additional context

Will add stacktraces and more context tomorrow.

**Comment by fdncred** [comment]
I believe this has already been fixed. Please try latest main.

**Comment by KAAtheWiseGit** [comment]
Yes, it's fixed on `main` 27793e745.
