### ISSUE TITLE
ls "" acts like ls / since nushell 0.90.1

### ISSUE THREAD

**Issue by Schweber** [nushell/nushell#12054]
### Describe the bug

Running `ls ""` acts like `ls /` in nushell 0.90.1.

In nushell 0.89.0 it acted like the "" was not present and thus acted on the present working directory.

### How to reproduce

1. Run `ls ""`
2. Output will be the same as `ls /`

### Expected behavior

`ls ""` acts on the present working directory, not on /.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.90.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball) |
| cargo_version      | cargo 1.75.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
Thanks @Schweber. Agree, this is a bug.

@WindSoilder I'm guessing this has something to do with globbing. What do you think?

**Comment by rgwood** [comment]
> ### Expected behavior
> 
> `ls ""` acts on the present working directory, not on /.

Is this expected? I would expect `ls ""` to fail because there is no directory named the empty string. Looks like that's what `zsh` does:

```
❯ ls ""
ls: cannot access '': No such file or directory
```

**Comment by WindSoilder** [comment]
What a good catch @rgwood !  So I think it should raise error rather than acting like `ls /`

**Comment by fdncred** [comment]
I agree that "" should report a `"" file not found` type of error.
