### ISSUE TITLE
Panick when a call to a custom command with many arguments is typed in interactively

### ISSUE THREAD

**Issue by robaca** [nushell/nushell#12069]
### Describe the bug

When trying to call amcustom command with many arguments via the command line, Nushell is panicking.

### How to reproduce

```
# Start a nested shell
nu 

# Then register a custom command with many args
def "a" [ b: string, c: string, d: string, e: string, f: string, g: string ] {}

# Then type in the following:
a b c d e
```

When pressing the 'e', you will get a panick error and the subshell is exiting:

```
thread 'main' panicked at crates/nu-parser/src/parser.rs:777:28:
index out of bounds: the len is 2 but the index is 3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected behavior

don't panick ;-)

### Screenshots

<img width="1333" alt="image" src="https://github.com/nushell/nushell/assets/580474/ae06a870-3967-4656-ad84-61472cdcc2ac">

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.90.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball) |
| cargo_version      | cargo 1.75.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by robaca** [comment]
Rust backtrace:
```
stack backtrace:
   0:        0x10350d320 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5172d33994dba7b3
   1:        0x102a495e4 - core::fmt::write::h7d3de5cea125083e
   2:        0x103522a60 - std::io::Write::write_fmt::h917406fdfae8a672
   3:        0x10350d180 - std::sys_common::backtrace::print::h69b1086853a48f9a
   4:        0x1035282d0 - std::panicking::default_hook::{{closure}}::h4e70f330f69a17a7
   5:        0x103527fc0 - std::panicking::default_hook::h2bfeb541bcbf5546
   6:        0x103528894 - std::panicking::rust_panic_with_hook::h9f5f598fe1ac063a
   7:        0x10350d9d0 - std::panicking::begin_panic_handler::{{closure}}::he73f9a7f640f3ffc
   8:        0x10350d52c - std::sys_common::backtrace::__rust_end_short_backtrace::h98898c1d66fb3a04
   9:        0x103528414 - _rust_begin_unwind
  10:        0x1036f10d0 - core::panicking::panic_fmt::h36a7abbdf3b00cb1
  11:        0x1036f125c - core::panicking::panic_bounds_check::h1b3df01aab58f0d9
  12:        0x10301a548 - nu_parser::parser::parse_multispan_value::h8eb7e2cec2b4f0df
  13:        0x10301ba70 - nu_parser::parser::parse_internal_call::h5244ae6ede653b16
  14:        0x10301d88c - nu_parser::parser::parse_call::hda6685d083ef9bfd
  15:        0x1030302dc - nu_parser::parser::parse_expression::h4e9e844ebc10939b
  16:        0x103031530 - nu_parser::parser::parse_builtin_commands::hab33326d46f9cbec
  17:        0x1030327fc - nu_parser::parser::parse_block::hd54a4470c332cfa6
  18:        0x1030354d4 - nu_parser::parser::parse::h7b2dc89cb3758695
  19:        0x102b8b728 - <nu_cli::syntax_highlight::NuHighlighter as reedline::highlighter::Highlighter>::highlight::h8390c77d0afe8a4e
  20:        0x10341bdfc - reedline::engine::Reedline::repaint::h3c56400a9e187fa0
  21:        0x103419480 - reedline::engine::Reedline::read_line::h0a93725d5c828ccf
  22:        0x102b37838 - nu_cli::repl::evaluate_repl::hed99a952807e16a2
  23:        0x102b26ef0 - nu::run::run_repl::h6d82ee6c4a95e5a9
  24:        0x102b155f0 - nu::main::ha3a4ab0808cec914
  25:        0x102b1c10c - std::sys_common::backtrace::__rust_begin_short_backtrace::hc9b38dbf0ee88291
  26:        0x102b245f0 - std::rt::lang_start::{{closure}}::ha70a43073d29d87b
  27:        0x103528310 - std::panicking::try::h8408a6df79f92b61
  28:        0x103520e1c - std::rt::lang_start_internal::ha925d3c7d3436bff
  29:        0x102b245d4 - std::rt::lang_start::hec3f33adab1f6183
  30:        0x102b16240 - _main

```

**Comment by sholderbach** [comment]
Also reported as:

- #13930 
- #8385
