### ISSUE TITLE
Parameters with @ cause a lot of issues

### ISSUE THREAD

**Issue by kvrhdn** [nushell/nushell#1206]
**Describe the bug**
Parameters with `@` cause parsing issues, requiring quotes.
Autocompletion on files seems to add a backslash as escape character, but this doesn't work.

**To Reproduce**
Example of a parameter with `@`:

```
❯ git clone git@github.com:nushell/nushell.git
error: Parse Error
- shell:1:44
1 | git clone git@github.com:nushell/nushell.git
  |                     ^^^^^^^^^^^^^^^^^^^^^^^^

❯ git clone 'git@github.com:nushell/nushell.git'
Cloning into 'nushell'...
...
```

Issues with filenames:

```
❯ touch file@.txt
error: Parse Error
- shell:1:15
1 | touch file@.txt
  |            ^^^^
```
I can escape the `@` with `\`, but this creates a file with `\@`...
```
❯ touch file\@.txt

❯ ls
━━━━━━━━━━━━┯━━━━━━┯━━━━━━┯━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━
 name       │ type │ size │ created        │ accessed       │ modified 
────────────┼──────┼──────┼────────────────┼────────────────┼────────────────
 file\@.txt │ File │  —   │ 33 seconds ago │ 33 seconds ago │ 33 seconds ago 
━━━━━━━━━━━━┷━━━━━━┷━━━━━━┷━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━━━
```
This gets even weirder when I try to move an existing file `file@.txt`:
```
❯ ls
━━━━━━━━━━━┯━━━━━━┯━━━━━━┯━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━
 name      │ type │ size │ created      │ accessed     │ modified 
───────────┼──────┼──────┼──────────────┼──────────────┼──────────────
 file@.txt │ File │  —   │ a minute ago │ a minute ago │ a minute ago 
━━━━━━━━━━━┷━━━━━━┷━━━━━━┷━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━

❯ mv file\@.txt test.txt
error: Rename aborted. (Does "test.txt" exist?)
- shell:1:22
1 | mv file\@.txt test.txt
  |               ^^^^^^^^ Rename aborted. (Does "test.txt" exist?)
```
This error is misleading.

Most of these issues can be avoided using quotes (i.e. `'file@.txt'`), but this not very obvious since auto-completion writes `file\@.txt`.

**Expected behavior**
I would expect nu to ignore the `@` (similar to bash).
I would expect autocompletion to put quotes around filenames, instead of adding backslashes (which don't work).

**Screenshots**
N/A

**Configuration (please complete the following information):**
- macOS Catalina (10.15.2)
- nu 0.8.0, installed using homebrew

**Comment by koenaad** [comment]
This seems to be related to #1140.

**Comment by andrasio** [comment]
You could try for now formatting it first.

`ls | format "some_string @ {name}" | echo $it`

Thanks! /cc @wycats

**Comment by jonathandturner** [comment]
This should be fixed in the latest master

**Comment by kvrhdn** [comment]
Can confirm I don't have any issues git cloning anymore :+1: I forgot I had a ticket open for this, love how nu keeps improving!
