### ISSUE TITLE
--table-name flag for into sqlite is broken

### ISSUE THREAD

**Issue by Kinchkun** [nushell/nushell#12067]
### Describe the bug

Cheers,

the flag `--table-name` for `into sqlite` doesn't have an effect. The bug is rather trivial but I am not sure about the proper solution.

[This commit](https://github.com/nushell/nushell/blame/71aacf50321cb1c5af5fa402e472762f21211c21/crates/nu-command/src/database/commands/into_sqlite.rs#L38) changed the flag name in the signature from `table_name` to `table-name`. But the [usage](https://github.com/nushell/nushell/blame/71aacf50321cb1c5af5fa402e472762f21211c21/crates/nu-command/src/database/commands/into_sqlite.rs#L165) wasn't updated:

```
let table_name: Option<Spanned<String>> = call.get_flag(engine_state, stack, "table_name")?;
```

However, the renaming of flag is a breaking change and I didn't find this in the list of breaking changes for 0.90.1. So maybe the renaming was a mistake? Should the renaming be reverted? I do think the kebab-case is more consistent though. 

### How to reproduce

```rust
{x: 1} | into sqlite --table-name "foo" test.db
open test.db
╭──────┬───────────╮
│      │ ╭───┬───╮ │
│ main │ │ # │ x │ │
│      │ ├───┼───┤ │
│      │ │ 0 │ 1 │ │
│      │ ╰───┴───╯ │
╰──────┴───────────╯
```

### Expected behavior

The table name in the example should be `foo` not `main`

### Configuration

| key                | value                                         |
| ------------------ | --------------------------------------------- |
| version            | 0.90.1                                        |
| branch             |                                               |
| commit_hash        |                                               |
| build_os           | macos-aarch64                                 |
| build_target       | aarch64-apple-darwin                          |
| rust_version       | rustc 1.74.0 (79e9716c9 2023-11-13)           |
| rust_channel       | stable-aarch64-apple-darwin                   |
| cargo_version      | cargo 1.74.0 (ecb9851af 2023-10-18)           |
| build_time         | 2024-03-04 09:05:53 +01:00                    |
| build_rust_channel | release                                       |
| allocator          | mimalloc                                      |
| features           | dataframe, default, sqlite, trash, which, zip |
| installed_plugins  |                                               |

**Comment by fdncred** [comment]
Thanks for finding this. I created https://github.com/nushell/nushell/pull/12068 for it.
