### ISSUE TITLE
which does not work on external command that are not in /usr/local/bin

### ISSUE THREAD

**Issue by koenaad** [nushell/nushell#1207]
**Describe the bug**
`which` does not work on external command that are not located in `/usr/local/bin`.

**To Reproduce**
I can successfully run `which` on external commands stored in `/usr/local/bin`:
```
❯ which brew
━━━━━━┯━━━━━━━━━━━━━━━━━━━━━┯━━━━━━━━━
 arg  │ path                │ builtin 
──────┼─────────────────────┼─────────
 brew │ /usr/local/bin/brew │ No 
━━━━━━┷━━━━━━━━━━━━━━━━━━━━━┷━━━━━━━━━
```

But `which` fails with commands (that are on my path), but in a non-default directory. `^which` works fine:
```
❯ which cargo
error: Binary not found for argument, and argument is not a builtin
- shell:1:11
1 | which cargo
  |       ^^^^^ not found

~/Desktop/test on ☁️  eu-west-1 
❯ ^which cargo
/Users/koenraad/.cargo/bin/cargo
```

**Expected behavior**
`which` should show the location of all commands, or maybe fallback to the external `which`.

**Screenshots**
N/A

**Configuration**
- macOS Catalina (10.15.2)
- nu 0.8.0, installed using homebrew

**Comment by coolshaurya** [comment]
It works on my manjaro linux machine. I guess its a mac-only issue. 

![image](https://user-images.githubusercontent.com/32027323/73155186-f20d0880-40ff-11ea-8a2f-07ac6e8216c7.png)

**Comment by jonathandturner** [comment]
@koenaad - I'm not able to reproduce this in macOS.

Did you change the path that Nu uses via the `config` command, by chance?  That might affect what `which` can find.

**Comment by koenaad** [comment]
I'm not sure...

My `env` looks normal and the config file is an empty file.

```
~ 
❯ env
─────────────────┬─────────────────┬─────────────────────────────────────┬─────────────────────────────────────┬─────────────────────────────────────┬──────────────────────────────────
 cwd             │ home            │ config                              │ history                             │ temp                                │ vars 
─────────────────┼─────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼──────────────────────────────────
 /Users/koenraad │ /Users/koenraad │ /Users/koenraad/Library/Application │ /Users/koenraad/Library/Application │ /var/folders/yp/zl94c3_12nz1q27ljx4 │ [row HOME LC_CTYPE LESS LOGNAME 
                 │                 │ Support/nu/config.toml              │ Support/nu/history.txt              │ snd9m0000gn/T/                      │ LSCOLORS OLDPWD PAGER PATH PWD 
                 │                 │                                     │                                     │                                     │ SHELL SHLVL SSH_AUTH_SOCK 
                 │                 │                                     │                                     │                                     │ STARSHIP_SHELL TERM TERM_PROGRAM 
                 │                 │                                     │                                     │                                     │ TERM_PROGRAM_VERSION 
                 │                 │                                     │                                     │                                     │ TERM_SESSION_ID TMPDIR USER 
                 │                 │                                     │                                     │                                     │ WASMTIME_HOME XPC_FLAGS 
                 │                 │                                     │                                     │                                     │ XPC_SERVICE_NAME ZSH _ 
                 │                 │                                     │                                     │                                     │ __CF_USER_TEXT_ENCODING] 
─────────────────┴─────────────────┴─────────────────────────────────────┴─────────────────────────────────────┴─────────────────────────────────────┴──────────────────────────────────

~ 
❯ config
─────────
 <value> 
─────────
  
─────────

```

My path seems normal:
```
~ 
❯ echo $nu.path
───┬────────────────────────────────────────────
 # │ <value> 
───┼────────────────────────────────────────────
 0 │ /Users/koenraad/.wasmtime/bin 
 1 │ /usr/local/bin 
 2 │ /usr/bin 
 3 │ /bin 
 4 │ /usr/sbin 
 5 │ /sbin 
 6 │ /usr/local/MacGPG2/bin 
 7 │ /Applications/Wireshark.app/Contents/MacOS 
 8 │ /Users/koenraad/.cargo/bin 
───┴────────────────────────────────────────────

```

But `which cargo` fails while I can still run `cargo` 😕 

```
~ 
❯ which cargo
error: Error trying to find binary for argument
- shell:1:11
1 | which cargo
  |       ^^^^^ error

~ 
❯ cargo --version
cargo 1.40.0 (bc8e4c8be 2019-11-22)

```

**Comment by jonathandturner** [comment]
@koenaad - are you able to try the version of Nu in master?

**Comment by koenaad** [comment]
Okay, I've updated to the latest master now.

If I run nushell directly using `cargo run`, it works as expected.
If I install nushell and then run it, it doesn't (same behaviour as above).

I installed nu using:
```
cargo install --path . --featuers=stable --force
```

My config folder seems normal. I have a `history.toml` and an empty `config.toml`.
Are there any other sources nushell will take configs from?
```
❯ ls "/Users/koenraad/Library/Application Support/nu"
───┬────────────────────────────────────────────────────────────┬──────┬────────┬────────────
 # │ name                                                       │ type │ size   │ modified 
───┼────────────────────────────────────────────────────────────┼──────┼────────┼────────────
 0 │ /Users/koenraad/Library/Application Support/nu/config.toml │ File │   —    │ 6 days ago 
 1 │ /Users/koenraad/Library/Application Support/nu/history.txt │ File │ 2.0 KB │ 8 secs ago 
───┴────────────────────────────────────────────────────────────┴──────┴────────┴────────────

```

It seems that all executables in `/Users/koenraad/.cargo/bin/` have this issue. I can execute them, but I can't use `which` on them.
This is also the directory where `nu` is installed... 🤔

**Comment by jonathandturner** [comment]
@avandesa - do you know why the issue @koenaad is seeing might happen. It seems like it's something related to `ichwh` or the paths Nu can see when it's been `cargo install`-ed.

**Comment by avandesa** [comment]
I'm not certain, I'll try to reproduce on Linux. I did a quick test to see if it was the space in the path, but it still appeared to work.

**Comment by thegedge** [comment]
I've been able to reproduce on OSX. Not sure the actual bug, but I can continue to dig.

**Comment by avandesa** [comment]
I poked around online and noticed there's far more ways to set env vars in macos, like through the `environment.plist` file. Do we know how `.cargo/bin` is added to `$PATH`? Is it through plist or by adding a line to `~/.profile`?

**Comment by thegedge** [comment]
> I poked around online and noticed there's far more ways to set env vars in macos, like through the environment.plist file.

I think `environment.plist` was environment set before running some application bundle (not sure if it's still used). 

> Do we know how `.cargo/bin` is added to `$PATH`? Is it through plist or by adding a line to `~/.profile`?

I think generally it would be through the sourcing of profile scripts.

I should also call out that it wasn't `cargo` that gave me the issue, but rather `dotnet`, which is in `/usr/local/share/dotnet`. I'm sure it's the same issue, just a different path 🙂

**Comment by avandesa** [comment]
I might have access to a macbook this weekend to try and debug this. I can't reproduce this on Linux, so there's probably some platform-specific behavior that I'm missing.

**Comment by thegedge** [comment]
I just had it not work for a command in `/usr/local/bin`, so there's definitely a larger issue here.

**Comment by koenaad** [comment]
I can confirm #1312 fixed my issue :+1:
