### ISSUE TITLE
Nu-check does not work on files that dont have the ".nu" file extension

### ISSUE THREAD

**Issue by tulilirockz** [nushell/nushell#12072]
### Describe the bug

The nu-check utility refuses to work on files that dont have the `.nu` extension. I know this is supposed to be a intended thing, but still, since files dont strictly need to have a file extension, that might be an issue when someone is trying to make a script that has a "#!/usr/bin/env -S nu" shebang or something like that

### How to reproduce

1. Create a nushell script without the `.nu` file extension
2. Try to run `nu-check ($SCRIPT)`

### Expected behavior

Nu-check should parse the script and do whatever it does

### Screenshots

![image](https://github.com/nushell/nushell/assets/120808662/75af7da0-734e-4ea5-a14d-e8dcadf42264)

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.89.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball) |
| cargo_version      | cargo 1.75.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
>  since files dont strictly need to have a file extension

This isn't necessarily true for cross platform compatibility. Windows scripts would need to have the extension to know what executable they're associated to.

**Comment by tulilirockz** [comment]
True! I guess maybe there should be a flag like "--dont-check-filename" or something like that? (if doing that is even necessary tho)

**Comment by tulilirockz** [comment]
Yup! Sorry for the dupe. Should I close this issue?

**Comment by fdncred** [comment]
yup, and add your comments to the other issue if you found it.

**Comment by tulilirockz** [comment]
Alright! Thank you very much!
