### ISSUE TITLE
Cannot pipe to `start` command?

### ISSUE THREAD

**Issue by Gremious** [nushell/nushell#12074]
### Describe the bug

Is it possible to provide the output of a command to e.g. `start` in a shell?

### How to reproduce

```nu
in ~
❯ pwd
C:\Users\Gremious

in ~
❯ pwd | start
Error: nu::parser::missing_positional

  × Missing required positional argument.
   ╭─[entry #37:1:1]
 1 │ pwd | start
   ╰────
  help: Usage: start <path> . Use `--help` for more information.
```

### Expected behavior

Opens the current working directory in the system's file explorer.

### Configuration

Default @ 0.90.1

**Comment by Gremious** [comment]
Ok I have immediately stumbled onto the fact that you can do `start (pwd)` by just typing random things

A bit unintuitive, while this isn't an "issue" anymore, I would like a comment/link to docs where I could learn why this behaviour happens? Is this intentional behaviour?

**Comment by fdncred** [comment]
You can also do `pwd | start $in`. Feel free to add a PR with docs.
