### ISSUE TITLE
`help` in standard library errors on some commands

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#12073]
### Describe the bug

Certain built-in commands are not found when using `std help`, but are when using regular `help`

### How to reproduce

```Nushell
> help loop
# Works
> use std help
> help loop
Error:   × std::help::item_not_found
   ╭─[entry #2:1:1]
 1 │ help loop
   ·      ──┬─
   ·        ╰── item not found
   ╰────
```

This also occurs with `all` and `any` (among others), but works for `while`, `append`, and others.

### Expected behavior

`std help` to have access to the same commands, at least ;-)

### Configuration

Also occurs in Linux, but here's the latest on Windows:

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.90.1                                               |
| branch             |                                                      |
| commit_hash        | c2992d5d8b8541b64e9fc1440ed2917fc9b757f7             |
| build_os           | windows-x86_64                                       |
| build_target       | x86_64-pc-windows-msvc                               |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                  |
| rust_channel       | 1.73.0-x86_64-pc-windows-msvc                        |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                  |
| build_time         | 2024-02-07 02:25:54 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  | from eml, from ics, from ini, from vcf               |

**Comment by fdncred** [comment]
kind of odd that it doesn't work. i think it's just doing `scope commands | where` in the script.

**Comment by fdncred** [comment]
@kubouch just tagging you here because this is something that your debugger stuff would be helpful on; figuring out why this isn't working.

**Comment by kubouch** [comment]
That's strange, not sure what could be the issue. My debugger stuff probably wouldn't help with it (unless you implement some kind of runtime inspector, which I sort of started last year).

**Comment by NotTheDr01ds** [comment]
Thanks - I found it with some `inspect`'s inserted.

It's failing [here](https://github.com/nushell/nushell/blob/27793e745203adbe76c34bb6a0407b8d53ad7ebf/crates/nu-std/std/help.nu#L650) on:

```Nushell
if ($example.result | describe) == "binary" { str join } else { lines }
```

On any command with a return result that `table` doesn't translate into a string (e.g. int, bool).

I'll send up the `to text` PR soon :P
