### ISSUE TITLE
`nu-check` is not consistent with `nu --ide-check`

### ISSUE THREAD

**Issue by AucaCoyan** [nushell/nushell#12076]
### Describe the bug

Hi, debugging the PR for nu_scripts I realized that `nu-check` gives false (not passed) but `nu --ide-check` doesn't give any error.
I don't know if both are checking the same things, but I believe this should be unintended

### How to reproduce

I could make a script with one of the sample from `nu_scripts`
```nu
let dir = (pwd)
let file = [ $dir, "git-aliases.nu"] | path join
print $file

# we download the file from github
http get https://raw.githubusercontent.com/nushell/nu_scripts/25514da84d4249ecebdb74c3a23c7184fcc76f50/aliases/git/git-aliases.nu
| save "git-aliases.nu" --force

let result_nu_check = http get https://raw.githubusercontent.com/nushell/nu_scripts/25514da84d4249ecebdb74c3a23c7184fcc76f50/aliases/git/git-aliases.nu
| nu-check
print $"nu-check says `git-aliases.nu` is: ($result_nu_check)\n"

print "... but nu --ide-check says it has no errors, only hints"
nu --ide-check 10 $"($file)" | to text  | ['[', $in, ']'] | str join | from json
```

### Expected behavior

I'm not sure if both are expected to have the same results, but I believe they should be!

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.89.0                                               |
| branch             |                                                      |
| commit_hash        | 2c1560e281d65a50d90b30c42006755b364b4928             |
| build_os           | windows-x86_64                                       |
| build_target       | x86_64-pc-windows-msvc                               |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                  |
| rust_channel       | 1.73.0-x86_64-pc-windows-msvc                        |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                  |
| build_time         | 2024-01-09 20:24:38 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by AucaCoyan** [comment]
And tested again with current release `0.90.1`
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.90.1                                   |
| branch             |                                          |
| commit_hash        | c2992d5d8b8541b64e9fc1440ed2917fc9b757f7 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)      |
| rust_channel       | 1.73.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)      |
| build_time         | 2024-02-07 02:27:07 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by kubouch** [comment]
@AucaCoyan Can you check if https://github.com/nushell/nushell/pull/12137 fixes it?

**Comment by AucaCoyan** [comment]
Yup, that fixes it. Thank you!
