### ISSUE TITLE
No prompt-indicator when starting with no config (`nu -n`) after using Starship

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#12096]
### Describe the bug

I'm using Starship for my prompt configuration.

Whenever I start a `nu -n` to test something in a "clean" environment, I have no prompt indicator.

### How to reproduce

Load the `starship/init.nu` generated by Starship or [follow the Nushell Book](https://www.nushell.sh/book/3rdpartyprompts.html#starship) instructions on configuring third-party prompts.

Start a new shell with `nu -n`

The prompt indicator (as well as the multiline, which isn't a big deal for me) will be missing.  I.e., instead of:

```Nushell
~> commandline
```

You'll have:

```Nushell
~commandline
```

### Expected behavior

Loading a `nu -n` will result in a shell with all configuration options set to their defaults, including prompt indicator.

### Configuration

I'm two releases back on this particular installation, but AFAIK the problem will still be present on newer releases (see Additional Context below).

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.89.0                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball)               |
| cargo_version      | cargo 1.75.0                                                                    |
| build_time         | 1980-01-01 00:00:00 +00:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | mimalloc                                                                        |
| features           | dataframe, default, extra, sqlite, trash, which, zip                            |
| installed_plugins  | from eml, from ics, from ini, from vcf, query, query json, query web, query xml |

### Additional context

This is due to the fact that Starship sets:

```Nushell
$env.PROMPT_INDICATOR = ""
```

And the new session created with `nu -n` inherits this value, but doesn't run Starship.  A new Nushell will reset (not inherit) `$env.config`, but other environment variables are not reset (*are* inherited).

Two possible fixes that I can think of:

* If possible, move `$env.PROMPT_INDICATOR` (and related) to `$env.config.PROMPT_INDICATOR` to be consistent with other configuration settings.  I say, "if possible", because I'm assuming there might be a *reason* that it isn't already, but I don't know.

* Reset `$env.PROMPT_INDICATOR` (and related) to default values on startup.

**Comment by fdncred** [comment]
I think what I hear you saying is that we should try to make a way for these env vars to be ignored when starting nushell with -n because if they're ignored, the defaults will kick in. Is that right?

```nushell
$env.PROMPT_COMMAND
$env.PROMPT_COMMAND_RIGHT
$env.PROMPT_INDICATOR
$env.TRANSIENT_PROMPT_COMMAND
$env.TRANSIENT_PROMPT_COMMAND_RIGHT
$env.TRANSIENT_PROMPT_INDICATOR
```

**Comment by NotTheDr01ds** [comment]
@fdncred Exactly. Thanks for summarizing!

**Comment by NotTheDr01ds** [comment]
Might should be in all cases, really - I mean, if using a `nu --config`, you probably want to start with the default values as wel.
