### ISSUE TITLE
How to fully reload changes to a submodule?

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#12099]
### Question

Given a submodules example like [`voice.nu` / `greetings.nu` / `animals.nu`](https://www.nushell.sh/book/modules.html#submodules-and-subcommands) from the Book, how can I make changes to `animals.nu` and have them take effect in the current shell?

If making changes to the main module (`voice.nu` in this case), then simply reimporting the module loads the changes:

```Nushell
use ./voice.nu
```

However, reloading the parent module does *not* seem to reload the submodules.  For instance, change `animals.nu` so that a dog returns `"Woof"` instead of `"haf"`.

* Reloading the parent module doesn't work:

  ```Nushell
  > use ./voice.nu
  > voice animal
  haf
  ```

* Hiding and reloading the main module doesn't work:
 
  ```Nushell
  > hide voice
  > use ./voice.nu
  > # or use voice
  > voice animals dog
  > haf
  ```

* Can't hide the submodule as `voice animals`:

  ```Nushell
  > hide voice animals
  Error: nu::parser::export_not_found

    × Export not found.
     ╭─[entry #1:1:12]
   1 │ hide voice animals
     ·            ───┬───
     ·               ╰── could not find imports
     ╰────
  ```

* Can't hide the submodule as `hide animals`:

  ```Nushell
  > hide animals
  > voice animals dog
  haf
  > hide animals
  > use voice
  > voice animals dog
  haf
  ```

In all cases:

```Nushell
> view source "voice animals dog"
 def voice animals dog [ ] {
    "haf"
```

The only way I've found to reload the submodule is to exit the shell and restart.

### Additional context and details

End-goal:  I'm going to try to start working on some standard library features, and these are all hidden behind submodules.

**Comment by kubouch** [comment]
There seem to be some bugs related to this. Calling `use voice.nu` after changing the file used to reliably reload the module, but maybe something went wrong with our caching.

`hide` is currently being considered to be deprecated in the future, and shouldn't be required to reload a module anyway.

**Comment by NotTheDr01ds** [comment]
Not sure if this is related (guessing it is), but the same "can't reload" issue occurs with `overlay use`/`overlay hide`.

**Comment by danyx23** [comment]
I just ran into this as well, in my case with a directory module. Since these have to re-export file modules now there is effectively no way to edit files and have them refresh other than restarting the nushell session.

**Comment by agirardeau** [comment]
This is particularly difficult with directory-based modules, where as far as I can tell, there's no way to load changes to `mod.nu` in the same shell at all. E.g., with the following:

```
foo/
  mod.nu
```

```nu
# foo/mod.nu
def bar [] { 12 }
```

Running the following prints `12`:

```
> use foo
> foo bar
```

If I update `mod.nu` so that bar returns a different value, re-using `foo` and calling `foo bar` continues to print `12`.

**Comment by WindSoilder** [comment]
@agirardeau For directory module case, you need to `use foo/` to load `foo/mod.nu`, or else you will load a already loaded module
