### ISSUE TITLE
help commands also displays the type of command

### ISSUE THREAD

**Issue by kvrhdn** [nushell/nushell#1209]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
Running `help commands` you get a table with a column "type".
Possible values would be: sink, filter, source, exec(?).

For example:
```
❯ help commands
━━━━┯━━━━━━━━━━━━━┯━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 #  │ name        │ type   │ description 
────┼─────────────┼────────┼──────────────────────────────────────────────────────────────
  0 │ append      │ filter │ Append the given row to the table 
  1 │ autoview    │ sink   │ View the contents of the pipeline as a table or list. 
  2 │ cd          │ exec   │ Change to a new path. 
  3 │ clip        │ sink   │ Copy the contents of the pipeline to the copy/paste buffer 
  4 │ compact     │ filter │ Creates a table with non-empty rows 
  5 │ config      │ source │ Configuration management. 
  6 │ count       │ sink   │ Show the total number of rows. 
  7 │ cp          │ exec   │ Copy files. 
  8 │ date        │ source │ Get the current datetime. 
  9 │ debug       │ sink   │ Print the Rust debug representation of the values 
 10 │ default     │ filter │ Sets a default row's column if missing. 
━━━━┷━━━━━━━━━━━━━┷━━━━━━━━┷━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

This would allow you to filter on a subset of commands. For instance if I'm looking for a command to fetch a website, I could type `help commands | where type == source` and only see commands that create data.

**Describe alternatives you've considered**
Don't know of any alternatives...

**Additional context**
N/A

**Comment by jzaefferer** [comment]
https://www.nushell.sh/book/en/pipeline.html talks about `input` (instead of source), `filter` and `output` (instead of sink).

`config` is both input (`--get`) and output (`--set`), right?

Maybe `cd`, `exit`, `shells` could be of type `shell` or `navigation`?

Looks like `cp` and `mv` are missing docs (at least on https://www.nushell.sh/documentation.html ), maybe that's type `filesystem`?
