### ISSUE TITLE
construct glob from strings

### ISSUE THREAD

**Issue by Zoybean** [nushell/nushell#12105]
### Related problem

I am trying to construct a glob that contains an interpolated string, to passinto functions like `ls`.
In my case, as a way to easily open a C# project's solution file, I was doing:
```
def sln [
  dir: path
] {
  $dir | path join `*.sln` | ls $in |
    get name |
    each { |file|
      start $file
      $file
    }
}
```
In the latest nushell version, this `ls` invocation no longer works, likely as a result of #9558 preventing strings from being treated as globs. What I would like, therefore, is a way to construct a `glob` from strings and other `glob`s, or to perform interpolation on a `glob`. I can see the some relevant discussion in #6014 but it didn't resolve this specific thread.

### Describe the solution you'd like

My suggestion would be to add a new function to join literal strings onto globs, escaping the strings as necessary, e.g.
 ``glob join $dir `/*.sln` | ls $in``
I imagine this function may have the opportunity to treat `string` and `glob` typed parameters differently, i.e. escape significant characters in `string`-typed parameters but not in `glob`-typed parameters, so e.g. if `$dir` was `"a*"` it would be implicitly escaped as `` `a[*]` ``, with the argument to `ls` being `` `a[*]/*.sln` ``

### Describe alternatives you've considered

- Allow string interpolation of glob literals, e.g.
 `` ls $`($dir)/*.sln` ``
I imagine this may have to never escape globs, as it would be unwise or unwieldy to decide on whether some interpolated thing is quoted or not by some rule,  so e.g. if `$dir` was `"a*"` it would not be escaped, with the argument to `ls` being `` `a*/*.sln` ``. I think this sacrifices flexibility compared to a dedicated `glob join` function that can selectively escape strings, but it may be useful anyway, for programmatically constructing `glob` patterns from `string` parts.

- change the behaviour and return type of `++` when applied to `string` and `glob` arguments, to behave like the `glob join` function I described. I think this would be surprising and unexpected behaviour, and therefore best avoided.

**Comment by WindSoilder** [comment]
Can you try `into glob` command?  It's mainly work for this case:
`$dir | path join `*.sln` | ls ($in | into glob)`

**Comment by Zoybean** [comment]
That works!
I think I need to get better at using the `help` feature to find these commands.

**Comment by Zoybean** [comment]
I don't know why I never considered direct conversion from a string instead of string interpolation.
This directly enables the first alternative I listed above. Rather than direct interpolation, just interpolate and call `into glob`.
Closing.
