### ISSUE TITLE
`to json --tabs 1` can't convert int to bool

### ISSUE THREAD

**Issue by gutenye** [nushell/nushell#12115]
### Describe the bug

from the [doc](https://www.nushell.sh/commands/docs/to_json.html), I can pass number to `--tabs`

```sh
{a:1} | to json --tabs 1
```

Got

```
Error: nu::shell::cant_convert

  × Can't convert to bool.
   ╭─[entry #1:1:24]
 1 │ {a:1} | to json --tabs 1
   ·                        ┬
   ·                        ╰── can't convert int to bool
   ╰────
  help: 
```

### How to reproduce

see above

### Expected behavior

works

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.91.0                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | macos-aarch64                                        |
| build_target       | aarch64-apple-darwin                                 |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (Homebrew)       |
| cargo_version      | cargo 1.76.0                                         |
| build_time         | 2024-03-05 20:28:40 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by fdncred** [comment]
Thanks. It looks to me like it is coded wrong.

I think this should probably be `get_flag()` instead of `has_flag()` and it'll need a few other changes, I'm sure.
https://github.com/nushell/nushell/blob/88227500483c1181c612a9f03b453094603dccc5/crates/nu-command/src/formats/to/json.rs#L48

**Comment by JoaoFidalgo1403** [comment]
Hi, I hope you're doing well. I'm interested in contributing to fix this bug. Is it still possible to work on it? If yes, could you please provide any additional information or guidance that might be helpful?

**Comment by fdncred** [comment]
@JoaoFidalgo1403 sure, you can work on it. my guidance was here https://github.com/nushell/nushell/issues/12115#issuecomment-1985593729
