### ISSUE TITLE
Wildcard glob (*) is not accessible both as string and glob for external commands

### ISSUE THREAD

**Issue by huangz986** [nushell/nushell#12124]
### Describe the bug

Builtin commands can handle glob well. But external commands only support strings. I don't know how to use wildcards with external commands now.

### How to reproduce

1. Suppose there are several .txt files in the current directory.
2. `let files = "*.txt"`
3. `bat $files` fails with "No such file or directory"
4. `bat ($files | into glob)` fails with "Cannot convert glob to a string" and "All argument to an external command need to be string-compatible"

### Expected behavior

I expected nu to parse the glob correctly while working with external commands. As to the example, contents of all .txt files under the current directory should be printed in the console.

### Screenshots

![test](https://github.com/nushell/nushell/assets/19283463/9d018702-9082-4969-9c1d-11508880d119)

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.91.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.76.0 (c84b36747 2024-01-18) |
| build_time         | 2024-03-08 18:47:52 +08:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
@WindSoilder any ideas?

**Comment by huangz986** [comment]
I've rechecked git commits and the newest blog post, and I find that the first one of three ways of using glob in the blog post work with external commands. The other two ways don't work, though, I'm not sure if it's a bug.
This command works: `bat ...(glob $files)`

**Comment by huangz986** [comment]
It's quite strange. `ls ...(glob $files)` fails, but `^ls ...(glob $files)` and `rm ...(glob $files) both work. I'm quite confused.

**Comment by WindSoilder** [comment]
> The other two ways don't work, though, I'm not sure if it's a bug.

Nushell doesn't allow implicit conversion between `string` and `glob` value.  So to make a variable work with globbing, you need to use `...(glob $files)`.

> It's strange. ls ...(glob $files) fails, but ^ls ...(glob $files) and rm ...(glob $files) both work. I'm quite confused.

And I agree with you, we need to improve `ls` and `du` to work for `...(glob $files)`

**Comment by huangz986** [comment]
> > The other two ways don't work, though, I'm not sure if it's a bug.
> 
> Nushell doesn't allow implicit conversion between `string` and `glob` value. So to make a variable work with globbing, you need to use `...(glob $files)`.
> 
> > It's strange. ls ...(glob $files) fails, but ^ls ...(glob $files) and rm ...(glob $files) both work. I'm quite confused.
> 
> And I agree with you, we need to improve `ls` and `du` to work for `...(glob $files)`

I see. It looks like `ls` and `du` do not support the `...` expanding as parameters yet. Perhaps you have planned to do so? Should I close this issue or what?

**Comment by WindSoilder** [comment]
Yup, I will close the issue in favor of #12147, thanks for your feedback
