### ISSUE TITLE
SQLite error when an empty set is `into sqlite`'ed

### ISSUE THREAD

**Issue by RGBCube** [nushell/nushell#12126]
### Describe the bug

```nu
❯ {} | into sqlite a.db

SqlInputError { error: Error { code: Unknown, extended_code: 1 }, msg: "near \")\": syntax error", sql: "CREATE TABLE IF NOT EXISTS [main] ()", offset: 35 }
Error:   × Failed to create table
```

### How to reproduce

Run that command

### Expected behavior

I expected it to tell me that it can't do it for an empty table or to create an empty DB.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.90.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball) |
| cargo_version      | cargo 1.75.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
LOL. invalid of course but it still shouldn't error like that. A more descriptive error would be nice.
