### ISSUE TITLE
Create new line in the middle of a prompt

### ISSUE THREAD

**Issue by oyarsa** [nushell/nushell#12123]
### Question

Is there a way to add a new line in the middle of a prompt? For example, in Fish, if you have this prompt: 

```sh
> test |abc
```

Where `|` is the cursor, if you press `Alt-Enter`, the prompt becomes this:

```sh
> test
|abc
```

Bash also has this in the form of `Ctrl-V Ctrl-J`.

Is there a way to do this in nushell/reedline? 

### Additional context and details

I tried various combinations and searched the issues, but couldn't find anything. My pipelines in nushell tend to get very long, and having the ability to go back and reformat like this helps. So far, I've been opening the prompt in Vim and changing stuff there, but it's suboptimal since there's no autocomplete or highlighting. 

PS: I know that you can end a line with `|`, and nushell will add a new line to the prompt. This question concerns an existing prompt to which I want to add lines in the middle.

```sh
❯ nu --version
0.90.1
```

**Comment by fdncred** [comment]
Have you tried adding a keybinding? I have these key bindings that both do the same thing but with different key combinations.
```
  {
    name: insert_newline
    modifier: alt
    keycode: char_i
    mode: [emacs vi_normal vi_insert]
    event: { edit: insertnewline }
  }
  {
    name: insert_newline
    modifier: alt
    keycode: enter
    mode: [emacs vi_normal vi_insert]
    event: { edit: insertnewline }
  }
```

**Comment by oyarsa** [comment]
This works perfectly, thank you!
