### ISSUE TITLE
Test "dummy" apps are getting cargo install-d

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1213]
**Describe the bug**
Our new testing apps like cococo and chop, which are used exclusive for testing purposes, are finding their way into .cargo/bin if you install --features=stable

**To Reproduce**
1. cargo install --path . --force --features=stable from a recent checkout

**Expected behavior**
Don't install the testing apps during a cargo install

**Comment by andrasio** [comment]
Fixed. Closing.
