### ISSUE TITLE
Automatically detect spaces for external arguments

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1214]
**Describe the bug**
Right now if you use $it, we create arguments to pass to the external command. If what we pass has spaces in it, we don't automatically quote value.  Seems like we should.

**To Reproduce**
1. Use $it to pass a value to an external and pass in a value that contains a space

**Expected behavior**
External gets called without any issue

Follow from #1210

**Comment by koenaad** [comment]
I'll work on a PR for this 🙂
