### ISSUE TITLE
Publish rustdoc

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1215]
**Is your feature request related to a problem? Please describe.**
Related to #1007, people mentioned we need to document the codebase better. One suggestion here from @coolshaurya is to publish docs on docs.rs. 

**Describe the solution you'd like**
A well-documented codebase that rustdoc can use to create the docs, and we publish these docs.

**Describe alternatives you've considered**
Just simply documenting the code base is an improvement.

**Comment by jonathandturner** [comment]
I just noticed we *do* publish the docs to docs.rs automatically, but the last few have failed.

Eg) https://docs.rs/crate/nu/0.8.0

**Comment by coolshaurya** [comment]
Maybe nu could publish the docs on its own url like www.nushell.sh/docs/ instead of publishing on docs.rs ?
