### ISSUE TITLE
Able to configure completion prompt

### ISSUE THREAD

**Issue by gutenye** [nushell/nushell#12155]
### Related problem

The completion prompt is always `| `, and you can't change it.

For example, I've set below code 

```sh
$env.PROMPT_INDICATOR_VI_INSERT = ''
$env.PROMPT_INDICATOR_VI_NORMAL = ''
```

After I type `gh <tab>`, you can see there's extra `| ` prompt shows up, and I want to disable it.

[![asciicast](https://asciinema.org/a/49xrUTvXqDXIqX53ljmsNhQMl.svg)](https://asciinema.org/a/49xrUTvXqDXIqX53ljmsNhQMl)

For [this case](https://github.com/starship/starship/issues/5423#issuecomment-1986835886)

### Describe the solution you'd like

Add a new `PROMPT_COMPLETAION` environment variable

```
$env.PROMPT_INDICATOR_COMPLETAION = '| '
```

**Comment by fdncred** [comment]
> The completion prompt is always | , and you can't change it.

Not true. Notice mine below.

![image](https://github.com/nushell/nushell/assets/343840/08dcaa80-e8ae-4719-805b-84785bf1b732)

It seems like you haven't looked into the config.nu deeply enough to see the completion_menu configuration.

**Comment by gutenye** [comment]
Thanks
