### ISSUE TITLE
Access permissions are different for external `mkdir` and nushell's `mkdir`

### ISSUE THREAD

**Issue by sarubo** [nushell/nushell#12161]
### Describe the bug

Access permissions are different for external `mkdir` and nushell's `mkdir`. Nushell's `mkdir` is more lenient.
If this is what you intended, feel free to close this issue without worrying about me.

### How to reproduce

1. `mkdir foo`
2. `^mkdir bar`
3. `^ls -lah --color`

### Expected behavior

Create a directory with the same access permission as the external `mkdir` using nushell's `mkdir`.

### Screenshots

![image](https://github.com/nushell/nushell/assets/47109823/327091b6-0d2a-4fbd-a68d-803c541e5a3d)

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.91.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 3016d7a64ccb2c2eac9f735f6144fc896ea724a5                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (Arch Linux rust 1:1.76.0-1) |
| cargo_version      | cargo 1.76.0                                                     |
| build_time         | 2024-03-06 05:55:14 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

### Additional context

Maybe related to #12007, #10785

**Comment by fdncred** [comment]
`mkdir` is a uutils/coreutils command. we just embed and use their `uu_mkdir` crate. So, this may be a good question for their repo. Alternatively, if their stand-alone mkdir works different than ours, that's also an issue we'd need to resolve.

**Comment by sarubo** [comment]
I tried using `mkdir` of uutils/coreutils.
The result was working the same as `^mkdir` as follows:

![image](https://github.com/nushell/nushell/assets/47109823/483ef6cf-1c8d-4015-9947-316dbe964c64)

I checked and found that uutils/coreutils uses `umask` to adjust permissions.

https://github.com/uutils/coreutils/blob/ffb70592ec9b430dfd28574cab1fe8d59497ed12/src/uu/mkdir/src/mkdir.rs#L60-L61


In contrast, nushell's `mkdir` does not adjust permissions.

https://github.com/KAAtheWiseGit/nushell/blob/c6043eb5002312a40425db8fbc85109a988f6180/crates/nu-command/src/filesystem/umkdir.rs#L13-L15
https://github.com/KAAtheWiseGit/nushell/blob/c6043eb5002312a40425db8fbc85109a988f6180/crates/nu-command/src/filesystem/umkdir.rs#L70
