### ISSUE TITLE
Can't `ls $it`

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1217]
**Describe the bug**
Sometimes you may have multiple directories and you want to quickly see what is in each. You might try something like `echo $nu.path | ls $it`, but this doesn't work.

**To Reproduce**
1. `echo $nu.path | ls $it`

**Expected behavior**
This should `ls` each of the directories in your path

**Comment by andrasio** [comment]
This is weird. It works fine for me.

**Comment by andrasio** [comment]
Hold on a second. You are correct. It ls's the current working directory instead.
