### ISSUE TITLE
Tab completion for custom commands cannot find files, only directories

### ISSUE THREAD

**Issue by Gremious** [nushell/nushell#12176]
### Describe the bug

I have very simple `show` command:
If it's directory - `ls`, if it's file - `cat`.

```nu
def show [path: directory = "."] {
	match ($path | path type) {
		"file" => { cat $path },
		"dir" => { ls $path },
		_ => "idk"
	}
}
```
However, I cannot tab complete files  - only directories. This is still the case if path doesn't have the `directory` type specified.

`ls` output: 

![image](https://github.com/nushell/nushell/assets/21365711/2926abc9-7a9c-4a0c-b957-ab00af633713)

---

real `cat` tab completion: 
![image](https://github.com/nushell/nushell/assets/21365711/6fe490c6-f35d-4ac8-8a92-2ca6b8f85275)
![image](https://github.com/nushell/nushell/assets/21365711/1b2ff8ec-fbc4-41cd-8d87-785f4e3a68fb)

---

`show` tab completion:
![image](https://github.com/nushell/nushell/assets/21365711/d671d448-71b1-4001-964d-887050cb0282)
![image](https://github.com/nushell/nushell/assets/21365711/44f90987-ce28-42da-b002-711291f57455)

### How to reproduce

Paste command in your config.nu
reload nushell
type `show` and press tab, look for files

### Expected behavior

Tab completion should show files as it does for ls/cat/etc.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.90.1                                   |
| branch             |                                          |
| commit_hash        | c2992d5d8b8541b64e9fc1440ed2917fc9b757f7 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)      |
| rust_channel       | 1.73.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)      |
| build_time         | 2024-02-07 02:25:09 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by WindSoilder** [comment]
It's because you are annotating path with `: directory` type, these type of completion is useful for `cd`.

You can get files if you define it with `: path` type, and give the parameter a different name, it will work.

I will close the issue for now, feel free to re-open it if it doesn't work
