### ISSUE TITLE
On ssh, previous prompts overwritten with "nu>" (using oh-my-posh prompt)

### ISSUE THREAD

**Issue by suttonbradley** [nushell/nushell#12180]
### Describe the bug

When ssh'd and using nushell with an oh-my-posh prompt, hitting enter (or finishing any command) results in the previous prompt being replaced with "nu>" (default prompt?) where other terminals will leave the prompt unchanged.

Desired:
![image](https://github.com/nushell/nushell/assets/31932528/8683dcbe-7904-4383-a9a0-4fd1bd5bd511)
Buggy:
![image](https://github.com/nushell/nushell/assets/31932528/cc85a3d4-334b-443f-92c8-f795d303d7e7)

### How to reproduce

use nushell over ssh

### Expected behavior

Expect old prompt render to still be there

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.90.1                                               |
| branch             |                                                      |
| commit_hash        | c2992d5d8b8541b64e9fc1440ed2917fc9b757f7             |
| build_os           | windows-x86_64                                       |
| build_target       | x86_64-pc-windows-msvc                               |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03)                  |
| rust_channel       | 1.73.0-x86_64-pc-windows-msvc                        |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26)                  |
| build_time         | 2024-02-07 02:25:23 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by fdncred** [comment]
Does this still happen on 0.91.0 or 0.91.1 (nightly)?

**Comment by suttonbradley** [comment]
yes, but I think updating oh-my-posh to 19.16.1 just fixed it!
