### ISSUE TITLE
Wrong `histogram` error

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#12194]
### Describe the bug

When a table is piped into a histogram, the resulting error mentions a non-existing `column-name` flag.

### How to reproduce

```Nushell
~/download> ls | histogram 
Error: nu::shell::unsupported_input

  × Unsupported input
   ╭─[entry #22:1:1]
 1 │ ls | histogram 
   · ─┬   ────┬────
   ·  │       ╰── Since --column-name was not provided, only lists of hashable values are supported.
   ·  ╰── input type: Record([("name", String), ("type", String), ("size", Filesize), ("modified", Date)])
   ╰────

~/download> ls | histogram --column-name name
Error: nu::parser::unknown_flag

  × The `histogram` command doesn't have flag `column-name`.
   ╭─[entry #23:1:1]
 1 │ ls | histogram --column-name name
   ·                ──────┬──────
   ·                      ╰── unknown flag
   ╰────
  help: Available flags: --help(-h), --percentage-type(-t). Use `--help` for more information.
```

### Expected behavior

Some other error message.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.90.1                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (Alpine Linux 1.76.0-r0) |
| cargo_version      | cargo 1.76.0                                                 |
| build_time         | 2024-02-14 02:25:04 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

**Comment by fdncred** [comment]
ya, it's not `--column-name` but it is `column-name`, meaning, it's not a flag but an optional parameter. The error message should be fixed.
