### ISSUE TITLE
Environment variables as default parameter values

### ISSUE THREAD

**Issue by jmoore34** [nushell/nushell#12199]
### Related problem

The following is not supported:

```nu
fn get_item [itemId = $env.ITEM_ID, itemType = $env.ITEM_TYPE] { 
   ...
}
```

Error: `Default values should be constant expressions`

### Describe the solution you'd like

Allow a subset of non-const default parameters, namely environmental variables

### Describe alternatives you've considered

1. Manually pass in the environment variable at the call site/REPL. This is a bit too verbose for the repl-like script I'd like to make.
2. Allow the parameters to be null, and default them to the environment variables in the function. This is a bit better, but still a bit verbose.

### Additional context and details

In my use case, the environment variables will always be populated, but there's a question of what to do in the case of the environment variable not being defined. Perhaps the syntax could be 

```nu
fn get_item [itemId = $env.ITEM_ID!, itemType = $env.ITEM_TYPE!] { 
   ...
}
```

i.e., with something like `!` to indicate that the call site should error if the environment variables are not defined.
 
Alternatively, perhaps the parameters must be marked as nullable:

```nu
fn get_item [itemId? = $env.ITEM_ID, itemType? = $env.ITEM_TYPE] { 
   ...
}
```

**Comment by jmoore34** [comment]
Actually, this works pretty well:

```nu
fn get_item [itemId: string] { 
   print ($itemId I default $env.itemId)
}
```

**Comment by srid** [comment]
@jmoore34 Is that (`... I default ...`) still valid Nu syntax?
