### ISSUE TITLE
`clear` not available on windows

### ISSUE THREAD

**Issue by yoshuawuyts** [nushell/nushell#1219]
**Describe the bug**
According to https://github.com/nushell/nushell/issues/859#issuecomment-570910178 `clear` should now work on Windows, but it isn't available for me.

**Screenshots**
![Screenshot 2020-01-14 01 25 35](https://user-images.githubusercontent.com/2467194/72303236-d1a76d80-366c-11ea-8cea-15a75379a0ab.png)

**Configuration (please complete the following information):**
 - OS: Windows
 - Version 0.8.0

__Notes__
`C-l` *does* work as expected however.

**Comment by koenaad** [comment]
For what it's worth, on macOS there also isn't a built-in `clear` command. It falls back to the native command:

```
> which clear
───────┬────────────────┬─────────
 arg   │ path           │ builtin 
───────┼────────────────┼─────────
 clear │ /usr/bin/clear │ No 
───────┴────────────────┴─────────
```

**Comment by JesterOrNot** [comment]
To Fix this we need a few things
1. A check to differentiate: windows vs OSX/Linux (as they both have the built-in clear command)
2.Write some code that will clear the screen for Windows

**Comment by andrasio** [comment]
We wrote an internal command for `echo`. If anyone wants to write an internal command for `clear` please file an issue and we will happily assign it.

**Comment by JesterOrNot** [comment]
I'll file it

**Comment by JesterOrNot** [comment]
Try running the latest code I wrote a new clear command

**Comment by andrasio** [comment]
Closing since the command has been added. Thank you!
