### ISSUE TITLE
`insert` implements closure `$in` inconsistently

### ISSUE THREAD

**Issue by texastoland** [nushell/nushell#12193]
### Describe the bug

I suspect this is a regression because I found it fixing a test in nu_scripts. I haven't checked what else may be affected.

In general I expect any closure `{ $in }` to behave identically to `{ |it| $it }`. Instead `$in` is behaving like stream input in the closure param to `insert`.

### How to reproduce

```console
❯ { in: test } | insert out { get in | str reverse }
Error: nu::shell::incompatible_path_access

  × Data cannot be accessed with a cell path
   ╭─[entry #1:1:29]
 1 │ { in: test } | insert out { get in | str reverse }
   ·                             ─┬─
   ·                              ╰── empty pipeline doesn't support cell paths
   ╰────


❯ { in: test } | insert out { $in.in | str reverse }
Error: nu::shell::incompatible_path_access

  × Data cannot be accessed with a cell path
   ╭─[entry #1:1:33]
 1 │ { in: test } | insert out { $in.in | str reverse }
   ·                                 ─┬
   ·                                  ╰── nothing doesn't support cell paths
   ╰────
```

### Expected behavior

Identical to:

```console
❯ { in: test } | insert out { |it| $it.in | str reverse }
╭─────┬──────╮
│ in  │ test │
│ out │ tset │
╰─────┴──────╯
```

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.91.0                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | macos-x86_64                                         |
| build_target       | x86_64-apple-darwin                                  |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (Homebrew)       |
| cargo_version      | cargo 1.76.0                                         |
| build_time         | 2024-03-05 20:28:40 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  | nu_plugin_explore                                    |

**Comment by IanManske** [comment]
Yeah, I figured this might be a little confusing. This goes back to #11258. To be consistent with the existing behavior of `update`, `upsert` and `insert` were changed so that `$in` would be the value at the cell path (and the closure parameter was kept as the current row/record). For example. this allows both the shorthand update form `ls | update modified { format date }` as well as updating columns based on other columns.

My original thought process was:
> We could change `$in` to be the same as `$it` for `insert`, but then this could affect `upsert` as well. `upsert` is defined as `update` if there is a value, otherwise `insert`. If `update` and `insert` have different values/behavior for `$in` (i.e., `$in` could be either the value at the cell path or the current row), then using `$in` in `upsert` might become difficult (e.g., the shorthand update becomes hard to use).

But I'm open to other solutions / changing the current behavior. For example, defining `upsert` this rigidly probably doesn't do any good. We could change `$in` to be the same as `$it` for `insert`, and then say that `upsert` shares `update`'s semantics regarding `$in`.

**Comment by texastoland** [comment]
Ohhh fascinating. That's quite intuitive for the other 2! For `insert` I personally prefer that `$in` duplicate `$it` on the principle of least surprise. But expanding `insert --help` might be equally good 🙌🏼

**Comment by IanManske** [comment]
> For insert I personally prefer that `$in` duplicate `$it` on the principle of least surprise.

Yeah, I also feel like this is the more intuitive behavior. Thanks for bringing this up! I will make this change sometime soon alongside some additional docs and `help` text :smile:

**Comment by texastoland** [comment]
Thanks a lot for following up 🙏🏼
