### ISSUE TITLE
Bundle nushell book with nu binaries.

### ISSUE THREAD

**Issue by mav3ri3k** [nushell/nushell#12205]
### Related problem

Nushell is feature packed and thus I often look at the book. However it is only accessible online, without offline support or man pages.

### Describe the solution you'd like

Bundle nushell book/commands with binaries such that:
```nu --book 8067``` can open the book on localhost at port 8067, or
```commands 8067``` to open commands on localhost at port 8067

### Describe alternatives you've considered

Man pages are a staple of documentation. They may be considered and gels extremely well with piping and tools like grep.

**Comment by mav3ri3k** [comment]
I believe that I have some idea how this can be done.
I see exposing it as a command a good option `doc book [port]`/`doc commands [port]`. 
- Commands live in crate `nu_commands`. I would create a new module for `doc`. 
- The only mandatory requirement seems to be applying trait `nu_protocol::engine::Command` for the command and finally import the module at `nu_commands/src/lib.rs`. 
- Opening book/command in the browser should be easy as it will not mingle with any shell specific stuff.

Would like me to give it at try ?

**Comment by mav3ri3k** [comment]
True, but it relies on knowing the command beforehand and then looking for specifics.
However, I often find myself looking for the index of commands to find a command that I generally do not use. Something like `cargo doc --open`. I personally find it useful.

**Comment by mav3ri3k** [comment]
Maybe adding to nushell would not be viable. I personally want it so I will be working on it as plugin: [nu_plugin_doc](https://github.com/mav3ri3k/nu_plugin_doc).

**Comment by fdncred** [comment]
> Maybe adding to nushell would not be viable. I personally want it so I will be working on it as plugin: [nu_plugin_doc](https://github.com/mav3ri3k/nu_plugin_doc).

If you get it to work, I'd be happy to add it to awesome-nu. Also, we're working on a plugin template for cargo generate if you need help starting your plugin. https://github.com/fdncred/nu_plugin_template. I've used it in all the plugins I've written.
