### ISSUE TITLE
`sleep` measures time in 100ms chunks

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#12223]
### Describe the bug

Currently `sleep` uses a loop which does a time check every 100ms, so times small times still take 100ms.  And other times get rounded up 100ms.

### How to reproduce

```Nushell
~> timeit { sleep 10ms }
100ms 309µs 147ns
~> timeit { sleep 50ms }
100ms 338µs 642ns
~> timeit { sleep 101ms }
200ms 558µs 749ns
```

### Expected behavior

For small values, sleep for exactly the time specified.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.90.1                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (Alpine Linux 1.76.0-r0) |
| cargo_version      | cargo 1.76.0                                                 |
| build_time         | 2024-02-14 02:25:04 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which, zip                           |
| installed_plugins  |                                                              |

**Comment by IanManske** [comment]
This was recently fixed in #12049 and should be working in v0.91 :smile:

**Comment by KAAtheWiseGit** [comment]
@IanManske thanks, that's indeed the case!

It works reliably for times smaller than 100ms.  Should I keep the issue open for times like `101ms` taking `200ms`, or would that be too niche of an edge case?

**Comment by IanManske** [comment]
> `101ms` taking `200ms`

Oh right, didn't realize that's still an issue. Yeah, let's keep this open for that.

**Comment by fdncred** [comment]
I'm confused, what is not working here?
```
❯ timeit { sleep 101ms }
105ms 63µs 542ns
❯ timeit { sleep 200ms }
210ms 144µs 42ns
❯ timeit { sleep 50ms }
55ms 85µs 875ns
```

**Comment by devyn** [comment]
@fdncred 

> I'm confused, what is not working here?
> 
> ```nushell
> ❯ timeit { sleep 101ms }
> 105ms 63µs 542ns
> ❯ timeit { sleep 200ms }
> 210ms 144µs 42ns
> ❯ timeit { sleep 50ms }
> 55ms 85µs 875ns
> ```

```nushell
> timeit { sleep 220ms }
301ms 609µs 660ns
```

Should be a pretty easy fix. I would calculate a deadline as an instant in the future and then sleep in increments of `min(max(deadline - now, 0ns), 100ms)`

**Comment by fdncred** [comment]
ok, i see this now. i just wasn't seeing the failures.
```nushell
❯ timeit { sleep 220ms }
312ms 991µs 750ns
```

**Comment by sunanda35** [comment]
I tried, works for me though.
