### ISSUE TITLE
Can't insert null `into sqlite` since 0.90

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#12225]
### Describe the bug

Can no longer insert a `null` via `into sqlite`.

### How to reproduce

```Nushell
> [
  { name: 'foo', modified_date: 1710703657 }
  { name: 'bar', modified_date: null}
]
| into sqlite foo.sqlite
```

Result:

```Nushell
Error: nu::shell::only_supports_this_input_type

  × Input type not supported.
   ╭─[source:1:1]
 1 │ nu --login
   · ▲
   · ╰── only bool, int, float, filesize, duration, date, string, nothing, binary input data is supported
   ╰────
   ╭─[entry #1:3:33]
 2 │   { name: 'foo', modified_date: 1710703657 }
 3 │   { name: 'bar', modified_date: null}
   ·                                 ──┬─
   ·                                   ╰── input type: nothing
 4 │ ] | into sqlite foo.sqlite
   ╰────
```

### Expected behavior

In 0.89, this worked fine.  

```Nushell
> [
  { name: 'foo', modified_date: 1710703657 }
  { name: 'bar', modified_date: null}
]
| into sqlite foo.sqlite
> open foo.sqlite
╭──────┬──────────────────────────────╮
│      │ ╭───┬──────┬───────────────╮ │
│ main │ │ # │ name │ modified_date │ │
│      │ ├───┼──────┼───────────────┤ │
│      │ │ 0 │ foo  │    1710703657 │ │
│      │ │ 1 │ bar  │               │ │
│      │ ╰───┴──────┴───────────────╯ │
╰──────┴──────────────────────────────╯
```

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.91.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (built from a source tarball) |
| cargo_version      | cargo 1.76.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | dataframe, default, extra, sqlite, trash, which, zip              |
| installed_plugins  |                                                                   |

### Additional context

I believe this change came with #10232 since that's the only `into sqlite` related change in 0.90.

This is a pretty big issue for me, and I haven't found a workaround yet other than continuing to run under 0.89.  Took me a while to notice it since I skipped 0.90.

**Comment by fdncred** [comment]
@dead10ck would you mind looking into this? I'm guessing it's because not all value types are handled in `value_to_sql()` anymore, namely `Value::Nothing`. That's my guess.

**Comment by dead10ck** [comment]
Oops, yeah, looks like I missed null. 😬 My bad. I can write up a patch when I get some time.

**Comment by dead10ck** [comment]
So actually, it turns out there's a small UX issue here. When the DB doesn't yet exist, we currently infer what the schema should be based on the first value that gets passed in. If that value is null, then we don't actually know what the type should be.

I'm thinking it might be best to throw an error that tells the user that either the first value can't be null or they have to create the DB beforehand.

We could probably add a command line switch that allows the user to specify the schema with Nushell types, but that should probably be a separate PR.

What do you folks think?

**Comment by fdncred** [comment]
When I wrote `into sqlite` I never intended the database to exist prior to running it. The whole point of `into sqlite` is to create a sqlite database and put your nushell data into it. Seems like what I was doing prior was if the value was null, i just created an empty string and inserted that. Maybe that's wrong. I really don't want to have an error if the sqlite db does not exist beforehand.

A schema would be nice, but agreed, that's separate.

**Comment by dead10ck** [comment]
Hmm, so if the column is supposed to be an int, and the first row's value for that column happens to be null, if we just assume `TEXT`, then we end up with a wrong database schema.

But in practice, maybe this won't matter much. Sqlite is dynamically typed anyway, so it has no qualms with inserting an int into a text column, unless the table is a strict table. But we don't currently give users this option anyway, so maybe that could be part of a separate change where we could allow users to make a strict table, and in this case require passing the schema explicitly.

So maybe for now just going back to the prior behavior of making a text column is a fine default behavior.

**Comment by dead10ck** [comment]
Actually, scratch that, I just tested it, and it inserts text if the column type is text, even with an int for input. So if we just assume text, then the column values really do end up with the wrong type.

**Comment by dead10ck** [comment]
Well it would be one thing if the non-null inserted values ended up with the right type, but if they all end up text, it isn't just a cosmetic theoretical problem. Consider this example, with the command patched to simply choose `TEXT` when the first value is null:

```
❯ : [{ name: foo, score: 2.1111 }, {name: bar, score: 10}, {name: quux, score: null}] | into sqlite test_good.db

❯ : [{name: quux, score: null}, { name: foo, score: 2.1111 }, {name: bar, score: 10}] | into sqlite test_bad.db

❯ : sqlite3 test_good.db 'select * from main order by score;'
quux|
foo|2.1111
bar|10.0

❯ : sqlite3 test_bad.db 'select * from main order by score;'
quux|
bar|10
foo|2.1111
```

The resulting database can end up useless, and the user may not know it right away, because we just made a decision for them.

**Comment by fdncred** [comment]
i'm still not real worried about it because the values can probably be cast to a certain datatype in nushell. if there was a good fix though, i wouldn't oppose it.

**Comment by NotTheDr01ds** [comment]
I just checked my databases, and yes:

* If the `last_edit_date` was present, it's inserted as an `int`
* If the `last_edit_date` wasn't in the API result set, I set the value to { last_edit_date: null } before passing it `into sqlite`.  The result is, as you expected, an empty string in that row.

That's been okay with me, because as @fdncred said, Nushell has been just "doing the right thing" with the values/types.

If there's a good fix, I wouldn't oppose it either, but it will mean that I'll have to scrub about 10GB of SQLite files to get them into the proper schema.  A sacrifice I'm willing to make ;-).

**Comment by NotTheDr01ds** [comment]
> That's been okay with me, because as @fdncred said, Nushell has been just "doing the right thing" with the values/types.

Hmm - Actually I take that back.  It's just a bug I never hit before, but the issue @dead10ck mentioned is present in my data:

```
sqlite3 test_bad.db 'select * from main order by score;'
```

I start a new db every month, and some of them had a `last_edit_date` as the first value, while some didn't.

If I was sorting by that data, well ... I still wouldn't have a problem since the Unix epoch isn't going to roll over anytime soon to causing an alpha sorting issue.  But I see the *potential* issue even with my data.

Again, I'm fine with "fixing" the data once a final solution is reached.

In the meantime, I'd be okay with the way things were working, so that I can at least insert `null`'s again.

**Comment by NotTheDr01ds** [comment]
One more separate comment.  I (now) understand that I've been totally abusing your (@fdncred) intention for `into sqlite`, but dang if it isn't so awesome in that abused state 😆.  I was looking back through my `history` as I converted from text-backend to SQLite, and I saw that `into sqlite` was *exactly* what made me move to Nushell over a year ago. I was going through doing this same thing with Prisma/JavaScript, but Nushell's `into sqlite` just made it 100 times easier.  Okay, 42 times easier ... That's a totally objective measurement.

**Comment by fdncred** [comment]
nice!

i'm wondering if there's a subcommand that could be written to enforce and convert by a schema?

**Comment by dead10ck** [comment]
Ok, I'll just go with defaulting to text for now and make a follow-up PR to specify a schema. But I do think it at least warrants a warning to the user, so I'll print a message to stderr when it makes this decision.

**Comment by NotTheDr01ds** [comment]
@dead10ck  Thanks! Just for clarity - Print a warning on *every* attempt to insert a `null` or just when it is creating the initial (bad) schema?

**Comment by dead10ck** [comment]
When it creates a new table from a null column. Every insert would be way too noisy lol

**Comment by NotTheDr01ds** [comment]
Whew ;-)

**Comment by dead10ck** [comment]
Ok I have a PR up: #12328

**Comment by NotTheDr01ds** [comment]
Thank you both!  Tested and confirmed that my script works again with the commit.
