### ISSUE TITLE
Unable to cd to folder name with dot in it.

### ISSUE THREAD

**Issue by dietercastel** [nushell/nushell#1224]
**Describe the bug**
Changing directory to a folder with a dot in the name results in a parse error.

**To Reproduce**
1. mkdir trying.this.out
2. cd trying.this.out/
3. See the parse error.

**Expected behavior**
That the directory name is parsed correctly and the current directory changed.

**Screenshots**

**Configuration (please complete the following information):**
 - OS: OSX
 - Version 0.8.0

As in #491: the workaround with enclosing the folder name in quotes works, although not convenient. (e.g. `cd "trying.this.out"` works.)

**Comment by reuvenab** [comment]
Issue still reproduces with nushell 0.10.1 on Windows 10
![image](https://user-images.githubusercontent.com/85445/75966625-4f506280-5ed3-11ea-8d3a-3b5f28994f4c.png)

**Comment by reuvenab** [comment]
Does commit [798a24e ](https://github.com/nushell/nushell/commit/798a24eda5aebe395a4489e28c0a30dd0c246043)should handle this flow?

![image](https://user-images.githubusercontent.com/85445/75967403-6ba0cf00-5ed4-11ea-8405-2d42776f164e.png)
