### ISSUE TITLE
Allow `return` in closures

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#12257]
### Related problem

I have a script with a `filter` closure, operating on table.  For certain rows, which don't have a field filled out, I want to return `false` early.  Currently, it's not possible to do it and I have to use nested `if`s instead:

```Nushell
	$tasks
	| sort-by deadline
	| filter {|task|
		if $task.deadline == null {
			return false
		}
		$task.deadline + 23.99hr > (date now) and (not $task.completed)
	}
```

### Describe the solution you'd like

Allow `return` in closures.

### Describe alternatives you've considered

It's possible that a new keyword for returning a value in a closure, i.e. `yield`, might be warranted here.

**Comment by sholderbach** [comment]
Same issue as in #7933 

We already support `return` in closures, but each command needs to properly invoke the block to handle the `ShellError::Return` we use to signal that.

On the fix for `filter`
