### ISSUE TITLE
Weird output from nushell ls command and seach with rg

### ISSUE THREAD

**Issue by trondhe** [nushell/nushell#12255]
### Describe the bug

Hey, I am entirely unsure where this problem lies in, but it only happens with nushell as I figured out.
But ripgrep gives a funny duplicate binary name from ls command.

### How to reproduce

1. wget https://apt.llvm.org/llvm.sh 
2. chmod +x llvm.sh
3. ./llvm.sh 18
4. cd /usr/bin
5. mv clangd-18 clangd 
6. ls -l | grep clangd // Observe output
7. ls -l | rg clangd // Observe output

This gives the following output for me. Both in nushell and then after just bash
```script
/usr/bin> ls -l | grep clangd                                                                                                              03/21/2024 11:11:25 AM
│ 165 │ clangd     │ symlink │ ../lib/llv │ false    │ rwxrwxrwx │         1 │ 24001646 │ root │ root    │       25 B │ 15 minutes  │ 15 minutes  │ 4 days ago  │
/usr/bin> ls -l | rg clangd                                                                                                                03/21/2024 11:11:44 AM
│ 165 │ clangdclangd     │ symlink │ ../lib/llv │ false    │ rwxrwxrwx │         1 │ 24001646 │ root │ root    │       25 B │ 15 minutes  │ 15 minutes  │ 4 days ago  │
/usr/bin> bash                                                                                                                             03/21/2024 11:12:03 AM
trondhe@pop-os:/usr/bin$ ls | grep clangd
clangd
trondhe@pop-os:/usr/bin$ ls | rg clangd
clangd
```

### Expected behavior

`ls | rg clangd` and `rg | grep clangd` should give same output both for both nushell and bash.
But for nushell and ripgrep, it duplicates the binary name.

I have checked the filesystem and there is for sure no `clangdclangd` executable in /usr/bin/.

Not sure if its an error of me, or a bug in ripgrep. But its an interesting bug anyway.

### Configuration

```script
~> version | transpose key value | to md --pretty         03/21/2024 11:15:02 AM
| key                | value                                                   |
| ------------------ | ------------------------------------------------------- |
| version            | 0.91.0                                                  |
| branch             |                                                         |
| commit_hash        | 3016d7a64ccb2c2eac9f735f6144fc896ea724a5                |
| build_os           | linux-x86_64                                            |
| build_target       | x86_64-unknown-linux-gnu                                |
| rust_version       | rustc 1.74.1 (a28077b28 2023-12-04)                     |
| rust_channel       | 1.74.1-x86_64-unknown-linux-gnu                         |
| cargo_version      | cargo 1.74.1 (ecb9851af 2023-10-18)                     |
| build_time         | 2024-03-05 20:50:10 +00:00                              |
| build_rust_channel | release                                                 |
| allocator          | mimalloc                                                |
| features           | default, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  |  
```

**Comment by fdncred** [comment]
I'm assuming this is because `rg` doesn't understand what ansi escape codes are (or isn't filtering them out during the search) and you have `$env.config.ls.clickable_links` set to true.

Each file name in the `ls` output in fact has the name twice, once for display, and once for a clickable link. You might want to search the `rg` documentation for links or hyperlinks to see if there's a parameter you can use with it to disable using it.

For searching through nushell tables, nushell provides the `find` command that works better. `ls | find term`.

We can reopen if we need to.

**Comment by trondhe** [comment]
Huh, that is interesting. Didnt know it was clickable, neat!
I can put an issue in ripgrep perhpa just to see what they think what is the correct behaviour,. Because as you said, this is technically correct.
