### ISSUE TITLE
`$in` variable is nothing

### ISSUE THREAD

**Issue by mb21** [nushell/nushell#12254]
### Describe the bug

Using an arbitrary variable name like `x` works:

```
> ls * | insert foo {|x| $x}
╭───┬────────────┬──────┬──────────┬────────────────┬───────────────────────────────╮
│ # │    name    │ type │   size   │    modified    │              foo              │
├───┼────────────┼──────┼──────────┼────────────────┼───────────────────────────────┤
│ 0 │ README.md  │ file │  2.2 KiB │ 28 minutes ago │ ╭──────────┬────────────────╮ │
│   │            │      │          │                │ │ name     │ README.md      │ │
│   │            │      │          │                │ │ type     │ file           │ │
│   │            │      │          │                │ │ size     │ 2.2 KiB        │ │
│   │            │      │          │                │ │ modified │ 28 minutes ago │ │
│   │            │      │          │                │ ╰──────────┴────────────────╯ │
╰───┴────────────┴──────┴──────────┴────────────────┴───────────────────────────────╯
```

### How to reproduce

Using the variable name `$in` doesn't:

```
> ls * | insert foo {|in| $in}
╭───┬────────────┬──────┬──────────┬────────────────┬─────╮
│ # │    name    │ type │   size   │    modified    │ foo │
├───┼────────────┼──────┼──────────┼────────────────┼─────┤
│ 0 │ README.md  │ file │  2.2 KiB │ 27 minutes ago │     │
╰───┴────────────┴──────┴──────────┴────────────────┴─────╯
```

I found some references in the docs that `$in` is a special variable, but not even that works:

```
ls * | insert foo {$in}
╭───┬────────────┬──────┬──────────┬────────────────┬─────╮
│ # │    name    │ type │   size   │    modified    │ foo │
├───┼────────────┼──────┼──────────┼────────────────┼─────┤
│ 0 │ README.md  │ file │  2.2 KiB │ 29 minutes ago │     │
╰───┴────────────┴──────┴──────────┴────────────────┴─────╯
```

### Expected behavior

The `foo` column should not be `nothing`.

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.89.0                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | macos-aarch64                                        |
| build_target       | aarch64-apple-darwin                                 |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21) (Homebrew)       |
| cargo_version      | cargo 1.75.0                                         |
| build_time         | 2024-01-09 20:16:29 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by fdncred** [comment]
Yes, `$in` is special. It's mostly because you're using version 0.89.0 and 0.89.0 is pretty old. We make changes fast. There could've been functionality changes and/or bug fixes.
```nushell
❯ ls | insert foo $in
╭─#─┬────name────┬─type─┬─size──┬───modified───┬──────foo───────╮
│ 0 │ Cargo.lock │ file │ 390 B │ 2 days ago   │ [table 4 rows] │
│ 1 │ Cargo.toml │ file │ 205 B │ 2 days ago   │ [table 4 rows] │
│ 2 │ src        │ dir  │ 128 B │ 12 hours ago │ [table 4 rows] │
│ 3 │ target     │ dir  │ 160 B │ 3 days ago   │ [table 4 rows] │
╰───┴────────────┴──────┴───────┴──────────────┴────────────────╯
```
or
```nushell
❯ ls | insert foo ($in)
╭─#─┬────name────┬─type─┬─size──┬───modified───┬──────foo───────╮
│ 0 │ Cargo.lock │ file │ 390 B │ 2 days ago   │ [table 4 rows] │
│ 1 │ Cargo.toml │ file │ 205 B │ 2 days ago   │ [table 4 rows] │
│ 2 │ src        │ dir  │ 128 B │ 12 hours ago │ [table 4 rows] │
│ 3 │ target     │ dir  │ 160 B │ 3 days ago   │ [table 4 rows] │
╰───┴────────────┴──────┴───────┴──────────────┴────────────────╯
```
or (notice this one is different than the others)
```nushell
❯ ls | insert foo {$in}
╭─#─┬────name────┬─type─┬─size──┬───modified───┬────────foo────────╮
│ 0 │ Cargo.lock │ file │ 390 B │ 2 days ago   │ {record 4 fields} │
│ 1 │ Cargo.toml │ file │ 205 B │ 2 days ago   │ {record 4 fields} │
│ 2 │ src        │ dir  │ 128 B │ 12 hours ago │ {record 4 fields} │
│ 3 │ target     │ dir  │ 160 B │ 3 days ago   │ {record 4 fields} │
╰───┴────────────┴──────┴───────┴──────────────┴───────────────────╯
```
Closing, as I believe this answers your question. We can open if again if we need to.

**Comment by mb21** [comment]
Ah sorry, I forgot to open a new terminal after updating nushell to 0.91.0. But there I still get a different result for `ls | insert foo {$in}` than you do. But if you're using latest `main` branch build, then it's probably fixed there already.

That being said, does the following work for you?

    ls | insert foo {|in| $in}

For me, it returns an empty column, which is unexpected?

**Comment by fdncred** [comment]
```nushell
❯ ls | insert foo {|in| $in}
╭─#──┬────────name─────────┬─type─┬───size───┬───modified───┬────────foo────────╮
│ 0  │ CODE_OF_CONDUCT.md  │ file │   3.4 KB │ a year ago   │ {record 4 fields} │
│ 1  │ CONTRIBUTING.md     │ file │  11.4 KB │ 2 weeks ago  │ {record 4 fields} │
│ 2  │ Cargo.lock          │ file │ 161.5 KB │ 13 hours ago │ {record 4 fields} │
│ 3  │ Cargo.toml          │ file │   6.4 KB │ a day ago    │ {record 4 fields} │
│ 4  │ Cross.toml          │ file │    666 B │ 3 weeks ago  │ {record 4 fields} │
...
```
