### ISSUE TITLE
expose the recursion limit value as a config option

### ISSUE THREAD

**Issue by kurokirasama** [nushell/nushell#12253]
### Related problem

I have a script that via recursion, iterates trough the pages of a youtube playlist via the youtube api. One youtube playlist has around 60 pages, and therefore I get the `Recursion limit (50) reached` error, since the limit is set to 50.

### Describe the solution you'd like

a configuration option to set this value to our needs

**Comment by fdncred** [comment]
From the Discord chat. I think it's here https://github.com/nushell/nushell/blob/c810f5e3daf7902898d38a0d168ef27301e81145/crates/nu-engine/src/eval.rs#L46-L59.

**Comment by fdncred** [comment]
@kurokirasama can you check the latest main to see if it fixes your issue here? It's now configurable after #12308

**Comment by kurokirasama** [comment]
> @kurokirasama can you check the latest main to see if it fixes your issue here? It's now configurable after #12308

hey, I set the limit to 100 and now my script is working again. Thanks!
