### ISSUE TITLE
No response after executing "git pull" and "git bash" with a proxy

### ISSUE THREAD

**Issue by road2coder** [nushell/nushell#12265]
### Describe the bug

Nushell would not respond to my subsequent commands after  executing "git pull" or "git push" with a proxy. I'm not sure if this is a problem with NuShell, but it works fine in other shells such as powershell and git bash.

### How to reproduce

1. add proxy config to ~/.ssh/config
```shell
Host github.com
  Hostname ssh.github.com
  ProxyCommand "D:\Environment\Git\mingw64\bin\connect.exe" -S 127.0.0.1:1080 -a none %h %p
```
2. execute "git pull" or "git push"，it works and print the result.
3. I can do nothing except input some characters.

### Expected behavior

Works fine after executing "git pull" and "git push".

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.91.0                                               |
| branch             |                                                      |
| commit_hash        | 3016d7a64ccb2c2eac9f735f6144fc896ea724a5             |
| build_os           | windows-x86_64                                       |
| build_target       | x86_64-pc-windows-msvc                               |
| rust_version       | rustc 1.74.1 (a28077b28 2023-12-04)                  |
| rust_channel       | 1.74.1-x86_64-pc-windows-msvc                        |
| cargo_version      | cargo 1.74.1 (ecb9851af 2023-10-18)                  |
| build_time         | 2024-03-05 20:46:04 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by WindSoilder** [comment]
It's strange....I use `git pull` and `git push` everyday, and don't see any issues.

**Comment by fdncred** [comment]
I use git all day long, no issues.

**Comment by road2coder** [comment]
> It's strange....I use `git pull` and `git push` everyday, and don't see any issues.

@WindSoilder It works well on linux. The issue only occurs on windows.

**Comment by wandleshen** [comment]
Hi @SeanSelene, sorry to bother you on this closed issue.

I am experiencing the exact same behavior on windows where nushell freezes (can type but can't enter/backspace) after a git pull. I noticed that you closed this issue—could you share how you eventually resolved it?
