### ISSUE TITLE
BASH/ZSH-like History Expansion

### ISSUE THREAD

**Issue by VehementHam** [nushell/nushell#12269]
### Related problem

The history expansion included in the Nushell is very lacking. I was disapointed when I ran `!?command [argument]`, and it did not run the last command starting with the string `command [argument]`. `^old^new^` does not work anymore either.

### Describe the solution you'd like

Here is documentation on ZSH history expansion: [#History-Expansion](https://zsh.sourceforge.io/Doc/Release/Expansion.html#History-Expansion). I would like all of these features implemented, as they can greaty increase the productivity of the user.

**Comment by fdncred** [comment]
Some of these are implemented via reedline like `!!`, `!n`, `!-n`, `!$`. You can find the code by looking for bashisms in reedline. We might be willing to accept a PR for more but being bash/zsh/posix compliant is a non-goal.

**Comment by VehementHam** [comment]
Okay, got it.
