### ISSUE TITLE
Multiple output types can't be formatted across multiple lines

### ISSUE THREAD

**Issue by texastoland** [nushell/nushell#12264]
### Describe the bug

Multiple output types can't be formatted across multiple lines.

### How to reproduce

```nu
def demo [--verbose]: [
  nothing -> nothing
  nothing -> string
] {
  print demoing
  if $verbose {
    'done'
  }
}
```

### Expected behavior

Parse instead of:

```
Error: nu::parser::unknown_type

  × Unknown type.
   ╭─[entry #1:1:24]
 1 │ def demo [--verbose]: [
   ·                        ┬
   ·                        ╰── unknown type
 2 │   nothing -> nothing
 3 │   nothing -> string
   ╰────
```

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.91.0                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | macos-x86_64                                         |
| build_target       | x86_64-apple-darwin                                  |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (Homebrew)       |
| cargo_version      | cargo 1.76.0                                         |
| build_time         | 2024-03-05 20:28:40 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  | nu_plugin_explore                                    |

### Additional context

I haven't tried it but my suspicion is this line:

https://github.com/nushell/nushell/blob/cc8f2b6419daa7c5c55fb8ca0ef257fc76be6674/crates/nu-parser/src/parser.rs#L3057

... needs `&[b'\n', b'\r', b',']` as `additional_whitespace`.

**Comment by amtoine** [comment]
@texastoland 
maybe the following should be allowed too? what you think?
```nushell
def foo []: nothing -> table<
    a: string,
    b: int,
> {
    [{ a: "lol", b: 123 }]
}
```
right now, it requires to wrap the io types in `[ ... ]` but `[ ... ]` are optional when there is a single io pair.

**Comment by texastoland** [comment]
> maybe the following should be allowed too?

I initially didn't add it here in case it needed discussion.

> are optional when there is a single io pair.

But totally agree about consistency. I'll PR later ✌🏼
