### ISSUE TITLE
Allow functions and modules to have the same name

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#12275]
### Related problem

I'm writing completions and putting them into files, named after the commands.  So, I have an `img2sixel.nu` file with `export extern img2sixel [` in it.

I don't want to rename all of the commands to `main`, because it would be confusing for subcommands.  A file for git, for example, would have `export extern main` and `export extern "git pull"`.

### Describe the solution you'd like

Allow function to have the same name as its parent module.

**Comment by fdncred** [comment]
> I don't want to rename all of the commands to main, because it would be confusing for subcommands. A file for git, for example, would have export extern main and export extern "git pull".

I could be wrong here, but I thought if your file was called `git.nu` and you had `main` and a `pull` custom command. You could use `use git.nu` and do `git pull` and it would call your `pull` custom command.

**Comment by KAAtheWiseGit** [comment]
@fdncred right, I didn't realize `extern` was subject to the same rules, as the `def` namespacing!

Thanks, I'll close the issue because my complaint is invalid.
