### ISSUE TITLE
regression(0.91.1): binary `| each { table }`

### ISSUE THREAD

**Issue by texastoland** [nushell/nushell#12287]
### Describe the bug

Uncovered in https://github.com/nushell/nushell.github.io/pull/1312#issuecomment-2017281910. I assume it's an `each` bug. But I tried replacing `table` with other commands like `to nuon` and couldn't cause it. Interestingly `for` just silently fails and it isn't `catch`-able either.

### How to reproduce

```console
❯ 0x[8989] | table
Length: 2 (0x2) bytes | printable whitespace ascii_other non_ascii
00000000:   89 89                                                ××

❯ 0x[8989] | each { table }
Length: 2 (0x2) bytes | printable whitespace ascii_other non_ascii
00000000:   89 89                                                ××

❯ [0x[8989]] | each { table }
Error: nu::shell::cant_convert

  × Can't convert to string.
   ╭─[entry #1:1:21]
 1 │ [0x[8989]] | each { table }
   ·                     ──┬──
   ·                       ╰── can't convert binary to string
   ╰────

❯ for $it in [0x[8989]] { $it | table | print }

❯ for $it in [0x[8989]] { $it | print }
Length: 2 (0x2) bytes | printable whitespace ascii_other non_ascii
00000000:   89 89                                                ××
```

### Expected behavior

Homebrew version:

```console
❯ /usr/local/bin/nu -n -c '[0x[8989]] | each { table }'
╭───┬─────────────────────────────────────────────────────────────────────╮
│ 0 │ Length: 2 (0x2) bytes | printable whitespace ascii_other non_ascii  │
│   │ 00000000:   89 89                                                ×× │
│   │                                                                     │
╰───┴─────────────────────────────────────────────────────────────────────╯
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.91.1                                   |
| branch             | main                                     |
| commit_hash        | b2c5dc204a851c7d2a7cd07b2b3157ba9e1f2173 |
| build_os           | macos-x86_64                             |
| build_target       | x86_64-apple-darwin                      |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21)      |
| rust_channel       | 1.75.0-x86_64-apple-darwin               |
| cargo_version      | cargo 1.75.0 (1d8b05cdd 2023-11-20)      |
| build_time         | 2024-03-25 21:20:31 -05:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | dataframe, default, sqlite, trash, which |
| installed_plugins  | explore                                  |

**Comment by fdncred** [comment]
Have you done a git bisect to see where this regression took place? I'm not saying you're wrong, but I don't ever remember being able to do that. I thought the pretty print output of binary was always "dumb" text and couldn't be changed.

This works
```nushell
❯ [0x[8989]]
╭───┬────────────╮
│ 0 │ [137, 137] │
╰───┴────────────╯
```
```nushell
❯ 0x[8989] | wrap output
╭────────┬────────────╮
│ output │ [137, 137] │
╰────────┴────────────╯
```

**Comment by texastoland** [comment]
> Have you done a git bisect to see where this regression took place?

I fell asleep before I got that far.

> I don't ever remember being able to do that.

This is a minimal repro of nushell/nushell.github.io#1312 (linked above) breaking the build script (on `main` not only the PR branch). It also works in Homebrew (output in the description).

> This works

I don't understand how it's related?

### Better Description

I probably didn't provided enough context:

#### 1. The `table` error isn't `catch`-able

Nu (`main`) errors (despite `try`) on the following line from https://github.com/nushell/nushell.github.io/blob/main/make_docs.nu (also `main`):

```nushell
let result = (do -i { $example.result | try { table --expand } catch { $in } } )
```

https://github.com/nushell/nushell.github.io/pull/1312#issuecomment-2019386391 provides a more thorough debug session. 1 input `make_docs` errors on is:

```console
❯ let repro = scope commands | where name == 'bits and' | get examples.0.result

❯ $repro | each { table }
Error: nu::shell::cant_convert

  × Can't convert to string.
   ╭─[entry #1:1:17]
 1 │ $repro | each { table }
   ·                 ──┬──
   ·                   ╰── can't convert binary to string
   ╰────


❯ $repro | each { describe }
╭───┬──────────────╮
│ 0 │ int          │
│ 1 │ binary       │
│ 2 │ list<int>    │
│ 3 │ list<binary> │
│ 4 │ binary       │
│ 5 │ binary       │
╰───┴──────────────╯
```

#### 2. `$binary_list | each { table }` breaks in nightly but not release

The repro can be simplified using its exact value instead of `scope commands`:

```console
❯ $repro.1 | to nuon
0x[8989]

❯ [0x[8989]] | each { table }
Error: nu::shell::cant_convert

  × Can't convert to string.
   ╭─[entry #1:1:21]
 1 │ [0x[8989]] | each { table }
   ·                     ──┬──
   ·                       ╰── can't convert binary to string
   ╰────
```

#### 3. `$binary_value | table` works

```console
❯ 0x[8989] | table
Length: 2 (0x2) bytes | printable whitespace ascii_other non_ascii
00000000:   89 89                                                ××
```

This is also the result you previously generated in https://www.nushell.sh/commands/docs/bits_and.html#examples. Notably `each` started behaving differently than piping each value directly.


#### 3. `$binary_value | each { table }` also works

```console
❯ 0x[8989] | table
Length: 2 (0x2) bytes | printable whitespace ascii_other non_ascii
00000000:   89 89                                                ××
```

Just exploring edge cases.

#### 4. `for $it in $binary_list { $it | table | print }` neither works nor errors

```console
❯ for $it in [0x[8989]] { $it | table | print }

❯ for $it in [0x[8989]] { $it | print }
Length: 2 (0x2) bytes | printable whitespace ascii_other non_ascii
00000000:   89 89                                                ××
```

I was hoping I could use it as a workaround to patch the website but discovered even more confusing behavior. The current release build produces identical output though.

**Comment by IanManske** [comment]
Looks like there was [special handling](https://github.com/nushell/nushell/blob/26786a759ea5b93d220ab5f50974a71318282bea/crates/nu-command/src/viewers/table.rs#L373) for binary values depending on whether or not the output was being printed to the terminal or if it was being collected as a value. Combined with the changes from #11934, this created some weird behavior. Not sure why this handling was there to begin with, since `table` is essentially a pretty formatter -- the output destination shouldn't matter.
