### ISSUE TITLE
Pasting via keyboard fails on Windows

### ISSUE THREAD

**Issue by tmr232** [nushell/nushell#1232]
**Describe the bug**
On Windows (either the regular shell or Windows Terminal Preview) none of the keyboard-based `paste` hotkeys work. Only the mouse one.

**To Reproduce**
1. Copy text to the clipboard
1. Run `nu.exe`
2. Press `Shift+Insert` or `Ctrl+V`

**Expected behavior**
The text from the clipboard is written where the cursor currently is in the nu shell.

**Configuration (please complete the following information):**
 - OS: Windows 10
 - Version 1909 (Build 18363.592)

Both `Shift+Insert` and `Ctrl+V` work in other shell on Windows. Both in the default shell window and the new Windows Terminal. But for nu, it seems that the only way to paste is using the right-mouse-button.

**Comment by jonathandturner** [comment]
We'll need to figure out cmd. I'm not sure why paste doesn't work quite right there.

For Windows Terminal, you can use `Ctrl+Shift+V`.

**Comment by tmr232** [comment]
Thanks!

**Comment by jonathandturner** [comment]
Looking back at this, I think we're in line with other apps running inside of cmd or Windows Terminal.  Closing, but we can open new items as we extend into other environments (like jupyter) to ensure the key commands works well.
