### ISSUE TITLE
`\'` is not working for single-quoted strings

### ISSUE THREAD

**Issue by klesh** [nushell/nushell#12343]
### Describe the bug

It is a bit confusing.

In the [Double-quoted Strings](https://www.nushell.sh/book/working_with_strings.html#double-quoted-strings) there is an escape for the single-quote character which is weird and l believed it should belong to the [Single-quoted String](https://www.nushell.sh/book/working_with_strings.html#single-quoted-strings)
<img width="656" alt="2024-03-31_20-48" src="https://github.com/nushell/nushell/assets/61080/c1bc73fe-7f64-4550-8281-2e7b553995a4">

However, I tried and confirmed that the document is correct the escape does work for Double-quoted strings.

<img width="212" alt="2024-03-31_20-46" src="https://github.com/nushell/nushell/assets/61080/bcee2db6-362b-48e1-8a43-e2a6d9033fc9">

### How to reproduce

1. launch nu v0.91
2. type `'a\'b'` and the repr is expecting an ending single quote
3. type `"a\'b"` would get a string `a'b`

### Expected behavior

1. type `'a\'b'` should end up with a string `a'b'
2. type `"a\'b"` should end up with a string `a\'b`

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.91.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 3016d7a64ccb2c2eac9f735f6144fc896ea724a5                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (Arch Linux rust 1:1.76.0-2) |
| cargo_version      | cargo 1.76.0                                                     |
| build_time         | 2024-03-17 13:45:33 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment]
double quotes should interpret escapes. single quotes should not interpret escapes.

**Comment by klesh** [comment]
Certainly, it's a straightforward guideline to adhere to.

I completely concur that while "double quotes should interpret escapes", but it doesn't mean that the single quote should be escaped because it can be safely put inside a double quoted string so no point to escape the character in my opinion.

I would agree the "single quotes should not interpret escapes" if followed by "except for the single quote itself", or it won't be possible to represent a single-quote inside a single quoted string.

My main objective is to find a way to safely convert a string variable to a string literal for a dynamically generated script https://github.com/nushell/nushell/pull/12344/files#diff-55c297ad2f01a5a4bd616f2a250d1c79750801c0a5ae2de5cd1f861d8599872eR44 , It appears to me that a single quoted string would be more appropriate since it won't be interpreted as escaped. What would you suggest? Thanks.

**Comment by weirdan** [comment]
> What would you suggest? 

There's now another type of string available in nu: raw strings. See https://www.nushell.sh/book/working_with_strings.html#raw-strings
