### ISSUE TITLE
How to make esc exit the nushell window

### ISSUE THREAD

**Issue by 107295472** [nushell/nushell#12356]
### Question

Press esc key to exit the window

**Comment by 107295472** [comment]
What you're talking about won't work.

**Comment by 107295472** [comment]
In fact, nushell executes exit and closes the window.

**Comment by fdncred** [comment]
Isn't that what you asked for with `Press esc key to exit the window`?

**Comment by 107295472** [comment]
> I haven't ever seen that requested.
> 
> You can play around with a keybinding to see if you can figure something out. I'd start with this one that I use to clear the buffer.
> 
> ```
>   {
>     name: clear
>     modifier: none
>     keycode: esc
>     mode: [emacs vi_normal vi_insert]
>     event: { edit: clear }
>   }
> ```
> 
> Then maybe change it to an executehostcommand with exit and see if it works.

Where is this written?

**Comment by fdncred** [comment]
keybindings are found in the config.nu

**Comment by 107295472** [comment]
OK, thanks
