### ISSUE TITLE
Nushell doesn't seem to clean up alt terminal modes on Windows

### ISSUE THREAD

**Issue by devyn** [nushell/nushell#12355]
### Describe the bug

Forgive me for lack of specifics, I'm still a little bit iffy on the details on how this all works on Windows, but I was able to reproduce something that [a few people reported on Discord](https://discord.com/channels/601130461678272522/601130461678272524/1224420186262601831) on current `main`.

It seems like when running some processes that use the console API to do more advanced things, like VITE, they might not clean up after themselves before returning to Nushell. This causes Nushell to gain back control but not be able to handle any special keypresses - just characters.

If there's someone on the team with more of an idea of what might be happening here, I'll hand it off - I just wanted to confirm that it is reproducible.

### How to reproduce

1. Install nushell and bun
2. Get a VITE app like https://github.com/supershaneski/bun-sample-app
3. `bun install`
4. `bun run dev`
5. Hit ctrl+C
6. `bun` exits, but Nushell can only accept character input.

### Expected behavior

The terminal should go back to normal and nushell should be able to handle input as it always does.

To be clear - VITE or a project it depends on is very likely doing something wrong here also, but I think Nushell should clean this up if PowerShell and others do, and it seems that they do.

It only happens on Windows. Linux confirmed to be fine, and I expect macOS too.

### Screenshots

![Screenshot_win11_2024-04-01_15:07:05](https://github.com/nushell/nushell/assets/10729/6cc39a57-62a2-49ad-9cce-2727dc0c16bc)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.91.1                                   |
| branch             | main                                     |
| commit_hash        | aaefc5e11074b99d1247218115370ae9b4100fc3 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21)      |
| rust_channel       | 1.75.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.75.0 (1d8b05cdd 2023-11-20)      |
| build_time         | 2024-04-01 14:38:36 -07:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which            |
| installed_plugins  | gstat, inc, query                        |

**Comment by IanManske** [comment]
One thing that we don't do, but probably should, is to restore the previous [terminal attributes](https://linux.die.net/man/3/tcgetattr) once the foreground process group finishes. I assume this in a similar vein? I'm just unfamiliar with what the Windows equivalent is.

**Comment by devyn** [comment]
Yeah, I suspect it's something like that

**Comment by sholderbach** [comment]
When reedline yields back from its reading to nushell we use `crossterm::terminal::disable_raw_mode` that should reset those attributes via [`tcsetattr` on unix](https://docs.rs/crossterm/0.27.0/src/crossterm/terminal/sys/unix.rs.html#92-108) and does the [following for windows](https://docs.rs/crossterm/0.27.0/x86_64-pc-windows-msvc/src/crossterm/terminal/sys/windows.rs.html#43-53)

**Comment by fdncred** [comment]
My advice would be to try a repro in reedline alone. My guess was like stefan's where either crossterm is doing something wrong, or we're doing something wrong by not calling the appropriate crossterm funciton. You'd have to tweak one of the examples to actually launch something but it may not be too tricky.

**Comment by IanManske** [comment]
I think `reedline`/`crossterm` records the state it sees at the start of `read_line` and restores the terminal to that. Rather, I think the external command is changing the terminal between calls to `read_line`.

**Comment by steelywing** [comment]
It can be reproduced just press the <kbd>Ctrl+C</kbd> when `bun` running

Reproduce:

- run `bun -e "while (true) {}"`
- Ctrl-C

**Comment by devyn** [comment]
That's interesting, I wonder if `bun` just always puts the terminal in a different mode for compatibility or something like that

**Comment by danlikestocode** [comment]
Having this exact same issue! Has anyone found any workarounds?

**Comment by devyn** [comment]
No, but avvo [on Discord](https://discord.com/channels/601130461678272522/614593951969574961/1225191620299849879) found that this is probably connected to Bun's new 1.1 release, where they tried to solve a "Terminate batch job? (Y/N)" prompt at the end in PowerShell. Whatever they're doing is probably causing this.

We're closer to figuring it out.

**Comment by danlikestocode** [comment]
> No, but avvo [on Discord](https://discord.com/channels/601130461678272522/614593951969574961/1225191620299849879) found that this is probably connected to Bun's new 1.1 release, where they tried to solve a "Terminate batch job? (Y/N)" prompt at the end in PowerShell. Whatever they're doing is probably causing this.
> 
> 
> 
> We're closer to figuring it out.

Seems like this was fixed upstream on 1.1.3, can anyone else confirm this?

**Comment by steelywing** [comment]
> Seems like this was fixed upstream on 1.1.3, can anyone else confirm this?

Bun 1.1.3 fixed this issue

**Comment by fdncred** [comment]
Should we close this now?

**Comment by devyn** [comment]
Yeah, I think we're still doing something different but unless someone else reports something else like this in the future, it's probably not really our fault.
