### ISSUE TITLE
Error in `complete` exit_code field instead of numerical exit code

### ISSUE THREAD

**Issue by 132ikl** [nushell/nushell#12369]
### Describe the bug

When running with an external command which exits with, eg., a SIGABRT,  `complete` contains an internal error:

```
$ ./a.out | complete
SIGABRT: child process './a.out' core dumped
╭───────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ stdout    │                                                                                                                    │
│ stderr    │                                                                                                                    │
│ exit_code │ ExternalCommand { label: "core dumped", help: "SIGABRT: child process './a.out' core dumped", span: Span { start:  │
│           │ 141774, end: 141781 } }                                                                                            │
╰───────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### How to reproduce

1. Run a program which throws a SIGABRT (may happen for other errors as well?)
```c
#include <signal.h>

int main() {
    raise(SIGABRT);
}
```
2. Run the executable and pipeline into complete, eg. `./a.out | complete`

### Expected behavior

To provide a numerical exit code

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.92.0                                   |
| branch             | makepkg                                  |
| commit_hash        | c3428b891a6ca733fd976971d2f440b5f41cd082 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.75.0 (1d8b05cdd 2023-11-20)      |
| build_time         | 2024-04-02 18:50:27 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | dataframe, default, sqlite, trash, which |
| installed_plugins  | clipboard                                |

**Comment by sholderbach** [comment]
That is caused by this recent addtion in #12315

after that a `Value::Error` was sent down the exit_code channel instead of a `Value::Int` with the bare POSIX value

https://github.com/nushell/nushell/blob/c3428b891a6ca733fd976971d2f440b5f41cd082/crates/nu-command/src/system/run_external.rs#L562-L570
