### ISSUE TITLE
0.92 breaks hook with code (0.91 is fine)

### ISSUE THREAD

**Issue by FrancescElies** [nushell/nushell#12382]
### Describe the bug

Given the following hook that activates a python venv.

```nu
# config.nu 
# hooks
        env_change: {
            PWD: [
                {
                    condition: {|before, after| ($after | path join ".venv/Scripts/activate.nu" | path exists) }
                    code: 'overlay use .venv/Scripts/activate.nu'

                }
            ]
        }

```

The hook works fine in nu 0.91

Running `overlay use venv/bin/activate.nu` directly on the console works fine in 0.91 and 0.92, it's just the hook above doesn't seem to activate the venv on 0.92.

I went through the [release notes](blog/2024-04-02-nushell_0_92_0.html) but didn't see anything that might affect such a hook, I saw some stuff related to how parenthesis work "_parentheses no longer collect external command output and are now solely for grouping and precedence_", maybe I need to update my hook?

If there is a better way to write such a hook I am also happy to change my settings.

### How to reproduce

get nu 0.92 add the hook above and see that the venv doesn't get activated afer cd into a folder with a venv

**Reprex**: 
```nu
# 1 create a venv in a folder
# I use uv, but the same should be valid for virtualenv
mkdir nushell-issue-venv-activate
cd nushell-issue-venv-activate
uv venv
cd ..

# 2 test the hook
cd nushell-issue-venv-activate
(version).version
(which python).path
```

```
# with nu 0.92
~\src\oss> cd nushell-issue-venv-activate
~\src\oss\nushell-issue-venv-activate> (version).version
0.92.0
~\src\oss\nushell-issue-venv-activate> (which python).path
╭───┬─────────────────────────╮
│ 0 │ C:\Python311\python.exe │
╰───┴─────────────────────────╯
```

```
# with nu 0.91
~\src\oss> cd nushell-issue-venv-activate
(nushell-issue-venv-activate) ~\src\oss\nushell-issue-venv-activate> (version).version
0.91.0
(nushell-issue-venv-activate) ~\src\oss\nushell-issue-venv-activate> (which python).path
╭───┬─────────────────────────────────────────────────────────────────────────────────────╮
│ 0 │ C:\Users\FrancescElies\src\oss\nushell-issue-venv-activate\.venv\Scripts\python.exe │
╰───┴─────────────────────────────────────────────────────────────────────────────────────╯
```

### Expected behavior

works for 0.92 as in 0.91

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.92.0                                   |
| branch             |                                          |
| commit_hash        | c3428b891a6ca733fd976971d2f440b5f41cd082 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21)      |
| rust_channel       | 1.75.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.75.0 (1d8b05cdd 2023-11-20)      |
| build_time         | 2024-04-02 18:05:08 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which            |
| installed_plugins  |                                          |

**Comment by kubouch** [comment]
Can you be more specific about “doesn't work”? Does it show some error? Can you also create a minimal reproducible example?

**Comment by FrancescElies** [comment]
> Can you be more specific about “doesn't work”? 

Sure sorry for that and thanks for your reply.

It seems `overlay use venv/bin/activate.nu` doesn't have any effect, I am sure it gets executed though.

I updated the issue description too.

> Does it show some error? 

No errors, just venv is not active.
Running `overlay list` just shows the zero layer.

> Can you also create a minimal reproducible example?

I think so, I'll come back with that

**Comment by fdncred** [comment]
@FrancescElies would you be able to test #12383 to see if it fixes your issue?

**Comment by FrancescElies** [comment]
Done, it does fix the issue.
