### ISSUE TITLE
How do I save a list of numbers as a raw binary file?

### ISSUE THREAD

**Issue by ultrapoci** [nushell/nushell#12398]
### Question

I'm working with raw bytes, and I would like to write a nushell function that takes a number N and outputs a .bin file containing exactly N random bytes.  I've noticed that this piece of code works for a single number:
```
12 | into binary -c | save test.bin -r -f
```
This creates a file named `test.bin` containing only the single byte `0x0c`. The problem is that I cannot generalize it to a list of numbers. In fact, if I do this:
```
[12] | each { || into binary -c } | save test.bin -r -f
```

This creates a file named `test.bin` which contains the bytes `0x0c` and `0x0a`. Basically, when passing a list to `into binary -c`, white spaces are added in between each integer of the list. For example:
```
[12, 13, 14, 15] | each { || into binary -c } | save test.bin -r -f
```

this code creates a file containing the bytes `0c 0a 0d 0a  0e 0a 0f 0a`.

Am I doing something wrong? Is this the expected behavior? I've just started using nushell so I may be doing something wrong.

### Additional context and details

I'm inspecting the binary file using `open --raw test.bin | into binary`.

**Comment by spitfire94** [comment]
`12..15 | each {|| into binary -c | save --raw --append test.bin } | ignore` gets me `0c 0d 0e 0f`

**Comment by fdncred** [comment]
You should also look into the `bytes` commands.

**Comment by devyn** [comment]
> `12..15 | each {|| into binary -c | save --raw --append test.bin } | ignore` gets me `0c 0d 0e 0f`

This is likely to be slow since the file has to be opened for each byte. I would try this

```nushell
1..1024 |
  each { random int ..255 } |
  into binary -c |
  bytes collect |
  save test.bin
```

(added the random int part to reflect the question)

**Comment by ultrapoci** [comment]
> > `12..15 | each {|| into binary -c | save --raw --append test.bin } | ignore` gets me `0c 0d 0e 0f`
> 
> This is likely to be slow since the file has to be opened for each byte. I would try this
> 
> ```nushell
> 1..1024 |
>   each { random int ..255 } |
>   into binary -c |
>   bytes collect |
>   save test.bin
> ```
> 
> (added the random int part to reflect the question)
> 
> Even faster would probably be to gen 64 bits at a time (without -c, and unconstrained range) but then you need to calc the size you want

Thank you, this works perfectly. I wonder why my original method caused whitespaces to be generated.

**Comment by devyn** [comment]
> Thank you, this works perfectly. I wonder why my original method caused whitespaces to be generated.

It's just because when you save a list to a file, nushell assumes you want lines. Doing things like `^command | lines | where $it =~ pattern | save out.txt` is super common, so it kind of makes sense for that to be the default.

I think the docs for `--raw` are maybe a little misleading, all it actually does is prevent format conversion - normally when you write to e.g. `foo.json`, it automatically converts to JSON for you, but `--raw` prevents that. It's the same as `open --raw`.

The right command to take a list of `binary` and concatenate it to one `binary` is `bytes collect`.

**Comment by ultrapoci** [comment]
I understand, thank you very much.
