### ISSUE TITLE
Existing column not found in `where` clause

### ISSUE THREAD

**Issue by brizzbuzz** [nushell/nushell#12399]
### Describe the bug

Hey... I have a horrible feeling that I'm doing something incredibly dumb, but for the life of me, I can't figure out what I could be doing wrong here.  I have a simple table (result of calling the 1password cli to get an item`).  I am then trying to filter an array based on a key of the item in the array..  This seems to work totally as expected for all columns except for 1 :exploding_head: 

![nushell-bug-04-03-24](https://github.com/nushell/nushell/assets/5607577/03d9247a-9960-4f17-8e48-e4d0616279c1)

As you can see from the screenshot, I have a simple table `fields` which I can filter via `where` for an expression such as `$fields | where label == "username"`.  Yet, when I try to do the exact same on the column `purpose` (which you can see above _does_ exist), I get an error complaining about the column not existing.  

### How to reproduce

Example json

```json
"fields": [
    {
      "id": "username",
      "type": "STRING",
      "purpose": "USERNAME",
      "label": "username",
      "value": "redacted",
      "reference": "redacted"
    },
    {
      "id": "password",
      "type": "CONCEALED",
      "purpose": "PASSWORD",
      "label": "password",
      "value": "super redacted",
      "reference": "redacted",
      "password_details": {
        "strength": "FANTASTIC"
      }
    },
    {
      "id": "notesPlain",
      "type": "STRING",
      "purpose": "NOTES",
      "label": "notesPlain",
      "value": "redacted",
      "reference": "redacted"
    },
    {
      "id": "redacted",
      "section": {
        "id": "redacted"
      },
      "type": "OTP",
      "label": "one-time password",
      "value": "redacted",
      "totp": "756607",
      "reference": "redacted"
    }
  ],

```

Store this into a variable, and then try to run the `where` expressions above

### Expected behavior

Columns that exist should... exist :)

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.91.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (built from a source tarball) |
| cargo_version      | cargo 1.76.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by brizzbuzz** [comment]
Ah! Ok... could it be that nushell doesn't handle null values? B/c inspecting the final field (totp), that row does not contain a key named purpose... so maybe I need a way to set a default value? going to try that now :) if so, maybe a more clear debug message or a way to enable null to not break the condition would be nice

**Comment by fdncred** [comment]
You can use `?` to make the field optional like this.
```nushell
 open test.json | where purpose? == NOTES
╭─#─┬─────id─────┬──type──┬purpose┬───label────┬──value───┬reference─╮
│ 0 │ notesPlain │ STRING │ NOTES │ notesPlain │ redacted │ redacted │
╰───┴────────────┴────────┴───────┴────────────┴──────────┴──────────╯
```

**Comment by brizzbuzz** [comment]
ah great :)
