### ISSUE TITLE
Shorthand flags

### ISSUE THREAD

**Issue by Amanita-muscaria** [nushell/nushell#1240]
**Is your feature request related to a problem? Please describe.**
No, just the ergonomics of shortened flags

**Describe the solution you'd like**
Instead of having to type `--help` or `--full`, it would be much more convenient to just use `-h` or `-f` respectively. Outside of convenience, this would mimic previous shells allowing easier/faster adoption by new users and also make it easy to port commands as plugins if a user desired.
Additionally, the flags should be able to be contracted together so instead of having to type `cmd -<a> -<b> -<c>` one could enter `<cmd> -<abc>` providing yet more ergonomics and further mimicking existing shells.

**Describe alternatives you've considered**
The only other option I know of would be to leave it as it is with just long-form flags.

**Comment by coolshaurya** [comment]
I think this was fixed by #1378

**Comment by Amanita-muscaria** [comment]
Not entirely. 1378 was just the initial support. I still need to put in the ability to use compound flags.

**Comment by jonathandturner** [comment]
This is working now
