### ISSUE TITLE
How to pipe binary output from one process as input to another? (All arguments to an external command need to be string-compatible)

### ISSUE THREAD

**Issue by DavidTelenko** [nushell/nushell#12404]
### Question

Here is a bash equivalent of a task I want to accomplish.
```bash
some_process < my/binary_file.bin
```
In nushell apparently there is no process substitution but I can run commands in `()` curly braces to pipe it's result to stdin of other command. However it doesn't seem to accept binary input.
```nushell
some_process (open -r my/binary_file.bin)
```
It results with an error
```
  × External command failed
   ╭─[entry #1:1:24]
 1 │ some_process (open -r my/binary_file.bin)
   ·                        ────────────┬───
   ·                                    ╰── Cannot convert binary to a string
   ╰────
  help: All arguments to an external command need to be string-compatible
```

**Comment by WindSoilder** [comment]
Maybe you can just use a pipeline?
```
open -r my/binary_file.bi | some_process
```

**Comment by crides** [comment]
Given
```bash
some_process < my/binary_file.bin
```

```nu
some_process (open -r my/binary_file.bin)
```
is not semantically equivalent. The former is passing thru stdin, the latter is passing as an argument. What WindSoilder said is the only equivalent form

**Comment by DavidTelenko** [comment]
The thing is I need to be able to pass read binary file not as only parameter to process. Here's the example:
```bash
some_process param1 < my/binary_file.bin
```
This time in nushell there is no way to do this in a simple pipeline and either I need to pass it in `()` as a parameter or use xargs equivalent in pipeline (`$in` parameter)
```nushell
some_process param1 (open -r my/binary_file.bin)
```
or 
```nushell
(open -r my/binary_file.bin) | some_process param1 $in
```
I'm sorry for confusion but I'm particularly new to both bash and nushell scripting.

**Comment by crides** [comment]
```nushell
open -r my/binary_file.bin | some_process param1
```
is fine. stdin and arguments are separate entities (in nushell or POSIX shells like bash)

**Comment by DavidTelenko** [comment]
@crides Oh, ok I didn't know that, thank you, my issue seem to be resolved)
