### ISSUE TITLE
`ls` doesn't list directories with parentheses

### ISSUE THREAD

**Issue by crides** [nushell/nushell#12407]
### Describe the bug

As title. _Files_ with parentheses are fine

### How to reproduce

1. `mkdir "(a)"`
2. `ls "(a)"`

### Expected behavior

list the directory

### Screenshots

![maim-2024 04 05 00 53 54](https://github.com/nushell/nushell/assets/15631555/770beba8-f883-4df9-9bff-2609dd20fccc)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.92.1                                   |
| branch             | dev                                      |
| commit_hash        | 5daac4af50ffa5f154b6b993e01adbcbb82b0cd9 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21)      |
| rust_channel       | 1.75.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.75.0 (1d8b05cdd 2023-11-20)      |
| build_time         | 2024-04-05 00:31:56 -07:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which            |
| installed_plugins  | audio_hook                               |

**Comment by merelymyself** [comment]
This is expected behaviour - `ls <directory>` lists the files inside the directory. (At present it would be empty.)

**Comment by crides** [comment]
Yep welp I totally forgot about that. Time to sleep
