### ISSUE TITLE
Error: nu::shell::xdg_config_home_invalid

### ISSUE THREAD

**Issue by kuchta** [nushell/nushell#12416]
### Describe the bug

On MacOS Sonoma I now get Error: nu::shell::xdg_config_home_invalid even though $env.XDG_CONFIG_HOME point to absolute path containing non-empty nushell dir.

```
Error: nu::shell::xdg_config_home_invalid

  × $env.XDG_CONFIG_HOME (/Users/kuchta/.config) is invalid, using default config directory instead: /Users/
  │ kuchta/.configs/.config/nushell
  help: Set XDG_CONFIG_HOME to an absolute path, or set it to an empty string to ignore it

/Users/kuchta: ls $"($env.XDG_CONFIG_HOME)/nushell"                                               04/05/2024 09:05:14 PM
╭───┬────────────────────────────────────────────────┬──────┬──────────┬────────────────╮
│ # │                      name                      │ type │   size   │    modified    │
├───┼────────────────────────────────────────────────┼──────┼──────────┼────────────────┤
│ 0 │ /Users/kuchta/.config/nushell/carapace.nu      │ file │    620 B │ 4 months ago   │
│ 1 │ /Users/kuchta/.config/nushell/completions.nu   │ file │   4.4 KB │ 2 years ago    │
│ 2 │ /Users/kuchta/.config/nushell/config.nu        │ file │   3.8 KB │ 2 hours ago    │
│ 3 │ /Users/kuchta/.config/nushell/default-theme.nu │ file │   1.4 KB │ 2 years ago    │
│ 4 │ /Users/kuchta/.config/nushell/env.nu           │ file │   2.7 KB │ 2 hours ago    │
│ 5 │ /Users/kuchta/.config/nushell/history.txt      │ file │ 147.3 KB │ 16 seconds ago │
╰───┴────────────────────────────────────────────────┴──────┴──────────┴────────────────╯
/Users/kuchta:                                                                                    04/05/2024 09:05:14 PM
```

### How to reproduce

set XDG_CONFIG_HOME on MacOS

### Expected behavior

No error

### Configuration

| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.92.1                                         |
| branch             |                                                |
| commit_hash        |                                                |
| build_os           | macos-aarch64                                  |
| build_target       | aarch64-apple-darwin                           |
| rust_version       | rustc 1.77.1 (7cf61ebde 2024-03-27) (Homebrew) |
| cargo_version      | cargo 1.77.1                                   |
| build_time         | 2024-04-04 14:18:54 +00:00                     |
| build_rust_channel | release                                        |
| allocator          | mimalloc                                       |
| features           | dataframe, default, sqlite, trash, which       |
| installed_plugins  |                                                |

**Comment by kuchta** [comment]
@ysthakur Yes, XDG_CONFIG_HOME is pointing to ~/.config which is a symlink to ~/.configs/.config. It's also strange that it says `using default config directory instead: /Users/kuchta/.configs/.config/nushell`, since the default had always been ~/Library/Application Support/nushell on macOS. So it's probably using the right one except for the error message...

**Comment by ysthakur** [comment]
Well, the old behavior on MacOS was this: does HOME exist? If so, use HOME/.config. Otherwise, use Library/Application Support. So maybe you've set HOME to /Users/kuchta/.configs? Regardless, the symlink should be resolved. I think I see how it can be fixed, give me a day to make the changes. Sorry about the error.

**Comment by kuchta** [comment]
I've never explicitly set HOME anywhere in my shell, so it's either comming from parent environment (system) or it's being set by the shell (nushell in this case) itself and it's set to `/Users/kuchta`.

Thank you @ysthakur ❤️

**Comment by ysthakur** [comment]
You're right, it was indeed using the `XDG_CONFIG_HOME` you set, just reporting an error before that.
