### ISSUE TITLE
`extern` completions for single-dash long options

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#12414]
### Related problem

Some Java CLI utilities (and I presume others, too) only support single dash long options: `plantuml -help` works, whereas `plantuml --help` doesn't.

### Describe the solution you'd like

Add a flag to `extern`, which either:

- Converts double-dashed options into single-dashed, when passing them to the underlying command
- Allows passing single-dashed long options.

**Comment by sholderbach** [comment]
Duplicate of #5959
