### ISSUE TITLE
`mut` variables don't update in v0.92

### ISSUE THREAD

**Issue by arnau** [nushell/nushell#12423]
### Describe the bug

Since updating to 0.92 `mut` variables don't change on update. Works fine in 0.91

### How to reproduce

Two examples after starting an interactive shell:

```nu
> mut x = 1
> $x = 2
> $x
1
>
> mut r = {a: 1, b: "abc"}
> $r.a = 2
> $r.c = "xxx"
> $r
{a: 1, b: "abc"}
```

### Expected behavior

I expect nu 0.92 to update `mut` values on update (upsert). Based on the two examples above I would expect:

- `$x == 2`
- `$r == {a: 2, b: "abc", c: "xxx"}`

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.92.1                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | macos-aarch64                       |
| build_target       | aarch64-apple-darwin                |
| rust_version       | rustc 1.77.1 (7cf61ebde 2024-03-27) |
| rust_channel       | stable-aarch64-apple-darwin         |
| cargo_version      | cargo 1.77.1 (e52e36006 2024-03-26) |
| build_time         | 2024-04-04 21:28:51 +01:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash, which       |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
Good catch. Thanks for the report.
1. I wonder how that happened.
2. I wonder why we don't have `mut` tests and if we do, how are they passing?

**Comment by devyn** [comment]
It's possible that it can only happen in the REPL due to the state merge

**Comment by devyn** [comment]
![Screenshot_20240406-063558.png](https://github.com/nushell/nushell/assets/10729/ecd70278-bbd9-4b45-a17e-895badf63b98)

Yeah, something is not happening right with merging the Stack back in

**Comment by fdncred** [comment]
Ian's already got a fix for it, yay!
