### ISSUE TITLE
Compute total size of all files/folders in directory rather than just directory's size

### ISSUE THREAD

**Issue by Amanita-muscaria** [nushell/nushell#1242]
**Is your feature request related to a problem? Please describe.**
Nope, just a feature

**Describe the solution you'd like**
When `ls` is given a specific flag, compute the total directory size. When the flag is not set, show the dash as it does currently

**Describe alternatives you've considered**
Just not doing this

**Comment by thegedge** [comment]
One question I'd like to first ask: would it make more sense for us to build a `du` alternative instead of baking this into `ls`? More generally, should we take the UNIX philosophy with our tools and try to keep their complexity down by making them do one thing well?
