### ISSUE TITLE
When double-clicking for selection, it selects AM/PM part from the previous line

### ISSUE THREAD

**Issue by jerrygreen** [nushell/nushell#12425]
### Describe the bug

I'm using VSCode integrated terminal. I'm not sure entirely if it's VSCode or nushell, but it's very annoying.

### How to reproduce

1. run `nu --version` for example, or anything really
2. copy-paste output (right click)
3. see this annoying "AM/PM" part being copied...

### Expected behavior

Copied output should not include text from rows above. Only the row being clicked should be selected.

### Screenshots

![gif1](https://github.com/nushell/nushell/assets/13215662/5fd0f57c-0de4-4660-94cf-14ea096c037c)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.92.1                                   |
| branch             |                                          |
| commit_hash        | c00a05a7625275811a3795abc1e903f4e820adf8 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21)      |
| rust_channel       | 1.75.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.75.0 (1d8b05cdd 2023-11-20)      |
| build_time         | 2024-04-04 14:25:58 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | dataframe, default, sqlite, trash, which |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
Weird. I don't have any issues.
![image](https://github.com/nushell/nushell/assets/343840/7c401519-2aaf-4231-bad2-4dcf32c623e5)

I wonder if it's related to the prompt or with vscode's shell?

**Comment by fdncred** [comment]
I don't have problems in vscode either with manual selection or double clicking to create the selection.
![image](https://github.com/nushell/nushell/assets/343840/890f5fea-6773-4932-a57c-653224f339cb)

**Comment by jerrygreen** [comment]
With manual selection I don't have issues either. It happens only when double-clicking to automatically select a range of characters.

It seems your terminal has some noticeable space in the end of each row. It doesn't seem the same on Windows. Might be related. Look, after AM/PM characters I don't any space at all:

![image](https://github.com/nushell/nushell/assets/13215662/3aa78a4d-3379-4450-8807-a714f3b87555)

It seems the program perceiving all of this as one single row, therefore selection previous part as one single word.

On your screenshot, it seems like there's some padding with one space or something, preventing from this.

I'm not sure if it's Windows, VSCode, or maybe some of your plugins fixing the issue. I don't have any plugins enabled.

**Comment by fdncred** [comment]
Could be Windows. My tests were on Macos.

**Comment by jerrygreen** [comment]
I agree, macOS doesn't have this issue. Windows-only it seems.
Not sure if it's something to LF/CLRF symbols, or what.

**Comment by fdncred** [comment]
Nushell won't control how a double click selects text anyway. So, this may be a vscode issue that you want to search for on their repo.

**Comment by jerrygreen** [comment]
Just notified them about this issue too:

- https://github.com/microsoft/vscode/issues/209782

This issue might be closed then I guess, as unrelated to `nu`.
Thanks for checking with your screenshots
