### ISSUE TITLE
When invoked from env.nu script only last echo instance is printed on console

### ISSUE THREAD

**Issue by DoumanAsh** [nushell/nushell#12421]
### Describe the bug

It is unclear if it is intended, but I used `echo` to print useful information from my env.nu file

With 0.92.1 only last `echo` instance is shown on console

My env.nu https://github.com/DoumanAsh/collectionScripts/blob/6b36b5fa476b36066718c332200cbb8eac5843d5/nushell/env.nu

### How to reproduce

1. Create `env.nu` with multiple `echo` invocations
2. Run shell with it

### Expected behavior

This looks like a regression since previous versions(probably before 0.92) didn't have such issue
All `echo` instances would be printed on console

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.92.1                                   |
| branch             |                                          |
| commit_hash        | c00a05a7625275811a3795abc1e903f4e820adf8 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.75.0 (82e1608df 2023-12-21)      |
| rust_channel       | 1.75.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.75.0 (1d8b05cdd 2023-11-20)      |
| build_time         | 2024-04-04 14:25:58 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | dataframe, default, sqlite, trash, which |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I thought this was the way it's supposed to work. The last item will get echoed. If you want everything, you use the `print` command. I think it's the same with a custom command, only the last echo would be output.

**Comment by DoumanAsh** [comment]
Oh, ok. I thought something is wrong since behavior changed from previous version
If not then nevermind it

**Comment by svallory** [comment]
It would be nice to add a warning about this in the docs. (maybe [here](https://www.nushell.sh/book/stdout_stderr_exit_codes.html#echo-print-and-log-commands)?)

It took me quite a while to figure out :/

**Comment by fdncred** [comment]
Probably a good idea. People trip on this sometimes.
