### ISSUE TITLE
Usability studies before 1.0

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1243]
**Is your feature request related to a problem? Please describe.**
As Nushell continues to grow, we'd like to perform some usability studies on it to see what concepts are difficult for people who don't traditionally use the shell heavily. This will help polish an rough edges of the user experience going 1.0.

**Describe the solution you'd like**
We'll need to discuss what the best options are here to reach out. We may want to build a web-based experience and have people try it out and then fill out a quick survey at the end.

**Describe alternatives you've considered**
There are also ways to pay for usability testing. That's a possibility as well.

**Open questions**
- Should rows be 0-based or 1-based?

**Comment by pwnorbitals** [comment]
This can also be organized at conferences / IRL meetings when possible, let the testing users try and feedback in-person. surveys and forms are inherently biased, and organizing user reachout campaigns on social networks and IRL might we a good way to avoid it, as long as we can transform the feedback into useful data afterwards.
