### ISSUE TITLE
Inconsistent command definition vs call syntax

### ISSUE THREAD

**Issue by kuchta** [nushell/nushell#12430]
### Related problem

Current command definition syntax with arguments in brackets is not consistent with it's calling syntax
```
def hello [ first: string, last: string ] { echo $"hello ($first) ($last)" } 
```
vs
```
hello John Doe
```

### Describe the solution you'd like

Regarding that shell doesn't use any separators for calling commands with arguments and that syntax is so engrained, the only possilbe solution to make command definition and calling consitent is to change command definition syntax:

```
def hello first: string last: string { echo $"hello ($first) ($last)" }
```

**Comment by kubouch** [comment]
We don't plan to change the come definition syntax. Removing the braces would make it harder to read.

**Comment by kuchta** [comment]
@kubouch I don't think that adding noise (apart from starting definition keyword which makes it clear that this is a definition) makes things easier to read, actually quite the contrary, but for people used to that syntax it can be subjectively harder to read. It depends if you prefer subjective or objective (consistency) point of view...
