### ISSUE TITLE
Typechecking failure

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#12444]
### Describe the bug

Under certain circumstances, `date to-record` type checking fails.  This might be a broader problem with type inference.

### How to reproduce

Script file:

```Nushell
const start_date = 2010-01-01

def round [] {
	format date "%Y-%m-%d" | into datetime | date to-timezone "+0000"
}

export def func [] {
	let today = date now | round
	$start_date - $today | date to-record | print
}
```

Error:

```Nushell
~> use /tmp/error.nu
~> error func 
Error: nu::shell::datetime_parse_error

  × Unable to parse datetime: [Duration {
  │     val: -450133200000000000,
  │     internal_span: Span {
  │         start: 106238,
  │         end: 106258,
  │     },
  │ }].
    ╭─[/tmp/error.nu:9:25]
  8 │     let today = date now | round
  9 │     $start_date - $today | date to-record | print
    ·                            ───────┬──────
    ·                                   ╰── datetime parsing failed
 10 │ }
    ╰────
  help: Examples of supported inputs:
         * "5 pm"
         * "2020/12/4"
         * "2020.12.04 22:10 +2"
         * "2020-04-12 22:10:57 +02:00"
         * "2020-04-12T22:10:57.213231+02:00"
         * "Tue, 1 Jul 2003 10:52:37 +0200"
```

### Expected behavior

I expected a regular type mismatch error.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.92.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.77.0 (aedd173a2 2024-03-17) (Alpine Linux 1.77.0-r0) |
| cargo_version      | cargo 1.77.0                                                 |
| build_time         | 2024-04-03 10:33:03 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which                                |
| installed_plugins  |                                                              |

**Comment by devyn** [comment]
I think this is a consequence of `any` typing the output of `date - date`, since passing something typed as `any` into `date to-record` has the same result but if it's properly typed as `duration` it doesn't. It would be helpful to type that as `duration` unless there's some reason for it to be `any`.

Our type system is gradual and best effort, we are just trying to prevent obvious errors as much as we can but it's not strictly required for correctness - hence the runtime type checks and the existence of the `any` type.

**Comment by KAAtheWiseGit** [comment]
Understood.

In this case, the thing which needs fixing is the erroneous debug printing of the internal value.
