### ISSUE TITLE
macOS: `nu` executable was not found

### ISSUE THREAD

**Issue by jerrygreen** [nushell/nushell#12447]
### Describe the bug

1. I am using macOS Monterey and tried to run `nu -c $nu.env-path`… it fails:
<img width="602" alt="Screenshot 2024-04-07 at 23 50 03" src="https://github.com/nushell/nushell/assets/13215662/1dbe020b-7828-49cb-aec7-d66293120159">

2. On your own website, the language markup is broken btw:
<img width="779" alt="Screenshot 2024-04-07 at 23 50 46" src="https://github.com/nushell/nushell/assets/13215662/0c34c92a-651f-48be-9b3b-9ca927e7ccc1">

3. There's [A LOT of people](https://github.com/nushell/nushell/discussions/5279) begging against this norm:
<img width="527" alt="Screenshot 2024-04-07 at 23 52 56" src="https://github.com/nushell/nushell/assets/13215662/a1763ceb-2990-49e0-8ad2-47d553d81cf0">

So I would like to vote against using "Application Support", but here I only humbly ask to fix this "executable was not found" issue when running `nu` script with arguments.

### How to reproduce

1.  on macOS (not just Monterey?)
2.  run `nu -c $nu.env-path`
3.  see error 

### Expected behavior

`nu` commands should be executed without errors

### Configuration

| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.92.1                                         |
| branch             |                                                |
| commit_hash        |                                                |
| build_os           | macos-x86_64                                   |
| build_target       | x86_64-apple-darwin                            |
| rust_version       | rustc 1.77.1 (7cf61ebde 2024-03-27) (Homebrew) |
| cargo_version      | cargo 1.77.1                                   |
| build_time         | 2024-04-04 14:18:54 +00:00                     |
| build_rust_channel | release                                        |
| allocator          | mimalloc                                       |
| features           | dataframe, default, sqlite, trash, which       |
| installed_plugins  |                                                |

### Additional context

`nu` on Windows works just fine, I see no such error.
Only on macOS.

**Comment by IanManske** [comment]
I think you meant to do `nu $nu.env-path` which will run `$nu.env-path` as a script. The `-c` flag, on the other hand, is used to run a command string like:
```nushell
> nu -c '1 + 1'
2
```

**Comment by fdncred** [comment]
1. Agree with Ian. You're trying to run commands with `nu -c` versus running a script `nu script`. So, this is working as expected.
2. The latest version of nushell support XDG_CONFIG_HOME as is [documented](https://www.nushell.sh/blog/2024-04-02-nushell_0_92_0.html#support-for-xdg-config-home-toc) in our release notes.

**Comment by IanManske** [comment]
In that case, I think you need to pass the command as a string:
```nushell
> nu -c '$nu.env-path'
```

**Comment by ysthakur** [comment]
>  although, I wonder why nu -c $nu.env-path doesn't fail on the other platforms?

I think it's because there's no spaces, so it looks like `nu -c /foo/bar/baz`, which is then interpreted as just a file path (rather than a command call `/Users/foo/Library/Application Support/...`)

**Comment by IanManske** [comment]
But wouldn't it still interpret it as the file path as one for an external command? When I try it locally:
```nushell
> nu -c $nu.env-path
Error: nu::shell::external_command

  × External command failed
   ╭─[source:1:1]
 1 │ /home/iama/.config/nushell/env.nu
   · ────────────────┬────────────────
   ·                 ╰── can't run executable
   ╰────
  help: Permission denied (os error 13)
```

**Comment by fdncred** [comment]
It could be a bug on other platforms. `nu -c $nu.envpath` seems wrong to me.

**Comment by jerrygreen** [comment]
I changed it to `nu -c '$nu.env-path'`, and it helped, thanks.

I supposed it's somewhere deep in the stacktrace inside `nu`.
Shame on me I haven't figured that's the end of the chain where the issue happens. Therefore: me.

In my defense, I don't know what exactly `$nu.env-path` token is doing, I thought it's just some shortcut function to print some text. Turns out, it's actual variable name? I never seen a variable with a dot in it.

**Comment by IanManske** [comment]
Figured it out, I think it's because a different shell is being used on each platform to run `nu -c $nu.env-path`.
On windows, I think it's cmd, which doesn't do anything special to `$nu.env-path`. It just passes it as a string, so the final command run inside nushell is just:
```nushell
$nu.env-path
```

But on macOS, I think nushell is being used as the parent shell? In that case `$nu.env-path` is being evaluated before being passed along, so the inner  nushell tries to run:
```nushell
/Users/foo/Library/Application Support/...
```

**Comment by devyn** [comment]
FYI, you can probably get your config in `~/.config` now by adding the following to `~/.profile`:

```sh
export XDG_CONFIG_HOME="$HOME/.config"
```

This will make all apps that support that spec reliably use the `~/.config` folder, including Nushell.

**Comment by jerrygreen** [comment]
@IanManske on macos, Node's `execSync` isn't evaluating from parent shell.

These are paths in Windows by the way:

```txt
C:\Users\Jerry\AppData\Roaming\nushell\env.nu
C:\Users\Jerry\AppData\Roaming\nushell\config.nu
```

And these are on macos:

```txt
/Users/jerrygreen/Library/Application Support/nushell/env.nu
/Users/jerrygreen/Library/Application Support/nushell/config.nu
```

Spaces in shells were traditionally evil. That's why so many people hate Apple's «Application Support»

But saying that, while being true, is just an over-simplification. For sure, there's so much more involved:

- in node, on macos, `$SHELL` says `/bin/zsh`, but I can't even use `print`, how on earth...
- in node, on windows, it seems to be `cmd.exe`, it doesn't have `print` but `print` works...
- in bash/zsh/fish/cmd, result of `nu -c $nu.env-path` isn't interpreted as command, it seems...
- in nu, on the other hand, result of `nu -c $nu.env-path` is interpreted as command, it seems...
- in bash/zsh/fish/cmd, result of `nu -c $nu.env-path` is interpreted as command if more than one token...
- in nu, any string like for example `$nu.env-path`, isn't interpreted as command if one token... (unlike `nu -c`)
- in nu, `$nu.env-path` seems to be just a variable... is it even a valid variable name in other shells? It's invalid. If you don't know about previous statement, coming from bash and other shells, it looks like some shorthand nu-specific syntax...

So, all of that is really confusing. Barely can tell how the thing even works.

But thanks for help, really. I guess I'll stick to `nu` as my daily shell. It's fast. It has pretty tables, supports md-csv-json-ANYTHING. It's compatible with Zoxide. It's all I need. I hope this shell becomes the standard soon. Like one day Apple did to zsh.
