### ISSUE TITLE
Regression in loop + echo interop

### ISSUE THREAD

**Issue by fennewald** [nushell/nushell#12463]
### Describe the bug

Behavior of `echo` in loop has changed.

In `0.88.2`,
```
loop {
  echo test
  break
}
```
Will print `test` once, and exit succesfully. However, in 0.92.1, this same block will print nothing. It is worth noting that
```
loop {
  ^echo test
  break
}
```
Does still work.

### How to reproduce

Run:
```
loop {
  echo foo
  break
}
```

### Expected behavior

I expected nu to print the message inside the loop.

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.92.1                                      |
| branch             | main                                        |
| commit_hash        | c00a05a7625275811a3795abc1e903f4e820adf8    |
| build_os           | linux-x86_64                                |
| build_target       | x86_64-unknown-linux-gnu                    |
| rust_version       | rustc 1.79.0-nightly (0824b300e 2024-03-24) |
| cargo_version      | cargo 1.79.0-nightly (d438c80c4 2024-03-19) |
| build_time         | 2024-04-04 11:46:26 -04:00                  |
| build_rust_channel | release                                     |
| allocator          | mimalloc                                    |
| features           | default, sqlite, trash, which               |
| installed_plugins  | net                                         |

### Additional context

Even large amounts of text still do not print anything:
```
mut i = 0
loop {
  echo test
  if ($i >= 1000000) {
    break
  }
  $i = ($i + 1)
}
```

**Comment by IanManske** [comment]
This is now intentional behavior. In `0.92`, we [changed](https://www.nushell.sh/blog/2024-04-02-nushell_0_92_0.html#echo-toc) `echo` to not print to stdout. You can use the `print` command to do this instead.

**Comment by fennewald** [comment]
Ahh, my mistake. Sorry for not checking the changelog, and thank you for clarifying.

**Comment by IanManske** [comment]
All good, you're welcome!
