### ISSUE TITLE
Add option to disable deprecation warnings

### ISSUE THREAD

**Issue by noverby** [nushell/nushell#12474]
### Related problem

I'm using home-manager, which generates nushell integration scripts.
The problem is, that many of the scripts often becomes out of date, and I'm not in the position of actually being able to change the scripts generated by home-manager, so they are not helpful. Thus, it would be useful to turn them off, since they break the experience of many tools. E.g. Atuin. 

### Describe the solution you'd like

Just an option in the config file.

**Comment by devyn** [comment]
I think this is reasonable, but we will end up removing deprecated behavior at some point - sometimes even in the next release.

I'm not sure I completely understand why the scripts can't be updated - is the issue what home-manager generates being outdated, or that you can't regenerate them?

**Comment by noverby** [comment]
@devyn It is that the scripts home-manager generates are outdated

**Comment by devyn** [comment]
I think it would be good for users to still be seeing the deprecation warnings so they can pressure projects like home-manager to update their scripts so that users don't end up with something inexplicably broken.

But maybe we can make it quieter by only showing a deprecation warning the first time somehow.

**Comment by noverby** [comment]
> But maybe we can make it quieter by only showing a deprecation warning the first time somehow.
@devyn That would be helpful for Atuin at least, where the warning totally breaks integration.
