### ISSUE TITLE
Tab completion needs better context

### ISSUE THREAD

**Issue by Amanita-muscaria** [nushell/nushell#1248]
**Is your feature request related to a problem? Please describe.**
It's frustrating to `cd` and hit tab but it goes into the built-in nu shell commands

**Describe the solution you'd like**
Have commands tell the shell what the command needs to tab through. e.g. `cd` needs directories, `ls` takes either files or directories, etc.

**Describe alternatives you've considered**
The alternatives I could think of would be leaving it as is or disabling tab completion. Neither sounds great.

**Comment by thegedge** [comment]
We're consolidating the completions effort in #290 for now. After we close off that issue, we can open (or reopen) specific issues related to completions.
