### ISSUE TITLE
Help for `to/from ndjson` points to spam site

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#12482]
### Describe the bug

Unfortunately, the NDJSON site linked in the help has been taken over by a Korean sports gambling website.  I'll provide a PR shortly to update to the spec page on GitHub.

### How to reproduce

```Nushell
use std formats
help to ndjson
```

Click on the link (or not, preferably) and get a website in Korean that, translated, reads something like:

> Sports Toto Recommended Reviews and Usage Strategy Guide
> 
> Sports betting, which provides thrilling betting experiences and generous incentives, continues to attract steady popularity. It offers a great opportunity to double the enjoyment of sports events and matches happening worldwide. You can bet on popular sports such as football, basketball, ice hockey, golf, horse racing, volleyball, cricket, and more.

### Expected behavior

We try not to lead users to spammy sports better websites ;-)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.92.0                                   |
| branch             |                                          |
| commit_hash        |                                          |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.76.0 (c84b36747 2024-01-18)      |
| build_time         | 2024-04-03 12:28:13 -04:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | dataframe, default, sqlite, trash, which |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
lol, thanks. good catch!
