### ISSUE TITLE
`use` doesn't respect NU_LIB_DIRS

### ISSUE THREAD

**Issue by khionu** [nushell/nushell#12489]
### Describe the bug

As on the tin. Using strace and running `use task` doesn't show it trying to access `~/.config/nushell/scripts`, which I haven't overwritten

### How to reproduce

1. Follow the directions in [Background tasks with Nu](https://www.nushell.sh/book/background_task.html).
2. Additionally create a `task/mod.nu` with the same contents
3. Start nu via `strace -o logfile nu`
4. From `~`, run `use task`, `use task.nu`, and `use task/`

### Expected behavior

I would expect strace to see the attempts to resolve `task` from `~/.config/nushell/scripts/`, but there are none.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.92.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (built from a source tarball) |
| cargo_version      | cargo 1.76.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which                                     |
| installed_plugins  |                                                                   |

Note, using NixOS with home-manager, tracking `nixpkgs/nixos-unstable`. I have attempted both letting Nix manage the files as symlinks and copying the files there manually.

### Additional context

[test.log](https://github.com/nushell/nushell/files/14952658/test.log) from me running strace

**Comment by fdncred** [comment]
I use scripts that are in NU_LIB_DIRS every day. Here's a snippet from my config.nu. All the leading folders are off of a folder in my NU_LIB_DIRS.
```nushell
# cargo completions
use "custom-completions/cargo/cargo-completions.nu" *
# use "custom-completions/winget/winget-completions.nu" *

# git/gh completions and aliases
use custom-completions/git/git-completions.nu *
use aliases/git/git-aliases.nu *
use custom-completions/gh/gh-completions.nu *

# broot completions
use '/Users/fdncred/.config/broot/launcher/nushell/br' *

# temperature converter
use "sourced/temp.nu" *
```

**Comment by khionu** [comment]
Well, as you can see in my strace output, it doesn't even try to check for the variable, and I've made sure that it's set immediately before testing.

**Comment by fdncred** [comment]
I know what I'm doing works because I use it every day. What I'm doing is slightly different than what you're doing though. I'm just using one file.

My NU_LIB_DIRS looks like this
```
╭───┬────────────────────────────────────────────────────────────╮
│ 0 │ /Users/fdncred/Library/Application Support/nushell/scripts │
│ 1 │ /Users/fdncred/src/nu_scripts                              │
│ 2 │ /Users/fdncred/Library/Application Support/nushell         │
╰───┴────────────────────────────────────────────────────────────╯
```
and you can see that item 1 is the nu_scripts folder. When I do something like `use "custom-completions/cargo/cargo-completions.nu" *` it's actually resolving it to `use "/Users/fdncred/src/nu_scripts/custom-completions/cargo/cargo-completions.nu" *`. I am not trying to use a folder, so maybe that's the difference?

**Comment by khionu** [comment]
That wouldn't explain why the logs that would show the API call to check for the files isn't seeing any entries for attempts to load the file that include the path in my NU_LIB_DIRS. It's not trying _any_ combination of paths that include it. Additionally, I've set the module as a file and as a `mod.nu` in the module-named folder, then tried three different ways to use it, one folder two not, so that's not it.

**Comment by YizhePKU** [comment]
> Additionally create a task/mod.nu with the same contents

Does it work if there isn't a directory named `task` in the current working directory? The current implementation searches the current directory first and only uses `NU_LIB_DIRS` as a fallback, even in cases where `task/mod.nu` doesn't exist.

**Comment by WindSoilder** [comment]
Hi, I'm looking back the information you provides in discord: https://discord.com/channels/601130461678272522/614593951969574961/1228122676506267748

I think you have alias `ls` to something like `exa`, right?  I think the point is the type of `$env.NU_LIB_DIRS` in your machine is not right, `ls -alhT $env.NU_LIB_DIRS` should failed.

I guess the type of `$env.NU_LIB_DIRS` in your machine is `string`(you can verify by `$env.NU_LIB_DIRS | describe`), but it's expected to be a `list<string>`.

**Comment by khionu** [comment]
This sounds plausible. It's correct that I don't set it myself, and the behaviour you described sounds right. I'll set it manually to be the default as a list, and see if that fixes it
