### ISSUE TITLE
The child 'nu' process in running Nushell is not readable on light background terminal 

### ISSUE THREAD

**Issue by agavrilov** [nushell/nushell#12490]
### Describe the bug

I'm using Windows Terminal with a light background (the light theme called 'One Half Light'). I configured Nushell to use the light theme as described here: https://www.nushell.sh/book/coloring_and_theming.html#working-on-light-background-terminal. 

When I use the table from the prompt, it is shown in correct colors - the dark border and content. 

But if I save the same table as a script file 'test.nu' and then run the script as 'nu test.nu' the output is shown in white colors - completely ineligible on the light background 

### How to reproduce

1. Use light background on the terminal
2. Use this table on the prompt: `[[c1 c2]; [t1 t2]]`
3. Observe the correct output with dark colors
4. Save the table `[[c1 c2]; [t1 t2]]` to **test.nu**
5. Run **nu test.nu**
6. Observer the output is shown in white colors 

### Expected behavior

The output of tables from scripts should be shown in same colors as in the prompt

### Screenshots

![image](https://github.com/nushell/nushell/assets/3209180/44303d56-e7b0-4750-9357-1ca35b76b531)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.92.2                                   |
| branch             |                                          |
| commit_hash        | 2a08a18b26865a86c793d183b9b042220ecb733a |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)      |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)      |
| build_time         | 2024-04-10 21:26:02 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | dataframe, default, sqlite, trash, which |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I think this is because nushell may not load your config when you do `nu script.nu`. It probably loads the default_config.nu file that it has in memory. Someone could do some investigation to confirm.

**Comment by WindSoilder** [comment]
When run `nu script.nu`, nushell won't read config file, and thus you need to pass `--config`.

e.g: `nu --config $nu.config-path script.nu`

I will close the issue for now, feel free to reopen it if you still have a question

**Comment by agavrilov** [comment]
It makes 'nu' command under Nushell unusable. At least the color scheme needs to be inherited from the parent process.
