### ISSUE TITLE
`table` doesn't stream

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1252]
**Describe the bug**
The table command doesn't stream, which means it will hang as it receives all the rows.

**To Reproduce**
1. compare: `ls **` to `ls ** | table`

**Expected behavior**
Table should stream in the same way `autoview` does

**Comment by Amanita-muscaria** [comment]
Is this still the case? I just tried it out on my machine and the two commands respond the same. It also looks like `table()` in table.rs uses an `async_stream!`

**Comment by thegedge** [comment]
+1 also working for me on OSX.

**Comment by jonathandturner** [comment]
Yup, this is fixed by #1283 (among others).  Closing
