### ISSUE TITLE
`load-env` can update PWD coming from the pipeline

### ISSUE THREAD

**Issue by YizhePKU** [nushell/nushell#12520]
### Describe the bug

`load-env { PWD: foo }` doesn't work, but `{ PWD: foo } | load-env` does. I think this behavior is inconsistent.

### How to reproduce

```nu
mkdir foo
load-env { PWD: foo } # error: PWD cannot be set manually
{ PWD: foo } | load-env # OK
```

### Expected behavior

`load-env` should either accept both or reject both.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.91.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (built from a source tarball) |
| cargo_version      | cargo 1.76.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
Agreed. Neither should be allowed.
