### ISSUE TITLE
 "The command line is too long." for `<command> ./input/*` but not when actually writing out the command.

### ISSUE THREAD

**Issue by Gremious** [nushell/nushell#12527]
### Describe the bug

I was trying to make a script for [gifski](https://gif.ski/), as it recomends, where:
1. ffmpeg outputs all the frames of an mp4 into a folder
2. gifksi has all of them as individual input parametrers like so: `gifski out.gif ./tempgif/*`

On a video with 384 frames, this outputs "The command line is too long."

However, running `glob tempgif/* |  str join ' ' |  $'.\gifski.exe --output gif.out ($in)' | nu -c $i` executes it no problem.
(does't seem to work with `^string` so `nu -c` it is)

Copy-pasting the ouput of `glob tempgif/* |  str join ' '` and just running the command manually also works just fine.

Copy pasting it as a script in a def also no problem.

Surprised `gifski *.png` doesn't just do the same thing `glob *.png` does and pass the raw output along?

### How to reproduce

get https://gif.ski/ and ffmpeg, run the following:

```nu
def to_gif [input: path] {
	mkdir ./tempgif
	ffmpeg -i $input tempgif/frame%04d.png
	./gifski.exe -o out.gif ./tempgif/*.png
}
```

### Expected behavior

It runs the command with no problem.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.92.2                                   |
| branch             |                                          |
| commit_hash        | 2a08a18b26865a86c793d183b9b042220ecb733a |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)      |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)      |
| build_time         | 2024-04-10 21:24:37 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which            |
| installed_plugins  |                                          |

**Comment by Gremious** [comment]
nvm I'm bad and was just only occatonally 8191 characters windows limit

**Comment by fdncred** [comment]
I've seen strange things on Windows at 8192. I'm still not convinced we don't have a bug in nushell around that number.

**Comment by ChrisDenton** [comment]
That's round about the limit for `cmd.exe`. Something is likely going through either cmd or a bat script (or both) at some point. https://learn.microsoft.com/en-US/troubleshoot/windows-client/shell-experience/command-line-string-limitation
