### ISSUE TITLE
Regression: can't pass $it to cmd on Windows

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1253]
**Describe the bug**
This used to work, but has broken in recent weeks:

```
❯ which az | get path | cmd /c $it
The filename, directory name, or volume label syntax is incorrect.
error: External command failed
- shell:1:32
1 | which az | get path | cmd /c $it
  |                       ^^^ command failed
```

**To Reproduce**
1. `which az | get path | cmd /c $it` 

**Expected behavior**
This should invoke az for you via cmd

**Configuration (please complete the following information):**
 - OS: [e.g. Windows]: Windows 10
 - Version [e.g. 0.4.0]: 0.8.1
 - Optional features (if any): stable

**Comment by koenaad** [comment]
This might be caused by https://github.com/nushell/nushell/pull/1220? This is a fairly recent commit that changes how $it behaves.
I did not test if single quotes are legal in a Windows terminal since I'm currently mac-only :/

**Comment by jonathandturner** [comment]
This is working now
