### ISSUE TITLE
Support `sort-by` with nested columns

### ISSUE THREAD

**Issue by devurandom** [nushell/nushell#12535]
### Related problem

My data has this shape:
```json
[{"metadata": {"creationTimestamp":"2024-04-15T12:11:00Z"}}]
```

### Describe the solution you'd like

I would like to `sort-by metadata.creationTimestamp`, like I can do `get metadata.creationTimestamp`.

### Describe alternatives you've considered

I could revert to `jq`, but I would prefer a solution with nushell's native tools.

**Comment by NotTheDr01ds** [comment]
I can certainly see the use for this, but can you `flatten` the data for sorting purposes in your particular use-case?

**Comment by devurandom** [comment]
Something like `... | flatten metadata | sort-by creationTimestamp`? (cf. https://www.nushell.sh/commands/docs/flatten.html)
Could work without name collisions for the data I have, yes. Thanks for giving me this workaround!
