### ISSUE TITLE
`explore` command crashes

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#12539]
### Describe the bug

The `explore` command panics with an error in time.rs. Not sure what is going on exactly.
![image](https://github.com/nushell/nushell/assets/343840/a32b040f-a966-4e69-bb81-37ae622e9a29)

### How to reproduce

1. nu
2. explore
3. :try
4. ls
5. click on another window, away from your terminal, and back to terminal again. I have to do this several times and sometimes type  |  then click away and back again, inevitably it crashes

### Expected behavior

no crash

### Screenshots

Full backtrace doesn't look like much more help.
![image](https://github.com/nushell/nushell/assets/343840/cb05f762-ef8b-4179-bcfe-c04aa7746537)

I'm assuming it's related to recent changes to help tuis.
/cc @devyn 

### Configuration

|key|value|
|-|-|
|version|0.92.3|
|branch|main|
|commit_hash|48e4448e55b9d1ad3e53c5b0d87387d346ae288e|
|build_os|windows-x86_64|
|build_target|x86_64-pc-windows-msvc|
|rust_version|rustc 1.77.2 (25ef9e3d8 2024-04-09)|
|rust_channel|1.77.2-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.77.2 (e52e36006 2024-03-26)|
|build_time|2024-04-16 10:40:54 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|dataframe, default, sqlite, trash, which|
|installed_plugins|bg, emoji, file, formats, msgpack, from_parquet, gstat, inc, json_path, jwalk, md, explore, pnet, polars, query, query_git, regex, str_similarity|

**Comment by fdncred** [comment]
A short video of the repro. I'm not sure if `plugin list` is required or not. I was just thinking back over what I was doing and I was messing around with `plugin list`
![panic_after_plugin_list](https://github.com/nushell/nushell/assets/343840/b776015c-93f9-46e2-9a45-c48c67582cdf)

**Comment by ayax79** [comment]
I can't reproduce on my mac. I'll try in windows.

**Comment by ayax79** [comment]
I was able to produce it in windows. The same panic:

<img width="906" alt="Screenshot 2024-04-16 at 18 12 26" src="https://github.com/nushell/nushell/assets/56345/1e8f8b7e-9446-49a8-a124-fc64f2496cd0">

I think the only place that overflow could occur is nu-explore/src/pager/events.rs:50

I'll try to add some debugging around to figure out what is going on.

With scrolling back, is that an issue everywhere? I am not having problems scrolling back in general. I'll install some plugins, but it seems odd that it would only effect `plugin list`

**Comment by fdncred** [comment]
> I was able to produce it in windows. 

Glad you could repro it.

I wasn't able to reproduce in Ubuntu WSL. Only on Windows.

> With scrolling back, is that an issue everywhere? 

The scrolling issue only occurs after the panic with me.

**Comment by fdncred** [comment]
Oof, just reproduced on macos, but it's weird.
![image](https://github.com/nushell/nushell/assets/343840/c9b61ffa-d9f5-4ea8-be4b-d4221b164e8d)

**Comment by ayax79** [comment]
And.. it looks like @devyn already fixed it.

**Comment by devyn** [comment]
Maybe, it seems like the macOS issue is separate but may have to do with running TUI apps within explore

**Comment by fdncred** [comment]
Closed due to Windows issue. Not quite sure about MacOS issue though.
