### ISSUE TITLE
Have a fallback namespace for builtin commands

### ISSUE THREAD

**Issue by suimong** [nushell/nushell#12552]
### Related problem

For builtin commands such as “exit”, make it accessbile as e.g. “builtin exit” or “builtin.exit”. The motivation for this is that while writing custom modules, I have a custom command called “exit” which does some cleanup stuff then calls the builtin “exit”, but could not because nushell recursively calls my “exit” custom command.

### Describe the solution you'd like

Having the ability to fully qualify a builtin command would solve the issue at the slight expense of taking up an additional word (“builtin”) in the global namespace.

**Comment by fdncred** [comment]
Seems like you could just name your custom command `def 'custom exit' [blah] {}` and avoid this. Right?

**Comment by kubouch** [comment]
There are plans to move builtin commands to modules, which would solve the problem. For now, you can `alias old-exit = exit` to refer to the builtin `exit` as `old-exit`.

I believe this has been asked already, this might be a duplicate.

**Comment by suimong** [comment]
> There are plans to move builtin commands to modules, which would solve the problem. For now, you can `alias old-exit = exit` to refer to the builtin `exit` as `old-exit`.
> 
> 
> 
> I believe this has been asked already, this might be a duplicate.

Ah this is a nice workaround. Should have thought of it. 

Feel free to close this if there is a duplicate.

**Comment by kubouch** [comment]
I currently don't have time to check the issues thoroughly. Ideally, before opening an issue, one would check for duplicates, so if you have the time, please do so if you haven't already.

**Comment by NotTheDr01ds** [comment]
It's possible that @kubouch is thinking about my #11686 as the possible duplicate (or it could be something else).  It's certainly related.

**Comment by suimong** [comment]
@kubouch Sorry I don't mean to take the conversation lightly. I was on commute when posting the issue and only did a cursory search.

@NotTheDr01ds thanks for the pointer. Apart from #11686, #11824 is also related. But #8854 is definitely the one with the exact same motivation use case as mine. Closing this in favor of #8854.

**Comment by kubouch** [comment]
No problem, we're all busy. Thanks for the investigation!
