### ISSUE TITLE
Expose Nushell version infos in `$nu`

### ISSUE THREAD

**Issue by poliorcetics** [nushell/nushell#12561]
### Related problem

As Nushell becomes supported by more and more tools (yay!) they have to contend with the rapid pace of evolution and semi-regular breaking changes.

To do this, tools have started to parse `$env.NU_VERSION` as [atuin did here](https://github.com/atuinsh/atuin/blob/2fba4aae933c17f0024110dd9ec4a57d748cf867/atuin/src/shell/atuin.nu#L39).

### Describe the solution you'd like

In typical XKCD fashion, let's introduce a new standard to fix all previous standards: Nushell would add `$nu.version` exposing the following informations (bikesheddable):

```nu
╭────────┬──────────╮
│ major  │ 0        │
│ minor  │ 92       │
│ patch  │ 2        │
│ commit │ abcdefgh │ # Possibly `null` (it's valid to build nushell after deleting `.git`)
│ extra  │          │ # Will often be `null`, could be a string like "-rc.1" for example
╰────────┴──────────╯
```

This would allow tools to easily say `if $nu.version.major <= 0 and $nu.version.minor <= 92 { ... } else { ... }`: that's readable and less error prone.

Having tuple and tuple comparison would probably work even better for `(major, minor, patch)` but that's not a requirement for nicer state than the current one.

### Describe alternatives you've considered

1. Keeping the env var parsing: that's what is done currently and works, and in a nicer way than sh-like shells because Nushell has nice string handling, but it's still not ideal and error prone. It adds several lines of code for something that should be trivial and has to be "rediscovered" each time
2. Have more granular env vars: still some string handling, proliferation of env vars is also not great when we have `$nu` as a source of information already

**Comment by poliorcetics** [comment]
Oh I didn't know it existed. It looks like an old command too, some commits go back 3 years.

I suppose it not being used is a combination of

1. Being a command with lots of unnecessary data when there is a variable with the data already computed
2. Discoverability not being good for it (though I don't know how to improve it if that's the case)

Still, having  explicit `major`, `minor` & `patch` would be good and avoid parsing. Having them in a variable that doesn't have to be computed on each call (for atuin: each command) *may* have performance benefits but if it does, I couldn't see them in those quick-n-dirty benches:

```nushell
timeit { mut x = 0; loop { if $x > 10000 { break; }; (version).version; $x = $x + 1 } }
8ms 938µs 41ns

let version_data = (version); timeit { mut x = 0; loop { if $x > 10000 { break; }; ($version_data).version; $x = $x + 1 } }
8ms 815µs 83ns
```

That's less than a 2% difference for 10 000 runs.

Running with `$env.NU_VERSION`:

```nushell
timeit { mut x = 0; loop { if $x > 10000 { break; }; $env.NU_VERSION; $x = $x + 1 } }
925ms 657µs 958ns
```

That's more than a 100 times worse, making a good argument for adding explicit `major`, `minor` & `patch` to `version` or `$nu.version.<...>`

I will make a PR for that this weekend

**Comment by NotTheDr01ds** [comment]
I'm a bit confused. The examples you provided show that `version` is about 100 times faster than `$env.NU_VERSION`, right?  But that doesn't speak to the performance of *parsing* the `version` output each time.

To see that:

```Nushell
> timeit {
    for _ in 1..10000 { version }
  }
11ms 252µs 364ns

> timeit {
    for _ in 1..10000 {
      let version_detail = (version).version | split column '.' | rename major minor patch
      $version_detail.major
    }
  }
63ms 14µs 226ns
```

That's only about 6x worse, not 100x.

And even then, across 10,000 calls, we're talking about less than a 50ms difference.  So, while I'm not quite sure I understand your use case with `atuin`, even if you parse it on each command you are only adding 0.006 *milliseconds* to each command.

**Comment by NotTheDr01ds** [comment]
However, as demonstrated, a performance gain of 0.006 milliseconds is simply so small here as to be a non-factor, and the "usability" (a.k.a. convenience) has to be countered with the [Nushell Design Philosophy](https://www.nushell.sh/contributor-book/philosophy_0_80.html#command-philosophy):

> 2. The aim of our library of builtin commands is to provide a collection of simple and composable primitive commands, that covers essential shell programming needs and allows virtually anything to be built via composition and creation of custom user commands and plugins. That's as opposed to maintaining an extensive catalog of more specialized commands in the core nushell codebase: more specialized functionality should exist as community-contributed libraries (e.g. plugins/nushell libraries).
>
> 3. If something can be done conveniently by composition of simpler commands then we do not add flags and options to do the same thing.

Since this can already *"be done conveniently by composition of simpler commands"*, I don't think it meets that criteria.

I'm not saying that convenience isn't a good goal, but it should be applied to either (a) more *common* situations or (b) things that are simply much harder (or impossible) to do in Nu-script.  For instance, [this PR of yours (#10480)](https://github.com/nushell/nushell/pull/10480) was a *great* addition, IMHO, since it allows us to do things that we simply couldn't do before.

Adding Rust code in this `version` case just means more potential maintenance later if things change (albeit a very small potential, I believe).

I'd just recommend checking with a maintainer before spending time on a PR for this one.

**Comment by poliorcetics** [comment]
For the important point:

> Adding Rust code in this version case just means more potential maintenance later if things change (albeit a very small potential, I believe).

Here is the whole diff for the command (https://github.com/nushell/nushell/blob/main/crates/nu-cmd-lang/src/core_commands/version.rs#L58) barring tests and docs, and even then I wouldn't expect them to inflate it much.

```rust
    static VERSION_NUMBERS: Lazy<(u8, u8, u8)> = Lazy::new(|| (
        env!("CARGO_PKG_VERSION_MAJOR").parse().expect("Cargo always set this"),
        env!("CARGO_PKG_VERSION_MINOR").parse().expect("Cargo always set this"),
        env!("CARGO_PKG_VERSION_PATCH").parse().expect("Cargo always set this"),
    ));

    record.push("major", Value::int(VERSION_NUMBERS.0 as _, call.head));
    record.push("minor", Value::int(VERSION_NUMBERS.1 as _, call.head));
    record.push("patch", Value::int(VERSION_NUMBERS.2 as _, call.head));
```

> I'm not saying that convenience isn't a good goal, but it should be applied to either (a) more common situations or (b) things that are simply much harder (or impossible) to do in Nu-script.

(b) is right in that it's not hard to do currently.

(a) is exactly why I opened this: checking Nu versions will only become more and more prevalent as tools adopt it, making that process easier **while not adding full blown version comparison or a new command** would be very useful IMO

<details><summary>The rest is less important and also wrong for some parts</summary>
<p>
I don't understand how you ended with 0.006ms of difference but comparing the actual command+field access I get 0.169ms of diff, which is two orders of magnitude bigger.

```
17:46:55 ~ 
🐘 ❯ timeit { let version_detail = $env.NU_VERSION | split column '.' | rename major minor patch; $version_detail.major }
183µs 125ns

17:47:28 ~ 
🐘 ❯ timeit { let version_detail = version; $version_detail.version }
14µs
```

Now, I agree that in theory 0.169ms is not that big of a deal except it's *one little part of a whole* that runs very often and a very easy win.

> 3. If something can be done conveniently by composition of simpler commands then we do not add flags and options to do the same thing.

I am not proposing adding either so that's just missing the point, I'm proposing adding information that's already in the binary to either `$nu` or `version`, which also already exists.

> 2. The aim of our library of builtin commands is to provide a collection of simple and composable primitive commands, that covers essential shell programming needs and allows virtually anything to be built via composition and creation of custom user commands and plugins. That's as opposed to maintaining an extensive catalog of more specialized commands in the core nushell codebase: more specialized functionality should exist as community-contributed libraries (e.g. plugins/nushell libraries).

I'm not proposing to add new commands ? That's also missing the point. I would even say it's also in favor of adding it ? "composable primitive commands" certainly works better when the command separates the version components instead of making the user do it each and every time.
</p>
</details>
