### ISSUE TITLE
Test helper applications are being cargo install-ed

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1257]
**Describe the bug**
Do a `cargo install --path . --force --features=stable` for a recent master of Nu.

You'll see:

```
    Replaced package `nu v0.8.1 (C:\Source\Play\nushell)` with `nu v0.8.1 (C:\Source\Play\nushell)` (executables `chop.exe`, `cococo.exe`, `fail.exe`, `nu.exe`, `nu_plugin_core_inc.exe`, `nu_plugin_core_ps.exe`, `nu_plugin_core_str.exe`, `nu_plugin_core_sys.exe`, `nu_plugin_core_textview.exe`)
```

chop.exe, cococo.exe, and fail.exe should not be part of the batch of commands installed.

**To Reproduce**
1. Do a `cargo install --path . --force --features=stable` for a recent master of Nu.

**Expected behavior**
Only plugins and nu itself should be installed.

**Comment by andrasio** [comment]
This has been fixed. Closing.
