### ISSUE TITLE
uname command no longer supports common flags

### ISSUE THREAD

**Issue by Newbytee** [nushell/nushell#12570]
### Describe the bug

As of https://github.com/nushell/nushell/pull/11684 (I think), the uname command no longer supports common flags like `-m`. This a problem for my use-case where I use `ssh <username>@<host> uname -m` in a script to deduce which architecture the device is.

If this is out of scope I understand, but to me this seems like a small "nice to have" compatibility feature.

### How to reproduce

1. Run `uname -m` with Nushell
2. Get an error about it being an unknown flag

### Expected behavior

I expected it to return the name of my machine's architecture

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.92.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-aarch64                                                |
| build_target       | aarch64-alpine-linux-musl                                    |
| rust_version       | rustc 1.77.0 (aedd173a2 2024-03-17) (Alpine Linux 1.77.0-r0) |
| cargo_version      | cargo 1.77.0                                                 |
| build_time         | 2024-04-03 10:33:03 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which                                |
| installed_plugins  |                                                              |

**Comment by fdncred** [comment]
Yup, that's correct and as designed. We went for a more nushell-centric uname than a bash-like implementation. You can do something like `(uname).machine` to mimick the `uname -m` functionality.

**Comment by Newbytee** [comment]
Would it not be feasible to have both? If I were writing a Nushell script I would of course go for the latter but in this case I'm logging into a foreign machine where I can't really detect the shell before connecting.

**Comment by fdncred** [comment]
Probably not. I mean, it's software so it's do-able, but being posix/bash compliant is a non-goal. Other core-team members may disagree with me.

We want users to feel at home and comfortable with nushell but we also want to leave the 30+ year past of bash behind and work in a more productive way. It's kind of a slippery slope. If we start changing one command to be more like bash then people will want their favorite command changed and all of a sudden, we have bash again.

**Comment by kubouch** [comment]
I agree with fdncred, there is no reason to add the flag to the Nushell command as it already gives a structured output. If we started to add compatibility flags to all the POSIX tools, there would be no end to it.

As a workaround, the native `uname` didn't go anywhere. You can run `ssh <username>@<host> bash -c 'uname -m'` if you're unsure which shell the target machine is using.

I'll close this as we most likely don't plan to add the flags, but feel free to ask again if something is unclear.
