### ISSUE TITLE
http post --content-type flag behavior is different

### ISSUE THREAD

**Issue by gutenye** [nushell/nushell#12588]
### Describe the bug

The `--content-type` flag behavior is different when set to `application/json` or `plain/text`. It's very confusing

### How to reproduce

1. Run `http post http://localhost '' --content-type application/json`
2. The request header `content-type` is set to `application/json`
3. Run `http post http://localhost '' --content-type plain/text`
4. The request header `content-type` is **not set** to `plain/text`

### Expected behavior

The request header `content-type` is **should set** to `plain/text`

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.91.0                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | macos-aarch64                                        |
| build_target       | aarch64-apple-darwin                                 |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (Homebrew)       |
| cargo_version      | cargo 1.76.0                                         |
| build_time         | 2024-03-05 20:28:40 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | mimalloc                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by alluringambiguous** [comment]
hey, I like this, I will take this up

**Comment by sholderbach** [comment]
Have fun!

**Comment by alluringambiguous** [comment]
Hi,
I have fixed the issue in this commit : https://github.com/nushell/nushell/commit/b9798741fb259f31debb72644160878f41c35c47

Can you please have a look at it? @sholderbach 
I will write test if you approve

**Comment by sholderbach** [comment]
> I have fixed the issue in this commit : https://github.com/nushell/nushell/commit/b9798741fb259f31debb72644160878f41c35c47

Looks plausible, please open it as a pull request. 
 
> I will write test if you approve

You can take a look how we use the `mockito` crate for testing.

**Comment by weirdan** [comment]
No longer reproducible with 0.96:
```console
$ http post https://httpbin.org/post '' --content-type plain/text | get headers.`Content-Type`
plain/text

$ http post https://httpbin.org/post '' --content-type text/plain | get headers.`Content-Type`
text/plain
```
