### ISSUE TITLE
Support configuring default flags in config.toml

### ISSUE THREAD

**Issue by kvrhdn** [nushell/nushell#1258]
**Is your feature request related to a problem? Please describe.**
Not really. This is more like a design proposal.

**Describe the solution you'd like**
I noticed there are some command which allow customization through flags, i.e. a flag that changes the behaviour of a command, not the functionality. It might be nice to set up a system that allows you to configure these kind of flags through the config.

Example:
```
ls | table --start_number 1
```

`--start_number` is an example of flag that changes the behaviour of `table` that could be considered a 'preference'. As in, it makes sense to _always_ want to use this flag.
Currently, you would have to always type this flag. But it would be nice if you could instead add an entry in `config.toml` kind of like:
```toml
[table]
"start_command" = 1
```

Running the `table` command would:
- use the value set by the `--start_command` flag if it is present
- use the value configured in `config.toml` if it is present otherwise
- or use the default otherwise

With a smart design, we might be able to leverage the existing flags of a command. If we could mark flags as `configurable`, it would be cool if they automatically hook into the config system.

**Describe alternatives you've considered**
Being able to define aliases might also solve this issue of typing flags over and over and is also useful for non-builtin commands.

**Comment by thegedge** [comment]
> Being able to define aliases might also solve this issue 
I think this is right. Perhaps we can close in favour of such an issue (https://github.com/nushell/nushell/issues/378)

**Comment by thegedge** [comment]
We have aliases now, and I think that's a better alternative to having per-command configuration (which would impose some cost on all invocations).
