### ISSUE TITLE
Can i specify the sort rule when sort an table

### ISSUE THREAD

**Issue by malongshuai** [nushell/nushell#12605]
### Question

for example, i want to sort the result of `ls` command by the filename length.

```
~> ls
╭───┬─────────────────────┬──────┬─────────┬──────────────╮
│ # │        name         │ type │  size   │   modified   │
├───┼─────────────────────┼──────┼─────────┼──────────────┤
│ 0 │ dump.rdb            │ file │   975 B │ 3 weeks ago  │
│ 1 │ redis-stable        │ dir  │ 4.0 KiB │ 3 months ago │
│ 2 │ redis-stable.tar.gz │ file │ 3.3 MiB │ 3 months ago │
╰───┴─────────────────────┴──────┴─────────┴──────────────╯
```

i checked the document: sort-by(<https://www.nushell.sh/commands/docs/sort-by.html>), i think it can accept a closure to sort by any rule. like this:

```
ls | sort-by {|row| $row.name | length}
```

**Comment by woosaaahh** [comment]
Hi !

The only parameters that `sort-by` accept are the column **names**.

It's not mentioned in the documentation but those parameters must be `string`.
See the line here https://github.com/nushell/nushell/blob/main/crates/nu-command/src/filters/sort_by.rs#L81
The `let columns: Vec<String>` part can be understood as "columns will be a vector (kind of array) of strings".

To solve your problem, you can use a temporary column and `sort-by` it.
```nushell
ls | insert name_len { get name | str length } | sort-by name_len | reject name_len
```
```nushell
> [[name]; [a] [bcd] [ef]]
╭───┬──────╮
│ # │ name │
├───┼──────┤
│ 0 │ a    │
│ 1 │ bcd  │
│ 2 │ ef   │
╰───┴──────╯
```
```nushell
> [[name]; [a] [bcd] [ef]]
::: | insert name_len { get name | str length }
::: | sort-by name_len
::: | reject name_len
╭───┬──────╮
│ # │ name │
├───┼──────┤
│ 0 │ a    │
│ 1 │ ef   │
│ 2 │ bcd  │
╰───┴──────╯
```
