### ISSUE TITLE
`ls -s <path>` loses colors from regular `ls <path>`

### ISSUE THREAD

**Issue by poliorcetics** [nushell/nushell#12618]
### Describe the bug

![Screenshot 2024-04-22 at 14 36 34](https://github.com/nushell/nushell/assets/7951708/ad478a2b-a3cf-4216-b46b-f443dafa7c29)

Note: this doesn't happen if the path is left unspecified: `ls -s` alone works perfectly well

### How to reproduce

1. open new shell
2. `ls /tmp`
3. `ls -s /tmp`

### Expected behavior

I expected `ls -s <path>` to output the same colors as `ls <path>`

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.92.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.76.0 (07dca489a 2024-02-04) (built from a source tarball) |
| cargo_version      | cargo 1.76.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which                                     |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
This is a known bug, so this issue is a dupe. There's at least one issue already opened for this. It's that metadata isn't getting saved properly.
