### ISSUE TITLE
using `--help` flag  causes all flags and arguments to disappear

### ISSUE THREAD

**Issue by coolshaurya** [nushell/nushell#1262]
**Describe the bug**
Passing the `--help` flag to any nu command makes all arguments and flags disappear. Does not happen with non-nu commands.

**To Reproduce**
1. Pass the `--help` flag to any nu command e.g. `ls --help`
2. See the arguments and flags disappear
3. 

**Expected behavior**
The flags and arguments to appear normally

**Screenshots**

![Peek 2020-01-22 22-34](https://user-images.githubusercontent.com/32027323/72916092-6003a980-3d67-11ea-959f-43eb1a88b5b2.gif)
![Peek 2020-01-22 22-33](https://user-images.githubusercontent.com/32027323/72916106-65f98a80-3d67-11ea-8b2f-4501bf7f4875.gif)

**Configuration (please complete the following information):**
 - OS: Manjaro Linux
 - Version: latest master (0.8.1) commit - 762c798670a07aa7bb333a09fc094cdb3a184799
 - Installed using `  cargo install --path . --force --features stable`

**Comment by andrasio** [comment]
Thanks! 

Close! It was introduced [here](https://github.com/nushell/nushell/commit/a5c5b4e7112af9312be27e6fc6bb1ce407b2f405)
