### ISSUE TITLE
Cannot cp file or directory on FreeBSD

### ISSUE THREAD

**Issue by Canvis-Me** [nushell/nushell#12627]
### Related problem

On `FreeBSD 14` stable branch, cannot `cp` file or directory, it will output
```
/usr/local/bin/nu: --reflink is only supported on linux and macOS
```

### Describe the solution you'd like

`cp` file or directory without any error.

### Describe alternatives you've considered

`xcp` works fine under `FreeBSD 14`

**Comment by fdncred** [comment]
We use uutils/coreutils for our `cp` command so you may want to see if it works for you. If it does, it means we have a bug in nushell. If it doesn't it means that coreutils cp doesn't support, it and it would have to be added to their uu_cp crate for us to support it.

**Comment by Canvis-Me** [comment]
Tested with `uu-cp` in `rust-coretils` port (actually `cp` in uutils/coreutils on `FreeBSD`), and both the copy of file and directory works well.

**Comment by fdncred** [comment]
Sounds like someone needs to do some debugging to see exactly what's going on. It would also be good to ensure versions of nushell are the latest and the version of uu_cp in nushell is that latest published by coreutils.

**Comment by Canvis-Me** [comment]
`nushell` version is `0.92.1`, and `coreutils` is `0.0.25`.

**Comment by fdncred** [comment]
This will take someone to build and fix who has freebsd available to them. We'd be happy to accept such a PR.
