### ISSUE TITLE
[FeatureRequest] support globbing braces expansion syntax {a,b} directly on readline

### ISSUE THREAD

**Issue by gutenye** [nushell/nushell#12647]
### Related problem

In bash: I can do this `cp {a,b} dest`
In nushell: I must do this `glob '{a,b}' | each { cp $in dest }`

Please support bash syntax, thanks.

### Describe the solution you'd like

globbing on readline supports the same pattern from glob cmd directly.

**Comment by fdncred** [comment]
In nushell you should use `str expand`. It's why it was created.

**Comment by gutenye** [comment]
I'm seeking a faster and more concise method since it's a commonly used daily operation, and also to provide ease of transition for users from other shells. If there are no plans to support this feature, please feel free to close it.

**Comment by fdncred** [comment]
I have no plans for it personally, but others may. We are purposefully not bash or posix compliant, but there are some things we add from bash from time to time because they're widely used. But other times we just provide workarounds like with glob in your example.
```nushell
❯ glob 'Cargo{.lock,.toml}'
╭───┬─────────────────────────────────────────────────────────╮
│ 0 │ C:\Users\username\source\repos\forks\nushell\Cargo.lock │
│ 1 │ C:\Users\username\source\repos\forks\nushell\Cargo.toml │
╰───┴─────────────────────────────────────────────────────────╯
```
