### ISSUE TITLE
As far as I can tell, currently there's no way to close a single subshell

### ISSUE THREAD

**Issue by isti115** [nushell/nushell#12642]
### Describe the bug

(Or should I say _"No popd?"_ in reference to #4269? 😀)

The following help page for `shells` lists the related commands:
https://www.nushell.sh/commands/categories/shells.html

If I recall correctly, at some point the documentation for `exit` used to say something like: _"Exit the current shell, or the entire process, if it's the last one."_

Right now I cannot find a way to exit a single subshell.

### How to reproduce

1. `nu`
2. `enter /tmp`
3. `shells`
4. `exit`

### Expected behavior

Only the currently active subshell / working directory should be removed from the list, but the entire process quits.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.92.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.77.1 (7cf61ebde 2024-03-27) (built from a source tarball) |
| cargo_version      | cargo 1.77.1                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which                                     |
| installed_plugins  |                                                                   |

### Additional context

Maybe `exit` should be kept for killing the entire process, and a new `leave` command could be added for leaving a single directory? I'm willing to try to work towards a PR on this if the maintainers agree that the current set of commands are lacking in terms of functionality / their behavior is insufficient, and this would be a welcome improvement.

**Comment by fdncred** [comment]
The "shell" functionality was moved to a script and removed from rust code. I think `dexit` replaced `exit` because we can't just type `exit` anymore without exiting the shell. The documentation is definitely outdated.

**Comment by isti115** [comment]
Thank you @fdncred, `dexit` works as expected!
I took a look at the documentation pages, and saw that as these commands are from the standard library, their entries are not automatically generated, so I updated them manually and sent a PR: https://github.com/nushell/nushell.github.io/pull/1369
