### ISSUE TITLE
`"7 days ago at 04:00" | into datetime` only applies the date, not the time

### ISSUE THREAD

**Issue by Schweber** [nushell/nushell#12650]
### Describe the bug

`"7 days ago at 04:00" | into datetime` goes back 7 days as intended but uses the present time, not the given time of `04:00`.

### How to reproduce

Run `"7 days ago at 04:00" | into datetime`

### Expected behavior

`"7 days ago at 04:00" | into datetime` goes back 7 days *and* sets the time to `04:00`.

The [manual](https://www.nushell.sh/commands/docs/into_datetime.html#into-datetime-for-conversions) shows exactly such an example.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.92.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.77.1 (7cf61ebde 2024-03-27) (built from a source tarball) |
| cargo_version      | cargo 1.77.1                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which                                     |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
Sounds like an upstream issue vs a nushell issue. We just use a crate to convert human readable text to date times

**Comment by fdncred** [comment]
I think it's this one https://github.com/technologicalMayhem/human-date-parser
