### ISSUE TITLE
`"last week at 04:00" | into datetime` panics

### ISSUE THREAD

**Issue by Schweber** [nushell/nushell#12651]
### Describe the bug

```
"last week at 04:00" | into datetime                                                                                                    
Error:   × Main thread panicked.
  ├─▶ at /build/nushell-0.92.1-vendor.tar.gz/human-date-parser/src/lib.rs:436:13
  ╰─▶ Tried to convert Week to a weekday, which is not possible. This is a bug.
  help: set the `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### How to reproduce

Run `"last week at 04:00" | into datetime`

### Expected behavior

"last week" could be interpreted as "7 days ago" (without more specific input) or "sometime last week" (with more specific input like "Friday last week"). 

In any case, nushell should not panic but show an error message if it doesn't understand "last week" or if "last week" without more specific input is deemed too vague and rejected on purpose.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.92.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.77.1 (7cf61ebde 2024-03-27) (built from a source tarball) |
| cargo_version      | cargo 1.77.1                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which                                     |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
Probably another upstream issue

**Comment by horasal** [comment]
actually I can't reproduce this panic on latest version

![2024-04-25 192354](https://github.com/nushell/nushell/assets/1991933/1179a085-2945-470b-bcc2-5945c5cb3541)

and the upstream library

![2024-04-25 ](https://github.com/nushell/nushell/assets/1991933/057c80a9-b774-4b1e-a638-6c9bc05afaad)

I think it's may be solved at sometime (maybe https://github.com/technologicalMayhem/human-date-parser/commit/e61ab9234cc30b3ef7a36f9c6e4a02c73968e73d )

Could you try the latest version of nushell?
