### ISSUE TITLE
cannot get specific coloum if not all rows contain a non-null value?

### ISSUE THREAD

**Issue by brunbjerg** [nushell/nushell#12663]
### Describe the bug

I am trying to filter through MBs of logs for specific column names that are only sometimes present, tactical_objective_value, in this case. The output of:

`open logging/logs/ordinator.log.2024-04-25 | from json -o | get fields`

Clearly indicates that the column is present (tactical_objective_value) but when selecting if it yields an error? Is this considered a bug? Or am I using nu "wrong"?

### How to reproduce

open logging/logs/ordinator.log.2024-04-25 | from json -o | get fields

│ # │                                                   message                                                    │ tactical_objective_value │
│ 0 │ starting loging                                                                                              │            ❎            │
│ 1 │ Excel file from path "sfully loaded                                                                │            ❎            │
│ 2 │ operation_description is not a string                                                            │            ❎            │
│ 3 │ operation_description is not a string                                                            │            ❎            │
│ 4 │ The Scheduling Environment is currently comprised of                              │            ❎            │
│ 5 │ StrategicAgent has started for asset: HB                                                     │            ❎            │
│ 6 │ TacticalAgent 0 has started, sending Its address to the StrategicAgent      │            ❎            │
│ 7 │ starting 4 workers                                                                                         │            ❎            │
│ 8 │ Actix runtime found; starting in Actix runtime                                              │            ❎            │
│ 9 │                                                      ❎                                                             │ 0                        │

ordinator on  80-test-strategic-optimized-work-order-builder via  v1.77.2
❯ open logging/logs/ordinator.log.2024-04-25 | from json -o | get fields | columns

│ 0 │ message                        │
│ 1 │ tactical_objective_value │

ordinator on  80-test-strategic-optimized-work-order-builder via  v1.77.2
❯ open logging/logs/ordinator.log.2024-04-25 | from json -o | get fields | select tactical_objective_value
Error: nu::shell::column_not_found

  × Cannot find column
 1 │ open logging/logs/ordinator.log.2024-04-25 | from json -o | get fields | select tactical_objective_value
 
                                                                                                                    ╰── cannot find column 'tactical_objective_value

but if I select the row and then select the column it works fine

`ordinator on  80-test-strategic-optimized-work-order-builder via  v1.77.2
❯ open logging/logs/ordinator.log.2024-04-25 | from json -o | get fields | get 9 | select tactical_objective_value
│ tactical_objective_value │ 0 │
`

### Expected behavior

I would expect nu to give me the column of the table when it says that it is present. Check screenshot for additional information.

### Screenshots

![screenshot_2024-04-25-095701](https://github.com/nushell/nushell/assets/44016161/f3bcbabb-654a-478e-9779-98ecd9ca4f4f)

### Configuration

❯ version | transpose key value | to md --pretty
| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.92.2                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 2a08a18b26865a86c793d183b9b042220ecb733a                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.77.1 (7cf61ebde 2024-03-27) (Arch Linux rust 1:1.77.1-2) |
| cargo_version      | cargo 1.77.1                                                     |
| build_time         | 2024-04-11 08:40:50 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, sqlite, trash, which                         |
| installed_plugins  |                                                                  |

**Comment by WindSoilder** [comment]
It seems that there are some records don't have `fields`, Can you try this?
```nushell
open logging/logs/ordinator.log.2024-04-25 | from json -o | get fields?
```

**Comment by fdncred** [comment]
Wind is right, the optional character `?` on the end of the field you're looking for should work, but you can also do `get -i tactical_objective_value`.

It can be helpful to look at each command's help like `help get` to understand how you can use it.

**Comment by brunbjerg** [comment]
Thank you, this worked! 

Nushell coerces the JSON document form representation of data into a table form. I think that this can be a little confusing. The ❎  signify the "missing" values, which of course were never actually missing.

I feel like there could be a user-interface improvement here. What do you guys think?

**Comment by fdncred** [comment]
the green x indicates that there is a place for a value in a tabular layout but there is no value in the data and therefore it's missing.

what type of improvements here are you thinking about?

**Comment by brunbjerg** [comment]
None that does not lead to a worse trade-off I think.
