### ISSUE TITLE
Can not get the correct datetime when I use `into datetime` to parse seconds timestamp

### ISSUE THREAD

**Issue by pzzxqj** [nushell/nushell#12671]
### Describe the bug

The result is incorrect when 'into datetime' convert seconds to datetime.

### How to reproduce

```sh
nu ❯ 1614434140 | into datetime 
1970-01-01T00:00:01
```

### Expected behavior

2021-02-27T13:55:40

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.92.2                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26) |
| build_time         | 2024-04-15 11:58:52 +08:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash, which       |
| installed_plugins  | regex                               |

**Comment by fdncred** [comment]
it's because `into datetime` doesn't support seconds. it only supports nanoseconds. i think this example is right.
```nushell
❯ 1614434140 * 1_000_000_000 | into datetime
Sat, 27 Feb 2021 13:55:40 +0000 (3 years ago)
```

**Comment by pzzxqj** [comment]
Thank your reply, May I ask if it has been considered as a default feature, or how do I wrap it with same command name `into datetime`?

**Comment by fdncred** [comment]
I'm not sure what you're asking. There are two examples that show how this works.
```nushell
  Convert nanosecond-precision unix timestamp to a datetime with offset from UTC
  > 1614434140123456789 | into datetime --offset -5
  Sat, 27 Feb 2021 13:55:40 +0000 (3 years ago)

  Convert standard (seconds) unix timestamp to a UTC datetime
  > 1614434140 * 1_000_000_000 | into datetime
  Sat, 27 Feb 2021 13:55:40 +0000 (3 years ago)
```

**Comment by pzzxqj** [comment]
I want to add only a second flag to `into datetime` command so that it can convert second to nanosecond while keeping original help information, flags and arguments. It's like decorator.

**Comment by fdncred** [comment]
I'm just not sure that's needed. If you know enough to do `into datetime --epoch-second` then you know enough to do `epoch * 1_000_000_000 | into datetime`.
