### ISSUE TITLE
nushell is not compatible with lowercase path on windows

### ISSUE THREAD

**Issue by mokeyish** [nushell/nushell#12676]
### Describe the bug

Some software installations seem to change Path into lowercase path, causing this BUG

### How to reproduce

1. Go to RegEditor
2. `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment`
3. Rename `Path` as `path`
4. Go to nushell, run `which which`

### Expected behavior

Make nushell compatible with lowercase path.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.92.2                                   |
| branch             |                                          |
| commit_hash        | 2a08a18b26865a86c793d183b9b042220ecb733a |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)      |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)      |
| build_time         | 2024-04-10 21:24:37 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which            |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
If either of these commands returns `path` vs `Path` on Windows, then that is a problem. I've seen it before.
```nushell
registry query --hklm 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
registry query --hkcu environment
```
I've been told a few times that Windows Path isn't case-sensitive but case-preserving. So, if some crazy program makes it `PaTh` in those locations, Windows would probably use it. Seems like a bad idea to me to have anything except `Path` on Windows.

We do have 2 PRs that try and make env vars case-insensitive, but they've bit-rotted a bit. It would be good if someone resurrected one of them and close these type of issues once and for all.

**Comment by YizhePKU** [comment]
Now that https://github.com/nushell/nushell/pull/12701 has landed, what do we think of this? Do we want to support this specific use case?

Currently, `$env.path` works, but the `which` command doesn't work because it uses `nu_engine::env::path_str()`, which fetches `Path` or `PATH` but not `path`.

**Comment by fdncred** [comment]
@YizhePKU ideally, in my perfect world, _any_ case spelling of path would work everywhere throughout all nushell commands and custom command as well as across all operating systems that we support.

**Comment by fdncred** [comment]
The problem I've seen recently is that HKCU will say `path` and HKLM will say `Path`. Having those two named different cause problems. I'm not sure how Windows works itself when they're different.

**Comment by ChrisDenton** [comment]
Windows doesn't care. Here's a silly program that illustrates how this works on Windows: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9c6ab81e8fdcb28e455ab8b6055f03b1

**Comment by fdncred** [comment]
If Windows doesn't care, we must have a bug in Nushell then. I thought we fixed that making it case insensitive but if the HKLM and HKCU are different it makes for problems. I guess it could be the rust implementation because I don't think we query any registry keys directly to get the path.
