### ISSUE TITLE
query web `--as-table` breaks (since 0.92)

### ISSUE THREAD

**Issue by wdv4758h** [nushell/nushell#12689]
### Describe the bug

You can't use `query web --as-table` without `--query` any more. The command in the examples break.

### How to reproduce

Get latest nightly nushell, run the sample command from `query web -h`, which is `http get https://en.wikipedia.org/wiki/List_of_cities_in_India_by_population | query web --as-table [City 'Population(2011)[3]' 'Population(2001)[3][a]' 'State or unionterritory' 'Ref']`.

### Expected behavior

Can use `--as-table` without `--query`

### Screenshots

![image](https://github.com/nushell/nushell/assets/2716047/87c2d998-5b93-4b65-aeb4-47fbd84a0ad9)

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.92.3                                                                          |
| major              | 0                                                                               |
| minor              | 92                                                                              |
| patch              | 3                                                                               |
| branch             | nightly                                                                         |
| commit_hash        | 24ecb84d971bf145e31bfab7615028984b4af803                                        |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                                             |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                                                 |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                                             |
| build_time         | 2024-04-28 01:44:34 +00:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | mimalloc                                                                        |
| features           | dataframe, default, sqlite, static-link-openssl, system-clipboard, trash, which |
| installed_plugins  | query                                                                           |

**Comment by wdv4758h** [comment]
Probably this part: https://github.com/nushell/nushell/blob/01d30a416b0edb1c022489d37a1448c042ce9920/crates/nu_plugin_query/src/query_web.rs#L123-L133
It forces the command to use `--query` flag, which is not the case in example or previous versions.

**Comment by wdv4758h** [comment]
I think the bug is also in 0.92. I locked my environment in 0.91, due to errors when upgrading nushell to run my scripts. Finally got time to look into the details.

**Comment by fdncred** [comment]
I've fixed this example many times. Typically, what happens is that the Wikipedia page changes slightly so the column names aren't the same anymore. I'm not sure if that's what is going on now, but that's usually what it is.

**Comment by wdv4758h** [comment]
Nope, it's not related to Wikipedia page. **Same command works in nushell 0.91. It's command parsing error since 0.92**.

Wikipedia page is not the root cause for this ticket. But I will suggest maybe use nushell governed web page as example, if that Wikipedia page changes too oftem.

**Comment by fdncred** [comment]
Yup, I think @devyn broke this by adding the `else` statement. I just put up a PR to fix it.

**Comment by fdncred** [comment]
Still works. Yay! At least it wasn't Wikipedia this time.
![image](https://github.com/nushell/nushell/assets/343840/d7fc1753-c850-4307-81af-766e8e8c0696)

**Comment by devyn** [comment]
Whoops, sorry about that. Guess I didn't read carefully enough. It would be good to add some tests, now that that's easy to do.
