### ISSUE TITLE
`from toml` with naive date results in invalid date

### ISSUE THREAD

**Issue by hardfau1t** [nushell/nushell#12699]
### Describe the bug

when bare date is specified in toml files this results in invalid date (`Thu, 1 Jan 1970 00:00:00 +0000 (54 years ago)`)
same applies for naive time.

Note: similar issue #11751 was fixed in #11846,

### How to reproduce

```nu
 [ ~ ] "dob = 2023-05-27" | from toml
╭─────┬──────────────╮
│ dob │ 54 years ago │
╰─────┴──────────────╯
[ ~ ] "dob = 2023-05-27" | from toml | get dob
Thu, 1 Jan 1970 00:00:00 +0000 (54 years ago)
```

for time
```nu
[ ~ ] "tm = 11:00:00" | from toml
╭────┬──────────────╮
│ tm │ 54 years ago │
╰────┴──────────────╯
[ ~ ] "tm = 11:00:00" | from toml | get tm
Thu, 1 Jan 1970 00:00:00 +0000 (54 years ago)
```

### Expected behavior

```nu
[ ~ ] "dob = 2023-05-27" | from toml | get dob
Sat, 27 May 2023 00:00:00 +0000 (11 months ago) 
```

Not sure what to expect from naive time

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.92.2                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 2a08a18b26865a86c793d183b9b042220ecb733a                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.77.1 (7cf61ebde 2024-03-27) (Arch Linux rust 1:1.77.1-2) |
| cargo_version      | cargo 1.77.1                                                     |
| build_time         | 2024-04-11 08:40:50 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, sqlite, trash, which                         |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment]
My guess is this is because nushell doesn't handle just a date or just a time. I believe a date or time must be a datetime with timezone.

**Comment by hardfau1t** [comment]
> My guess is this is because nushell doesn't handle just a date or just a time. I believe a date or time must be a datetime with timezone.

I am happy to create a pr for this but how do I proceed on this.

For date without time i think it is simple we can just create datetime with time set to 00:00:00 but creating bare time is a problem, otherwise we need to add `chrono::NaiveDate` and `chrono::NaiveTime`

**Comment by devyn** [comment]
I think we're unlikely to add time without date. We do have a duration type if that's how it's often used, but if not it's probably best to map it to a string or produce an error.

**Comment by ito-hiroki** [comment]
I'd like to work on this issue if no one's in charge.

**Comment by fdncred** [comment]
> I'd like to work on this issue if no one's in charge.

Go for it. I assigned it to you.
