### ISSUE TITLE
Can't pass negative float as CLI argument

### ISSUE THREAD

**Issue by wdv4758h** [nushell/nushell#12691]
### Describe the bug

See more info in discussion link.

#### Discussed in https://github.com/nushell/nushell/discussions/12473

<div type='discussions-op-text'>

<sup>Originally posted by **wdv4758h** April 11, 2024</sup>
This works:

```nu
# tmp.nu
def main [value: int] {
  print $value
}
```
```sh
nu tmp.nu -1
```

---

This does not work:

```nu
# tmp.nu
def main [value: float] {
  print $value
}
```
```sh
nu tmp.nu -1.0
```
```
Error: nu::parser::unknown_flag

  × The `main` command doesn't have flag `-1`.
   ╭─[<commandline>:1:7]
 1 │ main -1.0
   ·       ┬
   ·       ╰── unknown flag
   ╰────
  help: Available flags: --help(-h). Use `--help` for more information.
```

---

Having a .nu script file, and call that script with arguments. Not the case defining function in current nushell and call it.
For some reasons, int argument is ok, but float argument is not.

### How to reproduce

Write a nu script file with float as argument. Call it from CLI with negative float arguments.

### Expected behavior

Have a good way to pass negative float from CLI, like int.

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.92.3                                                                          |
| major              | 0                                                                               |
| minor              | 92                                                                              |
| patch              | 3                                                                               |
| branch             | nightly                                                                         |
| commit_hash        | 24ecb84d971bf145e31bfab7615028984b4af803                                        |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                                             |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                                                 |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                                             |
| build_time         | 2024-04-28 01:44:34 +00:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | mimalloc                                                                        |
| features           | dataframe, default, sqlite, static-link-openssl, system-clipboard, trash, which |
| installed_plugins  | query                                                                           |

**Comment by b-van-b** [comment]
I've noticed that you can still pass a negative value if you put it in parentheses, but only if the command has been added to nu with `def` or `use`:

```sh
# tmp.nu
export def main [value: float] {
  print $value
}
```
```sh
> nu tmp.nu (-1.5)
Error: nu::parser::unknown_flag

  × The `main` command doesn't have flag `-1`.
   ╭─[<commandline>:1:7]
 1 │ main -1.5
   ·       ┬
   ·       ╰── unknown flag
   ╰────
  help: Available flags: --help(-h). Use `--help` for more information.
``` 
```sh
  > use tmp.nu
  > tmp (-1.5)
  -1.5
```
