### ISSUE TITLE
regex returns group match as list of a single string

### ISSUE THREAD

**Issue by bmacnaughton** [nushell/nushell#12696]
### Describe the bug

whenever I use a regex in a where clause the where clause returns an empty list. while i can rearrange the code to "work", it doesn't let me select the original list entries, so i don't have the full filename i need.

### How to reproduce

Setup data
```
~\scripts\music-player> $f                                                                        04/28/2024 07:52:44 AM
╭────┬──────────────────────────────────────────────────────────────────────────────┬───────┬───────────┬──────────────╮
│  # │                                     name                                     │ type  │   size    │   modified   │
├────┼──────────────────────────────────────────────────────────────────────────────┼───────┼───────────┼──────────────┤
│  0 │ z:\flac\Nirvana\Nevermind\Nirvana-Nevermind-01-Smells Like Teen Spirit.flac  │ file  │  34.6 MiB │ 16 years ago │
│  1 │ z:\flac\Nirvana\Nevermind\Nirvana-Nevermind-02-In Bloom.flac                 │ file  │  30.2 MiB │ 16 years ago │
│  2 │ z:\flac\Nirvana\Nevermind\Nirvana-Nevermind-03-Come as You Are.flac          │ file  │  24.0 MiB │ 16 years ago │
╰────┴──────────────────────────────────────────────────────────────────────────────┴───────┴───────────┴──────────────╯
```

execute selection without regex in where clause (expected result)
```
~\scripts\music-player> $f | get name | parse -r '^(.+)(-\d{2}-)(.+)\.flac$' | get capture2 | where ( str contains -i 'om' )
╭───┬─────────────────╮
│ 0 │ In Bloom        │
│ 1 │ Come as You Are │
╰───┴─────────────────╯
```

execute selection with regex in where clause (incorrect result)
```
~\scripts\music-player> $f | where (get name | parse -r '^(.+)(-\d{2}-)(.+)\.flac$' | get capture2 | str contains 'om')
╭────────────╮
│ empty list │
╰────────────╯
```

with `inspect` showing that the value of the pipeline is correct but is not being honored by the `where` clause:
```
~\scripts\music-player> $f | where (get name | parse -r '^(.+)(-\d{2}-)(.+)\.flac$' | get capture2 | str contains 'om' | inspect )
╭─────────────┬────────────╮
│ description │ list<bool> │
├─────────────┴────────────┤
│                          │
├──────────────────────────┤
│ false                    │
╰──────────────────────────╯

╭─────────────┬────────────╮
│ description │ list<bool> │
├─────────────┴────────────┤
│                          │
├──────────────────────────┤
│ true                     │
╰──────────────────────────╯

╭─────────────┬────────────╮
│ description │ list<bool> │
├─────────────┴────────────┤
│                          │
├──────────────────────────┤
│ true                     │
╰──────────────────────────╯

╭────────────╮
│ empty list │
╰────────────╯
```

### Expected behavior

I expect this result:
```
~\scripts\music-player> $f | where (get name | parse -r '^(.+)(-\d{2}-)(.+)\.flac$' | get capture2 | str contains 'om')
╭──────┬────────────────────────────────────────────────────────────────────────┬────────┬────────────┬────────────────╮
│    # │                                  name                                  │  type  │    size    │    modified    │
├──────┼────────────────────────────────────────────────────────────────────────┼────────┼────────────┼────────────────┤
│    0 │ z:\flac\Nirvana\Nevermind\Nirvana-Nevermind-02-In Bloom.flac           │ file   │   30.2 MiB │ 16 years ago   │
│    1 │ z:\flac\Nirvana\Nevermind\Nirvana-Nevermind-03-Come as You Are.flac    │ file   │   24.0 MiB │ 16 years ago   │
╰──────┴────────────────────────────────────────────────────────────────────────┴────────┴────────────┴────────────────╯
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.92.2                                   |
| branch             |                                          |
| commit_hash        | 2a08a18b26865a86c793d183b9b042220ecb733a |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)      |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)      |
| build_time         | 2024-04-10 21:24:37 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which            |
| installed_plugins  |                                          |

### Additional context

I have tested this on linux as well and get the same results.

**Comment by bmacnaughton** [comment]
the problem seems to be that `parse` returns a list of string `[string]` for each group. that is passed to `str contains` which returns a list of bool `[bool]` and that is interpreted by `where` (or `filter`) as `false`. but `inspect` interprets `[bool]` as `true` or `false` when it displays the value.

i don't believe that `parse` capture groups should be `[string]` - they should just be `string`.

**Comment by fdncred** [comment]
Is this any better?
```nushell
❯ $f | where ($it.name | parse -r '^(.+)(-\d{2}-)(.+)\.flac$' | get 0.capture2 | str contains 'om')
╭─#─┬────────────────────────────────name─────────────────────────────────╮
│ 0 │ z:\flac\Nirvana\Nevermind\Nirvana-Nevermind-02-In Bloom.flac        │
│ 1 │ z:\flac\Nirvana\Nevermind\Nirvana-Nevermind-03-Come as You Are.flac │
╰───┴─────────────────────────────────────────────────────────────────────╯
```
or
```nushell
❯ $f | filter { |r| $r.name | parse -r '^(.+)(-\d{2}-)(.+)\.flac$' | get 0.capture2 | str contains 'om'}
╭─#─┬────────────────────────────────name─────────────────────────────────╮
│ 0 │ z:\flac\Nirvana\Nevermind\Nirvana-Nevermind-02-In Bloom.flac        │
│ 1 │ z:\flac\Nirvana\Nevermind\Nirvana-Nevermind-03-Come as You Are.flac │
╰───┴─────────────────────────────────────────────────────────────────────╯
```
Seems like it's not quite what you're looking for.

**Comment by fdncred** [comment]
Maybe this is a little closer. Thinking about it in a little different way.
```nushell
❯ $f | find -r om | get name | parse -r '^(?<path>.+)(?<track>-\d{2}-)(?<title>.+)\.flac$' | get title
╭───┬─────────────────╮
│ 0 │ In Bloom        │
│ 1 │ Come as You Are │
╰───┴─────────────────╯
```

**Comment by bmacnaughton** [comment]
> Seems like it's not quite what you're looking for.

both of those work because they do `get 0` to take the string out of the list. and they leave me with the full path (needed to play the music).

> Maybe this is a little closer. Thinking about it in a little different way.

this approach loses the full path and song titles can be ambiguous/duplicated, so the first two are better.

i appreciate your suggestions and am using an approach similar to the first two you suggested.

the underlying issue is that it seems wrong that `'string-of-some-sort' | parse -r 'regex(group)' returns each group as a list. i don't think they can be nested (even though the groups in the regex can be, the results always are linear, ordered by the regex group's opening paren). but maybe i'm missing something about the design and they can be nested?

**Comment by fdncred** [comment]
> this approach loses the full path and song titles can be ambiguous/duplicated, so the first two are better.

I thought that's what you wanted as stated above?

If you want the full path then `$f | find om` would work.

**Comment by bmacnaughton** [comment]
> If you want the full path then $f | find om would work.

but i only want to filter on song title matches, not the whole path - that includes the artist and album name.

> I'm not as convinced as you are that something is wrong

i could be wrong, but i see no use case for returning what is *always* going to be a single string as `[string]`. i don't believe that it's possible for the result of a group in a regex to be anything other than a string.

**Comment by bmacnaughton** [comment]
i'm sorry this is a bit confusing - i created the issue before i found that the issue was that `parse` returns groups as `[string]`, so the issue description and title were off. i can go back and fix the issue description if that would help.

**Comment by fdncred** [comment]
Here's another way that maintains the original file name for playing and inserts the parsed columns for searching.
```nushell
❯ $f | upsert split {|r| $r.name | parse -r '^(?<path>.+)(?<track>-\d{2}-)(?<title>.+)\.flac$'} | flatten --all | where title =~ om                 5  04:53:59 PM
╭─#─┬────────────────────────────────name─────────────────────────────────┬────────────────────path─────────────────────┬track─┬──────title──────╮
│ 0 │ z:\flac\Nirvana\Nevermind\Nirvana-Nevermind-02-In Bloom.flac        │ z:\flac\Nirvana\Nevermind\Nirvana-Nevermind │ -02- │ In Bloom        │
│ 1 │ z:\flac\Nirvana\Nevermind\Nirvana-Nevermind-03-Come as You Are.flac │ z:\flac\Nirvana\Nevermind\Nirvana-Nevermind │ -03- │ Come as You Are │
╰───┴─────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────┴──────┴─────────────────╯
```

**Comment by bmacnaughton** [comment]
two things i haven't used before `upsert` and `flatten`.  `upsert` is particularly nice!

for me the open question is whether `flatten` should be required at all. maybe this will all become intuitive to me after a while, but i see that it's a table of records where each property of the record is a string. so when i fetch the property, say `capture0`, i expect a string because the pipeline is operating on one row at a time.

```
~\scripts\music-player> 'xyzzy-99-something' | parse -r '(.+)-(\d{2})-(.+)' | inspect             04/28/2024 03:10:40 PM
╭─────────────┬─────────────────────────────────────────────────────────────╮
│ description │ table<capture0: string, capture1: string, capture2: string> │
├─────────────┴──────────┬────────────────────────┬─────────────────────────┤
│ capture0               │ capture1               │ capture2                │
├────────────────────────┼────────────────────────┼─────────────────────────┤
│ xyzzy                  │ 99                     │ something               │
╰────────────────────────┴────────────────────────┴─────────────────────────╯
```

but when i do that, i get `list<string>`:
```
~\scripts\music-player> 'xyzzy-99-something' | parse -r '(.+)-(\d{2})-(.+)' | get capture0 | inspect
╭─────────────┬──────────────╮
│ description │ list<string> │
├─────────────┴──────────────┤
│                            │
├────────────────────────────┤
│ xyzzy                      │
╰────────────────────────────╯
```

i guess i'm just thinking about it incorrectly. nu's pipeline is returning a list of the *one* possible groups. so i've been thinking about it as the *input* of an operation and nu is presenting it as the *output* (which will typically be multiple items).

```
~\scripts\music-player> ['xyzzy-99-something' 'xxx-42-huh' ]| parse -r '(.+)-(\d{2})-(.+)' | inspect | get capture0 | in
spect
╭─────────────┬─────────────────────────────────────────────────────────────╮
│ description │ table<capture0: string, capture1: string, capture2: string> │
├─────────────┴──────────┬────────────────────────┬─────────────────────────┤
│ capture0               │ capture1               │ capture2                │
├────────────────────────┼────────────────────────┼─────────────────────────┤
│ xyzzy                  │ 99                     │ something               │
│ xxx                    │ 42                     │ huh                     │
╰────────────────────────┴────────────────────────┴─────────────────────────╯

╭─────────────┬──────────────╮
│ description │ list<string> │
├─────────────┴──────────────┤
│                            │
├────────────────────────────┤
│ xyzzy                      │
│ xxx                        │
╰────────────────────────────╯

╭───┬───────╮
│ 0 │ xyzzy │
│ 1 │ xxx   │
╰───┴───────╯
```

i still find it odd, but am kind of getting my head around it.
