### ISSUE TITLE
from-md / to-md

### ISSUE THREAD

**Issue by yoshuawuyts** [nushell/nushell#1270]
**Is your feature request related to a problem? Please describe.**
It's quite common I want to quickly update some formatting in markdown. Whether it's inserting a new section, rewriting another, or reordering sections. Operating on markdown is often something that's nice to be able to do quickly, yet there are few tools that allow doing for this.

**Describe the solution you'd like**
I'd love for there to be `to-markdown` / `from-markdown` tools. I don't know of any markdown tools that work this way, but the way I think of markdown is as a hierarchy. `h1 > h2 > [ p, p, p ]` would be written as:

```markdown
# heading 1
## heading 2

paragraph 1

paragraph 2
```

Key-value stores could then be represented as markdown tables (https://github.com/nushell/nushell/issues/1183); arrays as lists. We'd probably need to try some things out.

**Describe alternatives you've considered**
I haven't found any good tools for quickly editing and updating markdown from the command line. There exist parsers that kind of work this way in Node.js, but to my knowledge there's not much prior art. Perhaps the closest is the way DOM selectors work, but those don't work on markdown input.

**Additional context**
I wanted to select [this code block](https://github.com/yoshuawuyts/speaking#talks) and reverse it, and realized having a tool would've made that really easy. But throwing something together is too slow, and if nu spoke markdown it'd be an excellent fit for it!

**Comment by jonathandturner** [comment]
@yoshuawuyts I like it :)  Might have to play with how it could work in practice, but in theory that's in line with the kinds of things we're talking about. Being able to load up a source file and get information about what's defined in it will be a big help for coding tools built in Nu in the future.

**Comment by JesterOrNot** [comment]
There are libraries that can do this https://crates.io/crates/pulldown-cmark if we add it I could pretty easily add some nu commands for it. @jonathandturner would you be opposed to adding another dependency?

**Comment by jonathandturner** [comment]
@JesterOrNot I'm okay with adding a dependency.

We've got `to-md` now, you might want to look into that (it probably could use improvements :D). We don't have a `from-md`, yet.

**Comment by JesterOrNot** [comment]
OK!

**Comment by JesterOrNot** [comment]
Wait from-md converts md to html right?

**Comment by jonathandturner** [comment]
@JesterOrNot  - I think the idea is that `from-md` would read in a markdown file and look for tables, then return those as structured values to Nu.

Like `from-json` reads in a json file and give you the values

**Comment by thegedge** [comment]
Another option would be to parse it as if it were hierarchical data:

```markdown
# Section 1
Some text

## Subsection 1
Subsection text a

## Subsection 2
Subsection text b

# Section 2
Some text
```

And maybe have that produce something like 

| sections  |    paragraphs   |    subsections   |
|-----------|-----------------|------------------|
| Section 1 | `[table 1 row]` | `[table 2 rows]` |
| Section 2 | `[table 1 row]` |                  |

**Comment by jonathandturner** [comment]
You probably want more than just tables, but it's a start.  The original request has more info you could get ideas from.

Doing it this way lets you do things like `from-md | to-html` and do the conversion you were suggesting

**Comment by jonathandturner** [comment]
@thegedge that's a good idea!

**Comment by thegedge** [comment]
Similar issue, which I'll close as a dupe: https://github.com/nushell/nushell/issues/1183

**Comment by empea-careercriminal** [comment]
Is this still a feature that makes sense to build or do solutions exist already?

**Comment by sholderbach** [comment]
`to md` exists and makes some guesses how to format a datastructure as text. `from md` does not exist at the moment and it might be unclear what its behavior should be. A more narrow specialization on stripping a table of formatting like suggested with #1183 might be a worthwhile addition.

**Comment by jarrodu** [comment]
I was just looking for this feature. Maybe the issue could be reopened. It has been a while since people have talked about it.

**Comment by sholderbach** [comment]
Reopening this issue as we had some fruitful discussions around the possible mapping from structured data to markdown and back here.

I personally think that it may be worth demonstrating the `from md` behavior in a plugin first before we decide on landing it in the core Nushell as there may be some iteration necessary before everyone is happy with opinionated decisions around how the unstructured data should be parsed to structured data.

**Comment by sholderbach** [comment]
Closing this as we haven't seen a clear strategy to parse arbitrary markdown and would like to see such an opinionated parser as a plugin first. In general we are now much more in favor of those things starting out as plugins/modules in the community before considering a move into the core.

**Comment by YPares** [comment]
A quick addition to just deal with markdown tables would be to add `--padding: string` and `--skip: range` args to `from csv`.
Because a markdown table is very much a CSV with '|' as a separator, extra '|' at the beginning and end of each line, and an extra "horizontal bar" line right beneath the headers.

So parsing a markdown table would be:
```
$str | from csv -s '|' --padding '|' --skip (1..1)
```
