### ISSUE TITLE
Error when trying to use "into sqlite" when column names contain spaces

### ISSUE THREAD

**Issue by john-boxcar** [nushell/nushell#12700]
### Describe the bug

When column names in a table contain spaces (common in CSV files) I get an error when trying to pipe
 this data into sqlite.

### How to reproduce

Create a file named test.csv which contains the following:
```csv
Column 1,Column 2
value1,value2
```

Run one of the following commands:
`open test.csv --raw | from csv | into sqlite test.db`
`cat test.csv | from csv | into sqlite test.db`

I can work around this error as follows:
`cat test.csv | sed '1 s/ /_/g' | from csv | into sqlite test.db`

### Expected behavior

The "into sqlite" command should automatically handle spaces in column names appropriately.

### Screenshots

![image](https://github.com/nushell/nushell/assets/161479879/12be213f-503c-46c1-a880-f4d84dcd8065)

### Configuration

| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.92.2                                         |
| branch             |                                                |
| commit_hash        |                                                |
| build_os           | linux-x86_64                                   |
| build_target       | x86_64-unknown-linux-gnu                       |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09) (Homebrew) |
| cargo_version      | cargo 1.77.2                                   |
| build_time         | 2024-04-10 21:15:51 +00:00                     |
| build_rust_channel | release                                        |
| allocator          | mimalloc                                       |
| features           | dataframe, default, sqlite, trash, which       |
| installed_plugins  |                                                |

**Comment by fdncred** [comment]
You'll also get a similar problem if your columns have dots in them like `Column.1`.

**Comment by Arian-D** [comment]
I don't know much rust, but I believe the issue is stemming from [here](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/database/commands/into_sqlite.rs#L272-L273) where the column names are not enclosed in backticks, single quotes, or double quotes.

I'm not sure what the right approach is, but at the very least I can tell you arbitrarily enclosing them in some character is not the best approach. For a funny example, in `somefile.db` try
```sql
CREATE TABLE weirdtable (`"` TEXT, "'" TEXT, '`' TEXT); /* valid */
INSERT INTO test2 (""", "'", "`") VALUES (1, 2, 3);  /* breaks */
INSERT INTO test2 (`"`, `'`, ```) VALUES (1, 2, 3);  /* breaks */
INSERT INTO test2 ('"', ''', '`') VALUES (1, 2, 3);  /* breaks */
```

**Comment by fdncred** [comment]
I think I'd like invalid characters like space and dot/period to be replaced with underscore for table names. I'm not sure that's the "right" thing to do but it's the first thing that comes to mind. If column names have a dot, we won't be able to query them easily and spaces are just a pain.

**Comment by ExaltedBagel** [comment]
Hello, new kid here! I took a quick look and it and it seems like quoting the column names solves the issues. Note that I picked up Rust last week, so I may be doing weird things with iterators. See PR https://github.com/nushell/nushell/pull/12759 for more info!
