### ISSUE TITLE
NU_LOG_LEVEL environment variable is ignored

### ISSUE THREAD

**Issue by PanieriLorenzo** [nushell/nushell#12707]
### Describe the bug

In version 0.92.2 (homebrew), the `NU_LOG_LEVEL` environment variable does not seem to affect what log levels are printed. For instance, setting `NU_LOG_LEVEL=ERROR` and then running `log info "hello"` still prints the log line. If this is intended then the [documentation](https://www.nushell.sh/book/stdout_stderr_exit_codes.html#echo-print-and-log-commands) is misleading or outdated.

### How to reproduce

Run the example from the [documentation](https://www.nushell.sh/book/stdout_stderr_exit_codes.html#echo-print-and-log-commands) verbatim

1. Make a file called `std_log.nu` with these contents:
```nu
use std log

def main [] {
    log debug "Debug message"
    log info "Info message"
    log warning "Warning message"
    log error "Error message"
    log critical "Critical message"
}
```

2. run the following in a POSIX shell (I used Bash)
```sh
NU_LOG_LEVEL=DEBUG nu std_log.nu
```

3. see that the message "Debug message" is not displayed, despite the log level being DEBUG.

Another smaller example:
```bash
$ NU_LOG_LEVEL=WARN nu -c 'use std log; log info "hello"'
```

Expected this to print nothing.

### Expected behavior

Expected `NU_LOG_LEVEL` to affect the printing of log messages of various levels, such as `NU_LOG_LEVEL=ERROR` disabling `DEBUG`, `INFO` and `WARN` messages.

### Configuration

| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.92.2                                         |
| branch             |                                                |
| commit_hash        |                                                |
| build_os           | linux-x86_64                                   |
| build_target       | x86_64-unknown-linux-gnu                       |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09) (Homebrew) |
| cargo_version      | cargo 1.77.2                                   |
| build_time         | 2024-04-10 21:15:51 +00:00                     |
| build_rust_channel | release                                        |
| allocator          | mimalloc                                       |
| features           | dataframe, default, sqlite, trash, which       |
| installed_plugins  |                                                |

### Additional context

Tested in a fresh Docker container and had the same issue:

```bash
docker run -it homebrew/brew
```

In docker container:
```bash
brew install nushell
nu --version    # 0.92.2
NU_LOG_LEVEL=WARN nu -c 'use std log; log info "hello"'
```

Expected nothing to be printed, but get "hello" anyway.

**Comment by amtoine** [comment]
@PanieriLorenzo 
i believe this should have been fixed in https://github.com/nushell/nushell/pull/12470 and should be released in 0.93.0 very soon today :wink: 

please feel free to ping here to reopen the issue if i was wrong or if it persists :relieved:
