### ISSUE TITLE
`glob` command doesn't accept glob argument type

### ISSUE THREAD

**Issue by dedebenui** [nushell/nushell#12716]
### Describe the bug

The glob command doesn't accept arguments that have been converted with `into glob`

### How to reproduce

```nushell
let pattern = [Desktop *] | path join | into glob
glob $pattern
```

I get the following error:
```
Error: nu::shell::cant_convert

  × Can't convert to string.
   ╭─[entry #8:2:6]
 1 │ let pattern = [Desktop *] | path join | into glob
 2 │ glob $pattern
   ·      ────┬───
   ·          ╰── can't convert glob to string
   ╰────
```

### Expected behavior

I expect the same output as `glob Desktop/*`

```
╭───┬───────────────────────────╮
│ 0 │ /Users/john/Desktop/file1 │
│ 1 │ /Users/john/Desktop/file2 │
│ 2 │ /Users/john/Desktop/file3 │
╰───┴───────────────────────────╯
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.93.0                                          |
| major              | 0                                               |
| minor              | 93                                              |
| patch              | 0                                               |
| branch             | main                                            |
| commit_hash        | cb6d495e0203663544c25d9696dc1626abd0e709        |
| build_os           | macos-aarch64                                   |
| build_target       | aarch64-apple-darwin                            |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-aarch64-apple-darwin                     |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-05-01 08:27:15 +02:00                      |
| build_rust_channel | debug                                           |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                 |

### Additional context

The bug is not present with `ls`:
```nushell
> let pattern = [Desktop *] | path join | into glob
> ls $pattern
╭───┬───────────────┬──────┬───────────┬────────────╮
│ # │      name     │ type │   size    │  modified  │
├───┼───────────────┼──────┼───────────┼────────────┤
│ 0 │ Desktop/file1 │ file │ 213.3 KiB │ 2 days ago │
│ 1 │ Desktop/file2 │ file │  45.5 KiB │ a week ago │
│ 2 │ Desktop/file3 │ file │  45.5 KiB │ a week ago │
╰───┴───────────────┴──────┴───────────┴────────────╯
```

**Comment by fdncred** [comment]
Right, the `glob` command wants a string pattern, not a glob, and then it does its own globbing. The `glob` command uses a completely different globbing crate than anything else in nushell.

For your example, this should work, since it's asking for a string.
```nushell
let pattern = [Desktop *] | path join
glob $pattern
```

**Comment by FulecoRafa** [comment]
Hello, first time contributing and I would like to work on this issue

**Comment by fdncred** [comment]
> Maybe we could first update [the doc](https://www.nushell.sh/lang-guide/chapters/types/basic_types/glob.html#casts) to reflect this, as the doc currently states this as an example to show the `glob` type is the first class object.

Agreed. That should be `ls $g` instead of `glob $g`.

**Comment by hjetmundsen** [comment]
Is this issue fixed? I just tried this with the latest source and I can't reproduce the issue.
