### ISSUE TITLE
0.93.0 compilation failure on NetBSD current

### ISSUE THREAD

**Issue by 0323pin** [nushell/nushell#12724]
### Describe the bug

0.93.0 fails to compile on NetBSD x86_64 with:
```
error[E0432]: unresolved import `libc::xucred`
  --> /usr/pkgsrc/wip/nushell/work/vendor/interprocess-1.2.1/src/os/unix/imports.rs:45:24
   |
45 |         pub(super) use libc::xucred;
   |                        ^^^^^^------
   |                        |     |
   |                        |     help: a similar name exists in the module: `uucred`
   |                        no `xucred` in the root

   Compiling parking_lot_core v0.9.9
For more information about this error, try `rustc --explain E0432`.
error: could not compile `interprocess` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

### How to reproduce

Source build of the new 0.93.0 release. v0.92.2 compiles without issues.

### Expected behavior

Successful build.

### Screenshots

NA

### Configuration

NA

### Additional context

```
~> name -rsv
NetBSD 10.99.10 NetBSD 10.99.10 (GENERIC) #0: Thu Apr 25 22:39:14 CEST 2024  pin@mybox:/home/pin/obj/sys/arch/amd64/compile/GENERIC
~> pkg_info | grep rust
rust-1.77.2         Safe, concurrent, practical language
```

**Comment by 0323pin** [comment]
The following patch fixes the build on NetBSD but, it might break other platforms,
```
+++ ../vendor/interprocess-1.2.1/src/os/unix/imports.rs
@@ -41,8 +41,8 @@ pub(super) use libc::{
 cfg_if! {
     if #[cfg(uds_ucred)] {
         pub(super) use libc::ucred;
-    } else if #[cfg(uds_xucred)] {
-        pub(super) use libc::xucred;
+    } else if #[cfg(uds_uucred)] {
+        pub(super) use libc::uucred;
         pub struct ucred {}
     } else {
         pub struct ucred {}
```

I'll try to re-work the conditional.

**Comment by 0323pin** [comment]
Actually, this only needs a version bump to `interprocess`-2.0.0, as the issue is fixed within the crate. Building the latest version standalone yields:

```
~> cd Downloads/interprocess-2.0.0
~> cargo build --release
    Updating crates.io index
  Downloaded libc v0.2.153
  Downloaded 1 crate (740.6 KB) in 0.59s
   Compiling libc v0.2.153
   Compiling interprocess v2.0.0 (/home/pin/Downloads/interprocess-2.0.0)
    Finished release [optimized] target(s) in 10.03s
```

**Comment by devyn** [comment]
I'll try to update `interprocess`. The release must have been very recent. I thought I had tried running with local sockets on FreeBSD and it was all okay, but maybe I'm misremembering.

Anyway, thanks for the report, happy to try to fix this.

**Comment by devyn** [comment]
I created a PR for interprocess 2.0.0. It's a little bit of a breaking change.

I totally misread this and thought it was FreeBSD, not NetBSD. It probably did work on FreeBSD, and that's why I got confused. I'll test there though.

**Comment by devyn** [comment]
My PR works for NetBSD, so I think we'll have this fixed in the next release.

**Comment by 0323pin** [comment]
Just woke-up. Awesome progress :)

> My PR works for NetBSD ...

So, you don't need me to test build and run on NetBSD?

**Comment by devyn** [comment]
If you'd like to it can't hurt. My installation is extremely bare-bones, so it would be good to see if it also works for someone who uses it regularly. Thanks!

**Comment by 0323pin** [comment]
Thank you!

> If you'd like to it can't hurt. My installation is extremely bare-bones, so it would be good to see if it also works for someone who uses it regularly.

I can confirm your PR fixes the build on NetBSD.

![2024-05-02-082523_1366x768_scrot](https://github.com/nushell/nushell/assets/90570748/e7fdac67-5dd1-47fe-a07c-d4795ad9e602)

**Comment by 0323pin** [comment]
Btw, I've merged the update to 0.93.0 into the main branch now using the following patch:
```
$NetBSD: patch-..vendor_interprocess-1.2.1_src_os_unix_imports.rs,v 1.1 2024/05/02 08:08:51 pin Exp $

NetBSD has uucred and not xucred.

--- ../vendor/interprocess-1.2.1/src/os/unix/imports.rs.orig	2024-05-02 07:34:36.709869722 +0000
+++ ../vendor/interprocess-1.2.1/src/os/unix/imports.rs
@@ -39,11 +39,14 @@ pub(super) use libc::{
 };
 
 cfg_if! {
-    if #[cfg(uds_ucred)] {
+        if #[cfg(uds_ucred)] {
         pub(super) use libc::ucred;
-    } else if #[cfg(uds_xucred)] {
+    } else if #[cfg(all(uds_xucred, not(target_os = "netbsd")))] {
         pub(super) use libc::xucred;
         pub struct ucred {}
+    } else if #[cfg(all(uds_uucred, target_os = "netbsd"))] {
+        pub(super) use libc::uucred;
+        pub struct ucred {}
     } else {
         pub struct ucred {}
     }
```

**Comment by 0323pin** [comment]
@devyn I see 👀 ...
The patch is temporary, until your PR is merged. Didn't want to leave our package out-of-date.

**Comment by devyn** [comment]
@0323pin oh, sorry, maybe I use :eyes: differently. I just meant I read it, not that I thought anything was unusual :slightly_smiling_face: 

A temporary patch sounds perfectly fine, and thanks for letting us know so we could come up with a solution. It sounds like that version of `interprocess` also caused issues for some other architectures - Termux had to do a patch for `socklen_t` because the code was assuming it was always `u32`, but it's `i32` on 32-bit platforms for them (not sure about NetBSD).

Hopefully 2.0.0 has more of the quirks worked out in general - so far, that does seem to be the case.
