### ISSUE TITLE
Raw strings inside of parentheses are not processed correctly.

### ISSUE THREAD

**Issue by maxim-uvarov** [nushell/nushell#12744]
### Describe the bug

[Raw strings](https://github.com/nushell/nushell/pull/9956) inside of parentheses are not processed correctly.

### How to reproduce

type in repl or use in script: 
```
print (r#'test'#)
```

### Expected behavior

to accept a raw string as a string

### Screenshots

![raw-strings](https://github.com/nushell/nushell/assets/4896754/1b57d4e0-926c-4444-9598-ae6f207f95c4)

### Configuration

| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.93.1                                                     |
| major              | 0                                                          |
| minor              | 93                                                         |
| patch              | 1                                                          |
| branch             | main                                                       |
| commit_hash        | bc6d934fa130962f9b5017477eaa6e52daea3d8c                   |
| build_os           | macos-aarch64                                              |
| build_target       | aarch64-apple-darwin                                       |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                        |
| rust_channel       | 1.77.2-aarch64-apple-darwin                                |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                        |
| build_time         | 2024-05-03 04:24:17 +00:00                                 |
| build_rust_channel | release                                                    |
| allocator          | mimalloc                                                   |
| features           | dataframe, default, sqlite, system-clipboard, trash, which |
| installed_plugins  | explore, image, inc, polars                                |

**Comment by fdncred** [comment]
Thanks @maxim-uvarov. Keep 'em coming. It's new so I kind of expect there to be edge cases that we missed.
