### ISSUE TITLE
nightly 2024-05-04 : Error `$env.PWD contains trailing slashes`

### ISSUE THREAD

**Issue by woosaaahh** [nushell/nushell#12758]
### Describe the bug

Hi everyone !

I'm currently trying the last Nightly release `2024-05-04 35a0f7a36991ab7ec3b4da5c6e681de240d58526`.

I tried to `cd` into a directory and used the paths completion to help me writing the full path.
After executing the `cd` command, I get an error `$env.PWD contains trailing slashes`.
Every other commands fail after this issue, even the `exit` one.

### How to reproduce

Here is an example

```sh
> cd ~/.config/nushell/
Error:   × $env.PWD contains trailing slashes


Error:   × $env.PWD contains trailing slashes


Error:   × $env.PWD contains trailing slashes


Error:   × $env.PWD contains trailing slashes


Error:   × $env.PWD contains trailing slashes


> ls
Error:   × $env.PWD contains trailing slashes


(repeated 4 more times)
> exit
Error:   × $env.PWD contains trailing slashes




(repeated 4 more times)
```

### Expected behavior

No error.

### Screenshots

Here is a recording from @132ikl (rose on discord) : https://asciinema.org/a/SPqtjP9bTlASL53Qr6ZYkX9ZI

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.93.1                                                                          |
| major              | 0                                                                               |
| minor              | 93                                                                              |
| patch              | 1                                                                               |
| branch             | nightly                                                                         |
| commit_hash        | 35a0f7a36991ab7ec3b4da5c6e681de240d58526                                        |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-musl                                                       |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                                             |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                                                 |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                                             |
| build_time         | 2024-05-04 01:34:12 +00:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | mimalloc                                                                        |
| features           | dataframe, default, sqlite, static-link-openssl, system-clipboard, trash, which |
| installed_plugins  |                                                                                 |

**Comment by devyn** [comment]
I believe this was caused by #12662
