### ISSUE TITLE
`nu-highlight` from the latest main produces unneded output

### ISSUE THREAD

**Issue by maxim-uvarov** [nushell/nushell#12792]
### Describe the bug

Hello! First of all, do maintainers expect to receive issues on the latest development build from Nushell? If not, please disregard this message. If yes, the issue is provided below.

I compiled the latest version of Nushell from the main branch.
And now I'm getting a strange result with `nu-highlight` and an example from the Nushell book.

```nu
> let x = [1 2]
> "> [...$x 3 ...(4..7 | take 2)]" | nu-highlight
```

output:
```
> [...$x 3 ...(4...7 | take 2) ...(4..7 | take 2)]
```

### How to reproduce

```nu
> let x = [1 2]
> "> [...$x 3 ...(4..7 | take 2)]" | nu-highlight
```

### Expected behavior

to output exactly the contents of a string

### Screenshots

<img width="603" alt="image" src="https://github.com/nushell/nushell/assets/4896754/cdd819aa-ad1b-4f33-9128-4e930c5e73e9">

### Configuration

| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.93.1                                                     |
| major              | 0                                                          |
| minor              | 93                                                         |
| patch              | 1                                                          |
| branch             | main                                                       |
| commit_hash        | bc6d934fa130962f9b5017477eaa6e52daea3d8c                   |
| build_os           | macos-aarch64                                              |
| build_target       | aarch64-apple-darwin                                       |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                        |
| rust_channel       | 1.77.2-aarch64-apple-darwin                                |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                        |
| build_time         | 2024-05-03 04:24:17 +00:00                                 |
| build_rust_channel | release                                                    |
| allocator          | mimalloc                                                   |
| features           | dataframe, default, sqlite, system-clipboard, trash, which |
| installed_plugins  | explore, image, inc, polars                                |

**Comment by IanManske** [comment]
> First of all, do maintainers expect to receive issues on the latest development build from Nushell? If not, please disregard this message.

Yes, thank you for reporting this! I just opened a PR that should hopefully fix this.
