### ISSUE TITLE
Bad record with unclosing quotes cause unhelpful error messages (need better error messages)

### ISSUE THREAD

**Issue by wdv4758h** [nushell/nushell#12795]
### Describe the bug

```nu
def func [] {
  {
    "A": ""B"   # <- the quote is bad
  }
}

def main [] {
}
```

```
Error: nu::parser::unexpected_eof

  × Unexpected end of code.
   ╭─[/tmp/error.nu:9:1]
 8 │ }
   ╰────
```

### How to reproduce

Run above code.

### Expected behavior

Show some helpful error messages pointing that bad quote line.

For comparison, here is the error messages from Python for similar case:
```python
  File "/tmp/error.py", line 3
    "A": ""B"
           ^
SyntaxError: unterminated string literal (detected at line 3)
```

It will be helpful if nushell can output error messages like this. The showcase is dumb, but I notice this kind off issue is hard to find when code gets bigger.

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.93.0                                                                          |
| major              | 0                                                                               |
| minor              | 93                                                                              |
| patch              | 0                                                                               |
| branch             |                                                                                 |
| commit_hash        | 3b220e07e3e3652bc722d4bc8370f2413df69473                                        |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                                             |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                                                 |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                                             |
| build_time         | 2024-04-30 23:06:38 +00:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | mimalloc                                                                        |
| features           | dataframe, default, sqlite, static-link-openssl, system-clipboard, trash, which |
| installed_plugins  | query                                                                           |

**Comment by bew** [comment]
Well, Python can give this quick error because it does not support multiline strings like
```
"foo
bar
baz"
```
which nushell does support.

**Comment by wdv4758h** [comment]
I don't think multiline support is a good reason to have bad error messages. Python output better error messages even with the `"""` multiline string. It shows the source of line that quote does not close. And actually, that's is not the case in much older Python versions. It needs effor to improve error messages. Raw parsing error sometime is not helpful enough.

Not an expert of nushell parser, but I will guess nushell parser has the context that which line the quote begins and doesn't close.

**Comment by WindSoilder** [comment]
Well, `unexpected_eof` is the key to allow multi-line string.  You can define a function like this:
```nushell
def func [] {
   {
     "A": ""B"   # <- the quote is bad
   }
 }"
 }
 }
```
But I agree that the error message can be better.
