### ISSUE TITLE
`complete` does not work with `o+e>|` operator

### ISSUE THREAD

**Issue by PigeonF** [nushell/nushell#12796]
### Describe the bug

When using `run-external` with `o+e>|`, `combine` still separates `stdout` and `stderr`. I am not sure if this is intended behaviour. For context, I am trying to get the interleaved stdout and stderr of an external program, so that I can faithfully reproduce the order of the external programs output.

### How to reproduce

```console
run-external nu "-c" "print STDOUT1; print -e STDERR1; print STDOUT2; print -e STDERR2" o+e>| complete
```

### Expected behavior

I would expect nushell to either warn that the redirection does not work with `complete`, or for the redirection to affect the result of `complete`.

### Screenshots

![Screenshot 2024-05-07 122349](https://github.com/nushell/nushell/assets/7536431/57709c9f-eec5-49f9-9ceb-193685cfa3a5)

### Configuration

| key                | value                                                                |
| ------------------ | -------------------------------------------------------------------- |
| version            | 0.93.0                                                               |
| major              | 0                                                                    |
| minor              | 93                                                                   |
| patch              | 0                                                                    |
| branch             |                                                                      |
| commit_hash        | 3b220e07e3e3652bc722d4bc8370f2413df69473                             |
| build_os           | linux-x86_64                                                         |
| build_target       | x86_64-unknown-linux-gnu                                             |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                                  |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                                      |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                                  |
| build_time         | 2024-04-30 22:58:28 +00:00                                           |
| build_rust_channel | release                                                              |
| allocator          | mimalloc                                                             |
| features           | default, sqlite, static-link-openssl, system-clipboard, trash, which |
| installed_plugins  |                                                                      |

**Comment by fdncred** [comment]
I'm not sure what you're saying. The output looks right to me, `complete` is always going to group stdout together and stderr together, that's what it is supposed to do.

```
❯ run-external nu "-c" "print STDOUT1; print -e STDERR1; print STDOUT2; print -e STDERR2" o+e>| 
STDOUT1
STDERR1
STDOUT2
STDERR2
```

**Comment by PigeonF** [comment]
My point was that the default behaviour for `complete` is to group stdout and stderr as you describe

```console
$ run-external nu "-c" "print STDOUT1; print -e STDERR1; print STDOUT2; print -e STDERR2" | complete
╭───────────┬─────────╮
│ stdout    │ STDOUT1 │
│           │ STDOUT2 │
│           │         │
│ stderr    │ STDERR1 │
│           │ STDERR2 │
│           │         │
│ exit_code │ 0       │
╰───────────┴─────────╯
```

However, if you run with redirection, the output is the same

```console
$ run-external nu "-c" "print STDOUT1; print -e STDERR1; print STDOUT2; print -e STDERR2" o+e>| complete
╭───────────┬─────────╮
│ stdout    │ STDOUT1 │
│           │ STDOUT2 │
│           │         │
│ stderr    │ STDERR1 │
│           │ STDERR2 │
│           │         │
│ exit_code │ 0       │
╰───────────┴─────────╯
```

Even though what I want / expect is for the second command to return something like

```console
# Expected output, not actual output
$ run-external nu "-c" "print STDOUT1; print -e STDERR1; print STDOUT2; print -e STDERR2" o+e>| complete
╭───────────┬─────────╮
│ stdout    │ STDOUT1 │
│           │ STDERR1 │
│           │ STDOUT2 │
│           │ STDERR2 │
│           │         │
│ stderr    │         │
│ exit_code │ 0       │
╰───────────┴─────────╯
```

**Comment by fdncred** [comment]
Thanks for explaining. That's clearer to me now. @WindSoilder what are your thoughts on this?

**Comment by WindSoilder** [comment]
Yeah, it's definitely the `complete`'s issue.  I remember it's not easy to fix before https://github.com/nushell/nushell/pull/11934 pr. Not sure if the situation has changed.  I can try to look into this.
