### ISSUE TITLE
`not <anything>` panics in REPL

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#12813]
### Describe the bug

Typing `not` followed by any expression in the REPL panics.

### How to reproduce

Type `not $`, `not (`, `not false`, etc. into REPL.

### Expected behavior

Not panic.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.93.1                                          |
| major              | 0                                               |
| minor              | 93                                              |
| patch              | 1                                               |
| branch             | main                                            |
| commit_hash        | 3b26c08dab31b98658e0836dd113d1f7af6c8d29        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-05-08 18:43:01 +03:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  | formats, gstat, highlight, inc, polars, query   |

### Additional context

```
not Error:   × Main thread panicked.
  ├─▶ at crates/nu-cli/src/syntax_highlight.rs:87:17
  ╰─▶ byte index 7 is out of bounds of `not $`
         0: 0x62b4c9294094 - rust_begin_unwind
         1: 0x62b4c847c055 - core::panicking::panic_fmt::ha6effc2775a0749c
         2: 0x62b4c8569923 - core::str::slice_error_fail_rt::hae2b0a3e014351e1
         3: 0x62b4c847c867 - core::str::slice_error_fail::he2ff12236fb0c056
         4: 0x62b4c868b180 - <nu_cli::syntax_highlight::NuHighlighter as reedline::highlighter::Highlighter>::highlight::h8d2941798f7e17f9
         5: 0x62b4c915d369 - reedline::engine::Reedline::repaint::h9e33c686510d3945
         6: 0x62b4c9159e0b - reedline::engine::Reedline::read_line::hbd5bb4700b7ef561
         7: 0x62b4c86a82d2 - nu_cli::repl::loop_iteration::hff531597d7240be1
         8: 0x62b4c86a1bae - std::panicking::try::hcdb9f8b95caeefd7
         9: 0x62b4c86ba944 - nu_cli::repl::evaluate_repl::had8f25f31091a173
        10: 0x62b4c8670ec2 - nu::run::run_repl::h3e269baf11b8287c
        11: 0x62b4c865dd95 - nu::main::he0f4b8995bab6346
  help: set the `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by ExaltedBagel** [comment]
This is probably from last week. There was work done in flatten.rs in the recent days such as #12793 which might have had some side effects.

**Comment by kubouch** [comment]
I tried reverting https://github.com/nushell/nushell/pull/12793 but it still panics

**Comment by kubouch** [comment]
In fact, typing `not <anything>` anywhere in the code panics. This is a high severity bug that must have been introduced recently, I'm pretty sure we would have noticed it if it was there for long.

If someone has time to bisect and track it down, it would be highly appreciated.

**Comment by kubouch** [comment]
If you try `'not false' | nu-highlight`, you'll get
```
not falfalse
```
where the first `fal` is highlighted yellow and the following `false` is cyan.

This is likely caused by the same bug and is easier to put into a test than typing into REPL.
