### ISSUE TITLE
problem with ` crates/nu-cli/src/syntax_highlight.rs:87:17` on the latest `main`

### ISSUE THREAD

**Issue by maxim-uvarov** [nushell/nushell#12814]
### Describe the bug

something is broken on the latest `main` (at least on my mac inside of wezterm)

### How to reproduce

1. paste `not (true and false)` into command line so it will be recorded into history
2. start entering `not (` - bug should appear

You can find my attempts in the video that is attached

https://github.com/nushell/nushell/assets/4896754/70fbc53e-07bd-4f7f-951e-5d200e4a4b6d

### Expected behavior

to behave without bugs

### Configuration

| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.93.1                                                     |
| major              | 0                                                          |
| minor              | 93                                                         |
| patch              | 1                                                          |
| branch             | main                                                       |
| commit_hash        | c54d223ea0b14f180b1793fa539419854c2e014f                   |
| build_os           | macos-aarch64                                              |
| build_target       | aarch64-apple-darwin                                       |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                        |
| rust_channel       | 1.77.2-aarch64-apple-darwin                                |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                        |
| build_time         | 2024-05-07 05:50:32 +00:00                                 |
| build_rust_channel | release                                                    |
| allocator          | mimalloc                                                   |
| features           | dataframe, default, sqlite, system-clipboard, trash, which |
| installed_plugins  | explore, image, inc, polars                                |

### Additional context

Here is my terminal with backtrace:

```
░▒▓ ~   06:27  📬 6
> not (trtrue and false)
true

░▒▓ ~   06:28  📬 6
> not (trtrue and false)
true

░▒▓ ~   06:28  📬 6
> not Error:   × Main thread panicked.
  ├─▶ at crates/nu-cli/src/syntax_highlight.rs:87:17
  ╰─▶ byte index 7 is out of bounds of `not (`
  help: set the `RUST_BACKTRACE=1` environment variable to
        display a backtrace.


░▒▓ ~   06:28  📬 6
> RUST_BACKTRACE=1 nu

░▒▓ ~   06:28  823ms 📬 6
> not (trtrue and false)
true

░▒▓ ~   06:28  📬 6
> not Error:   × Main thread panicked.
  ├─▶ at crates/nu-cli/src/syntax_highlight.rs:87:17
  ╰─▶ byte index 7 is out of bounds of `not (`
         0: 0x10207b718 - _rust_begin_unwind
         1: 0x1022e2fc4 -
      core::panicking::panic_fmt::h1cb43b60f5788132
         2: 0x10013c1ec -
      core::str::slice_error_fail_rt::h4e2622ead69dc193
         3: 0x1022e3560 -
      core::str::slice_error_fail::hc7d32fbcbb1b6342
         4: 0x1002949b8 -
      <nu_cli::syntax_highlight::NuHighlighter as
      reedline::highlighter::Highlighter>::highlight::h9da57f
      61381eae7b
         5: 0x101e6bc28 -
      reedline::engine::Reedline::repaint::h34d9e1cde26a017e
         6: 0x101e68f88 -
      reedline::engine::Reedline::read_line::h33df94a1550d752
      d
         7: 0x1002b2988 -
      nu_cli::repl::loop_iteration::h4c2b2a6c0a77b323
         8: 0x1002abf10 -
      std::panicking::try::ha740e39f612c6486
         9: 0x10026a3ec -
      nu_cli::repl::evaluate_repl::h6e05ce696f2fb0bb
        10: 0x10023e91c -
      nu::run::run_repl::hf11688a360fe35d2
        11: 0x100223fe8 - nu::main::h5f3bb83be07b5395
  help: set the `RUST_BACKTRACE=1` environment variable to
        display a backtrace.

```

**Comment by maxim-uvarov** [comment]
I guess it is the same as https://github.com/nushell/nushell/issues/12813

**Comment by WindSoilder** [comment]
Let's keep it open, because the behavior is different

**Comment by fdncred** [comment]
May be related to https://github.com/nushell/nushell/pull/12756 too?

**Comment by YizhePKU** [comment]
I triggered the same crash by just typing `[...[` into the shell.
