### ISSUE TITLE
feature request: `polars`: reimplementing `--name` option for `with-column`

### ISSUE THREAD

**Issue by maxim-uvarov** [nushell/nushell#12823]
### Related problem

Previously, `with-column` had a handy option `--name` to set the name for a new column. However, during refactoring, it disappeared. I ask @ayax79 to kindly consider reimplementing it.

### Describe the solution you'd like

If there is only one column - the argument of setting `--name` should be used as a column name as it is.

Optionally:

If there are more than one columns - it seems to me that it would be good to use the provided `--name` as a prefix for new columns, appending their current names to this prefix. If a column name is found to be repeated - just throw an error.

like: 
```
let $df = [[a]; [1]] | polars into-df 
let $df2 = [[a b]; [2 3]] | polars into-df 
$df | polars with-column --name 'c_' [
    ($df2.a),
    ($df2.b)
]

╭─#─┬─a─┬─c_a─┬─c_b─╮
│ 0 │ 1 │   2 │   3 │
╰─#─┴─a─┴─c_a─┴─c_b─╯
```

But I understand that what I'm asking now may be far beyond the current scope and not in line with current advancements. So please, just discard my suggestion. I can remind you of it in a few months.

**Comment by maxim-uvarov** [comment]
it might be related to https://github.com/nushell/nushell/issues/12821

**Comment by ayax79** [comment]
This is the eager syntax, it doesn't work with lazy syntax. The equivalent is:
```
polars with-column [
        ((polars col a) * 2 | polars as "c")
        ((polars col a) * 3 | polars as "d")
      ]
```

You have to use the `polars as` expression. I didn't implement this as a flag because I would have to implicitly add a polars add.

**Comment by maxim-uvarov** [comment]
I see, Jack.
It seems like what I need is `polars append`. And it seemingly works as what I needed at the beginning.

```
> let $df = [[a]; [1]] | polars into-df 
> let $df2 = [[a b]; [2 3]] | polars into-df 
> $df | polars append $df2
╭─#─┬─a─┬─a_x─┬─b─╮
│ 0 │ 1 │   2 │ 3 │
╰─#─┴─a─┴─a_x─┴─b─╯
```

Perhaps, we'll need to revise the current docs on the dataframe and actualize examples.
I will work on that in the near future and share my results.

My confusion came from the documentation examples that just stuck in my mind. I guess if I correct the documentation, other users won't have such problems.

**Comment by maxim-uvarov** [comment]
I'm okay with closing this issue.

P.S.: Below are my sentiments about organizing discussions. These sentiments don't require action (yet if anybody has any advice or insight on that, I would be happy to hear):

I really like the functionality of issues on GitHub—when it is verbose when someone mentions an issue or PR, and I prefer it to Discord.

However, I understand that it is a common board for the entire nushell community, and issues are probably not meant for discussions.

**Comment by fdncred** [comment]
Generally, issues are for reporting features or potential bugs. I think Discord serves discussions better than issues because it's easier to debate things in real time. We also have github discussions but I'm not a huge fan of them either.

Closing for now since the issue seems to be solved with `polars as`.
