### ISSUE TITLE
ripgrep return sufix-result, which may caused by hyperlink

### ISSUE THREAD

**Issue by Kiri2002** [nushell/nushell#12834]
### Describe the bug

Use ripgrep in nushell, will return sufix-result:

### How to reproduce
```
~/Desktop/test> ls                                                                           05/11/2024 11:17:20 AM AM
╭───┬───────────────────┬──────┬──────┬───────────────╮
│ # │       name        │ type │ size │   modified    │
├───┼───────────────────┼──────┼──────┼───────────────┤
│ 0 │ apple_on_tree.txt │ file │  3 B │ 2 minutes ago │
╰───┴───────────────────┴──────┴──────┴───────────────╯
~/Desktop/test> ls |grep on                                                                  05/11/2024 11:17:23 AM AM
│ 0 │ apple_on_tree.txt │ file │  3 B │ 3 minutes ago │
~/Desktop/test> ls |rg on                                                                    05/11/2024 11:17:28 AM AM
│ 0 │ on_tree.txtapple_on_tree.txt │ file │  3 B │ 3 minutes ago │
~/Desktop/test> bash                                                                         05/11/2024 11:17:38 AM AM
[kiri@kiri-laptop test]$ ls |rg on
apple_on_tree.txt
[kiri@kiri-laptop test]$ ls |grep on
apple_on_tree.txt
[kiri@kiri-laptop test]$ ls --hyperlink |grep on
on_tree.txtapple_on_tree.txt
```

### Expected behavior

ls |rg should work same as ls|grep

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.92.2                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 2a08a18b26865a86c793d183b9b042220ecb733a                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.77.1 (7cf61ebde 2024-03-27) (Arch Linux rust 1:1.77.1-2) |
| cargo_version      | cargo 1.77.1                                                     |
| build_time         | 2024-04-11 08:40:50 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | dataframe, default, sqlite, trash, which                         |
| installed_plugins  |                                                                  |

**Comment by devyn** [comment]
Hi, we don't really do anything special for the output to external commands, so it's expected that it will include ANSI escape sequences.

You're probably looking for something like `find` instead:

```nushell
ls | find on
```

**Comment by Kiri2002** [comment]
the file name is ```apple_on_tree.txt```.
when I try to use ```ls|rg``` to search "pattern" (rg is grep written in rust)
it will return the "pattern to end" as suffix to the result,
```
ls |rg on
on_tree.txtapple_on_tree.txt
```
so the suffix "on_tree.txt" is expected?

**Comment by devyn** [comment]
When sending a Nushell table to an external command (`rg` and `grep` both are, but `find` is not), that command will receive a formatted version of the table, including ANSI escape sequences. Some external commands might not like that.

Since `ls` is a builtin command that returns a table (compare `ls | describe` to `^ls | describe`, the external version), you should use Nushell's builtin commands for working with that data.

https://www.nushell.sh/book/working_with_tables.html

**Comment by Kiri2002** [comment]
Well, I see.  Thank u!
