### ISSUE TITLE
`help env` does not display all help information

### ISSUE THREAD

**Issue by Amanita-muscaria** [nushell/nushell#1285]
**Describe the bug**
Running `help env` or `env --help` will only show the description of `env` and information about the help flag but none of the other flags

**To Reproduce**
1. `help env` 

**Expected behavior**
It should display help information for each of the possible flags instead of just `--help`

**Screenshots**
![image](https://user-images.githubusercontent.com/4589044/73135695-b5131a00-400a-11ea-85f5-a2c7139547bd.png)

**Configuration (please complete the following information):**
 - OS: 5.4.11-arch1-1
 - Version: 0.8.1
 - Optional features: stable

**Comment by thegedge** [comment]
`env` doesn't have any other flags at the moment, @Amanita-muscaria. Were you expecting flags similar to that of `/usr/bin/env`?

**Comment by Amanita-muscaria** [comment]
Oh, I have no idea which piece of the code I was looking at now.... Sorry for the noise.
