### ISSUE TITLE
Metadata lost inside closures with `$in`

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#12854]
### Describe the bug

A bit odd. If a `$in` is consumed in a closure, the metadata for `ls` is lost.

### How to reproduce

Compare:

```Nushell
1..1 | each {||
  let any_variable = $in
  ls ~
}
```

Result: filenames are not colored according to extension.

However:

```Nushell
1..1 | each {||
  ls ~
}
```

Correct metadata results.

Inspection via `| metadata` shows the correct source for the later, but an empty record for the first.

Same with:

```Nushell
'any value'
| do {||
    let any_variable = $in
    ls ~   
}
```

Note that this is specific to `$in`.  The following works as expected:

```Nushell
'any value'
| do {||
    let any_variable = 'any value'
    ls ~   
}
```

### Expected behavior

I'd expect the unrelated use of `$in` in the closure to not change the metadata results

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.93.0                                          |
| major              | 0                                               |
| minor              | 93                                              |
| patch              | 0                                               |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-05-04 12:29:25 -04:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  | polars                                          |

### Additional context

Assuming metadata is simply cosmetic, this is not a big issue, of course.

**Comment by kubouch** [comment]
It is a known issue that metadata gets lost when pipeline is collected into a value, I'll close it in favor of the existing issue https://github.com/nushell/nushell/issues/8030

**Comment by fdncred** [comment]
Also, one of the reasons `metadata set` exists. It's a hacky command that sometimes works to fix these type of issues. I'd hope we can get rid of it at some point and metadata will flow better.
