### ISSUE TITLE
`tee` doesn't work within a loop

### ISSUE THREAD

**Issue by YuanYuYuan** [nushell/nushell#12862]
### Question

Hi there! I have a question about `tee`'s behavior

```nushell
echo "hello" | tee { save -a hello.log }
```
produces

```console
───┬───────
 0 │ hello
───┴───────
```

But 
```nushell
for idx in 1..5 { echo "hello" | tee { save -a hello.log } }
```
prints nothing.

Both of them do save the message(s) into _hello.log_. Any advice would be greatly appreciated!

**Comment by fdncred** [comment]
Any ideas/thoughts @devyn?

**Comment by devyn** [comment]
I believe this is an issue with expressions in `for`, as they don't print (even on the REPL) in that case. If you use an explicit `print`, it should work:

```nushell
> for idx in 1..5 { echo "hello" | tee { save -a hello.log } | print }
╭───┬───────╮
│ 0 │ hello │
╰───┴───────╯

╭───┬───────╮
│ 0 │ hello │
╰───┴───────╯

╭───┬───────╮
│ 0 │ hello │
╰───┴───────╯

╭───┬───────╮
│ 0 │ hello │
╰───┴───────╯

╭───┬───────╮
│ 0 │ hello │
╰───┴───────╯

```

Of course, at the moment, the `tee` command expects a stream, so your input gets converted to a list to make that happen. I will probably patch that sometime soon, as there really shouldn't be any difference between a text stream and a string.

**Comment by arnfaldur** [comment]
This issue can be closed.

**Comment by fdncred** [comment]
Thanks, ping us on discord if this needs to be reopened.
