### ISSUE TITLE
Show error message when processes are killed by SIGSEGV/SIGILL/etc

### ISSUE THREAD

**Issue by tgross35** [nushell/nushell#12874]
### Related problem

Nushell currently does not print anything when a program is terminated by a signal:

```
> echo "int main() { asm("ud2"); }" out> sigill.c
> gcc sigill.c -o sigill.out
> ./sigill.out
> # *crickets*
```

```
> echo "int main() { int v = *((int *)0x0); }" out> sigsegv.c
> gcc sigsegv.c -o sigsegv.out
> ./sigsegv.out
> # *crickets*
```

This could be okay if you have the exit code displayed as part of the prompt, but if you don't then it looks like everything completed successfully.

By contrast, Bash tells you what went wrong:

```
$ ./sigill.out
Illegal instruction
$ ./sigsegv.out
Segmentation fault
```

### Describe the solution you'd like

If a signal is the reason a program exits prematurely, print the associated comment so the user is aware of the problem (available at https://man7.org/linux/man-pages/man7/signal.7.html "Standard signals" table), or the same for the Windows equivalent. This can be retrieved on nix with [`ExitStatusExt::signal`](https://doc.rust-lang.org/std/os/unix/process/trait.ExitStatusExt.html#tymethod.signal).

**Comment by sholderbach** [comment]
With #12774 we now properly pull out the signal but don't report the error as mentioned here (I think we had code for that at some point.) The `$env.LAST_EXIT_CODE` contains the signal value in negated form (which I think is not the conventional form. If I recall on Linux it is signal value + 128?)

**Comment by tgross35** [comment]
Does nushell not use `std::process::Command`? If so, the signal is available with `.signal()` under the `ExitSignalExt` trait (which calls `libc::WIFSIGNALED(self.0).then(|| libc::WTERMSIG(self.0))` internally)

**Comment by IanManske** [comment]
#1304 only handles core dumps, not signals in general.
