### ISSUE TITLE
Windows: can get stuck with bad PWD when `cd`ing to drive root

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#12873]
### Describe the bug

On Windows, I can get stuck a state where the PWD is incorrect and I can't `cd` out of it:

```
D:> cd ~                                                                                          05/14/2024 07:34:22 PM
Error:   × $env.PWD is not an absolute path


Error:   × $env.PWD is not an absolute path


Error:   × $env.PWD is not an absolute path


Error:   × $env.PWD is not an absolute path
```

### How to reproduce

1. `cd` to the root of a drive, _without_ putting a slash on the end. For example, run `C:` (auto-cd functionality) or `cd C:`
2. Observe lots of `$env.PWD is not an absolute path` errors
3. Try to `cd` to a valid drive, you can't

### Expected behavior

I think Nu should probably just automatically append a backslash (e.g. `C:` -> `C:\`). It seems like that's what PowerShell does:

```
PS C:\Users\reill> D:
PS D:\>
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.93.1                                          |
| major              | 0                                               |
| minor              | 93                                              |
| patch              | 1                                               |
| branch             |                                                 |
| commit_hash        | 70c01bbb2617f5cd0cdeaeb66c691179a224b8aa        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-05-14 17:19:19 -07:00                      |
| build_rust_channel | debug                                           |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                 |

**Comment by IanManske** [comment]
@rgwood, I think you might be one commit before the PR that fixed this lol. #12779

**Comment by rgwood** [comment]
Hmm. I don’t think so, I believe I was on the latest commit last night. Possible the commit I reported for my version is wrong (I have noticed that it often gets stuck/cached). Will check tonight

**Comment by IanManske** [comment]
Ah ok, I was just going off the the commit hash listed in the `Configuration`, but I think the incremental compilation makes this report the wrong hash sometimes.

**Comment by rgwood** [comment]
I can no longer reproduce this on latest main:
```
Error:   × Cannot set $env.PWD to a non-absolute path
```

My bad, guessing I was on an older commit after all.
