### ISSUE TITLE
Input/Output types of nu script execution help message output are always any

### ISSUE THREAD

**Issue by cavivie** [nushell/nushell#12893]
### Describe the bug

Here is an example script `test.nu`:
```nushell
def main [] {

}

def "main init" [] {

}

def "main rand" [] : [nothing -> string] {
    random uuid
}
```

`input/output types` of nu script execution help message output are always `any`:
```
Input/output types:
  ╭───┬───────┬────────╮
  │ # │ input │ output │
  ├───┼───────┼────────┤
  │ 0 │ any   │ any    │
  ╰───┴───────┴────────╯
```

### How to reproduce

Execute help for the script:
```bash
nu test.nu -h
nu test.nu init -h
nu test.nu rand -h
```

### Expected behavior

When execute this:
```
nu test.nu rand -h
```

Should get like this:
```
Input/output types:
  ╭───┬─────────┬────────╮
  │ # │  input  │ output │
  ├───┼─────────┼────────┤
  │ 0 │ nothing │ string │
  ╰───┴─────────┴────────╯
```

### Configuration

| key                | value                                                                |
| ------------------ | -------------------------------------------------------------------- |
| version            | 0.93.0                                                               |
| major              | 0                                                                    |
| minor              | 93                                                                   |
| patch              | 0                                                                    |
| branch             |                                                                      |
| commit_hash        | 3b220e07e3e3652bc722d4bc8370f2413df69473                             |
| build_os           | linux-x86_64                                                         |
| build_target       | x86_64-unknown-linux-gnu                                             |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                                  |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                                      |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                                  |
| build_time         | 2024-04-30 22:58:28 +00:00                                           |
| build_rust_channel | release                                                              |
| allocator          | mimalloc                                                             |
| features           | default, sqlite, static-link-openssl, system-clipboard, trash, which |
| installed_plugins  |                                                                      |

**Comment by sholderbach** [comment]
This is due to a bug in the parser:
- We only accept the `:` type annotation if directly placed next to the preceding token. (`def foo [bar: int]: nothing -> string {}` instead of `def foo [bar : int] : nothing -> string {}`)
- But instead of raising an error this silently ignores all the type information but still creates a defintion. (for which the default i/o type pair is `any -> any`)

@texastoland figured out this problem after I ran into the same and started to work on this in #12358 but this ran into some roadblocks.

**Comment by texastoland** [comment]
Yep same issue! Got sidetracked by personal stuff but intend to wrap it up first week of June 🗓️
