### ISSUE TITLE
ENV_CONVERSIONS is not applied when setting env

### ISSUE THREAD

**Issue by D3V1LC0D3R** [nushell/nushell#12904]
### Describe the bug

When updating or setting `$env` and/or calling `load-env`, `$env.ENV_CONBERSIONS` for the affected vars is not applied.

When direnv for example updates the PATH with a ":" seperated string it overrides the list that was there before.

### How to reproduce

1. Start nushell and observe the conversions working

2. Edit the PATH or other vars that should get converted but dont

### Expected behavior

I expected nu to apply those conversions everytime `$env` is changed.

### Configuration

| k                  | v                                                                 |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.87.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03) (built from a source tarball) |
| cargo_version      | cargo 1.73.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

### Additional context

Using nixos and home-manager

**Comment by fdncred** [comment]
wow 0.87.0 is pretty old considering we're on 0.93.0, maybe 6 months old by now. can you check to see if you see a problem in the current version of nushell?

**Comment by D3V1LC0D3R** [comment]
That seems to have been the problem, thanks
