### ISSUE TITLE
Let `into filesize` handle decimal strings

### ISSUE THREAD

**Issue by Schweber** [nushell/nushell#12926]
I see `into filesize` fails for decimal string values also 
```
× Can't convert to int.
   ╭─[entry #1:1:2]
 1 │ ["8.3"] | into filesize
   ·  ──┬──
   ·    ╰── can't convert string to int
```   
   but works fine with `[8.3] | into filesize`
   
   I was adding functionality to handle negative file size, should I fix this in the same pr?

_Originally posted by @singh-priyank in https://github.com/nushell/nushell/issues/12396#issuecomment-2041447679_

**Comment by sholderbach** [comment]
Under the premise that Nu commands should do either the obvious, easily explained behavior or lean toward a more explicit form:
- I don't think supporting `float` input to `into filesize` is prudent
- It should either take a string that is annotated with the proper unit (then fractional filesizes have a realistic meaning) 
- or accept integer values with the premise that this means a single byte.

In my view this proposal should not be implemented. It basically performs two steps in one which users wouldn't necesarily expect. e.g. if you forget to enter the unit this would silently coerce.

There is the obvious alternative of going the `into int | into filesize` route or appending a unit as a string if that is warranted based on the context.
