### ISSUE TITLE
`nu --ide-ast` is missing `=` after `let` or `mut`

### ISSUE THREAD

**Issue by maxim-uvarov** [nushell/nushell#12924]
### Describe the bug

`nu --ide-ast` is missing `=` after `let`

<img width="743" alt="image" src="https://github.com/nushell/nushell/assets/4896754/afa38ce5-2c89-4dac-b4fc-da04ed7c51bb">

may be related to https://github.com/nushell/nushell/issues/12923

### How to reproduce

```nu
"let def = 'g'; mut abc = 'a'" | save assignment.nu -f
nu --ide-ast assignment.nu | from json | where content =~ '='
```

### Expected behavior

I expected `nu --ide-ast` to output all the symbols

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.93.1                                          |
| major              | 0                                               |
| minor              | 93                                              |
| patch              | 1                                               |
| branch             | main                                            |
| commit_hash        | 8adf3406e5e6c19f86c82c1f51db93d47217d8ef        |
| build_os           | macos-aarch64                                   |
| build_target       | aarch64-apple-darwin                            |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-aarch64-apple-darwin                     |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-05-17 13:40:01 +00:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  | explore, image, inc, polars, regex              |

**Comment by fdncred** [comment]
This is really the same as #12923

**Comment by sholderbach** [comment]
Again wouldn't say that this is truly a bug but rather a reflection of what our parser does currently. If we have a more formal grammar that says that the assignment operator `=` is part of a `let`/`mut` binding (which in the true grammar is a syntactic form but currently is a pile of hacks on a command call in the parser implementation). Until then I would say, there is nothing to depend upon in this output unless explicitly specified. But I would prefer to focus the investment in nice grammar on the new-nu-parser and only do so much to the old parser to maintain correctness.

**Comment by maxim-uvarov** [comment]
I see! Thank you for explanation!
