### ISSUE TITLE
`where` command is broken inside `do {}` block

### ISSUE THREAD

**Issue by LeoLuxo** [nushell/nushell#12931]
### Describe the bug

Any variant I could test of the `where` command is broken if executed inside a `do {}` block.
It always throws a `nu::shell::missing_parameter (Missing parameter: $it)` error, regardless of whether or not `$it` is used in the `where` command.

### How to reproduce

1. Execute `[] | where true`.
This should produce an empty list (expected output)
2. Execute `do { [] | where true }`.
An error `nu::shell::missing_parameter (Missing parameter: $it)` is thrown.
3. Execute `do { [] | where $it }`.
An error `nu::shell::missing_parameter (Missing parameter: $it)` is thrown.

### Expected behavior

I expected nu to have the same behavior of the `where` command working properly, even if inside a `do {}` block.

### Screenshots

![image](https://github.com/nushell/nushell/assets/24963173/39ea982c-3ad2-4bf7-a8c0-6682d021c4aa)

### Configuration

| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.93.0                                                     |
| major              | 0                                                          |
| minor              | 93                                                         |
| patch              | 0                                                          |
| branch             |                                                            |
| commit_hash        | ca5ee3dba328468b10989f0c85d94a6c0284b767                   |
| build_os           | windows-x86_64                                             |
| build_target       | x86_64-pc-windows-msvc                                     |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                        |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc                              |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                        |
| build_time         | 2024-05-01 12:53:36 -07:00                                 |
| build_rust_channel | release                                                    |
| allocator          | mimalloc                                                   |
| features           | dataframe, default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                            |

### Additional context

I have tested several versions of nu and narrowed down where the bug might have been introduced:
- `0.88.1` up to `0.91.0` are clear of the bug.
- `0.92.0` up to `0.93.0` seem to be affected by the bug.

If I understand the changelogs correctly, the bug was introduced when parameters were added to the `do` command;
```
(excerpt from nu 0.92.0 changelog)
Closures passed to do may now take optional parameters and rest parameters. Additionally, type annotations on the parameters will be checked/enforced. See [#12056](https://github.com/nushell/nushell/pull/12056) for the relevant PR.
```

**Comment by fdncred** [comment]
No issues with the latest main. Maybe it's already been fixed.
```nushell
❯ [{a: 1, b: 2}, {a: 3, b: 4}] | where a > 2
╭─#─┬─a─┬─b─╮
│ 0 │ 3 │ 4 │
╰───┴───┴───╯
❯ do { [{a: 1, b: 2}, {a: 3, b: 4}] | where a > 2 } 
╭─#─┬─a─┬─b─╮
│ 0 │ 3 │ 4 │
╰───┴───┴───╯
```
```nushell
❯ [true] | where true
╭───┬──────╮
│ 0 │ true │
╰───┴──────╯
❯ do { [true] | where true }
╭───┬──────╮
│ 0 │ true │
╰───┴──────╯
```

**Comment by LeoLuxo** [comment]
Oh that is very good to see!
I just did some digging through versions (see edit) and it seems the bug might have been introduced all the way back in `0.92.0`, glad it's fixed on main.
