### ISSUE TITLE
default LS_COLORS stopped working

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#12946]
### Describe the bug

What's weird is that when my nushell changes directory, I call this custom command.
```nushell
def lsg [] { ls | sort-by type name -i | grid -c | str trim }
```
so, on startup it prints out with the default LS_COLORS, just as it should.
![image](https://github.com/nushell/nushell/assets/343840/692785cf-9a88-4f22-add2-420382bbd3b5)

As soon as I change directory, it's broken.
![image](https://github.com/nushell/nushell/assets/343840/dba6624b-fba5-4891-9edd-c39492b761b9)

### How to reproduce

See above

### Expected behavior

Maintain default LS_COLORS

### Configuration

|key|value|
|-|-|
|version|0.93.1|
|major|0|
|minor|93|
|patch|1|
|branch|main|
|commit_hash|0b5a4c0d951622e60c318ecaa66f15ab2c80eeaa|
|build_os|windows-x86_64|
|build_target|x86_64-pc-windows-msvc|
|rust_version|rustc 1.77.2 (25ef9e3d8 2024-04-09)|
|rust_channel|1.77.2-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.77.2 (e52e36006 2024-03-26)|
|build_time|2024-05-23 13:58:58 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|default, sqlite, system-clipboard, trash, which|
|installed_plugins|bg, emoji, explore, file, file_dialog, formats, from_parquet, gstat, inc, json_path, jwalk, md, msgpack, pnet, polars, query, query_git, regex, str_similarity, stress_internals|

**Comment by fdncred** [comment]
I did a git bisect and PR #12922

**Comment by fdncred** [comment]
Here's a wild guess. Nushell is no longer identifying the folders as folders when I cd and is therefore not coloring them right. Notice that the folder icons are completely different looking in the two screenshots, but README.md looks fine.

**Comment by IanManske** [comment]
Looks like the `grid` command uses relative paths (relative to the current CWD of nushell process, not our internal CWD). This was fine before because we also ran `std::env::set_current_dir` whenever we changed directory.
