### ISSUE TITLE
git add cannot add file with path .

### ISSUE THREAD

**Issue by eggcaker** [nushell/nushell#12948]
### Describe the bug

cannot use `git add .` to add file to git 

$ git add . 
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths

### How to reproduce

1. add some new file to a git repo
2. run `git add . ` to add file 

### Expected behavior

should add file with `git add .` not git add ./file1` 

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.93.1                                          |
| major              | 0                                               |
| minor              | 93                                              |
| patch              | 1                                               |
| branch             | main                                            |
| commit_hash        | bf07806b1bc96eebcaa57456c97035a6bce68ef7        |
| build_os           | macos-aarch64                                   |
| build_target       | aarch64-apple-darwin                            |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-aarch64-apple-darwin                     |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-05-24 06:35:19 +08:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  | formats, polars, query, regex                   |

### Additional context

commit: 75689ec98aa7037f1101844ea16f1934c51ff706 works

**Comment by YizhePKU** [comment]
This is caused by PR https://github.com/nushell/nushell/pull/12921, which changed how arguments to external commands are expanded. I'll investigate further.

**Comment by YizhePKU** [comment]
We can close this as fixed via https://github.com/nushell/nushell/pull/12950.
