### ISSUE TITLE
`std help` broken by #12832

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#12941]
### Describe the bug

`std help` is completely broken at the moment in the latest build.  I should have caught this when updating `std help` the other day, but I was apparently a few commits behind on my fork.  Since `nu-std` hadn't been updated, it looked okay, but it apparently wasn't.

### How to reproduce

```nushell
> use std help
> help alias
Error:   × std::help::item_not_found
   ╭─[entry #1:1:20]
 1 │ use std help; help alias
   ·                    ──┬──
   ·                      ╰── item not found
   ╰────
```

### Expected behavior

No error

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.93.1                                          |
| major              | 0                                               |
| minor              | 93                                              |
| patch              | 1                                               |
| branch             | main                                            |
| commit_hash        | c7097ca93761ea2062fef2271ebbdc4a10d67bce        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-05-23 01:35:20 -04:00                      |
| build_rust_channel | debug                                           |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                 |

### Additional context

This appears to be due to the changes in #12832, which is listed as a breaking change.  `std help` will have to update to use the new `scope` results.

Also highlights the need for `std help` tests, which I didn't realize weren't in place at all.

**Comment by WindSoilder** [comment]
It's not breaked by #12832 , I think it's breaked by https://github.com/nushell/nushell/pull/10023, some fields are removed in `scope commands`
