### ISSUE TITLE
commands hints don't prioritize commands from current directory anymore

### ISSUE THREAD

**Issue by maxim-uvarov** [nushell/nushell#12951]
### Describe the bug

I think this PR is broken now https://github.com/nushell/nushell/pull/10780, so that commands hints don't prioritize commands from current directory anymore 

### How to reproduce

```
# open a new instance avoid $env.config.history.isolation
> nu

> mkdir test2
> cd test2
> print "command for test2"
> cd ..
> print "recent command for parent directory"
> exit

> nu
> cd test2
# start typing print and see that it will suggest `print "recent command for parent directory"` first
```

### Expected behavior

I expect nu to suggest the command that was previosly executed in the current working directory

### Screenshots

https://github.com/nushell/nushell/assets/4896754/42c68ce2-7079-4094-b52f-9b347a4b4c14

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.93.1                                          |
| major              | 0                                               |
| minor              | 93                                              |
| patch              | 1                                               |
| branch             | main                                            |
| commit_hash        | 2612a167e31fce874a7faaaecf2222a38c03c6c8        |
| build_os           | macos-aarch64                                   |
| build_target       | aarch64-apple-darwin                            |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-aarch64-apple-darwin                     |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-05-23 06:20:46 +00:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  | explore, image, inc, polars, regex              |

**Comment by fdncred** [comment]
Thanks @maxim-uvarov. I think this could be related to #12922. We'll investigate it.

**Comment by sholderbach** [comment]
This is complicated by the fact that the cwd is read out in `reedline` directly:

https://github.com/nushell/reedline/blob/a580ea56d4e5a889468b2969d2a1534379504ab6/src/history/base.rs#L149-L155

That was kind of sound as there is only ever one nushell process attached to a reedline REPL but with completely omitting process level CWD updates this breaks. 

So the fix will require either a change to reedline or guarantees how the process level state is kept during the active `Reedline::read_line` phase.
