### ISSUE TITLE
RHS of initial and subsequent assignment parsed differently

### ISSUE THREAD

**Issue by 9999years** [nushell/nushell#12956]
### Describe the bug

This fails because there's no executable named `example`:

```nu
> let $example = "hello"
> let $my_example = example
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #66:1:19]
 1 │ let $my_example = example
   ·                   ───┬───
   ·                      ╰── executable was not found
   ╰────
  help: No such file or directory (os error 2)
```

This also fails, for the same reason:

```nu
> mut $my_example = example
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #67:1:19]
 1 │ mut $my_example = example
   ·                   ───┬───
   ·                      ╰── executable was not found
   ╰────
  help: No such file or directory (os error 2)
```

But if I _reassign_ a mut variable, it gets parsed as a bareword string:

```nu
> mut $my_example = ""
> $my_example = example
> $my_example
example
```

### How to reproduce

```nu
let $example = "hello"
let $my_example = example  # Runs a command

mut $my_example = ""
$my_example = example  # Parses as a string
```

### Expected behavior

I expected the right-hand side of an assignment to be parsed the same, regardless of if the variable is mutable / had been assigned before.

### Configuration

| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.93.0                                                     |
| major              | 0                                                          |
| minor              | 93                                                         |
| patch              | 0                                                          |
| branch             |                                                            |
| commit_hash        |                                                            |
| build_os           | macos-aarch64                                              |
| build_target       | aarch64-apple-darwin                                       |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09) (Homebrew)             |
| cargo_version      | cargo 1.77.2                                               |
| build_time         | 2024-04-30 22:51:13 +00:00                                 |
| build_rust_channel | release                                                    |
| allocator          | mimalloc                                                   |
| features           | dataframe, default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                            |

**Comment by 9999years** [comment]
I think it would be a great remediation to explain what exactly is going on here in the documentation. Fits in with #1134, #12957, etc.

**Comment by sholderbach** [comment]
The `let/mut name = <full pipeline expression>` form is implemented very separately from `$x =<value/parenthesized expression>`.
The former is basically its own statement and the latter reuses the operator logic at the moment.
Yes we want to formalize more of that so we can reason/talk about that more easily.
