### ISSUE TITLE
unrecognized symbol `

### ISSUE THREAD

**Issue by xMonody** [nushell/nushell#12966]
### Question

GCC fails to recognize the ` symbol when using the pkgconf or pkg-config tool, but it functions normally in the Makefile.
![e77165036be94416e014b5a0cfc2ee6c](https://github.com/nushell/nushell/assets/76483540/61309548-bc27-4800-b1a3-538285755446)

**Comment by IanManske** [comment]
Backticks are used to define bare words (with spaces) in nushell. For something like command substitution, you can use parentheses:
```nushell
gcc test.c -o test (pkg-config --libs mariadb)
```

**Comment by xMonody** [comment]
Thank you very much for your response, but it seems like I cannot work here.
![5d8a0d83f57206db038d307f1722ddea](https://github.com/nushell/nushell/assets/76483540/259c1ebc-3b6c-4766-84bc-1a3b574dd31c)

**Comment by xMonody** [comment]
> Backticks are used to define bare words (with spaces) in nushell. For something like command substitution, you can use parentheses:
> 
> ```nushell
> gcc test.c -o test (pkg-config --libs mariadb)
> ```

Thank you very much for your response, but it seems like I cannot work here.
![5e6d23a892769bc9d0fa77e0baeeec70](https://github.com/nushell/nushell/assets/76483540/55165959-c523-496e-9e9a-10324d6e0c2e)

**Comment by IanManske** [comment]
Oh that's right, sorry about that. `pkg-config` outputs flags and each flag needs to be a separate argument to `gcc`. So, you can try splitting the output of `pkg-config`:
```nushell
gcc test.c -o test ...(pkg-config --libs mariadb | split row ' ')
```
The `...` is the spread operator and will put each list item as a separate argument.

**Comment by xMonody** [comment]
> Oh that's right, sorry about that. `pkg-config` outputs flags and each flag needs to be a separate argument to `gcc`. So, you can try splitting the output of `pkg-config`:
> 
> ```nushell
> gcc test.c -o test ...(pkg-config --libs mariadb | split row ' ')
> ```
> 
> The `...` is the spread operator and will put each list item as a separate argument.

I understand, thank you very much.
