### ISSUE TITLE
the command `rm -rf somefolder/**/*` will print a lot of errors

### ISSUE THREAD

**Issue by bp-galopin** [nushell/nushell#12964]
### Describe the bug

The console will be spammed with a lot of "Error: * no such file or directory: someabsolutepathtofile"

If the command is run a second time, no error

### How to reproduce

1. Be on windows 11, nushell 0.92.2
2. have a folder with a few thousands files in various 4-5 deep folder sub hierarchy
3. execute rm -rf thefolder/**/* 

### Expected behavior

Deletion of everything without errors

### Screenshots

```
Error:   × no such file or directory: REDACTEDPATH
   ╭─[entry #1:1:8]
 1 │ rm -rf folder/**/*
   ·        ────┬────
   ·            ╰── no such file or directory
   ╰────
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.92.2                                   |
| branch             |                                          |
| commit_hash        | 2a08a18b26865a86c793d183b9b042220ecb733a |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)      |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)      |
| build_time         | 2024-04-10 21:24:37 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash, which            |
| installed_plugins  |                                          |

### Additional context

My guess is that rm run multithreaded and somehow attempt deletion multiple times for the same path

**Comment by devyn** [comment]
This is expected, you're giving it a glob which includes all of the files and folders, and then telling it to remove them recursively. This would mean that for example you match `foo`, `foo\bar`, `foo\bar\baz.txt`, and then it removes them in that order, which results in `foo\bar` not existing because `foo` was removed recursively first.

You should just do `rm -rf somefolder`
