### ISSUE TITLE
`explore` spends too much time in `lscolorize()`

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#12980]
### Describe the bug

I noticed that `explore` was very slow when browsing large directories on Windows. I profiled it and found out that it's spending nearly all its time in `lscolor::lscolorize()`.

### How to reproduce

1. Run `ls C:\Windows\System32\ | explore`
2. Try to navigate around with keyboard arrows, note that it's very slow

### Expected behavior

I expected `explore` to be snappy.

### Screenshots

![image](https://github.com/nushell/nushell/assets/26268125/c972eaf2-c22d-46b3-a704-3a574cb65be6)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.93.1                                          |
| major              | 0                                               |
| minor              | 93                                              |
| patch              | 1                                               |
| branch             | main                                            |
| commit_hash        | a7807735b15ad377f281091a85afb3791d9df608        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-05-15 18:03:30 -07:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                 |

### Additional context

It seems like there are a few issues here:
1. `explore` uses filesystem metadata to do colorization, and getting that is slower on Windows than on *nix
2. `explore` is somewhat naive about how it does this; instead of retrieving metadata for files currently visible and/or caching data, it does it for every row in the table on every render

I'm not super keen on fixing this up in the near future; I'm tempted to disable the lscolorize code in `explore` for now.

**Comment by fdncred** [comment]
It's been a while since I've looked at the LS_COLORS stuff but as I recall, you can style any string, it doesn't have to be a path.

Ah ha, this is what I was thinking about https://docs.rs/lscolors/latest/lscolors/struct.LsColors.html#method.style_for_str

I wonder if we can just pass the file names as a string to style_for_str instead of calling style_for_path_with_metadata or style_for_path. Seems like that would make it a lot faster. If so, that may be a good change for general nushell too.

**Comment by rgwood** [comment]
Good call, I've raised a PR for that!
