### ISSUE TITLE
How to apply `from csv --separator '|'` on individual items of a larger csv?

### ISSUE THREAD

**Issue by MMesch** [nushell/nushell#12981]
### Question

I have a csv file `out.csv` with a column `Industries` that contains a pipe `|` symbol separated list of industries. I have tried converting the items to a list with this command:

`open out.csv | update Industries {| from csv --separator "|"} | explore`

but it fails with:

```
➜ open out.csv | update Industries {| from csv --separator "|"} | explore
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[entry #1:1:58]
 1 │ open out.csv | update Industries {| from csv --separator "|"} | explore
   ·                                                          ─┬─
   ·                                                           ╰── expected valid variable name for this parameter
   ╰────
```

It does work with `open out.csv | update Industries {| from csv --separator ";"} | explore`, returning a single list item because it's not the correct separator. This is why I am suspecting that it has something to do with using the `|` symbol. Does anyone have an idea how to do this or whether it is a bug?

### Additional context and details

I am using nushell on NixOS and it says:

```
nu --version
0.91.0
```

**Comment by fdncred** [comment]
Here's the secret sauce. Nushell infers how to open some files by the file extension. If you don't want that to happen, you need to tell nushell not to do that. For specifying the delimiter, you don't want that to happen. So, you need to say `open --raw out.csv`. The `--raw` tells nushell not to try and figure out what you're trying to do. Then you want to use `from csv`. So, something like `open --raw out.csv | from csv --delimiter '|'`.

You might also want to update nushell to get the latest changes. We're releasing 0.94.0 tomorrow.

**Comment by MMesch** [comment]
@fdncred thanks. However, in the command above I am trying to read a csv where one _element_ is another comma separated list of elements. Take this example:

```
Name,Industries
XXX,IT;Pharma;Robotics
YYY,Pharma;Robotics
```
Here I used "," as primary delimiter and ";" as subdelimiter.  Ultimately I am trying to filter on one element of the sublist, e.g. to get all items that have `IT` in them.

**Comment by bsierro** [comment]
you can get sub-list or sub-tables by parsing each cell: 

```nushell
let s = 'XXX,IT;Pharma;Robotics
YYY,Pharma;Robotics'
let parsed = $s | from csv --noheaders | rename name tags | update tags {|row| $row.tags | split row ";"}
$parsed | filter {|row| "IT" in $row.tags}
```

output:
```
╭───┬──────┬──────────────────╮
│ # │ name │       tags       │
├───┼──────┼──────────────────┤
│ 0 │ XXX  │ ╭───┬──────────╮ │
│   │      │ │ 0 │ IT       │ │
│   │      │ │ 1 │ Pharma   │ │
│   │      │ │ 2 │ Robotics │ │
│   │      │ ╰───┴──────────╯ │
╰───┴──────┴──────────────────╯
```

**Comment by dedebenui** [comment]
you can get sub-list or sub-tables by parsing each cell: 

```nushell
let s = 'XXX,IT;Pharma;Robotics
YYY,Pharma;Robotics'
let parsed = $s | from csv --noheaders | rename name tags | update tags {|row| $row.tags | split row ";"}
$parsed | filter {|row| "IT" in $row.tags}
```

output:
```
╭───┬──────┬──────────────────╮
│ # │ name │       tags       │
├───┼──────┼──────────────────┤
│ 0 │ XXX  │ ╭───┬──────────╮ │
│   │      │ │ 0 │ IT       │ │
│   │      │ │ 1 │ Pharma   │ │
│   │      │ │ 2 │ Robotics │ │
│   │      │ ╰───┴──────────╯ │
╰───┴──────┴──────────────────╯
```

**Comment by MMesch** [comment]
Thanks that's exactly what I was after—and it also works with `|` as separator.
