### ISSUE TITLE
Spread operator in a closure does not capture all arguments

### ISSUE THREAD

**Issue by pyz4** [nushell/nushell#12985]
### Describe the bug

The spread operator does not capture all residual arguments when used in a closure.

### How to reproduce

```
$ do {|a, ...b| echo $a ...$b} 1 2 3 4
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 3 │
│ 2 │ 4 │
╰───┴───╯
```

### Expected behavior

I expect the output to also include "2"

```
$ do {|a, ...b| echo $a ...$b} 1 2 3 4
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 2 │
│ 2 │ 3 │
│ 3 │ 4 │
╰───┴───╯
```

### Configuration

| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.93.0                                                     |
| major              | 0                                                          |
| minor              | 93                                                         |
| patch              | 0                                                          |
| branch             |                                                            |
| commit_hash        |                                                            |
| build_os           | windows-x86_64                                             |
| build_target       | x86_64-pc-windows-msvc                                     |
| rust_version       | rustc 1.79.0-nightly (385fa9d84 2024-04-04)                |
| rust_channel       | nightly-x86_64-pc-windows-msvc                             |
| cargo_version      | cargo 1.79.0-nightly (0637083df 2024-04-02)                |
| build_time         | 2024-05-25 21:19:07 -04:00                                 |
| build_rust_channel | release                                                    |
| allocator          | mimalloc                                                   |
| features           | dataframe, default, sqlite, system-clipboard, trash, which |
| installed_plugins  | polars                                                     |

**Comment by devyn** [comment]
I can reproduce this on 0.94.0. Need to look into why this is happening.
