### ISSUE TITLE
Error:   × Config record contains invalid values or unknown settings

### ISSUE THREAD

**Issue by Ender-Wang** [nushell/nushell#12991]
### Describe the bug

Got this on opening nu:
```
~> nu                                                                                          05/29/2024 11:27:49 AM AM
Error:   × Config record contains invalid values or unknown settings

Error:   × Error while applying config changes
     ╭─[/Users/user/Library/Application Support/nushell/config.nu:232:24]
 231 │     edit_mode: emacs # emacs, vi
 232 │     shell_integration: false # enables terminal shell integration. Off by default, as some terminals have issues with this.
     ·                        ──┬──
     ·                          ╰── boolean value is deprecated, should be a record. see `config nu --default`.
 233 │     render_right_prompt_on_last_line: false # true or false to enable or disable right prompt to be rendered on last line of the prompt.
     ╰────
  help: This value will be ignored.
```

### How to reproduce

Just opened nu today, it just pops up.

### Expected behavior

I should not get this error.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.94.0                                          |
| major              | 0                                               |
| minor              | 94                                              |
| patch              | 0                                               |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | macos-aarch64                                   |
| build_target       | aarch64-apple-darwin                            |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29) (Homebrew)  |
| cargo_version      | cargo 1.78.0                                    |
| build_time         | 2024-05-28 19:04:09 +00:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                 |

**Comment by Ender-Wang** [comment]
Btw, installed via brew.

**Comment by WindSoilder** [comment]
Sorry for the issue, there is a breaking change on latest version: https://www.nushell.sh/blog/2024-05-28-nushell_0_94_0.html#shell-integration-config-toc

To fix the issue, you can delete `shell_integration` config line, or change it to something like this:
```nushell
    shell_integration: {
        # osc2 abbreviates the path if in the home_dir, sets the tab/window title, shows the running command in the tab/window title
        osc2: true
        # osc7 is a way to communicate the path to the terminal, this is helpful for spawning new tabs in the same directory
        osc7: true
        # osc8 is also implemented as the deprecated setting ls.show_clickable_links, it shows clickable links in ls output if your terminal supports it. show_clickable_links is deprecated in favor of osc8
        osc8: true
        # osc9_9 is from ConEmu and is starting to get wider support. It's similar to osc7 in that it communicates the path to the terminal
        osc9_9: false
        # osc133 is several escapes invented by Final Term which include the supported ones below.
        # 133;A - Mark prompt start
        # 133;B - Mark prompt end
        # 133;C - Mark pre-execution
        # 133;D;exit - Mark execution finished with exit code
        # This is used to enable terminals to know where the prompt is, the command is, where the command finishes, and where the output of the command is
        osc133: true
        # osc633 is closely related to osc133 but only exists in visual studio code (vscode) and supports their shell integration features
        # 633;A - Mark prompt start
        # 633;B - Mark prompt end
        # 633;C - Mark pre-execution
        # 633;D;exit - Mark execution finished with exit code
        # 633;E - NOT IMPLEMENTED - Explicitly set the command line with an optional nonce
        # 633;P;Cwd=<path> - Mark the current working directory and communicate it to the terminal
        # and also helps with the run recent menu in vscode
        osc633: true
        # reset_application_mode is escape \x1b[?1l and was added to help ssh work better
        reset_application_mode: true
    }
```
