### ISSUE TITLE
`zoxide` navigation broken

### ISSUE THREAD

**Issue by RoloEdits** [nushell/nushell#12990]
### Describe the bug

After updating to `0.94` navigating directories with `zoxide` was broken. 

```shell
┌─   nushell on 󰊢 main -19 (  ) is 📦 v0.94.1 via  v1.78.0
└─▶  z projects
Error: nu::shell::io_error

  × I/O error
  help: The system cannot find the file specified. (os error 2)
```

After a bisect I found that it started here: https://github.com/nushell/nushell/pull/12975

### How to reproduce

1. using nushell 0.94
2. use the alias `z` to navigate using prior history

### Expected behavior

nushell should support the path zoxide uses

### Screenshots

![image](https://github.com/nushell/nushell/assets/12489689/c351c482-6ce8-4ecb-9e1b-97facb16cb96)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.94.1                                          |
| major              | 0                                               |
| minor              | 94                                              |
| patch              | 1                                               |
| branch             | main                                            |
| commit_hash        | f3991f2080284eadaec5a29b92def5bdf8d41248        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.78.0 (54d8815d0 2024-03-26)             |
| build_time         | 2024-05-28 20:32:11 -07:00                      |
| build_rust_channel | debug                                           |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
Thanks for fixing this @dedebenui!

**Comment by fdncred** [comment]
Closing this as the fix is mentioned above and the zoxide PR has already landed. Thanks again!
