### ISSUE TITLE
0.94 regression on parse --regex

### ISSUE THREAD

**Issue by SommerEngineering** [nushell/nushell#13011]
### Describe the bug

I have a build script for my project in Nushell. A part of the script is to gather information about the .NET installation. Here is the relevant snippet:

```nu
let dotnet_data = (^dotnet --info) | parse --regex '.?NET SDK:\s+Version:\s+(?P<sdkVersion>[0-9.]+).+Commit:\s+(?P<sdkCommit>[a-zA-Z0-9]+).+Host:\s+Version:\s+(?P<hostVersion>[0-9.]+).+Commit:\s+(?P<hostCommit>[a-zA-Z0-9]+)'
let sdk_version = $dotnet_data.sdkVersion.0
let host_version = $dotnet_data.hostVersion.0
let sdkCommit = $dotnet_data.sdkCommit.0
let hostCommit = $dotnet_data.hostCommit.0
```

Everything worked well with Nushell version 0.93.0. Since updating to version 0.94.0, the regex doesn't match anymore. I have read the release notes. The only thing that caught my attention is the refactoring of the `parse` command, https://github.com/nushell/nushell/pull/12791.

My script is part of my Git repo. I can guarantee that nothing has changed in the script. Therefore, I assume a regression in version 0.94.0.

I can prove that the regex is just fine, see https://regex101.com/r/vX81tb/1

### How to reproduce

Run these Nushell commands. I embedded a sample output of `dotnet --info`. Thus, everyone can reproduce this, even without a .NET installation:

```nu
let input = r#'.NET SDK:
 Version:           8.0.205
 Commit:            3e1383b780
 Workload version:  8.0.200-manifests.30778e70

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.205/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.5
  Architecture: arm64
  Commit:       087e15321b

.NET SDKs installed:
  8.0.205 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
'#

let dotnet_data = $input | parse --regex '.?NET SDK:\s+Version:\s+(?P<sdkVersion>[0-9.]+).+Commit:\s+(?P<sdkCommit>[a-zA-Z0-9]+).+Host:\s+Version:\s+(?P<hostVersion>[0-9.]+).+Commit:\s+(?P<hostCommit>[a-zA-Z0-9]+)'
let sdk_version = $dotnet_data.sdkVersion.0
let host_version = $dotnet_data.hostVersion.0
let sdkCommit = $dotnet_data.sdkCommit.0
let hostCommit = $dotnet_data.hostCommit.0
```

### Expected behavior

No error messages.

Instead, we get:

```
Error: nu::shell::access_beyond_end

  × Row number too large (empty content).
   ╭─[entry #9:1:43]
 1 │ let sdk_version = $dotnet_data.sdkVersion.0
   ·                                           ┬
   ·                                           ╰── index too large (empty content)
   ╰────
```

The `dotnet_data` variable is empty:

```nu
$dotnet_info

╭────────────╮
│ empty list │
╰────────────╯
```

### Configuration

```
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.94.0                                          |
| major              | 0                                               |
| minor              | 94                                              |
| patch              | 0                                               |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | macos-aarch64                                   |
| build_target       | aarch64-apple-darwin                            |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29) (Homebrew)  |
| cargo_version      | cargo 1.78.0                                    |
| build_time         | 2024-05-28 19:04:09 +00:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                 |
```

**Comment by IanManske** [comment]
Thanks for bringing up this issue. I've tried to get the regex to match on
- multiple versions: 0.91.0, 0.92.0, 0.93.0, 0.94.0
- using multiple inputs:
  - your example input
  - output from my local dotnet version
- using multiple piping methods:
  - piping the dotnet output directly to `parse` (with and without parens)
  - storing the string in a variable first, then piping the variable to `parse`

And in none of the cases, was I able to get the regex to match.

We use the `fancy_regex` crate to do regex parsing, and I believe that it treats `.` as any character except new lines. So, I'm not sure how the regex was matching before, because the regex you have needs to match new lines with `.+` in order to provide a match. (If I'm reading it correctly.)

**Comment by fdncred** [comment]
I just tried on Windows and MacOS with 0.93.0 and couldn't get the regex above to work either. However, there is definitely something different between 0.94.0 and 0.93.0 because, on Windows, in 0.93.0, I can do this, and it works.
```nushell
^dotnet --info | parse --regex '.?NET SDK:\s+Version:\s+(?P<sdkVersion>[0-9.]+)'
```
on macos, that statement doesn't work, even though I have dotnet installed on macos and can see a valid `dotnet --info` output.

**Comment by IanManske** [comment]
Oh that's right, sorry I forgot to put in the release notes, but `parse` operates on lines now in order to support streaming. For multi-line matches, there needs to be a `collect` beforehand:
```nushell
^dotnet --info | collect | parse --regex '.?NET SDK:\s+Version:\s+(?P<sdkVersion>[0-9.]+)'
```

**Comment by fdncred** [comment]
This works on my Windows box now with `collect` but I also had to enable `(?ms)` which, according to the comments, allows `multi-line mode and allow . to match \n`
```nushell
❯ open dn.txt | collect | parse --regex '(?ms).?NET SDK:\s+Version:\s+(?P<sdkVersion>[0-9.]+).+Commit:\s+(?P<sdkCommit>[a-zA-Z0-9]+).+Host:\s+Version:\s+(?P<hostVersion>[0-9.]+).+Commit:\s+(?P<hostCommit>[a-zA-Z0-9]+)'
╭─#─┬sdkVersion┬─sdkCommit──┬hostVersion┬─hostCommit─╮
│ 0 │ 8.0.300  │ 326f6e68b2 │ 8.0.6     │ 3b8b000a0e │
╰───┴──────────┴────────────┴───────────┴────────────╯
```
@IanManske That tidbit about `collect` and multiline matching probably needs to go in an example or the help docs I think.

**Comment by IanManske** [comment]
Agreed, I will update the release notes and will also open another PR for `parse`.

**Comment by SommerEngineering** [comment]
Thank you for the prompt responses. The solution from @fdncred also works for me with macOS. Thanks for your support.
