### ISSUE TITLE
Installation from homebrew lacks some commands

### ISSUE THREAD

**Issue by Emilios1995** [nushell/nushell#1301]
**Describe the bug**
I installed `nu` from` homebrew`. `nu --help` says I'm in `0.8.0` which I think should have all the commands in the documentation, but `fetch` just outputs `error: Command not found` 
**To Reproduce**
Install from homebrew per the instructions (`brew install nushell`)

**Expected behavior**
Have all the commands in the docs

**Screenshots**

**Configuration (please complete the following information):**
 - OS: Mac
 - Version 0.8.0
 - Installed from brew

**Comment by andrasio** [comment]
@Emilios1995 You have a regular installation of Nu. `fetch` is a plugin that's optional and it's not included in the default Nu build. Perhaps in the future someone might chime in and add another homebrew formula for installing Nu with all the features (where `fetch` comes)

If you are interested, you could try building locally [with these instructions](https://www.nushell.sh/installation.html#building-it-locally) and all the features or download the [pre-built binaries](https://github.com/nushell/nushell/releases/tag/0.9.0) we supply for convenience.

Please let us know how you do.

**Comment by andrasio** [comment]
@Emilios1995 It seems the formula does have the commands for installing all the features (including `fetch`), this is a bug. Thanks for reporting it.
