### ISSUE TITLE
Tilde expansion for external command arguments

### ISSUE THREAD

**Issue by weirdan** [nushell/nushell#13021]
### Describe the bug

It appears 0.94 no longer expands the tilde to the absolute path in external command arguments.

### How to reproduce

```sh
#!/bin/sh
echo $*
```
Running this script with nushell 0.93, bash and zsh with `~` as the argument produces the following output (regardless of PWD):
```
/home/weirdan
```
but running it with nushell 0.94+ it outputs the path relative to PWD.

### Expected behavior

Nushell should do what it did previously (and what other shells do) - expand the arguments to the absolute path.

### Configuration

Irrelevant

**Comment by weirdan** [comment]
It does. 0.94.1 kinda fixed it for the external command paths (e.g. `~/bin/something`), but it still happens with the _arguments_ (e.g. `something ~/logs/something.log`). Note the tilde in the command argument.

**Comment by kubouch** [comment]
I can't reproduce the original issue on 0.94.1.

Could you please give exact reproduction steps for the arguments issue you mentioned? It's not entirely clear what the problem is from your description. We're looking into it, and it might be related to some other broken things we're seeing.

**Comment by weirdan** [comment]
1. Save the script mentioned in the issue text to, say, `q.sh` in your home folder
2. Make it executable (`chmod a+x q.sh`)
3. While you're in your home folder, run it as `./q.sh ~`
4. Compare the output to when it's run from other shells

![image](https://github.com/nushell/nushell/assets/57403/fbec79fc-6f0b-4b55-99c2-5c37559ceb0c)

in the above screenshot, the output from the script is marked with arrows. The shells used:
1. Nushell 0.94.1 - outputs `.` (wrong)
2. Bash - outputs `/home/weirdan` (correct)
3. ZSH - outputs `/home/weirdan` (correct)
4. Nushell 0.93 - outputs `/home/weirdan` (correct)

**Comment by kubouch** [comment]
On 0.94.1 I also get `/home/user`. Check the `version` command to make sure you're indeed in 0.94.1.

**Comment by weirdan** [comment]
```
╭────────────────────┬──────────────────────────────────────────────────────────────────────╮
│ version            │ 0.94.1                                                               │
│ major              │ 0                                                                    │
│ minor              │ 94                                                                   │
│ patch              │ 1                                                                    │
│ branch             │                                                                      │
│ commit_hash        │ f3cf693ec701ab3086f984a8aeadfc9b50fadd90                             │
│ build_os           │ linux-x86_64                                                         │
│ build_target       │ x86_64-unknown-linux-gnu                                             │
│ rust_version       │ rustc 1.77.2 (25ef9e3d8 2024-04-09)                                  │
│ rust_channel       │ 1.77.2-x86_64-unknown-linux-gnu                                      │
│ cargo_version      │ cargo 1.77.2 (e52e36006 2024-03-26)                                  │
│ build_time         │ 2024-05-30 23:10:14 +00:00                                           │
│ build_rust_channel │ release                                                              │
│ allocator          │ mimalloc                                                             │
│ features           │ default, sqlite, static-link-openssl, system-clipboard, trash, which │
│ installed_plugins  │ inc, query                                                           │
╰────────────────────┴──────────────────────────────────────────────────────────────────────╯
```

**Comment by kubouch** [comment]
Ah! If you run it from your home directory, the output is indeed `.`, otherwise it works fine. Thanks, this is indeed a bug.

**Comment by fdncred** [comment]
I get this in Ubuntu from /home/fdncred/src/nushell
```nushell
❯ nvim q.sh
❯ chmod a+x q.sh
❯ ./q.sh ~ 
/home/fdncred
```
Breaks only in the ~ folder
```nushell
❯ cd ~
❯ mv src/nushell/q.sh .
❯ ./q.sh ~
.
```

**Comment by weirdan** [comment]
or in any parent folders, e.g. if you run it from `/home` with `$HOME` being `/home/fdncred` it would output `fdncred` rather than `/home/fdncred` as other shells do.

**Comment by kubouch** [comment]
Running this from 0.94.0 is broken in a similar way. Running it from commit https://github.com/nushell/nushell/pull/12921 directly, shows empty string instead of `.`. Running from a commit before the PR works fine, so it is clear that PR caused it.

**Comment by fdncred** [comment]
same. thanks for the detailed repro. it helps.
