### ISSUE TITLE
`nu::shell::io_error` when trying to run file on windows

### ISSUE THREAD

**Issue by Araxeus** [nushell/nushell#13020]
### Describe the bug

When trying to run ~a powershell `.ps1` script~ any file ([except `.bat`](https://github.com/nushell/nushell/pull/6278)) on windows, we get an error:
```
Error: nu::shell::io_error

  × I/O error
  help: %1 is not a valid Win32 application. (os error 193)
```

### How to reproduce

1. create a powershell `.ps1` file containing anything, for example `(Get-ChildItem).Count`
2. try to run it via nushell by calling the file name, for example `./childCount.ps1`
3. get error

### Expected behavior

Run the powershell script and print the output

### Screenshots

![image](https://github.com/nushell/nushell/assets/78568641/edd21a6f-9d4d-42b8-8eb7-fcb5e0c47cd8)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.94.1                                          |
| major              | 0                                               |
| minor              | 94                                              |
| patch              | 1                                               |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.78.0 (54d8815d0 2024-03-26)             |
| build_time         | 2024-05-31 15:27:30 +03:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                 |

### Additional context

I remember it used to work in some previous nushell version, but I might be wrong

* `pwsh -f ./childCount.ps1` obviously works
*  `./batscript.bat` works

**Comment by Araxeus** [comment]
After further inspection this has nothing to do with powershell, I can replicate the bug by creating an empty `test.txt` file and running in nushell `./test.txt`

![image](https://github.com/nushell/nushell/assets/78568641/20fefc01-f162-42a9-b27c-0bf28d5f4f90)

**Comment by fdncred** [comment]
Did those work before 0.94.0? Seems like ps1 files would need `pwsh file.ps1` and `.txt` files are not executable.

**Comment by Araxeus** [comment]
For some reason I remember executing a `ps1` file used to just work, and executing a `txt` file used to open it with the default file editor... but I tried downgrading to nushell v0.81.0 and it still threw the same error

Anyways it doesn't really make sense to throw an error here? the error text doesnt make much sense either, and also Windows have native file type handlers so this really should just work?

**Comment by Araxeus** [comment]
Actually yeah downgraded to v0.81.0 and it used to work. im trying to find out which exact version broke this

**Comment by Araxeus** [comment]
@fdncred I confirmed it used to work on v0.93.0, and broke on v0.94.0 

seems like https://github.com/nushell/nushell/pull/12921 broke it?

**Comment by Araxeus** [comment]
> Duplicate of #13016.

doesn't look like it? neither description nor how to reproduce?

did u debug why this is happening and saw it is the same reason or what?

**Comment by kubouch** [comment]
Ah, oops, sorry, too many tabs open :-D.

**Comment by devyn** [comment]
I can't really figure out why this would have worked before. Maybe because I don't have this configured, but it seems like you also have to set `PATHEXT` and have the registry file association to open it?

But ultimately we're still passing the ps1 file to `std::process::Command::new()`, which is what was happening before too as far as I can tell. I don't think this was triggering the behaviour where it was getting passed to `cmd.exe` because that was special cased for `.cmd` and `.bat` files.

**Comment by Araxeus** [comment]
> But ultimately we're still passing the ps1 file to `std::process::Command::new()`, which is what was happening before too as far as I can tell.

dont know much about nu architecture but after some debugging I figured out alot.

the current error in v0.94.0 is thrown here in `command.spawn()`:
https://github.com/nushell/nushell/blob/f3cf693ec701ab3086f984a8aeadfc9b50fadd90/crates/nu-system/src/foreground.rs#L35-L39

but here is what was happening in previous versions (<v0.93.0):

# input = `./typos.toml`

the code gets to here:
https://github.com/nushell/nushell/blob/3b220e07e3e3652bc722d4bc8370f2413df69473/crates/nu-command/src/system/run_external.rs#L174-L177

and fails with `{ code: 193, kind: Uncategorized, message: "%1 is not a valid Win32 application." }`

then we get to:
https://github.com/nushell/nushell/blob/3b220e07e3e3652bc722d4bc8370f2413df69473/crates/nu-command/src/system/run_external.rs#L216-L218

which_path = `"C:\\Git\\rust\\nushell\\typos.toml"`

https://github.com/nushell/nushell/blob/3b220e07e3e3652bc722d4bc8370f2413df69473/crates/nu-command/src/system/run_external.rs#L219-L221

`command_name "./typos.toml"` does not equal `file name = "typos.toml"`

https://github.com/nushell/nushell/blob/3b220e07e3e3652bc722d4bc8370f2413df69473/crates/nu-command/src/system/run_external.rs#L222-L230

cmd = `"cmd" "/D" "/c" "typos.toml"`

and then the child spawn successfully

# input = `typos.toml`

now this one is funny, it fails because `./` is missing which means the command name is equal to the file name, and we dont spawn another process

we get to here:
https://github.com/nushell/nushell/blob/3b220e07e3e3652bc722d4bc8370f2413df69473/crates/nu-command/src/system/run_external.rs#L219-L221

`command_name "typos.toml"` equal `file name = "typos.toml"`

**Comment by essenciary** [comment]
Seeing a similar error when attempting to run .bat files. I'm a new user so I don't know if this worked or if it's supposed to work. But this is unexpected and I'm not sure hot to address it. (PS I've made the .bat file executable). (Also the error message is kind of garbled, ex "epl.bat` not foundmmand `in").

```
> .\bin\repl.bat                                                                                06/03/2024 05:25:53 PM
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #1:1:1]
 1 │ .\bin\repl.bat
   · ───────┬──────
epl.bat` not foundmmand `in
   ╰────
epl.bat` is neither a Nushell built-in or a known external command
```

**Comment by fdncred** [comment]
I don't have issues with batch files. I created a batch file with this in it
```bat
@echo off
c:\users\username\.cargo\bin\bat.exe %1
```
and i can do `.\nushell\test.bat readme.md` without issues.

**Comment by essenciary** [comment]
I'm not sure what that does... I don't want to have a `.exe`. In my example above I just wanted to run the `.bat` file as done in Windows CMD.

**Comment by essenciary** [comment]
OK - so what can be the explanation for the error messages in my post? It worked without any issues in CMD.

**Comment by kubouch** [comment]
Double quotes allow escapes, so that string `"%~dp0..\bootstrap.jl"` is interpreted as having a `\b` character. Try changing to single quotes.

**Comment by fdncred** [comment]
Good catch Kubouch. Double quotes being escaped frequently causes problems in windows.

**Comment by Araxeus** [comment]
I think you might have missed the initial problem
 
>   × External command failed
>    ╭─[entry #1:1:1]
>  1 │ .\bin\repl.bat
>    · ───────┬──────
> epl.bat` not foundmmand `in
>    ╰────
> epl.bat` is neither a Nushell built-in or a known external command
> ```

try ` ./bin/repl.bat` or ` .\\bin\\repl.bat` ?

anyways this is unrelated to the issue I posted about

**Comment by mpawelski** [comment]
I have the same problem when I simply try to run .nu script from nushell. I have to run it by passing it to `nu` command (`.\script.nu` doesn't work, `nu .\script.nu` works.)

**Comment by fdncred** [comment]
@mpawelski .nu scripts aren't supposed to be executable on windows. If you want a foreign extension to launch with a particular program, you have to make windows do it since it doesn't know. You do this by associating nushell with the .nu extension. 

I wrote these instructions a long time ago. I assume they still work.

This is the contents of my `im_executable.nu` script that explains the secret sauce of making a nushell script executable on Windows. 

```nushell
def main [arg] {
  print $"Hello ($arg)!"
}

# How to make nushell scripts executable in Windows 11
# run cmd.exe as administrator and run these 2 commands
# it has to be cmd.exe because ftype and assoc are built-ins on cmd.exe
#
# assoc .nu=NushellScript
# ftype NushellScript=c:\some\path\.cargo\bin\nu.exe %1 %*
#
# note - should make this next part scriptable too
# run regedit.exe with administrator privileges
# go to key HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Session Manager\Environment
# add ;.NU to the PATHEXT key
# This allows you to type "im_executable World" without having to add the .nu extension
# restart cmd.exe/terminal/whatever shell hosting nushell
# Now you should be able to type "im_executable World", assuming im_executable.nu is in the current directory, and it should execute it
```

**Comment by mpawelski** [comment]
@fdncred Really? I am not supposed to execute nushell script _inside_ nushell shell? Sounds like a super weird thing, it makes sense that I cannot execute them in other shells or from windows explorer, but from nushell itself?

**Comment by fdncred** [comment]
I'm just explaining how windows works. You can't execute scripts from any other operating system either without special handling built into the os like shebangs and chmod +x.

We could perhaps do some special handling when a .nu is in the command position and source the file or something, but that doesn't exist right now.

**Comment by Nemeczek** [comment]
0.99.1 here. And sadly also affected 
```
~\Downloads> Account.json | from json                                                                  10/11/24 23:28:32
Error: nu::shell::io_error

  × I/O error
  help: %1 is not a valid Win32 application. (os error 193)

```

**Comment by fdncred** [comment]
I'm not sure what you're expecting nushell to do here. Account.json isn't a command in Windows. You'd typically need to do `open Account.json`.

**Comment by Nemeczek** [comment]
My bad... I wanted Account.json | open. Amazing project btw 👍

**Comment by fdncred** [comment]
@youk i can also confirm that my old instructions aren't working any longer. I think that's because we only shell out to cmd.exe for built-in commands now. If we're going to avail ourselves to Windows assoc/ftype/pathext stuff, we either need to shell out to cmd.exe or roll our own solution that looks up the .nu extension in the windows registry at HKEY_CLASSES_ROOT\.nu and then follow the key to HKEY_CLASSES_ROOT\nuscript (or whatever else it references), then follow that key to run the executable with parameters.

The real question is to determine when to do all that. My guess would be if a nushell script is in the command position maybe?

**Comment by fdncred** [comment]
Hopefully this fixes the problem. It does for me.
https://github.com/nushell/nushell/pull/14318

**Comment by Araxeus** [comment]
This wasn't actually fixed and is an undocumented regression. but ok

**Comment by fdncred** [comment]
Executing nushell scripts should be fixed. Executing bat and cmd seems to work fine. Executing ps1 may not be something nushell needs to do without pwsh.exe. Executing text files is definitely not something nushell should do, that relies on windows and the file extension association system. That's what the start command is about.

**Comment by fdncred** [comment]
We welcome people to come in and design things. However, we can't design everything since we're staffed by a team of volunteers, there are a million little details, and the team mostly does what they're interested in, like any open-source project. 

I can ask the core-team if they think ps1 files should be launch-able without specifying pwsh.exe and see what they think, so it's not only me making decisions. We also have weekly meetings that are open to the public that people can join and discuss items important to them.

**Comment by fdncred** [comment]
I'll re-open the issue so we can continue discussing how `.ps1` should be handled.

**Comment by fdncred** [comment]
Closing due to https://github.com/nushell/nushell/pull/14379

Let me know if I should reopen for some reason again.

**Comment by zhruith** [comment]
How about .py or .js ?
