### ISSUE TITLE
nushell have operator error

### ISSUE THREAD

**Issue by Thirdwinter** [nushell/nushell#13036]
### Describe the bug

Nushell is unable to handle certain plugin or automation tool-provided commands due to issues with path separators or unexpected operators. Additionally, Nushell struggles to process paths that are surrounded by `"` and separated by `'\'`, requiring the use of `\\` or `/` instead. These issues do not exist in other shells.

### How to reproduce

for example，use vscode maven_plugin to clean target 
![image](https://github.com/nushell/nushell/assets/149876001/08726502-3193-4edd-864a-bf5ecbcd0a0b)

### Expected behavior

I believe these errors should be addressed, or Nu's compatibility should be made more explicit.

### Configuration

| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.93.0                                                     |
| major              | 0                                                          |
| minor              | 93                                                         |
| patch              | 0                                                          |
| branch             |                                                            |
| commit_hash        | ca5ee3dba328468b10989f0c85d94a6c0284b767                   |
| build_os           | windows-x86_64                                             |
| build_target       | x86_64-pc-windows-msvc                                     |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                        |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc                              |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                        |
| build_time         | 2024-05-01 12:53:36 -07:00                                 |
| build_rust_channel | release                                                    |
| allocator          | mimalloc                                                   |
| features           | dataframe, default, sqlite, system-clipboard, trash, which |
| installed_plugins  | gstat, polars                                              |

### Additional context

I apologize, in some sense this may not impact usability, but I still hope that Nu can have higher compatibility, especially for these minor issues.

**Comment by ysthakur** [comment]
If you put a caret before the command name, it should work (`^"D:/.../mvn"`)

**Comment by ysthakur** [comment]
Sorry for the late reply. Is it possible for you to set a different shell in the IDE? In that case, you could set it to either a POSIX shell or a wrapper around Nushell
