### ISSUE TITLE
Build failed with flag --all-features [0.9.0]

### ISSUE THREAD

**Issue by pavelbinar** [nushell/nushell#1303]
**Describe the bug**
Build fail on Mac OS

**To Reproduce**
`cargo install nu --all-features --features=stable`

**Expected behavior**
Build successfully

**Screenshots**

 - OS: Mac OS Mojave 10.14.6
 - Version 0.9.0 Release
- cargo 1.40.0 (bc8e4c8be 2019-11-22)
- rustc 1.40.0 (73528e339 2019-12-16)
```
Warning: openssl@1.1 1.1.1d is already installed and up-to-date
To reinstall 1.1.1d, run `brew reinstall openssl@1.1`
Warning: cmake 3.16.3 is already installed and up-to-date
To reinstall 3.16.3, run `brew reinstall cmake`
```

**Error**
```
error: couldn't read /Users/pavelbinar/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-0.9.0/crates/nu-test-support/src/bins/chop.rs: No such file or directory (os error 2)
error: couldn't read /Users/pavelbinar/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-0.9.0/crates/nu-test-support/src/bins/cococo.rs: No such file or directory (os error 2)

error: couldn't read /Users/pavelbinar/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-0.9.0/crates/nu-test-support/src/bins/fail.rs: No such file or directory (os error 2)
error: aborting due to previous error
error: aborting due to previous error
error: aborting due to previous error
error: could not compile `nu`.
warning: build failed, waiting for other jobs to finish...
error: could not compile `nu`.
warning: build failed, waiting for other jobs to finish...
error: could not compile `nu`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `nu v0.9.0`, intermediate artifacts can be found at `/var/folders/8r/4x9j0wwd389_8j0yz6gk6zh00000gn/T/cargo-installHuEIcA`
Caused by:
  build failed
```

Full console log: https://gist.github.com/pavelbinar/c5b69a1455974b291ab5569f1d1703f5

**Comment by andrasio** [comment]
Please try `cargo install nu -all --features=stable` instead.

**Comment by pavelbinar** [comment]
`cargo install nu --features=stable` Works.

**Comment by andrasio** [comment]
@pavelbinar Thanks. Seems it doesn't quite work as expected. You are supposed to get the additional features installed (like `fetch`) but it's not installing them. Ideally you'd get them installed by doing `cargo install nu --all-features --features=stable` but will fail as you pointed it out.

Thanks for reporting it, we need to investigate.

(Please confirm `fetch` is not installed by running nu and trying something like `fetch https://formulae.brew.sh/api/formula/nushell.json`)

If you'd like to try out all the features installed, please try downloading directly the [pre-built binaries here](https://github.com/nushell/nushell/releases/tag/0.9.0).

Also, you could clone the repository and install it as well (for all the features). See [here for instructions](https://www.nushell.sh/installation.html#building-it-locally) regarding that.

**Comment by pavelbinar** [comment]
`fetch` test installed via `cargo install nu --features=stable`

```
~
❯ nu --version
nushell 0.9.0

~
❯ fetch https://formulae.brew.sh/api/formula/nushell.json
error: Command not found
- shell:1:55
1 | fetch https://formulae.brew.sh/api/formula/nushell.json
  | ^^^^^ command not found

~
```

BTW: I did try to build from source - works fine.
Where can I find the newly build binary? Does it install into the system path?

Thanks for all the hard work!

**Comment by andrasio** [comment]
@pavelbinar when you do `cargo install nu ..etc` it will install the binary in your path (usually `~/.cargo/bin` to overwrite you do `cargo install nu --features=stable --force`

If you clone the repository, you can do `cargo install nu --path . --features=stable` (and add `--force` if you'd like to overwrite the previous installation)

But it seems these are still not including all the plugins.

You could instead do:

`cargo build --all --features=stable && cargo run nu -all --features=stable`

**Comment by andrasio** [comment]
@pavelbinar the plugins are here `nu_plugin_[command name]`, you could try installing them separately. For instance, `fetch` would be `cargo install nu_plugin_fetch`

Try that, then run nu and it should pick it up.

**Comment by andrasio** [comment]
@pavelbinar You can find the latest pre-built [binary here](https://github.com/nushell/nushell/releases/tag/0.9.0)

**Comment by pavelbinar** [comment]
Thank you. I am good.

**Comment by andrasio** [comment]
@pavelbinar Please report any issues! Feedback is welcomed. More than welcome if you join the [discord chat](https://discordapp.com/invite/NtAbbGn).

**Comment by jonathandturner** [comment]
I've updated the instructions to use `cargo build --workspace --features=stable`

We should also potentially extend this to work on `cargo install` as well

**Comment by jonathandturner** [comment]
Closing, as this works with `cargo install` as well (via `cargo install --features=stable`)
