### ISSUE TITLE
Can run open command of bash in nushell

### ISSUE THREAD

**Issue by kmr-ankitt** [nushell/nushell#13046]
### Describe the bug

# Open command not working in nushell

![image](https://github.com/nushell/nushell/assets/90329779/212371f9-1a97-4eec-94c4-10b9f5a8d18c)

### How to reproduce

1. Open nushell
2. run `open .`

### Expected behavior

It should open the current directory in file explorer..

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.93.0                                          |
| major              | 0                                               |
| minor              | 93                                              |
| patch              | 0                                               |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.78.0 (54d8815d0 2024-03-26)             |
| build_time         | 2024-05-21 12:34:29 +05:30                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
I don't think `open` works this way but I'm pretty sure `start` does.

**Comment by Kissaki** [comment]
The [`open`](https://www.nushell.sh/commands/docs/open.html) command

> Load a file into a cell, converting to table if possible (avoid by appending '--raw').

The current directory is not a file.

**Comment by Kissaki** [comment]
To open the current directory in explorer you can run

```nu
explorer.exe $env.PWD
```
