### ISSUE TITLE
Cursor no longer blink after upgrading to nushell 0.94.x

### ISSUE THREAD

**Issue by CarterLi** [nushell/nushell#13049]
### Describe the bug

As the title says

### How to reproduce

1. run nushell

### Expected behavior

Cursor should blink

### Screenshots

N/A

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.94.2                                                           |
| major              | 0                                                                |
| minor              | 94                                                               |
| patch              | 2                                                                |
| branch             | makepkg                                                          |
| commit_hash        | be8c1dc0066cd1034a6b110a622f47b516bfe029                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29) (Arch Linux rust 1:1.78.0-1) |
| cargo_version      | cargo 1.78.0                                                     |
| build_time         | 2024-06-04 09:13:10 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | default, sqlite, system-clipboard, trash, which                  |
| installed_plugins  |                                                                  |

### Additional context

Found on Windows; tested on Linux

**Comment by kubouch** [comment]
I'm on Linux + Alacritty and the cursor doesn't blink either. However, it doesn't blink also on 0.93.0. Was it ever supposed to blink? What terminal emulator do you use?

**Comment by fdncred** [comment]
Our config should support what crossterm supports which is
```rust
pub enum SetCursorStyle {
    /// Default cursor shape configured by the user.
    DefaultUserShape,
    /// A blinking block cursor shape (■).
    BlinkingBlock,
    /// A non blinking block cursor shape (inverse of `BlinkingBlock`).
    SteadyBlock,
    /// A blinking underscore cursor shape(_).
    BlinkingUnderScore,
    /// A non blinking underscore cursor shape (inverse of `BlinkingUnderScore`).
    SteadyUnderScore,
    /// A blinking cursor bar shape (|)
    BlinkingBar,
    /// A steady cursor bar shape (inverse of `BlinkingBar`).
    SteadyBar,
}
```
