### ISSUE TITLE
Command 'du' on macOS throws error: "Operation not permitted (os error 1)"

### ISSUE THREAD

**Issue by kvrhdn** [nushell/nushell#1304]
**Describe the bug**
So I wanted to run the new `du` command, and then this happened 😅 

<img width="424" alt="Screenshot 2020-01-29 at 21 10 53" src="https://user-images.githubusercontent.com/7748404/73393460-fbeb6300-42db-11ea-8511-9d5f6419d2d4.png">

I assume it caused by the new security features introduced with Catalina, i.e. https://www.howtogeek.com/443611/how-macos-catalinas-new-security-features-work/

**System**
I'm running
- macOS Catalina 10.15.2 (19C57)
- nu 0.9.0

**Comment by thegedge** [comment]
Works for me.

Did you run this in a directory where there was a subdirectory/file that your account didn't have the privileges to stat? I'm guessing that's the problem, which is still a bug, just interested if that's the problem. You can try running `^du -d1` to see if it has the same issue (although it may complete, but may output errors to stderr).

**Comment by koenaad** [comment]
Ah, you're right! Running `^du` I get errors like:
```
du: ./Library/Application Support/CallHistoryTransactions: Operation not permitted
```
`du` works fine in 'regular' directories.

I'd consider it an enhancement then to limit the impact of these errors and still list all other directories.

**Comment by thegedge** [comment]
Yeah, I think there's a more general enhancement here, or at least something to think about: when an output stream emits an error, should we fail immediately, or ignore? I think the latter shouldn't be done automatically, but perhaps a user could request it.
