### ISSUE TITLE
polars open returns ComputeError(ErrString("invalid utf-8 sequence")) without details

### ISSUE THREAD

**Issue by devurandom** [nushell/nushell#13042]
### Describe the bug

Nushell is unable to read my Parquet file:
```
❯ let df = polars open survey.parquet
Error:   × Parquet reader error
   ╭─[entry #37:1:10]
 1 │ let df = polars open survey.parquet
   ·          ─────┬─────
   ·               ╰── ComputeError(ErrString("invalid utf-8 sequence"))
   ╰────
```

IntelliJ's viewer describes the file's DDL as:
```
message survey_scheme {
    required binary survey_data (STRING)
    required binary survey_data_freeform (STRING)
    required binary status (STRING)
    required binary email (STRING)
}
```

The data was originally imported into ClickHouse from a CSV file in ISO-8859-15 encoding. When exporting the data as Parquet, which uses UTF-8 to encode strings, some strings became garbled. Thus Nushell's assertion that the file contains an "invalid utf-8 sequence" is correct, but also not very helpful, as it does not provide any information which record (row/column) the error originated from.

### How to reproduce

1. Create a CSV in ISO-8859-15 encoding
2. Import it into ClickHouse
3. Export the data as Parquet
4. Try to load the Parquet file into Nushell

Any other way to create a Parquet file with wrongly encoded strings will likely yield the same result.

### Expected behavior

Nushell could print the coordinates of the field where the error occurred, e.g. "column survey_data_freeform, row 1234: invalid utf-8 sequence in".

### Configuration

| key                | value                                                                |
| ------------------ | -------------------------------------------------------------------- |
| version            | 0.94.1                                                               |
| major              | 0                                                                    |
| minor              | 94                                                                   |
| patch              | 1                                                                    |
| branch             |                                                                      |
| commit_hash        | f3cf693ec701ab3086f984a8aeadfc9b50fadd90                             |
| build_os           | linux-x86_64                                                         |
| build_target       | x86_64-unknown-linux-gnu                                             |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                                  |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                                      |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                                  |
| build_time         | 2024-05-30 23:10:14 +00:00                                           |
| build_rust_channel | release                                                              |
| allocator          | mimalloc                                                             |
| features           | default, sqlite, static-link-openssl, system-clipboard, trash, which |
| installed_plugins  | polars                                                               |

**Comment by fdncred** [comment]
I would try to open the file up through `decode` to change the encoding. You can see how with `decode --help`, probably something like `open -r file.csv | decode ISO-8859-15 | save file.utf8`

**Comment by devurandom** [comment]
Thanks for the advice! I managed to fix the original CSV file using `iconv`, re-imported it into ClickHouse, and then exported it again to Parquet. The fixed Parquet file can be read by Nushell without issues.
My report was mainly about the error message that was not very helpful to locate the problem. With information which row/column had caused the error it would have been a lot faster to figure out the root of the problem.

**Comment by ayax79** [comment]
I'll try to reproduce the issue and see if there's any additional information we can extract from the Polars error. Our ability to report details might be limited, as Polars errors are often quite opaque.

**Comment by ayax79** [comment]
@devurandom, I wasn't able to reproduce with these steps.. it might be because I am on a mac. Is there a chance you could post the original parquet file or one like it that you know fails?

**Comment by devurandom** [comment]
> @devurandom, I wasn't able to reproduce with these steps.. it might be because I am on a mac. Is there a chance you could post the original parquet file or one like it that you know fails?

Thanks for looking into this!

I cannot attach the original file, but I crafted a small example CSV file, loaded it into ClickHouse, exported it as Parquet. When trying to `polars open` it in Nushell, the same error as in the original report is shown. Please find both the original CSV and the Parquet file attached: [test.zip](https://github.com/user-attachments/files/15545897/test.zip)

**Comment by devurandom** [comment]
```nushell
nu --version
# 0.100.0

let df = polars open test.parquet
# (No error)
```
