### ISSUE TITLE
Can't interrupt `open` on CSV files

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#13064]
### Describe the bug

Interrupts don't work when opening CSV files.

### How to reproduce

Get a 1.5Gb file and run `open sample.csv`.  Interrupts won' t work for quite some time.

### Expected behavior

Immediate interrupt.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.92.0                                                       |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.77.0 (aedd173a2 2024-03-17) (Alpine Linux 1.77.0-r0) |
| cargo_version      | cargo 1.77.0                                                 |
| build_time         | 2024-04-03 10:33:03 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, trash, which                                |
| installed_plugins  |                                                              |

0.92, a bit outdated, but I don't think there were any major changes to `open` or `from csv`.

**Comment by rgwood** [comment]
Thanks for the bug report, good catch. I have a fix ready: #13076

**Comment by rgwood** [comment]
Nevermind, this is already fixed on the latest Nu. Please test on the latest version before filing bugs.
