### ISSUE TITLE
New shell_integration config won't parse

### ISSUE THREAD

**Issue by Eragra3** [nushell/nushell#13063]
### Describe the bug

I recently updated to 0.94.2, my old config had `shell_integration: true` - that seems to work fine, but throws deprecation warning.
```
boolean value is deprecated, should be a record. see `config nu --default`.
```

I decided to update my config with what is inside `config nu --default` and then config completely fails to parse with following error:
```
can't convert record<osc2: bool, osc7: bool, osc8: bool, osc9_9: bool, osc133: bool, osc633: bool, reset_application_mode: bool> to boolean
```

These errors contradict each other. Diffing my new config with `config nu --default` doesn't show any differences in that section.
I don't see others getting this error, so I'm assuming something is corrupted on my machine?

### How to reproduce

1. Set `shell_integration: true`
2. Run to see warning
3. Set `shell_integration` to new record format
4. Running should fail to parse completely

### Expected behavior

Nushell should start just fine with both configs

### Screenshots

New config
![obraz](https://github.com/nushell/nushell/assets/9082983/39940a2d-b7b0-4781-bde9-049c8c3f36c5)

Old config
![obraz](https://github.com/nushell/nushell/assets/9082983/7d16eceb-0097-421b-beda-6197001fc23f)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.94.2                                          |
| major              | 0                                               |
| minor              | 94                                              |
| patch              | 2                                               |
| branch             |                                                 |
| commit_hash        | be8c1dc0066cd1034a6b110a622f47b516bfe029        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-06-03 19:27:48 +00:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  | highlight                                       |

**Comment by Kissaki** [comment]
The [docs for `config nu` says](https://www.nushell.sh/commands/docs/config_nu.html):

> Edit nu configurations.

> `    --default, -d: Print default config.nu file instead.`

I read this as using `--default` *only* prints. Of course, if that were the case, it doesn't make sense that it throws an error either.

Maybe it tries to merge the two, and can't because of a mismatch?

---

As an alternative to fixing your warning, you can manually edit the nu config (with `config nu`) and add the record, or use [`config rest`](https://www.nushell.sh/commands/docs/config_reset.html) to reset the configs (you can afterwards manually compare and merge back in your own previous configuration from the backed up files in the same folder).

**Comment by Eragra3** [comment]
Ok I found the issue, apparently old PWD workaround somehow causes configuration parser to fail (???).

I removed code found in this issue https://github.com/nushell/nushell/issues/10166#issue-1875317528 from my config.nu and it works again.

This is the offending script:
```
if $env.config.shell_integration {
  $env.config.hooks.env_change = ($env.config.hooks.env_change | upsert PWD {|config|
    let val = $config.PWD? | default []

    $val | append {|_, after|
      mut val = $after

      if not ($env.IS_WSL? | is-empty) {
        $val = (wslpath -w $val)
      }

      print -n $"(ansi -o '9;9;')($val)(ansi "st")"
    }
  })
}
```

**Comment by Eragra3** [comment]
Ahh I see now, `if $env.config.shell_integration {` expects `shell_integration` to be a boolean, which incidentally was the recent change in config.

So this was just a series of unfortunate events. I'll close the issue now...
