### ISSUE TITLE
`go install -ldflags="options"` works in `0.94.0` but not in `0.94.1`, `0.94.2`

### ISSUE THREAD

**Issue by doongjohn** [nushell/nushell#13066]
### Describe the bug

I used this line of code to install https://github.com/gokcehan/lf however it doesn't work anymore.
```nushell
with-env {CGO_ENABLED: 0} { go install -ldflags="-s -w" github.com/gokcehan/lf@latest }
```

### How to reproduce

1. use version `0.94.1` or `0.94.2`
2. run command: `with-env {CGO_ENABLED: 0} { go install -ldflags="-s -w" github.com/gokcehan/lf@latest }`
3. error
```
❯ with-env {CGO_ENABLED: 0} { go install -ldflags="-s -w" github.com/gokcehan/lf@latest }
invalid value "\"-s -w\"" for flag -ldflags: missing =<value> in <pattern>=<value>
usage: go install [build flags] [packages]
Run 'go help install' for details.
```
using a single quote doesn't help
```
❯ with-env {CGO_ENABLED: 0} { go install -ldflags='-s -w' github.com/gokcehan/lf@latest }
invalid value "'-s -w'" for flag -ldflags: missing =<value> in <pattern>=<value>
usage: go install [build flags] [packages]
Run 'go help install' for details.
```

### Expected behavior

`-ldflags="-s -w"` should work.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.94.2                                          |
| major              | 0                                               |
| minor              | 94                                              |
| patch              | 2                                               |
| branch             |                                                 |
| commit_hash        | be8c1dc0066cd1034a6b110a622f47b516bfe029        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-06-03 19:27:48 +00:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                 |

**Comment by WindSoilder** [comment]
I can also reproduce it on 0.94.0
```
❯ version
╭────────────────────┬──────────────────────────────────────────────────────────────────────╮
│ version            │ 0.94.0                                                               │
│ major              │ 0                                                                    │
│ minor              │ 94                                                                   │
│ patch              │ 0                                                                    │
│ branch             │                                                                      │
│ commit_hash        │ 61182deb96c84fe1171179edcfeef9f1d301e8fb                             │
│ build_os           │ linux-x86_64                                                         │
│ build_target       │ x86_64-unknown-linux-musl                                            │
│ rust_version       │ rustc 1.77.2 (25ef9e3d8 2024-04-09)                                  │
│ rust_channel       │ 1.77.2-x86_64-unknown-linux-gnu                                      │
│ cargo_version      │ cargo 1.77.2 (e52e36006 2024-03-26)                                  │
│ build_time         │ 2024-05-28 19:14:48 +00:00                                           │
│ build_rust_channel │ release                                                              │
│ allocator          │ mimalloc                                                             │
│ features           │ default, sqlite, static-link-openssl, system-clipboard, trash, which │
│ installed_plugins  │ explore                                                              │
╰────────────────────┴──────────────────────────────────────────────────────────────────────╯

/tmp/nu-0.94.0-x86_64-unknown-linux-musl
❯ go install -ldflags='-s -w' github.com/gokcehan/lf@latest
invalid value "'-s -w'" for flag -ldflags: missing =<value> in <pattern>=<value>
usage: go install [build flags] [packages]
Run 'go help install' for details.
```
