### ISSUE TITLE
Copy (ctrl+c. ctrl+shift+c) does not work in Vim or ignored

### ISSUE THREAD

**Issue by kyxap** [nushell/nushell#13070]
### Describe the bug

Hey all, 

New user here!
For some reason seems like "copy" (ctrl+c. ctrl+shift+c) does not work if I'm doing this inside of the vim. 
But I can paste old clipboard but it always corrupted 

### How to reproduce

- choco install vim
- open file with vim
- select text and try to copy (ctrl+c. ctrl+shift+c)
- try to past (ctrl-v)
vim v9.1.466

### Expected behavior

Copied text is passed 

Actual: old clipboard is used and just copied is ignored, also seems like old clipboard is corrupted when pasted

### Screenshots

![ctrl+c](https://github.com/nushell/nushell/assets/3080529/890efa8e-96ca-4d25-9574-263ba3a704eb)

### Configuration

```bash
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.94.1                                          |
| major              | 0                                               |
| minor              | 94                                              |
| patch              | 1                                               |
| branch             |                                                 |
| commit_hash        | f3cf693ec701ab3086f984a8aeadfc9b50fadd90        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-05-30 23:14:11 +00:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  |  
```

### Additional context

vim v9.1.466
windows 11

**Comment by WindSoilder** [comment]
Hi, I'm not really sure if it's a nushell issue.
Does ctrl+c work if you are running vim inside powershell?

**Comment by kyxap** [comment]
move `source ~/.oh-my-posh.nu` to the  C:\Users\user_name\AppData\Roaming\nushell\env.nu ($nu.env-path) and got same results

**Comment by kyxap** [comment]
> Hi, I'm not really sure if it's a nushell issue. Does ctrl+c work if you are running vim inside powershell?

you are correct.. for some reason that vim (installed from choco) does not work in powershell or git-bash, but my old vim from `C:\Program Files\Git\usr\bin' works with no issue :(
