### ISSUE TITLE
Improve highlighting for bad parse

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#1308]
**Is your feature request related to a problem? Please describe.**
Commands that fail to parse could be clearer to user, as they currently show in a subtle grey:

![screenshot1](https://user-images.githubusercontent.com/833576/73477686-bb82f800-4362-11ea-837d-67674742ca3e.png)

**Describe the solution you'd like**
Highlight parse issues (when typing) like we show them after executing the command:

![screenshot2](https://user-images.githubusercontent.com/833576/73477701-c2116f80-4362-11ea-9bd1-600e343b3580.png)

**Comment by coolshaurya** [comment]
This works on my machine -
![image](https://user-images.githubusercontent.com/32027323/73538294-aa181980-4450-11ea-84e0-95d656a3ff6e.png)

**Comment by thegedge** [comment]
@coolshaurya is that while typing, or after you've pressed `<Return>`?

**Comment by coolshaurya** [comment]
while typing 
![Peek 2020-01-31 21-39](https://user-images.githubusercontent.com/32027323/73554727-44d52000-4472-11ea-9da2-feaac59f58a8.gif)

**Comment by thegedge** [comment]
Thanks! Seems like it could be an integration issue with the terminal then.

**Comment by jonathandturner** [comment]
@thegedge closing this issue as it seems to work as originally described, but you might want to open an issue to improve the UX.
