### ISSUE TITLE
Double-slash (`//`) after tilde (`~`) symbol in WD before command

### ISSUE THREAD

**Issue by Antosser** [nushell/nushell#13098]
### Question

Anytime I am in a subdirectory of ~, a double-slash gets printed after the ~ instead of a regular slash and looks very weird. Is this a bug in my configuration, a bug, or a new feature?

### Additional context and details

![image](https://github.com/nushell/nushell/assets/71790328/4c1c8218-6999-4253-b662-650a741925af)

Config file: https://termbin.com/j5cl6
Env file: https://termbin.com/ij4l

**Comment by fdncred** [comment]
I've seen this mentioned a couple times. My guess is that it's a bug in our `create_left_prompt` custom command in the env.nu but I have not confirmed it yet.

**Comment by Antosser** [comment]
I was using Linux Mint. I backed up my config and reset it to the defaults and the issue disappeared
