### ISSUE TITLE
Rename `for --numbered` to `for --enumerate` (or deprecate entirely?)

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#13094]
### Related problem

It's a minor nitpick, but `for --numbered` is essentially the same as an `enumerate` command.  I started out thinking we should just rename it to `--enumerate` for consistency, but then I realized that it is (or at least seems to be) fairly redundant.

Taking the example from `help for`:

```Nushell
> for $it in ['bob' 'fred'] --numbered { print $"($it.index) is ($it.item)" }
0 is bob
1 is fred
> for $it in (['bob' 'fred'] | enumerate) { print $"($it.index) is ($it.item)" }
0 is bob
1 is fred
```

### Describe the solution you'd like

If `for` is going to have a specialized argument for this, then I'd like to see it renamed `--enumerate` for consistency.

But given the ease of just using the `enumerate` command in the first place, should the flag just be deprecated/removed entirely?

### Additional context and details

Performance seems nearly identical here:

```nu
let variants = [
  { for $it in 1..100_000 --numbered { $"($it.index) is ($it.item)" } }
  { for $it in (1..100_000 | enumerate) { $"($it.index) is ($it.item)" } }
]

use std bench

$variants
| each {|closure|
    view source $closure
    | wrap variant
    | merge (
        bench $closure --rounds 10
        | reject times
        | format duration ms ...($in | columns)
      )
  }
| collect

╭───┬──────────────────────────────────────────────────────────────────────────┬────────────┬────────────┬────────────┬──────────╮
│ # │                                 variant                                  │    mean    │    min     │    max     │   std    │
├───┼──────────────────────────────────────────────────────────────────────────┼────────────┼────────────┼────────────┼──────────┤
│ 0 │ { for $it in 1..100_000 --numbered { $"($it.index) is ($it.item)" } }    │ 1223.95 ms │ 1215.62 ms │ 1234.94 ms │ 7.05 ms  │
│ 1 │ { for $it in (1..100_000 | enumerate) { $"($it.index) is ($it.item)" } } │ 1235.85 ms │ 1217.52 ms │ 1264.56 ms │ 13.19 ms │
╰───┴──────────────────────────────────────────────────────────────────────────┴────────────┴────────────┴────────────┴──────────╯
```

**Comment by fdncred** [comment]
I think --numbered was supposed to be removed when the same type of thing was removed from the `each` command.

**Comment by NotTheDr01ds** [comment]
@fdncred Ok, so no objection to me trying to mark it as deprecated?  I'm assuming I can look at a previous deprecation and replicate it based on my still limited Rust-skills.

**Comment by hustcer** [comment]
I think we can rename it to `--enumerate` rather than remove it.  `for` is commonly used and easier to find, a new comer may get frustrated if he doesn't know `enumerate`

**Comment by fdncred** [comment]
ya, i think it just needs to be removed but add an example with `| enumerate` to stay within our compositional mantra

**Comment by NotTheDr01ds** [comment]
> I think `--numbered` was supposed to be removed when the same type of thing was removed from the `each` command.

You're absolutely right - I just randomly<sup>1</sup> came across the reason why it *wasn't* removed at the time.  You suggested it should be in [#7777](https://github.com/nushell/nushell/pull/7777#issuecomment-1407414317)

> I wonder if it's still applicable, now that we have the `enumerate` command, to go back through our code and remove all the `--numbered` parameters on `each`, `for`, and the other commands that implement them? I haven't even tried to use `enumerate` on `for` or any other commands other than `each`.

But that PR had specifically *excluded* `for` since it was originally based on #6994 which didn't support `for`.

---

<sup>1</sup> A totally unrelated Discord search just popped up that PR ...

**Comment by weirdan** [comment]
`for --numbered` was removed in 0.96.0: https://www.nushell.sh/blog/2024-07-23-nushell_0_96_0.html#for-numbered-toc

**Comment by hustcer** [comment]
@weirdan Thanks 👍

**Comment by NotTheDr01ds** [comment]
@weirdan Thanks!  Totally forgot to close this when I implemented.  Of course, having to wait a month between deprecation and removal is my excuse for it slipping my mind ;-)
