### ISSUE TITLE
How I can run an subcommand inside a string?

### ISSUE THREAD

**Issue by DevAles** [nushell/nushell#13108]
### Question

`ollama run phi3 "Read this: $(cat file.txt)"´

I'm migrating to nushell, how I can do this kind of subcommand inside of strings?
(Sorry for my English and thanks for maintaining this project)

**Comment by kubouch** [comment]
You'll need string interpolation: https://www.nushell.sh/lang-guide/chapters/strings_and_text.html#string-interpolation
