### ISSUE TITLE
How to change the default output encoding?

### ISSUE THREAD

**Issue by timxx** [nushell/nushell#13148]
### Question

For the new git for windows (2.45), it just prints garbled text for CJK. Seems have to change the output encoding the utf-8.

For cmd it can uses `chcp 65001`, and for powershell it can changed by `$OutputEncoding = [Console]::OutputEncoding = [System.Text.Encoding]::UTF8`.

So how to change the output encoding for nushell?

**Comment by fdncred** [comment]
Nushell uses rust strings which are utf-8 already so there's no need to change anything in nushell to get utf-8.

**Comment by timxx** [comment]
> Nushell uses rust strings which are utf-8 already so there's no need to change anything in nushell to get utf-8.

But seems not work for git

![image](https://github.com/nushell/nushell/assets/1598262/56aafab9-d8bf-457b-ab10-dfb936b7c406)

I can use `chcp 65001` for workaround, but I have to set it every new nushell window.
![image](https://github.com/nushell/nushell/assets/1598262/55cd7b1f-1682-4c08-bfdf-1f6cb34a6af2)

**Comment by fdncred** [comment]
So, that means your question is how to set your terminal to 65001 every time. I've googled it before and that's what I did for my Windows machine. So I know it's possible. IIRC, there was some registry setting I had to change.

**Comment by devyn** [comment]
Sounds like it's probably the region settings control panel, where you can set UTF-8 as the "non-Unicode" codepage (remember: Unicode in Windows means wide char UTF-16)

https://stackoverflow.com/a/57134096/371407

All Windows console hosts including Windows terminal use the system code page encoding, not wide chars, which is why you have to `chcp`

**Comment by timxx** [comment]
> So, that means your question is how to set your terminal to 65001 every time. I've googled it before and that's what I did for my Windows machine. So I know it's possible. IIRC, there was some registry setting I had to change.

I'd prefer use nushell it's way, not by calling `chcp`. Such as powershell can change with `$OutputEncoding = [Console]::OutputEncoding = [System.Text.Encoding]::UTF8`, and can be added to profile

**Comment by timxx** [comment]
> Sounds like it's probably the region settings control panel, where you can set UTF-8 as the "non-Unicode" codepage (remember: Unicode in Windows means wide char UTF-16)
> 
> https://stackoverflow.com/a/57134096/371407
> 
> All Windows console hosts including Windows Terminal use the system code page encoding, not wide chars, which is why you have to `chcp`

I have tried the regional settings before, but the impact is too great. Some software does not support it, which will also cause the entire interface to become garbled.

**Comment by Magicgazer** [comment]
Add the following line at the end of the `config.nu`:

``` 
chcp 65001 | save NUL 
```

This will cause Nushell to switch to the active code page of 65001 while hiding the output of the command

**Comment by devyn** [comment]
You can just pipe to null (`| null`)

**Comment by fdncred** [comment]
One last point of clarification, `chcp` is a Windows command and doesn't change anything that nushell does. It changes the active code page in Winodws which can enable Windows to display characters of a certain code page. https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/chcp
