### ISSUE TITLE
`table` help example results are wrong

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#13149]
### Describe the bug

For `help table`, the `--expand` and `--collapse` examples in the help are not rendered correctly (even with #13146).

Also, for tracking, adding other commands with the same issue:

* `help flatten`
* `help zip`

### How to reproduce

`help table` then copy the second and third examples to the clipboard and run them.  The results shown in the help are not correct.

### Expected behavior

Example results match what the user will see when they run the command

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.94.2                                          |
| major              | 0                                               |
| minor              | 94                                              |
| patch              | 2                                               |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-06-10 14:29:01 -04:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
I don't want to remove the examples, but rather fix them somehow in the code.

**Comment by fdncred** [comment]
I played around with this in documentation.rs, just trying to hard-code all tables to `--expand` but couldn't get it to work. I'm probably missing some key concept here.

![image](https://github.com/nushell/nushell/assets/343840/5618fd51-0ada-42a7-a84c-48d074b0e935)

**Comment by NotTheDr01ds** [comment]
> I don't want to remove the examples, but rather fix them somehow in the code.

Ok, I've edited the issue to reflect *that*.  I also looked at this a bit last week to see if I could do anything about it, but didn't come up with anything either.  Of course, you have a much better chance than I do ;-)

But regardless, I'll leave this open as an issue on the core itself rather than removing the examples.

**Comment by NotTheDr01ds** [comment]
> I'm probably missing some key concept here.

Actually, you almost nailed it.  If you check your implementation against `help zip`, you'll see that it works.

The problem with `help table` is that the actual hardcoded `result`s are wrong.

I've fixed the `table --expand` result, but I'm not sure that `help --collapse` is fixable without being able to conditionally run `--compact` against it.  That result "table" can't (I don't believe) be represented in Rust.  Please correct me if I'm wrong.

I think perhaps I could attach a `--collapse` in the `table.rs` example itself, but I'm not sure yet.

**Comment by fdncred** [comment]
> The problem with help table is that the actual hardcoded results are wrong.

doh! that explains it then.

what i was thinking of doing when i wrote that code was to check the example.example to see if it ended with `--expand` or `--collapse` and then change the call appropriately before passing it into .run()
