### ISSUE TITLE
v0.94.2 Operator changes

### ISSUE THREAD

**Issue by Thirdwinter** [nushell/nushell#13163]
### Question

panache-git in the nu-script repository, I don't quite know how to fix this error, please help me
![image](https://github.com/nushell/nushell/assets/149876001/f3f4defb-119a-4374-8f1d-4d90a5827a4e)

**Comment by fdncred** [comment]
I don't really like the `--not` removal just because I think it's unintuitive, but I think what you'd need to do is change the script to say `| not (str contains '(detached)')` and then do that everywhere else in the script that it's using --not.

**Comment by Thirdwinter** [comment]
![image](https://github.com/nushell/nushell/assets/149876001/aa36e4be-9d1e-43dc-b80c-686c5c12faa1)
Sorry, is this what you mean? I tried to modify it but failed. Unfortunately, I don't understand the syntax and api of nu very well.

**Comment by fdncred** [comment]
@ysthakur Any advice here?

**Comment by IanManske** [comment]
Oops, looks like that script is out of date. There is an example in the [release notes](https://www.nushell.sh/blog/2024-05-28-nushell_0_94_0.html#str-contains-not-toc) (the `$in` example) that you can use to edit the script manually. 

But the script should be updated soon anyways.

**Comment by ysthakur** [comment]
> @ysthakur Any advice here?

I was thinking either `... | first | not ($in | str contains '(detached)')` or `not(... | first | str contains '(detached)')`, but putting a `not $in` at the end seems like a much simpler approach. No need for parentheses with that one.
