### ISSUE TITLE
`std help error make` fails

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#13189]
### Describe the bug

Looks like the `error make` example in the help might be getting executed in `std help`.  I'll investigate further when I get a chance.

### How to reproduce

```nu
> use std help
> help error make
Error: nu::shell::eval_block_with_input

  × Eval block failed with pipeline input
     ╭─[NU_STDLIB_VIRTUAL_DIR/std/help.nu:692:21]
 691 │ ] {
 692 │     let commands = (scope commands | sort-by name)
     ·                     ───────┬──────
     ·                            ╰── source value
 693 │
     ╰────

Error:   × my custom error message
```

### Expected behavior

Displays the help page for `error make`

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.94.2                                          |
| major              | 0                                               |
| minor              | 94                                              |
| patch              | 2                                               |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-06-10 14:29:01 -04:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  | jwalk                                           |

### Additional context

`my custom error message` is one of the examples in the doc for `error make`.  Something is getting executed here, which shouldn't be happening.

**Comment by fdncred** [comment]
I wonder what that's all about. 🤔
