### ISSUE TITLE
Add external commands in path to autocomplete

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1318]
**Is your feature request related to a problem? Please describe.**
As we add better support for autocomplete, we should look through the path to find what external commands are available, then add them to the list of commands we can complete.

**Describe the solution you'd like**
A simple registry entry that doesn't show up in `help commands` but still is available for autocomplete.

**Describe alternatives you've considered**
We could do a more extensive support by adding them to help commands, but I think that might be confusing.

**Comment by thegedge** [comment]
We're consolidating the completions effort in #290 for now. After we close off that issue, we can open (or reopen) specific issues related to completions that weren't resolved with the consolidated effort.
