### ISSUE TITLE
`polars to-parquet` with `null` values or mismatching types: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by devurandom** [nushell/nushell#13185]
### Describe the bug

```
❯ [[a]; [null]] | polars into-df
 #   a
 0

❯ [[a]; [null]] | polars into-df | polars to-parquet test.parquet
thread 'polars-0' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-arrow-0.39.2/src/compute/aggregate/memory.rs:68:18:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error:   × Failed to receive response to plugin call from `polars`
   ╭─[entry #51:1:34]
 1 │ [[a]; [null]] | polars into-df | polars to-parquet test.parquet
   ·                                  ────────┬────────
   ·                                          ╰── while waiting for this operation to complete
   ╰────
  help: try restarting the plugin with `plugin use 'polars'`
```

### How to reproduce

1. Run `[[a]; [null]] | polars into-df | polars to-parquet test.parquet`
2. Observe panic report

### Expected behavior

I would expect Nushell to encode a `null` cell into the Parquet file.

### Configuration

`❯ version | transpose key value | to md --pretty`
| key                | value                                                                |
| ------------------ | -------------------------------------------------------------------- |
| version            | 0.94.1                                                               |
| major              | 0                                                                    |
| minor              | 94                                                                   |
| patch              | 1                                                                    |
| branch             |                                                                      |
| commit_hash        | f3cf693ec701ab3086f984a8aeadfc9b50fadd90                             |
| build_os           | linux-x86_64                                                         |
| build_target       | x86_64-unknown-linux-gnu                                             |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                                  |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                                      |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                                  |
| build_time         | 2024-05-30 23:10:14 +00:00                                           |
| build_rust_channel | release                                                              |
| allocator          | mimalloc                                                             |
| features           | default, sqlite, static-link-openssl, system-clipboard, trash, which |
| installed_plugins  | custom_values, formats, gstat, inc, polars, query                    |

Related: https://github.com/nushell/nushell/issues/12726

**Comment by devurandom** [comment]
This is not particular to `null` values, but works also with mismatching types:
```
❯ [[a]; [""] [1]] | polars into-df | polars to-parquet test.parquet
thread 'polars-5' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/polars-arrow-0.39.2/src/compute/aggregate/memory.rs:68:18:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error:   × Failed to receive response to plugin call from `polars`
   ╭─[entry #59:1:36]
 1 │ [[a]; [""] [1]] | polars into-df | polars to-parquet test.parquet
   ·                                    ────────┬────────
   ·                                            ╰── while waiting for this operation to complete
   ╰────
  help: try restarting the plugin with `plugin use 'polars'`
```

**Comment by devurandom** [comment]
Related: https://github.com/nushell/nushell/issues/12726

**Comment by devurandom** [comment]
```nushell
nu --version
# 0.100.0

[[a]; [null]] | polars into-df | polars save test.parquet
# Error:   × Error saving file
#    ╭─[entry #16:1:46]
#  1 │ [[a]; [null]] | polars into-df | polars save test.parquet
#    ·                                              ──────┬─────
#    ·                                                    ╰── cannot write 'Object' datatype to parquet
#    ╰────

[[a]; [""] [1]] | polars into-df | polars save test.parquet
# Error:   × Error saving file
#    ╭─[entry #17:1:48]
#  1 │ [[a]; [""] [1]] | polars into-df | polars save test.parquet
#    ·                                                ──────┬─────
#    ·                                                      ╰── cannot write 'Object' datatype to parquet
#    ╰────

[[a]; [1] [1]] | polars into-df | polars save test.parquet
# (No error)
```

**Comment by ayax79** [comment]
You have to provide a schema in this case since object type is not a valid parquet type. We default to object type when the type cannot be determined

```nushell
[[a]; [null]] | polars into-df -s {a: str}  | polars save /tmp/foo.parquet
```

Also, you cannot mix numeric an string types. This will also result in an object type, which is incompatible with parquet.

**Comment by devurandom** [comment]
Would it be possible to improve the error message?  From "cannot write 'Object' datatype to parquet" I would not have concluded the things you explain this error to mean, let alone how to change my code to avoid the error.
