### ISSUE TITLE
Edge case! Odd error! Recognizing a `def` name inside an `each`.

### ISSUE THREAD

**Issue by c4lliope** [nushell/nushell#13202]
```nu

~/.build/nixos> [ a b ] | each {|name| def $name [] { print [ "call:" $name ] } }
Error: nu::parser::unknown_state

  × Unknown state.
   ╭─[entry #1:1:28]
 1 │ [ a b ] | each {|name| def $name [] { print [ "call:" $name ] } }
   ·                            ──┬──
   ·                              ╰── Could not get string from string expression
   ╰────

~/.build/nixos> [ a b ] | each {|name| def $name [] { print [ "call:" $name ] } }
```

**Comment by fdncred** [comment]
I believe this is working as expected because creating custom commands dynamically with names as variables is not supported.

**Comment by NotTheDr01ds** [comment]
Agreed - From `help def`:

> This command is a parser keyword. For details, check:
>    https://www.nushell.sh/book/thinking_in_nu.html

This is one of the most common misunderstandings when coming to Nushell.  And still somewhat irritating even when you do know what's going on 😉.

**Comment by ysthakur** [comment]
I agree with NotTheDr01ds about the error message needing to be changed. @c4lliope, if you have time, perhaps you could edit this issue to ask for a more helpful message? Or create a new issue.
