### ISSUE TITLE
Command autocompletion is messed up if the command is loaded from a file with DOS newlines

### ISSUE THREAD

**Issue by weirdan** [nushell/nushell#13207]
### Describe the bug

I'm getting messed up autocompletion for `std` commands.

Edit: it's not specific to `std` and happens for any command defined in a file with DOS/Windows newlines (CR+LF), see: https://github.com/nushell/nushell/issues/13207#issuecomment-2185144461

### How to reproduce

1. `use std`
2. type `std` and press tab

### Expected behavior

You get the list of possible commands and their description, in two columns

### Screenshots

![image](https://github.com/nushell/nushell/assets/57403/8e5f3ce4-50e3-4143-9122-1e0f51b3c722)
![image](https://github.com/nushell/nushell/assets/57403/3d1bcd4b-8510-4953-9e9b-7cd914e89947)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.94.2                                          |
| major              | 0                                               |
| minor              | 94                                              |
| patch              | 2                                               |
| branch             |                                                 |
| commit_hash        | be8c1dc0066cd1034a6b110a622f47b516bfe029        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-06-03 19:27:48 +00:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                 |

**Comment by woosaaahh** [comment]
Hi !

I can't reproduce this on Linux with 0.94.2 and default/custom configuration.

![2024-06-23_10-51-nushell-completion-default_config](https://github.com/nushell/nushell/assets/111681540/61ca724e-04e9-4c79-a9ac-ddb0ff3156a8)

![2024-06-23_10-53-nushell-completion-custom_config](https://github.com/nushell/nushell/assets/111681540/cdf38552-49c4-47a5-9bf7-e0f9cd320c0e)

**Comment by Kissaki** [comment]
I can reproduce on windows

<details><summary>output</summary>

```
nu ❯ | std                                                                                                                                                                                                                                              ~  - %ANSI_STOP%: literally (ansi reset)levele
std pwd                       Return the current working directory
   > help matcor single command, alias, or moduleases and modules, in that order.ushell.
   times: list<duration>benchmark report of the following form:tiple times and measure the time of execution.
std ellie                     the cute and friendly mascot of Nushell :)
 an example can be found in [this asciinema recording](https://asciinema.org/a/566513)roject
  11 │ assert pt.nu:11:1]true, it generates an error.d
[…]
```

</details>

<details><summary>version</summary>

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.94.2                                          |
| major              | 0                                               |
| minor              | 94                                              |
| patch              | 2                                               |
| branch             |                                                 |
| commit_hash        | be8c1dc0066cd1034a6b110a622f47b516bfe029        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)             |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)             |
| build_time         | 2024-06-03 19:27:48 +00:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  | query                                           |

</details>

**Comment by fdncred** [comment]
Looks find on mac
![image](https://github.com/nushell/nushell/assets/343840/16cfb461-6525-455a-a222-82ac75a4dde4)

**Comment by weirdan** [comment]
Looks similar with wezterm on windows:
![image](https://github.com/nushell/nushell/assets/57403/42ba34a2-6442-4131-ad67-9a08a589f0a4)

**Comment by fdncred** [comment]
I wonder if line endings could be the problem.

**Comment by weirdan** [comment]
That very well could be it. On Windows, I get CR LF (`0d0a`) in the help output, and if the code generating completions extracts the first line of `usage` by looking for two adjacent LFs (`0a0a`), it won't find them.

![image](https://github.com/nushell/nushell/assets/57403/d20bdf4b-ee2a-49ed-bcc9-446867e8b1fe)

**Comment by weirdan** [comment]
I can reproduce it with a custom command as well if I save the file defining it with dos newlines (CR+LF):

With DOS newlines (CR+LF):
![image](https://github.com/nushell/nushell/assets/57403/b587d6e4-7c47-42db-a51b-755746896d41)

With Unix newlines (LF):

![image](https://github.com/nushell/nushell/assets/57403/aacbc200-adfd-443c-bdce-5b36d08d7150)

The command in question is available here: https://github.com/nushell/nu_scripts/blob/a992f5b4fa2f7d907cbe32cb8933f05546b598a4/modules/jc/mod.nu#L1-L5

**Comment by weirdan** [comment]
This must be it: https://github.com/nushell/nushell/blob/9b7f899410e0f5bbeddd75d1c431c927c3e610af/crates/nu-protocol/src/engine/usage.rs#L84-L85
