### ISSUE TITLE
Feature Request: Support for `ls -r/--recursive`

### ISSUE THREAD

**Issue by mokeyish** [nushell/nushell#13219]
### Related problem

I want to recursively traverse all files in the directory and filter out the specified type and calculate its shasum

### Describe the solution you'd like

I hope there was a command that can list all path include subdirectory.

**Comment by fdncred** [comment]
Try `ls **/*`

**Comment by mokeyish** [comment]
> Try `ls **/*` or `glob **/*`

@fdncred Thanks，it works.

It would be better if this is supported. it canbe list here

<img width="1133" alt="图片" src="https://github.com/nushell/nushell/assets/16131917/2520269e-c13f-487e-b89c-f874272726c6">

**Comment by fdncred** [comment]
We don't plan on supporting -r since recursive listing is already supported.

**Comment by mokeyish** [comment]
@fdncred Hi, the following case is not support.

```shell
let a = "foo"
ls $"($a)/**/*"
```

```log
Error:   × No matches found for DoNotExpand("foo/**/*")
   ╭─[entry #19:1:4]
 1 │ ls $"($a)/**/*"
   ·    ──────┬─────
   ·          ╰── Pattern, file or folder not found
   ╰────
  help: no matches found
```

**Comment by fdncred** [comment]
I think for variables you want to use `into glob` like `ls ($"($a)/**/*" | into glob)`

**Comment by mokeyish** [comment]
> I think for variables you want to use `into glob` like `ls ($"($a)/**/*" | into glob)`

Thanks, this is a little unintuitive. I never thought it could be written like this

**Comment by fdncred** [comment]
This is where `help ls` is your friend because you can see that it takes either a glob or a string.

```nushell
Parameters:
  ...pattern <one_of(glob, string)>: The glob pattern to use.
```
