### ISSUE TITLE
Ease-of-use: Params enabled behind a line break.

### ISSUE THREAD

**Issue by c4lliope** [nushell/nushell#13234]
In large libraries, especially using many params,
command names can be a challenging read.

Can I erase your error message here?

```nu
  × Missing required positional argument.
   ╭─[/home/calliope/.build/config/nushell/scan.nu:1:9]
 1 │ def scan
   ·         ▲
   ·         ╰── missing params
 2 │ [node: path, --dura (-d): duration = 8sec] { loop { clear
   ╰────
  help: Usage: def {flags} <def_name> <params>
```

**Comment by NotTheDr01ds** [comment]
Arguments can already be separated by line breaks.  The only requirement is that the opening bracket for the argument list has to be on the same line as the command definition. E.g.:

```nu
def scan [
    node: path
    --dura (-d): duration = 8sec
] {
  do {"something"}
}
```
