### ISSUE TITLE
Count physical disk usage in `du`

### ISSUE THREAD

**Issue by Freaky** [nushell/nushell#1323]
**Is your feature request related to a problem? Please describe.**

The builtin `du` only takes apparent file size into account, disregarding disparity from compression, sparse files, and block size rounding.  On systems with ZFS, for instance, it's basically always wrong.

**Describe the solution you'd like**

Measure actual space used on-disk, either as a separate column, or controlled through a flag, or both.

**Additional context**

I wrote the [filesize](https://crates.io/crates/filesize) crate to do this portably across Unix and Windows.

It's basically free on Unix, being part of the Metadata structure - on Windows it involves a syscall, and hence a small amount of `unsafe` code.

Issue following from my comment in #679

**Comment by andrasio** [comment]
@Amanita-muscaria Thoughts?

**Comment by Amanita-muscaria** [comment]
I was initially going to put it in but it didn't seem like the metadata on Windows had what we needed. However, if there's a crate I'm down to add it. Should I do a switch for the size/blocks or just have both by default?

Actually.... if there are specific cases where the file size would be inaccurate, f.x. on a ZFS, I could detect those times and add it by default

**Comment by Freaky** [comment]
GNU, BSD, and Solaris `du` give sizes in physical blocks by default.  GNU `du` doesn't even offer a short-form flag for it:

```
      --apparent-size   print apparent sizes, rather than disk usage; although
                          the apparent size is usually smaller, it may be
                          larger due to holes in ('sparse') files, internal
                          fragmentation, indirect blocks, and the like
```

I think my preference would be both columns.  If only one, default to physical size like every other `du` - I think that's closest to the typical use-case.

**Comment by Amanita-muscaria** [comment]
Got a PR up now. Let me know if that's what you're looking for.
