### ISSUE TITLE
mv'ing a file to a non-existing directory prints a less than ideal error message

### ISSUE THREAD

**Issue by kvrhdn** [nushell/nushell#1324]
**Describe the bug**
`mv`'ing a file to a non-existing directory prints a inaccurate error message.

**To reproduce**
The error is fairly accurate when both the file and the destination directory do not exist:

```
~/Desktop 
❯ mv doesnotexist.txt non-existing-dir/
error: Rename aborted. (Does "non-existing-dir" exist?)
- shell:1:29
1 | mv doesnotexist.txt non-existing-dir/
  |                     ^^^^^^^^^^^^^^^^^ Rename aborted. (Does "non-existing-dir" exist?)

```

Yet, if the file exists Nu gives a more generic error _"No such file or directory (os error 2)"_:

```
~/Desktop 
❯ touch test.txt

~/Desktop 
❯ mv test.txt non-existing-dir/
error: Rename "test.txt" to "non-existing-dir" aborted. No such file or directory (os error 2)
- shell:1:29
1 | mv test.txt non-existing-dir/
  | ^^ Rename "test.txt" to "non-existing-dir" aborted. No such file or directory (os error 2)


```

This is error is confusing/inaccurate because as a user I can't immediatelly determine the cause of the error. 
My first instinct would be to check if `test.txt` actually exists.

But tbh, seems like a fairly minor issue. Other shells don't perform much better...

```
$  mv test.txt non-existing-dir/
mv: rename test.txt to non-existing-dir/: No such file or directory                                                                                                                     

$ touch test.txt

$ mv test.txt non-existing-dir/
mv: rename test.txt to non-existing-dir/: No such file or directory
```

**Expected behavior**
I expect nushell to clearly indicate which file or folder does not exist.

**Screenshots**

**Configuration (please complete the following information):**
- macOS Catalina 10.15.2
- nu 0.9.0

**Comment by Sosthene-Guedon** [comment]
The `cp` command also needs similar improvements.
I'll look into it.

**Comment by thegedge** [comment]
This behaviour appears to have changed (ee778d2). If source file doesn't exist:

```
❯ mv abc def
error: Invalid file or pattern.
- shell:1:10
1 | mv abc def
  |    ^^^ invalid file or pattern
```

And if it does, but the given directory doesn't:

```
nushell/tmp on 📙 HEAD (ee778d2)
❯ mv foo doesnt_exist/
nushell/tmp on 📙 HEAD (ee778d2)
❯ ls
───┬──────────────┬──────┬──────┬────────────
 # │ name         │ type │ size │ modified
───┼──────────────┼──────┼──────┼────────────
 0 │ bar          │ Dir  │      │ 2 days ago
 1 │ doesnt_exist │ File │  5 B │ 2 days ago
 2 │ foo1         │ File │  0 B │ 2 days ago
 3 │ foo2         │ File │  0 B │ 2 days ago
 4 │ foo3         │ File │  0 B │ 2 days ago
 5 │ foo_dir      │ Dir  │      │ 2 days ago
───┴──────────────┴──────┴──────┴────────────
```

So the issue is now the fact that we're ignoring the fact that the user explicitly calls out a directory, but we ignore that trailing `/`.

**Comment by thegedge** [comment]
Maybe not the nicest error message, but I think we're almost there:

```
❯ mv foo doesnt_exist/
error: Rename "foo" to "doesnt_exist" aborted. No such file or directory (os error 2)
- shell:1:20
1 | mv foo doesnt_exist/
  | ^^ No such file or directory (os error 2)
```

Probably just want to drop all of that "os error" stuff, and have it tag the right argument.
