### ISSUE TITLE
Make power operator `**` work with durations

### ISSUE THREAD

**Issue by bew** [nushell/nushell#13248]
### Related problem

I'm trying to compute to final delay of an exponantial backoff after N retries.
Having the ability to do this using duration types would be nice ✨

### Describe the solution you'd like

```console
$ 2sec ** 10
17min 4sec
```

### Describe alternatives you've considered

`2 ** 10 | into duration -u sec`
It's much less nice `¯\_(ツ)_/¯`

**Comment by fdncred** [comment]
I'm guessing this is where this would need to be changed.

https://github.com/nushell/nushell/blob/46ed69ab126015375d5163972ae321715f34874b/crates/nu-protocol/src/value/mod.rs#L3507-L3538

**Comment by bew** [comment]
Re-thinking about this I think my suggestion is actually wrong in some way..
Because `2sec ** 3` would basically be `2sec * 2sec * 2sec` which doesn't actually make much sense (duration * duration 👀).

I think I should have used `2sec * (2 ** 10)` which also works for different initial delay like `4sec * (2 ** 10)`, and this already works.
So I'm gonna close this, sorry for the inconvenience
