### ISSUE TITLE
`itertools::unfold` has been deprecated and will need to be replaced in Nu `generate`

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#13247]
### Describe the bug

The `generate` command (originally `unfold`) is based on `itertools::unfold`, which was deprecated in the latest (May) release of `itertools` and is planned for "future removal".

### How to reproduce

See https://docs.rs/itertools/latest/itertools/fn.unfold.html and https://github.com/rust-itertools/itertools/issues/223 

### Expected behavior

The suggestion is to use `std::iter::from_fn`.  If I'm (quickly/scanning) grokking the history, `unfold` was originally in `std::iter`, was removed, moved to `itertools`, reintroduced in `std::iter`, renamed to `from_fn` (and presumably refactored), and thus deprecated from `itertools`.

### Configuration

N/A in this case

### Additional context

cc: @hudclark as the original author of `generate`

**Comment by fdncred** [comment]
uh oh, we better do this before it's gone.

**Comment by NotTheDr01ds** [comment]
Exactly, and it's not a one-for-one signature match with the suggested alternative either.

**Comment by dmatos2012** [comment]
I will give this a try @fdncred :)

**Comment by dmatos2012** [comment]
Luckily, this was quite an easy change, and didn't get around to doing, aside from updating my branch etc, and looking into the docs, but i wouldn't say is so friendly that the PR was being worked on by someone else :( at the same time. That was the whole point of announcing to "give it a try", but ok. There should be other issues to close :)

I know we do not assign PRs and stuff, but yeah.

**Comment by fdncred** [comment]
sorry @dmatos2012 - i forgot you wanted to do it. i just saw a pr and it looked good, then landed it.

**Comment by dmatos2012** [comment]
No problem @fdncred is all good, just pointed out cause wanted to get rolling with contributing to nushell again, so thought this would be easy one before going  more in depth. Thanks 

No mistake, is all good. See ya in another PR @fdncred :)
