### ISSUE TITLE
Feature Request: Open command supports opening directories

### ISSUE THREAD

**Issue by arkxfly** [nushell/nushell#13257]
### Related problem

![image](https://github.com/nushell/nushell/assets/140048181/ea9488cf-2d21-4448-8bc3-02936d5f0451)

### Describe the solution you'd like

Commands to open file browsers on different platforms

- MacOS `open ./directory`
- Linux `xdg-open ./directory`
- Windows ` explorer.exe ./directory`

I hope nushell’s open command also supports opening directories. Provide a consistent experience across platforms.

**Comment by WindSoilder** [comment]
You can use `start` command in your case.  It's cross platform too

**Comment by fdncred** [comment]
In nushell `open` is reserved for opening files.
