### ISSUE TITLE
cd path/to/file.txt/.. causes directory not found error

### ISSUE THREAD

**Issue by TCROC** [nushell/nushell#13251]
### Describe the bug

Most commands in nushell (all I've tested) except ``cd`` evaluate ``/..`` at the end of a path to a file as being a path to a directory.  This is very convienent if you want to act on the directory that a file is located in and you have the path to that file.  Examples of things that work:

```
rm -rf path/to/file.txt/.. # works
mkdir path/to/file.txt/.. # works
ls path/to/file.txt/.. # works
```

```
cd path/to/file.txt/.. # errors
```

workaround:

```
cd (path/to/file.txt/.. | path expand)
```

### How to reproduce

1. cd path/to/file.txt/..
2. see that you get: directory not found

### Expected behavior

I expected nu to change into the directory that file.txt is located in

### Configuration

| key                | value                                              |
| ------------------ | -------------------------------------------------- |
| version            | 0.92.2                                             |
| branch             |                                                    |
| commit_hash        | 2a08a18b26865a86c793d183b9b042220ecb733a           |
| build_os           | linux-x86_64                                       |
| build_target       | x86_64-unknown-linux-musl                          |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                    |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                |
| build_time         | 2024-04-10 21:20:38 +00:00                         |
| build_rust_channel | release                                            |
| allocator          | mimalloc                                           |
| features           | default, sqlite, static-link-openssl, trash, which |
| installed_plugins  |                                                    |

**Comment by ysthakur** [comment]
> This is very convienent if you want to act on the directory that a file is located in and you have the path to that file.

I'm afraid I don't understand when this would happen. Could you provide an example of this? If there's legitimate uses for it, this does seems like something that might be *possible* to support. Otherwise, I have to agree with fdncred that this is expected behavior.

**Comment by TCROC** [comment]
@fdncred @ysthakur I agree that this is expected behavior.  This is not a bug.  I just tested some things in my bash terminal and it behaves the same way as nushell.   Thanks for taking a moment to look into this!  I believe this can be closed.
