### ISSUE TITLE
Intermediary output of thefuck (potentially other commands) is lost in pipes since Nu 0.92

### ISSUE THREAD

**Issue by spthiel** [nushell/nushell#13260]
### Describe the bug

As per https://discord.com/channels/601130461678272522/1256162666498621533 the intermediary output of "thefuck" is lost when directly piping the command to save.

### How to reproduce

1. Install thefuck
2. Run `thefuck (history | last | get "command")` to verify the prompt working
3. Run `thefuck (history | last | get "command") | save test.txt`

### Expected behavior

Appending `| save test.txt` should not modify the behaviour of the previous commands

### Screenshots

![Screenshot from 2024-06-28 11-03-27](https://github.com/nushell/nushell/assets/17518682/cfb1f9fc-7176-42fc-a2ea-eb91084f202d)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.95.0                                   |
| major              | 0                                        |
| minor              | 95                                       |
| patch              | 0                                        |
| branch             |                                          |
| commit_hash        |                                          |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.79.0 (ffa9cf99a 2024-06-03)      |
| build_time         | 2024-06-28 10:02:50 +02:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  |                                          |

**Comment by WindSoilder** [comment]
Additionally, it works on 0.91, starts to break on 0.92
