### ISSUE TITLE
Add 'like' operator (clone of =~)

### ISSUE THREAD

**Issue by freijon** [nushell/nushell#13261]
### Related problem

The `~` character is awkward to write on certain keyboards (I need to hit three keys to insert it). Also, I often confuse the order and write `~=` instead of `=~`, but maybe that's just my brain that's wired wrong.

### Describe the solution you'd like

In SQL languages the `like` operator is used. I propose that `like` could be used on top of `=~`. The operators should work exactly the same, it's just another way to write it. An operator-alias if you like. The syntax would be very SQL-like.

Example: `ls | where name like .bash` could be used instead of `ls | where name =~ .bash`

**Comment by fdncred** [comment]
If we added `like` for a synonym to `=~` we'd probably need to add `not-like` for a synonym to `!~` too. I wouldn't be against these changes.

**Comment by hustcer** [comment]
I don't think it's good idea to add `like`:
We can say `'m1cNnTsf2blMGiThe2beJnerh4xiA6mRy1NVjAY0VtULuOEX5BJWBiY6v0wi' =~ '2'`, but can we say `m1cNnTsf2blMGiThe2beJnerh4xiA6mRy1NVjAY0VtULuOEX5BJWBiY6v0wi`  and `2` **like** each other?

BTW: 
We already have `str contains` command, you can also write `ls | where name =~ .bash` as `ls | where ($it.name | str contains '.bash')`

**Comment by freijon** [comment]
My example was probably not the best, I use =~ with regex, which is not possible with `str contains`. The operator `like` would just say "use regex", like on SQL. It would be logical because `nushell` uses several commands borrowed from SQL, like `where`, `select`.

**Comment by hustcer** [comment]
`find` works with regex:
```nu
ls | find -r .bash -c [name]
```

**Comment by Or1g3n** [comment]
I agree it would be very nice to have a 'like' operator. Especially since nushell's ethos is about structured data. Leveraging existing syntax from tools like SQL/Pandas etc. when working with similar structures only makes it much easier for developers to pick up and go with minimal learning curve.

=~ or like
!= or not like
