### ISSUE TITLE
flag missing completable<string> 

### ISSUE THREAD

**Issue by FrancescElies** [nushell/nushell#13279]
### Describe the bug

If you combine [git-completions](https://github.com/nushell/nu_scripts/blob/main/custom-completions/git/git-completions.nu) and [gitv2](https://github.com/nushell/nu_scripts/blob/main/modules/gitv2/mod.nu) from https://github.com/nushell/nu_scripts

```nu
  × Missing flag argument.
     ╭─[/home/cesc/src/nushell-config/src/gitv2.nu:207:18]
 206 │     } else if $override {
 207 │         git pull --rebase
     ·                  ────┬───
     ·                      ╰── flag missing completable<string> argument
 208 │         git add --all
     ╰────
```

One workaround is to use `^git pull --rebase`.

Is this a bug or am I missing something?

### How to reproduce

1. Import both files in your config.nu

### Expected behavior

I expect to be able to git pull --rebase in imported files

### Screenshots

see line 207
![image](https://github.com/nushell/nushell/assets/6558089/352598f8-4e41-4923-840e-3c008ccb8479)
here the pull rebase definition
![image](https://github.com/nushell/nushell/assets/6558089/1bbb12a2-cf54-42de-9712-aeb37042e198)

### Configuration

| key                | value                                                         |
| ------------------ | ------------------------------------------------------------- |
| version            | 0.95.0                                                        |
| major              | 0                                                             |
| minor              | 95                                                            |
| patch              | 0                                                             |
| branch             |                                                               |
| commit_hash        | f93c6680bd5ae158190556eb1afc924b0290b52f                      |
| build_os           | linux-x86_64                                                  |
| build_target       | x86_64-unknown-linux-gnu                                      |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                           |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                               |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                           |
| build_time         | 2024-06-25 18:38:46 +00:00                                    |
| build_rust_channel | release                                                       |
| allocator          | mimalloc                                                      |
| features           | default, sqlite, static-link-openssl, system-clipboard, trash |
| installed_plugins  |                                                               |

### Additional context

**NOTE:** Calling `git pull --rebase` from the shell works with the extern command as defined in git-completions but fails when imported

The problem seems to be related to ...refs

**Comment by fdncred** [comment]
I'm not sure because I haven't landed any gitv2 changes in a long time because the author changes them too often. I'm considering removing it altogether from nu_scripts.

I use this but it has to be used in this order or there are similar errors. I'm not sure if it's a bug when sourcing completions before aliases or not. I haven't looked into it very deeply.
```nushell
use aliases/git/git-aliases.nu *
use custom-completions/git/git-completions.nu *
use custom-completions/gh/gh-completions.nu *
```

**Comment by fdncred** [comment]
I once thought gitv2 might grow to be better, but I don't think that's the case any longer. it's really someone's personal changes.
