### ISSUE TITLE
Weird error when using `into datetime`

### ISSUE THREAD

**Issue by freijon** [nushell/nushell#13280]
### Describe the bug

I get a weird error when I try to convert into a specific date:

```nushell
"09.02.2024 11:06:11" | into datetime --format '%d.%m.%Y %T'
```
```
Error: nu::shell::cant_convert

  × Can't convert to could not parse as datetime using format '%d.%m.%Y %T'.
   ╭─[entry #14:1:25]
 1 │ "09.02.2024 11:06:11" | into datetime --format '%d.%m.%Y %T'
   ·                         ──────┬──────
   ·                               ╰── can't convert input is not enough for unique date and time to could not parse as datetime using format '%d.%m.%Y %T'
   ╰────
  help: you can use `into datetime` without a format string to enable flexible parsing
```

### How to reproduce

run:
```nushell
"09.02.2024 11:06:11" | into datetime --format '%d.%m.%Y %T'
```

### Expected behavior

1. convert to datetime (this should work?)
2. if there is really a problem, show an error message that is understandable

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.94.2                                          |
| major              | 0                                               |
| minor              | 94                                              |
| patch              | 2                                               |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29) (gentoo)    |
| cargo_version      | cargo 1.78.0                                    |
| build_time         | 2024-06-05 16:16:58 +02:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  | bin_reader                                      |

**Comment by KAAtheWiseGit** [comment]
Was about to post this.  The [`parse_from_str`](https://docs.rs/chrono/latest/chrono/struct.DateTime.html#method.parse_from_str) method fails without a timezone.  What's weird is that `into datetime` uses `CantConvert` error for some reason.

Also, in theory, `into datetime` can use `NaiveDateTime` for this.  After all, it's already defaulting to the current timezone when inferring the format:

```Nushell
~> "09.02.2024 11:06:11" | into datetime
Mon, 2 Sep 2024 11:06:11 +0300 (in 2 months)
```

**Comment by hqsz** [comment]
I agree with upper opinions! i make simple [PR](https://github.com/nushell/nushell/pull/13289) to resolve this issue. I will receive a review on the direction of this patch.
