### ISSUE TITLE
Fetch should have a progress indicator

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1328]
**Is your feature request related to a problem? Please describe.**
Fetch is a great feature to have, but if you download large files it'd be good to know how the download is coming. 

**Describe the solution you'd like**
I'd like to see a progress indicator available, if possible. 

**Describe alternatives you've considered**
You could log the progress or put it into a status monitor for Nu.

**Comment by thegedge** [comment]
We've talked about terminal UI elements in Discord. Perhaps we should start thinking about a library of these things? 🙂

**Comment by coolshaurya** [comment]
[indicatif](https://github.com/mitsuhiko/indicatif) is a crate that can do this, although it may be overkill. 

Other options are [logbar](https://github.com/a-maier/logbar) and [progressing](https://github.com/dominicparga/progressing)
