### ISSUE TITLE
Auto-Discovery and auto-loading of completion files in standard directory

### ISSUE THREAD

**Issue by freijon** [nushell/nushell#13294]
### Related problem

A lot of packages nowadays provide nushell completions out of the box, which is great. Today it's up to the user to use these. Other shells like `bash`, `zsh` or `fish` have a standardized location where package maintainers can install the completion files of their package and the shell will pick them up automatically. I'd like for `nushell` to behave the same way.

### Describe the solution you'd like

We would have to find a standardized location where `nushell` would have to look for completion files. Package maintainers can install the completions of their packages into this folder.

- `nushell` would automatically load all completions in these folders.
- There could be a config to disable this behavior.
- User completions (sourced with the config) should be loaded with higher priority than "system completions".
- `nushell` should fail graciously when it can't load a system-completion automatically, maybe a small warning message but it shouldn't fall back to the default config like with usual config errors. The user may not have the permission to modify these completions and will have to file a bug for the corresponding package.

### Describe alternatives you've considered

I propose the location `/usr/share/nushell/completions` on Linux as a straight-forward location to put completions for various packages. Not sure what the best location would be for other platforms.

### Additional context and details

Install locations (on Linux) for various shells:

- Fish: `/usr/share/fish/vendor_completions.d/<package>.fish`
- Zsh: `/usr/share/zsh/site-functions/_<package>`
- Bash: `/usr/share/bash-completion/completions/<package>`

**Comment by devyn** [comment]
Hi,

#13217 implemented this I think, by providing a vendor autoload dir that can be configured at compile time.

I think we also have several other issues requesting something similar, so I'm closing it as a duplicate. But we should have it already implemented and ready for the next release anyway.
