### ISSUE TITLE
`<duration> mod <duration>`  gives `duration`, but said to be `float`

### ISSUE THREAD

**Issue by YDX-2147483647** [nushell/nushell#13298]
### Describe the bug

`<duration> mod <duration>`  gives another `duration`, but the type checker thinks it's a `float`.

### How to reproduce

```nu
> 92sec mod 1min
32sec
> 92sec mod 1min | describe
duration
> 32sec / 1sec 
32
```

But…

```nu
> (92sec mod 1min) / 1sec
Error: nu::parser::unsupported_operation

  × division is not supported between float and duration.
   ╭─[entry #6:1:1]
 1 │ (92sec mod 1min) / 1sec
   · ────────┬─────── ┬ ──┬─
   ·         │        │   ╰── duration
   ·         │        ╰── doesn't support these values
   ·         ╰── float
   ╰────
```

### Expected behavior

```nu
> (92sec mod 1min) / 1sec
32
```

### Screenshots

![](https://github.com/nushell/nushell/assets/73375426/a4859d76-df5c-4dd8-935d-6d7f5eb37fad)

### Configuration

| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.93.0                                                     |
| major              | 0                                                          |
| minor              | 93                                                         |
| patch              | 0                                                          |
| branch             |                                                            |
| commit_hash        | ca5ee3dba328468b10989f0c85d94a6c0284b767                   |
| build_os           | windows-x86_64                                             |
| build_target       | x86_64-pc-windows-msvc                                     |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                        |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc                              |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                        |
| build_time         | 2024-05-01 12:53:36 -07:00                                 |
| build_rust_channel | release                                                    |
| allocator          | mimalloc                                                   |
| features           | dataframe, default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                            |

**Comment by lavafroth** [comment]
Looks like the output type for both the division and modulo operators are assumed to be the same

https://github.com/nushell/nushell/blob/d5e00c0d5d30516d4f43989ceda6325512892b9c/crates/nu-parser/src/type_check.rs#L281

which is probably why the type checker expects a float value

https://github.com/nushell/nushell/blob/d5e00c0d5d30516d4f43989ceda6325512892b9c/crates/nu-parser/src/type_check.rs#L295

whereas the mod operation itself output a `Duration` type.

https://github.com/nushell/nushell/blob/d5e00c0d5d30516d4f43989ceda6325512892b9c/crates/nu-protocol/src/value/mod.rs#L3432-L3438
