### ISSUE TITLE
Tests that use `cococo` or `chop` commands fail

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#1330]
**Describe the bug**
Running `cargo test`, I'm presented with some errors of missing commands: `cococo` and `chop`.  Because of this, some tests fail:

```
shell::pipeline::commands::external::external_words::relaxed_external_words
shell::pipeline::commands::external::it_evaluation::takes_rows_of_nu_value_lines
shell::pipeline::commands::external::it_evaluation::takes_rows_of_nu_value_strings
shell::pipeline::commands::external::tilde_expansion::does_not_expand_when_passed_as_argument_and_does_not_start_with_tilde
shell::pipeline::commands::internal::can_process_one_row_from_internal_and_pipes_it_to_stdin_of_external
shell::pipeline::commands::internal::takes_rows_of_nu_value_strings_and_pipes_it_to_stdin_of_external
```

**To Reproduce**
1. run `cargo test`

**Expected behavior**
I suppose I expect the commands to exist or if they have been removed, then for the tests to be removed or to use some alternative command in their place so the tests pass

**Configuration (please complete the following information):**
 - macOS 10.15.2
 - nushell v0.9.0

I would've tried to fix the issue, but I'm not sure which direction the maintainers want to go with these or if maybe the failed tests are just an isolated incident that only I'm experiencing.

**Comment by jonathandturner** [comment]
We should write this somewhere a little easier to find.  Because of the additional apps you need to run the tests, you need a slightly different test command:

```
cargo test --all --features stable,test-bins
```

**Comment by JosephTLyons** [comment]
Awesome!  All tests passed!
