### ISSUE TITLE
Tilde expansion not working for external/aliased commands

### ISSUE THREAD

**Issue by OJarrisonn** [nushell/nushell#13316]
### Describe the bug

Tilde expansion simply not happens when calling an external command. This is a change from nushell 0.95.

I have the alias `export alias ez = eza -halF --color=auto --icons=always --group-directories-first --binary`. When calling `ez ~` i get `"~": No such file or directory (os error 2)`

### How to reproduce

1. Create an alias for a command which uses a file path as an argument
2. Call the alias with a path containing `~`
3. See the error message

### Expected behavior

I expected the ~ to be expanded just like it was before

### Configuration

| key                | value                                                         |
| ------------------ | ------------------------------------------------------------- |
| version            | 0.95.0                                                        |
| major              | 0                                                             |
| minor              | 95                                                            |
| patch              | 0                                                             |
| branch             |                                                               |
| commit_hash        | f93c6680bd5ae158190556eb1afc924b0290b52f                      |
| build_os           | linux-x86_64                                                  |
| build_target       | x86_64-unknown-linux-gnu                                      |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                           |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                               |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                           |
| build_time         | 2024-06-25 18:38:46 +00:00                                    |
| build_rust_channel | release                                                       |
| allocator          | mimalloc                                                      |
| features           | default, sqlite, static-link-openssl, system-clipboard, trash |
| installed_plugins  |                                                               |

### Additional context

Also the parsing of paths starting with a variable isn't working anymore and require it to be wrapped inside a `$""` which is the worse experience possible.

A shell syntax should be as straight forward as possible requiring any kind of overhead to use `~` or variables brings a bad user experience

**Comment by fdncred** [comment]
Can you try the latest main branch. I have no issues with it.

**Comment by OJarrisonn** [comment]
I'm using the 0.95.0 version from cargo and often the `~` expansion fails with both `eza` or the `ez` alias

**Comment by fdncred** [comment]
I don't have any issues with your alias `ez ~` or just typing `eza ~` in the latest main. I'm on Windows but I tested on WSL Ubuntu as well without issue.

**Comment by OJarrisonn** [comment]
Just disabled the completions for `eza` and now it works fine. Don't know exactly how to fix the completion, but i'll open a issue in the proper repo

**Comment by sholderbach** [comment]
> Just disabled the completions for `eza` and now it works fine. Don't know exactly how to fix the completion, but i'll open a issue in the proper repo

What do you mean by disabling completions? Something on `eza`'s side or some external completion provider or by removing an `extern` block (like those in https://github.com/nushell/nu_scripts/blob/main/custom-completions/eza/eza-completions.nu)

**Comment by OJarrisonn** [comment]
By disabled completions i mean i've removed the `source eza-completions.nu` file from my `config.nu`

Sourcing the file the completions do work, but the command doesn't. `eza <tab>` shows the completions as expected. But running `eza ~` doesn't list the files in the home directory, instead, `eza` just tries to list the files in a directory called `~` which doesn't exists, it means tilde expansion isn't working as expected.

Probably when passing strings to the external command the glob expansion ins't being applied

This issue isn't particular to `eza`. Every command that uses a custom completion with a `export extern` is being affected

**Comment by sholderbach** [comment]
Yeah it seems like we treat the positional arguments differently with respect to glob expansion depending on whether they are "just" arguments to an unknown external or fall-through arguments to a known external.

**Comment by fdncred** [comment]
Looks like https://github.com/nushell/nushell/pull/13414 fixes this issue. I've tested with the eza completions and a few other ways and it looks good to me.

**Comment by OJarrisonn** [comment]
So i just downloaded nu 0.96.0 with `cargo install` and the problem still happens

[example](https://asciinema.org/a/5whfcU0kKDOa7zWTFdDy1VWPc)

Using nushell and the custom completions scripts provided in the `nushell/nu_scripts` repo

**Comment by fdncred** [comment]
I'm wondering if something changed in the custom completion script because i just did a git pull and did `use custom-completions/eza/eza-completions.nu *` and am not having the issue on Windows.

**Comment by OJarrisonn** [comment]
Oh i'm using `source`, using `use` and modifying the eza-completions to use `export extern "main"` resolved the issue

So it means that now completions should use `use` instead of `source`?

**Comment by devyn** [comment]
Hmm, I'll see if I can reproduce your exact steps here. You're loading the completion with `source` and then tilde expansion is only working partially?

**Comment by fdncred** [comment]
No issued with ~\.config on windows. Is this different than what you're doing? I haven't tried source yet.
![eza](https://github.com/user-attachments/assets/59620da0-f231-4585-8abd-178493ffdd7d)

**Comment by OJarrisonn** [comment]
Might found something interesting. Downloaded custom completions again and some of them work but some don't

When capturing paths with `string` args in `export extern`, the ~ expansion won't happen. 
Sometimes the order that i use `use` matters (need to confirm if this is true)

It might be a nice idea to add a `path` type to nushell to force tilde expansion and that kind of stuff

**Comment by OJarrisonn** [comment]
This won't trigger ~ expansion

```
export extern "bat" [
    ...files
   --help
]
```

This will

export extern "bat" [
   --help
]

**Comment by fdncred** [comment]
There is a path type like below but I'm not sure it'll work like you're saying.

```nushell
def fifi [x: path] {
  print $x
}
```

**Comment by OJarrisonn** [comment]
Using `path` seems to fixes

Ofc needs more testing, but if this is the case must create some sort of warning for nu_scripts guys

**Comment by WindSoilder** [comment]
I think the issue can be closed :)
Feel free to reopen it if you still get the issue
