### ISSUE TITLE
JSON formatting output by to json is unusual

### ISSUE THREAD

**Issue by drmason13** [nushell/nushell#13326]
### Describe the bug

Is this JSON formatting performed by `to json` intentional?
```
{
  "version": "v0.4.4",
  "notes": "blablabla",
  "pub_date": "2024-05-04T16:05:00Z",
  "platforms":
  {
    "windows-x86_64":
    {
      "signature": "blablabla",
      "url": "https://blablabla"
    }
  }
}
```

### How to reproduce

```
echo '{"version": "v0.4.4","notes": "blablabla","pub_date": "2024-05-04T16:05:00Z","platforms":{"windows-x86_64":{"signature": "blablabla","url": "https://blablabla"}}}' | from json | to json
```

### Expected behavior

```
{
  "version": "v0.4.4",
  "notes": "blablabla",
  "pub_date": "2024-05-04T16:05:00Z",
  "platforms": {
    "windows-x86_64": {
      "signature": "blablabla",
      "url": "https://blablabla"
    }
  }
}
```
Noting the leading `{` of nested objects is on the same line as the `"key":`

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.95.0                                   |
| major              | 0                                        |
| minor              | 95                                       |
| patch              | 0                                        |
| branch             |                                          |
| commit_hash        |                                          |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.78.0 (54d8815d0 2024-03-26)      |
| build_time         | 2024-07-09 21:50:28 +01:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  |                                          |

**Comment by drmason13** [comment]
I'm sorry if this has been raised before, but I couldn't find the issue by searching. A **ton** of issues show up when searching for anything to do with JSON. I think it annoyingly finds every bug report with a something-json plugin installed and that seems to be quite popular 😃

**Comment by drmason13** [comment]
Ha, wow posting this issue has made me realise I've been running an old version of nu for a while now!
I was updating using `cargo install` but my terminal profile was loading a completely different version of nu - whoops! 😆 

Anyhoo, the issue persists with a *much* newer version of nu:

```
~> version | transpose key value | to md --pretty                                                                                                                                             2024-07-09 22:20:01
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.95.0                                   |
| major              | 0                                        |
| minor              | 95                                       |
| patch              | 0                                        |
| branch             |                                          |
| commit_hash        |                                          |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.78.0 (54d8815d0 2024-03-26)      |
| build_time         | 2024-07-09 21:50:28 +01:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  |                                          |
~> echo '{"version": "v0.4.4","notes": "blablabla","pub_date": "2024-05-04T16:05:00Z","platforms":{"windows-x86_64":{"signature": "blablabla","url": "https://blablabla"}}}' | from json | to json
{
  "version": "v0.4.4",
  "notes": "blablabla",
  "pub_date": "2024-05-04T16:05:00Z",
  "platforms":
  {
    "windows-x86_64":
    {
      "signature": "blablabla",
      "url": "https://blablabla"
    }
  }
}
```
I'll update the details in this issue now

**Comment by drmason13** [comment]
I had a poke about and found that the underlying hjson implementation [has a toggle](https://github.com/nushell/nushell/blob/main/crates%2Fnu-json%2Fsrc%2Fser.rs#L688-L695) "braces same line" which sounds like exactly what I expect.

It defaults to false, very easy to change. I'll try to whip up a quick pull request soon.

**Comment by drmason13** [comment]
I've checked and there doesn't seem to be any formal standard for the style of JSON output, only that the output conforms to the grammar, and insignificant whitespace is allowed by the grammar.
However, the example JSON objects in [RFC-8259](https://datatracker.ietf.org/doc/html/rfc8259#section-13) use the braces on same line style, which is probably why it is so ubiquitous.
Anecdotally, it's the only style I've ever seen used before encountering nushell, but I'm sure [someone will prefer the braces on new lines style](https://xkcd.com/1172/).

I was thinking about this and considering adding a config option to control the json syntax style, but I am concerned that it bloats the nu config without _good enough_ reason. Without actually asking people "do you depend on or prefer the current json syntax output?" it's hard to know. This kind of breaking change - without requiring a config option to opt in - is best made before 1.0 stability guarantees.

I'm currently working around it - purely for personal aesthetic reasons - by piping into [`jq`](https://jqlang.github.io/jq/), which does use the braces same line style. So I guess that's another source for it being the "standard style".

**Comment by sholderbach** [comment]
Thanks for researching this, I am fine with that, also sounds like that most JS style guides use brace on the same line/K&R style consistently.
