### ISSUE TITLE
table not filling the screen width sometimes

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#13336]
### Describe the bug

As described [here](https://github.com/nushell/nushell/pull/13325#issuecomment-2221517786), sometimes the table is not filling the width of the screen.

### How to reproduce

I don't have a good repro but I know it happens with a script where I'm `get`ting the `data` column out of a table. I'm hoping this is enough information for @zhiburt to understand what is going on.
![image](https://github.com/nushell/nushell/assets/343840/e0431b0d-6d1e-4210-8bf0-ca99ec8e69a0)

### Expected behavior

Fill the width of the terminal

### Configuration

|key|value|
|-|-|
|version|0.95.1|
|major|0|
|minor|95|
|patch|1|
|branch|main|
|commit_hash|0178295363fb00a455a9ad403c2aca20093e4ee5|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.77.2 (25ef9e3d8 2024-04-09)|
|rust_channel|1.77.2-aarch64-apple-darwin|
|cargo_version|cargo 1.77.2 (e52e36006 2024-03-26)|
|build_time|2024-07-10 16:26:14 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|default, sqlite, system-clipboard, trash|
|installed_plugins|bexpand 1.3.5, bg 0.5.0, emoji 0.5.0, file 0.5.0, formats 0.95.1, from_parquet 0.5.0, gstat 0.95.1, highlight 1.1.4+0.94.0, image 0.4.2, inc 0.95.1, json_path 0.5.0, jwalk 0.5.0, md 0.5.0, mime 0.94.2, plist 0.94.0, pnet 1.7.0, polars 0.95.1, port_list 1.4.0, port_scan 1.2.0, qr_maker 1.1.0, query 0.95.1, query_git 0.5.0, regex 0.5.0, str_similarity 0.5.0, stress_internals 0.95.1|

### Additional context

/cc @zhiburt

**Comment by fdncred** [comment]
I was also able to easily reproduce this with `help -f term`.
![image](https://github.com/nushell/nushell/assets/343840/75fb3e86-8aab-40bb-af13-75b9be0f1c1d)

**Comment by sholderbach** [comment]
Does the presence of specific ANSI coloring play a role?

**Comment by fdncred** [comment]
I looks like with or without ansi coloring it still doesn't fill the width of the screen.
![image](https://github.com/nushell/nushell/assets/343840/2310221c-2719-449b-973c-5fa7f6dbed5d)

**Comment by sholderbach** [comment]
I didn't mean the effect of the global ANSI setting but that some `Value::String` have ANSI codes in them (I don't forget what I have to finish on `find`). If that's throwing of the width calculations. Surprising that the column name seem to dictate the width here but still have slightly different padding.

**Comment by fdncred** [comment]
> Surprising that the column name seem to dictate the width here but still have slightly different padding.

This is a recent change. The [old way](https://github.com/nushell/nushell/pull/13291) was to truncate headers and that was a problem because you couldn't really see what the name of the column was without calling `columns`.

> If that's throwing of the width calculations.

I figure it's related to the most recent changes since this used to work, but just work differently.

**Comment by fdncred** [comment]
Here's another way to reproduce the problem.

![image](https://github.com/nushell/nushell/assets/343840/f9e9076a-f995-4180-83f4-e759f9de68e5)
