### ISSUE TITLE
Nushell does not recognize files with `~` after their extension

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#1333]
**Describe the bug**
If you try to run a command such as `rm` or `open` on a file with a `~` after its extension, Nushell highlights the extension in red and the command breaks.  An example is `.foo.bar~`.  The strange thing is it only breaks when you are in the directory of that file.  If you navigate to a parent directory and launch the same command, the path is accepted: `rm parent/.foo.bar~`

**To Reproduce**
1. Try `rm` or `open` on a backup file with a name of `x.y~`, where x is the filename and y is the extension.  Make sure to use the command directly inside of the folder the file resides in.

**Expected behavior**
I expect to be able to use path-related commands on files that have `~` after their extension (backup files)

**Configuration (please complete the following information):**
- macOS 10.15.2
- nushell v0.9.0

**Comment by JosephTLyons** [comment]
I don't think I'll be able to fix this one.  The logic of the parser is way beyond me.  I've spent the last 3-4 days trying to understand it and I just can't get a grasp of it.

**Comment by jonathandturner** [comment]
@JosephTLyons - this should now be fixed in the latest master. Closing, but if you still see it happening, please re-open.

**Comment by JosephTLyons** [comment]
Yep, seems to be fixed over here.  Nice work!
