### ISSUE TITLE
The operator ; does not behave as documented

### ISSUE THREAD

**Issue by yashamon** [nushell/nushell#13354]
### Describe the bug

git add .; git commit -m "test"; git commit -m "test"; echo "blah"
will not print blah, in any other shell it does.

Apparently the "error or warning that there are no commits to be done terminates the thread"

### How to reproduce

In the description.

### Expected behavior

I expected nu complete all commands.

### Configuration

| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.93.0                                                     |
| major              | 0                                                          |
| minor              | 93                                                         |
| patch              | 0                                                          |
| branch             |                                                            |
| commit_hash        | ca5ee3dba328468b10989f0c85d94a6c0284b767                   |
| build_os           | windows-x86_64                                             |
| build_target       | aarch64-pc-windows-msvc                                    |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                        |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc                              |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                        |
| build_time         | 2024-05-01 12:24:39 -07:00                                 |
| build_rust_channel | release                                                    |
| allocator          | mimalloc                                                   |
| features           | dataframe, default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                            |

**Comment by fdncred** [comment]
I thought `;` would stop executing the next command if the previous one failed. Also, it's always good to report errors in the current version because we won't be fixing old versions.

**Comment by ysthakur** [comment]
Yeah, as fdncred said, this is how semicolon is supposed to work in Nushell. It's not what other shells do, but it's not a goal for Nushell to be POSIX-compliant. I think we'll have to close this issue as not planned, sorry. Changing the behavior of ; would break a great many people's scripts.

I don't know what the equivalent of Bash's semicolon is in Nushell, though. If it doesn't already exist and there's no issue for it already open, feel free to open another issue. In the meantime, I think wrapping your git commands with `do` should eat the errors and allow execution to continue.

**Comment by yashamon** [comment]
I don't know what is POSIX but it's not even compatible with powershell and cmd.
Which operator should I use then?


I tried wrapping with do in various ways and couldn't get it to work.
Could you please give a working example?

**Comment by ysthakur** [comment]
> Which operator should I use then?
I don't know, let me ask around.

> Could you please give a working example?
Sorry, I should've given more info. The `--ignore-errors` (`-i`) flag will let you ignore all errors, both (Nu)shell errors and external program errors. So this should execute the last line:
```sh
git commit -m "test"
do -i { git commit -m "test" }
echo "blah"
```

**Comment by ysthakur** [comment]
I don't think there's currently any way to do this without using `do` or `try`. Feel free to make a feature request if you need this behavior.
