### ISSUE TITLE
Meh? What's wrong with column selection?

### ISSUE THREAD

**Issue by zhexyez** [nushell/nushell#13350]
### Question

![Screenshot_20240711_195754_Termux](https://github.com/nushell/nushell/assets/35332515/e0b512db-94de-416a-b9e4-d66ab94acf0c)
![Screenshot_20240711_195815_Termux](https://github.com/nushell/nushell/assets/35332515/5cb4f624-6c64-4502-9770-cb18338a3a3f)
![Screenshot_20240711_195834_Termux](https://github.com/nushell/nushell/assets/35332515/57946cc8-d823-49db-92b9-8ad84d348f75)

What is wrong with selecting column2? Selecting column1 works perfectly well. Either I am stupid or this thing is inconsistent.

Command I want to execute:
```shell
hexdump <filename> | lines | split column " " | select <column name>
```

**Comment by fdncred** [comment]
it's because you have "holes" in your data. You should use `... | select column2?` the `?` here means it's optional. Or you could use `... | select -i column2`. Same for `get`.

**Comment by zhexyez** [comment]
> it's because you have "holes" in your data. You should use `... | select column2?` the `?` here means it's optional. Or you could use `... | select -i column2`. Same for `get`.

Thanks, that works. Could you elaborate on what these "gaps" are? For now I suppose they are "null-values" or missing values. Then why `select column<x>` doesn't show them again when selecting, but require to specify ignoring?

**Comment by fdncred** [comment]
The "holes" I mention are cells without any value as indicated by green x in your original screenshot. Not `null` and not empty strings but entirely missing.
