### ISSUE TITLE
`select` renames my columns

### ISSUE THREAD

**Issue by freijon** [nushell/nushell#13359]
### Describe the bug

Not sure if it's a bug or a deliberate behavior... Anyhow: When a column has a period in its name and I `select` said column, the period will be replaced with an underscore

### How to reproduce

```nushell
[[foo.bar test yadda]; [1 2 3]] | select "foo.bar" test
```
will result in a table:
```
╭───┬─────────┬──────╮
│ # │ foo_bar │ test │
├───┼─────────┼──────┤
│ 0 │       1 │    2 │
╰───┴─────────┴──────╯
```
please notice the "foo_bar" column (instead of "foo.bar")

### Expected behavior

The output I expected would have looked like this:
```
╭───┬─────────┬──────╮
│ # │ foo.bar │ test │
├───┼─────────┼──────┤
│ 0 │       1 │    2 │
╰───┴─────────┴──────╯
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.94.2                                          |
| major              | 0                                               |
| minor              | 94                                              |
| patch              | 2                                               |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29) (gentoo)    |
| cargo_version      | cargo 1.78.0                                    |
| build_time         | 2024-06-05 16:16:58 +02:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  | bin_reader                                      |

**Comment by sholderbach** [comment]
I can't really gather the history why @WindSoilder introduced it in https://github.com/nushell/nushell/pull/5577 for `select` if we had other commands also trying to separate column names from cell paths.

I think we should be faithful to the original column names as you can safely quote those in a cell path.
