### ISSUE TITLE
Cell path display output doesn't escape/quote properly

### ISSUE THREAD

**Issue by sholderbach** [nushell/nushell#13362]
### Describe the bug

The current `Display` implementation for `CellPath` directly outputs both the string key/column members and int row. This makes it impossible to distinguish columns from rows should they contain only numbers or contain a dot.

### How to reproduce

```sh
> $.0."0"
0.0
> $."foo.bar".baz
foo.bar.baz
```

#### Either...

```sh
> $.0."0"
0."0"
> $."foo.bar".baz
"foo.bar".baz
```

#### ... or

```sh
> $.0."0"
$.0."0"
> $."foo.bar".baz
$."foo.bar".baz
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.95.1                                   |
| major              | 0                                        |
| minor              | 95                                       |
| patch              | 1                                        |
| branch             | main                                     |
| commit_hash        | f65bc97a545264e0fc0ca4ccb953a73a1cc1b07a |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)      |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)      |
| build_time         | 2024-07-12 10:59:10 +02:00               |
| build_rust_channel | debug                                    |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  |                                          |

**Comment by sholderbach** [comment]
Additional challenges:
- should this include a unique prefix as in `$.` to be equivalent to its literal?
- Which quoting/escaping routine to use, on top of detection of `.` or all digits, this also has to take into account the used quotes or what escape sequences are active in those.
- Funky interaction with `select` currently flattening deep nested acesses using `Display` (see #13361)

**Comment by fdncred** [comment]
Seems like the original intent of the cell-path literal was to be able to construct cell-paths and then use them for `select` and maybe `get`. So, however we change it, we need to ensure that still works.
```nushell
let cp = $."foo.bar".baz
$table | select $cp
```
We also need to keep in mind that we have `into cell-path` as well so theoretically there may need to be changes there too.

**Comment by sholderbach** [comment]
Currently `into cell-path` only accepts either an index or a structured form as a list or table so it doesn't have the full parsing logic to deal with (so unquoting/unescaping) and can immediately generate unique/correct cell paths.

I think when showing such a cell path it should be pretty much equivalent to the corresponding literal.

**Comment by IanManske** [comment]
Another thing to note is that the `Display` implementation for `CellPath` is used when serializing cell paths to nuon. Because of this escaping issue, `$value | to nuon | from nuon` may not return the same value.

> should this include a unique prefix as in `$.` to be equivalent to its literal?

I'm leaning towards yes, but I thinking leaving the prefix out is also fine.
