### ISSUE TITLE
Missing characters in prompt when in git branch?

### ISSUE THREAD

**Issue by petertirrell** [nushell/nushell#1336]
**Describe the bug**
When in a git folder, the prompt shows empty boxes and miscoloring of the branch name:

**To Reproduce**
1. Downloaded release version 0.9.0, running on Windows 10
2. Added the path of the extracted files to my PATH variable
3. I've tried different fonts - Consolas, DejaVu Sans Mono, with and without PowerLine, CascadiaCode, with and without PowerLine

**Expected behavior**
Something else?  I'm not sure what it's supposed to look like...some sort of UTF characters?

**Screenshots**
![image](https://user-images.githubusercontent.com/4230164/73758864-294f6b00-4739-11ea-8338-88392e72e638.png)

**Configuration (please complete the following information):**
 - OS: Windows 10
 - Version 0.9.0

**Comment by jonathandturner** [comment]
@petertirrell - Sorry for the slow reply.  If you're running on Windows with starship, you'll get the best support using the new Windows Terminal, which can support the utf-8 characters that starship prints out.

**Comment by thegedge** [comment]
@petertirrell is this still an issue in the latest terminal?

If not, I'd rather close this issue and open a new one so that we could support an alternative starship config for terminals that don't have UTF-8 support.

**Comment by petertirrell** [comment]
@thegedge go ahead and close it.  My work laptop where I experienced this doesn't have the latest Windows Terminal version so I haven't been able to confirm that was the issue, but I'm assuming it was.  Thanks for following up and I'll keep playing with this project, it looks nice!
