### ISSUE TITLE
vendor/autoload should respect `XDG_DATA_DIRS`

### ISSUE THREAD

**Issue by LordMZTE** [nushell/nushell#13378]
Nushell will currently only look for files to autoload in `/usr/local/share/nushell/vendor/autoload` (which is configurable only at compile-time). This is problematic for a variety of reasons:
1. `/usr/local` is reserved through software installed manually, historically through `make install`. Any modern package manager will strongly discourage the use of this directory, instead opting for using `/usr` as a prefix directly. On traditional Linux systems. Vendored files will thus end up in `/usr/share`.
2. Per-user installations will typically go into `~/.local`. Software with nushell externs installed per-user will not work with the current approach.
3. Distributions such as NixOS choose to structure this completely differently. NixOS only ever places anything in `/usr` for workarounds or compatibility reasons. A typical NixOS installation will only contain `/usr/bin/env` as the only file in `/usr`.
4. A user may want to configure their system in some other way.

Luckily, this problem has largely been solved through the `XDG_DATA_DIRS` and `XDG_DATA_HOME` (for read-write) environment variables, containing a colon-separated list of base directories. As a NixOS user, I can confirm that every program on my system currently respects this. Here's the value of this environment variable on my system for reference:
```nushell
> $env.XDG_DATA_DIRS | split row :
┏─┬─────────────────────────────────────────────┓
│0│/home/lordmzte/.nix-profile/share            │
│1│/nix/profile/share                           │
│2│/home/lordmzte/.local/state/nix/profile/share│
│3│/etc/profiles/per-user/lordmzte/share        │
│4│/nix/var/nix/profiles/default/share          │
│5│/run/current-system/sw/share                 │
│6│/home/lordmzte/.local/share                  │
┗─┴─────────────────────────────────────────────┛
```
Nushell should append `nushell/vendor/autoload` to all these paths as well as `XDG_DATA_HOME` and search them in order. For more details, see the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables).

**Comment by fdncred** [comment]
Thanks for your opinion. This is the way nushell currently works.

The `$nu.vendor-autoload-dir` can be controlled at compile time with the environment variables NU_VENDOR_AUTOLOAD_DIR or PREFIX. This way, if a distribution packager wants to build with a specific autoload dir, they can do that.

https://github.com/nushell/nushell/pull/13180
https://github.com/nushell/nushell/pull/13217

**Comment by IanManske** [comment]
> 1. `/usr/local` is reserved through software installed manually ...

Yep, I agree that `/usr/share` would be better.

> 2. Per-user installations will typically go into `~/.local`. Software with nushell externs installed per-user will not work with the current approach.

For now we are not concerned with / do not have a method for user-specific config/completions. `$nu.vendor-autoload-dir` is for system files I believe? But I would be in favor of adding some mechanism to address this. Perhaps using the `$nu.data-dir` that was also added?

> 3. and 4.

Oh that's right, I forgot `XDG_DATA_DIRS` was a thing. Yeah, I think this makes sense, it actually fits quite nicely.

**Comment by fdncred** [comment]
> $nu.vendor-autoload-dir is for system files I believe?

Yes, this is a system level directory, not a user level directory.

**Comment by LordMZTE** [comment]
> The `$nu.vendor-autoload-dir` can be controlled at compile time with the environment variables NU_VENDOR_AUTOLOAD_DIR or PREFIX. This way, if a distribution packager wants to build with a specific autoload dir, they can do that.

I don't think this covers all cases. First, why should only system-wide software have working completions? If someone installs software in `~/.local`, which usually follows the same structure, that should ideally be loaded too. Another example where this wouldn't work is Nix, where someone can open a shell with some program with out installing it. These shells will have `XDG_DATA_DIR` updated with a directory for that software. Recompiling the shell every time here is not a sensible solution.

**Comment by jcgruenhage** [comment]
There is some more background regarding autoloading in https://github.com/nushell/nushell/issues/11337. For those that haven't read this yet, it might be worth doing so to get additional context.

> > 1. `/usr/local` is reserved through software installed manually ...
> 
> Yep, I agree that `/usr/share` would be better.

Actually, if your build tooling is setting the `PREFIX` env var, you cal already make it go into `/usr/share` instead of `/usr/local/share`. I think this is something the packager has to handle (see https://github.com/chimera-linux/cports/pull/2504/files#diff-87162a8fa49cf924757c7ba1bfc0089d3f3dce841b941927812b55943cd511b0R5-R7 for example), and for binaries that are not handled by a distribution, `/usr/local/share` is the right place. I don't think there is anything to do regarding this specific problem.

The rest of the problems: Yeah, that should all happen at some point down the line, fully agreed. I'm sure it'll be coming later, this is just a first implementation of this functionality to get the ball rolling :)

**Comment by jcgruenhage** [comment]
Thinking about this again I've realised a mistake in my reasoning: It's not about nushell being shipped by the distro or not, which makes the decision whether it should look in `/usr/local/share` or `/usr/share`: The `vendor/autoload` files are not coming from nushell, but from nushell extensions or other tools shipping completions or stuff like that after all. Taking this into perspective, nushell should check *both* of these directories, or rather go straight for `XDG_DATA_DIRS` and `XDG_DATA_HOME`. My conclusion that checking the `PREFIX` during compilation is enough for that specific problem was wrong.

**Comment by fdncred** [comment]
I don't have a problem changing the folder from `/usr/local/share/nushell/vendor/autoload` to `/usr/share/nushell/vendor/autoload`. The PR originally started there https://github.com/nushell/nushell/pull/13180/commits/d04741603d68387113a014b79fe3b295e9c833fd but if I recall correctly, I think maybe @devyn? thought that /usr/local/share was the wrong folder. I could be misremembering. I was trying to get some PR in that people could use.

I'm also not opposed added XDG_DATA_DIRS as an auto-load user-level folder. Adding a user-level auto-loading folder was always the plan as well. If someone wants to put together a PR, we'll review it.

**Comment by devyn** [comment]
Yes, my opinion is that `/usr/local` should be the default and almost every package manager should override the prefix to `/usr`. This is because most systems reserve `/usr` for files managed by the package manager, and `/usr/local` is the one that can be managed by the user's own system wide installation of things if they so choose.

I'm not opposed to checking the `XDG_DATA_DIRS` too, I think I suggested having some environment variable to add to that list but if there's a good standard one we might as well do that. What matters most is that we get the prefixes right - `/share` should be added to `PREFIX` but I think not to the `XDG_DATA_DIRS`.

I don't believe that we should necessarily build everything around what Nix expects but if it makes things easier and seems reasonable then I'm okay with it.

**Comment by jcgruenhage** [comment]
> Yes, my opinion is that `/usr/local` should be the default and almost every package manager should override the prefix to `/usr`. This is because most systems reserve `/usr` for files managed by the package manager, and `/usr/local` is the one that can be managed by the user's own system wide installation of things if they so choose.

As I mentioned in my second reply: This reasoning is flawed. The files that nushell loads from these directories are not owned by the nushell installation/package, they are owned by which ever vendor extension is automatically loaded from them. As such, there might very well be extensions automatically loaded from both places. It should look in both, or rather, it should look in `XDG_DATA_DIRS`, which falls back to ` /usr/local/share/:/usr/share/` if not set according to the spec, which results in looking into both of them.

> I'm not opposed to checking the XDG_DATA_DIRS too, I think I suggested having some environment variable to add to that list but if there's a good standard one we might as well do that. What matters most is that we get the prefixes right - /share should be added to PREFIX but I think not to the XDG_DATA_DIRS.

Already on it? If not, I'd be willing to tackle this.

**Comment by jcgruenhage** [comment]
> I'm also not opposed added XDG_DATA_DIRS as an auto-load user-level folder. Adding a user-level auto-loading folder was always the plan as well. If someone wants to put together a PR, we'll review it.

`XDG_DATA_DIRS` is a list of system level folders. `XDG_DATA_HOME` is the user level equivalent.

**Comment by fdncred** [comment]
Thanks for the clarification.

**Comment by LordMZTE** [comment]
> I don't believe that we should necessarily build everything around what Nix expects but if it makes things easier and seems reasonable then I'm okay with it.

What I've proposed is not Nix-specific - I merely proposed that we should follow the XDG specification (linked in the original issue).
The only expectation Nix makes towards software is that it follows said specification, which has been unanimously agrees upon across most Unices.

Furthermore, I believe the concept of compile-time configuration to be fundamentally flawed because of the reasons already explained by @jcgruenhage. We should remove this entirely.

**Comment by devyn** [comment]
We support platforms that don't or don't necessarily comply with the XDG specification. It is the norm for most programs to have a compiled in `PREFIX` to fall back to.

**Comment by devyn** [comment]
To be clear though, I definitely think that should take a backseat to `XDG_DATA_DIRS`, that sounds like a better solution.
