### ISSUE TITLE
Command history should first give the last command in that tab

### ISSUE THREAD

**Issue by ejerke** [nushell/nushell#13375]
### Related problem

I have multiple terminal tabs open and I have one thing running on each of them. When I want to rerun one of them, I expect to be able to just Ctrl+C, up-arrow and Enter. However, If I have run something else since the last time I ran that command, it won't give the last command run in that tab/window.

### Describe the solution you'd like

Any time you press the up-arrow the first time, it should give you the latest command run in that tab/window, not the latest from command history.

### Additional context and details

This seems to be implemented across terminal windows, but not across tabs.

Edit: Was trying it out a bit more and it seems like this is actually a bug not a feature request. The bug seems to be present both across tabs and windows.

**Comment by ysthakur** [comment]
Try setting sync_on_enter to false in your config (https://github.com/nushell/nushell/blob/main/crates/nu-utils/src/sample_config/default_config.nu#L198).

**Comment by ejerke** [comment]
@ysthakur Thanks for the quick answer! That does indeed seem to satisfy my request.

However, I feel like nushell should also have option to sync on enter, but still satisfy this, such as zsh. What I mean is that I often do want to share some of the commands between the terminal sessions. This sync_on_enter is a very black and white solution and I feel like it could be more elegant.

**Comment by ysthakur** [comment]
Yeah, that would be nice. Could you look over in Reedline (nushell/reedline) to see if such a feature exists, and if not, file an issue there?

**Comment by ysthakur** [comment]
Also, check out Atuin (https://atuin.sh/), I think it has what you want.

**Comment by ejerke** [comment]
Will do, thanks!!
