### ISSUE TITLE
"cd ..." and Tab should show the files in that folder?

### ISSUE THREAD

**Issue by ejerke** [nushell/nushell#13380]
### Question

When constructing a command such as "cd ..." and pressing tab, I would expect to see the files in that folder. Should this be working?

Edit: removed question about interpreting the "..." as not a glob-expansion. Since "go test ./..." can be run with `go test './...'`

**Comment by coodeneko** [comment]
This might explain some odd actions I am getting running p4 from nushell as well.

**Comment by ejerke** [comment]
@coodeneko You're right, thx! Edited the question accordingly.

**Comment by Ancient77** [comment]
I'm not quite sure what the issue is. Could you possibly provide an example and let me know what it produces, as well as what you would ideally like it to produce?

**Comment by ejerke** [comment]
Sure @Ancient77! I would expect the same behavior as with "cd .." and "cd ..." (apparently you have to add a forward slash in nushell):
**Expected:**
In my home directory, typing "cd ../" and pressing Tab I expect to see all user home directories.
In my home directory, typing "cd .../" and pressing Tab I expect to see all directories in root.

**Actual:**
"cd ../" + Tab works as expected.
"cd .../" + Tab: "NO RECORDS FOUND"

Seems like the glob expansion happens only after pressing enter?
