### ISSUE TITLE
Help for main subcommands 

### ISSUE THREAD

**Issue by soanvig** [nushell/nushell#13397]
### Describe the bug

We are able to define `main` function to be run automatically when the file is run from shell.
We can define documentation for `main` function, and it properly works with `--help`.

However when we define main subcommands they work, but don't display in help.

### How to reproduce

`file.nu`:
```nushell
#!/usr/bin/nu

# My main function
def main [] {}

# Main subcommand
def 'main sub' [] {}
```

```
> nu ./file.nu --help
My main function

Usage:
  > main

Flags:
  -h, --help - Display the help message for this command
```

### Expected behavior

Main function help works exactly like other functions help i.e. it supports subcommands

```
My main function

Usage:
  > main

Subcommands:
  main sub - Main subcommand

Flags:
  -h, --help - Display the help message for this command
```

### Configuration

| key                | value                                            |
| ------------------ | ------------------------------------------------ |
| version            | 0.94.0                                           |
| major              | 0                                                |
| minor              | 94                                               |
| patch              | 0                                                |
| branch             |                                                  |
| commit_hash        |                                                  |
| build_os           | linux-x86_64                                     |
| build_target       | x86_64-unknown-linux-gnu                         |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29) (Void Linux) |
| cargo_version      | cargo 1.78.0                                     |
| build_time         | 2024-06-14 00:11:58 +00:00                       |
| build_rust_channel | release                                          |
| allocator          | mimalloc                                         |
| features           | default, sqlite, system-clipboard, trash, which  |
| installed_plugins  |                                                  |

### Additional context

As an alternative solution I would also accept any hack to overcome that.
I tried `alias main = myFun` (where `myFun` contains subcommand), and then help works, but subcommands doesn't.

I tried aliasing all subcommands to `main <subcommand> = myFun <subcommand>` but it is tedious, and prints ugly help, because it prints aliases as well which lets to duplicated entries.

I tried working around it in various way, but nothing works. 
The only thing that really works is sourcing the file first, and not using `main` at all, but that is not acceptable, because instead of just running the script (which works as a command runner) requires two commands instead of one, and also pollutes the scope with some internal helper functions (unless I separate them into module). Automated sourcing is not acceptable as well, because it doesn't work in non Nu REPL environments.

I found Discord post about this: https://discord.com/channels/601130461678272522/1249462215430639716/1249486321160818739
That says it worked in 0.93

**Comment by sholderbach** [comment]
If I recall correctly the help reports it for user defined subcommands of a module (if you `use` the file and then call it by its name), so we have some logic for that, possible that there is something broken when run as a script (I thought we tried to rename the help text to the name of the script as you call it by that?)

**Comment by cboecking** [comment]
+1 for updating the -h options to return a list of subcommands.

[This was in interesting and helpful conversation](https://discord.com/channels/601130461678272522/1259580889218678975/1259580889218678975) about extracting subcommand help from a script (and it s relationship to modules). 

Using the thread's recommendation, I was able to create a subcommand that can be consumed by both the script and the module (see below alias comment). This means that I could use the module's help to extract some of the subcommand details.

```nu
#!/usr/bin/env nu
# Module description goes here...
# creating world peace

# creating world peace
export def main [] {
    help main # Return useful information
}

# informal salutations
export def hi [name: string] {
    $"Hello ($name)"
}
alias "main hi" = hi # must be defined after the namesake command definition
```

I hope this helps! Chuck

**Comment by soanvig** [comment]
@cboecking thank you. I tried that method (aliasing) as well, but it's extremely suboptimal for the reasons I pointed in original comment.
