### ISSUE TITLE
Some characters should not be *displayed* by `char --list` 

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#13395]
### Describe the bug

When running `char --list`, a few characters that are actually output to the terminal have undesired side-effects and should be suppressed.

### How to reproduce

`char --list`

* The bell will sound (or screen flash, if visual bell is set).  Since no character is output, the table alignment is off-by-one at this point.
* The backspace will also not take up any width, plus it will actually backspace a character, throwing off the table alignment by 2 characters on that line plus one character on all subsequent lines through the end of the table.

### Expected behavior

Just don't output those two characters.  They should still be *listed* in the set, but the actual output has the side-effects above (and would never display on-screen anyway as characters) so just don't attempt it.

### Screenshots

![image](https://github.com/user-attachments/assets/a542f5a9-0d71-487b-9b04-010b4e9c83ee)

### Configuration

Also tested under latest Windows release.

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.95.0                                   |
| major              | 0                                        |
| minor              | 95                                       |
| patch              | 0                                        |
| branch             |                                          |
| commit_hash        |                                          |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)      |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)      |
| build_time         | 2024-06-28 06:28:34 -04:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  |                                          |

**Comment by NotTheDr01ds** [comment]
Probably a good first issue candidate?

**Comment by fdncred** [comment]
ya, agreed. should be cleaned up.

**Comment by f3wenbo** [comment]
I want to fix this issue for my first task here. Is it ok?
If so, I want to confirm the expected behavior. Is it just now showing the *bel* and *backspace* in the `char --list` command?

**Comment by fdncred** [comment]
I'm ok with it if @NotTheDr01ds is. They may have already started fixing it. Not sure.

It should show bel and backspace in the list but just not actually issue bel or backspace actions.

**Comment by NotTheDr01ds** [comment]
@f3wenbo Yes, please do!  I'm still working on fixing @fdncred's theme preview scripts that I (and several others before me) broke ;-)

**Comment by fdncred** [comment]
I assigned it to you @f3wenbo

**Comment by f3wenbo** [comment]
@NotTheDr01ds Thank you. I am working on it now. By the way, what font are you using in the terminal?

**Comment by fdncred** [comment]
ya, probably so
