### ISSUE TITLE
couldn't fit table in 269 columns

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#13405]
### Describe the bug

@zhiburt Looks like more table rendering problems. This one comes from opening the sample.parquet file in my [nu_plugin_parquet](https://github.com/fdncred/nu_plugin_parquet) repo.
```nushell
❯ open sample.parquet
Couldn't fit table into 269 columns!
```
I think this also has to do with data because there are some strange characters in the last column of this parquet file. I can get it to fully display if I make my font small enough (so i have 314 columns).

### How to reproduce

1. clone the nu_plugin_parquet repo side-by-side with the cloned nushell folder
2. cargo install --path .
3. plugin add ~/.cargo/bin/nu_plugin_parquet
4. exit
5. start nushell again
6. make sure you're in the nu_plugin_parquet folder
7. open sample.parquet

### Expected behavior

open the parquet file, displaying the columns that fit on the screen.

### Configuration

|key|value|
|-|-|
|version|0.95.1|
|major|0|
|minor|95|
|patch|1|
|branch|main|
|commit_hash|22379c9846713c3905bc3e4ef5f9187113f5a689|
|build_os|windows-x86_64|
|build_target|x86_64-pc-windows-msvc|
|rust_version|rustc 1.77.2 (25ef9e3d8 2024-04-09)|
|rust_channel|1.77.2-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.77.2 (e52e36006 2024-03-26)|
|build_time|2024-07-18 16:15:34 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|default, sqlite, system-clipboard, trash|
|installed_plugins|bg 0.5.0, emoji 0.5.0, explore, file 0.5.0, formats 0.95.1, gstat 0.95.1, highlight 1.2.0+0.95.0, inc 0.95.1, json_path 0.5.0, jwalk 0.5.0, md 0.5.0, parquet 0.6.0, periodic_table, pnet 1.7.0, polars 0.95.1, query 0.95.1, query_git 0.5.0, regex 0.5.0, str_similarity 0.5.0, stress_internals 0.95.1|

**Comment by zhiburt** [comment]
I could picture it being all related with emojie issue;

But could you provide a sample file so I could test it.

**Comment by fdncred** [comment]
> I could picture it being all related with emojie issue;

It may be.

> But could you provide a sample file (`sample.parquet`) so I could test it.

It's in the repo above https://github.com/fdncred/nu_plugin_parquet

**Comment by zhiburt** [comment]
So got it on terminal width `291`.
99% percent is related to that same issue cause once I've got that panic.

I've tried to build with latest `tabled` but it will require a few hours; to say exactly...

Thanks for well explain reproducible by the way.

**Comment by fdncred** [comment]
ok, thanks for looking into it.
