### ISSUE TITLE
Screen scrolls up when pressing any key

### ISSUE THREAD

**Issue by eugenesvk** [nushell/nushell#13410]
### Describe the bug

0.95 started to have this issue on Windows with WezTerm with default config when it scrolls buffer up on any key press

On windows terminal the line flickers every time, so I guess it's the same issue (but no scrolling)

### How to reproduce

Open WezTerm with nushell 
Press any key

### Expected behavior

Whatever the key is supposed to do, nothing else, no scrolling

### Screenshots

https://github.com/user-attachments/assets/d85e45e8-ee47-41a1-8f84-660cf50397c5

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.95.0                                   |
| major              | 0                                        |
| minor              | 95                                       |
| patch              | 0                                        |
| branch             |                                          |
| commit_hash        | f93c6680bd5ae158190556eb1afc924b0290b52f |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)      |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)      |
| build_time         | 2024-06-25 18:41:02 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  |                                          |

### Additional context

n/a

**Comment by fdncred** [comment]
This is a dupe and and old issue https://github.com/nushell/nushell/issues/5585. It has to do with how WezTerm on windows handles OSC133. I think you can just disable it in your config to stop it from happening.

**Comment by eugenesvk** [comment]
Interesting, why did it work in the recent 93 version? If I disable it, I lose my mouse click zone selects :(
