### ISSUE TITLE
Multiline `input`

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#13420]
### Related problem

I stumbled upon a discussion (#13366), which asks about an `<<EOF` alternative.  I actually had a similar problem some time ago, when I wanted to manually write in a big chunk of text with newlines, which I didn't want to have in history[^rest].

[^rest]: But I did want to record the rest of the command, so just using space at the beginning wouldn't have worked.

### Describe the solution you'd like

Which brings me to the idea I had: a `--multiline` flag for the `input` command.  It would allow writing in text with newlines and terminating it with `Ctrl+D` aka EOF.  It can be used as a Bash `<<EOF` replacement and also for free-form input prompts.

**Comment by weirdan** [comment]
Looks like it's a duplicate of #11376

**Comment by KAAtheWiseGit** [comment]
Ah, that's right
