### ISSUE TITLE
Weird string quoting behavior for external commands

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#13431]
### Describe the bug

Quotes strike again:

```Nushell
~/fork/nushell> ^echo `"input"`
`input`
```

### Expected behavior

I expected it to be `"input"`, or at least `` `"input"` ``.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.95.0                                                       |
| major              | 0                                                            |
| minor              | 95                                                           |
| patch              | 0                                                            |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10) (Alpine Linux 1.79.0-r1) |
| cargo_version      | cargo 1.79.0                                                 |
| build_time         | 2024-07-05 13:45:14 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, system-clipboard, trash                     |
| installed_plugins  |                                                              |

**Comment by KAAtheWiseGit** [comment]
Oh, and the other quotes work correctly:

```Nushell
~/fork/nushell> ^echo "input"
input
~/fork/nushell> ^echo '"input"'
"input"
~/fork/nushell> ^echo "'input'"
'input'
~/fork/nushell> ^echo "`input`"
`input`
```

Until they don't:

```Nushell
~/fork/nushell> ^echo `'input'`
`input`
```

And this is just bizarre:

```Nushell
~/fork/nushell> ^echo `'"input"'`
`"input"`
```

**Comment by KAAtheWiseGit** [comment]
After playing around with it some more, I think the issue is that inner quotes tend to disappear inside of the literal ones:

```Nushell
~> ^echo `input ' other'`
`input  other`
~> ^echo `a"b"`
`ab`
~> ^echo `'a' "b"`
`a b`
```

The parser must be stripping the first and the last quotes:

```Nushell
~> ^echo ` a "string "with" quotes" `
` a string "with" quotes `
```

And whenever this happens the backticks appear, whereas usually they don't:

```Nushell
~> ^echo ` a string with quotes `
 a string with quotes 
```

**Comment by NotTheDr01ds** [comment]
(Arriving here via #13578) This seems expected to me.  A backtick string is essentially a [*"bare string that can include whitespace."*](https://www.nushell.sh/book/working_with_strings.html#string-formats-at-a-glance).

**Comment by KAAtheWiseGit** [comment]
The problem is that it's silently stripping a pair of quotes inside it, while retaining the outer ones.  And it only does this in external commands:

```Nushell
~> echo ` 'ident' `
 'ident' 
~> ^echo ` 'ident' `
` ident `
```

**Comment by NotTheDr01ds** [comment]
(Arriving here via #13578) 

Working through the scenarios, I think this is by design. It's a combination of two parsing "Rules":

* Rule 1: A backtick string is essentially a [*"bare string that can include whitespace."*](https://www.nushell.sh/book/working_with_strings.html#string-formats-at-a-glance).

* Rule 2: When passing quoted params to an external, Nushell removes the quotes. There's probably a better reference for this (and if not, there needs to be), but [from the 0.96 release notes](https://www.nushell.sh/blog/2024-07-23-nushell_0_96_0.html#consistent-parsing-for-known-externals-toc):

  > some of the more unique things we do for externals like removing the quotes in `--foo="bar"`

So yes, (I think) it's expected that Nushell strings off the single-or-double quotes when it appears to be quoting an argument to an external.

**Comment by KAAtheWiseGit** [comment]
@NotTheDr01ds but backtick strings doesn't contain the backticks itself.  But when passed to external strings, it does.  The reason Nushell strips quotes, as I see it, is because the arguments passed to native and external commands should be the same.  So, `nu-cmd --foo="bar"` will get the value `bar`, so `ex-cmd --foo="bar"` should also get `bar`, not `"bar"`.  Thus, it makes no sense to me that passing `` ` "ident" ` `` to native and external commands would yield a different result

**Comment by NotTheDr01ds** [comment]
Good point - It seems to me that Nushell should be stripping one level of outermost quotes, including backticks.  Is that what you're expecting here?

**Comment by KAAtheWiseGit** [comment]
I think so, yeah.  Overall, I'd expect two things:

- Quoted arguments/flags values should be the same, wherever they are being passed to external or native commands.
- Only the outermost layer of quoting is stripped.  So, if the first quote is `` ` ``, `"` shouldn't be stripped.  And visa versa.

**Comment by KAAtheWiseGit** [comment]
I've just stumbled upon a practical example of the issues this causes.  I was searching for a list of commands in my plugin, so I wanted to grep `"decode`.  I did the following:

```Nushel
~/project/nu-plugin/endecode> rg search `"decode`
```

Which yielded no results.  This is because `rg` gets `` `"decode` `` as the input instead of correct `"decode`.  So, I have to do this:

```Nushell
~/project/nu-plugin/endecode> rg "\"decode"
src/command/base58.rs
16:		"decode base58"

src/command/crockford.rs
15:		"decode crockford"

src/command/html.rs
15:		"decode html"

src/command/z32.rs
15:		"decode z32"

src/command/z85.rs
15:		"decode z85"
```

Which works correctly.

**Comment by weirdan** [comment]
In this specific case you could also do `rg '"decode'` or `rg r#'"decode'#`
