### ISSUE TITLE
Getting MallocStackLogging when running any command

### ISSUE THREAD

**Issue by noahbald** [nushell/nushell#13446]
### Describe the bug

I'm not sure of the exact issue, but nushell has started outputting the following when I run any command.

```
nu(6495) MallocStackLoggin: can't turn off malloc stack logging because it was not enabled.
```

### How to reproduce

Not sure on a clear reproduction, but this seems to have started after running `bat` within a `par-each`

### Expected behavior

I shouldn't see this message in my terminal

### Screenshots

![image](https://github.com/user-attachments/assets/1901eed0-ce3e-45a7-b94a-42be81e6bb5e)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.94.2                                          |
| major              | 0                                               |
| minor              | 94                                              |
| patch              | 2                                               |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | macos-aarch64                                   |
| build_target       | aarch64-apple-darwin                            |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29) (Homebrew)  |
| cargo_version      | cargo 1.78.0                                    |
| build_time         | 2024-06-03 07:38:55 +00:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
Does it happen on the latest version 0.96.0?

**Comment by hustcer** [comment]
> Does it happen on the latest version 0.96.0?

I guess yes. I have came across this issue a few days ago. I have to restart the terminal

**Comment by noahbald** [comment]
> Does it happen on the latest version 0.96.0?

I've just upgraded and it seems to be gone - but if it comes back I'll let you know

**Comment by noahbald** [comment]
> Does it happen on the latest version 0.96.0?

Yes, just updated and I'm still seeing this message - even after restarting the terminal

![image](https://github.com/user-attachments/assets/1ab0eb4e-6590-4128-b2db-f2c40b450acb)

---

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.94.2                                          |
| major              | 0                                               |
| minor              | 94                                              |
| patch              | 2                                               |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | macos-aarch64                                   |
| build_target       | aarch64-apple-darwin                            |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29) (Homebrew)  |
| cargo_version      | cargo 1.78.0                                    |
| build_time         | 2024-06-03 07:38:55 +00:00                      |
| build_rust_channel | release                                         |
| allocator          | mimalloc                                        |
| features           | default, sqlite, system-clipboard, trash, which |
| installed_plugins  |                                                 |

**Comment by noahbald** [comment]
Sorry, just noticed `nu --version` is different to `version` - I think zellij is doing something here.
If I do a hard restart it seems to be gone

**Comment by fdncred** [comment]
`nu --version` and `version` should report the same version. If they don't then you have two versions of nushell installed somehow.

**Comment by sholderbach** [comment]
Can you try a build with `cargo build --no-default-features --features plugin,trash-support,sqlite` to disable `mimalloc` which we use as a replacement allocator.

**Comment by noahbald** [comment]
> `nu --version` and `version` should report the same version. If they don't then you have two versions of nushell installed somehow.

Sorry, I don't mean to confuse - I believe my terminal session was restored with 0.94.2, so `version` gave that output, but the binary was updated, so `--version` had a different output.

I haven't had any issues so far running on 0.96.0, so this issue can probably be closed

**Comment by fdncred** [comment]
Thanks

**Comment by tgross35** [comment]
For what it's worth, I am seeing this error in 0.108.0:

```text
> nu --version
nu(552) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
0.108.0
```

I don't see a clear pattern but it seems to show up occasionally on long-running shells. Once it shows up, that shell session is "poisoned" an the error gets emitted with every command that gets run.

(I'm upgrading now to see if 0.109.1 fixes it)
