### ISSUE TITLE
`path exists` *I/O Error* on Partially Valid Non-Existent Paths

### ISSUE THREAD

**Issue by QORTEC** [nushell/nushell#13460]
### Describe the bug

When checking a `path` using Nushell commands, an I/O error occurs if there is a valid file path in the middle of the path being checked. This error has been directly observed with both `path exists` and `path type`. 
Instead of returning the expected result, Nushell exits with an **nu::shell::io_error** with the reason **Not a directory (os error 20)**.

### How to reproduce

Create and execute a Nushell script with the following content:

```nushell
#!/bin/nu

'' | save -f text_file
mkdir empty_dir

'does_not_exist' | path exists | print
'empty_dir' | path exists | print
'empty_dir/sub_dir' | path exists | print

'text_file' | path exists | print
'text_file/sub_dir' | path exists | print
```
Alternatively, you can run the sequence of commands above and observe the output.

### Expected behavior

All `path` commands should return the expected values for the entire path:
- The `path exists` command should return `false` when the path is nonexistent, 
  even if there is a valid file path in the middle of the path being checked.
- The `path type` command should return `null` when the path is nonexistent, 
  even if there is a valid file path in the middle of the path being checked.

### Screenshots

```
false
true
false
true
Error: nu::shell::io_error

  × I/O error
    ╭─[/mnt/truenas/qortec/GitHub/Owl-Package/linux-zfs/nushell/path_error.nu:12:1]
 11 │ 'text_file' | path exists | print
 12 │ 'text_file/sub_dir' | path exists | print
    · ─────────┬─────────
    ·          ╰── Not a directory (os error 20)
    ╰────
```

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.95.0                                      |
| major              | 0                                           |
| minor              | 95                                          |
| patch              | 0                                           |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | linux-x86_64                                |
| build_target       | x86_64-unknown-linux-gnu                    |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10) (Solus) |
| cargo_version      | cargo 1.79.0                                |
| build_time         | 2024-07-05 07:13:14 +00:00                  |
| build_rust_channel | release                                     |
| allocator          | mimalloc                                    |
| features           | default, sqlite, system-clipboard, trash    |
| installed_plugins  | query 0.95.0                                |

**Comment by sholderbach** [comment]
Can you check our behavior on the most recent release `0.96.0`, we have been working quite a bit on the internal handling of paths recently.

**Comment by QORTEC** [comment]
I have the exactly same error on version `0.96.0`:
| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.96.0                                      |
| major              | 0                                           |
| minor              | 96                                          |
| patch              | 0                                           |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | linux-x86_64                                |
| build_target       | x86_64-unknown-linux-gnu                    |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10) (Solus) |
| cargo_version      | cargo 1.79.0                                |
| build_time         | 2024-07-26 12:02:55 -04:00                  |
| build_rust_channel | release                                     |
| allocator          | mimalloc                                    |
| features           | default, sqlite, system-clipboard, trash    |
| installed_plugins  | query 0.96.0                                |

**Comment by KAAtheWiseGit** [comment]
Can confirm this.  The issue stems from the `try_exists` method on the Rust paths:

> By contrast, try_exists will return Ok(true) or Ok(false), respectively, if the path was verified to exist or not exist. If its existence can neither be confirmed nor denied, it will propagate an Err(_) instead. This can be the case if e.g. listing permission is denied on one of the parent directories.

And `path exists` currently bubbles up the errors from `try_exists` to the user.
