### ISSUE TITLE
Nushell reporting command not found error when binary is not executable

### ISSUE THREAD

**Issue by SUPERCILEX** [nushell/nushell#13477]
### Describe the bug

```
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #1:1:1]
 1 │ ./docs/plot-instruction-cdf.py
   · ───────────────┬──────────────
   ·                ╰── Command `./docs/plot-instruction-cdf.py` not found
   ╰────
  help: `./docs/plot-instruction-cdf.py` is neither a Nushell built-in or a known external command

```

### How to reproduce

Make a non-executable binary and try to run it.

### Expected behavior

This is very confusing because the file does exist, it just needs a `chmod +x`.

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.95.0                                      |
| major              | 0                                           |
| minor              | 95                                          |
| patch              | 0                                           |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | linux-x86_64                                |
| build_target       | x86_64-unknown-linux-gnu                    |
| rust_version       | rustc 1.81.0-nightly (4bc39f028 2024-06-26) |
| rust_channel       | nightly-x86_64-unknown-linux-gnu            |
| cargo_version      | cargo 1.81.0-nightly (4ed7bee47 2024-06-25) |
| build_time         | 2024-06-26 22:59:16 -07:00                  |
| build_rust_channel | release                                     |
| allocator          | mimalloc                                    |
| features           | default, sqlite, system-clipboard, trash    |
| installed_plugins  |                                             |

**Comment by WindSoilder** [comment]
I think it's already handled by #13589
