### ISSUE TITLE
`some_module some_submodule start --help` will show help for built-in `start`

### ISSUE THREAD

**Issue by maxim-uvarov** [nushell/nushell#13470]
### Describe the bug

It seems like a bug to me. It appeared in version 0.96.0 and did not exist in version 0.95. If a module contains a command with the same name as another command, calling this command using `some_mod capture start --help` will also return help for the built-in `start` command.

### How to reproduce

```
# recreate some_mod
mkdir 'some_mod';

r########'# start capturing commands and their outputs into a file
export def --env start [
    file: path = 'numd_capture.md'
    --separate # don't use `>` notation, create separate blocks for each pipeline
]: nothing -> nothing { }'######## | save some_mod/capture.nu;

r########'export module "capture.nu"'######## | save some_mod/mod.nu;
```

```
> use some_mod;
> some_mod capture start --help
```

<img width="852" alt="image" src="https://github.com/user-attachments/assets/d5591e9a-f8ac-46e9-9034-a3d09f7fc3a3">

### Expected behavior

I expect nushell to output only help for specified module

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.96.1                                   |
| major              | 0                                        |
| minor              | 96                                       |
| patch              | 1                                        |
| branch             | stor-no-ansi-reset                       |
| commit_hash        | 6a83a05e33d51784a76052ada5c1c1283692e4d1 |
| build_os           | macos-aarch64                            |
| build_target       | aarch64-apple-darwin                     |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)      |
| rust_channel       | 1.77.2-aarch64-apple-darwin              |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)      |
| build_time         | 2024-07-26 14:40:04 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  | polars 0.96.0, regex                     |

**Comment by sid-6581** [comment]
In addition, submodule commands named `main` are lumped in with the parent module `main`:

![image](https://github.com/user-attachments/assets/3e766ed4-a37b-484f-ab73-8c566681f83f)

Also, `help test subtest` doesn't work even though it's a command that's in scope:

![image](https://github.com/user-attachments/assets/96b6e05d-f989-4cf2-ac01-76bf01192312)

![image](https://github.com/user-attachments/assets/98e91508-dfdb-41e2-b014-fda020e2bbf9)

**Comment by rosshadden** [comment]
We have to use `main` in order to make imports work. But using `main` makes all the helps for all the main method show up. So the more you buy into Nushell's ecosystem the more frustrating it is.

![image](https://github.com/user-attachments/assets/093d75db-ab21-46a7-975c-1b0b2969e785)

**Comment by fdncred** [comment]
closed by https://github.com/nushell/nushell/pull/14490
