### ISSUE TITLE
`ls -f` should output absolute path for symlinks in `target` column

### ISSUE THREAD

**Issue by weirdan** [nushell/nushell#13479]
### Describe the bug

`help ls` says:
```
help ls | find "full-path"
╭───┬──────────────────────────────────────────────────────╮
│ 0 │   -f, --full-paths - display paths as absolute paths │
╰───┴──────────────────────────────────────────────────────╯
```
`ls -l` outputs the symlink target in the `target` column, which is a path (potentially not existing, but still)

Thus I think `ls -lf` should output a fully qualified path in the `target` column.

### How to reproduce

```
cd /tmp
mkdir bug
cd bug
ln -s a b
(ls -lf).target.0 # returns `a`
```

### Expected behavior

Nu should return `/tmp/bug/a` when `-f` flag is given.

### Configuration

| key                | value                                                         |
| ------------------ | ------------------------------------------------------------- |
| version            | 0.96.0                                                        |
| major              | 0                                                             |
| minor              | 96                                                            |
| patch              | 0                                                             |
| branch             |                                                               |
| commit_hash        | a80dfe8e807035ad8d5bb751b385315982e7aad6                      |
| build_os           | linux-x86_64                                                  |
| build_target       | x86_64-unknown-linux-gnu                                      |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)                           |
| rust_channel       | 1.77.2-x86_64-unknown-linux-gnu                               |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)                           |
| build_time         | 2024-07-24 01:05:44 +00:00                                    |
| build_rust_channel | release                                                       |
| allocator          | mimalloc                                                      |
| features           | default, sqlite, static-link-openssl, system-clipboard, trash |
| installed_plugins  | formats, gstat, inc, polars, query 0.95.0                     |

**Comment by amtoine** [comment]
thanks for the repro, i see what you mean now :pray:
