### ISSUE TITLE
make the `math` commands const

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#13482]
We could make the `math` commands const if that's something people are interested in. I just did `math sqrt` for funsies.
```nushell
❯ const PHI = (1 + (5 | math sqrt)) / 2
❯ $PHI
1.618033988749895
```

There's also PHI defined in the std lib although I always forget how to use it.
```nushell
❯ use std math PHI
❯ $PHI
1.618033988749895
```

_Originally posted by @fdncred in https://github.com/nushell/nu_scripts/issues/924#issuecomment-2254624897_

**Comment by amtoine** [comment]
and i support this idea :wink:

**Comment by fdncred** [comment]
It's not tricky to do, but there's a bunch of commands to do so that makes the repetitive work a bit of a drag. But it's good first issue worthy.

**Comment by amtoine** [comment]
agreed :+1:

**Comment by Qnbie** [comment]
Hello
I started to working on this issue

**Comment by amtoine** [comment]
@Qnbie, thanks a lot for working on this :pray: 

feel free to take inspiration from https://github.com/nushell/nushell/pull/13487
