### ISSUE TITLE
tee changes the input

### ISSUE THREAD

**Issue by j-xella** [nushell/nushell#13489]
### Describe the bug

`tee` converts everything to lists. So:

* `[ 1 2 3 ] | tee {}` - output is the same as input, as already a list
* `[ { a:b } ] | tee {}` - output is the same as input, as table is a list

BUT !!!

* `1 | tee {}` - input is a number, output is a list, with the number as the single element
* `{ a:b } | tee {}` - input is a record, output is a table of one row

This happens not only to the output of tee, but also to the input that is passed to the closure

### How to reproduce

Try the above examples, see the output.

### Expected behavior

`tee` should not tamper with the data passed to it, but forward it as is.

Or is this an expected behaviour?  Help doesn't mention it...

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.96.1                                   |
| major              | 0                                        |
| minor              | 96                                       |
| patch              | 1                                        |
| branch             |                                          |
| commit_hash        | f7d6c28a001f94f224e459e21df0da2ab5bdc923 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)      |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)      |
| build_time         | 2024-07-29 23:44:03 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
@devyn thoughts on this?

**Comment by devyn** [comment]
Yeah, someone else reported this a while ago. I didn't really intend for `tee` to be used on non-iterables, and it will probably require a separate code path to do this, but I think it makes sense.
