### ISSUE TITLE
gitpod stopped working

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1348]
**Describe the bug**
Seems like gitpod stopped working recently. Looks like it might be related to using a stable Rust older then 1.40.

**To Reproduce**
1. Try to land a PR
2. See that gitpod doesn't succeed
3. 

**Expected behavior**
It should be able to build all the PRs

@JesterOrNot - do you know how to update the image to a newer Rust, by chance?

**Comment by JesterOrNot** [comment]
I'll look into it

**Comment by JesterOrNot** [comment]
There is an active PR https://github.com/gitpod-io/workspace-images/pull/157

**Comment by jankeromnes** [comment]
FYI the fix was deployed and nushell seems to work well. 🙂
