### ISSUE TITLE
IR unable to double evaluate alias with $in

### ISSUE THREAD

**Issue by 132ikl** [nushell/nushell#13490]
### Describe the bug

This is a bit of a weird one, but I ran into it while re-sourcing my alias module while doing some testing. If you source and then re-source a module containing an alias that refers to `$in`, IR indicates that the `block is missing compiled representation`. The alias works fine, it just throws the error when you try to `source`. It seemingly also works if you edit the file, even if you don't change the offending alias?

```nushell
[rose@lilith ~/tmp] $ $env.NU_USE_IR
Error: nu::shell::name_not_found

  × Name not found
   ╭─[entry #1:1:6]
 1 │ $env.NU_USE_IR
   ·      ────┬────
   ·          ╰── did you mean 'USE_IR'?
   ╰────

[rose@lilith ~/tmp] $ source test.nu
[rose@lilith ~/tmp] $ source test.nu
```

In a different nu instance:

```nushell
[rose@lilith ~/tmp] $ $env.NU_USE_IR
true
[rose@lilith ~/tmp] $ source test.nu
[rose@lilith ~/tmp] $ source test.nu
Error:   × Can't evaluate block in IR mode
   ╭─[/home/rose/tmp/test.nu:1:1]
 1 │ alias foo = echo $in
   · ──────────┬──────────
   ·           ╰── block is missing compiled representation
   ╰────
  help: the IrBlock is probably missing due to a compilation error

```

### How to reproduce

1. Create a file with an alias that contains in, eg. `alias foo = echo $in`
2. With IR enabled, source the file.
3. Source the file again.

### Expected behavior

Re-source the file without error

### Configuration

| key                | value                                                                                                                                                              |
| ------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| version            | 0.96.2                                                                                                                                                             |
| major              | 0                                                                                                                                                                  |
| minor              | 96                                                                                                                                                                 |
| patch              | 2                                                                                                                                                                  |
| branch             | makepkg                                                                                                                                                            |
| commit_hash        | c31291753c0ab5383edcd2d3f93bc7d9eab69658                                                                                                                           |
| build_os           | linux-x86_64                                                                                                                                                       |
| build_target       | x86_64-unknown-linux-gnu                                                                                                                                           |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10)                                                                                                                                |
| rust_channel       | stable-x86_64-unknown-linux-gnu                                                                                                                                    |
| cargo_version      | cargo 1.79.0 (ffa9cf99a 2024-06-03)                                                                                                                                |
| build_time         | 2024-07-30 00:30:39 +00:00                                                                                                                                         |
| build_rust_channel | release                                                                                                                                                            |
| allocator          | mimalloc                                                                                                                                                           |
| features           | default, sqlite, system-clipboard, trash                                                                                                                           |
| installed_plugins  | custom_values 0.1.0, example 0.95.1, explore_ir 0.1.0, formats 0.95.1, gstat 0.95.1, inc 0.95.1, jwalk 0.6.0, polars 0.95.1, query 0.95.1, stress_internals 0.95.1 |

**Comment by WindSoilder** [comment]
I think it's already fixed in latest main :)
