### ISSUE TITLE
`rm *` does not remove file start with `.`

### ISSUE THREAD

**Issue by steelywing** [nushell/nushell#13493]
### Describe the bug

`rm *` does not remove file start with `.`

### How to reproduce

```
echo | save .test
rm *
```

### Expected behavior

Normal

### Screenshots

```
E:\test\test> ls                                                                                  07/31/2024 10:33:49 AM
╭───┬───────┬──────┬──────┬───────────────╮
│ # │ name  │ type │ size │   modified    │
├───┼───────┼──────┼──────┼───────────────┤
│ 0 │ .test │ file │  0 B │ 2 minutes ago │
╰───┴───────┴──────┴──────┴───────────────╯
E:\test\test> rm *                                                                                07/31/2024 10:35:54 AM
Error:   × File(s) not found
   ╭─[entry #34:1:4]
 1 │ rm *
   ·    ┬
   ·    ╰── File(s) not found
   ╰────


E:\test\test> ls                                                                                1 07/31/2024 10:35:57 AM
╭───┬───────┬──────┬──────┬───────────────╮
│ # │ name  │ type │ size │   modified    │
├───┼───────┼──────┼──────┼───────────────┤
│ 0 │ .test │ file │  0 B │ 2 minutes ago │
╰───┴───────┴──────┴──────┴───────────────╯
E:\test\test> 
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.96.1                                   |
| major              | 0                                        |
| minor              | 96                                       |
| patch              | 1                                        |
| branch             |                                          |
| commit_hash        | f7d6c28a001f94f224e459e21df0da2ab5bdc923 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)      |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)      |
| build_time         | 2024-07-29 23:43:54 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  |                                          |

**Comment by NotTheDr01ds** [comment]
I'd call this "as designed", personally.  That's normal behavior for most shells, especially those with Linux/Unix roots.  `rm *` intentionally skips "hidden" files, and "hiding" under Unix is done with a leading dot.

Core `rm` command comes from [`uutils/coreutils`](https://github.com/uutils/coreutils), and it includes this statement:

> uutils aims to be a drop-in replacement for the GNU utils. Differences with GNU are treated as bugs.

Thus by "as designed" conclusion.

**Comment by steelywing** [comment]
> Thus my "as designed" conclusion.

OK, so I should use `rm .*` to remove the files that start with `.`? (after the bug #13494 is fixed)

**Comment by NotTheDr01ds** [comment]
For a compact, cross-platform solution, you could:

```nu
> ls -a **/a     # Optional, but nice to "preview" the list first
> ls -a **/* | rm -r ...$in.name
```

See also [this Unix & Linux question](https://unix.stackexchange.com/q/77127/432493) - It's a pretty popular question with a lot of different (and, given the complexity, some wrong) answers.

The nice thing about Nushell in this case is that its `ls` *doesn't* return the `.` and `..` as results, unlike the Linux version.  That makes the above command more compact than its equivalent `xargs` version in other shells.  Note that the Nushell `glob` *does* return the current directory as a result of `glob **/*`, so I'd avoid that for this purpose.

**Comment by NotTheDr01ds** [comment]
Also, given that `ls` returns files starting with a leading dot on Windows, but not Linux, I guess there's an argument to be made that `rm` should treat Linux and Windows differently as well.  That said, it would probably require convincing the upstream `uutils` team that should be the case.  Nushell `ls` doesn't come from `uutils`, but `rm` does.

**Comment by steelywing** [comment]
@NotTheDr01ds Thanks for the explain 👏👏

**Comment by fdncred** [comment]
> Core rm command comes from [uutils/coreutils](https://github.com/uutils/coreutils), and it includes this statement:

@NotTheDr01ds I don't think that's the case. I don't see `uu_rm` anywhere in our source code. Although we probably should use the uu code for that command.
