### ISSUE TITLE
`random binary`

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#13500]
I realized today I needed a way to generate random bytes, but there isn't a function for that in the `random` family.

I'd propose a `random bytes <length>` signature.

**Comment by fdncred** [comment]
sounds good to me

**Comment by NotTheDr01ds** [comment]
Seems easy enough to create as a Nushell custom command, no?  Is it worth adding as a built-in?

**Comment by KAAtheWiseGit** [comment]
@NotTheDr01ds the reason I'm proposing it for the main shell is because there are already 5 other randomness command, including one for dice.

And I'm unsure about the `bytes`/`binary` thing.  The type is `binary`, but the commands to work with have the `bytes` prefix.

**Comment by NotTheDr01ds** [comment]
> the reason I'm proposing it for the main shell is because there are already 5 other randomness command, including one for dice.

Yeah, `dice` is already pretty ... dicey.  (/groan)

Honestly, though, it seems to me that some of these (`dice` and `chars` at least) would be great candidates for porting to `std`, at least once we get the start-up performance issue fixed.

> And I'm unsure about the `bytes`/`binary` thing. The type is `binary`, but the commands to work with have the `bytes` prefix.

True, but `random int`, `random float`, `random bool` all use the type.

**Comment by KAAtheWiseGit** [comment]
Yeah, I agree on both counts.
