### ISSUE TITLE
'from-ssv' skips empty elements and shifts the remaining columns to the left

### ISSUE THREAD

**Issue by kvrhdn** [nushell/nushell#1350]
**Describe the bug**
If a space-separated table has an empty element (i.e. there is a row that has no value for some column), `from-ssv` will not detect this and shift all the next element to the left.

**To Reproduce**
Run some command that has space-separated table with an empty element.

In the following example the `PORTS` column is empty for the first element. Because of this, the value of the next column (`NAMES`) is shifted to the left and `from-ssv` splits the data into 2 tables.

```
❯ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
a41566c3765f        docsrs_web          "/opt/docsrs/entrypo…"   2 minutes ago       Up 2 minutes                            docsrs_web_run_1ab629ca8b57
c009496a92d6        postgres:alpine     "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes        5432/tcp            docsrs_db_1

❯ docker ps | from-ssv
───┬──────────────┬────────────┬────────────────────────┬───────────────┬──────────────┬─────────────────────────────
 # │ CONTAINER ID │ IMAGE      │ COMMAND                │ CREATED       │ STATUS       │ PORTS 
───┼──────────────┼────────────┼────────────────────────┼───────────────┼──────────────┼─────────────────────────────
 0 │ a41566c3765f │ docsrs_web │ "/opt/docsrs/entrypo…" │ 2 minutes ago │ Up 2 minutes │ docsrs_web_run_1ab629ca8b57 
───┴──────────────┴────────────┴────────────────────────┴───────────────┴──────────────┴─────────────────────────────
───┬──────────────┬─────────────────┬────────────────────────┬───────────────┬──────────────┬──────────┬─────────────
 # │ CONTAINER ID │ IMAGE           │ COMMAND                │ CREATED       │ STATUS       │ PORTS    │ NAMES 
───┼──────────────┼─────────────────┼────────────────────────┼───────────────┼──────────────┼──────────┼─────────────
 1 │ c009496a92d6 │ postgres:alpine │ "docker-entrypoint.s…" │ 3 minutes ago │ Up 3 minutes │ 5432/tcp │ docsrs_db_1 
───┴──────────────┴─────────────────┴────────────────────────┴───────────────┴──────────────┴──────────┴─────────────
```

**Expected behavior**
I would expect `from-ssv` to detect if a column is empty and display the table correctly.
```
❯ docker ps | from-ssv
───┬──────────────┬─────────────────┬────────────────────────┬───────────────┬──────────────┬──────────┬────────────────────────────
 # │ CONTAINER ID │ IMAGE           │ COMMAND                │ CREATED       │ STATUS       │ PORTS    | NAMES
───┼──────────────┼─────────────────┼────────────────────────┼───────────────┼──────────────┼──────────┼────────────────────────────
 0 │ a41566c3765f │ docsrs_web      │ "/opt/docsrs/entrypo…" │ 2 minutes ago │ Up 2 minutes │          | docsrs_web_run_1ab629ca8b57 
 1 │ c009496a92d6 │ postgres:alpine │ "docker-entrypoint.s…" │ 3 minutes ago │ Up 3 minutes │ 5432/tcp │ docsrs_db_1 
───┴──────────────┴─────────────────┴────────────────────────┴───────────────┴──────────────┴──────────┴────────────────────────────
```

**Screenshots**
N/A

**Configuration (please complete the following information):**
Nu 0.9.0

**Comment by thegedge** [comment]
I think this is working as expected. If you use `--aligned-columns` you'll get the expected result. What do you think, @kvrhdn ?

**Comment by kvrhdn** [comment]
Using `--aligned-colums` fixes this indeed. Note to myself: check the help page a bit more 😅 

But it's not clear to me why this isn't the default behaviour? In which cases would you _not_ want to parse using aligned columns?

**Comment by thegedge** [comment]
> But it's not clear to me why this isn't the default behaviour? In which cases would you not want to parse using aligned columns?

I'm not 100% sure why it wasn't chosen as the default, but my guess would be that  there's a cost to aligned columns, so whoever created this command would like for  the user to explicitly request that, or perhaps there are examples of commands that don't align the columns (I can't think of any right now), or maybe a bit of both.

Either way, we're really hoping to get aliases in soon, so if you wanted aligned columns to be the default, it should be easy to set up an alias that makes it do so 🎉 (I've done this for a lot of commands in my zsh profile)

**Comment by ilius** [comment]
I started defining functions in `config.toml` in startup section.
https://github.com/nushell/nushell/blob/main/docs/sample_config/config.toml

Once you get used to them, you will have much more power!

Aliases are very limited, for example you can't use pipe, unlike Bash.
But even in Bash, functions are recommended over aliases (except maybe for very simple cases).
