### ISSUE TITLE
`http post` is slow compared to other tools

### ISSUE THREAD

**Issue by freijon** [nushell/nushell#13512]
### Describe the bug

I'm porting a bash script to nushell. That's when I noticed a huge slow-down in performance. I narrowed it down to the `http post` requests.

### How to reproduce

1. Run `timeit { http post --raw --headers [Cookie "sid=foo"] --content-type application/json $"https://www.deezer.com/ajax/gw-light.php?method=song.
getListData&api_version=1.0&api_token=bar" { sng_ids: 355777961 }` --> will take between 1.5sec and 2.5sec for me
2. Run `timeit { curl -s --header "Cookie: sid=foo" $"https://www.deezer.com/ajax/gw-light.php?method=song.getListData&api_version=1.0&api_token=bar"
--data '{"sng_ids":[355777961]}' }` --> will take between 280ms and 350ms

### Expected behavior

Shouldn't take longer than comparable tools (I've tried `curl` and `xh`)

### Configuration

| key                | value                                        |
| ------------------ | -------------------------------------------- |
| version            | 0.95.0                                       |
| major              | 0                                            |
| minor              | 95                                           |
| patch              | 0                                            |
| branch             |                                              |
| commit_hash        |                                              |
| build_os           | linux-x86_64                                 |
| build_target       | x86_64-unknown-linux-gnu                     |
| rust_version       | rustc 1.77.1 (7cf61ebde 2024-03-27) (gentoo) |
| cargo_version      | cargo 1.77.1                                 |
| build_time         | 2024-07-26 07:29:12 +02:00                   |
| build_rust_channel | release                                      |
| allocator          | mimalloc                                     |
| features           | default, sqlite, system-clipboard, trash     |
| installed_plugins  | bin_reader                                   |

**Comment by cyradotpink** [comment]
This seems to be a quirk of deezer's API, where it takes no longer to respond to requests made with unknown/rare user agents. When I make `http post` pretend to be curl, it gets a response just as quickly: 
![image](https://github.com/user-attachments/assets/e881c4af-3677-48fc-a49a-6492a8d96184)

**Comment by freijon** [comment]
Indeed, I can reproduce it with a custom User-Agent. Thank you for figuring this out, wouldn't have thought of that.
