### ISSUE TITLE
`ls` doesn't sort files when passed a pattern

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#13527]
### Describe the bug

When executing `ls` in a current directory, it returns sorted results.  But when a path is passed to `ls`, the files are no longer sorted by name.

### How to reproduce

```Nushell
~> fs list /usr/bin/ | first 10
───┬────────────────────────┬─────────┬─────────┬──────────────
 # │          name          │  type   │  size   │   modified   
───┼────────────────────────┼─────────┼─────────┼──────────────
 0 │ /usr/bin/humanfriendly │ file    │   985 B │ 3 months ago 
 1 │ /usr/bin/fc-query      │ file    │ 14.3 KB │ 3 months ago 
 2 │ /usr/bin/gcc-ranlib    │ file    │ 34.7 KB │ 4 months ago 
 3 │ /usr/bin/unshare       │ symlink │    12 B │ 2 months ago 
 4 │ /usr/bin/bunzip2       │ symlink │    12 B │ 2 years ago  
 5 │ /usr/bin/grim          │ file    │ 35.1 KB │ a year ago   
 6 │ /usr/bin/lua           │ symlink │     6 B │ 2 months ago 
 7 │ /usr/bin/tar           │ symlink │     8 B │ 2 months ago 
 8 │ /usr/bin/wireplumber   │ file    │ 14.5 KB │ 3 months ago 
 9 │ /usr/bin/gio           │ file    │ 83.9 KB │ 2 months ago 
───┴────────────────────────┴─────────┴─────────┴──────────────
~> ^ls -1 /usr/bin/ | head -10
2to3
2to3-3.12
Xwayland
[
[[
abuild
abuild-addgroup
abuild-adduser
abuild-apk
abuild-fetch
```

### Expected behavior

I expected Nu's `ls` to always sort the file/directory names.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.96.0                                                       |
| major              | 0                                                            |
| minor              | 96                                                           |
| patch              | 0                                                            |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.80.0 (051478957 2024-07-21) (Alpine Linux 1.80.0-r0) |
| cargo_version      | cargo 1.80.0 (376290515 2024-07-16)                          |
| build_time         | 2024-07-29 21:29:54 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, system-clipboard, trash                     |
| installed_plugins  | endecode 0.1.0                                               |

**Comment by NotTheDr01ds** [comment]
See #13267

**Comment by KAAtheWiseGit** [comment]
Missed it in the search!
