### ISSUE TITLE
Multiple commands?

### ISSUE THREAD

**Issue by ryanpcmcquen** [nushell/nushell#1352]
Is there a way to chain two commands? `;` and `&&` do not work. How do I run something like?

```
which foo && echo 'hey'
```

**Comment by thegedge** [comment]
Definitely something we'll have to explore. We do have https://github.com/nushell/nushell/issues/740, so I'm going to close this one as a duplicate. I encourage you to subscribe to that issue if you want to keep track of  the progress or make suggestions.

**Comment by thegedge** [comment]
Duplicate of https://github.com/nushell/nushell/issues/740

**Comment by ryanpcmcquen** [comment]
Thanks!
