### ISSUE TITLE
Plugin Output Type Reporting Formatting Issue

### ISSUE THREAD

**Issue by fennewald** [nushell/nushell#13520]
### Describe the bug

When formatting the output of  `help <plugin command>`, if `plugin command` output type is extremely long, the table formatter will mis-calculate length.

Whatever my terminal width, the output is always 2 characters too wide. For the examples below, I added newlines so that the formatted text matches what was displayed on my terminal. In the true output, these newlines were not present.

```
Enumerate network interfaces on the current host

Usage:
  > net

Flags:
  -h, --help - Display the help message for this command

Input/output types:
  ╭───┬─────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─╮
  │ # │  input  │                                                             output                                                             
│
  ├───┼─────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─┤
  │ 0 │ nothing │ table<name: string, description: string, mac: string, ips: table<type: string, addr: string, prefix: int>, flags:             
 │
  │   │         │ record<is_up: bool, is_broadcast: bool, is_loopback: bool, is_point_to_point: bool, is_multicast: bool>>                      
 │
  ╰───┴─────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─╯
```

### How to reproduce

1. Define a plugin with a relatively complex return type. For example:
```text
table<name: string, description: string, mac: string, ips: table<type: string, addr: string, prefix: int>, flags: record<is_up: bool, is_broadcast: bool, is_loopback: bool, is_point_to_point: bool, is_multicast: bool>>
```
The corresponding signature definition, for convenience:
```rust
fn signature(&self) -> Signature {
    Signature::build(self.name()).input_output_type(
        Type::Nothing,
        Type::Table(Box::new([
            ("name".to_string(), Type::String),
            ("description".to_string(), Type::String),
            ("mac".to_string(), Type::String),
            (
                "ips".to_string(),
                Type::Table(Box::new([
                    ("type".to_string(), Type::String),
                    ("addr".to_string(), Type::String),
                    ("prefix".to_string(), Type::Int),
                ])),
            ),
            (
                "flags".to_string(),
                Type::Record(Box::new([
                    ("is_up".to_string(), Type::Bool),
                    ("is_broadcast".to_string(), Type::Bool),
                    ("is_loopback".to_string(), Type::Bool),
                    ("is_point_to_point".to_string(), Type::Bool),
                    ("is_multicast".to_string(), Type::Bool),
                ])),
            ),
        ])),
    )
}
```
2. Load the plugin
3. View the plugin signature with `help <plugin command>`

### Expected behavior

Correctly format the output type.

### Screenshots

<img width="3006" alt="Screenshot 2024-08-02 at 1 48 34 PM" src="https://github.com/user-attachments/assets/9dd0014d-56a9-4efc-a7ed-c3c3a043b29f">

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.96.0                                      |
| major              | 0                                           |
| minor              | 96                                          |
| patch              | 0                                           |
| branch             |                                             |
| commit_hash        | a80dfe8e807035ad8d5bb751b385315982e7aad6    |
| build_os           | linux-x86_64                                |
| build_target       | x86_64-unknown-linux-gnu                    |
| rust_version       | rustc 1.82.0-nightly (7120fdac7 2024-07-25) |
| cargo_version      | cargo 1.82.0-nightly (5f6b9a922 2024-07-19) |
| build_time         | 2024-07-26 14:50:41 +00:00                  |
| build_rust_channel | release                                     |
| allocator          | mimalloc                                    |
| features           | default, sqlite, system-clipboard, trash    |
| installed_plugins  | net 1.6.1                                   |

**Comment by sholderbach** [comment]
Do you observe the same for a command with huge types defined as a Nushell function or is this specific to plugins?

**Comment by fennewald** [comment]
Yes, I do observe the same behavior(exactly two characters too wide) for commands

**Comment by sholderbach** [comment]
OK, thanks for checking! Just for completeness you are using `tmux` as the terminal multiplexer, if there would be an interaction with the terminal width measurement?

**Comment by fennewald** [comment]
I was using iterm2 previously, tested with tmux and still see the behavior. I will test from alacritty later.

On closer inspection, the table is indented with two spaces at left, unlike normal table outputs. I'd bet this is the source of the issue: the table formatter is not accounting for the padding added by the help output formatter.

**Comment by sholderbach** [comment]
Ah that sounds like a good guess!

**Comment by Embers-of-the-Fire** [comment]
Possibly associated code:

https://github.com/nushell/nushell/blob/85b06b22d99942062f1dccd201616396211721a4/crates/nu-engine/src/documentation.rs#L337-L359

The documentation generator manually adds a padding to the result of `table` command. However, if the content is too long, the two whitespace will lead to the error reported by this issue.

Potential solution:

Add a `padding` arg for `table` command and avoid writing manual padding.
