### ISSUE TITLE
`repeat` and `str repeat`

### ISSUE THREAD

**Issue by Embers-of-the-Fire** [nushell/nushell#13534]
### Related problem

I want to repeat some existing data, but I couldn't find a replacement for methods like `Itertools::repeat` or `<&str>::repeat` in nu. Perhaps indirect implementation can be achieved using methods such as `each`, but I think adding an explicit command would be a better option.

### Describe the solution you'd like

`repeat`:

```nu
> [1, 2] | repeat 3
[1, 2, 1, 2, 1, 2]
```

`str repeat`:

```nu
> "nu" | repeat 3
nununu
```

### Describe alternatives you've considered

The specific implementation form, command names, and additional flags need to be discussed.

**Comment by hustcer** [comment]
We already have `repeat` in `std`:
```nu
use std repeat

'nu' | repeat 3 | str join
```

**Comment by Embers-of-the-Fire** [comment]
> We already have `repeat` in `std`:
> 
> ```nu
> use std repeat
> 
> 'nu' | repeat 3 | str join
> ```

I have been using nu for too long and didn't even consider the concept of std :(
