### ISSUE TITLE
Autocomplete Wraps Paths With Spaces in Quotes 

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#1353]
**Describe the bug**
When using `tab` to complete a directory name when typing in a path, if that path has a space in it, the entire path is wrapped in quotes (`"`) after the autocomplete finishes.

**To Reproduce**
1.  Use a command that requires a path, such as `cd`.  Navigate to a directory whose name has a space and then use the `tab` button to autocomplete the directory name
2. Notice that the entire path is then wrapped in quotes

**Expected behavior**
While this isn't entirely wrong (quotes can be used to wrap a path that has directories with spaces to make it valid), it breaks the flow of typing, since you'll hit the `tab` button and the autocomplete will wrap the path in quotes, then you have to move the mouse back inside of the last quote to continue typing your path.  Additionally, I think this breaks using `tab` to autocomplete after this.

One way to get around it would be to insert an escape symbol (`\`) before the space upon autocompleting a path name with a space in it, such as bash and zsh do:

Ex: `cd Programming/Rust/Forked\ Repos/`

But I don't know how all operating systems deal with this (mostly, I have no way of knowing what Windows does when autocompleting a folder name with a space in it)

I haven't done any testing, but I would guess this is related issue https://github.com/nushell/nushell/issues/1314 and its fix https://github.com/nushell/nushell/pull/1325

**Configuration (please complete the following information):**
 - OS: macOS 10.15.3
 - 0.9.0

**Screenshots**

Before autocomplete:
<img width="762" alt="Screen Shot 2020-02-06 at 7 13 33 PM" src="https://user-images.githubusercontent.com/19867440/73989730-d3cfb580-4914-11ea-9932-fd99ee220f70.png">

After autocomplete:
<img width="762" alt="Screen Shot 2020-02-06 at 7 13 35 PM" src="https://user-images.githubusercontent.com/19867440/73989732-d6320f80-4914-11ea-8e1b-017684c16db8.png">

**Comment by JosephTLyons** [comment]
The suggested solution will not work, as using `\` before a space will break the parser and flag the remainder of the path as an error.

**Comment by thegedge** [comment]
Agreed, this feels like it breaks the flow of typing. Sounds like it a parser issue, regardless of the solution. For example, if the parser could understand `"a/b/c"/not/in/quotes`, the current autocomplete behaviour could work too.

**Comment by thegedge** [comment]
We're consolidating the completions effort in #290 for now. After we close off that issue, we can open (or reopen) specific issues related to completions that weren't resolved with the consolidated effort.
