### ISSUE TITLE
Add --to-float to the str plugin

### ISSUE THREAD

**Issue by 8176135** [nushell/nushell#1354]
**Is your feature request related to a problem? Please describe.**
When I try to parse a csv file floats, I find that can't sum a list of floats/decimals.

**Describe the solution you'd like**
Add a --to-float to the `str` plugin, and after looking through the source, it seems `sum` doesn't sum floats/bigdecimal either

**Describe alternatives you've considered**
N/A

**Additional context**
I'm not sure what other commands need float support as well.

This seems easy enough to implement, so I'll try to do it myself, and create a PR if what I propose sounds fine.

**Comment by thegedge** [comment]
👍 although I would probably introduce some new command, as `str` doesn't scream "convert to float". Seems like we need some kind of `convert` or `coerce` command that can handle converting between types. Probably needs some design thought 🙂

**Comment by thegedge** [comment]
Since we already have a `--to-int`, seems reasonable to add a `--to-float`.

I do feel like `str` is becoming a "bloated" command, with a lot of flags, but that's a separate issue.
