### ISSUE TITLE
Nushell panics on output of external command without trailing newline

### ISSUE THREAD

**Issue by kvrhdn** [nushell/nushell#1355]
**Describe the bug**
When the output from an external command does not have a trailing newline, Nushell will crash when trying to read it.

**To Reproduce**
Bug was discovered using [`hub`](https://hub.github.com/). I use this utility to query the Github API.

The following command crashes the shell:

```
❯ hub api 'orgs/nushell/repos' | from-json
thread 'main' panicked at 'Internal error: could not read lines of text from stdin', src/commands/classified/external.rs:276:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```

I _think_ this is caused by the lack of newline and the end of the output from `hub`. ZSH shows a `%` at the end of the output.

Note the following works and simply prints the raw JSON:
```
❯ hub api 'orgs/nushell/repos'
[{"id":186024298,"node_id":"MDEwOlJlcG9zaXRvcnkxODYwMjQyOTg=","name":"nushell","full_name":"nushell/nushell","private":false,...
```

**Expected behavior**
I would expect Nushell to be able to handle input without trailing newline.

So, the following should work:
```
❯ hub api 'orgs/nushell/repos' | from-json
```

**Screenshots**
N/A

**Configuration (please complete the following information):**
Nu 0.9.0 (built from master a couple of days ago)

**Comment by thegedge** [comment]
Not 100% sure what's happening here, but it seems to be specific to `hub` (other commands likely exist that would exhibit a similar behaviour). Here's what we're seeing:

```
Err(Custom { kind: UnexpectedEof, error: "bytes remaining in stream" })
```

Still digging, but not 100% sure why that would be happening.

**Comment by thegedge** [comment]
Ah, I think I may know why. `LinesCodec` is unhappy with a single line that doesn't end in `\n`, which is what `hub` outputs:

```
$ hub api 'orgs/nushell/repos' | wc -l
       0
```

**Comment by thegedge** [comment]
Okay, I actually have another idea that I think will potentially be quite valuable moving forward. Instead of emitting lines or strings or bytes into an `InputStream`, we emit something that indicates a pipe / `AsyncRead`. The receiving end then has to decide how to read from it (byte by byte, chunks, all at once, etc).

This should resolve A LOT of these quirks with externals. Just need to figure out what this looks like for plugins. Going to play around with the idea.

**Comment by thegedge** [comment]
https://github.com/nushell/nushell/pull/1364 will eliminate the panic with an informative message, which is an improvement. I think we should still make this work though.
