### ISSUE TITLE
after entering every symbol in the nushell prompt command line - newline is added before the prompt

### ISSUE THREAD

**Issue by oleks41** [nushell/nushell#13573]
### Describe the bug

not sure is this a bug of the nushell or of the wezterm, but if nushell is launched in the wezterm, - after typing any symbol from the keyboard past output of the terminal appended with a newline, so the gap between the output and the prompt begins to arise.

this happens only with nushell, standard windows terminal works okay

### How to reproduce

1. install wezterm
2. run nu

### Expected behavior

append a symbol typed to the prompt command line

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.96.1                                   |
| major              | 0                                        |
| minor              | 96                                       |
| patch              | 1                                        |
| branch             |                                          |
| commit_hash        | f7d6c28a001f94f224e459e21df0da2ab5bdc923 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)      |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)      |
| build_time         | 2024-07-29 23:43:54 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  |                                          |

### Additional context

~> wezterm.exe --version                                                                                                                                                     08.08.24 21:51:18
wezterm 20240203-110809-5046fc22

**Comment by fdncred** [comment]
there's several dupes of this. you most likely want to disable osc133 in the config.nu.
