### ISSUE TITLE
Add touch command

### ISSUE THREAD

**Issue by UltraWelfare** [nushell/nushell#1357]
Since there are already implementations of some commands such as `mv` `cp` etc, I think it would be also great to add the `touch` command.
Even in it's most simple stage it should support:
1. Creating an empty file (or even multiple empty files)
2. Updating access and modification time of a file

Creating an empty file is a simple piece of code but changing the access-modification times are a little bit harder because Windows handles metadata differently than Linux. We can consider using the crate [filetime](https://github.com/alexcrichton/filetime) since it's cross-platform and may make things easier.

**Comment by JesterOrNot** [comment]
Can I work on this one?

**Comment by jonathandturner** [comment]
@JesterOrNot please do :)

**Comment by JesterOrNot** [comment]
Thanks!
