### ISSUE TITLE
Single value output via -c

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1360]
**Describe the bug**
Follow-up from 
https://github.com/nushell/nushell/pull/1359

A single value output via -c seems to output a table but should be a simple value output. 

**To Reproduce**
1. Output a single value (like `echo foo`) via -c
2. 
3. 

**Expected behavior**
Simple text output

**Comment by thegedge** [comment]
Everything seems to work on my end, @jonathandturner:

```
$ cargo run --features=stable,test-bins -- -c "echo 1" 
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
     Running `target/debug/nu -c 'echo 1'`
1

$ cargo run --features=stable,test-bins -- -c "echo 'test'"
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
     Running `target/debug/nu -c 'echo '\''test'\'''`
test
```

**Comment by jonathandturner** [comment]
yeah, I couldn't repro it this morning, seems it got fixed.
