### ISSUE TITLE
Contribute Shell Integration Sequence for VS Code.

### ISSUE THREAD

**Issue by anthonykim1** [nushell/nushell#13607]
### Related problem

Running Terminal Run Recent Command via Command Palette shows nu shell commandline that is mixed up together with exit code and the datetime. 

### Describe the solution you'd like

pass in explicit commandline sequence and other shell integration sequence so we all can use shell integration to its full! 
https://github.com/microsoft/vscode/pull/225335 Should be merged soon, which would help sort/organize nuShell Commands by itself aside from other shell.

**Comment by fdncred** [comment]
I thought that was the point of osc633. Are you saying our osc633 isn't working?

**Comment by anthonykim1** [comment]
@fdncred Yes, I can see that it is defined as a constant here: https://github.com/nushell/nushell/blob/0eabbb88dd3ec6fc2a82228f42a0d88678e8ff19/crates/nu-cli/src/prompt_update.rs#L49 but don't think it is actually being used anywhere. 

Passing in the explicit 633 E sequence such as https://github.com/microsoft/vscode-python/blob/b872cb490f6281798aef24b20fd3afd8e0355ac6/python_files/pythonrc.py#L54 
(from Python extension), should help with unwanted characters such as prompt '>', exit code, datetime being placed into the history when 'Terminal: Run Recent Command' is triggered from the command palette. 

If it was just the commandline itself passed via 633 E sequence, users would just be able to click on previous command history triggered via command palette and run that historical command right away. (Instead of erroring out atm due to attachment of '>', exitcode, datetime. 



![Screenshot 2024-08-13 at 3 56 07 PM](https://github.com/user-attachments/assets/0348e31a-5edc-42c4-b8cd-3cfdde2319cf)

**Comment by fdncred** [comment]
it should be used if enabled in the config.nu file under the shell_integration section.

**Comment by sholderbach** [comment]
Is this the `PROMPT_INDICATOR` messing with the naive assumptions? If we print the "prompt" marker sequence in the free text section of the prompt and follow that up with the prompt indicator as built into reedline that would appear after it.

**Comment by fdncred** [comment]
I played around with adding OSC 633E here https://github.com/nushell/nushell/pull/13625

**Comment by anthonykim1** [comment]
Great, just saw the PR. @fdncred Thank you for doing this

**Comment by sholderbach** [comment]
Has this been closed in full by #13625 or are we missing additional bits?

**Comment by anthonykim1** [comment]
I think we should be good now :)

**Comment by jmoore34** [comment]
Started up VS Code today to see this :)

![image](https://github.com/user-attachments/assets/cce454c7-38ed-4170-bcfd-bb6115f0c797)
