### ISSUE TITLE
`glob` doesn't accept globs

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#13611]
### Describe the bug

Glob doesn't accept variables with type `glob`, as its signature defines `<glob>` as string.

### How to reproduce

```Nushell
~> def globbing [arg: glob] { glob $arg }
Error: nu::parser::type_mismatch

  × Type mismatch.
   ╭─[entry #3:1:33]
 1 │ def globbing [arg: glob] { glob $arg }
   ·                                 ──┬─
   ·                                   ╰── expected string, found glob
   ╰────
```

### Expected behavior

Glob should accept both `string` and `glob`.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.96.0                                                       |
| major              | 0                                                            |
| minor              | 96                                                           |
| patch              | 0                                                            |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.80.0 (051478957 2024-07-21) (Alpine Linux 1.80.0-r0) |
| cargo_version      | cargo 1.80.0 (376290515 2024-07-16)                          |
| build_time         | 2024-07-29 21:29:54 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, system-clipboard, trash                     |
| installed_plugins  | endecode 0.1.0                                               |

**Comment by fdncred** [comment]
I've thought about this in the past too. #13612 hopefully fixes it.
