### ISSUE TITLE
Ctrl+A doesn't select all text

### ISSUE THREAD

**Issue by MadSpindel** [nushell/nushell#13622]
### Describe the bug

Nushell doesn't select all text when Ctrl+A is pressed. Instead, it moves the cursor to the beginning of the text, without selecting anything.

https://github.com/user-attachments/assets/b21d66de-c847-4f73-96da-0846ab486e25

### How to reproduce

1. Start Windows Terminal with Nushell
2. Write some text
3. Press Ctrl+A

### Expected behavior

It should select all text as PowerShell does:

https://github.com/user-attachments/assets/6db8164f-7abc-4f3f-a5f4-fc1bf8253a8a

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.96.1                                   |
| major              | 0                                        |
| minor              | 96                                       |
| patch              | 1                                        |
| branch             |                                          |
| commit_hash        | f7d6c28a001f94f224e459e21df0da2ab5bdc923 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.77.2 (25ef9e3d8 2024-04-09)      |
| rust_channel       | 1.77.2-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.77.2 (e52e36006 2024-03-26)      |
| build_time         | 2024-07-29 23:43:54 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
You're welcome to change the keybindings in the config.nu to whatever works for you and your terminal.  These are already in the config.nu
```nushell
        {
            name: move_to_line_start
            modifier: control
            keycode: char_a
            mode: [emacs, vi_normal, vi_insert]
            event: { edit: movetolinestart }
        }

        {
            name: select_all
            modifier: control_shift
            keycode: char_a
            mode: emacs
            event: { edit: selectall }
        }
```
