### ISSUE TITLE
assert fails with invalid span

### ISSUE THREAD

**Issue by ThinkChaos** [nushell/nushell#13649]
### Describe the bug

The following reproducer causes `assert` to build an invalid span.

### How to reproduce

```nu
use std assert

def main [] {
  const rec = {x: "x", y: "y"}

  assert equal ($rec.x) $rec.y
}
```

Current output:
```plain
Error:   × invalid error format.
    ╭─[NU_STDLIB_VIRTUAL_DIR/std/assert.nu:44:16]
 43 │             msg: ($message | default "Assertion failed."),
 44 │ ╭─▶         label: ($error_label | default {
 45 │ │               text: "It is not true.",
 46 │ │               span: (metadata $condition).span,
 47 │ ├─▶         })
    · ╰──── `$.label.start` should be smaller than `$.label.end`
 48 │         }
    ╰────
  help: 94958 > 94940
```

### Expected behavior

Produce the expected error.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.95.0                                                            |
| major              | 0                                                                 |
| minor              | 95                                                                |
| patch              | 0                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29) (built from a source tarball) |
| cargo_version      | cargo 1.78.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, system-clipboard, trash                          |
| installed_plugins  |                                                                   |

**Comment by sholderbach** [comment]
Seems to be a duplicate of #10666

**Comment by ThinkChaos** [comment]
Yes, thanks! Posted my reproducer there.
