### ISSUE TITLE
Unbalanced delimiters on parens when stripping `"` from output of 2nd/last `$"...(... | str trim -c '"')"` before string ends

### ISSUE THREAD

**Issue by x10an14** [nushell/nushell#13667]
### Describe the bug

A minimal example illustrating it from real life:
```nu
2024-08-22 12:37:41+02:00: ~/Doc/statusplattform-nais-operator is 📦 v1.0.3 via 🦀 v1.78.0 via ❄️   impure (nix-shell-env) on ☁️
x10an14@laptop ❌1 ❯ : $"(nix eval '.#image.drvAttrs.imageName' | str trim --char '"'):(nix eval '.#image.drvAttrs.imageTag' | str trim --char '"')"
Error: nu::parser::unbalanced_delimiter

  × Unbalanced delimiter.
   ╭─[entry #49:1:124]
 1 │ $"(nix eval '.#image.drvAttrs.imageName' | str trim --char '"'):(nix eval '.#image.drvAttrs.imageTag' | str trim --char '"')"
   ·                                                                                                                            ┬
   ·                                                                                                                            ╰── unbalanced ( and )
   ╰────


2024-08-22 12:40:01+02:00: ~/Doc/statusplattform-nais-operator is 📦 v1.0.3 via 🦀 v1.78.0 via ❄️   impure (nix-shell-env) on ☁️
x10an14@laptop ❌1 ❯ : $"(nix eval '.#image.drvAttrs.imageName' | str trim --char r#'"'#):(nix eval '.#image.drvAttrs.imageTag' | str trim --char r#'"'#)"
Error: nu::parser::unbalanced_delimiter

  × Unbalanced delimiter.
   ╭─[entry #50:1:130]
 1 │ $"(nix eval '.#image.drvAttrs.imageName' | str trim --char r#'"'#):(nix eval '.#image.drvAttrs.imageTag' | str trim --char r#'"'#)"
   ·                                                                                                                                  ┬
   ·                                                                                                                                  ╰── unbalanced ( and )
   ╰────
   ```

### How to reproduce

1. Find a command that outputs string/byte/stream wrapped in `"`
2. See description for how to trigger error (NB: Must be piped to `| str trim`, _and_ this must be done more than once in string)
3. Profit

### Expected behavior

```nu
($"(nix eval '.#image.drvAttrs.imageName' | str trim --char '"'):(nix eval '.#image.drvAttrs.imageTag' | str trim --char '"')" == "<pseudo code for `imageName` string>:<pseudo code for `imageTag` string>") && echo "I worked as expected!"
```
NB: The github UI parser does not agree w/my version of which `#` count as comments:
![image](https://github.com/user-attachments/assets/fac267a1-efe5-4d82-8a25-82f8b698b1d7)

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.96.1                                                            |
| major              | 0                                                                 |
| minor              | 96                                                                |
| patch              | 1                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10) (built from a source tarball) |
| cargo_version      | cargo 1.79.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, system-clipboard, trash                          |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
When quotes give me problems, I find myself doing something like this.
```nushell
print $"(nix eval '.#image.drvAttrs.imageName' | str trim --char (char dq)):(nix eval '.#image.drvAttrs.imageTag' | str trim --char (char dq))"
```

**Comment by sholderbach** [comment]
Seems to be a version of #10327

Somehow the parser state is messed up after the `#` inline.

**Comment by x10an14** [comment]
> Somehow the parser state is messed up after the `#` inline.

Maybe, but remember: ["NB: The github UI parser does not agree w/my version of which `#` count as comments:"](https://github.com/nushell/nushell/issues/13667#issue-2480488192)

**Comment by x10an14** [comment]
@fdncred Where can I find the map containing `{"name": "dq", "character": "\""}`?

**Comment by fdncred** [comment]
> @fdncred Where can I find the map containing `[{"name": "dq", "character": "\""}]`?

I'm not sure what you're asking. General nushell questions can get answered pretty quickly on Discord. Maybe you're looking for the list of characters/abbreviations supported by the `char` command? If so, then `char --list` is what you're looking for.

**Comment by x10an14** [comment]
Sorry for delay in response, `char --list` shows the "map" I was looking for =)
