### ISSUE TITLE
Record can not be passed as args correctly  in some cases

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#13662]
### Describe the bug

Record can not be passed as args correctly in some cases:

### How to reproduce

1. Create a `record.nu` file:
```nu
# record.nu
def main [foo: record, --bar: record] {
    print $foo
    print $bar
}
```
2. Run `record.nu` with the following args:
```nu
# 1. Work as expected
> nu record.nu {a:1,b:'c'}
╭───┬───╮
│ a │ 1 │
│ b │ c │
╰───┴───╯

# 2. Dosn't work as expected
> nu record.nu {a:1,b:'c',c:'d'}
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[<commandline>:1:6]
 1 │ main "{a:1,b:c',c:'d}"
   ·      ────────┬────────
   ·              ╰── expected block, closure or record
   ╰────

# 3. Work as expected
> nu record.nu {a:1,b:'c',c:"d"}
╭───┬───╮
│ a │ 1 │
│ b │ c │
│ c │ d │
╰───┴───╯

```

### Expected behavior

`nu record.nu {a:1,b:'c',c:'d'}` should work just as `nu record.nu {a:1,b:'c',c:"d"}`

### Configuration

| key                | value                                                                 |
| ------------------ | --------------------------------------------------------------------- |
| version            | 0.97.1                                                                |
| major              | 0                                                                     |
| minor              | 97                                                                    |
| patch              | 1                                                                     |
| branch             | nightly                                                               |
| commit_hash        | 60769ac1ba3ea036d889f140095d855e5597840c                              |
| build_os           | macos-aarch64                                                         |
| build_target       | aarch64-apple-darwin                                                  |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29)                                   |
| rust_channel       | 1.78.0-aarch64-apple-darwin                                           |
| cargo_version      | cargo 1.78.0 (54d8815d0 2024-03-26)                                   |
| build_time         | 2024-08-21 03:38:23 +00:00                                            |
| build_rust_channel | release                                                               |
| allocator          | mimalloc                                                              |
| features           | default, sqlite, static-link-openssl, system-clipboard, trash         |
| installed_plugins  | formats 0.97.1, gstat 0.97.1, inc 0.97.1, polars 0.97.1, query 0.97.1 |

**Comment by sholderbach** [comment]
This seems to be a problem with quoting for externals (from the parent Nushell the call to `nu` with a script is just another external) and how we handle parsing of arguments inside a `nu` script invocation.

In the following error message it looks like the single quotes get mistreated. The "outer" ones seem to disappear while the inner ones remain.

> ```nu
> > nu record.nu {a:1,b:'c',c:'d'}
> Error: nu::parser::parse_mismatch
> 
>   × Parse mismatch during operation.
>    ╭─[<commandline>:1:6]
>  1 │ main "{a:1,b:c',c:'d}"
>    ·      ────────┬────────
>    ·              ╰── expected block, closure or record
>    ╰────
> ```
