### ISSUE TITLE
`^` assignment syntax in `$env` causing `nushell` to hang

### ISSUE THREAD

**Issue by RoloEdits** [nushell/nushell#13660]
### Describe the bug

```shell
Error:   × External command calls must be explicit in assignments
    ╭─[C:\Users\**\AppData\Roaming\nushell\env.nu:87:15]
 86 │
 87 │ $env.EDITOR = hx
    ·               ─┬
    ·                ╰── add a caret (^) before the command name if you intended to run and capture its output
 88 │ $env.VISUAL = code
    ╰────
  help: the parsing of assignments was changed in 0.97.0, and this would have previously been treated as a string.
        Alternatively, quote the string with single or double quotes to avoid it being interpreted as a command name.
        This restriction may be removed in a future release.
```

After adding the carrot to `hx` and `code`, I just see this when opening the terminal:
![image](https://github.com/user-attachments/assets/4b32f51e-eb74-4125-b66e-e9765e5b3cdb)

### How to reproduce

1. Change assignment for `$env.VISUAL` and `$env.EDITOR` as suggested to do for runnable commands with he carrot prefix
2. Open terminal
3. Hangs

### Expected behavior

Should open as normal, not trying to execute on an assignment.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.97.1                                   |
| major              | 0                                        |
| minor              | 97                                       |
| patch              | 1                                        |
| branch             | build                                    |
| commit_hash        | 4bc8963a3b80d3920dab91db6b7a0045d8993c11 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)      |
| build_time         | 2024-08-21 00:01:53 -07:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  |                                          |

**Comment by sholderbach** [comment]
The warning error was exactly introduced to prevent the situation you are describing after the [change that you don't need to parenthesize the right hand side of assignments](https://www.nushell.sh/blog/2024-08-20-nushell_0_97_1.html#more-consistent-parsing-of-assignment-toc):
You want to assign the *value* `hx` to the variable `$env.EDITOR` not the output of running `hx` to the variable.

In the help message at the bottom the two options are layed out, but the spanned note is maybe biased in one direction.

**Comment by sholderbach** [comment]
In your case you want to resolve the new ambiguity by quoting the name of the command that gets stored and executed later:

```nushell
$env.EDITOR = "hx"
$env.VISUAL = "code"
```
