### ISSUE TITLE
gcc: fatal error: cannot execute 'ld': execvp: Argument list too long

### ISSUE THREAD

**Issue by 0323pin** [nushell/nushell#13672]
### Describe the bug

Cannot compile v0.97.1 on NetBSD development branch.

Some of our build machines are hiting this problem already with v0.96.1 see, http://shadow.netbsd.org/pub/pkgsrc/packages/reports/HEAD/NetBSD-10.0-x86_64/20240821.1314/nushell-0.96.1/build.log

I can still compile v0.96.1 on my system, NetBSD mybox 10.99.11 NetBSD 10.99.11 (GENERIC) #0: Mon Aug 19 17:53:44 UTC 2024

But, now I'm stuck with this while compiling v0.97.1

The problem is that this is a really long command line  exceding the limit on NetBSD.

```
# sysctl kern.argmax
kern.argmax = 262144
```

On macOS for example it is 1048576.

### How to reproduce

NA

### Expected behavior

Should compile a working binary.

### Screenshots

NA

### Configuration

NA

### Additional context

Obviously, I could compile a custom kernel allowing a larger limit but, this wouldn't help updating the package, since the build servers will still have the default limits.

Increasing this at the OS level would also, only have an effect on the development branch. Releases will be years down the road.

Can you guys do something about this and help me keeping supporting `nu` on NetBSD?

Thank you.

**Comment by fdncred** [comment]
Interesting. It looks like nushell has reached some magical number of crates that makes the command line too long to compile. Not sure what the fix for that is other than reducing dependencies.

**Comment by 0323pin** [comment]
@riastradh This is becoming a bit more weird ...

Building `nushell`-0.97.1 in my home directory, _i.e._ outside pkgsrc, using `cargo build --release` works just fine.

We might be very close to the limit and something within pkgsrc is causing this to tip over.

**Comment by bsiegert** [comment]
@0323pin A big factor in the length of the command line is the location of the build directory. If you compile in `/home/pin/nushell`, that shaves off a ton of characters compared to `/usr/pkgsrc/shells/nushell/work/nushell-x.y.z` :)

**Comment by 0323pin** [comment]
Which basically means we are **really** close to the edge 😞

**Comment by 0323pin** [comment]
Right, I'd guess the risk is still there but, I've actually just managed to compile 0.98.0 within pkgsrc standard locations.

```
~> version | transpose key value | to md --pretty                                                                                                                   09/21/2024 08:14:56 AM
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.98.0                                                            |
| major              | 0                                                                 |
| minor              | 98                                                                |
| patch              | 0                                                                 |
| branch             | master                                                            |
| commit_hash        | 7411809b38577b8f5007882ced34ffc3cb4258a7                          |
| build_os           | netbsd-x86_64                                                     |
| build_target       | x86_64-unknown-netbsd                                             |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06) (built from a source tarball) |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)                               |
| build_time         | 2024-09-21 08:05:39 +02:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash                                            |
| installed_plugins  |                                                                   |
```

I'll bump the package from 0.96.1 to 0.98.0 when I find some time.

**Comment by 0323pin** [comment]
@sholderbach [Merged](http://mail-index.netbsd.org/pkgsrc-changes/2024/09/22/msg307604.html)

**Comment by 0323pin** [comment]
FYI `nushell`-0.98.0 built successfully on the official builds.

**Comment by sholderbach** [comment]
Awesome, thanks!
