### ISSUE TITLE
Allow Control Over Custom Completion Sorting

### ISSUE THREAD

**Issue by fj0r** [nushell/nushell#13696]
### Describe the bug

For the results returned by custom completion functions, it will be sorted again. However, in some scenarios, maintaining the order is more convenient.

### How to reproduce

```nu_script
mkdir test-completions
cd test-completions/
git init .
for i in 0..9 {
    echo $i | save -a out
    git add .
    git commit -m $i
}

def 'nu-complete git log' [] {
    git log --oneline 
    | lines
    | split column ' ' value description
}

def git-log [commit: string@"nu-complete git log"] {
    git log --stat -p -n 1   
}
```
After running git-log followed by pressing tab, the result is:
```
156dd77  9
20362fc  7
4cb007a  1
571e202  8
6567ef6  6
9f103f7  4
c0809ab  3
c257bc0  5
e31050e  0
f6752e0  2
```

### Expected behavior

```
156dd77 9
571e202 8
20362fc 7
6567ef6 6
c257bc0 5
9f103f7 4
c0809ab 3
f6752e0 2
4cb007a 1
e31050e 0
```

### Screenshots

![image](https://github.com/user-attachments/assets/2462cc32-69ef-4130-aed0-a1e9f21172d6)

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.97.1                                                           |
| major              | 0                                                                |
| minor              | 97                                                               |
| patch              | 1                                                                |
| branch             | makepkg                                                          |
| commit_hash        | 60769ac1ba3ea036d889f140095d855e5597840c                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06) (Arch Linux rust 1:1.80.1-1) |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)                              |
| build_time         | 2024-08-21 12:14:01 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | default, sqlite, system-clipboard, trash                         |
| installed_plugins  | custom_values, formats, gstat, polars, query, stress_internals   |

**Comment by fdncred** [comment]
This sounds like a discussion on Discord we just had https://discord.com/channels/601130461678272522/1276981416307069019

https://github.com/nushell/nushell/pull/4674

Here's an excerpt. We're considering removing this functionality.
```nushell
# completion
def "__z_complete" [line : string, pos: int] {
  let prefix = ( $line | str trim | split row ' ' | append ' ' | skip 1 | get 0)
  let data = (^zoxide query $prefix --list | lines)
  {
    completions : $data,
                options: {
                 completion_algorithm: "fuzzy",
                 positional: false
                }
  }
}
```
