### ISSUE TITLE
Add iCal/vCard support

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#137]
It'd be fun to be able to magic open up iCal and/or vCard files and get into the details

**Comment by wycats** [comment]
Is there a crate for this?

**Comment by PhilipConte** [comment]
I'd love to try to take a stab at this. Does [ical](https://crates.io/crates/ical) seem right?

**Comment by jonathandturner** [comment]
@PhilipConte - yeah that looks like it might work. Please feel free to give it a try and let us know how it goes.

**Comment by pulpdrew** [comment]
Is anyone else working on this anymore? If not, I can give it a shot

**Comment by jonathandturner** [comment]
@pulpdrew - please do!

**Comment by jonathandturner** [comment]
Added in #1504
