### ISSUE TITLE
Tab completion should go further in for single-branch dir trees

### ISSUE THREAD

**Issue by mattdkerr** [nushell/nushell#1371]
**Is your feature request related to a problem? Please describe.**
For many Java program source code trees there is a folder structure that looks like `<project>/src/main/java/com/<company abbrev>/<project>/<component>/...` . When using Bash or Clink tab completion, it has a nice behavior of moving further down the tree. This is because there is only a single choice for the next directory. Currently in 0.9.0 Nushell on Windows, the behavior instead is for a second hit of the tab in the same scenario it doesn't go further down the directory tree-- instead it cycles back to remove the subfolder.

**Describe the solution you'd like**
Make it more similar to what other shells are doing, which feels like a better solution.

**Describe alternatives you've considered**
Give a different tap style to complete the next single subfolder or any subfolder (double tap tab?)

**Comment by thegedge** [comment]
We're consolidating the completions effort in #290 for now. After we close off that issue, we can open (or reopen) specific issues related to completions.
