### ISSUE TITLE
Expose more openssl functionality

### ISSUE THREAD

**Issue by j-xella** [nushell/nushell#13734]
### Related problem

I understand that nu shell uses openssl internally already for http connections etc... But openssl is way more than that:

* keypair generation
* hashing
* document signing and signature verifying
* data encryption and decryption, both with password and key pairs
* working with x509 certificates
* ...

Wouldn't it be good to expose more of that functionality via nushell commands, so that it would be accessible in a platform-independent way? It would also open a whole new area where nushell could shine.

### Describe the solution you'd like

Just run `openssl -h` - it already has options and subcommands. nushell could start gradually implementing them, for example 

* `ossl dgst`
* `ossl genrsa`
* ...

I personally believe that `openssl` sub-command structure should be replicated as close as possible, to minimise the learning curve.

### Describe alternatives you've considered

using external openssl command line utility. But various versions are installed everywhere, and some systems may have it unavailable...

**Comment by j-xella** [comment]
Not a big difference from a user perspective, but wouldn't it be less efficient to implement it as a separate plugin, considering that  openssl code is already inside the main nu executable? What is required is just an interface to it.

**Comment by KAAtheWiseGit** [comment]
I presume a lot of SSL codes gets removed by the linker, so adding an explicit dependency might bloat the Nushell executable.  In addition, supporting the whole openssl suite doesn't feel like a job the base Nushell should do.  Nushell depends on a ton of libraries (more that 700 in total), and I don't think that it's a good idea to expose all of them to the user.

Also, since `openssl` is a transitive dependency through `native-tls`, it's not included in the Windows build:

```Nushell
[target.'cfg(not(target_os = "windows"))'.dependencies]
# Our dependencies don't use OpenSSL on Windows
openssl = { version = "0.10", features = ["vendored"], optional = true }
```

**Comment by fdncred** [comment]
I'd vote for scripts to wrap openssl. I'm not sure we'd have much appetite for built-ins for openssl. Maybe for a few commands potentially, but not for everything it does.

**Comment by NotTheDr01ds** [comment]
> scripts to wrap openssl

How portable would that be to Windows?

**Comment by sholderbach** [comment]
Resounding no as this would have significant costs for the maintenance of the core project for limited benefit to the users of this functionality (you already leave structured data to plain text for most encryption/signing work)

- Primary concern: Security as adding this would wildly grow our attack surface
  - Even though the most critical part of the implementation is provided by the cryptographic "backend" of e.g. openssl, still extra attention in the maintenance is necessary for such a "frontend" to provide proper defaults, be free of bugs/sidechannels/backdoors etc.
  - Additional need to respond to potential vulnerabilities upstream, not just for the well understood standard modern TLS to serve `http` client commands for the majority of usecases. Distributors may choose to dynamically link openssl but we also distribute as staticly linked builds. Those would have to release urgent patches for more kinds of openssl CVEs
- If we went all in to emulate the existing CLI suite around openssl utils specifically would limit us when attempting to switch our TLS backend (`rustls`, `libressl` etc.) 
- All the choices to make around, which commands/options/defaults to include, will take up bandwidth from the core nushell project (security adjacent decisions necessarily should draw more qualified eyeballs)

The choices are much easier if this a plugin maintained by someone willing to invest the necessary time and and attention to detail for the work around cryptography and security.

But the core of nushell we want to stabilize in a finite time is primarily a shell and a programming language and not an evergrowing crossplatform toolbox distribution.
