### ISSUE TITLE
Incorrect pipeline signature should not be ignored

### ISSUE THREAD

**Issue by j-xella** [nushell/nushell#13736]
### Describe the bug

When pipeline types are specified incorrectly in function signature, they are silently ignored. This is an error, and it should be treated accordingly.

### How to reproduce

```nushell
# incorrect, there should be a colon after argument specs
def test1 [] nothing -> nothing {}

# correct
def test2 []: nothing -> nothing {}
```

Above are 2 function definitions, the latter is the correct version of the former.

And yet both are accepted by nu shell. The former just gets the pipe spec quietly ignored and treated like `def test1 [] {}`.

### Expected behavior

Nu shell should raise exception when processing the definition of `test1`

### Configuration

| key                | value                                                         |
| ------------------ | ------------------------------------------------------------- |
| version            | 0.97.1                                                        |
| major              | 0                                                             |
| minor              | 97                                                            |
| patch              | 1                                                             |
| branch             |                                                               |
| commit_hash        | 60769ac1ba3ea036d889f140095d855e5597840c                      |
| build_os           | linux-x86_64                                                  |
| build_target       | x86_64-unknown-linux-musl                                     |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29)                           |
| rust_channel       | 1.78.0-x86_64-unknown-linux-gnu                               |
| cargo_version      | cargo 1.78.0 (54d8815d0 2024-03-26)                           |
| build_time         | 2024-08-21 03:29:44 +00:00                                    |
| build_rust_channel | release                                                       |
| allocator          | mimalloc                                                      |
| features           | default, sqlite, static-link-openssl, system-clipboard, trash |
| installed_plugins  | polars 0.97.1, query 0.97.1                                   |

**Comment by KAAtheWiseGit** [comment]
Related to #11266
