### ISSUE TITLE
Custom values cannot be decoded if value is using an enum

### ISSUE THREAD

**Issue by cptpiepmatz** [nushell/nushell#13743]
### Describe the bug

When creating a plugin that generates a `CustomValue` which is an `enum`, the custom value cannot be decoded properly by nushell.

### How to reproduce

1. Build [this plugin](https://gist.github.com/cptpiepmatz/d5cd23b7566e0770cf0d111e31f5ed5d#file-brokencustomvalueplugin-rs)
2. `plugin add` and `plugin use` it
3. Run `gen broken value`
4. Get an error
```sh
nu ❯ gen broken value
Error: nu::shell::custom_value_failed_to_decode

  × Custom value failed to decode
   ╭─[entry #1:1:1]
 1 │ gen broken value
   · ────────┬───────
   ·         ╰── Bincode does not support Deserializer::deserialize_identifier
   ╰────
  help: the plugin may have been updated and no longer support this custom value
  ```

### Expected behavior

I want to use enums in my code for custom values, so having them work would be great.

### Configuration

| key                | value                                                                        |
| ------------------ | ---------------------------------------------------------------------------- |
| version            | 0.97.1                                                                       |
| major              | 0                                                                            |
| minor              | 97                                                                           |
| patch              | 1                                                                            |
| branch             |                                                                              |
| commit_hash        |                                                                              |
| build_os           | windows-x86_64                                                               |
| build_target       | x86_64-pc-windows-msvc                                                       |
| rust_version       | rustc 1.80.0 (051478957 2024-07-21)                                          |
| rust_channel       | stable-x86_64-pc-windows-msvc                                                |
| cargo_version      | cargo 1.80.0 (376290515 2024-07-16)                                          |
| build_time         | 2024-08-22 14:56:22 +02:00                                                   |
| build_rust_channel | release                                                                      |
| allocator          | mimalloc                                                                     |
| features           | default, sqlite, system-clipboard, trash                                     |
| installed_plugins  | broken 0.1.0-broken-custom-value, highlight 1.2.2+0.97.1, plotters 0.1.0-wip |

**Comment by devyn** [comment]
Okay, I did a deep dive into this and I honestly can't understand why bincode doesn't support `deserialize_identifier()`. It's explicitly not implemented in bincode, but serde's generated code frequently uses it.

I did find that explicitly specifying `#[serde(tag = "t", content = "c")]` (adjacently tagged) on the enum made it work, but I don't really understand why this is required. I believe bincode is supposed to work out of the box with serde's default external tagging, so this is strange. I wonder if the generated code has changed at some point recently.

You may want to file an issue with bincode. For reference, this is bincode 1.x, and you should be able to reproduce it by serializing and deserializing a simple enum - even without any fields it seemed to fail.

In the meantime, I will consider switching us to MessagePack even for custom value content, as there are still some settings there to make it relatively efficient / comparable to bincode performance.
