### ISSUE TITLE
extra tokens in `def` or `extern` don't error out

### ISSUE THREAD

**Issue by 1Kinoti** [nushell/nushell#13748]
### Describe the bug

Extra tokens in `def` and `extern` are simply ignored

```nushell
def id [it] what is happening here? { $it }
#           -----------------------
#                      |
#           these tokens are ignored

extern cargo [] also happens here
#               -----------------
#                       |
#                these tokens too
```

This only happens if the tokens are put after the parameters

### How to reproduce

1. Write the code above

2. Run it
```nushell
# Runs perfectly
id 4
```

### Expected behavior

I expect nu to reject the extra tokens

### Configuration

| key                | value                                                         |
| ------------------ | ------------------------------------------------------------- |
| version            | 0.97.1                                                        |
| major              | 0                                                             |
| minor              | 97                                                            |
| patch              | 1                                                             |
| branch             |                                                               |
| commit_hash        | 60769ac1ba3ea036d889f140095d855e5597840c                      |
| build_os           | linux-x86_64                                                  |
| build_target       | x86_64-unknown-linux-gnu                                      |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29)                           |
| rust_channel       | 1.78.0-x86_64-unknown-linux-gnu                               |
| cargo_version      | cargo 1.78.0 (54d8815d0 2024-03-26)                           |
| build_time         | 2024-08-21 03:29:24 +00:00                                    |
| build_rust_channel | release                                                       |
| allocator          | mimalloc                                                      |
| features           | default, sqlite, static-link-openssl, system-clipboard, trash |
| installed_plugins  |                                                               |

**Comment by KAAtheWiseGit** [comment]
Related to #11266  Although it's more about type checking.

Maybe this one should be kept to track the parsing issue, because the example here is better
