### ISSUE TITLE
Inconsistent results when using `into datetime` on "x months ago" strings

### ISSUE THREAD

**Issue by salo-dea** [nushell/nushell#13759]
### Describe the bug

When using a string like "5 months ago" as input for `into datetime`, it may produce dates that are actually in the future.
For me anything more than "3 months ago" seems to give a date in the future.
"12 months ago" produces the same result as "now", with modulo behaviour ("13 months ago" == "1 month ago" etc.)

### How to reproduce

Run: `1..24 | each {$"($in) months ago" | {str: $in, interpreted: ($in | into datetime)}}`
Result:
| str           | interpreted                                   |
| ------------- | --------------------------------------------- |
| 1 months ago  | Sat, 3 Aug 2024 15:46:52 +0200 (a month ago)  |
| 2 months ago  | Wed, 3 Jul 2024 14:46:52 +0200 (2 months ago) |
| 3 months ago  | Mon, 3 Jun 2024 14:46:52 +0200 (3 months ago) |
| 4 months ago  | Sun, 4 May 2025 14:46:52 +0200 (in 8 months)  |
| 5 months ago  | Thu, 3 Apr 2025 14:46:52 +0200 (in 7 months)  |
| 6 months ago  | Wed, 5 Mar 2025 13:46:52 +0100 (in 6 months)  |
| 7 months ago  | Sun, 2 Feb 2025 14:46:52 +0100 (in 5 months)  |
| 8 months ago  | Fri, 3 Jan 2025 14:46:52 +0100 (in 4 months)  |
| 9 months ago  | Tue, 3 Dec 2024 14:46:52 +0100 (in 3 months)  |
| 10 months ago | Sun, 3 Nov 2024 14:46:52 +0100 (in 2 months)  |
| 11 months ago | Thu, 3 Oct 2024 15:46:52 +0200 (in a month)   |
| 12 months ago | Mon, 2 Sep 2024 15:46:52 +0200 (now)          |
| 13 months ago | Sat, 3 Aug 2024 15:46:52 +0200 (a month ago)  |
| 14 months ago | Wed, 3 Jul 2024 14:46:52 +0200 (2 months ago) |
| 15 months ago | Mon, 3 Jun 2024 14:46:52 +0200 (3 months ago) |
| 16 months ago | Sun, 4 May 2025 14:46:52 +0200 (in 8 months)  |
| 17 months ago | Thu, 3 Apr 2025 14:46:52 +0200 (in 7 months)  |
| 18 months ago | Wed, 5 Mar 2025 13:46:52 +0100 (in 6 months)  |
| 19 months ago | Sun, 2 Feb 2025 14:46:52 +0100 (in 5 months)  |
| 20 months ago | Fri, 3 Jan 2025 14:46:52 +0100 (in 4 months)  |
| 21 months ago | Tue, 3 Dec 2024 14:46:52 +0100 (in 3 months)  |
| 22 months ago | Sun, 3 Nov 2024 14:46:52 +0100 (in 2 months)  |
| 23 months ago | Thu, 3 Oct 2024 15:46:52 +0200 (in a month)   |
| 24 months ago | Mon, 2 Sep 2024 15:46:52 +0200 (now)          |

### Expected behavior

Get the valid date (in the past).

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.97.1                                   |
| major              | 0                                        |
| minor              | 97                                       |
| patch              | 1                                        |
| branch             |                                          |
| commit_hash        | 60769ac1ba3ea036d889f140095d855e5597840c |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29)      |
| rust_channel       | 1.78.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.78.0 (54d8815d0 2024-03-26)      |
| build_time         | 2024-08-21 03:34:17 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I've answered this before. This is a dupe. It's just how the underlying crate works.

**Comment by sholderbach** [comment]
> I've answered this before. This is a dupe. It's just how the underlying crate works.

Do you have a link to that? We should not be reliant on crates with confusing semantics.

**Comment by sholderbach** [comment]
Let's give ourselves a time limit for the fix, after that I am gonna put the dependent feature up for removal.

**Comment by salo-dea** [comment]
I had a quick check with human-date-parser, in the latest state of their main it is fixed by this PR: https://github.com/technologicalMayhem/human-date-parser/pull/9

There's just no new tag yet..
I don't have so much experience with open source things - would it be appropriate to poke them to potentially tag a new version?

**Comment by fdncred** [comment]
> I had a quick check with human-date-parser, in the latest state of their main it is fixed by this PR: https://github.com/technologicalMayhem/human-date-parser/pull/9

Good because I'm not going to support removing this feature. Hopefully they're publish a new crate soon.

> would it be appropriate to poke them to potentially tag a new version?

I pinged them in the PR you mentioned. Thanks for researching it.

**Comment by salo-dea** [comment]
Seems they already published a new version, just didn't respond on that PR https://crates.io/crates/human-date-parser/0.2.0
Had a quick local check with that and the behaviour seems to be fixed

**Comment by fdncred** [comment]
Thanks for the heads-up @salo-dea. I missed that. Just submitted https://github.com/nushell/nushell/pull/13962 for this.
