### ISSUE TITLE
Using an alias for an external command defined in a module messes up arguments

### ISSUE THREAD

**Issue by nome** [nushell/nushell#13776]
### Describe the bug

When invoking an alias for an external command with `mymodule myalias`, the alias name becomes part of the external command's arguments. This means the command arguments passed depend on the way the alias is imported, which is highly surprising.

### How to reproduce

```
~> module m1 { export alias a1 = /bin/sh -c "echo $*" -- }
~> use m1
~> m1 a1 b c d
a1 b c d
```

Note the extra `a1` argument passed to `/bin/sh`. This doesn't happen when importing the alias directly:

```
~> use m1 a1
~> a1 b c d
b c d
```

Nor does this happen with builtin commands:

```
~> module m2 { export alias a2 = print -n }
~> use m2
~> m2 a2 b c d
bcd
```

### Expected behavior

I expected aliases to external commands to behave the same way as aliases to internal commands, i.e.:

```
~> module m1 { export alias a1 = /bin/sh -c "echo $*" -- }
~> use m1
~> m1 a1 b c d
b c d
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.97.1                                   |
| major              | 0                                        |
| minor              | 97                                       |
| patch              | 1                                        |
| branch             |                                          |
| commit_hash        |                                          |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)      |
| build_time         | 2024-08-31 19:06:16 +02:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  |                                          |

**Comment by hardfau1t** [comment]
another similar issue, might be same, If alias is done for external command it adds command name at the end
```nu
module this {
    export alias ll = eza -l 
}
```
If i run `ll` this outputs `eza -l ll`
IR for this looks like this 
```
# 4 registers, 10 instructions, 7 bytes of data
   0: load-literal           %1, glob-pattern("eza", no_expand = false)
   1: load-literal           %2, glob-pattern("-l", no_expand = false)
   2: load-literal           %3, glob-pattern("ll", no_expand = false)
   3: push-positional        %1
   4: push-positional        %2
   5: push-positional        %3
   6: redirect-out           caller
   7: redirect-err           caller
   8: call                   decl 131 "run-external", %0
   9: return                 %0
   ```
   Interestingly this doesn't happen for builting commands
   ```
module this {
    export alias ll = ls -l 
}```

This ouputs corrects and IR of this looks like below
```
# 1 register, 5 instructions, 4 bytes of data
   0: push-flag              "long"
   1: redirect-out           caller
   2: redirect-err           caller
   3: call                   decl 201 "ls", %0
   4: return                 %0
   ```
