### ISSUE TITLE
`find` breaks date column in tables

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#13789]
### Describe the bug

I used `find` on an `ls` table, which includes the `modified` datetime column.  `find` overwrote the column with plus signs.  I presume it's happening because dates get converted to string for `find` (and there's a plus in the format for the time zone).  But it shouldn't remove the whole date.

### How to reproduce

```Nushell
~> ls /bin/ | find +
────┬────────────────────┬─────────┬──────────┬──────────
  # │        name        │  type   │   size   │ modified 
────┼────────────────────┼─────────┼──────────┼──────────
  0 │ /bin/umount        │ symlink │     11 B │ +        
  1 │ /bin/su            │ symlink │     11 B │ +        
  2 │ /bin/date          │ symlink │     12 B │ +        
```

### Expected behavior

I think `find` should either not search the datetime column, keep them as dates, or return the full string representation of the date.

### Configuration

| key                | value                                                        |
| ------------------ | ------------------------------------------------------------ |
| version            | 0.97.1                                                       |
| major              | 0                                                            |
| minor              | 97                                                           |
| patch              | 1                                                            |
| branch             |                                                              |
| commit_hash        |                                                              |
| build_os           | linux-x86_64                                                 |
| build_target       | x86_64-alpine-linux-musl                                     |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06) (Alpine Linux 1.80.1-r0) |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)                          |
| build_time         | 2024-08-29 21:40:07 +00:00                                   |
| build_rust_channel | release                                                      |
| allocator          | mimalloc                                                     |
| features           | default, sqlite, system-clipboard, trash                     |
| installed_plugins  | endecode 0.2.0, template 0.1.0                               |

**Comment by fdncred** [comment]
It is expected that `find` searches the modified column's data vs what nushell presents. It is not expected that it eats the date. Since plus is an operator, I wonder if it's getting confused. What happens with `"+"`?

No issues with minus
![image](https://github.com/user-attachments/assets/3cb53ffa-6537-4c9f-96a0-cdf516ec95db)

**Comment by KAAtheWiseGit** [comment]
`"+"` yields the same results.  Searching for other parts of the date returns the full textual representation:

```Nushell
~> ls /bin/ | find month
────┬─────────────────┬─────────┬──────────┬────────────────────────────────────────────────
  # │      name       │  type   │   size   │                    modified                    
────┼─────────────────┼─────────┼──────────┼────────────────────────────────────────────────
  0 │ /bin/date       │ symlink │     12 B │ Wed, 20 Mar 2024 20:31:52 +0300 (5 months ago) 
  1 │ /bin/udevadm    │ file    │ 215.3 KB │ Tue, 26 Mar 2024 01:59:03 +0300 (5 months ago) 
  2 │ /bin/cp         │ symlink │     12 B │ Wed, 20 Mar 2024 20:31:52 +0300 (5 months ago) 
...
~> ls /bin/ | find :
────┬────────────────────┬─────────┬──────────┬────────────────────────────────────────────────
  # │        name        │  type   │   size   │                    modified                    
────┼────────────────────┼─────────┼──────────┼────────────────────────────────────────────────
  0 │ /bin/umount        │ symlink │     11 B │ Thu, 5 Sep 2024 16:14:08 +0300 (3 hours ago)   
  1 │ /bin/su            │ symlink │     11 B │ Thu, 5 Sep 2024 16:14:08 +0300 (3 hours ago)   
  2 │ /bin/date          │ symlink │     12 B │ Wed, 20 Mar 2024 20:31:52 +0300 (5 months ago) 
...
```

**Comment by weirdan** [comment]
It's not specific to dates either:

```console
$ [[d]; ["a+b"] ] | find +
╭───┬───╮
│ # │ d │
├───┼───┤
│ 0 │ + │
╰───┴───╯
```

**Comment by fdncred** [comment]
Looks like a bug somewhere. As a work-around you could do this.
```nushell
[[d]; ["a+b"] ] | find -r '\+'
╭─#─┬──d──╮
│ 0 │ a+b │
╰───┴─────╯
```

**Comment by weirdan** [comment]
It's likely we need to escape the `needle` before putting it into regex here:

https://github.com/nushell/nushell/blob/4d2d553cca5abd3f6c204c20c1eca0f1df094924/crates/nu-command/src/help/help_.rs#L196

See https://docs.rs/fancy-regex/latest/fancy_regex/fn.escape.html

**Comment by NotTheDr01ds** [comment]
Hmm - I guess everyone is either running an older config file, they've set the `datetime_format` manually, or perhaps there's a mismatch between internal-Rust-and config again, because my default with no config is simply "humanized".

That said, I also get the problem on `ls /bin/ | find +`, but on *filenames* rather than dates:

```nu
ls /bin/ | find -r '\+'

# =>
╭───┬───────────────────────────────┬─────────┬───────────┬─────────────╮
│ # │             name              │  type   │   size    │  modified   │
├───┼───────────────────────────────┼─────────┼───────────┼─────────────┤
│ 0 │ /bin/g++                      │ symlink │       6 B │ 3 years ago │
│ 1 │ /bin/c++                      │ symlink │      21 B │ a year ago  │
│ 2 │ /bin/g++-11                   │ symlink │      23 B │ a year ago  │
│ 3 │ /bin/x86_64-linux-gnu-c++filt │ file    │  22.3 KiB │ a year ago  │
│ 4 │ /bin/x86_64-linux-gnu-g++     │ symlink │       6 B │ 3 years ago │
│ 5 │ /bin/x86_64-linux-gnu-g++-11  │ file    │ 910.8 KiB │ a year ago  │
│ 6 │ /bin/c++filt                  │ symlink │      24 B │ a year ago  │
╰───┴───────────────────────────────┴─────────┴───────────┴─────────────╯

ls /bin/ | find +

# =>
╭───┬──────┬─────────┬───────────┬─────────────╮
│ # │ name │  type   │   size    │  modified   │
├───┼──────┼─────────┼───────────┼─────────────┤
│ 0 │ +    │ symlink │       6 B │ 3 years ago │
│ 1 │ +    │ symlink │      21 B │ a year ago  │
│ 2 │ +    │ symlink │      23 B │ a year ago  │
│ 3 │ +    │ file    │  22.3 KiB │ a year ago  │
│ 4 │ +    │ symlink │       6 B │ 3 years ago │
│ 5 │ +    │ file    │ 910.8 KiB │ a year ago  │
│ 6 │ +    │ symlink │      24 B │ a year ago  │
╰───┴──────┴─────────┴───────────┴─────────────╯
```

**Comment by fdncred** [comment]
@NotTheDr01ds you can try `ls | find month` you should see how nushell transforms the date for you.

**Comment by weirdan** [comment]
> It's not specific to dates either:

To expand on this, any regex special characters (as long as they form a valid regex syntax) break `find` highlighting. Examples are `{1}`, `[]`, `?`, `+`, `*` and so on.

**Comment by fdncred** [comment]
Thanks for the tip @weirdan. https://github.com/nushell/nushell/pull/13792
