### ISSUE TITLE
Why i get config error when i use the oh my posh?

### ISSUE THREAD

**Issue by arsalanmohseni** [nushell/nushell#13790]
### Question

Hi
Im using nushell as my default shell and oh my posh
When i create a oh my posh config with robbyrussel theme, its show me config error but it doesn't show on other themes
How do i fix it??
An how to make it automattically to run:
```bash
source ~/.oh-my-posh.nu
```

### Additional context and details

Here an image of my error:
![temp](https://github.com/user-attachments/assets/8e38306a-771d-4b44-a635-eba10229a40d)
And its not be the theme i choosed

**Comment by fdncred** [comment]
Seems like a question for the oh-my-posh folks. You should be able to follow [their documentation](https://ohmyposh.dev/docs/installation/prompt) without issue. I assume that "CONFIG ERROR" means there is an on-my-posh config file that has invalid syntax.

**Comment by weirdan** [comment]
Does it also happen if you run
```
oh-my-posh print primary --config /path/to/robbyrussel/theme/file.omp.json
```
?

**Comment by arsalanmohseni** [comment]
> Seems like a question for the oh-my-posh folks. You should be able to follow [their documentation](https://ohmyposh.dev/docs/installation/prompt) without issue. I assume that "CONFIG ERROR" means there is an on-my-posh config file that has invalid syntax.
I go step by step with docs

**Comment by arsalanmohseni** [comment]
> Does it also happen if you run
> 
> ```
> oh-my-posh print primary --config /path/to/robbyrussel/theme/file.omp.json
> ```
> 
> ?

No, its when i use:
```bash
oh-my-posh init nu --config ~/robbyrussell.omp.json
```

**Comment by weirdan** [comment]
```
oh-my-posh print primary --config /path/to/robbyrussel/theme/file.omp.json
```

running this (of course you would need to adjust the path to the config) would help you diagnose the problem. If it still produces `Config error` then the problem is clearly on OMP side (either with OMP itself or that config file), and has nothing to do with nushell.

**Comment by arsalanmohseni** [comment]
I found that if you want to use oh my posh with nu shell you need to download your theme file from github and save it to your fav path
Example:

```bash
oh-my-posh init nu --config path/to/your/theme/file/yourthemefilename.omp.json
```
