### ISSUE TITLE
match arm leaking scope

### ISSUE THREAD

**Issue by suimong** [nushell/nushell#13804]
### Describe the bug

Environment variables set in a match arm will leak to the outer scope. This is not exactly a bug, though at first glance this looks like an exception to nushell's otherwise very strict scoping rules. I wonder if this semantic is intended.

### How to reproduce

![image](https://github.com/user-attachments/assets/1a25f543-bfa7-4228-8bf7-94dddf99e3dd)

### Expected behavior

Either:

1. keep things the way it is, i.e. match arm not "scoped", but document this behavior somewhere.
2. make match arm scoped, but add a `--env` flag to `match` (similar to `def`)

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.97.1                                                            |
| major              | 0                                                                 |
| minor              | 97                                                                |
| patch              | 1                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06) (built from a source tarball) |
| cargo_version      | cargo 1.80.0 (376290515 2024-07-16)                               |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, system-clipboard, trash                          |
| installed_plugins  | formats 0.95.0                                                    |

**Comment by WindSoilder** [comment]
I think it works as intended, match arms is something like `if`, which also changes env inside the block

**Comment by suimong** [comment]
Ah right. Just found out about the Tips section in https://www.nushell.sh/book/control_flow.html. Thanks for clarifying.
