### ISSUE TITLE
Panic when using `detect columns --guess`

### ISSUE THREAD

**Issue by Schweber** [nushell/nushell#13820]
### Describe the bug

This panics:
```
"UUID:             50f8081c-9846-4bb5-af9a-b31a5d8fd947                                                                                  
 	no stats available
 Total to scrub:   11.34GiB
 Rate:             0.00B/s
 Error summary:    no errors found" | detect columns --guess | print

Error:   × Main thread panicked.
  ├─▶ at crates/nu-command/src/strings/guess_width.rs:209:83
  ╰─▶ index out of bounds: the len is 19 but the index is 19
  help: set the `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

### How to reproduce

See above

### Expected behavior

Show a table with the input. At least not panic.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.97.1                                                            |
| major              | 0                                                                 |
| minor              | 97                                                                |
| patch              | 1                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06) (built from a source tarball) |
| cargo_version      | cargo 1.80.0 (376290515 2024-07-16)                               |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, system-clipboard, trash                          |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
I wonder if this is the panic that @WindSoilder just recently fixed? Can you try on the main branch 0.97.2?
