### ISSUE TITLE
What should be the mime type for nushell scripts?

### ISSUE THREAD

**Issue by cptpiepmatz** [nushell/nushell#13858]
### Question

Recently in the discord server I saw a discussion about what nushell scripts' mime type would be. [This PR](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/merge_requests/231) used `application/x-nuscript` and `text/x-nu` as an alias. What are the mime types that should be officially recognized? In my jupyter kernel a mime type for the language is also expected. So having one that is endorsed would be great.

**Comment by fdncred** [comment]
I'm fine with both of those. They seem reasonable to me. Not sure what others think.

**Comment by cptpiepmatz** [comment]
Having them properly documented would be great.

**Comment by cptpiepmatz** [comment]
This was discussed in the [meeting from the 18th of september](https://hackmd.io/@nucore/H1bgUtLaC) and I opened a [PR](https://github.com/nushell/nushell.github.io/pull/1556) to add the docs

**Comment by fdncred** [comment]
landed that pr so I'm closing this. i wonder if we need to do a PR to freedesktop.org since they are different now?
