### ISSUE TITLE
Rename not accepting variables. 

### ISSUE THREAD

**Issue by hydrosIII** [nushell/nushell#13854]
### Describe the bug

I am trying to rename a table with a variable. 
  This variable was taken from the table itself, as doing some transformations the names were lost. So, I tried to pass them in a string variable. However it is not possible because nushell interprets as if the string was between " "

I put here a minimal working example. 

### How to reproduce

Minimal working Example:

If you pass a string to a table to try to rename me. The rename, renames just the first cell with all the string. 
```nushell
let table_example= [[a b]; [1 2]] 
let new_names = new_name1 new_name2
$table_example |  rename $"($new_name)"
```

![image](https://github.com/user-attachments/assets/046ba958-e141-4d1a-a7bb-f49b77c102bd)

```nushell
let table_example= [[a b]; [1 2]] 
let new_names = new_name1 new_name2
$table_example |  rename  new_name1 new_name2
```
![image](https://github.com/user-attachments/assets/d1e79025-6406-4fd6-95bc-310d1c024d6f)

So it seems that there is not a way to unquote the string variable. I have tried different sintax to expand the variable but nothing has worked. Here in the minimal working example is very clear because the string has to be created using quotes. But in the example that i am using it comes from a series of pipes. 

### Expected behavior

Be able to unquote the string when it is passed as a variable. So that it is recognized as a series of words separated by spaces. 

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.96.1                                   |
| major              | 0                                        |
| minor              | 96                                       |
| patch              | 1                                        |
| branch             |                                          |
| commit_hash        |                                          |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)      |
| build_time         | 2024-08-19 11:27:05 +02:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  | formats 0.96.1                           |

**Comment by fdncred** [comment]
Have you tried this? It works on the latest main branch.
```nushell
let table_example = [[a b]; [1 2]]
let new_names = [new_name1 new_name2]
$table_example | rename ...$new_names
╭─#─┬─new_name1─┬─new_name2─╮
│ 0 │         1 │         2 │
╰───┴───────────┴───────────╯
```

**Comment by NotTheDr01ds** [comment]
I think your example might need some rework - It's not valid, and even after fixing it, it doesn't return the result you show.  I think you may have a previously declared variable that is throwing things off.

```nu
let table_example = [[a b]; [1 2]] 
let new_names = new_name1 new_name2
$table_example |  rename $"($new_names)"

# =>
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #1:2:17]
 1 │ let table_example = [[a b]; [1 2]]
 2 │ let new_names = new_name1 new_name2
   ·                 ────┬────
   ·                     ╰── Command `new_name1` not found
 3 │ $table_example |  rename $"($new_names)"
   ╰────
  help: Did you mean `rename`?

```

The issue there is that `new_name1` is a bare-word in the "command position" - the first part of the expression.  In 0.96.1, that was interpreted as an external.

In 0.97.1, that's just not allowed at all.

At best, what you seem to be hoping for is two bareword strings, which still wouldn't be assignable to a variable unless, as @fdncred pointed out, it was in a list.

> This variable was taken from the table itself

To get the result you show in the screenshot, here's what you are probably doing:

```nu
let table_example = [[a b]; [1 2]] 
let new_names = "new_name1 new_name2"
$table_example |  rename $"($new_names)"

# =>
╭───┬─────────────────────┬───╮
│ # │ new_name1 new_name2 │ b │
├───┼─────────────────────┼───┤
│ 0 │                   1 │ 2 │
╰───┴─────────────────────┴───╯
```

If so, then your solution may be:

```nu
let table_example = [[a b]; [1 2]] 
let new_names = "new_name1 new_name2" | split row ' '
$table_example |  rename ...$new_names

# =>
╭───┬───────────┬───────────╮
│ # │ new_name1 │ new_name2 │
├───┼───────────┼───────────┤
│ 0 │         1 │         2 │
╰───┴───────────┴───────────╯
```

**Comment by hydrosIII** [comment]
@NotTheDr01ds  You are right my example is wrong. Sorry I think I wrote it instead of copying it. 
```

let table_example = [[a b]; [1 2]]
let new_names = "new_name1 new_name2" 
$table_example |  rename $"($new_names)"      
```

**Comment by hydrosIII** [comment]
I am having a similar issue now with find. I will open another bug for this.

**Comment by NotTheDr01ds** [comment]
No worries. Does my example do what you need?

**Comment by hydrosIII** [comment]
Yes. In fact it serves for other purposes as well. I had the same issue with find to find names in a table and now it works.

**Comment by hydrosIII** [comment]
Is had some troubles with names with space in them. But that is another history, doing regex from space to _ solves it.
