### ISSUE TITLE
Is there a way to disable multi-dot path expansion?

### ISSUE THREAD

**Issue by luchev** [nushell/nushell#13866]
### Question

Is it possible to prevent nu from treating `'...'` as `'../..'`?
This could be useful when using for example `bazel test ...`

**Comment by fdncred** [comment]
if you quote it like `bazel test "..."` i think it won't expand.

**Comment by luchev** [comment]
Yes, that works. I should have phrased my question better.
Is there a flag in the settings that would disable the path expansion?

**Comment by fdncred** [comment]
not at the moment. based on our last team meeting we are thinking about special casing `./...` for go but if bazel uses something different it won't help.

**Comment by luchev** [comment]
Bazel was just an example I stumbled upon. I don't think adding special cases for one CLI tool is ideal, as one can argue why was one tool treated differently from others. So that was why my question about Bazel was if a config option exists - it's the first thing that came to mind that seemed generic enough to be already added to nu. In some zsh plugins multiple dots expansion is handled with aliases, which is not as elegant as nu, but can be overwritten.
Thank you for the discussion. My question has been answered :)

**Comment by fdncred** [comment]
There are really only a few options. We discussed this in the meeting last Wednesday. These were the viable options.

- remove ndots entirely
- leave what we have now
- special case ./... <– leaning toward this option
- use extern, works but is kind of a pain since every command you use would have to be declared as an extern

**Comment by luchev** [comment]
I see. I don't have enough context and knowledge on how ndots are being used to give a valuable suggestion. Personally I do not use them outside `cd`, so I don't know the use cases with other commands.
