### ISSUE TITLE
`do --ignore-program-errors` doesn't wait for the last command to finish

### ISSUE THREAD

**Issue by aionescu** [nushell/nushell#13876]
### Describe the bug

When running a `do --ignore-program-errors { ... }` block, the `do` exits without waiting for the last command in the closure to finish.

This only seems to occur if the last command in the closure is an external command.
It also doesn't occur with regular `do`, `do --ignore-shell-errors`, nor `try`.

I've observed the issue in versions `0.97.1` and `0.98.0`.

### How to reproduce

Run the following function:

```nu
def f [] {
  do -p { ^sleep 1 }
  print Foo
}
```

When calling `f` at the REPL, it immediately prints `Foo`, then waits for 1 second.

### Expected behavior

I expected `f` to only print Foo _after_ sleeping for 1 second.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.98.0                                                           |
| major              | 0                                                                |
| minor              | 98                                                               |
| patch              | 0                                                                |
| branch             | makepkg                                                          |
| commit_hash        | 6e1e824473e15eba246e1c43704c5d88fa237a17                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04) (Arch Linux rust 1:1.81.0-1) |
| cargo_version      | cargo 1.81.0 (2dbb1af80 2024-08-20)                              |
| build_time         | 2024-09-18 13:20:08 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | default, sqlite, trash                                           |
| installed_plugins  |                                                                  |

**Comment by NotTheDr01ds** [comment]
Copying my findings from our Discord chat in here as well:

```nu
def f [] {
  print 'One'
  do -p {
    print 'Two'
    ^sleep 4
    if false { print 'Three' }
  }
  print 'Four'
}
```

As @aionescu mentioned, simple having a separate command at the end of the closure, even if it is a no-op, prevents the issue from happening.  In this case, the `^sleep` occurs at the appropriate place.

Comment `if` statement out, and the `^sleep` takes place concurrently or after the entire command has finished - Not sure which yet.
