### ISSUE TITLE
Nushell 0.98 errors on non-nushell binaries

### ISSUE THREAD

**Issue by Bryntet** [nushell/nushell#13871]
### Describe the bug

Just updated to 0.98.0-1 on my system running Arch (so it might be a distro-specific issue).

Running any binary gives the following error message `Error: nu::shell::non_zero_exit_code`.

### How to reproduce

1. Be on 0.98.0-1 on arch
2. Run the following in any shell (i have tested it is not a terminal specific issue, by running in TTY)
```
~> test                                                      2024-09-19 10:10:42
Error: nu::shell::non_zero_exit_code

  × External command had a non-zero exit code
   ╭─[entry #1:1:1]
 1 │ test
   · ──┬─
   ·   ╰── exited with code 1
   ╰────
```

### Expected behavior

Not error.

### Configuration

~> version | transpose key value | to md --pretty          1 2024-09-19 10:10:41
| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.97.1                                                           |
| major              | 0                                                                |
| minor              | 97                                                               |
| patch              | 1                                                                |
| branch             | makepkg                                                          |
| commit_hash        | 60769ac1ba3ea036d889f140095d855e5597840c                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06) (Arch Linux rust 1:1.80.1-1) |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)                              |
| build_time         | 2024-08-21 12:14:01 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | default, sqlite, system-clipboard, trash                         |
| installed_plugins  |                                                                  |

**Comment by WindSoilder** [comment]
Thanks for the report!  It's a new feature, you can refer here for more information: https://www.nushell.sh/blog/2024-09-17-nushell_0_98_0.html#non-zero-exit-codes-are-now-errors-toc

And you can config it to disable such error message:
```nushell
config = {
    display_errors: { exit_code: false }
}
```

**Comment by Bryntet** [comment]
Oh, sorry about that! It would've been nice if for the first time you experienced it/launched after the update it would notify about this, but I know that such things can be difficult to implement nicely. Thanks for the quick response!

**Comment by rukai** [comment]
I hit the same issue and the display_errors config fixed the issue for me.

However I think exit_code really ought to be true by default?
I cant imagine a REPL user wanting such a verbose error every time a command gives a non-zero exit code, since this very rarely actually conveys anything to the user.
Most commands are designed to give useful error output to stdout or stderr, so nushell providing 8 lines of output just to say the exit code is a bit redundant.

I guess a counter argument is when you start getting into complex piped commands, the error could be useful in showing which command gave the error.
Maybe the error should only activate when a pipe or other more complex command is invoked?
