### ISSUE TITLE
cd can't change into directories containing "."

### ISSUE THREAD

**Issue by notryanb** [nushell/nushell#1387]
**Describe the bug**
Trying to `cd` into a directory containing a period causes "expected argument"

**To Reproduce**
1. Outside of nu, `mkdir netstandard2.1` (there looks to also be a bug with `mkdir`)
2.  start `nu` and navigate to the directory containing the `netstandard2.1` directory
3. `cd netstandard2.1`

**Expected behavior**
I expect to be able to `cd` into any directory with a valid naming convention for a supported OS.

**Configuration (please complete the following information):**
 - OS: Windows
 - 0.9.0+

**Other**
I realize putting quotes around the directory works (for `mkdir` as well). Powershell does not require the user to do this. I have not tried on linux/MacOS yet.

**Comment by jonathandturner** [comment]
Fixed in latest master.
