### ISSUE TITLE
keybindings to non-alphanumeric characters with modifiers doesn't work

### ISSUE THREAD

**Issue by suimong** [nushell/nushell#13888]
### Describe the bug

The following keybinding does not execute:

```nushell
    {
      name: wrap_buffer_with_quote
      modifier: control
      keycode: "char_'"
      mode: [emacs vi_normal vi_insert]
      event: {
        send: executehostcommand,
        cmd: r#'
          commandline edit --append '"'
          commandline set-cursor 0
          commandline edit --insert '"'
          commandline set-cursor -e
        '#
      }
    }
```
 I tried it without modifier (ala #8977) and it works fine. But with a modifier (i tried `control`, `alt`, `control_alt`, `shift`), quite a few of the keycodes (i tried `char_[`, `char_'`, `char_"`, `char_;`) doesn't work.

### How to reproduce

1. Added the above code to keybindings in `config.nu`
2. press `<c-'>`

### Expected behavior

execute the cmd regularly.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.97.1                                                            |
| major              | 0                                                                 |
| minor              | 97                                                                |
| patch              | 1                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06) (built from a source tarball) |
| cargo_version      | cargo 1.80.0 (376290515 2024-07-16)                               |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, system-clipboard, trash                          |
| installed_plugins  |                                                                   |

**Comment by weirdan** [comment]
What does `input listen` report when you press that key combination?

**Comment by suimong** [comment]
Here are the outputs of `input listen --type [key]` when pressing different key combinations:
- `ctrl_'`: 
```
╭───────────┬────────────────╮
│ type      │ key            │
│ key_type  │ char           │
│ code      │ '              │
│ modifiers │ [list 0 items] │
╰───────────┴────────────────╯
```
- `ctrl_[`:
```
╭───────────┬────────────────╮
│ type      │ key            │
│ key_type  │ other          │
│ code      │ esc            │
│ modifiers │ [list 0 items] │
╰───────────┴────────────────╯

```
- `ctrl_a`:
```
╭───────────┬───────────────────────────────╮
│ type      │ key                           │
│ key_type  │ char                          │
│ code      │ a                             │
│           │ ╭───┬───────────────────────╮ │
│ modifiers │ │ 0 │ keymodifiers(control) │ │
│           │ ╰───┴───────────────────────╯ │
╰───────────┴───────────────────────────────╯

```

The results are quite baffling... I use a regular laptop keyboard with no special setup...

**Comment by weirdan** [comment]
My knowledge of terminals is quite superficial, but from what I understand there are many variables that may affect your experience:

* your terminal emulator
* `$TERM` variable settings (`$env.TERM`)
* whether or not your terminal supports kitty keyboard protocol
* whether or not you have enabled it in nushell (`$env.config.use_kitty_protocol`)
* what keybinding does your terminal emulator interpret on its own (e.g. there are quite a few keyboard shortcuts that Wezterm claims as its own).

> I use a regular laptop keyboard with no special setup...

Terminals are as much a mess as human languages. It's like saying "I'm a regular guy with a regular mouth, why doesn't that other guy understand me?" :grin:

**Comment by weirdan** [comment]
Also it doesn't seem nushell properly enables kitty protocol:

```console
$ input listen -r
╭───────────────┬────────────────╮
│ type          │ key            │
│ key_type      │ char           │
│ code          │ '              │
│ modifiers     │ [list 0 items] │
│ raw_code      │ 39             │
│ raw_modifiers │ 0              │
╰───────────────┴────────────────╯
$ print "\e[>1u" # enables 'Disambiguate escape codes' mode
                                                                                                                                  $ input listen -r
╭───────────────┬───────────────────────────────╮
│ type          │ key                           │
│ key_type      │ char                          │
│ code          │ '                             │
│               │ ╭───┬───────────────────────╮ │
│ modifiers     │ │ 0 │ keymodifiers(control) │ │
│               │ ╰───┴───────────────────────╯ │
│ raw_code      │ 39                            │
│ raw_modifiers │ 2                             │
╰───────────────┴───────────────────────────────╯
$ $env.config.use_kitty_protocol # even though it should have been enabled from the start
true
```

**Comment by suimong** [comment]
> Terminals are as much a mess as human languages. It's like saying "I'm a regular guy with a regular mouth, why doesn't that other guy understand me?" 😁

Ah, I wasn't even thinking in the direction of terminal emulator...Partly because I first discovered this in VSCode's terminal emulator, then I tried in Alacritty, then GNOME Terminal, with identical results. 

> whether or not you have enabled it in nushell ($env.config.use_kitty_protocol)

I was not aware of that config entry. However it does not seem to make a difference after enabling it (the key pressed for `input listen` is `ctrl_[`:

![image](https://github.com/user-attachments/assets/318de592-b079-473c-8396-5a6c2a3650be)

Anyway, this doesn't seem like a nushell bug, and I just discovered that `alt+'` works😁. So closing.

@weirdan Thanks for the help!

**Comment by weirdan** [comment]
I did a little digging, and this is what I found:

> VSCode's terminal emulator, then I tried in Alacritty, then GNOME Terminal, with identical results.

VSCode (xterm.js) and GNOME Terminal (libvte) do not support kitty protocol at all. Alacritty looks like it does, but the configuration switch to enable it is not documented anywhere: https://github.com/alacritty/alacritty/blob/master/alacritty_terminal/src/term/mod.rs#L350

There are two similar commands in nushell: `input listen` and `keybindings listen`. The former ignores `$env.config.use_kitty_protocol`, while the latter respects this config value, so it's better to use `keybindings listen` to debug keyboard shortcuts.

Nushell (reedline actually) enables and disables kitty protocol for every command prompt (https://github.com/nushell/reedline/blob/d8b240ade899f95b22d49a4cec995f5e19bafca8/src/engine.rs#L644-L649), probably to make sure it doesn't stay enabled when any external program is started. That's why `$env.config.use_kitty_protocol` didn't automatically affect `input listen`.

**Comment by suimong** [comment]
Cool! A question I should ask earlier, are `ctrl-[`, `ctrl-'` not valid key combinations in non-kitty-protocol-enabled terminals? In other words, in order to support the above two key combos, is it necessary to have a kitty-keyboard-compatible terminal AND have config.use_kitty_protocol set to true in Nushell?

**Comment by weirdan** [comment]
From what I understand, without kitty protocol being enabled what terminals do more or less resembles what's documented as legacy encoding here (of course there will also be terminal-specific quirks, and probably a number of competing ways to do the same): https://sw.kovidgoyal.net/kitty/keyboard-protocol/#legacy-key-event-encoding. If you follow the algorithm you'll see that `Ctrl+'` sends the same data as `'`.

So yes, to make sure nushell can use those shortcuts you need both to have a capable terminal *and* enable it on both sides (in terminal and nushell, because nushell needs to opt-in into using kitty protocol).

**Comment by suimong** [comment]
I skimmed through that page but it's too much information for me at this time of day, and probably easier just to use a kitty compatible terminal and call it a day. Much appreciate all the advice and digging!
