### ISSUE TITLE
Add basic vector operations to `math`

### ISSUE THREAD

**Issue by YPares** [nushell/nushell#13889]
### Related problem

It would be useful to have some operations that treat lists of numbers as vectors (in the "vector space" sense) and compute dot products, cosines and sines between them. Assuming of course a classical euclidean metric, ie. `norm(v) = sqrt(v.x² + v.y² + v.z² + ...)`.

### Describe the solution you'd like

- `$list | math sqnorm` # Return the squared norm of a list (treated as a vector)
- `$list1 | math dot $list2` # Return the dot product between two vectors. Importantly `$a | math sqnorm` should always be equal to `$a | math dot $a`
- `$list1 math vcos | $list2` # Return the cosine of the angle between two vectors
- `$list1 math vsin | $list2` # Return the sine of the angle between two vectors

I'm proposing separated `vcos` and `vsin` instead of a general `vangle` returning directly an angle in radians, because the sin and cos are often not needed together (e.g. treating cosine alone as a measure of "similarity" is a very common thing to do) and cos and sin by themselves are simpler to compute.

### Describe alternatives you've considered

Writing custom functions. But these are really the first things you need when using lists as vectors, and a lot of applications need no more than that (notably do not need a full set of linear algebra primitives, matrices and all).

### Additional context and details

Applications: assessing "similarity" between rows or columns of a table. I'm working on a simple "vectorize" plugin which would do that, with simple algorithms like TF/IDF, which would return for each column of a table a vector representation.

**Comment by sholderbach** [comment]
As I have already been the party-pooper on the #14015 PR implementation attempt.

In the current state, adding this to the core language doesn't have the support of the core team. We have to limit what we ship with Nushell to the things that have a broad userbase/list of possible uses, and have strong downsides if they were not part of the single Nushell binary. Here the functionality can easily be provided by a plugin for the users that have more math needs.
Our builtin-`list` type itself isn't strongly optimized for dense math of typical linear-algebra libraries. So this would seem like a mismatch to ship optimizations for some ops (similarities/distances) while the core datatype is not lending itself towards that.

We will be happy to see that first as a plugin, we can always decide later that we have a more complete linalg story that could be either bundled up as a larger plugin or receive support in the language core.

Right now we need to keep our core slim to more efficiently perfect the core of the type system, language, and engine so we can stabilize for the eventual 1.0 release.
