### ISSUE TITLE
Allow to `reject` column with empty cells

### ISSUE THREAD

**Issue by vwkd** [nushell/nushell#13884]
### Describe the bug

Currently, `reject`ing a column errors at the first empty cell in a sparse table. I'd have to do some complicated conditional empty checks first.

This seems little useful since I want the cell gone anyway, if it's empty or not.

### How to reproduce

```nu
> [{a: 1, b: 2}, {a: 1}] | reject b
Error: nu::shell::column_not_found

  × Cannot find column 'b'
   ╭─[entry #21:1:16]
 1 │ [{a: 1, b: 2}, {a: 1}] | reject b
   ·                ───┬──           ┬
   ·                   │             ╰── cannot find column 'b'
   ·                   ╰── value originates here
   ╰────
```

### Expected behavior

```nu
> [{a: 1, b: 2}, {a: 1}] | reject b
 #   a
 0   1
 1   1
```

### Configuration

| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.98.0                                         |
| major              | 0                                              |
| minor              | 98                                             |
| patch              | 0                                              |
| branch             |                                                |
| commit_hash        |                                                |
| build_os           | macos-aarch64                                  |
| build_target       | aarch64-apple-darwin                           |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04) (Homebrew) |
| cargo_version      | cargo 1.81.0                                   |
| build_time         | 2024-09-18 07:48:46 +00:00                     |
| build_rust_channel | release                                        |
| allocator          | mimalloc                                       |
| features           | default, sqlite, trash                         |
| installed_plugins  |                                                |

**Comment by vwkd** [comment]
Oh, I overlooked the `-i, --ignore-errors - ignore missing data (make all cell path members optional)` option. The naming is a bit confusing but it's there.

**Comment by weirdan** [comment]
You could also do `| reject b?` (note the question mark).
