### ISSUE TITLE
from-json makes a mess when input object keys are unsorted

### ISSUE THREAD

**Issue by dcarosone** [nushell/nushell#1389]
**Describe the bug**
reading json input with inconsistent object key order causes nu to split into a new table each time the order changes, even though the schema for each row is the same

**To Reproduce**
1. `cargo install fselect`
2. `fselect path, size, sha1 from . where is_file==true order by sha1 into json | from-json`

Note: on master you may hit #1355 here as an additional complication. 0.9.0 from `cargo install` shows this issue.

**Expected behavior**
A single table with each field read into the correct column

**Screenshots**

output is a bunch of small tables, with the same schema but different order. Sometimes you get a few rows together, if the input data happened to be consistent from one object to the next.

```
──────┬────────────────────────────────────────────────────────────┬──────┬──────────────────────────────────────────
 #    │ Path                                                       │ Size │ Sha1 
──────┼────────────────────────────────────────────────────────────┼──────┼──────────────────────────────────────────
 3727 │ ./target/release/.fingerprint/memchr-ef0f82ba05bd7b08/lib- │ 487  │ ffdeefe4d00040f5449d2c66a2414ed778b118a9 
      │ memchr-ef0f82ba05bd7b08.json                               │      │  
──────┴────────────────────────────────────────────────────────────┴──────┴──────────────────────────────────────────
──────┬──────┬──────────────────────────────────────────┬───────────────────────────────────────────
 #    │ Size │ Sha1                                     │ Path 
──────┼──────┼──────────────────────────────────────────┼───────────────────────────────────────────
 3728 │ 78   │ fffaff20838c441ca6188a6a6e3bbf7c49dcc2ad │ ./crates/nu-test-support/src/bins/nonu.rs 
──────┴──────┴──────────────────────────────────────────┴───────────────────────────────────────────
──────┬────────────────────────────────────────────────────────────┬──────────────────────────────────────────┬────────
 #    │ Path                                                       │ Sha1                                     │ Size 
──────┼────────────────────────────────────────────────────────────┼──────────────────────────────────────────┼────────
 3729 │ ./target/release/deps/libsignal_hook-79e6f094343ef799.rlib │ fffe55532c6004c0be6c67024b551ae841e30715 │ 455322 
──────┴────────────────────────────────────────────────────────────┴──────────────────────────────────────────┴────────
```

This is because the input json (pretty-printed here) is an array of objects with consistent schema but random field order:

```json
[
  {
    "Path": "./target/release/deps/c2_chacha-ca1a0c91310eabb8.d",
    "Sha1": "002837be8e2ca93b9262347fa0373e2187cd9fea",
    "Size": "921"
  },
  {
    "Size": "172",
    "Sha1": "002d6db4051f291d43f9f4da43109ac4614c4ba0",
    "Path": "./.gitpod.Dockerfile"
  },
  {
    "Sha1": "00509a8e7c0f536c49d30c4b259d6909d9d90086",
    "Path": "./target/release/deps/libonce_cell-4291a11a6452f8bf.rlib",
    "Size": "132086"
  },
...
```

This is not an `fselect` issue. Lots of software will generate json like this, nothing requires consistent key order, and many will serialise a hash in native hash order which (with seeding) will be different for every object.

The problem can be worked around by
* appending `| pick Path Size Sha1` which seems to re-consolidate the data back into a single table
* by sorting the json keys, eg via `jq -S .`, but note that this needs to be done externally; doing it as part of a nu pipeline will hit #1390 on 0.9.0 and #1355 on master.

**Configuration:**
 - OS: Linux
 - Version: 0.9.0
 - Optional features: none

Note that fselect works fine with csv or tsv (default) format, but those have no headers

**Comment by thegedge** [comment]
The only hesitation I have with sorting columns is that we impose additional cost on _every_ pipeline. I think that in most cases this isn't an issue, so I'd much rather the user be explicit at requesting this behaviour.

If we did decide to do this in nushell, I think it should be configurable, and default to disabled.

Another option is to make it easy to name the columns when `--headerless`. Once we have aliases, this shouldn't be nearly as bad.

**Comment by dcarosone** [comment]
Hm. 

* I think the fix is really only needed in `from_json`, not every pipeline.
* It's not really "sorting" (my bad choice of wording in the issue title, sorry). We don't want to, for example, change the column order when the JSON does happen to be consistent.
* That term does suggest an overhead on every record, even when it turns out to be a NOP. But there is apparently already a check for changes (that causes table-splitting now), and the solution to this won't be any more expensive than that check unless/until the order does change.

As for prevalence, it depends a lot on what is generating the json.  Serde does happen to serialise structs in field order, and similar might well be true for other languages where a defined source order exists.  But for a lot of more dynamic languages (js, python, perl), as well as more dynamic ways of handling data (think serde's `json::Value` mode, which I assume `nu` is using) the data is usually a hashmap emitted in randomised order. The great majority of data I see looks like this.

Thus I'm not nearly as convinced that the default should be, effectively, the current broken behaviour.

As for `--headerless` for csv/tsv/etc: yes, but that's largely unrelated to json where the fields _are_ properly labelled. Also there's precedent in `split_column` for that.

**Comment by thegedge** [comment]
Ah yes, the focus is on `from-json`. My apologies for broadening that to all commands. Ignore my hesitation, as I think just making it work for `from-json` should be fine 🙂

**Comment by andrasio** [comment]
I'm closing this in favor of the changes checking we already do when printing.

It's not ideal to change this in `from-json`, you might be working with saved json files that the unsorted keys for whatever reason. If we open them, do things on them, and save again. We will be saving it with the key ordering changed and end users might not want that.
