### ISSUE TITLE
"external_1 | external_2" pipeline behaves very differently to other shells

### ISSUE THREAD

**Issue by dcarosone** [nushell/nushell#1390]
**Describe the bug**
piping two external commands together causes the second to be invoked repeatedly, once for each chunk

**To Reproduce**
1. cargo install fselect
2. fselect path, size, sha1 from . where is_file==true into json | wc

note: any command that produces enough output will do; I'm using `fselect` because this was found while investigating #1389 and because the sha1 hashing takes time, and this helps to show the chunking/streaming behaviour.

**Expected behavior**
A single invocation of external_2 (`wc`) with all the input data unmolested, just like other shells.

**Screenshots**

Behaviour depends on version

using nu 0.9.0, external_2 gets invoked once for each input chunk:

```
data/foss/rust/nushell(master)> fselect path, size, sha1 from . where is_file==true into json | wc
      0       1     985
      0       1    1021
      0       1    1018
      0       1     962
      0       1    1967
      0       1    1884
      0       1    3854
      0       1     979
      0       1    1010
      0       1    1998
      0       1    4938
      0       1    4017
      0       1    1981
...
```

using 0.9.1 (current master), external_2 gets invoked once, but with empty input!

```
data/foss/rust/nushell(master)> fselect path, size, sha1 from . where is_file==true into json | wc
      0       0       0
```

this latter may be related to #1355 because fselect outputs a single json value with no whitespace, including no terminating newline.

So, this might be partially fixed in master, but it's hard to tell here?

**Configuration:**
 - OS: Linux
 - Version: 0.9.0, master 8ae8ebd1076ea1f37db92349ef8d84dfaabd0ada
 - Optional features: none

**Comment by thegedge** [comment]
For the first part, that was indeed fixed by https://github.com/nushell/nushell/pull/1358.

For the second part, definitely something odd happening with externals that don't output a newline at the end of the stream:

```
nushell on 📙 no-newline-char-in-externals is 📦 v0.9.1 via 🦀 v1.41.0
❯ printf "test" | wc -c
       0
nushell on 📙 no-newline-char-in-externals is 📦 v0.9.1 via 🦀 v1.41.0
❯ echo "test" | wc -c
       4
nushell on 📙 no-newline-char-in-externals is 📦 v0.9.1 via 🦀 v1.41.0
❯ ^echo "test" | wc -c
       5
```

I think @jonathandturner attempted to fix this issue in https://github.com/nushell/nushell/pull/1391, but must be a case we're missing (above output is from latest master).
