### ISSUE TITLE
`error make` not executed in `if-else` statements inside of custom function

### ISSUE THREAD

**Issue by j4ckd4n** [nushell/nushell#13907]
### Question

Not seeing this in documentation or maybe I just don't quite understand it (?). Was hoping for someone to assist with the following issue:

I have the following function defined inside of a custom `tools.nu` file:
```
# Command to fetch client information from itsol
export def "itsol get" [
  id_name: string # ID or Name of the client to fetch
  ] {
  if ($id_name == null) {
    error make {
      msg: "No id_name specified",
      label: { text: "Usage: itsol get <id_name>" }
    }
  }
  let result = run-external 'python' $"C:\\library\\code\\scripts\\python\\itsol.py" $id_name
  if $env.LAST_EXIT_CODE == 2 {
    error make {
      msg: "Missing environment credentials",
      label: { text: "Please set the environment variables redacted and redacted" }
    }
  }
  else if $env.LAST_EXIT_CODE == 3 {
    error make {
      msg: "No client found",
      label: { text: "No client info found for the specified variable" }
    }
  }
  else if $env.LAST_EXIT_CODE != 0 {
    error make {
      msg: "An error occurred",
      label: { text: "An error occurred while fetching the client info" }
    }
  }
  $result | from json
}
```

The `itsol.py` script returns appropriate exit codes when a specific issue occurs which from my understanding is stored in `$env.LAST_EXIT_CODE`. This seems to be true as the shell shows the following:
![image](https://github.com/user-attachments/assets/91a269e5-fb99-4c31-a4aa-35fa40f9e991)

Unsure if I am missing something or if something else is going on that the `error make` code does not get executed upon match. Any assistance or direction would be appreciated.

Thank you in advance.

Documentation reviewed:
- https://www.nushell.sh/book/control_flow.html#if
- https://www.nushell.sh/book/creating_errors.html

**Comment by weirdan** [comment]
You may need to adjust your formatting, as the current parser is quite sensitive to whitespace placement. E.g. the following works:

```nushell
if false {
} else if true { print 123 }
```

but this doesn't:
```nushell
if false { }
else if true { print 123 }
```

So make sure `else if` is on the same line as the closing curly brace of the preceding `if / else if`

You should be getting `Command 'else' not found` error though:
![image](https://github.com/user-attachments/assets/aed5caa3-4db6-4e97-95cd-9d1c0e533ff5)

**Comment by j4ckd4n** [comment]
Hmmm, moved the `else if` statement on the same line as the closing curly brace however still not getting the `error make` to execute. Not seeing any errors or notices of potential issues with the script either. See the updated code below:
![image](https://github.com/user-attachments/assets/df8896ef-c7ea-4832-bf9a-9853c90f93f9)

Should probably mentioned before, running NuShell Version 0.98.0.

**Comment by rayanamal** [comment]
I'm developing a fairly complex and big application in Nu and I've run into this situation a lot. Agreed this is undocumented. I don't know Rust and didn't look into internals, but my current understanding is that errors are just plain values in Nu and they are emitted upon encounter in command boundaries (and possibly other situations, idk). Take a look:
```
~> help error make

Create an error.

Search terms: panic, crash, throw

Usage:
> error make {flags} <error_struct>

Flags:
-h, --help - Display the help message for this command
-u, --unspanned - remove the origin label from the error

Parameters:
error_struct <record>: The error to create.

Input/output types:
╭───┬─────────┬────────╮
│ # │  input  │ output │
├───┼─────────┼────────┤
│ 0 │ nothing │ error  │
╰───┴─────────┴────────╯
```

`error make` *creates* error values. It doesn't raise or throw errors as you might encounter in PLs like python.

Your function creates a bunch of error values but then doesn't do anything with them. Try to `print` one of those errors after the `if` statements that created them, or even just try to run them through a no-op like `each {}`.

**Comment by fdncred** [comment]
Have you tested something like this?
```nushell
error make (
  if $env.LAST_EXIT_CODE == 2 {
    {
      msg: "Missing environment credentials",
      label: { text: "Please set the environment variables redacted and redacted" }
    }
  } else if $env.LAST_EXIT_CODE == 3 {
    {
      msg: "No client found",
      label: { text: "No client info found for the specified variable" }
    }
  } else if $env.LAST_EXIT_CODE != 0 {
    {
      msg: "An error occurred",
      label: { text: "An error occurred while fetching the client info" }
    }
  }
)
```

**Comment by dcarosone** [comment]
> Your function creates a bunch of error values but then doesn't do anything with them. 

Correct.  You're making error values, but then just returning the result anyway.

> Try to `print` one of those errors after the `if` statements that created them, or even just try to run them through a no-op like `each {}`.

No, leave the caller to deal with the error. Just return the error rather than the result.  You can just put that ln a final else clause or reformat the lot into a match block, something like the following, as the last expression:

```
match $env.LAST_EXIT_CODE {
  0 => { $result | from json },
  2 => { error make … }
  3 => { error make … }
  _ => { error make … }
}
```

**Comment by dcarosone** [comment]
basically: attempting to use an error value is the step that actually throws an error and changes the control flow; `error make` just allows you to construct such a value

**Comment by dcarosone** [comment]
And, finally, 0.98 changes the behaviour for externs so that non-zero exit codes will raise an error anyway, so you can just use `try {} catch {}` around your command rather than any of this mess with side-effect environment variables, or just use the result directly and let the error bubble out.

**Comment by j4ckd4n** [comment]
> And, finally, 0.98 changes the behaviour for externs so that non-zero exit codes will raise an error anyway, so you can just use `try {} catch {}` around your command rather than any of this mess with side-effect environment variables, or just use the result directly and let the error bubble out.

Figured that there was no need to throw any errors. Just wanted it to let me know if there are any issues based on the exit code. The code below works as I want it to at this time. I appreciate all of the help and insight I received here! Thank you!

Final code:
```nushell
export def "itsol get" [
	id_name: string # ID or Name of the client to fetch
	] {
	if ($id_name == null) {
		error make {
			msg: "No id_name specified",
			label: {
				text: "Usage: itsol get <id_name>"
			}
		}
	}
	try {
		run-external 'python' $"<path>" $id_name | from json
	} catch {
		if $env.LAST_EXIT_CODE == 2 {
			echo "Missing environment credentials"
		} else if $env.LAST_EXIT_CODE == 3 {
			echo "Client not found"
		} else if $env.LAST_EXIT_CODE != 0 {
			echo "An error occurred"
		}
	}
}
```

**Comment by weirdan** [comment]
> 	if ($id_name == null) {

this is actually a dead code, because `string` can never be `null`

**Comment by j4ckd4n** [comment]
> > if ($id_name == null) {
> 
> this is actually a dead code, because `string` can never be `null`

Good to know. Went ahead and removed it from the code. Thanks!
