### ISSUE TITLE
Lists recognize string as unknown command

### ISSUE THREAD

**Issue by dougg0k** [nushell/nushell#13901]
### Describe the bug

For whatever reason, when building a list/array, and the string put there has a `key=value`, it gives an error.

Only seem to have if there is no space. Same with =number/letter.

```
nu ✗ let list = ["VAR=1"]
Error: nu::parser::unknown_command

  × Unknown command.
   ╭─[entry #25:1:12]
 1 │ let list = ["VAR=1"]
   ·            ────┬────
   ·                ╰── unknown command
   ╰────
```

### How to reproduce

You can straight type `let list = ["VAR=1"]` or put into a file.

### Expected behavior

To just be a string, even more so when in between quotes.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.98.0                              |
| major              | 0                                   |
| minor              | 98                                  |
| patch              | 0                                   |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.81.0 (2dbb1af80 2024-08-20) |
| build_time         | 2024-09-21 16:21:54 -03:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash              |
| installed_plugins  | bash_env 0.14.2                     |

**Comment by fdncred** [comment]
Seems like a bug buy here's a work-around. Use spaces around items in your list.
```nushell
❯ let list = [ "VAR=1" ]
❯ $list
╭───┬───────╮
│ 0 │ VAR=1 │
╰───┴───────╯
```
