### ISSUE TITLE
hash does not support binary input

### ISSUE THREAD

**Issue by dcarosone** [nushell/nushell#13916]
### Describe the bug

`hash` (or at least `hash sha256`) doesn't support binary as an input type

### How to reproduce

```
❯ seq 0 2000 | each { random binary (1MB | into int) | hash sha256 }
Error: nu::parser::input_type_mismatch

  × Command does not support binary input.
   ╭─[entry #12:1:43]
 1 │ seq 0 2000 | each { random binary (1MB | into int) | hash sha256 }
   ·                                                      ─────┬─────
   ·                                                           ╰── command doesn't support binary input
   ╰────
   ```

### Expected behavior

I expected hashing binary data to work.

for my use case this was just to generate input that was cpu-heavy, so passing through `encode hex` was fine as a workaround because I don't care about the hash values directly, but there's no reason this shouldn't work

### Configuration

NixOS unstable

❯ version | transpose key value | to md --pretty
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.98.0                                                            |
| major              | 0                                                                 |
| minor              | 98                                                                |
| patch              | 0                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06) (built from a source tarball) |
| cargo_version      | cargo 1.80.0 (376290515 2024-07-16)                               |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash                                            |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
This seems to work
```nushell
❯ open README.md | into binary | hash sha256
42efbf4acda4ebe77ee3636894ffa752189017ea5a6843c946836d31b33f6880
❯ open README.md | into binary | hash sha256 --binary
Length: 32 (0x20) bytes | printable whitespace ascii_other non_ascii
00000000:   42 ef bf 4a  cd a4 eb e7  7e e3 63 68  94 ff a7 52   B××J××××~×ch×××R
00000010:   18 90 17 ea  5a 68 43 c9  46 83 6d 31  b3 3f 68 80   •×•×ZhC×F×m1×?h×
```
but this doesn't. I'm not sure why.
```nushell
❯ random binary 16
Length: 16 (0x10) bytes | printable whitespace ascii_other non_ascii
00000000:   1c 8f d5 c7  18 69 dd d8  f4 99 22 de  de 9c b9 71   •×××•i××××"××××q
❯ random binary 16 | hash sha256
Error: nu::parser::input_type_mismatch

  × Command does not support binary input.
   ╭─[entry #10:1:20]
 1 │ random binary 16 | hash sha256
   ·                    ─────┬─────
   ·                         ╰── command doesn't support binary input
   ╰────
```

**Comment by fdncred** [comment]
I think i figured it out https://github.com/nushell/nushell/pull/13923

**Comment by dcarosone** [comment]
Thanks.  It turns out passing it through `collect` also works around it.  I'm still not entirely clear what the difference is, I thought it might be between "binary" and "binary (stream)" as shown by `describe`, but that's not it.
