### ISSUE TITLE
Shorthand flags should support `-abc` 

### ISSUE THREAD

**Issue by coolshaurya** [nushell/nushell#1393]
**Is your feature request related to a problem? Please describe.**
more ergonomic to type `-abc` instead `-a -b -c`

**Describe the solution you'd like**
Flags in the form `-abc` to be supported.

**Describe alternatives you've considered**
none

**Additional context**
Currently, doing `-abc` is the same as doing `-a`

**Comment by coolshaurya** [comment]
Considering that this has already been covered in #1240, should I close this ?

**Comment by jonathandturner** [comment]
@coolshaurya - yeah, let's close this and use #1240 to track it.
