### ISSUE TITLE
REPL panics when function has exactly 6 arguments

### ISSUE THREAD

**Issue by aionescu** [nushell/nushell#13930]
### Describe the bug

When trying to call a function with exactly 6 arguments at the REPL, Nu panics when typing the 4th argument.

### How to reproduce

Define the following function:

```nu
def f [a b c d e f] { }
```

Then, at the REPL, try calling it with the following parameters:

```nu
f 1 2 3
```

Trying to write _any_ character after `3 ` (note the space) will cause Nu to panic with the message:

```plaintext
Error:   × Main thread panicked.                                                                                                                               
  ├─▶ at crates/nu-parser/src/parser.rs:926:28
  ╰─▶ index out of bounds: the len is 2 but the index is 3
  help: set the `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

The issue only occurs if `f` has _exactly_ 6 parameters. The names and type signatures of the function and parameters don't seem to affect the outcome.

I've observed the issue on Nu v0.98.0, on both Linux and Android (Termux), and it occurs even with `nu --no-config-file`.

### Expected behavior

I expect to be able to call the command as usual. For example, `f 1 2 3 4 5 6`.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.98.0                                                           |
| major              | 0                                                                |
| minor              | 98                                                               |
| patch              | 0                                                                |
| branch             | makepkg                                                          |
| commit_hash        | 6e1e824473e15eba246e1c43704c5d88fa237a17                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04) (Arch Linux rust 1:1.81.0-1) |
| cargo_version      | cargo 1.81.0 (2dbb1af80 2024-08-20)                              |
| build_time         | 2024-09-18 13:20:08 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | default, sqlite, trash                                           |
| installed_plugins  |                                                                  |

**Comment by sholderbach** [comment]
Ok that is really curious that it is specific for 6 args in the signature and when given 4 args in the call.

This has been reported in two other issues as well:

- https://github.com/nushell/nushell/issues/12069
- https://github.com/nushell/nushell/issues/8385

The problem goes really far back!

**Comment by aionescu** [comment]
I tried searching for "six" and "6" and saw no relevant issues, so I didn't realize it's a duplicate, sorry!

**Comment by sholderbach** [comment]
No worries, I only remembered I have seen this kind of thing before and then went through the known parser panics. Thanks for narrowing down the search space for debugging with the observation!

Annoying that this is so longstanding and after the initial attempt to fix that went in the wrong direction we haven't it figured out yet.

**Comment by NotTheDr01ds** [comment]
Hmm - In hopes of isolating the issue, I think it's actually, `n > (x + 1) // 2` (Floor Division), where:

* `x` is the number of arguments on the command
* `n` is the number of arguments entered.

In other words, with 7 or 8 args in the command definition, the 5th argument will panic the parser.
