### ISSUE TITLE
explore no longer has proper LS_COLORS

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#13936]
### Describe the bug

When doing the command `ls | explore` the LS_COLORS is not working any longer.

@zhiburt could you please look into this. 
I was able to [fix](https://github.com/nushell/nushell/pull/13935) `grid` and `ls` but `explore` is a bit different and I wasn't sure what to change.

### How to reproduce

See above

### Expected behavior

LS_COLORS coloring

### Configuration

|key|value|
|-|-|
|version|0.98.1|
|major|0|
|minor|98|
|patch|1|
|branch|main|
|commit_hash|13df0af5140674e00980ff19843c9bf2e1aa36bb|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.79.0 (129f3b996 2024-06-10)|
|rust_channel|1.79.0-aarch64-apple-darwin|
|cargo_version|cargo 1.79.0 (ffa9cf99a 2024-06-03)|
|build_time|2024-09-25 16:18:26 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|default, sqlite, trash|
|installed_plugins|bexpand 1.3.5, bg 0.5.0, compress 0.1.0, dt 0.1.0, emoji 0.6.0, example 0.98.0, explore_ir 0.2.0, file 0.8.0, formats 0.98.0, gitql 0.1.0, gstat 0.98.0, image 0.4.2, inc 0.98.0, json_path 0.7.0, jwalk 0.8.0, md 0.5.0, parquet 0.8.0, pnet 1.7.0, polars 0.98.0, qr_maker 1.1.0, query 0.98.0, query_git 0.7.0, regex 0.7.0, str_similarity 0.7.0, strutils 0.5.0|

**Comment by zhiburt** [comment]
Hi there,
I wonder if it does work for me?

![image](https://github.com/user-attachments/assets/459e6115-c85f-4099-be16-1d4ea3f75016)

**Comment by fdncred** [comment]
Your folders are not colored in your screenshot and they should be. The files are colored because the coloring for files just looks at the file extension but coloring for folders has to get the metadata for folders. if there isn't a full path provided to the ls_colors coloring routines, the folders won't be colored.
