### ISSUE TITLE
Windows `use <module>` (on file-based module) fails without extension

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#13931]
### Describe the bug

On Windows, `use <module>` fails, but `use <module>.nu` works.  On Linux, `use <module>` does not require an extension.

### How to reproduce

In the root of the Nushell repo:

```nu
use toolkit; toolkit check pr
```

On Linux, this works, but on Windows, it returns:

```nu
Error: nu::parser::module_not_found

  × Module not found.
   ╭─[entry #2:1:5]
 1 │ use toolkit
   ·     ───┬───
   ·        ╰── module toolkit not found
   ╰────
  help: module files and their paths must be available before your script is run as parsing occurs before anything is evaluated
```

Using `use toolkit.nu` works, though.

### Expected behavior

`use <module>` works without `.nu` extension on all platforms.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.98.0                                   |
| major              | 0                                        |
| minor              | 98                                       |
| patch              | 0                                        |
| branch             |                                          |
| commit_hash        | 6e1e824473e15eba246e1c43704c5d88fa237a17 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10)      |
| rust_channel       | 1.79.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.79.0 (ffa9cf99a 2024-06-03)      |
| build_time         | 2024-09-18 08:03:04 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I could be wrong but when you do `use toolkit`, for some reason I was thinking that it was looking for a folder named toolkit.

**Comment by NotTheDr01ds** [comment]
Yeah - Something else is going on here.  I think I might be getting `toolkit` from somewhere in the `NU_LIB_PATH` on Linux, which was (a) throwing me off, and (b) concerning.

Closing and investigating further.  At least *this* is not the issue.

**Comment by fdncred** [comment]
ya, use should search NU_LIB_DIRS for things that match, iirc.
