### ISSUE TITLE
Colored YAML as an output format

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#1394]
**Is your feature request related to a problem? Please describe.**
When there are lots of columns, `table` output can sometimes be less than desirable:

```
❯ ls --full | first 5
───┬────────────┬──────┬────────┬──────────┬───────────┬───────┬───────┬────────┬──────────┬─────
 # │ name       │ type │ target │ readonly │ mode      │ uid   │ group │ size   │ created  │ ...
───┼────────────┼──────┼────────┼──────────┼───────────┼───────┼───────┼────────┼──────────┼─────
 0 │ .DS_Store  │ File │   —    │ No       │ rw-r--r-- │ abcde │ vwxyz │ 6.1 KB │ 2 months │ ...
   │            │      │        │          │           │       │       │        │ ago      │
 1 │ .azure     │ Dir  │   —    │ No       │ rwxr-xr-x │ abcde │ vwxyz │   —    │ 4 months │ ...
   │            │      │        │          │           │       │       │        │ ago      │
 2 │ .cargo     │ Dir  │   —    │ No       │ rwxr-xr-x │ abcde │ vwxyz │   —    │ 4 months │ ...
   │            │      │        │          │           │       │       │        │ ago      │
 3 │ .circleci  │ Dir  │   —    │ No       │ rwxr-xr-x │ abcde │ vwxyz │   —    │ 4 months │ ...
   │            │      │        │          │           │       │       │        │ ago      │
 4 │ .editorcon │ File │   —    │ No       │ rw-r--r-- │ abcde │ vwxyz │  223 B │ 4 months │ ...
   │ fig        │      │        │          │           │       │       │        │ ago      │
───┴────────────┴──────┴────────┴──────────┴───────────┴───────┴───────┴────────┴──────────┴─────
```

There are two issues here:
1. we can't see all the columns, and
2. some of the values can be split across two or more lines.

**Describe the solution you'd like**
Use a YAML or YAML-like format (e.g., `mysql`'s vertical format with `\G`). With either of these solutions, readability would increase greatly if we could highlight column names and values. It could look something like this:

```
  ...

  ---
  name: projects
  type: Directory
  created: 5 days ago
  accessed: 5 days ago
  modified: 5 days ago

  ---
  name: tasks.txt
  type: File
  size: 12KB
  created: 2 days ago
  accessed: 2 days ago
  modified: 2 days ago

  ...
```

**Describe alternatives you've considered**
A "card" format was described in https://github.com/nushell/nushell/issues/1190 as another alternative view, although it may still suffer from the "many columns" issue.

**Comment by KSXGitHub** [comment]
my suggestion from https://github.com/nushell/nushell/issues/1190#issuecomment-586713560:

* Field names should be dimmed.
* Field values should be highlighted according to their types (String, Number, Size, Date, Enum, HyperLink, etc.)

**Comment by KSXGitHub** [comment]
I'm a dilemma regarding Date values of `ls`:
  * `2 days ago` is friendly to human but not recognized as Date by most YAML parsers.
  * ISO 8601, while still readable by humans, it is not as intuitive as the above.

**Comment by KSXGitHub** [comment]
> There are two issues here:
> 
> 1. we can't see all the columns, and
> 2. some of the values can be split across two or more lines.

Let me add another:
3. Resizing terminal messes up layouts and borders.
