### ISSUE TITLE
Strange behavior of into int command

### ISSUE THREAD

**Issue by ArtemChandragupta** [nushell/nushell#13948]
### Describe the bug

I want to write a script to rotate my monitor in hyprland, to make this I need to get a value of current rotation, using `hyprcl` tool by finding string with transform word and get the number after it.

But instead i get the error that tells me that "0" can't be turned to an integer:

```nu
  hyprctl monitors | find transform | parse '{transform} {id}' | get id.0 | into int | $in + 1
Error: nu::shell::cant_convert

  × Can't convert to int.
   ╭─[entry #29:1:75]
 1 │ hyprctl monitors | find transform | parse '{transform} {id}' | get id.0 | into int | $in + 1
   ·                                                                           ────┬───
   ·                                                                               ╰── can't convert string to int
   ╰────
  help: string "0" does not represent a valid integer
```

But this

```nu
  '0' | into int
0
```
Works
Output of hyprctl monitors for a reference:

```
  hyprctl monitors
Monitor eDP-1 (ID 0):
	1920x1200@60.02600 at 0x0
	description: AU Optronics 0x1D8F
	make: AU Optronics
	model: 0x1D8F
	serial: 
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 35 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: false
	solitary: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 1920x1200@60.03Hz 1920x1080@60.03Hz 1600x1200@60.03Hz 1680x1050@60.03Hz 1280x1024@60.03Hz 1440x900@60.03Hz 1280x800@60.03Hz 1280x720@60.03Hz 1024x768@60.03Hz 800x600@60.03Hz 640x480@60.03Hz 
```

### How to reproduce

1. have hyprland
2. print hyprctl monitors | find transform | parse '{transform} {id}' | get id.0 | $in + 1 into your terminal

### Expected behavior

I should get an integer

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.98.0                                                            |
| major              | 0                                                                 |
| minor              | 98                                                                |
| patch              | 0                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06) (built from a source tarball) |
| cargo_version      | cargo 1.80.0 (376290515 2024-07-16)                               |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash                                            |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
my guess is that since you're using `find` it's highlighting the output with ansi escapes. what happens if you use `find -r transform`? the `-r` parameter doesn't highlight the hits.

**Comment by ArtemChandragupta** [comment]
It just returns the output, while original commands pick the one line into a list:

```nu
hyprctl monitors | find -r transform 
Monitor eDP-1 (ID 0):
	1920x1200@60.02600 at 0x0
	description: AU Optronics 0x1D8F
	make: AU Optronics
	model: 0x1D8F
	serial: 
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 35 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: false
	solitary: 0
	activelyTearing: false
	disabled: false
	currentFormat: XRGB8888
	availableModes: 1920x1200@60.03Hz 1920x1080@60.03Hz 1600x1200@60.03Hz 1680x1050@60.03Hz 1280x1024@60.03Hz 1440x900@60.03Hz 1280x800@60.03Hz 1280x720@60.03Hz 1024x768@60.03Hz 800x600@60.03Hz 640x480@60.03Hz 
```

```nu
hyprctl monitors | find transform 
╭───┬──────────────────╮
│ 0 │     transform: 0 │
╰───┴──────────────────╯
```

**Comment by fdncred** [comment]
That's because you have to send it through the `lines` command to get the external output into separate lines.

```nushell
❯ let hype = your output
❯ $hype | lines | find -r transform | str trim | parse "{key}: {value}" | get value.0 | into int
0
```

**Comment by ArtemChandragupta** [comment]
Yes, this works. Thank you for the advise. 

I love nushell way to do things, but sometimes it can be quite inconsistent, that it can even be mistaken for a bug.

**Comment by weirdan** [comment]
The original had a trailing escape sequence (the part starting with 1b) coming from the `find` highlighting:
```
r#'scale: 1.00
   transform: 0
   focused: yes'# | find transform | parse '{transform} {id}' | get id.0 | into binary

Length: 5 (0x5) bytes | printable whitespace ascii_other non_ascii
00000000:   30 1b 5b 30  6d                                      0•[0m
```
