### ISSUE TITLE
config.nu does not persist defined custom commands.

### ISSUE THREAD

**Issue by twilwa** [nushell/nushell#13942]
### Describe the bug

I feel like I must be doing something wrong, but my config.nu looks like this:

# Functions
```nushell
def nvims [] {
    let items = ["default" "Kickstart" "lazyvim" "NvChad" "AstroNvim"]
    let config = (echo $items | fzf --prompt=" Neovim Config  " --height=~50% --layout=reverse --border --exit-0)
    if ($config | is-empty) {
        echo "Nothing selected"
        return
    }
    if $config == "default" {
        nvim $args
    } else {
        ^NVIM_APPNAME=$config nvim $args
    }
}


def lnvim [] { {with-env { NVIM_APPNAME: 'lazyvim' } { nvim } }
def testme [] { echo "test me" }
```
It must be reading from my actual config file, as I get this on startup:
```
Error: nu::parser::variable_not_found

  × Variable not found.
     ╭─[/home/anon/.config/nushell/config.nu:908:14]
 907 │     if $config == "default" {
 908 │         nvim $args
     ·              ──┬──
     ·                ╰── variable not found.
 909 │     } else {
 ```
 however, this is the behavior I get when running and of the def'd commands:
 ```
 ~> testme                                                                                                Error: nu::shell::external_command
  × External command failed
   ╭─[entry #1:1:1]
 1 │ testme
   · ───┬──
   ·    ╰── Command `testme` not found
   ╰────
  help: Did you mean `tee`?

~> nvims                                                                                                                                                                                     09/26/2024 09:16:37 PM
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #2:1:1]
 1 │ nvims
   · ──┬──
   ·   ╰── Command `nvims` not found
   ╰────
  help: `nvims` is neither a Nushell built-in or a known external command

~> knvim                                                                                                                                                                                     09/26/2024 09:16:41 PM
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #3:1:1]
 1 │ knvim
   · ──┬──
   ·   ╰── Command `knvim` not found
   ╰────
  help: `knvim` is neither a Nushell built-in or a known external command
```
  ('knvim' is set as an alias in my config.nu, thought i'd test that as well.)

### How to reproduce

Add a 'def' to the end of config.nu as described above.

### Expected behavior

alias knvim to NVIM_APPNAME=Kickstart nvim, define lnvim as NVIM_APPNAME=lazyvim nvim, get output from testme.

### Configuration

~> version | transpose key value | to md --pretty                                                                                                                                            09/26/2024 09:20:53 PM
| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.98.0                              |
| major              | 0                                   |
| minor              | 98                                  |
| patch              | 0                                   |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.79.0 (ffa9cf99a 2024-06-03) |
| build_time         | 2024-09-26 19:05:24 -07:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash              |
| installed_plugins  |                                     |
~>

**Comment by ysthakur** [comment]
Hi! I'm having hard time telling what's going on because of the formatting, could you enclose the code for your config and the error messages in code fences?
````
```
Like this
...code here...
```
````

The problem, I think, is that you have an error in your `config.nu` itself: `$args` isn't defined. You can't ignore it. It's a parse time error, and so your `config.nu` won't be loaded at all. You should fix that first.

Another thing (unrelated to your problem) is that `echo` in Nushell is the identity function. I think `print` is what you want.

**Comment by fdncred** [comment]
ya, i agree. the `nvims` custom command has syntax errors. before putting it in your config.nu you should test it out in the repl to make sure it works.

**Comment by ysthakur** [comment]
Looks like the signature of `nvims` should look like this (using a [rest parameter](https://www.nushell.sh/book/custom_commands.html#rest-parameters)):
```
def nvims [ ...args ]
```
Or better, since this is a wrapper around `nvim`:
```
def --wrapped nvims [ ...args ]
```
With `--wrapped`, you won't have to declare every option used by `nvim` yourself. Flags will be treated as string arguments and put into `$args`.

**Comment by twilwa** [comment]
I see -- I'm less concerned about nvims not functioning normally, so I've deleted the function for now until I get more familiar with nushell syntax. However, the strange behavior still persists -- 'testme' returns a 'command not found' error, but 'lnvim' does seem to be recgonized -- it just doesn't do anything, heh. Nothing happens and no error prints, but if i run it with an arg, I get 'extra positional argument'.

I think I'll stick to bash as the primary shell for now until I have time to really wrap my head around how nushell works, but I am curious what I've missed this time -- here's the relevant part of my revised config.nu:
```
alias knvim = NVIM_APPNAME=Kickstart nvim
alias cnvim = NVIM_APPNAME=NvChad nvim
alias anvim = NVIM_APPNAME=AstroNvim nvim


def lnvim [] { {with-env { NVIM_APPNAME: 'lazyvim' } { nvim } }
def testme [] { echo "test me" } }


use ~/.cache/starship/init.nu
source ~/.local/share/atuin/init.nu
source ~/.zoxide.nu
```
and env.nu, just in case:
```
# PATH modifications
$env.PATH = ($env.PATH | split row (char esep) | append [
    "~/.local/share/pnpm"
    "~/Downloads/graphlit"
    "~/.pyenv/bin"
    "/usr/local/go/bin"
    "~/go/bin"
    "~/bin"
    "/opt/nvim"
    "~/.foundry/bin"
    "~/.deno/bin"
])

$env.NVM_DIR = "~/.nvm"

$env.PNPM_HOME = "~/.local/share/pnpm"
$env.ANTHROPIC_API_KEY = [redacted]

# To load from a custom file you can use:
# source ($nu.default-config-dir | path join 'custom.nu')

mkdir ~/.cache/starship
starship init nu | save -f ~/.cache/starship/init.nu
zoxide init nushell | save -f ~/.zoxide.nu
```

**Comment by weirdan** [comment]
>  'testme' returns a 'command not found' error, but 'lnvim' does seem to be recgonized -- it just doesn't do anything, heh.

You have some issues with `{}` nesting there, they are more apparent when you format the code:
```nushell
def lnvim [] { 
  {
    with-env { NVIM_APPNAME: 'lazyvim' } { nvim } 
  }
  def testme [] { echo "test me" } 
}
```
So `testme` is a nested def (nushell allows it) and the part with `with-env` is in a block (that doesn't do anything on itself.

what I think you want instead is:

```nushell
def lnvim [] { with-env { NVIM_APPNAME: 'lazyvim' } { nvim } }
# or, more concisely
# def lnvim [] { NVIM_APPNAME=lazyvim nvim } 

def testme [] { echo "test me" }
```

**Comment by twilwa** [comment]
def lnvim [...file:any] { NVIM_APPNAME=lazyvim nvim ...$file }
def testme [] { echo "test me" }

ended up doing it! Everything's functioning as expected.

Revised 'nvims' as follows -- when using --wrapped, i get 'type mismatch' when trying to type the args as 'any':
```
def nvims --wrapped [...args] {
    let items = ["default" "Kickstart" "lazyvim" "NvChad" "AstroNvim"]
    let config = (print $items | fzf --prompt=" Neovim Config  " --height=~50% --layout=reverse --border --exit-0)
    if ($config | is-empty) {
        echo "Nothing selected"
        return
    }
    if $config == "default" {
        nvim $args
    } else {
        ^NVIM_APPNAME=$config nvim $args
    }
}
```
So i think my 'print $items' wants to be piped into my 'fzf' here -- it looks like that's not the case, so I modified it to:

```
def nvims --wrapped [...args] {
    let items = ["default" "Kickstart" "lazyvim" "NvChad" "AstroNvim"]
    let config = (print $items | fzf ...$items --prompt=" Neovim Config  " --height=~50% --layout=reverse --border --exit-0)
    if ($config | is-empty) {
        echo "Nothing selected"
        return
    }
    if $config == "default" {
        nvim $args
    } else {
        ^NVIM_APPNAME=$config nvim $args
    }
}
```

which provides the following behavior in the attached image:

![image](https://github.com/user-attachments/assets/7e4ec1ec-492d-4a03-a070-46ba3dc19dbb)

worked with it with chatgpt for a little bit and got everything working. Final config.nu looks like:

```
def nvims --wrapped [...args] {
    let items = ["default", "Kickstart", "lazyvim", "NvChad", "AstroNvim"]
    let config = ($items | str join "\n" | fzf --prompt=" Neovim Config " --height=~50% --layout=reverse --border --exit-0)

    # Debug statements
    echo "Selected config: ($config)"
    echo "Type of config: " ($config | describe)

    if ($config | is-empty) {
        echo "Nothing selected"
        return
    }
    if $config == "default" {
        nvim ...$args
    } else {
        with-env { NVIM_APPNAME: $config } {
            nvim ...$args
        }
    }
}

def knvim [...args] { NVIM_APPNAME=Kickstart nvim ...$args }
def cnvim [...args] { NVIM_APPNAME=NvChad nvim ...$args }
def anvim [...args] { NVIM_APPNAME=AstroNvim nvim ...$args }

def lnvim [...file:any] { NVIM_APPNAME=lazyvim nvim ...$file }
```

thanks very much for all your help my frens! next command to learn is 'tutor' (probably should have started with that :P)  I'll close it out here.
