### ISSUE TITLE
Panic when completion menu items contains UTF-8 characters and `(`

### ISSUE THREAD

**Issue by petricavalry** [nushell/nushell#13951]
### Describe the bug

Same as title. But completion works good without completion menu (just one item matches).

```
Error:   × Main thread panicked.
  ├─▶ at /usr/src/debug/rust/rustc-1.81.0-src/library/core/src/str/mod.rs:659:21
  ╰─▶ byte index 8 is not a char boundary; it is inside 'よ' (bytes 6..9) of `おはよう/`
         0: 0x56dc1c07a414 - rust_begin_unwind
         1: 0x56dc1b1c8893 - core::panicking::panic_fmt::h0655b7b676f50c86
         2: 0x56dc1b2979ed - core::str::slice_error_fail_rt::h9b9528f958b9dec0
         3: 0x56dc1b1c8fea - core::str::slice_error_fail::h88d0d2d626e6f9da
         4: 0x56dc1bf6c4b7 - reedline::menu::columnar_menu::ColumnarMenu::create_string::h27d56fa5d417da46
         5: 0x56dc1bf6a2e6 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut
      F>::call_once::h562616b1a11d9fa1
         6: 0x56dc1bf4c90a - <alloc::string::String as
      core::iter::traits::collect::FromIterator<alloc::string::String>>::from_iter::hd0f13b363e237bf4
         7: 0x56dc1bf6e620 - <reedline::menu::columnar_menu::ColumnarMenu as reedline::menu::Menu>::menu_string::h96dbad3cfcb8a798
         8: 0x56dc1bf336c0 - reedline::painting::painter::Painter::print_menu::h909301c95f2a9905
         9: 0x56dc1bf3311e - reedline::painting::painter::Painter::repaint_buffer::h46bd0374a1cffd61
        10: 0x56dc1bf64486 - reedline::engine::Reedline::repaint::h4b463cfef1bd119e
        11: 0x56dc1bf60d7a - reedline::engine::Reedline::read_line::h1c31a28a31a65b4b
        12: 0x56dc1b3da538 - nu_cli::repl::loop_iteration::hda4d1895f734f783
        13: 0x56dc1b3d5350 - std::panic::catch_unwind::h3f3c30d5d508999f
        14: 0x56dc1b419e88 - nu_cli::repl::evaluate_repl::hcbf539aaf1a6b69d
        15: 0x56dc1b3adff6 - nu::run::run_repl::h723cd5d7cb9f8683
        16: 0x56dc1b39cc2d - nu::main::hbc2188a8d2cb45fa
```

### How to reproduce

1.  Create two directory:

    ```console
    mkdir おはよう 'おはよう('
    ```

3.  Enter おは and press Tab.

### Expected behavior

Completion menu should show normally.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.98.1                                                           |
| major              | 0                                                                |
| minor              | 98                                                               |
| patch              | 1                                                                |
| branch             | main                                                             |
| commit_hash        | 8200831b07ab87ab23c4a56a8a08251d0332b114                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04) (Arch Linux rust 1:1.81.0-1) |
| cargo_version      | cargo 1.81.0 (2dbb1af80 2024-08-20)                              |
| build_time         | 2024-09-30 00:11:09 +08:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | default, sqlite, trash                                           |
| installed_plugins  |                                                                  |

**Comment by petricavalry** [comment]
This issue is caused by reedline.

**Comment by ysthakur** [comment]
This is probably the same issue as https://github.com/nushell/nushell/issues/11916

**Comment by petricavalry** [comment]
> Thanks for reporting this. This is probably the same issue as #11916

Thanks a lot. I will reopen this issue if still panic after #11916 fixed.

**Comment by ysthakur** [comment]
Just changing the close reason
