### ISSUE TITLE
heads and footers don't always match

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#13966]
### Describe the bug

@zhiburt a while back you fixed some bugs with headers getting truncated. That is working great but now the footers are truncated. When you have a minute, it would be great if you could look into this.

## Header
![image](https://github.com/user-attachments/assets/34eb5d37-93dd-44fa-9f8c-e85c3dc65e16)

## Footer
![image](https://github.com/user-attachments/assets/6f162c9c-454b-4d87-b748-582425c27c10)

Notice how the headers don't match the footers. It seems that whatever you did to the headers, needs to be done to the footers.

### How to reproduce

See above

### Expected behavior

See above

### Configuration

|key|value|
|-|-|
|version|0.98.1|
|major|0|
|minor|98|
|patch|1|
|branch|main|
|commit_hash|166d5fa4ffa3c5514b2d7597f3238e6828c986f9|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.79.0 (129f3b996 2024-06-10)|
|rust_channel|1.79.0-aarch64-apple-darwin|
|cargo_version|cargo 1.79.0 (ffa9cf99a 2024-06-03)|
|build_time|2024-09-30 16:55:41 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|default, sqlite, trash|
|installed_plugins|bexpand 1.3.5, bg 0.5.0, compress 0.1.0, dt 0.1.0, emoji 0.6.0, explore_ir 0.2.0, file 0.8.0, formats 0.98.1, gitql 0.1.0, gstat 0.98.1, image 0.4.2, inc 0.98.1, json_path 0.7.0, jwalk 0.8.0, md 0.5.0, parquet 0.8.0, pnet 1.7.0, polars 0.98.1, qr_maker 1.1.0, query 0.98.1, query_git 0.7.0, regex 0.7.0, strutils 0.5.0|

**Comment by zhiburt** [comment]
Could you @fdncred provide an exact term size.
Just can't reproduce it with ease.

But it's interesting if the case.

![image](https://github.com/user-attachments/assets/5feee7aa-f070-4b99-b182-ccc156a7a1e8)

**Comment by fdncred** [comment]
Sure. I'm using ghostty and my font size is 20 points.
```nushell
❯ term size
╭─────────┬─────╮
│ columns │ 135 │
│ rows    │ 44  │
╰─────────┴─────╯
```
