### ISSUE TITLE
Nushell doesn't appear to properly handle named pipes

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#1396]
**Describe the bug**
I've found at least two cases in which a named pipe (from `mkfifo`) isn't being handled correctly in nushell:

1. `ls` will display it as a `symlink`
2. `rm <pipe path>` will fail with "invalid file"

There are likely other issues, but these are the only two I've observed before filing this issue.

**To Reproduce**
1. `mkfifo named.pipe`
2. `ls`
3. `rm named.pipe`

```
error: Invalid file: /Users/gedge/src/github.com/nushell/nushell/named.pipe
- shell:1:13
1 | rm "named.pipe"
  |    ^^^^^^^^^^ invalid file
```

**Expected behavior**
1. `ls` would display the type as "Pipe", or something along those lines.
2. `rm <pipe path>` would remove the pipe.

**Configuration (please complete the following information):**
 - OS: OSX
 - Version 10.15.2

**Comment by lincis** [comment]
I would like to tackle this issue.

**Comment by thegedge** [comment]
It's yours, @lincis. Join us in the `#developing` on Discord if you want to ask any questions or need some help 🙂
