### ISSUE TITLE
Remove automatic line-ending parsing

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1397]
**Describe the bug**
We currently assume that the input stream from stdin wants to be parsed using line endings like `\n` but this is incorrect for a few reasons:

* If the user wishes to work with the text in a different way, they don't have the control
* If the stdin doesn't end with a line ending, we would fail to read it in. We currently have a workaround where we insert this line ending, but this is incorrect in the general case
* If stdin is binary data, we might end up reading in bytes that aren't characters and look for line endings in them. This will cause panics and confusion

**To Reproduce**
1. Stream between an external and another command

**Expected behavior**
The solution is in a few parts.

* Make streaming from an external take in bytes (you can think of this as packets of bytes). These would be unaltered from what is read in from the external's stdout.
* Give internal commands a way to read in a string of text
* Give internal commands a way to collect the stream as text
  * Note: it's unclear if these should be automatic conversions based on the type of the input or manually done by each command
* **Remove** the automatic line ending parsing (LineCodec), and move to BytesCodec
* Next, when viewing, do *not* treat a stream of non-row values as separate rows.  Instead, simply display the text (or binaryview the binary) using simple streaming methods
Note: Do **not** collect text or binary and use in a viewer by default as these streams may not terminate

**Comment by thegedge** [comment]
@jonathandturner any progress here? I feel like `MaybeTextCodec` is a step in this direction.

**Comment by jonathandturner** [comment]
@thegedge I believe all of these were fixed with `MaybeTextCodec`
