### ISSUE TITLE
Escapes pipes in strings sent to cmd

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1398]
**Describe the bug**
The pipe character (`|`) is currently not allowed in strings

**To Reproduce**
1. ❯ az webapp create -n "myapp" -g "mygroup" -p "myplan" -r "node|10.15"

Will give you:
```
'10.15' is not recognized as an internal or external command,
operable program or batch file.
```
**Expected behavior**
The pipe character will be treated as part of the string

**Configuration (please complete the following information):**
 - OS: [e.g. Windows]: Window 10
 - Version [e.g. 0.4.0]: 0.9.1

**Comment by thegedge** [comment]
For additional context, some basic examples work:

```
~/tmp/rust is 📦 v0.1.0 via 🦀 v1.41.0
❯ echo "a | b"
a | b

~/tmp/rust is 📦 v0.1.0 via 🦀 v1.41.0
❯ ^echo "a | b"
a | b

~/tmp/rust is 📦 v0.1.0 via 🦀 v1.41.0
❯ ^echo -n "a | b"
-n a | b

~/tmp/rust is 📦 v0.1.0 via 🦀 v1.41.0
❯ ^echo "a | b" "<--->" "c | d"
a | b <---> c | d
```

**Comment by thegedge** [comment]
Actually, maybe it works on OSX. Perhaps something related to how we pass things to `cmd`?

**Comment by jonathandturner** [comment]
Yeah, it looks like this needs to be escaped before being sent to `cmd`.  Removing parser tag as it's external-related

**Comment by itn3000** [comment]
same issue is still occured in 0.21.0, run following program, then get error(windows10-1909)
```
rg "|" abc.txt
```
(rg is [ripgrep](https://github.com/BurntSushi/ripgrep))
only `echo "abc|abc"` is working, but trying to pass literal `|` to external command is not interpreted as literal `|`.

**Comment by chrmod** [comment]
@itn3000 I was hit by the same issue - a way around that works is to use single quotes and escape the pipe `rg '\|'`
