### ISSUE TITLE
windowe11: Error: nu::shell:: "env_variable_not_found " Environment variable 'PATH' not found

### ISSUE THREAD

**Issue by qianlongzt** [nushell/nushell#13995]
### Describe the bug

Error: nu::shell:: "env_variable_not_found " Environment variable 'PATH' not found

### How to reproduce

1. use windows terminal open nu

### Expected behavior

run other programs no error

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.98.0                                   |
| major              | 0                                        |
| minor              | 98                                       |
| patch              | 0                                        |
| branch             |                                          |
| commit_hash        | 6e1e824473e15eba246e1c43704c5d88fa237a17 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10)      |
| rust_channel       | 1.79.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.79.0 (ffa9cf99a 2024-06-03)      |
| build_time         | 2024-09-18 08:04:05 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  |                                          |

**Comment by qianlongzt** [comment]
I found my windows 11 have "Path"(user) and "path"(system) env. result to process is path.

I fix this rename "path"(system) to Path.

should nu handle "path"?

**Comment by fdncred** [comment]
No, on Windows, there should only be on case spelling of Path. I'm not even sure how Windows works with one being path and the other Path.
