### ISSUE TITLE
`try` block prints result (0.98 regression)

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#13991]
### Describe the bug

When using a `try` block, the return value of the block is now being printed to the screen.  This did not occur in 0.97.1.

### How to reproduce

```nu
def foo [] {
  try { "This value should not be displayed." }
  "This, however, is the true return value of foo."
}

foo

# => This value should not be displayed.
# => This, however, is the true return value of foo.
```

In 0.97.1 and before, only the expected result is returned.

Adding an `ignore` suppresses it, but you shouldn't have to do that to every `try` block.

### Expected behavior

Not print results unless it is the return value of the root expression or explicitly printed.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.98.0                              |
| major              | 0                                   |
| minor              | 98                                  |
| patch              | 0                                   |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10) |
| rust_channel       | 1.79.0-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.79.0 (ffa9cf99a 2024-06-03) |
| build_time         | 2024-09-27 20:06:48 -04:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash              |
| installed_plugins  |                                     |

**Comment by IanManske** [comment]
Thanks for reporting this! A fix should be up soon.
