### ISSUE TITLE
Partial evaluation like xargs

### ISSUE THREAD

**Issue by wycats** [nushell/nushell#14]
Straw man:

```powershell
ps | where name =~ chrome | kill $it.pid
```

TL;DR, when a statement refers to `$it`, it effectively desugars into a closure taking one parameter whose value is the current pipeline input.

**Comment by jonathandturner** [comment]
Likely blocked on #180

**Comment by wycats** [comment]
This is done

**Comment by raboof** [comment]
How do you use this? I get `unknown variable: $it` with the straw man example, but I guess the actual syntax is different ;)

**Comment by raboof** [comment]
Ah, `ps | where name =~ chrome | each { kill $it.pid }`

**Comment by hasnolen** [comment]
Seems like I had use `$in`, not `$it`. See 
> [Pass values as command parameters](https://www.nushell.sh/book/coming_from_bash.html)

>  `ls \*\*/Makefile | get name | vim $in`
