### ISSUE TITLE
`/proc/<nu_pid>/cwd` links to wrong directory

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#14000]
### Describe the bug

Perhaps related to #12953.

Since installing the latest main, whenever I create a new Tmux window using the hotkeys, Nushell always starts in `~/.local/share/rust/cargo/bin`, which is the directory where the binary is located.  I'm assuming this is a side-effect of #12953.

Root issue appears to be that `/proc/($nu.pid)/cwd` is *always* linked to the binary directory.  For all other applications and shells (and Nu 0.98 and before), it reflects the *current* path of the process.

I'm guessing this is going to generate corner-cases with applications other than just Tmux.

#### Core issue

```nu
cd ~

# Launch latest main
/path/to/nu_main/nu
[ /proc, $nu.pid, cwd ] | path join | ls -l -D $in | get target

# => /proc/to/nu_main

cd /
[ /proc, $nu.pid, cwd ] | path join | ls -l -D $in | get target

# => /proc/to/nu_main

cd ~
# Launch 0.98 or before
/path/to/0.98/nu
[ /proc, $nu.pid, cwd ] | path join | ls -l -D $in | get target

# => /home/ntd

cd /
[ /proc, $nu.pid, cwd ] | path join | ls -l -D $in | get target

# => /
```

Bash (confirmed), Fish (confirmed), (probably) Neovim, etc. all have the correct `cwd` link as well.

#### Reproduce Tmux issue

With 0.98.1 main set as the user shell:

1. Configure `~/.config/tmux/tmux.conf`:

   ```
   bind c new-window -c '#{pane_current_path}'
   ```

2. `cd ~`

2. Run Tmux with `tmux`

3. Create a new window using <kbd>Ctrl</kbd>+<kbd>B</kbd> <kbd>C</kbd>

Result: New window starts in bin directory rather than `~`.

Note that, when using the `tmux `command directory, rather than a keybinding, it works as expected:

```
cd ~
tmux new-window -c "#{pane_current_path}"
pwd

# => /home/ntd
```

While I'm guessing/hoping I can figure out some configuration to work around this, I'm worried that this is going to cause other issues as well.

Notes:

* Tested in a temp `XDG_CONFIG_HOME` with fresh `config.nu`, etc.

### Expected behavior

`/proc/<nu_pid>/cwd` is linked to current directory

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.98.1                                   |
| major              | 0                                        |
| minor              | 98                                       |
| patch              | 1                                        |
| branch             | main                                     |
| commit_hash        | 00709fc5bd69083ecefe40f535702984c19ffa1a |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10)      |
| rust_channel       | 1.79.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.79.0 (ffa9cf99a 2024-06-03)      |
| build_time         | 2024-10-03 07:45:21 -04:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I'm not sure what to do about this but one hack may be to do `nu -e 'cd what/ever/folder'`

**Comment by weirdan** [comment]
Do you have `$env.config.shell_integration.osc7` enabled? tmux is supposed to support it.

**Comment by NotTheDr01ds** [comment]
@weirdan Yes, I'm using defaults, and it's enabled.  That seems to explain why manually entering:

```nu
tmux new-windows -c "#{pane_current_path}"
```

... is working.

I also think I figured out the root issue, so (assuming I'm right), I'm about to update the top-level issue.

**Comment by NotTheDr01ds** [comment]
@fdncred Good thought, but I need Tmux to pass that directory in dynamically, and it's getting the wrong directory.

**Comment by NotTheDr01ds** [comment]
Thinking I might be able to create a Nushell key binding that runs the `tmux new-windows ...`.  The Tmux server may not be able to query the current directory through `/proc`, but Nushell itself will know what it is.

Downside is that, to my knowledge, I can't create a leader-key in Nushell, right?  That means 20 years of `screen` muscle-memory down the tubes.

Regardless, I think not updating the process `cwd` on `cd` is a pretty bad issue and is going to break other things.

**Comment by fdncred** [comment]
@NotTheDr01ds could you try this to see if it fixes it https://github.com/nushell/nushell/pull/14003 ?

**Comment by NotTheDr01ds** [comment]
@fdncred Yes, fixes both root and secondary issue.

**Comment by NotTheDr01ds** [comment]
I had just started going through the changes in it to see if I could spot the reason why `cwd` changed, and if perhaps one of the deletions was "over-aggressive".  But still coming up to speed on that PR.

**Comment by fdncred** [comment]
We'd prefer not to revert it and do a surgical fix. So, if you can figure that out, it would be great!

**Comment by NotTheDr01ds** [comment]
I'll ... try, but those with understanding of the intent have a much better chance than I ;-)

**Comment by NotTheDr01ds** [comment]
Thanks! Yeah, the older commits looked more likely to trigger the issue, but it didn't manifest until the most recent.  Still coming up to speed on that area of the code, which is hard to do on mobile ;-).

**Comment by fdncred** [comment]
This was Kubouch's feedback to me earlier 
```
#12953 removed setting CWD from merge_env(). So reverting it should be enough. 
```
