### ISSUE TITLE
not found commands are recorded in history with `exit_status = 0`

### ISSUE THREAD

**Issue by maxim-uvarov** [nushell/nushell#14016]
### Related problem

When user enters a command that doesn't exist - nushell records it with `exit_status = 0`, which seems misleading

![Screenshot 2024-10-05 at 8 56 07 PM](https://github.com/user-attachments/assets/14d5433d-8427-4ced-886e-5d6e27afc34b)

### Describe the solution you'd like

user `@uep` on discord suggested that it would be better to record `exit_status = null`

**Comment by WindSoilder** [comment]
Hmm... I can't reproduce it again.  
```nushell
> history | last 2 | get 0
╭─────────┬──────╮
│ command │ as   │
│ index   │ 5705 │
╰─────────┴──────╯
```
My history command never show `exit_status`

**Comment by maxim-uvarov** [comment]
Oh, wow! It works the same way for me too! @WindSoilder, thanks for checking!

And many thanks to whoever fixed this!
