### ISSUE TITLE
`transpose` swallows and hides errors from pipeline

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#14027]
### Describe the bug

most of the time, Nushell handles errors fine, e.g. by throwing directly when it occurs.

however, it sometimes does not do that and, when a command later in a pipeline sees the errors, it does not know what to do and give a very obscure error.

tbh, this could very well be a design issue with Nushell errors where they are sometimes more like values and some other times more like exceptions :thinking: 
e.g. it's possible to sometimes store an error in a variable like a value and, as soon as you do anything with it, it throws and crashes as an exception 

### How to reproduce

1. run the following
```nushell
"alice - 12s" | parse "{name} - {t}" | into duration t
```
2. see the correct error (even though the span could be a bit better and point to `{t}` instead of `parse`, it's fine i think)
```
Error: nu::shell::cant_convert_with_value

  × Can't convert string `12s` to duration.
   ╭─[entry #11:1:17]
 1 │ "alice - 12s" | parse "{name} - {t}" | into duration t
   ·                 ─┬─┬
   ·                  │ ╰── this string value...
   ·                  ╰── can't be converted to duration
   ╰────
  help: supported units are ns, us/µs, ms, sec, min, hr, day, and wk
```

3. run the following which adds a call to `transpose`
```nushell
"alice - 12s" | parse "{name} - {t}" | into duration t | transpose --header-row
```
4. get the following very impossible-to-debug error
```
Error:   × Header row is incomplete and can't be used
   ╭─[entry #13:1:58]
 1 │ "alice - 12s" | parse "{name} - {t}" | into duration t | transpose --header-row
   ·                                                          ────┬────
   ·                                                              ╰── using incomplete header row
   ╰────
```

### Expected behavior

i expected the second command (bullet 3) to give the same error as the first one, e.g.
```
Error: nu::shell::cant_convert_with_value
  × Can't convert string `12s` to duration.
   ╭─[entry #13:1:58]
 1 │ "alice - 12s" | parse "{name} - {t}" | into duration t | transpose --header-row
   ·                 ─┬─┬
   ·                  │ ╰── this string value...
   ·                  ╰── can't be converted to duration
   ╰────
  help: supported units are ns, us/µs, ms, sec, min, hr, day, and wk
```

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.98.0                              |
| major              | 0                                   |
| minor              | 98                                  |
| patch              | 0                                   |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10) |
| rust_channel       | 1.79-x86_64-unknown-linux-gnu       |
| cargo_version      | cargo 1.79.0 (ffa9cf99a 2024-06-03) |
| build_time         | 2024-09-21 11:17:41 +02:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash              |
| installed_plugins  | clipboard 0.98.0, explore 0.98.0    |

**Comment by fdncred** [comment]
Hmmm, or maybe we could have multiple errors per pipeline. I've seen that before. Not sure if we should go back to the first error and report that or just report all of them. Either would probably be an improvement over 'eating' the error I think.

**Comment by amtoine** [comment]
yeah i agree!

with this example, i think only the first error really makes sense but maybe in general having all of them could prove useful, probably depends on the situation :)

**Comment by PhotonBursted** [comment]
I started playing around with this a little, to see if I could find an entrypoint.
The behaviour is a little inconsistent?

```nushell
let basecase = "alice - 12s" | parse "{name} - {t}" | into duration t
$basecase                             # Error as proposed
$basecase | transpose --header-row    # Fails, error message pointing to transpose
$basecase | transpose                 # Returns empty list...?
$basecase | to nuon                   # Fails, error message "cannot convert to nuon", same issue really
$basecase | to json                   # Error as proposed
$basecase | to msgpack                # Error as proposed
$basecase | into string               # Error as proposed
```

So some commands act appropriately, and others are really confused.

I'm not totally familiar with how the error handling works, but I did see that `describe`ing the basecase told me it was a stream of errors (`list<error> (stream)`, to be exact); perhaps that is why some behave and others don't?

**Comment by fdncred** [comment]
Thanks for trying to push this forward. What you've described with some commands handling streams and others not handling them is definitely plausible. Each command has its own code so theoretically they could be very different. It would be nice to have a standardization pass on all commands with things like this in mind.

**Comment by a-stevan** [comment]
yeah, i've just encountered the same error with the following setup
```nushell
$some_table_with_foo_column
    | insert bar {|it|
        # some code that involves an unknown command
    }
    | reject foo
```

and the error i get is 
```
cannot find column 'foo'
```
where it should be
```
Command `whatever` not found
```

**Comment by a-stevan** [comment]
i haven't tried it yet, but noice, thanks guys :pray: :ok_hand:
