### ISSUE TITLE
Error: nu::shell::non_zero_exit_code

### ISSUE THREAD

**Issue by dougg0k** [nushell/nushell#14024]
### Question

Hi,

Is there anything that can be done through configuration maybe, or this is intended, to have an error for every non-0/successful or even cancelled/interrupted commands?

**Comment by fdncred** [comment]
Have you read the release notes? https://www.nushell.sh/blog/2024-09-17-nushell_0_98_0.html#non-zero-exit-codes-are-now-errors-toc

**Comment by dougg0k** [comment]
Obviously no. Thanks.
