### ISSUE TITLE
When command starts with `? ` all text after is hidden

### ISSUE THREAD

**Issue by JesterOrNot** [nushell/nushell#1402]
**Describe the bug**
Text after a leading ? is hidden

**To Reproduce**
1. Type a `?`
2. Type other stuff see that you can't see that
3. Click enter see that the other stuff was typed and you are not insane 😃 

**Expected behavior**
See all text after the `?`
**Screenshots**
![image](https://user-images.githubusercontent.com/50386709/74698622-1ec6b400-51c4-11ea-9cc0-b5902be065e8.png)

**Configuration (please complete the following information):**
 - OS: Ubuntu (Gitpod)
 - Version latest
 - Optional features all

**Comment by thegedge** [comment]
👍 note that I had to type a space after the `?` to get the same behaviour, but I do get it 🙂

**Comment by jonathandturner** [comment]
This should be fixed in master
