### ISSUE TITLE
What is the equivalent command for 'where' command in linux?

### ISSUE THREAD

**Issue by unisons** [nushell/nushell#14045]
### Question

What is the equivalent command for 'where' command in linux?

I'd like to find the location of some commands or executables in the path. In PowerShell, I can use "get-command" and in linux I can use "where" or "location". But I can't find the proper command in NuShell.

**Comment by dedebenui** [comment]
Use `which` to know where a command is, which the flag `-a/--all` to list all commands found in your `PATH`, not only the first one. You can find more info with `help which`

Example:
```
>>> which -a python
╭───┬─────────┬────────────────────────────────────────────────┬──────────╮
│ # │ command │                      path                      │   type   │
├───┼─────────┼────────────────────────────────────────────────┼──────────┤
│ 0 │ python  │ /Users/dedebenui/some_project/.venv/bin/python │ external │
│ 1 │ python  │ /Users/dedebenui/miniconda3/bin/python         │ external │
╰───┴─────────┴────────────────────────────────────────────────┴──────────╯
```

**Comment by unisons** [comment]
@dedebenui Thank you for the reply!
