### ISSUE TITLE
Data loss: New `history import` command clobbers existing history

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#14076]
### Describe the bug

cc: @qfel @fdncred 

`history import` *overwrites* existing history when importing.  This can cause loss of portions of the command history.  Recommend that this be reverted until fixed.

Side-note:  I'm *really* glad I tested this in a `mktemp -d` environment.  I would have lost the first 1705 items from my SQLite-backed history, as that's how many commands I had in the text-backed version that I tried importing.

### How to reproduce

Best tested with:

```nu
$env.XDG_CONFIG_HOME = (mktemp -d)
./target/release/nu

# Answer Y to prompts to create config files

# => Config file created at: /tmp/tmp.1SmeNTqrtd/nushell/config.nu

# Output abbreviated/omitted below when not important
echo 1
echo 2
echo 3
echo 4
echo 5
history

# => ╭───┬─────────╮
# => │ # │ command │
# => ├───┼─────────┤
# => │ 0 │ echo 1  │
# => │ 1 │ echo 2  │
# => │ 2 │ echo 3  │
# => │ 3 │ echo 4  │
# => │ 4 │ echo 5  │
# => ╰───┴─────────╯

# Edit $nu.config-path and change history.file_format to sqlite
# exit and restart the shell (using same temp config)

history
# => ╭───┬─────────────────────────────┬─────────┬─────────────────────────────────┬──────────┬─────────────╮
# => │ # │       start_timestamp       │ command │               cwd               │ duration │ exit_status │
# => ├───┼─────────────────────────────┼─────────┼─────────────────────────────────┼──────────┼─────────────┤
# => │ 0 │ 2024-10-13 02:02:58.885 UTC │ history │ /home/ntd/src/ntd-forks/nushell │     0sec │           0 │
# => ╰───┴─────────────────────────────┴─────────┴─────────────────────────────────┴──────────┴─────────────╯

echo a
echo b
echo c
echo d
history

# => ╭───┬─────────────────────────────┬─────────┬─────────────────────────────────┬──────────┬─────────────╮
# => │ # │       start_timestamp       │ command │               cwd               │ duration │ exit_status │
├───┼─────────────────────────────┼─────────┼─────────────────────────────────┼──────────┼─────────────┤
# => │ 0 │ 2024-10-13 02:02:58.885 UTC │ history │ /home/ntd/src/ntd-forks/nushell │      1ms │           0 │
# => │ 1 │ 2024-10-13 02:03:04.360 UTC │ echo a  │ /home/ntd/src/ntd-forks/nushell │     0sec │           0 │
# => │ 2 │ 2024-10-13 02:03:05.492 UTC │ echo b  │ /home/ntd/src/ntd-forks/nushell │     0sec │           0 │
# => │ 3 │ 2024-10-13 02:03:06.675 UTC │ echo c  │ /home/ntd/src/ntd-forks/nushell │     0sec │           0 │
# => │ 4 │ 2024-10-13 02:03:08.087 UTC │ echo d  │ /home/ntd/src/ntd-forks/nushell │     0sec │           0 │
# => │ 5 │ 2024-10-13 02:03:12.432 UTC │ history │ /home/ntd/src/ntd-forks/nushell │     0sec │           0 │
# => ╰───┴─────────────────────────────┴─────────┴─────────────────────────────────┴──────────┴─────────────╯

# So far, so good, but now

history import
history

# => ╭───┬─────────────────────────────┬────────────────────┬─────────────────────────────────┬──────────┬─────────────╮
# => │ # │       start_timestamp       │      command       │               cwd               │ duration │ exit_status │
├───┼─────────────────────────────┼────────────────────┼─────────────────────────────────┼──────────┼─────────────┤
# => │ 0 │                             │ echo 1             │                                 │     0sec │           0 │
# => │ 1 │                             │ echo 2             │                                 │     0sec │           0 │
# => │ 2 │                             │ echo 3             │                                 │     0sec │           0 │
# => │ 3 │                             │ echo 4             │                                 │     0sec │           0 │
# => │ 4 │                             │ echo 5             │                                 │     0sec │           0 │
# => │ 5 │                             │ history            │                                 │     0sec │           0 │
# => │ 6 │                             │ vi $nu.config-path │                                 │     0sec │           0 │
# => │ 7 │ 2024-10-13 02:03:16.283 UTC │ history import     │ /home/ntd/src/ntd-forks/nushell │     0sec │           0 │
# => │ 8 │ 2024-10-13 02:03:17.653 UTC │ history            │ /home/ntd/src/ntd-forks/nushell │     0sec │           0 │
# => ╰───┴─────────────────────────────┴────────────────────┴─────────────────────────────────┴──────────┴─────────────╯
```

The `echo <letter>` commands that *were* in the SQLite-backed history have been overwritten by the `echo <number>` commands from the old text-backed history.

### Expected behavior

`history import` should *add to*, not overwrite, existing history file.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.98.1                                   |
| major              | 0                                        |
| minor              | 98                                       |
| patch              | 1                                        |
| branch             | main                                     |
| commit_hash        | 0c72f881a635e258f86a7cd4346ee842699061e1 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10)      |
| rust_channel       | 1.79.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.79.0 (ffa9cf99a 2024-06-03)      |
| build_time         | 2024-09-26 14:23:04 -04:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  |                                          |

**Comment by qfel** [comment]
Wow, that was fast.

The code doesn't try to clear/remove anything, so I suspect it's some interaction with the item IDs that only the sqlite backend manages.

I'll take a look later, but for now sent https://github.com/nushell/nushell/pull/14078 - I think it's better than reverting and re-sending the entire change later.

**Comment by NotTheDr01ds** [comment]
> Wow, that was fast.

Lol - Yeah, I did a pull and noticed the changes.  I branched to do some word-smithing and formatting on the help/doc and was testing it out while doing the write-up.  I didn't want to mess with my main history, so I just copied my `history.sqlite` and `history.txt` into a new `XDG_CONFIG_HOME` and was surprised when none of my recent commands were being suggested from the history.

That also raises the point of whether an import should *append* or *insert* the "other format" (or provide both options)?

**Comment by qfel** [comment]
> That also raises the point of whether an import should append or insert the "other format" (or provide both options)?

It was meant to append. But I didn't notice that while that plaintext backend ignores item IDs on save, it still produces them when reading - causing issues when importing from plaintext to sqlite (but not vice-versa).
