### ISSUE TITLE
ColumnPath syntax not fully supported in externals.

### ISSUE THREAD

**Issue by andrasio** [nushell/nushell#1408]
**Describe the bug**
When attempting to pass a column path either when trying to fetch from `$it` or `$nu`, nothing happens.

**To Reproduce**
Given the file `data.json`:

```shell
{ 
 "dependencies": [
  { "some crate": "server" },
  { "other": "nu" }
 ]
}
```

followed by: `open data.json | ^echo $it.dependencies.0."some crate"`

**Expected behavior**
Should print `server`

**Comment by thegedge** [comment]
Looks like @jonathandturner's recent work fixed this:

```
❯ open Cargo.toml | get bin | ^echo $it.name
fail
chop
cococo
nonu
iecho
nu_plugin_core_textview
nu_plugin_core_inc
nu_plugin_core_ps
nu_plugin_core_str
nu_plugin_core_sys
nu_plugin_stable_average
nu_plugin_stable_fetch
nu_plugin_stable_binaryview
nu_plugin_stable_match
nu_plugin_stable_post
nu_plugin_stable_tree
nu_plugin_stable_start
nu
```
