### ISSUE TITLE
Bug: NU_LOG_FORMAT and NU_LOG_DATE_FORMAT are not defined

### ISSUE THREAD

**Issue by FMotalleb** [nushell/nushell#14109]
### Describe the bug

I encountered an issue while trying to install one of my plugins using `nupm`:

https://github.com/FMotalleb/nu_plugin_image

It's strange because I recently updated other plugins using the same installation method, and they worked fine (all of them already used `std log`).

```
~\Documents\GitHub\nu_plugin_image> nupm install --path .
1 10/16/2024 11:54:41 PM
Error: nu::shell::column_not_found

  × Cannot find column 'NU_LOG_FORMAT'
     ╭─[std/log\mod.nu:158:9]
 157 │     let log_format = if ($format_string | is-empty) {
 158 │         $env.NU_LOG_FORMAT
     ·         ─────────┬────────┬
     ·                  │        ╰── value originates here
     ·                  ╰── cannot find column 'NU_LOG_FORMAT'
 159 │     } else {
     ╰────
```

When I set `NU_LOG_FORMAT` to an empty string (`""`) and tried again, I received another error:

```
~\Documents\GitHub\nu_plugin_image> nupm install --path .
10/16/2024 11:55:45 PM
Error: nu::shell::column_not_found

  × Cannot find column 'NU_LOG_DATE_FORMAT'
     ╭─[std/log\mod.nu:148:28]
 147 │ def now [] {
 148 │     date now | format date $env.NU_LOG_DATE_FORMAT
     ·                            ───────────┬───────────┬
     ·                                       │           ╰── value originates here
     ·                                       ╰── cannot find column 'NU_LOG_DATE_FORMAT'
 149 │ }
     ╰────
```

I was able to resolve the issue by setting both environment variables, but this still seems like a bug.

### How to reproduce

Well I think its from std/log or nupm atleast

### Expected behavior

Format should have a default value

### Configuration

| key                | value                                                                                                          |
| ------------------ | -------------------------------------------------------------------------------------------------------------- |
| version            | 0.99.0                                                                                                         |
| major              | 0                                                                                                              |
| minor              | 99                                                                                                             |
| patch              | 0                                                                                                              |
| branch             |                                                                                                                |
| commit_hash        |                                                                                                                |
| build_os           | windows-x86_64                                                                                                 |
| build_target       | x86_64-pc-windows-msvc                                                                                         |
| rust_version       | rustc 1.82.0-nightly (41dd149fd 2024-08-11)                                                                    |
| rust_channel       | nightly-x86_64-pc-windows-msvc                                                                                 |
| cargo_version      | cargo 1.82.0-nightly (0d8d22f83 2024-08-08)                                                                    |
| build_time         | 2024-10-16 23:36:40 +03:30                                                                                     |
| build_rust_channel | release                                                                                                        |
| allocator          | mimalloc                                                                                                       |
| features           | default, sqlite, static-link-openssl, system-clipboard, trash                                                  |
| installed_plugins  | audio_hook 0.2.6, clipboard 0.99.0, desktop_notifications 1.2.5, image 0.5.6, port_list 1.4.4, port_scan 1.2.5 |

**Comment by FMotalleb** [comment]
well it has a default value idk what happend to that session
maybe the terminal session was buggy, I cannot identify the source of the issue so i will close this one

**Comment by fdncred** [comment]
I wonder if this was due to the stdlib changes? @NotTheDr01ds any thoughts?

**Comment by weirdan** [comment]
Those variables _do_ have default values:

https://github.com/nushell/nushell/blob/9d25b2f29ab178c7dd514b90fe4575156f6a7b60/crates/nu-std/std/log/mod.nu#L38-L41

**Comment by FMotalleb** [comment]
**Some context:**
* This wasn't the first launch (I already had 3 other instances of Nu running in other VS Code windows).
* Nu was launched inside VS Code, which sometimes preserves older states.
    * In this case, if it preserved an older state, it was a 0.98 version of Nu.
    * I think it only preserve outputs but Its possible that the state contains Env vars from older instance
* The older version of Nu had already been removed (I use Cargo, and the issue occurred on Windows. It's essentially impossible to run `cargo install nu` from within Nu itself, so I had to use cmd instead).

**Comment by NotTheDr01ds** [comment]
> Nu was launched inside VS Code, which sometimes preserves older states.

Is it possible that VSCode was launched from inside the 0.98 Nushell before it was uninstalled?

Regardless, I can't say for sure what happened there.  I can't think of a scenario where the environment variable would *not* be available after a `use std log` (or any variation thereof).

I'll try a few scenarios with `nupm` installing a plugin and see if I can reproduce.

**Comment by FMotalleb** [comment]
vscode was launched using nu 0.99
in my buildscript I am using `use std log` so maybe its not about nupm and its just my buildscript

and I am able to reproduce it
Idk how or why but it happens again for that instance of vscode

**Comment by FMotalleb** [comment]
when I manually execute `use std log` it works fine
so maybe its from nupm

**Comment by FMotalleb** [comment]
I removed `use std log` from my build script and it still failed
possibly because it was imported by nupm itself

**Comment by fdncred** [comment]
How about `use std/log`? We've (@NotTheDr01ds) recently change things around to make it more efficient.

**Comment by FMotalleb** [comment]
Same effect as `use std log` if I explicitly import it nupm works as expected but if I don't import it before calling nupm it fails

**Comment by FMotalleb** [comment]
and now Its like the nupm is broken, I cannot install anything if I dont import std log before nupm calls

**Comment by fdncred** [comment]
sounds like a bug in nupm. things probably need to change there since the stdlib change a bit.

**Comment by FMotalleb** [comment]
well it fixed with [this PR](https://github.com/nushell/nupm/pull/103)
but idk what is going on

**Comment by sdmoralesma** [comment]
I have a script:

```nushell
#!/usr/bin/env nu
use std log

export-env {
    $env.NU_LOG_LEVEL = "INFO"
}

# [...] Commands using log
```
And failed updating to 0.99.0 it failed with the same error. The only way to fix it was to add the missing env vars as:

```nushell
#!/usr/bin/env nu
use std log

export-env {
    $env.NU_LOG_LEVEL = "INFO"
    $env.NU_LOG_FORMAT = $env.NU_LOG_FORMAT? | default "%ANSI_START%%DATE%|%LEVEL%|%MSG%%ANSI_STOP%" 
    $env.NU_LOG_DATE_FORMAT = $env.NU_LOG_DATE_FORMAT? | default "%Y-%m-%dT%H:%M:%S%.3f" 
}
```

**Comment by fdncred** [comment]
@ErichDonGubler I could be wrong here, but I thought I saw that the `use std/log` needed to be inside of the main but @NotTheDr01ds would know for sure.

**Comment by NotTheDr01ds** [comment]
Thanks for the cc, @fdncred.

Yes, when a module imports another module with an exported environment, the parent module doesn't automatically (re)export that environment.  There are ways to handle this - See https://www.nushell.sh/book/modules/creating_modules.html#export-env-runs-only-when-the-use-call-is-evaluated

The first option is useful when you only need the module in a single command in your module.  The second works if you need it in the global module scope.

**Comment by NotTheDr01ds** [comment]
I'm working on an update to the doc around this, but my laptop keyboard just went kaput. I'll be able to finish pushing it when I get back to my desktop.
