### ISSUE TITLE
A `shared queue` or similar

### ISSUE THREAD

**Issue by ghost** [nushell/nushell#14103]
### Related problem

When i write a more complex script i sometimes encounter the need to share data between multiple threads, create a self-feeding pipeline, or similar.

Examples:

* [webserver.nu](https://github.com/Jan9103/webserver.nu) runs netcat as webserver and has to feed the http-response into the stdin of the same process, whichs stdout contains the request.
* [my TUI-library experiment](https://github.com/Jan9103/potash) is currently single-threaded and therefore can only either update data on its own or accept user-input.
  * another `htop`-alternative
  * a scrollable log-viewer
  * a IRC-client
  * a statistic reader with both live-data and adjustable view (zoom, etc)
  * exiting any live-data-viewer
* some of my private scripts generate a bunch of tasks (which themselves generate new ones), which i would like to multi-thread (simple example: webcrawler)
* [numng](https://github.com/Jan9103/numng) (package manager; currently written in python) uses a que internally, which gets filled from all sorts of sub-functions by the que-handler (which would require a single giga-function in nu with `mut`)

### Describe the solution you'd like

A global queue with [locking](https://en.wikipedia.org/wiki/Lock_%28computer_science%29) and the following commands (name, etc are open for discussion):

```nu
# create a new global que and return its ID
def "globque create" []: nothing -> int {}

def "globque append" [que_id: int, object: any]: nothing -> nothing {}
def "globque append_all" [que_id: int, object: list<any>]: nothing -> nothing {}

def "globque is_empty" [que_id: int]: nothing -> bool {}

# returns null if no object is in the que
def "globque pop" [
  que_id: int
  --wait-for: duration  # time to wait and retry before returning `null`
]: nothing -> any {}

def "globque delete" [que_id: int]: nothing -> nothing {}
```

maybe a `--lock-timeout: duration` might be necessary.

this feels like a fairly nu-ish system to me (nu uses pipelines -> que; etc).

### ^mkfifo

```nu
let fifo = $"(mktemp --directory)/a"
^mkfifo $fifo

{"foo": "bar"} | to nuon --raw | save --append $fifo

let output = (^cat $fifo)  # cat does not try to follow
let output = (try { $output | from nuon } catch { null })  # handle "nothing yet written" return value
```

downsides to this:
* it is more involved
* it is platform specific (no windows / mac support; and requires external optional dependencies)
* `--wait-for`, etc are quite involved to implement
* if you try to split tasks between 2 threads this wont work (either you take everything or nothing)

### stor

while a stor table can be used as a list<any> (via `to nuon`) it has a few problems:
* it is way more involved to implement
* its hard to remove things safely (sql-escaping is hard)
* it feels far from a stable API (the only "documentation" is `--help`, and the PR; and `dataframe` has been deleted in the past)
* there is no locking between `read` and `delete`
* `sqlite` is a disable-able feature and not every user might have it

### Additional context and details

This is just a idea - feel free to decline it, discuss changes, etc

**Comment by fdncred** [comment]
My first idea was `stor`. I also don't think it's really disable-able. I guess if you turn off the sqlite feature and recompile on purpose it wouldn't work. not sure what would happen if that feature wasn't compiled in. i suspect several things would break.

My second/third idea was to use `$env.VAR` or `mut var` and roll-your-own locking. But I guess if "global" means across sessions, that wouldn't work. If it's supposed to be across nushell sessions, then it probably needs to be outside of nushell like with a file.

My vote would still be for stor i think.

**Comment by fdncred** [comment]
Do you happen to have a link to a repo in case others have this same need?

**Comment by fdncred** [comment]
nice work @Jan9103. seems like a good portion of the "secret sauce" is in the locking. i wonder if there's room for a locking command in nushell. 🤔 not sure how it would work either since it's not super useful by itself.
