### ISSUE TITLE
`return` inside closures sets `LAST_EXIT_CODE` to 1

### ISSUE THREAD

**Issue by JoaquinTrinanes** [nushell/nushell#14113]
### Describe the bug

Using `return` inside closures sets `$env.LAST_EXIT_CODE` to 1. This is only propagated when running the closure with `do --env` or inside hooks.

In practice, this means that having `direnv` hooked to the shell will make the prompt always show an error code.

### How to reproduce

~~1. Unset hooks (`$env.config.hooks.pre_prompt = []; $env.config.hooks.pre_execution = []`...)
2. Check that `$env.LAST_EXIT_CODE` is 0
3. `$env.config.hooks.pre_prompt = [{ return }]`
     The issue can be replicated with closures too (`$env.config.hooks.pre_prompt = [{|| return }]`)
4. `$env.LAST_EXIT_CODE` will always be 1~~

1. Ensure `$env.LAST_EXIT_CODE` is 0
2. `do --env { return }; $env.LAST_EXIT_CODE # returns 1`
    `do --env { return 0 }; $env.LAST_EXIT_CODE # returns 1 too`
    `do --env {|| return }; $env.LAST_EXIT_CODE # returns 1 too`
    `{ return }; $env.LAST_EXIT_CODE # works fine`

The real use-case is using `direnv`:

```nushell
$env.config.hooks.pre_prompt = (
    $env.config.hooks.pre_prompt?
    | default []
    | append {||
        let direnv = direnv export json | from json --strict | default {}

        if ($direnv | is-empty) {
            return # causes LAST_EXIT_CODE to be 1
        }
        $direnv
        | items {|key, value|
            {
                key: $key
                value: (do (
                    $env.ENV_CONVERSIONS?
                    | default {}
                    | get -i $key
                    | get -i from_string
                    | default {|x| $x}
                ) $value)
            }
        }
        | transpose -ird
        | load-env # removing the return statement and replacing this with 'try { load-env }' fixes the issue
    }
)
```

### Expected behavior

Don't set `LAST_EXIT_CODE` to 1 if there are no actual errors.

### Configuration

This is the latest version in `nixpkgs`, but it also happens in nightly (`9d25b2f29ab178c7dd514b90fe4575156f6a7b60`). The issue doesn't seem to happen in 0.98.0.

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.99.0                                                            |
| major              | 0                                                                 |
| minor              | 99                                                                |
| patch              | 0                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04) (built from a source tarball) |
| cargo_version      | cargo 1.81.0 (2dbb1af80 2024-08-20)                               |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash                                            |
| installed_plugins  |                                                                   |

**Comment by dcarosone** [comment]
For direnv, there is a workaround as here: https://github.com/nix-community/home-manager/pull/5971/files
A workaround for atuin in the issue linked just above.
