### ISSUE TITLE
`$env.LAST_EXIT_CODE` set by `return` in pre-prompt hooks

### ISSUE THREAD

**Issue by dcarosone** [nushell/nushell#14112]
### Describe the bug

When a pre-prompt hook uses an early return, $env.LAST_EXIT_CODE is set to 1, for .. rather unclear reasons.

Such hooks are installed by at least atuin and direnv hooks, and have been reported by users upgrading to 0.99. The typical symptom is that a prompt indicator turns red (such as with starship) to indicate failure of the previous command.

See, for example:
* https://github.com/atuinsh/atuin/issues/2423
* Discord discussion https://discord.com/channels/601130461678272522/601130461678272524/1296367021264736329

### How to reproduce

```nu
$env.config.hooks.pre_prompt = [{ return }]
```

minimal repro thanks to @K900

It doesn't seem to matter whether the return arg is empty or given, it always sets the error variable

### Expected behavior

Not set error, as in 0.98 and previously.

This seems to be something overlooked from #13954.
I do also like #13953 as a way to address the issue of errors in hooks more boradly, but I don't think it's directly relevant here.

### Configuration

(I'm yet to update and see the bug; have been helping to diagnose elsewhere)

**Comment by dcarosone** [comment]
ping @IanManske

**Comment by IanManske** [comment]
Sorry for that, should be fixed with #14120! A patch release will come tomorrow or the next few days.

**Comment by dcarosone** [comment]
i think this should be closed too
