### ISSUE TITLE
multiply operation overflowed (w/ int from sqlite)

### ISSUE THREAD

**Issue by AikoAtExact** [nushell/nushell#14124]
### Describe the bug

given the Chrome History sqlite database
I am trying to make sense of the `last_visit_time`
resource: https://superuser.com/questions/602252/can-chrome-browser-history-be-exported-to-an-html-file

no matter where I insert `into int` to force integer math,
casting into `float` as suggested does work, so there is a workaround.

> open History | query db "select * from urls order by last_visit_time desc" | update last_visit_time { |r| (($r.last_visit_time - 11_644_473_600_000_000 | into float) * 1_000) |into int -s | into datetime } | explore

### How to reproduce

1. make a copy of your Chrome History db as described: https://superuser.com/questions/602252/can-chrome-browser-history-be-exported-to-an-html-file
2. start nushell
```
> open History | query db "select * from urls order by last_visit_time desc" | update last_visit_time { |r| ((($r.last_visit_time | into int -s) - 11_644_473_600_000_000 | into int -s) * 1_000) |into int -s | into datetime } | explore
Error: nu::shell::operator_overflow

  × Operator overflow.
   ╭─[entry #69:1:192]
 1 │ open History | query db "select * from urls order by last_visit_time desc" | update last_visit_time { |r| ((($r.last_visit_time | into int -s) - 11_644_473_600_000_000 | into int -s) * 1_000) |into int -s | into datetime } | explore
   ·                                                                                                                                                                                                ┬
   ·                                                                                                                                                                                                ╰── multiply operation overflowed
   ╰────
  help: Consider using floating point values for increased range by promoting operand with 'into float'. Note: float has reduced precision!

### Expected behavior

```
> ((13_373_733_814_753_694 / 1_000_000) - 11_644_473_600) * 1_000_000_000 | into int | into datetime
Fri, 18 Oct 2024 14:03:34 +0000 (an hour ago)
> ((13_373_733_814_753_694 / 1_000) - 11_644_473_600_000) * 1_000_000 | into int | into datetime
Fri, 18 Oct 2024 14:03:34 +0000 (an hour ago)
> ((13_373_733_814_753_694 - 11_644_473_600_000_000) * 1_000) | into datetime
Fri, 18 Oct 2024 14:03:34 +0000 (an hour ago)
> open History | query db "select * from urls order by last_visit_time desc" | update last_visit_time { |r| (($r.last_visit_time - 11_644_473_600_000_000) * 1_000) | into datetime } | explore

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.98.0                                                            |
| major              | 0                                                                 |
| minor              | 98                                                                |
| patch              | 0                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04) (built from a source tarball) |
| cargo_version      | cargo 1.81.0 (2dbb1af80 2024-08-20)                               |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash                                            |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
This seems to work for me.
```nushell
open ~/Desktop/History | 
  get urls | 
  sort-by last_visit_time --reverse | 
  where last_visit_time != 0 | 
  first 10 | 
  update last_visit_time {|d| (($d.last_visit_time / 1_000_000) - 11644473600) * 1_000_000_000 | math round | into datetime}
```

**Comment by AikoAtExact** [comment]
Is it possible for the error message to inform the user what values were involved triggering the overflow?

**Comment by fdncred** [comment]
error messages can be changed but i'm not sure what a better error message would look like. not saying our can't be better but i'm not sure what it would say.

**Comment by AikoAtExact** [comment]
in this case.. it looks like the error parser can figure out that it went wrong doing a multiplication.. 
perhaps the message can include the multiplier and multiplicand values?

> multiply operation overflowed (- 11_644_473_600_000_000 * 1_000)

**Comment by AikoAtExact** [comment]
I guess.. the values do not need to be part of the message... perhaps it can be as simple as doing dump of the current stackframe values... the reader/debugger should be able to figure out which values are being used to do the computation/evaluation..

I agree... someone... in another issue ... ;)
