### ISSUE TITLE
potential parser bug when a bare string contains the "#" character

### ISSUE THREAD

**Issue by suimong** [nushell/nushell#14129]
### Describe the bug

When using `nix run` command with a custom flake, I observed some parsing descrepancies.

### How to reproduce

1. `nix run nixpkgs#hello` runs fine.
2. `nix run nur#hello` causes nushell to produce a parsing error. (`nur` is just a relative path to a directory that is a nix flake)
3. `nix run /path/to/nur#hello` causes nushell to produce a parsing error.
4. `cd nur; nix run .#hello` works fine.
5. ` nix run "/home/ben/Depot/nur#hello-benny"` works fine.

Here's a screenshot of running the above on my machine:

![image](https://github.com/user-attachments/assets/be6342e4-fa3e-4dc3-83b2-d55b1ebc9c85)

### Expected behavior

Correctly parsing `nur#hello`, `/path/to/nur#hello` as normal string. Since the parsing error `expects '` after `#`, I suspect it has something to do with the raw string feature?

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.98.0                                                            |
| major              | 0                                                                 |
| minor              | 98                                                                |
| patch              | 0                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06) (built from a source tarball) |
| cargo_version      | cargo 1.80.0 (376290515 2024-07-16)                               |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash                                            |
| installed_plugins  | formats 0.98.0, gstat 0.98.0, polars 0.98.0, query 0.98.0         |

**Comment by sholderbach** [comment]
Good sleuthing that the pathiness may play into that, here!

Vaguely related issues with `#` in strings leading to problems in other cases:

- https://github.com/nushell/nushell/issues/10327
- https://github.com/nushell/nushell/issues/13810

**Comment by hustcer** [comment]
Closed by https://github.com/nushell/nushell/pull/14616
