### ISSUE TITLE
Apply `display_output` hook to byte streams

### ISSUE THREAD

**Issue by KAAtheWiseGit** [nushell/nushell#14137]
### Related problem

As was discovered in #13444, `display_output` doesn't apply to byte streams.  This can be problematic for a few usecases, as it prevents hooks from working on external commands and `open --raw`.

https://github.com/nushell/nushell/blob/8c8f795e9e8da080a1a3e1f22af5869d3c6dacd5/crates/nu-cli/src/util.rs#L284-L298

### Describe the solution you'd like

I agree with @fdncred in that `display_hook` should be applied to byte streams too.  I think the distinction between byte streams and strings is a bit arbitrary when it comes to displaying, since both will have to be collected to be printed.

### Describe alternatives you've considered

If there's a fundamental difference between streams and values I'm missing here, I think a separate `display_stream_output` hook could be added.

### Additional context and details

See #13444

**Comment by sholderbach** [comment]
What are the (intended) interactions with the output of externals.
If I understand our code correctly, they should be writing to the system STDOUT/STDERR directly if no redirection is present. When they redirect via a `|` to an interal their output gets piped with a `ByteStream` and for file redirection of externals again the OS redirection primitives are used. 
Is there a case where we would unexpectedly move external output to `display_output` and things get weird?

**Comment by IanManske** [comment]
As @sholderbach alluded to, TTY applications must have their stdout set to the terminal. But, in order to redirect the output of an external into a display hook, the output must be set to an OS pipe (i.e., not the terminal). This will probably break a lot of things.

I think it's fine to maybe send the other kinds of bytestreams (file, reader) to the display hook, but child processes specifically will be problematic.

**Comment by IanManske** [comment]
Ok, #14141 coincidentally works, because the display output hook does not set a redirection. So, external commands will still output to the terminal, but the other bytestream cases will be sent to the display hook which I guess makes sense.
