### ISSUE TITLE
Inconsistent `join` behavior for table vs list-of-records

### ISSUE THREAD

**Issue by aionescu** [nushell/nushell#14134]
### Describe the bug

`join` produces different output based on the type/format of its second argument.

### How to reproduce

At the REPL:

```nushell
> [[a b]; [1 2]] | join [[a c]; [1 3]] a
╭────────────╮
│ empty list │
╰────────────╯

> [[a b]; [1 2]] | join [{ a: 1 c: 3}] a
╭───┬───┬───╮
│ a │ b │ c │
├───┼───┼───┤
│ 1 │ 2 │ 3 │
╰───┴───┴───╯
```

### Expected behavior

I expected both calls to `join` to return the same output (a non-empty table), because the arguments passed to them are equal:

```nushell
> [[a c]; [1 3]] == [{ a: 1 c: 3}]
true
```

As noted by @fdncred on Discord, `join` returns the expected output if the tables are `let`-bound first:

```nushell
> let a = [[a b]; [1 2]]
> let b = [[a c]; [1 3]]
> $a | join $b a
╭───┬───┬───╮
│ a │ b │ c │
├───┼───┼───┤
│ 1 │ 2 │ 3 │
╰───┴───┴───╯
```

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.98.0                                                           |
| major              | 0                                                                |
| minor              | 98                                                               |
| patch              | 0                                                                |
| branch             | makepkg                                                          |
| commit_hash        | 6e1e824473e15eba246e1c43704c5d88fa237a17                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04) (Arch Linux rust 1:1.81.0-1) |
| cargo_version      | cargo 1.81.0 (2dbb1af80 2024-08-20)                              |
| build_time         | 2024-09-18 13:20:08 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | default, sqlite, trash                                           |
| installed_plugins  |                                                                  |

**Comment by sholderbach** [comment]
That seems to be the following issue in action:

- https://github.com/nushell/nushell/issues/13537
