### ISSUE TITLE
Historical messages scroll upwards when any key is pressed

### ISSUE THREAD

**Issue by road2coder** [nushell/nushell#14143]
### Describe the bug

Historical messages such as output, error, and prompts scroll upwards and disappear when any key is pressed. Scrolling the mouse forward makes them visible again.

https://github.com/user-attachments/assets/adfb8ad6-01c2-4c2b-b109-1d0b9476f3bc

### How to reproduce

1. run any commad
2. press some keys

### Expected behavior

Historical messages are always visible and not move.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.99.1                                   |
| major              | 0                                        |
| minor              | 99                                       |
| patch              | 1                                        |
| branch             |                                          |
| commit_hash        | 8812072f065be283df3e9a81f3945d0364f2f247 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10)      |
| rust_channel       | 1.79.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.79.0 (ffa9cf99a 2024-06-03)      |
| build_time         | 2024-10-20 19:44:31 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
It's hard to see with such a tiny screen but I'm assuming you're using WezTerm on Windows. If so, this is a known issue. The current suggestion it to turn off osc133.

**Comment by road2coder** [comment]
> It's hard to see with such a tiny screen but I'm assuming you're using WezTerm on Windows. If so, this is a known issue. The current suggestion it to turn off osc133.

I'm exactly using WezTerm on Windows. Setting `$env.config.shell_integration.osc133` to false works. Thank you!
