### ISSUE TITLE
Capture output using $(foo) or `foo`

### ISSUE THREAD

**Issue by JesterOrNot** [nushell/nushell#1415]
**Is your feature request related to a problem? Please describe.**
In bash you can capture the stdout of a command for reuse by using `$(foo)` or `` `foo` ``nu as far as I know does not support this
**Describe the solution you'd like**
Add support for capturing stdout for use later
**Describe alternatives you've considered**
Create another system

**Comment by thegedge** [comment]
Note that many other shells are very string-oriented, whereas nushell is meant to be stream-oriented. My guess is that a lot of the use cases for stdout capture will be handled by blocks.

I think we'll need to establish the use cases for stdout capture and translate these to nu.
