### ISSUE TITLE
When using `parse`, there is a `nu::parser::extra_positional` error 

### ISSUE THREAD

**Issue by j1m-ryan** [nushell/nushell#14169]
### Describe the bug

I am trying to use the built in `parse` function, but get `nu::parser::extra_positional` whenever I supply an argument. I believe this is a bug as my usage is based off the docs.

### How to reproduce

From the example in the docs here.
https://www.nushell.sh/commands/docs/parse.html
1. open up a terminal running nushell
2. run `"hi there" | parse "{foo} {bar}"`

output
```nu
~[I] "hi there" | parse "{foo} {bar}"
Error: nu::parser::extra_positional

  × Extra positional argument.
   ╭─[entry #9:1:20]
 1 │ "hi there" | parse "{foo} {bar}"
   ·                    ──────┬──────
   ·                          ╰── extra positional argument
   ╰────
  help: Usage: parse
```

### Expected behavior

I would expect parse to be able to take an argument, like in the docs. eg this
```nu
> "hi there" | parse "{foo} {bar}"
╭───┬─────┬───────╮
│ # │ foo │  bar  │
├───┼─────┼───────┤
│ 0 │ hi  │ there │
╰───┴─────┴───────╯
```

### Configuration

| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.99.1                                         |
| major              | 0                                              |
| minor              | 99                                             |
| patch              | 1                                              |
| branch             |                                                |
| commit_hash        |                                                |
| build_os           | macos-aarch64                                  |
| build_target       | aarch64-apple-darwin                           |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04) (Homebrew) |
| cargo_version      | cargo 1.81.0                                   |
| build_time         | 2024-10-20 02:45:05 +00:00                     |
| build_rust_channel | release                                        |
| allocator          | mimalloc                                       |
| features           | default, sqlite, trash                         |
| installed_plugins  |                                                |

**Comment by weirdan** [comment]
Are you sure you don't override the `parse` command somewhere in your config (or anything imported from the config)?

**Comment by j1m-ryan** [comment]
Sorry that was it! Thanks
