### ISSUE TITLE
windows encoding / code page 850 not supported

### ISSUE THREAD

**Issue by mbyt** [nushell/nushell#14168]
### Describe the bug

On a European Windows 11, the default code page is 850 https://en.wikipedia.org/wiki/Code_page_850 (this can be checked via the `chcp` https://ss64.com/nt/chcp.html command).

This is mostly compatible with ASCII, however, when there are German "Umlaute" like "Abhören" in the output, it is not compatible to ASCII any more, thus commands like the following fail in nushell:
```nushell
nu> netstat -o -an -p TCP | lines
Error: nu::parser::non_utf8

  × Non-UTF8 string
   ╭─[entry #23:1:1]
1 │ netstat -o -an -p TCP | lines
   · ───┬───
   ·    ╰── non-UTF8 string
   ╰────
  help: see `decode` for handling character sets other than UTF-8

~ ❯
```

Thus, one needs to decode the 850 code page / encoding. However, I cannot do
```nushell
netstat -o -an -p TCP | decode DOS-850 | lines
```
or variants, as the 850 is not supported by https://docs.rs/encoding_rs/latest/encoding_rs/index.html#statics, which states: "_For single-byte DOS encodings beyond the ones supported by the Encoding Standard, there is the [oem_cp](https://crates.io/crates/oem_cp) crate_".

Indeed in https://crates.io/crates/oem_cp there is the 850 encoding, however, unfortunately this crate is not included in nushell (I checked the Cargo.lock file).

Could code page 850 be supported by nushell?

### How to reproduce

* default European windows 11, e.g. German language
* netstat -o -an -p TCP | lines

### Expected behavior

No error when piping commands with "Umlaute"

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.99.1                                   |
| major              | 0                                        |
| minor              | 99                                       |
| patch              | 1                                        |
| branch             |                                          |
| commit_hash        | 8812072f065be283df3e9a81f3945d0364f2f247 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10)      |
| rust_channel       | 1.79.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.79.0 (ffa9cf99a 2024-06-03)      |
| build_time         | 2024-10-20 19:44:43 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  | query 0.98.0                             |

**Comment by weirdan** [comment]
Wouldn't it be easier for you to change the codepage to UTF-8 in `config.nu` (`chcp 65001`)? This way you wouldn't have to decode all externals output explicitly.

**Comment by mbyt** [comment]
Hm, unclear why, but it doesn't work in a nushell window if I call chcp 65001 beforehand:

![image](https://github.com/user-attachments/assets/0842befa-8bc0-48a3-abc9-fbafc25109ae)

**Comment by fdncred** [comment]
I use set the code page globally in Windows following [this link](https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window), but that may not prevent other commands from returning non-utf8 text, which I assume is what netstat could be doing.

I'm not opposed to allowing the decode command to support the oem_cp crate. I guess we'd just need to test if a decoding exists and if it doesn't then check if the oem_cp crate has it?

**Comment by mbyt** [comment]
@fdncred thanks for thinking about this. Here is an example file of the netstat example above / 850 encoding  [netstat_head_codepage_850_german.txt](https://github.com/user-attachments/files/17538633/netstat_head_codepage_850_german.txt)

**Comment by mbyt** [comment]
@fdncred that was fast, 💛 / thanks a lot for supporting the OEM / DOS 850 encoding in nushell!
