### ISSUE TITLE
Dynamic `overlay use`

### ISSUE THREAD

**Issue by Tazoeur** [nushell/nushell#14164]
### Describe the bug

Hello,

I am trying to create a function that will help me write some boilerplate when trying to activate a Python virtualenv.
I must say that I am a beginner with nu, and I tried to do this little function as an exercise.
Still, if this error was trivial to solve or if a workaround was mentioned in the (great) documentation, I think that I wouldn't be filling this issue.

This is related to https://github.com/nushell/nushell/discussions/12206

### How to reproduce

```nu
def venv_activate [] {
    use std log
    let venvs = (ls | where type == dir | where ($it.name | str contains "venv") | get name)
    if ( $venvs | is-empty ) {
        log warning "There are no virtualenv in this folder"
    } else {
        if ( ($venvs | length) == 1) {
            let venv_name = ($venvs | first)
            let venv_activation_file = ($env.pwd | path join $venv_name bin activate.nu)
            overlay use $venv_activation_file as $venv_name
        } else {
            log info "There are multiple venvs here:"
            $venvs | each {|v| log info $"\t* ($v)"}
            log info "Either use `overlay use <venv>/bin/activate.nu`, either update this script."
        }
    }
}
```
gives me the beautiful error:
```
Error:   × Error: nu::shell::not_a_constant
  │
  │   × Not a constant.
  │      ╭─[/home/me/.dotfiles/nushell/config.nu:970:25]
  │  969 │             let venv_activation_file = ($env.pwd | path join $venv_name bin activate.nu)
  │  970 │             overlay use $venv_activation_file as $venv_name
  │      ·                         ──────────┬──────────
  │      ·                                   ╰── Value is not a parse-time constant
  │  971 │         } else {
  │      ╰────
  │   help: Only a subset of expressions are allowed constants during parsing. Try using the 'const' command or typing the value literally.
  │
     ╭─[/home/me/.dotfiles/nushell/config.nu:970:13]
 969 │             let venv_activation_file = ($env.pwd | path join $venv_name bin activate.nu)
 970 │             overlay use $venv_activation_file as $venv_name
     ·             ──────────────────┬─────────────────
     ·                               ╰── Encountered error during parse-time evaluation
 971 │         } else {
     ╰────
```

### Expected behavior

I would have expected the virtualenv to be correctly loaded. since it's working when I do it manually with `overlay add ./venv/bin/activate.nu`

### Configuration

| key                | value                                                                 |
| ------------------ | --------------------------------------------------------------------- |
| version            | 0.99.1                                                                |
| major              | 0                                                                     |
| minor              | 99                                                                    |
| patch              | 1                                                                     |
| branch             |                                                                       |
| commit_hash        |                                                                       |
| build_os           | linux-x86_64                                                          |
| build_target       | x86_64-unknown-linux-gnu                                              |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04)                                   |
| rust_channel       | stable-x86_64-unknown-linux-gnu                                       |
| cargo_version      | cargo 1.81.0 (2dbb1af80 2024-08-20)                                   |
| build_time         | 2024-10-21 20:19:16 +02:00                                            |
| build_rust_channel | release                                                               |
| allocator          | mimalloc                                                              |
| features           | default, sqlite, trash                                                |
| installed_plugins  | formats 0.99.1, gstat 0.99.1, inc 0.99.1, polars 0.99.1, query 0.99.1 |

**Comment by NotTheDr01ds** [comment]
This is, unfortunately, the correct behavior.

`overlay use` is a parser keyword. Copying from the help:

> This command is a parser keyword. For details, check: https://www.nushell.sh/book/thinking_in_nu.html

Short summary:

Nushell handles each file in two parts:

* Parsing
* Evaluation

Parser keywords like `use`, `source`, etc. can only accept constants as arguments because the *evaluation* phase hasn't occurred at that point.

> it's working when I do it manually with `overlay add ./venv/bin/activate.nu`

There you are using a constant.  If you were to try the following in the REPL, you'll get the same error. It will even be caught before you hit <kbd>Enter</kbd> with the syntax highlighting.

```nu
let module_name = "abc"
overlay use $abc
```

**Comment by Tazoeur** [comment]
Hello @NotTheDr01ds, thank you very much for the explanation provided.

Even though I now understand why the dynamic `overlay use` isn't possible, I still think it's worth the drawback of losing the definitions of the current session.

Here's the updated version, with the new subshell trick.

```nu
# Ask user input in order to chose an element from a list
def chose_one_in_list [xs: list<string>, message: string = "Type your choice (Ctrl+c to quit)"] -> string {
    $xs | enumerate | each { |elt| print $"\t * [($elt.index + 1)] ($elt.item)" }
    mut value = 0
    mut is_valid = false

    while not $is_valid {
        print $message
        let choice = (input)
        try {
            $value = ($choice | into int)
            $value = $value - 1
            if ($value < 0 ) or ($value >= ($xs | length) ) {
                print "[error] invalid index provided."
            } else {
                $is_valid = true
            }
        } catch {
            print "[error] expecting integer."
        }
    }

    $xs | get $value

}
# Activate a python virtual environment
#
# If a folder containing `venv` is found as a child of the current dir,
# this script is searching for the `<folder>/bin/activate.nu` script.
# If multiple folder are found, the user is asked to chose which one
# he wants to use.
def venv_activate [] {
    use std log
    let venvs = (ls | where type == dir | where ($it.name | str contains "venv") | get name)
    if ( $venvs | is-empty ) {
        log warning "There are no virtualenv in this folder"
    } else {
        if ( ($venvs | length) == 1) {
            let venv_name = ($venvs | first)
            let venv_activation_file = ($env.pwd | path join $venv_name bin activate.nu)
            nu -e $"overlay use ($venv_activation_file) as ($venv_name)"
        } else {
            print "The following venvs are available:"
            let choice = chose_one_in_list $venvs
            let venv_activation_file = ($env.pwd | path join $choice bin activate.nu)
            nu -e $"overlay use ($venv_activation_file) as ($choice)"
        }
    }
}
```

**Comment by dgroomes** [comment]
(I know this issue is closed but I got here from search and will leave my tidbit)

I have the same scenario, and I use a clever abuse of Nushell hooks to make this work. It's a  **self-erasing hook**: <https://github.com/dgroomes/my-software/blob/a86b3087f36c57f50063b16b5dc929985a4d6de8/nushell/config.nu#L79>

```
const ACTIVATE_DO = r#'
# ERASE ME
overlay use --prefix do.nu
let hooks = $env.config.hooks.pre_prompt
let filtered = $hooks | where ($it | describe) != "string" or $it !~ "# ERASE ME"
$env.config.hooks.pre_prompt = $filtered
'#

# Activate a 'do.nu' script as an overlay module.
#
# By convention, I put 'do.nu' scripts in projects and this lets me compress my workflow. The 'do activate' command
# activates the local 'do.nu' script as a module using Nushell's *overlays*. Because of Nushell's parse-evaluate model, this
# is actually pretty difficult to do, so we can abuse Nushell hooks to do this.
export def --env "do activate" [] {
    if not ("do.nu" | path exists) {
        error make --unspanned { msg: "No 'do.nu' script found." }
    }

    # Here is the tricky part. Register a pre_prompt hook that will load the 'do.nu' script and then the hook will
    # erase itself. I have details about this pattern in my nushell-playground repository: https://github.com/dgroomes/nushell-playground/blob/b505270046fd2c774927749333e67707073ad62d/hooks.nu#L72

    $env.config = ($env.config | upsert hooks.pre_prompt {
        default [] | append $ACTIVATE_DO
    })
}

export alias da = do activate
```

In the end, I get the concise `da` alias I want and there's no shortcomings (although I wouldn't be surprised if this breaks in future releases because modifying hooks from a hook seems like undefined behavior).
