### ISSUE TITLE
compiler fails when using $in variable in a script

### ISSUE THREAD

**Issue by amkhlv** [nushell/nushell#14178]
### Describe the bug

Trying to run this shell script :

```
#!/usr/bin/env nu
let x = $in
echo $x
```

results in a strange error message:

 ```
1 │ ╭─▶ #!/usr/bin/env nu
 2 │ │   
 3 │ │   let x = $in
 4 │ │   
 5 │ │   echo $x
 6 │ ├─▶ 
   · ╰──── block is missing compiled representation
   ╰────
  help: the IrBlock is probably missing due to a compilation error

```
The workaround is to use   `let x = cat `  instead of `let x = $in` 

### How to reproduce

using `nu` version 0.99.1, run the above script

### Expected behavior

I expect either code run, or produce a legible error message.

### Configuration

NixOs, nu version 0.99.1 installed by running `cargo install nu`

**Comment by 132ikl** [comment]
Here's the output with `$env.NU_DISABLE_IR = 1`:
```
Error: nu::shell::variable_not_found

  × Variable not found
   ╭─[/home/rose/tmp/test.nu:3:9]
 2 │ 
 3 │ let x = $in
   ·         ─┬─
   ·          ╰── variable not found
 4 │ echo $x
   ╰────
```

Looks like you need a main function for $in to work:

```
def main [] {
    let x = $in
    echo $x
}
```

Also, I'm guessing you'll want to use the `--stdin` option, meaning the whole script would look like this:

```
#!/usr/bin/env -S nu --stdin

def main [] {
    let x = $in
    echo $x
}
```

**Comment by fdncred** [comment]
I wouldn't expect $in to be available in a shebang situation as the first line. Maybe I'm wrong?

**Comment by amkhlv** [comment]
I got it. Thank you !

**Comment by amkhlv** [comment]
It was my mistake.
