### ISSUE TITLE
Return syntax parsing is buggy

### ISSUE THREAD

**Issue by RGBCube** [nushell/nushell#14170]
Works (normal):

```nu
def x []: number -> string { "a" }
```

Requires `-> returnType` (it shouldn't):

```nu
def x []: number {}
```

Gets ignored totally (should raise a type error instead):

```nu
def x [] -> string { 1 }
```

**Comment by fdncred** [comment]
Seems like the second example is working the way it should by providing an error. I'm not sure what you mean by saying, "it shouldn't".

**Comment by fdncred** [comment]
Good point @sgvictorino. I forgot about that documentation. Let me ask the team.

**Comment by kubouch** [comment]
I think 2 shouldn't be allowed because it looks like an output type. 3 is also problematic because people often think of it as `nothing -> string` while in fact it is `any -> string`. IMO the parsing just needs to be tightened and throw more errors at unexpected syntax.

**Comment by RGBCube** [comment]
> Seems like the second example is working the way it should by providing an error. I'm not sure what you mean by saying, "it shouldn't".

I expected it to work and behave as `: string -> any`, but @kubouch has a fair point. It's too ambiguous and people will get confused over both `: T` and `-> T` being valid.

What about this syntax instead?

```nu
def instring-outnumber string -> [] -> number {
  into number
}
```

I think it makes more sense and is clearer, but it looks funny. But I strongly believe that the input type shouldn't be there between the return type and argument list.

**Comment by fdncred** [comment]
I'd be satisfied with strict checking on input output types. `def name []: in_type -> out_type {}`. It's either all there or none of it's there and assumed as any.

**Comment by NotTheDr01ds** [comment]
Git blame on that doc shows me.  I think I just moved it from somewhere else, but I should have checked the second one at least.

The third example is due to #11266 (and possibly others before it).  I've been bitten before by that as well. We should at least fix the doc on that.  I'll put in a PR in that repo.

**Comment by kubouch** [comment]
That "funny" syntax indeed looks a bit confusing, but more importantly, it prevents specifying multiple in/out type pairs.

I'd also vote for disallowing the "shortened" variants. Extensions of the syntax can be of course discussed as a separate problem, but I'd first focus on making the current syntax parsed correctly.
