### ISSUE TITLE
Quit History Search (Ctrl+r) via Emacs' standard Ctrl+g

### ISSUE THREAD

**Issue by ppena-LiveData** [nushell/nushell#14177]
### Related problem

While searching through command history, it would be much nicer to be able to hit Ctr+g (Emacs standard abort keyboard shortcut) instead of having to hit the Escape key to quit out of the History Menu.

### Describe the solution you'd like

Hitting Ctrl+g while the History Menu is up would close the dialog.

**Comment by fdncred** [comment]
Nushell allows you to change key bindings in the config.nu. Have you tried that?
