### ISSUE TITLE
`clear` command in series of commands breaks the output

### ISSUE THREAD

**Issue by postpersonality** [nushell/nushell#14176]
### Describe the bug

Doing `clear; echo "111\n222\n333"` breaks screen output.
![image](https://github.com/user-attachments/assets/4436fe69-ae80-4022-8444-05d5795597c6)
![image](https://github.com/user-attachments/assets/0e9dbacc-a11d-470a-8c89-1d0226aebef8)

### How to reproduce

1. Open up a new terminal
2. Enter `clear; echo "111\n222\n333"`

### Expected behavior

The screen is clear and I see 111, 222, 333 at their own lines without garbage from buffer.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.99.1                                   |
| major              | 0                                        |
| minor              | 99                                       |
| patch              | 1                                        |
| branch             |                                          |
| commit_hash        | 0586b37d03031ae8c3110ea2b51cacaad46c7cdc |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.82.0 (f6e511eec 2024-10-15)      |
| rust_channel       | 1.82.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.82.0 (8f40fc59f 2024-08-21)      |
| build_time         | 2024-10-21 16:47:44 +03:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  |                                          |

**Comment by NotTheDr01ds** [comment]
I can reproduce, and I think I have a fix for it.  Just double-checking it on Windows and then I'll submit the PR for review.
