### ISSUE TITLE
"get foo.bar" does not expand arrays, while "get foo | get bar" does

### ISSUE THREAD

**Issue by kvrhdn** [nushell/nushell#1418]
**Describe the bug**
If you use a nested selector with `get` (i.e. `foo.bar`), arrays do not get expanded correctly. Resulting in tables with header `<value>`.
If you use `get foo | get bar` the array is expanded correctly.

**To Reproduce**
I encountered this problem when dealing with a JSON with nested arrays, a simplified example:
```json
{
    "services": [
        {
            "deployments": [
                {
                    "id": "1"
                },
                {
                    "id": "2"
                }
            ]
        }
    ]
}
```

You can `open` this JSON:
```
❯ open test.json
───┬────────────────
 # │ services 
───┼────────────────
 0 │ [table 1 rows] 
───┴────────────────

❯ open test.json | debug
(services=[(deployments=[(id="1") (id="2")])])
```

You can select a field that contains an array using `get`:

```
❯ open test.json | get services
───┬────────────────
 # │ deployments 
───┼────────────────
 0 │ [table 2 rows]
───┴────────────────

❯ open test.json | get services | debug
(deployments=[(id="1") (id="2")])
```

Now, if you try to `get` a level deeper:
```
❯ open test.json | get services.deployments
───┬────────────────
 # │ <value> 
───┼────────────────
 0 │ [table 2 rows] 
───┴────────────────

❯ open test.json | get services.deployments | debug
[(id="1") (id="2")]
```

Notice how `get` is not able to expand the array into a table, despite both elements having the same field `id`. We end up with a header `<value>` which can not be `get` further.

A chain of `get`s is able to do this:
```
❯ open test.json | get services | get deployments
───┬────
 # │ id 
───┼────
 0 │ 1 
 1 │ 2 
───┴────

❯ open test.json | get services | get deployments | debug
───┬──────────
 # │ <value> 
───┼──────────
 0 │ (id="1") 
 1 │ (id="2") 
───┴──────────
```

... and `echo`ing the result also fixes this:
```
❯ open test.json | get services.deployments | echo $it
───┬────
 # │ id 
───┼────
 0 │ 1 
 1 │ 2 
───┴────
```

**Expected behavior**
I would expect `get foo.bar` to be able to expand arrays so the column header shows `id`.
Additionally, I would expect `get foo.bar` and `get foo | get bar` to do the same thing.

**Screenshots**
N/A

**Configuration (please complete the following information):**
macOS 10.15.2
nu 0.9.1 (built from master)

**Comment by andrasio** [comment]
@kvrhdn You can mix and match your column path with integers and regular strings. Integers fetches the nth row, while regular strings fetches by column.

In your case you'd do: `open test.json | get services.deployments.0.0.id` to get the `id` field from the first under `deployments`.

deployments has 1 row that happens to be a table so: `get services.deployments.0` gets that table.

The result of that has two rows so you'd need to do: `get services.deployments.0.0` to get the id objects.

**Comment by andrasio** [comment]
@kvrhdn Try also: `get services.0.deployments`

**Comment by andrasio** [comment]
@kvrhdn If you have column names that contain spaces, you can also enclose them in double quotes for the column path: `get column."another spaced column"`

**Comment by kvrhdn** [comment]
Ah cool! That's how I can make that work.

So, is it right that I can use an index if the the pipeline contains something like `[table x rows]`?

I can get it working now, but it still feels a bit weird. I.e., these return the same output:
```
❯ open test.json | get services
❯ open test.json | get services.0
───┬────────────────
 # │ deployments 
───┼────────────────
 0 │ [table 2 rows] 
───┴────────────────
```
But this isn't legal:
```
❯ open test.json | get services | get 0
error: No rows available
- shell:1:37
1 | open test.json | get services | get 0
  |                                     ^ A row at '0' can't be indexed.
- shell:1:37
1 | open test.json | get services | get 0
  |                                     - Appears to contain columns. Columns available: deployments
```

**Comment by andrasio** [comment]
@kvrhdn You can use an index operator yes, by indicating numbers in the column path. If Nu sees you are trying to fetch by index but it's not a table it will error to you. Same goes if you try to fetch by string to something other than a row with columns.

You get the error because we don't allow indexes to `get` as the first path member in the column path. For that you use `nth` command.

**Comment by kvrhdn** [comment]
Okay, makes sense.

I'll have to get used to the model a bit more but it feels pretty powerful in general. And the error message will gently guide when I make mistakes 🙂

**Comment by andrasio** [comment]
@kvrhdn Re-opening :)

I think we should add a better error message when you try a number as the first path member.
