### ISSUE TITLE
`math round --precision` does not work with precision above 2

### ISSUE THREAD

**Issue by umnikos** [nushell/nushell#14185]
### Describe the bug

With `--precision` values above 2, `math round` acts exactly the same as if it was passed `--precision 2`.

### How to reproduce

```
~ $ [ 1.5913467 31.04149 ] | math round
 0    2 
 1   31 
~ $ [ 1.5913467 31.04149 ] | math round --precision 1
 0    1.60 
 1   31.00 
~ $ [ 1.5913467 31.04149 ] | math round --precision 2
 0    1.59 
 1   31.04 
~ $ [ 1.5913467 31.04149 ] | math round --precision 3
 0    1.59 
 1   31.04 
~ $ [ 1.5913467 31.04149 ] | math round --precision 4
 0    1.59 
 1   31.04 
~ $ [ 1.5913467 31.04149 ] | math round --precision 100
 0    1.59 
 1   31.04 
```

### Expected behavior

This should have been the output instead:
```
~ $ [ 1.5913467 31.04149 ] | math round
 0    2 
 1   31 
~ $ [ 1.5913467 31.04149 ] | math round --precision 1
 0    1.60 
 1   31.00 
~ $ [ 1.5913467 31.04149 ] | math round --precision 2
 0    1.59 
 1   31.04 
~ $ [ 1.5913467 31.04149 ] | math round --precision 3
 0    1.591 
 1   31.041 
~ $ [ 1.5913467 31.04149 ] | math round --precision 4
 0    1.5913 
 1   31.0415 
~ $ [ 1.5913467 31.04149 ] | math round --precision 100
 0    1.5913467 
 1   31.04149 
```

### Configuration

| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.99.0                                         |
| major              | 0                                              |
| minor              | 99                                             |
| patch              | 0                                              |
| branch             |                                                |
| commit_hash        |                                                |
| build_os           | linux-x86_64                                   |
| build_target       | x86_64-unknown-linux-gnu                       |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04) (Homebrew) |
| cargo_version      | cargo 1.81.0                                   |
| build_time         | 2024-10-15 19:01:08 +00:00                     |
| build_rust_channel | release                                        |
| allocator          | mimalloc                                       |
| features           | default, sqlite, trash                         |
| installed_plugins  |                                                |

**Comment by weirdan** [comment]
Looks like `table` (the default output hook) does its own rounding.

**Comment by weirdan** [comment]
See https://github.com/weirdan/nushell/blob/e911ff4d67e5342f325d825745f6f5c01504d6e6/crates/nu-utils/src/sample_config/default_config.nu#L239

**Comment by umnikos** [comment]
Oh, fair enough.
