### ISSUE TITLE
Should nu add trailing newline to scalar values?

### ISSUE THREAD

**Issue by kbd** [nushell/nushell#1419]
```shell
$ cat test.json
{"foo":"bar"}
$ nu -c 'open test.json | get foo'
bar
$ nu -c 'open test.json | get foo' | xxd
00000000: 6261 720a                                bar.
```

I would not expect 'bar' to be returned with a trailing newline. Even if I use the built-in 'trim' it still has a newline:

```shell
$ nu -c 'open test.json | get foo | trim' | xxd
00000000: 6261 720a                                bar.
```

**Comment by thegedge** [comment]
Yeah, this was a hack (https://github.com/nushell/nushell/pull/1391) to fix another issue (#1355).

We'll definitely be fixing this. I'm going to close this one in favour of https://github.com/nushell/nushell/issues/1420. Thanks for the report! 🙌

**Comment by thegedge** [comment]
Actually, this is a separate issue. This is a newline when running a standalone pipeline (e.g., `-c`)

**Comment by jonathandturner** [comment]
Should we just remove the newline when running with `-c`?

**Comment by kbd** [comment]
> Should we just remove the newline when running with -c?

`nu` output with `-c` should not have a newline if there wasn't one in the original output, but `nu` should not remove a newline if there is one.

This is correct behavior:

```shell
$ python3 hello.py | xxd
00000000: 6865 6c6c 6f0a                           hello.
$ nu -c 'python3 hello.py' | xxd
00000000: 6865 6c6c 6f0a                           hello.
```

As is this, actually:

```shell
$ python3 hello_no_newline.py | xxd
00000000: 6865 6c6c 6f                             hello
$ nu -c 'python3 hello_no_newline.py' | xxd
00000000: 6865 6c6c 6f                             hello
```

So, `nu` isn't always adding a newline to output when using `-c`. However, this is incorrect:

```shell
$ nu -c 'open test.json | get foo | xxd'
00000000: 6261 72                                  bar
$ nu -c 'open test.json | get foo' | xxd
00000000: 6261 720a                                bar.
```
