### ISSUE TITLE
Human readable datetimes not working correctly with "local" timezone

### ISSUE THREAD

**Issue by kiil** [nushell/nushell#14195]
### Describe the bug

See How to reproduce and Expected behavior

### How to reproduce

Days shift according to timezone offset, eg in this case on `01:00:00`:

```
: 'yesterday' | into datetime
Mon, 28 Oct 2024 01:00:00 +0100 (2 days ago)
: 'today' | into datetime
Tue, 29 Oct 2024 01:00:00 +0100 (13 hours ago)
: 'tomorrow' | into datetime
Wed, 30 Oct 2024 01:00:00 +0100 (in 10 hours)
```

### Expected behavior

Days should always shift on `00:00:00` like so:

```
: 'yesterday' | into datetime
Mon, 28 Oct 2024 00:00:00 +0100 (2 days ago)
: 'today' | into datetime
Tue, 29 Oct 2024 00:00:00 +0100 (14 hours ago)
: 'tomorrow' | into datetime
Wed, 30 Oct 2024 00:00:00 +0100 (in 9 hours)
```

### Configuration

| key                | value                                                       |
| ------------------ | ----------------------------------------------------------- |
| version            | 0.99.1                                                      |
| major              | 0                                                           |
| minor              | 99                                                          |
| patch              | 1                                                           |
| branch             |                                                             |
| commit_hash        |                                                             |
| build_os           | linux-x86_64                                                |
| build_target       | x86_64-unknown-linux-gnu                                    |
| rust_version       | rustc 1.79.0-nightly (1cec373f6 2024-04-16)                 |
| rust_channel       | nightly-x86_64-unknown-linux-gnu                            |
| cargo_version      | cargo 1.79.0-nightly (48eca1b16 2024-04-12)                 |
| build_time         | 2024-10-21 11:36:50 +02:00                                  |
| build_rust_channel | release                                                     |
| allocator          | mimalloc                                                    |
| features           | default, sqlite, trash                                      |
| installed_plugins  | explore 0.98.0, formats 0.99.1, polars 0.99.1, query 0.99.1 |

**Comment by fdncred** [comment]
When I run these commands, it looks like the timezone information is wrong so that will affect what date is provided.
```nushell
❯ 'yesterday' | into datetime
Sun, 27 Oct 2024 19:00:00 -0500 (2 days ago)
❯ 'tomorrow' | into datetime
Tue, 29 Oct 2024 19:00:00 -0500 (in 10 hours)
❯ 'today' | into datetime
Mon, 28 Oct 2024 19:00:00 -0500 (13 hours ago)
```
If you look at the `today` output, you'll see that it says 19:00:00, 13 hrs ago, when actually it is 8:30 in the morning so it should say 8 or 9 hours ago and whatever time it is in my local time zone, which it got right as -0500.

**Comment by kiil** [comment]
@fdncred have a look:

```
: '10:00' | into datetime
Tue, 29 Oct 2024 10:00:00 +0100 (4 hours ago)
```

That is completely correct, because 10:00 stays 10:00.

But to have 'today' become 01:00:00, in my case, or 19:00:00, in your case - is meaningless. IMHO.

**Comment by fdncred** [comment]
I took a quick look at the code
https://github.com/nushell/nushell/blob/03015ed33fd95c0df9250a284e72fd0d0c971b5f/crates/nu-command/src/conversions/into/datetime.rs#L275-L276

And it's just calling into the human-date-parser crate. I'm not sure what we can do about it being wrong. Seems like it's an upstream problem. Perhaps there are other functions we could call?

**Comment by kiil** [comment]
@fdncred I am using the functionality to find tasks that have a deadline tomorrow, and I work around the issue like so:

```
where due >= (('tomorrow' | into datetime) - 1hr)
```

But in the daylights saving period of the year I have to manually edit my code to `2hr` instead of `1hr`. Less than ideal, but if there is now other way, it will have to do.

**Comment by fdncred** [comment]
it may be that we just need a better crate? I'm not sure. I understand the use case, I'm just not sure what we can do about it since we're just passing in 'yesterday' and it's giving us a result. There is no manipulation of the data. That's why I'm saying that it could be a problem upstream with that crate.

**Comment by kiil** [comment]
Maybe this is related: https://github.com/technologicalMayhem/human-date-parser/issues/3

**Comment by kiil** [comment]
A better workaround that others may find useful:

```
: 'tomorrow 00:00' | into datetime
Wed, 30 Oct 2024 00:00:00 +0100 (in 8 hours)
```
This gives both the correct date *and* time, and the correct time span. Also works with 'today' and 'yesterday'.

**Comment by fdncred** [comment]
> Maybe this is related: [technologicalMayhem/human-date-parser#3](https://github.com/technologicalMayhem/human-date-parser/issues/3)

Someone could definitely try to convert the datetime coming back from human-date-parser to a local datetime, although the time zone for me is already right so I don't think it would change my 19:00:00 to anything else.

**Comment by fdncred** [comment]
> A better workaround ....

This works for me too
```nushell
❯ 'yesterday' | into datetime
Sun, 27 Oct 2024 19:00:00 -0500 (2 days ago)
❯ 'yesterday 00:00' | into datetime
Mon, 28 Oct 2024 00:00:00 -0500 (a day ago)
```

**Comment by kiil** [comment]
> > Maybe this is related: [technologicalMayhem/human-date-parser#3](https://github.com/technologicalMayhem/human-date-parser/issues/3)
> 
> Someone could definitely try to convert the datetime coming back from human-date-parser to a local datetime, although the time zone for me is already right so I don't think it would change my 19:00:00 to anything else.

I think you are right about that.

**Comment by fdncred** [comment]
we could also just vendor the crate and fix it, if someone was dedicated enough to do that and support it.

**Comment by fdncred** [comment]
I put up this PR, based on what we learned here, if anyone wants to try it out https://github.com/nushell/nushell/pull/14266
