### ISSUE TITLE
`save -f` creates an empty file when piping from external commands to `save`

### ISSUE THREAD

**Issue by justbispo** [nushell/nushell#14199]
### Describe the bug

The title is incomplete because I couldn't write a succinct enough title that included the full explanation.

I've noticed that whenever I pipe the output of an external command doing something with a file to `save` and overwrite that file, it produces a 0 bytes file.
I've currently only tried with two programs, `bat` and `jq` but it should happen with any program that creates an output.
If I save to a different file, it works. If I save again to this different file but overwrite it with `save -f`, it also works. Only overwriting the file the external command interacted fails.

### How to reproduce

1. Create a `test.json` file with some valid json
2. Run `jq -r tostring test.json | save -f test.json`
3. Alternatively, run `bat test.json | save -f test.json`

### Expected behavior

The file produced shouldn't be empty and should contain some content.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.99.1                                   |
| major              | 0                                        |
| minor              | 99                                       |
| patch              | 1                                        |
| branch             |                                          |
| commit_hash        | 8812072f065be283df3e9a81f3945d0364f2f247 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10)      |
| rust_channel       | 1.79.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.79.0 (ffa9cf99a 2024-06-03)      |
| build_time         | 2024-10-20 19:44:31 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  |                                          |

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.99.1                              |
| major              | 0                                   |
| minor              | 99                                  |
| patch              | 1                                   |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | aarch64-linux-android               |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10) |
| rust_channel       | 1.79.0-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.79.0 (ffa9cf99a 2024-06-03) |
| build_time         | 2024-10-21 00:30:57 +00:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash              |
| installed_plugins  |                                     |

**Comment by IanManske** [comment]
Writing to a file while also reading from the same file unfortunately does not work (in any shell). Writing to a file requires first clearing the file, which then immediately causes the read to finish.

For internal commands, we try to detect this case and show an error:
```nu
> open test.txt | save -f test.txt
Error:   × pipeline input and output are the same file
   ╭─[entry #2:1:25]
 1 │ open test.txt | save -f test.txt
   ·                         ────┬───
   ·                             ╰── can't save output to 'test.txt' while it's being read
   ╰────
  help: insert a `collect` command in the pipeline before `save` (see `help collect`).
```

But for external commands, this is hard (maybe impossible?) to detect, so no error message is shown. Like the error message suggests, putting a `collect` before the `save` solves the issue.
```
bat test.json | collect | save -f test.json
```

**Comment by justbispo** [comment]
OK, I was reading about this after your response and it totally makes sense that shells can't do it. I presumed the left operand would finish running, and thus closing the file, before running the right operand. I've learned something new about shells today.
