### ISSUE TITLE
Commands are evaluated in backtick string arguments to externals

### ISSUE THREAD

**Issue by 132ikl** [nushell/nushell#14202]
### Describe the bug

When passing a backtick string argument to an external command, commands in parenthesis are evaluated.

I ran into this while auto-completing a file with parenthesis in its name to an external, which could potentially be destructive:

```nushell
scp `my cool file (shutdown)` remotehost:/path/
```

I was able to reproduce this issue on 1d15bbc95b8d56a421f64f185ede0f029e183302 but not 5002d87, so it is caused by #13910 (cc @WindSoilder)

### How to reproduce

```nushell
^echo `($nu.pid)`
```

### Expected behavior

Never execute commands in backtick strings.

### Configuration

| key                | value                                                                                                                                                            |
| ------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.99.2                                                                                                                                                           |
| major              | 0                                                                                                                                                                |
| minor              | 99                                                                                                                                                               |
| patch              | 2                                                                                                                                                                |
| branch             | makepkg                                                                                                                                                          |
| commit_hash        | e104bccfb94e5572c4c138ce59121ed84456d7d0                                                                                                                         |
| build_os           | linux-x86_64                                                                                                                                                     |
| build_target       | x86_64-unknown-linux-gnu                                                                                                                                         |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06)                                                                                                                              |
| rust_channel       | 1.80.1-x86_64-unknown-linux-gnu                                                                                                                                  |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)                                                                                                                              |
| build_time         | 2024-10-29 21:42:57 +00:00                                                                                                                                       |
| build_rust_channel | release                                                                                                                                                          |
| allocator          | mimalloc                                                                                                                                                         |
| features           | default, sqlite, trash                                                                                                                                           |
| installed_plugins  | custom_values 0.1.0, example 0.98.0, explore 0.99.1, formats 0.98.0, gstat 0.98.0, inc 0.98.0, jwalk 0.8.0, polars 0.98.0, query 0.98.0, stress_internals 0.98.0 |et       | x86_64-unknown-linux-gnu                                                                                                                                         |
| rust_version       | rustc 1.79.0 (129f3b996 2024-06-10)                                                                                                                              |
| rust_channel       | 1.79.0-x86_64-unknown-linux-gnu                                                                                                                                  |
| cargo_version      | cargo 1.79.0 (ffa9cf99a 2024-06-03)                                                                                                                              |
| build_time         | 2024-10-16 08:00:06 +00:00                                                                                                                                       |
| build_rust_channel | release                                                                                                                                                          |
| allocator          | mimalloc                                                                                                                                                         |
| features           | default, sqlite, trash                                                                                                                                           |
| installed_plugins  | custom_values 0.1.0, example 0.98.0, explore 0.99.1, formats 0.98.0, gstat 0.98.0, inc 0.98.0, jwalk 0.8.0, polars 0.98.0, query 0.98.0, stress_internals 0.98.0 |

**Comment by WindSoilder** [comment]
Oh, sorry for causing something like this.  I'll try to look into it
