### ISSUE TITLE
adding a trailing \n to pipelines may corrupt binary data

### ISSUE THREAD

**Issue by dcarosone** [nushell/nushell#1420]
**Describe the bug**
The initial fix in #1391 adds a newline to pipeline byte content.  

As noted there, it's an incorrect fix, but since that was noted post-merge, I'm raising this as a new issue to ensure it doesn't get lost 

**To Reproduce**
1. pipe binary bytestreams between commands
2. 
3. 

**Expected behavior**
pipelines for unstructured data do not alter bytestream content

**Screenshots**

```
/home/dan> dd if=/dev/urandom bs=1M count=2 of=/tmp/foo
2+0 records in
2+0 records out
2097152 bytes (2.1 MB, 2.0 MiB) copied, 0.011876 s, 177 MB/s
/home/dan> sha1sum /tmp/foo
01b54ffc3795e0c3fe4c00c92261fb04bf845f1f  /tmp/foo
/home/dan> cat /tmp/foo | sha1sum -
da39a3ee5e6b4b0d3255bfef95601890afd80709  -
```
vs in bash:
```
❯ cat /tmp/foo | sha1sum -
01b54ffc3795e0c3fe4c00c92261fb04bf845f1f  -
```

**Configuration:**
 - OS: linux
 - Version 0.10.0
 - Optional features (if any)

**Comment by thegedge** [comment]
👍 We've been discussing how defaulting to line output has generally caused problems, no matter how good a default it may be. We're planning on moving to externals emitting byte blobs by default, and having the user explicitly request `| lines` when lines are actually needed.

I'm really hoping to complete this work before the next release 🤞

**Comment by jonathandturner** [comment]
With #1457, I'm hoping we took a big step in the direction of supporting this correctly.

```
❯ sha1sum /tmp/foo
81635d0e8e264b3cc1040be98233309eb34cd8b0  /tmp/foo
nushell on 📙 bytes_codec is 📦 v0.10.1 via 🦀 v1.41.0 
❯ cat /tmp/foo | sha1sum -
81635d0e8e264b3cc1040be98233309eb34cd8b0  -
nushell on 📙 bytes_codec is 📦 v0.10.1 via 🦀 v1.41.0 
❯ exit
jonathan@pop-os:~/Source/nushell$ cat /tmp/foo | sha1sum -
81635d0e8e264b3cc1040be98233309eb34cd8b0  -
```

Closing, but please re-open (or open new issues) if there are related cases that aren't correct.
