### ISSUE TITLE
mkdir should support `-p` flag

### ISSUE THREAD

**Issue by Tritlo** [nushell/nushell#14215]
### Describe the solution you'd like

`mkdir -p` in bash, zsh, and even powershell support the `-p` flag, which, when given a path, creates all missing directories in the path.

E.g. `mkdir -p a/b/c` will create `a`, `a/b` and `a/b/c`

I would like this flag to be supported in the `nu` implementation.

**Comment by Dorumin** [comment]
I think that's the default behavior of mkdir. Certainly a compatibility hazard, if you want isomorphic command calls, but recursive directory creation already works.

**Comment by 132ikl** [comment]
If you want it to error, you can do use something like this:

```nushell
def mkdir-exists [...rest: string] {
    for $path in $rest {
        if ($path | path parse | get parent | path exists) {
           mkdir $path
        } else {
           print $"Cannot create ($path), parent does not exist"
        }
    }
}
alias mkdir = mkdir-exists
```

**Comment by fdncred** [comment]
Correct, it is by design that nushell is not like all unix systems. One reason is that nushell is cross platform with Windows, MacOS, Linux, and some BSDs. Nushell is not intended to be posix compliant.

**Comment by NotTheDr01ds** [comment]
Just a heads-up that PowerShell does *not* support `-p` for creating multiple directories at one time.

PowerShell *always* creates multiple directories as needed, just like Nushell.

`-p` in PowerShell is simply short for `mkdir -path` (just as `-pa` and `-pat`), which is the optional argument to specify the path to be created.  It is basically a no-op in most cases.
