### ISSUE TITLE
Touch follows symlinks

### ISSUE THREAD

**Issue by Dorumin** [nushell/nushell#14212]
### Describe the bug

`touch` follows symlinks. It probably shouldn't.

At least, it inconveniences me, so if it _should_, it would be good to have a flag that prevents it from doing so, since modifying symlink times is not really possible. (I also find it's not possible to set times in general without a reference file, if you have a `datetime` value for example. Why not?)

--> https://github.com/nushell/nushell/blob/main/crates/nu-command/src/filesystem/touch.rs#L98
--= Probably use symlink_metadata instead

### How to reproduce

1. Attain a symlink through mysterious means
2. `touch symlink -m -r base.txt`
3. Validate the symlink's metadata hasn't changed, and its target file's has

### Expected behavior

Touch the symlink

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.98.0                              |
| major              | 0                                   |
| minor              | 98                                  |
| patch              | 0                                   |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | windows-x86_64                      |
| build_target       | x86_64-pc-windows-msvc              |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04) |
| rust_channel       | stable-x86_64-pc-windows-msvc       |
| cargo_version      | cargo 1.81.0 (2dbb1af80 2024-08-20) |
| build_time         | 2024-09-21 23:12:24 -03:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash              |
| installed_plugins  |                                     |

**Comment by ysthakur** [comment]
I believe GNU `touch` also follows symlinks by default, though it has a flag `-h` to avoid following them.

There's a PR in progress to add `uutils`'s `touch` command: https://github.com/nushell/nushell/pull/11817. Still waiting for the next release of uutils/coreutils, which will include changes that would allow Nushell to use `uu_touch`.

**Comment by Dorumin** [comment]
> I believe GNU `touch` also follows symlinks by default, though it has a flag `-h` to avoid following them.
> 
> There's a PR in progress to add `uutils`'s `touch` command: #11817. Still waiting for the next release of uutils/coreutils, which will include changes that would allow Nushell to use `uu_touch`.

Cool. Good to know. So the short-term fix would be to add a flag, won't break existing stuff and it'd behave as the unix touch. Long-term, the rest of uutils things, for what doesn't need structured data at least.

Also, `touch` seems to use the `filetime` package modifying the times, which also follows symlinks. There's a symlink function there too that would need to be used.
