### ISSUE TITLE
[parse] command expansion

### ISSUE THREAD

**Issue by c4lliope** [nushell/nushell#14228]
Hello, I'm a 'lil unsure on the rules around running a wrapped command properly. Here are some quick examples of my issue:

a. Originally, I presumed a parenthesized string may be ran as a command. Unsure where I picked up this notion; the function only prints the command as a string.

b. Similarly, skipping the `str join` pipe only displays the command as an argument list.

```nu
def "cycle" --wrapped [ --dura (-d): duration = 6sec, ...command: string ] {
  loop { clear; ($command | str join ' ') | print; sleep $dura } }


~> cycle ls /dev/sd*                                                11/01/2024 06:31:25 AM AM
╭───┬──────────╮
│ 0 │ ls       │
│ 1 │ /dev/sd* │
╰───┴──────────╯

```

c. so I checked a couple expansion patterns to keep from doing the string conversion. none really held up like I needed.

```nu
Error: nu::shell::external_commandther a Nushell built-in or a known external command
- Check again using:
  × External command failed                                                 11/01/2024 06:08:42 AM AM
    ╭─[/home/calliope/.build/config/nushell/scan.nu:21:17]
 20 │ def "cycle" --wrapped [ --dura (-d): duration = 6sec, ...command: string ] {
 21 │   loop { clear; ...($command) | print; sleep $dura } }
    ·                 ──────┬──────
    ·                       ╰── Command `...[ls, /dev/sd*]` not found
    ╰────
  help: `...[ls, /dev/sd*]` is neither a Nushell built-in or a known external command


Error: nu::shell::external_command

  × External command failed
    ╭─[/home/calliope/.build/config/nushell/scan.nu:21:18]
 20 │ def "cycle" --wrapped [ --dura (-d): duration = 6sec, ...command: string ] {
 21 │   loop { clear; (...$command) | print; sleep $dura } }                11/01/2024 06:08:13 AM AM
    ·                  ─────┬─────
    ·                       ╰── Command `...$command` not found
    ╰────
  help: `...$command` is neither a Nushell built-in or a known external command

~>                                                                        1 11/01/2024 06:08:14 AM AM

Error: nu::shell::external_command
    > shell $m.space
  × External command failed
    ╭─[/home/calliope/.build/config/nushell/scan.nu:21:18]
 20 │ def "cycle" --wrapped [ --dura (-d): duration = 6sec, ...command: string ] {
 21 │   loop { clear; (...($command)) | print; sleep $dura } }les):
    ·                  ──────┬──────
    ·                        ╰── Command `...[ls, /dev/sd*]` not found
    ╰────
  help: `...[ls, /dev/sd*]` is neither a Nushell built-in or a known external command
```

In each case I used a simple command that I hope is general-purpose enough for many use cases:
```nu
~> cycle ls /dev/sd*                                                        11/01/2024 06:07:40 AM
```

**Comment by fdncred** [comment]
I think you can do something like this to run externals. The key is to have a command and parameters separately.
```nushell
def "cycle" --wrapped [ --dura (-d): duration = 6sec, ...command: string ] {
  loop { clear; ^($command | first) ($command | skip | str join '') | print; sleep $dura }
}
```

**Comment by c4lliope** [comment]
eh... I'm more looking for a bridge to `nu -c "..."`, only one that has no need to launch another nu process.

I guess I remember there's a quirk because nu code is compiled, no? maybe launching `nu -c $cmd` is cheap enough in memory to make no difference. My main concern is that I run many-many custom function definitions and I'd be sad to load them all again if there's a cheaper approach.

**Comment by fdncred** [comment]
I think `nu -c` is the only way right now.

**Comment by c4lliope** [comment]
Oh! Guess I recall that `nu -c` does not source in any `~/.config/nushell` files; this means I can be nice and picky about my loading calls, by choosing among:

* `nu -c 'ls /dev/sd*'` - core nu only
* `nu -c 'source "~/.config/nushell/disc.nu"; disc ls;'` - include a single helper module
* `nu -e 'disc complex-command; exit'` - load full local shell, exit once done.

I'll hark back here if anything goes unexpectedly.
early pass on some crucial nu modules (nixOS):
https://share.operand.online/gram/build/config/nushell/

**Comment by fdncred** [comment]
There's also this "documentation" that shows when/what config files are sourced. https://gist.github.com/fdncred/b87b784f04984dc31a150baed9ad2447/
