### ISSUE TITLE
mv command can't detect the path of a file in the same directory where you are running the command 

### ISSUE THREAD

**Issue by charleschege** [nushell/nushell#1423]
`mv` doesn't detect `../` or `~/` if the source file does not have an absolute path or if source is in the same directory you must use a `./`

You can't do `mv README.MD ~/`

You must add a . / which is
`mv ./README.MD ~/`

**Comment by thegedge** [comment]
Not seeing this on the current master (0f0847e). Going to close, but reopen with more specifics (file types, OS, etc) if you're still having this issue.
