### ISSUE TITLE
`-h` on some commands doesn't work while `--help` does

### ISSUE THREAD

**Issue by coolshaurya** [nushell/nushell#1427]
**Describe the bug**
In some commands, doing `h` prints an error while --help works perfectly.

**To Reproduce**
1. type `where -h`
2. 
3. 

**Expected behavior**
`where -h` to work the same as doing `where --help`

**Configuration (please complete the following information):**
 - OS: Manjaro Linux
 - Version 0.10.0
 - Optional features - `stable`

**Comment by thegedge** [comment]
Looks like it could be anything with required parameters. Thanks for the report!
