### ISSUE TITLE
Can add duration to date, but not date to duration

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#14294]
### Describe the bug

Best just reproduced:

### How to reproduce

```nushell
(date now) + 1hr
# => Sat, 9 Nov 2024 23:44:39 -0500 (in an hour)
1hr + (date now)
# => Error: addition is not supported between duration and date
```

### Expected behavior

Commutative property of addition to hold true:

(A + B) == (B + A)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.99.2                                   |
| major              | 0                                        |
| minor              | 99                                       |
| patch              | 2                                        |
| branch             |                                          |
| commit_hash        | d6944b348fa508b7fb7ff7c7614a9d0860e9a109 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06)      |
| rust_channel       | 1.80.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)      |
| build_time         | 2024-11-03 07:47:12 -05:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I think there just needs to be a counterpart to this
https://github.com/nushell/nushell/blob/919d55f3fc1c74743db44050d1045799901e884e/crates/nu-protocol/src/value/mod.rs#L2447-L2457

It seems like we excluded it on purpose but I'm not sure why.
