### ISSUE TITLE
Using `inc` and `save` to increment package version in cargo.toml file reverses ordering of sections 

### ISSUE THREAD

**Issue by charleschege** [nushell/nushell#1429]
So I used save and inc to increment my package version in cargo.toml file and it incremented my package version by when it saved the file, the file was in reverse. Instead of saving the sections as
```
[package]
....

[dependencies ]
.... 

[dependencies.async_std]
....
```

It save these sections in reverse as follows
```
[dependencies.async_std]
....

[dependencies ]
.... 

[package] 
....
```

**Comment by jonathandturner** [comment]
The `toml` package we currently use preserves semantics but unfortunately doesn't preserve ordering. We might need to look into other dependencies that could do this.
