### ISSUE TITLE
strange behavior with nushell in wezterm

### ISSUE THREAD

**Issue by DartMitai** [nushell/nushell#14304]
### Describe the bug

When you enter any character, even if it is a space, a new line appears at the terminal (WezTerm)

### How to reproduce

Windows 11
WezTerm
nu

### Expected behavior

normal operation

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.97.1                                   |
| major              | 0                                        |
| minor              | 97                                       |
| patch              | 1                                        |
| branch             |                                          |
| commit_hash        | 60769ac1ba3ea036d889f140095d855e5597840c |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.78.0 (9b00956e5 2024-04-29)      |
| rust_channel       | 1.78.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.78.0 (54d8815d0 2024-03-26)      |
| build_time         | 2024-08-21 03:34:17 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, system-clipboard, trash |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
One fix for this is to upgrade to 0.99.1 and set osc133 to false in the config file.

**Comment by DartMitai** [comment]
thanks bro
