### ISSUE TITLE
Proposal: uncouple table stages in the output stream

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1433]
**Is your feature request related to a problem? Please describe.**
The current protocol for output streams is pretty powerful. We can describe streams of rows in a way that can be consumed at different stages in the pipeline, and in a structural way.  That said, the current system has a few drawbacks:

* There is no way to stream non-table data. Eg) streaming of large binaries or large strings is not currently possible as they assume you have the whole data unit and can send as a single unit (rather than stream)
* There is no way to stream inner table data. Inner tables must be fully realized as a single unit
* Rows in the table currently contain column names, which leads to lots of duplication
* It's currently ambiguous if the user means rows of strings (eg what comes from lines) and the contents of a text file
* Related: we assume that contents streams out of an external command as text with line-endings. This feature would allow us to express a stream of bytes, which the user could then optionally turn into lines

**Describe the solution you'd like**

The solution would be in two parts:

_Un-coupling the table stages themselves_

Currently we have Row and Table as two Value types, but this isn't expressive enough.

I suggest we expand this into the actual stages:
* BeginTable / EndTable
* Header
* BeginRow / EndRow
* BeginCell / EndCell (for discrete cells we could also have a shortcut Cell)

Where we have:
* Row (header1: data1_1, header2: data1_2, ...)
* Row (header1, data2_1, header2: data2_2, ...)

We would have:
* BeginTable
* Header (header1, header2, ...)
* BeginRow
* Cell(data1_1)
* Cell(data1_2)
* EndRow
* BeginRow
* Cell(data2_1)
* Cell(data2_2)
* EndRow
* EndTable

_Uncoupling tables from other value types in the stream_

Each value that comes in the stream over the first value is assumed to be rows of a table, but this prevents us from representing streaming other kinds of data.  I propose we no longer assume that data units are rows. They must be expressed as part of the row data in the protocol, or we assume they're part of a stream of bytes or text.

**Describe alternatives you've considered**
We could switch to a more command-based protocol that, like an instruction set around how to build up a table. This would be powerful, but I feel the value-based approach should be explore more before we investigate this direction.

**Drawbacks to this proposal**
There are drawbacks to this proposal. The new protocol is more verbose, which increases wire and memory traffic and may impact performance. It also makes emitting tables more complex in that you have more steps - this can be mitigated somewhat with convenience functions. I believe this complexity is worthwhile, as it opens up the possibility to express different kinds of streams that were not expressible in the current design.

**Comment by thegedge** [comment]
This reminds me a lot of XML processing. I've seen three styles:

- DOM-based, load the entire thing as a tree.
- SAX-based, load as a stream of events
- Something in between the two (for example, https://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/XML/Reader)

What you're proposing is something akin to SAX. I like it because it fits the streaming model we push for internally.

What's missing is what this would look like to consumers (i.e., internal commands and plugins). Would the interface to such a stream of events look like `InputStream`? Something else, maybe closer to the protocol itself? Mind expanding on that.

**Comment by jonathandturner** [comment]
@thegedge - good question... I'm starting to wonder if we should simplify a bit.  Right now the reading would be similar to SAX, in that the reader would need to hold more state to parse as values came through the pipeline.

Maybe we need discrete and begin/end versions of nodes.  That would let you have something much closer to the current protocol if you knew all your values were discrete.

Will think about it a bit more to see if that can be simplified any.

**Comment by jonathandturner** [comment]
Bumping this, as I just hit it again.

Currently, a stream with strings is treated as a multi-part string that should be concatenated. Unfortunately, `get`-ing names from a table (eg, `ls | get name`) is being treated as the same thing, even though the latter would be more natural as a list.
