### ISSUE TITLE
Type annotation for record seems broken when used as command flag

### ISSUE THREAD

**Issue by petrisch** [nushell/nushell#14348]
### Describe the bug

The following script fails in v0.100 and did probably fail before,
but I' quite sure it used to work and I don't see why it shouldn't.

```nushell
def main [
  --foo: record<string>
] {
  print $foo
}
```
produces:
```nushell
~ nu reprod.nu --foo {"test": "bla"}
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[<commandline>:1:12]
 1 │ main --foo "{test: bla}"
   ·            ──────┬──────
   ·                  ╰── expected block, closure or record
   ╰────
```
even though the types should match.
```nushell
~ {"test": "bla"} | describe
record<test: string>
```
It looks like the given block is transfered to a string first and hence doesn't match the record anymore.
Maybe I'm just doing this wrong, and hit me if this is a known one.
I really looked inte existing issues, but 1.2k is quite a bit....

### How to reproduce

like in the description, this should be a minimal example.

### Expected behavior

printing out the record.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.100.0                             |
| major              | 0                                   |
| minor              | 100                                 |
| patch              | 0                                   |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | windows-x86_64                      |
| build_target       | x86_64-pc-windows-msvc              |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04) |
| rust_channel       | stable-x86_64-pc-windows-msvc       |
| cargo_version      | cargo 1.81.0 (2dbb1af80 2024-08-20) |
| build_time         | 2024-11-13 16:40:46 +01:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash              |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
Shouldn't it be like this?
```nushell
❯ def cmd [--foo: record<test: string>] {
    print $foo
  }
❯ cmd --foo {"test": "blah"}
╭──────┬──────╮
│ test │ blah │
╰──────┴──────╯
```

**Comment by petrisch** [comment]
Hm, so it works if the script has been sourced and it works for primitive types,
but not for complex structures if called with `nu cmd.nu --foo {"test": "blah"}` right?

Thats probably documented, but I can't find it.

**Comment by petrisch** [comment]
http://www.nushell.sh/book/scripts.html#argument-type-interpretation

Thats probably it right?
With `nu cmd.nu` nushell cannot know such types.

**Comment by petrisch** [comment]
I think thats what it is and kind of logic. Case closed.
