### ISSUE TITLE
Allow `rm ...<var>` to accept a table, using the `name` field automatically

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#14349]
### Related problem

I commonly find myself doing something like:

```nushell
cd /tmp
ls rust* | sort-by modified | where modified < (date now) - 1wk
# => Confirm the list has what I want
# Up-arrow and Append ...
ls rust* | sort-by modified | where modified < (date now) - 1wk | rm ...$in
```

Oops!  I just forgot the `| get name`.

### Describe the solution you'd like

Perhaps it's a bit too "magic", but how would people feel about `rm` checking for a table argument and automagically using the `name` column if it exists (and error otherwise)?

Perhaps "table" isn't (or perhaps is) the right idea here:

* We could `rm $table`, in which case it would be a table.  In that case, we'd probably want to extend `rm $list` to work without a list spreader.
* Or stick with list-spreading, in which case we'd really be taking a `rest` of `record` values and extract the `name` value from it.

Either seems possible, and perhaps a bit more convenient and understandable to shell users, but is it "too magic" or does it have problematic corner-cases?

**Comment by IanManske** [comment]
Too much magic for me :magic_wand:

**Comment by WindSoilder** [comment]
To be honest I don't like this.  In this case, explicit is better than implicit, especially in something like `rm` command

**Comment by NotTheDr01ds** [comment]
Fair enough - Closing :-)
