### ISSUE TITLE
Vertical lines aren't continuous in windows terminal (preview)

### ISSUE THREAD

**Issue by tekjar** [nushell/nushell#1436]
**Describe the bug**
```
────┬────────────────┬──────┬─────────┬────────────
 #  │ name           │ type │ size    │ modified
────┼────────────────┼──────┼─────────┼────────────
  0 │ .cargo         │ Dir  │    —    │ 1 hour ago
  1 │ .git           │ Dir  │    —    │ 1 hour ago
  2 │ .gitignore     │ File │   123 B │ 1 day ago
  3 │ .gitlab-ci.yml │ File │   958 B │ 1 day ago
```

**Configuration (please complete the following information):**
 - OS: Windows 10
 - Version 0.10

Looks fine in power shell though

**Comment by thegedge** [comment]
Sounds like your windows terminal could be configured with a font that isn't fixed width. Are you able to verify whether or not that's the case, @tekjar?

**Comment by tekjar** [comment]
Very new to using windows. I'll try to find that

**Comment by thegedge** [comment]
Thanks, @tekjar . Let me know what you discover!

**Comment by thegedge** [comment]
Hey, @tekjar . I'm going to close this as I suspect it was simply a font issue, not a `nushell` issue. Also, the table you posted in the original description appears to have vertical lines appear continuous 🙂

If I was wrong about this, let me know and we'll re-open and investigate more.
