### ISSUE TITLE
Default `config.nu` and `env.nu` files are not created.

### ISSUE THREAD

**Issue by mastermach50** [nushell/nushell#14363]
### Describe the bug

The default `config.nu` and `env.nu` files are not created if a `~/.config/nushell` exists even if that folder is empty.

### How to reproduce

1. Backup and remove `config.nu` and `env.nu` from `~/.config/nushell`.
2. Run `nu`

### Expected behavior

Default `config.nu` and `env.nu` files are created.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.100.0                                                           |
| major              | 0                                                                 |
| minor              | 100                                                               |
| patch              | 0                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.82.0 (f6e511eec 2024-10-15) (built from a source tarball) |
| cargo_version      | cargo 1.82.0 (8f40fc59f 2024-08-21)                               |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash                                            |
| installed_plugins  |                                                                   |

**Comment by WindSoilder** [comment]
Hmm... I can reproduce it, I think it's a regression

**Comment by fdncred** [comment]
I believe this is by design according to @NotTheDr01ds PR that enabled this functionality. As I recall, the intent is to allow someone to always run without a config file if the folder exists without being nagged to create files. I think this is the PR https://github.com/nushell/nushell/pull/13857

**Comment by sholderbach** [comment]
This is the behavior that @NotTheDr01ds moved for with:
- https://github.com/nushell/nushell/issues/13669
- https://github.com/nushell/nushell/pull/13857

**Comment by NotTheDr01ds** [comment]
Yes, this was the first part of #14249, but in retrospect I probably would have held the "don't recreate" behavior as part of that PR.

In the meantime, you can regenerate the defaults if desired using:

```nushell
config nu --default | save $nu.config-path
config env --default | save $nu.env-path
```

**Comment by mastermach50** [comment]
@NotTheDr01ds I think this functionality would be better implemented by creating marker files such as `.nu_no_config` and `.nu_no_env` if the user really does not want to have the env and config files.

I ran into this when I moved my custom env and config file into another folder to let nu generate default config and env files so that I can compare those to my own.

Most users would not expect nu to behave in such a way. If this is indeed the way that nu is planning to move forward then there should be some message on startup indicating that default files were not generated due to there being a `nushell` folder.

**Comment by NotTheDr01ds** [comment]
> I ran into this when I moved my custom env and config file into another folder to let nu generate default config and env files so that I can compare those to my own.

I know that's a common pattern today, and that's really a workaround to the core problem that the *next* PR is trying to resolve.  We really won't create *any* defaults in the future - They will be loaded internally before the user's `env.nu` and `config.nu` load.  This is already happening in 0.100.0, to a large degree, but the "default" configs are still in place and auto-generated today. The plan is for those to go away in the next release.  See #14249 for details.

This means that you'll no longer modify an ~800-line config file, but rather just have a much smaller `config.nu` with the values you want to change from the defaults.  This is more in line with the way that other shells (and applications in general) behave.

**Comment by mastermach50** [comment]
@NotTheDr01ds Seems like I was thinking from the perspective of a longtime nu user, I forgot that this was the design pattern used by other software.
