### ISSUE TITLE
Random pick or shuffle

### ISSUE THREAD

**Issue by hirschenberger** [nushell/nushell#1437]
**Is your feature request related to a problem? Please describe.**
I sometimes have to pick a number of random files from a folder

**Describe the solution you'd like**
Either a `ls | shuffle | first 10` or `ls | pick --random 10`

**Describe alternatives you've considered**
Tried with the shell cmd `shuf` but it didn't work

If you suggest your favorite implementation, I'd like to implement it.

**Comment by hirschenberger** [comment]
I implemented it as a plugin:

https://github.com/hirschenberger/nu_plugin_shuffle

**Comment by jonathandturner** [comment]
@hirschenberger - if you'd like this to be part of the official Nu plugins, let us know

**Comment by hirschenberger** [comment]
Sure, what do you need, a PR?

**Comment by jonathandturner** [comment]
Yup, a PR to add it with the other plugins should work. You may need to add it to the master Cargo.toml also

**Comment by hirschenberger** [comment]
Do I have to yank my crate then or will it simply be updated because it has a higher version number?

**Comment by jonathandturner** [comment]
@hirschenberger - good question. There are ways to transfer ownership (https://crates.io/policies). You could also use a different name so that it doesn't conflict (and then possibly yank the published versions?)

**Comment by hirschenberger** [comment]
I invited you as owner of my plugin

**Comment by jonathandturner** [comment]
Can you invite me again? I don't seem to see the invitation.

**Comment by jonathandturner** [comment]
Follow-up: we're looking into moving the plugin to a command, to make it easier to publish. (and `shuffle` is a good command to have anyway, so it makes sense :)

**Comment by hirschenberger** [comment]
So you mean to yank the crate and integrate it directly into the nu crate?

**Comment by jonathandturner** [comment]
What we've done is move the command into Nu itself.  You may want to yank the crate, or add a new version to point people to the internal command in versions of Nu 0.11.0 and later.

**Comment by hirschenberger** [comment]
Ok, I yanked all versions. So happy to see the new release.
