### ISSUE TITLE
`$env.config.color_config.shape_and/shape_or` are not used

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#14372]
### Describe the bug

Setting/changing `$env.config.color_config.shape_and` (and `...shape_or`) has no effect.

As far as I can tell, there's simply no code-path that uses these settings.  `nu-parser::flatten` should have a match arm in `flatten_expression_into()` for these operators, along with a corresponding `output.push()`, but I don't see either.

### How to reproduce

```nushell
$env.config.color_config.shape_and = 'red'
if (true and false) { "No" }
```

Notice that the `and` is still styled with the `shape_operator` setting.

### Expected behavior

The `and` and `or` operators would be styled differently based on the value.

I haven't looked at the history yet, but I'm assuming that someone at some point saw value in styling these differently, and I agree there is.

In the meantime, they at least fall-through as `style_operator`.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.100.0                                  |
| major              | 0                                        |
| minor              | 100                                      |
| patch              | 0                                        |
| branch             | main                                     |
| commit_hash        | 30f98f7e64a63a159ce70f02aa6c4c1196cd9ca7 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06)      |
| rust_channel       | 1.80.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)      |
| build_time         | 2024-11-13 06:35:04 -05:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  |                                          |

**Comment by NotTheDr01ds** [comment]
Side-note: Please let me know if I'm reading this wrong.  For the moment, I'm going to document these two settings as *"Not currently used"*.

**Comment by fdncred** [comment]
I think the syntax highlighting is supposed to happen here.
https://github.com/nushell/nushell/blob/13ce9e4f64ba324e9cd62fc3780951ab5683c205/crates/nu-cli/src/syntax_highlight.rs#L147-L148

Not sure why it's not happening.

**Comment by NotTheDr01ds** [comment]
I believe it's because the match expression doesn't actually have the corresponding `FlatShape::And/Or` since it wasn't pushed in `flatten`, but I'm not 100% certain.

**Comment by NotTheDr01ds** [comment]
Odd - To me they are coming through as `shape_operator`.

I'm also starting to wonder about `shape_literal` - I can't see a use for it yet.  I could imagine it being a fall-through in case a literal shape (string, int, record, etc. etc.) wasn't being matched properly, but (a) I think the other literals are all getting parsed correctly, and (b) I also don't see a corresponding Expr where that shape would be pushed onto the flatten output.

**Comment by fdncred** [comment]
I added this to flatten.rs and it fixed it. I changed `and` to red and `or` to an orange.
```rust
        Expr::Operator(op) => match op {
            nu_protocol::ast::Operator::Boolean(boolean) => {
                if *boolean == Boolean::And {
                    output.push((expr.span, FlatShape::And));
                } else if *boolean == Boolean::Or {
                    output.push((expr.span, FlatShape::Or));
                } else {
                    output.push((expr.span, FlatShape::Operator));
                }
            }
            _ => {
                output.push((expr.span, FlatShape::Operator));
            }
        },
        // Expr::Operator(_) => output.push((expr.span, FlatShape::Operator)),
```
![image](https://github.com/user-attachments/assets/e46b240b-bd6b-4fd7-be65-a204312ae29a)

**Comment by sholderbach** [comment]
I think the more reasonable thing to do is to subsume them under `shape_operator` for now.
Makes customizing the theme more user friendly with less confusable entries to work with. Based on the fact that most programming languages/standard editor configs don't seem to bother with stuff like this I would wager even folks spending more time configuring than using Nushell wouldn't explicitly ask for more operators if we don't offer individual operators.
And as long as no one invests serious thought in optimizing `reedline`'s syntaxhighlight/print logic our current single-threaded eventhandle-syntaxhighlight-print loop is susceptible to too much waste in the syntax highlight step, potentially causing flickering or delays when navigating/typing through a larger buffer.

**Comment by fdncred** [comment]
I'm fine with having all operators the same color but that begs the question, do we need FlatShape::And/Or at all? I thought flatshapes were only used for syntax highlighting but I could be wrong.

**Comment by sholderbach** [comment]
Not sure if the operator completion uses them, some completion code uses them out of convenience if I recall. But it should be possible to make the boolean `and` and `or` regular operators in the flatshape. The only thing I would check is if our "just a warning to make the redditors mad" logic for `&&` / `||` may have used them at some point.

**Comment by NotTheDr01ds** [comment]
> FlatShape::And/Or at all? I thought flatshapes were only used for syntax highlighting but I could be wrong.

I wouldn't go wild with styling other operators, but I think `and` and `or` are probably nice to differentiate in syntax-highlighting.  It's not a big deal either way to me, though.  It's there, so if you are okay with making the change above, I'd say just "keep it".  It's probably more trouble to rip it out.
