### ISSUE TITLE
Support setting column names in advance using flags for `from csv` / `from tsv`

### ISSUE THREAD

**Issue by WieeRd** [nushell/nushell#14398]
### Related problem

The Nushell cookbook presents an external completer using the fish shell.

https://www.nushell.sh/cookbook/external_completers.html

```nushell
let fish_completer = {|spans|
    fish --command $'complete "--do-complete=($spans | str join " ")"'
    | $"value(char tab)description(char newline)" + $in
    | from tsv --flexible --no-infer
}
```

This part has always bugged me:

> `$"value(char tab)description(char newline)" + $in`

Not only it's inefficient since it'll be creating a whole new potentially large string via string concatenation just to give columns their names, but also I don't find it semantically clean.

One of the main appeals of Nushell is being able to avoid the awkward string operations that the traditional shells and tools have been doing and instead work with real, strongly typed data rather than formatted strings. In that sense, prepending the header row with string concatenation before parsing the tsv feels like a band-aid fix rather than a real solution.

### Describe the solution you'd like

I suggest a new flag `--columns {col1} {col2} ...` to name to columns in advance.
This flag will imply `--noheaders` and remove the need for prepending the header row.

```nushell
fish --command $'complete "--do-complete=($spans | str join " ")"'
| from tsv --flexible --no-infer --columns value description
```

### Describe alternatives you've considered

Currently, it is possible to parse the tsv headerless with `--noheaders` and later name them with `rename`.

```nushell
fish --command $'complete "--do-complete=($spans | str join " ")"'
| from tsv --flexible --no-infer --noheaders
| rename value description
```

But according to the cookbook, this method has an edge case it cannot cover.

> if the first line of the input doesn't have a second column the parser will skip that column for all the input

**Comment by Bahex** [comment]
> if the first line of the input doesn't have a second column the parser will skip that column for all the input

It might be better to address this issue than to add a `--columns` flag that accepts a list of column names.

If for some reason it can't be fixed, or fixing it has undesirable drawbacks, in my opinion it would be better to have a flag that specifies the number of expected columns.

```nushell
.. | from tsv --flexible --no-infer --no-headers --columns=2 | rename value description
# vs
.. | from tsv --flexible --no-infer --no-headers --columns=[value, description]
```

**Comment by WieeRd** [comment]
`--columns=2` sounds much more simple to implement and does address all the problems.
Delegating the job of naming the columns to `rename` is more DRY as well.
I think this is the way to go.
