### ISSUE TITLE
`timeit` with expression will execute twice

### ISSUE THREAD

**Issue by PulsarShock** [nushell/nushell#14401]
### Describe the bug

# In 0.98.0
```nu
> timeit print 123
123
123
177µs 400ns
> timeit {print 123}
123
176µs 500ns
```

# In 0.97.1
```nu
> timeit print 123
123
167µs 100ns
```

it seems that `timeit <closure>` works fine

### How to reproduce

try `timeit print 123` and `timeit {print 123}`

### Expected behavior

`timeit <expr>` will not execute twice

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.100.0                                  |
| major              | 0                                        |
| minor              | 100                                      |
| patch              | 0                                        |
| branch             |                                          |
| commit_hash        | 30f98f7e64a63a159ce70f02aa6c4c1196cd9ca7 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06)      |
| rust_channel       | 1.80.1-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)      |
| build_time         | 2024-11-13 03:41:46 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
This could be related to `print` vs `timeit`. I'm not sure what is causing it.
```nushell
❯ timeit print 123
123
123
511µs 900ns
❯ timeit ls
5ms 524µs 400ns
❯ timeit 123
22µs 400ns
❯ timeit ^ls
assets   Cargo.lock  CITATION.cff        CONTRIBUTING.md  Cross.toml  docker   README.md            scripts      src    toolkit.nu  wix
benches  Cargo.toml  CODE_OF_CONDUCT.md  crates           devdocs     LICENSE  rust-toolchain.toml  SECURITY.md  tests  typos.toml
112ms 128µs 100ns
```

**Comment by fdncred** [comment]
With `timeit print 123`, the `print 123` automatically fires as it should, then the `eval_expression_with_input Expr::Call` happens and it's printed again since it's evaluated. Very interesting.
