### ISSUE TITLE
Filename completion is displayed severely incorrectly

### ISSUE THREAD

**Issue by SolitudeSF** [nushell/nushell#14408]
### Describe the bug

Trying to complete the filename displays number of issues. The selection displayed immediatly is somewhere in the middle of the list with the selection cursor not even being visible. Scrolling down reveals the cursor. Trying to scroll up you can see that it doesnt display part of the list while the cursor is invisible, then jump to directories.

In the video i am constantly scrolling.

https://github.com/user-attachments/assets/519ef05e-0d15-423a-805e-f76433afea76

### How to reproduce

Try to complete a filename from long filenames probably.

### Expected behavior

Display a single suggestion on a single line with cursor visible.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.100.0                                                          |
| major              | 0                                                                |
| minor              | 100                                                              |
| patch              | 0                                                                |
| branch             | makepkg                                                          |
| commit_hash        | 30f98f7e64a63a159ce70f02aa6c4c1196cd9ca7                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.82.0 (f6e511eec 2024-10-15) (Arch Linux rust 1:1.82.0-2) |
| cargo_version      | cargo 1.82.0 (8f40fc59f 2024-08-21)                              |
| build_time         | 2024-11-13 08:00:49 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | default, sqlite, trash                                           |
| installed_plugins  |                                                                  |

**Comment by SolitudeSF** [comment]
i forgot that i already opened an issue about this

**Comment by 132ikl** [comment]
@SolitudeSF can you link the previous issue?

**Comment by SolitudeSF** [comment]
#13141
