### ISSUE TITLE
shells/enter/dexit/p/n/g commands described in "Shells in Shells" are missing

### ISSUE THREAD

**Issue by genovese** [nushell/nushell#14419]
### Question

The "Shells in Shells" subsection of the Nu Book described the shells, enter, dexit, p, n, and g commands, but in my newly installed nushell 0.100.0 those commands are neither found nor listed in help commands; nor are they listed in the command reference on the website; and the link to the shells command gets a 404. Have these commands been removed or is there something that needs to be loaded/configured to make them available?

### Additional context and details

Running nushell 0.100.0 in Iterm 2 on Mac OS 12.6

Simple reproducible example:
```
> enter src                                                                                                                                                             11/23/2024 11:32:21 AM
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #7:1:1]
 1 │ enter src
   · ──┬──
   ·   ╰── Command `enter` not found
   ╰────
  help: `enter` is neither a Nushell built-in or a known external command
```

**Comment by Bahex** [comment]
Try this
```nushell
use std/dirs shells-aliases *
```
There was a recent change concerning this: https://www.nushell.sh/blog/2024-10-15-nushell_0_99_0.html#standard-library-std-dirs-toc

Documentation is a little outdated.

**Comment by NotTheDr01ds** [comment]
Apologies - I definitely need to update the doc for the 0.99 changes.  That tidbit was in the release notes and a deprecation message in 0.99, but it needs to be in the doc as well.

My personal recommendation is to use the unaliased:

```nushell
use std/dirs
dirs            # list directory stack (same as 'shells')
dirs add        # add a directory and change to it (same as 'enter')
dirs drop       # drop the current directory and change to the previous directory in the list (same as 'dexit')
dirs goto       # goto index (same as 'g')
dirs next       # Make the next directory in the list the active one (same as 'n')
dirs prev       # Make the previous directory in the list active (same as 'p')
```

To me, this has the advantage of:

* Being closer to other shells directory stack functionality, if that matters
* Easier to remember for most commands
* Autocompletes with help

**Comment by genovese** [comment]
Thanks, that's very helpful!  I do like the `dirs` approach.

**Comment by NotTheDr01ds** [comment]
Book chapter on the topic has been updated with the latest info. Thanks!
