### ISSUE TITLE
Prompt goes to a new line when typing any character

### ISSUE THREAD

**Issue by thecaprisun** [nushell/nushell#14445]
### Describe the bug

This bug always happens except for when I just cleared the screen, every time I type a character, even backspace, the prompt just goes down by a line.
I'm using Windows 11 23H2 22631.4460, nushell 0.100.0 installed via winget, and wezterm 20240203-110809-5046fc22.

https://github.com/user-attachments/assets/b4488701-ed80-410f-b085-6d332bf29af9

### How to reproduce

1. Install wezterm
2. Install nushell
3. Run any command and type any character.

### Expected behavior

The prompt staying on the same line

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.100.0                                  |
| major              | 0                                        |
| minor              | 100                                      |
| patch              | 0                                        |
| branch             |                                          |
| commit_hash        | 30f98f7e64a63a159ce70f02aa6c4c1196cd9ca7 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06)      |
| rust_channel       | 1.80.1-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)      |
| build_time         | 2024-11-13 03:41:33 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
1. this is a dupe https://github.com/nushell/nushell/issues/5585 
2. if you disable osc133 in the config.nu it should probably fix it
3. closing as dupe

**Comment by thecaprisun** [comment]
> 1. this is a dupe https://github.com/nushell/nushell/issues/5585 
> 
> 2. if you disable osc133 in the config.nu it should probably fix it
> 
> 3. closing as dupe

alright, thank you
