### ISSUE TITLE
Proposal: Simplifying autoview and removing binaryview

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1444]
**Is your feature request related to a problem? Please describe.**
Currently, when data is available to be viewed it is sent to `autoview`, which has a hardcoded set of steps it does to try to view the data.  One of these steps is to hand binary data off to `binaryview`, which itself is like autoview but focused on binary data.  This heuristic requires manual updates, recompilations, and doesn't allow for users to alter the set of viewers after an install.

**Describe the solution you'd like**
I propose we extend the `from-*` and `to-*` style of commands to include `view-*`.  For example, `view-jpeg` would be invoked if there was a unit of data and it was tagged with metadata that let us know the type of the data was "jpeg".

Because this would work for both text- and binary-based data, it would not be necessary to maintain binaryview, as both format types would use the same view logic.

**Describe alternatives you've considered**
One alternative is to not fix this now and continue to manually update. Another would be to remove autoviewing except for the simple cases and require users to view data manually.

**Comment by thegedge** [comment]
I like the idea of having `<action>-<extension>` because it means it could be easy to extend a builtin command with custom behaviour. `git` takes this approach, for example.

I'd love to expand this proposal with two things (that can be separate issues):

1. `open-<extension>`, so that people could do `open <file>.<extension>`, and
2. a generalized means of creating commands that can be extended in this way.

**Comment by devurandom** [comment]
For `open-<extension>` we already have `xdg-open`, which uses the [shared MIME database](https://www.freedesktop.org/wiki/Specifications/shared-mime-info-spec/) to figure out the MIME type, the [desktop entry database](https://www.freedesktop.org/wiki/Specifications/desktop-entry-spec/) to figure out which applications support opening that MIME type, and the [MIME application database](https://www.freedesktop.org/wiki/Specifications/mime-apps-spec/) to learn about the user's preferred application for that MIME type.
