### ISSUE TITLE
`polars explode` fails with a single item string list

### ISSUE THREAD

**Issue by xentec** [nushell/nushell#14442]
### Describe the bug

Greetings, and thank you for developing Nushell!

I've hit a bug, where Nushell might be too eager to simplify a `list<str>`, where it contains only one element and is passed to `polars explode`:

```
> ({key: ['a'], var: [1 2 3]}
::: | polars into-df
::: | polars explode key
::: | polars into-nu
::: | flatten | to md --pretty)
Error:   × Error collecting lazy frame
   ╭─[entry #49:4:3]
 3 │ | polars explode key
 4 │ | polars into-nu
   ·   ───────┬──────
   ·          ╰── `explode` operation not supported for dtype `object`
 5 │ | flatten | to md --pretty)
   ╰────
```

### How to reproduce

1. Exploding `key` with two values works: 
```nu
{key: ['a' 'b'], var: [1 2 3]} | polars into-df | polars explode key | polars into-nu | flatten | to md --pretty
```
2. Exploding `key` with a single value doesn't: 
```nu
{key: ['a'], var: [1 2 3]} | polars into-df | polars explode key | polars into-nu | flatten | to md --pretty`
```

### Expected behavior

For each of the steps above:

1.
| key | var |
| --- | --- |
| a   | 1   |
| a   | 2   |
| a   | 3   |
| b   | 1   |
| b   | 2   |
| b   | 3   |
2.
| key | var |
| --- | --- |
| a   | 1   |
| a   | 2   |
| a   | 3   |

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.100.0                                                          |
| major              | 0                                                                |
| minor              | 100                                                              |
| patch              | 0                                                                |
| branch             | makepkg                                                          |
| commit_hash        | 30f98f7e64a63a159ce70f02aa6c4c1196cd9ca7                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.82.0 (f6e511eec 2024-10-15) (Arch Linux rust 1:1.82.0-2) |
| cargo_version      | cargo 1.82.0 (8f40fc59f 2024-08-21)                              |
| build_time         | 2024-11-13 08:00:49 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | default, sqlite, trash                                           |
| installed_plugins  | polars 0.100.0                                                   |

**Comment by ayax79** [comment]
Applying a schema to the original example:
```nushell
{key: ['a' 'b'], var: [1 2 3]} | polars into-df -s {key:list<str>, var:list<u8>} | polars explode key | polars collect
```

Also, itt appears the schema is correct when using the table syntax:
```nushell
> ❯ : [[key var]; [[a b] [1 2 3]]] | polars into-df | polars schema
╭─────┬───────────╮
│ key │ list<str> │
│ var │ list<i64> │
╰─────┴───────────╯
```
