### ISSUE TITLE
"sys cpu" is slow

### ISSUE THREAD

**Issue by ineu** [nushell/nushell#14470]
### Related problem

I need to get the number of CPU cores in my script. I would usually use the external binary `nproc`
```
/home/ineu ▶ timeit { nproc }                                                                                11/29/2024 11:18:00
8
10ms 21µs 707ns
```
but decided to try nu's built-in `sys cpu`. And it appears to be very slow for the task it does:

```
/home/ineu ▶ timeit { sys cpu | length | print }
8
404ms 443µs 120ns
```

Which is 40 times slower than nproc.

Of course, `sys cpu` shows more data than a number of cores. But all this data (and even more) can be feched much faster with a function:
```nu
def cpuinfo [] {
    open /proc/cpuinfo | split row "\n\n" | par-each {
        parse -r '(?<key>\w+)\s+:\s+(?<value>\w+)' | transpose -rd
    }
}
```

```/home/ineu ▶ timeit { cpuinfo | print }
╭───┬───────────┬──────────────┬────────┬───────┬───────┬──────────┬───────────┬─────┬──────┬────┬──────────┬───────┬────────╮
│ # │ processor │  vendor_id   │ family │ model │ name  │ stepping │ microcode │ MHz │ size │ id │ siblings │ cores │  ...   │
├───┼───────────┼──────────────┼────────┼───────┼───────┼──────────┼───────────┼─────┼──────┼────┼──────────┼───────┼────────┤
│ 0 │ 0         │ GenuineIntel │ 6      │ 142   │ Intel │ 10       │ 0xf6      │ 400 │ 6144 │ 0  │ 8        │ 4     │ ...    │
│ 1 │ 7         │ GenuineIntel │ 6      │ 142   │ Intel │ 10       │ 0xf6      │ 400 │ 6144 │ 0  │ 8        │ 4     │ ...    │
│ 2 │ 5         │ GenuineIntel │ 6      │ 142   │ Intel │ 10       │ 0xf6      │ 799 │ 6144 │ 0  │ 8        │ 4     │ ...    │
│ 3 │ 3         │ GenuineIntel │ 6      │ 142   │ Intel │ 10       │ 0xf6      │ 400 │ 6144 │ 0  │ 8        │ 4     │ ...    │
│ 4 │ 1         │ GenuineIntel │ 6      │ 142   │ Intel │ 10       │ 0xf6      │ 799 │ 6144 │ 0  │ 8        │ 4     │ ...    │
│ 5 │ 6         │ GenuineIntel │ 6      │ 142   │ Intel │ 10       │ 0xf6      │ 800 │ 6144 │ 0  │ 8        │ 4     │ ...    │
│ 6 │ 4         │ GenuineIntel │ 6      │ 142   │ Intel │ 10       │ 0xf6      │ 400 │ 6144 │ 0  │ 8        │ 4     │ ...    │
│ 7 │ 2         │ GenuineIntel │ 6      │ 142   │ Intel │ 10       │ 0xf6      │ 799 │ 6144 │ 0  │ 8        │ 4     │ ...    │
╰───┴───────────┴──────────────┴────────┴───────┴───────┴──────────┴───────────┴─────┴──────┴────┴──────────┴───────┴────────╯
13ms 916µs 715ns
```

`sys cpu` also displays load average, but that one is very fast to get as well:
```
/home/ineu ▶ timeit { open /proc/loadavg }
266µs 991ns
```

So it looks like `sys cpu` is very inefficient way to get the data (maybe relies on a cross-platform lib which is slow per se?).

### Describe the solution you'd like

Make it fast

**Comment by fdncred** [comment]
Agreed that it's slower. However, there's not much we can do about it. We use the `sysinfo` crate to get this information. Feel free to submit an upstream PR to the sysinfo repo to improve the speed.

**Comment by fdncred** [comment]
I put this PR up to help https://github.com/nushell/nushell/pull/14472

**Comment by ineu** [comment]
> Another thought is to just add a flag to get the cpu count. Maybe that would be faster?

I'm not sure it's a good idea to change the output type based on a flag (`table` vs `integer`). Maybe we should have different subcommands, e.g. `sys cpu cores` vs `sys cpu count`? Or even better a nested table like we have in `sys users`. Though `sys cpu | length` also looks idiomatic to me.

Another issue I see now is the `load_average` column. LA is a property of the running system, not the hardware, so it should live in `sys host` rather than `sys cpu`.

**Comment by fdncred** [comment]
I could change the PR to return a table instead of an int. It would just be weird to have a table for 1 item. I could return a record but it's the same diff as an int.

> Though sys cpu | length also looks idiomatic to me.

It's not really a question about being idiomatic. It's about speed.

> load average

Load average could be moved because it's a separate call that doesn't appear to be related to individual cpus.

**Comment by ineu** [comment]
> I could change the PR to return a table instead of an int. It would just be weird to have a table for 1 item. I could return a record but it's the same diff as an int.

From my point of view a command must always return/output the same structure. For example, `ls` always returns a table, each row representing a file. Options to `ls` can add additional rows or columns, but cannot change the output type from table to int. So to me an option would be confusing.

What do you think about a subcommand?
```
/home/ineu ▶ def 'sys cpu count' [] { nproc }                                                                11/29/2024 22:26:38
/home/ineu ▶ sys cpu                                                                                         11/29/2024 22:35:40
╭──────┬─────────┬─────────────────────────────────────────────┬─────────┬──────────────┬─────────────────────┬────────────────╮
│    # │  name   │                    brand                    │  freq   │  cpu_usage   │    load_average     │   vendor_id    │
├──────┼─────────┼─────────────────────────────────────────────┼─────────┼──────────────┼─────────────────────┼────────────────┤
│    0 │ cpu0    │ Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz    │     805 │         0.00 │ 0.10, 0.19, 0.33    │ GenuineIntel   │
│    1 │ cpu1    │ Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz    │     800 │         5.00 │ 0.10, 0.19, 0.33    │ GenuineIntel   │
│    2 │ cpu2    │ Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz    │     799 │         7.30 │ 0.10, 0.19, 0.33    │ GenuineIntel   │
│    3 │ cpu3    │ Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz    │     799 │         0.00 │ 0.10, 0.19, 0.33    │ GenuineIntel   │
│    4 │ cpu4    │ Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz    │     800 │         2.50 │ 0.10, 0.19, 0.33    │ GenuineIntel   │
│    5 │ cpu5    │ Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz    │     800 │         2.50 │ 0.10, 0.19, 0.33    │ GenuineIntel   │
│    6 │ cpu6    │ Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz    │     799 │         0.00 │ 0.10, 0.19, 0.33    │ GenuineIntel   │
│    7 │ cpu7    │ Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz    │     799 │         2.50 │ 0.10, 0.19, 0.33    │ GenuineIntel   │
╰──────┴─────────┴─────────────────────────────────────────────┴─────────┴──────────────┴─────────────────────┴────────────────╯
/home/ineu ▶ sys cpu count                                                                                   11/29/2024 22:35:43
8
```

> It's not really a question about being idiomatic. It's about speed.

What I mean is: if `cpu sys` was fast, then `sys cpu | length` would be more idiomatic than an option. So it's _simply_ a matter of making the list fast :)

Alas I'm not familiar with `sysinfo` crate (and Rust ecosystem in general) so it would take me a while to patch the crate.

**Comment by IanManske** [comment]
Since the load columns take a large amount of time, would it makes sense to them remove by default from the `sys cpu` output? Then, we could add a flag would be to add back those columns rather than having a flag specifically for cpu/core count?

**Comment by fdncred** [comment]
> What do you think about a subcommand?

`sys cpu count` wouldn't be a sub command, it would be a sub sub command, which we don't have right now.

> Since the load columns take a large amount of time

I'm not convinced that's what's taking the most time. There's at least a sysinfo-built-in 200ms delay to get cpu usage. If we take load average and cpu usage, the command isn't useful.

Some profiling would need to be done to see where most of the time is being taken other than the 200ms delay for cpu usage.

Personally, I don't have a problem with commands outputting different shapes. Although, I know some core team members do.

**Comment by IanManske** [comment]
> I'm not convinced that's what's taking the most time. There's at least a sysinfo-built-in 200ms delay to get cpu usage. If we take load average and cpu usage, the command isn't useful.

Ah yes, I meant the `cpu_usage` (one of the "load columns" in my head). With that disabled, the time is less than 1ms.
```nu
> timeit { sys cpu }
639µs 396ns
```

**Comment by fdncred** [comment]
ok, but the point of sys cpu is to get cpus and usage. I could see a sys cpu-load and sys cpu-count but I'm not sure what difference it makes just to have another flag that changes the output.

**Comment by IanManske** [comment]
> ok, but the point of sys cpu is to get cpus and usage.

We could, for example, add a `--long` flag that adds back the `cpu_usage` column. I don't think this goes against the purpose of `sys cpu`. Plus, it matches the `--long` flag pattern on `ls` and `ps`.

> I'm not sure what difference it makes just to have another flag that changes the output.

Having a flag that changes the output type hinders or even breaks type checking unfortunately.

**Comment by fdncred** [comment]
> Having a flag that changes the output type hinders or even breaks type checking unfortunately.

If that's the case, it should be applied in all commands for consistency. I'm not in favor of it.

> We could, for example, add a --long flag 

I could probably support a long flag but it's still the same diff. One will output a table with 1 column or a record and the other will output the normal table.

**Comment by IanManske** [comment]
> If that's the case, it should be applied in all commands for consistency. I'm not in favor of it.

I believe we try to, or at least try not to break type checking. I could only find a few commands that have incorrect types due to flags changing the return type:
- `into datetime --list`
- `to html --list`
- `uniq --count`
- `uniq-by --count`

There are other commands like `char --list` and `group-by --to-table` that can also change return type based on flags, but these commands return type `any`. This is not ideal since this essentially disables type checking, but the types are at least correct.

So, unless `sys cpu` is changed to return type `any`, typing checking will complain about mismatched types:

```nu
> [1 2] | par-each -t (sys cpu --cpu-count) {}
Error: nu::parser::type_mismatch

  × Type mismatch.
   ╭─[entry #1:1:21]
 1 │ [1 2] | par-each -t (sys cpu --cpu-count) {}
   ·                     ──────────┬──────────
   ·                               ╰── expected int, found table
   ╰────

```

> I could probably support a long flag but it's still the same diff. One will output a table with 1 column or a record and the other will output the normal table.

I meant that the `--long` flag would add back the `cpu_usage` column **in addition** to the other columns just like `ls --long` or `ps --long`. This way the output type is always `table`.

**Comment by fdncred** [comment]
@IanManske You should feel free to put up a PR to do it how you're saying it should be done. I'll close mine when you do.
