### ISSUE TITLE
`select`, `reject` and `get` do not stream

### ISSUE THREAD

**Issue by YPares** [nushell/nushell#14487]
### Related problem

When selecting columns out of a streamed table, `select` consumes the whole table before outputting something. But there should be no need for that when we just want to filter on columns, so one would sort of expect `select` to be able to work in a streamed fashion. The same goes for `reject` and `get`.

### Describe the solution you'd like

I'd like `$very_big_streamed_table | {select,reject} colX colY colZ` and `$very_big_streamed_table | get colX` to be able to return the filtered table/list in a streamed fashion.

### Describe alternatives you've considered

You have to use `each {select ...}` to instead have `select` operate on each individual record. This is not a complicated fix, granted, but it's still tedious on the command-line, and it makes it error-prone to remember which table filters need to be wrapped in `each` to maintain streaming and which do not (`insert`, `update`, etc).

**Comment by fdncred** [comment]
Looking at the code, it looks like select streams to me. The describe command also says it's a stream but there are several match statements, so I'd have to have a reproducible example that demonstrates your claim. Otherwise, it's hard to debug and figure out what you mean.

**Comment by cosineblast** [comment]
I think I can reproduce this issue:
```
(0..1)
| each {|it| if ($it == 0) { {name: bob, age: 20} } else { error make {msg: oops} } } 
| select name
| first
```
Ideally, this should give me a record `{name: bob}`, but it gives me the `oops` error:
![image](https://github.com/user-attachments/assets/665b7988-e9cb-453e-9af2-3c314881a049)

However, if we run this and replace `select name` by `each {|it| $it | select name}`, it doesn't produce the error, as `each` streams correctly:

![image](https://github.com/user-attachments/assets/d514ef09-dfac-4e82-aade-5f51c83739ee)

**Comment by fdncred** [comment]
This is interesting but I don't think that demonstrates a problem. With this pipeline:
```nushell
(0..1)
| each {|it| if ($it == 0) { {name: bob, age: 20} } else { error make {msg: oops} } } 
| select name
| first
```
you are constructing every element in the list _before_ you call `select`.

With your second pipeline you're intentionally telling it to iterate both each's one item at a time with a `select` _inside_ of the each while telling it to stop before it gets to index 1.

This would also fail if you had two each's and select outside of the each.
```nushell
❯ (0..1)
 | each {|it| if ($it == 0) { {name: bob, age: 20} } else { error make {msg: oops} } }
 | each {|it| $it } | select name
```

**Comment by cosineblast** [comment]
Indeed, thing is, as it currently behaves, `select`'s output isn't lazy, so whenever you do `thing | select name | first`, it will completely evaluate the stream `thing` before producing any results. I think @YPares suggests is that `select`'s output should be lazy, like `each`.

**Comment by YPares** [comment]
@fdncred I do agree with @cosineblast (thx for putting it up faster than I did). I would expect his first code excerpt _not_ to fail, because the second list element shouldn't be evaluated.

**Comment by fdncred** [comment]
You both may be right but I'm seeing it. I compare select vs each and the code is pretty similar. Of course, select works with cell paths and ints where each works with closures. I also see that select uses a custom pipeline iterator where each does not. They both work with ListStreams and do not call collect.

You should feel free to submit a PR that tries to change select to how you think it should work.

**Comment by fdncred** [comment]
It seems to work. Can you test with real data? https://github.com/nushell/nushell/pull/14492

**Comment by 132ikl** [comment]
This shouldn't be closed yet, since #14492 only fixes `select` but not `reject` and `get`, right?

**Comment by fdncred** [comment]
agreed. feel like working on them?

**Comment by 132ikl** [comment]
not right now, but this has been bugging me as well, so we'll see how tomorrow fares :rofl:

also, I was testing this a while ago and made this command to test. I was able to confirm your fix works:

```nushell
generate {|i| sleep 0.5sec; {out: {foo: $i bar: hi}, next: ($i + 1)} } 0 | select foo
```

(never outputs anything before #14492, but does output after #14492)

**Comment by fdncred** [comment]
I have `get` done but I'm not sure how to test it.

**Comment by 132ikl** [comment]
the above should work with `get` and `reject` as well, just replace the `select` :smile:

**Comment by fdncred** [comment]
That's what I thought. Either I did something wrong, or it just doesn't work. I get the same error before and after my change.

```nushell
❯ (0..1)
❯❯❯ | each {|it| if ($it == 0) { {name: bob, age: 20} } else { error make {msg: oops} } }
❯❯❯ | get name
❯❯❯ | first
Error: nu::shell::column_not_found

  × Cannot find column 'name'
   ╭─[entry #5:1:2]
 1 │ (0..1)
   ·  ──┬─
   ·    ╰── value originates here
 2 │ | each {|it| if ($it == 0) { {name: bob, age: 20} } else { error make {msg: oops} } }
 3 │ | get name
   ·       ──┬─
   ·         ╰── cannot find column 'name'
 4 │ | first
   ╰────
```

**Comment by fdncred** [comment]
I may just start over tomorrow. It's late.

**Comment by fdncred** [comment]
> I will give this a try.

Thanks @cosineblast . I've already fixed `select` (hopefully). The other commands remain though. Good luck. We appreciate your help.
