### ISSUE TITLE
`open /dev/random` hangs Nu

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1448]
**Describe the bug**
`open /dev/random`

**To Reproduce**
1. `open /dev/random`

**Expected behavior**
This should stream out

**Comment by jonathandturner** [comment]
I think we might want to switch `open` and `fetch` to outputting a stream of data that is handled by MaybeTextCodec. Then, moving the logic to handle encodings like utf-16 LE and BE into MaybeTextCodec.

**Comment by arashout** [comment]
I would like to work on this because I want to learn more about Streams/Streaming.
I'll probably need lot of help with this

**Comment by arashout** [comment]
Resolved by the above PR.
Still need to work on https://github.com/nushell/nushell/issues/1898
