### ISSUE TITLE
Tests hang in commands::use_::use_main_not_exported when /usr/bin/spam exists

### ISSUE THREAD

**Issue by musicinmybrain** [nushell/nushell#14515]
### Describe the bug

On a rather normal, fully updated Fedora 41 installation, `cargo test --workspace` hangs in `commands::use_::use_main_not_exported`, apparently forever.

Skipping this test (`cargo test --workspace -- --exact --skip commands::use_::use_main_not_exported`) works, as does `cargo run -- -c "use toolkit.nu; toolkit test stdlib"`.

After a bit of investigation with `ps` and `strace`, I found that the test had executed `/usr/bin/spam`, which is part of the [`opensp` package in Fedora](https://src.fedoraproject.org/rpms/opensp), and `/usr/bin/spam` was blocked waiting for input. It turns out that removing the `opensp` package so that there is no `spam` in the `PATH` also fixes the test.

I don’t understand nushell well enough to propose a fix, but it seems like for the tests in `crates/nu-command/tests/commands/use_.rs` that use a `spam.nu` test script, the path search priority should be such that it isn’t “overridden” by the presence of a `/usr/bin/spam`.

### How to reproduce

```
$ sudo dnf install opensp
$ git clone https://github.com/nushell/nushell
$ cd nushell
$ cargo test --workspace
[…]
test commands::ucp::copy_file_with_update_flag ... ok
test commands::use_::use_main_not_exported has been running for over 60 seconds
```

### Expected behavior

All tests pass regardless of what might or might not be present in `/usr/bin`.

### Configuration

> version | transpose key value | to md --pretty                                                                                                                       12/04/2024 06:48:27 PM
| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.100.1                                                    |
| major              | 0                                                          |
| minor              | 100                                                        |
| patch              | 1                                                          |
| branch             | main                                                       |
| commit_hash        | 05b7c1fffa24d91328414aa09d3560d01be01753                   |
| build_os           | linux-x86_64                                               |
| build_target       | x86_64-unknown-linux-gnu                                   |
| rust_version       | rustc 1.83.0 (90b35a623 2024-11-26) (Fedora 1.83.0-1.fc41) |
| cargo_version      | cargo 1.83.0 (5ffbef321 2024-10-29)                        |
| build_time         | 2024-12-04 18:47:39 -05:00                                 |
| build_rust_channel | debug                                                      |
| allocator          | mimalloc                                                   |
| features           | default, sqlite, trash                                     |
| installed_plugins  |                                                            |

**Comment by 132ikl** [comment]
Shoot, I ran into this previously but forgot to fix it. Give me a few minutes...

**Comment by 132ikl** [comment]
Related: #11261 #8463 #12958

**Comment by fdncred** [comment]
One approach is to name such test harness things like nu_*_suffix nu_spam_test123.

**Comment by musicinmybrain** [comment]
Thank you!
