### ISSUE TITLE
polars with-column name flag

### ISSUE THREAD

**Issue by reider-dev** [nushell/nushell#14512]
### Describe the bug

running

```nu
let df = [ { a: 0 },{ a: 1 }] 
| polars into-df 
| polars with-column -n b ( polars lit (-1) ) 
| polars collect

$df | print
```

produces

```nu
╭───┬───┬─────────╮
│ # │ a │ literal │
├───┼───┼─────────┤
│ 0 │ 0 │      -1 │
│ 1 │ 1 │      -1 │
╰───┴───┴─────────╯
```

where the column name does not seems to be derived from the polars lit function instead of the with-columns name flag.

### How to reproduce

run the following the snippet above.

### Expected behavior

I would expect the -n or --name flag to work such that the result has a column names "b" instead of "literal"

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.100.0                             |
| major              | 0                                   |
| minor              | 100                                 |
| patch              | 0                                   |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.83.0 (90b35a623 2024-11-26) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.83.0 (5ffbef321 2024-10-29) |
| build_time         | 2024-12-03 06:08:48 +01:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash              |
| installed_plugins  | polars 0.100.0                      |

**Comment by fdncred** [comment]
That seems like a bug to me. @ayax79 what do you think?

You could also use `polars as` like this.
```nushell
let df = [ { a: 0 },{ a: 1 }]
  | polars into-df
  | polars with-column ( polars lit (-1) | polars as "b" )
  | polars collect

$df
╭─#─┬─a─┬─b──╮
│ 0 │ 0 │ -1 │
│ 1 │ 1 │ -1 │
╰───┴───┴────╯
```

**Comment by ayax79** [comment]
Currently `--name` only works with eager dataframes. Making it work with lazy dataframes would mean forcing the equivalent of the `polars as` into the lazyframe's logical plan. That could cause some odd behavior. 

The right solution is probably to remove the `--name` flag all together and explicit eager dataframe support. I have been considering removing the eager implementation from most of the commands that support both anyways. What this would mean is if you run a command that works with lazy frames, it will convert the dataframe to a lazyframe. This would also be more efficient if you are executing multiple lazy frame commands, it would just require an explicit `polars collect` at the end.

**Comment by fdncred** [comment]
I agree. It's probably best to start with removing the `--name` flag.

As far as removing eager, it seems like you went down that path and ran into some roadblock and reverted. I can't remember exactly. I could be making that up.

**Comment by ayax79** [comment]
> I agree. It's probably best to start with removing the `--name` flag.
> 
> As far as removing eager, it seems like you went down that path and ran into some roadblock and reverted. I can't remember exactly. I could be making that up.

I believe it had something to do with mixing multiple dataframes, I would need to go look. As in interim solution, we could just document `--name` better and cause an error to happen when using a lazyframe.

**Comment by ayax79** [comment]
Added documentation and errors: https://github.com/nushell/nushell/pull/14527
