### ISSUE TITLE
dataframe combining logical masks

### ISSUE THREAD

**Issue by reider-dev** [nushell/nushell#14518]
### Describe the bug

I would like to combine logical masks as presented in the  [documenation](https://www.nushell.sh/book/dataframes.html#series-and-masks)

### How to reproduce

running:

```nu
(true | polars into-df) and (false | polars into-df)
```

returns:
```nu
Error: nu::shell::type_mismatch

  × Type mismatch.
   ╭─[entry #25:1:9]
 1 │ (true | polars into-df) and (false | polars into-df)
   ·         ───────┬──────
   ·                ╰── expected bool
   ╰────
```

### Expected behavior

not error

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.100.0                             |
| major              | 0                                   |
| minor              | 100                                 |
| patch              | 0                                   |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.83.0 (90b35a623 2024-11-26) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.83.0 (5ffbef321 2024-10-29) |
| build_time         | 2024-12-03 06:08:48 +01:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash              |
| installed_plugins  | polars 0.100.0                      |

**Comment by reider-dev** [comment]
> This seems correct to me because `and` needs a boolean result and `true | into-df` returns a NuDataFrame which is not a boolean. it's similar to doing `1 and 3`, which also produces an error, since 1 and 3 are not bools.

How should I interpret the error messages from the following two commands? In test 1 the error suggests the left hand argument is a "NuDataFrame", while the second suggests a "Series of type bool". Am I missing something?

## test 1
```nu
# running
(true | polars into-df) == true

# returns
Error: nu::shell::type_mismatch

  × Type mismatch during operation.
   ╭─[entry #24:1:9]
 1 │ (true | polars into-df) == true
   ·         ───────┬──────  ─┬ ──┬─
   ·                │         │   ╰── bool
   ·                │         ╰── type mismatch for operator
   ·                ╰── NuDataFrame
   ╰────
```

## test 2
```nu
# running
(true | polars into-df) == 0

# returns
Error:   × Incorrect type
   ╭─[entry #25:1:9]
 1 │ (true | polars into-df) == 0
   ·         ───────┬──────
   ·                ╰── Series of type bool can not be used for operations with an i64 value
   ╰────
```

**Comment by fdncred** [comment]
```nushell
true | polars into-df | describe
NuDataFrame
```
So, test1 is correct. test2 may be reporting the wrong error.

**Comment by reider-dev** [comment]
I still have the impression something is not working correctly. Test 1 and 2 work as expected, but combing masks with the logical operator fails.  The documentation (linked in initial comment) suggests it should work.
```nu
# basic setup
let df = [{a: 1},{a: 2},{a: 3}] | polars into-df

# test 1
$df | polars set (-1) --mask ($df > 1)
╭───┬────╮
│ # │ a  │
├───┼────┤
│ 0 │  1 │
│ 1 │ -1 │
│ 2 │ -1 │
╰───┴────╯

# test 2
$df | polars set (-1) --mask ($df < 3)
╭───┬────╮
│ # │ a  │
├───┼────┤
│ 0 │ -1 │
│ 1 │ -1 │
│ 2 │  3 │
╰───┴────╯

# test 3
$df | polars set (-1) --mask (($df > 1) and ($df < 3))
Error: nu::shell::type_mismatch

  × Type mismatch.
   ╭─[entry #11:1:32]
 1 │ $df | polars set (-1) --mask (($df > 1) and ($df < 3))
   ·                                ───┬───
   ·                                   ╰── expected bool
   ╰────

polars set (-1) --mask (($df > 1) and ($df < 3))

**Comment by fdncred** [comment]
@ayax79 any ideas here?

**Comment by ayax79** [comment]
I'll have to dig into this a bit.. I am not as familiar with the workings of `polars set`.. It does look like the code has a lot of explicit checks for boolean types.

**Comment by reider-dev** [comment]
> I'll have to dig into this a bit.. I am not as familiar with the workings of `polars set`.. It does look like the code has a lot of explicit checks for boolean types.

I have the impression the error stems from boolean operations of polars series.. the error is throw if you just try and run:

```nu
($df > 1) and ($df < 3)
```

**Comment by ayax79** [comment]
@reider-dev,

Yeah, that makes sense. `and` is a nushell command and wouldn't understand how to handles dataframes of booleans. It expects two nushell boolean values. My guess if we will have to make a custom command.. I don't immediately see a way to override `and` functionality like overriding operators.. @fdncred, am I missing something?

**Comment by ayax79** [comment]
Actually, I think I found it.. It just hasn't been implemented in polars/dataframe/values/nu_dataframe/between_values.rs

**Comment by ayax79** [comment]
More investigation. For some reason I don't think the plugin is being called when Operator::Booean(Boolean::And) operations happen.

**Comment by ayax79** [comment]
In 0.98 with the new IR feature disabled, the following works.. note that the column needs to be called out directly.
```nushell
($df.a > 1) and ($df.a < 3)
```

I'll connect with @devyn some more.. It looks like none of the custom value add stuff is getting called when using IR.

**Comment by devyn** [comment]
I think I've found a fix for this. Thanks for reporting!
