### ISSUE TITLE
Newline delimited nuon (ndnuon) does not work with multiline strings

### ISSUE THREAD

**Issue by 132ikl** [nushell/nushell#14517]
### Describe the bug

You cannot round-trip a multi-line string through ndnuon.

cc @amtoine 

### How to reproduce

```nushell
"foo\nbar" | to ndnuon | from ndnuon
# => Error: nu::shell::eval_block_with_input
# => 
# =>   × Eval block failed with pipeline input
# =>     ╭─[std/formats/mod.nu:39:30]
# =>  38 │ export def "to ndnuon" []: [any -> string] {
# =>  39 │     each { to nuon --raw } | to text
# =>     ·                              ───┬───
# =>     ·                                 ╰── source value
# =>  40 │ }
# =>     ╰────
# => 
# => Error: 
# =>   × error when loading nuon text
# =>     ╭─[std/formats/mod.nu:34:20]
# =>  33 │ export def "from ndnuon" []: [string -> any] {
# =>  34 │     lines | each { from nuon }
# =>     ·                    ────┬────
# =>     ·                        ╰── could not load nuon text
# =>  35 │ }
# =>     ╰────
# => 
# => Error: 
# =>   × error when parsing nuon text
# =>     ╭─[std/formats/mod.nu:34:20]
# =>  33 │ export def "from ndnuon" []: [string -> any] {
# =>  34 │     lines | each { from nuon }
# =>     ·                    ────┬────
# =>     ·                        ╰── could not parse nuon text
# =>  35 │ }
# =>     ╰────
# => 
# => Error: 
# =>   × error when parsing
# =>    ╭────
# =>  1 │ "foo
# =>    ·    ┬
# =>    ·    ╰── Unexpected end of code.
# =>    ╰────
```

### Expected behavior

Multiline strings should persist through ndnuon roundtrip. Probably should be escaped as `\n`.

### Configuration

| key                | value                                                                                                                                                              |
| ------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| version            | 0.100.1                                                                                                                                                            |
| major              | 0                                                                                                                                                                  |
| minor              | 100                                                                                                                                                                |
| patch              | 1                                                                                                                                                                  |
| branch             | makepkg                                                                                                                                                            |
| commit_hash        | a3327122755c00ae9384320e519a1257b91d424f                                                                                                                           |
| build_os           | linux-x86_64                                                                                                                                                       |
| build_target       | x86_64-unknown-linux-gnu                                                                                                                                           |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04)                                                                                                                                |
| rust_channel       | 1.81.0-x86_64-unknown-linux-gnu                                                                                                                                    |
| cargo_version      | cargo 1.81.0 (2dbb1af80 2024-08-20)                                                                                                                                |
| build_time         | 2024-12-04 09:00:11 +00:00                                                                                                                                         |
| build_rust_channel | release                                                                                                                                                            |
| allocator          | mimalloc                                                                                                                                                           |
| features           | default, sqlite, trash                                                                                                                                             |
| installed_plugins  | custom_values 0.1.0, explore 0.99.1, explore_ir 0.5.0, formats 0.98.0, gstat 0.98.0, inc 0.98.0, jwalk 0.8.0, polars 0.98.0, query 0.98.0, stress_internals 0.98.0 |

**Comment by amtoine** [comment]
ooh wow i just stumbled upon that in an NDNUON file yesterday :thinking:

**Comment by amtoine** [comment]
the thing is there might be literal `\n` in there as well :confused:

**Comment by amtoine** [comment]
i think strings could be encoded as follows:
```nushell
"foo\n\\n\nbar" | to nuon | str replace --all "\n" '\n'
```
but, throwing `lines` in there breaks the input line into a list with three elements :thinking:
