### ISSUE TITLE
polars set dtype

### ISSUE THREAD

**Issue by reider-dev** [nushell/nushell#14511]
### Question

I would like to  use the polars set  with the  --mask option.  I do something like:

```nu
# create dataframe
let df = [ { a: 0 },{ a: 1 }] 
| polars into-df 
| polars with-column -n b ( polars lit (-1) ) 
| polars rename literal b
| polars collect

# create mask
let mask = ( $df | polars get a ) > 0

# try to set some rows to 0 using the mask
$df 
| polars with-column (
    $df
    | polars get b
    | polars set 0 --mask $mask
)
```

The result I get is an error:
```nu
Error:   × Error casting to i64
   ╭─[entry #43:1:59]
 1 │ $df | polars with-column ($df | polars get b | polars set 0 --mask $mask)
   ·                                                           ┬
   ·                                                           ╰── invalid series dtype: expected `Int64`, got `i32`
   ╰────
```

Is this expected behavior? Do I need to somehow cast the constant?

### Additional context and details

|version|major|minor|patch|branch|commit_hash|build_os|build_target|rust_version|rust_channel|cargo_version|build_time|build_rust_channel|allocator|features|installed_plugins|
|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|
|0.100.0|0|100|0|||linux-x86_64|x86_64-unknown-linux-gnu|rustc 1.83.0 (90b35a623 2024-11-26)|stable-x86_64-unknown-linux-gnu|cargo 1.83.0 (5ffbef321 2024-10-29)|2024-12-03 06:08:48 +01:00|release|mimalloc|default, sqlite, trash|polars 0.100.0|

**Comment by reider-dev** [comment]
> I think you need to cast it like this but @ayax79 may have other ideas. If you're opening a file, you can specify the schema on open with --schema. You can also apply a --schema on `polars into-df` but you're adding a column with `polars lit` which I don't think allows a dtype to be specified.
> 
> ```nushell
> $df
> | polars with-column (
>   $df
>   | polars cast i64 b
>   | polars get b
>   | polars set 0 --mask $mask
> ) | polars collect
> ╭─#─┬─a─┬─b──╮
> │ 0 │ 0 │ -1 │
> │ 1 │ 1 │  0 │
> ╰───┴───┴────╯
> ```

That's a very workable solution, thank you. 

It could be a nice feature request to attempt to cast or specify the input set value data type.

**Comment by ayax79** [comment]
I think this is a good solution. A couple of different things you could do when creating the dataframe:

This is a cleaned version of what you have above that casts the datatype on creation.
```nushell
let df = [ { a: 0 },{ a: 1 }]
  | polars into-df
  | polars with-column ( polars lit (-1) | polars cast i64 | polars as b)
  | polars collect
```

This one uses the schema flag to add a new column:
```nushell
let df = [ { a: 0 },{ a: 1 }] 
  | polars into-df -s {a: u16, b: i64} 
  | polars collect
```

**Comment by fdncred** [comment]
@reider-dev are we good to close this?

**Comment by reider-dev** [comment]
While I think there is a use case to infer the intended input scalar datatype by attempting to cast to the series datatype, I am happy with the possible solutions. 

I am quite enjoying learning to use polars and nushell. Thanks for help.
