### ISSUE TITLE
Custom completion sorts alphabetically by default

### ISSUE THREAD

**Issue by yerlaser** [nushell/nushell#14547]
### Describe the bug

When I create custom completions and return a list it gets sorted internally by Nushell.
This becomes a problem when the list comes from `git log` where entries appear in the date sorted order (newest at the top).
Alphabetically sorting this list makes no sense

### How to reproduce

Create a custom completer that outputs [aa cc bb] and observe that the output gets sorted alphabetically

### Expected behavior

The list should not be sorted by default, the creator of the completer needs to take care of sorting as it fits to the purpose

### Configuration

0.100.1

**Comment by fdncred** [comment]
I thought you could create a custom completer that sorted however you want. @ysthakur may remember.

**Comment by ysthakur** [comment]
Ah yeah, the behavior you're looking for was indeed the original behavior, but there was a regression in July. This was fixed in https://github.com/nushell/nushell/pull/14424, which was merged just last week. It's in main right now, if you're able to build Nushell from source. If not, this should be included in the next release, which is on the 24th of December.

**Comment by NotTheDr01ds** [comment]
@ysthakur Are you sure?  I just ran the following MRE in the latest main, and it still has the results above.

MRE:

```nushell
def comp [] { [ cc bb aa ] }
def foo [x: string@comp] {}
```

No matter how you sort in the completer, it's going to come out alphabetized.

The alternative is an "external" completer which can be customized quite a bit more.

```nushell
$env.config.completions.external.completer = {|spans|
  match $spans.0 {
    foo => [ cc bb aa ]
    _ => []
  }
}
def foo [x] {}
```

This works in both 0.100 and latest main.

**Comment by NotTheDr01ds** [comment]
@ysthakur Oh ... I see.  That's a change I didn't know about.  I need to try out the record return, I guess.

**Comment by NotTheDr01ds** [comment]
Full MRE modified:

```nushell
def comp [] {
  {
    completions: [ cc bb aa ]
    options: {
      completion_algoritm: fuzzy
      sort: false
    }
  }
}

def foo [x: string@comp] {}
```

**Comment by NotTheDr01ds** [comment]
@ysthakur How long have we been able to return a record for a custom-completion?  It doesn't look like that's a new change from your recent PR, but I've never seen it mentioned (or documented) before.

**Comment by ysthakur** [comment]
@NotTheDr01ds Not sure. This commit from 2022 allows the suggestions themselves to be records, but returning a record for the entire thing with an `options` field seems to have existed even before that: https://github.com/nushell/nushell/commit/661283c4d2f00dd49c55895a88ab386a6b14954b. We should definitely document it, yeah.

**Comment by yerlaser** [comment]
Oh, OK. I see now.
Thanks a lot for your help!
