### ISSUE TITLE
`nu -c history` bug.

### ISSUE THREAD

**Issue by romancitodev** [nushell/nushell#14543]
### Describe the bug

I think this is a weird bug, because for some reason if I run `history` in my session, all the history data is brought back as expected. But the moment I run `nu -c history` (it should be expected to return the same history data) it just returns nothing.

I was testing and noticed that it gets the data from `history.txt` but I use sqlite.

### How to reproduce

1. open a new terminal
2. exec `nu -c history`

### Expected behavior

`nu -c history` should returns the same as `history`.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.100.0                                  |
| major              | 0                                        |
| minor              | 100                                      |
| patch              | 0                                        |
| branch             |                                          |
| commit_hash        | 30f98f7e64a63a159ce70f02aa6c4c1196cd9ca7 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.80.1 (3f5fd8dd4 2024-08-06)      |
| rust_channel       | 1.80.1-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.80.1 (376290515 2024-07-16)      |
| build_time         | 2024-11-13 03:41:46 +00:00               |
| build_rust_channel | release                                  |
| allocator          | mimalloc                                 |
| features           | default, sqlite, trash                   |
| installed_plugins  | clipboard 0.100.0                        |

**Comment by romancitodev** [comment]
![image](https://github.com/user-attachments/assets/b6d07707-e875-49ce-83cb-35621350e79d)

**Comment by NotTheDr01ds** [comment]
> I was testing and noticed that it gets the data from `history.txt` but I use sqlite.

Can you show the results of:

```nushell
$env.config.history
```

The behavior you are seeing is expected with some configurations.

**Comment by romancitodev** [comment]
Yeah, those are the results:

```
+---------------+--------+
| max_size      | 100000 |
+---------------+--------+
| sync_on_enter | true   |
+---------------+--------+
| file_format   | sqlite |
+---------------+--------+
| isolation     | false  |
+---------------+--------+
```

![image](https://github.com/user-attachments/assets/05a94208-ee6e-4504-bcfc-ba635cec8e08)

**Comment by romancitodev** [comment]
Thanks! The first one just work for me!
