### ISSUE TITLE
Pattern matching with raw string as pattern doesn't match

### ISSUE THREAD

**Issue by chklauser** [nushell/nushell#14554]
### Describe the bug

Pattern matching a string against a raw string (`r#''#`) as a pattern doesn't match. 
 * `==` against the raw string works fine

This is very surprising to me. Pattern matching shouldn't care, which literal syntax I've used (as long as it's a literal constant).

Why am I doing this? Because I'm generating the nushell code in question and the pattern text (the thing in quotes) is not a value that I control. I wanted to use raw strings to make the generator a bit more robust to weird inputs.

### How to reproduce

```nu
match "jj" { r#'jj'# => true, _ => false }
```
(returns `false`)

### Expected behavior

`true`

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.100.0                             |
| major              | 0                                   |
| minor              | 100                                 |
| patch              | 0                                   |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | windows-x86_64                      |
| build_target       | x86_64-pc-windows-msvc              |
| rust_version       | rustc 1.82.0 (f6e511eec 2024-10-15) |
| rust_channel       | stable-x86_64-pc-windows-msvc       |
| cargo_version      | cargo 1.82.0 (8f40fc59f 2024-08-21) |
| build_time         | 2024-11-13 18:41:32 +01:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash              |
| installed_plugins  |                                     |

**Comment by NotTheDr01ds** [comment]
I can't think of a good reason that shouldn't match, other than a bug.

However, you might be able to work around it with a guard expression. For example:

```nushell
match "jj" {
  $x if $x == r#'jj'# => true,
  _ => false
}
# => true
```
