### ISSUE TITLE
`echo 1; echo 2` only prints "2"

### ISSUE THREAD

**Issue by Gremious** [nushell/nushell#14576]
### Describe the bug

I was trying to figure out how to "&&" in nushell and tried `echo 1; echo 2` but it would only print 2 (any parameters triggers the bug).

`git pull; echo a` works fine with 

```
Already up to date.
1
```

though

`echo 1; git pull; echo 2`
skips the first echo 

```
Already up to date.
2
```

### How to reproduce

Type `echo 1; echo 2` in shell

### Expected behavior

It prints

```
1
2
```

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.100.0                                                          |
| major              | 0                                                                |
| minor              | 100                                                              |
| patch              | 0                                                                |
| branch             | makepkg                                                          |
| commit_hash        | 30f98f7e64a63a159ce70f02aa6c4c1196cd9ca7                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.82.0 (f6e511eec 2024-10-15) (Arch Linux rust 1:1.82.0-2) |
| cargo_version      | cargo 1.82.0 (8f40fc59f 2024-08-21)                              |
| build_time         | 2024-11-13 08:00:49 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | mimalloc                                                         |
| features           | default, sqlite, trash                                           |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment]
This is expected because nushell only returns the last value. If you want to see both, you should use print.
```nushell
❯ print 1;print 2
1
2
```
I'm sure there is more information about this in our documentation. Here's a start. https://www.nushell.sh/book/stdout_stderr_exit_codes.html#echo-print-and-log-commands

**Comment by NotTheDr01ds** [comment]
A common question - I have a PR I sent last night to add it to the [Thinking in Nu](https://www.nushell.sh/book/thinking_in_nu.html) Chapter.
