### ISSUE TITLE
Add coalesce option to polars full join

### ISSUE THREAD

**Issue by johnalotoski** [nushell/nushell#14572]
### Related problem

The dataframe command prior to polars offered an outer join:
```
dfr join --outer <other> <left_on> <right_on>
```
With this, two tables having columns of `A, B`, and `A, C` being left_on and right_on joined on `A` would get joined to a table with columns of `A, B, C`.

The polars dataframe replacement does not offer an equivalent outer join, but instead a full join which for the above case instead creates a dataframe table having output columns of `A, B, A_x, C`.

### Describe the solution you'd like

The upstream polars source seems to [provide a way](https://docs.pola.rs/user-guide/transformations/joins/#full-join) to obtain prior `dfr join -o ...` behavior by setting `coalesce=True` to arrive at `A, B, C` output.

Could a polars coalesce option on full join be added to nu to achieve prior functionality?

### Describe alternatives you've considered

Some extra code to iterate over the rows and manually coalesce the A, A_x columns and then reject column A_x.

**Comment by fdncred** [comment]
My guess is that we'd accept a PR for the change you're requesting.

/cc @ayax79

**Comment by johnalotoski** [comment]
Thank you @fdncred.  Not sure if I'll be able to do the PR, but here is a minimum repro sample:
```
# Sample tables
> let table1 = [[A B]; ["common" "common"] ["table1" "only"]]
> let table2 = [[A C]; ["common" "common"] ["table2" "only"]]

> $table1
╭───┬────────┬────────╮
│ # │   A    │   B    │
├───┼────────┼────────┤
│ 0 │ common │ common │
│ 1 │ table1 │ only   │
╰───┴────────┴────────╯

> $table2
╭───┬────────┬────────╮
│ # │   A    │   C    │
├───┼────────┼────────┤
│ 0 │ common │ common │
│ 1 │ table2 │ only   │
╰───┴────────┴────────╯

# On the legacy pandas dfr:
> nu --version
0.93.0

> $table1 | dfr into-df | dfr join -o ($table2 | dfr into-df) A A
╭───┬────────┬────────┬────────╮
│ # │   A    │   B    │   C    │
├───┼────────┼────────┼────────┤
│ 0 │ common │ common │ common │
│ 1 │ table2 │        │ only   │
│ 2 │ table1 │ only   │        │
╰───┴────────┴────────┴────────╯

# On the current polars dfr:
> nu --version
0.100.0

> $table1 | polars into-df | polars join -f ($table2 | polars into-df) A A
╭───┬────────┬────────┬────────┬────────╮
│ # │   A    │   B    │  A_x   │   C    │
├───┼────────┼────────┼────────┼────────┤
│ 0 │ common │ common │ common │ common │
│ 1 │        │        │ table2 │ only   │
│ 2 │ table1 │ only   │        │        │
╰───┴────────┴────────┴────────┴────────╯

# Command to make polars full join equivalent behavior to pandas outer join:
> $table1 | polars into-df | polars join -f ($table2 | polars into-df) A A
   | polars into-nu
   | update A {|i| if $i.A == null { $i.A_x } else { $i.A } }
   | reject A_x
   | polars into-df
╭───┬────────┬────────┬────────╮
│ # │   A    │   B    │   C    │
├───┼────────┼────────┼────────┤
│ 0 │ common │ common │ common │
│ 1 │ table2 │        │ only   │
│ 2 │ table1 │ only   │        │
╰───┴────────┴────────┴────────╯
```

**Comment by ayax79** [comment]
The `--outer` feature went away after it was removed from polars core in version 0.41. It was replace by `JoinType::Full` which I exposed through `--full`

**Comment by ayax79** [comment]
I'll have a PR out soon that adds a new flag `--coalesce-columns`:

```nushell
> ❯ : $table1 | polars into-df | polars join -f ($table2 | polars into-df) --coalesce-columns A A
╭───┬────────┬────────┬────────╮
│ # │   A    │   B    │   C    │
├───┼────────┼────────┼────────┤
│ 0 │ common │ common │ common │
│ 1 │ table2 │        │ only   │
│ 2 │ table1 │ only   │        │
╰───┴────────┴────────┴────────╯
```
