### ISSUE TITLE
Support reading newline delimited JSON (ndjson)

### ISSUE THREAD

**Issue by lewisdiamond** [nushell/nushell#1458]
First, what is nushell made for? Is it meant as an everyday shell or is it focused on data manipulation?

I'm trying to use nushell to manipulate large amounts of data and there are many things missing. One important thing is the lack of newline delimited json support. I want to pipe large ndjson files to filters and aggregate functions but I can't seem to get that working.

**Describe the solution you'd like**

`open myfile.ndjson | where myField == "something" | select myOtherField | sum` to sum all values of `myOtherField` of objects (json) where `myField` is equal to "something". (I'm using `select` as an example, I don't know if it exists or not or if there's an equivalent under another name)

**Describe alternatives you've considered**
`< myfile.ndjson jq -rc 'select(myField == "something") | .myOtherField'  |  somethingThatSums?`

**Comment by jonathandturner** [comment]
You can use the `from-json -o` command to convert JSON where each line is a separate JSON object.

`open myfile.ndjson | from-json -o | where myField == "something" | get myOtherField | sum`

**Comment by thegedge** [comment]
Seems reasonable to have `open *.ndjson` be the same as `open | from-json -o`. What do you think, @jonathandturner ?

> First, what is nushell made for? Is it meant as an everyday shell or is it focused on data manipulation?

It's a bit of both 🙂

Once mature enough, nushell should be able to replace the everyday shell.

**Comment by waldyrious** [comment]
I for one would like to see this feature implemented :)
