### ISSUE TITLE
No `$env.config.color_config.glob` option

### ISSUE THREAD

**Issue by PerchunPak** [nushell/nushell#14600]
### Describe the bug

Setting `$env.config.color_config.glob` gives me `cannot find column 'glob'`, looks like it is not defined in code, but I can find some references to it.

https://github.com/nushell/nushell/blob/39770d41975a0dae3cdc89802215416a4c6671e4/crates/nu-color-config/src/style_computer.rs#L97
https://github.com/nushell/nushell/blob/39770d41975a0dae3cdc89802215416a4c6671e4/crates/nu-color-config/src/style_computer.rs#L114

### How to reproduce

1. Run `$env.config.color_config.glob`

### Expected behavior

no error

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.100.1                                                           |
| major              | 0                                                                 |
| minor              | 100                                                               |
| patch              | 1                                                                 |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.82.0 (f6e511eec 2024-10-15) (built from a source tarball) |
| cargo_version      | cargo 1.82.0 (8f40fc59f 2024-08-21)                               |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | mimalloc                                                          |
| features           | default, sqlite, trash                                            |
| installed_plugins  |                                                                   |

Installed on NixOS from 3760910f0bbf58e25787ee685046cd2837924882

**Comment by NotTheDr01ds** [comment]
Good catch - Looks like it's been missing for a while.  I'll add it to the default config so it will get populated.

**Comment by PerchunPak** [comment]
Looks like `$env.config.color_config.closure` has the same issue

**Comment by fdncred** [comment]
I thought this was `shape_globpattern`?

**Comment by NotTheDr01ds** [comment]
@fdncred There's both.  The `glob` is what would show in:

```nushell
let a: glob = "*"
$env.config.color_config.glob = "red"
{
  glob: $a
}

# => ╭──────┬───╮
# => │ glob │ * │
# => ╰──────┴───╯
```

The glob in structured data is styled via the `.glob`.

On the other hand:

```nushell
$env.config.color_config.shape_globpattern = "black"
def foo [x: glob] {}
foo "*"
```

The argument to `foo` will be styled via `.shape_globpattern`

**Comment by NotTheDr01ds** [comment]
I'm not quite sure how to demonstrate `$env.config.color_config.closure`, however.  The `<closure xxx>` will never be styled, AFAICT.

**Comment by fdncred** [comment]
Thanks for the examples

**Comment by PerchunPak** [comment]
Looks like I found one more: `$env.config.color_config.shape_raw_string`

**Comment by NotTheDr01ds** [comment]
@PerchunPak Thanks!

All of the above *except* `shape_garbage` appear to be there.  I'm adding that one (building while I type this).
