### ISSUE TITLE
Commands missing globs

### ISSUE THREAD

**Issue by pontaoski** [nushell/nushell#1462]
Some commands that a user would expect to have globbing support don't have globbing support:

- [ ] open (`open *.json`)
- [x] rm (`rm vgcore.*`)

**Comment by codri** [comment]
Powershell also supports globs in cd, and glob expansion. That's a very handy feature for jumping around.
Ex, having the following folder structure:
```
/pwd
  /test
  /test1
    /nested1
  /test2
```

You can do the following in Powershell
`cd *1` and enter to navigate to test1, or `cd *1<Tab>` to expand the glob, and cycle through multiple results.
`cd *st` and tab would cycle through all of the top level folders.
Globs also work for nested folders, ex: `cd */*nes` will match the nested folder.
