### ISSUE TITLE
Online documentation book is not searchable

### ISSUE THREAD

**Issue by klausi** [nushell/nushell#1464]
The book at https://www.nushell.sh/book/en/table_of_contents.html does not have a search bar, so I was not able to find information how to replace a command with the original bash command in #749 .

Any chance a search input can be added there?

**Comment by thegedge** [comment]
Definitely think a search bar would be a good feature :+1:

**Comment by klausi** [comment]
There is a search field now at https://www.nushell.sh , so this if fixed!
