### ISSUE TITLE
mkdir: dot followed by number followed by underscore: "x.0_"

### ISSUE THREAD

**Issue by reuvenab** [nushell/nushell#1465]
**Describe the bug**
mkdir fails when trying to create directory name in format  "x.0_"
(dot followed by number followed by underscore)

**To Reproduce**
1. mkdir x.0_

**Expected behavior**
Directory named after x.0_ to be created

**Screenshots**
![image](https://user-images.githubusercontent.com/85445/76163998-a5cbd400-6153-11ea-9c59-b77523ea4488.png)

**Configuration (please complete the following information):**
 - OS: Windows 10
 - Version 0.10.1

Issue could be seen before issuing actual command, when typing.
Error message looks similar to https://github.com/nushell/nushell/issues/1186 so may be error in the command line parser

**Comment by humancalico** [comment]
It seems like any number or a special character after the dot doesn't work. 
![Screenshot from 2020-03-08 22-01-30](https://user-images.githubusercontent.com/51334444/76167923-62438b00-6190-11ea-8ab4-311447e9db2c.png)
![Screenshot from 2020-03-08 22-35-58](https://user-images.githubusercontent.com/51334444/76167925-666fa880-6190-11ea-8028-f303a7d48a6e.png)

**Comment by thegedge** [comment]
Labeling as a bug, but I think we're still trying to decide on what should be allowed "raw", and what should be quoted.

For now, you should be able to quote these without issue:
```
mkdir "x.0_"
```

**Comment by jonathandturner** [comment]
This should be fixed in master (and be part of the next release)
