### ISSUE TITLE
nu -c emits special characters

### ISSUE THREAD

**Issue by fnuttens** [nushell/nushell#14694]
### Describe the bug

I encountered a weird behavior after updating to version 0.101.0; the command invocation of Nushell emits special characters in the result. I tried disabling ansi coloring, but the issue remains.

For example, a simple `today` command that returns the current date will result in the following string when invoked from `nu --config ~/.config/nushell/config.nu --no-newline -c today | debug --raw`:
```
    \u{1b}]10;#cad3f5\u{7}    \u{1b}]11;#24273a\u{7}    \u{1b}]12;#8aadf4\u{7}    \r2024-12-29
```

### How to reproduce

1. execute a command that returns a simple string using `nu -c`
2. observe that the result is prefixed by special characters

### Expected behavior

I expect `nu -c --no-newline` to return only the string from my custom command (e.g. `2024-12-29`).

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.101.0                                     |
| major              | 0                                           |
| minor              | 101                                         |
| patch              | 0                                           |
| branch             |                                             |
| commit_hash        | fb2610904997f54f50ad52095948bede81695f31    |
| build_os           | linux-x86_64                                |
| build_target       | x86_64-unknown-linux-gnu                    |
| rust_version       | rustc 1.81.0 (eeb90cda1 2024-09-04)         |
| rust_channel       | 1.81.0-x86_64-unknown-linux-gnu             |
| cargo_version      | cargo 1.81.0 (2dbb1af80 2024-08-20)         |
| build_time         | 2024-12-22 15:47:14 +00:00                  |
| build_rust_channel | release                                     |
| allocator          | mimalloc                                    |
| features           | default, sqlite, static-link-openssl, trash |
| installed_plugins  | hmac 0.13.0                                 |

**Comment by fdncred** [comment]
Nushell isn't doing that. Here's what those characters mean.
* `\u{1b}` - This is the ESC character
* `]` - Means the next text is an ansi OSC command
* `10;#cad3f5` - 10 means set the foreground color to that hex color
* `\u{7}` - This is the ansi BEL character which signals the end of a sequence
* `11;#24273a` - 11 means set the background color to that hex color
* `12;#8aadf4` - 12 means set the cursor color to that hex color
* `\r2024-12-29` - carriage return then print date

I believe these sequences are coming from your today command and not from nushell.

**Comment by fnuttens** [comment]
That’s strange, `today | debug -r` seems to indicate that the command does return a string:

```
~
at 13:31:30 ❯ today | debug -r
String {
    val: "2024-12-29",
    internal_span: Span {
        start: 100435,
        end: 100445,
    },
}
```

Here’s what the command does:

```nu
def today [] {
  date now | format date "%Y-%m-%d"
}
```

I also tried piping the result into `ansi strip` but I still get those characters:

```
~
at 13:31:10 ❯ nu --config ~/.config/nushell/config.nu -c "today | ansi strip" | debug -r
String {
    val: "    \u{1b}]10;#cad3f5\u{7}    \u{1b}]11;#24273a\u{7}    \u{1b}]12;#8aadf4\u{7}    \r2024-12-29",
    internal_span: Span {
        start: 560011,
        end: 560013,
    },
}
```

**Comment by fnuttens** [comment]
Ah, it looks like the culprit might be in my config:

```
~
at 13:40:37 ❯ nu --config ~/.config/nushell/config.nu -c "print foobar" | debug -r
String {
    val: "    \u{1b}]10;#cad3f5\u{7}    \u{1b}]11;#24273a\u{7}    \u{1b}]12;#8aadf4\u{7}    \rfoobar",
    internal_span: Span {
        start: 560613,
        end: 560615,
    },
}

~
at 13:41:57 ❯ nu -c "print foobar" | debug -r
String {
    val: "foobar",
    internal_span: Span {
        start: 560681,
        end: 560683,
    },
}
```

**Comment by fnuttens** [comment]
Yup, I just commented the import of my theme (`source `~/.config/nushell/scripts/catppuccin-macchiato.nu`) and the issue is gone 😅 
I guess I’ll have to make a theme-less configuration for my text editor 🙂 

Thank you for your help and sorry for this non-bug!

**Comment by fdncred** [comment]
That's pretty weird that the theme is causing this issue.

**Comment by weirdan** [comment]
@fdncred it does it to set terminal background: https://github.com/nushell/nu_scripts/blob/e380c8a355b4340c26dc51c6be7bed78f87b0c71/themes/nu-themes/catppuccin-macchiato.nu#L132-L141

**Comment by fdncred** [comment]
ya, i'm familiar with how the themes work. I just wasn't remembering it. I think the problem is doing both those things in the same file.

**Comment by fnuttens** [comment]
@fdncred is this a special file loaded by nu?

**Comment by fdncred** [comment]
no, it's just a file that i put all my custom commands in and source it from config.nu

**Comment by fnuttens** [comment]
That’s exactly what I do as well 🤔 

```nu
# config.nu
use `~/.config/nushell/custom-commands.nu` * # Defines today command
source `~/.config/nushell/scripts/catppuccin-macchiato.nu`
```

**Comment by fdncred** [comment]
does switching them around make any difference? we also have the `$nu.vendor-autoload-dirs` that automatically source any *.nu script in them. You could also try that.

**Comment by fnuttens** [comment]
Changing the line order inside of config.nu has no effect, but sourcing the theme from one of the autoloaded dirs works well, thank you! I ended up adding a `~/.local/share/nushell/vendor/autoload/theme.nu`; that still means creating a second config file but at least I don’t need to change Helix’s configuration 🙂

**Comment by NotTheDr01ds** [comment]
If I'm understanding the thread above, it sounds like the theme load is creating an issue when running `--config -c <commandstring>`?  If so, what about making the theme load dependent on `$nu.is-interactive`?

```nushell
if $nu.is-interactive { source `~/.config/nushell/scripts/catppuccin-macchiato.nu` }
```

**Comment by fnuttens** [comment]
@NotTheDr01ds oh that’s so neat, thank you!
