### ISSUE TITLE
`lines` behavior changed recently

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1470]
**Describe the bug**

foo.json:
```
{
  "first": "first",
  "second": "this\nshould\nbe\nseparate\nlines"
}
```

In master:
```
$ open foo.json | get first second | lines
───┬───────────
 # │ <value>
───┼───────────
 0 │ firstthis
 1 │ should
 2 │ be
 3 │ separate
 4 │ lines
───┴───────────
```

previously, was:
```
───┬──────────
 # │ <value>
───┼──────────
 0 │ first
 1 │ this
 2 │ should
 3 │ be
 4 │ separate
 5 │ lines
───┴──────────
```

**To Reproduce**
1. Use the example above

**Expected behavior**
The `lines` command should work across rows.

Note: this will likely be fixed in an upcoming protocol update. Filing this issue as a reminder to add this test case into the test suite as part of the protocol update.

cc @thegedge

**Comment by smaydew** [comment]
I'm a Rust newbie, but really want to get involved. One of my co-workers is contributing to nushell and I thought this would be a good place to start. If the maintainers would like, I can pick up this issue as a starter.
