### ISSUE TITLE
Text is hidden after leading (.*)

### ISSUE THREAD

**Issue by JesterOrNot** [nushell/nushell#1471]
**Describe the bug**
I used regex in the title basically a ( followed by anything and ending with a ) will hide everything from the open parentheses until the end of the line

**To Reproduce**
1. Type stuff
2. type the (stuff)
3. see the hidden text

**Expected behavior**
Text is rendered correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/50386709/76271255-e3108e80-6245-11ea-8164-25b0aa02cf84.png)

**Configuration (please complete the following information):**
 - OS: Gitpod
 - Version: 1.10.1

Related to #1402

**Comment by thegedge** [comment]
Looks like a raw parenthetical group just makes everything hidden.

**Comment by jonathandturner** [comment]
This should be fixed in master
