### ISSUE TITLE
What does `echo $it` do?

### ISSUE THREAD

**Issue by waldyrious** [nushell/nushell#1478]
I'm not sure I understand the role of the `$it` variable. All the examples I could find involve its usage with `echo` in a pipeline, like `... | echo $it`; but those examples seem to do the same when the `| echo $it` part is omitted... 🤔

As for documentation, I expected to find something in the [book](https://www.nushell.sh/book/en/), perhaps in the [Pipeline](https://www.nushell.sh/book/en/pipeline.html) or the [Metadata](https://www.nushell.sh/book/en/metadata.html) sections, or even [Types of data](https://www.nushell.sh/book/en/types_of_data.html), but found nothing.

There are two terse descriptions in this repo:

https://github.com/nushell/nushell/blob/8ef5c475150c48db988aa75f83dd9c1f04f4d120/README.md#L189

https://github.com/nushell/nushell/blob/2956b0b087555a1703a86b896e7333ef436ccc09/crates/nu-protocol/src/value/evaluate.rs#L9-L11

But they don't clarify this — if anything, they reinforce my perception of it as an apparent no-op. Could it perhaps be only useful when we want to access structured content inside the data passing through the pipeline, as in `$it.foo.bar` (in which case plain `echo $it` is indeed redundant)? Or is there some other nuance I'm missing?

**Comment by thegedge** [comment]
Documentation definitely needs some improvement 👍 

---

If you view a command as a stream of data, `$it` is one piece of that data. You can generally think of this data as tables, where each row is structured (the structure is defined by its column names). Here's some example from `ls`:

```
---+---------------+------+----------+---------+------------+------------
 # | name          | type | readonly | size    | accessed   | modified 
---+---------------+------+----------+---------+------------+------------
 0 | add.rs        | File |          | 2.7 KB  | 2 days ago | 2 days ago 
 1 | sum.rs        | File |          | 3.0 KB  | 2 days ago | 2 days ago 
---+---------------+------+----------+---------+------------+------------
```

So `$it` references a single row in that table. You can also access a specific column in a row. For example, `$it.name`. Take a look at https://www.nushell.sh/book/en/working_with_tables.html to understand tables.

Hope this helps!

**Comment by waldyrious** [comment]
Thanks for the clarification! I think one of the aspects that added to the confusion was the name itself — "it" is very vague and ambiguous. Is renaming the variable a possibility? I can think of several options that could convey its meaning more clearly: `$row`, `$line`, or `$entry`, for instance.

**Comment by thegedge** [comment]
Just for context, "it" is a common short form for "iterator". Not saying that's clear or it's a good name, just wanted to fill you in 🙂

> Is renaming the variable a possibility?

Things are still far from settled in stone, so I think this is always a possibility. I'll discuss with the team if we should go for a rename.

**Comment by waldyrious** [comment]
> Just for context, "it" is a common short form for "iterator". Not saying that's clear or it's a good name, just wanted to fill you in 🙂

Thanks for the extra hint!

>> Is renaming the variable a possibility?

> Things are still far from settled in stone, so I think this is always a possibility. I'll discuss with the team if we should go for a rename.

I don't suppose this has been discussed yet? Any updates would be appreciated.

**Comment by jonathandturner** [comment]
@waldyrious - not yet. If you've got some ideas, we can open an issue to brainstorm (or brainstorm on the discord)

There is a new variable that's the value coming in from the pipeline, so you can do:

```
> 5 + 10 | echo $in
15
```

It's a bit different than how `$it` used to work, as it represents the whole pipeline coming in. Just wanted to mention it here, too, since the design around $it/$in is part of the growing and changing part of the language.

**Comment by waldyrious** [comment]
Thanks for the mention of `$in` — I actually had just read about it from the [1.0 RFC](https://github.com/nushell/rfcs/blob/path_to_1_0/text/0006-path-to-1.0.md), which by the way does state:

> The `$it` variable feels a bit special and also unpredictable. We need a design that makes it easy to predict when it will be available and what it will do.

(That's tangential with my concern here which is mostly about naming, though.)

> If you've got some ideas, we can open an issue to brainstorm (or brainstorm on the discord)

Well, I did put forth a few options in a [comment above](https://github.com/nushell/nushell/issues/1478#issuecomment-597746490) that I'd love to get feedback on:

> I can think of several options that could convey its meaning more clearly: `$row`, `$line`, or `$entry`, for instance.

Just to be clear: I get that using "it" for an iterator is a common pattern in programming, but it's not very accessible. And even among programmers, many will be familiar with other conventions, like `i`.

**Comment by waldyrious** [comment]
Quoting the quote from my previous comment:

> I can think of several options that could convey its meaning more clearly: `$row`, `$line`, or `$entry`, for instance.

I'd love to hear feedback on these suggestions.

**Comment by onthebridgetonowhere** [comment]
I would suggest we close this issue for now. 

@waldyrious - let's open a new issue to suggest improvements for the `$it`, if you'd like to get more feedback on it.

**Comment by fdncred** [comment]
@onthebridgetonowhere @waldyrious - we're up for improvements but it would also be good to have some better documentation on `$it` and `$in` so those contributions would be much appreciated. Maybe an entire chapter on them. We could just start with examples too if that was easier.

**Comment by waldyrious** [comment]
> I would suggest we close this issue for now.

In the sense that the question has been answered? If so, that's fair, although I would rather have this issue repurposed (retitled) to be explicitly about a possible renaming of `$it` (in case that's still a valid option at this point), as I proposed above, since that would greatly alleviate the ambiguity, in a more effective way than documentation IMHO.

Of course, I wouldn't mind if a discussion explicitly about renaming came to a conclusion to keep the current name, but at least the decision would be explicit rather than just historical baggage (as in "it's been called that since the beginning").

**Comment by onthebridgetonowhere** [comment]
We could keep it open if you'd prefer that. I was proposing to start a fresh issue as that would maximize the chances of folks discussing these suggestions, as this issue is really in the back of our issue list so it is less visible. 

@fdncred always a good idea to have clear and well written documentation - examples, both simple and complex are a must in my opinion!

**Comment by fdncred** [comment]
A fresh issue is fine with me.
