### ISSUE TITLE
Portable version of Nushell

### ISSUE THREAD

**Issue by anki-code** [nushell/nushell#1482]
Hello!

I think about adding Nushell to [xxh project](https://github.com/xxh/xxh) which allows you to bring your shell wherever you go through the ssh.

Is there a way to run Nushell in portable mode? (static binary, AppImage)

For example the AppImage works good and could be build:
* [Using AppImage template on Open Build Service](https://build.opensuse.org/package/show/home:rfparedes:branches:OBS:AppImage:Templates:SLE:12-SP4/AppImageTemplate)
* [Using PEP 571 recommended manulinux2010 on Travis CI](https://github.com/niess/linuxdeploy-plugin-python/tree/master/.travis)

Thanks!

**Comment by thegedge** [comment]
Hey, @anki-code 👋 

There's no portable mode right now, as far as I know (well, there's docker, but then you need docker 😬).

We likely won't be able to prioritize that work right now, as we're focused on the things that will get us to 1.0 (see the pinned issues in our repo). If you're interested in setting this up, we're more than happy to support you. It should be as simple as `cargo install --features=stable nu` or downloading the latest `_linux` release on https://github.com/nushell/nushell/releases.

**Comment by Coca162** [comment]
I'd be interested in this getting looked at again since in my efforts to package a nushell script as a appimage I'm currently facing issues with `http get` causing generic `Network Failure`s. If there was a official appimage for this hopefully it wouldn't be a issue.
