### ISSUE TITLE
Way to use first row as headers

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1486]
**Is your feature request related to a problem? Please describe.**
When working with data from data files like xlsx, you sometimes get the headers as the first row of data. It'd be nice if there was a command that could take the first row and make it the headers for the columns.

**Describe the solution you'd like**
Maybe a new command like `headers` or maybe we extend and existing command?

**Describe alternatives you've considered**
You can do `| pivot --ignore-titles | pivot --header-row` but this feels cumbersome and probably inefficient.

**Comment by andrasio** [comment]
I faced this same problem! Agree.

**Comment by thegedge** [comment]
We have a lot of `from-xyz` commands that have things like `--headerless` and what not. One related thing to keep in mind would be whether or not we could expand, for example:

```
from-ssv
```

into

```
from-ssv | headers
```

Basically, making our commands super simple, and only copying the behaviour of something else we provide into ac ommand when it means a significant performance benefit. What do you all think?

**Comment by jonathandturner** [comment]
This is fixed with the `headers` command.

@thegedge - It feels like we should add your suggestion to a checklist of "ways we could streamline Nu" that we go back over as we get closer to 1.0
