### ISSUE TITLE
which command exits with wrong error when user has no permissions to execute a binary

### ISSUE THREAD

**Issue by charleschege** [nushell/nushell#1489]
The `which` command gives the impression that a binary does not exist in the system if the user checking the binary does not have permission to execute it.

For example, with a binary `foo` that only the root user has permission to execute, when checked with `which foo` it emits the error:

```rust
error: Binary not found for argument, and argument is not a built in 
- shell:1:9
1| which wrk
 |       ^^^ not found 
```
This command should list the `foo` binary even if a user does not have permissions to execute it

This issue is similar to https://github.com/nushell/nushell/issues/1488

**Comment by lincis** [comment]
bash in similar situation returns nothing.
Anyway I would like to take care on this one and #1488 .

**Comment by thegedge** [comment]
@lincis have you started? I have all the code ready to go, just need to write some tests.

**Comment by lincis** [comment]
Nope, not yet, just did some exploring. Anything else I could help with?

**Comment by thegedge** [comment]
Nope! Feel free to continue working on https://github.com/nushell/nushell/issues/1488, but I can finish this one off 🙂
