### ISSUE TITLE
rm

### ISSUE THREAD

**Issue by wycats** [nushell/nushell#15]
Basic spec:

```
function rm($file)
OR
function rm($it)
```

`$file` may be an absolute or relative path or a file object. `$it` may only be a file object.

If `$file` is a relative path, it's interpreted relative to the current `cwd`.

If the file to delete is a directory, it behaves like `rm -rf` in Linux or `rm -Recurse -Force` in PowerShell. The user must have permissions to delete the relevant files.

If the file to delete is a file, it behaves like `rm`. The user must have permissions to delete the relevant file.

Open Question: Should `rm` on a directory confirm? If so, how does it relate to #16.

**Comment by jonathandturner** [comment]
rm is now available
