### ISSUE TITLE
Remove multiple files at once 

### ISSUE THREAD

**Issue by charleschege** [nushell/nushell#1512]
`rm` command does not allow removing multiple files using one command like
 `rm foo foo.rs bar.md`

**Comment by Sosthene-Guedon** [comment]
Currently, no command support a variable number of arguments and no plugin can either since `Signature` doesn't support it.
Its something that clearly needs to be added.

**Comment by jonathandturner** [comment]
@Sosthene-Guedon this is possible using the .rest() method in signatures. 

You can see an example in the `get` command: https://github.com/nushell/nushell/blob/master/crates/nu-cli/src/commands/get.rs#L26

**Comment by Sosthene-Guedon** [comment]
@jonathandturner Indeed, my bad
