### ISSUE TITLE
Can't `mv` to compound previous directory

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1523]
**Describe the bug**
We just fixed #1291, though there are a few cases that we might have to tackle still.  One I just noticed is that if you do `mv foo ../..` we still throw an error.

**To Reproduce**
1. `touch foo`
2. `mv foo ../..`
3. 

**Expected behavior**
This should move the file up two directories.

Likely just need to extend the logic in #1519

**Comment by JosephTLyons** [comment]
This seems to be resolved

**Comment by thegedge** [comment]
☝️ yep, verified it works
