### ISSUE TITLE
parsing of names with `.` is a bit off

### ISSUE THREAD

**Issue by steveklabnik** [nushell/nushell#1529]
**Describe the bug**

I have a `src` directory, with a `steveklabnik.com` subdirectory. Sometimes, a trailing `\` is acceptable, but not always. Here's what I mean:

```commandline
❯ cd src\steveklabnik.com
steveklabnik.com is 📦 v0.1.0 via 🦀 v1.42.0
```

This works! Let's try it, with a closing `\`, which is what tab completion gives me:

```
❯ cd ../..
~
❯ cd src\steveklabnik.com\
steveklabnik.com is 📦 v0.1.0 via 🦀 v1.42.0
```

This works! Let's try doing it step by step:

```
❯ cd ../..
~
❯ cd src
~/src
❯ cd steveklabnik.com
steveklabnik.com is 📦 v0.1.0 via 🦀 v1.42.0
```

No problem! But:

```
❯ cd ..
~/src
❯ cd steveklabnik.com\
error: cd unexpected com\
- shell:1:20
1 | cd steveklabnik.com\
  |                 ^^^^ unexpected argument (try cd -h)
```

**Expected behavior**

I would expect that they both would work properly. Alternatively, if tab complete didn't add the `\`, I would rarely see this bug.

**Configuration (please complete the following information):**
 - OS: Windows 10
 - Version 0.11.0
 - Optional features `--features=stable`

**Comment by jonathandturner** [comment]
This should now be fixed in master
