### ISSUE TITLE
open and view can't take $it

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#153]
It would be great if $it (and $it with path) was universal, and we could use it on any commands. Currently, it seems to be a mixed bag whether or not the command supports it.

**Comment by jonathandturner** [comment]
Blocked on #180

**Comment by jonathandturner** [comment]
Eg) `ls | skip 4 | first 1 | get name | open $it`

**Comment by wycats** [comment]
At the moment, it depends on whether the command is WholeStream or PerItem. Does that address this issue @jonathandturner ?

**Comment by jonathandturner** [comment]
This should be closed now as this should work a expected for per-item commands
