### ISSUE TITLE
why the linux tar is so big?

### ISSUE THREAD

**Issue by mobop** [nushell/nushell#1539]

**Comment by thegedge** [comment]
Looks like it's just way more debug information in the executable by default.

We can make it smaller by building with `RUSTFLAGS="-C link-args=-s"`, which will

> Remove all symbol table and relocation information from the executable.

[source](https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html)

**Comment by thegedge** [comment]
We're going to try ☝️ on the next release. If the tar is still large, feel free to reopen 🙂
