### ISSUE TITLE
Handling compressed/disk image files

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#154]
Can we cd into .zip and .dmg files? Or is there a way to enter them and step inside the mount?

**Comment by electroniceel** [comment]
The Midnight Commander (mc) contains a very comprehensive virtual filesystem (vfs). It can not only open .zips, but also .tar, .deb, .rpm, .iso and a lot more. It also can handle network filesystems like smb, sftp and fish.

Something like that would fit really well into nu.

Some vfs components of mc are written in c ([midnight-commander.git] / src / vfs / ), others use the extfs-wrapper, which calls scripts (perl, python,...) to do the actual decompression ([midnight-commander.git] / src / vfs / extfs / helpers / ).

I'm not sure if it is viable to directly incorporate the vfs portion of mc as it is GPL3 and mostly written in C. But I think it could serve as a good example how to implement a powerful vfs system.
