### ISSUE TITLE
autocd doesn't expand tilde

### ISSUE THREAD

**Issue by aeosynth** [nushell/nushell#1544]
**To Reproduce**
1. type ~, hit enter

output:
```
error: Command not found
- shell:1:1
1 | ~
  | ^ command not found
```

**Expected behavior**
I should cd to my home folder

**Configuration (please complete the following information):**
Void Linux
nu 0.12 from `cargo install nu`

**Comment by jonathandturner** [comment]
This should now work in master. As this should be in the next release, I'll go ahead and close
