### ISSUE TITLE
Allow more than two arguments for cp and mv 

### ISSUE THREAD

**Issue by quebin31** [nushell/nushell#1548]
**Is your feature request related to a problem? Please describe.**
Currently, the `cp` and `mv` command signatures only allow two parameters, in most scenarios, this isn't enough and the `cp` command must be repeated multiple times. For example, the following fails

```
~ 
❯ cp a b c Test
error: cp unexpected c
- shell:1:13
1 | cp a b c Test
  |        ^ unexpected argument (try cp -h)
```

Since it's not possible to specify a glob pattern for this operation, one must repeat it for each file (`a`, `b` and `c`), which is not the optimal solution

```
~ 
❯ cp a Test 

~ 
❯ cp b Test 

~ 
❯ cp c Test

```

**Describe the solution you'd like**
The above command should allow multiple params, I think this can be done specifying a single `rest` param in the signature with `Pattern` syntax shape. Drawbacks of this solution are that  `help cp` and `help mv` will be less clear since they heavily depend on the signature, and it's not possible to show the possible combination of params just like GNU `cp` does (see [`man cp`](http://man7.org/linux/man-pages/man1/cp.1.html)). One way to solve this would be to add methods to set custom messages for help description, allowing to change `usage` and `parameters` descriptions.

**Describe alternatives you've considered**
Another solution would be to create a custom crate for glob patterns since the actual `glob` crate doesn't allow this specific behavior, other shells like ZSH allow doing this:

```
cp {a,b,c} Test
```

**Comment by kubouch** [comment]
You can pass a list of files like this: `cp/mv [ a b c ] Test`.
Globs used in that list won't work, though, so `cp/mv [ *.txt a b c ] Test` will copy/move only `a b c`.

**Comment by saffronsnail** [comment]
@kubouch Do you know why it doesn't expand the list elements? It's not obvious to me looking at the source for mv, but I'm pretty new to the codebase so I might be missing something.

**Comment by kubouch** [comment]
@saffronsnail I think when it is passed as a list like that, it considers all its items as strings. The question is whether is should or shouldn't expand in this case -- not sure what is the preferred way, might as well be a bug.

It expands the glob only when it is a direct argument to a command, apparently. For example this works: `echo [ *.txt a b c ] | each { cp $it Test }`.
