### ISSUE TITLE
The 'pick' command is not discoverable, 'select' would be more appropriate

### ISSUE THREAD

**Issue by ryepesg** [nushell/nushell#1549]
**Is your feature request related to a problem? Please describe.**
In terms of querying data, the standard operation for choosing columns is `select` instead of `pick`. Examples where that is the case include PowerShell, LinQ, Clojure and SQL.

**Describe the solution you'd like**
I would like to be able to use the command `select` instead of the command `pick`

**Describe alternatives you've considered**
Explain in the official documentation why `pick` is chosen instead of `select`, maybe in a FAQ section

**Comment by thegedge** [comment]
Sorry for the delayed response! We've actually made the change from `pick` to `select`, which will be available in the release next week.

---

I thought I'd also share some of my thoughts on naming, which we all know is one of the Hard Problems 🙂

I don't do a lot of SQL, but I do a lot of Ruby. In Ruby, something like `pick` would be called either `fetch` or `pluck`. People will be coming from many different backgrounds and it's hard to say which one we should favour, unless there's a name that is almost always used across languages.

I personally think explaining name choices isn't worth the effort. What _is_ worth the effort are two things:

- "cheat sheets" when coming from something else, to ease onboarding. We do have that now https://www.nushell.sh/book/en/nushell_map.html 🙌
- For someone who disagrees with our naming choices, a way to map or alias these to a preferred set of names. We do have aliases now, but there are still some kinks to work out

**Comment by ryepesg** [comment]
Great news @thegedge, thanks for that! I agree, naming is a really hard problem. From my perspective, at least consistency with one or two of the main programming languages is enough. This is why `pick` drew my attention, I have invested considerable time comparing standard libraries in functional and not functional programming languages and this is the first time I saw it.

I love https://www.nushell.sh/book/en/nushell_map.html

I am not sure if you like the idea of multiple cheat sheets, but I will be more than happy to work on these three:

- NuShell from other shells and DSL (the current nushell_map.html)
- NuShell from imperative languages: Python, Kotlin, C++, C#, Rust
- NuShell from functional languages: Clojure, Tablecloth (Ocaml / Elm), Haskell

That work will not just be helpful to people coming from other languages, but also to find out if there are missing functions in NuShell that could potentially be useful.

**Comment by jonathandturner** [comment]
@ryepesg - I think having multiple cheat sheets sounds like a great idea. They definitely sound like they could be helpful for many more types of developers coming to Nu from a variety of backgrounds.

**Comment by ryepesg** [comment]
Thanks @jonathandturner, I will be working on a draft to share in the discord channel.

**Comment by ryepesg** [comment]
I am happy about the first PR being merged and I am working on the second one already. I am really impressed by the names chosen for the Nu commands. The only items that stood out after my analysis where:

- `take` is the classic option instead of `keep`
- `transpose` is what I saw, but never before `pivot`

I tested standard phrases in English to see which expressions are more common and these are the results:

"take elements form" -> 1,190 results
"keep elements form" -> 4 results

"pivot matrix" -> 6,620 results
"transpose matrix" -> 111,000 results 

Another minor aspect is:

- `inc` and `dec` exists in Clojure, but in Nu only `inc`

**Comment by ryepesg** [comment]
@jonathandturner @thegedge I have created another PR: https://github.com/nushell/book/pull/93

In regards to my comment about `pivot`, I found out that SQL in fact uses it. Although I still think `transpose` is a better name, at least I now understand where did it come from. I am still curious about `keep` though.
