### ISSUE TITLE
tab completion eats words if it doesn't know what to do

### ISSUE THREAD

**Issue by Amanita-muscaria** [nushell/nushell#1552]
**Describe the bug**
When I hit tab for a completion and nu doesn't know what to do it deletes everything back to the first letter for the string I was trying to complete
e.g. `git checkout nam<tab>` will change to `git checkout n`

**To Reproduce**
1. see description

**Expected behavior**
Probably nothing should happen. I think the traditional is to make a ding but I always disable that as it drives me nuts

**Screenshots**

**Configuration (please complete the following information):**
 - OS: Arch 5.5.13
 - Version 0.12.0
 - Optional features: stable

**Comment by thegedge** [comment]
@jonathandturner is this an issue in your parser rewrite?

**Comment by jonathandturner** [comment]
@thegedge - I see the same thing, so I'm guessing it's a bug in the autocompletion (not part of parser update)
