### ISSUE TITLE
Unify path expansion

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#1553]
We expand paths in many places, and we have lots of forms that get expands:

- `.` is "current directory"
- `..` is "parent directory"
- `~` is "home directory"
- https://github.com/nushell/nushell/pull/1547 will make `n` dots represent `n - 1` levels upwards.

There's likely more, but the problem is that we have this knowledge scattered about in several places. We should bring it all together into a single place, and test that these all evaluate as we'd expect. Two places where this expansion happens right now would be `FilesystemShell` (for most fs commands) and `Cli` (for autocd).

A related task would be to eliminate any tests that focus on testing the behaviour of expansion in the context of a command, but are redundantly testing a behaviour of another test.

**Comment by quebin31** [comment]
Just when I proposed my custom `canonicalize` method I found out that it should be generic over FilesystemShell, I'm thinking in adding it as an extra utility, since this function may resolve `n` dots, `..`, `.`, `~` and optionally symlinks (configurable). Going this way will allow other commands to use this custom path expansion as well (e.g. `open`)

**Comment by jonathandturner** [comment]
We'll also need to update the filename completer, which currently doesn't support things like `...`.

**Comment by jonathandturner** [comment]
(this doesn't have to be at the same time, but something we should add to a checklist we can work through)

**Comment by quebin31** [comment]
Path expansion should be available to plugin developers?

**Comment by thegedge** [comment]
> Path expansion should be available to plugin developers?

It could perhaps be a small crate inside of nushell for now. When everything is more stabilized, we could publish it and then plugins could depend on it.
