### ISSUE TITLE
CTRL+L Regression

### ISSUE THREAD

**Issue by LiHRaM** [nushell/nushell#1555]
**Regression: <kbd>CTRL</kbd>+<kbd>L</kbd> doesn't clear screen**
Pressing <kbd>CTRL</kbd>+<kbd>L</kbd> doesn't clear the terminal in v0.12.0 on my configuration. Similar to #1104, but not sure if this was a regression or caused by something else altogether.

**To Reproduce**
1. Open terminal
2. Run `nu`
3. Press <kbd>CTRL</kbd>+<kbd>L</kbd>

**Expected behavior**
The terminal screen is cleared.

**Configuration (please complete the following information):**
 - OS: Linux
 - Version: pop-os 5.4.0-7618-generic
 - Nushell: v0.12.0 (prepackaged from Github)
- Desktop Environment: Gnome 3.36.0
- Windowing System: Wayland and Xorg

**Comment by thegedge** [comment]
It's working for me on OSX, so this could be specific to linux.

**Comment by LiHRaM** [comment]
Switched to the Windows partition, can confirm it's Linux only - works fine on Windows.

**Comment by jonathandturner** [comment]
I'm not able to repro on my Pop! OS 19.10 machine. I wonder if it's specific to some set of configurations in Linux.

Are you using a different terminal, by chance? Not sure what might be different

**Comment by LiHRaM** [comment]
I'm running Pop!_OS 20.04, so the latest Gnome and a different kernel. But default terminal. I have the same problem on a different laptop running Arch, but Gnome 3.36 as well.

**Comment by jonathandturner** [comment]
@LiHRaM - I looked for Pop!_OS 20.04, but it looks like it's not released, yet. Do you have a link to the pre-release, by chance? I can give it a try

**Comment by LiHRaM** [comment]
@jonathandturner - Yeah, no problem!
You can upgrade to the latest pre-release using `pop-upgrade release upgrade systemd --force-next`.

I'd be careful though, I had to nuke the Gnome config files in my home folder in order for it to work.

**Comment by jonathandturner** [comment]
@LiHRaM - thanks for the warning. I think I'll wait until the official 20.04 comes out, and then try it then.  Hopefully will get released soon.

**Comment by LiHRaM** [comment]
@jonathandturner: So it turns out this was caused by `edit_mode` being set to `vi`.
Sorry about that, I guess I misunderstood what that setting did.
