### ISSUE TITLE
Build (cross-compiling) error with trash 1.0.0 for armv7-linux-androideabi platform

### ISSUE THREAD

**Issue by star191** [nushell/nushell#1556]
**Describe the bug**
When trying to build (cross-compile) Nushell for armv7-linux-androideabi platform, it gives some errors: `use of undeclared type or module platform`

Full error list:
```Rust
Compiling trash v1.0.0
error[E0433]: failed to resolve: use of undeclared type or module `platform`
  --> D:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\trash-1.0.0\src\lib.rs:49:5
   |
49 |     platform::remove(path)
   |     ^^^^^^^^ use of undeclared type or module `platform`

error[E0433]: failed to resolve: use of undeclared type or module `platform`
  --> D:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\trash-1.0.0\src\lib.rs:71:5
   |
71 |     platform::remove_all(paths)
   |     ^^^^^^^^ use of undeclared type or module `platform`

error[E0433]: failed to resolve: use of undeclared type or module `platform`
  --> D:\rust\cargo\registry\src\github.com-1ecc6299db9ec823\trash-1.0.0\src\lib.rs:76:5
   |
76 |     platform::is_implemented()
   |     ^^^^^^^^ use of undeclared type or module `platform`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `trash`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**To Reproduce**
1. clone the repo
2. add this to `config` file in `.cargo`:
```YAML
[target.armv7-linux-androideabi]
// check your own path to SDK
ar = "D:\\androidSDK\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ar.exe"
linker = "D:\\androidSDK\\ndk-bundle\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\armv7a-linux-androideabi21-clang++.cmd"

[build]
target = "armv7-linux-androideabi"
```
3. `cargo build --release`

**Expected behavior**
Build correctly executable Nushell file for armv7-linux-androideabi platform.

**Configuration (please complete the following information):**
 - Host OS: Windows 10
- Target Platform: armv7-linux-androideabi
 - Version: stable

**Comment by thegedge** [comment]
This is an issue with the `trash` crate. Created https://github.com/ArturKovacs/trash/issues/10. Will keep 👀 on it 🙂

**Comment by star191** [comment]
I was just trying to cross-compiled it for my Android 9. Maybe I did it wrong?
Also, it don't build on target device too.

**Comment by thegedge** [comment]
@star191, I looped you in on the issue on the `trash` repo, because I don't know much about `armv7-linux-androideabi`.

It seems reasonable to make it an optional feature, @jonathandturner 👍

**Comment by Amanita-muscaria** [comment]
Removing the trash dependency would break `rm -t`. As long as you don't use that, I think it should otherwise be fine.

**Comment by thegedge** [comment]
@Amanita-muscaria yep, that's exactly what we're hinting at 🙂

@star191 appears to have a platform that doesn't have trash support, so we should make the dependency optional, or limit it to the supported platforms. That's the action item here.

**Comment by star191** [comment]
> @star191 appears to have a platform that doesn't have trash support, so we should make the dependency optional, or limit it to the supported platforms. That's the action item here.

Hokay! 🍰

**Comment by jonathandturner** [comment]
There seem to be more items that need to get fixed, so we may want to open issues as we find them.  At least on my test setup with termux on android, I see one where the decimal crate doesn't compile because of some type error. They may need some kind of specific support added.
