### ISSUE TITLE
auto-cd doesn't support spaces in directory names

### ISSUE THREAD

**Issue by nclements** [nushell/nushell#1557]
When trying to use auto-cd to change to a directory with a space in the name one of two errors are reported:
- Command not found
- Type Error

**To Reproduce**
1. make a directory with a space in the name ```mkdir "t 2"``` 
2. use auto-cd: ```t 2``` or ```"t 2"``` (the latter makes more sense)

**Expected behavior**
Ideally, success.

**Example**
```
~/tst ➜ ls
───┬──────┬──────┬──────┬────────────
 # │ name │ type │ size │ modified
───┼──────┼──────┼──────┼────────────
 0 │ t 2  │ Dir  │      │ 6 mins ago
 1 │ t1   │ Dir  │      │ 6 mins ago
───┴──────┴──────┴──────┴────────────
~/tst ➜ t1
~/tst/t1 ➜ ..
~/tst ➜ "t 2"
error: Type Error
- shell:1:5
1 | "t 2"
  | ^^^^^ Expected command, found string
~/tst ➜
```

**Configuration (please complete the following information):**
 - OS: MacOS Catalina
 - nu 0.12 from ```cargo install nu --features=stable```

**Comment by jonathandturner** [comment]
Thanks for the report. This should be fixed in master, and with luck will be part of the upcoming release.
