### ISSUE TITLE
Parsing around `~` is tricky

### ISSUE THREAD

**Issue by steveklabnik** [nushell/nushell#1561]
**Describe the bug**

I can `cd` to `~/tmp` but not `~\tmp` on Windows.

**To Reproduce**

    > cd ~\tmp

**Expected behavior**

I would expect to change to the `tmp` subdirectory of my home directory, like this command:

    > cd ~/tmp

**Configuration (please complete the following information):**
 - OS: Windows
 - Version 0.12.0
 - Optional features `stable`.

**Comment by jonathandturner** [comment]
I wonder if more Windows-specific logic needs to get added to `shellexpand`.  I don't see anything here: https://github.com/netvl/shellexpand/blob/master/src/lib.rs, but I need to dig in further

**Comment by nightscape** [comment]
I'm experiencing the same thing. What's interesting is that tab-completion only works with `\`, but `cd`ing only with `/`:
```
❯ cd ~\Worksp <tab>
❯ cd ~\Workspaces
error: Cannot change to directory
- shell:1:15
1 | cd ~\Workspaces
  |    ^^^^^^^^^^^^ directory not found
❯ cd ~/Workspaces
~/Workspaces
❯
```
Looks like two different code paths are taken for the two?

**Comment by steveklabnik** [comment]
This appears to be fixed 
![image](https://user-images.githubusercontent.com/27786/123723003-161dcd80-d84f-11eb-9100-9680a575b80c.png)
