### ISSUE TITLE
Universal date mangling and formatting tool

### ISSUE THREAD

**Issue by devurandom** [nushell/nushell#1565]
**Is your feature request related to a problem? Please describe.**

Working with dates is a common task and could be supported first-class by nushell.

Related to #1564 (human-readable formatting in `autoview`) and #1566 (via the `fmt to-iso8601` tool, since ISO 8601 describes formatting for both dates and durations)

**Describe the solution you'd like**

There could be an easy way to display dates as ISO 8601, e.g. through a tool that turns a date object into a string (here shown as an extension to a fictitious `fmt` tool):
```
> date | fmt to-iso8601
2020-04-10T08:21:51+02:00
```

Also it nice would be, if this there was a tool to parse dates from stdin, potentially building on the `str` tool introduced in nushell v0.15:
```
> echo wednesday | str to-date | fmt to-iso8601
2020-04-08

> echo last year | str to-date | fmt to-iso8601
2019

> echo noon tomorrow | str to-date | fmt to-iso8601
2020-04-11T12:00:00+02:00
```

This tool would assume the input is in local time, unless it comes with explicit timezone information:
```
> echo 12:00 | str to-date | fmt to-iso8601
2020-04-08T12:00:00+02:00

> echo 12:00 +10:00 | str to-date | fmt to-iso8601
2020-04-08T12:00:00+10:00
```

Thus a tool to change the timezone would be handy, too:
```
> echo 12:00 | str to-date | timezone utc | fmt to-iso8601
2020-04-10T10:00:00Z
```

The same `str to-date` tool could of course also made to turn text that (implicitly) contains timezone information into date objects (that can then be manipulated or formatted by other nushell commands, like the proposed `fmt to-iso8601`):
```
> echo @1590602056 | str to-date | fmt to-iso8601
2020-05-27T17:54:16Z

> echo 2020-05-27T17:54:16Z | str to-date | fmt to-iso8601
2020-05-27T17:54:16Z
```

P.S. In these examples I always pipe the results through `fmt to-iso8601` to show a compact and universal output, instead of a table that involves more typing and distracts from the important parts I wanted to show.

**Describe alternatives you've considered**

I do not see good alternatives apart from writing these tools myself.

**Comment by Delapouite** [comment]
In the past, I've used `chronic` which is a similar tool in this category: https://github.com/alexherbo2/chronic

**Comment by jonathandturner** [comment]
I'm not super familiar with iso8601 output, but looking at your example, I tried using the `format` command to get close:

```
date | format "{year}-{month}-{day}T{hour}:{minute}:{second}{timezone}"
2020-4-11T19:49:55+12:00
```

Your examples are good, we could make something that was much more composible, and more compact, than what I wrote

**Comment by devurandom** [comment]
> I'm not super familiar with iso8601 output, but looking at your example, I tried using the `format` command to get close:
> 
> ```
> date | format "{year}-{month}-{day}T{hour}:{minute}:{second}{timezone}"
> 2020-4-11T19:49:55+12:00
> ```
> 
> Your examples are good, we could make something that was much more composible, and more compact, than what I wrote

Thanks!

Note, though, that `to-iso8601` was only part of my suggestion. I was thinking that a suite of commands to work on dates as a first class object would be really nice. Things like:
* Parsing dates from other formats, including "human" formats that depend more on the context (-> `from-date`)
  - Having worked with Time Warrior and Task Warrior (e.g. `timew summary :lastweek` or `task add due:sunday ...`) inspired this partially.
* Time / date conversion as a first class operation (-> `timezone utc`)
  - Really awesome would be stuff like `date | to-calendar hijri` (Islamic) or `date | to-calendar solarhijri` (modern Iranian).
  - Or `echo 23 Farvardin 1399 | from-calendar solarhijri | to-iso8601`
* Calculations involving dates (see #1566)

**Comment by elichai** [comment]
Another related feature request is passing a UNIX timestamp as an input to `date` so it will print it in human readable time

**Comment by devurandom** [comment]
> Another related feature request is passing a UNIX timestamp as an input to `date` so it will print it in human readable time

Thanks for that suggestion. I extended my proposal with an example of how this could look like.
