### ISSUE TITLE
Universal duration mangling and formatting tool

### ISSUE THREAD

**Issue by devurandom** [nushell/nushell#1566]
**Is your feature request related to a problem? Please describe.**

Working with durations is a common task and could be supported first-class by nushell.

Related to #1564 (human-readable formatting in `autoview`) and #1565 (via the `fmt to-iso8601` tool, since ISO 8601 describes formatting for both dates and durations)

**Describe the solution you'd like**

There could be an easy way to display durations as ISO 8601, e.g. through a tool that turns a duration object into a string (here shown as an extension to a fictitious `fmt` tool):
```
> sys | get host.uptime | fmt to-iso8601
P1DT23H34M32S
```

Also it nice would be, if this there was a tool to parse durations from stdin, potentially building on the `str` tool introduced in nushell v0.15:
```
> echo 1 year | str to-duration | fmt to-iso8601
P1Y
```

The same tool could also do calculations:
```
> echo P1D + 2 hours | str to-duration | fmt to-iso8601
P1DT2H

> echo 10:00 + 12:00 | str to-duration | fmt to-iso8601
PT22H
```

An alternative way to do calculations could be through a separate tool that works on a table and sums up all rows, but I am not well-versed with nushell yet to express that properly. Some half-baked attempt:
```
> sys | get host.uptime | append (echo 2 hours | str to-duration) | sum | fmt to-iso8601
P2DT1H34M32S
```

The built-in `sum` would have to be extended to support duration objects.

Combining this with #1565, we could also do calculations with dates and durations, the result being a date:
```
> date | append (echo 2 hours | str to-duration) | sum | fmt to-iso8601
2020-04-10T10:21:51+02:00
```

Since dates and durations have different structure / different table, the table fed into `sum` would have to look like:

| year | month | day | hour | minute | second | timezone | hours
| --- | --- | --- | --- | --- | --- | --- | --- |
| 2020 | 4 | 10 | 8 | 21 | 51 | +02:00 | |
| | | | | | | | 2 |

P.S. In these examples I always pipe the results through `fmt to-iso8601` to show a compact and universal output, instead of a table that involves more typing and distracts from the important parts I wanted to show.

**Describe alternatives you've considered**

I do not see good alternatives apart from writing these tools myself.

**Comment by jonathandturner** [comment]
I was looking at uptime, and I think it predates us adding a duration type.  You can do this today using shorthands like `1d` for 1 day.

This doesn't give you the iso date format, yet, but I can at least change uptime to use the duration value, which is a u64 time in seconds, that we can then work with through a converter, like the `to-iso8601` you suggest.

**Comment by devurandom** [comment]
> I was looking at uptime, and I think it predates us adding a duration type. You can do this today using shorthands like `1d` for 1 day.
> 
> This doesn't give you the iso date format, yet, but I can at least change uptime to use the duration value, which is a u64 time in seconds,

Thanks!

> that we can then work with through a converter, like the `to-iso8601` you suggest.

The `to-iso8601` is just one part of my suggestion. Others are:
* Support for durations (and dates) in `sum`
 - I think durations cannot just be added to dates after conversion to seconds, because of leap seconds and such things, that depend on the date they get added to.
* Ingress of durations from non-nushell contexts, that involves parsing dates from a string
* Possibly also ways to make `... | append (echo 2 hours | from-duration) | ...` work, without involving nasty things like word splitting. As I see it, it would involve a way to hand over the output of `from-duration` as an argument (or 2nd input stream) to `append` and a way to append a row with multiple columns to the input stream / table.
