### ISSUE TITLE
Unable to execute command containing dots

### ISSUE THREAD

**Issue by devurandom** [nushell/nushell#1568]
**Describe the bug**

Commands containing dots in their name cannot be executed.

**To Reproduce**

```
❯ echo $nu.path | to-json | jq | rg /var/lib/flatpak
  "/var/lib/flatpak/exports/bin",

❯ ls /var/lib/flatpak/exports/bin/org.signal.Signal
──────────┬────────────────────────────────────────────────
 name     │ /var/lib/flatpak/exports/bin/org.signal.Signal
 type     │ Symlink
 size     │
 modified │ 6 days ago
──────────┴────────────────────────────────────────────────

❯ org.signal.Signal
error: Command not found
- shell:1:17
1 | org.signal.Signal
  | ^^^ command not found
```

**Expected behavior**

The program `org.signal.Signal` should be started.

**Configuration (please complete the following information):**
 - OS: Linux 5.5
 - Version: 0.12.0
 - Optional features: --features=stable

**Comment by jonathandturner** [comment]
This should be fixed in master. If it's not, please reopen so we can fix it.
