### ISSUE TITLE
Incorrect source file header

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#1577]
[#1571](https://github.com/nushell/nushell/pull/1571/files#diff-5ec38171b96601edd1f52fc112b31bf3R1-R16) included a per-file license header that mentions nushell being distributed under the GPL. This actually isn't the case, as the [LICENSE](https://github.com/nushell/nushell/blob/master/LICENSE) file states we are distributed under the GPL.

We should figure out if the original author intended for GPL, or if was unintentional. If GPL, we may not actually want to receive this contribution, since it is far less permissive.

(For your attention, @quebin31)

**Comment by thegedge** [comment]
I just missed it, but looks like https://github.com/nushell/nushell/pull/1575 will close this one 🙂

**Comment by quebin31** [comment]
@quebin31 It was an error with VS Code, that adds license header automatically and I didn't notice it until the last moment just after I pushed the changes. #1575 will fix it, but you can delete it now, I didn't mean to use the GPL license.

**Comment by thegedge** [comment]
Just wanted to be 100% sure. We can wait until #1575 gets in and then close out this issue 🙂

Thanks, @quebin31!
