### ISSUE TITLE
Escaping appears broken for [ character

### ISSUE THREAD

**Issue by mcbeth** [nushell/nushell#1585]
**Describe the bug**
There doesn't appear to be a way to escape [] in filenames, and tab completion doesn't provide working solutions, I've not explored other traditionally shell-escaped characters

**To Reproduce**
1. touch "[Hello World].txt"
2. ls
3. ls "[Hello World].txt"

I see:
```
> ls
──────────┬───────────────────
 name     │ [Hello World].txt
 type     │ File
 size     │ 0 B
 modified │ 6 mins ago
──────────┴───────────────────

> ls "[Hello World].txt"
error: Invalid File or Pattern
- shell:1:22
1 | ls "[Hello World].txt"
  |    ^^^^^^^^^^^^^^^^^^^ invalid file or pattern
```
**Expected behavior**
I would expect similar outputs between lines 2 and 3

**Configuration (please complete the following information):**
 - OS: Linux williwaw 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Version:  e3da037b801cbc85383dc119fdf79899c8ed62cd

**Comment by thegedge** [comment]
We probably need to be escaping before we glob, because `[...]` is a character matching glob.

**Comment by fpatwa** [comment]
I would like to work on this issue - could you please assign it to me? Thanks!

**Comment by jonathandturner** [comment]
@fpatwa - sure thing, it's yours

**Comment by thegedge** [comment]
@fpatwa Still working on this? Need any help, or should we unassign?

**Comment by fpatwa** [comment]
> @fpatwa Still working on this? Need any help, or should we unassign?

Sorry got delayed on this but would still like to keep working on it if its okay! Thanks.

**Comment by diohabara** [comment]
@thegedge
If @fpatwa is not working anymore, I'd like to work on this!

**Comment by fpatwa** [comment]
> @thegedge
> If @fpatwa is not working anymore, I'd like to work on this!

@diohabara Please go ahead!
@thegedge Unfortunately I did not get a chance to work on this.

**Comment by Sean1708** [comment]
Is there any workaround for this? Other than just escaping to the system `ls`?

**Comment by onthebridgetonowhere** [comment]
I was working on the parser the other day so I am taking a look at this now. Hope to have a fix soon.

**Comment by Sean1708** [comment]
This is still a problem on 0.32.0, but I don't know whether it's been fixed on master. Don't know if it should still be marked stale if it's unsolved.

**Comment by Sean1708** [comment]
Still an issue on `0.36.0`.

**Comment by dantinkakkar** [comment]
Can I pick this up?

**Comment by fdncred** [comment]
this should be fixed for a while now. escaping brackets is done with `char left_bracket` and `char right_bracket`. check out `char --list` for a complete list.

**Comment by Sean1708** [comment]
Hi @fdncred there are still two outstanding issues for me (refer to the code snippet below):

1. After creating the file the first thing I did (in the snippet below) was type `ls ` and hit the Tab key to trigger autocomplete, upon doing so it completed the _unescaped_ file name `"[Hello World].txt"`. This is a major usability issue IMO, but might be considered out of the scope of this issue.
2. Escaping brackets doesn't seem to work with `ls`, although it works fine with `echo`. This might be _me_ doing something wrong, but if it is then I can't for the life of me figure out what...

```
Welcome to Nushell 0.44.0 (type 'help' for more info)

~ 
❯ mktemp -d
/tmp/tmp.OeTN0PTXLm

~ 
❯ cd /tmp/tmp.OeTN0PTXLm/

/tmp/tmp.OeTN0PTXLm 
❯ touch "[Hello World].txt"

/tmp/tmp.OeTN0PTXLm 
❯ ls "./[Hello World].txt"
error: No matches found
  ┌─ shell:4:4
  │
4 │ ls "./[Hello World].txt"
  │    ^^^^^^^^^^^^^^^^^^^^^ no matches found


/tmp/tmp.OeTN0PTXLm 
❯ ls
───┬───────────────────┬──────┬──────┬────────────────
 # │       name        │ type │ size │    modified    
───┼───────────────────┼──────┼──────┼────────────────
 0 │ [Hello World].txt │ File │  0 B │ 14 seconds ago 
───┴───────────────────┴──────┴──────┴────────────────


/tmp/tmp.OeTN0PTXLm 
❯ ls "[Hello World].txt"
error: No matches found
  ┌─ shell:6:4
  │
6 │ ls "[Hello World].txt"
  │    ^^^^^^^^^^^^^^^^^^^ no matches found


/tmp/tmp.OeTN0PTXLm 
❯ ls $"(char left_bracket)Hello World(char right_bracket).txt"
error: No matches found
  ┌─ shell:7:4
  │
7 │ ls $"(char left_bracket)Hello World(char right_bracket).txt"
  │    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no matches found


/tmp/tmp.OeTN0PTXLm 
❯ ls $"./(char left_bracket)Hello World(char right_bracket).txt"
error: No matches found
  ┌─ shell:8:4
  │
8 │ ls $"./(char left_bracket)Hello World(char right_bracket).txt"
  │    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no matches found


/tmp/tmp.OeTN0PTXLm 
❯ echo $"(char left_bracket)Hello World(char right_bracket).txt"
[Hello World].txt

/tmp/tmp.OeTN0PTXLm 
❯ ls
───┬───────────────────┬──────┬──────┬───────────────
 # │       name        │ type │ size │   modified    
───┼───────────────────┼──────┼──────┼───────────────
 0 │ [Hello World].txt │ File │  0 B │ 2 minutes ago 
───┴───────────────────┴──────┴──────┴───────────────
```

**Comment by jntrnr** [comment]
I have a hunch this might be happening because `[` is being seen as part of the glob pattern.

The glob crate lists `[` as part of a pattern: https://docs.rs/glob/latest/glob/struct.Pattern.html

**Comment by jntrnr** [comment]
I wonder if we want to support these kinds of patterns or just the `?` and `*` ones

**Comment by fdncred** [comment]
I personally love the full-on-globbing for things like how this works in powershell `ls [a..f]*`. I wonder how we can the best of both worlds. I mean, it sounds like we're trying to use double quotes as the escape here `touch "[Hello world].txt"` but I'm not sure we really want to introduce escapes. It's kind of a tough problem.
