### ISSUE TITLE
Support Boolean conditions in where clauses

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#1586]
**Is your feature request related to a problem? Please describe.**
The documentation seems to indicate that one can filter by a boolean in a where clause but I can't figure out how.

**Describe the solution you'd like**
I'd like to be able to do `open msft.json | pick urls required | where required == true` or `open msft.json | pick urls required | where required` as the documentation seems to indicate.

**Describe alternatives you've considered**
I've tried:
`open msft.json | pick urls required | where required == true`
`open msft.json | pick urls required | where required == 1`
`open msft.json | pick urls required | where required == True`
`open msft.json | pick urls required | where required == Yes`
`open msft.json | pick urls required | where required`

**Additional context**
I stumbled upon this when trying to get this command working:
`open msft.json | pick urls | str urls --find-replace [".+\.(.+)\.(com|net|ms|ly|org)" "*.$1.$2"] | sort-by urls | uniq` but i really only needed the ones where required = true.

Attached is the msft.json zipped for testing.
[msft.zip](https://github.com/nushell/nushell/files/4477190/msft.zip)

**Comment by thegedge** [comment]
You'll be happy to know that a lot of the work @jonathandturner has been doing lately will likely take care of this 🙂

**Comment by jonathandturner** [comment]
This should be fixed now in master (and should be part of next week's release).  You can use `| where required`
