### ISSUE TITLE
'update' command

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#159]
The update command would take a file to update and a block. It would magic open the file, run the block on the contents, and then take the result and magic save to the same filename.

For example:

```
> update Cargo.toml { inc package.version }
```

(This example assumes #158)

**Comment by jonathandturner** [comment]
Blocked on #180

**Comment by andrasio** [comment]
#900

**Comment by andrasio** [comment]
Well, who would've had thought this could be done as an alias ;). Closing.
