### ISSUE TITLE
Add 'startup' loading to scripts and -c

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1590]
**Is your feature request related to a problem? Please describe.**
Currently, 'startup' is only run for CLI. We should extend it to script running and -c

**Comment by thegedge** [comment]
To add to this one: other shells have different kinds of startup scripts based on the mode (login, interactive, etc). I think we should have different kinds of startup scripts, but I would want the sequence to be a little simpler than other shells. Maybe

1. interactive,
2. non-interactive, and
3. all?
