### ISSUE TITLE
can't pass argument to external command in alias

### ISSUE THREAD

**Issue by aeosynth** [nushell/nushell#1592]
**To Reproduce**
```
> alias g [x] { git $x }
g log
# git help shows here
```
**Expected behavior**
the command receives the argument

**Configuration (please complete the following information):**
void linux
nu bd5836e25d767d534a2b04b90da9e22707a69122

**Comment by thegedge** [comment]
Definitely specific to externals:

```
nushell on 📙 HEAD (bd5836e) is 📦 v0.12.1 via 🦀 v1.42.0
❯ alias log [x] { echo $x }
nushell on 📙 HEAD (bd5836e) is 📦 v0.12.1 via 🦀 v1.42.0
❯ log test
test
```
```
nushell on 📙 HEAD (bd5836e) is 📦 v0.12.1 via 🦀 v1.42.0
❯ alias log [x] { ^echo $x }
nushell on 📙 HEAD (bd5836e) is 📦 v0.12.1 via 🦀 v1.42.0
❯ log test

```
```
nushell on 📙 HEAD (bd5836e) is 📦 v0.12.1 via 🦀 v1.42.0
❯ alias log [x] { ^echo test $x }
nushell on 📙 HEAD (bd5836e) is 📦 v0.12.1 via 🦀 v1.42.0
❯ log test
test
```
```
nushell on 📙 HEAD (bd5836e) is 📦 v0.12.1 via 🦀 v1.42.0
❯ alias log [x] { ^echo "test -->" $x "<--" }
nushell on 📙 HEAD (bd5836e) is 📦 v0.12.1 via 🦀 v1.42.0
❯ log test
test --> <--
```

**Comment by thegedge** [comment]
Right, we don't evaluate args in externals right now.

I'm going to hack up a fix for the way things work currently, but I think we've been wanting to move externals more towards internals. Two benefits to this off the top of my head:

1. How arguments are evaluated into something that the commands can consume is consolidated, and
2. makes it easier to introduce things like autocomplete and syntax highlighting for externals.

**Comment by thegedge** [comment]
@jonathandturner fixed this one. Verified these all work on master 🙂
