### ISSUE TITLE
Need a better json parser?

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1595]
**Describe the bug**
If you try to open this:

```
{
  value: 'secret-value',
  name: 'secret-name'
}
```
Note: this comes from the output of node, so it seems like a json-like format we should treat as json

**To Reproduce**
1. Save the above example as 'example.json'
2. `open "example.json"`
3. Notice the values don't look correct

**Expected behavior**
This should parse as expected

**Comment by thegedge** [comment]
Hmm, technically that would be invalid JSON.

```json
{
  value: 'secret-value',
  name: 'secret-name'
}
```

☝️ just to emphasize. Two problems:

1. the keys must always be quoted, and
2. doubles quotes must always be used.

Looks like node is emitting something intended to be `eval`-uated by Javascript. I would say this is a bug with node, if it's supposed to be emitting JSON.

**Comment by Peter42** [comment]
`mv "example.json"  "example.yaml"` :smile:

**Comment by jonathandturner** [comment]
Haha, okay fair enough. I'll close since it's not actually json being output
