### ISSUE TITLE
Fail to spawn process when given full path

### ISSUE THREAD

**Issue by mgattozzi** [nushell/nushell#1596]
**Describe the bug**

Fail to spawn process despite giving an explicit path to an executable.

**To Reproduce**
1. This was a brand new shell, fresh install from source with `cargo install --path . --features=stable` with no env vars set, including PATH
2. Type in "/path/to/executable args"
3. Get an error saying unable to spawn process.

However, I found once I set the PATH it worked, and when I removed PATH from the config it worked. Even with a new spawned process or deleted config. I have no clue as to why this might be the case. I tried to reproduce it after the fact, but it seems like a one off thing.

**Expected behavior**

I was expecting it to run an explicitly named executable by it's full path like I can with other shells.

**Screenshots**

**Configuration (please complete the following information):**
 - OS: OSX
 - Version Catalina
 - Optional features (if any) `--features=stable`

**Comment by jonathandturner** [comment]
Currently not able to reproduce this, but we should keep an eye on it. It may be related to how paths are set on startup, we might be doing something that's breaking the binary detection logic later on.

**Comment by thegedge** [comment]
@mgattozzi did you happen to see this again? If we're not able to reproduce, I'll close the issue and we can reopen once we see it again.

**Comment by mgattozzi** [comment]
I haven't been able to get it to happen again 🤷‍♂️ I'll close to issue for now 😁
