### ISSUE TITLE
It's not possible to execute $it

### ISSUE THREAD

**Issue by kvrhdn** [nushell/nushell#1598]
**Describe the bug**
In a pipeline, when you end up with a `$it` that contains a command, you can't execute it without wrapping it in `nu -c $it`.

**To Reproduce**

You need some pipeline which filters out a command, in my case I had a README with some commands I execute often:

```
❯ bat README.md | lines | skip 19 | first 4
───┬──────────────────────────────────────────────────────────────────────────────────────────────
 # │ <value> 
───┼──────────────────────────────────────────────────────────────────────────────────────────────
 0 │ ./gradlew :coach-service:coach-service-adapter-sql:cleanTenantIndependent 
 1 │ ./gradlew :coach-service:coach-service-adapter-sql:migrateTenantIndependent -PLOAD_TEST_DATA 
 2 │ ./gradlew :coach-service:coach-service-adapter-sql:cleanTenantDependent 
 3 │ ./gradlew :coach-service:coach-service-adapter-sql:migrateTenantDependent -PLOAD_TEST_DATA 
───┴──────────────────────────────────────────────────────────────────────────────────────────────
```
When you try to execute `$it` this fails with "Expected command, found variable":
```
❯ bat README.md | lines | skip 19 | first 4 | $it
error: Type Error
- shell:1:47
1 | bat README.md | lines | skip 19 | first 4 | $it
  |                                             ^^^ Expected command, found variable

```

I have had similar situations with `package.json` files:
```
❯ open package.json | get scripts.start | $it
error: Type Error
- shell:1:43
1 | open package.json | get scripts.start | $it
  |                                         ^^^ Expected command, found variable
```

Workaround, wrap it with `nu -c`:

```
❯ open package.json | get scripts.start | nu -c $it
```

**Expected behavior**
I would expect `$it` to execute the command it contains.

**Screenshots**

**Configuration (please complete the following information):**
 - macOS 10.15.4
- nushell 0.12.0
- installed with brew

**Comment by aaronsb** [comment]
In powershell, you can't do that either. You invoke the expression instead (Invoke-Expression) which evaluates the result of the expression as a command.

![image](https://user-images.githubusercontent.com/2738471/81452979-42ebbe80-913d-11ea-979f-667af2f661ad.png)
