### ISSUE TITLE
Error highlighting visual artifacting on windows

### ISSUE THREAD

**Issue by ryanisaacg** [nushell/nushell#1599]
**Describe the bug**
After a screen clear, the error highlighting remains visible on the given cells.

**To Reproduce**
1. Insert some random alphanumeric text like 'abc123'
2. Insert a semicolon
3. Run the broken command
4. Clear the screen with Ctrl-L

**Expected behavior**
The error highlighting on the cells should be cleared during screen clear.

**Screenshots**
A clean nu session
![image](https://user-images.githubusercontent.com/7978904/79496123-ad548780-7ff3-11ea-9feb-1c85a4491e9f.png)
Introduce some error highlighting
![image](https://user-images.githubusercontent.com/7978904/79496155-b8a7b300-7ff3-11ea-8c20-96578cd76579.png)
Get an error
![image](https://user-images.githubusercontent.com/7978904/79496180-bfcec100-7ff3-11ea-937a-52b1359575dd.png)
Clear the screen, error cells still visible
![image](https://user-images.githubusercontent.com/7978904/79496202-c8bf9280-7ff3-11ea-9e5c-6432181b15da.png)

**Configuration:**
 - OS: Windows 10
 - Version: 0.12.0
 - Optional features: I'm unsure, I got it via `cargo install nu` so whatever that would default to?

Problem occurs in both the standard cmd terminal host and the new Windows Terminal.

**Comment by jonathandturner** [comment]
This should be fixed now. If you still see it happening in the latest master, please feel free to re-open this issue
