### ISSUE TITLE
Confirmation infrastructure

### ISSUE THREAD

**Issue by wycats** [nushell/nushell#16]
Like `-WhatIf` and `-Force` in PowerShell.

We should do better than PS at getting arbitrary commands to support confirmation.

Idea from @jonathandturner: what if dangerous behavior like removing files could only be accomplished by returning actions from commands, which would then be handled by the host?

@wycats likes it.

**Comment by jonathandturner** [comment]
We may revisit, but this feels different than the direction we ended up going (using flags to confirm important steps)
