### ISSUE TITLE
Panic in `sum` of example data

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1603]
**Describe the bug**
The `sum` command will panic if you try to sum things that aren't numbers.

```
tests/fixtures/formats on 📙 master 
❯ open sample.db | nth 1 | get table_values | sum
thread 'main' panicked at 'not implemented: Internal error: can't add non-primitives.', crates/nu-protocol/src/value.rs:431:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
1. cd tests/fixtures/formats
2. open sample.db | nth 1 | get table_values | sum
3. 

**Expected behavior**
Give a helpful error message

**Comment by jonathandturner** [comment]
Looks like the issue here comes from there being std::ops implemented on Primitive and Value that will panic if they get something they don't expect. Unfortunately, this will definitely happen in practice, as the bug shows.

What we probably want to do is to not use std::ops, since our operations can fail.  Instead, we could use the new math operations, and merge them with some of the logic from the std::ops to get something that's as good as both, but also returns a Result so we can see the possible error.

From there, point the data processing and `sum` work at the new non-std::ops functions.

**Comment by jonathandturner** [comment]
What we'd need to replace:
* https://github.com/nushell/nushell/blob/master/crates/nu-protocol/src/value.rs#L400-L434
* https://github.com/nushell/nushell/blob/master/crates/nu-protocol/src/value/primitive.rs#L105-L163

We could merge the best parts of the above into:
* https://github.com/nushell/nushell/blob/master/crates/nu-cli/src/data/value.rs#L25-L106

We may even want the code to live in nu-protocol like the original code.

**Comment by andrasio** [comment]
I feel more comfortable this way. fwiw, it panics because opening `sample.db | nth 1 | get table_values` gives back an empty string in the result set (denoting a missing value instead of Nothing)
