### ISSUE TITLE
History (ctrl + r) with fzf

### ISSUE THREAD

**Issue by casidiablo** [nushell/nushell#1616]
The current history search (triggered with Ctrl + R) works similar to that of a barebones bash installation. Is there a way to configure it to delegate to `fzf` so we can have code completion using a fuzzy search?

For reference, this is how fzf configures this feature in each major shell out there: https://github.com/junegunn/fzf/tree/master/shell

**Comment by thegedge** [comment]
Currently there's no easy way to do this. We're using rustyline, which does have a fuzzy completion type (https://docs.rs/rustyline/6.1.1/rustyline/config/enum.CompletionType.html), but it's not fzf.

More generally, as far as I can tell, we can't hook into the key bindings and execute something custom.

**Comment by pka** [comment]
We had fuzzy search with Ctrl-R in #672, but it got reverted in #980. It did work around the missing configuration option of rustyline with an additional loop around `process_line`, which is not nice. My preferred solution would be a configuration option in rustyline for a custom reverse-search or an optional fuzzy history search built into rustyline. Fuzzy search in Ctrl-R should be an independent configuration from fuzzy search in command completion (see also https://github.com/pka/nushell/commit/da55ffa).

**Comment by jonathandturner** [comment]
Rustyline uses `skim`, which has fzf-like features.  The issue we had at one point trying to use it was that `skim` doesn't work in Windows, yet. There is some work going on there, and we'd love to explore adding it once Windows support is added.

**Comment by zacps** [comment]
Bump.

**Comment by torarvid** [comment]
Does anyone know if there's a workaround for this? (I believe this is gonna be a deal-breaker for me at least 😬)

**Comment by danjenson** [comment]
same^

**Comment by fellnerse** [comment]
I also would like to use fzf

**Comment by rosshadden** [comment]
Hopefully whichever solution is arrived at or recommended, we will have a way to use `fzf` itself (or any arbitrary command) rather than the solution being "something with fzf-ish features".

My ideal solution would be letting users specify their own scripts/commands for certain features, like tab-completion (my zsh currently uses fzf for completion for example), history completion (my zsh currently uses fzf for this as well), and more.
Letting things like this be configurable (and making sure some common configurations work) seems like a much better idea than coupling the shell with any particular software. Surely anyone in here asking for that sort of coupling really just wants the ability to use it, not for the shell to come with it out of the box.

**Comment by rosshadden** [comment]
> with a custom keybinding to trigger a custom nushell-script, to feed history to fzf
@mborejdo Can you give any more details? I also use wezterm and that sounds like it might work for me too for now.

**Comment by mborejdo** [comment]
@rosshadden sure. I have something like this in my wezterm keybindings:
```
...
{key = "r", mods = "LEADER", action = wezterm.action {SendString = "historyfzf\x0D "}},
...
```

Then I have this nushell helper function

```
def historyfzf [] {
	history | reverse | each { echo [$it (char nl)] } | str collect | fzf --header '[HISTORY]' | cbs
	_pasteAtCursor
}
```

**Comment by rosshadden** [comment]
Thanks, I was overthinking it. I was trying to spawn child processes in the opened window haha.

**Comment by fellnerse** [comment]
@mborejdo what is `cbs` and `_pasteAtCursor`? I would like to do a similar thing in iTerm..

**Comment by mborejdo** [comment]
@fellnerse I am on windows and need some trickery to achieve what I want: `cbs` is a windows-clipboard helper which I use to copy the fzf output to my clipboard. Then I have another helper, which misuses `espanso` (https://github.com/federico-terzi/espanso) and inserts the current clipboard at the current cursor-position, so I dont have to type it

**Comment by fellnerse** [comment]
@mborejdo cool thank you for the explanation with this I got it to work on macos natively without dependencies:

```
def historyfzf [] {
	let x = (history | reverse | each { echo [$it (char nl)] } | str collect | fzf --header '[HISTORY]')
	let y = $'tell application "System Events" to keystroke "($x)"'
	osascript -e $y
}
```
it's probably possible to make it look nicer but I'm not sure how

In iTerm you have to go to keybindings and record `ctrl + r` and set it to `Send: 'historyfzf \n'`

**Comment by rosshadden** [comment]
Thanks. This is my adaptation for linux:

```lua
# fzf through shell history, typing result
# requires `xdotool`
def fzf-history [] {
	let cmd = (history | reverse | reduce { $acc + (char nl) + $it } | fzf --prompt "HISTORY>")
	xdotool type $cmd
}
```

I'm trying to make it pre-populate the prompt with whatever was already typed before hitting the mapping. Will update if I figure out a way to do that.

**Comment by fellnerse** [comment]
And here the update for iTerm: `\u0001historyfzf --query="\u0005"\u000d`
this needs to be used as 'send text as vim special characters': `\u0001` means start of line `\u0005` end of line and `\u000d` return

**Comment by pakelley** [comment]
Just to put this together (for iterm at least), I added a custom command in `/path/to/config/dir/fzf.nu`:
```
# fzf through shell history, typing result.
# To configure on iTerm, make a keybinding (presumably for C-r) whose action is "Send text with vim special chars",
#    and use: \u0001fzf-history --query="\u0005"\u000d
#    where \u0001 is for the start of a line, \u0005 is the end of a line, and \u000d is RET
def fzf-history [
	--query (-q): string # Optionally start with given query.
] {
    let cmd = (history | uniq | reverse | each { echo [$it (char nl)] } | str collect | fzf --query $"($query)")
    osascript -e $'tell application "System Events" to keystroke "($cmd)"'
}
```
Added in the instructions because one day I'll forget 😁. Also, I added `uniq` to filter out duplicate results.
Then in `/path/to/config/dir/config.toml` add `"source fzf.nu"` to your `startup` section, e.g.:
```
startup = ["source fzf.nu"]
```
And finally, in iterm add a keybinding (Keys > Key Bindings > +), presumably for ^-r, that binds to a `Send text with "vim" special chars` action, where the action is `\u0001fzf-history --query="\u0005"\u000d`.
Then restart `nu` and ^-r should work for both query and non-query results 🙂 

---

(side note)
If you get a `osascript is not allowed to send keystrokes. (1002)`, make sure iterm has access to Accessibility (Preferences > Security & Privacy > Privacy > Accessibility).
If you're like me and you get this when iterm already has access... just restart? I tried a few things, but then the restart finally helped. Not sure if it was a combination of things or just the restart though, tbh 😅

**Comment by fedoranvar** [comment]
my solutin for v0.59

**Comment by fellnerse** [comment]
Thats cool, that should work on mac as well I guess (will try it) and on cross terminal

**Comment by 89z** [comment]
Given example doesnt work with current version:

~~~
PS D:\Desktop\nushell-0.60.0> .\nu.exe
Error: nu::shell::unsupported_config_value (link)

  × Unsupported config value
     ╭─[C:\Users\Steven\AppData\Roaming\nushell\config.nu:224:1]
 224 │     event: [
 225 │       { edit: { cmd: insertString value: "fzf-history-search" } }
     ·       ─────────────────────────────┬─────────────────────────────
     ·                                    ╰── expected reedline EditCommand, got {cmd: insertstringvalue: fzf-history-search}
~~~

**Comment by azerbe** [comment]
> Just to put this together (for iterm at least), I added a custom command in `/path/to/config/dir/fzf.nu`:
> 
> ```
> # fzf through shell history, typing result.
> # To configure on iTerm, make a keybinding (presumably for C-r) whose action is "Send text with vim special chars",
> #    and use: \u0001fzf-history --query="\u0005"\u000d
> #    where \u0001 is for the start of a line, \u0005 is the end of a line, and \u000d is RET
> def fzf-history [
> 	--query (-q): string # Optionally start with given query.
> ] {
>     let cmd = (history | uniq | reverse | each { echo [$it (char nl)] } | str collect | fzf --query $"($query)")
>     osascript -e $'tell application "System Events" to keystroke "($cmd)"'
> }
> ```
> 
> Added in the instructions because one day I'll forget 😁. Also, I added `uniq` to filter out duplicate results. Then in `/path/to/config/dir/config.toml` add `"source fzf.nu"` to your `startup` section, e.g.:
> 
> ```
> startup = ["source fzf.nu"]
> ```
> 
> And finally, in iterm add a keybinding (Keys > Key Bindings > +), presumably for ^-r, that binds to a `Send text with "vim" special chars` action, where the action is `\u0001fzf-history --query="\u0005"\u000d`. Then restart `nu` and ^-r should work for both query and non-query results 🙂
> 
> (side note) If you get a `osascript is not allowed to send keystrokes. (1002)`, make sure iterm has access to Accessibility (Preferences > Security & Privacy > Privacy > Accessibility). If you're like me and you get this when iterm already has access... just restart? I tried a few things, but then the restart finally helped. Not sure if it was a combination of things or just the restart though, tbh 😅

I had to modify it a tiny bit to work with 0.63.0 on MacOS

```
let cmd = (history | uniq | reverse | each { |it| echo [$it (char nl)] } | str collect | fzf --query $"($query)")
```

The identifier `|it|` was missing. Thanks for your work!

**Comment by rosshadden** [comment]
As a contributor to this issue I should probably note that I now use the built-in history search. It's not nearly as good as fzf of course but it's much less hacky to use.

I wonder if nushell could allow for `fzf` to be specified as an intermediary or something so that we could use it in place of their built-in search. Then it could be used not only for history but any other built-in or custom menu.

**Comment by jokeyrhyme** [comment]
Something that neovim has done with their Lua API is provide `vim.ui.input()` and `vim.ui.select()`: these come with basic built-in implementations, but are intended to be replaced by custom user-land code where users want more features or different presentation styles

Over time, more of neovim's built-in functionality and third-party extensions will call these hooks (or whatever they've been replaced with)

Perhaps nushell could take a similar approach and define hooks or extensions points for when a menu/list needs to be presented to the user, and user-land configuration could swap in fzf or any compatible implementation

**Comment by azzamsa** [comment]
My current workaround:

```
    {
      name: "all history"
      modifier: control
      keycode: char_h
      mode: emacs
      event: [
        { edit: Clear }
        {
          edit: insertString
          value: "history_all"
        }
        { send: enter }
      ]
   },
```

```Nu
# List all history
def history_all [] {
  let history_ = (history | get command | uniq | reverse | to text | sk)
  xdotool type $history_
}

# List previous history in current directory
def history_in_pwd [] {
  let history_ = (history | where cwd == $env.PWD | get command | uniq | reverse | to text | sk)
  xdotool type $history_
}
alias hh = history_in_pwd
```

Feel free to throw any improvement!

**Comment by janosimas** [comment]
@azzamsa I just tried your solution but I got some issues.

- `xdotool` is taking ages to type the commands
- The command `history_all` is added to the history

Do you have a solution for any of those?

**Comment by azzamsa** [comment]
> xdotool is taking ages to type the commands

I don&rsquo;t see similar issue

> The command history<sub>all</sub> is added to the history

Yes, I have the same issue and still don&rsquo;t have enough time to solve it. Currently I just use the built-in \`Ctrl-r\` command

**Comment by azzamsa** [comment]
@janosimas now I ditched `skim` and just use built-in menu. It check all my requirements: no duplicate, sorted, only successful command, plus filter only command executed in current directory.

```Nu
 menus: [
    {
        # List all unique successful commands
        name: all_history_menu
        only_buffer_difference: true
        marker: "? "
        type: {
            layout: list
            page_size: 10
        }
        style: {
            text: green
            selected_text: green_reverse
        }
        source: { |buffer, position|
            history
            | where command =~ $buffer
            | reverse
            | where exit_status != 1
            | each { |it| {value: $it.command } }
            | uniq
        }
    }
    {
        # List all unique succesfull commands in current directory
        name: pwd_history_menu
        only_buffer_difference: true
        marker: "? "
        type: {
            layout: list
            page_size: 10
        }
        style: {
            text: green
            selected_text: green_reverse
        }
        source: { |buffer, position|
            history
            | where command =~ $buffer
            | reverse
            | where exit_status != 1
            | where cwd == $env.PWD
            | each { |it| {value: $it.command } }
            | uniq
        }
    }
]

  keybindings: [
    {
      name: "all history"
      modifier: control
      keycode: char_h
      mode: emacs
      event: { send: menu name: all_history_menu }
    }
    {
      name: "pwd history"
      modifier: control
      keycode: char_p
      mode: emacs
      event: { send: menu name: pwd_history_menu }
    }
  ]

}
```

**Comment by janosimas** [comment]
@azzamsa It looks pretty cool but I still cannot reproduce.

Do you have any special setting for your `history`? I don't have a `exit_status`or a `cwd` property.

**Comment by azzamsa** [comment]
> Do you have any special setting for your `history`? I don't have a `exit_status`or a `cwd` property.

No, it is built-in, I am on Nu 0.67.0, my full config is here:  https://github.com/azzamsa/dotfiles/blob/61a68518f545f92df690aecb8802681ce21fa0e2/nushell/.config/nushell/config.nu#L39

**Comment by janosimas** [comment]
Found it, `history_file_format: "sqlite"` has extra attributes

**Comment by fdncred** [comment]
The new `commandline` command really helps out here. This command works with `fzf` and skim's `sk` (if you replace the command below with the proper external). It may work with broot too, but i have not tried.
```
    {
      name: fuzzy_history
      modifier: CONTROL
      keycode: char_r
      mode: emacs
      event: {
        send: executehostcommand
        cmd: "commandline (history | each { |it| $it.command } | uniq | reverse | str collect (char nl) | fzf --layout=reverse --height=40% -q (commandline) | decode utf-8 | str trim)"
      }
    }
```

**Comment by DeeUnderscore** [comment]
Looks like you need to use null separators to handle multiline history entries properly, making the command something like this:

```nu
commandline (history | each { |it| $it.command } | uniq | reverse | str collect (char -i 0) | fzf --read0 --layout=reverse --height=40% -q (commandline) | decode utf-8 | str trim)
```

**Comment by YodaEmbedding** [comment]
Using @DeeUnderscore, here's what goes in `~/.config/nushell/config.nu`'s `keybindings` section:

```nushell
    {
      name: fuzzy_history
      modifier: control
      keycode: char_r
      mode: [emacs, vi_normal, vi_insert]
      event: [
        {
          send: ExecuteHostCommand
          cmd: "commandline (
            history
              | each { |it| $it.command }
              | uniq
              | reverse
              | str collect (char -i 0)
              | fzf --read0 --layout=reverse --height=40% -q (commandline)
              | decode utf-8
              | str trim
          )"
        }
      ]
    }
```

**Comment by washanhanzi** [comment]
`str collect` is marked as [deprecated](https://www.nushell.sh/book/commands/str_collect.html#frontmatter-title-for-deprecated). Now is `str join`.

**Comment by MatrixManAtYrService** [comment]
The fzf parameter `--scheme=history` is helpful to ensure that fzf orders its selections in a way that makes sense if the input data is a history file.  Here's what I ended up with: https://github.com/MatrixManAtYrService/configs/blob/7f68e5b6f82ef464bd6952d74b32bf0ee816653e/home-manager/config/nushell/config.nu#L760

**Comment by NotTheDr01ds** [comment]
@MatrixManAtYrService Great implementation - Thank you!  A few ideas for improvements:

* I believe `reverse` and `uniq` should be reversed, since `uniq` is only keeping the *first* occurrence and throwing off the `--scheme=history` sort order.  It took me a few minutes to figure out why my most recent command weren't showing up first in the list.

* Thanks for the great start on the multi-line support.  It's too bad `fzf` doesn't support multi-line out of the box like the `reedline` menu does.  However, in [one of the related `fzf` issues](https://github.com/junegunn/fzf/issues/2216#issuecomment-711977935) it was suggested to the preview feature here, which works great.  Just add `--preview '{}'`

**Comment by mxlje** [comment]
It seems that the `commandline` command has changed as the examples above did not work for me. I have adjusted the script based on comments here and have now ended up with this.

The key difference is the addition of `edit --insert` to the `commandline` call, which inserts the output of the fzf selection at the current cursor position. You can also remove that, which will make it default to replacing the current input buffer. I like that this way you can run a command, then type some prefix or brackets, and then insert a command from the history. I also used

```
keybindings: [
  {
    name: fuzzy_history
    modifier: control
    keycode: char_r
    mode: [emacs, vi_normal, vi_insert]
    event: [
      {
        send: ExecuteHostCommand
        cmd: "commandline edit --insert (
          history
            | get command
            | reverse
            | uniq
            | str join (char -i 0)
            | fzf
              --preview '{}'
              --preview-window 'right:30%'
              --scheme history
              --read0
              --layout reverse
              --height 40%
              --query (commandline)
            | decode utf-8
            | str trim
        )"
      }
    ]
  }
]
```

**Comment by NotTheDr01ds** [comment]
@mxlje Good idea on the `--insert` possibilities - That can greatly improve composability.  E.g.:

`let prev_result = ` <kbd>Ctrl</kbd>+<kbd>R</kbd> and the last line in the history is right there for insertion.

BUT ... The `--query (commandline)` gets in the way of that, since the `let prev_result` (or even the brackets you mentioned) get included in the fuzzy-search.

I'm almost thinking I might try two different keybindings:

* One with `--query (commandline)` but without `--insert`
* The other with `--insert` but without the `--query ...`

For now, I think I'm going to run just the second version since (a) I'll probably get the most benefit out of the composability improvement, (b) I think I can train myself to type the query *after* hitting the keybinding.

A few additional tips:

* You can get multi-line, syntax-highlighted preview with:
   
  ```Nushell
  --preview='echo -n {} | nu --stdin -c \'nu-highlight\''
  ```

* @fdncred added an `fzf` keybinding for increasing the size of the preview window that I've incorporated into my version.

Here's my current version.

```Nushell
{
  name: fuzzy_history
  modifier: control
  keycode: char_r
  mode: [emacs, vi_normal, vi_insert]
  event: [
    {
      send: ExecuteHostCommand
      cmd: "do {
        $env.SHELL = /usr/bin/bash
        commandline edit --insert (
          history
          | get command
          | reverse
          | uniq
          | str join (char -i 0)
          | fzf --scheme=history 
              --read0
              --layout=reverse
              --height=40%
              --bind 'ctrl-/:change-preview-window(right,70%|right)'
              --preview='echo -n {} | nu --stdin -c \'nu-highlight\''
              # Run without existing commandline query for now to test composability
              # -q (commandline)
          | decode utf-8
          | str trim
        )
      }"
    }
  ]
}
```

**Comment by NotTheDr01ds** [comment]
I believe it was the way that `fzf` interpolated the string.  If it detected `bash`, then it was consistent, at least.  Or something like that ...

**Comment by fdncred** [comment]
I wonder if we could submit a PR to fzf to have it support nushell better?

**Comment by whoslucifer** [comment]
I have added the keybindings but am getting this error

ll::external_command

  × External command failed
    ╭─[/home/asherah/.config/nushell/config.nu:16:1]
 15 │
 16 │ keybindings: [
    · ──────┬─────
    ·       ╰── Command `keybindings:` not found
 17 │   {
    ╰────

**Comment by DeeUnderscore** [comment]
`keybindings` is a record in `$env.config`, so it should go there.

(there is also a `keybindings` command, but that's separate, and does not support setting new binds)

**Comment by whoslucifer** [comment]
> ```nushell
> {
>   name: fuzzy_history
>   modifier: control
>   keycode: char_r
>   mode: [emacs, vi_normal, vi_insert]
>   event: [
>     {
>       send: ExecuteHostCommand
>       cmd: "do {
>         $env.SHELL = /usr/bin/bash
>         commandline edit --insert (
>           history
>           | get command
>           | reverse
>           | uniq
>           | str join (char -i 0)
>           | fzf --scheme=history 
>               --read0
>               --layout=reverse
>               --height=40%
>               --bind 'ctrl-/:change-preview-window(right,70%|right)'
>               --preview='echo -n {} | nu --stdin -c \'nu-highlight\''
>               # Run without existing commandline query for now to test composability
>               # -q (commandline)
>           | decode utf-8
>           | str trim
>         )
>       }"
>     }
>   ]
> }
> ```

Thanks. Its working now

**Comment by whoslucifer** [comment]
> `keybindings` is a record in `$env.config`, so it should go there.
> 
> (there is also a `keybindings` command, but that's separate, and does not support setting new binds)

Thanks. Its working now
