### ISSUE TITLE
^echo removes double quotes

### ISSUE THREAD

**Issue by casidiablo** [nushell/nushell#1617]
Running this: `^echo '[{"foo": "bar"}]'` we get:

```
[{foo: bar}]
```

But the expected output is 

```
[{"foo": "bar"}]
```

This is happening for me in NixOS using version `0.12.1`

**Comment by thegedge** [comment]
Related issue https://github.com/nushell/nushell/issues/1439

**Comment by thegedge** [comment]
Looks like this is resulting in the following parse:

```
built command "sh" "-c" "git commit \"-m\"this is a test\"\""
```

This would be the same as running this on the command line:

```
git commit "-m"this is a test""
```

So we'll need to drop those quotes around the entire thing.
