### ISSUE TITLE
Flip the default setting for `nu --stdin`

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1618]
**Is your feature request related to a problem? Please describe.**
Currently, users need to remember to pass `--stdin` to redirect stdin when they want to run -c or a script. However, most of the time, if you're calling `nu` from outside, you're going to want to redirect stdin.  

**Describe the solution you'd like**

We should consider flipping the default to stdin being redirected when running -c or a script, and then allow people to pass `--no-stdin` if they don't want this redirection.

**Comment by thegedge** [comment]
I think it could go either way, so it's hard to say which is more optimal. Ideally, we could determine if there's stdin, but I don't know of a super portable way to do that kind of check. Perhaps we could create a `bytes()` iterator and `peek()`?
