### ISSUE TITLE
Panic when running alias given an argument prefixed with $

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#1621]
**Describe the bug**
When passing an argument to an alias for an external command, and that argument is raw (i.e., not quoted), starts with a $, and can't be evaluated/resolved, panic occurs.

**To Reproduce**
1. `alias env [name] { ^echo $name }`
2. `env "$HOME"` (works)
3. `env $HOME` (panics)

**Expected behavior**
An appropriate error is displayed.

**Configuration (please complete the following information):**
 - OS: macOS 10.15.4 
 - Version: 72cf57d
 - Features: stable

**Comment by jonathandturner** [comment]
Fixed in #1624
