### ISSUE TITLE
Extract metadata (ID3, EXIF, XMP etc.) from common binary data files

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#163]
Binary data has some good metadata we could display. For example, mp3 files could show their encoding, length of the track, artist, and album.

**Comment by jonathandturner** [comment]
Unclear if we want these elements in the `tags` part or as the main data.

**Comment by Joshfindit** [comment]
Having some experience with file-metadata, I would *highly* suggest having metadata in flexible ‘tag’ structures. ID3, EXIF, etc can all be firehoses of data as well as parsing nightmares. The metadata of a file *should* be treated differently than the file itself, but “in the real world” we need metadata to travel with main data and so they can mashed togther separated by “header” and “footer” boundaries.

I just found out about Nu 4 minutes ago, but I’m already excited about being able to be free from the shackles of the old ways.

**Comment by waldyrious** [comment]
I for one would like to see this! (Commenting mostly to prevent stale-bot from closing this issue.)

**Comment by hustcer** [comment]
no stale

**Comment by hyiltiz** [comment]
Could we rename this issue to something like `Extract metadata (ID3, EXIF, XMP etc.) from common binary data files` since the main discussion is really about metadata, and not `opening mp3` which is probably better done with tools like `mpv` `cmus` and `ffplay`.

**Comment by jntrnr** [comment]
With Nushell's focus on loading structured data formats rather than extracting data from formats (like extracting tables from html, or exif from images etc), closing this issue.

This would be perfect material for plugins, though. Just not part of the core nushell experience.

**Comment by Joshfindit** [comment]
Adding a link to a plugin that pulls data from MP3s: https://github.com/notryanb/nu_plugin_id3
