### ISSUE TITLE
Can't cd to symlinked directories

### ISSUE THREAD

**Issue by mattbradbury** [nushell/nushell#1631]
**Describe the bug**
Can not 'cd' to directories which are symlinks to other directories.

**To Reproduce**
1. On Ubuntu 20.04
2. cd /bin  <--- Fails
3. cd /; cd bin <--- Changes to the symlinked directory
4. pwd  
(output:  /usr/bin )

**Expected behavior**
cd to the symlinked directory from anywhere, not just the parent directory of the symlink.  Display the symlinked directory path instead of the actual on disk path when you do change into the directory.

**Configuration (please complete the following information):**
 - OS: Ubuntu 20.04 Beta
 - Version 0.13.0
 - Optional features (if any)
    --features = stable

**Comment by thegedge** [comment]
Hmm, so it's not exactly that we can't cd to symlinked directories, but specifically it could be based on something else. My guess is on a faulty permissions check.

@mattbradbury What are the permissions on `/`, `/bin`, and `/usr/bin`?

**Comment by mattbradbury** [comment]
/ and /usr/bin are 755 root:root

/bin is 777, well lrwxrwxrwx  technically.

This is a 2day old install, so it’s almost pristine Ubuntu.

**Comment by quebin31** [comment]
@thegedge, I can confirm this also happens on regular symlinks with the ideal permissions, only if you aren't on the parent directory where the symlink resides, fails with relative and absolute paths
