### ISSUE TITLE
ls alias fails on ~

### ISSUE THREAD

**Issue by aeosynth** [nushell/nushell#1632]
```
alias l [x] { ls $x }
l ~
error: Alias failed to run
- shell:1:3
1 | l ~
  | ^ alias failed to run
- shell:1:3
1 | l ~
  | - diagnostic
```

**Configuration (please complete the following information):**
void linux
nu 0.13

**Comment by aeosynth** [comment]
not sure if this is the same issue or not, but it also fails on integers:

```
l 2
error: Alias failed to run
- shell:1:3
1 | l 2
  | ^ alias failed to run
- shell:1:3
1 | l 2
  | - Unknown Error(Error("invalid type: integer `2`, expected path string", line: 1, column: 61))
```

**Comment by thegedge** [comment]
@aeosynth the integer case is expected to fail, since `ls` expects paths/strings.  That being said, error messaging can be improved 🙂

**Comment by aeosynth** [comment]
in this case `2` is a path.

```
/tmp> mkdir 2
/tmp> ls 2
/tmp> l 2
error: Alias failed to run
```

**Comment by jonathandturner** [comment]
For folks looking to fix this - it looks like the `ls` in filesystem_shell.rs doesn't do its own normalize/canonicalize/absolutize, and as an alias we won't know to do it ahead of time as arguments are allowed to be `any`. 

For the second issue mentioned here: https://github.com/nushell/nushell/issues/1632#issuecomment-618751952, looks like we need to extend some of the coercions between types to be more generous. You can use a number as a path, as @aeosynth mentions, and we should allow the argument to coerce to a path.

**Comment by quebin31** [comment]
> For folks looking to fix this - it looks like the `ls` in filesystem_shell.rs doesn't do its own normalize/canonicalize/absolutize, and as an alias we won't know to do it ahead of time as arguments are allowed to be `any`. 
> 
> For the second issue mentioned here: https://github.com/nushell/nushell/issues/1632#issuecomment-618751952, looks like we need to extend some of the coercions between types to be more generous. You can use a number as a path, as @aeosynth mentions, and we should allow the argument to coerce to a path.

Actually the method we need there is `expand_path` from the parser crate, which expands `~` for all commands this automatically done for Paths and Patterns shapes, but as @jonathandturner said the arguments for aliases are `Any`, therefore no path expansion, my suggestion is to make the expansion there.

**Comment by LhKipp** [comment]
```shell
/home/leo/repos/nushell/nushell(main)> alias l -i [x] {ls $x}
/home/leo/repos/nushell/nushell(main)> l 2
───┬──────┬──────┬──────┬─────────────
 # │ name │ type │ size │  modified   
───┼──────┼──────┼──────┼─────────────
 0 │ 2    │ File │  0 B │ 25 secs ago 
───┴──────┴──────┴──────┴─────────────
/home/leo/repos/nushell/nushell(main)> l ~
────┬───────────────────────────────────────────────────────────────┬─────────┬──────────┬─────────────
 #  │                             name                              │  type   │   size   │  modified   
────┼───────────────────────────────────────────────────────────────┼─────────┼──────────┼─────────────
 plenty of stuff here :)
────┴───────────────────────────────────────────────────────────────┴─────────┴──────────┴─────────────
/home/leo/repos/nushell/nushell(main)> version
───┬─────────┬──────────────────────────────────────────┬────────────────
 # │ version │               commit_hash                │    features    
───┼─────────┼──────────────────────────────────────────┼────────────────
 0 │ 0.21.1  │ 4e17292a12a7913c8cd308e81af4f9c9fcb3f4fc │ [table 1 rows] 
───┴─────────┴──────────────────────────────────────────┴────────────────
```

This seems fixed for me :)

**Comment by aeosynth** [comment]
ls alias works for me now
