### ISSUE TITLE
can't use flags with alias

### ISSUE THREAD

**Issue by aeosynth** [nushell/nushell#1633]
```
alias l [x] { ls $x }
l -a
error: l unexpected -a
- shell:1:4
1 | l -a
  |    ^ unexpected flag (try l -h)
```

**Expected behavior**
`ls -a` should run

**Configuration (please complete the following information):**
void linux
nu 0.13

**Comment by quebin31** [comment]
One question @jonathandturner, how would this behave if the block inside is a pipeline?

**Comment by aeosynth** [comment]
works now
