### ISSUE TITLE
Aliases being per-item commands can sometimes have unexpected behaviours

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#1634]
**Describe the bug**
Aliases are always a `PerItemCommand`, but this can be a little awkward if they're wrapping a `WholeStreamCommand`.

**To Reproduce**

```
nushell on 📙 HEAD (88f06c8) is 📦 v0.13.0 via 🦀 v1.42.0
❯ alias chars [] { wc -c }
nushell on 📙 HEAD (88f06c8) is 📦 v0.13.0 via 🦀 v1.42.0
❯ cat Cargo.toml | chars
    5419
nushell on 📙 HEAD (88f06c8) is 📦 v0.13.0 via 🦀 v1.42.0
❯ cat Cargo.toml | lines | chars
       9
      11
      18
      41
      35
      15
      ...
```

**Expected behavior**
I would expect this to be the same as if I didn't use an alias, which looks like this:

```
nushell on 📙 HEAD (88f06c8) is 📦 v0.13.0 via 🦀 v1.42.0
❯ cat Cargo.toml | lines | wc -c
    5245
nushell on 📙 HEAD (88f06c8) is 📦 v0.13.0 via 🦀 v1.42.0
❯ cat Cargo.toml | wc -c
    5419
```

The discrepancy is likely because `lines` is dropping the newline char.

**Configuration (please complete the following information):**
 - OS: macOS 10.15.4
 - Version [e.g. 0.4.0]
 - Optional features (if any)

**Comment by jonathandturner** [comment]
@thegedge I wonder if we should revisit the idea of automatically transforming commands to `each` commands if there is an `$it`, otherwise they're always whole stream

**Comment by thegedge** [comment]
If we did that, we could really clean up externals even more. I think it's worth exploring the idea. `alias` could simply ask the block what kind of "sink" it has and decide what to do based on that.

**Comment by thegedge** [comment]
Another unexpected behaviour is https://github.com/nushell/nushell/issues/1654. Basically, we lose the "empty" characteristic of the originating input stream (constructed in `cli.rs` as the initial input stream to a pipeline). This means all external commands that are used as the _very_ first thing in an alias receive have a stdin pipe set up.
