### ISSUE TITLE
Vi: faster key timeout or keytimeout configuration

### ISSUE THREAD

**Issue by homburg** [nushell/nushell#1638]
# Problem
rustyline has a default delay/timeout of 500ms when pressing escape to switch from vi insert mode to vi normal model. My expectation from other shells/line editors is "no" delay.

# Suggestion
I'd like the default keytimeout to be lower (1 or 0 works in my terminal) (see https://github.com/kkawakam/rustyline/issues/371) or to add a config option to set the keytimeout for rustyline.

# Alternatives
Alternatively rustyline could have a smaller default or respect the `KEYTIMEOUT` env var like zsh

**Comment by jonathandturner** [comment]
@homburg - are you interested in submitting a PR for this? I'd be happy to accept one

**Comment by homburg** [comment]
> @homburg - are you interested in submitting a PR for this? I'd be happy to accept one

Sure, there does not seem to be a magical right value for everyone, so I'll probably add it as a configuration option with a low default value
