### ISSUE TITLE
Histogram does not work on numbers

### ISSUE THREAD

**Issue by siedentop** [nushell/nushell#1641]
**Describe the bug**
The documentation for `histogram` suggests that histograms can be created for numbers (like integers). This does not work (version 0.13.0).

**To Reproduce**
1. Assert that `version == 0.13.0`.
2. Read the [histogram documentation](https://github.com/nushell/nushell/blob/master/docs/commands/histogram.md). 
3. Run the code as given in the documentation.

File: `make_random.awk`, (Make executable)
```awk
#!/usr/bin/awk -f
BEGIN {
  printf("value\n");
  srand();
  i=1;
  while (i++<=50) {
    printf("%d\n",int(rand()*5 + 0.5));
  }
  exit;
}
```

```nu
> ./make_random.awk > random.csv
> open random.csv | histogram value
error: Type Error
- shell:1:33
1 | open random.csv | histogram value
  |                             ^^^^^ Expected string, found integer
```

**Expected behavior**
I'd expect the same behavior as observed in the [documentation](https://www.nushell.sh/commands/histogram.html). Namely, that ` | histogram value` provides a histogram and does not have an error.

If generating histograms for numbers is not intended, it would be great to update the documentation.

**Screenshots**

**Configuration (please complete the following information):**
 - OS: macOS
 - Version: nu 0.13.0 (installed via Cargo)
 - Optional features (if any): None

**This works**
This behavior works: `./make_random.awk | lines | trim | parse "{key}" | histogram key`
Note that it seems to me that the numbers are treated as strings.

**Originally raised in Discord**:
https://discordapp.com/channels/601130461678272522/614593951969574961/702718213850660886
https://discordapp.com/channels/601130461678272522/614593951969574961/702726558275600456

As mentioned in Discord by @jonathandturner, @andrasio might be a good assignee.

**Comment by thegedge** [comment]
I guess what's happening here is that the `value` given to histogram is the actual value of `value`, not the string `"value"`. The struggle here is how much do we want to be explicit vs allowing bare words. I think in this case, it's intended to be a column path, so `histogram` probably just needs some tweaking

A quick workaround for the time being (I think) is to use `open random.csv | histogram "value"` 🙂

**Comment by rimathia** [comment]
Since this was marked as a good first issue, can I try and let you know on Saturday whether I think I'll manage?

**Comment by thegedge** [comment]
Yep, go for it @rimathia. Let me know if you have any questions, or join us on discord in `#developing` (I'm not there as much lately, but there's usually someone around who can help).

**Comment by siedentop** [comment]
@thegedge your suggestion does not work for me:
```
> open random.csv | histogram "value"
error: Type Error
- shell:1:35
1 | open random.csv | histogram "value"
  |                             ^^^^^^^ Expected string, found integer
```

**Comment by thegedge** [comment]
Not 100% sure, but really looks like you found a bug 🙂

**Comment by siedentop** [comment]
This is the issue: 

`crates/nu-cli/src/commands/group_by.rs:78:28` fails the `as_string()` conversion, which is implemented in 
`crates/nu-protocol/src/value.rs:248`. 


## Possible Solutions
1. Extend `as_string` so that Integer are converted to strings. This means that it will work.
2. First-class support for numbers. This would enable bining of numbers, show zeros for missing values, etc.

*I prefer the second option*, from a user perspective. 

Here is the required patch for the first option. If desired, I will create a PR for that.

```diff
diff --git a/crates/nu-protocol/src/value.rs b/crates/nu-protocol/src/value.rs
index 286ae4cb..b65e4619 100644
--- a/crates/nu-protocol/src/value.rs
+++ b/crates/nu-protocol/src/value.rs
@@ -249,6 +249,7 @@ impl Value {
         match &self.value {
             UntaggedValue::Primitive(Primitive::String(string)) => Ok(string.clone()),
             UntaggedValue::Primitive(Primitive::Line(line)) => Ok(line.clone() + "\n"),
+            UntaggedValue::Primitive(Primitive::Int(int)) => Ok(int.to_string()),
             UntaggedValue::Primitive(Primitive::Path(path)) => {
                 Ok(path.to_string_lossy().to_string())
             }
```

### Omissions
The patch is missing implementations for

* Decimal
* Date
* Duration
* Boolean

---
## Misc

Debug config for VS-Code:
```json
{
            "type": "lldb",
            "request": "launch",
            "name": "Histogram",
            "program": "${workspaceFolder}/target/debug/nu",
            "args":  "'-c printf \"1\n1\n2\n2\n\" | lines | trim | parse \"{key}\" | str --to-int key | histogram key'",
            "cwd": "${workspaceFolder}"
        }
```

**Comment by rimathia** [comment]
Too slow, I didn't realize group was just supposed to work here. I'll find something else.

**Comment by thegedge** [comment]
@siedentop no worries. Your suggestions were great. Looks like (1) was the fix that went in, although at a different level.
