### ISSUE TITLE
brew outdated, can't update with pre-release

### ISSUE THREAD

**Issue by jzaefferer** [nushell/nushell#1643]
**Describe the bug**
`brew install nu` installs 0.12.0, but trying to use `brew bump-formula-pr nushell --url https://github.com/nushell/nushell/archive/0.13.0.tar.gz` to update the formula fails, since the 0.13.0 release is still marked as a pre-release

```
brew bump-formula-pr nushell --url https://github.com/nushell/nushell/archive/0.13.0.tar.gz
==> Downloading https://github.com/nushell/nushell/archive/0.13.0.tar.gz
==> Downloading from https://codeload.github.com/nushell/nushell/tar.gz/0.13.0
######################################################################## 100.0%
Warning: Cannot verify integrity of 352073a98d2709a8d00a0715f2e179eeb5f7311f48016a05310e903f57dbca92--nushell-0.13.0.tar.gz
A checksum was not provided for this resource.
For your reference the SHA-256 is: a07f730fa5dfe96ea3104b1cc13d2e72951a754870f22fb0dac6e30a359c6d8e
==> replace /https:\/\/github\.com\/nushell\/nushell\/archive\/0\.12\.0\.tar\.gz/ with "https://github.com/nushell/nushell/archive/0.13.0.tar.gz"
==> replace "f6bd3b36722b2edd7a89b945c3e9d91dcc1c32e472ba82f61816c65b0083cde0" with "a07f730fa5dfe96ea3104b1cc13d2e72951a754870f22fb0dac6e30a359c6d8e"
nushell:
  * 0.13.0 is a GitHub prerelease
Error: 1 problem in 1 formula detected
Error: `brew audit` failed!
```

Removing the pre-release toggle should be trivial. Though maybe you could integrate `brew bump-formula-pr nushell --url [source-url]` into your release process?

I'm not sure what happens when that command finishes, since its currently failing. Though the result should be something like https://github.com/Homebrew/homebrew-core/pull/52402

**Comment by jzaefferer** [comment]
It would help to unmark the 0.13.0 release as "pre-release"

**Comment by thegedge** [comment]
I think we're not wanting to do so, because pre release really makes sense here.nushell is still quite "beta" in the sense that things are breaking from one release to the next.

I wonder if there's a way where we can keep "pre release", but still be able to simplify a bump in homebrew 🤔

**Comment by jzaefferer** [comment]
Is this documented anywhere?

0.12.0 made it to brew, so somehow this works.

**Comment by jzaefferer** [comment]
I really wanted to try out aliases - started writing a bug report about how they're broken, until I realized that brew only installed 0.12

**Comment by thegedge** [comment]
> Is this documented anywhere?

Which thing in particular?

> 0.12.0 made it to brew, so somehow this works.

Yeah, it must work. Looking at the update to 0.12 (https://github.com/Homebrew/homebrew-core/commit/6d1f38c65e12fb6168618b9027bed63f10efdd0b) it looks like it was bumped manually.

**Comment by jzaefferer** [comment]
I still don't get how a pre release is helping anyone here - the 0.x.x version hints at the unstable state of the project, and the docs clearly say that it's in somewhat early development.

**Comment by jonathandturner** [comment]
@jzaefferer - I'm happy to stop using the "pre release" flag if it's causing problems with release automation tools.  You're right that it's clearly documented that it's pre-1.0 in other places

**Comment by jonathandturner** [comment]
@jzaefferer - if I edit 0.13 to remove the "pre release" flag, would that help here?

**Comment by jzaefferer** [comment]
Yeah, I think so. At least it should get us beyond the 'brew audit' issue

**Comment by thegedge** [comment]
Pre-release tag is removed. No prerelease errors, but I did get some weird SSL errors. Still, I pushed a PR: https://github.com/Homebrew/homebrew-core/pull/53803.

Moving forward, we'll not tag as a prerelease. We'll try to remember to bump in homebrew, but in case we forget, `bump-formula-pr` should work without any special flags.

**Comment by thegedge** [comment]
https://github.com/Homebrew/homebrew-core/pull/53803 is in. Just tried installing 0.13.0 and everything is 👍
