### ISSUE TITLE
Should "command --help" work for for commands with mandatory arguments?

### ISSUE THREAD

**Issue by rimathia** [nushell/nushell#1650]
**Is your feature request related to a problem? Please describe.**

kill -h (or any command with one or more mandatory arguments) gives an output similar to this:

error: kill requires process id of process that is to be killed parameter
- shell:1:7
1 | kill -h
  | ^^^^ requires process id of process that is to be killed parameter

Which is very clear about what I should type:

kill 42 -h then actually outputs the help message

**Describe the solution you'd like**
I would like "command --help" or "command -h" to always output the help message even if the command has one or more required arguments.

**Describe alternatives you've considered**
Inserting a dummy argument to get the help  message works perfectly fine, this is a pure "let nushell be even nicer to the user" feature.

**Comment by rimathia** [comment]
If you think this may be suitable as a first issue I would be interested in taking a stab at it.

**Comment by jonathandturner** [comment]
@rimathia that'd be great! You can find the logic for required positional args towards the bottom of parser.rs in the nu-parser sub-crate. If you have any questions feel free to ask here or on the discord.

**Comment by jonathandturner** [comment]
Fixed by #1659
