### ISSUE TITLE
ssh not working

### ISSUE THREAD

**Issue by ksnyde** [nushell/nushell#1654]
When I use SSH to go into a different machine I get the following error to start:

```sh
Pseudo-terminal will not be allocated because stdin is not a terminal.
```

This can be avoided by adding the `-tt` parameter to SSH and while I can login to the remote machine it would appear that there is something different about stdin, that any command does not return anything to the visible terminal (my suspicion is the command was executed but the results not returned). 

**To Reproduce**
1. ssh to any host using the `-tt` parameter (e.g., `ssh --tt root@myserver.com`)
2. type `ls`

**Expected behavior**
I would expect to see a directory listing and instead i can see the carraige return move the cursor down a line but then it never comes back with anything.

**Configuration (please complete the following information):**
 - OS: macOs
 - Version: Catalina
 - Nushell version: 0.13.0

**Comment by thegedge** [comment]
Hmm, interestingly, it works for me locally, in Catalina. I set up "Remote login"  in my sharing preferences, and ran `ssh localhost` and 👍

Trying to think of what could be different, I could only think of SSH config. Mine's pretty bare. Anything in yours that you think could be related?

**Comment by jonathandturner** [comment]
It might also matter if you're calling `ssh` from inside an alias or a pipeline rather than as a stand-alone command.

**Comment by thegedge** [comment]
Ah, good point, @jonathandturner. Outside of nushell I get this:

```
$ echo test | ssh localhost
Pseudo-terminal will not be allocated because stdin is not a terminal.

$ echo $?
1

$ echo test | ssh localhost 'cat'
test
```

I get the same inside of nushell, and also created an "ssh echo" alias and everything worked as expected.

**Comment by ksnyde** [comment]
Ok, my **grok** proficiency is quite low with Nushell at the moment but I have retried today and I'm embarrased to say that maybe I was _only_ getting this result when I used an alias. I have the following setup:

```sh
> config --get startup
alias wordpress [] { ssh root@192.168.1.99 }
```

This does indeed present with the "Psuedo-terminal" message. If I directly type in the **ssh** command it _does_ seem to work (which I swear was not working with 0.12.0 but upgraded at some point and maybe didn't take close enough note of it).

**Comment by thegedge** [comment]
Thanks for the clear explanation, @ksnyde!

So it was indeed an `alias` issue (which I should have tried, my bad). I think @jonathandturner and I talked about this issue recently, where things inside the alias block don't understand that they're the _very_ first command, in which case they don't need any stdin piping.

**Comment by ksnyde** [comment]
@thegedge from the articulation i'm hearing though I'd have thought that putting a native **nu** command into the first position in the pipeline would resolve this issue but I still continue to have the issue even when I inject the "echo" into the first slot in the pipeline.

**Comment by thegedge** [comment]
I'll try to highlight the issue, and how to currently work around it, with examples:

```
❯ ssh me@host.com
```

This should work without issue.

```
❯ alias myssh { ssh me@host.com }
❯ myssh
```

In this example, although you would think the `ssh` in `myssh` is the very first thing that can run and doesn't have a stdin pipe, we currently do set up a stdin pipe with an empty input stream. This is what's broken, because that isn't the behaviour we want.

```
❯ alias myssh { echo; ssh me@host.com }
❯ myssh
```

This will currently work, because the empty stream gets consumed by an echo (for all intents and purposes, a "no op") and then ssh is ran regularly.

We do want to fix this so that the second example works, but that should be a way to work around it for now 🙂

**Comment by thegedge** [comment]
This is essentially https://github.com/nushell/nushell/issues/1654, so I'm going to consider this one a duplicate. Feel free to subscribe to that issues, @ksnyde.
