### ISSUE TITLE
Make `trim` trim all columns and rows

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1657]
**Is your feature request related to a problem? Please describe.**
Right now the `trim` command expects to get a stream of strings to trim.  Often, though, when you really want to `trim` is when you have a table and the data has spaces around it.

**Describe the solution you'd like**
`trim` should be extended to work on rows as well as strings. For rows, it will go one-deep and trim the contents of each column, outputting the newly-trimmed rows.

**Describe alternatives you've considered**
We could make a new command to do this, but I think extending `trim` is the most natural.

**Additional context**
You can find the current `trim` command in https://github.com/nushell/nushell/blob/master/crates/nu-cli/src/commands/trim.rs

Tests in: https://github.com/nushell/nushell/tree/master/crates/nu-cli/tests/commands (though it looks like `trim` doesn't have tests, yet, and we should add them)

**Comment by rimathia** [comment]
I'll have a look at it.

**Comment by rimathia** [comment]
Just for my understanding: Is the idea explicitly that trim should only go one-deep into rows and not more than that (e.g. with tables containing tables)? The use case of "trim strings at any depth in this table" seems plausible but not obvious to me. Or is the question based on a misunderstanding of how nesting works?

**Comment by jonathandturner** [comment]
@rimathia - I'd start with only going in one level deep.  If that's not enough we can extend it later, but at least one level will be pretty useful.

**Comment by thegedge** [comment]
Closed by https://github.com/nushell/nushell/pull/1664
