### ISSUE TITLE
Revisit name?

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#166]
There may be some naming confusion with other projects (nuget was mention as one possible confusion point). We may want to revisit, or decide that we won't revisit and close this issue.

**Comment by andrasio** [comment]
I think we can close this issue now. It's too late. @jonathandturner @wycats

**Comment by Hrxn** [comment]
*"With the right attitude, it's never too late"* 
— unknown

**Comment by jonathandturner** [comment]
We could change it, but it'd need to be significantly better to handle all the drawbacks

**Comment by JosephTLyons** [comment]
I'd vote to close this.  `nushell` is already pretty popular and has a ton of momentum behind it.  Changing it might kill some of that momentum, IMO.

**Comment by jonathandturner** [comment]
Agreed. Getting votes from other core folks. @andrasio @wycats @thegedge

**Comment by thegedge** [comment]
Yeah, I'm 👍 for the name. Agree on the momentum. A name change would likely be detrimental to the momentum at this point.
