### ISSUE TITLE
history incomplete

### ISSUE THREAD

**Issue by ksnyde** [nushell/nushell#1666]
I find the history very limiting, here are what I believe to be critical (and then nice-to-have) features:

- HISTORY LENGTH:  I use my history as a means of an informal audit as well as a reminder of less used commands on certain servers. Having the history default to 100 items is fine but this really should be configurable to whatever the user/use-case needs
- WHERE: I wanted to try build my version of the GREP request (from below) but I tried what I thought was obvious:

    - `history | where value =~ 'ls'`
    - `history | where <value> =~ 'ls'`

but in both cases I was told:

>  Expected row or table, found string" for **value**

I remember reading somewhere that some commands like `ls` if not piped are automatically piped into a table formatter (or something to this effect) and I suspect this table is likely being created by that effect but in the commands section of the documents I can't find any reference to this and I don't have time to go through ever page again.

My last attempt to address this involved using the `^` operator. I figured I could get to the old **history** command by typing:

- `^history | grep ls`

but this failed with a command not found. I then tried:

- `history | ^grep ls`

this sort of worked and I guess maybe helps me to better understand the `^` operator as basically blocking the auto-formatting operator. Unfortunately, unlike the traditional unix command, this version of history is not CR delimited so the output is not readable at all. I'm sure I could pipe that again and put into a format that I could use but I've now run into my window of time and must get back to coding ;) 

NICE TO HAVE:

- GREP: I think most people have muscle memory where they can use `history | grep ABC` to look for a particular command. While I suspect there's a way to achieve this with the more power "where clause" (which there should be an example of in docs) it would be nice if piping to grep still worked as expected. I think little flourishes like this would help maintain people trying out Nu to stick with it.

**Comment by ksnyde** [comment]
Oh and right after I committed (to myself) to get back to coding I instead looked at the docs again and finally found `autoview` in the pipeline section and had a brief moment of optimism where I thought this would work:

> `history | ^grep ls | autoview`

But nothing; just a long concatenated string which I'm now guessing is all that's left from running grep with the `^` modifier

**Comment by aeosynth** [comment]
you can use `$it`

    history | where $it =~ ls

i agree history size is too small, bash default is 500 lines and that's still small

**Comment by aeosynth** [comment]
fixed with https://github.com/nushell/nushell/pull/1837 - set `history_size = 10_000` in config

**Comment by alexandrestein** [comment]
This seems to not been working for me :disappointed: :
```
↑50% ➜ history | count
101
~ 
↑51% ➜ config get history_size
10000
~ 
↑51% ➜ history | count
101
```

I'm on linux using a compiled version with extra feature:
```
↑53% ➜ version
───┬─────────┬────────────────
 # │ version │    features    
───┼─────────┼────────────────
 0 │ 0.21.0  │ [table 3 rows] 
───┴─────────┴────────────────
~ 
↑54% ➜ version | get features
───┬───────────
 0 │ default   
 1 │ clipboard 
 2 │ trash     
───┴───────────
```
