### ISSUE TITLE
Build autosuggest functionality in?

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#167]
A good example of "did you mean?" UX improvements: https://github.com/nvbn/thefuck

We could allow commands to have completions and also autocorrections/did-you-mean? The system could then first fail and if there's a suggested fix, offer to run the suggested fix.

**Comment by mati865** [comment]
Should this be closed?
> The system could then first fail and if there's a suggested fix, offer to run the suggested fix.

Functionality to run suggestion like in thefuck is missing.
