### ISSUE TITLE
Add a from_parquet command

### ISSUE THREAD

**Issue by jakeswenson** [nushell/nushell#1671]
**Is your feature request related to a problem? Please describe.**
Yes! But not a problem with `nu` -- I wan't an easy way to view `.parquet` files.

**Describe the solution you'd like**
I'd like to add a `from-parquet` command that supports the `.parquet` file format and parses into a `nu` value like the `from-` commands.

**Describe alternatives you've considered**
Can recommend [`parquet-tools`](https://github.com/apache/parquet-mr/tree/master/parquet-tools) to users, but it would be nice if it could integrate with `nu` values.

**Additional context**
We should use [the parquet crate](https://crates.io/crates/parquet)

I'm happy to look at this work.

**Comment by jonathandturner** [comment]
@jakeswenson please do! Feel free to ask questions here or on discord

**Comment by jakeswenson** [comment]
@jonathandturner, now that the `parquet` crate builds in `stable` I've got a basic plugin working, see here: https://github.com/jakeswenson/nu_plugin_from_parquet

Any thoughts on where you want plugins to live longer-term? (in this repo, or community ones in separate repos?)

**Comment by alippai** [comment]
@jakeswenson I'm new to rust, but doesn't your crate read parquet row-by-row? I didn't benchmark it, but in theory you should:

1. read one column per batch
2. convert it to the desired format
3. update the values in a pre-allocated row based (nu) format
4. do 1-3. in loop for the next columns
5. do 1-4. in a bigger loop doing this batch-by-batch

**Comment by jakeswenson** [comment]
Hi @alippai, thanks for your interest.

> I'm new to rust, but doesn't your crate read parquet row-by-row?

yes.

>  didn't benchmark it, but in theory you should:

What _should_ be done depends on the goal. I am currently more interested in making this work and less focused on making this as performant as possible. But the process you've outlined above could make sense when the time comes.
I think that the current `nu` plugin system is going to be a bigger issue since it can't support predicate pushdown, which is far more interesting from a performance perspective when dealing with big data.

This is just the first release, version `0.0.0`. 
I am certain there are many improvements to be had, and PRs are always welcome.

@alippai do you have any suggestions related to the questions I raised above about where plugin code should live?

**Comment by alippai** [comment]
It's really great, that it's happening, thank you!

Given that nu is a binary tool which is deployed using rpm, conda, nix or other package managers it would be nice to be able to upstream the package, put the plugin into core nu. This way when somebody uses nu they doesn't get error about not being able to parse parquet or the nu-plugin-parquet is not available in their repository when they try to install it.

The predicate pushdown sound like a really big loss, you are 100% right that it's a magnitude bigger question.

**Comment by jonathandturner** [comment]
@jakeswenson - we're still collecting the plugins in one place, so if you think it's ready let's land it into the main repo.

At some point in the future, we'll make a repo dedicated to them, but we're not quite there yet.

**Comment by jakeswenson** [comment]
Awesome! Thanks all for the feedback. @jonathandturner I'll submit a PR later today to add this to the directory where other plugins live. Thanks!
