### ISSUE TITLE
where does not respond to `-h` flag

### ISSUE THREAD

**Issue by derekcollison** [nushell/nushell#1673]
`where -h` does not work

**Expected behavior**
Shows help

**Screenshots**
![image](https://user-images.githubusercontent.com/90097/80409398-a3494900-887d-11ea-8100-cc8e2ca3c402.png)

**Configuration (please complete the following information):**
 - OS: MacOSX Catalina
 - Version 0.13.0

**Comment by jonathandturner** [comment]
Thanks for the report. This should be fixed in the latest master. If you still see it there, or in the upcoming release, please reopen this issue and let us know.
