### ISSUE TITLE
commands shown in argument tab completions

### ISSUE THREAD

**Issue by aeosynth** [nushell/nushell#1675]
**To Reproduce**
```
mkdir a/foo
cd a
cd f<tab>
```

**Expected behavior**
the line should expand to `cd foo/`

instead nothing happens, and pressing `<tab>` again shows:

```
foo          from-eml     from-bson    from-sqlite  from-xml     from-vcf
first        from-tsv     from-json    from-toml    from-yaml
format       from-ssv     from-ods     from-url     from-yml
from-csv     from-ini     from-db      from-xlsx    from-ics
```

**Configuration (please complete the following information):**
void linux
nu 0.13.1 c704157bc8aec542a2afc5170b13d863d84ec59e

**Comment by thegedge** [comment]
I wasn't able to reproduce this, but there are other issues when attempting to do so. We're consolidating the completions effort in https://github.com/nushell/nushell/issues/290 for now.
