### ISSUE TITLE
run from Azure Cloud Shell missing libxcb-shape.so.0

### ISSUE THREAD

**Issue by ctaggart** [nushell/nushell#1676]
**Describe the bug**
I like running Rust binaries from Azure Cloud Shell.  When I download and extract the 0.13.0 linux binary and try to run it, I get:
```
nu: error while loading shared libraries: libxcb-shape.so.0: cannot open shared object file: No such file or directory
```

**To Reproduce**
1. download binary
`curl -LO https://github.com/nushell/nushell/releases/download/0.13.0/nu_0_13_0_linux.tar.gz`
2. extract binaries
`tar xf nu_0_13_0_linux.tar.gz`
3. add to PATH
`export PATH=$HOME/nu_0_13_0_linux/nushell_0_13_0:$PATH`
4. run `nu`

**Expected behavior**
It includes the dependencies or there are instructions for installing them.

I attempted to download and put the binaries in the same directory, but it did not work.
```
apt-get download libxcb-shape0
ar x libxcb-shape0_1.11.1-1ubuntu1_amd64.deb data.tar.xz
tar x -C $HOME/nu_0_13_0_linux/nushell_0_13_0 --strip-components 4 -f data.tar.xz ./usr/lib/x86_64-linux-gnu/libxcb-shape.so.0.0.0 ./usr/lib/x86_64-linux-gnu/libxcb-shape.so.0
```

**Screenshots**

**Configuration (please complete the following information):**
Azure Cloud Shell is on:
```
$ lsb_release -da
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

**Comment by jonathandturner** [comment]
@ctaggart - I wonder if the version of Ubuntu is too old for the versions that Nu gets built against.  The release builds are built with all the features, so they end up pulling in a few extra libraries.

You might try building it from master using more normal settings, if you can.  This should give you fewer extra library dependencies.

Ideally, in the future we'll do package release so you don't have to try to get a tarball running.

**Comment by ctaggart** [comment]
> Ideally, in the future we'll do package release so you don't have to try to get a tarball running.

For Azure Cloud Shell, you can not install packages due to [limited user permissions](https://docs.microsoft.com/en-us/azure/cloud-shell/limitations#user-permissions). The tarball will still be needed.

**Comment by jonathandturner** [comment]
I guess something we'll need to decide is if the tarball should have the full set of features, or if we should assume that if you get the tarball that you're on a more limited linux system, or on a distro that may not have support out of the box.  I can imagine that tarball should be more compatible, and that the distros can ship a more full-featured version also.
