### ISSUE TITLE
"kB" not recognised for size, but "kb" is, and "Kb" is.

### ISSUE THREAD

**Issue by rbtcollins** [nushell/nushell#1678]
**Describe the bug**

Something odd with the size handling.

```
? ls | where size > 10KB
? ls | where size > 10Kb
? ls | where size > 10kb
? ls | where size > 10kB
error: Coercion error
- shell:1:22
1 | ls | where size > 10kB
  |            ^^^^ bytes
- shell:1:22
1 | ls | where size > 10kB
  |                   ---- string
? ls Jenkinsfile
──────────┬─────────────
 name     │ Jenkinsfile
 type     │ File
 size     │ 9.0 KB
 modified │ 5 hours ago
──────────┴─────────────
```

I expected either the 2nd example to show the file (as it is larger than 10 Kilo-*bits*), and the 3rd and 4th to both be errors, or I could understand `kb` and `KB` both being Kilo-Bytes, and Kilo-bits being not available. But accepting `Kb`, which is the SI unit for Kilo-bit, treating it as Kilo-byte, and then not accepting `kB` - it's done my head in.

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**
 - OS: Linux
❯ version
─────────┬────────
 version │ 0.13.0
─────────┴────────

 - stable features

**Comment by jonathandturner** [comment]
@rbtcollins - are you interested in taking this one, by chance? It should be a pretty straightforward fix. 

https://github.com/nushell/nushell/blob/master/crates/nu-parser/src/parse.rs#L273

**Comment by thegedge** [comment]
Resolved by https://github.com/nushell/nushell/pull/1693
