### ISSUE TITLE
Book introduction out of date

### ISSUE THREAD

**Issue by rbtcollins** [nushell/nushell#1679]
**Describe the bug**
The book describes on https://www.nushell.sh/book/en/introduction.html  `sys` having `host.users` with a string content and using `echo $it`, but these examples no longer work.

**To Reproduce**

```
sys | get host
──────────┬─────────────────────────────────────────────
 name     │ Linux
 release  │ 5.3.0-1019-azure
 version  │ #20-Ubuntu SMP Fri Mar 27 23:54:23 UTC 2020
 hostname │ lifeless
 arch     │ x86_64
 uptime   │ 8:03:47:32
 sessions │ [table 2 rows]
──────────┴─────────────────────────────────────────────
```

Note sessions rather than users, and then 
```
sys | get host.sessions
───┬─────────
 # │ <value>
───┼─────────
 0 │ robertc
 1 │ robertc
───┴─────────
```
note the tab format with <value> rather than the books example output:
```
> sys | get host.users
jonathan
```
And `echo $it` then fails to be useful in this fashion:
```
sys | get host.sessions | echo $it
───┬─────────
 # │ <value>
───┼─────────
 0 │ robertc
 1 │ robertc
───┴─────────
```

**Configuration (please complete the following information):**
 - OS: Linux 
 - Version 0.13
 - Optional features (if any): stable

**Comment by thegedge** [comment]
Hey, @rbtcollins 👋 

I also created https://github.com/nushell/book/issues/68, linking back here.

**Comment by rbtcollins** [comment]
Thanks

**Comment by thegedge** [comment]
Looks like it was fixed 🙂
