### ISSUE TITLE
Support math operations

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#168]
Would be nice to be able to evaluate simple expressions in the shell. Things like `2 + 3` either via raw expression or via a new command (`calc` maybe?)

**Comment by jonathandturner** [comment]
I think a `calc` command is probably best.

**Comment by terencode** [comment]
What's wrong with `echo $((3 * 2))` ?

**Comment by patriksvensson** [comment]
@jonathandturner I could give this a shot if it's up for grabs.

**Comment by jonathandturner** [comment]
@patriksvensson - please do

**Comment by jonathandturner** [comment]
@terencode - we could support a shorthand like that in the future, potentially

**Comment by terencode** [comment]
Ok, thanks.

**Comment by JesterOrNot** [comment]
Hey, can I help? if so am I correct in that you want it to be in Rust is Bash ok?

**Comment by loksonarius** [comment]
Just tossing out a possibly farfetched solution, but how does having something like a `lua` command that reads inputs and passes each input to a (possibly in-line) LUA script that can do whatever transformations (including arithmetic calculation) per line and output each result as a row for an output table?
Doesn't necessarily have to be LUA, maybe a more functional language would be more appropriate for functional operations on a row of data, but the basic idea of off-loading arithmetic and traditional computation to a subsystem that's well designed for it and can be embedded.

I see there's a functional-style language that's implemented in Rust that should be embedable: [gluon](https://github.com/gluon-lang/gluon).

Some sample usage could look like:

```
ls | pick name size | lua "name = input.name, size_mb = input.size / 1024"
```

where the calc string defines the inside out a LUA table that gets printed in a format suitable for more piping. A sample wrapper script for a `lua` command could look like:

<img width="496" alt="image" src="https://user-images.githubusercontent.com/7764106/66598749-bad61400-eb6f-11e9-9a91-55bd27a1650d.png">

I concede that this doesn't address issues where maybe basic arithmetic is needed for something like a `where` clause, but if a `calc` command is being proposed as a viable solution, I'd evaluate this as a potential alternative to it.

**Comment by coderkalyan** [comment]
Hey, is this open? I'd like to work on it! If its ok, I will open a simple PR with basic `calc` functionality, and @jonathandturner can let me know if there is anything in particular he needs (as I'm new to the repo)

**Comment by andrasio** [comment]
#900

**Comment by miller-time** [comment]
Is #574 a duplicate of this?

**Comment by coolshaurya** [comment]
I am interested in working on this. Doesn't look too difficult.

So two ways I can think of implementing this are -

1. Use [meval](https://github.com/rekka/meval-rs) for math expression parsing. Requires an additional dependency to be added.
1. Implement the math parser yourself like https://gitlab.com/jrop/rust-calc/tree/master. Requires much more effort but needs no extra dependencies.

I personally think option 1 is the better way to do this.

Also, should this be implemented as a plugin or a command ?
