### ISSUE TITLE
clip: add pasting

### ISSUE THREAD

**Issue by aeosynth** [nushell/nushell#1690]
**Describe the solution you'd like**
In addition to copying, the `clip` command should be able to paste.

**Describe alternatives you've considered**
The alternative is to keep using external programs for pasting.

**Comment by 1ntEgr8** [comment]
For pasting, I think it would be better to have a separate `paste` command. We could use a flag (like say `-p`) on `clip` to indicate pasting, but it doesn't feel very natural.

Thoughts?

**Comment by 1ntEgr8** [comment]
@jonathandturner Is this feature on the roadmap/has been implemented?

**Comment by jonathandturner** [comment]
@1ntEgr8 - still worth exploring

the bot is trying to help clean out issues where people are no longer following them (sorry for the noise)
