### ISSUE TITLE
Support for prompt hooks

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#1695]
**Is your feature request related to a problem? Please describe.**
I've been trying to build support for `nushell` into [`zoxide`](https://github.com/ajeetdsouza/zoxide). Currently, `nushell` does not appear to have an equivalent of a `PROMPT` variable or function. The lack of this not only means that custom prompts can't be used with `nushell`, but also makes it impossible for tools like `zoxide` to work with it (which relies on `zoxide add` being invoked upon every prompt).

**Describe the solution you'd like**
In order to implement https://github.com/ajeetdsouza/zoxide/issues/69, I'd need something like a hook that gets called upon every prompt. This is a very common feature that is also implemented in other shells:
- `PROMPT_COMMAND` in `bash`
- `--on-event fish_prompt` in `fish`
- `PS1` in all POSIX shells
- `precmd_functions` in `zsh`

On an unrelated note, it would be great if there was a hook that listens for changes in the current working directory. This, too, has been implemented in some shells:
- `--on-variable PWD` in `fish`
- `chpwd_functions` in `zsh`

**Describe alternatives you've considered**
- I could use a [`starship` custom command](https://starship.rs/config/#custom-commands) to call `zoxide add` without printing any output. This, of course, would only be available to `nushell` users that have enabled the `starship` feature.
- Since `zoxide` is also written in Rust, it should be possible to integrate it directly with `nushell`. Do let me know if that is an avenue you would like to explore.

**Additional context**
This feature also seems to have been discussed in https://github.com/nushell/nushell/issues/356, but was closed after `starship` was integrated with `nushell`.

**Comment by jonathandturner** [comment]
We did end up implementing configuring the internal prompt: https://github.com/nushell/nushell/pull/2064

It should be part of the 0.16.0 release.

If there are additional features you need, let us know.

**Comment by jonathandturner** [comment]
I'm going to go ahead and close this as it's now powerful enough you can write some pretty complex prompts. I recently also ran powerline with it.

If there is more that's needed, please re-open or create a new issue.

**Comment by bramswenson** [comment]
For new users or otherwise looking for something like `chpwd_functions` in order to load directory specific environment variables and scripts, see [`autoenv`](https://www.nushell.sh/book/commands/autoenv.html)
