### ISSUE TITLE
More/better escaping for passing $it to native commands

### ISSUE THREAD

**Issue by jzaefferer** [nushell/nushell#1699]
**Is your feature request related to a problem? Please describe.**

My question was: How do I pass the output of a command to an external command, with proper escaping?

I want to use the `code` external command to edit nu's config file. This almost works:
```shell
config --path | code $it
```
Unfortunately that path contains a space (on OSX, "Application Support"), so it actually opens two non-existing files (`~/Library/Application` and `Support/nu/config.toml`)

**Describe the solution you'd like**

According to [@jonathandturner on Discord](https://discordapp.com/channels/601130461678272522/614593951969574961/706184341944008714), there's some automatic escaping in place, but he thinks it needs more.

**Describe alternatives you've considered**

config --path | code "$it" makes it worse (code expected a string)

**Additional context**

Another way to reproduce this:
```shell
> config --path | ^cat $it
cat: ~/Library/Application: No such file or directory
cat: Support/nu/config.toml: No such file or directory
```

The motivation to edit the `nu/config.toml` originally came from wanting to edit aliases there, instead of using rather complicated inline pipelines using `config --get` etc.

**Comment by jonathandturner** [comment]
In case folks want to dig into this one, nu will do a bit of cleanup for external commands here: https://github.com/nushell/nushell/blob/master/crates/nu-cli/src/commands/classified/external.rs#L123-L160

It may need a bit more work so that things like the whitespace issue above is also handled

**Comment by jonathandturner** [comment]
I just tried the original example in macOS using master and it seems to be fixed now. Closing, but please reopen if you still see the issue.

**Comment by jzaefferer** [comment]
I can confirm this, too, now that I've managed to build from master
