### ISSUE TITLE
Command for opening files (and URLs) in their app

### ISSUE THREAD

**Issue by jzaefferer** [nushell/nushell#1700]
**Is your feature request related to a problem? Please describe.**
To open files in their associated apps, different OSes have different native commands: `open` on OSX, `start` on Windows, `xdg-open` on Linux. A nushell command to enscapulate those different commands would fill a gap and avoid using external commands.

**Describe the solution you'd like**

A command like `open` (on OSX), but in nushell. Since the name `open` is already taken, something else is needed. Maybe `start` like on Windows.

**Describe alternatives you've considered**
Alternative is to use the "local" native version (like `^open`).

**Additional context**
A rust crate that implements this: https://crates.io/crates/open this has fallbacks for other commands on linux, not only xdg-open

An apparently well maintained nodejs package for the equivalent function: https://github.com/sindresorhus/open interestingly/weirdly it ships with a copy of `xdg-open`

**Comment by jonathandturner** [comment]
This would make a really good plugin if wants to implement it. `start` seems like a pretty good name.

**Comment by 1ntEgr8** [comment]
I can try to work on this

**Comment by jonathandturner** [comment]
@1ntEgr8 please do!

**Comment by JosephTLyons** [comment]
Sweet.  I've been wanting this functionality in Nu for some time now.  I will say I'm biased and like `open` more, since I'm a Mac user and because it makes more sense to me to "open" a file over "starting" one, but I guess that could be my first alias.

**Comment by jzaefferer** [comment]
#1727 added the command as a plugin. It's missing documentation though.

Do plugin commands also get documented via docs/commands?

**Comment by jonathandturner** [comment]
@jzaefferer yeah, if they're party of the standard set. I'd like to make this one part of that set

**Comment by jonathandturner** [comment]
Added by @1ntEgr8
