### ISSUE TITLE
Can we speed up `du`?

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1702]
**Is your feature request related to a problem? Please describe.**
There are a few crates we could explore to speed up `du`.  Crates like `walkdir` and `jwalk` both are potentials here.

We could rewrite du to take advantage of either and benchmark it against the current implementation.  If we can find a faster one it'll not only speed up `du` but also the new `ls -d`.

cc @JosephTLyons who mentioned the poor performance on du for large directories.

**Describe the solution you'd like**
A more optimized walk and summing of the disk usage. It doesn't have to use any particular crate.

**Describe alternatives you've considered**
We could call out to external binaries, but we've generally focused on using the crates.

**Comment by fdncred** [comment]
`jwalk` seems to be super fast.

**Comment by JosephTLyons** [comment]
Had a short conversation with someone who uses `jwalk` here in their application and they mention it being much faster than `walkdir`

https://github.com/imsnif/diskonaut/issues/20#issuecomment-645749574

Seems like another vote for `jwalk`
