### ISSUE TITLE
Insert command fails on table with <value> column

### ISSUE THREAD

**Issue by nespera** [nushell/nushell#1703]
**Describe the bug**
Doing an insert on a table with a `<value>` column yields an error. Related to #1698 

**To Reproduce**
`ls | get name` gives output like this:
```
───┬──────────────
 # │ <value> 
───┼──────────────
 0 │ americas.csv 
 1 │ iso.csv 
───┴──────────────
```
Trying to add a column using `ls | get name | insert format "csv"` gives an error:
```
error: Unrecognized type in stream
- shell:1:35
1 | ls | get name | insert format "csv"
  |          ^^^^ original value
```
While giving the column a name first means it works:
`ls | get name | wrap | insert format "csv"`
```
───┬──────────────┬────────
 # │ Column       │ format 
───┼──────────────┼────────
 0 │ americas.csv │ csv 
 1 │ iso.csv      │ csv 
───┴──────────────┴────────
```

**Expected behavior**
The original command should behave something like the second example. It seems like these tables with a `<value>` column are not really true tables, which is surprising to a newcomer.

**Screenshots**

**Configuration (please complete the following information):**
 - OS: Linux Mint
 - Version 19.3
 - Optional features (if any)

**Comment by notryanb** [comment]
The [Working With Tables](https://www.nushell.sh/book/en/working_with_tables.html) section of the Nu Book states the following. 

- `pick` - creates a new table which includes only the columns specified
- `get` - returns the values inside the column specified

If you change your command to  `ls | pick name | insert format "csv"`, it looks like it works as intended.

I agree that this is surprising. The documentation on the site for [pick](https://www.nushell.sh/commands/pick.html) and [get](https://www.nushell.sh/commands/get.html) don't convey this difference like the book does. 

Another confusing thing in the documentation is `help insert` looks to differ from the website's definition of [insert](https://www.nushell.sh/commands/insert.html).

"Edit an **existing column** to have a new value." vs  "**adds a column** to any table output"

@nespera - Starting with some more concise documentation may help out here or is there an alternative you were thinking of?

**Comment by nespera** [comment]
@notryanb I'm not clear what the use case is for these lists of values, which would not be covered by a single column table. In most cases they act the same way until you hit a surprise like this one.

**Comment by thegedge** [comment]
I've labelled this as a bug, even though it's not technically a bug, but it is definitely confusing for someone new to nushell. Moving forward, we'll think more about this 🙂

**Comment by andrasio** [comment]
@nespera If you are working with a list of values like that, you might be looking for `append` or `prepend` so you'd do `ls | get name | append "some value"` or `ls | insert format "csv"`

In case you need a table with columns you can use `wrap "column name"` like you did. Difference is that commands like `insert`, `edit` operate on tables with columns.

**Comment by pwnorbitals** [comment]
> I've labelled this as a bug, even though it's not technically a bug, but it is definitely confusing for someone new to nushell. Moving forward, we'll think more about this 🙂

How would one proceed to fix that ? Would a documentation update be sufficient. or did you have any idea about fixing it in code ?
