### ISSUE TITLE
which command should handle aliases

### ISSUE THREAD

**Issue by jzaefferer** [nushell/nushell#1713]
**Is your feature request related to a problem? Please describe.**

This is unexpected:
```
❯ config --get startup
───┬────────────────────────────────────────
 # │ <value>
───┼────────────────────────────────────────
 0 │ alias myecho [msg] { echo Hello $msg }
 1 │ alias s [] { git status -sb }
───┴────────────────────────────────────────
nushell on 📙 1709-from-docs is 📦 v0.13.1 via 🦀 v1.43.0
❯ which s
─────────┬──────────────────────────
 arg     │ s
 path    │ nushell built-in command
 builtin │ Yes
─────────┴──────────────────────────
```

**Describe the solution you'd like**
I think `which` needs special handling for aliases. Maybe like this?
```
─────────┬──────────────────────────
 arg     │ s
 path    │ nushell alias: [] { git status -sb }
 builtin │ No
─────────┴──────────────────────────
```

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by hedonhermdev** [comment]
I would like to work on this issue.

**Comment by jonathandturner** [comment]
@hedonhermdev sounds good

**Comment by thegedge** [comment]
> I would like to work on this issue.

🙌 

I assigned it to you @hedonhermdev. Let us know if you need any guidance (here, or the `#developing` on Discord). If you're not able to finish it, just let me know so I can unassign you 🙂

**Comment by SanchithHegde** [comment]
@hedonhermdev In case you haven't started working on this yet, please let me know. I'd like to work on this.

**Comment by hedonhermdev** [comment]
Hey @SanchithHegde you can go ahead I am not working on this

**Comment by SanchithHegde** [comment]
@thegedge @jonathandturner This issue can be closed now that #2894 has been merged.

**Comment by jonathandturner** [comment]
@SanchithHegde thanks!

**Comment by jzaefferer** [comment]
Woohoo, nice work y'all 🥳
