### ISSUE TITLE
Ideas for Consistency

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#1714]
# Ideas for Consistency

In order to help newcomers get up to speed fast, it would be nice to somehow allow them to bring their knowledge with them and utilize it with nushell without spending a lot of time learning the nushell syntax.

For instance, there are some consistencies with SQL and .Net Linq.

| Definition | NuShell Syntax | SQL Syntax | .Net Linq Syntax | PowerShell |
|-|-|-|-|-|
||pick|select|Select|
||where|where|Where|
||first|top, limit|Take|
||last||Last|
||skip||Skip|
||keep||
||sort-by|order by|OrderBy|Sort-Object|
||lines|||
||=|=|=|-eq or =|
||=~|like|Contains, StartsWith|
||compact|||
||edit|||
||from|||ConvertFrom-*|
||to|||ConvertTo-*|
|||||

### Potential Solutions
- Create system level aliases that are essentially synonyms like `pick = select`. These aliases would get installed by default when a user installs nushell.
- Create code level commands that support different syntaxes like sql or dotnet or bash.
-

Disclaimer, this isn't meant to be a thorough comparison of every command in nushell, but rather, it's meant to get a point across and spur on conversation about this topic.

**Comment by thegedge** [comment]
I don't know if it needs to be built into nu itself, but we could recommend some configs / scripts which would set up the aliases to mimic these other environments.

Another option is an entry point in the nushell book for those coming from other places, similar to what we have for bash (see https://www.nushell.sh/book/en/coming_from_bash.html)

**Comment by jzaefferer** [comment]
A "coming from sql" chapter sounds pretty good! The table is a great start for that already.

The one thing that sticks out is `pick`. I wonder if that really should be renamed to `select`.

**Comment by quebin31** [comment]
> A "coming from sql" chapter sounds pretty good! The table is a great start for that already.
> 
> The one thing that sticks out is `pick`. I wonder if that really should be renamed to `select`.

`pick` is shorter, I think that this could be solved with bash-a-like alias, but nushell alias act in a different way, more like closures. If nu would have something like C macros (or bash-a-like aliases) that just replace text you will be able to add them to your startup-config, and indeed many people will have configs with everything set up and you will only download them and include them. What do you think @jonathandturner ?

**Comment by fdncred** [comment]
If you'd like to contribute to this, you can update the google sheet [here](https://docs.google.com/spreadsheets/d/1V8z0oZ6yIr8LFP2l8L9I0FDamrBa4dJhlYf4fvg_pnk/edit?usp=sharing)

**Comment by fdncred** [comment]
Closing now that tables have made it into book.
