### ISSUE TITLE
Aliases should support variable arguments or 'rest' arguments

### ISSUE THREAD

**Issue by kvrhdn** [nushell/nushell#1716]
**Is your feature request related to a problem? Please describe.**
I want to create an alias which will basically add a prefix to a command.

Use case: I use [aws-vault](https://github.com/99designs/aws-vault) to run commands with the correct AWS credentials:
```
aws-vault exec <my-profile> -- <some command>
```
I tried to create an alias like this:
```
alias kaws [cmd] { aws-vault exec <my-profile> -- $cmd }
```
But this will only capture one 'word'. For example, this fails:
```
kaws aws s3 ls
error: kaws unexpected s3
- shell:1:14
1 | kaws aws s3 ls
  |          ^^ unexpected argument (try kaws -h)
```

**Describe the solution you'd like**
I'd need a way to describe a parameter which captures multiple inputs.

Maybe something like:
```
alias kaws [...cmd] { aws-vault exec <my-profile> -- $cmd }
```

**Describe alternatives you've considered**
@jonathandturner proposed creating an alias with many arguements, with the idea that arguments that are not specified are left blank. But this doesn't work.
```
alias kaws [arg1 arg2 arg3 arg4 arg5] { .... }
```

```
kaws aws s3 ls
error: Alias failed to run
- shell:1:14
1 | kaws aws s3 ls
  | ^^^^ alias failed to run
- shell:1:14
1 | kaws aws s3 ls
  | ---- Type Error
(expected:
string,
actual:
nothing)
```

**Additional context**

**Comment by fdncred** [comment]
Here's another similar example.

Alias: 
` alias build-profile [arg1 arg2 arg3] { with-env [RUSTFLAGS '-C debuginfo=2 -C opt-level=0 -C link_args=/PROFILE'] { cargo build $arg1 $arg2 $arg3 }}`

Error:
```❯ build-profile
error: Alias failed to run
- shell:1:13
1 | build-profile
  | ^^^^^^^^^^^^^ alias failed to run
- shell:1:13
1 | build-profile
  | ------------- Type Error
(expected:
string,
actual:
nothing)```

**Comment by jonathandturner** [comment]
Can you try it again with https://github.com/nushell/nushell/pull/1722 and see if that helps the issue?  It might take a few tries, but this approach is what seemed to make sense initially

**Comment by fdncred** [comment]
@jonathandturner my alias appears to be working with this change.

**Comment by yashamon** [comment]
What is the the status of this? Passing variables to aliases no longer appears possible.
alias ls [$dir] = ls $dir 
is giving an error.

**Comment by fdncred** [comment]
Custom commands is what you want.

**Comment by yashamon** [comment]
Custom command  runs in a new scope so is not comparable.
eg. running on command line:
def mycd [dir] {cd $dir}
mycd foo
does nothing

One workaround solution would be to allow parameters to pass to the source
script invocation.

Then we could do something like (source mycd.nu) foo. (or some other
syntax) I think this does not exist at the moment or am I wrong?

I think in powershell you just  do:
 . mycd.ps1 foo
so sourcing with parameters is allowed.

But anyway this is a workaround it would be much better to have aliases
with parameters imo.

**Comment by fdncred** [comment]
You're right about `def` being scoped but if you try `def-env` it should work.
