### ISSUE TITLE
External command may be closing prematurely

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1719]
**Describe the bug**
I was poking around and tried this in the nushell root:

```
error: Unable to read from stdout.
- shell:1:49
1 | ls **/*.rs | git blame $it.name | save blames.txt
  |              ^^^ unable to read from stdout
```

The command runs for a while and then sometimes just dies with the error above. 

**To Reproduce**
1. in the nushell repo root
2. ls **/*.rs | git blame $it.name | save blames.txt 
3.  

**Expected behavior**
The external command shouldn't close before the pipeline is done processing.

**Configuration (please complete the following information):**
 - OS: Manjaro Linux, latest
 - Version: 0.13.1
 - Optional features (if any)

**Comment by jonathandturner** [comment]
@thegedge - does this sound related to some of the external optimizations you worked on, by chance?

**Comment by thegedge** [comment]
There's a good chance it could be. I'll take a quick look.

**Comment by thegedge** [comment]
Okay, I think I have a fix that I'll put out later today. We should poll the status whenever we get an `Err` from reading from stdout. If the command failed, it's likely that the pipe was closed, so we can ignore the `Err`.

**Comment by thegedge** [comment]
```
error: Unable to read from stdout (incomplete utf-8 byte sequence from index 8191)
- shell:1:54
1 | git ls-files | lines | git blame $it | save blames.txt
  |                        ^^^ unable to read from stdout
```

**Comment by jonathandturner** [comment]
So that's coming from MaybeTextCodec, but it's acting like either there's a bug in the codec or the pipe is getting closed before the full content is read.  One idea - if we're using something like a channel, I think once one side closes then reads don't succeed?  I'm just guessing what might cause us to not get the full buffer.

**Comment by thegedge** [comment]
Ah, I think I have the fix. I'll push it soon. Not sure how to test, so I'll just send out the fix.
