### ISSUE TITLE
Needed quotes for external command are removed

### ISSUE THREAD

**Issue by AminArria** [nushell/nushell#1730]
**Describe the bug**
I'm using an external command and giving an argument that needs its quotes preserved, but they are removed when generating the external call

**To Reproduce**
1. ^echo '#some-argument'

**Expected behavior**
Should print `#some-argument`

**Configuration (please complete the following information):**
 - OS: macOS Catalina 10.15.3
 - Version 0.13.0

When using `nu -l trace` the built command is

```
> built command "sh" "-c" "echo #woooo"
```

**Comment by thegedge** [comment]
Fixed by https://github.com/nushell/nushell/pull/2095
