### ISSUE TITLE
Add new Windows drive test

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1732]
**Is your feature request related to a problem? Please describe.**
Currently, you can use the automatic change directory to change drives in Nu. For example, `D:` will change to the D drive when you're in the CLI.  This works just like it would in other Windows shells, which is handy.

Unfortunately, this code is a little easy to break. To help with this, we should create some new tests that help test that we can change to a drive and get what we expect.

**Describe the solution you'd like**
Exploring using the Windows `subst` command to create a drive pointing at a temporary directory.  Then create a test that will use this `subst` step to change to a drive, make a change, and change back from the drive and check that the change was made.

**Describe alternatives you've considered**
If there are other ways to test changing drives, and the approaches work on CI, please feel free to use them.

**Comment by HiranmayaGundu** [comment]
Hey @jonathandturner ! I'd like to learn Rust, and wanted to do that by contributing here and picking this issue up. I've been exploring the codebase and my understanding is that you want a test case in `crates/nu-cli/tests/commands/cd.rs` ? And the test case should do the following:- 
```shell
pwd | config --set_into main_dir
mkdir test_fiolder 
subst Z: test_folder 
Z: 
echo "some text" > test_file.txt 
config --get main_dir | cd $it 
echo test_folder\test_file 
```
And then assert that it echos "some text"?

**Comment by pwnorbitals** [comment]
Now the PR is merged, is there any work left to close this issue ?
