### ISSUE TITLE
Add a `benchmark` command

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1733]
**Is your feature request related to a problem? Please describe.**
It's sometimes helpful to want to measure how long a block takes to execute.  It'd be nice to be able to measure this inside of Nu.

**Describe the solution you'd like**

Let's add a `benchmark` command that takes a block as input.  When run, `benchmark` will start timing, run the block to completion, and then report the time it took to run the block.

The `benchmark` command can return the time as a Duration value.

**Additional context**
You can read the `with-env` command source code at "crates/nu-cli/src/commands/with_env.rs" to learn how to run a block to completion.

**Comment by pag4k** [comment]
I would like to work on this.

**Comment by jonathandturner** [comment]
@pag4k great - I've assigned it to you

**Comment by quebin31** [comment]
Shouldn't be clearer and shorter to be `bench` instead of `benchmark`?

**Comment by thegedge** [comment]
> Shouldn't be clearer and shorter to be `bench` instead of `benchmark`?

I think `bench` is less clear when considering an ESL (english as a second language) perspective, so I'd rather stick to full words and people can always alias to shorter names, if they so desire 🙂

Another option is `time`, which is pretty common in shells (and there's a `/usr/bin/time` on a lot of UNIX-y platforms).

**Comment by quebin31** [comment]
> > Shouldn't be clearer and shorter to be `bench` instead of `benchmark`?
> 
> I think `bench` is less clear when considering an ESL (english as a second language) perspective, so I'd rather stick to full words and people can always alias to shorter names, if they so desire slightly_smiling_face
> 
> Another option is `time`, which is pretty common in shells (and there's a `/usr/bin/time` on a lot of UNIX-y platforms).

Yea, I guess `time` would be even better, but it's clearly open to consensus.

**Comment by JosephTLyons** [comment]
Closed by https://github.com/nushell/nushell/pull/2223
