### ISSUE TITLE
Add username/password to `fetch`

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1734]
**Is your feature request related to a problem? Please describe.**
Currently, the `post` command allows you to pass a username and password when posting to a server, which is great. Unfortunately, we don't have a way to do this yet with `fetch`.

**Describe the solution you'd like**
Extend `fetch` so that, like `post`, it can also also take in a username and password to authenticate against a server before it does a get request with the server.

**Describe alternatives you've considered**
You could imagine merging the `post` and `fetch` commands together. I see that as something we could think about in the future.

**Additional context**
You can look at the `post` command source in "crates/nu_plugin_post/src" to learn more about how post uses username and password.

**Comment by thegedge** [comment]
@jonathandturner Do we have a way to not save a command to history, or supply the password interactively? If not, that would be a good (separate) issue.

**Comment by he4d** [comment]
I would like to implement this!
