### ISSUE TITLE
A few follow-up items for `start`

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1735]
**A few follow-up items for `start`**

I tested `start` a bit in Manjaro and saw a few follow-up things we should do:

* running `start build.rs` appears to work, but also prints an error:

```
> start build.rs
start error: Failed to open file(s) with xdg-open. gnome-open, kde-open, and wslview
```

Unsure as to why it both works and print errors, so far.

* plugin can be added to the stable set of plugins, so that it's installed when `nu` is installed.  The main `Cargo.toml` lists all the plugins that are going to be built, and there's also a list of plugins that will be part of the "stable" list.  Adding it there and in the `[[bin]]` area below will help it get installed and loaded.

cc @1ntEgr8

**Comment by 1ntEgr8** [comment]
Ah, good catch. Forget to add a `return Ok(())` if the command succeeded. 

I'll add it to the stable list!
