### ISSUE TITLE
Nushell does not allow for negative numbers after flags

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#1737]
**Describe the bug**
While working on the `cal` command, I noticed Nushell wasn't parsing negative number correctly for me.  I assume Nushell either doesn't support negative numbers or that the parser for that is broken.

**To Reproduce**
1. Enter in a negative number for a command that has as flag that receives an integer from the command line.  
2. See that the output is non-negative

**Expected behavior**
I would expect Nushell to be able to interpret negative numbers.

**Screenshots**
<img width="762" alt="Screen Shot 2020-05-08 at 8 35 13 PM" src="https://user-images.githubusercontent.com/19867440/81459022-aee51b80-916b-11ea-9828-e18fd11db40a.png">

**Configuration (please complete the following information):**
 - OS: macOS 10.15.4
 - Version 0.13.1

**Comment by jonathandturner** [comment]
The issue looks like it's coming from https://github.com/nushell/nushell/blob/master/crates/nu-parser/src/parse.rs#L873

The flags parser is kicking in for things that are just negative numbers. We need to check that it's not a negative number before we start treating it like a flag

**Comment by thegedge** [comment]
@jonathandturner this is really interesting. Some commands allow `-<digit>` to be a flag (e.g., -0 can often mean "null character terminated"). If I have a command that has both a number/any shape for a positional arg, and the `-1` flag, some questions come to mind:

- How do we resolve that ambiguity?
- How can a user resolve that ambiguity? I know `--` often acts as a separator for positional args.

**Comment by onthebridgetonowhere** [comment]
This looks like an interesting first issue for me to dig more into nu and its codebase.  I have been poking a bit around to understand this calendar command, and then trying to go from there. 

What I tried
* cal -y --> OK
* cal -y 0 [ 1 2 3 2021] --> all positive numbers, returns an error shell |  ^^ unexpected argument (try cal -h)
* cal --full-year 0 [1, 2, 3 , 2020] --> all positive numbers, OK 
* cal --full-year -1 --> Error, Year is invalid, which makes sense. The code checking for this is [here](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/commands/cal.rs#L80).

What I do not understand is the difference between cal -y and cal --full-year and I guess how commands are parsed in general. One fails at negative numbers (as expected), and the other fails at all numbers. I probably need to learn the difference between a flag with - and one with --. 

I poked around in the parse.rs file, but I need more time to get an understanding of all the mechanism. Time to hit the documentation :-) 

As @jonathandturner mentioned, I probably need to start looking into the flags parser. Any hints where to poke? 
I tried some random print statements and what I see is that when I have the full --full-year, I hit this [line](https://github.com/nushell/nushell/blob/main/crates/nu-parser/src/parse.rs#L774) but when I use -y I do not hit anything around there, so need to figure out where this short flag is being parsed.

**Comment by jonathandturner** [comment]
@onthebridgetonowhere - 

I think if we're in a situation where it can be a flag, I think we have to assume it's a flag. This does mean we lose the ability to take a raw negative number as an argument to the command.

One possible solution, though we don't support it just yet, is to wrap the -1 in parens, so you'd type `(-1)` to differentiate it from a `-1` flag.

btw, for your examples, I'm not sure if `cal` supports passing in a list like that:

```
> cal --full-year 0 [1, 2, 3 , 2020]
error: cal unexpected [1, 2, 3 , 2020]
   ┌─ shell:21:19
   │
21 │ cal --full-year 0 [1, 2, 3 , 2020]
   │                   ^^^^^^^^^^^^^^^^ unexpected argument (try cal -h)
```

**Comment by JosephTLyons** [comment]
> What I do not understand is the difference between cal -y and cal --full-year ...

`cal -y` / `cal --year` adds in the year column:

```shell
───┬──────┬────────┬────────┬─────────┬───────────┬──────────┬────────┬──────────
 # │ year │ sunday │ monday │ tuesday │ wednesday │ thursday │ friday │ saturday 
───┼──────┼────────┼────────┼─────────┼───────────┼──────────┼────────┼──────────
 0 │ 2021 │        │      1 │       2 │         3 │        4 │      5 │        6 
 1 │ 2021 │      7 │      8 │       9 │        10 │       11 │     12 │       13 
 2 │ 2021 │     14 │     15 │      16 │        17 │       18 │     19 │       20 
 3 │ 2021 │     21 │     22 │      23 │        24 │       25 │     26 │       27 
 4 │ 2021 │     28 │     29 │      30 │        31 │          │        │          
───┴──────┴────────┴────────┴─────────┴───────────┴──────────┴────────┴──────────
```

`cal --full-year 2021` prints a full year calendar, instead of just the current month:

```shell
────┬────────┬────────┬─────────┬───────────┬──────────┬────────┬──────────
 #  │ sunday │ monday │ tuesday │ wednesday │ thursday │ friday │ saturday 
────┼────────┼────────┼─────────┼───────────┼──────────┼────────┼──────────
  0 │        │        │         │           │          │      1 │        2 
  1 │      3 │      4 │       5 │         6 │        7 │      8 │        9 
  2 │     10 │     11 │      12 │        13 │       14 │     15 │       16 
  3 │     17 │     18 │      19 │        20 │       21 │     22 │       23 
  4 │     24 │     25 │      26 │        27 │       28 │     29 │       30 
  5 │     31 │        │         │           │          │        │          
  6 │        │      1 │       2 │         3 │        4 │      5 │        6 
  7 │      7 │      8 │       9 │        10 │       11 │     12 │       13 
  8 │     14 │     15 │      16 │        17 │       18 │     19 │       20 
  9 │     21 │     22 │      23 │        24 │       25 │     26 │       27 
 10 │     28 │        │         │           │          │        │          
 11 │        │      1 │       2 │         3 │        4 │      5 │        6 
 12 │      7 │      8 │       9 │        10 │       11 │     12 │       13 
 13 │     14 │     15 │      16 │        17 │       18 │     19 │       20 
 14 │     21 │     22 │      23 │        24 │       25 │     26 │       27 
 15 │     28 │     29 │      30 │        31 │          │        │          
 16 │        │        │         │           │        1 │      2 │        3 
 17 │      4 │      5 │       6 │         7 │        8 │      9 │       10 
 18 │     11 │     12 │      13 │        14 │       15 │     16 │       17 
 19 │     18 │     19 │      20 │        21 │       22 │     23 │       24 
 20 │     25 │     26 │      27 │        28 │       29 │     30 │          
 21 │        │        │         │           │          │        │        1 
 22 │      2 │      3 │       4 │         5 │        6 │      7 │        8 
 23 │      9 │     10 │      11 │        12 │       13 │     14 │       15 
 24 │     16 │     17 │      18 │        19 │       20 │     21 │       22 
 25 │     23 │     24 │      25 │        26 │       27 │     28 │       29 
 26 │     30 │     31 │         │           │          │        │          
 27 │        │        │       1 │         2 │        3 │      4 │        5 
 28 │      6 │      7 │       8 │         9 │       10 │     11 │       12 
 29 │     13 │     14 │      15 │        16 │       17 │     18 │       19 
 30 │     20 │     21 │      22 │        23 │       24 │     25 │       26 
 31 │     27 │     28 │      29 │        30 │          │        │          
 32 │        │        │         │           │        1 │      2 │        3 
 33 │      4 │      5 │       6 │         7 │        8 │      9 │       10 
 34 │     11 │     12 │      13 │        14 │       15 │     16 │       17 
 35 │     18 │     19 │      20 │        21 │       22 │     23 │       24 
 36 │     25 │     26 │      27 │        28 │       29 │     30 │       31 
 37 │      1 │      2 │       3 │         4 │        5 │      6 │        7 
 38 │      8 │      9 │      10 │        11 │       12 │     13 │       14 
 39 │     15 │     16 │      17 │        18 │       19 │     20 │       21 
 40 │     22 │     23 │      24 │        25 │       26 │     27 │       28 
 41 │     29 │     30 │      31 │           │          │        │          
 42 │        │        │         │         1 │        2 │      3 │        4 
 43 │      5 │      6 │       7 │         8 │        9 │     10 │       11 
 44 │     12 │     13 │      14 │        15 │       16 │     17 │       18 
 45 │     19 │     20 │      21 │        22 │       23 │     24 │       25 
 46 │     26 │     27 │      28 │        29 │       30 │        │          
 47 │        │        │         │           │          │      1 │        2 
 48 │      3 │      4 │       5 │         6 │        7 │      8 │        9 
 49 │     10 │     11 │      12 │        13 │       14 │     15 │       16 
 50 │     17 │     18 │      19 │        20 │       21 │     22 │       23 
 51 │     24 │     25 │      26 │        27 │       28 │     29 │       30 
 52 │     31 │        │         │           │          │        │          
 53 │        │      1 │       2 │         3 │        4 │      5 │        6 
 54 │      7 │      8 │       9 │        10 │       11 │     12 │       13 
 55 │     14 │     15 │      16 │        17 │       18 │     19 │       20 
 56 │     21 │     22 │      23 │        24 │       25 │     26 │       27 
 57 │     28 │     29 │      30 │           │          │        │          
 58 │        │        │         │         1 │        2 │      3 │        4 
 59 │      5 │      6 │       7 │         8 │        9 │     10 │       11 
 60 │     12 │     13 │      14 │        15 │       16 │     17 │       18 
 61 │     19 │     20 │      21 │        22 │       23 │     24 │       25 
 62 │     26 │     27 │      28 │        29 │       30 │     31 │          
────┴────────┴────────┴─────────┴───────────┴──────────┴────────┴──────────
```

**Comment by kubouch** [comment]
This happens with `let` as well: #3139.

Just bundling the issues together since they're related.

I think the `(-1)` would work well. Can't think of better solution now. Perhaps the error message could be improved as well: When the parser notices the flag could be a negative number (integer or decimal or anything else that could be negative), it would suggest this workaround in the error text. I haven't looked into the parser code yet so I don't know how feasible this is.

**Comment by onthebridgetonowhere** [comment]
@jonathandturner thanks for the explanation and suggestion. We can probably try to have the `(-1)` paranthesis and see how that goes. Regarding the example with the list, yes, indeed it is not supported. It was more of exemplifying that other positive integers behave the same. 

@JosephTLyons thank you for clarifying the difference. My explanation was kinda poor; I was thinking more in the lines how are these two commands parsed differently, but I think I got it in the end! 

@kubouch Great idea with the error part. I like that. 

One question I have though, is, are commonly used numbers as flags? My very little experience so far was that most flags are one letters, combination of letters, or full words. I will take another look into the parser and see if I can get something going with the `( )` for numbers.

**Comment by thegedge** [comment]
@onthebridgetonowhere two examples that come to mind:

- Lots of flags that emit/consume many items default to each item on its own line, but can also separate them by null bytes. This is typically done with the `-0` flag
    - Examples: `xargs -0` for consuming, `rg` for emitting.
- `kill` and `pkill` can take the numerical codes for signals. For example, `kill -9 pid` sends a `SIGKILL` to `<pid>`.

The first example is relatively common. The latter is only going to be meaningful for any command that sends signals to processes.

**Comment by onthebridgetonowhere** [comment]
@thegedge thank you! silly me, I completely forgot about `kill -9`, I think it was too early in the morning. 

I'd be excited to try looking into supporting numbers with parentheses. It seems that people would like that solution, at least for now.
