### ISSUE TITLE
Support nested JSON objects

### ISSUE THREAD

**Issue by texastoland** [nushell/nushell#1750]
`open extensions.json` (VS Code application file) doesn't output usefully. Its structure is:

```json
[
    {
        "identifier": {
            "id": "vscode.bat"
        }
    },
    {
        "identifier": {
            "id": "ocamllabs.ocaml-platform",
            "uuid": "e3d4a4c9-859a-4367-9080-50dccbd4f1da"
        },
        "disabled": true
    }
]
```

It looks like:

```md
───┬───────────────
 # │ identifier 
───┼───────────────
 0 │ [row id] 
───┴───────────────
───┬───────────────┬──────────
 # │ identifier    │ disabled 
───┼───────────────┼──────────
 1 │ [row id uuid] │ Yes 
───┴───────────────┴──────────
```

## Proposed Solution

1. Nested headings (most readable):

```md
───┬─────────────────────────────────────────────────────────────────┬──────────
 # │ identifier                                                      │ disabled 
   ├──────────────────────────┬──────────────────────────────────────┤
   │ id                       │ uuid                                 │
───┼──────────────────────────┼──────────────────────────────────────┼──────────
 0 │ vscode.bat               |                                      |
 1 │ ocamllabs.ocaml-platform | e3d4a4c9-859a-4367-9080-50dccbd4f1da │ Yes
───┴──────────────────────────┴──────────────────────────────────────┴──────────
```

## Alternative Solutions

2. Nested tables (most compact):

```md
───┬─────────────────────────────────────────────┬──────────
 # │ identifier                                  │ disabled 
───┼──────┬──────────────────────────────────────┼──────────
 0 │ id   │ vscode.bat                           |
   ├──────┼──────────────────────────────────────┤
 1 │ id   | ocamllabs.ocaml-platform             │ Yes 
   │ uuid | e3d4a4c9-859a-4367-9080-50dccbd4f1da │
───┴──────┴──────────────────────────────────────┴──────────
```

3. JSON path headings:

```md
───┬──────────────────────────┬──────────────────────────────────────┬──────────
 # │ identifier.id            │ identifier.uuid                      │ disabled 
───┼──────────────────────────┼──────────────────────────────────────┼──────────
 0 │ vscode.bat               |                                      |
 1 │ ocamllabs.ocaml-platform | e3d4a4c9-859a-4367-9080-50dccbd4f1da │ Yes
───┴──────────────────────────┴──────────────────────────────────────┴──────────
```

**Comment by thegedge** [comment]
The one difficult with the nesting output is that we're taking a stream-based approach, which doesn't play nicely with this kind of output because we have to drain the entire stream to collect the set of fields.

Not saying that we shouldn't do this, just that it doesn't fit well with nushell's approach. I would probably make it an output style that is opt in 🙂

**Comment by thegedge** [comment]
Question: for the output you expect, did you intend to make it look like this:

```
───┬─────────────────────────────────────────────┬──────────
 # │ identifier                                  │ disabled 
───┼──────┬──────────────────────────────────────┼──────────
 0 │ id   │ bat                                  |
   ├──────┼──────────────────────────────────────┤──────────
 1 │ id   | ocamllabs.ocaml-platform             │ Yes 
   │ uuid | e3d4a4c9-859a-4367-9080-50dccbd4f1da │
───┴──────┴──────────────────────────────────────┴──────────
```

(note the extension of the line in the middle)

**Comment by nespera** [comment]
Maybe you could have a `flatten` command that would take these kind of nested table structures (coming from Json or elsewhere) and turn them into a table with `path` and `value` columns. Like this:
```
open extensions.json | flatten
───┬──────────────────────────┬──────────────────────────────────────
 # │ path                     │ value
───┼──────────────────────────┼──────────────────────────────────────
 0 │ 0.identifier.id          | vscode.bat                 
 1 │ 1.identifier.id          | ocamllabs.ocaml-platform 
 2 │ 1.identifier.uuid        | e3d4a4c9-859a-4367-9080-50dccbd4f1da 
 3 | 1.disabled               | true
───┴──────────────────────────┴──────────────────────────────────────
```
Not sure if that would satisfy the use case here.

**Comment by texastoland** [comment]
@thegedge I didn't intend to extend the line. I was just replacing `[row id uuid]` as literally as possible with a nested table. Whatever is most scannable works for me.

In retrospect I prefer the final option. It seems the most intuitive for querying without suffering from long paths as headings. The downside is it wouldn't be consistent with the way plain objects are dispayed.

**Comment by texastoland** [comment]
> The one difficult with the nesting output is that we're taking a stream-based approach, which doesn't play nicely with this kind of output because we have to drain the entire stream to collect the set of fields.

That makes sense. I don't know if it's possible but what if you consumed the first object then the first ten if it wasn't huge to determine headings. Any additional fields could be hidden kind of like `ls` withou `--full`.

**Comment by thegedge** [comment]
Yeah, I think the final option is better. The reason I asked was because it was hard to see from your expected output if disabled being "Yes" applied to both 0 and 1.

**Comment by kollstrom** [comment]
Is this going anywhere? Would we super useful 👌

**Comment by waldyrious** [comment]
Weird, is the stale bot misconfigured? The issue hasn't been close after 5 days as its message states. (Not that I think it should be closed — I think this would be a wonderful feature!)

**Comment by hustcer** [comment]
I need this feature badly, Thanks.

**Comment by texastoland** [comment]
There didn't seem to be contention about the proposed formatting or the need for a flag. Regarding streaming it seems feasible to do a fast first pass inferring recursive structure without processing or saving any data for the sake of table layout. Will anything about the new engine simplify implementation?

**Comment by fdncred** [comment]
With the latest main branch this is handled a bit better. Plus we have a `flatten` command as well.

```
╭───┬───────────────────┬──────────╮
│ # │    identifier     │ disabled │
├───┼───────────────────┼──────────┤
│ 0 │ {record 1 field}  │ ❎       │
│ 1 │ {record 2 fields} │ true     │
├───┼───────────────────┼──────────┤
│ # │    identifier     │ disabled │
╰───┴───────────────────┴──────────╯
```
and flattened here
```
╭───┬──────────────────────────┬──────────────────────────────────────┬──────────╮
│ # │            id            │                 uuid                 │ disabled │
├───┼──────────────────────────┼──────────────────────────────────────┼──────────┤
│ 0 │ vscode.bat               │ ❎                                   │ ❎       │
│ 1 │ ocamllabs.ocaml-platform │ e3d4a4c9-859a-4367-9080-50dccbd4f1da │ true     │
├───┼──────────────────────────┼──────────────────────────────────────┼──────────┤
│ # │            id            │                 uuid                 │ disabled │
╰───┴──────────────────────────┴──────────────────────────────────────┴──────────╯
```
with this in mind, I'm closing this issue. please re-open if you object.

**Comment by waldyrious** [comment]
@fdncred I think this use case would be a good fit for the `nested_table_2` feature of tabled (as mentioned [here](https://github.com/zhiburt/tabled/issues/198)). Perhaps this issue could be reopened, now that the functionality is at hand?

**Comment by texastoland** [comment]
That's gorgeous about time to try Nu again 😍

**Comment by texastoland** [comment]
1 year later this is my UX favorite feature 🥇
