### ISSUE TITLE
Copying a directory doesn't work properly

### ISSUE THREAD

**Issue by elichai** [nushell/nushell#1762]
**Describe the bug**
Can't copy directories properly, after doing all of these commands I think it copied most of the things but I still get an error.

**To Reproduce**
```sh
> cp -r old new
error: Error: No such file or directory (os error 2)
> mkdir new
> cp -r old new
error: Error: No such file or directory (os error 2)
> cp -r old/ new/
error: Error: No such file or directory (os error 2)
> cp -r old/* new/
error: Error: No such file or directory (os error 2)
```

**Expected behavior**
It should create a new directory and copy all the contents from the old to the new

**Configuration (please complete the following information):**
Arch Linux
nushell 0.13.0

**Comment by tannakartikey** [comment]
I'd like to fix this issue

**Comment by thegedge** [comment]
It's yours, @tannakartikey 🙂

**Comment by JosephTLyons** [comment]
Hey @tannakartikey, if you weren't able to find time to work on this issue, that is ok, we can remove you as the assignee, but if you're still interested in working on this, then that is ok too!

**Comment by tannakartikey** [comment]
Hey @JosephTLyons sorry for the delay

Somehow I missed @thegedge 's comment

**Comment by tannakartikey** [comment]
@elichai @thegedge I am not able to replicate this issue on v0.17.0 (Ubuntu 18.04)

**Comment by elichai** [comment]
I don't know what to say, but I can't reproduce this either.
(it has also been too long for me to remember what was exactly happening)

**Comment by thegedge** [comment]
It's been long enough that we may have unintentionally, and unexpectedly, fixed the underlying issue. I'll close it for now, but we can reopen if it happens again.

Thanks for reporting, @elichai, and thanks for exploring, @tannakartikey.

**Comment by Avi-D-coder** [comment]
I don't think this fully is fixed.
I don't have a minimal example, but on a source that contains a big dir (47G) `cp -r` is throwing an error, and leaving a partially copied dest.
