### ISSUE TITLE
insert doesn't behave as described in docs

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#1763]
**Describe the bug**
`insert` docs show examples where the column value that's being inserted is inserted for every row, but it appears to pop out the first item and insert the value only for that row.

**To Reproduce**
1. `ls | insert test test`

**Expected behavior**
All files in the directory would have the "test" column with a value of "test".

**Screenshots**

```
nushell/crates on  add-some-examples
❯ ls | first 3
───┬──────────┬──────┬───────┬─────────────
 # │ name     │ type │ size  │ modified
───┼──────────┼──────┼───────┼─────────────
 0 │ foo.json │ File │  52 B │ 23 mins ago
 1 │ nu-build │ Dir  │ 128 B │ 2 weeks ago
 2 │ nu-cli   │ Dir  │ 160 B │ 2 days ago
───┴──────────┴──────┴───────┴─────────────

nushell/crates on  add-some-examples
❯ ls | insert test test
──────────┬─────────────
 name     │ foo.json
 type     │ File
 size     │ 52 B
 modified │ 23 mins ago
 test     │ test
──────────┴─────────────
```

**Configuration (please complete the following information):**
 - OS: macOS
 - Version 10.15.4
 - `stable,test-bins`

**Comment by uberblah** [comment]
I am also observing this. Ubuntu 18.04. Installed fresh via `cargo install nu` on latest stable Rust toolchain.
