### ISSUE TITLE
A `sort-by` Flag to Perform Case-Insensitive Sorts On String Columns

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#1771]
**Is your feature request related to a problem? Please describe.**
Sometimes, sorting data case-sensitively is not what you want, sometimes, you want to sort case-insensitively.  I would love if Nushell had a way to do this.

**Describe  the solution you'd like**
I would like a flag on `sort-by`, something like `--insensitive` or whatever makes most sense, that would perform case-insensitive sorts on string columns.  The thing that is tricky about that if the user does a `sort-by` that includes non-string columns (I.E. `sort-by name type size`), the sort for that column should default to the normal sort (this is where I'm having trouble).

**Describe alternatives you've considered**
None

**Comment by filalex77** [comment]
I'll check what I can do.

**Comment by thegedge** [comment]
I'll assign it to you, @filalex77, so that people know you're looking into it. Let me know if you want to hand it off to someone else 🙂

**Comment by JosephTLyons** [comment]
I was working on this at one point.  I gave up because though I had it doing case insensitive sorts for columns with strings, as soon as I’d do a sort-by that had any non-string columns, it would blow up.  The way I coded it, I didn’t have a good way around it.  So yeah, make sure to try some sort-bys that include non-string columns to ensure it still sorts normally on those.

**Comment by JosephTLyons** [comment]
@filalex77, curious if you are still interested in doing this.  If so, by all means, if not, I could take another stab at it.

**Comment by filalex77** [comment]
@JosephTLyons Thanks for asking. I'll be busy for a week or so, so please feel free to try if you want to. I can review your PR :)

**Comment by JosephTLyons** [comment]
> @JosephTLyons Thanks for asking. I'll be busy for a week or so, so please feel free to try if you want to. I can review your PR :)

I definitely don’t want to take this from you if you are still wanting to do it, just was offering in the case that you decided to not do it.

**Comment by JosephTLyons** [comment]
Closed via: https://github.com/nushell/nushell/pull/2225
