### ISSUE TITLE
Listing C:\Windows reveals unexpected results

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#1785]
**Describe the bug**
When I do a `ls C:\Windows` I get a bunch of tables instead of just one.

**To Reproduce**
1. ls C:\Windows

**Expected behavior**
I expect every file and folder to be listed in a single table.

**Screenshots**
![2020-05-14_09-17-08](https://user-images.githubusercontent.com/343840/81945434-bc633100-95c3-11ea-94bd-af5718690fc2.png)

**Configuration (please complete the following information):**
 - OS: Windows 10
 - Version 1909 Build 18363.836
 - Optional features (if any): Using Windows Terminal

Built nushell from master.

**Comment by thegedge** [comment]
We currently break the display of a table every time the set of columns change, which explains what you're seeing.

It's odd that we don't have a size for everything. I'd rather it be empty than simply not present, like `type` and `modified`. For anyone interested in investigating, we can consider an empty value here:

https://github.com/nushell/nushell/blob/81ff598d6cbf476be8525d56833e3e660d8c1c98/crates/nu-cli/src/data/files.rs#L127-L158
