### ISSUE TITLE
Fresh install thinks I am in us-west-1

### ISSUE THREAD

**Issue by WyseNynja** [nushell/nushell#1788]
**Describe the bug**

I just installed with `brew install nushell`, ran `nu` and it says I'm in us-west-1. How does that detection work?

**To Reproduce**

```
Last login: Thu May 14 19:31:15 on ttys006
vacuum:~ bryan$ nu
Welcome to Nushell 0.13.0 (type 'help' for more info)
~ on ☁️  us-west-1 
❯ 
```

**Expected behavior**

I expected to see something like:

```
Last login: Thu May 14 19:31:15 on ttys006
vacuum:~ bryan$ nu
Welcome to Nushell 0.13.0 (type 'help' for more info)
~
❯ 
```

I got rid of all my dotfiles (~/.bashrc and such) just in case they were related, but that didn't change anything.

**Comment by WyseNynja** [comment]
It works as expected on my other user account on the same system (using the same brew installed version)

**Comment by 1ntEgr8** [comment]
i might be wrong, but i think it prints that when it detects a git repo

**Comment by thegedge** [comment]
That's a feature of `starship-prompt`. That looks like an AWS region, which is described here: https://starship.rs/config/#aws

> The aws module shows the current AWS region and profile. This is based on `AWS_REGION`, `AWS_DEFAULT_REGION`, and `AWS_PROFILE` env var with `~/.aws/config` file.

So likely there's something somewhere that's setting some/all of these env vars. Do you see any of them when running `env` on a fresh shell prompt?

**Comment by WyseNynja** [comment]
None of those env vars are set. I do have a ~/.aws/config that sets the default region to us-west-1, but I don't understand why that would interact with the prompt like this. Sounds like this is an issue for starship-prompt though

**Comment by WyseNynja** [comment]
Removing that config made the shell work as expected

**Comment by thegedge** [comment]
Yeah, starship-prompt out of the box has a bunch of things enabled (you can see from the link I posted that the AWS stuff isn't disabled by default).

`nushell`` currently sets up the starship configuration itself, but really it should be configurable by the user. I'm thinking we can create a separate issue for that and consider this one closed. What do you think?

**Comment by cig0** [comment]
Since Nu's shipped Starship honors Starship configuration file, it's actually easy to set the prompt the way you want, you only need to create a `~/.config/starship.toml` if there's none already:

```bash
# https://starship.rs/config/#prompt                                                                                                                                                                                                           

## Prompt                                                                                                                                                                                                                                      
prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    "package",
    "golang",
    "nodejs",
    "python",
    "rust",
    "golang",
    "aws",
    "env_var",
    "cmd_duration",
    "line_break",
    "jobs",
    "character",
]

## Packages configuration                                                                                                                                                                                                                      
#[package]                                                                                                                                                                                                                                     
#disabled = false                                                                                                                                                                                                                              

#[python]                                                                                                                                                                                                                                      
#disabled = false                                                                                                                                                                                                                              
#pyenv_version_name = true                                                                                                                                                                                                                     

[directory]
truncation_length = 8
```

HTH
