### ISSUE TITLE
Doesn't build on OpenBSD.

### ISSUE THREAD

**Issue by vext01** [nushell/nushell#1793]
Hi,

Saw nushell, looks neat, wanted to try it on my OpenBSD machine.

As noted [here](https://github.com/svartalf/rust-battery/issues/19) the `battery` crate doesn't build on OpenBSD and in turn, this stops nushell from building (see [here](https://github.com/svartalf/rust-battery/issues/19#issuecomment-629141535) for the compilation error).

Could `battery` be made an optional dep?

Thanks

**Comment by HiruNya** [comment]
`battery` seems to only be used in `nu_plugin_sys` so If the `battery` crate is the only problem then you should be able to compile by disabling the `sys` feature which is on by default.

**Comment by myfreeweb** [comment]
`sys` and `ps` plugins require support in https://github.com/heim-rs/heim too

`starship_prompt` also requires support in https://github.com/GuillaumeGomez/sysinfo (wow, dragging in a whole different system info lib >_<)

Also you might be interested in:

https://github.com/jonathandturner/rawkey/pull/4 for `binaryview` (which really should not be used, a terminal app linking to xlib is ridiculous >_<)

https://github.com/ArturKovacs/trash/pull/15 for `trash-support`

**Comment by vext01** [comment]
So, the following works:
```
 cargo install --no-default-features nu
```

Is there a way to disable the battery feature automatically on OpenBSD? Like a `./configure` check would do in auto-tools?

**Comment by thegedge** [comment]
> Is there a way to disable the battery feature automatically on OpenBSD? Like a ./configure check would do in auto-tools?

Nothing at the moment, but this shouldn't be too difficult to either a) add to the `battery` crate, or b) disable in nushell until someone does (1) 🙂
