### ISSUE TITLE
Allow `cd` to read from pipeline

### ISSUE THREAD

**Issue by danielakhterov** [nushell/nushell#1794]
**Is your feature request related to a problem? Please describe.**
I'd like to `alias cg [] { ghq list --full-path  | sort | fzf | cd }` which would use fzf to fuzzy search through a list of git repositories. However this currently isn't possible because `cd` does not read from pipe; at least from the looks of it.

**Describe the solution you'd like**
I'd like for `cd` to be able to take the first row of a pipe and cd to there, or perhaps if there are multiple rows it will create N number of shells in all those directories.

**Describe alternatives you've considered**
Have tried to make the above a sub expression/command, but I failed to do so. The following doesn't work, but that might be my lack of understanding of how Nu works.
```bash
cd $(echo "/home")
```

Edit:
Also tried to use `xargs` today, but that didn't work either:
```bash
echo "/home" | xargs cd
```

**Comment by thegedge** [comment]
I think this makes sense. A few points:

- It may be worth it to fail if there's more than one row in the pipeline.
- If we don't want to fail on more than one row, we should make sure the docs/help emphasizes that it will only take the first row.
- Need to decide what an empty pipeline does. `cd` in a lot of shells will go to the home directory when given no directory. Do we want that behaviour, or do we want it to do nothing?

**Comment by Yam76** [comment]
Wouldn't this behavior be better for `enter`?

**Comment by danielakhterov** [comment]
@Yam76 You're right. I guess piping a list of directories to cd shouldn't create N number of shells, and instead only use the first row. However, piping a list of directories to enter probably should create an N number of shells. Neither of which work currently though.

**Comment by aeosynth** [comment]
cd does work, I use this to jump to a subdirectory with `fd`:

    alias j [x] { fd -1td $x | trim | cd $it }

note the `trim`, and `$it`. your 2nd example works:

    echo "/home" | cd $it

your first example might work with `trim`, as external commands might add a newline. using external echo fails:

    ^echo "/home" | cd $it

because this turns into `cd /home/\n`; use `debug` to see what's getting passed around.

**Comment by Yam76** [comment]
I don't think `$it` is explicitly explained in the Book. Maybe it should get its own section?

**Comment by danielakhterov** [comment]
Thank you, that does work. `ghq list --full-path | sort | fzf | trim | cd $it` is exactly what I wanted.
The `$it` operator was used in the book, but from what I remember it didn't go in depth as to what it means or does. Also, did not realize the `\n` would prevent `cd` from jumping to the directory; although that does make sense looking in retrospect. I guess I'm a little confused as to when to use `$it` vs when to use a `|`.

Also, not sure if I should start a new issue for this, but is there currently any way to bind `Ctrl+g` to a command? Perhaps I'm looking at it wrong and it should simply be an alias to an escape sequence, but I'm trying to mimic the functionality of the fish-ghq plugin for Fish shell. This in particular https://github.com/decors/fish-ghq/blob/master/conf.d/ghq_key_bindings.fish

**Comment by aeosynth** [comment]
> but is there currently any way to bind Ctrl+g to a command?

not currently: https://github.com/nushell/nushell/issues/1536
