### ISSUE TITLE
env vars seem to be broken

### ISSUE THREAD

**Issue by elichai** [nushell/nushell#1795]
**Describe the bug**
when I try to set an env var I get weird results from binaries

**To Reproduce**
This command works fine:
`cargo test --features=test-bins`
but when I do this:
`RUST_BACKTRACE=1 cargo test --features=test-bins`
I get:
```
error: Found argument '--features' which wasn't expected, or isn't valid in this context
        Did you mean to put '--features' after the subcommand 'test'?

USAGE:
    cargo [OPTIONS] [SUBCOMMAND]

For more information try --help
```
**Expected behavior**
It should just work (and obv it works in bash/sh)

**Comment by nlbrown2** [comment]
I'm new, but I think the syntax for specifying environment variables with the `with-env` command. When I run `with-env [RUST_BACKTRACE "1"] {cargo test --features=test-bins}` I don't get the parsing error.

**Comment by jonathandturner** [comment]
Both styles should work. It's possible the "shorthand" form needs more thorough testing.

**Comment by elichai** [comment]
> When I run `with-env [RUST_BACKTRACE "1"] {cargo test --features=test-bins}` I don't get the parsing error.

FYI, How do I pass multiple variables to `with-env`?
