### ISSUE TITLE
nushell breaks gdb workflow because of the lack of buildin `exec` command

### ISSUE THREAD

**Issue by LesleyLai** [nushell/nushell#1799]
**Describe the bug**
Hi, I just started to use nushell and it seems very promising. However, I noticed a problem when I try to debug a piece of C++ code, and gdb stop working (in the terminal and in IDEs). Apparently `gdb run` depends on the shell builtin `exec` command, and nu does not support that command.

I am not sure what should be the solution to this problem. I tried to define an alias
``` nu
alias exec [c] { "echo 'exec $c'" | bash }
```
but it was not working.

**To Reproduce**
1. `chsh` to nu
2. Run `gdb`
3. `gdb run`

**Expected behavior**
`gdb run` works fine.

**Screenshots**
![Screenshot_2020-05-15_18-05-07](https://user-images.githubusercontent.com/8359374/82105091-b742d680-96d6-11ea-8186-47e90ee22e0a.png)

**Configuration (please complete the following information):**
 - OS: Pop!_OS
 - Version 20.04
 - gdb 9.1

**Comment by thegedge** [comment]
Since nushell is cross platform, and Windows doesn't have `exec` capabilities (cygwin did some funky things to emulate it), we didn't put any effort into adding an exec out of the box.

That doesn't mean it wouldn't be possible to add `exec` on platforms that support it though 🙂

**Comment by LesleyLai** [comment]
Yeah. I was shocked that gdb invokes the default shell rather than calls `exec` directly.

**Comment by almindor** [comment]
This should be added, `exec` is NOT a command/program like `ls` and is supposed to be a part of any shell on `*NIX` according to the `POSIX` standard.

`man exec` says (shortened):

```
PROLOG
       This manual page is part of the POSIX Programmer's Manual.  The Linux implementa‐
       tion of this interface may differ (consult the corresponding  Linux  manual  page
       for details of Linux behavior), or the interface may not be implemented on Linux.

NAME
       exec — execute commands and open, close, or copy file descriptors

SYNOPSIS
       exec [command [argument...]]

DESCRIPTION
       The  exec utility shall open, close, and/or copy file descriptors as specified by
       any redirections as part of the command.

       If exec is specified without command or arguments, and any file descriptors  with
       numbers  greater  than 2 are opened with associated redirection statements, it is
       unspecified whether those file descriptors remain open when the shell invokes an‐
       other  utility.   Scripts  concerned that child shells could misuse open file de‐
       scriptors can always close them explicitly, as shown in one of the following  ex‐
       amples.

       If  exec is specified with command, it shall replace the shell with command with‐
       out creating a new process. If arguments are specified, they shall  be  arguments
       to command.  Redirection affects the current shell execution environment.

IEEE/The Open Group                       2013                                  EXEC(1P)
```

**Comment by thegedge** [comment]
This should be fixed by https://github.com/nushell/nushell/pull/2495. Reopen if you're still having problems.
