### ISSUE TITLE
Current blockers

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#180]
# 1. Plugins/commands cannot call each other

Currently, to be able to evaluate a block, we need to be able to invoke the commands in the block. There's currently no way to do this for a couple reasons:

- the command registry is not given to plugins
- commands can not invoke other commands

# 2. (DONE) Spans need filename information

Currently spans do not track the file they're coming from. When we support tracking that a value was loaded from a certain file, we'll need to track that location information in the span.

CC @wycats

**Comment by jonathandturner** [comment]
2 is now done

**Comment by wycats** [comment]
@jonathandturner Can we close this?

**Comment by jonathandturner** [comment]
@wycats we'll need to fix 1 when we do scripts and more complex pipelines, but it's not an immediate blocker

**Comment by hone** [comment]
@wycats @jonathandturner I'm potentially interested in helping with this if there's an easy starting point.
