### ISSUE TITLE
A Way to Bring Out Nested Tables Into Main Tables

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#1800]
**Is your feature request related to a problem? Please describe.**
When working with nested data, sometimes you run into situations like this:

<img width="482" alt="Screen Shot 2020-05-15 at 10 17 00 PM" src="https://user-images.githubusercontent.com/19867440/82108075-1a923000-96fa-11ea-93d1-da1fb1f0ebee.png">

To get the the inner data of `pets`, you need to do this:

<img width="562" alt="Screen Shot 2020-05-15 at 10 17 10 PM" src="https://user-images.githubusercontent.com/19867440/82108088-2d0c6980-96fa-11ea-8caf-c12210e4f189.png">

This works, but if you have a very large data set and you end up performing some sorting and filtering on the inner data, it becomes hard to see how it relates to the outer data without sorting and filtering it the same way and then matching the indices between the two tables.

I would love a command or flag (I don't know how this would work) that would bring out the nested structure and replace the column that holds it with those columns.  Ignoring the command here (since I just changed the data structure), the result would be:

<img width="490" alt="Screen Shot 2020-05-15 at 10 17 48 PM" src="https://user-images.githubusercontent.com/19867440/82108124-6e9d1480-96fa-11ea-9678-020e76343b30.png">

I have no idea what the syntax could look like, but something like: `open pets.json | expand pets` or `open pets.json --expand pets`.
**Describe the solution you'd like**
A command or flag that would allow you to "expand" nested structures

**Describe alternatives you've considered**
None

**Comment by JosephTLyons** [comment]
Or maybe `expand` is a better name

**Comment by jonathandturner** [comment]
cc @andrasio who was doing a lot of exploring of possible solutions for issues like this

**Comment by JosephTLyons** [comment]
I suppose that if this sort of idea was considered, there would need to be an inverse function to take data within some columns and push it into a nested structure somehow.  If your goal is to be able to pull nested tables out directly into a table to manipulate it, you maybe want to be able to put it back to its original structure.  I can see situations where a user would be bringing some nested tables out, sorting / filtering, then putting putting things back to how they were.

**Comment by JosephTLyons** [comment]
I believe `flatten` achieves this?
