### ISSUE TITLE
`from tsv` errors but `from-tsv` works fine

### ISSUE THREAD

**Issue by dmnd** [nushell/nushell#1803]
**Describe the bug**
`from tsv` errors but `from-tsv` works fine.

I guess it's something to do with `usr/bin/from`? Is my system weird in some way?

**To Reproduce**
```
❯ ^echo "a\\tb\\n1\\t2\\n3\\t4\\n" > /tmp/test
~
❯ open /tmp/test | from tsv
from: can't read /var/mail/tsv
~
❯ open /tmp/test | from-tsv
───┬───┬───
 # │ a │ b
───┼───┼───
 0 │ 1 │ 2
 1 │ 3 │ 4
───┴───┴───
~
```
**Expected behavior**
```
❯ ^echo "a\\tb\\n1\\t2\\n3\\t4\\n" > /tmp/test
~
❯ open /tmp/test | from tsv
───┬───┬───
 # │ a │ b
───┼───┼───
 0 │ 1 │ 2
 1 │ 3 │ 4
───┴───┴───
~
❯ open /tmp/test | from-tsv
───┬───┬───
 # │ a │ b
───┼───┼───
 0 │ 1 │ 2
 1 │ 3 │ 4
───┴───┴───
~
```
**Configuration (please complete the following information):**
 - OS: MacOS Catalina 
 - Version: 10.15.4 (19E287)

**Comment by jonathandturner** [comment]
For "from tsv", you'll need to be on version 0.14.0 or later. You can check your version with the `version` command.

**Comment by dmnd** [comment]
Oops, I'm on 0.13, and somehow your issue template made me think of OS version but not nushell version. Sorry for the stupid issue! 🤦

**Comment by jonathandturner** [comment]
No worries and thanks for the reminder to clarify the issue template
