### ISSUE TITLE
Invocation doesn't properly return errors

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1810]
**Describe the bug**
Argument invocation is swallowing errors it should bubble up to the user.

**To Reproduce**
1. If there isn't a `foo` command available, it should error to call it in an invocation
2. Eg) `echo $(foo)`
3. 

**Expected behavior**
Errors like the above should be show to the user.
**Configuration (please complete the following information):**
 - OS (e.g. Windows): Linux
 - Nu version (you can use the `version` command to find out): 0.14.1
 - Optional features (if any):

**Comment by cjpearce** [comment]
I'd really like to give this a go if it's up for grabs. It would be my first contribution to the project so I may take some extra time to find my way around.

**Comment by thegedge** [comment]
No worries, @cjpearce, it's yours! Join us on the discord channel in `#developing` if you have any questions or want some guidance 🙂

I'll help get you started. You'll want to focus around here: https://github.com/nushell/nushell/blob/5f1136dcb07ef1c1a6adabe5ea332dcfd40a1301/crates/nu-cli/src/evaluate/evaluator.rs#L186-L206

**Comment by cjpearce** [comment]
Thanks! I've put something together that seems to work, but I might need some advice on the approach.
