### ISSUE TITLE
Explore using the new `dirs` crates

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1817]
**Is your feature request related to a problem? Please describe.**
Recently announced are new crates for doing `dirs` functionality (the original crate was abandoned)

https://www.reddit.com/r/rust/comments/gli4pc/directoriesnext_dirsnext_the_new_home_for/

**Describe the solution you'd like**
We should take a look at them and see if they fit the needs Nu has. If so, it may make sense to go ahead and move to them.

**Describe alternatives you've considered**
We can keep what we have, as it seems to work well enough.

**Comment by coolshaurya** [comment]
The new crates are drop-in replacements for the old ones and will be maintained unlike the original. Therefore I think nu should switch to the new crates.

**Comment by pwnorbitals** [comment]
I’d advocate for switching. 

> We can keep what we have, as it seems to work well enough.
Well I can see it has issues of its own too (#893)

**Comment by brightly-salty** [comment]
I would also advocate switching; there is a RustSec advisory out for dirs, which will cause `cargo audit` to throw a warning on nushell or a dependent crate (https://rustsec.org/advisories/RUSTSEC-2020-0053).

I would be willing to implement this and submit a PR if it would be accepted.
