### ISSUE TITLE
Need to document `no_auto_pivot`

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1826]
**Is your feature request related to a problem? Please describe.**
With https://github.com/nushell/nushell/pull/1791, we now allow disabling the auto-rotation of a single row.  We should document this in the list of config flags in the book.

**Describe the solution you'd like**
Document it in the book :)

**Comment by thegedge** [comment]
- [x] Book
- [ ] Nushell

**Comment by jzaefferer** [comment]
@thegedge since you added that checklist - where in 'Nushell' should this get documented?

`help config` doesn't have a list of available config variables - maybe that's the part that's missing?

**Comment by thegedge** [comment]
I was thinking here: https://github.com/nushell/nushell/blob/ae8c8649345b85c05fe69c210fedbc1f7417ce76/docs/commands/config.md

Looks like it's already done!
