### ISSUE TITLE
Expose `max_history_size` from rustyline

### ISSUE THREAD

**Issue by lightclient** [nushell/nushell#1829]
It would be helpful to allow the history size to be configured by the user. I believe the most sensible solution is to expose it via a config variable (like `edit_mode`). Alternatively, it could be exposed via an env variable. I am happy to file a PR resolving this if we can come to agreement on an implementation.

**Comment by thegedge** [comment]
I can assign you to this issue, @lightclient, if you're interested in working on it?

**Comment by lightclient** [comment]
Yep, happy to handle it. Do you think it is best to expose via the `config.toml` or would an env variable be preferable?

**Comment by thegedge** [comment]
Great question. We lean more towards `config.toml` values for configuring nushell behaviours 🙂 

Assigning to you!
