### ISSUE TITLE
Tilde not expanding in $nu.path

### ISSUE THREAD

**Issue by lightclient** [nushell/nushell#1834]
I have a `.bin` folder in my `$HOME` directory that has several small scripts. Although `~/.bin` is in my path, they are not found when I try to execute them. If I manually replace `~` with the full path, they work as expected.

```console
/home/lightclient> cat ~/.bin/testy
#!/bin/sh

echo "test complete"
/home/lightclient> echo $nu.path
_____________________
 0 _ /bin
 1 _ /usr/bin
 2 _ /usr/sbin
 3 _ ~/.bin
 4 _ /usr/local/sbin
 5 _ /usr/local/bin
_____________________
/home/lightclient> testy
error: Command not found
- shell:1:5
1 | testy
  | ^^^^^ command not found
/home/lightclient> bash
[lightclient@laptop ~]$ echo $PATH
/bin:/usr/bin:/usr/sbin:~/.bin:/usr/local/sbin:/usr/local/bin
[lightclient@laptop ~]$ testy
test complete
[lightclient@laptop ~]$ exit
exit
```

**Configuration (please complete the following information):**
 - OS: Arch
 - Nu version: `0.14.0 `
 - Optional features (if any): none

I could probably put together a PR sometime this week to fix this, unless someone wants to get to it earlier. I am guessing it won't be terribly involved.

**Comment by lightclient** [comment]
For color: https://github.com/fish-shell/fish-shell/issues/2310

**Comment by thegedge** [comment]
zsh doesn't seem to expand tilde in home either.

`~` is a legitimate directory name, so it could be that someone actually wants `~/.bin` (local to the current path) to be part of `PATH`. If we expand `~`, it's impossible to do that. I don't like making things impossible, but I think it's also _highly_ unlikely that someone is sprinkling `~/.bin` folders around their filesystem.

I wonder what others think?

**Comment by lightclient** [comment]
@thegedge you're right, it does appear that `~` is not expanded by `zsh`'s `PATH` search:

```console
> PATH="~/.bin"
> echo $PATH
~/.bin
> which testy
testy not found
```

However, it does expand `~`s when parsing a line:

```console
laptop% PATH=~/test
laptop% echo $PATH
/home/lightclient/test
```

Therefore, it seems reasonable to expand elements in the `path` table on startup.

**Comment by ryanpcmcquen** [comment]
It doesn't seem that `$HOME` expands either, when setting it for the path. Do all path values need to be absolute?

**Comment by mightyiam** [comment]
> It doesn't seem that `$HOME` expands either, when setting it for the path. Do all path values need to be absolute?

That's a good question, isn't it...

**Comment by crodjer** [comment]
I am also facing the same. Because of this, I am unable to generate a portable `nu` shell configuration - which works for any username.

**Comment by jonathandturner** [comment]
I suspect this is still true until we fully move to the new path crate. Marking as not-stale. cc @kubouch

**Comment by kubouch** [comment]
@jonathandturner I'll put it on my list to investigate. Please throw at me similar issues if you find more.

**Comment by kubouch** [comment]
Sounds similar similar to #3605

**Comment by mightyiam** [comment]
Thank you, @kubouch .
