### ISSUE TITLE
Aliases need better type inference

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1835]
**Describe the bug**
Trying to create an alias that uses a value that isn't parsed with 'any' token parser:

```
alias set-env [name value] { echo $nu.env | insert $name $value | config --set_into env }
```

If you try to run `set-env`, it will fail because you can't pass in a column-path as the first argument.

**To Reproduce**
1. Run the above
2. Try to call `set-env`

**Expected behavior**
When we create an alias, we need to infer the types of the parameters. Without that, we can't successfully parse the arguments as expected.

**Comment by LhKipp** [comment]
```shell
/home/leo/repos/nushell/nushell(main)> alias -i set-env [name value] {config set $name $value}
/home/leo/repos/nushell/nushell(main)> set-env HI_THERE 1
───┬──────────
 # │ HI_THERE 
───┼──────────
 0 │        1 
───┴──────────
/home/leo/repos/nushell/nushell(main)> config get HI_THERE
1
/home/leo/repos/nushell/nushell(main)> version
───┬─────────┬──────────────────────────────────────────┬────────────────
 # │ version │               commit_hash                │    features    
───┼─────────┼──────────────────────────────────────────┼────────────────
 0 │ 0.21.1  │ 4e17292a12a7913c8cd308e81af4f9c9fcb3f4fc │ [table 1 rows] 
───┴─────────┴──────────────────────────────────────────┴────────────────
```

May it be that this issue is deprecated. The config command changed and there is better type inference. Can this be closed?
