### ISSUE TITLE
Tables not displaying properly in tmux

### ISSUE THREAD

**Issue by lightclient** [nushell/nushell#1839]
**Expected:**
```console
/home/lightclient/test/> ls
───┬──────┬──────┬──────┬───────────
 # │ name │ type │ size │ modified
───┼──────┼──────┼──────┼───────────
 0 │ a    │ File │  0 B │ 1 min ago
 1 │ b    │ File │  0 B │ 1 min ago
 2 │ c    │ File │  0 B │ 1 min ago
───┴──────┴──────┴──────┴───────────
```

**Actual:**
```console
/home/lightclient/test> ls
______________________________________
 # _ name _ type _ size _ modified
______________________________________
 0 _ a    _ File _  0 B _ 33 secs ago
 1 _ b    _ File _  0 B _ 32 secs ago
 2 _ c    _ File _  0 B _ 31 secs ago
______________________________________
```

**Configuration:**
 - OS: Arch (tmux 2.9a, alacritty 0.3.3)
 - Nu version: 0.14.0
 - Optional features (if any): none

Note:
```console
/home/lightclient/> cat .tmux.conf
set -g default-terminal "tmux-256color"
```

**Comment by thegedge** [comment]
Not experiencing the same issue, and nowhere in our codebase or `prettytable` is there a separator set as `_` (at least, I couldn't find one). Will need some further investigation.

**Comment by jonathandturner** [comment]
@lightclient - would you mind adding a screenshot of what you're seeing? Just so we have something to compare against visually

**Comment by lightclient** [comment]
@jonathandturner no problem, please see below.
![2020-05-18-1589830820_screenshot_2560x1440](https://user-images.githubusercontent.com/14004106/82252972-4cc7ab80-990d-11ea-84b6-5dfd2d96971b.jpg)

**Comment by fdncred** [comment]
![image](https://user-images.githubusercontent.com/343840/82255181-d2e9ef00-9919-11ea-808c-f189ff2fe4ec.png)

Version 3.0a on WSL looks ok.
