### ISSUE TITLE
du doesn't respond to ctrl-c on OpenBSD

### ISSUE THREAD

**Issue by vext01** [nushell/nushell#1844]
I ran a long `du` task by accident, and expected to be able to kill it with ctrl-c:

```
/home/edd> du .
^C^C^C^C^C^C
```

This is on 0.14.0 on OpenBSD with no features enabled.

Nu can be killed with `ctrl-z` followed by `kill %`, but it's not ideal.

**Comment by thegedge** [comment]
Yeah, we have a few commands that probably don't properly stream results, checking for Ctrl-C. `du` should be easy though 🙂

**Comment by JosephTLyons** [comment]
I pretty much have this working, but I may need a bit more guidance before it is finished up.  Unless anyone objects, I could officially take this issue.
