### ISSUE TITLE
Provide the reverse of `lines`.

### ISSUE THREAD

**Issue by bwinton** [nushell/nushell#1847]
**Describe the bug**
I can fairly easily go from the output of a command (like `git log`) to a table, but it's surprisingly hard to go back from a table to the original string.

**To Reproduce**
1. try to get `git log --graph` to output the first 30 commits.

**Expected behavior**
I thought it would be fairly simple, but couldn't figure out how.

**Configuration (please complete the following information):**
 - MacOS
 - 0.14.0
 - stable features.

It seems like, due to the internal pager perhaps, `git log --graph | head 30` doesn't work. So I tried `git log --graph | first 30`, but that gives me a table, and I can't for the life of me figure out how to turn that back into a string for the console. `textview` only shows the first line (and for some reason gets rid of the embedded newline in my custom git format). `to md` is close, but inserts an extra newline between each row. There's no `println!` that I could use with `each`… I'm stumped.

**Comment by bwinton** [comment]
(Oh, and for the record, the full command I'm trying to use is:
`git -c color.ui=always log --graph --abbrev-commit --all --decorate "--format=format:%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)" | first 30`
)

**Comment by jonathandturner** [comment]
I'd definitely like to see this.  I agree it's a bit odd that it's hard to go from rows back to a string.  Maybe we need a `to string` command.

**Comment by bwinton** [comment]
This might be scope creep, but it may also be interesting to have `to txt` take the separator as a flag (defaulting to `\n`), so you can smush everything on one line if that's what you wanted to do…

**Comment by steven807** [comment]
I spent quite a while today trying to figure out how to take `ls | get name` to output a single line.  (For 30+ years, I've had `l` alias to `echo *` in bash/csh/etc -- I like the compact output).  It finally occurred to me to just say `alias l [] = { ^echo * }`.
I'd love to stay within `nu` and just say `ls | get name | to txt ' '` (per @bwinton's above suggestion)

**Comment by andrasio** [comment]
Does that `format` or interpolation work for you?

Try?:

```
git -c color.ui=always log --graph --abbrev-commit --all --decorate "--format=format:%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n %C(white)%s%C(reset) %C(dim white)- %an%C(reset)" | lines | first 30 | format "{$it}"
```

or string interpolation

```
git -c color.ui=always log --graph --abbrev-commit --all --decorate "--format=format:%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n %C(white)%s%C(reset) %C(dim white)- %an%C(reset)" | lines | first 30 | echo `{{$it}}`
```

**Comment by andrasio** [comment]
@steven807 `ls | format "{name}"` / `ls | format "{$it.name}"` / `ls | echo `{{$it.name}}`` /

**Comment by steven807** [comment]
> @steven807 `ls | format "{name}"` / `ls | format "{$it.name}"`

These don't seem to put the output on a single line for me (version `0.15.0`).  It seems to be exactly the same as `ls | get name`, i.e. a table with one file per line.

**Comment by bwinton** [comment]
Doesn't seem like they do.

> Try?:
> ```
> [...] | format "{$it}"
> ```

That returns a table of 30 blank lines…

> or string interpolation
> ```
> [...] | echo `{{$it}}`
> ```

That returns "\`{{$it}}`".

¯\\\_(ツ)\_/¯

**Comment by coolshaurya** [comment]
You can do this now with #2289. the command now will be - `your_pipeline | str collect $(char newline)`.

**Comment by thegedge** [comment]
☝️ And specifically, if we're talking about the reverse of `lines`, just a `str collect` will do (because `lines` includes the newline in each string).

But indeed, `str collect` is the inverse.

Perhaps we should make `lines` be `str split` instead, which makes it a clear inverse, and anyone could then make `lines` an alias. Something to consider another day 🙂

**Comment by dogancelik** [comment]
The command below downloads all tarball versions of [del package](https://www.npmjs.com/package/del) with wget.

```
nu> fetch "https://registry.npmjs.org/del" | get versions | pivot | each { get Column1.dist.tarball } | str collect $(char newline) | wget -i -
```

Instead of `str collect $(char newline)`, I was thinking a command like `join "\n"`.

**Comment by a13ph** [comment]
```nushell
(open --raw file.ext | lines | str join (char newline)) == (open --raw file.ext)
```


this allows you to do manipulations on lines in-between, for example you can drop second line before `str join`ing back:
```nushell
open --raw file.ext | lines | drop nth 2 | str join (char newline)
```
