### ISSUE TITLE
libssl not loaded errors after installing nu through Cargo

### ISSUE THREAD

**Issue by djc** [nushell/nushell#1855]
**Describe the bug**
When starting up nu, I get the following messages:

```
djc-ing master corda-rpc $ nu                          
Welcome to Nushell 0.14.0 (type 'help' for more info)
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/djc/.cargo/bin/nu_plugin_binaryview
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/djc/.cargo/bin/nu_plugin_tree
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/djc/.cargo/bin/nu_plugin_binaryview
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/djc/.cargo/bin/nu_plugin_tree
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/djc/.cargo/bin/nu_plugin_binaryview
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/djc/.cargo/bin/nu_plugin_tree
  Reason: image not found
```

**To Reproduce**
1. cargo install nu --features stable
2. Start nu
3. 

**Configuration (please complete the following information):**
 - OS (e.g. Windows): macOS 10.15.4
 - Nu version (you can use the `version` command to find out): 0.14.0
 - Optional features (if any): stable

I do have openssl installed through homebrew (`openssl openssl@1.1` according to `brew list`).

**Comment by thegedge** [comment]
Interesting. It's linked against openssl 1.0, but looks like you have openssl 1.1. Perhaps the plugins were built and installed in a time where you had 1.0?

What happens if you do these steps:

- remove the files that are complaining (the "Referenced from" binaries in your message)
- `cargo build --features=stable`
- `cargo install --features=stable nu`

**Comment by djc** [comment]
Going through those steps seems to have solved the problem.

**Comment by thegedge** [comment]
Great! 🎉 

I don't see this as a nu issue. Unfortunately, between the time you last installed nu and the most current time, openssl 1.0 disappeared from your system. Homebrew is unfortunately bad at dependencies, because it doesn't know everything about your system, and what depends on what. This often means dependencies still being references by some executables will disappear, and those executables no longer function. I've been bitten by this plenty of times 🙂

**Comment by djc** [comment]
I'm still confused. I installed nu 2 hours ago from scratch and when I ran it it showed these errors. Why did I have to manually remove the "old" plugins? Did these plugins go away?

**Comment by thegedge** [comment]
I have two suspicions.

The first is that you had an old installation laying around, and `cargo install` didn't try to reinstall these plugins. When you say "2 hours ago from scratch", does that mean you've never installed nu before then?

My second suspicion would be that there's some kind of cache floating around in cargo/crates, but I'd be surprised by that, given how difficult it is to maintain such a cache. If there were a cache, there could be old binaries that are referencing this old library.

Outside of that, I'm uncertain. Maybe someone else has some other ideas 🙂

**Comment by djc** [comment]
I did install nu before then. But shouldn't my installation from 2 hours ago have overwritten these plugins?

**Comment by thegedge** [comment]
Ohh, I know what happened. I just did a `cargo install` myself, and noticed all of the plugins had the feature name as part of the bin name, either `nu_plugin_core_*` or `nu_plugin_stable_*`. Notice that in your error message, stable/core isn't part of the name. I'm guessing these were installed before the way we currently have things named (perhaps a `cargo install --bins`?).

If the names aren't going to change again, then I think we're done. If there are plans to rename them, we should do that now before moving forward. @andrasio @jonathandturner what do you think?

**Comment by lukesutton** [comment]
I know this issue is closed, but for anyone who is having the same issue, you can use cargo to uninstall any artefacts left over from a previous install e.g. `cargo uninstall nu:0.2.0`. You can find the list of installed versions via `cargo install --list`
