### ISSUE TITLE
Starship emoji fail if I configure some starship modules only

### ISSUE THREAD

**Issue by djc** [nushell/nushell#1856]
**Describe the bug**
The insertion of seemingly unrelated configuration makes emoji fail.

**To Reproduce**

<img width="614" alt="Screen Shot 2020-04-23 at 15 52 42" src="https://user-images.githubusercontent.com/158471/80106690-7abe0800-857a-11ea-801d-9f47d12f41f0.png">

**Expected behavior**
Disabling particular modules should not make emoji fail. (It does not appear to matter what configuration I set -- anything I add appears to make the emoji fail to show up.)

**Screenshots**

**Configuration (please complete the following information):**
 - OS (e.g. Windows): macOS 10.15.4
 - Nu version (you can use the `version` command to find out): nu 0.14.0 (also happened with 0.13.0)
 - Optional features (if any): stable

Also filed this as https://github.com/starship/starship/issues/1133, but got no response there (perhaps because the problem might be related to how starship is embedded in nu?).

**Comment by filalex77** [comment]
Reproduced on Windows 10, Nu 0.14.0. `git` icon changed.

<details>
<summary>Testing logs</summary>

```
nushell on 📙 master is 📦 v0.14.1 via 🦀 v1.43.1
❯ open ~/.config/starship.toml
error: File could not be opened
- shell:1:28
1 | open ~/.config/starship.toml
  |      ^^^^^^^^^^^^^^^^^^^^^^^ file not found

nushell on 📙 master is 📦 v0.14.1 via 🦀 v1.43.1
❯ echo '{"line_break":{"disabled":true}}' | from json | save ~/.config/starship.toml

nushell on  master is 📦 v0.14.1 via 🦀 v1.43.1 ❯ open ~/.config/starship.toml
────────────┬────────────────
 line_break │ [row disabled]
────────────┴────────────────

nushell on  master is 📦 v0.14.1 via 🦀 v1.43.1 ❯ rm ~/.config/starship.toml
deleted C:\Users\brigh\.config\starship.toml

nushell on 📙 master is 📦 v0.14.1 via 🦀 v1.43.1
❯
```

</details>

**Comment by djc** [comment]
This is still happening with nu 0.17.0. 😞

**Comment by jonathandturner** [comment]
@djc - you can call out to starship now by configuring a custom prompt. I'd be curious if you see the same behavior calling out that way rather than using the built in.

That's let us know if it's something related to the embedding or not.

**Comment by djc** [comment]
Ah, is there any documentation on how to set that up? I skimmed over https://www.nushell.sh/book/en/configuration.html but didn't see anything that seemed related.

**Comment by djc** [comment]
This is also happens if I run `starship prompt` outside nushell, so I suppose it's unrelated to nushell's embedding. I'll close this issue and pursue this further in https://github.com/starship/starship/issues/1133.
