### ISSUE TITLE
Add support for the new official Windows package manager

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#1859]
**Is your feature request related to a problem? Please describe.**
Microsoft recently announced "winget", which is in preview. It's due to become the official Windows package manager.  https://github.com/microsoft/winget-cli

**Describe the solution you'd like**
We should investigate what needs to happen to support this package manager. Taking a quick look at the release announcement, it targets Windows 10, as does Nu. 

**Describe alternatives you've considered**
There are alternative package managers for Windows, but if this one becomes the official one, and it works well enough to have growing adoption, it will be the natural choice.

**Comment by filalex77** [comment]
Seems like `winget` only supports `exe`/`msi`/`appx` installers for now.

Issues to watch:
- https://github.com/microsoft/winget-cli/issues/194
- https://github.com/microsoft/winget-cli/issues/182
- https://github.com/microsoft/winget-cli/issues/140

**Comment by fdncred** [comment]
Looks like we can make a yaml file and PR it [here](https://github.com/microsoft/winget-pkgs)

**Comment by jonathandturner** [comment]
Looks like we'll need to put Nu into a bundled installer. Not a bad idea.  Looks like the current set is:

exe, msi, msix, inno, wix, nullsoft, appx

**Comment by jonathandturner** [comment]
@filalex77 - those are great issues to watch. thanks!

**Comment by ctaggart** [comment]
I looks like support for exe/zip is on the roadmap for March 2021.
- https://github.com/microsoft/winget-cli/milestone/19 v0.17.x
- https://github.com/microsoft/winget-cli/milestone/20 v0.18.x

**Comment by TechWatching** [comment]
I did not submit this manifest to the Windows Package Manager repository but I can if you agree and if the value look fine to you (again it was just a quick test).

Another thing we could do would be to integrate this manifest generation in nushell github actions pipeline to generate it when a new version of nushell is released. wingetcreate has some [documentation](https://github.com/microsoft/winget-create/#using-windows-package-manager-manifest-creator-in-a-cicd-pipeline) about that in an Azure pipeline, it should not be too hard to convert it to a GitHub Action task.

**Comment by fdncred** [comment]
Ya, I think it's a good idea to support `winget` and put it in our CI. I'm sure we'd accept a PR that does such a thing. I just went through all the steps again to submit the PR and it requires you sign a CLA which states you're the sole owner of this software, which I'm not. We'll have to talk about this a bit more.

**Comment by itsme-alan** [comment]
@fdncred CLA refers to code which you are submitting to the repo (the YAML) not the software itself. I opened a PR anyway: https://github.com/microsoft/winget-pkgs/pull/17428

**Comment by fdncred** [comment]
Oooooh!  That wasn't clear to me. Thanks for submitting the PR.

**Comment by fdncred** [comment]
Let's close this since you submitted the winget PR. Thanks for everyone's help here!

**Comment by fdncred** [comment]
Maybe let's keep this open until it's live.

**Comment by itsme-alan** [comment]
The PR is now merged:

![Installing nu using winget - screenshot](https://user-images.githubusercontent.com/75578443/121848171-46ba1f00-cd07-11eb-869f-ffa4d59d6b29.png)

**Comment by jonathandturner** [comment]
@itsme-alan - thanks for getting this landed!

**Comment by itsme-alan** [comment]
I will open a PR to add instructions to README.

I think this issue should remain open until someone automates this PR process

**Comment by TechWatching** [comment]
I opened a PR #3717 to automate the PR process during a release of nushell.

**Comment by TechWatching** [comment]
@jntrnr @fdncred  I created a [new PR](https://github.com/nushell/nushell/pull/3819) to solve the issue that occured during last release.

**Comment by fdncred** [comment]
closing this due to #3819. Thanks!
