### ISSUE TITLE
Ensure saved aliases work in startup 

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1860]
**Describe the bug**
We recently landed https://github.com/nushell/nushell/pull/1852.  After having a think, I wonder if there are some situations where `--save` doesn't quite do what you want.  For example, if the alias in `startup` is not on a row by itself, but is part of another row, are we properly replacing it?

Feels like we may want to be less fancy and just append for now. In the future, we can have a more structured way of updating the startup.

**To Reproduce**
1. In theory, in startup, add an alias as a part of another command

**Expected behavior**
You should be able to add aliases without breaking other parts of the startup.

cc @1ntEgr8

**Comment by 1ntEgr8** [comment]
Just wanted to make sure I understand this:
if we have the following `startup`:
```
startup = [ "ls -a | alias say-hi [] { echo 'hello world' }" ]
``` 
attempting to create a new alias `alias say-hi [] ....` should replace the one in the pipeline?

**Comment by jonathandturner** [comment]
Right. It can get pretty complicated to find all of them and also to change the one the user wants to change.  Are you thinking we should just not try to replace the ones in the example?  That could make sense I guess.  

Just my feeling: for now, I think putting it last will have the effect: it will save that alias so they can use it later. It's not as fancy, but I think users could see it and understand what's happening.
