### ISSUE TITLE
"command not found" when any "from" or "to" command

### ISSUE THREAD

**Issue by empath-75** [nushell/nushell#1864]
**Describe the bug**
just installed from homebrew:

```
11:17:19 ❯ nu
Welcome to Nushell 0.14.0 (type 'help' for more info)

☸ qawest in ~ via 💎 v2.6.3 
11:06:46 ❯ echo '{"hello": "world"}' | from-json
error: Command not found
- shell:1:37
1 | echo '{"hello": "world"}' | from-json
  |                             ^^^^^^^^^ command not found
11:08:43 ❯ ls | to-json
error: Command not found
- shell:1:12
1 | ls | to-json
  |      ^^^^^^^ command not found
```

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**
 - OS (e.g. Windows):
 - Nu version (you can use the `version` command to find out): 
 - Optional features (if any):

**Comment by filalex77** [comment]
In Nushell 0.14.0, `from-*` and `to-*` commands became subcommands, e.g. `from *` and `to *`. See [0.14.0 release announcement](https://www.nushell.sh/blog/2020/05/12/nushell_0_14_0.html#breaking-changes-renaming-some-commands-jonathandturner-andrasio).

```
❯ echo '{"hello": "world"}' | from json
───────┬───────
 hello │ world 
───────┴───────
```

**Comment by thegedge** [comment]
@empath-75 was there some documentation that referenced a `from-*` or `to-*` command?

**Comment by kubouch** [comment]
@thegedge In [Quick command references](https://www.nushell.sh/documentation.html#quick-command-references) the from*/to*  commands are still listed with dashes `-`. It confused me as well.

**Comment by thegedge** [comment]
👍 I can see two things we could improve here:

1. Update the documentation (what I think will close this issue), and
2. maybe try to implement a "did you mean" message whenever a command is not found.

How does that sound?

**Comment by kubouch** [comment]
1. Just removing `-` from the doc is the most straightforward. However, I've been thinking that since _subcommands_ are now a thing, perhaps the quick reference could only list _commands_ to avoid clutter. _Commands_ like `from` or `to` could have a small `+` next to them where you could unroll its _subcommands_. Or an asterisk indicating they have _subcommands_ which would be listed on the _command_ page itself.
2. There is already an error on `get non-existent-column` which tells you what is wrong: 
```
^^^^^^^^^^ There isn't a column named 'non-existent-column'
---------- Perhaps you meant 'some-existing-column'? Columns available: foo, bar, baz
```
So it could have the same semantics:
```
^^^^^^^^^^ There isn't a command named 'from-json'
---------- Perhaps you meant 'from json'? Subcommands available for command 'from': csv, json, toml, whatever
```
Or something similar. This could easily grow into a very complex and verbose beast though.

**Comment by thegedge** [comment]
>  However, I've been thinking that since subcommands are now a thing, perhaps the quick reference could only list commands to avoid clutter.

+1 for this. To start, we could just make all the subcommands render on the page for the root command, later adding the `[+]` to expand on the index page (depending on how much work is involved to do that).

> There is already an error on get non-existent-column which tells you what is wrong:

Yep, I think we have a crate that does "did you mean" functionality, so I'm thinking it could be easy to adapt. The only problem is that we don't collect all external executables, so we could only suggest internal commands right now. I think that's a-o-k, and if we ever cache external commands, we can then expand it 🙂

**Comment by arashout** [comment]
Addressed in documentation
