### ISSUE TITLE
Mutually exclusive Signature switches

### ISSUE THREAD

**Issue by Kelli314** [nushell/nushell#1870]
It doesn't look like the Signature implementation currently allows for defining mutually exclusive arguments. For example, in #1869 the `rm -t` and `rm -p` switches should never be specified together as one sends files to trash and the other removes them permanently.  The alternative solution is to just do manual error checking in the related functions, but it would be nice to have this built-in.

**Comment by thegedge** [comment]
Great idea!

One nice side effect of doing this kind of thing, though, is that we could paint flags in an error state (e.g., `--trash` would be coloured red if one already provided `--permanent`).

Let's put this on the side for now, though, but try to keep track of some examples (like what you provided) of cases where a `Signature` may want to handle constraints on flags. The reason for this is that I don't want to add this complexity without fully understanding the scope of what we'd need. There's a cost to the wrong abstraction, so I'd like to get it right 🙂

I'll start the list:

## "One of"
* `rm`: one of `--permanent` or `--trash`
