### ISSUE TITLE
Implement OpenAutoComplete for command completions

### ISSUE THREAD

**Issue by Br1ght0ne** [nushell/nushell#1881]
**Is your feature request related to a problem? Please describe.**
- There should be a standard way for external commands to provide completions to Nu.
- All Nu commands/plugins should provide completions

**Describe the solution you'd like**
Implement [OpenAutoComplete](https://github.com/openautocomplete/openautocomplete) in Nu.
This would allow for both external commands *and* Nu commands/plugins to provide a standardised schema of completions to `nu-cli`.

**Describe alternatives you've considered**
- Writing a custom completion file format - won't drive adoption by program authors, is viable only for internal Nu commands
- Supporting an existing completion file format (like Bash, see #1412) - more widespread than OAC, but that doesn't go well with Nu's crossplatform support (e.g. why would Windows users have Bash completions on their device?)
- Not providing means for external command completions at all - definitely contradicts #290, and doesn't sound like a future for Nu

**Additional context**
I've started working on a (rather hacky) [implementation of OpenAutoComplete in Rust](https://github.com/filalex77/oac). It's only a parser for now (JSON => Rust structs), e.g. Nu (or other crates) would need to provide means for:
- supported command detection
Commands supporting OAC spec should support `--openautocomplete` flag (see [OAC-enabled app development considerations](https://github.com/openautocomplete/openautocomplete/blob/master/SPECIFICATION.md#oac-enabled-app-development-considerations))
- generating actual completions UI

Not in scope for Nu (more like stretch goals for `oac` crates):
- Add `--openautocomplete` support to `clap`

**Comment by thegedge** [comment]
We definitely need to think more broadly about completions.

I figure @jonathandturner and @wycats have stronger opinions here than me, but here's my two cents worth right now:

- OAC is incredibly immature, so it's hard to say if it will be a good fit for nushell. My major concern is that it's likely being modeled in the context of existing shells, and nushell is trying to be something totally different, so it's more likely that we could diverge.
- nushell has signatures and types. These are used for parsing, painting, completions, and much more in nushell. They're also have the potential be far more robust and flexible than patterns. In other words, OAC format may not be able to express everything we get from a signature, making it a poor fit as the fundamental descriptor of a command in nushell.
- We could totally build a completion engine that can consumes OAC formats on top of our own 🙂

**Comment by filalex77** [comment]
@thegedge Thanks for a detailed answer! I definitely agree with your points.

 Should I keep this issue open as a reminder until later?

**Comment by thegedge** [comment]
It's not a bad idea to keep this on our radar, so let's keep it open 🙂

I'll add the `investigate` tag.
