### ISSUE TITLE
Add min and max commands

### ISSUE THREAD

**Issue by mardukbp** [nushell/nushell#1882]
They take a column as input. Similar to `average` and `sum`.

**Comment by jonathandturner** [comment]
@mardukbp - this sounds good.

Any interest in trying to work on the idea, too?

**Comment by mardukbp** [comment]
Yeah, I will take a look at the implementation of average and try to implement these functions myself.

**Comment by jonathandturner** [comment]
@mardukbp sounds good. If you have any questions, feel free to ask here or in the discord.

**Comment by fdncred** [comment]
It would be nice to combine all these math plugins into one so one could do `ls | get size | math sum` or something like that. But that would probably take it from a `good first issue` to something more complicated.

**Comment by arashout** [comment]
currently I don't think average is a plug-in, it was recently moved I think.
Either would I would be interested in working on this, I was looking into this issue previously as well.
Maybe after I figure out how to do min/max I can work on making a plug-in to combine them all?

**Comment by fdncred** [comment]
@arashout I'm cool with that or even if you and @mardukbp want to combine efforts in some way. I'd just like to declutter the bin folder. the more plugins we have the slower starting up nushell will be - although that speed has been radically increased lately.

**Comment by arashout** [comment]
Also for the overarching plug-in name, what about `stats`?

**Comment by jonathandturner** [comment]
Agreed with @fdncred that something like min/max wants to be built-in internal commands I think.

As for the name of the command, I'm starting to wonder if we want to start a `math` command. That'd give you `math min`, `math max`, `math average`, etc.  @arashout `stats` could also work, though when I first read that I thought it meant stats on the file rather than mathematical statistics.

**Comment by arashout** [comment]
Okay I'll stick with `math`.
I'm working on getting the max plugin working right now

**Comment by arashout** [comment]
@jonathandturner Can be closed

**Comment by mardukbp** [comment]
Thank you @arashout!
