### ISSUE TITLE
`sum` doesn't handle mismatched types correctly

### ISSUE THREAD

**Issue by DangerFunPants** [nushell/nushell#1883]
**Describe the bug**
`sum` doesn't handle mismatched types correctly.

**To Reproduce**
```nu
echo [1 2 3 NotAnInt] | sum
```

**Expected behavior**
Nu should report an error indicating that the user attempted to sum two values for which the sum operation is not defined. Instead Nu treats the non-numeric values as an inverse for add (i.e. forall v \in  `Value`, v + t = 0 where t is a non-numeric value). As a result the example given above outputs 0 instead of the expected error. This is done because the type signature of the `add` operation (`T -> T -> T`) prevents an error being returned to the caller, so the function just returns a default value.

**Configuration**
 - OS: NixOS 20.03
 - Nu version: 0.14.1

This is related to the issues raised in #1787 and #1603 but does not actually have the same root cause. 

@jonathandturner prposes a solution to this issue under #1603:
>What we probably want to do is to not use std::ops, since our operations can fail. Instead, we could use the new math operations, and merge them with some of the logic from the std::ops to get something that's as good as both, but also returns a Result so we can see the possible error.

I agree with @jonathandturner but this issue raises a few questions: 
1. Why does the `Value` type contain an `Error` variant? This results in the `Value` interface feeling a little clunky because chained calls on a single `Value` instance don't really compose anymore. It's also awkward to use functions that return `Result<Value, T>` because callers need to handle both the `Result::Err` variant and the `Error` variant of the `Value` type. My impression is that the `Value` type is deeply rooted in many core components of `Nu` so it might be difficult (and even ill-advised) to change this but it's interesting to think about. 
2. There's also the question of how type checking should be done as data flows through the pipeline. I'm not going to say much about this because I get the impression that it's an issue that everyone is already thinking about, but fixing this issue would involve doing some ad-hoc type checking so it might be helpful to consider this as a simple use case for prototyping how end-to-end type checking might work.

**Comment by thegedge** [comment]
> Why does the `Value` type contain an `Error` variant? 

I joined the project after decisions were made here, but I have a hunch to the answer here. `Value` is the main piece of data used as part of the nu protocol. It's what internals and plugins use to communicate. Plugins unfortunately can't return a `Result` 🙂

That being said, there's no reason we couldn't have something special for plugins (e.g., an enum with either a value or the error), and internally we pass around `Result<ValueWithoutErrorVariant, ShellError>`. This is above my pay grade 😉
