### ISSUE TITLE
Ability to explicitly request running an internal command

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#1885]
**Is your feature request related to a problem? Please describe.**

If we were to alias a builtin command, it would be recursive (I think?):

```
alias ls [...] { ls ... }
```

**Describe the solution you'd like**

Just like we have `^ex` to force running an external command, some kind of syntax to force a builtin command would be useful.

**Describe alternatives you've considered**

I can't think of any alternative for this.

**Comment by uberjay** [comment]
Other shells typically use the `builtin` builtin for this. e.g.,
```
alias ls [...] { builtin ls ... }
```

**Comment by thegedge** [comment]
We'll need to consider subcommands too (for example, `to json`).

**Comment by bailey-layzer** [comment]
Could I claim this (and #2191)? I can implement it as a command `builtin` as @uberjay suggested. What about `_bi` for an abbreviated syntax to parallel `^ex`?

**Comment by jonathandturner** [comment]
I was thinking about this one recently. I think the way aliases are implemented is going to make it difficult, so the first thing we probably want to do is to perhaps change how those are implemented.

Currently, when an alias is created, we put it in the list of internal commands. This means if you alias an existing internal command, we'll remove the old one and put the alias in its place. This clearly has some negative consequences :)

My hunch is that we want aliases to be scoped, just like variables. We'd need to work out what an alias can see - eg) maybe they can only commands in a higher scope than they are? It's maybe a little tricky, and something we should spin up a separate issue thread on so we can explore all the corner cases.

I think once we figure out how to get the right visibility for commands in aliases, and for aliases to not overwrite internal commands, then being able to alias internal commands and still be able to call into the original commands should just work.

**Comment by bailey-layzer** [comment]
This continues to bounce aorund my head. Question on expected behavior: say I create an `alias full-ls [] { ls -f }` and then a default `alias ls [] { ls -a }`. If I now call `full-ls`, should I see the hidden files (i.e. should the alias appear to "capture" commands in its block, however that's actually accomplished)?

**Comment by thegedge** [comment]
Great question, @bailey-layzer.

I think the most natural thing would be that aliases can call aliases. When we override a builtin name, I can see these two possibilities:

1. Try to be smart, analyze the pipeline to see if that builtin is called, and ensure the builtin is called instead of the alias being called recursively.
2. Assume the user forces it to be the builtin through some command that ensures the builtin is called instead of the alias. For example, `builtin ls`. Even if we did this, it may still be good to analyze the body of the alias to ensure infinite recursion doesn't happen, but we could also do this check at runtime (I prefer doing it statically though).

Perhaps there's another?

**Comment by gutenye** [comment]
This is not solved. Can we reopen it?
