### ISSUE TITLE
Provide VS Code debug support for Nushell

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#1887]
**Is your feature request related to a problem? Please describe.**
I would love to be able to use VS Code to debug Nushell code.  It is mostly currently possible, aside from an error thrown by Nushell:

```shell
Welcome to Nushell 0.14.1 (type 'help' for more info)
/Users/josephlyons/Programming/Rust/Forked Repos/nushell(master)> ls
Something unexpected happened:
ShellError { error: UntaggedRuntimeError { reason: "Could not open terminal for output" }, cause: None }
```

**Additional context**

Here is the the way I set up VS Code in order to debug Nushell/Rust code:

1. Open the Nushell project in VS Code
2. Install [Rust Analyzer extension](https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer)

<img width="1648" alt="Screen Shot 2020-05-25 at 1 43 52 AM" src="https://user-images.githubusercontent.com/19867440/82782101-888cd480-9e29-11ea-8ae6-4ad8dc6e8acb.png">

3. Install [CodeLLBD extension](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb)

<img width="1648" alt="Screen Shot 2020-05-25 at 1 43 45 AM" src="https://user-images.githubusercontent.com/19867440/82782118-92163c80-9e29-11ea-8501-00b7addb070c.png">

4. Click the debug icon on the lift side of VS Code and click "Create a launch.json file"

<img width="1648" alt="Screen Shot 2020-05-25 at 1 43 57 AM" src="https://user-images.githubusercontent.com/19867440/82782148-a22e1c00-9e29-11ea-9af8-1a4ef62d0340.png">

6. Select "LLBD" in the dropdown

<img width="1648" alt="Screen Shot 2020-05-25 at 1 48 24 AM" src="https://user-images.githubusercontent.com/19867440/82782241-dbff2280-9e29-11ea-8d56-76405a6b2867.png">

7. Select "Yes" to the question: "Cargo.toml has been detected in this workspace.
Would you like to generate launch configurations for its targets?"

<img width="1648" alt="Screen Shot 2020-05-25 at 1 44 31 AM" src="https://user-images.githubusercontent.com/19867440/82782251-e3263080-9e29-11ea-970f-fa0deaebd803.png">

8. Select "Debug executable 'nu'" in the "Debug Run" dropdown

<img width="1535" alt="Screen Shot 2020-05-25 at 1 44 55 AM" src="https://user-images.githubusercontent.com/19867440/82782299-04871c80-9e2a-11ea-919c-fac14f0091fb.png">

9. Set a breakpoint in the code and click the play button in next to the "Debug Run" dropdown.  You will notice that VS Code actually does stop the code execution and provides you with the variable values on the left side.

<img width="1648" alt="Screen Shot 2020-05-25 at 1 45 48 AM" src="https://user-images.githubusercontent.com/19867440/82782398-39936f00-9e2a-11ea-8ee4-75e015419665.png">

10.  Allow the debugger to finish its execution and notice the error produced by Nushell:

<img width="1648" alt="Screen Shot 2020-05-25 at 1 45 51 AM" src="https://user-images.githubusercontent.com/19867440/82782427-4ca63f00-9e2a-11ea-81dc-f825c1bdee1a.png">

**Comment by arashout** [comment]
That error message comes from the [`table.rs`](https://github.com/arashout/nushell/blob/d0f17bbe5893d8534f9551a03bd5c2eaad95045a/crates/nu-cli/src/format/table.rs#L406)

I'm not familiar enough with nu to think about possible workarounds or solutions.
Does it work if you comment out that line? I guess you just would not have any outputs for tables

**Comment by arashout** [comment]
Odd, just tried this and I can't reproduce it.
My debug seems to work fine, thanks for the detailed write-up on the process because I actually didn't know the debugging worked in Rust yet!

**Comment by mokeyish** [comment]
The stale bot should be turned off, it doesn't really solve the problem, it just covers it up.

----


On VsCode on Windows, because cmd is too difficult to use, so I set to use nushell. However, after this setting, when I click debug rust code, nushell freezes.


![image](https://github.com/user-attachments/assets/c915a8d9-2045-44ed-a3d5-c89772e71f11)
