### ISSUE TITLE
Implement from-x509

### ISSUE THREAD

**Issue by mardukbp** [nushell/nushell#1889]
**Use case**
Nushell can be used as a tool for inspecting X.509 certificates, providing a more efficient interface than `openssl`.

**Describe the solution you'd like**
Using the `native_tls` crate one can import DEM- and PER-formatted X.509 certificates without requiring a third-party C library. The resulting string has to be parsed as a nested structure of Nu Shell-tables.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by fdncred** [comment]
Posted in r/rust https://dev.to/wayofthepie/decode-a-certificate-5903
