### ISSUE TITLE
Implement from and to functions for email formats

### ISSUE THREAD

**Issue by mardukbp** [nushell/nushell#1892]
**Is your feature request related to a problem? Please describe.**
Sometimes one needs to extract attachments from an Outlook .msg file or an Apple Mail .mbox file.
Nu Shell could be the tool for doing that and more.

**Describe the solution you'd like**
The [mailbox](https://github.com/meh/rust-mailbox) crate parses emails stored in MBOX format. The [mailparse](https://github.com/staktrace/mailparse) crate parses emails stored in Maildir format. Using these crates these email formats can be parsed as nested Nu Shell-table structures.
 
**Describe alternatives you've considered**
None.

**Additional context**
Nu Shell already has rudimentary support for the .elm format. AFAIK there is still no Rust parser for .msg files.

**Comment by aeshirey** [comment]
> Sometimes one needs to extract attachments from an Outlook .msg file or an Apple Mail .mbox file.

I wrote the [.eml parser library](https://github.com/aeshirey/EmlParser/) that Nu uses as well as the `from-eml` command. Extracting attachments themselves from .eml files is [something I'd like to do](https://github.com/aeshirey/EmlParser/issues/2) at some point.

As for msg and mbox, it looks like there's [an mbox library](https://github.com/meh/rust-mailbox) that is roughly analogous to `EmlParser` but doesn't yet do attachments. I don't see anything for msg files at all.
