### ISSUE TITLE
Discuss the Possibility of Adding a Mechanism to Allow Colors to be Applied to Data

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#1893]
**Is your feature request related to a problem? Please describe.**
In some commands, being able to apply color to the data may be desired.  Specifically, this came up in the discussion of how to show the current day in the `cal` command (some details [here](https://github.com/nushell/nushell/issues/1740)) and the idea of providing some way to color the data came up.  I think this could be useful in other situations as well, although I don't specifically know where.  It would open up new ways to show data that I think could be attractive for users.

**Describe the solution you'd like**
Not sure.  In Discord, @jonathandturner mentioned: "...Values can have metadata attached to them. We could put a color in that metadata, but we'll need to do some tests to see much much slower that makes printing it out".  I don't fully know how colors work in Nushell, but maybe it could be an Option... `Option<ColorChoice>`, and if it is `None`, then there is nothing to apply, else, apply the color.  Again, I don't know how colors work, I haven't really investigated it, so maybe this makes no sense at all with the current implementation of it all.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by fdncred** [comment]
@JosephTLyons Hopefully we can make these configurable parameters. Maybe a specific `[colors]` section in the `config.toml` with something like `app`:`key`:`color`. 
Example:
```
[colors]
cal:current_day:#FF0000
cal:holiday:#00FF00
cal:normal_day:#0000FF
ls:folder:#666666
ls:executable:#FF0000
ls:file:#00FF00
```

**Comment by JosephTLyons** [comment]
> @JosephTLyons Hopefully we can make these configurable parameters. Maybe a specific `[colors]` section in the `config.toml` with something like `app`:`key`:`color`. 
> 
> Example:
> 
> ```
> 
> [colors]
> 
> cal:current_day:#FF0000
> 
> cal:holiday:#00FF00
> 
> cal:normal_day:#0000FF
> 
> ls:folder:#666666
> 
> ls:executable:#FF0000
> 
> ls:file:#00FF00
> 
> ```

That seems like a good idea.

**Comment by fdncred** [comment]
@JosephTLyons Where'd you get with this? I've been looking at https://github.com/sharkdp/lscolors and it seems to work pretty well for coloring files.

**Comment by JosephTLyons** [comment]
@fdncred, well, when I was working on this, I was just trying to add a mechanism to allow data in the table to be colored.  I had it working at one point, but then the old nu-table was scrapped and a new one was added.  I tried re-writing the code for the new nu table and ran into some issues with certain structs we use from other packages not supporting some of the traits I would've need to get it to work.  I let @jonathandturner know of what issues I ran into and then I moved on away from it.  

I don't remember exactly what I was doing, but I think I was trying to add `Option<TextStyle>` to the tag, so that tagged values could be accompanied by either Some TextStyle or None, then it would be used when the table was printed, but yeah, the technical issues kept this from happening.

I haven't thought of any other solutions or discussed anything else, but I have a command I've been wanting to add color support to ever since it was created, so I'm open to hear what other suggestions there might be.

**Comment by fdncred** [comment]
@JosephTLyons Thanks for the recap. If you look at [this gist](https://gist.github.com/fdncred/94d197614a83eb96df3dc396f423147c), you'll see my inventory of how color is used in nushell. The idea is to abstract a renderer, perhaps like you're saying, and make it accessible with coloring/theming. This renderer could also render other things too, kind of like autoview was intended to do. We talked a little about it yesterday [here](https://github.com/nushell/notes/blob/main/07-31-2020.md) but didn't have time to go into detail.

It would be nice to push this along. Perhaps we need a RFC for this so other people can comment and make suggestions. Thoughts?
