### ISSUE TITLE
`save` allows arbitrary top-level values in TOML

### ISSUE THREAD

**Issue by filalex77** [nushell/nushell#1907]
**Describe the bug**
Split from #1906.
`save` shouldn't allow writing any top-level values other than a table to a TOML file, and should give a proper error message.

**To Reproduce**
1. Construct a value other than a table (e.g. `ls | get modified` is an array of strings)
2. `save` the value to a TOML file
3. Try to `open` the resulting file, get an error.

**Expected behavior**
`save` should give an error message, and nothing should get saved to the file.

**Comment by arashout** [comment]
I'm going to try and tackle this

**Comment by arashout** [comment]
@thegedge I think I have resolved this in my PR

**Comment by thegedge** [comment]
Closed by https://github.com/nushell/nushell/pull/1946
