### ISSUE TITLE
Error: Unable to read from stdout (incomplete utf-8 byte sequence from index 8191)

### ISSUE THREAD

**Issue by Cykooz** [nushell/nushell#1909]
```
❯ cat data.csv | from csv --headerless
^Cerror: Unable to read from stdout (incomplete utf-8 byte sequence from index 8191)
- shell:1:44
1 | cat data.csv | from csv --headerless
  | ^^^ unable to read from stdout
```

This command stuck after I run it. The error shown above has appeared after I press Ctrl+C.

----
Ubuntu 19.10
Nushell 0.14.0

**Comment by jonathandturner** [comment]
@Cykooz - are you able to share the "data.csv" file you're reading from?

**Comment by Cykooz** [comment]
@jonathandturner 
[data.zip](https://github.com/nushell/nushell/files/4700674/data.zip)

**Comment by fdncred** [comment]
A couple interesting things here.
1. That it's exactly 8191, which on a 0 indexed file is 8192 aka exactly 8k.
2. That byte's text is on row 161 and looks weird. 
`259318,2020-03-01T11:46:36.774000+00:00,,–ò–†–ò–ù–ê-HP (Windows 10) v1.9.3.16` (with mac roman encoding)
`259318,2020-03-01T11:46:36.774000+00:00,,╨ÿ╨á╨ÿ╨¥╨É-HP (Windows 10) v1.9.3.16`(with cp437 encoding)
`259318,2020-03-01T11:46:36.774000+00:00,,ИРИНА-HP (Windows 10) v1.9.3.16` (with utf-8 encoding)
3. Byte 8191 is right after this part of the line `259318,2020-03-01T11:46:36.774000+00:00,,`

So, my question is, is the `funky` part of that line `D0 98 D0 A0 D0 98 D0 9D D0 90 2D` (in hex), part of utf-8.

**Comment by Cykooz** [comment]
The example CSV-file is a text with UTF-8 encoding.

**Comment by Cykooz** [comment]
It was fixed. I've checked this case on version 0.33
