### ISSUE TITLE
`str to-float` should probably be `str to-decimal`

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1925]
**Is your feature request related to a problem? Please describe.**
We should keep our naming consistent where possible. The recent `str to-float` should probably called `str to-decimal` to keep with the naming convention for decimals in other parts of the project.

**Describe the solution you'd like**
Rename the sub-command to `to-decimal`

**Describe alternatives you've considered**
We can keep it float and rename the others to float, but float is very specific to an implementation of a decimal number, and we use big decimal numbers underneath.

**Comment by jonathandturner** [comment]
@routrohan yes! will assign it to you

**Comment by routrohan** [comment]
Thank you @jonathandturner 
could you please specify the location of the sub-command? 
like the file/ directory name?

**Comment by jonathandturner** [comment]
If you search for `to-float`, you'll see the places that will need to change:

```
> rg "to-float"
crates\nu-cli\tests\commands\str_.rs
110:            | str to-float

crates\nu-cli\src\commands\str_\to_float.rs
24:        "str to-float"
28:        Signature::build("str to-float").rest(
49:            example: "echo '3.1415' | str to-float",
```

**Comment by andrasio** [comment]
@routrohan You may want to rename the file `to_float.rs` as `to_decimal.rs`, too. Then, in that same directory `str_` find the file `mod.rs` and rename the re-export `StrToFloat` to `StrToDecimal`. Continue with the replacement on `StrToDecimal` as well in the files at `crates/nu-cli/src/commands.rs` and `crates/nu-cli/src/cli.rs` and you should be ready to go.

Don't forget to run the tests (`cargo test --all --features=stable`)

**Comment by routrohan** [comment]
@andrasio Alright! will do

**Comment by routrohan** [comment]
It has been done. I am open to other basic fixes / contributions if needed.

**Comment by andrasio** [comment]
@routrohan Great! Are you in the Discord chat btw?

**Comment by routrohan** [comment]
No
I would love to join for more opportunities

**Comment by johnterickson** [comment]
Haha I just asked about this morning - glad to see it making progress!

**Comment by JosephTLyons** [comment]
https://github.com/nushell/nushell/pull/1926

**Comment by jonathandturner** [comment]
It does, thanks for the reminder
