### ISSUE TITLE
Implement history navigation with j and k when in vi mode

### ISSUE THREAD

**Issue by IovoslavIovchev** [nushell/nushell#1927]
**Is your feature request related to a problem? Please describe.**
Currently, when `vi` mode is enabled, the `j` and `k` keys are not used for navigating the command history. While the arrow keys do the job, it would be more comfortable if the `j` and `k` keys could be used as well.

**Describe the solution you'd like**
- Pressing `j` does the same thing as arrow key down.
- Pressing `k` does the same thing as arrow key up.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by IovoslavIovchev** [comment]
This is actually something that `rustyline` offers out of the box, however the feature is currently only available on the latest master, as it was committed after v6.1.2 was released.

**Comment by thegedge** [comment]
Oh, great to hear. Then that means we can wait until the next release of rustyline, bump it in nushell, and call it a day 🙂

**Comment by IovoslavIovchev** [comment]
Yep, I guess this can be closed now.

**Comment by thegedge** [comment]
I'll keep it open as a reminder to bump rustyline asap.

**Comment by jonathandturner** [comment]
Bumped, should be working in master. If it isn't, please let us or rustyline know.
