### ISSUE TITLE
Garbled output on Windows when ls is run in C:\

### ISSUE THREAD

**Issue by trolleyman** [nushell/nushell#1929]
**Describe the bug**
When I run `ls` on Windows in `C:\`, the result appears garbled

**To Reproduce**
1. Navigate to `C:\`
2. Run `ls`
3. Garbled output

**Screenshots**
Garbed output:
![image](https://user-images.githubusercontent.com/4435960/83540531-631a5d80-a4f0-11ea-9127-3c55173a6999.png)

![image](https://user-images.githubusercontent.com/4435960/83540725-96f58300-a4f0-11ea-9ad4-44ace21a59e3.png)

**Configuration (please complete the following information):**
 - OS: Windows
 - Nu version: 0.14.0
 - Optional features (if any): `stable`

**Comment by thegedge** [comment]
I thought we recently made `ls` always include the size column, but maybe I'm wrong there.

There's also the issue with the `sys` files not having any type.

**Comment by jonathandturner** [comment]
There may be some improvements in master, but I tried a recent master and still seeing some of this behavior where a column is left out.

I wonder if we should updated TaggedDictBuilder to take the columns first, so that it will automatically fill Nothing in for you if you don't provide it.

**Comment by fdncred** [comment]
@jonathandturner, @thegedge My vote, for file system listing, is that we should have a fixed number of columns for `ls` and another set of fixed columns for `ls -f`, per platform, and then populate `Unknown` where nu doesn't have permissions or whatever is going on. Not to get on a soapbox or anything but, for me, this greatly affects the usability. I also relate this to reading csv files where the columns change off and on and the output looks similar to this issue.

Alternately if a `TaggedDictBuilder`update accomplishes the same thing but better, I'm all for that too, whichever is easier

**Comment by fdncred** [comment]
Related to #1985

**Comment by arashout** [comment]
I believe this has been resolved with the above PR.
Please Re-open if it's not the case!
