### ISSUE TITLE
Starship symbols not showing properly

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#1933]
[EDIT: Adjusted the description to match the actual problem after installing emoji fonts]

**Describe the bug**
Starship launched from within `nu` has a different icon for Git branch than `starship` launched from a terminal.

**To Reproduce**
Steps to reproduce missing git branch symbol:
1. `git clone https://github.com/nushell/nushell.git`
2. cd nushell
3. see the screenshot

**Expected behavior**
Expected to see a Git branch icon instead of a book

**Screenshots**
![starship_bug_emoji](https://user-images.githubusercontent.com/25571562/83938512-8ccbd100-a7dd-11ea-9aa4-667b28da5616.png)

**Configuration (please complete the following information):**
 - OS (e.g. Windows): ArchLinux
 - Nu version (you can use the `version` command to find out): 0.14.0 (installed from AUR)
 - Optional features (if any): 
    * Alacritty terminal 0.4.3
    * starship (from AUR) 0.41.3
    * installed `noto-fonts-emoji` font package
    * using fish as my default shell
    * haven't touched any configuration files of either nushell or starship

**Comment by chipbuster** [comment]
Hey @kubouch, starship maintainer here.

Do you have an [emoji font](https://wiki.archlinux.org/index.php/fonts#Emoji_and_symbols) like ttf-joypixels or noto-font-emoji installed? This seems to be the most common issue with emojis on Arch--they aren't packaged into the rest of the system fonts like they are in other places.

**Comment by kubouch** [comment]
Yes, I didn't have an emoji font installed. That solved the missing boxes. However, nu still shows a book instead of a branch icon:
![starship_bug_emoji](https://user-images.githubusercontent.com/25571562/83938294-a4a25580-a7db-11ea-81b8-0a90472238ef.png)

**Comment by chipbuster** [comment]
Hmm, that's strange. The powerline fonts use a reserved area of the Unicode spec, so there shouldn't be *wrong* emojis.

Have you modified `alacritty.yml` at all? If so, could you post the contents of `alacritty.yml` here?

**Comment by kubouch** [comment]
I don't recall touching alacritty config. I deleted the local config file just to be sure and the problem still persists, also on a different PC.

**Comment by chipbuster** [comment]
Hmm, I'm at a loss then. Powerline uses the private area of the Unicode space for symbols, so it shouldn't be misinterpreted like that, but the only thing I can think of is that it's somehow incorrectly interpreting the emoji alongside some other escape.

Could you confirm that this still happens in a different terminal emulator (say, something VTE-based?) If so, then I'm unfortunately out of ideas for the time being.

**Comment by kubouch** [comment]
I tried Termite, same issue.

**Comment by kubouch** [comment]
Actually, from a Discord discussion I now recall that Nushell uses its own icon set so that's probably why it shows different icons.

So probably not an issue after all but I still keep it open as it might be a good point to add to the documentation (along with installing emoji fonts).

**Comment by chipbuster** [comment]
I think the emoji font thing should be documented on the Starship side as well--you're not the first person to have this issue, and I doubt you'll be the last.

**Comment by deoradh** [comment]
So what's the resolution?  Is there a fix for this?

Windows 10, using Windows Terminal, with Cascadia Code PL font.

Custom prompt for PS + Posh is working.  Nu + Statship is showing the book.  Changing to use Fira Code doesn't change it.  Trying Nu in a standalone window (not WT) doesn't change it.

**Comment by kubouch** [comment]
Now that [starship is not part of Nushell anymore](https://www.nushell.sh/blog/2020/09/01/nushell_0_19.html#starship-is-now-external), this is not a thing anymore.
