### ISSUE TITLE
Character encoding in files with  open  and  save

### ISSUE THREAD

**Issue by stuartclayman** [nushell/nushell#1939]
I have had some issues with a file recently.   I spent ages on it until I realised the real issue.

I have a big CSV file which uses ';' separators, so I was hoping that nushell would be useful.
But when I tried to process it in any way I got strange messages:

```
❯ open nilg.csv  --raw | lines
error: Expected a string from pipeline
- shell:1:28
1 | open nilg.csv  --raw | lines
  |                        ^^^^^ requires string input
- shell:1:28
1 | open nilg.csv  --raw | lines
  |      -------- value originates from here
```

When I tried to just open it

`❯ open nilg.csv  --raw `

I got this:

```
172450:   3b 22 22 3b  22 22 3b 22  22 0d 0a 22  4d 72 22 3b   ;"";"";"".."Mr";
172460:   22 57 69 6c  73 6f 6e 20  4d 50 22 3b  22 53 61 6d   "Wilson MP";"Sam
172470:   6d 79 22 3b  22 48 6f 75  73 65 20 6f  66 20 43 6f   my";"House of Co
172480:   6d 6d 6f 6e  73 0b 4c 6f  6e 64 6f 6e  0b 53 57 31   mmons.London.SW1
172490:   41 20 30 41  41 22 3b 22  22 3b 22 30  31 37 31 20   A 0AA";"";"0171 
1724a0:   32 31 39 20  33 30 30 30  22 3b 22 22  3b 22 44 55   219 3000";"";"DU
1724b0:   50 22 3b 22  4d 50 22 3b  22 22 3b 22  22 3b 22 22   P";"MP";"";"";""
1724c0:   3b 22 22 3b  22 22 3b 22  22 3b 22 22  3b 22 22 3b   ;"";"";"";"";"";
```

After a bit of scratching around I tried this:

```
❯ open nilg.csv  --raw | describe
binary
```

This confused me a lot, as every other tool I used had no problem with this file.

After a couple of hours of trying various things, like cutting columns, selecting some rows only using LibreOffice, and looking at other files, I realised that this was the only file that nushell complained about.

Anyway to cut a long story short, the underlying issue is that my file was encoded in ISO-8859-1 and used a few 'special' characters.  When I used LibreOffice to save it as UTF-8, and then try that file in nushell everything is fine.

Now this process of saving new files is not a good general solution going forward, and I think that nushell should not assume that all input files are in some UTF encoding.  There's a lot of historic data out there, from many platforms.

So is it possible to add a '--encoding' flag to `open` and to `save` so these aspects can be dealt with properly in nushell.

That way I can do:  `open nilg.csv --encoding iso-8859-1 --raw | lines `
without having an external tool to do re-encoding.

**Comment by andrasio** [comment]
@stuartclayman THANK YOU. I faced this exact problem and stop digging into it. We figured it was an encoding issue.

**Comment by andrasio** [comment]
@stuartclayman If your data is not sensitive or if you have other ways to provide us a file like it. Can you supply it to us so we can download and investigate?

**Comment by stuartclayman** [comment]
Here is the file.  It's zipped up as CSV is not a supported file type apparently.

Note there are not so many special characters, but this is an example person name to look out for:
Cllr,Caoimhín,Mac Giolla Mhín
    see the special í


[nilg.zip](https://github.com/nushell/nushell/files/4732957/nilg.zip)

**Comment by stuartclayman** [comment]
Having thought about it some more, I think that the current default way of showing such a file as 'binary' is not correct.
It would be better to send it onto the pipeline as text, and have the special characters shown as \0xED or \xED.
That way

**Comment by stuartclayman** [comment]
Still trying .....

Anyway I found a half way solution.  This works for me:

`❯ iconv -f iso-8859-1 -t utf-8 nilg.csv | from csv --separator ';' `

but you do need iconv to be installed

**Comment by jonathandturner** [comment]
Seems like we should add iso-8859-1 support to `open` and to the `MaybeTextCodec` (or better yet, have open use the codec, so we can share the codec across all input streams)

**Comment by stuartclayman** [comment]
For generality you should do more than just iso-8859-1.
Also have the same options in `save`

I did a bit of searching.   It seems this package has the necessary functionality  [https://github.com/lifthrasiir/rust-encoding](https://github.com/lifthrasiir/rust-encoding)

Then we can do:
`open nilg.csv --encoding iso-8859-1 | some_processing | save new_file.csv --encoding windows-1252`

Dealing with different encodings in multiple data files is a regular issue in some of the work me and my colleagues do, so having a toolset that deals with it well is a real bonus.

**Comment by gl-yziquel** [comment]
`open my_encoded_file.txt --raw | decode Windows-1252` seems to work pretty fine. (thanks discord chat for that.)

I know this is an old issue, but if people stumble here, like me, this may suit their needs.
