### ISSUE TITLE
Investigate connecting to platform's recycle bin

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#194]
Some platforms have a way to delete items into a recycle bin, where they can later be recovered if necessary. We may want to find or create a crossplatform way to move files into the recycle bin for that platform rather than outright deleting them.

**Comment by jdvr** [comment]
Hi, I have found https://github.com/ArturKovacs/trash

is it ok if I put some effort in make it works for OSx and the I integrate the crate into Nu?

What do you think ?

**Comment by jonathandturner** [comment]
@jdvr - that sounds great

**Comment by ayazhafiz** [comment]
@jdvr should be good to go after https://github.com/ArturKovacs/trash/pull/1 is merged.

**Comment by jdvr** [comment]
I have subscribe to the issue. Once is merged I will go ahead with this. Thanks.

**Comment by jdvr** [comment]
The task has been merged and the [crate](https://crates.io/crates/trash) has a new version.

I will try to draft something this weekend and create a PR.

**Comment by jonathandturner** [comment]
Sounds great

**Comment by jdvr** [comment]
Hi, I have made some progress. I will tested it on MacOs this afternoon and create a PR if everything goes well.

Demo.

[![asciicast](https://asciinema.org/a/T4FePfmfjPQ2s3v5WQuGZGlH1.svg)](https://asciinema.org/a/T4FePfmfjPQ2s3v5WQuGZGlH1)

**Comment by jonathandturner** [comment]
Fixed by #854 (thanks @jdvr!)
