### ISSUE TITLE
Is it possible to use nu command from another shell?

### ISSUE THREAD

**Issue by aborruso** [nushell/nushell#1941]
Hi,
probably this is a stupid question: if I'm in example I use zsh, is it possible tu run something like `nu ls | pivot`? If yes, how to do it?

Thank you

**Comment by thegedge** [comment]
Yep, you can use `-c` to use nushell to run a pipeline:

```
$ nu -c 'ls | pivot'
```

Two other ways are via stdin (I think this works):

```
$ echo 'ls | pivot' | nu
```

or in a script:

```
$ cat myscript.nu
ls | pivot

$ nu myscript.nu
```

**Comment by aborruso** [comment]
Great, thank you
