### ISSUE TITLE
Linux installation using pre-built binaries

### ISSUE THREAD

**Issue by aborruso** [nushell/nushell#1942]
Hi,
is it ok to install it using Linux pre-built binaries?
Unzip it and put the output in the PATH is it the right way to install it via binaries? 

I'm asking it because in the documentation there is not this kind of installation for Linux and maybe it is not recommended.

Thank you

**Comment by fdncred** [comment]
I think the key on any operating system is to have all the executables in your path and it should work. We recommend certain ways to install but there are certainly other ways, as you suggest.

**Comment by aborruso** [comment]
Thank you very much @fdncred 

Can I do a PR and add this way also for a generic linux disto?

**Comment by fdncred** [comment]
Sure. Thanks.
