### ISSUE TITLE
Licenses we use

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1948]
**Describe the bug**
We currently don't know the licenses we transitively use. It'd be good to have a way to collect these for the current snapshot of Nu. 

**To Reproduce**
1. Build Nu
2. Sit in confusion wondering what the actual license is for that binary

**Expected behavior**
Having a list of the licenses used so that someone who consumes Nu for other projects knows the actual licenses that binary is built with.

**Comment by jonathandturner** [comment]
Looks like there are some `cargo` plugins for this, like: https://crates.io/crates/cargo-about

**Comment by fdncred** [comment]
Summary from my local fork. At least it's a good inventory to start with. Now, we just need to decide what is good and what is bad, if any.
![Screen Shot 2020-06-07 at 12 48 15 PM](https://user-images.githubusercontent.com/343840/83976111-962c6a80-a8bd-11ea-9e34-0c3c416ee773.PNG)

**Comment by fdncred** [comment]
Windows `less.exe` uses MIT found [here](https://github.com/jftuga/less-Windows/blob/master/LICENSE)

http://www.greenwoodsoftware.com/less/download.html#binaries

**Comment by jonathandturner** [comment]
I think we're good here, and there are ways to query it.
