### ISSUE TITLE
Typechecking the Value stream

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#195]
Just like we do typechecking of parameters now, it might be nice in the future to also be able to say what kind of Values the command expects in the input stream (and also potentially what kind of values it will output)

**Comment by thegedge** [comment]
Is this something beyond our use of signatures, @jonathandturner ?

**Comment by arashout** [comment]
Would it work to have some type of optional method/field on `WholeStreamCommand`?
So you would specify what Value variant the command expects like have it be automatically type-checked that way?

**Comment by thegedge** [comment]
Great idea, @arashout. That could definitely work, but I still think encoding this in the `Signature` is potentially the better solution here. I see two advantages:

1. We can statically analyze a pipeline without even having to construct and feed values through it.
2. We can emit this information in help docs for the command.

We actually already have `input` and `yields` in the `Signature`, but no command currently specifies it. Perhaps we should start there 🙂
