### ISSUE TITLE
User-definable custom keybindings to run arbitrary commands

### ISSUE THREAD

**Issue by HarrisonB** [nushell/nushell#1958]
Bash and other shells allow custom keymappings to run specific programs. E.g. I have <kbd>CTRL</kbd>+<kbd>T</kbd> set up to run a function that pipes `fd` into `fzf`.

It doesn't appear that this is currently possible to configure by an end user.

I'm not sure how this configuration would be managed--it could be a new command (e.g. like `alias`) or saved via `config`.

I don't know if there are any alternatives to this functionality. While many of the things one might want to map to specific keys could be added via inserting more built-in functionality (e.g. #1616), this cannot possibly handle all use-cases.

**Comment by fdncred** [comment]
configurable keybinding is implemented in 0.17. however, i have not tested `skim` with it. Theoretically it should work on non-windows systems. I do not think `fzf` will work though as `rustyline` uses `skim`.

**Comment by jonathandturner** [comment]
I wonder if rustyline would let us configure custom keybindings to call back into Nu. If so, we could call out into skim/fzf in the same way.

**Comment by HarrisonB** [comment]
Perhaps I should re-title this as the goal was execution of arbitrary commands via custom keybindings?

**Comment by fdncred** [comment]
Opened [this ](https://github.com/kkawakam/rustyline/issues/418)just now to see what the rustyline folks will say, or if they have any interest at all.

**Comment by jonathandturner** [comment]
Looks like this is still an issue

**Comment by danjenson** [comment]
This would be great

**Comment by fellnerse** [comment]
Is there an update?

**Comment by kubouch** [comment]
This might be possible with engine-q.

**Comment by fdncred** [comment]
this works, closing.
```
    {
        name: fzf
        modifier: control
        keycode: char_f
        mode: emacs
        event: [
            { edit: { cmd: clear } }
            { edit: { cmd: insertstring value: 'cd (ls | where type == dir | each {|it| $it.name} | str collect (char nl) | fzf | decode utf-8 | str trim)' } }
            { send: enter }
        ]
    }
```

**Comment by 89z** [comment]
Given example doesnt work with current version:

~~~
PS D:\Desktop\nushell-0.60.0> .\nu.exe
Error: nu::shell::unsupported_config_value (link)

  × Unsupported config value
     ╭─[C:\Users\Steven\AppData\Roaming\nushell\config.nu:223:1]
 223 │         event: [
 224 │             { edit: { cmd: insertstring value: 'cd (ls | where type == dir | each {|it| $it.name} | str collect (char nl) | fzf | decode utf-8 | str trim)' } }
     ·             ─────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────
     ·                                                                                      ╰── expected reedline EditCommand, got {cmd: insertstringvalue: cd (ls | where type == dir | each {|it| $it.name} | str collect (char nl) | fzf | decode utf-8 | str trim)}
~~~

**Comment by partiallyordered** [comment]
Current example from the [documentation](https://www.nushell.sh/book/line_editor.html#keybindings), for anyone who finds this later:
```
    keybindings: [
    {
      name: change_dir_with_fzf
      modifier: CONTROL
      keycode: Char_y
      mode: emacs
      event: {
        send: executehostcommand,
        cmd: "cd (ls | where type == dir | each { |it| $it.name} | str join (char nl) | fzf | decode utf-8 | str trim)"
      }
    }
```

**Comment by askeladd123** [comment]
Can a keybinding insert stdout of a command into the shell?

I tried creating this keybinding:
```nu
keybindings: [
    {
      name: get_dir_fzf
      modifier: CONTROL
      keycode: Char_y
      mode: emacs
      event: {
        send: executehostcommand,
        cmd: "[ ~/dir1 ~/dir2 ] | to text | fzf"
      }
    }
]
```

I did the following: 
- insert `cd`
- press `control`+`y`
   - enter *fzf* and get dir
- press `enter`, move to chosed dir

Unfortunately, the output is not inserted. Rather it flashes then disappears.

Is this expected? Is it possible to acheive what I want, aside from using the `InsertString` event?

**Comment by partiallyordered** [comment]
I think what you want is a [user-defined menu](https://www.nushell.sh/book/line_editor.html#user-defined-menus) with a (custom keybinding)[https://www.nushell.sh/book/line_editor.html#menu-keybindings-1].

**Comment by askeladd123** [comment]
I spoke a bit too early. Found out `cmd: "commandline edit --insert ([ ~/dir1 ~/dir2 ] | to text | fzf)"` does what I want. 

@partiallyordered  your example also works great. Only problem is it uses Nushells completer instead of *fzf*, which has fuzzy search.

**Comment by partiallyordered** [comment]
> which has fuzzy search

Funny you mention that. I said "lightly edited"- one of the things I did was remove a comment which said something like "It would be nice if Nushell had an inbuilt fuzzy comparison operator".
