### ISSUE TITLE
Can't start nu if config file is readonly

### ISSUE THREAD

**Issue by nprindle** [nushell/nushell#1963]
**Describe the bug**

If the `config.toml` file is readonly, then nushell fails to start.

**To Reproduce**

1. Create an empty `~/.config/nu/config.toml`
2. Remove write permissions, e.g. `chmod -w ~/.config/nu/config.toml`
3. Try to start `nu`

Sample output:
```
nprin@nprin:~$ nu
Welcome to Nushell 0.15.0 (type 'help' for more info)
Error: ShellError { error: UntaggedRuntimeError { reason: "Permission denied (os error 13)" }, cause: None }
```

**Expected behavior**

`nu` should be able to start normally even if it can't write to the config file. It should throw a warning/error only if `nu` needs to modify the file.

**Configuration (please complete the following information):**

 - OS: NixOS Linux
 - Nu version: 0.15.0
 - Optional features (if any): None

For context, this makes it impossible to manage the config file with something like NixOS's `home-manager`, since such a tool would symlink `~/.config/nu/config.toml` to something in a readonly filesystem like the Nix store. Using such tools, the user would expect to make all configuration changes via that tool, not directly, so not being able to modify the config via `nu` itself would not be a problem.

**Comment by thegedge** [comment]
Sounds like we're trying to write to the config file on boot 🤔
