### ISSUE TITLE
Question in math mode

### ISSUE THREAD

**Issue by larry0220** [nushell/nushell#1964]
nushell version: 0.14.0

❯ = 2 / 2 / 2
0.5

❯ = 2 / 2 / 2 + 1
0.3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333

**Comment by jonathandturner** [comment]
Wow, good catch. A bit embarrassing :)

Looks like we were missing a line that was causing us to forget the last operator we save, so we missed that addition as lower precedence. I've put a fix in #1966
