### ISSUE TITLE
Regression: `ls` without permissions causes error

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#1985]
**Describe the bug**
I fixed some warnings in `ls` as I moved it away from async_stream, and I suspect I broke how `ls` would list files even if the permissions weren't available.

**To Reproduce**
1. `ls` inside a directory with permission restrictions, like C:\Windows on Windows

**Expected behavior**
We should do a full listing and skip or blank-out things we don't have permissions to see

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Windows
 - Nu version (you can use the `version` command to find out): 0.15.1

**Comment by arashout** [comment]
What is the problem?
Mine seems to work okay?

![image](https://user-images.githubusercontent.com/10860860/84825149-d71b3200-afd5-11ea-8ac3-04b1d6e0f308.png)

**Comment by jonathandturner** [comment]
Hmm, I can't repro it. I'll close and re-open if I can find a repro

**Comment by fdncred** [comment]
@jonathandturner `ls -f \Windows`
![image](https://user-images.githubusercontent.com/343840/84826511-a8f31d80-afe8-11ea-8026-5ea939b7688f.png)

**Comment by thegedge** [comment]
Looks like another case of having a `Nothing` when we can't get metadata:

https://github.com/nushell/nushell/blob/49b0592e3c509e4ada038f4cd7088e845305405b/crates/nu-cli/src/data/files.rs#L71-L85

**Comment by jonathandturner** [comment]
As a side thought: we should stuff an empty column in there if it's not available rather than not having the column.  That would allow the table to stay aligned.

**Comment by jonathandturner** [comment]
Lol, what @thegedge said :D

**Comment by fdncred** [comment]
@jonathandturner You closed this. Does that means it's fixed?

**Comment by fdncred** [comment]
I think this was perhaps closed by mistake.

**Comment by arashout** [comment]
I believe this has been resolved with the above PR.
Please Re-open if it's not the case!
