### ISSUE TITLE
Make`sum` a sub-command of `math`

### ISSUE THREAD

**Issue by arashout** [nushell/nushell#1989]
**Describe the bug**
Currently to sum numbers, you call 
`echo [1 2 3] | sum`
However, after this PR: https://github.com/nushell/nushell/pull/1969, there is a `math` command which contains the `min`, `max` and `average` sub-commands.
Used like so:
`echo [1 2 3] | math max`

I think it would make sense to move `sum` to be a `math` sub-command.

**Expected behavior**
`sum` should be a sub-command of `math`, so I could use it like
`echo [1 2 3] | math sum`

You should also update the documentation and add some unit tests

**help**
This task should be a good issue for first time contributors.
You can refer to the sub-commands in `math` to understand what needs to be down and also this PR:   https://github.com/nushell/nushell/pull/1969, which moves `average` under the `math` umbrella.

Feel free to ping me @arashout, if you get stuck and need any help

**Comment by JosephTLyons** [comment]
I could take a crack at this.

**Comment by arashout** [comment]
Sounds good, let me know if you need any help!

**Comment by JosephTLyons** [comment]
> Sounds good, let me know if you need any help!

Thanks, I started this the other day and feel like it isn't far, but I'm stuck a little bit.  Might take me a bit longer to figure a few things out.
