### ISSUE TITLE
Failed to install nu with cargo

### ISSUE THREAD

**Issue by ProgrammingLife** [nushell/nushell#1991]
Trying to install nu with: `cargo install nu` command but failed with the error message:

```
error: reached the type-length limit while instantiating `std::thread::LocalKey::<std::syn...:Vec<nu_protocol::value::Value>>`
    |
    = note: consider adding a `#![type_length_limit="4391720"]` attribute to your crate

error: aborting due to previous error

error: could not compile `nu_plugin_sys`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `nu v0.15.0`, intermediate artifacts can be found at `/tmp/cargo-installBCH9sW`

Caused by:
  build failed
```

What do I do wrong?

**Configuration (please complete the following information):**
 - OS: Linux Mint 19.1
 - Nu: the latest
- Cargo: 1.41.0
- rustc: 1.41.0

**Comment by jonathandturner** [comment]
@ProgrammingLife - you'll need to update your `rustc` to the latest stable version. They recently fixed the limits to make it work better with async Rust code.

**Comment by JosephTLyons** [comment]
@ProgrammingLife, were you able to get Nu installed?

**Comment by JosephTLyons** [comment]
I'm going to go ahead and close this issue for now.  @ProgrammingLife, if you are still having issues installing Nushell through `cargo install nu`, feel free to open up another issue.
