### ISSUE TITLE
Make absolute value subcommand: math abs

### ISSUE THREAD

**Issue by andrasio** [nushell/nushell#2000]
That takes the absolute value of the input. 

Example: `echo [-1 -1] | math abs` => `[1 1]`. This issue is already assigned.

**Comment by bedomax** [comment]
👌

**Comment by fdncred** [comment]
And if you want to add more math enhancements, see the backlog https://github.com/nushell/nushell/projects/2#card-40409628

**Comment by xolve** [comment]
If its still open, would like to work in it.

**Comment by bedomax** [comment]
@andrasio could you assign @xolve ? Thanks.

**Comment by andrasio** [comment]
@xolve Hey, how are we doing?

**Comment by xolve** [comment]
Hey @andrasio, I haven't been able to work on it till now. I see that I can work on it this week. Can we wait some more time on this?

**Comment by andrasio** [comment]
@xolve No problem!
