### ISSUE TITLE
Make mode subcommand: math mode

### ISSUE THREAD

**Issue by andrasio** [nushell/nushell#2001]
`math mode` to get the value that [appears most often](https://en.wikipedia.org/wiki/Mode_(statistics)).

**Comment by amousa11** [comment]
I'd like to take a stab at this

**Comment by fdncred** [comment]
And for more math enhancements, see the backlog https://github.com/nushell/nushell/projects/2#card-40409628

**Comment by andrasio** [comment]
@amousa11 Great! Just assigned it to you.
