### ISSUE TITLE
Incorrect configuration file will crash Nu on startup.

### ISSUE THREAD

**Issue by andrasio** [nushell/nushell#2003]
If a manual change is made in the Nu configuration file that can be located at `echo $nu.config-path` and it's not valid `toml` format, Nu will panic.

We need to report an error instead and let Nu continue working.

**Comment by bedomax** [comment]
👌

**Comment by peterallin** [comment]
This seems to work as requested for me. Running on Ubuntu 20.04, git SHA 7813063c938c6c517aca47afa5f75d081ca42e4c. I get the following message on start up:

  Config could not be loaded.
  Couldn't parse config file:
  expected an equals, found a newline at line 1 column 14

and then get a nu prompt.

**Comment by arashout** [comment]
Resolved with:
https://github.com/nushell/nushell/pull/2077

**Comment by arashout** [comment]
Closing since I believe it is resolved via https://github.com/nushell/nushell/pull/2077.
