### ISSUE TITLE
Rename `math average` to `math avg`

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2009]
**Is your feature request related to a problem? Please describe.**
The current `math average` is a bit long to type.

**Describe the solution you'd like**
 We already abbreviate `math min` and `math max`, so let's abbreviate average also to avg.  This would give us `math avg`.

**Describe alternatives you've considered**
We could keep it the full name and ask people to use aliases. Changing it has two advantages though: it's consistent and easier to type.

**Comment by JosephTLyons** [comment]
What about `math median` then?

**Comment by JosephTLyons** [comment]
Closed by https://github.com/nushell/nushell/pull/2014
