### ISSUE TITLE
cargo test fails with the argument --target

### ISSUE THREAD

**Issue by Philipp-M** [nushell/nushell#2021]
**Describe the bug**

cargo test fails nearly all tests (1 passes), if the target is explicitly given.

**To Reproduce**
`cargo test  --target x86_64-unknown-linux-gnu`

**Expected behavior**
Non failing tests

Currently nixpkgs unstable fails to build using the default `buildRustPackage` `checkPhase`, which uses `--target`.
Here's the context: https://github.com/NixOS/nixpkgs/pull/90714/files#r443044501

And a pastebin trying to build it on current NixOS unstable master: https://pastebin.com/yRjpS2Fz

**Comment by pwnorbitals** [comment]
Is it fixed now ?

**Comment by FollieHiyuki** [comment]
Hi. I have the same issue when trying to build nushell on Void Linux

**Comment by jonathandturner** [comment]
Are you cross compiling to a target different than the one you're running on? If so the tests may fail, as we run external commands as part of the test, and these externals are built for the target.

**Comment by FollieHiyuki** [comment]
In my case running `cargo test --release` works, while `cargo test --release --target x86_64-unknown-linux-musl` doesn't, and I'm building nushell on a Voidlinux-x86_64-musl machine.

**Comment by Philipp-M** [comment]
Yes for me it's also (still) the same error but with NixOS and the target being `x86_64-unknown-linux-gnu` on a machine with the same architecture/libc.
