### ISSUE TITLE
enh: Split-column support for whitespace vertically aligned data

### ISSUE THREAD

**Issue by rbtcollins** [nushell/nushell#2029]
**Is your feature request related to a problem? Please describe.**
I'd like to bring Windows 'netstat' data into nu, but haven't found a way so far. The issue I'm having is that split-column seems to want a 'char' to split on, but the separate for netstat is a variable number of space characters. So a regex like " +" would be suitable, but [a] character isn't.

**Describe the solution you'd like**
Anything that lets me process netstat output.

Two sample outputs:
```
netstat -aon -p tcp

Active Connections

  Proto  Local Address          Foreign Address        State           PID
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING       2668
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING       4
```
and
```
netstat -ao -p tcp -b

Active Connections

  Proto  Local Address          Foreign Address        State           PID
  TCP    0.0.0.0:135            lifelesstr2:0          LISTENING       2668
  RpcSs
 [svchost.exe]
  TCP    0.0.0.0:445            lifelesstr2:0          LISTENING       4
 Can not obtain ownership information
  TCP    0.0.0.0:2179           lifelesstr2:0          LISTENING       6648
 [vmms.exe]
```

This bug won't fully address the second case, I don't think, but it will address the first.

**Describe alternatives you've considered**

**Additional context**

**Comment by fdncred** [comment]
@rbtcollins Here's a painful start on the first one.
```
> netstat -aon -p tcp | lines | skip 3 | parse --regex "(?P<Proto>[A-Z].+)\s+(?P<LocalAddress>[0-9]{0,3}\.[0-9]{0,3}\.[0-9]{0,3}\.[0-9]{0,3}:[0-9]{1,5})\s+(?P<ForeignAddress>[0-9]{0,3}\.[0-9]{0,3}\.[0-9]{0,3}\.[0-9]{0,3}:[0-9]{1,5})\s+(?P<State>[A-Z].+)\s+(?P<PID>[0-9]{1,5})"
```

**Comment by jonathandturner** [comment]
I had an idea for how to do this the other day, but hadn't had a chance to implement it.

The algorithm goes something like this:
* For the first line, find where all the spaces are
* Then, for each line after the first line, make sure there's a space in this line in the same place. If not, remove it.
* At the end, we should know where there are spaces that fall in the same places in all the rows

From there, take this map of where the spaces are, and extract out the column data.

**Comment by rbtcollins** [comment]
Thanks @fdncred I hadn't found parse, I guess I need to read the book more carefully :/. But even so -  the mental model of split-colums is I think rather better than a full language description in *most* cases like this.

@jonathandturner I think the second case will need the full parse support actually - variable number of lines per record means we can't just hack every Nth line to be folded with the previous line to make it into a column and then do column splitting.

**Comment by fdncred** [comment]
@rbtcollins Here's another run at it, `netstat -aon -p tcp | lines | skip 4 | split column "   " -c Proto Local_Address Foreign_Address State PID | trim`. The `secret sauce` is to split on 3 spaces and use `-c` to `--collapse-empty` columns, then name the column headers. Definitely easier to read than the regex one.

Output
```
─────┬───────┬─────────────────────┬─────────────────────┬─────────────┬───────
  #  │ Proto │    Local_Address    │   Foreign_Address   │    State    │  PID
─────┼───────┼─────────────────────┼─────────────────────┼─────────────┼───────
  0  │ TCP   │ 0.0.0.0:135         │ 0.0.0.0:0           │ LISTENING   │ 1308
  1  │ TCP   │ 0.0.0.0:445         │ 0.0.0.0:0           │ LISTENING   │ 4
  2  │ TCP   │ 0.0.0.0:623         │ 0.0.0.0:0           │ LISTENING   │ 17592
  3  │ TCP   │ 0.0.0.0:902         │ 0.0.0.0:0           │ LISTENING   │ 5812
  4  │ TCP   │ 0.0.0.0:912         │ 0.0.0.0:0           │ LISTENING   │ 5812
  5  │ TCP   │ 0.0.0.0:1536        │ 0.0.0.0:0           │ LISTENING   │ 1008
  6  │ TCP   │ 0.0.0.0:1537        │ 0.0.0.0:0           │ LISTENING   │ 896
  7  │ TCP   │ 0.0.0.0:1538        │ 0.0.0.0:0           │ LISTENING   │ 1864
  8  │ TCP   │ 0.0.0.0:1539        │ 0.0.0.0:0           │ LISTENING   │ 1872
  9  │ TCP   │ 0.0.0.0:1540        │ 0.0.0.0:0           │ LISTENING   │ 3336
 10  │ TCP   │ 0.0.0.0:1544        │ 0.0.0.0:0           │ LISTENING   │ 5344
 11  │ TCP   │ 0.0.0.0:1545        │ 0.0.0.0:0           │ LISTENING   │ 3300
 12  │ TCP   │ 0.0.0.0:1547        │ 0.0.0.0:0           │ LISTENING   │ 984
 13  │ TCP   │ 0.0.0.0:1579        │ 0.0.0.0:0           │ LISTENING   │ 5708
 14  │ TCP   │ 0.0.0.0:2179        │ 0.0.0.0:0           │ LISTENING   │ 2772
 15  │ TCP   │ 0.0.0.0:3389        │ 0.0.0.0:0           │ LISTENING   │ 1632
 16  │ TCP   │ 0.0.0.0:4502        │ 0.0.0.0:0           │ LISTENING   │ 5708
 17  │ TCP   │ 0.0.0.0:5040        │ 0.0.0.0:0           │ LISTENING   │ 9004
 18  │ TCP   │ 0.0.0.0:5357        │ 0.0.0.0:0           │ LISTENING   │ 4
 19  │ TCP   │ 0.0.0.0:16992       │ 0.0.0.0:0           │ LISTENING   │ 17592
 20  │ TCP   │ 0.0.0.0:22000       │ 0.0.0.0:0           │ LISTENING   │ 42776
 21  │ TCP   │ 127.0.0.1:1037      │ 127.0.0.1:4502      │ ESTABLISHED │ 7320
 22  │ TCP   │ 127.0.0.1:1447      │ 127.0.0.1:34141     │ ESTABLISHED │ 42516
 23  │ TCP   │ 127.0.0.1:1546      │ 127.0.0.1:5354      │ ESTABLISHED │ 5640
 24  │ TCP   │ 127.0.0.1:1616      │ 127.0.0.1:5354      │ ESTABLISHED │ 5640
 25  │ TCP   │ 127.0.0.1:1625      │ 127.0.0.1:27015     │ ESTABLISHED │ 12788
 26  │ TCP   │ 127.0.0.1:4502      │ 127.0.0.1:1037      │ ESTABLISHED │ 5708
```

**Comment by rbtcollins** [comment]
Yeah I think this is still a valid request

**Comment by rbtcollins** [comment]
comment below

**Comment by fdncred** [comment]
closing this as we have:
* `from ssv`
* `detect columns`
* `split column " " -c`
* `parse`
