### ISSUE TITLE
Math precision & human readable numbers

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2033]
**Describe the bug**
I wouldn't necessarily call this a bug but maybe we should think about adding a precision flag and a human readable number flag, that isn't summarized, or configuration point so we don't have results like below.

**To Reproduce**
```
~/Desktop
06/22/2020 08:20:11 ❯ ls | to json | from json | get size | math avg
1658039.590909090909090909090909090909090909090909090909090909090909090909090909090909090909090909091
```

**Expected behavior**
It would be nice seeing a human readable number with precision, assuming it's defined somewhere, like `1,658,039.59`
Perhaps:
```
~/Desktop
06/22/2020 08:20:11 ❯ ls | to json | from json | get size | math avg --precision 2 --human
1,658,039.59
```

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Windows 10 2004
 - Nu version (you can use the `version` command to find out): latest master
 - Optional features (if any): features=stable

**Comment by JosephTLyons** [comment]
Very cool idea.  This could be useful for the `--human` flag:

https://crates.io/crates/num-format

**Comment by fdncred** [comment]
@JosephTLyons Nice crate. I do think we need `--human` in several places probably. Obviously, anywhere it's outputting numbers I think there should be a flag. Although, you don't want to automatically do the `human` thing because we can't be certain that someone's output isn't someone else's input via pipe.

Also, we'd need to get the localized character for digit separation. Oh wait, your crate suggestion already takes that into account. Cool!

**Comment by bailey-layzer** [comment]
Would it make sense to implement this as a command? That way it could be used for any decimal output without having to add `--human` to existing/future commands (plus math expressions), and could be expanded to other number formatting.

**Comment by fdncred** [comment]
I'm up for wherever it fits best and can be used with every place numbers are used. I assigned it to you @bailey-layzer. I'd like to see `precision` and `human` implemented but if you only want to work on one of them, that's fine too. Thanks for the help!

**Comment by JosephTLyons** [comment]
> Would it make sense to implement this as a command? That way it could be used for any decimal output without having to add `--human` to existing/future commands (plus math expressions), and could be expanded to other number formatting. Either way, I'd be interested in taking this on.

I was sort of thinking the same with it possibly being a command, so it could be used everywhere without it being re-implemented for each command.

**Comment by bailey-layzer** [comment]
I'm wrapping up `human` and `precision` as commands but had a thought - what if they were combined into something like `print`? That would leave room to expand the command to other types of output and/or fancier formatting.

**Comment by fdncred** [comment]
I'd rather have `human` and `precision` landed first and then if we want to tweak it into `print` we can later. `print` also has a connotation of printing to a printer. I guess I'm down with `some_alternate_name_to_print` if it has `--human` and `--precision` as arguments.
