### ISSUE TITLE
Coercion error between bytes and integer

### ISSUE THREAD

**Issue by johnterickson** [nushell/nushell#2036]
**Describe the bug**
I can't do basic math between file size and integers because there isn't coercion.

**To Reproduce**
```
ls **/* | where type == "File" | = $it.size / 1024
```

**Expected behavior**
`size` is coerced to `integer`

https://discordapp.com/channels/601130461678272522/614593951969574961/724675622030409768

**Comment by jonathandturner** [comment]
`compute_values` in crates/nu-cli/src/data/value.rs needs a few more cases.

The one above is that we need to add a case for (Bytes, Int). I think multiple and divide make sense here.

Optionally: We might also want to add a case for (Bytes, Bytes) that allow you to divide, which would give you a plain decimal as a result (or, if you get fancy, use the same "divide and if it's a whole number, return an int" like we do with divide of (Int, Int).

**Comment by utam0k** [comment]
Can I try this issue?

**Comment by jonathandturner** [comment]
@utam0k sure! It's yours

**Comment by RedlineTriad** [comment]
This can probably be closed, but it seems #2160 didn't have a `close` or `fixes` before the PR number so it didn't get auto-closed.

**Comment by jonathandturner** [comment]
@RedlineTriad good catch.
