### ISSUE TITLE
NuShell Crash on Ctrl-C

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2038]
**Describe the bug**
In Windows, when I hit `up arrow` and then `ctrl+c` nushell crashes with:
```
thread 'main' panicked at 'expect_string assumes that the value must be a string', crates\nu-protocol\src\value.rs:135:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

[process exited with code 101]
```

**To Reproduce**
1. Start nu.exe
2. Hit up arrow to retrieve last command from history
3. Hit Ctrl-C

**Expected behavior**
I expect it to cancel the current command, which isn't running  yet, and return me to a new prompt without any text.

**Screenshots**
N/A

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Windows 10 2004
 - Nu version (you can use the `version` command to find out): 0.15.1 from master
 - Optional features (if any): stable

**Comment by avrong** [comment]
Having the same issue just pressing Ctrl+C in Windows Terminal after start and when running a command.

<img width="500" src="https://user-images.githubusercontent.com/6342851/90338784-c2b6de00-dff4-11ea-992c-3d3e87660513.png">

**Comment by fdncred** [comment]
Happens in mac too with 0.18.2

**Comment by thegedge** [comment]
Doesn't happen for me.

I have basically no configuration. @fdncred I know you have a custom prompt set up. What happens if you remove the prompt configuration?

**Comment by fdncred** [comment]
Makes no difference. With prompt commented out or not. I've tested in Linux/Mac/Windows in these environments.
Linux = Windows Terminal WSL2
Mac = iterm2
Windows = Windows Terminal
Windows = cmd.exe
I start nushell, once it starts and is waiting for me, I hit ctrl-c and it pukes.
```
C:\Users\username\source\repos\forks\nushell(main)>
thread 'main' panicked at 'expect_string assumes that the value must be a string', crates\nu-protocol\src\value.rs:123:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

[process exited with code 101]```
