### ISSUE TITLE
Piping nu command to output has issues

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#2041]
**Describe the bug**
When calling a nu command as a bash command, then piping the output to a file, many things are included in the output that won't work in a file.  There is extra data surrounding the values.  Also the tables sometimes get horizontally truncated with the `...` symbols.

**To Reproduce**
1. run `nu -c ls > output.txt` inside of your terminal

```txt
────┬───────────────────────────┬──────┬────────┬───────────────
 [32m[1m# (B[m │ [32m[1mname                     (B[m │ [32m[1mtype(B[m │ [32m[1msize  (B[m │ [32m[1mmodified(B[m 
────┼───────────────────────────┼──────┼────────┼───────────────
 [32m[1m 0(B[m │ Applications             (B[m │ Dir (B[m │  160 B(B[m │ 2 months ago(B[m 
 [32m[1m 1(B[m │ Books                    (B[m │ Dir (B[m │  192 B(B[m │ 1 month ago(B[m 
 [32m[1m 2(B[m │ Desktop                  (B[m │ Dir (B[m │  672 B(B[m │ 6 secs ago(B[m 
 [32m[1m 3(B[m │ Documents                (B[m │ Dir (B[m │  256 B(B[m │ 2 months ago(B[m 
 [32m[1m 4(B[m │ Downloads                (B[m │ Dir (B[m │  224 B(B[m │ 5 hours ago(B[m 
 [32m[1m 5(B[m │ Dropbox                  (B[m │ Dir (B[m │  480 B(B[m │ 1 month ago(B[m 
 [32m[1m 6(B[m │ GameMakerStudio2         (B[m │ Dir (B[m │   96 B(B[m │ 2 months ago(B[m 
 [32m[1m 7(B[m │ Library                  (B[m │ Dir (B[m │ 2.4 KB(B[m │ 2 weeks ago(B[m 
 [32m[1m 8(B[m │ Movies                   (B[m │ Dir (B[m │  128 B(B[m │ 7 months ago(B[m 
 [32m[1m 9(B[m │ Music                    (B[m │ Dir (B[m │  192 B(B[m │ 7 months ago(B[m 
 [32m[1m10(B[m │ Online Courses           (B[m │ Dir (B[m │  128 B(B[m │ 10 months ago(B[m 
 [32m[1m11(B[m │ Pictures                 (B[m │ Dir (B[m │  192 B(B[m │ 3 months ago(B[m 
 [32m[1m12(B[m │ Programming              (B[m │ Dir (B[m │  832 B(B[m │ 2 months ago(B[m 
 [32m[1m13(B[m │ Public                   (B[m │ Dir (B[m │  128 B(B[m │ 7 months ago(B[m 
 [32m[1m14(B[m │ School Related           (B[m │ Dir (B[m │  128 B(B[m │ 4 years ago(B[m 
 [32m[1m15(B[m │ Software Licenses        (B[m │ Dir (B[m │   96 B(B[m │ 3 years ago(B[m 
 [32m[1m16(B[m │ TI-84 Plus Silver Edition(B[m │ Dir (B[m │  160 B(B[m │ 2 years ago(B[m 
 [32m[1m17(B[m │ Tax Returns              (B[m │ Dir (B[m │  128 B(B[m │ 1 week ago(B[m 
 [32m[1m18(B[m │ Work Related             (B[m │ Dir (B[m │  256 B(B[m │ 3 weeks ago(B[m 
 [32m[1m19(B[m │ github                   (B[m │ Dir (B[m │  384 B(B[m │ 10 months ago(B[m 
 [32m[1m20(B[m │ output.txt               (B[m │ File(B[m │    0 B(B[m │ 0 secs ago(B[m 
────┴───────────────────────────┴──────┴────────┴───────────────
```
Check the raw version of this ^, it didn't render correctly here

**Expected behavior**
I think when piping output to a file, we can entirely turn of the table width truncation thing, since the file can be scrolled horizontally if the table is too wide.  I also think that all extra data that gets inserted should be omitted.

**Screenshots**

**Configuration (please complete the following information):**
 - macOS 10.15.5
 - 0.15.0

**Comment by fdncred** [comment]
That `...` drives me crazy.  In case you didn't realize it, that funky text is the ANSI escape codes that create color. I agree, color should be stripped on a `>`, or `>>`, or maybe `tee`, or maybe `|`. And the `...` should be removed altogether and auto-pivoted, which I tried to do but that stinking `...` still gets in the way. :(

**Comment by jonathandturner** [comment]
Yeah, what we should be doing is to check if stdout is being redirected, and if so, to not output tables with ansi.

**Comment by JosephTLyons** [comment]
> That `...` drives me crazy. In case you didn't realize it, that funky text is the ANSI escape codes that create color. I agree, color should be stripped on a `>`, or `>>`, or maybe `tee`, or maybe `|`. And the `...` should be removed altogether and auto-pivoted, which I tried to do but that stinking `...` still gets in the way. :(

I sort of figured it was the coloring data, but wasn't sure.

**Comment by fdncred** [comment]
we recently added a feature to strip coloring from tables for non-ttys. the same technology could be adapted as a command line parameter for nushell. something like `nu --no-color -c 'ls'`. i think it would be pretty easy.

**Comment by fdncred** [comment]
I believe this is fixed on the latest main branch. please reopen if it isn't.
