### ISSUE TITLE
Automating the Nushell release process

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2042]
Below are the steps we do for the Nushell release process. These are currently done manually, which is error-prone and time-consuming, and we'd like to automate these steps as much as possible.

Below you'll see `<version>` as the stand-in for the version to be released. For example, `0.15.0`.

## Draft release on GitHub

* create a draft release for the upcoming release on GitHub
* name the release "`<version>` Release"
* set the release tag to `<version>`
* copy the text from the previous release, updating links to what will be the new blog url, and new links to the release

## Windows

In a Windows image:
* git pull 
* cargo build --release --all --features=stable
* create directory:
  * `nu_<version>_windows\nushell_<version>`
* copy nu.exe and all nu_plugin_*.exe into the directory
* copy our release README into the directory
* copy the "less.exe" into the directory
* zip as `nu_<version>_windows.zip`
* add the zip to the github draft release above

## Linux

In a Linux image:
* git pull
* cargo build --release --all --features=stable
* create directory:
  * `nu_<version>_linux\nushell_<version>`
* copy nu and all nu_plugin_* into the directory 
* copy our release README into the directory
* copy the linked openssl into the directory
* tar gzip as `nu_<version>_linux.tar.gz`
* add the zip to the github draft release above

## macOS

In a macOS image:
* git pull
* cargo build --release --all --features=stable
* create directory:
  * `nu_<version>_macOS\nushell_<version>`
* copy nu and all nu_plugin_* into the directory 
* copy our release README into the directory
* zip as `nu_<version>_macOS.zip`
* add the zip to the github draft release above

## Crates.io

Publish these crates to crates.io, using this order:

* crates/nu-build: cargo publish
* crates/nu-source: cargo publish --no-verify 
* crates/nu-errors: cargo publish --no-verify
* crates/nu-protocol: cargo publish --no-verify
* crates/nu-parser: cargo publish
* crates/nu-value-ext: cargo publish --no-verify
* crates/nu-plugin: cargo publish --no-verify
* crates/nu-test-support: cargo publish --no-verify
* `creates/nu_plugin_*`: cargo publish
* crates/nu-table: cargo publish
* crates/nu-cli: cargo publish
* `<root>`: cargo publish

## Publish blog post

This step can be done manualy

## Publish GitHub release

Turn the release from draft to published.

**Comment by charlespierce** [comment]
This looks pretty close to what we do for Volta, I can probably get a good start on most of it. I don't have any experience with GH Actions' secrets stuff, so I'm not sure how the `cargo publish` step will work. I believe you could store the token as a secret on the Repo, then fetch it in the action and run `cargo login` using it, then follow up with a script that does `cd <dir> && cargo publish` for each crate you're trying to publish.

A couple of follow-up questions:

1. For the Linux build, is there a specific Linux flavor / version you use, for compatibility with things like `libc`? Or is it all statically linked / not needing significant backwards compatibility?

2. For the archives, do they include a directory, or are all of the relevant files in the root of the archive?

3. When you say "copy the release README", is that referring to the `README.md` file in the root of the project, or is that a different file?

**Comment by jonathandturner** [comment]
@charlespierce -

1. I've used both Manjaro and Pop! OS in the past. I'm sure an Ubuntu would be perfectly okay here. 

2. I've been including the directory in the archive. You might want to check the archives in the latest release to see if I got the names right. I've been just copying the directories and filling them with the latest release assets. 

3. There's a small text file I've been including in the bundle. If you look inside one of the releases, you'll see a text file beside the binaries. It just tells you to copy this into your path. 

Which reminds me:

* Should we consider creating .deb, .dmg, and wix-based Windows installs? This seems like something people might like to have. I know @fdncred was looking into Wix earlier today.

**Comment by fdncred** [comment]
We're still validating the msi that Wix creates but from what I can tell, it seems done-ish. The missing part is how to automate with CI, i.e. 
1. download the wix toolkit from https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
2. download `less` from https://github.com/jftuga/less-Windows/releases/download/less-v562.1/less.exe and put it in the wix folder
3. run `cargo install cargo-wix`
4. run `cargo wix`
5. put the msi in release assets.

I think that's it.

**Comment by charlespierce** [comment]
@fdncred I'm not sure about the `less` step, but the images provided by GH Actions already have the WiX Toolset available. On Volta we use `cargo wix` to create the installer and all we've needed to do is run `cargo install cargo-wix` and then `cargo wix` to create the MSI file.

@jonathandturner Great, I'll take a look at the last few releases and see if I can come up with something that matches.

**Comment by fdncred** [comment]
Great! Since GH Actions already have Wix then it should be easy. I'm guessing a `curl` command could download `less` and put it somewhere. Wherever that is, we just need to update the wix xml to point to that folder. Then all the exes will be contained in the msi.

**Comment by fdncred** [comment]
@jonathandturner caught that starship is not being included in the build so we'll have to tweak the wix part to something like this.

0. my plan is to commit `less.exe` to the source tree in the `wix` folder so we don't have to download anything but i haven't discussed this with anyone yet.
1. `cargo install cargo-wix`
2. `cargo build` is already ran previously so we don't need to run it again.
3. `cargo wix --no-build` - i think this just takes the appropriate bins that are in the `target\release` folder
4. add to assets

**Comment by charlespierce** [comment]
Created #2048 (nice power of 2!) with a GH Workflow set up to create a Release whenever a tag in the form of a version is pushed into the repo.

**Comment by fdncred** [comment]
Sweet! Thanks @charlespierce !!!

**Comment by arashout** [comment]
Can this task be closed with the merging of @charlespierce ?
Are are we creating an additional PR for the wix functionality and actual publishing before closing?

**Comment by jonathandturner** [comment]
@arashout - I think we're good now. Wix is in and we successfully did a release with automation. @fdncred is working on some updates, but we can file other issues for those and any additional features we want to add. 

For now, I'll probably keep doing the crate release by hand, though we may want to write a script to make that easier (another thing we could write a separate issue for)

Going ahead and closing. Thanks all!
