### ISSUE TITLE
Move from glibc to musl for more stable binary releases 

### ISSUE THREAD

**Issue by charleschege** [nushell/nushell#2044]
there is an issue that I raised, on discord chat, where with every new release of nushell, once I download the release binaries from Github they don't work because of compiling with a different version of glib.  This apparently can be solved by using musl as a replacement for glibc and statically linking it. Read the article below for more information. 
https://saarw.github.io/dev/2020/06/18/shipping-linux-binaries-that-dont-break-with-rust.html

**Comment by svartalf** [comment]
Switching to `musl` can affect dependencies used by Nu, I personally can say that `heim` crate (used for `sys` and `ps` plugins) does not provides any guarantees for `-musl` targets right now; you can expect it to compile at most, but that's basically it.

Another notable issue is that `sys | get host.users` command will stop working for `musl` builds, see https://wiki.musl-libc.org/faq.html#Q:-Why-is-the-utmp/wtmp-functionality-only-implemented-as-stubs?

**Comment by thegedge** [comment]
I can see a couple of options here:

1. Provide a musl build (as well as a glibc build) in the release, making sure we mention that there will likely be issues (like the one @svartalf mentioned above).
2. Provide documentation on how a user can manually build without the correct glibc. This will primarily impact Linux users, I think, and I believe they are pretty familiar with having to manually build software 😬

**Comment by charleschege** [comment]
How about creating binaries using a glibc version that has been available to all LTS releases of Debian and Ubuntu, like Ubuntu 20.04 and 18.04.
this could be helpful unlike the current release that jturner had said is compiled on manjaro Linux and from my knowledge, manjaro uses the newer releases of software probably including glibc

**Comment by thegedge** [comment]
@charleschege If that would also solve this issue, sounds like a great solution. Targeting LTS releases seems like a good thing to be doing.

**Comment by jonmast** [comment]
In my (limited) experience binaries built on older versions of glibc run fine on newer distros, it's the reverse that causes problems. The new automated build in https://github.com/nushell/nushell/pull/2048 is set up to use "ubuntu-latest", which is currently 18.04, so this may be largely solved now?

Providing musl builds doesn't seem worth the overhead given the drawbacks mentioned, to my knowledge the only compatibility issues with glibc are for precompiled binaries so users with more esoteric configurations can always build from source.

**Comment by charleschege** [comment]
Thanks for making this possible. Version 0.16 now works out of the box with Linux binaries downloaded from Github releases.
