### ISSUE TITLE
`ls` should be more forgiving

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2046]
**Describe the bug**
Seeing issues in Windows where `ls` doesn't give the full listing.

**To Reproduce**
1. `ls` from C:\

**Expected behavior**
Even if there are issues with permissions, it's okay to abbreviate that record and keep going.

**Screenshots**
![image](https://user-images.githubusercontent.com/547158/85527825-56a4a300-b65f-11ea-9d49-1a9993c5cd9c.png)

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Windows 10
 - Nu version (you can use the `version` command to find out): 0.15.1

**Comment by thegedge** [comment]
Could we tag rows with some kind of "error" metadata? The table view code could read that metadata and decide to perhaps color it differently, or do something to indicate to the user that the row failed in some capacity.

**Comment by fdncred** [comment]
Piling on here. These issues are somewhat related #1929, #1985 #1785 (closed by related)

**Comment by arashout** [comment]
If all we want to do is swallow the error, sort of like what we already do for this type of permissions issue:
```rust
  Err(e) => {
                    if e.kind() == std::io::ErrorKind::PermissionDenied {
                        None
                    } else {
                        return Some(Err(e.into()));
                    }
                }
```
Then it is a easy fix. Just need a `match` statement instead of `if` (Also would be a "good first issue"). @jonathandturner 

However @thegedge suggests seems like a more general solution that could be useful in other areas

**Comment by jonathandturner** [comment]
Looks like the original issue here is fixed and as well as a set of related issues.
