### ISSUE TITLE
Autocomplete does not work with sudo 

### ISSUE THREAD

**Issue by charleschege** [nushell/nushell#2047]
For example when I want to autocomplete nautilus file manager,
```sh
$ sudo naut #press tab here
```
If I press tab to autocomplete `naut` to `nautilus` it won't work. But autocomplete without `sudo` works fine

**Comment by MarkuBu** [comment]
tried this with nu 0.31.0 on Arch. Same issue. Tried to run `sudo pacman -S`, but doesn't autocomplete any package

**Comment by charleschege** [comment]
Still active

**Comment by jbaiter** [comment]
Still having this problem, is this a known bug/limitation?

**Comment by charleschege** [comment]
Yes this is still an issue. Nu can't handle Autocomplete of a `sudo <command>` enven though it can handle `<command>` .

**Comment by sholderbach** [comment]
Should mainly be resolved by #8094
