### ISSUE TITLE
Add other uuid versions as flags on random uuid

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#2051]
**Is your feature request related to a problem? Please describe.**
[This PR](https://github.com/nushell/nushell/pull/2050) added a `random` command and a `uuid`subcommand.  The uuid subcommand only adds in uuid4, but there exists 5 other versions of uuid, and each one works differently than the last and uses a different method to create the uuid.  By default, were using uuid4, but others may have different needs.

**Describe the solution you'd like**
Add flags on the uuid subcommand for each version, but default to uuid4 if no flags are used.

I wouldn't mind picking this up, since it is fresh in my mind, so long as the maintainers were alright with it.

**Comment by JosephTLyons** [comment]
After looking further into what the other uuid versions off, I don't think it makes sense to add them to nushell.  Apparently version 2 is skipped in many librarys because it isn't secure.. it is not here in the rust crate either:

https://docs.rs/uuid/0.8.1/uuid/

The other uuid versions take multiple bits of input, such as some data used used for a "namespace" and information used by the hashing functions.  I think this would be overkill just to get a different variation on the uuid, but if others disagree, it can be added.  I think this can probably be closed, unless someone else objects.

**Comment by thegedge** [comment]
I'm not opposed to adding in the others. Do you have a use case in mind?

**Comment by JosephTLyons** [comment]
> I'm not opposed to adding in the others. Do you have a use case in mind?

I don't have a specific use case, I only ever use uuid4 since it doesn't require data to be passed in, I originally suggested adding in the others just in case other individuals preferred them, but I don't know how feasible it is now, considered the fact the other uuid versions require multiple inputs, not just one.
