### ISSUE TITLE
Add other random subcommands

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#2052]
**Is your feature request related to a problem? Please describe.**
[This PR](https://github.com/nushell/nushell/pull/2050) added a `random` command and a `uuid` subcommand.  I originally mentioned having a `number` subcommand, but @jonathandturner mentioned having a `bool`, `decimal` and `integer` subcommands, which makes more sense to me, personally.  These should probably be made into separate issues, but I wanted for others to have a chance to discuss any ideas they might have before writing each one out.

**Describe the solution you'd like**
Add `bool`, `decimal`, and `integer` subcommands.  We should probably consider what each command does on its own by default (its min range, max range, and whether it is signed or not), then consider what flags to add to adjust those default values.

I was thinking:

- [X] `random bool` https://github.com/nushell/nushell/pull/2061
    - A bias flag to influence the likelihood of a true occurring, `random bool --true-prob 0.73` (this is sort of just a fun suggestion, but others may find it totally worthless and think it should not be put in, which is fine)
- [X] `random integer` https://github.com/nushell/nushell/pull/2489
- [ ] `random decimal`

**Comment by bailey-layzer** [comment]
`random normal` would also be pretty cool (or maybe sampling from common distributions would be better as a separate command).

**Comment by jonathandturner** [comment]
@bailey-layzer - sounds interesting. what kind of things did you have in mind?

**Comment by bailey-layzer** [comment]
I didn't have a use case in mind, and on further reading it would be less straightforward than I'd thought. Honestly to get much out of it you'd need a lot of other functionality that's probably better left in statistical programming.

**Comment by jonathandturner** [comment]
@bailey-layzer - Nu should be usable for data processing, too, so (at least in theory) it will grow some statistics functionality over time. Would be curious to learn more about the gaps there. Mostly just waiting for people with the background in it.

**Comment by smaydew** [comment]
New to Rust, but I'd like to jump in and get my feet wet. This seems like a good one to start with if nobody has any objections.

**Comment by thegedge** [comment]
It's yours, @smaydew.

**Comment by JosephTLyons** [comment]
Absolutely, I think it was @jonathandturner who suggested some of these subcommands so there might be some implementation details for flags and default values.

**Comment by smaydew** [comment]
@thegedge @jonathandturner I have some questions about implementation of the `random integer` sub-command. I'm trying to get connected to #developing on Discord, but can't find that group, or usernames. I've setup Discord and my tag is smaydew#6993 

Is that the best place to discuss and get help, or is working here in the issue itself better?

**Comment by jonathandturner** [comment]
@smaydew those sound like a good starting set.

You could also allow people to pass in a range:

```
random integer 3..10
```

**Comment by smaydew** [comment]
Yep, that is on the list too.

**Comment by smaydew** [comment]
Yes, it's been implemented.
