### ISSUE TITLE
Problems with redirection when handling $() with `tty`

### ISSUE THREAD

**Issue by BKDaugherty** [nushell/nushell#2069]
**Describe the bug**

For some reason, when using `$(tty)` I get an output of nothing.

```
/Users/brendond> echo $(pwd)
/Users/brendond
/Users/brendond> echo $(tty)
/dev/ttys002
───┬──
 0 │
───┴──
```

This is most visible when doing something like this command

```
/Users/brendond> echo $nu.env | insert GPG_TTY $(tty) | config --set_into env
/dev/ttys002
──────┬──────────────────
 env  │ [row 34 columns]
 path │ [table 14 rows]
──────┴──────────────────
/Users/brendond> config | get env.GPG_TTY
<Nothing>
/Users/brendond>
```

**To Reproduce**
1. `echo $nu.env | insert GPG_TTY $(tty) | config --set_into env`

**Expected behavior**
Instead of printing $(tty), and storing "<Nothing>", I would expect the above command to store the environment variable GPG_TTY.

**Screenshots**

**Configuration (please complete the following information):**
 - OS (e.g. Windows):
 - Nu version (you can use the `version` command to find out): 
 - Optional features (if any):

MacOS Mojave, 10.14.6

You can get around this by adding a command to redirect the input

```
echo $nu.env | insert GPG_TTY $(tty | trim) | config --set_into env
```
/Users/brendond> echo $nu.env | insert GPG_TTY $(tty | trim) | config --set_into env
──────┬──────────────────
 env  │ [row 34 columns]
 path │ [table 14 rows]
──────┴──────────────────
/Users/brendond> config | get env.GPG_TTY
/dev/ttys002
```

**Comment by jonathandturner** [comment]
I thought I'd fixed this, but I'm still seeing the old behavior. Reopening for more investigation.

**Comment by ajeetdsouza** [comment]
Still relevant.

**Comment by fdncred** [comment]
This works on 0.59.1
```
> let-env GPG_TTY = (echo (tty))
```
