### ISSUE TITLE
Pending checks for mv, rm, cp, ls, and mkdir to consider them ready.

### ISSUE THREAD

**Issue by androbtech** [nushell/nushell#207]
- [x] Basic working functionality.
- [ ] Permanent signature. 
- [x] Handle and report back all Errs the command could throw appropriately.
- [x] Wildcard support.
- [ ] throughout test coverage (unit and integration)

#### Satisfy features:
- [x] `rm` recursive support `--recursive`.
- [x] `cp` recursive support `--recursive`.
- [x] `ls` recursive support (leveraging `globs`).
- [x] `mkdir` regular and intermediary directory creation.

**Comment by jonathandturner** [comment]
You might also want to add tests for the recursive functionality of each

**Comment by androbtech** [comment]
> You might also want to add tests for the recursive functionality of each

Done. (Don't know why I missed it) 

Under "Recursive support check"

**Comment by androbtech** [comment]
> What's "permanent signature" here?

Here and there the traits have changed for command implementations (receiving evaluated/unevaluated args, context, shell manager) and number of arguments have changed a bit as Nushell keep maturing.

Permanent in that sense.

**Comment by BatmanAoD** [comment]
Oh, so it refers to the signature of the actual Rust `fn`s implementing these builtins?

**Comment by androbtech** [comment]
> Oh, so it refers to the signature of the actual Rust `fn`s implementing these builtins?

Si [señor](https://github.com/nushell/nushell/blob/master/src/commands/mv.rs#L16-L41).

**Comment by jonathandturner** [comment]
@androbtech are there other checks that still need to be added to mark this complete?

**Comment by androbtech** [comment]
@jonathandturner Flag revisit and other than that... think we are Ok.

**Comment by androbtech** [comment]
@jonathandturner Closing this. Will revisit and reopen if needed.
