### ISSUE TITLE
echo does not support special characters

### ISSUE THREAD

**Issue by yanganto** [nushell/nushell#2079]
**Describe the bug**
The echo in nushell is not support the special character, such as `\n`

**To Reproduce**
1. open nushell, `nu`
2. echo string with newline character, `echo "111\n222"`
3. it prints `111\n222`

**Expected behavior**
The expected output is 
```
111
222
```

**Screenshots**
The different output from nushell and zshell
![snapshot](https://www.ant-lab.tw/img/nushell.png)

**Configuration (please complete the following information):**
 - Archlinux
 - nushell 0.15.0

**Comment by jonathandturner** [comment]
We added support for special characters in the upcoming 0.16 release. We don't use the escape character (\n) but instead use a function call:

```
> format "111{$(char newline)}222"
```

**Comment by yanganto** [comment]
Got it, thanks.

**Comment by yanganto** [comment]
Following command do not work properly, so we all missing special character again.
```
> format "111{$(char newline)}222"
```

**Comment by fdncred** [comment]
This is what I do for making strings. `build-string "111" $(char newline) "222"`. I'm not very good with `format`.

**Comment by yanganto** [comment]
Got it.  Thanks a lot.  :)
