### ISSUE TITLE
`math product` to multiply a list of numbers

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2081]
**Is your feature request related to a problem? Please describe.**
We currently have `math sum` to sum a list of numbers together. Might be nice to have a way to multiple a list of numbers, too.

**Describe the solution you'd like**
We could add a `math product` command that works like `math sum`, but instead multiplies all the numbers together.

**Describe alternatives you've considered**
We could instead have a "fold" or "combine" operation that can apply an arbitrary function pairwise and consume a list of values. This is more general, but perhaps less intuitive to new users.

**Comment by gdhuper** [comment]
If this issue is up for grabs, I'd like to take a stab at it. Thanks

**Comment by jonathandturner** [comment]
@gdhuper sure thing. It's yours

**Comment by JosephTLyons** [comment]
Closed by https://github.com/nushell/nushell/pull/2249
