### ISSUE TITLE
Whitespaces in latest Windows Terminal are ignored

### ISSUE THREAD

**Issue by lesurp** [nushell/nushell#2089]
**Describe the bug**
When typing a space (or even copying one from clipboard), all whitespaces / tabs are simply not pasted. This happens in Windows Terminal but not in regular cmd.exe (terminal emulator).
Note that the problem does not occur with powershell nor cmd.exe (shell) which is why I presume it comes from nushell.

**To Reproduce**
1.  Open Windows Terminal (Version: 1.0.1811.0, installed from Windows Store)
2. Start nu.exe
3. Press space

**Expected behavior**
A space

**Configuration (please complete the following information):**
 - Windows 10
 - Nu version: 0.16.0

**Comment by jonathandturner** [comment]
I just tried the latest using 1.0.1811.0 from the Windows Store and I'm not able to reproduce this issue. Can you say a bit more about your configuration? Are you using different fonts that the default Windows Terminal font? Is your Windows localized for a region of the world?

Trying to think of other things that might cause space to fail.

**Comment by lesurp** [comment]
Thanks for the quick answer! And sorry for the inconvenience you were right... 

I use the [eurkey](https://eurkey.steffen.bruentjen.eu/) keyboard layout, and it turns out that opening Windows Terminal + NuShell while the layout is active reproduces the bug.
However, if I switch to any other layout before opening the shell, the space bar works as usual (and I can even go back to eurkey once it's been opened).

I don't think we'll ever know what's going on there..! Thanks again for the help

**Comment by lesurp** [comment]
In the unlikely case someone else encounters the problem (e.g. future me), here's an autohotkey script that changes the layout, open the shell, then changes back...

```ahk
LWin & Return::
Send, #{Space}
run, C:/Users/lesur/AppData/Local/Microsoft/WindowsApps/Microsoft.WindowsTerminal_8wekyb3d8bbwe/wt.exe
Sleep 500
Send, +#{Space}
return
```
