### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by ryanpcmcquen** [nushell/nushell#2090]
I just wanted to say thank you for this awesome project! I tried Nushell a long time ago, and could see the potential but there were too many bugs or oddities at that time, I just tried it again yesterday, and the project has come a long way, and will now be replacing `fish` as my default shell.

Bravo to the team for this fantastic shell.

**Comment by jonathandturner** [comment]
@ryanpcmcquen - thanks! much appreciated :)

**Comment by andrasio** [comment]
@ryanpcmcquen <3 <3 <3 <3
