### ISSUE TITLE
Additional subcommands for str  (length, camelCase, etc)

### ISSUE THREAD

**Issue by rrichardson** [nushell/nushell#2092]
List of String Methods: 

- [x] len
- [x] reverse
- [x] ltrim --char_to_trim
- [x] rtrim --char_to_trim
- [x] contains
- [x] ends-with
- [x] starts-with
- [x] index-of
- [x] split
- [ ] camelCase
- [ ] snake_case
- [ ] kebab-case
- [ ] PascalCase
- [ ] SHOUTY_SNAKE_CASE
- [ ] slice (substring.. can we alias this to slice?)
- [ ] replace slice
- [x] replace substr (find-replace)
- [x] replace regex (find-replace)

**Is your feature request related to a problem? Please describe.**

When working with files on my filesystem, I found I had the need to filter by the length of names. 

For that reason, a `str len` subcommand would be nice. 

Also, `str upcase` and downcase are useful,  but in programming and configuration management,  I find myself having to convert between  SHOUT_SNAKE_CASE and camelCase  and whatnot. 

**Describe the solution you'd like**

We could easily achieve the translation between different cases by using  Inflector
https://crates.io/crates/Inflector 

Its only dependencies are on regex and lazy_static, which are already dependencies of nushell. 

**Describe alternatives you've considered**

So far, the only workaround I've found for getting the length of a string is : 

`ls | where type == File | default nmlen 0 | update nmlen { echo $it.name | size | get chars } `  

which is a bit unwieldy

**Additional context**

**Comment by rrichardson** [comment]
Collecting additional feature requests here: 
len
reverse
 ltrim --char_to_trim
rtrim --char_to_trim
contains
ends-with
starts-with
index-of
split

**Comment by rrichardson** [comment]
Also, change the comma parameters of subcommands like `substr` back into a table,  so 
`substring "3, 6"  foo` 
becomes 
`substr foo 3 6`  (i think?)

**Comment by jonathandturner** [comment]
Adding `str length` with #2102 
I also added `split chars` to split a string into its chars with #2101 

Happy to help review if anyone wants to take some of the above

**Comment by jonathandturner** [comment]
Was thinking of adding `str width` to output the likely display width of the string (accounting for things like CJK characters to be double sized, etc)

**Comment by fdncred** [comment]
@rrichardson There are also string cases here https://github.com/nushell/nushell/projects/2#card-41184697

**Comment by rrichardson** [comment]
@fdncred - ah.. pad is a great idea..  

Can someone share a use-case for `width`?   I guess if we have length, having a corresponding function for the number of bytes a string will use could be handy..  

Also, while I am working with the inflector API, I was thinking of adding plural and singular because it won't be much additional hassle.

**Comment by fdncred** [comment]
@rrichardson I think `width` has to do with this issue https://github.com/nushell/nushell/issues/1784

**Comment by andrasio** [comment]
All implemented it seems. Please re-open if not.
