### ISSUE TITLE
<Tab> for autocomplete current word

### ISSUE THREAD

**Issue by ProgrammingLife** [nushell/nushell#2098]
When I type:  ```l```  it suggest to autocomplete it with my previous command: 
```
ls | where size > 100kb | sort-by modified
```
I want to complete current typing word with ```<Tab>``` key until a following whitespace like this done in zsh. How to get it?

**Comment by thegedge** [comment]
Duplicate of https://github.com/nushell/nushell/issues/2135

@ProgrammingLife I'm pretty sure I got that right ☝️ Let me know if your request is different.

**Comment by thegedge** [comment]
Also something to note: we'll likely keep `<Tab>` the default key binding for completions, but key bindings are intended to be configurable, so you could always change this 🙂
