### ISSUE TITLE
Sometimes quotes are not removed before interpretation

### ISSUE THREAD

**Issue by philip-peterson** [nushell/nushell#2104]
**Describe the bug**
Putting quotes in the middle of a bareword leads to the quotes being included in the output

**To Reproduce**

To establish how most shells work, and also nushell in this case,
```
$> echo 'echo'
echo
```

This is expected, but...

```
$> echo ech'o'
ech'o'
```

This is pretty nonstandard.

**Expected behavior**
Same output in both circumstances.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Linux
 - Nu version (you can use the `version` command to find out):  0.15.0
 - Optional features (if any): `--features stable`

**Comment by thegedge** [comment]
I took care of most odd quoting issues in https://github.com/nushell/nushell/pull/2095, but called out this is one that's not particularly easy to take care of 😞 

My only intuition right now is that we'd have to implement custom parsing logic for this, which is a lot of work for something that I don't think is the right approach. I think the right approach is to work with nu's syntax to get the value you need.

@philip-peterson Can you think of a more interesting example where quotes would end up in the middle of a word? Perhaps an example where you're required to write it that way. I ask because I wouldn't expect anyone to write `echo ech'o'` over just `echo echo` (or your first example).

**Comment by philip-peterson** [comment]
I can think of a few examples where you would need this type of string concatenation. Setting the internal vs. external concern aside, since it's conceivable that for any external use case there is probably an internal use case as well...

One is just a productivity use case. You are typing what you think will be a one-word commit message, when you realize you want to turn it into a sentence

```
git commit -m Update' the docs'
```

Another would be if you want to have something single quoted but then concatenate it with a string that has string interpolation

```
echo 'Here is some text that has some $raw code for instance'"and now I want to $interpolate variables"
```

Here are a variety of other use cases
```
git commit -m everything\'s broken
```

```
git commit -m "Enable \"foo\" feature flag"
```

```
git commit -m 'I started typing a message but then realized I don'"'t actually want single quotes anymore"
```


```
git commit -m 'Disallow the ", :, !, and '"'"' characters' # in bash, prints: git commit -m Disallow the ", :, !, and ' characters
```

**Comment by philip-peterson** [comment]
I would think this probably deserves special parsing logic; if it requires an overhaul, I would be happy to take it on, and this might be a good opportunity to improve the special character handling as well such as metacharacters etc. which I know there's another issue out for: #1456 and some other related ones: #385 #1251

**Comment by thegedge** [comment]
I played around some, and I think the biggest thing here is choosing how quoting works.

For example, zsh:

```
❯ echo 'a''b'
a'b
```

differs from sh/bash:

```
❯ echo 'a''b'
ab
```

Most programming languages would be closer to sh/bash. For example, Ruby:

```ruby
❯ puts "a'bc"'12"3'
a'bc12"3
```
minus the fact that whitespace is ignored, and the strings are technically concatenated together:

```ruby
def len(*a)
  puts a.length
end

len "a'bc" '12"3'
1
```

I don't think we need an RFC here, but I would at least like a few people to chime in before we make a decision. My two cents worth would be this:

- Quoted strings start with a quoting character, and end as soon as that same quoting character is found (although this could change based on whether or not we choose to do the classic backslash style quoting).
- Quoted strings that have no whitespace between them are concatenated together. For example, `"abc"'123'` becomes `"abc123"`.
- Quoted strings that have whitespace between them are considered two separate strings. For example,
`"abc" '123'` would be two separate strings `"abc"` and `"123"`.
- There'll be at least a couple of ways to include the quoting character in the same string:
  - Some kind of escaping mechanism (https://github.com/nushell/nushell/issues/1456)
  - Unquote, then open with a different quoting character (for example, `'don'"'"'t'`)

**Comment by philip-peterson** [comment]
I agree with most of that, those seem like a reasonable set of rules. I'd add in that I'm not sure what the difference between a bareword and a string is; bare words including things like blocks delimited by `[` and `{` further complicates the definition. Would a bareword in a command like `ls foo` also be a string?

> For example, zsh:
>
>❯ echo 'a''b'
>a'b

I actually couldn't reproduce this behavior. After looking into it, I found that it's a special option you can enable, called `RC_QUOTES`.

> Quoted strings start with a quoting character, and end as soon as that same quoting character is found

There is one problem with this rule, which is the `$()` syntax. Basically the grammar of both Zsh and Bash behave as though the `...` portion in `$(...)` is its own new grammatical context, . In other words,

```
echo "$(echo "foo")"
```

does not get parsed to

```
["echo", "$(echo "+"foo"+")"]
```

but rather, a tree something like this:

```
["echo", ["echo", "foo"]]
```

**Comment by thegedge** [comment]
> I actually couldn't reproduce this behavior. After looking into it, I found that it's a special option you can enable, called `RC_QUOTES`.

Ah, my bad. Looks like I have that one enabled. I should really understand my zsh setup 😅 

> There is one problem with this rule, which is the $() syntax. Basically the grammar of both Zsh and Bash behave as though the ... portion in $(...) is its own new grammatical context, . In other words,

That makes sense. I'll expand the rules to capture this.
