### ISSUE TITLE
Unify autoenv with config

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#2117]
**Is your feature request related to a problem? Please describe.**

[Autoenv](https://github.com/nushell/nushell/pull/1943) is a relatively new feature in nushell that supports setting up a custom environment on a per-directory basis. The one issue we have currently is that it's a bit of a unique snowflake. It has some overlap with our regular configuration, but mostly does its own thing.

**Describe the solution you'd like**

First, I'd like to see us layer our contexts, just like [Golang](https://golang.org/pkg/context/). This will allow us to stack our contexts without needing mutability to do some complex manipulation of the existing context. In pseudo rust code, it would look a little something like this:

```rust
struct BaseContext { ... }

struct LayeredContext {
  head: Context,
  tail: Option<LayeredContext>,
}

trait EnvContext {
  fn get_env(&self, key: &String) -> Option<Value>;
}

impl EnvContext for BaseContext {
  fn get_env(&self, key: &String) -> Option<Value> {
    self.env.get(key)
  }
}

impl EnvContext for LayeredContext {
  fn get_env(&self, key: &String) -> Option<Value> {
    self
      .head
      .get_env(key)
      .or_else(|| {
        self.tail.map(|c| c.get_env(key))
      })
  }
}
```

Whenever we switch into a directory with an autoenv config, it would be as simple as bubbling up a new context:

```rust
fn autoenv(...) -> LayeredContext {
  let per_directory_config = Config::load(current_directory);
  LayeredContext::new(
    per_directory_config.into(),
    self.current_context.into()
  )
}
```

The second thing I'd like to see, highlighted in the above code snippet, is the unification of configuration and autoenv files. They both currently share `env`, but autoenv brings some new things to the table:

- `scriptvars`, which are basically env vars but computed from a nu pipeline.
- `entryscripts`, scripts to run when entering a directory (basically like `startup` from config), and
- `exitscripts`, scripts to run when existing an autoenv directory.

Entry scripts are kind of like login/profile scripts from other shells, and exit scripts would be like a logout script. There's no reason we couldn't bring these concepts to our general configuration. I'm not sure the proper terms to use here to apply everywhere, but I like `enter` and `exit`. These have a nice symmetry with our `enter` and `exit` commands.

**Describe alternatives you've considered**

The current implementation is the major alternative, but I think the proposed solution has some superior characteristics:

- Users and developers of nushell only have to learn one concept. This prevents similar concepts from diverging slightly, causing confusion.
- With unification, we can take a `git` approach to configuration and just allow autoenv config to be configured with `git --local`. Schema and other validations then are unified in one place.
- Lack of mutability in the context would be less prone to error.
- The layered context approach is flexible, making it more future proof and resilient to other things that may want to manipulate the current context. It potentially is a little slower, but if we really need speed we could always take an "event sourcing" approach where we snapshot and use that snapshot as the basis for fetching variables and other contextual information.

/cc @samhedin

**Comment by thegedge** [comment]
Actually, why don't we name things in an event-y way? Something like `on_enter` and `on_exit`?

**Comment by samhedin** [comment]
I agree - closer integration between autoenv and existing functionality could simplify things in the future. This is a bit over my head, since I am not super familiar with the codebase. I like the idea of `LayeredContext` though.

>Something like on_enter and on_exit?

Yes! A while back I thought of a more generalized system for adding event handlers. Maybe a simple generalization of some of autoenv's planned functionality could result in a system that allows nushell to support other events in the future?

**Comment by thegedge** [comment]
> This is a bit over my head, since I am not super familiar with the codebase. I like the idea of `LayeredContext` though.

No worries. This is quite a significant issue. It was something that came to my mind and I wanted to capture (before it left my mind, which happens more and more as I get older 😅)

> Maybe a simple generalization of some of the suggested features could result in a system that allows nushell to support other events too?

Yesss! `before_command` and `after_command` would be amaze.
