### ISSUE TITLE
Update `config` to use subcommands

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2119]
**Is your feature request related to a problem? Please describe.**
The original `config` command was made before we had support for subcommands. Now that we have them, we can update `config` to use them.

**Describe the solution you'd like**
Let's move all the commands of `config` into subcommands.

Before:
`config --set [variable value]`

After:
`config set variable value`

We can do this conversion for all the named arguments of `config`:

* `config set variable value`
* `config get variable`
* `config remove variable`
* `config clear`
* `config path`

While we're updating, we can now also remove `set_into`, as our ability to pass tables in has gotten better using the `$()` syntax.

**Describe alternatives you've considered**
We can keep it the way that it is, but it feels a bit awkward compared to how other, more recent commands work.

**Comment by fdncred** [comment]
And not eat comments during processing of config.

**Comment by jonathandturner** [comment]
@fdncred - if you want, you could write up a second issue about moving to a better toml crate (maybe the one you found?). I think that should be doable as a `good first issue` also.

**Comment by fdncred** [comment]
@jonathandturner ok - I added #2132 and tagged it with `good first issue`.

**Comment by ritobanrc** [comment]
I'd like to work on this.

**Comment by fdncred** [comment]
@ritobanrc I assigned this issue to you. Have at it! Thanks for your help!

**Comment by TheMatten** [comment]
Shouldn't this issue be closed as resolved?

**Comment by thegedge** [comment]
Yep, looks like it should! Thanks, @TheMatten.
