### ISSUE TITLE
Automatic path escaping is incorrect

### ISSUE THREAD

**Issue by LiHRaM** [nushell/nushell#2121]
**Describe the bug**
I have a folder, `master's thesis`, which I frequently want to `cd` to.
When I use tab autocompletion in nu, it automatically escapes `'`, which is invalid syntax in nu.

**To Reproduce**
1. `mkdir test'`
2. `cd test` + <kbd>tab</kbd>
3. Observe the output, i.e. `cd test\'/`

Example output from my shell:
```
~
λ mkdir test'

~
λ cd test\'/
error: Cannot change to directory
  ┌─ shell:1:4
  │
1 │ cd test\'/
  │    ^^^^^^^ directory not found
```

**Expected behavior**
Nu should not escape characters in autocomplete which do not require escaping.

**Configuration (please complete the following information):**
 - **OS**: Windows
 - **Nu Version**: 0.16.0

**Comment by almindor** [comment]
This seems to be a bug in the parser not in the completion actually. The completion escapes `'` with `\'` properly but the basic lite parser seems incapable of escape sequences. I'll see if I can make a PR.

**Comment by LiHRaM** [comment]
Seems the changes broke something, now `mkdir test'` doesn't parse correctly. Unless that was intentional?

**Comment by thegedge** [comment]
I wonder if this is the problem, or at least part of it: https://github.com/nushell/nushell/blob/0f688d7da7481c78b54b280661930e0912e1b7b4/crates/nu-cli/src/commands/classified/internal.rs#L217

**Comment by jonathandturner** [comment]
@LiHRaM - `mkdir test'` is looking for the closing `'`. To write that you'll need quotes around it `mkdir "test'"`

After that, you can now tab complete by doing `cd test<tab>`.
