### ISSUE TITLE
documentation for `split-row` and `split-column` needs updated

### ISSUE THREAD

**Issue by efx** [nushell/nushell#2124]
**Describe the bug**
The [documentation website](https://www.nushell.sh/documentation.html) for [split-row](https://www.nushell.sh/commands/split-row.html) is incorrect. The command syntax has changed to `split row`.

**To Reproduce**
1. install stable nu
2. `echo "4, 0, 2, 0, 7, 8" | split-row ','`
3. See error

**Expected behavior**
I expect the documentation to be correct. In due time of course since we are not at 1.0 just yet 😄.
An example of the correct syntax for split row is:
```
echo "4, 0, 2, 0, 7, 8" | split row ','
```
This also affects `split-column`. 
**Screenshots**
<img width="1101" alt="Screen Shot 2020-07-06 at 11 46 05" src="https://user-images.githubusercontent.com/472721/86612561-50c39180-bf7e-11ea-9bd6-17f318428df8.png">

**Configuration (please complete the following information):**
 - macOS
 - 0.16.0

**Comment by Zooce** [comment]
I this this was fixed in https://github.com/nushell/book/pull/104

**Comment by thegedge** [comment]
Yep, I think those two cover this issue. Thanks, @Zooce !
