### ISSUE TITLE
Better TOML handling

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2132]
**Is your feature request related to a problem? Please describe.**
For me, I like to edit the `config.toml` file manually and store alternate versions of aliases, prompts, env variables, etc. The only problem with this is the minute you do `config set [blah blah]` all your comments are gone because our current toml crate doesn't serialize comments.

**Describe the solution you'd like**
I'd like to be able to store comments in the `config.toml` file and use the normal `config set []` command maintain the comments. This may require the switch to a different toml package such as [toml_edit](https://crates.io/crates/toml_edit).

**Describe alternatives you've considered**
toml_edit is the only other package I've looked at. For now my only alternative is to not use the nushell commands if I want to keep my comments.

**Additional context**
N/A

**Comment by danilyanich** [comment]
Hi everyone :wave:. Is this a relevant issue? If so, I'd like to work on it.

**Comment by fdncred** [comment]
+1 for asking. yes, it's relevant. I was hoping to replace our toml crate with toml_edit. I've done some [prototype work here](https://github.com/fdncred/toml_edit_test), just playing around with toml_edit. Feel free to use and abuse this code. The prototype code doesn't work the way I'd want it to in nushell but it may be helpful to look at for starting.

**Comment by fdncred** [comment]
@danilyanich I forgot to mention that I had a draft PR already on this - feel free to use it or not use it - it's #2492

**Comment by fdncred** [comment]
@danilyanich How's it going? We haven't heard much from you recently.

**Comment by fdncred** [comment]
there have been some recent updates to toml_edit that is supposed to make it a drop-in replacement for toml-rs. it would be nice for someone to investigate this.

**Comment by GabrielBG0** [comment]
hey, how should i test it? i changed to toml_edit but as i dont know how the command works i don't know how to test it 😅

**Comment by fdncred** [comment]
you need to see if nushell is reading the config.toml file and if you can use the `config` command to read and write values to the nushell config.toml without eating comments and preserving the toml order.

**Comment by kaleidawave** [comment]
Any progress on this...?

I want to do `open x.toml | modify_thing | save x.toml` and it is currently unusable because it reformats and removes comments.

Using `toml_edit` looks like a good idea. Is this a easy thing to add given that it is loading the TOML it into a table? Does that table retain order and how would it hold comments...?

**Comment by GabrielBG0** [comment]
We decided to not go on with changing how Nu handle toml files once we are not sure if we'll stick with it on the new engine ([engine-q](https://github.com/nushell/engine-q)).  Making the change would not be super straightforward as it looked so the best option was to wait until we know for sure if we will use toml still or if configs will be managed differently.

As for editing other files, this maybe a good enough use case to make the change, but I guess it would, most likely, ship only with engine-q. I don't know how Darren ( @fdncred ) and the others feel about this, nor what is the exact state of engine-q rn, but if thats a wanted feature I could work on it.

**Comment by fdncred** [comment]
I think we've scrapped the idea about using toml as a config syntax for engine-q. We're mostly really loving the nu script syntax for the config system in engine-q. However, I still think toml-edit should be used in `from toml` and `to toml` for engine-q because of the same original reasons. So, if @GabrielBG0 or @kaleidawave or anyone else wants to have a go at it, let me know and we can make a new issue in engine-q and i'll assign it to whomever.

**Comment by GabrielBG0** [comment]
if @kaleidawave don't want to get it I can do it, It's his call

**Comment by fdncred** [comment]
I created this issue https://github.com/nushell/engine-q/issues/450 on engine-q for tracking. Jump in there if you want to work on it. For now, I'm closing this issue.

**Comment by fdncred** [comment]
Still an issue in 0.106.1
