### ISSUE TITLE
Surprising alias behavior

### ISSUE THREAD

**Issue by ndarilek** [nushell/nushell#2133]
Trying to use Nu full-time, and am experiencing surprising behavior with some aliases. I have:

```toml
startup = ["alias  gpl [] { git pull }", "alias  gps [] { git push }", "alias  gl [] { git log --abbrev-commit }"]
```

When I run those commands manually, they behave as I'd expect. But as aliases, I see the following:

* _gl_: Does not page output, and seems to attempt to make a table out of it somehow.
* _gps_ and _gpl_: Succeed, but report an error:

```
conduit on 📙 master is 📦 v0.1.0 
❯ gpl
───┬─────────────────────────────────────────────────────────────────────────────────
 0 │ Updating 67a1f21..b819398                                                       
   │ Fast-forward                                                                    
 1 │  src/client_server.rs  | 117 ++++++++++++++++++++++++++++++++++++++++++-------- 
   │  src/database/users.rs |  36 +++++++++++++---                                   
   │  src/main.rs           |   1 +                                                  
   │  3 files changed, 132 insertions(+), 22 deletions(-)                            
───┴─────────────────────────────────────────────────────────────────────────────────
error: Error: From https://git.koesters.xyz/timo/conduit
   67a1f21..b819398  master               -> origin/master
   53e7a1a..c0107d9  account-deactivation -> origin/account-deactivation
 * [new branch]      improve-to-device-removal -> origin/improve-to-device-removal
 * [new branch]      logout-all           -> origin/logout-all
conduit on 📙 master is 📦 v0.1.0 
```

My expectation is that an alias would behave identically to typing in the aliased command, and if I wanted any additional Nu magic, I'd have to opt in.

Thanks.

**Comment by thegedge** [comment]
Thanks for the report!

> gl: Does not page output, and seems to attempt to make a table out of it somehow.

This is covered in https://github.com/nushell/nushell/issues/389, so I'd recommend following that one to see progress 🙂

> gps and gpl: Succeed, but report an error:

Interesting! Either there's a nonzero exit status (which means it didn't succeed, even if it appeared to succeed), or we're displaying an error because something was emitted to stderr (I don't think we do that). We'll have to investigate that one!

**Comment by ndarilek** [comment]
Not sure what specifically is happening with gps/gpl, but my expectation 
is that aliases would behave identically to entering the command, and I 
don't otherwise get that error indicator. Maybe git is sending something 
to stderr for some reason, but even if it were, a feature calling itself 
aliases shouldn't augment the output at all IMO.


Thanks for the other issue reference--I'll follow that one.

**Comment by thegedge** [comment]
Taking a look at the code, I think it's unlikely this is a `nu` error, but some error being emitted by the remote. Do you think that's possible?

Another issue I think you raised is that `stdout` is becoming a list of lines instead of simply being output on the screen? That is indeed kind of surprising.

**Comment by ndarilek** [comment]
If under Bash I do `git pull >/dev/null`, I get lots of output. Unless 
I'm mistaken, it looks like git is dumping everything to stderr. If I do 
the same for an up-to-date repo, I get no output, so assume the 
"Everything is up to date" line goes to stdout.


If what's happening is that the alias is implicitly adding "| lines| or 
something similar, eliminating that magic is probably the way forward. 
I'd add that myself if I wanted that behavior.


Thanks.

**Comment by fdncred** [comment]
@thegedge I was going to file an issue on this but it may be the same thing/or simlar. I do the command below, on Windows (not sure about other OS), and it pages with `less.exe`. It looks great but when I hit `q` to quit, there's an error. FWIW, if I do the exact same thing in PowerShell and there's no error.

git command:
`git log --graph --pretty='format:%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative `

![image](https://user-images.githubusercontent.com/343840/86923250-67d7c000-c0f3-11ea-9e7d-5dc8aa6e0f69.png)

**Comment by thegedge** [comment]
After running that command, @fdncred, I see this:

```
❯ echo $?
141
```

Looking into it, this is because pressing `q` closes the pipe before consuming everything, and `git` will report this as an error. If you scroll to the very end, you'll see that goes away. Rather unfortunate 😞

**Comment by fdncred** [comment]
hmmm, in powershell without any modules running I get the same result. It looks like less is returning this value on `q` for some reason. You're right again. :)
```
PS .\nushell> $LASTEXITCODE
141
```
