### ISSUE TITLE
`$*`, or some way to pass free-form arguments to aliases

### ISSUE THREAD

**Issue by ndarilek** [nushell/nushell#2134]
I'm a screen reader user who aliases _gl_ to _git log --abbrev-commit_ so that, when reading commit logs, I don't have to listen to complete SHA hashes. Sometimes I want to do _gl <other git log arguments here>_, which works in Fish and other shells.

I know I can add ignored arguments in the meantime, and in general like the system of explicitly specifying arguments. But having some sort of glob argument pattern for aliases would be nice as well.

Thanks.

**Comment by thegedge** [comment]
Hey, @ndarilek. Is this what you're looking for: https://github.com/nushell/nushell/issues/1716?

If yes, we can close this one as a duplicate.

**Comment by ndarilek** [comment]
Looks like it. Sorry I missed that one.

**Comment by thegedge** [comment]
> Sorry I missed that one.

No worries. We have a bit of a bug backlog, so it's very easy to not get the same terms as what someone else used. I struggle all the time to find an issue I'm fairly confident already exists 🙂
