### ISSUE TITLE
Support partial completions

### ISSUE THREAD

**Issue by ryanpcmcquen** [nushell/nushell#2135]
Coming from `fish` shell, I miss the partial completion with <kbd>Alt</kbd> and arrow keys.

Here's an example of partial completion in action. I find this feature infinitely useful!
![partial_completion](https://user-images.githubusercontent.com/772937/86824811-7e264300-c043-11ea-9d66-af36ca7db681.gif)

Perhaps this could be part of the convo in this issue as well:
https://github.com/nushell/nushell/issues/290

**Comment by fdncred** [comment]
I would love to see this too.

**Comment by thegedge** [comment]
☝️ Removed the "completions" label, which I've been using to mean "completion suggestions". This is what we call "hinting", where we hint to what the user wants the line to be, based on historical lines. A little pedantic, but this helps me focus my work around completions 🙂

**Comment by thegedge** [comment]
I think this is missing functionality in rustyline. If we take a look at https://docs.rs/rustyline/6.2.0/rustyline/enum.Cmd.html, the only option we have is `CompleteHint`. In other words, we can complete the entirety of the hint, but not partially. We'll either need rustyline to add:

1. partial hint completion, or
2. custom commands for key bindings.

**Comment by schrieveslaach** [comment]
I've created a PR that adds the missing partial completion: kkawakam/rustyline#513

**Comment by schrieveslaach** [comment]
@thegedge, as it turns out Nushell could use a custom commands for key binding when [this TODO](https://github.com/kkawakam/rustyline/pull/513#issuecomment-818878226) has been fixed. When the PR kkawakam/rustyline#513 will be merged, I will integrate it into Nushell.

**Comment by thegedge** [comment]
Thanks for taking this on, @schrieveslaach!
