### ISSUE TITLE
Filename completion with quoting characters not always working

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#2136]
**Describe the bug**

When filenames contains quoting characters or other things that require the name to be surrounded by quotes (e.g., whitespace), tab completion isn't always producing the correct result.

**To Reproduce**

I have these files:

- `foo bar`
- `foo'bar`
- `abc"123'`

And this nested directory structure:
- `foo/bar spaces/a"b"c`

```
> cat foo<TAB><TAB>
foo bar  foo'     foo'bar
```

So we get the correct set, but here are some cases that don't complete correctly:

```
> cat "foo <TAB>
> cat "foo "foo bar"
```
```
> cat "foo'b<TAB>
> cat foo'bar         <-- forgot double quotes
```
```
> ls "foo'/<TAB>
> ls "foo'/bar spaces/"
> ls "foo'/bar spaces/<TAB>"
> ls ""foo'/bar spaces/a"b"c/""   <-- only option here are backticks
```
```
> ls abc<TAB>
> ls "abc"123"
```

**Expected behavior**
These complete to actual paths, with the right quoting character used.

https://github.com/nushell/nushell/pull/2129 improved some cases by wrapping things in double quotes, but we need to go a little further 🙂

**Comment by thegedge** [comment]
https://github.com/nushell/nushell/pull/2192 addresses most of this, but this one:

```
> cat "foo <TAB>
> cat "foo "foo bar"
```

Seems to still exist. I think it could be a bug in rustyline itself, because the completion item and position is correct. Will investigate.

**Comment by fdncred** [comment]
Is there a way to turn of case sensitivity? I even added a PR to rustyline to disable that on Windows. By default, the windows file system is not case sensitive and it makes it harder to navigate if I have to remember which folders / file have upper case letters.

**Comment by fdncred** [comment]
Two items here.

1. `ls<tab>` changes it to `"ls "`
    Expected: Folder and file completions.
2. `ls<space><tab>` removes `ls` and replaces it with folders. 
    Expected `ls<space>` and start completing folders and files.

![ls](https://user-images.githubusercontent.com/343840/91723761-e2f0ac00-eb61-11ea-9c56-aba3fb96bfbf.gif)

Version

|version|commit_hash|nushell_features|
|-|-|-|
|0.18.2|889b67ca928e1bcf4c4170f2402c150da142f0f7|default, clipboard, trash|

**Comment by fdncred** [comment]
Here's a test with spaces in the file names. Seemed to work well. It also shows it not completing `\pro` which it should if it were not case sensitive.

I goofed up at the end and hit enter without a quote.
![ls-spaces](https://user-images.githubusercontent.com/343840/91724467-f81a0a80-eb62-11ea-8e84-bd4f332a6f56.gif)
