### ISSUE TITLE
Keep Nushell from Creating an Empty Table Initially

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#2138]
**Describe the bug**
If you run certain commands that do not generate data, but simply filter data, on their own, sometimes, nushell will output an empty table.  Some commands `drop` and `first` demonstrate this.  

**To Reproduce**
1. Run `drop 0` or `first` without any piping
2. See the output of the empty table with 1 row

**Expected behavior**
I would expect nushell to not send an empty table through the pipeline initially.  Maybe this is intentional and there is no way around it; I don't know where to look to find out where this is occuring.

**Screenshots**
<img width="362" alt="Screen Shot 2020-07-08 at 2 15 43 AM" src="https://user-images.githubusercontent.com/19867440/86884020-f2eb9280-c0c0-11ea-8564-fb298e991d1e.png">

**Configuration (please complete the following information):**
 - macOS 10.15.5
 - Nu version (you can use the `version` command to find out): 0.16.0
 - Optional features (if any):

**Comment by JosephTLyons** [comment]
Another thing I've noticed is that this doesn't happen on 0.16.0 (the last release) (on right), but happens on master of 0.16.1 (on left), so it must've been a recent change that caused it:

<img width="828" alt="Screen Shot 2020-07-08 at 5 52 16 PM" src="https://user-images.githubusercontent.com/19867440/86974217-e9efd500-c143-11ea-8c4f-954df54ac32a.png">

**Comment by jonathandturner** [comment]
The original issue seems to be fixed now
