### ISSUE TITLE
to xml

### ISSUE THREAD

**Issue by warrenseine** [nushell/nushell#2141]
**Is your feature request related to a problem? Please describe.**

`from json` has a symmetric `to json`, but `from xml` hasn't. Here's an example with `open | save` (which I believe uses `from | to` under the hood:
```
❯ open pom.xml | save pom.xml
error: Save requires string data
  ┌─ shell:1:16
  │
1 │ open pom.xml | save pom.xml
  │                ^^^^ consider converting data to string (see `help commands`)
```

Saving with `--raw` just produces an empty file.

**Describe the solution you'd like**
It'd like XML to work similarly to JSON.

**Describe alternatives you've considered**
Opening the file as raw text and saving as raw text works as expected, but prevents me from manipulating data to increase a version with `inc` for instance.

**Additional context**
```
❯ uname -a
Darwin C02V83QMHV2Q 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
❯ sw_vers -productVersion
10.15.5
❯ nu --version
nushell 0.15.0
```

**Comment by warrenseine** [comment]
I suppose it's a pretty simple "first issue" for anyone willing to contribute!

**Comment by warrenseine** [comment]
@thegedge I see that [roxmltree](https://github.com/RazrFalcon/roxmltree/blob/master/README.md), the library used to parse XML in `from xml`, can only read XML, not write it. If I want to output XML, I can either:
1. integrate another XML library ([xmltree](https://docs.rs/xmltree/0.10.1/xmltree/index.html) looks ok)
2. add the write capability to roxmltree (which, considering the name of the library, sounds like a bad idea)
3. implement the serializer myself

What would you recommend?

**Comment by thegedge** [comment]
I think regardless of what you do, you'll likely end up having to do (3) to some extent, because you need to find a mapping between a nushell `Value` and whatever crate you use.

I think there are two options:

1. Follow something like our `to json` method, and make use of a serde thing (e.g., https://docs.rs/serde-xml-rs/0.4.0/serde_xml_rs)
2. Follow something like out `to html` method, and manually build up a string.

I think either choice is fine, but I'd probably go with (1), because it'll likely take care of many subtle issues you'd have when writing your own serialization, like ensuring strings are properly encoded with entities and such 🙂

**Comment by thegedge** [comment]
By the way, if you're interested in working on this, I'd be happy to assign the issue to you, @warrenseine

**Comment by warrenseine** [comment]
I do. I have no previous Rust experience, so I can't commit to anything, but I think it'd be a good issue to learn the language (and the project architecture as well).

**Comment by thegedge** [comment]
It's yours! Let us know if you have any questions. You can join us in #developing on discord, or just ask in here 🙂

**Comment by warrenseine** [comment]
I've submitted a first incomplete PR (#2155). I'd appreciate if someone could have a look and answer a few questions.

**Comment by warrenseine** [comment]
I now realise that I can't simply convert any table to XML. I see at least 2 obvious issues:
- lists don't exist in XML
- XML files can't have multiple roots

You can't convert the following JSON file to XML without additional logic:
```json
{
  "authors": ["you", "me"],
  "version": 42
}
```

You would idiomatically write something like:

```xml
<package>
  <authors>
    <author>you</author>
    <author>me</author>
  </authors>
  <version>42</version>
</package>
```

but `package` or `author` are new nodes I can't just invent.

I'm going to reject non-XML input. The basic use case is still relevant.

**Comment by warrenseine** [comment]
Please re-open if there’s a bug (and I’m sure there will be!).
