### ISSUE TITLE
open --raw is no longer raw

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2144]
**Describe the bug**
It appears that something, maybe #2028, changed `open --raw`. It seems to go through `bat` or some other process to display a file. Maybe this is a `textview` change. I'm not sure. I found it by looking at @arashout 's `summaries.md` file. If you look at the one without stripping the ANSI sequences.

**To Reproduce**
1. open --raw summaries.md

**Expected behavior**
I expect a raw output without without a table. I'm also not sure where they syntax highlighting is coming from. Is that just because it has embedded ansi sequences or is something else coloring it?

**Screenshots**
![image](https://user-images.githubusercontent.com/343840/87062017-1e11d700-c1d2-11ea-9303-e05825e32e13.png)

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Windows 10 2004
 - Nu version (you can use the `version` command to find out): 0.16.1 from master
 - Optional features (if any): features=stable

Rename to `summaries_raw.md` since GH doesn't allow `.md` files as attachments.
[summaries_raw.txt](https://github.com/nushell/nushell/files/4897939/summaries_raw.txt)

**Comment by arashout** [comment]
I probably introduced this bug in my pr for open.
I'll take a look

**Comment by arashout** [comment]
So I may need some help with this. @jonathandturner 
The `raw` functionality is working correctly, but what we are seeing in the screenshot is the Streaming "packets"/"frames"? from `MaybeTextCodec`. 
I don't really know how to make the numbers go away...

**Comment by arashout** [comment]
Just to add more context to this issue, from discord:
```
jturnerToday at 10:30 AM
@arashout the way things currently work, at the end of the pipeline is always either an external command, or the autoview command. The autoview command checks the output, and then redirects it depending on the type of data it is
part of the problem we're having is that the protocol is incomplete.  It's not currently possible to tell the difference between a stream of strings that should be appended, and a table where each row is a string
in theory, once we fixed this, the issue you're seeing where the strings are put into a table should get fixed
```

I also think this issue and https://github.com/nushell/nushell/issues/2138 are related

**Comment by jonathandturner** [comment]
This has improved since the original issue. Closing, but please reopen if you find cases that cause the issue.
