### ISSUE TITLE
FilePath handling as builtin

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2145]
**Is your feature request related to a problem? Please describe.**
It would be nice if Nu had a path builtin for dealing with file paths. Maybe a command called path with subcommands.

**Describe the solution you'd like**
- [ ] path basename
- [ ] path extension
- [ ] path directory_name
- [ ] path get_fullpath
- [ ] path filename
- [ ] ?
- [ ] ?

**Describe alternatives you've considered**
Parsing with regex

**Additional context**
#387

**Comment by mattyhall** [comment]
Hi, I was going to look into doing this (following roughly how str is worked out) but saw the extra context. Are the maintainers planning on using something other than std::path::Path as their representation? If so I suppose it is best I wait for such a decision

**Comment by fdncred** [comment]
@mattyhall I think you should run with it. I think the comments on UNC and *nix/Windows slashes are still valid. I think it's also probably a good idea to look at other path library crates - maybe std::path::Path is good, maybe there's something better/easier/more options. I'm not sure. @jonathandturner , @thegedge - any input on this?

**Comment by mattyhall** [comment]
As of #2255: basename, extension and expand (equivalent to "get_fullpath" I think) are done

**Comment by fdncred** [comment]
Just looked at the code @mattyhall. Good job! Thanks so much for adding this! Looking forward to your next one. :)
