### ISSUE TITLE
Functional methods?

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#216]
With block being one of the Value types, we could explore non-mutating methods.

`measure-room | $it.area`

For example, the above might happen in two steps, where measure-room returns both a structure and a few convenience methods to deal with that structure.

Not sure if we want to go this way or something more like typeclasses, but could be interesting to explore

**Comment by wycats** [comment]
We definitely need methods. design-needed big time.

**Comment by obust** [comment]
Or it could be a multiple dispatch mechanism similar to [Julia methods](https://docs.julialang.org/en/v1/manual/methods/) where dispatch is based on argument types. Though it may make the use of `$it` too obtrusive.
Not sure which one fits best with the piping mechanism.

**Comment by pwnorbitals** [comment]
Is this still in the works ?
