### ISSUE TITLE
config documentation update

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2166]
**Describe the bug**
I noticed there are a few places that `config --set` is referenced in the documentation. Config has recently changed and doesn't have flag like it used to. So, it would be nice to get these occurences updated from `config --set` to `config set`. I think this is a complete list of config subcommands that need to be changed.
* clear
* get
* load
* path
* remove
* set
* set_into

**Comment by morrme** [comment]
What about this one (from README): https://github.com/nushell/nushell/blob/main/README.md#configuration

**Comment by fdncred** [comment]
@morrme Good catch. There are several places where it needs updating like this.

**Comment by morrme** [comment]
@fdncred What about this table? https://github.com/nushell/nushell/blob/main/docs/commands/config.md#flags

**Comment by fdncred** [comment]
@morrme Yes, exactly!

**Comment by morrme** [comment]
Should the table be eliminated, or just updated without the ` --`

**Comment by fdncred** [comment]
I think all changes throughout the documentation should probably be just to remove the `--`'s. If you find something that you don't agree with, bring it up and we can discuss it.  Should I assign this to you? :)

**Comment by morrme** [comment]
sure. 🙂

**Comment by fdncred** [comment]
Done. Thanks for your help!!!

**Comment by Tauheed-Elahee** [comment]
@morrme I see that you made a pull request for README.md could you also update the [Nu book](https://www.nushell.sh/book/) as well?
