### ISSUE TITLE
Expand a list of primitives into separate positional arguments for externals

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#2169]
**Is your feature request related to a problem? Please describe.**
I'd like an easy way to "splat" a nu list into separate positional arguments for an external command. For example, `vim $(ls | where type == File | get name)` would open all of the files in the current directory with vim.

**Describe the solution you'd like**
I think it makes sense to have `external <list>` evaluate as `external list.0 list.1 ...`, similar to `command "$@"` in other shells, since externals don't know how to process structured data. Given that, I don't think there'd be ambiguity here. Tables with named columns should always fail.

**Describe alternatives you've considered**
Other alternatives would be special "splatting" syntax, but that's a heavy hammer that I prefer avoiding at all costs.  It may be necessary if we want a similar behaviour for internal commands, though, because otherwise we have an ambiguity (if we have a command `foo` that takes an arbitrary number of positional arguments, does `foo <list>` expand like above, or is it a single argument?)

`xargs` could work too, but that external won't be available everywhere.

**Comment by kfardanesh** [comment]
**Posting my example from discord:**
Thought I'd offer some observations while trying to programmatically update python packages
```nu -c $(echo "python -m pip install --upgrade " $(python -m pip list | lines | skip 2 | parse "{package} {version}" | trim | = `{{$it.package}} `) | str collect)```


The above works, but displays awkwardly when set as an alias as follows:
```alias --save pip_upgrade_packages [] { nu -c $(echo "python -m pip install --upgrade " $(python -m pip list | lines | skip 2 | parse "{package} {version}" | trim | = `{{$it.package}} `) | str collect) }```
