### ISSUE TITLE
Should we detect non 24-bit color terminals?

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#217]
Terminals like the default macOS terminal are not 24-bit and cause issues with some of the commands that expect 24-bit color ansi. We should probably detect this and fall back to something the terminal supports.

**Comment by muv1** [comment]
Yes please. With Windows, only version 10 has ANSI color, so you get this:

~~~
Welcome to Nushell 0.13.0 (type 'help' for more info)
 [1;36m/Desktop/nushell_0_13_0 [0m
 [1;32m❯ [0m
~~~

**Comment by muv1** [comment]
https://github.com/nushell/nushell/issues/1630
