### ISSUE TITLE
Command substitution not interoperable with inbuilt commands

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#2174]
**Is your feature request related to a problem? Please describe.**
I'm the author of [zoxide](https://github.com/ajeetdsouza/zoxide), and I've been trying to integrate it with Nushell. zoxide allows a user to cd into a directory by using just a keyword. A simple way of doing this would be:

```
cd $(zoxide query foo)
```

However, this is does not currently work in Nushell. However, something like this does work, presumably because `pwd` is an inbuilt command:

```
cd $(pwd)
```

**Describe the solution you'd like**

I'd love for Nushell to support strings output from regular programs as arguments to inbuilt functions like `cd`.

**Describe alternatives you've considered**

If there is a way to convert the output to a format recognized by Nushell, that would also work for me.

**Additional context**

A more reproducable example of the above - this works:

```
cd $(echo '/')
```

but this doesn't:

```
cd $(/bin/echo '/')
```

**Comment by thegedge** [comment]
Possibly related: https://github.com/nushell/nushell/issues/2069

**Comment by ajeetdsouza** [comment]
Still relevant.

**Comment by ajeetdsouza** [comment]
Relevant.

**Comment by filaretov** [comment]
Has anyone looked into this? On Windows at least, it seems like the trailing newline is an issue:

```
>>> cd (^echo /)
...directory not found error
>>> cd (^echo / | str trim)
works
```

**Comment by herlon214** [comment]
@filaretov yeah, indeed looks like it's a newline issue:
```
> echo $"'(^cat file)'"
'/home/Users/herlon

'
```

**Comment by herlon214** [comment]
Removing the `^` works:
```
> cd (echo '/')
```

**Comment by herlon214** [comment]
Ok, adding the `-n` flag to echo works:
```
> cd (^echo -n '/')
```
