### ISSUE TITLE
Support for logical paths with pwd

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#2175]
**Is your feature request related to a problem? Please describe.**
Most shells support two options with `pwd`:

- `-L` for the logical path (leaving symlinks in the path, removing `.` and `..`)
- `-P` for the physical path (similar to `canonicalize` in Rust)

Currently, Nushell only supports physical paths with `pwd`. This leads to an unintuitive experience, since `pwd` is used in the prompt:

```
/tmp> mkdir a
/tmp> cd a
/tmp/a> ln -s /tmp/a /tmp/b
/tmp/a> cd ../b
/tmp/a> !?
```

**Describe the solution you'd like**
I'd like a way to query the current logical path, similar to `pwd -L` on other shells. Not only will this improve the prompt, but also help tools like [zoxide](https://github.com/ajeetdsouza/zoxide) retrieve the logical current path and add it to the database, allowing the user to query that logical path in future.

**Describe alternatives you've considered**
I've tried `echo $nu.cwd`, but it too seems to return a physical path with symlinks resolved.

**Additional context**
https://man7.org/linux/man-pages/man1/pwd.1.html

**Comment by thegedge** [comment]
This will be tougher than expected, because we [canonicalize the path](https://github.com/nushell/nushell/blob/8551e06d9ea1d25d97989bc4874571c0bcc7d410/crates/nu-cli/src/shell/filesystem_shell.rs#L213) whenever we cd, which will read the symlink and set the current working directory based on that result.

**Comment by ueXIMcWizBrdyVEciAlSwxP8aaXP70mO** [comment]
I am bumping this issue since this is still a problem on `0.32.0`. A practical example of nushell's path-canonicalization behavior being cumbersome is in interactions with `sysfs`: `cd /sys/bus/usb/devices/usb1` lands in `/sys/devices/.../usb1`. I would be happy to experiment with removing the `cd` canonicalization behavior if it is not already under development.

**Comment by zioroboco** [comment]
I've commented out [this line](https://github.com/nushell/nushell/blob/e77219a59f181fe08722ab4a3357147090b91de2/crates/nu-path/src/expansions.rs#L33) and it addressed the issue, and nothing has broken... _yet_.

My understanding is this would cause issues for windows users, but hopefully an interesting experiment nonetheless. I'll report back if anything comes up.

**Comment by pcrockett** [comment]
Would this also affect `$env.FILE_PWD` in scripts? I would very much like to have the logical path there too.

**Comment by alexjp** [comment]
this would be extremely usefull in nixos!

**Comment by sivertism** [comment]
Came across this issue when trying out nushell at work. We organize our fairly large code base by extensive use of symlinks to git repos stored in a cache server for read-only access. This means that the "real" path to a repo may look like `/cacheserver/<very-long-hash>/...`. So when I enter such a repo with nushell, e.g. `cd project/a/b/c/d/e/thing` I 1) get an enormous prompt, 2) get stuck, as `..` will just put me into the cacheserver, not the workspace I came from. 

This is a show stopper for me in using nushell at work, but I hope this issue will get fixed, as nushell looks very interesting!

Meanwhile, I'll try the "fix" mentioned in [the post above](https://github.com/nushell/nushell/issues/2175#issuecomment-1176453494).

**Comment by zedgamer9128** [comment]
I've also got this issue is this being worked on
for example 
![image](https://github.com/nushell/nushell/assets/33319711/07708c3d-577b-451e-9a00-2643093852df)
as you can see /Zed is softlink to /mnt/d in other shells such as fish it will show /Zed but here the real path is shown

**Comment by bew** [comment]
What would be the next step to progress this further?

What about trying for 1 or 2 releases without the canonicalization?
If there are issues at least we'll know about them and why we want to canonicalize, or see what other solution we can find.

**Comment by kubouch** [comment]
Maybe a band-aid solution could be to add `$env.PWD_LOGICAL` and `$env.FILE_PWD_LOGICAL` that won't have resolved symlinks.

**Comment by groundedtako** [comment]
Are there any plans to support this? Also a deal breaker at work.

**Comment by YizhePKU** [comment]
@groundedtako I'm working on PR #12603 to support this. There's still some bugs to iron out, but you can expect things to work soon.

**Comment by YizhePKU** [comment]
PR #12603 has landed. `cd` and `pwd` now use logical paths by default, and have a `-P` switch to force physical path. We can close this now.
