### ISSUE TITLE
config command suite reassessment

### ISSUE THREAD

**Issue by andrasio** [nushell/nushell#2185]
`--set` takes the arguments as positionals and no longer a table. 

`config set [table_mode light]` < no longer supported.
`config set table_mode light` < new way.

**Comment by jonathandturner** [comment]
@andrasio is this issue to change the docs or how `config set` works?

**Comment by andrasio** [comment]
> @andrasio is this issue to change the docs or how `config set` works?

I think we can conclude this is resolved.

**Comment by andrasio** [comment]
> > @andrasio is this issue to change the docs or how `config set` works?
> 
> I think we can conclude this is resolved. /cpy @jonathandturner
