### ISSUE TITLE
History not preserving across sessions.

### ISSUE THREAD

**Issue by ryanpcmcquen** [nushell/nushell#2193]
I'm on nushell 0.16.0, Mac OS 10.15.x. My history isn't preserving across sessions, things I ran a day ago are already gone ... is there some special config I am missing? I looked at the code here and the default is 100,000 lines of history, but mine never seems to go too far beyond 100.

Here's my config:
```
completion_mode = "circular"
use_starship = true

path = ["/usr/local/opt/tomcat@8/bin", "/usr/local/opt/php@7.3/sbin", "/usr/local/opt/php@7.3/bin", "/usr/local/opt/node@12/bin", "/usr/local/bin", "/usr/bin", "/bin", "/usr/sbin", "/sbin", "/Library/Apple/usr/bin"]
```

**Comment by ryanpcmcquen** [comment]
I also tried manually setting `history_size` to `500000`, but that's not helping either.

**Comment by bailey-layzer** [comment]
The history seems to gets munched down to 100 with/after the first command after running nu - calling `history` first will show a longer history from the last session, but upon calling it again there are 101 entries including the first `history`.

**Comment by ryanpcmcquen** [comment]
@jonathandturner, thanks for the fast fix!

**Comment by ryanpcmcquen** [comment]
This is broken again, I think because of changes for #2234.

**Comment by JosephTLyons** [comment]
> This is broken again, I think because of changes for #2234.

Yes, I ended up reverting that one commit because it ended up causing our test suite to run extremely slow.  Normally, the suite runs in 5-10 seconds, but the commit that was reversed had an unintended side effect which caused our test suite to take 15-20 minutes to run, which slowed down development a lot.  I think some sort of alternative solution may be coming along at some point.

**Comment by ryanpcmcquen** [comment]
This bug should be reopened then. If you limit the default history size to something small like 1000, does that help with the test suite?

**Comment by ryanpcmcquen** [comment]
Is this fixed in `0.18.1`?

**Comment by mborejdo** [comment]
@ryanpcmcquen using the updated config (https://github.com/nushell/nushell/blob/main/docs/sample_config/config.toml) the history-size limit seems to be honored. At least I get more than 100 entries now

**Comment by ryanpcmcquen** [comment]
@mborejdo or @JosephTLyons, did `history_size` change to `max_history_size`?

**Comment by mborejdo** [comment]
@ryanpcmcquen as far as I understand, its rustylines config which is exposed directly to nushell. So I guess, its now the cariable name which rustyline uses/expects
