### ISSUE TITLE
to html: fix output for lists

### ISSUE THREAD

**Issue by jzaefferer** [nushell/nushell#2208]
**Describe the bug**
When using `to html` to format a list, all values are joined without spaces (and no other formatting)

**To Reproduce**
```
> echo "[1,2,3]" | from json | to html
<html><body>123</body></html>
```

**Expected behavior**
I'd expect at least spaces between the list elements. Or a headerless table:
```
<html><body><table><tr><td>0</td><td>1</td></tr><tr><td>1</td><td>2</td></tr><tr><td>2</td><td>3</td></tr></table></body></html>
```

**Configuration (please complete the following information):**
 - OS (e.g. Windows): OSX (should be OS independent)
 - Nu version (you can use the `version` command to find out): latest main (0.16.1)

See also https://github.com/nushell/wasm-nu/issues/16

**Comment by coolshaurya** [comment]
I think there are 3 types of values that need to be handled separately when converting to HTML  -

1. Single value - a single value like `echo 10`. This will be transformed to HTML without any wrapping at all.
1. A list - a list of values like `echo 1..10`. This will produce an `<ul>`/`<ol>`.
1. A table - a table of values like `echo 1..10 | wrap num` or `echo 5 | wrap a`. This will produce a `<table>`

Additionally this would match what nu outputs in the terminal

**Comment by jzaefferer** [comment]
That sounds good to me! So the missing piece is the second item. I think a `<ol>` makes slightly more sense here, since the list is ordered.
