### ISSUE TITLE
Error for `ps`

### ISSUE THREAD

**Issue by jzaefferer** [nushell/nushell#2210]
**Describe the bug**
Using nu from latest main (0.16.1), `ps` fails with an error.

**To Reproduce**
1. Run `ps`

It outputs this:

error: Error: Error while processing begin_filter response: Error("unknown variant `Filesize`, expected one of `Nothing`, `Int`, `Decimal`, `Bytes`, `String`, `Line`, `ColumnPath`, `Pattern`, `Boolean`, `Date`, `Duration`, `Range`, `Path`, `Binary`, `BeginningOfStream`, `EndOfStream`", line: 0, column: 0) {"jsonrpc":"2.0","method":"response","params":{"Ok":[{"Ok":{"Value":{"value":{"Row":{"entries":{"pid":{"value":{"Primitive":{"Int":1355}},"tag":{"anchor":null,"span":{"start":0,"end":2}}},"name":{"value":{"Primitive":{"String":"nu_plugin_core_p"}},"tag":{"anchor":null,"span":{"start":0,"end":2}}},"status":{"value":{"Primitive":{"String":"Running"}},"tag":{"anchor":null,"span":{"start":0,"end":2}}},"cpu":{"value":{"Primitive":{"Decimal":3.5696399999999997}},"tag":{"anchor":null,"span":{"start":0,"end":2}}},"mem":{"value":{"Primitive":{"Filesize":1654784}},"tag":{"anchor":null,"span":{"start":0,"end":2}}},"virtual":{ [...]

This actually goes on for several pages(!). Here's the full output: https://gist.github.com/jzaefferer/594f5b5bf64d0f06fede9b7458092f55

**Expected behavior**
What `ps` is actually supposed to do

**Configuration (please complete the following information):**
 - OS: macOS 10.15.5
 - Nu version: 0.16.1 5e722181
 - Optional features (if any): built with `cargo install --path . --force --features=stable`

Running `sys` I get the same initial error (error: Error: Error while processing begin_filter response: Error("unknown variant `Filesize`, expected one of `Nothing`, `Int`, `Decimal`, `Bytes`, `String`, `Line`, `ColumnPath`, `Pattern`, `Boolean`, `Date`, `Duration`, `Range`, `Path`, `Binary`, `BeginningOfStream`, `EndOfStream`", line: 0, column: 0)) but then the rest of the output is different, a lot shorter.

**Comment by fdncred** [comment]
@jzaefferer I'm guessing this is because @jonathandturner changed `Bytes` to `Filesize` recently in #2153. Maybe there is some place we missed.

**Comment by jonathandturner** [comment]
@jzaefferer - you might have an older version of the plugin for `ps` installed. You could try installing from source `cargo install --path . --features=stable` to make sure you have a more up-to-date plugin.

**Comment by jzaefferer** [comment]
Yep, looks like I was building with outdated dependencies. https://www.nushell.sh/book/en/installation.html never mentions `cargo update`, even though that seems to be necessary when pulling updates (not when doing a fresh clone/initial install, I guess).
