### ISSUE TITLE
Incorrect group-by example (or implementation?)

### ISSUE THREAD

**Issue by jzaefferer** [nushell/nushell#2211]
**Describe the bug**
`group-by --help` provides this example:

```
echo [1 3 1 3 2 1 1] | group-by { echo `({{$it}} - 1) % 3` | calc | str from }
error: Unknown column
  ┌─ shell:1:33
  │
1 │ echo [1 3 1 3 2 1 1] | group-by { echo `({{$it}} - 1) % 3` | calc | str from }
  │                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ row does not contain this column
```
The description is "write pipelines for a more involved grouping key", which doesn't tell me what this is actually supposed to do.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): OSX
 - Nu version (you can use the `version` command to find out): latest from main
 - Optional features (if any): stable build

**Comment by jzaefferer** [comment]
I rebuilt my nu version after doing `cargo update` (I always assumed that `cargo install` will update implicitly) and now I get a different result, but it still looks wrong:
```
echo [1 3 1 3 2 1 1] | group-by { echo `({{$it}} - 1) % 3` | calc | str from }
───────┬────────────────
 error │ [table 7 rows]
───────┴────────────────
```
With `| get error` it looks like this:
```
echo [1 3 1 3 2 1 1] | group-by { echo `({{$it}} - 1) % 3` | calc | str from } | get error
───┬───
 0 │ 1
 1 │ 3
 2 │ 1
 3 │ 3
 4 │ 2
 5 │ 1
 6 │ 1
───┴───
```

**Comment by andrasio** [comment]
@jzaefferer Can't reproduce.

```
echo [1 3 1 3 2 1 1] | group-by { echo `({{$it}} - 1) % 3` | calc | str from }
  #   0                2                1
────────────────────────────────────────────────────────
  0   [table 4 rows]   [table 2 rows]   [table 1 rows]
```

What is the output of: ```echo [1 3 1 3 2 1 1] | echo `({{$it}} - 1) % 3` | calc | str from | debug --raw``` in your build?

**Comment by andrasio** [comment]
@jzaefferer 
Ohhhhhhh `calc` is now a subcommand of `math` and renamed as `eval`. Could you try:

```
echo [1 3 1 3 2 1 1] | group-by { echo `({{$it}} - 1) % 3` | math eval | str from }
```

**Comment by jzaefferer** [comment]
That works better, I guess?
```
echo [1 3 1 3 2 1 1] | group-by { echo `({{$it}} - 1) % 3` | math eval | str from }
───┬────────────────
 0 │ [table 4 rows]
 2 │ [table 2 rows]
 1 │ [table 1 rows]
───┴────────────────
```
I still don't understand what it does or is supposed to do.

**Comment by andrasio** [comment]
@jzaefferer I'ts not a great example but, the block is taking a value, computing it's modulus against 3 and that result is the key to store the value.

**Comment by jzaefferer** [comment]
Alright, so I guess the example needs an update (to use `math eval`). And you could add that description.
