### ISSUE TITLE
Unable to start vi or nvim via alias

### ISSUE THREAD

**Issue by lpil** [nushell/nushell#2218]
**Describe the bug**

I am running nushell on Ubuntu within Windows 10 using WSL2 + Windows Terminal.

I have the following config:

```toml
startup = [
  "alias n [] { nvim }",
  "alias v [] { vi }",
]
```

When I then run `v` or `n` the terminal hangs without printing anything.

With nvim if I press `ctrl-c` nushell crashes and prints this:

![image](https://user-images.githubusercontent.com/6134406/87863344-154b9e80-c952-11ea-9272-ae6c2ca59ab3.png)

With vi the terminal no longer responds to anything and I have to kill vi from another terminal.

Once killed it prints this and nushell resumes as per usual.

![image](https://user-images.githubusercontent.com/6134406/87863376-55ab1c80-c952-11ea-8ac1-e191fc9cc146.png)

**To Reproduce**
1. Set config as above
2. Run `v`

**Expected behavior**
Vi (or nvim for n) should start and function normally.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Ubuntu within Windows 10 using WSL2 + Windows Terminal. 
 - Nu version (you can use the `version` command to find out): 0.16
 - Optional features (if any):

```
louis /mnt/c/Users/louis > ls ~/bin/nu*
  #    name                                   type   size      modified
────────────────────────────────────────────────────────────────────────────
  0    /home/louis/bin/nu                     File   21.6 MB   2 weeks ago
  1    /home/louis/bin/nu_plugin_binaryview   File    5.2 MB   2 weeks ago
  2    /home/louis/bin/nu_plugin_fetch        File    6.3 MB   2 weeks ago
  3    /home/louis/bin/nu_plugin_inc          File    4.5 MB   2 weeks ago
  4    /home/louis/bin/nu_plugin_match        File    5.6 MB   2 weeks ago
  5    /home/louis/bin/nu_plugin_post         File    6.3 MB   2 weeks ago
  6    /home/louis/bin/nu_plugin_ps           File    4.7 MB   2 weeks ago
  7    /home/louis/bin/nu_plugin_start        File    4.9 MB   2 weeks ago
  8    /home/louis/bin/nu_plugin_sys          File    5.2 MB   2 weeks ago
  9    /home/louis/bin/nu_plugin_textview     File    9.2 MB   2 weeks ago
  10   /home/louis/bin/nu_plugin_tree         File    5.3 MB   2 weeks ago
```

**Comment by thegedge** [comment]
Works fine for me outside of an alias, so this feels like a problem with aliases. Likely how we provide stdin into an alias doesn't use the special empty stream that we use elsewhere.

**Comment by jgelens** [comment]
Patch #2224 fixed it for me.

**Comment by jonathandturner** [comment]
@jgelens - that's good news. 

@lpil - are you able to also test to see if the latest fixes have fixed your issue?

**Comment by lpil** [comment]
I'll have a test tomorrow, cheers :)

**Comment by jgelens** [comment]
@lpil I'm not sure if aliasing neovim works nicely yet until #1884 is implemented. e.g. `nvim file1.txt file2.txt` does not work. A symlink might be better until then.

**Comment by lpil** [comment]
@jgelens I was going to open an issue to how to do that very thing! I shall eagerly watch that issue. Thanks

**Comment by thegedge** [comment]
I think https://github.com/nushell/nushell/issues/1716 is the issue to watch for that. Closing this issue, since it's fixed (verified locally). If you want to open multiple files, for now you could do something like this:

```
alias n [a b c] { nvim $a $b $c }
```

We currently ignore empty values, so you could easily add more to that to work for most of your use cases 🙂
