### ISSUE TITLE
paint_textview needs optimization

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#222]
Currently, paint_textview will reallocate and render the buffer every frame. As the buffer contains the whole contents of the file, we don't need to do this every frame but instead only when the size of the terminal changes.

**Comment by arashout** [comment]
Is `paint_textview` still a thing? Couldn't grep for it in the codebase

**Comment by jonathandturner** [comment]
We switched to using `bat` so we can close this now.
