### ISSUE TITLE
Git pretty example from documentation not working

### ISSUE THREAD

**Issue by pegak** [nushell/nushell#2227]
**Describe the bug**
I use example from [here](https://www.nushell.sh/cookbook/en/git.html) - Parse formatted commit messages. Output is `error: Error: sh: nu: No such file or directory`.

**To Reproduce**
1. Run `git log "--pretty=format:%h<nu>%aN<nu>%s<nu>%aD" | lines`
2. See `error: Error: sh: nu: No such file or directory`

**Expected behavior**
Output as shown in documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/12586960/87912645-0b1ec280-ca6e-11ea-90a3-7306c088dca3.png)

**Configuration (please complete the following information):**
 - OS:   macOS 10.15.6 (19G71a)
 - Nu version (you can use the `version` command to find out): 0.16.0

Add any other context about the problem here:

`git log --pretty='format:%h<nu>%aN<nu>%s<nu>%aD' | lines` works. But it is not written in the documentation this way.

**Comment by notryanb** [comment]
@pegak I've updated the [cookbook documentation](https://www.nushell.sh/cookbook/en/git.html) as I ran into the same issue on nushell version `0.19` for Windows. You may also want to upgrade to the latest nu version. My understanding is that the parser has been changing since `0.16`

**Comment by pegak** [comment]
Yeah, I am already on 0.19 with features=extra. :)

**Comment by pegak** [comment]
And example works now.
