### ISSUE TITLE
Add a limit to the `split` command

### ISSUE THREAD

**Issue by robyoung** [nushell/nushell#2229]
**Is your feature request related to a problem? Please describe.**
When spliting rows by a character sometimes the split character is used multiple times in the last column. For example;
For example `apt list --installed` returns lines like `wget/focal,now 1.20.3-1ubuntu1 amd64 [installed]` and I would like to split on space. However, lines sometimes look like `update-manager-core/focal,now 1:20.04.9 all [installed,upgradable to: 1:20.04.10.1]` and the last section would be split into multiple parts.

**Describe the solution you'd like**
I would like to be able to limit the number of columns `split column` splits into.
```
> apt list --installed | lines | split column " " --limit 4
─────┬────────────────────────────────┬────────────────────────┬─────────┬───────────────────────
  #  │ Column1                        │ Column2                │ Column3 │ Column4
─────┼────────────────────────────────┼────────────────────────┼─────────┼───────────────────────
   1 │ wget/focal,now                 │ 1.20.3-1ubuntu1        │ amd64   │ [installed]
   2 │ update-manager-core/focal,now  │ 1.20.4.9               │ all     │ [installed,upgradable to: 1:20.04.10.1]
─────┴────────────────────────────────┴────────────────────────┴─────────┴───────────────────────
```

**Describe alternatives you've considered**
I also considered being able to split by regular expression which I think would also be useful. However, for the case described above a regular expression would be much more complex than a limit.

**Additional context**
```
❯ sys | get host
──────────┬─────────────────────────────────────────────
 name     │ Linux
 release  │ 5.4.0-40-generic
 version  │ #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020
 hostname │ development
 arch     │ x86_64
 uptime   │ 4:05:36
 sessions │ [table 1 rows]
──────────┴─────────────────────────────────────────────
```

**Comment by fdncred** [comment]
How about this? `apt list --installed | lines |  parse "{pkg} {version} {platform} {status}"`

**Comment by robyoung** [comment]
Oh yes! `parse` looks like exactly what I want. Thank you 🙇‍♂️
