### ISSUE TITLE
The Nushell Test Suite Is Running Extremely Slow

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#2234]
**Describe the bug**
In the past, the Nushell test suite would run fairly fast for me.  After it was done compiling, the tests would run in 5 or so seconds on my machine.  Today, the tests took 10-15 minutes to run.  At first, I thought it was a number of things, maybe my most recent upgrade to Rust 1.45.0, but after downgrading, I found that wasn't the case.  I had just upgraded my OS version as well, but that upgrade happened after I noticed the test speed issue, so I knew that wasn't the case.  I then tried running the tests in a different shell (I normally run Nushell in zsh), but that didn't change anything.

I decided to run `git bisect`, starting at about a month ago in the commits.  I noticed the tests ran like normal here, so I worked through `git bisect` until it spit this out:

https://github.com/nushell/nushell/commit/6829ad7a3060a4c9a8732a344fac481377dcae2b

After reverting this commit, the tests ran with their normal speed of a 5 or so seconds.

I think it was proposed to revert this commit to bring back the speed of the tests, and then re-open the original issue the commit was addressing (https://github.com/nushell/nushell/issues/2193), and try to find an alternative solution to it.

@jonathandturner 
@fdncred 

**Configuration (please complete the following information):**
 - macOS 10.15.6
 - 0.16.1

**Comment by fdncred** [comment]
I think https://github.com/nushell/nushell/pull/2235 should be rolled back. Please see that link for why.
