### ISSUE TITLE
Unable to edit or remove history file

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#2236]
**Describe the bug**
I am unable to alter the history file manually.

**To Reproduce**
0. There is a history file at `$nu.history-path`
1. Edit `$nu.history-path`
2. The contents of the file get reset to the state at step 0.
3. Remove `$nu.history-path`
4. The history file re-appears in the state at step 0.

**Expected behavior**
I would expect it being possible to edit/remove the history file

**Configuration (please complete the following information):**
 - OS (e.g. Windows):
ArchLinux
 - Nu version (you can use the `version` command to find out):
0.19.0 (47c53469349bef5013cea3a9c938de1a857030bb)  built with `cargo build --release --features=stable`
 - Optional features (if any):
using `dwm` window manager

**Comment by kubouch** [comment]
The reason I suspect window manager to be involved is that the commands passed to my launch-bar (e.g., libreoffice, I don't have any non-terminal text editors) get appended to the history file. So the dwm seems to pass that command into whatever shell I'm using. Then, nu probably copies that file into RAM and saves it back when the command is over. This would explain why my edits have no effect.

**Comment by kubouch** [comment]
@Acidic9 I'm not having the issue anymore. The edits to the history file persist. Would you mind writing up more detailed reproduction steps?

**Comment by Acidic9** [comment]
I just solved it now. I had to dig into the source code of nushell to find the history txt file location. It turned out to be: `/Users/ari/Library/Application Support/org.nushell.nu/history.txt`, and I just opened the file and deleted everything inside it and saved.

After running the `history` command, it populated the file with:
```
#V2
history
```
Which seems correct.

**Comment by kubouch** [comment]
The history file location should be stored in `$nu.history-path`, I don't think you need to dig the source for that. Or am I missing something?

Anyway, I'll close this and if there are any more issues with the history file, please tag me to reopen or file a new issue. Thanks!

**Comment by kubouch** [comment]
Confirmed, `history --clear` doesn't work for me either. Seems like the problem of this issue is a bit different so I started a new issue.
