### ISSUE TITLE
Cannot call .bat file on Windows

### ISSUE THREAD

**Issue by demilich1** [nushell/nushell#2240]
When running nushell on Windows, I could not find any way to execute a batch file which resides in the current folder.

1. navigate to a folder which contains a batch file (or create a new batch file 'test.bat' in the current folder with the content
`echo "Hello, world"`
2. try calling test.bat, ^test.bat, ./test.bat etc
3. Notice the output 'command not found' no matter which way you try it

**Configuration (please complete the following information):**
 - OS: Windows 10 version 1909
 - Nu version: nushell 0.17.0

**Comment by jankoprowski** [comment]
`.\file.bat` works for me:

![image](https://user-images.githubusercontent.com/125283/95684964-33453a00-0bf5-11eb-98f1-2014450796ec.png)

**Comment by robinv85** [comment]
Can confirm it works with a backslash. I was also trying with `./file.bat` but that one is for *nix file systems so maybe this is not an actual bug :)

Seems like a lot of applications actually support both slashes and backslashes for file paths on Windows so this is nice to have.

**Comment by demilich1** [comment]
I can also confirm it works with backslash. However, the tab auto complete does not work for .bat files. I also like the idea of maybe supporting both slash and backslash.
