### ISSUE TITLE
Nu does not resolve auto-completed files/folders paths with "\", and does not auto-complete paths with "/"

### ISSUE THREAD

**Issue by gerred** [nushell/nushell#2241]
**Describe the bug**
When attempting to `open` a file in Nu to a valid path using `/` as a path separator, Nu works as expected. However, tab-based autocomplete of file paths does not work.

When attempting to `open` a file in Nu to an equally valid path using `\` as a separator, Nu's tab-based autocompletion works as expected. However, attempting to access the file results in the following error:

```
error: Error opening file: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  ┌─ shell:1:6
  │
1 │ open ~\.gitconfig
  │      ^^^^^^^^^^^^ Error opening file
````

**To Reproduce**
Steps listed in the description.

**Expected behavior**

**Screenshots**

**Configuration (please complete the following information):**
 - Windows 10
 - 0.17.0
 - Optional features (if any): Stable

Shown on video to @fdncred.

**Comment by fdncred** [comment]
In `0.16.1` and `0.17.0` I get
```
C:\Users\username()
07/22/2020 01:41:26.067 PM ▶ open ~\Desktop\input-csv.txt
error: Cannot canonicalize file "C:\\Users\\username\\~\\Desktop\\input-csv.txt" because Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }
  ┌─ shell:1:6
  │
1 │ open ~\Desktop\input-csv.txt
  │      ^^^^^^^^^^^^^^^^^^^^^^^ Cannot canonicalize
```

**Comment by gerred** [comment]
I've seen that too on certain outputs when I tried, not sure in some cases what I did differently (I was changing a lot of underlying env at the same time).

**Comment by thegedge** [comment]
I'm (slowly) working on refactoring completion, with the intent to eventually write our own completer for nushell. I think this issue will eventually be resolved with that.

For now though, I can mention that we use `rustyline`'s completer, so it only works with `\` on Windows, and `/` elsewhere (because of https://doc.rust-lang.org/std/path/constant.MAIN_SEPARATOR.html). Since we have been holding off on having an escape character – typically `\` - we could probably support both in our completer.

So I'm thinking we can focus on the "can't open file" and "cannot canonicalize" issues, hopefully get those fixed 🙂

**Comment by gerred** [comment]
I'd be happy to take a shot at the latter - while I know Rust, I haven't done any of it on Windows (and this seems decently platform specific enough) and some pointers of where I should look in the codebase / things that come to mind would be helpful.

**Comment by thegedge** [comment]
If the only issue right now is `canonicalize`, it's probably here: https://github.com/nushell/nushell/blob/a36d2a1586fda5f5f70c065e898455527d265512/crates/nu-cli/src/commands/open.rs#L195-L201

If it still has trouble opening the file, there's no clear location where that could be happening, but if I had to guess it would be https://github.com/nushell/nushell/blob/a36d2a1586fda5f5f70c065e898455527d265512/crates/nu-cli/src/commands/open.rs#L216

**Comment by pwnorbitals** [comment]
@gerred Could you make any progress on this issue ? I’d like to help get this issue fixed

**Comment by fdncred** [comment]
@gerred Any updates? If not, we can  assign this to @pwnorbitals to help out.

**Comment by fdncred** [comment]
@pwnorbitals I assigned you. Have at it.

**Comment by gerred** [comment]
Thanks @pwnorbitals for taking this on - I'm doing a bit of a sabbatical and wasn't checking up on this issue.

**Comment by gerred** [comment]
@pwnorbitals Have you had a chance to make any progress here? If not, I'm back at it and can take a crack.

**Comment by gerred** [comment]
@fdncred will you re-add me as an assignee as well?

**Comment by gerred** [comment]
Thanks @jonathandturner!

**Comment by fdncred** [comment]
please have at it!

**Comment by jonathandturner** [comment]
Related bugs were recently fixed, and I believe they include this one. If you're still seeing the issue, please reopen.
