### ISSUE TITLE
Add `Tau` Constant to `Math Eval`

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#2258]
According to the documentation:

https://doc.rust-lang.org/nightly/std/f64/consts/constant.TAU.html

The `Tau` constant will be stabilized in Rust 1.47.  We could add this to our list of constants (currently `pi` and `e`) in `Math Eval` when Rust 1.47 is officially released.

**Comment by JosephTLyons** [comment]
I realize Tau is 2pi, but I believe that some people prefer to use Tau over 2pi and also, if you check the source, the constants are slightly different - I assume from some sort of floating point rounding.

**Comment by thegedge** [comment]
Note, we use https://docs.rs/meval/0.2.0/meval/, so I think the work would actually have to be done on that crate and then updated here.

**Comment by JosephTLyons** [comment]
Ahh yeah.  I see that now.  I guess this can be used as a reminder to see if the crate maintainers over there end up adding it or not.

**Comment by fdncred** [comment]
I'm still trying to learn rust but I thought one could implement an extension trait to add functionality to an external crate that you don't own. Is this not possible in this Tau example?

**Comment by thegedge** [comment]
Actually, now that you mention it @fdncred, there's a way to evaluate with a [`Context`](https://docs.rs/meval/0.2.0/meval/struct.Context.html), so perhaps we could just put the var in there and call it a day.

**Comment by JosephTLyons** [comment]
That's cool.  I did create an issue in the `meval-rs` repo here:

https://github.com/rekka/meval-rs/issues/23

Not sure if the original author will be interested in adding it or not, but figured it wouldn't hurt to try.

**Comment by fdncred** [comment]
@JosephTLyons I prototyped this in `eval.rs` as @thegedge suggested.
```rust
pub fn parse<T: Into<Tag>>(math_expression: &str, tag: T) -> Result<Value, String> {
    let mut ctx = meval::Context::new();
    ctx.var("tau", 6.28318530717958647692528676655900577f64);
    match meval::eval_str_with_context(math_expression, &ctx) {
        Ok(num) if num.is_infinite() || num.is_nan() => Err("cannot represent result".to_string()),
        Ok(num) => Ok(UntaggedValue::from(Primitive::from(num)).into_value(tag)),
        Err(error) => Err(error.to_string().to_lowercase()),
    }
}
```
Seems to work.
![image](https://user-images.githubusercontent.com/343840/88673742-991e2d00-d0ae-11ea-8874-16dd2895dae7.png)

Feel free to add it and other variables/constants you think are missing.

**Comment by rjboas** [comment]
Hi, I just stumbled across this and had a quick look and thought I'd document a quick update.

Tau has been stabilised in std now that Rust 1.47 has been released.

As said before, meval doesn't have tau and the project seems to be inactive, but the `meval::Context` solution could be implemented using std now.

**Comment by fdncred** [comment]
@rjboas Thanks for the update. We would welcome this via PR if you feel so inclined. It does indeed look like `meval` is inactive.

**Comment by JosephTLyons** [comment]
There's currently an issue, I tried to add Tau the day Rust 1.47 was released, but Meval truncates the constants it provides.  The truncation is enough that there is no longer a difference between `2 * pi` and `Tau`, so I never opened a PR.
