### ISSUE TITLE
`path` commands should point at the command when run by themselves

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2261]
**Describe the bug**
Run `path expand` by itself:

```
26/07/2020 16:15:52> path expand
error: value is not string or path
  ┌─ shell:1:1
  │
1 │ path expand
  │ ^ got nothing
```

**To Reproduce**
1. `path expand` by itself
2. Get curious error message
3. 

**Expected behavior**
We should make sure the spans point to the correct locations for errors. Shouldn't be too bad, we get the name_tag passed in and could use that.

**Comment by warrenseine** [comment]
I'm not sure my fix work. Now we get:

```
/Users/w.seine/Code/nushell(fix-path-error-span)> path expand
error: value is not string or path
  ┌─ shell:1:1
  │
1 │ path expand
  │ ^^^^^^^^^^^
  │ │
  │ got nothing
  │ originates from here
```

**Comment by onthebridgetonowhere** [comment]
This does not seem to yield an error anymore. @jonathandturner - is this still a problem? If not, we should close this issue?
