### ISSUE TITLE
Fold/reduce command

### ISSUE THREAD

**Issue by bailey-layzer** [nushell/nushell#2267]
**Is your feature request related to a problem? Please describe.**
Similar to `each` and the `math` commands, I'd like to reduce a list with an arbitrary block.

**Describe the solution you'd like**
A `fold` (`reduce`, `agg`, ...?) command. Say I have a list of charges by month:
```
❯ open example.json | from json
───┬───────┬───────
 # │ month │ total 
───┼───────┼───────
 0 │     2 │    30 
 1 │     3 │    10 
 2 │     4 │     3 
 3 │     5 │    60 
───┴───────┴───────
```
The `fold` command would allow summing these while applying interest to the total after each month:
``open example.json | from json | get total | fold 0 { = $it + $( math eval `{{$acc}}^1.05` )}``

**Describe alternatives you've considered**
The example I've thought of can already be accomplished with `each`:
``... | get total | each -n { = $it.item * $( math eval `(5 - {{$it.index}})^1.05` )} | math sum``

**Additional context**
I'd like to work on this if there's interest in it. I thought I'd seen an incomplete reduce-by command similar to this, but I can't find it anymore.

**Comment by thegedge** [comment]
@andrasio you'd likely be interested here. I think I've brought up the idea of some command to fold, and perhaps express a lot of the aggregation methods we have in terms of that (instead of custom implementations in nushell).

**Comment by jonathandturner** [comment]
My one nit with having it is to use a more beginner-friendly name. @bailey-layzer mentioned `reduce` as one possibility.
