### ISSUE TITLE
Request: Publish WebAssembly package to NPM

### ISSUE THREAD

**Issue by KSXGitHub** [nushell/nushell#2275]
Node.js tooling is lacking a cross-platform shell (sh, bash, zsh, and batch are platform-specific while JavaScript itself is too verbose for a shell language).

**Comment by jonathandturner** [comment]
For this to work well, we may need to add wasi(?) support as well so that you could access the local filesystem. To get around this in the demo, we're currently using a fake filesystem. For NPM, you'd want to be able to access the real one.

**Comment by KSXGitHub** [comment]
WASI is just an emulation of UNIX interface to enable porting old programs (ones that are not created with WASM in mind) to the web. I guess nushell's WASM in the web demo has an API? It would be more powerful if one can manipulate structured input/output of nushell (i.e. as JavaScript objects). I don't think nushell's API would be too complex to require WASI either, JS side can provide callbacks for file system access and executing subprocesses.

My point is, I think WASI is unnecessary.

**Comment by jonathandturner** [comment]
@KSXGitHub - I've been thinking about this issue. Are you interested in working on it, by chance? I can help mentor, though it seems you may know as much as I do (maybe more?)

**Comment by KSXGitHub** [comment]
@jonathandturner I have some other projects to do at the moment.

**Comment by jonathandturner** [comment]
@KSXGitHub - no worries, I thought I'd ask in case you were interested and had time.
