### ISSUE TITLE
Configuration book command for setting config value is outdated

### ISSUE THREAD

**Issue by djc** [nushell/nushell#2277]
**Describe the bug**

The book doesn't seem to match (the 0.17.0 release of) the actual product:

![Screen Shot 2020-07-30 at 11 55 52](https://user-images.githubusercontent.com/158471/88909622-a3c9f500-d25b-11ea-8c19-c426e4ab1b52.png)

<img width="449" alt="Screen Shot 2020-07-30 at 11 57 00" src="https://user-images.githubusercontent.com/158471/88909755-ca882b80-d25b-11ea-8fd8-604dae0951e3.png">

**Comment by thegedge** [comment]
I think this will be fixed by https://github.com/nushell/book/pull/117
