### ISSUE TITLE
Have `str collect` take an optional separator value

### ISSUE THREAD

**Issue by coolshaurya** [nushell/nushell#2286]
**Is your feature request related to a problem? Please describe.**
It would be nice to have `str collect` take a optional separator value

**Describe the solution you'd like**
With this -
 `echo 1..5 | str from | str collect "|"` 
will return 
`1|2|3|4|5`

 `echo a b c d e f g h | str from | str collect  $(char newline)`
will return 
```
a
b
c
d
e
f
g
h
```

**Describe alternatives you've considered**
Make a new subcommand in `str` for this functionality

**Additional context**
None

**Comment by fdncred** [comment]
oooh!  I like that idea!

**Comment by JosephTLyons** [comment]
Is someone already working on this?  I can probably add it if not.
