### ISSUE TITLE
`config load` does not appear to work

### ISSUE THREAD

**Issue by jonknapp** [nushell/nushell#2287]
**Describe the bug**
Running `config load nu.toml` to load a local configuration file called `nu.toml` shows table output as if it was loaded, but it does not change anything related to the current running nu shell. The same happens when I use an absolute path to the config file.

**To Reproduce**
1. copy config to a new file: `cp $(config path) nu.toml`
2. clear config `config clear`
3. start new terminal / nu session
4. attempt to load config: `config load nu.toml`
5. see tabular output of config, but shell session is unchanged from the config (ex: starship enabled)

**Expected behavior**
I expected the command to load the config contents into my current shell's session.

**Screenshots**
<img width="1116" alt="example commands not updating shell config" src="https://user-images.githubusercontent.com/8836231/89107940-9d29b200-d402-11ea-88f4-5afd2bf290b6.png">
[config load trace.log of similar attempt](https://github.com/nushell/nushell/files/5011058/config.load.trace.log)

**Configuration (please complete the following information):**
 - OS: Mac 10.15.6
 - Nu version: 0.17.0 installed through homebrew using `~/homebrew` as install directory for homebrew

I did try trimming down the config I attempted to load to only `use_starship = true` and it did not make a difference.

**Comment by avandesa** [comment]
I just ran into this same issue on Windows as well. On commit 724b177.

**Comment by rgbrizzlehizzle** [comment]
Any movement on this? same issue on Big Sur and Nushell `0.29.0`
