### ISSUE TITLE
Autocomplete now always asks if it should display the possibilities even if there are only a few

### ISSUE THREAD

**Issue by nickolay** [nushell/nushell#2304]
**Describe the bug**
`completion_type` / `completion_prompt_limit` defaults regressed since 0.17.0.

**To Reproduce**
1. `git clone git@github.com:nushell/nushell.git && cd nushell && cargo run`
2. Type the letters `ls`
3. Hit TAB twice

**Actual behavior**: displays only "Display all 8 possibilities? (y or n)"

**Expected behavior**: Display the first 100 options (e.g. `ls`, `lsof`, etc) without asking. This can be achieved by changing the nushell config from empty to:
```
[line_editor]
completion_type = "list"
completion_prompt_limit = 100
```

**Configuration (please complete the following information):**
 - OS (e.g. Windows): macOS 10.15.5
 - Nu version (you can use the `version` command to find out): master (6202705eb621dc9edaec0eca2556d665bac9140e)
 - Optional features (if any): N/A

**Details**
Recent changes in PR https://github.com/nushell/nushell/pull/2244 and the following changed the defaults: `completion_prompt_limit` used to be 100 ([defined in rustyline](https://github.com/kkawakam/rustyline/blob/2fe886c9576c1ea13ca0e5808053ad491a6fe049/src/config.rs#L157))

Additionally, adding an _empty_ `[line_editor]` section to nushell config changes the default of `completion_type` from "list" (the [nushell default on non-windows](https://github.com/nushell/nushell/blob/e1c5940b042683eca82b338158dac47d194c7b67/crates/nu-cli/src/cli.rs#L549)) to "circular" (the [rustyline default](https://github.com/kkawakam/rustyline/blob/2fe886c9576c1ea13ca0e5808053ad491a6fe049/src/config.rs#L156)), which is probably not intended and very confusing.

CC @fdncred

**Comment by fdncred** [comment]
You're right. I defaulted to non-rustyline defaults when I made this change. I just submitted a PR to match most of rustyline's defaults https://github.com/nushell/nushell/pull/2305.

I'm not sure how completion_type is getting set to circular because if there's no completion_type, it defaults to a platform specific value. Will have to investigate further.

**Comment by nickolay** [comment]
> if there's no completion_type, it defaults to a platform specific value

The problem is that only happens if the [value is unknown](https://github.com/nushell/nushell/blob/6202705eb621dc9edaec0eca2556d665bac9140e/crates/nu-cli/src/cli.rs#L623) or if [the entire `line_editor` section does not exist](https://github.com/nushell/nushell/blob/6202705eb621dc9edaec0eca2556d665bac9140e/crates/nu-cli/src/cli.rs#L682). If the section does exist, but does not have an entry for completion_type, it remains set to rustyline's default.

**Comment by fdncred** [comment]
Maybe I should set all the defaults at the beginning of that function and then if others are set, they'll override the defaults.

**Comment by nickolay** [comment]
That's a great idea. I think you can also rely on rustyline's defaults where nushell doesn't need to override them (e.g. the `completion_prompt_limit`).

**Comment by fdncred** [comment]
@nickolay Just pushed this one to hopefully take care of this issue https://github.com/nushell/nushell/pull/2306

**Comment by fdncred** [comment]
Should be fixed now. Thanks!

**Comment by nickolay** [comment]
Yep, works fine now. Thanks for the quick fix!
