### ISSUE TITLE
Can't use ssh-add to unlock passphrase-protected keys

### ISSUE THREAD

**Issue by agateau** [nushell/nushell#2311]
**Describe the bug**

My ssh keys are protected by a passphrase, but typing that passphrase all the time is annoying, so I usually add them to ssh-agent using this command:

```
ssh-add ~/.ssh/id_rsa
```

Then any ssh-based command (such as `ssh`, `rsync`, `git fetch` and `git push`) won't ask for the passphrase. Unfortunately, `ssh-add` does not work with Nushell. It fails like this:

```
/home/agateau> ssh-add ~/.ssh/id_rsa
Error connecting to agent: No such file or directory
```

Looking at the process list we can see ssh-agent is running:

```
/home/agateau> ps | where name == "ssh-agent"
───┬────────┬───────────┬──────────┬────────┬──────────┬─────────
 # │ pid    │ name      │ status   │ cpu    │ mem      │ virtual 
───┼────────┼───────────┼──────────┼────────┼──────────┼─────────
 0 │ 312957 │ ssh-agent │ Sleeping │ 0.0000 │   2.8 MB │  6.2 MB 
 1 │ 313223 │ ssh-agent │ Sleeping │ 0.0000 │ 471.0 KB │  6.2 MB 
───┴────────┴───────────┴──────────┴────────┴──────────┴─────────
```

But the `SSH_AGENT_PID` environment variables are wrong:

```
/home/agateau> echo $nu.env | pivot | where Column0 =~ SSH
───┬───────────────┬────────────────────────────────────
 # │ Column0       │ Column1                            
───┼───────────────┼────────────────────────────────────
 0 │ SSH_AGENT_PID │ 213361                             
 1 │ SSH_AUTH_SOCK │ /tmp/ssh-pNu5MVUlVSa4/agent.213318 
───┴───────────────┴────────────────────────────────────
```

If I look at the same variables from another shell it says:

```
agateau$ env | grep ^SSH
SSH_AGENT_PID=313223
SSH_AUTH_SOCK=/tmp/ssh-mVRlIIZ5y9kQ/agent.313182
```

Here we can see `$SSH_AGENT_PID` matches with the pid of the running `ssh-agent` process.

**To Reproduce**
1. Create a passphrase-protected ssh key with `ssh-keygen`
2. Make sure `ssh-agent` is running
3. Try to add the key to it with `ssh-add /path/to/the/private/key`

**Expected behavior**
Key is not added, `ssh-add` cannot communicate with `ssh-agent`.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Kubuntu 20.04
 - Nu version (you can use the `version` command to find out):  0.17.0

**Comment by fdncred** [comment]
If you set those $nu environment variables to what they should be, do the ssh-commands work? I'm wondering if the env vars are changing by a process spun up or restarted in bash and nushell isn't watching the vars for changes.  Just a guess.

**Comment by agateau** [comment]
I tried to, but the variable override system does not let me set more than one variable at a time, and setting only `SSH_AGENT_PID` fails :( 

```
/home/agateau> SSH_AGENT_PID=359288 SSH_AUTH_SOCK=/tmp/ssh-fAIPgzX2WpQm/agent.359244 ssh-add ~/.ssh/id_rsa
error: Command not found
  ┌─ shell:1:22
  │
1 │ SSH_AGENT_PID=359288 SSH_AUTH_SOCK=/tmp/ssh-fAIPgzX2WpQm/agent.359244 ssh-add ~/.ssh/id_rsa
  │                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ command not found
```

**Comment by fdncred** [comment]
Right, but you could edit your `config.toml` file and in the `[env]` section put those variables and values in there, relaunch nu and see what happens.  Just trying to come up with different things. Obviously, this isn't a fix. I think #1832 is partially involved here with your last attempt to a work-around.

**Comment by agateau** [comment]
I found out the problem. Was my fault. For some reason my `config.toml` contained an `[env]` section filled with a "snapshot" of my environment from I don't know when.

:man_facepalming:

Deleting the section fixed the bug. Sorry for the noise.

**Comment by LaffertyDev** [comment]
For future people, I had the same issue. agateau correctly identifies the reason. I recently got a new macbook and followed the recommended install steps from nushell.

As part of this, my `config.toml` file looked something like:

```
[env]
CMD_DURATION_MS = "7"
HOME = "/Users/<IGN>"
LANG = "en_US.UTF-8"
LOGNAME = "<IGN>"
SSH_AUTH_SOCK = "/private/tmp/com.apple.launchd.wTACojsyhn/Listeners"
TERM = "xterm-256color"
TERM_PROGRAM = "Apple_Terminal"
TERM_PROGRAM_VERSION = "443"
TERM_SESSION_ID = "<IGN>"
```

Note the `SSH_AUTH_SOCK`. Removing this, and everything worked as expected.
