### ISSUE TITLE
Option to disable welcome message

### ISSUE THREAD

**Issue by ImGamez** [nushell/nushell#2313]
Add option in the config to disable the welcome message "Welcome to Nushell 0.17.0 (type 'help' for more info)".
Gives a cleaner look to the terminal.

**Comment by jonathandturner** [comment]
We should be able to add a `config` setting for this. Would be a good issue for people just getting started with working on Nu.

**Comment by coolshaurya** [comment]
This issue should be closed as it has been fixed by #2314.
