### ISSUE TITLE
Bash Braces Pattern

### ISSUE THREAD

**Issue by oberien** [nushell/nushell#2317]
Bash (and a lot of other shells) support [braces expansion](https://www.gnu.org/software/bash/manual/html_node/Brace-Expansion.html). In some cases it allows easier commands and reduces typing a prefix multiple times. For example `mv /foo/bar/baz/README.{txt,md}` expands to `mv /foo/bar/baz/README.txt /foo/bar/baz/README.md`. Another (more contrived) example is `echo {1..3}-{1,2}` expanding to `echo 1-1 1-2 2-1 2-2 3-1 3-2`.

Some more examples can be seen [here](https://www.linuxjournal.com/content/bash-brace-expansion), [here](https://unix.stackexchange.com/questions/409065/how-does-curly-brace-expansion-work-in-the-shell) or [here](https://linuxhint.com/bash_shell_brace_parameter_expansion/#a5).

**Comment by oberien** [comment]
This isn't stale.

**Comment by itsMapleLeaf** [comment]
I'd also love to see this. One could maybe userland this in the form of an `expand` command, but I just started using Nu yesterday 😅 would take a while to try to wrap my head around that

**Comment by rosshadden** [comment]
I managed to miss this issue on my first pass looking for a parallel feature in nushell and had [started a discussion](https://github.com/nushell/nushell/discussions/4259) asking if this were possible.
This is such an efficient syntax and I am aware that it might not translate 1:1 to nushell, but the concept of having an extremely convenient, concise way of expressing substring differences would be very cool.

**Comment by metafates** [comment]
I think it's better to address this issues to the https://github.com/nushell/reedline instead

**Comment by sholderbach** [comment]
> I think it's better to address this issues to the [nushell/reedline](https://github.com/nushell/reedline) instead

Reedline tries to stay agnostic with respect to the actual grammar of nushell (so you could also use it for another language) and let nushell implement the details knowing the exact parsing rules. But we certainly would be open to some work to extend the current completion logic to also support smart expansions better.
Currently we treat it mostly as: select an option from suggestions and then mess with the buffer, but that paradigm is not great for expansions where there is one thing you want to happen, while not messing with the experience when interacting with completion options (and only one would be available).
One break from that rule I would like to move to nushell as well is the `bashisms` feature that contains the history based expansions like `sudo !!`

**Comment by id-ekaagr** [comment]
You need this in nu: `("{1..2}" | str expand)`, it's bash eq is `{1..2}`. Thank me later.

**Comment by amtoine** [comment]
yeah, i think this issue can be closed with the addition of `str expand` a few releases back :blush:

**Comment by nightkr** [comment]
Not sure I agree with the closing.. `mv ...("foo-{bar,baz}" | str expand)` is better than nothing, but it's still wildly less convenient to use than (bash's) `mv foo-{bar,baz}`, and feels like a big step up in terms of ceremony from how you would expect a `mv` invocation to look.

**Comment by kuchta** [comment]
I think in these super useful and time-saving cases, like brace expansion or variable expansion, it would be best if nushell could expand them on tab completion.

**Comment by atahabaki** [comment]
unless nushell's string parsing changes `str expand` or similar commands or plugins will be the only option. I'm the maintainer of [bracoxide](https://github.com/atahabaki/bracoxide) crate which `str expand` command depends on. If you have brilliant ideas to implement such as:

- {inc,dec}rement `{7..10}` and `{10..7}`
- custom {dec,inc}rement `{1..10;+2}` and `{10..1;-2}`
- prefix and postfix `{8..10;0=}` => `[08,09,10]` and `{10..8;=0}` => `[10,90,80]`
- optional start/end `{..10}` and `{10..}`
- char range w/ unicode support `{a..z}` and `{A..Z}` (I do not think this will be with bracoxide  v1.0)

Features, if you want to take a look: https://github.com/atahabaki/bracoxide/issues
If you have an idea that you like to share, feel free to share.

I'm currently working on these features with new parsing mechanism that will give proper error/warning messages than current implementation. Besides that I'm hoping to get more performance. We'll see. I just can't motivate myself to work on that awesome crate i built. Anyways, Take care!

**Comment by nik-rev** [comment]
@amtoine could this issue be re-opened? I'd still like to see the syntax directly supported

I want to be able to write this:

```
ls *.{ttf,otf}
```

Instead of:

```
ls ...("*.{ttf,otf}" | str expand | each { into glob })
```

**Comment by atahabaki** [comment]
I can implement this, but if I recall correctly, features like `mkdir {x,y,z}` don't really align with Nushell's philosophy, which emphasizes structured data and powerful pipelines.

I'd be happy to open a PR if this is something the team would like to include in the core language.

I'm glad people are finding `str expand` useful, and I'd love to see it available in more places. Ultimately, though, that decision is up to the Nushell team.

One design question that comes to mind is how this would interact with paths that literally contain braces. If brace expansion were supported by commands like `mkdir`, `ls`, `path exists`, and others, how would users refer to a file or directory named `{foo}` without triggering expansion? Would that require an explicit `--no-expansion` flag, escaping braces, or some other mechanism? I'm curious how the team would approach that.

For context, I'm also working on a rewrite of {bracoxide} to make it more configurable (e.g. customizable escape characters and error collection), so I've been thinking about these kinds of edge cases quite a bit.

**Comment by ErichDonGubler** [comment]
@atahabaki: I'm not @nik-rev, but answering for myself, we already have some special behavior for bare strings with glob expansion. I would expect that brace expansion only gets added to bare strings.

**Comment by atahabaki** [comment]
I’d be happy to work on this. I’ll read through the parser flow first to figure out where brace_expr fits best, especially around the existing glob/path handling. If the team is okay with this direction, I can start exploring an implementation.

**Comment by T3sT3ro** [comment]
Is there a workaround or some way to implement this already with user config, so that those paths/globs expand on TAB? I find myself coming back to nushell once in a while, but stuff like this is what kills ergonomics for me, forcing me to go back to zsh thinking time and time again "ok, nu is neat but it's warts like this in day to day usage are blockers for me".
