### ISSUE TITLE
`ls .file` doesn't list explicitly specified hidden files unless -a is passed

### ISSUE THREAD

**Issue by oberien** [nushell/nushell#2318]
**Describe the bug**
When using `ls` to list a hidden file which was explicitly passed as an argument, it isn't listed unless the `-a` flag is passed. In other shells (tested with bash and zsh), when using `ls` and passing a hidden file as explicit argument, that file is listed no matter if the `-a` flag is passed or not.

For glob patterns / [filename expansion](https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html) this is similar. In other shells `*.foo` only matches non-hidden files, while `.*.foo` matches on hidden files, no matter if `-a` is passed or not. For example `ls -a *.foo` would only return non-hidden files (even if `-a` is specified), while `.*.foo` will find hidden files, even if `-a` isn't specified. In nushell, `ls *.foo` or `ls .*.foo` won't return any hidden files, while `ls -a *.foo` and `ls -a .*.foo` both will return hidden files.  
The same should be applied to folder-globbing. In sh, `ls **/*` only lists non-hidden files while in nushell, it lists all files, including hidden ones, even without the `-a` parameter.

**To Reproduce**
1. `touch .testdotfile`
2. `ls .testdotfile`: nothing is printed
3. `ls -a .testdotfilee`: the file is listed

**Expected behavior**: Hidden files which are explicitly specified as argument (or via a glob pattern) should be listed even without the `-a` flag. For glob patterns, `*.foo` should only ever return non-hidden files, while `.*.foo` should always return hidden files.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): arch linux 5.7.12-arch1-1
 - Nu version (you can use the `version` command to find out): Manually compiled from #2296.

**Comment by samuelvanderwaal** [comment]
@thegedge This appears to be fixed so the issue can probably be closed?
