### ISSUE TITLE
After pasting, the cursor is before the last character in the pasted text instead of after it

### ISSUE THREAD

**Issue by mhmdanas** [nushell/nushell#2319]
**Describe the bug**
After pasting some text, the cursor is before the last character in the pasted text.

**To Reproduce**
1.  Paste anything in Nu

**Expected behavior**
I expect the cursor to be after the last character in the pasted text.

**Screenshots**

![Bug-demonstration](https://user-images.githubusercontent.com/32234660/89802344-f12e4800-db20-11ea-8d5b-99fddddc3b66.gif)

**Configuration (please complete the following information):**
 - OS (e.g. Windows): macOS 10.15.6
 - Nu version (you can use the `version` command to find out): 0.17.0
 - Optional features (if any):

I'm not really sure, but I think this bug showed up initially in 0.16.0.

**Comment by fdncred** [comment]
I see the exact same thing. I'm guessing this has something to do with rustyline, the line editor we use, but I'm not sure.

**Comment by mhmdanas** [comment]
Tried to reproduce this on Nu 0.18.1 and it seems like it was fixed. Closing this issue.
