### ISSUE TITLE
Date subcommands

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2324]
**Is your feature request related to a problem? Please describe.**
Looking at the `date` command, I see it doing different types of things. Might be nice to split this up into subcommands.

**Describe the solution you'd like**
Here's one way we could split up the subcommands:

* `date now` - return the current date
* `date to-utc` - convert the given date in the stream to UTC
* `date to-local` - convert the given date to the local timezone
* `date format` - format the date using the given format string
* `date expand` - expand the given date value into the structured date value (what you get when you do `date` today)

**Describe alternatives you've considered**
We can leave it as flags. This is fine for now, but I think you'll ultimately want more control/flexibility over dates and not just assume the user wants the current date.

**Comment by Zooce** [comment]
Looks like this can be closed, right?

**Comment by thegedge** [comment]
@Zooce at least from the original list, looks like we're still missing `date local` (I think `date expand` is no longer relevant).

**Comment by Zooce** [comment]
Hi @thegedge, thanks for the reply!

I was looking into the code and it seems that `date now` actually _kind of_ covers the `date local` case -- it gives the current date in the local timezone, but doesn't do any conversion.

I'm now wondering if the idea is still there to do conversions at all, since currently none of the `date` commands actually take any input for the purpose of converting the timezone.

I think the closest command so far is `str to-datetime` -- I don't know how to get it to return a table (I'm not sure if it can or not).

If the idea is to add some conversion functionality to the `date` subcommands, what would it look like from the user's perspective?

_Maybe something like these?_
* `$ echo '2020-08-04T16:39:18+00:00' | date to-local | date format '%Y.%m.%d_%H %M %S,%z'`
* `$ date local | date to-utc` _(this one is kind of pointless, but it gets an idea across)_

Also, is there an existing command (or set of piped commands) that already achieve this?

**Comment by Zooce** [comment]
I think you're on to something there. Your solution certainly seems more Nushell-y, and I think it's the right direction to go (although I'm not the expert here, by any means).

I'm still unfamiliar with how the basic data structures in Nushell work (like `OutputSteam`, `Value`, etc.), I'm in the learning phase here, so I have a couple of questions (even if someone else decides to make this update before I do -- totally cool):
* If the `date` commands return a `DateTime` (from the `chrono` crate, right?) what should be the Nushell type that is actually returned?
  * Or maybe a better question, what is the proper way to convert a `DateTime` struct to a non-table `OutputStream`?
* I think the answer to this is "yes", but would the output of, say, `date now` be a string (like `str to-dateimte` command)?

_(Sorry for the super n00b questions -- actually I'll probably have a couple more questions too...I just don't yet know what those questions are.)_

**Comment by thegedge** [comment]
> If the date commands return a `DateTime` (from the `chrono` crate, right?) what should be the Nushell type that is actually returned?

Yep, looks like we're using `chrono::DateTime`.

All commands return a stream of `Value`s, so you'd be returning that. Specifically, you'll end up with something like `UntaggedValue::date(chrono_date_time)`, and that'll either be `.into_untagged_value()` if you don't have a `Tag`, or `.into_value(tag)` if you do have one (we often do, it's the thing that allows us to show in errors where a value came from).

> I think the answer to this is "yes", but would the output of, say, `date now` be a string (like `str to-dateimte` command)?

Yep, I think that's a good place to start. Perhaps we could present it in a way so you know it's a structured datetime, not a string. I don't have any ideas here, but we can always tweak this, even make it configurable 🙂

> Sorry for the super n00b questions

Never be sorry for questions! The one thing I've learned in my career is that being open to asking questions is a valuable part of one's skillset. Not sure if you're on our [Discord](https://discord.com/invite/NtAbbGn), but our `#developing` channel is another great place to get some help.

**Comment by mvolkmann** [comment]
In version 0.28.0 `date to-table` produces no output. Is that a bug?

**Comment by jonathandturner** [comment]
@mvolkmann - `date to-table` needs a date as input:

```
date now | date to-table
───┬──────┬───────┬─────┬──────┬────────┬────────┬─────
 # │ year │ month │ day │ hour │ minute │ second │ ... 
───┼──────┼───────┼─────┼──────┼────────┼────────┼─────
 0 │ 2021 │     3 │  12 │    6 │     53 │     26 │ ... 
───┴──────┴───────┴─────┴──────┴────────┴────────┴─────
```

**Comment by mvolkmann** [comment]
I'm curious why just entering `date now` doesn't render that by default the way that `ls` and `ps` do.
IIUC correctly, `| auto view` is automatically added to some commands, but I don't know yet which ones.
Would it be a bad idea if `date now` was one of those?

**Comment by jonathandturner** [comment]
@mvolkmann - seems like a bug. mind filing an issue?
