### ISSUE TITLE
Redox Support

### ISSUE THREAD

**Issue by AdminXVII** [nushell/nushell#2327]
This is a summary on my work compiling nushell for Redox. I'd like to eventuallly have the stable feature compile on Redox. This is more of a report than a feature request per se.

Right now, compilation is blocked by those crates:
 - nix, which must be updated to 0.18.0 across the dep tree. Unlocks features uuid-support,term-support,ctrlc-support,director
ies-support,inc,match,trash-support,start,bson,trace,term-support
 - signal-hook, a patch must be created upstream, then it needs to propagate across the dep tree. Blocks features textview,binaryview
 - socket2, a redox local patch must be upstreamed, then propagated. Blocks features sys,ps,which-support,post,fetch
 - openssl, must setup cross-compilation. Blocks feature git-support
 - ptree, which seems dead since 2 years. Needs to merge https://gitlab.com/Noughmad/ptree/-/merge_requests/5. Blocks feature ptree-support,tree
 - sqlite, must setup cross-compilation. Blocks feature sqlite

Features that are not yet implemented on Redox
 - clipboard, blocks feature clipboard-cli

**Comment by jonathandturner** [comment]
@AdminXVII - If you manage to get it building with a subset of features, feel free to send a PR to create a feature group specifically for redox that only includes things compatible on that OS.

**Comment by AdminXVII** [comment]
Great I'll do so when nix is up to date everywhere.
