### ISSUE TITLE
do -i { ... } shows the error message

### ISSUE THREAD

**Issue by ionutvmi** [nushell/nushell#2338]
**Describe the bug**
I just upgraded to 0.18.1 and I noticed that do -i shows the error message.
I am using do -i to get the current git branch in the prompt similar to the examples from the following article: https://www.nushell.sh/blog/2020/06/30/nushell_0_16_0.html

**To Reproduce**
1. Open nushell
2. run `do -i {git status}` in a folder which is not part of a git repo

**Expected behavior**
`do -i { ... }` should not show the error message

**Configuration (please complete the following information):**
 - OS: Win 10
 - Nu version 0.18.1

**Comment by fdncred** [comment]
Strange behavior. Am I trying to reproduce it right?
![image](https://user-images.githubusercontent.com/343840/90015787-b20e0d00-dc6e-11ea-9cde-e6956f634b0f.png)
I'm on Win 10.0.19041.388 with Nu 0.18.1 just built from main.

**Comment by ionutvmi** [comment]
Sorry, I got confused because the prompt was still active.
I disabled it and here are the steps:

![image](https://user-images.githubusercontent.com/3531898/90019083-9a5a7700-dcb6-11ea-9abd-6dd0fc9bbaa3.png)

It looks like the git command alone doesn't show an error, but I try to pipe it then it shows up.

```
do -i { git rev-parse --abbrev-ref HEAD | trim }
```

**Comment by fdncred** [comment]
I ran into this exact problem the other day and @jonathandturner's suggestion was to move `trim` to the outside of the braces like this: `do -i {git rev-parse --abbrev-ref HEAD } | trim`. Does that work for you?

**Comment by ionutvmi** [comment]
Yes, it did.

Thank you very much for the tip !
