### ISSUE TITLE
Nushell doesn't respect chosen terminal colors

### ISSUE THREAD

**Issue by davidarmstronglewis** [nushell/nushell#2342]
Specifically, when I run something like `ls`, I expect nushell to use my chosen color for bold fonts for the headers. Instead it's green, which doesn't need configuration. There's a configuration option to use bold colors for table headers, which still comes in as green.

I know this project is striving to be as cross-platform as possible, so is it just not feasibly to use a terminal emulator's chosen colors? If so, is there a way to override them and provide my own?

Here's a demonstration of what I mean. I have a nice dark red chosen as my bold font, but nushell loves green. I mean, green's great, but I think I prefer to make my own choices :laughing:

![Screenshot from 2020-08-12 12-26-56](https://user-images.githubusercontent.com/6754950/90059032-61f77080-dc97-11ea-9b72-ed8c3020481b.png)

And thank you for this awesome project!

**Comment by fdncred** [comment]
Right. Nushell is not theme-able or theme-aware yet. We'd love it to be, but it's not yet. I've tried a couple of theme in Windows Terminal. This was done with windows terminal color schemes.
![image](https://user-images.githubusercontent.com/343840/90063916-aa228d00-dcaf-11ea-828f-35d9b69eb7cb.png)
![image](https://user-images.githubusercontent.com/343840/90063941-b27ac800-dcaf-11ea-96cc-1b3ac4d5361b.png)

**Comment by davidarmstronglewis** [comment]
Seems this is something you're all aware of - should I keep this issue open or is this something already on the roadmap?

**Comment by fdncred** [comment]
Yes, we know about it. Yes, we can close this. Yes, it's on the roadmap. :) Sorry we don't have it yet.

**Comment by davidarmstronglewis** [comment]
All good, it's just an itch I was personally having and felt strongly enough to come here. Thanks for communicating about it :heart:
