### ISSUE TITLE
Check for empty argument in if statement

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#2343]
**Is your feature request related to a problem? Please describe.**
Currently, aliases do accept less than the defined number of arguments - however, there is no way to actually check if they've been left empty when called. This leads to things like equality checks failing (comparing `string` with `nothing`).

**Describe the solution you'd like**
It would be nice to be able to check if an argument is empty (i.e. `nothing`) first.

**Additional context**
I've been trying to add support for [zoxide](https://github.com/ajeetdsouza/zoxide), which is a replacement for the `cd` command. When no arguments are passed, the `z` alias should `cd ~`, else if there's one argument `-`, it should `cd -`, otherwise it should `cd $(zoxide query $a $b $c $d)`.

**Comment by fdncred** [comment]
I have to say that I really like `zoxide`. I'd love to just make it the `cd` we use with zero configuration and have it `just work` . It doesn't appear that it's available as a crate that we can just add but more of a cli app, if I read everything correctly. 

This isn't the place for feature request for zoxide, but I'd also like to see a `--list` option to show what's in the db and I'd love it to just read our `history` file to `add` items to the `zoxide` db.

I wonder if an `alias` like this would help. `alias is_nothing [a] { if $(echo $a | str length) == 0 {echo $true}
{echo $false}}`. You can have aliases call aliases.

**Comment by ajeetdsouza** [comment]
Hey @fdncred,

- Thanks! Currently, zoxide is structured as more of a CLI app than a crate. However, if the maintainers of Nushell want to integrate it natively, I'd be very happy to refactor and help with the effort!
- The latest release actually does support `zoxide query --list`! I've thought of parsing history before, but I don't think it would be possible - we have to handle multiple shell instances writing to the same history file with `cd relative/path`, and we'd have no way of keeping track of each instance's `$PWD`. I'm always open to suggestions and feature requests, though - just create an issue!
- I tried the alias you mentioned, but it seems to always return `false`. I might be doing something wrong, could you provide me an example of how you would use it?

**Comment by fdncred** [comment]
I'll have to check out the newest release. I built from the repo yesterday 0.4.3 but maybe it's changed since then.

I'll talk to the team about if we want to integrate. We have  meeting tomorrow.

I'm not sure what the problem is with the alias, it seems to work as in the screenshot. 
![image](https://user-images.githubusercontent.com/343840/90143814-aa6c6800-dd43-11ea-9f99-9f88215b1b82.png)

**Comment by ajeetdsouza** [comment]
@fdncred I was hoping for this to work:

```
/tmp> alias is_nothing [a] { if $(echo $a | str length) == 0 {echo $true} {echo $false}}
/tmp> alias y [a] { is_nothing a }
/tmp> y
false
```

**Comment by fdncred** [comment]
Your `y` alias is wrong. You need a dollar sign on the last a. like this `alias y [a] { is_nothing $a}`. Also, I don't think you can just say `y`. You need to say `y some` = false or `y ""` = true.

**Comment by ajeetdsouza** [comment]
Ah, my bad. In that case, I don't think `is_nothing` would work for me - what I wanted was a mechanism to create an alias `z` that does the following:
- `z` does a `cd ~`.
- `z -` does a `cd -`.
- `z foo bar` does a `cd $(zoxide query -- foo bar)`.

**Comment by andrasio** [comment]
@ajeetdsouza might not solve it all together, try `empty?` command.

**Comment by andrasio** [comment]
@ajeetdsouza : There should be simpler ways to do it.

```
> alias super-cd [args] { if $args.0 == "" { cd ~  } { if $args.0 == '-' { cd -  } { cd $(query "--" $args.0 $args.1)  } } }
> alias x [arg_1 arg_2] { echo [$arg_1 $(if $(= $arg_2 | empty?) == $true { = "empty" } { = $arg_2 })] | format "{$it}" | where $it != "empty" | wrap args | super-cd $it.args }

> super-cd
> super-cd "-"
> super-cd foo bar
```

**Comment by fdncred** [comment]
@andrasio Nice! Just got it working in windows.
Entries from my config. Had to change double quotes to single quotes.
```
    "alias cd-or-oxide-it [args] { if $args.0 == '' { cd ~  } { if $args.0 == '-' { cd - } { cd $(zoxide query -- $args.0 $args.1)  } } }",
    "alias super-cd [arg_1 arg_2] { echo [$arg_1 $(if $(= $arg_2 | empty?) == $true { = 'empty' } { = $arg_2 })] | format '{$it}' | where $it != 'empty' | wrap args | cd-or-oxide-it $it.args }"
```

**Comment by ajeetdsouza** [comment]
Also, @fdncred, did you have a chance to talk to the Nushell team about native zoxide integration?

**Comment by fdncred** [comment]
@ajeetdsouza We did talk about it a little bit a couple Fridays ago but we made no decision.

**Comment by ajeetdsouza** [comment]
Fair enough. Do let me know if they decide on moving forward with it!
