### ISSUE TITLE
Can't cd ~\Downloads even though it's auto completed but can cd ~/downloads

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2344]
**Describe the bug**
In Windows, I can't `cd ~\Downloads` even though `~\Downloads` is autocompleted by rustyline. However, I can `cd ~/downloads`

**To Reproduce**
1. cd ~\Down<TAB> then hit enter
2. watch it fail
3. cd ~/downloads then hit enter
4. watch it work

**Expected behavior**
Both scenarios should work

**Screenshots**
```
C:\Users\user\source\repos\forks\nushell(main)
08/13/2020 10:12:00.283 AM> cd ~\Downloads\
error: Cannot change to directory
  ┌─ shell:1:4
  │
1 │ cd ~\Downloads\
  │    ^^^^^^^^^^^^ directory not found

C:\Users\user\source\repos\forks\nushell(main)
08/13/2020 10:12:06.764 AM> cd ~/downloads
C:\Users\user\Downloads()
```

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Windows Version 10.0.19041.450
 - Nu version (you can use the `version` command to find out): 0.18.1
 - Optional features (if any): ``
`───┬───────────
 0 │ default
 1 │ clipboard
 2 │ trash
 3 │ starship
───┴───────────``` <-- This should collect in one statement btw, instead of a table.

**Comment by thegedge** [comment]
Should hopefully be fixed once I get around to implementing our own path completer. We're hacking around rustyline's completer in several ways already, so I'd rather not hack on more 🙂
