### ISSUE TITLE
Question: Do the "typed" streams rely on the standard file descriptors (stdin, stdout, stderr), or new ones?

### ISSUE THREAD

**Issue by castarco** [nushell/nushell#2351]
**Is your feature request related to a problem? Please describe.**
From what I read in the documentation, is not entirely clear to me if nushell tries to extract "meaning" from certain old plain text outputs, or if it's in fact able to deal with explicitly typed streams (lets call them `typedin`, `typedout` and `typederr`, with correspondent file descriptor numbers 3, 4 and 5; as an example).

I ask this because, even if it's possible to interpret old untyped outputs, and even if nushell has no aim to keep backwards compatibility with POSIX shell, somehow it feels natural to me to introduce new explicitly strongly typed streams, and I'm not sure if that's something already done or maybe planned.

**Comment by thegedge** [comment]
All pipelines use internal streams to pass along the structured data.

There are two special cases.

The first would be external/legacy commands. When such a command is encountered in the pipeline, we:
1. take string data from the structured stream and write it the stdin of the command we spawn, and
2. read its stdout and feed it back into the internal stream as string data.

The second case are nu plugins. These are build around a JSON-RPC protocol we've built to send and receive structured data.

> I ask this because, even if it's possible to interpret old untyped outputs, and even if nushell has no aim to keep backwards compatibility with POSIX shell, somehow it feels natural to me to introduce new explicitly strongly typed streams

I think, down the line, it would be really interesting to consider a standard for such a thing. Arguably, the aforementioned protocol could be that.

> and I'm not sure if that's something already done or maybe planned.

At the moment, we have no plans to pursue this, since things are moving and changing pretty quickly. Definitely something to keep in mind after 1.0, once things have stabilized 🙂

**Comment by castarco** [comment]
Thx for the explanation 👍🏻

**Comment by castarco** [comment]
Regarding the typed streams, I had this crazy idea of defining "type signatures" for cli applications, and storing them in some "standardized" directory (let's say `/etc/cli_stream_types/` just as an example), so it would be possible to statically validate some shell scripts using those available type definitions (similar to how Typescript interfaces with Javascript code).

**Comment by thegedge** [comment]
Well, @castarco, this isn't crazy at all. This is actually where nushell is headed. A nushell command is built around a [signature](https://github.com/thegedge/nushell/blob/79ce2658b3a145cf15a038f073c7c39ad2c3a666/crates/nu-protocol/src/signature.rs#L97-L119), which can define the:

- flags the command receives, and the type of values (if it's a flag that receives a value),
- positional arguments and their types,
- inputs into the command, and
- outputs from the command.

Two things to note:

First, we don't really do much with the input/output part of a signature yet (most commands don't even specify it). We were hoping to start taking advantage of that sometime soon, so we could do a static validation of pipeline and verify the types "agree". At the moment, type errors are generated during the execution of a pipeline.

Second, input/output types are hard to specify for some commands. For example, the `get` command. If we have the following:

```
ls | get name
```

The output of `get` is a list of filenames. If I have

```
ls | get size
```

I now have a list of file sizes. You can see that the output type varies based on the input type. I don't think our definition of `Signature` is powerful enough to allow for specifying these "dynamic" output types.

Some issues you can follow:
- https://github.com/nushell/nushell/issues/195 – typecheck the stream
- https://github.com/nushell/nushell/issues/2368 – how to define a `Signature` for an external command?

**Comment by castarco** [comment]
I guess we need to figure out how to define some sort of "dependent types", this can be slightly more complex than in FP languages due to the fact that many cli applications follow different standards to parse options and arguments, but maybe this could be achieved by defining some sort of high level types that can be dynamically inferred given the "shape/structure" of the command (something like: if the command fulfills the properties `A`, `B`, and `C`, then is of type `T1`; and if it fulfills the properties `X` & `Z` then it is of type `T2`).

To be more precise, and to avoid problems, the mechanism should have many restrictions. I'm thinking on some sort of exhaustive (and sequential) pattern matching mechanism (possibly over string arrays), where the last possible match always gives us a "type" denoting a malformed command.

I could work a little bit on the structure + syntax + inference algorithm for such definitions, I'm not sure if it's worth yet for `nushell`, but I need more time to dive deep into the code, and in the meantime before being able to contribute code maybe this is more approachable to me.

**Comment by thegedge** [comment]
Sounds like you have the right ideas.

I think it's a big enough project that it's worth thinking about it a bit first before diving in, and then writing your thoughts down in an RFC (https://github.com/nushell/rfcs). We're starting to use the RFC process for these kinds of large, complex features 🙂
