### ISSUE TITLE
`sort-by` should fail gracefully if mismatched types are compared

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2357]
**Describe the bug**
From discord just now:

```
open Data.ods | get Sheet1.Column3 | sort-by
thread 'main' panicked at 'Unimplemented BUG: What about primitives that don't have an order defined?: ("decimal", "string")', [my_truncated_path]/nu-cli-0.18.1/src/commands/sort_by.rs:145:21
```

`sort-by` should not crash Nu if mismatched types are used

**To Reproduce**
1. `echo [1 "foo"] | sort-by`
2. Look at sadness at your crashed shell

**Expected behavior**
We should detect this error and tell the user that the data could not be sorted

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Latest Pop! OS
 - Nu version (you can use the `version` command to find out): Latest main

**Comment by jonathandturner** [comment]
We should be outputting a ShellError instead of using `.expect` here: https://github.com/nushell/nushell/blob/6eb2c94209af69df0cf2e39b7f0624ea2300d7bb/crates/nu-cli/src/commands/sort_by.rs#L145

**Comment by ngraham20** [comment]
Is this issue still open for contributions? I see that a PR was submitted a bit ago. What still needs doing and may I give a crack at it?

**Comment by JosephTLyons** [comment]
It does seem that https://github.com/nushell/nushell/pull/2360 was the solution to the issue here, so I will close this out.
