### ISSUE TITLE
BASH compatibility with `-l` (login shell)

### ISSUE THREAD

**Issue by Havvy** [nushell/nushell#2362]
Filing this one on behalf of @jonathandturner , so I'll let his words speak:

> jturner: I noticed the other day that some systems want to be able to call the login shell with -l, and if they can't it's a problem. Nu currently using -l for logging, so we conflict with that and fail not-so-gracefully
jturner: might as well just support the -l for login shells

**Comment by ammkrn** [comment]
This issue currently prevents nu from being used with vscode's integrated terminal with vscode's default settings (at least for osx). It also prevents nu from being opened on some terminal emulators, for example wezterm.

For vscode, users can get around it for now by putting this in your JSON settings (on osx):
`"terminal.integrated.shellArgs.osx": []`
