### ISSUE TITLE
Idea: StructOpt-like argument parser for Nu scripts

### ISSUE THREAD

**Issue by KSXGitHub** [nushell/nushell#2368]
While working with BASH, I wished I could use something like [StructOpt](https://github.com/TeXitoi/structopt) so that I wouldn't have to write parsing algorithm and `--help` message on my own.

Regarding Nu, I think a parser like StructOpt would be a killer feature on its own.

I imagine it would work like this:
* User defines a schema in before all other commands but not before shebang.
* Built-in `help` command can read the schema without executing the script.
* When user pass the arguments to the script, they will be parsed against the schema and produce a `$nu_args` table.

**Comment by thegedge** [comment]
We haven't sketched it out, but we're hoping to have a concise way to express a `Signature` in scripts. For example, internally it looks like this:

https://github.com/nushell/nushell/blob/738541f7275fc82ab712343097a9d640e58e5740/crates/nu-cli/src/commands/du.rs#L39-L70
