### ISSUE TITLE
Adding column headings when loading in data

### ISSUE THREAD

**Issue by wdenton** [nushell/nushell#2371]
There seems to be no easy way to add column headings, for example when loading in data from a CSV file.  (This is the opposite of `headers`, which takes the headings from the first row.)

This works:

    open --raw file.csv | lines | split column "," "heading1" "heading2"

If there is an easier way, I didn't see it in the docs.  If there isn't, perhaps this could be added, so something like `open file.csv | <something> "heading1" "heading2"` would work?

**Comment by thegedge** [comment]
`split column <delim> [column names...]` is exactly the thing you're looking for 🙂

Another option, which may be a little clearer by technically more to write, would be:

```
open --raw file.csv | lines | split column "," | rename heading1 heading2
```

In terms of seeking something "easier", do you mean you'd like to be able to not have to write `lines` also? If so, this is exactly what an alias should solve:

```
alias mycsv [file column_names...] { open --raw file | lines | split column "," $column_names... }
```

Then you could just write

```
mycsv file.csv heading2 heading2
```

Note, the `...` syntax isn't a thing that exists today, but the idea is that it would allow an arbitrary number of arguments.
