### ISSUE TITLE
Parser expects Tagged, eventhough Unit has to be parsed

### ISSUE THREAD

**Issue by LhKipp** [nushell/nushell#2373]
Current workaround at the end of this post
**Describe the bug**
Parsing stage fails with error message: "Expected Tagged, found duration", when parsing SyntaxShape::Unit into Tagged<u64>.

/home/leonhard/programs/nushell(main)> sleep 1sec
error: Type Error
  ┌─ shell:1:7
  │
1 │ sleep 1sec
  │       ^^^^ Expected Tagged, found duration

**To Reproduce**
Patch with problematic code: https://gist.github.com/LhKipp/10f8cf9b0f29107e079461655af17fa8
1. git apply sleep_expects_tagged.patch
2. compile && run
3. enter command: sleep 1sec

**Expected behavior**
Sleep for 1sec.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Artix Linux
 - Nu version (you can use the `version` command to find out): nushell 0.18.2
 - Optional features (if any):

According to @jonathandturner  the current workaround is:
Change the Tagged<u64> to Value and SyntaxShape::Unit to SyntaxShape::Any.

**Comment by LhKipp** [comment]
Okay, I resolved this Issue partially. The above mentioned problem comes from not handling a Primitive::Duration in a match statement.

However, the sleep command doesn't work yet.
```shell
/home/leonhard/programs/nushell(main)> sleep 1sec
error: Type Error
  ┌─ shell:1:1
  │
1 │ sleep 1sec
  │ ^^^^^ Expected Vec, found nothing
```
This problem arises from the additional_dur (type: Vec<Tagged<u64>>) of struct SleepArgs beeing processed as such:
```shell
...
 TRACE nu_cli::deserializer > Processing additional_dur
 TRACE nu_cli::deserializer > pushing None
 TRACE nu_cli::deserializer > popping value :: Some(DeserializerItem { key_struct_field: Some(("additional_dur", "additional_dur")), val: Value { value: Primitive(Nothing), tag: Tag { anchor: None, span: Span { start: 0, end: 5 } } } })
 TRACE nu_cli::deserializer > <Vec> Extracting Value { value: Primitive(Nothing), tag: Tag { anchor: None, span: Span { start: 0, end: 5 } } } for vec
```
The function: deserialize_seq in deserializer.rs doesn't handle such a case in the match statement, as apparently rest arguments are normally (?) supposed to hold a value of type Table.

```shell
/home/leonhard/programs/nushell(main)> kill 3029384320
...
 TRACE nu_cli::deserializer > Processing rest
 TRACE nu_cli::deserializer > pushing Some(Value { value: Table([]), tag: Tag { anchor: None, span: Span { start: 0, end: 0 } } })
 TRACE nu_cli::deserializer > popping value :: Some(DeserializerItem { key_struct_field: Some(("rest", "rest")), val: Value { value: Table([]), tag: Tag { anchor: None, span: Span { start: 0, end: 0 } } } })
 TRACE nu_cli::deserializer > <Vec> Extracting Value { value: Table([]), tag: Tag { anchor: None, span: Span { start: 0, end: 0 } } } for vec
```

I am not sure where the bug is. Is the additional_dur wrongly handled or is a match arm missing?

You can check out at https://github.com/LhKipp/nushell/tree/ParserExpectsVec for the commits etc.

**Comment by jonathandturner** [comment]
@LhKipp can you share the code for the SleepArgs and how you process the args? It seems something isn't quite lining up between the types, but it's a bit difficult to tell. From the logs it seems like it's related to the `rest` arg

**Comment by jonathandturner** [comment]
Oops, missed the link. Looking now :+1:

**Comment by jonathandturner** [comment]
@LhKipp your rest arg in the struct I believe needs to be called `rest` to line up with the rest argument. Once you rename it, it should start to work

**Comment by LhKipp** [comment]
Thanks. That solves the problem.
