### ISSUE TITLE
parse command - ignore whitespace - or some easy way to split words into columns

### ISSUE THREAD

**Issue by rrichardson** [nushell/nushell#2375]
I really like awk's "word" selection syntax: 

```
> echo "this is      a          test" | awk '{ print $1 " " $4 }'
this test
```

It parses out words without me needing to worry about the whitespace between them

Most modern CLI tools are nice enough to pad and align all of the output, but when I parse them, I need a way to ignore  the additional whitespace. 

The parse command is powerful, but right now it works too much like `scanf`  It treats the input tokens in the format string as absolutely positioned by whitespace.  I think that the default behavior should be more like awk's $

Parse's current behavior: 

```
❯ echo "this is      a          test" | parse "{a} {b} {c} {d}"
───┬─────────────────────
 a │ this
 b │ is
 c │
 d │     a          test
───┴─────────────────────
```

What I'd like to see: 

```
❯ echo "this is      a          test" | parse "{a} {b} {c} {d}"
 ───┬──┬──┬──
         a  |     b    |   c    |    d
0 |    this     is      a        test
────────────
```

I've tried `split columns  ...` which is what I'd expect to work.. splitting a string into columns.. at least that's what it says on the label I think. 

```
❯ echo "this is      a          test" | split column " "
──────────┬──────
 Column1  │ this
 Column2  │ is
 Column3  │
 Column4  │
 Column5  │
 Column6  │
 Column7  │
 Column8  │ a
 Column9  │
 Column10 │
 Column11 │
 Column12 │
 Column13 │
 Column14 │
 Column15 │
 Column16 │
 Column17 │
 Column18 │ test
──────────┴──────
```

Split row almost works the way I want.. but it puts the values into rows instead of columns.. 

```
❯ echo "this is      a          test" | split row " "
───┬──────
 0 │ this
 1 │ is
 2 │ a
 3 │ test
───┴──────
````

Actually.. I just found the `-c` argument for split column and it almost gets me where I want to be: 

```
❯ echo "this is      a          test" | split column -c " "
─────────┬──────
 Column1 │ this
 Column2 │ is
 Column3 │ a
 Column4 │ test
─────────┴──────
``` 

Is there any way I can index the rows by number instead of having to type out `Column1` to fetch the value I care about?

**Comment by rrichardson** [comment]
also.. it was pointed out that `from ssv` should work as well.... with some tweaks.. 

```
❯ echo "this is      a          test" | from ssv --headerless -m 1
─────────┬──────
 Column1 │ this
 Column2 │ is
 Column3 │ a
 Column4 │ test
─────────┴──────
```

**Comment by rrichardson** [comment]
Side proposal: 

Can we just change the name of the auto-generated columns to just their ordinal?  1, 2 3.. 
or if numbers won't work.. maybe just `C1`  

The Prefix of Column seems a bit redundant.. since.. well.. it's a column in a table, so we know it's a column..

**Comment by thegedge** [comment]
Okay, there's a few things to dissect in here.

> Is there any way I can index the rows by number instead of having to type out `Column1` to fetch the value I care about?

I think `split row` is the way to go if you just want to pull out a single thing:

```
> echo "this is      a          test" | split row " " | nth 2
a
```

> Can we just change the name of the auto-generated columns to just their ordinal? 1, 2 3..
or if numbers won't work.. maybe just C1

```
> echo [this is a test]
───┬──────
 0 │ this
 1 │ is
 2 │ a
 3 │ test
───┴──────
```

That's kind of like a "list", and those numbers aren't columns, but row indices. These are two different things, so there's room for confusion by just going for straight numbers.

Given that, if we were going to make any changes, I'd lean towards `C[n]` being the default. I think it could make sense to also consider this a "column name prefix" configuration, which you could then set to an empty string and get 1, 2, 3... 🙂 

@andrasio from a data processing perspective, what do you think is best here?

> I really like awk's "word" selection syntax:

```
echo "this is      a          test" | awk '{ print $1 " " $4 }'
echo "this is      a          test" | split column -c " " | rename 1 2 3 4 | format "{1} {4}"
echo "this is      a          test" | ws | format "{1} {4}"
```

That last one is assuming you made an alias for the split column, and that we had the configuration option I mentioned above. The end result is even less typing! What do you think?

**Comment by fdncred** [comment]
I added this in Discord. Is it what you're looking for?
```
echo "this is      a          test" | split column " " --collapse-empty
───┬─────────┬─────────┬─────────┬─────────
 # │ Column1 │ Column2 │ Column3 │ Column4
───┼─────────┼─────────┼─────────┼─────────
 0 │ this    │ is      │ a       │ test
───┴─────────┴─────────┴─────────┴─────────
```

**Comment by rrichardson** [comment]
@thegedge - I definitely think option 3 looks good.  

I think the magic of the `ws` command would be that it could also rename an arbitrary number of columns into their ordinals. 
I am a bit skeptical of a configuration change that controls naming, because it could lead to a serious usability issue where people see examples and try to run them, but they don't work because the names are wrong.  IMO, config settings should effect superficial output and styling , but not programming functionality. 

@fdncred  - pointed out that a config change of `pivot_mode` to "auto"  also produced results that are more intuitive for a beginner.  

Looking at all of the options and approaches,  I think the biggest issue I have right now is the auto-naming.  If we could auto-create more compact column names, as suggested by @thegedge, that'd be the biggest improvement. 

`parse` - IMO, still has more promise for the most succinct and powerful approach to translating strings into variables. Perhaps we could provide a similar flag for parse as we do for split column's `--collapse-empty`   Although,  I think the flag would be more correctly defined as "ignore consecutive whitespace".  

e.g. 
```
echo "this is      a          test" | parse --ignore-whitespace " {foo} {_} {_} {bar}" 
───┬───┬──────
 # │        foo     │     bar │ 
───┼───┼──────
 0 │        this              test
───┴───┴──────
```

**Comment by thegedge** [comment]
> I think the magic of the ws command would be that it could also rename an arbitrary number of columns into their ordinals.

With the ability to "splat" something over a "rest positional", which we'll need, this would be possible. `ws` could look a little like this:

```
with-var cols { split column -c " " } { echo $cols | rename 1..$cols.count }
```

Or if we implement data frames, it may be possible to directly get the count:

```
split column -c " " | rename 1..$frame.count
```

Just throwing ideas out there 🙂
