### ISSUE TITLE
Using '/' in relative paths is not valid

### ISSUE THREAD

**Issue by ImGamez** [nushell/nushell#2376]
When you try to open an executable in the current directory, if I type ./file.exe says that '.' isn't a valid command, needs to be .\file.exe to work.

**To Reproduce**
1. Try to execute a file in the current directory using "./" to indicate the path.

**Expected behavior**
Both "./" and ".\" should be valid options to indicate that the file is in the current directory, since bash/powershell use "./", only cmd can use ".\", coming from those shells I would expect the same behavior.

**Screenshots**
![nu](https://user-images.githubusercontent.com/4965415/90590658-5841a180-e19e-11ea-8d3f-6a7c6d176dc3.png)
nu
(Sorry for spanish on the console, but basically it says that "." isn't recognized as a command.)

![zsh](https://user-images.githubusercontent.com/4965415/90591089-693ee280-e19f-11ea-9a65-12f66b97f9d2.png)
zsh

![cmd](https://user-images.githubusercontent.com/4965415/90591131-82479380-e19f-11ea-85a2-b2207ea2a4c7.png)
cmd

![Powershell using Starship Prompt](https://user-images.githubusercontent.com/4965415/90591267-ecf8cf00-e19f-11ea-9734-10b10fcee913.png)
Powershell using Starship Prompt

**Configuration:**
 - OS: Windows 10 2004
 - Nu version: 0.17.0

**Comment by fdncred** [comment]
If `pwd` was always part of the path, I think it would fix part of this issue. Typically `\` is the path separator in Windows so `.\` should work on Windows and `/` is the separator on Linux & Mac so `./` should work there. I agree that we could probably make this more user friendly.
