### ISSUE TITLE
Duplicate commands - `trim` and `str trim`

### ISSUE THREAD

**Issue by coolshaurya** [nushell/nushell#2382]
**Describe the bug**
To trim strings both the `trim` and `str trim` commands can be used. I believe having 2 commands that do the same thing is not good and can be confusing to new users.

**To Reproduce**
N/A

**Expected behavior**
Only one command for trimming should be there, IMO.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Manjaro Linux
 - Nu version (you can use the `version` command to find out): 0.18.2
 - Optional features (if any): 
![image](https://user-images.githubusercontent.com/32027323/90868580-a29c6b80-e3b4-11ea-8fcb-ba734ae86fff.png)

**Comment by gillespiecd** [comment]
Per chat on discord, `trim` will be deprecated in favor of `str trim`. I can pick this up 👍
