### ISSUE TITLE
Make it more clear commands that consume the stream.

### ISSUE THREAD

**Issue by andrasio** [nushell/nushell#2392]
Brainstorming with @jonathandturner .

At the moment, we've approached commands in a way that only perform the minimum amount of work to start streaming results. There are cases where a command needs to consume the stream (`group-by`, `str collect`, etc). There is no way to distinguish which commands consume all the stream, and which ones don't.

We could address this by naming commands and end them with the `!` character to tell it consumes all the stream. 

The drawback is that there may be many commands that would end up with `!` and the same commands without it (lazy). For that case we could avoid naming them with `!` at the end and simply add a sub command to `do`.

The sub command would be called `<-`, `!` (lovely to save it too for denoting message passing (command actions perhaps?)) or something like it. Therefore, if I want to compose a pipeline that consumes I could do instead:

```
do <- { ls | cmd | cmd }
do ! { ls | cmd | cmd }
```

and Nu would happily process and consume them all.

**Comment by thegedge** [comment]
I think this is part of learning the toolbox, but agree with @fdncred's points, in particular:

1. `!` feels like some kind of negation, and
2. some real examples would be helpful to show pipelines where this "consumes entire stream" can be confusing.

I'm also not for `x <- z` right now, until we figure out variables. That could easily be variable assignment 🙂

**Comment by andrasio** [comment]
@thegedge Think of it like it Ruby when you do `collection.map vs collection.map!`
