### ISSUE TITLE
Completions of the first command can be a path

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2393]
**Is your feature request related to a problem? Please describe.**
It'd be nice if the new completions let you complete a path as the first argument. I remember using this at one point, though I'm not sure if it worked before or not.  Say I'm in directory:

```
Source/nu-data
> ../<TAB>
```

should let me complete into `Source/nushell`

**Describe the solution you'd like**
See above. Not sure if there are alternatives, but they might work too.

cc @thegedge

**Comment by thegedge** [comment]
Yeah, I think I missed this one when attempting to move everything over. This one's a little interesting, because you don't want to show paths all the time, only when you can guarantee that it's a path in the command position (or perhaps when the default completion set is empty?).

**Comment by nu8** [comment]
https://github.com/nushell/nushell/issues/2420
