### ISSUE TITLE
Allow grouping and sliding windows for `each`

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2395]
**Is your feature request related to a problem? Please describe.**
Today's `each` is a handy tool for working on the stream one row at a time, even allowing you to number the rows as you go.

But what happens when you want to work with more than one row at a time?

**Describe the solution you'd like**
I propose we add a new subcommand to `each` called `group` that would let you work with groups of rows:

```
> echo [1 2 3 4 5 6] | each { echo $it }
```
would still output [1 2 3 4 5 6]

With the subcommand:

```
> echo [1 2 3 4 5 6] | each group 3 { echo $it }
```
Would output [1 2 3], [4 5 6]

We should also allow there to be overlap between groups, letting you have a "sliding window" over the data. Something like this:

```
> echo [1 2 3 4 5 6] | each group 3 --overlap 2 { echo $it }
```
Would output [1 2 3], [2 3 4], [3 4 5], [4 5 6]

And:

```
> echo [1 2 3 4 5 6] | each group 3 --overlap 1 { echo $it }
```
Would output [1 2 3], [3 4 5], [5 6]

**Describe alternatives you've considered**
We could make a whole different command, though it feels more natural to me that this is part of `each` since it's responsible for iteration over rows.

For someone with some Rust experience, this shouldn't be too bad. If you have any questions, feel free to ask here or swing by discord.

**Comment by ritobanrc** [comment]
I really like this idea, but `--overlap` feels clunky to me. If I want regular sliding windows (similar to `std::slice::windows` or `itertools::tuple_windows`), I need to manually subtract 1 from the amount I'm grouping by. 

Maybe it makes sense to imitate the Rust standard library here and offer two different subcommands, `chunks` and `windows`. But this has the disadvantage of not being able to slide while skipping (i.e. the last example, `each group 3 -- overlap 1`). Admittedly, the slide-and-skip behavior seems oddly specific (I can't really think of any use-cases for it), so maybe something like `each windows 3 --skip 1` would be reasonable.

**Comment by jonathandturner** [comment]
Agreed. Having two different subcommands also makes sense. I agree that having both flags feels a bit clunky. Taking @ritobanrc 's idea, how about this:

```
each group 3
```
Would output every 3 rows as a group

```
each window 3
```

By default would output 3 rows, slide over 1, output 3 and continue until finished.  We could add a `--skip` or maybe `--stride` to say how much to move the window each time.  I think maybe `group` is a little clearer than `chunk` though I could be wrong there.

**Comment by ritobanrc** [comment]
Yeah, I agree. `group` is clearer than `chunk`, and I think `--stride` makes sense for windows. I'd like to try my hand at implemented this, if you don't mind.

**Comment by jonathandturner** [comment]
@ritobanrc - please do! I'll assign it to you
