### ISSUE TITLE
Email test file looks like phishing

### ISSUE THREAD

**Issue by micahsnyder** [nushell/nushell#2397]
Minor complaint here. I was building nushell (`rust install nu`) and noticed that the `.eml` test sample is picked up as phishing/fraud.  I'm wondering if perhaps a different sample should be used.

https://www.virustotal.com/gui/file/3d8da836653a257dc1891fde0ce0fd007cda1b1cfdd9017477bdcf8151bea859/detection

The suspicious line, from ClamAV's perspective at least, is this link which claims to be eBay, but actually goes to some IP address:
https://github.com/nushell/nushell/blob/de5cd4ec2360a5be2e34bf7dc7d00a4e2017fde3/tests/fixtures/formats/sample.eml#L52

Regards,
Micah

**Comment by micahsnyder** [comment]
To follow up, I thought maybe removing the suspicious URL would disable the detection, but I guess ClamAV has 14 other signatures which also alert on this specific email. 😁

Replacing the file entirely with a benign email would probably be nice. Again -- super minor complaint.

**Comment by thegedge** [comment]
Thanks for the report! There's definitely no need for us to link out to a potential phishing link. For whoever picks up this issue, I would just either

1. replace that link with something less sketchy, or
2. manually edit the entire body to just be a little bit of plaintext (for a test fixture, we just need the basics).
