### ISSUE TITLE
Crash on `inf` value in CSV

### ISSUE THREAD

**Issue by vlmutolo** [nushell/nushell#2400]
**Describe the bug**
When the value `inf` is found in a CSV file, the BigDecimal `From<f64>` implementation crashes. I haven't finished investigating, but it seems like that crate assumes all `f64`s can be turned into a BigDecimal. Not sure they accounted for `inf` values. I was going to open a PR when I found the issue, but now I''m not sure if this is better solved in the BigDecimal crate or in `nu_protocol::UntaggedValue::decimal`.

**To Reproduce**
1. Create the following CSV file. Name it `bad.csv`.
```csv
1,2
3,inf
```
2. Start nushell (`nu`).
3. Execute `open bad.csv`. This step should panic.

**Expected behavior**
I expected it to display the CSV file. It crashes instead.

**Screenshots**

**Comment by thegedge** [comment]
Probably the same as https://github.com/nushell/nushell/issues/2349

`BigDecimal` can't represent infinity 😞

**Comment by vlmutolo** [comment]
Yeah, I also found that bug. Figured it was different enough (float vs int) to warrant another issue. 

Good news is that there's a [PR in the `bigdecimal`](https://github.com/akubera/bigdecimal-rs/pull/65) crate to at least fix the `nan` and `inf` issue. Bad news is that it doesn't look like there's been any activity since late May.

**Comment by thegedge** [comment]
I also created https://github.com/akubera/bigdecimal-rs/issues/67, but if a PR has been sitting around this long, it may not end up getting addressed. If there's no movement, I think there are some other options:

1. find other crates that can represent infinity,
2. build checks to verify these special conditions, or
3. wrap these types ourselves and add the behaviour we need.
