### ISSUE TITLE
nushell sometimes crashes with InvalidInput under Windows Terminal (1.1.2233.0)

### ISSUE THREAD

**Issue by chenxiaolong** [nushell/nushell#2401]
**Describe the bug**

In Windows Terminal, once the scrollbar appears, some nushell commands cause nushell to crash. The error is always:
```
Error: Io(Os { code: 87, kind: InvalidInput, message: "The parameter is incorrect." })
```

**To Reproduce**

1. Press enter enough times to make the scrollbar in Windows Terminal appear
2. Run `help`

**Expected behavior**

The help output should be printed and then the prompt should show up again.

**Configuration (please complete the following information):**
 - OS: Windows 10 2004 (build 19041.450)
 - Nu version: 0.18.1 
 - Optional features (if any): Compiled with `--features=stable`

**Comment by chenxiaolong** [comment]
It seems the same happens with `sys | get host.sessions` as well. I can file that in a separate bug report if needed.
```
C:\Users\chenxiaolong> sys | get host.sessions
chenxiaolong
Error: Io(Os { code: 87, kind: InvalidInput, message: "The parameter is incorrect." })
```

**Comment by chenxiaolong** [comment]
It seems that this might only be happening when nushell is running under Windows Terminal (1.1.2233.0). Not sure why. When running under conhost.exe or Alacritty, I don't encounter this problem.

**Comment by chenxiaolong** [comment]
This is what is logged when I set `RUST_LOG=trace`:
```
C:\Users\chenxiaolong\git\nushell(main)> echo 1 DEBUG rustyline > Emacs command: AcceptLine
 DEBUG rustyline > Changeset::begin
 DEBUG rustyline > Changeset::end

 DEBUG rustyline > ANSI colors already enabled
 DEBUG rustyline > Changeset::delete(0, "")
 DEBUG rustyline > Changeset::insert_str(0, "")
1 DEBUG rustyline > initial cursor location: 1, 31

Error: Io(Os { code: 87, kind: InvalidInput, message: "The parameter is incorrect." })
```
The error is being printed out here: https://github.com/nushell/nushell/blob/f078aacc25dfb9741f0c747f5e3a040cf58373cf/crates/nu-cli/src/cli.rs#L1186

I tried building with nightly and checking `.backtrace()` on that error object, but there's no backtrace attached.

**Comment by Ryan1729** [comment]
> When running under conhost.exe or Alacritty, I don't encounter this problem.

I have encountered this issue using Alacritty as well.

#### Versions
`nushell 0.19.0`
`alacritty 0.4.3 (c723247)`
`Windows 10.0 build 18363`

**Comment by jonathandturner** [comment]
Should hopefully be fixed by https://github.com/nushell/nushell/pull/2565. If it's not, please reopen so we can investigate further.
