### ISSUE TITLE
Suggest install via 'anaconda' and/or 'spack'

### ISSUE THREAD

**Issue by michaelkarlcoleman** [nushell/nushell#2402]
The current install methods don't look easy in an HPC environment.  (And Rust fills me with minor dread.)

Your shell looks interesting, though.  To widen your availability, perhaps an install via Anaconda or Spack would be useful.  Probably not hard to add.  Cheers!

**Comment by jonathandturner** [comment]
Thanks for the suggestion! Are the pre-built binaries also difficult in HPC? https://github.com/nushell/nushell/releases/tag/0.18.1

(it's been a long while since I did much HPC)

**Comment by michaelkarlcoleman** [comment]
Sort of.  Didn't immediately spot those, and something like 'homebrew' doesn't seem like a good idea.  HPC is indeed a different world.

Our biggest problem is that we're locked to a distro version and cannot feasibly update for a long time.

Looking at the pre-compiled binaries with 'ldd', I get this:
```
./nu: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./nu)
./nu_plugin_binaryview: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./nu_plugin_binaryview)
./nu_plugin_binaryview: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./nu_plugin_binaryview)
./nu_plugin_fetch: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./nu_plugin_fetch)
./nu_plugin_from_bson: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./nu_plugin_from_bson)
./nu_plugin_from_sqlite: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./nu_plugin_from_sqlite)
./nu_plugin_inc: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./nu_plugin_inc)
./nu_plugin_match: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./nu_plugin_match)
./nu_plugin_post: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./nu_plugin_post)
./nu_plugin_ps: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./nu_plugin_ps)
./nu_plugin_start: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./nu_plugin_start)
./nu_plugin_sys: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./nu_plugin_sys)
./nu_plugin_textview: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./nu_plugin_textview)
./nu_plugin_to_bson: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./nu_plugin_to_bson)
./nu_plugin_to_sqlite: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./nu_plugin_to_sqlite)
./nu_plugin_tree: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./nu_plugin_tree)
```

Okay, stop laughing.  Anyway, when you're famous, we'll probably figure it out.  But right now, I'm thinking it's best to go for that "it just works" experience.  I suspect a conda module or even spack would do that.

Mike

**Comment by jonathandturner** [comment]
Sorry for the slow reply - no laughing here. It's mostly just a matter of finding people will the right expertise who are able to do the work.

For those folks who find this issue and would like to help out with one or both of these options, we're happy to collaborate and see if we can get them working and supported.

**Comment by izahn** [comment]
Indeed it would be great to have a `conda` package, I've submitted one at https://github.com/conda-forge/staged-recipes/pull/15302

If there is anyone here willing to serve as a co-maintainer of the conda package please let me know! Responsibilities are minimal (mostly reviewing and merging automated update PRs) but its always nice to have at least two maintainers.

**Comment by izahn** [comment]
The issue with https://github.com/conda-forge/staged-recipes/pull/15302 is lega/political i.e., conda-forge requires licenses for all software included in a package. Since nushell depends on a large number of rust packages we would have to locate licenses for all of them. Alternatively we could re-package all those dependencies for conda-forge, but either way it will be a hassle.

My advice at the moment is to use conda to install `rust` from conda-forge, and then use cargo to install `nushell`. That is:

```
conda create -n cargo -c conda-forge rust pkgconfig openssl zlib
conda activate cargo
cargo install nu
PATH=$HOME/.cargo/bin:$PATH nu
```

This is a little more work than the hoped-for `conda install nushell`, but not much more.

**Comment by jntrnr** [comment]
This is going to end up being out of scope, as all the packaging is done by third-party volunteers and not the Nushell core team.
