### ISSUE TITLE
Disable hints

### ISSUE THREAD

**Issue by nu8** [nushell/nushell#2403]
If I enter this command:

~~~
echo Sunday
~~~

then press the letter `e`, the previous command is filled in. I dont want that.
is it possible to disable?

https://www.nushell.sh/book/en/configuration.html

**Comment by jonathandturner** [comment]
I was looking through the more recent settings, but I don't see it: https://github.com/nushell/nushell/pull/2238

I think what you're seeing is called 'hinting' in the line editor we use. In theory, there would be a way in the configuration to turn that off but looks like we don't yet support configuring it.

That's good feedback.

**Comment by nu8** [comment]
Man, thats too bad. I am currently using PowerShell, and I would like to switch to NuShell as the Unicode support is way better. But that hinting is super annoying and dealbreaker for me. Hopefully in the future it will be configurable.

Thanks for fast comment.

**Comment by thegedge** [comment]
For anyone who's interesting in adding this configuration, we just need to make https://github.com/thegedge/nushell/blob/b72b66873100f65f93dad5201a2713e5be9a7575/crates/nu-cli/src/shell/helper.rs#L13-L18 support an optional hinter.

We could check configuration in `cli.rs`, and if disabled, supply `None` for the hinter.

**Comment by amitdev** [comment]
I was trying out nushell today and faced the same issue. Raised a PR based on the above comment by @thegedge : https://github.com/nushell/nushell/pull/2405. Let me know how it looks.

**Comment by JosephTLyons** [comment]
Closed via https://github.com/nushell/nushell/issues/2403

**Comment by nu8** [comment]
@JosephTLyons the issue closed itself?

**Comment by JosephTLyons** [comment]
> @JosephTLyons the issue closed itself?

Oops, fixed.
