### ISSUE TITLE
How to apply an external transformation/command to a column?

### ISSUE THREAD

**Issue by vkobel** [nushell/nushell#2408]
Hello, first, thanks a lot for this great project!

I'm struggling to apply a simple transformation to a column (e.g. convert a decimal number to hexadecimal, or really running any external tool/command using the value from an existing cell as input), I tried with `update`:

``... | update my_col $(printf %x `{{my_col}}`)``

I also tried a lot of variations of the above but to no avail... 
Am I missing something here? Is it possible to achieve this?

Thanks!

**Comment by thegedge** [comment]
You can use a block whose output will become the replacement value

```
ls | update name { echo `Test: {{name}}` }
```

I couldn't get this to work with `printf` though:

```
> ls | update name { printf "Test: %s" $it.name }
error: Received unexpected type from pipeline (row)
  ┌─ shell:1:20
  │
1 │ ls | update name { printf "Test: %s" $it.name }
  │                    ^^^^^^ expected a string
```

So I think we're not running that block in an expected way 🤔

**Comment by vkobel** [comment]
Indeed, the same error I got.
Static parameters to printf work fine though: `... | update blocknb $(printf %x 15)`, it outputs `f` as expected. Maybe there's an interpolation or order of interpretation issue?

**Comment by thegedge** [comment]
Oh, that's really interesting, and will really help exploring this bug.

I think we're doing something wrong when attempting to run an external command in a block. For example, this works:

```
echo 15 | echo $(echo $it | str from | printf %x $it | echo $it)
```

but this doesn't (although the `f` does get echoed to stdout):

```
echo 15 | echo $(echo $it | str from | printf %x $it)
```

Those are all pretty verbose too, so there are improvements we could make there, but for this issue we'll focus on an external at the end of a pipeline in a `$(...)` invocation.

**Comment by vkobel** [comment]
Maybe this helps:

I was able to convert each cell (but there's only a single column...) like this:
```bash
> echo [14 15 16] | wrap decimal | echo $it.decimal | str from | echo $(printf %x $it)
───┬────
 0 │ e  
 1 │ f  
 2 │ 10 
───┴────
```

But still no luck with `update` to make it work with a table:
```bash
> echo [14 15 16] | wrap decimal | update decimal $(echo $it.decimal | str from | echo $(printf %x $it))
error: Unrecognized type in stream
  ┌─ shell:1:1
  │
1 │ echo [14 15 16] | wrap decimal | update decimal $(echo $it.decimal | str from | echo $(printf %x $it))
  │ ^ original value

```

**Comment by thegedge** [comment]
The @nushell/core-team discussed the invocation syntax not having clear/intuitive semantics in terms of what kind of data it receives. I think the above serves as good examples where it's hard to know what to do.

That being said,

```
echo [14 15 16] | wrap decimal | update decimal $(echo $it.decimal | str from | echo $(printf %x $it))
```

Works on my machine when running from the `main` branch, so perhaps we've unexpectedly fixed it? 🤔 

This also works, and would probably be the better option, since we give `update` a block instead of an invocation:

```
echo [14 15 16] | wrap decimal | update decimal { echo $it.decimal | str from | echo $(printf %x $it) }
```

**Comment by andrasio** [comment]
Indeed. We need to look at externals too.

```
echo [1 2 3] | wrap n | update n $(echo %x $(= $it.n | str from))
```

^ replacing the `echo` in the invocation with `printf` should work but it's not. For above example it works as expected since the arguments: `%x` and `$(= $it.n | str from)` will update the field with them as a table.

**Comment by vkobel** [comment]
I confirm the invocation example fails on **0.18.1**:
```bash
echo [14 15 16] | wrap decimal | update decimal $(echo $it.decimal | str from | echo $(printf %x $it))
```
but on the same version, the block alternative works fine!
```bash
echo [14 15 16] | wrap decimal | update decimal {echo $it.decimal | str from | echo $(printf %x $it)}
```

On **0.18.2** (889b67ca928e1bcf4c4170f2402c150da142f0f7), both invocation and block work as expected!

**Comment by fdncred** [comment]
BTW - `$()` was replaced with `()`
