### ISSUE TITLE
cd driveletter: should just work

### ISSUE THREAD

**Issue by amoldeshpande** [nushell/nushell#2409]
**Describe the bug**
Currently I'm forced to specify a full path when switching between drives.  This is contrary to expected behavior on Windows.
**To Reproduce**
1. cd c:\
2. cd windows
3. cd d:\
4. cd c:  

does nothing (it should at least print some message if it's not going to do anything)

**Expected behavior**
expect 4 to switch back to c:\windows

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Windows 10 2004
 - Nu version (you can use the `version` command to find out): 0.18
 - Optional features (if any):

Reading comments on previous issues, it seems like there is some misinformation that the shell needs to maintain current directory on each drive.  This is absolutely not true. As long as the SetCurrentDirectory Win32 API or the _chdir() Visual C++ CRT function are used, the current directory per drive is maintained by the OS.

Looking forward to playing more with this shell though.

**Comment by thegedge** [comment]
We _should_ be tracking the previous working directory on a drive, so this seems like a bug.

> Reading comments on previous issues, it seems like there is some misinformation that the shell needs to maintain current directory on each drive. This is absolutely not true. As long as the SetCurrentDirectory Win32 API or the _chdir() Visual C++ CRT function are used, the current directory per drive is maintained by the OS.

FYI nushell tracks its own working directory, so we don't get to take advantage of this behaviour. This helps us ensure behaviour is as consistent as possible across platforms 🙂

**Comment by amoldeshpande** [comment]
well, keeping track of the current working directory is one thing, but keeping track of working directories on other drives seems like a uniquely Windows issue. 

 My fear with the shell doing its own tracking is that there will be subtle behavior differences.  However, I will leave that to your judgement.  

thanks!
