### ISSUE TITLE
Spelling correction

### ISSUE THREAD

**Issue by amoldeshpande** [nushell/nushell#2410]
**Is your feature request related to a problem? Please describe.**
One of my favorite features in tcsh (and I believe zsh) is spelling correction.  If you mistype a command, the shell will offer to correct it for you.
This is one of the main reasons I've never switched to another shell for interactive use.

**Describe the solution you'd like**
nush should support spelling correction

**Comment by thegedge** [comment]
How does the feature work? Does it correct it automatically while you type? Does it suggest the correct spelling after you enter the incorrect command? Do you press the TAB key and it'll fix it for you?

I use zsh and don't have this feature, so I'm unfamiliar. Perhaps I don't have it enabled though 🙂

**Comment by amoldeshpande** [comment]
it corrects after you hit return.   from some cursory googling,  this might show you how to enable it in zsh https://linux.die.net/man/1/zshoptions

Even in tcsh it can be a bit aggressive, but I like it nonetheless. zsh seems to have more granular control with a "nocorrect" prefix for commands that it habitually trips up on.

tcsh man page here https://linux.die.net/man/1/tcsh  (if you search for "spelling correction") you will find the relevant part.

**Comment by thegedge** [comment]
Thanks for clarifying, @amoldeshpande. There's a potential for some synergy between such a feature and completions, but a first attempt at this could focus on correcting the entire line.
