### ISSUE TITLE
Crash when parsing file

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2412]
**Describe the bug**
Run this command on this file and watch it crash.
`open dockps.txt | lines | split column " " --collapse-empty | headers`

**Expected behavior**
Not to crash

**Screenshots**
![image](https://user-images.githubusercontent.com/343840/91212453-d8ec2a80-e6d5-11ea-80b9-238ffe7d0425.png)

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Version 10.0.19041.450
 - Nu version (you can use the `version` command to find out): 

|version|commit_hash|nushell_features|
|-|-|-|
|0.18.2|a64cfb6285a84cd5cffc10e36f4a398688abe6e6|default|

 - Optional features (if any):

[dockps.txt](https://github.com/nushell/nushell/files/5125612/dockps.txt)

**Comment by dmeijboom** [comment]
I think I can make a PR to fix this. Seems like this command returns three rows with different headers but the `headers` command tries to get the headers from the first row. So if the second row has more columns than the amount of headers in the first row this fails.

It shouldn't panic but @fdncred I think you're looking for the `docker ps | from tsv` command, right?

**Comment by fdncred** [comment]
`from tsv` would've been another good way to try. The person who asked about this ended up using the json output of docker ps which seemed to work perfectly.

agreed. it shouldn't panic.
