### ISSUE TITLE
Improve error message for coercion errors

### ISSUE THREAD

**Issue by jzaefferer** [nushell/nushell#2414]
**Is your feature request related to a problem? Please describe.**

From the one-year-of-nushell blog post:
```
error: Coercion error
  ┌─ shell:1:3
  │
1 │ = 1min + 1kb
  │   ^^^^   --- filesize(in bytes)
  │   │       
  │   duration
```

**Describe the solution you'd like**
As the note in the blog post says: "note: we’ll be making this error better in the future" - a better error message makes sense!

Maybe something like "math error: trying to add incompatible types, duration and filesize"

I couldn't find an existing issue for this, so hopefully this helps.

**Comment by peterthejohnston** [comment]
I'd like to have a go at this if that's ok. Looking through the repo, it looks like all the uses of `CoerceError` are math-related, so an error message like you said could work.

But if `CoerceError` is meant to be used for a broader category of errors than just math, then maybe the language in the message should be kept more generic? Something like just "coercion error: incompatible types for operation, duration and filesize"?

Or if `CoerceError` implies that nu *tried* to coerce the types to match, but couldn't, it could be something like "unsuccessful type coercion: types duration and filesize are not compatible".

Does anyone have thoughts?

**Comment by jzaefferer** [comment]
I think the `=` clearly makes this in the context of math operations, so it should be fine to mention that in the error message.

If other commands end up with a similar pattern, we can still come up with a better message there.
