### ISSUE TITLE
Inconsistent string/filepath handling

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2415]
**Describe the bug**
@rrichardson discovered this issue and we tried to fix it in discord.

Trying to cd to a path from which.

Doesn't work
1. `which nu | get path | dirname $it | cd $it`
2. `which nu | get path | cd $(dirname $it)`
3. `which nu | get path | cd $(dirname $it | trim)`

Does work
1. `which nu | get path | dirname $it | trim | cd $it`

We were originally theorizing the `cd` needed a `filepath` however, `trim` is probably returning a `string` so that kind of negates that theory. Once we figured out that one of my aliases work, we decided to try other things and arrived at one that works (above). I was also thinking that since externals were involved that maybe the issue, but it doesn't appear to be.

The alias I was referencing.
`alias z [a b c d] {if $(echo $a | empty?) == $true { cd ~ } {echo $a | if $it == '-' { cd - } {cd $(zoxide query -- $a $b $c $d | trim)}}}`

**Expected behavior**
I think any of the four cases above should work. They seem reasonable approaches.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Windows 10 2004
 - Nu version (you can use the `version` command to find out): 

|version|commit_hash|nushell_features|
|-|-|-|
|0.18.2|a64cfb6285a84cd5cffc10e36f4a398688abe6e6|default|

**Comment by thegedge** [comment]
`dirname` is an external for me, and appears to behave in a weird fashion:

```
> echo $(which nu | get path | dirname $it)
/usr/local/bin
───┬──
 0 │
───┴──

> echo $(which nu | get path | dirname $it | echo $it)
/usr/local/bin
```

So it looks like we're not properly capturing the output when an external is at the end of a block? 🤔

**Comment by andrasio** [comment]
Possibly related to a recent fix I did with `$()` invocation, maybe. See: #2423

**Comment by fdncred** [comment]
Related, I also just added a PR so that `dirname` and `filestem` are no longer external

**Comment by fdncred** [comment]
These works now with the built in `dirname`:
1. `echo $(which nu | get path | path dirname)`
2. `which nu | get path | path dirname | cd $it`
3. `which nu | get path | path dirname | trim | cd $it`

These do not work, although that may be because nu is being misused.
1.
```
which nu | get path | cd $(path dirname)
error: value is not string or path
  ┌─ shell:1:1
  │
1 │ which nu | get path | cd $(path dirname)
  │ -                          ^^^^^^^^^^^^ got nothing
  │ │
  │ originates from here
```
2. 
```
which nu | get path | cd $(path dirname $it)
error: Type Error
  ┌─ shell:1:41
  │
1 │ which nu | get path | cd $(path dirname $it)
  │                                         ^^^ Expected column path, found file path
```
3.
```
which nu | get path | trim | cd $(path dirname)
error: value is not string or path
  ┌─ shell:1:1
  │
1 │ which nu | get path | trim | cd $(path dirname)
  │ -                                 ^^^^^^^^^^^^ got nothing
  │ │
  │ originates from here
```
