### ISSUE TITLE
Aliases created via `config set startup` and `alias --save` are not deduplicated

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#2419]
**Describe the bug**

If I create an alias `x` using `config set startup`, and then create another one using `alias x --save`, it does not overwrite the previous alias.

**To Reproduce**
1. `config set startup ["alias x [msg] { echo $msg }"]`
2. `alias x --save [msg] { echo $msg }`
3. `config get startup`

**Expected behavior**
`config get startup` should only output 1 row with `alias x`, but it displays two of them.

**Configuration (please complete the following information):**
 - OS: Arch Linux
 - Nu version (you can use the `version` command to find out): 0.18.1
 - Optional features (if any): None

**Comment by bailey-layzer** [comment]
(2) ends up with an extra space between `x` and `[msg]` when it's saved.

**Comment by ajeetdsouza** [comment]
@bailey-layzer true, but shouldn't Nushell attempt to deduplicate aliases regardless of spacing?

**Comment by thegedge** [comment]
My two preferred options here:

1. Wait until we have profile scripts, at which point we can eliminate aliases that are saved in config and ask users to put their aliases in the profile script.
2. Switch to a "table"-like configuration for saved aliases, so saving naturally overwrites (like reassigning to an existing key in a hash table would overwrite the previous value). We'd key on the name of the alias.

**Comment by ajeetdsouza** [comment]
Still relevant.

**Comment by ajeetdsouza** [comment]
Relevant.

**Comment by fdncred** [comment]
neither `config` commands nor `alias --save` exist anymore in our latest main branch. so, I'm closing this. please re-open if you think this is in error.

configuration settings are in a config.nu script now and can be viewed our updated using idiomatic nushell commands. the special keyword is `$config`.
