### ISSUE TITLE
add suggestions for common commands, i.e. "It looks like you are using head, try first instead"

### ISSUE THREAD

**Issue by jakobhellermann** [nushell/nushell#2427]
When starting to use `nushell`, you have to study `help commands` for a while to even know how to start using it.
Like the rust compiler, which recognizes common mistakes, nushell could see that you use commands like `tail`, `xargs` etc. and suggest a better replacement.

Of course this does not apply to usages like 
```sh
$ head ...
```
but only to 
```sh
$ ls | head 5
```
since you may *want* to use the regular command.

I think this could make the "onboarding" experience much nicer for new users.

**Comment by thegedge** [comment]
Love the idea of improving the onboarding experience. I think it could potentially be quite difficult to implement, but maybe someone has some good ideas.

**Comment by pwnorbitals** [comment]
Love the idea too. I think we should start by listing the common commands (and use cases) and their `nushell` alternative. This could then be translated to rules we could apply in-code to warn the user
