### ISSUE TITLE
Shareable shell sessions.

### ISSUE THREAD

**Issue by andrasio** [nushell/nushell#245]
Building up on #244 | @androbtech // @jonathandturner 

With a polymorphic shell ring buffer (different types of shells bonded into the ring) we can add logic and permit two Nu users do things such as:

* Pair Programming
* Share Nu session to N users (Think N users watching your session on realtime)

Things worth investigating for landing this.
* Visibility of Nu users within the network.
* Zero-configuration.
* Nu session connections over some network securely regardless if it's a local network or from the internet. 
* Augmenting `enter` command and be able to inspect the users discoverable.
* Entering (`enter`) others users sessions 
* Augmenting `enter` and be able to "intelligently" figure out we want to enter a session over some network from other Nu users (`Eg. | enter nu://{IP}`)

**Comment by jaydeland** [comment]
Adding splits would be nice as well
