### ISSUE TITLE
No way of inclusive..exclusive ranges

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2459]
**Is your feature request related to a problem? Please describe.**
Current ranges, like `1..3` are inclusive on both ends, so what you get out would be 1, 2, 3.

It'd be nice to have a way of saying the right hand side was exclusive.

**Describe the solution you'd like**
We can start out with an addition to the current syntax. Here's the first one that came to mind:

* `1..3` - 1, 2, 3
* `1..<3` - 1, 2

**Describe alternatives you've considered**
We could make exclusive right hand side the default and use `1..=3` like Rust

**Comment by thegedge** [comment]
Ruby uses `...` for inclusive on the right, `..` for exclusive on the right.

I'm sure it would be really difficult for us to get the parser to do this, but the mathematical notation would be square brackets for inclusive ("closed") ranges and open brackets for exclusive ("open") ranges. I think the only way we could make this work in nu, without ambiguity, would be something like this:

```
[1..3] => 1, 2, 3
[1..3) => 1, 2
(1..3] => 2, 3
(1..3) => 2
```

**Comment by radekvit** [comment]
I would like to work on an implementation for the Rust-consistent variant (`..` for right-exclusive and `..=` for right-inclusive) if that's OK.
That can be changed to the original proposed solution with `..<` relatively trivially.

**Comment by pwnorbitals** [comment]
Now the PR is merged, we can probably close this issue
