### ISSUE TITLE
Using Ctrl-C to cancel program ends Nushell process

### ISSUE THREAD

**Issue by xSke** [nushell/nushell#2461]
**Describe the bug**
When running a long-lived process in Nushell and hitting Ctrl-C in the terminal, the entire Nushell process will end instead.

**To Reproduce**
1. Run a program that runs for a long time (meaning long enough to get a keypress in before it terminates naturally, so... a lot)
2. Hit Ctrl-C to stop that program

**Expected behavior**
I expected the "inner program" to terminate and to return to Nushell.

**Screenshots**
I can reproduce this with `npm`, since (on my system) it takes a second or two to return even for simple commands.

![image](https://user-images.githubusercontent.com/16242158/91668088-f1ab7480-eb09-11ea-80b5-f34827f7ac85.png)

After this, my terminal goes dead and I have to restart the session.

---

A similar thing happens when starting Nushell from the standard Windows command prompt:

![image](https://user-images.githubusercontent.com/16242158/91668122-38996a00-eb0a-11ea-9454-ffab3e6c81b5.png)

Although after this, the terminal is left in a strange state (see the `Terminate batch job (Y/N)?`) where it's seemingly alternating between being in and out of Nushell? I don't know what's going on there...

![image](https://user-images.githubusercontent.com/16242158/91668135-5ff03700-eb0a-11ea-840b-c73db7a68a72.png)

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Windows 10 20.04, using Windows Terminal 1.1.200810003-release1.1, with Nushell configured as the shell directly in WT.
 - Nu version (you can use the `version` command to find out): 0.18.1, from `scoop`
 - Optional features (if any): `default`, `clipboard`, `trash`, `starship`

Can't reproduce from PowerShell, weirdly.

**Comment by xSke** [comment]
(whoops, submitted too early, will edit)

**Comment by sudomabider** [comment]
Can confirm this has been happening for me since I started using nushell from `0.15`.  Happens in windows terminal, and integrated terminals such VS, vscode.

**Comment by thegedge** [comment]
Let's try to narrow this down, as there's not too many places where nushell will exit. What do you see for:

```
> config get ctrlc_exit
```

**Comment by xSke** [comment]
> 
> 
> Let's try to narrow this down, as there's not too many places where nushell will exit. What do you see for:
> 
> ```
> > config get ctrlc_exit
> ```

Upgraded to 0.19.0, issue still persists:

```
Welcome to Nushell 0.19.0 (type 'help' for more info)
C:\Users\Astrid> config get ctrlc_exit
error: Missing key in config
  ┌─ shell:1:12
  │
1 │ config get ctrlc_exit
  │            ^^^^^^^^^^ key

C:\Users\Astrid>
```

Nothing for `ctrlc_exit`?

**Comment by thegedge** [comment]
I think the only other place we'd exit the process would be here: https://github.com/nushell/nushell/blob/0178b532893a0d06095a109586aa7444efd3ec57/crates/nu-cli/src/cli.rs#L775-L777

Which is likely due to a readline error. I'm thinking the process exiting when hitting Ctrl-C is a red herring, and this is actually just a manifestation of https://github.com/nushell/nushell/issues/2401. I think https://github.com/nushell/nushell/pull/2533 is intended to fix that issue.

**Comment by fdncred** [comment]
As said above, this ctrl-c error has been happening for months. I've tested with the latest version of rustyline and the problem still exists. #2533 does not fix tihs issue on Windows. This issue is a duplicate of #2038.

#2440 is fixed by #2533.

This is the backtrace I created this morning.

```
thread 'main' panicked at 'expect_string assumes that the value must be a string', crates\nu-protocol\src\value.rs:127:18
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\fmt\mod.rs:1076
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\io\mod.rs:1537
   5: std::sys_common::backtrace::_print
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:217
   9: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:526
  10: std::panicking::begin_panic
  11: nu_protocol::value::UntaggedValue::expect_string
  12: nu_cli::cli::cli::{{closure}}
  13: std::thread::local::LocalKey<T>::with
  14: futures_executor::local_pool::block_on
  15: <alloc::collections::vec_deque::VecDeque<T> as core::ops::drop::Drop>::drop
  16: <<toml::value::Value as serde::de::Deserialize>::deserialize::ValueVisitor as serde::de::Visitor>::visit_str
  17: std::rt::lang_start_internal::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\rt.rs:52
  18: std::panicking::try::do_call
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:348
  19: std::panicking::try
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:325
  20: std::panic::catch_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panic.rs:394
  21: std::rt::lang_start_internal
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\rt.rs:51
  22: main
  23: invoke_main
             at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  24: __scrt_common_main_seh
             at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  25: BaseThreadInitThunk
  26: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by thegedge** [comment]
That's definitely a panic-able line, @fdncred . Although it would break things for anyone that has this config set properly, we should probably use `as_bool` (so people would set it with `$true` inside the shell).

That being said, I don't think that's the issue. @xSke showed us that they don't have `ctrlc_exit` set, and yet are still seeing the issue. That line of code cannot be reached if the config value isn't set.

**Comment by fdncred** [comment]
Changing from
```rust
.map(|s| s.value.expect_string() == "true") 
```
to
```rust
.map(|s| s.value.is_true())
```
fixed the problem for me.

I'll see if I can repro the problem without a config.

**Comment by fdncred** [comment]
Please test with latest main and let us know if you still have issues.

**Comment by xSke** [comment]
Still on 0.19.0, but I'm not getting a backtrace from Nushell at all. Again can't repro this on PowerShell but using cmd.exe and setting RUST_BACKTRACE=1 just makes the issue happen as normal with on additional output. This doesn't seem to be a panic at all, given WT tells me `[process exited with code 3221225786]` - that exit code being `0xC000013A` or `STATUS_CONTROL_C_EXIT` (per https://stackoverflow.com/a/25444766).

I'll try on latest main and see if it still happens, though :)

**Comment by xSke** [comment]
@fdncred Update: can still reproduce on 0.20.0, unfortunately :/
![image](https://user-images.githubusercontent.com/16242158/94526462-d7160980-0235-11eb-8779-b8b22634a172.png)

**Comment by fdncred** [comment]
@xSke Strange. I just did the same thing and it worked with a build from a couple days ago. I wonder what is different.
```npm --version
^C^CTerminate batch job (Y/N)? y
error: External command failed
  ┌─ shell:1:1
  │
1 │ npm --version
  │ ^^^ command failed
```

**Comment by xSke** [comment]
If more info about my environment helps, this is Windows Terminal 1.3.2651.0, Nushell 0.20.0 installed from scoop (https://github.com/ScoopInstaller/Main/blob/master/bucket/nu.json). This happens with any command, I just used `npm` as an example of something that executes slowly enough for me to hit Ctrl-C while running. And as mentioned before, I can *not* reproduce this running `nu` from PowerShell - however, I *can* when running `cmd` from PowerShell, and running `nu` in *there*. So maybe PowerShell is doing something funky (although correct?) with SIGINTs that the others aren't?

**Comment by fdncred** [comment]
I can't figure out how to reproduce this problem.
I've used Windows Terminal 1.3.2651.0 and1.4.2652.0.
I've launched nu.exe 
* from Win+R 
* from both versions of windows terminal by setting nu up in the WT settings.json
* by launching cmd.exe and then running nu.exe
* by launching powershell.exe and then running nu.exe
* by launching pwsh.exe and then running nu.exe

In all situations I've tried Ctrl+C seems to work as expected and cancels the batch file that `npm` executes.

If you do `which npm` from nu, does it look similar to this?

```
 which npm
───┬─────┬─────────────────────────────────┬─────────
 # │ arg │ path                            │ builtin
───┼─────┼─────────────────────────────────┼─────────
 0 │ npm │ C:\Program Files\nodejs\npm.cmd │ No
───┴─────┴─────────────────────────────────┴─────────
```

**Comment by xSke** [comment]
Yes:

```
C:\Users\Astrid> which npm
───┬─────┬───────────────────────────────────────────────────────┬─────────
 # │ arg │                         path                          │ builtin
───┼─────┼───────────────────────────────────────────────────────┼─────────
 0 │ npm │ C:\Users\Astrid\scoop\apps\nodejs-lts\current\npm.cmd │ No
───┴─────┴───────────────────────────────────────────────────────┴─────────
```

**Comment by fdncred** [comment]
So you should get the same `Terminate batch job (Y/N)?` that I do.

Do you get the same error if you build from main?

**Comment by xSke** [comment]
...I've worked it out. Looks like the key was that I installed Nushell through scoop, which wraps executables in a shim presumably to have a coherent PATH. I'm not sure what it's doing, but if I run nushell *directly* from the install directory, then the issue goes away? Which I guess is the solution, but this is still veeeeery weird. I'll close the issue and see if I have the energy to make an issue on their repo instead :)

**Comment by imranmaj** [comment]
I'm not using scoop, but I'm still getting this error. It exits with:

```Error: Io(Os { code: 87, kind: InvalidInput, message: "The parameter is incorrect." })```.

**Comment by fdncred** [comment]
@imranmaj I've seen this error many times and it's usually due to a `rustyline` bug. There have been several of them fixed. My guess is that you're not using the latest version of nushell. If you are, please correct me.

**Comment by imranmaj** [comment]
Yes, I was on 0.18.1. I have updated to 0.20.0 and the issue seems to have been fixed. Thank you!

**Comment by sagacity** [comment]
I'm seeing this behaviour using nu 0.26.0 (installed via scoop) and Windows Terminal 1.4.3243.0 (installed via Windows App Store). Is there anything I can do to help reproduce? The configuration property `ctrlc_exit` was not set, but setting it to `false` explicitly didn't help.

Using a different version of Terminal (1.4.201119003-release1.4, via Scoop) doesn't help.

**Comment by fdncred** [comment]
You might try running it without scoop. @xSke reported that this solved the issue.

**Comment by sagacity** [comment]
Argh, sorry, I totally missed that. Running nu directly indeed works, thanks!

**Comment by babinc** [comment]
Fixed it by install it it with `cargo` rather than `winget`
