### ISSUE TITLE
size command: char definition

### ISSUE THREAD

**Issue by gillespiecd** [nushell/nushell#2465]
For the `size` command, are chars supposed to represent the number of human readable chars (a.k.a graphmeme) or number of "chars" as in a Rust primitive?

To see what I mean:

```
> echo "Amélie" | size
────────────┬───
 lines      │ 0
 words      │ 1
 chars      │ 7
 max length │ 8
────────────┴───
> echo "Amelie" | size
────────────┬───
 lines      │ 0
 words      │ 1
 chars      │ 6
 max length │ 6
```

If the behavior works as intended, maybe we could add another output or flag for human readable chars?

Additionally, it may be worth clarifying "max length" is the total number of bytes? I originally found the term "max length" a little confusing, but maybe that's just me.

**Comment by thegedge** [comment]
Definitely worth doing two things here:
1. Emphasize if "length" is byte
2. Show both byte and char length
