### ISSUE TITLE
SQL join two tables

### ISSUE THREAD

**Issue by sanga** [nushell/nushell#2469]
**Is your feature request related to a problem? Please describe.**
I would like the ability to be able to join two tables together in the sql meaning of the word "join"

**Describe the solution you'd like**
Perhaps an example would be illustrative. Currently I'm trying to build a table containing all pertinent info for github PRs. Essentially to easily answer the question "what can currently be merged". This involves pulling json from 2 places: Our CI system and from github. So after I\ve gotten the data, I have two tsv files (as in the attached image). I would like to be able to make a single table our of those two tsv files, by "joining" them on the `id` column.
![2020-08-31-194550_grim](https://user-images.githubusercontent.com/2088/91745800-3abfff00-ebc4-11ea-85fa-c590558a57f1.png)

**Describe alternatives you've considered**
TBH I haven't considered alternatives :)

**Comment by vpperego** [comment]
This is an awesome feature and I believe it was already proposed in this [issue](https://github.com/nushell/nushell/issues/549).

**Comment by marekdedic** [comment]
This is still relevant, don't close this...

**Comment by dumblob** [comment]
This will most probably require performant [differential dataflow](https://scattered-thoughts.net/writing/why-isnt-differential-dataflow-more-popular/ ) (see also [query planning for streaming systems](https://scattered-thoughts.net/writing/why-query-planning-for-streaming-systems-is-hard )).

E.g. [dida]( https://github.com/jamii/dida ) (from the author of the linked blog posts) is a very good implementation.

**Comment by jjorissen52** [comment]
If I understand the question correctly, you achieve this using [dataframes](https://www.nushell.sh/book/dataframes.html).

|Column0|Column1|
|-|-|
|version|0.39.0|
|build_os|macos-x86_64|
|rust_version|rustc 1.58.0-nightly (c390d69a6 2021-10-28)|
|rust_channel|nightly-x86_64-apple-darwin (default)|
|cargo_version|cargo 1.58.0-nightly (6c1bc24b8 2021-10-24)|
|pkg_version|0.39.0|
|build_time|2021-10-29 14:04:12 -05:00|
|build_rust_channel|release|
|features|ctrlc, dataframe, default, rustyline, term, which, zip|
|installed_plugins|fetch, from sqlite, match, post, ps, sys|

**Comment by fdncred** [comment]
since this is supported with dataframes, called `dfr` in the latest main branch. I'm closing this. please re-open if you find this in error.
