### ISSUE TITLE
Completions: auto-cd paths don't get quotes

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2477]
**Describe the bug**
Auto-cd doesn't properly quote in cases where `cd <path>` will.

**To Reproduce**
1. Use auto-cd to change to a directory with a space.
2. Compare to the result of typing `cd` first

**Expected behavior**
These should have the same quoting behavior.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Pop! OS
 - Nu version (you can use the `version` command to find out): latest main

**Comment by gorogoroumaru** [comment]
@jonathandturner, could you explain what "properly quote" means in detail?
