### ISSUE TITLE
Panic in str to-datetime

### ISSUE THREAD

**Issue by tiffany352** [nushell/nushell#2484]
**Describe the bug**
Nu panics and exits to the parent shell when you use `str to-datetime` wrong.

**To Reproduce**
```
/home/tiffany> echo "1566997680962280" | str to-datetime
thread 'main' panicked at 'invalid or out-of-range date', /builddir/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.13/src/naive/date.rs:173:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
➜  ~
```
I accidentally ran into this while trying to import `journalctl` output as a way of learning to use Nu.

I tried running with `RUST_BACKTRACE` set but it just prints a bunch of `<unknown>` in the build I have installed. (Installed from Fedora package).

**Expected behavior**
It shouldn't panic. A panic handler for cases like this would be nice too.

**Screenshots**

**Configuration (please complete the following information):**
 - OS: Fedora 31 (Server Edition)
 - Nu version: 0.18.1
 - Optional features: default, clipboard, trash, starship

**Comment by rezural** [comment]
I get this on nighgly, ubuntu 20.04,

thread 'main' panicked at 'invalid or out-of-range date', /home/rezural/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.15/src/naive/date.rs:173:51
stack backtrace:
   0: rust_begin_unwind
             at /rustc/73dc675b9437c2a51a975a9f58cc66f05463c351/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/73dc675b9437c2a51a975a9f58cc66f05463c351/library/core/src/panicking.rs:85
   2: core::option::expect_failed
             at /rustc/73dc675b9437c2a51a975a9f58cc66f05463c351/library/core/src/option.rs:1213
   3: core::option::Option<T>::expect
             at ./.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:333
   4: chrono::naive::date::NaiveDate::from_ymd
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.15/src/naive/date.rs:173
   5: dtparse::Parser::build_naive
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/dtparse-1.1.0/src/lib.rs:966
   6: dtparse::Parser::parse
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/dtparse-1.1.0/src/lib.rs:725
   7: dtparse::parse
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/dtparse-1.1.0/src/lib.rs:1346
   8: nu_cli::commands::str_::to_datetime::action
             at /mnt/5961635e-9d86-438d-98d3-b10e29e84d06/code/nushell/crates/nu-cli/src/commands/str_/to_datetime.rs:134
   9: nu_cli::commands::str_::to_datetime::operate::{{closure}}::{{closure}}
             at /mnt/5961635e-9d86-438d-98d3-b10e29e84d06/code/nushell/crates/nu-cli/src/commands/str_/to_datetime.rs:96
  10: <T as futures_util::fns::FnMut1<A>>::call_mut
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/fns.rs:28
  11: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::{{closure}}
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/stream/stream/map.rs:62
  12: core::option::Option<T>::map
             at ./.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:437
  13: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/stream/stream/map.rs:62
  14: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/stream/stream/map.rs:61
  15: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.5/src/stream.rs:121
  16: <nu_cli::stream::output::OutputStream as futures_core::stream::Stream>::poll_next
             at /mnt/5961635e-9d86-438d-98d3-b10e29e84d06/code/nushell/crates/nu-cli/src/stream/output.rs:48
  17: <futures_util::stream::stream::then::Then<St,Fut,F> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/stream/stream/then.rs:79
  18: <futures_util::stream::stream::flatten::Flatten<St,<St as futures_core::stream::Stream>::Item> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/stream/stream/flatten.rs:55
  19: <futures_util::stream::stream::Flatten<St> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:118
  20: <futures_util::stream::stream::take_while::TakeWhile<St,Fut,F> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/stream/stream/take_while.rs:87
  21: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.5/src/stream.rs:121
  22: <nu_cli::stream::input::InputStream as futures_core::stream::Stream>::poll_next
             at /mnt/5961635e-9d86-438d-98d3-b10e29e84d06/code/nushell/crates/nu-cli/src/stream/input.rs:154
  23: futures_util::stream::stream::StreamExt::poll_next_unpin
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/stream/stream/mod.rs:1323
  24: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/stream/stream/next.rs:35
  25: nu_cli::commands::autoview::command::autoview::{{closure}}
             at /mnt/5961635e-9d86-438d-98d3-b10e29e84d06/code/nushell/crates/nu-cli/src/commands/autoview/command.rs:99
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
  27: nu_cli::cli::process_line::{{closure}}
             at /mnt/5961635e-9d86-438d-98d3-b10e29e84d06/code/nushell/crates/nu-cli/src/cli.rs:1021
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
  29: nu_cli::cli::cli::{{closure}}
             at /mnt/5961635e-9d86-438d-98d3-b10e29e84d06/code/nushell/crates/nu-cli/src/cli.rs:729
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
  31: futures_executor::local_pool::block_on::{{closure}}
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  32: futures_executor::local_pool::run_executor::{{closure}}
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:87
  33: std::thread::local::LocalKey<T>::try_with
             at ./.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:271
  34: std::thread::local::LocalKey<T>::with
             at ./.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:247
  35: futures_executor::local_pool::run_executor
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:83
  36: futures_executor::local_pool::block_on
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  37: nu::main
             at /mnt/5961635e-9d86-438d-98d3-b10e29e84d06/code/nushell/src/main.rs:158
  38: core::ops::function::FnOnce::call_once
             at ./.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227

**Comment by thegedge** [comment]
Looking at `dtparse` (what we currently use for datetime parsing), I think an "integer string" is intended to basically be `YYYYMMDDHHMMSS`, whereas I think you have a UNIX timestamp.

A couple of things here. First, We definitely shouldn't panic.

Second, we don't have any means to convert a UNIX timestamp to a nushell datetime. Given the above, it'd be hard to distinguish between a UNIX timestamp and an "integer date string". We could probably add a flag to `str to-datetime` to indicate the string is a UNIX timestamp.
