### ISSUE TITLE
Settings starship prompt causes incorrect output

### ISSUE THREAD

**Issue by reflog** [nushell/nushell#2485]
**Describe the bug**
Starship prompt on nu is rendered incorrectly:

**To Reproduce**
1. install starship prompt
2. ```config set prompt `echo $(starship prompt)` ```

**Expected behavior**
Should look something like:
![image](https://user-images.githubusercontent.com/109876/91944055-27b54800-ed06-11ea-85c6-ce8c7a54a504.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/109876/91944020-1ff5a380-ed06-11ea-820b-fd7b37fdf84f.png)

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Ubuntu 20
 - Nu version (you can use the `version` command to find out): 0.19
 - Optional features (if any): extra

P.S. Powerline works just fine:
after ``` config set prompt `echo $(powerline shell left)` ```
![image](https://user-images.githubusercontent.com/109876/91944371-a4482680-ed06-11ea-907b-d31e39ecd03a.png)

**Comment by jonathandturner** [comment]
@reflog - are you running Nu inside another shell by chance? Some people have reported having issue that way, especially if both shells are using starship.

**Comment by reflog** [comment]
@jonathandturner - correct! running from zsh that also used starship.

**Comment by jonathandturner** [comment]
@reflog - I'm not sure, but this may be a bug in starship. If you run only one copy of starship (the one in Nu), does it work correctly?

**Comment by jonathandturner** [comment]
It's also possible that starship is detecting that zsh is running and then outputs thinking the shell is zsh. You may need to set some environment variables so that it doesn't try to do that.

**Comment by Zooce** [comment]
I'm having a similar issue but it's just not using starship at all, starting nu from inside bash, but without using starship in bash, running the latest Pop!_OS.

**Comment by crides** [comment]
I found this out as well right after installing 0.19.0. I think the problem comes from `STARSHIP_SHELL`. Try to check that env variable inside `nu`. For me, it's set to `zsh` no matter what, and I found out it comes from the config, when I followed the book and `config set env $nu.env`, which contained that env var set to `zsh`.

**Comment by ritobanrc** [comment]
I was having the same issue with zsh and nushell, but it works correctly when I have only one instance of starship running. However, I can use multiple instances of starship between zsh and bash or zsh and fish, so this still feels like a nushell bug.

**Comment by davidarmstronglewis** [comment]
I'm not so sure this is a nushell bug. I use starship with zsh and when I run `starship prompt` from within zsh I get a similarly messed up output. Has anyone interacted with the starship folks about this or know if there's an issue open on their end with regards to this?

**Comment by DanielRivasMD** [comment]
I was having the same problem, `zsh` session with `starship` active and `nushell` session with incorrect parsing. The solution, inspired on above comments, add the following lines to your `nushell` `config.toml`:

```
prompt = "echo $(starship prompt)"

[env]
STARSHIP_SHELL = "nushell"
``` 

That way you overwrite the conflicting variable (`STARSHIP_SHELL`) within the current shell. Cheers

**Comment by davidarmstronglewis** [comment]
@DanielRivasMD thanks for the tip! I keep bouncing away and coming back to nushell. Every time I do there's new features that solve previous pain points ❤️

**Comment by eoinkelly** [comment]
Just in case anybody else ends up here, the following configuration correctly set up nushell 0.41.0 started from zsh with both using starship:

```toml
# nushell config.toml (location varies depending on how you installed nushell)
prompt = "starship prompt"

[env]
STARSHIP_SHELL = "nushell"
```
