### ISSUE TITLE
Interpret ranges for substring differently to allow more use-cases

### ISSUE THREAD

**Issue by PunkIslamist** [nushell/nushell#2493]
When I was looking for a way to strip the file extension off of file names, I thought I could just use `str substring`. Given the current way that the `range` argument is interpreted, this is not easy.

I think the following interpretation of the `start` and `end` of the range would cover more use cases than the current one:
- `echo 'good nushell' | str substring '5,12'` -> stays the same, returns `nushell`
- `echo 'good nushell' | str substring ',-5'` -> **changed** `-5` always means 5th char from the end, so it goes from `0` to `length - 5` and returns `good nu`
- `echo 'good nushell' | str substring '5,'` -> stays the same, returns `nushell`
- `echo 'good nushell' | str substring ',7'` -> stays the same, returns `good nu`
- `echo 'good nushell' | str substring '-5,'` -> **changed**  `-5` always means 5th char from the end, so it goes from `length - 5` to the end and returns `shell`
- `echo 'good nushell' | str substring '-3,-5'` -> **changed** this would try to go from `length - 3` to `length - 5` and throw the `End must be greater than or equal to Start` error

**Describe alternatives you've considered**
You can `str reverse`, then do `str substring [range]`, and do one more `str reverse`, but that seems really inefficient and clunky. Or you could somehow get the length first and use that somehow?

PS: thanks for your great work so far, I am really enjoying Nushell so far!

**Comment by thegedge** [comment]
Resolved by https://github.com/nushell/nushell/pull/2499
