### ISSUE TITLE
User Env & Path Not Being Merged w/ System Env & Path on Windows

### ISSUE THREAD

**Issue by forgiv** [nushell/nushell#2515]
**Describe the bug**
In Windows there's a User Env that's separate from the System Env. These Envs are merged together by the shell and made available as a single Env. nushell isn't doing that. It's only making the System Env available while ignoring the User Env.

**To Reproduce**
1. Open the Environment Variables GUI in Windows and take note of the two separate sections (Users & System)
2. Open nushell, I opened with a profile in Windows Terminal but I've also tested this by running the nu executable from within PowerShell and got the same issue
3. Run `echo $nu.path` and `echo $nu.env` and notice that the results do not include the environment variables from the top section of the Environment Variables GUI (the user environment section)

**Expected behavior**
User Environment and System Environment should be merged together when the environment and path is mounted in nushell.

**Screenshots**
Path mounted in nushell
![image](https://user-images.githubusercontent.com/1571866/92521674-9fdeaa80-f1eb-11ea-8d28-728f96d0c38d.png)

System Path: Maches Path Mounted in nushell
![image](https://user-images.githubusercontent.com/1571866/92521763-c8ff3b00-f1eb-11ea-9732-684d980b9871.png)

User Path: Missing From nushell
![image](https://user-images.githubusercontent.com/1571866/92521722-b1c04d80-f1eb-11ea-9bf1-ced3330da1c2.png)

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Windows 10
 - Nu version (you can use the `version` command to find out):  0.19.0
 - Optional features (if any): none

**Comment by thegedge** [comment]
This is interesting. We do use `std::env::vars` to get env vars from the host, so at first glance it appears it could be a bug there.

I took a quick look, and it appears rust uses [`GetEnvironmentStringsW`](https://github.com/rust-lang/rust/blob/838325726a05855f10fbb6b3dc7165a7d8dde7b9/library/std/src/sys/windows/os.rs#L136), which from its docs says:

> The `GetEnvironmentStrings` function returns a pointer to a block of memory that contains the environment variables of the calling process (both the system and the user environment variables)

So it looks like it could be something on our end 🤔

**Comment by forgiv** [comment]
I ran this code from the rust doc [here](https://doc.rust-lang.org/std/env/fn.vars.html)

```rust
use std::env;

// We will iterate through the references to the element returned by
// env::vars();
for (key, value) in env::vars() {
    println!("{}: {}", key, value);
}
```

This is the path that was returned:

```
Path: 
C:\ProgramData\scoop\shims;
C:\windows\system32;
C:\windows;
C:\windows\System32\Wbem;
C:\windows\System32\WindowsPowerShell\v1.0\;
C:\windows\System32\OpenSSH\;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\WINDOWS\System32\OpenSSH\;
C:\HashiCorp\Vagrant\bin;
C:\Program Files\dotnet\;
C:\Users\shark\scoop\apps\nodejs-lts\current\bin;
C:\Users\shark\scoop\apps\nodejs-lts\current;
C:\Users\shark\scoop\apps\openssl\current\bin;
C:\Users\shark\scoop\apps\composer\current\home\vendor\bin;
C:\Users\shark\scoop\apps\nu\current\Plugins;
C:\Users\shark\scoop\shims;
C:\Users\shark\AppData\Local\Microsoft\WindowsApps
```

When comparing to above I can see that the path does indeed have my user path merged into it.

I think that can confirm that's it's something on nushells end.

**Comment by thegedge** [comment]
Thanks for exploring that, @forgiv. Agreed, that confirms we must be doing something weird on our end.

There'll be some investigation, but I suspect this is a fairly easy fix, so I'm gonna tag this as a good first issue. I could be very wrong about that though 😅

**Comment by jankoprowski** [comment]
I built nu from latest sources under Windows today and I do not see repro.

OS: `Windows 10`
Command used to build nu: `cargo build`

![image](https://user-images.githubusercontent.com/125283/95682690-f114fc00-0be6-11eb-8edf-1a29f16fd8b3.png)
![image](https://user-images.githubusercontent.com/125283/95682708-0d189d80-0be7-11eb-86f4-8768338fe0a5.png)

**Comment by forgiv** [comment]
Ran again on version 0.20.0 and issue is gone. I'm gonna go ahead and close this issue since I can no longer recreate the problem on the current version.

@jankoprowski I tried running with and without administrator and the result was the same.
