### ISSUE TITLE
Durations should allow for decimals

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2516]
**Describe the bug**
`10.5sec` should parse but it's not currently allowed.

**To Reproduce**
1. Use a decimal with a unit, like `10.5sec`

**Expected behavior**
This is a handy shorthand rather than having to write out the a decimal + unit. Some of these don't make sense, since `0.5ns` isn't currently supported, so we'd need to figure out how we want to do it.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Any
 - Nu version (you can use the `version` command to find out): latest main

**Comment by xolve** [comment]
Would like to take a dig at this one.
