### ISSUE TITLE
Better docs for `update`

### ISSUE THREAD

**Issue by tiffany352** [nushell/nushell#2518]
**Is your feature request related to a problem? Please describe.**
I was having a lot of trouble figuring out how to table a table, update 1 column, and then output a new table with that column updated. The `update` command's documentation only shows how to add a fixed value to the table, and not perform transformations of the old value.

**Describe the solution you'd like**

Better documentation, and maybe a reference in the cookbook.

**Describe alternatives you've considered**
I'm fairly new to query based languages like Nu so I'm not sure.

**Additional context**

For anyone reading this and wondering how to use `update`:

Say you have a table like this:
```
❯ open fonts.json | first 3
───┬───────────┬───────┬────────────────
 # │   Name    │ Value │      Tags
───┼───────────┼───────┼────────────────
 0 │ Legacy    │     0 │ [table 1 rows]
 1 │ Arial     │     1 │ [table 2 rows]
 2 │ ArialBold │     2 │ [table 0 rows]
───┴───────────┴───────┴────────────────
```

and you want to perform a transformation on `Tags` to make it readable. You use the `update` command like this:
```
❯ open fonts.json | update Tags { get Tags | str collect ", " } | first 3
───┬───────────┬───────┬──────
 # │   Name    │ Value │ Tags
───┼───────────┼───────┼──────
 0 │ Legacy    │     0 │ Deprecated
 1 │ Arial     │     1 │ Foo, Bar
 2 │ ArialBold │     2 │
───┴───────────┴───────┴──────
```

**Comment by jonathandturner** [comment]
Agreed :+1: . The docs are definitely due a rewrite. This is one of those areas that really need to have whole new chapters, since we've changed a fair bit about how to work with tables since we first wrote those sections in the book.

**Comment by fdncred** [comment]
I had the same problem so I wrote this alias that I can refer to in order to remind me.
`alias nuver [] {version | update features {get features | str collect ', '} }`

Then I can do `nuver | to md` and get this table below.

|version|commit_hash|features|
|-|-|-|
|0.19.0|d9ae66791a6d5eca9e76422815a1f5d0075dd0ea|default, clipboard, trash|

**Comment by radekvit** [comment]
Apart from improving the docs, would this be a good new internal command?
Something like
`version | flatten features` => 
version | commit_hash | features
-- | -- | --
0.19.0 | d9ae667 | default, clipboard, trash



I could imagine variants
* `flatten` - flattens all columns
* `flatten column_name` - flattens single column
* `flatten -r`, `flatten -r column_name` - could handle tables within tables by serializing them into strings
