### ISSUE TITLE
`open` should check file type before steaming output

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2519]
**Describe the bug**
If you do `open bigfile.png` or `open bigfile.txt` we stream the data out progressively, which makes it difficult to work with the data as we one did.

**To Reproduce**
1. See above
2. 
3. 

**Expected behavior**
We should check that the file is a file, and if so, to read the file.  If it's a character device, like /dev/random on Linux, then we can opt to not try to load the whole file but instead progressively stream like the current `open` behavior.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): All
 - Nu version (you can use the `version` command to find out): latest main

**Comment by fdncred** [comment]
It seems like this would fix the emulator as well.
