### ISSUE TITLE
Remove plugin search path

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#252]
We should narrow our search path down to one predictable place to find the plugins, which can be configured by the user.

**Comment by wycats** [comment]
Would the user use symlinks to merge together multiple locations where plugins were found?

This problem seems like "we need some sort of package management"

**Comment by jonathandturner** [comment]
The current design of searching path seems to be the easiest for cross-languages.  We may want to revisit in the future, but closing for now
