### ISSUE TITLE
Nu hangs when pipes have nothing on either side of them (excluding other pipes)

### ISSUE THREAD

**Issue by mhmdanas** [nushell/nushell#2521]
**Describe the bug**
If you put nothing on either or both sides of a pipe, Nu will hang. This doesn't include other pipes.

**To Reproduce**

There are many ways to reproduce this behavior. They include, but are not limited to:
- `|`
- ` | ` (there's whitespace around this one but GitHub doesn't show it for some reason.)
- `| echo`
- ` | echo` (whitespace before pipe)
- `echo | |`
- `echo | | |`

Somewhat confusingly, running `echo || |` works but echos `||`.

I will add any other interesting commands later.

**Expected behavior**
Nu should report an error.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): macOS 10.15.6
 - Nu version (you can use the `version` command to find out): 0.19.0
 - Optional features (if any): none

Since you can put anything instead of `echo`, even if it doesn't exist, I believe this is most likely a parsing issue.

**Comment by mhmdanas** [comment]
This issue is mostly the same as #2606, except that it happens with pipes and not parens or quotes. Should this issue be closed and incorporated into that issue or should it just be renamed?

**Comment by jonathandturner** [comment]
More recent nu versions seem to give parse errors for incomplete pipelines. Closing, but please reopen if you're still seeing an issue
