### ISSUE TITLE
0.19 autocomplete paths doesn't work on macos

### ISSUE THREAD

**Issue by AndrewMorsillo** [nushell/nushell#2523]
**Describe the bug**
Per title, autocomplete doesn't work for paths on macos. This is a bummer because path autocompletion is pretty much the most common operation in day to day use.

**To Reproduce**
1. `cargo install nu --features=extra`  (stable rust)
2. `nu`
3. `cd /Us<tab><tab>` -- no completion

**Expected behavior**
Autocomplete should work for paths on all systems

**Configuration (please complete the following information):**
 - OS (e.g. Windows): MacOS 10.15.6
 - Nu version (you can use the `version` command to find out): 0.19.0
 - Optional features (if any): extra

**Comment by mhmdanas** [comment]
This is odd. I'm using the same macOS and Nu version as you, but withoutoptional features. Path autocompletion is working flawlessly for me.

**Comment by AndrewMorsillo** [comment]
It is strange. A bell icon shows up on the top of iTerm2 when I press tab to complete a path. I can't debug further now but later I will try a reboot and reinstall nu without extra features to see if that's the issue.

**Comment by thegedge** [comment]
I just merged https://github.com/nushell/nushell/pull/2525, which I think should fix this issue. Would you be able to verify, @AndrewMorsillo.

**Comment by AndrewMorsillo** [comment]
@thegedge works fine with the change, thanks!
