### ISSUE TITLE
Nushell should modify the window title

### ISSUE THREAD

**Issue by coolshaurya** [nushell/nushell#2527]
**Is your feature request related to a problem? Please describe.**
It would be nice to differentiate at a glance between different terminals that have different programs/directories open. Most programs like kakoune and bash change the window title. 

**Describe the solution you'd like**

1. Nushell to change the window title to something  like `Nushell - ~/blah/meow` that shows the current directory by default.
1. Have a config option to change the default similar to the prompt config option

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by fdncred** [comment]
@coolshaurya I'm guessing you're not talking about windows but from Windows I have this as the first line of my `startup` config.
```
startup = [
    "title NuShell v $(version | get version)",
```

What would be the trigger to update the title? Would it be when someone cd's? With a config entry that is something like this `title = $(pwd)`?

Theoretically, on Windows, one could update the title from the prompt like `prompt = title $(pwd) ; za $(pwd) ; other stuff to draw prompt`

**Comment by coolshaurya** [comment]
> What would be the trigger to update the title? Would it be when someone cd's? 

Currently when I open a program that sets the title and then exit it the title persists. Therefore I think the title should be updated every time a command is executed.

> With a config entry that is something like this title = $(pwd)?

Yes

**Comment by mborejdo** [comment]
It would be great, if nushell's echo would support escape-sequences (see https://github.com/nushell/nushell/issues/1251). We could use OSC1-escape sequence in nushells prompt

**Comment by fdncred** [comment]
@mborejdo I use these aliases to set the window title.

```
"alias set_title_str [str-arg] {echo [$(char title) ' ' $str-arg ' ' $(char bel)] | str collect}",
"alias get_abbrev_pwd_win [] {echo [$(pwd | split row '\\' | first $(pwd | split row '\\' | count | each {= $it - 1} ) |  str substring '0,1' | format '{$it}/' | append $(pwd | split row '\\' | last ) | str collect)] | str collect}",
"alias get_abbrev_pwd_lin [] {echo [$(pwd | split row '/' | first $(pwd | split row '/' | count | each {= $it - 1} ) | each { str substring '0,1' | format '{$it}/' } | append $(pwd | split row '/' | last ) | str collect)] | str collect}",
"alias set_title [] {set_title_str $(echo $(get_abbrev_pwd_win))}",
```

The secret sauce [starts here](https://github.com/nushell/nushell/blob/4e17292a12a7913c8cd308e81af4f9c9fcb3f4fc/crates/nu-cli/src/commands/char_.rs#L141) with some escape sequences.

**Comment by mborejdo** [comment]
@fdncred ah nice. Didn't know about the builtin escape sequences. Would be great to be more flexible here and be able to echo custom sequences. For example I also use OSC-7 to announce the current working directory to my terminal

**Comment by fdncred** [comment]
@mborejdo I'm working on something for the ansi command to take escape sequences without the escape char like `ansi -e "1;31m"`. I'm not sure it'll work though. Also, do you have a good reference form ansi escape sequences and osc escape sequences?

**Comment by mborejdo** [comment]
@fdncred thats great! The best I came across so far is https://xtermjs.org/docs/api/vtfeatures/ which features an extensive list.

**Comment by fdncred** [comment]
I don't understand what OSC-7 does. Is it just like a `pwd`?

**Comment by mborejdo** [comment]
I am not sure how widely supported the OSC7-sequence is. I am using it for https://github.com/wez/wezterm 's tab and split functionality to maintain the PWD across splits and tabs. Here the author describes it: https://wezfurlong.org/wezterm/shell-integration.html

**Comment by fdncred** [comment]
@mborejdo If you wanted to test the changes to the ansi command you can try this branch https://github.com/fdncred/nushell/tree/csi_osc_sequence_support. I can't tell if the osc stuff is working or not. I may end up removing it if I can't confirm it works.

**Comment by fdncred** [comment]
#2719 should close this if it wasn't closeable already.

**Comment by fdncred** [comment]
closing as #2719 landed

**Comment by hgigas** [comment]
`echo [(ansi -o '0') 'some title' (char bel)] | str collect` not working (not changing terminal title). Nushell version 0.66.3, terminals: Alacritty, xterm, gnome-terminal...

**Comment by fdncred** [comment]
if you have `shell_integration: true` in your config.nu the title is set automatically now.

**Comment by hgigas** [comment]
Thanks a lot.

With `shell_integration: true`... is it possible to set tittle with current command? for example running vi to open config.nu and terminal title set automatically to `~/.config/nushell>vi config.nu`

**Comment by fdncred** [comment]
No, that's not possible right now. I could see having that configurable though if someone wanted to submit a PR. For instance, we could have a setting like `window_title_format: %S:%P:%L` where `%S` may be short_home, `$P` may be program_name, `$L` could be long_home, or some such abbreviated things.

**Comment by hgigas** [comment]
Maybe without `shell_integration` but with environment variable, similar to `BASH_COMMAND`.

`$"(ansi title)$nu or env...(ansi st)"

Is there something like `BASH_COMMAND` in Nushell?

**Comment by fdncred** [comment]
I have no idea what BASH_COMMAND is so probably not. :)

**Comment by hgigas** [comment]
`BASH_COMMAND` stores current command in Bash. For example:

```
$ echo $BASH_COMMAND
echo $BASH_COMMAND
```
How to get current running command in Nushell?

**Comment by fdncred** [comment]
The only way to get the last command is to look in the history.

**Comment by hgigas** [comment]
Done. Thank you very much.

Terminal title with path and running command. config.nu:
```
  shell_integration: false
...
  hooks: {
...
    pre_execution: [{
      print $"(ansi title)(pwd)> (history | last 1 | get 0 | get command)(ansi st)"
    }]
```

**Comment by laikq** [comment]
In case someone else finds this helpful: Now you can use `commandline` to get the current command in `pre_execution`, see #8207

**Comment by grey4owl** [comment]
I cam up with this most accurate and responsive solution with help of environment variables:

`~/.config/nushell/config.nu`
```rust
shell_integration: false
....
hooks: {
    pre_prompt: [{ 
        if "LAST_CMD" in $env {
            print $"(ansi title)(pwd | str replace "/home" "~") > ($env.LAST_CMD)(ansi st)"
        } else {
            print $"(ansi title)(pwd | str replace "/home" "~")(ansi st)"
        }
    }] 
    pre_execution: [{ 
        $env.LAST_CMD = (commandline)
    }] 
    .
    .
    .
}
```
output: `~/username > last_cmd`

**Comment by fdncred** [comment]
clever.

Here's the macos version of the pre_prompt hook
```nushell
    pre_prompt: [{||
      if "LAST_CMD" in $env {
        print $"(ansi title)(pwd | str replace "/Users/username" "~") > ($env.LAST_CMD)(ansi st)"
      } else {
        print $"(ansi title)(pwd | str replace "/Users/username" "~")(ansi st)"
      }
    }]
```

**Comment by grey4owl** [comment]
@fdncred Cool, the only thing missing is the `print -n` flag for not inserting newline that i forgot to add..

**Comment by jbarnat** [comment]
Ubuntu 24.04.4
alacritty 0.13.2
nushell 0.111.0

```nushell
$env.config = {
  shell_integration: {
    osc2: false 
  }
}
def set_window_title [t: string] {
    # @see https://en.wikipedia.org/wiki/ANSI_escape_code#C0_control_codes

    let oscSeqence = (
      0x[1b 5d 30 3b]
      | append ($t | into binary)
      | append 0x[07]
    )
    $oscSeqence | save --raw --force (tty)
}
```
