### ISSUE TITLE
pwd command crashes nushell on windows

### ISSUE THREAD

**Issue by AsafMah** [nushell/nushell#2528]
**Describe the bug**
Using the latest version on nu on windows 10, the pwd command crashes the program

**To Reproduce**
```
C:\Users> pwd
C:\Users
Error: Io(Os { code: 87, kind: InvalidInput, message: "The parameter is incorrect." })
```
And then it crashes

**Configuration (please complete the following information):**
 - OS (e.g. Windows): windows 10
 - Nu version (you can use the `version` command to find out):  19.0

**Comment by fdncred** [comment]
@AsafMah This is strange. I've seen that error before but I'm not sure where it's coming from. 

I built from main this morning and `pwd` seems to be working for me on Windows. This is my version informatin.

|version|commit_hash|features|
|-|-|-|
|0.19.0|e9bb4f25eb22d527af2943e9b159e7026f9c8b1e|default, clipboard, trash|

**Comment by jonathandturner** [comment]
Should hopefully be fixed by https://github.com/nushell/nushell/pull/2565. If it's not, please reopen so we can investigate further.
