### ISSUE TITLE
autoview crashes nushell when receiving data from `to json`, `to html`, or `to yaml`

### ISSUE THREAD

**Issue by TrevorAC99** [nushell/nushell#2532]
When `to json`, `to html`, or `to yaml` pipe their result into `autoview` explicitly or implicitly, it prints out the expected text and then prints out `Error: Io(Os { code: 87, kind: InvalidInput, message: "The parameter is incorrect." })` before crashing nushell.

**To Reproduce**
1. run `ls | to json`, `ls | to html`, or `ls | to yaml` with or without adding `| autoview` 

**Expected behavior**
I would expect that the JSON, HTML, or YAML be printed to stdout and then the shell would be ready to accept the next command.

**Configuration (please complete the following information):**
 - OS: Windows
 - Nu version: 0.19.0
 - Optional features (if any): None

Saving the result of `to` to a file works as expected, so running `ls | where type == File | select name size modified | to json --pretty 2 | save -r ./test.json` correctly sends the json to the file. Running that same command without the `| save -r ./test.json` on the end causes the error. This is easier to observe when starting another shell and running `nu` from within that shell so the crash doesn't immediately close the window.

Edit: I forgot to note that I was running `nu` in Windows Terminal

**Comment by fdncred** [comment]
Related to #2528, #2401, #2440, maybe others

**Comment by jonathandturner** [comment]
Should hopefully be fixed by https://github.com/nushell/nushell/pull/2565. If it's not, please reopen so we can investigate further.
