### ISSUE TITLE
Support alternative integer shapes, such as binary and hexadecimal

### ISSUE THREAD

**Issue by EmNudge** [nushell/nushell#2536]
**Is your feature request related to a problem? Please describe.**
I've gotten in the habit of using the Chrome console for binary and hexadecimal math using bitwise operators. It's nice, but having this possible in the terminal would be a nice QOL feature.
Atm `0b101011` and `0xffa3b` both are interpreted as strings. 

**Describe the solution you'd like**
It would be fantastic to be able to express numbers using other "literal" formats, like what is possible in most modern programming languages. The `=` command should be able to parse `0b101011` and `0xffa3b` as numbers. 
Having the `to` command also support "binary", "hexadecimal", and "octal" would be nice as well.

**Describe alternatives you've considered**
Since the only context I would personally use this is with the `=` command, this could also be made instead into another package. I'd want bitwise operators eventually, but those require the `|` symbol, which is already in use. For that, a separate plugin that supports bitwise operators might be preferable.

**Additional context**
N/A

**Comment by rezural** [comment]
Probably relevent:

https://github.com/rust-lang/rfcs/issues/1098

**Comment by rezural** [comment]
Could do some matching in the first (2 & perhaps one character), and fall through to base10 if it is not 0x,0o, etc. (whatever rust's naming scheme is?
