### ISSUE TITLE
Can't paste via keyboard under Windows

### ISSUE THREAD

**Issue by ndarilek** [nushell/nushell#2537]
Recently switched to Windows and decided to give Nu a shot there. The biggest issue is that I'm unable to paste in text via the keyboard. Neither Ctrl-V nor Ctrl-Shift-V works.

Am I missing something?

**Comment by jonathandturner** [comment]
Are you running Nu inside of cmd or Windows Terminal? You should be able to use the paste that comes with either of those. If you can't, that's something we should look into.

**Comment by fdncred** [comment]
Traditionally `cmd.exe` allows you to paste via right click if you have it configured as such via the properties dialog. Here's a [link that explains this](https://www.howtogeek.com/howto/25590/how-to-enable-ctrlv-for-pasting-in-the-windows-command-prompt/). 

With `Windows Terminal`, out of the box, Ctrl-C copy, Ctrl-V paste work. I can't remember what Ctrl-Shift-V does off the top of my head. Documentation for keybindings on Windows Terminal [is here](https://docs.microsoft.com/en-us/windows/terminal/customize-settings/key-bindings.).

**Comment by ndarilek** [comment]
So if I press Win-r, type nu, then press either Ctrl-V or Ctrl-Shift-V 
with something in my clipboard, nothing pastes. Likewise if I run nu 
from within cmd, not sure if that should make a difference.


I'm a blind screen reader user, so while right-clicking may in fact 
paste, that requires me to pick up my mouse, make sure it's on, etc. 
Those aren't huge blockers as such, but the mouse isn't a tool I 
generally use, so it definitely makes pasting less convenient.


Anyhow, not sure if there's something else I might try. I just jumped 
ship from Linux to Windows a couple weeks ago and am using Nu to have 
something more sane than cmd, so if there's something else I might try 
then please do let me know.


Thanks!

**Comment by jonathandturner** [comment]
@ndarilek - totally understood, and thanks for explaining. Where we are right now, Nu will need to run under cmd or Windows Terminal. When you run it directly, it'll likely pick one of those and run it inside of that.

In the future, we'd like to make Nu more standalone, so that it's able to be used directly. This should help work around any of these issues. Once we do make the transition to being more standalone, I'd love to make sure that it's accessible for screen readers, too.

That's still a ways out, but somewhere we hope to go with Nu.

**Comment by fdncred** [comment]
This is what you need to do.
1. Type Win-R to run nu.exe
2. Type Alt-Space to show this menu. It's also available by clicking the icon in the top left of the window.
![image](https://user-images.githubusercontent.com/343840/92990975-0393fc80-f4a6-11ea-819d-e8b28d979972.png)
3. Type P to select and activate the Properties Window which looks like this.
![image](https://user-images.githubusercontent.com/343840/92991000-3211d780-f4a6-11ea-89e1-df6bfbc93692.png)
4. From here you can enable the copy and paste keys in the Edit Options group box. I'd enable them all with the Q, I, k, F, C keys.
5. There are also settings in the other tabs.

However, my recommendation to you is to install Windows Terminal and run cmd.exe, powershell.exe, pwsh.exe, nu.exe, wsl, all from inside of a tab in Windows Terminal. You can install Windows Terminal from the [Microsoft App Store](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab) or from [Github](https://github.com/microsoft/terminal/releases).

Good Luck!

**Comment by fdncred** [comment]
@ndarilek Were you able to follow the procedure above I outlined?

**Comment by ndarilek** [comment]
Sorry, was away for the weekend.

But yeah, some combination of a) first running cmd and b) changing settings got paste working. For some reason, cmd lets me paste fine with Ctrl-v, so I assumed an issue on Nu's part.

Thanks for the clarification.
