### ISSUE TITLE
Ctrl-D exits nushell, not current shell

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#2545]
**Describe the bug**
Ctrl-D exits the nushell process instead of the current shell.

**To Reproduce**
1. `enter help`
2. Press Ctrl-D

**Expected behavior**
I would expect Ctrl-D to mimic the `exit` command and just exit the help shell, returning to the filesystem shell. Although the current behaviour is totally reasonable, I found it quite surprising.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): macOS 10.15.6
 - Nu version (you can use the `version` command to find out): 0.19 @ 0178b532893a0d06095a109586aa7444efd3ec57
 - Optional features (if any): default

**Comment by jonathandturner** [comment]
In theory, this should be detect-able. I *think* this is the area that you'd change:

https://github.com/nushell/nushell/blob/main/crates/nu-cli/src/cli.rs#L528-L530
