### ISSUE TITLE
Sleep command cannot be cancelled with Ctrl+C

### ISSUE THREAD

**Issue by radekvit** [nushell/nushell#2546]
**Describe the bug**
The built-in sleep command cannot be stopped immediately by pressing Ctrl+C

**To Reproduce**
1. run `sleep 15sec`
2. Press Ctrl+C

**Expected behavior**
The `sleep` command immediately ends after pressing Ctrl+C

**Configuration (please complete the following information):**
 - OS (e.g. Windows): WSL2, Windows
 - Nu version (you can use the `version` command to find out): 19.0
 - Optional features (if any): 

`echo 1..100000000000000` can be stopped this way, so at least some built-in commands behave correctly.

**Comment by thegedge** [comment]
An async version would probably be good, but I think for now we can just switch from a simple `thread::sleep`, to something like this (pseudo-rust):

```rust
let deadline = now + sleep duration;
while now < deadline {
    if ctrl_c.load(Ordering::SeqCst) {
        break;
    }

    thread::sleep(small_duration)
}
```

**Comment by radekvit** [comment]
@thegedge 
I actually tried to implement this using a future (https://rust-lang.github.io/async-book/02_execution is pretty much exactly it), but that didn't help either. My knowledge of futures is quite limited, so I may be just missing something there.

Also I'm not familiar with how nu handles Ctrl+C, there may be an issue there.

**Comment by thegedge** [comment]
> I actually tried to implement this using a future (rust-lang.github.io/async-book/02_execution is pretty much exactly it), but that didn't help either. My knowledge of futures is quite limited, so I may be just missing something there.

If you want to take a shot at implementing a custom `Future`, go for it. I think we'll eventually choose a runtime to work with (like `smol`, `tokio`, or `async-std`), which will typically already have such a thing, but we haven't committed to one of those yet.

> Also I'm not familiar with how nu handles Ctrl+C, there may be an issue there.

We just use a shared `AtomicBool`. It's the `ctrl_c` I showed above. You can access it via `CommandArgs` (`args.ctrl_c`), which the sleep command should be receiving.

Let me know if that helps you make some more progress 🙂

**Comment by radekvit** [comment]
@thegedge I believe I have it. Turns out that a built-in Future from something like `tokio` or `async-std` wouldn't have worked anyways, since we have to check `ctrl_c` manually to return the result early.

Your pointers helped a ton, thank you.

**Comment by thegedge** [comment]
> wouldn't have worked anyways, since we have to check ctrl_c manually to return the result early.

Ah yes, you're totally right. In that case, we can eventually generalize the pattern you have here, similar to what I did with [`InterruptibleStream`](https://github.com/nushell/nushell/blob/main/crates/nu-cli/src/stream/interruptible.rs).

Even better, we should think about how we could handle Ctrl-C without having to have every command think about it. So many improvements we can make 🙈

**Comment by thegedge** [comment]
Fixed by https://github.com/nushell/nushell/pull/2550
