### ISSUE TITLE
direnv support

### ISSUE THREAD

**Issue by Parasrah** [nushell/nushell#2549]
**Is your feature request related to a problem? Please describe.**

I use `direnv` in conjunction with `nix-direnv` for my development environments, so that my environment (and packages/dependencies) will automatically be loaded/unloaded as I enter the directory. To my knowledge I can't get this behaviour using the `direnv` replacement that ships with `nushell`

**Describe the solution you'd like**

I'd rather see a shell take advantage of well established tools like `direnv` and work to integrate with them rather than developing their own competing solution

**Describe alternatives you've considered**

An alternative solution is to support both your built-in replacement and `direnv`, which would be potentially a lot of work for little gain

**Additional context**

Just want to clarify I'm fine if nothing comes of this and you decide the `nix` integration isn't compelling enough to support, and I don't have expectations. These are just my opinions and I figured I'd share them in case you found it valuable. I really respect what you guys are doing here, and I think there are so many great things about `nushell`

Also if you haven't tried out `direnv+nix` before, I would highly recommend doing so, it's awesome

**Comment by thegedge** [comment]
I think this is both a nushell issue and a `direnv` issue.

First, in `nushell`
1. hooking mechanism, and
2. a means to export env vars to the process.

We want to these regardless of `direnv`.

Once those things are available in `nushell`, `direnv` will need to be able to support a nushell-compatible hook and export.

> I'd rather see a shell take advantage of well established tools like direnv and work to integrate with them rather than developing their own competing solution

I think normally we'd try to do this. I'm all for not building something new until there's a good reason to do so.

We've built it into the shell for now though, because we don't have an easy way to hook into nushell. Once we have an easy way to do that, it could make sense to push this behaviour to external tools 🙂

**Comment by Parasrah** [comment]
Okay that makes total sense, I'm guessing this ties into the same issues blocking `fzf` support right now? In any case thanks so much for the clarification on this, I'm really excited about `nushell` and think you are all doing a great job. Even though I don't use it as my daily driver yet, I still find myself running it a couple times a day to solve little things that would be so much harder in bash

**Comment by jgelens** [comment]
A temporary workaround for now:
``` direnv export json | from json | to toml | echo "[env]" $(char newline) $it | save .nu-env```

**Comment by dysinger** [comment]
> A temporary workaround for now:
> ` direnv export json | from json | to toml | echo "[env]" $(char newline) $it | save .nu-env`

This doesn't work with nu 0.24.1 I get
```
> direnv export json | from json | to toml | echo "[env]" $(char newline) $it | save .nu-env
direnv: loading ~/src/scarf-sh/repo/.envrc
direnv: loading /nix/store/a5djjcqhnm580c6rss0nvn3nkk9pva08-dev-env/.profile
direnv: export +KUBECONFIG +SCARF_ROOT ~NIX_PATH ~PATH
error: Variable not in scope
  ┌─ shell:1:73
  │
1 │ direnv export json | from json | to toml | echo "[env]" $(char newline) $it | save .nu-env
  │                                                                         ^^^ missing '$it' (note: $it is only available inside of a block)

```

**Comment by dysinger** [comment]
also

```
/home/tim> echo $(character newline)
error: Command not found
  ┌─ shell:1:8
  │
1 │ echo $(character newline)
  │        ^^^^^^^^^ command not found

```

**Comment by jgelens** [comment]
> > A temporary workaround for now:
> > ` direnv export json | from json | to toml | echo "[env]" $(char newline) $it | save .nu-env`
> 
> This doesn't work with nu 0.24.1 I get
> 
> ```
> > direnv export json | from json | to toml | echo "[env]" $(char newline) $it | save .nu-env
> direnv: loading .....
> error: Variable not in scope
>   ┌─ shell:1:73
>   │
> 1 │ direnv export json | from json | to toml | echo "[env]" $(char newline) $it | save .nu-env
>   │                                                                         ^^^ missing '$it' (note: $it is only available inside of a block)
> ```

Just wrap the `echo` in an `each` block.

**Comment by dysinger** [comment]
that worked great. for others:

```
direnv export json | from json | to toml | each { echo "[env]" $(char newline) $it } | save .nu-env
```

**Comment by Parasrah** [comment]
I would still like to see an official integration when the blockers are resolved

**Comment by bbhoss** [comment]
in case any other n00bs find this, the command is now:
` direnv export json | from json | to toml | each { echo "[env]" (char newline) $it } | save .nu-env`

**Comment by thomasaarholt** [comment]
If you're getting a `input cannot be parsed as JSON`, then the above command should be changed to `direnv exec / direnv export json | from json | to toml | each { echo "[env]" (char newline) $it } | save .nu-env`. See this [direnv comment](https://github.com/direnv/direnv/issues/809#issuecomment-869042674) for a bit more info.

**Comment by AmandaCameron** [comment]
So an update on this, from my personal config.nu: 

I now have
```nu
def-env load-direnv [] {
  direnv export elvish | from json | load-env
}
```

-- As an experiment, when NixOS updated to 0.63, I decided to give the hooks a try, with the following: 

```nu
  hooks: {
    env_change: {
       PWD: [{|before, after|
         let e = (direnv export elvish | from json)
         if ($e | length) == 1 {
           $e | load-env
         }
      }]
    }
```

However, it seems that the hooks can't effect the surrounding environment, like a def-env can.

So for this to be fully working in the future, and I assume for direnv to add support for it, it would require the hooks to be able to edit the environment.

I also tried the `pre_prompt` hook, and that didn't work either.

**Comment by johnae** [comment]
@AmandaCameron etc. Just linking to my comment on how it's now possible to use direnv as far as I can tell. See my comment here https://github.com/nushell/nushell/pull/5982#issuecomment-1207170350

**Comment by johnae** [comment]
I'll just repost the working code here (requires version 0.66) since other similar code was that is specifically related to direnv support:

```
env_change: {
      PWD: [{
        code: "let e = (direnv export json | from json)\nlet newenv = if ($e | length) == 1 { $e } else { {} }\n$newenv | load-env"
      }]
    }
```

Afaiu you can't run load-env in a block and have it affect the environment, that's the reason for the let x = if.

**Comment by kubouch** [comment]
@johnae If you want, you can share this code to https://github.com/nushell/nu_scripts or contribute it to https://www.nushell.sh/cookbook. It's always good to document working use cases.

I'll close this issue then, it should be possible to load / unload environment variables when changing directory.

**Comment by johnae** [comment]
I've created a PR with an example setup here: https://github.com/nushell/nu_scripts/pull/272

**Comment by johnae** [comment]
Also contributed a PR to the cookbook: https://github.com/nushell/nushell.github.io/pull/554

**Comment by noahfraiture** [comment]
> Also contributed a PR to the cookbook: [nushell/nushell.github.io#554](https://github.com/nushell/nushell.github.io/pull/554)

Hey, do you know if it's possible to reduce the verbosity ? Having all the exported variable is impossible
