### ISSUE TITLE
Cannot `cd ~/` on Mac OS

### ISSUE THREAD

**Issue by ryanpcmcquen** [nushell/nushell#2552]
**Describe the bug**
I see that `~` expands with `ls`, but not with `cd`.

**To Reproduce**
1. Type `cd ~/Lib`.
2. Press <kbd>Tab</kbd>.
3. It should expand to `~/Library`, but it does not with the `cd` command.

**Expected behavior**
I would expect `cd ~/Lib` to become `cd ~/Library/` with tab completion.

**Screenshots**
![tilde_not_expanding_with_cd](https://user-images.githubusercontent.com/772937/93252098-e4b59480-f749-11ea-87e0-f9330e55027f.gif)

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Mac OS 10.15.x
 - Nu version (you can use the `version` command to find out): 0.19.0
 - Optional features (if any): Installed from Homebrew.

**Comment by thegedge** [comment]
This was my bad. Rushed some of the new completion engine into 0.19.0, but it had a few bugs. https://github.com/nushell/nushell/pull/2525 fixed this issue (reopen if that's not the case).

**Comment by ryanpcmcquen** [comment]
Thank you @thegedge!
