### ISSUE TITLE
`help commands` include subcommands

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#2561]
**Is your feature request related to a problem? Please describe.**
`help commands` only shows the toplevel commands. There's no easy way to also enumerate the subcommands.

**Describe the solution you'd like**
Some ideas:

**Idea 1**
`help commands` would also show subcommands, all under the existing `name` column.

**Idea 2**
`help commands` would also show subcommands, but in another column:

| command | subcommand | description |
|-|-|-|
| ... | ... | ... |
| str | | description |
| str | camel-case | description |
| str | capitalize | description |
| ... | ... | ... |
|-|-|-|

**Idea 3**
`help commands` shows the root commands, but also includes a column stating whether or not a command has subcommands. `help commands --with-subcommands` would show all commands.

**Comment by coolshaurya** [comment]
I think it's a good idea to use nested tables for this. So `help commands` would have a `subcommands` column that has a table with all the subcommands in it with name and description like -

|name|description|subcommands|
|-|-|-|
|a|Description of command a||
|b|Description of command b|[table 2 rows]|
|c|Description of command c||
|d|Description of command d||
|e|Description of command e||

and then if you `get` the subcommands column of a particular command ( by doing something like `help commands | where name == b | get subcommands`) then you'd get something like - 

|name|description|
|-|-|
|b|Description of command b|
|b x|Description of command b x|
|b y|Description of command b y|
|b z|Description of command b z|
