### ISSUE TITLE
Have `str trim` apply to all relevant columns when none supplied

### ISSUE THREAD

**Issue by thegedge** [nushell/nushell#2564]
**Is your feature request related to a problem? Please describe.**
We decided to have a single trim function in https://github.com/nushell/nushell/issues/2382. What I didn't realize was that `trim` had slightly different behaviour than `str trim`: it will trim ALL columns by default.

**Describe the solution you'd like**
Have `str trim`, without any arguments, trim all columns with `String` / `Line` values.

**Current behaviour:**
```
> echo '[{"a": " b ", "b": "   c"},{"a": " 1 ", "b": "   2   "}]' | from json | str trim
error: value is not string
  ┌─ shell:1:67
  │
1 │ echo '[{"a": " b ", "b": "   c"},{"a": " 1 ", "b": "   2   "}]' | from json | str trim
  │                                                                   ^^^^^^^^^ got row
```

**Desired behaviour**
```
> echo '[{"a": " b ", "b": "   c"},{"a": " 1 ", "b": "   2   "}]' | from json
───┬───┬───
 # │ a │ b
───┼───┼───
 0 │ b │ c
 1 │ 1 │ 2
───┴───┴───
```

**Comment by jonathandturner** [comment]
Looks like this works now
