### ISSUE TITLE
Implement a way to identify commands as internal only

### ISSUE THREAD

**Issue by gillespiecd** [nushell/nushell#2567]
There are some helper commands like `run_external` that are internal only meaning they aren't meant to be executed by end users. It would be helpful to have a way to identify and possibly filter out these commands from outputs such as `help commands`.

One option is to create a new default function on the `WholeStreamCommand` trait (e.g. `is_internal`) and then update internal commands to overwrite it as true. There may also be a better way to do this.

**Comment by jonathandturner** [comment]
@gillespiecd that sounds like a good place to put it.
