### ISSUE TITLE
time ls -d don't work correctly

### ISSUE THREAD

**Issue by Mart-Bogdan** [nushell/nushell#2568]
**Describe the bug**

**To Reproduce**
1. type `time ls -d`
2. runs zero seconds and outputs " . " 

**Expected behavior**
Display list of all files and dirs with sizes and execution time

it's seems to work with `time ls`  but looking on output it's using /bin/ls, not built in command

**Screenshots**
![image](https://user-images.githubusercontent.com/775038/93580500-90f4b680-f9a8-11ea-95b2-0e703b818fd2.png)

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Linux Kernel 4.15.0-117-generic; Ubuntu 18.04.5 LTS
 - Nu version (you can use the `version` command to find out): Nushell 0.19.0

**Comment by radekvit** [comment]
@jonathandturner 
Do we currently have a way to run a `Block` from an internal command?

I would like to make a `time` internal command, and I'm trying to figure out how much effort it would take.
If we do that, we could make `time` more nushell-y.

**Comment by fdncred** [comment]
Have you tried the `benchmark` command? i.e. `benchmark {ls -d}`?

**Comment by Mart-Bogdan** [comment]
@fdncred it works:
```
/home/winnie> benchmark { ls -d }
30sec 315ms 768us 405ns
```

So time is just call to platform executable ?

sadly that benchmark do not measure sys time.

**Comment by fdncred** [comment]
@Mart-Bogdan yes, I think `time` is the platform time command.

**Comment by thegedge** [comment]
@Mart-Bogdan we could look into expanding benchmark to include sys/user/cpu timings, as long as we can do so in a cross-platform manner 🙂

Note, `time ls -d` works as expected though. `time` in nushell is likely running `/usr/bin/time`, so we're in the world of "externals" (as nushell calls them). That means `ls -d` is the _external_ `ls`. You can run `^ls -d` to see that it just emits a dot. In any other shell, try `/bin/ls -d`. Here's what I get:

```
> /bin/ls -d
.
```

**Comment by Mart-Bogdan** [comment]
Nice, didn't know about ^ [(command escaping)](https://www.nushell.sh/book/en/escaping.html) and about **benchmark**

Does the benchmark covered somewhere in the book?

**Comment by Mart-Bogdan** [comment]
![image](https://user-images.githubusercontent.com/775038/93687250-cc84a300-fac4-11ea-9d7e-291f87993fa5.png)
It works, thanks!

**Comment by Mart-Bogdan** [comment]
I'm wondering what is idle time?

**Comment by radekvit** [comment]
> I'm wondering what is idle time?

@Mart-Bogdan It is the total available CPU time during execution, for all cores.

For example, if you have 2 CPU cores and 1 of them worked at 50% during your task, and the other at 0%, you will get 1sec real time, 0.5sec user time and 1.5sec idle time.
