### ISSUE TITLE
Rich clipboard support

### ISSUE THREAD

**Issue by tiffany352** [nushell/nushell#2572]
**Is your feature request related to a problem? Please describe.**
I want to clip NuShell table output in a way that I can easily paste it into Google Sheets, Confluence, etc.

**Describe the solution you'd like**
```
❯ open fonts.csv | clip
error: Given non-string data
  ┌─ shell:1:18
  │
1 │ open fonts.csv | clip
  │                  ^^^^ expected strings from pipeline
```
Make it so when you pass a table to clip it automatically fills the clipboard with relevant MIME types.

For example, if I copy some cells from Google Sheets and put it into [this clipboard inspector tool](https://evercoder.github.io/clipboard-inspector/), I see this:

![image](https://user-images.githubusercontent.com/1254344/93648290-49c5f000-f9bf-11ea-9905-dea3dffbd2f0.png)

But if I use the clip command, I end up with this:

```
❯ open fonts.csv | to html | clip
```
![image](https://user-images.githubusercontent.com/1254344/93648330-6104dd80-f9bf-11ea-9cda-e334d9aa156a.png)

And pasting it into other apps just pastes it as plain text.

**Describe alternatives you've considered**
An option to set the mime type as a flag on the clip command maybe.

**Additional context**
My current "workflow" (please break it) is to save to a .csv file, then open Google Sheets and import it as a CSV, then copy the cells from Google Sheets and paste them into other apps (Confluence, etc.). Now that I think about it I can probably streamline it a bit if I install LibreOffice or something, but that's what I have currently.

**Comment by jonathandturner** [comment]
For people looking into this - I'm not sure which clipboard crates support richer input, but this would be a cool feature if we can find one that supports it. When I originally implemented `clip` I just grabbed the first one I saw without looking for rich copy/paste support. Should be okay to swap them out if we can keep it generally cross-platform.
