### ISSUE TITLE
Inc with flags seems to only work if you pass a field

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#258]

**Comment by androbtech** [comment]
`ls | get size | inc` seems to work fine.

Can you type an example?

**Comment by jonathandturner** [comment]
`open Cargo.toml | get package.version | inc --minor` doesn't work for me. I get:

![Screenshot from 2019-08-08 13-13-35](https://user-images.githubusercontent.com/547158/62668039-6337f280-b9de-11e9-975b-4ca92ddf8c1e.png)

**Comment by androbtech** [comment]
Confirmed.

`open Cargo.toml | get package | get version | inc => works`
`open Cargo.toml | get package | get version | inc --minor => same error as yours`
`open Cargo.toml | get package.version | inc --minor => same error`
