### ISSUE TITLE
Implement from / to JWT commands

### ISSUE THREAD

**Issue by Delapouite** [nushell/nushell#2589]
**Is your feature request related to a problem? Please describe.**
JSON Web Token https://tools.ietf.org/html/rfc7519 is one the popular format to exchange authorization or authentication data in protocols like OAuth or OpenID Connect. At first, the token is not supposed to be interpreted by a human, but inspecting its content is often useful to debug and confirm info like the issuer, the expiration date…

**Describe the solution you'd like**
A new pairs of `from` / `to` command that will be able to nicely displays a table with the fields from the JWT header, and the various claims it contains like `iss`, `sub`… in columns.

**Describe alternatives you've considered**
A CLI written in rust exists to decode / encode JWT: https://github.com/mike-engel/jwt-cli

**Additional context**
A similar issue is related to the support of X.509 certificates https://github.com/nushell/nushell/issues/1889

**Comment by Delapouite** [comment]
Hello bot

**Comment by johnae** [comment]
Now that Nushell is programmable, an example implementation of this could be (provided you have jwt-cli installed):

```nuon
def "from jwt" [] {
∙   jwt decode --json - | from json | flatten
∙ }
```

**Comment by j-xella** [comment]
And this seems to be a pure nushell implementation. Equivalent of `jc --jwt --pretty | from json`, tested on nu 0.97.1, but should work with some older versions too:

```nu
# Pipe JWT in, something like 
# "eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiSm9lIENvZGVyIn0.5dlp7GmziL2QS06sZgK4mtaqv0_xX4oFUuTDh1zHK4U" |
split row . | do { {
  header:    ($in.0 | decode base64 -c url-safe-no-padding | from json )
  payload:   ($in.1 | decode base64 -c url-safe-no-padding | from json )
  signature: ($in.2 | decode base64 -c url-safe-no-padding -b )
} }
```

**Comment by j-xella** [comment]
> ```nushell
> $in * 1_000_000_000 | into datetime
> ```

Interesting way of converting Unix time stamp into datetime :)  I went with

```nushell
into datetime -f %s
```

**Comment by sbrow** [comment]
@j-xella I was just hacking stuff together :sweat_smile:, didn't realize there was a proper solution for it.

**Comment by sbrow** [comment]
I am stumped, as this no longer works.

```bash
export def "from jwt" []: string -> record {
  (
    split row .
    | {
      header:    ($in.0 | decode base64 --url --nopad | into string | from json )
      payload:   ($in.1 | decode base64 --url --nopad | into string | from json )
      signature: ($in.2 | decode base64 --url --nopad)
    }
    | convert-datetime 'exp'
    | convert-datetime 'iat'
    | convert-datetime 'nbf'
  )
}
```

Output
```bash
Error: nu::shell::cant_convert

  × Can't convert to string.
   ╭─[/home/<redacted>/jwt.nu:5:57]
 4 │     | {
 5 │       header:    ($in.0 | decode base64 --url --nopad | into string | from json )
   ·                                                         ─────┬─────
   ·                                                              ╰── can't convert binary to string
 6 │       payload:   ($in.1 | decode base64 --url --nopad | into string | from json )
   ╰────
  help: try using the `decode` command
```

Even though `into string` *claims* that it accepts binary as input.

```bash
> into string -h
Convert value to string.

Search terms: convert, text

Usage:
  > into string {flags} ...(rest)

Flags:
  -h, --help: Display the help message for this command
  -d, --decimals <int>: decimal digits to which to round

Parameters:
  ...rest <cell-path>: For a data structure input, convert data at the given cell paths.

Input/output types:
  ╭────┬───────────┬──────────────╮
  │  # │   input   │    output    │
  ├────┼───────────┼──────────────┤
  │  0 │ binary    │ string       │
  │  1 │ int       │ string       │
  │  2 │ number    │ string       │
  │  3 │ string    │ string       │
  │  4 │ glob      │ string       │
  │  5 │ bool      │ string       │
  │  6 │ filesize  │ string       │
  │  7 │ date      │ string       │
  │  8 │ duration  │ string       │
  │  9 │ list<any> │ list<string> │
  │ 10 │ table     │ table        │
  │ 11 │ record    │ record       │
  ╰────┴───────────┴──────────────╯
```

**Comment by weirdan** [comment]
@sbrow replace the `into string` part with `decode` (shorthand for `decode utf-8`) and it'll work:

```nushell
header:    ($in.0 | decode base64 --url --nopad | decode | from json )
```
