### ISSUE TITLE
Table literals with nested tables incorrectly parse header as separate rows

### ISSUE THREAD

**Issue by tikue** [nushell/nushell#2592]
**To Reproduce**
```
> echo [[line_editor]; [[edit_mode max_history_size]; [vi 100]]] | get line_editor
───┬──────────────────
 0 │ edit_mode
 1 │ max_history_size
───┴──────────────────
```

**Expected behavior**
```
> echo [[line_editor]; [[edit_mode max_history_size]; [vi 100]]] | get line_editor
───┬───────────┬──────────────────
 # │ edit_mode │ max_history_size
───┼───────────┼──────────────────
 0 │ vi        │           100000
───┴───────────┴──────────────────
```

**Configuration**
 - OS: Mac
 - Nu version: 0.20.0
 - Optional features: none

**Comment by thegedge** [comment]
So what's interesting here is that I would have expected an error for what you describe. To expand what this looks like from a table literal perspective:

```
[
  [line_editor];
  [
    [edit_mode max_history_size]; [vi 100]
  ]
]
```

Notice how the first row is `[edit_mode max_history_size]; [vi 100]`, which isn't a valid literal. When you add one more set of square brackets, you get close to what one would expect:

```
> echo [ [line_editor] ; [ [[edit_mode max_history_size] ; [vi 100]] ] ]
───┬────────────────
 # │  line_editor
───┼────────────────
 0 │ [table 1 rows]
───┴────────────────
> echo [ [line_editor] ; [ [[edit_mode max_history_size] ; [vi 100]]] ]  | get line_editor
───┬───────────┬──────────────────
 # │ edit_mode │ max_history_size
───┼───────────┼──────────────────
 0 │ vi        │              100
───┴───────────┴──────────────────
```

The second part is correct, but it's impossible to get the first part to be:

```
───┬──────────────────────────────────
 # │           line_editor
───┼──────────────────────────────────
 0 │ [row edit_mode max_history_size]
───┴──────────────────────────────────
```

In JSON land, it's the difference between these two:

1. `{"a": {"b": 1}}`
2. `{"a": [{"b": 1}]}`

Currently our literals will construct the latter, and there's no way to construct the former (as far as I can tell).

I can see a couple of issues here:

1. How can we represent a nested table, like in (1) above?
2. An error message for what @tikue originally described.

**Comment by jonathandturner** [comment]
When you add the extra `[]` to the table in the cell, it seems to currently parse correctly. Following @thegedge's reasoning, it should error without (which it appears to do with recent versions) and it works when wrapped with `[]`. Closing, but if there are further improvements you see, please reopen.
