### ISSUE TITLE
`config.toml` path changed in 0.20.0

### ISSUE THREAD

**Issue by ryanpcmcquen** [nushell/nushell#2593]
**Describe the bug**
`config path` now points to: `"$HOME/Library/Application Support/org.nushell.nu/config.toml"`, in `0.19.0` and earlier it was: `"$HOME/Library/Preferences/org.nushell.nu/config.toml"`

**To Reproduce**
1. Upgrade from 0.19.0 or earlier to 0.20.0.
2. Notice that your config is gone.

**Expected behavior**
We should probably add this to breaking changes in the release notes for 0.20.0.

**Configuration (please complete the following information):**
 - OS: Mac OS 10.15.x
 - Nu version: 0.20.0

**Comment by jonathandturner** [comment]
I'll add this to the breaking changes. Sorry about that.

We've been trying to find a supported directories crate, but unfortunately most had been abandoned until more recently.

**Comment by ryanpcmcquen** [comment]
No worries, it was an easy fix!

**Comment by fdncred** [comment]
@ryanpcmcquen is it ok that we close this?

**Comment by ryanpcmcquen** [comment]
@fdncred, yep!
