### ISSUE TITLE
Unmatched parens or quotes begin continuation without indicator

### ISSUE THREAD

**Issue by mhmdanas** [nushell/nushell#2606]
**Describe the bug**
When `(`, `[`, `{`, `"`, ``, and `'` are unmatched with their counterparts, ~~Nu hangs~~ there's a continuation, but there's no indication of it at all.

**To Reproduce**
Many possible reproductions exists. Examples:
- `e(`
- `e (`
- `e ()(`
- `e (()`
- `e ))(`
- `e $(`
- `{)`

All bracket types and quote types produce the same behavior.

**Expected behavior**
~~Nu should report an error about unmatched quotes or brackets~~ There should be a clear indicator that this is not a hang and that this is just a continuation.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): macOS 10.15.6
 - Nu version (you can use the `version` command to find out): 0.20.0
 - Optional features (if any): none

~~As you can see in examples, you can use a nonexistent command or even not use a command, so this is probably a parsing issue.~~

~~May be~~ related to #2521.

**Comment by jonathandturner** [comment]
If you're in the CLI, this behavior is expected, though unfortunately rustyline (the crate we use for line editing) doesn't give you an indicator that it's expected.  The unclosed paren allows you to continue typing on the next line and finish with the ending paren.  For example, it will let you type:

```
do {
  echo "hello"
}
```

As three lines in the CLI.  I'd really like to rustyline to give us an indicator because as you point out, it's generally confusing to not know if nu is hung or just waiting for more input.

**Comment by mhmdanas** [comment]
First, thanks for the swift reply!

Second, yes, you're totally right. This is not actually a parsing issue like I thought. But as you say, there's no indication it's not a hang. Should I keep this issue open until it's clear this is not a hang?

**Comment by mhmdanas** [comment]
Actually, even #2521 is not a hang. This is a surprise.

**Comment by mhmdanas** [comment]
I was going to report another issue where repeated semicolons "hang" Nu, but now I see all my reports have pretty much the same cause. I apologize for the inconvenience.

**Comment by jonathandturner** [comment]
@mhmdanas - no worries at all. I wonder if we should just rename this issue to be "Unmatched parens being continuation without indicator" or something like that?  That way we can turn this into an ask of the rustyline folks.

**Comment by mhmdanas** [comment]
That sounds reasonable.

**Comment by fdncred** [comment]
we now have multi-line indicator in the latest main branch. closing this. please re-open if you think this is in error.
