### ISSUE TITLE
`select` for column names with spaces incorrectly keeps quote marks

### ISSUE THREAD

**Issue by azriel91** [nushell/nushell#2608]
**Describe the bug**

When using quote marks to select a column name that contains spaces, the `select` command includes the literal quotes as part of the column name.

This means when using an operation that references column names afterwards (e.g. `sort-by`), one has to include literal quotes.

```sh
# My intuition is that `sort-by` should be able to use "a name" instead of '"a name"'
❯ echo [["a name" "b"]; [3 4] [1 2]] | select "a name" "b" | sort-by '"a name"'
                                                                     ^________^ extra quotes :(
```

**To Reproduce**

1. Pipe a table with a multi word column name through `select`:

	```sh
	echo [["a name" "b"]; [3 4] [1 2]] | select "a name" "b"
	```

**Expected behavior**

The original column name is retained.

**Screenshots**

<details open>
<summary>Example</summary>

```sh
# Without select
❯ echo [["a name" "b"]; [3 4] [1 2]]
───┬────────┬───
 # │ a name │ b
───┼────────┼───
 0 │      3 │ 4
 1 │      1 │ 2
───┴────────┴───

# With select
❯ echo [["a name" "b"]; [3 4] [1 2]] | select "a name" "b"
───┬──────────┬───
 # │ "a name" │ b
───┼──────────┼───
 0 │        3 │ 4
 1 │        1 │ 2
───┴──────────┴───
```

</details>

**Configuration (please complete the following information):**
 - OS (e.g. Windows): OSX Darwin 19.6.0
 - Nu version (you can use the `version` command to find out): 0.20.0
 - Optional features (if any): `clipboard`, `trash` (used `cargo install nu --features=extra`)

**Comment by JonathanArns** [comment]
I am somewhat new to rust and nushell, but I would like to take a shot at this :)
