### ISSUE TITLE
mv allows moving a directory into itself

### ISSUE THREAD

**Issue by demilich1** [nushell/nushell#2612]
**Describe the bug**
The **mv** command allows to move a directory into a subdirectory of itself. At least there is no error message but the end result is that the directory is gone (deleted)

**To Reproduce**
```
mkdir a
mkdir a/b
mv a a/b
```

**Expected behavior**
I would expect an error message of some kind, i.e. the standard linux **mv** command outputs
`mv: cannot move 'a' to a subdirectory of itself, 'a/b/a'`

**Configuration (please complete the following information):**
 - OS: Tested on Windows
 - Nu version: nushell 0.20.0

**Comment by luccasmmg** [comment]
I would like to be assigned to this issue, if it is possible, will try to work on it tomorrow
