### ISSUE TITLE
display return status of external programs

### ISSUE THREAD

**Issue by jansol** [nushell/nushell#2615]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when an application crashes with a segmentation fault or such and my shell just drops me into the prompt without saying what happened.

**Describe the solution you'd like**
I'd prefer a short message saying why the application terminated before the prompt, like bash does.

**Comment by fdncred** [comment]
Do you mean like catching the return status of external programs?

**Comment by jansol** [comment]
Yes, that seems to be the way to handle this on *nix.

**Comment by jansol** [comment]
feature request still applies

**Comment by jansol** [comment]
Stil applies.

This issue should probably have the enhancement and polish tags.

**Comment by fdncred** [comment]
Agreed. Also, a dupe of #3970, #3185, #2733

**Comment by hustcer** [comment]
It works now on latest main, try `git status | complete`
So I will close this issue.
