### ISSUE TITLE
table output is vertical

### ISSUE THREAD

**Issue by gyakovlev** [nushell/nushell#2618]
**Describe the bug**
I've built it on ppc64le system ( after fixing https://github.com/alkis/decimal/issues/52 )
for some reason output in the tables is vertical.

**To Reproduce**
1. `nu`
2. `ls`

**Expected behavior**
I expect output to be horizontal.

**Screenshots**
![image](https://user-images.githubusercontent.com/168902/94690432-96250000-02dc-11eb-99cf-6b689c391401.png)

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Linux ppc64le
 - Nu version (you can use the `version` command to find out): 0.20.0
 - Optional features (if any): `--features extra`

otherwise, all tests seems to pass.

probably worth another bug: anything related to time crashes as
```
ya@hydra ~ $ RUST_BACKTRACE=full nu
Welcome to Nushell 0.20.0 (type 'help' for more info)
/home/ya> ls -l
thread 'main' panicked at 'No such local time', /var/tmp/portage/app-shells/nushell-0.20.0/work/cargo_home/gentoo/chrono-0.4.15/src/offset/mod.rs:173:34
stack backtrace:
   0:        0x10692be34 - <unknown>
   1:        0x106966e64 - <unknown>
   2:        0x10691f9ec - <unknown>
   3:        0x106913d84 - <unknown>
   4:        0x106913964 - <unknown>
   5:        0x106914664 - <unknown>
   6:        0x1067cda80 - <unknown>
   7:        0x1067ce47c - <unknown>
   8:        0x10678b2b4 - <unknown>
   9:        0x105f20080 - <unknown>
  10:        0x1060b4c84 - <unknown>
  11:        0x105ec4010 - <unknown>
  12:        0x10601c460 - <unknown>
  13:        0x105c478f0 - <unknown>
  14:        0x105c51ae8 - <unknown>
  15:        0x105c51590 - <unknown>
  16:        0x106100650 - <unknown>
  17:        0x105c81e30 - <unknown>
  18:        0x105c79738 - <unknown>
  19:        0x105c7d0c0 - <unknown>
  20:        0x105c4845c - <unknown>
  21:        0x105c94bd0 - <unknown>
  22:        0x105c485e4 - <unknown>
  23:        0x10692c644 - <unknown>
  24:        0x10690927c - <unknown>
  25:        0x105c95048 - <unknown>
  26:     0x7fffa426645c - <unknown>
  27:     0x7fffa4266634 - __libc_start_main
  28:                0x0 - <unknown>
```

timezone is `/etc/localtime -> ../usr/share/zoneinfo/US/Pacific`

**Comment by fdncred** [comment]
I've seen things like your screenshot before and it's usually because nushell's [crate that determines the terminal's width](https://crates.io/crates/term_size), `term_size` fails and returns the default of 20 columns wide. It might be worth testing `term_size` itself on your platform to see if it works.

The other error looks like the `chrono` crate is failing which appears to be an error message [here](https://github.com/chronotope/chrono/blob/aaee91222802471c656480ddb49b6f1e53a69a96/src/offset/mod.rs#L173).

**Comment by gyakovlev** [comment]
also tried in different terms (xterm console alacritty + tmux on top of some) - same result.
I'll try to dig it later if I  find time.

**Comment by fdncred** [comment]
It could very well be a bug in our term_width code that uses term_size. I have seen odd behavior in the past. Sorry that I can't quite pinpoint this for you.

**Comment by gyakovlev** [comment]
I see 3 ioctl errors coming before output coming from term_size
```
ioctl(1, _IOC(0, 0x54, 0x13, 0), 0x7fffddb801e8) = -1 ENOTTY (Inappropriate ioctl for device)
ioctl(0, _IOC(0, 0x54, 0x13, 0), 0x7fffddb801e8) = -1 ENOTTY (Inappropriate ioctl for device)
ioctl(2, _IOC(0, 0x54, 0x13, 0), 0x7fffddb801e8) = -1 ENOTTY (Inappropriate ioctl for device)
```
from term_size
```
/// Query the current processes's output (`stdout`), input (`stdin`), and error (`stderr`) in
/// that order, in the attempt to determine terminal width. If one of those streams is actually
/// a tty, this function returns its width and height as a number of characters.
```

so yeah, it's `dimensions()` returns nothing so default `20,20` gets assigned.
why it gets `ENOTTY` from ioctl on standard io descriptors though.

I've seen `TCGETS/TIOCGWINSZ/TIOCSWINSZ/termios` related bugs on ppc64 before, for example in `file` app
https://bugs.astron.com/view.php?id=168


this
https://github.com/clap-rs/term_size-rs/blob/master/src/platform/unix.rs

defines as
```rust
#[cfg(any(target_os = "linux", target_os = "android"))]
static TIOCGWINSZ: c_ulong = 0x5413;
```

but real value is `0x40087468L` on ppc.

here's simple test.

```
#include <termios.h>
#include <sys/ioctl.h>
#include <stdio.h>
#include <unistd.h>

int
main(void) {
        struct winsize ws;
        ioctl(STDIN_FILENO, TIOCGWINSZ, &ws);

         printf ("lines %d\n", ws.ws_row);
         printf ("columns %d\n", ws.ws_col);
         printf ("sizeof TIOCGWINSZ: %lx\n", TIOCGWINSZ );

        return (0);
}
```

ppc64
```
 ./tty-size
lines 52
columns 278
sizeof TIOCGWINSZ: 40087468
```

arm64 for example
```
./tty-size
lines 52
columns 278
sizeof TIOCGWINSZ: 5413
```

after re-compiling with proper value defined in term_size tables look great.
I'll open a bug there.

![image](https://user-images.githubusercontent.com/168902/94712354-d93f9d00-02f5-11eb-86c1-9b6701901179.png)

**Comment by gyakovlev** [comment]
also it somehow fixed `localtime` error, not sure how though... only thing different is fixup in `term_size` crate. but I built it without `extra` this time, maybe something in there uses chrono?
![image](https://user-images.githubusercontent.com/168902/94714507-b367c780-02f8-11eb-9e8d-60c4ea26bb5a.png)

**Comment by fdncred** [comment]
that's so strange. glad it's working for you. thanks for the research!

**Comment by gyakovlev** [comment]
actually I was wrong, still crashes in my homedir, I was just testing different one.
trying to figure out what's causing it.

**Comment by gyakovlev** [comment]
there's something here:
https://github.com/chronotope/chrono/issues/110

pinpointed it to my ~/Desktop directory

if it's present - it crashes.
if I `touch ~/Desktop` it no longer crashes.

it indeed has a very strange Access stamp very far in the future =)

```
  File: Desktop
  Size: 60              Blocks: 0          IO Block: 65536  directory
Device: 33h/51d Inode: 7006972     Links: 2
Access: (0700/drwx------)  Uid: ( 1111/      ya)   Gid: ( 1111/      ya)
Access: 4461565-09-11 14:49:52.000000000 +0000
Modify: 2020-09-30 19:10:39.955071181 +0000
Change: 2020-09-30 19:36:55.223166795 +0000
 Birth: -
```

looks like chrono bails out if it encounters that.
I don't know how I got this time on that file...

**Comment by fdncred** [comment]
lolz - year 4,461,565 - hope our code runs that long :)

**Comment by gyakovlev** [comment]
```
##
ls -ula --full-time
drwx------  2 ya   ya    60 4461565-09-11 07:49:52.000000000 -0700 Desktop

##
ls -ula
drwx------  2 ya   ya    60 Sep 11  4461565 Desktop


###
       %x     time of last access, human-readable

       %X     time of last access, seconds since Epoch

       %y     time of last data modification, human-readable

       %Y     time of last data modification, seconds since Epoch

       %z     time of last status change, human-readable

       %Z     time of last status change, seconds since Epoch
stat --printf='%x %X %y %Y %z %Z\n' Desktop
4461565-09-11 07:49:52.000000000 -0700 140731247285392 2020-09-30 12:10:39.955071181 -0700 1601493039 2020-09-30 12:36:55.223166795 -0700 1601494615
```

indeed, other tools also show it, but don't panic like chrono.

so epoch value is `140731247285392`

let's divide `LLONG_MAX` by `140731247285392`
it's around `65538.90635354418656539949` which is suspiciously close to `65535 / 0xFFFF`

also let's divide timestamp by `unit32_t` max
```
140731247285392 / 4294967295
32766.54689529876850901608
```
which is close to `32,767 / int16_t max`

and obviously with `uint32_t max`
```
140731247285392 / 2147483647
65533.09380585564943303151
```

so some userspace tool which wanted to preserve atime used wrong type at some point. my best guess.
I recently re-installed the system, trying to remember if I restored this (empty) directory from backup or let desktop environment create it.

not `nu's` fault ofc, just commenting here for history and own curiosity.

**Comment by fdncred** [comment]
closing since i think we resolved your issue. please reopen if i'm incorrect.
