### ISSUE TITLE
prompt hook no longer works with some externals

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2622]
**Describe the bug**
My prompt stopped working with a particular commit. I used `git bisect` to figure out where it broke. Here are the results.
```
cb7723f4230f067a61a0b6e75a7c5af4821df4fd is the first bad commit
commit cb7723f4230f067a61a0b6e75a7c5af4821df4fd
Author: Jonathan Turner <jonathandturner@users.noreply.github.com>
Date:   Sat Sep 26 11:40:02 2020 +1200
    Refactor scope (#2602)
    * Refactor scope to have parents
```

I use a somewhat complex prompt on windows in which I make calls to the external `git` and `zoxide`. Here's the setup.

Some aliases first
```
"alias za [a b c d] {zoxide add $a $b $c $d}",
"alias z [a b c d] {if $(echo $a | empty?) == $true { cd ~ } {echo $a | if $it == '-' { cd - } {cd $(zoxide query -- $a $b $c $d | str trim)}}}",
"alias zl [] {zoxide query --list}", 
"alias get_abbrev_pwd_win [] {echo [$(pwd | split row '\\' | first $(pwd | split row '\\' | count | = $it - 1 ) |  str substring '0,1' | format '{$it}/' | append $(pwd | split row '\\' | last ) | str collect)] | str collect}",
"alias get_abbrev_pwd_lin [] {echo [$(pwd | split row '/' | first $(pwd | split row '/' | count | = $it - 1 ) | each { str substring '0,1' | format '{$it}/' } | append $(pwd | split row '/' | last ) | str collect)] | str collect}",
"alias set_title [] {set_title_str $(echo $(get_abbrev_pwd_win))}",
"alias git_br [] {echo [ $(ansi gb) $(pwd) $(ansi reset) '(' $(ansi cb) $(do -i { git rev-parse --abbrev-ref HEAD  } | str trim | str collect ) $(ansi reset) ')' $(char newline) $(ansi yb) $(date format '%m/%d/%Y %I:%M:%S%.3f %p' --raw) $(ansi reset) ' ¯\\_(ツ)_/¯ ' ] | str collect | echo [$it $(char prompt) ' '] | str collect}",
```
And here's the prompt
```
prompt = "za $(pwd) | = `{{$(set_title)}} {{$(git_br)}}`"
```

**To Reproduce**
1. Put the above configuration points in your config.toml
2. Start nushell

**Expected behavior**
The prompt should look something like this:
```
C:\Users\username\source\repos\forks\nushell(main)
09/30/2020 12:45:20.936 PM>
```
If you have zoxide installed you should be able to `cd` into a new folder and then do `zl` to see that the new folder is now in `zoxide`'s database.

**Configuration (please complete the following information):**
 - OS (e.g. Windows):Microsoft Windows [Version 10.0.19041.508]
 - Nu version (you can use the `version` command to find out): 

|version|commit_hash|nushell_features|
|-|-|-|
|0.20.0|892a416211511b3ac7e988c24bd40df7ea99f511|default, clipboard, trash|

**Comment by jonathandturner** [comment]
@fdncred is this fixed now?

**Comment by fdncred** [comment]
@jonathandturner Just tested. Looks good. All is working now.
