### ISSUE TITLE
Shell becomes unusable after some exploring with (tab) autocompletion

### ISSUE THREAD

**Issue by jansol** [nushell/nushell#2639]
**Describe the bug**
I was trying to parse filenames from the output of a command with the intention of passing them to another utility to read a checksum field from them, tried exploring the available builtins with tab completion and after a few failed attempts nu was using a gigabyte of RAM according to KSysGuard and became unusably slow (even typing would take 5s to register or not register at all).

**To Reproduce**
1. `cat -- | rg storage | sed -e 's/: .*$//' | from<tab>`
2. try `from csv`, hit enter and paste some data that is not csv
3. repeat 2

**Expected behavior**
Command completion should not degrade the user experience even when the user tries to complete a lengthy pipeline with no clue as to what they are doing.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): NixOS unstable
 - Nu version (you can use the `version` command to find out): 0.19.0
 - Optional features (if any):

**Comment by fdncred** [comment]
There were some changes in the 0.20 release. Could you try that version, or even the latest source, to see if the problem still exists?

**Comment by jansol** [comment]
Can't repro on 0.20.0
