### ISSUE TITLE
Support for mercurial bookmarks

### ISSUE THREAD

**Issue by zbraniecki** [nushell/nushell#2648]
**Is your feature request related to a problem? Please describe.**

No, it's a regular feature request.

**Describe the solution you'd like**

Similarly to git branches, mercurial uses bookmarks. It would be great to have support for them in nushell just like we have support for git branches.

**Describe alternatives you've considered**

I was using zsh before and it has mercurial support, but I'm now trying nu as my default shell and that's a feature I miss.

**Additional context**

I work on Mozilla and we use Mercurial for Gecko and Firefox.

**Comment by fdncred** [comment]
Can you expand on this support a bit? Do you mean adding support in the prompt or somewhere else?

**Comment by zbraniecki** [comment]
When I'm in a directory with git repo, I see:

```
/home/zbraniecki/projects/icu4x(master)>
```

where `(master)` is a git branch I'm on.

When I'm in mozilla-unified directory, I see:

```
/home/zbraniecki/projects/mozilla-unified/>
```

while I'd like to see:

```
/home/zbraniecki/projects/mozilla-unified(central)>
```

where `central` is my bookmark.

I assume that what git does is that it checks if there's a `.git` directory in the path and then calls `git branch` and shows it. For mercurial you'd check if there's `.hg` directory in the path and call `hg book` to get it.

**Comment by fdncred** [comment]
One possible solution to this is to modify your prompt by editing the `config.toml` file.

In mine I have something like this:
```# prompt = "= `{{$(git_br)}}`"```

`git_br` is an alias that looks like this:
`"alias git_br [] {echo [ $(ansi gb) $(pwd) $(ansi reset) '(' $(ansi cb) $(do -i { git rev-parse --abbrev-ref HEAD  } | str trim | str collect ) $(ansi reset) ')' $(char newline) $(ansi yb) $(date format '%m/%d/%Y %I:%M:%S%.3f %p' --raw) $(ansi reset) ' ¯\\_(ツ)_/¯ ' ] | str collect | echo [$it $(char prompt) ' '] | str collect}",`

Note the embedded git command that puts the branch in my prompt `git rev-parse --abbrev-ref HEAD`. Perhaps you could use something similar and change that part to `hg book` or whatever the appropriate command is.

My prompt is a little odd but this is what those commands make my prompt look like
![image](https://user-images.githubusercontent.com/343840/95584324-25c85e00-0a03-11eb-9640-5eb9cfee6252.png)

**Comment by zbraniecki** [comment]
For the record, I was able to achieve it with starfish - https://starship.rs/config/#mercurial-branch (had to enable this module)

**Comment by fdncred** [comment]
ok. closing. thanks for the update.
