### ISSUE TITLE
completion_mode "list" doesn't work on Windows

### ISSUE THREAD

**Issue by AndrewMorsillo** [nushell/nushell#2664]
**Describe the bug**
Per title, setting `completion_mode` to `"list"` has no effect. Completion is still in default circular mode. This is on Windows 10.

**To Reproduce**
1. install nushell 0.20.0
2. `config set completion_mode "list"`
3. Attempt a completion, it is still in circular mode

**Expected behavior**
List mode should work

**Screenshots**
N/A

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Windows 10
 - Nu version (you can use the `version` command to find out): 0.20.0
 - Optional features (if any): default clipboard trash

**Comment by fdncred** [comment]
This is because `completion_type` needs to be under `[line_editor]` as [described here](https://github.com/nushell/nushell/pull/2238). Sorry if the documentation was out of date.

**Comment by AndrewMorsillo** [comment]
Ah, that does it, thanks. Seems the docs are just a bit out of date.

**Comment by fdncred** [comment]
closing. someone the docs will get updated. :)
