### ISSUE TITLE
Invalid command in alias has unhelpful error message

### ISSUE THREAD

**Issue by avandesa** [nushell/nushell#2665]
**Describe the bug**

When executing an alias with an invalid/unknown command, the resulting error message does not point to which subcommand is not found.

**To Reproduce**

Assuming `bar` is not a valid command/alias/external program:

```
alias foo [] { bar } 
foo
```

**Expected behavior**

The error message should point out `bar` as an unrecognized command, or otherwise indicate to the user exactly where the error occurred.

**Screenshots**

![image](https://user-images.githubusercontent.com/11090778/95910440-12ecbb00-0d6e-11eb-8570-0f0eb00e7050.png)

Notice that there's no indication which part of the alias failed. For this example, we know what's wrong because the alias was created one line ago, but a user may not remember exactly what commands are used in alias later on. For example, after the 0.20 release and the [merge of `trim` with `str trim`][merge], a few of my aliases I created a week before broke and were difficult to debug because of this.

[merge]: https://github.com/nushell/nushell/pull/2576

**Configuration (please complete the following information):**
 - OS: Windows, but (probably) applicable to all platforms
 - Nu version: 0.20.0
 - Optional features: Built w/ default features

**Comment by HaramanJohal** [comment]
I'm new to the repo and haven't done much Rust but would be happy to have a go at this, having a read of some contributing docs now to get started

It seems like something that we might want to do based on the second core value:
> It should provide great informative errors messages when a command will not succeed correctly. This is critically important. A fun shell gives clear, actionable errors.
