### ISSUE TITLE
Add round subcommand: math round

### ISSUE THREAD

**Issue by morbatex** [nushell/nushell#2671]
**Is your feature request related to a problem? Please describe.**
It would be nice if one could round mathematical values. 

**Describe the solution you'd like**
A math round command could be added which rounds the input:
`echo [1.5 2.3 -3.1] | math round` => `[2 2 -3]`

If it's ok I would implement this.

**Comment by fdncred** [comment]
Agreed. Maybe `floor` and `ceiling` so we can round up or down.
