### ISSUE TITLE
Help command to list out all possible (or at least most common) configurations

### ISSUE THREAD

**Issue by gillespiecd** [nushell/nushell#2687]
**Is your feature request related to a problem? Please describe.**
It would be helpful to understand all of the possible configurations with explanations, similar to `help commands` except it would be `help config`. This would help users understand how to use configurations in an easy to use manner.

**Describe the solution you'd like**
`help config` outputs a table with a list of the available configurations and some explanation of how they work

e.g.
| Name      | Description | Subconfig
| ----------- | ----------- | -----------
| table_mode      | Display table formats, such as rounded or solid seperators     |
| path   | Paths that Nushell uses to find binaries, similar to `$PATH` in bash        |
| line_editor | Configures line editor options, such as history or completion | [table 5 rows]

**Describe alternatives you've considered**
Reading through various docs such as the book and README, but they can become cumbersome to find and may become outdated or forked from each other.

**Comment by fdncred** [comment]
I was trying to think about how we could do this in code but all I'm coming up with is running a program to extract all the `config.get`s out of the `*.rs` files. Writes the results to an md file and stores it on github somewhere. So that when you do a help config it could do a fetch thisfile.md.

Any ideas on your side?

**Comment by gillespiecd** [comment]
@fdncred That seems like a reasonable approach. I don't have a good solution myself, can give some thought into it, mainly just had the idea without any implementations in mind.
