### ISSUE TITLE
Use of rest in signature and args has to be first?

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2694]
**Describe the bug**
While writing a `seq` command I stumbled upon a problem where i could get the `rest` of the arguments to populate correctly. It gave all kinds of bizarre errors. @jonathandturner was able to help me narrow it down to `rest` needed to be first in my `SeqArgs` struct and `.rest` needed to be first in my signature.

**To Reproduce**
Some examples to show what I mean above.

I had to do this to get `rest` to work.
```rust
#[derive(Deserialize)]
pub struct SeqArgs {
    rest: Vec<Tagged<u64>>,
    separator: Option<Tagged<String>>,
    terminator: Option<Tagged<String>>,
    widths: Tagged<bool>,
}
```
and
```rust
    fn signature(&self) -> Signature {
        Signature::build("seq")
            .rest(SyntaxShape::Int, "sequence values")
            .named(
                "separator",
                SyntaxShape::String,
                "separator character (defaults to \\n)",
                Some('s'),
            )
            .named(
                "terminator",
                SyntaxShape::String,
                "terminator character (defaults to separator)",
                Some('t'),
            )
            .switch(
                "widths",
                "equalize widths of all numbers by padding with zeros",
                Some('w'),
            )
    }
```

This is what it looked like when it wouldn't work.
```rust
pub struct SeqArgs {
    separator: Option<Tagged<String>>,
    terminator: Option<Tagged<String>>,
    widths: Option<Tagged<bool>>,
    rest: Vec<Tagged<u64>>,
}
```
```rust
    fn signature(&self) -> Signature {
        Signature::build("seq")
            .named(
                "separator",
                SyntaxShape::String,
                "separator character (defaults to \\n)",
                Some('s'),
            )
            .named(
                "terminator",
                SyntaxShape::String,
                "terminator character (defaults to separator)",
                Some('t'),
            )
            .switch(
                "widths",
                "equalize widths of all numbers by padding with zeros",
                Some('w'),
            )
            .rest(SyntaxShape::Int, "sequence values")
    }
```
**Expected behavior**
It would be nice not to have to worry about order of arguments/signature.

**Screenshots**

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Microsoft Windows [Version 10.0.19042.572]
 - Nu version (you can use the `version` command to find out): 

|version|commit_hash|features|
|-|-|-|
|0.21.0|f5d9fe1d864df84ad66cf46cf268cb2a2d7c0804|default|

**Comment by gillespiecd** [comment]
I ran into a similar issue in https://github.com/nushell/nushell/pull/2696, swapping out the order helped solve failing tests related to column path parsing for `rest`, but it is not entirely clear to me why.
