### ISSUE TITLE
Compare string and file path

### ISSUE THREAD

**Issue by justablob** [nushell/nushell#2700]
**Is your feature request related to a problem? Please describe.**
I'm trying to compare a file path (`$nu.cwd`) to a string (`"C:\\WINDOWS\\System32"`), but using the normal if syntax, I get a coercion error
Code: `if ($nu.cwd == "C:\\WINDOWS\\System32") { cd } { nothing };`

**Describe the solution you'd like**
Ideally, it'd just compare them.

**Describe alternatives you've considered**
I've tried a fuzzy match (`=~`) but that did nothing.

**Additional context**
When starting NuShell from Windows Terminal, it opens in System32. I wanna cd to ~, but only if it's actually in System32. When I launch it using a context menu shortcut, it opens in the correct directory.

**Comment by fdncred** [comment]
Does this work for you?
`if ($(echo $nu.cwd) == "C:\\Windows\\System32") { cd } { nothing }`

It works on macos with
`if ($(echo $nu.cwd) == "/some/multi/level/path") {= 1} {= 0}`

**Comment by justablob** [comment]
@fdncred Yep, that works perfectly. Thanks :)
