### ISSUE TITLE
Calling external command inside each block returns "Received unexpected type from pipeline (row)" error

### ISSUE THREAD

**Issue by CBenoit** [nushell/nushell#2705]
**Describe the bug**
When calling an external command inside an `each` block the following error is returned.

```
error: Received unexpected type from pipeline (row)
  ┌─ shell:1:13
  │
1 │ ls | each { ^echo $it.name }
  |             ^^^^^ expected a string
```

It is noteworthy that external command is actually executed for each element before erroring. See screenshot.

Output is mixed up with error, probably because of parallel execution.

**To Reproduce**

Simply try this pipeline

```
ls | each { ^echo $it.name }
```

**Screenshots**

![image](https://user-images.githubusercontent.com/3809077/97237643-ed27d300-17bd-11eb-8080-afee70ccb523.png)

**Configuration:**
 - OS: Archlinux
 - Nu version: 0.21.0 and current master (1b0ed3051)
 - Optional features: extra

**Comment by jonathandturner** [comment]
This may be specific to `$it.name` and `each`. A variation of the above appears to work correctly:

```
> ls *.txt | get name | each { ^echo $it }
```
