### ISSUE TITLE
Combine JSON objects even when some keys are missing

### ISSUE THREAD

**Issue by waldyrious** [nushell/nushell#2721]
**Is your feature request related to a problem? Please describe.**
Currently, `from json` is able to detect a JSON structure that's an array of object all sharing the same keys:

```console
$ echo '[{"foo":"abc", "bar":123}, {"foo":"def", "bar":456}, {"foo":"ghi", "bar": 789}]' | from json
───┬─────┬─────
 # │ foo │ bar
───┼─────┼─────
 0 │ abc │ 123
 1 │ def │ 456
 2 │ ghi │ 789
───┴─────┴─────
```

However, if one of the objects is missing one of the keys, it's not combined in the same table, even if it shares the other keys with the other objects:

```console
$ echo '[{"foo":"abc", "bar":123}, {"foo":"def", "bar":456}, {"foo":"ghi"}]' | from json
───┬─────┬─────
 # │ foo │ bar
───┼─────┼─────
 0 │ abc │ 123
 1 │ def │ 456
───┴─────┴─────
───┬─────
 # │ foo
───┼─────
 2 │ ghi
───┴─────
```

**Describe the solution you'd like**
I would like the output to be like this instead:

```console
$ echo '[{"foo":"abc", "bar":123}, {"foo":"def", "bar":456}, {"foo":"ghi"}]' | from json
───┬─────┬─────
 # │ foo │ bar
───┼─────┼─────
 0 │ abc │ 123
 1 │ def │ 456
 2 │ ghi │ 
───┴─────┴─────
```

**Describe alternatives you've considered**
Pre-processing the JSON to include keys with empty values does result in the expected outcome, but it is cumbersome:

```console
$ echo '[{"foo":"abc", "bar":123}, {"foo":"def", "bar":456}, {"foo":"ghi", "bar":null}]' | from json
───┬─────┬─────
 # │ foo │ bar
───┼─────┼─────
 0 │ abc │ 123
 1 │ def │ 456
 2 │ ghi │
───┴─────┴─────
```

I realize this would make it ambiguous whether the empty cell is an empty string, null or simply missing, but the ambiguity already exists between the first two anyway:

```console
$ echo '[{"foo":"abc", "bar":123}, {"foo":"def", "bar":456}, {"foo":"ghi", "bar":""}]' | from json
───┬─────┬─────
 # │ foo │ bar
───┼─────┼─────
 0 │ abc │ 123
 1 │ def │ 456
 2 │ ghi │
───┴─────┴─────
```

**Additional context**
I really like the approach used by http://json2table.com and https://www.convertcsv.com/json-to-csv.htm — see the JSON and CSV samples in [this comment](https://github.com/InterruptorPt/ate-onde-chega-cultura/issues/16#issuecomment-719968836) for an example JSON structure with lots of missing keys in multiple objects, that both tools were able to correctly parse into a table/CSV. I'd like nushell to be able to do the same, even if via an command-line option like `-o`/`--objects`.

**Comment by fdncred** [comment]
I agree that nushell should be more resilient. However, I believe there is a difference in implementations between these tools. Nushell streams the data where most tools read all the data in at once and massage it before writing it out. Both scenarios are good at different things. Streaming is good for massive multi-gigabyte files processing with low memory consumption. I think reading an entire file may be good at handling missing and extra columns better. Nushell is always up for good suggestions on how to handle data better.

**Comment by waldyrious** [comment]
@fdncred I understand the issue with streaming data vs. reading it all at once, but I don't know enough about the internals of how this is implemented in Nushel to understand whether any improvements (e.g. allowing missing columns in rows that come in the middle of the data) would be possible or fundamentally unworkable. Do you see any possible path forward for this request?

**Comment by fdncred** [comment]
One school of thought on a similar issue was to allow the end user to select which columns they want thereby allowing nushell to only get the specific columns.

Another approach is the read the entire stream, or a definable portion of it, and detect the columns to be used and then output the data in those columns. If you collect the entire stream then you could have all the columns and the ones that weren't populated could be blank. Or perhaps, reading the first 1000 rows is good enough to do that?

**Comment by waldyrious** [comment]
The option to let the user specify the columns makes sense, but I really would like if nushell was able to offer a more intuitive behavior by default. Is the issue that a streaming pipeline actually prints the table row by row, and therefore can't go back to add more columns to the header and to the rows that have already been printed? Or does autoview somehow batch the data it prints (I'd assume it does since IIRC it implements paginating behavior)? If the latter is true, then something similar to your second approach could be implemented based on that, right?

In any case, I can understand that the case of rows in the middle of a table having extra columns (that previous rows didn't have) is tricky to handle without some backtracking mechanism. But for the case where one of the rows in the middle of the table is missing columns that were present in the previous ones (i.e. the example I opened this issue with), why couldn't the printing code simply show empty cells in those cases and continue streaming normally?

**Comment by fdncred** [comment]
> Is the issue that a streaming pipeline actually prints the table row by row

yes

> Or does autoview somehow batch the data

I don't think it batches things but it ends tables at 1000 rows and starts a new table. There's also a paging functionality using minus that is compiled with a special feature.

As you have pointed out, there are probably several ways to solve this problem. We're open to innovative solutions. Feel free to jump in and submit a PR to help with this.

**Comment by waldyrious** [comment]
I'd be happy to contribute code, but as someone who never programmed Rust before, I was hoping to get some sort of general consensus on the design decisions and desirable solutions in this issue thread, before jumping in to learn the codebase and prepare a PR.

That said, pointers to where in the code I'd have to touch to modify this behavior (and maybe book chapters or other docs that would be relevant to obtain the necessary background) would be helpful :)

**Comment by fdncred** [comment]
I'm fine with providing the columns on the command line. You can try that and adjust as necessary.

I guess I would start with `from json` in crates/nu-command/src/commands/formats/from/json.rs. I think the `from_json()` function would be a good place to start investigating. You could start with some `eprintln!("{}", blah);` functions to see what's going on and try to decipher where the best place is to add things. You can see our contributors guide at nushell.sh.

**Comment by hustcer** [comment]
It works for me on the latest main:
`echo '[{"foo":"abc", "bar":123}, {"foo":"def", "bar":456}, {"foo":"ghi"}]' | from json`
```
  #   foo   bar
─────────────────
  0   abc   123
  1   def   456
  2   ghi   ❎
```
So I will close it, please reopen if you still have issues.
