### ISSUE TITLE
Pretty saving json files on Windows only uses \n

### ISSUE THREAD

**Issue by PunkIslamist** [nushell/nushell#2724]
**Describe the bug**
Saving a JSON file with the argument `--pretty` adds `\n` instead of the correct newline characters on Windows. It looks fine when running `> open file.json` but does not work in any other program outside of NuShell as a line break.

**To Reproduce**
1. Write a JSON file using `> echo ["a" "b"] | to json -p 2 | save file.json`
2. Open the file in any editor

**Expected behavior**
The generated JSON contains proper line breaks.

**Screenshots**
On the screenshot you can see the file opened in VS Code, and below it the output via NuShell.

![image](https://user-images.githubusercontent.com/26367652/97908057-743cf400-1d46-11eb-9156-55b77e2404d4.png)

**Configuration (please complete the following information):**
 - OS: Windows 10
 - Nu version: 0.21.0

**Add any other context about the problem here**
I tried replacing `\n` with `char newline` before saving to JSON, but that did not work. Result was the same. But when doing `echo char newline | save file.txt` it adds the correct line break.

**Comment by fdncred** [comment]
Does `echo ["a" "b"] | to json -p 2 | save --raw file.json` work the way you want it to?

**Comment by PunkIslamist** [comment]
> Does `echo ["a" "b"] | to json -p 2 | save --raw file.json` work the way you want it to?

It does indeed! Is this the desired behaviour? It seems surprising to me but that might just be a lack of understanding on my side.

**Comment by fdncred** [comment]
I'm not really sure what the desired behavior is. LOL. @jonathandturner can you answer that question?

**Comment by jonathandturner** [comment]
Feels like `to json` needs to detect Windows and use a better default
