### ISSUE TITLE
Better Starship integration

### ISSUE THREAD

**Issue by ryanpcmcquen** [nushell/nushell#2733]
**Is your feature request related to a problem? Please describe.**
In attempting to document Starship usage, I realized that there are some parameters we could be passing to make the integration nicer. Namely:

- --status
- --cmd-duration
- --keymap
- --jobs

**Describe the solution you'd like**
Expose these in `nushell` so that `prompt = "echo $(starship prompt)"` can be expanded to pass them.

**Describe alternatives you've considered**
Not having them I guess? @fdncred mentioned that `benchmark` may already be usable for the `cmd-duration`.

**Additional context**
Somewhat related tickets:
https://github.com/nushell/nushell/issues/2703
https://github.com/starship/starship/issues/1716

**Comment by mburszley** [comment]
Isn't this the purpose of `starship.toml` to configure the prompt?  I don't see the value-add of having cli arguments.  I do observe the problem with exit codes not being reflected so `error_symbol` is never seen.

**Comment by ryanpcmcquen** [comment]
@mburszley, these configurations are not possible with `starship.toml`.

**Comment by ryanpcmcquen** [comment]
@fdncred is this possible with https://github.com/nushell/nushell/pull/3081?

**Comment by fdncred** [comment]
You may be able to pass the `$nu.env.CMD_DURATION` env var in the `--cmd-duration` parameter. If you try it, let me know how it comes out.

**Comment by davidkna** [comment]
I tried it once, but I couldn’t figure out how to convert the duration type into milliseconds.

**Comment by ryanpcmcquen** [comment]
I've tried this:
```
prompt = "starship prompt --cmd-duration=$nu.env.CMD_DURATION"
```

And this:
```
[env]
STARSHIP_DURATION = "$nu.env.CMD_DURATION"
```

And this inside of `starship.toml`:
```
[cmd_duration]
min_time = 1
format = "took [$CMD_DURATION](bold yellow)"
```

There must be a way but I probably have something wrong syntax wise.

**Comment by fdncred** [comment]
@davidkna it doesn't use nu's internal duration mechanism. It's just this:
```rust
let cmd_start_time = std::time::Instant::now();
.add_env_var("CMD_DURATION", format!("{:?}", cmd_start_time.elapsed()));
```

**Comment by fdncred** [comment]
@ryanpcmcquen I haven't tried but maybe something like this?

`prompt = (starship prompt --cmd-duration=($nu.env.CMD_DURATION))`

so that `(starhip)` and `($nu.env.CMD_DURATION)` are sub expressions?

**Comment by fdncred** [comment]
@davidkna I could just make it `cmd_start_time.elapsed().as_millis()` if that's more helpful?

**Comment by jonathandturner** [comment]
@fdncred if we added support to `into string` for durations, you could do that also, right? `($nu.env.CMD_DURATION | into string)`

**Comment by davidkna** [comment]
@fdncred Something like that should work.

**Comment by fdncred** [comment]
Maybe i'll make this change a PR and update the env var to something like `$nu.env.CMD_DURATION_MS`. Give me a few.

**Comment by fdncred** [comment]
The PR is landed. Can y'all give it a try and see if it helps the situation?

**Comment by davidkna** [comment]
@fdncred It works now.

**Comment by fdncred** [comment]
@ryanpcmcquen does this change work for you too?

**Comment by ryanpcmcquen** [comment]
I haven't had time to test, but I imagine it would. @davidkna, how did you configure it?

**Comment by davidkna** [comment]
@ryanpcmcquen 
```toml
prompt = 'starship prompt --cmd-duration $nu.env.CMD_DURATION_MS'
```

**Comment by ryanpcmcquen** [comment]
Doing this until the next release:
```
prompt = "$nu.env.CMD_DURATION\nstarship prompt"
```

**Comment by ryanpcmcquen** [comment]
@fdncred, did `$nu.env.CMD_DURATION` go away? Seems `$nu.env.CMD_DURATION_MS` is the only one available now.

**Comment by ryanpcmcquen** [comment]
That makes sense, I kinda liked how the other one would auto parse the time, but it's not a big deal. This one works great with Starship.

**Comment by ryanpcmcquen** [comment]
It'd still be nice to have exit code.

**Comment by fdncred** [comment]
agreed. we've been talking about it recently and where to add it in engine-q.

**Comment by fdncred** [comment]
we've added exit code via `$env.LAST_EXIT_CODE`
