### ISSUE TITLE
History command include timestamps

### ISSUE THREAD

**Issue by gillespiecd** [nushell/nushell#2735]
**Describe the solution you'd like**
`history` will output a table with:
1. column with timestamp of when command was ran
1. column with the command ran

This could either be a flag or built into the command itself

**Implementation Thoughts**
Internally, Bash does this by having a separate line that stores the timestamp in `.bash_history`

![image](https://user-images.githubusercontent.com/6572184/98450106-b7081e80-20ee-11eb-8c02-cb8b99979ec0.png)

In Nushell, something similar could be done when a command is run in `cli.rs`, add a history entry with the timestamp and then add an entry with the command line. If timestamp doesn't exist (e.g. past commands before this change), then output current timestamp.

```
            LineResult::Success(line) => {
                >>> ADD history entry for timestamp 
                rl.add_history_entry(&line);
                let _ = rl.save_history(&history_path);
                context.maybe_print_errors(Text::from(line));
            }
```

Then when the `history` command reads the file, it can act accordingly.

**Comment by fdncred** [comment]
I think this would be a good add if/when `nu_line` ever comes to fruition. I'm not sure how `rustyline` would respond to this.

**Comment by lukexor** [comment]
Can we re-open this? This seems like a very useful feature - and specifically looking to use it to track work I do a bit more automatically.

**Comment by DJDuque** [comment]
Any chance this can be re-opened? Seems like a pretty useful feature.

**Comment by fdncred** [comment]
@DJDuque Use the sqlite history option. `$env.config.history.file_format = sqlite`

**Comment by DJDuque** [comment]
> [@DJDuque](https://github.com/DJDuque) Use the sqlite history option. `$env.config.history.file_format = sqlite`

Awesome, this is great!

Two notes for people coming from the future looking gor this:
1. You need to put quotes around `sqlite` i.e. `$env.config.history.file_format = "sqlite"`.
2. Beware that this will empty your old history.

**Comment by fdncred** [comment]
We also have `history import` functionality. `help history import`.
