### ISSUE TITLE
Better HTTP support: add commands for PUT & DELETE requests

### ISSUE THREAD

**Issue by bluejuniper** [nushell/nushell#2741]
Currently only have commands for POST/GET requests

**Comment by rgwood** [comment]
The HTTP commands need some attention and this is a good place to start; we should make it possible to do any HTTP action instead of just GET and POST.

**Comment by rgwood** [comment]
Some feedback from Discord suggests that 2 might be the way to go:

> i like your suggestion of adding `http <verb>`, this seems the most intuitive for nushell
> ...
> when attempting to figure out http get on my own, i did attempt to use `http` as that was the most intuitive thing for me.

If we do this, perhaps we should alias `fetch` to `http get` for convenience?

**Comment by sholderbach** [comment]
I think at the same time we need to identify what the scope of a nushell-value-add interface should be. I think reimplementing `curl` in it's entirety is a non-goal.

**Comment by rgwood** [comment]
> Is this going to enhance by http pipeline ?

I don't understand the question, sorry.

> If there is can I work on it?

You are welcome to work on it but I may not be able to help much with design and review.

**Comment by jaudiger** [comment]
Should we now close this issue ? Since everything is merged into the main branch.

**Comment by sholderbach** [comment]
Yes! Thanks for implementing and refactoring all this!
