### ISSUE TITLE
Bugs in multiline: externals

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2744]
**Describe the bug**
Using an external as one of the commands causes values to be evaluated out of order.

**To Reproduce**

```
echo a
^echo c
echo $(char newline)
echo b
```

Outputs:

```
c
a
b
```

**Expected behavior**
```
ac

b
```

**Comment by aminya** [comment]
I am experiencing a related bug. Is this a known issue?

```
> node -e 'console.log("sss")
console.log("aaaa")'

sss
```

I expected
```
sss
aaa
```
