### ISSUE TITLE
Add  a to/from base64 or a more general hashing command

### ISSUE THREAD

**Issue by notryanb** [nushell/nushell#2748]
**Is your feature request related to a problem? Please describe.**
I've found often enough, at least in web development, I've needed to generate Base64 encoded data. My solution up until recently has been to use online tools until I found I could do it fairly easily, albeit verbose in PowerShell. I have not searched for a *nix equivalent. It would be very helpful to have a to/from conversion for Base64 encoding that has a really simple interface.

It may be helpful to develop a more generalized hashing command even if the `from` features are not possible.

**Describe the solution you'd like**
Examples for solving the initial problem of Base64 encoding/decoding. It would default to UTF8.
- `username:password | to base64`  => dXNlcm5hbWU6cGFzc3dvcmQ=
- `dXNlcm5hbWU6cGFzc3dvcmQ= | from base64` => username:password
- `username:password | to base64 --encoding=unicode` =>dQBzAGUAcgBuAGEAbQBlADoAcABhAHMAcwB3AG8AcgBkAA==
- `dQBzAGUAcgBuAGEAbQBlADoAcABhAHMAcwB3AG8AcgBkAA== | from base64 --encoding=unicode` =>username:password

**Describe alternatives you've considered**
My initial use case is specifically for strings, so I thought it could be a `str` subcommand, however a user may need to apply this to binary data as well.

Base64 could be a subset of a more generalized `hash` or `crypto` command. Some examples may include the following.

- `username:password | hash base64 to-utf8` => dXNlcm5hbWU6cGFzc3dvcmQ=
- `dXNlcm5hbWU6cGFzc3dvcmQ= | hash base64 from-utf8` => username:password
- `some-binary-data-you-may-want-to-checksum | hash md5` => MD5 Result

**Additional context**
Here are examples of how I've accomplished the same behavior in PowerShell.
- `[System.Convert]::ToBase64String([System.Text.Encoding]::UNICODE.GetBytes("username:password"))`
- `[System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("username:password"))`

I'd like to start playing around with this. Some input on the interface would be helpful. I'm personally leaning towards the `hash` command with individual sub commands so other people can implement new hash functions following a similar pattern.

**Comment by Delapouite** [comment]
That would indeed be a welcomed addition. I'd suggest that this `base64` utility should also support the very popular `base64url` flavor, in which the chars `+` is `-` and `/` is `_`. https://tools.ietf.org/html/rfc4648#section-5

**Comment by fdncred** [comment]
@notryanb I like the `hash` command myself with `base64`, `sha256`, `md5`, etc subcommands. Good examples and use cases too. Thanks!
@jonathandturner @andrasio what are your thoughts on this?
