### ISSUE TITLE
Kubectl native support

### ISSUE THREAD

**Issue by kivio** [nushell/nushell#2749]
**Is your feature request related to a problem? Please describe.**

Using kubectl command line often I need to made complex query and displaying on it, unfortunately to do it natively you need to use jsonPATH which is terrible for complicated tables. Trying to use nushell but it's not compatible as kubectl returns strings with complicated formatting.

**Describe the solution you'd like**

It will be good if nushell will support kubectl tabular output natively or to add `from kubectl` operator.

**Describe alternatives you've considered**

**Additional context**

**Comment by fdncred** [comment]
@kivio I'd like to play around with what's not working for you. Is there a file you can provide that demonstrates the issues you're having and then describe exactly what you're trying to get out of said file?

**Comment by kivio** [comment]
this is example output of `kubectl get service` command:
```
kubectl get service
NAME                                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
helm-artifactory-jcr-artifactory           ClusterIP   10.100.108.5    <none>        8082/TCP,8081/TCP   47h
helm-artifactory-jcr-postgresql            ClusterIP   10.100.66.255   <none>        5432/TCP            20h
helm-artifactory-jcr-postgresql-headless   ClusterIP   None            <none>        5432/TCP            47h
```

I want to do on it things like for example sorting it by AGE. 

How I understand comparing with `ps` support it should work  like:
`kubectl get service | str to-int AGE | sort-by AGE`

But it doesn't work as a table produced by kubernetes is not real table.

Output I get look's like:
```
error: no values to work with
  ┌─ shell:1:40
  │
1 │ kubectl get service | str to-int AGE | sort-by AGE
  │                                        ^^^^^^^ no values to work with

error: Type Error
  ┌─ shell:1:1
  │
1 │ kubectl get service | str to-int AGE | sort-by AGE
  │ ^^^^^^^ Expected row or table, found string

```

Unfortunately when I try to put it into lines and then parse - it's problematic as cannot define delimiters between columns.
Of course, I can work on yamls or jsons from kubectl but it starts being much more complex to do something.

**Comment by fdncred** [comment]
I thought you said there was a json output from kubectl. did i misunderstand you?

**Comment by kivio** [comment]
There is an option to get JSON - but it's not JSON with these fields - there is like 50 more fields per row and complex structure.
Example output for only one line:

```
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "annotations": {
            "helm.fluxcd.io/antecedent": "helm:helmrelease/jcr"
        },
        "creationTimestamp": "2020-11-10T18:04:43Z",
        "labels": {
            "app": "postgresql",
            "chart": "postgresql-8.7.3",
            "heritage": "Helm",
            "release": "helm-artifactory-jcr"
        },
        "name": "helm-artifactory-jcr-postgresql-headless",
        "namespace": "artifactory",
        "resourceVersion": "48002472",
        "selfLink": "/api/v1/namespaces/artifactory/services/helm-artifactory-jcr-postgresql-headless",
        "uid": "3522ca46-5a72-43e3-ac15-e351b83a8784"
    },
    "spec": {
        "clusterIP": "None",
        "ports": [
            {
                "name": "tcp-postgresql",
                "port": 5432,
                "protocol": "TCP",
                "targetPort": "tcp-postgresql"
            }
        ],
        "selector": {
            "app": "postgresql",
            "release": "helm-artifactory-jcr"
        },
        "sessionAffinity": "None",
        "type": "ClusterIP"
    },
    "status": {
        "loadBalancer": {}
    }
}
```

**Comment by fdncred** [comment]
wow, that json is a mess. lots of detail though. how about this for your first question.
`open kube.txt | lines | str trim | split column " " --collapse-empty | headers`
```
╭───┬──────────────────────────────────────────┬───────────┬───────────────┬─────────────┬───────────────────┬─────╮
│ # │ NAME                                     │ TYPE      │ CLUSTER-IP    │ EXTERNAL-IP │ PORT(S)           │ AGE │
├───┼──────────────────────────────────────────┼───────────┼───────────────┼─────────────┼───────────────────┼─────┤
│ 0 │ helm-artifactory-jcr-artifactory         │ ClusterIP │ 10.100.108.5  │ <none>      │ 8082/TCP,8081/TCP │ 47h │
│ 1 │ helm-artifactory-jcr-postgresql          │ ClusterIP │ 10.100.66.255 │ <none>      │ 5432/TCP          │ 20h │
│ 2 │ helm-artifactory-jcr-postgresql-headless │ ClusterIP │ None          │ <none>      │ 5432/TCP          │ 47h │
╰───┴──────────────────────────────────────────┴───────────┴───────────────┴─────────────┴───────────────────┴─────╯
```

**Comment by kivio** [comment]
Found solution - this table that kubectl produce need to be aligned - use `align` utility. (https://legacy.cs.indiana.edu/~kinzler/align/)
Effect:
```
kubectl get service | align | lines | split column " " --collapse-empty | headers
───┬──────────────────────────────────────────┬───────────┬───────────────┬─────────────┬───────────────────┬─────
 # │                   NAME                   │   TYPE    │  CLUSTER-IP   │ EXTERNAL-IP │      PORT(S)      │ AGE
───┼──────────────────────────────────────────┼───────────┼───────────────┼─────────────┼───────────────────┼─────
 0 │ helm-artifactory-jcr-artifactory         │ ClusterIP │ 10.100.108.5  │ <none>      │ 8082/TCP,8081/TCP │ 2d
 1 │ helm-artifactory-jcr-postgresql          │ ClusterIP │ 10.100.66.255 │ <none>      │ 5432/TCP          │ 2d
 2 │ helm-artifactory-jcr-postgresql-headless │ ClusterIP │ None          │ <none>      │ 5432/TCP          │ 2d
───┴──────────────────────────────────────────┴───────────┴───────────────┴─────────────┴───────────────────┴─────
```

**Comment by kivio** [comment]
Have made alias for this ugly part inside ;) 
`alias kubetable [] { align | lines | str trim | split column ' ' --collapse-empty | headers }`

and now I can do things like `kubectl get po -n kube-system | kubetable | str find-replace "d" "" AGE | sort-by AGE`

**Comment by kivio** [comment]
believe align function can be useful in some cases as part of nushell.

**Comment by fdncred** [comment]
That `align` is cool however it assumes data is not streamed. A lot of nushell commands stream data so we'd have to have something like a `collect` command in order to do alignment like this. But this is a great find for your case.
