### ISSUE TITLE
Use command output as argument for other command

### ISSUE THREAD

**Issue by janosimas** [nushell/nushell#2754]
**Describe the bug**
Using `$()` to produce an output that will be used in another command fails when it's concatenated with some other text.

**To Reproduce**
```bash
echo $(pwd)\test
```

**Expected behavior**
The output of `pwd` concatenated with `\test`

**Configuration (please complete the following information):**
 - Windows 10
 - Nu: 0.21.0 

I first notice the issue when using `docker` to process some files, I wanted to give access to my current folder. This is straightforward in other shells.
My command looks like this:
```bash
docker run --rm --network host -v $(pwd):/tmp ...
```

**Comment by kubouch** [comment]
You need to build the string with manually: `echo $(build-string $(pwd) \test)`. More straightforward concatenation would be nice for sure, though it might clash with the data types nushell uses.

**Comment by janosimas** [comment]
It solved my issue, thanks!

In any case, it's quite unpleasant to use `build-string`. I don't know about the clash but I would strongly vote for a more straightforward concatenation.

**Comment by jonathandturner** [comment]
@janosimas can you file a feature request for simpler concatenation? That way we won't lose the idea
