### ISSUE TITLE
`fetch` does not resolve names; "url not found"

### ISSUE THREAD

**Issue by Halkcyon** [nushell/nushell#2756]
**Describe the bug**
This may exist for `post` as well, but I've only tested `fetch` so far.  I'm trying to interact with company-internal sites and if I do not use a FQDN, `fetch` gives me the error `url not found`.  I've ensured my proxies (and `no_proxy`) are configured properly.  This is a Windows environment where I'm on the same domain as the host so I'm not fully-pathing the domain, i.e.:

```sh
fetch https://host/path
# vs.
fetch https://host.domain.com/path
```

**To Reproduce**
Unsure how to reproduce publicly.

**Expected behavior**
The commands should resolve the name properly.

**Configuration (please complete the following information):**
 - OS (e.g. Windows): Win7
 - Nu version (you can use the `version` command to find out): `0.22.0`
 - Optional features (if any): `--all-features`

**Comment by fdncred** [comment]
I get the same thing regardless of whether i'm behind my company's firewall or not. But it works on other sites like https://www.google.com and https://www.github.com. So, i'm not sure what is going on.

**Comment by fdncred** [comment]
I did a quick change on the code to show the error instead of just 'url not found' and this is what it's saying.
```
error: URL could not be opened
  ┌─ shell:1:7
  │
1 │ fetch https://www.redactedsite.com
  │       ^^^^^^^^^^^^^^^^^^^^^^^^ ResponseBodyError(None): unknown error
```

**Comment by mburszley** [comment]
@fdncred It looks like it's going to the generic error block here:
https://github.com/nushell/nushell/blob/main/crates/nu_plugin_fetch/src/fetch.rs#L254-L258

**Comment by fdncred** [comment]
ya, that generic error block is what I changed to get the specific error I posted above. Also, keep in mind that we're a whole version behind on surf. We're running 1.x and 2.x is out. Maybe the bug is fixed in 2.x?
