### ISSUE TITLE
Simpler command output concatenation

### ISSUE THREAD

**Issue by janosimas** [nushell/nushell#2757]
**Is your feature request related to a problem? Please describe.**
The current way of doing a concatenation of the output of a command is to use `build-string`.
It's cumbersome, specially when comparing to other shells.

**Describe the solution you'd like**
Having some tag like `${cmd}` that concatenates.

**Describe alternatives you've considered**
The current way to execute a command is using `$(cmd)` but I understand there may be conflicts about the Nu data types.
Maybe using a different marker like `$[cmd]`, that would always output a string. I believe this would solve the issue about the data types.

**Additional context**
Initial discussion #2754.

I first notice the issue when using docker to process some files, I wanted to give access to my current folder. This is straightforward in other shells.
My command looks like this:
```bash
docker run --rm --network host -v $(pwd):/tmp ...
```

**Comment by fdncred** [comment]
Another way to concatenation strings is with `str collect` like `echo [str1 str2 str3 str4] | str collect`, although I wouldn't call this less cumbersome.

**Comment by fdncred** [comment]
Just brainstorming here.

One thought is to emulate pwsh by using the plus sign.
`"one" + "|" + "two" + "|" + 5 + "|" + $PSVersionTable.Count`
`one|two|5|9`

What are alternate ways of doing string concatenation?

bash
* `$var1$var2` - but we don't have variables yet so this isn't really applicable
* `"${var1}World"` - same note as above
* `printf "%s%s" "foo" "bar"` - in this respect, `build-string` works a little like this so I'm not sure a `printf` command would make things better
* `echo ${HOSTTYPE}foo` returns `x86_64foo` - i'm guessing this is an option where nushell but maybe with string interpolation like ```echo `{{$nu.env.HOSTTYPE}}`foo```

**Comment by janosimas** [comment]
In bash we can do `$(cmd)` and execute a command, it doesn't need to be a variable.
In powershell it also works but I'm not sure about the difference of `$()` and `${}`.

Something like the last option looks good to me.

**Comment by GrabbenD** [comment]
For future readers who stumble upon this, there's a [couple](https://www.nushell.sh/book/coming_from_bash.html#command-equivalents) of ways to achieve this nowadays e.g.:

```nushell
# Command substitution
podman image inspect --format '{{ .ID }}' ...(podman image list --all --quiet | lines)

# String interpolation
podman run --rm --interactive --tty --cpus=$"(sys cpu | length)" docker.io/library/archlinux:latest 'nproc'
```
