### ISSUE TITLE
Autocomplete freeze on commands

### ISSUE THREAD

**Issue by deuzu** [nushell/nushell#2759]
**Describe the bug**

Autocompleting a command freeze for ~5 seconds then succeed.

**To Reproduce**

1. Type half of a command
2. Press tab
3. Wait for ~5 seconds

**Expected behavior**

Autocomplete on commands should take less than 1 second.

**Video**

[![watch the video](https://i.imgur.com/A09XWF2.png)](https://streamable.com/bm1kv4)

**Configuration:**

 - OS: Ubuntu 20.04 on WSL 2 On Windows 10
 - Nu version: 0.22.0
 - Optional features: all (I guess? 🤷‍♂️)

The autocomplete works fine with paths.  
[Windows has interoperability with Linux via WSL](https://docs.microsoft.com/en-us/windows/wsl/interop), meaning that all Windows commands (`.exe` in path) are autocompletable from Nu or Bash. Bash is not affected by the latency on command autocompletion.

**Comment by fdncred** [comment]
I've noticed this too and it's really annoying. I never thought that it could be the interoperability functionality you're talking about but it makes total sense.

**Comment by deuzu** [comment]
I disabled interoperability with Windows on WSL, Windows binaries are not appended in path anymore and autocompletion is now as fast as bash.

More details on how to disable interoperability here: https://github.com/microsoft/WSL/issues/1493

**Comment by HoroTW** [comment]
I fixed it by deactivating the "appendWindowsPath" feature.
You will lose the ability to `just` execute windows binaries like the explorer.exe (you can still execute them by using the full path /mnt/c/..../explorer.exe)

Create a `/etc/wsl.conf` with following content:

```
[Interop]
appendWindowsPath = False
```

After that you have to restart wsl by executing
`wsl.exe --shutdown`

Now you can enjoy a blazing fast nushell 😄
(you can still add single executable like the explorer.exe to your path after that)

**Comment by fdncred** [comment]
Good tips. Thanks for sharing.
