### ISSUE TITLE
Make feedback easy to give

### ISSUE THREAD

**Issue by jamiedgh** [nushell/nushell#2761]
**Is your feature request related to a problem? Please describe.**
The [Nushell](nushell.sh) homepage at the bottom asks for feedback without any link, which means a user would have to hunt for where to give their feedback. By the time I've figured out where to send feedback, I may have forgotten what I wanted to tell you in the first place. If you ask a user to volunteer help, the process should be frictionless and immediate.

**Describe the solution you'd like**
The sentence should be a link to perhaps the issues section of this github or a form. Also, consider prominently displaying links to community pages, such as reddit, twitter, the nushell stack exchange tag, and maybe a discord group. I know social media can be obnoxious, but projects can live or die by the community they foster. 

A discord group could include a bot that collections questions and answers into a document, which could then be read through occasionally to add to a cookbook or stack exchange question-answer catalogue. This would be so worthwhile, as finding answers on stackexchange via an external search engine is like having a well-indexed cookbook.

**Describe alternatives you've considered**
Another thought I just had would be to package into nushell a searchable catalogue of all nushell tagged stack exchange posts. Seeing as it would all be text, I can't imagine the size would be very big, and it would give users an offline searchable copy of all kinds of problems and solutions.

**Comment by jankoprowski-intel** [comment]
Maybe nushell should provide command **feedback** running browser on given web page?

**Comment by mhmdanas** [comment]
It may be appropriate to transfer this issue to https://github.com/nushell/nushell.github.io.
