### ISSUE TITLE
Improve workflow to set Nu as the default shell in VS Code

### ISSUE THREAD

**Issue by yoshuawuyts** [nushell/nushell#2775]
**Is your feature request related to a problem? Please describe.**
VS Code has a dropdown available to select shells, but nushell is not part of it. I've managed to make Nu my default shell for my windows terminal, but VS Code doesn't respect these settings -- so having an easy way to set Nu as the default shell would make setting up Nu a lot easier.

**Describe the solution you'd like**
Ideally VS Code could display Nu in the shell list, if available and enable for it to be selected. I think this can be done either by submitting a patch to VS Code itself, or by authoring a nu language plugin that adds this option.

**Describe alternatives you've considered**
Alternatively in the interim having a config guide on how to enable it as the default shell for VS Code would be useful. [Example of instructions for a different shell](https://techcommunity.microsoft.com/t5/itops-talk-blog/configure-visual-studio-code-to-run-powershell-for-windows-and/ba-p/283258).

**Additional context**
This is what the selection dropdown looks like today:

![Screenshot 2020-12-03 10 17 04](https://user-images.githubusercontent.com/2467194/100989192-db6de400-3550-11eb-81e0-8bbc5a384b9a.png)

**Comment by fdncred** [comment]
It would be great to have an extension with syntax highlighting and this feature once our scripting gets more mature.

**Comment by scambier** [comment]
> Alternatively in the interim having a config guide on how to enable it as the default shell for VS Code would be useful. Example of instructions for a different shell.

This link is outdated, and configuring a new shell in VSCode is now quite straightforward.

In the Command Palette, look for `Terminal: Configure Terminal Settings`, then `Terminal > Integrated > Profiles: [your OS]`, and click on "Edit in setttings.json". This will auto-complete your settings.json with the default values.

Just add a new profile and set it as your default:
```js
  "terminal.integrated.profiles.windows": {
    /* other profiles */
    "Nu": {
      "path": "path to nushell excecutable",
    }
  },
  "terminal.integrated.defaultProfile.windows": "Nu"
```

**Comment by fdncred** [comment]
This is how I have mine

```json
        "Nushell": {
            "path": "C:\\Apps\\Nushell\\nu_latest\\nu.exe"
        },
        "Nushell (No Config)": {
            "path": "C:\\Apps\\Nushell\\nu_latest\\nu.exe",
            "args": ["--config-file", "C:\\Users\\username\\AppData\\Roaming\\nushell\\nu\\config\\empty-conifg.toml"],
            "overrideName": true
        }
```

**Comment by fdncred** [comment]
This is how I have mine

```json
        "Nushell": {
            "path": "C:\\Apps\\Nushell\\nu_latest\\nu.exe"
        },
        "Nushell (No Config)": {
            "path": "C:\\Apps\\Nushell\\nu_latest\\nu.exe",
            "args": ["--config-file", "C:\\Users\\u\\AppData\\Roaming\\nushell\\nu\\config\\empty-conifg.toml"],
            "overrideName": true
        }
```

**Comment by yoshuawuyts** [comment]
The nushell twitter account recently [shared a photo](https://twitter.com/nu_shell/status/1413932556144168960/photo/1) covering [the ability to contribute terminal profiles](https://code.visualstudio.com/updates/v1_58#_contribute-terminal-profiles) in a recent version of VS Code.

> Terminal profiles can now be contributed by extensions and they will be displayed in the profile picker:

---

Given there's [an official nushell VS Code extension now](https://marketplace.visualstudio.com/items?itemName=TheNuProjectContributors.vscode-nushell-lang) I wonder if it would make sense to integrate it into that?

**Comment by sholderbach** [comment]
I think on Windows this now works out of the box when nushell is installed (through the `.msi` in this case) and the `vscode-nushell-lang` extension is installed.

![grafik](https://user-images.githubusercontent.com/15833959/210071074-0619477c-305f-4bae-a50d-0244ca492ce1.png)

**Comment by Banyc** [comment]
I did this to get my env variables back:

```json
"nu": {
    "path": "bash",
    "args": [
        "-l",
        "-c",
        "nu"
    ],
}
```

**Comment by jntrnr** [comment]
Looks like this works now. Thanks for the idea :)

**Comment by el-f** [comment]
for windows:
```py
  "terminal.integrated.profiles.windows": {
    # other profiles
    "Nushell": {
      "path": "nu",
    }
  },
  "terminal.integrated.defaultProfile.windows": "Nushell"
  ```

**Comment by jsonMartin** [comment]
> I am macOS, and I use this configuration:
> 
> ```json
>  "terminal.integrated.profiles.osx": {
>     "nu": {
>       "path": "/opt/homebrew/bin/nu",
>     }
>   },
>   "terminal.integrated.defaultProfile.osx": "nu",
> ```

Thanks, that worked for me!

**Comment by ishipachev** [comment]
Guys, does it work for you when you try to debug python file?
I'm trying to use this combination: Win10 + VSCode + Python + Pixi + Debug button. 

And I've got this:
![image](https://github.com/user-attachments/assets/d75368e8-0183-4a95-8e23-5e9adbdeac4b)
It seems that VSCode (or pixi?) try to call a command with && symbol which is not something nushell likes:

```
c: && cd c:\dev\data_processing\mosaic_extractor && cmd /C "c:\programs\miniconda\envs\raw2dng\python.exe c:\Users\360ci\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher 52989 -- c:\dev\data_processing\mosaic_extractor\extract_frames_integrate_gpx.py "
```

Honestly, I don't know whom to blame here: VSCode or pixi for forming this command. Defenitely not nushell. Does anyone know how to resolve it? I don't want to switch back to powershell :(

**Comment by fdncred** [comment]
There are several things in that command line that nushell doesn't like right now. I'd love to see it fixed in nushell and in vscode.
1. `c:` <- this doesn't work in nushell. it would probably need to be added to nushell or changed to in vscode to `cd c:\`
2. `&&` <- this doesn't work in nushell. we'd have to see if `;` works as the help says. Would need to be changed in vscode for nushell.
3. `"c:\any\path"` <-- this doesn't work in nushell since double quotes mean interpret escapes. This would need to be changed to backtick quotes or single quotes in vscode for nushell.
4. `/../..\debug\launcher` <- this might work? i don't think nushell cares of the direction of slashes. would have to be tested more.
5. `--` <- I know -- doesn't work for nushell but since this is being passed to launcher, it may work?
6. ending the quoted string with a space seems wrong?

**Comment by ishipachev** [comment]
> There are several things in that command line that nushell doesn't like right now. I'd love to see it fixed in nushell and in vscode.

I agree. But there are a couple moments which I don't understand I must admit.
How does VSCode forms the command? I found [this](https://code.visualstudio.com/docs/terminal/shell-integration) documentaion and nushell is not there in the list:
```
Supported shells:

Linux/macOS: bash, fish, pwsh, zsh
Windows: pwsh
```
But what does it mean "supported"? How much we can do here without diving into VSCode itself by tweaking up settings.json? I've tried just "Run" python file and it works. But with debug I have a long command I copypasted above. In this case it has a quite command which contains symbols not appropriate for nushell. The same using tasks.json. 

The questions is how to modify vscode command to have a correct call for the debugger. Maybe an answer to have a custom command which runs the selected script in the selected environment and properly attach it to the debugger? Well, the question is how to build this command in tasks.json and if this command can be easily adopted for any type of python environments, including venv, conda, pixi etc.

**Comment by DreamMaoMao** [comment]
> 
> ```python
>   "terminal.integrated.profiles.windows": {
>     # other profiles
>     "Nushell": {
>       "path": "nu",
>     }
>   },
>   "terminal.integrated.defaultProfile.windows": "Nushell"
> ```

just need now
```json
    "terminal.integrated.defaultProfile.windows": "Nushell",

```

**Comment by ishipachev** [comment]
Just in case for everyone who is also looking for a solution for python debugger in VSCode here. Seems like it got some attention from MS team (thanks to @karthiknadig and @eleanorjboyd):
https://github.com/microsoft/debugpy/issues/1853
and
https://github.com/microsoft/vscode-python-debugger/issues/647
