### ISSUE TITLE
Key binding: Insert and AcceptLine

### ISSUE THREAD

**Issue by 89z** [nushell/nushell#2781]
I would like to make a key binding, that move to the parent directory. I came
up with this:

~~~
-
   key:
      ControlUp:
   binding:
      Insert:
         repeat: 1
         string: "cd .."
~~~

but it requires the Enter key. Then I tried this:

~~~
-
   key:
      ControlUp:
   binding:
      Insert:
         repeat: 1
         string: "cd ..\n"
~~~

but it just adds a literal Newline, then still wants and Enter key. Then I found
this:

~~~
-
   key:
      ControlUp:
   binding:
      AcceptLine:
~~~

but doesnt seem like both can be combined. I am currently using this with
PowerShell:

~~~
Set-PSReadLineKeyHandler Ctrl+UpArrow {
   Set-Location ..
   [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
}
~~~

Is what I am wanting possible with Nushell?

**Comment by 89z** [comment]
https://github.com/kkawakam/rustyline/issues/306

**Comment by 89z** [comment]
boop

**Comment by fdncred** [comment]
keybindings are completely different now since we're using `reedline` now instead of `rustyline`. This type of thing should be possible given how flexible keybindings are now. Unfortunately, keybindings aren't documented real well right now.

Given that this works, I'm going to close this issue.
```
    {
        name: fzf
        modifier: control
        keycode: char_f
        mode: emacs
        event: [
            { edit: { cmd: clear } }
            { edit: { cmd: insertstring value: 'cd (ls | where type == dir | each {|it| $it.name} | str collect (char nl) | fzf | decode utf-8 | str trim)' } }
            { send: enter }
        ]
    }
```

**Comment by 89z** [comment]
I dont understand - why if your command Ctrl+F when mine was Ctrl+UpArrow?

Is Ctrl+UpArrow not possible?

**Comment by fdncred** [comment]
they keybinding in my example was just an example of some of what it can do. you can see what is available with `keybindings list`, but yes, control up is a possibility.

**Comment by 89z** [comment]
> you can see what is available with `keybindings list`, but yes, control up is a possibility.

That command doesnt work:

~~~
D:\Desktop\nushell-0.44.0> keybindings list
error: Command not found
  ┌─ shell:1:1
  │
1 │ keybindings list
  │ ^^^^^^^^^^^ command keybindings not found
~~~

**Comment by 89z** [comment]
Your given example doesnt work with current version:

~~~
PS D:\Desktop\nushell-0.60.0> .\nu.exe
Error: nu::shell::unsupported_config_value (link)

  × Unsupported config value
     ╭─[C:\Users\Steven\AppData\Roaming\nushell\config.nu:223:1]
 223 │         event: [
 224 │             { edit: { cmd: insertstring value: 'cd (ls | where type == dir | each {|it| $it.name} | str collect (char nl) | fzf | decode utf-8 | str trim)' } }
~~~
