### ISSUE TITLE
Panic when table has too many columns

### ISSUE THREAD

**Issue by bailey-layzer** [nushell/nushell#2799]
**Describe the bug**
Nu panics when a table with many columns is `autoview`ed. From the trace, it looks like the problem arises [here](https://github.com/nushell/nushell/blob/main/crates/nu-table/src/table.rs#L998) when the terminal width is less than 3* the number of columns.

**To Reproduce**
- I encountered this with `echo $nu.env`.
- `open test.csv` also reproduces if the csv has enough columns.

**Expected behavior**
I'm honestly not sure how I would a 100-column row should be displayed (either in terms of usability or Nu's existing design) - has this come up already? I guess a one-row table like `$nu.env` could be displayed vertically (or switch to vertical after some threshold).

**Configuration (please complete the following information):**
 - OS: Linux
 - Nu version: 0.24.2 (0b5ab1ef22ee7d6b6a73a3007cc3c055fb938168)
 - Optional features (if any): "extra"

**Comment by bailey-layzer** [comment]
(now seeing this overlaps with #389)

**Comment by jonathandturner** [comment]
I'm happy to mentor anyone working on this
