### ISSUE TITLE
Parallel Process Pipes with Fan In and Fan Out Patterns

### ISSUE THREAD

**Issue by sirinath** [nushell/nushell#2811]
**Is your feature request related to a problem? Please describe.**
In comparison to [NextFlow](https://www.nextflow.io/) pipelines in NuShell can improve.

**Describe the solution you'd like**
Can we have [NextFlow](https://www.nextflow.io/) like functionality especially when NuShell scripting arrives. Also scripting should have best possible compiling and JITing functionality for performance.

**Describe alternatives you've considered**
[NextFlow](https://www.nextflow.io/)

**Additional context**
[NextFlow](https://www.nextflow.io/)

**Comment by fdncred** [comment]
Can you please explain in more detail what `NextFlow like functionality` you're looking for is? i.e. what doesn't work the way you want it to?

**Comment by sirinath** [comment]
> Can you please explain in more detail what NextFlow like functionality you're looking for is? i.e. what doesn't work the way you want it to?
- Ability to specify input streams/channels/pipes of a process
- Ability specify output streams/channels/pipes of a process
- Ability to define filters on streams/channels/pipes
- Ability to specify the connections between input and output streams/channels/pipes to create a computational dataflow graph of processors (DAG) which pipe the input and outputs into one another as  component which can be combined to create larger process graphs
- Ability to have fan-in fan-out streams/channels/pipes
- Ability to combine streams/channels/pipes based on combining logic
- Ability define filters on streams/channels/pipes
- Ability define calculations and expressions on streams/channels/pipes
- Ability to schedule schedule these computational graphs for execution
