### ISSUE TITLE
autoview printing order

### ISSUE THREAD

**Issue by Maan2003** [nushell/nushell#2816]
**Describe the bug**
The autoview doesn't print correctly 

**To Reproduce**
1. `echo 1 | autoview; ^echo external`
2. `echo [1, 2, 3] | each { echo $it | autoview; }`

**Current behavior**

1.
```
external
1
```
2. 
```
123
```

**Expected behavior**

1.
```
1
external
```

2. 
```
1
2
3
```
**Configuration:**
| Column0            | Column1                                                                                                                       |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.24.1                                                                                                                        |
| branch             | HEAD                                                                                                                          |
| short_commit       | 5183fd25                                                                                                                      |
| commit_hash        | 5183fd25bb8e96261271740df641ff79d583a098                                                                                      |
| commit_date        | 2020-12-15T20:13:18+00:00                                                                                                     |
| build_os           | windows-x86_64                                                                                                                |
| rust_version       | rustc 1.48.0 (7eac88abb 2020-11-16)                                                                                           |
| rust_channel       | stable-x86_64-pc-windows-msvc (default)                                                                                       |
| cargo_version      | cargo 1.48.0 (65cbdd2dc 2020-10-14)                                                                                           |
| pkg_version        | 0.24.1                                                                                                                        |
| build_time         | 2020-12-15 20:30:18                                                                                                           |
| build_rust_channel | release                                                                                                                       |
| features           | clipboard-cli, ctrlc, default, directories, dirs, git, ichwh, ptree, rich-benchmark, rustyline, term, trash, uuid, which, zip |

**Comment by jonathandturner** [comment]
With the latest, I'm seeing much closer to the expected example (though `123` since there's no carriage returns between the values)

Going ahead and closing as I think the root of the issue has been fixed.
