### ISSUE TITLE
Regular expression, possibly glob, and more binary comparison operator support.

### ISSUE THREAD

**Issue by andrasio** [nushell/nushell#282]
We've worked on globs and regular expressions in commands (`ls`, `cp`, etc) and plugins (`str`) and also the case for filesystem related use cases such as working with paths (`Path`/`PathBuf`).

Nu supports parsing and supplying Path types in command signatures out of the box. We should consider supporting globs and regular expressions at `hir` level. 

Also adding syntax and refer to regular expressions like `/wy(.*)/` (Ruby does this) and Nu supplying us `Regex`s constructed in signatures. Binary comparison operators support (`=~` and `!=~`) for matching regexes too.

With these additions we can do something like these:

`ps | where name =~ /nu_plugin_(.*)/`
 `ls | where name =~ /pattern/`

/ref @jonathandturner @wycats

**Comment by jonathandturner** [comment]
@androbtech - We have some ideas about possibly matching without using regular expressions. Or, rather, that there might be a simpler solution for the 90% case.

Here's one idea:

Say you had an input file of:

```
Jonathan Turner lives in New Zealand
Yehuda Katz lives in USA
Andrés Robalino lives in Ecuador
```
(etc)

You could parse that a few ways, including with a regex. I was wondering if one way to handle it works less with a regex and more with what you know about the string. Something like this:

```
parse FirstName " " LastName " lives in " Location
```

We could also pass in a flag that allowed you to get both the matches as new Values as well as the unmatched rows.

**Comment by androbtech** [comment]
For that `match` command that you were talking about before. Right!

**Comment by jonathandturner** [comment]
we'll need something like that, but not sure what quite yet

**Comment by wycats** [comment]
I showed nu to @wifelette and she suggested `=~` for stuff like `ls | where title =~ whatever`. :+1:

**Comment by howdoicomputer** [comment]
That'd be cool. Right now `ls | grep` doesn't seem to work as expected.

**Comment by andrasio** [comment]
#900

**Comment by jonathandturner** [comment]
We have a few forms of this, so going ahead and closing this as complete now.
