### ISSUE TITLE
nu calling external commands first sometimes?

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2822]
**Describe the bug**
while testing an alias named `reset` I noticed that `alias reset = echo $(ansi -e '0m')` seemed be ignored and nu was calling `/usr/bin/reset` on my mac. I updated my alias to `alias reset = ansi -e '0m'` and did `echo $(reset)` and it still seems to be calling the external command.

**Expected behavior**
call internal commands/aliases/custom commands first

|key|value|
|-|-|
|version|0.24.2|
|branch|main|
|short_commit|d2a00a2d|
|commit_hash|'d2a00a2daa1d0ddf0f6b3ef4c6f5be6a23c760c6'|
|commit_date|2020-12-23T16:56:05+00:00|
|build_os|macos-x86_64|
|rust_version|rustc 1.48.0 (7eac88abb 2020-11-16)|
|rust_channel|stable (default)|
|cargo_version|cargo 1.48.0 (65cbdd2dc 2020-10-14)|
|pkg_version|0.24.2|
|build_time|2020-12-25 14:44:55|
|build_rust_channel|debug|
|features|ctrlc, default, directories, dirs, git, ichwh, ptree, rich-benchmark, rustyline, term, uuid, which, zip|

**Comment by LhKipp** [comment]
I tested this on the main branch under Linux. I don't have this faulty behavior.

```shell
/home/leo/repos/nushell(main)> reset -V
ncurses 6.2.20200212
/home/leo/repos/nushell(main)> alias reset = echo
/home/leo/repos/nushell(main)> reset hi
hi
/home/leo/repos/nushell(main)> echo $(reset hi)
hi
/home/leo/repos/nushell(main)> 
```
