### ISSUE TITLE
aliases with an invocation $() breaks coloring

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2823]
**Describe the bug**
aliases with an invocation $() seem to break the coloring

**To Reproduce**
1. try using the coloring aliases in the details section below to color things.
2.
3.

Here's a bunch of aliases that I've been working on. Don't assume this script is correct but it seemed to help find this problem

<details>

#### found here https://github.com/PowerShell/PowerShell/blob/5f3dd938b792e1a395fd011ac1461246db7c0e1f/src/System.Management.Automation/FormatAndOutput/common/PSStyle.cs

alias formatting.format_accent = echo $(ansi -e '32;1m')
alias formatting.error_accent = echo $(ansi -e '36;1m')
alias formatting.error = echo $(ansi -e '31;1m')
alias formatting.warning = echo $(ansi -e '33;1m')
alias formatting.verbose = echo $(ansi -e '33;1m')
alias formatting.debug = echo $(ansi -e '33;1m')

alias reset = ansi -e '0m'
alias blink_off = echo $(ansi -e '25m')
alias blink = echo $(ansi -e '5m')
alias bold_off = echo $(ansi -e '22m')
alias bold = echo $(ansi -e '1m')
alias hidden = echo $(ansi -e '8m')
alias hidden_off = echo $(ansi -e '28m')
alias reverse = echo $(ansi -e '7m')
alias reverse_off = echo $(ansi -e '27m')
alias italic_off = echo $(ansi -e '23m')
alias italic = echo $(ansi -e '3m')
alias underline_off = echo $(ansi -e '24m')
alias underline = echo $(ansi -e '4m')
alias strikethrough_off = echo $(ansi -e '29m')
alias strikethrough = echo $(ansi -e '9m')

#### this doesn't work right. i need to have an $(ansi escape) defined but i don't think there is one
def format_hyperlink [link text] {echo [$(ansi -o '8;;') $link '\' $text $(ansi -o '8;;') '\'] | str collect }

alias foreground.black = echo $(ansi -e '30m')
alias foreground.blue = echo $(ansi -e '34m')
alias foreground.cyan = echo $(ansi -e '36m')
alias foreground.darkgray = echo $(ansi -e '90m')
alias foreground.green = echo $(ansi -e '32m')
alias foreground.lightblue = echo $(ansi -e '94m')
alias foreground.lightcyan = echo $(ansi -e '96m')
alias foreground.lightgray = echo $(ansi -e '97m')
alias foreground.lightgreen = echo $(ansi -e '92m')
alias foreground.lightmagenta = echo $(ansi -e '95m')
alias foreground.lightred = echo $(ansi -e '91m')
alias foreground.lightyellow = echo $(ansi -e '93m')
alias foreground.magenta = echo $(ansi -e '35m')
alias foreground.red = echo $(ansi -e '31m')
alias foreground.white = echo $(ansi -e '37m')
alias foreground.yellow = echo $(ansi -e '33m')
def foreground.from_rgb [red green blue] { echo [$(ansi -e '38;2;') $red ';' $green ';' $blue 'm;'] | str collect }

alias background.black = echo $(ansi -e '40m')
alias background.blue = echo $(ansi -e '44m')
alias background.cyan = echo $(ansi -e '46m')
alias background.dark_gray = echo $(ansi -e '100m')
alias background.green = echo $(ansi -e '42m')
alias background.light_blue = echo $(ansi -e '104m')
alias background.light_cyan = echo $(ansi -e '106m')
alias background.light_gray = echo $(ansi -e '107m')
alias background.light_green = echo $(ansi -e '102m')
alias background.light_magenta = echo $(ansi -e '105m')
alias background.light_purple = echo $(ansi -e '105m')
alias background.light_red = echo $(ansi -e '101m')
alias background.light_yellow = echo $(ansi -e '103m')
alias background.magenta = echo $(ansi -e '45m')
alias background.purple = echo $(ansi -e '45m')
alias background.red = echo $(ansi -e '41m')
alias background.white = echo $(ansi -e '47m')
alias background.yellow = echo $(ansi -e '43m')
def background.from_rgb [red green blue] { echo [$(ansi -e '48;2;') $red ';' $green ';' $blue 'm;'] | str collect }
</details>

**Configuration (please complete the following information):**

|key|value|
|-|-|
|version|0.24.2|
|branch|main|
|short_commit|d2a00a2d|
|commit_hash|'d2a00a2daa1d0ddf0f6b3ef4c6f5be6a23c760c6'|
|commit_date|2020-12-23T16:56:05+00:00|
|build_os|macos-x86_64|
|rust_version|rustc 1.48.0 (7eac88abb 2020-11-16)|
|rust_channel|stable (default)|
|cargo_version|cargo 1.48.0 (65cbdd2dc 2020-10-14)|
|pkg_version|0.24.2|
|build_time|2020-12-25 14:44:55|
|build_rust_channel|debug|
|features|ctrlc, default, directories, dirs, git, ichwh, ptree, rich-benchmark, rustyline, term, uuid, which, zip|

**Comment by ehawman-rosenberg** [comment]
Wanted to chime in here.

`ls -a | sort-by type` will produce a nice list with color highlights.

`alias la = (ls -a | sort-by type)`, when called, will produce a plain white list.

Is this the same issue you're experiencing?

OS: Windows 10
Terminal: Windows Terminal Preview
Nu Version: 0.63.0

**Comment by fdncred** [comment]
I think that's different than this issue but it annoys me that aliases like you mention don't allow ls_colors. I'm not sure what the fix is either.
