### ISSUE TITLE
Question — Is it possible to use Ctrl-e instead of right arrow-key when selecting a suggestion?

### ISSUE THREAD

**Issue by khadegd** [nushell/nushell#2825]
When I type `cd`, the `nushell` suggests a path, to select the suggestion I can't use <kbd>Ctrl</kbd>-<kbd>e</kbd> like fish/zsh. I got to press <kbd>→</kbd> right arrow key. Is there a way to remap it to <kbd>Ctrl</kbd>-<kbd>e</kbd>?

**Comment by fdncred** [comment]
hi @khadegd ! you can experiment with [keybindings](https://github.com/nushell/nushell/blob/main/docs/sample_config/keybindings.yml) and see if you can get that to work.

**Comment by khadegd** [comment]
Thanks @fdncred.

**Comment by fdncred** [comment]
@khadegd did you get it working the way you want?
