### ISSUE TITLE
Extensive Configurable Context Dependent Colour Use In Output

### ISSUE THREAD

**Issue by sirinath** [nushell/nushell#2838]
Can context dependent colour coding can be used for better visual recognition like:

![image](https://user-images.githubusercontent.com/637415/103434696-fbb1c100-4c2a-11eb-80e2-9148cadf906b.png)

Souece: https://the.exa.website/

**Comment by fdncred** [comment]
@sirinath That's what [this PR](https://github.com/nushell/nushell/pull/2826) is about. It reads the `LS_COLORS` environment variable and colors the output appropriately. There's some things we're still working on with it.

Also, similar to exa, we color primitives if it's configured in the `config.toml` file.

**Comment by sirinath** [comment]
Can this be extended beyond `ls` where any command's colour can be configured.

**Comment by fdncred** [comment]
any command right now that outputs primitives in a table currently supports coloring. is there something else you're suggesting?

**Comment by sirinath** [comment]
I have the same thing in mind but not limited to tables.

Also, the **latency** and **efficiency** in applying the colours. E.g.
- built in commands can have metadata tags of some sort to make it efficient to apply the colours than re-parsing the output where possible
- un-ported commands may need the output parsed until tags and meta data is added or 3rd party commands and programs

**Comment by fdncred** [comment]
i think we're up for latency and efficiency in applying colors via tags. personally, i have noticed some lag in drawing with `ls` colors. tbh, i've been thinking about standardizing on the `colored` or `recolored` crate for coloring and making the colors more unified throughout the system. so, i'd welcome a pr that starts to do things like that.

**Comment by sirinath** [comment]
Unified colors and a framework to apply colours would be desirable but using `colored` or `recolored` will introduce a MPL dependency.

**Comment by fdncred** [comment]
We could also `roll-our-own` ansi coloring functionality with something similar to [this implementation](https://github.com/redox-os/ion/blob/935811eafdd0436acc5f6981d1fef20076c54c5c/src/lib/shell/colors.rs) that I was looking at the other day.
