### ISSUE TITLE
Equivalent to linux "find" commmand?

### ISSUE THREAD

**Issue by medakk** [nushell/nushell#2840]
**Is your feature request related to a problem? Please describe.**

It'd be nice to use the streaming commands on arbitrary files rooted under a subdirectory, like GNU [find](https://man7.org/linux/man-pages/man1/find.1.html) returns

**Describe the solution you'd like**

Something like how `ls` is implemented currently, but with the ability to recurse through subdirectories

**Comment by fdncred** [comment]
do you mean, and have you tried, `ls **/*`?

**Comment by medakk** [comment]
That's perfect. Thank you!
