### ISSUE TITLE
Allowing terminal customization

### ISSUE THREAD

**Issue by Azgrom** [nushell/nushell#2843]
On Manjaro Linux distributions we have the command pattern on terminal:
 -  `[rafael@I-7590 ~]$`: for the `~/` path;
 - `[rafael@I-7590 nushell]$`: for any absolute path where the current `nutshell/` directory finds itself.

In this terminal, if a user has a virtual environment activated it looks like: `(<venv name>) [rafael@I-7590 nushell]$`

With some shell scripts functions it's possible for the user to make a local repository branch's name to appear before the square brackets. So it looks like: `(<venv name>) (main) [rafael@I-7590 nushell]$`, with profile styled colors.

So I wonder if it is interesting for the project to allow customization on how the _current_ _directory_, _user_ and _hostname_ is presented. Even with a 2560x1440 screen resolution and font sized at 9pt I find too verbose having an absolute directory path sharing space with an also relatively long terminal command on nushell.

>  Note: This suggestion is about providing a way for the user to define the terminal presentation anyway he/she likes. The example above is simply how I consider to be a concise, an yet informative, presentation.

**Comment by fdncred** [comment]
@Azgrom Nushell provides the ability for a user to customize their prompt by setting the `prompt` inside of the `config.toml` file. 

For instance, mine prints the weather like this `/Users/fdncred/Downloads/rust/forks/nushell<main> (40.3 °F ☁️ ) ▶` where main is in cyan, the path is in green the weather is gathered by calling custom commands.  

There's an abbreviated one that I used to use. I have it defined like this in the `[startup]` section of my `config.toml`: `"def get_abbrev_pwd_lin [] {echo [$(pwd | split row '/' | first $(pwd | split row '/' | count | each {= $it - 1} ) | each { str substring '0,1' | format '{$it}/' } | append $(pwd | split row '/' | last ) | str collect)] | str collect}",` and it prints the same path above like this `U/f/D/r/f/nushell`.

So, there are a few was to customize the prompt right now. Does this information help?

**Comment by Azgrom** [comment]
I see... Thank you, this information helps.
