### ISSUE TITLE
Gentoo ebuild packaging

### ISSUE THREAD

**Issue by Woomymy** [nushell/nushell#2845]
Hello, I'm sorry if this issue isn't classed correctly but i don't think it's a feature request / a bug report. I have recently created two gentoo ebuilds (packages) a source package that builds nu and installs it and a binary package that gets a github release and installs it in /usr/bin/nu. These packages are located [in my own overlay](https://github.com/Woomy4680-exe/woomy-overlay/tree/master/app-shells). Can these be added in the nu's readme for gentoo users ? Must i create another overlay (called nushell-overlay for example). Regards, Woomy

**Comment by Woomy4680-exe** [comment]
Just packed 0.25.1 and marked as stable!

**Comment by fdncred** [comment]
Thanks for building a package for gentoo users. We appreciate the help.

**Comment by Woomymy** [comment]
Woops. I forgot to close it when I saw that nu is now in official three. Thanks !
