### ISSUE TITLE
`source`ing inside of a block doesn't set up block

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2852]
**Describe the bug**
If you run `source` from inside of a block, it doesn't appear to properly source into that block.

Here's an example run that fails:

```
/home/jonathan/Source/nushell(main)> do { source fixedme.nu; breakme 100 }
error: Command not found
  ┌─ shell:5:25
  │
5 │ do { source fixedme.nu; breakme 100 }
  │                         ^^^^^^^ command not found

10
/home/jonathan/Source/nushell(main)> cat fixedme.nu
def breakme [x] {
  def ohno [y] {
    echo $y
  }
  ohno $x
}
breakme 10
```

**To Reproduce**
1. See above

**Expected behavior**
The above should run without error

Latest main

**Comment by jonathandturner** [comment]
Realizing this might be correct to the current implementation, as we parse `breakme` first, before we run `source fixedme.nu`.  Still, I'm not sure it feels correct.

**Comment by jonathandturner** [comment]
You can also repro using a simpler:

```
> source fixedme.nu; breakme 100
```

Notice how keeping it on the same line gives the error, where as breaking them up over two lines succeeds

**Comment by fdncred** [comment]
maybe semi-colon should be treated like newline so that it succeeds on one line?

**Comment by jonathandturner** [comment]
It's not that so much as the parser needs to be able to do the work of `source`, so that any command it parses after that point can see the definitions. I've got a hacky workaround here for now: https://github.com/nushell/nushell/pull/2855
