### ISSUE TITLE
Custom prompt errors running a binary

### ISSUE THREAD

**Issue by cdhunt** [nushell/nushell#2863]
**Describe the bug**
With v0.25 the prompt errors running a binary until I manually invoke it.

**To Reproduce**
1. Custom prompt config that calls out to an exe

**Expected behavior**
In <0.25 the prompt immediately rendered when opening launching nu.

**Screenshots**

![image](https://user-images.githubusercontent.com/114173/103697908-959ca500-4f6e-11eb-99b8-c5520c658faf.png)

**Configuration (please complete the following information):**

```
> config get prompt
echo $(oh-my-posh -config c:\Users\chunt\.ohmyposh-lite.json)
```

**Comment by corbinu** [comment]
I am seeing this exact same problem with starting starship in both Mac OS and Ubuntu

**Comment by corbinu** [comment]
Related: https://github.com/nushell/nushell/issues/2873

**Comment by corbinu** [comment]
This has been fixed and can be closed

**Comment by jonathandturner** [comment]
@corbinu - thanks!
