### ISSUE TITLE
Disable startup when invoking nu scripts (non-interactive)

### ISSUE THREAD

**Issue by rrichardson** [nushell/nushell#2864]
It is a little bit surprising that the `startup` script in the config is executed when I invoke `nu mytest.nu`  

This is probably the default behavior for shells, but it might be nice to offer the option, since I expect that many people would like to use nu as an interpreted scripting language. 

I am thinking it might be nice to default to disable startup when the user supplies a script as an argument to `nu`.  Then it could offer a flag that would let a person enable the startup script under such conditions if they so chose.

**Comment by sirxyzzy** [comment]
This clobbered me when I tried to run a nushell script, from within in my startup, this behavior caused launch to hang, as it went recursive on me, I was able to ctrl c out after I noticed dozens of nu processes had been spawned :-)

**Comment by sirxyzzy** [comment]
@rrichardson I was able to use "source" instead, does that help?
