### ISSUE TITLE
Build break with latest 'syn'?

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#2867]
Looks like this issue *may* be caused by a breaking change in a semver-compatible version of `syn`.

```
error[E0432]: unresolved import `syn::export`
 --> C:\Users\joturner\.cargo\registry\src\github.com-1ecc6299db9ec823\rust-embed-impl-5.7.0\src\lib.rs:8:11
  |
8 | use syn::{export::TokenStream2, Data, DeriveInput, Fields, Lit, Meta};
  |           ^^^^^^ could not find `export` in `syn`
```

cc @dtolnay

**Comment by wonderfulspam** [comment]
Possibly caused by this commit? https://github.com/dtolnay/syn/commit/957840eba2c7f11c95e0227760d78dc481a91de7

**Comment by wonderfulspam** [comment]
By extension, the fix in [`rust_embed_impl`](https://github.com/pyros2097/rust-embed/blob/master/impl/src/lib.rs) might be something along the lines of

```diff
use proc_macro::TokenStream;
+use proc_macro2::TokenStream as TokenStream2;
use std::{env, path::Path};
-use syn::{export::TokenStream2, Data, DeriveInput, Fields, Lit, Meta};
+use syn::{Data, DeriveInput, Fields, Lit, Meta};
```

**Comment by jonathandturner** [comment]
Great, thanks for investigating.

We'll pin to the older `syn` for now, and we can remove that pin once other crates catch up.

**Comment by jonathandturner** [comment]
Closing, as we're working around this issue with https://github.com/nushell/nushell/pull/2868
