### ISSUE TITLE
config set booleans

### ISSUE THREAD

**Issue by aeosynth** [nushell/nushell#2869]
I tried to disable the welcome message with `config set skip_welcome_message true`, but this didn't work; it added `"true"` as a string, and I had to edit the config file to change it to the `true` boolean. I looked at the config docs but they didn't help.

It should be possible and clear how to set booleans using `config set`.

nu 0.25.0

**Comment by jonathandturner** [comment]
Can you try using `$true` and `$false`?

We need to document these a bit better.

**Comment by aeosynth** [comment]
using `$true` works, thanks

> We need to document these a bit better.

yes, an example in the config page would help
