### ISSUE TITLE
Vi Mode Improvements

### ISSUE THREAD

**Issue by EntilZha** [nushell/nushell#2878]
The Vi mode support seems to rely on rustyline which unfortunately doesn't have support for visual mode https://github.com/kkawakam/rustyline/issues/335 and in general I'm finding vi mode a bit confusing coming from Fish shell.

For example, if I have typed `test0 test1 test2`, I'd expect something like `esc 0` to put my cursor on the start of the line and `ciw` to delete `test0` and put my cursor on the line. Instead, it seems like it enters are mode where the line becomes:
1. esc, nothing happens
2. Hit 0, and this shows up `(arg: 0) test0 test1 test2`
3. Typing more text puts it at the end of the line.

**Describe the solution you'd like**
It would be great to take a look at VI mode and see what can be done to make it work more comparably to the way that fish handles VI mode. It would be great if it works for simple cases like above and there were a bit more clarity about modes/etc

Thanks!

**Comment by mightyiam** [comment]
I'm a little confused. I'm not sure what to expect from vi mode. I set `edit_mode` to `"vi"` and I'm not sure I see a difference in behavior.

**Comment by smweber** [comment]
I’m seeing the same thing. I’m new to nushell, but it seems that setting `edit_mode` to `”vi”` doesn’t seem to actually change the shell to a vi mode - emacs style commands continue to work and `esc` does nothing. It seems that vi mode has worked in the past, so I’m guessing this might be a regression?

**Comment by jonathandturner** [comment]
Once you set the mode, you should see the change once you restart nushell.

The setting has moved over the last few months, I believe.

If you're using the latest setting (https://www.nushell.sh/book/configuration.html#line-editor-section) and you've restarted and still don't see it, definitely let us know.

**Comment by smweber** [comment]
I believe I've set the correct config setting, and I've restarted nu:
```
sweber@M1-Mini ~ % nu
Welcome to Nushell 0.27.1 (type 'help' for more info)
/Users/sweber> config
───┬───────────
 # │ edit_mode 
───┼───────────
 0 │ vi        
───┴───────────
```
But I'm still not seeing any vi behaviour. I installed nu from cargo just today if that makes any difference. Thanks for looking into this!

**Comment by jonathandturner** [comment]
@smweber - you need to put that setting in the [line_editor] section

**Comment by smweber** [comment]
Yup, that was the problem. I was using `config set edit_mode "vi"`, which I must have inferred from old docs. Thanks for the help!

**Comment by MatrixManAtYrService** [comment]
Vi mode isn't bad as-is, I've definitely used worse.  Support for `ciw`, `caw`, `diw`, and `daw` would be pretty cool.  So would visual mode, but I guess that's tricky.

One related thing that I've used elsewhere (and it might already exist in nushell--I'm not sure what to search for) is a keybind that just opens the current command in $EDITOR.  From there you can use whatever unsupported voodoo you like.  Then you save the file and its contents are placed in your command buffer.

**Comment by MatrixManAtYrService** [comment]
I ran across a case today where I wanted `o`, `O`, and `J` support.  If you paste something like:

```
(foo
baz)
```

You need `o` or `O` to change it to this
```
(foo
bar
baz)
```


And you need `J` to change it to this (backspacing the newline doesn't work, although deleting it is an option)
```
(foo baz)
```

**Comment by MatrixManAtYrService** [comment]
`gg` and `G` are pretty important.  Without them, if you're editing multiline commands, you may end up pressing the up-arrow one too many times.  This takes you to the previous item in history, fine.  Then you press the down arrow, because oops you went too far, and instead of returning you to the top line of the command you were editing, you zip to the bottom line, which is pretty jarring.

Initially I thought this was a bug, but it's probably desirable behavior because it lets you keep down-arrowing through multi-line commands without having to down-arrow through each line of each one.  nushell vi mode matches zsh vi mode in this way.

I never had this problem with zsh, but that's only because zsh line mode supports `gg` and `G`.

**Comment by jaredmontoya** [comment]
@MatrixManAtYrService 

```nushell
                {
                  name: insert_newline
                  modifier: shift
                  keycode: enter
                  mode: [emacs, vi_normal, vi_insert]
                  event: { edit: insertnewline }
                }
```
