### ISSUE TITLE
No way to execute a `find -exec` command?

### ISSUE THREAD

**Issue by Ryan-McLemon** [nushell/nushell#2882]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to execute something like this:
```
find . -type d -maxdepth 1 -exec cd {} && cd .. \;
```

**Describe the solution you'd like**
This command would execute without the following error:
```
find: -exec: no terminating ";" or "+"
```

**Describe alternatives you've considered**
For now you can wrap this in `bash -c ""`.

**Comment by jonathandturner** [comment]
I'm wondering if this is parser-related or something else. Can you try:

```
find . -type d -maxdepth 1 -exec 'cd {} && cd .. \;'
```

Or is the `&&` separating two separate commands?

If so, in Nushell we use `;` to mean what Bash uses `&&` for.

**Comment by Ryan-McLemon** [comment]
@jonathandturner, some variations:
```
λ find . -type d -maxdepth 1 -exec 'cd {} && cd .. \;'
find: -exec: no terminating ";" or "+" 

λ find . -type d -maxdepth 1 -exec 'cd {} && cd .. \;';
find: -exec: no terminating ";" or "+" 

λ find . -type d -maxdepth 1 -exec 'cd {} && cd .. \;';;
find: -exec: no terminating ";" or "+" 

λ find . -type d -maxdepth 1 -exec 'cd {} && cd .. \;'\;
find: -exec: no terminating ";" or "+" 

λ find . -type d -maxdepth 1 -exec 'cd {} && cd .. \;'\+;
find: -exec: no terminating ";" or "+" 

λ find . -type d -maxdepth 1 -exec 'cd {} && cd .. \;'+;
find: -exec: no terminating ";" or "+" 

λ find . -type d -maxdepth 1 -exec 'cd {} && cd .. \;'+\;
find: -exec: no terminating ";" or "+" 

λ find . -type d -maxdepth 1 -exec 'cd {} \;'+\;
find: -exec: no terminating ";" or "+" 

λ find . -type d -maxdepth 1 -exec 'cd {} \;';
find: -exec: no terminating ";" or "+" 

λ find . -type d -maxdepth 1 -exec 'cd {} \;'
find: -exec: no terminating ";" or "+" 

λ find . -type d -maxdepth 1 -exec 'cd {} \;'+
find: -exec: no terminating ";" or "+" 

λ find . -type d -maxdepth 1 -exec 'cd {} \;'+;
find: -exec: no terminating ";" or "+"
```

**Comment by fdncred** [comment]
Granted, this is different but does it help?

```
find -maxdepth 1 -type d -exec file '{}' ';'
.: directory
./docker: directory
./.azure: directory
./src: directory
./.circleci: directory
./tests: directory
./wix: directory
./.git: directory
./docs: directory
./.cargo: directory
./.theia: directory
./.github: directory
./crates: directory
./pkg_mgrs: directory
./samples: directory
./target: directory
./.vscode: directory
./images: directory
./debian: directory
```

`> lsb_release -a`
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy

**Comment by jonathandturner** [comment]
Ahh that could be it. The final `;` needs to be quoted because semi-colon is reserved for Nushell as a separator of pipelines.

**Comment by fdncred** [comment]
It seems like this should work too
```
find -maxdepth 1 -type d | each { cd $it; sleep 1sec; cd .. }
```
but i'm getting
```
error: Cannot change to directory
   ┌─ shell:13:38
   │
13 │ find -maxdepth 1 -type d | each { cd $it; sleep 1sec; cd .. }
   │                                      ^^^ directory not found
```

**Comment by Ryan-McLemon** [comment]
@fdncred I think that is because `find` isn't returning structured data:
```
λ find . -maxdepth 1 -type d | each { echo $it }
.
./foo
./bar
```

**Comment by jonathandturner** [comment]
@Ryan-McLemon you may need to trim the carriage return off the output from `find`.

`find -maxdepth 1 -type d | str trim | each { cd $it; sleep 1sec; cd .. }`

just guessing

**Comment by jonathandturner** [comment]
oh I see what it is. If you wan to do each line:

```
find -maxdepth 1 -type d | lines | each { cd $it; sleep 1sec; cd .. }
```

**Comment by fdncred** [comment]
@Ryan-McLemon  right, external commands don't necessarily return structured data but that doesn't mean nushell can't use it. afterall, if you are in nushell and do `cd ./foo` it works , right?

@jonathandturner 
```
find -maxdepth 1 -type d | str trim | each { cd $it; sleep 1sec; cd .. }
error: Cannot change to directory
   ┌─ shell:19:49
   │
19 │ find -maxdepth 1 -type d | str trim | each { cd $it; sleep 1sec; cd .. }
   │
```
This doesn't error out
```
find -maxdepth 1 -type d | str trim | each { echo $it | cd; sleep 1sec; cd .. }
```

```
find -maxdepth 1 -type d | lines | str trim | each { cd $it; sleep 1sec; cd .. }
error: Cannot change to directory
   ┌─ shell:25:57
   │
25 │ find -maxdepth 1 -type d | lines | str trim | each { cd $it; sleep 1sec; cd .. }
   │                                                         ^^^ directory not found
```

**Comment by jonathandturner** [comment]
I found an issue that was causing my suggestion from working, will try to put up a PR soon.

**Comment by jonathandturner** [comment]
Fixed the issue with `lines` here: https://github.com/nushell/nushell/pull/2887

You should be able to pipe through `lines` then `each` and use the result now. 

Something to keep in mind: `each { cd $it; cd .. }` won't work if one of the directories you work on is `.`. For that directory, for the `cd ..` step you'll end up in your home directory.

One way to work around this is to use `enter` instead:

`your command | lines | each { enter $it; exit }` will do a similar thing but will also work if you pass in the current directory.

**Comment by Ryan-McLemon** [comment]
Thank you @jonathandturner!
