### ISSUE TITLE
Some kind of iteration structure (like a Bash `for`)?

### ISSUE THREAD

**Issue by Ryan-McLemon** [nushell/nushell#2883]
**Is your feature request related to a problem? Please describe.**
Is there any way to do a simple `for` loop in nushell? I can't find anything.

**Describe the solution you'd like**
Some way to do a `for` loop or some other kind of iteration method.

**Describe alternatives you've considered**
For now I guess you can just do a `bash -c ""` for whatever command you want, but that is no fun.

**Comment by jonathandturner** [comment]
Depends on the kind of loop, but here are a few examples:

```
ls | each { echo $it.name }
```

```
echo 1..10 | each { echo $it }
```

```
echo [1, 2, 3, 4, 5] | each { echo $it }
```

**Comment by Ryan-McLemon** [comment]
Oh! @jonathandturner you are a lifesaver!
```
ls | each { cd $it.name; git pull --all; cd .. }
```

I know in the old Bash world, using `ls` for looping was frowned upon (people often preferred `find`), does nushell have these same caveats?

**Comment by fdncred** [comment]
There's also `seq` like:
```
seq 1 10 | each { echo $it }
```
and `seq date` if you want to iterate on dates

**Comment by Ryan-McLemon** [comment]
Is there a way to get the docs search tagged for `loop` or `iteration` so that users can find `each` more easily?

<img width="234" alt="Screen Shot 2021-01-07 at 9 52 29 AM" src="https://user-images.githubusercontent.com/76971348/103926731-29d14e00-50ce-11eb-92b8-0482107fda94.png">
<img width="240" alt="Screen Shot 2021-01-07 at 9 52 35 AM" src="https://user-images.githubusercontent.com/76971348/103926733-2a69e480-50ce-11eb-8671-d39510745ad2.png">

`for` might also be useful as a 'tag' for that search, although that is such a generic word ...

**Comment by Ryan-McLemon** [comment]
Is there a way to get only directories with `ls`?

**Comment by jonathandturner** [comment]
yeah, that'd be a great fix for the docs. would you mind adding an issue to https://github.com/nushell/nushell.github.io?

and no hangups with using any command for iteration. Nu sees the output all the same (it's the same kind of structured data)

If you want only dirs from ls you can do `ls | where type == Dir`

**Comment by Ryan-McLemon** [comment]
Issue created!
https://github.com/nushell/nushell.github.io/issues/84

Thank you @jonathandturner and @fdncred!

**Comment by Ryan-McLemon** [comment]
@jonathandturner or @fdncred any reason why this `echo` wouldn't work?

```
 ls ~/code | where type == Dir | each { cd $it.name; echo $it.name; git pull --all; cd .. }
```
```
Already up to date.
Fetching origin
Already up to date.
Fetching origin
Already up to date.
Fetching origin
Already up to date.
Fetching origin
Already up to date.
```

**Comment by fdncred** [comment]
@Ryan-McLemon if you have `;` in your statements then only the last one gets to output things. So, since your `echo $it.name` is in the middle you'd need to change it to `echo $it.name | autovew;`

**Comment by Ryan-McLemon** [comment]
Fantastic. Thank you for answering all my questions @fdncred and @jonathandturner! This is why Nushell is the truth!

**Comment by Ryan-McLemon** [comment]
@fdncred, I don't seem to have that command ...

```
 ls ~/code | where type == Dir | each { cd $it.name; echo $it.name | autovew; git branch; git pull --all; cd ~/code };
  │                                                                                                               ^^^^^^^ command not found
```

**Comment by fdncred** [comment]
I'm not sure which command it's complaining about. I just did this and it seemed to work.
```
ls | where type == Dir | each { cd $it.name; echo [$it.name $(char newline)] | str collect | autoview; cd ~/src/forks/nushell}
crates
debian
docker
docs
images
pkg_mgrs
samples
src
target
tests
wix
```

**Comment by Ryan-McLemon** [comment]
Ah, typo here `autovew` vs. `autoview`. One oddity is that `autoview` moves all that output to the end:

```
ls ~/code | where type == Dir | each { cd $it.name; echo $it.name | autoview; git branch; git pull --all; cd ~/code };
Fetching origin
Already up to date.
* master
Fetching origin
Already up to date.
* master
/code/foo/code/bar
```

**Comment by fdncred** [comment]
@Ryan-McLemon I think this may be a known bug.

**Comment by jonathandturner** [comment]
Here's one of them: https://github.com/nushell/nushell/issues/2816

**Comment by Ryan-McLemon** [comment]
Thanks!

**Comment by codic12** [comment]
Hi, sorry for necrobumping, but is it possible to do an infinite loop in Nu?
In Bash, for example, I can do:
```
while :; do date; done
```
In Nu, I tried:
```
seq date | each { echo $it }
```
But that just prints the date once. The most simple translation would be something like:
```
infiniteloopcommand | each { date now }
```
, but while I don't know what infiniteloopcommand should be, even iterating a fixed number of times:
```
echo 1..10 | each { date now }
```
prints `0 secs ago` each time. I assume that is because Date is a distinct type? If so, how do I view all the fields to get the type I want? TIA!

**Comment by jonathandturner** [comment]
@codic12 - you could do an open-ended range, something like `echo 1.. | each { date now }`

**Comment by codic12** [comment]
Thank you for that, that works perfectly! Still curious why date now prints 0 secs though...

**Comment by jonathandturner** [comment]
@codic12 the `0 secs ago` is trying to give a human readable sense for the date. You can still use it as a date value.

You can see it changing if you do:

```
echo 1..10 | each { date now | debug }
```

You can format it as a string if that's what you're looking for (`date format`)

**Comment by codic12** [comment]
Thanks. However, `date format "%I:%M:%S %p"` seems to output nothing, even outside of a loop... very interesting.

**Comment by jonathandturner** [comment]
@codic12 you need to pass a date value into it. `date now | date format "%I:%M:%S %p"`

**Comment by gongmingbin** [comment]
> @codic12 - you could do an open-ended range, something like `echo 1.. | each { date now }`

but is it possible to `break` for some condition?  or said is that something like `break` in some language that can use in nu?

**Comment by gongmingbin** [comment]
> @codic12 - you could do an open-ended range, something like `echo 1.. | each { date now }`

but is it possible to `break` for some condition?  or said is that something like `break` in some language that can use in nu?
