### ISSUE TITLE
New aliases cannot be made persistent

### ISSUE THREAD

**Issue by yerlaser** [nushell/nushell#2884]
After aliases have been changed in version 0.25 to behave like string expansion there's now no way to make them persistent.
The corresponding option doesn't work any more.
I tried to find the alternative with "help alias", but it gives me an error.
I also tried to put that into startup with:
config set startup "alias dir = exa"
It gets saved as can be seen by "config" command, but after launching a new shell I don't have that alias set.
In general, it seems "config set startup" doesn't work but that is a separate issue.

**Comment by jonathandturner** [comment]
You need to pass an array of strings that you want to run on startup:

```
config set startup ["alias dir = exa"]
```

**Comment by yerlaser** [comment]
That works, thanks.
The issue can be closed then.
I'll see if I can help to contribute in improving documentation.
