### ISSUE TITLE
do -i does not show interactive programs

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#2891]
Tested with Nushell 0.25.1 on Linux. Requires [fzf](https://github.com/junegunn/fzf) installed.

This command works as expected. fzf opens, allows you to select something, and prints the output:
```
do { fzf }
```

However, in this case, fzf opens, but is not visible:
```
do -i { fzf }
```

**Comment by jonathandturner** [comment]
is that true for all interactive programs?

I know some programs use stderr as way of giving you an interactive mode so they can send the answer via stdout (maybe fzf is one of those?)

**Comment by jonathandturner** [comment]
there may be a better way to ignore errors here, just wanted to focus in on what's happening

**Comment by ajeetdsouza** [comment]
Ah, you're right - fzf does use stderr for the interactive mode. I didn't know `do -i` ignored stderr, I'd assumed it was the equivalent of `<command> || true` in Bash (ignoring the exit code).

If this is the case, I'd say Nushell is doing it's job, and doesn't need to handle this separately. Thanks for clarifying!

**Comment by jonathandturner** [comment]
@ajeetdsouza - yeah, we may want to file a separate issue to explore if we want `do -i` to work like the Bash you list so that stderr-style programs do work.
