### ISSUE TITLE
Alias command missing on Windows

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#2896]
**Describe the bug**
The `alias` command seems to be missing on Windows.

**To Reproduce**

1. Install nushell 0.25.1 (either via the MSI or Cargo)
2. Type "alias":
```
> alias
error: Type Error
  ┌─ shell:4:1
  │
4 │ alias
  │ ^^^^^ Expected alias, found alias
```
3. Type "help commands", note that `alias` is missing:
```
> help commands
─────┬──────────────┬────────────────────────────────────────────────────────────────────────────────────┬─────────────────
  #  │     name     │                                    description                                     │   subcommands
─────┼──────────────┼────────────────────────────────────────────────────────────────────────────────────┼─────────────────
   0 │ ansi         │ Output ANSI codes to change color                                                  │
...
```

**Expected behavior**
`alias` should be present and functional.

**Configuration**

```
version | pivot
───┬────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                             Column1
───┼────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.25.1
 1 │ build_os           │ windows-x86_64
 2 │ rust_version       │ rustc 1.49.0 (e1884a8e3 2020-12-29)
 3 │ rust_channel       │ stable (default)
 4 │ cargo_version      │ cargo 1.49.0 (d00d64df9 2020-12-05)
 5 │ pkg_version        │ 0.25.1
 6 │ build_time         │ 2021-01-09 10:22:26
 7 │ build_rust_channel │ release
 8 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, git, ichwh, ptree, rich-benchmark, rustyline,
   │                    │ term, trash, uuid, which, zip
───┴────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**

I initially observed this after installing via the MSI. I then uninstalled nushell and reinstalled using cargo (`cargo install nu --features=extra`) and ran into the same issue.

This also occurs when installing 0.24.1 via Scoop.

**Comment by fdncred** [comment]
I don't think alias shows up anymore as a command but it still works. For instance, if you do `alias ll = ls -l` it should work.

**Comment by rgwood** [comment]
Interesting, that does work for me. But the examples from [the aliases documentation](https://www.nushell.sh/book/aliases.html) do not:

```
> alias ls-names [] { ls | select name }
error: Type Error
   ┌─ shell:11:16
   │
11 │ alias ls-names [] { ls | select name }
   │                ^^ Expected =, found []
   ```

**Comment by jonathandturner** [comment]
The documentation is unfortunately out of date it looks like. You can read more about the changes on the release announcement until we get the book updated: https://www.nushell.sh/blog/2021-01-05-nushell_0_25.html

**Comment by rgwood** [comment]
Gotcha, thanks for the quick response!

**Comment by rgwood** [comment]
Quick question: is there an easy way to persist commands created using `def`? Something like the `--save` flag from the old `alias` command (which does not seem to work with `def`)?

**Comment by fdncred** [comment]
I believe you have to put them in the `startup = [" ", " "]` section on the config.toml file.
