### ISSUE TITLE
testing count rows with if $it no longer working

### ISSUE THREAD

**Issue by schmitzli** [nushell/nushell#2900]
**Describe the bug**
**if $it** is no longer working with a value form a pipe.
When using count on a table and continuing the pipe with an if comparison $it is not accepted anymore as a representation for the value form the pipe.

**To Reproduce**
```
▶ ls | count | if $it > 10 {echo many} {echo some}
error: Variable not in scope
  ┌─ shell:4:17
  │
4 │ ls | count | if $it > 10 {echo many} {echo some}
  │                 ^^^ missing '$it' (note: $it is only available inside of a block)


```

**Expected behavior**
for more than 10 files it gives **many** else **some**

**Workaround**
▶ ls | count | wrap x | each { if $it.x > 10 {echo many} {echo some} }

I guess let does not accept a value from a pipe.

**Configuration (please complete the following information):**

```
───┬────────────────────┬──────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                       Column1
───┼────────────────────┼──────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.25.1
 1 │ build_os           │ windows-x86_64
 2 │ rust_version       │ rustc 1.48.0 (7eac88abb 2020-11-16)
 3 │ rust_channel       │ stable-x86_64-pc-windows-msvc (default)
 4 │ cargo_version      │ cargo 1.48.0 (65cbdd2dc 2020-10-14)
 5 │ pkg_version        │ 0.25.1
 6 │ build_time         │ 2021-01-06 21:42:13
 7 │ build_rust_channel │ release
 8 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, git, ichwh, ptree, rich-benchmark,
   │                    │ rustyline, term, trash, uuid, which, zip
───┴────────────────────┴──────────────────────────────────────────────────────────────────────────────────────

```

**Add any other context about the problem here.**

**Comment by fdncred** [comment]
I believe this is the intended behavior now. `$it` only works within a block, specifically `each { }`, as your work-around shows.

**Comment by schmitzli** [comment]
With the new **let** command a different solution is: 
`do { let file_count = $(ls | count) ;  if $file_count > 10 {echo many} {echo some} }`

credits to fdncred ;-)
