### ISSUE TITLE
error: Variable not in scope for a def parameter

### ISSUE THREAD

**Issue by schmitzli** [nushell/nushell#2901]
**Describe the bug**
i'm struggeling with a replacement for an 0.23 alias in nu 0.25.

My alias (0.23) was testing if a directory had a certain file (not perfect but it worked):
`alias notx [dir file] { ls $dir | where name =~ $file | count | if $it > 0 {echo ''} {echo $dir} }
`
Now in 0.25 i have:
```
def check-file [dir file] { ls $dir | where $(echo $it.name | path basename) == $file | count }
def notx [dir file] { check-file $dir $file | wrap x | each { if $it.x > 0 {echo ''} {echo $dir}} }

```

**To Reproduce**
1. with the 2 def above
2. execute `notx . testxyz`
```

▶ notx . testxyz
error: Variable not in scope
   ┌─ shell:11:1
   │
11 │
   │   unknown variable
```

The unknown variable is the second use of parameter $dir in the else case echo.

**Expected behavior**
the parameter passed for dir should be echoed if the file did not exist in dir

**Configuration (please complete the following information):**

```
> version | pivot
╭───┬────────────────────┬───────────────────────────────────────────────────────────────────────╮
│ # │ Column0            │ Column1                                                               │
├───┼────────────────────┼───────────────────────────────────────────────────────────────────────┤
 0 │ version            │ 0.25.1
 1 │ build_os           │ windows-x86_64
 2 │ rust_version       │ rustc 1.48.0 (7eac88abb 2020-11-16)
 3 │ rust_channel       │ stable-x86_64-pc-windows-msvc (default)
 4 │ cargo_version      │ cargo 1.48.0 (65cbdd2dc 2020-10-14)
 5 │ pkg_version        │ 0.25.1
 6 │ build_time         │ 2021-01-06 21:42:13
 7 │ build_rust_channel │ release
 8 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, git, ichwh, ptree, rich-benchmark,
   │                    │ rustyline, term, trash, uuid, which, zip
─╰───┴────────────────────┴───────────────────────────────────────────────────────────────────────╯
```

**Add any other context about the problem here.**

**Comment by schmitzli** [comment]
i even tried to avoid shadowing, use let to define as variable and added space for the }
```
def check-file [dir file] { ls $dir | where $(echo $it.name | path basename) == $file | count }
def notx [dirx file] { let d = $dirx ; check-file $d $file | wrap x | each { if $it.x > 0 { echo '' } { echo $d }} }
```
but have the same issue, maybe it's just some stupid mistake somewhere ?

**Comment by fdncred** [comment]
@schmitzli How about this one?

```
def notx [dir file] {
    let file_count = $(ls $dir | where name =~ $file | count)
    if $file_count > 0 {
        echo $dir | path expand
    } {
        echo ''
    }
}
```

**Comment by schmitzli** [comment]
thank you, fdncred !

The trick is to assign the count to a variable which avoids the **each**.
However i still need to echo the name (else i get a coercion error)
and change the compare to == 0 to keep the logic:
```

def notx [dir file] {
    let file_count = $(ls $dir | where $(echo name) =~ $file | count)
    if $file_count == 0 {
        echo $dir | path expand
    } {
        echo ''
    }
}
```

I think, this is still a workaround and the original should have worked.
So i suspect a problem in the scoping of variables.
Therefore i'm not closing this issue, yet, or did i miss something?

**Comment by schmitzli** [comment]
oh, the Coercion error is already fixed :-) thanks again

**Comment by fdncred** [comment]
can we close this then?

**Comment by schmitzli** [comment]
For my specific case i've now a workaround, but in general there is a parameter scope issue.
Here's a simplified example:

```
▶ def test [glob] { ls $glob | each { if $it.size > 1000 {echo $glob} {echo tiny}} }


▶ test c*
error: Variable not in scope
   ┌─ shell:38:62
   │
38 │ def test [glob] { ls $glob | each { if $it.size > 1000 {echo $glob} {echo tiny}} }
   │                                                              ^^^^^ unknown variable
```
here i would expect that the parameter $glob can be used throughout the definition and the output for some files would be "c*" for others "tiny"

**Comment by fdncred** [comment]
@jonathandturner any ideas what's going on with this `variable not in scope`?

**Comment by jonathandturner** [comment]
@fdncred - nothing jumps out at me, we should definitely investigate.

**Comment by ahkrr** [comment]
I also encountered this problem. I could resolve this by first defining 
`def nop [ _nop ] { }` and then defining 
`def test [glob] { ls $glob | each { nop $glob; if $it.size > 1000 {echo $glob} {echo tiny}} }`.
Maybe if `each` is  used and a variable isn't used (evaluated?) in a certain way before use, it isn't registered as a variable of this scope. This 
`def test [glob] { ls $glob | each { let x = $glob; if $it.size > 1000 {echo $glob} {echo tiny}} }` for example will also result in `variable not in scope`

**Comment by schmitzli** [comment]
all fine in 0.26.0
