### ISSUE TITLE
strange error text

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2909]
Repro

1. `ansi --help`
2. `let c = 25`
3. `do { let c = $(echo "$(c + 2)" | math sum); echo $c }`

see this error
```
error: Coercion error
  ┌─ shell:1:1
  │
1 │ ansi --help
  │ ^
  │ │
  │ integer
  │ string
```
Granted, I think this means my syntax for the `do` statement is wrong but it shouldn't be complaining about `ansi --help`, right?

I'm thinking I should've used `math eval` here too.

|key|value|
|-|-|
|version|0.25.1|
|branch|main|
|short_commit|481c6d45|
|commit_hash|'481c6d4511927cdc59a25004331539b0946ef1f1'|
|commit_date|2021-01-10 22:58:15|
|build_os|windows-x86_64|
|rust_version|rustc 1.49.0 (e1884a8e3 2020-12-29)|
|rust_channel|stable (default)|
|cargo_version|cargo 1.49.0 (d00d64df9 2020-12-05)|
|pkg_version|0.25.1|
|build_time|2021-01-11 07:10:51|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, default, directories, dirs, git, ichwh, ptree, rich-benchmark, rustyline, term, trash, uuid, which, zip|

**Comment by kubouch** [comment]
I think this issue is similar to the last one discussed in the Deveoping Discord channel.

Copy-pasting @jonathandturner's comment for reference:
> I think we might be able to fix this by making sure all definitions are available as part of the history. There are a few places we don't store where source code came from. In theory once that's fixed, we should be able to give good errors for them.
