### ISSUE TITLE
Release #4 - Nu Scripts

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#291]
# Requirements for Nu scripts
- [x] variables
- [x] functions
- [x] script loading/executing

**Comment by tfga** [comment]
Not just functions: closures.

Both bash and fish have functions. But:

* They're not first class
* Can't be nested
* Don't close over the environment where they were defined (i.e. aren't closures)
* Can't be anonymous

And people [complain about this](https://github.com/fish-shell/fish-shell/issues/2610).

My point is: it might be easier/simpler to have closures from the start than to add simple bash-style functions and then try to add them later.

Maybe this is already what you have in mind when you talk about [blocks](https://book.nushell.sh/en/types_of_data)?

**Comment by wycats** [comment]
@tfga nu's existing blocks are designed as closures (they hold onto a Scope instance from where they were originally evaluated).

Blocks are very restricted at the moment (they mostly arise at the moment when you write syntax like `where cpu > 0` which desugars into `where { $it.cpu > 0 }` but we're big fans of full fledged closures.

**Comment by tfga** [comment]
@wycats Awesome! A shell with closures would be a real game changer.

Have you ever heard of `es`? It's an ancient and now seemly defunct shell that was entirely built around the idea of lambdas. I'm not a great fan of their syntactic choices, but this is good work. Lots of interesting ideas in there. Have a look at their [paper](https://stuff.mit.edu/afs/sipb/user/yandros/doc/es-usenix-winter93.html).

> In es, almost all standard shell constructs (e.g., pipes and redirection) are translated into a uniform representation: function calls. The primitive functions which implement those constructs can be manipulated the same way as all other functions: invoked, replaced, or passed as arguments to other functions. The ability to replace primitive functions in es is key to its extensibility; for example, a user can override the definition of pipes to cause remote execution, or the path-searching machinery to implement a path look-up cache. 

> (...) For example:

    ls > /tmp/foo

> is internally rewritten as

    %create 1 /tmp/foo {ls}

>before it is evaluated. `%create` is the built-in function which opens `/tmp/foo` on file-descriptor 1 and runs `ls`. 

Anyway. Congratulations on the project. I'm really excited about it. Can't wait to see how it evolves / what you come up with.

**Comment by Southclaws** [comment]
How about embedding [Deno](https://github.com/denoland/deno)? Maybe not for the prompt itself but for scripts? It's available as a Rust crate, it's security focused, it's a well-known syntax so there would be no inventing of yet another new language.

**Comment by ubsan** [comment]
I would love some Ruby style closures -- `{ |$x, $y| $x + $y }`; one of my least favorite parts of pwsh is the length of `param` and how annoying they are to introduce

**Comment by richerve** [comment]
I also would vote for embedding a well known language if possible. I was thinking of playing with [Starlark](https://github.com/bazelbuild/starlark) that also has a Rust implementation [here](https://github.com/google/starlark-rust/). I think is a sufficiently mature language and it doesn't try to implement all features of a full-fledged language.

**Comment by jeffparsons** [comment]
As a nearly entirely uninformed outside observer, I imagine two future for scripting in Nu:

- Nu _aggressively_ avoids having its own scripting language aside from the bare minimum required to write command lines (pipe, variable substitution, and that's it), and instead focuses on clever ways to integrate with arbitrary existing languages; or

- Nu ends up with its own fully fledged language that is crafted around the specific design and needs of Nu.

I think the former is possible, and might be kind of cool. (I've been meaning for a long time to experiment with other/better ways for Unix-y command line tools to talk to each other.) But it would be an even bigger paradigm shift than anything else Nu is already doing, and might be _more_ work than designing a new scripting language.

I can't imagine a middle ground. Every example I've seen of an attempt to make a "minimal-ish" language ends up accidentally/awkwardly becoming a fully fledged programming language. E.g. RainerScript, Terraform's HCL, even HAProxy config files. So I feel that picking one extreme or the other from the start would lead to a much better future than trying to walk a middle path.

**Comment by tfga** [comment]
I agree with @jeffparsons. 

The problem is, language and shell have conflicting requirements. If you optimize for the shell, the language design suffers; if you prioritise the language, the shell UX becomes unbearable (that's how, on one hand, bash ended up being such a disaster as a language; and why, on the other, nobody uses general purpose programming languages' REPLs as shells[1]).

Coming up with a solution that satisfies both is the real challenge. But, in order to have any chance of doing this, language and shell should be considered simultaneously. 

IMHO. 

----
[1] Incidentally, that's also why every suggestion of simply using / embedding an existing language is, IMO, missing the point. A shell scripting language _can't be_ a general purpose language. It's not that it can't be done: of course it can. But if you do this, the shell ergonomics will be so bad that _nobody will use it_.

**Comment by jonathandturner** [comment]
Just to chime in and dump some notes here as this conversation starts back up:

Big +1 on balancing shell requirements and language requirements. Yehuda and I have both worked in language design and tool design for years, and all of us care passionately about UX.

For that reason, we didn't want to race ahead and create a language before we were steeped in the requirements that shells have. There are many: working with internal commands, calling out to external commands, completions, pipelining, dealing with errors, processing infinite streams, and we're still learning constraints as we fill out the features.

Here's some thoughts on some hunches, and we're eager to chat with other people about them, experiment with them, and just see if they'll hold up:

* We know that we want to resist mutation and side effects as much as possible. This lets us have fun with pipeline optimization later, and also allows us to process units of work in parallel and know that we can do so without any unexpected behavior.
* We suspect that as you describe pipelines in script that they should be lazy. That is, you describe a pipeline and assign it to a variable, we don't just start immediately processing it. This lets you built up exactly what you want, and only when its output is used that we actually start to process it.
* Like Yehuda mentions earlier in this thread, we suspect closures and blocks will play into how things work (again, leaning heavily on immutability)
* On the parsing side, we're looking into how commands are more similar to macros that can do things like an expansion step, and also inform the parser how to parse data in certain locations because of a) knowing the command, and b) knowing the type of the element expected at that location in the command. One fallout from this is that we already have two different parsers: one for external commands and another for internal commands.

We're working our way towards what we need for functions, while always making sure to test if what we're building works well for tooling, error reporting, type checking, and what you'd expect from how a shell should work.

**Comment by richerve** [comment]
I've been trying [elvish](https://elv.sh/) recently and by looking at their docs and the language spec they defined, it seems that it aligns with at least some of the bullet points that you mentioned. I'm not saying to use that language but probably can be used as a source of inspiration/comparison. I for example like the general functional programming feel of the language.

**Comment by Southclaws** [comment]
I fully agree with @tfga, I suggested using JS (deno) as the scripting language since it's well known but not as the shell language. I think a shell can have two languages/APIs. What you type in the prompt doesn't have to be the same as what you run in scripts!

**Comment by sandorex** [comment]
While it may be weird to seperate shell syntax and script syntax it may allow for it to be a a full scripting language

**Comment by linuxbytes** [comment]
Really like the project and shell environment. IMO a shell is a intermit interaction with the system and to automate with scripting. Unlike programming language which is mainly use for development. A shell need to have 3 foundations which is read, write data and run programs, which it needs to be able to interact With each other.  My concerns it could become a sql tool like https://www.osquery.io/  which is really imo is a db query or api call and not a shell. By all means this is really hard to do and I applause 👏  for making a new shell.

**Comment by ryepesg** [comment]
Another example of prior art is Xonsh (https://xon.sh/), which allows to use Python as the scripting language

**Comment by sandorex** [comment]
I may be a bit biased but i'd recommend taking a look at [crush](https://github.com/liljencrantz/crush) syntax, it is inspired by nushell but i really like it's language design

**Comment by PerBothner** [comment]
I've been experimenting with [a shell-line syntax](https://kashell.org/) as an alternative to the primary Scheme syntax for [Kawa](https://www.gnu.org/software/kawa/).  It's a mix of ideas, some (but not all) implemented, and not at all fully-baked - but feel free to rip off any ideas you like.

To summarize my ideas for KaShell most relevant to its use for a shell (not all implemented or explicit in the above link):

* There are no reserved words or "syntax keywords" - even infix operators are essentially just macros that could potentially be redefined.  Macros may have different "operator precedence" and associativity.

* Variable names are identifiers, without a prefix like `$`.

* Some macros automatically quote their arguments as if the arguments were string literals. There is a string escape syntax that allows sub-expressions which are evaluated at run-time.

* There a `run` macro which implicitly quotes the following arguments. The first argument is searched for as a command name (an executable file or builtin); the remaining arguments are command-line arguments to the command. If there is a left argument (before the `run` command), that is evaluated (without quoting), and the result becomes the standard input to the command.

* The `run` is not required if the command is an identifier that not in the lexical scope *and* it is in the `PATH` at compile-time *and* at run-time.  A filename (absolute or relative) containing slashes is an identifier in this context.

* A pipeline `cmd1 a1 a2 | cmd2 b1 b2 | cmd3 c1 c2` is syntactic sugar for `((cmd1 a1 a2) cmd2 b1 b2) cmd3 c1 c2`.

**Comment by jonathandturner** [comment]
@PerBothner - Very cool. For Nu, I've been wondering if we can blur similar lines:

* What if aliases and variables worked the same?  Aliases could live at the scope level you create them.  We could use `set x = 3` and `set my_alias a b = echo $a $b`.

* Perhaps we also allow you to invoke calls using `$`.  So you can use `echo $a` and also `echo $(run this call)`

We currently use the shape information (basically type information) that the user gives us for each command to change how the parser works for each argument.  This allows us to do some of the macro-like things you mention, like converting `where x > 3` to `where { = $it.x > 3 }`.  Similar to how you mention you can imply variables sometimes, we're trying to allow the user to write just the column name and if we know a column is expected, do the expansion for them.

Would be interested to see some examples of `run` and when it's required and when it's implied.

For your last point, is it correct to say that each piece, like `(cmd1 a1 a2)` returns a new command?  We do some bit of this now, though we build it using the async pipeline functionality, where we build up a pipeline and once composed, it can be activated. Otherwise, it's lazy and doesn't produce any values.  Would be interesting to see some examples of this, too.

**Comment by PerBothner** [comment]
In my terminology `(cmd1 a1 a2)` returns a "process object", not a command (which I think of as a generalization of a procedure).  A process object implements `Future<Blob>` where Blob can be coerced to a byte-string or a character-string as needed.  For NuShell, think of `Blob` as general command result. While the KaShell syntax is only partially implemented, the process concepts are working using [Scheme function-call syntax](https://www.gnu.org/software/kawa/Processes.html) as well as the [process-literal syntactic sugar](https://www.gnu.org/software/kawa/Processes.html#process-literals).

A fundamental issue in designing a "scripting language" is when a "word" (a sequence of non-delimiter characters) is a literal (quoted) string or when it is evaluated.  Do you write:

    echo $((10 + $i))     # Bash-style

or:
 
    print (10 + i)        # Python-style

Bash-style is familiar for shells and other languages where you're mostly working with strings: In a shell the command-line arguments are strings, and stdin/stdout/stderr are also usually viewed as strings.  It becomes more awkward when you're dealing with typed data and more complex objects/lists.  Consider something as simple as whether `3.2` and `true` are strings or numbers/booleans.

The context of my previous comment is how do you take a language with Python-like syntax and Scheme-like semantics (including macros and user-defined operators) and make it pleasant to use as a command shell.  The macro `run` (and the for rules when it is implicit) is for such a language where identifiers are by default variable/function names (not strings), and where you're trying to reduce command-argument quoting. 

In a language with Bash-style syntax each "word" is implicitly quoted, you don't need `run` but you need `$` for "unquote".  It's a trade-off but I think Bash-style syntax is more limiting.

**Comment by texastoland** [comment]
> Another example of prior art is Xonsh ([xon.sh](https://xon.sh/)), which allows to use Python as the scripting language

Xonsh looks verbose and error-prone on the boundaries between scripting and shell syntax.

> I suggested using JS (deno) as the scripting language since it's well known but not as the shell language.

Deno is inspiring but would certainly end up in the same camp.

> i'd recommend taking a look at [crush](https://github.com/liljencrantz/crush) syntax, it is inspired by nushell but i really like it's language design

Maybe there could be some collaboration with @liljencrantz? Crush looks similarly inspired to the Elvish language too.

Sorry to drive by. I love what you do 👏🏽

**Comment by krooq** [comment]
I totally agree with @jeffparsons and @tfga.
I'm also not sure why @Southclaws comment got a thumbsdown, the implications of what he said isn't obscene, its no different to using something like `awk` or `python` or even a binary.

One of my first comments to @jonathandturner was expressing my desire for scripting but I think I have matured since then and see that there are probably better, more reusable ways of doing things.

I think @jeffparsons idea is really the better way of doing things, especially from a portability standpoint.  You really don't want your scripting language to be tied to the shell, it really only works with something like bash because bash is so prolific and a lot of it is standardized.
Besides, scripting languages mostly support this, e.g. with python you can just run with -m or -s.

**Comment by jonathandturner** [comment]
@krooq - we still definitely see Nu as a full language. The root of it is that we want to make an interactive language, like a *truly* interactive language that's intended to allow developers to explore their systems, data, files, services, whatever, in real-time. And preferably, in a relaxed, enjoyable way.

Like @tfga points out, this means the language has to feel natural inside the shell. It's one of the main reasons we wanted to start with the shell first.

And I also agree with @jeffparsons - we have to go all the way.

Today's Nu is a rough outline of where we're going, but you can see lots of missing pieces. You can't create full scripts, yet, you can't define your own commands in code (aside from using `alias`), you can't create tasks, and on and on. The hope is that we'll get there, and by 1.0 we'll have a full language you can use both for lightweight, interactive shell tasks as well as something that's powerful enough to run large scripts.  And, even more, Nu's potential for other development environments, like Jupyter-style notebooks, will also shine. The shell doesn't have to be limited to the text terminal.

It's also a rough outline because we're growing organically, and looking to other folks to help us fill out the design.

**Comment by vitiral** [comment]
I just came across nushell and love it. To point out some brainstorming I did which had a few similar ideas (but only implemented as a library... probaly won't implement now that I've seen how awesome nushell is), I thought of creating a shell called [jsh](github.com/vitiral/jsh). It's basic idea was to:

* Provide structured types to shells, even though those types are just json and possibly json specifications (similar to protobuf). It definitely shares this goal with nushell
* Allow for pipes to be run in parallel -- so if you are outputting a list that list can be "streamed" to the next command, which can process it one line at a time. This works well for json since the program can wait for the ending "]" from it's stdin to wakeup.

This isn't a comment about jsh (although it might be worthwhile for nushell to consider concurrent pipes as a design goal) but rather how easy I found it to incorporate jsh into "normal" programs. All they had to do was provide for a `--jsh-request` cmdline param. They then should gaurantee that they would expect json on the stdin and output json on the stdout/stderr.

Nushell could do a similar thing: if `--nushell-request` is passed to a program it must adhere to some "spec" defined by nushell, such as that all input/output is json (maybe with specific fields), which nushell can then interpret as tables and pass to other programs. In this way, any script in any language could be run inside of nushell provided it adheres to this spec. Furthermore, the program can run in parallel.

In fact, it might be easier to embed a "simpler" spec such as jsh, which nushell knows hot to interact with :wink:

**Comment by vitiral** [comment]
I was reading the book, from the README I see you basically already do this :+1: 

> Plugins are binaries that are available in your path and follow a nu_plugin_* naming convention. These binaries interact with nu via a simple JSON-RPC protocol where the command identifies itself and passes along its configuration, which then makes it available for use. If the plugin is a filter, data streams to it one element at a time, and it can stream data back in return via stdin/stdout. If the plugin is a sink, it is given the full vector of final data and is given free reign over stdin/stdout to use as it pleases.

**Comment by marekkowalczyk** [comment]
Why not just adopt an existing language? 

E.g., [ABS](https://www.abs-lang.org/); I don't know how good it is, though.

**Comment by wycats** [comment]
@marekkowalczyk: It makes sense for us to be *inspired* by another language, but the scripting language should have more than a passing connection to the REPL language. We worked hard to make the REPL language a viable scripting language, so I think that's the direction that makes the most sense. 😄

**Comment by jonathandturner** [comment]
Support shipped in 0.25

**Comment by BarryMode** [comment]
Horray! The wait is over.
