### ISSUE TITLE
&& Operator

### ISSUE THREAD

**Issue by wycats** [nushell/nushell#293]
Support workflows like `make && make install`.

For the first iteration, we're going to be conservative and require parens if you mix `|` and `&&`

**Comment by andrasio** [comment]
#900

**Comment by waldyrious** [comment]
@jonathandturner is this now superseded by the `;` separator [introduced in 0.13](https://www.nushell.sh/blog/2020/04/21/nushell_0_13_0.html)?

**Comment by jonathandturner** [comment]
@waldyrious - good catch. yes, we can close now
