### ISSUE TITLE
Make the shell not crash

### ISSUE THREAD

**Issue by wycats** [nushell/nushell#294]
- [ ] Survey all unwraps
- [ ] Return errors instead of panicking
- [ ] Catch all panics at the boundary

**Comment by adam-mcdaniel** [comment]
Repeatedly having problems on Zorin (Ubuntu).

My shell crashes a ton. Sometimes my shell will crash trying to run a program, and will immediately crash again when i run the program in a new instance of the shell again.

Love the shell, ive stopped using bash and everything else!

**Comment by jonathandturner** [comment]
@adam-mcdaniel - we've done a lot of stability work since this was first file. Closing this issue, though we can file specific crashing issues as we find them.
