### ISSUE TITLE
menu completion

### ISSUE THREAD

**Issue by sesameguy** [nushell/nushell#2946]
Hi , i am a newbie of nuhell
I want to ask that is there menu completion when press `tab`?

Below image is the Menucomplete in `powershell`
![shell](https://user-images.githubusercontent.com/61531905/104865457-fec0e700-5976-11eb-959b-33797272c39d.jpg)

**Comment by fdncred** [comment]
You might try playing around with `completion_type` in the `line_editor` section in the `config.toml`. [Here's](https://github.com/nushell/nushell/blob/main/docs/sample_config/config.toml) a sample config.toml file, although I'm not sure it will work exactly the way you're wanting it to.

**Comment by sesameguy** [comment]
thx so much.
Moreover, is it possible to select the item by arrow key?

**Comment by fdncred** [comment]
In the same folder as the sample config.toml on our repo is a keybindings.yml file that should allow you to remap keys.
