### ISSUE TITLE
Using echo/autoview inside a loop with other commands is broken

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#2950]
**Describe the bug**
`echo` has trouble printing when more commands are present inside a block. There are two issues:
* unexpected `autoview` formatting
* delayed display on the screen with `echo`

**To Reproduce**
1. `> seq 1 3 | each { echo $it }`
    - works as expected, got a list
2. `> seq 1 3 | each { echo $it; sleep 1sec }`
    - does not print anything
3. `> seq 1 3 | each { echo $it | autoview; sleep 1sec }`
    - prints "123" (i.e., not a table just a string "123"), after all iterations are finished running
4. `> seq 1 3 | each { sleep 1sec; echo $it }`
    - prints the correct output after all iterations are finished running
5. `> seq 1 3 | each { sleep 1sec; echo $it | autoview }`
    - prints "123" (i.e., not a table just unstructured string "123"), after all iterations are finished running

**Expected behavior**

In all cases, I would expect echo to print in every iteration instead of everything at once after the loop has finished.

3. I would expect a list, not just "123".
5. I would expect a list, not just "123". The output should be similar to 4 but isn't.

**Configuration (please complete the following information):**

```
> version | pivot
  #         Column0                                                            Column1
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   0   version              0.25.2
   1   branch               main
   2   short_commit         088e6622
   3   commit_hash          088e662285c568462811c01c585975a97802fcff
   4   commit_date          2021-01-15 20:06:29
   5   build_os             linux-x86_64
   6   rust_version         rustc 1.49.0 (e1884a8e3 2020-12-29)
   7   rust_channel         stable (default)
   8   cargo_version        cargo 1.49.0 (d00d64df9 2020-12-05)
   9   pkg_version          0.25.2
  10   build_time           2021-01-18 10:24:49
  11   build_rust_channel   release
  12   features             clipboard-cli, ctrlc, default, directories, dirs, ichwh, ptree, rich-benchmark, rustyline, term, trash, uuid,
                            which, zip
```

**Add any other context about the problem here.**
Using `textview` instead `autoview` prints to the screen immediately but it formats the output in a weird way:
```
> seq 1 3 | each { echo $it | textview; sleep 1sec }
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ READER
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ 1
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ READER
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ 2
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ READER
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ 3
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

I tried running `ls` instead of `echo` and it works as expected:
```
> seq 1 3 | each { ls; sleep 1sec }
(nothing)
> seq 1 3 | each { ls | autoview; sleep 1sec }
(shows files)
(waits 1 sec)
(shows files)
(waits 1 sec)
(shows files)
(waits 1 sec)
```

**Comment by jonathandturner** [comment]
For this one:

```
> seq 1 3 | each { echo $it | autoview; sleep 1sec }

    prints "123" (i.e., not a table just a string "123"), after all iterations are finished running
```

You're asking for the individual values 1, 2, 3. For each of those values, you ask to print them to the screen. The result "123" might seem strange, but I think it's expected here.

By using `each`, you're pulling the table apart into the values that make up each piece. By starting with a list of values, you'll get the individual values.

Are you trying to print out individual rows of the table one at a time?

**Comment by schmitzli** [comment]
I would like to add simple example, hopefully it adds to the whole picture:

```
▶ echo 1 ; echo 2
2
```
I had expected the output of 1 and 2, normally even with an auto-added newline.
If an echo is followed with a colon and another command the output is lost.

**Comment by stormasm** [comment]
```
echo $nu.env 
```
crashes nushell completely ?

**Comment by kubouch** [comment]
> For this one:
> 
> ```
> > seq 1 3 | each { echo $it | autoview; sleep 1sec }
> 
>     prints "123" (i.e., not a table just a string "123"), after all iterations are finished running
> ```
> 
> You're asking for the individual values 1, 2, 3. For each of those values, you ask to print them to the screen. The result "123" might seem strange, but I think it's expected here.
> 
> By using `each`, you're pulling the table apart into the values that make up each piece. By starting with a list of values, you'll get the individual values.
> 
> Are you trying to print out individual rows of the table one at a time?

Thanks for explanation, the "123" makes sense now. It can come as a surprise when you're used to having structured data every time.

My use case was to print some status info inside a loop processing bunch of files, so I can monitor the progress (it takes a long time):
```
ls spam/* | get name | each { echo $it; process_file $it }
```
Then I started messing around with the commands and discovered these surprises.

I see #2952 might fix that, will test once it lands.

**Comment by kubouch** [comment]
OK, #2952 fixes autoview flushing.

The echo not printing can be sidestepped with a custom command, e.g.:
```
def println [x:any] {
    echo [ $it $(char newline) ] | str collect | autoview
}

> seq 1 3 | each { println $it; sleep 1sec }
1
2
3
```
