### ISSUE TITLE
'sys' incorrectly reporting memory information

### ISSUE THREAD

**Issue by Qwanve** [nushell/nushell#2958]
**Describe the bug**
The 'sys' command currently is reporting I have 12.2 MB of ram total, 9.4 MB free, 3.0 MB of total swap and 3.0 MB of free swap. These numbers are all incorrect, as htop reports I have 11.7 GB of ram, I'm using 900ish MB, and I'm using 0K of 2.9G of swap.
 
**To Reproduce**
1. run 'sys | get mem'
2. compare to info found in top, htop, etc.

**Expected behavior**
I expect that sys should report memory information correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/44913094/105273903-646cc900-5b59-11eb-8e8f-8933aa6be650.png)
![image](https://user-images.githubusercontent.com/44913094/105273957-7cdce380-5b59-11eb-8272-8e58107e00aa.png)

**Configuration (please complete the following information):**

```
> version | pivot
────┬────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────
 #  │      Column0       │                                                 Column1
────┼────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────
  0 │ version            │ 0.25.2
  1 │ branch             │ main
  2 │ short_commit       │ 2a42482a
  3 │ commit_hash        │ 2a42482ae9827d69664e4b25af4c19206181a0a7
  4 │ commit_date        │ 2021-01-20 19:07:16
  5 │ build_os           │ linux-x86_64
  6 │ rust_version       │ rustc 1.49.0 (e1884a8e3 2020-12-29)
  7 │ rust_channel       │ stable-x86_64-unknown-linux-gnu (default)
  8 │ cargo_version      │ cargo 1.49.0 (d00d64df9 2020-12-05)
  9 │ pkg_version        │ 0.25.2
 10 │ build_time         │ 2021-01-20 19:56:29
 11 │ build_rust_channel │ release
 12 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, trash, uuid, which, zip
────┴────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by JosephTLyons** [comment]
Probably related to the most recent swap to `sysinfo`

https://github.com/nushell/nushell/commit/b435075e0964b80d207cc3fd50f827a564f6cdd2

**Comment by JosephTLyons** [comment]
I can look into this

**Comment by JosephTLyons** [comment]
Probably related to the most recent swap to `sysinfo`

https://github.com/nushell/nushell/commit/b435075e0964b80d207cc3fd50f827a564f6cdd2

**Comment by jonathandturner** [comment]
Yeah, if sysinfo is less accurate, we should swap it back.

**Comment by fdncred** [comment]
I wonder if this is a known but in the `sysinfo` crate?

**Comment by jonathandturner** [comment]
Oh, you know it might be the units. I might be assuming bytes when it's kb or something

**Comment by jonathandturner** [comment]
Yup, that's what it was. PR incoming
