### ISSUE TITLE
scripts broken when left parentheses not on same line as def 

### ISSUE THREAD

**Issue by stormasm** [nushell/nushell#2972]
**Describe the bug**

The lexer is emitting an EOL token incorrectly when it is in the middle of lexing a command
where the parenthesis span multiple lines and the left parens is on the 2nd line instead
of the same line as the def statement.

https://github.com/stormasm/nuscratch/blob/main/parsedef/psum.nu

The above test file shows examples of broken scripts

In Summary:

### BROKEN case one
```
def p1 [arg]
{ echo $arg }
```

### BROKEN case two
```
def p2 [arg]
{ 
echo $arg }
```

### BROKEN case three
```
def echo_broken_case2 [arg]
{
echo $arg
}
```

#### Here is the problem described in more detail...

https://github.com/stormasm/nuscratch/blob/main/parsedef/test_out1.md

The if command is not working in scripts when it spans multiple lines

Here is the script file...
https://github.com/stormasm/nutmp/blob/master/scripts/test/if.nu

### Broken if command case where parenthesis are on different lines

```
def if_broken_case1 [dir] {
  if $dir == crates {
    echo 'got crates'
  }
  {
    echo 'got something else'
  }
}
```

**Comment by fdncred** [comment]
I've also see something like this break.
```
def t4 [dir]
{
   echo blah
}
```
just because the left brace was on a separate line

**Comment by stormasm** [comment]
https://github.com/nushell/nu_scripts/blob/main/nu_index_fg.nu#L5

@fdncred 
The above script you wrote is the example I found to show me **if** works
in some cases ---- that is why the more scripts we write the more
examples we will have of what is working and how to implement it.

I am also starting to realize  that having optional input parameters,
and then being able to a function to quickly test if any parameters were passed
in or not would be something good to have...

That is an example of something we want to put in our **standard library**

Just a real simple way to say ---- once optional parameters are up and
running --- were any input parameters passed in or not ?

**Comment by stormasm** [comment]
@jonathandturner I will explore further into 
lex.rs 
https://github.com/nushell/nushell/blob/main/crates/nu-parser/src/lex.rs#L316
and see if I can see anything that might be causing this problem ?

**Comment by stormasm** [comment]
#2956 once this PR lands then I will move forward in writing some more tests to see if we can figure out why this is not working...

**Comment by stormasm** [comment]
**Test # 1**

def my_echo [arg] { echo $arg }

**Test # 2**

def my_echo [arg] {
echo $arg }

**Test # 3**

def my_echo [arg]
{
echo $arg
}

**Test # 1**

[Token { contents: EOL, span: Span { start: 0, end: 1 } }, Token { contents: Baseline("def"), span: Span { start: 1, end: 4 } }, Token { contents: Baseline("my_echo"), span: Span { start: 5, end: 12 } }, Token { contents: Baseline("[arg]"), span: Span { start: 13, end: 18 } }, Token { contents: Baseline("{ echo $arg }"), span: Span { start: 19, end: 32 } }, Token { contents: EOL, span: Span { start: 32, end: 33 } }]

**Test #2**

[Token { contents: EOL, span: Span { start: 0, end: 1 } }, Token { contents: Baseline("def"), span: Span { start: 1, end: 4 } }, Token { contents: Baseline("my_echo"), span: Span { start: 5, end: 12 } }, Token { contents: Baseline("[arg]"), span: Span { start: 13, end: 18 } }, Token { contents: Baseline("{\necho $arg }"), span: Span { start: 19, end: 32 } }, Token { contents: EOL, span: Span { start: 32, end: 33 } }]

**Test # 3**

[Token { contents: EOL, span: Span { start: 0, end: 1 } }, Token { contents: Baseline("def"), span: Span { start: 1, end: 4 } }, Token { contents: Baseline("my_echo"), span: Span { start: 5, end: 12 } }, Token { contents: Baseline("[arg]"), span: Span { start: 13, end: 18 } }, Token { contents: EOL, span: Span { start: 18, end: 19 } }, Token { contents: Baseline("{\necho $arg\n}"), span: Span { start: 19, end: 32 } }, Token { contents: EOL, span: Span { start: 32, end: 33 } }]

**Test # 1**

LiteBlock { block: [LiteGroup { pipelines: [LitePipeline { commands: [LiteCommand { parts: [Spanned { span: Span { start: 1, end: 4 }, item: "def" }, Spanned { span: Span { start: 5, end: 12 }, item: "my_echo" }, Spanned { span: Span { start: 13, end: 18 }, item: "[arg]" }, Spanned { span: Span { start: 19, end: 32 }, item: "{ echo $arg }" }], comments: None }] }] }] }

**Test # 2**

LiteBlock { block: [LiteGroup { pipelines: [LitePipeline { commands: [LiteCommand { parts: [Spanned { span: Span { start: 1, end: 4 }, item: "def" }, Spanned { span: Span { start: 5, end: 12 }, item: "my_echo" }, Spanned { span: Span { start: 13, end: 18 }, item: "[arg]" }, Spanned { span: Span { start: 19, end: 32 }, item: "{\necho $arg }" }], comments: None }] }] }] }

**Test # 3**

LiteBlock { block: [LiteGroup { pipelines: [LitePipeline { commands: [LiteCommand { parts: [Spanned { span: Span { start: 1, end: 4 }, item: "def" }, Spanned { span: Span { start: 5, end: 12 }, item: "my_echo" }, Spanned { span: Span { start: 13, end: 18 }, item: "[arg]" }], comments: None }] }] }, LiteGroup { pipelines: [LitePipeline { commands: [LiteCommand { parts: [Spanned { span: Span { start: 19, end: 32 }, item: "{\necho $arg\n}" }], comments: None }] }] }] }

**Comment by stormasm** [comment]
More discussion about this issue in Discord on January 31, 2021

[here](https://discord.com/channels/601130461678272522/615329862395101194/805496900022304839)
and [here](https://discord.com/channels/601130461678272522/615962413203718156/805503274576379944)

**Comment by mvolkmann** [comment]
Note that table definitions are also affected by this. For example, the following is not parsed correctly:

```bash
let sports = [
  [name players];
  [baseball 9]
  [basketball 5]
  [football 11]
  [hockey 6]
]
```

But this way of writing it is parsed correctly:

```bash
let sports = [[name players
  ]; [
  baseball 9] [
  basketball 5] [
  football 11] [
  hockey 6]
]
```

The issue seems to be that ending a list on the line where it started causes unexpected parsing.

**Comment by mvolkmann** [comment]
I think this should remain open. It seems I don't have permission to remove the "Stale" label myself.

**Comment by stormasm** [comment]
This is still not fixed...  See above Broken Case 1 and Broken Case 2...

Unless we want to tell users that the first bracket must be on line 1...

Not sure what we want to do with this case...

**Comment by stormasm** [comment]
https://github.com/stormasm/nubug/tree/main/issue-2972

go to the above directory and try

```
source case1-broke.nu
source case2-broke.nu
```

and you will see some strange behavior
its not working the way it is supposed to.

**Comment by fdncred** [comment]
I'm not convinced this is a bug. We have a certain syntax that has to be met, and if it's not met, we throw an error. The question is, should we support @stormasm's case1 and case1 examples. I'm not sure. 

@jntrnr, what do you think?

**Comment by jntrnr** [comment]
For how the current parser works, both @mvolkmann's examples work, but the others are not currently expected to work. This is to keep the parser a bit more manageable and the syntax a bit more consistent.

**Comment by stormasm** [comment]
@jntrnr @fdncred I filed this issue over one year ago !
and now I am not sure either --- in fact I am fine with the way it currently
works and we just leave it alone for now...

but eventually people are going to run into this and wonder
why the location of the brace matters
and why it has to be on the same line...

**Comment by stormasm** [comment]
>>>This is to keep the parser a bit more manageable and the syntax a bit more consistent....

@jntrnr I agree with what you are saying ---- keeping the parser
manageable is important...

I am going to close this issue ?
Is that OK ?

**Comment by jntrnr** [comment]
@stormasm yeah that's okay.

related: we should try to get the syntax written down sometime (soon?) so that people understand how the parsing is supposed to work
