### ISSUE TITLE
How-to installation guide.

### ISSUE THREAD

**Issue by androbtech** [nushell/nushell#298]
It'd be nice if we can instruct how to set-up and run nu for the platforms.

**Comment by DanielRosenwasser** [comment]
Things I'm running into:

* no `x11-dev` on my system, so `cargo build` fails
* even after I `sudo apt-get install x11-dev`, I get link-time errors.

  ```
    = note: /usr/bin/ld: cannot find -lxcb-render
            /usr/bin/ld: cannot find -lxcb-shape
            /usr/bin/ld: cannot find -lxcb-xfixes
            collect2: error: ld returned 1 exit status
  ```

**Comment by androbtech** [comment]
> Things I'm running into:
> 
> * no `x11-dev` on my system, so `cargo build` fails
> * even after I `sudo apt-get install x11-dev`, I get link-time errors.
>   ```
>     = note: /usr/bin/ld: cannot find -lxcb-render
>             /usr/bin/ld: cannot find -lxcb-shape
>             /usr/bin/ld: cannot find -lxcb-xfixes
>             collect2: error: ld returned 1 exit status
>   ```

Please try the packages listed in the( installation guide)[https://book.nushell.sh/en/installation#dependencies].

**Comment by androbtech** [comment]
Oh.. I was the one who opened this issue originally. Thanks @DanielRosenwasser! 

Closing this since we have a book with installation instructions now. [The Nu Book](https://book.nushell.sh).

**Comment by androbtech** [comment]
Reopening this so we can write the dependencies needed in the `README` as well. /cpy @jonathandturner

**Comment by wycats** [comment]
Is this addressed?

**Comment by androbtech** [comment]
> Is this addressed?
Yes
