### ISSUE TITLE
select does not work correct with duplicate column

### ISSUE THREAD

**Issue by djvsrose** [nushell/nushell#2985]
****** consider the following case
ls | count
17

ls | select name modified | count
17

ls | select name modified name | count.  => duplicate name column here
34                                                                => the count should still be 17 not 34
 

 0 │ version            │ 0.26.0                                                                             
 1 │ build_os           │ macos-x86_64                                                                       
 2 │ rust_version       │ rustc 1.49.0                                                                       
 3 │ cargo_version      │ cargo 1.49.0                                                                       
 4 │ pkg_version        │ 0.26.0                                                                             
 5 │ build_time         │ 2021-01-27 21:21:53                                                                
 6 │ build_rust_channel │ release                                                                            
 7 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip 
───┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────

**Comment by andrasio** [comment]
Fixed. Thanks for reporting it!
