### ISSUE TITLE
Nu panics when called from another shell

### ISSUE THREAD

**Issue by donkeyteethUX** [nushell/nushell#2989]
Nu does not seem to work when called from bash. However nu is clearly doing something because it panics. 
I wasn't able to find documentation for this; I just tried it. Should it work?

![image](https://user-images.githubusercontent.com/35647226/106368666-409b4700-6300-11eb-9586-e58d4342c91a.png)

**Comment by fdncred** [comment]
Thanks for the report.  It shouldn't crash but the proper way to call nu from a shell is `nu -c "command"`

**Comment by donkeyteethUX** [comment]
Cool thanks!
