### ISSUE TITLE
table is horked and I don't know why

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#2994]
**Describe the bug**
use this file - note, line two and line four have a trailing space. You may also need `leading_trailing_space_bg = "white"` in your config.toml under the `[line_editor]` section.

```
one
two 
three
four 
```

This command `open test | wrap text` produces this result
![image](https://user-images.githubusercontent.com/343840/106489883-dbb82c00-647a-11eb-9b32-9a01c0d821ad.png)

**Expected behavior**
The table to be properly formed on left and right sides.

|key|value|
|-|-|
|version|0.26.0|
|branch|main|
|short_commit|b052d524|
|commit_hash|'b052d524da3ed5cbc85d955c60a4694a0fb8f55d'|
|commit_date|2021-01-29 07:44:02|
|build_os|windows-x86_64|
|rust_version|rustc 1.49.0 (e1884a8e3 2020-12-29)|
|rust_channel|stable (default)|
|cargo_version|cargo 1.49.0 (d00d64df9 2020-12-05)|
|pkg_version|0.26.0|
|build_time|2021-01-29 08:58:23|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, trash, uuid, which, zip|

**Comment by jonathandturner** [comment]
@fdncred - looks like the bug here is that we aren't handling multiline strings well? (esp. if there are trailing spaces?)

what do you get if you do: `open test | lines | wrap text`?

**Comment by fdncred** [comment]
@jonathandturner it looks better but doesn't show the trailing spaces. not sure if there is a built-in `trim` somewhere or what.
![image](https://user-images.githubusercontent.com/343840/106495663-9ba87780-6481-11eb-9758-7814316a4419.png)
