### ISSUE TITLE
Suggestion: add the ability to remove files while maintaining directory structure.

### ISSUE THREAD

**Issue by GitHub-user-2020** [nushell/nushell#2998]
I am starting to like nushell after using it a few minutes, and I like how it can potentially unify my Windows and Linux workflow.

I've thought about how nushell's tabling workflow can potentially make targeted file deletion a bit simpler, like when I need to maintain directory structure too, as in this [link](https://stackoverflow.com/questions/7714900/remove-only-files-in-directory-on-linux-not-directories).

Unfortunately, the default shell for Linux and Windows resort to using rather contrived CLI prompts in my opinion, requiring the following:

Linux:

    $ find "<dir>"* ! -type d -exec rm -vf '{}' \;

Windows:
    
    $ Get-ChildItem -Path "<dir>" -Include *.* -File -Recurse | foreach { $_.Delete()}

I wonder if future versions of nushell can take this into account.

**Comment by fdncred** [comment]
How about something like this? 

1. Define a custom command with what you want to do. `def noop [filename:any] { echo $filename }`
2. Run the command on the files you find. `ls **/* | where type == File | each { noop $it }`

**Comment by GitHub-user-2020** [comment]
Where can I find more information with regards to custom commands for that? I would like to improve my understanding of that in my own time possibly

**Comment by fdncred** [comment]
There isn't a lot of documentation on custom command yet but you can start [here](https://www.nushell.sh/blog/2021-01-05-nushell_0_25.html#custom-commands) and [here](https://www.nushell.sh/blog/2021-01-26-nushell_0_26.html#rest-support-in-custom-commands-lhkipp-jonathandturner). I found these by going [here ](https://www.nushell.sh/)and searching in the search box. 

If you're good to go, please close the issue.
