### ISSUE TITLE
Unwrap cleanup (master list)

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#300]
If you'd to help remove the unwraps in Nu, respond below with the file you'd like to work on. From there, you can send in a PR that removes unwraps in that file and instead returns errors that the user can see.

If you have questions, feel free to ask here, on twitter (I'm @jntrnr) or on our discord (https://discord.gg/NtAbbGn)

- [ ] tests/command_cd_tests.rs:99:        assert_eq!(PathBuf::from(actual), dirs::home_dir().unwrap());
- [ ] tests/command_config_test.rs:17:            nu::config_path().unwrap().join(expected)
- [ ] tests/command_config_test.rs:57:    h::delete_file_at(nu::config_path().unwrap().join("test_3.toml"));
- [ ] tests/command_config_test.rs:86:    h::delete_file_at(nu::config_path().unwrap().join("test_4.toml"));
- [ ] tests/command_config_test.rs:114:    h::delete_file_at(nu::config_path().unwrap().join("test_5.toml"));
- [ ] src/cli.rs:325:            .map(|s| match s.as_string().unwrap().as_ref() {
- [ ] src/utils.rs:36:        AbsolutePath::new(self.inner.parent().unwrap())
- [ ] src/context.rs:51:        let registry = self.registry.lock().unwrap();
- [ ] src/context.rs:57:        let registry = self.registry.lock().unwrap();
- [ ] src/context.rs:63:        let mut registry = self.registry.lock().unwrap();
- [ ] src/context.rs:68:        let registry = self.registry.lock().unwrap();
- [ ] src/context.rs:97:        let mut host = self.host.lock().unwrap();
- [ ] src/context.rs:117:        self.registry.get_command(name).unwrap()
- [ ] src/errors.rs:577:    fn unwrap_error(self, desc: impl Into<String>) -> Result<T, ShellError>;
- [ ] src/errors.rs:581:    fn unwrap_error(self, desc: impl Into<String>) -> Result<Tagged<T>, ShellError> {
- [ ] tests/helpers/mod.rs:183:        get_app_root(AppDataType::UserConfig, &nu::APP_INFO).unwrap()
- [ ] src/format/vtable.rs:77:        table.print_term(&mut *host.out_terminal()).unwrap();
- [ ] src/format/table.rs:209:            .map(|s| match s.as_string().unwrap().as_ref() {
- [ ] src/format/table.rs:257:        table.print_term(&mut *host.out_terminal()).unwrap();
- [ ] src/format/entries.rs:39:        let max_name_size: usize = self.entries.iter().map(|(n, _)| n.len()).max().unwrap();
- [ ] src/data/base.rs:97:        Primitive::Decimal(BigDecimal::from_f64(float).unwrap())
- [ ] src/data/base.rs:229:        Ok(last.unwrap())
- [ ] src/shell/help_shell.rs:26:            let value = command_dict(registry.get_command(&cmd).unwrap(), Tag::unknown());
- [ ] src/shell/help_shell.rs:31:                value.get_data_by_key("usage").unwrap().as_string().unwrap(),
- [ ] src/shell/help_shell.rs:74:                step => match viewed.get_data_by_key(step.to_str().unwrap()) {
- [ ] src/plugins/inc.rs:307:        assert_eq!(inc.apply("0.1.3").unwrap(), Value::string("1.0.0"));
- [ ] src/plugins/inc.rs:314:        assert_eq!(inc.apply("0.1.3").unwrap(), Value::string("0.2.0"));
- [ ] src/plugins/inc.rs:321:        assert_eq!(inc.apply("0.1.3").unwrap(), Value::string("0.1.4"));
- [ ] src/plugins/inc.rs:338:        let output = plugin.filter(subject).unwrap();
- [ ] src/plugins/inc.rs:340:        match output[0].as_ref().unwrap() {
- [ ] src/plugins/inc.rs:366:        let output = plugin.filter(subject).unwrap();
- [ ] src/plugins/inc.rs:368:        match output[0].as_ref().unwrap() {
- [ ] src/plugins/inc.rs:395:        let output = plugin.filter(subject).unwrap();
- [ ] src/plugins/inc.rs:397:        match output[0].as_ref().unwrap() {
- [ ] src/plugins/binaryview.rs:222:    let decoder = decoder.unwrap();
- [ ] src/plugins/binaryview.rs:226:    let buffer = decoder.read_image().unwrap();
- [ ] src/plugins/binaryview.rs:242:    let decoder = decoder.unwrap();
- [ ] src/plugins/binaryview.rs:246:    let buffer = decoder.read_image().unwrap();
- [ ] src/plugins/binaryview.rs:271:    let raw_image_buffer = raw_image_buffer.unwrap();
- [ ] src/plugins/binaryview.rs:284:            .unwrap();
- [ ] src/plugins/binaryview.rs:307:            .unwrap();
- [ ] src/plugins/binaryview.rs:396:                image::ImageBuffer::<image::Rgba<u8>, &[u8]>::from_raw(256, 240, slice).unwrap();
- [ ] src/plugins/embed.rs:75:            self.field.as_ref().unwrap(),
- [ ] src/shell/value_shell.rs:44:                step => match viewed.get_data_by_key(step.to_str().unwrap()) {
- [ ] src/plugins/str.rs:174:                } => self.params.as_mut().unwrap().push(String::from(s)),
- [ ] src/plugins/str.rs:258:        let configured = plugin.config().unwrap();
- [ ] src/plugins/str.rs:272:        assert_eq!(plugin.action.unwrap(), Action::Downcase);
- [ ] src/plugins/str.rs:282:        assert_eq!(plugin.action.unwrap(), Action::Upcase);
- [ ] src/plugins/str.rs:292:        assert_eq!(plugin.action.unwrap(), Action::ToInteger);
- [ ] src/plugins/str.rs:329:        assert_eq!(strutils.apply("ANDRES").unwrap(), Value::string("andres"));
- [ ] src/plugins/str.rs:336:        assert_eq!(strutils.apply("andres").unwrap(), Value::string("ANDRES"));
- [ ] src/plugins/str.rs:343:        assert_eq!(strutils.apply("9999").unwrap(), Value::int(9999 as i64));
- [ ] src/plugins/str.rs:360:        let output = plugin.filter(subject).unwrap();
- [ ] src/plugins/str.rs:362:        match output[0].as_ref().unwrap() {
- [ ] src/plugins/str.rs:383:        let output = plugin.filter(subject).unwrap();
- [ ] src/plugins/str.rs:385:        match output[0].as_ref().unwrap() {
- [ ] src/plugins/str.rs:408:        let output = plugin.filter(subject).unwrap();
- [ ] src/plugins/str.rs:410:        match output[0].as_ref().unwrap() {
- [ ] src/plugins/str.rs:431:        let output = plugin.filter(subject).unwrap();
- [ ] src/plugins/str.rs:433:        match output[0].as_ref().unwrap() {
- [ ] src/plugins/str.rs:456:        let output = plugin.filter(subject).unwrap();
- [ ] src/plugins/str.rs:458:        match output[0].as_ref().unwrap() {
- [ ] src/plugins/str.rs:479:        let output = plugin.filter(subject).unwrap();
- [ ] src/plugins/str.rs:481:        match output[0].as_ref().unwrap() {
- [ ] src/commands/from_csv.rs:69:                    fields.get(idx).unwrap(),
- [ ] src/shell/shell_manager.rs:32:        self.shells.lock().unwrap().push(shell);
- [ ] src/shell/shell_manager.rs:33:        self.current_shell = self.shells.lock().unwrap().len() - 1;
- [ ] src/shell/shell_manager.rs:39:            let mut shells = self.shells.lock().unwrap();
- [ ] src/shell/shell_manager.rs:58:        self.shells.lock().unwrap().is_empty()
- [ ] src/shell/shell_manager.rs:62:        self.shells.lock().unwrap()[self.current_shell].path()
- [ ] src/shell/shell_manager.rs:66:        let env = self.shells.lock().unwrap();
- [ ] src/shell/shell_manager.rs:72:        self.shells.lock().unwrap()[self.current_shell].set_path(path)
- [ ] src/shell/shell_manager.rs:81:        self.shells.lock().unwrap()[self.current_shell].complete(line, pos, ctx)
- [ ] src/shell/shell_manager.rs:85:        self.shells.lock().unwrap()[self.current_shell].hint(line, pos, ctx)
- [ ] src/shell/shell_manager.rs:90:            let shell_len = self.shells.lock().unwrap().len();
- [ ] src/shell/shell_manager.rs:102:            let shell_len = self.shells.lock().unwrap().len();
- [ ] src/shell/shell_manager.rs:113:        let env = self.shells.lock().unwrap();
- [ ] src/shell/shell_manager.rs:123:        let env = self.shells.lock().unwrap();
- [ ] src/shell/shell_manager.rs:129:        let env = self.shells.lock().unwrap();
- [ ] src/commands/to_bson.rs:47:        Value::Primitive(Primitive::Decimal(d)) => Bson::FloatingPoint(d.to_f64().unwrap()),
- [ ] src/commands/to_bson.rs:81:                    Ok(Bson::RegExp(r.unwrap(), opts.unwrap()))
- [ ] src/commands/to_bson.rs:94:                        if let Bson::Document(doc) = object_value_to_bson(s.unwrap())? {
- [ ] src/commands/to_bson.rs:95:                            Ok(Bson::JavaScriptCodeWithScope(js.unwrap(), doc))
- [ ] src/commands/to_bson.rs:117:                Ok(Bson::TimeStamp(ts.unwrap()))
- [ ] src/commands/to_bson.rs:130:                        Ok(v) => Ok(Bson::Binary(v, bin.unwrap())),
- [ ] src/commands/to_bson.rs:141:                let obj_id = ObjectId::with_string(&obj_id.unwrap());
- [ ] src/commands/to_bson.rs:145:                    Ok(Bson::ObjectId(obj_id.unwrap()))
- [ ] src/commands/to_bson.rs:154:                Ok(Bson::Symbol(sym.unwrap()))
- [ ] src/commands/help.rs:49:                        let value = command_dict(registry.get_command(&cmd).unwrap(), tag.clone());
- [ ] src/commands/help.rs:54:                            value.get_data_by_key("usage").unwrap().as_string().unwrap(),
- [ ] src/commands/enter.rs:75:                            .await.unwrap();
- [ ] src/commands/vtable.rs:38:            let mut host = context.host.lock().unwrap();
- [ ] src/commands/clip.rs:55:        let mut clip_context: ClipboardContext = ClipboardProvider::new().unwrap();
- [ ] src/commands/clip.rs:82:        clip_context.set_contents(new_copy_data).unwrap();
- [ ] src/commands/table.rs:38:            let mut host = context.host.lock().unwrap();
- [ ] src/commands/post.rs:68:    let user = call_info.args.get("user").map(|x| x.as_string().unwrap());
- [ ] src/commands/post.rs:72:        .map(|x| x.as_string().unwrap());
- [ ] src/commands/post.rs:78:            post(&path_str, &body, user, password, path_span, &registry, &raw_args).await.unwrap();
- [ ] src/commands/post.rs:239:                    let content_type = Mime::from_str(content_type).unwrap();
- [ ] src/commands/post.rs:309:                                .unwrap()
- [ ] src/commands/command.rs:571:                        .unwrap();
- [ ] src/commands/command.rs:586:                .unwrap();
- [ ] src/commands/from_xml.rs:66:        Value::string(n.text().unwrap()).tagged(tag)
- [ ] src/commands/shells.rs:34:    for (index, shell) in args.shell_manager.shells.lock().unwrap().iter().enumerate() {
- [ ] src/commands/from_sqlite.rs:106:            // this unwrap is safe because we know the ValueRef is Text.
- [ ] src/commands/from_sqlite.rs:107:            Value::Primitive(Primitive::String(t.as_str().unwrap().to_string())).tagged(tag)
- [ ] src/commands/classified.rs:310:                let stdout = popen.stdout.take().unwrap();
- [ ] src/commands/classified.rs:315:                let stdout = popen.stdout.take().unwrap();
- [ ] src/commands/classified.rs:318:                let stream = stream.map(move |line| Value::string(line.unwrap()).tagged(name_tag));
- [ ] src/env/host.rs:47:        term::stdout().unwrap()
- [ ] src/env/host.rs:51:        term::stderr().unwrap()
- [ ] src/commands/to_json.rs:42:            .unwrap(),
- [ ] src/commands/to_json.rs:57:                    serde_json::Value::Number(serde_json::Number::from_f64(*x as f64).unwrap())
- [ ] src/commands/plugin.rs:106:                let request_raw = serde_json::to_string(&request).unwrap();
- [ ] src/commands/plugin.rs:179:                                    let request_raw = serde_json::to_string(&request).unwrap();
- [ ] src/commands/plugin.rs:221:                let request_raw = serde_json::to_string(&request).unwrap();
- [ ] src/commands/plugin.rs:304:        let request_raw = serde_json::to_string(&request).unwrap();
- [ ] src/commands/plugin.rs:305:        let mut tmpfile = tempfile::NamedTempFile::new().unwrap();
- [ ] src/parser/parse/files.rs:25:        tag.origin.unwrap()
- [ ] src/commands/from_tsv.rs:70:                    fields.get(idx).unwrap(),
- [ ] src/parser/parse/parser.rs:105:                    Number::Decimal(BigDecimal::$from(decimal).unwrap())
- [ ] src/parser/parse/parser.rs:111:                    Number::Decimal(BigDecimal::$from(*decimal).unwrap())
- [ ] src/parser/parse/parser.rs:688:    let int = FromStr::from_str(frag).unwrap();
- [ ] src/parser/parse/token_tree_builder.rs:337:        let head = input.next().unwrap();
- [ ] src/commands/save.rs:175:                let command_name = format!("to-{}", extension.to_str().unwrap());
- [ ] src/commands/from_yaml.rs:59:            Value::number(n.as_i64().unwrap()).tagged(tag)
- [ ] src/commands/from_yaml.rs:62:            Value::Primitive(Primitive::from(n.as_f64().unwrap())).tagged(tag)
- [ ] src/parser/parse/unit.rs:44:        Unit::from_str(input).unwrap()
- [ ] src/commands/to_yaml.rs:33:            serde_yaml::Value::Number(serde_yaml::Number::from(b.to_f64().unwrap()))
- [ ] src/commands/to_yaml.rs:39:            serde_yaml::Value::Number(serde_yaml::Number::from(f.to_f64().unwrap()))
- [ ] src/commands/fetch.rs:67:        let (file_extension, contents, contents_tag, span_source) = result.unwrap();
- [ ] src/commands/fetch.rs:146:                let content_type = Mime::from_str(content_type).unwrap();
- [ ] src/commands/fetch.rs:228:                            .unwrap()
- [ ] src/commands/open.rs:68:        let (file_extension, contents, contents_tag, span_source) = result.unwrap();
- [ ] src/parser/parse/operator.rs:41:        Operator::from_str(input).unwrap()
- [ ] src/parser/parse/tokens.rs:40:            RawNumber::Int(tag) => Number::Int(BigInt::from_str(tag.slice(source)).unwrap()),
- [ ] src/parser/parse/tokens.rs:42:                Number::Decimal(BigDecimal::from_str(tag.slice(source)).unwrap())

**Comment by t-hart** [comment]
I'll cover **Unit.rs**.

**Comment by t-hart** [comment]
I looked through a couple of these the other day and found that for some files, they're only unwrapping in the tests. Is that something that should be removed too?

I very much agree with not unwrapping in program code, but in testing it'd only make your tests fail, which is what they should do given an unexpected value. Just wondering whether that's something to look into or not.

**Comment by jonathandturner** [comment]
@t-hart - unwrapping in tests is probably okay. Mostly, for unwraps, we're trying to remove places where the shell will panic when someone is using it.

**Comment by jonathandturner** [comment]
Closing this, but we should do a new one that's up to date.  We list removing unwraps in other issues, so that work is still being tracked.
