### ISSUE TITLE
Wrap External commands ala PowerShell Crescendo

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#3001]
**Is your feature request related to a problem? Please describe.**
Most external commands do not represent themselves as data.

**Describe the solution you'd like**
Have a functionality similar to [PowerShell Crescendo](https://devblogs.microsoft.com/powershell/announcing-powershell-crescendo-preview-1/) to wrap external commands. I see these wrappers being distributed as part of our standard library of scripts.

See some of PS Crescendo's examples [here in their repo](https://github.com/PowerShell/Crescendo/tree/master/Microsoft.PowerShell.Crescendo/Samples).

[Part1 Blog](https://devblogs.microsoft.com/powershell/native-commands-in-powershell-a-new-approach/)
[Part2 Blog](https://devblogs.microsoft.com/powershell/native-commands-in-powershell-a-new-approach-part-2/)

[A Video](https://channel9.msdn.com/Shows/IT-Ops-Talk/OPS117-PowerShell-Deep-Dive) that explains how it works starting at `52:00`.

[PowerShell Crescendo Preview 1](https://devblogs.microsoft.com/powershell/announcing-powershell-crescendo-preview-1/)
[PowerShell Crescendo Preview 2](https://devblogs.microsoft.com/powershell/announcing-powershell-crescendo-preview-2/)
[PowerShell Crescendo Preview 3](https://devblogs.microsoft.com/powershell/announcing-powershell-crescendo-preview-3/)

**Comment by fdncred** [comment]
I'd still like to see nushell be able to support something like this.

**Comment by dark-ether** [comment]
we already have the extern keyword could it be modified to allow parsing the command output as data?

**Comment by jntrnr** [comment]
This is supported as part of the "known external commands" work.

**Comment by fdncred** [comment]
It's not part of known externals, but i'm fine with closing this. `Crescendo` is a way that powershell makes non-tabular data into powershell-style tables. Another tool that does a similar thing is [jc](https://github.com/kellyjonbrazil/jc).
