### ISSUE TITLE
'ps' on Linux shows 0% cpu usage for all processes

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#301]

**Comment by androbtech** [comment]
Investigated a bit. The field does not even render. Only the `pid`, `parent`, `status`, `name`, and `exe` fields.

**Comment by twe4ked** [comment]
Remove “NOTE: OMG FIXME” from [the book](https://github.com/nushell/book/blob/591a14d0976c32e126ffa04cc1117d57a783aff1/introduction.md) when this is fixed.

**Comment by jonathandturner** [comment]
Should be fixed for all platforms with https://github.com/nushell/nushell/pull/325
