### ISSUE TITLE
edit-and-execute-command (C-x C-e)

### ISSUE THREAD

**Issue by ocehugo** [nushell/nushell#3017]
**Is your feature request related to a problem? Please describe.**
Yes. In nushell 0.26, there is apparently no support for the equivalent edit-and-execute-command feature present in bash. The classical ```C-x C-e``` keyboard shortcut is not available and I can't find anything in the docs or the book about it.

**Describe the solution you'd like**
Support edit-and-execute-command. Probably something in the line of 

```nu
config set edit_and_execute_editor "vi"
config set edit_and_execute_trigger "Ctrl-x Ctrl-e" 
```

**Describe alternatives you've considered**

vi-mode is not enough, particularly for long lines or more than singleton changes.

Apart from a staple functionality in most shells, this feature complements - and I would say suppress - vi/emacs mode, since with 3 keystrokes one can rely on all the power of the full editor instead of adapted, reduced, and unmodifiable keybindings.

**Comment by fdncred** [comment]
We use `rustlyine` for line editing. You might want to investigate [our keybindings sample](https://github.com/nushell/nushell/tree/main/docs/sample_config) and/or check out their repo to see if what you're trying to is possible. I'm not sure.

**Comment by ocehugo** [comment]
thanks for the heads up @fdncred. I agree, its a feature of readline, not bash per se.  Will dig through rustyline then, and report back.
