### ISSUE TITLE
wrong output after error. 

### ISSUE THREAD

**Issue by ocehugo** [nushell/nushell#3018]
**Describe the bug**
nushell 0.26 in OSX catalina creates non-formatted outputs after an error.

See image below:

**To Reproduce**

1. ```ls ``` and normal output will be done.
2. ``` ls -al | vim ```
2. error is raised, vim is open, close vim 
3. ```ls``` output is not formatted anymore.

**Expected behavior**
Step 3. above is the same as 1.

**Screenshots**
![image](https://user-images.githubusercontent.com/1202691/107136531-4cb68280-6958-11eb-8e1c-d931b04eca51.png)

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
version | pivot
  #        Column0                                              Column1
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
  0   version              0.26.0
  1   build_os             macos-x86_64
  2   rust_version         rustc 1.49.0
  3   cargo_version        cargo 1.49.0
  4   pkg_version          0.26.0
  5   build_time           2021-01-27 21:49:24
  6   build_rust_channel   release
  7   features             ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip
```

**Add any other context about the problem here.**
Changing window size do not fix the problem. Shell restart is required.

edited: fixed template to bug report, since I did a feature request template by accident.

**Comment by fdncred** [comment]
maybe try something like `ls *.toml | each {vim $it.name}`

**Comment by ocehugo** [comment]
@fdncred, I'm aware of the operations, but your answer is not the solution per se. My example was just a way to trigger the problem. For example: ```echo abc  | head``` would also cause the formatting issue.

Update:
I found out that the problem here is that alacritty and nushell are not playing well together. This problem is not reproducible in osx default terminal or using bash+alacritty.

**Comment by fdncred** [comment]
@ocehugo oh, ok. I just did it on windows too.
```
nushell
➜ echo abc | head
abc
```
