### ISSUE TITLE
ignore newlines in history/ avoid too many empty lines in prompt

### ISSUE THREAD

**Issue by ocehugo** [nushell/nushell#3019]
**Describe the bug**
nushell history do not ignore empty new lines/CR. Moreover, new empty lines in history creates a strange newline repetition when user is navigating in the history with say, up arrows.

**To Reproduce**
1. start nushell, call something like ```version | pivot ```, and hit CR 2 or more times.
2. Hit arrow up to search for a command in history.
3. At first hit, a new line will be created above the cursor . at the second hit a new line is apparently created below the cursor.
4. When you found your command, the command is put on the 2 lines below where it should.

**Expected behavior**
newlines are ignored in history search and in history itself. The above steps do not add newlines to the prompt.

**Screenshots**
![image](https://user-images.githubusercontent.com/1202691/107136845-ce0f1480-695a-11eb-9a5d-01759bca6103.png)
**Configuration (please complete the following information):**

See image above.

**Add any other context about the problem here.**

Please note that starship in nushell is also using an unnecessary extra line (below the green arrow ->). I couldn't manage to fix this with any config (maybe another bug). Other shells are OK with the same config.

**Comment by jonathandturner** [comment]
I'm not able to reproduce this with the current version of Nushell. Does it occur for you using the default prompt or specifically when using starship?

**Comment by medakk** [comment]
I can reproduce this on a main-build with the default prompt

```
────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────
 #  │      Column0       │                                      Column1                                       
────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────
  0 │ version            │ 0.26.1                                                                             
  1 │ branch             │ main                                                                               
  2 │ short_commit       │ 233161d5                                                                           
  3 │ commit_hash        │ 233161d56ed909e1666b05cdbef5c1e165d0c13d                                           
  4 │ commit_date        │ 2021-02-07 15:10:06                                                                
  5 │ build_os           │ linux-x86_64                                                                       
  6 │ rust_version       │ rustc 1.49.0 (e1884a8e3 2020-12-29)                                                
  7 │ rust_channel       │ stable (default)                                                                   
  8 │ cargo_version      │ cargo 1.49.0 (d00d64df9 2020-12-05)                                                
  9 │ pkg_version        │ 0.26.1                                                                             
 10 │ build_time         │ 2021-02-07 19:17:24                                                                
 11 │ build_rust_channel │ release                                                                            
 12 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip 
────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────
```

I see newlines when I run `history`:

```
 92 │ history                                          
 93 │ \n                                               
 94 │ ls                                               
 95 │ \n                                               
 96 │ ls -l                                            
 97 │ ls | sort-by -r size                             
 98 │ \n                                               
 99 │ ls          
```

**Comment by ocehugo** [comment]
@jonathandturner, yes I can reproduce without starship, but with slightly and more clean behaviour:

Using:
```
config set prompt "pwd"
```
and doing the above (cmd, CR,CR, up,up, up), I see two repeated "pwd" entries printed on the screen , one per line, before reaching my cmd history on the third printed line. I would expect my cursor to be at N-3 lines isntead.

**Comment by e3pax** [comment]
I have the exact same issue with starship. I have not found a solution. My config works on all other shells just fine too. My current shell is fish but I want to switch to nu.
