### ISSUE TITLE
where: accept human-format file size

### ISSUE THREAD

**Issue by ilius** [nushell/nushell#3023]
Accept file size formats like `123k`, `12m`, `1.5g` in `where` command.

- k/K for kilobytes.
- m/M for megabytes.
- g/G for gigabytes.

For example:

    ls | where size > 12m

instead of 

    ls | where size > 12582912

**Comment by jonathandturner** [comment]
these might be a little too short and may be ambiguous. We currently use a couple letters to make it less ambiguous. Instead of `1k` it's `1kb` for example.

**Comment by ilius** [comment]
Thanks for responding.
I see, it's also documented in https://www.nushell.sh/book/commands/where.html

Personally I think `1M` (one month) is not logical, because month is not a duration of time, is has varied length in all calendars.

But `m` for minute makes sense.
And I understand it's hard for parser to detect these based on type of column.

But at least K and G are pretty standard for Kilo and Giga, and it's not specific to file size (bytes).
They are not used in time or calendar context.
Can be parsed independently from column type,

**Comment by jonathandturner** [comment]
@ilius - agreed, "1 month" isn't logical and should be removed. I think the largest duration we should use is 1 day or 1 week, anything after that will depend on the calendar.

In the future, we may add other unit types that someone could optionally add (like for example maybe someone comes up with currency as an optional feature or weights and measures). As people use additional unit types, it feels like we should make them more readable now rather than more compressed.

**Comment by ilius** [comment]
If you want to be picky, even kb, mb, Mb, gb, Gb are all ambiguous.
b can be interpreted as bits.
Only kB, MB and GB are accurate and unambiguous.

While K, M and G units are pretty standard in Linux, Mac and BSD.
Both in output and flags of commands like du, df, ls, etc.

But I'm fine with it either way.
You can close this issue.

**Comment by ilius** [comment]
Just one more thing.
What about decimal numbers?
Like `2.5GB`?

**Comment by ilius** [comment]
I'm closing this in favor of #3030

**Comment by eugenesvk** [comment]
> these might be a little too short and may be ambiguous

Where is the ambiguity for a file `size` column in the `ls | where size >` command? The ~full list `k`,`m`,`g`,`t`,`p`,`e`,`z`,`y` (nothing for bytes) is a list of unique labels

Can these units at least be configurable? I mean, one of the best features of having column/data type is that you can reduce ambiguity: you know it's file sizes, so you know that `m` can't mean `months`, and that helps getting to exactly the minimum convenient abbreviation, which is 1-letter in this case
(similarly, `where accessed > 1day` isn't great, `where accessed > 1d` is pretty unambiguious and much more convenient)
