### ISSUE TITLE
New command to set table alignment

### ISSUE THREAD

**Issue by ilius** [nushell/nushell#3027]
**Is your feature request related to a problem? Please describe.**

**Case 1**: using `from csv` or `from json` command, all numbers are right-aligned in the resulting table.
Even if these numbers are double-quoted (in csv, json, yaml or other format that uses quotation).
If all the values in that column are numeric, that may be natural or expected for most cases.
But it would be very unnatural **if most of values in that column are nun-numeric**, or the numbers have different type/unit, and are not comparable (for example environment variables, config parameters, system statistics etc)

**Case 2**: for the ease of reading or any other reason, we want to force a column (or all columns) to be aligned to left, right or center.

**Describe the solution you'd like**
I propose adding a new command like `align`, for example:

    ... | from csv | align c,l,l,r

(`c`=center, `l`=left, `r`=right).

If the number of columns exceed the number of parts in this command, we can do one of these:
- Return error (maybe a bit too extreme)
- Ignore and hide additional columns
- Use the default alignment (left of right depending on value type) for additional columns

The last one is the best option I think.

**Comment by fdncred** [comment]
Right now alignment occurs by datatype. You can see it [here](https://github.com/nushell/nushell/blob/0e13d9fbaaf286cb7b8aeb9758ea56a783e85c8f/crates/nu-data/src/primitive.rs#L228) in the repo. I think specifying alignment would be cool but I'd also like to do it by datatype because one can change the color of each datatype too. I think what you're proposing is slightly different but maybe we could come up with some combined way to do it.

**Comment by ilius** [comment]
How can I specify the type of columns coming from `from `?

**Comment by ilius** [comment]
The default alignment can be defined based on dataype.
But changing datatype just to change alignment is not very nice.
Type and alignment are separate things.
We don't want to loose the colors to change alignment.

**Comment by ilius** [comment]
I found `str from COL` to change type of one column to string.

**Comment by fdncred** [comment]
right, i think there may only be a few datatypes we can create, int, decimal, date, string, maybe others. but i recently updated `str from` to include most datattypes, but that i think that just creates strings. `str to-int`, `str to-datetime`, `str to-decimal` do what you'd expect.

**Comment by ilius** [comment]
Question: Is there a way to convert filesize columns to integer or decimal directly? (without converting to string, removing commas and then converting to integer/decimal)
If no, would you be open to a pull request?

**Comment by fdncred** [comment]
@ilius I don't think there's a command to do that easily. sometimes i have to take a 'trip through json' to do certain conversions like `ls | to json | from json`. I think we'd be option to convert to int/decimal easier but if we're talking about filesizes it would need to support the filesize nomenclature like `23kb`, `17kib`, `b`, `kb`, `mb`, `gb`, etc.

what's your idea to do this?

**Comment by ilius** [comment]
I'm thinking of an `int` command (just like `str`) that can convert anything in tables to integer, kind of like `int` function in Python or Go, or `to_i` in Ruby.
It can even replace `str to-int`.
I'm not sure it can replace `into-int` which only takes an argument (doesn't seem to work with `each` either).

**Comment by ilius** [comment]
I just realized `from json` changes the order of columns (`to json` produces correctly)
I guess because an unordered Hash Map is used to de-serialize objects.
Is this considered a bug?

**Comment by fdncred** [comment]
We had to change json crates and the one we use doesn't support maintaining order. It's a known issue. I'm not sure there's an issue in it or not.

**Comment by ilius** [comment]
Here is my filesize to int function in case a user needed it

```
def size2int [] {
	format filesize size B | str from size | str find-replace -a ',' '' size | str to-int size
}
```
Example: `ls | size2int`
(The column name needs to be `size`)

**Comment by ilius** [comment]
I can't figure out how to pass a column name as argument to a function
```
def size2int [p] {
    format filesize $p B | str from $p | str find-replace -a ',' '' $p | str to-int $p
}
```
Error:
```
error: Type Error
  ┌─ shell:1:15
  │
1 │ ls | size2int size
  │               ^^^^ Expected column path, found string
```

And can't specify type `column path` or `column_path` for function argument.

**Comment by fdncred** [comment]
I'm not quite sure either. I don't think we have `column path` as a datatype yet for scripts. @jonathandturner any ideas?

**Comment by fdncred** [comment]
I played around a little bit more and created this script, that also doesn't work. :(
```
def size2int [--column(-c):any] {
    update $column {
        get $column |
        str from |
        str find-replace -a ',' '' |
        str to-int
    }
}
```
It returns a similar error. I was thinking that `any` would make a difference but apparently not.
```
ls | size2int -c size
error: Type Error
   ┌─ shell:18:18
   │
18 │ ls | size2int -c size
   │                  ^^^^ Expected column path, found string
```
This was based on this command that does work.
`ls | update size { get size | str from | str find-replace -a ',' '' | str to-int }`

**Comment by ilius** [comment]
I think the problem is in [nu-engine/src/deserializer.rs line 404](https://github.com/nushell/nushell/blob/041086d22ad072506974a9163cc1c38a41b0949e/crates/nu-engine/src/deserializer.rs#L404)
But I can't figure out the syntax to fix it!

Should probably add something like
```
		        Value {
		            value: UntaggedValue::Primitive(Primitive::String(value.val)),
		            ..
		        } => {
		        	let s = value.val.spanned(span);
                                ColumnPath::build(&s)
	        	}
```
But where do we get the `span` from?

**Comment by fdncred** [comment]
`Span::unknown()`? I believe [span is here](https://github.com/nushell/nushell/blob/main/crates/nu-source/src/meta.rs)

**Comment by ilius** [comment]
Great! It fixes it! Adding PR.

**Comment by ilius** [comment]
I just realized we still can't use a variable (defined by let) or `$(...)` as the column name for `where` command.
Although it works as part of conditional expression.
