### ISSUE TITLE
Filesize rendering and parsing use different standards

### ISSUE THREAD

**Issue by ilius** [nushell/nushell#3034]
**Describe the bug**
When rendering/showing a table, file sizes use units of `KB=1000B`, `MB=1000KB` etc.
Which is wrong. It should use `KB=1024B`, `MB=1024KB` etc.
The nu parser (`where` command) works correctly (uses 1024).

**To Reproduce**
- `ls` or `du` in a directory with sub-directories, the size of directories shown as `4.1 KB` instead of `4 KB`
- Use or create a file with a size bigger than 1000 and run `ls`, and compare the output of standard `ls` in Linux/Mac, or open file Properties in Windows

```
> version | pivot
────┬────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────
 #  │      Column0       │                                                 Column1                                                  
────┼────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────
  0 │ version            │ 0.26.1                                                                                                   
  1 │ branch             │ main                                                                                                     
  2 │ short_commit       │ 7f7e8465                                                                                                 
  3 │ commit_hash        │ 7f7e8465da7e558d5acbfdf56bc3186c21b3b65a                                                                 
  4 │ commit_date        │ 2021-02-09 08:16:10                                                                                      
  5 │ build_os           │ linux-x86_64                                                                                             
  6 │ rust_version       │ rustc 1.48.0                                                                                             
  7 │ cargo_version      │ cargo 1.46.0                                                                                             
  8 │ pkg_version        │ 0.26.1                                                                                                   
  9 │ build_time         │ 2021-02-09 10:09:36                                                                                      
 10 │ build_rust_channel │ release                                                                                                  
 11 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, trash, uuid, which, zip 
────┴────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by ilius** [comment]
I was almost sure this line was the cause:
https://github.com/nushell/nushell/blob/main/crates/nu-data/src/base/shape.rs#L207

I changed 1000 to 1024 but didn't fix it!
This is the command I use to compile:

    cargo build --workspace --features=extra --release

Then I run `./target/release/nu`

What am I missing?

**Comment by ilius** [comment]
Oh the problem is coming from `byte.format`

https://docs.rs/byte-unit/4.0.9/byte_unit/

**Comment by ilius** [comment]
Looks like `kB=kilobyte=1000B`, and `KiB=kibibyte=1024B`
https://en.wikipedia.org/wiki/Byte#Multiple-byte_units

This is so confusing!
Because both Windows and Linux use `K` or `KB` as kibibyte or 1024B!

**Comment by ilius** [comment]
Perhaps we can have a config parameter like `filesize_metric=false`.

But right now, inconsistency between parsing and rendering is the biggest issue I think.

**Comment by ilius** [comment]
Okay, so I set `filesize_format = "kib"` in config but then it shows everything as `KiB`, not `GiB` etc

**Comment by ilius** [comment]
Maybe accept a list of units in `filesize_format` config to decide which of the two standards to use?

And also change nu-parser to be kB=1000B and KiB=1024B etc?

**Comment by fdncred** [comment]
when i worked on the `filesize_format` config I was trying to get it to spit out file sizes as a consistent format, specifically bytes. I'd rather see my sizes in a consistent format which is why i always have my format set to `filesize_format = "B"`. but i can see how some people may like the summarization formatting like you've specified. maybe if we had a `filesize_unit=1000` or `filesize_unit=1024` we could make the unset `filesize_format` return either?

**Comment by ilius** [comment]
There are several ways we can use config to customize the output.

But can you check this PR first please?
https://github.com/nushell/nushell/pull/3035

**Comment by fdncred** [comment]
It looks like you need to update the tests to work.

**Comment by ilius** [comment]
I fixed the tests.

**Comment by ilius** [comment]
Okay so now that inconsistency is fixed, I guess I can close this issue.

I can add a new PR for switching between metric and 1024-based units with a config key (should not override `filesize_format`).
