### ISSUE TITLE
Enforce consistent style in config options (esp. boolean options)

### ISSUE THREAD

**Issue by ammkrn** [nushell/nushell#3037]
I'm using nu 0.26.0 on MacOS. Thanks for all the hard work so far. Going through the manual I was thrown off a little bit by this minor UX issue. If the authors agree with one or both of these points I'll try and PR the relevant changes.

1. The boolean configuration options in `config.toml` mix affirmative and negative descriptors, in some cases requiring double-negation to get the desired option. For example, it seems like the manual's description of `no_auto_pivot` is written in the affirmative: `whether or not to automatically pivot single-row results`. I want to say "not" after reading the description "whether or not to automatically pivot single-row results", but the option is `no_auto_pivot`, so I need to set it to `true`.

2. The boolean options in `config.toml` are either "true" or "false", but the output of `config` renders them as `yes` and `no`, which seems like an unnecessary transformation.

IMO it's more intuitive for all options to assume the affirmative (do the thing, add the feature, etc); if the default or preferred option is negative, a parenthetical `(default = false)` in the description is a more clear way of communicating that fact. 

I think this is more intuitive:
```
show_welcome_message (default = true)
show_table_indexes (default = true)
auto_pivot (default = false)
```

when compared to:
```
skip_welcome_message
disable_table_indexes 
no_auto_pivot
```

**Comment by fdncred** [comment]
I believe the docs to be outdated, for one thing we have this now for `no_auto_pivot` because of the reasons you've suggested - `pivot_mode = "auto" # auto, always, never`.

definitely agree about `yes`, `true`, `no`, `false`.

the s[ample config here](https://github.com/nushell/nushell/tree/main/docs/sample_config) should be updated i believe.

**Comment by ammkrn** [comment]
@fdncred 

Thanks for the info, I agree `pivot_mode` is more pleasant and #3043 deals with the bool display. I'll leave the first point as food for thought w.r.t future boolean options since it's a style thing, and making changes would require a larger discussion about deprecation of config options. I feel like Alacritty did this pretty well; it shows a warning on startup if it finds deprecated config options (which users should be able to disable).
