### ISSUE TITLE
nushell crashes trying to run `ls` command

### ISSUE THREAD

**Issue by Azgrom** [nushell/nushell#3039]
The crash reproduces in this way:

```shell
 [rafael@I-7590 ~]$ nu
Welcome to Nushell 0.26.0 (type 'help' for more info)
/home/rafael> ls
thread 'main' panicked at 'unable to get the config.toml file: ShellError { error: Diagnostic(ShellDiagnostic { diagnostic: Diagnostic { severity: Error, code: None, message: "Couldn\'t parse config file:\nexpected an equals, found a newline at line 4 column 236", labels: [Label { style: Primary, file_id: 0, range: 0..0, message: "file name" }], notes: [] } }), cause: None }', /home/rafael/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-data-0.26.0/src/base/shape.rs:161:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

As you can see I simply initialize nu and run `ls`.

```shell
 [rafael@I-7590 ~]$ rustc --version
rustc 1.49.0 (e1884a8e3 2020-12-29)
```

I am compiling nushell from this repository with the above Rust compiler...

It is preventing me from using nushell. Hope this feedback is useful.

**Comment by jonathandturner** [comment]
While we definitely don't want to crash in this situation, it looks like your "config.toml" file, where the config options are loaded from, has some syntax errors in it.

**Comment by Azgrom** [comment]
Yep. There is a snippet code @fdncred suggested at #2843 in my `config.toml`. Sorry not have it already shown.

At that point that snippet worked just fine. And now it makes this error to happen...

**Comment by fdncred** [comment]
The way to test that snippet is to just try and run it from the command line. If it fails you should see what the problem is... hopefully.

**Comment by ammkrn** [comment]
> While we definitely don't want to crash in this situation, it looks like your "config.toml" file, where the config options are loaded from, has some syntax errors in it.

I ran into this again with the `ls` thing. #3382 was sort of a monkey patch; imo this "crash on parse error" behavior should be treated as a non-trivial issue. If you're using nu as your login shell and/or have your terminal set to default to nu, you're now locked out of your terminal and have to rely on some hack to get to and fix the config file. In some cases the terminal closes before it even displays the message about the parse error.

**Comment by jonathandturner** [comment]
@ammkrn were you able to see where the parse error is happening? what file and line number?

**Comment by ammkrn** [comment]
@jonathandturner It seems like any parse error followed by a call to `ls` will do it, but two examples I know will trigger it on 0.31.0 are leaving a comma off a list element like in the paths list, and just having a key with no value.

```
rm_always_trash = true
some_key =
...
```

or

```
path = [
  "an_entry_without_a_comma"
  "second_entry"
]
```

**Comment by fdncred** [comment]
@ammkrn thanks for the research. I'm guessing there are a few of these expects around the config file scattered throughout the code base. I've updated this and will push a change shortly to see if this fixes the problem.
```
            filesize_format_var = match crate::config::config(Tag::unknown()) {
                Ok(cfg) => cfg
                    .get("filesize_format")
                    .map(|val| val.convert_to_string().to_ascii_lowercase())
                    .unwrap_or_else(|| "auto".to_string()),
                _ => "auto".to_string(),
            }
```

**Comment by fdncred** [comment]
Hopefully this will fix it https://github.com/nushell/nushell/pull/3510

**Comment by ammkrn** [comment]
@fdncred 

Thanks. Lmk if there's any desire to use the "always return a config, log if there's an error and we're using the default" thing. The other places in the repo where `::config()` gets invoked tend to use the pattern
```
if let Ok(cfg) = config() {
   // do stuff with the user's config settings
}

//rest
```
just ignoring potential errors. Having a fallback default that's defined in one place that just gets reused might make it easier to avoid [some of the boilerplate](https://github.com/nushell/nushell/blob/55baee9a9a7b24207551c74bb9998927584f53a6/crates/nu_plugin_textview/src/textview.rs#L15).

If nothing else, it would be nice if `::config()` logged the presence of a parse error that gets introduced such that it wasn't caught during startup.

**Comment by fdncred** [comment]
@ammkrn I think that's a reasonable change. Feel free to submit a PR cleaning all that stuff up as you suggest. If there's an issue parsing the config.toml, i agree that a default should be loaded, but there should also be an error message so the user understands why their settings aren't applied.
