### ISSUE TITLE
When calling external tool, filepath is not covered to string

### ISSUE THREAD

**Issue by djvsrose** [nushell/nushell#3046]
Consider the command

ls | where $(head -n 1 $it.name) =~ "SomeTextILookedFor"

This caused error: Received unexpected type from pipeline (row)
                                head -n $it.name
                                ^^^^ expected a string

$it.name is a filepath not a string. But when calling external tool, filepath should be allowed

 0 │ version                  │ 0.26.0
 1 │ build_os                │ macos-x86_64
 2 │ rust_version        │ rustc 1.49.0
 3 │ cargo_version     │ cargo 1.49.0
 4 │ pkg_version        │ 0.26.0
 5 │ build_time           │ 2021-01-27 21:21:53
 6 │ build_rust_channel │ release
 7 │ features               │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip

**Comment by ilius** [comment]
This is a real issue!
I have an external command in my `prompt`, and sometimes `nu` falls into a state that shows this error just by pressing Enter (no command, just Enter), every time, so I have to leave the shell and open it again.

**Comment by ilius** [comment]
The problem is with the `head` command part, not `$it.name`
Example:
```
ls | first 1 | where $(/usr/bin/echo abc) =~ "abc"
```

```
error: Received unexpected type from pipeline (row)
  ┌─ shell:5:22
  │
5 │ ls |first 1| where $(/usr/bin/echo abc) =~ "abc"
  │                      ^^^^^^^^^^^^^ expected a string
```

**Comment by ilius** [comment]
Perhaps a better example:
```
ls | where type == File | insert first_line {/usr/bin/head -n1 $it.name}
```
```
error: Received unexpected type from pipeline (row)
  ┌─ shell:3:46
  │
3 │ ls | where type == File | insert first_line {/usr/bin/head -n1 $it.name}
  │                                              ^^^^^^^^^^^^^ expected a string
```

**Comment by ilius** [comment]
Okay I found a kind of hackish way to do what you want.
First you need to define a function
```
def first-line [p] {
	head -n1 $p | split row '\n' | split column '\n' | get Column1
}
```
that you should put in your startup script or directly in startup section of your config
https://github.com/nushell/nushell/blob/main/docs/sample_config/config.toml

Then for example:

```
ls | where type == File | insert first_line {each {first-line $it.name}} | where first_line =~ "License"
```
Produces:
```
───┬─────────┬──────┬────────┬────────────┬─────────────
 # │  name   │ type │  size  │  modified  │ first_line  
───┼─────────┼──────┼────────┼────────────┼─────────────
 0 │ LICENSE │ File │ 1.1 KB │ 5 days ago │ MIT License 
```

You can define another function to make it easier:
```
def insert-first-line [] {
	insert first_line {each {first-line $it.name}}
}
```

Then:
```
ls | where type == File | insert-first-line | where first_line =~ "License"
```
