### ISSUE TITLE
Azure CLI ('az) command can't pipe

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#306]
Unclear as to why just yet, but I'm not able to pipe the output from `az` into the pipeline.

**Comment by jonathandturner** [comment]
I cant' repro the hang, so it might have been temporary. Now it seems like the output can't be parsed as json (possibly because the pretty printing is causing the output to happen from multiple lines)

**Comment by jonathandturner** [comment]
I can see the hang with the latest, even after changing from-json to merge into one string. The hang seems to be unrelated.

**Comment by jonathandturner** [comment]
Closing for now. This seems related more to the particular service you're connecting to. If I can get a good repro, I'll reopen.

**Comment by TechWatching** [comment]
@jonathandturner How do you use nushell with azure cli ? I was expecting to be able to use from-json to parse it but as you said it does not work. Being able to manipulate (filter, transform ...) outputs of azure cli with nushell would be awesome but I don't see how to do it.
