### ISSUE TITLE
Add flag to start nushell without loading any configuration files

### ISSUE THREAD

**Issue by LhKipp** [nushell/nushell#3068]
We already have `skip-plugins`. It would be good to also have the ability to skip the loading of
1. the global config file
2. any local config file (.nu-env)

**Comment by fdncred** [comment]
And make sure not to stomp on the current config.toml with a 0 byte config.toml. Right now, if you rename your config.toml and start nu, it will created a 0 byte file.

**Comment by LhKipp** [comment]
We could use this feature in our test code. It will make the test code more consistent.

**Comment by fdncred** [comment]
ya, when I run test i **always** have to remove my config.toml

**Comment by LhKipp** [comment]
We now have "config-file" for tests which solves part of the problem.
We load many different things on startup, we should better look how we can configure the startup in general, instead of adding 1 feature once at a time.
