### ISSUE TITLE
Auto complete doesn't auto complete

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#3076]
**Describe the bug**
I'd like to do simple completion by typing `source ls-wide<tab>` and have it autocomplete the file names that are clearly in the directory.

**To Reproduce**
1. watch gif
2. read my comments in the gif
3. watch the keystrokes in the bottom right hand corner of the gif

**Expected behavior**
It autocomplete the file name or file name list.

**Screenshots**
![no_autocomplete](https://user-images.githubusercontent.com/343840/108425887-b9573a00-7200-11eb-9915-7988ffa27ce2.gif)

**Configuration (please complete the following information):**

02/18/2021 03:41:47.022 PM ¯\_(ツ)_/¯ ▶ nuver | to md
|key|value|
|-|-|
|version|0.27.1|
|branch|main|
|short_commit|deff1aa6|
|commit_hash|'deff1aa63b49fcba6b1a066a15c3fc869bc91508'|
|commit_date|2021-02-17 23:54:48|
|build_os|windows-x86_64|
|rust_version|rustc 1.50.0 (cb75ad5db 2021-02-10)|
|rust_channel|stable (default)|
|cargo_version|cargo 1.50.0 (f04e7fab7 2021-02-04)|
|pkg_version|0.27.1|
|build_time|2021-02-18 15:29:38|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, trash, uuid, which, zip|

**Comment by jonathandturner** [comment]
I think this might be specific to the `source` command. Does it autocomplete for other commands?

**Comment by fdncred** [comment]
Kind of.

Doesn't work - i guess a lot of these are `~` related
1. `ls ~<tab>` - no completions
2. `ls ~/<tab>` - no completions - probably due to being on windows
3. `cd ~\.c<tab>` - completes `~.\cache\` - but actual cd fails
4. `ls ~\<tab>` - allows me to cycle through completions, but once I choose one the command fails
5. `vim ~\.config\starship.toml` - fails and tries to load `~.configstarship.toml` - maybe thinking `\` is an escape?

Works
1. `ls s<tab>` completes `sample_data\` and the command actually works
2. `vim ls<tab>` completes `ls-less.nu` and works as expected

if you have others you want me to try let me know.
