### ISSUE TITLE
Add signal name option to kill

### ISSUE THREAD

**Issue by warrenseine** [nushell/nushell#3077]
**Is your feature request related to a problem? Please describe.**
Today, I wanted to send SIGTERM to my application and realized I had to fall back to the native `kill` command.

**Describe the solution you'd like**
I'd like to pass the signal as an optional argument (e.g. `kill -s 15 <pid>` or `kill -s TERM <pid>`).

**Describe alternatives you've considered**
`^kill -15 <pid>`

**Additional context**
I was about to implement the feature and understood _why_ it wasn't already available. I see that on Windows we use `taskkill` which naturally doesn't support signals. So I open this issue first to know whether you prefer to avoid a non-cross-platform feature, which would make sense.

**Comment by warrenseine** [comment]
Looking at the [philosophy](https://www.nushell.sh/contributor-book/philosophy.html), it is not stated whether you want to adhere to strict cross-platform compatibility or if feature can be available on specific platforms.

**Comment by jonathandturner** [comment]
@warrenseine - I think it's okay if a system has additional capabilities, like signals, to support them as optionally include commands and flags.

Something we've been trying to avoid is lighting up functionality only on one platform that *could* work across platforms if we did enough work.

**Comment by jokeyrhyme** [comment]
Could we re-open this?
