### ISSUE TITLE
Ability to disable the `External command failed` error diagnostic

### ISSUE THREAD

**Issue by lpil** [nushell/nushell#3085]
**Is your feature request related to a problem? Please describe.**

When writing code I often run my compiler from the terminal in order to see any error messages. When there is one it is printed by the compiler, which then returns a non-zero exit code. Upon seeing this exit code Nu also prints an error, which obscures the error I actually wish to see, making it less clear what has happened.

Here is an example:

```
❯ gleam build
error: Type mismatch
  ┌─ \\?\C:\Users\louis.pilfold\Desktop\ok\src\ok.gleam:2:3
  │
2 │   1.0 + 1.0
  │   ^^^ Not an Int

error: External command failed
  ┌─ shell:5:1
  │
5 │ gleam build
  │ ^^^^^ command failed
```

**Describe the solution you'd like**

I would like to be able to disable this Nu diagnostic printing via configuration.

```
❯ gleam build
error: Type mismatch
  ┌─ \\?\C:\Users\louis.pilfold\Desktop\ok\src\ok.gleam:2:3
  │
2 │   1.0 + 1.0
  │   ^^^ Not an Int
```

**Describe alternatives you've considered**

Alternatively a concise and non-distracting format could be offered by Nu, again opted-in via configuration:
```
❯ gleam build
error: Type mismatch
  ┌─ \\?\C:\Users\louis.pilfold\Desktop\ok\src\ok.gleam:2:3
  │
2 │   1.0 + 1.0
  │   ^^^ Not an Int

exit: 1
```

This would give a visual indicator of the exit code in addition to the error message printed by the program that failed.

Thank you

**Comment by jonathandturner** [comment]
@lpil there's `do -i { }` now, though reading the suggestion it seems like you want a more universal setting rather than something you can wrap around a single command?

**Comment by lpil** [comment]
Yes that's right.

Also I don't want to discard the exit status as `do -i` does, it's purely the visual indicator that I wish to make less distracting

**Comment by lpil** [comment]
This addition is still desired, thank you.

**Comment by carschandler** [comment]
I'd still like to see this option! Plenty of commands give nonzero exit codes when it's really an expected result, like `diff` when two files are different, and it can be annoying to the super verbose error message every time. I rarely care about exit codes unless I'm using them in a script.

**Comment by weirdan** [comment]
@carschandler The option is there:
 https://github.com/nushell/nushell/blob/4907575d3df7370c73c1774b9ccb403c40c2841c/crates/nu-utils/src/sample_config/default_config.nu#L178-L180

**Comment by carschandler** [comment]
@weirdan amazing! Thanks very much.
