### ISSUE TITLE
Change chart command to work as a generic plot

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#3096]
**Is your feature request related to a problem? Please describe.**
Currently, the chart command displays the histogram which makes it problematic if you want to plot generic x/y data.

**Describe the solution you'd like**
I would propose the chart command to just plot data from a table:
```
> let data = $(seq 1 3 | wrap x | merge { seq 4 6 | wrap y } | merge { seq 7 9 | wrap z })
> echo $data
  #   n   foo   bar
────────────────────
  0   1     4     7
  1   2     5     8
  2   3     6     9

> echo $data | chart line n foo
(displays one data line from the `foo` column with `n` column as x-axis)

> echo $data | chart line n foo bar
(displays two data lines from the `foo` and `bar` columns with `n` column as x-axis)

> echo $data | chart line
(takes `n` as x-axis and `foo` as y-axis by default)
```

If you want to display histogram, you can just call the histogram command and pass it to chart: `echo $data | histogram foo | chart foo count`. This way, the functionality of `histogram` and `chart` is decoupled making the chart command more universal.

**Comment by kubouch** [comment]
Would still be cool.

**Comment by jntrnr** [comment]
Removing as I believe `chart` is no longer supported. If this is in error, please re-open.

**Comment by fdncred** [comment]
If anyone is interested in writing a nushell plugin for charting, I saw this crate and thought it would be great for that purpose https://github.com/yuankunzhang/charming
