### ISSUE TITLE
Update modified time of a directory

### ISSUE THREAD

**Issue by janosimas** [nushell/nushell#3098]
**Is your feature request related to a problem? Please describe.**
I want to update the modified time of a directory.

**Describe the solution you'd like**
I expected `touch` to do this.

**Describe alternatives you've considered**
I'm using the external command `^touch` to do this.

**Additional context**
I'm looking for a idiomatic way of doing this.

**Comment by janosimas** [comment]
bump

**Comment by fdncred** [comment]
we'd probably accept a pr to `touch` for this functionality.
