### ISSUE TITLE
Contributor guide list

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#310]
We'd like to write a contributor guide to help people jump in.  Some things that @twe4ked mentioned getting started:

* Cover the difference between WholeStreamCommand and PerItemCommand?
* When do you write a plugin vs a built-in command?
* Best coding practices:
  * eg) avoid using macros unless they are needed, avoid static state initialization, what the clear separation is for plugins and core, etc

**Comment by twe4ked** [comment]
https://book.nushell.sh/metadata explains what tags and spans are for. This could be useful to link from the contributor docs.

**Comment by twe4ked** [comment]
Is https://github.com/nushell/nushell/blob/db125b4318dc10fdc959bd20e1d7baafbe3e094f/.azure/azure-pipelines.yml#L2 the best place to look for what nightly people are developing against? Might be a good thing to list somewhere.

**Comment by thegedge** [comment]
We have a [`CONTRIBUTING.md`](https://github.com/nushell/nushell/blob/master/CONTRIBUTING.md) now, which points to our contributors book. It's been awhile since this was opened too, so we can open new issues for improvements to make to these.
