### ISSUE TITLE
Cannot create alias for setting enviro variables?

### ISSUE THREAD

**Issue by ryanpcmcquen** [nushell/nushell#3108]
**Describe the bug**
Is it possible to set an alias to update or set an environment variable?

**To Reproduce**
```
~
λ alias foo = FOO=~/foo

~
λ foo
error: Command not found
   ┌─ shell:12:1
   │
12 │ foo
   │ ^^^ command not found

```

**Expected behavior**
I would expect this to set the value of `FOO` in the environment.

**Configuration (please complete the following information):**

```
───┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                      Column1
───┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.27.1
 1 │ build_os           │ macos-x86_64
 2 │ rust_version       │ rustc 1.49.0
 3 │ cargo_version      │ cargo 1.49.0
 4 │ pkg_version        │ 0.27.1
 5 │ build_time         │ 2021-02-19 05:44:09
 6 │ build_rust_channel │ release
 7 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip
───┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────
```

**Comment by LhKipp** [comment]
AFAIK: We use `let-env <name> <equals> <expr> {flags} `. There exists a shorthand for running the next command with an additional env var as follows: `<VAR>=<value> cmd`

**Comment by ilius** [comment]
I tried `let-env` in a function, but it seems that the variable is only valid within the function.

There is no way to `export` a variable?
like we do `export FOO` or `export FOO=~/foo` in Bash, and it becomes available shell-wide (and in every sub-shell and program that runs in that shell)

**Comment by LhKipp** [comment]
Environment variables are scoped in nushell. Meaning: Their lifetime is bound to the scope they are set in.
You can use `source` to source a file without creating a new scope (reusing your current scope).

```rust
/home/leo/repos/nushell(move_script_to_nu_engine)> echo $nu.env.FOO
error: Unknown column
  ┌─ shell:3:14
  │
3 │ echo $nu.env.FOO
  │              ^^^ did you mean 'HOME'?

/home/leo/repos/nushell(move_script_to_nu_engine)> source leo/env
/home/leo/repos/nushell(move_script_to_nu_engine)> echo $nu.env.FOO
foo
/home/leo/repos/nushell(move_script_to_nu_engine)> cat leo/env
let-env FOO = foo
```

Your config.toml will also be "`sourced`". Meaning: Everything you set in your startup affects your current scope:
```rust
> cat config.toml
startup = ["let-env BAR = bar"]
> nu
/home/leo/repos/nushell(move_script_to_nu_engine)> echo $nu.env.BAR
bar
```

**Comment by LhKipp** [comment]
> I tried `let-env` in a function, but it seems that the variable is only valid within the function.

Yes, as env-vars are scoped. I personally agree, that is a little odd.



> There is no way to `export` a variable?
> like we do `export FOO` or `export FOO=~/foo` in Bash, and it becomes available shell-wide (and in every sub-shell and program that runs in that shell)

AFAIK: No / Not yet.

**Comment by ilius** [comment]
The lack of export is a problem.

But limitng unexported vars to a scope is good I think.

If you want to set a variable conditionally, you can do `let-env FOO = $(if cond {echo foo} {echo bar})`.
Would be nice to be able to declare a variable though (and set it in inner blocks).

**Comment by ryanpcmcquen** [comment]
Actually, this appears to work as expected:

```
alias foo = let-env FOO = /Users/foo/foo
```

But I can't find a way to echo the change:

```
alias foo = let-env FOO = /Users/foo/foo; echo $nu.env.FOO
```

Nothing is output when I run this.

I even tried adding `autoview`:

```
alias foo = let-env FOO = /Users/foo/foo; echo $nu.env.FOO | autoview
```

**Comment by ilius** [comment]
I think alias definition can not include semi-colon.

**Comment by Fishrock123** [comment]
I just ran into this and from reading the environment docs it is very confusing that `let-env` does not do this.

**Comment by ryanpcmcquen** [comment]
This is working for me:
```
startup = ["alias foo = let-env FOO = /Users/baz.foo/bar"]
```
