### ISSUE TITLE
when I input yes words in nushell, then alway output in terminal 'y'  not stop

### ISSUE THREAD

**Issue by baoyachi** [nushell/nushell#3110]
**Describe the bug**
alway out y not stop

the detail with below

https://user-images.githubusercontent.com/10433001/109255298-ac54cf00-782e-11eb-93cc-25cefbec7f9d.mp4

**Comment by jonathandturner** [comment]
@baoyachi - can you run `which yes`?

**Comment by baoyachi** [comment]
env : macos Big Sur 11.0.1

```bash
➜  ~ which yes
/usr/bin/yes
➜  ~
```

It's seems not nu-shell bug.  yes command alway out y. but I confirm not what does `yes` effect

**Comment by jonathandturner** [comment]
You're correct. The `yes` command outputs 'y' without stop. You can see this when you are outside of nushell. It does seem like a strange command, I agree. I have the same thing in Linux, too.

**Comment by jonathandturner** [comment]
I'll close this as it's not a bug with nushell.
