### ISSUE TITLE
Detect trash support. Allow rm -t flag only if trash supported.

### ISSUE THREAD

**Issue by phuffman** [nushell/nushell#3116]
**Describe the bug**
`rm -t file.txt` deletes file without sending to trash. 

**To Reproduce**
1. Install nu on Mac: `brew install nushell`
2. Delete file with -t flag: `rm -t file.txt`
3. File deleted but not moved to trash (as -t would suggest.)

**Expected behavior**
File moved to trash OR -t flag disallowed.

**Screenshots**

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
 0 │ version            │ 0.27.1
 1 │ build_os           │ macos-x86_64
 2 │ rust_version       │ rustc 1.49.0
 3 │ cargo_version      │ cargo 1.49.0
 4 │ pkg_version        │ 0.27.1
 5 │ build_time         │ 2021-02-19 05:45:20
 6 │ build_rust_channel │ release
 7 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid,
   │                    │ which, zip
```

**Add any other context about the problem here.**

**Comment by jakobnissen** [comment]
Same thing happens to me on GNOME3 on Linux. Good thing I tested it on a dummy file first!
