### ISSUE TITLE
MDF File Support

### ISSUE THREAD

**Issue by schrieveslaach** [nushell/nushell#3129]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Nushell could read data from MDF files ([MS SQL server files](https://en.wikipedia.org/wiki/Microsoft_SQL_Server#Data_storage)) as tables. For example, by using `open database.mdf | …`

I'm working on a [parser crate](https://gitlab.com/schrieveslaach/oxidized-mdf) for MDF files and when I released the first version of it, I want to contribute it as a feature to nushell. The crate is or will be called `oxidized-mdf`

**Describe alternatives you've considered**

`oxidized-mdf`is based on [OrcaMDF](https://github.com/improvedk/OrcaMDF) that has been licensed under GPLv3. Therefore, `oxidized-mdf` is licensed under GPLv3 because it is a derivative work of OrcaMDF. Because of that I'm not sure it can be integrated here because that means that nushell must use GPLv3, right? So in this case MDF support must be provided as a separate plugin, right? 

**Additional context**

**Comment by schrieveslaach** [comment]
Unstale.

**Comment by schrieveslaach** [comment]
Unstale

**Comment by rgwood** [comment]
Hi! I think this functionality would be pretty cool and it would have helped me when I was working with SQL Server daily.

However, these days we're pretty conservative about the functionality we ship built-in. I think MDF support would be a great fit for a Nushell plugin (let us know if you need help writing one) but we're unlikely to build this functionality into Nu.
