### ISSUE TITLE
alias is only able to handle two contiguous strings to the right of the equal sign

### ISSUE THREAD

**Issue by stormasm** [nushell/nushell#3138]
**Describe the bug**
It looks like if you pass more than two strings to the right side of the equal sign with alias
and then type the actual alias command you just entered nushell crashes

**To Reproduce**
1. alias ri = random integer 1..5
2. then type ri
nushell crashes

But this works fine :
alas rx = random integer

The problem is with the 3rd string to the right of the equal sign

I will investigate further and report back here....

@fdncred also reported seeing similar issues with #2933

**Comment by jakevossen5** [comment]
I am not sure if this is related (I can open a seperate issue if needed), but I am struggling to create an alias with multiple commands. In bash, I would do something like `alias brep = 'brew update;brew upgrade'`, but if I then type `brep` in nushell it says command not found. If I remove the quotes, it sets the alias to `brew update` and just runs brew upgrade. Any ideas?

**Comment by jonathandturner** [comment]
yeah, currently `alias` only works when 1:1 with a command you want to expand into.  I wonder if the issue @stormasm is hitting is related to expanding to a subcommand. In truth, I'm betting the alias expansion code just needs to be rewritten to be more robust than it is today.

**Comment by jakevossen5** [comment]
Yeah. I would love to see alias support for multiple commands. Companies I have worked in the past frequently slack around aliases with multiple commands (and I use a few myself) so it would be great if we could get support for these in nushell!

**Comment by jonathandturner** [comment]
@jakevossen5 if you don't need the special expansion semantics of alias, you can use `def` and define your own commands. These would be able to call multiple commands.

**Comment by jakevossen5** [comment]
Yeah, that is what I am going to do for now. Thanks!

**Comment by mvolkmann** [comment]
Here is an example of an alias that causes nu to crash.

```bash
alias cdrust = cd $nu.env.RUST_DIR
```

After defining this, entering `cdrust` gives "thread 'main' panicked at 'index out of bounds: the len is 6 but the index is 6', /Users/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-engine-0.28.0/src/shell/painter.rs:49:13".

**Comment by mvolkmann** [comment]
I think this should remain open. It seems I don't have permission to remove the "Stale" label myself.

**Comment by fdncred** [comment]
This works fine now `alias ri = random integer 1..5` and then running `ri`. Closing. If it's still an issue we can reopen.
