### ISSUE TITLE
Wrong handling of negative numbers

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#3139]
**Describe the bug**
Parser thinks a negative value assigned with `let` is a flag.

It was discovered on Discord but I think it doesn't have an issue yet.

**To Reproduce**
1. `let x = -1`
2. Watch unexpected flag error

**Expected behavior**
Able to assign negative numbers to variables.

**Configuration (please complete the following information):**
0.27.2 (semi-latest main, on my phone now)

**Comment by jonathandturner** [comment]
Workaround for folks who find this issue before we can get to it:

```
let x = (-1)
```

**Comment by kubouch** [comment]
Yep, still happens.

**Comment by jntrnr** [comment]
Fixed in engine-q/latest main
