### ISSUE TITLE
Erlang REPL crashes nushell

### ISSUE THREAD

**Issue by John-Goff** [nushell/nushell#3145]
**Describe the bug**
When closing the Erlang or Elixir REPL, nushell crashes. This happens regardless of whether or not nu is set to the default shell.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Erlang/Elixir
2. Invoke `erl`/`iex` (both exhibit this behaviour)
3. Close via `Ctrl-c Ctrl-c` (or any other method of closing the REPL, all I tested crashed)

**Expected behaviour**
Nushell does not crash

**Screenshots**
```
➤ iex
Erlang/OTP 23 [erts-11.1.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.11.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
^C
➤ 
Error: Io(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" })
```
Where `➤` is my nu prompt.

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
────┬────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────
 #  │      Column0       │                                                 Column1                                                  
────┼────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────
  0 │ version            │ 0.27.1                                                                                                   
  1 │ branch             │ master                                                                                                   
  2 │ short_commit       │ 49ac14b7                                                                                                 
  3 │ commit_hash        │ 49ac14b73426b4a9f4619d2807960dd9d53297a7                                                                 
  4 │ commit_date        │ 2021-02-19 06:05:02                                                                                      
  5 │ build_os           │ linux-x86_64                                                                                             
  6 │ rust_version       │ rustc 1.50.0                                                                                             
  7 │ cargo_version      │ cargo 1.50.0                                                                                             
  8 │ pkg_version        │ 0.27.1                                                                                                   
  9 │ build_time         │ 2021-03-06 20:00:40                                                                                      
 10 │ build_rust_channel │ release                                                                                                  
 11 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, trash, uuid, which, zip 
────┴────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────

```

**Comment by fdncred** [comment]
I wonder if it has anything to do with `ctrlc_exit` https://www.nushell.sh/book/configuration.html#nushell-configuration-with-config-toml

**Comment by John-Goff** [comment]
I just tried explicitly setting that to both true and false and the issue still persists. As well, if I start `node` and press `Ctrl-c Ctrl-c` nushell does not exit.

**Comment by John-Goff** [comment]
This issue is still occurring on nushell version 0.33.0. When I start `erl` or `iex` from within nushell, then press `Ctrl-C Ctrl-C` to exit the repl, nu crashes with 
```
Error: Io(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" })
```
same as before. But when I stop the `erl` repl by pressing `Ctrl-g q <RET>` then nu does not crash. Perhaps it has something to do with how the BEAM exits? Not sure what the difference between the two stopping mechanisms is, but I don't think either should crash the shell.

**Comment by John-Goff** [comment]
Issue is still present on nushell version 0.37.0.

**Comment by valeth** [comment]
This still occurs in version 0.41.0

It is showing an IO error for a split second before closing.

![mpv-shot0001](https://user-images.githubusercontent.com/3198362/145848730-7e192dc7-9101-490e-aa8e-26c12c67e2a6.jpg)

**Comment by valeth** [comment]
Another maybe interesting observation.
If I run it through another shell (like `sh -c 'erl'`) and try to exit it the same way it will crash.
But if I start a new interactive shell like `sh` first and then run `erl` it will not crash.
It's a workaround, but I would prefer not having to use it.

**Comment by fdncred** [comment]
it sounds like `erl` is exiting in some weird way. i'm not sure how to fix this other than adding an issue on the erl repo.

**Comment by valeth** [comment]
Found another oddity, and this might be related because erlang uses shellscript wrappers.
When I run an `sh` shell inside nu, and then send it a SIGKILL, it prints an `Errno(EIO)` and then exits like with `erl`.

**Comment by John-Goff** [comment]
Just tested with the latest `main` after engine-q was merged, issue appears to be resolved. Thanks everyone!
