### ISSUE TITLE
Substituion does not work inside paths

### ISSUE THREAD

**Issue by codic12** [nushell/nushell#3152]
**Describe the bug**
If 
```
let E = 'e'
```
and `/e, ./e` exist, then:
```
cd $E
``` 
works, but
```
cd /$E
```
fails.

**To Reproduce**
1. Declare a variable with `let`.
2. Try making a directory with the variable's value as it's name in the current directory.
3. Try `cd`ing using the variable name, eg `cd $E`
4. Now try making a directory with the variable's name somewhere not in the cwd, eg inside in your new directory.
5. Try `cd`ing using the variable name, eg `cd e/$E`.

**Expected behavior**
I can use variable substitution, like $E, within a path. I'm not sure if it's a bug or a feature, if this is purposefully not implemented feel free to close this!

**Configuration (please complete the following information):**

```
───┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                      Column1                                       
───┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.28.0                                                                             
 1 │ build_os           │ linux-x86_64                                                                       
 2 │ rust_version       │ rustc 1.50.0 (Fedora 1.50.0-1.fc33)                                                
 3 │ cargo_version      │ cargo 1.50.0                                                                       
 4 │ pkg_version        │ 0.28.0                                                                             
 5 │ build_time         │ 2021-03-09 22:16:36                                                                
 6 │ build_rust_channel │ release                                                                            
 7 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip 
───┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────
```

**Comment by ahkrr** [comment]
From my perspective this is a feature not a bug because other things are also not supported
``` sh
let TEST = word
echo $TEST       # prints word
echo ./$TEST     # prints ./$TEST
echo $(build-string ./ $TEST) # prints ./word
cd $(build-string ./ $TEST)   # attempts to cd
```
As long as the $ sign doesn't appear at the beginning no substitution happens. 
Like in the example, if one really wants to build a path they can do it explicitly. 
The $ sign has bitten me in my bash and zsh times more often that it should have and i like the explicitness even though it adds extra typing from time to time.

**Comment by codic12** [comment]
That's an interesting viewpoint. I didn't know about build-string, thanks!

**Comment by codic12** [comment]
Closing this, I don't think it's a bug
