### ISSUE TITLE
ls ignores secured files/directories

### ISSUE THREAD

**Issue by tiffany352** [nushell/nushell#3157]
**Describe the bug**
When the current user doesn't have access to open a file or directory, `ls` seems to ignore them entirely and not count towards the file list. Leads to some surprising situations.

**To Reproduce**
1. Use a Linux system. Might happen on Windows or macOS system too but I haven't tried.
2. Find a directory that's locked down. In particular, owned by a different user with permissions like 700.
3. Try to run `ls` and observe that the directory appears empty.

**Expected behavior**
It should indicate somehow that there are files with permission errors present.

**Screenshots**
![image](https://user-images.githubusercontent.com/1254344/110749629-39683280-81f6-11eb-8b7a-ec158224369d.png)

**Configuration (please complete the following information):**
```
❯ version | pivot
───┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                      Column1
───┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.28.0
 1 │ build_os           │ linux-x86_64
 2 │ rust_version       │ rustc 1.50.0 (Fedora 1.50.0-1.fc33)
 3 │ cargo_version      │ cargo 1.50.0
 4 │ pkg_version        │ 0.28.0
 5 │ build_time         │ 2021-03-09 22:16:36
 6 │ build_rust_channel │ release
 7 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip
───┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────
```

Ran into this on Fedora 33. `nushell-0.28.0-1.fc33.src.rpm` installed via `copr:copr.fedorainfracloud.org:atim:nushell`. 

**Add any other context about the problem here.**

`du` has a similar problem in that it miscounts directories when there's permissions errors. It does expose this information, but not in an easy to notice way.
![image](https://user-images.githubusercontent.com/1254344/110748952-46d0ed00-81f5-11eb-97ad-8f7f12f39fe5.png)

**Comment by luccasmmg** [comment]
Just passing by to say that im currently working on this now, the only thing that is missing is how to display the current permissions of the file in a rwx format(ex: 700)
