### ISSUE TITLE
cp, mv, and rm commands need to support -i flag

### ISSUE THREAD

**Issue by mvolkmann** [nushell/nushell#3162]
**Is your feature request related to a problem? Please describe.**
To protect me from myself I like to use the `-i` option of these commands to prompt for confirmation.

**Describe the solution you'd like**
Add support for the `-i` flag to the cp, mv, and rm commands.

**Comment by mvolkmann** [comment]
I see that I can define aliases like this: `alias rm = ^rm -i`
But it would be nice to not need to not need to do that.

**Comment by fdncred** [comment]
I don't run linux typically. What do the `-i` flags do?

**Comment by mvolkmann** [comment]
If I enter `rm -i some-file.txt`, it prompts me with "remove some-file.txt?" and I have to type "y" to get it to delete the file. I alias the `rm` command to `rm -i` so it just always does this.

**Comment by mvolkmann** [comment]
I think this should remain open. It seems I don't have permission to remove the "Stale" label myself.

**Comment by GabrielBG0** [comment]
hey, since this feature was moved over to engine-q what should we do about this issue? should I create a new one on the engine-q's repo?

**Comment by onsah** [comment]
It looks like changes are in engine-q. Should this issue closed?

**Comment by jntrnr** [comment]
@onsah - I think what we'll do for the issues fixed by e-q is to merge e-q into nushell, and after that go through all the issues tagged as "will be fixed by engine-q" and make sure they're fixed. If so, go ahead and close them then.

**Comment by onsah** [comment]
Oh, I didn't know the process. Thanks for giving the information!

**Comment by jntrnr** [comment]
We had some support for this in engine-q, but I recently rewrote it and ported the nushell commands more closely because of some semantic differences.

We'll need to add back in the interactive flag based on the ported logic.

**Comment by GabrielBG0** [comment]
is the way I designed it (the interaction by it self) good enough or do you guys have any suggestions?

**Comment by jntrnr** [comment]
Okay, I think the translation went okay. If folks want to work on the interactive mode, we can work on that again based on the newer versions of the commands.

**Comment by njbull4** [comment]
Hi :wave:, I'd like to take a crack at this if no one is actively working on it

**Comment by GabrielBG0** [comment]
Hey, if u get it, there is still code that I wrote that u can use, its on the útil file its the get_interactive_confirmation function. It should take care of the interactive portion of the problem.

**Comment by njbull4** [comment]
Thanks @GabrielBG0. Using your PR into engine-q as reference and will utilize the get_interactive_confirmation function from the latest code :thumbsup:

**Comment by fdncred** [comment]
go for it @njbull4. thanks!

**Comment by njbull4** [comment]
Hi guys, started a draft PR with rm implementation. 

I'm having some trouble adding tests using interactive mode. I attempted using the nu! macro for test setup but see that it does not write to stdin so was unable to inject mock user input. Is there another existing test util I can use to accomplish this or should I write my own?

**Comment by fdncred** [comment]
I'm not really sure how we'd test interactive mode? You may want to look at the tests for 0.44 for interactive mode. You can download the old source code from the repo releases section. If there aren't any there we can probably move foward without any but you may find something.

**Comment by GabrielBG0** [comment]
If I remember correctly sisce interactive is more like a ui fearure I didn't write any tests for it, I tested locally and asked people to teste it before merging it

**Comment by njbull4** [comment]
Hi everyone, 
I trawled through the 0.44 source code in search of tests using interactive mode, to no avail. I went ahead and finished the implementation without tests, and opened the PR for review.

**Comment by hustcer** [comment]
Closed by https://github.com/nushell/nushell/pull/5523
