### ISSUE TITLE
New plugins are not found in MacOS Brew installation

### ISSUE THREAD

**Issue by elferherrera** [nushell/nushell#3165]
I installed nushell via brew because I couldn't compile the crate in this mac (errors with curl from macports and not having root access). Anyway, I created a new plugin following the tutorial and to my surprise `nu` didn't find the new command. I can see that it is being loaded to the list of plugins

![image](https://user-images.githubusercontent.com/6942205/111029505-d55f8d00-83f4-11eb-9039-9f7a1cd74ed8.png)

but the new command is no where to be seen 

![image](https://user-images.githubusercontent.com/6942205/111029532-093ab280-83f5-11eb-970b-0e62355363b1.png)

I followed the same example in a debian container and the plugin works fine. However, in this container I was able to `cargo install` the crate.

Any suggestions to load the plugins in MacOS?
Or, how to compile the crate without removing curl from macports?

**Comment by fdncred** [comment]
I think I've seen this before. The plugins need to be in the same directory as `nu`. Have you tried that?

**Comment by elferherrera** [comment]
Yeap, that did it. I moved the binary to `nu`'s folder. Thanks.

**Comment by fdncred** [comment]
no problem. i'm not sure why brew does this. i've also heard of people leaving the files wherever brew puts them and then creating symbolic links to the folder where nu is.

closing as this appears to be resolved.

**Comment by elferherrera** [comment]
btw, I found that if I add the .cargo/bin folder to the the `plugin_dirs` option from the configuration file, then the new plugins and their functions are included to nushell

**Comment by fdncred** [comment]
yup, that's true too. I forgot about that.
