### ISSUE TITLE
textview settings not working

### ISSUE THREAD

**Issue by mvolkmann** [nushell/nushell#3171]
It seems that none of the settings in the `[textview]` section work.
Perhaps I'm doing something wrong.
I have this in my config file:

```toml
[textview]
grid = false
header = false
line_numbers = false
theme = "TwoDark"
true_color = true
vcs_modification_markers = true
use_italics = true
```

After changing my config file, I exited the shell and started a new one so the changes would take effect.
In particular, the `ls` command outputs a table that has a header and the line number column despite me turning off those options. Grid lines are also rendered.
I'm not sure what changes I should expect to see from the other options, but I don't see any differences.

**Configuration:**

│ 0 │ version            │ 0.28.0                                                                             │
│ 1 │ build_os           │ macos-x86_64                                                                       │
│ 2 │ rust_version       │ rustc 1.50.0 (cb75ad5db 2021-02-10)                                                │
│ 3 │ rust_channel       │ stable-x86_64-apple-darwin (default)                                               │
│ 4 │ cargo_version      │ cargo 1.50.0 (f04e7fab7 2021-02-04)                                                │
│ 5 │ pkg_version        │ 0.28.0                                                                             │
│ 6 │ build_time         │ 2021-03-10 19:48:28                                                                │
│ 7 │ build_rust_channel │ release                                                                            │
│ 8 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip │

**Comment by fdncred** [comment]
The `[textview]` are settings that are configured to view text files with our integration with the `bat` crate. If you want to change the settings of the table you can look at the `[color_config]` section. We have some documentation on what the config file options are [here](https://www.nushell.sh/book/configuration.html),

**Comment by fdncred** [comment]
please reopen if that didn't answer your questions.
