### ISSUE TITLE
documenting custom commands in startup config

### ISSUE THREAD

**Issue by mvolkmann** [nushell/nushell#3176]
**Describe the bug**
I understand how I can add documentation to custom commands for the command and each parameter.
But it seems I can't do that in the `startup` value in the config file.
Can I define custom commands in a `.nu` file and source that from the config file?
When a new shell starts, I'd like to be able to view documentation for a custom command using the `help` command.

**Configuration (please complete the following information):**

version,0.28.0
build_os,macos-x86_64
rust_version,rustc 1.50.0 (cb75ad5db 2021-02-10)
rust_channel,stable-x86_64-apple-darwin (default)
cargo_version,cargo 1.50.0 (f04e7fab7 2021-02-04)
pkg_version,0.28.0
build_time,2021-03-10 19:48:28
build_rust_channel,release
features,"ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip"
```


**Add any other context about the problem here.**

**Comment by danielRi** [comment]
Is this possible by now. Im also looking to how achieve this, Im on `0.60.0`

**Comment by hustcer** [comment]
> Is this possible by now? Im also looking to how to achieve this, Im on `0.60.0`

You can add custom commands in the config file located at `$nu.config-path`, just like this: https://github.com/nushell/nushell/blob/fa0400c3f29763d91cb944b172b9575ab5805a10/docs/sample_config/default_config.nu#L3

**Comment by danielRi** [comment]
Hey! Thanks for the help! Sorry, may I asks this: Is it possible to load them for external files too?

I saw the config file has this part:
```let-env NU_LIB_DIRS = [
    ($nu.config-path | path dirname | path join 'scripts')
]
```

To my understanding, I thought I can just put `.nu` scripts to this folder `($nu.config-path | path dirname | path join 'scripts')`, and then I can call the scripts from anywhere after nu startup, by calling `nu script.nu`. This doesnt seem to work. I also tried to put `use script.nu` or `source script.nu` to the config file, but no luck. 

Am I doing something wrong or did I misunderstand this?

**Comment by hustcer** [comment]
@danielRi I think you are right, maybe this feature need more polish, any more comments on this? @kubouch

**Comment by kubouch** [comment]
NU_LIB_DIRS currently doesn't work in config.nu because of this: https://www.nushell.sh/book/thinking_in_nushell.html#parsing-and-evaluation-are-different-stages . I'm planning to hard-code the default value so it would be possible.

The NU_LIB_DIRS expansion currently works only for use, source and register commands. We could add it also to the beginning of Nushell so when you run `nu script.nu` it would look it up.

**Comment by danielRi** [comment]
Thanks so much for the fast updates. Asolutely hyped for nushell, keep it up 👍
