### ISSUE TITLE
Support viewing exit status of previous command

### ISSUE THREAD

**Issue by jakevossen5** [nushell/nushell#3185]
**Is your feature request related to a problem? Please describe.**
I would like to know what the exit code of the commands I run are

**Describe the solution you'd like**
I would like to be able to run `echo $?`, and see the exit status of the command that just ran

**Describe alternatives you've considered**
Maybe instead of `$?` we could do something like `$nu-exit-code`? or `$exit-code`? 

**Additional context**
This might part of a larger process to match these: https://www.gnu.org/software/bash/manual/html_node/Special-Parameters.html#Special-Parameters

A lot of shells also have a `x` or something to indicate the previous command failed. `startship` for example uses this to turn the prompt red if there is a non-zero exit status

**Comment by steveklabnik** [comment]
I also ran into this today.

**Comment by hustcer** [comment]
+1

**Comment by jntrnr** [comment]
This is now supported in latest main with the `LAST_EXIT_CODE` environment variable

**Comment by 71** [comment]
Any way to access `LAST_EXIT_CODE` after `let`? `bash -c 'exit 1'; $env.LAST_EXIT_CODE` is `1`, but `let x = bash -c 'exit 1'; $env.LAST_EXIT_CODE` is `0`. `complete` is out of the question because I want to stream the output.
