### ISSUE TITLE
version 0.28: alias not working? 

### ISSUE THREAD

**Issue by martinrode** [nushell/nushell#3187]
**Describe the bug**
The alias command as described in the documentation is not working in my Nu.

**To Reproduce**
1. help alias
2. alias

**Expected behavior**
"alias" is not known in my version 0.28. I expect this to exist, cause its documented.

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot

───┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                      Column1                                       
───┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.28.0                                                                             
 1 │ build_os           │ macos-x86_64                                                                       
 2 │ rust_version       │ rustc 1.50.0                                                                       
 3 │ cargo_version      │ cargo 1.50.0                                                                       
 4 │ pkg_version        │ 0.28.0                                                                             
 5 │ build_time         │ 2021-03-09 22:34:29                                                                
 6 │ build_rust_channel │ release                                                                            
 7 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip 
───┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**

**Comment by fdncred** [comment]
the `alias` command was removed a few releases ago and our documentation hasn't caught up. you can [read about it here](https://www.nushell.sh/blog/2021-01-05-nushell_0_25.html#aliases). however, you can still define an alias in your config.toml file or on the command line, like this `alias l = ls -l`

**Comment by martinrode** [comment]
Fair enough, but what are we supposed to use instead?

(BTW: Fastest "close" in my life ;-))

**Comment by fdncred** [comment]
> Fair enough, but what are we supposed to use instead?

I don't understand. I explained how to use `alias` in 0.28.0 two ways, in the config.toml and on the command line and also provided a documentation link. which part am i misunderstanding?

> (BTW: Fastest "close" in my life ;-))

lolz

**Comment by martinrode** [comment]
Ok, got ya. Its not a "command" anymore but you did not discontinue the built-in (or however you call this now).

**Comment by fdncred** [comment]
we just changed the way `alias` works.
