### ISSUE TITLE
data extraction: table from deeply nested data possible?

### ISSUE THREAD

**Issue by martinrode** [nushell/nushell#3191]
**Is your feature request related to a problem? Please describe.**
I am working with huge JSON objects (received from a web API) and read the data using `from json`.

When I now want to access that data, I can use "get" to extract.

My problem now is that the deeply nested structure like

```json
{
"objects": [
  {
     "object": {
           "_id": 1,
           "reference": "ref1"
     },
     "object": {
           "_id": 2,
           "reference": "ref2"
     },
     "object": {
           "_id": 3,
           "reference": "ref2"
     }
  }
]
}
```

With `get` i can do `get objects.object._id objects.object.reference` which gives me one column list:

|d|
|--|
|1|
|ref1|
|2|
|ref2|
|3|
|ref3|

**Describe the solution you'd like**

What I would like to extract is:

|_id|reference|
|--|--|
|1|ref1|
|2|ref2|
|3|ref3|

**Describe alternatives you've considered**

Using a third party tool (again) to work with JSON...

**Comment by ahkrr** [comment]
I am not working with json myself, but did you try 

```
select objects.object._id objects.object.reference 
```
```
> help get
Open given cells as text.
...
```
```
> help select
Down-select table to only these columns.
...
```

**Comment by martinrode** [comment]
nice! "select" is exactly what i need. slowly becoming a fan...

**Comment by andrasio** [comment]
@martinrode take `flatten` for a spin, too. `group-by` too.
