### ISSUE TITLE
SyntaxError when running python script

### ISSUE THREAD

**Issue by elferherrera** [nushell/nushell#3192]
**Describe the bug**
When running a python script I get a SyntaxError

**To Reproduce**
1. Using this script:
``` python
def create_name() -> str:
  return "some name"
       
if __name__ == "__main__":
  a = create_name()
  print(f"{a} do something")
```
2. Run script using `python test.py`

**Expected behavior**
To print the string to terminal

**Screenshots**
![image](https://user-images.githubusercontent.com/6942205/111604502-4cb66780-87cd-11eb-85d7-b1f837ee841d.png)

**Configuration (please complete the following information):**

```
> version | pivot
╭───┬────────────────────┬───────────────────────────────────────────────────────────────────────╮
│ # │ Column0            │ Column1                                                               │
├───┼────────────────────┼───────────────────────────────────────────────────────────────────────┤
│ 0 │ version            │ 0.27.1                                                                │
│ 1 │ build_os           │ linux-x86_64                                                    
│ 2 │ rust_version       │ rustc 1.49.0 (e1884a8e3 2020-12-29)         
│ 3 │ cargo_version      │ cargo 1.49.0 (d00d64df9 2020-12-05)      
│ 4 │ pkg_version        │ 0.27.1                                                                
│ 5 │ build_time         │  2021-02-20 12:37:33                                     
│ 6 │ build_rust_channel │ release                                                       
│ 7 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline,  
│   │                    │     term, uuid, which, zip                              
╰───┴────────────────────┴───────────────────────────────────────────────────────────────────────╯
```

**Add any other context about the problem here.**

**Comment by jonathandturner** [comment]
@elferherrera this script works the same for me inside and outside of Nushell. Can you run `python -v` from inside Nushell and confirm it's the same one that's found outside of Nushell?

**Comment by elferherrera** [comment]
@jonathandturner you are right. Inside Nushell python 2.7 is called, and outside python 3.8. I would guess inside Nushell I have another alias for `python`. 
Is there a way to fix this?

**Comment by jonathandturner** [comment]
@elferherrera what might be happening is that nushell is using a different path than what is used outside of nushell. It's also possible that outside of nushell you may be using a virtualenv, that this isn't working the same way in nushell.

You can alias python yourself using the `alias` command like: `alias python = /usr/bin/python3`

**Comment by elferherrera** [comment]
@jonathandturner yeap, that did the trick. Thanks a lot. 

Btw, Is there a way to automatically create this python alias when working in a virtual env?
something like `alias python = myenv/bin/python3`
