### ISSUE TITLE
some aliases crash shell

### ISSUE THREAD

**Issue by mvolkmann** [nushell/nushell#3194]
I have the following aliases defined in my Nushell config file:

```bash
startup = [
  "alias pull = git pull origin $(git rev-parse --abbrev-ref HEAD)",
  "alias push = git push origin $(git rev-parse --abbrev-ref HEAD)"
]
```

When I type either one, the shell crashes and the terminal window closes before I press return.
But if I enter  the same commands manually, they work fine.
Any idea why this would happen?

**Comment by stormasm** [comment]
https://github.com/nushell/nushell/issues/3138
may be relevant to this issue....

**Comment by martinrode** [comment]
```
startup = [
    "alias api6 = ~/go/src/github.com/programmfabrik/apitest/apitest --limit-response=0 -c ~/go/src/github.com/programmfabrik/fylr/cmd/fylr/fylr.yml --curl-bash --stop-on-fail",
    "alias cdgo = cd ~/go/src/github.com/programmfabrik/fylr",
    "nu /Users/martin/.nu/gl.nu"
]
```

This crashed my startup too.

gl.nu:
```
def gl [] {
    git log --pretty=%h»¦«%s»¦«%aN»¦«%aE»¦«%aD -n 5 | lines | split column "»¦«" commit subject name email date | update date { get date | str to-datetime }
}
}}}

Also, using "|" inside an alias does not work for me...

**Comment by kubouch** [comment]
@martinrode A side note, doesn't probably solve the crashing: You probably want to `source /Users/martin/.nu/gl.nu`, instead of `nu /Users/martin/.nu/gl.nu` -- the latter would just run the file without exporting the `gl` command into the current scope.

**Comment by jonathandturner** [comment]
Aliases should be a bit more stable now. Are you seeing the same issue on recent releases?

**Comment by jonathandturner** [comment]
Closing since we improved this, but please reopen if you're still experiencing issues.
