### ISSUE TITLE
table parsing issue

### ISSUE THREAD

**Issue by mvolkmann** [nushell/nushell#3204]
**Describe the bug**

It seems like parsing of the table syntax is very picky about the placement of newlines.

**Steps To Reproduce**

Enter the following:

```bash
echo [[foo bar]; [1 2]] # fine

echo [[foo bar]; [
  1 2]
] # fine

echo [
  [foo bar];
  [1 2]
] # not fine
```

The first two produce the expected table output, but the third does not. It should produce the same output.

![Nushell-table-parsing](https://user-images.githubusercontent.com/79312/111924754-05053980-8a74-11eb-93cf-e645c7788f67.png)

**Comment by stormasm** [comment]
#2972 this might be related to your issue...

**Comment by mvolkmann** [comment]
I think this is a serious issue and should remain open. It seems I don't have permission to remove the "Stale" label myself.
