### ISSUE TITLE
describe command should return actual data type names

### ISSUE THREAD

**Issue by mvolkmann** [nushell/nushell#3206]
When `describe` is called on a custom command parameter with a type of `int` it returns `integer`.
I think it should return `int` instead.
I'm not sure if this is an issue with any other data types.

```bash
def demo [n: int] {
  echo $n | describe # outputs "integer"
}

demo 3
```

**Comment by mvolkmann** [comment]
In addition it would be nice if the `describe` command could return the names of structured data types like `list` and `table`.

**Comment by mvolkmann** [comment]
I think this should remain open. It seems I don't have permission to remove the "Stale" label myself.

**Comment by fdncred** [comment]
In 0.59.1 it returns `int`
```
> def demo [n: int] {
   echo $n | describe # outputs "integer"
}

> demo 1 
int
```
