### ISSUE TITLE
how to break loop for some conditon?

### ISSUE THREAD

**Issue by gongmingbin** [nushell/nushell#3208]
it possible to `break`  loop for some condition?  or  something like while(condition)?
```
while(conditon){
  dosomthing()
}
# or 
while(true){
  if(conditon){
    break
}
}

_Originally posted by @gongmingbin in https://github.com/nushell/nushell/issues/2883#issuecomment-798681336_

**Comment by fdncred** [comment]
we don't have `while` yet. We have `if` where you can check conditions.

**Comment by gongmingbin** [comment]
> we don't have `while` yet. We have `if` where you can check conditions. I don't believe we have a `break` command either.

but without while, how to  do something like that in bash?
```bash
do_until_success() {
  res=-1
  while [[  ! $res -eq 0 ]]; do
    $@
    res=$?
  done
}
```

**Comment by fdncred** [comment]
ya, i think `recursive` may be the only way.
