### ISSUE TITLE
Cannot abort commands with Control + c

### ISSUE THREAD

**Issue by alexherbo2** [nushell/nushell#3212]
### Steps

1. Enter `sleep 1hr; systemctl suspend`.
2. Press <kbd>Control</kbd> + <kbd>c</kbd> to abort.

### Outcome

`sleep 1hr` is aborted and `systemctl suspend` is executed.

### Expected

Abort all commands.

**Comment by jonathandturner** [comment]
You can break `sleep` with ctrl+c now. Going ahead and closing.
