### ISSUE TITLE
histogram percentages wrong

### ISSUE THREAD

**Issue by mvolkmann** [nushell/nushell#3215]
**Describe the bug**
The percentages reported by the histogram command are wrong.

**To Reproduce**

```bash
# The newlines need to be placed like this
# due to a parser bug.
let data = [
  [name color]; [
  Mark yellow] [
  Tami blue] [
  Amanda green] [
  Jeremy yellow] [
  Sally blue] [
  Sam yellow]
]
echo $data | get color | histogram
```

This code produces the following table:

```text
╭───┬────────┬───────┬────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ # │ value  │ count │ percentage │ frequency                                                                                           │
├───┼────────┼───────┼────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 0 │ blue   │     2 │ 66.67%     │ ******************************************************************                                  │
│ 1 │ green  │     1 │ 33.33%     │ *********************************                                                                   │
│ 2 │ yellow │     3 │ 100.00%    │ *************************************************************************************************** │
╰───┴────────┴───────┴────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Expected behavior**

The percentages are double what they should be. They should be 33.33%, 16.67%, and 50%.

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
╭───┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────╮
│ # │ Column0            │ Column1                                                                            │
├───┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────┤
│ 0 │ version            │ 0.28.0                                                                             │
│ 1 │ build_os           │ macos-x86_64                                                                       │
│ 2 │ rust_version       │ rustc 1.50.0 (cb75ad5db 2021-02-10)                                                │
│ 3 │ rust_channel       │ stable-x86_64-apple-darwin (default)                                               │
│ 4 │ cargo_version      │ cargo 1.50.0 (f04e7fab7 2021-02-04)                                                │
│ 5 │ pkg_version        │ 0.28.0                                                                             │
│ 6 │ build_time         │ 2021-03-14 18:08:55                                                                │
│ 7 │ build_rust_channel │ release                                                                            │
│ 8 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip │
╰───┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by mvolkmann** [comment]
Unrelated, but it would be nice if `histogram` had a flag to control the width of the `frequency` column it produces.

**Comment by andrasio** [comment]
@mvolkmann Whoa, thanks! You are right. It's giving percentages relative to the highest one and not exactly what histogram should be doing. (What would you call this instead? if it were to be a command, too)

**Comment by mvolkmann** [comment]
Is the fix to change line 80 in crates/nu-data/src/utils/mod.rs to pass the total as the first argument instead `maxima`?

I don't know what the official name is for computing percentages based on the maximum value. I wonder if that variation is needed.

**Comment by fdncred** [comment]
@andrasio @mvolkmann I believe what the histogram is doing is called `percentage frequency`, which is a real thing.

**Comment by mvolkmann** [comment]
Maybe the `histogram` command should accept a flag to indicate which form of percentages are desired with whichever one is most common being the default.

**Comment by fdncred** [comment]
yes, i agree on the flag.

**Comment by kubouch** [comment]
@andrasio I think it could be called `normalize`: When you divide each column count with the total element count so they all sum up to 100%.

**Comment by mvolkmann** [comment]
I think this should remain open. It seems I don't have permission to remove the "Stale" label myself.

**Comment by WindSoilder** [comment]
@mvolkmann Hi, for now the default calculate method is changed in the main branch, would you please verify it?

**Comment by kubouch** [comment]
Seems like it's fixed by https://github.com/nushell/nushell/pull/5518 . Please reopen or make a new issue if there are some future problems with the new histogram.
