### ISSUE TITLE
Wishlist: A collection of features that I wish existed in Bash/Zsh and hope that Nu implements them too

### ISSUE THREAD

**Issue by KSXGitHub** [nushell/nushell#3228]
Some of the following wishes may have already been implemented by Nu, but I will list them anyway.

1. I wish I can inspect the places (which lines of code from which files) where a certain identifier (variable, function, or alias) is defined and redefined.
2. I wish I can inspect the places where a certain environment variable is mutated.
3. I wish startup files (`.bash_profile`, `.bashrc`, `.zshrc`, etc.) are without side-effect.
4. I wish zsh and bash don't rely solely on startup files for configuration, but also use machine writable formats (such JSON, YAML, TOML, etc.) so that software distributors may find an easier way to install/uninstall their tools to/from the system.
5. I wish "importing modules" (via `source`) does not change depending on working directory, but instead, the relative position of the module files.
6. I wish every module has its own namespace to avoid name collision and to allow sharing libraries without worrying about names.
7. I wish I don't have to wrap double-quotes around environment variables when I use them, it's annoying.
8. I wish startup is faster. Startup files are mostly to blame, but there are no alternatives.

There could be more, but I can't think of them at the moment.

**Comment by mhmdanas** [comment]
Speaking as somebody who's got some experience with triaging issues, I think many maintainers would highly appreciate if these requests each get their own issue (check for existing issues of course!). Maybe Nu's maintainers are fine with this, but I thought I'd say this anyway.

**Comment by KSXGitHub** [comment]
@mhmdanas I don't want to appear as a spammer.

**Comment by mhmdanas** [comment]
@KSXGitHub would you appear as a spammer if you opened a number of legitimate issues? I don't think so. But in the end, it's up to the maintainers if they don't mind this type of issues.

**Comment by KSXGitHub** [comment]
@mhmdanas I rather not second guessing every single maintainer's personality. Anyway, could you please hide your comments as off-topic? I shall hide mine.
