### ISSUE TITLE
using source in config.toml sometimes fails in 0.29.1

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#3236]
**Describe the bug**
The problem is using `source` in the config.toml sometimes creates an error like the below image.
![image](https://user-images.githubusercontent.com/343840/113153886-1fba7980-91fd-11eb-82c0-92ae220b7722.png)

The odd part is that, in the below config.toml snippet, the alias part succeeds but the prompt part fails.
```toml
startup = [
    "source C:\\Users\\dschroeder\\source\\repos\\forks\\nu_scripts\\prompt\\left_and_right_prompt.nu",
    "source C:\\Users\\dschroeder\\AppData\\Roaming\\nushell\\nu\\config\\aliases.nu",
```

the aliases.nu file contains this
```
alias ll = ls -al
alias la = ls -a
```

the left_and_right_prompt.nu and be found [here in the nu_scripts repo](https://github.com/nushell/nu_scripts/blob/main/prompt/left_and_right_prompt.nu)

If I source the file after the startup fails, things seem to work again.
![image](https://user-images.githubusercontent.com/343840/113154391-9788a400-91fd-11eb-9865-8929dd49dc3d.png)

This may or may not be related to #3041 since I started seeing problems after it was merged.

|key|value|
|-|-|
|version|0.29.1|
|branch|main|
|short_commit|14169c01|
|commit_hash|'14169c01efd15d549ac7cff730740965bff1e911'|
|commit_date|2021-03-31 08:04:52|
|build_os|windows-x86_64|
|rust_version|rustc 1.51.0 (2fd73fabe 2021-03-23)|
|rust_channel|stable (default)|
|cargo_version|cargo 1.51.0 (43b129a20 2021-03-16)|
|pkg_version|0.29.1|
|build_time|2021-03-31 08:09:15|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, trash, uuid, which, zip|

**Comment by LhKipp** [comment]
The problem in a nutshell here is:
in config.toml:
```nu
startup = ["source prompt.nu", "def x [dir] {...}"]
```
In `prompt.nu`
```nu
def prompt [] {...}

def x [] {...}
```

Because nu differentiates functions only by their name and everything in startup gets sourced, the later define of `x` overwrites the correct one.

**Comment by fdncred** [comment]
I'm closing this issue. Here's the problem and solution.

Problem:
1. I had these custom commands defined in both my config.toml and a script that I was sourcing at the top of my config.toml (git_br, set_titls_str git_abbrev_pwd_win, git_abbrev_pwd_lin, set_title)
2. since the script was being sourced in the first line, all these commands in the config.toml were overwritting the script commands with the exact same name.
3. so the script wasn't working because they were overwritten with older versions.

Solution:
1. I commented out all the config.toml duplicate custom command names
2. and everything works better now. it's just surprising that it worked at all previously.

Thanks to @LhKipp for helping figure this out!
