### ISSUE TITLE
Display error message when the configuration is successfully updated

### ISSUE THREAD

**Issue by nibon7** [nushell/nushell#3244]
**Describe the bug**
nu shows ```error: Error: Can't update frame with tag Some("/home/nibon7/.config/nu/config.toml"). No such frame present!``` when update config item. It was introduced by commit c42b5887.

**To Reproduce**
1. ```config set edit_mode "vi"```
2. ```config set edit_mode "emacs"```

**Expected behavior**
Don't display error message when the configuration is successfully updated

**Comment by LhKipp** [comment]
This happens repeatedly after you used config set once, right? Thanks for reporting this issue, it slipped through :(

**Comment by nibon7** [comment]
> This happens repeatedly after you used config set once, right? Thanks for reporting this issue, it slipped through :(

It was fixed.Thanks!😎
