### ISSUE TITLE
f32 and f64 values

### ISSUE THREAD

**Issue by sunfishcode** [nushell/nushell#3245]
I'm looking to use nu to process some data I have which contains `f32` and `f64` values. An `UntaggedValue` can be constructed from an `f32` or an `f64`, however it doesn't appear to preserve `f32` or `f64` values. For example, the assert in this code fails:

```rust
use bigdecimal::ToPrimitive;
use nu_protocol::UntaggedValue;
use nu_protocol::Primitive;

fn main() {
    let a: f64 = 0.1;
    let val = UntaggedValue::from(a);
    let dec = match val {
        UntaggedValue::Primitive(Primitive::Decimal(d)) => d,
        _ => panic!(),
    };
    let z = dec.to_f64().unwrap();
    assert_eq!(a, z);
}
```

It appears `BigDecimal` does not support this in general; the docs [say](https://docs.rs/bigdecimal/0.2.0/bigdecimal/) "It is not recommended to convert a floating point number to a decimal directly, as the floating point representation may be unexpected."

Since f32 and f64 are common data types in many systems, would it make sense to add explicit [`Primitive`](https://docs.rs/nu-protocol/0.29.0/nu_protocol/value/primitive/enum.Primitive.html) arms for them? I'd be able to work on a PR for this, if this sounds like a good direction.

An alternative would be to represent `f32` and `f64` values as `String`s. This works, but loses nu's nice property of having typed data. Converting invalid strings into `NaN`s as eg. Javascript does can lead to surprising results, as `NaN` can have multiple interpretations.

**Comment by jonathandturner** [comment]
@sunfishcode - sorry for the slow reply here. I'd definitely like to brainstorm this a bit. Like you point out, there are issues with converting f32/f64 directly and we may want to keep them in their native form at times.

I've also been playing with the idea of introducing an i64 type. Currently, I'm thinking that this i64 automatically promotes to big int if math every overflows, but would be good to chat about what impact that might have on wasm compat.

**Comment by sunfishcode** [comment]
I am still planning to work on this; I've been distracted by other projects lately, but I do hope to make time for this.

**Comment by jntrnr** [comment]
The upcoming engine (engine-q) currently supports f64 but not f32. Not sure if, from a scripting standpoint, it makes to have both or if f64 should be enough.

You can check it out here: https://github.com/nushell/engine-q

**Comment by jntrnr** [comment]
Cool - already now that the new engine is in nushell main, I'm going to close. This engine uses `f64` for its floating point operations.
