### ISSUE TITLE
Using the double-quotes in `alias` has strange behavior

### ISSUE THREAD

**Issue by Jason5Lee** [nushell/nushell#3250]
1. Executing `alias command = "ls -l"`
2. Executing `alias command ="ls -l"`

**Expected behavior**
For 1, it should either create an alias to `ls -l` or show the error of using double-quotes.
For 2, it should either create an alias to `ls -l` or show the error of not adding space after `=`.

**Screenshots**
For 1, the `alias` command executed without any error, but the alias is not created.
![image](https://user-images.githubusercontent.com/25118271/113421153-27e10780-93fd-11eb-9fb7-2ad0ee3710e3.png)
For 2, it prints a very confusing error message.
![image](https://user-images.githubusercontent.com/25118271/113421217-4c3ce400-93fd-11eb-85bc-d26a78836155.png)

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
───┬────────────────────┬─────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                 Column1                                 
───┼────────────────────┼─────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.29.0                                                                  
 1 │ build_os           │ macos-x86_64                                                            
 2 │ rust_version       │ rustc 1.51.0                                                            
 3 │ cargo_version      │ cargo 1.51.0                                                            
 4 │ pkg_version        │ 0.29.0                                                                  
 5 │ build_time         │ 2021-03-30 23:31:22                                                     
 6 │ build_rust_channel │ release                                                                 
 7 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, 
   │                    │ which, zip                                                              
───┴────────────────────┴─────────────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**

**Comment by alexherbo2** [comment]
The correct syntax is without quotes.

The error messages are not helpful though.

For 1. the alias is created but `ls -l` (as a single token) is not found.

For 2. the syntax is wrong.  It expects `=` but finds `="ls`.

**Comment by alexherbo2** [comment]
I wonder if the equal sign should not be removed from the language.
