### ISSUE TITLE
startup commands not getting picked up.

### ISSUE THREAD

**Issue by andrasio** [nushell/nushell#3259]
**Describe the bug**
commands in `startup` under nu configuration (`def`s, etc) aren't being picked up by Nu's scope.

Follow up from #3041 

**To Reproduce**
Here is a [failing test](https://github.com/nushell/nushell/blob/main/tests/shell/mod.rs#L14-L24) using a `startup.toml` configuration file with the following contents:

```
skip_welcome_message = true

startup = ["def hello-world [] { echo 'Nu World' }"]
```

**Expected behavior**
```
> hello-world
Nu World
```

/cpy @LhKipp

**Comment by stormasm** [comment]
The way I get def's to work is to source the file they are located in from startup, then everything is OK.

https://github.com/stormasm/nuconfig/blob/main/config.toml

See the above file and the other files located in the repo...

**Comment by jonathandturner** [comment]
I'm guessing this is fixed now, since a lot of folks use startup commands. Closing, but if you're still seeing it please reopen.
