### ISSUE TITLE
Add --regex Example

### ISSUE THREAD

**Issue by jeff-hykin** [nushell/nushell#3260]
**Is your feature request related to a problem? Please describe.**
Kinda, after looking at the [parse --regex PR](https://github.com/nushell/nushell/pull/1863/files ) and `help parse`, I can't figure out how to use the regex option.

**Describe the solution you'd like**
Add one or two examples to the help function
ex1:
```
echo "hello jeff" | parse --regex 'hello (.+)' | nth 1 | get Capture1
```
ex2
```
open nushell_git_log_oneline.txt
| parse --regex "(?P<Hash>\w+) (?P<Message>.+) \(#(?P<PR>\d+)\)"
| nth 1
| get PR
| echo $it
```

**Describe alternatives you've considered**
- Seaching [www.nushell.sh](www.nushell.sh)
- searching the discord
- searching the source code
- trying random stuff 
![Screen Shot 2021-04-03 at 8 52 46 PM](https://user-images.githubusercontent.com/17692058/113496501-e49b9d00-94bf-11eb-8a8c-2f34de55271f.png)

**Additional context**
Nu is awesome ⚡️, I just need to figure out how to do my existing workflows like pcregrep, sed, and awk 😅

**Comment by jeff-hykin** [comment]
Hey I finally got it working! 
```
open hello.txt | lines | parse --regex 'hello (?P<name>.+)'
```
Example should still probably be added, and probably should mention that named capture groups are required.

**Comment by fdncred** [comment]
I agree. A sample would be nice. We use the [regex crate](https://docs.rs/regex/1.4.5/regex/index.html) and I've never really liked it for regular expressions because it's kind of weird.

**Comment by jonathandturner** [comment]
Parse now has a regex example, which should help.

@jeff-hykin For the end of the original issue, where you do `echo $it`, can now do `echo $in` to get the contents of the pipeline.

I'm going ahead and closing, but if there's more work here, please reopen and we can update the issue for the remaining work.
