### ISSUE TITLE
surprising behavior of into-int 

### ISSUE THREAD

**Issue by efx** [nushell/nushell#3273]
**Describe the bug**
I expected `echo "123" | into-int` to produce an integer but no output appears.
`echo 123 | into-int` behaves similarly.

**To Reproduce**
1. `nu -c 'echo "123" | into-int'`

**Expected behavior**
I expect that pipeline to yield an integer I can use for variable assignment or further processing.

**Screenshots**
Here is some example output from the `into-int` commands I am trying.
<img width="374" alt="Screen Shot 2021-04-06 at 3 15 51 PM" src="https://user-images.githubusercontent.com/472721/113766048-00cf5200-96eb-11eb-88d4-bdb56a62e92b.png">

**Configuration (please complete the following information):**

```
> version | pivot
───┬────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                                 Column1                                                  
───┼────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.29.0                                                                                                   
 1 │ build_os           │ macos-x86_64                                                                                             
 2 │ rust_version       │ rustc 1.51.0 (2fd73fabe 2021-03-23)                                                                      
 3 │ rust_channel       │ stable-x86_64-apple-darwin (default)                                                                     
 4 │ cargo_version      │ cargo 1.51.0 (43b129a20 2021-03-16)                                                                      
 5 │ pkg_version        │ 0.29.0                                                                                                   
 6 │ build_time         │ 2021-04-06 09:50:31                                                                                      
 7 │ build_rust_channel │ release                                                                                                  
 8 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, trash, uuid, which, zip 
───┴────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**
I am probably doing something wrong :).
I am trying to parse directories that follow a SemVer naming structure. 
I was hoping to convert the `1.0.0` directory name to an integer so I can compare the version numerically.

**Comment by fdncred** [comment]
I think [this PR](https://github.com/nushell/nushell/pull/3119) would've fixed that problem but the author didn't want to change the name so it didn't get done. Feel free to take that code and try to PR that change.

**Comment by efx** [comment]
@fdncred thank you for the tip and history! 

I'll attempt to resurrect that PR this week with @andrasio's [requested changes](https://github.com/nushell/nushell/pull/3119#issuecomment-791841137).
