### ISSUE TITLE
Activating a Python virtual environment fails with error

### ISSUE THREAD

**Issue by liquidat** [nushell/nushell#3275]
**Describe the bug**
[Activating a Python virtual environment](https://docs.python.org/3/tutorial/venv.html#creating-virtual-environments) fails:

```
> source tutorial-env/bin/activate
error: if requires block to run if condition is true parameter
   ┌─ shell:50:1
   │
50 │ if [ -n "${PYTHONHOME:-}" ] ; then
   │ ^^ requires block to run if condition is true parameter

```

**To Reproduce**
1. create Python virtual environment: `python3 -m venv tutorial-env`
2. launch it: `source tutorial-env/bin/activate`

**Expected behavior**
The launch of the environment should not fail with an error.
Instead, I should be provided with a working Python environment.

**Screenshots**
N/A

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version|pivot
───┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                      Column1                                       
───┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.29.0                                                                             
 1 │ build_os           │ linux-x86_64                                                                       
 2 │ rust_version       │ rustc 1.50.0 (Fedora 1.50.0-1.fc33)                                                
 3 │ cargo_version      │ cargo 1.50.0                                                                       
 4 │ pkg_version        │ 0.29.0                                                                             
 5 │ build_time         │ 2021-03-30 21:40:58                                                                
 6 │ build_rust_channel │ release                                                                            
 7 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip 
───┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**

```
> python3 --version
Python 3.9.2
```

**Comment by fdncred** [comment]
The nushell `source` command is only for sourcing nushell scripts at this time. You can't use it the way you demonstrate to source bash/sh scripts.

**Comment by liquidat** [comment]
@fdncred Thanks for the quick reply. Is there a workaround for activating Python environments?

**Comment by fdncred** [comment]
Not that I know of because the environment variables in nushell are found in `$nu.env`. I mean, you could rewrite the activate script in nushell but that would probably be a pain. So, unfortunately, I'm not sure of an easy way forward right now.

**Comment by kubouch** [comment]
Yes, you would need to convince the Python tutorial authors to include a nushell version of the activate script (you can see they already have a version for csh and fish).

I'm not sure if there is anything nushell could do -- seems like it's up to the script authors to add the support for nu. Perhaps nushell could have a feature to export env variables from other shells? Not sure...

**Comment by liquidat** [comment]
Thanks, maybe I can come up with something on their side.

**Comment by azymohliad** [comment]
Came here looking if there are any built-in helpers for sourcing bash environment. For now I've been using this workaround: running bash, sourcing the environment, and then running nu again.

```
bash -c ". tutorial-env/bin/activate && nu" 
```

Which is a bit ugly (because my process tree looks like: bash -> nu -> bash -> nu after that), but works.
