### ISSUE TITLE
Cannot forward options with `...rest`

### ISSUE THREAD

**Issue by alexherbo2** [nushell/nushell#3276]
```
# synapse
# https://synapse-bt.org
alias s = sycli
alias S = synapse
alias sa = sycli add
alias si = sycli status
alias sl = sycli list
alias sp = sycli-fzf pause
alias sP = sycli-fzf resume
alias sw = sycli-fzf del --files
alias sW = pkill synapse

# fzf integration
# https://github.com/junegunn/fzf
def sycli-fzf [...rest] {
  sycli list --output json | jq --raw-output '.[].name' | fzf | lines | each {
    sycli $rest $it
  }
}
```

Running `sw` gives `sw: unexpected flag (try sycli-fzf -h)`.

**Comment by LhKipp** [comment]
I think `...rest` was never meant to forward flags. Maybe we should provide a variable to custom commands containing all flags?

**Comment by aitorpazos** [comment]
I would also like to be able to pass the flags to the custom command. I my case I was trying to leverage custom commands to get a better `kubectl` experience:
```
def k [...rest] { 
  kubectl --output json $rest | from json
}
```
But I am hitting this roadblock. So as long as those flags were ignored by custom commands and passed in the `...rest` (or other variable as @LhKipp was suggesting) that should be fine.

**Comment by bugabinga** [comment]
In my opinion there are further problems with how the `...rest` parameter is handled right now.
Consider the following script:

```nu
def A [ ...rest: any ] { echo (build-string "Method A. Rest description: " ($rest | describe) (char newline)); echo $rest; B $rest }
def B [ ...rest: any ] { echo (build-string "Method B. Rest description: " ($rest | describe) (char newline)); echo $rest; C $rest }
def C [ ...rest: any ] { echo (build-string "Method C. Rest description: " ($rest | describe) (char newline)); echo $rest}

A 1 2 3 4 5 6 7 8 9 0

# the following shows the behaviour I would have expected

def a [ $rest: table ] { echo (build-string "Method a. Rest description: " ($rest | describe) (char newline)); echo $rest; b $rest }
def b [ $rest: table ] { echo (build-string "Method b. Rest description: " ($rest | describe) (char newline)); echo $rest; c $rest }
def c [ $rest: table ] { echo (build-string "Method c. Rest description: " ($rest | describe) (char newline)); echo $rest}

a [1 2 3 4 5 6 7 8 9 0]
```
```sh
∽/nu_playground
  nu .\flat_rest.nu
Method A. Rest description: [table 10 rows]
  0   1
  1   2
  2   3
  3   4
  4   5
  5   6
  6   7
  7   8
  8   9
  9   0


Method B. Rest description: table of
integer
  0   [table 10 rows]


Method C. Rest description: table of
table of
integer
  0   [table 1 rows]


Method a. Rest description: [table 10 rows]
  0   1
  1   2
  2   3
  3   4
  4   5
  5   6
  6   7
  7   8
  8   9
  9   0


Method b. Rest description: [table 10 rows]
  0   1
  1   2
  2   3
  3   4
  4   5
  5   6
  6   7
  7   8
  8   9
  9   0


Method c. Rest description: [table 10 rows]
  0   1
  1   2
  2   3
  3   4
  4   5
  5   6
  6   7
  7   8
  8   9
  9   0
```

This makes it tricky to build up a library of custom commands that depend on each other.
I think either a way to manually explode table values that get passed into commands is needed, or maybe `...rest` arguments could get automatically flattened.

Consider, automatic reduction of tables to strings already occurs when passing table values (which `...rest` is) to external commands:
```nu
^echo ([hi there])
# this is as if it got automatically translated to
nu -c (build-string ^echo ' ' ([hi there] | str collect ' '))
```
So maybe happening something similar with nu commands is not too surprising.

**Comment by herlon214** [comment]
I'm trying to send the given flags to kubectl:
```
def k [...rest:string] {
	let result = (kubectl $rest | lines | detect columns)
	echo $result
}
```
Is there any way to collect all the args including the flags?

**Comment by Benjamin-L** [comment]
In general, it seems like there's a missing builtin (could be called `apply`) to run a command with arguments from a list.

Something like:
```
apply foo [ a b c ]
# equivalent to
foo a b c
```

**Comment by sparebytes** [comment]
**Quoted Flags**: Something else that could be a source of confusion is the difference between how **quoted** flag-looking arguments are passed to internal and external commands.

```nu
# play.nu
def main [...args] { echo $args }

main "-f" # Prints │ 0 │ -f │
main -f  # Unknown flag

# Nu or Bash interactive terminal
./play.nu "-f" # Unknown flag
./play.nu -f # Unknown flag
```

----
**Problems with a separate `...flags` argument**: @LhKipp, If we are forwarding the args and flags to an external command, how would Nu know which are booleans, arrays

```nu
def main [...args, ...flags] {
  external-command $args $flags
}

main "an-argument" --name "George" --quiet --watch "src" --watch "lib"

# undesired outcome
external-command "an-argument" "George" "src" "lib" --name --quiet --watch --watch
```

**Comment by LhKipp** [comment]
@sparebytes Thanks for your detailed comment. I am not contributing to nushell anymore and I haven't looked into the code since then or followed updates on the project.
Judging by your 2nd example, it is probably impossible to determine which arguments belong to flags and which don't. But that's just my 2 cents.

**Comment by olanod** [comment]
perhaps some special syntax to capture the raw arguments
```
def foo [..^raw-rest] { command $raw-rest }
```

**Comment by jntrnr** [comment]
@kubouch may be able to talk about flag forwarding here, as there's been some relatively recent work on it.

**Comment by jokeyrhyme** [comment]
Apologies if this should be asked elsewhere, but this seemed sort of related ... ?

I have a list of strings, and I'd like to pass them as arguments when calling another command e.g.

```
let args = ["one", "two", "three"]
^my-command ... what goes here ... ?
# should execute `my-command one two three`
```

I'm guessing `extern-wrapped` isn't appropriate here?

And my use case gets more complicated, in that I want to be able to do this within a custom function, e.g.

```
def process_arguments_then_pass_along [...args: string] {
    # note that this doesn't work, it's just an example of what I've tried
    another_command ...$ARGS
}
```

**Comment by kubouch** [comment]
You can use just `^my-command $args`

**Comment by weirdan** [comment]
I think it's already solved with `def --wrapped` (previously called `extern-wrapped`): https://www.nushell.sh/commands/docs/def.html#examples

**Comment by sholderbach** [comment]
I think with the external focus it is true, there may still be some issues we want to keep explicitly asking for better flag pass through for nested internal commands.
