### ISSUE TITLE
reduce --numbered bug

### ISSUE THREAD

**Issue by mvolkmann** [nushell/nushell#3298]
**Describe the bug**
There is an issue with the `--numbered` (`-n`) flag on the `reduce` command. See below.

**To Reproduce**

```bash
let scores = [3 8 4]
echo $scores | reduce { = $acc + $it } # 15 - correct
echo $scores | reduce -n { = $acc.item + $it.item } # Type Error: Expected row or table, found integer
```

**Expected behavior**

The second use of `reduce` above should produce the same result, 15.

***Configuration (please complete the following information):**

│ 0 │ version            │ 0.29.0                                                                             │
│ 1 │ build_os           │ macos-x86_64                                                                       │
│ 2 │ rust_version       │ rustc 1.50.0 (cb75ad5db 2021-02-10)                                                │
│ 3 │ rust_channel       │ stable-x86_64-apple-darwin (default)                                               │
│ 4 │ cargo_version      │ cargo 1.50.0 (f04e7fab7 2021-02-04)                                                │
│ 5 │ pkg_version        │ 0.29.0                                                                             │
│ 6 │ build_time         │ 2021-03-30 20:30:47                                                                │
│ 7 │ build_rust_channel │ release                                                                            │
│ 8 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip │

**Comment by jonathandturner** [comment]
This seems to work on recent Nu versions:

```
> [1 2 3] | reduce -n { $acc.item + $it.item }
───┬───────┬──────
 # │ index │ item 
───┼───────┼──────
 0 │     0 │    6 
───┴───────┴──────
```

**Comment by ShakenCodes** [comment]
https://www.nushell.sh/book/working_with_lists.html still references this bug.
