### ISSUE TITLE
Running `echo ..` starts printing integers forever

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#3313]
**Describe the bug**
Running `echo ..` starts printing a never ending stream of incrementing integers

**To Reproduce**
1. `echo ..`

**Expected behavior**
Print `..`

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot

  #         Column0                                        Column1
───────────────────────────────────────────────────────────────────────────────────────────────────
   0   version              0.29.2
   1   branch               path-parse
   2   short_commit         d1ccef41
   3   commit_hash          d1ccef410b78205da2dfbaddf0c4e6b2b4768327
   4   commit_date          2021-04-13 23:13:34
   5   build_os             linux-x86_64
   6   rust_version         rustc 1.51.0 (2fd73fabe 2021-03-23)
   7   rust_channel         stable-x86_64-unknown-linux-gnu (default)
   8   cargo_version        cargo 1.51.0 (43b129a20 2021-03-16)
   9   pkg_version          0.29.2
  10   build_time           2021-04-14 00:22:58
  11   build_rust_channel   debug
  12   features             ctrlc, default, directories, dirs, ichwh, rustyline, term, which, zip
```

**Comment by jonathandturner** [comment]
this is correct behaviour. it's assumed that if you do an infinite stream, eg `echo 1..` also does this, that you'll limit the stream using something like `first` as part of the pipeline.

That said, if you're not able to Ctrl-C out of this, that's a bug.

**Comment by kubouch** [comment]
Ah, ok. It's quite confusing because `..` can also be a path.

**Comment by jonathandturner** [comment]
Oooh, good point. hmmmm.

I wonder if we should change the range syntax to being something like `(a..b)` instead of just `a..b`

**Comment by kubouch** [comment]
I think it would be enough if `..` required at least one number on either side: `1..` or `..1`. Then you're unlikely to use it as a path. `..` by itself doesn't seem very useful, to me.

**Comment by jonathandturner** [comment]
@kubouch sounds good

**Comment by luccasmmg** [comment]
Could i be assigned to this? If im correct all the work would be done in the parse_range function inside the parser, right? just making sure that there is at least one number on either side.
