### ISSUE TITLE
nu-command building hang

### ISSUE THREAD

**Issue by DonJTru** [nushell/nushell#3321]
**Describe the bug**
nu-command hangs when building nu from crates.io

**To Reproduce**
1. log into server via ssh.
2. install required dependencies.
3. run `cargo install nu`

**Expected behavior**
nu to compile

**Extra**
This is running on a $5/Month digital ocean Ubuntu 20 VPS

**Comment by jonathandturner** [comment]
Can you say a bit more about the size of machine you're coming by on? How much memory does it have? What version of Rust is it using? How much drive side does it have?
