### ISSUE TITLE
Move off of `ichwh`

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#3328]
**Is your feature request related to a problem? Please describe.**
We're currently using both `which` and `ichwh`. The `ichwh` crate is meant for use in async/await use cases, though because we have rewritten to use sync iterators, we no longer need this functionality.

**Describe the solution you'd like**
Let's rewrite the `ichwh` usage to use a simpler, sync approach. This would let us remove one of the last async parts in the engine.

**Describe alternatives you've considered**
We can keep it as is, but I don't see any advantage to being async in this case.

**Comment by swsiadak** [comment]
looks like this can be closed?

**Comment by jonathandturner** [comment]
@swsiadak yup, good catch
