### ISSUE TITLE
Script arguments

### ISSUE THREAD

**Issue by janosimas** [nushell/nushell#3334]
**Is your feature request related to a problem? Please describe.**
I may have missed something but I didn't fin a way to read arguments in a script.

**Describe the solution you'd like**
The scripts could have a implicit `input` table that we could index on it `input | get 1`
Another suggestion is to use `each { $it }` to iterate on the input.

**Describe alternatives you've considered**
I tried the bash format `$1` and the iterator format `each { ... $it }`

**Comment by fdncred** [comment]
There are examples here of scripts that take arguments on the command line and scripts that take input from a pipeline https://github.com/nushell/nu_scripts

**Comment by janosimas** [comment]
@fdncred Thanks for the link,
I may be missing it but I couldn't find a sample of a script that takes an argument.

I found scripts that define function that takes arguments but that's not my use case.

I want to do something like:
```sh
$ nu foo.nu arg1 arg2
```

**Comment by jonathandturner** [comment]
@janosimas - this isn't yet supported, but it's something we'd like to add.

**Comment by jjorissen52** [comment]
Very much looking forward to this, thank you for the great work so far!

**Comment by hustcer** [comment]
Waiting for this feature to be supported !  Thanks for the great work.

**Comment by hustcer** [comment]
@jntrnr Any plan for this? Thx

**Comment by jntrnr** [comment]
@hustcer - I've got some ideas for engine-q (the upcoming engine for Nushell) that should support this. We're getting closer but it's not yet implemented.

Basically, you'll be able to define a `main` definition and make it available as the entry point for the script. The parameter definitions of this `main` will then be the flags/positional args that the script will have.

**Comment by obust** [comment]
It is great to provide an easy way to bootstrap a CLI app using the `main` with flags/positional args !

Coming from python, this makes me think of the very versatile `fire` [CLI library](https://github.com/google/python-fire).
In particular I would highlight the mechanics of [functions returning functions](https://github.com/google/python-fire/blob/master/docs/guide.md#chaining-function-calls) which allow for subcommand and/or chaining of function calls. Note that classes are not required to allow this. It can also work by matching on input strings and returning appropriate functions.

However it would be great to be able to also support arbitrary input syntax and **not** only the common dash based flag (`-f`) and option `--fruit banana`.
For example, [hydra](https://hydra.cc/docs/tutorials/basic/your_first_app/simple_cli/) is a CLI library that created its own versatile input syntax that works in pair with a yaml config file. This gives a totally different interface to scripts with different benefits. In particular, Hydra is used mostly in scientific computing where experiment parametrization is usually cumbersome.

**Comment by hustcer** [comment]
This feature is supported on the latest main, check this: https://github.com/nushell/nushell/issues/3762#issuecomment-1000672775, And here is a example: https://github.com/nushell/nushell.github.io/blob/main/i18n.nu
So I will close it, please reopen if you still have issues.

**Comment by tmccombs** [comment]
I love this solution! Nice work!
