### ISSUE TITLE
radix_trie crash on 0.29 and above.

### ISSUE THREAD

**Issue by Stromberg90** [nushell/nushell#3341]
**Describe the bug**
This happens with both 0.29 and 0.30.
**0.27 and 0.28 works**.
When I try to run nu, it crashes with:
thread 'main' panicked at 'multiple-keys with the same bit representation.', C:\\Users\\Stromberg\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\radix_trie-0.2.1\\src\\keys.rs:76:9 

**To Reproduce**
1. Open shell of choice
2. > cargo install --version ^0.30 nu
3. > nu
4. Crash

**Expected behavior**
Don't panic

**Configuration (please complete the following information):**
This is from the most recent version that works, on the ones that crash I'm not able to run this command.
```
> version | pivot
╭───┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────╮
│ # │ Column0            │ Column1                                                                            │
├───┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────┤
│ 0 │ version            │ 0.28.0                                                                             │
│ 1 │ build_os           │ windows-x86_64                                                                     │
│ 2 │ rust_version       │ rustc 1.51.0 (2fd73fabe 2021-03-23)                                                │
│ 3 │ cargo_version      │ cargo 1.51.0 (43b129a20 2021-03-16)                                                │
│ 4 │ pkg_version        │ 0.28.0                                                                             │
│ 5 │ build_time         │ 2021-04-21 10:27:28                                                                │
│ 6 │ build_rust_channel │ release                                                                            │
│ 7 │ features           │ ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, uuid, which, zip │
╰───┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────╯
```

**Add any other context about the problem here.**
stack backtrace:                                                                                                                                                                                      
> 0:     0x7ff63d0d76a8 - std::backtrace_rs::backtrace::dbghelp::trace                                                                                                                                                           at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98                                                   
1:     0x7ff63d0d76a8 - std::backtrace_rs::backtrace::trace_unsynchronized                                                                                                                                                     at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66                                                             
2:     0x7ff63d0d76a8 - std::sys_common::backtrace::_print_fmt                                                                                                                                                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:67                                                                         
3:     0x7ff63d0d76a8 - std::sys_common::backtrace::_print::{{impl}}::fmt                                                                                                                                                      at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:46                                                                         
4:     0x7ff63c5d069b - core::fmt::write                                                                                                                                                                                       at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\fmt\mod.rs:1096                                                                                   
5:     0x7ff63d0d65d8 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>                                                                                                                                            at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\io\mod.rs:1568                                                                                     
6:     0x7ff63d0d5c2c - std::sys_common::backtrace::_print                                                                                                                                                                     at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:49                                                                         
7:     0x7ff63d0d5c2c - std::sys_common::backtrace::print                                                                                                                                                                      at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\sys_common\backtrace.rs:36                                                                         
8:     0x7ff63d0d5c2c - std::panicking::default_hook::{{closure}}                                                                                                                                                              at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:208                                                                                   
9:     0x7ff63d0d4f2f - std::panicking::default_hook                                                                                                                                                                           at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:225                                                                                  
10:     0x7ff63d0d4f2f - std::panicking::rust_panic_with_hook                                                                                                                                                                   at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:591                                                                                  
11:     0x7ff63c6a0744 - hashbrown::raw::Fallibility::alloc_err                                                                                                                                    
12:     0x7ff63c6a070f - hashbrown::raw::Fallibility::alloc_err                                                                                                                                    
13:     0x7ff63c68f74d - hashbrown::raw::Fallibility::alloc_err                                                                                                                                    
14:     0x7ff63c6a33c0 - hashbrown::raw::Fallibility::alloc_err                                                                                                                                    
15:     0x7ff63c65f58f - hashbrown::raw::Fallibility::alloc_err                                                                                                                                    
16:     0x7ff63c65579c - hashbrown::raw::Fallibility::alloc_err                                                                                                                                    
17:     0x7ff63c50e4fd - __ImageBase                                                                                                                                                               
18:     0x7ff63c501006 - __ImageBase                                                                                                                                                               
19:     0x7ff63c50102b - __ImageBase                                                                                                                                                               
20:     0x7ff63c512ca4 - main                                                                                                                                                                      
21:     0x7ff63d20b790 - invoke_main                                                                                                                                                                                            at d:\A01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78                                                                                          
22:     0x7ff63d20b790 - __scrt_common_main_seh                                                                                                                                                                                 at d:\A01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288                                                                                         
23:     0x7ff8a1c57034 - BaseThreadInitThunk                                                                                                                                                       
24:     0x7ff8a2c02651 - RtlUserThreadStart

**Comment by Stromberg90** [comment]
Still happens for me on 0.31
```
thread 'main' panicked at 'multiple-keys with the same bit representation.', C:\Users\Stromberg\.cargo\registry\src\github.com-
1ecc6299db9ec823\radix_trie-0.2.1\src\keys.rs:76:9                                                         stack backtrace:                                                                                                                                                                                                                             
0:     0x7ff784fcf1e8 - std::backtrace_rs::backtrace::dbghelp::trace                                                                                                                                                                                                  
at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98                                                                                               
1:     0x7ff784fcf1e8 - std::backtrace_rs::backtrace::trace_unsynchronized                                                                                                                                                                                            
at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66                                                                                                   
2:     0x7ff784fcf1e8 - std::sys_common::backtrace::_print_fmt                                                                                                                                                                                                        
at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\sys_common\backtrace.rs:67                                                                                                                
3:     0x7ff784fcf1e8 - std::sys_common::backtrace::_print::{{impl}}::fmt                                                                                                                                                                                             
at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\sys_common\backtrace.rs:46                                                                                                                
4:     0x7ff7845cd5dc - core::fmt::write                                                                                                                                                                                                                              
at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\core\src\fmt\mod.rs:1092                                                                                                                          
5:     0x7ff784fce188 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>                                                                                                                                                                                   
at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\io\mod.rs:1572                                                                                                                            
6:     0x7ff784fcd80c - std::sys_common::backtrace::_print                                                                                                                                                                                                            
at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\sys_common\backtrace.rs:49                                                                                                                
7:     0x7ff784fcd80c - std::sys_common::backtrace::print                                                                                                                                                                                                             
at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\sys_common\backtrace.rs:36                                                                                                                
8:     0x7ff784fcd80c - std::panicking::default_hook::{{closure}}                                                                                                                                                                                                     
at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:208                                                                                                                          
9:     0x7ff784fccaca - std::panicking::default_hook                                                                                                                                                                                                                  
at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:225                                                                                                                         
10:     0x7ff784fccaca - std::panicking::rust_panic_with_hook                                                                                                                                                                                                          
at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53\/library\std\src\panicking.rs:591                                                                                                                         
11:     0x7ff78468fbf4 - hashbrown::raw::Fallibility::alloc_err                                                                                                                                                                           
12:     0x7ff78468fbbf - hashbrown::raw::Fallibility::alloc_err                                                                                                                                                                           
13:     0x7ff7850f855d - core::str::traits::str_index_overflow_fail                                                                                                                                                                       
14:     0x7ff784692740 - hashbrown::raw::Fallibility::alloc_err                                                                                                                                                                           
15:     0x7ff784651e6e - hashbrown::raw::Fallibility::alloc_err                                                                                                                                                                           
16:     0x7ff7846484e6 - hashbrown::raw::Fallibility::alloc_err                                                                                                                                                                           
17:     0x7ff78453d67a - __ImageBase                                                                                                                                                                                                      
18:     0x7ff784531006 - __ImageBase                                                                                                                                                                                                      
19:     0x7ff78453102b - __ImageBase                                                                                                                                                                                                      
20:     0x7ff784541b84 - main                                                                                                                                                                                                             
21:     0x7ff7850f2c80 - invoke_main                                                                                                                                                                                                                                   
at d:\A01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78                                                                                                                                 
22:     0x7ff7850f2c80 - __scrt_common_main_seh                                                                                                                                                                                                                        
at d:\A01\_work\12\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288                                                                                                                                
23:     0x7ffe03b654e0 - BaseThreadInitThunk                                                                                                                                                                                      
24:     0x7ffe04a2485b - RtlUserThreadStart 
```

**Comment by Stromberg90** [comment]
Think I found it, while troubleshooting on my config file I found my keybindings.yml 
```
# Finish the line entry
- key:
    Ctrl: J
  binding:
    AcceptLine:
- key:
    Ctrl: M
  binding:
    AcceptLine:
- key:
    Enter:
  binding:
    AcceptLine:
```
if I comment out this then it works, if I keep this binding in crashes either on startup or when calling exit.
```
- key:
    Ctrl: M
  binding:
    AcceptLine:
```

even after commenting out this binding, if I press ctrl-m in nushell it crashes in the same way.
so then there is still a issue with crashing for me, although now I can use it since I rarely/ever type ctrl-m.

here is my config just in case.
```
skip_welcome_message = true
table_mode = "reinforced"
startup = [
    "alias cd_temp = cd C:\\Users\\Stromberg\\Desktop\\temp",
]
```

**Comment by jonathandturner** [comment]
My guess is that rustyline (the line editor we use) is doing some normalizing of the keys. Ctrl-M might be getting treated as a carriage return and overlapping with the other keys you've bound to new line.

I think all we do is pass along the key configuration to rustyline, so it is possible this is an issue with [rustyline](https://github.com/kkawakam/rustyline) itself.

**Comment by Stromberg90** [comment]
That seems to be the case, I found a previous issue that matches, I'll see if I can reproduce this using only rustyline. 
https://github.com/kkawakam/rustyline/issues/509

**Comment by Stromberg90** [comment]
There is a comment saying "Version 8.1.0 released" in the issue I linked, and since then there has been another version released.
So I will test this again when there is a new nushell release that has updated to rustyline 8.1.0 or above.
