### ISSUE TITLE
`get` Errors on Valid Cell Paths

### ISSUE THREAD

**Issue by jjorissen52** [nushell/nushell#3352]
**Describe the bug**
`get` sometimes errors on valid celll paths.

**To Reproduce**
1. save the contents of [this gist](https://gist.github.com/jjorissen52/85578af10d32a352f0b313e3184aed0d#file-epic-dump-json) as `dump.json` in a shell
2. `cat dump.json | from json -o` to see table structure
3. `cat dump.json | from json -o | get embeds` works, shows a column named fields
4. `cat dump.json | from json -o | get embeds.0` successfully displays indexed row but raises error anyway
5. `cat dump.json | from json -o | get embeds.fields` successfully accesses column fields but displays an error anyway
6. `cat dump.json | from json -o | select embeds | get embeds.fields` successfully shows fields
7. `cat dump.json | from json -o | select embeds | get embeds.fields | select value | get value` successfully shows table of values
8. `cat dump.json | from json -o | select embeds | get embeds.fields | select value | get value.1` fails to access cell

**Expected behavior**
I expect each of the above to succeed without error, and to be able to access columns without first performing a `select`.

**Screenshots**
## 4 
<img width="769" alt="image" src="https://user-images.githubusercontent.com/12461302/115942481-1fb24000-a470-11eb-88d5-5dfc3b4d5c89.png">

## 5
<img width="616" alt="image" src="https://user-images.githubusercontent.com/12461302/115942504-3b1d4b00-a470-11eb-8a88-6090aac0521f.png">

## 6
<img width="641" alt="image" src="https://user-images.githubusercontent.com/12461302/115942545-61db8180-a470-11eb-84e2-cd07a3db6732.png">

## 7 & 8
<img width="952" alt="image" src="https://user-images.githubusercontent.com/12461302/115942726-41f88d80-a471-11eb-8019-3bfad71ea83e.png">

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
───┬────────────────────┬───────────────────────────────────────────────────────────────────────
 # │      Column0       │                                Column1
───┼────────────────────┼───────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.30.0
 1 │ build_os           │ linux-x86_64
 2 │ rust_version       │ rustc 1.51.0 (2fd73fabe 2021-03-23)
 3 │ rust_channel       │ stable-x86_64-unknown-linux-gnu (default)
 4 │ cargo_version      │ cargo 1.51.0 (43b129a20 2021-03-16)
 5 │ pkg_version        │ 0.30.0
 6 │ build_time         │ 2021-04-24 00:20:19
 7 │ build_rust_channel │ release
 8 │ features           │ ctrlc, default, directories, dirs, ichwh, rustyline, term, which, zip
───┴────────────────────┴───────────────────────────────────────────────────────────────────────
```

**Comment by fdncred** [comment]
can you share the dump.json file?

**Comment by jjorissen52** [comment]
Yes, it's in the gist from step 1.

**Comment by fdncred** [comment]
I can't do anything with this json. It looks invalid to me. This is what I get.

```
cat dump.json | from json -o
error: Could not parse as JSON ("EOF while parsing an object" at line 1 column 1)
   ┌─ shell:59:17
   │
59 │ cat dump.json | from json -o
   │ ---             ^^^^^^^^^ input cannot be parsed as JSON
   │ │
   │ value originates from here
```

**Comment by fdncred** [comment]
I was able to reproduce your issues with this file though.
[dump2.json.txt](https://github.com/nushell/nushell/files/6372906/dump2.json.txt)

**Comment by jjorissen52** [comment]
@fdncred it was supposed to be more of a "json per line" or ndjson file. Sorry about that, glad you figured it out.
