### ISSUE TITLE
In vscode terminal, some content print twice

### ISSUE THREAD

**Issue by Halkcyon** [nushell/nushell#3356]
**Describe the bug**
I've noticed this most commonly with the "Command not found" errors, but sometimes it triggers by just running commands as well.  I'm unable to replicate it in all places that I've found it.

I'm running vscode through the "Remote - WSL" extension.

**To Reproduce**
1. Trigger "Command not found" by entering a non-existent command.

**Expected behavior**
Errors / stdout are printed once.

**Screenshots**
![image](https://user-images.githubusercontent.com/25436433/116008352-1a750280-a5e2-11eb-8b55-4e74039171d7.png)

![image](https://user-images.githubusercontent.com/25436433/116008370-2bbe0f00-a5e2-11eb-9652-b95a1cc8d646.png)

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
───┬────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                                 Column1                                                  
───┼────────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.30.0                                                                                                   
 1 │ build_os           │ linux-x86_64                                                                                             
 2 │ rust_version       │ rustc 1.51.0 (2fd73fabe 2021-03-23)                                                                      
 3 │ rust_channel       │ nightly-x86_64-unknown-linux-gnu (default)                                                               
 4 │ cargo_version      │ cargo 1.51.0 (43b129a20 2021-03-16)                                                                      
 5 │ pkg_version        │ 0.30.0                                                                                                   
 6 │ build_time         │ 2021-04-25 14:02:54                                                                                      
 7 │ build_rust_channel │ release                                                                                                  
 8 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, trash, uuid, which, zip 
───┴────────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by Halkcyon** [comment]
Changing my default prompt seems to have resolved the problem.  I haven't run into the issue again this afternoon after configuring my prompt to `starship`.  Previously I had no configuration set.

**Comment by jonathandturner** [comment]
I'm not able to repro in recent Nushell versions. Closing, but please reopen if you're still seeing the issue.
