### ISSUE TITLE
Brew install with all features?

### ISSUE THREAD

**Issue by jakevossen5** [nushell/nushell#3362]
**Is your feature request related to a problem? Please describe.**
I want to be able to use nushell with specified features (specifically, trash_support) and I also want to use homebrew

**Describe the solution you'd like**
I would like to see that the default brew package contain all features. I don't think too many people are worried about binary size, and it is a bit cumbersome to compile from source to get these features.

**Describe alternatives you've considered**

- Provide a separate homebrew package (`nushell-full`?)
- Have an option in the existing formula (`brew install nushell --full`?)

**Comment by jonathandturner** [comment]
The homebrew port is maintained by volunteers working on homebrew rather than here. You may want to try filing an issue on the homebrew repo and see if you can connect with the maintainer there.

**Comment by jakevossen5** [comment]
Thanks! Just curious - what would your preferred situation be?

**Comment by jonathandturner** [comment]
I generally would prefer distros to distribute with 'extra' if at all possible. This is going to be the best experience for users generally.

**Comment by jakevossen5** [comment]
Homebrew has been updated, thank you!
