### ISSUE TITLE
Store metadata for history: timestamp, runtime, directory, exit status, session id (like zsh-histdb)

### ISSUE THREAD

**Issue by phiresky** [nushell/nushell#3364]
**Is your feature request related to a problem? Please describe.**
I'm a zsh user with [histdb](https://github.com/larkery/zsh-histdb) and [histdb-fzf](https://github.com/m42e/zsh-histdb-fzf). This means my command history is stored in a SQLite database, with the following metadata that's very useful:

* hostname and directory the command was run in. this is the most useful, I have Ctrl+R bound by default to list the history only of that directory (and subdirectories).
* runtime. how long the command took to run
* exit status. useful to tell if the command did what it should after the fact
* session id. allows filtering the history to a specific shell session (e.g. only current session, or session of a specific command found in the history).

It also allows syncing the database between different computers, though that's kinda buggy in histdb.

**Describe the solution you'd like**

One of the following:

* Make the history actions hookable - basically like in zsh where you have hooks that run before and after a command, plus the customizability of Ctrl+R
    histdb does this with just two hooks:

         add-zsh-hook zshaddhistory _histdb_addhistory
         add-zsh-hook precmd _histdb_update_outcome
 
* Integrate this functionality into the main nushell. I have no idea how the nushell internals work, and I'm not sure if 

**Describe alternatives you've considered**
The current history is very limited. There's some suggestions to add timestamps like https://github.com/nushell/nushell/issues/2735, but for me the directory is as important as the timestamp.

If there's any way to hook into the history in current nushell, I'd love to know.

All the above metadata could be stored in a flat file format as now, but IMO it's worth it to move to a real database (I'd suggest SQLite for easy concurrent use from multiple shells). 

**Additional context**
Just look at this screenshot: 
![image](https://user-images.githubusercontent.com/2303841/116416699-d597d880-a83a-11eb-8b6d-e782df3fcf68.png)
Isn't that awesome?
I love the idea of nushell, but I don't want to give up my awesome zsh history :) I'd probably be willing to implement this myself, if you all are open to the idea and can tell me where to integrate it.

**Comment by phiresky** [comment]
This is still an issue in my opinion

**Comment by fdncred** [comment]
we're planning on doing this in reedline/nushell eventually.

**Comment by hustcer** [comment]
@fdncred Can we close this issue?

**Comment by fdncred** [comment]
Yup. Thanks all.
