### ISSUE TITLE
Alias with a dollar expression panics when typed / run

### ISSUE THREAD

**Issue by Sciencentistguy** [nushell/nushell#3369]
**Describe the bug**
When an alias exists with a dollar expression (such as `alias e = nvim $(fzf)`), and the alias is typed into the shell, the shell panics.

**To Reproduce**
1. Define an alias such as `alias e = nvim $(fzf)`
2. Type `e`
3. Panic: 
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 2', crates/nu-engine/src/shell/painter.rs:49:13
```

**Expected behavior**
Not a panic

**Configuration:**

```
────┬────────────────────┬──────────────────────────────────────────────────────────────────────────────────
 #  │      Column0       │                                     Column1
────┼────────────────────┼──────────────────────────────────────────────────────────────────────────────────
  0 │ version            │ 0.30.1
  1 │ branch             │ main
  2 │ short_commit       │ 36cc5eb9
  3 │ commit_hash        │ 36cc5eb9333d3560bae1719d5671fce73259bf38
  4 │ commit_date        │ 2021-04-27 20:30:32
  5 │ build_os           │ linux-x86_64
  6 │ rust_version       │ rustc 1.51.0 (2fd73fabe 2021-03-23)
  7 │ rust_channel       │ stable-x86_64-unknown-linux-gnu (default)
  8 │ cargo_version      │ cargo 1.51.0 (43b129a20 2021-03-16)
  9 │ pkg_version        │ 0.30.1
 10 │ build_time         │ 2021-04-27 20:54:33
 11 │ build_rust_channel │ release
 12 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, ptree, rustyline, term, trash,
    │                    │ uuid, which, zip
────┴────────────────────┴──────────────────────────────────────────────────────────────────────────────────

```
and 
```
────┬────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────
 #  │      Column0       │                                              Column1
────┼────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────
  0 │ version            │ 0.30.1
  1 │ branch             │ main
  2 │ short_commit       │ 37925620
  3 │ commit_hash        │ 37925620462f5b5efd13d173f6a288a7de4c04bf
  4 │ commit_date        │ 2021-04-29 13:10:10
  5 │ build_os           │ linux-x86_64
  6 │ rust_version       │ rustc 1.51.0 (2fd73fabe 2021-03-23)
  7 │ rust_channel       │ stable-x86_64-unknown-linux-gnu (default)
  8 │ cargo_version      │ cargo 1.51.0 (43b129a20 2021-03-16)
  9 │ pkg_version        │ 0.30.1
 10 │ build_time         │ 2021-04-30 16:19:40
 11 │ build_rust_channel │ debug
 12 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, ptree, rustyline, term, trash, uuid, which, zip
────┴────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────
```

This issue is caused by the parser creating `Span`s that reference the alias expansion (so for example the sub-expression `fzf` is at indexes `(2,5)` of the expression `$(fzf)`.

When the contents of the dollar expression are tokenized, the span_offet is set to 2 (to ignore the `$(`). This then creates a baseline token (`Spanned<String>`) with span `(2,5)` (which works and identifies the `fzf` out of `$(fzf)`).

This span is then eventually returned to `paint_string`, where it is then passed to `shapes()`. This then defines `FlatShape`s that contains `Span`s with the value `(2,5)`, but are attached to the expanded alias (`e`) which has `len=1`. This then panics in `Painter::paint()`, where an unconditional `IndexMut` is used to set the styles.

This crash can be patched with a single line of code change:
In `crates/nu-engine/src/shell/painter.rs`: on line 50:
replace `self.styles[pos] = styled_span.item;`
with `self.styles.get_mut(pos).map(|x| *x = styled_span.item);`

I'd be happy to create a PR to apply this patch if this is desired.

However this is probably a bug in the parser, and should probably be fixed there.

**Comment by ahkrr** [comment]
The problem with the alias expansion that leads to the incorrect spans is already being discussed in the PR #3196

**Comment by jonathandturner** [comment]
This seems to work for me in recent Nushell versions. Closing, but if you still see the issue please reopen.
