### ISSUE TITLE
nu_plugin_from_sqlite.exe and nu_plugin_to_sqlite.exe identified as Trojan.Gen.MBT by Symantec Endpoint Protection

### ISSUE THREAD

**Issue by KristoferHansson** [nushell/nushell#3383]
**Is your feature request related to a problem? Please describe.**
Symantec Endpoint Protection identifies nu_plugin_from_sqlite.exe and nu_plugin_to_sqlite.exe as Trojan.Gen.MBT

Started happening yesterday, after having used nushell for about a month without problem, was probably due to an updated classification in symantec.
![image](https://user-images.githubusercontent.com/56853/116972267-11a7bf00-acbb-11eb-82fc-0cc0b0ec045a.png)

**Describe the solution you'd like**
Investigate why this happens, possibly file a request to symantec to put those on their allowlist

**Describe alternatives you've considered**
N/A

**Additional context**
Windows 10 20H2
Symantec Endpoint Security V14 (14.3.MP1) build 1148 (14.3.1148.0100)

**Comment by efx** [comment]
A wholly subjective other data point: 

I am running macOS and have another antivirus installed called "Trend Micro Security Agent".
<img width="406" alt="Screen Shot 2021-05-07 at 11 45 19 AM" src="https://user-images.githubusercontent.com/472721/117475129-b29bb180-af29-11eb-8fd3-ec1c493d8102.png">
I manually scanned my local version of `nu_plugin_extra_from_sqlite` and it was not flagged as problematic.

My comment does mean anything besides another antivirus does not consider this file a virus.

**Comment by staabm** [comment]
I can reproduce the same problem when opening the demo in firefox on windows. the GDATA antvir is reporting a Trojan

![grafik](https://user-images.githubusercontent.com/120441/136164322-78d4c71c-8199-4f84-9f55-7a7dc620c609.png)
