### ISSUE TITLE
Failed to spawn process error when using oh-my-posh prompt in non-filesystem shells

### ISSUE THREAD

**Issue by cdhunt** [nushell/nushell#3384]
**Describe the bug**

oh-my-posh doesn't work when cd-ing into a structured file on Windows. It appears to attempt to open the path as it were a file and fail, but I'm not sure if this is the cause of the process failure or just another related issue.

```
> config get prompt
echo $(oh-my-posh -pwd `{{$(pwd)}}`
```

Related issue in oh-my-posh: https://github.com/JanDeDobbeleer/oh-my-posh/issues/698

**To Reproduce**
1. Have a moderately complex structure file Nu understands
2. enter shell `enter $(config path)` ([Nu docs](https://www.nushell.sh/book/shells_in_shells.html#going-beyond-directories))
3. cd into the file `cd color_config`

**Expected behavior**
oh-my-posh not to crash. Ideally, it should understand the path format to render in the path section.

**Screenshots**
Here's one that fails.
![image](https://user-images.githubusercontent.com/114173/117002627-cb9a2d80-acb1-11eb-92f7-5d2fcc3f9e99.png)

And he's a normal run.
![image](https://user-images.githubusercontent.com/114173/117002881-216ed580-acb2-11eb-9371-be09b9a16c30.png)

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
>   #    Column0              Column1
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   0   version              0.30.0
   1   short_commit         02d57299
   2   commit_hash          02d5729941c9e5ad013889e1b9c452cc40a8e4df
   3   commit_date          2021-04-21 02:31:54
   4   build_os             windows-x86_64
   5   rust_version         rustc 1.51.0 (2fd73fabe 2021-03-23)
   6   rust_channel         stable-x86_64-pc-windows-msvc (default)
   7   cargo_version        cargo 1.51.0 (43b129a20 2021-03-16)
   8   pkg_version          0.30.0
   9   build_time           2021-04-21 05:40:50
  10   build_rust_channel   release
  11   features             clipboard-cli, ctrlc, default, directories, dirs, ichwh, ptree, rustyline, term, trash, uuid, which, zip
```

**Comment by JanDeDobbeleer** [comment]
I did some tests and can confirm nu fails at running the executable when you cd into a file's table:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/2492783/117046428-f9628f00-ad10-11eb-95c5-8630743f7ccb.png">

**Comment by JanDeDobbeleer** [comment]
There's a difference between stale and not being picked up...

**Comment by jonathandturner** [comment]
@JanDeDobbeleer - agreed. There have been a lot of fixes to various parts of how externals are run, so it's worth the check to ensure that it's still an issue with the most recent versions.

If it is, yes, let's definitely keep this open.

**Comment by JanDeDobbeleer** [comment]
I'll check on latest

**Comment by JanDeDobbeleer** [comment]
@jonathandturner still the same:

<img width="529" alt="image" src="https://user-images.githubusercontent.com/2492783/123522182-1043b300-d6bc-11eb-8b38-337469aaa88e.png">
