### ISSUE TITLE
make `uniq` more useful-ish

### ISSUE THREAD

**Issue by RustemB** [nushell/nushell#3385]
GNU's uniq programm has several useful flags like `-u/--unique` or `-d/--repeated` which is not included in nu's uniq  command

```nu
> echo [1 2 2 3 3] | uniq -d
───┬───
 0 │ 2
 1 │ 3
───┴───

> echo [1 2 3 3 4 4] | uniq -u
───┬───
 0 │ 1
 1 │ 2
───┴───
```

**Comment by jonathandturner** [comment]
With recent versions, `uniq` now supports the `-d` flag. We don't seem to support `-u`, yet.

**Comment by mcbattirola** [comment]
I've submitted a PR to support the `-u` flag


it's my first contribution, please let me know if I can change something to make it better,
thanks!
