### ISSUE TITLE
gitpod setup fails 

### ISSUE THREAD

**Issue by floh96** [nushell/nushell#3386]
The gitpod setup fails with 
```
error[E0658]: use of unstable library feature 'renamed_spin_loop'
  --> /workspace/.cargo/registry/src/github.com-1ecc6299db9ec823/spinning_top-0.2.3/src/spinlock.rs:57:17
   |
57 |                 hint::spin_loop();
   |                 ^^^^^^^^^^^^^^^
   |
   = note: see issue #55002 <https://github.com/rust-lang/rust/issues/55002> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `spinning_top`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `nu v0.30.1 (/workspace/nushell)`, intermediate artifacts can be found at `/workspace/nushell/target`
```
The error looks similar to #3282 which was solved by updating rust to 1.51
Default rust version for gitpod is 1.51 see https://github.com/gitpod-io/workspace-images/blob/master/full/Dockerfile#L196 so should be good?
(Also the README states you need rust 1.47 or later is this correct?)

**Comment by aleybe** [comment]
I was able to resolve this in gitpod by entering this into the shell: 
`bash -cl "rustup default stable"`

I think the default rust version is behind which is causing this error. I don't know enough about gitpod (or rust for that matter :S) to give any more of a comment on this 😂

**Comment by ijt** [comment]
I'm getting this same error when running `cargo install nu`. Unfortunately, I don't have `rustup` on the box I want to run this on, and I don't have access to install it there.

**Comment by aleybe** [comment]
Are you using this inside the gitpod for nushell @ijt ?

**Comment by ijt** [comment]
I wasn't but then I took your suggestion and built it within gitpod, then
scp-ed it to my box. Now it's working for me. Thanks!

**Comment by floh96** [comment]
this is still an issue

**Comment by TommasoBianchi** [comment]
I think the issue here might be related with the fact that gitpod is not rebuilding the custom Docker image on prebuilds unless the Dockerfile is changed, which leads to the usage of an old image with an outdated rust version (looks like `1.48` to me).

A way to solve this might be to make use of a gitpod `init` task to run `rustup default stable` (similarly to what @aleybe suggested, but in an automated way).

**Comment by floh96** [comment]
this seems to be fixed:
> 🤙 This task ran as a workspace prebuild
