### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by cup** [nushell/nushell#339]
please and thank you

https://github.com/nushell/nushell/releases

**Comment by jonathandturner** [comment]
Roger that, working it now

**Comment by mistydemeo** [comment]
Echoing this - glad to hear you're already looking into it! Having git tags would make it easier for package managers to package this. Right now it's not clear which git revision lines up with which cargo release.

**Comment by jonathandturner** [comment]
They should now be available at: https://github.com/nushell/nushell/releases/tag/0.2.0

If you hit any hiccups, let us know :)

**Comment by jonathandturner** [comment]
@mistydemeo - good point, will do that next time to make it easier
