### ISSUE TITLE
engine-p: list of commands that have not yet been ported

### ISSUE THREAD

**Issue by stormasm** [nushell/nushell#3390]
Updated June 30, 2021
I have been trying to keep up with this list but may have missed one or two commands that have already been ported.  If you find one that is already ported but still on this list please ping me and I will remove it...

Updated June 7, 2021
Finish removing arg deserialization #3552 
* Remove the .process() for argument that uses deserialization
* Remove the arg deserializer
* Convert all commands to use simpler evaluation

Updated June 4, 2021
[See these comments as well...](https://github.com/nushell/nushell/issues/3390#issuecomment-854720771)

#### How do you tell quickly what commands have not been ported to engine-p ?

```
cd crates/nu-command/src
rg Deserialize
```

This will show you this line of code
```rust
#[derive(Deserialize)]
```

and lead you to another way to show a command has not been ported.

```rust
args.process()?;
```

If you see the above line of code anywhere in a command file its a candidate for re-factoring to engine-p style coding...

I am hoping to write up the steps needed to port a command over to engine-p in a tutorial style fashion similar to [andrasio's](https://github.com/andrasio) excellent document called [Implementing a Nu Command Guide](https://github.com/nushell/nushell/blob/main/docs/implementing_a_command.md)...

Once I port over one or two commands myself I will have a better sense of the content of the tutorial.

#### List of Commands that have not yet been ported

This is an evolving list; as commands get merged I will delete them from this list....

* append.rs
* debug.rs
* def.rs
* default.rs
* describe.rs
* du.rs
* empty.rs
* every.rs
* exec.rs
* first.rs
* flatten.rs
* get.rs
* help.rs
* history.rs
* insert.rs
* kill.rs
* length.rs
* let_env.rs
* merge.rs
* nth.rs
* nu/plugin.rs
* open.rs
* pivot.rs
* prepend.rs
* reduce.rs
* reject.rs
* rename.rs
* rotate/command.rs
* rotate/counter_clockwise.rs
* seq.rs
* seq_dates.rs
* skip/command.rs
* sleep.rs
* sort_by.rs
* source.rs
* split_by.rs
* split/column.rs
* split/row.rs
* termsize.rs
* touch.rs
* to_html.rs
* to_md.rs
* update.rs
* where_.rs
* with_env.rs
* wrap.rs

**Comment by kubouch** [comment]
You can also search for `ActionStream` and `run_with_actions` :-).

**Comment by stormasm** [comment]
@kubouch thanks for the update, also can you please (if you remember) if you port over any of the other commands on this list --- then note them here and I will go through and update the above list with the PR number where the command was ported over...  thank you !  its great that you were already able to port over some of the commands...

**Comment by kubouch** [comment]
OK, I'll always mention this issue in my PRs.

**Comment by stormasm** [comment]
### Completed commands in alphabetical order

range.rs @kubouch #3377

**Comment by stormasm** [comment]
### History of engine-p commits...

#3270 Switch to "engine-p" starts on April 6, 2021

**Comment by efx** [comment]
The introductory comment is quite helpful @stormasm!
Two quick additions:
- I noticed that `args.process()` is only used in a comment so it is better to search for the serialize.
- per @kubouch's [advice](https://github.com/nushell/nushell/issues/3390#issuecomment-833869530), you can search for what files contain those patterns with:
```sh
 rg --files-with-matches 'ActionStream|run_with_actions'
 ```
 I'm combining all searches using:
 ```sh
 rg --files-with-matches 'Deserialize|ActionStream|run_with_actions'
 ```
 And nu flavored fanciness:
 ```nu
 rg --files-with-matches 'Deserialize|ActionStream|run_with_actions' | lines | path basename | wrap | sort-by Column
```

**Comment by stormasm** [comment]
Not everything is done so please keep open...

**Comment by jntrnr** [comment]
Closing this in favour of #4357
