### ISSUE TITLE
Panic when defining alias using string interpolation

### ISSUE THREAD

**Issue by esbullington** [nushell/nushell#3396]
**Describe the bug**

Receive panic when I try to define alias using string interpolation.

```alias ev = vim `{{$nu.env.XDG_CONFIG_HOME}}/vim/vimrc` ```
 
Msg: "thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 3'"

I also reproduced using string interpolation with non-environmental variables.

**To Reproduce**
1. Define alias with string interpolation, either in config startup or at prompt

**Expected behavior**
Expect not to crash, and ideally define alias using interpolated string.

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
────┬────────────────────┬────────────────────────────────────────────
 #  │      Column0       │                  Column1
────┼────────────────────┼────────────────────────────────────────────
  0 │ version            │ 0.30.1
  1 │ branch             │ pager_vi_keybindings
  2 │ short_commit       │ 8308c09c
  3 │ commit_hash        │ 8308c09c504de0444179eb01d3eca03feb0d7e0b
  4 │ commit_date        │ 2021-05-06 15:57:20
  5 │ build_os           │ linux-x86_64
  6 │ rust_version       │ rustc 1.51.0 (2fd73fabe 2021-03-23)
  7 │ rust_channel       │ stable-x86_64-unknown-linux-gnu (default)
  8 │ cargo_version      │ cargo 1.51.0 (43b129a20 2021-03-16)
  9 │ pkg_version        │ 0.30.1
 10 │ build_time         │ 2021-05-07 15:29:22
 11 │ build_rust_channel │ debug
 12 │ features           │ clipboard-cli, ctrlc, default,
    │                    │ directories, dirs, ptree, rustyline, term,

```

**Add any other context about the problem here.**

@jonathandturner requested bug report in discord.

**Comment by jgoday** [comment]
@esbullington This seems to be a problem with the string interpolation expansion in 'nu-engine/src/shell/painter.rs', styles in Painter are initialized before string interpolation occurs.
Simplest solution to avoid this panic could be something like this ?  https://github.com/jgoday/nushell/commit/ac6eeb9c3abc44b95910d1c6c772084f3235fb33

**Comment by ahkrr** [comment]
Reading this issue, it could also be related to parsing and substituting aliases and not adjusting all spans correctly, as was investigated in this #3196 PR. 
The incorrect spans would, if I remember correctly, also end up crashing the painter.

**Comment by jonathandturner** [comment]
I've fixed some of the alias panicks. Does this issue still repro on more recent versions of Nushell?

We've also changed the string interpolation from backtick to `$"(3 +4)"`

**Comment by ueXIMcWizBrdyVEciAlSwxP8aaXP70mO** [comment]
On `0.32.0` (Linux 5.10), after adjusting for the string interpolation syntax, this issue no longer causes problems. I tested with the following `config.toml`:
```
startup = [
    'alias ev = vim $"($nu.env.XDG_CONFIG_HOME)/vim/vimrc"'
]
```

**Comment by jonathandturner** [comment]
I'm seeing similar when used on the commandline: `alias ev = vim $"($nu.env.XDG_CONFIG_HOME)/vim/vimrc"` seems to work okay.

Closing, but if you still see the issue, please reopen.

**Comment by Xananax** [comment]
I'm not managing to create aliases.

```
Error: nu::parser::cant_alias_expression

  × Can't create alias to expression.
     ╭─[/home/xananax/.config/nushell/config.nu:769:1]
 769 │ 
 770 │ alias godot4 = $"($nu.env.HOME)/.local/share/hourglass/versions/4.1/godot --editor"
     ·                ──────────────────────────────────┬─────────────────────────────────
     ·                                                  ╰── aliasing StringInterpolation is not supported
 771 │ alias godot3 = $"($nu.env.HOME)/.local/share/hourglass/versions/3.5/godot --editor"
     ╰────

```

I attempted all the syntaxes referenced in this thread, as well as using `$env.HOME` instead of `$nu.env.HOME`.

**Comment by hustcer** [comment]
How about ?
```nushell
alias godot4 = do -i { ^$"($nu.env.HOME)/.local/share/hourglass/versions/4.1/godot --editor" }
```

**Comment by Xananax** [comment]
Neat! The second one works. 

The first syntax suppressed errors, but running `godot4` would have no effect.

Thanks!

(For anyone reading in the future, additionally to notice the argument sits outside of the binary path, which is enclosed in quotes)
