### ISSUE TITLE
Improve consistency: lists vs. tables, math-mode vs. commands

### ISSUE THREAD

**Issue by mb21** [nushell/nushell#3397]
**Is your feature request related to a problem? Please describe.**
I had a hard time coming up with the following and didn't like the result either:

    ls ** | where {= $(echo $it | get name | str from | str ends-with '.css')} | sort-by size

## Background

I really like the philosophy of nushell, especially this part:

> the pipeline, which borrows heavily from the original Unix ideas of connecting simple programs together into more complex commands.

Because this is essentially saying that we value composability. So I was a little surprised to see that there are several things in nu (as currently implemented) that don't seem to compose very well.

This issue may be somewhat echoing #1134:

> There are a lot more bugs and inconsistencies. To fix these bugs, I believe the grammar must be simplified, to make it more consistent and intuitive. Furthermore, a formal grammar is necessary for contributors, so we know what the desired behavior is in some edge cases.

Feel free to close as duplicate as you see fit.

### Lists vs. Tables

Taking an [example from the book](https://www.nushell.sh/book/working_with_tables.html#getting-data-out-of-a-table):

`ls | get name` returs a list, while `ls | select name` returns a table. Which requires this awkward explanation:

> The one way to tell these apart looking at the table is the characteristic `value` column name

This means that while I can do:

    ls | select name | where name == test

I require a more elaborate syntax to work on the list:

    ls | get name | where {= $it == test}

Contrast this with SQL where "everything is a table". `SELECT 7;` is a valid statement that returns a table with one row and one column (there's also [syntax for bigger tables](https://www.postgresql.org/docs/9.4/queries-values.html)). And it can be composed in subqueries as follows:

    SELECT * FROM (SELECT 7) AS foo;
  
     ?column? 
    ----------
            7
            
Notice that the column name is auto-generated, similar to:

    echo [[meal size]; [arepa small]] | pivot
    ───┬─────────┬─────────
     # │ Column0 │ Column1 
    ───┼─────────┼─────────
     0 │ meal    │ arepa   
     1 │ size    │ small   
    ───┴─────────┴─────────

### Commands vs math-mode

Continuing the previous example, if I want to use something more elaborate than a simple operator like `==`, say e.g. `str ends-with`, which happens to be a command, then I end up with:

    ls | where {= $(echo $it.name | str ends-with ".css") }
    
Why do I need to enter math-mode (expression mode?) and then immediately go into command-mode with `$()` again? or what exactly is it `$()` does anyway?

What is the difference between `echo 7` and `= 7`? Sometimes they both work: `echo 1 | inc` and `= 1 | inc` both return `2`. But while `echo 1 | describe` says `integer`, neither `echo 1 + echo 1` or `(echo 1) + (echo 1)` do what I want.

And what's the difference between `echo` and `build-string`? I can even do `build-string 1 | inc`?

## Proposal

What would seem consistent and composable to me, as a new user of nu, would be:

- What has been known so far as a list, is a table with one column.
- A pipeline stage always consumes/outputs a table.
- A table with only one row and one column, is automatically cast to the primitive value it contains if necessary. (Thus if a pipeline ends in such a table, only the value will be printed out.)
- Also vice-versa: primitive value is cast to a table if necessary.
- Primitive values, tables, and also commands and blocks are [expressions](https://doc.rust-lang.org/reference/statements-and-expressions.html). (This is what #3389 seems to take a stab at?)
- Blocks are simply [lambda functions](https://doc.rust-lang.org/rust-by-example/fn/closures.html).

## Examples

```
> [1 2 3] | each { $it.Column0 + 1 }
───┬─────────
 # │ Column0 
───┼─────────
 0 │ 2
 1 │ 3
 2 │ 4
───┴─────────

# when the table has only one column, the following shorthand also works:

> [1 2 3] | each { $it + 1 }
───┬─────────
 # │ Column0 
───┼─────────
 0 │ 2
 1 │ 3
 2 │ 4
───┴─────────

> ['bob' 'fred'] | each { `Hi {{$it}}!` }
───┬──────────
 # │ Column0  
───┼──────────
 0 │ Hi bob!  
 1 │ Hi fred! 
───┴──────────

> ('foo' | str starts-with 'f') && (7 + 3 == 10)
true

> 'ls' | str capitalize
Ls

> echo ls | str capitalize
Ls

> ls | where { $it.name | str ends-with ".css" }
────┬───────────────────────┬──────┬──────────┬─────────────
 #  │         name          │ type │   size   │  modified   
────┼───────────────────────┼──────┼──────────┼─────────────
  0 │ AppComponent.css      │ File │  35.1 KB │ 2 years ago 
────┴───────────────────────┴──────┴──────────┴─────────────

> ls | where { let name = $it.name; (name | str ends-with ".css") && (name | str starts-with "App") }
────┬───────────────────────┬──────┬──────────┬─────────────
 #  │         name          │ type │   size   │  modified   
────┼───────────────────────┼──────┼──────────┼─────────────
  0 │ AppComponent.css      │ File │  35.1 KB │ 2 years ago 
────┴───────────────────────┴──────┴──────────┴─────────────

> let increment = { $it + 1 }
> [1 2 3] | each $increment
───┬─────────
 # │ Column0 
───┼─────────
 0 │ 2
 1 │ 3
 2 │ 4
───┴─────────

> 'bob' | { `Hi {{$it}}!` }
Hi bob!

# The above is a bit weird, so maybe worth considering making the argument of the lambda explicit:

> 'bob' | \name{ `Hi {{$name}}!` }
Hi bob!

> ['bob', 'fred'] | each \item index{ `{{$index + 1}}. {{$item | str capitalize}}` }
───┬─────────
 # │ Column0 
───┼─────────
 0 │ 1. Bob  
 1 │ 2. Fred
───┴─────────

> [London Washington] | append Guayaquil
───┬────────────
 # │ Column0
───┼────────────
 0 │ London
 1 │ Washington
 2 │ Guayaquil
───┴────────────

> [[city size]; [London medium]] | append [NY big]
───┬────────┬─────────
 # │ city   │   size  
───┼────────┼─────────
 0 │ London │  medium 
 1 │ NY     |  big    
───┴────────┴─────────
```

Sorry if this was a bit lengthy. And some of the things aren't very well-thought through yet. But I hope you see what I'm getting at.

**Comment by mb21** [comment]
Thanks for the quick and positive reply!

Cool, it seems that #3389 already goes a long way towards making more things expressions.

> A stream of rows is treated as a list now

Not the other way around? I found the concept of list in the book, but nowhere [in the types](https://www.nushell.sh/contributor-book/values.html#primitive)? Ah, but that `Table` type there is probably misleading me, as it's not streamable, so not the actual table that the pipes operate on?

> So at some level the model thinks of that single value as a list of one element.

Either way, would be nice if there was consistent language in the book that mapped cleanly to the internal representation, and that `describe` then would also reflect. I thought that removing the concept of list and just having a table of rows was easiest, but... shrug.

So maybe things will start to really work if we come up with good auto-type-casting/coercion rules.

- from tables to primitives and vice versa
- from file paths to strings and vice versa

This is of course a trade-off. JavaScript famously casts almost anything to anything, which results often in very surprising behaviour. Strongly typed langauges like Rust, require the user to [cast explicitly](https://doc.rust-lang.org/rust-by-example/types/cast.html), which improves safety at the cost of some verbosity. Not sure where nu should fall on that spectrum. Putting some `| str from` in a few places is not the end of the world, but if primitives are auto-converted to tables, and tables are auto-pivoted, then why not do the same for other types?

But yeah, would definitely be nice if e.g appending two tables (`UNION` in SQL)  that don't have the same number of columns of the same type, would give an error instead of doing something stupid.

**Comment by mb21** [comment]
btw. not sure whether there is a mature rust crate that implements [parser combinators](https://en.wikipedia.org/wiki/Parser_combinator) yet, but if there is, that would definitely simplify parsing and automatic error-generation a lot...

**Comment by mb21** [comment]
One more example demonstrating the power of expressions and lambda functions:

    > date now | date to-table | \d{ `year is {{d.year}} and month is {{$d.month - 1}}` }

This would even allow us to retire the `date format` and `format` commands, since the string syntax is more general: it allows us to nest and compose arbitrary expressions (like the `$d.month - 1` in the example).

Instead of requiring a special script syntax:

    def greet [name] {
      echo "hello" $name
    }
    echo [pete bob] | each {= $(greet $it)}

you can simply do:

     let greet = \name{
       `hello {{$name}}`
     }
     [pete bob] | each $greet

Having the functions be first-class citizens, allows us to assign them to variables and pass them to other functions (also known as higher order functions):

     let greet = \formattingFn,name{
       `hello {{$name | formattingFn}}`
     }
     let greetCapitalized = \name{
       greet (str Capitalize) $name
     }
     [pete bob] | each $greetCapitalized

or if we support [currying](https://vexx32.github.io/2019/01/10/PowerShell-Functional-Features#currying-functions):

     [pete bob] | each ($greet (str Capitalize))

It seems, [PowerShell has these functional things](https://medium.com/swlh/functional-programming-in-powershell-876edde1aadb) built in, even if the syntax is sometimes a bit baroque.

---

Anyway, I actually was thinking about types and data structures. When posting the previous comments, I kind of assumed that naturally the table should be nu's canonical aggregate data type (like it is in SQL). But maybe that's not smart. Sure, a lot of builtins like `ls` and `ps` return tables, but a primary feature of nu is also working with JSON files, which aren't tables, but are a composition of lists/arrays and dictionaries/hashtables/objects. And while it's natural to emulate a table as a list of dictionaries (that's what MongoDB does), the other way around is not so straightforward (because a table requires all rows to have the same keys, so it is less general).

So maybe we should simply have lists and dictionaries and nothing more?  (that's actually what [PowerShell seems to be doing as well?](https://ss64.com/ps/syntax-datatypes.html), couldn't find the corresponding official docs). If all rows have the same key, we can still visualize it as a table, of course. And if we want these things to be strictly typed, with few or no automatic casts, then something like [TypeScript's appraoch to typing JS objects](https://www.typescriptlang.org/docs/handbook/interfaces.html) seems like a good fit:

> One of TypeScript’s core principles is that type checking focuses on the shape that values have. This is sometimes called “duck typing” or “structural subtyping”.

(Which I'm sure you're familiar with ;-))

Would have to experiment around to see whether the types don't get in the way too much in a shell... but I feel nu would profit greatly from a more rigorous and explicit approach here. To avoid inconsistencies like this weird-looking output that `describe` says is a string, but looks like a table, but should be a list of one element I think?

```
> cat test.json
{
  "files": ["foo"]
}

> open test.json | get files
───────┬─────────────────────
       │ /Users/me/test.json
───────┼─────────────────────
   1   │ foo
───────┴─────────────────────
```

**Comment by mb21** [comment]
Still think this would be good to do :)

**Comment by jonathandturner** [comment]
@mb21 - since some of these work now and some still don't, can you file a new issue or update this current issue, to reflect the remaining work? It'd make it easier for folks to jump in and start fixing the things that aren't done.

**Comment by dumblob** [comment]
How about just declaring that:

1) each command has to accept pipe data in the most generic format (I'm deliberately not saying what format it is, but I'm sure it has to be extensible at least in compile time as newly defined commands can require new data types which won't fit the existing set of data types the generic format will support) - imagine something like [TLV](https://en.wikipedia.org/wiki/Type%E2%80%93length%E2%80%93value ) or any other stream-oriented **extensible** (unlike msgpack/cbor/...) efficient (in terms of native binary data support unlike JSON/XML/...) format like [uSX](https://github.com/dumblob/uSX ) or [ston](https://github.com/Hejsil/ston )
2) each command is **in addition to (1)** encouraged to accept also data in other formats - especially the one format which **the command itself finds most efficient** to work with (targetting zero-copy)
3) each command is required to produce pipe data in the most generic format (the same one as in (1) )
4) each command is **in addition to (3)** encouraged to produce also data in other formats - especially the one format which **the command itself finds most efficient** to work with (targetting zero-copy)
5) at the beginning of the pipe plumbing both producer and consumer will try to find the most efficient way to exchange data

This is to avoid any need for conversion commands in between while at the same time offer run-time detection of the most efficient way to produce & consume data.

Btw. having separate filtering commands as the primary recommended measure to filter data in pipelines might sound very tempting but it actually makes things less composable in practice considering that non-filtering commands will be extended over time which will result in new filtering needs and these will at some point be impossible to satisfy in the generic context of a "filtering command" and will be satisfiable only in the contexts of non-filtering commands.

Another reason is that filtering commands will never be able to efficiently support the special data types and thus everything would in practice just collapse to using the generic format significantly harming performance. Actually this whole idea might be implemented as an extension subcommand for "generic" filtering commands but the "main" implementation would be rooted in the non-filtering command.

@mb21 your suggestions sound very rigorous so I think you might be interested in [Til](https://github.com/til-lang/til ) which looks and has very similar goals as Nushell, but it actually didn't grow "based on needs over time" as Nushell but rather as a rigorously engineered language trying to solve all the toughest corner cases already from the beginning (but it lacks nice sugar Nushell has - e.g. implicit `| autoview` if missing any sink etc.).

**Comment by mb21** [comment]
@jntrnr I'll update nushell and try to play around with it and see which cases now work...

> your suggestions sound very rigorous so I think you might be interested in Til which looks and has very similar goals as Nushell, but it actually didn't grow "based on needs over time" as Nushell but rather as a rigorously engineered language 

yes! that more rigorous (or composable/consistent) approach is exactly what I think Nushell could profit from. Til looks cool, but seems to suffer the opposite problem? No easy to use built-in operators/commands for often-used things like working with the filesystem, json parsing etc.? That's the area where Nushell really shines in my opinion :)

**Comment by jntrnr** [comment]
Are there some parts of Nushell that feel less compatible or consistent? That's definitely the goal though no doubt there are places we can improve.

**Comment by dumblob** [comment]
>Til looks cool, but seems to suffer the opposite problem? No easy to use built-in operators/commands for often-used things like working with the filesystem, json parsing etc.?

Actually I'm pretty convinced all this can be built in the very same manner **but rigorously/composably** in Til. Til is much younger, so it didn't put much effort yet into introducing all these commands which make nushell practically usable already now. The idea is, that building these commands on top of the rigorous/composable base is much easier and faster than in nushell :wink:. But your mileage may vary...

**Comment by mb21** [comment]
I quickly went through the original examples with `nushell v0.33.0` and quite a few indeed work now (mostly around math mode / expressions), nice! But also quite a few still fail:

```
['bob' 'fred'] | each { `Hi {{$it}}!` }

ls | where { $it.name | str ends-with ".css" }

ls | where { let name = $it.name; (name | str ends-with ".css") && (name | str starts-with "App") }

'bob' | { `Hi {{$it}}!` }

'bob' | \name{ `Hi {{$name}}!` }

['bob', 'fred'] | each \item index{ `{{$index + 1}}. {{$item | str capitalize}}` }
```

or don't do a useful thing:

```
[[city size]; [London medium]] | append [NY big]
```

**Comment by jntrnr** [comment]
This issue I think got a lot better with the new engine, that's now in nushell main.

In short, we can tell a difference between different structure types, and don't auto-flatten anymore. Things like `echo 1` and `echo [1]` no longer look like each other.

Of the @mb21 list (with updated syntax):

Works:
```
> ['bob' 'fred'] | each { $"Hi ($it)!" }
╭───┬──────────╮
│ 0 │ Hi bob!  │
│ 1 │ Hi fred! │
╰───┴──────────╯
```

```
> ls | where ($it.name | str ends-with ".toml")
╭───┬───────────────┬──────┬─────────┬───────────────╮
│ # │     name      │ type │  size   │   modified    │
├───┼───────────────┼──────┼─────────┼───────────────┤
│ 0 │ Cargo.toml    │ file │ 3.6 KiB │ 5 minutes ago │
│ 1 │ Makefile.toml │ file │   449 B │ a day ago     │
│ 2 │ rustfmt.toml  │ file │    16 B │ a day ago     │
╰───┴───────────────┴──────┴─────────┴───────────────╯
```

```
> ls | where { |row| let name = $row.name; ($name | str ends-with ".toml") && ($name | str starts-with "Ca") }
╭───┬────────────┬──────┬─────────┬───────────────╮
│ # │    name    │ type │  size   │   modified    │
├───┼────────────┼──────┼─────────┼───────────────┤
│ 0 │ Cargo.toml │ file │ 3.6 KiB │ 9 minutes ago │
╰───┴────────────┴──────┴─────────┴───────────────╯
```

```
> 'bob' | $"Hi ($in)!"
Hi bob!
```

```
> 'bob' | each { |name| $"Hi ($name)!" }
Hi bob!
```
```
> ['bob', 'fred'] | each -n {|item| $"($item.index + 1). ($item.item | str capitalize)" }
╭───┬─────────╮
│ 0 │ 1. Bob  │
│ 1 │ 2. Fred │
╰───┴─────────╯
```

With those working, I think I'll close this, but file an issue for the `[[city size]; [London medium]] | append [NY big]` case.

If there are others I missed, let's file separate issues for them. While it's great to brainstorm in one place, as things progress, it's easier to track functionality in separate issues.

Cheers for everyone jumping into this one.

**Comment by mb21** [comment]
nice, the new engine seems to be really paying off!

**Comment by morzel85** [comment]
`['bob' 'fred'] | each { $"Hi ($it)!" }`

Does not work 0.75.0

```
1 │ ['bob' 'fred'] | each { $"Hi ($it)!" }
   ·                       ────────┬───────
   ·                               ╰── variable not found
```

**Comment by mb21** [comment]
@morzel85 I think the special `$it` variable doesn't exist anymore, you can just supply each with a normal function/closure:

```
['bob' 'fred'] | each {|n| $"Hi ($n)" }
```
