### ISSUE TITLE
Can't access directores with "..." in their name even when using autocomplete

### ISSUE THREAD

**Issue by jansol** [nushell/nushell#3398]
**Describe the bug**
A directory with "..." in its name does for all intents and purposes not exist to nushell. Such a directory can't be created  either as `mkdir "a...b"` results in a directory and a subdirectory in it: `a../..b`.

**To Reproduce**
1. Have a directory named say, "a...b"
2. Verify that it's there with `ls`
3. Try to cd into it in nushell by either typing the name manually or autocompleting it from the first letter(s)
4. "directory not found"

**Expected behavior**
Autocompletion should escape directory names correctly where needed.

**Configuration (please complete the following information):**

```
~
❯ version | pivot
───┬────────────────────┬────────────────────────────────────────────────────────────
 # │      Column0       │                          Column1
───┼────────────────────┼────────────────────────────────────────────────────────────
 0 │ version            │ 0.30.0
 1 │ build_os           │ linux-x86_64
 2 │ rust_version       │ rustc 1.51.0
 3 │ cargo_version      │ cargo 1.51.0
 4 │ pkg_version        │ 0.30.0
 5 │ build_time         │ 2021-04-25 10:06:26
 6 │ build_rust_channel │ release
 7 │ features           │ ctrlc, default, directories, dirs, ichwh, rustyline, term,
   │                    │ which, zip
───┴────────────────────┴────────────────────────────────────────────────────────────
```

**Comment by kubouch** [comment]
It seems to autocomplete an existing `a...b` directory but, indeed, `cd` and `mkdir` doesn't work correctly.

BTW, is there a common use case for naming paths with `...` in them?

**Comment by jonathandturner** [comment]
Just a hunch, but I wonder if this is coming from our path expansion code that handles things like `~`. We may need logic in there to split the path on the path separator and then only expand if one of the sub-parts is an exact match. That way we're not expanding in the middle of strings but rather entire path elements.
