### ISSUE TITLE
nu shell should understand tilde ~ home directory

### ISSUE THREAD

**Issue by RokuKent** [nushell/nushell#340]
```
/Users/ksandvik/Downloads> cd ~/dl
error: Parse Error
- shell:1:3
1 | cd ~/dl
  |    ^^^^
/Users/ksandvik
```

**Comment by vors** [comment]
This is a super annoying nit that I trip over so many times in the first 10 minutes that I had to switch back to my default shell.

**Comment by androbtech** [comment]
Thanks @vors ! Will ping you when support is built-in. Apologies are in order.

**Comment by ryzokuken** [comment]
Looking into this.

**Comment by wycats** [comment]
We should only expand `~` if the value is being coerced into a path.

**Comment by wycats** [comment]
I'm working on this

**Comment by jonathandturner** [comment]
Basic support has now landed as https://github.com/nushell/nushell/pull/479
