### ISSUE TITLE
Minor enhancement: Display mode information in vi editing mode, simillar to `vi_ins_mode_string` and `vi_cmd_mode_string` set in `.inputrc`

### ISSUE THREAD

**Issue by Delanii** [nushell/nushell#3416]
**Is your feature request related to a problem? Please describe.**
While using nushell in `vi` editing mode there is no option to display currently active `vi` mode (insert/normal).

**Describe the solution you'd like**
It would be great if nushell would display currently active mode (insert/normal) while using `vi` editing, similar to how it is displayed by  `vi_ins_mode_string` and `vi_cmd_mode_string` set in `.inputrc` with bash/zsh shell. This might be purely `rustyline` feature, so let me know if I should redirect my request there.

**Describe alternatives you've considered**
I dont know about any.

**Comment by fdncred** [comment]
I think you guessed right. If `rustyline` supports this functionality, we can probably support it. Do you know if this type of thing exists in `rustyline`?

**Comment by Delanii** [comment]
My knowledge of `rustyline` features goes only as far as its documentation outline says, and there seems to be no such feature documented. I was myself suprised that this is dealt with by `readline` library and not the prompt (not mentioning shell).

I try to repost this to `rustyline`.
