### ISSUE TITLE
can't call executables in path

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#3418]
**Describe the bug**
Nushell doesn't allow me to call executables in my `$nu.path`. I thought we had fixed this recently with [this pr](https://github.com/nushell/nushell/pull/3336).

**To Reproduce**
1. find an exe in your path
2. try to run it
3. watch it fail

**Expected behavior**
Run the command

|key|value|
|-|-|
|version|0.31.1|
|branch|main|
|short_commit|3aa00b78|
|commit_hash|'3aa00b78f95b308a6d76eef086e018cd0e0252d0'|
|commit_date|2021-05-12 03:53:34|
|build_os|windows-x86_64|
|rust_version|rustc 1.52.1 (9bc8c42bb 2021-05-09)|
|rust_channel|stable (default)|
|cargo_version|cargo 1.52.0 (69767412a 2021-04-21)|
|pkg_version|0.31.1|
|build_time|2021-05-12 07:37:45|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, default, directories, dirs, ptree, rustyline, term, trash, uuid, which, zip|

**Comment by jonathandturner** [comment]
No repro for me. I just ran `cargo run` and was able to run `notepad.exe`.

**Comment by fdncred** [comment]
#3422 fixed this.
