### ISSUE TITLE
Consider an alternative to reqwest

### ISSUE THREAD

**Issue by orf** [nushell/nushell#342]
Reqwest is used in one major place: `open`, to obviously support opening remote URL's.

However `reqwest` the dependency adds 68 dependencies to the build, and about 4mb to the release binary size (!!!).

`reqwest` pulls in a lot of the tokio stack, and seems to support things like HTTP/2. Do we really need this? Is there a smaller, perhaps simpler library we could use instead?

**Comment by jonathandturner** [comment]
One possibility would be Surf (https://blog.yoshuawuyts.com/surf/) or something like it

**Comment by jbcden** [comment]
I would like to try working on this if that is ok. I am hoping to try and open a PR tomorrow!

**Comment by jonathandturner** [comment]
@jbcden - sounds good! you can see a PR I started (#397) but it needs to work to finish it

**Comment by jbcden** [comment]
@jonathandturner Sounds good! I am looking at it now! I started to look at this yesterday but your branch is a fair bit further along!
