### ISSUE TITLE
Tracking: std::env::vars() on Windows does not match C#

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#3423]
**Describe the bug**
Filed issue: https://github.com/rust-lang/rust/issues/85242

This is a tracking issue to follow the status of the issue in `std::env::vars()` where the output does not match the .NET output of the equivalent function.

**Comment by ChrisDenton** [comment]
Update: This should now be fixed in Rust nightly. If all goes well, it will make it to stable in version 1.55.

**Comment by fdncred** [comment]
closing this because upstream issue seems to have been merged.
