### ISSUE TITLE
Consider an alternative to ‘open’

### ISSUE THREAD

**Issue by Joshfindit** [nushell/nushell#343]
MacOS has an `open` command that is very convenient.

(At least I think so, I use it quite frequently)

**Comment by jonathandturner** [comment]
Ah, that's true.

At least in theory, you can use the native open by using `^open`. Not sure if that would become muscle memory in time, or if it would be annoying.

**Comment by Joshfindit** [comment]
I’m honestly not sure how annoying it would be, I suppose it would matter whether I used Nu’s open or Apple’s open more often. I feel like they would both be fairly common in an ideal world.

As this was percolating since opening it, a suggestion popped in:
How about call the binary `nushell` and the ‘open’ command `nu`?

It’s just spitballing, so no pressure, but it *is* 50% less typing...

**Comment by androbtech** [comment]
You are right. I use macOS's `open` very frequently too. Support for using native commands instead of `nu`'s was landed this week before releasing. You can imagine how I was doing while it wasn't supported.

So far I've been Ok calling escaping commands `^open` (native `open`) since in my case it's usually for opening up URL's, macOS apps, and that's it.

We are in shells. Most work with files and opening them is using shell editors, too. 

For what cases would you constantly use macOS's native `open` @Joshfindit ?

**Comment by Joshfindit** [comment]
> You are right. I use macOS's `open` very frequently too. Support for using native commands instead of `nu`'s was landed this week before releasing. You can imagine how I was doing while it wasn't supported.

!! That sounds challenging!

> For what cases would you constantly use macOS's native `open` @Joshfindit ?

- One of the main ones is opening a finder window at the current location as I manage files a lot and some things are just faster to do with the mouse.
- Viewing PDFs (not structured data, just documents to review)
- Viewing media files (images, video, audio)
- (Less often) launching applications that are not in the Applications folder

I may come back and add more as I use the computer and get reminded

**Comment by mistydemeo** [comment]
I ran into this when I was looking to report the same thing! I'd also like to suggest using an alternate command. I use `open` extensively in my day-to-day routine, for much the same reasons that Josh does; I'd also see my muscle memory interfering with learning `nu`, especially if I'm switching back and forth between `nu` and other shells.

**Comment by kuchta** [comment]
I also think that 'open' is unfortunate, since it's havily used on (not just) macOS. I would suggest to use 'read' instead which is also used by other shells, so it's not so likely to collide with another program.

**Comment by mb21** [comment]
I second @kuchta's suggestion: it should be called `read`.

I was already confusing nu's `open` and `enter` (which is which?) and `read` is just such a natural name to start a pipeline of commands with.

**Comment by jonathandturner** [comment]
Tracking a set of possible command renames in #408. Closing this in favor of working on them there.
