### ISSUE TITLE
Allow Dynamic PATH Values

### ISSUE THREAD

**Issue by oberien** [nushell/nushell#3435]
When setting up Ruby on arch-linux, it is suggested to put all user-installed ruby gems into `~/.local/...`. To add them to the `$PATH`, [the arch wiki](https://wiki.archlinux.org/title/ruby#Setup) suggests to add the following lines to the `~/.profile` to dynamically set the correct path to ruby gem binaries:
```bash
export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export PATH="$PATH:$GEM_HOME/bin"
```
With `let-env` I'm able to generate `$nu.env.GEM_HOME` during startup using
```
config set startup ["let-env GEM_HOME = (ruby -e 'puts Gem.user_dir' | str trim)"]
```
However, it is currently not possible to similarly change the path during startup or while running.
There isn't a similar command to change the path, and adding a string-interpolated value as path element doesn't work in the `config.toml`:
```
path = [..., $"{ruby -e 'puts Gem.user_dir' | str trim}/bin"]
```
That only results in the error
```
error: Couldn't parse config file:
unexpected character found: `$` at line 1 column 154
  ┌─ shell:1:1
  │
1 │ 
  │ ^ file name
```

I think there are two different use-cases here:
* I want a $nu.path element which is generated and expanded during nushell startup
* I want to dynamically change $nu.path during runtime via scripting

For the former use-case, which is the one I'm having, it could make sense to allow string-expansion in the `path` config value.
For the latter use-case, a new command similar to `let-env` makes sense.

**Comment by jokeyrhyme** [comment]
I have a similar issue, I think

I have a script that conditionally sets/updates environment variables: https://gitlab.com/jokeyrhyme/dotfiles/-/blob/master/config/environment.sh#L34

These are just dynamic enough that they cannot be expressed by the current configuration system in `nu`

I suppose a temporary work around could be to not launch `nu` directly, but launch a custom wrapper script that sets up my dynamic environment variables first and then calls `exec nu`

I'm curious about what the `nu`-way of doing this ought to be

Could `nu` have some sort of scripting support for its configuration?

**Comment by oberien** [comment]
Not stale.

**Comment by filaretov** [comment]
It seems `pathvar` might work for this? It was added recently (#3670). Be aware that you might have a version which doesn't work properly, because of flipped ';' and ':' separators, which has also already been fixed, but isn't in the 0.34.0 release (#3829).

**Comment by filaretov** [comment]
Also, I'm not sure whether this is intended to be used, but setting the PATH with `let-env PATH = ...` does change the path at runtime. This does not require using `pathvar` at all. The value of PATH has to be a correctly delimited string.

**Comment by filaretov** [comment]
If you've compiled from source recently and have a version higher than 0.34.0, sourcing the following file in the startup section of your `config.toml` should work:

```
#  ruby_gems.nu, nushell > 0.34.0

let-env GEM_HOME = (ruby -e 'puts Gem.user_dir' | str trim)
pathvar add ([$nu.env.GEM_HOME "bin"] | path join)
```

If you're on 0.34.0 or lower (i.e. you've installed Nushell from a package manager or `cargo install`), the following should also
do the trick:

```
# ruby_gems.nu, nushell <= 0.34.0

let-env GEM_HOME = (ruby -e 'puts Gem.user_dir' | str trim)
let gem-bin = ([$nu.env.GEM_HOME "bin"] | path join)
let new-path = ($nu.path | prepend $gem-bin | str collect ":")
let-env PATH = $new-path
```

The above should work for *nix systems. For Windows, PATH should be Path, and the separator is ";" (semicolon), not ":" (colon). Though I've never used Ruby, so I don't know if everything else holds for Windows.

In both cases, just add `source /path/to/ruby_gems.nu` to `startup` in `config.toml`.

For reference, here's a script that activates a Python venv, which does similar things, in case it's useful: [venv.nu](https://github.com/nushell/nu_scripts/blob/main/virtual_environments/venv.nu)

**Comment by jntrnr** [comment]
You can build up your PATH using `append` based on the results of commands.

```
> $env.PATH = ($env.PATH | append xxx)
```

Doing this in the `env.nu` should make those changes visible before the shell starts up.

We do not use bash-style string interpolation as nushell instead uses a list for PATH.
