### ISSUE TITLE
Publish to chocolatey for easier installation on Windows

### ISSUE THREAD

**Issue by TechWatching** [nushell/nushell#3436]
**Is your feature request related to a problem? Please describe.**
I want to automate nushell installation on my Windows latop and I am using chocolatey for that. Unfortunately, nushell is not available as a chocolatey package. I would be great if it were.

**Describe the solution you'd like**
```choco install nuget``` would be great.

**Describe alternatives you've considered**
I could use scoop as a package manager but I am using chocolatey for everything else and I guess many other people are.

**Additional context**
Linked to https://github.com/nushell/nushell/issues/1179.

**Comment by jonathandturner** [comment]
If someone is interested in working on this, let us know. So far we've just been letting volunteers maintain the packages on the various distros and package repos.

**Comment by jonathandturner** [comment]
@TechWatching Nushell is now on Winget. Does this check the box for easy windows installation?

**Comment by TechWatching** [comment]
Totally ! Closing the issue
