### ISSUE TITLE
cargo install nu fails 

### ISSUE THREAD

**Issue by proc** [nushell/nushell#344]
cargo install nu fails at the end with the following error:

```
Compiling pin-project v0.4.0-alpha.4
   Compiling tiff v0.3.1
   Compiling futures-async-stream v0.1.0-alpha.4
error[E0554]: #![feature] may not be used on the stable release channel
   --> /Users/petertran/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.1.0-alpha.4/src/lib.rs:194:1
    |
194 | #![feature(gen_future, generator_trait)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `futures-async-stream`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `nu v0.2.0`, intermediate artifacts can be found at `/var/folders/b2/zv_m0bg15wjc07ggkl2gpldw0000gp/T/cargo-install3eQB4o`

Caused by:
  build failed
```

**Comment by mistydemeo** [comment]
According to the instructions, Nu requires the nightly version of Rust: https://book.nushell.sh/en/installation#installing-rust

It looks like you may be using a stable release instead.

**Comment by steakknife** [comment]
`cargo +nightly ...` is the droid you're looking for (assuming `rustup toolchain install nightly` already).

**Comment by bjd2385** [comment]
For others who arrive at this issue thread, I to first came across this error during compilation --
```
...
   Compiling heim-runtime v0.0.2
   Compiling futures-async-stream v0.1.0-alpha.4
error[E0554]: #![feature] may not be used on the stable release channel
   --> /home/brandon/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.1.0-alpha.4/src/lib.rs:194:1
    |
194 | #![feature(gen_future, generator_trait)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling tiff v0.3.1
error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `futures-async-stream`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `nu v0.2.0`, intermediate artifacts can be found at `/tmp/cargo-installjqdTmZ`

Caused by:
  build failed
(base) brandon@b350-gaming-pc:~$ cargo +nightly install nu
error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed
```
Followed @steakknife's suggestion, but then hit the following error (I'm totally new to the Rust ecosystem) --
```
$ cargo +nightly install nu
error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed
```
So I ran
```
(base) brandon@b350-gaming-pc:~$ rustup toolchain install nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
...
```
and then tried the first command again, and `nu` was installed :D
```
$ nu
/home/brandon> 
```

**Comment by androbtech** [comment]
@bjd2385 Great job!

@proc Please follow [the installation instructions](https://book.nushell.sh/en/installation#installing-rust) as @mistydemeo wrote above. Thank you!

**Comment by lemourA** [comment]
Hello guys, I've already got the nightly version installed but running `cargo +nightly install nu` is issuing the following error message:
```
    Updating crates.io index
error: failed to download `nu v0.2.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-0.2.0/Cargo.toml`

Caused by:
  the `default-run` manifest key is unstable

Caused by:
  feature `default-run` is required

consider adding `cargo-features = ["default-run"]` to the manifest
```

Is Cargo saying I should add `cargo-features = ["default-run"]` to the project's build file ?

**Comment by dbarnett** [comment]
I got stuck on this, too. Looking again I do see it says "you will need to use the nightly version", but if it needs `+nightly` in the command, shouldn't that be in the instructions? And a note after the install command that "if you see `#![feature] may not be used on the stable release channel` it means you forgot to use the nightly channel" would be very helpful, too.

**Comment by codeshrew** [comment]
Another heads up, if you installed multiple versions you'll need to switch to the nightly with:

```
rustup default nightly-x86_64-apple-darwin
```

You can check what the names of your installed versions are with:

```
rustup toolchain list
```

Also, make sure you sourced the cargo env:

```
source $HOME/.cargo/env
```

**Comment by dbarnett** [comment]
@codeshrew Do you need `+nightly` only to override the default if you didn't set that to nightly, just one or the other?

**Comment by elec3647** [comment]
How do I get rustup on MacOS? I have installed other things with cargo and have rust installed, but not rustup...

**Comment by wycats** [comment]
I'm closing this as addressed through documentation. Hopefully future people who hit this issue will find this thread.

Any other feedback on how to improve the documentation to reduce the frequency of this problem would be appreciated 😄
