### ISSUE TITLE
Use box drawing characters?

### ISSUE THREAD

**Issue by Porges** [nushell/nushell#345]
IMO switching to box-drawing characters makes the output a lot more readable (this is `FORMAT_BOX_CHARS` from `prettytable`):

![Output image using box drawing characters for table](https://user-images.githubusercontent.com/12575/63629909-bca05280-c669-11e9-88f7-5e7bae9de130.png)

Would you consider doing this by default, or do we need to introduce an option?

**Comment by Porges** [comment]
And here it is using a custom format to be closer to the existing `+--+` style:
![image](https://user-images.githubusercontent.com/12575/63630429-9a5d0380-c66e-11e9-8a8d-d5ffcd9b1ab1.png)

**Comment by jonathandturner** [comment]
@Porges - do you know if this works in Windows by chance?

**Comment by Porges** [comment]
These screenshots are all from Windows 😁

**Comment by Porges** [comment]
And a third version switching the double-line interior for a bold top and bottom line (based on the LaTeX `memoir` class):

![image](https://user-images.githubusercontent.com/12575/63630979-05a9d400-c675-11e9-8beb-c573b9d0237a.png)

**Comment by jonathandturner** [comment]
Would you be interesting in submitting a PR?  There are a few options and it'd be good to give them a try to see what feels best.

**Comment by be5invis** [comment]
Users using CJK languages _may_ use legacy CJK fonts taht have full-width box-drawing characters. Be careful about them and give an option to opt-this out.
