### ISSUE TITLE
Cannot escape "|" in native command line string in windows

### ISSUE THREAD

**Issue by itn3000** [nushell/nushell#3454]
**Describe the bug**
Unexpected behavior if string in executing native command includes `|` even if string is double quoted.

**To Reproduce**

1. prepare native command(e.g. `rg`) in windows
2. create text file 
2. do `rg --help "a|b|c"` in nushell commandline

then output following error message

```
'b\' is not recognized as an internal or external command,
operable program or batch file.
```

**Expected behavior**
output `rg` help text in this example.

**Screenshots**

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
───┬────────────────────┬───────────────────────────────────────────────────────────────────────
 # │      Column0       │                                Column1
───┼────────────────────┼───────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.30.0
 1 │ build_os           │ windows-x86_64
 2 │ rust_version       │ rustc 1.50.0 (cb75ad5db 2021-02-10)
 3 │ rust_channel       │ stable (default)
 4 │ cargo_version      │ cargo 1.50.0 (f04e7fab7 2021-02-04)
 5 │ pkg_version        │ 0.30.0
 6 │ build_time         │ 2021-04-30 10:45:02
 7 │ build_rust_channel │ release
 8 │ features           │ ctrlc, default, directories, dirs, ichwh, rustyline, term, which, zip
───┴────────────────────┴───────────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**

* This seems not to be reproduced in nushell's built-in command like `echo`
* This seems not to be reproduced in linux

**Comment by fdncred** [comment]
One way to fix this maybe would be to add the pipe char to the char command like `char pipe`. I may experiment with that. That would change this command to `rg --help "a(char pipe)b(char pipe)c"` - kind of seems like the long way around. :(

**Comment by fdncred** [comment]
I just added this in a PR https://github.com/nushell/nushell/pull/3457

**Comment by itn3000** [comment]
After my investigating, I found nu tries `|` to `\|`(according to https://github.com/nushell/nushell/blob/5fcc7f23285b1abe6eb9b3a4985b9c76b0b9be80/crates/nu-command/src/commands/classified/external.rs#L153 ), 
but for cmd.exe,`^` should be used for escape character.

**Comment by fdncred** [comment]
i agree that it should be circumflex/caret to escape. i submitted a pr to fix this. unfortunately this command `rg --help "a|b|c"` still doesn't work. It returns this:
```
rg --help "a|b|c"
'b\' is not recognized as an internal or external command,
operable program or batch file.
error: External command failed
  ┌─ shell:1:1
  │
1 │ rg --help "a|b|c"
  │ ^^ command failed
```

**Comment by fdncred** [comment]
I changed a few things and got it to not error out but i'm not sure it does what you're wanting it to. it's in the main branch if you want to give it a try.

**Comment by itn3000** [comment]
I tried and the problem seems to be fixed, thank you.

**Comment by jonathandturner** [comment]
@itn3000 thanks for checking
