### ISSUE TITLE
Running path directly automatically cd-s into it

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#3460]
**Describe the bug**
Not sure if it's a feature or a bug. Entering only a path to nushell and hitting enter automatically enters the directory.

**To Reproduce**
1. be in the nushell root directory
2. `crates`
3. `pwd` (shows `.../nushell/crates`)

**Expected behavior**
Now looking at it, it's pretty cool but it came as a surprise when I first saw it. I'm not sure if it is intentional or not.

**Screenshots**

**Configuration (please complete the following information):**

Running latest main branch, i.e., with the new syntax updates.

```
  #         Column0                                    Column1
────────────────────────────────────────────────────────────────────────────────────────────
   0   version              0.31.1
   1   branch               main
   2   short_commit         cb90b90c
   3   commit_hash          cb90b90cbf60c774b6ada77282faecff32540921
   4   commit_date          2021-05-21 19:06:53
   5   build_os             linux-x86_64
   6   rust_version         rustc 1.52.0 (88f19c6da 2021-05-03)
   7   rust_channel         stable-x86_64-unknown-linux-gnu (default)
   8   cargo_version        cargo 1.52.0 (69767412a 2021-04-21)
   9   pkg_version          0.31.1
  10   build_time           2021-05-21 21:35:20
  11   build_rust_channel   debug
  12   features             ctrlc, default, directories, dirs, rustyline, term, which, zip
```

**Comment by fdncred** [comment]
I believe this is expected and part of the "auto cd" feature, iirc. https://github.com/nushell/nushell/blob/1b4f7b34c89e3919bbb901ac79a40c979c832c64/crates/nu-command/src/commands/run_external.rs#L90

**Comment by kubouch** [comment]
OK, thanks! So it's definitely intentional.

I'm not sure if I like it or not since it can be quite confusing when you're in another directory suddenly. Needs some getting used to, I guess.

**Comment by jonathandturner** [comment]
I think the fish way of doing this is to require something like `./` in front to make it less something you'd do by accident
