### ISSUE TITLE
How to open and save a list of files using wildcard

### ISSUE THREAD

**Issue by aborruso** [nushell/nushell#3465]
Hi, I have nushell 0.30.0.

I would like to open and save a list of json files using a wildcard.
Is there a nu way to run something like the command below?

```
open *.json | get s | to csv | save --raw output.csv
```

It's way to merge a lot of input files with the same structure.

Thank you

**Comment by jonathandturner** [comment]
@aborruso you might be able to do it like this:

```
ls *.json | each { open $it | get s } | save output.csv
```

**Comment by aborruso** [comment]
@jonathandturner thank you for this really really great project.

I have tried it, but I have

```
error: Type Error
   ┌─ shell:22:25
   │
22 │ ls *.json | each { open $it | get s } | save output.csv
   │                         ^^^ Expected Tagged, found row
```

**Comment by jonathandturner** [comment]
@aborruso you might need to use `each { open $it.name ... ` instead. I did it from memory :sweat_smile:

**Comment by jonathandturner** [comment]
`$it` is the whole row in the example I gave you, but you really just want the `name` column which has the filename

**Comment by aborruso** [comment]
> @aborruso you might need to use `each { open $it.name ... ` instead. I did it from memory 😅

It's really impressive, it works!!!

Now I must study and understand how to add a column with the input filename
