### ISSUE TITLE
`help` should print a list of all commands

### ISSUE THREAD

**Issue by lilyball** [nushell/nushell#347]
If I run `help` in Nu, it prints the exact same output as `bash -c help`. This is rather weird.

**Comment by jonathandturner** [comment]
We definitely need a `help` system. One idea is to have a simple one that uses what we have: https://github.com/nushell/nushell/issues/302, though we may want to go a bit further and have docs for the commandline args for builtin commands, etc.

**Comment by lilyball** [comment]
Yeah, having a help system would be good, but I'm really confused as to why the command today is giving me Bash's output.

**Comment by jonathandturner** [comment]
If nu didn't have an internal command of that name, it will call out to the OS and try to run an external command of the same name.

**Comment by lilyball** [comment]
There is no OS-level command of this name. The only thing I can imagine is that nushell is using an API that actually invokes the command using /bin/sh.

**Comment by jonathandturner** [comment]
Ahhh yes, that must be it.

**Comment by vors** [comment]
On this note, I could not find the list of all the existing commands. Not in the book, not in the build-in help.

**Comment by jonathandturner** [comment]
@vors the current list is in the readme of this repo, though I'm not sure if it's up-to-date

**Comment by vors** [comment]
@jonathandturner thank you, found it!

**Comment by wycats** [comment]
This is rather weird, but understandable.

**Comment by wycats** [comment]
Converting this issue to a feature-request for a `help` command

**Comment by wycats** [comment]
Realizing this is a dup of #302

**Comment by lilyball** [comment]
To be honest, I very explicitly did not file this as "`help` should give me a list of commands". I filed this as "why am I seeing `bash` output when running something that turns out to be a bash builtin?" because that's *very weird*. I assume there are other commands I can replicate this with too once `help` is fixed, but I haven't gone looking for them.

**Comment by twe4ked** [comment]
@lilyball is right, this is a separate issue unrelated to `help`.

As far as I can tell the issue comes from using `Exec::shell()` instead of `Exec::cmd()` when running external commands.

https://github.com/nushell/nushell/blob/628da27122e7da22f9ffd53e819267f6a87dedb8/src/commands/classified.rs#L353

Unfortunately it's not a one line change because the not-windows version is using string concatenation.

**Comment by wycats** [comment]
@lilyball Thanks for the extended response. I originally used `sh` / `cmd` as a compatibility hack (it supported shebangs and `.cmd` files for free without having to work through all of the semantics in question and reimplement them).

It was definitely a sloppy first pass, and I agree that the results amount to a bug. Do you know if there are any crates we could use that implement things like shebang and other expected shell features, or will we have to implement them from scratch?

**Comment by lilyball** [comment]
I am not aware offhand of any such crates, but I haven't researched this topic either.

My first thought is to go check out what other Rust shells are doing.
