### ISSUE TITLE
On Windows, should we make the current directory part of the path?

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#3471]
A few Windows users have pointed out that not being able to run executables in the current directory doesn't feel natural in Windows.

We could support this by adding the current directory to the top of the PATH when we do the `which` lookups for externals and when running the externals. We don't have to show it to the user, but I think -- since it feels more natural to someone in Windows -- it would just match with expectations.

**Comment by fdncred** [comment]
Agreed. Always search the current folder. Actually, I think Windows works like this when you try to execute something:
1. check local dir
2. checks each path in %PATH%, left to right
3. checks %WINDIR%

**Comment by ChrisDenton** [comment]
Here's an example of how powershell 7 behaves:

```
Z:\target\debug> hello
hello: The term 'hello' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Suggestion [3,General]: The command hello was not found, but does exist in the current location. PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\hello". See "get-help about_Command_Precedence" for more details.
Z:\target\debug> .\hello
Hello, world!
```

**Comment by jonathandturner** [comment]
I'm starting to think we should do this as it would match `cmd` and `pwsh`. We can keep non-Windows system the same as they are today, so this would only affect Windows.

**Comment by fdncred** [comment]
@jonathandturner I'd still vote for adding the current folder to the path. However, if I can manually add `.` to the `$nu.path` and nushell know to search the local folder first, then that would be a good work-around for me.

I'm also fine with working the way powershell works but I'd like to have a work-around like what I suggested above. I don't want to always have to type `.\blah` to get `blah` to run unless it's already in my path. I hate that about powershell too and on bash I always make sure `.` is in my path. :)

**Comment by rgwood** [comment]
Good news, we support this now: https://github.com/nushell/nushell/blob/c9fb381d69b0b23a7095c4d97ddf6ee476b65bb1/crates/nu-command/src/system/run_external.rs#L203-L204
