### ISSUE TITLE
calculator with pipe support

### ISSUE THREAD

**Issue by rrichardson** [nushell/nushell#348]
I tend to just run `node` when I need to do some complex math. 

This is not optimal.  I would love to do basic math inline.  I would really love a math repl where we could pipe numbers/data into and out of math expressions. 

Maybe some of the features are present in table.. but really I'd just like to do something like: 

`open foo.json | get bar.baz.size | ((/ 1024 ** 4`))` 

or something.. I'm not picky :)

**Comment by wycats** [comment]
It seems like 

```
open foo.json | get bar.baz.size | $it / 1024 ** 4
```

would be very close to working. I'm not sure that we'd want to eat up so many useful ASCII characters just for math, so maybe a literal syntax for math expressions would be the way to go?

**Comment by jedahan** [comment]
Something to consider regarding special escapes - the less sublanguages introduced the less overhead for people to learn and inconsistencies. http://www.oilshell.org/blog/2016/10/26.html

**Comment by rrichardson** [comment]
Closing this in favor of  #168  (or #574)
