### ISSUE TITLE
`load-env` for multiple environment updates

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#3481]
**Is your feature request related to a problem? Please describe.**
Currently, Nushell is a bit limited in that it can't easily `source` a dynamic script and get a set of commands to run. But what if instead, we had a way of loading a table of key/value pairs into the environment rather than thinking of it as a bunch of commands to run?

Another case that came up in discord (via lilymara) is to parse the results of an external, like `ssh-agent`, and then update the environment based on what you were able to parse.

Both of these seem like we might be able solve them with a slightly different approach that we had previously looked into.

**Describe the solution you'd like**

The new command `load-env` would be able to be handed a table that represents a set of key/value pairs. These would correlated to the variable and value used to set into the environment.

For example, this call:

```
load-env [[name, value]; ["NAME", "JT"] ["AGE", "UNKNOWN"]]
echo $nu.env.NAME # prints JT
```
The `load-env` has access to the current scope and should be able to update the environment variables this way. It needs to just take in the table value, pattern match to find the contents, iterate over the contents, and update the environment in the scope with each of the values.

I'm assuming that the above is basically equivalent to an expansion similar to:

```
let-env NAME = JT
let-env AGE = UNKNOWN
```

Though we wouldn't need to implement it as an expansion. Instead, we could reuse the environment setting logic from let-env and allow it to work over more than one pair.

**Describe alternatives you've considered**

We could make `source` allow for more dynamic calls, though this causes problems with the parser in the future.

We could also make a mutating environment update, though currently we're trying to resist any mutation/shadowing that affects values outside of the current block.

**Comment by lily-mara** [comment]
I'd like to try implementing this

**Comment by jonathandturner** [comment]
@lily-mara - sounds good. it's yours :slightly_smiling_face:
