### ISSUE TITLE
add option to trim

### ISSUE THREAD

**Issue by aborruso** [nushell/nushell#3482]
If I run `trim`

```
echo [[Column1]; ["  Value1   a lot of spaces  "] [Value3]] | str trim
```

it trims only "wrong" withe spaced at the beginning and at the end

```
───┬──────────────────────────
 # │         Column1
───┼──────────────────────────
 0 │ Value1   a lot of spaces
 1 │ Value3
───┴──────────────────────────
```

It it would be great a complete white spaces cleaning, replacing multiple whitespace with singles in the "middle", to have

```
───┬──────────────────────────
 # │         Column1
───┼──────────────────────────
 0 │ Value1 a lot of spaces
 1 │ Value3
───┴──────────────────────────
```

**Comment by fdncred** [comment]
I don't think `trim` is a command anymore. What version are you using? I don't think `str trim` works the way you want it to either, though. `str find-replace` has an `--all` flag that may help. I think we'd accept a PR to do like you're talking as long as it's behind a flag.

**Comment by aborruso** [comment]
> I don't think `trim` is a command anymore.

I have corrected my text: it's a subcommand. 

I know I can use `str find-replace`, but I think that trimmimg, using tables is especially a cleaning white spaces commands.

It's only a proposal, I'm not able to write the code to have it.

**Comment by arouene** [comment]
`trim` is a "[classic](https://en.wikipedia.org/wiki/Trimming_(computer_programming))" in computer programming, it is intended to only remove *leading* and *trailing* whitespaces.

Maybe we are missing a command like `tr` in bash (that would remove repeating char with --squeeze-repeats parameter), but `trim` IMHO do what it is intended to do.

**Comment by aborruso** [comment]
> `trim` is a "[classic](https://en.wikipedia.org/wiki/Trimming_(computer_programming))" in computer programming, it is intended to only remove _leading_ and _trailing_ whitespaces.

Thank you @arouene I do not want to change the classic meaning of trim.

Using this great tool - nushell - we are working with tables. and the trimming of whitespaces is a classic cleaning job to execute every time you have a table.
It's so popular that you have it in spreadsheet, great cli [tool as Miller](https://miller.readthedocs.io/en/latest/reference-verbs.html#clean-whitespace), cleaning tools as [OpenRefine](https://docs.openrefine.org/manual/cellediting#collapse-consecutive-whitespace), etc, etc..

I know I can do a regex search and replace. I'm doing this request because is a classic task, and I'm proposing to add it as trim option. If trim it's not the right place, what about to add a new "clean white spaces" command?

![image](https://user-images.githubusercontent.com/30607/120276668-48212b80-c2b3-11eb-916b-4e5cb8595491.png)

**Comment by fdncred** [comment]
We're fine with someone adding a PR with an `--all` flag to the `str trim` command.

**Comment by merkrafter** [comment]
Would you consider this a beginner-friendly (for this project) issue, or are there too many places involved that will need changes?

**Comment by fdncred** [comment]
I think it's pretty "beginner-friendly". You could probably make the changes in this file. https://github.com/nushell/nushell/blob/main/crates/nu-command/src/commands/str_/trim/trim_both_ends.rs

**Comment by palashahuja** [comment]
Maybe this PR can help - https://github.com/nushell/nushell/pull/3659 ?

**Comment by aborruso** [comment]
@palashahuja I think that this kind of trim is very useful: using nu, we work with tables and the trimming of whitespaces is a classic cleaning job to execute every time you have a table.

Thank you

**Comment by palashahuja** [comment]
@aborruso This feature is added to master. Feel free to try this out!

**Comment by aborruso** [comment]
Thank you very much @palashahuja  , great
