### ISSUE TITLE
option to disable field type inferencing

### ISSUE THREAD

**Issue by aborruso** [nushell/nushell#3485]
Hi,
if my input is this CSV 

```
exampleField
047
067
```

and I open it, I have field type inferencing, text to integer casting (`047` to `47`).

```
───┬──────────────
 # │ exampleField
───┼──────────────
 0 │           47
 1 │           67
───┴──────────────
```

I think it would be great to have an option that disable field type inferencing, a flag to give to `from csv` or more generally to `open` command.

We have discussed about it here https://github.com/nushell/nushell/discussions/3483

**Comment by aborruso** [comment]
@jntrnr is there no way to block field type inferencing, to have in example all strings? 

Thank you

**Comment by fdncred** [comment]
still exists on latest main branch, not sure about fixing it.

**Comment by hustcer** [comment]
`open -r a.csv | from csv --no-infer ` should work on the latest main
