### ISSUE TITLE
A symlink to a directory does not complete with a trailing slash

### ISSUE THREAD

**Issue by alexherbo2** [nushell/nushell#3490]
```
mkdir hunter-x-hunter
ln -s hunter-x-hunter hxh
```

Typing `hx▌` and pressing <kbd>Tab</kbd> results:

```
hxh▌
```

instead of:

```
hxh/▌
```

**Comment by jonathandturner** [comment]
On recent nushell versions on my machine, it looks like we complete correctly:

```
cd hx<tab>
```
now gives:
```
> cd ./hxh
```

Closing, but if you're still seeing an issue, please reopen.

**Comment by alexherbo2** [comment]
The issue is to not complete with a trailing slash.
