### ISSUE TITLE
Autocompletion of tilde path in quotes leads to a bizarre behaviour

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#3513]
**Describe the bug**
Trying to tab-complete, e.g., `'~\Down<Tab>'` prints `all?` instead. I suspect this is not the intended behaviour.

**To Reproduce**
1. Have `Downloads` folder in your home folder
2. Type `~\Down` or `~/Down`
3. Hit `<Tab>` key
4. Observe `all?` appear instead of the path

**Expected behavior**
Should autocomplete to the Downloads folder.

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
 #  │      Column0       │                            Column1
────┼────────────────────┼────────────────────────────────────────────────────────────────
  0 │ version            │ 0.31.1
  1 │ branch             │ main
  2 │ short_commit       │ ed515cbc
  3 │ commit_hash        │ ed515cbc0c8a41e3ef378d56c5c76096c14fbff0
  4 │ commit_date        │ 2021-05-28 23:10:04
  5 │ build_os           │ windows-x86_64
  6 │ rust_version       │ rustc 1.51.0 (2fd73fabe 2021-03-23)
  7 │ rust_channel       │ stable (default)
  8 │ cargo_version      │ cargo 1.51.0 (43b129a20 2021-03-16)
  9 │ pkg_version        │ 0.31.1
 10 │ build_time         │ 2021-05-30 01:57:19
 11 │ build_rust_channel │ debug
 12 │ features           │ ctrlc, default, directories, dirs, rustyline, term, which, zip
```
(also the same on 0.31.0)

**Add any other context about the problem here.**
Seems related to #3329

**Comment by kubouch** [comment]
Seems to happen only on Windows

**Comment by jonathandturner** [comment]
It may take some additional logic for Windows-specific changes to this, based on the changes in #3577

**Comment by jonathandturner** [comment]
@kubouch - if you try the latest with #3577, does it fix this issue?

**Comment by kubouch** [comment]
@jonathandturner Yes, it expands fine. It has a side effect: When you type `'~\Down<Tab>`, you lose the opening quote but I guess that's fine.

**Comment by jonathandturner** [comment]
@kubouch makes sense. In theory, you should only get quotes as part of the completion if they're needed
