### ISSUE TITLE
`sys | get cpu` shows blank `brand` column on Apple M1

### ISSUE THREAD

**Issue by reaganmcf** [nushell/nushell#3525]
**Describe the bug**
When viewing the table output from `sys | get cpu` on an Apple M1 machine, the `brand` column is empty for all entries.

**To Reproduce**
1. On an Apple m1 device, open up nushell
2. Run `sys | get cpu`

**Expected behavior**
`brand` to actually contain the proper brand name of the CPU, in this case,
 `Apple` or `Apple M1`. 

**Screenshots**
<img width="223" alt="Screen Shot 2021-05-31 at 9 06 05 PM" src="https://user-images.githubusercontent.com/20019463/120252935-04e3a000-c254-11eb-8a98-3a37468bdcb0.png">

**Configuration**
```
───┬────────────────────┬───────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                  Column1
───┼────────────────────┼───────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.31.0
 1 │ build_os           │ macos-aarch64
 2 │ rust_version       │ rustc 1.51.0
 3 │ cargo_version      │ cargo 1.51.0
 4 │ pkg_version        │ 0.31.0
 5 │ build_time         │ 2021-05-12 17:07:40
 6 │ build_rust_channel │ release
 7 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, ptree, rustyline, term,
   │                    │ trash, uuid, which, zip
───┴────────────────────┴───────────────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**

**Comment by fdncred** [comment]
Would love to have a M1 to test on. :) We rely on `sysinfo` to figure this part out. It looks like they may be working on some M1 issues https://github.com/GuillaumeGomez/sysinfo/issues/ although I didn't see anything specific to brand.

**Comment by reaganmcf** [comment]
I would be more than happy to work on this if you @fdncred or someone else wouldn't mind pointing me in the right direction in the codebase :). I've watched a view of @jonathandturner's YT videos about Nushell but that's about it, so still trying to get a grasp over the codebase.

**Comment by fdncred** [comment]
@reaganmcf The sys command is [here ](https://github.com/nushell/nushell/tree/main/crates/nu_plugin_sys)however it's not our code that needs fixing. It's the sysinfo repo that I linked above that needs to support M1 hardware. Once it's supported there, we can include that version of the crate and all should work.

**Comment by reaganmcf** [comment]
Ah. I didn't catch that it was another repo. Thanks! 👍🏻

**Comment by fdncred** [comment]
No worries. Let us know if you see any movement over there. All we'd need to do is update to the version of their crate that supports M1.

**Comment by reaganmcf** [comment]
My patch has been merged into master over at `sysinfo`. I'll open a PR with the bumped version once it's published on crates 👍

**Comment by fdncred** [comment]
nice! thanks for the help!
