### ISSUE TITLE
0.32 appears to not have been released

### ISSUE THREAD

**Issue by efx** [nushell/nushell#3528]
Thank you for all your work on nu shell!
I'm excited to try the default expression experience. 
**Describe the bug**
The [release blog article](https://www.nushell.sh/blog/2021-06-01-nushell_0_32.html) states `0.32` is available.
`cargo install nu --features=extra` says I have already installed `0.31`. 

GitHub also lists the `0.32` [release](https://github.com/nushell/nushell/releases) but that is not marked as the latest stable one.

**Expected behavior**
I expected `0.32` to have been released to the crates.io registry as the blog post stated.

**Comment by efx** [comment]
I'm curious *why* the release seems to have failed.
Was #3521 the release PR?

**Comment by fdncred** [comment]
It's not released yet. I noticed the blog as well.

**Comment by efx** [comment]
> It's not released yet; the release is still in draft.

Ah, thanks for the context!
That would explain the unlisted YouTube video. 
So this sounds like the converse.
The release blog post was deployed but nu `0.32` is not released yet.

**Comment by jonathandturner** [comment]
This PR will land when the release goes out today. Should be in a few hours

**Comment by jonathandturner** [comment]
@efx - oh looks like you found a bug in our CI. The blog post accidentally went live when the PR went up, rather than waiting for the PR to get merged.

We'll try to fix that for the next release.

**Comment by jonathandturner** [comment]
The release is out now

**Comment by efx** [comment]
@jonathandturner ah, thank you for explaining what happened!
