### ISSUE TITLE
Brew formula

### ISSUE THREAD

**Issue by ashrithr** [nushell/nushell#353]
Support for installing nushell via `brew`

**Comment by shirshak55** [comment]
there is something called nu already in brew :(

**Comment by shirshak55** [comment]
nushell is avail tho.

**Comment by ashrithr** [comment]
https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

**Comment by jonathandturner** [comment]
The formula is now available. https://github.com/Homebrew/homebrew-core/commit/f642b2d0cee68b77b7de5622011669c268df6ee9

**Comment by waldyrious** [comment]
For future reference and cross-linking, the PR to Homebrew that introduced the formula was https://github.com/Homebrew/homebrew-core/pull/43440.

**Comment by waldyrious** [comment]
Also, the formula is macOS-only for now. There's work for adapting it to Linux in https://github.com/Homebrew/linuxbrew-core/issues/15316 / https://github.com/Homebrew/linuxbrew-core/pull/15317.

**Comment by waldyrious** [comment]
Update: the formula now builds on Linux as well, following the release of Rust 1.39 which allowed the `nushell` formula to use the `rust` formula directly rather than compiling the nightly version! 🎉
