### ISSUE TITLE
Easy way to format a structured output into a string (e.g. `to txt` ?)

### ISSUE THREAD

**Issue by IgorMinar** [nushell/nushell#3531]
**Is your feature request related to a problem? Please describe.**

I'd like to have an easy way to turn a structured result into a string so that I can save it as plaintext or maybe even pass it into `less` for pagination.

Currently if I try to create a txt file from an ls output I get an error:
```
> ls | save f.txt
error: Save requires string data
  ┌─ shell:3:6
  │
3 │ ls | save f.txt
  │      ^^^^ consider converting data to string (see `help commands`)
```

**Describe the solution you'd like**
```
ls ./src/** | to txt | save files.txt

# or just

ls ./src/** | save files.txt

# also something like

ls ./src/** | to txt | less
```

**Describe alternatives you've considered**
I tried `into str` which unsurprisingly didn't work.

**Additional context**

I love the power of the structured result format, but for a day-to-day convenience there should also be a way to convert the structured result into a plain string.

**Comment by ahkrr** [comment]
I am currently using the `to md` command to do this. 
This will convert `nu tables` into plain output as `md tables` and `nu lists` will be converted to `plain lists`, basically txt.
Try to look at the differences between these commands and if this works for you as well.
```bash
ls | to md | cat

ls | get name | to md | cat

ls | select name | to md | cat
```
Depending on what you are trying to convert, a `to txt` version may still be necessary.

**Comment by fdncred** [comment]
My "hack" is to use the `nu` command while within `nushell` to produce things like this. The command that created this is `nu -c ls | lolcat`
![image](https://user-images.githubusercontent.com/343840/120655609-797f3000-c448-11eb-9158-62b2f7acc881.png)

**Comment by fdncred** [comment]
Here's another idea. You could put this into a `def` and call it when you want to use it.
```
(ls).name | into string | str collect (char nl) | save foo.txt
```

**Comment by IgorMinar** [comment]
@fdncred's idea to use nu command within nu as `nu -c ls | lolcat` is the best workaround so far (thanks for sharing it!), but I believe that this is a very frequently used feature that shouldn't require workarounds.

**Comment by fdncred** [comment]
It's @jntrnr who taught me that. :)

**Comment by fdncred** [comment]
I think this is all enabled now.

`ls | table | less -FRX` <-- pipe output through less
`ls | table | save foo` <-- save ansi enabled text to a file (not readable really but you can cat it)
`ls | table | ansi strip | save foo` <-- table without ansi colors
`(ls).name | into string | str collect (char nl) | save foo.txt` <-- same as above

@jntrnr are you ready to close this or should we make it easier yet?

**Comment by jntrnr** [comment]
Yup, I think we've added a lot more capabilities here recently. Should be fixed now.
