### ISSUE TITLE
Bat integration not working

### ISSUE THREAD

**Issue by tiffany352** [nushell/nushell#3532]
**Describe the bug**

I'm not getting syntax highlighting or line numbers when I `open` files.

When I run `open README.md`, it just dumps raw text into my terminal, without syntax highlighting. In the past, it would display it nicely highlighted using bat, and this appears to still be the intended behavior. 

**To Reproduce**
1. Run `open README.md` or any other file that should have syntax highlighting.
2. Sadness

**Expected behavior**

I remember in the past it displayed in a box with line numbers and syntax highlighting. I'd like to get that back.

**Screenshots**
![image](https://user-images.githubusercontent.com/1254344/120430197-7cd0c980-c32b-11eb-8945-6271a8720745.png)

**Configuration (please complete the following information):**

Reproduces on my Windows 10 PC:
```
❯ version
────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────
 version            │ 0.32.0
 short_commit       │ 7bf10b98
 commit_hash        │ 7bf10b980cff5df340c284b0314d9ac19b0c9590
 commit_date        │ 2021-06-01 08:11:21
 build_os           │ windows-x86_64
 rust_version       │ rustc 1.52.1 (9bc8c42bb 2021-05-09)
 rust_channel       │ stable-x86_64-pc-windows-msvc (default)
 cargo_version      │ cargo 1.52.0 (69767412a 2021-04-21)
 pkg_version        │ 0.32.0
 build_time         │ 2021-06-01 08:29:50
 build_rust_channel │ release
 features           │ clipboard-cli, ctrlc, default, directories, dirs, ptree, rustyline, term, trash, uuid, which,
                    │ zip
────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────
```

I have `bat` on my PATH and it works fine when I directly invoke it, in case that matters.

Reproduces on my Fedora Server:

```
❯ version
────────────────────┬────────────────────────────────────────────────────────────────
 version            │ 0.31.0
 build_os           │ linux-x86_64
 rust_version       │ rustc 1.51.0 (Fedora 1.51.0-3.fc33)
 cargo_version      │ cargo 1.51.0
 pkg_version        │ 0.31.0
 build_time         │ 2021-05-11 20:23:19
 build_rust_channel │ release
 features           │ ctrlc, default, directories, dirs, rustyline, term, which, zip
────────────────────┴────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**

Seems to happen even in extras builds.

**Comment by fdncred** [comment]
I wonder what's going on. I have the same build hash as your windows version and I get this.
![image](https://user-images.githubusercontent.com/343840/120478857-eaecaf00-c372-11eb-998e-782d2aefab57.png)

These are the options I have configured in my nushell config.toml file.
```toml
[textview]
term_width = "default"
tab_width = 4
colored_output = true
true_color = true
header = true
line_numbers = true
grid = false
vcs_modification_markers = true
snip = true
wrapping_mode = "NoWrapping"
use_italics = true
paging_mode = "QuitIfOneScreen"
# pager = "less -RFX"
pager = "less"
theme = "TwoDark"
```

![image](https://user-images.githubusercontent.com/343840/120479282-62224300-c373-11eb-9b35-f7249c2be9d4.png)

I don't have `bat` installed on windows at all.

|key|value|
|-|-|
|version|0.32.0|
|branch|main|
|short_commit|7bf10b98|
|commit_hash|'7bf10b980cff5df340c284b0314d9ac19b0c9590'|
|commit_date|2021-06-01 03:11:21|
|build_os|windows-x86_64|
|rust_version|rustc 1.52.1 (9bc8c42bb 2021-05-09)|
|rust_channel|stable (default)|
|cargo_version|cargo 1.52.0 (69767412a 2021-04-21)|
|pkg_version|0.32.0|
|build_time|2021-06-01 07:41:41|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, default, directories, dirs, ptree, rustyline, term, trash, uuid, which, zip|

**Comment by tiffany352** [comment]
I had no textview settings, tried copying and pasting yours into my config and I'm still not getting any highlighting.

Also just reproduced this on a third computer, also running Windows 10 with nu installed via scoop (which distributes the official GitHub releases).

I'm using Windows Terminal in case that turns out to be relevant. There's no TERM variable set, but colors are working normally when rendering tables. I tried setting TERM to `xterm-256color` just to see if it could affect it, but it didn't do anything.

```
❯ version
────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────
 version            │ 0.32.0
 short_commit       │ 7bf10b98
 commit_hash        │ 7bf10b980cff5df340c284b0314d9ac19b0c9590
 commit_date        │ 2021-06-01 08:11:21
 build_os           │ windows-x86_64
 rust_version       │ rustc 1.52.1 (9bc8c42bb 2021-05-09)
 rust_channel       │ stable-x86_64-pc-windows-msvc (default)
 cargo_version      │ cargo 1.52.0 (69767412a 2021-04-21)
 pkg_version        │ 0.32.0
 build_time         │ 2021-06-01 08:29:50
 build_rust_channel │ release
 features           │ clipboard-cli, ctrlc, default, directories, dirs, ptree, rustyline, term, trash, uuid, which, zip
────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by jonathandturner** [comment]
I'm able to repro this if I install from `scoop`. It looks like the scoop install only installs "nu.exe" and doesn't install any of the plugins that go along with it.

The textview plugin is what gives nushell the ability to do the scrolling bat view. The script used to create the nu package for scoop likely needs to be updated so that it can include the plugins as well.

We don't control the scoop package. It's handled by a third party.

I've filed an issue on the scoop repo that explains the issue: https://github.com/ScoopInstaller/Main/issues/2253

**Comment by tiffany352** [comment]
Installing the plugins in the correct location fixes the issue. Should be fine to close this ticket since the only fix is updating the scoop package.

**Comment by tiffany352** [comment]
Although, one thing that'd be nice is if `version` showed which plugins are currently enabled. That would have thrown some red flags.

**Comment by fdncred** [comment]
#3548 should take care of the version part.
