### ISSUE TITLE
Ctrl C on Windows

### ISSUE THREAD

**Issue by tiffany352** [nushell/nushell#3533]
**Describe the bug**

When I try to use ctrl+C to interrupt a process running in my shell, it ends up killing the entire shell process, with an exit code like 3221225786.

**To Reproduce**
1. Have nu on Windows 10
2. Run `cat` or another non-builtin program that takes long enough before exiting to be interruptible
3. Press ctrl+C

**Expected behavior**

The program being run should receive the interrupt and exit

**Screenshots**
![image](https://user-images.githubusercontent.com/1254344/120430951-a2120780-c32c-11eb-805b-61557010e5f1.png)

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
❯ version
────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────
 version            │ 0.32.0
 short_commit       │ 7bf10b98
 commit_hash        │ 7bf10b980cff5df340c284b0314d9ac19b0c9590
 commit_date        │ 2021-06-01 08:11:21
 build_os           │ windows-x86_64
 rust_version       │ rustc 1.52.1 (9bc8c42bb 2021-05-09)
 rust_channel       │ stable-x86_64-pc-windows-msvc (default)
 cargo_version      │ cargo 1.52.0 (69767412a 2021-04-21)
 pkg_version        │ 0.32.0
 build_time         │ 2021-06-01 08:29:50
 build_rust_channel │ release
 features           │ clipboard-cli, ctrlc, default, directories, dirs, ptree, rustyline, term, trash, uuid, which,
                    │ zip
────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**

Reproduced with both Windows Terminal and VS code. The nu process really does exit entirely.

I run into this like every day and didn't think to report it until now.

**Comment by fdncred** [comment]
can you add this to your nushell config.toml and see if the problem still happens?

`ctrlc_exit = false`

**Comment by tiffany352** [comment]
Still happens with ctrlc_exit either true or false. I've been keeping it set to false.

**Comment by fdncred** [comment]
hmm, i can't reproduce it. not sure what's going on.

**Comment by inga-lovinde** [comment]
@tiffany352 , did you install nushell using scoop by any chance? It seems to be a known bug #2641 that exists for quite a long time.

**Comment by tiffany352** [comment]
Ugh, that's frustrating. Thanks for the heads up, using the official installer fixes the issue.

I've already got multiple PRs outstanding, one of which fixes a pretty critical issue with the nu package, that seem to just be getting completely ignored for a week+, so I feel like I can't really rely on scoop anymore.
