### ISSUE TITLE
Update Starship integration instructions

### ISSUE THREAD

**Issue by janosimas** [nushell/nushell#3536]
**Describe the bug**
The new syntax breaks the old instructions.

**To Reproduce**
1. Nu 0.32
2. ```config set prompt `echo $(starship prompt)` ```

**Solution:**
The new syntax integration: 
```
config set prompt (echo 'starship prompt')
```

**Comment by jonathandturner** [comment]
I found one place in the Japanese book that uses this, so I fixed it.

Did you see other places in the docs that needed updating?

**Comment by janosimas** [comment]
When I do a search I can find it in the changelog 0.19, that's where I found it for my setup.
May it's worth to add a topic in the cookbook or contributors?

Maybe a topic for integrations with other tools, are there others worth to mention?

**Comment by jonathandturner** [comment]
@janosimas we documented it in the book as part of the configuration section: https://www.nushell.sh/book/configuration.html#prompt-configuration

**Comment by janosimas** [comment]
Now I have a different question, why does the search doesn't find this page if I search for "starship"?

**Comment by ryanpcmcquen** [comment]
For those of us who manually modify `config.toml`, this is the new line:
```
prompt = "starship prompt"
```

**Comment by jonathandturner** [comment]
> Now I have a different question, why does the search doesn't find this page if I search for "starship"?

@janosimas - it seems search will only work with the headers of the pages rather than the contents of the pages. I'll ask the folks who worked on the page if it can work over the whole pages

**Comment by fdncred** [comment]
current starship instructions for the latest main branch are located at https://github.com/nushell/nushell/blob/main/docs/3rd_Party_Prompts.md. We need to update the official docs when we release.

**Comment by fdncred** [comment]
docs are updated https://www.nushell.sh/book/3rdpartyprompts.html#starship
