### ISSUE TITLE
Add vi binding to command line edit.

### ISSUE THREAD

**Issue by locheng** [nushell/nushell#354]
In Bash, you could do 'set -o vi' to use Vi binding for command line edit. It would greatly improve the productivity for Vi users.

**Comment by iamcodemaker** [comment]
This should be straightforward to implement. Nu uses rustyline for command line editing and rustyline already supports vi mode.

**Comment by MarcoPolo** [comment]
One line patch for now
```
diff --git a/src/cli.rs b/src/cli.rs
index a04a621..26ece91 100644
--- a/src/cli.rs
+++ b/src/cli.rs
@@ -207,7 +207,7 @@ pub async fn cli() -> Result<(), Box<dyn Error>> {
     }
     let _ = load_plugins(&mut context);
 
-    let config = Config::builder().color_mode(ColorMode::Forced).build();
+    let config = Config::builder().edit_mode(rustyline::config::EditMode::Vi).color_mode(ColorMode::Forced).build();
     let mut rl: Editor<_> = Editor::with_config(config);
 
     #[cfg(windows)]
```

**Comment by jaydeland** [comment]
Sweet - Vi line editing is a great addition - will it work on the table that is returned as well?

**Comment by wycats** [comment]
We should make this work via `config`. See #100 for some design considerations on reloading the config.
