### ISSUE TITLE
do -i blocks sometimes return errors

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#3541]
**Describe the bug**
`do -i {}` is supposed to run without errors, but there are certain inputs for which it does return errors.

**To Reproduce**
```
> # outside of a git repository
> do -i { git branch | str trim }
fatal: not a git repository (or any of the parent directories): .git
```

**Expected behavior**
No error should have been returned.

---

Tested on Nushell 0.32.0.

**Comment by fdncred** [comment]
@ajeetdsouza good catch. I reproduced it too.

**Comment by fdncred** [comment]
JT straightened me out. You need to do it like this:
`> do -i { git branch } | str trim`
The only thing that should be in the block is what could fail.

**Comment by ajeetdsouza** [comment]
That's what I used eventually, but isn't the whole point of `do -i` to have a fallible _block_ of code where the error is ignored, rather than just a single expression?

**Comment by fdncred** [comment]
ya, I think it needs to be a bit more robust.

**Comment by ajeetdsouza** [comment]
Still relevant.

**Comment by ajeetdsouza** [comment]
Relevant.

**Comment by fdncred** [comment]
ok, i see what i was doing. if I do it like this `do -i { (git branch) } | str trim`, i still get errors.
