### ISSUE TITLE
`version` command does not list all the features

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#3547]
**Describe the bug**
Running `version` command does not list all the features nu was built with.

**To Reproduce**
1. Clone nu repo
2. `cargo install --path=. --features=extra,table-pager,dataframe` (my usual build command)
3. `(version).features` lists only basic features, for example `inc`,  `table-pager` and `dataframe` are missing

**Expected behavior**
It should list all the extra features as well as `table-pager` and `dataframe`.

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
❯ version | pivot
  #         Column0                                                      Column1
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   0   version              0.32.0
   1   branch               main
   2   short_commit         290c712c
   3   commit_hash          290c712cde3d84873cd7b482ae9356f28fad6b35
   4   commit_date          2021-06-02 10:49:14
   5   build_os             linux-x86_64
   6   rust_version         rustc 1.52.0 (88f19c6da 2021-05-03)
   7   rust_channel         stable (default)
   8   cargo_version        cargo 1.52.0 (69767412a 2021-04-21)
   9   pkg_version          0.32.0
  10   build_time           2021-06-02 16:11:00
  11   build_rust_channel   release
  12   features             clipboard-cli, ctrlc, default, directories, dirs, ptree, rustyline, term, trash, uuid, which, zip
```

**Add any other context about the problem here.**
I think this happened in 0.31.1 as well.

**Comment by fdncred** [comment]
[This section of code](https://github.com/nushell/nushell/blob/8b193db0cbc9eb93f8c7d3fb514b59be92e0fa30/crates/nu-command/src/commands/version.rs#L147) probably needs to be tweaked.

**Comment by fdncred** [comment]
BTW - There is an issue open here to support this as well. https://github.com/baoyachi/shadow-rs/issues/53

**Comment by kubouch** [comment]
Still does not list all the features.

**Comment by fdncred** [comment]
what features are missing?

**Comment by kubouch** [comment]
At least the `table-pager` is still missing. The default features might also be better expanded instead of just stating `default`. The `extra` features are now listed in plugins which is fine.

**Comment by fdncred** [comment]
I added this with dataframe and table-pager https://github.com/nushell/nushell/pull/3749

**Comment by kubouch** [comment]
Thanks!
