### ISSUE TITLE
syntax highlight command line, even with broken syntax

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#3549]
**Is your feature request related to a problem? Please describe.**
The second you type a `"`, `'`, `[`, `(`, or `{` the syntax highlighting on the command line breaks.

**Describe the solution you'd like**
It would be nice if the syntax highlighter uses some technique to internally complete the broken syntax which could enable the syntax highlighter to work on all but the last word you're typing.

**Describe alternatives you've considered**
Don't use syntax highlighting - say it ain't so!

**Comment by ahkrr** [comment]
Another possibility would be to immediately insert the closing `char` when typing the opening `char`, similar to settings one can enable in some text-editors. This would insert both `(` and `)` on typing `(`, `(` before the cursor and `)` after. And it would not insert a new `)` when typing `)` and the next `char` after the cursor is `)` and would only move past it.
I don't know if this behavior can be added on `nushells` side, or it has to be on `rustylines` side.

**Comment by stepnivlk** [comment]
@ahkrr I believe such a behavior should be configurable. I personally don't like it in editors.

**Comment by jonathandturner** [comment]
This should be improved on latest main. Closing, but if there are remaining issues, let's open new issues for the specific cases.
