### ISSUE TITLE
Size of Directory is wrongly displayed.

### ISSUE THREAD

**Issue by Enforcer007** [nushell/nushell#3558]
**Describe the bug**
Size of directories are always shown as 4.1KB when using ls command

**To Reproduce**
1. Open Terminal
2. Hit nu
3. Hit ls

**Expected behavior**
It should display the actual size of directory.

**Screenshots**
NU terminal:
![Nu screenshot](https://user-images.githubusercontent.com/6951100/120892485-2ebe0d80-c62c-11eb-8f43-bf8b02cb2d61.jpg)

Normal Terminal:
![terminal screenshot](https://user-images.githubusercontent.com/6951100/120892491-38477580-c62c-11eb-89de-5a80fe7c1b71.jpg)

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
───┬────────────────────┬────────────────────────────────────────────────────────────────
 # │      Column0       │                            Column1                             
───┼────────────────────┼────────────────────────────────────────────────────────────────
 0 │ version            │ 0.32.0                                                         
 1 │ build_os           │ linux-x86_64                                                   
 2 │ rust_version       │ rustc 1.52.1 (9bc8c42bb 2021-05-09)                            
 3 │ rust_channel       │ stable-x86_64-unknown-linux-gnu (default)                      
 4 │ cargo_version      │ cargo 1.52.0 (69767412a 2021-04-21)                            
 5 │ pkg_version        │ 0.32.0                                                         
 6 │ build_time         │ 2021-06-05 18:06:11                                            
 7 │ build_rust_channel │ release                                                        
 8 │ features           │ ctrlc, default, directories, dirs, rustyline, term, which, zip 
───┴────────────────────┴────────────────────────────────────────────────────────────────

```

**Comment by fdncred** [comment]
I believe this means that on your system the directory entry itself is 4.1k. Not the contents of the directory.

**Comment by Enforcer007** [comment]
Thanks @fdncred, it worked. 

But don't you think by **ls** we should get the size of contents along the listing.

Also how does **ls -d** command makes it to return with sizes. I have tried in a normal terminal it was displaying only **.** ?

**Comment by jonathandturner** [comment]
@Enforcer007 - to get the size of the contents would be very slow if it was the default, unfortunately. Imagine doing a listing of a directory that has lots of subdirectories and files in those subdirectories.

**Comment by Enforcer007** [comment]
Thanks @jonathandturner
