### ISSUE TITLE
Prompt customization

### ISSUE THREAD

**Issue by ashrithr** [nushell/nushell#356]
Is there a way to customize the prompt by setting variables or configuration?

**Comment by jonathandturner** [comment]
You can't customize the prompt, yet. That's something we could add in the future, though.

**Comment by Joshfindit** [comment]
Biggest one for me: showing the git branch

**Comment by twe4ked** [comment]
It shows the git branch by default!

```
/Users/odin/Dev/github/wycats/nushell(master)>
```

**Comment by wycats** [comment]
I really want something like this (could be added to `config`). I'd like something better than the templating on offer in existing shells, which I can't, for the life of me, ever read.

**Comment by djc** [comment]
Have been thinking about this for the past few days. Some design thoughts:

For reference, what I've been using for bash: `export PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \W \$\[\033[00m\] '`

And zsh:

```zsh
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git*' formats "%F{green}%b%f "
zstyle ':vcs_info:git*' actionformats "%F{green}%b (%a)%f "
precmd() {
    vcs_info
    PS1="%B%F{blue}%m%f ${vcs_info_msg_0_}%F{blue}%1~ \$%f%b "
}
```

I think maybe we could use format-like strings for variables, like this:

`{host} {user} {cwd} {vcs} $`

And maybe some kinds of tags for colors? You can do foreground and background colors, so maybe prefix with `f` and `b` (or `fg` and `bg`)? Could use `[]` or `<>` or `()`.

`<f:bright-green>{user}@{host}</f:bright-green> {cwd} $`

**Comment by jonathandturner** [comment]
@djc I really like this:

```
{host} {user} {cwd} {vcs} $
```

We've been talking about using similar syntax for a string parsing function, so this would be a nice parallel people could learn and use.

**Comment by wycats** [comment]
Something like this seems very cool.

**Comment by jedahan** [comment]
I really like just setting an environment variable to an array of functions. As long as the functions print to stdout, it allows people to define arbitrary customizations without needing to rely on builtins. 

It would be nice to have left and right prompt. See https://github.com/geometry-zsh/geometry as an example of what I mean.

**Comment by Southclaws** [comment]
I'd love to join this shell with the Starship prompt, both written in Rust, it's a match made in heaven!

https://github.com/starship/starship

I'm not certain on how starship is implemented under the hood though, so I'm not totally sure how easy it would be to integrate. But, it might be as simple as just importing the crate given it's Rust!

**Comment by Southclaws** [comment]
7 Emojis seems like enough interest, I have poked around the code and it seems easy enough but will require a PR to the Starship repo to make it more library-friendly as currently it just writes directly to stdout - would be neater if there was a neatly exposed function to return the prompt as a string.

I could make it invoke the starship command externally but it just seems like such a good opportunity to grab some performance given both of these things are written in Rust!

**Comment by kbd** [comment]
> I really like just setting an environment variable to an array of functions.

I always love feeling seen by fellow geeks. That’s how I do [my prompt](https://github.com/kbd/setup/blob/27218ba9f549c0ca838913987a478b18c7afd2b4/HOME/bin/shell_sources/prompt.sh#L191) and I wasn’t previously familiar with geometry.

**Comment by jonathandturner** [comment]
As of 0.6.0, you can use starship. I'll close this issue, but if we feel like we want non-starship customization, we can explore that in a different issue.

**Comment by jonathandturner** [comment]
For those finding this later, we did end up implementing configuring the internal prompt: https://github.com/nushell/nushell/pull/2064

It should be part of the 0.16.0 release.

**Comment by pvarga-dni** [comment]
For those ending up here nowadays:

```nu
let-env PROMPT_COMMAND_RIGHT = '' # ...to hide the right prompt, for example. Or:
let-env PROMPT_COMMAND = { your | awesome | prompt } # ...where "your awesome prompt" can be any series of commands
```

**Comment by gadzhi-m** [comment]
Hello. How can I change the path in the prompt line from full path (/home/user) to tilde (~)?
