### ISSUE TITLE
Starship config is ignored in 0.32.0.

### ISSUE THREAD

**Issue by ryanpcmcquen** [nushell/nushell#3576]
**Describe the bug**
My `starship.toml` is no longer picked up.

**To Reproduce**
1. Have a `~/.config/starship.toml`.
2. See that settings are ignored.

**Expected behavior**
Settings would be read as they were before.

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
❯ version | pivot
───┬────────────────────┬─────────────────────────────────────────────────────────────────────
 # │      Column0       │                               Column1
───┼────────────────────┼─────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.32.0
 1 │ build_os           │ macos-x86_64
 2 │ rust_version       │ rustc 1.51.0
 3 │ cargo_version      │ cargo 1.51.0
 4 │ pkg_version        │ 0.32.0
 5 │ build_time         │ 2021-06-01 21:00:59
 6 │ build_rust_channel │ release
 7 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, ptree, rustyline,
   │                    │ term, trash, uuid, which, zip
───┴────────────────────┴─────────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**
Here are the contents of `starship.toml`:
```
add_newline = true

[character]
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold green)"
vicmd_symbol = "[λ](bold yellow)"
```

The prompt character is not changing.

**Comment by ryanpcmcquen** [comment]
I also tried adding `STARSHIP_PROMPT = "~/.starship/config.toml"` under `[env]` in `config.toml`, but it doesn't seem to help.

**Comment by jonathandturner** [comment]
@ryanpcmcquen if you run starship by itself by calling something like `starship prompt` does it look correct there? If it looks correct when you run it by itself but doesn't look correct in nushell, yeah that definitely sounds like an issue

**Comment by ryanpcmcquen** [comment]
I found the issue! Now that `~` correctly maps to the HOME directory, I had to remove the `HOME` declaration I had in `[env]`:

```
HOME = "~/"
```

That was causing the issue, and the prompt is now being read correctly!
