### ISSUE TITLE
path is lost? from within nu.exe running inside of nu.exe

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#3587]
**Describe the bug**
If i'm running nushell and I type `nu.exe` it launched another nushell. The odd thing is that it stops finding things that are in my path.

**To Reproduce**
1. run nu
2. run nu
3. look for error messages

**Expected behavior**
Just work

**Screenshots**
![image](https://user-images.githubusercontent.com/343840/121417912-0a19ac80-c930-11eb-9a43-aaf770dba48b.png)

ok, so where is `zoxide` then?
![image](https://user-images.githubusercontent.com/343840/121418006-20c00380-c930-11eb-8813-c1d776d590f8.png)

It's actually in here which is in my path
![image](https://user-images.githubusercontent.com/343840/121418073-32091000-c930-11eb-92a1-d1ff2e28412e.png)

also, note that items in my `config.toml` path are doubly added to my `$nu.path` in the inner nushell.
![image](https://user-images.githubusercontent.com/343840/121418445-93c97a00-c930-11eb-9be9-79c3a8b942d6.png)

i wonder if there's some case sensitive nonsense going on? my path has `C:\Users\dschroeder\.cargo\bin` but `which` returns `C:\users\dschroeder\.cargo\bin\zoxide.EXE`

|key|value|
|-|-|
|version|0.32.1|
|branch|main|
|short_commit|5ec226a4|
|commit_hash|'5ec226a4161449bea74fbf9c84f75ae87ee00cff'|
|commit_date|2021-06-08 16:14:38|
|build_os|windows-x86_64|
|rust_version|rustc 1.52.1 (9bc8c42bb 2021-05-09)|
|rust_channel|stable (default)|
|cargo_version|cargo 1.52.0 (69767412a 2021-04-21)|
|pkg_version|0.32.1|
|build_time|2021-06-08 16:18:51|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, default, directories, dirs, ptree, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by ueXIMcWizBrdyVEciAlSwxP8aaXP70mO** [comment]
It looks like this is because paths added through `config.toml` are re-added every time a new nushell instance is created. The relevant snippet is here:

https://github.com/nushell/nushell/blob/a8f6a132399ba0bc4348e06812b02bdd63c602fb/crates/nu-engine/src/evaluation_context.rs#L207-L233

**Comment by fdncred** [comment]
it's doubling the paths configured in the config.toml. the previously existing path entries are still there. the rest of the mystery is why things in the path don't work after running nu inside of nu.

**Comment by ueXIMcWizBrdyVEciAlSwxP8aaXP70mO** [comment]
I have to make a revision to my previous comment. It looks like there is a check to make sure duplicates are not added: https://github.com/nushell/nushell/blob/0.32.0/crates/nu-engine/src/evaluation_context.rs#L183

Could the problem have something to do with the "actual" path being `C:\Users\...` and the configured path being `C:\users\...`?

I cannot reproduce this issue on my end, so my apologies about any misjudgments.

**Comment by fdncred** [comment]
Ya, that's what I think too.

**Comment by fdncred** [comment]
oh, i think this is fixed. i can't reproduce it any longer! yay!
