### ISSUE TITLE
Path with tilde tab-completes differently on Linux vs Windows

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#3591]
**Describe the bug**
On Linux `~/Down<Tab>` completes to `~/Downloads` while on Windows, `~\Down<Tab>` expands into the absolute path. Not a big deal but is a bit inconsistent.

**Expected behavior**
I think both should expand to `~/Downloads`. The absolute path can be obtained via `path expand`

**Configuration (please complete the following information):**

```
> version | pivot
────┬────────────────────┬────────────────────────────────────────────────────────────────
 #  │      Column0       │                            Column1
────┼────────────────────┼────────────────────────────────────────────────────────────────
  0 │ version            │ 0.32.1
  1 │ branch             │ main
  2 │ short_commit       │ 2e968d25
  3 │ commit_hash        │ 2e968d25571f5ccb6cfa9caeea91395328a9b97b
  4 │ commit_date        │ 2021-06-08 10:48:02
  5 │ build_os           │ linux-x86_64
  6 │ rust_version       │ rustc 1.52.1 (9bc8c42bb 2021-05-09)
  7 │ rust_channel       │ stable-x86_64-unknown-linux-gnu (default)
  8 │ cargo_version      │ cargo 1.52.0 (69767412a 2021-04-21)
  9 │ pkg_version        │ 0.32.1
 10 │ build_time         │ 2021-06-08 21:33:19
 11 │ build_rust_channel │ release
 12 │ features           │ ctrlc, default, directories, dirs, rustyline, term, which, zip
 13 │ installed_plugins  │ fetch, match, post, ps, sys
────┴────────────────────┴────────────────────────────────────────────────────────────────
```

**Comment by jonathandturner** [comment]
@kubouch when I do a tab complete in Windows for `~/Down` I get `~\Downloads`. Is this what you mean?

**Comment by kubouch** [comment]
@jonathandturner Yes, I meant '~\Down<Tab>`. I just turned off my Windows but I think it resolved into absolute path.

**Comment by kubouch** [comment]
Might be another but that you get two different results with the two separators.

**Comment by NiklasJonsson** [comment]
On 0.33 I get:
```
ls ~/Down[Tab] -> ~\Downloads\
ls ~\Down[Tab] -> ~\Downloads\
```
Haven't tested any others.

**Comment by jonathandturner** [comment]
The way it works in 0.33 as @NiklasJonsson mentions seems to be good. Closing, but please reopen if there are other cases that need updating.
