### ISSUE TITLE
`autoview` should also print the table headers at the end for long tables

### ISSUE THREAD

**Issue by oberien** [nushell/nushell#3592]
When I have a long table, e.g. the output of `ps`, I need to scroll up a few hundred lines to find out which columns are available. It would be helpful if the table headers are also printed at the end of the table. Maybe it could be added to the end of a table if there are more than 25 or so lines.

**Comment by kubouch** [comment]
We could check the table pager (behind `table-pager` feature) and use the same logic to decide the threshold.

**Comment by hustcer** [comment]
It's already supported on latest main branch, I will close it, and related issue: https://github.com/nushell/nushell/issues/4158
