### ISSUE TITLE
PermissionDenied when closing nu in /

### ISSUE THREAD

**Issue by bmalehorn** [nushell/nushell#360]
It looks like `nu` attempts to dump history.txt into the cwd when the shell is closed. This crashes if you don't have write permissions to the current directory.
 
```
/home/brian/nushell(master)> cd /
/>
CTRL-D
Error: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
```

**Comment by jonathandturner** [comment]
Confirmed. I can repro it here, too.

Thanks for the report

**Comment by jonathandturner** [comment]
I'm going to close this issue since the root cause was fixed. We have another issue for a better location for the history file (#100) that caused the panic, so we can do the rest of the work on that issue.
