### ISSUE TITLE
Make Windows binaries available for download

### ISSUE THREAD

**Issue by cool-RR** [nushell/nushell#361]
This will be helpful for the people who are interested enough to download and try something new, but not interested in installing dependencies and figuring out how to compile.

**Comment by razpeitia** [comment]
There is a download for windows, https://github.com/nushell/nushell/releases/download/0.2.0/nu_0_2_0_windows.zip
but it lacks of the `nu.exe`. But I have compiled mine on windows 10 64 bits if you want to give it a try.
[nu.zip](https://github.com/nushell/nushell/files/3536926/nu.zip)

**Comment by cool-RR** [comment]
Thank you!

**Comment by cool-RR** [comment]
I get this error:

```
---------------------------
nu.exe - Entry Point Not Found
---------------------------
The procedure entry point CreateFile2 could not be located in the dynamic
link library KERNEL32.dll.
---------------------------
OK
---------------------------
```

**Comment by razpeitia** [comment]
Well, at least we tried.

**Comment by jonathandturner** [comment]
@cool-RR - what version of Windows are you running?

**Comment by cool-RR** [comment]
Windows 7 ultimate, though I'd like it to work on my Windows 10 machine too.

**Comment by jonathandturner** [comment]
I think the issue @razpeitia pointed out is one of the big ones, I forgot to put nu.exe in the zip!  Oops.

I've updated the zip with nu.exe. Not sure if it will work on Windows 7 (I use Windows 10), but it's worth a try.

**Comment by cool-RR** [comment]
Still fails on Windows 7 with the same error message.

Separately, why is the binary hidden? It's not mentioned in the Installation part of the readme, or the Installation section of the Nu book. It should be one of the first things that a person sees when they come across your project.

**Comment by Kissaki** [comment]
I’m running it just fine on Windows 10.

**Comment by jonathandturner** [comment]
@cool-RR - will file an issue to update them

**Comment by reignmaker** [comment]
I have the same error @cool-RR has
`The procedure entry point CreateFile2 could not be located in the dynamic
link library KERNEL32.dll.`

Windows 7

**Comment by jonathandturner** [comment]
I don't think we have an easy way to support Windows 7. I'll close this issue, but we can track Windows 7 support as a separate issue as it may require other changes.
