### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by craig123456** [nushell/nushell#3610]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by craig123456** [comment]
[]()[]()@craig123456

**Comment by craig123456** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> 
[]()
- 40741

**Comment by jonathandturner** [comment]
@craig123456 looks like you opened this by accident? If not, you can create a new issue. When you do, be sure to fill in the data in the original issue description.
