### ISSUE TITLE
Path containing tilde and backward slash doesn't work on windows (0.32)

### ISSUE THREAD

**Issue by NiklasJonsson** [nushell/nushell#3616]
**Describe the bug**
As of 0.32, nushell fails to expand paths starting with ~ and containing \

**To Reproduce**
1. `echo "x" | save ~/tmp.txt`
2. `ls ~\tmp.txt`

**Expected behavior**
`ls ~/tmp.txt` outputs:
```
───┬───────────────────────────┬──────┬──────┬────────────
 # │           name            │ type │ size │  modified
───┼───────────────────────────┼──────┼──────┼────────────
 0 │ C:\Users\njonsson\tmp.txt │ File │  1 B │ 7 secs ago
───┴───────────────────────────┴──────┴──────┴────────────
```
but `ls ~\tmp.txt` fails with
```
error: No matches found
    ┌─ shell:137:4
    │
137 │ ls ~\tmp.txt
    │    ^^^^^^^^^ no matches found

```

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
───┬────────────────────┬────────────────────────────────────────────────────────────────
 # │      Column0       │                            Column1
───┼────────────────────┼────────────────────────────────────────────────────────────────
 0 │ version            │ 0.32.0
 1 │ build_os           │ windows-x86_64
 2 │ rust_version       │ rustc 1.54.0-nightly (5c0292654 2021-05-11)
 3 │ rust_channel       │ nightly-x86_64-pc-windows-msvc (default)
 4 │ cargo_version      │ cargo 1.54.0-nightly (e51522ab3 2021-05-07)
 5 │ pkg_version        │ 0.32.0
 6 │ build_time         │ 2021-06-02 16:17:54
 7 │ build_rust_channel │ release
 8 │ features           │ ctrlc, default, directories, dirs, rustyline, term, which, zip
───┴────────────────────┴────────────────────────────────────────────────────────────────
```
This happens for non-nushell binaries as well:
```
vim ~/tmp.txt # works
vim ~\tmp.txt # fails
```

**Comment by NiklasJonsson** [comment]
`path expand` seems to behave differently as well:
```
$ echo ~/tmp.txt
~/tmp.txt
$ echo ~\tmp.txt
~\tmp.txt
$ echo ~/tmp.txt | path expand
C:\Users\njonsson\tmp.txt
$ echo ~\tmp.txt | path expand
~\tmp.txt
```

**Comment by kubouch** [comment]
On the latest main branch, `echo ~\tmp.txt | path expand` works for me but the commands do not pick it up.

Interestingly, autocompletion works (also fixed on latest main) but the commands complain. #3605 seems to be related to this one.

**Comment by NiklasJonsson** [comment]
I looked into this a bit and the code that is responsible is https://github.com/nushell/nushell/blob/main/crates/nu-parser/src/path.rs#L85 which uses `shellexpand` which does not seem to support windows style paths, `~\`. There is an open MR from february (!) to add it https://github.com/netvl/shellexpand/pull/13 but as it's been open for such a long time, it seems that it is not too likely to be merged in soon. I'm also seeing a bit of shell expansion code spread out in differerent locations:
```
crates\nu-cli\src\completion\path.rs
crates\nu-engine\src\filesystem\path.rs
crates\nu-parser\src\path.rs
crates\nu-command\src\commands\classified\external.rs
```
Although it is not a lot of code, it seems to me like it makes sense to move all path-expansion to common location so that it's handled uniformly across the project. I'm not sure if the best place to put it is inside `nu-parse` (which has the least deps and kind of makes sense) or just create a new crate `nu-fs`/`nu-path`. I'll start experimenting with the former atleast.

**Comment by kubouch** [comment]
@NiklasJonsson Thanks for looking into it! We were actually wondering the same thing. The path expansion is kind of scattered around all over the place. Ideally, we should get rid of the `shellexpand` crate and have our own logic in one place.

We have most of the path expansion stuff in `nu-engine::filesystem::path` already, I would suggest starting there. It just needs to be adapted to also work with strings (to be usable in the parser). Then, we could also add features missing from `shellexpand`, namely the `~\` expansion in Windows and `~name` expansion. It can be moved from engine somewhere else but I'm not sure if it warrants having its own crate, we'd need to think about it. For now, I think the engine is fine and I think it doesn't really fit into the parser.

If you're interested in working on this, I already investigated these issues and planned to do this myself, so we can chat further if you need some help -- either here or maybe Discord is more suitable.

**Comment by NiklasJonsson** [comment]
Yeah, the logic in `nu-engine` seems to be more fleshed out. I suggested to put the common code in `nu-parser` because `nu-engine` already depens on `nu-parser`. Not sure if we can add a dep the other way? We can continue on discord.
