### ISSUE TITLE
echo commands inside script don't output newline

### ISSUE THREAD

**Issue by NiklasJonsson** [nushell/nushell#3620]
**Describe the bug**
An echo command with a single word as arg inside a `def` doesn't output a newline after the word

**To Reproduce**
1. Create file `test.nu` with
```
def mycmd [] {
  echo test
  echo test2
}
```
2. `source test.nu`
3. `mycmd` outputs:
```
testtest2
```

**Expected behavior**
Expected output
```
test
test2
```

**Configuration (please complete the following information):**

```
> version | pivot
 #  │      Column0       │                            Column1
────┼────────────────────┼────────────────────────────────────────────────────────────────
  0 │ version            │ 0.32.1
  1 │ branch             │ main
  2 │ short_commit       │ ec96e85d
  3 │ commit_hash        │ ec96e85d048eb2667f07f6bd89b02ef91775c154
  4 │ commit_date        │ 2021-06-15 04:34:08
  5 │ build_os           │ windows-x86_64
  6 │ rust_version       │ rustc 1.52.0 (88f19c6da 2021-05-03)
  7 │ rust_channel       │ stable-x86_64-pc-windows-msvc (default)
  8 │ cargo_version      │ cargo 1.52.0 (69767412a 2021-04-21)
  9 │ pkg_version        │ 0.32.1
 10 │ build_time         │ 2021-06-15 20:14:14
 11 │ build_rust_channel │ debug
 12 │ features           │ ctrlc, default, directories, dirs, rustyline, term, which, zip
 13 │ installed_plugins  │ fetch, match, post, ps, sys
────┴────────────────────┴────────────────────────────────────────────────────────────────
```

**Comment by NiklasJonsson** [comment]
Possibly related, with the following file:
```
def ps_echo [] {
    powershell echo 1
    powershell echo 2
}
```
`ps_echo` outputs
```
───┬───
 0 │ 1
 1 │
───┴───

2
```

**Comment by fdncred** [comment]
I believe this is by design. You could do something like this.
```
def mycmd [] {
  $"test(char newline)"
  $"test2(char nl)"
}
```

**Comment by NiklasJonsson** [comment]
So generally, commands are not expected to print newlines? E.g.
```
def cmd [ file ] {
  open $file
  open $file
}
```
 and then `source test.nu` and `cmd test.nu` outputs:
```
def cmd [ file ] {
    open $file
    open $file
}def cmd [ file ] {
    open $file
    open $file
}
```
but if I run (in the prompt):
```
$ open test.nu
$ open test.nu
```
There is a newline after the first output of `open` so that the prompt is on a newline for the second call. My assumption was that each line in a nushell file is executed as I would have executed them one by one in the prompt but maybe I have understood something fundamental?

**Comment by fdncred** [comment]
I agree that there are some inconsistencies that we probably need to fix to make things more intuitive. Thanks for pointing that out.

**Comment by NiklasJonsson** [comment]
I'm glad to help :). I'm switching my everyday scripting from platform-specific bash/powershell with all their weirdness but also hoping get stuff like nice argparsing & syntax as part of it as well. I'm liking nushell alot so far but still figuring things out. Just to add to the discussion, running `nu test.nu`with the file containing:
```
powershell echo 2
powershell echo 3
```
outputs
```
2
3
```
but the file
```
echo 2
echo 3
```
outputs
```
23
```

**Comment by fdncred** [comment]
Ya, `echo` doesn't exactly work like a traditional `echo`. We've been discussing perhaps changing it to something people are more familiar with. Please feel free to jump in an help!

**Comment by NiklasJonsson** [comment]
I would like to contribute but I'm not sure how it's supposed to be working. If a put a list of commands in a function, are they always supposed to output structured data, e.g. tables or lines? Or is it only 'nu' commands that should, e.g. `ls`? Should two `ls` calls in a function:
```
def fn [] {
  ls src
  ls target
}
```
create a single table that is output from the `fn` command or should they be separate as they are now? I guess I'm asking if a function (`def`) is intended to be a list of separate commands or if it is supposed to fit into the nu ideas of pipelines & structured data in some special way?

**Comment by NiklasJonsson** [comment]
As of latest main, the following:
```
def ps_echo [] {
    powershell echo 1
    powershell echo 2
}
```
outputs
```
1
2
```
so that's been fixed. As for builtin echo not outputting newlines, as it is the intended behaviour, I don't see a reason to keep this issue open, so I'll close it.
