### ISSUE TITLE
After ping command shell quit abnormally

### ISSUE THREAD

**Issue by eggcaker** [nushell/nushell#3626]
**Describe the bug**
 press Ctrol-c stop ping command then  the shell exit with code  3221225786

**To Reproduce**
1. Typing `ping xxxxx.com``` 
2. press Ctrl-C to stop the ping command running

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────────
 #  │      Column0       │                                        Column1
────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────────
  0 │ version            │ 0.32.0
  1 │ short_commit       │ 7bf10b98
  2 │ commit_hash        │ 7bf10b980cff5df340c284b0314d9ac19b0c9590
  3 │ commit_date        │ 2021-06-01 08:11:21
  4 │ build_os           │ windows-x86_64
  5 │ rust_version       │ rustc 1.52.1 (9bc8c42bb 2021-05-09)
  6 │ rust_channel       │ stable-x86_64-pc-windows-msvc (default)
  7 │ cargo_version      │ cargo 1.52.0 (69767412a 2021-04-21)
  8 │ pkg_version        │ 0.32.0
  9 │ build_time         │ 2021-06-01 08:29:50
 10 │ build_rust_channel │ release
 11 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, ptree, rustyline, term, trash, uuid,
    │                    │ which, zip
────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**

**Comment by reaganmcf** [comment]
I tested this out on my windows machine, and my `version | pivot` is identical to yours, and attached is the result I am getting. I am unable to reproduce this - what website were you pinging?
![Screen Shot 2021-06-16 at 9 37 14 AM](https://user-images.githubusercontent.com/20019463/122229085-72174800-ce86-11eb-9258-8fddb25ae125.png)

**Comment by eggcaker** [comment]
@reaganmcf  even ping google.com same result 
```
D:\> ping google.com

Pinging google.com [172.217.24.14] with 32 bytes of data:
Reply from 172.217.24.14: bytes=32 time=87ms TTL=57
Reply from 172.217.24.14: bytes=32 time=88ms TTL=57
Reply from 172.217.24.14: bytes=32 time=86ms TTL=57

Ping statistics for 172.217.24.14:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 86ms, Maximum = 88ms, Average = 87ms
Control-C

[process exited with code 3221225786]
```

**Comment by eggcaker** [comment]
Got more information here . seems all shells are same . I guess maybe it's not nushell related issue. close for now.

**Comment by eggcaker** [comment]
based on this issue:  https://github.com/PowerShell/PowerShell/issues/11314  I changed the commmandline param for pwsh , pwsh works . but nu still not working.

**Comment by fdncred** [comment]
is nushell installed via scoop too?

**Comment by eggcaker** [comment]
@fdncred yes

**Comment by eggcaker** [comment]
install the latest version 0.33 with cargo it's working now.
