### ISSUE TITLE
Documentation out of date for "using output of one command inside another"

### ISSUE THREAD

**Issue by matthewhague** [nushell/nushell#3640]
**Describe the bug**

The documentation gives the example

    > stat $(which git).path

for using the output of one command inside another. This does not work in 0.32.0

```
> stat $(which git).path
error: Variable not in scope
  ┌─ shell:1:6
  │
1 │ stat $(which git).path
  │      ^^^^^^^^^^^^ unknown variable: $(which git)
```

Instead

    > stat $"((which git).path)"

seems to be the way to go.

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
 # │      Column0       │                         Column1                          
───┼────────────────────┼──────────────────────────────────────────────────────────
 0 │ version            │ 0.32.0                                                   
 1 │ build_os           │ linux-x86_64                                             
 2 │ rust_version       │ rustc 1.52.1                                             
 3 │ cargo_version      │ cargo 1.52.0                                             
 4 │ pkg_version        │ 0.32.0                                                   
 5 │ build_time         │ 2021-06-17 15:45:25                                      
 6 │ build_rust_channel │ release                                                  
 7 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, ptree, 
   │                    │ rustyline, term, trash, uuid, which, zip   
```

**Comment by jonathandturner** [comment]
@matthewhague - where in the docs did you see the example?

**Comment by jonathandturner** [comment]
Looks like you also found another issue. `stat (which git).path` should also work, but seems like there's a bug there. Will see if we can fix that, too.

**Comment by yourealwaysbe** [comment]
> @matthewhague - where in the docs did you see the example?

Sorry, basic omission from me! It's on the [coming from bash](https://www.nushell.sh/book/coming_from_bash.html) page.

**Comment by jonathandturner** [comment]
Both issues should be fixed now. Thanks for reporting!
