### ISSUE TITLE
Use of ranger in a sequence does not display ranger

### ISSUE THREAD

**Issue by yourealwaysbe** [nushell/nushell#3641]
**Describe the bug**

The ranger documentation suggests to use the following for cd-ing to the current ranger directory on exit

    ranger --choosedir=<myfile>; cd $(cat <myfile>)

That is, ranger writes the current directory to myfile on exit, then the cd changes to that directory.

If i try similar in nushell

    > ranger; cd test

or 

    def rangercd [] {
        ranger
        cd test
    }

then ranger does not display, but waits for input.

Is there a way of specifying that a command should be run in "raw" mode. That is have direct access to stdin/out/err and not produce any structured data?

```
 # │      Column0       │                         Column1                          
───┼────────────────────┼──────────────────────────────────────────────────────────
 0 │ version            │ 0.32.0                                                   
 1 │ build_os           │ linux-x86_64                                             
 2 │ rust_version       │ rustc 1.52.1                                             
 3 │ cargo_version      │ cargo 1.52.0                                             
 4 │ pkg_version        │ 0.32.0                                                   
 5 │ build_time         │ 2021-06-17 15:45:25                                      
 6 │ build_rust_channel │ release                                                  
 7 │ features           │ clipboard-cli, ctrlc, default, directories, dirs, ptree, 
   │                    │ rustyline, term, trash, uuid, which, zip   
```

**Comment by fdncred** [comment]
I'm unfamiliar with `ranger` but it seems like this part isn't being done `cd $(cat <myfile>)` in your custom command or from the command line. Am I misunderstanding the issue?

**Comment by yourealwaysbe** [comment]
Looks like i was a bit wrong, sorry. The `ranger; cd test` crashes ranger. Putting it in a function has no output. I made an [asciinema recording](https://asciinema.org/a/O08fiSTNTsi0I0VbUOi8jHCKa).

**Comment by fdncred** [comment]
can you link me to the ranger repo? it reminds me of `fzf`. maybe something like this would work `cd (ranger)`

**Comment by yourealwaysbe** [comment]
Ranger is [here](https://github.com/ranger/ranger).

Trying `cd (ranger)` has the same behaviour as

    def rr [] {
        ranger
        cd test
    }

in that there is no output from ranger so you can't see what you're doing with it.

**Comment by jonathandturner** [comment]
I tried the same thing with `vim` and get a similar problem.

Both:

```
def rangercd [] {
    vim
    cd test
}
```

and

```
def rangercd [] {
    vim; cd test
}
```

Cause vim to give warnings about output redirection, leaving the shell in a bad state

**Comment by fdncred** [comment]
have you tried this? `ranger --choosedir=<myfile>; cd (cat <myfile>)`? If ranger is writing the output to a file then it seems like we should open that file to get the folder to cd to.

**Comment by yourealwaysbe** [comment]
> have you tried this? `ranger --choosedir=<myfile>; cd (cat <myfile>)`? If ranger is writing the output to a file then it seems like we should open that file to get the folder to cd to.

Thanks. I gave it a go, but ranger still crashed. I think the command after the `;` doesn't really matter too much, it's the behaviour of `;` causing the problem. E.g. both of the following cause crashes

    > ranger; ls
    > vim; ls

I notice also that

    > ls; ls

only outputs the results of the last `ls`. This may be intentional, but it looks like whatever's swallowing the output of the first command is causing the interactive TUI programs (ranger, vim) problems.

**Comment by jonathandturner** [comment]
@yourealwaysbe - I'm working on a PR now that could fix the `ls; ls` thing. It was intentional, but honestly it's just generally confusing, especially if you don't expect it or haven't seen it before.

If we treat `;` to be the same as carriage return, you should see both. I think that'd be less surprising

**Comment by yourealwaysbe** [comment]
Thanks. This seems to work in bd44bcee for me now.

For anyone trying to do like me, here's how i'm aliasing it in my `.config/nu/config.toml` (it took a bit of playing to figure it out! -- and there may be better ways):

```
startup = [
    "def f [] { ranger --choosedir=$HOME/.cache/rangerdir.txt; cd (cat ($'($nu.env.HOME)/.cache/rangerdir.txt')) }",

]
```

Thanks for your work on this project, it's looking good!

**Comment by gegnew** [comment]
Apologies to necropost, but this solution does not appear to work any more, and I'm having trouble figuring out why. If you replace the `cd` command after the `;` with just `cat /path/to/rangerdir`, it prints the dir that ranger wants to drop you into, but the `cd` command doesn't seem to execute
