### ISSUE TITLE
Add a comment command to help when pasting in lines without paths.

### ISSUE THREAD

**Issue by bwinton** [nushell/nushell#3648]
**Is your feature request related to a problem? Please describe.**
When I used bash, my prompt contained `:` at the start, and `;` at the end, so that I could paste entire input lines and the prompt would be ignored, leaving just the command I had copied.

**Describe the solution you'd like**
It would be nice to have a similar ability in nu.

**Describe alternatives you've considered**
I tried using `()`, but the stuff inside isn't a valid command, so that doesn't work so well.
`#` at the start works, but then ignores the entire line.
I also tried `/*` and `*/`, figuring they were kind of the rustiest, but they didn't work.

**Additional context**
It's sort of a low priority request, but I think it might be an interesting feature. I guess it could also help documenting aliases and the prompt in your config.toml, too…

**Comment by fdncred** [comment]
I'm really lost. Maybe a screenshot or two or a little screentogif thing would help?

**Comment by bwinton** [comment]
Does this explain what I'm trying to do a little more?
![prompt-copy](https://user-images.githubusercontent.com/159571/122616456-5d8aa980-d058-11eb-830b-fc2064a4c009.gif)

**Comment by fdncred** [comment]
oh, i may be finally getting it. It seems like `:` is a begin comment marker and `;` is an end comment marker. I didn't know that being mostly on windows. So, you're copying the entire line but everything between the comment markers is ignored, and the rest of the line executes. Do I understand correctly?

**Comment by bwinton** [comment]
Yep! I might phrase it more like `:` is a command that ignores the rest of the arguments and `;` is the regular end-of-statement character, but the result is the same. 🙂

**Comment by fdncred** [comment]
That's an interesting comment but when i want to the last command I just hit up arrow. :)

**Comment by bwinton** [comment]
Yes, the example was intentionally simplistic to demonstrate the behaviour.
For a more common usage, I would be pasting something from a different console, or when I'm logged in to another server, where the up-arrow doesn't work quite as well… 😉

**Comment by bwinton** [comment]
(That did get me thinking, though, and I think I can just add `def : [...rest] {}` and then everything will work the way I expect, so perhaps this doesn't need to be part of the core release… 🤷🏻‍♂️)

**Comment by fdncred** [comment]
true. i haven't tried but maybe that would work.

**Comment by bwinton** [comment]
(It seems to fail if you have stuff in `()`s, but maybe that's not such a painful limitation.)
