### ISSUE TITLE
was $it removed when chaining commands ? 

### ISSUE THREAD

**Issue by midnightexigent** [nushell/nushell#3654]
I am using `nu 0.32`

following the documentation, I tried

`ps  | where name == baz | last | get pid | kill $it`

which yields "unknown variable: $it"

was $it removed ? If yes what's the new way to get the values when pipelining ?

**Comment by kubouch** [comment]
This sounds like "it-expansion" we had earlier. The above used to be a shorthand to `... | each { kill $it }` but was later removed, so you need to write the `each { }` manually. The documentation needs to be updated.

It is a bit awkward when you have just one value (like your example). There were some design ideas how to resolve this but didn't get to implementation yet.

**Comment by appomsk** [comment]
It's not "a bit" awkward. It's just awkward. It was my the  very first thought when I started reading the docs - "why i need `| each { ... }` instead of a simple `| ... `."

**Comment by jonathandturner** [comment]
We've got a few ideas as how to improve this, though they're not yet implemented.

One of them would be to use `$it` to mean the whole stream, which I think lets you do what's in the original post.

Another is a way to refer to parts of the incoming stream. So you could do `%0` to refer to the first item in the stream, `%1` the second, and so on. Then the whole stream might be something like `%` or `%%`.

That'd let you type:

```
ps | where name == baz | last | get pid | kill %
```

**Comment by appomsk** [comment]
Awk-like option with %, %0..., etc. is good one. Just an opinion.

**Comment by midnightexigent** [comment]
Since I get the idea that this is still being discussed and in early stages, here's another idea

New command: `as` 

Takes a stream and a parameter `name`. Brings into scope a variable called `name` whose value is the stream 

Examples

`echo "hello" | as v | echo $v`

`ps | where name == baz | last | as target | kill $target.pid`

**Comment by jonathandturner** [comment]
This is now part of 0.33 and later as `$in`. Closing for now, as the feature is implemented, but we'd like to get feedback about how it works in practice.
