### ISSUE TITLE
config set removes comments in the configuration file

### ISSUE THREAD

**Issue by gutenye** [nushell/nushell#3657]
**Describe the bug**

After running `config set`, all comments in the configuration file are lost. Comments can help us better understanding the configuration file

**To Reproduce**
1. vi (config path)
2. add some comments
3. open a new shell
4. config set a 1
5. all comments in the config file are lost

**Expected behavior**

Comments are kept

**Comment by fdncred** [comment]
Yup, I don't like it either. We need to switch to the `toml-edit` crate but we just haven't yet. Sorry.

**Comment by hustcer** [comment]
No more `config.toml` use `config.nu` instead on the latest main, so I will close this.
