### ISSUE TITLE
notion: web-based interface for nushell

### ISSUE THREAD

**Issue by RichMorin** [nushell/nushell#3663]
I'd like to propose adding a web-based interface to nushell. Although there are other ways this could be useful, my primary motivation is improving accessibility for blind and visually impaired users.

By way of explanation, consider the way that nushell formats tables using monospace characters. This works fine for sighted users, but is completely useless for blind ones. However, if the tables were formatted using HTML, any screen reader could let a blind user navigate the table in two dimensions.

I suspect that there are also opportunities for adding useful menus and other widgets, but I won't try to predict what they might be.

-r

**Comment by fdncred** [comment]
Sounds cool. This was one of our first attempts at such a thing although it doesn't tick all the boxes you mention. https://www.nushell.sh/demo/

**Comment by RichMorin** [comment]
That seems like a great start. It might benefit from having some semantic HTML tags added for navigation and such, but it's very much in the right direction. It might be nice to fiddle with the layout to make it easier for a blind person to use. FWIW, I know several blind techies who could try things out, make suggestions, etc.

**Comment by jonathandturner** [comment]
@RichMorin we'd definitely welcome the help, and we'd be happy to improve the html output or take PRs to improve the output.
