### ISSUE TITLE
Feature Request: Cycle through autocomplete options

### ISSUE THREAD

**Issue by nathom** [nushell/nushell#3679]
In `zsh` you can cycle through the autocomplete options by repeatedly hitting tab. It would be nice to have something similar in nu.

Screengrab of zsh feature:
https://user-images.githubusercontent.com/74019033/123303827-1460ac80-d4d3-11eb-810a-c4336584b34c.mov

I'd be willing to implement it if someone can point me in the right direction. Thanks.

**Comment by jonathandturner** [comment]
@nathom - the current implementation for this comes from rustyline (https://github.com/kkawakam/rustyline)

**Comment by fdncred** [comment]
@nathom, we're in the process exploring & creating an using a different line editor called [reedline](https://github.com/nushell/reedline). Please give it a try and let us know, in that repo, if it works. Alternatively, if it doesn't work, feel free to jump in and help with it.
