### ISSUE TITLE
Nushell shadows /usr/bin/open on Mac

### ISSUE THREAD

**Issue by nightscape** [nushell/nushell#3685]
**Describe the bug**
- Mac has a script `/usr/bin/open` that is used for opening files, directories, etc.
- Nushell provides an `open` command which shadows the former.
- Many programs rely on `open` being the Mac-native one (e.g. Emacs)
- When using Nushell as a login shell (which is awesome), these programs break.

**To Reproduce**
1. Buy a Mac 😉 
2. Setup Nushell as login shell
3. Install Emacs
4. Open an org-mode file and try to `org-export-dispatch` -> `Export to HTML` -> `As HTML file and open`

**Expected behavior**
`/usr/bin/open` gets used to open the resulting file in a browser.

**Actual behavior**
The file doesn't open and Emacs displays an error like this:
```
Command /usr/local/bin/nu -c open ~/test.html: exited abnormally with code 1.
```

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
❯ version | pivot
───┬────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                                                                 Column1
───┼────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.33.0
 1 │ build_os           │ macos-x86_64
 2 │ rust_version       │ rustc 1.53.0
 3 │ cargo_version      │ cargo 1.53.0
 4 │ pkg_version        │ 0.33.0
 5 │ build_time         │ 2021-06-23 00:20:02
 6 │ build_rust_channel │ release
 7 │ features           │ clipboard-cli, ctrlc, default, ptree, rustyline, term, trash, uuid, which, zip
 8 │ installed_plugins  │ binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath
───┴────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**
This is somewhat related to https://github.com/nushell/nushell/issues/2822 and https://github.com/nushell/nushell/issues/2188.
It would be nice to be able to work around this and maybe describe the workaround in https://www.nushell.sh/book/configuration.html#configuring-nu-as-a-login-shell

**Comment by ueXIMcWizBrdyVEciAlSwxP8aaXP70mO** [comment]
I do not have a Mac, so this may or may not work for you. However, I tried to simulate an environment with an ambient open command with a placeholder `open` command in my path:
```
#! /bin/sh
vi ${@}
```
Simply adding `alias open = ^open` uses the system `open` rather than `nu`'s open. You can re-map `nu`'s open with `alias nuopen = open`.

**Comment by nightscape** [comment]
Great tip @ueXIMcWizBrdyVEciAlSwxP8aaXP70mO! Added a PR to document this.
Thank you!
