### ISSUE TITLE
README should show syntax to escape to regular OS command (/bin/ls etc)

### ISSUE THREAD

**Issue by paul-hammant** [nushell/nushell#369]
Like is is back-tick, or a full-qualified path to? 

Where there's no match for nushell, is it a fall-through?

This for the README, I think

**Comment by coolshaurya** [comment]
You put a caret `^` in front of the command. So to use the system's `ls` command you do `^ls`

example -

```sh
> ls
───┬────────────────────────────┬──────┬───────┬─────────────
 # │ name                       │ type │ size  │ modified 
───┼────────────────────────────┼──────┼───────┼─────────────
 0 │ abaracadabra.txt           │ File │ 401 B │ 1 month ago 
 1 │ coww.txt                   │ File │  24 B │ 1 month ago 
 2 │ randomweirdstuff.txt       │ File │ 197 B │ 1 month ago 
 3 │ youshouldeatmorecereal.txt │ File │ 768 B │ 1 month ago 
 4 │ zebrasarecrazy.txt         │ File │ 556 B │ 1 month ago 
───┴────────────────────────────┴──────┴───────┴─────────────

> ^ls
abaracadabra.txt  coww.txt  randomweirdstuff.txt  youshouldeatmorecereal.txt  zebrasarecrazy.txt
```

**Comment by thegedge** [comment]
@paul-hammant This is mentioned in the book (here: https://www.nushell.sh/book/en/escaping.html).

I think the question to answer is: should we move everything into the book and have the README be a little more bare. I'm thinking yes, but if not, this does seem like a good thing to call out in the README.

**Comment by paul-hammant** [comment]
Your choice.

**Comment by thegedge** [comment]
Looks like the README has been made far more lean that what I recall, so I think we're pushing more and more into the book (which is also translated). I think that's the better choice 🙂
