### ISSUE TITLE
Starship prompt + enter file

### ISSUE THREAD

**Issue by jimmiebfulton** [nushell/nushell#3695]
**Describe the bug**
I have set my prompt to "starship prompt".

If I 'enter' a file (Ex: `enter Cargo.toml`), and cd into a section, I get an error:

```
error: No such file or directory (os error 2)
  ┌─ shell:1:1
  │
1 │ starship prompt
  │ ^^^^^^^^ failed to spawn
```

It appears that my path is not respected when I'm 'entered' into a file and a command on my path is used as my prompt.

**To Reproduce**
1. Set the prompt to "starship prompt"
2. enter Cargo.toml
3. cd package

**Expected behavior**
I should be able to have a prompt that works when I'm browsing the file system, or a file.  Perhaps when browsing a file, custom prompts are disabled?

```
> version | pivot
```
│ 0 │ version            │ 0.33.0                                      │
│ 1 │ build_os           │ macos-x86_64                                │
│ 2 │ rust_version       │ rustc 1.53.0-nightly (42816d61e 2021-04-24) │
│ 3 │ rust_channel       │ stable-x86_64-apple-darwin (default)        │
│ 4 │ cargo_version      │ cargo 1.53.0-nightly (0ed318d18 2021-04-23) │
│ 5 │ pkg_version        │ 0.33.0                                      │
│ 6 │ build_time         │ 2021-06-25 21:03:51                         │
│ 7 │ build_rust_channel │ release                                     │
│ 8 │ features           │ ctrlc, default, rustyline, term, which, zip │
│ 9 │ installed_plugins  │ fetch, match, post, ps, sys                 │
```

**Comment by ueXIMcWizBrdyVEciAlSwxP8aaXP70mO** [comment]
Value shells break anything reliant on the host file system because they overwrite the notion of paths: https://github.com/nushell/nushell/blob/03c9eaf005a828381665a67e09bf09b2d8dbea89/crates/nu-engine/src/shell/value_shell.rs#L34-L37

**Comment by jimmiebfulton** [comment]
> Value shells break anything reliant on the host file system because they overwrite the notion of paths:
> 
> https://github.com/nushell/nushell/blob/03c9eaf005a828381665a67e09bf09b2d8dbea89/crates/nu-engine/src/shell/value_shell.rs#L34-L38
> 
> It is not immediately clear to me how best to solve this. Escaping to the system with `^` in front `prompt` executables does not resolve the issue either.

I can see how this might be tricky.  

One approach is that only builtins work on ValueShells.  All non-builtins would get executed by a regular shell.  However, it might not makes sense to execute arbitrary external commands in a ValueShell.

Perhaps the only external command that might make any sense in a ValueShell is a custom prompt, in which it could be special cased.  That said, does a custom prompt even make sense in a ValueShell.  Probably not.  In which case, it may make sense to use the built-in prompt for ValueShells, and a custom shell can be use for path shells.

Here's a possible approach: Each Shell type would have it's own optional prompt customizations.  When you set the standard shell's custom prompt, that only applies to that shell type.  The value shell prompt would keep it's default.  If someone wanted to customize their value shell prompt, they would have to specifically opt in to do doing so, and it may very well look different than the standard shell's prompt.  And unlikely that something like Starship could even be used, as it has no notion of ValueShells.

**Comment by jntrnr** [comment]
I don't think we have a way currently to have starship interact with a value shell. Keeping open so we can circle back to it.

**Comment by fellnerse** [comment]
Then you should at least mention this in the section in the [cookbook](https://www.nushell.sh/book/configuration.html#prompt-configuration)

**Comment by fdncred** [comment]
nushell doesn't support 'value shells' any longer so one cannot enter a file on the 0.59.1.
