### ISSUE TITLE
Good idea to embed Luajit?

### ISSUE THREAD

**Issue by ck3d** [nushell/nushell#3698]
I think about a using Nushell as a replacement to Bash to build computation pipelines with less overhead to combine

1. Classic GNU tools,
2. Nushell builtins, and
3. Lua Scripts executed by Luajit

I need your opinion about following question:

Is it worth or a good idea to embed Luajit into Nushell, similar to Pandoc and NVim? I want to avoid process forks of luajit and serialization processing.

I can spend time to implement this feature, if it fits your roadmap.

**Comment by jonathandturner** [comment]
@ck3d - what are some of the things you'd like to use luajit for in nushell?

While Nushell is its own language, it can definitely learn from other languages where they do something better.

**Comment by ck3d** [comment]
My wish is to chain existing Lua functions in a performant way between Nushell pipes.

If Lua is embedded in Nushell, then I could simply add e.g. sha256 into Nushell without forking and recompile the project.

**Comment by jonathandturner** [comment]
We support writing plugins now, which could let you access sha256 without building nushell. The plugin chapter of the contributor book shows how to write one in Rust and Python, which might give you some ideas:

https://www.nushell.sh/contributor-book/plugins.html

**Comment by ck3d** [comment]
Thanks, I will give it a try.
