### ISSUE TITLE
Nu breaks X11 login

### ISSUE THREAD

**Issue by tacerus** [nushell/nushell#3699]
**Describe the bug**
Having `nu` set as the users default shell, X11 no longer allows logging in to the account, providing the message `Login for <user> is disabled`. Only upon forcefully resetting the login shell to i.e. `bash` using `usermod` GUI access to the system can be regained. This has been observed with X11 based KDE Plasma on openSUSE Tumblweed.

**To Reproduce**
1. Change the login shell to `/home/<user>/.cargo/bin/nu` using `usermod -s` (using `chsh -s` does not work, as it reports `nu` is not a valid shell - maybe this should have been an indicator for me not to do it in the first place, but still).
2. Reboot the system.
3. Attempt to log in using the logon manager.

**Expected behavior**
The system should allow me to log in and fully utilize X11 with `nu` being the logon shell.

**Configuration (please complete the following information):**

openSUSE Tumbleweed, latest updates as of 27/06/2021

```
 0 │ version            │ 0.32.0                                                         
 1 │ build_os           │ linux-x86_64                                                   
 2 │ rust_version       │ rustc 1.52.1                                                   
 3 │ cargo_version      │ cargo 1.52.0                                                   
 4 │ pkg_version        │ 0.32.0                                                         
 5 │ build_time         │ 2021-06-14 23:22:37                                            
 6 │ build_rust_channel │ release                                                        
 7 │ features           │ ctrlc, default, directories, dirs, rustyline, term, which, zip 
```

**Add any other context about the problem here.**
`chsh -s` not allowing `nu` to be set as the default shell might be related.

**Comment by Username404-59** [comment]
I have the same issue on openSUSE Tumbleweed with the Budgie desktop

**Comment by ueXIMcWizBrdyVEciAlSwxP8aaXP70mO** [comment]
This forum post suggests that the solution is to add the `nu` binary to `/etc/shells`: https://www.linuxquestions.org/questions/suse-opensuse-60/xsession-login-for-user-is-disabled-611855/

**Comment by Username404-59** [comment]
This is the script that is meant to add nu to /etc/shells; I think it may not be present in the packages of openSUSE?

**Comment by tacerus** [comment]
Interesting - didn't realize there was a script for it.

If I remember correctly, I installed it through cargo. Is it supposed to be executed along with a cargo install as well? I assume if the cargo install happens on a user level, it won't be able to, so maybe it should print a post-install notification to the user, informing them to run the /etc/shell hook manually as root.

**Comment by hustcer** [comment]
@tacerus Can you try it with nu v0.63 ? This should work now

**Comment by rgwood** [comment]
Closing as we believe this is fixed now. Happy to reopen if someone is still experiencing this.
