### ISSUE TITLE
Nushell lexing/parsing improvements

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#3700]
**Is your feature request related to a problem? Please describe.**
Some possible improvements to lexing and parsing in Nushell.

**Describe the solution you'd like**
In thinking through parsing and lexing this morning, I realised we can improve how we do it in the future. The key is that Nushell cares specifically about whitespace (and, as we'll see, other characters that pretend to be whitespace).

## Summary

We can cut down on heap allocations by using liberal use of [string interning](https://en.wikipedia.org/wiki/String_interning) and reduce our amount of extra parsing by leaning on our ASCII-based separators as the token delimiters rather than decoding/encoding Strings as UTF-8.

## Lexing

Because of this focus on whitespace as how we separate tokens, we actually can remove all the utf-8 logic we have. Instead, we can work in spans of bytes. We already do this with Span, but here, imagine that what the lexer gives you in something like this:

=input=
```
# foo.nu
def foo [] { 3 }
```

=output=
```
// assume foo.nu is stored as id 1
enum TokenKind {
  Bare,
  Quote,
  List,
  Block,
}
vec![
  Token { kind: Bare, span: Span { id: 1, start: 0, end: 3 } },
  Token { kind: Bare, span: Span { id: 1, start: 4, end: 7 } },
  Token { kind: List, span: Span { id: 1, start: 8, end: 10 } },
  Token { kind: Block, span: Span { id: 1, start: 11, end: 16 } },
]
```
Basically we read in the file contents as bytes, or as a String that we immediately treat as bytes, and then from there we only care about the spans of those bytes. The file contents are stored ([interned](https://en.wikipedia.org/wiki/String_interning)), so we can refer to the original source file using an id.

The nice thing about this approach is that we really don't do any heap allocation of String data. We only refer to the spans inside the string, and fetch out the contents when needed.

Taking this a step further, we could intern bare words also, so that we're not having to do name lookups using string comparison, but instead could use the id.

## Parsing

Once lexed, the tokens we have give us windows into the original source. This lets us still use the same recursive parse we use today where parsing can handle a block as a string or can expand it by lexing and parsing the contents, letting the expected type in that position drive how the parse runs.

Taking the above example, we'd continue to use the spans:

Let's assume "def" and "foo" where interned as string id's 0 and 1, respectively.

```
Expression::Definition {
  name: String {id: 1, Span {id: 1, start: 4, end: 7 } },
  args: None,
  block: Block {
    Spanned { expr: Expression::Int(3), span: Span { id: 1, start: 13, end: 14 } }
  }
}
```

## ASCII-fying the lexer and why

To accomplish this, I think we need the lexer to be able to split tokens based on a set of parameters that you give it. Currently, it's configurable to either use spaces or to also include newline as a whitespace. We can extend this to include comma as another kind of whitespace (used when handling lists of values).

The lexer would move to handling bytes rather than chars. The current lexer uses CharIndices, but this isn't necessary if we use bytes.

We're allowed to do this because in utf-8, we can be assured that so long as we use ASCII whitespace (and optionally-accepted-as-whitespace, like comma), we are allowed to parse at the byte level, as the encoded UTF-8 char will have a high bit 7 (making it non-ASCII). 

So long as we follow similar lexing logic, we'll lex spans which themselves can be decoded to be valid UTF-8 strings.

**Comment by elferherrera** [comment]
How is the string `interned`? are you planning to use a vector to keep them or the string is going to be stored within the same expression struct?

**Comment by jonathandturner** [comment]
@elferherrera - it'll be interned into a global. For efficiency/correctness, I'm experimenting with a way of splitting set into two parts: the permanent set and the working set, where the working set can be thrown away and redone. We'll need this for when we parse something to know shapes but don't want the state changes (like syntax highlighting and completions).

**Comment by jonathandturner** [comment]
For folks who want to help with the current experiment: https://github.com/jonathandturner/engine-q

**Comment by camblomquist** [comment]
#1134 floats the idea of a formal grammar, which I think is important for any lexer/parser improvements going forward. With a formal grammar, you can just use a parser generator to create the parser. This also makes it clear what is and is not considered valid syntax and what might want to be considered valid but isn't.

**Comment by jntrnr** [comment]
This should be fixed in latest main.

We still need a former grammar, and we can track that with the mentioned issue.
