### ISSUE TITLE
add ci to update winget package

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#3705]
We need our CI pipeline to update the winget package on release. I have no idea how to do it. There may be some documentation [in pkgs repo here](https://github.com/microsoft/winget-pkgs) or [in cli repo here](https://github.com/microsoft/winget-cli) about it.

**Comment by TechWatching** [comment]
See my last PR #3717

**Comment by fdncred** [comment]
yay! thanks! how were you able to test it?

**Comment by TechWatching** [comment]
As said in the PR, I tested on a bumn private repository with a similar job to the one I created in nushell release pipeline to check that the script created a PR in the winget package repository. It works well, it created a PR for 0.33.0 which already exist in the repo so I closed that PR once tested. 

So I did not really test the complete release nushell pipeline as it would involve creating a new release, but as it is almost the same code that I tested it should work fine. I guess we will verify that when 0.34.0 will be released 😁.

**Comment by fdncred** [comment]
Thanks!

**Comment by TechWatching** [comment]
I created a [new PR](https://github.com/nushell/nushell/pull/3819) to solve the issue that occured during last release.

**Comment by fdncred** [comment]
Thanks again. Closing due to https://github.com/nushell/nushell/pull/3819

**Comment by jntrnr** [comment]
Looks like we're getting something: https://github.com/microsoft/winget-pkgs/pull/25824

will we need to check the boxes manually each time?

**Comment by just1a-person** [comment]
> will we need to check the boxes manually each time?

From my experience I didn't have to check those boxes.
