### ISSUE TITLE
Add support for OSC-7 to let terminals know the shell's CWD

### ISSUE THREAD

**Issue by vamolessa** [nushell/nushell#3707]
**Is your feature request related to a problem? Please describe.**
Currently, we *almost* can generate OSC-7 sequence:
`build-string (ansi -o '9;9;') '"' (pwd) '"' (???)`

Where the `(???)` would be the sequence `ESC\`. 
Although the `ansi` lets we create OSC escape sequences, it actively prevents us from creating the escape sequence `ESC\`
which is required for ending the OSC-7 sequence.

For instance, in powershell we can do:
```
$esc = [char]27
echo "$e]9;9;D:$e\"
```
And then the next time I split the terminal view, I'll be in the `D:` directory.

**Describe the solution you'd like**
One easy option is to simply let the `ansi` command generate the sequence `ESC \` like: `ansi -e \`.
It currently gives us the error:
```
error: no need for escape characters
   ┌─ shell:44:9
   │
44 │ ansi -e \
   │         ^ no need for escape characters
```

Another one would be creating a new command like `title` but that generates the sequence
`ESC]9;9;"CWD"ESC\` for us.

**Describe alternatives you've considered**
One alternative would be creating a file with the correct ending sequence bytes (eg `ESC\`) and appending its contents
to the generated sequence like:
`build-string (ansi -o '9;9;') '"' (pwd) '"' (open --raw bytes-sequence.txt)`

**Additional context**
n/a

**Comment by fdncred** [comment]
Have you looked at `ansi --help`? There is a parameter called `--osc` that create this in rust `\x1b]`. Is that what you mean?

**Comment by fdncred** [comment]
1. please help me understand the purpose of osc-7, just for my education
2. let me know what want `ESC\` to be named and i can add it quickly so you can do `ansi <name>` where name is what we think it should be called.

**Comment by vamolessa** [comment]
sure!
1. In most terminals (windows terminal included), if we print the sequence: `ESC]9;9;<path>ESC\`, it notifies it of the shells current directory (see: https://github.com/microsoft/terminal/pull/8330). Then they can provide a feature of spawning a new shell in the same directory as the previous shell, say, in a split window.
2. I think the sequence `ESC\` is called string terminator (`ST`). There's a little bit of information about it in here: https://en.wikipedia.org/wiki/ANSI_escape_code (look for the header `Fe Escape sequences`).

**Comment by fdncred** [comment]
Thanks for the info. Added it here https://github.com/nushell/nushell/pull/3712

**Comment by fdncred** [comment]
Landed the PR - Please reopen if it didn't fix this issue.
