### ISSUE TITLE
`$nothing` should be convertible to empty string

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#3711]
**Describe the bug**
`$nothing | into string` currently yields a "nothing" string. I think it empty string (`""`) represents `$nothing` better than literal "nothing".

**To Reproduce**
1. `$nothing | into string`

**Expected behavior**
Empty string (`""`)

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
  #         Column0                                                                                         Column1
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   0   version              0.33.1
   1   branch               main
   2   short_commit         19c79f0a
   3   commit_hash          19c79f0a735b08489385cbb81e739b0c1b2a7580
   4   commit_date          2021-06-24 21:17:37
   5   build_os             linux-x86_64
   6   rust_version         rustc 1.52.1 (9bc8c42bb 2021-05-09)
   7   rust_channel         stable-x86_64-unknown-linux-gnu (default)
   8   cargo_version        cargo 1.52.0 (69767412a 2021-04-21)
   9   pkg_version          0.33.1
  10   build_time           2021-06-24 22:48:18
  11   build_rust_channel   release
  12   features             clipboard-cli, ctrlc, default, ptree, rustyline, term, trash, uuid, which, zip
  13   installed_plugins    binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath

**Comment by stevenbarragan** [comment]
What are the use cases for this? I find it hard to see how typing `$nothing | into string` is better than just `""`

**Comment by kubouch** [comment]
@stevenbarragan By itself not very useful but for example you can have a function that returns nothing. Also, string interpolation: `$"($nothing)"` expands to empty string which is inconsistent with the current `into string`.

**Comment by jonathandturner** [comment]
A related update: I just added comparison coercion for `$nothing` this morning with #3750. This doesn't do the `into string` step, but may help in other cases.
