### ISSUE TITLE
nushell -c breaks unexpectedly on 0.33

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#3715]
**Describe the bug**

`nushell -c` is supposed to be able to run a proper Nushell script. This used to work fine on earlier versions of Nushell, but seems to be broken in 0.33.

**To Reproduce**
1. Write the following script to `/tmp/foo.nu`:
```
def __zoxide_prompt [] {
    let git = $"(do -i {git rev-parse --abbrev-ref HEAD} | str trim)"
    let git = (if (echo $git | str length) == 0 {
        ""
    } {
        build-string (char lparen) (ansi cb) $git (ansi reset) (char rparen)
    })
    build-string (ansi gb) (pwd) (ansi reset) $git "> "
}
```
2. `nu /tmp/foo` does not return an error.
3. `nu -c "$(cat /tmp/foo)"`

**Expected behavior**

I expected `nu -c $script` to work the same way as `nu $script_file`.

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
───┬────────────────────┬─────────────────────────────────────────────
 # │      Column0       │                   Column1                   
───┼────────────────────┼─────────────────────────────────────────────
 0 │ version            │ 0.33.0                                      
 1 │ build_os           │ linux-x86_64                                
 2 │ rust_version       │ rustc 1.53.0 (Fedora 1.53.0-1.fc34)         
 3 │ cargo_version      │ cargo 1.53.0                                
 4 │ pkg_version        │ 0.33.0                                      
 5 │ build_time         │ 2021-06-22 20:03:41                         
 6 │ build_rust_channel │ release                                     
 7 │ features           │ ctrlc, default, rustyline, term, which, zip 
 8 │ installed_plugins  │ fetch, match, post, ps, sys                 
───┴────────────────────┴─────────────────────────────────────────────
```

**Add any other context about the problem here.**

**Comment by jonathandturner** [comment]
@ajeetdsouza If you use `nu -c "cat /tmp/foo"` instead of `nu -c "$(cat /tmp/foo)"`, does that fix it? We changed the subexpression syntax to no longer use the `$`, so you can also do: `nu -c "(cat /tmp/foo)"`

**Comment by ajeetdsouza** [comment]
@jonathandturner sorry, I should have been clearer.

`nu -c <SCRIPT>` breaks when you pass the following script as an argument:

```
def __zoxide_prompt [] {
    let git = $"(do -i {git rev-parse --abbrev-ref HEAD} | str trim)"
    let git = (if (echo $git | str length) == 0 {
        ""
    } {
        build-string (char lparen) (ansi cb) $git (ansi reset) (char rparen)
    })
    build-string (ansi gb) (pwd) (ansi reset) $git "> "
}
```

Since passing that entire script as a string is not very practical, I wrote it to a file and used command substitution to generate the actual string. In my `bash` shell,

```bash
#!/usr/bin/env bash

# pass the script to `echo`
echo "$(cat /tmp/foo)"

# pass the script to `nushell`
nu -c "$(cat /tmp/foo)"
```

**Comment by jonathandturner** [comment]
When I try it, it looks like bash is including quotes around the whole script. Are you seeing something similar?

```
error: Type Error
  ┌─ shell:1:1
  │  
1 │ ╭ "def __zoxide_prompt [] {
2 │ │     let git = $"(do -i {git rev-parse --abbrev-ref HEAD} | str trim)"
3 │ │     let git = (if (echo $git | str length) == 0 {
4 │ │         ""
  · │
7 │ │     })
8 │ │     build-string (ansi gb) (pwd) (ansi reset) $git ">
  │ ╰─────────────────────────────────────────────────────^ Expected environment variable assignment, found "def __zoxide_prompt [] {
    let git = $"(do -i {git rev-parse --abbrev-ref HEAD} | str trim)"
    let git = (if (echo $git | str length) == 0 {
        ""
    } {
        build-string (char lparen) (ansi cb) $git (ansi reset) (char rparen)
    })
    build-string (ansi gb) (pwd) (ansi reset) $git ">
```

**Comment by ajeetdsouza** [comment]
The quotes are being added by Nushell when displaying the text. The double quotes in `bash` are only there to prevent it from splitting the input using whitespace. If you were doing the same thing with Nushell, it would look like this:

```
#!/usr/bin/env nu

nu -c (cat /tmp/foo)
```

The same error occurs there too.

**Comment by fdncred** [comment]
@ajeetdsouza I just did this and it seems to have worked.
```
#!/usr/bin/env bash

# pass the script to `echo`
echo "$(cat /tmp/foo)"

# pass the script to `nushell`
nu /tmp/foo
```

although i'm not real sure what the point is to this? do you have more context? Is it maybe to test the script in ci or something like that? btw - it seems like `nu -c` should work to me. i'm not sure why it doesn't.

Also, as an alternative approach, i've found that double quotes `"` and single quotes `'` are interchangeable. Some languages like doubles where others behave better with singles. So, this command works in bash with the below script `nu -c "$(cat /tmp/foo)"`

```sh
def __zoxide_prompt [] {
    let git = $'(do -i {git rev-parse --abbrev-ref HEAD} | str trim)'
    let git = (if (echo $git | str length) == 0 {
       ''
    } {
        build-string (char lparen) (ansi cb) $git (ansi reset) (char rparen)
    })
    build-string (ansi gb) (pwd) (ansi reset) $git '> '
}
```

**Comment by ajeetdsouza** [comment]
> Is it maybe to test the script in ci or something like that?

@fdncred  correct. I'm using this in CI to test [zoxide's initialization script](https://github.com/ajeetdsouza/zoxide/blob/b9b0abe4716bf0e6e9bf6d2b8faedd231b648b2d/src/shell.rs#L174). This broke when I upgraded to Nushell 0.33.

Thanks for the suggestion to use single quotes, it seems to have fixed it for now. I'm not sure why double quotes are behaving differently when used directly versus with `nu -c`.

**Comment by fdncred** [comment]
double quotes makes a difference because, like @jntrnr said, bash is already double quoting. so double quotes within double quotes confuses nushell. I'm going to close this now. please reopen if needed.

**Comment by ajeetdsouza** [comment]
@fdncred please reopen. If you look at the test I linked to, I'm actually passing in the script using Rust:

```rust
let source = r#"
def __zoxide_prompt [] {
    let git = $'(do -i {git rev-parse --abbrev-ref HEAD} | str trim)'
    let git = (if (echo $git | str length) == 0 {
       ''
    } {
        build-string (char lparen) (ansi cb) $git (ansi reset) (char rparen)
    })
    build-string (ansi gb) (pwd) (ansi reset) $git '> '
}"#;
Command::new("nu").args(&["-c", source]);
```

Rust is not inserting double quotes here. I was just using Bash because I thought it would be faster to explain that way. You can invoke the same command with Nushell, and Nushell does not insert double quotes either.

**Comment by fdncred** [comment]
oh, it's working with single quotes but you want to leave it open in order to make it work with double quotes? do i understand correctly?

**Comment by ajeetdsouza** [comment]
That's correct. This is not happening because of bash -- it happens however you invoke the `nu` command. The problem is that a script that works with `nu <filename>` doesn't work with `nu -c <contents of file>`, which is an inconsistency.

**Comment by ajeetdsouza** [comment]
Relevant.

**Comment by hustcer** [comment]
The following script run successfully in nu v0.61, I think we can close this issue
```
def __zoxide_prompt [] {
    let git = $"(do -i {git rev-parse --abbrev-ref HEAD} | str trim)"
    let git = (if (echo $git | str length) == 0 {
        ""
    } else {
        build-string (char lparen) (ansi cb) $git (ansi reset) (char rparen)
    })
    build-string (ansi gb) (pwd) (ansi reset) $git "> "
}
```

**Comment by ajeetdsouza** [comment]
True, this can be closed. The quoting issue showed up elsewhere and that has already been fixed.
