### ISSUE TITLE
cd using variable

### ISSUE THREAD

**Issue by lundholmx** [nushell/nushell#3719]
**Is your feature request related to a problem? Please describe.**
It is not an issue per se, but I would like to use cd along with a variable to change directory like so:

```sh
> let p = (zoxide query somedir)
> cd $p
```

But instead I get an error:

```sh
> cd $p
error: Cannot change to directory
   ┌─ shell:42:4
   │
42 │ cd $p
   │    ^^^^^^^ directory not found
```

**Describe the solution you'd like**
I want to be able to use a variable with the cd command.

I'm sorry if this is already supported and I'm missing something obvious.

**Comment by jonathandturner** [comment]
@lundholmx - this should work, you may have to pass the output of `zoxide` through `str trim` to remove the carriage return if it's giving one.

```
let p = (zoxide query somedir | str trim)
cd $p
```

**Comment by lundholmx** [comment]
Thank you! Sorry for the confusion.

**Comment by fdncred** [comment]
With the latest main branch, this will have to be `zoxide query somedir | str trim -c (char newline)` since the new version of trim doesn't trim `\n` by default any longer.
