### ISSUE TITLE
Autocomplete support with shellac

### ISSUE THREAD

**Issue by killercup** [nushell/nushell#372]
Do you have any plans for supporting external auto-completion? The recently [presented](https://www.redox-os.org/news/rsoc-ion-ux-4-5/) shellac language-server-like implementation in the Ion shell seems promising.

**Comment by jonathandturner** [comment]
Thanks for the heads up, will take a look

**Comment by thegedge** [comment]
We're consolidating the completions effort in #290 for now. After we close off that issue, we can open (or reopen) specific issues related to completions.
