### ISSUE TITLE
Can't find `config.toml` if there's an error in `config.toml`

### ISSUE THREAD

**Issue by cadojo** [nushell/nushell#3721]
This issue is related to user stupidity! 

I am new to nushell, and I tried setting a value in `startup` from the command line: `> echo "alias ll = ls -l" | config set_into startup`. __Don't run this command!__ It broke my nushell. 

__Problem:__
If there's an error in your `config.toml`, nushell starts without any knowledge of `config`. Now, when I run `> config path` to see where the file I need to fix is, it gives: `error: Error: No global config found!`

I need some way to figure out where the `config.toml` file is. Even when I remove and re-install nushell, it still gives the same error on startup: `error: Error: expected an array of strings as startup commands`

__Solution:__
The `config.toml` file defaulted _somewhere_. I'm sure the default location is system-dependent. Is there a way to provide some command to figure out where `config.toml` "should be" for your system?

**Comment by ueXIMcWizBrdyVEciAlSwxP8aaXP70mO** [comment]
The default `config.toml` directory is given by [`directories_next::ProjectDirs`](https://docs.rs/directories-next/2.0.0/directories_next/struct.ProjectDirs.html). By platform, these are:

- Unix: `"${XDG_CONFIG_HOME}/nu"`
- Windows: `"%APPDATA%\nushell\nu"`
- Mac: `"${HOME}/Library/Application Support/org.nushell.nu"`

The relevant code is here: https://github.com/nushell/nushell/blob/main/crates/nu-data/src/config.rs#L167

When I tested on Linux, it looks like `nushell` will create a `config.toml` in the directory for your platform if there is not already one present.

**Comment by PranavBhattarai** [comment]
I have a similar situation here in Fedora Workstation 35 as u can see:
![image](https://user-images.githubusercontent.com/32763112/149974398-19cb5165-ef04-4755-b682-352c82d0272f.png)

Everything was working fine. I used Nushell with [Starship](https://starship.rs/) prompt in Alacritty terminal. It was very fast and responsive. Suddenly today I decided to use vanilla Nushell with no other hacks (like starship) from scratch. So I uninstalled nushell, even wiped nu's config folder and file. And then I reinstall nushell.
That's when things started to see error message whenever I launched nushell.

Above _tried_ to use above mentioned solution, but i didn't worked. Am I doing it the right way?!
![image](https://user-images.githubusercontent.com/32763112/149975328-98072df3-b17a-4d85-ad30-a170fc375b96.png)

I do have a directory and a file inside ~/.config/nu folder and it also has config.toml file as you can see:
![image](https://user-images.githubusercontent.com/32763112/149975695-8fa8ade3-ee58-475c-86ac-67fb5b2129ac.png)
But this doesn't get recognized by nushell for some weird reason.

@cadojo help!

**Comment by jntrnr** [comment]
@PranavBhattarai - can you file a new issue for your case?

**Comment by PranavBhattarai** [comment]
@jntrnr Will, it not pollute nushell GitHub issues? Since we have 2 related issues already, it is necessary.

**Comment by jntrnr** [comment]
@PranavBhattarai - since you're commenting on one that's closed, it'd be better to open a new one rather than potentially lose your comment because we are only looking at open issue

**Comment by PranavBhattarai** [comment]
@jntrnr Done #4265
