### ISSUE TITLE
PTY Instability

### ISSUE THREAD

**Issue by dmgolembiowski** [nushell/nushell#3725]
By the way, I'm loving nushell. Thank you for putting so much passion into its design.

**Piping Standard Output to a Foreground PTY Causes Instability**
Undefined behavior happens when trying to use `/dev/stdout` contents, and piping them into a process that readily takes buffered input from `/dev/stdin`.

**To Reproduce**
1. `nu`
2. `ps -l | vim -`

**Expected behavior**
I'm assuming there's supposed to be better handling by me, but it's not clear to me what kinds of pipe-delimited transformations I should use.
Conceivably,  I think there's a possibility to shim the desired behavior by encoding the table into something UTF-8 friendly. But I think I saw approaches similar to this yet they involved `| save ...`, which seemed like it would break the command chain.

**Screenshots**

![Pipes](https://s6.gifyu.com/images/pipe2.gif)

**Configuration (please complete the following information):**
```
───┬────────────────────┬─────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                       Column1                                       
───┼────────────────────┼─────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.33.0                                                                              
 1 │ build_os           │ linux-x86_64                                                                        
 2 │ rust_version       │ rustc 1.54.0-nightly (0a8629bff 2021-06-11)                                         
 3 │ rust_channel       │ nightly-x86_64-unknown-linux-gnu (default)                                          
 4 │ cargo_version      │ cargo 1.54.0-nightly (aa8b09297 2021-06-09)                                         
 5 │ pkg_version        │ 0.33.0                                                                              
 6 │ build_time         │ 2021-07-03 11:45:13                                                                 
 7 │ build_rust_channel │ release                                                                             
 8 │ features           │ clipboard-cli, ctrlc, default, ptree, rustyline, term, trash, uuid, which, zip      
 9 │ installed_plugins  │ binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match,       
   │                    │ post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, 
   │                    │ xpath                                                                               
───┴────────────────────┴─────────────────────────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**

**Comment by theAkito** [comment]
I think I encountered this issue, when trying to pipe a `*.tar.gz` into `tar` from a `fetch`. This breaks a lot of piping possibilities.

**Comment by rgwood** [comment]
Can either of you give more details as to what failed?

I'm not able to reproduce this; `ps -l | vim -` works OK for me on v0.72
![image](https://user-images.githubusercontent.com/26268125/204962985-9b4f0250-de04-4af6-8b47-144be0ba9ac4.png)

**Comment by dmgolembiowski** [comment]
> Can either of you give more details as to what failed?
> 
> I'm not able to reproduce this; `ps -l | vim -` works OK for me on v0.72 ![image](https://user-images.githubusercontent.com/26268125/204962985-9b4f0250-de04-4af6-8b47-144be0ba9ac4.png)

Thank you, I think I ought to close this issue if it's no longer applicable on a recent release.
