### ISSUE TITLE
Table alignment improvements

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#3726]
**Is your feature request related to a problem? Please describe.**

from `char --list`:

![Screenshot from 2021-07-04 07-55-17](https://user-images.githubusercontent.com/547158/124365586-390c0f80-dc9d-11eb-9462-25c4388b6321.png)

**Describe the solution you'd like**
We could experiment with absolute column alignment:

From ANSI:
```
CSI n G | CHA | Cursor Horizontal Absolute | Moves the cursor to column n (default 1). (not ANSI.SYS)
```

**Describe alternatives you've considered**
We could also try using tabs (or ANSI tabs) to see if we could guess correctly and use tabs to align in the cases where we're misaligned.

**Comment by jntrnr** [comment]
Closing as we're "good enough". there's no way to get this perfect across all terminals.

**Comment by fdncred** [comment]
For the person in the future who doesn't accept this answer, I have a crazy idea. 😆 

We could (somehow) create a canvas, let's pretend it's some html-like canvas. Then we could render our tabular output onto it. Then take that and render it to image data and display the image in the terminal. Of course, the terminal would have to support `sixel` or some other image protocol such as iterm2's but it could be do-able, but maybe slow?

Quite a few terminals support sixel these days. I was surprised at the list here https://www.arewesixelyet.com/.
