### ISSUE TITLE
Allow subcommand aliases

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#3731]
**Is your feature request related to a problem? Please describe.**
It'd be nice to be able to make new subcommands using aliases, for example:

```
> alias "from ndjson" = from json -o
```
or
```
> alias from ndjson = from json -o
```

**Describe the solution you'd like**
We can extend alias to handle subcommands

**Describe alternatives you've considered**
Or take in quoted string and treat that as a subcommand.

related to #1458

**Comment by fdncred** [comment]
@jntrnr i think this works now. can you confirm this is what you were looking for?
`alias "from ndjson" = from json -o`
`echo $"{ "one": 1, "two": 2 }(char nl){ "three": 3, "four": 4 }" | from ndjson`
