### ISSUE TITLE
Ctrl+Backspace should delete last word

### ISSUE THREAD

**Issue by lietu** [nushell/nushell#3733]
**Is your feature request related to a problem? Please describe.**
In most OSes in most contexts Ctrl+Backspace deletes the last word before the caret, this also works on `cmd.exe`, PowerShell, as well as basically any text field everywhere. Nushell should support the same on every OS, though this does not seem to be typical of Linux - dunno about Mac.

**Describe the solution you'd like**
When pressing `Ctrl` and `Backspace` at the same time, the last word - determined by word separators - before the current cursor position on the command line should be deleted. Likely the most useful way is to leave the trailing whitespace in place, but include it when deleting, so: `foo bar ` + `Ctrl+Backspace` makes `foo `. On Windows this is not always how it happens by default, which causes extra unnecessary keypresses.

**Additional context**
![backspace](https://user-images.githubusercontent.com/1296558/124452193-d7c46900-dd8e-11eb-9624-968beaadd6ad.gif)

**Comment by fdncred** [comment]
Have you tried this with a keybindings.yml? Are you saying [this](https://github.com/nushell/nushell/blob/b8c3a10e5b1b6bd6da85fe1eb7a629bc7c8b57a9/docs/sample_config/keybindings.yml#L19-L27) doesn't work?

**Comment by lietu** [comment]
1. No I haven't tried that - didn't know it was a thing, I tried to search for this and that didn't show up
2. I'm not sure - I'll try that in a little while
3. It should be default behavior

**Comment by iamprady** [comment]
> Have you tried this with a keybindings.yml? Are you saying [this](https://github.com/nushell/nushell/blob/b8c3a10e5b1b6bd6da85fe1eb7a629bc7c8b57a9/docs/sample_config/keybindings.yml#L19-L27) doesn't work?

`ALT + BACKSPACE` works on Windows. But `CTRL + BACKSPACE` is not working.

**Comment by lietu** [comment]
Ah, yea, if this configuration is the default config - the highlighted part in https://github.com/nushell/nushell/blob/b8c3a10e5b1b6bd6da85fe1eb7a629bc7c8b57a9/docs/sample_config/keybindings.yml#L19-L27 does not work.

**Comment by jonathandturner** [comment]
As another datapoint, the line editor we're working on to integrate into Nu, [reedline](https://github.com/jonathandturner/reedline), does support ctrl+backspace in Windows.

**Comment by fdncred** [comment]
I was just debugging this again and I believe it works now. Here's the one item in my keybindings.yml file.
```yaml
- key:
    Backspace:
  modifiers:
    CTRL:
  binding:
    Kill:
      BackwardWord:
        repeat: 1
        word: Big
```

Here's a gif to demonstrate. The green text in the bottom right shows the keys i'm typing.
![ctrl-bksp](https://user-images.githubusercontent.com/343840/124926039-b350d280-dfc2-11eb-8de5-3a0c591482e0.gif)

Closing this.
