### ISSUE TITLE
help with GLIBC_2.29 error

### ISSUE THREAD

**Issue by shuncon** [nushell/nushell#3737]
nu: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by nu)

**Comment by jonathandturner** [comment]
@shuncon can you say more about the system you're trying to install on?

**Comment by waywardmonkeys** [comment]
If I were to guess, I'd suggest that it might be Ubuntu 18.04, which is still on GNU libc 2.27.

**Comment by lijilina** [comment]
[root@localhost tmp]# hostnamectl
   Static hostname: localhost.localdomain
         Icon name: computer-vm
           Chassis: vm
        Machine ID: a51f5e136f94469b8244616431a82ffe
           Boot ID: 51f34e50d9204b09b7155eb151cc8e45
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1160.el7.x86_64
      Architecture: x86-64
[root@localhost tmp]# chsh -s /usr/local/bin/nu test2
Changing shell for test2.
chsh: Warning: "/usr/local/bin/nu" is not listed in /etc/shells.
chsh: Shell not changed.

**Comment by waywardmonkeys** [comment]
Centos 7 is glibc 2.17 ... you'll have to either build your own `nu`, or perhaps there should be a build using `musl` instead that can be run more widely. (Or use a really old machine for building releases that has a very old glibc, like Centos 7.)

**Comment by xiaofengjue** [comment]
hi，I have met this problem just now, the environment is VMware merchine centos7, the problem as follows:

nu: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by nu)
nu: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by nu)
nu: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by nu)

it really annoys me, since a few days ago I've met this problem

**Comment by alextremblay** [comment]
I tried building nushell with musl....

nu itself wasn't too bad, i did eventually get it to build, but the plugins...

It was a nightmare. I ended up having to clone and build custom versions of openssl, zlib, and something else (i don't remember... libgit maybe?) with musl, and then do a bunch of extra steps to get the nushell musl build to see and link those, and after many hours of that, it still wasn't working, so i gave up and scrapped the whole thing.

**Comment by alextremblay** [comment]
I do have a working github action to build nushell in a centos7 docker container, you can see it here: https://github.com/alextremblay/nushell-build/blob/main/.github/workflows/release.yml

it's in the 'linux-compat' job. Feel free to use it as a reference. 

The resultant build of nushell + plugins is compatible with pretty much every major linux distro in active use.

**Comment by hustcer** [comment]
I have just pull down the official centos 7 image by `docker pull centos:centos7`
and build the latest nushell release in it successfully, the command history for ref:

```bash
yum update
# Install rust by: 
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
yum install gcc wget libxcb openssl-devel libX11-devel -y
cd /lib
curl -s https://api.github.com/repos/nushell/nushell/releases/latest | grep tarball_url | cut -d '"' -f 4 | wget -i - -O nu-latest.tar.gz
tar xvf nu-latest.tar.gz
cd nushell-nushell* && bash ./install-all.sh 
# Add start nu sucessfully by:
nu
```
