### ISSUE TITLE
from-csv should support headers

### ISSUE THREAD

**Issue by igor-petruk** [nushell/nushell#374]
At the moment the reader is initialized like this

```rust
    let mut reader = ReaderBuilder::new()
        .has_headers(false)
        .from_reader(s.as_bytes());
```

**Comment by igor-petruk** [comment]
In addition, it always outputs things like this.

```
 value
-------------
 [190 items]
-------------
```

I'd expect separate columns even if unnamed. I am not confident file a bug, maybe I just don't know how to use it.

**Comment by androbtech** [comment]
Thanks for reporting it @igor-petruk !

**Comment by igor-petruk** [comment]
I have my own script that produces something like

```
a,b,c
x,1,1
y,2,2
z,3,3
```

I call it like this

```
my_script | lines | from-csv
```
or
```
my_script | from-csv
```

However this does give me the result I want, but I have to list the header:
```
my_script | lines | split-column "," a b c | skip 1
```

**Comment by androbtech** [comment]
@igor-petruk Could you try again with the latest changes? [This should fix](https://github.com/nushell/nushell/pull/368) the problem.

**Comment by androbtech** [comment]
@igor-petruk Pushed [new changes](https://github.com/nushell/nushell/pull/415). For usage [please check here](https://github.com/nushell/nushell/blob/master/tests/filters_test.rs#L5-L96)
