### ISSUE TITLE
text file to table line-by-line

### ISSUE THREAD

**Issue by AriesAlex** [nushell/nushell#3748]
**Is your feature request related to a problem? Please describe.**
I want to count the number of lines in .txt file. To do this I want to open it as a table and then get the number of rows via length command

**Describe the solution you'd like**
open file.txt | split "\n" | length

**Comment by jonathandturner** [comment]
@AriesAlex - you can do this today using a slightly different command: `open file.txt | lines | length`

**Comment by AriesAlex** [comment]
Oh, thanks! And is it possible to divide not by lines, but by any character?
This is my first issue, should I close this and ask this in another one?

**Comment by jonathandturner** [comment]
you can also use characters to split lines, like `split row (char nl)` (nushell doesn't use escape characters currently)

That will give you a slightly different answer, as blank links will also disappear.

**Comment by fdncred** [comment]
> And is it possible to divide not by lines, but by any character?

Have a look at `split chars --help`
