### ISSUE TITLE
Marriage with other-than-bourne-shell languages (e.g. Python)

### ISSUE THREAD

**Issue by dumblob** [nushell/nushell#3755]
Newbie here. There be dragons :wink:.

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to either write my own bindings into non-bourne-shell languages to gain the desired functionality (in the simpliest form like `^python -c 'import scipy.constants as c;x=5;y=6;def f(z): print(x,y,z,c.pi)'`) or even reimplement the whole desired functionality in `nu` myself.

**Describe the solution you'd like**
I'd imagine something along the lines as `sh` (i.e. bash, dash, ...) is supported (i.e. easily call any binary with given arguments). But for Python functions/objects and other languages with enormous ecosystems.

**Describe alternatives you've considered**
Currently one needs to wrap everything in `nu` commands to make it usable in practice. That's enormously tedious, error-prone, inefficient and results only in a lot of boilerplate code.

I've also considered some generic FFI command for `nu` - that could work for C and other lower-level utilities (very useful! imagine calling winapi or Linux syscalls directly from `nu`!).

I've also considered `nu` command doing some automated cached binding generation in the background to interface e.g. with Python libraries.

**Additional context**
Writing native plugins for `nu` is super tedious and doesn't scale. It's mainly good for the upstream development but not much for downstream development which doesn't usually even have any Rust compiler at hand.

**Comment by fdncred** [comment]
I'm not even real sure what the ask is here. sorry, but I don't understand.

**Comment by hustcer** [comment]
I think it’s a non-goal for nushell, I'd recommend you to try [just](https://github.com/casey/just) you can [write your recipes in any language](https://just.systems/man/chapter_38.html), and the recipes can depend on each other. This may help you. And I will close this issue, sorry.
