### ISSUE TITLE
how to let string toupper?

### ISSUE THREAD

**Issue by kasini3000** [nushell/nushell#3761]
**Is your feature request related to a problem? Please describe.**
how to let string toupper? i can not get keyword 'toupper' by search. 

**Describe the solution you'd like**
where found toupper function?

**Comment by fdncred** [comment]
you can discover the commands with `help commands` and get more details with `help str` and `help str update`
`echo 'dogs and cats' | str upcase`

please reopen if this isn't the answer you're looking for.
