### ISSUE TITLE
Unlike in Bash, scripts treat $1  as a file to look for. Why so?

### ISSUE THREAD

**Issue by jerzybrzoska** [nushell/nushell#3762]
**Unlike in Bash scripts treat $1  as a file to look for**
The following script written in Bash takes one argument ($1), a file name without its extension, and creates a .c file prepending it with some boilerplate. 
```
#!/home/jerzy/.cargo/bin/nu
echo $1 
echo  "#include<stdio.h>
//#include<stdlib.h>

int main() {
 

return 0;	
}
/***********************************************************************

*****************************************************************/" > ${1}.c


```
When the same script is run with nu (with 'test' as its CLI argument) I get:

>File not found: test

**To Reproduce**
1. Download (or just copy and paste) the script, replace `#!/home/jerzy/.cargo/bin/nu` with the one of your choice.
2. Run with Bash first
3. Then run the same script with nu

**Comment by fdncred** [comment]
maybe try `bash name_of_script.sh` from within nu or perhaps put a shebang in the script?

**Comment by jerzybrzoska** [comment]
@fdncred I did already try all of these before opening this issue - to no avail. I pasted here the code without shebangs because different people may have various environments.

**Comment by fdncred** [comment]
you might be able to piece something together with our `selector` command. here's a start `fetch https://www.anandtech.com/show/6985/choosing-a-gaming-cpu-at-1440p-adding-in-haswell- | selector div -a | selector img -t src`

**Comment by jerzybrzoska** [comment]
@fdncred I replaced the script in the original post so that it is no longer a scraping script.
Now it is a very simple script and everyone can run it and see that CLI arguments do not work in nu, at least with syntax taken from Bash.

**Comment by fdncred** [comment]
if you want to capture arguments in a nushell script, you probably need to write nushell custom commands as demonstrated in the nushell/nu_scripts repo.

**Comment by panicbit** [comment]
As it stands now, the nu cli will treat any rest argument as another script to execute.
E.g. `nu foo bar` will execute `foo` and then `bar`.
This alone makes it currently impossible to pass any args for scripts into nu.
Even if the cli allowed this, there would be no way for a custom command or a plugin to access this without nu exposing the args explicitly.

IMO the ability to pass in arguments to scripts is highly desirable.

**Comment by fdncred** [comment]
you can pass arguments to scripts as demonstrated in the nushell/nu_scripts repo. There are a few scripts there that utilize the custom command parameter named `...rest` that allows you to collect and pass many arguments at once.

**Comment by panicbit** [comment]
The fact that custom commands can accept `...rest` parameters is a completey unrelated featuer. I looked at the `nushell/nu_script` scripts that contain `...rest` and none of them had a shebang nor demonstrated how the desired goal could be reached. To me it feels like there is still a misunderstanding of what is being requested in this issue.

The task is to translate the following bash script to nu:

### greet.sh
```bash
#!/usr/bin/env bash

echo hello $1
```

This script allows you to run it from pretty much any shell, even non-bash ones as `./greet.sh world`, getting `hello world` as output.

**Comment by fdncred** [comment]
Ya, I see what you're saying now. sorry for the misdirection.  I'm not sure nushell works with shebangs. I was suggesting that you do something like this.
1. write a script with a custom command.
2. source that script
3. execute the custom command in that script.

example script
```bash
def greet [...rest] {
    $"Hello, ($rest)!"
}
```

```> source greet.nu```

```
> greet World
Hello, World!
```

I tried playing around with `$it` but couldn't get it to respond to a shebang script with no custom commands.

**Comment by hustcer** [comment]
There is a similar issue [here](https://github.com/nushell/nushell/issues/3334)

**Comment by hustcer** [comment]
We need this feature badly, because we want rewrite all our scripts by nushell.

**Comment by jntrnr** [comment]
If folks are interested, we're chatting a bit about how best to implement script params in #design-discussion on the [discord](https://discord.gg/NtAbbGn)

**Comment by hustcer** [comment]
@jntrnr Will this issue be fixed in `engine-q` ? Thanks

**Comment by jntrnr** [comment]
@hustcer - the way we currently have working in engine-q is something like this:

```
def main [arg1: string, arg2: int] { .. }
```

If engine-q detects a `main` in the script you're running from the commandline, it'll run that first with the arguments you pass in from the commandline.

**Comment by hustcer** [comment]
@jntrnr Great, sounds good! Can we have it in nushell  at around 01/31/2022 ?

**Comment by hustcer** [comment]
> @hustcer - the way we currently have working in engine-q is something like this:
> 
> ```
> def main [arg1: string, arg2: int] { .. }
> ```
> 
> If engine-q detects a `main` in the script you're running from the commandline, it'll run that first with the arguments you pass in from the commandline.

This already works in the latest main branch. I think we can close this issue, please reopen if you still have issues.
