### ISSUE TITLE
Option to disable hints

### ISSUE THREAD

**Issue by cinerea0** [nushell/nushell#3768]
**Is your feature request related to a problem? Please describe.**
I find command autosuggestions to be visually noisy. However, I like the tabular view and all of the other features nu provides.

**Describe the solution you'd like**
I would like to be able to turn off autosuggestions using some kind of option in nushell's `config.toml` file.

**Describe alternatives you've considered**
Being able to set the color of the autosuggestions to the terminal's background color may also work as long as the issue that Fish currently faces where doing that makes the terminal's cursor disappear is avoided.

**Comment by fdncred** [comment]
Do you mean the hints?  The part that is dark gray here?
![image](https://user-images.githubusercontent.com/343840/125629112-b2051546-c2ff-4ca4-9773-8b76c289eedf.png)

**Comment by cinerea0** [comment]
@fdncred Yes, that's it. I'll adjust the title of my issue to use nu's preferred term for the feature.

**Comment by fdncred** [comment]
thanks for confirming. we'll have to investigate, hints are a feature of the line editor we use called rustyline.

**Comment by fdncred** [comment]
oh wait, there is a `show_hints` already in the source code - ugh, it looks like it's broken. :(

**Comment by fdncred** [comment]
This should fix it. You just have to change the `config.toml` in the `[line_editor]` section to have `show_hints = false`
https://github.com/nushell/nushell/pull/3780
