### ISSUE TITLE
fix nightly version with `rust-toolchain` file

### ISSUE THREAD

**Issue by 7ma7X** [nushell/nushell#377]
The version of `rustc nightly` has been rapidly changing, and you may well fail to build program because you've installed a bit old version of *rustc* (for example, `rustc nightly 2019-07-07` can't build `futures-io`).
So I suggest rustc version should be fixed by explicitly writing down in `rust-toolchain` file.

**Comment by est31** [comment]
The version [is already pinned](https://github.com/nushell/nushell/blob/master/.azure/azure-pipelines.yml#L2) in azure-pipelines.yml. Pinning via a rust-toolchain file would be a really great idea as well. I wonder whether there is a way to have azure read the rust-toolchain file.

**Comment by zimbatm** [comment]
related: #362

**Comment by 7ma7X** [comment]
Good.
