### ISSUE TITLE
when mouse drag with table-paper feature,main thread panic.

### ISSUE THREAD

**Issue by shenhunluo** [nushell/nushell#3773]
Terminal : Windows Terminal Preview
OS : Windows
Target : stable-x86_64-pc-windows
version : 0.23/0.24
features : table-paper

**Screenshots**
![image](https://user-images.githubusercontent.com/19304469/125579833-29f56247-7381-4729-80ca-ba629ffe114a.png)

Error only on 'Windows Terminal Preview',normal on 'Windows Terminal' 'alacritty' 'mobaXterm' 'powerShell'

**Comment by shenhunluo** [comment]
Sorry,I can not speak English

**Comment by fdncred** [comment]
If the error occurs only on Windows Terminal Preview but works everywhere else, doesn't that mean it's a problem with the preview version of windows terminal?

Does this still happen on the latest version of nushell?

**Comment by shenhunluo** [comment]
> If the error occurs only on Windows Terminal Preview but works everywhere else, doesn't that mean it's a problem with the preview version of windows terminal?
> 
> Does this still happen on the latest version of nushell?

I think this is a bug in minus or crossterm.
I inserted the print code in crossterm, I found that if the mouse drag is slow,minus will not panic.
And only 'Windows Terminal Preview' catch MouseEvent, so Error only on 'Windows Terminal Preview'.

**Comment by shenhunluo** [comment]
> If the error occurs only on Windows Terminal Preview but works everywhere else, doesn't that mean it's a problem with the preview version of windows terminal?
> 
> Does this still happen on the latest version of nushell?

**Comment by jntrnr** [comment]
This seems to be fixed in the latest main. I'm going to close it, but if you still see it in the latest main, please re-open.
