### ISSUE TITLE
`$it` is lost in `if` condition

### ISSUE THREAD

**Issue by x3rAx** [nushell/nushell#3774]
**Describe the bug**
I don't know if this really is a bug or if it's just me doing it wrong but the behavior is definitely not what I expected:

I try to create a custom `ls` command which shows me more details on the date, just like the `bash` version does. I use `update` to update the `modified` column but when I try to use `$it` inside an `if` condition, I get "Unknown variable: $it":

```nushell
ls -l | select mode inode uid group size modified name | update modified { if ($it.modified | date to-table | get year) == (date to-table).year { echo format-date-without-year-but-with-time} { echo format-date-with-year-and-without-time } }
```

**To Reproduce**
1. Try to update the modified field of `ls -l` based on the year:
   ```nushell
   ls -l | select modified | update modified { if ($it.modified | date to-table).year == 2021 {echo a} {echo b} }
   ```

**Expected behavior**
The `it` variable should also be available in the `if` condition like it is when doing an echo of the same value:

```nushell
ls -l | select modified | update modified { echo ($it.modified | date to-table).year }
```

**Screenshots**

**Configuration (please complete the following information):**

My configuration is empty:

```
> config
───┬──
 0 │
───┴──
```

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
───┬────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                         Column1
───┼────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.33.0
 1 │ build_os           │ linux-x86_64
 2 │ rust_version       │ rustc 1.53.0
 3 │ cargo_version      │ cargo 1.53.0
 4 │ pkg_version        │ 0.33.0
 5 │ build_time         │ 2021-07-07 09:30:49
 6 │ build_rust_channel │ release
 7 │ features           │ clipboard-cli, ctrlc, default, ptree, rustyline, term, trash, uuid, which, zip
 8 │ installed_plugins  │ binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps,
   │                    │ query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath
───┴────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**

I'm completely new to nushell. I literally started to use it about 2 hours ago after I decided it would be time to finally give it a try. Please forgive me if I'm doing something fundamentally wrong here. 😬

**Comment by x3rAx** [comment]
I just found out how to do it correctly:

Since `nushell` 0.32 it is possible to name block parameters, so it is possible to use an explicit variable name instead of `$it`.

**I will however leave this issue open because maybe it should have worked the way I first tried it. Please close this issue if the described behavior is expected.**

---

So the solution to my problem is:

```nushell
ls -l | select modified | update modified { |row| if ($row.modified | date to-table).year == 2021 {echo a} {echo b} }
                                           ,^^^^^    ,^^^^
---> this >-------------------------------'---------'
```

The above command is just for demonstration. What I wanted to achieve was this:
```nushell
alias ll = (ls -l | select mode inode uid group size modified name | update modified { |row| let m = $row.modified; let d = ($m | date to-table); let y = (date to-table).year; if $d.year == $y { $m | date format "%d.%m  %H:%M:%S"  } { $m | date format "%d.%m.%Y" } })
```

which then produces the following for the `modified` column:

```
> ll | get modified
───┬─────────────────
 0 │ 31.05  09:16:32
 1 │ 31.03.2020
 2 │ 18.12.2019
 3 │ 13.07.2018
 4 │ 10.10.2020
 5 │ 31.03.2018
 6 │ 14.09.2019
 7 │ 09.04  15:57:51
 8 │ 11.04  09:47:35
 9 │ 14.07  06:16:19
───┴─────────────────
```

**Comment by fdncred** [comment]
in your first command, you'd want to use `each`, something like this `ls -l | each { update modified { $it.name }}`

if you still have a question, please re-open.
