### ISSUE TITLE
Feature request: support for alias

### ISSUE THREAD

**Issue by patriksvensson** [nushell/nushell#378]
Loving this project. Would be super useful if there was support for alias.

For example, to clear the terminal I should use `cls`, but I prefer `clear`. Would be nice if there was some way of adding this alias to a nushell profile or similar.

```
> alias clear cls
```

**Comment by howdoicomputer** [comment]
Came here looking for the `clear` command. Aliases would be super nice and would probably be a necessary feature for a `1.0` release, no?

**Comment by patriksvensson** [comment]
@Flare576 That would absolutely solve it, but would be nice with built in alias support as well.

**Comment by jonathandturner** [comment]
`alias` is now available on master and should be part of the next release

**Comment by ksnyde** [comment]
@jonathandturner feeling a bit unsure with all things Rust so let me ask the newbie question ... what's the best way to install from master? How frequently are new versions published?

**Comment by thegedge** [comment]
Hey, @ksnyde 👋 

> what's the best way to install from master?

The "Local" instructions (https://github.com/nushell/nushell#local) should be good enough to get you up and running, although I'd recommend `cargo install --features=stable` to get some more goodies 🙂

> How frequently are new versions published?

We have a three week release cycle 3️⃣

**Comment by ndarilek** [comment]
Looks like this is in a release now? How does one use it? Looks like the "alias" command runs a block on each row of the table. I'm wondering if I'm misunderstanding this functionality? How would I use this command to, say, alias "gpl" to "git pull" and save that in my config?

Thanks.

**Comment by thegedge** [comment]
> Looks like this is in a release now?

Yes 🙂

> How does one use it? Looks like the "alias" command runs a block on each row of the table. I'm wondering if I'm misunderstanding this functionality? How would I use this command to, say, alias "gpl" to "git pull" and save that in my config?

We'll better document it in the near future, but for now I'll help out here. You can create an alias like this:

```
❯ alias <name> [<args>] { <pipeline> }
```

So to create an alias for git pull, you can do this:

```
❯ alias gpl [] { git pull }
```

And if you wanted to give it args:

```
❯ alias gpl [remote branch] { git pull $remote $branch }
```

We currently have an issue where an alias that starts with an external function may fail if the alias is the first part of a pipeline. We should hopefully have that fixed by our next release.

**Comment by ndarilek** [comment]
Neat, thanks! Two more questions: how do I save that alias so it is 
evaluated on startup, and is it possible to just pass whatever arguments 
I send to the alias through to the command without specifying them in 
the definition?

**Comment by ksnyde** [comment]
@ndarilek have a glance at the 0.13.0 release notes about the "startup" variable in **config**. Here's the meat of it:

```sh
config --set [startup ["alias myecho [msg] { echo $msg }"]]
```

**Comment by ndarilek** [comment]
Cool, thanks, read the release notes. My gpl Fish alias is as follows:


```

function gpl
   git pull $argv
end


Is there an $argv equivalent so I can just pass in everything given to 
the alias without hard-coding or even requiring parameters? I grepped 
the book and didn't immediately see anything. I do plan on reading it 
indepth, but am trying to dive into the deep end and make myself use Nu, 
and unfortunately these aliases are years of muscle memory so I'm trying 
to bring them up quickly. :)


Thanks again.

**Comment by thegedge** [comment]
Not yet, @ndarilek. If we don't already have an issue for it, I'd recommend opening one 🙂

**Comment by lpil** [comment]
Hello! Is it possible to have variable numbers of args for aliases?

```nushell
alias g [...x] { git ...$x }
```

**Comment by hrvolapeter** [comment]
@lpil I would like that very much too, however I'm not sure how well it combines with nu philosophy and maybe we just have to start thinking a new way

**Comment by jonathandturner** [comment]
@lpil / @hrvolapeter - it'd be a good feature. I think there are a few pieces we need to add first, but adding support is definitely something we'd like to do.
