### ISSUE TITLE
Removing `alias`' and `def`s

### ISSUE THREAD

**Issue by RustemB** [nushell/nushell#3782]
**Is your feature request related to a problem? Please describe.**
Need a way to remove `alias`s and `def`s

**Describe the solution you'd like**
maybe something like `unalias` and `undef`

**Comment by fdncred** [comment]
ya, i agree. right now, i think the only option is to exit out of nushell and start again, which isn't very nice.

**Comment by pejato** [comment]
@fdncred Any way I could take this issue?

Looks like we already added `unalias` in https://github.com/nushell/nushell/pull/3879 so we'll just need `undef`.

Just some thoughts on `undef`.. Can also discuss this on the Discord.

* In my opinion, we should prohibit calling `undef` with a built-in command and print an informative error
* the `unalias` PR added a 0 arg version of `alias` to print out all aliases in the current scope; do we want to do something like that for `def` as well?

* we should think about how we want `undef` to behave if we `undef` a command used by another command

e.g.

```
def f [i:int] { $i + 1 }
def g [j:int] { f $j }
```

If we `undef` f, what should happen when we call `g`?

I have a rough implementation of this already, and the current behavior is that calling `g 3` after I `undef` f prints
```
error: Error: Missing command 'f'
```
It is probably better to match the behavior of defining `g` without `f` in scope. e.g. just running
```
def g [j:int] { f $j }
```
and calling `g 3` yields
```
error: Command not found
   ┌─ shell:21:17
   │
21 │ def g [j:int] { f $j }
   │                 ^ command f not found
```

If we look to other shells for inspiration..

`zsh` yields `g: command not found: f`
`bash` yields `-bash: f: command not found`

**Comment by fdncred** [comment]
@pejato go for it, it's yours! however, please make sure you discuss your design in discord so the core-team can help steer you in the right direction.

**Comment by pejato** [comment]
Soooo, I talked with @jntrnr about this on Discord. Seems like `undef` won't be of much use to us once we have "overlays" working. If anyone feels strongly I can keep working on this or pick it up themselves but I'm going to look at other tasks for the moment.
