### ISSUE TITLE
Abrupt halt

### ISSUE THREAD

**Issue by Manish0925** [nushell/nushell#3785]
**Describe the bug**
Shell stops working upon typing the command "source con" without even hitting Enter key (atleast in Windows)

**To Reproduce**
1.  Type "source con"

**Expected behavior**
Shell stops working and user is unable to enter anything

**Screenshots**

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
╭───┬────────────────────┬───────────────────────────────────────────────────────────────────────╮
│ # │ Column0            │ Column1                                                               │
├───┼────────────────────┼───────────────────────────────────────────────────────────────────────┤
│ 0 │ version            │ 0.34.0                                                                │
│ 1 │ build_os           │ windows-x86_64                                                        │
│ 2 │ rust_version       │ rustc 1.53.0                                                          │
│ 3 │ cargo_version      │ cargo 1.53.0                                                          │
│ 4 │ pkg_version        │ 0.34.0                                                                │
│ 5 │ build_time         │ 2021-07-13 18:43:38                                                   │
│ 6 │ build_rust_channel │ release                                                               │
│ 7 │ features           │ clipboard-cli, ctrlc, dataframe, default, rustyline                   │
│   │                    │ term, trash, vvid, which, zip                                         │
╰───┴────────────────────┴───────────────────────────────────────────────────────────────────────╯
```

**Add any other context about the problem here.**

**Comment by fdncred** [comment]
That's cool and freaky at the same time. I know that on Windows, `con` is a reserved keyword. I'm not sure why it hangs nushell though.

**Comment by Manish0925** [comment]
Doesn't happen for "con". Happens only for "source con"

**Comment by Manish0925** [comment]
> That's cool and freaky at the same time. I know that on Windows, `con` is a reserved keyword. I'm not sure why it hangs nushell though.

Doesn't happen for "con". Happens only for "source con"
