### ISSUE TITLE
broken link in releases

### ISSUE THREAD

**Issue by adsick** [nushell/nushell#3786]
https://github.com/nushell/book/blob/master/en/installation.md#dependencies
this one gives 404

**Comment by fdncred** [comment]
thanks

**Comment by dineshkumar12004** [comment]
can i work on this @fdncred

**Comment by fdncred** [comment]
it's yours @dineshkumar12004 . Have fun!

**Comment by dineshkumar12004** [comment]
Hey I just wanna verify i'm in the right path 
This is the broken URL path: https://github.com/nushell/book/blob/master/en/installation.md#dependencies
This is the correct URL path:  https://www.nushell.sh/book/installation.html#dependencies

And i'm not sure where exactly these files of releases(https://github.com/nushell/nushell/releases?after=0.26.0) present in repo. can you give some pointers. Thanks :)

**Comment by jntrnr** [comment]
with @dineshkumar12004's help, I updated the last few releases. Closing
