### ISSUE TITLE
Autocomplete for paths are case sensitive on Windows

### ISSUE THREAD

**Issue by patriksvensson** [nushell/nushell#379]
If I have a folder called `D:/Foo` and I start writing `cd D:\f` and press `tab` I get no match for `Foo`. If I try `cd D:\F` it works as expected.

**Comment by jonathandturner** [comment]
good catch. We're planning on improvements to autocomplete for the next release, and this should definitely be included

**Comment by Andrew-Webb** [comment]
This complicates things a bit:-

https://www.howtogeek.com/354220/how-to-enable-case-sensitive-folders-on-windows-10/

**Comment by tmr232** [comment]
I don't think it changes the desired behaviour much - if there's a case-sensitive match, go for that. If not - do a case-insensitive match. It's behaviour that I'd enjoy on Linux as well.

**Comment by fdncred** [comment]
This case sensitivity on Windows drives me crazy. It makes the auto-complete nearly unusable. Love NuShell. Hate NuShell auto-complete.

**Comment by tmr232** [comment]
Is this implemented in nushell, or just using rustyline?

**Comment by fdncred** [comment]
I believe it's rustyline. I've tried to look for a case insensitive setting in rustyline but didn't find one, but maybe I just missed it.

**Comment by thegedge** [comment]
We're consolidating the completions effort in #290 for now. After we close off that issue, we can open (or reopen) specific issues related to completions that weren't resolved with the consolidated effort.

**Comment by fdncred** [comment]
Just pushed a rustyline [PR ](https://github.com/kkawakam/rustyline/pull/387)to take care of this.
