### ISSUE TITLE
command line syntax highlighting is broken ?

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#3790]
**Describe the bug**
The command line isn't syntax highlighted properly

**To Reproduce**
1. type alias cfy = (cal --full-year 2021)
2. type cfy
3. observe how c is colored differently than fy

**Expected behavior**
All the same color

**Screenshots**
looks normal
![image](https://user-images.githubusercontent.com/343840/125795696-4a6d45f3-534c-46e4-80ea-e76080f137b1.png)

not normal
![image](https://user-images.githubusercontent.com/343840/125795746-be0da5fe-3fcd-4943-b349-0b9150944f79.png)

**Configuration (please complete the following information):**

|key|value|
|-|-|
|version|0.34.0|
|branch|main|
|short_commit|2864eaeb|
|commit_hash|2864eaebaefbead4ee68c298866adaf0028cc9d0|
|commit_date|2021-07-14 09:47:33|
|build_os|windows-x86_64|
|rust_version|rustc 1.53.0 (53cb7b09b 2021-06-17)|
|rust_channel|stable (default)|
|cargo_version|cargo 1.53.0 (4369396ce 2021-04-27)|
|pkg_version|0.34.0|
|build_time|2021-07-15 08:28:49|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by shaaraddalvi** [comment]
👋🏽 can I try picking this up? I'm new to this project so I may need some help/pointers to work my way through though!

**Comment by fdncred** [comment]
ya, sure. go for it. i'll assign it to you.

**Comment by shaaraddalvi** [comment]
I'm trying to figure out how the aliases are stored in memory as the alias command doesn't seem to do any operation apart from just `Ok()`.

Also seems like the painting / highlighting is happening [here](https://github.com/nushell/nushell/blob/main/crates/nu-engine/src/shell/painter.rs#L25).

Is there a way to debug the shell interactively in VSCode or other IDE?

**Comment by fdncred** [comment]
You may be able to find the information you're looking for by looking at `$scope.aliases`. You're right that the `alias` command isn't really a command. I think @jntrnr just wrote it to allow `alias --help` to respond properly.

**Comment by shaaraddalvi** [comment]
Took another look at it after a long break (sorry!) and this still reproduces on `main`.

High-level understanding till now is - 
* [This](https://github.com/nushell/nushell/blob/4f7b423f3679e237d615b91e45cf14119aafe290/crates/nu-engine/src/shell/painter.rs#L30) is where the alias is being expanded into a block.
* During expansion of an alias with `expand_aliases_in_call`, the span of alias is set into the span of the expansion. E.g. taking the example in OP, span for `cfy` would be set into the span of `(cal --full-year 2021)`.
* Even though we have this correct span, while getting the shapes [here](https://github.com/nushell/nushell/blob/4f7b423f3679e237d615b91e45cf14119aafe290/crates/nu-engine/src/shell/painter.rs#L30), we ignore this span information set above and still go on evaluating the spans for the actual expansion. i.e., we try to compute spans ignoring the fact that this command was aliased.
* This is verified by replacing `output.push(FlatShape::Flag.spanned(expr.span));` [here](https://github.com/nushell/nushell/blob/4f7b423f3679e237d615b91e45cf14119aafe290/crates/nu-parser/src/shapes.rs#L120). Not that this should be a fix, but it verifies the above.

@jntrnr any suggestions about how to go about fixing this? 😄 Maybe the fact that we are expanding aliases needs to be stored somewhere in the `Block`?

**Comment by jntrnr** [comment]
@shaaraddalvi - sorry for the slow delay. We've been doing a lot of work to rewrite the parser, and it seems like this issue may have gotten fixed as part of that effort.

If you're at all curious in possibly helping out with some of these parser related issues, you can find out more in the rewrite repo: https://github.com/nushell/engine-q

**Comment by jntrnr** [comment]
This is now highlighted white which is... better? This is basically just the highlighter giving up and picking the default.

**Comment by fdncred** [comment]
fixed with engine-q changes.
