### ISSUE TITLE
Open in $EDITOR

### ISSUE THREAD

**Issue by naefl** [nushell/nushell#3795]
**Is your feature request related to a problem? Please describe.**
in zsh, when I'm in normal mode of the vim line editor, pressing `v` will open the current line in nvim for editing which is
*chef's kiss*

**Describe the solution you'd like**
a keybinding action that does the same 

Thanks again for the awesome shell.

**Comment by fedoranvar** [comment]
ping!

**Comment by sholderbach** [comment]
This is now implemented in all edit modes with `Ctrl-o` to open the external editor. 

This first reads the config for `buffer_editor` and then `VISUAL` or `EDITOR`. Key event to trigger it is `OpenEditor` but vi rebinding is currently limited.

#5614 
#5426
https://github.com/nushell/reedline/pull/422
https://github.com/nushell/reedline/pull/411
