### ISSUE TITLE
What document tool does www.nushell.sh use？

### ISSUE THREAD

**Issue by longtai94** [nushell/nushell#3796]

**Comment by fdncred** [comment]
I don't understand your question. What do you mean?

**Comment by eggcaker** [comment]
I guess you want this :  vuepress
https://github.com/nushell/nushell.github.io

**Comment by longtai94** [comment]
> I guess you want this : vuepress
> https://github.com/nushell/nushell.github.io
> https://vuepress.vuejs.org/

Thank you very much. That's what I want
