### ISSUE TITLE
How to convert duration to string ?

### ISSUE THREAD

**Issue by roninee** [nushell/nushell#3800]
I tried  dur | into string , didn't work.
Is there command to get  variable "type", like  $x | type...

**Comment by adsick** [comment]
btw I also thought about it, and I don't know as well.
also was a bit confused when trying to copy nu's table output in 'clever' way by doing ```version | clip``` it gave an error 'can't convert to string' lol, I see it on my screen in the form of string....

**Comment by fdncred** [comment]
It just looks like duration isn't implemented in `into string`. It could be added.

This is what I did to reproduce this issue.
```rust
let one = (ls | first | get modified)
let two = (ls | last | get modified)
echo ($two - $one)
12day 5min 55sec 229ms 148us 842ns
```
```
echo ($two - $one) | into string
error: Error: Unimplemented: into string for primitive: Duration(BigInt { sign: Plus, data: BigUint { data: [1037155229148842] } })
```

**Comment by adsick** [comment]
why it can't just use the default string representation which is then gets printed on screen?

**Comment by fdncred** [comment]
@adsick I think it's because strings are not written to the screen, nushell `Value`s are written to the screen. so, one has to convert the `Value` to a string or other nushell type.

**Comment by roninee** [comment]
@adsick @fdncred 
I found a short one : 
_$"($dur)"_
This is a string!
But I think we still need a 'TYPE' command

**Comment by fdncred** [comment]
to get the datatype you can use the `describe` command or the `debug --raw` command

**Comment by roninee** [comment]
@fdncred Thanks, it's very helpful!
