### ISSUE TITLE
Running commands shells out before variable expansion.

### ISSUE THREAD

**Issue by camblomquist** [nushell/nushell#3801]
**Describe the bug**

nushell doesn't appear to expand variables before shelling out, which makes it difficult to pass variables to commands.

**To Reproduce**
1. Call an external command with a nu-style variable (I used `git --git-dir=$nu.home-dir log`)
2. Command will respond with the literal string rather than the expanded variable.
3. Using cmd variables works since the literal is passed and then parsed by cmd.

**Expected behavior**
When passing a variable as an argument to an external command, I would expect it to

- Expand variables before shelling out
- Not shell out in the first place (though this may just be a misinterpretation of what I believe a shell should be able to do.)

**Screenshots**
<img width="432" alt="WindowsTerminal_87vd6krHbT" src="https://user-images.githubusercontent.com/36173306/126076349-5e03b4c7-0b7b-4e97-a7f2-9c596aa552a5.png">

**Configuration**

```
> version | pivot
───┬────────────────────┬────────────────────────────────────────────────────
 # │      Column0       │                      Column1
───┼────────────────────┼────────────────────────────────────────────────────
 0 │ version            │ 0.34.0
 1 │ build_os           │ windows-x86_64
 2 │ rust_version       │ rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)
 3 │ rust_channel       │ nightly-x86_64-pc-windows-msvc (default)
 4 │ cargo_version      │ cargo 1.52.0-nightly (90691f2bf 2021-03-16)
 5 │ pkg_version        │ 0.34.0
 6 │ build_time         │ 2021-07-16 12:47:08
 7 │ build_rust_channel │ release
 8 │ features           │ ctrlc, dataframe, default, rustyline, term, which,
   │                    │ zip
 9 │ installed_plugins  │ fetch, match, post, ps, sys
───┴────────────────────┴────────────────────────────────────────────────────

```
In case it is relevant, I am running nushell inside Windows Terminal.

**Comment by fdncred** [comment]
Can you try this to see if it makes any difference?

`git --git-dir=($nu.home-dir) log`
`git --git-dir=($nu.env.USERPROFILE) log`

**Comment by camblomquist** [comment]
> 
> 
> Can you try this to see if it makes any difference?
> 
> `git --git-dir=($nu.home-dir) log`
> `git --git-dir=($nu.env.USERPROFILE) log`

Neither of these expand either. I'd be slightly more concerned if they did since that would be a different syntax from the rest of the book so far.
And for completeness, I've also tried `[]`, `{}`, `""`, `''`, and `'${}`
I forgot to mention that I'm running inside Windows Terminal, which shouldn't change the issue but was still worth mentioning. Issue has been updated with this information.

**Comment by fdncred** [comment]
ya, it looks like the parser maybe isn't parsing correctly. i would've thought my examples should work but i guess not. thanks for finding this. 
cc @jntrnr

**Comment by jntrnr** [comment]
does `git $"--git-dir=($nu.env.USERPROFILE)" log` work?

**Comment by camblomquist** [comment]
> 
> 
> does `git $"--git-dir=($nu.env.USERPROFILE)" log` work?

This does appear to work.

**Comment by jntrnr** [comment]
That'd be one workaround, at least for now, to use the `$""` string interpolation. Would be nice to improve this a bit, too.

**Comment by camblomquist** [comment]
I was going to try to jump in and work on this one, but I realize I don't really know enough about the syntax to make that sort of change.
What should be the expected behavior here? Given that `$"..."` exists, I would assume that `$"..."` should always expand and `"..."` alone will keep raw. But should any `$var` be parsed or just `($var)`? It looks like only the latter is parsed in `$"..."` but both are allowed otherwise.

`let var = "Hello!"`
then

| Input | Desired Output |
| --- | --- |
| `--arg=$"($var)"` | `--arg=Hello!` |
| `--arg="($var)"` | `--arg=($var)` |
| `--arg=($var)` | `--arg=Hello!` |
| `--arg=$var` | ??? |

I've also started using `cmd /C echo` for testing this behavior because it makes more sense than the arbitrary git command which was only used because that's what I first used when I encountered the issue.

**Comment by fdncred** [comment]
i can't get this to work in 0.59 ` ^$"git --git-dir=($nu.home-path) log"` but this does expand right without the caret.

```
> $"git --git-dir=($nu.home-path) log"
git --git-dir=/home/fdncred log
```

**Comment by jntrnr** [comment]
@fdncred you'll need the `^` in front to run it

**Comment by fdncred** [comment]
> @fdncred you'll need the `^` in front to run it

ya, i tried that right here https://github.com/nushell/nushell/issues/3801#issuecomment-1043165401

**Comment by jntrnr** [comment]
@fdncred in the quoted code it looks like it's missing. If you do a string interpolation without the `^` it will just print the result string

**Comment by fdncred** [comment]
@jntrnr you're cracking me up. We're talking passed each other. Here's a screenshot of the comment above. notice the yellow part and how it has the caret. Then i go on to say that it does expand without the caret and that may be what you're referencing.

![image](https://user-images.githubusercontent.com/343840/154546446-d6d9c71e-6ab8-447a-a861-faac1d12f6ed.png)

there's been a half-dozen prs since i mentioned this earlier today so i'll try again in a few and see if it still pukes.

**Comment by jntrnr** [comment]
oooohhhhh

**Comment by jntrnr** [comment]
basic ones seem to work for me:

```
> let foo = "it"
> $"g($foo)" 
git
> ^$"g($foo)"
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
...
```
These are common Git commands used in various situations:

**Comment by fdncred** [comment]
ya, let's close it. your mini-repro is working for me too now that i've rebuilt. i'm getting errors with the longer one but it's because there's no repo in my $nu.home-path folder.

**Comment by hustcer** [comment]
@fdncred Should this issue be closed?

**Comment by fdncred** [comment]
ya, i forgot i said that 15 days ago. lol
