### ISSUE TITLE
could you support a command that open current directory by explorer/file manager

### ISSUE THREAD

**Issue by Silentdoer** [nushell/nushell#3806]

**Comment by fdncred** [comment]
on windows, if i type `start crates` where `crates` is a folder, it opens windows explorer in the folder named crates. Is that what you mean?

**Comment by Silentdoer** [comment]
> on windows, if i type `start crates` where `crates` is a folder, it opens windows explorer in the folder named crates. Is that what you mean?

such as i cd in /home/user1, then i use command 'open-dir', then system will open folder of user1

**Comment by fdncred** [comment]
Closing this as it seems to be resolved. Please reopen if I'm misunderstanding.
