### ISSUE TITLE
support boolean flags for custom commands

### ISSUE THREAD

**Issue by zkat** [nushell/nushell#3813]
**Is your feature request related to a problem? Please describe.**
I'm trying to write a custom command that has a boolean switch.

**Describe the solution you'd like**
I'd like to be able to write the following:

```nu
def florb [ --dry-run: boolean ] { if (!$dry-run) { cmd ... } }
```

And then use it like this:

```nu
> florb --dry-run
```

**Describe alternatives you've considered**
I guess I can use `any` and test if something was passed to it, but I still need an actual argument to pass to it?

**Comment by fdncred** [comment]
This has been my work-around for that.
```rust
def print2 [
    --separator(-s):any     # Optional separator (not yet flagged as optional?)
    ...rest                 # All of the parameters
    ] {
    let is_empty = ($separator | empty?)
    let num_of_rest = ($rest | length)
    if $is_empty {
        $rest | into string | str collect
    } {
        $rest | into string | str collect $separator
    }
}
```
```>print2 -s '-' one 2 3
one-2-3
```
```>print2 one 2 3
one23
```

**Comment by zkat** [comment]
I just realized that this seems to Just Work if the parameter is just `--dry-run` with no type param? Is that intended?

**Comment by fdncred** [comment]
please explain. do you mean this works? `def florb [ --dry-run ] { if $dry-run { $true } { $false } }` or something else? This command works if you pass `--dry-run` but pukes if you don't provide an argument.

**Comment by zkat** [comment]
Interesting. I'll have to check what I did on Monday because I'm certain I managed to get something like this working and was pretty surprised!

**Comment by jntrnr** [comment]
Had to play with this a little to remember how this works in the new engine, but does seem to work. Here's the updated pattern:

```
> def florb [ --dry-run: bool ] { if $dry-run == $false { echo yes! } else { echo no } }
> florb
yes!
> florb --dry-run
no
```

Going to close as I think this is enough for the original issue. If there are related issues, please feel free to file more. I'm betting we can keep polishing this part of the language a bit more.
