### ISSUE TITLE
echo to stderr

### ISSUE THREAD

**Issue by zkat** [nushell/nushell#3816]
**Is your feature request related to a problem? Please describe.**
I would like to output to stderr as needed (related: #2259)

**Describe the solution you'd like**

I would like to be able to do something like `echo -e 'hello, error'`

**Describe alternatives you've considered**

There's... not really a way to do this right now. I guess you can write a custom (non-nu) program to make this happen :(

**Additional context**

Having a redirect feature like #2259 is fine too.

**Comment by hustcer** [comment]
@zkat Currently we have `error make { msg: 'Hello, error' }` on the latest main branch will output:
```
Error:
  × Hello, error
```
Does this feature meet your needs?

**Comment by jntrnr** [comment]
We may want to have an `eprint` to go with `print` as well, which would do the same action but print to stderr.

**Comment by tmccombs** [comment]
A problem with `error make` is that it causes an error, so it isn't suitable for things like verbose logs, or progress indicators. For example, 

```nushell
do -i { error make { msg: "Starting..."}; echo "Done" }
```
will never print "Done"

**Comment by NotTheDr01ds** [comment]
@jntrnr --
> We may want to have an `eprint` to go with `print` as well, which would do the same action but print to stderr.

What about just adding a flag to `print` to specify the fd?  While I'm not sure there's any way to open an additional fd at the moment in nu, it would future-proof the process with more flexibility when/if there is a way.

I'd propose `print -o` for "other" or "output":

E.g. to print to stderr:
```
> print -o 2 "Hello, World"
```

Side-note that PowerShell defines additional streams beyond just the equivalents of stdout/stderr:

Stream # | Description | Introduced in | Write Cmdlet
-- | -- | -- | --
1 | Success Stream | PowerShell 2.0 | Write-Output
2 | Error Stream | PowerShell 2.0 | Write-Error
3 | Warning Stream | PowerShell 3.0 | Write-Warning
4 | Verbose Stream | PowerShell 3.0 | Write-Verbose
5 | Debug Stream | PowerShell 3.0 | Write-Debug
6 | Information Stream | PowerShell 5.0 | Write-Information

**Comment by NotTheDr01ds** [comment]
Also, a hacky workaround in the meantime is:

```
echo "Hello, World" | save /dev/fd/2
```

**Comment by hustcer** [comment]
`print -e` could be used to print to stderr on the latest `main`, so can this issue be closed?

**Comment by extemporalgenome** [comment]
> @jntrnr --
> E.g. to print to stderr:
> 
> ```
> > print -o 2 "Hello, World"
> ```

This could work, though it'd be nice if symbolic synonyms were also available (i.e. `stdout` could be used in place of `1`, and `stderr` could be used in place of `2`, leading to `print -o stderr "Hello, World"` as the more readable, less magical equivalent approach).

**Comment by extemporalgenome** [comment]
@strega-nil also has requested a very similar feature, among other requests, in #3943 (related, but not a duplicate issue/request)

> I would like to be able to just write to this stream (perhaps via echo --stderr

**Comment by extemporalgenome** [comment]
Ah, it looks like `print` presently does have a `--stderr (-e)` flag.

**Comment by rgwood** [comment]
Closing because I think `print -e` addresses this, happy to reopen if I've got that wrong.
