### ISSUE TITLE
check exit code for command

### ISSUE THREAD

**Issue by zkat** [nushell/nushell#3817]
**Is your feature request related to a problem? Please describe.**
As part of scripting, it's important to be able to check whether a command succeeded, whether by assigning its exit code directly to a variable, or by checking the exit code of the previous command.

**Describe the solution you'd like**
Some replacement for the stuff that bash/zsh/etc do would be good, so:

```nu
> crash "bad"
💥
> $?
1
```

It might also be nice to capture it directly and put it in a variable:

```nu
> let code = ? crash "bad" # ? itself might be "cute" for this but probably not what nu would do?
> echo $code
1
```

**Describe alternatives you've considered**
There's literally no way to do this right now, that I can tell.

**Additional context**

**Comment by hustcer** [comment]
`$env.LAST_EXIT_CODE` was supported on the latest main. so I will close this issue.
