### ISSUE TITLE
Tables are rendered incorrectly when strings contain ansi color codes

### ISSUE THREAD

**Issue by jmoore34** [nushell/nushell#3820]
**Describe the bug**
When a string inside a table contains a color code, the spacing of cells is broken.

**To Reproduce**
`[[a b]; [$"(ansi red)x" y]]`
![image](https://user-images.githubusercontent.com/1783464/126582872-910d0316-b653-469e-ad9c-a4500e73d980.png)

Less importantly, bold is also not reset on the dividing line:
`[[a b]; [$"(ansi rb)x" y]]`
![image](https://user-images.githubusercontent.com/1783464/126582914-90451a0b-7b6d-4918-9326-ff82bfd8d682.png)

**Expected behavior**
The column width should be like so:
![image](https://user-images.githubusercontent.com/1783464/126583143-e0bef097-8097-431a-a886-853df1bded9f.png)

**Screenshots**
See above

**Configuration (please complete the following information):**

Run `version | pivot` and paste the output to show OS, features, etc.

```
> version | pivot
───┬────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                                                                 Column1
───┼────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.34.0
 1 │ build_os           │ windows-x86_64
 2 │ rust_version       │ rustc 1.52.1 (9bc8c42bb 2021-05-09)
 3 │ rust_channel       │ stable-x86_64-pc-windows-msvc (default)
 4 │ cargo_version      │ cargo 1.52.0 (69767412a 2021-04-21)
 5 │ pkg_version        │ 0.34.0
 6 │ build_time         │ 2021-07-14 18:32:11
 7 │ build_rust_channel │ release
 8 │ features           │ clipboard-cli, ctrlc, dataframe, default, rustyline, table-pager, term, trash, uuid, which, zip
 9 │ installed_plugins  │ binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath
───┴────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Add any other context about the problem here.**

**Comment by fdncred** [comment]
If you want the bold reset you need to tell it to do that like this example shows in `ansi --help`.
`echo [(ansi -e '3;93;41m') Hello (ansi reset) " " (ansi gb) Nu " " (ansi pb) World] | str collect`

I agree, we should remove the ansi escapes from the string width calculation. i think that would fix the problem.

**Comment by jmoore34** [comment]
Closing because y'all fixed this in engine-q. Thanks!

![image](https://user-images.githubusercontent.com/1783464/148131615-9b58be8c-2e7c-4064-b0d0-1bc8684b5786.png)

**Comment by fdncred** [comment]
thanks @jmoore34 for checking.
