### ISSUE TITLE
$in not found if used in if statement

### ISSUE THREAD

**Issue by NiklasJonsson** [nushell/nushell#3826]
### Describe the Bug

``` 
$ "test" | if "t" =~ $in { yes } { no }
error: Variable not in scope
   ┌─ shell:12:20
   │
12 │ "test" | if "t" =~ $in { yes } { no }
   │                    ^^^ unknown variable: $in
```
but e.g.
```
$ "test" | $in
test
```
works. Note that it doesn't matter if `$in` is used in the condition or the body:
```
 "test" | if $true { $it } { no }
error: Variable not in scope
   ┌─ shell:14:21
   │
14 │ "test" | if $true { $it } { no }
   │                     ^^^ unknown variable: $it

```

### To Reproduce

1. create pipeline ending with `if` and try to use `$in` in the if-condition or if-body

### Expected behavior

I can use $in inside the if-statement as well.

### Configuration

───┬────────────────────┬────────────────────────────────────────────────────────
 # │      Column0       │                        Column1
───┼────────────────────┼────────────────────────────────────────────────────────
 0 │ version            │ 0.34.0
 1 │ build_os           │ windows-x86_64
 2 │ rust_version       │ rustc 1.54.0-nightly (5c0292654 2021-05-11)
 3 │ rust_channel       │ nightly-x86_64-pc-windows-msvc (default)
 4 │ cargo_version      │ cargo 1.54.0-nightly (e51522ab3 2021-05-07)
 5 │ pkg_version        │ 0.34.0
 6 │ build_time         │ 2021-07-20 13:50:17
 7 │ build_rust_channel │ release
 8 │ features           │ ctrlc, dataframe, default, rustyline, term, which, zip
 9 │ installed_plugins  │ fetch, match, post, ps, sys
───┴────────────────────┴────────────────────────────────────────────────────────

**Comment by hustcer** [comment]
`"test" | if "t" =~ $in { 'yes' } else { 'no' }` works on latest main. So I will close this, please reopen if you still have issues
