### ISSUE TITLE
Possible float/integer confusion with ps | cpu > 1.5 ?

### ISSUE THREAD

**Issue by stevedonovan** [nushell/nushell#383]
The error suggests that the evaluator thinks this field is integer:

```
/home/steve/hd/rust/repos/scanlex(master)> ps | where  cpu > 1.1
error: Could not evaluate (CoerceError)
- shell:1:12
1 | ps | where  cpu > 1.1
  |             ^^^^^^^^^ could not evaluate
```

**Comment by jonathandturner** [comment]
I could definitely believe that it's being stored as an integer. If that's what it is, in theory it should be pretty straightforward to fix if you want to give it a try

**Comment by 1011X** [comment]
Judging by [this line][1], it seems like the cpu column is stored as a float.

I ran into this issue as well and judging by the syntax highlighting, it seems like nu is treating `1.1` as a string. For me, whereas an integer would be purple, `1.1` is green like any other string argument.

[1]: https://github.com/nushell/nushell/blob/1b863cbb2bee233c4092fb68e08f134780292ba3/src/object/process.rs#L19

**Comment by jonathandturner** [comment]
@1011X - good catch. The coloring could point to the issue being in the parser instead.

**Comment by luc1fe** [comment]
hmmm 😢

**Comment by jonathandturner** [comment]
This should be fixed now with more recent work on decimals and the parser.

Closing, but if you find a case where decimals aren't supported, please reopen.
