### ISSUE TITLE
Broken config error should also tell the path to the config

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#3830]
### Describe the Bug

When you mess up Config.toml, the error message doesn't tell you where the config is and subsequent attempts to run `config path` fail due to no global config found.

### To Reproduce

1. Modify Cargo.toml so that Nushell won't launch. For example: `path = [ C:\foo\bar ]` (hint: the path is not a string)
2. Launch nu, see the error not printing the config path:
```
error: Couldn't parse config file:
invalid TOML value, did you mean to use a quoted string? at line 2 column 5
  ┌─ shell:1:1
  │
1 │
  │ ^ file name
```
3. Cannot run `config path` due to "error: Error: No global config found!"

### Expected behavior

I'd like to see the path to Config.toml in the error message so I can go and fix it. I forgot where the file is on Windows and now have to go search for it.

### Configuration

```
> version | pivot
────┬────────────────────┬────────────────────────────────────────────────────────
 #  │      Column0       │                        Column1
────┼────────────────────┼────────────────────────────────────────────────────────
  0 │ version            │ 0.34.0
  1 │ branch             │ main
  2 │ short_commit       │ 0f9e55da
  3 │ commit_hash        │ 0f9e55dac628f564c9ddcc215e7b4ca45609e597
  4 │ commit_date        │ 2021-07-23 17:03:28
  5 │ build_os           │ windows-x86_64
  6 │ rust_version       │ rustc 1.53.0 (53cb7b09b 2021-06-17)
  7 │ rust_channel       │ stable (default)
  8 │ cargo_version      │ cargo 1.53.0 (4369396ce 2021-04-27)
  9 │ pkg_version        │ 0.34.0
 10 │ build_time         │ 2021-07-24 10:41:50
 11 │ build_rust_channel │ release
 12 │ features           │ ctrlc, dataframe, default, rustyline, term, which, zip
 13 │ installed_plugins  │ fetch, match, post, ps, sys
────┴────────────────────┴────────────────────────────────────────────────────────
```

**Comment by kubouch** [comment]
This seems to be the same issue as #3721 

Here I suggest a solution as well -- I should have created a feature request and not a bug.

**Comment by PranavBhattarai** [comment]
I have a similar situation here in Fedora Workstation 35 as u can see:
![image](https://user-images.githubusercontent.com/32763112/149974398-19cb5165-ef04-4755-b682-352c82d0272f.png)

Everything was working fine. I used Nushell with [Starship](https://starship.rs/) prompt in Alacritty terminal. It was very fast and responsive. Suddenly today I decided to use vanilla Nushell with no other hacks (like starship) from scratch. So I uninstalled nushell, even wiped nu's config folder and file. And then I reinstall nushell.
That's when things started to see error messages whenever I launched nushell.

Above _tried_ to use the solution mentioned [here](https://github.com/nushell/nushell/issues/3721), but it didn't work. Am I doing it the right way?!
![image](https://user-images.githubusercontent.com/32763112/149975328-98072df3-b17a-4d85-ad30-a170fc375b96.png)

I do have a directory and a file inside ~/.config/nu folder and it also has config.toml file as you can see:
![image](https://user-images.githubusercontent.com/32763112/149975695-8fa8ade3-ee58-475c-86ac-67fb5b2129ac.png)
But this doesn't get recognized by nushell for some weird reason.

@kubouch  help!

**Comment by kubouch** [comment]
In Nushell, the `$nu.config-path` does not depend on successfully loading the config.toml so the issue should be solved when we merge.

**Comment by PranavBhattarai** [comment]
well, waiting for that to happen.

**Comment by jntrnr** [comment]
This should be much better now in the latest main. Now, the config is a normal nushell script file, so loading errors should be much easier to find and highlight for debugging.

Here's an example of the latest main, when you have an error in your config:
```
  × External command
    ╭─[/home/jt/.config/nushell/config.nu:44:1]
 44 │ let-env GITHUB_USERNAME = "myuser"
 45 │ lt-env GITHUB_PASSWORD = "12345"
    · ───┬──
    ·    ╰── can't run executable
 46 │ 
    ╰────
    ```

**Comment by PranavBhattarai** [comment]
yes, just reinstalled nushell which has `0.44.0` and I didn't have to do anything. Everything worked normally without throwing errors.

Cool.
