### ISSUE TITLE
ScopeFrame PATH env. variable is not updated when nu is ran with `cargo run`

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#3831]
### Describe the Bug

Very subtle bug but it seems like if Nushell is ran with `cargo run`, the Path env. variable (Windows version of PATH) you get with `ScopeFrame.get_env("Path")` contains only entries from the config file but not the contents of the Path env. variable.

It appears to me like the extra environment variables added by cargo/Rust toolchain somehow made the scope to read only the path from config.

### To Reproduce

1. Clone nushell repository, `cd nushell`
2. Fix the swapped env path separators in ` .\crates\nu-test-support\src\lib.rs` if necessary
2. Put some existing path into Config.toml path field, e.g. `path = [ "C:" ]`
3. `cargo run`
4. Display nu path variable
```
> $nu.path
0. C:
1. ... paths related to rust toolchain
?. ... other paths that come from the original Path env var
``` 
5. Read "Path" env variable from scope (`pathvar` calls `args.context.scope.get_env("Path")` internally); only entries from config are listed.
```
> pathvar
0. C:
```
6. `exit`
7. `target\debug\nu`
8. Display nu path variable
```
> $nu.path
0. C:
1. ... other paths that come from the original Path env var
```
9. Read "Path" env variable from scope; same output as 8, as expected
```
> $nu.path
0. C:
1. ... other paths that come from the original Path env var
```

### Expected behavior

I expect the scope env variables to always be updated.

### Configuration

```
> version | pivot
────┬────────────────────┬────────────────────────────────────────────────────────
 #  │      Column0       │                        Column1
────┼────────────────────┼────────────────────────────────────────────────────────
  0 │ version            │ 0.34.0
  1 │ branch             │ main
  2 │ short_commit       │ 0f9e55da
  3 │ commit_hash        │ 0f9e55dac628f564c9ddcc215e7b4ca45609e597
  4 │ commit_date        │ 2021-07-23 17:03:28
  5 │ build_os           │ windows-x86_64
  6 │ rust_version       │ rustc 1.53.0 (53cb7b09b 2021-06-17)
  7 │ rust_channel       │ stable (default)
  8 │ cargo_version      │ cargo 1.53.0 (4369396ce 2021-04-27)
  9 │ pkg_version        │ 0.34.0
 10 │ build_time         │ 2021-07-24 13:33:40
 11 │ build_rust_channel │ debug
 12 │ features           │ ctrlc, dataframe, default, rustyline, term, which, zip
 13 │ installed_plugins  │
────┴────────────────────┴────────────────────────────────────────────────────────
```

**Comment by kubouch** [comment]
Seems like a Windows-only issue.

**Comment by fdncred** [comment]
I noticed this something like this yesterday but didn't investigate it. i assume it's the same issue. if i did `cargo run` on nushell, it would act differently that if i did `cargo build`. so, i quit doing `cargo run`.

**Comment by kubouch** [comment]
@fdncred I think the issue goes beyond just `cargo run` but might affect other scenarios when the launching tool alters the environment somehow. I had to dance around this in tests in #3828 where I observed similar behavior.

**Comment by kubouch** [comment]
This should be fixed now with engine-q merge.
