### ISSUE TITLE
Allow converting integers to binary and hexadecimal representation

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#3838]
### Related Problem

Nushell can understand hex and binary numbers when you type `0x...` or `0b...` but it always prints them as decimal integers. It would be great if we had an option to convert integers into binary and hexadecimal representations as well.

### Describe the solution you'd like

I don't have an exact idea where it would be best to place this functionality. Perhaps as an additional flag to `into int`:
```
> 0b111 | into int  --decimal 
7

> 0xf | into int   # implicit --decimal flag
15

> 15 | into int --hex
0xf

> 7 | into int --bin
0b111
```

The question is how to solve the formatting. The `0b` and `0x` prefix should be mandatory, in order for Nushell to understand it's an integer. There should be an option to set the target length, for example, to get the bytes aligned:
```
> 15 | into int --hex
0xf

> 7 | into int --hex --digits=2
0x0f
```

You could interpret an integer as signed or unsigned:
```
> 0b111 | into int  # implicit --unsigned
7

> 0b111 | into int --signed  # calculate two's complement
-1
```

Negative numbers seem a bit tricky. But they would use the same rule as unsigned numbers: By default, represent them with the least possible number of digits.
```
> -1 | into int --bin
0b11  

> -1 | into int --bin --digits=4
0b1111  # sign-extend to 4 digits
```

The key thing here is, the result would stay integer all the time.

### Describe alternatives you've considered

There could be a command that would allow advanced formatting, e.g., passing a `{:#018b}` into Rust's formatter together with the number. This would be useful for general-purpose formatting but has two problems:
* The result is a string, not an integer
* The user would need to know the formatter syntax which is not obvious (I need to look it up every time and always mix it up with printf syntax).

**Comment by fdncred** [comment]
love it. how about octal too?

**Comment by fdncred** [comment]
i'd also like to remove `str to-int` and combine all that functionality in `into int`.

**Comment by kubouch** [comment]
Yeah, why not octal. Nu accepts them with the `0o` prefix, I didn't know. We could go even further and add a `--base` flag for manually putting in the base -- though the use case is rather limited and we'd need to figure out what prefix to use, if any. Binary + hex + octal sounds like a good combo to me.

Also +1 for removing `str to-int`.

**Comment by fdncred** [comment]
this is kind of related but jt recently added the range iteration of 0o, 0x, and 0b but the problem I have is that it always iterates in decimal. so if you do `echo 0x0..0xf` you get 1 through 15. i'd like to be able to get all those in hex, not decimal. i mean, if i go to the trouble to specify iteration in hex, i problem want the output in hex. i wonder if something like this could be augmented in the range iterator.

**Comment by jmoore34** [comment]
Looks like a cool feature.

If you're needing a quick workaround in the meantime, you could use rink, which is another tool made in rust
![image](https://user-images.githubusercontent.com/1783464/127051333-256f0a31-41f7-45b1-b34b-12dccb6a4339.png)

**Comment by kubouch** [comment]
@fdncred So that the integer would always retain its original format? Would that mean that just typing `0xf` would print `0xf` again instead of `15`? It might be a good thing or a bad thing, not sure :-D. 

Just thinking about the implementation, it would probably require some metadata attached to the integer internally, or split the `Primitive::Int` into `Primitive::Int::HexInt`, `Primitive::Int::BinInt`, etc. The second looks better to me.

**Comment by kubouch** [comment]
@jmoore34 Nice, thanks! That's useful as a workaround for now.

**Comment by fdncred** [comment]
> @fdncred So that the integer would always retain its original format? Would that mean that just typing `0xf` would print `0xf` again instead of `15`? It might be a good thing or a bad thing, not sure :-D.

I'm just saying that we should provide the option to do it. sometimes when i'm trying to iterate in hex, i don't want decimals, otherwise i'd iterate in decimal. 

We currently provide the way to convert a hex to a decimal with `echo FF | str to-int -r 16` and to from binary to decimal with `echo '1101' | str to-int -r 2` but there isn't a way to go the other direction easily. So, if i'm doing `echo 0x00..0xff` I'm not sure how to get the hex representation out of that.

I was working on porting this c# portion of code to a nushell script and couldn't do it.
```c#
for (int a = 0x2580; a <= 0x259F; a++)
   Console.Write($"{(char)a}");
for (int a = 0x25E2; a <= 0x25E5; a++)
    Console.Write($"{(char)a}");
```

**Comment by fdncred** [comment]
I'm fine with closing this now since i can do this
```
for x in 0x2580..0x259f {
  ($x | fmt).lowerhex
}
╭────┬────────╮
│  0 │ 0x2580 │
│  1 │ 0x2581 │
│  2 │ 0x2582 │
│  3 │ 0x2583 │
│  4 │ 0x2584 │
│  5 │ 0x2585 │
│  6 │ 0x2586 │
│  7 │ 0x2587 │
│  8 │ 0x2588 │
```

**Comment by kubouch** [comment]
Yeah, I was originally thinking about not having the string conversion step but it would probably be too complicated and `fmt` is good enough.
