### ISSUE TITLE
`dataframe dtypes` shouldn't show the `...`

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#3842]
### Describe the Bug

`dataframe dtypes` should show all the columns and not truncate them in the middle.

cc @elferherrera 

### To Reproduce

1. load a file with a bunch of columns
2. $data | dataframe dtypes

### Expected behavior

show all the columns datatypes

### Screenshots

![image](https://user-images.githubusercontent.com/343840/127000209-83146143-acbf-4cba-a99a-7baa9b20817e.png)

### Configuration

|key|value|
|-|-|
|version|0.34.1|
|branch|main|
|short_commit|d54d7cc4|
|commit_hash|'d54d7cc4316c485a13940e14ed7ce66783e3d9c3'|
|commit_date|2021-07-25 15:36:09|
|build_os|windows-x86_64|
|rust_version|rustc 1.53.0 (53cb7b09b 2021-06-17)|
|rust_channel|stable (default)|
|cargo_version|cargo 1.53.0 (4369396ce 2021-04-27)|
|pkg_version|0.34.1|
|build_time|2021-07-26 08:25:59|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

### Additional Context

my work around was to guess at how many columns there were and do this `$data | dataframe dtypes | dataframe show -n 200` which then showed all the columns because there were "only" 170 columns.

**Comment by fdncred** [comment]
maybe this is by design?

**Comment by elferherrera** [comment]
This is by design

All dataframe commands return a dataframe and dataframes are never printed complete to avoid issues with massive dataframes.

Probably we could add a message that points the user to the command `show` to print the complete dataframe

**Comment by fdncred** [comment]
it's probably fine. it's just a lot of typing to get the list of column datatypes.
