### ISSUE TITLE
Broken compilation with extra features

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#3851]
### Describe the Bug

Nushell latest main does not compile with `extra` features enabled. Seems like it's coming from the S3 plugin.

This happened not so long ago, I was able to build yesterday just fine.

### To Reproduce

1. clone nushell repo
2. `cargo install --path=. --features=extra`
3. observe the error
```
error: failed to compile `nu v0.34.1 (.../nushell)`, intermediate artifacts can be found at `.../.cargo/target`

Caused by:
  failed to select a version for the requirement `crypto-mac = "^0.4"`
  candidate versions found which didn't match: 0.11.1, 0.11.0, 0.10.1, ...
  location searched: crates.io index
  required by package `hmac v0.4.1`
      ... which is depended on by `s3handler v0.7.0`
      ... which is depended on by `nu_plugin_s3 v0.34.1 (.../nushell/crates/nu_plugin_s3)`
      ... which is depended on by `nu v0.34.1 (.../nushell)`
```

### Expected behavior

Expected smooth compilation.

### Configuration

Trying to compile at commit e4c282f0a611face3b68dfb51780d5cc5f3347ed on Linux.

### Additional Context

Latest known working commit for me is d54d7cc4316c485a13940e14ed7ce66783e3d9c3 which is just one commit ago. The error might come from somewhere else. Looks like the versioning system of the `crypto-mac` crate changed or something like that.

**Comment by fdncred** [comment]
i wonder if this is a mac/linux thing. i just compiled the latest main on windows without issue.

**Comment by fdncred** [comment]
I do get the same thing in WSL2 though.
![image](https://user-images.githubusercontent.com/343840/127169724-7aa0e090-0472-4af5-9e97-4cb44c11aea3.png)

my only way around this was to comment out the s3 stuff in the cargo.toml

**Comment by lukesutton** [comment]
I'm running the macOS Monterey beta (21A5284e) and I'm receiving the same error.

**Comment by alexandrestein** [comment]
Same on Debian 10.
Commenting the S3 references into Cargo.toml prevent the error. Thanks @fdncred.

**Comment by fdncred** [comment]
I'm hoping @yanganto will help us fix this. https://github.com/nushell/nushell/pull/2328

**Comment by yanganto** [comment]
Yes, I will take a look on this.

**Comment by yanganto** [comment]
Hi @kubouch, may you check on this again,  I have check this can build on NixOS unstable with following minial extra feature.
```
extra = [
    "default",
    # "binaryview",
    # "inc",
    "tree",
    # "textview",
    # "clipboard-cli",
    # "trash-support",
    # "uuid-support",
    # "start",
    # "bson",
    # "sqlite",
    "s3",
    # "chart",
    # "xpath",
    # "selector",
    # "query-json",
]
```

Thanks for reporting this.  
Hi @fdncred thanks for pin me.

**Comment by kubouch** [comment]
I confirm it's no longer broken for me on the latest main. Thank you @yanganto!
