### ISSUE TITLE
Command definitions are locally scoped

### ISSUE THREAD

**Issue by bugabinga** [nushell/nushell#3852]
### Describe the Bug

When defining a command via `def` inside an if-block, it is not globally accessible.

### To Reproduce

Run:
```
if $true { def test [] { echo TEST } } {}
test
error: Command not found
  ┌─ shell:1:1
  │
1 │ test
  │ ^^^^ command test not found

```

### Expected behavior

The output `TEST` upon running the command `test`.

### Configuration

version | pivot | to md
|Column0|Column1|
|-|-|
|version|0.34.0|
|build_os|windows-x86_64|
|rust_version|rustc 1.53.0 (53cb7b09b 2021-06-17)|
|rust_channel|stable-x86_64-pc-windows-msvc (default)|
|cargo_version|cargo 1.53.0 (4369396ce 2021-04-27)|
|pkg_version|0.34.0|
|build_time|2021-07-15 12:13:55|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

### Additional Context

My use case is that `(config).statrtup` equals `source nurc` and inside `nurc` I want to be able to source different scripts depending on the hostname.

e.g.:
```
if (sys).host.hostname == "Windows" { source nurc.some-hostname } {}
```

Command definitions inside these script however are never accessible.

One potential workaround could have been to always source at toplevel like so:
```
source (build-string nurc. (sys).host.hostname)
error: can't load source file
   ┌─ shell:14:8
   │
14 │ source (build-string nurc. (sys).host.hostname)
   │        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't load source file
```
I am unsure why `source` cannot be followed by a subexpression.
Is this intended behaviour?

**Comment by fdncred** [comment]
It would be nice to have an option on `source` like `--global` to tell it where to put this information, but, I believe, the way it currently works is by design.
/cc @jntrnr

**Comment by hustcer** [comment]
Currently should be:
```
if true { def test-cmd [] { echo TEST } } else {}
```
$> test-cmd
```
Error: nu::shell::external_command (link)

  × External command
   ╭─[entry #41:1:1]
 1 │ test-cmd
   · ────┬───
   ·     ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)
```
And I think Command definitions are locally scoped is reasonable, maybe we should close this issue? 
However, the error message is a bit weird now

**Comment by fdncred** [comment]
a def will be scoped. this is by design. you also cannot source with expressions. that is by design as well.
