### ISSUE TITLE
Bugs: GDB set args 

### ISSUE THREAD

**Issue by JJJazzer** [nushell/nushell#3856]
### Describe the Bug

Hi, 
I enter ```set args xxxx``` in gdb, nushell occured an error.
```
Starting program: /home/liuyu/wireshark-2.2.0/tshark -r ./t.pcap
error: exec unexpected -r
  ┌─ shell:1:42
```

### To Reproduce

```
gdb ./tshark
(gdb) set args -r ./t.pcap
(gdb) r
Starting program: /home/liuyu/wireshark-2.2.0/tshark -r ./t.pcap
error: exec unexpected -r
  ┌─ shell:1:42
  │
1 │ exec /home/liuyu/wireshark-2.2.0/tshark -r ./t.pcap
  │                                          ^ unexpected flag (try exec -h)

During startup program exited with code 1.
(gdb)
```

### Expected behavior

It's have no error on bash.
```
Reading symbols from ./tshark...
(gdb) set args -r ./t.pcap
(gdb) r
Starting program: /home/liuyu/wireshark-2.2.0/tshark -r ./t.pcap
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
```

### Screenshots

On nushell
![image](https://user-images.githubusercontent.com/28669475/127278031-839947f5-a9cc-412e-9436-82caa8dc7919.png)

On bash
![image](https://user-images.githubusercontent.com/28669475/127278217-b3ea4c8f-f337-4ac2-ae69-c493f3dc1821.png)

### Configuration

|Column0|Column1|
|-|-|
|version|0.32.0|
|build_os|linux-x86_64|
|rust_version|rustc 1.52.1 (Fedora 1.52.1-1.fc32)|
|cargo_version|cargo 1.52.0|
|pkg_version|0.32.0|
|build_time|2021-06-02 14:25:48|
|build_rust_channel|release|
|features|ctrlc, default, directories, dirs, rustyline, term, which, zip|

**Comment by kubouch** [comment]
Seems like a similar issue to https://github.com/nushell/nushell/issues/2675

**Comment by hanwnz** [comment]
Yes, i think so, 
Sometimes, i run ```exec 'command'````, nushell mybe crashed or exited, i don't know.

![image](https://user-images.githubusercontent.com/28669475/127287616-983753e9-4702-46de-a94c-68d5cbf7bec8.png)

**Comment by fdncred** [comment]
I think the problem is that `exec` is being called which references and internal command and our internal command has no `-r` flag. Which I think is why we get this `error: exec unexpected -r`

**Comment by sholderbach** [comment]
I think this has been fixed through @kubouch 's signature fall through work in #7527 

Reopen if the problem persists
