### ISSUE TITLE
Simplify dataframe contains

### ISSUE THREAD

**Issue by naefl** [nushell/nushell#3859]
### Related Problem

`dataframe contains` right now requires a single flag, `-p` which contains the pattern, and no other arguments.
I think it would be both simpler and more convenient to just allow ommitting the -p

### Describe the solution you'd like

`dataframe contains "mystring"` vs `dataframe contains -p "mystring"`

**Comment by naefl** [comment]
@elferherrera small QoL feature request :) thanks for your awesome work enjoying it thoroughly

**Comment by elferherrera** [comment]
@naefl thanks for using it. The more feedback the better. I think that is something that can be changed rather easy. Try to submit a PR tomorrow morning with the changes
