### ISSUE TITLE
Utils for editing and handling paths

### ISSUE THREAD

**Issue by illeatmyhat** [nushell/nushell#387]
Really a lot of issues rolled into one.
Lacking in utils for dealing with paths, i.e. Unix `dirname`
```
C:\Users\Foobar> which nu | str | explorer
error: Unrecognized type in stream: Primitive(Path("C:\\Users\\Foobar\\.cargo\\bin\\nu.EXE"))
```
Consider taking a look at Python's very cross-platform pathlib library for inspiration.

**Comment by wycats** [comment]
I think this is a great idea.

We probably need to work out how programmers should think about Windows and Unix paths. We could probably make a subset of `/`-based paths "just work" on Windows, but we can't forget about `\\?\` paths and UNC paths in general.

**Comment by wycats** [comment]
I'll also add that Rust's very nice portable path library handles UNC-style paths reasonably well. I don't think we should just cargo cult Rust's path lib into nu, though. I'd be interested in a quick survey of language path libraries to find the best facilities.
