### ISSUE TITLE
Perform event handlers (probes, hooks) RFC

### ISSUE THREAD

**Issue by stevenbarragan** [nushell/nushell#3872]
### Related Problem

There is a lot of tools that rely on been able to perform operations on event driven basis. As described on https://github.com/nushell/nushell/issues/2130. Nu should be able to setup event handlers and execute them accordingly.

### Describe the solution you'd like

-  New `perform` command to setup event's handlers. It stores them in the config file under the `events` key.
-  New `emit` plugin will execute all handlers for the specified event.

```bash
> def callback [] { echo "hello from callback" }

> perform callback --on event-name     // it adds `callback` into the config file under `events.event-name`
> emit event-name                      // it executes commands from the config from events.event-name
  hello from callback

> def callback-with-params [param] { echo $param }

> perform callback-with-params --on event-name
> emit event-name-param "hello from callback with params"
  hello from callback with params

> perform callback --on job-exit 99   // you can specify other params
```

## Some other ideas

```bash
perform callback.nu --on event-name // it can execute nu scripts as well
perform callback.nu 		    // it can execute a nu script or command right away
perform callback.sh --on event-name // it executes scripts from other shells
perform callback.sh                 // it should be able to execute it right away too
perform callback --at 12:00am       // time can be specified
perform callback --at 00**0         // it works with cron syntax as well
```

### Describe alternatives you've considered

Adding a event handler into de config file can be done by the `config` command but I think having `perform` makes it easier to setup.

Talk about state mutation. What thread are the event handlers executed? Can they be executed asynchronously?

### Notes

The config `startup` will be move into `events.startup` instead and executed by `emit startup` instead. We'll make sure to add backwards compatibility and update docs.

 It'll be necessary to "emit" the events in the rights places to add support to events such as "change-dir", or "job-exit", etc.

-- edit: Use `perform` instead of `exec`

**Comment by hustcer** [comment]
+1

**Comment by hustcer** [comment]
Related issue: https://github.com/nushell/nushell/issues/2130

**Comment by sholderbach** [comment]
We now have hooks that are able to react to a limited set of events. 

https://www.nushell.sh/book/hooks.html

Primarily supported is the ability to react to a change of an environment variable.

Feel free to reopen if you want to see specific suggestions how we could improve the interface or the set of supported events implemented.
