### ISSUE TITLE
`each` performs undocumented flattening

### ISSUE THREAD

**Issue by frantisekhanzlikbl** [nushell/nushell#3876]
### Describe the Bug

The `each` command flattens the result of the whole operation, just like `flat_map` does in other languages.

### To Reproduce

```nu
[a, b] | each { [1, 2] }
```

### Expected behavior

The result in a list with two elements, each of which is a list of two elements: `[[1, 2], [1, 2]]`

### Actual behaviour

The result is an array of four elements: `[1, 2, 1, 2]`

### Configuration

key | value
-- | --
version            | 0.34.0
build_os          | linux-x86_64
rust_version    | rustc 1.53.0
cargo_version      | cargo 1.53.0
pkg_version        | 0.34.0
build_time         | 2021-07-23 02:29:07
build_rust_channel | release
features           | clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip
installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath

(formated for readability as the output of `version | pivot` rendered really badly on GitHub)

### Additional Context

Coming from other programming languages, this is *very* confusing, as at least I have never met a `map` or equivalent function that does this. I feel like this should not be the intended behaviour, but if it is, it should be documented (and I am willing to add PR with the documentation).

The flattening also only performed on one layer, as `[a, b] | each { [[1, 2]] }` gives me the result that I would expect.

**Comment by jntrnr** [comment]
This is now fixed in the latest main.
