### ISSUE TITLE
confusing parser error when using `where` with equality comparison

### ISSUE THREAD

**Issue by frantisekhanzlikbl** [nushell/nushell#3877]
### Describe the Bug

I have found a piece of code that produces a very confusing error that I do not know how to resolve.

### To Reproduce

```nu
(echo [0, 1] | where $it == 0)
```

### Expected behavior

The snippet parses just fine and results in array `[0]`.

### Actual behaviour

Nu refuses the snippet with an error

```nu
error: Type Error
    ┌─ shell:112:1
    │
112 │ (echo [0, 1] | where $it == 0)
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Expected environment variable assignment, found (echo [0, 1] | where $it == 0)
```

This also happens when the condition is surrounded by braces: `(echo [0, 1] | where { $it == 0 })`.

This only happens when using the equality comparison operator, i.e. `(echo [0, 1] | where $it > 0)` works as expected.

### Configuration

key | value
-- | --
version            | 0.34.0
build_os          | linux-x86_64
rust_version    | rustc 1.53.0
cargo_version      | cargo 1.53.0
pkg_version        | 0.34.0
build_time         | 2021-07-23 02:29:07
build_rust_channel | release
features           | clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip
installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath

(formatted for readability as the output of `version | pivot` rendered really badly on GitHub)

### Additional Context

Interestingly, the code works as expected when it is not surrounded by parentheses. Unfortunately, I need to use them, as the expression is to be used as an element of a list.

**Comment by fdncred** [comment]
This seems to work for me in 0.34.1 built from the latest main.
```
> echo [0, 1] | where $it == 0
0
```
```
> echo [0, 1] | where $it == 1
1
```
as well as
```
> echo [0, 1] | echo $in.0
0
```

**Comment by jntrnr** [comment]
This is coming from a parser bug, I think. With the parens around the outside, the current parser will treat it as a single token. Then it'll find the `=` inside of that token and assume it's an environment shorthand (like `FOO=BAR`). One way to not parse this way is to check the left and right hand side look like valid environment variables and values.

**Comment by hustcer** [comment]
I think we can close it? @jntrnr

**Comment by jntrnr** [comment]
This should be fixed now
