### ISSUE TITLE
opening a source file for viewing with the internal pager seems to core

### ISSUE THREAD

**Issue by robg204** [nushell/nushell#388]
On deb10, if I open a .rs file for viewing with the internal pager, it displays the first page of the file, the navigation hints at the bottom, and returns me to the shell immediately.  nu_plugin_textview is segfaulting (sigsegv) and tries (and in my case fails) to generate a core.  It also messes up the terminal such that reset is required.

**Comment by jonathandturner** [comment]
A few things to help us figure out why it might be failing:

* are you using the rawkey optional feature?
* what OS and OS version are you using?

**Comment by robg204** [comment]
Installed all features (so yes, rawkey), debian 10, 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux.

**Comment by jonathandturner** [comment]
I'm wondering if `rawkey` is what's causing the problem. If you try without that feature, do you get the see the same crash?

**Comment by robg204** [comment]
Good intuition.  Without rawkey it works fine.

**Comment by jonathandturner** [comment]
May make sense to just take rawkey support out of the text viewer and use it only when absolutely necessary, at least, until it can be made more robust.

**Comment by jonathandturner** [comment]
I wonder if it's an xorg vs wayland vs ?? type of issue, where the technique used only works for certain X servers

**Comment by jonathandturner** [comment]
Moving away from rawkey for textviewing, which should make it more stable
