### ISSUE TITLE
A way to get the current shells / scripts `pid`

### ISSUE THREAD

**Issue by x3rAx** [nushell/nushell#3881]
### Related Problem

If you want to find the parent of the current process it is necessary to either get the current `pid` (`$PID` in bash scripts) and get the parent process of that `pid` or to get the parents `pid` directly from some kind of environment or shell variable (this is the `$PPID` in bash).

### Describe the solution you'd like

It should be possible to get the current shell's or script's `pid` and `ppid` maybe through `$nu.pid` and `$nu.ppid`

### Describe alternatives you've considered

In bash scripts the `pid` and parent `pid` are available as environment variables, but since `nu` has this neat `$nu` variable I think it is better suited for holding these.

**Comment by fdncred** [comment]
That could be added. Right now, you can use nushell's built-in `ps` command to get a processes pid. `ps | where name == nu` or `nu.exe` depending on os.

**Comment by x3rAx** [comment]
Sure, but if there are multiple `nu` processes, there is no way to find the process of the current shell / script. At least I haven't found one.

**Comment by fdncred** [comment]
I'm hesitant about adding such a thing on startup just because everything we add slows down nushell's startup speed. It sounds logical and makes sense to me, i just don't want to slow startup down.

**Comment by x3rAx** [comment]
Wouldn't it be possible to make it lazy, so the `nu` process only looks up it's PID when it is requested and then cache the result? I don't know how a process gets information about it's PID. But based on your concerns about startup speed, I guess that it does not get written to a defined address in memory, but rather the process must ask the kernel what it's PID / PPID is?

If it is not possible to make `$nu.pid` lazily evaluate to the PID, maybe a builtin command can do that?
