### ISSUE TITLE
source command not support file path which include space

### ISSUE THREAD

**Issue by eggcaker** [nushell/nushell#3885]
### Describe the Bug

when source nu scripts which path include some spaces, it's not working 

### To Reproduce

```
source "d:\\hello world\\test.nu"
```

### Expected behavior

should be source success 

### Screenshots

error: can't load source file
    ┌─ shell:351:8
    │
351 │ source "d:\hello world\test.nu"
    │        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't load source file

### Configuration

────┬────────────────────┬────────────────────────────────────────────────────────
 #  │      Column0       │                        Column1
────┼────────────────────┼────────────────────────────────────────────────────────
  0 │ version            │ 0.34.1
  1 │ branch             │ main
  2 │ short_commit       │ d54d7cc4
  3 │ commit_hash        │ d54d7cc4316c485a13940e14ed7ce66783e3d9c3
  4 │ commit_date        │ 2021-07-26 04:36:09
  5 │ build_os           │ windows-x86_64
  6 │ rust_version       │ rustc 1.53.0 (53cb7b09b 2021-06-17)
  7 │ rust_channel       │ stable-x86_64-pc-windows-msvc (default)
  8 │ cargo_version      │ cargo 1.53.0 (4369396ce 2021-04-27)
  9 │ pkg_version        │ 0.34.1
 10 │ build_time         │ 2021-07-26 19:18:40
 11 │ build_rust_channel │ release
 12 │ features           │ ctrlc, dataframe, default, rustyline, term, which, zip
 13 │ installed_plugins  │
────┴────────────────────┴────────────────────────────────────────────────────────

**Comment by jntrnr** [comment]
I'm going to re-open so we can test against engine-q and make sure this works there.

**Comment by jntrnr** [comment]
This looks like it's working in the latest main (which uses the new engine). Going to close, but if you're still seeing issues, please re-open.
