### ISSUE TITLE
Pagination of long tables

### ISSUE THREAD

**Issue by swiftcoder** [nushell/nushell#389]
Commands that output very long tables are awkward, since the column headings are printed at the top (and hence not visible unless you scroll backwards in terminal history).

Ideally for tables that are taller than the current terminal height, only as many rows as fit on screen would print, with a `press SPACE to show more`-style prompt to display the rest of the table.

**Comment by indeyets** [comment]
this could be an option of [autoview](https://github.com/nushell/nushell/blob/master/src/commands/autoview.rs), probably

**Comment by wycats** [comment]
At the beginning of the project (#22) I thought it would be nice to be able to pipe tables into a `cursive`-based table for this reason.

Maybe someone could look into it?

**Comment by dbarnett** [comment]
For a table view, instead of a plain old pager interface, it would be fantastic to drop straight into a list of rows with fuzzy matching.

I had an urge to hook up something like https://github.com/mooz/percol for exploring and manipulating long tables, but couldn't get useful results especially since piping to external commands is so limited. Doing it as a native nushell command could unlock some big wins like fuzzy matching only on a particular column.

**Comment by devurandom** [comment]
Unlike the OP, when I type `ps` on my system (nushell 0.5.0), I get a bunch of tables, each a different number of lines long, with different widths each. That seems even more annoying than a single long table.

I like the idea of being thrown into a `$PAGER` when the output of a built-in command is longer than one screen. I wonder whether something like [bat](https://github.com/sharkdp/bat) could be of use, given that it also displays its output in tables and adds nice colouring to the formats it supports. Maybe it could be taught to accept input from nushell? Or even extended, as was suggested previously, to allow filtering or sorting columns...?

**Comment by waldyrious** [comment]
Just keeping all tables with the same width (and maybe getting rid of the separation between the tables, leaving the heading rows as separators) would improve this a great deal.

In other words, instead of this:
<details>

```
> ps
━━━━┯━━━━━━━┯━━━━━━━━━━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━
 #  │ pid   │ name             │ status  │ cpu
────┼───────┼──────────────────┼─────────┼────────────────────
  0 │ 70813 │ nu_plugin_ps     │ Running │  3.581166000000000
  1 │ 70625 │ nu               │ Running │  0.000000000000000
  2 │ 60758 │ mdworker_shared  │ Running │  0.000000000000000
  3 │ 60676 │ mdworker_shared  │ Running │  0.000000000000000
  4 │ 60674 │ mdworker_shared  │ Running │  0.000000000000000
...
 45 │ 34615 │ passd            │ Running │  0.000000000000000
 46 │ 34612 │ studentd         │ Running │  0.000000000000000
 47 │ 32241 │ MTLCompilerServi │ Running │  0.000000000000000
 48 │ 31270 │ MirrorDisplays   │ Running │  0.000000000000000
 49 │ 31222 │ PowerChime       │ Running │  0.000000000000000
━━━━┷━━━━━━━┷━━━━━━━━━━━━━━━━━━┷━━━━━━━━━┷━━━━━━━━━━━━━━━━━━━━
━━━━┯━━━━━━━┯━━━━━━━━━━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━━
 #  │ pid   │ name             │ status  │ cpu
────┼───────┼──────────────────┼─────────┼─────────────────────
 50 │ 30635 │ rcd              │ Running │   0.000000000000000
 51 │ 30198 │ QuickLookUIServi │ Running │   0.000000000000000
 52 │ 29896 │ ScopedBookmarkAg │ Running │   0.000000000000000
 53 │ 28943 │ MTLCompilerServi │ Running │   0.000000000000000
 54 │ 26217 │ mdwrite          │ Running │   0.000000000000000
 55 │ 23477 │ com.apple.DFRSys │ Running │   0.000000000000000
 56 │ 22315 │ MTLCompilerServi │ Running │   0.000000000000000
 57 │ 21173 │ com.docker.hyper │ Running │   5.457981999999999
 58 │ 21169 │ com.docker.backe │ Running │   0.000000000000000
 59 │ 21168 │ com.docker.drive │ Running │   0.000000000000000
 60 │ 21167 │ com.docker.vpnki │ Running │ 0.02360659000000000
 61 │ 21166 │ com.docker.osxfs │ Running │ 0.04857438000000000
...
```
</details>

I think this would be more readable:
```
> ps
━━━━┯━━━━━━━┯━━━━━━━━━━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━━
 #  │ pid   │ name             │ status  │ cpu
────┼───────┼──────────────────┼─────────┼─────────────────────
  0 │ 70813 │ nu_plugin_ps     │ Running │   3.581166000000000
  1 │ 70625 │ nu               │ Running │   0.000000000000000
  2 │ 60758 │ mdworker_shared  │ Running │   0.000000000000000
  3 │ 60676 │ mdworker_shared  │ Running │   0.000000000000000
  4 │ 60674 │ mdworker_shared  │ Running │   0.000000000000000
...
 45 │ 34615 │ passd            │ Running │   0.000000000000000
 46 │ 34612 │ studentd         │ Running │   0.000000000000000
 47 │ 32241 │ MTLCompilerServi │ Running │   0.000000000000000
 48 │ 31270 │ MirrorDisplays   │ Running │   0.000000000000000
 49 │ 31222 │ PowerChime       │ Running │   0.000000000000000
━━━━┿━━━━━━━┿━━━━━━━━━━━━━━━━━━┿━━━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━
 #  │ pid   │ name             │ status  │ cpu
────┼───────┼──────────────────┼─────────┼─────────────────────
 50 │ 30635 │ rcd              │ Running │   0.000000000000000
 51 │ 30198 │ QuickLookUIServi │ Running │   0.000000000000000
 52 │ 29896 │ ScopedBookmarkAg │ Running │   0.000000000000000
 53 │ 28943 │ MTLCompilerServi │ Running │   0.000000000000000
 54 │ 26217 │ mdwrite          │ Running │   0.000000000000000
 55 │ 23477 │ com.apple.DFRSys │ Running │   0.000000000000000
 56 │ 22315 │ MTLCompilerServi │ Running │   0.000000000000000
 57 │ 21173 │ com.docker.hyper │ Running │   5.457981999999999
 58 │ 21169 │ com.docker.backe │ Running │   0.000000000000000
 59 │ 21168 │ com.docker.drive │ Running │   0.000000000000000
 60 │ 21167 │ com.docker.vpnki │ Running │ 0.02360659000000000
 61 │ 21166 │ com.docker.osxfs │ Running │ 0.04857438000000000
...
```
</details>

**Comment by devurandom** [comment]
Are there pagers that support a fixed heading? So the table heading could be pinned to the top of the screen and only the table content would scroll? That would be an amazing improvement over traditional line based output.

**Comment by fdncred** [comment]
@jonathandturner Is there a way to use the new bat textview to paginate tables? Seems like `ls /Applications | textview` or `ls /Applications | less` would work but it doesn't. Maybe we could treat textview like a generic pager in the future.

**Comment by jansol** [comment]
Whatever solution ends up being used, it should also handle content with very long lines gracefully.

For example when using NixOS and doing `echo $nu.env` you currently get hit with a screen full of nothing but 
`───┴────────────────────────────────────┴───────────┴────` because your PATH is 500 miles long due to the way Nix works (500 miles is an exaggeration, but a screen full of nothing but lines is not) . Both ellipsising long lines to fit everything into the available view size or scrolling sideways would be acceptable solutions to me in situations like this.

**Comment by archaeron** [comment]
you have probably already seen this, but there is now a cross platform pager written in rust:
https://pijul.org/posts/2020-12-09-minus/

**Comment by ilius** [comment]
Converting rows to string with `to` and passing it to standard Unix pager (less/more) works, for example:

    ls | to tsv | less

But then we loose the table structure.

Perhaps as an alternative, you can add a new type to `to` command, like `ls | to table` to produce the same output as the `ls` command, to pass to a pager program.

**Comment by ilius** [comment]
I just found `autoview` command.
To me sounds like it should work with pagers, like `ls | autoview | less`, but it doesn't.

**Comment by fdncred** [comment]
Until we have proper paging, I created a true hack to this and [posted it here](https://github.com/nushell/nu_scripts/blob/main/ls-less.nu) as a script.

**Comment by fdncred** [comment]
at least this presents a way that one can page a table, but i agree, it's a total hack and not what we want going forward. i figured someone would find it useful.

**Comment by ilius** [comment]
Looks like you added implicit pagination.
I think pagination must be explicit (with a `less` command)
Because shell is generally not an interactive user interface (except for the prompt line)
Automatically switching to an interactive program like a pager is not a good idea.
No matter how long the table is, the user still may want to use the scrollbar of his terminal.
If you want to pager, you pipe it with a pager, whether or not the results fit in the screen (Sometimes they fit vertically but not horizontally. Sometimes they fit both ways, but you still don't want them to persist on your terminal screen, just want a preview before saving it to file for example....)

**Comment by jonathandturner** [comment]
@ilius - +1, we want to make it explicit before we ship the next version. We wanted to land the code that was working first, and then improve it. Hopefully it won't be too much trouble to take what we have and then create an explicit pagination command from it.

**Comment by ilius** [comment]
Thanks.
Glad we are on the same "page".

**Comment by jansol** [comment]
Whatever happened to this?
