### ISSUE TITLE
Using Nushell in CI services like GitHub Action

### ISSUE THREAD

**Issue by aminya** [nushell/nushell#3897]
### Related problem

It would be nice if nushell can add a `run-nushell` action to GitHub's marketplace.

https://github.com/marketplace?type=actions&query=nushell+

### Describe the solution you'd like

An action like this:
```
- uses: actions/run-nushell@v1
  with:
    script: |
		ls .
```
This action should setup nu automatically (and cache it for future calls), and then run the given script

Similar to [GitHub Script](https://github.com/actions/github-script)

### Describe alternatives you've considered

Installing nushell on each platform manually using the available package managers, then run the scripts. Not as convenient as my suggested solution though.

### Additional context and details

If I want to write cross-platform actions, one good way is to use nushell.

**Comment by fdncred** [comment]
ya, that would be cool. i really have no idea how to accomplish this, do you?

**Comment by aminya** [comment]
Yes. For GitHub Actions, there are two parts:
1. install and cache nushell. This can be its own separate action (setup-nushell). 

The implementation can use the package managers (e.g. brew, winget, etc), or it can download the binaries using javascript.
[an example for the first approach](https://github.com/turtlesec-no/get-ninja/blob/main/action.yml)
[an example for the second approach](https://github.com/aminya/install-cmake/blob/new-versions-and-arch/src/ninja.ts)

2. spawn the passed nushell script from JavaScript (what GitHub Actions is based on).

The implementation would be something like this:
```js
  const script = core.getInput('script', {required: true}) // get input from the github action yaml file
  execSync(nushellBin, ["--commands", script], { stdio: "inherit" }) // run
```

**Comment by fdncred** [comment]
we'd probably support a PR into a new nushell_ci repo to support this is if you, or someone else, wanted to implement it.

**Comment by aminya** [comment]
Staleness is not a good measure to assume something is fixed.

**Comment by jntrnr** [comment]
@aminya - agreed. I'm wondering if we should just tag issues that need a triage without putting any text. That way, it's mostly for the maintainers to go back through rather than something the person filing the issue needs to do.

**Comment by hustcer** [comment]
I am interested in this issue, maybe I can give it a try

**Comment by fdncred** [comment]
sure

**Comment by hustcer** [comment]
I intend to start dealing with this issue maybe next week

**Comment by hustcer** [comment]
@aminya You can use `setup-nu` now: https://github.com/marketplace/actions/setup-nu
closing this.
