### ISSUE TITLE
Multiline strings are not passed correctly to external programs

### ISSUE THREAD

**Issue by aminya** [nushell/nushell#3898]
### Describe the bug

Multiline strings are not passed correctly to external programs.

### How to reproduce

```
> node -e 'console.log("sss")
console.log("aaaa")'

sss
```

### Expected behavior

I expected
```
sss
aaa
```

### Screenshots

![image](https://user-images.githubusercontent.com/16418197/128336275-0ca6db95-28c1-461d-8241-defa70caaae2.png)

### Configuration

Installed using winget.

```
────┬────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────
 #  │      Column0       │                                         Column1
────┼────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────
  0 │ version            │ 0.35.0
  1 │ short_commit       │ bc682066
  2 │ commit_hash        │ bc682066d8eb756727c38d98ae58a34dd9cb3b38
  3 │ commit_date        │ 2021-08-03 08:01:09
  4 │ build_os           │ windows-x86_64
  5 │ rust_version       │ rustc 1.54.0 (a178d0322 2021-07-26)
  6 │ rust_channel       │ stable-x86_64-pc-windows-msvc (default)
  7 │ cargo_version      │ cargo 1.54.0 (5ae8d74b3 2021-06-22)
  8 │ pkg_version        │ 0.35.0
  9 │ build_time         │ 2021-08-03 08:46:53
 10 │ build_rust_channel │ release
 11 │ features           │ clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip
 12 │ installed_plugins  │ binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps,
    │                    │ query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath
────
```

### Additional context

Might be related to #3765

**Comment by fdncred** [comment]
It looks to me like this may be a parsing bug because the newline appears to be truncating the input. See the two examples, all on one line versus on multiple lines.

![image](https://user-images.githubusercontent.com/343840/128354846-87e0f16f-fc5c-4640-8ba5-443d3866fcc9.png)

**Comment by aminya** [comment]
JavaScript needs ";" in between the commands if you want to put two operations in the same line.

**Comment by fdncred** [comment]
Good point. Thanks.
![image](https://user-images.githubusercontent.com/343840/128364390-f0791302-7d71-45cb-a0b4-3158ebfc2bef.png)
The second one is a bug though I think since the newline isn't being parsed correctly.

**Comment by aminya** [comment]
Since this is a critical bug, could you put it as a priority? I can't use nushell if it cannot call external programs properlly.

**Comment by jntrnr** [comment]
I'm not sure either. My guess is that it's related to the external argument not getting proper escaping on Windows. Since we shell out to cmd, we'd have to set up the call in a way that cmd can take it in.

**Comment by aminya** [comment]
In the short term, I can live with a quick fix.

But in the long run, why should Nushell shell out to CMD? I thought that Nushell is a full shell, and it can spawn the processes directly. Shelling out just adds bugs (this one), complexity (strange quoting rules), and reduces the performance (using Nushell to load another Shell).
