### ISSUE TITLE
Table based directory view

### ISSUE THREAD

**Issue by jaydeland** [nushell/nushell#390]
Really loving this project - I am ecixted to try it out asap.

It would be great to have a vdir command that would give a Ranger or Mignight Commander style way of interacting with the directory.

**Comment by jonathandturner** [comment]
Agreed! There's definitely opportunity here to make a way to navigate tables (and tables inside of tables) a bit more interactive

**Comment by thegedge** [comment]
We should either suggest installing [broot](https://dystroy.org/broot/), or integrate with it 🙂

I think the decision of whether to suggest an external vs include in the code comes down to how many users want a feature.
