### ISSUE TITLE
ls not filter System Volume Information on windows 

### ISSUE THREAD

**Issue by eggcaker** [nushell/nushell#3908]
### Describe the bug

when run ```ls d:\ |where size > 10kb``` , got error 
```
D:\> ls d:\ |where size > 10kb
error: Coercion error
    ┌─ shell:130:15
    │
130 │ ls d:\ |where size > 10kb
    │               ^^^^   ---- filesize(in bytes)
    │               │
    │               nothing
```

### How to reproduce

run ls d:\ | where size > 10kb

### Expected behavior

should be ls with any error 

### Configuration

────────────────────┬───────────────────────────────────────────────────────────────────
 version            │ 0.35.0
 short_commit       │ bc682066
 commit_hash        │ bc682066d8eb756727c38d98ae58a34dd9cb3b38
 commit_date        │ 2021-08-03 08:01:09
 build_os           │ windows-x86_64
 rust_version       │ rustc 1.54.0 (a178d0322 2021-07-26)
 rust_channel       │ stable-x86_64-pc-windows-msvc (default)
 cargo_version      │ cargo 1.54.0 (5ae8d74b3 2021-06-22)
 pkg_version        │ 0.35.0
 build_time         │ 2021-08-03 08:46:53
 build_rust_channel │ release
 features           │ clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash,
                    │ uuid, which, zip
 installed_plugins  │ binaryview, chart bar, chart line, fetch, from bson, from sqlite,
                    │ inc, match, post, ps, query json, s3, selector, start, sys,
                    │ textview, to bson, to sqlite, tree, xpath
────────────────────┴───────────────────────────────────────────────────────────────────

**Comment by fdncred** [comment]
this works on the latest version 0.59.1. closing.
