### ISSUE TITLE
upgrade sysinfo dep

### ISSUE THREAD

**Issue by hedonihilist** [nushell/nushell#3909]
### Describe the bug

When running `ps` in Nu, the names of kernel processes is blank:

```
─────┬─────────┬───────────────────────────────────────────────────────────────────────────────┬─────────────┬─────────┬───────────┬────────────
  #  │   pid   │                                     name                                      │   status    │   cpu   │    mem    │  virtual   
─────┼─────────┼───────────────────────────────────────────────────────────────────────────────┼─────────────┼─────────┼───────────┼────────────
   0 │      12 │                                                                               │ Sleep       │  0.0000 │       0 B │        0 B 
   1 │     690 │ ModemManager                                                                  │ Sleep       │  0.0000 │   4.3 MiB │  230.1 GiB 
   2 │      63 │                                                                               │ Sleep       │  0.0000 │       0 B │        0 B 
   3 │    2136 │ python3.9                                                                     │ Sleep       │  0.0000 │  25.1 MiB │  771.3 GiB 
   4 │    3777 │ python3.9                                                                     │ Sleep       │  0.0000 │  11.1 MiB │   40.2 GiB 
   5 │ 1487541 │                                                                               │ Unknown(73) │  0.0000 │       0 B │        0 B 
   6 │      88 │                                                                               │ Unknown(73) │  0.0000 │       0 B │        0 B 
   7 │ 1567676 │                                                                               │ Unknown(73) │  0.0000 │       0 B │        0 B 
   8 │    2155 │ gsd-disk-utility-notify                                                       │ Sleep       │  0.0000 │   3.5 MiB │  222.9 GiB 
   9 │      44 │                                                                               │ Sleep       │  0.0000 │       0 B │        0 B 
  10 │    4635 │ chrome                                                                        │ Sleep       │  0.0000 │  45.3 MiB │   19.9 TiB 
```

I updated sysinfo dep from v0.16.5 to v0.18.0 and compiled `nu`. The names are displayed as expected. (notice the kworker... processes)

```
─────┬─────────┬──────────────────────────────────────┬─────────────┬─────────┬───────────┬────────────
  #  │   pid   │                 name                 │   status    │   cpu   │    mem    │  virtual   
─────┼─────────┼──────────────────────────────────────┼─────────────┼─────────┼───────────┼────────────
   0 │ 1327980 │ kworker/0:0-events                   │ Unknown(73) │  0.0000 │       0 B │        0 B 
   1 │    4672 │ chrome                               │ Sleep       │  0.0000 │  43.8 MiB │   19.9 TiB 
   2 │     611 │ phtunnel                             │ Sleep       │  0.0000 │   2.5 MiB │    5.3 GiB 
   3 │     126 │ kstrp                                │ Unknown(73) │  0.0000 │       0 B │        0 B 
   4 │    1799 │ gnome-session-b                      │ Sleep       │  0.0000 │   5.7 MiB │  564.4 GiB 
   5 │    4165 │ chrome                               │ Sleep       │  0.0000 │  17.9 MiB │   19.9 TiB 
   6 │    1841 │ gsettings-helpe                      │ Sleep       │  0.0000 │   3.9 MiB │  226.7 GiB 
   7 │ 1487542 │ kworker/5:0-events                   │ Unknown(73) │  0.0000 │       0 B │        0 B 
   8 │    3936 │ gpg-agent                            │ Sleep       │  0.0000 │   2.0 MiB │  150.7 GiB 
   9 │     106 │ scsi_eh_2                            │ Sleep       │  0.0000 │       0 B │        0 B 
  10 │ 1394203 │ zsh                                  │ Sleep       │  0.0000 │   7.3 MiB │   15.3 GiB 
```

### How to reproduce

1. compile `nu` V0.35 with sysinfo dep 0.16.5
2. run `ps` in Nu

### Expected behavior

displaying names of each process correctly, rather than showing a blank

### Configuration

───┬────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                                                              Column1                                                                              
───┼────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.34.0                                                                                                                                                            
 1 │ build_os           │ linux-x86_64                                                                                                                                                      
 2 │ rust_version       │ rustc 1.53.0                                                                                                                                                      
 3 │ cargo_version      │ cargo 1.53.0                                                                                                                                                      
 4 │ pkg_version        │ 0.34.0                                                                                                                                                            
 5 │ build_time         │ 2021-07-15 04:50:50                                                                                                                                               
 6 │ build_rust_channel │ release                                                                                                                                                           
 7 │ features           │ clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                
 8 │ installed_plugins  │ binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, 
   │                    │ xpath                                                                                                                                                             
───┴────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by sanxiyn** [comment]
sysinfo dep is now at v0.23.0 and ps displays kernel processes correctly.

**Comment by fdncred** [comment]
@hedonihilist @sanxiyn we're on 0.22.2 now, could probably update to 0.23.2 as well but we've also changed ps quite a bit. please test to see how it works for you.
