### ISSUE TITLE
Vim and NVim

### ISSUE THREAD

**Issue by jaydeland** [nushell/nushell#391]
Is it possible to use shell based apps in Nu? Or perhaps integrate vim as the base editor in the shell.

**Comment by jonathandturner** [comment]
We don't have a Nu script, yet, but it's something that's planned for the future.

Trying to pick a default editor sounds very dangerous :) (emacs vs vi wars and all that)

**Comment by dbarnett** [comment]
Usually the desktop environment configures which editor to use for what, not the shell. Do you have an example of what behavior you'd want to see?

**Comment by rrichardson** [comment]
How about just vim keystrokes for line editing?   I am not sure if I will ever be able to train myself not to use  `escape,  0, w`  to jump to the second word on a line.

**Comment by dbarnett** [comment]
@rrichardson Dupe of #354 if it's just about vi mode on the shell (which already has a pull request out to solve it). @jaydeland was there anything else you had in mind for this issue?

**Comment by wycats** [comment]
For future readers, commands like `vim` and `emacs`, as well as commands like `git` that implicitly open an editor, are expected to "just work".

We should address #354 ASAP.

**Comment by Silentdoer** [comment]
may be can use rust amp for default editor
