### ISSUE TITLE
history.txt file messed up

### ISSUE THREAD

**Issue by ssrlive** [nushell/nushell#3910]
### Describe the bug

I use nushell in windows with `windows terminal`, I find that the %localuserdata%/nushell/nu/data/history.txt is corrupted always when I open 2 processes of NuShell. Like the screenshot. please fix it.

### How to reproduce

 the %localuserdata%/nushell/nu/data/history.txt is corrupted always when I open 2 processes of NuShell.

### Expected behavior

The history.txt is protected safe.

### Screenshots

![image](https://user-images.githubusercontent.com/30760636/128678820-94f3ed42-ea24-45a8-a104-66cb386db082.png)

**Comment by stormasm** [comment]
Unfortunately this is a known issue and there is a solution on the horizon for sure...   Eventually we will integrate reedline into nushell and the history bug will go away --- so we are holding off on investing any energy into fixing the bug ---- and we are pretty sure / but not positive it is out of our control as it might possibly live inside rustyline.  Of course if you care to tackle this now that would be great too.  Thank you for your patience on this issue...

**Comment by lily-mara** [comment]
This corruption issue may be resolved by #3916

**Comment by stormasm** [comment]
great news ! thanks for digging into this issue further and helping out...  will be interesting to see if this clears up the bug...  I will stay tuned to this issue...

**Comment by lily-mara** [comment]
FWIW I have been running the latest main commit for the past few days and have not seen this history bug happen again. If you want do that, you can clone the repository and try it out.

```
$ git clone https://github.com/nushell/nushell.git
$ cd nushell
$ cargo install --path . --force
```

**Comment by ssrlive** [comment]
Perfect! Well done.

**Comment by ssrlive** [comment]
No No No, the issue exists yet. It's so bad.
![image](https://user-images.githubusercontent.com/30760636/129524765-00478d9e-cde1-4704-bb28-03bedc3c661f.png)

**Comment by jntrnr** [comment]
@ssrlive you may need to delete the old history from outside of Nushell without Nushell running

**Comment by ssrlive** [comment]
It's NOT work. It's NOT the point. @jntrnr

**Comment by jntrnr** [comment]
@ssrlive - please calm down. We're all volunteers here trying to improve Nushell.

**Comment by ssrlive** [comment]
I am very calm. Maybe the issue is caused by rustyline itself.

**Comment by jntrnr** [comment]
There's a fix in place in rustyline https://github.com/kkawakam/rustyline/pull/560. We're hoping they'll do a release so we can update nushell. With luck, that will fix it.

**Comment by ssrlive** [comment]
I have changed this line 
https://github.com/nushell/nushell/blob/bc682066d8eb756727c38d98ae58a34dd9cb3b38/crates/nu-cli/Cargo.toml#L29
to 
```
rustyline = { git="https://github.com/kkawakam/rustyline.git", optional=true }
```
and `cargo update` then `cargo build --release` to test it. hope this can help.

**Comment by stormasm** [comment]
ok great idea !! keep us posted on your findings...

**Comment by ssrlive** [comment]
fixed. close.
