### ISSUE TITLE
Docs should explain early where to find `config path`

### ISSUE THREAD

**Issue by thomasaarholt** [nushell/nushell#3911]
### Related problem

New user to nushell here. Like a lot of new users (I think), upon installing a new shell I was interested in customizing it. I looked up the ["Configuration"](https://www.nushell.sh/book/configuration.html#nushell-configuration-with-config-toml) chapter in the Nu book, and it took me longer than expected to find out where to find the `config.toml` file. 

### Describe the solution you'd like

A simple "The path to the config file can be found by calling `config path`" would be nice to have after the very first paragraph after "Nushell Configuration with ´config.toml´"

**Comment by jafriyie1** [comment]
Ah I'm sorry that you dealt with this. I am also a new user to nushell and I ran into a similar issue. I can add this to the configuration chapter if you'd like. @fdncred is that ok with you?

**Comment by thomasaarholt** [comment]
Nice one! Thanks for that :)

**Comment by fdncred** [comment]
Sounds good. Go for it @jafriyie1
