### ISSUE TITLE
Can't init fast terminal task with vscode‘s npm script on Windows

### ISSUE THREAD

**Issue by ShiftWatchOut** [nushell/nushell#3912]
### Describe the bug

When I use my favorite shell in my favorite code editor, they got an unusual problem as the Title says.
![image](https://user-images.githubusercontent.com/23012269/128967608-242ac966-0bc3-4d47-bf12-3d11efc7ec72.png)

Then I glimpse [the source code of VSC](https://github.com/microsoft/vscode/blob/08b1c2e68c980fac5837ef9ff3e024fad5847046/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1112), found that they add a `'/d'` and `'/c'` after the command, and it seems like nushell can't resolve this arg yet.

### How to reproduce

1. PC Platform: Windows 10 20H2,  VSC version: 1.59.0,  Nushell version: 0.35.0.
2. VSC setting.json
   ```json
    {
           ...
            "terminal.integrated.profiles.windows": {
            "nushell": {
                "path": "C:\\Users\\Macrohard\\.cargo\\bin\\nu.exe",
                "args": [],
            },
            "PowerShell": {
                "source": "PowerShell",
                "icon": "terminal-powershell"
            },
            "Command Prompt": {
                "path": [
                    "${env:windir}\\Sysnative\\cmd.exe",
                    "${env:windir}\\System32\\cmd.exe"
                ],
                "args": [],
                "icon": "terminal-cmd"
            },
            "Git Bash": {
                "source": "Git Bash"
            }
        },
        "terminal.integrated.defaultProfile.windows": "nushell",
    }
   ```
3. Prepare a modern JS project with npm script configured, launch any script by a click on VSC's npm script panel.

### Expected behavior

I wonder if it is my fault to set wrong configuration on VSC, can anybody show me the right one, it would be so nice, or is it possible for Nushell to handle this `/d` of `/c` arg

### Configuration

───┬────────────────────┬────────────────────────────────────────────────────────
 # │      Column0       │                        Column1
───┼────────────────────┼────────────────────────────────────────────────────────
 0 │ version            │ 0.35.0
 1 │ build_os           │ windows-x86_64
 2 │ rust_version       │ rustc 1.53.0 (53cb7b09b 2021-06-17)
 3 │ rust_channel       │ stable-x86_64-pc-windows-msvc (default)
 4 │ cargo_version      │ cargo 1.53.0 (4369396ce 2021-04-27)
 5 │ pkg_version        │ 0.35.0
 6 │ build_time         │ 2021-08-10 10:23:04
 7 │ build_rust_channel │ release
 8 │ features           │ ctrlc, dataframe, default, rustyline, term, which, zip
 9 │ installed_plugins  │ fetch, match, post, ps, sys
───┴────────────────────┴────────────────────────────────────────────────────────

**Comment by alextremblay** [comment]
I don't think nushell should be adding custom logic to handle /d and /c command line flags, those are historical windows-isms.

I personally think you should file a bug with VSCode. I think it's an error for VSCode to assume all shells in windows use /c for command invokation and /d for... whatever that does

**Comment by ShiftWatchOut** [comment]
@stefnotch Not yet, and it seems that Nushell is still not fully useable in VSCode. I'm using Git Bash insde VSCode now, sad😢.
