### ISSUE TITLE
Cursor disappearing from view after narrowing a table down to one field (Windows)

### ISSUE THREAD

**Issue by samuelludwig** [nushell/nushell#393]
On Windows 10

On two different terminals (I've tried it on both the new Windows Terminal and Cmder) whenever I have narrowed a table down to one single field/entry (via say `ls | get name | nth 4`) my cursor disappears and is no longer visible. I can still navigate the terminal and characters like normal, but I can no longer see the cursor itself, which makes discerning where I'm putting characters difficult.

**Comment by jonathandturner** [comment]
Do you have a screenshot of what this looks like, by chance? Not sure exactly what you mean
