### ISSUE TITLE
Default values for arguments to custom commands

### ISSUE THREAD

**Issue by NiklasJonsson** [nushell/nushell#3930]
### Describe the solution you'd like

It would be nice to have a default argument support, e.g.:

```
def t1 [--x = 10] { echo $x }
def t2 [x = 10] { echo $x }
```

### Describe alternatives you've considered

Both of these work as well:

```
if $x == $nothing {
 let x = 10
}{}
```
```
let x = ($x | empty? -b { 10 })
```

**Comment by hustcer** [comment]
It's already supported by this PR: https://github.com/nushell/nushell/pull/4770
