### ISSUE TITLE
|...rest| in a block does not get bound

### ISSUE THREAD

**Issue by strega-nil** [nushell/nushell#3944]
### Describe the bug

In a block, the parameter list `|...rest|` does not bind anything.

### How to reproduce

```nu
> { |...rest| echo $rest } foo bar
```

### Expected behavior

This should output

|index|item|
|-|-|
|0|foo|
|1|bar|

### Screenshots

It instead outputs nothing.

### Configuration

|Column0|Column1|
|-|-|
|version|0.35.0|
|build_os|windows-x86_64|
|rust_version|rustc 1.54.0 (a178d0322 2021-07-26)|
|rust_channel|stable-x86_64-pc-windows-msvc (default)|
|cargo_version|cargo 1.54.0 (5ae8d74b3 2021-06-22)|
|pkg_version|0.35.0|
|build_time|2021-08-19 17:34:15 -07:00|
|build_rust_channel|release|
|features|ctrlc, dataframe, default, rustyline, term, which, zip|
|installed_plugins|fetch, match, post, ps, sys|

**Comment by fdncred** [comment]
I'm confused by this issue. `...rest` isn't a command yet in nushell, it's a parameter to a custom command. are you suggesting that we make it a command? sorry i'm missing your point. :(

**Comment by strega-nil** [comment]
@fdncred the way that parameter binding works in a block is:

```nu
{ |x, y| ... } foo bar
```

in the block, `$x = foo` and `$y = bar`.

**Comment by kubouch** [comment]
It took me a while to realize what's wrong:
```
> def foo [...rest] {
    echo $rest
}

> foo 10 20 30
  0   10
  1   20
  2   30

> { |...rest| echo $rest } 10 20 30
error: Variable not in scope
   ┌─ shell:23:18
   │
23 │ { |...rest| echo $rest } 10 20 30
   │                  ^^^^^ unknown variable: $rest
```

The last two outputs should be identical.

@fdncred `{ |...rest| echo $rest } foo bar` means that you define a block and immediately call it with arguments "foo" and "bar".

**Comment by fdncred** [comment]
i didn't realize that was supposed to work. :)

**Comment by jntrnr** [comment]
This works with the latest main now:

```
> do { |...rest| echo $rest } foo bar
```
