### ISSUE TITLE
Characters missing from output

### ISSUE THREAD

**Issue by jakobnissen** [nushell/nushell#3946]
### Describe the bug

Characters missing from output spuriously. Unfortunately it seems to be random, perhaps a race condition, so I was not able to consistently reproduce it. When operating on tens of thousands of lines, it did happen nearly every time, but in a different manner each time

### How to reproduce

I was able to consistently create it with a 40k row CSV file `bn.csv`
```
$ head -1 ./bn.csv > ./bnfilt.csv
$ cat ./bn.csv | rg "SAG" - | rg "V00" - >> bnfilt.csv
```
Single characters got deleted, consistently. I then reran the same lines in Bash, and it worked.

### Expected behavior

Not delete any characters

### Configuration

```
───┬────────────────────┬────────────────────────────────────────────────────────
 # │      Column0       │                        Column1
───┼────────────────────┼────────────────────────────────────────────────────────
 0 │ version            │ 0.35.0
 1 │ build_os           │ linux-x86_64
 2 │ rust_version       │ rustc 1.56.0-nightly (8007b506a 2021-08-14)
 3 │ rust_channel       │ nightly-x86_64-unknown-linux-gnu (default)
 4 │ cargo_version      │ cargo 1.56.0-nightly (b51439fd8 2021-08-09)
 5 │ pkg_version        │ 0.35.0
 6 │ build_time         │ 2021-08-15 15:42:54 +02:00
 7 │ build_rust_channel │ release
 8 │ features           │ ctrlc, dataframe, default, rustyline, term, which, zip
 9 │ installed_plugins  │ fetch, match, post, ps, sys, tree
───┴────────────────────┴────────────────────────────────────────────────────────
```

**Comment by fdncred** [comment]
I don't believe redirection like this, using `>` or `>>` is supported by nushell.

**Comment by rgwood** [comment]
Closing as this never got a response from the original author and Nu doesn't support redirection like that.

Feel free to reopen if someone can still reproduce this.
