### ISSUE TITLE
add more sequence type  to seq command 

### ISSUE THREAD

**Issue by eggcaker** [nushell/nushell#3951]
### Related problem

I'm try to generate a table with data a to z, or a to e 

### Describe the solution you'd like

I think if the seq can support more sequence type like a-z , even more like monday-sunday something real sequence in the world 

feel free to close  this issue just ask for fun.

**Comment by davidp918** [comment]
Hi, I'd like to work on this issue

**Comment by arbaregni** [comment]
HI are you still working on this issue?

I would like to give it a go as well.

**Comment by elferherrera** [comment]
@arbaregni I think nobody if working on it. Wanna have a go?

**Comment by davidp918** [comment]
@arbaregni Sure, though I was half way through but don't think I will have time to complete it. If you want to see my changes I can share it with you.

**Comment by arbaregni** [comment]
@elferherrera Yes, absolutely!

@davidp918 Yeah, if you want to share those, great.

**Comment by arbaregni** [comment]
sorry, yeah I'm still working on it I've just been somewhat busy this past
month

**Comment by GabrielBG0** [comment]
no problem, just checking

**Comment by hustcer** [comment]
I think we can close this issue after: https://github.com/nushell/nushell/pull/5453, as monday to sunday is less important
