### ISSUE TITLE
Tab Completion takes 10+ seconds

### ISSUE THREAD

**Issue by FugiTech** [nushell/nushell#3955]
### Describe the bug

Pressing TAB to auto-complete a command or parameter takes around 12 seconds to return. When it finishes the result is as expected, it simply takes much longer than expected to complete.

### How to reproduce

1. Type `cd ~/.ss` into prompt
2. Press TAB
3. Wait 12 seconds
4. Prompt should now say `cd ~/.ssh/`

### Expected behavior

I expect pressing TAB to complete in under a second, ideally near-instantly

### Configuration

```
───┬────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                                                              Column1
───┼────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.35.0
 1 │ build_os           │ linux-x86_64
 2 │ rust_version       │ rustc 1.54.0 (a178d0322 2021-07-26)
 3 │ rust_channel       │ stable-x86_64-unknown-linux-gnu (default)
 4 │ cargo_version      │ cargo 1.54.0 (5ae8d74b3 2021-06-22)
 5 │ pkg_version        │ 0.35.0
 6 │ build_time         │ 2021-08-13 01:57:35 -07:00
 7 │ build_rust_channel │ release
 8 │ features           │ clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip
 9 │ installed_plugins  │ binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree,
   │                    │ xpath
───┴────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

### Additional context

I'm running nushell 0.35 in Ubuntu 20.04 LTS via WSL2 with the Starship prompt. I tried searching for a similar issue and couldn't find anything, so apologies if it turns out I've just done something incredibly dumb. I've really enjoyed using nushell for the past week and greatly appreciate y'all making such a fantastic terminal experience :)

**Comment by fdncred** [comment]
This is a known issue with WSL. https://github.com/nushell/nushell/issues/2759

**Comment by jntrnr** [comment]
Reopening for now to make this easier for folks to find

**Comment by aminya** [comment]
For me, on native Windows, path autocomplete is usually slow for the first time (~2-3 seconds). It seems that some module is being loaded when autocomplete happens for the first time.

**Comment by fdncred** [comment]
WSL completions for windows paths will be slower than native because having to traverse outside the vm to a ntfs file system, which is much slower than ext4. however, having said that. for funsies, i added the windows path and another windows path to my WSL fish path and it's pretty responsive.

**Comment by herlon214** [comment]
This https://github.com/nushell/nushell/pull/5114 should help a little bit with that, so you don't need to face the slowness for every character you type

**Comment by hustcer** [comment]
@FugiTech Can you try it with the latest nu version? Do you still have such issue? Thx

**Comment by jntrnr** [comment]
Going ahead and closing this, as I think we've done what we can on the Nushell side. Once WSL fixes its performance issues, it should also naturally improve.
