### ISSUE TITLE
Tree format for communication between utils

### ISSUE THREAD

**Issue by nin-jin** [nushell/nushell#3956]
### Related problem

- Utils should produce user readable output.
- But this output should be program readable too for pipelining.
- Not only tables, but any trees.
- And processing should be fast, without escaping.

### Describe the solution you'd like

I have developed a format [Tree](https://github.com/nin-jin/tree.d), which optimized for these use cases.

[An example](https://github.com/nin-jin/slides/tree/master/tree#tree-%D0%BA%D0%B0%D0%BA-%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB-%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D1%8F) of what we can come to in shell. You can also find a lot of details about the format there.

### Describe alternatives you've considered

JSON - popular alternative, but it's unreadable by users. For example, there are problems with the representation of multi-line text.

**Comment by rgwood** [comment]
I think this could be a Nushell plugin, feel free to reach out if you need any help writing one. These days we're trying to slim down Nu's feature set and I don't think we'd want this built into Nu right now.
