### ISSUE TITLE
Items in history completion can't be tab completed

### ISSUE THREAD

**Issue by Firstyear** [nushell/nushell#3959]
### Describe the bug

When running a command that is in the history, it appears with a greyed out text. IE `git sta` shows `git status` with the `tus` in light grey, to indicate that the history knows this is a command we have run before. However, you can`t complete this component. 

### How to reproduce

1. run 'git status'
2. run 'git sta' and hit tab

### Expected behavior

Complete the command from history.

### Screenshots

![Screen Shot 2021-08-24 at 12 20 13](https://user-images.githubusercontent.com/271005/130545531-2d237ca6-b0f2-426a-a3d3-9140120a5875.png)

### Configuration

───┬────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 # │      Column0       │                                                                                 Column1
───┼────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 0 │ version            │ 0.35.0
 1 │ build_os           │ macos-x86_64
 2 │ rust_version       │ rustc 1.53.0
 3 │ cargo_version      │ cargo 1.53.0
 4 │ pkg_version        │ 0.35.0
 5 │ build_time         │ 2021-08-04 04:55:04
 6 │ build_rust_channel │ release
 7 │ features           │ clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip
 8 │ installed_plugins  │ binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath
───┴────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by filaretov** [comment]
I think that's a Rustyline feature called "hints" and the associated action is called "CompleteHint" in the keybindings config, [here it is in the example keybindings file](https://github.com/nushell/nushell/blob/487fafbca3aa594b8de3bc9379ac6ec6ba5fe767/docs/sample_config/keybindings.yml#L66).

For some reason, "right arrow" (without Shift) works just fine on my machine, without having it bound. I'm guessing you can set it to something else in your own `keybindings.yml` file, though I'm not sure whether you can use TAB for completing hints as well as regular completion at the same time.

It did take me a while to figure out how to use the hint completion as well. Maybe we need a quick introduction in the book on the line editor?

**Comment by Firstyear** [comment]
I think so, because at the moment there doesn't seem to be much about that present in the book :)

**Comment by Firstyear** [comment]
Ahhhh it seems if you set that key bind you break all other uses of Tab complete XD

**Comment by filaretov** [comment]
Yup, seems like it :D To be fair, it's probably good having them on separate keybindings, otherwise it'd be fairly difficult to correctly guess whether a user wants to complete the hint or use other completions.

I can open an issue on the docs repo to document line editing a bit more. Does this solve your issue?

**Comment by Firstyear** [comment]
Kind-of? I think it should be possible to complete from multiple sources history or paths at the same time, so the fact that changing it to tab breaks it seems wrong to me, and using right arrow feels unnatural?

**Comment by filaretov** [comment]
It seems conditional bindings are now possible in Rustyline with  kkawakam/rustyline#492, but I'm not sure whether that's configurable via `keybindings.yml`.

Also, is using a `keybindings.yml` file for configuration implemented in Nushell or does it come with Rustyline?

Would it be possible to expose some conditional flags in `keybindings.yml` to make this possible?

I'm also used to Ctrl-E for hint completion and going to the end of the line, depending on whether there's a displayed hint. That would be very nice to have. That issue was discussed in Rustyline and an example setup for it can be found [here](https://github.com/kkawakam/rustyline/blob/master/examples/custom_key_bindings.rs#L45-L51).

**Comment by fdncred** [comment]
The intent is to use `right-arrow` by default to complete hints. This is the default without a keybindings.yml file. If you use the sample one, shift-right-arrow should work.

Yes, keybindings.yml is implemented in nushell, it does not come with rustyline. 

Yes, it could be augmented however with so much work going into reedline right now I'm not sure it's worth the effort. Our plan is to eventually switch to using reedline as our line editor as soon as it is feasible. So, it may be good for one to check out the [reeline repo](https://github.com/jntrnr/reedline) and contribute things you want there.

Can we close this issue or are there more questions?

**Comment by Firstyear** [comment]
It sounds like this is already known as a pain point, so if this is captured as a use case and feature for reedline then I'm all good to close it. 

It's worth saying, nushell looks really great, and I can't wait for it to be my main shell of choice. Great work 🎉

**Comment by sholderbach** [comment]
For the new `reedline` line editor by default `<Right arrow>` triggers the `HistoryHintComplete` event and `CTRL+<Right Arrow>` triggers a partial completion in the form of `HistoryHintWordComplete`. In theory tab can be rewired to take precedence over the completions but this would interfere with the normal tab completions if the cursor is at the end of the line
