### ISSUE TITLE
`max_history_size` not working

### ISSUE THREAD

**Issue by ssrlive** [nushell/nushell#3965]
### Describe the bug

I try to change the max history count from 100 to 1000, but it don't working.
```
config set max_history_size 1000
```

### How to reproduce

open `nushell` and key in some commands beyond 100 records.

### Expected behavior

I hope we can store more history records.

### Screenshots

![image](https://user-images.githubusercontent.com/30760636/130724956-b0c64254-fe3a-4b7e-8a2a-3c80e2af77e5.png)

**Comment by fdncred** [comment]
This is because `max_history_size` needs to be in the `[line_editor]` section of the config.toml.
![image](https://user-images.githubusercontent.com/343840/130798572-06538728-81a7-40e7-9a39-16a225624283.png)

please re-open if this doesn't address your concern.
