### ISSUE TITLE
Get the exit status of last executed command

### ISSUE THREAD

**Issue by theEndurance-del** [nushell/nushell#3970]
### Related problem

In both bash and zsh we have an option to display the exit status for the previously executed command to know if it was successful or not. This is pretty handy if either the command gives not output but doesn't (happened to me while using `light` command) or the output is tremendous and you just want to determine if it was a success or not.

### Describe the solution you'd like

If it would be possible please add an options to view the exit status, which in both zsh and bash, is displayed by the `$?` variable.

**Comment by ChrisDenton** [comment]
More prior art: Powershell uses `$LastExitCode` for the actual code and `$?` for a boolean success/failure.

**Comment by theEndurance-del** [comment]
> More prior art: Powershell uses `$LastExitCode` for the actual code and `$?` for a boolean success/failure.

Yup, it can also be done like having a single row table containing both the exit code and whether if the command executed was a success or a failure.

**Comment by hustcer** [comment]
`$env.LAST_EXIT_CODE` has already been supported on the latest main. So I will close this, please reopen if you still have issues.
