### ISSUE TITLE
Need a way to check if a column exists in a table

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#3979]
### Related problem

I want to check if a user has set the `prompt` variable under `$nu.config`, or if the user has set `PROMPT_STRING` under `$nu.env`. Unfortunately, there doesn't seem to be a way of doing this.

### Describe the solution you'd like

A way to check if a column is set would be great. I would have thought that this was the purpose of `empty?`, but `empty?` doesn't distinguish between 0-length strings and unset fields. `$nothing` throws type coercion errors when I try to use that.

### Describe alternatives you've considered

The closest I got was this:
```
$nu.config | select prompt | empty?
```

This returns `$true` if `prompt` is unset OR set to an empty string, and `$false` if `prompt` is set to anything else. What I'd like is something that returns `$true` if prompt is unset, and `$false` if `prompt` is set to anything at all (including an empty string).

### Additional context and details

I'm trying to use this in [zoxide](https://github.com/ajeetdsouza/zoxide)'s Nushell plugin. See here: https://github.com/ajeetdsouza/zoxide/blob/2a5c8ca7555cb759f8982bb0a81fccb007614610/templates/nushell.txt#L36

**Comment by fdncred** [comment]
> What I'd like is something that returns $true if prompt is unset, and $false if prompt is set to anything at all (including an empty string).

* $true if prompt is unset
`(config | select prompt | empty?) == $true`

* $false if it is set to anything at all
`(config | select prompt | empty?) == $false`

@ajeetdsouza does that cover it? are there specific cases where these don't work?

**Comment by ajeetdsouza** [comment]
Nope. Here's an example:

```
>> unlet-env foo
>> ($nu.env | select foo | empty?) == $true
$true # expected $true

>> let-env foo = ''
>> ($nu.env | select foo | empty?) == $true
$true # expected $false
```

**Comment by filaretov** [comment]
This was discussed recently on the Discord. If I remember correctly, one of the proposed solutions would be to make comparison more lenient, so it doesn't raise type coercion errors.

Alternatively, maybe something like `nothing?` could be implemented?

I was experiencing the same issue and am also interested in a solution to this problem.

**Comment by fdncred** [comment]
So, it seems like the only real problem is if the env var is set to an empty string, if i'm understanding correctly.
one could do something like this.

1. env var exists with some text test 
```
> let-env foo = 'some prompt text'
> let has_prompt_text = ($nu.env | select foo | get foo | split chars | length) > 0
> $has_promp_text
true
```

2. env var exists with an empty string
```
> let-env foo2 = ''
> let exists_but_empty = ($nu.env | select foo2 | get foo2 | split chars | length) == 0
> $exists_but_empty
true
```

3. env var does not exist at all
```
> let no_env_var = ($nu.env | select foo3 | empty?)
> $no_env_var
true

**Comment by ajeetdsouza** [comment]
@fdncred AFAICT, none of these commands actually distinguish between a variable that has been set to an empty string, and a variable that has been unset.

**Comment by fdncred** [comment]
I'm not following - number 2 is a var with an empty string and number 3 is an unset var.

**Comment by ajeetdsouza** [comment]
Both number 2 and number 3 return `true` in the empty string as well as the unset var case.

**Comment by xanderificnl** [comment]
I would like to second the request for an unambiguous way to check if a variable is set.

As far as I know, the 'only' safe way to check if `$nu.config.startup` is empty, is by doing:

```config | select startup | empty? | first```

Without `first` the command can either return `true` or a `table` containing one more multiple `false` values. So we might end up with a coercion error. So adding `first` ensures we're either picking `true` or the first value of the `table` which is always `false`. 

What _really_ bothers me (priorities!) is that the command - the way I read it - implies I'm looking for an empty startup line, or that I'm assuming the variable exist.

In reality, I'm trying to do something like this:
```
# Create startup if it doesn't exist.
if ($nu.config.startup | exists?) == $false { config set ... } {}

config set startup (config get startup | append "alias nuopen = open" | append "alias open = ^open")
```

**Comment by hustcer** [comment]
Related issue: https://github.com/nushell/nushell/issues/4307

**Comment by fdncred** [comment]
One way to check for a particular column is to use the `columns` command like `ls | columns | where $it == size`. Seems like this issue should be closed to me.

**Comment by schmitzli** [comment]
The earlier answers are quite outdated, the config settings are discussed in the linked case.
For the original question the previous answer can work like this to produce a boolean result.

`help commands | columns | any {|c| $c == usage} `

an alternative (on records, which could even check the content type) would be to use describe 

`help commands | first | describe | str contains ' usage: string,'`

**Comment by mon-jai** [comment]
> * $true if prompt is unset
>   `(config | select prompt | empty?) == $true`
> * $false if it is set to anything at all
>   `(config | select prompt | empty?) == $false`

It doesn't seem to work now

```
~〉{ "foo": "Hello world" } | select bar
Error: nu::shell::column_not_found (link)

  × Cannot find column
   ╭─[entry #23:1:1]
 1 │ { "foo": "Hello world" } | select bar
   · ────────────┬───────────          ─┬─
   ·             │                      ╰── cannot find column 'bar'
   ·             ╰── value originates here
   ╰────
```

**Comment by fdncred** [comment]
You can use `'bar' in record` where record is a record or list or maybe a table. I can't remember.

**Comment by fdncred** [comment]
We definitely have this with `in` and with utilizing the `columns` command when needed. Closing for now. Please re-open if it's not clear with your use case.

**Comment by cig0** [comment]
> You can use `'bar' in record` where record is a record or list or maybe a table. I can't remember.

It took me a few minutes to figure out how to implement this, so I'm leaving an example for anyone else getting here looking for the answer.
In my case, I want to check if a remote shell session spawned the shell, and if so, enable the SSH agent:
```
if ('SSH_CLIENT' in $env) {
   ssh-agent-setup
}
```

HTH!
