### ISSUE TITLE
`table-pager` feature compilation is broken again

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#3981]
### Describe the bug

The underlying pager crate `minus` doesn't compile on rust 1.54.

### How to reproduce

1. `cargo build --features=table-pager`
2. Observe error about sync and std_async

### Expected behavior

Expected smooth compilation

### Configuration

(compiled with --features=extra)
|key|value|
|-|-|
|version|0.36.1|
|branch|main|
|short_commit|66cedf0b|
|commit_hash|66cedf0b3aa4ff4e9b37313ac7a629f4069acf0a|
|commit_date|2021-08-29 13:40:28 +00:00|
|build_os|linux-x86_64|
|rust_version|rustc 1.54.0 (a178d0322 2021-07-26)|
|rust_channel|stable (default)|
|cargo_version|cargo 1.54.0 (5ae8d74b3 2021-06-22)|
|pkg_version|0.36.1|
|build_time|2021-08-31 23:53:51 +03:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

### Additional context

minus version 3.4.0

**Comment by Th3Kh3d1v3** [comment]
There is a 4.0+ version of minus now.

**Comment by karlmdavis** [comment]
Any chance this might land back in, at some point? I ran into the lack of this feature (running `ls -la ~`) almost immediately after first installing `nu` today, so FWIW it seems likely that it's an important polish issue for new users.

**Comment by jntrnr** [comment]
@karlmdavis things like `ls -la ~ | less` should work well in the latest main

**Comment by karlmdavis** [comment]
Ahh, okay. I'll just keep an eye out for the next release, then. Thanks!
