### ISSUE TITLE
Converting JSON object into CSV

### ISSUE THREAD

**Issue by jussiarpalahti** [nushell/nushell#3982]
### Describe the bug

I have JSON object that I'd like to convert to CSV. Object keys should become one column and object values another on the same row. I get an error: `Expected a table with CSV-compatible structure from pipeline`.

### How to reproduce

1. Take a sample JSON `{"name1": 1, "name2": 2}` 
2. `echo '{"name1": 1, "name2": 2}'|from json |pivot|to csv`

### Expected behavior

To get CSV like so:
```
Column0,Column1
name1,1
name2,2
```

### Configuration

|key|value|
|-|-|
|version|0.36.0|
|build_os|macos-x86_64|
|rust_version|rustc 1.54.0|
|cargo_version|cargo 1.54.0|
|pkg_version|0.36.0|
|build_time|2021-08-24 18:01:17 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by fdncred** [comment]
it's a little odd that this works the way you'd expect.
```
> $"{"name1": 1, "name2": 2}" | from json | pivot
╭───┬─────────┬─────────╮
│ # │ Column0 │ Column1 │
├───┼─────────┼─────────┤
│ 0 │ name1   │    1    │
│ 1 │ name2   │    2    │
╰───┴─────────┴─────────╯
```
but this does not
```
> $"{"name1": 1, "name2": 2}" | from json | pivot | to csv
error: Expected a table with CSV-compatible structure from pipeline
  ┌─ shell:6:51
  │
6 │ $"{"name1": 1, "name2": 2}" | from json | pivot | to csv
  │                                           -----   ^^^^^^ requires CSV-compatible input
  │                                           │
  │                                           originates from here
```
and yet, you can do this
```
> [[col0 col1]; [name1 1] [name2 2]]
╭───┬───────┬──────╮
│ # │ col0  │ col1 │
├───┼───────┼──────┤
│ 0 │ name1 │    1 │
│ 1 │ name2 │    2 │
╰───┴───────┴──────╯
```
and this
```
> [[col0 col1]; [name1 1] [name2 2]] | to csv
col0,col1
name1,1
name2,2
```

**Comment by arthur-targaryen** [comment]
It looks like parsing a text as JSON using this command `$"{"name1": 1, "name2": 2}" | from json` creates a table where `1` and `2` are of type `BigInt`. Later, `to csv` is unable to convert a `Primitie::BigInt` into its CSV format (see [`to_string_tagged_value`](https://github.com/nushell/nushell/blob/cc5c4d38bb9d0945e41691a0d8a93a5f84fe257f/crates/nu-command/src/commands/formats/to/delimited.rs#L131)).

Here's an example whith a table containing a big int.
```
> [[Planet Mass]; [Mars 641700000000000000000000]] | to csv
error: Expected a table with CSV-compatible structure from pipeline
   ┌─ shell:34:52
   │
34 │ [[Planet Mass]; [Mars 641700000000000000000000]] | to csv
   │ ------------------------------------------------   ^^^^^^ requires CSV-compatible input
   │ │
   │ originates from here
```

One fix would be to add the ability to convert a `Primitie::BigInt` into its CSV format.
Another would be to investigate why `from json` converts the numbers into big ints.
