### ISSUE TITLE
Directory precedence over NU command

### ISSUE THREAD

**Issue by yooakim** [nushell/nushell#3989]
### Related problem

If possible it would be nice if one could use the change-directory function also when a directory has the same name as a built-in command. 

I have source code in a folder named _source_ and if I simply type `source` I get this message:
```
error: source requires a path for sourcing parameter
   ┌─ shell:35:1
   │
35 │ source
   │ ^^^^^^ requires a path for sourcing parameter
```

and the issue because NU has a built in command named `source`. Here's a simple animation to show the issue:
![nu-shell-precedence](https://user-images.githubusercontent.com/862546/132010713-4244165d-8b0c-40ef-b251-2a775ccaa00f.gif)

### Describe the solution you'd like

If possible it would be nice if NU could check if a directory exists before it launches it's internal command.

### Additional context and details

I've tried this on both Windows and Linux and the behavior is the same.

**Comment by jntrnr** [comment]
You can use `./source` to help disambiguate that you mean the directory.

Commands should generally get precedence when there's a conflict so you are always able to do things like `exit`, `ls`, etc.

**Comment by yooakim** [comment]
Of course, good point @jntrnr - not sure what I was thinking ;-) thanks.
