### ISSUE TITLE
[FR] a way of maintaining state between function calls

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#3990]
### Related problem

While I understand that Nushell aims to be pure/functional wherever possible, there are unavoidable occasions where one would need to maintain some kind of state between function calls. In most other shells, one would use a shell variable to track this, but Nushell doesn't support anything like that.

### Describe the solution you'd like

A way to set and mutate global shell variables would be ideal.

### Describe alternatives you've considered

A way to set and mutate global environment variables would be nice too, but wouldn't fulfill all the above use cases since it also interferes with child shells. I think we should have something like that regardless.

### Additional context and details

The use case I have in mind is for [zoxide](https://github.com/ajeetdsouza/zoxide)'s Nushell plugin:
- In case a user initializes zoxide twice by accident, zoxide can detect that it's been initialized before and exit early.
- Potentially, zoxide can track when the user changes their directory -- it can observe `pwd` at each prompt, and figure out when `pwd` changes.

**Comment by jntrnr** [comment]
There may be some ways we can help with your use cases. For example `pwd` should be set correctly in the environment when the plugin is called. If it isn't, that's something we should fix.

I'd definitely prefer we try to solve the specific cases that are causing issues, rather than adding global mutable state. We'd like to avoid any mutable global state in Nushell's design. This is one of those features that's great at first but unfortunately is too easily misused, resulting in code that's much harder to reason about.

**Comment by ajeetdsouza** [comment]
@jntrnr I want to run some code every time a user changes his directory (for [zoxide](https://github.com/ajeetdsouza/zoxide)).

In other shells you can define a PWD hook. Bash doesn't have this, but you can add a function to `PROMPT_COMMAND` (similar to `PROMPT_STRING` in Nushell) that updates some global variable with the value of `$PWD`. Every time it changes, we know that the user has changed directories.

It would be nice if there was a way to do this from Nushell, too.

**Comment by ajeetdsouza** [comment]
@kubouch that works for me. If you want more consistency, this is named `$OLDPWD` in bash.

**Comment by ajeetdsouza** [comment]
@kubouch come to think of it, I don't think that would work. You need a way of knowing if the previous directory has _changed_. Having something like `$OLDPWD` just tells you what the previous directory was at every prompt, you still have no way if it has actually changed between two prompts.

Another option that might work is a cd hook that gets called every time the current directory is changed. Example: `--on-variable PWD` in fish and `chpwd_functions` in zsh.

**Comment by jntrnr** [comment]
The way to do this would be to use `def-env` calls, and set values into the environment. I don't think there are any plans for persistent mutable state outside of the environment.
