### ISSUE TITLE
Visual failure indicator

### ISSUE THREAD

**Issue by aminya** [nushell/nushell#3993]
### Related problem

Sometimes, it is not apparent if a process has been successful or not.

### Describe the solution you'd like

It would be nice if Nushell has a visual indicator that shows if a process has exited with non 0 code. This can be a simple red cross (❌) before the next prompt name after the failure.

### Additional context and details

Related to #3970

**Comment by kubouch** [comment]
Yes, we should have a system for dealing with error codes. You can already modify the prompt by setting the `PROMPT_STRING` env variable so by connecting these two components, it should be possible to achieve what you're asking.

**Comment by aminya** [comment]
This doesn't always work when the command exits with a non-zero code.

**Comment by jntrnr** [comment]
This is supported in recent Nushell versions:

```
> ^false
> $env.LAST_EXIT_CODE
1
```

Then, you configure your prompt to change what it prints based on that env variable.
