### ISSUE TITLE
[feature] register a profile with Windows Terminal on installation

### ISSUE THREAD

**Issue by yoshuawuyts** [nushell/nushell#3994]
### Related problem

In https://github.com/nushell/nushell/pull/3717 Nushell has been made available for installation via `winget` on Windows. In https://github.com/nushell/vscode-nushell-lang/pull/39 has been made available from the shell picker in VS Code.

The final feature missing for turn-key setup on Windows is making Nushell available on [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701?activetab=pivot:overviewtab)'s dropdown pane after Nu has been installed:

![Screenshot 2021-09-06 10 54 41](https://user-images.githubusercontent.com/2467194/132189999-4a7e7706-b156-41b8-8273-a8951357d876.png)

This not only makes it easy for people to try out Nu. It also makes it easy to select Nu as the default shell:

![change-default-Windows-Terminal](https://user-images.githubusercontent.com/2467194/132190422-76b9e577-9421-496d-bba9-4db9ecc20abb.jpg)

### Describe the solution you'd like

Windows Terminal supports something called [Fragment Extensions](https://docs.microsoft.com/en-us/windows/terminal/json-fragment-extensions) which allows third-party devs to generate new profiles for Windows Terminal.

Ideally Nushell for Windows could generate such a profile on installation, so that Nu becomes available for Windows Terminal out of the box.

### Describe alternatives you've considered

Windows Terminal [is available on GitHub](https://github.com/microsoft/terminal) so another option would be to submit a PR which hard-codes Nushell feature detection. However Fragment Extensions exist _precisely_ so that devs don't have to do that, which makes it seem like the better option to start with.

### Additional context and details

git bash for Windows [recently added support for Fragment Extensions](https://github.com/git-for-windows/git/issues/3183) and serves as a good example of how to generate such a profile with relatively little effort.

**Comment by fdncred** [comment]
First of all, why are you running nushell 0.13.0 released Apr-21-2020? 😆 
Second, I'm familiar with fragment extensions although I haven't investigated them recently. Let me take a look.

It looks like there are a couple ways to create these fragments.
1. We don't deliver nushell through the Microsoft Store, but that would be nice, so strike that way.
2. But it looks like we could use the way for 'downloaded applications'

```
For applications installed from the web, there are 2 cases.

The first is that the installation is for all the users on the system. In this case, the JSON files should be added to the folder:

C:\ProgramData\Microsoft\Windows Terminal\Fragments\{app-name}

In the second case, the installation is only for the current user. In this case, the JSON files should be added to the folder:

C:\Users\<user>\AppData\Local\Microsoft\Windows Terminal\Fragments\{app-name}

Note that both the ProgramData and LocalAppData folders are known folders that the installer should be able to access. If in either case, if the Windows Terminal\Fragments directory does not exist, the installer should create it.
```

It looks like we'd need a couple more things.
1. a json fragment with profile and maybe a color scheme
2. the only real place i see this going is in our windows msi. i'm not sure the fragment would help much with a zip file. although we maybe could hack together a batch file that would put a profile in the proper location?

We should probably look at this closer. I agree, it would be fun to include something like this in our msi so that winget/choco/scoop get it automatically.

**Comment by myty** [comment]
I agree that the best place for this would be the MSI installer.  

For reference, Git for Windows did this and it was a nice addition. By the looks of it, it doesn't seem too complex to get setup. 
https://github.com/git-for-windows/build-extra/pull/339

I think the only thing that might be a sticking point is generating the GUID. 
https://github.com/git-for-windows/build-extra/pull/356

**Comment by fdncred** [comment]
@myty we'd probably just want to generate a guid and use it as the nushell guid. Here's one for anyone who wants to tackle this `AAB79973-318F-43B6-A9BC-B4096493753F`

**Comment by Gabrielbdd** [comment]
Hi guys

Is someone already working on this one?

I was searching for some issue to start contributing with Nushell and just found this one, which I guess I can handle based on the previous comments.

**Comment by fdncred** [comment]
It's yours @Gabrielbdd

**Comment by fdncred** [comment]
Ping @Gabrielbdd. Made any progress on this?

**Comment by hustcer** [comment]
@fdncred I think it works now, does it?

**Comment by fdncred** [comment]
> @fdncred I think it works now, does it?

I do not think we've received any PRs for a vscode fragment extension. so, I don't think this works yet.

**Comment by rgwood** [comment]
This was addressed by https://github.com/nushell/nushell/pull/5812

**Comment by pedrohgmacedo** [comment]
Hi. I installed the nushell, and it broke my terminal settings backup script.
The nushell GUID does not match the one generated using [the procedure microsoft outlined here.](https://learn.microsoft.com/en-us/windows/terminal/json-fragment-extensions#:~:text=Generating%20a%20new%20profile%20GUID). I wonder if it is possible to fix that?
