### ISSUE TITLE
Wrong version of binary for macos in 0.2.0 release

### ISSUE THREAD

**Issue by dzhlobo** [nushell/nushell#400]
I downloaded a zip file for 0.2.0 for macos from the [release page](https://github.com/nushell/nushell/releases/tag/0.2.0).

When I run `nu --vesrion` it shows `nushell 0.1.3` but I expect to see `nushell 0.2.0`.

Is it because the release has a wrong binary of older version or is it an intentional behavior of the "pre-release" version?

**Comment by jonathandturner** [comment]
The hardicoded version didn't get updated. You should be okay. A fix went in recently to prevent this in the future
