### ISSUE TITLE
Add a nurc.nu in addition to the config.toml file

### ISSUE THREAD

**Issue by aminya** [nushell/nushell#4001]
### Related problem

I've always wanted to add some functions definitions in a nu file so they are sourced automatically whenever I open my shell. However, this is not currently possible. At the moment, I am maintaining a `~/nurc.nu` file, and I have to source it every time I open the shell manually by `source ~/nurc.nu`.

[What config.toml provides](https://github.com/nushell/nushell/blob/cc5c4d38bb9d0945e41691a0d8a93a5f84fe257f/docs/sample_config/config.toml#L6-L10) is not a replacement for a ".nu" file. It is very awkward to define everything in single-line strings without any syntax highlighting.

### Describe the solution you'd like

Add a `nurc.nu` in addition that is sourced automatically

**Comment by fdncred** [comment]
You can `source` files automatically by putting that command in the `[startup]` section of your config.toml. I'm not sure the tilde expansion works there though. I have them hard coded to a specific path in my config.toml.

**Comment by aminya** [comment]
I don't want to use absolute paths. This makes my config file unreusable.

**Comment by fdncred** [comment]
You should try the latest main branch and see if it works for you. I just added `source ~/.zoxide.nu` and it worked for me.

**Comment by aminya** [comment]
> You should try the latest main branch and see if it works for you. I just added `source ~/.zoxide.nu` and it worked for me.

Yes, it works on the master branch. 

But still, it makes sense to me to add this as a reasonable default to prevent future inconsistencies.

**Comment by Mrfiregem** [comment]
A `config.nu` file would be great to have. It's one of the core features missing that's putting me off from using this shell more, besides being unable to source files that use variables.

**Comment by hustcer** [comment]
`config.nu` was supported on the latest main, and I will close this
