### ISSUE TITLE
Errors raised within `def` blocks do not have proper tags

### ISSUE THREAD

**Issue by lily-mara** [nushell/nushell#4011]
### Describe the bug

Errors raised while _running_ (not defining) functions with `def` blocks do not have proper source attribution, so it is difficult to track them down.

### How to reproduce

```
> echo 'def my-custom-command [] { command-that-doesnt-exist }' | save script.nu
> source ./script.nu
> my-custom-command
error: Command not found
  ┌─ shell:3:6
  │  
3 │   deactivate
  │ ╭──────^
4 │ │ $nu.env
5 │ │ source ./venv.nu
  │ ╰───────────^ command command-that-doesnt-exist not found
```

Notice that the lines nushell prints look to be from earlier in the nushell history, the filename it provides is `shell`, and the line/column numbers are incorrect.

### Expected behavior

I expect nushell to provide the name of the script, line number, and snippet from the line in the error output. Something like:

```
> echo 'def my-custom-command [] { command-that-doesnt-exist }' | save script.nu
> source ./script.nu
> my-custom-command
error: Command not found
  ┌─ test.nu:1:28
  │
1 │ def my-custom-command [] { command-that-doesnt-exist }
  │                            ^^^^^^^^^^^^^^^^^^^^^^^^^ command command-that-doesnt-exist not found

```

Now it actually prints the line/command that caused the error, and the file name/line number/column number are what we expect.

### Configuration

|key|value|
|-|-|
|version|0.37.0|
|build_os|linux-x86_64|
|rust_version|rustc 1.55.0 (c8dfcfe04 2021-09-06)|
|rust_channel|stable-x86_64-unknown-linux-gnu (default)|
|cargo_version|cargo 1.55.0 (32da73ab1 2021-08-23)|
|pkg_version|0.37.0|
|build_time|2021-09-14 19:49:03 -07:00|
|build_rust_channel|release|
|features|ctrlc, dataframe, default, rustyline, term, which, zip|
|installed_plugins|fetch, match, post, ps, sys|

**Comment by kubouch** [comment]
This one should be addressed with the upcoming engine-q.

**Comment by jntrnr** [comment]
Phew, yes, we spent a lot of time improving this one in the new engine. I'm going to close because I think the kind of issue you were running into is now fixed (as a class of issues). That said, if you try the latest main and still see things like this, please re-open this or file a new issue.
