### ISSUE TITLE
Shell simply crashes when providing arguments in a specific manner to a custom command

### ISSUE THREAD

**Issue by theEndurance-del** [nushell/nushell#4016]
### Describe the bug

I created a custom command in nushell to update my AUR and core packages more efficiently, It is supposed to take three separate flags, out of which one is supposed to take a string argument.

The flags are defined like this:
```
def archupdate [
    --aur (-a): string #Update aur packages only(requires the aur helper name)
    --core (-c) #Update packages in core repositories
    --full (-f) #Update all packages
    ] { rest of the code here }
```

The command usually runs fine except when I provide the flags like this: `archupdate -ac aura`

Now, The command itself isn't supposed to run anyways because of me not providing flags in the right manner, but instead of the command itself failing, it crashes the entire shell.

### How to reproduce

1. Create the custom command as described above,
2. Provide the arguments as `archupdate -ac <args for -a>`

### Expected behavior

I expected nu to simply error out and complain about invalid arguments for the parameter.

### Screenshots

This is the error generated by `RUST_BACKTRACE=full nu`: 
```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', crates/nu-parser/src/parse.rs:1573:68
stack backtrace:
   0:     0x5592a5f2b930 - <unknown>
   1:     0x5592a5f5583c - <unknown>
   2:     0x5592a5f236b5 - <unknown>
   3:     0x5592a5f2e18b - <unknown>
   4:     0x5592a5f2dc61 - <unknown>
   5:     0x5592a5f2e864 - <unknown>
   6:     0x5592a5f2e337 - <unknown>
   7:     0x5592a5f2be2c - <unknown>
   8:     0x5592a5f2e299 - <unknown>
   9:     0x5592a4eadd21 - <unknown>
  10:     0x5592a4eadce2 - <unknown>
  11:     0x5592a542adf8 - <unknown>
  12:     0x5592a5433aa4 - <unknown>
  13:     0x5592a5437df3 - <unknown>
  14:     0x5592a543a67f - <unknown>
  15:     0x5592a4eca334 - <unknown>
  16:     0x5592a4eced3f - <unknown>
  17:     0x5592a4f3f248 - <unknown>
  18:     0x5592a4eda7cf - <unknown>
  19:     0x5592a4ed8b6c - <unknown>
  20:     0x5592a4ede3d9 - <unknown>
  21:     0x5592a4ed2296 - <unknown>
  22:     0x5592a4ed0d27 - <unknown>
  23:     0x5592a4ed2e39 - <unknown>
  24:     0x5592a4ed2fd5 - <unknown>
  25:     0x5592a4ed6db8 - <unknown>
  26:     0x5592a4eb19f7 - <unknown>
  27:     0x5592a4eb061b - <unknown>
  28:     0x5592a4eaeaf0 - <unknown>
  29:     0x5592a4eae64d - <unknown>
  30:     0x5592a4eae620 - <unknown>
  31:     0x5592a5f2ee6a - <unknown>
  32:     0x5592a4eae606 - <unknown>
  33:     0x7fbde866db25 - __libc_start_main
  34:     0x5592a4eae51e - <unknown>
  35:                0x0 - <unknown>
```

This is how the shell crashes actually:

https://user-images.githubusercontent.com/57960301/133481929-81c94661-660a-49cc-9e76-f48e0b52e457.mp4

 *Note: as it is apparent that the shell crashes after typing `archupdate -a` but rather it crashes right after I press any flag within the command such as `-ac` or `-af`.*

### Configuration

|key|value|
|-|-|
|version|0.37.0|
|build_os|linux-x86_64|
|rust_version|rustc 1.55.0|
|cargo_version|cargo 1.55.0|
|pkg_version|0.37.0|
|build_time|2021-09-15 00:41:44 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by kubouch** [comment]
The panic originates from this line: https://github.com/nushell/nushell/blob/cc3653cfd981672a95bb3942dbdc718290bc5453/crates/nu-parser/src/parse.rs#L1573

**Comment by jntrnr** [comment]
note: this is fixed in engine-q, but we should also fix it in nushell since we're still a ways out from integrating e-q into nushell.

**Comment by ahkrr** [comment]
I think this Issue can be closed because https://github.com/nushell/nushell/pull/4107 should have fixed it.

**Comment by kubouch** [comment]
Indeed, does not happen anymore for me. I'll close it, please reopen if it becomes an issue again.
