### ISSUE TITLE
Incorrect span for type errors in `if` statement condition

### ISSUE THREAD

**Issue by Pantonshire** [nushell/nushell#4018]
### Describe the bug

For some `if` statements where the condition is not a boolean, the resulting type error highlights the first character of the first line instead of the erroneous condition.

### How to reproduce

```
echo "hello world"
if $nothing {echo yes} {echo no}
```

### Expected behavior

I expected nu to display an error highlighting the incorrectly-typed condition of the `if` statement.

### Screenshots

<img width="465" alt="Screenshot 2021-09-15 at 20 09 20" src="https://user-images.githubusercontent.com/34181656/133495000-241e1cdc-b132-4cd9-8c78-e804a3dc17aa.png">

### Configuration

|key|value|
|-|-|
|version|0.37.0|
|build_os|macos-x86_64|
|rust_version|rustc 1.55.0|
|cargo_version|cargo 1.55.0|
|pkg_version|0.37.0|
|build_time|2021-09-14 19:45:30 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by jntrnr** [comment]
This issue I think it's possibly related to how spans travel through variables.  There are a few places in Nushell that might cause this.

This issue is fixed in engine-q:

![image](https://user-images.githubusercontent.com/547158/133496740-f0959841-9238-4017-a9b3-7e6d7d8cc9d9.png)

**Comment by jntrnr** [comment]
New engine is now in nushell main. We get a proper error now:

```
> if $nothing {echo yes} else {echo no}
Error: nu::shell::cant_convert (link)

  × Can't convert to bool.
   ╭─[entry #59:1:1]
 1 │ if $nothing {echo yes} else {echo no}
   ·    ────┬───
   ·        ╰── can't convert nothing to bool
   ╰────
```
