### ISSUE TITLE
Ctrl-C has no effect when running ls **/

### ISSUE THREAD

**Issue by terencode** [nushell/nushell#403]
Reproduction steps:
1. Run `ls **/` on a large directory tree to not make it return immediately
2. Try to send SIGINT with Ctrl+C 
3. Notice it has no effect and the command keeps running

---
nushell 0.2.0- 5d34e3a

**Comment by jonathandturner** [comment]
Confirmed - I've seen this too. We might need to check for key presses while we output long tables

**Comment by jonathandturner** [comment]
This should be fixed by #812
