### ISSUE TITLE
error: dataframe unexpected to-series

### ISSUE THREAD

**Issue by franklucky001** [nushell/nushell#4030]
### Describe the bug

I download release 0.37, and use example in document `let new = ([9 8 4] | dataframe to-series new_col)`, get error: dataframe unexpected to-series. i use dataframe help and subcommand to-series not Found, Did I do something wrong?

### How to reproduce

use `let new = ([9 8 4] | dataframe to-series new_col)` in nushell

### Expected behavior
```
───┬───────────────
 # │ new_col (i64)
───┼───────────────
 0 │             9
 1 │             8
 2 │             4
───┴───────────────
```
### Screenshots

![1632192949(1)](https://user-images.githubusercontent.com/25685004/134104782-645a857b-4b44-46c6-9a69-0da5731f9bc8.png)

**Comment by elferherrera** [comment]
@franklucky001 there is no command called to-series. You can try with to-df

**Comment by franklucky001** [comment]
@elferherrera 
I found this example in nushell website https://www.nushell.sh/book/dataframes.html#working-with-series
Isn't this your official website?
![image](https://user-images.githubusercontent.com/25685004/134128528-9afd9c28-00e6-4e8b-ae4e-6b1d74993e55.png)

**Comment by elferherrera** [comment]
You are right. I forgot to update the documentation. Let me do that now.
But now everything is a dataframe, for that reason we only have to-df

**Comment by rgwood** [comment]
Believe this can be closed now that the documentation has been updated.
