### ISSUE TITLE
expose a function for  command_not_found to allow user to customize 

### ISSUE THREAD

**Issue by eggcaker** [nushell/nushell#4032]
### Describe the solution you'd like

right now when run a command which does not exists has a error message like : 
```
error: Command not found
   ┌─ shell:17:1
   │
17 │ aaaa
   │ ^^^^ command aaaa not found
```
in zsh, you can define a function ```command_not_found_handler ```  in .zshrc file.

**Comment by fdncred** [comment]
that sounds cool. and what do you have your zsh `command_not_found_handler` do right now? i'm trying to figure out what cool things this exposes.

**Comment by eggcaker** [comment]
for example :  https://github.com/eggcaker/dotfiles/commit/3045f90adcb4d90c86a3b45d3896962599a31ece 
in this commit,  I define some  handler function with regex, if the command match  timestamp, convert it to human date . if it's match a stock code, will fetch the stock information ,other raise default  error command not found . 

and another use cases is I have some script wrote with powershell, I want a handler if command not found I can call powershell script  and get result back as a normal nu command

**Comment by flying-sheep** [comment]
We could add a `ftc.nu` to this: https://github.com/pkasemir/find-the-command

**Comment by sholderbach** [comment]
Sounds like a possible place to add a hook

**Comment by stevenxxiu** [comment]
I think for *Arch Linux* the official place to add this should be [pkgfile - ArchWiki](https://wiki.archlinux.org/title/Pkgfile#Command_not_found).

**Comment by stevenxxiu** [comment]
I'm giving a shot of implementing this. I need `nu_cli::repl::eval_hook` in `crates/nu-command/src/system/run_external.rs`, but `nu_cli::repl` is a private module. Any ideas on how to refactor?

**Comment by jntrnr** [comment]
Closed with https://github.com/nushell/nushell/pull/8314
