### ISSUE TITLE
Unexpected alias behavior when piping in alias

### ISSUE THREAD

**Issue by GustavoPeredo** [nushell/nushell#4035]
### Describe the bug

I'm not fully sure if I should open this as a bug or as a feature request, for me it seems like an unexpected behavior, that's why I'm opening as a bug.

Adding a pipe to an alias command on startup or while running nushell doesn't seem to work.

### On startup

Add the following line to `config.toml` file:
```
startup = ["alias test = cat ~/Dokumente/agenda.txt | grep Monday "]
```

Run nushell with `nu`
Results:
* On startup nushell runs the command supposed to receive the pipe (in this case grep):
```
❯nu
grep: Unbekannte Option »Monday«
Aufruf: grep [OPTION]… MUSTER [DATEI]…
„grep --help“ liefert weitere Informationen.
Welcome to Nushell 0.37.0 (type 'help' for more info)
```
* When running the `test` alias:
```
Monday
00:00-----------------
|                    |
12:00-----------------
|                    |
----------------------

```
(It `cat`s the file only)

#### Experiment 1

* Run the following command:
```
alias test = cat ./Dokumente/agenda.txt | grep Monday
```
(nushell first runs `alias` and then pipes the output to grep, therefore the alias only `cat`s, similar to the startup scenario)

#### Experiment 2

* Run the following command:
```
alias test = 'cat ./Dokumente/agenda.txt | grep Monday'
```

* I imagine this `alias` is saving `'cat ./Dokumente/agenda.txt | grep Monday'` as a string, therefore causing the following output:
```
❯test
cat ./Dokumente/agenda.txt | grep Monday

```

#### Experiment 3

* Running the following command:

```
alias test = `cat ./Dokumente/agenda.txt | grep Monday`
```

* Causes `test` to search for a `cat ./Dokumente/agenda.txt | grep Monday` command that doesn't exist

```
❯test
error: Command not found
   ┌─ shell:28:1
   │
28 │ test
   │ ^^^^ command `cat ./Dokumente/agenda.txt | grep Monday` not found

```

### Expected behavior

I expected nushell to work similarly to zsh (maybe bash?) where I could:

### On Startup

Be able to store pipes inside aliases:
```
alias todo-up="cat ~/Dokumente/agenda.txt | grep Monday"
```
(line similar to one I have on my .zshrc file)

### While running

If I run the following command on bash (this works on zsh as well) it gives me the desired output:
```
[gustavo@thinkpad ~]$ alias todo-up="cat ~/Dokumente/agenda.txt | grep Monday"
[gustavo@thinkpad ~]$ todo-up 
Monday
```

### Configuration

|key|value|
|-|-|
|version|0.37.0|
|build_os|linux-x86_64|
|rust_version|rustc 1.55.0|
|cargo_version|cargo 1.55.0|
|pkg_version|0.37.0|
|build_time|2021-09-15 00:41:44 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

### Additional context

PS: I'm not `cat`ting into `grep` IRL, but the behavior is the same lol.

**Comment by theEndurance-del** [comment]
Try aliasing like this:

`alias todo-up = {cat ~/Dokumente/agenda.txt | grep Monday}`

In `config.toml` it should look like this:
``` toml
startup = ["alias todo-up = {cat ~/Dokumente/agenda.txt | grep Monday}"]
```

**Comment by GustavoPeredo** [comment]
Thanks for commenting, this seems to solve my issue.
