### ISSUE TITLE
Piping into an external command concatenates all input as if it were a single string

### ISSUE THREAD

**Issue by dartacao** [nushell/nushell#4042]
### Describe the bug

Piping into an external command concatenates all input as if it were a single string. Using rush (a CLI utility to run jobs in parallel) as an example, but as far as I can tell this is a nu issue. If there is a more nushell-native way of running parallel jobs, I couldn't find it.

### How to reproduce

Running `seq 8 | into string | rush 'echo {}-'` prints out 12345678-, not the numbers separated by '-'.
Because the intention is to run these commands in parallel, I cannot use each: `seq 8 | each {into string | rush 'echo {}'}`) (see screenhot).
Using `seq 8 | rush 'echo {}-'` returns an error, as it expects a string and not int.

### Expected behavior

I expected it to print a random sequence from 1-8, and not 12345678 as it does.

### Screenshots

![image](https://user-images.githubusercontent.com/2131630/134769364-8c7ab899-bf3e-4530-a32e-f091d9ecb00b.png)
Here's what I tried, all with no success. 

### Configuration

|key|value|
|-|-|
|version|0.37.0|
|short_commit|f9ae8820|
|commit_hash|f9ae882012e87e328adbe8da90d3a37ba8aa0448|
|commit_date|2021-09-14 19:45:30 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.55.0 (c8dfcfe04 2021-09-06)|
|rust_channel|stable-x86_64-pc-windows-msvc (default)|
|cargo_version|cargo 1.55.0 (32da73ab1 2021-08-23)|
|pkg_version|0.37.0|
|build_time|2021-09-14 20:08:37 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

### Additional context

I'm new-ish to nushell, but I think this is the correct syntax for what I'm doing (`seq 8 | into string | rush 'echo {}-'`). But it does not run as expected. If this is incorrect, I hope anyone can assist me?

**Comment by fdncred** [comment]
if you want to use a separator with `seq` you can do `seq 8 -s '-'`.

**Comment by dartacao** [comment]
@fdncred Maybe I did not write clearly, the idea is that rush _should_ print a random sequence, since it should start 8 jobs in parallel. I wish to run another set of commands in parallel, to compile several figures in tex (which is quite slow in sequence). It should "just work" through stdin, or am i incorrect?

**Comment by fdncred** [comment]
nushell has no mechanism to call external programs in parallel. i think `each` is the best we have right now.

**Comment by dartacao** [comment]
Ok, that confirms what i initially thought
. But shouldn't seq piped as a string to rush (https://github.com/shenwei356/rush) at least work? Here's nu and pwsh as an example:
![image](https://user-images.githubusercontent.com/2131630/134770970-e49c7240-aa6f-4003-9cba-8e2642e65440.png)

**Comment by fdncred** [comment]
i'm not sure. it looks like something is collecting the stream before passing it to rush. but this seems to work.
```
> echo a=b=c | ^./rush -D "=" -k 'echo {}' --immediate-output
(2/1/1): b
(3/1/1): c
(1/1/1): a
```
and only using external commands seems to work
```
> ^seq 1 10 | ^./rush 'echo {}' --immediate-output
(1/1/1): 1
(2/1/1): 2
(4/1/1): 4
(3/1/1): 3
(7/1/1): 7
(5/1/1): 5
(6/1/1): 6
(8/1/1): 8
(9/1/1): 9
(_2.10/1/1): 10
```

**Comment by fdncred** [comment]
@jntrnr thought this may be because rush is expecting newlines so i tried this and it seems to work.
```
> echo 1 2 3 4 5 | into string | each {$"($it)(char nl)"} | str collect | ^./rush 'echo {}' --immediate-output
(3/1/1): 3
(4/1/1): 4
(1/1/1): 1
(2/1/1): 2
(5/1/1): 5
```
or this
```
> seq 8 | into string | each {$"($it)(char nl)"} | str collect | ^./rush 'echo {}' --immediate-output
(3/1/1): 3
(2/1/1): 2
(1/1/1): 1
(4/1/1): 4
(7/1/1): 7
(5/1/1): 5
(6/1/1): 6
(8/1/1): 8
```

**Comment by dartacao** [comment]
Ok, so all of the proposed solutions work, thanks @fdncred ! I think this is either a windows only thing (though I can't be sure?) OR a nushell + external concatenation issue somewhere in the pipeline. Maybe this has to do with JSON files registering '\n' literally when save is used? Ive run into that a couple hours ago as well

**Comment by fdncred** [comment]
You may be able to use the `--raw` parameter where the new lines are being injected.

**Comment by fdncred** [comment]
closing since we made it work.
