### ISSUE TITLE
how to set http_proxy and https_proxy environment variables?

### ISSUE THREAD

**Issue by pedoc** [nushell/nushell#4045]
### Related problem

I have tried the following options:

1. alias in startup(not working)
```toml
startup=["alias nuproxy = let-env http_proxy = http://127.0.0.1:10809 ; let-env https_proxy = http://127.0.0.1:10809;"]
```
The alias instruction is executed automatically and is incomplete (only the last sentence of code is executed), in fact I do not want this instruction to be executed unless I manually call alias ```nuproxy```.I think alias is just a definition, why should it be executed at startup？
![image](https://user-images.githubusercontent.com/6604230/134795010-9afa5206-0f78-4bf3-96c0-ab9b93a067cd.png)

2. custom command(not working)
```toml
startup=["def nuproxy [] { let-env http_proxy = http://127.0.0.1:10809 ; let-env https_proxy = http://127.0.0.1:10809; }"]
```
When I manually execute custom command ```nuproxy```, there is no change in environment variables.
![image](https://user-images.githubusercontent.com/6604230/134795176-4626bc7d-6549-433e-8f52-3c4fdd888358.png)

3.Execute directly on the shell,(working,but not the desired solution)
If the let-env command is executed directly, it works normally, but these inputs are cumbersome and error-prone, and only need to be enabled in some scenarios.
![image](https://user-images.githubusercontent.com/6604230/134795150-3e49dab9-8ffc-405c-954f-4763b8d12d07.png)

any help?thanks

### Describe the solution you'd like

The environment variables set in the custom command can take effect in the session.

### Additional context and details

Compile with the latest code, commit id：# 32581497efab4245859e04f8f8ef8e67b785f79c

**Comment by fdncred** [comment]
with the `def`, I think nushell only recognizes that env var within the current scope. you can see that with this:
```
def a [] { 
let-env a = 1
echo $nu.env.a
let-env b = 2
echo $nu.env.b
}
```
```
> a
12
```
```
> echo $nu.env.a
error: Unknown column
   ┌─ shell:52:14
   │
52 │ echo $nu.env.a
   │              ^ did you mean '_'?
```
with the alias, i'm not sure creating multiple in one alias is allowed. you can test that with this:
```
> alias a = let-env a = 1
> alias b = let-env b = 2
> a
> echo $nu.env.a
1
> b
> echo $nu.env.b
2
```

**Comment by pedoc** [comment]
first,thanks u.

Yes, I have tried these, but I am not satisfied.If you set an alias at startup, you will not be able to get rid of the global proxy. In fact, I only set the proxy when I need it.

**Comment by fdncred** [comment]
We're not satisfied with our current functionality in this regard either. Which is why so much effort is being put into our new `engine-q`. We're hoping to eventually land an feature we're tentatively calling `overlays` which would allow you to 'enter' and overlay and have different settings. Then when you 'exit' the overlay, your original settings are restored. It's kind of like our `autoenv` feature, which is kind of like `dotenv`, but on a grander scale.

**Comment by fdncred** [comment]
One last thought, have you tried this and does it work? `alias nuproxy = (let-env http_proxy = http://127.0.0.1:10809 ; let-env https_proxy = http://127.0.0.1:10809)`

**Comment by pedoc** [comment]
Sorry for the delay in my reply.

> One last thought, have you tried this and does it work? `alias nuproxy = (let-env http_proxy = http://127.0.0.1:10809 ; let-env https_proxy = http://127.0.0.1:10809)`

yes,it's working.
![image](https://user-images.githubusercontent.com/6604230/135702203-7420821d-ae59-4792-99fe-6029b6b3d4aa.png)


```
"alias nuproxy = (let-env http_proxy = http://127.0.0.1:10809 ; let-env https_proxy = http://127.0.0.1:10809)",
"alias unproxy = (unlet-env http_proxy ; unlet-env https_proxy ; )"
```

Thank you again for providing such an excellent tool. :)
