### ISSUE TITLE
About the tab key (completions)

### ISSUE THREAD

**Issue by 0x3rhy** [nushell/nushell#4046]
### Related problem

Bad experience about the tab key

### Describe the solution you'd like

Can you first search for the file name in the current directory? Each time tab will always first query the nushell commands, then go to the environment variable and then go to the current directory. When you try to execute a file named `start_xx_task.bat` on Windows, enter `st` and use `tab` completion, you will understand how bad it is

**Comment by fdncred** [comment]
we're working on completions. i like your idea of search order.

**Comment by fdncred** [comment]
tab key is working as expected in 0.59.1. please re-open if you disagree.
