### ISSUE TITLE
libgit2.so.1.1 not found

### ISSUE THREAD

**Issue by danjenson** [nushell/nushell#4047]
On arch Linux, libgit was upgraded to `libgit2.so.1.2`, so now the shell fails to start since `nu_plugin_core_textview` requires 1.1. This was pretty tricky to figure out since my user account became inoperable when I upgraded packages recently. Is there a list of shared system libraries nushell depends on? I will probably need to install a hook to recompile whenever I upgrade dependencies.

**Comment by fdncred** [comment]
The dependencies are listed here https://www.nushell.sh/book/installation.html#dependencies. textview uses git because the `bat` crate uses git.

**Comment by danjenson** [comment]
Thanks!
