### ISSUE TITLE
Cyrillic field name is borked

### ISSUE THREAD

**Issue by EgZvor** [nushell/nushell#4049]
### Describe the bug

When using a field name in cyrillic the output has strange question mark symbols (due to coloring?)
```
/home/egzvor> ls | rename 'имя' 'тип' 'размер' 'изменён' | where им�� == 'Reading'
───┬─────────┬─────────┬────────┬────────────
 # │   имя   │   тип   │ размер │  изменён   
───┼─────────┼─────────┼────────┼────────────
 0 │ Reading │ Symlink │   18 B │ a year ago 
───┴─────────┴─────────┴────────┴────────────
```

### How to reproduce

1. Copy the command below
```
ls | rename 'имя' 'тип' 'размер' 'изменён' | where имя == 'something'
```

### Expected behavior

Display cyrillic field name correctly

### Configuration

|key|value|
|-|-|
|version|0.37.0|
|build_os|linux-x86_64|
|rust_version|rustc 1.55.0|
|cargo_version|cargo 1.55.0|
|pkg_version|0.37.0|
|build_time|2021-09-15 00:41:44 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by fdncred** [comment]
@kubouch I'm wondering if this is possibly a `..._lossy()` conversion somewhere that puts question marks for characters it doesn't know? 

It's also interesting that the error message prints it fine.
![image](https://user-images.githubusercontent.com/343840/135270872-3964a602-85cc-4631-8590-08b3e0e9d720.png)

You can also put a quote before it and it corrects itself until you remove the quote.
![image](https://user-images.githubusercontent.com/343840/135271094-5fc29594-6f05-4e06-bc7e-8f56a6dd7594.png)

**Comment by jntrnr** [comment]
This is now support in nushell's main branch
