### ISSUE TITLE
Syntax highlighting appears to not handle correctly unicode length

### ISSUE THREAD

**Issue by CBenoit** [nushell/nushell#4054]
### Describe the bug

Hello!

I noticed the syntax highlighting is not working as expected when using unicode.
I didn’t check code, but I suppose this is related to use of `len()` instead of `.chars().count()` somewhere.

### How to reproduce

Write this
```
echo $"6 × 7 = (6 * 7)"
```

### Expected behavior

Correct syntax highlighting like shown on the bottom line.

### Screenshots

![image](https://user-images.githubusercontent.com/3809077/135476533-c28b76f7-3f6b-4d0a-8627-b9113c071b04.png)

### Additional context

Top line is using the unicode character "×" while the bottom one is using the "x" letter.

**Comment by jntrnr** [comment]
This looks like it'll be fixed in the upcoming parser changes (part of the engine-q work):

![image](https://user-images.githubusercontent.com/547158/135511498-fcd50e16-6c00-454b-8574-fd0482ef560f.png)

**Comment by CBenoit** [comment]
Nice! I’ll just close right away to reduce issue management then
