### ISSUE TITLE
Nushell doesn't check if output is a teletype or not

### ISSUE THREAD

**Issue by dartacao** [nushell/nushell#4057]
### Describe the bug

Using neovim bangs as an example:
Doing :!ls yields a series of ansi color codes which should not be present.

### How to reproduce

1. Open nvim
2. Run :!ls or any other command
3. See output?

### Expected behavior

A colorless table with file names and no color codes

### Screenshots

![image](https://user-images.githubusercontent.com/2131630/135597121-11c363f0-b255-4980-827e-bf16ff977861.png)

### Configuration

|key|value|
|-|-|
|version|0.37.0|
|short_commit|f9ae8820|
|commit_hash|f9ae882012e87e328adbe8da90d3a37ba8aa0448|
|commit_date|2021-09-14 19:45:30 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.55.0 (c8dfcfe04 2021-09-06)|
|rust_channel|stable-x86_64-pc-windows-msvc (default)|
|cargo_version|cargo 1.55.0 (32da73ab1 2021-08-23)|
|pkg_version|0.37.0|
|build_time|2021-09-14 20:08:37 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by kubouch** [comment]
Yes, ran into the same issue.

I was thinking we could add a flag to the nushell executable to disable colors. Then, you'd set your vim shell to "nu --no-color". Not sure how feasible would that be. I've never worked with colors myself.

**Comment by dartacao** [comment]
That would be a good solution. I was told that there is a function in C to check if an output is a tty or not, perhaps there is a Rust equivalent? If so, it could also be automatically detected on startup.

**Comment by hustcer** [comment]
Same issue here

**Comment by fdncred** [comment]
I just submitted a PR that might fix it. It would be nice if y'all test it with your `:!ls` stuff - i'm in windows and try to stay away from vim if possible. :)

**Comment by kubouch** [comment]
@fdncred This is absolutely awesome, works out of the box! Thanks!
![ls](https://user-images.githubusercontent.com/25571562/135632609-c62f5e1e-4718-46a3-9c1c-eb667f70196c.png)
