### ISSUE TITLE
Installation fails unless pkg-config installed on Ubuntu

### ISSUE THREAD

**Issue by John-Goff** [nushell/nushell#406]
The README lists `libssl` as the only dependency, but installation via `cargo install nu --features rawkey,clipboard` fails with 
```
error: failed to run custom build command for `x11 v2.18.1`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installPcQj62/release/build/x11-7c0ea440e6ca0b57/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"x11\" \"x11 >= 1.4.99.1\"", cause: Os { code: 2, kind: NotFound, message: "No such file or directory" } }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to compile `nu v0.2.0`, intermediate artifacts can be found at `/tmp/cargo-installPcQj62`

Caused by:
  build failed
```
unless `pkg-config` is installed (`sudo apt install pkgconf` on my system). 

Using rust nightly installed via rustup on Ubuntu 19.04

**Comment by jonathandturner** [comment]
Thanks for the report, looks like the step for X11 need to be in the book but only if you use the optional features

**Comment by wycats** [comment]
Is it normal for Ubuntu to not have pkgconfig?

**Comment by jankoprowski** [comment]
I had similar issue: https://github.com/nushell/nushell/issues/456
Installing pkgconfig helped!

**Comment by jonathandturner** [comment]
We've updated the book to mention this, so going ahead and closing.
