### ISSUE TITLE
Table layout broken on Windows after open vim with nushell 0.38

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4065]
### Describe the bug

Table layout broken on Windows after open vim

### How to reproduce

1. Start nu from Windows Terminal and run `ls` works fine.
2. Open vim in terminal then quit
3. Run `ls` in nu, the table layout was broken

### Expected behavior

The table is displayed correctly after vim quit

### Screenshots

Before:
![image](https://user-images.githubusercontent.com/1161607/136128042-0a5a52bf-5726-42e5-a1b3-1628fefc8de5.png)

After open vim and quit:

![image](https://user-images.githubusercontent.com/1161607/136128097-e44b0234-b146-4453-8ca1-719930ec4298.png)

### Configuration

|name|val|
|-|-|
|version|0.38.0|
|short_commit|e1ebd461|
|commit_hash|e1ebd461d24927deb48ac758f9b456a21b479065|
|commit_date|2021-10-05 17:35:25 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.55.0 (c8dfcfe04 2021-09-06)|
|rust_channel|stable-x86_64-pc-windows-msvc (default)|
|cargo_version|cargo 1.55.0 (32da73ab1 2021-08-23)|
|pkg_version|0.38.0|
|build_time|2021-10-05 18:08:23 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

### Additional context

> `sys|get host|select name 'os version' 'kernel version'|to md`

|name|os version|kernel version|
|-|-|-|
|Windows|10 (19043)|19043|

**Comment by kubouch** [comment]
I'm wondering if it has something to do with #4058 . Doesn't happen on my Linux though.

**Comment by hustcer** [comment]
Mac and linux may not have this issue

**Comment by fdncred** [comment]
i have the same experience. it must be something with the way vim is exiting the shell. it's like a cr lf issue or something.
![image](https://user-images.githubusercontent.com/343840/136218000-6e06b0f6-b766-4e45-96ab-ad10be055c41.png)

**Comment by fdncred** [comment]
I've also confirmed that it's not related to #4058 by reverting it and testing. the problem still exists without it.

**Comment by hustcer** [comment]
This issue was fixed in nu 0.59+
