### ISSUE TITLE
Add feather file format support ? 

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4075]
### Related problem

For more detail here: https://arrow.apache.org/docs/python/feather.html

### Describe the solution you'd like

I think we can add `from feather` and `to feather` command to support feather file format handling.

**Comment by jntrnr** [comment]
As this isn't widely used, this would be better as a plugin. Closing, but folks should feel free to write and share plugins for formats.

**Comment by Hofer-Julian** [comment]
Feather files are already supported by the dataframe plugin
