### ISSUE TITLE
Can ls output both different color for directory and normal file ?

### ISSUE THREAD

**Issue by WindSoilder** [nushell/nushell#4077]
### Describe the solution you'd like

![图片](https://user-images.githubusercontent.com/22256154/137040551-68b115fe-5483-47bc-942b-b4bf5db14d6b.png)

I have try the config in the repo, and the output for ls is great, but I think it would be better if we can output different color for directory and file.  So I can easily scan out which is a directory, and which is a normal file.

sadly I've read out the nu book and can't find a solution for it...Any suggestion?

**Comment by jntrnr** [comment]
This should now work in the latest main, which uses the new engine.
