### ISSUE TITLE
Aborting a jline-based application leaves nushell in a weird state

### ISSUE THREAD

**Issue by raboof** [nushell/nushell#4078]
### Describe the bug

When I abort an interactive sbt session with ^C, in particular for example while it's compiling, it sometimes leaves nushell in a weird state where I can't successfully enter commands anymore.

### How to reproduce

Unfortunately I don't have a 'nice' reproducer for this yet, but I wanted to record the issue for future reference anyway. I hope to find time to amend to it later ;)

### Expected behavior

allow me to enter commands again

### Configuration

|key|value|
|-|-|
|version|0.37.0|
|build_os|linux-x86_64|
|rust_version|rustc 1.55.0|
|cargo_version|cargo 1.55.0|
|pkg_version|0.37.0|
|build_time|1980-01-01 00:00:00 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by rgwood** [comment]
I suspect this is fixed just like https://github.com/nushell/nushell/issues/5261. 

Closing for now, but @raboof please let us know if you can still reproduce this and we'll reopen.
