### ISSUE TITLE
open of url needs to fully redirect

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#409]
Currently if you do an `open` of a url that redirects, we don't get the final result but an intermediate step:

Compare:

```
> open http://jonathanturner.org/feed.xml
<a href='http://www.jonathanturner.org/feed.xml'>Found</a>.                                                                                                                                                       

> open http://www.jonathanturner.org/feed.xml
----------
 rss 
----------
 [1 item] 
----------
```

**Comment by jonathandturner** [comment]
Related: https://github.com/rustasync/surf/pull/21

**Comment by wycats** [comment]
@jonathandturner Do we want to wait for https://github.com/rustasync/surf/pull/21 or try to address it ourselves?

**Comment by yoshuawuyts** [comment]
https://github.com/http-rs/surf/issues/18 is the tracking issue for this. I've gone and closed the draft PR, as we should instead follow a simpler model instead (redirect for GET requests with no body only).

It would be fantastic to see contributions for this!
