### ISSUE TITLE
operator "in" performs normal after “where” but not “dataframe where”,show "expected primitive values"

### ISSUE THREAD

**Issue by MoneySail** [nushell/nushell#4090]
![image](https://user-images.githubusercontent.com/17845399/138545550-04445dea-9c8f-4fc6-950c-7b3b32a1403a.png)

Hello everyone，i use "open xxx1.xlsx|get xxx2|headers| where xxx3 in [value1 value2 value3] " is Ok,but i use dataframe open,show "expected primitive values", how to solve this problem?

**Comment by elferherrera** [comment]
I dont think dataframes where have that in option. It only has equality (==) or similar (=~)

You can however create a filter mask and apply that to the dataframe 
https://www.nushell.sh/book/dataframes.html#series-and-masks

**Comment by rgwood** [comment]
Closing because this seems to be answered.
