### ISSUE TITLE
Make type in `ls` lowercase

### ISSUE THREAD

**Issue by vwkd** [nushell/nushell#4092]
### Related problem

When writing `ls | where type == File` reaching for the SHIFT key costs me one additional awkward key stroke... But on a more serious note, it isn't so obvious to me why the value of the type is in uppercase.

- The values of type are of fixed set that never changes.
- `ls` doesn't use these values itself so there is no precedence. Granted there is a table in the manual that refers to them (or slightly longer counterparts) in uppercase but this seems to be rather because of long-form text starting uppercase in a new lines since everywhere else in the manual they are used lowercase.
- In similar places values are lowercase like the boolean value of the `readonly` column, e.g. `ls | where readonly == false`.

---

Referred snippet from `man ls`:

```
b     Block special file.
c     Character special file.
d     Directory.
l     Symbolic link.
s     Socket link.
p     FIFO.
-     Regular file.
```

### Describe the solution you'd like

Make type in `ls` lowercase such that `ls | where type == file` and similar.

### Describe alternatives you've considered

Continuing to reach for that SHIFT key...

**Comment by vwkd** [comment]
Thanks! Just to remember that docs also needs updating.

**Comment by jntrnr** [comment]
This is now supported in nushell's latest main
