### ISSUE TITLE
Use expressive names

### ISSUE THREAD

**Issue by vwkd** [nushell/nushell#4093]
### Related problem

Expressiveness is great. It allows to use natural language cues to help understanding. Until now history was constrained by having to type each character out manually leading to the opposing need for brevity. I'm still astonished how strong brevity actually is when it's even about saving a few keystrokes like a command `ls` compared to `list`.

Autocomplete #290 will lift the constraint and make brevity a thing of the past. Names can finally be expressive.

Nushell already uses many more expressive names, e.g. `sort-by`, `rotate counter-clockwise`, etc. But it still uses some brief names, e.g. `g`, `n `, `p`, `cd`, `ls`, etc.

Using sometimes brief and sometimes expressive names is inconsistent. But also it forces the historic constraint onto the younger generations coming to computers only now which don't need it. For them everything could be more expressive.

### Describe the solution you'd like

1. Only use expressive names going forward.
2. Introduce expressive aliases for existing brief names.

This way muscle memory can keep working while younger people don't need to suffer the constraints of history.

Command aliases:

`ls` -> `list`
`cp` -> `copy`
`mv` -> `move` or `rename`
`rm` -> `remove`
`cd` -> `change-directory` or `switch`
`mkdir` -> `make-directory` or `create-directory` or `directory`
etc.

**Comment by hustcer** [comment]
Actually, I like the names: ls, cp, mv, rm, cd, mkdir, they are easier to remember for bash users. Just follow the common conventions is a good choice, IMO.

**Comment by hustcer** [comment]
Actually, I like the names: ls, cp, mv, rm, cd, mkdir, they are easier to remember for bash users. Just follow the common conventions is a good choice, IMO.

**Comment by vwkd** [comment]
I agree with @kubouch that an alias - having two names for a command - will create a division in documentation, education, and so on that might do more harm than good.

I changed my mind and think only commands that are unique to nushell (existing and any new ones) should be expressive, while traditional commands taken from old systems (`ls`, `cd` etc.) remain as they are to not break compatibility. Those commands are like “marks of history”.

It’s not too different from words in natural language. Language keeps using old words and only adds new ones on top, instead of tearing apart the whole language each X years. This allows yesterday’s language to still be understood tomorrow.
