### ISSUE TITLE
Implicit coercion of boolean `false` and empty value

### ISSUE THREAD

**Issue by vwkd** [nushell/nushell#4094]
### Describe the bug

I have a table with a column with boolean values of which some are empty.

```
───┬───────
 # │   A   
───┼───────
 0 │       
 1 │ false 
 2 │ true  
───┴───────
```

I want to filter this table between `true`, `false` and empty value.

But Nushell coerces boolean `false` and the empty value.

This issue isn't limited to tables. It stems from the underlying data types.

Also there might be more issues with implicit coercion that I haven't tested yet, like empty string `""` and zero `0`.

Implicit coercion is hard to get right as JavaScript has famously proven. Nushell shouldn't do implicit coercion and instead offer some explicit way.

### How to reproduce

`> [[A]; [$nothing] [$false] [$true]] | where A == $false`

#### Expected

```
───┬───────
 # │   A   
───┼───────
 0 │ false 
───┴───────
```

#### Actual

```
───┬───────
 # │   A   
───┼───────
 0 │       
 1 │ false 
───┴───────
```

`> [[A]; [$nothing] [$false] [$true]] | where A != $false`

#### Expected

```
───┬──────
 # │  A   
───┼──────
 0 │  
 1 │ true 
───┴──────
```

#### Actual

```
───┬──────
 # │  A   
───┼──────
 0 │ true 
───┴──────
```

`> [[A]; [$nothing] [$false] [$true]] | where A != $nothing`

#### Expected

```
───┬──────
 # │  A   
───┼──────
 0 │ false 
 1 │ true 
───┴──────
```

#### Actual

```
───┬──────
 # │  A   
───┼──────
 0 │ true 
───┴──────
```

`> [[A]; [$nothing] [$false] [$true]] | where A == $nothing`

#### Expected

```
───┬───────
 # │   A   
───┼───────
 0 │       
───┴───────
```

#### Actual

```
───┬───────
 # │   A   
───┼───────
 0 │       
 1 │ false 
───┴───────
```

### Configuration

|key|value|
|-|-|
|version|0.38.0|
|build_os|macos-x86_64|
|rust_version|rustc 1.55.0|
|cargo_version|cargo 1.55.0|
|pkg_version|0.38.0|
|build_time|2021-10-05 17:35:25 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by andrasio** [comment]
@vwkd Have you considered using the `compact` command to get rid of values that aren't there?
