### ISSUE TITLE
builtin command to bypass user-defined aliases / functions

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#4100]
### Related problem

User-defined functions/variables often interfere with the intended behavior of shell plugins, causing all sorts of surprising bugs. A way to unambiguously call a command or a shell builtin would be great.

Specifically, my use case: I want [zoxide](https://github.com/ajeetdsouza/zoxide) to be able to _replace_ the cd command with a smarter version of itself. For that, I would need to write a cd function that parses the arguments and then calls the builtin cd command with the actual directory name.

### Describe the solution you'd like

Nushell could perhaps take some inspiration from other shells here.

On POSIX shells you can use a backslash to escape user-defined functions:

```sh
\cd /home/foo
```

On bash you can use the `builtin` command:

```sh
\builtin cd /home/foo
```

It also has the `command` builtin for unambiguously calling binaries.

**Comment by madprops** [comment]
I'm also interested in this. 
I have a program that works by wrapping "cd" in shells like bash and fish and calling the "builtin" version at some points.
As you can see here: https://github.com/madprops/ezkl/blob/main/ezkl.fish.sh

**Comment by jooooscha** [comment]
Any update on this?

**Comment by ajeetdsouza** [comment]
Real-world use case for this: https://github.com/ajeetdsouza/zoxide/issues/511

**Comment by KoviRobi** [comment]
I think this is now possible -- I like to alias `g` to `git`, and the following works for me:
```
~ at 23:37:03 nu
❯ alias shell = ( hide g; g )

~ at 23:37:06 nu
❯ alias g = git

~ at 23:37:18 nu
❯ g | lines | take 2
╭───┬────────────────────────────────────────────────────────────────────────────╮
│ 0 │ usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]  │
│ 1 │            [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path] │
╰───┴────────────────────────────────────────────────────────────────────────────╯

~ at 23:38:01 nu
❯ shell
╭───┬────────┬───────────╮
│ # │ active │   path    │
├───┼────────┼───────────┤
│ 0 │ true   │ /home/rmk │
╰───┴────────┴───────────╯

```

**Comment by kubouch** [comment]
Theoretically, it should work with `hide` and overlays, but there is still something not working correctly, most likely related to predeclarations in the parser.

**Comment by KoviRobi** [comment]
This also breaks the tests, if you have the [`st` terminal emulator](https://st.suckless.org/) installed:

<details><summary>Test error output</summary>

```
failures:

---- commands::all::checks_if_all_returns_error_with_invalid_command stdout ----
=== stderr
couldn't read from shell: Input/output error
child exited with status 1
Error: nu::shell::type_mismatch (link)

  × Type mismatch.
   ╭─[source:1:1]
 1 │ [red orange yellow green blue purple] | all {|it| ($it | st length) > 4 }
   ·                                                                     ┬
   ·                                                                     ╰── compatible type
   ╰────


thread 'commands::all::checks_if_all_returns_error_with_invalid_command' panicked at 'assertion failed: actual.err.contains(\"can\'t run executable\") ||\n    actual.err.contains(\"did you mean\")', crates/nu-command/tests/commands/all.rs:68:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- commands::any::checks_if_any_returns_error_with_invalid_command stdout ----
=== stderr
couldn't read from shell: Input/output error
child exited with status 1
Error: nu::shell::type_mismatch (link)

  × Type mismatch.
   ╭─[source:1:1]
 1 │ [red orange yellow green blue purple] | any {|it| ($it | st length) > 4 }
   ·                                                                     ┬
   ·                                                                     ╰── compatible type
   ╰────


thread 'commands::any::checks_if_any_returns_error_with_invalid_command' panicked at 'assertion failed: actual.err.contains(\"can\'t run executable\") ||\n    actual.err.contains(\"did you mean\")', crates/nu-command/tests/commands/any.rs:44:5


failures:
    commands::all::checks_if_all_returns_error_with_invalid_command
    commands::any::checks_if_any_returns_error_with_invalid_command

test result: FAILED. 946 passed; 2 failed; 6 ignored; 0 measured; 0 filtered out; finished in 19.39s

error: test failed, to rerun pass `-p nu-command --test main`
```
</detail>

and as `st` is not an alias I guess we cannot hide it?

**Comment by kubouch** [comment]
The `st` test error would probably better be fixed by changing the test to something else that is not a likely binary name (not sure what the test is supposed to test, is the `st` to just generate an error?).

And yes, if a binary is in your PATH, you cannot `hide` it. You could still modify your PATH though.

**Comment by jntrnr** [comment]
This appears to be fixed now. If you still are noticing limitations, please re-open or file a new issue.

**Comment by BatmanAoD** [comment]
It looks like `hide` will hide aliases _and_ builtins? I'm not really sure what's happening here. Prior to the `hide`, my `ls` was aliased to `eza`:

```
RM-LOSX-0F2WP14 in ~/tmp
❯ : hide ls

RM-LOSX-0F2WP14 in ~/tmp
❯ : which ls
╭───┬─────────┬─────────┬──────────╮
│ # │ command │  path   │   type   │
├───┼─────────┼─────────┼──────────┤
│ 0 │ ls      │ /bin/ls │ external │
╰───┴─────────┴─────────┴──────────╯
```

**Comment by Ezall2001** [comment]
i am also experiencing this

I have `alias ls = eza`
if i run `hide ls`
it hides both the alias an the built-in

nu version: 0.104.1

**Comment by kaem-e** [comment]
same issue here

**Comment by stevenxxiu** [comment]
Duplicate of #3792.
