### ISSUE TITLE
Panic when clicking in windows terminal

### ISSUE THREAD

**Issue by Therzok** [nushell/nushell#4101]
### Describe the bug

Panic in windows terminal and powershell 7+ with chart usage.

```
hread '<unnamed>' panicked at 'Event flag 3 does not exist.', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm_winapi-0.7.0\src\structs\input.rs:201:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### How to reproduce

`ps | select name mem cpu | chart line name`

Clicking on the terminal screen is fine, but when holding down left click and moving about the following error is logged

### Expected behavior

Doesn't crash, not sure what it should behave like

### Screenshots

![image](https://user-images.githubusercontent.com/109974/139559462-a7316f13-914a-499d-9704-c7538ffc8e8c.png)

### Configuration

|key_value|Column1|
|-|-|
|version|0.38.0|
|short_commit|e1ebd461|
|commit_hash|e1ebd461d24927deb48ac758f9b456a21b479065|
|commit_date|2021-10-05 17:35:25 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.55.0 (c8dfcfe04 2021-09-06)|
|rust_channel|stable-x86_64-pc-windows-msvc (default)|
|cargo_version|cargo 1.55.0 (32da73ab1 2021-08-23)|
|pkg_version|0.38.0|
|build_time|2021-10-05 18:08:23 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by jntrnr** [comment]
Should be fixed in latest main with reedline
