### ISSUE TITLE
How to source .profile etc

### ISSUE THREAD

**Issue by spease** [nushell/nushell#4103]
### Related problem

Using nushell with nix, and there are shell files that need to be sourced to set required variables

### Describe the solution you'd like

A way to source files. In my case, I have added the requisite source commands to .profile. It would be most convenient if I could have nushell source it.

### Describe alternatives you've considered

source ~/.profile

This did not seem to set any environment variables

**Comment by kubouch** [comment]
Do these .profile files follow the Nushell syntax? Nushell can read only Nu code now, you'd have to translate them if they don't. Could you provide more details on what you're trying to do?

In general, one method to load environment variables from a file is to make the file return a nu table with "name" and "value" columns, like this: `[[name value]; [SOME_PATH /usr/foo/path]]`, then use `load-env` to activate the env vars from the table. If you know the name of the env var in advance, you can use `let-env`. There is also `pathvar` to modify PATH-like variables.

**Comment by spease** [comment]
Thanks. Good question, and I found subtle differences in nushell that seem to make it incompatible with setting environment variables (no export keyword, needing spaces around equals vs no spaces) and aliases. So, no, I later found out it wouldn't work.

ion's solution to this was to have a `source-sh` command that at least recognized simple environment variable setting patterns. I'd suggest either the same thing and/or autodetecting #!/bin/sh (though this is probably less common on sourced scripts).

It's extremely frustrating when a shell goes off and introduces tiny changes in the syntax (but nothing revolutionary) that mostly serve to introduce an unnecessary learning curve and prevent leveraging the existing body of support for shells. I had to deal with this with ion and I'm reasonably sure it introduced a roadblock to adoption that most people don't want to deal with. I wound up painstaking rewriting my .profile to work with the subset of primitives that both sh-style and ion-style shells used with use of source-sh for nix (package manger) scripts. I don't think that's going to be possible with nushell though. 

While I don't expect 100% compatibility and obviously do want things that aren't in other shells, keeping the simple stuff the same, or at least capable of accepting input from existing syntax where the fundamentals are concerned but autoformatting to something cleaner, makes it much easier for the shell to be a drop-in replacement to get started.

But if there really are strong arguments for a hard requirement for spaces, no export keyword, etc, I think the bimodal interpreting is the best of both worlds. Maybe a limited compatibility interpreter should be a separate Rust crate so that shells can easily hand things off to it and get back a list of aliases, environment variables, macros, and configuration state.

**Comment by kubouch** [comment]
I wouldn't call Nushell "revolutionary" but certainly it is "very different" from other shells. In some design aspects it takes completely orthogonal direction. For example, Nushell is 100% immutable while POSIX shells like Bash frequently mutate the global state  -- this is the reason why `export` cannot work the same way in Nushell as it does in Bash. Basically, Nushell tries to reimagine what could a shell look like if we started from scratch and that implicitly makes POSIX compliance a non-goal. I don't know all the technical aspects, but space is used as a token separator which makes it impossible to not require the space -- I imagine doing so would complicate the parser significantly. Also, the syntax with spaces is easier to read and again, we prioritize user friendliness to POSIX compliance.

I can imagine having a support for a small subset of POSIX syntax, not as a part of the Nushell language but as an external tool. We were already thinking about adding the support for `.env` files which follow the `NAME=value` syntax. If I data mine your post further, another missing feature would be defining aliases -- in the new engine, these two are planned to be a part of the upcoming module system. We then have a plugin system, so anybody can write a "nu-posix-translate" plugin that would read a simple POSIX script and give you a Nushell module that you can activate and bring in the env vars and aliases.

I think if you do `export FOO=bar` in Bash (maybe also dash?), then run or exec nu, you should have `$nu.env.FOO` available in Nushell. That could be a viable approach if you don't want to translate your scripts.

**Comment by spease** [comment]
Thanks, that's useful to know. However, wrt immutability, can't you still set config variables, including the path, from the prompt? Or do you just mean while a script is running? (Didn't try that)

In any case, I spent some time this morning and I think I got a set of dotfiles that seem to do what I want (alacritty, tmux, nu, nix, my custom Rust-based prompt (though I might switch to starship), macOS and Linux, red coloring for night work).

https://github.com/spease/config

In the past, at one company, I built up a set of aliases to help me with work for filing tickets, deploying software, etc. from the command line. Currently I only have one command really, for managing my dotfiles, so that was simple enough to workaround.

My workaround is basically what I said - launch sh with tmux, setup everything, then exec into nushell. This turns out to be necessary in my case, since I'm sharing the config with multiple computers which may or may not have nushell installed via nix or on the system, and tmux only lets you set a shell binary with arguments (not a full command as the tmux documentation suggests).

**Comment by jansol** [comment]
As another NixOS user, may I ask what nix-specific problems you are encountering? I have nu set as the shell in Alacritty (but not as my login shell) and nix is working just fine.

**Comment by spease** [comment]
I’m actually using nix and not NixOS. Since I changed things around to launch sh as a login shell in each tmux pane and then exec nu from .profile, I haven’t been having issues with nix anymore. It did take some doing to figure out the exact combo to get what I wanted tho.

**Comment by jansol** [comment]
One thing that would already help immensely would be being able to specify certain environment variables as "pass-through" i.e. have them visible inside nu with the same values that nu gets from its parent process. This should make things like ssh-agent work correctly again. (Currently for ssh-agent to work in nu on nixos I need to have hardcoded SSH_AUTH_SOCK which contains my uid and thus isn't very portable. At least it stays consistent across reboots.)

**Comment by kubouch** [comment]
@jansol Can you expand the ssh-agent problem into a separate issue? I remember, I had to set SSH_AUTH_SOCK to make it working but forgot what the problem was exactly.

I didn't understand your "pass-through" description. I'm not sure about Nushell, but engine-q at least collects the parent's environment variables when it starts, then passes all of its environment variables to any child process it spawns.

**Comment by kubouch** [comment]
@spease Sorry, I forgot about your follow-up question. 

You are right, in Nushell, setting a config modifies the global state. In engine-q, however, the config is currently a normal variable, and therefore is scoped and immutable -- whenever you exit the scope, you lose the modifications.

**Comment by luccahuguet** [comment]
I'll add that, for me to get it working, I simply added this to my login.nu:

`let-env PATH = ($env.PATH | split row (char esep) |
│ │ │ │ │ │ │ │ │ append 'example/path/1' |
│ │ │ │ │ │ │ │ │ append 'example/path/2' |
    ...
│ │ │ │ │ │ │ │ │ append '/path/to/home/.nix-profile/bin' |
│ │ │ │ │ │ │ │ │ append '/nix/var/nix/profiles/default/bin'
│ │ │ │ │ )`

this way I did not need that .sh file, which was written in bash

**Comment by mokeyish** [comment]
Hi, I want to source .profile with following command.

```sh
let extra_env = (bash -c "source .profile && env" | lines  | parse "{n}={v}" | filter { |x| (not $x.n in $env) or ($x.v) != ($env | get $x.n) } | where n != "_")
```

But now it results:
```txt
╭───┬────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ # │       n        │                                                                             v                                                                              │
├───┼────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 0 │ LAST_EXIT_CODE │ 1                                                                                                                                                          │
│ 1 │ DIRS_POSITION  │ 0                                                                                                                                                          │
│ 2 │ MK123          │ 153                                                                                                                                                        │
│ 3 │ PATH           │ /home/abc/.local/bin:/home/abc/bin:/home/abc/.sdkman/candidates/maven/current/bin:/home/abc/.sdkman/candidates/java/current/bin:/home/abc/.cargo/bin: │
│   │                │ /home/abc/.deno/bin:/home/abc/.local/bin:/home/.share/conda/condabin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games                            │
╰───┴────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

How to convert it to `{MK123: 153 , PATH: xxx} | load-env`

**Comment by amtoine** [comment]
@mokeyish 
if there is always `LAST_EXIT_CODE` and `DIRS_POSITION` in the first two positions and you want to load all the others, you should be able to do
```nushell
$extra_env | skip 2 | transpose -r | into record | load-env
```
:yum:

**Comment by mokeyish** [comment]
@amtoine Thanks, it works for me 😋. 

Here is the final command.

```shell
bash -c $"source ($env.HOME)/.profile && env" | lines  | parse "{n}={v}" | filter { |x| (not $x.n in $env) or ($x.v) != ($env | get $x.n) } | where not n in ["_", "LAST_EXIT_CODE", "DIRS_POSITION"] | transpose -r | into record | load-env
```

If anyone can further optimize this command, please let me know.

**Comment by c1m50c** [comment]
> > Thanks, it works for me yum.
> 
> happy it works 😌
> 
> > If anyone can further optimize this command, please let me know.
> 
> maybe you could combine the `filter` and the `where` but it's pretty good 👌
> 
> 💡 because it's so long, i'd break the line on the pipes
> 
> ```nushell
> bash -c $"source ($env.HOME)/.profile && env"
>     | lines
>     | parse "{n}={v}"
>     | filter { |x| (not $x.n in $env) or $x.v != ($env | get $x.n) }
>     | where not n in ["_", "LAST_EXIT_CODE", "DIRS_POSITION"]
>     | transpose --header-row
>     | into record
>     | load-env
> ```

For people using versions `>=0.9.0`, ensure you replace the _not in_ operations with _not-in_, here's the updated version of this code:

```nushell
bash -c $"source ($env.HOME)/.profile && env"
    | lines
    | parse "{n}={v}"
    | filter { |x| ($x.n not-in $env) or $x.v != ($env | get $x.n) }
    | where n not-in ["_", "LAST_EXIT_CODE", "DIRS_POSITION"]
    | transpose --header-row
    | into record
    | load-env
```

**Comment by tesujimath** [comment]
I just noticed this when looking for something else.

Perhaps you'd enjoy my [bash-env plugin](https://github.com/tesujimath/nu_plugin_bash_env)?

**Comment by ninelore** [comment]
Here's an updated version of above snippet

Changes:
- Instead of sourcing .profile start bash as login shell, which sources everything relevant 
- Replaced deprecated `filter` with `where`
- More ignores

```nushell
bash -lic env
    | lines
    | parse "{n}={v}"
    | where n not-in $env or v != ($env | get $it.n)
    | where n not-in ["_", "LAST_EXIT_CODE", "DIRS_POSITION", "SHLVL", "STARSHIP_SHELL", "STARSHIP_SESSION_KEY"]
    | transpose --header-row
    | into record
    | load-env
```
