### ISSUE TITLE
Dead end with background process

### ISSUE THREAD

**Issue by yozhgoor** [nushell/nushell#4104]
### Describe the bug

Hello! To start my first issue on this project, I want to say that Nushell is amazing!

I have a problem related to Neovim that doesn't appear with Bash.

I start a new editor with nvim and i sometimes use `Ctrl+z` to use the shell and type some commands. If i open Neovim with Nu, the process is blocked and i can't get access to the shell.

Since i can't type `fg` to go back into Neovim, i need to quit the process. (It's possible that you can go back in another way, but i don't really know how).

### How to reproduce

1. Open neovim from nushell
2. Type `ctrl+z` to move neovim process in background
3. Now you are stuck

### Expected behavior

When i send the Neovim process to the background, i expect to be able to get access to the shell, type some command like usual and be able to move the neovim process to the foreground again with typing `fg`

### Configuration

|key|value|
|-|-|
|version|0.39.0|
|build_os|linux-x86_64|
|rust_version|rustc 1.56.0 (09c42c458 2021-10-18)|
|rust_channel|stable-x86_64-unknown-linux-gnu (default)|
|cargo_version|cargo 1.56.0 (4ed5d137b 2021-10-04)|
|pkg_version|0.39.0|
|build_time|2021-10-31 22:33:24 +01:00|
|build_rust_channel|release|
|features|ctrlc, dataframe, default, rustyline, term, which, zip|
|installed_plugins|fetch, match, post, ps, sys|

**Comment by kubouch** [comment]
I think this is not supported in Nushell at the moment, but in engine-q, we just added a support for background / parallel tasks and usage like this should be possible in the future.

**Comment by jntrnr** [comment]
Tasks didn't make it into engine-q, but so I'll remove the label. We would like to support them, and the work will likely build on the new engine.

**Comment by hustcer** [comment]
Seems to be a dupe of https://github.com/nushell/nushell/issues/1038

**Comment by jntrnr** [comment]
Closed as dupe of #1038
