### ISSUE TITLE
Impossible to `ls` an external subexpression that prints a path as a string

### ISSUE THREAD

**Issue by aminya** [nushell/nushell#4108]
### Describe the bug

It is not possible toImpossible to `ls` an external subexpression that prints a path as a string.

### How to reproduce

```nu
let x = (an_external_command_that_prints_a_path)
ls $x
```
or

```nu
let x = (an_external_command_that_prints_a_path | into path)
ls $x
```

or

```nu
let x = (an_external_command_that_prints_a_path | path parse)
ls $x
```

None of them work

### Expected behavior

The string to path conversion should be automatic.

### Screenshots

![image](https://user-images.githubusercontent.com/16418197/140596534-3e03aed0-c3e4-439d-a867-86a1000aea98.png)

or

![image](https://user-images.githubusercontent.com/16418197/140596539-821b75ef-cee5-41f3-b5bc-e7209d8d8484.png)

### Configuration

|key|value|
|-|-|
|version|0.39.0|
|short_commit|2b06ce27|
|commit_hash|2b06ce27d3b7d9eec65686586f1c469f908dc7f2|
|commit_date|2021-10-26 19:36:41 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.56.0 (09c42c458 2021-10-18)|
|rust_channel|stable-x86_64-pc-windows-msvc (default)|
|cargo_version|cargo 1.56.0 (4ed5d137b 2021-10-04)|
|pkg_version|0.39.0|
|build_time|2021-10-26 20:04:24 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by aminya** [comment]
Also pipelines do not work for `ls`

```nu
echo $path | ls
```

**Comment by kubouch** [comment]
`ls (pwd)` and `ls | (pwd | into path)` both work for me. `ls` should accept both strings and paths. You can check the types like this:
```
> pwd | describe
string

> pwd | into path | describe
path
```

The error you're getting looks like the command gives you a path that does not exist. Could it be that?

The `path parse` case is different. If you look at the output of `path parse`, you see it gives you a table, which `ls` currently does not accept. It might be worth letting commands accept also these parsed path tables, but that would need some design work.

**Comment by fdncred** [comment]
since you're using an external you might want to try string interpolation. there's a [pr](https://github.com/nushell/nushell/pull/3686) that is supposed to make it work like this: `^$"(ros2 pkg prefix --share std_msgs)"`

**Comment by jntrnr** [comment]
This should now work a lot better with the latest main, which uses a new engine and one of the fixes is to work better across strings and filepaths.
