### ISSUE TITLE
Show number of errors when running commands with `each`

### ISSUE THREAD

**Issue by alexkreidler** [nushell/nushell#4110]
### Related problem

First off, hats off to you all, NuShell is brilliant. I remember seeing it a few years ago in an earlier state and not trying it, but when I did today, I searched around the docs for a few minutes, and I was able to write this one-liner that is quite a bit more understandable than the equivalent bash:

```bash
ls **/*.json | each { open $it.name | get description | str length } | math avg
659.7426621160409556313993174061433447098976109215017064846416382252559726962457337883959044368600683error: Unknown column
   ┌─ shell:37:43
   │
37 │ ls **/*.json | each { open $it.name | get description | str length } | math avg
   │                                           ^^^^^^^^^^^
   │                                           │
   │                                           There isn't a column named 'description'
   │                                           Perhaps you meant 'abc'? Columns available: abc
```
It looks for every JSON file in immediate subdirectories, and calculates the average length of the `description` field for the files.

### Describe the solution you'd like

I'd like this command to show me how many commands (for each file in my case) errored out, ideally with a table for every type of error and the number of times it occurred. 

Otherwise, it's great that there is a final successful value even with some errors in the pipeline.

I'm not sure how complicated this would be for the internals and there are probably many options for what the UX should be (eg `my-commands | more-of-them | get-errors` to return a table). This could also open some possibilities for some commands to operate on errors like regular data, filtering or sorting them. Thanks!

**Comment by kubouch** [comment]
I think @andrasio once looked into making errors regular values so they could be manipulated further. We need to look into this stuff again, I also miss better error handling -- like you suggested, collecting the errors into the table and analyze them one-by-one, etc.

So far, the only "error control" we have now is `do -i { ... }` which will ignore errors inside the block.

**Comment by jntrnr** [comment]
As @kubouch mentions, you'd have to ignore the errors and count the errors yourself. By default, an error like this one should halt the pipeline processing.

With that, we'll close this as it's possible to do this, if you want to, but it wouldn't be part of the pipeline processing logic.
