### ISSUE TITLE
can not support flutter.bat command

### ISSUE THREAD

**Issue by Silentdoer** [nushell/nushell#4112]
### Describe the bug

i have installed flutter, i can run flutter --version or flutter.bat --version in cmd, but can not run in nushell;

OS: windows 10
version: 0.39.0

### How to reproduce

run a .bat command

### Expected behavior

run succeed

**Comment by fdncred** [comment]
can you show the error and perhaps the contents of `flutter.bat`?

**Comment by Silentdoer** [comment]
i am sorry, when i restart my computer, it's run ok
