### ISSUE TITLE
Appending to a file fails if the file does not exist

### ISSUE THREAD

**Issue by sensationallulu** [nushell/nushell#4113]
### Describe the bug

wtf is the way of appending to a file,
this shell converts the simple 
 echo "hello mama" >> README.md 
into this abomination....
 echo "hello mama" | save --raw --append ./README.md
and... the empty file needs to exist, other wise it wil output an error.....
i don't see the point in changing that, whats the point? and why it needs to be created an empty file, while in bash, a supposed inferior shell, its pretty easy and intuitive to do?

### How to reproduce

$ echo "# hello kitty" | save --raw --append ./README.md
error: No such file or directory (os error 2)
   ┌─ shell:72:25
   │
72 │ echo "# hello kitty" | save --raw --append ./README.md
   │                         ^^^^ IO error while saving

### Expected behavior

Create and append the text echoed

### Screenshots

Not needed

### Configuration

|key|value|
|-|-|
|version|0.39.0|
|build_os|linux-x86_64|
|rust_version|rustc 1.56.0|
|cargo_version|cargo 1.56.0|
|pkg_version|0.39.0|
|build_time|2021-10-26 21:37:29 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by fdncred** [comment]
ya, append should probably create the file if it doesn't exist but technically append means to add to something that already exists. so if you do this, it works fine.
```
touch README.md
echo "hello mama" | save --raw --append ./README.md
```
also, redirects like `>>` are not supported in nushell, which is why they don't work. We should probably error out with a better message though.
