### ISSUE TITLE
Multi-word commands

### ISSUE THREAD

**Issue by vwkd** [nushell/nushell#4114]
### Describe the bug

In programming languages there are some constructs that use multiple words in different positions, e.g. `for .. in ..` or `if .. then .. else ..`.

Currently, nushell models those constructs sometimes as commands with multiple words like the `for $x in $y` command and sometimes with a single word like the `if $x $y $z` command. This is a bit inconsistent.

If I understand correctly, under the hood a nushell (sub)command can consist only of a single word. The "in" in `for $x in $y` is actually just a parameter that must take the constant value "in".

It would make sense to go all-in on expressiveness and allow commands to have multiple words. Then `for $x in $y` wouldn't need to model "in" as a parameter and the `if` command could be made more expressive as `if $x then $y else $z`.

Alternatively, one could decide to never use multi-word commands. This would make the language less expressive and potentially more difficult to extend in the future. If so, the `for` command should be shortened to `for $x $y` to be consistent.

### How to reproduce

```
> help for
Run a block on each row of the table.

Usage:
  > for <var> <in> <value> <block> {flags} 

Parameters:
  <var> the name of the variable
  <in> the word 'in'
  <value> the value we want to iterate
  <block> the block to run on each item
```

### Expected behavior

```
> help for
Run a block on each row of the table.

Usage:
  > for <var> in <value> <block> {flags} 

Parameters:
  <var> the name of the variable
  <value> the value we want to iterate
  <block> the block to run on each item
```

### Configuration

|key|value|
|-|-|
|version|0.39.0|
|build_os|macos-x86_64|
|rust_version|rustc 1.56.0|
|cargo_version|cargo 1.56.0|
|pkg_version|0.39.0|
|build_time|2021-10-26 19:36:41 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by jntrnr** [comment]
This is now supported in nushell's latest main
