### ISSUE TITLE
how to "cd /lib/modules/(uname -r)"

### ISSUE THREAD

**Issue by gipsyh** [nushell/nushell#4117]
I want to ask how to "cd /lib/modules/(uname -r)" in nushell
thanks

**Comment by kubouch** [comment]
This should do the trick: `cd $"/lib/modules/(uname -r)"`. 

You can also join paths like this in a cross-platform way: `"/lib/modules" | path join (uname -r)"`

The `$"..."` construct is called string interpolation and expands any `(...)` inside.

**Comment by kubouch** [comment]
I think the answer should be sufficient so I'll close this.

Please, feel free to ask on Discord or GitHub Discussions if you have more questions. We prefer issues to be used for bug reports and feature requests.
