### ISSUE TITLE
Any way to reduce binary size?

### ISSUE THREAD

**Issue by wilem82** [nushell/nushell#4119]
I wanted to try writing scripts in Nushell on my small cloud vm which doesn't even have enough RAM to build Rust projects from source. So I downloaded Nushell from Github releases and it's 454mb, for a shell? Honestly, it feels like an Electron app. :) I'm not sure whether I need all those Nu plugins in the distribution bundle, but even just the Nu itself is ~50mb, 34 after stripping. Love Nushell, but this makes my brain explode. Is that a temporary setback in Nu's design, or a downside to using Rust in general? Thank you for any explanations.

**Comment by jntrnr** [comment]
There's some discussion in a different issue about it: https://github.com/nushell/nushell/issues/3896

We're also working on an engine to replace the current engine-q one, which may be able to help as well. Closing this issue in favour of #3896
