### ISSUE TITLE
piping: internal -> external is very limited

### ISSUE THREAD

**Issue by indeyets** [nushell/nushell#412]
it looks like it is impossible to pipe output from nu-commands to external apps (via stdout). 

an easy way to test: `ls | autoview | /usr/bin/less`

**Comment by wycats** [comment]
It sort of works if the internal command produces a list of string values, but that's a rather narrow case, and we don't have stuff like `join` (or, in general, the opposite of `parse` to make it easy).

I hit this sort of problem a lot while dogfooding.

**Comment by andrasio** [comment]
#900
