### ISSUE TITLE
Upgrading polars from 0.16 to 0.17

### ISSUE THREAD

**Issue by nmandery** [nushell/nushell#4121]
### Related problem

I wanted to use the `dataframe` command with a parquet file containing `UInt64` columns, but this currently not supported as that datatype is feature-gated in polars 0.16

```
error: Invalid Operation
  ┌─ shell:5:16
  │
5 │ dataframe open ./data/prepared/10/fuel-stations-cellagg.parquet
  │                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Invalid operation Cannot create polars series from UInt64 type
```

### Describe the solution you'd like

There is a newer released version of polars available (`0.17.0`), which includes the `UInt64` datatype. There are quite a few other changes in that version, with a major one being the refactoring of all temporal datatypes including the dropping of the "duration" datatypes (https://github.com/pola-rs/polars/pull/1361). There may be more changes relevant for nushell, but I have not lookied into that in depth.

I could prepare a PR for that upgrade, but I want to ask beforehand if that breaking change would have a chance of accpetance.

### Describe alternatives you've considered

Simply enabling the required feature gate for polars 0.16.

**Comment by elferherrera** [comment]
Hi. If you want to submit a PR with the upgrade go ahead. Probably you will have to change some things in the dataframe commands. I expect nothing major
