### ISSUE TITLE
Any plans to implement osquery support?

### ISSUE THREAD

**Issue by blurayne** [nushell/nushell#413]
Of course this should be optional.

**Comment by wycats** [comment]
This is cool!

How do you think it would be integrated?

**Comment by wycats** [comment]
I looked into this more and it looks like there's a Rust version of osquery called [siquery](https://crates.io/crates/siquery). It seems like it would be straight-forward to integrate.

I get the basic idea: osquery is also "table-oriented" and it seems like it would be a good fit with our table oriented approach.
