### ISSUE TITLE
`keep while` seems not work as expected ?

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4130]
### Describe the bug

`help keep while` shows no example, and if I ran `[1, 3, 2] | keep while $it > 1` output nothing, did I use it in the wrong way?

### How to reproduce

Just Run `[1, 3, 2] | keep while $it > 1` to see the result

### Expected behavior

Expected output:
```
  0   3
  1   2
```

### Configuration

|key|value|
|-|-|
|version|0.39.0|
|build_os|macos-x86_64|
|rust_version|rustc 1.56.0 (09c42c458 2021-10-18)|
|rust_channel|stable-x86_64-apple-darwin (default)|
|cargo_version|cargo 1.56.0 (4ed5d137b 2021-10-04)|
|pkg_version|0.39.0|
|build_time|2021-10-27 12:31:41 +08:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by jntrnr** [comment]
For your example, `keep while` wouldn't return anything. `keep` starts at the first element and takes some number of elements. With `keep while`, if it can't take the first element it'll just stop.

You may be looking for `where` to filter elements out that match the condition.

**Comment by hustcer** [comment]
@jntrnr I see, thanks

**Comment by fdncred** [comment]
an example here for those who come here later.
```
[1 1 1 2 1] | keep while $it == 1
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 1 │
│ 2 │ 1 │
╰───┴───╯
```
