### ISSUE TITLE
10 times more memory usage due to using UPX

### ISSUE THREAD

**Issue by aminya** [nushell/nushell#4131]
### Describe the bug

In version 0.40, the memory usage of nu has increased significantly, it is now almost 32 MB, while for version 0.39.0 it was only 3 MB.

Using UPX to compress binaries is not a good idea. It just moves the hard disk space into the memory space, while also slowing down the startup. It is now impossible to use `nu` in small embedded systems with limited memory.

### How to reproduce

Open nu 0.40.0 
Open nu 0.39.0

Compare the memory usage in the task manager

### Expected behavior

Not sacrificing performance for binary size. The 0.39.0 binary can be 7zipped and the resulting size would be the same as the UPXed binary.

### Screenshots

The top nu is 0.40 and the bottom is 0.39. The column shows the memory usage

![image](https://user-images.githubusercontent.com/16418197/142527090-1ff1802b-154c-4f6e-9f55-7ae3a4fd975e.png)

### Configuration

|key|value|
|-|-|
|version|0.40.0|
|short_commit|2590fcbe|
|commit_hash|2590fcbe5c7721fe9835657de284e14c0602ecad|
|commit_date|2021-11-16 08:53:03 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.56.1 (59eed8a2a 2021-11-01)|
|rust_channel|stable-x86_64-pc-windows-msvc (default)|
|cargo_version|cargo 1.56.0 (4ed5d137b 2021-10-04)|
|pkg_version|0.40.0|
|build_time|2021-11-16 09:50:28 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by fdncred** [comment]
This is a bummer. Apparently, we can either have 10x binary size, which people complain about, or big memory size. I'm not sure which is worse.

**Comment by aminya** [comment]
If the download size is an issue, the binaries should be compressed using common compression methods such as 7z, tar.xz
The compressed size of a normal binary is identical to the UPXed size.

If the installation size is an issue the plugins should be downloaded dynamically on demand instead of by default. 

This also affects the startup time. As we know memory and CPU are expensive, but storage is cheap. So we should not choose the incorrect optimization goal. The binary size optimization is just a non-ending rabbit hole.  In my opinion, this is a bad misconception internalized in the minds of the developers.

**Comment by kubouch** [comment]
I agree it's better to have larger storage size than memory consumption.

@aminya I'm just curious, do you use nushell on an embedded device?

**Comment by pedoc** [comment]
I did not find this problem on my computer.

But this may be related to the installation method?  I installed it from ``cargo``.

OS:
win10 21H2(19044.1379)

![image](https://user-images.githubusercontent.com/6604230/142625505-627a5b20-4fc6-4737-96d2-0c6caab38c35.png)
![image](https://user-images.githubusercontent.com/6604230/142625740-dcf4deb7-d694-4fe1-97b2-fcc6309b3e72.png)

**Comment by fdncred** [comment]
I believe one would only see this problem if they use the (already zipped) binaries in the releases section of github starting with [0.40.0](https://github.com/nushell/nushell/releases/tag/0.40.0)

**Comment by mhmdanas** [comment]
Although I am one of the people advocating reducing the size of the binaries, when I heard that Nu 0.40.0 uses UPX I immediately thought this would be an issue, so I think this needs to be re-considered.

**Comment by feep** [comment]
Close this?

Bye bye upx sorry #4173
