### ISSUE TITLE
Kali style terminal needed

### ISSUE THREAD

**Issue by ssrlive** [nushell/nushell#4133]
### Describe the solution you'd like

Can you please provide kali linux terminal style? like this:

![image](https://user-images.githubusercontent.com/30760636/142722142-62f96d97-dad2-42c6-bf88-1fdd4cfa52d9.png)

thus, When we run into deeper directory, we can clearly tape into our long command in the console and the same time we can see the full path we located.

In addition, when we enter a command, if the command does not yet exist in the system, it will be displayed in red; if it exists, it will be displayed in other color. How about it?

**Comment by kubouch** [comment]
Can you describe better what your suggestion is? I did not understand your first suggestion and I'm not familiar with Kali Linux terminal.

Your second suggestion (display unknown command in red) might be doable. I split it off into a separate issue: #4134. For a future reference, it's better to create separate issues if you have multiple topics to discuss.

**Comment by ssrlive** [comment]
I have make an image to describe it. I hope you can understand my means.

In this way, we can know where we are at a glance.
At the same time, a path that is too long will not interfere with the complete input of long commands.

![image](https://user-images.githubusercontent.com/30760636/142724021-1dae9f78-cddb-4cff-9238-4c114be05a13.png)

**Comment by fdncred** [comment]
you can create your own prompt by changing the environment variable `PROMPT_COMMAND` and make it look just like your first screenshot if you like.

**Comment by ssrlive** [comment]
Is the input cursor stay always second line? @fdncred

**Comment by kubouch** [comment]
You can make it output anything you want. Try this:

```
> def build-prompt [] { $"(pwd)(char nl)> " }

> let-env PROMPT_COMMAND = build-prompt
```

Now you should see the prompt change. You can change the `build-prompt` command to output whatever you want. When you're done, you can put these into the startup section of the config.toml so it will loaded every time you run nushell.

**Comment by ssrlive** [comment]
Tested. it's OK. thanks.

**Comment by ssrlive** [comment]
In file `~/.config/nu/config.toml`, add the following lines:
```
startup = [
    "def build-prompt [] { $\"(char lparen)($nu.env.USER)@((sys).host.hostname)(char rparen) - [(pwd)](char nl)$ \" }",
    "let-env PROMPT_COMMAND = build-prompt"
]
```
