### ISSUE TITLE
Display unknown external commands in red in the prompt

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4134]
### Describe the solution you'd like

When typing in a command, paint it in red if it wasn't found. The parser could check with the `which` feature whether the command exists and output an error if not.

It has a side effect though that when you start typing, it would be red until you finish typing the command name. Therefore, it should be configurable.

The `which` calls might also have some overhead so we should watch out for that, too.

### Additional context and details

Originally suggested in #4133. I'm splitting it off into a separate issue for clarity.

**Comment by elferherrera** [comment]
I was thinking about this one. We can add this check in the run external command, but they the error will appear when the command get evaluated. For the parser I think we would have to run `which` all the time for every command typed when not found in the list of available decls

**Comment by mike-lloyd03** [comment]
Hey I'd really like to see this feature implemented. If someone could point me in the right direction, I'll look into opening a PR.

Some quick notes:
- To avoid lots of overhead, we could just create a list of all commands on path when the shell starts. If a new command gets installed, the user will have to restart the shell or perhaps run some refresh command.
- It's possible we could watch the directories on the path for changes and if so, it would trigger a reload of the valid commands list

oh-my-zsh seems to use a cache for accomplishing this:
https://github.com/zsh-users/zsh-syntax-highlighting/blob/122dc464392302114556b53ec01a1390c54f739f/highlighters/main/main-highlighter.zsh#L159

**Comment by kubouch** [comment]
@mike-lloyd03 Seems like most concerns are about performance on Windows. One solution that would minimize the complexity and maintenance cost in Nushell's code would be to have an `IS_KNOWN_EXECUTABLE` closure as an environment variable. By default it would be `{|| true}` corresponding to the current behavior. The syntax highlighter would run this closure and check the output for true/false to decide the highlighting color. How you'd implement the closure would be up to you. You could maintain the cache as a list in an environment variable, or store it in a file if it becomes too large. You could implement it either in Nu code or as a plugin for higher performance. The cache updating could be handled in the config on Nushell startup or in hooks, again using standard Nu code with no extra machinery required in the codebase. And also, importantly, even if we don't arrive at a fully cross-platform, high-performance solution right off the bat, maybe somebody else would be able to figure it out later on, without touching the source code.

We could also hard-code it into Nushell but then, we need to be sure we're cross-platform and personally, after thinking about it, I'm a fan of the freedom setting the environment variable would give you. Also, every piece of code added to Nushell's codebase increases the maintenance cost.

Either way, it seems the solution would be checking the PATH/Path/PWD directories so I would start by experimenting on different platforms, especially Windows and WSL, to see how fast the PATH/Path/PWD probing is and how often we can afford to update it. That should give us ideas how to go forward.

**Comment by mike-lloyd03** [comment]
Okay the plugin approach sounds good. I'm reading through the Rust docs on [`nu_protocol`](https://docs.rs/nu-protocol/0.71.0/nu_protocol/) as well as the [example](https://www.nushell.sh/contributor-book/plugins.html#plugins) in the docs but I'm unclear about how to create a plugin that impacts text highlighting. Are there more extensive docs for plugins I'm not seeing?

**Comment by kubouch** [comment]
My suggestion wasn't to make a plugin that affects the highlighting. What I suggested was that you'd have an environment variable IS_KNOWN_EXECUTABLE that the syntax highlighter would query. You'd implement it and the rest of the logic (e.g., populating the known commands cache) using nu code. This might involve a plugin.

The second option is to have the whole logic live inside Nushell which most of the core team seemed in favor of.

In either case, we need to make sure the system is fast on Windows and WSL so that would be the first point where I would start investigating.

**Comment by Hofer-Julian** [comment]
> In either case, we need to make sure the system is fast on Windows and WSL so that would be the first point where I would start investigating.

To add numbers to this.
Measuring `which` for a non-exisiting command `py` on Windows gives:
```powershell
$ hyperfine "which py" -i
Benchmark 1: which py
  Time (mean ± σ):       5.7 ms ±   1.2 ms    [User: 5.6 ms, System: 6.8 ms]
  Range (min … max):     4.5 ms …  11.2 ms    67 runs
```
So it seems like this isn't a problem.

However, the same isn't true for WSL:
```bash
$ hyperfine "which py" -i
Benchmark 1: which py
  Time (mean ± σ):     127.0 ms ±   4.4 ms    [User: 12.6 ms, System: 12.3 ms]
  Range (min … max):   119.1 ms … 137.4 ms    23 runs
```

I also had a look at fish's behavior.
Instead of caching known commands, it seems like they limit the rate they add syntax highlighting to your prompt:

https://user-images.githubusercontent.com/30049909/216594469-c856662a-80d0-4a96-9b83-83f0ec14f528.mp4

**Comment by jntrnr** [comment]
This would be cool, but it'd have to be off by default as not all platforms are going to be able to search the path quickly without performance overhead.

**Comment by weirdan** [comment]
I believe this is done already: https://asciinema.org/a/X1XbHFoJfRah0FRaN0TPQTGi4

**Comment by Hofer-Julian** [comment]
> I believe this is done already: https://asciinema.org/a/X1XbHFoJfRah0FRaN0TPQTGi4

Is this on by default though?

**Comment by weirdan** [comment]
There's `$env.config.highlight_resolved_externals` that controls this behaviour: https://github.com/nushell/nushell/blob/main/crates/nu-utils/src/sample_config/default_config.nu#L267

**Comment by kubouch** [comment]
Seems like that covers the use case, thanks!

**Comment by tombh** [comment]
The config link above is stale, here's a permalink: https://github.com/nushell/nushell/blob/d8c24936588659fed0f340543e2a7c6f5d35782e/crates/nu-utils/src/default_files/sample_config.nu#L523

```nu
# highlight_resolved_externals (bool):
# true: Applies the `color_config.shape_external_resolved` color (below) to external commands
#       which are found (resolved) on the path
# false: Applies the `color_config.shape_external` color to *all* externals simply based on whether
#        or not they would be *parsed* as an external command based on their position.
# Defaults to false for systems with a slower search path
$env.config.highlight_resolved_externals = true
```
