### ISSUE TITLE
Nushell is trying to display prompt when engine-q is launched?

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4136]
### Describe the bug

I'm not sure if it's a Nushell or engine-q issue. When I open engine-q with Nushell as a default shell, I get this (`config.nu` is empty):
```
Loading config from: "~/.config/nushell/config.nu"
sh: line 1: build-prompt: command not found
```

The `build-prompt` command is defined in my `~/.config/nu/init.nu` which is sourced by Nushell on startup. The relevant section of my Nushell's `~/.config/nu/config.toml` looks like this:

```toml
startup = [ "source ~/.config/nu/init.nu" ]

[env]
PROMPT_COMMAND    = "build-prompt"
```

Maybe Nushell is still trying to build the prompt even though engine-q is running?

### How to reproduce

1. Define `build-prompt` command inside `~/.config/nu/init.nu`
2. Put the toml snippet above into the Nushell's config.toml
3. Reload Nushell
4. Launch engine-q
5. Observe the "build-prompt: command not found" error

### Expected behavior

Expected no error messahe.

### Configuration

|key|value|
|-|-|
|version|0.40.0|
|branch|main|
|short_commit|2590fcbe|
|commit_hash|2590fcbe5c7721fe9835657de284e14c0602ecad|
|commit_date|2021-11-16 08:53:03 +00:00|
|build_os|linux-x86_64|
|rust_version|rustc 1.56.1 (59eed8a2a 2021-11-01)|
|rust_channel|stable (default)|
|cargo_version|cargo 1.56.0 (4ed5d137b 2021-10-04)|
|pkg_version|0.40.0|
|build_time|2021-11-16 17:14:30 +02:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by jntrnr** [comment]
What do you have inside of your `~/.config/nushell/config.nu` file?

**Comment by kubouch** [comment]
@jntrnr It does not seem to depend on the contents of config.nu. Currently, I have let-env LS_COLORS there but I get the same error even with empty file.

**Comment by kubouch** [comment]
Turns out engine-q inherits `PROMPT_COMMAND` from Nushell parent which then fails because the command I had in Nushell's `PROMPT_COMMAND` is not available under engine-q.
