### ISSUE TITLE
"cargo install nu" triggers recompilation every time

### ISSUE THREAD

**Issue by antoniocorbi** [nushell/nushell#4137]
### Describe the bug

Hi all!, first time here.
If I install nushell via "cargo install nu" it all goes ok, but every time I re-run "cargo install nu" it downloads and recompiles everyting each and every time, no matter if I've just done the last "cargo install nu" seconds away.

### How to reproduce

1. cargo install nu
2. cargo install nu

### Expected behavior

Do not recompile nushell if everything is up to date.

### Additional context

I'm using rustc 1.56.1 on GNU/Linux (ArchLinux).

**Comment by fdncred** [comment]
This documentation seems to indicate that cargo is running as it's intended, specifically this part.
```
If the source is crates.io or --git then by default the crate will be built in a temporary target directory. To avoid this, the target directory can be specified by setting the CARGO_TARGET_DIR environment variable to a relative path. In particular, this can be useful for caching build artifacts on continuous integration systems.
```

**Comment by antoniocorbi** [comment]
Thanks fdncred.

I don't have this problem with any of the other 'plugins' installed via 'cargo install xyz'.

**Comment by hustcer** [comment]
I don't have this issue on my mac, with rust v1.60 installed:
```shell
➜  nushell git:(main) cargo install nu
    Updating crates.io index
     Ignored package `nu v0.62.0` is already installed, use --force to override
➜  nushell git:(main) cargo install nu
    Updating crates.io index
     Ignored package `nu v0.62.0` is already installed, use --force to override
```
Can you try it with the latest rust?

**Comment by antoniocorbi** [comment]
Hi,

It also seems to be working with rust 1.60 under GNU/Linux now.

Antonio

**Comment by hustcer** [comment]
That's great! let's close it
