### ISSUE TITLE
Nushell on windows starts in C:\Windows\System32

### ISSUE THREAD

**Issue by martinlindhe** [nushell/nushell#4138]
### Describe the bug

Starting nu.exe gives you a prompt in C:\Windows\System32, where the user home folder would be a better default.

### How to reproduce

Open nu.exe on windows, notice the current directory is C:\Windows\System32

### Expected behavior

I expect to be greeted by my home directory.

### Screenshots

![image](https://user-images.githubusercontent.com/181531/142761325-d4209d5b-b096-4d28-8c9e-7332115c2f7f.png)

**Comment by fdncred** [comment]
This is controlled by your windows terminal profile for nushell. Got to settings in windows terminal and you can see where to change it.

**Comment by martinlindhe** [comment]
@fdncred First off, Windows Terminal puts me in HOME directory using powershell, cmd.exe, git-bash.exe and even WSL (bash) without changing the settings of Windows Terminal.
I am reporting this issue because the behavior differs with nushell vs every other shell I used on Windows.

Secondly, see screenshot, top part is CMD.EXE which does not have "profiles".

**Comment by fdncred** [comment]
This is controlled by Windows Terminal. If you google for how to set the startup folder, you'll find dozens of links like this one. https://zimmergren.net/set-the-default-starting-directory-in-windows-terminal/

**Comment by martinlindhe** [comment]
According to Microsoft's docs:
`Default behavior: When the startingDirectory value is not specified, you will get different results depending on where you launch Terminal`

This is inconsistent with nushell, see above.
I attempted to demonstrate with this video clip:

https://user-images.githubusercontent.com/181531/142763975-bd883a7f-f178-478e-b8d0-5b7874996c94.mp4

**Comment by fdncred** [comment]
Yes, I run windows most of the time and always use Window Terminal with it. I understand how this works. There are only three ways that I can think of to control the startup folder.
1. The ways I've already indicated, i.e. change the startupDirectory in the settings.json
2. Deliver a Windows Terminal Fragment with our installer and put in our repo, which we currently do not do but there is an issue for it for someone to contribute it. https://github.com/nushell/nushell/issues/3994 
3. I guess we could submit a PR to the Windows Terminal team specifically for nushell, but I doubt that would happen or be accepted.

If you have another way of controlling this, please let us know.
