### ISSUE TITLE
It doesn't supports "&&"

### ISSUE THREAD

**Issue by danimesq** [nushell/nushell#4139]
### Describe the bug

When typing `clear && git status`, it outputs:

> error: clear unexpected &&
>   ┌─ shell:2:7
>   │
> 2 │ clear && git status
>   │       ^^ unexpected argument (try clear -h)
> 

### How to reproduce

Just run `clear && git status` or any other commands using `&&`

### Expected behavior

Should work normally as it did in bash.

### Screenshots

![Screenshot from 2021-11-20 23-04-48](https://user-images.githubusercontent.com/6765277/142807087-f42bb093-b484-4cb5-b7ab-81532efd84f5.png)

### Configuration

>   ┌─ shell:1:1
>   │
> 1 │ > version | pivot key value | to md
>   │ ^ command > not found
>

**Comment by jntrnr** [comment]
in nushell, we use `&&` for conditions like `if $x < 10 && $y < 13`. For the bash style `&&`, you can use `;`

**Comment by danimesq** [comment]
> For the bash style `&&`, you can use `;`

Here's another issue:
When using `;` inside quotes, like in a git commit message:
![Screenshot from 2021-11-20 21-26-00](https://user-images.githubusercontent.com/6765277/142807776-56daaacf-57d1-4c4a-bca1-d90413073150.png)

**Comment by jntrnr** [comment]
@danimesq - can you file that one as a separate issue?

**Comment by danimesq** [comment]
> in nushell, we use && for conditions like if $x < 10 && $y < 13

And how to switch `&&` for `;` while not getting rid of nushell, so it can work normally without scaring away bash users?

**Comment by jntrnr** [comment]
@danimesq unfortunately, if we tried to follow bash, we'd have a worse syntax (neither `&&` nor `<` would work in the example above)

**Comment by danimesq** [comment]
Can bash scripts loaded in nushell still work using `&&`?

**Comment by jntrnr** [comment]
yes, for bash scripts, we'll call out to bash. For your example, when you call out to the external command you may need to put `\` in front of the semicolon.

We should fix that issue, but the `\` should help you workaround it for now

**Comment by kubouch** [comment]
I'll close this since we don't plan adding a support for Bash-like `&&`.

**Comment by danimesq** [comment]
> Here's another issue:
> When using ; inside quotes, like in a git commit massage:

Done and merged here: https://github.com/nushell/nushell/pull/4157.

**Comment by avkonst** [comment]
If `;` is nu's "operator" for bash's `&&`, what is nu's "operator" for bash's `||` ?

**Comment by jondlm** [comment]
> If `;` is nu's "operator" for bash's `&&`, what is nu's "operator" for bash's `||` ?

https://www.nushell.sh/commands/docs/try.html
