### ISSUE TITLE
";" is slipping from quotes such as a git commit message

### ISSUE THREAD

**Issue by danimesq** [nushell/nushell#4140]
### Describe the bug

When using `;` inside quotes, like in a git commit massage:
![Screenshot from 2021-11-20 21-26-00](https://user-images.githubusercontent.com/6765277/142807776-56daaacf-57d1-4c4a-bca1-d90413073150.png)

### How to reproduce

Type, for example:
git commit -m "update 1; update 2"

The git commit message will be only "update 1".

### Expected behavior

Work normally with quotes like in Bash.

**Comment by danimesq** [comment]
Not only `;`, but also a single `&` (for example, curl json apis are failing because of missing parameters)

**Comment by BraulioVM** [comment]
The issue can be reproduced a bit more easily using `^echo`:

```
$ ^echo "aaa;bbb"
aaa
sh: 1: bbb: not found
```

I don't know much about nushell so I'm not sure if this is the expected behaviour. I suspect it isn't expected. I'm looking into it

**Comment by BraulioVM** [comment]
Ok, found the bug and fixed it. I will be submitting a PR shortly
