### ISSUE TITLE
[Question] Does it works on ARM (Raspberry Pi Zero W)?

### ISSUE THREAD

**Issue by danimesq** [nushell/nushell#4143]

**Comment by fdncred** [comment]
You should drop by [Discord](https://discord.gg/NtAbbGn) and ask. I thought I've seen people running it but I'm not sure.

**Comment by danimesq** [comment]
So, the same binary is theoretically multi-arch?

**Comment by fdncred** [comment]
No, I think they were saying they compiled it themselves.

**Comment by kubouch** [comment]
You should be able to cross-compile for ARM, although the Pi Zero W seems to use armv6 which is quite an old ISA, I haven't tried myself, and probably nobody from the dev team either.

Somebody tried compiling recently for Android and they got it working: #4151

**Comment by danimesq** [comment]
Is the default build x86 32 or 64?

**Comment by danimesq** [comment]
> So, the same binary is theoretically multi-arch?

I know its not possible.

I once thought it because your default build for Linux doesn't specify whether it is i386 or amd64.

**Comment by fdncred** [comment]
> Is the default build x86 32 or 64?

I'm not sure. It probably depends on the architecture you're compiling on.

**Comment by kubouch** [comment]
Most architectures are 64-bit nowadays.

**Comment by danimesq** [comment]
I suggest telling it in the next builds.
