### ISSUE TITLE
Convert duration to nanoseconds

### ISSUE THREAD

**Issue by raffomania** [nushell/nushell#4145]
### Related problem

I have a duration value that I would like to display as hours, e.g. "78 hours". Nushell displays it in multiple units, e.g. "3day 14hr 22min 44sec". 

### Describe the solution you'd like

Adding a way to convert a duration into any form of integer would probably be easiest to implement. Alternatively, a command like `duration to-table` or `duration format` would be easiest to use in my case.

### Describe alternatives you've considered

The following commands either fail or don't provide the format I need:

- `$duration | into int`
- `$duration | date format "%h"`
- `$"($duration)"`

At the moment I'm using `parse "{days}day {hours}hr {minutes}min {seconds}sec"` to convert a duration into a table.

**Comment by fdncred** [comment]
ya, sounds cool. i may also vote for `into time hours` or `into duration hours`. i like the `dat format "%h"` too.

**Comment by sholderbach** [comment]
Now possible with `into duration --convert`
