### ISSUE TITLE
Support more zsh/bash keyboard shortcuts

### ISSUE THREAD

**Issue by sunshowers** [nushell/nushell#4153]
### Related problem

I've been trying out nushell, which looks great so far! However it looks like it's missing a few shortcuts that are standard (though a bit less well-known) and that I use everyday, such as M-. (alt-period) to insert the last word of the last command (cycling back commands).

### Describe the solution you'd like

Here's my `zsh` `bindkey` output, which should be pretty close to stock IIRC.

https://gist.github.com/sunshowers/7d1300af9c88e24780240d520d28b610

`^` means ctrl, and `^[` means meta.

### Describe alternatives you've considered

I tried configuring `M-.` locally but I didn't see a way to have the behavior I wanted, unfortunately. I could have missed something though!

**Comment by fdncred** [comment]
there is a keybindings.yml file that you can customize but it's kind of hit-or-miss and doesn't have a lot of coverage yet. I'd still try it out. there's one in the repo as a sample.

**Comment by sunshowers** [comment]
Ah yeah I didn't see the option for `insert-last-word` in there. Regardless I think these should be shipped as defaults.

**Comment by fdncred** [comment]
the new keybindings functionality in 0.59.1 is very powerful. it would be good to know which items in your gist it doesn't support. of course, they would need to be translated to the reedline variant since nushell doesn't support this syntax for keybindings.

**Comment by fdncred** [comment]
the new keybindings functionality in 0.59.1 is very powerful. it would be good to know which items in your gist it doesn't support. of course, they would need to be translated to the reedline variant since nushell doesn't support this syntax for keybindings.

**Comment by jntrnr** [comment]
As we have stronger keybindings these days, I'm going to go ahead and close this. If you see missing capabilities, please re-open or file issues for the missing issues.
