### ISSUE TITLE
Add alternative table headers (at least for longer pages)

### ISSUE THREAD

**Issue by eugenesvk** [nushell/nushell#4158]
### Related problem

When a table is long I can't see table headers without going to the top, which is at an arbitrary position (unless it's the first command after `cls`)

### Describe the solution you'd like

Add a config to freely position table header:
- always at the bottom (in this case it's always visible)
- at the bottom only for long tables (> than X rows)
- at the top and at the bottom
- additionally, at every Xth row (for visually parsing long tables), though this might be too much as usually tables aren't that complex that they'd require an additional hint 

### Describe alternatives you've considered

you could `cls; command` and then shortcut-move to the top

**Comment by fdncred** [comment]
we've definitely talked about putting a header at the bottom of a table before. I think it's a good idea. I like your other ideas as well like if a table is > than x rows.

**Comment by fdncred** [comment]
ya, this is configurable in 0.59 and above now. i have mine set to `always` so i get headers and footers all the time to make it easier to know what columns are. you can also set it to a number of rows so like footers only show up when it's over 35 rows, or whatever you set it to.

![image](https://user-images.githubusercontent.com/343840/157493582-318efd69-5512-4df4-b25c-5a9e4fc909fa.png)
