### ISSUE TITLE
[Extension request] Detect when user is writting in bash syntax, and tell

### ISSUE THREAD

**Issue by danimesq** [nushell/nushell#4159]
For example, when user inputs:

`command 1 && command 2`

Instead of throwing an error, instruct user to use `;` instead of `&&`.

**Comment by kubouch** [comment]
This would require adding bash support to the parser which we do not plan to do. We could add some hints to error messages (when the `&&` operation fails, for example), however, that would clutter them.

I think it is important to recognize Nushell has a non-POSIX syntax. For this reason, we have a whole book page dedicated to converting common patterns from Bash (https://www.nushell.sh/book/coming_from_bash.html) and `&&` is one of them.

I'll close this issue, then.

**Comment by danimesq** [comment]
> we have a whole book page dedicated to converting common patterns from Bash (https://www.nushell.sh/book/coming_from_bash.html)

Still I couldn't figure out how from this single page how to use cat with a text in the command, not from a file.
