### ISSUE TITLE
Panics when stdout is closed

### ISSUE THREAD

**Issue by lopopolo** [nushell/nushell#4161]
### Describe the bug

`nu -h` panics when stdout is closed:

```console
$ RUST_BACKTRACE=1 nu -h | false
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1193:9
stack backtrace:
   0: _rust_begin_unwind
   1: std::panicking::begin_panic_fmt
   2: std::io::stdio::_print
   3: nu_command::commands::viewers::autoview::command::autoview
   4: <nu_command::commands::viewers::autoview::command::Command as nu_engine::whole_stream_command::WholeStreamCommand>::run
   5: nu_engine::whole_stream_command::Command::run
   6: nu_engine::evaluation_context::EvaluationContext::run_command
   7: nu_cli::app::consume
   8: nu_cli::app::App::main
   9: nu_cli::app::App::run
  10: nu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### How to reproduce

`nu -h | false`

### Expected behavior

nushell exits cleanly with a success error code and does not panic.

### Configuration

|key|value|
|-|-|
|version|0.40.0|
|build_os|macos-x86_64|
|rust_version|rustc 1.56.1|
|cargo_version|cargo 1.56.0|
|pkg_version|0.40.0|
|build_time|2021-11-16 08:53:03 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by lopopolo** [comment]
It looks like this is not just `-h`. `nu -c version | false` panics too.

```console
$ nu -c version | false
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1193:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I took a peek at the source and I couldn't tell if this was coming from either:

https://github.com/nushell/nushell/blob/fb197f562a778b687822a15b7e9374713324a5bc/crates/nu-protocol/src/macros.rs#L9

or 

https://github.com/nushell/nushell/blob/fb197f562a778b687822a15b7e9374713324a5bc/crates/nu-command/src/commands/viewers/autoview/command.rs#L230

**Comment by kubouch** [comment]
Interesting, it happens for me, too. This needs fixing. Happens on engine-q, too.

**Comment by onthebridgetonowhere** [comment]
Just FYI, on version 0.35.0 it does not panic (that's an old version I have lying around).

**Comment by BraulioVM** [comment]
I have a fix for this. It's essentially because of https://github.com/rust-lang/rust/issues/24821 

The solution is to re-implement `out!`, `outln!` and similar internal macros in terms of `write!` and `writeln!`, which let you handle the broken pipe error gracefully. I will submit my patch tomorrow
