### ISSUE TITLE
Fails in programs whose name are numbers

### ISSUE THREAD

**Issue by danimesq** [nushell/nushell#4162]
I have a program at /usr/bin/01.

Tried it in nu shell, but:

> error: Type Error
>   ┌─ shell:1:4
>   │
> 1 │ 01 ignore site
>   │    ^^^^^^ Expected operator, found ignore

**Comment by fdncred** [comment]
I believe the parser assumes numbers are numbers.

**Comment by danimesq** [comment]
> I believe the parser assumes numbers are numbers. I think this is expected behavior.

Its quite problematic, and prevents the naming of programs such as `01`.

**Comment by BraulioVM** [comment]
You can always run it like:

```
$ ^01 ignore site
```

where ^ indicates an external command. I believe the current behaviour is fine, given that programs whose names are just numbers are uncommon. Otherwise, things could get a bit ambiguous. What does the following do:

```
01 + 7
```

should that return 8? Or should that call your "01" program with a + argument and a 7 argument? 

Would you be satisfied with just running ^01, @danimesq ?

**Comment by fdncred** [comment]
good point @BraulioVM. i forgot about `^`, which tells nushell the command is external.

**Comment by danimesq** [comment]
>>01 + 7
>
>
>should that return 8? Or should that call your "01" program with a + argument and a 7 argument?

Yes, your point is valid.

> Would you be satisfied with just running ^01, @danimesq ?

Personally I think using special characters is worse than numbers in UX (with numbers and letters, no need to press `Shift` or `Control`).

I humbly don't want to do a change to nu's syntax, but I would like to propose if something like `^01 + 7` (other character, as its already being used) could be used when doing math on the prompt; leaving the pure `01 + 7` to .nu/.sh files.

**Comment by danimesq** [comment]
Indeed it would be an absurd to change a part of your syntax just because a random weirdo (me) made a program called `01`; so here were my humble five cents.

**Comment by danimesq** [comment]
The fix is to be done on my side: adding `01vcs` (sources into `01`) to be used in shells like nu.
