### ISSUE TITLE
error: nu is missing value for flag --loglevel

### ISSUE THREAD

**Issue by vincent-163** [nushell/nushell#4163]
### Describe the bug

I've just tried using nushell so I installed it and `chsh`'ed to nushell. However, when I started the shell using `genie -s` (from https://github.com/arkane-systems/genie) I got the following error:
```bash
error: nu is missing value for flag --loglevel
  ┌─ shell:1:1
  │
1 │ nu -l
  │ ^^
```

This seems to be caused by the `-l` flag. genie invokes nushell like: `/usr/bin/nushell -l`, and the `-l` flag means "login shell" in other shells like bash. tmux also has documentation for `-l` flag where the falg is simply ignored:
```
     -l            Behave as a login shell.  This flag currently has no effect and is for compatibility with other
                   shells when using tmux as a login shell.
```
 I'm not sure if it is standard behavior, but are there plans to support `-l` flags for compatibility, even if it's simply ignored?

### How to reproduce

Run `nu -l`

### Expected behavior

nu should start as a shell

### Configuration

|key|value|
|-|-|
|version|0.40.0|
|build_os|linux-x86_64|
|rust_version|rustc 1.56.1 (Arch Linux rust 1:1.56.1-3)|
|cargo_version|cargo 1.56.0|
|pkg_version|0.40.0|
|build_time|2021-11-16 21:31:00 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by fdncred** [comment]
I'm sure we could rename the loglevel flag but then there's be no `-l` so it would still probably fail. I'm not sure what "behaves as login shell" really means from a code perspective. I don't think anyone would be against a PR that implemented such a thing.
