### ISSUE TITLE
[How to] Use if value = value; then/else in a script?

### ISSUE THREAD

**Issue by danimesq** [nushell/nushell#4165]
I don't think it was an fault of research in my side, because I didn't found it in the examples and other references.

**Comment by jntrnr** [comment]
How about `help if`?

**Comment by fdncred** [comment]
the `help` system in nushell is pretty helpful. you can do `help <command>` or `<command> --help` or `help -f <search string>`. i'm closing this in favor of those. please reopen if you still have questions.

**Comment by danimesq** [comment]
So, `let x = 10` is the way nu declares a variable?

In bash its `x=10`, which is shorter.

I'll study more about how nu scripts differ from bash and how I can port mine without making them harder to understand. Hope nu is as simple as bash.

**Comment by danimesq** [comment]
This works:

> let x = 10
> if $x > 5 { $"greater than 5(char nl)" } { $"less than or equal to 5(char nl)" }

However, when trying to check if its equal:

> if $x = 5 { echo 'greater equals 5' } { echo 'less than or greater than to 5' }

Output: 

> 
> error: Type Error
>    ┌─ shell:13:7
>    │
> 13 │ if $x = 5 { echo 'greater equals 5' } { echo 'less than or greater than to 5' }
>    │       ^ Expected operator, found =
> 

What are the supported operators?

**Comment by jntrnr** [comment]
@danimesq - you might want to have a look at the book: https://www.nushell.sh/book/operators.html

**Comment by danimesq** [comment]
Also, how to use `if $x > 5 { $"greater than 5(char nl)" } { $"less than or equal to 5(char nl)" }` in indented lines instead of one?

**Comment by danimesq** [comment]
> And how to use if $x > 5 { $"greater than 5(char nl)" } { $"less than or equal to 5(char nl)" } in indented lines instead of one?

Moved to: https://github.com/nushell/nushell/issues/4168#issuecomment-981891125
