### ISSUE TITLE
Its echoing in the same line; is it expected?

### ISSUE THREAD

**Issue by danimesq** [nushell/nushell#4166]
My script (samplenew.sh):

> #!/bin/nu -e
> 
> echo "Does it works in nu?"
> 
> let x = 10; if $x > 5 { echo 'greater than 5' } { echo 'less than or equal to 5' }

Input: `nu samplenew.sh`

Output:

```
Does it works in nu?greater than 5
```

**Comment by fdncred** [comment]
yes. if you want a new line you need to do something like this: `$"Does it work in nu?(char nl)"`
