### ISSUE TITLE
How to use "if" in multiple indented lines instead of one?

### ISSUE THREAD

**Issue by danimesq** [nushell/nushell#4168]
For example:

> if $x > 5 { $"greater than 5(char nl)" } { $"less than or equal to 5(char nl)" }

Tried but couldn't reproduce it locally.

**Comment by jntrnr** [comment]
Did you assign `$x` to a value first? This works for me, so I'm going to go ahead and close

**Comment by danimesq** [comment]
> Did you assign $x to a value first? This works for me, so I'm going to go ahead and close

Yes, here's the full picture:

> let x = 10
> if $x > 5 { $"greater than 5(char nl)" } { $"less than or equal to 5(char nl)" }
> 
> if $x == 5 { $"greater equals 5(char nl)" } { $"less than or greater than to 5(char nl)";echo 'next' }

But my question is about how to indent in multiple lines (as used to in bash; so is more organized) instead of oneline.

**Comment by jntrnr** [comment]
use new lines?

You may need to spend a little time with the language first and then see what you get stuck on. There's also a discord for asking questions. Issues are more for issues or feature requests in the language.

**Comment by danimesq** [comment]
> or feature requests in the language.

And here is my feature request: to support `if`, `while` and other blocks having multiple lines instead of one.

Nu (uses one line):

> let x = 10
> if $x == 5 { $"cmd 1(char nl)";$"need of ; for new command"$;cat file.txt;$"new command in same line; how to organize?" }

Bash (supports multiple lines):

> x=10 # smaller
> if [ "$x" = "5" ];then
>    echo "cmd 1"
>    echo "no need of ; for new command"
>    cat file.txt
>    echo "new command in new line"
> fi

**Comment by jntrnr** [comment]
Did you even try writing a new line in the block?

**Comment by danimesq** [comment]
`Did you even try writing a new line in the block?`

Yes.

Before (working):

> let x = 10
> if $x > 5 { $"greater than 5(char nl)" } { $"less than or equal to 5(char nl)" }

After (not working):

> let x = 10
> if $x == 5 {
> $"cmd 1(char nl)"
> $"need of ; for new command"
> cat file.txt
> $"new command in same line; how to organize?" 
> }

**Comment by jntrnr** [comment]
As I said, if you have questions on how Nushell works, please use the discord. Your example above is working but you are expecting something different.

**Comment by danimesq** [comment]
> Your example above is working but you are expecting something different.

No, it isn't.

Used:

> let x = 10
> if $x == 5 {
> $"cmd 1(char nl)"
> $"need of ; for new command"
> cat file.txt
> $"new command in same line; how to organize?"
> }

Output:

> error: == requires right hand side parameter
>   ┌─ shell:4:7
>   │
> 4 │ if $x == 5 {
>   │       ^^ requires right hand side parameter

**Comment by fdncred** [comment]
The problem with your script, and what nushell is saying (not very well), is that the `if` command has to be constructed like it tells you in the help. Please read the help. `if <condition> <then_case> <else_case>` which means for you:
```
if $x == 5 {
  $"cmd 1(char nl)"
  $"need of ; for new command"
  cat file.txt
  $"new command in same line; how to organize?"
} {
  # something here to satisfy the syntax
}
```
