### ISSUE TITLE
Can't use "." inside a cat EOF

### ISSUE THREAD

**Issue by danimesq** [nushell/nushell#4169]
Source:

> 
> #!/bin/nu -e
> 
> cat << "EOF"
> . SHIBA IN NU
> ─────────▄──────────────▄
> ────────▌▒█───────────▄▀▒▌
> ────────▌▒▒▀▄───────▄▀▒▒▒▐
> ───────▐▄▀▒▒▀▀▀▀▄▄▄▀▒▒▒▒▒▐
> ─────▄▄▀▒▒▒▒▒▒▒▒▒▒▒█▒▒▄█▒▐
> ───▄▀▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▀██▀▒▌
> ──▐▒▒▒▄▄▄▒▒▒▒▒▒▒▒▒▒▒▒▒▀▄▒▒▌
> ──▌▒▒▐▄█▀▒▒▒▒▄▀█▄▒▒▒▒▒▒▒█▒▐
> ─▐▒▒▒▒▒▒▒▒▒▒▒▌██▀▒▒▒▒▒▒▒▒▀▄▌
> ─▌▒▀▄██▄▒▒▒▒▒▒▒▒▒▒▒░░░░▒▒▒▒▌
> ─▌▀▐▄█▄█▌▄▒▀▒▒▒▒▒▒░░░░░░▒▒▒▐
> ▐▒▀▐▀▐▀▒▒▄▄▒▄▒▒▒▒▒░░░░░░▒▒▒▒▌
> ▐▒▒▒▀▀▄▄▒▒▒▄▒▒▒▒▒▒░░░░░░▒▒▒▐
> ─▌▒▒▒▒▒▒▀▀▀▒▒▒▒▒▒▒▒░░░░▒▒▒▒▌
> ─▐▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▐
> ──▀▄▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▄▒▒▒▒▌
> ────▀▄▒▒▒▒▒▒▒▒▒▒▄▄▄▀▒▒▒▒▄▀
> ───▐▀▒▀▄▄▄▄▄▄▀▀▀▒▒▒▒▒▄▄▀
> ──▐▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▀▀
> . SHIBA IN NU
> EOF

Output:

> error: Command not found
>    ┌─ shell:19:1
>    │
> 19 │ . SHIBA IN NU
>    │ ^ command . not found

**Comment by jntrnr** [comment]
Please stop filing issues for questions about the language. There is a book that explains how the structured pipes work as well as the discord where you can ask questions.

**Comment by danimesq** [comment]
> Please stop

Hey??

> There is a book that explains how the structured pipes work as well as the discord where you can ask questions.

Have pointed to [coming_from_bash](https://www.nushell.sh/book/coming_from_bash.html) but it only contains replacements for `> <path>` and `>> <path>`, but not `<<`.

About `cat <path>` replacement, it contains instructions for files, not texts inside the command.

And sorry, next time I'll ask on Discord instead.
