### ISSUE TITLE
Since it is written in Rust, does it have the same performance as in bash written in C

### ISSUE THREAD

**Issue by vairamsvsjdo** [nushell/nushell#417]
Since it is written in Rust, does it have the same performance as in bash written in C
What is the performance benchmark?
Is there a guidance when abstraction code using functional works better than the bash?

**Comment by jonathandturner** [comment]
In theory, it will, though we haven't focused on optimization just yet.

We're hoping to build up guidance as we build up the ability to write scripts and more complex queries.

**Comment by wycats** [comment]
I don't really consider `bash` to be particularly fast, but once we get through support for the critical features, we should take a look at anything that seems especially slow and fix it.

Fun is our top priority 😄 
But painfully slow is no fun 😂

**Comment by Mehdi-YC** [comment]
for my experience, nushell is faster , i tried it in fedora37 in a vm , and starship is faster in nu than bash
is it just my case or does anyone notice this too ?
