### ISSUE TITLE
Optional parameter for custom command raise `unknown variable` error on Windows

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4170]
### Describe the bug

Optional parameter for custom command raise `unknown variable` error on Windows

### How to reproduce

1. Define a custom command:
```
def 'get-env' [
  key: string         # The key to get it's env value
  default?: string  # The default value for an empty env
] {
  let val = ($nu.env | pivot key value | match key $key | get value)
  if ($val | empty?) { $default } { $val }
}
```
2. Run `get-env abc` on windows cause the following error:
```
> get-env abc
error: Variable not in scope
    ┌─ shell:280:24
    │
280 │   if ($val | empty?) { $default } { $val }
    │                        ^^^^^^^^ unknown variable: $default
```

### Expected behavior

Out put `$nothing` or a empty string

### Configuration

|key|value|
|-|-|
|version|0.40.0|
|short_commit|2590fcbe|
|commit_hash|2590fcbe5c7721fe9835657de284e14c0602ecad|
|commit_date|2021-11-16 08:53:03 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.56.1 (59eed8a2a 2021-11-01)|
|rust_channel|stable-x86_64-pc-windows-msvc (default)|
|cargo_version|cargo 1.56.0 (4ed5d137b 2021-10-04)|
|pkg_version|0.40.0|
|build_time|2021-11-16 09:50:28 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by fdncred** [comment]
I think it's saying that you specify `default?` as the name but when you reference the variable you call it `default` with the `?` missing.

**Comment by hustcer** [comment]
@fdncred "You can make a parameter optional by adding ? to its name. Optional parameters do not need to be passed."  See [Ref](https://github.com/nushell/nushell/blob/bff81f24aa52d3a0b4f186ca031c447fda92a1f9/docs/commands/def.md)

**Comment by fdncred** [comment]
i don't think that was ever implemented was it? Do you have a PR with that? i know we talked about it for the longest time.

**Comment by hustcer** [comment]
> i don't think that was ever implemented was it? Do you have a PR with that? i know we talked about it for the longest time.

I did not send any PR. It works on macOS but has an error on Windows, could be a bug.

**Comment by hustcer** [comment]
Well, I found the same problem on macOS(I ignore some thing previously on mac),  so the issue will be: How can we check `$default` is an unknown variable and handle it?

**Comment by fdncred** [comment]
if you look on our nu_scripts repo I think you'll find some alternative ways of checking using `$nothing` and `empty?`

**Comment by hustcer** [comment]
> if you look on our nu_scripts repo I think you'll find some alternative ways of checking using `$nothing` and `empty?`

I have already tried, just did not work can you show me how? Thanks

**Comment by fdncred** [comment]
@hustcer if you look at this file, you can see the comments where i talk about optional parameters https://github.com/nushell/nu_scripts/blob/main/stdlib_candidate/print.nu

**Comment by hustcer** [comment]
> @hustcer if you look at this file, you can see the comments where i talk about optional parameters https://github.com/nushell/nu_scripts/blob/main/stdlib_candidate/print.nu

@fdncred I See, thanks.  So the key point is optional parameter should be written as an option like`--default(-d):any`, not yet `default?: string`. I will leave this issue open as `default?: string` is more likely to be taken as optional parameter, IMO.

**Comment by rosshadden** [comment]
I was confused by this too. Support for optional params was added in #2966. However after experimentation and research I believe that it is implemented only in the parsing and is not in a usable state. I have yet to figure out how to do something like this:

```nu
def lol [name?: string] {
	if ($name | empty?) {
		echo yes
	} {
		echo no
	}
}
```

It parses correctly and no errors are thrown until runtime tries to compute the variable:

```
error: Variable not in scope
unknown variable: $name
```

**Comment by jntrnr** [comment]
This should be working with the latest main:

```
> def lol [name?: string] {
   if $name == $nothing {
     echo yes
   } else {
     echo no
   }
}
> lol test
no
> lol
yes
```
