### ISSUE TITLE
Allow passing through environment variables from the parent process

### ISSUE THREAD

**Issue by jansol** [nushell/nushell#4171]
### Related problem

On my setup the desktop environment automatically launches an instance of ssh-agent for my user when I log in and sets some related environment variables, namely `SSH_AUTH_SOCK` and `SSH_ASKPASS`. These are referring to runtime-generated paths and thus can't be relied on enough to hardcode them in a config that may be shared across machines. Since I am using NixOS `SSH_ASKPASS` will also change across reboots without warning if the package gets updated and the location of the binary changes (it depends on the package's hash).

### Describe the solution you'd like

Add an option to list environment variables in the config file whose values should be propagated from the parent process as is. Simply propagating everything would also work, but I can imagine there are very valid reasons not to do that.

### Additional context and details

Would probably also cover a number of use cases related to #4103

**Comment by fdncred** [comment]
I believe the way this works is if you want environment variables to populate from the host os/parent process when you launch nushell, you make sure and **do not** define those particular env vars in nushell's config.toml file. This assumes you're not using nushell as your login shell.

By default, nushell inherits all environment variables from the host shell.

**Comment by jansol** [comment]
I have nu set as the shell in alacritty but I don't get any of the ssh-agent particular variables (I do get a few others though, now that you mention it, particularly). I don't have those in my config either so not sure what is going on with them. Bash however does get them even if I launch it from within nu. My .profile does not set them, so not sure where it's pulling them from...

**Comment by fdncred** [comment]
i wonder if it's weird timing issue like nushell is starting, gathers all env vars, then ssh-agent starts and writes env vars after nushell has gathered them all. @kubouch we were talking the other day about env vars getting out of sync. this appears to be one way although i'm not sure i could reproduce it mainly because i'm on windows and don't use ssh.

**Comment by jansol** [comment]
I don't think that is the case since ssh-agent is running already, it is launched when I log in as part of the systemd user session.

**Comment by jansol** [comment]
Aah, I found something: there is a `/etc/profile` that sources an autogenerated file that in turn does export quite a few environment variables, including `SSH_AUTH_SOCK`. However a great number of those *are* in fact present in nu even though they are not listed in the config. `SSH_AUTH_SOCK` for some reason is not.

**Comment by kubouch** [comment]
I remember there were some bugs in Nushell about environment variables. In engine-q, when it starts, it grabs all env vars from `std::env::vars()` and gives them to the engine. So any env variable that is set before launching engine-q should be visible. Maybe you could try if it works on engine-q? Alternatively, you can test by hacking a small Rust program that grabs all `std::env::vars()`.

**Comment by jansol** [comment]
Okay dumping `std::env:.vars()` to a file gave me roughly the same results running from Dolphin vs running from nu +/- a couple of variables from my nu config, so it would seem the environment of the parent is indeed captured correctly and bash has the ssh-agent variables thanks to `/etc/profile`.
