### ISSUE TITLE
`inc 1.1.1` returns nothing 

### ISSUE THREAD

**Issue by cnrmck** [nushell/nushell#4177]
### Describe the bug

Love nushell! Noticed this bug

Calling `inc 1.1.1 -p` returns nothing

### How to reproduce

Call `inc 1.1.1` 

### Expected behavior

Expected it to return 1.1.2

### Configuration

|key|value|
|-|-|
|version|0.40.0|
|branch|main|
|short_commit|79c7b20c|
|commit_hash|79c7b20cfdf3eed2dd6beeb684911d6b87d1eae9|
|commit_date|2021-12-02 07:05:04 +00:00|
|build_os|macos-x86_64|
|rust_version|rustc 1.56.1 (59eed8a2a 2021-11-01)|
|rust_channel|stable-x86_64-apple-darwin|
|cargo_version|cargo 1.56.0 (4ed5d137b 2021-10-04)|
|pkg_version|0.40.0|
|build_time|2021-12-02 10:51:47 -07:00|
|build_rust_channel|release|
|features|ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by jntrnr** [comment]
@cnrmck - welcome, and thanks!

For `inc`, it currently assumes that the string is coming from the input rather as an arg. Rewriting your example with that in mind, you'll get something like:

```
> "1.1.1" | inc -p
1.1.2
```

**Comment by cnrmck** [comment]
Ah ha! Thank you for the quick response. Just picked this up today. 

Getting used to the idea that input and arguments are different... very cool
