### ISSUE TITLE
`detect columns` fails to parse cell contents that include spaces

### ISSUE THREAD

**Issue by waldyrious** [nushell/nushell#4183]
### Describe the bug

Using the example output from the [docker ps documentation](https://docs.docker.com/engine/reference/commandline/ps/):
```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
673394ef1d4c        busybox             "top"               47 seconds ago      Up 45 seconds                           nostalgic_shockley
d85756f57265        busybox             "top"               52 seconds ago      Up 51 seconds                           high_albattani
```

Here's how `detect columns` parses it: 
```
> cat ~/docker-ps.txt | detect columns
───┬──────────────┬──────────────┬─────────┬─────────┬─────────┬─────────┬───────┬────────────────────
 # │  CONTAINER   │      ID      │  IMAGE  │ COMMAND │ CREATED │ STATUS  │ PORTS │       NAMES        
───┼──────────────┼──────────────┼─────────┼─────────┼─────────┼─────────┼───────┼────────────────────
 0 │ 673394ef1d4c │ 673394ef1d4c │ busybox │ "top"   │ seconds │ seconds │       │ nostalgic_shockley 
 1 │ d85756f57265 │ d85756f57265 │ busybox │ "top"   │ seconds │ seconds │       │ high_albattani     
───┴──────────────┴──────────────┴─────────┴─────────┴─────────┴─────────┴───────┴────────────────────
```

There are two errors in this output, both related to cell contents that include spaces:
- The `CONTAINER ID` column is split into two columns, with identical content;
- Cell contents that include spaces (in the CREATED and STATUS columns) is trimmed down to a single word.

### How to reproduce

1. Create a `~/docker-ps.txt` file with the contents indicated above
2. Run `~/docker-ps.txt | detect columns`

### Expected behavior

The correct output should be:
```
> cat ~/docker-ps.txt | detect columns
───┬──────────────┬─────────┬─────────┬────────────────┬───────────────┬───────┬────────────────────
 # │ CONTAINER ID │  IMAGE  │ COMMAND │    CREATED     │    STATUS     │ PORTS │       NAMES        
───┼──────────────┼─────────┼─────────┼────────────────┼───────────────┼───────┼────────────────────
 0 │ 673394ef1d4c │ busybox │ "top"   │ 47 seconds ago │ Up 45 seconds │       │ nostalgic_shockley 
 1 │ d85756f57265 │ busybox │ "top"   │ 52 seconds ago │ Up 51 seconds │       │ high_albattani     
───┴──────────────┴─────────┴─────────┴────────────────┴───────────────┴───────┴────────────────────
```

### Configuration

| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.40.0                                                                                                                                                                  |
| build_os           | linux-x86_64                                                                                                                                                            |
| rust_version       | rustc 1.56.1                                                                                                                                                            |
| cargo_version      | cargo 1.56.0                                                                                                                                                            |
| pkg_version        | 0.40.0                                                                                                                                                                  |
| build_time         | 1980-01-01 00:00:00 +00:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                      |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

### Additional context

If it helps, `from ssv` is able to correctly identify cell contents that include spaces:
```
> cat ~/docker-ps.txt | from ssv
───┬──────────────┬─────────┬─────────┬────────────────┬───────────────┬────────────────────
 # │ CONTAINER ID │  IMAGE  │ COMMAND │    CREATED     │    STATUS     │       PORTS        
───┼──────────────┼─────────┼─────────┼────────────────┼───────────────┼────────────────────
 0 │ 673394ef1d4c │ busybox │ "top"   │ 47 seconds ago │ Up 45 seconds │ nostalgic_shockley 
 1 │ d85756f57265 │ busybox │ "top"   │ 52 seconds ago │ Up 51 seconds │ high_albattani     
───┴──────────────┴─────────┴─────────┴────────────────┴───────────────┴────────────────────
```

(There's a separate bug in this output, in that the empty PORTS column isn't properly detected, but I've reported that separately as #4182.)

**Comment by fdncred** [comment]
`detect columns` is a relatively new command, but `from ssv` seems to work fine for this use case `| from ssv --aligned-columns`

**Comment by fdncred** [comment]
`detect columns` is a relatively new command, but `from ssv` seems to work fine for this use case `| from ssv --aligned-columns`

**Comment by jntrnr** [comment]
`detect columns` still has this issue on latest main.

@fdncred I wonder if `detect columns` should work more closely to what `| from ssv --aligned-columns` does?

**Comment by fdncred** [comment]
After the latest changes to the `detect columns` algorithm.
```
❯ 'CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES1:08 AM
❯❯❯ 673394ef1d4c        busybox             "top"               47 seconds ago      Up 45 seconds                           nostalgic_shockley
❯❯❯ d85756f57265        busybox             "top"               52 seconds ago      Up 51 seconds                           high_albattani' | detect columns
╭─#─┬─CONTAINER ID─┬──IMAGE──┬COMMAND┬────CREATED─────┬────STATUS─────┬PORTS┬───────NAMES────────╮
│ 0 │ 673394ef1d4c │ busybox │ "top" │ 47 seconds ago │ Up 45 seconds │     │ nostalgic_shockley │
│ 1 │ d85756f57265 │ busybox │ "top" │ 52 seconds ago │ Up 51 seconds │     │ high_albattani     │
╰───┴──────────────┴─────────┴───────┴────────────────┴───────────────┴─────┴────────────────────╯
```
