### ISSUE TITLE
command to measure execution time like `time`(Bash)

### ISSUE THREAD

**Issue by kyoheiu** [nushell/nushell#4184]
### Describe the solution you'd like

It would be much better if nushell had a time command by default, which would measure the execution time and output it.
Or maybe nu already has such a command or combination of commands... If so, please let me know ;)

**Comment by jntrnr** [comment]
@kyoheiu there's a command called `benchmark` that might do what you need

**Comment by kyoheiu** [comment]
@jntrnr Thanks! This is close to what I'm thinking. But Bash's `time` returns three types of time: real, user, and sys. `benchmark` seems to return only real time. Is there any way to get a more accurate (or detailed) execution time? Or should I use `hyperfine` instead?

**Comment by fdncred** [comment]
nushell used to report that information, as you can see here: https://github.com/nushell/nushell/blob/ee9eddd85169035ed3410774f884ee2e9d148b69/crates/nu-command/src/commands/platform/benchmark.rs#L118-L141
however, `heim` took a while to compile so we disabled it.
I think for now, if you want that level of information you can try:
* `^time some_command`
* `hyperfine some_command`
* do some testing with heim and see if it's still slow to compile and maybe submit a pr if it's not.

**Comment by kyoheiu** [comment]
@fdncred  Thank you. I'll give it a try.
