### ISSUE TITLE
Why the command `into column_path` is named in snake-case?

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4185]
### Describe the bug

Why the command `into column_path` is named in snake-case? It's a bit weird as most of the nushell subcommands are named in kebab-case.

### How to reproduce

See: `help -f column`

### Expected behavior

Change `into column_path` into ``into column-path``

### Configuration

|key|value|
|-|-|
|version|0.40.0|
|build_os|macos-x86_64|
|rust_version|rustc 1.56.1|
|cargo_version|cargo 1.56.0|
|pkg_version|0.40.0|
|build_time|2021-11-16 08:53:03 +00:00|
|build_rust_channel|release|
|features|clipboard-cli, ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip|
|installed_plugins|binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath|

**Comment by fdncred** [comment]
makes sense. we probably just missed that when it was pr'd. feel free to submit a pr to be more consistent.

**Comment by hustcer** [comment]
> makes sense. we probably just missed that when it was pr'd. feel free to submit a pr to be more consistent.

Okay, I will try this later.
