### ISSUE TITLE
Add a default value flag (-d, --default) to `query json`

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4186]
### Related problem

When query a json string the result could be a list, table, string, etc. or `$nothing`, if the key does not exist we will get `$nothing` as the result, which may break the pipeline due to various kinds of converting related errors. Such as:

$ `'{"b":["c","d"], "x": ["y", "z"]}'|query json m| each { echo $it } | str collect '.'`
```bash
error: could not convert to string
   ┌─ shell:13:70
   │
13 │ '{"b":["c","d"], "x": ["y", "z"]}'|query json m| each { echo $it } | str collect '.'
   │                                    ----------                        ^^^^^^^^^^^ tried to convert 'nothing' in input to a string
   │                                    │
   │                                    'nothing' value originated here
```

### Describe the solution you'd like

If we have a default value flag (`-d, --default`) to the query `query json` command things will be much easier:
`'{"b":["c","d"], "x": ["y", "z"]}'|query json -d [] m| each { echo $it } | str collect '.'` 
the result will be the same as:
`[] | each { echo $it } | str collect '.'`

**Comment by fdncred** [comment]
seems reasonable.

**Comment by hustcer** [comment]
Currently nu v0.59 run `'{"b":["c","d"], "x": ["y", "z"]}'|query json m| each { echo $it } | str collect '.'` with out any errors, and the output is an empty string which is reasonable.
Any need  to add a default value flag (`-d, --default`) to `query json`? Not so urgent anymore, and maybe we should keep `query json` **PURE**
So I will close this issue.
