### ISSUE TITLE
Nullability, null coalescing, null-safe calls, null-safe piping

### ISSUE THREAD

**Issue by jmoore34** [nushell/nushell#4188]
### Related problem

Here is an example use case in which nullability could be useful:

```nu
def e [
  directory: string?
] {
  explorer (directory ?? $in ?? ".")
}
```

With `??` as a null coalescing operator, you could use this command in three different ways:
1. `e ~   # Provide a directory to open in explorer`
2. `(which nu).path | path dirname | into string | e  # Use a value from the pipeline`
3. `e   # Default to opening the current directory if no input is given`

### Describe the solution you'd like

Here are some ideas for how nullability could be used:

- Nullable command arguments (see example above), presumably only allowed as the last arguments (possible alternative: using a variadic `...rest` argument)
- Null coalescing operator `??`
  - This could even be split into a nullish-coalescing operator (e.g. `??`) and a strict null-coalescing operator (e.g. `???`), for instance to distinguish between `$nothing` and null-like things (such as empty string)
    - Alternative: add a command that returns `$nothing` if the input is null-like (e.g. empty string), and return the input otherwise. This could then emulate a nullish-coalescing operator in the pipeline, e.g. `some_command | nullish? ?? 'default'`
- Safe calls/piping via command variants that return `$nothing` rather than error out
  - `which? nonexistent_binary | get? path`
  - `(which? nonexistent_binary)?.path`
  - `(open? package.json | get? version | inc? -p) ?? 1.0.0`
  - `cd? nonexistent_directory ?? echo "directory does not exist"`
- Perhaps something like this could be used to help emulate bash's `&&` and `||` functionality. For instance, there could be a null-check pipe operator e.g. `|?` which only pipes the input if it is not `$nothing`, e.g. `(which? nonexistent_binary)?.path |? echo $"There is a binary located at ($in)"`
  - Could possibly be extended to external commands, e.g. `git? status ?? echo "no git repository here"`. Or, perhaps there could be a helper command(s) that returns `$nothing` if the pipeline returns a nonzero exit code, outputs to stderr, aborts, outputs matching a regex, etc., e.g. something like `some_command | error? --nonzero-exit-code ?? echo "command failed"`

### Additional context and details

This is less a request and more brainstorming

**Comment by jntrnr** [comment]
I think this is largely fixed now. I think by you 😁 

If there are additional features Nushell doesn't have, can you open separate issue for them, just to make them easier to track?

**Comment by r-k-b** [comment]
This was one of the few relevant search results, when I was searching for how to do null coalescing in nushell.  
For future readers, here's a relevant example:

```nushell
let x = $foo | default $env.BAR? | default 123
```

The docs page for `default`: https://www.nushell.sh/commands/docs/default.html
