### ISSUE TITLE
config set_into is not setting the expected table entry

### ISSUE THREAD

**Issue by valeth** [nushell/nushell#4197]
### Describe the bug

When trying to set an environment variable with `set_into` instead of `set` it appears to stringify the entire argument and use that as key.

`config set` works as expected.

### How to reproduce
> note: `xdg_home` just returns an absolute file path
1. Pipe a value into config: `xdg_home "toolchain" "ghcup" | str trim | config set_into env.GHCUP_INSTALL_BASE_PREFIX`
2. `config get env.GHCUP_INSTALL_BASE_PREFIX` returns nothing
3. `config get "env.GHCUP_INSTALL_BASE_PREFIX"` returns the value

### Expected behavior

The value is set in the `env` table

### Configuration

| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.41.0                                                                                                                                                                  |
| build_os           | linux-x86_64                                                                                                                                                            |
| rust_version       | rustc 1.57.0 (Arch Linux rust 1:1.57.0-1)                                                                                                                               |
| cargo_version      | cargo 1.57.0                                                                                                                                                            |
| pkg_version        | 0.41.0                                                                                                                                                                  |
| build_time         | 2021-12-07 19:39:17 +00:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

**Comment by kubouch** [comment]
We're planning to deprecate config commands once we merge the new engine (engine-q) and use a `config.nu` script instead of config.toml. I'll close this issue but if you find any problems with the new config system, please file another issue.

As a side node, to set environment variables, you probably want to use `let-env` or `load-env` instead of modifying the config.
