### ISSUE TITLE
Support for additional integer operations

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4202]
### Related problem

Allowing more integer operations would be useful.

### Describe the solution you'd like

* `>> N` shift right by N bits
* `<< N` shift left by N bits

Since we use i64 for the underlying integer representation, we should probably use arithmetic shift.

Also, we could add integer division: `// N` (e.g., `5 // 2` would be 2).

### Describe alternatives you've considered

Not having them is not a major problem.

**Comment by jntrnr** [comment]
We may end up wanting `>>` for redirection, not sure.

Bit ops could probably also be named, if we want them. `1 shl 5` or something?  Not sure how often they'd come up in practice.

**Comment by flying-sheep** [comment]
> We may end up wanting `>>` for redirection, not sure.

`save --append` is cleaner and already exists, so what would it be for?

**Comment by hustcer** [comment]
These integer operations are supported now
