### ISSUE TITLE
Weird output when using `screen`

### ISSUE THREAD

**Issue by lain-ke** [nushell/nushell#4204]
### Describe the bug

When using `screen` and attempting to print anything with a table, it displays ����������

### How to reproduce

1. Run `screen`
2. Run any command with a table display like `ls` or `sys`

### Expected behavior

Nu is expected to print a table with data, and while the data is displayed, the table sides (columns and lines) are displayed with ���� symbols.

### Screenshots

![image](https://user-images.githubusercontent.com/59977484/145882234-471b7315-4475-4ebf-9cec-90ea435bcb41.png)

### Configuration

| key                | value                                                  |
| ------------------ | ------------------------------------------------------ |
| version            | 0.41.0                                                 |
| build_os           | openbsd-aarch64                                        |
| rust_version       | rustc 1.57.0                                           |
| cargo_version      | cargo 1.57.0                                           |
| pkg_version        | 0.41.0                                                 |
| build_time         | 2021-12-13 20:40:09 +01:00                             |
| build_rust_channel | release                                                |
| features           | ctrlc, dataframe, default, rustyline, term, which, zip |
| installed_plugins  | fetch, match, post, ps, sys                            |

### Additional context

Running on a Raspberry Pi 4B with OpenBSD 7.0

**Comment by jntrnr** [comment]
Interesting - those would be unicode characters normally. Is it possible that screen doesn't support unicode output?

**Comment by lain-ke** [comment]
They had an open issue with this, [https://unix.stackexchange.com/questions/81923/gnu-screen-doesnt-echo-unicode-characters-correct](https://unix.stackexchange.com/questions/81923/gnu-screen-doesnt-echo-unicode-characters-correct) but ti's from years ago.

**Comment by lain-ke** [comment]
Okay, thanks for your quick reply.
