### ISSUE TITLE
Single quotes should prevent expansion of '~'

### ISSUE THREAD

**Issue by goj** [nushell/nushell#4205]
### Describe the bug

Coming from other shells it's a bit surprising that `'~'` is expanded

### How to reproduce

1. Make a directory named '~' ( `^mkdir '~'`), add some content.
2.  See what's there, e.g. `ls '~'`
     * For the brave: delete it in nushell with `rm -r`

### Expected
I would expect that specific directory to be listed

### Actual
Whole home directory is listed.

This is catastrophic if `rm` is used instead of `ls`.

**Comment by jntrnr** [comment]
In our upcoming engine, I believe that it'll be expanded in both places so your `^mkdir` would fail to create a new directory.

Can you say more about what shells you're coming from that don't use ~ as home? I'm honestly a bit surprised, I thought it was nearly universal (with the exception of maybe something on Windows)

**Comment by kubouch** [comment]
In Nushell `'` and `"` quotes are treated equal, similar to Python.

I guess we could add, e.g., `--noexpand` flag to the filesystem commands to prevent them from expanding the paths. My personal use case for this is when debugging Nushell, sometimes I end up with weird files and directories that are called `~/` for example. You don't want to call `rm` on that :grinning:.

**Comment by BatmanAoD** [comment]
It looks like #7711 only changes how tilde-expansion is done for external commands; why not make it consistent and always suppress tilde-expansion inside of quotes?
