### ISSUE TITLE
rm -r fails with rm_always_trash enabled

### ISSUE THREAD

**Issue by Sympel** [nushell/nushell#4208]
### Describe the bug

If I try to remove a non-empty directory using `rm -r <path>`, `rm` fails with the error:
```
error: Could not delete because: Unknown { description: "Path: '\"/home/sympel/.local/share/Trash/files/<path>.<number>\"'. Message: No such file or directory (os error 2)" }
Try '--trash' flag
   ┌─ shell:17:7
   │
17 │ rm -r ~/tmp
   │       ^^^^^ Unknown { description: "Path: '\"/home/sympel/.local/share/Trash/files/<path>.<number>\"'. Message: No such file or directory (os error 2)" }
```
This does not seem to happen if the directory is empty or if the directory was just created.
`^rm -r <path>` removes everything without problems.

### How to reproduce

1. Set `rm_always_trash = true`
2. ???

### Expected behavior

The specified directory should be removed, if it exists.

### Screenshots

![20211214_16h51m45s_grim](https://user-images.githubusercontent.com/56477664/146031641-0a0bac5b-2589-490f-b76f-8e22cd5bd337.png)

### Configuration

| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.41.0                                                                                                                                                                  |
| build_os           | linux-x86_64                                                                                                                                                            |
| rust_version       | rustc 1.57.0 (Arch Linux rust 1:1.57.0-1)                                                                                                                               |
| cargo_version      | cargo 1.57.0                                                                                                                                                            |
| pkg_version        | 0.41.0                                                                                                                                                                  |
| build_time         | 2021-12-07 19:39:17 +00:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

### Additional context

I don't know what is causing this, I tried rebooting and did some testing on different files and directories to narrow down the problem without any results.
I encountered the problem for the first time today but I don't know when the last time I removed non-empty directories before that was, so I can't even tell what introduced this issue or how long it has been there.
This issue stops appearing if I disable rm_always_trash.

**Comment by fdncred** [comment]
Just tested this in 0.59.1 and it works now. Closing.
