### ISSUE TITLE
Can't run shell script with absolute path, which contains whitespace.

### ISSUE THREAD

**Issue by WindSoilder** [nushell/nushell#4214]
### Describe the bug

I can't execute a script which absolute path contains whtespace? like:
```
/Applications/PyCharm CE.app/Contents/bin/format.sh test1.py
```
But fish shell can run the script with the following manner:
```
/Applications/PyCharm\ CE.app/Contents/bin/format.sh test1.py
```
The `engine-q` have the same issue too.

### How to reproduce

1. put a shell scirpt in a path which contains whitespace, my example is: `/Applications/PyCharm\ CE.app/Contents/bin/format.sh`, enable `+x` mode for it.
2. execute the shell script with absolute path.
```
/Applications/PyCharm\ CE.app/Contents/bin/format.sh
```

### Expected behavior

The shell should be executed successfully

### Screenshots

![图片](https://user-images.githubusercontent.com/22256154/146733727-c95cd508-88b4-4e4f-a168-da10c194b012.png)

### Configuration

| key                | value                                                  |
| ------------------ | ------------------------------------------------------ |
| version            | 0.40.0                                                 |
| build_os           | macos-x86_64                                           |
| rust_version       | rustc 1.59.0-nightly (acbe4443c 2021-12-02)            |
| rust_channel       | nightly-x86_64-apple-darwin (default)                  |
| cargo_version      | cargo 1.58.0-nightly (294967c53 2021-11-29)            |
| pkg_version        | 0.40.0                                                 |
| build_time         | 2021-12-06 14:17:11 +08:00                             |
| build_rust_channel | release                                                |
| features           | ctrlc, dataframe, default, rustyline, term, which, zip |
| installed_plugins  | fetch, match, post, ps, sys                            |

**Comment by fdncred** [comment]
Can you please try this in Nushell?
`^$"/Applications/PyCharm CE.app/Contents/bin/format.sh" test1.py`
I thought we added something so that a string interpolated path would work.

**Comment by WindSoilder** [comment]
It gives me an error
![图片](https://user-images.githubusercontent.com/22256154/146857484-c6a73be3-d4e1-4366-ad25-75f9fa5e193b.png)

**Comment by jntrnr** [comment]
for people interested in fixing this, it seems that python does things a bit differently:

```
> ^"./test dir/echo.py"
hello from python

> ^"./test dir/echo.sh"
sh: 1: ./test: not found
```

**Comment by jntrnr** [comment]
This is fixed now with the new engine - we now detect when we need to run through bash but do not do it by default:

```
> ^'./test dir/echo.py'
hello form python
> ^'./test dir/echo.sh'
hello from sh
```
