### ISSUE TITLE
`str index-of` returns incorrect indexes for strings that have CJK characters

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4215]
### Describe the bug

`str index-of` returns incorrect indexes for strings that have CJK characters

### How to reproduce

```nu
let s = '[Rust 程序设计语言](title-page.md)'
let start = ($s | str index-of '(')
let end = ($s | str index-of ')')
echo ($s | str substring $'($start + 1),($end)')
```
Got output:
```
d)
```
Actual indexes result: $start == 25 && $end == 39

### Expected behavior

The expected behavior should be:
1. Final output: `title-page.md`
2. And the indexes result expected: $start == 13 && $end == 27

### Configuration

| key                | val                                                                                                                                                                     |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.41.0                                                                                                                                                                  |
| build_os           | macos-x86_64                                                                                                                                                            |
| rust_version       | rustc 1.56.1                                                                                                                                                            |
| cargo_version      | cargo 1.56.0                                                                                                                                                            |
| pkg_version        | 0.41.0                                                                                                                                                                  |
| build_time         | 2021-12-07 17:21:00 +00:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

**Comment by fdncred** [comment]
ya, the problem is the unicode characters. I believe the code uses `find(pattern)` and `rfind(pattern)` to locate the index. the problem with that is that `find` doesn't understand these double byte characters. we could change it to use a single char for searching but that limits it. I'm not sure what the right solution is.

**Comment by fdncred** [comment]
I think I figured out how to fix this and fixed it in engine-q. The same fix may work for Nushell.

**Comment by hustcer** [comment]
Works fine in the new engine
