### ISSUE TITLE
add a flag to from csv (or open ) to disable the type inference or a way to specify a column type

### ISSUE THREAD

**Issue by eggcaker** [nushell/nushell#4217]
### Related problem

demo as the image below

![image](https://user-images.githubusercontent.com/21374/146940462-08c99b19-2263-469b-988a-3322af5c99ca.png)

### Describe the solution you'd like

add some flag `--disable-inference` or add `--column-types str int str ` 

### Additional context and details
```csv
file,key
json_202106211443374205793022206.mp3,202106211443374205793022206
json_202110071326581362575723177.mp3,202110071326581362575723177
json_202110271739111705789823147.mp3,202110271739111705789823147
```

**Comment by fdncred** [comment]
cat you also paste that 3 line csv in here so we can use it to test. it would be difficult to type it exactly by looking at your screenshot. :)

**Comment by hustcer** [comment]
Duplication of this one: https://github.com/nushell/nushell/issues/3485

**Comment by hustcer** [comment]
`open -r a.csv | from csv --no-infer ` should work on the latest main
