### ISSUE TITLE
Fails to install on windows via WinGet or Chocolatey

### ISSUE THREAD

**Issue by er2** [nushell/nushell#4218]
### Describe the bug

Upgrading via chocolatey seemed to create a failed, mostly empty install. I uninstalled from Chocolately and tried to install via `winget` and that failed.

### How to reproduce

```
winget install nushell.nushell
```

### Expected behavior

I expected a successful install

### Screenshots

[WinGet-2021-12-21-16-21-47.392.log](https://github.com/nushell/nushell/files/7758267/WinGet-2021-12-21-16-21-47.392.log)

### Additional context
```
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19042 N/A Build 19042
```

**Comment by jntrnr** [comment]
@er2 - we don't manage the packages for chocolatey and winget. You may need to track down the maintainers for nushell for those repos.

**Comment by fdncred** [comment]
It looks like the msi is failing because it's already installed. The log shows error 1603 which points to this https://docs.microsoft.com/en-us/troubleshoot/windows-server/application-management/msi-installation-error-1603. Maybe you can uninstall it and try winget again?

**Comment by fdncred** [comment]
We may need to change our WiX with something similar to this. A PR would be nice :)

https://stackoverflow.com/questions/11732290/how-do-i-make-a-wix-msi-always-remove-a-previous-version

**Comment by hustcer** [comment]
I have successfully installed nushell v0.60 by using winget, I think we can close this now

**Comment by fdncred** [comment]
if i understand correctly, the question is, will you be able to install the next release via winget. if our msi installer doesn't allow you to overwrite the existing install, then we may have to change it.

**Comment by er2** [comment]
This is working for me now. All I did was get the latest update via Chocolatey.
