### ISSUE TITLE
Support Decimal128

### ISSUE THREAD

**Issue by pmeredit** [nushell/nushell#422]
Decimal128 numbers are useful for financial calculations, and some file formats, like bson support them natively. Currently the bson crate does not actually support Decimal128, itself, because the only Decimal128 library is wrapping C, which is a concern for platform-indepdence.

**Comment by jonathandturner** [comment]
@wycats - is this issue complete with your recent decimal work?

**Comment by wycats** [comment]
Yep! I decided on BigDecimal, fwiw
