### ISSUE TITLE
Opening empty yaml file and inserting data should not fail

### ISSUE THREAD

**Issue by fellnerse** [nushell/nushell#4221]
### Describe the bug

executing `touch test.yaml ; nuopen test.yaml | insert id 0` results in:
error: Type Error
  ┌─ shell:1:1
  │
1 │ which starship
  │ ^ Expected row, found nothing

### How to reproduce

`touch test.yaml ; nuopen test.yaml | insert id 0`

### Expected behavior

should print the same as executing `touch test.toml ; nuopen test.toml | insert id 0`

### Screenshots

<img width="357" alt="image" src="https://user-images.githubusercontent.com/41167496/147068655-9677199c-9f09-4344-bd0c-fb2a28e93141.png">

### Configuration

| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.41.0                                                                                                                                                                  |
| build_os           | macos-aarch64                                                                                                                                                           |
| rust_version       | rustc 1.56.1                                                                                                                                                            |
| cargo_version      | cargo 1.56.0                                                                                                                                                            |
| pkg_version        | 0.41.0                                                                                                                                                                  |
| build_time         | 2021-12-07 17:21:00 +00:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

**Comment by fdncred** [comment]
confirmed that this yaml interaction still exists in 0.59.0. not sure if it's the yaml code or the update code, since insert doesn't exist any longer.

**Comment by rgwood** [comment]
I think this no longer applies after v0.60, writing to a YAML file would be done with `save` now. Happy to reopen if I've got that wrong.
