### ISSUE TITLE
fetch panics on some sites when `bat` built with `regex-fancy` engine 

### ISSUE THREAD

**Issue by nibon7** [nushell/nushell#4224]
### Describe the bug

```
thread 'main' panicked at 'regex string should be pre-tested: InvalidEscape("\\g")', /home/nibon7/.cargo/registry/src/github.com-1ecc6299db9ec823/syntect-4.6.0/src/parsing/regex.rs:72:57
stack backtrace:
   0:     0x565521118e5c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7c5cbc950a6e98ca
   1:     0x56552113f7ec - core::fmt::write::h6d4e36f71c229c7e
   2:     0x565521114e35 - std::io::Write::write_fmt::h9a4d183c6d8e2e45
   3:     0x56552111ab60 - std::panicking::default_hook::{{closure}}::h7077f7ca514617b6
   4:     0x56552111a717 - std::panicking::default_hook::h94f8fbeb7a4dbcff
   5:     0x56552111b214 - std::panicking::rust_panic_with_hook::h4f815477eb18bcfb
   6:     0x56552111acf0 - std::panicking::begin_panic_handler::{{closure}}::h7a39573fedeb5d43
   7:     0x565521119304 - std::sys_common::backtrace::__rust_end_short_backtrace::h6230e6996d5f866c
   8:     0x56552111ac59 - rust_begin_unwind
   9:     0x56551ed72de1 - core::panicking::panic_fmt::h7e065fe499918015
  10:     0x56551ed72ed3 - core::result::unwrap_failed::h934e10679b725d01
  11:     0x56551ef3a637 - core::result::Result<T,E>::expect::hf1feff5a8b87eaa8
                               at /rustc/1.56.1/library/core/src/result.rs:1259:23
  12:     0x56551ef667e2 - syntect::parsing::regex::Regex::regex::h7e36ce369d00b0de
                               at /home/nibon7/.cargo/registry/src/github.com-1ecc6299db9ec823/syntect-4.6.0/src/parsing/regex.rs:72:17
  13:     0x56551ef666d0 - syntect::parsing::regex::Regex::search::h237d08dbcd048b7e
                               at /home/nibon7/.cargo/registry/src/github.com-1ecc6299db9ec823/syntect-4.6.0/src/parsing/regex.rs:63:9
  14:     0x56551ef5c023 - syntect::parsing::parser::ParseState::search::h9804194ed99a8437
                               at /home/nibon7/.cargo/registry/src/github.com-1ecc6299db9ec823/syntect-4.6.0/src/parsing/parser.rs:413:27
  15:     0x56551ef5b69f - syntect::parsing::parser::ParseState::find_best_match::h7354815865b66038
                               at /home/nibon7/.cargo/registry/src/github.com-1ecc6299db9ec823/syntect-4.6.0/src/parsing/parser.rs:339:45
  16:     0x56551ef5a989 - syntect::parsing::parser::ParseState::parse_next_token::hb158a80f5e1f8e24
                               at /home/nibon7/.cargo/registry/src/github.com-1ecc6299db9ec823/syntect-4.6.0/src/parsing/parser.rs:239:26
  17:     0x56551ef5a6e5 - syntect::parsing::parser::ParseState::parse_line::h6e49204db2dc9b8c
                               at /home/nibon7/.cargo/registry/src/github.com-1ecc6299db9ec823/syntect-4.6.0/src/parsing/parser.rs:206:15
  18:     0x56551ef3727f - syntect::easy::HighlightLines::highlight::hef0c7418f52c89de
                               at /home/nibon7/.cargo/registry/src/github.com-1ecc6299db9ec823/syntect-4.6.0/src/easy.rs:62:19
  19:     0x56551edacee7 - <bat::printer::InteractivePrinter as bat::printer::Printer>::print_line::hccae50acb09d2656
                               at /home/nibon7/.cargo/registry/src/github.com-1ecc6299db9ec823/bat-0.18.3/src/printer.rs:392:13
  20:     0x56551edf785b - bat::controller::Controller::print_file_ranges::h8b7597d5f3218cdf
                               at /home/nibon7/.cargo/registry/src/github.com-1ecc6299db9ec823/bat-0.18.3/src/controller.rs:230:21
  21:     0x56551edf6fec - bat::controller::Controller::print_file::hf6bcd3e286f331ce
                               at /home/nibon7/.cargo/registry/src/github.com-1ecc6299db9ec823/bat-0.18.3/src/controller.rs:188:13
  22:     0x56551edf63f6 - bat::controller::Controller::run_with_error_handler::he9a89cddaaed9814
                               at /home/nibon7/.cargo/registry/src/github.com-1ecc6299db9ec823/bat-0.18.3/src/controller.rs:138:34
  23:     0x56551edf5525 - bat::controller::Controller::run::hece94fe39961887c
                               at /home/nibon7/.cargo/registry/src/github.com-1ecc6299db9ec823/bat-0.18.3/src/controller.rs:30:9
  24:     0x56551ed84817 - bat::pretty_printer::PrettyPrinter::print::h85f7c0b6034921b2
                               at /home/nibon7/.cargo/registry/src/github.com-1ecc6299db9ec823/bat-0.18.3/src/pretty_printer.rs:279:9
  25:     0x56551ed743d4 - nu_plugin_textview::textview::view_text_value::h43ca91a9de82ed26
                               at /source/rust/nushell/crates/nu_plugin_textview/src/textview.rs:70:9
  26:     0x56551ed73be2 - nu_plugin_textview::nu::<impl nu_plugin::plugin::Plugin for nu_plugin_textview::textview::TextView>::sink::hf25a2af2866b451c
                               at /source/rust/nushell/crates/nu_plugin_textview/src/nu/mod.rs:13:13
  27:     0x56551efb3791 - nu_plugin::plugin::serve_plugin::hade967b77fdee4e4
                               at /source/rust/nushell/crates/nu-plugin/src/plugin.rs:70:21
  28:     0x56551ed737a7 - nu_plugin_core_textview::main::h0ca570f2694b0e48
                               at /source/rust/nushell/src/plugins/nu_plugin_core_textview.rs:5:5
  29:     0x56551ed7371b - core::ops::function::FnOnce::call_once::h860943886c785d50
                               at /rustc/1.56.1/library/core/src/ops/function.rs:227:5
  30:     0x56551ed73a4e - std::sys_common::backtrace::__rust_begin_short_backtrace::h8b88f45cf4f86e86
                               at /rustc/1.56.1/library/std/src/sys_common/backtrace.rs:125:18
  31:     0x56551ed73a21 - std::rt::lang_start::{{closure}}::hbaf91bd9c49b0cac
                               at /rustc/1.56.1/library/std/src/rt.rs:63:18
  32:     0x56552111b81a - std::rt::lang_start_internal::h57f29373da9cb8d0
  33:     0x56551ed739f0 - std::rt::lang_start::haf9a1063e0ae439c
                               at /rustc/1.56.1/library/std/src/rt.rs:62:5
  34:     0x56551ed737cc - main
  35:     0x7f1cca1667fd - __libc_start_main
  36:     0x56551ed735da - _start
  37:                0x0 - <unknown>
```

The `regex-onig` engine seems ok.

### How to reproduce

fetch https://www.google.com

### Expected behavior

fetch don't panic

### Configuration

| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.41.0                                                                                                                                                                  |
| branch             | fetch_panic                                                                                                                                                             |
| short_commit       | 6cd124dd                                                                                                                                                                |
| commit_hash        | 6cd124ddb23267cc085d016d6c752ee599eb6af2                                                                                                                                |
| commit_date        | 2021-12-22 19:48:43 +00:00                                                                                                                                              |
| build_os           | linux-x86_64                                                                                                                                                            |
| rust_version       | rustc 1.56.1 (gentoo)                                                                                                                                                   |
| cargo_version      | cargo 1.56.0                                                                                                                                                            |
| pkg_version        | 0.41.0                                                                                                                                                                  |
| build_time         | 2021-12-24 15:04:30 +08:00                                                                                                                                              |
| build_rust_channel | debug                                                                                                                                                                   |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

**Comment by fdncred** [comment]
This looks like a `bat`/`syntect` regex incompatibility issue, just from the first line of the panic `'regex string should be pre-tested: InvalidEscape("\\g")'`. 

You can see that the error is coming from [here](https://github.com/trishume/syntect/blob/b041cb61210b0dd23b9f332ace247fcfdad90d08/src/parsing/regex.rs#L69) in the syntect crate.


This is taken from [here](https://github.com/sharkdp/bat/blob/43e1a11ad86af47d1a5fb304e973541dab91e16d/doc/assets.md) in the bat repo:
```
bat has a set of syntax highlighting regression tests in tests/syntax-tests. 
The main idea is make sure that we do not run into issues we had in the past where either 
(1) syntax highlighting for some language is suddenly not working anymore or 
(2) bat suddenly crashes for some input (due to regex incompatibilities between syntect and Sublime Text).
```

**Comment by nibon7** [comment]
I have tried `regex-onig` engine on linux and windows, it works fine for me.

**Comment by fdncred** [comment]
if you want to create a pr switching that setting I'll accept it and we can run with it to see if it works ok.

**Comment by nibon7** [comment]
`fancy-regex` has known issues on some syntaxes.
trishume/syntect#287

**Comment by fdncred** [comment]
ah ha, that makes sense. thanks again for the fix.
