### ISSUE TITLE
sourcing a .nu script containing a source command of a file that does not exists fails

### ISSUE THREAD

**Issue by fellnerse** [nushell/nushell#4227]
### Describe the bug

I try to replicate fish [psub](https://fishshell.com/docs/current/cmds/psub.html) command in nu. doing this just for executing works fine (tell me if I dont need to actually write this on my own but I could not find a different way of executing a string: i.e. execute 'ls').

Now I also wanted to be able to source these commands as well (i.e. source 'alias a = b'). In total I would like to parse git aliases automatically.

You can find the script i wrote attached. When the '/tmp/nustuff.nu' is missing I get a weird error:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/41167496/147357227-0850cb1b-836e-49ab-896d-46ce06a5dffd.png">
when I manually create the file it works. But creating the file in the script is not enough, as somehow only the sourcing is tested.
<img width="755" alt="image" src="https://user-images.githubusercontent.com/41167496/147357282-8955f17a-459b-43d7-adc4-03648a0da9f1.png">
Also ideally I would like to use the $file variable for sourcing as for the `nu` command, but this does not work.

### How to reproduce

```
# Writes the input to a file, executes and deletes it
def psub [
            --source (-s)  # wether to source the file or not
        ] {
    each {   
        echo $it $source
        let file = '/tmp/nustuff.nu'
        echo $it | save $file
        cat $file
        if $source == $true { source '/tmp/nustuff.nu'} {nu $file}
    }
}
alias psub = psub
```

### Expected behavior

Should be able to source the script.

### Configuration

| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.41.0                                                                                                                                                                  |
| build_os           | macos-aarch64                                                                                                                                                           |
| rust_version       | rustc 1.56.1                                                                                                                                                            |
| cargo_version      | cargo 1.56.0                                                                                                                                                            |
| pkg_version        | 0.41.0                                                                                                                                                                  |
| build_time         | 2021-12-07 17:21:00 +00:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

### Additional context

Also sourcing in a .nu function in general seems not to work. I only got it to work with a script without function call. Might need the possibility to source a function call.

**Comment by fdncred** [comment]
can you please retest this with the latest main branch?
