### ISSUE TITLE
alias with variable does not work

### ISSUE THREAD

**Issue by fellnerse** [nushell/nushell#4228]
### Describe the bug

When aliasing a variable it does not fail nor work.

### How to reproduce

`echo 'asdf' | each {alias $it = $it} | alias`
<img width="329" alt="image" src="https://user-images.githubusercontent.com/41167496/147358018-cd5d94b8-0a16-4320-98c3-2993388fd18a.png">

### Expected behavior

Should source the alias

### Configuration

| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.41.0                                                                                                                                                                  |
| build_os           | macos-aarch64                                                                                                                                                           |
| rust_version       | rustc 1.56.1                                                                                                                                                            |
| cargo_version      | cargo 1.56.0                                                                                                                                                            |
| pkg_version        | 0.41.0                                                                                                                                                                  |
| build_time         | 2021-12-07 17:21:00 +00:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

**Comment by fdncred** [comment]
I tried this again and i don't believe this is allowed. It also gives an error message now.
```
> echo 'asdf' | each {|r| alias $r = $r } | alias
Error: nu::parser::unexpected_keyword (link)

  × Statement used in pipeline.
   ╭─[entry #1:1:1]
 1 │ echo 'asdf' | each {|r| alias $r = $r } | alias
   ·                                           ──┬──
   ·                                             ╰── not allowed in pipeline
   ╰────
  help: 'alias' keyword is not allowed in pipeline. Use 'alias' by itself, outside of a pipeline.
```
