### ISSUE TITLE
Display wrong CJK characters when using `where` command

### ISSUE THREAD

**Issue by nibon7** [nushell/nushell#4229]
### Describe the bug

When enter multi CJK characters after `where` command,nu can't display the character entered just now.

### How to reproduce

 1. Enter `where ` and then some CJK characters 

### Expected behavior

Display correct CJK characters when using `where` command

### Screenshots

https://user-images.githubusercontent.com/15247421/147386391-a2375760-82fd-42b3-af95-fbb401b24ee3.mp4

### Configuration

| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.41.0                                                                                                                                                                  |
| branch             | main                                                                                                                                                                    |
| short_commit       | 1214cd57                                                                                                                                                                |
| commit_hash        | 1214cd57e885da095d2c213385156278e48c8ead                                                                                                                                |
| commit_date        | 2021-12-24 14:34:59 +00:00                                                                                                                                              |
| build_os           | windows-x86_64                                                                                                                                                          |
| rust_version       | rustc 1.57.0 (f1edd0429 2021-11-29)                                                                                                                                     |
| rust_channel       | stable-x86_64-pc-windows-msvc                                                                                                                                           |
| cargo_version      | cargo 1.57.0 (b2e52d7ca 2021-10-21)                                                                                                                                     |
| pkg_version        | 0.41.0                                                                                                                                                                  |
| build_time         | 2021-12-25 10:38:57 +08:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

### Additional context

Linux has the same issue.

**Comment by fdncred** [comment]
Do you know if the same issue exists in `engine-q`?

**Comment by eggcaker** [comment]
just tested on engine-q, it works.

**Comment by nibon7** [comment]
> Do you know if the same issue exists in `engine-q`?

Thanks, engine-q works!
