### ISSUE TITLE
History auto-complete shouldn't show lines that errored

### ISSUE THREAD

**Issue by Joshfindit** [nushell/nushell#423]
Example from a muscle-memory collision:

```
/private/tmp> ls -la
error: Type Error
- shell:1:3
1 | ls -la
  |    ^^^ Expected Path, found flag
```

The next `ls` suggests `ls -la`

Seems to me a quick/dirty fix would be only add to autosuggest when a command is successful

**Comment by jonathandturner** [comment]
This looks like it needs a better error message. It's underlining the part of the command that didn't work and saying it expecting a path there (since we don't support `ls -la`)

**Comment by Joshfindit** [comment]
@jonathandturner that was probably a bad example as it's totally understandable that someone might think I was talking about `-la` being unsupported.

Here are some other examples:

```

**Comment by Joshfindit** [comment]
Essentially instead of a flow like this that causes this behaviour:
*(apologies for not knowing how `nu` *actually* does this)*

1. Take input
2. Enter is pressed
3. Input is stored in the "autosuggest table"
4. Command is executed and success/fail happens

A flow like this that would avoid it:

1. Take input
2. Enter is pressed
3. Command is executed and success/fail happens
4. **IF** successful: Input is stored in the "autosuggest table"

**Comment by jonathandturner** [comment]
We don't have autosuggest features yet, but we do have an issue for them: https://github.com/nushell/nushell/issues/338

With it, theoretically you might be able to do what you're suggesting. Like:

```
/Users/josh> ps | first seven
error: Value is not a number
- shell:1:11
1 | ps | first seven
  |            ^^^^^ did you mean 7?
```

**Comment by jonathandturner** [comment]
Maybe you're expected the underline to have been changed with a suggestion?  I hadn't thought of that (we've been thinking about the rustc style that underlines and then writes the suggestion as a label)

**Comment by Joshfindit** [comment]
Hm. It seems I'm not communicating this well 😔

I'm just talking about the behaviour that happens when you're typing a command, and *before* it's executed.

![image](https://user-images.githubusercontent.com/1937155/63655674-91992a00-c761-11e9-86c2-5c8f2265ba5b.png)

**Comment by jonathandturner** [comment]
Ah - so you think the history shouldn't be shown if there's a error?

**Comment by Joshfindit** [comment]
![nu first seven](https://user-images.githubusercontent.com/1937155/63655758-ade99680-c762-11e9-89d2-b5f41a351d81.gif)

I would say history (accessing via up arrow) *should*, but auto-suggest *should not*

**Comment by wycats** [comment]
I agree with @Joshfindit. Does Rustyline have a way to differentiate?

**Comment by jonathandturner** [comment]
I've filed this issue upstream: https://github.com/kkawakam/rustyline/issues/297
