### ISSUE TITLE
The command doesn't terminate

### ISSUE THREAD

**Issue by hungpham3112** [nushell/nushell#4230]
I'm new with `nushell` and currently I'm using Window.

When open `gvim` in `nushell`, I have to quit gvim to continue use `nushell`.

![image](https://user-images.githubusercontent.com/75968004/147403802-71542864-3a90-40f7-bc92-8cc1dc51be4b.png)

In picture, `gvim` command line still run and can't continue use `nushell`. It's quite different than `cmd`, `powershell `and others.

**Comment by fdncred** [comment]
does this still exist in the current main branch of the repo?

**Comment by hungpham3112** [comment]
> does this still exist in the current main branch of the repo?

Sorry for late reply, it still exists. I'm using nushell with `scoop install nu` in Windows.

**Comment by jntrnr** [comment]
`scoop install nu` still uses the old version. We'll have a new version published in a few weeks

**Comment by hungpham3112** [comment]
> `scoop install nu` still uses the old version. We'll have a new version published in a few weeks

I got it.

**Comment by hustcer** [comment]
@hungpham3112 scoop should be able to install nu v0.62 now, can you try it again? Does this issue still exists?

**Comment by hustcer** [comment]
It works for me on Windows 10, closing this, feel free to reopen if not work for you

**Comment by hungpham3112** [comment]
I still have this issue with nu 0.66.2 on Windows 11. 

![image](https://user-images.githubusercontent.com/75968004/183550082-04f1bf13-c9b3-48c0-bb0e-ff946b18cecc.png)

**Comment by fdncred** [comment]
Many apps are like this. some apps will launch themselves into the background like vscode does and others like notepad hang the terminal until you quit the app. This is expected behavior until someone adds the ability to launch an app into a background process.

**Comment by jntrnr** [comment]
Closing as dupe of #247
