### ISSUE TITLE
Nushell 0.42 (Windows) will crash if unknown command is entered

### ISSUE THREAD

**Issue by cpkio** [nushell/nushell#4237]
### Describe the bug

Enter any erroneous text in command line.

### How to reproduce

```
Welcome to Nushell 0.42.0 (type 'help' for more info)
29.12.21 18:04:16 C:\ hsd
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\which-4.2.2\src\finder.rs:156:36
stack backtrace:
   0:     0x7ff76a4420af - git_index_checksum
   1:     0x7ff76a462eaa - git_index_checksum
   2:     0x7ff76a437f88 - git_index_checksum
   3:     0x7ff76a444ea6 - git_index_checksum
   4:     0x7ff76a4448a7 - git_index_checksum
   5:     0x7ff76a445505 - git_index_checksum
   6:     0x7ff76a4450eb - git_index_checksum
   7:     0x7ff76a4429d7 - git_index_checksum
   8:     0x7ff76a445049 - git_index_checksum
   9:     0x7ff76a5f0d20 - git_proxy_options_init
  10:     0x7ff76a5f0ce7 - git_proxy_options_init
  11:     0x7ff76993abe8 - git_rebase_onto_id
  12:     0x7ff76993a9c7 - git_rebase_onto_id
  13:     0x7ff76993aaa9 - git_rebase_onto_id
  14:     0x7ff76993a7f7 - git_rebase_onto_id
  15:     0x7ff76993ade0 - git_rebase_onto_id
  16:     0x7ff76a5f01db - git_proxy_options_init
  17:     0x7ff76993ac3b - git_rebase_onto_id
  18:     0x7ff7698e1e30 - git_rebase_onto_id
  19:     0x7ff7698ba0f3 - git_rebase_onto_id
  20:     0x7ff7698b8eac - git_rebase_onto_id
  21:     0x7ff7698cd27c - git_rebase_onto_id
  22:     0x7ff7696b6c08 - git_tag_tagger
  23:     0x7ff76939fb59 - git_filter_source_path
  24:     0x7ff7693833be - git_filter_source_path
  25:     0x7ff7698d14dd - git_rebase_onto_id
  26:     0x7ff7698bfc4f - git_rebase_onto_id
  27:     0x7ff7698aaad4 - git_rebase_onto_id
  28:     0x7ff769903323 - git_rebase_onto_id
  29:     0x7ff769901e20 - git_rebase_onto_id
  30:     0x7ff7698e954b - git_rebase_onto_id
  31:     0x7ff76932923d - <unknown>
  32:     0x7ff7693150e3 - <unknown>
  33:     0x7ff7693137e5 - <unknown>
  34:     0x7ff76931118b - <unknown>
  35:     0x7ff7693116d6 - <unknown>
  36:     0x7ff7693116b8 - <unknown>
  37:     0x7ff76a441b9b - git_index_checksum
  38:     0x7ff769311227 - <unknown>
  39:     0x7ff76a5d4510 - git_proxy_options_init
  40:     0x7ffdb95e3034 - BaseThreadInitThunk
  41:     0x7ffdbb7f1551 - RtlUserThreadStart
```

### Expected behavior

Expected a message of `command not found`.

### Configuration

| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.42.0                                                                                                                                                                  |
| short_commit       | 62011b6b                                                                                                                                                                |
| commit_hash        | 62011b6bccc3fa4d745b3671b499d8dc549c1eb5                                                                                                                                |
| commit_date        | 2021-12-28 09:56:59 +00:00                                                                                                                                              |
| build_os           | windows-x86_64                                                                                                                                                          |
| rust_version       | rustc 1.57.0 (f1edd0429 2021-11-29)                                                                                                                                     |
| rust_channel       | stable-x86_64-pc-windows-msvc                                                                                                                                           |
| cargo_version      | cargo 1.57.0 (b2e52d7ca 2021-10-21)                                                                                                                                     |
| pkg_version        | 0.42.0                                                                                                                                                                  |
| build_time         | 2021-12-28 10:24:46 +00:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

**Comment by fdncred** [comment]
I get this on Mac. I wonder what's happening on Windows.
```
> adf
error: Command not found
  ┌─ shell:1:1
  │
1 │ adf
  │ ^^^ command adf not found
```

**Comment by nibon7** [comment]
Can't reproduce on win11 22000.376.


| Column0            | Column1                                                                                                                                                                 |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.42.0                                                                                                                                                                  |
| branch             | main                                                                                                                                                                    |
| short_commit       | 62011b6b                                                                                                                                                                |
| commit_hash        | 62011b6bccc3fa4d745b3671b499d8dc549c1eb5                                                                                                                                |
| commit_date        | 2021-12-28 09:56:59 +00:00                                                                                                                                              |
| build_os           | windows-x86_64                                                                                                                                                          |
| rust_version       | rustc 1.57.0 (f1edd0429 2021-11-29)                                                                                                                                     |
| rust_channel       | stable-x86_64-pc-windows-msvc                                                                                                                                           |
| cargo_version      | cargo 1.57.0 (b2e52d7ca 2021-10-21)                                                                                                                                     |
| pkg_version        | 0.42.0                                                                                                                                                                  |
| build_time         | 2021-12-30 09:26:56 +08:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, which, zip                                                                                                                  |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

**Comment by cpkio** [comment]
The last working release for me is 0.36.

**Comment by cpkio** [comment]
This erroneos behaviour is caused by `which-4.2.2` when parsing `pathext` environment variable. In my case an extra `;` at the end of `pathext` env was the culprit. The error was raised in CMD only, running from Powershell is OK. Closing this because it's not Nu fault.

**Comment by fdncred** [comment]
oooh, good catch. is there an issue already on the `which` repo?

**Comment by cpkio** [comment]
I've referenced this issue there.
