### ISSUE TITLE
Diff commands with ">" file-output indicator will result in "extra operand" error.

### ISSUE THREAD

**Issue by ShikiSuen** [nushell/nushell#4238]
### Describe the bug

This bug doesn't happen with zsh.

### How to reproduce

Run this command (written in a makefile) in nushell (with any content of the two cin files ready in the current folder):
```
diff -u phone.cin phone-from-libchewingdata.cin > new.patch
```

### Expected behavior

No errors returned.

### Screenshots

![image](https://user-images.githubusercontent.com/3164826/147811708-69ab1cb6-7e3d-4152-a73c-bca034d71359.png)

### Configuration

| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.41.0                                                                                                                                                                  |
| build_os           | macos-x86_64                                                                                                                                                            |
| rust_version       | rustc 1.57.0                                                                                                                                                            |
| cargo_version      | cargo 1.57.0                                                                                                                                                            |
| pkg_version        | 0.41.0                                                                                                                                                                  |
| build_time         | 2021-12-18 21:46:02 +08:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

**Comment by ShikiSuen** [comment]
Not an nushell-specific issue.

**Comment by jntrnr** [comment]
@ShikiSuen in Nushell, `>` means greater than, like `30 > 20`. You can use `| save new.patch` instead.

**Comment by ShikiSuen** [comment]
@jntrnr Thanks for your help.

Something not related to Nushell: I also met exactly the same issue with /bin/sh shipped in macOS, leading to my last resort of appending "|| true" at the end of the commandline. I wonder whether you have any idea about how to deal with that.
