### ISSUE TITLE
Wireguard issue

### ISSUE THREAD

**Issue by cryptoquick** [nushell/nushell#4239]
### Describe the bug

I'm a bit new to nushell, so forgive me if I'm missing something, but when I try to generate a public key using wireguard's config tools, no public key is generated, and instead, `Usage: wg pubkey` is printed to stdout.

### How to reproduce

`wg genkey | tee private.key | wg pubkey > public.key`

### Expected behavior

Nothing printed to stdout, two files in current directory called `public.key` and `private.key`

### Screenshots

![Screenshot from 2022-01-01 19-43-10](https://user-images.githubusercontent.com/285690/147864655-d806cb58-62b8-4d25-8b52-00b8a08f8a8c.png)

### Configuration

| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.41.0                                                                                                                                                                  |
| build_os           | linux-x86_64                                                                                                                                                            |
| rust_version       | rustc 1.57.0 (Arch Linux rust 1:1.57.0-1)                                                                                                                               |
| cargo_version      | cargo 1.57.0                                                                                                                                                            |
| pkg_version        | 0.41.0                                                                                                                                                                  |
| build_time         | 2021-12-07 19:39:17 +00:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

### Additional context

For context, this is a pretty common set of instructions for anyone setting up wireguard as their VPN.

**Comment by fdncred** [comment]
nushell doesn't work with redirection like bash/zsh. the `>` symbol means 5 > 10. you might try ` | save foo` or maybe ` | save --raw foo`

**Comment by cryptoquick** [comment]
Oh... I'm not sure how I feel about that, haha... Even fish worked with that, and it's... a useful command used in lots of things.

**Comment by fdncred** [comment]
Ya, nushell is a little different. POSIX compliance is a [non-goal](https://www.nushell.sh/contributor-book/philosophy.html#non-goals). Good luck! Drop by discord if you want to talk about nushell.
