### ISSUE TITLE
Optional Redirection of `stdout`

### ISSUE THREAD

**Issue by cryptoquick** [nushell/nushell#4240]
### Related problem

I find `>` to be much more useful when used for output redirection than for comparison, so it might be nice if there was an option in the config that would replace the current `>` behavior with something like `gt` or `>=`, or maybe even moving all comparison functionality to a `where` statement.

The current behavior could be a significant barrier to adoption, but perhaps it could be made optional?

### Describe the solution you'd like

Option in config... maybe something like this?

`swap_gt_comparison_operator_with_redirection = true`

I'm not sure if there's a better way to express this idea.

### Describe alternatives you've considered

Not only is replacing `>` with `| save` cumbersome, it's not even guaranteed to have the same behavior.

### Additional context and details

This is something I ran into here:
https://github.com/nushell/nushell/issues/4239#issuecomment-1003657994

I also noticed this confusion happened in another recent feature:
#4238

**Comment by jntrnr** [comment]
"it's not even guaranteed to have the same behavior."

Can you talk a bit more about places where it doesn't act the same for you?

**Comment by cryptoquick** [comment]
> "it's not even guaranteed to have the same behavior."
> 
> Can you talk a bit more about places where it doesn't act the same for you?
> 
> In theory it should be pretty close, if you're saving into a text file.

I'd have to think if I needed to use the --raw option, as mentioned here:

https://github.com/nushell/nushell/issues/4239#issuecomment-1003657994

**Comment by fdncred** [comment]
we also have the `complete` command now which is a bit different. You can test it like this `do -i { git branch n | complete }` - this should capture stderr, stdout, as well as an exit code.

**Comment by rgwood** [comment]
As of version 0.72, we now have `out>` and `err>` for redirection: https://www.nushell.sh/blog/2022-11-29-nushell-0.72.html#redirection

ex: `^ls out> out.txt`

Please give that a spin if you have time, and let us know what you think!
