### ISSUE TITLE
Open -command fails to open text files on Windows when file's extension is something not specifically supported

### ISSUE THREAD

**Issue by gibboni** [nushell/nushell#4243]
### Describe the bug

Open -command fails to open files on Windows when file's extension is something not specifically supported (for example .txt, .bak). The same file/command works on Linux. There is a short delay and after that it will give an error 'invalid charset name'.

### How to reproduce

See the screenshot below.

### Expected behavior

I expect nu to display the content of the text file.

### Screenshots

<img width="422" alt="nu-error" src="https://user-images.githubusercontent.com/17921438/148061326-eabb7f01-cf13-4420-8a98-c97e6f2ed596.png">

### Configuration

| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.42.0                                                                                                                                                                  |
| short_commit       | 62011b6b                                                                                                                                                                |
| commit_hash        | 62011b6bccc3fa4d745b3671b499d8dc549c1eb5                                                                                                                                |
| commit_date        | 2021-12-28 09:56:59 +00:00                                                                                                                                              |
| build_os           | windows-x86_64                                                                                                                                                          |
| rust_version       | rustc 1.57.0 (f1edd0429 2021-11-29)                                                                                                                                     |
| rust_channel       | stable-x86_64-pc-windows-msvc                                                                                                                                           |
| cargo_version      | cargo 1.57.0 (b2e52d7ca 2021-10-21)                                                                                                                                     |
| pkg_version        | 0.42.0                                                                                                                                                                  |
| build_time         | 2021-12-28 10:24:46 +00:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

### Additional context

Nu shell was installed via scoop

**Comment by fdncred** [comment]
hmmm, this is odd. i just did `cp Cargo.toml car.txt` and then `open car.txt` and it opened just fine in textview. if you do `open config.txt | textivew` or `open config.txt -r | textview` does it do anything different?

**Comment by gibboni** [comment]
I managed to find the reason for this. I had installed Nu via Scoop and also a package called unxutils, which contains a bunch of GNU command line utilities for Windows. Something in those utilities was conflicting with Nu shell because when I removed the unxutils package the open-command started to work normally again. After I re-installed the package the problem also returned.

**Comment by fdncred** [comment]
that's really odd. if there is an `open` command in gnu utils nushell shouldn't be calling it unless you typed `^open`. i wonder what was going on under the hood.

**Comment by gibboni** [comment]
Unxutils provides `less` command and I isolated that to be the real culprit behind this. For some reason Nu tries to use it. Renaming the command to something else fixes the issue.

**Comment by gibboni** [comment]
The use of `less` seems to be documented. Because Nu shell can not control what kind of `less` is provided by the system and the pager used can be changed in the configuration (textview.pager) I'm now closing this issue.
