### ISSUE TITLE
Memory allocation failure caused by newlines

### ISSUE THREAD

**Issue by mdfinvia** [nushell/nushell#4244]
### Describe the bug

Processing external data e.g. with `open` or `fetch` containing newlines fails with
```
memory allocation of 7881122326526296064 bytes failed
```

### How to reproduce

1. `char nl | save foo`
2. `open foo`

### Expected behavior

No failure when ingesting trivial raw data.

### Configuration

| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.42.0                                                                                                                                                                  |
| build_os           | linux-x86_64                                                                                                                                                            |
| rust_version       | rustc 1.57.0 (f1edd0429 2021-11-29)                                                                                                                                     |
| rust_channel       | stable-x86_64-unknown-linux-gnu                                                                                                                                         |
| cargo_version      | cargo 1.57.0 (b2e52d7ca 2021-10-21)                                                                                                                                     |
| pkg_version        | 0.42.0                                                                                                                                                                  |
| build_time         | 2022-01-05 23:41:51 +01:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

### Additional context

This issue does not seem to occur in `engine-q`.

**Comment by jntrnr** [comment]
I can't seem to repro in linux mint.

```
/home/jt/Source> char nl | save foo
/home/jt/Source> open foo
───────┬─────────────────────────────────────────────────────────────────────────────
       │ foo
───────┼─────────────────────────────────────────────────────────────────────────────
   1   │ 
───────┴─────────────────────────────────────────────────────────────────────────────
```

**Comment by jntrnr** [comment]
@mdfinvia - what distro are you using?

**Comment by mdfinvia** [comment]
```
> lsb_release -a
LSB Version:	n/a
Distributor ID:	openSUSE
Description:	openSUSE Tumbleweed
Release:	20211207
Codename:	n/a
```

**Comment by mdfinvia** [comment]
I can not reproduce this bug with the prebuilt binaries either.

**Comment by mdfinvia** [comment]
```
> rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)
```

**Comment by jntrnr** [comment]
same here, and I built from source:
```
> rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)
```

hmm, that is odd

**Comment by mdfinvia** [comment]
I built again from source without the `extra` feature enabled and cannot repro.

**Comment by jntrnr** [comment]
here's my setup while we're figuring this out:

```
────┬────────────────────┬───────────────────────────────────────────────────────────
 #  │      Column0       │                          Column1                          
────┼────────────────────┼───────────────────────────────────────────────────────────
  0 │ version            │ 0.42.0                                                    
  1 │ branch             │ main                                                      
  2 │ short_commit       │ 62011b6b                                                  
  3 │ commit_hash        │ 62011b6bccc3fa4d745b3671b499d8dc549c1eb5                  
  4 │ commit_date        │ 2021-12-28 09:56:59 +00:00                                
  5 │ build_os           │ linux-x86_64                                              
  6 │ rust_version       │ rustc 1.57.0 (f1edd0429 2021-11-29)                       
  7 │ rust_channel       │ stable-x86_64-unknown-linux-gnu                           
  8 │ cargo_version      │ cargo 1.57.0 (b2e52d7ca 2021-10-21)                       
  9 │ pkg_version        │ 0.42.0                                                    
 10 │ build_time         │ 2021-12-31 20:59:37 +11:00                                
 11 │ build_rust_channel │ release                                                   
 12 │ features           │ ctrlc, dataframe, default, rustyline, term, trash, uuid,  
    │                    │ which, zip                                                
 13 │ installed_plugins  │ binaryview, chart bar, chart line, fetch, from bson,      
    │                    │ from sqlite, inc, match, post, ps, query json, s3,        
    │                    │ selector, start, sys, textview, to bson, to sqlite, tree, 
    │                    │ xpath                                                     
────┴────────────────────┴───────────────────────────────────────────────────────────
```

Looks like I'm on extra

**Comment by mdfinvia** [comment]
I'm still recompiling, but another thing that might be affecting things is that I am using `sccache`. I will try compiling without sccache too.

**Comment by mdfinvia** [comment]
Can repro again after compiling with `extra`, independent of whether `sccache` is used or not :sweat_smile:

**Comment by mdfinvia** [comment]
I guess I'll have to drill down into the individual features or try a bisect.

**Comment by jntrnr** [comment]
@mdfinvia if you can do that, that'd be great. Happy to fix it if we can find the root cause

**Comment by mdfinvia** [comment]
Oh boy, this is gonna be a fun one. It doesn't repro in debug mode either, so that sounds like some unsoundness to me...

**Comment by mdfinvia** [comment]
Well, I suddenly can't repro at all anymore, so I'm gonna close this for now :eyes:
