### ISSUE TITLE
starship + wezterm + nushell; preserve split-pane working directory

### ISSUE THREAD

**Issue by kcking** [nushell/nushell#4246]
I figured out a configuration that seems to work on windows for informing wezterm of the current directory using OSC7

```
prompt = "echo [(starship_prompt) (ansi -o '7') \"file://\" (pwd) (char bel)] | str collect"
```

Submitting this issue to see if anyone has an idea of how to do it "more correctly," and for others to find if they're wondering how to do it

**Comment by fdncred** [comment]
you could also do this with string interpolation. `prompt = $"(starship_prompt)(ansi -o '7') file://($nu.cwd)(char bel)"`. you might want to check this on the latest main to see if it works.

**Comment by fdncred** [comment]
closing due to suggested solution. please reopen if you have further questions.

**Comment by Abdillah** [comment]
I don't quite get how to do this. Does we need to override starship `init.nu`? 
Or things probably has been change since above conversation.

**Comment by fdncred** [comment]
if you use shell_integration = true, OSC7 is already set https://github.com/nushell/nushell/blob/aaa21c161971e4474a87c1916486e71d37bff426/crates/nu-cli/src/repl.rs#L648-L649

**Comment by Abdillah** [comment]
Ah it seems I have double `let-env config` which led to my other comment mentioned you fdncred. Sorry and thanks.
