### ISSUE TITLE
Bump pretty dependency for nu-source

### ISSUE THREAD

**Issue by michel-slm** [nushell/nushell#4249]
### Related problem

nu-source currently requires pretty 0.5.2, but 0.11.2 is out (0.5.2 is released over 3 years ago).

From upstream's changelog, there's a minor breaking change in v0.7.0, so this might need some testing:
https://github.com/Marwes/pretty.rs/blob/master/CHANGELOG.md

- Rename space to line and newline to hardline

### Describe the solution you'd like

nu-source's Cargo.toml requires a newer version of pretty

### Additional context and details

I'm packaging nushell in Fedora, and we generally prefer maintaining a single version of each crate, though sometimes we're forced to keep several versions if there's significant API breakage and we have crates that depend on incompatible versions.

**Comment by fdncred** [comment]
can you please confirm this in nushell again since we've merged engine-q into it?

**Comment by michel-slm** [comment]
@fdncred I'll try again, thanks! Will report back

**Comment by michel-slm** [comment]
nu-source 0.44.0 still require pretty 0.5.2: https://crates.io/crates/nu-source/0.44.0/dependencies

but it seems that crate is gone after the engine-q merge. Is there an ETA for releasing 0.59.0 / 0.60.0? Fedora packaging relies on published crates, so I'll have to wait for that to be cut. Thanks!

**Comment by fdncred** [comment]
Roughly 3 weeks unless we decide to release a beta.

**Comment by michel-slm** [comment]
I've pencilled it in my calendar, thanks

**Comment by fdncred** [comment]
closing since it's not used any longer

**Comment by fdncred** [comment]
closing since it's not used any longer
