### ISSUE TITLE
Consider forking common-path

### ISSUE THREAD

**Issue by michel-slm** [nushell/nushell#4250]
### Related problem

common-path, which `nu-data` depends on, [has not been updated in 3 years](https://crates.io/crates/common-path), and the [upstream repo](https://gitlab.com/pwoolcoc/common-path) is no longer present.

Looking at the author's [other crates](https://crates.io/users/pwoolcoc?sort=recent-updates), faclair is also missing a repo, and many of the recent updates involve putting the crates in the public domain.

I've reached out to the author via email, but have not heard back.

### Describe the solution you'd like

I asked the author to at least temporarily put the repo back up. If the author responds, perhaps the Nushell project can consider forking it the same way `nu-json` is maintained here as a fork, and that way we have the development history preserved.

### Describe alternatives you've considered

Fallback: just create a new repo and check in the current crate as is.

### Additional context and details

This came up during the [Fedora package review](https://bugzilla.redhat.com/show_bug.cgi?id=2038645), when the reviewer noticed that the `rand` dev-dependency is really old (`common-path` builds and tests fine with the latest `rand`), and I tried filing a PR upstream and noticed there's no upstream.

**Comment by kubouch** [comment]
Thanks for checking the dependencies. I think nu-data might not be necessary anymore once we merge engine-q. We have values built in directly in the nu-protocol and it does not seem to have the common-path dependency.

If this functionality is needed, we can replicate it in the `nu-path` crate.

**Comment by jntrnr** [comment]
This should be fixed in the latest engine in main.

**Comment by michel-slm** [comment]
awesome, thanks! my packaging effort was blocked on this, so looks like now I can continue
