### ISSUE TITLE
cargo.toml: expand '~' in path variables

### ISSUE THREAD

**Issue by danjenson** [nushell/nushell#4251]
### Describe the bug

I use nushell across a linux and mac installation. Unfortunately, the home on void linux is `/home/danj` while it is `/Users/danj` on the mac. Having directories that don't exist in the path really seems to throw off nushell, i.e. having `/home/danj/.cargo/bin` in my path on mac makes the nushell prompt much, much slower (presumably because it's attempting to search a directory that doesn't exist?). 

### How to reproduce

1. Put a path that doesn't exist int he paths variable to see the prompt slow down.
2. Put a path with '~' in it to see that it doesn't search these paths.

### Expected behavior

It would search '~' paths.

### Configuration

| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.42.0                                                                                                                                                                  |
| build_os           | macos-x86_64                                                                                                                                                            |
| rust_version       | rustc 1.60.0-nightly (1409c015b 2022-01-11)                                                                                                                             |
| rust_channel       | nightly-x86_64-apple-darwin                                                                                                                                             |
| cargo_version      | cargo 1.60.0-nightly (358e79fe5 2022-01-04)                                                                                                                             |
| pkg_version        | 0.42.0                                                                                                                                                                  |
| build_time         | 2022-01-11 19:07:02 -08:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

**Comment by kubouch** [comment]
Yeah, this is an issue. In engine-q, you'll be able to manipulate and customize environment variables on startup with arbitrary Nushell code so you can expand it manually your config. But `~` should also "just work" without manual expansion in Nushell, but for running external commands, you'll still probably want to send the expanded form.

**Comment by jntrnr** [comment]
The new engine should do a lot more expansion than the previous engine. In theory, the cases you were hitting should "just work" now.

If you're still having problems with the latest main, please reopen this issue or file new issues.
