### ISSUE TITLE
Segmentation fault on OpenBSD -current

### ISSUE THREAD

**Issue by WildSphinx** [nushell/nushell#4253]
### Describe the bug

I get a segfault when I run nu.
```
$ nu
Welcome to Nushell 0.42.0 (type 'help' for more info)
Segmentation fault (core dumped)
```
I can run commands with nu -c.

### How to reproduce

1. run nu
2. segfault

### Expected behavior

The shell should run normally!

### Configuration

> version | pivot key value | to md --pretty

| key                | value                                                  |
| ------------------ | ------------------------------------------------------ |
| version            | 0.42.0                                                 |
| build_os           | openbsd-x86_64                                         |
| rust_version       | rustc 1.57.0                                           |
| cargo_version      | cargo 1.57.0                                           |
| pkg_version        | 0.42.0                                                 |
| build_time         | 2022-01-12 20:45:18 UTC                            |
| build_rust_channel | release                                                |
| features           | ctrlc, dataframe, default, rustyline, term, which, zip |
| installed_plugins  | fetch, post, ps, sys                                   |

### Additional context

I don't think it's related, but I compiled nushell with the following command, because libressl 3.5.0 in -current isn't officially released on libressl.org, thus not supported by openssl-sys, so I used openssl instead:

`$ OPENSSL_LIB_DIR=/usr/local/lib/eopenssl30 OPENSSL_INCLUDE_DIR=/usr/local/include/eopenssl30 cargo install nu`

**Comment by hustcer** [comment]
@WildSphinx Have you tried the latest nu version v0.63 ?  Or you can compile nu from the latest main branch

**Comment by hustcer** [comment]
Since there is no response we will close this issue first, if you still have such issues please reopen it
