### ISSUE TITLE
how to set default encoding to UTF-8 in windows 10?

### ISSUE THREAD

**Issue by Silentdoer** [nushell/nushell#4255]
### Describe the solution you'd like

can set encoding by config.

**Comment by fdncred** [comment]
can you please explain your use case more?

**Comment by Becker-Asano** [comment]
After a fresh install via 'winget install nushell' (see: https://www.nushell.sh/) on Windows 10 and after fixing the config file problem as described in https://github.com/nushell/nushell/issues/5455#issuecomment-1119536130, an 'ls' gives me this:
![image](https://user-images.githubusercontent.com/1073833/167778251-50b1a392-6dbc-4bc5-bd4a-43227841fa01.png)
Not nice, not usable, thus UTF8 encoding would be nice to have..

**Comment by fdncred** [comment]
It's a little known functionality that, in windows, you can use `chcp 65001`, "change codepage", to change the code page of the terminal/command prompt.

https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window
