### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by brasilikum** [nushell/nushell#4257]
### Describe the bug
```
❯ stat (which git)
error: Type Error
   ┌─ shell:18:13
   │
18 │ stat (which git)
   │             ^^^ Expected string, found row


~ 
❯ stat (which "git")
error: Type Error
   ┌─ shell:19:13
   │
19 │ stat (which "git")
   │             ^^^^^ Expected string, found row


~ 
❯ stat (which 'git')
error: Type Error
   ┌─ shell:20:13
   │
20 │ stat (which 'git')
   │             ^^^^^ Expected string, found row


~ 
❯ stat (which 'git').path
16777231 3483905 lrwxr-xr-x 1 g admin 0 28 "Nov 25 18:07:03 2021" "Nov 25 18:07:03 2021" "Nov 25 18:07:03 2021" "Nov 25 18:07:03 2021" 4096 0 0 /opt/homebrew/bin/git

~ 
❯ stat (which git).path
16777231 3483905 lrwxr-xr-x 1 g admin 0 28 "Nov 25 18:07:03 2021" "Nov 25 18:07:03 2021" "Nov 25 18:07:03 2021" "Nov 25 18:07:03 2021" 4096 0 0 /opt/homebrew/bin/git
```

### How to reproduce

1. stat (which 'git')

### Expected behavior

The error message should tell me that I need to add something like `.path` 

### Configuration

❯ version | pivot key value | to md --pretty 
| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.42.0                                                                                                                                                                  |
| build_os           | macos-aarch64                                                                                                                                                           |
| rust_version       | rustc 1.56.1                                                                                                                                                            |
| cargo_version      | cargo 1.56.0                                                                                                                                                            |
| pkg_version        | 0.42.0                                                                                                                                                                  |
| build_time         | 2021-12-28 09:56:59 +00:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

**Comment by fdncred** [comment]
agreed, errors are the best yet in nushell. typically, the debug process is to run the `(which git)` first to see what it does and then call the external on it. on engine-q this works different but i'm not sure i'd call it better. `stat (which git | decode utf-8)`. This is the error on e-q that i get may be a little better if i try the first command.

```
> stat (which git)       
Error: nu::shell::external_command (link)                                                                                                                                 

  × External command
   ╭─[entry #3:1:1]
 1 │ stat (which git)
   ·      ─────┬─────
   ·           ╰── Cannot convert argument to a string
   ╰────
```

**Comment by fdncred** [comment]
this is fixed in nushell/main now with `stat (which git).path`
