### ISSUE TITLE
Environment variables all in single row

### ISSUE THREAD

**Issue by rookboom** [nushell/nushell#4260]
### Describe the bug

My environment variables seems to be transposed.

### How to reproduce

My config.toml looks like this:
``` 
path = ["/home/foo/.cargo/bin", "home/foo/.local/bin", "/usr/local/cuda-11.4/bin"]
prompt = "starship prompt"
startup = ["source /home/foo/repos/nu_scripts/virtual_environments/venv.nu", "alias deactivate = source /home/foo/repos/nu_scripts/virtual_environments/venv_deactivate.nu", "alias activate = load-env (venv .venv)", "zoxide init nushell --hook prompt | save /home/foo/.zoxide.nu", "source /home/foo/.zoxide.nu"]

[env]
LIBTORCH = "/home/foo/libtorch"
LD_LIBRARY_PATH = "/home/foo/libtorch/lib:$LD_LIBRARY_PATH"
```

When I view my environment variables with `echo $nu.env` is see this:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/1814791/149874837-bf726773-7766-4649-9d4e-55364d98eefc.png">

### Expected behavior

I expected it to look more like:

| Name  | Value |
| ------------- | ------------- |
| LIBTORCH    | "/home/foo/libtorch"  |
| LD_LIBRARY_PATH | "${LIBTORCH}/lib:$LD_LIBRARY_PATH"  |

### Configuration

| key                | value                                                  |
| ------------------ | ------------------------------------------------------ |
| version            | 0.42.0                                                 |
| build_os           | linux-x86_64                                           |
| rust_version       | rustc 1.56.0 (09c42c458 2021-10-18)                    |
| rust_channel       | stable-x86_64-unknown-linux-gnu                        |
| cargo_version      | cargo 1.56.0 (4ed5d137b 2021-10-04)                    |
| pkg_version        | 0.42.0                                                 |
| build_time         | 2021-12-31 11:14:47 -08:00                             |
| build_rust_channel | release                                                |
| features           | ctrlc, dataframe, default, rustyline, term, which, zip |
| installed_plugins  | fetch, match, post, ps, sys                            |

### Additional context

My environment variables also doesn't seem to be working, so I am wondering whether I have the formatting wrong.

**Comment by fdncred** [comment]
this is expected behavior. you can pipe through pivot like `echo $nu.env | pivot` or you can set the `pivot_mode` in the config file to `always`, `never`, or `auto`.

**Comment by jntrnr** [comment]
This is also fixed in the upcoming engine (nicknamed engine-q), so future versions will go up-down rather than left-to-right

**Comment by fdncred** [comment]
use the `transpose` command in nushell v0.59 now.
