### ISSUE TITLE
If user uninstall nushell, it should self-destruct all configs. And if user reinstall nushell, it should just work without throwing error.

### ISSUE THREAD

**Issue by PranavBhattarai** [nushell/nushell#4265]
### Related problem

I have a similar situation here in Fedora Workstation 35 as u can see:
![image](https://user-images.githubusercontent.com/32763112/149974398-19cb5165-ef04-4755-b682-352c82d0272f.png)

Everything was working fine. I used Nushell with [Starship](https://starship.rs/) prompt in Alacritty terminal. It was very fast and responsive. Suddenly today I decided to use vanilla Nushell with no other hacks (like starship) from scratch. So I uninstalled nushell, even wiped nu's config folder and file. And then I reinstall nushell.
That's when things started to see error messages whenever I launched nushell.

Above _tried_ to use above mentioned solution, but it didn't work. Am I doing it the right way?!
![image](https://user-images.githubusercontent.com/32763112/149975328-98072df3-b17a-4d85-ad30-a170fc375b96.png)

I do have a directory and a file inside ~/.config/nu folder and it also has config.toml file as you can see:
![image](https://user-images.githubusercontent.com/32763112/149975695-8fa8ade3-ee58-475c-86ac-67fb5b2129ac.png)
But this doesn't get recognized by nushell for some weird reason.

### Describe the solution you'd like

There are many noob users like me who could benefit from this feature request. The user expects when he/she uninstall something, it really purge everything off in a clean slate. But it's not the case.  We do have some config files left behind. And configs might not always be in the standard `~/.config` folder. It could be hidden somewhere where uninstallers usually ignore.

Providing clean uninstallation and reinstallation environment, encourage user to use the software. Because he /she is going through that painful process for a reason. And the reason is **EXPECTATION** that software will work. if he/she wants to reinstall the shell, it should just work as if the user was installing in some newly installed Linux distribution for the first time.

### Describe alternatives you've considered

- sudo dnf remove nushell
- sudo dnf update; sudo dnf clean packages; sudo dnf system-upgrade clean ; flatpak update; sudo dnf autoremove; flatpak uninstall --unused
- restarted my pc
- delete /.config/nu directory and its config.toml file

### Additional context and details

- Distro: Fedora Workstation 35 
- Architecture: x86_64
- Gnome: 41

**Comment by kubouch** [comment]
It is the package manager's job to clean up the installation because Nushell does not really have a way to know when it's being uninstalled.

That being said, if I understand the issue correctly, in the upcoming big Nushell update all the paths are listed under `$nu`, for example `$nu.config-file`, etc. So you can list all these paths and delete them, then remove Nushell.

**Comment by PranavBhattarai** [comment]
cool. Can't wait for this big update.

**Comment by sholderbach** [comment]
Closing this as this is probably packaging platform specific and should be discussed with the distributors and done according to the platform conventions.
