### ISSUE TITLE
Case-insensitive matching

### ISSUE THREAD

**Issue by UmbralReaper** [nushell/nushell#4267]
### Describe the solution you'd like

Case-insensitive matching for commands, in particular the `where` command, to make
```
$ ls | where type == file
```
the same as 
```
$ ls | where type == File
```

**Comment by adamkpickering** [comment]
I'm not sure I agree that this would be a good thing to do. We definitely want the ability to do exact matches using `where`, so this seems like it would entail adding another operator.

Also, this sort of thing could be done if there were an operator that did regex, for which case insensitivity is just one case. A quick search turns up https://stackoverflow.com/questions/56094933/how-to-make-regex-case-insensitive.

**Comment by hustcer** [comment]
@UmbralReaper You can do it this way: `ls | where type =~ "(?i)File"`, for more detail: https://www.nushell.sh/book/operators.html#regular-expression-string-contains-operators

**Comment by UmbralReaper** [comment]
That's awesome! Regex matching is a nice feature to have.
Though, the goal of this idea was to type less at the prompt, not more 😅.

**Comment by jmoore34** [comment]
See also `ls | find file`
