### ISSUE TITLE
Document regex capabilities

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4268]
### Related problem

Asked here
https://github.com/nushell/nushell/discussions/4266

### Describe the solution you'd like

We should state what kind of regex we support.

This might be as simple as stating we use the `regex` crate. I haven't looked at all the commands that use regex, so I'm not sure.

**Comment by fdncred** [comment]
agreed. i've chased this question myself a couple times. having it documented would help because it is a very particular flavor of regex.

**Comment by sakimyto** [comment]
Hi, I was just trying to read the whole project before I joined the development.
Let me see if I understood it right.
Check where regex is used in the entire `nushell/crates/` directory, and create documentation on regex, is that it?

**Comment by kubouch** [comment]
@sakimyto Yeah, that sounds right.

We're about to merge the big update relatively soon, but I don't think it will impact this issue since AFAIK we did not change anything regarding regex.

**Comment by sakimyto** [comment]
@kubouch
OK. Let's find out where it is used.

**Comment by sakimyto** [comment]
First, I checked each of their `Cargo.toml`. But the only thing I could find related to regular expressions was `rust_lang/regex`. However, I found a possibility that it uses other crates in dependencies of dependencies. For exmaple, `nu_plugin_textview` -> `sharkdp/bat` -> `rust-onig/rust-onig`.
We should also look into crates for dependents, right?

**Comment by fdncred** [comment]
textview will be removed in the next version of nushell but regex is used in a few place like in the `str find-replace` command. so, I'd just focus on the https://github.com/rust-lang/regex

**Comment by sakimyto** [comment]
Then, I'll add that we basically use rust-lang/regex to the docs and cotributer book？

**Comment by kubouch** [comment]
@sakimyto Yeah, that sounds good!

**Comment by sakimyto** [comment]
Hmmm,where would be a good place to write this?
I'm thinking of adding to 2 parts.

1. Add to the end of https://github.com/nushell/nushell.github.io/blob/master/contributor-book/plugins.md#creating-a-plugin-in-rust
2. Add to the end of https://github.com/nushell/nushell/blob/main/docs/commands/README.md#anything-else

**Comment by fdncred** [comment]
Maybe make a new section in the book called regex?

**Comment by sakimyto** [comment]
@fdncred I'm grateful for your support. Created PR.
https://github.com/nushell/nushell.github.io/pull/218

**Comment by kubouch** [comment]
Fixed with @sakimyto 's PR
