### ISSUE TITLE
Reverse sort does  not work

### ISSUE THREAD

**Issue by zdrummond** [nushell/nushell#427]
Looking at the docs[1] I see that you should be able to pass `--reverse` to `sort-by`. But when I do so I get 

```
ls | sort-by size --reverse
error: Unimplemented: passing flags is not supported yet.
```

[1] also, there really should be a way to get help from the command line. I assumed man or --help would work, and they did not. Even the Nu book didn't have a comperhensive list of commands. Finally the README did the trick.

**Comment by jonathandturner** [comment]
@zdrummond - your example works for me, though the support for `--reverse` just landed very recently. Are you on a recent version of the code in master?

**Comment by zdrummond** [comment]
I just installed via cargo at 1:57pm PST today.

It says it downloaded and installed `nu v0.2.0` if that helps?

**Comment by androbtech** [comment]
> I just installed via cargo at 1�:57pm PST today.
> 
> It says it downloaded and installed `nu v0.2.0` if that helps?

Hi @zdrummond . You installed the released binary. `--reverse` support landed after that release. [try building from source to get it](https://book.nushell.sh/en/installation#building-from-source). Make sure to follow instructions and report back any issues you might encounter.

**Comment by dbarnett** [comment]
Yup, I was going to report the same thing but after building from source it does work. This can be closed as Fixed.

**Comment by twe4ked** [comment]
Interestingly #421 just landed. Do we want to keep the `--reverse` flags?

**Comment by jonathandturner** [comment]
@twe4ked - that'd be good for a separate issue. I'll close this, if you want to file another issue to look into if it makes sense to keep it.

**Comment by twe4ked** [comment]
https://github.com/nushell/nushell/issues/452
