### ISSUE TITLE
gpg failed to sign the data

### ISSUE THREAD

**Issue by Relwi** [nushell/nushell#4273]
### Describe the bug

When I try to commit in the terminal with gpg, it gives me this error:
```
error: gpg failed to sign the data
fatal: failed to write commit object
```
To work in bash I needed to add `export GPG_TTY=$(tty)` in `~/.bashrc` and it works. But in Nushell idk what I need to put in the `~/.config/nu/config.toml`, if I put the previous command doesn't work.

### How to reproduce

1. Do some changes on a project.
2. `git add .`
3. `git commit -m "some message"`

### Expected behavior

I expected nu to show the "import password" of gpg and allow to commit.

### Configuration

❯ version | pivot key value | to md --pretty
| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.43.0                                                                                                                                                                  |
| branch             | makepkg                                                                                                                                                                 |
| short_commit       | 4e8e0386                                                                                                                                                                |
| commit_hash        | 4e8e03867c87307d536369a20dbe81491666ee51                                                                                                                                |
| commit_date        | 2022-01-18 17:51:21 +00:00                                                                                                                                              |
| build_os           | linux-x86_64                                                                                                                                                            |
| rust_version       | rustc 1.58.0 (Arch Linux rust 1:1.58.0-1)                                                                                                                               |
| cargo_version      | cargo 1.58.0                                                                                                                                                            |
| pkg_version        | 0.43.0                                                                                                                                                                  |
| build_time         | 2022-01-19 02:01:57 +00:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

**Comment by jntrnr** [comment]
in the startup section, something similar to the bash would be:

```
let-env GPG_TTY = (tty)
```

**Comment by Relwi** [comment]
Damn that was fast, it works of course, thanks for your help! Im gonna close the issue.
