### ISSUE TITLE
build fails on FreeBSD 11.2-STABLE

### ISSUE THREAD

**Issue by fdge** [nushell/nushell#428]
```
   Compiling heim-virt v0.0.6
error: Unsupported target OS
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/heim-virt-0.0.6/src/sys/mod.rs:15:9
   |
15 |         compile_error!("Unsupported target OS");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0425]: cannot find function `detect` in module `self::sys`
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/heim-virt-0.0.6/src/lib.rs:182:16
    |
182 |     self::sys::detect()
    |                ^^^^^^ not found in `self::sys`
help: possible candidate is found in another module, you can import it into scope
    |
33  | use crate::detect;
    |

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `heim-virt`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `nu v0.2.0`, intermediate artifacts can be found at `/tmp/cargo-install8xMg4w`

Caused by:
  build failed
```

**Comment by jonathandturner** [comment]
If you build without the `sys` plugin (if you remove it from the Cargo.toml), does it get further?

**Comment by fdge** [comment]
(I'm still learning rust)
I'm assuming I needed to comment these lines

#[[bin]]
#name = "nu_plugin_sys"
#path = "src/plugins/sys.rs"


by doing that I get more errors:

   Compiling darling v0.9.0
   Compiling darling v0.8.6
   Compiling heim-net v0.0.6
   Compiling heim-process v0.0.6
error: Unsupported target OS
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/heim-process-0.0.6/src/sys/mod.rs:15:9
   |
15 |         compile_error!("Unsupported target OS");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0412]: cannot find type `IoCounters` in module `sys`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/heim-net-0.0.6/src/counters.rs:10:28
   |
10 | pub struct IoCounters(sys::IoCounters);
   |                            ^^^^^^^^^^ not found in `sys`
help: possible candidate is found in another module, you can import it into scope
   |
1  | use crate::counters::IoCounters;
   |

error[E0425]: cannot find function `io_counters` in module `sys`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/heim-net-0.0.6/src/counters.rs:83:10
   |
83 |     sys::io_counters().map_ok(Into::into)
   |          ^^^^^^^^^^^ not found in `sys`
help: possible candidate is found in another module, you can import it into scope
   |
1  | use crate::counters::io_counters;
   |

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0412, E0425.
For more information about an error, try `rustc --explain E0412`.
error: Could not compile `heim-net`.
warning: build failed, waiting for other jobs to finish...
error[E0425]: cannot find function `pids` in module `sys`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/heim-process-0.0.6/src/pids.rs:11:10
   |
11 |     sys::pids()
   |          ^^^^ not found in `sys`
help: possible candidate is found in another module, you can import it into scope
   |
1  | use crate::pids::pids;
   |

error[E0425]: cannot find function `pid_exists` in module `sys`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/heim-process-0.0.6/src/pids.rs:16:10
   |
16 |     sys::pid_exists(pid)
   |          ^^^^^^^^^^ not found in `sys`
help: possible candidate is found in another module, you can import it into scope
   |
1  | use crate::pids::pid_exists;
   |

error[E0412]: cannot find type `Process` in module `sys`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/heim-process-0.0.6/src/process/mod.rs:14:25
   |
14 | pub struct Process(sys::Process);
   |                         ^^^^^^^ not found in `sys`
help: possible candidate is found in another module, you can import it into scope
   |
1  | use crate::process::Process;
   |

error[E0425]: cannot find function `processes` in module `sys`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/heim-process-0.0.6/src/process/mod.rs:51:10
   |
51 |     sys::processes().map_ok(Into::into)
   |          ^^^^^^^^^ not found in `sys`
help: possible candidate is found in another module, you can import it into scope
   |
1  | use crate::process::processes;
   |

error: aborting due to 5 previous errors

Some errors have detailed explanations: E0412, E0425.
For more information about an error, try `rustc --explain E0412`.
error: Could not compile `heim-process`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `nu v0.2.0`, intermediate artifacts can be found at `/tmp/cargo-installJivazk`

Caused by:
  build failed

**Comment by wycats** [comment]
P.S. we should have an official policy about supported platforms. As a starting point, we should probably support all of Rust's tier-1 platforms.
