### ISSUE TITLE
Panic on def-hide-def combo with pre-existing def

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4287]
```
line1> def foo [] { "foo" }

line2> def foo [] { "foo" }; hide foo; def foo [] {
panic!
```
 It panics on `get_decl_mut()` at this line: https://github.com/nushell/engine-q/blob/e76451866dd6b70755d7f318a329c6631edb974a/crates/nu-parser/src/parse_keywords.rs#L109

On line2, the first foo was hidden so when attempting to get the "foo" decl, it finds "foo" defined in line1 and attempts to get a mut ref for it which is not possible because it's already inside the permanent state.

Seems like `get_decl_mut()` is used solely in `parse_def()` to get the predeclared def and fill in the contents, so maybe it could be changed to only look for predecls inside the delta's scope frame predecls and return None if it couldn't find any which would be converted to InternalError inside parse_def().

**Comment by kubouch** [comment]
Still happens but seems like on a different line:

```
> def foo [] { "foo" }   
> def foo [] { "foo" }; hide foo; def foo [] { "bar"  # hitting } triggers:
thread 'main' panicked at 'internal error: can only mutate declarations in working set', crates\nu-protocol\src\engine\engine_state.rs:1197:13
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b\/library\core\src\panicking.rs:107
   2: nu_protocol::engine::engine_state::StateWorkingSet::get_decl_mut
   3: nu_parser::parse_keywords::parse_def
   4: nu_parser::parser::parse_builtin_commands
   5: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   6: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
   7: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
   8: <nu_protocol::ast::block::Block as core::convert::From<T>>::from
   9: nu_parser::parser::parse_block
  10: nu_parser::parser::parse
  11: <nu_cli::syntax_highlight::NuHighlighter as reedline::highlighter::Highlighter>::highlight
  12: reedline::engine::Reedline::clear_screen
  13: reedline::engine::Reedline::read_line
  14: nu::repl::evaluate
  15: core::ptr::drop_in_place<alloc::sync::Arc<nu_command::strings::str_::substring::Substring>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jntrnr** [comment]
This seems to be happening because we're trying to update some information inside of the EngineState instead of the working set. When we hide and when we add `def` definitions, these all would need to go into the EngineState. That needs to be true regardless of how many `hide` calls the user makes.

I'll let you dig in as you know this code better than me, but I'd be happy to brainstorm with you.
