### ISSUE TITLE
Need to move painting to viewer

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#4288]
Currently, it looks like we're adding ANSI codes to the strings themselves in the table. This works great at first, but if you try to extract the data, you still get the ANSI.

![image](https://user-images.githubusercontent.com/547158/142774295-2575f1e4-1b99-4d0c-b9d7-c829d0473235.png)

Thinking about this a bit - I think the best place for the coloring is much later in the pipeline. The viewer could read some metadata or something(?) and know what color to paint the cell.

**Comment by jntrnr** [comment]
This seems to be fixed now? Closing, but we should watch for it.

**Comment by amtoine** [comment]
> This seems to be fixed now? Closing, but we should watch for it.
>
i do not see any ANSI colors in the `nushell` repo
```nushell
> ls | get name.1 | into binary
Length: 15 (0xf) bytes | printable whitespace ascii_other non_ascii
00000000:   43 4f 4e 54  52 49 42 55  54 49 4e 47  2e 6d 64      CONTRIBUTING.md
```
whereas
```nushell
> $"(ansi red)foo(ansi reset)" | into binary
Length: 12 (0xc) bytes | printable whitespace ascii_other non_ascii
00000000:   1b 5b 33 31  6d 66 6f 6f  1b 5b 30 6d                •[31mfoo•[0m
```
