### ISSUE TITLE
need `is_custom` in command to tell if command is a custom command

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4291]
in nushell we have this:
![image](https://user-images.githubusercontent.com/343840/144611214-b9cf9d70-81c6-4d67-b1e5-db0493696922.png)

in e-q we have this:
![image](https://user-images.githubusercontent.com/343840/144611722-fca2456f-871a-4cbb-9b15-6f0c9fa3ae41.png)

- [ ] add `signature` to `$scope.commands` table.
- [x] add `is_custom` to `$scope.commands` table.

**Comment by hustcer** [comment]
We have is_custom already, but there is no `signature` column
