### ISSUE TITLE
Hiding used module from script fails

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4292]
After `use ~/.config/nushell/init.nu *` inside `~/.config/nushell/config.nu`, `hide init` in REPL fails for some reason when it is .

**Comment by jntrnr** [comment]
@kubouch is this still an issue?

**Comment by amtoine** [comment]
in my config, i'm using a module of mine called `gm`
```nushell
> gm
the `nu-[g]it-[m]anager`, a WIP to manage any `git` repo in a centralized store, with sugar on top
...
```
and if i hide it in the REPL
```nushell
> hide gm
```
it's gone
```nushell
> gm
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #3:1:1]
 1 │ gm
   · ─┬
   ·  ╰── executable was not found
   ╰────
  help: No such file or directory (os error 2)
```

**Comment by sholderbach** [comment]
> in my config, i'm using a module of mine called `gm`

@amtoine 
Are you using it with `use scriptname.nu *` as in the MRE? If yes, feel free to close

**Comment by amtoine** [comment]
> Are you using it with `use scriptname.nu *` as in the MRE? If yes, feel free to close
>
not with `gm` but i'm able to not see any "*fail*" when doing this with a file
1. put `use nu-goat-scripts/src/sys.nu *` in my `config.nu` (`sys.nu` comes from my [`nu-goat-scripts`](https://github.com/goatfiles/scripts/tree/main/nu_scripts))
2. start the REPL
3. i can use the [`disk` command](https://github.com/goatfiles/scripts/blob/8acc6c89eb60279c1a0d30ee4c9513701ad0bba4/nu_scripts/src/sys.nu#L2-L9)
4. `hide sys` does not do anything (:question: is this the bug??)
5. `hide disk` hides the `disk` command and i cannot use it anymore

i'm not sure what we mean by "*fails*" in the original issue, is this what happens in step 4? :thinking:

**Comment by kubouch** [comment]
Can't reproduce. The `hide init` shouldn't work because definitions from `init` were imported with `*` without the `init` prefix.
