### ISSUE TITLE
Allow creating default prompt manually

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4297]
For integrations that modify the prompt, it would be nice if we could get a default prompt (also right prompt) via, e.g., a new command.

An example integration in virtualenv would then look like this:
```
# if PROMPT_COMMAND environment variable is not set:
let PROMPT_COMMAND = { $"($virtual-env) (default-prompt)" }
```

**Comment by elferherrera** [comment]
isnt this better to be defined as a nushell command?

**Comment by kubouch** [comment]
@elferherrera Yeah, the Nushell command is `default-prompt` in the example above.

**Comment by elferherrera** [comment]
That should be only a string, no?

**Comment by kubouch** [comment]
@elferherrera Yeah
