### ISSUE TITLE
Add missing `into` conversions

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4302]
Some Values do not have their `into` conversion commands. While not all of them might not need it, we might still look into expanding them.

|Value | `into` | Implemented |
|------ | -------- | -- |
|Bool | `bool` | ☑️ |
|Int | `int` | ☑️ |
|Filesize | `filesize` | ☑️ |
|Duration| | ☑️ |
|Date | `datetime` | ☑️ |
|Range | | |
|Float | `decimal` | ☑️ |
|String | `string` | ☑️ |
|Record | | |
|List | | |
|Block| |  |
|Nothing| | |
|Error | | |
|Binary | `binary` | ☑️ |
|CellPath| | |
|CustomValue | | |

**Comment by kubouch** [comment]
We got `bool` recently but still missing the others. Not all of them might be important.

**Comment by hustcer** [comment]
> Not all of them might be important.

Which `into` commands are important ?

**Comment by fdncred** [comment]
oh, i thought kubouch's list above was sort of a checklist to show which were completed.

we used to have an `into cellpath` with whatever the old name was, but i'm not sure it's as important now since engine-q

**Comment by fdncred** [comment]
oh ya, you're right @hustcer. let's close this then. @kubouch please re-open if you think there are more we should add. i also added a checklist above to be clear.
