### ISSUE TITLE
breaking changes & punch list

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4305]
This is the start of a list of breaking changes between Nushell and engine-q.

# Breaking Changes for Usage

| idx | Nushell v0.44 | Nushell v0.59.1 |
| - | - | - |
| 1 | if { } { } | if { } else { } |
| 2 | str trim -rc (char nl) | str trim -r -c (char nl) |
| 3 | config.toml | config.nu (find location with `$nu.config-path`) |
| 4 | let-env FOO = $nothing | hide $FOO |
| 5 | $nu.home-dir | $nu.home-path |
| 6 | $nu.temp-dir | $nu.temp-path |
| 7 | config commands | $config |
| 8 | `$nu.env` | `$nu.env` is now `$env` |
| 9 | $nu.path | `$env.PATH`/`$env.Path` <- can do more in config.nu |
| 10 | $nu.lang | $scope.commands |
| 11 | str to-int | into int|
| 12 | `$nu.env.PROMPT_COMMAND` is a string | `$env.PROMPT_COMMAND` is a block or a string |
| 13 | get (has auto flatten) | get doesn't auto flatten |
| 14 | to json | to json is formatted as 'pretty' |
| 15 | environment variable is a string | environment variable can be any value |
| 16 |tags | `tags` is now `metadata` |
| 17 | bigint/bigdecimal | engine-q uses machine i64 and f64 |
| 18 | File, Dir in `ls` | file, dir in `ls` |
| 19 | binaryview | binaryview has been removed (it may be an optional plugin in the future) |
| 20 | textview | textview is removed. Install `bat` to view source files, or pipe the output into `less` |
| 21 | dataframe | dfr |
| 22 | shells: `active`, `name`, `path` columns| shells: `active`, `path` columns |
| 23 | `cd` is now scoped  | current directory now comes from `PWD` in `$env`. Changing directory in a block or custom command no longer changes the caller's directory. To do this, return a table that the caller can use to update their env |
| 24 | reduce $acc $it | reduce $it.acc $it.item (temporary, needs parser support) |
| 25 | char branch, char segment| char nf-branch, char nf-segment (`char`s that start with `nf-` are from nerdfont fonts) |
| 26 | `save --append` | We're (hopefully temporarily) removing append as it needs a bit more design before it's ready |
| 27 | wasm supported | wasm support currently not started |
| 28 | `enter <filename>` | engine-q only supports entering directories |
| 29 | str to-decimal | into decimal |
| 30 | 'ff' \| str to-int -r 16 | 'ff' \| into int -r 16 |
| 31 | pivot | renamed to transpose |
| 32 | term size -w -t | term size -c -r |
| 33 | selector | query web |
| 34 | xpath | query xml |
| 35 | config directory name: `nu` | config directory name: `nushell` |
| 36 | `nth 1` | `select 1`, `select` can now down-select rows as well as columns |
| 37 | match | match command is now integrated into the find command |
| 38 | each group | is now `group` |
| 39 | each window | is now `window` |
| 40 | play nes games | can no longer play nes games in terminal :( |
| 41 | empty? -b | missing functionality |
| 42 | wrap | wrap name |
| 43 | hash base64 | can't hash base64 a string with a single quote in it |
| 44 | | |
| 45 | | |
| 46 | | |
| 47 | | |
| 48 | | |
| 49 | | |
| 50 | | |

# Breaking Changes for Commands and Parameters

| idx | breaking changes                              | e-q resolution                                                   | Yes = fix/No = won't fix |
| --- | --------------------------------------------- | ---------------------------------------------------------------- | ------------------------ |
| 1   | `alias` missing parameter `equals`            | `equals` is not a parameter in engine-q                          |    No, e-q parser works differently                      |
| 2   | `alias` missing parameter `rest`              | `rest` renamed to `initial_value`                                |    No, e-q parser works differently                      |
| 3   | `all?` missing parameter `condition`          | `condition` renamed to `predicate`                               |                          |
| 4   | `ansi gradient` missing parameter `rest`      | `rest` renamed to `column path` (\* space in param name)         |                          |
| 4   | `ansi strip` missing parameter `rest`         | `rest` renamed to `column path` (\* space in param name)         |                          |
| 5   | `any?` missing parameter `condition`          | `condition` renamed to `predicate`                               |                          |
| 6   | `append` missing parameter `row value`        | `row value` renamed to `row`                                     |                          |
| 7   | `binaryview` with parameter `bytes`           | removed from engine-q                                            | No                       |
| 8   | `binaryview` with parameter `lores`           | removed from engine-q                                            | No                       |
| 10  | `binaryview` with parameter `skip`            | removed from engine-q                                            | No                       |
| 11  | `cd` missing parameter `directory`            | `directory` renamed to `path`                                    |                          |
| 12  | `compact` missing parameter `rest`            | `rest` renamed to `columns`                                      |                          |
| 13  | `config get` with parameter `get`             | removed from engine-q                                            |      No                    |
| 14  | `config remove` with parameter `remove`       | removed from engine-q                                            |   No                       |
| 15  | `config set` with parameter `key`             | removed from engine-q                                            |      No                    |
| 16  | `config set` with parameter `value`           | removed from engine-q                                            |      No                    |
| 17  | `config set_into` with parameter `set_into`   | removed from engine-q                                            |   No                       |
| 18  | `cp` missing parameter `src`                  | `src` renamed to `source`                                        |                          |
| 19  | `cp` missing parameter `dst`                  | `dst` renamed to `destination`                                   |                          |
| 20  | `dfr aggregate` missing parameter `operation` | `operation` renamed to `operation-name`                          |                          |
| 21  | `dfr cum` with parameter `type`               | `cum` renamed to `cumulative`                                    |                          |
| 22  | `dfr cum` with parameter `reverse`            | `cum` renamed to `cumulative`                                    |                          |
| 23  | `dfr select` with parameter `rows`            | `select` renamed to `get`                                        |                          |
| 24  | `dfr select` with parameter `rest`            | `select` renamed to `get`                                        |                          |
| 25  | `dfr last` missing parameter `n_rows`         | `n_rows` renamed to `rows`                                       |                          |
| 26  | `dfr melt` missing parameter `value_name`     | `value_name` renamed to `value-name`                             |                          |
| 27  | `dfr melt` missing parameter `variable_name`  | `variable_name` renamed to `variable-name`                       |                          |
| 28  | `dfr open` missing parameter `no_header`      | `no_header` reamed to `no-header`                                |                          |
| 29  | `dfr open` missing parameter `infer_schema`   | `infer_schema` renamed to `infer-schema`                         |                          |
| 30  | `dfr open` missing parameter `skip_rows`      | `skip_rows` renamed to `skip-rows`                               |                          |
| 31  | `dfr pivot` missing parameter `pivot column`  | `pivot column` renamed to `pivot-column`                         |                          |
| 32  | `dfr pivot` missing parameter `value column`  | `value column` renamed to `value-column`                         |                          |
| 33  | `dfr sample` missing parameter `n_rows`       | `n_rows` renamed to `n-rows`                                     |                          |
| 34  | `dfr show` with parameter `tail`              | `show` renamed to `to-nu`                                        |                          |
| 35  | `dfr show` with parameter `n_rows`            | `show` renamed to `to-nu`                                        |                          |
| 36  | `dfr to-csv` missing parameter `no_header`    | `no_header` renamed to `no-header`                               |                          |
| 37  | `date format` missing parameter `format`      | `format` renamed to `format string` (\* space in param name)     |                          |
| 38  | `def` missing parameter `name`                | `name` renamed to `def_name`                                     |                          |
| 39  | `drop nth` missing parameter `row number`     | `row number` renamed to `rest`                                   |                          |
| 40  | `empty?` with parameter `rest`                |  | fixed with nushell/engine-q#764                         |
| 41  | `empty?` with parameter `block`               |  | fixed with nushell/engine-q#764                         |
| 42  | `enter` missing parameter `location`          | `location` renamed `path`                                        |                          |
| 43  | `exit` missing parameter `code`               | `code` renamed to `exit-code`                                    |                          |
| 44  | `for` missing parameter `var`                 | `var` renamed to `var_name`                                      |                          |
| 45  | `for` missing parameter `in`                  | `in` is not a parameter in engine-q                              |                          |
| 46  | `for` missing parameter `value`               | `value` renamed to `range`                                       |                          |
| 47  | `g` missing parameter `index`                 | `index` renamed to `shell-number`                                |                          |
| 48  | `if` missing parameter `condition`            | `condition` renamed to `cond`                                    |                          |
| 49  | `if` missing parameter `then_case`            | `then_case` renamed to `then_block`                              |                          |
| 50  | `if` missing parameter `else_case`            | `else_case` renmaed to `else_expression`                         |                          |
| 51  | `insert` with parameter `column`              | `insert` replaced with `update` comand that inserts if missing   |                          |
| 52  | `insert` with parameter `value`               | `insert` replaced with `update` comand that inserts if missing   |                          |
| 53  | `keep` missing parameter `rows`               | `rows` renamed to `n`                                         |                          |
| 54  | `keep until` missing parameter `condition`    | `condition` renamed to `predicate`                            |                          |
| 55  | `keep while` missing parameter `condition`    | `condition` renamed to `predicate`                            |                          |
| 56  | `let` missing parameter `name`                | `name` renamed to `var_name`                                  |                          |
| 57  | `let` missing parameter `equals`              | `equals` is not a parameter in engine-q                          |                          |
| 58  | `let` missing parameter `expr`                | `expr` renamed to `initial_value`                             |                          |
| 59  | `let-env` missing parameter `name`            | `name` renamed to `var_name`                                  |                          |
| 60  | `let-env` missing parameter `equals`          | `equals` is not a parameter in engine-q                          |                          |
| 61  | `let-env` missing parameter `expr`            | `expr` renamed to `initial_value`                             |                          |
| 62  | `ls` missing parameter `path`                 | `path` renamed to `pattern`                                   |                          |
| 63  | `nth` missing parameter `row number`          | `row number` renamed to `rest`                                |                          |
| 64  | `open` missing parameter `path`               | `path` renamed to `filename`                                  |                          |
| 65  | `open` missing parameter `encoding`           | moved `encoding` to `decode` `                                   |                          |
| 66  | `prepend` missing parameter `row value`       | `row value` renamed to `row`                                     |                          |
| 67  | `select` missing parameter `columns`          | `columns` renamed to `rest`                                      |                          |
| 68  | `skip` missing parameter `rows`               | `rows` renamed to `n`                                            |                          |
| 69  | `skip until` missing parameter `condition`    | `condition` renamed to `predicate`                               |                          |
| 70  | `skip while` missing parameter `condition`    | `condition` renamed to `predicate`                               |                          |
| 71  | `str to-datetime` with parameter `rest`       | `str to-datetime` replaced with `into datetime`                                   |                          |
| 72  | `str to-datetime` with parameter `format`     | `str to-datetime` replaced with `into datetime`                                   |                          |
| 73  | `str to-datetime` with parameter `timezone`   | `str to-datetime` replaced with `into datetime`                                   |                          |
| 74  | `str to-datetime` with parameter `offset`     | `str to-datetime` replaced with `into datetime`                                   |                          |
| 75  | `str to-decimal` with parameter `rest`        | `str to-datetime` replaced with `into decimal`                                    |                          |
| 76  | `str to-int` with parameter `rest`            | `str to-int` replaced with `into int`                                        |                          |
| 77  | `str to-int` with parameter `radix`           | `str to-int` replaced with `into int`                                        |                          |
| 78  | `to json` missing parameter `pretty`          | `pretty` missing because it defaults to pretty                   |                          |
| 79  | `where` missing parameter `condition`         | `condition` renamed to `cond`                                 |                          |
| 80  | `wrap` missing parameter `column`             | `column` renamed to `name`                                    |                          |
| 81  | `zip` missing parameter `block`               | `block` renamed to `other`                                    |                          |

## Punch List

This is a punch list of things that need to be added/fixed to existing functionality.

- [x] the `-i` part of `do -i`
- [x] the `-al` part of `ls -al`
- [x] the `-n` part of `table -n`
- [x] the `-n` part of `each -n`
- [x] the `-n` part of `for -n`
- [x] the `-` part of `cd -`
- [x] syntax highlighting in Examples of `--help`
- [x] piped input to a custom command (def)
- [x] `open Cargo.lock | into binary | skip 10 | first 25` -> pretty hex
- [x] some thing

## Just Different

* Update config settings in real time without having to exit and relaunch nushell. `let $config = ($config | update edit_mode vi)`

### `main` command in scripts
If the script contains `main` it will be ran after all the script is executed. It also accepts arguments from the command line. You can run it like this: `nu foo.nu arg1 --flag` and if the script contains a hashbang/shebang line (`#!/usr/bin/env nu`): `./foo.nu arg1 --flag`.

**Comment by fdncred** [comment]
> Why specifically is `dir` being changed to `path` in some places, but not others? That seems like an erroneous change that does nothing but create a strange inconsistency to me.

we were trying to standardize. it would be helpful for you to point out where it's not standarized.

**Comment by hyiltiz** [comment]
Any way to get some of the goodies back, such as `textview/bat`, `binaryview` and being able to 😏play NES games😏?

**Comment by fdncred** [comment]
@hyiltiz `textview/bat` probably not. `binaryview` kind of already exists under a different name. You can do `some file | into binary`. Maybe someday we'll bring back NES emulation.

**Comment by jntrnr** [comment]
Seems like the list has settled down now. I'll go ahead and close this, but if we're missing items we haven't finished, please file issues for them.
