### ISSUE TITLE
Better way of detecting environment variable existence

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4307]
In scripts, you often check for a value of an env var like this:
```
> if $env.FOO {
    blah
} else {
    bob
}
```

However, if `$env.FOO` does not exist, it will throw an error. To make it safe, you would need to check it like this:
```
> if ("FOO" in (env).name) {
    if $env.FOO {
        blah
    } else {
        bob
    }
}
```
which is quite wordy.

One way to make this more ergonomic would be nushell/nushell#4310.

Another one would be to bring back `$nothing` erasing the env var and augment `env` to accept arguments. So `env FOO` would either give you the value or `$nothing` if not found.

**Comment by kubouch** [comment]
@jntrnr I wouldn't be opposed to having the `?.`, even if it would result in `$nothing` conflating. It would be a clear improvement over the current state.

**Comment by kubouch** [comment]
@zoechi Try `is-empty`

**Comment by jntrnr** [comment]
We now allow the `?` to say a field is optional.

```
> $env.FOO
Error: nu::shell::column_not_found

  × Cannot find column
   ╭─[entry #197:1:1]
 1 │ $env.FOO
   · ──┬─ ─┬─
   ·   │   ╰── cannot find column 'FOO'
   ·   ╰── value originates here
   ╰────

> $env.FOO?
```
