### ISSUE TITLE
Plugins should stream their input

### ISSUE THREAD

**Issue by sophiajt** [nushell/nushell#4308]
I was just looking at some plugin code and noticed:

```
        let input = match input {
            PipelineData::Value(value, ..) => value,
            PipelineData::ListStream(stream, ..) => {
                let values = stream.collect::<Vec<Value>>();

                Value::List {
                    vals: values,
                    span: call.head,
                }
            }
            
        };
```

Ideally, plugins would work with streams of input also, so that they can pull on the input they need rather than doing a full collection before the plugin runs.

**Comment by IanManske** [comment]
Plugins now stream thanks to @devyn :tada:

**Comment by devyn** [comment]
> I imagine that we would need to spawn a thread that is feeding each value to stdout from nushell and the plugin reads then one at the time. I'm wondering how do you tell the spawned process that you may want to stop receiving so it can stop sending data

Yeah, I ended up doing basically all of this. If you're curious about it, you can have a look at [`crates/nu-plugin-core/src/interface/stream/mod.rs`](https://github.com/nushell/nushell/blob/main/crates/nu-plugin-core/src/interface/stream/mod.rs). We're basically multiplexing the same connection between many streams with locally unique IDs, and there are four messages: `Data`, `Ack`, `Drop`, `End` (it's almost like TCP!). `End` is sent by the producer when they're done sending messages for the stream and it can be deregistered, and `Drop` is sent by the consumer when they're no longer interested in messages and so the producer can stop sending.

**Comment by elferherrera** [comment]
@devyn
Thanks a lot for the ping. I've been following closely how you are improving the plugin system. 

One thing that I haven't figured out is how does nushell knows to what plugin it needs to send data to. Example, say you have two plugins that stay alive (e.g. polars and plugin-x). Both plugins have different commands and have been registered in nu. My question is, how does nu know what stream belongs to each plugin? 
do you have a map somewhere in nu that has a relationship of the commands/plugins and streams?

**Comment by devyn** [comment]
No, we don't have any need for centralized management of plugins, there's basically just a `PluginInterfaceManager` that handles that for each plugin independently, each containing their own `StreamManager`. When a plugin is running, a handle to that exists within `PersistentPlugin`. There is a dedicated thread for each running plugin to read messages coming in from the plugin, and when it reads stream messages it basically just sends them to the right channel - the underlying streams from a plugin just contain a `mpsc::Receiver`.
