### ISSUE TITLE
Command tests to be finished

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#4314]
Following on from nushell/engine-q#922, here are the command tests that still need work. Before I list them, let's also list some of the kinds of issues you might need to fix in these tests:
 - Error text not being the same. In this case, fix the test
 - Commands not yet implemented. You'll need to implement the command, then re-enable the test.
 - Tests that use single tick `'` in the test. Because of how the e-q test harness works, this can cause an issue. There may be similar issue with tests that expect to have newlines in strings. For the single tick, change the test to use double quotes `"` instead, if possible.
 - Differences in `nth` and `get`. In engine-q, we can tell the difference between `echo 1` and `echo [1]`. This means you'll sometimes need to update a test that uses `nth` to use `get` instead (nth gets the outer row, get gets the inner value).
 - Missing errors. In this case, you'll need to update the command with some additional logic in places that should error but currently aren't.
 - Logic differences. Same idea, you'll need to update the command to have the correct logic.
 - Differences in output format. There are a few places that the tests expects `10.0` and we currently output `10`. These are roughly equivalent, and I've personally just been updating the test to reflect the more up-to-date output format.

how-to's:
 - how-to find the test example. search for the last part like `cal_february_2020_leap_year`
 - how-to test only a single test. in vscode click the `Run test` marker about the test. without vscode you can try something like `cargo test --package nu-command --test main -- commands::cal::cal_sees_pipeline_year --exact --nocapture`
 - how-to understand test output. once you run a test, if it uses `assert_eq`, it will list the `left` output and the `right` output if there are errors. this usually maps to expected output compared to actual output. so, the left needs to match the right, that's part of what you're fixing.
 - when you're done, and the test is working, make sure you remove any `FIXME` comments and `#[ignore]` above the test.
 - if you have questions about whether to fix the test or fix the command, come to the `#engine-q` channel on discord and ask about it.

The tests:
 - [x] commands::cal::cal_february_2020_leap_year
 - [x] commands::cal::cal_full_year
 - [x] commands::cal::cal_sees_pipeline_year
 - [x] commands::cal::cal_week_day_start_monday
 - [x] commands::cp::deep_copies_with_recursive_flag
 - [x] commands::cp::error_if_attempting_to_copy_a_directory_to_another_directory
 - [x] commands::def::def_with_comment
 - [x] commands::drop::columns 
 - [x] commands::drop::more_columns_than_table_has - (empty? not returning anything when results are in fact empty)
 - [x] commands::each::each_group_works
 - [x] commands::each::each_no_args_in_block
 - [x] commands::each::each_window
 - [x] commands::each::each_window_stride
 - [x] commands::each::each_works_separately
 - [x] ~~commands::empty::passing_a_block_will_set_contents_on_empty_cells_and_leave_non_empty_ones_untouched - (empty -b changing all other values to $true)~~ removed
 - [x] ~~commands::empty::reports_emptiness - (missing wrap functionality)~~ removed
 - [x] ~~commands::empty::sets_block_run_value_for_an_empty_column - (empty -b changing all other values to $true)~~ removed
 - [x] ~~commands::empty::sets_block_run_value_for_many_empty_columns - (missing wrap functionality)~~ removed
 - [x] commands::every::gets_no_rows_by_every_skip_one
 - [x] commands::find::find_with_filepath_search_with_multiple_patterns
 - [x] commands::find::find_with_filepath_search_with_string
 - [x] commands::find::find_with_list_search_with_char
 - [x] commands::flatten::flatten_nested_tables_that_have_many_columns
 - [x] commands::flatten::flatten_nested_tables_with_columns
 - [x] commands::flatten::flatten_row_columns_having_same_column_names_flats_separately - (don't think flatten is working right here)
 - [x] commands::flatten::flatten_table_columns_explicitly - (flatten is working differently here too)
 - [x] commands::format::can_use_variables - (don't think format understands records)
 - [x] commands::format::format_filesize_works - (format filesize isn't a subcommand yet)
 - [x] commands::format::format_filesize_works_with_nonempty_files - (format filesize isn't a subcommand yet)
 - [x] commands::format::given_fields_can_be_column_paths - (don't think format understands records)
 - [x] commands::get::errors_fetching_by_column_not_present
 - [x] commands::get::errors_fetching_by_column_using_a_number
 - [x] commands::get::errors_fetching_by_index_out_of_bounds
 - [x] commands::group_by::errors_if_block_given_evaluates_more_than_one_row
 - [x] commands::hash_::base64_decode_characterset_binhex - (single quote inside of double quote problem)
 - [x] commands::hash_::error_when_invalid_character_set_given - (nu!() doesn't appear to be capturing the actual.err)
 - [x] commands::hash_::md5_works_with_file
 - [x] commands::hash_::sha256_works_with_file
 - [x] commands::headers::headers_adds_missing_column_name
 - [x] commands::headers::headers_uses_first_row_as_header
 - [x] ~~commands::help::help_generate_docs_length - (generate_docs is not a subcommand of help yet)~~ removed
 - [x] commands::histogram::count - (histogram command doesn't exist yet)
 - [x] commands::histogram::summarizes_by_column_given - (histogram command doesn't exist yet)
 - [x] commands::histogram::summarizes_by_values - (histogram command doesn't exist yet)
 - [x] commands::into_filesize::into_filesize_str_many_newlines
 - [x] commands::into_filesize::into_filesize_str_newline
 - [x] commands::lines::lines_multi_value_split
 - [x] commands::lines::lines_proper_buffering
 - [x] commands::ls::fails_when_glob_doesnt_match
 - [x] commands::ls::list_all_columns
 - [x] commands::ls::lists_all_files_in_directories_from_stream
 - [x] commands::math::avg::can_average_bytes
 - [x] commands::math::compound_where
 - [x] commands::math::compound_where_paren
 - [x] commands::math::eval::evaluates_three_multiplied_by_five
 - [x] commands::math::eval::evaluates_twenty_four_divided_by_two
 - [x] commands::math::eval::evaluates_two_plus_two
 - [x] commands::math::eval::evaluates_two_to_the_power_four
 - [x] commands::math::sqrt::can_sqrt_irrational
 - [x] commands::math::sqrt::can_sqrt_numbers
 - [x] commands::math::sum::sum_of_a_row_containing_a_table_is_an_error
 - [x] commands::merge::row - (merge doesn't appear to work this way any longer)
 - [x] commands::move_::column::moves_a_column_after - (get | trim | collect is collecting records instead of values)
 - [x] commands::move_::column::moves_columns_after
 - [x] commands::move_::column::moves_columns_before - (get | trim | collect is collecting records instead of values)
 - [x] commands::move_::mv::errors_if_destination_doesnt_exist
 - [x] commands::move_::mv::errors_if_moving_to_itself
 - [x] commands::move_::mv::errors_if_multiple_sources_but_destination_not_a_directory
 - [x] commands::move_::mv::errors_if_renaming_directory_to_an_existing_file
 - [x] commands::move_::mv::errors_if_source_doesnt_exist
 - [x] commands::open::errors_if_file_not_found
 - [x] commands::open::parses_xml
 - [x] commands::parse::simple::errors_when_missing_closing_brace
 - [x] commands::parse::simple::extracts_fields_from_the_given_the_pattern
 - [x] commands::path::exists::checks_if_existing_file_exists
 - [x] commands::path::parse::parses_into_correct_number_of_columns
 - [x] commands::path::split::splits_correctly_single_path
 - [x] commands::path::split::splits_correctly_with_column_path
 - [x] commands::path::type_::returns_type_of_existing_directory
 - [x] commands::path::type_::returns_type_of_existing_file
 - [x] commands::random::decimal::generates_0
 - [x] commands::random::decimal::generates_55
 - [x] commands::random::decimal::generates_an_decimal
 - [x] commands::reduce::folding_with_tables
 - [x] commands::reduce::reduce_numbered_example - (i think reduce is broken here)
 - [x] commands::reduce::reduce_numbered_integer_addition_example
 - [x] commands::reduce::reduce_table_column
 - [x] commands::reduce::reduce_table_column_with_path
 - [x] commands::rename::errors_if_no_columns_present - (silent failure with renaming a column that doesn't exist)
 - [x] commands::rm::errors_if_attempting_to_delete_a_directory_with_content_without_recursive_flag
 - [x] commands::rm::errors_if_attempting_to_delete_single_dot_as_argument
 - [x] commands::rm::errors_if_attempting_to_delete_two_dot_as_argument
 - [x] commands::rm::rm_wildcard_keeps_dotfiles
 - [x] commands::roll::columns::can_roll_in_the_opposite_direction
 - [x] commands::roll::columns::can_roll_the_cells_only_keeping_the_header_names
 - [x] commands::roll::columns::four_in_bitstring_left_shifted_with_three_bits_should_be_32_in_decimal
 - [x] commands::roll::columns::roll_left_by_default
 - [x] commands::roll::rows::can_roll_up
 - [x] commands::roll::rows::roll_down_by_default
 - [x] commands::rotate::counter_clockwise
 - [x] commands::save::save_append_will_create_file_if_not_exists - (append subcommand/parameter of save doesn't exist yet)
 - [x] commands::select::allows_if_given_unknown_column_name_is_missing - ( select doesn't insert a column if missing, just errors)
 - [x] commands::select::complex_nested_columns - (commands working different + duplication bug)
 - [x] commands::select::ignores_duplicate_columns_selected
 - [x] commands::sort_by::by_invalid_column
 - [x] commands::sort_by::by_invalid_types - (no idea why this doesn't work)
 - [x] commands::sort_by::ls_sort_by_name_insensitive
 - [x] commands::sort_by::ls_sort_by_name_sensitive
 - [x] commands::sort_by::ls_sort_by_type_name_insensitive
 - [x] commands::sort_by::ls_sort_by_type_name_sensitive
 - [x] commands::source::sources_unicode_file_in_normal_dir
 - [x] commands::source::sources_unicode_file_in_unicode_dir_with_spaces_1 - (seems like unicode is throwing it off but the below tests passed)
 - [x] commands::source::sources_unicode_file_in_unicode_dir_with_spaces_2 - (seems like unicode is throwing it off but the below tests passed)
 - [x] commands::source::sources_unicode_file_in_unicode_dir_without_spaces_1
 - [x] commands::source::sources_unicode_file_in_unicode_dir_without_spaces_2
 - [x] commands::uniq::nested_json_structures - (uniq doesn't appear to work on structures any longer)
 - [x] commands::uniq::uniq_counting
 - [x] commands::uniq::uniq_when_keys_out_of_order - (uniq doesn't appear to work on structures any longer)
 - [x] commands::with_env::with_env_hides_variables_in_parent_scope
 - [x] commands::with_env::with_env_shorthand_nested_quotes
 - [x] commands::zips_two_tables - (zip appears to be creating a block in a table in error)

**Comment by hustcer** [comment]
How to run a specific test? say `commands::flatten::flatten_table_columns_explicitly`

**Comment by efx** [comment]
PSA: I noticed you need to run `cargo test` *before* filtering on individual test suites.

Otherwise you'd see an error like below:
```console
~/f/nushell (main↑183|✚1) $ cargo test --package nu-command --test main -- commands::flatten::flatten_row_column_explicitly --exact --nocapture
    Finished test [unoptimized + debuginfo] target(s) in 0.76s
     Running tests/main.rs (target/debug/deps/main-ad25c68a3c49275c)

running 1 test
thread 'commands::flatten::flatten_row_column_explicitly' panicked at 'Can't run test "nushell/target/debug/nu" No such file or directory (os error 2)', crates/nu-command/tests/commands/flatten.rs:72:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test commands::flatten::flatten_row_column_explicitly ... FAILED
````

**Comment by herlon214** [comment]
I checked here `commands::format::format_filesize_works` is already passing, should we update the list?

**Comment by onthebridgetonowhere** [comment]
@jntrnr - these seems to have been added. Shall we close this issue?
