### ISSUE TITLE
Weird conversion of string to table

### ISSUE THREAD

**Issue by archaeron** [nushell/nushell#4318]
hi

I just tried to port a nushell script to engine-q and noticed something weird

![image](https://user-images.githubusercontent.com/471043/152155397-7dec3583-bb98-4a93-b560-24125a0f6d3c.png)

I don't understand why `str trim` would convert a string to a table here

this is with the version from the `main` branch at `cbdc0e2010852c7dff93a8eb645e8c54aa62a1d8`  (1. Feb)

**Comment by archaeron** [comment]
@jntrnr awesome, thank you! should I test this in nushell now? or engine-q? :)

**Comment by jntrnr** [comment]
The fix should be in engine-q now. It'll also show up in nushell main after the merge tomorrow (which will happen after tomorrow's nushell release)

**Comment by archaeron** [comment]
@jntrnr I tried it in engine-q and it looks great! also the nushell script I had is simpler now :)
I'm really looking forward to the merge! thanks for nushell
