### ISSUE TITLE
Highlighting matching brackets / parentheses

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4325]
This might be more a reedline feature request. A cool thing would be to highlight a matching paren / brace / bracket when the cursor is on one.

**Comment by vmiheer** [comment]
I was just trying to brainstorm how to implement it. I think I agree with @kubouch that it could be a reedline improvement. Seems like that would imply change to https://docs.rs/reedline/latest/reedline/trait.Highlighter.html trait where in addition to string, it will also take `Option<cursorposition: u32>` as context to determine if current character entails highlighting this and some other character.
But given that @jntrnr has moved in here, he might have better idea.

**Comment by kubouch** [comment]
> I was just trying to brainstorm how to implement it. I think I agree with @kubouch that it could be a reedline improvement. Seems like that would imply change to https://docs.rs/reedline/latest/reedline/trait.Highlighter.html trait where in addition to string, it will also take `Option<cursorposition: u32>` as context to determine if current character entails highlighting this and some other character. But given that @jntrnr has moved in here, he might have better idea.

I don't really work on the line editor but if you want to discuss it further, the best way would be to hit the reedline channel on our Discord and hopefully @sholderbach or @elferherrera would be able to help.

**Comment by sholderbach** [comment]
@vmiheer Providing the cursor position with the trait sounds good. 
If the highlighting of the matching brace should be static the actual brace matching logic could then live inside the existing `Highlighter`. 
If the brace highlighting should be a transient animation this would probably require some more heavy lifting on the reedline side.

**Comment by sholderbach** [comment]
@vmiheer If you want to give it a go, we now use an updated `Highlighter` API since #4657
