### ISSUE TITLE
Passing a negative argument to `nth` or `every` doesn't error

### ISSUE THREAD

**Issue by Pantonshire** [nushell/nushell#4333]
In Nushell, passing a negative argument to `nth` or `every` gives a range error. In engine-q, negative arguments to these commands are cast to `usize` by `usize`'s implementation of `FromValue` instead of giving an error. For example, on 64-bit targets, `nth -1` will get the 18446744073709551616th row of the input.

I think it would probably make more sense for these commands to error when a negative argument is provided.

**Comment by fdncred** [comment]
`nth` doesn't exist any longer
`every -1` fails with an error
`select -1` fails with an error
`get -1` fails with an error

I'm thinking we're covered here now.

**Comment by fdncred** [comment]
`nth` doesn't exist any longer
`every -1` fails with an error
`select -1` fails with an error
`get -1` fails with an error

I'm thinking we're covered here now.
