### ISSUE TITLE
Improve how env conversions are done in config

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4339]
When reading config.nu, the captured environment variables are Strings (Value::Strings, technically) because you first need the `$config` variable to perform the conversion to arbitrary Values. This makes it a kind of chicken-and-egg problem when defining variables like PATH together with their conversions together in their config.

For example, when PATH is defined as a list in the config, it seems to fail because the subsequent String->Value conversion will fail silently (the PATH is a Value::List already, not Value::String). Maybe all we need is to add better error reporting at this stage.

**Comment by fdncred** [comment]
@kubouch should this be closed in light of #4748 - or is this different?

**Comment by kubouch** [comment]
It's a bit different, but I already described this in the docs and I don't have problems defining PATH anymore. We can open a new issue if there are problems in the future.
