### ISSUE TITLE
Bare tokens should allow +

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#434]
Nu doesn't currently allow you to pass a + where you're passing a bare token. This should be allowed, as in the case of passing +nightly to cargo.

**Comment by wycats** [comment]
I wonder whether problems like this will eventually require us to parse external commands differently.

**Comment by jonathandturner** [comment]
@wycats - I think the bare token would stay the most general, but we would have another stage of parsing that internal commands use that would further parse the bare tokens.

**Comment by wycats** [comment]
We currently treat bare tokens and external words differently. I'll look into why external commands don't support these characters.

**Comment by jonathandturner** [comment]
after #1046 and #1047 this should be fixed.
