### ISSUE TITLE
prints blank rows when else loop is commented out

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4341]
I'm puzzled because I've had to remove all my `(char nl)` commands in an effort to stop double printing new lines. I'm also getting extra new lines on a loop iteration that I'm not sure where they're coming from. with this snippet below it's as if the else loop is just printing a new line and nothing else when it's commented out. when it's not commented out, it prints as it should.

```
let param_missing_in_eq = ($eq_param | to json | str length)
if $param_missing_in_eq == 2 {
    $"missing: command [($cmd)] exists but parameter [($param_name)] is missing in eq"
} 
# else {
#     $"found: command [($cmd)] found param type [($x.parameter_type)]"
# }
```

_Originally posted by @fdncred in https://github.com/nushell/engine-q/issues/739#issuecomment-1013540683_

**Comment by lukexor** [comment]
If it helps, here's an easy to reproduce example:

```
[11:14] v0.59.0 ❯ ls | each { $it | save files }
╭────┬──╮
│  0 │  │
│  1 │  │
│  2 │  │
│  3 │  │
│  4 │  │
│  5 │  │
│  6 │  │
│  7 │  │
│  8 │  │
│  9 │  │
│ 10 │  │
│ 11 │  │
│ 12 │  │
│ 13 │  │
│ 14 │  │
│ 15 │  │
│ 16 │  │
│ 17 │  │
╰────┴──╯
```

**Comment by jntrnr** [comment]
We can fix this if we do the same fix to `each` we just did to `for`, namely: automatically filter out any `$nothing` from the stream.

**Comment by fdncred** [comment]
yes, please
