### ISSUE TITLE
How to transpose rows into (named) columns

### ISSUE THREAD

**Issue by dbarnett** [nushell/nushell#435]
If I have an array or single column of data, like
```
---+---------
 # | value 
---+---------
 0 | Octavia 
 1 | Butler
```
is there a simple way to transpose the data so each row's value gets its own column?
```
---+------------+-----------
 # | first_name | last_name
---+------------+-----------
 0 | Octavia    | Butler
```

**Comment by jonathandturner** [comment]
Does `vtable` do what you need by chance?

It admittedly needs a better name

**Comment by jonathandturner** [comment]
Oh I see what you mean, it's a bit more than just a visual pivot

**Comment by dbarnett** [comment]
Yeah, I thought vtable might do what I wanted from the description, but I couldn't get it to do anything useful. Could use an example of what it does in the docs.
