### ISSUE TITLE
Path autocompletion does not work with `use` argument

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4352]
The argument of `use` has the import pattern syntax shape:
```
use file.nu [ a b c ]
    ^^^^^^^   ^ ^ ^
     head     members
```

I would like to tab-complete the file.nu. Currently, the head is set to a String flat shape. However, even setting it to a Filepath does not help.

The issue is present even after applying this PR: https://github.com/nushell/engine-q/pull/705

**Comment by sholderbach** [comment]
This now works
