### ISSUE TITLE
`module` command should be parsed as a call in the parser

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4358]
Currently, `module -h` does not work because it uses the old parsing style.

However, parsing it as a call has the difficulty that the block (2nd argument of `module`) is not a regular block but a module block with a special syntax. We would need to add a SyntaxShape for it and maybe even a special Value::ModuleBlock (which could hold the Overlay struct we already have). So this has potentially far-reaching consequences.

**Comment by jntrnr** [comment]
This is working in the latest main.
