### ISSUE TITLE
Make pick support column paths

### ISSUE THREAD

**Issue by dbarnett** [nushell/nushell#436]
I can pass dotted column paths as arguments to `get`, but `pick` doesn't seem to accept anything but literal column names. Could it?
> open Cargo.toml | get lib.name package.version
For example, I can use `get` to pull out nested values from a table:
```
> open Cargo.toml | get lib.name package.version
---+-------
 # | value 
---+-------
 0 | nu 
 1 | 0.2.0 
---+-------
```
but if I try the equivalent with `pick`:
```
> open Cargo.toml | pick lib.name package.version
```
instead of seeing the values I'm selecting for as I expect:
```
----------+-----------------
 lib.name | package.version 
----------+-----------------
 nu       | 0.2.0
----------+-----------------
```
I see an empty table as if those column names don't exist:
```
----------+-----------------
 lib.name | package.version 
----------+-----------------
          |  
----------+-----------------
```

Is there a reason pick couldn't handle dotted column paths?

**Comment by wycats** [comment]
We could definitely support this. This comes up a bunch and could use a dedicated facility.

**Comment by dbarnett** [comment]
Cool, then I'd like to take a stab at fixing this if you want to assign it to me.

**Comment by jonathandturner** [comment]
@dbarnett - I missed this comment, but looks like it's still available to be fixed if you want to give it a go

**Comment by dbarnett** [comment]
Thanks, I still might but not sure how soon. Feel free to take it over in the meantime. Or even better, if you wouldn't mind walking me through some of the code changes it'll need, that could help me get familiar with the code overall.

**Comment by jonathandturner** [comment]
This should now work in recent versions versions of Nu.
