### ISSUE TITLE
Parsing units has a rounding error?

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#4360]
```
> 95.4KiB
95.5 KiB
```

**Comment by fdncred** [comment]
i'm thinking this looks better
```
> 95.4KiB 
97.8 KB
```

**Comment by fdncred** [comment]
to reproduce this, you have to have your filesize_format set to kib in your config.
`let config = ($config | update filesize_format kib)`

this still exists in 0.59.1

**Comment by fdncred** [comment]
to reproduce this, you have to have your filesize_format set to kib in your config.
`let config = ($config | update filesize_format kib)`

this still exists in 0.59.1

**Comment by jntrnr** [comment]
This appears to be fixed now:

```
> 95.4KiB
95.4 KiB
```
