### ISSUE TITLE
Add ability to view table headers

### ISSUE THREAD

**Issue by dradtke** [nushell/nushell#4362]
### Describe the solution you'd like

When working with a large CSV file, it's hard to see what headers are available for use with commands like `select`. I see that there is a `headers` function, but that forces the table to be interpreted with the first line as headers, and isn't helpful for displaying what the headers are.

Basically, I want `xsv headers` ported to Nushell.

### Describe alternatives you've considered

`open file.csv | first 1` is the best I can come up with currently, but it truncates the list of columns when it's too long for the terminal.

**Comment by fdncred** [comment]
closing since `columns` answers this question. please reopen if you disagree.
