### ISSUE TITLE
split: undocumented "\n" substitution

### ISSUE THREAD

**Issue by panicbit** [nushell/nushell#4363]
The builtin `split row` and `split column` replace occurrences of `\n` with a newline:

https://github.com/nushell/nushell/blob/265ee1281d810a569c7daddd02031f5c6991699e/crates/nu-command/src/commands/strings/split/row.rs#L41
https://github.com/nushell/nushell/blob/265ee1281d810a569c7daddd02031f5c6991699e/crates/nu-command/src/commands/strings/split/column.rs#L51

However, this behaviour is neither documented, nor does the implementation allow you to escape this substitution.
Ontop of that, allowing this substitution only in this command feels to me like this is gonna be a pitfall.

**Comment by panicbit** [comment]
Sorry, I opened this thinking engine-q was already merged. It doesn't look like engine-q does this. Gonna close this 😄

**Comment by panicbit** [comment]
Nvm, still valid 😅 https://github.com/nushell/engine-q/blob/9259a56a28f1dd3a4b720ad815aa19c6eaf6adce/crates/nu-command/src/strings/split/column.rs#L72

**Comment by dev-msp** [comment]
FYI - this was fixed in #4731.

**Comment by fdncred** [comment]
nice! - closing.
