### ISSUE TITLE
`source` does not work in alias

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4366]
### Describe the bug

Seems like `source` invoked via an alias does not work.

I know we banned `source` to be used in pipelines so you cannot do `cd dir; source file.nu` which would fail but maybe it could be relaxed a bit to allow simple sourcing alias (see example)

### How to reproduce

```
> alias foo = source foo.nu

> foo
Error: nu::parser::unexpected_keyword (https://docs.rs/nu-parser/0.1.0/nu-parser/enum.ParseError.html#variant.StatementInPipeline)

  × Statement used in pipeline.
   ╭─[entry #4:1:1]
 1 │ alias foo = source foo.nu
   ·             ───┬──
   ·                ╰── not allowed in pipeline
   ╰────
  help: 'source' keyword is not allowed in pipeline. Use 'source' by itself, outside of a pipeline.
```

### Expected behavior

Being able to source within alias.

It would be useful to define, e.g. `alias reload-config = source ~/.config/nushell/config.nu` so you don't have to type it every time.

### Configuration

Latest engine-q

```
  version              0.1.0
  branch               main
  short_commit         fefd5fef
  commit_hash          fefd5fef12702e40911dffd7bc7b198045b2ff1a
  commit_date          2022-02-04 18:02:03 +00:00
  build_os             linux-x86_64
  rust_version         rustc 1.58.1 (db9d1b20b 2022-01-20)
  rust_channel         stable-x86_64-unknown-linux-gnu
  cargo_version        cargo 1.58.0 (f01b232bc 2022-01-19)
  pkg_version          0.1.0
  build_time           2022-02-04 20:05:09 +02:00
  build_rust_channel   release
  features             dataframe, default, which, zip
  installed_plugins    gstat
```

**Comment by skelly37** [comment]
Works flawlessly on newest nu 0.44, requires rewriting instead of developing from zero, just a tip.

**Comment by kubouch** [comment]
A simple workaround is `alias foo = (source foo.nu)`.

**Comment by kubouch** [comment]
The workaround has the following issue though: https://github.com/nushell/nushell/issues/4822

**Comment by kubouch** [comment]
This works now
