### ISSUE TITLE
`pivot` is missing

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4367]
### Describe the bug

Based on https://github.com/nushell/nushell/issues/4356 `pivot` seems to be ported but I can't run it. Maybe it's missing from the default context?

### How to reproduce

1. `pivot # error, can't run executable`

### Expected behavior

`pivot` should work since we have ask people to run it in the issue template.

### Configuration

```
  version              0.1.0
  branch               main
  short_commit         9259a56a
  commit_hash          9259a56a28f1dd3a4b720ad815aa19c6eaf6adce
  commit_date          2022-02-07 13:22:31 +00:00
  build_os             linux-x86_64
  rust_version         rustc 1.58.1 (db9d1b20b 2022-01-20)
  rust_channel         stable-x86_64-unknown-linux-gnu
  cargo_version        cargo 1.58.0 (f01b232bc 2022-01-19)
  pkg_version          0.1.0
  build_time           2022-02-08 11:48:59 +02:00
  build_rust_channel   release
  features             dataframe, default, which, zip
  installed_plugins    gstat
```

**Comment by jntrnr** [comment]
@kubouch - we'll need to update the issue template. engine-q uses `transpose` instead of `pivot`

**Comment by hustcer** [comment]
@jntrnr How about `query json`? Can not find this command in `engine-q` either

**Comment by jntrnr** [comment]
@hustcer - it's in the plugins. You'll need to register `nu_plugin_query`
