### ISSUE TITLE
group-by date crashes nushell

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4369]
### Describe the bug

type `group-by date` and hit enter. it crashes nushell like this
```
group-by date
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', crates\nu-command\src\filters\group_by.rs:98:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `C:\CarTar\debug\nu.exe` (exit code: 101)
```

`group-by date` doesn't exist yet but it still shouldn't crash.

### How to reproduce

1. type `group-by date` and hit enter

### Expected behavior

give some error message

### Configuration

|key|value|
|-|-|
|version|0.59.0|
|branch|main|
|short_commit|7242e52f|
|commit_hash|7242e52faac350a71a62c1ccb723ab64a2c6f656|
|commit_date|2022-02-08 15:02:28 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.58.1 (db9d1b20b 2022-01-20)|
|rust_channel|stable-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.58.0 (f01b232bc 2022-01-19)|
|pkg_version|0.59.0|
|build_time|2022-02-08 09:06:14 -06:00|
|build_rust_channel|debug|
|features|dataframe, default, which, zip|
|installed_plugins|gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml|

**Comment by jntrnr** [comment]
Yeah. I was thinking about it after you mentioned it. I think `group-by date` isn't well-formed because you only use subcommand names that don't conflict with parameters. We should have maybe caught that in nushell before it landed.

We could add a flag or something to `group-by`, maybe `group-by --date` or something.

**Comment by fdncred** [comment]
ya, i just want to be able to group-by date with a format, which assumes the column is a nushell date type. i also noticed that even the example doesn't work in `group-by date`. It must be returning a `None` in the example code.

```
Examples:
  Group files by type
  > ls | group-by date --format '%d/%m/%Y'
```

but this works - i mean i guess this is what it's supposed to do.
```
ls | group-by date modified --format '%d/%m/%Y'
╭───┬────────────────┬────────────────┬────────────────┬────────────────┬────────────────╮
│ # │ 08/02/2022     │ 12/04/2021     │ 15/04/2021     │ 08/10/2021     │ 07/02/2022     │
├───┼────────────────┼────────────────┼────────────────┼────────────────┼────────────────┤
│ 0 │ [table 7 rows] │ [table 9 rows] │ [table 1 rows] │ [table 4 rows] │ [table 1 rows] │
╰───┴────────────────┴────────────────┴────────────────┴────────────────┴────────────────╯
```

**Comment by fdncred** [comment]
closing - doesn't crash anymore.
