### ISSUE TITLE
Come up with a way to optimize pipelines

### ISSUE THREAD

**Issue by pmeredit** [nushell/nushell#437]
There is a lot of room for pipeline optimization if we provide a way to move stages (such as nth, skip, or filters) into a query optimizer such that we can translate the pipeline stages into native queries for datasources. As a concrete example, when querying a SQLite database, we could turn a filter stage into a where clause that will be able to make use of SQLite indexes.

I have some code for converting Mongo Aggregation to SQL that we can use as an example, but the bigger design issue here is providing a nice extensible framework for “slurping” pipeline stages into an optimizer.

As a stretch goal, it would be interesting to provide an API that could provide a user the ability to optimize user created “stages” (programs) for different data source formats. Otherwise, for any stage that is opaque to nushell will have to be the point at which the optimizer stops, leaving subsequent stages to be interpreted in memory by nushell itself.

**Comment by wycats** [comment]
I think it's a great idea to eventually do some optimization and planning, especially against the basic streamy commands.

It would make a lot of sense to take a close look at it when we have enough real-world usage to see what patterns to prioritize. In the meantime, let's collect up approaches that people have used (query optimization, loop fusion, inlining in PLs).
