### ISSUE TITLE
output on the command line is different than in a script

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4376]
### Describe the bug

this may be debateable whether this is a bug or not.

### How to reproduce

1. put `for x in 0..10 { ls } | flatten` in a foo.nu script and run it, it prints out records intead of a table
2. put table at the end like `for x in 0..10 { ls } | flatten | table` and now the output is tabular
3. on the command line if you do `for x in 0..10 { ls } flatten` it's tabular

### Expected behavior

i think that item 1 above should probably output a table without having to specifiy `| table` in a script. maybe?

### Configuration

| key                | value                                                                                         |
| ------------------ | --------------------------------------------------------------------------------------------- |
| version            | 0.59.0                                                                                        |
| branch             | main                                                                                          |
| short_commit       | 6d303f2c                                                                                      |
| commit_hash        | 6d303f2ca3c71e86d55b1a82e08eec7ee642c6bc                                                      |
| commit_date        | 2022-02-08 19:08:02 +00:00                                                                    |
| build_os           | windows-x86_64                                                                                |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)                                                           |
| rust_channel       | stable-x86_64-pc-windows-msvc                                                                 |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)                                                           |
| pkg_version        | 0.59.0                                                                                        |
| build_time         | 2022-02-08 13:50:53 -06:00                                                                    |
| build_rust_channel | release                                                                                       |
| features           | dataframe, default, which, zip                                                                |
| installed_plugins  | gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml |

### Additional context

@sholderbach found this

**Comment by jntrnr** [comment]
This should be fixed by https://github.com/nushell/nushell/pull/4377. Can you confirm?

**Comment by sholderbach** [comment]
Resolved. Thank you
