### ISSUE TITLE
ENV values can not be set conditionally with `let-env`

### ISSUE THREAD

**Issue by lukexor** [nushell/nushell#4379]
### Describe the bug

`let` allows the right-hand side to be a conditional if/else statement while `let-env` does not.

e.g.

```
let-env PATH = if (env | any? name == VENV_OLD_PATH) { $env.VENV_OLD_PATH } else { $env.PATH }
```

Is this an intended breaking change with engine-q?

### How to reproduce

engine-q does not support setting ENV vars conditionally:

```
let-env PATH = if (env | any? name == VENV_OLD_PATH) { $env.VENV_OLD_PATH } else { $env.PATH }
Error: nu::parser::extra_positional (https://docs.rs/nu-parser/0.59.0/nu-parser/enum.ParseError.html#variant.ExtraPositional)

  × Extra positional argument.
   ╭─[entry #4:1:1]
 1 │ let-env PATH = if (env | any? name == VENV_OLD_PATH) { $env.VENV_OLD_PATH } else { $env.PATH }
   ·                   ─────────────────┬─────────────────
   ·                                    ╰── extra positional argument
   ╰────
  help: Usage: let-env <var_name> = <initial_value>
```

### Expected behavior

In nushell this works:

```
let-env PATH = if (env | any? name == VENV_OLD_PATH) { $env.VENV_OLD_PATH } else { $env.PATH }
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | baceb546                                 |
| commit_hash        | baceb54660a990e51dd4db60075ced9ef7cd6554 |
| commit_date        | 2022-02-08 17:13:04 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-08 10:47:47 -08:00               |
| build_rust_channel | release                                  |
| features           | default, which                           |
| installed_plugins  |                                          |

### Additional context

This use case is to primarily support virtual environments and temporary ENV changes based on a `.nu-env` file and `autoenv`

Workaround is to use a temporary variable:

```
let path = if (env | any? name == VENV_OLD_PATH) { $env.VENV_OLD_PATH } else { $env.PATH }
let-env PATH = $path
```

**Comment by fdncred** [comment]
what happens if you put the entire right hand side in parens?  like this
`let-env PATH = (if (env | any? name == VENV_OLD_PATH) { $env.VENV_OLD_PATH } else { $env.PATH })`

**Comment by lukexor** [comment]
That does indeed work! `let` and `let-env` should be consistent I would think.

**Comment by fdncred** [comment]
ya, agreed. it seems like being consistent may be better.
