### ISSUE TITLE
`insert` command is missing in 0.59 ?

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4381]
### Describe the bug

`insert` command is missing in 0.59

### How to reproduce

help insert                                                                                                                                         
```bash
Error: nu::shell::command_not_found (link)

  × Command not found
   ╭─[entry #1:1:1]
 1 │ help insert
   ·      ───┬──
   ·         ╰── command not found
   ╰────
```

### Expected behavior

`insert` command should exist

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | merge-engine-q                           |
| short_commit       | d70d91e5                                 |
| commit_hash        | d70d91e5591b83a689df0de40a40f07de0fda69b |
| commit_date        | 2022-02-07 19:54:06 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-08 10:45:41 +08:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, which, zip           |
| installed_plugins  | query, query json, query web, query xml  |

**Comment by eggcaker** [comment]
checkout the [breaking changes](https://github.com/nushell/nushell/issues/4305) , `insert` replaced with `update` command that inserts if missing

**Comment by hustcer** [comment]
Thanks 👍
