### ISSUE TITLE
Can not input or paste `let v = (LANG=en_US git branch -vv)` in the terminal without any change in v0.59

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4384]
### Describe the bug

Can not input or paste `let v = (LANG=en_US git branch -vv)` in the terminal without any change in v0.59, it will automatically change to `let v = (LANGLANG=en_US git branch -vv)` and $v output was not as expected.

### How to reproduce

1. Try to  input or paste `let v = (LANG=en_US git branch -vv)` in the terminal
2. The input will change to `let v = (LANGLANG=en_US git branch -vv)`
3. $v output nothing

### Expected behavior

Input should be displayed as it is.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | merge-engine-q                           |
| short_commit       | d70d91e5                                 |
| commit_hash        | d70d91e5591b83a689df0de40a40f07de0fda69b |
| commit_date        | 2022-02-07 19:54:06 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-08 10:45:41 +08:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, which, zip           |
| installed_plugins  | query, query json, query web, query xml  |

**Comment by jntrnr** [comment]
I'm seeing two possibly related errors:

* The duplication and incorrect highlighting
* The incorrect redirection of output for the subexpression (for me it prints to the screen instead of assigning to the variable)

**Comment by lukexor** [comment]
Definitely seems highlight related.

As you type - the first `space` after the `=` results in it getting malformed and highlighting changing from red (invalid) to normal - backspacing the `space` returns the `=` - so the input isn't being lost, just stomped on somewhere in the highlighter
