### ISSUE TITLE
case insensitive sorting of tables

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4386]
### Describe the bug

This doesn't work like it should `ls | sort-by name -i`. It does the sorting but not case-insensitively like it should.

### How to reproduce

1. ls | sort-by name -i
2. ls | sort-by -i name

### Expected behavior

sort things case-insensitively

### Configuration

| key                | value                                                                                                    |
| ------------------ | -------------------------------------------------------------------------------------------------------- |
| version            | 0.59.0                                                                                                   |
| branch             | main                                                                                                     |
| short_commit       | 565be6aa                                                                                                 |
| commit_hash        | 565be6aaefc60be154265d8951027c19769b02ae                                                                 |
| commit_date        | 2022-02-08 15:32:27 +00:00                                                                               |
| build_os           | macos-aarch64                                                                                            |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)                                                                      |
| rust_channel       | stable-aarch64-apple-darwin                                                                              |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)                                                                      |
| pkg_version        | 0.59.0                                                                                                   |
| build_time         | 2022-02-08 09:53:03 -06:00                                                                               |
| build_rust_channel | debug                                                                                                    |
| features           | dataframe, default, which, zip                                                                           |
| installed_plugins  | gstat, inc, nu-example-1, nu-example-2, nu-example-3, nu-python, query, query json, query web, query xml |

### Additional context

/cc @stormasm - looks like I missed some cases

**Comment by stormasm** [comment]
@fdncred I noticed that as well yesterday when I was working on this but thought maybe I did not understand how it was "supposed" to work.  So glad you clarified for us that it is indeed not yet (exactly) correct.  Since I am not actually sure myself how it is supposed to sort would you mind showing in this issue how the ordering should work with a small example, Thanks !

**Comment by stormasm** [comment]
ok cool thanks that makes sense...

**Comment by fdncred** [comment]
fixed
