### ISSUE TITLE
Nu explodes if terminal width is less than prompt width on Windows

### ISSUE THREAD

**Issue by Porges** [nushell/nushell#439]
Repro: run `nu`, shrink terminal until the `>` character would wrap, `nu` dies.

Start: okay:

![image](https://user-images.githubusercontent.com/12575/63658358-19cd0d00-c7fe-11e9-9bb6-10f9c26b43a5.png)

Shrinking window: still okay (but prompt is not reprinted very well):
![image](https://user-images.githubusercontent.com/12575/63658377-336e5480-c7fe-11e9-85ce-4416fac3a8e7.png)

Keep going: oh no! :boom:
![image](https://user-images.githubusercontent.com/12575/63658388-454ff780-c7fe-11e9-9070-521cc40d74d8.png)

Link to: #438

**Comment by wycats** [comment]
@jonathandturner Do you have any ideas about this?

**Comment by wycats** [comment]
#438

**Comment by Porges** [comment]
After a quick look, the bug is probably inside `rustyline`.

**Comment by Porges** [comment]
Reported here: https://github.com/kkawakam/rustyline/issues/280

In the mean time, `nu` could probably handle this `Err` result more gracefully.

**Comment by jonathandturner** [comment]
Since rustyline fixed this, I think we should move to the github version of rustyline to help them test ahead of their next release.

**Comment by jonathandturner** [comment]
https://github.com/nushell/nushell/pull/667

**Comment by jonathandturner** [comment]
I believe this is fixed now
