### ISSUE TITLE
sys and ps commands hanging indefinitely

### ISSUE THREAD

**Issue by CodeLongAndProsper90** [nushell/nushell#4390]
### Describe the bug

On nixos, running `sys` or `ps` in nushell causes the shell to hang indefinitely. I'm using nixpkgs `689b76bcf36055afdeb2e9852f5ecdd2bf483f87`, nushell `0.43.0`

### How to reproduce

`nix shell nixpkgs#nushell -c nu -c sys`

### Expected behavior

I expected `sys` or `ps` to display a table or return to the prompt without hanging.

### Configuration

| key                | value                                                                                                                                                                   |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.43.0                                                                                                                                                                  |
| build_os           | linux-x86_64                                                                                                                                                            |
| rust_version       | rustc 1.57.0                                                                                                                                                            |
| cargo_version      | cargo 1.57.0                                                                                                                                                            |
| pkg_version        | 0.43.0                                                                                                                                                                  |
| build_time         | 1980-01-01 00:00:00 +00:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

**Comment by jntrnr** [comment]
Thanks for the bug report. Something that's changed recently is that we've rewritten these commands, though there may still be similar behaviours with the new commands. Would you be able to build the latest main to see if you still see them?

**Comment by CodeLongAndProsper90** [comment]
After waiting, it appears that `sys` took 2m 45s to run, instead of hanging.

**Comment by jntrnr** [comment]
@CodeLongAndProsper90 is that with 0.43 nushell or with the latest main?

**Comment by CodeLongAndProsper90** [comment]
0.43

**Comment by CodeLongAndProsper90** [comment]
Still takes 2m 45s, even on `main` (`fc88a8538be65d12a514da3d0ed52c496b902ac7`)

**Comment by CodeLongAndProsper90** [comment]
So I `strace`d it, and it was hanging on `statfs("/media/hdd")` (all access actually) and apparently it's something with my system because unplugging and replugging it. Explains why it hung `sys`, but I wouldn't expect it to hang `ps`... I've resolved it now.

**Comment by fdncred** [comment]
This may be upstream in the `sysinfo` [crate](https://github.com/GuillaumeGomez/sysinfo). It would be nice to know if you can run the example in that repo. As I recall, there's on example with a bunch of different options after you run it and you choose the options of a type of a menu.
