### ISSUE TITLE
Add ability or command to capture stderr

### ISSUE THREAD

**Issue by lukexor** [nushell/nushell#4396]
### Related problem

Currently there is no way for nushell to handle or manipulate output on stderr. So, for example, this leads to having to resort to bash or zsh for capturing log output to a file or parsing it to a table in nushell.

Compare:
```
> bash -c 'echo "stdout"' | lines | wrap output

╭───┬────────╮
│ # │ output │
├───┼────────┤
│ 0 │ stdout │
╰───┴────────╯
```

```
> bash -c '>&2 echo "stderr"' | lines | wrap output
stderr
```

### Describe the solution you'd like

Some language support (a setting or command) for allowing stderr in pipelines.

**Comment by rgwood** [comment]
@lukexor I think the new `complete` command addresses this: https://github.com/nushell/nushell/pull/4647

**Comment by 89z** [comment]
Does `complete` work with files? I want to do the NuShell equivalent of this POSIX syntax:

~~~
something 2> file.txt
~~~

**Comment by lukexor** [comment]
@rgwood I've seen `complete` and while it works for some things, I think there are still some gaps. For example it doesn't seem to be able to capture anything printed out with the rust `log` crate implementations such as `pretty_env_logger`.

For example, one of my projects:

```
> cargo run --example logging | complete
   Compiling pix-engine v0.5.5 (~/dev/pix-engine)
    Finished dev [unoptimized + debuginfo] target(s) in 8.00s
     Running `target/debug/examples/logging`
 INFO  pix_engine::engine > Starting `PixEngine`...
 INFO  pix_engine::engine > Quitting `PixEngine`...
╭───────────┬───╮
│ stdout    │   │
│ stderr    │   │
│ exit_code │ 0 │
╰───────────┴───╯
```

**Comment by jntrnr** [comment]
To redirect stderr, you need another step:

```
> do -i { cargo run --example logging}  | complete 
```

The `do -i { ... }` form is currently the only way to force stderr to be redirected. Otherwise, it gets freely printed to the screen.

**Comment by lukexor** [comment]
Thanks! I'd love for that to be in the help for `complete`.

**Comment by 89z** [comment]
That doesnt seem to work in all cases. For example, this eats stderr, but doesnt send it to the file:

~~~
do -i { something } | save file.txt
~~~

**Comment by jntrnr** [comment]
@89z you need to combine `do -i { .. }` with `complete` to get the stream out that you want

**Comment by 89z** [comment]
but, does `complete` even work with files? If so, what does the syntax look like?

**Comment by tmccombs** [comment]
How would one do something equivalent to :

```bash
some_command 2> file1 | less
```
in nushell?

**Comment by lukexor** [comment]
Complete seems to do the trick for most things. @tmccombs a lot of the piping redirection of bash has to be handled differently, I'm not sure how nushell would split stderr and stdout to two different places, but could open a feature request for it if it's not possible
