### ISSUE TITLE
Register plugin path can not be a variable

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4399]
### Describe the bug

Register plugin path can not be a variable

### How to reproduce

1. `register -e capnp ~/.cargo/bin/nu_plugin_quer` works
2. `let p = ('~/.cargo/bin/nu_plugin_query'|path expand); register -e capnp $p` does not work
```
〉register -e capnp $p                                                                                                                                  02/10/2022 10:04:14 AM
Error: nu::parser::file_not_found (link)

  × File not found
   ╭─[entry #24:1:1]
 1 │ register -e capnp $p
   ·                   ─┬
   ·                    ╰── File not found: $p
   ╰────
```

### Expected behavior

`let p = ('~/.cargo/bin/nu_plugin_query'|path expand); register -e capnp $p` should work just as `register -e capnp ~/.cargo/bin/nu_plugin_quer` does

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | e1f98c1b                                 |
| commit_hash        | e1f98c1bfd16108e18641ef220090fa101057a77 |
| commit_date        | 2022-02-09 23:20:46 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-10 09:49:52 +08:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | query, query json, query web, query xml  |

**Comment by kubouch** [comment]
Unfortunately, because `register` is a parser keyword, it cannot work like that. That's a limitation of the language.

I'm not sure there is anything we can do to support it without fundamentally changing how Nushell works.

**Comment by hustcer** [comment]
> Unfortunately, because `register` is a parser keyword, it cannot work like that. That's a limitation of the language.
> 
> I'm not sure there is anything we can do to support it without fundamentally changing how Nushell works.

Any work around for this? It's found that we have to register the plugin every time if we want to use that plugin in my scripts, and for a team with lots of members the plugin path could be different like `~/.cargo/bin/nu_plugin_query` or `/usr/local/Cellar/nushell/bin/nu_plugin_query`, etc. It will be quite inconvenient if we can't register plugin dynamically.

**Comment by kubouch** [comment]
At the moment, no, you need to type it manually.

In the future, not directly, but we might be able to make some kind of workaround: You would have a directory (e.g., `~/.config/nushell/plugins`) where you could put (or symlink) your plugins and then call just `register nu_plugin_query`. We plan similar functionality for lookup of scripts as well.

The directory could be configurable, but that poses extra challenge since we'd be using eval'd value in the parser. However, we're already handling it for the current working directory stored in the engine state, so we could use a similar approach for the plugins/scripts directories.

**Comment by hustcer** [comment]
There is a workaround for those who using [just](https://github.com/casey/just) to manage their scripts, just modify your `Justfile` like this:
```make
set shell := ['nu', '-c']

NU_DIR := parent_directory(`(which nu).path.0`)

test:
  @register -e capnp {{ join(NU_DIR, 'nu_plugin_query') }}; \
    version
```
And run `just test` you will see the plugin from nu `version` output

**Comment by hustcer** [comment]
`NU_PLUGIN_DIRS` already supported
