### ISSUE TITLE
Need support for environment variables

### ISSUE THREAD

**Issue by kbumsik** [nushell/nushell#440]
> was: "cd $HOME returns error: Expected string, got Primitive(Nothing)"

Hi, since `cd ~` is not working yet #373 I'm trying to do same with `cd $HOME` but it returns the following error:

```
cd $HOME
error: Expected string, got Primitive(Nothing)
```

It looks like the shell does not recognize it as string, but `echo $HOME` works well:

```
echo $HOME
/home/kbumsik
```

**Comment by wycats** [comment]
At the moment there is no support for environment variables.

Normal variables will have the syntax `$<IDENT>`, so we need something else for environment variables. The most straight-forward approach would be something like PowerShell's namespaced variables (`$env:HOME`). Do you have any other thoughts?

**Comment by kbumsik** [comment]
Oh I see, but then how `echo $HOME` still works?
To me `$env:HOME` sounds better than conventional `$HOME` approach. I personally prefer `$env.HOME though` but `$env:HOME` is not a big deal to me. Here are some other considerations I can come up with:

1. How `export` command would look like?
2. How to per-command override? like `HOME=/home/john any_command`?

**Comment by wycats** [comment]
> Oh I see, but then how echo $HOME still works?

I think it probably works by accident:

- `echo` is an external command
- external commands get their arguments as strings -- eventually external commands will have interpolation for stuff like this, but right now they're just passed right through
- it probably parses `$HOME` for you

**Comment by wycats** [comment]
> How to per-command override? like HOME=/home/john any_command

Yes, I think this syntax should "just work". I miss it dearly in PowerShell.

**Comment by wycats** [comment]
I'm marking this as a bug since a shell without environment variable support isn't much of a shell.

**Comment by andrasio** [comment]
@kbumsik For the moment since our latest release you could do 

```shells
env | get vars."HOME" | cd
```

Inspecting the environment you can do with the `env` command.

**Comment by andrasio** [comment]
@kbumsik `~` was also fixed. Thank you!!! Please reopen or open a new issue if you see something not working as expected.

**Comment by robyoung** [comment]
@andrasio your suggested sollutions don't seem to work for me.

```
> nu --version
nushell 0.16.0
> env
HOME=/home/robyoung
PATH=/home/robyoung/.cargo/bin:/home/robyoung/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> env | get vars."PATH"
error: Type Error
  ┌─ shell:1:1
  │
1 │ env | get vars."PATH"
  │ ^^^ Expected row or table, found string

> echo $nu:env
───┬──
 0 │
───┴──
>
```

**Comment by andrasio** [comment]
> @andrasio your suggested sollutions don't seem to work for me.
> 
> ```
> > nu --version
> nushell 0.16.0
> > env
> HOME=/home/robyoung
> PATH=/home/robyoung/.cargo/bin:/home/robyoung/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> > env | get vars."PATH"
> error: Type Error
>   ┌─ shell:1:1
>   │
> 1 │ env | get vars."PATH"
>   │ ^^^ Expected row or table, found string
> 
> > echo $nu:env
> ───┬──
>  0 │
> ───┴──
> >
> ```

Nu has changed a lot :)

`echo $nu.path`
