### ISSUE TITLE
`where` does not work as before while filtering boolean column simply by the column name

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4400]
### Describe the bug

`where` does not work as before while filtering boolean column simply by the column name

### How to reproduce

1. `[[version patch]; [0.1.0 $false] [0.1.1 $true] [0.2.0 $false]]|where patch` works in the old engine
2. In v0.59 `[[version patch]; [0.1.0 $false] [0.1.1 $true] [0.2.0 $false]]|where patch` output nothing, we have to use `[[version patch]; [0.1.0 $false] [0.1.1 $true] [0.2.0 $false]]|where patch == $true` instead

### Expected behavior

`[[version patch]; [0.1.0 $false] [0.1.1 $true] [0.2.0 $false]]|where patch` should behave just as `[[version patch]; [0.1.0 $false] [0.1.1 $true] [0.2.0 $false]]|where patch == $true` in the new engine.

```
╭───┬─────────┬───────╮
│ # │ version │ patch │
├───┼─────────┼───────┤
│ 0 │ 0.1.1   │ true  │
╰───┴─────────┴───────╯
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | e1f98c1b                                 |
| commit_hash        | e1f98c1bfd16108e18641ef220090fa101057a77 |
| commit_date        | 2022-02-09 23:20:46 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-10 09:49:52 +08:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | query, query json, query web, query xml  |

**Comment by fdncred** [comment]
The new behavior is expected. The old behavior is unexpected. I'm not sure we'll change the new behavior. We'll have to talk about it.

**Comment by hustcer** [comment]
> The new behavior is expected. The old behavior is unexpected. I'm not sure we'll change the new behavior. We'll have to talk about it.

Agree, both of the behavior is acceptable

**Comment by fdncred** [comment]
@hustcer is it ok if we close this and try to live with the 0.59.0 behavior?

**Comment by hustcer** [comment]
> @hustcer is it ok if we close this and try to live with the 0.59.0 behavior?

Okay
