### ISSUE TITLE
Cannot run `git fetch origin --prune '+refs/tags/*:refs/tags/*'` in the new engine

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4404]
### Describe the bug

Cannot run `git fetch origin --prune '+refs/tags/*:refs/tags/*'` in the new engine

### How to reproduce

1. `git fetch origin --prune '+refs/tags/*:refs/tags/*'` run pretty well in `bash` or the old `nu`
2. Run the above command in nu v0.59.0 will get:
```
Error: nu::shell::file_not_found (link)

  × File not found
   ╭─[entry #1:1:1]
 1 │ git fetch origin --prune '+refs/tags/*:refs/tags/*'
   ·                          ─────────────┬────────────
   ·                                       ╰── pattern not found
   ╰────

```

### Expected behavior

Should run without any exception

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.59.0                                              |
| branch             | main                                                |
| short_commit       | c2118e75                                            |
| commit_hash        | c2118e7505d779103bf6f6c845ea86f8a1cd70c0            |
| commit_date        | 2022-02-10 02:24:29 +00:00                          |
| build_os           | macos-x86_64                                        |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)                 |
| rust_channel       | stable-x86_64-apple-darwin                          |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)                 |
| pkg_version        | 0.59.0                                              |
| build_time         | 2022-02-10 12:07:35 +08:00                          |
| build_rust_channel | release                                             |
| features           | dataframe, default, which, zip                      |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by kubouch** [comment]
I think it's trying to glob. If I remember correctly, we added glob expansion for external commands but we should probably just pass the string as-is if the glob fails.

**Comment by hustcer** [comment]
Another command that can not be run successfully: `git push --mirror 2>&1`
```
fatal: '2>&1' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Works fine in bash. Not sure whether they are the same issue.

**Comment by fdncred** [comment]
I don't believe nushell has ever supported redirection like `2>&1. iirc,
1 is stdout. 2 is stderr. so nushell doesn't support redirection like `>`, `1>`, `2>`, `1>&2`, `2>&1`. right now we just have `| save`

I agree about the first issue. it kind of looks like regex too but I don't think there's regex handlers for externals so I'm sure kubouch is right about glob.

**Comment by hustcer** [comment]
> I don't believe nushell has ever supported redirection like `2>&1`. iirc, 1 is stdout. 2 is stderr. so nushell doesn't support redirection like `>`, `1>`, `2>`, `1>&2`, `2>&1`. right now we just have `| save`
> 

Actually, I'm run it in this way `let output = ((^git push --mirror 2>&1) | compact | str collect)`, redirection should work for `^git`

**Comment by fdncred** [comment]
it would be great to have an example that doesn't require a git push :) if possible. clearly we're forcing the call to an external with `^` but i'm not sure how the shelling out and redirection works in nushell right now. it's an interesting case.

**Comment by kubouch** [comment]
@hustcer You'd need to pipe it through bash or some other shell in order for `2>&1` to work. Nushell will just take it and pass as a string argument to the spawned process.
