### ISSUE TITLE
Support ctrl+left and ctrl+right on keyboard

### ISSUE THREAD

**Issue by dbarnett** [nushell/nushell#441]
On bash I can normally use ctrl+left and ctrl+right to jump the cursor over whole words, but on Nushell when I press ctrl+left or ctrl+right it doesn't have any effect on the cursor or anything else. Can that be supported on Nushell?

**Comment by wycats** [comment]
Is this supported in Rustyline?

**Comment by dbarnett** [comment]
Figured out it's not a built-in shortcut on readline, just a commonly configured mapping at least on Ubuntu (https://stackoverflow.com/a/5029155/307705). It's discussed somewhat in kkawakam/rustyline#115 and supposedly it's possible to customize keybindings after https://github.com/kkawakam/rustyline/commit/ace74cc187. Is there some special configuration to enable that or hook it up to inputrc?

**Comment by dbarnett** [comment]
I think I found my answer: they provide a `bind_sequence` method that can be used to configure rustyline, but it looks like nushell would need code to load inputrc and feed the config into rustyline for it to work. I posted on that rustyline issue to confirm that's the way to go.

**Comment by jonathandturner** [comment]
@dbarnett - we could potentially add support for doing this. If it's a feature we want to support broadly be default, we can also bundle that settings file into Nu itself.

**Comment by dbarnett** [comment]
I played around with it and found I can get the behavior I'm personally looking for by adding these lines into src/cli.rs:
```rust
rl.bind_sequence(KeyPress::ControlLeft, Cmd::Move(Movement::BackwardWord(1, Word::Vi)));
rl.bind_sequence(KeyPress::ControlRight, Cmd::Move(Movement::ForwardWord(1, At::AfterEnd, Word::Vi)));
```

Not sure if it can just be hard-coded without at least an opt-out though. I had been hoping it'd be possible to just read your system settings from inputrc so it could just "do the right thing" without getting too controversial, but that looks like it'd be extremely brittle to even be able to process a subset of the grammar if there are no helpers for it built into the library.

**Comment by dbarnett** [comment]
So could I just add that code and put it behind a config option? Any suggestions on what to call it and where to put it if so?
