### ISSUE TITLE
Unable to change user's login shell

### ISSUE THREAD

**Issue by stefins** [nushell/nushell#4417]
Hey,
 I'm unable to change my login shell to nushell
> chsh -s `which nu`
> Changing shell for user.
> Password for user:
> chsh: /usr/local/bin/nu: non-standard shell

OS : MacOS Big Sur

**Comment by fdncred** [comment]
is the path to nu in the /etc/shells file?

**Comment by stefins** [comment]
Yeah that seems to work! Thanks  :)
