### ISSUE TITLE
Panic when typing command name imported from module

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4418]
### Describe the bug

Under some scenarios, typing the name of a command exported from a module panics.

### How to reproduce

1. Create a `spam.nu` file containing this:
```
export def foo [p: path] {
    if $true {
        echo $p
    }
}
```
2. `use spam.nu *`
3. `foo` - - After typing the last `o`, it panics
```
thread 'main' panicked at 'Attempt to mutate a block that is in the permanent (immutable) state', crates/nu-protocol/src/engine/engine_state.rs:1153:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: nu_protocol::engine::engine_state::StateWorkingSet::get_block_mut
   3: nu_parser::parser::parse
   4: <nu_cli::syntax_highlight::NuHighlighter as reedline::highlighter::Highlighter>::highlight
   5: reedline::engine::Reedline::repaint
   6: reedline::engine::Reedline::read_line
   7: nu::repl::evaluate
   8: nu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Expected behavior

Not panic

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | ba4d8ae8                                 |
| commit_hash        | ba4d8ae8c3b44aa399cdb1f8c7d960830df5bf01 |
| commit_date        | 2022-02-10 23:27:51 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-11 10:30:13 +02:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | gstat                                    |

### Additional context

This bug happens only in a very specific scenario:
1. Module must be a file (manually defined `module` works fine)
2. The custom command must reference its argument inside a block (see the `if $true {...}` in the example)

**Comment by jntrnr** [comment]
@kubouch was this working before the variable capture fix I landed yesterday?

**Comment by kubouch** [comment]
@jntrnr Yes, it was working before the PR (commit 0e5f4d88c58e6c3c81b13368f087fde9e2696b99 works fine)
