### ISSUE TITLE
Nushell cheat sheet

### ISSUE THREAD

**Issue by dbarnett** [nushell/nushell#442]
Could there be a "cheat sheet" of handy operations in Nushell, like you'd find [for vim](https://vim.rtorr.com/) or [for git](https://scotch.io/bar-talk/git-cheat-sheet)? That could be really useful as a quickstart and a great way to showcase nushell's power through examples.

## :postal_horn: UPDATE: a cheat sheet has been started in [*Nushell cheat sheet*](https://www.nushell.sh/book/cheat_sheet.html)
thanks @lomm28 :pray:

**Comment by wycats** [comment]
Great idea!

**Comment by igitur** [comment]
Also looking for a 1 or 2 pager that I can print out, stick against my wall to get me migrated from bash to nu.

**Comment by kw-fn** [comment]
Has this been accomplished with the [cookbook](https://www.nushell.sh/cookbook/)?

**Comment by igitur** [comment]
> Has this been accomplished with the [cookbook](https://www.nushell.sh/cookbook/)?

The cookbook is too verbose. A cheatsheet is 1 or 2 page pdf with a selection of the most common commands and patterns to use. Summarised very condensely.

**Comment by kw-fn** [comment]
Ok.. Is it necessary for this issue to persist?

**Comment by igitur** [comment]
> Ok.. Is it necessary for this issue to persist?

So I know this is open-source and I'm not owed anything. But I still believe a cheatsheet would be super useful for any newcomer.

I've been using nushell as my default Windows Terminal shell for almost a year and I keep having to Google how to do things specific to nushell.

**Comment by kw-fn** [comment]
I guess you wouldn't be okay just capturing the output of `help commands`?

**Comment by jntrnr** [comment]
Checking in - agreed this would be useful to have around.

**Comment by lomm28** [comment]
is anyone working on this? If not, I could give it a try.

**Comment by amtoine** [comment]
> is anyone working on this? If not, I could give it a try.
>
not that i'm aware of :thinking: 

please go ahead :blush:

**Comment by lomm28** [comment]
@amtoine I believe this one can be closed now.

**Comment by amtoine** [comment]
i've updated the description of this issue to link to the cheat sheet :+1: 

if there are missing things, we should file issues in the website directly :yum:
