### ISSUE TITLE
Global variable not found from main

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4426]
### Describe the bug

Seems like `main` has issues capturing variables from outer scope

### How to reproduce

1. Create `foo.nu`:
```
#!/usr/bin/env nu

let foo = "foo"

def main [] {
    $foo
}
```
2. `chmod +x foo.nu`
3. `./foo.nu`
```
× Variable not found
   ╭─[./foo.nu:5:1]
 5 │ def main [] {
 6 │     $foo
   ·     ──┬─
   ·       ╰── variable not found
 7 │ }
   ╰────
```

### Expected behavior

The `foo` variable should be found.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | ba4d8ae8                                 |
| commit_hash        | ba4d8ae8c3b44aa399cdb1f8c7d960830df5bf01 |
| commit_date        | 2022-02-10 23:27:51 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-11 10:30:13 +02:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | gstat                                    |

### Additional context

When I change `main` to other function and then call the function, the `$foo` is captured correctly:
```
#!/usr/bin/env nu

let foo = "foo"

def print-foo [] {
    $foo
}

print-foo
```

**Comment by kubouch** [comment]
@jntrnr I'm wondering if this is the same capture bug you were hunting before.

**Comment by jntrnr** [comment]
I found it - wow funny. I was trying not to evaluate the whole file and only focus on the `main` call. But, if you think about it, how would we ever get a value for `$foo` without evaluating the body of the file?

Working on a fix
