### ISSUE TITLE
Unhelpful error message for `update` if block returns the wrong data type

### ISSUE THREAD

**Issue by sholderbach** [nushell/nushell#4429]
### Describe the bug

`update` erroneously triggers the `Error: nu::shell::column_not_found` and highlights the  column name positional, if the block for the update command does not process the data in a way that returns a compatible list.

## Correct pipeline: 
``` nu
["test", "words", "for", "checking"] | wrap "text_col"  | update len_col { get text_col | str length}
```
Produces a valid table.
## Mistake:
```
["test", "words", "for", "checking"] | wrap "text_col"  | update len_col { $in.text_col | str length}
```
## Misleading error message:
```
Error: nu::shell::column_not_found (link)

  × Cannot find column
   · ▲
   · ╰── value originates here
   ╰────
   ╭─[entry #13:1:1]
 1 │ ["test", "words", "for", "checking"] | wrap "text_col"  | update len_col { $in.text_col | str length}
   ·                                                                  ───┬───
   ·                                                                     ╰── cannot find column
   ╰────
```

### Expected behavior

Inform the user that the result should be a list, which can be coerced into a new column of the table record

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | 19caef26                                 |
| commit_hash        | 19caef260d0a18b226a32f7a76976d38503f964a |
| commit_date        | 2022-02-08 16:21:17 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-08 18:01:29 +01:00               |
| build_rust_channel | debug                                    |
| features           | default, which                           |
| installed_plugins  |                                          |

**Comment by sholderbach** [comment]
Documentation of my confusion as the **input** to the update command differs between the two versions and thus triggers the code path with the wrong error message in `nu_protocol::value::Value::replace_data_at_cell_path`.

![image](https://user-images.githubusercontent.com/15833959/153663576-e853c813-e3e5-4a76-b036-7b35c15f88bb.png)

**Comment by hustcer** [comment]
I think we can close this issue now, the `update` behavior has been changed, and we should use `insert` or `upsert` to create a non-exist column

**Comment by sholderbach** [comment]
Closing would depend, whether `insert`/`upsert` provide now a better error message for the problem in the block. This is not technically related to the check for presence of  a column but rather a bug in the error reporting machinery

**Comment by sholderbach** [comment]
Situation more informative now
