### ISSUE TITLE
lsof command

### ISSUE THREAD

**Issue by dbarnett** [nushell/nushell#443]
The lsof command on Linux outputs a bunch of tabular data that would lend itself very well to nushell's structured paradigm. It also wouldn't need quite as many flags and options since Nushell mechanisms can handle most of the filtering and data manipulation.

**Comment by dbarnett** [comment]
Alternatively, the same information could be embedded into the sys structure. I'd just like to have intuitive Nushell commands to look up the same info, in whatever form that ends up being.

**Comment by wycats** [comment]
What should we name it? `open-files` is pretty long, but `files` is probably too confusing. I'd like to avoid cargo-culting confusing unixy acronyms (especially ones I never remember myself) if possible.

@jonathandturner any thoughts?

**Comment by twe4ked** [comment]
`open-files` sounds good to me, with tab completion long names aren't too much of a problem.

**Comment by dbarnett** [comment]
"open-files" doesn't sound too long but it's not quite self-explanatory from the name since "open" is a verb too so the name reads like it's a tool for opening files.

Note that the lsof tool lists things like network ports, too, not just "files" in the normal sense. That could mean one tool with a really generic name or could mean multiple tools with more specific names.

And is it worth considering adding relevant info nested under `sys`, or no?

**Comment by Akito13** [comment]
```
in-use
```
Maybe?

**Comment by joshy** [comment]
A remark maybe related or not. Every time I start some process and it crashes because some other process is already using the port I need to google the right way to find which process is using it. A `open-ports` command would also be nice. So it would be:
 * open-files
 * open-ports
etc

**Comment by waldyrious** [comment]
For future reference, `lsof`'s output is properly handled by the new `detect columns` functionality (#4127):

```
> lsof | head
COMMAND      PID    TID TASKCMD                USER   FD      TYPE             DEVICE  SIZE/OFF       NODE NAME
systemd        1                               root  cwd   unknown                                         /proc/1/cwd
systemd        1                               root  rtd   unknown                                         /proc/1/root
systemd        1                               root  txt   unknown                                         /proc/1/exe
systemd        1                               root NOFD                                                   /proc/1/fd
kthreadd       2                               root  cwd   unknown                                         /proc/2/cwd
kthreadd       2                               root  rtd   unknown                                         /proc/2/root
kthreadd       2                               root  txt   unknown                                         /proc/2/exe
kthreadd       2                               root NOFD                                                   /proc/2/fd
rcu_gp         3                               root  cwd   unknown                                         /proc/3/cwd
```

```
> lsof | head | detect columns
───┬──────────┬─────┬─────┬─────────┬──────┬──────┬─────────┬────────┬──────────┬──────┬──────────────
 # │ COMMAND  │ PID │ TID │ TASKCMD │ USER │  FD  │  TYPE   │ DEVICE │ SIZE/OFF │ NODE │     NAME     
───┼──────────┼─────┼─────┼─────────┼──────┼──────┼─────────┼────────┼──────────┼──────┼──────────────
 0 │ systemd  │ 1   │     │         │ root │ cwd  │ unknown │        │          │      │ /proc/1/cwd  
 1 │ systemd  │ 1   │     │         │ root │ rtd  │ unknown │        │          │      │ /proc/1/root 
 2 │ systemd  │ 1   │     │         │ root │ txt  │ unknown │        │          │      │ /proc/1/exe  
 3 │ systemd  │ 1   │     │         │ root │ NOFD │         │        │          │      │ /proc/1/fd   
 4 │ kthreadd │ 2   │     │         │ root │ cwd  │ unknown │        │          │      │ /proc/2/cwd  
 5 │ kthreadd │ 2   │     │         │ root │ rtd  │ unknown │        │          │      │ /proc/2/root 
 6 │ kthreadd │ 2   │     │         │ root │ txt  │ unknown │        │          │      │ /proc/2/exe  
 7 │ kthreadd │ 2   │     │         │ root │ NOFD │         │        │          │      │ /proc/2/fd   
 8 │ rcu_gp   │ 3   │     │         │ root │ cwd  │ unknown │        │          │      │ /proc/3/cwd  
───┴──────────┴─────┴─────┴─────────┴──────┴──────┴─────────┴────────┴──────────┴──────┴──────────────
```
