### ISSUE TITLE
roll commands maintain ls_colors

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4444]
### Describe the bug

`ls | roll up` should maintain LS_COLORS coloring.

### How to reproduce

ls | roll up

### Expected behavior

maintain coloring

### Configuration

|key|value|
|-|-|
|version|0.59.0|
|branch|main|
|short_commit|baf6348e|
|commit_hash|baf6348e663b8d7ef1a047b706f3c409f61961db|
|commit_date|2022-02-12 15:06:52 +00:00|
|build_os|macos-aarch64|
|rust_version|rustc 1.58.1 (db9d1b20b 2022-01-20)|
|rust_channel|stable-aarch64-apple-darwin|
|cargo_version|cargo 1.58.0 (f01b232bc 2022-01-19)|
|pkg_version|0.59.0|
|build_time|2022-02-12 09:07:34 -06:00|
|build_rust_channel|debug|
|features|dataframe, default, which, zip|
|installed_plugins|gstat, inc, nu-example-1, nu-example-2, nu-example-3, nu-python, query, query json, query web, query xml|

**Comment by jntrnr** [comment]
fixed by #4525
