### ISSUE TITLE
Inline environment variables

### ISSUE THREAD

**Issue by wycats** [nushell/nushell#445]
This syntax should "just work":

```
$ RUST_LOG=trace cargo run
```

It should be treated as syntax by the parser.

**Comment by indeyets** [comment]
Fish shell uses explicit `env`. So it would be `$ env RUST_LOG=trace cargo run`. I'm not sure why, but probably there are reasons and it makes sense to consider this.

One possible reason is that logic is clearly encapsulated into `env` command

**Comment by indeyets** [comment]
it's not about syntactic complexity, but about consistency. `fish` shell tries to tell that everything is a function call. so env-setting needs to start with function name too. they decided to avoid making special case

I'm ok with either option :)

**Comment by jedahan** [comment]
though I like the try of `env RUST_LOG trace | cargo run` what happens when you try and compose?

`env PROD true | cargo build | append $PROD`

what would it mean to have `env PROD false` somewhere later in the chain? Does `env` also passthrough the pipe?

This is super interesting design space.

**Comment by CreepySkeleton** [comment]
Not really related here, but I would also like to see support for something like `export` in bash.

**Comment by dignifiedquire** [comment]
Is there any workaround for this? I use this constantly, and this effectively blocks me from using nushell :(

**Comment by thegedge** [comment]
@dignifiedquire I think the only way to work around this right now is via `env`:

```
/usr/bin/env NAME=value my_command ...
```

**Comment by kvrhdn** [comment]
Hi, I'd like to bump this issue 🙂 This is the only thing that forces me to switch to another shell now and then.

**Comment by andrasio** [comment]
@jonathandturner can we close this?

**Comment by CreepySkeleton** [comment]
It looks like this was implemented! https://github.com/nushell/nushell/pull/1717

The syntax is awkward though.

**Comment by thegedge** [comment]
Yep, that one closes it. A familiar shorthand form was added to

```
❯ FOO="testing env var" ^env | grep FOO
FOO="testing env var"
```

It only supports on env var at the moment though, but I opened https://github.com/nushell/nushell/issues/1832 to solve that.

**Comment by floam** [comment]
For what it's worth, on fish, we ended up adding support for the shorthand too because it's convenient and everyone wants it; it's nice to use, elegance be damned.

**Comment by kindkitchen** [comment]
<sup>Sorry, **I see that the issue is already closed**, but because for me at the end it is still not clear how to export variable for simple shell usage - I let here my similar problem with solution, may be it will become handy for someone.</sup>

#### What i wanted: _`(bash equivalent)`_
1. inline usage
    ```bash
    NVIM_APPNAME=nvim-kickstart nvim
    ```
2. aliasing somewhere in some config
    ```bash
    alias nvim="NVIM_APPNAME=nvim kickstart nvim"
    ```
#### How I get it: _`(nushell)`_
1. inline usage
    ```nushell
    export-env { $env.NVIM_APPNAME = 'nvim-kickstart' }; nvim
    ```
2. ~~aliasing~~ in `config.nu`
    ```nushell
    export-env { $env.NVIM_APPNAME = 'nvim-kickstart' };
    ```
#### The documentation that help me:
[https://www.nushell.sh/commands/docs/export-env.html#examples](https://www.nushell.sh/commands/docs/export-env.html#examples)

**Comment by weirdan** [comment]
> `NVIM_APPNAME=nvim-kickstart nvim`

This works in nushell as well.

For alias, I would either do:

```nushell
alias nvim = with-env {NVIM_APPNAME: nvim-kickstart} { ^nvim }
```

or 

```nushell
alias nvim = do { $env.NVIM_APPNAME = "nvim-kickstart"; ^nvim }
```

You don't need `export-env` in `config.nu`, you can just use:

```nushell
$env.NVIM_APPNAME = 'nvim-kickstart'
```
