### ISSUE TITLE
Disable annoying bell sound on error

### ISSUE THREAD

**Issue by vivainio** [nushell/nushell#446]
Repro:

- Use Windows build 0.2.0
- Directory "foo" doesn't exist
- Type "cd foo" and press tab
- Bell sound sounds every time you press tab

Expected behavior:

- Bell doesn't ring

**Comment by jonathandturner** [comment]
@vivainio - I wonder if it's from your windows sound settings? I don't hear a bell in Windows.

**Comment by jonathandturner** [comment]
but yes, agreed that sounds annoying if it's the default windows behavior

**Comment by vivainio** [comment]
I have a pretty clean windows image (wiped a few few weeks ago). This is probably some config option in rustyline

**Comment by vivainio** [comment]
Seems that it's not configurable in rustyline. Should this ticket be moved there?

**Comment by Akito13** [comment]
This is an issue related to Windows. It does it all the time, that's why I have the system sounds disabled entirely. Same behaviour with WSL, for example.

**Comment by vivainio** [comment]
@Akito13 it's definitely rustyline code ringing that bell though

**Comment by vivainio** [comment]
I created a ticket on rustyline library https://github.com/kkawakam/rustyline/issues/281

**Comment by vivainio** [comment]
Rustyline has a PR up: https://github.com/kkawakam/rustyline/pull/282. I wonder if nushell project can test it somehow? I don't know how to do it

**Comment by jonathandturner** [comment]
We can move to the github version of rustyline. Would that help @vivainio?

**Comment by jonathandturner** [comment]
We're going to move to the git version of rustyline, which should fix this. https://github.com/nushell/nushell/pull/667

I'm going to close the issue, but please reopen and ;et us know if you still hear the bell on the recent master.

**Comment by rokopt** [comment]
> We're going to move to the git version of rustyline, which should fix this. #667
> 
> I'm going to close the issue, but please reopen and ;et us know if you still hear the bell on the recent master.

I'm hearing the bell after, for example, hitting Tab when there's no way to complete the current string, on nushell 0.15.0 as installed by homebrew in a WSL 2 Ubuntu distribution on Windows 10 Pro 2004.  Is that expected (a version that doesn't have the fix yet), or should I re-open?
