### ISSUE TITLE
Custom completions coming from an external not working

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4463]
### Describe the bug

For me, if the completions list comes from an external, the custom completions do not work

### How to reproduce

```
# git-complete.nu
def "nu-complete git branch" [] {
   ^git branch | lines | each { $it | str find-replace "\* " "" | str trim }
}

extern "git checkout" [
  branch: string@"nu-complete git branch"
]
```
Then (assuming you're in a git repository with more than one branch),
```
> source git-complete.nu

> git checkout <tab>
NO_RESULTS_FOUND
```

### Expected behavior

Menu with branches should pop up.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | 1fd7b9ac                                 |
| commit_hash        | 1fd7b9ac38022e3157a5aa09d14db994c88283ed |
| commit_date        | 2022-02-12 11:11:54 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-12 14:03:38 +02:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | gstat                                    |

### Additional context

Things I tried:

### Works:
```
def "nu-complete git branch" [] {
  [ one two ]
}
```

### Doesn't work:
First have a `print_lines.bash` file:
```
#!/usr/bin/env bash

echo "one"
echo "two"
```
Then, define completions list like this:
```
def "nu-complete git branch" [] {
  bash print_lines.bash | lines
} 
```

It does not matter where I define these functions (REPL, script, config.nu).

**Comment by jntrnr** [comment]
![image](https://user-images.githubusercontent.com/547158/153769956-94326bb3-a40d-4dca-bebd-fb32b266e375.png)

@kubouch - are you running nushell as a login shell or from inside another shell? trying to think what might be different. I'm also on 64-bit linux (linux mint)

**Comment by kubouch** [comment]
@jntrnr Login shell

**Comment by kubouch** [comment]
It works for me on Windows.

**Comment by jntrnr** [comment]
@kubouch hmm, same here

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.59.0                                              |
| branch             | main                                                |
| short_commit       | 85d1a681                                            |
| commit_hash        | 85d1a681c7eed48361224a01bdfb3c080f48e1b9            |
| commit_date        | 2022-02-11 19:26:36 +00:00                          |
| build_os           | linux-x86_64                                        |
| rust_version       | rustc 1.58.0 (02072b482 2022-01-11)                 |
| rust_channel       | stable-x86_64-unknown-linux-gnu                     |
| cargo_version      | cargo 1.58.0 (7f08ace4f 2021-11-24)                 |
| pkg_version        | 0.59.0                                              |
| build_time         | 2022-02-11 14:58:01 -05:00                          |
| build_rust_channel | release                                             |
| features           | dataframe, default, trash, which, zip               |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

The only differences I can see is that you're building with a slightly different version of rustc, and I have more plugins installed. I wouldn't think either would make much of a difference.

**Comment by kubouch** [comment]
The problem is when path is translated to a list:
```
 def build-config [] {
     {
         env_conversions: {
             "PATH": {
                 from_string: { |s| $s | split row ':' }
                 to_string: { |v| $v | str collect ':' }
             }
         }
     }
 }

 let config = build-config
```

Relevant code: https://github.com/nushell/nushell/blob/fbaafaa4598cb3c58789c05692a90604de8a2506/crates/nu-cli/src/completions.rs#L273

**Comment by jntrnr** [comment]
@kubouch - did you ever figure out why your PATH conversions weren't working for externals in completions?

**Comment by kubouch** [comment]
@jntrnr Not yet. The PATH printed at line 273 is correct so it must be `run_external` not interpreting the PATH correctly under some circumstances. I plan to do more experiments later.

**Comment by fedoranvar** [comment]
@kubouch 

i've replaced spaces for dashes in func names, and it worked: (nu-complete git branch -> nu-complete-git-branch)
```nu
def "nu-complete-git-branch" [] {
  ^git branch | lines | each { $it | str find-replace "\* " "" | str trim }
}

def "nu-complete-git-remote" [] {
  ^git remote | lines | each { $it | str trim }
}

extern "git checkout" [
  branch: string@"nu-complete-git-branch"
]

extern "git push" [
  remote?: string@"nu-complete-git-remote",
  branch?: string@"nu-complete-git-branch"
]
```
![image](https://user-images.githubusercontent.com/52028706/154614858-f3bddfa9-628e-469d-a358-a6e1d10e855c.png)
![image](https://user-images.githubusercontent.com/52028706/154614883-5ca3b4bd-9b3a-4281-b6c5-1be25c5532d0.png)

**Comment by kubouch** [comment]
@fedoranvar Interesting. With spaces it didn't work?

**Comment by fedoranvar** [comment]
@kubouch yes, with space it didn't work.

it would be good if that was mentioned in #4300

**Comment by kubouch** [comment]
For me, adding dashes doesn't work.
