### ISSUE TITLE
sort-by -i with multiple columns doesn't sort right

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4467]
### Describe the bug

`ls | sort-by type name -i` doesn't sort the multiple columns specified case-insensitively.

### How to reproduce

1. in nushell 0.44 do `ls | sort-by type name -i` and look at the results
2. compare those to nushell 0.59

### Expected behavior

sort multiple columns insensitively

### Configuration

|key|value|
|-|-|
|version|0.59.0|
|branch|main|
|short_commit|f9e1c4ef|
|commit_hash|f9e1c4ef502cc0d6aeb2edf7d6be2dcf2461fdf6|
|commit_date|2022-02-09 10:58:54 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.58.1 (db9d1b20b 2022-01-20)|
|rust_channel|stable-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.58.0 (f01b232bc 2022-01-19)|
|pkg_version|0.59.0|
|build_time|2022-02-09 09:56:07 -06:00|
|build_rust_channel|debug|
|features|dataframe, default, which, zip|
|installed_plugins|gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml|

### Additional context

/cc @stormasm - ugh, works better but not quite there yet. why is sorting so hard. :)

**Comment by stormasm** [comment]
@fdncred honestly, I have no idea how to sort multiple columns...  

I have thought about it for awhile and have always been intrigued by the concept.  

Hopefully, it will be more obvious to someone else who has more experience with sorting multiple columns / or someone who understands how to do it who has a theoretical computer science background and knows the key algorithms / mental models / to get the job done right / in an efficient manner...

For me, luckily we have **vec.sort_by** which does the first column correctly.

**Comment by stormasm** [comment]
@fdncred also I don't understand how it is supposed to work even by looking at the results from nushell 0.44...  Especially when I start trying different test cases...

**Comment by fdncred** [comment]
@stormasm i have that mess in a new PR #4469 but i have no idea if i implemented it right. hehe.

**Comment by stormasm** [comment]
@fdncred thanks !  I reviewed and commented on #4469 as well, looking forward to hear what @jntrnr thinks if it looks good...  
nice job !
