### ISSUE TITLE
odd behavior with let and ^start

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4472]
### Describe the bug

On the way to reproducing a mac panic, i discovered this. I meant to create an alias but i created a variable instead. When i assign the start command to a variable it opens another tab in Windows Terminal. I presume this is because it's running the start command. I'm not really sure if this is expected but it surprised me.

### How to reproduce

1. let open = ^start

you should now have another tab or window open on windows.

### Expected behavior

just let me set a variable it without starting another session.

### Configuration

|key|value|
|-|-|
|version|0.59.0|
|branch|main|
|short_commit|f9e1c4ef|
|commit_hash|f9e1c4ef502cc0d6aeb2edf7d6be2dcf2461fdf6|
|commit_date|2022-02-09 10:58:54 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.58.1 (db9d1b20b 2022-01-20)|
|rust_channel|stable-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.58.0 (f01b232bc 2022-01-19)|
|pkg_version|0.59.0|
|build_time|2022-02-09 09:56:07 -06:00|
|build_rust_channel|debug|
|features|dataframe, default, which, zip|
|installed_plugins|gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml|

**Comment by jntrnr** [comment]
if you run `^start` by itself in nu, what happens?

**Comment by fdncred** [comment]
it opens another window in WT just like it does when you do `let open = ^start`

**Comment by jntrnr** [comment]
then seems like that's what we'd expect? Or does `^start` work differently if redirected?

**Comment by fdncred** [comment]
this is what i'm saying (not very well). it seems like it would be evaluated lazily. so, when you do `let open = ^start` it accepts it and goes on with it's business. but then, if i type `$open` it would then execute the `^start` and behave the way it's described.

**Comment by jntrnr** [comment]
yeah, for the lazy stuff about the only way we support it is with blocks, so you'd have to do `let open = { ^start }` and then `do $open` later. For the other cases, including subexpressions, we try to get to a value as soon as possible

**Comment by fdncred** [comment]
closing this since it's working as designed.
