### ISSUE TITLE
`cd` won't keep the path of previous block

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4490]
### Describe the bug

`cd` won't keep the path of previous block, or does it designed to behave this way?

### How to reproduce

1. Create a file `foo.nu` with content:
```nu
#!/usr/bin/env nu

def main [ ] {
    let foo = $true
    if $foo {
        cd ~; pwd
    }
    pwd
}
```
2. Run `nu foo.nu`, in v0.44 we will get the same path, However, in v0.59 they are different

### Expected behavior

The two `pwd`  output should be the same just as in nu v0.44

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.59.0                                              |
| branch             | main                                                |
| short_commit       | e763a8dc                                            |
| commit_hash        | e763a8dcef25a653bb4ede6a8965bd1f10bc54d5            |
| commit_date        | 2022-02-15 22:36:24 +00:00                          |
| build_os           | macos-x86_64                                        |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)                 |
| rust_channel       | stable-x86_64-apple-darwin                          |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)                 |
| pkg_version        | 0.59.0                                              |
| build_time         | 2022-02-16 09:51:43 +08:00                          |
| build_rust_channel | release                                             |
| features           | dataframe, default, which, zip                      |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by kubouch** [comment]
This works as intended. `cd` essentially means changing the `PWD` environment variable so it is scoped like other env vars.

**Comment by hustcer** [comment]
Okay, thanks
