### ISSUE TITLE
`update` should be able to access `$it`

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4492]
### Describe the bug

`update` command should be able to access `$it` in nu v0.59, just as it does in nu v0.44

### How to reproduce

1. In v0.59 run `[[version patch]; [0.1.0 $false] [0.1.1 $true] [0.2.0 $false]]|update version { $it.version | inc -p }` get:
```nu
Error: nu::parser::variable_not_found (link)

  × Variable not found.
   ╭─[entry #23:1:1]
 1 │ [[version patch]; [0.1.0 $false] [0.1.1 $true] [0.2.0 $false]]|update version { $it.version | inc -p }
   ·                                                                                 ─┬─
   ·                                                                                  ╰── variable not found
   ╰────
```
2. In v0.44 it will output:
```
  #   version   patch
───────────────────────
  0   0.1.1     false
  1   0.1.2     true
  2   0.2.1     false
```

### Expected behavior

`update` should be able to access `$it` in v0.59

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.59.0                                              |
| branch             | main                                                |
| short_commit       | e763a8dc                                            |
| commit_hash        | e763a8dcef25a653bb4ede6a8965bd1f10bc54d5            |
| commit_date        | 2022-02-15 22:36:24 +00:00                          |
| build_os           | macos-x86_64                                        |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)                 |
| rust_channel       | stable-x86_64-apple-darwin                          |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)                 |
| pkg_version        | 0.59.0                                              |
| build_time         | 2022-02-16 09:51:43 +08:00                          |
| build_rust_channel | release                                             |
| features           | dataframe, default, which, zip                      |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by fdncred** [comment]
you can try using a named block parameter like this `[[version patch]; [0.1.0 $false] [0.1.1 $true] [0.2.0 $false]]|update version {|r| $r.version | inc -p }`
