### ISSUE TITLE
How to add horizontal line for every element 

### ISSUE THREAD

**Issue by TangSirOnGit** [nushell/nushell#4493]
### Related problem

I have a txt file like this:
```
prop			|type			|description
totalCount	|Integer		|description for a
count		|Integer		|description for b
pageIndex	|Integer		|description for c
pageSize	|Integer		|description for d
```
I want to parse it into a table:

`open ./sample.txt | lines | split column "|"|str trim`

the output is :

<img width="539" alt="image" src="https://user-images.githubusercontent.com/10524715/154219976-d30e3b7c-c526-4abb-bbf2-33a2ecb3f123.png">

 

### Describe the solution you'd like

I want to display  a line between every element, like this : 
<img width="512" alt="image" src="https://user-images.githubusercontent.com/10524715/154220196-5164ad69-4dba-44e8-90f3-50bc82adf4d8.png">

What param do I need to input? 

Thanks!

**Comment by eggcaker** [comment]
change table_mode to basic like : 
```
let $config = {
  table_mode: basic
}
```
