### ISSUE TITLE
Odd behavior of `update` from records

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4495]
### Describe the bug

Add a new column from record cells is not work as expected

### How to reproduce

Just run the following cmd:
```nu
echo [[version package]; [0.1.0 {from: 0.0.9, isPatch: $false}] [0.1.1 {from: 0.1.0, isPatch: $true}]] |
    update from-ver {
        get package | each { |pkg|
            echo ($pkg)
            ($pkg.from)
        }
    }
```
will get the following output:
```
╭────────┬───────╮
│ column │ from  │
│ value  │ 0.0.9 │
╰────────┴───────╯
╭────────┬───────╮
│ column │ from  │
│ value  │ 0.1.0 │
╰────────┴───────╯
Error: nu::shell::name_not_found (link)

  × Name not found
   ╭─[tmp/update.nu:4:1]
 4 │             echo ($pkg)
 5 │             ($pkg.from)
   ·                   ──┬─
   ·                     ╰── did you mean 'column'?
 6 │         }
   ╰────
```

### Expected behavior

The expected output should be:
```
╭─────────┬───────╮
│ from    │ 0.0.9 │
│ isPatch │ false │
╰─────────┴───────╯
╭─────────┬───────╮
│ from    │ 0.1.0 │
│ isPatch │ true  │
╰─────────┴───────╯
╭───┬─────────┬───────────────────┬───────────────────╮
│ # │ version │      package      │     from-ver      │
├───┼─────────┼───────────────────┼───────────────────┤
│ 0 │ 0.1.0   │ {record 2 fields} │     0.0.9         │
│ 1 │ 0.1.1   │ {record 2 fields} │     0.1.0         │
╰───┴─────────┴───────────────────┴───────────────────╯
```

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.59.0                                              |
| branch             | main                                                |
| short_commit       | e763a8dc                                            |
| commit_hash        | e763a8dcef25a653bb4ede6a8965bd1f10bc54d5            |
| commit_date        | 2022-02-15 22:36:24 +00:00                          |
| build_os           | macos-x86_64                                        |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)                 |
| rust_channel       | stable-x86_64-apple-darwin                          |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)                 |
| pkg_version        | 0.59.0                                              |
| build_time         | 2022-02-16 09:51:43 +08:00                          |
| build_rust_channel | release                                             |
| features           | dataframe, default, which, zip                      |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by fdncred** [comment]
what if you do what it says? does that give the result you're looking for?

```
echo [[version package]; [0.1.0 {from: 0.0.9, isPatch: $false}] [0.1.1 {from: 0.1.0, isPatch: $true}]] |
    update from-ver {
        get package | each { |pkg|
            echo ($pkg)
            ($pkg.column)
        }
    }
```

**Comment by hustcer** [comment]
> what if you do what it says? does that give the result you're looking for?

No, it's not what I want either, the output is:
```
╭───┬─────────┬───────────────────┬───────────────────╮
│ # │ version │      package      │     from-ver      │
├───┼─────────┼───────────────────┼───────────────────┤
│ 0 │ 0.1.0   │ {record 2 fields} │ {record 2 fields} │
│ 1 │ 0.1.1   │ {record 2 fields} │ {record 2 fields} │
╰───┴─────────┴───────────────────┴───────────────────╯
```
And expected:
```
╭───┬─────────┬───────────────────┬───────────────────╮
│ # │ version │      package      │     from-ver      │
├───┼─────────┼───────────────────┼───────────────────┤
│ 0 │ 0.1.0   │ {record 2 fields} │     0.0.9         │
│ 1 │ 0.1.1   │ {record 2 fields} │     0.1.0         │
╰───┴─────────┴───────────────────┴───────────────────╯
```

**Comment by hustcer** [comment]
If it's not a bug, then how to make it output the expected result?

**Comment by fdncred** [comment]
I'm not sure. I think it's a bug myself.

**Comment by fdncred** [comment]
what about this? ```
echo [[version package]; [0.1.0 {from: 0.0.9, isPatch: $false}] [0.1.1 {from: 0.1.0, isPatch: $true}]] |
  update from-ver {|pkg| 
  $pkg.package.from
}```
is that what you want?

**Comment by hustcer** [comment]
`echo ($pkg)` is for debugging only, `get package | each { |pkg|  ($pkg.column) }` is what I want

**Comment by hustcer** [comment]
> what about this?
> 
> ```
> echo [[version package]; [0.1.0 {from: 0.0.9, isPatch: $false}] [0.1.1 {from: 0.1.0, isPatch: $true}]] |
>   update from-ver {|pkg| 
>   $pkg.package.from
> }
> ```
> 
> is that what you want?

This way really works. Thanks. And I will leave this issue open, as `get package | each { |pkg| ($pkg.from) }` should work too, does it ?

**Comment by jntrnr** [comment]
This is the one I found:

```
> [[version package]; [0.1.0 {from: 0.0.9, isPatch: $false}] [0.1.1 {from: 0.1.0, isPatch: $true}]] | update from-ver { |$it| $it | get package.from }
```

I think the issue with using `each` here is that you're doing `each` over a record, which works differently. There, it's going to iterate over the column names and values of each field in the record.

**Comment by hustcer** [comment]
@jntrnr I see,thanks, I will close it if it's not a bug
