### ISSUE TITLE
Unable to install or build nushell

### ISSUE THREAD

**Issue by smschauhan** [nushell/nushell#450]
![image](https://user-images.githubusercontent.com/1220611/63675914-7d0f6d00-c807-11e9-9f0e-8dc85c554c74.png)

I tried both through `cargo install nu` and `cargo build && cargo run` but can't seem to make the default-run issue go away. 

Any help is appreciated!

**Comment by twe4ked** [comment]
It might be that you're not using nightly rust.

Try: `cargo +nightly install nu`.

See [the installation instructions](https://github.com/nushell/nushell#installation).

**Comment by Akito13** [comment]
@smschauhan You have to install Rust as in shown on the Rust homepage. Then you select "Custom Installation" and install the nightly version. Then you have to make the nightly channel the default channel by running `rustup default nightly`. This will take a couple of minutes. Then try again installing Nu.

**Comment by smschauhan** [comment]
Ok, that fixed it. Thanks guys!

**Comment by Akito13** [comment]
This issue should be closed..
