### ISSUE TITLE
String created from external command output does not preserve colors

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4503]
### Describe the bug

Context here: https://github.com/nushell/nushell/discussions/4477

Seems like running string interpolation from an external does not preserve the colors.

### How to reproduce

1. `nu -c 'ls'`  # nice colors!
2. `$"(nu -c 'ls')"`  # no colors!

### Expected behavior

Both should return the same output.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | d620f76a                                 |
| commit_hash        | d620f76a21161f7661861a0cb936dacaa1bc510b |
| commit_date        | 2022-02-16 19:30:37 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-17 00:19:15 +02:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by jntrnr** [comment]
I'm not sure if we'll be able to keep them through subexpressions unless we change how the metadata thing works. Right now metadata is attached to `PipelineData` but a subexpression becomes a `Value` not `PipelineData`

**Comment by hustcer** [comment]
It's okay, this issue is low priority

**Comment by hustcer** [comment]
This issue was originally brought up by me, but now that there is a workaround, I'm going to close it. BTW: `bash` has the same issue.
