### ISSUE TITLE
Idea: Tagging external programs with marshalling commands

### ISSUE THREAD

**Issue by Vurich** [nushell/nushell#451]
It would be useful to be able to "tag" external programs (using some kind of per-file or per-command metadata) with input-marshalling and output-marshalling shell scripts, so that (for example) `git branch | sort-by name` or `git status | where status == Untracked | git add` do what you'd expect. You could include a standard set of these and/or have them be easy to add manually, like `which some-command | add-input-filter $it { skip 1 | split-by ' | ' }`, for example. This means that external commands could look like internal commands without the hassle of having to write a fully-fledged plugin.

Obviously an alternative is to replace the program entirely with your own script, but this is a far lighter-weight alternative that encourages doing it for any program you need to use, plus it makes it much easier to remove filters where they're unnecessary. Not to mention that since this would only make sense with `nu` itself, replacing the program would essentially confine you to not being able to use any other shell unless you did some crazy `$PATH` shenanigans.

**Comment by eira-fransham** [comment]
Hey @wycats (or whoever else is involved nowadays), I randomly remembered this issue 6 years later, was there ever any work on this? I know a couple of people mentioned it in other issues but I'm out of the loop on Nushell nowadays.
