### ISSUE TITLE
commands without examples

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4518]
### Describe the bug

It would be nice to have at least one example in every command. This is a list of commands without examples. Some of these may not be needed and some may be bogus because I noticed that we have no way to filter out external completion refs.

- [x] alias
- [x] benchmark
- [x] cd
- [x] cp
- [x] date (not needed - it just lists subcommands)
- [x] date list-timezone
- [x] date now
- [x] def
- [x] def-env
- [x] detect columns
- [x] dfr (not needed - it just lists subcommands)
- [x] do
- [x] drop column
- [x] enter
- [x] env
- [x] exit
- [x] export (need a root command)
- [x] export def
- [x] export def-env
- [x] export env
- [x] extern
- [x] from (not needed - it just lists subcommands)
- [x] from tsv
- [x] from yml
- [x] g
- [x] grid
- [x] hash (not needed - it just lists subcommands)
- [x] hide
- [x] history
- [x] into (not needed - it just lists subcommands)
- [x] keybindings (not needed - it just lists subcommands)
- [x] length
- [x] let
- [x] let-env
- [x] lines
- [x] ls
- [x] math (not needed - it just lists subcommands)
- [x] mkdir
- [x] module
- [x] mv
- [x] n
- [x] p
- [x] path (not needed - it just lists subcommands)
- [x] random (not needed - it just lists subcommands)
- [x] register
- [x] reject
- [x] rm
- [x] roll (not needed - it just lists subcommands)
- [x] run-external
- [x] save
- [x] shells
- [x] shuffle
- [x] source
- [x] split (not needed - it just lists subcommands)
- [x] split column
- [x] split row
- [x] str (not needed - it just lists subcommands)
- [x] table
- [x] to (not needed - it just lists subcommands)
- [x] touch
- [x] transpose
- [x] update
- [x] url (not needed - it just lists subcommands)
- [x] use
- [x] view-source
- [x] where
- [x] wrap

### How to reproduce

n/a

### Expected behavior

n/a

### Configuration

|key|value|
|-|-|
|version|0.59.0|
|branch|main|
|short_commit|c7c42772|
|commit_hash|c7c427723bd2a065603cf081391c908b0ff4232d|
|commit_date|2022-02-17 22:23:04 +00:00|
|build_os|macos-aarch64|
|rust_version|rustc 1.58.1 (db9d1b20b 2022-01-20)|
|rust_channel|stable-aarch64-apple-darwin|
|cargo_version|cargo 1.58.0 (f01b232bc 2022-01-19)|
|pkg_version|0.59.0|
|build_time|2022-02-17 18:19:43 -06:00|
|build_rust_channel|debug|
|features|dataframe, default, which, zip|
|installed_plugins|gstat, inc, nu-example-1, nu-example-2, nu-example-3, nu-python, query, query json, query web, query xml|

### Additional context

command used to partially create this list `$scope.commands | where ($it.examples | length) == 0 && is_custom == $false && category != deprecated && is_plugin == $false | get command | str collect (char nl)`

**Comment by hustcer** [comment]
how to test examples？

**Comment by fdncred** [comment]
examples that have a result other than `None` are tested during `cargo test --all --all-features`. I'm not sure there's a way to test one specifically.

**Comment by hustcer** [comment]
I have tried `cargo test --all --all-features` yesterday for `update` command, seems not work

**Comment by fdncred** [comment]
not sure what's going on but I just tested this in the `to md` command and it tests and fails like it should.
```
            Example {
                description: "Outputs an MD string representing the contents of this table",
                example: "[[foo bar]; [1 2]] | to md",
                result: Some(Value::test_string("bob")),
            },
```

```
--- formats::to::md::tests::test_examples stdout ----
input: [[foo bar]; [1 2]] | to md
result: String { val: "|foo|bar|\n|-|-|\n|1|2|\n", span: Span { start: 21, end: 26 } }
done: 294.458µs
input: [[foo bar]; [1 2]] | to md --pretty
result: String { val: "| foo | bar |\n| --- | --- |\n| 1   | 2   |\n", span: Span { start: 47, end: 52 } }
done: 278.625µs
input: [{"H1": "Welcome to Nushell" } [[foo bar]; [1 2]]] | to md --per-element --pretty
result: String { val: "# Welcome to Nushell\n| foo | bar |\n| --- | --- |\n| 1   | 2   |", span: Span { start: 114, end: 119 } }
done: 356.791µs
input: [[foo bar]; [1 2]] | to md
result: String { val: "|foo|bar|\n|-|-|\n|1|2|\n", span: Span { start: 163, end: 168 } }
done: 262.125µs
thread 'formats::to::md::tests::test_examples' panicked at 'the example result is different to expected value: String { val: "|foo|bar|\n|-|-|\n|1|2|\n", span: Span { start: 163, end: 168 } } != String { val: "bob", span: Span { start: 0, end: 0 } }', crates/nu-command/src/example_test.rs:137:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    formats::to::md::tests::test_examples

test result: FAILED. 320 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.11s
```

**Comment by hustcer** [comment]
This PR https://github.com/nushell/nushell/pull/4521 try to add examples for: `alias, date now, where, wrap, exit`

**Comment by hustcer** [comment]
And these commands: `date, export, from, hash, into, keybindings, math, path, random, roll, split, str, to, url` who have sub commands need not have examples, IMO

**Comment by hustcer** [comment]
I will add examples for these commands in two days:
`env, let-env, cp, ls, drop-column, detect-columns, lines, length, benchmark, mkdir, mv, rm, touch, reject, transpose, split column, split row, cd, date list-timezone, def, do`, so others can go on with:
```
╭────┬────────────────────╮
│  0 │ def-env            │
│  1 │ enter              │
│  2 │ export def         │
│  3 │ export def-env     │
│  4 │ export env         │
│  5 │ extern             │
│  6 │ from tsv           │
│  7 │ from yml           │
│  8 │ g                  │
│  9 │ grid               │
│ 10 │ hide               │
│ 11 │ history            │
│ 12 │ module             │
│ 13 │ n                  │
│ 14 │ p                  │
│ 15 │ register           │
│ 16 │ run-external       │
│ 17 │ save               │
│ 18 │ shells             │
│ 19 │ shuffle            │
│ 20 │ source             │
│ 21 │ table              │
│ 22 │ use                │
│ 23 │ view-source        │
╰────┴────────────────────╯
```

**Comment by fdncred** [comment]
> And these commands: `date, export, from, hash, into, keybindings, math, path, random, roll, split, str, to, url` who have sub commands need not have examples, IMO

I generally agree with this except for `export`. I agree that `export` doesn't need examples if it's going to be a root command that just lists it's subcommands. However, it's not even a root command yet. So, there's no help for it whatsoever. I guess I'm saying that we need the normal `export` command so you can do `export --help` and see all the subcommands.

**Comment by fdncred** [comment]
@hustcer with like 100 PRs today. LOL. keep up the good work. we really appreciate your work!

**Comment by fdncred** [comment]
> This PR: #4549 need some help, the example `echo $'c1 c2 c3(char nl)a b c' | detect columns` failed

Just make it `None` please.

**Comment by hustcer** [comment]
@fdncred Okay, It's ready now

**Comment by hustcer** [comment]
@fdncred Don't forget `where`

**Comment by fdncred** [comment]
@hustcer sorry - I missed that one.

**Comment by hustcer** [comment]
I think I can try to add examples for `hide, register, save, source, table, history and shuffle` later
