### ISSUE TITLE
alias not being set correctly if referenced in a custom command

### ISSUE THREAD

**Issue by lukexor** [nushell/nushell#4523]
### Describe the bug

Found an odd thing that referencing an alias in a custom command following the alias definition results in the alias not being mapped correctly,

### How to reproduce

```
alias rm = ^rm -i
def cmd [] {
  rm -f file
}
```

Result: `rm` is not aliased
```
> which rm
╭───┬─────┬──────────────────────────┬─────────╮
│ # │ arg │           path           │ builtin │
├───┼─────┼──────────────────────────┼─────────┤
│ 0 │ rm  │ Nushell built-in command │ true    │
╰───┴─────┴──────────────────────────┴─────────╯
```

Remove custom cmd or move it before the alias and works as expected.

### Expected behavior

Aliases defined should be mapped regardless of execution order of custom commands

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | e1f98c1b                                 |
| commit_hash        | e1f98c1bfd16108e18641ef220090fa101057a77 |
| commit_date        | 2022-02-09 23:20:46 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-15 09:31:33 -08:00               |
| build_rust_channel | release                                  |
| features           | default, which                           |
| installed_plugins  |                                          |

**Comment by jntrnr** [comment]
I'm not able to repro this with a similar example:

```
alias ls = print "done"
def cmd [] {
  ls
}

cmd
```

When I run that as a script, I see "done" printed to the screen.

I'm going to go ahead and close as this may have been fixed, but if you can still repro it, please re-open.
