### ISSUE TITLE
Wrong variable name delimiter

### ISSUE THREAD

**Issue by Diegovsky** [nushell/nushell#4542]
### Describe the bug

It seems nushell is including a slash as a variable name in path expansions.

```
/home/diegovsky> echo $nu.env.HOME/.config
error: Unknown column
  ┌─ shell:7:14
  │
7 │ echo $nu.env.HOME/.config
  │              ^^^^^ did you mean 'HOME'?
```

### How to reproduce

1. Open nushel;
2. Eval a path that has an environment variable embedded (E.x: `echo $nu.env.HOME/.config`);

### Expected behavior

I expected the expansion to not consider the slash as part of the variable name/path.

**Comment by kubouch** [comment]
This is expected behavior. You need to either wrap it in a string interpolation `$"($nu.env.HOME)/.config"` or do `$nu.env.HOME | path join .config`. The second option is probably better since it's cross-platform.

This is a bit different than other shells like bash.
