### ISSUE TITLE
--features=extra may not include trash support

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4562]
### Describe the bug

with `rm_always_trash` set to `true` and I remove a file I get `Cannot execute 'rm'; the current configuration specifies 'rm_always_trash = true', but the current nu executable was not built with feature 'trash_support'`

### How to reproduce

see above

### Expected behavior

remove to trash

### Configuration

|key|value|
|-|-|
|version|0.59.0|
|branch|main|
|short_commit|c7c42772|
|commit_hash|c7c427723bd2a065603cf081391c908b0ff4232d|
|commit_date|2022-02-17 22:23:04 +00:00|
|build_os|macos-aarch64|
|rust_version|rustc 1.58.1 (db9d1b20b 2022-01-20)|
|rust_channel|stable-aarch64-apple-darwin|
|cargo_version|cargo 1.58.0 (f01b232bc 2022-01-19)|
|pkg_version|0.59.0|
|build_time|2022-02-17 18:19:43 -06:00|
|build_rust_channel|debug|
|features|dataframe, default, which, zip|
|installed_plugins|gstat, inc, nu-example-1, nu-example-2, nu-example-3, nu-python, query, query json, query web, query xml|

**Comment by jntrnr** [comment]
should be fixed now
