### ISSUE TITLE
Autocomplete is hard to use in the new nushell

### ISSUE THREAD

**Issue by aminya** [nushell/nushell#4574]
### Describe the bug

In the new shell, the autocomplete has changed to require one extra "Enter". Unlike other programs that only hitting "Tab" completes the paths, now, an extra "Enter" is required for nushell.

### How to reproduce

Try to cd to a folder without typing its full name and pressing enter

### Expected behavior

Tab should autocomplete 

### Screenshots

![image](https://user-images.githubusercontent.com/16418197/154870698-d4114332-81ca-4f38-ae1f-049d26cadf14.png)

### Configuration

╭────────────────────┬──────────────────────────────────────────╮
│ version            │ 0.59.0                                   │
│ branch             │ main                                     │
│ short_commit       │ 0256e42e                                 │
│ commit_hash        │ 0256e42e3b752109a0578abd9a21c9deb19bf815 │
│ commit_date        │ 2022-02-12 14:14:17 +00:00               │
│ build_os           │ windows-x86_64                           │
│ rust_version       │ rustc 1.58.1 (db9d1b20b 2022-01-20)      │
│ rust_channel       │ stable-x86_64-pc-windows-msvc            │
│ cargo_version      │ cargo 1.58.0 (f01b232bc 2022-01-19)      │
│ pkg_version        │ 0.59.0                                   │
│ build_time         │ 2022-02-12 14:41:11 +00:00               │
│ build_rust_channel │ release                                  │
│ features           │ dataframe, default, which, zip           │
│ installed_plugins  │                                          │
╰────────────────────┴──────────────────────────────────────────╯

**Comment by jntrnr** [comment]
@aminya - in the latest main, we have quick completions turned on. If you hit tab and start typing enough to get down to a single item, it will auto-select it for you.

We may need to make completions case-sensitive (or configurable to make them case-sensitive)

**Comment by aminya** [comment]
Oh, OK. I used the latest Release draft binaries available here:
https://github.com/nushell/nushell/actions/workflows/release.yml

I'll wait for new binaries.

**Comment by WindSoilder** [comment]
> If you hit tab and start typing enough to get down to a single item, it will auto-select it for you.

It may be better that when I hit tab in selected item, the item still auto-complete to my input, and when I tab other item, it auto-complete other item.

**Comment by aminya** [comment]
Closing it since it is fixed on master
