### ISSUE TITLE
Table layout breaks on link in text

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#4578]
### Describe the bug

I'm noticing an issue with rendering on https://github.com/nushell/nushell/commit/a96f8b891e148d0deb37fa760323345acdc6dd4f. If you `fetch` the metadata for [this issue](https://github.com/nushell/nushell/releases/tag/0.44.0), the first link present in the body text does not completely show up and the border of the table breaks.

### How to reproduce

1. Run `fetch https://api.github.com/repos/nushell/nushell/releases/58955739`
2. Observe table layout broken on `body` property

### Expected behavior

I expect all of the following text to be visible inside the boundaries of the table:

```
This is the 0.44.0 release of Nushell. You can learn more about this release here: https://www.nushell.sh/blog/2022-02-08-nushell_0_44.html

For convenience, we are providing full builds for Windows, Linux, and macOS. These are the "all extra features" builds, so be sure you have the requirements to enable all capabilities: https://www.nushell.sh/book/installation.html#dependencies
```

### Screenshots

![image](https://user-images.githubusercontent.com/26268125/154907758-e82d99fa-fd00-4f09-946a-9dbd26c65670.png)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | a96f8b89                                 |
| commit_hash        | a96f8b891e148d0deb37fa760323345acdc6dd4f |
| commit_date        | 2022-02-21 03:31:50 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-20 22:31:49 -08:00               |
| build_rust_channel | debug                                    |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

### Additional context

OS: Debian on Windows 11 (WSL2).
Terminal: Windows Terminal Preview v1.13.10395.0

**Comment by fdncred** [comment]
I think it's actually there but not rendering right. Can you try this `fetch https://api.github.com/repos/nushell/nushell/releases/58955739 | get body`?

@jntrnr any ideas about this? it's a bit weird.

**Comment by rgwood** [comment]
That seems OK:
![image](https://user-images.githubusercontent.com/26268125/154991489-a1a16f1c-5d53-4631-9aed-89508d23e088.png)

**Comment by jntrnr** [comment]
Seems like there are a few places we need to do some cleaning in nu-table so that cells can display correctly. We know already that the tab character and the carriage return character both cause issues. Maybe there's a similar thing going on here with the url?

@rgwood looks like that's the case. Was looking at the binary to see what it might be:

```
00001f20:   66 20 4e 75  73 68 65 6c  6c 2e 20 59  6f 75 20 63   f Nushell. You c
00001f30:   61 6e 20 6c  65 61 72 6e  20 6d 6f 72  65 20 61 62   an learn more ab
00001f40:   6f 75 74 20  74 68 69 73  20 72 65 6c  65 61 73 65   out this release
00001f50:   20 68 65 72  65 3a 20 68  74 74 70 73  3a 2f 2f 77    here: https://w
00001f60:   77 77 2e 6e  75 73 68 65  6c 6c 2e 73  68 2f 62 6c   ww.nushell.sh/bl
00001f70:   6f 67 2f 32  30 32 32 2d  30 32 2d 30  38 2d 6e 75   og/2022-02-08-nu
00001f80:   73 68 65 6c  6c 5f 30 5f  34 34 2e 68  74 6d 6c 5c   shell_0_44.html\
00001f90:   72 5c 6e 5c  72 5c 6e 46  6f 72 20 63  6f 6e 76 65   r\n\r\nFor conve
00001fa0:   6e 69 65 6e  63 65 2c 20  77 65 20 61  72 65 20 70   nience, we are p
```

**Comment by jntrnr** [comment]
I'll work on a PR to see if we can clean up the cell data before we try to use it.
