### ISSUE TITLE
Command `7z b` does not work

### ISSUE THREAD

**Issue by lucatrv** [nushell/nushell#4593]
### Describe the bug

As in subject, I guess it's due to the whitespace character.

### How to reproduce

Enter command `7z b`

### Expected behavior

Start 7zip benchmark

**Comment by fdncred** [comment]
What is the error you get? is 7zip in your path?

**Comment by jntrnr** [comment]
@fdncred - I think it's from the number parser thinking `7z` is a number. We probably need more graceful fall-through

**Comment by fdncred** [comment]
i was thinking that too but since it was `7z` i thought it might not mistake it.

**Comment by fdncred** [comment]
What about `^7z b` does that work for you @lucatrv ?

**Comment by lucatrv** [comment]
> What is the error you get? is 7zip in your path?

Yes 7zip is in my path, and `7z b` works as expected in Bash, Zsh, Fish.

I get the following error:

```
error: Type Error
   ┌─ shell:39:4
   │
39 │ 7z b
   │    ^ Expected operator, found b
```

**Comment by lucatrv** [comment]
> What about `^7z b` does that work for you @lucatrv ? The `^` tells nushell that this is an external.

`^7z b` works fine.
