### ISSUE TITLE
Strings are not passed as they are to externals

### ISSUE THREAD

**Issue by elferherrera** [nushell/nushell#4601]
### Describe the bug

The next command errors because the string after the filter is not passed as it is
```
gcloud dataproc jobs list --region europe-west1 --limit=50 --filter="labels.table_name=vagabond_tranches" --sort-by="statusHistory[0].stateStartTime"
```

The error received from the external is this one
```
ERROR: (gcloud.dataproc.jobs.list) INVALID_ARGUMENT: Could not parse the filter: Unexpected property ''. Expected one of [labels, clusterName, placement.clusterName, status.state, operationType]
```

### How to reproduce

run external command that requires an argument with string

### Expected behavior

The string is passed correctly to the argument

**Comment by elferherrera** [comment]
It seems this is not related to nushell but to rust itself

This [issue](https://github.com/rust-lang/rust/issues/29494) describes it and there is a nightly [feature](https://doc.rust-lang.org/nightly/std/process/struct.Command.html#method.raw_arg) waiting for approval.

I'm closing this issue but leaving this for future reference

**Comment by jntrnr** [comment]
Let's leave this open and tag it `upstream`. We may have to work with the Rust teams to help finish it.

**Comment by jntrnr** [comment]
@elferherrera - the issue you linked to is marked Windows-specific. Seems like it would fix the issue you saw on Windows, but you originally saw it on macOS too right?

**Comment by elferherrera** [comment]
I see the issue with externals in MacOS and Windows operating system. I linked to that issue for reference with scaped quotes

**Comment by JCallicoat** [comment]
I just found in a another issue that nu seems to be passing the double quotes literally to external commands that have flags with an `=` (https://github.com/nushell/nushell/issues/4609#issuecomment-1054940285) which seems like it could be related. Could you try your command with spaces on those flags instead of equals, i.e., `--filter "labels.table_name=vagabond_tranches" --sort-by "statusHistory[0].stateStartTime"` and see if it works?

**Comment by JCallicoat** [comment]
Simple reproducer to show the quotes being passed through to the command:

```c
// foo.c
#include <stdio.h>
int main(int argc, char **argv) {
    for (int i=1; i < argc; i++) {
        puts(argv[i]);
    }
}
```
```
gcc -o foo foo.c

./foo --filter="labels.table_name=vagabond_tranches"
--filter="labels.table_name=vagabond_tranches"
```

Compared to zsh:

```
./foo --filter="labels.table_name=vagabond_tranches"
--filter=labels.table_name=vagabond_tranches
```

**Comment by elferherrera** [comment]
@JCallicoat I can confirm that by adding a space the external command works

**Comment by fdncred** [comment]
> Should we add a config flag that removes quotes from arguments to externals to behave like bash?

imo, passing arguments to externals should "just work". we continually have issues with it. I'd like to resolve it once and for all. I'm not sure what that resolution looks like though.

**Comment by fdncred** [comment]
I'm willing to try just about anything in order to quit having complaints about external parameters not working.
