### ISSUE TITLE
External command output been swallowed when called from a custom command

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4608]
### Describe the bug

External command output been swallowed when called from a custom command. I'm not sure whether it's by design or a bug.

### How to reproduce

1. Create a script `foo.nu` in a git repo with the following content:
```nu
def push-repo [] { git push origin main:feature/foo }; push-repo
```
2. Run `nu foo.nu`, the repo pushed to remote successfully with nothing output
3. Change the above script to:
```nu
def push-repo [] { print (git push origin main:feature/foo) }; push-repo
```
4. And run again will get output like this:
```
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote:
remote: Create a pull request for 'feature/ab2' on GitHub by visiting:
remote:      https://github.com/hustcer/nushell/pull/new/feature/ab2
remote:
To github.com:hustcer/nushell.git
 * [new branch]        main -> feature/ab2
 
```

### Expected behavior

**The external command execution without any output is not friendly enough for a novice**

`def push-repo [] { git push origin main:feature/foo }; push-repo` should have the same output as `def push-repo [] { print (git push origin main:feature/foo) }; push-repo`

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.59.0                                              |
| branch             | main                                                |
| short_commit       | 9888f8f2                                            |
| commit_hash        | 9888f8f298e18ca60e713637914014d8767e077c            |
| commit_date        | 2022-02-21 22:22:21 +00:00                          |
| build_os           | macos-x86_64                                        |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)                 |
| rust_channel       | stable-x86_64-apple-darwin                          |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)                 |
| pkg_version        | 0.59.0                                              |
| build_time         | 2022-02-22 09:51:58 +08:00                          |
| build_rust_channel | release                                             |
| features           | dataframe, default, trash, which, zip               |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by jntrnr** [comment]
Hmm, here's what I see for a similar command:

```
> def get-git-status [] { git status }; get-git-status | str length
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	flamegraph.svg
	greet.nu
	perf.data
	perf.data.old
	prin.nu
	what[foo].txt

nothing added to commit but untracked files present (use "git add" to track)
0
```

I don't see any redirection at all. It seems like the external runs and nothing is sent out the pipe (which is the 0 string length at the end)

**Comment by hustcer** [comment]
Don't use `git status` use `git push` like `def push-repo [] { git push origin main:feature/foo }; push-repo`
`git status`  works well for me too, It runs locally and fast, where as `git push` is more time consuming

**Comment by hustcer** [comment]
I have met lots of such git related issue recently, the scripts works before, but failed recently, maybe after this PR:
https://github.com/nushell/nushell/pull/4594 . I have to wrap them in `print ()` to make them work as expected.

**Comment by lukexor** [comment]
I'm not sure what git is doing behind the scenes with it's push output, but echo works fine for both stderr and stdout:

```
def bash-stderr [] { bash -c "echo This message goes to stderr >&2" }
def bash-stdout [] { bash -c "echo This message goes to stdout" }

[15:11] v0.59.0 ❯ bash-stderr
This message goes to stderr

[15:11] v0.59.0 ❯ bash-stdout
This message goes to stdout

```

**Comment by hustcer** [comment]
Will this issue be fixed before 0.60 beta release?

**Comment by jntrnr** [comment]
We have a slightly different way of handling this now, using the new `complete` command:

```
> def bash-stdout [] { do -i { bash -c "echo This message goes to stdout" } | complete }; bash-stdout
╭───────────┬─────────────────────────────╮
│ stdout    │ This message goes to stdout │
│ stderr    │                             │
│ exit_code │ 0                           │
╰───────────┴─────────────────────────────╯

> def bash-stderr [] { do -i { bash -c "echo This message goes to stderr >&2" } | complete }; bash-stderr
╭───────────┬─────────────────────────────╮
│ stdout    │                             │
│ stderr    │ This message goes to stderr │
│ exit_code │ 0                           │
╰───────────┴─────────────────────────────╯
```

**Comment by hustcer** [comment]
This issue was fixed on the latest main
