### ISSUE TITLE
`rm` cannot remove broken symlink

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4611]
### Describe the bug

If symlink points to an invalid location it cannot be removed.

### How to reproduce

1. `touch foo.txt`
2. `ln -s foo.txt symlink-to-foo.txt`
3. `rm foo.txt`
4. `rm ./symlink-to-foo.txt`

### Expected behavior

Should remove the broken symlink.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | 41fa1ab6                                 |
| commit_hash        | 41fa1ab6561e7bd048f3705628546e18a5a026b1 |
| commit_date        | 2022-02-21 15:46:19 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-21 17:46:48 +02:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | gstat                                    |

**Comment by hustcer** [comment]
Related Issue: https://github.com/nushell/nushell/issues/3977

**Comment by jntrnr** [comment]
duplicated of #3977
