### ISSUE TITLE
nushell doesn't see modified PATH

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4613]
### Describe the bug

This is taken from #4606 to track this issue.

This may be unrelated to #4606 but when I was trying to test it on Windows, I couldn't get it to work. Here's my process.

1. 7z.exe is not in my path so i need to add it. I did `let-env PATH = ($env.PATH | append "C:\Apps\7-zip")`
2. do `$env.PATH` to make sure `c:\apps\7-zip` is in there, and it is.
3. do `which 7z` - returns nothing.
4. do `which 7z.exe` - returns nothing.
5. do `7z b` - gives an error
6. do `7z` - prints out 7z.

my diagnosis, is that maybe this PR is not the problem, but I can't really tell since i cannot access new additions to my path.

This also could be something I'm doing wrong, but I can't see what it is right now.

UPDATE: I tested on my Mac with commit c7c42772 and it seems to work fine.

### How to reproduce

see above

### Expected behavior

the ability to append folders to the path and nushell be able to find executables within that new addition to the path.

### Configuration

I'll update this in a little while when I'm back on windows.

**Comment by jntrnr** [comment]
This could be a dupe of https://github.com/nushell/nushell/issues/4299

**Comment by kubouch** [comment]
Yeah, could be. I'll try to fix `which` as soon as I get the chance.

**Comment by fdncred** [comment]
i added `which_in` and `which_in_all` in a test branch and found out that it makes `which` work better. semi-related we still have to update `external_exception` to execute things like `7z` based on this pr https://github.com/nushell/nushell/pull/4606

**Comment by fdncred** [comment]
This now works after JT's PRs to support it.

**Comment by kubouch** [comment]
@fdncred Can you check if this PR fixes it? #4690

**Comment by fdncred** [comment]
@kubouch after i did a `git merge main` on your #4690 and rebuilt, it fixes this issue. good work!

**Comment by fdncred** [comment]
this is fixed.
