### ISSUE TITLE
Can't run some commands Ex 7zip: Expected operator, found a

### ISSUE THREAD

**Issue by pragmaticmero** [nushell/nushell#4616]
### Describe the bug

Can't run some commands that otherwise I can with bash, 7zip is the best example of this bug.

### How to reproduce

1. Install Nushell
`$ sudo pacman -S nushell`
2. Install p7zip
`$ sudo pacman -S p7zip`
3. Enter Nushell
`$ nu`
4. Try to compress a file in 7z format
`$ 7z a -t7z file.7z file.txt`

### Expected behavior

I expected to.... you know.... COMPRESS THE FILE
Instead it give this error
```
$ 7z a -t7z pene.7z pene.txt
error: Type Error
   ┌─ shell:16:4
   │
16 │ 7z a -t7z pene.7z pene.txt
   │    ^ Expected operator, found a
```

And when I write it in the terminal, the words "a" and "pene.7z" appear with red color highlighted.
Why this error happens?
I've had this bug for 5 months ago when I was trying shells. It was never fixed I imagine. 
This bug also happens with some other commands with "unconventional" flag/parameter systems.

### Configuration

I'm using Arch Linux 64-Bit

### Additional context

A solution would be to just use bash, the command runs there, but I really want to try this shell, its rust based, that's the best selling point for me.
Other solution that i've found is to write:
`$ ^7z a -t7z pene.7z pene.txt`
But why is that? I need an explanation

**Comment by jntrnr** [comment]
This is fixed in the latest main
