### ISSUE TITLE
Custom Login Startup Script

### ISSUE THREAD

**Issue by glossnyx** [nushell/nushell#4620]
### Describe the solution you'd like

It would be really useful if you could specify a custom startup script to run for a login shell.

### Describe alternatives you've considered

A way of checking if the current shell is a login shell would also work and may be preferrable.

**Comment by jntrnr** [comment]
This is possible now in the latest main with the `--config` flag.

**Comment by glossnyx** [comment]
Thanks for the quick response! Unfortunately this doesn't work in my case since I don't know of any way to pass arguments to the login shell (pretty sure it's not possible).

**Comment by jntrnr** [comment]
ahh, maybe we need a `login.nu` that's run when in `-l` mode.

**Comment by sec65** [comment]
Can I take this one? I'm new to the project, but I would give it a try.
