### ISSUE TITLE
Unexpected behavior of `empty? -b`

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4634]
### Describe the bug

Unexpected behavior of `empty? -b`

### How to reproduce

Run `echo [[version count]; [0.1.0 1] [0.1.1 $nothing]] | empty? count -b { |_| 3 }`
in v0.44 will get:
```
  #   version   count
───────────────────────
  0   0.1.0         1
  1   0.1.1         3
```
And in v0.59 will get:
```
  #   version   count
───────────────────────
  0   0.1.0     true
  1   0.1.1         3
```

### Expected behavior

```
  #   version   count
───────────────────────
  0   0.1.0         1
  1   0.1.1         3
```

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.59.0                                              |
| branch             | main                                                |
| short_commit       | 3c62d27c                                            |
| commit_hash        | 3c62d27c280dd7a7ba276760c239bfaa1b5080cd            |
| commit_date        | 2022-02-24 19:02:28 +00:00                          |
| build_os           | macos-x86_64                                        |
| rust_version       | rustc 1.58.1 (db9d1b20b 2022-01-20)                 |
| rust_channel       | stable-x86_64-apple-darwin                          |
| cargo_version      | cargo 1.58.0 (f01b232bc 2022-01-19)                 |
| pkg_version        | 0.59.0                                              |
| build_time         | 2022-02-25 09:46:17 +08:00                          |
| build_rust_channel | release                                             |
| features           | dataframe, default, trash, which, zip               |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by fdncred** [comment]
agreed. I mentioned this same thing here https://github.com/nushell/nushell/issues/4314 but I hadn't filed an issue yet. thanks!
