### ISSUE TITLE
Need better Windows paths for default config creation

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#4642]
### Describe the bug

![image](https://user-images.githubusercontent.com/547158/155749543-58ab02da-3d76-4362-853e-21be64043a22.png)

### How to reproduce

1. Start up nu fresh on Windows
2. See the above when you create a new config

### Expected behavior

Should show the correct Windows paths

**Comment by fdncred** [comment]
Are you saying you don't like the location or the `\\`?

**Comment by elferherrera** [comment]
I am wondering the same. What is the error? That has been my path in eq

**Comment by jntrnr** [comment]
Sorry, I meant the `\\`. It should just be `\`

**Comment by fdncred** [comment]
got it. i'll fix this real quick.
