### ISSUE TITLE
Support tab indentation in commands like `to json`.

### ISSUE THREAD

**Issue by zkldi** [nushell/nushell#4644]
### Related problem

At the moment the only indentation option for output is spaces. This is useful, but I am personally an advocate for tabs for [Accessibility Reasons](https://old.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/).

As such, files in projects I work on are typically tab-indented, so doing something like `open package.json | update name "foobar" | save out.json` results in forced 2space indentation, and `open package.json | update name "foobar" | to json -i 4 | save --raw out.json` while less convenient, only lets me control how many spaces are output.

### Describe the solution you'd like

`to json` (and co.) could take a third flag, `-t --tabs`, which would specify to indent with exactly one tab.

This flag would be incompatible with `-i`, as the two cannot reasonably be applied at the same time. I'm not sure if there is a way for the typesystem to display mutual exclusion like this.

### Additional context and details

It's possible that the API for `save` might just be inconvenient in general for saving indentations, since it seems to force 2 space indentation on the happy path (without using `--raw`). Maybe there should be a way to specify formatting somehow? That would be a separate issue, though.

Thanks.

**Comment by fdncred** [comment]
understood. seems like a reasonable request. i'm sure we'd accept a pr for such a change.

**Comment by zkldi** [comment]
Looks like this is fixed in #4705.
