### ISSUE TITLE
Up- and Down- Arrow should consider entered text

### ISSUE THREAD

**Issue by Flare576** [nushell/nushell#465]
When I type in a partial command and press ⬆️, I expect to only see historical commands starting with my partial. Example:

```
> cd /a/really/long/path
> ls
> cd /another/really/long/path
> ls
> cd /a/ ⬆️
```

I'd expect the line to now have `cd /a/really/long/path`, but it actually has `ls`

**Comment by Porges** [comment]
This will be a feature for `rustyline`.

**Comment by oberien** [comment]
Is there an update on this? I'm very used to typing the beginning of a command and using arrow-up a few times to find a command in my history from the zsh feature and would love to see it in nushell.

If you can give me some hints I'm willing to implement this feature and create a PR.

**Comment by jonathandturner** [comment]
@oberien - we currently use https://github.com/kkawakam/rustyline to do our line editing. If it gets implemented there, we should be able to add it nushell.  You might want to file an issue on that repo and see if it's being worked on. The bonus is that other people using rustyline would also benefit.

**Comment by deathtrip** [comment]
Why won't they accept the pull request?
Maybe nu should (temporarily?) switch to a rustyline fork.

**Comment by taylorthurlow** [comment]
!notstale

**Comment by Porges** [comment]
This is not stale.

**Comment by vishhvaan** [comment]
> I have slightly different case, where I'd like arrow up to match commands that contain the text I've entered, not just commands that start with the text. e.g. when I enter `rebuild`, then press arrow up, I'd expect it to match `sudo nixos-rebuild switch` from my history.
> 
> I'm currently running nushell 0.71.0, but I also couldn't find any mention of this feature in any following release notes.

This would be useful
