### ISSUE TITLE
`export --help` not work

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4653]
### Describe the bug

`export --help` not work

### How to reproduce

```
$> export --help
Error: nu::parser::unexpected_keyword (link)

  × Unexpected keyword.
   ╭─[entry #27:1:1]
 1 │ export --help
   · ───┬──
   ·    ╰── unexpected export
   ╰────
  help: 'export' keyword is allowed only in a module.
```

### Expected behavior

Output should be the same as `help export`

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | 11bc0565                                 |
| commit_hash        | 11bc056576485f6f8b427fd21adc5d777add6573 |
| commit_date        | 2022-02-26 09:19:19 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-02-26 18:34:28 +08:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | query, query json, query web, query xml  |

**Comment by fdncred** [comment]
it looks like it's coming from `UnexpectedKeyword`

**Comment by nyurik** [comment]
same with `alias --help`

**Comment by fdncred** [comment]
try `help alias` and `help export`

**Comment by nyurik** [comment]
> try `help alias` and `help export`

Yes, those work, and they say that --help is a valid parameter :)
