### ISSUE TITLE
Remember Last Command

### ISSUE THREAD

**Issue by provjeremys** [nushell/nushell#466]
Very similar to #378, but I noticed that some of the commands from the docs get very long, e.g.

```
> open people.txt | lines | split-column " | " first_name last_name job | sort-by first_name
```

A `remember` command would be great, and due to the chaining, having it either interactive or command-driven would help. (for example, I may only want to save off `| lines | split-column " | " first_name last_name job` as 'parseFirstLastJob` for reuse)

**Comment by jedahan** [comment]
if name is required, why not make it the first argument and get rid of the `-n` option?

how do you feel about being able to pipe to remember as in `my | long | command | remember myLongCommand` ?

Is there a chance of remember randomly generating names for you? Or would you need some magic like `my | long | command | remember {myCoolNameGenerator}`

**Comment by jedahan** [comment]
Yeah I was wondering if the stdmeta or whatever it’s called shares the currently constructed pipe, which could enable ‘| remember’. Otherwise remember becomes something like ‘alias somefunction=“$$”’ (which is still awesome and helpful).
