### ISSUE TITLE
`do` command does not pass rest arguments to the passed block

### ISSUE THREAD

**Issue by andrasio** [nushell/nushell#4660]
### Describe the bug

The help information for `do` states that the rest arguments to it will be passed to the block parameter.

`do block ...rest`

I'm not sure how to use the arguments passed from the block. I'd expect this to work (unless I'm missing something)

### How to reproduce

```
do {|text| echo $text} "hola"
```

### Expected behavior

```
do {|text| echo $text} "hola"
```

should print in the screen `hola`

**Comment by fdncred** [comment]
related https://github.com/nushell/nushell/issues/4522

**Comment by jntrnr** [comment]
This one is going to need a bit more work in the type system. Right now there isn't a way to say "a block with an arbitrary signature" that gets filled in later. All the other commands already know how many parameters they need, and we want to check those.

```
do {|text| echo $text} "hola"                                                                                                                                 03/04/2022 11:47:25 AM
Error: nu::parser::parse_mismatch (link)

  × Parse mismatch during operation.
   ╭─[entry #1:1:1]
 1 │ do {|text| echo $text} "hola"
   ·     ───┬──
   ·        ╰── expected 0 block parameter
   ╰────
```
