### ISSUE TITLE
Zfs replication fails due to checksum error

### ISSUE THREAD

**Issue by ludsoft** [nushell/nushell#4679]
Hi, 

I've tried replicating a zfs pool in nu shell. Here is the command:
`sudo zfs send -v poolname/dataset@snapshot | sudo zfs -sF recv otherpoolname`

It starts working but stops after some time saying that there is a snapshot mismatch. 
I've tried it almost 20 times with different hard drives and pools, it always fails. Some time after 15 minutes et roughly 100 GB replicated, sometime after 7s and less than 1 GB replicated. 

Trying the same in bash worked flawlessly so I'm tempted to think that nushell was the issue. 

My pool is a small one (1TB). 

I'm only raising this issue for what it could mean for the | operator. If ZFS is raising a checksum error, would that mean some bytes are changed by it? Shoudn't I use this operator as nushell is treating it differently from what I'm used in bash / zsh?

Anyway, thanks for all the work, nu is quite fun to use and anything that can keep moving the command line forward is a great initiative.

**Comment by jntrnr** [comment]
Thanks for the bug report - I'm definitely curious what might be causing it.

Can you fill out the issue template that the repo provides? It helps us debug the issue and includes things like what nushell version, which build, OS, etc that you're using.

**Comment by hustcer** [comment]
@ludsoft Can you try it again with the latest nu release and add more information? Thanks

**Comment by hustcer** [comment]
Due to insufficient information about this issue, we will close it now. If you still have such issue please add more detail and reopen it, sorry for the inconvenience.

**Comment by ludsoft** [comment]
Hi, Sorry for lacking time to reproduce this with additional information. 
I'll retry with the latest version and revert (at some point...). I'll reopen the issue if I still have it.  
Thanks!
