### ISSUE TITLE
decode: Command not found

### ISSUE THREAD

**Issue by jnlmmln** [nushell/nushell#4685]
### Describe the bug

Hi everybody,
I was following the coloring and theming guide and tried setting up `LS_COLOR`.
https://github.com/nushell/nushell/blob/main/docs/How_To_Coloring_and_Theming.md#ls_colors-colors-for-the-ls-command

Unfortunately the decode command seems to be missing:
```
> let-env LS_COLORS = (vivid generate molokai | decode utf-8 | str trim)
error: Command not found
   ┌─ shell:78:47
   │
78 │ let-env LS_COLORS = (vivid generate molokai | decode utf-8 | str trim)
   │                                               ^^^^^^ command decode not found
   ```
   
   Is `decode` an external command, which I have to install?
   If yes why is it then listed as [command](https://www.nushell.sh/book/commands/decode.html)?

Do I use the wrong documentation?

### How to reproduce

1. Install vivid: `cargo install vivid`
2. Run: `let-env LS_COLORS = (vivid generate molokai | decode utf-8 | str trim)`

### Expected behavior

The command executes and sets the LS_COLORS env variable.

### Configuration

> version | rotate counter-clockwise key value | reverse | to md --pretty

| key                | value                                                  |
| ------------------ | ------------------------------------------------------ |
| version            | 0.44.0                                                 |
| build_os           | linux-x86_64                                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)                    |
| rust_channel       | stable-x86_64-unknown-linux-gnu                        |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)                    |
| pkg_version        | 0.44.0                                                 |
| build_time         | 2022-02-26 00:34:27 +01:00                             |
| build_rust_channel | release                                                |
| features           | ctrlc, dataframe, default, rustyline, term, which, zip |
| installed_plugins  | fetch, match, post, ps, sys                            |

### Additional context

While getting the configuration information I recognised that the `transpose` command was also not found.

**Comment by hustcer** [comment]
You are configuring the old nu v0.44 according to the latest doc which is for nu 0.59

**Comment by jnlmmln** [comment]
Ahh got it, thank you for the quick response.
