### ISSUE TITLE
`ls ~ | path relative-to ~ -c [name]` does not work as expected

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4686]
### Describe the bug

`ls ~ | path relative-to ~ -c [name]` does not work as expected

### How to reproduce

Run `ls ~ | path relative-to ~ -c [name]` in nu v0.59 will get:
```
  #                                        name                                        type     size      modified
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   0   CantConvert("prefix not found", "string", Span { start: 18357, end: 18359 })   dir         320   2 weeks ago
   1   CantConvert("prefix not found", "string", Span { start: 18357, end: 18359 })   dir         192   a day ago
   2   CantConvert("prefix not found", "string", Span { start: 18357, end: 18359 })   dir         768   2 months ago
   3   CantConvert("prefix not found", "string", Span { start: 18357, end: 18359 })   dir       3,616   9 hours ago
```

### Expected behavior

Should work as it does in nu v0.44

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | a6a96b29                                 |
| commit_hash        | a6a96b29cbadf42e2fb0908e71947689e8861669 |
| commit_date        | 2022-02-28 23:31:53 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-03-01 09:46:51 +08:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | query, query json, query web, query xml  |

**Comment by hustcer** [comment]
Closing, same as https://github.com/nushell/nushell/issues/5202

**Comment by fdncred** [comment]
LOL - we opened the same issue. sorry.

**Comment by hustcer** [comment]
> LOL - we opened the same issue. sorry.

Never mind, I forgot about it too
