### ISSUE TITLE
Plugin names are different on mac and Windows

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4692]
### Describe the bug

Plugin names are different on mac and Windows
On windows:
nu_plugin_example.exe
nu_plugin_gstat.exe
nu_plugin_query.exe
nu_plugin_inc.exe

On Mac:
nu_plugin_core_example
nu_plugin_extra_gstat
nu_plugin_extra_query
nu_plugin_core_inc

### How to reproduce

Check the bin dir

### Expected behavior

The plugin names should be:
nu_plugin_core_example.exe
nu_plugin_extra_gstat.exe
nu_plugin_extra_query.exe
nu_plugin_core_inc.exe
On windows 

### Configuration

| key                | value                                    |                                                                                                          
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | 42f1874a                                 |
| commit_hash        | 42f1874a3aae2e3bc3c669cb0aac0132a586ea24 |
| commit_date        | 2022-03-01 13:05:29 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-03-01 13:52:36 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I think the windows names look better to me. I'm not sure why they're different but I assume it's because we're compiling them twice to make all the bins properly due to cargo limitations.

**Comment by jntrnr** [comment]
Should be fixed with #4719
