### ISSUE TITLE
Plugin register failed on windows

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4693]
### Describe the bug

Plugin register failed on windows

### How to reproduce

1. Run `register -e capnp "C:\Program Files\nu\bin\nu_plugin_extra_query.exe"` will get output:
```console
Error: nu::parser::file_not_found (https://docs.rs/nu-parser/0.59.0/nu-parser/enum.ParseError.html#variant.FileNotFound)

  × File not found
   ╭─[entry #23:1:1]
 1 │ register -e capnp "C:\Program Files\nu\bin\nu_plugin_extra_query.exe"
   ·                   ─────────────────────────┬─────────────────────────
   ·                                            ╰── File not found: "C:\Program Files\nu\bin\nu_plugin_extra_query.exe"
   ╰────

```
2. Actually the plugin file exists:
Run `ls "C:\Program Files\nu\bin\nu_plugin_extra_query.exe"` will get:
```
╭───┬───────────────────────────────────────────────────┬──────┬─────────┬──────────────╮
│ # │                       name                        │ type │  size   │   modified   │
├───┼───────────────────────────────────────────────────┼──────┼─────────┼──────────────┤
│ 0 │ C:\Program Files\nu\bin\nu_plugin_extra_query.exe │ file │ 1.6 MiB │ 19 hours ago │
╰───┴───────────────────────────────────────────────────┴──────┴─────────┴──────────────╯
```

### Expected behavior

Plugin register should work on windows

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |                                                                                                          
| version            | 0.59.0                                   |                                                                                                
| branch             | main                                     |
| short_commit       | 42f1874a                                 |
| commit_hash        | 42f1874a3aae2e3bc3c669cb0aac0132a586ea24 |
| commit_date        | 2022-03-01 13:05:29 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-03-01 13:52:36 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by hustcer** [comment]
It seems to be caused by the quotes around `C:\Program Files\nu\bin\nu_plugin_extra_query.exe`, but there is a space in the path, how to do with it?

**Comment by jntrnr** [comment]
I think we should change the parser to be able to handle the quotes when doing `register`

**Comment by fdncred** [comment]
@hustcer I think a work-around is to cd to that directory and register the plugins from there.
