### ISSUE TITLE
date now evaluates to "now"

### ISSUE THREAD

**Issue by efx** [nushell/nushell#4698]
### Describe the bug

`date now` prints out a literal "now" value instead of the current date.

### How to reproduce

1. `date now`

### Expected behavior

I expect it to print the full date.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | 88d7b50e                                 |
| commit_hash        | 88d7b50e378d074e9d6003db0a8c9b4c02d5b182 |
| commit_date        | 2022-03-02 12:52:24 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-02 13:00:29 -05:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by efx** [comment]
Might relate to changes in #4661.

**Comment by jmoore34** [comment]
This happens because `autoview` for DateTime gives the same output as `date humanize`. Perhaps this could be changed or made customizable (#3735). 

As a workaround, you can do `date now | date format` or simply `date format`.

**Comment by stormasm** [comment]
I have seen this as well, it has been "broken" now for a week or two, not exactly sure how long....

**Comment by jntrnr** [comment]
yeah, we could make it output the RFC3339 format if used as a value by itself maybe?  I like the human format for tables like `ls` but as a single value I agree it can be confusing that the thing you're looking at is actually a date

**Comment by jmoore34** [comment]
Perhaps it could display both, e.g. `Wed, 02 Mar 2022 14:42:37 -0600 (now)`.

I was also thinking it might be cool to be able to provide a block in the config that determines how it displays, that way the user could also tweak the locale-specific parts and add colors and such.

**Comment by efx** [comment]
> This happens because autoview for DateTime gives the same output as date humanize. Perhaps this could be changed or made customizable (https://github.com/nushell/nushell/issues/3735).

swell! Thanks for the explanation and workaround @jmoore34! 

I am not blocked on a fix or anything too.
Just wanted to do my OSS part to make visible so others can see we are aware and jamming on a solution.

**Comment by rgwood** [comment]
`date now` [is used as an example in the Nu Book introduction](https://www.nushell.sh/book/) so that might need to be updated when this issue is resolved.
