### ISSUE TITLE
Stdout not captured when last block in last each

### ISSUE THREAD

**Issue by b333z** [nushell/nushell#4699]
### Describe the bug

I've noticed that if you have an each at the end of a block, and in the each block the last is an external, we don't seem to capture into the each output stream and instead leak to the shells stdout.

### How to reproduce

To reproduce, run the following, notice how the table is empty:

```nu
〉echo [[foo bar]; [a b] [c d] [e f]] | each { |it| nu --testbin cococo $it.foo }
a
c
e
╭───┬──╮
│ 0 │  │
│ 1 │  │
│ 2 │  │
╰───┴──╯
```

If we make the each not the last thing in the pipeline we are ok:

```nu
〉echo [[foo bar]; [a b] [c d] [e f]] | each { |it| nu --testbin cococo $it.foo } | select 1
╭───┬───╮
│ 0 │ c │
╰───┴───╯
```

If we make the external call not the last thing in the each block, also ok:

```nu
〉echo [[foo bar]; [a b] [c d] [e f]] | each { |it| nu --testbin cococo $it.foo | complete | get stdout}
╭───┬───╮
│ 0 │ a │
│ 1 │ c │
│ 2 │ e │
╰───┴───╯
```

### Expected behavior

I think if we got this it would be ideal:

```nu
〉echo [[foo bar]; [a b] [c d] [e f]] | each { |it| nu --testbin cococo $it.foo}
╭───┬───╮
│ 0 │ a │
│ 1 │ c │
│ 2 │ e │
╰───┴───╯
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | fd88920a                                 |
| commit_hash        | fd88920a9d68ad133f9cbb27671dc706d78be1bc |
| commit_date        | 2022-03-02 20:58:56 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 1980-01-01 00:00:00 +00:00               |
| build_rust_channel | debug                                    |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
This kind of looks like what i'd expect.

**Comment by b333z** [comment]
This was fixed in https://github.com/nushell/nushell/pull/4777
