### ISSUE TITLE
Haiku

### ISSUE THREAD

**Issue by theAkito** [nushell/nushell#470]
Since one of the best things about Nu is that it is designed from ground-up to be an extremely modern and up-to-date application, I find it only natural that [Haiku](https://www.haiku-os.org/) should be one of its (key?) targets, when it comes to operating systems, as this is an OS that is also built from the ground up with a modern attitude per design.

I don't see a real urgency in this matter, but I also don't think it should be dismissed entirely.

**Comment by vctibor** [comment]
There's both rustc and cargo at version 1.36 easily available from HaikuDepot. But it is stable channel. Compilation of nushell fails with:

```
error: failed to parse manifest at `/boot/home/hello/nushell/Cargo.toml`

Caused by:
  the `default-run` manifest key is unstable

Caused by:
  feature `default-run` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["default-run"]` to enable this feature
```

Rustup exits immediately with:

```
~/hello/nushell> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup: unrecognized OS type: Haiku
```

**Comment by vctibor** [comment]
Issue requesting Rustup support for Haiku was closed because of Haiku not being Tier 2 or above:

https://github.com/rust-lang/rustup.rs/issues/1374

Build of Rustup from git fails on Haiku with:

```
error: failed to run custom build command for `lzma-sys v0.1.15`

Caused by:
  process didn't exit successfully: `/boot/home/rustup.rs/target/debug/build/lzma-sys-c987239769ab5cdf/build-script-build` (exit code: 1)
--- stdout
cargo:rerun-if-env-changed=LZMA_API_STATIC
cargo:include=/boot/home/.cargo/registry/src/github.com-1ecc6299db9ec823/lzma-sys-0.1.15/xz-5.2/src/liblzma/api
TARGET = Some("x86_64-unknown-haiku")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-unknown-haiku")
CC_x86_64-unknown-haiku = None
CC_x86_64_unknown_haiku = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-haiku = None
CFLAGS_x86_64_unknown_haiku = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "xz-5.2/src/liblzma/api" "-I" "xz-5.2/src/liblzma/lzma" "-I" "xz-5.2/src/liblzma/lz" "-I" "xz-5.2/src/liblzma/check" "-I" "xz-5.2/src/liblzma/simple" "-I" "xz-5.2/src/liblzma/delta" "-I" "xz-5.2/src/liblzma/common" "-I" "xz-5.2/src/liblzma/rangecoder" "-I" "xz-5.2/src/common" "-I" "/boot/home/.cargo/registry/src/github.com-1ecc6299db9ec823/lzma-sys-0.1.15" "-Wall" "-Wextra" "-std=c99" "-pthread" "-DHAVE_CONFIG_H=1" "-o" "/boot/home/rustup.rs/target/debug/build/lzma-sys-139c98b22d166edd/out/xz-5.2/src/liblzma/common/alone_decoder.o" "-c" "xz-5.2/src/liblzma/common/alone_decoder.c"
cargo:warning=cc: error: unrecognized command line option '-pthread'
exit code: 1

--- stderr


error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "xz-5.2/src/liblzma/api" "-I" "xz-5.2/src/liblzma/lzma" "-I" "xz-5.2/src/liblzma/lz" "-I" "xz-5.2/src/liblzma/check" "-I" "xz-5.2/src/liblzma/simple" "-I" "xz-5.2/src/liblzma/delta" "-I" "xz-5.2/src/liblzma/common" "-I" "xz-5.2/src/liblzma/rangecoder" "-I" "xz-5.2/src/common" "-I" "/boot/home/.cargo/registry/src/github.com-1ecc6299db9ec823/lzma-sys-0.1.15" "-Wall" "-Wextra" "-std=c99" "-pthread" "-DHAVE_CONFIG_H=1" "-o" "/boot/home/rustup.rs/target/debug/build/lzma-sys-139c98b22d166edd/out/xz-5.2/src/liblzma/common/alone_decoder.o" "-c" "xz-5.2/src/liblzma/common/alone_decoder.c" with args "cc" did not execute successfully (status code exit code: 1).
```

**Comment by ret394** [comment]
Wait for Haiku to stabilize you impatient fools.

To some companies - And learn how to create decent donation pages, you luddites. Ever heard of this state of the art tech called the Web? Use it anyway, it's open* tech. 

So awesome! https://www.haiku-inc.org/donate/

you're welcome, as always. all the best. 👍
don't say nasty stuff or do rude stuff to folks on Github or other sites.

[ret394](https://github.com/ret394)

**Comment by korrat** [comment]
HaikuDepot now provides Rust stable 1.50. Perhaps this issue could be revisited?

**Comment by jonathandturner** [comment]
For folks who want to try building on Haiku - you could try building with `--no-default-features` first. By now, a good number of the platform-specific crates should be optional, since that's what we had to do for wasm. With luck, you'll be able to have something working, and then can isolate what dependencies prove a challenge.
