### ISSUE TITLE
Bool flag should accept `false` value

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4702]
### Related problem

For this script: `def ready [--ready: bool] { if $ready { 'Ready!' } else { 'Not ready!' } }`
Both `ready --ready=true` and `ready --ready` output: `Ready!` just as expected, However, `ready --ready=false` will get the `Ready!` output too, that's not as expected

### Describe the solution you'd like

Both `ready` and `ready --ready=false` should get `Not ready!` output, why this could be helpful?
Supposing we get the ready status by calling some command: `let status = (call-some-command)`, and then we want to call `ready` command, we can do it this way: 
```
if $status { ready --ready } else { ready }
```
But `ready --ready=$status` will be more clean and simpler, especially when you have many bool flags like this one:
`ready --bool-flag1=$bool-val1 --bool-flag2=$bool-val2 --bool-flag3=$bool-val3 ...`

### Additional context and details

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | 0da9213d                                 |
| commit_hash        | 0da9213de62960916981ae293dad3eded536abc8 |
| commit_date        | 2022-03-01 23:38:35 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-02 10:13:36 +08:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | query, query json, query web, query xml  |

**Comment by fdncred** [comment]
I think this is a bug because I can do this and it works fine
```
def ready [--ready: any] { if $ready { 'Ready!' } else { 'Not ready!' } }
```

**Comment by uasi** [comment]
As @jntrnr explained in https://github.com/nushell/nushell/pull/4972#issuecomment-1079628713, allowing values to be attached to bool flags creates ambiguity:

>     def foo [--bar: bool, baz?:bool] {
>       print $bar
>       print $baz
>     }
>     
>     foo --bar true
>
> Now, the question is how do we parse `foo --bar true`? If we allow the boolean to optionally be here, we're in a place where it's ambiguous whether we should parse the boolean as part of the `--bar` flag and assign it to the `$bar` variable or if we should parse it as the optional positional `$baz`.

**Comment by hustcer** [comment]
It seems that we should use `def ready [--ready: any] { if $ready { 'Ready!' } else { 'Not ready!' } }` in such case, that's okay, I will close it.
