### ISSUE TITLE
Extra characters in completions

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#4709]
### Describe the bug

Starting with #4704, we now sometimes get extra characters when completing from the menu. Here's one example:

![](https://cdn.discordapp.com/attachments/683070703716925568/949020617636741130/unknown.png)

And then if I pick `Cargo.toml`, I get:

![](https://cdn.discordapp.com/attachments/683070703716925568/949020805172428820/unknown.png)

cc @elf

### How to reproduce

See above

### Expected behavior

The completion logic shouldn't add extra characters to the selection. It should complete to whatever is chosen from the menu.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | jsonification                            |
| short_commit       | e7ff3861                                 |
| commit_hash        | e7ff3861992f95db544f011116e5b48ec28a0552 |
| commit_date        | 2022-03-03 13:17:26 +00:00               |
| build_os           | macos-aarch64                            |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-aarch64-apple-darwin              |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-03 08:26:37 -05:00               |
| build_rust_channel | debug                                    |
| features           | default, which                           |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
Adding this so we don't lose it. 
![image](https://user-images.githubusercontent.com/343840/156786393-8dbd4990-c155-4c57-903d-b316d2db5de9.png)
