### ISSUE TITLE
autocomplete fails 

### ISSUE THREAD

**Issue by taooceros** [nushell/nushell#4710]
### Describe the bug

If we have a string like this. `git branch -a | lines | each { |line| $line | str find-replace '(\*)|(remotes\)' '' | str tr }`
hit tab at the `tr` won't produce str trim, but hit tab at the str (delete the tr) will get us the accurate result for str *.

### How to reproduce

1. Type the string
2. Tab

### Expected behavior

Autocomplete produce str trim

### Configuration

version: 0.59 beta

**Comment by fdncred** [comment]
i was able to reproduce this behavior too on 4965f4cb

**Comment by hustcer** [comment]
Please try nu v0.62 or build from the latest main branch, it works now
