### ISSUE TITLE
Duplicate code

### ISSUE THREAD

**Issue by TyPR124** [nushell/nushell#4712]
https://github.com/nushell/nushell/blob/47d5501f9f1194e04b6768b695e339b69cf79db7/src/commands.rs#L36-L46

This looks to me like a bit of duplicate code that is not needed. Unless `err` has interior mutability and for some reason `report_error` mutates it (which I haven't checked for but seems unlikely). Noticed while browsing the code in relation to #4711

**Comment by fdncred** [comment]
ya, i'm guessing one of those needs to be removed.
