### ISSUE TITLE
Add installation instructions using the Chocolatey package manager

### ISSUE THREAD

**Issue by dgalbraith** [nushell/nushell#4713]
### Related problem

Instructions are provided to install `Nushell` in a number of ways, including using various package managers.

As a user of the [Chocolatey](https://chocolatey.org) package manager I would like appropriate installation instructions available.  Consider adding instructions to install `Nushell` on Windows using [Chocolatey](https://chocolatey.org).

nushell/nushell.github.io#247

### Describe the solution you'd like

Update the project `README.md` file to include details on how to install `nushell` with the [Chocolatey](https://chocolatey.org) package manager.

To install Nu via [Chocolatey](https://chocolatey.org):
```shell
choco install nushell
```

**Comment by fdncred** [comment]
we'd accept a PR for this.
