### ISSUE TITLE
Design needed for required-homogeneous streams

### ISSUE THREAD

**Issue by wycats** [nushell/nushell#472]
It commonly comes up that you want a command that operates on elements of the input stream under the assumption that the input stream is homogeneous.

#469 is a good example. We want to give metadata about the elements of the input stream, but that doesn't really make sense if the input stream is heterogeneous.

PowerShell falls back to a list mode if the input is heterogeneous but this feels too error-prone to me. We could have a "give me the metadata for every item in the list" query, but I don't think it makes sense as the default. Having a reliable way to get metadata about elements of the input stream, with a failure if the input stream isn't homogeneous, will become even more important once we have scripts, but I think it's important in shell mode too.

Proposed design: commands can say that they operate on a typed stream of inputs (just like they can declare the type of their arguments), and all of the elements of the stream would need to be that type. We would also have a way to say that all elements of the stream could be any specific dictionary type, or any specific list type (analogous to `Vec<T>`).

This is related to #419, because null often makes a table appear to be heterogeneous. We would want a way to say that rows are considered equivalent if they contain a null column. Detailed design forthcoming.

**Comment by jonathandturner** [comment]
We currently handle outputting tables of different shapes by starting a new table. We can also output packets of raw string/binary that are mixed into the stream.

Closing this, though we should be open to targeting specific use cases in the current design as we find them.
