### ISSUE TITLE
register command panics on completion

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4723]
### Describe the bug

i typed `register -e capnp c:\c<tab>` and it panics.
```
C:\Users\username\source\repos\forks\nushell〉register -e capnp c:\cthread 'main' panicked at 'attempt to subtract with overflow', C:\Users\username\.cargo\git\checkouts\reedline-e42026a78d91c510\e9c1e37\src\engine.rs:613:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `c:\cartar\debug\nu.exe` (exit code: 101)
```

### How to reproduce

see above

### Expected behavior

no panics

### Configuration

|key|value|
|-|-|
|version|0.59.1|
|branch|main|
|short_commit|89b7f4d5|
|commit_hash|89b7f4d57c7350508e0ae9095709f22768420b7b|
|commit_date|2022-03-04 14:00:11 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.59.0 (9d1b2106e 2022-02-23)|
|rust_channel|stable-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.59.0 (49d8809dc 2022-02-10)|
|pkg_version|0.59.1|
|build_time|2022-03-04 08:38:01 -06:00|
|build_rust_channel|debug|
|features|dataframe, default, trash, which, zip|
|installed_plugins||

**Comment by stormasm** [comment]
@fdncred do you think this is this related to https://github.com/nushell/nushell/issues/4277 ?

**Comment by fdncred** [comment]
> @fdncred do you think this is this related to #4277 ?

maybe - i'm not sure exactly what's causing this. i guess it's not doing the math right for spans or something?

**Comment by elferherrera** [comment]
My guess is that it is related to scaped \\
I fixed something like this recently.

**Comment by fdncred** [comment]
i think jt had a fix for this too - someting about uppper/lowercase panics. either way, i can't reproduce it so i'm closing.
