### ISSUE TITLE
show the installed plugins

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4724]
### Related problem

after #4719 i don't think we'll be able to easily show `installed_plugins` anymore in our `version` command without searching the file system.

![image](https://user-images.githubusercontent.com/343840/156790210-4e31f54b-dc23-4adc-b289-7edc8c950f2d.png)

btw - i have all the plugins installed here.

### Describe the solution you'd like

show what plugins are installed.

### Describe alternatives you've considered

maybe we can add `which <each_plugin_name>` to be able to show them.

**Comment by jntrnr** [comment]
Yeah, I think `$scope.commands | where is_plugin == true` isn't working either. Maybe plugins aren't setting their flags?

**Comment by elferherrera** [comment]
That is supposed to work. I can see the plugins as well

**Comment by jntrnr** [comment]
Funny, you know this is a different machine, I bet I haven't registered any yet. oops

**Comment by hustcer** [comment]
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | b73af3b8                                 |
| commit_hash        | b73af3b8df58cdde22c0454a8a24b141654c7f03 |
| commit_date        | 2022-03-08 15:10:01 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-09 09:55:16 +08:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | query, query json, query web, query xml  |

This works for me on mac and windows. So I will close it.
