### ISSUE TITLE
-c, --col parameter for `find`

### ISSUE THREAD

**Issue by zkldi** [nushell/nushell#4729]
### Related problem

`find` at the moment searches on all columns in a table. People might want to restrict this to certain columns. I think taking a `-c` flag that specifies columns would be useful. If vararging flags is possible, passing multiple `-c` columns would restrict to those columns.

### Describe the solution you'd like

`ls | find --col=name foo` OR `ls | find -c name foo`

### Describe alternatives you've considered

You can do `ls | get col_name | find foo`, but that results in you losing all other columns in the output.

### Additional context and details

This was discussed in the discord, I should be free to submit a PR for this.

**Comment by fdncred** [comment]
This could also be done with `where` like `ls | where name == foo`.

**Comment by fdncred** [comment]
This could also be done with `where` like `ls | where name == foo`.

**Comment by zkldi** [comment]
Oh thats actually already what I want -- and clearer. Thanks!
