### ISSUE TITLE
Issue with quoted fields

### ISSUE THREAD

**Issue by lucatrv** [nushell/nushell#4737]
### Describe the bug

I'm using Nushell 0.59.1 on Arch Linux, compiled from source `master` branch.

The following command:

```
bat --theme="Sublime Snazzy" file
```

errors out with message:

```
[bat warning]: Unknown theme '"Sublime Snazzy"', using default.
```

The issue may be related to the added single quotes. The following command works:

```
bat "--theme=Sublime Snazzy" file
```

### How to reproduce

```
bat --theme="Sublime Snazzy" file
```

### Expected behavior

`bat` should use the `Sublime Snazzy` theme.

**Comment by hustcer** [comment]
```
bat --theme="Sublime Snazzy" file
```
This works for me on mac, I'm using `bat 0.20.0`

**Comment by fdncred** [comment]
this works for me too, the same as @hustcer, so I'm closing for now. please reopen if you still have issues.

**Comment by lucatrv** [comment]
I'm also using `bat 0.20.0`, but I confirm the issue on Arch Linux. I run `nu` manually from `bash`, but I do not think this can have an effect. I've just recompiled Nushell from `master` branch, and also tried deleting my `config.nu` file, but `bat --theme="Sublime Snazzy" file` still does not work.

**Comment by fdncred** [comment]
We'll need help from someone on linux then because this issue doesn't appear on Mac, not sure about windows.

**Comment by hustcer** [comment]
It works fine on Windows 10

**Comment by sholderbach** [comment]
Is this behavior still present?

**Comment by fdncred** [comment]
this is still broken for me. it doesn't puke but it also doesn't highlight anything properly.

**Comment by jntrnr** [comment]
Just tried this on Ubuntu LTS with the latest main and it's working correctly.

Closing, but if you can find a configuration where it repros, please re-open.
