### ISSUE TITLE
Member syntax `foo."bar"`

### ISSUE THREAD

**Issue by wycats** [nushell/nushell#474]
`col."first name"` should work.

TL;DR `"first name"` should be a valid member part.

**Comment by Porges** [comment]
Thought: given the support for structured data it could be nice to have something like XPath/JsonPath.

**Comment by Porges** [comment]
Had a look into the issue and strings are [already meant to be valid parts of paths](https://github.com/nushell/nushell/blob/3d912a2c1dae8a9925232730b30642ba948f1696/src/parser/parse/parser.rs#L524), but there's a mis-parse somewhere else that's turning `get foo."bar"` into [two pipeline elements where `"bar"` is a new command](https://gist.github.com/Porges/0ca6988b0b10b665100fba09b177ad05).

**Comment by Porges** [comment]
I came up with a solution to the pipeline mis-parse but there's a bad interaction between `bare` and `path` :thinking: so if we have `col."first name"` then `bare` will gobble up `col.` and then `path` will want to parse a `.` before it consumes `"first name"`. This might need more rework...

**Comment by jonathandturner** [comment]
@wycats does this work with your recent fixes?

**Comment by wycats** [comment]
Yep!
