### ISSUE TITLE
Table layout broken on windows in some cases

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4741]
### Describe the bug

Table layout broken on windows in some cases
This is another incompatible issue I have came across on Windows

### How to reproduce

Just run the following code:
```nu
def 'show-env' [] {
  let gitProxy = (if (git config --global --list | grep proxy | empty?) { 'Off' } else { 'On' })
  version | transpose | rename nu-ver value

  echo [
    [name, value];
    ['Git Proxy', $gitProxy]
  ]
}
show-env
```
And you will see the broken table layout like this:

![image](https://user-images.githubusercontent.com/1161607/156887004-386972c8-636c-4a0b-8345-8eaf56f421ef.png)

### Expected behavior

Should output the same as running on mac

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | feature/scripts                          |
| short_commit       | d591a6e5                                 |
| commit_hash        | d591a6e55c45e6976dedc0cd3974b26202bbbd77 |
| commit_date        | 2022-03-05 05:31:12 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-05 17:23:28 +08:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | query, query json, query web, query xml  |

**Comment by jntrnr** [comment]
Are the terminals in Windows and the Mac set to the same width?

**Comment by hustcer** [comment]
> Are the terminals in Windows and the Mac set to the same width?

I have the same issue even in fullscreen mode

**Comment by fdncred** [comment]
This looks like ansi escapes leaking, which we see sometimes with the `git-for-windows` tools.

**Comment by hustcer** [comment]
> This looks like ansi escapes leaking, which we see sometimes with the `git-for-windows` tools.

Probably yes, and I have studied all these layout broken cases, they have the same point, that's using `git` command in the scripts.

**Comment by fdncred** [comment]
Ya, some of them are from `git` and others are from the coreutils like `cat` and other in the git\usr\bin folder. What's happening is the vt processing is getting disabled (I think). So, we've fixed some of the issues by adding this function `enable_vt_processing()` but there may be other places we need to call it from.

**Comment by hustcer** [comment]
Currently I have to use `let $config = { table_mode: 'none' }`  to make it better

**Comment by hustcer** [comment]
Great! This issue has been fixed on the latest main. Thanks.
