### ISSUE TITLE
add version and icon to windows version of nushell

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4742]
### Related problem

Mimic these.

https://github.com/ruffle-rs/ruffle/commit/9e38c4188b5da21b311d39594fde6eb67e989947

https://github.com/ruffle-rs/ruffle/blob/master/desktop/assets/ruffle_desktop.rc

### Describe the solution you'd like

add version and icon to windows version of nushell and plugins

**Comment by CBenoit** [comment]
Has someone been looking into that?

**Comment by fdncred** [comment]
This has been implemented already.
