### ISSUE TITLE
Cannot cd into ~/

### ISSUE THREAD

**Issue by Nate-Watts** [nushell/nushell#475]
Maybe I have something setup incorrectly with my environment, but currently ~/ isn't recognized.
```
/Users/nwatts> cd ~
error: Parse Error
- shell:1:3
1 | cd ~
  |    ^
/Users/nwatts> 
```

**Comment by twe4ked** [comment]
Dupe of https://github.com/nushell/nushell/issues/340.

**Comment by jonathandturner** [comment]
Closing as dupe of #340

**Comment by jonathandturner** [comment]
(basic support now in https://github.com/nushell/nushell/pull/479)
