### ISSUE TITLE
dfr open test.json yields ArrowError

### ISSUE THREAD

**Issue by stormasm** [nushell/nushell#4758]
### Describe the bug

when I do the following command...

```rust
dfr open test.json

```rust
 ArrowError(ExternalFormat("Expected JSON record to be an object, found Array([Object({\"a\": Number(1), \"b\": Number(2)}), Object({\"a\": Number(3), \"b\": Number(4)})])"))
```

### How to reproduce

* Create a json file and then run the command

test.json = 
```rust
[{"a": 1,"b": 2},{"a": 3,"b": 4}]
```

* Create a json file this way and then run the command...

```rust
[[a b]; [1 2] [3 4]] | to json | save test.json
```

```rust
dfr open ./test.json
```

### Expected behavior

not fail...

**Comment by jntrnr** [comment]
I *think* `dfr open` requires that json be object json, or one object-per-line in the file rather than all the objects in a single list

**Comment by stormasm** [comment]
I just asked @elferherrera his opinion on this as well....  and hopefully fairly soon I will understand the dfr codebase well enough to be able to understand it too.  Thank you...

**Comment by elferherrera** [comment]
The accepted JSON format for polars is this
```
"{"a":1, "b":2.0, "c":false, "d":"4"}
{"a":-10, "b":-3.5, "c":true, "d":"4"}
{"a":2, "b":0.6, "c":false, "d":"text"}
{"a":1, "b":2.0, "c":false, "d":"4"}
{"a":7, "b":-3.5, "c":true, "d":"4"}
{"a":1, "b":0.6, "c":false, "d":"text"}
{"a":1, "b":2.0, "c":false, "d":"4"}
{"a":5, "b":-3.5, "c":true, "d":"4"}
{"a":1, "b":0.6, "c":false, "d":"text"}
{"a":1, "b":2.0, "c":false, "d":"4"}
{"a":1, "b":-3.5, "c":true, "d":"4"}
{"a":100000000000000, "b":0.6, "c":false, "d":"text"}"
```
As you can see, it is a list of records

**Comment by elferherrera** [comment]
I see. The issue is the way the data is stored in the file. If you open the file it has newline characters that the polars parser doesn't like. It will only allow the format I pasted above

**Comment by stormasm** [comment]
{"a":1, "b":2.0, "c":false, "d":"4"}
{"a":-10, "b":-3.5, "c":true, "d":"4"}
{"a":2, "b":0.6, "c":false, "d":"text"}

This file works...

Same as above but without the initial quotes and ending quotes...

**Comment by stormasm** [comment]
Ok so I am closing this as we now know what works / and what does not work...
For future reference: anyone reading this your json must conform to the above format only....
