### ISSUE TITLE
reduce -n returns an IncompatiblePathAccess error

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#4759]
### Describe the bug

Simple uses of `reduce --numbered` (`-n`) return an "IncompatiblePathAccess" error.

### How to reproduce

```
〉[1 2 3] | reduce -n {|it, acc| $acc.item + $it.item }
╭───────┬──────────────────────────────────────────────────────────────────╮
│ index │ 2                                                                │
│ item  │ IncompatiblePathAccess("error", Span { start: 5905, end: 5909 }) │
╰───────┴──────────────────────────────────────────────────────────────────╯
```

Or, using [this example from the book](https://github.com/nushell/nushell.github.io/blob/d9839a5819d74ab99770c7ecfd3881ccd9eecaa2/book/working_with_lists.md?plain=1#L137-L148) (slightly simplified):

```
〉[3 8 4] | reduce -n {|it, acc| $acc.item + $it.index * $it.item }
╭───────┬──────────────────────────────────────────────────────────────────╮
│ index │ 2                                                                │
│ item  │ IncompatiblePathAccess("error", Span { start: 5958, end: 5962 }) │
╰───────┴──────────────────────────────────────────────────────────────────╯
```

### Expected behavior

I expected nu to return an integer, not an error.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | 69fd7771                                 |
| commit_hash        | 69fd77712014d54d3ef24cdec5f9252ac03cf83b |
| commit_date        | 2022-03-06 00:55:37 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-05 20:45:25 -08:00               |
| build_rust_channel | debug                                    |
| features           | default, which                           |
| installed_plugins  |                                          |

### Additional context

I noticed this when trying to upgrade [this example in the book](https://github.com/nushell/nushell.github.io/blob/d9839a5819d74ab99770c7ecfd3881ccd9eecaa2/book/working_with_lists.md?plain=1#L137-L148) for engine-q block syntax. A comment in the example links to [this issue](https://github.com/nushell/nushell/issues/3298) which was closed; might be related?

**Comment by hustcer** [comment]
It’s a simple and fundamental usage and I think we should fix it in v0.60

**Comment by hustcer** [comment]
Seems still not work well? @jntrnr 
$> [1 2 3] | reduce -n {|it, acc| $acc.item + $it.item }
```
Error: nu::shell::incompatible_path_access (link)

  × Data cannot be accessed with a cell path
   ╭─[entry #8:1:1]
 1 │ [1 2 3] | reduce -n {|it, acc| $acc.item + $it.item }
   ·                                     ──┬─
   ·                                       ╰── int doesn't support cell paths
   ╰────
```

**Comment by hustcer** [comment]
This works:
`[1 2 3] | reduce -n {|it, acc| $acc + $it.item }`
`[3 8 4] | reduce -n {|it, acc| $acc + $it.index * $it.item }`
