### ISSUE TITLE
`pwd` output on Windows should be the same as the path printed by powershell

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4761]
### Describe the bug

`pwd` output on Windows should be the same as the path printed by powershell

### How to reproduce

`pwd` will output something like `/d/Data/iWork/nushell`, however, the powershell output path is `D:\Data\iWork\nushell`
and run `cd /d/Data/iWork/nushell` in nushell will get:
```

Error: nu::shell::directory_not_found_help (https://docs.rs/nu-protocol/0.59.1/nu-protocol/enum.ShellError.html#variant.DirectoryNotFoundHelp)

  × Directory not found
   ╭─[entry #3:1:1]
 1 │ cd /d/Data/iWork/nushell
   ·    ──────────┬──────────
   ·              ╰── directory not found
   ╰────
  help: IO Error: Os { code: 3, kind: NotFound, message: "Could not find the specified path." }
```

### Expected behavior

`pwd` output on Windows should be the same as the path printed by powershell, Or `cd /d/Data/iWork/nushell` should work as expected and `path` related commands should accept paths like `/d/Data/iWork/nushell`

### Screenshots

![image](https://user-images.githubusercontent.com/1161607/156996084-4b55d136-ced0-4d9b-aa3b-2972e10f6faf.png)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | 7701c6b1                                 |
| commit_hash        | 7701c6b1d4a0f42043e562e0d5ed82c236f06958 |
| commit_date        | 2022-03-06 17:22:18 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-07 11:28:08 +08:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | query, query json, query web, query xml  |

**Comment by fdncred** [comment]
but wait, I don't think we have a `pwd` command. I bet this is the `git` tools external you're calling. I think we have `$nu.cwd` in nushell.

**Comment by jntrnr** [comment]
maybe we should add a `pwd` command?

**Comment by hustcer** [comment]
> maybe we should add a pwd command?

Agree!

**Comment by hustcer** [comment]
I will close this issue and use `$env.PWD` instead
