### ISSUE TITLE
Tracking issue for missing metadata and `LS_COLORS`

### ISSUE THREAD

**Issue by jaeheonji** [nushell/nushell#4763]
List of missing `metadata` in `nu-command/src/filters` commands.
Missing `metadata` will cause `ls_colors` to not print properly to the terminal.

The following PR shows a simple example:
* #4525 
* #4603

| Command                | Status  |
|------------------------|---------|
| `drop`                 | #4908 |
| `keep`                 | #4908 |
| `append`               | #4908 |
| `collect`              | #5009  |
| `compact`              | #5009 |
| `each` (group, window) | #5009 |
| `every`                | #5009 |
| `flatten`              | #5009 |
| `get`                  | #5009 |
| `headers`              | #5009 |
| `par-each` (group)     | #5009 |
| `prepend`              | #5009 |
| `range`                | #5009 |
| `reduce`               | none - probably not a good fit|
| `reject`               | #5009 |
| `rename`               | #5009 |
| `rotate`               | #5009 |
| `select`               | #5009 |
| `shuffle`              | #4908 |
| `transpose`            | #5009 |
| `uniq`                 | #4908 |
| `update` (cell)        | #5009 |

There may be more missing metadata out of the list. Please let me know if there's anything I've missed 😸

**Comment by fdncred** [comment]
thanks for tracking these @jaeheonji

**Comment by fdncred** [comment]
wow, we may be done here @jaeheonji. do you see any more places we need to add this?

**Comment by jaeheonji** [comment]
@fdncred No! This seems to be enough 😄. I saw the contents of #5009. The `get` and `reduce` cases don't seem to be suitable for applying `LS_COLORS`.

If there is any additional content, it seems to be a separate issue.
So I think you can close this issue. (YEEAH! 🥳)

**Comment by fdncred** [comment]
the only thing i just recently saw missing is `ls /usr -s` doesn't respect ls_colors. there's a separate [issue ](https://github.com/nushell/nushell/issues/4319)for that though so we can probably close this.
