### ISSUE TITLE
`path is-dir` function 

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#4768]
### Related problem

I'd like a way to check if a given path is a directory or not, similar to the `-d` test on other shells. This would be useful for [zoxide](https://github.com/ajeetdsouza/zoxide) to support Nushell.

### Describe the solution you'd like

A function such as `path is-dir`, similar to `path exists`, would be great. Alternatively, this could be an argument such as `path exists -d`.

### Additional context and details

CC @fdncred

**Comment by jmoore34** [comment]
One thing you can do is use `path type`, e.g.
![image](https://user-images.githubusercontent.com/1783464/157104902-f6f9c207-52a5-4bd5-b6ee-d56888a327c1.png)

**Comment by ajeetdsouza** [comment]
That works, thanks!

**Comment by fdncred** [comment]
@ajeetdsouza Will what @jmoore34 suggested work for you? Also, our strings work differently now. double quoted strings mean that there can be escapes. single quoted strings work the way the old ones did.
so,
```
> "hello\nworld"
hello
world
```
and 
```
> 'hello\nworld'
hello\nworld
```

**Comment by ajeetdsouza** [comment]
Got it, will use those instead. Thanks!
