### ISSUE TITLE
cd $x doesn't work if $x = "-"

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#4769]
### Describe the bug

This goes to the previous directory:

```
cd "-"
```

However, this looks for a directory named "-":

```
let x = "-";
cd $x
```

I'm not sure if this is intentional or not, but I found it surprising behaviour. Is there a way I can ask `cd` to treat `-` as a special case even if it's in a variable?

### How to reproduce

```
let x = "-";
cd $x
```

### Expected behavior

Should go to previous directory.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | 42f1874a                                 |
| commit_hash        | 42f1874a3aae2e3bc3c669cb0aac0132a586ea24 |
| commit_date        | 2022-03-01 13:05:29 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-03-01 13:39:18 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
i tried with single quotes, double quotes and `cd ($x)` - none of these seem to work here.

**Comment by uasi** [comment]
At least, that behavior is consistent with the way other built-in commands handle quoted flags.

```
> ls --help
List the files in a directory.

Usage:
[snip]

> ls "--help"
Error: nu::shell::directory_not_found (https://docs.rs/nu-protocol/0.60.0/nu-protocol/enum.ShellError.html#variant.DirectoryNotFound)

  × Directory not found
   ╭─[entry #24:1:1]
 1 │ ls "--help"
   ·    ────┬───
   ·        ╰── directory not found
   ╰────

> let $help = "--help"; ls $help
Error: nu::shell::directory_not_found (https://docs.rs/nu-protocol/0.60.0/nu-protocol/enum.ShellError.html#variant.DirectoryNotFound)

  × Directory not found
   ╭─[entry #25:1:1]
 1 │ let $help = "--help"; ls $help
   ·                          ──┬──
   ·                            ╰── directory not found
   ╰────
```

Maybe we need a lisp-like unquote operator `cd ,($x)` or something.

<details>

<summary>Configuration</summary>

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.0                                   |
| short_commit       | 74af31a4                                 |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315 |
| commit_date        | 2022-03-22 19:07:11 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.60.0                                   |
| build_time         | 2022-03-22 19:23:50 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

</details>

**Comment by fdncred** [comment]
@ajeetdsouza i noticed a comment in your `.zoxide.nu` file. isn't this how it's supposed to work? is this enough to unblock `z -`?
![image](https://user-images.githubusercontent.com/343840/164766111-92d33359-09d5-4b9d-b674-901ca7fd2130.png)

this doesn't work, but i'm not sure it should
```
> let x = -
> cd $x <-- fails
> cd ($x) <-- fails
```
```
> let x = "-"
> cd $x <-- fails
> cd ($x) <-- fails
```
and yet, this seems to work just fine
```
> let x = 'c:\temp'
> cd $x <-- works!
> cd ($x) <-- works!
```

**Comment by ajeetdsouza** [comment]
@fdncred the problem is that I have no way to conditionally `cd` into `$OLDPWD`:

```
cd (if true { "-" } else { "foo" })
```

gives me the error:

```
Error: nu::shell::directory_not_found_help (https://docs.rs/nu-protocol/0.61.0/nu_protocol/enum.ShellError.html#variant.DirectoryNotFoundHelp)

  × Directory not found
   ╭─[entry #3:1:1]
 1 │ cd (if true { "-" } else { "foo" })
   ·               ─┬─
   ·                ╰── directory not found
   ╰────
  help: IO Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
