### ISSUE TITLE
Changing environment from inside a block

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#4771]
### Related problem

I need a way to conditionally `cd` into a directory. I need this to implement the `z` function in [zoxide](https://github.com/ajeetdsouza/zoxide). I know that using `def-env` allows us to set environment variables from within a function, but how can I do this inside an if-else block?

### Describe the solution you'd like

Perhaps an `if-env` keyword?

**Comment by fdncred** [comment]
I don't believe one can do this yet. that's what this PR is all about https://github.com/nushell/nushell/pull/4656 - @jntrnr is still considering if we should allow this or not.

**Comment by jmoore34** [comment]
Here is a workaround I used for something similar:

```
def-env goto [] {
    let input = $in
    cd (
        if ($input | path type) == file {
            ($input | path dirname)
        } else {
            $input
        }
    )
}
```

**Comment by fdncred** [comment]
good point @jmoore34, as long as the `if` expression is inside of `()` part of the cd statement it should work. btw - i love this command jon. i use `$nu.config-path | goto` frequently.

**Comment by ajeetdsouza** [comment]
I'm using that, but it only works when you are doing a `cd` in both cases. Otherwise, it would be something like:

```
cd (if $condition { "/tmp" } else { "$nu.cwd" })
```

This works great, but throws an extra error if the current directory does not exist (i.e. has been deleted).

**Comment by fdncred** [comment]
@ajeetdsouza i'm not sure how applicable is but `do -i` works a lot better now. this eats all those errors `do -i { cd (if true { "c:\\tempz" } else { "$nu.cwd" }) }`

**Comment by ajeetdsouza** [comment]
I've updated the title to reflect my more general use case. For example, I'd like to be able to change an environment variable from within `PROMPT_COMMAND`. Currently, this appears to be impossible to do, but if support for this were added, zoxide would be able to use PWD hooks with Nushell.

**Comment by kubouch** [comment]
@ajeetdsouza Can you give an example how you would use changing environment variables from inside `PROMPT_COMMAND`?

In general, I think it again comes to the design limitations of the language where we don't allow modifying a global scope. For example, scoped environment variables are necessary to be able to safely implement `par-each`.

However, we were thinking about implementing hooks when you enter a directory (and possibly other cases) so maybe that would help your use case? But that will be after 0.60.

**Comment by ajeetdsouza** [comment]
> However, we were thinking about implementing hooks when you enter a directory

This is exactly what I wanted to do. If I have hooks, I probably wouldn't need this feature. However, it seems inconsistent to me that the language allows something like `def-env`, but has no mechanism for defining environment variables in any other block (even when the block is within a `def-env`).

**Comment by 71** [comment]
I was bitten by the same issue (`def-env` not propagating to inner blocks). No matter what the solution is, I believe it would be good to document this limitation and/or show warnings when `let-env` (or friend) is used in an inner block of a `def-env` function.

For the particular case of changing the environment, I found a workaround: build a record of environment variable entries in the function, and then call `load-env $record` at the top level of the function. Something like

```nu
let new-env = if $foo { {FOO: 1} } else { {} }

load-env $new-env
```

**Comment by kubouch** [comment]
@71 Currently, we follow a simple procedure: _all_ blocks are scoped, except `def-env` which preserves the environment. That's a relatively simple rule but we've noticed people bumping into this and we're looking into ways to improve it.

I'd personally lean towards removing `def-env` and making it possible to mark any block as env-preserving, so you could make your own `def-env` alternative, but also have to option to make if/else (and other) blocks preserve the environment with some distinct syntax. If we started special-casing `if` to preserve the environment or making it dependent on whether it is inside `def-env` or not, it would create a lot of implicit rules and make the mental model more complicated.

**Comment by 71** [comment]
@kubouch I understand this, but since this requires some design discussion I commented to ask for a temporary improvement (warning about why `def-env` does not propagate to inner blocks) and to suggest a workaround (using `load-env`).
