### ISSUE TITLE
Strange behaviour of source command in config.nu

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#4773]
### Describe the bug

There are a couple of problems with the `source` command when I use it in my `config.nu`.

---

Suppose the file `~/foo` does not exist. Then the following `config.nu` file fails, saying that the file does not exist:

```
echo "some code" | save ~/foo
source ~/foo
```

However, the file should exist, because I just created it. However, when I go to check, I see that the file has not been created either.

---

Suppose the file `~/foo` had the contents `"some code"`. Now, consider the following `config.nu` file:

```
echo "other code" | save ~/foo
source ~/foo
```

This should have sourced `other code`, because that's what I just wrote to the file. However, Nushell (incorrectly) ends up loading `some code`. When I check, I see that `~/foo` (correctly) contains `other code`.

---

Finally, `source` does not work with variables. This is strange behaviour, considering that everything else in Nushell does.

### How to reproduce

N/A

### Expected behavior

N/A

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.0                                   |
| branch             | main                                     |
| short_commit       | 42f1874a                                 |
| commit_hash        | 42f1874a3aae2e3bc3c669cb0aac0132a586ea24 |
| commit_date        | 2022-03-01 13:05:29 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.0                                   |
| build_time         | 2022-03-01 13:39:18 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

### Additional context

These issues are blockers for the implementation of the [zoxide](https://github.com/ajeetdsouza/zoxide) plugin on Nushell.

CC @fdncred

**Comment by fdncred** [comment]
What you're trying to do may not be do-able in nushell. It's my understanding that writing a file happens at 'eval time' and sourcing a file happens at 'parse time' and I don't believe those two things ever mix. I'm hoping we can come up with some other solution that fits both nushell and zoxide. Nushell's architecture is just different and we don't try to be POSIX-like so `source` in nushell doesn't really work like `source` in bash.

**Comment by ajeetdsouza** [comment]
The basic idea is that `zoxide init nushell` generates a script which I want Nushell to source, I'd love to hear if there are alternate ways of doing so.

**Comment by fdncred** [comment]
yup, understood. I still have this in my nushell v0.44 config.
```
startup = [
    "zoxide init nushell --hook prompt | save ~/.zoxide.nu",
    "source ~/.zoxide.nu",
```

**Comment by kubouch** [comment]
@ajeetdsouza Would it be possible to add `zoxide init nushell --hook prompt | save ~/.zoxide.nu` into installation instructions and have only `source ~/.zoxide.nu` in the config? Does the `zoxide.nu` need to be rewritten on every Nushell startup?

Unfortunately, as @fdncred said, it's a language design issue that's not easy to fix -- allowing it would have deep consequences and disallow many assumptions we currently rely on.

**Comment by ajeetdsouza** [comment]
@kubouch while that would work, it would break every time zoxide was upgraded. I don't want to rely on package managers to rewrite the script each time, moreso for a fast-changing shell like Nushell.

**Comment by kubouch** [comment]
@ajeetdsouza I see. The way you described (save and source file within the same script) is currently impossible. However, there might be a workaround: Within `zoxide.nu` you would define environment variable, e.g., `let-env ZOXIDE_VERSION = '0.7.0'` and a custom command along these lines:
```
def zoxide-check-updates [] {
    let actual_version = (zoxide --version | str trim)
    if $actual_version != $env.ZOXIDE_VERSION {
        zoxide init nushell --hook prompt | save ~/.zoxide.nu
        print $'Zoxide was upgraded from ($env.ZOXIDE_VERSION) to ($actual_version), please reload Nushell'
    }
}
```
Then, you could instruct users to put this to the `config.nu`:
```
source ~/.zoxide.nu
zoxide-check-updates
```

You would need to run `zoxide init nushell --hook prompt | save ~/.zoxide.nu` when you install zoxide for the first time. But after that, it should keep the script up to date and notify users when it changed. The advantage is that you don't write the file on every startup.

**Comment by kubouch** [comment]
Ah, I see. I'm afraid regenerating the file after each change might be the best solution now. Currently, we don't have plans to change how `source` works since that would change everything.

**Comment by ajeetdsouza** [comment]
I managed to fix this by adding `echo "some code" | save ~/foo` to `env.nu` and `source ~/foo` to `config.nu`: https://github.com/ajeetdsouza/zoxide/pull/362/commits/e06c8308f9a714e481decfa50a65073948fe206b

CC @davidkna perhaps Starship can do something similar?

**Comment by hustcer** [comment]
@ajeetdsouza Since you have already found a workaround, and https://www.nushell.sh/book/thinking_in_nushell.html#think-of-nushell-as-a-compiled-language, can we close this issue?
