### ISSUE TITLE
Consolidate methods of finding current directory

### ISSUE THREAD

**Issue by ajeetdsouza** [nushell/nushell#4775]
### Related problem

There are 3 redundant ways to find the current directory:

```
echo $nu.cwd
echo $env.PWD
pwd
```

### Describe the solution you'd like

From the [Zen of Python](https://www.python.org/dev/peps/pep-0020/):

> There should be one-- and preferably only one --obvious way to do it.

**Comment by fdncred** [comment]
lolz - clearly you don't work on windows much which has like 20 ways to do everything. haha. btw - `pwd` is not an internal command any more, however we may add it at some point. I'm guessing the other two are the same 'under the hood' since nearly everything is scoped now.

**Comment by ajeetdsouza** [comment]
Fair enough, though I'd still say we remove `$nu.cwd`. Since we're pre-1.0, we don't have to maintain backward compatibility like Windows does.

**Comment by fdncred** [comment]
ya, we may end up doing that `$nu.cwd` pre-dates `$env.PWD`. i figure we'll keep `$env.PWD` and i also think that we'll eventually add a `pwd` internal command too.
