### ISSUE TITLE
Fix link for Windows Visual C++

### ISSUE THREAD

**Issue by 89z** [nushell/nushell#4776]
Here:

https://github.com/nushell/nushell#local

it has this link:

https://www.microsoft.com/en-us/download/details.aspx?id=52685

that link is not valid anymore, this is the correct link:

https://docs.microsoft.com/cpp/windows/latest-supported-vc-redist

can we please correct it?

**Comment by fdncred** [comment]
Good info. Can you create a PR to update this?

**Comment by 89z** [comment]
no

**Comment by hustcer** [comment]
I will take it
