### ISSUE TITLE
`to csv` with list input doesn't work as expected

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4780]
### Describe the bug

`to csv` with list input doesn't work as expected

### How to reproduce

`[1 2] | to csv -s ','` in latest main get:
```
""
""
""
```
However, in v0.44 will get:
```
1,2
```

### Expected behavior

Should output `1,2`

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | 299fea85                                 |
| commit_hash        | 299fea8538361ff841decbf7d1f7e8ff8dfc7ef9 |
| commit_date        | 2022-03-08 01:17:33 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-08 09:40:37 +08:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | gstat                                    |

**Comment by jntrnr** [comment]
for other folks that see this, you can also use `| str collect ' '`
