### ISSUE TITLE
Allow "fall-through" flags in signatures

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4781]
### Related problem

Currently, signatures accept `...rest` as fall-through positional arguments. It would be nice, if there was a way to do the same for flags and named options (e.g., `..-flags` just for the sake of an example). It would be useful in (at least) two scenarios:

1. Complex external commands with custom completions. With fall-through signature, the [`extern git checkout`](https://github.com/nushell/nushell/blob/cede9b3156d5f90fe95c74f82725abb753d77c7a/docs/sample_config/default_config.nu#L55-L78) signature would not require repeating all the signature parameters:
```
extern "git checkout" [
  branch?: string@"nu-complete git branches" # name of the branch to checkout
  ..-flags
]
```
2. Wrapper commands, for example
```
def valgrind-profile [program, ...rest, ...flags] {
    valgrind  --tool=callgrind --callgrind-out-file=callgrind.out ^$program $rest $flags
}
```

### Describe the solution you'd like

Not sure about the exact implementation and syntax, we would need to brainstorm it.

**Comment by jntrnr** [comment]
on a related note: I'd like a way in the signature to say that calls need to preserve the order of the arguments (rather named or positional) so that it's easier to pass through to externals without doing a lot of additional work.

**Comment by kubouch** [comment]
@jntrnr Can you give an example? I can't imagine what you mean.

**Comment by elferherrera** [comment]
In your first example, it is a flag and a value. Right?

**Comment by jntrnr** [comment]
right

**Comment by kubouch** [comment]
There are two other cases where fall-through signatures would be useful:
* `sudo`: Allow `sudo pacman` to reuse `pacman`'s signature. The `sudo` signature could be 100% fallthrough
* `exec`: I hit it again recently when debugging with gdb: When you debug `a.out -x 4`, gdb will call `exec a.out -x 4` which will fail because `-x` is not `exec`'s flag. It could have 100% fallthrough signature as well.

One corner case is the `-h` flag which we automatically interpret as help, but we should have a way to fallthrough that as well (e.g., `df -h` Unix command uses `-h` flag as "human-readable").

**Comment by lukexor** [comment]
Another example of needing fall-through flags with `cargo`

`cargo run <binary>` where the binary reads arguments from the command line (like with `clap` or `structopt`). There's no reasonable way to define what these flags would be generically for `cargo run`

**Comment by lukexor** [comment]
I think this is related - but `npm` has a similar need to pass flags through. e.g.

in `package.json`:

`"test": "jest",`

`npm run test -h` would execute: `npm run -h`

while

`npm run test -- -h`  would execute: `jest "-h"`

Currently you have to opt-out of the extern by using `^npm` as a work-around.

**Comment by jeroen-meijer** [comment]
I have a separate use case but think fall-through flags (or some way to let _any_ arguments regardless of type fall through to a single variable usable in custom functions) would be very useful.

In my case, I have a function that simply redirects any arguments it gets to an inner function, like so:

```nu
def flutter [...args: any] {
  fvm flutter $args
}
```

All it does is append `fvm` to the command. (An alias doesn't work for me in this case since I want to do more with this command than just redirect arguments to something else.)

However, this call doesn't work at the moment since, for example, passing `--version` to this function throws an error.

I'm new to Nu, however, so I'm not sure if my use case fully applies to this issue. If anybody has a good alternative for this particular problem, let me know. Thx!

**Comment by harrysarson-signaloid** [comment]
When writing a function that wraps and external command I have found that putting the flags in quotes works around this issue:

```nu

def func[...args: any] {
  external_cmd $args
}

# ...

func --flag   # fails
func '--flag' # works

```

**Comment by jntrnr** [comment]
@kubouch - how well is this working these days?

**Comment by kubouch** [comment]
`extern-wrapped` could be used for this purpose, as it forces `...rest` to be strings. Similarly, `extern` also forces all undefined args to be strings. (`extern-wrapped` seems broken currently, needs to be fixed)

**Comment by kubouch** [comment]
The second part of the problem is being able to pass flags to custom commands. We still don't have a mechanism for that, see https://github.com/nushell/nushell/issues/9116

**Comment by kubouch** [comment]
Passing flags to externals seems to be solved with `def --wrapped` and the spread operator, so I'll close it. The remaining issue of passing named flags to Nushell commands is tracked in https://github.com/nushell/nushell/issues/12592.
