### ISSUE TITLE
Span issue with `error make`

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4784]
### Describe the bug

`error make` will give a wrong span if the value is inside a block

Related (possibly duplicate: #4460)

### How to reproduce

```
> def err [x] {
    if $x == 'foo' {
        let span = (metadata $x).span
        error make {
            msg: "Error"
            label: {
                text: "failed"
                start: $span.start
                end: $span.end
            }
        }
    }
}

> err foo
Error:
  × Error
    ╭─[entry #57:1:1]
  1 │     def err [x] {
  2 │ ╭─▶ if $x == 'foo' {
  3 │ │   let span = (metadata $x).span
  4 │ │   error make {
  5 │ │       msg: "Error"
  6 │ │       label: {
  7 │ │           text: "failed"
  8 │ │           start: $span.start
  9 │ │           end: $span.end
 10 │ │       }
 11 │ │   }
 12 │ ├─▶ }
    · ╰──── failed
 13 │     }
    ╰────
```

### Expected behavior

The arrow should point to `foo`.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | 4f43d751                                 |
| commit_hash        | 4f43d75130eb5e62bcb725b62c0dd7f14afacd3c |
| commit_date        | 2022-03-07 01:01:29 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-07 12:33:32 +02:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

### Additional context

Running `error make` directly without the `if` block works as expected.

**Comment by kubouch** [comment]
This bug appears again

**Comment by jntrnr** [comment]
This appears to be fixed in the latest main and now prints:

```
~/Disks> err foo
Error:   × Error
   ╭─[entry #230:1:1]
 1 │ err foo
   ·     ─┬─
   ·      ╰── failed
   ╰────
```
