### ISSUE TITLE
Custom completions do not work when not exported from a module

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4785]
### Describe the bug

When custom completion command is defined within a module but not exported, it doesn't work.

### How to reproduce

```
> module spam {
    def compl [] { [ a b c ] }
    export def foo [x: string@compl] { $x }
}

> use spam foo

> foo <tab>  # nothing happens
```

### Expected behavior

The completion should work in this case.

Not sure how custom completions are implemented but rather than looking up the `compl` name, it should be referenced by DefId.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | 4f43d751                                 |
| commit_hash        | 4f43d75130eb5e62bcb725b62c0dd7f14afacd3c |
| commit_date        | 2022-03-07 01:01:29 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-07 12:33:32 +02:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by jntrnr** [comment]
@kubouch - can you check if https://github.com/nushell/nushell/pull/4801 fixes this issue?
