### ISSUE TITLE
empty? returns list of bools instead of a single bool

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#4786]
### Describe the bug

I think I've found a regression in the `empty?` command; if you pipe it a list, it outputs a new list instead of a scalar value.

### How to reproduce

Run `[red green blue] | empty?`, note that it returns a list of booleans.

### Expected behavior

I expected `empty?` to return a single boolean indicating whether the list it was given is empty.

### Screenshots

![image](https://user-images.githubusercontent.com/26268125/157298811-8758954d-06fe-41dd-a0fe-eb0e953bc449.png)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | 97b3e4a2                                 |
| commit_hash        | 97b3e4a233fa25b3e3f7bbc2fe8db72c263b76b1 |
| commit_date        | 2022-03-03 19:05:55 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-03 12:09:15 -08:00               |
| build_rust_channel | debug                                    |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

### Additional context

There is an example for `empty?` in the docs which is how I first noticed this. https://www.nushell.sh/book/working_with_lists.html

**Comment by hustcer** [comment]
Related issue: https://github.com/nushell/nushell/issues/3903
