### ISSUE TITLE
Keybinding insert plus Enter

### ISSUE THREAD

**Issue by DanielRivasMD** [nushell/nushell#4805]
### Related problem

On keybindings.yml, there is a binding for `Insert` which accepts a sequence of characters. But I have not figure out how to bind 'Enter' at the end of this sequence

### Describe the solution you'd like

An option, or alternative, to bind a sequence of characters plus 'Enter'

**Comment by hustcer** [comment]
Try this example on the latest main:
```
{
        name: reload_config
        modifier: control
        keycode: char_r
        mode: emacs
        event: [
            { edit: { cmd: clear } }
            { edit: { cmd: insertString value: $"source '($nu.config-path)'" } }
            { send: Enter }
        ]
    }
```

**Comment by fdncred** [comment]
ya, it works in 0.59 and above. we're not going to be able to fix this in 0.44. closing.

**Comment by DanielRivasMD** [comment]
Thanks! Why are the releases so behind by `cargo install`, by the way?

**Comment by DanielRivasMD** [comment]
@jntrnr - Amm ok... Good to know now! Big fan of yours by the way.

**Comment by 89z** [comment]
The listed example doesnt work with the current release:

~~~
PS D:\Desktop\nushell-0.60.0> .\nu.exe
Error: nu::shell::unsupported_config_value (link)

  × Unsupported config value
     ╭─[C:\Users\Steven\AppData\Roaming\nushell\config.nu:224:1]
 224 │         event: [
 225 │             { edit: { cmd: insertString value: $"source '($nu.config-path)'" } }
     ·             ──────────────────────────────────┬─────────────────────────────────
     ·                                               ╰── expected reedline EditCommand, got {cmd: insertstringvalue: source 'c:\users\steven\appdata\roaming\nushell\config.nu'}
~~~

**Comment by 89z** [comment]
https://github.com/nushell/nushell/issues/2781
