### ISSUE TITLE
add search terms to extra_usage

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4808]
### Related problem

People can't find what they're looking for.

### Describe the solution you'd like

It would be nice to add search terms to `extra_usage` so that when people use `help -f` they can find what they're looking for. For instance, maybe we add popular encodings to the `decode` command's `extra_usage` statment like `utf-8`, `windows-1252`, others.

maybe we should have common terminology in `extra_usage` like `normal extra_usage text` and then at the end have `search terms: blah1, blah2, blah3`?

**Comment by royb3** [comment]
Sounds like an issue I can work on. I see it has the good first issue tag. Anything I should know besides what's on nushell.sh?

**Comment by fdncred** [comment]
I'd say maybe just be consistent throughout with something like "search terms: ". I guess?

**Comment by rgwood** [comment]
I think this issue has been replaced by #5093, Signature now has a `search_terms()` function that is a better place than `extra_usage`.

**Comment by royb3** [comment]
Yup, that issue seems to describe a better way to go forward now we have the search_terms function.
