### ISSUE TITLE
add extra_usage text from open in 0.44 to decode

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4809]
### Describe the bug

the extra_usage text was accidentally removed from open when porting open, because open doesn't do encoding/decoding any longer. it needs to be put back in, at some point, to `decode` which is where most of the encoding/decoding code landed after the port.

i'm guessing there are other commands where the extra_usage may have been left out too. it's easy to overlook but it's helpful with things like `help -f blah` when searching for something.

### How to reproduce

N/A

### Expected behavior

have the extra_usage from open in decode

### Configuration

|key|value|
|-|-|
|version|0.59.1|
|branch|main|
|short_commit|0d82d7df|
|commit_hash|0d82d7df602dea0e27ff68352157988cdda2b5d4|
|commit_date|2022-03-09 13:05:35 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.59.0 (9d1b2106e 2022-02-23)|
|rust_channel|stable-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.59.0 (49d8809dc 2022-02-10)|
|pkg_version|0.59.1|
|build_time|2022-03-09 07:38:36 -06:00|
|build_rust_channel|debug|
|features|dataframe, default, trash, which, zip|
|installed_plugins|gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml|

**Comment by hustcer** [comment]
Maybe I can try this one

**Comment by fdncred** [comment]
@hustcer have at it, my friend. i'll assign it to you, but if you get tired, let me know and i'll unassign it.

**Comment by fdncred** [comment]
thanks @hustcer !!
