### ISSUE TITLE
mv '[].txt a' crashes, problems with bracket / glob pattern

### ISSUE THREAD

**Issue by FilipAndersson245** [nushell/nushell#4811]
### Describe the bug

Nushell cannot handle Brackets correctly in some cases, example being when trying to `mv` a file containing them. This seem to be the same for multiple commands using `globs`, Would be nice to be able to disable globs if requested.

### How to reproduce

1. Have a file with name containing `[` `]`
2.  use `mv` to move/rename the file.

### Expected behavior

I expect the file to be renamed, without an error.

### Screenshots

![image](https://user-images.githubusercontent.com/17986183/157721663-a5d87cc9-ee19-4c80-a35a-4aa0746751d9.png)

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.59.1                                      |
| branch             | main                                        |
| short_commit       | 14dc662e                                    |
| commit_hash        | 14dc662e505f4aa648240329250c125a6b4c859e    |
| commit_date        | 2022-03-10 13:37:24 +00:00                  |
| build_os           | windows-x86_64                              |
| rust_version       | rustc 1.61.0-nightly (10913c000 2022-03-03) |
| rust_channel       | nightly-x86_64-pc-windows-msvc              |
| cargo_version      | cargo 1.61.0-nightly (3d6970d50 2022-02-28) |
| pkg_version        | 0.59.1                                      |
| build_time         | 2022-03-10 16:13:09 +01:00                  |
| build_rust_channel | release                                     |
| features           | dataframe, default, trash, which, zip       |
| installed_plugins  | gstat                                       |

**Comment by fdncred** [comment]
i personally want to keep globs and even enhance them so we could do `ls [a-z]*.txt` or `ls [a..z]*.txt` but I think we also need to be able to escape them. Maybe we need to add `[` and `]` as escapes so we could do `mv "blah\[something\]" something_else`?

**Comment by fdncred** [comment]
It looks like it's going to take more work than just adding more escape characters. i think we'll need to change how each command interacts with globs or have a helper function somewhere that every command can use when dealing with globs.

**Comment by fdncred** [comment]
@FilipAndersson245 does https://github.com/nushell/nushell/pull/4818 fix this?

**Comment by FilipAndersson245** [comment]
**Yes now it works**

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.59.1                                      |
| branch             | main                                        |
| short_commit       | c023d411                                    |
| commit_hash        | c023d4111a4d59ca6d423e484267916a898e6452    |
| commit_date        | 2022-03-13 18:30:37 +00:00                  |
| build_os           | windows-x86_64                              |
| rust_version       | rustc 1.61.0-nightly (5f4e06771 2022-03-10) |
| rust_channel       | nightly-x86_64-pc-windows-msvc              |
| cargo_version      | cargo 1.61.0-nightly (65c826642 2022-03-09) |
| pkg_version        | 0.59.1                                      |
| build_time         | 2022-03-13 19:56:56 +01:00                  |
| build_rust_channel | release                                     |
| features           | dataframe, default, trash, which, zip       |
| installed_plugins  | gstat                                       |
