### ISSUE TITLE
Change `=~` and `!~` to match regex instead of substring

### ISSUE THREAD

**Issue by adamkpickering** [nushell/nushell#4817]
### Related problem

First: nushell is great! Keep up the great work!!

I have two related ideas:

1. It seems to me that the `where` and `find` commands are redundant: both of them have to do with filtering lists of things. It seems that `find` is intended for single-dimensional lists (i.e. `[moe larry curly]`) whereas `where` is intended for tables. Also, it seems that `find` can do regex, whereas `where` cannot.

    I'm sure there are technical reasons for having two commands, but as a user this is unintuitive. I feel that there should be a single command that can be used for filtering lists of things down to smaller lists of things.

2. The `where` command has the `=~` operator for finding substrings. This works great, but I think it could be better: the `=~` operator could be the "regex matching" operator. If this were the case, no functionality would be lost (substring matching is a subset of the functionality of regex) and much would be gained.

    Also, this is how `bash` works. I don't want `nu` to be `bash`, but there is a precedent that would make it easier for many people to learn and adopt nushell.

### Describe the solution you'd like

I propose abolishing the `find` command and merging its functionality into `where`. Funny enough, this is kind of supported at the moment:
```
[moe larry curly] | find l
```
seems to be equivalent to
```
[moe larry curly] | where $it =~ l
```
Of course, `where` does not have the regex functionality that `find` does. If `=~` became the regex operator as I described above, much of the functionality would be replaced. Then instead of
```
[moe larry curly] | find --regex 'l.*y'
```
you could do
```
[moe larry curly] | where $it =~ 'l.*y'
```
There is other functionality that `find` has:

`--insensitive`: easily replaced by using `(?i)` in your regex.
`--multiline`: easily replaced by piping the input into `lines` before filtering.
`--dotall`: seems "anti-nu" and best left to an external command like `grep` if you ever need to do this.
`--invert`: could be done using the `!~` operator in `where`.

As for the `--predicate` option I'm not so sure what to do with it. This is the realm of `filter` functions in other languages. But it seems redundant to have a `where` command and a `filter` command. But then again, there is a `reduce` command. `filter` may be the best way to go with this.

What do you think?

**Comment by kubouch** [comment]
We chatted about `=~` being regex once (@andrasio) and it might be a good idea. We just need to make sure we don't compile the regex expression every `where` iteration for performance reasons. But yeah, we could have a regex operator and use `in`/`not-in` for substring matching.

One use of `find` you missed is searching through the whole table (e.g., `help commands | find filters`) -- I'd say this is the primary use case (at least for me) so I would still keep it.

**Comment by fdncred** [comment]
iirc, I originally added the `find` command so that you can look through columnar data without needing to know what column the data you're looking for is in. I'd prefer to retain that functionality. I also want to add highlighting of the search term in the hit results as I originally intended.

**Comment by adamkpickering** [comment]
> One use of find you missed is searching through the whole table (e.g., help commands | find filters) -- I'd say this is the primary use case (at least for me) so I would still keep it.

That's good to know about, I've been looking for a way to do that! How about this for an equivalent `where` syntax:

```
$table | where * =~ filters
```

> only people who know regex can remember all that mess. I'd rather it be easy to use.

There's a part of me that wants to say that regex is the standard DSL for string matching, and that knowledge of it is something that everyone should have if they're using the command line. But ultimately the `(?i)` syntax is neither readable nor common (I've never seen it in the wild, nor was I aware of it before this), so maybe extra flags are needed. It just seems like a shame to have multiple commands for very similar tasks.

Perhaps these flags could be added to `where`? I'm all out of ideas 🤷

**Comment by kubouch** [comment]
`where` and `find` fulfill two different tasks: `where` filters the input stream and `find` looks up string/regex matches. You can use `where` for whatever row condition you want, e.g. `1..10 | where $it > 3`, not limited to just strings. Collapsing them into one command would, in my opinion, introduce too much mental overhead.

However, I support the `=~` and `!~` to operate as regex and have `in` and `not-in` for substring matches.

**Comment by adamkpickering** [comment]
Ok that is fair. I hope I haven't been `--insensitive` :grin:

> However, I support the =~ and !~ to operate as regex and have in and not-in for substring matches.

That would be great!

**Comment by kubouch** [comment]
@adamkpickering Haha, no worries :-D . I'll change the issue title to reflect the `=~` regex proposal, please let me know if you have any objections.

**Comment by rgwood** [comment]
I like this proposal a lot (specifically point 2: change the `=~` and `!~` operators to use regex), and I'd like to volunteer to implement it.

I love the convenient syntax of `=~` and `!~`, but I've frequently been frustrated by their limited utility. Changing the operators to use regex feels right for many reasons:

- It's backwards-compatible
- It does not add new symbol-based operators (JT has stated a preference to keep these to a minimum)
- When used with `where`, it's more ergonomic/concise than a new `str match` command would be
- It's in line with existing Bash behavior

**Comment by fdncred** [comment]
The initial presumption that `find` is not for tables is incorrect. See the [announcement here](https://www.nushell.sh/blog/2021-09-14-nushell_0_37.html#finding-data-in-tables) and the [PR here](https://github.com/nushell/nushell/pull/3971).

I'm not interested in losing the `find` command, especially since it now contains all the previously-known-as `match` command's functionality.

What i'd like to do, although it may not be popular, is to add two more operators.

* `=$` which means `ends_with` to go along with the recently added `=^` which means `starts_with`
* `=r` which means find with regex, so now you could use `where column_name =r some_regex`

**Comment by rgwood** [comment]
We discussed this a bit more on Discord; the short version is that I'll try adding regex support to `=~` and `!~`.

**Comment by fdncred** [comment]
very nice
<img width="547" alt="Screen Shot 2022-04-07 at 6 27 04 AM" src="https://user-images.githubusercontent.com/343840/162188908-75a1305f-0f40-4d53-9cc5-56279b237a7f.png">
