### ISSUE TITLE
Which shows hidden items

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4820]
### Describe the bug

Currently, `which` does not respect if a command/alias was hidden

### How to reproduce

1. `alias foo = echo foo`
2. `hide foo`
3. `which foo` # still shows the alias

### Expected behavior

It shouldn't show hidden definitions / aliases

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | 14dc662e                                 |
| commit_hash        | 14dc662e505f4aa648240329250c125a6b4c859e |
| commit_date        | 2022-03-10 13:37:24 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-10 16:08:48 +02:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | gstat                                    |

**Comment by hustcer** [comment]
Maybe a Related issue of this one: https://github.com/nushell/nushell/issues/4550

**Comment by kubouch** [comment]
Yes, thanks, they both should respect hiding.

**Comment by kubouch** [comment]
Also related: https://github.com/nushell/nushell/issues/4504

`which` needs to be fixed.
