### ISSUE TITLE
Alias to source shouldn't source the script

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4822]
### Describe the bug

When defining `alias foo = (source foo.nu)`, it will parse the script with side effects.

This is currently preventing Python virtualenv from working.

### How to reproduce

Have two scripts:
```
# activate-foo.nu

alias foo = echo foo
alias deactivate-foo = (source deactivate-foo.nu)
```

```
# deactivate-foo.nu

hide foo
```

Then,
```
> source ./activate-foo.nu         

> deactivate-foo 
Error: nu::parser::not_found (https://docs.rs/nu-protocol/0.59.1/nu-protocol/enum.ShellError.html#variant.NotFound)

  × Not found.
   ╭─[deactivate-foo.nu:1:1]
 1 │ hide foo
   ·      ─┬─
   ·       ╰── did not find anything under this name
   ╰────
```

The reason why this happened is that when defining the `alias deactivate-foo = (source deactivate-foo.nu)`, the parser will go into `deactivate-foo.nu` and `hide foo`. Then, when `deactivate-foo` is called, the `foo` is already hidden.

### Expected behavior

Defining an alias with source should not have side effects. Only running the alias should.

Perhaps the alias definition could have a throwaway scope frame? Not sure what would the best fix be...

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | 14dc662e                                 |
| commit_hash        | 14dc662e505f4aa648240329250c125a6b4c859e |
| commit_date        | 2022-03-10 13:37:24 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-10 16:08:48 +02:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | gstat                                    |

**Comment by xxuun** [comment]
I faced this problem, is there any idea?

>  Error: nu::parser::cant_alias_expression

>  × Can't create alias to expression.
>     ╭─[C:\Users\Administrator\AppData\Roaming\nushell\config.nu:894:23]
> 893 │
> 894 │ alias venv_activate = (source C:\Users\Administrator\AppData\Roaming\nushell\venv.nu)
>     ·                       ───────────────────────────────┬───────────────────────────────
>     ·                                                      ╰── aliasing FullCellPath is not supported
>     ╰────
>  help: Only command calls can be aliased.

**Comment by kubouch** [comment]
Aliases were changed to alias command names with parameters only, you can't alias subexpressions. The above case could be written as a custom command, e.g. `def --env venv-activate { source ... }`.

It should be possible to do `alias venv-activate = source ...`, but we'd need someone to make a PR for it, currently only the `overlay ...` are aliasable parser keywords. If you're trying to activate a Python virtual environment, you might indeed need `overlay use` instead of `source`, see https://github.com/pypa/virtualenv/blob/b6c052bdac73138251dc46abda6154f3a0bf8a14/src/virtualenv/activation/nushell/activate.nu

**Comment by xxuun** [comment]
> Aliases were changed to alias command names with parameters only, you can't alias subexpressions. The above case could be written as a custom command, e.g. `def --env venv-activate { source ... }`.
> 
> It should be possible to do `alias venv-activate = source ...`, but we'd need someone to make a PR for it, currently only the `overlay ...` are aliasable parser keywords. If you're trying to activate a Python virtual environment, you might indeed need `overlay use` instead of `source`, see https://github.com/pypa/virtualenv/blob/b6c052bdac73138251dc46abda6154f3a0bf8a14/src/virtualenv/activation/nushell/activate.nu

Yes I use overlay now, appreciate for your reply!
