### ISSUE TITLE
Invalid history_previous binding in default config

### ISSUE THREAD

**Issue by TheMatten** [nushell/nushell#4825]
### Describe the bug

On fresh installation, accepting default configuration, shell reports this error after every command:
```
Error: nu::shell::unsupported_config_value (link)

  × Unsupported config value
     ╭─[/home/USER/.config/nushell/config.nu:235:1]
 235 │           { send: menupageprevious }
 236 │           { send: edit, cmd: undo }
     ·           ────────────┬────────────
     ·                       ╰── expected Reedline event, got edit
 237 │         ]
     ╰────
```
Looking at other code, it seems like mentioned the line (https://github.com/nushell/nushell/blob/ccc85a29795e8eb1f9a6b63790ba4b48da274939/docs/sample_config/default_config.nu#L236) should be
```
{ edit: { cmd: undo } }
```
instead, which seems to fix the issue (though I'm not really familiar with keybinds configuration).

### How to reproduce

1. accept default configuration on first run

### Expected behavior

The error should not appear.

**Comment by fdncred** [comment]
Thanks. fixed it with #4826
