### ISSUE TITLE
Treat Programs exit status as "If/where" condition

### ISSUE THREAD

**Issue by storyfeet** [nushell/nushell#4830]
### Related problem

I've been trying to work out how to take the exit status from a program and use it in an if / where condition

If the file exists then don't download it again.

```
open file_list.json | where "Magic to say file doesn't exist locally" | each {|f| curl $"site.com/($f.name} --output $f.name}

```
or words to that effect.

I can't find it in the docs, My plan was to use the "file" program's exit status, but can't seem to make it work in the condition

I'm currently using version 0.44.0 on linux

In the docs I came across a phrase called "complete" which ought to have done the job, but it doesn't seem to exist in 0.44.0

### Describe the solution you'd like

If this exists, I'd like to see how to do it in the book,
Otherwise, a means to turn exit statuses into boolean/numeric values within an if clause

**Comment by rgwood** [comment]
Hi @storyfeet,

> In the docs I came across a phrase called "complete" which ought to have done the job, but it doesn't seem to exist in 0.44.0

That's correct, `complete` is relatively new (and it won't be backported). If you'd like, you could give the latest Nu version a try; beta binaries are available [here](https://www.nushell.sh/blog/2022-03-01-nushell_0_59.html) and you can also build this repo from source.

**Comment by hustcer** [comment]
@storyfeet  Please install the latest nu v0.62 or build from the latest main branch instead, thanks
and sorry for the inconvenient
