### ISSUE TITLE
Bake in LIB_DIRS so they can be used in config.nu

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#4845]
### Related problem

Currently, LIB_DIRS and PLUGIN_DIRS is defined only in the default config file. However, that makes them impossible to use within the config file (you cannot source from LIB_DIRS inside config.nu since the environment values are not yet merged into the engine state when source parsing happens).

### Describe the solution you'd like

Bake the default directories into the binary when Nushell starts so they're usable within `config.nu`

**Comment by hustcer** [comment]
@kubouch Can we close this issue? Anything else should be done?

**Comment by hustcer** [comment]
I will close it now, Please reopen if this doesn't work
