### ISSUE TITLE
Dataframe crashes nushell when reading JSON with an empty object field

### ISSUE THREAD

**Issue by Mathspy** [nushell/nushell#4847]
### Describe the bug

`nushell` panics when attempting to read a dataframe that contains a field that is an empty object with the following error:

```
thread 'main' panicked at 'assertion failed: !fields.is_empty()', /Users/mathspy/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow2-0.9.2/src/array/struct_/mod.rs:75:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### How to reproduce

Run `dfr open test.json` where `test.json` contains the following:

```json
{"example":{}}
```

### Expected behavior

Should produce an error saying the field is empty, or ignore it implicitly but not crash

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | 10d805c1                                 |
| commit_hash        | 10d805c1fae2d4f71e6c039c2318ab0a0c1c9427 |
| commit_date        | 2022-03-14 12:41:09 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-14 10:14:22 -04:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by hustcer** [comment]
A field with an empty object is quite common, I think we should fix this in v0.60

**Comment by hustcer** [comment]
> Unfortunately that's not in our plate. That is polars JSON parser. Can you add this issue there?

okay，I will fill a ticket later

**Comment by hustcer** [comment]
Currently no crash happened:
```
open-df t.json
Error:
  × Json reader error
   ╭─[entry #38:1:1]
 1 │ open-df t.json
   · ───┬───
   ·    ╰── ArrowError(NotYetImplemented("read an Array from a non-Array JSON"))
   ╰────
```
I think we can close this issue now
