### ISSUE TITLE
Dataframe crashes nushell when reading an empty JSON file

### ISSUE THREAD

**Issue by Mathspy** [nushell/nushell#4848]
### Describe the bug

`nushell` panics when attempting to read a dataframe from an empty JSON file:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/mathspy/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-core-0.19.1/src/utils/mod.rs:659:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### How to reproduce

Run `dfr open test.json` where `test.json` contains nothing.

### Expected behavior

Should produce an error saying the file is empty

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | 10d805c1                                 |
| commit_hash        | 10d805c1fae2d4f71e6c039c2318ab0a0c1c9427 |
| commit_date        | 2022-03-14 12:41:09 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-14 10:14:22 -04:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by hustcer** [comment]
No panic happened with nu v0.73:
```
open-df t.json
Error:
  × Json reader error
   ╭─[entry #39:1:1]
 1 │ open-df t.json
   · ───┬───
   ·    ╰── ComputeError(Owned("InvalidEOF"))
   ╰────
```
Close it now
