### ISSUE TITLE
Passing flag parameter with variable to external commands not work as expected

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4860]
### Describe the bug

Passing flag parameter with variable to external commands not work as expected

### How to reproduce

In nushell repo run `let author = 'JT'; git log -n 1 --author=$author` will get nothing output
And positional parameters work well, we have to use `nu -c $'git log -n 1 --author=($author)'` as a workaround

### Expected behavior

The output should be same as `git log -n 1 --author=JT`

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | 9db356e1                                 |
| commit_hash        | 9db356e174288e74f7b5374d679b72907731eb70 |
| commit_date        | 2022-03-17 02:29:52 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-17 11:01:03 +08:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | gstat                                    |

**Comment by fdncred** [comment]
I would also think that this would work but it returns an error too. `^$"git log -n 1 --author=($author)"`

```
Error: nu::shell::external_command (link)

  × External command
   ╭─[entry #9:1:1]
 1 │ ^$"git log -n 1 --author=($author)"
   ·  ─────────────────┬────────────────
   ·                   ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)
```

**Comment by hustcer** [comment]
@fdncred Can we fix it in v0.60?

**Comment by fdncred** [comment]
It would be nice if we could.

**Comment by hustcer** [comment]
@jntrnr It's found that `let author = 'JT'; git log -n 1 $'--author=($author)'` does not work but `let author = 'JT'; git log -n 1 $"--author=($author)"` works, It's acceptable. If we have no better choice I can close this issue, How do you think?

**Comment by jntrnr** [comment]
@hustcer - I added https://github.com/nushell/nushell/pull/4867 to help with the first case that doesn't currently work

**Comment by hustcer** [comment]
> @hustcer - I added #4867 to help with the first case that doesn't currently work

Great, then close it after the first case work?

**Comment by jntrnr** [comment]
@hustcer - yeah, it's landed now. If that works for you, you can close it.

**Comment by hustcer** [comment]
`let author = 'JT'; git log -n 1 $'--author=($author)'` works now
