### ISSUE TITLE
nu-0.59.1 build failure

### ISSUE THREAD

**Issue by 0323pin** [nushell/nushell#4861]
### Describe the bug

`nu`-0.59.1 from commit 9db356e174288e74f7b5374d679b72907731eb70 fails to build on NetBSD.

First attempt to build fails since NetBSD `libc` doesn't support `trash-support`

I've disabled this feature at build time and have the following features enabled, "plugin", "which", "zip-support".

But, I'm hitting the following build error,

```
Compiling nu-command v0.59.1 (/usr/pkgsrc/wip/nushell/work/nushell-9db356e174288e74f7b5374d679b72907731eb70/crates/nu-command)
error[E0425]: cannot find function `collect_proc` in crate `nu_system`
  --> crates/nu-command/src/system/ps.rs:74:28
   |
74 |     for proc in nu_system::collect_proc(Duration::from_millis(100), false) {
   |                            ^^^^^^^^^^^^ not found in `nu_system`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `nu-command` due to previous error
*** Error code 101

Stop.
```

### How to reproduce

Build `nu` from git-HEAD

### Expected behavior

Build finishes successfully.

### Additional context

OS: NetBSD-current (9.99.94)
Rust: 1.59.0

**Comment by jntrnr** [comment]
@0323pin - we can add build flags to ignore that call like @fdncred mentions. @0323pin - if you comment out that section, does it succeed in building?

**Comment by 0323pin** [comment]
@jntrnr I can try tonight or, if I don't have time, early tomorrow.

**Comment by 0323pin** [comment]
@jntrnr do you mean to remove the whole section from line 74 until the end of `ps.rs`? Sorry if this sounds weird but, I'm not a programmer 😞 

In that case, I get this

```
error[E0425]: cannot find function `run_ps` in this scope
  --> crates/nu-command/src/system/ps.rs:40:9
   |
40 |         run_ps(engine_state, call)
   |         ^^^^^^ not found in this scope

warning: unused import: `std::time::Duration`
 --> crates/nu-command/src/system/ps.rs:1:5
  |
1 | use std::time::Duration;
  |     ^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused imports: `IntoInterruptiblePipelineData`, `ShellError`, `Value`
 --> crates/nu-command/src/system/ps.rs:6:24
  |
6 |     Category, Example, IntoInterruptiblePipelineData, PipelineData, ShellError, Signature, Value,
  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                ^^^^^^^^^^             ^^^^^

For more information about this error, try `rustc --explain E0425`.
warning: `nu-command` (lib) generated 2 warnings
error: could not compile `nu-command` due to previous error; 2 warnings emitted
*** Error code 101

Stop.
```

Just for the record, `ps` and `sys` commands have never worked due to lack of support in `sysinfo` (https://github.com/GuillaumeGomez/sysinfo/issues/631). I've been discussing the possibility of setting-up a CI internally but, I still have no concrete plan.

**Comment by fdncred** [comment]
I'm thinking you might need some conditional compilation maybe like this in `lib.rs`

```rust
#[cfg(target_os = "linux")]
mod linux;
#[cfg(target_os = "macos")]
mod macos;
#[cfg(not(target_os = "linux"))]
#[cfg(not(target_os = "macos"))]
#[cfg(not(target_os = "windows"))]
mod other;
#[cfg(target_os = "windows")]
mod windows;

#[cfg(target_os = "linux")]
pub use self::linux::*;
#[cfg(target_os = "macos")]
pub use self::macos::*;
#[cfg(not(target_os = "linux"))]
#[cfg(not(target_os = "macos"))]
#[cfg(not(target_os = "windows"))]
pub use self::other::*;
#[cfg(target_os = "windows")]
pub use self::windows::*;
```
and add an `other.rs` that doesn't really do anything but exposes the function. maybe like this.
```rust
use std::time::Duration;

pub struct ProcessInfo;

pub fn collect_proc(_interval: Duration, _with_thread: bool) -> Vec<ProcessInfo> {
    vec![]
}
```
this way, when ps calls `collect_proc` there is a function of "other" oses and it just returns an empty vec. I'm not sure how to test this since I don't have that os but it's an idea.

**Comment by 0323pin** [comment]
@fdncred Thanks! I can test this would it possible to get these in patch format?

Forgot to add that `ps` works if I shell-out of `nu` into `ksh` using `^ps`
As for `sys` it outputs non-sense,

```
/home/pin()
2022-03-18 13:04 > sys | to md --pretty
| host         | mem                                   |
| ------------ | ------------------------------------- |
| [row uptime] | [row total free swap total swap free] |
```

**Comment by 0323pin** [comment]
@fdncred yes, I know this. I'm trying to build from the latest git-commit in the main branch. I was just pointing out the historical trouble with `ps`.

**Comment by fdncred** [comment]
oh, ok. i'm sorry, i misunderstood you. the 0.59.1 uses a combination of procs and sysinfo and other stuff we found.

**Comment by 0323pin** [comment]
> i don't know how to generate a patch.

😄 I've already patched `lib.rs` and added `other.rs` the build is running.
`other.rs` should be inside `/crates/nu-command` correct?

Let's see if I also need to patch `ps.rs`.

**Comment by fdncred** [comment]
`others.rs` needs to be here `/crates/nu-system/src/others.rs` and the `lib.rs` that needs changing is `/crates/nu-system/src/lib.rs`

**Comment by 0323pin** [comment]
I've tested your changes and appreciate your help.
Now, I get the following,

```
error[E0599]: no method named `pid` found for struct `ProcessInfo` in the current scope
  --> crates/nu-command/src/system/ps.rs:80:23
   |
80 |             val: proc.pid() as i64,
   |                       ^^^ method not found in `ProcessInfo`

error[E0599]: no method named `name` found for struct `ProcessInfo` in the current scope
  --> crates/nu-command/src/system/ps.rs:86:23
   |
86 |             val: proc.name(),
   |                       ^^^^ method not found in `ProcessInfo`
   |
   = help: items from traits can only be used if the trait is implemented and in scope
note: `HashDigest` defines an item `name`, perhaps you need to implement it
  --> crates/nu-command/src/hash/generic_digest.rs:7:1
   |
7  | pub trait HashDigest: digest::Digest + Clone {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `status` found for struct `ProcessInfo` in the current scope
  --> crates/nu-command/src/system/ps.rs:95:27
   |
95 |                 val: proc.status(),
   |                           ^^^^^^ method not found in `ProcessInfo`

error[E0599]: no method named `cpu_usage` found for struct `ProcessInfo` in the current scope
   --> crates/nu-command/src/system/ps.rs:102:23
    |
102 |             val: proc.cpu_usage(),
    |                       ^^^^^^^^^ method not found in `ProcessInfo`

error[E0599]: no method named `mem_size` found for struct `ProcessInfo` in the current scope
   --> crates/nu-command/src/system/ps.rs:108:23
    |
108 |             val: proc.mem_size() as i64,
    |                       ^^^^^^^^ method not found in `ProcessInfo`

error[E0599]: no method named `virtual_size` found for struct `ProcessInfo` in the current scope
   --> crates/nu-command/src/system/ps.rs:114:23
    |
114 |             val: proc.virtual_size() as i64,
    |                       ^^^^^^^^^^^^ method not found in `ProcessInfo`

error[E0599]: no method named `command` found for struct `ProcessInfo` in the current scope
   --> crates/nu-command/src/system/ps.rs:121:27
    |
121 |                 val: proc.command(),
    |                           ^^^^^^^ method not found in `ProcessInfo`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `nu-command` due to 7 previous errors
*** Error code 101

Stop.
```

`ps.rs` still needs something else.

**Comment by 0323pin** [comment]
@fdncred started another build, will report back.

**Comment by 0323pin** [comment]
I will double check all the patches and re-try. The last build failed in the same way as the previous.
No more time today, though.

**Comment by fdncred** [comment]
that's odd - i would think that `vec![]` would evaluate to `.is_empty()`

**Comment by 0323pin** [comment]
@fdncred I'm building from a fork I've created to make patching more flexibel. You can check the diffs and see if you spot anything obvious, https://github.com/0323pin/nushell

**Comment by fdncred** [comment]
a quick glance at your changes and i think they look right. i'm not sure what is going on.

**Comment by 0323pin** [comment]
Maybe @jntrnr can spot something. Thanks for looking.
I can start another build tomorrow on a clean directory, just to make sure.

**Comment by jntrnr** [comment]
Just from looking at the error, it seems like there isn't any *bsd support for `ProcessInfo`? Not sure why else all those methods would be missing. My hunch is that nu-system might need some bsd-specific fixes it doesn't have just yet

**Comment by 0323pin** [comment]
> it seems like there isn't any *bsd support for ProcessInfo

Are you using an external crate for these or, internal code?
I guess, the question is what is needed to and required support?

I've imported nushell-0.34.0 into NetBSD and been using it since. It would be sad if we can't keep updating the package.
Anything I can do?

**Comment by 0323pin** [comment]
I already knew this but for the record the build fails on a clean build environment with the following error,

```
   Compiling nu-command v0.59.1 (/usr/pkgsrc/wip/nushell/work/nushell-ae46d2e46ee4369020f4a835816448a0f0feab98/crates/nu-command)
error[E0599]: no method named `pid` found for struct `ProcessInfo` in the current scope
  --> crates/nu-command/src/system/ps.rs:82:27
   |
82 |                 val: proc.pid() as i64,
   |                           ^^^ method not found in `ProcessInfo`

error[E0599]: no method named `name` found for struct `ProcessInfo` in the current scope
  --> crates/nu-command/src/system/ps.rs:88:27
   |
88 |                 val: proc.name(),
   |                           ^^^^ method not found in `ProcessInfo`
   |
   = help: items from traits can only be used if the trait is implemented and in scope
note: `HashDigest` defines an item `name`, perhaps you need to implement it
  --> crates/nu-command/src/hash/generic_digest.rs:7:1
   |
7  | pub trait HashDigest: digest::Digest + Clone {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no method named `status` found for struct `ProcessInfo` in the current scope
  --> crates/nu-command/src/system/ps.rs:97:31
   |
97 |                     val: proc.status(),
   |                               ^^^^^^ method not found in `ProcessInfo`

error[E0599]: no method named `cpu_usage` found for struct `ProcessInfo` in the current scope
   --> crates/nu-command/src/system/ps.rs:104:27
    |
104 |                 val: proc.cpu_usage(),
    |                           ^^^^^^^^^ method not found in `ProcessInfo`

error[E0599]: no method named `mem_size` found for struct `ProcessInfo` in the current scope
   --> crates/nu-command/src/system/ps.rs:110:27
    |
110 |                 val: proc.mem_size() as i64,
    |                           ^^^^^^^^ method not found in `ProcessInfo`

error[E0599]: no method named `virtual_size` found for struct `ProcessInfo` in the current scope
   --> crates/nu-command/src/system/ps.rs:116:27
    |
116 |                 val: proc.virtual_size() as i64,
    |                           ^^^^^^^^^^^^ method not found in `ProcessInfo`

error[E0599]: no method named `command` found for struct `ProcessInfo` in the current scope
   --> crates/nu-command/src/system/ps.rs:123:31
    |
123 |                     val: proc.command(),
    |                               ^^^^^^^ method not found in `ProcessInfo`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `nu-command` due to 7 previous errors
*** Error code 101

Stop.
```

**Comment by grtcdr** [comment]
`nu-system` appears to be only available for Windows, macOS and Linux only at the moment. Which is why you're seeing all those `no method named` errors.

**Comment by 0323pin** [comment]
@grtcdr Hi my friend, thanks for jumping in, appreciated.

The failing build has all the above patches included though. `lib.rs` in my build is as follows, as suggested by @fdncred 
```

#[cfg(target_os = "linux")]
mod linux;
#[cfg(target_os = "macos")]
mod macos;
#[cfg(not(target_os = "linux"))]
#[cfg(not(target_os = "macos"))]
#[cfg(not(target_os = "windows"))]
mod other;
#[cfg(target_os = "windows")]
mod windows;

#[cfg(target_os = "linux")]
pub use self::linux::*;
#[cfg(target_os = "macos")]
pub use self::macos::*;
#[cfg(not(target_os = "linux"))]
#[cfg(not(target_os = "macos"))]
#[cfg(not(target_os = "windows"))]
pub use self::other::*;
#[cfg(target_os = "windows")]
pub use self::windows::*;
```

**Comment by grtcdr** [comment]
Has the patch helped in getting a successful build?

**Comment by 0323pin** [comment]
@grtcdr nope. The error above is with all the 3 patches provided earlier by @fdncred

**Comment by grtcdr** [comment]
The patch needs to implement all the methods that are reported as not having been defined in the crate.

**Comment by grtcdr** [comment]
At this point, the patch should just be implemented in `nu-system`.

**Comment by 0323pin** [comment]
@grtcdr I'd have to agree with this

**Comment by jntrnr** [comment]
We'd be happy to take a PR to `nu-system` by someone familiar with netbsd. What @grtcdr suggests creating a `netbsd.rs` definitely sounds like a good way to do it.

**Comment by grtcdr** [comment]
I could help you achieve that, but I'll have to setup a new NetBSD environment from scratch, which could take me a while due to my terrible internet connection. Would you like me to do that?

**Comment by 0323pin** [comment]
@grtcdr that would be awesome.
Although, I would like to help and learn a bit more, so maybe next time I get at least a start.

**Comment by grtcdr** [comment]
The first thing that comes to mind for me is to lay out a barebones implementation of [ProcessInfo](https://github.com/nushell/nushell/blob/01c1e5e8b0e243dbf7dfc4d3673e6f3f629ace30/crates/nu-system/src/linux.rs#L177), where we can make use of a handy macro that Rust provides called `todo!()`. This satisfies the compiler's needs to a certain degree, so that it doesn't scream back saying the method doesn't exist. We'll do this for every function, until we can begin the real work and actually implement the functionalities that `ProcessInfo` exposes.

**Comment by 0323pin** [comment]
Closing this now as a potential solution is more complex than what I can handle. @grtcdr thank you for looking and for your patches, the build now fails to compile the `procfs` crate, as this is Linux only.

`nushell-0.44.0` will be available as legacy package for sometime.

**Comment by jntrnr** [comment]
@0323pin - you could leave this open and see if someone else with bsd experience can help.

**Comment by 0323pin** [comment]
@jntrnr Appreciate your thought, I'll re-open this.
I'll share it with my fellow NetBSD developers, the amount of work required is rather large, though.

**Comment by 0323pin** [comment]
I'm actually thinking that a NetBSD implementation might be closer to the existing implementation for MacOS, rather than the Linux one. I might kick a build after the weekend using,

```
[target.'cfg(target_os = "macos", target_os="netbsd"))'.dependencies]
libproc = "0.10"
errno = "0.2"
users = "0.11"
which = "4"
libc = "0.2"
```

**Comment by 0323pin** [comment]
@jntrnr Ok, the above won't really work at the moment, neither `procfs` or, `libproc` have support for any of the *BSDs.

Lets take one step at the time, though. I found someone willing to help :)
Could you please list all stuff (pid, env, full-cmd, thread-list?, ...) that's needed to implement `netbsd.rs`?
Thanks!

**Comment by fdncred** [comment]
@0323pin if you look at this function, you can see what each platform (Mac, linux, windows) is returning by looking at the cols.push() lines. https://github.com/nushell/nushell/blob/8a9cc33aacf978d95617f79252025a7204d0109d/crates/nu-command/src/system/ps.rs#L69-L149

**Comment by 0323pin** [comment]
@fdncred Thanks.

**Comment by hustcer** [comment]
@0323pin  Guess this issue should be fixed by https://github.com/nushell/nushell/pull/6456, Can you have a try on the latest main branch?

**Comment by 0323pin** [comment]
This was unexpected ... yes, looking at the changes, it should have fixed it.
I'll try a build when I find the time and report back. Let's keep this open until then.
Thanks for reaching out.

**Comment by 0323pin** [comment]
@hustcer So, I couldn't wait that long 😄 

I've just built from git-HEAD with the following features enabled, `plugin` and `which-support`, `trash-support` has always failed. But, I should try again as it seams the trash crate has evolved recently.

I will try also enabling `dataframe` and `database` features later.

**Comment by 0323pin** [comment]
@jntrnr Any hint on when 0.67.1 will be released? We are still providing pre-compiled binaries for 0.44.0 and it would be nice to bump this to the 0.6x.x series.

**Comment by 0323pin** [comment]
Alright, I'll close this issue now.
All the following features can be enabled and build fine, `plugin`, `which-support`, `dataframe` and `database`.

The `trash-support` feature still causes the build to fail, so I'll leave it out for now. `dataframe` and `database` are now set as optional build features that can be enabled by the user. Default build is set with `plugin` and `which-support` enabled.
Everything is ready to update the package, as soon as a new release is out.

Thanks!

**Comment by fdncred** [comment]
@0323pin We plan on releasing 0.68.0 on Sept 6

**Comment by 0323pin** [comment]
Updated, http://mail-index.netbsd.org/pkgsrc-changes/2022/09/06/msg260136.html
