### ISSUE TITLE
Alias disappeared after been used once 

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4868]
### Describe the bug

I have just installed the latest main and found that alias disappeared after been used once 

### How to reproduce

Run `alias lll = ls -l; $nu.scope.aliases | where alias == lll` will get:
```
  #   alias   expansion
─────────────────────────
  0   lll     ls -l
```
And run `lll` then `$nu.scope.aliases | where alias == lll` will get nothing output, Alias `lll` disappeared without `hide`

### Expected behavior

`$nu.scope.aliases | where alias == lll` should have `lll` alias unless I hide it

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | 7773c4cd                                 |
| commit_hash        | 7773c4cd4d29ba2d1abe04230d9424804bb23671 |
| commit_date        | 2022-03-18 06:59:28 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-18 16:07:19 +08:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | query, query json, query web, query xml  |

**Comment by kubouch** [comment]
It might be similar to https://github.com/nushell/nushell/issues/4838

**Comment by hustcer** [comment]
> It might be similar to #4838

I'm not quit sure, #4838 was 5days ago, but this issue seems occurred in the last two days, I almost build it everyday

**Comment by kubouch** [comment]
It might be related to this PR: https://github.com/nushell/nushell/pull/4858

**Comment by kubouch** [comment]
Yeah, after running an alias, it's not visible anymore:
```
> alias lll = ls -l
> lll
... prints table
> lll
... error: can't run executable
```

**Comment by eggcaker** [comment]
it's working  with any issue on commit 6700fbeed72ad9f6cfc7943e85b4fc20cca09dc7

**Comment by jntrnr** [comment]
Confirmed. Looking into it now
