### ISSUE TITLE
command to list nushell escapes

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4869]
### Related problem

I was thinking that it may be nice to have a command that lists our characters that can be escaped, found here https://github.com/nushell/nushell/blob/4f05e9f4a6eb0a7b494926213c9ae1e42b9c6b8d/crates/nu-parser/src/parser.rs#L2166-L2324

Or maybe it's good enough just to document them in our book?

### Describe the solution you'd like

command or documentation

**Comment by stormasm** [comment]
@fdncred agreed, also it would be nice to explain this concept, why it is important, why you need it etc...  honestly, I am not sure exactly how it works and why we need it, what it does etc...

the only mention in the book of escaping (according to algolia) is here:

https://www.nushell.sh/old_book/escaping.html#escaping-to-the-system

which is unrelated to (I believe) to what we are discussing in this issue...

**Comment by fdncred** [comment]
> ...  I am not sure exactly how it works and why we need it, what it does etc...

This was introduced with #4706 and i added to it in #4772

It's when the double quotes and single quotes became different. This is how it works.

So, this `"one\ntwo"` outputs
```
one
two
```
whereas this `'one\ntwo` outputs
```
one\ntwo
```

It's really just to help people who are used to using escapes in other languages.

**Comment by fdncred** [comment]
Now that we have a stdlib, we could pretty easily create a `help escapes` command.

**Comment by vedaRadev** [comment]
I'd like to work on this as a first contribution to this project if possible.

Is there a consensus on what a `help escapes` command should do? Maybe just quick reference for what valid escapes are?

Something like this (assuming all of the following are correct):
| sequence | output |
|------------|---------|
| \\" | " |
| \\' | ' |
| \\\\ | \\ |
| \\/ | / |
| \\( | ( |
| \\) | ) |
| \\{ | { |
| \\} | } |
| \\$ | $ |
| \\^ | ^ |
| \\# | # |
| \\\| | \| |
| \\~ | ~ |
| \\a | alert bell |
| \\b | backspace |
| \\e | escape |
| \\f | form feed |
| \\n | newline (line feed) |
| \\r | carriage return |
| \\t | tab |
| \\u{X...} | a single unicode character, where X... is 1-6 digits (0-9, A-F) |

**Comment by amtoine** [comment]
looking at the output of `help operators`, the table you give above sounds pretty good :yum:
