### ISSUE TITLE
Parse Error when command argument contains equal sign

### ISSUE THREAD

**Issue by cdhunt** [nushell/nushell#487]
I'm trying to pass an argument to `terraform` and the argument syntax uses `=` which appears to trip up nu.

```
error: Parse Error                                                                   
- shell:1:23                                                                         
1 | terraform init -backend=false                                                
  |                        ^^^^^^                                                   
 ```

**Comment by jankoprowski** [comment]
Same with `make test TESTS=my_test`

**Comment by jonathandturner** [comment]
Recently @wycats landed some changes to external command support in the parser. It seems this is now fixed.

I'll close the issue, but please re-open if the issue is still happening with the latest code in master.
