### ISSUE TITLE
aliases to defs don't always work

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4872]
### Describe the bug

Yes, the title is clumsy. Let me explain it better here.

Consider the following defs. The point of these defs is to be able to alias ls eventually so that I can have all of my ls calls sorted by type then name insensitively.

```shell
def old-ls [path?] {
  if $path == $nothing {
    ls . | sort-by type name -i
  } else {
    ls $path | sort-by type name -i
  }
}

# ls sort type name -i
def lss [path?] {
  if $path == $nothing {
    old-ls .
  } else {
   old-ls $path
  }
}
```
if I run `lss` it works exactly the way I want it to. if I run `lss /` it work as expected.

now, do `alias ls = lss`. I can still do `ls` and it reports identically to `lss`. however, if I do `ls /`, it lists the items on my root but the results are no longer sorted and I'm not sure why.

Is there a bug in my defs or is this a problem at a lower level in the nushell code?

### How to reproduce

see above

### Expected behavior

return the results sorted

### Configuration

|key|value|
|-|-|
|version|0.59.1|
|branch|main|
|short_commit|762da098|
|commit_hash|762da0989c9502aab7105a21cff192624e8e148f|
|commit_date|2022-03-15 03:50:46 +00:00|
|build_os|macos-aarch64|
|rust_version|rustc 1.59.0 (9d1b2106e 2022-02-23)|
|rust_channel|stable-aarch64-apple-darwin|
|cargo_version|cargo 1.59.0 (49d8809dc 2022-02-10)|
|pkg_version|0.59.1|
|build_time|2022-03-15 06:58:25 -05:00|
|build_rust_channel|debug|
|features|dataframe, default, trash, which, zip|
|installed_plugins|gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml|

**Comment by jntrnr** [comment]
This seems to be fixed in the latest main. Can you confirm that it's fixed for you?

**Comment by fdncred** [comment]
you're right. thank goodness. I thought I was on the latest main but I wasn't.
