### ISSUE TITLE
Incorrect `size` statistics output

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#4883]
### Describe the bug

Incorrect `size` statistics output

### How to reproduce

`"There are seven words in this sentence" | size | select lines` get output `lines   0`
`'大家好' | size | select words` get output `words   1`
`'今天天气真好' | size | select words` get output `words   1`

### Expected behavior

`"There are seven words in this sentence" | size | select lines` should output `lines   1`
`'大家好' | size | select words` should output `words   3`
`'今天天气真好' | size | select words` should output `words   6`

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.59.1                                   |
| branch             | main                                     |
| short_commit       | 01c1e5e8                                 |
| commit_hash        | 01c1e5e8b0e243dbf7dfc4d3673e6f3f629ace30 |
| commit_date        | 2022-03-19 14:52:50 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.59.1                                   |
| build_time         | 2022-03-19 23:04:50 +08:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | gstat                                    |

**Comment by fdncred** [comment]
it counts lines by how many `\n` it sees. in this example there are 0.

**Comment by elferherrera** [comment]
I added a PR to fix the lines. Regarding the words by characters in another language is a bit harder and I don't know how you could do it

**Comment by fdncred** [comment]
I don't see any way to count "word" in unicode. We can do it like it does it now, or count graphemes or count code points but unicode text is tricky. 

we could use fetch to send it to translate.google.com and count all English works - LOL

**Comment by hustcer** [comment]
> I added a PR to fix the lines. Regarding the words by characters in another language is a bit harder and I don't know how you could do it

Never mind, `wc` result is incorrect either for word counting:
```
echo '今天天气真好'|wc
       1       1      19
```

**Comment by hustcer** [comment]
> 
> we could use fetch to send it to translate.google.com and count all English works - LOL

This way is unreliable 😵‍💫

**Comment by fdncred** [comment]
We return the same as `wc` here, before @elferherrera's PR.
```
"There are seven words in this sentence" | wc
      0       7      38
```

**Comment by hustcer** [comment]
> We return the same as `wc` here, before @elferherrera's PR.
> 
> ```
> "There are seven words in this sentence" | wc
>       0       7      38
> ```

 ^echo "There are seven words in this sentence" | wc
       1       7      39

**Comment by fdncred** [comment]
`echo` is adding the `\n`

**Comment by fdncred** [comment]
There is this https://github.com/dead10ck/uwc but it looks pretty old.

**Comment by hustcer** [comment]
I don't think our stats need to be consistent with `wc`, `nushell` is a new shell, it's not `bash` or `sh`, It's `nushell`, and the result should compliance with common sense, Just my personal opinion

**Comment by fdncred** [comment]
maybe we just change the title of that column to `line_endings` and then include the `uwc` code.

**Comment by hustcer** [comment]
In my opinion we should define `size` in our own way and not be influenced by `wc`, `line_endings ` maybe correct but more wordy, forgive me for being so picky 😄 . What to you think? @jntrnr

**Comment by fdncred** [comment]
if you're not counting line endings it's going to be off when you count lines in a file.

```
echo "lines1\nlines2\nlines3" | save test
```

Example1:
```
line 1\n
line 2\n
line 3
```
wc = 2, size = 2

```
echo "lines1\nlines2\nlines3\n" | save test
```
Example2:
```
line 1\n
line 2\n
line 3\n
```
wc = 3, open = 3

**Comment by fdncred** [comment]
I'm good with whatever we decide. I don't really care. I'm just pointing out the pitfalls. For a 1 line example with no line ending, I can understand how it looks weird.

**Comment by hustcer** [comment]
> I'm good with whatever we decide. I don't really care. I'm just pointing out the pitfalls. For a 1 line example with no line ending, I can understand how it looks weird.

I agree with you. I was convinced and both are okay for me, too

**Comment by fdncred** [comment]
@hustcer Check this debug output out. What do you think? Is it right?
```
'大家好' | size 
counts = {
    Lines: 0,
    Words: 3,
    Bytes: 9,
    GraphemeClusters: 3,
    CodePoints: 3,
}
╭───────┬───╮
│ lines │ 0 │
│ words │ 1 │
│ chars │ 3 │
│ bytes │ 9 │
╰───────┴───╯
```
```
> '今天天气真好' | size
counts = {
    Lines: 0,
    Words: 6,
    Bytes: 18,
    GraphemeClusters: 6,
    CodePoints: 6,
}
╭───────┬────╮
│ lines │ 0  │
│ words │ 1  │
│ chars │ 6  │
│ bytes │ 18 │
╰───────┴────╯
```

**Comment by hustcer** [comment]
@fdncred I think it's right

**Comment by hustcer** [comment]
Seems still not right in some case: 
`$'Are you ok? I am fine' | size`  ---> 1 line as expected
`$'Are you ok?(char nl)I am fine' | size`  ---> Output 1 line, expected to be 2

**Comment by fdncred** [comment]
That's because the way you count lines is by counting line endings. I may take a look tomorrow if I have time.
