### ISSUE TITLE
Piping into `lines` freezes up

### ISSUE THREAD

**Issue by YuriGeinishBC** [nushell/nushell#489]
On Windows 10, 1803, 17134.950 and Nu 0.2.0 (`cargo +nightly install nu`):

- `netstat -na` prints the autoview correctly
- `netstat -na | lines` freezes Nu's output until you hit Ctrl+C, which unfreezes Nu and prints the autoview result properly
- `dir | lines` works correctly
- `busybox ls -la / | lines` works correctly
- (cmd.exe) `netstat -na >netstat-output.txt` then (nu) `open netstat-output.txt | lines` works correctly.

It seems there's something weird in interaction between Nu and `netstat` specifically.

**Comment by jonathandturner** [comment]
@YuriGeinishBC - Does this still occur with more recent versions of Nu? I'm not able to repro in Linux.

**Comment by wilem82** [comment]
No freezes on Windows 1909 18363.535.   Nu is 0.8.0.

**Comment by jonathandturner** [comment]
Great, thanks for letting us know.
