### ISSUE TITLE
Change cursor shape based on vi mode?

### ISSUE THREAD

**Issue by jrpat** [nushell/nushell#4895]
### Related problem

In bash and zsh, I can configure the cursor shape to reflect the current vi mode (ie. bar for insert, block for normal). Is there a way to do this with nushell?

### Describe the solution you'd like

I'm new to nushell and not sure what would be idiomatic here.

Perhaps a `PROMPT_CURSOR_VI_INSERT` and `PROMPT_CURSOR_VI_NORMAL`?

### Describe alternatives you've considered

I've tried doing some various things with `(ansi -e ...)` in my `PROMPT_INDICATOR_VI_NORMAL` but no luck so far.

### Additional context and details

nushell is very very cool. Inspiring! Thanks for making it :)

**Comment by jntrnr** [comment]
This should be supported in 0.60. There's a bit if info here: https://www.nushell.sh/book/configuration.html#environment

**Comment by jrpat** [comment]
Thanks! Just got it to work. Should have tinkered a bit more before posting.

```
let-env PROMPT_INDICATOR_VI_INSERT = $": (ansi -e '6 q')"
let-env PROMPT_INDICATOR_VI_NORMAL = $": (ansi -e '2 q')"
```
