### ISSUE TITLE
Launching a file with spaces does not work as expected

### ISSUE THREAD

**Issue by tahir-hassan** [nushell/nushell#4897]
### Describe the bug

If I `cd` to a directory where I store my Markdown notes, and I try to launch VSCode with it as its name:

```
code '.\Notes about alacritty.md'
```

Then VSCode tries to open:

```
C:\Users\MyUsername\MarkdownNotes\'.\Notes about alacritty.md'
```

In other words, it is sending the single quotation marks and the dot backslash to VSCode (or whatever app you are running.

### How to reproduce

1. Create a directory, and a file named `Notes about alacritty.md`.
2. `cd` to this directory
3. run the command `code '.\Notes about alacritty.md'`

### Expected behavior

I expect NuShell to open `Notes about alacritty.md` in VSCode just like PowerShell does, and not send the quotation marks to VSCode, nor the dot backslash.

### Screenshots

![image](https://user-images.githubusercontent.com/12032684/159611188-a13e1c12-cfa0-4d14-bfe5-d8072709aa0d.png)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.0                                   |
| short_commit       | 74af31a4                                 |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315 |
| commit_date        | 2022-03-22 19:07:11 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.60.0                                   |
| build_time         | 2022-03-22 19:26:49 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by hustcer** [comment]
code `.\Notes about alacritty.md` should work since v0.62, I have just tried on my Mac. Please reopen if not
