### ISSUE TITLE
show_hints 

### ISSUE THREAD

**Issue by 89z** [nushell/nushell#4898]
I want to disable hints. I tried editing `config.nu`, but it seems its not currently possible.

**Comment by 89z** [comment]
This seems to do it:

~~~
let $config = {
   color_config: {
      hints: {
         attr: h
      }
   }
}
~~~

Although I think its just hiding them rather than properly disabling them.

<https://github.com/nushell/nushell/blob/a435a9924ce36606acab57c612a9c3ec82c7152e/crates/nu-color-config/src/nu_style.rs#L45-L50>

Also, despite what this says:

<https://github.com/nushell/nushell/blob/a435a9924ce36606acab57c612a9c3ec82c7152e/docs/sample_config/default_config.nu#L130-L135>

Using `hints: { attr: n }` did not get rid of them. Finally, that link is also not valid anymore:

<https://github.com/nushell/nushell/blob/main/docs/How_To_Coloring_and_Theming.md>

**Comment by 89z** [comment]
Looks like that doc was removed here:

https://github.com/nushell/nushell/commit/b714e034aa4a5588de88dbe24420a70a34f34795

**Comment by 89z** [comment]
https://github.com/nushell/nushell/pull/4726

**Comment by fdncred** [comment]
I don't think there's a way to completely disable hints yet. One strategy would be to make it the identical color as your terminal background color.

**Comment by 89z** [comment]
As mentioned in above comment, this seems to work:

~~~
let $config = {
   color_config: {
      hints: { attr: h }
   }
}
~~~

but I think its just hiding them, rather than disabling them

**Comment by fdncred** [comment]
oh, i missed that. thanks.
