### ISSUE TITLE
Nushell 0.6 misparses environment variables

### ISSUE THREAD

**Issue by crides** [nushell/nushell#4899]
### Describe the bug

Nushell doesn't seem to parse environment variables with (single) quotes correctly. On starup `nu` returns errors like:

```
Error:
  × Environment variable was not captured: c''
  help: Got empty value.
```

and `env | where name == TEST` returns:

```
╭───┬──────┬────────┬───────┬───────╮
│ # │ name │  type  │ value │  raw  │
├───┼──────┼────────┼───────┼───────┤
│ 0 │ TEST │ string │ 'a 'b │ 'a 'b │
╰───┴──────┴────────┴───────┴───────╯
```

which is obviously not correct

### How to reproduce

1. (outside nushell) `export TEST="a 'b c'"`
2. Launch nushell `nu`

### Expected behavior

No error occurs, and `env` outputs correctly for the set variable

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.60.0                                    |
| branch             | makepkg                                   |
| short_commit       | 74af31a4                                  |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315  |
| commit_date        | 2022-03-22 19:07:11 +00:00                |
| build_os           | linux-x86_64                              |
| rust_version       | rustc 1.59.0 (Arch Linux rust 1:1.59.0-1) |
| cargo_version      | cargo 1.59.0                              |
| pkg_version        | 0.60.0                                    |
| build_time         | 2022-03-23 00:39:08 +00:00                |
| build_rust_channel | release                                   |
| features           | dataframe, default, trash, which, zip     |
| installed_plugins  |                                           |

**Comment by jfchevrette** [comment]
I'm seeing the same errors and I was able to reproduce by setting the following before starting nushell

`export FOO="bar -c 'baz -xy qux' something"`

no errors if I use double quotes
`export FOO="bar -c \"baz -xy qux\" something"`

Looks like there is a problem with single quotes?

**Comment by ianliu** [comment]
I think I'm having the same bug; I was going to test nushell today, and stumbled with this error:

```
Error: 
  × Environment variable was not captured: Q=_s>
  help: Got empty name.

thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I have the following variable defined in my bash:

```
declare -x PARINT="rTbgqR B=.,?'_A_a_@ Q=_s>|"
```

Why would nushell try to parse this variable at all?
