### ISSUE TITLE
`use` scripts in `config.nu`

### ISSUE THREAD

**Issue by webdesserts** [nushell/nushell#4901]
### Related problem

I'd like to `use` external scripts in my `config.nu` but after playing around with it for a bit, I'm not sure if that's currently possible. There's two reasons I want this:

1. Break up `config.nu` setup 
2. Auto-expose modules from external scripts

### Describe the solution you'd like

In general I would like to do something like this in `config.nu`

```
# Where to look for scripts
let-env NU_LIB_DIRS = [($env.HOME | path join 'scripts')]

# expose small util scripts to the env
use utils.nu *
# configure prompt
use prompt.nu
# define some extern commands and their autocompletions
use externs.nu
# color theme
use themes.nu

$theme = themes solarized dark

let $config = {
  color_config: $theme
}
```

### Describe alternatives you've considered

I've tried to look for a way to auto-execute a script without having to manually `use` them myself and `config.nu` seems to be the only place to do this.

I've also considered splitting up my `utils.nu` module into individual bin files, but this is painful to maintain and wouldn't help with things like `externs.nu` and `themes.nu`

### Additional context and details

Even though I _want_ to do this stuff in `config.nu`, it also seems like a bad place to do all this because it's treated as a "special" environment where the `$env` hasn't been converted from strings yet. I would normally prefer to work in a setup environment that acted as much like the normal shell environment as possible so those scripts were portable between `config.nu` and my actual shell sessions.

**Comment by ehdevries** [comment]
Importing a module from another file in `config.nu` would be great. `source` works in `config.nu`, and that's certainly helpful if you have a script that isn't specifically organized as a module, but `use` would add the flexibility to import just about any external nushell code and use it how you like.

**Comment by Mrfiregem** [comment]
Seems to be related to [this comment](https://github.com/nushell/nushell/issues/3176#issuecomment-1085534982) in #3176.
