### ISSUE TITLE
/ after home path after doing `cd`

### ISSUE THREAD

**Issue by skelly37** [nushell/nushell#4902]
### Describe the bug

Just a minor bug but very annoying. Doing no-argument `cd` to the home location for some reason adds '/' at the end of the prompt. Here's what I see in my terminal:

```
/home/skelly37〉cd                                                              
/home/skelly37/〉 
```

Note that doing `cd` with any argument makes it work correctly (`cd ~/` as well)

### How to reproduce

1. Spawn shell
2. Do `cd`

### Expected behavior

It should look like any other path i.e. /home/skelly37 instead of /home/skelly37/

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.60.0                                    |
| branch             | makepkg                                   |
| short_commit       | 74af31a4                                  |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315  |
| commit_date        | 2022-03-22 19:07:11 +00:00                |
| build_os           | linux-x86_64                              |
| rust_version       | rustc 1.59.0 (Arch Linux rust 1:1.59.0-1) |
| cargo_version      | cargo 1.59.0                              |
| pkg_version        | 0.60.0                                    |
| build_time         | 2022-03-23 00:39:08 +00:00                |
| build_rust_channel | release                                   |
| features           | dataframe, default, trash, which, zip     |
| installed_plugins  |                                           |

**Comment by hustcer** [comment]
I don't have this issue on Mac, not sure whether that’s because I’m using [oh-my-posh](https://ohmyposh.dev/docs/customize) Maybe you can have a try, there is an example here: https://github.com/nushell/nushell/issues/4909#issuecomment-1076406328

**Comment by kubouch** [comment]
I don't have this bug either.

**Comment by Yethal** [comment]
I have this on Linux

**Comment by skelly37** [comment]
Maybe it’s Linux/Unix specific, what about your platforms? @kubouch @hustcer

**Comment by kubouch** [comment]
Actually, yeah, it's present in the default config.
