### ISSUE TITLE
Resize issue in 0.60

### ISSUE THREAD

**Issue by janosimas** [nushell/nushell#4906]
### Describe the bug

When resizing a terminal with `nushell`, it prints many prompts and mess up the terminal.

### How to reproduce

Start nushell in a terminal emulator
Resize the terminal

### Expected behavior

I expect no change when resizing the terminal window

### Screenshots

![image](https://user-images.githubusercontent.com/10848832/159660764-f79ef9b4-90a1-416d-b8bf-559089825cc0.png)

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.60.0                                      |
| build_os           | linux-x86_64                                |
| rust_version       | rustc 1.61.0-nightly (58f11791a 2022-03-17) |
| rust_channel       | nightly-x86_64-unknown-linux-gnu            |
| cargo_version      | cargo 1.61.0-nightly (65c8266 2022-03-09)   |
| pkg_version        | 0.60.0                                      |
| build_time         | 2022-03-23 07:27:09 +01:00                  |
| build_rust_channel | release                                     |
| features           | dataframe, default, trash, which, zip       |
| installed_plugins  |                                             |

**Comment by sholderbach** [comment]
This is a long known issue with reedline (https://github.com/nushell/reedline/issues/42, https://github.com/nushell/reedline/issues/157) We definitely have to do better in this aspect but some of it is probably not perfectly solvable as different terminal emulators might behave differently in different situations (buffer with scrollbar/without, which window handle gets pulled, and the end boss unicode character width)

**Comment by jntrnr** [comment]
Has this improved at all in recent Nushell main? I made some fixes to reedline/nushell so that hopefully it works more closely to other shells.

**Comment by janosimas** [comment]
No, still the same in `0.65.0`

**Comment by fellnerse** [comment]
I have something similar since the beginning I guess, it never bother me before; but yeah it seems like 66 fixed it for me. One thing I noticed is that the option `$config.animate_prompt` is no gone, right? I just removed it form my config

**Comment by hustcer** [comment]
> No, still the same in `0.65.0`

How about v0.66.2?

**Comment by janosimas** [comment]
I just tested with v0.66.3 and seems to be fixed :+1:

**Comment by VarLad** [comment]
@hustcer I still have the resize issue. Now the prompt is not messy, but when the terminal is resized vertically, the prompt jumps a few lines down. This only happens with nushell on all terminals I tried it with. 
Should I make a new issue for it or should we track it in this issue too?

**Comment by hustcer** [comment]
@VarLad You can open a new issue instead, thanks

**Comment by VarLad** [comment]
I think its this issue https://github.com/nushell/nushell/issues/4937 (but on Linux as well)
