### ISSUE TITLE
Error url has misplaced dash

### ISSUE THREAD

**Issue by Toby222** [nushell/nushell#4907]
### Describe the bug

The url that is given when an error occurs wrongly links to a crate with `-` instead of `_`, as should be on [Docs.rs](https://docs.rs/) 
`https://docs.rs/nu-protocol/0.60.0/nu-protocol/` instead of `https://docs.rs/nu-protocol/0.60.0/nu_protocol/`

### How to reproduce

1. Cause any error
2. Observe the difference in url

### Expected behavior

Provide the correct url

### Screenshots

![error url and real url side-by-side](https://user-images.githubusercontent.com/14962962/159664485-b4dab6f5-e653-435d-9ede-27c0f3ea4e38.png)

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.60.0                                    |
| branch             | makepkg                                   |
| short_commit       | 74af31a4                                  |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315  |
| commit_date        | 2022-03-22 19:07:11 +00:00                |
| build_os           | linux-arm                                 |
| rust_version       | rustc 1.59.0 (Arch Linux rust 1:1.59.0-1) |
| cargo_version      | cargo 1.59.0                              |
| pkg_version        | 0.60.0                                    |
| build_time         | 2022-03-23 01:28:49 +00:00                |
| build_rust_channel | release                                   |
| features           | dataframe, default, trash, which, zip     |
| installed_plugins  |                                           |

### Additional context

This seems to be caused by miette ([see this](https://github.com/zkat/miette/blob/2fa5551c81831734fd9a162463a4a939dff9dfba/miette-derive/src/url.rs#L85)), which uses the same name for package and crate, instead of properly escaping the crate.

**Comment by kubouch** [comment]
Yeah, this should be the correct link: https://docs.rs/nu-protocol/0.60.0/nu_protocol/enum.ShellError.html#variant.IncompatiblePathAccess

**Comment by rgwood** [comment]
Looks like this just got fixed in Miette: https://github.com/zkat/miette/issues/147

**Comment by sholderbach** [comment]
Fixed by #5167

**Comment by zkat** [comment]
@hustcer I don't think this made it into 0.61 btw. Sorry for the trouble!
