### ISSUE TITLE
Display `PROMPT_COMMAND_RIGHT` in last instead of first prompt line

### ISSUE THREAD

**Issue by davidkna** [nushell/nushell#4909]
### Related problem

Related: #4374 #4375

`PROMPT_COMMAND_RIGHT` displays in the first prompt line. Whereas in other shells, `RPROMPT` in `zsh` and `fish_righ_prompt` the right prompt is displayed on the input line/last line of the prompt. This also doesn't play well this shells that leave the first prompt line empty by default (for example in starship #4375).

### Describe the solution you'd like

Change `PROMPT_COMMAND_RIGHT` to display in the same line as the input/last prompt line.

### Describe alternatives you've considered

- Add another prompt command for the last prompt line.
- Have prompts implement this by themselves.

**Comment by fdncred** [comment]
I'm not following what you're asking. We have a demo script called oh-my.nu in the nu_scripts/prompts folder where you can see how to use the right prompt and is displayed on the same line as the left prompt.

**Comment by davidkna** [comment]
I can't test oh-my.nu, because it doesn't seem to work with nushell 0.60.
If that prompt is a single-line prompt the right prompt will be displayed in the same line as the input, because first=last line.

But in the case of a multi-line prompt it would be:
```
prompt_line1                   rprompt
prompt_line2> <user input>
```
whereas I would expect it to work like this:
```
prompt_line1
prompt_line2> <user input> rprompt
```

**Comment by hustcer** [comment]
Have you tried oh-my-posh?  https://ohmyposh.dev/docs/customize it works fine for me.
I'm using brew to install oh-my-posh and here is my config snippet:
```shell
let posh-dir = (brew --prefix oh-my-posh | str trim)
let posh-theme = $'($posh-dir)/share/oh-my-posh/themes/'
let-env PROMPT_COMMAND = { oh-my-posh prompt print primary --config $'($posh-theme)/zash.omp.json' }
let-env PROMPT_INDICATOR = $"(ansi y)$> (ansi reset)"
```

**Comment by fdncred** [comment]
> I can't test oh-my.nu, because it doesn't seem to work with nushell 0.60.

it does still work in 0.60. I'm running it now
![image](https://user-images.githubusercontent.com/343840/159716721-2046ccc6-bd59-4d65-9b7d-bbf1d2aa68f6.png)

**Comment by fdncred** [comment]
@hustcer could you put your instructions in the 3rd party prompt section of the book? https://www.nushell.sh/book/3rdpartyprompts.html#nerdfonts

**Comment by hustcer** [comment]
> @hustcer could you put your instructions in the 3rd party prompt section of the book? https://www.nushell.sh/book/3rdpartyprompts.html#nerdfonts

Ok, I will add it later

**Comment by fdncred** [comment]
to my way of thinking, it should act like your middle example. but on the other hand, i'm not sure why you'd use starship to draw the left prompt and something else to draw the right prompt. I thought starship had right prompt support already.

**Comment by davidkna** [comment]
The rprompt in question is just an example. Starship usually handles right-aligned prompt modules with the `$fill` module. But without shell-specific hacks, `PROMPT_COMMAND_RIGHT` doesn't render `starship prompt --right` as expected from other shells.

OhMyPosh seems to be handling the right prompt manually without support from `PROMPT_COMMAND_RIGHT`, which starship does not yet support.

**Comment by JadeYao-z** [comment]
## I am using the starship jetpack theme
## starship left prompt, there are strange characters, causing line breaks

I tried to print, `left` `right` prompts, but found a problem on the left.

Found that nushell text rendering is rendered from `right` and then `left`.
```bash
◎ ls
╭───┬─────────────────┬──────┬────────┬─────────────╮
│ # │      name       │ type │  size  │  modified   │
├───┼─────────────────┼──────┼────────┼─────────────┤
│ 0 │ .gitignore      │ file │    8 B │ 8 hours ago │
│ 1 │ Cargo.lock      │ file │ 6.4 kB │ 8 hours ago │
│ 2 │ Cargo.toml      │ file │  134 B │ 8 hours ago │
│ 3 │ anyhow.txt      │ file │  955 B │ 8 hours ago │
│ 4 │ rust常见依赖.md │ file │  882 B │ 8 hours ago │
│ 5 │ src             │ dir  │    0 B │ 8 hours ago │
│ 6 │ target          │ dir  │    0 B │ 8 hours ago │
│ 7 │ tokio.txt       │ file │ 1.5 kB │ 8 hours ago │
╰───┴─────────────────┴──────┴────────┴─────────────╯

                                         □ demo_r1 △⎪◌◦⎥ pkg ◨ 0.1.0 rs ⊃ 1.87.0 19:41

◎

# becomes
◎ ls
╭───┬─────────────────┬──────┬────────┬─────────────╮
│ # │      name       │ type │  size  │  modified   │
├───┼─────────────────┼──────┼────────┼─────────────┤
│ 0 │ .gitignore      │ file │    8 B │ 8 hours ago │
│ 1 │ Cargo.lock      │ file │ 6.4 kB │ 8 hours ago │
│ 2 │ Cargo.toml      │ file │  134 B │ 8 hours ago │
│ 3 │ anyhow.txt      │ file │  955 B │ 8 hours ago │
│ 4 │ rust常见依赖.md │ file │  882 B │ 8 hours ago │
│ 5 │ src             │ dir  │    0 B │ 8 hours ago │
│ 6 │ target          │ dir  │    0 B │ 8 hours ago │
│ 7 │ tokio.txt       │ file │ 1.5 kB │ 8 hours ago │
╰───┴─────────────────┴──────┴────────┴─────────────╯

◎                                        □ demo_r1 △⎪◌◦⎥ pkg ◨ 0.1.0 rs ⊃ 1.87.0 19:41
```

look this
```nu 
$env.PROMPT_COMMAND = {|| 
    let starship_left = ( 
        ^'C:\Users\jadeyao\scoop\shims\starship.exe' prompt --cmd-duration $env.CMD_DURATION_MS
        $"--status=($env.LAST_EXIT_CODE)"
        --terminal-width (term size).columns
    )
    # Filter and solve the problem. However, I don't know what this strange character is? Space?
    $starship_left | str replace ' ' ''
}
```

## It can be concluded that maybe oh-my-posh also exists, this kind of?

What should you do?

**Comment by JadeYao-z** [comment]
## Conclusion: Mixing `export-env` and `load-env` may cause unpredictable environment variables.

Now it is 2025/05/24

![Image](https://github.com/user-attachments/assets/4d425912-496a-4e74-b5a1-dff13316bcf5)

Environment:

- win10 + nushell
- nixos24 + nushell

In both environments, I directly removed `load-env` and used `$env`. **Result: nushell + starship Jetpack displays normally**

```bash
export-env {
    $env.STARSHIP_SHELL = "nu"
    $env.STARSHIP_SESSION_KEY = (random chars -l 16)
    $env.PROMPT_MULTILINE_INDICATOR = (
        ^'C:\Users\jadeyao\scoop\shims\starship.exe' prompt --continuation
    )

    # Clear the default prompt and use Starship completely
    $env.PROMPT_INDICATOR = ""

    # Left prompt (replace space with -)
    $env.PROMPT_COMMAND = {||
        (
            ^'C:\Users\jadeyao\scoop\shims\starship.exe' prompt
            --cmd-duration $env.CMD_DURATION_MS
            $"--status=($env.LAST_EXIT_CODE)"
            --terminal-width (term size).columns
        )
    }

    # Right prompt (replace space with -)
    $env.PROMPT_COMMAND_RIGHT = {||
        (
            ^'C:\Users\jadeyao\scoop\shims\starship.exe' prompt
            --right
            --cmd-duration $env.CMD_DURATION_MS
            $"--status=($env.LAST_EXIT_CODE)"
            --terminal-width (term size).columns
        )
    }

    # Make sure the right prompt is displayed on the last line
    $env.config = ($env.config? | default {} | merge {
        render_right_prompt_on_last_line: true
    })
}
```

Nushell sometimes has a strict order of evaluating environment variables and closures. Mixing `export-env` and `load-env may` cause unpredictable environment variables.

`load-env` may be designed to load static environment variables and is not suitable for writing dynamic closure commands in it.
