### ISSUE TITLE
Unable to 'cd' in a folder having the '+' character

### ISSUE THREAD

**Issue by teras** [nushell/nushell#491]
I have a folder in my system named "C++" which (obviously) contains my C++ projects.
But with nu I am not able to cd in here.
Is this a feature and how can I overcome it?

**Comment by jonathandturner** [comment]
@teras - this was fixed recently in master and should be available in the next preview release.

Until then you could try putting quotes around the name to see if that works around the issue. 

```
cd "C++"
```

**Comment by teras** [comment]
Indeed this works! thank you
