### ISSUE TITLE
Debian 11 (stable) install via cargo - invalid type for key `profile.profiling.strip`

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [nushell/nushell#4910]
### Describe the bug

While trying to install nu via cargo on Debian 11 (current stable) I got a error message about an _invalid type_ for the key `profile.profiling.strip`. This the full output.

```
cargo install nu
    Updating crates.io index
  Downloaded nu v0.60.0
error: failed to parse manifest at `/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-0.60.0/Cargo.toml`

Caused by:
  invalid type: unit variant, expected string only for key `profile.profiling.strip`
```

### How to reproduce

1. Debian 11 up to date
2. install _cargo_ via `apt install cargo`.
3. install required and optional dependencies (pkg-config libssl-dev libxcb-composite0-dev libx11-dev) as described in README.md
4. install nu via `cargo install nu`

### Expected behavior

Get it installed.

### Configuration

My OS
```
$ uname -a
Linux quark 5.10.0-12-arm64 #1 SMP Debian 5.10.103-1 (2022-03-07) aarch64 GNU/Linux
```

The cargo package
```
$ apt-cache policy cargo
cargo:
  Installiert:           0.47.0-3+b1
  Installationskandidat: 0.47.0-3+b1
  Versionstabelle:
 *** 0.47.0-3+b1 500
        500 http://deb.debian.org/debian bullseye/main arm64 Packages
        100 /var/lib/dpkg/status
```

**Comment by fdncred** [comment]
I believe `strip` was stabilized in rustc version 1.59.0. are you running that version of rust?

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I don't think so because Debian does not offers this in the stable repo.

```
apt-cache policy rustc
rustc:
  Installiert:           1.48.0+dfsg1-2
  Installationskandidat: 1.48.0+dfsg1-2
  Versionstabelle:
 *** 1.48.0+dfsg1-2 500
        500 http://deb.debian.org/debian bullseye/main arm64 Packages
        100 /var/lib/dpkg/status
```

I would recommend to update the `README.md` about that.

**Comment by hustcer** [comment]
The cargo version in `README.md` has been updated, so I will close this issue. Thanks for your remind
