### ISSUE TITLE
Clearing the current prompt with escape

### ISSUE THREAD

**Issue by petrisch** [nushell/nushell#4911]
### Related problem

In bash the escape key clears the current input of the prompt. As far as I can see the escape key is not doing anything at that moment, so maybe this could be a feature.

### Describe the solution you'd like

Use escape for clearing the prompt.

### Describe alternatives you've considered

I can use Ctrl-C for that but this gives another line which wouldn't be necessary.

**Comment by petrisch** [comment]
Hm, so now I entered this in my config:
```
    {
      name: clear_prompt
      modifier: none
      keycode: escape
      mode: emacs # Options: emacs vi_normal vi_insert
      event: {
        until: [
          { edit: Clear }
          { send: Enter }
        ]
      }
    }
```
Which doesn't work for some reason yet to find out. But even if it would I don't think thats what I'm thinking of.
I only want the current prompt to be cleaned, not the entire terminal.
To define it as a keybinding would be fine, but I didn't find a command to do it.
Or am I searching in the wrong place, is this up to the terminal emulater (alacritty on windows in this case?)

**Comment by fdncred** [comment]
what about `edit cutfromstart` as a work-around?
`│ 23 │ emacs     │ CONTROL  │ Char('u') │ Edit([CutFromStart])`

**Comment by fdncred** [comment]
just tried this and it seems to work fine
```
     {
       name: clear
       modifier: none
       keycode: esc
       mode: emacs
       event: { edit: clear }
    }
```

**Comment by petrisch** [comment]
Yap now I can confirme this too. I don't know why it didn't work for me at first, but now it does.
I just think it can be confusing what "clear" here really means.
