### ISSUE TITLE
Add ability to specify Dataframe schema explicitly

### ISSUE THREAD

**Issue by dradtke** [nushell/nushell#4917]
### Related problem

I have a CSV file with a column that contains a number-looking value, but it is technically an identifier, and so would be better classified as a string. However, when I try to open the file, I get this error:

```
/home/admin) let df = open report.csv
Error:
  × Parquet reader error
   ╭─[entry #4:1:1]
 1 │ let df = dfr open report.csv
   ·          ────┬───
   ·              ╰── ComputeError("Could not parse 24492152075717191392128 as dtype Int64 at column 26.\n                                            The total offset in the file is 247 bytes.\n\n                                            Consider running the parser `with_ignore_parser_errors=true`\n                                            or consider adding 24492152075717191392128 to the `null_values` list.")
   ╰────
```

CSV as a format is limited, so Nu tries to infer the schema as an int64 because it contains all numbers, which causes it to fail because as a number, it is too big.

### Describe the solution you'd like

One of either

1. When parsing a number-looking value fails, just treat it as a string instead. This would work for my use-case, but would probably need to be configurable in case it doesn't work for others.
2. Allow the `dfr open` command to somehow allow the user to specify the schema for one or more columns.

As a side note, the error suggests running the parser with `with_ignore_parser_errors=true`, but I am not able to find out how to use that from the documentation.

This looks very similar to https://github.com/nushell/nushell/issues/4083

**Comment by fdncred** [comment]
> Is there any way to tell Nushell to convert a specific column into a string? Something like `into decimal` but for dataframe columns?

i don't see anything when i do `dfr <tab>` or when i do `help -f string | where name =~ dfr`

**Comment by elferherrera** [comment]
I think it could be a good idea to have the ability to specify the schema when opening a file. We could use nu syntax to specify that

**Comment by devurandom** [comment]
`polars into-df` supports a `--schema` argument and gives these examples:
```
  Convert to a dataframe and provide a schema
  > {a: 1, b: {a: [1 2 3]}, c: [a b c]}| polars into-df -s {a: u8, b: {a: list<u64>}, c: list<str>}
  #   a          b                 c
   0   1   {record 1 field}   [list 3 items]

  Convert to a dataframe and provide a schema that adds a new column
  > [[a b]; [1 "foo"] [2 "bar"]] | polars into-df -s {a: u8, b:str, c:i64} | polars fill-null 3
  #   a    b    c
   0   1   foo   3
   1   2   bar   3
```
Does that help?

**Comment by fdncred** [comment]
ya, let's close this now. thanks.
