### ISSUE TITLE
NU-native unix-find command

### ISSUE THREAD

**Issue by fakedrake** [nushell/nushell#4918]
### Related problem

I am trying to run a complicated find command like `find . -type f -name log -exec grep -nH msg \+`  so I need to resort to running `/bin/find` instead.

### Describe the solution you'd like

Ideally I would like a full feature nu-native find utility. I know it's a big undertaking but glory lies ahead. 

EDIT: I just realized that I can't use `-exec` at all as nu complains that `/bin/find: missing argument to `-exec'`

**Comment by kubouch** [comment]
You can use `^` to escape native commands, e.g., `^find`.

**Comment by hustcer** [comment]
I'm using https://github.com/sharkdp/fd instead

**Comment by hustcer** [comment]
Maybe we can "borrow" some from https://github.com/uutils/findutils 😄

**Comment by rgwood** [comment]
Yeah, I think `fd` does a great job of being a modern "find" replacement.

We would consider design proposals for a native Nu version of something similar; feel free to add info to this issue or ping us on Discord.
