### ISSUE TITLE
Source does not accept variables

### ISSUE THREAD

**Issue by Diegovsky** [nushell/nushell#4919]
### Describe the bug

The `source` command does not expand variables and uses it's args verbatim.

### How to reproduce

On nu 0.60, run this:
```nushell
echo $nu.config-path # Outputs your config.nu path
source $nu.config-path # Errors
```

### Expected behavior

I expected `source` to expand variables, like other commands.

### Screenshots

![image](https://user-images.githubusercontent.com/46163903/159753820-263c0c81-b020-489c-b1e3-25bc7b554e9b.png)

### Additional context

Using the default config.

**Comment by fdncred** [comment]
You are correct. It does not support variables. Some of this is covered here https://www.nushell.sh/book/thinking_in_nushell.html#parsing-and-evaluation-are-different-stages

**Comment by Diegovsky** [comment]
Indeed. Is there a way to have muiltiple scripts alongside `config.nu`? I want to organize it better by having separate files and sourcing all of them in the main script.

**Comment by fdncred** [comment]
yes, you either `source` or `use` other scripts depending on whether they are `modules` or not.

**Comment by Diegovsky** [comment]
It does not work if I start `nu` outside the `nushell` folder.

**Comment by fdncred** [comment]
It takes a static path/full path to the script.

**Comment by Diegovsky** [comment]
I see. Thanks :)
