### ISSUE TITLE
How nushell uses tty/pty?

### ISSUE THREAD

**Issue by zhiburt** [nushell/nushell#4922]
Hi there,

It's not a bug I would say it's more of an question.

How `nushell` works with tty?

Trying to run a general `expect` script causes a bit of struggle.

I would expect to get "something" from nushell.
But we get just an endless byte stream.
With the same bytes repeated `\u{1b}[6n`.

```
buffer "\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n\u{1b}[6n"
```

### How to reproduce

You can run either code to verify the issue.

```tcl
package require Expect

spawn nu

exp_send "uname\n"

expect {
    "Linux" { exit }
    timeout {
        failed "finding uname"
    }
}
```

```rust
use std::io::Read;
use expectrl::spawn;

fn main() {
    let mut nu = spawn("nu").unwrap();

    let mut buf = vec![];
    let mut b = [0];
    loop {
        let n = nu.read(&mut b).unwrap();
        if n == 0 {
            break;
        }

        buf.push(b[0]);

        println!("buffer {:?}", String::from_utf8_lossy(&buf));
    }
}
```

### Expected behavior

Get a prompt.

### Configuration

```
/expectrl〉version | transpose key value | to md --pretty
| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.60.0                              |
| build_os           | linux-x86_64                        |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10) |
| pkg_version        | 0.60.0                              |
| build_time         | 2022-03-23 16:09:08 +03:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |
```

**Comment by fdncred** [comment]
this `\u{1b}[6n` looks like an ansi escape sequence. taken from here https://en.wikipedia.org/wiki/ANSI_escape_code#OSC_(Operating_System_Command)_sequences


<html>
<body>


CSI 6n | DSR | Device Status Report | Reports the cursor position (CPR) by transmitting ESC[n;mR, where n is the row and m is the column.)
-- | -- | -- | --



</body>
</html>

i'm not sure why nushell would be returning that though.

**Comment by sholderbach** [comment]
I expect that this is originating from reedline trying to initialize the prompt position, we only support interactive terminal emulators at the moment and don't do "is a tty" checks inside reedline

**Comment by zhiburt** [comment]
@sholderbach so we can close it?

**Comment by sholderbach** [comment]
I would put this on the list of lower priority things to improve. The use case is probably not that common but would be nice for some testing.

**Comment by sholderbach** [comment]
We now do a basic isatty check, but there were some additional [hickups when hooking up nushell to a debugger](https://github.com/nushell/nushell/pull/6584#discussion_r989473676).
We should probably try to polish some of that to also be able to do interactive tests with an expect library if we have a good use case for that.

**Comment by jntrnr** [comment]
@sholderbach - is this still on our list for improvements?

**Comment by sholderbach** [comment]
Let's close this one. I have an issue on the radar around the testability of reedline that hooks into this `isatty` behavior.
