### ISSUE TITLE
&& doesn't work with FiraCode font 

### ISSUE THREAD

**Issue by corbinu** [nushell/nushell#4923]
### Describe the bug

I use FiraCode as my default font in my terminal. I have tried both the main and nerdfonts version. When I use "&&" it is treated not as an operator but as the next input.

### How to reproduce

1. Configure terminal font as FiraCode
2. Run:
```
cat && ls
```

Output is:
```
cat: &&: No such file or directory
cat: ls: No such file or directory
```

### Expected behavior

&& operator should work normally

### Screenshots

![Screen Shot 2022-03-23 at 1 59 05 PM](https://user-images.githubusercontent.com/533625/159794614-86927827-9d2c-463b-a671-6c8853a87788.png)

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.60.0                              |
| build_os           | macos-x86_64                        |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23) |
| rust_channel       | stable-x86_64-apple-darwin          |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10) |
| pkg_version        | 0.60.0                              |
| build_time         | 2022-03-23 12:54:23 -07:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |

**Comment by jntrnr** [comment]
Nushell uses `;` instead of `&&` between two commands

**Comment by kubouch** [comment]
`&&` is a boolean AND operator in Nushell

**Comment by corbinu** [comment]
Sorry! Must have missed that in one of the blog updates. Probably was skimming
