### ISSUE TITLE
0b[...] binary literal support similar to 0x[...] syntax

### ISSUE THREAD

**Issue by jmoore34** [nushell/nushell#4924]
### Describe the solution you'd like

Just as we support `0x[ab cd ef]` syntax, it would be nice to also support the binary equivalent, e.g. `0b[1101 0010]`.

Ideally, an odd number of bits would also be supported, and spaces/commas could ideally go anywhere.

### Describe alternatives you've considered

`"0b1101 0010" | into binary` works currently.

### Additional context and details

For consistency, it might also be nice to have the octal equivalent.

**Comment by jntrnr** [comment]
Love it

**Comment by jntrnr** [comment]
@jmoore34 - can you say more about "Ideally, an odd number of bits would also be supported"?

**Comment by jmoore34** [comment]
@jntrnr I was thinking it would be nice to be able to do e.g. `0b[1 1001]` instead of just `0b[0001 1001]`

**Comment by jntrnr** [comment]
Ahh okay, so it pads left up to a byte boundary. Definitely sounds doable

**Comment by merkrafter** [comment]
Hi, I would like to take this one. Do you have any hints where to start looking for the `0x[..]` implementation?

**Comment by merkrafter** [comment]
Implemented the binary format and left padding; please let me hear your thoughts.
