### ISSUE TITLE
`for` loop is not terminated on Ctrl-C

### ISSUE THREAD

**Issue by burjui** [nushell/nushell#4927]
### Describe the bug

ditto

### How to reproduce

```nu
$ for _ in 0.. { sleep 10sec }
```
Pressing Ctrl-C does nothing. But if you press it during just `sleep 10sec` running on its own, the command terminates. Same goes for any command in the block.

### Expected behavior

Ctrl-C should terminate the loop.

### Configuration

| version            | 0.44.0                                                                                                                                                                  |
| branch             | makepkg                                                                                                                                                                 |
| short_commit       | a660720b                                                                                                                                                                |
| commit_hash        | a660720b6889eab2fa3153854b0a367172c3821d                                                                                                                                |
| commit_date        | 2022-02-08 01:15:46 +00:00                                                                                                                                              |
| build_os           | linux-x86_64                                                                                                                                                            |
| rust_version       | rustc 1.58.1 (Arch Linux rust 1:1.58.1-1)                                                                                                                               |
| cargo_version      | cargo 1.58.0                                                                                                                                                            |
| pkg_version        | 0.44.0                                                                                                                                                                  |
| build_time         | 2022-02-08 01:38:08 +00:00                                                                                                                                              |
| build_rust_channel | release                                                                                                                                                                 |
| features           | ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     |
| installed_plugins  | binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath |

**Comment by hustcer** [comment]
Do you have this issue on the latest version: v0.60.0?

**Comment by shenhunluo** [comment]
I tried "for i in 1..10 { echo $i;sleep 10sec }",the result for Ctrl+c is not reasonable too. sleep is stop,but iter will finish executing without sleep

**Comment by burjui** [comment]
@shenhunluo You're right! Actually, `for`'s behaviour is even more unreasonable than that:

```nu
$ for _ in 1..3 { echo "a"; echo "b"; echo "c" }
a
b
a
b
a
b
╭───┬───╮
│ 0 │ c │
│ 1 │ c │
│ 2 │ c │
╰───┴───╯
```
Err... what? o_O

**Comment by shenhunluo** [comment]
@burjui I think,nushell may have formatted the last one as a table. in 'for _ in 1..3 { echo "a"; echo "b"; echo "c" }' only "c" is a table,and in "for i in 1..10 { echo $i;sleep 10sec }","sleep" may be in table too

**Comment by shenhunluo** [comment]
@burjui  "for i in 1..10 { echo $i;sleep 1sec;echo $i }"
This can stop normally

**Comment by jntrnr** [comment]
It looks like RangeIterator doesn't have ctrl-c yet. Once this is added, the iterator should check each iteration to make sure that it breaks when the ctrl-c is hit.

**Comment by thangchung** [comment]
@jntrnr I have got the same issue that @burjui described above. I run the `nushell` on Windows 11. See the exception below

![image](https://user-images.githubusercontent.com/422341/160326369-110811e1-c194-47b4-9561-db77d6064bc1.png)

And another thing, I think that is related to this issue too, is when I run [`docker-compose`](https://github.com/docker/compose) or [`tye`](https://github.com/dotnet/tye) on the `nushell`, at any time, I press `CTRL + C`, then it throws the same exit code `4294967295`. I tried to run on `Powershell`, and this issue hasn't happened

![image](https://user-images.githubusercontent.com/422341/160326598-da41e778-f2c8-4762-adc2-be346f51a80d.png)

**Comment by jntrnr** [comment]
> @shenhunluo You're right! Actually, `for`'s behaviour is even more unreasonable than that:
> 
> ```nu
> $ for _ in 1..3 { echo "a"; echo "b"; echo "c" }
> a
> b
> a
> b
> a
> b
> ╭───┬───╮
> │ 0 │ c │
> │ 1 │ c │
> │ 2 │ c │
> ╰───┴───╯
> ```
> 
> Err... what? o_O

I've been thinking about this example, and it definitely feels like one where the "output the last thing in the block" way we handle all blocks in Nushell now just feels surprising (in a bad way)

Doing some brainstorming to see what we can do so we can have fewer bad surprises but things generally still work in a predictable way.
