### ISSUE TITLE
Ctrl+V not working on windows 11

### ISSUE THREAD

**Issue by pedoc** [nushell/nushell#4930]
### Describe the bug

Can't paste content via Ctrl+V shortcut,But pasting can be done by clicking the right mouse button.

### How to reproduce

1. cargo install nu --features=extra
2. win+r execute nu
3. copy anything and then switch to nu to paste 

### Expected behavior

ctrl+v it's working

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.60.0                                |path expand | path exists)) {
| build_os           | windows-x86_64                        |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)   |
| rust_channel       | stable-x86_64-pc-windows-msvc         |trim -rc (char newline))'
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)   |
| pkg_version        | 0.60.0                                |
| build_time         | 2022-03-24 17:18:41 +08:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

**Comment by rgwood** [comment]
I'm only able to reproduce this in the old Windows Console Host (and right-click-to-paste seems to work there).

ctrl+v works as expected in Windows Terminal. I've set Windows Terminal to be my default terminal so "win+r execute nu" opens in Windows Terminal.

**Comment by pedoc** [comment]
I also tested in cmder and windows terminal and it does work. It looks like only cmd has this problem. 
I don't know if this is a bug, if not, please close this issue, thanks

**Comment by pedoc** [comment]
On the latest version this problem is gone so close it now.
