### ISSUE TITLE
Environment variable / cli arg for default config

### ISSUE THREAD

**Issue by jeremiahpslewis** [nushell/nushell#4931]
### Related problem

As seen in this PR https://github.com/Homebrew/homebrew-core/pull/97593, because nushell tries to help the user with creating / migrating their nushell config, it is not straightforward to run nushell with the default config. A CLI arg --default-config` would make this easier and cleaner and perhaps be useful for other testing use cases.

### Describe the solution you'd like

A CLI arg --default-config` would make this easier and cleaner and perhaps be useful for other testing use cases.

**Comment by hustcer** [comment]
We have added a default env config file In this PR: https://github.com/nushell/nushell/pull/5099, guess we should add a `--default-env` too, otherwise, we may have similar issue for bumping brew formula here: https://github.com/Homebrew/homebrew-core/pull/97593

**Comment by Caedan** [comment]
Is this ticket free for me to pick up?

**Comment by Caedan** [comment]
> We have added a default env config file In this PR: #5099, guess we should add a `--default-env` too, otherwise, we may have similar issue like [Homebrew/homebrew-core#97593](https://github.com/Homebrew/homebrew-core/pull/97593) while bumping a new brew formula.

So, what's exactly left to do? Adding a an arg `--default-env` and `--default-config` and if these args are used, it should generate:
- https://github.com/nushell/nushell/blob/main/docs/sample_config/default_env.nu
- https://github.com/nushell/nushell/blob/main/docs/sample_config/default_config.nu

**Comment by fdncred** [comment]
> Is this ticket free for me to pick up?

Sorry, I didn't see you asked to work on this. Please feel free to work on a PR for it. Yes, I think that all that's left to do is add `--default-env` and `--default-config`. I was thinking of combining them like `--default-configs` but it's probably better to leave them separate.

I'm not sure if it should create those `default_env.nu` and `default_config.nu` or just apply them somehow.

**Comment by zephaniahong** [comment]
@fdncred  Seeing that it's been awhile, would it be okay if I claimed this ticket instead?

**Comment by fdncred** [comment]
@zephaniahong I'm not even sure it's needed anymore. The reason for this issue was to overcome a Homebrew issue but it seems to be resolved now.

If someone objects to closing this, let me know an we can re-open it.
