### ISSUE TITLE
NuShell is calling cmd.exe on Windows

### ISSUE THREAD

**Issue by 89z** [nushell/nushell#4932]
### Describe the bug

If I run a missing command with NuShell on Windows, I get this:

~~~
D:\piccolo> hello
'hello' is not recognized as an internal or external command,
operable program or batch file.
~~~

I thought I recognized this message, so I opened Command Prompt (`cmd.exe`), and sure enough:

~~~
Microsoft Windows [Version 10.0.18363.1139]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Steven>hello
'hello' is not recognized as an internal or external command,
operable program or batch file.
~~~

So, why is NuShell using another shell for executing commands? Rust proper doesnt do this. If you use a program like this:

~~~rust
use std::{
   io,
   process::Command
};

fn main() -> io::Result<()> {
   Command::new("hello").status()?;
   Ok(())
}
~~~

You get this:

~~~
Error { kind: NotFound, message: "program not found" }
~~~

So Rust is using Windows API or something to launch the program, not any shell. Hence the different message. The whole reason I am using NuShell, is because I am not happy with the existing Windows shells. So I dont want NuShell calling the existing shells.

### How to reproduce

no

### Expected behavior

no

**Comment by hustcer** [comment]
I think that's because nu can't find an internal command named `hello` and will automatically escaped to the external command: https://www.nushell.sh/book/escaping.html

**Comment by 89z** [comment]
@hustcer yeah thats fine, but NuShell doesnt need to call another shell (`cmd.exe`) to execute an external command. It can just execute it directly.

**Comment by 89z** [comment]
Its doing it here:

https://github.com/nushell/nushell/blob/ea7c8c237e1deac53c91f94bb123dbd8120dea7e/crates/nu-command/src/platform/clear.rs#L31-L35

and here:

<https://github.com/nushell/nushell/blob/ea7c8c237e1deac53c91f94bb123dbd8120dea7e/crates/nu-command/src/system/run_external.rs#L469-L471>

`cmd.exe` is not needed on Windows to clear the screen or run an external command. For command, rust can just call the command directly, like this:

~~~rust
let mut process = std::process::Command::new("hello");
~~~

and to clear the screen, Windows APIs are available for that, or Windows Terminal accepts ANSI escape codes, just like Linux terminals.

**Comment by jmoore34** [comment]
I think this change was introduced because before it (in engine-q), nu couldn't run .cmd files in the PATH. (https://github.com/nushell/engine-q/issues/820).

Perhaps a workaround might be to add some special handling for .cmd files on Windows.

**Comment by 89z** [comment]
@jmoore34, a `.cmd` file is a script, similar to a Python script. If you are going to execute a Python script, you do it like this:

~~~
python file.py
~~~

similarly, if you are going to run a `.cmd` file, you do it like this:

~~~
cmd /c file.cmd
~~~

Similar to Rust proper, I don't think that `cmd.exe` should be called for every single executable, just to handle the special case of `.cmd` files. I was quite disappointed by this change, as NuShell to me should be a replacement shell, and calling `cmd.exe` just kills that idea.

**Comment by jntrnr** [comment]
Just to clarify a few things - 

Nushell used to call cmd.exe for *all* executables, and this has been the case for many versions of Nushell. It worked, but as @89z points out, it doesn't feel quite right, as Nushell is meant to be a replacement shell.

With 0.60, we changed this. Now by default Nushell does the handling of running external commands itself on all platforms, with the exception of a few cases:

 - In Linux/macOS, if the file that the user is trying to run ends in .sh, we pass it automatically through bash
 - On Windows, the same happens for ending in .cmd files, we pass through cmd.exe
 - On Windows, we also fall through to cmd.exe if we can't find the executable. This is to help with cases where the user is trying to call something that actually isn't an executable at all, but a kind of Windows pseudo-executable that's only visible via cmd.exe.

If you're running an application and it's found, and it's not a .sh or .cmd, then Nushell is handling invoking it itself. The other cases are when Nushell isn't able to do so.

**Comment by hustcer** [comment]
@jntrnr I think we can add this to the nu book

**Comment by 89z** [comment]
> 
> * On Windows, we also fall through to cmd.exe if we can't find the executable. This is to help with cases where the user is trying to call something that actually isn't an executable at all, but a kind of Windows pseudo-executable that's only visible via cmd.exe.
> 
> If you're running an application and it's found, and it's not a .sh or .cmd, then Nushell is handling invoking it itself. The other cases are when Nushell isn't able to do so.

@jntrnr I have been programming on Windows since about 2005. For many years, I used Command Prompt (`cmd.exe`) as my primary shell. `cmd.exe` is not a good shell. Its an awful shell. It doesn't even have command history. It doesn't have Unicode. It uses weird syntax, like `&` for statement separator. Its quoting rules, if not completely broken, will make you pull your hair out. Compared to something like POSIX sh, writing Batch files feels like walking on glass.

So you can imagine how happy I was, to see shells like PowerShell get better, to the point that they were usable as a daily shell, or now NuShell, which is also very close to that point for me. Hopefully you can understand, how upsetting it could be, that after all these years, I still cant get away from `cmd.exe`. Here I am, happy and using NuShell, but little did I know, that I am one mistyped command away from getting stuck with `cmd.exe` all over again.

So its good to hear that `cmd.exe` is only used in some limited cases, but as long as NuShell is doing this, I cannot use NuShell. I think NuShell is great for many reasons, but this is a deal-breaker. I wish you the best of luck in this project.

**Comment by hustcer** [comment]
Closed by https://github.com/nushell/nushell/pull/6253
