### ISSUE TITLE
Plugin registration failed on Windows 11

### ISSUE THREAD

**Issue by pedoc** [nushell/nushell#4933]
### Describe the bug

The compiled plugin cannot be successfully registered 

### How to reproduce

1. clone and update repo to latest
2. cargo build --release --workspace --features=extra
3. register --encoding=capnp C:\Users\pedoc\.cargo\bin\nu_plugin_gstat.exe
output:
```
Error:
  x Error getting signatures
   ,-[entry #13:1:1]
 1 | register --encoding=capnp C:\Users\pedoc\.cargo\bin\nu_plugin_gstat.exe
   : ^^^^|^^^
   :     `-- Plugin failed to decode: Failed: Too many segments: 1917133436
   `----
```

### Expected behavior

Register the plugin normally

### Screenshots

![image](https://user-images.githubusercontent.com/6604230/159940990-84ba3556-b9b2-497e-a21d-716e4af5c789.png)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.0                                   |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.60.0                                   |
| build_time         | 2022-03-24 22:18:36 +08:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | nu-example-1, nu-example-2, nu-example-3 |

### Additional context

only ```register --encoding=capnp C:\Users\pedoc\.cargo\bin\nu_plugin_example.exe``` it's working,Other plugins will all fail

**Comment by fdncred** [comment]
you need to use `-e json` - we change all the plugins to `json` protocol except `example`.

**Comment by pedoc** [comment]
it's working,thank you very much 

PS:
the [documentation](https://www.nushell.sh/book/plugins.html#adding-a-plugin) may need to be updated accordingly.

**Comment by hustcer** [comment]
> 
> PS: the [documentation](https://www.nushell.sh/book/plugins.html#adding-a-plugin) may need to be updated accordingly.

Thanks. It's already updated, just need a deploy
