### ISSUE TITLE
`flatten` only prints the last field

### ISSUE THREAD

**Issue by phayes** [nushell/nushell#4934]
### Describe the bug

`flatten` only prints the last field when running against the following input:

https://gist.github.com/phayes/d7ce87e5fb095e060b82e6134a83a16b

Adding `transpose key value` to the pipeline seems to result in the correct behavior, but I think flatten should probably do this by default. 

### How to reproduce
```
fetch https://gist.githubusercontent.com/phayes/d7ce87e5fb095e060b82e6134a83a16b/raw/0a7517b56ef1d4ce7feab781521a65c5341e8a28/lang.json | flatten
```

### Expected behavior

Flatten should print all rows, not just the last one.

**Comment by onthebridgetonowhere** [comment]
Might be related to #5443

**Comment by WindSoilder** [comment]
It seems that currently flatten only works well for table, but not record.

flatten `record` it nested record contains all the same key, it will generate wield output, which contains too much columns.

Maybe we can try to make `auto transfer from record to table` if we meet record input?

**Comment by WindSoilder** [comment]
Hmm... After a little more investigation, I think using `transpose` is preferred.

Considered for the following case:
```
{a: [1 2], b: 3, c: {d: 4, e: 5}}
```
The flatten result is:
```
╭───┬───┬───┬───┬───╮
│ # │ a │ b │ d │ e │
├───┼───┼───┼───┼───┤
│ 0 │ 1 │ 3 │ 4 │ 5 │
│ 1 │ 2 │ 3 │ 4 │ 5 │
╰───┴───┴───┴───┴───╯
```

It makes key to be result column, which can be valid and works as desired.

**Comment by jntrnr** [comment]
Agreed. This seems to be working as expected, at least on the current main. You're flattening a record of records into a record, which is getting displayed.

You can use `transpose` to turn this into rows, but flattening into a record is correct.
