### ISSUE TITLE
Add flag to `input` that disables echoing of user keystrokes

### ISSUE THREAD

**Issue by adamkpickering** [nushell/nushell#4943]
### Related problem

I am writing a script that takes a password from the user and stores it in a variable. The `input` command is used for taking input from users in this fashion, but it prints out every keystroke to the terminal - if the terminal is not cleared immediately after, someone could easily read the password. I don't want to pass the password in via CLI flags because it will go into the history. I don't want to do it via environment variables for the same reason.

Bash has the `-s` option on `read`, which allows the user to enter input without writing the user's keystrokes to the terminal. This is also how things like `sudo` work. It would be ideal if nushell had something like this.

### Describe the solution you'd like

I would like a flag on `input` that causes it to not print out my keystrokes. Perhaps `-s` would be a good option since it mimics bash and is somewhat of a mnemonic ("s" is for secret).

### Describe alternatives you've considered

I think one can do it via editing tty settings (on Linux). But that is messy, and not cross-platform either.

**Comment by hustcer** [comment]
Resolved by this PR: https://github.com/nushell/nushell/pull/5017, Thanks
