### ISSUE TITLE
Error: Environment variable was not captured + `panic` + possible "environment variable injection" (if that's a thing)

### ISSUE THREAD

**Issue by x3rAx** [nushell/nushell#4944]
### Describe the bug

# The Original Error

When I start nushell (v0.60) I get the following error message:

```txt
Error:
  × Environment variable was not captured: {}' --bind 'ctrl-u:half-page-up,ctrl-d:half-page-down,ctrl-h:page-up,ctrl-l:page-down,ctrl-f:preview-half-page-down,ctrl-b:preview-half-page-up''
  help: Got empty value.
```

The variable it fails to capture is

```txt
FZF_DEFAULT_OPTS=--preview 'bat {}' --bind 'ctrl-u:half-page-up,ctrl-d:half-page-down,ctrl-h:page-up,ctrl-l:page-down,ctrl-f:preview-half-page-down,ctrl-b:preview-half-page-up'
```

It seems like nushell is confused by the single quotes in combination with a space inside. I can reproduce the error with

```txt
MY_VAR="som 'single quotes' foo" nu

MY_VAR="'single quotes' foo" nu

MY_VAR="'single quotes'" nu
```

but not without the space inside the quotes.

# Causing nushell to Panic

Additionally, I can totally crash nushell when I put an **uneven** number of single quotes in the environment variable

```txt
MY_VAR="crashes ' nushell" nu
```

```txt
Error:
  × Environment variable was not captured: nushell'
  │ 'SHELL'='/run/current-system/sw/bin/bash'
--- CENSORED ---
  │ 'NIX_PROFILES'='/run/current-system/sw
  help: Got empty value.

Error:
  × Environment variable was not captured: /nix/var/nix/profiles/default
  help: Got empty value.

Error:
  × Environment variable was not captured: /etc/profiles/per-user/x3ro
  help: Got empty value.

Error:
  × Environment variable was not captured: /home/x3ro/.nix-profile'
--- CENSORED ---
  │ 'XDG_SESSION_DESKTOP'='none+bspwm'
  │ 'XDG_SESSION_TYPE'='x11'
--- CENSORED ---
  │ 'wg_is_zoomed'='
  help: Got empty value.

thread 'main' panicked at 'internal error: can't find PWD', crates/nu-protocol/src/engine/engine_state.rs:1237:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I have `--- CENSORED ---` some lines that contain personal information.

What you can see from the error output though is, that nushell interprets the un-closed single quote as the end of the current variables value. It then tries to find the next variables name but it seems that it allows for pairs of single quotes, so it never finds a value because all "=" chars are now **inside** single quotes.

# Environment Variable Injection (if that's a thing)

Based on my research I came to the conclusion that it should be possible to "inject" an environment variable from the value of another environment variable.

I don't think that this is a security risk but it hints where the problem lies.

If you run the following from `bash`:

```bash
unset NOT_EXPORTED
export HELLO="world' 'NOT_EXPORTED'='oh hi"
nu -c '$env.NOT_EXPORTED'
```

you get the output `oh hi` even though `NOT_EXPORTED` has been unset before. But `HELLO` "injects" it.

### How to reproduce

From a `bash` shell, run

```bash
export MY_VAR="som 'single quotes' foo"
nu
```

or

```bash
export MY_VAR="crashes ' nushell"
nu
```

or (this one does not error but it should not output anything)

```bash
unset NOT_EXPORTED
export HELLO="world' 'NOT_EXPORTED'='oh hi"
nu -c '$env.NOT_EXPORTED'
```

### Expected behavior

The contents of the environment variables should be the same as they are on the "outside". Single quotes should be ok. Uneven numbers of single quotes in environment variable values should be ok.

### Configuration

〉version | transpose key value | to md --pretty
| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.60.0                                |
| build_os           | linux-x86_64                          |
| rust_version       | rustc 1.59.0                          |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.60.0                                |
| build_time         | 1980-01-01 00:00:00 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

### Additional context

I just built nushell v0.60.0 from source on NixOS (it is not yet available through the package manager). Packaging / building on NixOS is sometimes a bit tricky as it does not strictly obey [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard). However, I can reproduce the same behavior in a Linux Mint VM.

Thanks for nushell, thanks for engine-q, I love it :heart:

**Comment by jntrnr** [comment]
possibly related to https://github.com/nushell/nushell/issues/4899

**Comment by x3rAx** [comment]
Yes this is exactly the same issue. I've looked for similar bugs but I somehow missed that one 😬
