### ISSUE TITLE
`open` command wrapping tabbed source files

### ISSUE THREAD

**Issue by lblackstone** [nushell/nushell#495]
The `open` command seems to be wrapping certain lines incorrectly, with characters from the start of the line wrapping around to the right margin.

I'm using iTerm2 on Mac, if that matters.

Here's the input file:
```
module github.com/pulumi/pulumi-kubernetes

go 1.12

require (
	github.com/Azure/go-autorest/autorest v0.8.0 // indirect
	github.com/Azure/go-autorest/autorest/azure/auth v0.1.0 // indirect
	github.com/Azure/go-autorest/autorest/to v0.2.0 // indirect
	github.com/Azure/go-autorest/autorest/validation v0.1.0 // indirect
	github.com/ahmetb/go-linq v3.0.0+incompatible
	github.com/cbroglie/mustache v1.0.1
	github.com/docker/docker v1.13.1 // indirect
	github.com/evanphx/json-patch v4.1.0+incompatible
	github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
	github.com/golang/protobuf v1.3.1
	github.com/google/gofuzz v1.0.0 // indirect
	github.com/googleapis/gnostic v0.2.0
	github.com/gophercloud/gophercloud v0.0.0-20190418141522-bb98932a7b3a // indirect
	github.com/imdario/mergo v0.3.7 // indirect
	github.com/jinzhu/copier v0.0.0-20180308034124-7e38e58719c3
	github.com/json-iterator/go v1.1.6 // indirect
	github.com/mitchellh/go-wordwrap v1.0.0
	github.com/pkg/errors v0.8.1
	github.com/pulumi/pulumi v1.0.0-beta.4.0.20190826221914-99d70e4610d2
	github.com/stretchr/testify v1.3.0
	google.golang.org/grpc v1.20.1
	gopkg.in/inf.v0 v0.9.1 // indirect
	k8s.io/api v0.0.0-20190620084959-7cf5895f2711
	k8s.io/apimachinery v0.0.0-20190612205821-1799e75a0719
	k8s.io/client-go v0.0.0-20190620085101-78d2af792bab
	k8s.io/kube-openapi v0.0.0-20190418160015-6b3d3b2d5666
	k8s.io/kubernetes v1.14.1
	k8s.io/utils v0.0.0-20190308190857-21c4ce38f2a7 // indirect
)

replace (
	github.com/Azure/azure-sdk-for-go => github.com/Azure/azure-sdk-for-go v31.1.0+incompatible
	github.com/Azure/go-autorest => github.com/Azure/go-autorest v12.4.3+incompatible
	github.com/Nvveen/Gotty => github.com/ijc25/Gotty v0.0.0-20170406111628-a8b993ba6abd
	github.com/census-instrumentation/opencensus-proto => github.com/census-instrumentation/opencensus-proto v0.2.1
	github.com/grpc/grpc-go => google.golang.org/grpc v1.20.1
	github.com/hashicorp/vault => github.com/hashicorp/vault v1.2.0
)
```

Here's what it looks like using the open command:
![Screen Shot 2019-08-27 at 12 20 05 PM](https://user-images.githubusercontent.com/9253463/63797357-28cac280-c8c5-11e9-8696-02e0f041befb.png)

**Comment by jonathandturner** [comment]
What version of iTerm 2 and macOS are you running nu with? It's possible they are returning a width that isn't what Nu expects.

Also, do you get the same behavior with if you make the terminal wider or more narrow?

**Comment by oskarskog** [comment]
I can repro this with MATE Terminal 1.22.1 and alacritty 0.3.3 on Manjaro

![Screenshot at 2019-08-29 14-29-08](https://user-images.githubusercontent.com/19431886/63936651-01acf600-ca69-11e9-9cd8-d479c14b05ee.png)

**Comment by jonathandturner** [comment]
I can reproduce it if I use tabs for indentation in a source file.

```cpp
#include <iostream>

using namespace std;

int main() {
        cout << "Hello world" << endl;
        return 0;
}
```

Will investigate to see if this is on our side or upstream

**Comment by jonathandturner** [comment]
Tried to fix this with https://github.com/nushell/nushell/pull/537.  Let me know if it helps.

**Comment by lblackstone** [comment]
I'm not very familiar with Rust, so it's probably obvious, but how do you build from master? It looks like the README only has info about downloading the release from cargo.

**Comment by lblackstone** [comment]
Figured it out. I confirmed that your fix worked, and the file is displaying properly now. Thanks!

**Comment by oskarskog** [comment]
This is still showing up over here, on both of the terminal emulators, removing the tabs doesn't seem to make a difference either. Also checked that nushell is receiving the proper width and height for the terminal emulator.

![Screenshot at 2019-08-30 20-51-09](https://user-images.githubusercontent.com/19431886/64041195-9269fb80-cb67-11e9-8e48-21e363c23afc.png)
