### ISSUE TITLE
mv, cp and other commandline tools

### ISSUE THREAD

**Issue by charleschege** [nushell/nushell#4952]
Nushell commands like `mv` and `cp` don't provide any feedback on performing an operation. There is no `--verbose` feature like in native unix commands provided by the distribution, like `mv -v foo.txt bar.txt` .

The `rm` command for Nushell is a good example of feedback provided when a file is deleted as seen below:
```
╭───┬─────────────────────────────────────────────────╮
│ 0 │ deleted /home/foo/Downloads/./FooDir │
```

### Describe the solution you'd like

Provide feedback flag like `-v` or like the `rm` command that just does it automatically.

**Comment by EliKor** [comment]
I'd like to try and take this up if that is ok.

**Comment by Zizico2** [comment]
What's the status on this? The Pull Request was merged. Is this issue resolved? From what I understand the `normal` version and the `quiet` version of the commands are operational but we still need a `verbose` version

**Comment by hustcer** [comment]
> What's the status on this? The Pull Request was merged. Is this issue resolved? From what I understand the `normal` version and the `quiet` version of the commands are operational but we still need a `verbose` version

The PR was merged and `mv` command has feedback now, however, `cp` still need to be improved

**Comment by hustcer** [comment]
https://github.com/nushell/nushell/pull/5482

**Comment by hustcer** [comment]
Another related issue: https://github.com/nushell/nushell/issues/3899

**Comment by hustcer** [comment]
All `mv / cp / rm` commands have `--verbose` flag now
