### ISSUE TITLE
duration to string, Please save your work first

### ISSUE THREAD

**Issue by roninee** [nushell/nushell#4953]
### Describe the bug

Actually, I know what's the problem. The reason is that the duration cannot  convert to string; I should use: `$"($duration)"`, but I always forget.
SAVE YOUR WORK FIRST！！！
Start A New Shell, then Run:
`[{d:'2022-01-01'}] | each {|it| ( (date now) - ($it.d | into datetime ))| split row ' ' | get 0 }`

### How to reproduce

CPU : I3 4160
OS: Windows 11

### Expected behavior

.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.0                                   |
| short_commit       | 74af31a4                                 |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315 |
| commit_date        | 2022-03-22 19:07:11 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.60.0                                   |
| build_time         | 2022-03-22 19:26:49 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by hustcer** [comment]
I think this issue should be fixed before v0.61 release.

**Comment by jntrnr** [comment]
Looks like it may not be date-related. You can also see an invalid span on this example:

```
> metadata ({foo: 10} | (20 - $in.foo)) | get span
╭───────┬───────╮
│ start │ 18651 │
│ end   │ 18646 │
╰───────┴───────╯
```

It seems to require a record piped in and then some math on one of its members.

**Comment by roninee** [comment]
Yep, It's Not  date-related. 
The root of the problem is str-type check, It should alert "expected: string" first, but the 'each' command made it delay , then explode.
You can try :
`( (date now) - ( '2022-01-01' | into datetime ))| split row '  '  | get 0  `
![image](https://user-images.githubusercontent.com/44699767/162209676-89c7cc76-ee92-4088-aa7e-1fbc339ac034.png)
