### ISSUE TITLE
can't run executable error with alias, other aliases for same command work

### ISSUE THREAD

**Issue by marianoguerra** [nushell/nushell#4955]
### Describe the bug

if I create an alias like `alias mypush = git push origin` and run it I get the following error:

```
Error: nu::shell::external_command (link)

  × External command
   ╭─[entry #7:1:1]
 1 │ mypush
   · ───┬──
   ·    ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)
```

it works if I do `alias mypush = ^git push origin` instead.

similar aliases for the same command work, like this one: `alias gst = git status`

### How to reproduce

1. Create the following aliases (with git installed)
2. `alias mypush1 = git push origin`
3. `alias mypush2 = ^git push origin`
4. `alias gst = git status`
5. Run the following commands
6. gst
7. mypush1
8. mypush2

### Expected behavior

all should find the git command

instead: mypush1 fails with the error described above

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.60.0                              |
| build_os           | linux-x86_64                        |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10) |
| pkg_version        | 0.60.0                              |
| build_time         | 2022-03-22 22:38:58 +01:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |

### Additional context

ubuntu 21.10

**Comment by ryanpcmcquen** [comment]
Is this because the new default config contains a `export extern "git push" [` entry?

**Comment by herlon214** [comment]
> Is this because the new default config contains a `export extern "git push" [` entry?

I'd say so, changing the alias to `/usr/bin/git push origin` seems to be working fine

**Comment by jntrnr** [comment]
Now that we don't ship with git completions on by default, going ahead and closing this.
