### ISSUE TITLE
`path join` does not work correctly with filtered lists

### ISSUE THREAD

**Issue by panicbit** [nushell/nushell#4958]
### Describe the bug

`path join` works fine with list literals or lists generated by other commands, however, filtered lists (using `drop`, `first`, `last`, `where` etc) are passed through 1:1 by `path join`.

### How to reproduce

Input:
```
[a, b, c] | drop 1 | path join
```

Observe unexpected output:
```
╭───┬───╮
│ 0 │ a │
│ 1 │ b │
╰───┴───╯
```

### Expected behavior

Output:
```
a/b
```

### Screenshots

![image](https://user-images.githubusercontent.com/628445/160174961-709d4b0a-6490-4270-86df-e65db5909abe.png)

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.60.0                                |
| build_os           | linux-x86_64                          |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)   |
| rust_channel       | stable-x86_64-unknown-linux-gnu       |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)   |
| pkg_version        | 0.60.0                                |
| build_time         | 2022-03-23 14:52:22 +01:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

**Comment by fdncred** [comment]
that's weird. thanks.

**Comment by filaretov** [comment]
In case it helps with debugging, it works correctly when running with `--log-level trace` (it seems).

**Comment by fdncred** [comment]
this seems to be fixed. please reopen if you disagree.
