### ISSUE TITLE
How are aliases set in the config for 0.60?

### ISSUE THREAD

**Issue by ryanpcmcquen** [nushell/nushell#4962]
### Describe the bug

In 0.44, I would set aliases like so:

```
startup = [
    "alias foo = let-env FOO = /Users/foo/.bar/baz"
]
```

I've tried this syntax in 0.60:
```
alias foo = let-env FOO = /Users/foo/.bar/baz
```

But when running the alias, I receive an error:
```
λ foo
Error: nu::shell::external_command (link)

  × External command
   ╭─[entry #1:1:1]
 1 │ foo
   · ─┬─
   ·  ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)
```

### How to reproduce

1. Set an alias in the config.
2. Run that alias in a new shell.

### Expected behavior

Execute the alias.

### Screenshots

<img width="385" alt="Screen Shot 2022-03-25 at 11 45 24 AM" src="https://user-images.githubusercontent.com/772937/160182713-cf158955-73a7-4ad8-bbdc-913d119deea9.png">

### Configuration

λ version | transpose key value | to md --pretty
| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.60.0                                |
| build_os           | macos-x86_64                          |
| rust_version       | rustc 1.59.0                          |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.60.0                                |
| build_time         | 2022-03-22 19:07:11 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

**Comment by jntrnr** [comment]
You'll need quotes around your path. Since `let-env` can be any value now, the right hand side is treated as a full expression rather than a string

**Comment by ryanpcmcquen** [comment]
@jntrnr thanks for the fast reply. Just to make sure, it should be this?
```
alias foo = let-env FOO = "/Users/foo/.bar/baz"
```
I still get an error with that syntax:
```
λ foo
Error: nu::shell::external_command (link)

  × External command
   ╭─[entry #1:1:1]
 1 │ foo
   · ─┬─
   ·  ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)
```

**Comment by kubouch** [comment]
`alias foo = let-env FOO = "/Users/foo/.bar/baz"` works for me.

The error span should put at the path instead of foo, though. This way, it's not really clear what's happening.

**Comment by ryanpcmcquen** [comment]
> `alias foo = let-env FOO = "/Users/foo/.bar/baz"` works for me.

Does it work inside of `config.nu` or just if ran inside of a prompt?

**Comment by jntrnr** [comment]
```
> nu
/Users/jt/Source/nushell〉foo
/Users/jt/Source/nushell〉$env.FOO
/Users/foo/.bar/baz
```

config works fine for me

**Comment by ryanpcmcquen** [comment]
Never mind, I was editing the wrong file, it all works!
![giphy](https://user-images.githubusercontent.com/772937/160187289-9e08170b-a348-4a69-a998-571fea293685.gif)
