### ISSUE TITLE
Multi-command alias only executes last command output

### ISSUE THREAD

**Issue by nyurik** [nushell/nushell#4969]
### Describe the bug

If an alias contains multiple commands, only the last one is executed.

### How to reproduce

```
alias st = (echo 'a'; echo 'b')
st
```

### Expected behavior

should run all commands, printing all of their output.  Instead, I only see `b` printed.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.60.0                              |
| build_os           | linux-x86_64                        |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10) |
| pkg_version        | 0.60.0                              |
| build_time         | 2022-03-25 09:40:45 -04:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |

**Comment by hustcer** [comment]
You can try `alias st = (print 'a'; print 'b')` for more detail:
https://www.nushell.sh/book/types_of_data.html#groups

**Comment by nyurik** [comment]
@hustcer thanks, the `print` does work - but this is really confusing -- why does `echo` behaves differently?  From [docs](https://www.nushell.sh/book/command_reference.html):

> print - Prints the values given
> echo - Echo the arguments back to the user

Note that surprisingly running both commands without an alias work as expected -- both of these print identical correct result:
```
> echo 'a'; echo 'b'
> print 'a'; print 'b'
```

**Comment by jntrnr** [comment]
This is more because of the subexpressions, which favour resolving to a single value. `(echo a; echo b)` only outputs b for example.

**Comment by nyurik** [comment]
Thx. This was just one of those WTF review moments 😀. I think this could use some rethinking as it is clearly goes against the PLS - Principle of least surprise, but I am just starting with nushell, so don't know the reasons behind this specific implementation

**Comment by jntrnr** [comment]
Closing as I think this is working correctly, there was just some confusion about `echo` vs `print`?
