### ISSUE TITLE
Auto-suggestion panics when meeting "、" and "txt", "mp4".

### ISSUE THREAD

**Issue by BobH-Official** [nushell/nushell#4971]
### Describe the bug

Sorry, the bug is a little bit complex that I cannot give it a simple name for the title.(NEED HELP)
Auto-suggestion panics on a very specific situation.
The folder should have at least two files, whose name should meets these requirements.
1. all the file name should be same, excpet for the extension
2. at least two files, one of them should be ".txt", one should be ".mp4" or ".m4a"
3. should contain "、" in the middle
4. should start with non-English letter, (I tried "紧急", "あ", "新", "啊")

Some notes:
1. for 1&2, if there is only one file with the name, no panic.
2. for 2, ".txt"&".tvt" no panic.
3. for 3, a single "、"(like "、.txt") no panic. "、啊" no panic. "啊、" no panic.
4. for 4, "a、b" no panic, "a、啊" no panic.

### How to reproduce

1. create more than one file, with the requirements listed:
   * all the file name should be same, excpet for the extension
   * at least two files, one of them should be ".txt", one should be "mp4" or "m4a"(note I tried "txt"&"tvt", didn't panic)
   * should contain "、" in the middle
   * should start with non-English letter, (I tried "紧急", "あ", "新", "啊")
   * examples(which I tried): "新、b" "新增、一二三四" "啊、b" "あ、b" "紧急删除、神秘病毒，生化实验…美国在乌克兰究竟做了什么？"
3. enter a command, I first met this bug doing "ffmpeg -i", later I tried "open", both panics.
4. enter the beginning of a file
7. enter "TAB" for suggestions
8. PANIC!

### Expected behavior

No panic and pretty suggestions should appear.

### Screenshots

This is the error message.("open .\紧急"is what I typed in, the rest is the panic message.)
```
open .\紧急thread 'main' panicked at 'byte index 31 is not a char boundary; it is inside '，' (bytes 29..32) of `.\紧急删除、神秘病毒，生化实验…美国在乌克兰究竟做了什么？.m4a`', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\reedline-0.3.0\src\menu\completion_menu.rs:371:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Configuration

version		Windows 11 Pro
version		21H2
installed at	‎2021/‎12/‎19
OS componet	22000.556
experience	Windows 功能體驗套件 1000.22000.556.0

——————————————————————————————————————————————————————

processor	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
RAM		16.0 GB (15.8 GB 可用)
OS type		64 bit OS，x64 processor

——————————————————————————————————————————————————————

〉nu --version
0.60.0

### Additional context

* The shortest file name should be:
1. "啊、啊.txt"&"啊、啊.mp4"
2. "啊、啊.txt"&"啊、啊.m4a"

* The content in the file does not influence the bug.

**Comment by rgwood** [comment]
Thank you for the detailed bug report! I was able to reproduce this with `RUST_BACKTRACE` enabled:

```
thread 'main' panicked at 'byte index 4 is not a char boundary; it is inside '新' (bytes 2..5) of `.\新、.mp4`', C:\Users\reill\.cargo\registry\src\github.com-1ecc6299db9ec823\reedline-0.3.0\src\menu\completion_menu.rs:371:29
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\panicking.rs:116
   2: core::fmt::Arguments::new_v1
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\fmt\mod.rs:365
   3: core::str::slice_error_fail
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\str\mod.rs:114
   4: core::str::traits::impl$7::index
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\core\src\str\traits.rs:214
   5: core::str::traits::impl$4::index<core::ops::range::Range<usize> >
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\core\src\str\traits.rs:64
   6: alloc::string::impl$25::index
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\alloc\src\string.rs:2224
   7: reedline::menu::completion_menu::impl$3::can_partially_complete
             at C:\Users\reill\.cargo\registry\src\github.com-1ecc6299db9ec823\reedline-0.3.0\src\menu\completion_menu.rs:371
   8: reedline::engine::Reedline::handle_editor_event
             at C:\Users\reill\.cargo\registry\src\github.com-1ecc6299db9ec823\reedline-0.3.0\src\engine.rs:589
   9: reedline::engine::Reedline::handle_editor_event
             at C:\Users\reill\.cargo\registry\src\github.com-1ecc6299db9ec823\reedline-0.3.0\src\engine.rs:847
  10: reedline::engine::Reedline::handle_event
             at C:\Users\reill\.cargo\registry\src\github.com-1ecc6299db9ec823\reedline-0.3.0\src\engine.rs:468
  11: reedline::engine::Reedline::read_line_helper
             at C:\Users\reill\.cargo\registry\src\github.com-1ecc6299db9ec823\reedline-0.3.0\src\engine.rs:445
  12: reedline::engine::Reedline::read_line
             at C:\Users\reill\.cargo\registry\src\github.com-1ecc6299db9ec823\reedline-0.3.0\src\engine.rs:347
  13: nu_cli::repl::evaluate_repl
             at C:\Users\reill\github\nushell\crates\nu-cli\src\repl.rs:251
  14: nu::main
             at C:\Users\reill\github\nushell\src\main.rs:246
  15: core::ops::function::FnOnce::call_once<enum$<core::result::Result<tuple$<>,miette::eyreish::Report>, 1, 18446744073709551615, Err> (*)(),tuple$<> >
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.0                                   |
| branch             | main                                     |
| short_commit       | a435a992                                 |
| commit_hash        | a435a9924ce36606acab57c612a9c3ec82c7152e |
| commit_date        | 2022-03-23 02:09:58 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.60.0                                   |
| build_time         | 2022-03-22 21:56:16 -07:00               |
| build_rust_channel | debug                                    |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | nu-python                                |

**Comment by jntrnr** [comment]
@sholderbach / @elferherrera - looking at the backtrace, this *may* be a reedline issue. We might want to do some join investigation.

**Comment by elferherrera** [comment]
we were having a similar issue with non ansi characters with the function can partially complete. I'll look into it

**Comment by uasi** [comment]
`啊、.txt` and `啊、.mp4` are okay while `啊啊啊.txt` and `啊啊啊.mp4` lead to a panic. I believe the culprit is the length of the filename being longer than a few bytes, not `、`.

**Comment by uasi** [comment]
I think I figured it out. The cause is that `reedline::menu::find_common_string` incorrectly returns character counts instead of byte counts under certain conditions. Possible fix is as follows.

```diff
diff --git a/src/menu/mod.rs b/src/menu/mod.rs
index b89d854..2bee2a5 100644
--- a/src/menu/mod.rs
+++ b/src/menu/mod.rs

@@ -225,15 +225,15 @@ fn find_common_string(values: &[(Span, String)]) -> (Option<&(Span, String)>, Op
                 Some(first_string.len())
             } else {
                 first_string
-                    .chars()
-                    .zip(value.chars())
-                    .position(|(mut lhs, mut rhs)| {
+                    .char_indices()
+                    .zip(value.char_indices())
+                    .find(|((_, mut lhs), (_, mut rhs))| {
                         lhs.make_ascii_lowercase();
                         rhs.make_ascii_lowercase();
 
                         lhs != rhs
                     })
-                    .map(|new_index| match index {
+                    .map(|((new_index, _), _)| match index {
                         Some(index) => {
                             if index <= new_index {
                                 index
```

**Comment by elferherrera** [comment]
looks like it may work. Do you mind creating a PR with these changes?. Also, do you mind adding tests for the issues you are correcting?

**Comment by uasi** [comment]
@elferherrera Sure, created https://github.com/nushell/reedline/pull/363
