### ISSUE TITLE
Support ansi "default" code

### ISSUE THREAD

**Issue by webdesserts** [nushell/nushell#4973]
### Related problem

I would like to build `color_config` themes that work with a variety of different preset terminal colors, but am finding it difficult with the current available ansi colors. In particular, there's not too many good options for building themes that support both light and dark backgrounds. For example, even the default nushell theme looks like this on light backgrounds:

![Screen Shot 2022-03-26 at 1 42 09 AM](https://user-images.githubusercontent.com/916253/160228180-1c3e2f77-a7f0-40e9-9ca0-99dcdf24a631.png)

### Describe the solution you'd like

If possible, I would like nushell to support the "default" ansi code `39m`. This uses the default foreground color that a terminal user might have selected. This color is unique and can be selected separately from the main 16 ansi colors. For example, in iTerm, you can configure it here:

![Screen Shot 2022-03-26 at 1 29 00 AM](https://user-images.githubusercontent.com/916253/160227745-f14c2ee2-89cf-4a1b-b8a2-080809db0fca.png)

The main benefit of using this code over codes like `white` and `black` are that you can be confident that the color will be readable on the terminal's main background. For example, here is an example demonstrating how using the default ansi color enables a theme to easily adapt to both light and dark themes:

**Light Theme:**
*(top: nushell, bottom: custom theme w/ default)*

![Screen Shot 2022-03-26 at 1 24 27 AM](https://user-images.githubusercontent.com/916253/160228291-624bd1b3-30ce-462d-b2d7-bbfa4dfd90ca.png)

**Dark Theme:**
*(top: nushell, bottom: custom theme w/ default)*

![Screen Shot 2022-03-26 at 1 24 44 AM](https://user-images.githubusercontent.com/916253/160228297-a824fff0-8558-4004-9da3-4aa6269266d6.png)

To take advantage of this color, I would like the following ansi codes to be introduced for both the `ansi` command and the `color_config` record:

| name | code |
| ---     | ---     |
| default | `39m` |
| default_bold | `1;39m` |
| default_dimmed | `2;39m` |
| default_italic | `3;39m` |
| default_underline | `4;39m` |
| default_reverse | `7;39m` |

### Describe alternatives you've considered

The current workarounds I've been using are:

1. Explicitly passing the code into the ansi command when manually coloring strings: `ansi -e "2;39m"`
2. Using `reset` records in `color_config` themes:
   ```
   color_config: {
     headers: { fg: reset, attr: db }
     # note: the following does not work
     # string: reset
   }
   ```

Both of these are cumbersome and the reset variation doesn't have the ease of use of something like `default_dimmed`

### Additional context and details

I understand that `default` is probably an overloaded term and would be happy with an alternatively named keyword that still uses the same ansi code under the hood.

**Comment by fdncred** [comment]
This seems reasonable but I'm thinking this should be change in `nu-ansi-term` first. Then it can be enabled in nushell.

**Comment by fdncred** [comment]
This is actually going to take 3 PRs I think.

- [x] nu-ansi-term https://github.com/nushell/nu-ansi-term/pull/4
- [ ] reedline
- [ ] nushell

**Comment by webdesserts** [comment]
> sidenote - I like your gradient prompt - looks cool

Thanks! While digging into this I discovered the `ansi gradient` command and had fun playing around with it. So thanks to whoever built that out and for making it easy to work with.

> This is actually going to take 3 PRs I think.

If you think any of those are approachable for new contributors I would be happy giving one a shot.

**Comment by fdncred** [comment]
I implemented gradient. Thanks. :)

I have the other two PRs finished already but since reedline depends on it and nushell depends on it, it'll have to be published to crates.io first.

**Comment by webdesserts** [comment]
@fdncred Thanks for implementing this so quick! Looking forward to trying it out in the next release 😊

**Comment by fdncred** [comment]
@webdesserts looking forward to seeing your themes. :)
