### ISSUE TITLE
Failing to expand tilde because of permissions needs better error

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#4977]
### Describe the bug

I just tried to do `ls ~/Downloads` and it returns nothing when there are clearly files in my Downloads folder. I also tried `ls ~/Do<tab>` to complete it with the same result.

### How to reproduce

see above

### Expected behavior

list downloads

### Configuration

|key|value|
|-|-|
|version|0.60.0|
|branch|main|
|short_commit|80769b71|
|commit_hash|80769b7197ad94b8679cf3cc36efbd20a1b892c1|
|commit_date|2022-03-24 19:08:34 +00:00|
|build_os|macos-aarch64|
|rust_version|rustc 1.59.0 (9d1b2106e 2022-02-23)|
|rust_channel|stable-aarch64-apple-darwin|
|cargo_version|cargo 1.59.0 (49d8809dc 2022-02-10)|
|pkg_version|0.60.0|
|build_time|2022-03-24 18:03:54 -05:00|
|build_rust_channel|debug|
|features|dataframe, default, trash, which, zip|
|installed_plugins|gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml|

**Comment by fdncred** [comment]
Ugh - it's a permissions issue. Fish shell returns this `ls: cannot open directory '/Users/fdncred/Downloads/': Operation not permitted`. Would be nice to know that from nushell.

**Comment by fdncred** [comment]
Note to self, next time do `stat /path/to/folder` to see things in more detail. Also, used this link to fix the permissions https://www.switchingtomac.com/macos/how-to-fix-or-repair-disk-permissions-in-macos/

Still it would've been nice if nushell would've reported the error with `ls ~/Downloads`.  At least I got this when I tried not letting nushell expand the tilde but it should've been displayed both ways.

```
ls /Users/fdncred/Downloads/ 
Error:
  × Permission denied
   ╭─[entry #34:1:1]
 1 │ ls /Users/fdncred/Downloads/
   ·    ────────────┬────────────
   ·                ╰── The permissions of 700 do not allow access for this user
   ╰────
```

**Comment by jntrnr** [comment]
This appears to work on the latest main

```
~/Disks> ls ~/Disks/root
Error:   × Permission denied
   ╭─[entry #267:1:1]
 1 │ ls ~/Disks/root
   ·    ──────┬─────
   ·          ╰── The permissions of 700 do not allow access for this user
   ╰────
```
