### ISSUE TITLE
`lines` behaviour for mixed line ending styles

### ISSUE THREAD

**Issue by panicbit** [nushell/nushell#4989]
### Describe the bug

Currently the `lines` command can split strings just fine if the string only contains `\n` or only contains `\r\n`.
However, if a string contains both `\n` and `\r\n` line endings, then `\n` endings are ignored.

### How to reproduce

```nu
"foo\nbar\r\nquux" | lines
```
Currently results in:
```nu
╭───┬──────╮
│ 0 │ foo  │
│   │ bar  │
│ 1 │ quux │
╰───┴──────╯
```

### Expected behavior

`lines` should split on `\n` or `\r\n` regardless of the presence of one or the other.
As an example for how I expect this to behave see [std::str::lines](https://doc.rust-lang.org/std/primitive.str.html#method.lines).
The expected output for the repro command above is:
```
╭───┬──────╮
│ 0 │ foo  │
│ 1 │ bar  │
│ 2 │ quux │
╰───┴──────╯
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.0                                   |
| branch             | main                                     |
| short_commit       | 8a9cc33a                                 |
| commit_hash        | 8a9cc33aacf978d95617f79252025a7204d0109d |
| commit_date        | 2022-03-25 22:56:40 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.60.0                                   |
| build_time         | 2022-03-26 00:07:31 +01:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
This is tangentially related to https://github.com/nushell/nushell/pull/4887. I mention that `lines` and `size` aren't doing the same thing. Maybe some code could be borrowed to enhance `lines`?
