### ISSUE TITLE
Environment variable was not captured

### ISSUE THREAD

**Issue by tddschn** [nushell/nushell#4990]
### Describe the bug

Some environment variable was not captured.

With `MANPAGER` set to `sh -c 'col -bx | bat -l man -p'`,
I got this output on `zsh` initialization:
```
Error: 
  × Environment variable was not captured: -bx
  help: Got empty value.

Error: 
  × Environment variable was not captured: bat
  help: Got empty value.

Error: 
  × Environment variable was not captured: -l
  help: Got empty value.

Error: 
  × Environment variable was not captured: man
  help: Got empty value.

Error: 
  × Environment variable was not captured: -p''
  help: Got empty value.
```

I have nushell installed but I don't use it, and I couldn't find any nushell init command in my `.zshrc`.
I don't know why nushell does anything when I initialize zsh by running `zsh`.

### How to reproduce

```zsh
command cat <<'EOF' > ~/.zshrc
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
EOF

exec zsh
```

### Expected behavior

Nushell doesn't do anything on zsh initialization.
If it needs to capture env vars, it should be able to handle edge cases like the `MANPAGER` described above.

### Screenshots

<img width="389" alt="CleanShot-2022-03-27T13-22-54@2x" src="https://user-images.githubusercontent.com/45612704/160267970-227d1b49-0553-476a-a42e-fc5a89abe42a.png">

**Comment by jntrnr** [comment]
@tddschn - I think this is fixed by #4960 - are you running 0.60 or are you building from main?

**Comment by tddschn** [comment]
@jntrnr I'm running 0.60 on macOS, installed from Homebrew.

**Comment by jntrnr** [comment]
@tddschn it should be, with luck

**Comment by tddschn** [comment]
@jntrnr That'd be great! One thing that I don't understand is that why does Nushell do this on zsh initialization?

**Comment by appomsk** [comment]
@tddschn previous shell exports some environment variables with single quotes in them. 0.60 does not like it. In my case these were some FZF variables. I believe it's not only zsh issue.
