### ISSUE TITLE
book info on configuring use of Starship needs update

### ISSUE THREAD

**Issue by mvolkmann** [nushell/nushell#4993]
### Describe the bug

There are two pages in the "book" that describe configuring the use of Starship.
The instructions here work for me: https://www.nushell.sh/book/configuration.html#prompt-configuration
But the instructions here do not: https://www.nushell.sh/book/3rdpartyprompts.html

I think the later page needs to be updated to match the former.

### How to reproduce

Try to follow the recommended steps on both pages.

### Expected behavior

I expected the documentation on both pages to match.

**Comment by fdncred** [comment]
I just tried both and they work on my Mac. However, we shouldn't have 2 section that say the same thing.

## Option A worked:

let-env STARSHIP_SHELL = "nu"

def create_left_prompt [] {
  starship prompt --cmd-duration $env.CMD_DURATION_MS $'--status=($env.LAST_EXIT_CODE)'
}

let-env PROMPT_COMMAND = { create_left_prompt }
let-env PROMPT_COMMAND_RIGHT = ""

let-env PROMPT_INDICATOR = ""
let-env PROMPT_INDICATOR_VI_INSERT = ": "
let-env PROMPT_INDICATOR_VI_NORMAL = "〉"
let-env PROMPT_MULTILINE_INDICATOR = "::: "

## Option B worked:

let-env STARSHIP_SHELL = "nu"
let-env STARSHIP_SESSION_KEY = (random chars -l 16)
hide PROMPT_COMMAND_RIGHT
let-env PROMPT_INDICATOR = " "
let-env PROMPT_COMMAND = { starship prompt --cmd-duration $env.CMD_DURATION_MS $'--status=($env.LAST_EXIT_CODE)' | str trim }


I'm wondering if it has something to do with starting with a prompt that already has starship enabled and starting another shell that has a starship prompt too. We've seen odd things like that in the past.

**Comment by jntrnr** [comment]
Book updated with https://github.com/nushell/nushell.github.io/pull/353
