### ISSUE TITLE
Tables are cut off when using multiline prompt

### ISSUE THREAD

**Issue by valeth** [nushell/nushell#4994]
### Describe the bug

When using a prompt that spans across multiple lines, the last row in the table are cut off.
I'm using starship for my prompt, set up following their instructions in the readme, and the following config:

```toml
add_newline = true

format = """
$username$hostname\
$directory\
$git_branch$git_commit$git_state$git_status\
$line_break\
$cmd_duration$status$character\
"""
```

If I remove the `$line_break` and set `add_newline` to false it does no longer cut of table rows.

Not sure if this is a bug in starship or nushell.

### How to reproduce

1. Configure starship prompt format to include a line break
2. Experience cut-off table rows

### Expected behavior

Tables should be rendered completely.

### Screenshots

This is the output I'm getting (left is with the `$line_break`, right is without).
![Screenshot_20220327_151709](https://user-images.githubusercontent.com/3198362/160283438-9722e02b-fa68-4c19-ab99-e4fbd96882aa.png)

Note that this only happens if there isn't enough space in the current terminal view.
![Screenshot_20220327_152207](https://user-images.githubusercontent.com/3198362/160283567-bd36c546-b419-4fd6-8e6f-5ba631224b76.png)

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.60.0                                    |
| branch             | makepkg                                   |
| short_commit       | 74af31a4                                  |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315  |
| commit_date        | 2022-03-22 19:07:11 +00:00                |
| build_os           | linux-x86_64                              |
| rust_version       | rustc 1.59.0 (Arch Linux rust 1:1.59.0-1) |
| cargo_version      | cargo 1.59.0                              |
| pkg_version        | 0.60.0                                    |
| build_time         | 2022-03-23 00:39:08 +00:00                |
| build_rust_channel | release                                   |
| features           | dataframe, default, trash, which, zip     |
| installed_plugins  |                                           |

**Comment by elferherrera** [comment]
I think this is reedline issue. Does it happen outside zellij as well?

**Comment by valeth** [comment]
Seems to be fine outside of zellij.
So it's an issue with the way zellij renders its panes then.

**Comment by valeth** [comment]
Might also be worth noting that I'm running zellij directly from allacritty, without executing it from a shell.
Because that gave me problems with duplicate `PATH` entries.

**Comment by sholderbach** [comment]
As a zellij maintainer mentioned in https://github.com/nushell/reedline/issues/359#issuecomment-1079714809 there is a problem with ANSI scrolling commands. Those are used by reedline after finalizing a line input and if the content exceeds the height of the screen (This should apply to what you are describing). This should be fixed soon on the zellij side

**Comment by sholderbach** [comment]
Will close for now. Feel free to reopen if it persists after their fix.
