### ISSUE TITLE
PWD contains double backslashes on Windows

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#5000]
### Describe the bug

`$env.PWD` is now putting 2 backslashes between each directory on Windows. For example, `C:\\Users\\reilly` instead of `C:\Users\reilly`. This is noticeable in the default prompt.

I did a `git bisect` and this started occurring in #4960.

### How to reproduce

Launch Nu, check contents of $env.PWD

### Expected behavior

I expected a single backslash as a directory separator.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.1                                   |
| branch             | main                                     |
| short_commit       | 5586d4a0                                 |
| commit_hash        | 5586d4a0a0c95d8e7149834a150fb54bd6281411 |
| commit_date        | 2022-03-27 22:11:56 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.60.1                                   |
| build_time         | 2022-03-27 15:57:19 -07:00               |
| build_rust_channel | debug                                    |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

**Comment by jntrnr** [comment]
Sigh - so does this mean some environment variables will need `"` and some will need `'`?

I'm wondering if we want a kind of third option that's totally raw. like maybe `'''` on either side

**Comment by fdncred** [comment]
I'm not a big fan of python style triple quoting. How about something using another symbol like:
- `@'this is 'my' raw string'@`
- `@"this is "my" raw string"@`

**Comment by hustcer** [comment]
I thinks this should be better:
```
`'this is 'my' raw string'`
`"this is "my" raw string"`
```

**Comment by hustcer** [comment]
> I'm wondering if we want a kind of third option that's totally raw. like maybe ''' on either side

This way is also good, +1

**Comment by jntrnr** [comment]
Circling back to this... I'm not entirely sure the problem was escaping. That's what I thought at first, but now I'm not so sure.

```
> let-env FOO = "\\bar"
> $env.FOO
\bar
```

I wonder if it has to do with the environment importer doing a step it shouldn't

**Comment by fdncred** [comment]
looks like https://github.com/nushell/nushell/pull/5090 has fixed this for me.

**Comment by rgwood** [comment]
Fixed for me too, thanks JT!
