### ISSUE TITLE
Numpad enter not working

### ISSUE THREAD

**Issue by Dialga** [nushell/nushell#5005]
### Describe the bug

You can't press up and numpad Enter to rerun the last command

### How to reproduce

Run some command
Press up
Press Enter on numpad

### Expected behavior

command to reexecute

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.60.0                                    |
| branch             | makepkg                                   |
| short_commit       | 74af31a4                                  |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315  |
| commit_date        | 2022-03-22 19:07:11 +00:00                |
| build_os           | linux-x86_64                              |
| rust_version       | rustc 1.59.0 (Arch Linux rust 1:1.59.0-1) |
| cargo_version      | cargo 1.59.0                              |
| pkg_version        | 0.60.0                                    |
| build_time         | 2022-03-23 00:39:08 +00:00                |
| build_rust_channel | release                                   |
| features           | dataframe, default, trash, which, zip     |
| installed_plugins  |                                           |

**Comment by fdncred** [comment]
have you tested this with the command `keybinding listen` to see if nushell can even "hear" these key presses? sometimes terminals will "eat" them before nushell can "hear" them.

**Comment by sholderbach** [comment]
Can not reproduce on my Ubuntu "20.04 focal fossa" system (gnome desktop/gnome terminal). For me, the numpad's enter gets mapped to the same key event as the main enter button (As confirmed by `keybinding listen`). For the key event listening over the terminal we use the `crossterm` Rust crate. If there is no special behavior in your terminal emulator observable by `keybinding listen` it might make sense to raise the issue with `crossterm` with additional info on the terminal emulator (does it intercept certain keys explicitly) and desktop environment (Wayland or X might remap keys/keycodes as well as the desktop config).

Feel free to reopen if you have more info from your system, that might help narrow it down

**Comment by tforgione** [comment]
For anyone interested, I had the same problem with alacritty + nushell. There is this very weird thing where `keybinding listen` believes that I press Ctrl+J when I press the numpad enter key:

```
char: j, code: 0x00006a, modifier: KeyModifiers(CONTROL), flags: 0b000010, kind: Press, state: KeyEventState(0x0)
```

The same doesn't happen with terminator:

```
code: Enter, modifier: KeyModifiers(0x0), flags: 0b000000, kind: Press, state: KeyEventState(0x0)
```

What's interesting is that when I go in terminator / zsh and I sent the keypress, it seems to behave as if I had pressed enter.

Anyway, right now, I fixed this by adding the following object in my keybindings:

```
{
    name: newline_or_run_command_2
    modifier: CONTROL
    keycode: char_j
    mode: emacs
    event: {send: enter}
}
```
