### ISSUE TITLE
Completion of cd lists files

### ISSUE THREAD

**Issue by Spacelord-XaN** [nushell/nushell#5006]
### Describe the bug

The completion of the Change directory (cd) command does list files and directories.

### How to reproduce

1. In a directory that contains files and sub-directories
2. type cd
3. press tab

### Expected behavior

It should list only directories.

### Screenshots

![WindowsTerminal_llnnvpXPur](https://user-images.githubusercontent.com/11078891/160344557-1f1dea18-10b8-4717-af8d-2ed7b84feae0.png)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.0                                   |
| short_commit       | 74af31a4                                 |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315 |
| commit_date        | 2022-03-22 19:07:11 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.60.0                                   |
| build_time         | 2022-03-22 19:26:49 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by hustcer** [comment]
Completion of cd lists only directories now on the latest main
