### ISSUE TITLE
multiple value support for (custom) completion

### ISSUE THREAD

**Issue by ottointhesky** [nushell/nushell#5012]
Currently, a parameter can only be followed by (non or) a single value. When using python and the standard argparse functionality, you can define how many values should be ‘consumed’ by a specific parameter (see https://docs.python.org/3/library/argparse.html#nargs). This way you can avoid repeating the corresponding parameter name over and over again (instead of ‘--opt val1 –opt val2 –opt val3’ one can write '--opt val1 val2 val3’). The Boost program option library provides exactly the same feature (https://stackoverflow.com/questions/8175723/vector-arguments-in-boost-program-options). We are using this feature quite extensively (in C++ and Python) and it would be fantastic if we could create matching completion definitions for our tools.

**Comment by jntrnr** [comment]
While you'll be able to call external commands and pass the same flag multiple times, it's unlikely we'll support this in Nushell. In Nushell, you can use one flag and pass the whole list you want at one go, without having to use the repeat flag workaround.

**Comment by ottointhesky** [comment]
I'm not sure that I was understood correctly. Refering to the custom completion example. Let's assume we have an extern exceutable named 'my-test' that expects the parameter --animals with mutliple values. I can define the compeletion as follows:

module commands {
    def animals [] { ["cat", "dog", "eel" ] }
    export extern my-test [
        --animals: string@animals
    ] 
}

And the completion support works perfectly for the "first animal". But for a second or third value I do not get the "cat", "dog", "eel"  suggestion. It would be great if I can tell nushell that multiple or a specific number of elements (in this case "string@animals") are excepted.  As mentoined in my first post, this behaviour is support by several standard option parsing libraries.
