### ISSUE TITLE
Nushell crashes after overriding builtin function with a function that calls the original

### ISSUE THREAD

**Issue by Yethal** [nushell/nushell#5013]
### Describe the bug

Defining a function with the same name as a builtin nushell function and calling the original version within the scope of that function causes nushell to use the overriden version and not the original creating infinite recursion and crash

### How to reproduce

Import following module to nu:
`export def-env cd [
  arg
] {
  echo $arg
  cd $arg
}`
Try changing directory
Notice the arg is repeatedly echoed until the crash

### Expected behavior

Function works as expected (echo the arg and change directory)

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.60.0                                              |
| build_os           | linux-x86_64                                        |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)                 |
| rust_channel       | stable-x86_64-unknown-linux-gnu                     |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)                 |
| pkg_version        | 0.60.0                                              |
| build_time         | 2022-03-22 22:32:35 +01:00                          |
| build_rust_channel | release                                             |
| features           | default, trash, which, zip                          |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by fdncred** [comment]
ya, like i said in discord, i think  you have to have 2 custom commands to override one so it doesn't go into the infinite recursion.  here's my `ls` example again.
```
def old-ls [path?] {
  if $path == $nothing {
    ls . | sort-by type name -i
  } else {
    ls $path | sort-by type name -i
  }
}

# ls sort type name -i
def ls [path?] {
  if $path == $nothing {
    old-ls .
  } else {
   old-ls $path
  }
}
```

**Comment by jntrnr** [comment]
A definition, from inside of itself, will see itself recursively first. Effectively, you're checking the recursion checking here.

With the latest main, we get an error from having too much recursion:

```
~/Source/nushell> cd foo
Error: nu::shell::recursion_limit_reached

  × Recursion limit (50) reached
   ╭─[entry #4:1:1]
 1 │ def-env cd [ arg ] { echo $arg; cd $arg }
   ·                    ───────────┬──────────
   ·                               ╰── This called itself too many times
   ╰────
```

Going ahead and closing, as I think we're in an expected state at this point.
