### ISSUE TITLE
Strip '+ ' decoration in git branch list (current branch in some worktree) [completions]

### ISSUE THREAD

**Issue by naufraghi** [nushell/nushell#5014]
https://github.com/nushell/nushell/blob/1aef3a730a21ef0b4048c6cd2db8df6592831592/docs/sample_config/default_config.nu#L64

Tested with:

```py
  def "nu-complete git branches" [] {
    ^git branch | lines | each { |line| $line | str find-replace '[\*\+] ' '' | str trim }
  }
```

If interested I can open a PR.

**Comment by fdncred** [comment]
i think it's fine to PR this - i don't think it'll bother people who don't need it since, i believe, that find-replace is regex.
