### ISSUE TITLE
Externals string arguments don't work with extern

### ISSUE THREAD

**Issue by elferherrera** [nushell/nushell#5015]
### Describe the bug

It seems that the string interpolation doesn't work when an external has an extern defined

```
git branch | lines | find ISSUE | each { |$it| $it | str trim } | each { |$branch| git branch -d $"($branch)" } 
```

In this case the git branch command has an extern defined. When running this one liner git errors with the message

error: branch '' not found

If the extern is removed then the command works

### How to reproduce

1. define an extern command for `git branch`
2. run the next command
```
git branch | lines | find ISSUE | each { |$it| $it | str trim } | each { |$branch| git branch -d $"($branch)" } 
```

### Expected behavior

The branches with the word ISSUE should be deleted

### Configuration

Main branch

**Comment by filaretov** [comment]
I think it has something to do with the `$branch` variable not being bound/found properly. Other variables work and the string interpolation itself evaluates.

**Comment by filaretov** [comment]
I think #5125 and #5140 fix this issue, this can be closed.
