### ISSUE TITLE
Nushell 0.60 seems to break alias

### ISSUE THREAD

**Issue by ws93** [nushell/nushell#5018]
### Describe the bug

I upgraded to 0.60.0 and found that my `python` executable stopped working with following error message:
```
/Users/ws/dev〉python                                                         03/28/2022 09:51:05 PM
Error: nu::shell::external_command (link)

  × External command
   ╭─[entry #1:1:1]
 1 │ python
   · ───┬──
   ·    ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)
``` 
But this was apparently working on my previous version of Nushell and it's still working in my iTerm2. I tested with some other executable like `go` and they are working fine. Then I noticed that  I configured `python` to be an alias for `python3.10` and if I run `python3.10` from Nushell 0.60.0, it will work fine. So this new version seems to break aliases?

### How to reproduce

1. Add some alias in your original terminal. For me, I added a line `alias goo="go"` in my `~/.zshrc` file inside my iTerm2 terminal
2. Restart terminal or run `source ~/.zshrc` to pick up that alias change
3. Try running `goo` in original terminal and it should work the same as `go`
4. open Nushell and run `goo` (alias). it will give me that `can't run executable` error. But running `go` (real command) inside Nushell works fine. 

### Expected behavior

I expect all the aliases defined in my original terminal should still work in Nushell

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.60.0                              |
| build_os           | macos-aarch64                       |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23) |
| rust_channel       | stable-aarch64-apple-darwin         |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10) |
| pkg_version        | 0.60.0                              |
| build_time         | 2022-03-22 21:40:02 -04:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |

**Comment by Eschryn** [comment]
For me aliases have been working fine. So I just want to ask if you've updated you're configuration as nushell has a new configuration format that is incompatible with the old one

**Comment by kubouch** [comment]
I haven't had a problem with aliases either:
```
> alias python = python3.10

> which python
  #      arg              path           built-in
───────────────────────────────────────────────────
  0   python3.10   /usr/bin/python3.10   false

> python
Python 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Did you define the aliases inside Nushell or before running Nushell? The reproduction steps are not very clear, maybe you can make them more precise?

**Comment by ws93** [comment]
> I just want to ask if you've updated you're configuration 

I didn't update the nushell config. Just did a `cargo install nu`

> Did you define the aliases inside Nushell or before running Nushell?

I defined these aliases in original iTerm2 terminal and before running Nushell

**Comment by hustcer** [comment]
> I defined these aliases in original iTerm2 terminal and before running Nushell

Nushell won't aware of the aliases you defined previously, you have to redefine them in `$nu.config-path`

**Comment by kubouch** [comment]
Yeah, Nushell will grab only environment variables but not aliases from the parent shell.

**Comment by ws93** [comment]
Ah got it. I'm new to Nushell and didn't know that.

Just want to share my experience in case this is something unexpected. And aliases from parent shell was definitely working in older version of Nushell (< 0.60.0). Not sure why.

**Comment by ws93** [comment]
Close this ticket per above

**Comment by kubouch** [comment]
I think they worked before because we used to shell out when running an external (it would spawn bash or something and run the external through that). Now, we run the external directly. I would argue the previous behavior was a bug actually.
