### ISSUE TITLE
Types for `git push` are incorrect

### ISSUE THREAD

**Issue by ErichDonGubler** [nushell/nushell#5021]
### Describe the bug

Currently, `git push`'s is typed to only accept a single positional argument. This is incorrect, however, as multiple branches are definitely accepted by Git.

### How to reproduce

1. Attempt to push multiple new branches at a time to a remote repository in Git. Observe that the command is rejected, and the following diagnostic is emitted:

    ```
	git push -u origin a b c d
	Error: nu::parser::extra_positional (link)
	
	  × Extra positional argument.
	   ╭─[entry #7:1:1]
	 1 │ git push -u origin a b c d
	   ·                      ┬
	   ·                      ╰── extra positional argument
	   ╰────
	  help: Usage: git push {flags} (remote) (refspec)
    ```

### Expected behavior

Observe that escaping the command as an external works just fine:

```
^git push -u origin a b c d
```

I expect `nu` to model that correctly.

**Comment by jntrnr** [comment]
For anyone who wants to work on this one - the current types are https://github.com/nushell/nushell/blob/main/docs/sample_config/default_config.nu

**Comment by dev-msp** [comment]
I think this is actually the same thing as #5012, the multi-value completion feature.

**Comment by jntrnr** [comment]
In this case, I think you could also switch the typing to use `...rest` instead of having a single position?

**Comment by hustcer** [comment]
@ErichDonGubler You can try the latest config here:
https://github.com/nushell/nushell/blob/7490392eb982fbbc1036bf9356ada84764f601b1/docs/sample_config/default_config.nu#L44

**Comment by ErichDonGubler** [comment]
@hustcer: Just tested, WFM! Yay! Thank you! ❤️
