### ISSUE TITLE
Plugins with capnp can't use cell path

### ISSUE THREAD

**Issue by sophiajt** [nushell/nushell#5023]
### Describe the bug

capnp has some limitations on what types it supports for parameters. Because of this, you can't use capnp with eg commands that need cell paths.

### How to reproduce

Use a cell path in your command and pick capnp.

If you switch with json, it will work.

### Expected behavior

Capnp should support all the same features as the json one

**Comment by sholderbach** [comment]
capnp plugin protocol has been removed
