### ISSUE TITLE
Nushell 0.60 startup hangs / double-prompt

### ISSUE THREAD

**Issue by danjenson** [nushell/nushell#5025]
### Describe the bug

Nushell 0.60 does weird things when starting:
1. Occasionally hangs
2. Creates a second prompt

From the screenshot, you can also see that exiting it leaves the prompt in the middle of the window...not sure if this is a nushell, alacritty, or bspwm issue, but I don't recall it being an issue before.

### How to reproduce

Start a new terminal.

### Expected behavior

No double prompts or hanging (doesn't happen every time, maybe every 10th time or so?).

### Screenshots

![nushell_double_prompt](https://user-images.githubusercontent.com/4793438/160750995-985163d3-a5be-4f1d-a20b-d6841935d018.gif)

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.60.0                                      |
| build_os           | linux-x86_64                                |
| rust_version       | rustc 1.61.0-nightly (ab0c2e18d 2022-03-27) |
| rust_channel       | nightly-x86_64-unknown-linux-gnu            |
| cargo_version      | cargo 1.61.0-nightly (109bfbd 2022-03-17)   |
| pkg_version        | 0.60.0                                      |
| build_time         | 2022-03-29 10:47:38 -07:00                  |
| build_rust_channel | release                                     |
| features           | dataframe, default, trash, which, zip       |
| installed_plugins  |                                             |

**Comment by jntrnr** [comment]
We have seen some issues with alacritty + nushell. Does it still happen if you use a different terminal?

**Comment by kubouch** [comment]
I use alacritty + i3 window manager and haven't had problems for a long while.

**Comment by rgwood** [comment]
Has anyone seen this recently? I haven't, possible it's been fixed.

**Comment by zggff** [comment]
Yes this issue is still present for me.

**Comment by rgwood** [comment]
@zggff Can you confirm which issue you're experiencing? Hangs, the double prompt, both?

Would also help to get your version (`version | transpose key value | to md --pretty`) and terminal info.

**Comment by zggff** [comment]
It also happens when resizing the terminal window.

**Comment by JaoCR** [comment]
March 23 and problem is still going on. Tried to set up nu today, Linux machine. Second prompt will show up whenever I increase the height of the window. The number of empty lines  between the old and new prompt is directly proportional to the increase in size. Most inconveniently, it will also happen on the startup of the terminal emulator (both gnome terminal and alacritty), which tells me the window is being resized after the terminal is started, probably. Any ideas?  

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.76.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | linux-x86_64                         |
| build_target       | x86_64-unknown-linux-gnu             |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)  |
| rust_channel       | stable-x86_64-unknown-linux-gnu      |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)  |
| pkg_version        | 0.76.0                               |
| build_time         | 2023-03-01 11:24:17 -03:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

**Comment by Zoybean** [comment]
There's another issue specific to the double prompt issue: #4937
I suspect this only happens alongside the hang on startup, because when it hangs, you split the terminal to try again.

**Comment by jntrnr** [comment]
Close this, as I think this issue is happening because of the tiling window manager + https://github.com/nushell/reedline/issues/620

Once that gets fixed, in theory this should be fixed. At the very least, this is a reedline issue rather than a nushell one.
