### ISSUE TITLE
Readable (ANSI compatible) colors by default

### ISSUE THREAD

**Issue by chtenb** [nushell/nushell#5028]
### Related problem

When I run `ls`, `nu` uses colors that are not from my terminal color palette, i.e. colors that are not ANSI colors. The same is true for other commands and menus. Sometimes this makes the text un- or less readable. From the documentation about colors it is not clear how the colors used by `nu` map onto the ANSI colors. Some colors seem to map, others don't.

Another issue is that `nu` uses the `inverse` graphic rendition with two (arbitrary?) ANSI colors for some things like menu's. This is also not guaranteed to be readable.
![image](https://user-images.githubusercontent.com/1030961/160797820-b9831a4c-685a-4398-9c5a-2b67f621cf81.png)

Would there be a more robust way to do this?

### Describe the solution you'd like

I would like the default set of colors to use the ANSI colors only. A second best solution would be to have an easy way to configure `nu` to only use ANSI colors.

For color inverted rendition (in menu's) I think only the default foreground and background colors should be used, as they are the most likely to produce a readable color inverted rendition. Or when a certain color is necessary or desirable then at least the color should be inverted with the default background color, and not with another color.

**Comment by sholderbach** [comment]
For the basic foreground colors I think (nu-)ansi-term maps them to the respective 4-bit colors that are affected by theming. Don't know how the inversion is handled of the cuff.

**Comment by fdncred** [comment]
I believe any normal color defined in the config with a color name like green will be mapped to the terminal's color palette. These are specified as ansi escapes by nu-ansi-term. 

Any color like a hex color or style with hex colors are the exact colors specified.

**Comment by chtenb** [comment]
> I believe any normal color defined in the config with a color name like green will be mapped to the terminal's color palette. These are specified as ansi escapes by nu-ansi-term.

That would make sense, but I can't mentally map the the colors listed under [normal colors](https://www.nushell.sh/book/coloring_and_theming.html#normal-colors-and-abbreviations) to ANSI colors, because ANSI doesn't have a `light green` or `dark gray` color.

> You can see that it uses the nu-ansi-term crate

Judging from its README it also supports EXTENDED ANSI colors (those 256 colors) and true colors. When I referred to ANSI colors in the OP I meant the 16 ANSI colors (4 bit colors).

> Can you provide your platform information as requested in the issue form? 

Looks like that is only in the "bug report" issue form :)

> are you using the default configuration found in default_config.nu in the repo? 

Yes, though I had to comment out the help config related things, because they spawned warnings.
I'll paste it anyway.

|key|value|
|-|-|
|version|0.60.0|
|short_commit|74af31a4|
|commit_hash|74af31a42ff4feb8d5d9897c0d99c7434678a315|
|commit_date|2022-03-22 19:07:11 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.59.0 (9d1b2106e 2022-02-23)|    
|rust_channel|stable-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.59.0 (49d8809dc 2022-02-10)|   
|pkg_version|0.60.0|
|build_time|2022-03-22 19:26:49 +00:00|
|build_rust_channel|release|
|features|dataframe, default, trash, which, zip|      
|installed_plugins||



```nu
# Nushell Config File

# Specifies how environment variables are:
# - converted from a string to a value on Nushell startup (from_string)
# - converted from a value back to a string when running external commands (to_string)
# Note: The conversions happen *after* config.nu is loaded
let-env ENV_CONVERSIONS = {
  "PATH": {
    from_string: { |s| $s | split row (char esep) }
    to_string: { |v| $v | str collect (char esep) }
  }
  "Path": {
    from_string: { |s| $s | split row (char esep) }
    to_string: { |v| $v | str collect (char esep) }
  }
}

# Directories to search for scripts when calling source or use
#
# By default, <nushell-config-dir>/scripts is added
let-env NU_LIB_DIRS = [
    ($nu.config-path | path dirname | path join 'scripts')
]

# Directories to search for plugin binaries when calling register
#
# By default, <nushell-config-dir>/plugins is added
let-env NU_PLUGIN_DIRS = [
    ($nu.config-path | path dirname | path join 'plugins')
]

module completions {
  # Custom completions for external commands (those outside of Nushell)
  # Each completions has two parts: the form of the external command, including its flags and parameters
  # and a helper command that knows how to complete values for those flags and parameters
  #
  # This is a simplified version of completions for git branches and git remotes
  def "nu-complete git branches" [] {
    ^git branch | lines | each { |line| $line | str find-replace '[\*\+] ' '' | str trim }
  }

  def "nu-complete git remotes" [] {
    ^git remote | lines | each { |line| $line | str trim }
  }

  export extern "git checkout" [
    branch?: string@"nu-complete git branches" # name of the branch to checkout
    -b: string                                 # create and checkout a new branch
    -B: string                                 # create/reset and checkout a branch
    -l                                         # create reflog for new branch
    --guess                                    # second guess 'git checkout <no-such-branch>' (default)
    --overlay                                  # use overlay mode (default)
    --quiet(-q)                                # suppress progress reporting
    --recurse-submodules: string               # control recursive updating of submodules
    --progress                                 # force progress reporting
    --merge(-m)                                # perform a 3-way merge with the new branch
    --conflict: string                         # conflict style (merge or diff3)
    --detach(-d)                               # detach HEAD at named commit
    --track(-t)                                # set upstream info for new branch
    --force(-f)                                # force checkout (throw away local modifications)
    --orphan: string                           # new unparented branch
    --overwrite-ignore                         # update ignored files (default)
    --ignore-other-worktrees                   # do not check if another worktree is holding the given ref
    --ours(-2)                                 # checkout our version for unmerged files
    --theirs(-3)                               # checkout their version for unmerged files
    --patch(-p)                                # select hunks interactively
    --ignore-skip-worktree-bits                # do not limit pathspecs to sparse entries only
    --pathspec-from-file: string               # read pathspec from file
  ]

  export extern "git push" [
    remote?: string@"nu-complete git remotes", # the name of the remote
    refspec?: string@"nu-complete git branches"# the branch / refspec
    --verbose(-v)                              # be more verbose
    --quiet(-q)                                # be more quiet
    --repo: string                             # repository
    --all                                      # push all refs
    --mirror                                   # mirror all refs
    --delete(-d)                               # delete refs
    --tags                                     # push tags (can't be used with --all or --mirror)
    --dry-run(-n)                              # dry run
    --porcelain                                # machine-readable output
    --force(-f)                                # force updates
    --force-with-lease: string                 # require old value of ref to be at this value
    --recurse-submodules: string               # control recursive pushing of submodules
    --thin                                     # use thin pack
    --receive-pack: string                     # receive pack program
    --exec: string                             # receive pack program
    --set-upstream(-u)                         # set upstream for git pull/status
    --progress                                 # force progress reporting
    --prune                                    # prune locally removed refs
    --no-verify                                # bypass pre-push hook
    --follow-tags                              # push missing but relevant tags
    --signed: string                           # GPG sign the push
    --atomic                                   # request atomic transaction on remote side
    --push-option(-o): string                  # option to transmit
    --ipv4(-4)                                 # use IPv4 addresses only
    --ipv6(-6)                                 # use IPv6 addresses only
  ]
}

# Get just the extern definitions without the custom completion commands
use completions *

# for more information on themes see
# https://www.nushell.sh/book/coloring_and_theming.html
let default_theme = {
    # color for nushell primitives
    separator: white
    leading_trailing_space_bg: { attr: n } # no fg, no bg, attr none effectively turns this off
    header: green_bold
    empty: blue
    bool: white
    int: white
    filesize: white
    duration: white
    date: white
    range: white
    float: white
    string: white
    nothing: white
    binary: white
    cellpath: white
    row_index: green_bold
    record: white
    list: white
    block: white
    hints: dark_gray

    # shapes are used to change the cli syntax highlighting
    shape_garbage: { fg: "#FFFFFF" bg: "#FF0000" attr: b}
    shape_binary: purple_bold
    shape_bool: light_cyan
    shape_int: purple_bold
    shape_float: purple_bold
    shape_range: yellow_bold
    shape_internalcall: cyan_bold
    shape_external: cyan
    shape_externalarg: green_bold
    shape_literal: blue
    shape_operator: yellow
    shape_signature: green_bold
    shape_string: green
    shape_string_interpolation: cyan_bold
    shape_datetime: cyan_bold
    shape_list: cyan_bold
    shape_table: blue_bold
    shape_record: cyan_bold
    shape_block: blue_bold
    shape_filepath: cyan
    shape_globpattern: cyan_bold
    shape_variable: purple
    shape_flag: blue_bold
    shape_custom: green
    shape_nothing: light_cyan
}

# The default config record. This is where much of your global configuration is setup.
let $config = {
  filesize_metric: false
  table_mode: rounded # basic, compact, compact_double, light, thin, with_love, rounded, reinforced, heavy, none, other
  use_ls_colors: true
  rm_always_trash: false
  color_config: $default_theme
  use_grid_icons: true
  footer_mode: "25" # always, never, number_of_rows, auto
  quick_completions: true # set this to false to prevent auto-selecting completions when only one remains
  partial_completions: true  # set this to false to prevent partial filling of the prompt
  animate_prompt: false # redraw the prompt every second
  float_precision: 2
  use_ansi_coloring: true
  filesize_format: "auto" # b, kb, kib, mb, mib, gb, gib, tb, tib, pb, pib, eb, eib, zb, zib, auto
  edit_mode: emacs # emacs, vi
  max_history_size: 10000
  menu_config: {
    columns: 4
    col_width: 20   # Optional value. If missing all the screen width is used to calculate column width
    col_padding: 2
    text_style: green
    selected_text_style: green_reverse
    marker: "| "
  }
  history_config: {
    page_size: 10
    selector: "!"
    text_style: green
    selected_text_style: green_reverse
    marker: "? "
  }
  # help_config: {
  #   columns: 4
  #   col_width: 20   # Optional value. If missing all the screen width is used to calculate column width
  #   col_padding: 2
  #   selection_rows: 4
  #   description_rows: 10
  #   text_style: green
  #   selected_text_style: green_reverse
  #   description_text_style: yellow
  #   marker: "? "
  # }
  keybindings: [
    {
      name: completion_menu
      modifier: none
      keycode: tab
      mode: emacs # Options: emacs vi_normal vi_insert
      event: {
        until: [
          { send: menu name: completion_menu }
          { send: menunext }
        ]
      }
    }
    {
      name: completion_previous
      modifier: shift
      keycode: backtab
      mode: [emacs, vi_normal, vi_insert] # Note: You can add the same keybinding to all modes by using a list
      event: { send: menuprevious }
    }
    {
      name: history_menu
      modifier: control
      keycode: char_x
      mode: emacs
      event: {
        until: [
          { send: menu name: history_menu }
          { send: menupagenext }
        ]
      }
    }
    {
      name: history_previous
      modifier: control
      keycode: char_z
      mode: emacs
      event: {
        until: [
          { send: menupageprevious }
          { edit: undo }
        ]
      }
    }
  ]
}


###### STARSHIP ######

let-env STARSHIP_SHELL = "nu"

def create_left_prompt [] {
  starship prompt --cmd-duration $env.CMD_DURATION_MS $'--status=($env.LAST_EXIT_CODE)'
}

# Use nushell functions to define your right and left prompt
let-env PROMPT_COMMAND = { create_left_prompt }
let-env PROMPT_COMMAND_RIGHT = ""

# The prompt indicators are environmental variables that represent
# the state of the prompt
let-env PROMPT_INDICATOR = ""
let-env PROMPT_INDICATOR_VI_INSERT = ": "
let-env PROMPT_INDICATOR_VI_NORMAL = "〉"
let-env PROMPT_MULTILINE_INDICATOR = "::: "
```

**Comment by chtenb** [comment]
> That would make sense, but I can't mentally map the the colors listed under [normal colors](https://www.nushell.sh/book/coloring_and_theming.html#normal-colors-and-abbreviations) to ANSI colors, because ANSI doesn't have a light green or dark gray color.

I did some testing and it seems that in my terminal green and lightgreen are both the same thing. The same holds for black and darkgray. 

Anyhow, the colors used by `ls` are not among these.

**Comment by fdncred** [comment]
Thanks for there responses.

> That would make sense, but I can't mentally map the the colors listed under [normal colors](https://www.nushell.sh/book/coloring_and_theming.html#normal-colors-and-abbreviations) to ANSI colors, because ANSI doesn't have a light green or dark gray color.

These colors are represented as bold, bright, high intensity in terminals. So `light green` is the same as using the bold attribute `1` in the ansi escape for green `32` like this `ESC[1;32m`. They're just called 90-97 fg and 100-107 bg to make it easier. "bold" may not be supported in your terminal, but that's how they are created in ansi. You are right though that we support more than 8 fg colors and 8 bg colors.

What terminal are you using? I see now that you're on Windows but you must not be using Windows Terminal because it supports 4-bit, 8-bit, and 24-bit ansi color.

I'm still confused as to why your colors are messed up because we're not using anything fancy. green 'ESC[32m' and green reverse 'ESC[7;32m' are very common. Reverse/Inverted color was on the first amber and green CRTs so I'm not sure why they would not work for you. But at least, you have the option to change these settings in windows or in nushell.

**Comment by chtenb** [comment]
> So light green is the same as using the bold attribute 1 in the ansi escape for green 32 like this ESC[1;32m. 

That was what I suspected as well, but for me light green does not render with the same color as bold green. Instead light green is exactly the same as green, while bold green indeed uses the high intensity variant of the color.

> What terminal are you using?

Sorry I forgot to included that information. I'm using the integrated terminal in VSCode. 

Now I just tested the colors of nushell `ls` inside WSL with VSCode and there they appear exactly how I expected them! And strangely enough the color inverted rendering also works properly there: it uses green background with the terminal background color as foreground. That's odd

**Comment by chtenb** [comment]
And for the record, the variable `$env.LS_COLORS` is not defined.

**Comment by chtenb** [comment]
I just noticed that on WSL the LS_COLORS variable is defined:

```
echo $env.LS_COLORS
rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
```

However, on windows it is not:

```
❯ echo $env.LS_COLORS
Error: nu::shell::name_not_found (https://docs.rs/nu-protocol/0.60.0/nu-protocol/enum.ShellError.html#variant.DidYouMean)

  × Name not found
   ╭─[entry #4:1:1]
 1 │ echo $env.LS_COLORS
   ·           ────┬────
   ·               ╰── did you mean 'COLORTERM'?
```

**Comment by fdncred** [comment]
oh interesting, so maybe the `LS_COLORS` is changing this setting too, as it should for the name column.  I know a new vscode was released yesterday and i also know that their integrated terminal has been getting a major overhaul. I'm not saying it's all vscode's problem. I'm just saying that it could be part of the problem sometimes. I use the vscode terminal too but when it starts misbehaving i change to Windows Terminal. It seems to be way more solid. 

Seems like we're narrowing down things a bit - that's good.

**Comment by chtenb** [comment]
Does nushell use some kind of fallback when LS_COLORS is not defined? Perhaps that fallback contains hard color codes?

**Comment by chtenb** [comment]
> I use the vscode terminal too but when it starts misbehaving i change to Windows Terminal. 

In my experience the integrated terminal works pretty well these days, as long as you leave the zoom setting to 0.

**Comment by fdncred** [comment]
> Does nushell use some kind of fallback when LS_COLORS is not defined? Perhaps that fallback contains hard color codes?

yes. i believe if `LS_COLORS` is not defined it uses this 8-bit color sequence.
```
let-env LS_COLORS = "st=0:di=0;38;5;81:so=0;38;5;16;48;5;203:ln=0;38;5;203:cd=0;38;5;203;48;5;236:ex=1;38;5;203:or=0;38;5;16;48;5;203:fi=0:bd=0;38;5;81;48;5;236:ow=0:mi=0;38;5;16;48;5;203:*~=0;38;5;243:no=0:tw=0:pi=0;38;5;16;48;5;81:*.z=4;38;5;203:*.t=0;38;5;48:*.o=0;38;5;243:*.d=0;38;5;48:*.a=1;38;5;203:*.c=0;38;5;48:*.m=0;38;5;48:*.p=0;38;5;48:*.r=0;38;5;48:*.h=0;38;5;48:*.ml=0;38;5;48:*.ll=0;38;5;48:*.gv=0;38;5;48:*.cp=0;38;5;48:*.xz=4;38;5;203:*.hs=0;38;5;48:*css=0;38;5;48:*.ui=0;38;5;149:*.pl=0;38;5;48:*.ts=0;38;5;48:*.gz=4;38;5;203:*.so=1;38;5;203:*.cr=0;38;5;48:*.fs=0;38;5;48:*.bz=4;38;5;203:*.ko=1;38;5;203:*.as=0;38;5;48:*.sh=0;38;5;48:*.pp=0;38;5;48:*.el=0;38;5;48:*.py=0;38;5;48:*.lo=0;38;5;243:*.bc=0;38;5;243:*.cc=0;38;5;48:*.pm=0;38;5;48:*.rs=0;38;5;48:*.di=0;38;5;48:*.jl=0;38;5;48:*.rb=0;38;5;48:*.md=0;38;5;185:*.js=0;38;5;48:*.go=0;38;5;48:*.vb=0;38;5;48:*.hi=0;38;5;243:*.kt=0;38;5;48:*.hh=0;38;5;48:*.cs=0;38;5;48:*.mn=0;38;5;48:*.nb=0;38;5;48:*.7z=4;38;5;203:*.ex=0;38;5;48:*.rm=0;38;5;208:*.ps=0;38;5;186:*.td=0;38;5;48:*.la=0;38;5;243:*.aux=0;38;5;243:*.xmp=0;38;5;149:*.mp4=0;38;5;208:*.rpm=4;38;5;203:*.m4a=0;38;5;208:*.zip=4;38;5;203:*.dll=1;38;5;203:*.bcf=0;38;5;243:*.awk=0;38;5;48:*.aif=0;38;5;208:*.zst=4;38;5;203:*.bak=0;38;5;243:*.tgz=4;38;5;203:*.com=1;38;5;203:*.clj=0;38;5;48:*.sxw=0;38;5;186:*.vob=0;38;5;208:*.fsx=0;38;5;48:*.doc=0;38;5;186:*.mkv=0;38;5;208:*.tbz=4;38;5;203:*.ogg=0;38;5;208:*.wma=0;38;5;208:*.mid=0;38;5;208:*.kex=0;38;5;186:*.out=0;38;5;243:*.ltx=0;38;5;48:*.sql=0;38;5;48:*.ppt=0;38;5;186:*.tex=0;38;5;48:*.odp=0;38;5;186:*.log=0;38;5;243:*.arj=4;38;5;203:*.ipp=0;38;5;48:*.sbt=0;38;5;48:*.jpg=0;38;5;208:*.yml=0;38;5;149:*.txt=0;38;5;185:*.csv=0;38;5;185:*.dox=0;38;5;149:*.pro=0;38;5;149:*.bst=0;38;5;149:*TODO=1:*.mir=0;38;5;48:*.bat=1;38;5;203:*.m4v=0;38;5;208:*.pod=0;38;5;48:*.cfg=0;38;5;149:*.pas=0;38;5;48:*.tml=0;38;5;149:*.bib=0;38;5;149:*.ini=0;38;5;149:*.apk=4;38;5;203:*.h++=0;38;5;48:*.pyc=0;38;5;243:*.img=4;38;5;203:*.rst=0;38;5;185:*.swf=0;38;5;208:*.htm=0;38;5;185:*.ttf=0;38;5;208:*.elm=0;38;5;48:*hgrc=0;38;5;149:*.bmp=0;38;5;208:*.fsi=0;38;5;48:*.pgm=0;38;5;208:*.dpr=0;38;5;48:*.xls=0;38;5;186:*.tcl=0;38;5;48:*.mli=0;38;5;48:*.ppm=0;38;5;208:*.bbl=0;38;5;243:*.lua=0;38;5;48:*.asa=0;38;5;48:*.pbm=0;38;5;208:*.avi=0;38;5;208:*.def=0;38;5;48:*.mov=0;38;5;208:*.hxx=0;38;5;48:*.tif=0;38;5;208:*.fon=0;38;5;208:*.zsh=0;38;5;48:*.png=0;38;5;208:*.inc=0;38;5;48:*.jar=4;38;5;203:*.swp=0;38;5;243:*.pid=0;38;5;243:*.gif=0;38;5;208:*.ind=0;38;5;243:*.erl=0;38;5;48:*.ilg=0;38;5;243:*.eps=0;38;5;208:*.tsx=0;38;5;48:*.git=0;38;5;243:*.inl=0;38;5;48:*.rtf=0;38;5;186:*.hpp=0;38;5;48:*.kts=0;38;5;48:*.deb=4;38;5;203:*.svg=0;38;5;208:*.pps=0;38;5;186:*.ps1=0;38;5;48:*.c++=0;38;5;48:*.cpp=0;38;5;48:*.bsh=0;38;5;48:*.php=0;38;5;48:*.exs=0;38;5;48:*.toc=0;38;5;243:*.mp3=0;38;5;208:*.epp=0;38;5;48:*.rar=4;38;5;203:*.wav=0;38;5;208:*.xlr=0;38;5;186:*.tmp=0;38;5;243:*.cxx=0;38;5;48:*.iso=4;38;5;203:*.dmg=4;38;5;203:*.gvy=0;38;5;48:*.bin=4;38;5;203:*.wmv=0;38;5;208:*.blg=0;38;5;243:*.ods=0;38;5;186:*.psd=0;38;5;208:*.mpg=0;38;5;208:*.dot=0;38;5;48:*.cgi=0;38;5;48:*.xml=0;38;5;185:*.htc=0;38;5;48:*.ics=0;38;5;186:*.bz2=4;38;5;203:*.tar=4;38;5;203:*.csx=0;38;5;48:*.ico=0;38;5;208:*.sxi=0;38;5;186:*.nix=0;38;5;149:*.pkg=4;38;5;203:*.bag=4;38;5;203:*.fnt=0;38;5;208:*.idx=0;38;5;243:*.xcf=0;38;5;208:*.exe=1;38;5;203:*.flv=0;38;5;208:*.fls=0;38;5;243:*.otf=0;38;5;208:*.vcd=4;38;5;203:*.vim=0;38;5;48:*.sty=0;38;5;243:*.pdf=0;38;5;186:*.odt=0;38;5;186:*.purs=0;38;5;48:*.h264=0;38;5;208:*.jpeg=0;38;5;208:*.dart=0;38;5;48:*.pptx=0;38;5;186:*.lock=0;38;5;243:*.bash=0;38;5;48:*.rlib=0;38;5;243:*.hgrc=0;38;5;149:*.psm1=0;38;5;48:*.toml=0;38;5;149:*.tbz2=4;38;5;203:*.yaml=0;38;5;149:*.make=0;38;5;149:*.orig=0;38;5;243:*.html=0;38;5;185:*.fish=0;38;5;48:*.diff=0;38;5;48:*.xlsx=0;38;5;186:*.docx=0;38;5;186:*.json=0;38;5;149:*.psd1=0;38;5;48:*.tiff=0;38;5;208:*.flac=0;38;5;208:*.java=0;38;5;48:*.less=0;38;5;48:*.mpeg=0;38;5;208:*.conf=0;38;5;149:*.lisp=0;38;5;48:*.epub=0;38;5;186:*.cabal=0;38;5;48:*.patch=0;38;5;48:*.shtml=0;38;5;185:*.class=0;38;5;243:*.xhtml=0;38;5;185:*.mdown=0;38;5;185:*.dyn_o=0;38;5;243:*.cache=0;38;5;243:*.swift=0;38;5;48:*README=0;38;5;16;48;5;186:*passwd=0;38;5;149:*.ipynb=0;38;5;48:*shadow=0;38;5;149:*.toast=4;38;5;203:*.cmake=0;38;5;149:*.scala=0;38;5;48:*.dyn_hi=0;38;5;243:*.matlab=0;38;5;48:*.config=0;38;5;149:*.gradle=0;38;5;48:*.groovy=0;38;5;48:*.ignore=0;38;5;149:*LICENSE=0;38;5;249:*TODO.md=1:*COPYING=0;38;5;249:*.flake8=0;38;5;149:*INSTALL=0;38;5;16;48;5;186:*setup.py=0;38;5;149:*.gemspec=0;38;5;149:*.desktop=0;38;5;149:*Makefile=0;38;5;149:*Doxyfile=0;38;5;149:*TODO.txt=1:*README.md=0;38;5;16;48;5;186:*.kdevelop=0;38;5;149:*.rgignore=0;38;5;149:*configure=0;38;5;149:*.DS_Store=0;38;5;243:*.fdignore=0;38;5;149:*COPYRIGHT=0;38;5;249:*.markdown=0;38;5;185:*.cmake.in=0;38;5;149:*.gitconfig=0;38;5;149:*INSTALL.md=0;38;5;16;48;5;186:*CODEOWNERS=0;38;5;149:*.gitignore=0;38;5;149:*Dockerfile=0;38;5;149:*SConstruct=0;38;5;149:*.scons_opt=0;38;5;243:*README.txt=0;38;5;16;48;5;186:*SConscript=0;38;5;149:*.localized=0;38;5;243:*.travis.yml=0;38;5;186:*Makefile.in=0;38;5;243:*.gitmodules=0;38;5;149:*LICENSE-MIT=0;38;5;249:*Makefile.am=0;38;5;149:*INSTALL.txt=0;38;5;16;48;5;186:*MANIFEST.in=0;38;5;149:*.synctex.gz=0;38;5;243:*.fdb_latexmk=0;38;5;243:*CONTRIBUTORS=0;38;5;16;48;5;186:*configure.ac=0;38;5;149:*.applescript=0;38;5;48:*appveyor.yml=0;38;5;186:*.clang-format=0;38;5;149:*.gitattributes=0;38;5;149:*LICENSE-APACHE=0;38;5;249:*CMakeCache.txt=0;38;5;243:*CMakeLists.txt=0;38;5;149:*CONTRIBUTORS.md=0;38;5;16;48;5;186:*requirements.txt=0;38;5;149:*CONTRIBUTORS.txt=0;38;5;16;48;5;186:*.sconsign.dblite=0;38;5;243:*package-lock.json=0;38;5;243:*.CFUserTextEncoding=0;38;5;243"
```

**Comment by chtenb** [comment]
Ah, that explains the culprit :) When I paste that ls_colors into my WSL VSCode terminal the `ls` colors start to look like they do in the windows VSCode terminal. 

I think my feature request would be to mention this fallback explicitly in the docs ([there is a section about LS_COLORS](https://www.nushell.sh/book/coloring_and_theming.html#ls-colors-colors-for-the-ls-command)) and mention that it does not use the 4 bit ANSI colors, but the 8 bit ANSI colors.

On the inverted color rendition in the completion menu, that stays the same, even after explicitly setting the LS_COLORS variable.

**Comment by fdncred** [comment]
> On the inverted color rendition in the completion menu, that stays the same, even after explicitly setting the LS_COLORS variable.

`LS_COLORS` has nothing to do with the menus. It's only used to color file names. You can change the menu color settings in the config.nu file.

I have no problem with this feature being documenting better, but I'm still confused why your terminal is horked. Windows, VSCode, and WSL can both handle 4/8/24-bit coloring.

Here's my Windows VSCode in WSL
![image](https://user-images.githubusercontent.com/343840/161116514-bf94b699-34c8-4b67-923b-c2d0af42f520.png)

Here's my regular VSCode in Windows
![image](https://user-images.githubusercontent.com/343840/161116391-1e47b427-ca71-4343-9ff4-6008a1803c8b.png)

**Comment by chtenb** [comment]
> LS_COLORS has nothing to do with the menus. It's only used to color file names. You can change the menu color settings in the config.nu file.

I see, I misread one of your earlier posts.

> but I'm still confused why your terminal is horked. 

I think nushell part of the issue is cleared up. I just need to figure out why WSL gets a LS_COLORS from somewhere while normal Windows does not, but that is not a nushell issue.

> You can change the menu color settings in the config.nu file.

Yeah, but it's still strange that the inverted colors are wrong on Windows but correct on WSL.
But I'm starting to think that this is a problem in VSCode.

**Comment by fdncred** [comment]
ok, please close this issue when you're satisfied.

**Comment by chtenb** [comment]
I just wrote a little nushell script to test the ansi escape code behavior of a terminal

```nu
def printcolors [] {
  for $color-offset in [30 40 90 100] {
    for $color in 0..9 {
      if $color != 8 { # 8 is not a color code
        for $style in 1..9 {
          build-string $"\e[($color + $color-offset);($style)m" $'\e[($color + $color-offset)($style)m' "\e[0m"
        } | str collect
      }
    } | flatten
  } | flatten
}
```

On WSL this looks like 

![image](https://user-images.githubusercontent.com/1030961/161133227-e00ed2d7-d7f7-4f64-8dc1-49e38f8ff5cf.png)

but on vanilla windows it looks like

![image](https://user-images.githubusercontent.com/1030961/161133105-24c80c1b-a83d-472e-bfec-ed4883ffa075.png)

So the color inverted rendition issue is definitely in VSCode/windows and not in nushell.

**Comment by chtenb** [comment]
Created an issue for this over at VSCode: https://github.com/microsoft/vscode/issues/146471

**Comment by fdncred** [comment]
> I think it would be good for us to edit the default themes of nushell to use as much of the default terminal colours as possible, as this does not seem to be the case currently.

I'm not really sure what that statement means.

If LS_COLORS isn't defined it uses these defaults, which i think it based off of the `vivid snazzy` colors.
https://github.com/nushell/nushell/blob/65a163357d122e297eb7df81bce1d1207fd3431b/crates/nu-utils/src/utils.rs#L58-L65

You can see all the `vivid` colors with this script.
```nushell
vivid themes | lines | each {|theme|
  print $"Theme ($theme)"
  $env.LS_COLORS = (vivid generate $theme)
  print (ls | table)
}
```

**Comment by fdncred** [comment]
If you had an LS_COLORS env var set, it would use those, so the default is to use the end users colors. When there is no LS_COLORS env var it uses the colors above. Why? Because I liked those colors when I enabled this feature, that's all. 

It's definitely using 8-bit colors. You can see that they're using the 38;5 escape which pulls from the 256 color palette. My preference was to use 24-bit colors but there are still quite a few terminals that never upgraded to that. Using 4-bit colors would significantly limit the amount of colors.

**Comment by fdncred** [comment]
Feel free to propose a new 4-bit LS_COLORS env var. I won't be a fan since it limits it to 16 colors but others may.

One approach is to take sharkdp's vivid and add a 4bit conversion to it here https://github.com/sharkdp/vivid/blob/89e7fe37190051719ee7bfa11e0377b5e0e32515/src/color.rs#L4-L8 but that would only work with the themes that vivid supports.
