### ISSUE TITLE
Non-interactive sessions shouldn't render prompt

### ISSUE THREAD

**Issue by davidkna** [nushell/nushell#5029]
### Describe the bug

When stdin is piped into nushell non-interactively, it should not render the prompt. For instance, this means starship custom modules with nushell will result in an infinite loop without the `shell` option. Even without that, having the prompt in the output is not desirable.

### How to reproduce

1. `echo true | nu`

### Expected behavior

Don't print prompt and execute `stdin` input.

**Comment by jntrnr** [comment]
I get a different error now:

```
> echo "true" | nu
Error:   × Nushell launched as a REPL, but STDIN is not a TTY; either launch in a valid terminal or provide arguments to invoke
  │ a script!
```

I'll go ahead and close as the original issue was fixed. If there are related issues to this, please open new issues for them and we'll take a look.
