### ISSUE TITLE
Confusing error message of load-env

### ISSUE THREAD

**Issue by fellnerse** [nushell/nushell#5033]
### Describe the bug

have a look here: https://github.com/nushell/nushell/discussions/5032

### How to reproduce

```
$fnm-env | where name != PATH                                                                                                                                          03/30/2022 03:16:49 PM
╭───┬───────────────────────────┬────────────────────────────────────────────────────────────────────────────╮
│ # │           name            │                                   value                                    │
├───┼───────────────────────────┼────────────────────────────────────────────────────────────────────────────┤
│ 0 │ FNM_MULTISHELL_PATH       │ /Users/sebastianfellner/Library/Caches/fnm_multishells/84905_1648646209407 │
│ 1 │ FNM_VERSION_FILE_STRATEGY │ local                                                                      │
│ 2 │ FNM_DIR                   │ /Users/sebastianfellner/.fnm                                               │
│ 3 │ FNM_LOGLEVEL              │ info                                                                       │
│ 4 │ FNM_NODE_DIST_MIRROR      │ https://nodejs.org/dist                                                    │
╰───┴───────────────────────────┴────────────────────────────────────────────────────────────────────────────╯
```
But now I get this error, as load-env now would like to have a record. Do you know how to convert a table to record? I'm missing something like prepend for record to generate it by iterating over the table.

```
$fnm-env | where name != PATH | load-env                                                                                                                               03/30/2022 03:16:57 PM
Error: nu::shell::unsupported_input (link)

  × Unsupported input
   ╭─[entry #79:1:1]
 1 │ $fnm-env | where name != PATH | load-env
   ·                                 ────┬───
   ·                                     ╰── Record not supported
   ╰────

```
### Expected behavior

should give a hint that it should be record and not table type?

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.60.0                                |
| build_os           | macos-aarch64                         |
| rust_version       | rustc 1.59.0                          |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.60.0                                |
| build_time         | 2022-03-22 19:07:11 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

**Comment by kubouch** [comment]
You can put three backticks (3x `) around code blocks to make it easier to read
