### ISSUE TITLE
`where column > some_int` fails when filtering text file

### ISSUE THREAD

**Issue by oskarskog** [nushell/nushell#504]
While running ```ps | where pid < 10``` works as expected I found that when the input source is a normal text file ```where``` behaves differently.

```
/tmp> open file | lines | split-column ";" name gender age
━━━┯━━━━━━━━┯━━━━━━━━┯━━━━━
 # │ name   │ gender │ age
───┼────────┼────────┼─────
 0 │ mike   │ man    │ 26
 1 │ joe    │ man    │ 22
 2 │ sally  │ woman  │ 11
 3 │ joanna │ woman  │ 44
━━━┷━━━━━━━━┷━━━━━━━━┷━━━━━
```

now trying to filter this file on age

```
/tmp> open file | lines | split-column ";" name gender age | where age > 23
error: Could not evaluate (CoerceError)
- shell:1:61
1 | open file | lines | split-column ";" name gender age | where age > 23
  |                                                              ^^^^^^^^ could not evaluate
```

however, if the number filtered on inside "", it seems to work as you'd expect

```
/tmp> open file | lines | split-column ";" name gender age | where age > "23"
━━━┯━━━━━━━━┯━━━━━━━━┯━━━━━
 # │ name   │ gender │ age
───┼────────┼────────┼─────
 0 │ mike   │ man    │ 26
 1 │ joanna │ woman  │ 44
━━━┷━━━━━━━━┷━━━━━━━━┷━━━━━
```

**Comment by oskarskog** [comment]
This seems to be due to a type mismatch in the binary expression
```
ShellError { error: CoerceError { 
left: Tagged { tag: Tag { origin: None, span: Span { start: 51, end: 52 } }, item: "string" }, 
right: Tagged { tag: Tag { origin: None, span: Span { start: 55, end: 57 } }, item: "int" } }, 
cause: None }
```
Does this mean that the parser mistakes the column value to be of type string?

**Comment by jonathandturner** [comment]
@oskarskog - The split-column command is returning the parts to you as strings, rather than trying to figure out the type of each column.  In the future, we might want to add a way that you can annotate what you want the column types to be, but currently by default it's always string.  You can run the column through a `str --to-int` command to convert them to integers, as a workaround

**Comment by oskarskog** [comment]
@jonathandturner - Alright, I see. The value I'm filtering on is perceived to be an int though, couldn't the same "figuring out" function be used to map column values into their perceived type? That way  when running ```open file | lines | split-column ";" name gender age | where age > 23``` the operands are at least of the same type. Or are there some apparent down sides to this approach?

**Comment by oskarskog** [comment]
@wycats - I think you're right, auto-coercing was a bad idea. I'm all for explicitly casting like you suggested.

I guess the reason for me not realizing that ```split-column``` outputs strings is that as both ```ps``` and the file I opened show column values the same way. Then is seemed strange (from a user's perspective) that I have to do a conversion in the file case. 

I unconsciously thought that if something is a string it looks like _"this"_ , if it's an int it looks like 1, float 1.0, and so on...

So, would it make sense to show to the user of what type a column is, in some way? Or do I just have to overcome this thought pattern? :)

**Comment by androbtech** [comment]
@oskarskog As mentioned by @jonathandturner , Please try this workaround:

`open file | lines | split-column ";" name gender age | str age --to-int | where age > "23"`

let me know if it works.

**Comment by oskarskog** [comment]
@androbtech - it's giving me the same type mismatch because I cast age to int and then compare it to "23" which is a string.
```
/home/oskar/dev/nushell(master)> open /tmp/file | lines | split-column ";" name age gender | str age --to-int | where age > "23"
error: Could not evaluate (CoerceError)
- shell:1:85
1 | open /tmp/file | lines | split-column ";" name age gender | str age --to-int | where age > "23"
  |                                                                                      ^^^^^^^^^^ could not evaluate
```
I guess you meant to compare to 23 as an int? In this case it works as it should. As a simple improvement I think error messages could be more descriptive and show the types of the operands causing the error.

**Comment by androbtech** [comment]
@oskarskog Sorry about that, I typed the command incorrectly (used double quotes in 23) This is the correct way: 

`open file | lines | split-column ";" name gender age | str age --to-int | where age > 23`

**Comment by androbtech** [comment]
@jonathandturner Would be interesting to think about ideas here.

so, `open file | lines | split-column ";" name gender age | where age > 23`

What if `where` command could also analyze metadata from the input and, based on the block and their types, attempt to coerce automatically?

In this particular example `where` would look at the metadata and learn that `age` came from `split-column` and since the block compares it to an integer it could try to coerce it implicitly?

**Comment by jonathandturner** [comment]
@andrasio - your work with type inference might be helpful here, too.
