### ISSUE TITLE
tutor echo contains example that doesn't behave as described

### ISSUE THREAD

**Issue by toffaletti** [nushell/nushell#5042]
### Describe the bug

`tutor echo` contains this example, which doesn't seem to echo a list.

```
echo 1..10

You can also use echo to work with individual values of a range. In this
example, echo will create the values from 1 to 10 as a list.
```

### How to reproduce

1. run `tutor echo`
2. run `echo 1..10` as described

### Expected behavior

Given the description in the example I was expecting to see something similar to:
```
〉echo 1 2 3 4 5 6 7 8 9 10
╭───┬────╮
│ 0 │  1 │
│ 1 │  2 │
│ 2 │  3 │
│ 3 │  4 │
│ 4 │  5 │
│ 5 │  6 │
│ 6 │  7 │
│ 7 │  8 │
│ 8 │  9 │
│ 9 │ 10 │
╰───┴────╯
```

actual output is:

```
〉echo 1..10
1..10

```

### Configuration

〉version | transpose key value | to md --pretty                                                                                 03/30/2022 05:12:18 PM
| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.60.0                                |
| build_os           | macos-aarch64                         |
| rust_version       | rustc 1.59.0                          |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.60.0                                |
| build_time         | 2022-03-22 19:07:11 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

**Comment by hustcer** [comment]
`echo 1..10` indeed works different from running in nu v0.44, I guess this could be a bug

**Comment by rgwood** [comment]
Good catch. Seems like it's not much work to make ranges display as tables; I can put up a PR if the team agrees that this is the right course of action. Will confirm with people tomorrow.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/26268125/160982091-5dca8996-4591-49fc-b5f2-dc5e74e1873e.png">

**Comment by fdncred** [comment]
1. I believe changing `echo` was an intentional design change. @jntrnr can you chime in on this please?
2. I think the tutor docs need to be updated to reflect how it works now and perhaps add `print`.
3. I'm so tired of those `\\` in windows.

**Comment by toffaletti** [comment]
I found that 1..10 does work as I'd expect with | fmt, but not with | grid. The current behavior seems inconsistent in ways I don't understand.

**Comment by hustcer** [comment]
> Good catch. Seems like it's not much work to make ranges display as tables; I can put up a PR if the team agrees that this is the right course of action. Will confirm with people tomorrow.
> 

It's confirmed to be a bug that need to be fixed @rgwood
