### ISSUE TITLE
Cargo completion freezes the terminal when there is more than one target

### ISSUE THREAD

**Issue by Hofer-Julian** [nushell/nushell#5045]
# Problem:

If I use [`cargo-completions`](https://github.com/nushell/nu_scripts/blob/main/custom-completions/cargo/cargo-completions.nu)  it freezes the terminal when I have one than more possibility.

# Steps to reproduce

- Use a Rust project with multiple binaries (e.g https://github.com/BurntSushi/ripgrep)
- Type `cargo run --bin` in the terminal 
- Press tab
- No input is possible anymore and the terminal has to be killed

(The same thing happens with `cargo run --example`)

# Note

It is not obvious to me why that happens, it seems to do the same thing as the git completion which works fine.
I've only tested this on Windows.

**Comment by fdncred** [comment]
i changed the cargo completions so i could run the completers normally.
```
> cd .\ripgrep\
> nu-complete cargo bins 
╭───┬────╮
│ 0 │ rg │
╰───┴────╯
> nu-complete cargo examples 
╭───┬──────────────╮
│ 0 │ simplegrep   │
│ 1 │ search-stdin │
│ 2 │ walk         │
╰───┴──────────────╯
> cargo run --bin <tab>
```
the last command just hangs and i'm not sure why.

**Comment by fdncred** [comment]
more research. it seems that this command is hanging
`"C:\\Users\\username\\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin\cargo.exe" metadata --format-version=1 --offline --no-deps`
i can kill that subprocess and the hanging part ends.


1. i wonder if our double backslash bug is breaking it
2. i wonder if cargo is hanging by itself - i tried to run the command and it returns a json string without issue.

**Comment by jntrnr** [comment]
Closing this, as we don't ship with cargo completions anymore. If there are bugs on the cargo completions, we should probably file them on nu_scripts (if they still repro) or if we think it's a nushell related issue, then to reduce the repro and file a new issue here.
