### ISSUE TITLE
Panic when using 'open' on custom created parser ('from ...' command)

### ISSUE THREAD

**Issue by neosam** [nushell/nushell#5046]
### Describe the bug

When a new "from ..." command is created to parse a custom format, the open command panics:

> thread 'main' panicked at 'Internal error: can't run custom command with 'run', use block_id', /home/neosam/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-protocol-0.60.0/src/signature.rs:524:9
> stack backtrace:
>    0:     0x56051de82bc4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
>    1:     0x56051d22fbec - core::fmt::write::h753c7571fa063ecb
>    2:     0x56051de79982 - std::io::Write::write_fmt::h2815c0519c99ba09
>    3:     0x56051de85922 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
>    4:     0x56051de855b3 - std::panicking::default_hook::hda898f8d3ad1a5ae
>    5:     0x56051de85f2d - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
>    6:     0x56051de85c27 - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
>    7:     0x56051de830d4 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
>    8:     0x56051de859ad - rust_begin_unwind
>    9:     0x56051cdf6291 - core::panicking::panic_fmt::h3a79a6a99affe1d5
>   10:     0x56051d7404a7 - <nu_protocol::signature::BlockCommand as nu_protocol::engine::command::Command>::run::h37bb857f1d1a5781
>   11:     0x56051d3ab7cb - <nu_command::filesystem::open::Open as nu_protocol::engine::command::Command>::run::h4eed7565a1bb9989
>   12:     0x56051d614263 - nu_engine::eval::eval_call::h143c55f688c546d0
>   13:     0x56051d618695 - nu_engine::eval::eval_expression_with_input::h7aca2905d949b400
>   14:     0x56051d61897a - nu_engine::eval::eval_block::h795345480ddffd9d
>   15:     0x56051d32262f - nu_cli::util::eval_source::h32a0fd53a3f01501
>   16:     0x56051d328149 - nu_cli::repl::evaluate_repl::heb7a5af0b56b8866
>   17:     0x56051d2f5fe4 - nu::main::he2a1195c03575f41
>   18:     0x56051d3022fd - std::sys_common::backtrace::__rust_begin_short_backtrace::h55d9f15a97acd3cc
>   19:     0x56051d304a45 - std::rt::lang_start::{{closure}}::hb5935dab7cf45c3a
>   20:     0x56051de822f9 - std::rt::lang_start_internal::h52e73755f77c7dd9
>   21:     0x56051d2f7c6e - main
>   22:     0x7f7f434f7fd0 - __libc_start_call_main
>                                at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
>   23:     0x7f7f434f807d - __libc_start_main_impl
>                                at ./csu/../csu/libc-start.c:409:3
>   24:     0x56051ce22565 - _start
>   25:                0x0 - <unknown>

I'm using nushell 0.6.0 on Ubuntu 21.10.

### How to reproduce

In this example lets create a parser for foobar separated values (fsv):
1. Create the "from foobar" function:  def "from foobar" [] { lines | split column "foobar" }
2. Create the fsv: echo "afoobarb\ncfoobard" | save test.foobar
3. Try to open the fsv:  open ./test.foobar

### Expected behavior

It should give me a table with two columns and two rows.  The cells should be a, b, c and d.   Instead it panics.

**Comment by neosam** [comment]
I've created a pull requires which at least prevents nushell from crashing but I didn´t figure out how to run a command using the block_id.

**Comment by neosam** [comment]
Now I found a way to fix the bug and updated my PR.

**Comment by hustcer** [comment]
Confirm fixed by https://github.com/nushell/nushell/pull/5049, Thanks
