### ISSUE TITLE
`nu` should have a mode like `bash -c`

### ISSUE THREAD

**Issue by mb21** [nushell/nushell#505]
> Original: "`nu` could read command so it could serve as a jq replacement"

Change usage to:

    nu [OPTIONS] [COMMAND]

so you could do:

    nu 'open https://api.github.com/repos/stedolan/jq/commits | first 1 | to-json'

This could make nu a viable replacement for [jq](https://stedolan.github.io/jq/) so nu could sneak itself into bash scripts etc. that currently use jq. The equivalent jq command to the above is:

     curl https://api.github.com/repos/stedolan/jq/commits | jq '.[0]'

Care would have to be taken to pipe the stdin and stdout correctly.

**Comment by jonathandturner** [comment]
We support `nu -c` now, closing
