### ISSUE TITLE
`nu -c` doesn't have access to custom commands

### ISSUE THREAD

**Issue by danjenson** [nushell/nushell#5053]
### Describe the bug

I define a bunch of commands in my `config.nu` file (previously my `init.nu`). However, when I run `nu -c` it no longer has access to these functions, even if I specify a config:
```nushell
nu --config ~/.config/nushell/config.nu -c 'my_custom_func'
```
This worked previously, and I started to transition a lot of my sxhkd functions from bash to nushell, but now they don't work.

### How to reproduce

1. Define a function in the config.
2. Try to execute it with `nu -c`.

### Expected behavior

Previously, nushell had access to my custom functions, but now it can't seem to locate them and I'm not sure how to make it aware of them.

### Screenshots

![image](https://user-images.githubusercontent.com/4793438/161156637-c40eb757-551c-4ff8-93c2-070906d37d21.png)

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.60.0                                      |
| build_os           | linux-x86_64                                |
| rust_version       | rustc 1.61.0-nightly (ab0c2e18d 2022-03-27) |
| rust_channel       | nightly-x86_64-unknown-linux-gnu            |
| cargo_version      | cargo 1.61.0-nightly (109bfbd 2022-03-17)   |
| pkg_version        | 0.60.0                                      |
| build_time         | 2022-03-29 10:47:38 -07:00                  |
| build_rust_channel | release                                     |
| features           | dataframe, default, trash, which, zip       |
| installed_plugins  |                                             |

**Comment by hustcer** [comment]
It works on my mac after this PR: https://github.com/nushell/nushell/pull/5618
