### ISSUE TITLE
`nu ['-c' 'version']` doesn't work as expected

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#5056]
### Describe the bug

`nu ['-c' 'version']` doesn't work as expected

### How to reproduce

It's found that
```bash
> let args = [ 
  '-c' 
  'version'
] 
> nu $args
```
works, but `nu ['-c' 'version']` doesn't work

```shell
$> nu ['-c' 'version']
Error:
  × No such file or directory (os error 2)
```

### Expected behavior

`nu ['-c' 'version']` should output just the same as `nu -c version`

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.1                                   |
| branch             | main0                                    |
| short_commit       | a00f5c89                                 |
| commit_hash        | a00f5c89c2c80fb4ad3459a94e58462cb5008012 |
| commit_date        | 2022-04-01 01:44:39 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0                             |
| cargo_version      | cargo 1.59.0                             |
| pkg_version        | 0.60.1                                   |
| build_time         | 2022-04-01 09:50:37 +08:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | gstat                                    |

### Additional context

In bash we can do:
```
nu \
  -c 'version'
```
to break command in multiple lines, if `nu ['-c' 'version']` works we can break lines easier:
```
nu -c [
    'custom-command'
    '--long-flag-a=a'
    '--long-flag-b=b'
    positionArg1
    arg2
]
```

**Comment by kubouch** [comment]
The 
```
nu -c [
    'custom-command'
    '--long-flag-a=a'
    '--long-flag-b=b'
    positionArg1
    arg2
]
```
does not work by design since the `-c` flag supports a string argument only. You'd need to do `nu -c ([...] | str collect ' ')`

What I see as a problem is that
```
nu ['-c' 'version']
```
does not work while
```
nu (['-c' 'version'])
```
does. We might want to fix that one.

**Comment by hustcer** [comment]
@kubouch Fine, That’s acceptable
