### ISSUE TITLE
External 'drop through' cmds cannot run on Windows mapped network drives`

### ISSUE THREAD

**Issue by MCoooo** [nushell/nushell#5059]
### Describe the bug

When cd'ing into a mapped network drive, nushell presents the drive as a DOS UNC path. CMD.exe does not support UNC paths.

### How to reproduce

1. Create mapped network drive
2. cd into the drive
3. Run dir - because ls currently failing :))
5. CMD.exe complains:
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
6. Displays c:\Windows contents

### Expected behavior

1. When changing directory into a mapped network drive the user should be running off the mapped drive path, e.g. L:\  (or at least give an option)
2. This will prevent legacy components with such dependencies from failing.

**Comment by fdncred** [comment]
I think this is also related to #4863

**Comment by MCoooo** [comment]
Yes, agreed. Thanks for aligning.
