### ISSUE TITLE
With starship: Terminal crashes when a command waiting for stdin is aborted

### ISSUE THREAD

**Issue by Hofer-Julian** [nushell/nushell#5074]
### Describe the bug

Opening an issue here, but I am not sure whether nushell or starship needs to be fixed.
With activated starship prompt the terminal crashes when a command waiting for stdin is aborted.

### How to reproduce

1. Enable starship as described [here](https://github.com/starship/starship#step-2-setup-your-shell-to-use-starship) 
2. Run `cat` (or `bat` on Windows) with no parameters
3. Abort by pressing `ctrl-c`
4. See the followng error:
```
error: Found argument '-1' which wasn't expected, or isn't valid in this context

	If you tried to supply `-1` as a value rather than a flag, use `-- -1`

USAGE:
    starship prompt [OPTIONS]

For more information try --help

NOTE:
    passed arguments: ["prompt", "--cmd-duration", "1128", "--status", "-1"]
```
5. Press `ctrl-d`
6. The terminal crashes

### Expected behavior

1. Enable starship as described [here](https://github.com/starship/starship#step-2-setup-your-shell-to-use-starship) 
2. Run `cat` (or `bat` on Windows)
3. Abort by pressing `ctrl-c`
4. An empty prompt appears

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.60.0                                |
| build_os           | linux-x86_64                          |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)   |
| rust_channel       | stable-x86_64-unknown-linux-gnu       |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)   |
| pkg_version        | 0.60.0                                |
| build_time         | 2022-03-23 08:05:49 +01:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

### Additional context

I've also reproduced that on Windows

**Comment by fdncred** [comment]
I just reproduced this in nushell. I think that error message is from `starship` so I think the problem is there. It appears that `starship` doesn't like negative return values maybe? I also tested this in the nushell prompt without `starship` and nushell worked fine.

**Comment by Hofer-Julian** [comment]
> I just reproduced this in nushell. I think that error message is from `starship` so I think the problem is there. It appears that `starship` doesn't like negative return values maybe? I also tested this in the nushell prompt without `starship` and nushell worked fine.

Indeed.
See https://github.com/starship/starship/pull/3833
