### ISSUE TITLE
We should optimize for speed

### ISSUE THREAD

**Issue by FilipAndersson245** [nushell/nushell#5076]
### Related problem

Currently, we utilize `opt-level = "s"` in `Cargo.toml` this weights the compiler more for binary size over that of speed. With the new engine, the overall binaries are a lot smaller than previously. I propose we optimize for speed instead. removing this config.

### Describe the solution you'd like

I like us to remove `opt-level = "s"` this will use the default profile,

### Describe alternatives you've considered

If the reduced compile time is a problem I think we should at least enable this for release builds done released here on GitHub.

### Additional context and details

I examined on my machine how this changes filesize, compile-time, and runtime, to evaluate runtime I tested running the [gradient_benchmark](https://github.com/nushell/nu_scripts/blob/ca89da5242a4306880a417fcc75fe44ec3c57a8e/coloring/gradient_benchmark.nu), don't know how representative this benchmark is.

| | current  | opt-level=3 | difference   |
| ----------| ------------- | ------------- |-|
| size (nu.exe)  | 28.2MB  | 39.0MB       |  +40% |
| compile time | 9m9s  | 11m21s          |  +25% |
| runtime         | 420ms  | 379ms          | -10% |

**Comment by fdncred** [comment]
I'm not sure I'd trade 2 minutes of compile time for 40ms of performance increase.

**Comment by FilipAndersson245** [comment]
I think it would improve the user experience, to have a lower response time, Maybe we can configure release builds to run using this command instead? I don't know the general workflow of how nushell dev team use `--release` builds, as I suspect most use debug builds by default?

**Comment by fdncred** [comment]
I ran this test and here are my results
```
with current settings
cargo b --feature=extra --release
1m 51s nu 36,757,696
> source ./gradient_benchmark.nu
╭───┬───────────────────╮
│ 0 │ 802ms 379us 41ns  │
│ 1 │ 793ms 244us 41ns  │
│ 2 │ 783ms 319us 83ns  │
│ 3 │ 411ms 555us 416ns │
│ 4 │ 676ms 195us 41ns  │
│ 5 │ 678ms 482us 208ns │
│ 6 │ 160ms 603us 916ns │
╰───┴───────────────────╯

without opt-level = "s"
cargo b --features=extra --release
2m 08s nu 36,027,296
> source ./gradient_benchmark.nu
╭───┬───────────────────╮
│ 0 │ 779ms 224us 875ns │
│ 1 │ 756ms 135us 875ns │
│ 2 │ 757ms 912us 833ns │
│ 3 │ 396ms 859us 958ns │
│ 4 │ 644ms 590us 41ns  │
│ 5 │ 649ms 335us 125ns │
│ 6 │ 164ms 20us        │
╰───┴───────────────────╯
```

**Comment by jntrnr** [comment]
This doesn't seem to do much improvement.

For where Nushell is currently, developer time is more important than small amounts of performance. As it matures, we may start looking into ways to get small speed improvements, but right now making sure we can develop it more quickly is more important.

**Comment by FilipAndersson245** [comment]
Could we instead change the release script to utilize improved optimization, without changing the buildtimes when doing local builds?

**Comment by fdncred** [comment]
If we had a real-world use case that demonstrated it was slow and that optimizing it via this setting would make it more than a few milliseconds faster, then I'd be in favor of changing it. I'm not sure I would otherwise.
