### ISSUE TITLE
Ability to iterate over record pairs, or ability access key/value of pair

### ISSUE THREAD

**Issue by AadamZ5** [nushell/nushell#5079]
### Related problem

I love this project! One of the tasks I was trying to perform in nushell was to filter through some dependencies in my (JS project) `package.json` and remove them. 

I started with this:

```
open ./package.json | get dependencies
```

which gives me a record of all the dependency names as keys, and the version strings as values.

I want to somehow filter through all of the key/value pairs, and find the packages that match a certain string. However, I can't figure out how to generically access the key (or value, but I'm not concerned about that here) when iterating over the record. Honestly, I'm not even sure if I'm iterating over the record. 

I was hoping something like this would work:
```
open ./package.json | get dependencies | each { |$x| echo $x.0 } 
```
but the `Record` type "doesn't support cell paths"

How can I access the key or value individually, without knowing the key name ahead of time? Perhaps there's some way to convert the record to a table?

### Describe the solution you'd like

I'd like some way to iterate over the record generically. It would be great to be able to access the key name without knowing the name ahead of time.

### Describe alternatives you've considered

I could (maybe?) send this to a string, then parse up the string, but I was really hoping to avoid doing that. It seems like the philosophy of Nushell is to enable strong data access without needing lots of string parsing and filtering from the user.

### Additional context and details

In Javascript for example, I can do:

```javascript

// Where object is my entire "dependencies" object, with keys as package names, and values as the versions of each package

for (const key in object) {
  //If I need the value
  const value = object[key]
}
```

How can I achieve something similar in Nushell?

**Comment by fdncred** [comment]
you could try something like this as an example `open ./package.json | get dependencies | transpose key value | each { |x| $"key-($x.key) value-($x.value)"}` - the secret sauce is the `transpose key value`.

**Comment by AadamZ5** [comment]
> you could try something like this as an example `open ./package.json | get dependencies | transpose key value | each { |x| $"key-($x.key) value-($x.value)"}` - the secret sauce is the `transpose key value`.

That works wonderfully! I had a hard time figuring out how to work with Records in this way. Any interest in updating the docs with an example like this? I can offer a PR too, but I'm also having a difficult time finding the docs source to update 😅

**Comment by fdncred** [comment]
> Any interest in updating the docs ...

ya, sure. Please update the docs with whatever you think is a reasonable sample.

**Comment by AadamZ5** [comment]
Opened a PR at https://github.com/nushell/nushell.github.io/pull/370

Thanks :)
