### ISSUE TITLE
Can we configure to not draw the gridlines?

### ISSUE THREAD

**Issue by schittli** [nushell/nushell#508]
#### Thanks a lot for your work and this great shell!

nushell always draws gridlines which looks nice but is disturbing / does not improve our daily work because the columns usually are recognized very well without drawn lines.

Is there a way to configure nushell, so that it does not draw the grid and maybe just underlines the column headings? (No continuous horizontal line to separate the header from data)

Thanks a lot, kind regards,
Thomas

**Comment by jonathandturner** [comment]
Do you mean something like this?

https://github.com/nushell/nushell/pull/349#issuecomment-524690034

**Comment by schittli** [comment]
**Thanks a lot!,** I had searched for a similar issue but used the wrong terms :-(

The linked example is great, just the upmost horizontal line is unnecessary (we love to use every line on the screen with useful data :-)) 

I hope it's ok if I close this issue.
