### ISSUE TITLE
[Usability] source command should have option to watch folder for changes and new scripts

### ISSUE THREAD

**Issue by DejayRezme** [nushell/nushell#5082]
### Related problem

Lets say I will need 10 custom scripts to do stuff and make my life easier. During the time I work on those 10 scripts I will save each 100 times and try them out. Per design for each new testing I have to type "source foo.nu" before testing new version, which means at least tapping cursor up twice, return, tapping curser up twice, return, to test again. The new F5 "reload config" keybind makes this much easier but the biggest problem is not the 1000 times I will have to reload my scripts, it's that I will forget it sometimes. This makes using nushell more error prone and will lead to confusion, frustration or in the worst case even data loss.

### Describe the solution you'd like

Ideally I'd like to do what I do in powershell: Have a script folder in the path dir and any time I want to add or change a script I just can make or edit a .ps1 file there and immediately call it without worrying.

A way to do this with nushell might be to expand the source command to be used in the config.nu:

`source -w, --watch`
--watch option will register some OS magic to notify nushell if the sourced file modified date has changed. Alternatively some kind of sleep timer

`source -w myFolder\`
This will source and watch all *.nu files in the directory as well as new files being added.

### Describe alternatives you've considered

Alternatively the scanning for changes is only done the moment you are about the execute a new shell command by pressing return in the shell.

Or you could have a mechanism that if you call a command that is unknown, a file with that command's name is searched in $env.Path.

Creating an executable nu script with a shebang I guess kinda solves this problem, but not really either because this basically executes "nu foo.nu". Which means it is much slower than calling a command. Powershell executes script files in it's own context. The nu executable filesize has gone down dramatically but it's still not a good solution for a shell imho.

### Additional context and details

Sorry if this has already been discussed and decided. 

nushell is really awesome and I really want to start using it, but extensibility is so fundamental and there it is unfortunately lacking. 
Having to register and add your script file to a special config file is not good, but having to manually reload it every time you edit it is worse. In my opinion this is a severe usability bug. 

In any case I would also suggest adding a section in the manual / book about how the workflow for developing custom scripts / commands should look like.

**Comment by fdncred** [comment]
I know how this could work in windows but not in linux or macOS. I'm just not as familiar with *nix for watching. This would make debugging while writing scripts easier. I'd also think this would need to be spawned in a background thread as well. It's not supported right now but it would be a cool feature.

**Comment by DejayRezme** [comment]
A background thread isn't great. But it would solve the problem and would "contain" the solution in either "source" or some other internal command ("source-watch"?). So it doesn't create sprawl in the whole engine. Although the sourcing of modified or new scripts should probably only happen while the shell isn't busy executing stuff.

And it would be optional. You could also have two script directories, one for developing that is watched and one for deployment that isn't watched.

**Comment by rgwood** [comment]
This would be really useful. I wonder if it should be more general than scripts; maybe it could run arbitrary Nu blocks (and those blocks could run a script if needed)? Here's a sketch of what I'm thinking:

```
> help watch-files
Watch for file changes and execute Nu code in response to changes

Usage:
  > watch-files <pattern> <block>

Flags:
  -d, --debounce-ms
      How long to debounce changes, in milliseconds (default: 0)

Parameters:
  pattern: a glob pattern identifying files to watch
  block: A Nu block to run whenever a file changes. The changed file's path can be accessed as $path

Examples:
  Run cargo test whenever a Rust file changes
  >  watch-files **/*.rs { cargo test }

  Log all changes in a child directory
  >  watch-files some_dir/* { $path | save --append file_changes.log }
```

**Comment by hustcer** [comment]
Maybe we can use https://github.com/watchexec/watchexec ?

**Comment by rgwood** [comment]
@hustcer I like Watchexec a lot, but I've been having some troubles using it with Nushell. I can't get Watchexec to execute Nu pipelines that contain more than 1 word, for example:

```
> watchexec -- nu -c "open foo.txt"
Usage:
  > open {flags} (filename) 

Flags:
...
```

I'm not sure whether that's a Watchexec bug, a Nu bug, or user error. Have you successfully used Watchexec to run Nu commands?

**Comment by hustcer** [comment]
@fdncred Sorry, I don't use it much, just know it might help 😅

**Comment by DejayRezme** [comment]
@rgwood that sounds like a good idea. You could turn it on for a session or put it in your config.nu and it sources / re-sources *.nu files in specified directories as they appear or are modified.

I'm not sure but I suspect you do need some internal support in nu for this right? There is no way you could have an external command like watchexec make already running nu shells source a file, right?

Hmm I guess you could find some really hacky way to send some input to the terminal or input stream or something haha.

**Comment by rgwood** [comment]
FWIW I got Watchexec to work from inside Nu:
```
watchexec --shell=nu -- `echo "hello"`
```

That launches a new Nu instance to run `echo`, but it might still be useful in some situations. I'm going to keep looking into creating a command that runs code inside the current Nu instance.

**Comment by DejayRezme** [comment]
Well if you could send a keycode for like Ctrl-W for reloading the config to the console, this could be a way. But I could imagine sending keycodes to terminals might be a bit suspicious and might be forbidden? 

You could have a 'watchsources.nu' in your script folder that launches watchexec and sources the files. And maybe even modifies itself to add discovered files. Then when config gets reloaded, the wachsources.nu and referenced scripts get reloaded too.

**Comment by rgwood** [comment]
I believe this can be closed now that we have [a general `watch` command](https://www.nushell.sh/book/commands/watch.html#frontmatter-title-for-filesystem).
