### ISSUE TITLE
Nushell 0.60 no longer correctly clears scrollback with Ctrl/Cmd + K

### ISSUE THREAD

**Issue by sinhpham** [nushell/nushell#5089]
### Describe the bug

In iTerm2/VSCode embedded terminal I used to be able to clears the scrollback using Ctrl/Cmd + K. Now with 0.60 after clearing the scrollback, typing new a new command would make the prompt jump back to where it was before.

### How to reproduce

1. Start nushell 0.60 in iTerm2/vscode embedded terminal/MacOS default terminal
2. Run any command, `version` is a good example
3. Press `Cmd + K`
4. Type `version` again
5. `version` appears somewhere in the middle, before clearing.

### Expected behavior

The command after `Cmd + K` should appear at the top of the terminal

**Comment by fdncred** [comment]
I'm not sure what `Ctrl/Cmd + K` should do but I use this to do something similar as a work-around.
```python
# Full term reset, cls, clear buffer, attributes off,
def clsterm [] {
  $"(ansi esc)c(ansi clsb)(ansi cls)(ansi reset)(ansi home)"
}
```

**Comment by stormasm** [comment]
I believe you are referring to this issue which is closed....

https://github.com/nushell/reedline/issues/196

the above solution with **clsterm** works great and I have been using it for months now and I am happy with it...

another sequence which is close to the above one is...

```rust
alias cls = $"(ansi cls)(ansi clsb)(ansi reset)(ansi home)"
```

**Comment by sinhpham** [comment]
Oh yes that's the same issue, thanks @fdncred @stormasm.

It would be great if nushell can support this out of the box though, either by supporting `Ctrl/Cmd + K` or have `cls/clsterm` built-in.

Not sure if we want to close this issue, or turn it to a feature request. I'll let you guys decide.

**Comment by stormasm** [comment]
@sinhpham having cls/clsterm built-in is an interesting idea / concept....

I know it would be helpful for everyone who needs it !  Like me :)

Right now everyone who needs it --- needs to do what I do --- 
which is throw it their config.nu

We will see what other folks think...

**Comment by seeker-3** [comment]
I just installed new shell to try it out. I hit the same issue. I use (CMD + K) instead of typing clear all the time since it's faster.

It clears the text, but when you start typing again, it immediately jumps back down to where the cursor was cleared from.

**Comment by fdncred** [comment]
> It clears the text, but when you start typing again, it immediately jumps back down to where the cursor was cleared from.

@jntrnr is this related to what you were trying to fix today with the resizing stuff changing the prompt? or is this entirely separate?

**Comment by appetrosyan** [comment]
OK, so we have a workaround. It'd be nice if we could also use the expected thing to get the expected outcome

**Comment by stormasm** [comment]
@fdncred works fine for me on the mac...
And I am sure you are testing on windows...
I think we can go ahead and close this issue...
curious to know if it works fine on linux as well....

**Comment by seeker-3** [comment]
Yup, works for me now. I'm on Mac

**Comment by stormasm** [comment]
If someone could test on linux that would be great ! 😄 
Thank you....

**Comment by fdncred** [comment]
I was on mac when I reported earlier. On Windows I do `ctrl-L` (not capital L, i just wrote it that way for legibility). I don't know if the keybindings are different on windows or if i just have it mapped differently.

**Comment by sinhpham** [comment]
Working for me now on mac + wezterm. I'll leave the issue open for others to confirm on Linux/Windows.

**Comment by sholderbach** [comment]
Cmd-K is a mac specific behavior, that the terminal emulator itself performs the clearing, the Ctrl-L behavior is implemented by the shell/line editor.

Great that this is resolved

**Comment by fariss** [comment]
Got this issue in Kitty, solved it using:
```
map cmd+k combine : clear_terminal scrollback active : send_text normal,application \x0c
```
