### ISSUE TITLE
Add search terms to commands

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#5093]
### Related problem

In [this PR](https://github.com/nushell/nushell/pull/4980), we introduced "search terms": Words that help you search for commands (check `help commands`). Currently, only `prepend`, `append` and `reduce` have the search terms.

### Describe the solution you'd like

Let's populate them! We could make a collective effort of adding relevant search terms to commands. 

### Describe alternatives you've considered

Instead of making a huge PR adding a ton, I would recommend making smaller PRs covering some logical groups of commands so we can discuss it effectively.

### Additional context and details

EDIT: If you see some existing search terms that feel redundant or inaccurate, feel free to change or remove them.

EDIT: Just to document which commands still need search terms we've created this list. (Last updated 2023-09-12 by @sholderbach)

<details>
<summary>Command to generate list</summary>

```
scope commands | 
  filter { |cmd| ($cmd.search_terms | str length) == 0 } | 
  each { |cmd| $"- [ ] `($cmd.name)` in category ($cmd.category)"} | 
  str join (char nl)
```

</details>

- [ ] `ansi gradient` in category platform
- [ ] `ansi link` in category platform
- [ ] `ansi strip` in category platform
- [ ] `ast` in category debug
- [ ] `banner` in category default
- [ ] `bits` in category bits
- [ ] `break` in category core
- [ ] `bytes` in category bytes
- [ ] `cal` in category generators
- [ ] `clear` in category platform
- [ ] `collect` in category filters
- [ ] `columns` in category filters
- [ ] `compact` in category filters
- [ ] `complete` in category system
- [ ] `config env` in category env
- [ ] `config nu` in category env
- [ ] `config reset` in category env
- [ ] `continue` in category core
- [ ] `create_left_prompt` in category default
- [ ] `create_right_prompt` in category default
- [ ] `date format` in category removed
- [ ] `debug` in category debug
- [ ] `decode base64` in category hash
- [ ] `decode hex` in category formats
- [ ] `def` in category core
- [ ] `def-env` in category core
- [ ] `default` in category filters
- [ ] `dfr agg` in category lazyframe
- [ ] `dfr agg-groups` in category expression
- [ ] `dfr all-false` in category dataframe
- [ ] `dfr all-true` in category dataframe
- [ ] `dfr append` in category dataframe
- [ ] `dfr as-date` in category dataframe
- [ ] `dfr as-datetime` in category dataframe
- [ ] `dfr cache` in category lazyframe
- [ ] `dfr collect` in category lazyframe
- [ ] `dfr columns` in category dataframe
- [ ] `dfr concatenate` in category dataframe
- [ ] `dfr contains` in category dataframe
- [ ] `dfr count` in category expression
- [ ] `dfr count-null` in category dataframe
- [ ] `dfr cumulative` in category dataframe
- [ ] `dfr drop` in category dataframe
- [ ] `dfr drop-duplicates` in category dataframe
- [ ] `dfr drop-nulls` in category dataframe
- [ ] `dfr dtypes` in category dataframe
- [ ] `dfr dummies` in category dataframe
- [ ] `dfr explode` in category lazyframe
- [ ] `dfr expr-not` in category expression
- [ ] `dfr fetch` in category lazyframe
- [ ] `dfr fill-nan` in category lazyframe
- [ ] `dfr fill-null` in category lazyframe
- [ ] `dfr filter` in category lazyframe
- [ ] `dfr filter-with` in category dataframe or lazyframe
- [ ] `dfr first` in category dataframe
- [ ] `dfr flatten` in category lazyframe
- [ ] `dfr get` in category dataframe
- [ ] `dfr get-day` in category dataframe
- [ ] `dfr get-hour` in category dataframe
- [ ] `dfr get-minute` in category dataframe
- [ ] `dfr get-month` in category dataframe
- [ ] `dfr get-nanosecond` in category dataframe
- [ ] `dfr get-ordinal` in category dataframe
- [ ] `dfr get-second` in category dataframe
- [ ] `dfr get-week` in category dataframe
- [ ] `dfr get-weekday` in category dataframe
- [ ] `dfr get-year` in category dataframe
- [ ] `dfr group-by` in category lazyframe
- [ ] `dfr implode` in category expression
- [ ] `dfr into-df` in category dataframe
- [ ] `dfr into-lazy` in category lazyframe
- [ ] `dfr into-nu` in category dataframe
- [ ] `dfr is-duplicated` in category dataframe
- [ ] `dfr is-not-null` in category dataframe
- [ ] `dfr is-null` in category dataframe
- [ ] `dfr is-unique` in category dataframe
- [ ] `dfr join` in category lazyframe
- [ ] `dfr last` in category dataframe
- [ ] `dfr lowercase` in category dataframe
- [ ] `dfr ls` in category dataframe
- [ ] `dfr max` in category expression
- [ ] `dfr mean` in category expression
- [ ] `dfr median` in category lazyframe
- [ ] `dfr melt` in category dataframe
- [ ] `dfr min` in category expression
- [ ] `dfr n-unique` in category dataframe
- [ ] `dfr not` in category dataframe
- [ ] `dfr open` in category dataframe
- [ ] `dfr quantile` in category lazyframe
- [ ] `dfr rename` in category dataframe or lazyframe
- [ ] `dfr replace` in category dataframe
- [ ] `dfr replace-all` in category dataframe
- [ ] `dfr reverse` in category lazyframe
- [ ] `dfr rolling` in category dataframe
- [ ] `dfr sample` in category dataframe
- [ ] `dfr select` in category lazyframe
- [ ] `dfr set` in category dataframe
- [ ] `dfr set-with-idx` in category dataframe
- [ ] `dfr shape` in category dataframe
- [ ] `dfr shift` in category dataframe or lazyframe
- [ ] `dfr slice` in category dataframe
- [ ] `dfr sort-by` in category lazyframe
- [ ] `dfr std` in category expression
- [ ] `dfr str-lengths` in category dataframe
- [ ] `dfr str-slice` in category dataframe
- [ ] `dfr strftime` in category dataframe
- [ ] `dfr sum` in category expression
- [ ] `dfr summary` in category dataframe
- [ ] `dfr take` in category dataframe
- [ ] `dfr to-arrow` in category dataframe
- [ ] `dfr to-avro` in category dataframe
- [ ] `dfr to-csv` in category dataframe
- [ ] `dfr to-jsonl` in category dataframe
- [ ] `dfr to-parquet` in category dataframe
- [ ] `dfr unique` in category dataframe or lazyframe
- [ ] `dfr value-counts` in category dataframe
- [ ] `dfr var` in category expression
- [ ] `dfr with-column` in category dataframe or lazyframe
- [ ] `do` in category core
- [ ] `du` in category core
- [ ] `echo` in category core
- [ ] `encode base64` in category hash
- [ ] `encode hex` in category formats
- [ ] `every` in category filters
- [ ] `exec` in category system
- [ ] `explain` in category debug
- [ ] `explore` in category viewers
- [ ] `export module` in category core
- [ ] `export-env` in category env
- [ ] `extern` in category core
- [ ] `extern-wrapped` in category core
- [ ] `first` in category filters
- [ ] `flatten` in category filters
- [ ] `for` in category core
- [ ] `format` in category strings
- [ ] `from` in category formats
- [ ] `from csv` in category formats
- [ ] `from json` in category formats
- [ ] `from nuon` in category formats
- [ ] `from ods` in category formats
- [ ] `from ssv` in category formats
- [ ] `from toml` in category formats
- [ ] `from tsv` in category formats
- [ ] `from url` in category formats
- [ ] `from xlsx` in category formats
- [ ] `from xml` in category formats
- [ ] `from yaml` in category formats
- [ ] `from yml` in category formats
- [ ] `get` in category filters
- [ ] `grid` in category viewers
- [ ] `group` in category filters
- [ ] `group-by` in category filters
- [ ] `hash` in category hash
- [ ] `hash md5` in category hash
- [ ] `hash sha256` in category hash
- [ ] `headers` in category filters
- [ ] `help` in category core
- [ ] `help aliases` in category core
- [ ] `help commands` in category core
- [ ] `help externs` in category core
- [ ] `help modules` in category core
- [ ] `help operators` in category core
- [ ] `hide` in category core
- [ ] `hide-env` in category core
- [ ] `histogram` in category chart
- [ ] `history` in category misc
- [ ] `history session` in category misc
- [ ] `if` in category core
- [ ] `inspect` in category debug
- [ ] `into` in category conversions
- [ ] `is-empty` in category filters
- [ ] `items` in category filters
- [ ] `keybindings default` in category platform
- [ ] `keybindings list` in category platform
- [ ] `keybindings listen` in category platform
- [ ] `last` in category filters
- [ ] `let-env` in category removed
- [ ] `lines` in category filters
- [ ] `load-env` in category filesystem
- [ ] `loop` in category core
- [ ] `match` in category core
- [ ] `math` in category math
- [ ] `merge` in category filters
- [ ] `metadata` in category debug
- [ ] `module` in category core
- [ ] `move` in category filters
- [ ] `overlay` in category core
- [ ] `overlay hide` in category core
- [ ] `overlay list` in category core
- [ ] `overlay new` in category core
- [ ] `overlay use` in category core
- [ ] `par-each` in category filters
- [ ] `path` in category path
- [ ] `path basename` in category path
- [ ] `path dirname` in category path
- [ ] `path exists` in category path
- [ ] `path expand` in category path
- [ ] `path join` in category path
- [ ] `path parse` in category path
- [ ] `path relative-to` in category path
- [ ] `path split` in category path
- [ ] `path type` in category path
- [ ] `profile` in category debug
- [ ] `pwd` in category default
- [ ] `register` in category core
- [ ] `rename` in category filters
- [ ] `return` in category core
- [ ] `rotate` in category filters
- [ ] `run-external` in category system
- [ ] `scope` in category core
- [ ] `scope aliases` in category filters
- [ ] `scope commands` in category filters
- [ ] `scope engine-stats` in category filters
- [ ] `scope externs` in category filters
- [ ] `scope modules` in category filters
- [ ] `scope variables` in category filters
- [ ] `seq` in category generators
- [ ] `seq char` in category generators
- [ ] `seq date` in category generators
- [ ] `shuffle` in category filters
- [ ] `sort` in category filters
- [ ] `sort-by` in category filters
- [ ] `source` in category core
- [ ] `source-env` in category core
- [ ] `split` in category strings
- [ ] `split-by` in category filters
- [ ] `str` in category strings
- [ ] `str expand` in category strings
- [ ] `sys` in category system
- [ ] `take until` in category filters
- [ ] `take while` in category filters
- [ ] `term size` in category platform
- [ ] `to` in category formats
- [ ] `to csv` in category formats
- [ ] `to html` in category formats
- [ ] `to json` in category formats
- [ ] `to md` in category formats
- [ ] `to nuon` in category formats
- [ ] `to text` in category formats
- [ ] `to toml` in category formats
- [ ] `to tsv` in category formats
- [ ] `to xml` in category formats
- [ ] `to yaml` in category formats
- [ ] `try` in category core
- [ ] `update` in category filters
- [ ] `update cells` in category filters
- [ ] `values` in category filters
- [ ] `version` in category core
- [ ] `view` in category debug
- [ ] `view files` in category debug
- [ ] `view source` in category debug
- [ ] `view span` in category debug
- [ ] `window` in category filters
- [ ] `with-env` in category env
- [ ] `wrap` in category filters
- [ ] `zip` in category filters

**Comment by hustcer** [comment]
To filter out the commands without a search_terms:
```nu
help commands | where is_custom == false | where {|it| ($it.search_terms | str trim | empty?) == true }
```

**Comment by zephaniahong** [comment]
@kubouch Hi!
I'm trying to do up the search terms for the git commands but I realised that the files for those don't exist? Could I get some advice as to how to approach it?

Thank you!

**Comment by kubouch** [comment]
Git commands are custom signatures defined in the default config, you can't have search terms for these at the moment.

**Comment by NotTheDr01ds** [comment]
Just came across this when searching for something else.  It seems to me that it has lived a useful life, but can probably be closed now since (a) most or all commands have search terms, (b) the feature is well-known enough that search terms are commonly added regularly, (c) otherwise, it seems like a "lives forever" issue, and who wants to live forever (sorry, random Queen/Highlander reference).

**Comment by fdncred** [comment]
Love Highlander and Queen! Thanks!
