### ISSUE TITLE
[Performance] Optimize `external_exception` detection

### ISSUE THREAD

**Issue by sholderbach** [nushell/nushell#5106]
To provide a seamless experience with the completions and parsing we have to do some checks to see what external commands exist (that may also start with numbers e.g. `7z`) 

The current implementation of that check seems to do a bunch of filesystem lookups:

https://github.com/nushell/nushell/blob/3ceb39c82c487f795c056ebc66af5c9445a1571f/crates/nu-cli/src/util.rs#L355-L419

In doing so it creates a significant portion of the temporary allocations:

![image](https://user-images.githubusercontent.com/15833959/161980066-cef9b079-7174-4b66-95eb-6f0bd9348e5f.png)

This also leads to a significant time of the execution being spent there:

![image](https://user-images.githubusercontent.com/15833959/161980986-75db8d9c-ac23-4244-9af5-28ae7d3cdbdd.png)

This may be a worthy target for optimization. Maybe the allocations can be avoided or aggressive caching can be performed to avoid the performance impact

**Comment by herlon214** [comment]
I would say that this performance issue also has something to do with the way we're doing the completions right now. Every time the user types a character all those fetch calls will be executed again. The chances are very low that in the meantime between user typing two characters the fetch result will change

**Comment by sholderbach** [comment]
Yeah, maybe trying to just reuse the values within one repl loop might be enough to make that not noticeable.

**Comment by fdncred** [comment]
imo, what needs to happen is that this `external_exceptions` function needs to run at startup and only when the path is modified and not on every command or prompt. I think the hard part may be that we don't necessarily know when the path env var is modified.

**Comment by sholderbach** [comment]
Is it actually needed to have a full list of externals available? Would it suffice to do targeted lookups on triggering a completion with a certain character/ having an expression with an unknown and then add them to a BTreeSet or similar?

**Comment by fdncred** [comment]
I'm not following, this isn't only about completions. It's about finding these things like `7z` that look like maths.

**Comment by fdncred** [comment]
> Could it work to have a list of known externals that nushell has seen before?

I'm kind of wondering if it would be better to make a config point that says these are known external_exceptions like:
```
external_exceptions = [ "7z", "7z.exe" ]
```
and then we just use that list.

**Comment by jntrnr** [comment]
@sholderbach - does https://github.com/nushell/nushell/pull/5115 help?
