### ISSUE TITLE
nushell freezes with weird ls command

### ISSUE THREAD

**Issue by DejayRezme** [nushell/nushell#5112]
### Describe the bug

I was messing around and typed this weird construct in, nushell started to print newlines and control-c would not stop the execution either

### How to reproduce

let bigfiles = (ls | where size > 2kb) 
ls (2 * $bigfiles.0.size)

### Expected behavior

It should output "can't convert filesize to string"

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.0                                   |
| short_commit       | 74af31a4                                 |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315 |
| commit_date        | 2022-03-22 19:07:11 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.60.0                                   |
| build_time         | 2022-03-22 19:26:49 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by herlon214** [comment]
Is there any specific reason for using `ls` and not `echo`?

**Comment by DejayRezme** [comment]
> Is there any specific reason for using `ls` and not `echo`?

No there is no reason why anyone would do this. At least no sane reason :) But it shouldn't crash and probably points to some weird bug in nushell

**Comment by DejayRezme** [comment]
This seems fixed in 0.61. 
Did someone fix something or is it just no longer reproducible?
