### ISSUE TITLE
clip needs help and should print or output it's input

### ISSUE THREAD

**Issue by DejayRezme** [nushell/nushell#5113]
### Related problem

`help clip` returns "command not found". Typing in clip alone also outputs "INFO: Type "CLIP /?" for usage." - which looks different than other commands.

I'd also suggest that clip always prints or outputs it's input as other pipeline filters. Or that there be a -p option. For example the following should output the 

`version | transpose key value | to md --pretty | clip`

### Describe the solution you'd like

`help clip` should work.

ls | clip should either print it's input or output it's input, and do so either by default or optional parameter --print. Or maybe have an optional parameter for --quiet if you don't want it to print.

### Additional context and details

#3694

**Comment by fdncred** [comment]
clip is not an internal nushell command so it wouldn't have nushell help.

**Comment by DejayRezme** [comment]
Oh sorry, didn't realize it's a dos command!
Should clip be an internal command ?

**Comment by fdncred** [comment]
no worries. clip may be a helpful command but it would need to be cross platform if we had one.

**Comment by jmoore34** [comment]
IIRC it existed in 0.44 but wasn't ported

**Comment by fdncred** [comment]
> IIRC it existed in 0.44 but wasn't ported

I checked and don't see it on Mac. I still have v0.44 named nu44 and run it from time to time for comparison.

**Comment by jmoore34** [comment]
Huh, maybe it was before engine-p and not ported. [Link for reference](https://github.com/nushell/nushell/blob/e4c6336bd41f785f6b9a2200fb58f32796eb4380/crates/nu-cli/src/commands/clip.rs)

**Comment by fdncred** [comment]
ya, it must of got removed at some point because i can't use it in nu44. weird. it may be good to add one though.
