### ISSUE TITLE
Completions sometimes crashing

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#5127]
### Describe the bug

I'm still working on finding a reliable repro for this, but I'm seeing completions sometimes crashing with the latest main.

Here's one example:
```
> cd ../thirdparty/thread 'main' panicked at 'assertion failed: self.is_char_boundary(idx)', /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/string.rs:1446:9
```
I started typing, hit <tab> and boom. I suspect something we're calculating is using the wrong kinds of offsets.

### How to reproduce

See above

### Expected behavior

This shouldn't crash

### Additional context

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.1                                   |
| branch             | main                                     |
| tag                |                                          |
| short_commit       | e86c1b11                                 |
| commit_hash        | e86c1b118ecef3d548b714881ef0380c5ee249f0 |
| commit_date        | 2022-04-07 19:36:16 +00:00               |
| build_os           | macos-aarch64                            |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-aarch64-apple-darwin              |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01)      |
| pkg_version        | 0.60.1                                   |
| build_time         | 2022-04-08 07:43:24 +12:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | gstat                                    |

**Comment by jntrnr** [comment]
Here's the repro I just tried:

```
> cd ../thirdparty/r<tab>
```

I don't have any folders that start with `r`, so it deleted it back to `cd ../thirdparty/` this is a little odd but okay. Next, I hit `<tab>` again. Then, it panicked:

Backtrace:
```
/Users/jt/Source/nushell〉cd ../thirdparty/thread 'main' panicked at 'assertion failed: self.is_char_boundary(idx)', /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/string.rs:1446:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5
   3: alloc::string::String::insert
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/string.rs:1446:9
   4: nu_cli::completions::completer::NuCompleter::completion_helper
             at ./crates/nu-cli/src/completions/completer.rs:97:9
   5: <nu_cli::completions::completer::NuCompleter as reedline::completion::base::Completer>::complete
             at ./crates/nu-cli/src/completions/completer.rs:213:9
   6: <reedline::menu::columnar_menu::ColumnarMenu as reedline::menu::Menu>::update_values
             at /Users/jt/.cargo/git/checkouts/reedline-e42026a78d91c510/6332747/src/menu/columnar_menu.rs:523:17
   7: reedline::menu::ReedlineMenu::update_values
             at /Users/jt/.cargo/git/checkouts/reedline-e42026a78d91c510/6332747/src/menu/mod.rs:186:44
   8: reedline::engine::Reedline::handle_editor_event
             at /Users/jt/.cargo/git/checkouts/reedline-e42026a78d91c510/6332747/src/engine.rs:583:29
   9: reedline::engine::Reedline::handle_editor_event
             at /Users/jt/.cargo/git/checkouts/reedline-e42026a78d91c510/6332747/src/engine.rs:854:27
  10: reedline::engine::Reedline::handle_event
             at /Users/jt/.cargo/git/checkouts/reedline-e42026a78d91c510/6332747/src/engine.rs:474:13
  11: reedline::engine::Reedline::read_line_helper
             at /Users/jt/.cargo/git/checkouts/reedline-e42026a78d91c510/6332747/src/engine.rs:451:23
  12: reedline::engine::Reedline::read_line
             at /Users/jt/.cargo/git/checkouts/reedline-e42026a78d91c510/6332747/src/engine.rs:353:22
  13: nu_cli::repl::evaluate_repl
             at ./crates/nu-cli/src/repl.rs:265:21
  14: nu::main
             at ./src/main.rs:262:21
  15: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
```

**Comment by sholderbach** [comment]
I think that's our friend Unicode
