### ISSUE TITLE
`..branchname` in `git log ..branchname` is expanded by nushell

### ISSUE THREAD

**Issue by devurandom** [nushell/nushell#5131]
### Describe the bug

Double dots (`..`) in arguments to external commands appear to be expanded by nushell:
```
❯ git log ..staging
fatal: ambiguous argument '[REDACTED ABSOLUTE PATH]/..staging': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Also quoting `..staging` (`git log "..staging"` or `git log '..staging'`) does not help: The error returned by `git` is exactly the same. Escaping the dots (`..staging` -> `\.\.staging`) makes nushell no longer expand them, but also passes them literally to `git`, which then cannot find the path. This is the same when quoting the argument (`'..staging'` -> `'\.\.staging'`, `"..staging"` -> `"\.\.staging"`).

### How to reproduce

1. Try to run `git log ..staging`
2. Observe an error printed by `git`

### Expected behavior

I would expect nushell to not expand arguments that are not valid paths. In fact as a bash and fish user, it comes unexpected that it expands regular paths at all, i.e. paths that do not contain `*` or `~`. At the very least I would expect there to be an obvious way to prevent this expansion and pass an argument literally, as I wrote it, to the command.

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.60.0                                |
| build_os           | linux-x86_64                          |
| rust_version       | rustc 1.59.0 (gentoo)                 |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.60.0                                |
| build_time         | 2022-03-25 19:35:23 +01:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

### Additional context

See-also: https://github.com/nushell/nushell/issues/4205

**Comment by strega-nil** [comment]
I did a bisection; it looks like one of:

```
41dbc641ccdd34ed05076b389d0d181b66baabbf
b4c72e85e12f7a80ccc3d30164d53533f53ce901
```

is the bad commit.

**Comment by jntrnr** [comment]
That looks like the engine-q PR. It changed a bunch of things, so we'd probably be better off trying to code before it landed and looking for parser differences that need to get ported into the new parser

**Comment by strega-nil** [comment]
@jntrnr it looks like it's just that it switched from `expand_path` to `expand_path_with`, and the check wasn't correct - it needs to check for `arg.starts_with("~/")` or something like that.
