### ISSUE TITLE
Terminal.app "Automatically Mark Prompt Lines" is broken when starship is enabled in nushell

### ISSUE THREAD

**Issue by toffaletti** [nushell/nushell#5138]
### Describe the bug

Terminal.app Has a feature to "mark" prompt lines so command+up/down arrow jump to the previous or next prompt. Marks are denoted by a `[` on the left side of the terminal. This feature normally works with nushell, but when starship is installed as the prompt in nushell this functionality is broken and no marks are created for prompt lines.

### How to reproduce

1. Install starship as the prompt for nushell following the instructions in the nushell docs OR starship's docs.
2. Open Terminal.app
3. hit enter a few times (notice marks are not being created, there is no `[` on the prompt line)
4. command+up arrow and input doesn't jump to previous prompt

### Expected behavior

I expect prompt lines to be marked. In the screenshot you can see this is working with `starship` and `fish` (first few prompt lines), but not `starship` and `nushell` (later prompt lines with no `[`)

### Screenshots

<img width="25" alt="Screen Shot 2022-04-08 at 3 12 08 PM" src="https://user-images.githubusercontent.com/145012/162539505-2abc1607-0bd6-46c8-bb3a-8fe24c5ee2ea.png">

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.60.0                                |
| build_os           | macos-aarch64                         |
| rust_version       | rustc 1.59.0                          |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.60.0                                |
| build_time         | 2022-03-22 19:07:11 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

**Comment by fdncred** [comment]
Can you point me to where this setting is at in terminal.app? I'm not familiar with it. We'd need to know how it works in order to duplicate the behavior. I'm not sure we can without knowing more.

**Comment by toffaletti** [comment]
Under Edit > Marks > Automatically Mark Prompt Lines

After some more experimentation: it works fine with default prompt, oh-my-posh prompt, but not with starship default prompt. I've not yet been able to figure out what starship is doing to break this feature and fish+starship works so its the combination of nushell+starship.

I'm not sure how Terminal.app works, but `kitty` docs have this to say:

https://sw.kovidgoyal.net/kitty/shell-integration/#notes-for-shell-developers

**Comment by sholderbach** [comment]
Interesting that it works with the basic prompt. We may want to send those marks with reedline by default, so implementers of custom prompts don't have to worry about them. One thing I'm curious about is how this will play out with repainting the prompt.

**Comment by fdncred** [comment]
I agree that such a thing should be exposed by reedline however it should be configurable because iTerm2 describes these as proprietary escape sequences, although many terminal emulators support them. I would just be worried that on an unsupported terminal emulator, we'd be outputting odd characters that couldn't be interpreted.

Having said that, I would like to have a function to send arbitrary ansi escape sequences from reedline to the terminal emulator. I can think of a few that I'd like to support, off the top of my head.

1. setting title sequences
2. terminal clear sequences
3. terminal clear buffer sequences
4. marking sequences as described in this issue

**Comment by sholderbach** [comment]
2. and 3. sound like good candidates for `ReedlineEvents` (i.e. probably more aptly named commands) for the keybindings. 1. as well but maybe more interesting separately while the evaluation phase of the repl is ongoing. 4. maybe make this configurable but automatic. 5. will have to read up on the API

**Comment by fdncred** [comment]
Sounds good @sholderbach. I just don't want to automatically emit things that break some people's terminals. We'd have to test though. If it works on the majority, we may just run with it and people can disable if they want to.

**Comment by schrieveslaach** [comment]
I was thinking about Kitty's shell integration in Nushell independently. So I came across this issue and linked a PR to it. Maybe, you guys could provide some guidance. External commands are not yet working.

BTW: you can integrate title sequences like this in your `config.nu`:

```nushell
let-env PROMPT_COMMAND = {
   echo [
      (ansi title) $env.USER '@' (hostname) (ansi st)
      (^/usr/bin/starship prompt --cmd-duration $env.CMD_DURATION_MS --status $env.LAST_EXIT_CODE)
   ] | str collect
}
```

I'm not sure if that should be documented or if that should be a feature of Nushell. Maybe in following form?

```
let-env TITLE_COMMAND = {
   echo [ env.$USER '@' (hostname) ] | str collect
}
```

**Comment by fdncred** [comment]
I think an env var for TITLE_COMMAND is a good idea, but personally, I wouldn't set it to user@host. But that's the nice thing about env vars, you can always change them.
