### ISSUE TITLE
Failing tests on Windows

### ISSUE THREAD

**Issue by boyvanduuren** [nushell/nushell#5142]
### Describe the bug

Three tests on Windows are failing:

```
---- tests::test_parser::let_env_expressions stdout ----
stdout:
stderr: Error: nu::shell::name_not_found (https://docs.rs/nu-protocol/0.60.1/nu-protocol/enum.ShellError.html#variant.DidYouMean)

   ╭─[C:\Users\boy\AppData\Local\Temp\.tmpYKsRXh:1:1]
 1 │ let-env PATH = if (env | any? name == VENV_OLD_PATH) { $env.VENV_OLD_PATH } else { $env.PATH }; echo done
   ·                                                                                         ──┬─
   ·                                                                                           ╰── did you mean 'Path'?
   ╰────


thread 'tests::test_parser::let_env_expressions' panicked at 'assertion failed: output.status.success()', src\tests.rs:43:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::test_parser::let_env_expressions
```

```
---- shell::pipeline::commands::external::correctly_escape_external_arguments stdout ----
=== stderr

thread 'shell::pipeline::commands::external::correctly_escape_external_arguments' panicked at 'assertion failed: `(left == right)`
  left: `"'$0'"`,
 right: `"$0"`', tests\shell\pipeline\commands\external.rs:71:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    shell::pipeline::commands::external::correctly_escape_external_arguments
```

```
---- shell::pipeline::commands::external::execute_binary_in_string stdout ----
=== stderr

thread 'shell::pipeline::commands::external::execute_binary_in_string' panicked at 'assertion failed: `(left == right)`
  left: `"\\\"$0\\\""`,
 right: `"$0"`', tests\shell\pipeline\commands\external.rs:83:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    shell::pipeline::commands::external::execute_binary_in_string
```

### How to reproduce

Run the tests on Windows.

### Expected behavior

Tests to pass.

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.60.1                                      |
| branch             | main                                        |
| tag                |                                             |
| short_commit       | 14066ccc                                    |
| commit_hash        | 14066ccc304f8f856751bd027d789e7a36d0f5b6    |
| commit_date        | 2022-04-09 05:17:48 +00:00                  |
| build_os           | windows-x86_64                              |
| rust_version       | rustc 1.62.0-nightly (f4a7ce997 2022-04-08) |
| cargo_version      | cargo 1.62.0-nightly (e2e2dddeb 2022-04-05) |
| pkg_version        | 0.60.1                                      |
| build_time         | 2022-04-09 10:43:01 +02:00                  |
| build_rust_channel | debug                                       |
| features           | default, trash, which, zip                  |
| installed_plugins  |                                             |

**Comment by fdncred** [comment]
In windows depending on how you run nushell i.e. cmd.exe, windows_terminal, conemu, powershell, posh, etc. the path environment variable can sometimes be `$env.PATH` or `$env.Path`.
