### ISSUE TITLE
source command is unable to handle subexpression

### ISSUE THREAD

**Issue by JanDeDobbeleer** [nushell/nushell#5146]
### Describe the bug

I have a command that outputs a string. The string is a path to a valid nu shell script. When using a subexpression to get the script location as a result, it seems to want to evaluate the expression rather than the output of the expression.

EDIT: it seems `source` also can't handle variables. If that's by design it's rather strange. Here's to hoping it's a missing feature🤞🏻

### How to reproduce

```
source (echo "valid_script.nu")
```

### Expected behavior

It sources the script as it would evaluate to `source "valid_script.nu"`

### Screenshots

<img width="867" alt="image" src="https://user-images.githubusercontent.com/2492783/162630959-24a0ba00-fec3-4fa3-bedd-0247f55d9704.png">

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.60.0                                |
| build_os           | macos-x86_64                          |
| rust_version       | rustc 1.59.0                          |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.60.0                                |
| build_time         | 2022-03-22 19:07:11 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

**Comment by jntrnr** [comment]
This is currently by design. There's a section in the book that talks about it: https://www.nushell.sh/book/thinking_in_nushell.html#parsing-and-evaluation-are-different-stages

**Comment by JanDeDobbeleer** [comment]
@jntrnr I'm working around it by creating the file to an immutable location. But in all honesty, and I've seen similar issues while trying to understand the issue, it's very counter intuitive.

```
oh-my-posh init nu
source ~/.oh-my-posh.nu
```
