### ISSUE TITLE
Nushell gets OOM killed when `save`ing a large amount of pipeline output

### ISSUE THREAD

**Issue by evanrichter** [nushell/nushell#5147]
### Describe the bug

The `save` command does not flush contents to the output file periodically, meaning a large input stream causes nu to collect it all in memory, eventually causing an OOM condition on the system.

### How to reproduce

1. On a unix like system
2. Watch nushell memory usage in htop or something
3. `cat /dev/zero | save /dev/null` in nu
4. Nu never flushes contents to the file, so its memory balloons forever, eventually getting OOM'd

### Expected behavior

Stream the pipeline output to the file and not collecting all the contents to write at once

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.60.0                                    |
| branch             | makepkg                                   |
| short_commit       | 74af31a4                                  |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315  |
| commit_date        | 2022-03-22 19:07:11 +00:00                |
| build_os           | linux-x86_64                              |
| rust_version       | rustc 1.59.0 (Arch Linux rust 1:1.59.0-1) |
| cargo_version      | cargo 1.59.0                              |
| pkg_version        | 0.60.0                                    |
| build_time         | 2022-03-23 00:39:08 +00:00                |
| build_rust_channel | release                                   |
| features           | dataframe, default, trash, which, zip     |
| installed_plugins  |                                           |

**Comment by jntrnr** [comment]
Can you try with the latest main? There's been some work in this area, though I'm not sure if this specific issue was fixed.

**Comment by evanrichter** [comment]
Fantastic, it does work on the latest commit! Sorry for the needless issue.

BTW, the build time is very impressive... It only took 83 seconds to cold compile a release build on a 16 core, 16GB ram desktop!
