### ISSUE TITLE
TSV parser

### ISSUE THREAD

**Issue by indeyets** [nushell/nushell#515]
nu has `from_csv` importer for CSV format. would be nice to support its sister-format: TSV (tab-separated values). A lot of tools produce such files

**Comment by wycats** [comment]
Cool idea!

Is there a good Rust TSV crate we could use?

**Comment by androbtech** [comment]
@indeyets Please rebuild Nu with master. Should be ready to go for reading, writing, opening, and saving tsv.

/ref @wycats
