### ISSUE TITLE
prompt really slow to apear in wsl due to large/slow dirs on path

### ISSUE THREAD

**Issue by harrysarson** [nushell/nushell#5151]
### Describe the bug

Running nushell in wsl the prompt takes ~10 seconds to apear each time.

Note: running 

```
> PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib' nu
```

i.e. explicitly setting `$PATH` to not include the windows dirs makes the prompt appear instantly each time.

### How to reproduce

1. Start nushell in wsl
2. Press enter

### Expected behavior

not take 10 seconds to load the prompt.

### Configuration

〉version | transpose key value | to md --pretty                                       04/10/2022 09:33:51 PM
| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.60.0                                    |
| branch             | makepkg                                   |
| short_commit       | 74af31a4                                  |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315  |
| commit_date        | 2022-03-22 19:07:11 +00:00                |
| build_os           | linux-x86_64                              |
| rust_version       | rustc 1.59.0 (Arch Linux rust 1:1.59.0-1) |
| cargo_version      | cargo 1.59.0                              |
| pkg_version        | 0.60.0                                    |
| build_time         | 2022-03-23 00:39:08 +00:00                |
| build_rust_channel | release                                   |
| features           | dataframe, default, trash, which, zip     |
| installed_plugins  |                                           |

### Additional context

```
> echo $env.PATH | to md --pretty                                                      04/10/2022 09:37:11 PM
/usr/local/sbin
 /usr/local/bin
 /usr/sbin
 /usr/bin
 /sbin
 /bin
 /usr/games
 /usr/local/games
 /usr/lib/wsl/lib
 /mnt/c/WINDOWS/system32
 /mnt/c/WINDOWS
 /mnt/c/WINDOWS/System32/Wbem
 /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/
 /mnt/c/WINDOWS/System32/OpenSSH/
 /mnt/c/Users/Sarson/AppData/Local/Microsoft/WindowsApps
 /mnt/c/Users/Sarson/AppData/Local/Programs/Microsoft VS Code Insiders/bin
 /usr/bin/site_perl
 /usr/bin/vendor_perl
 /usr/bin/core_perl
```

```
> benchmark { ls /mnt/c/WINDOWS/system32 }                                             04/10/2022 09:40:52 PM
15sec 31ms 918us 700ns
```

Note: the dir isn't huge (about 4500 files/dirs in it) but something about how the windows fs is mounted into WSL makes statting the files really slow.

**Comment by jntrnr** [comment]
Can you try with the latest main? We've done a few improvements to startup and prompt draw times. You should see some big improvements on WSL.

**Comment by a5066987** [comment]
I had the same issue in wsl2. And I believe earlier version is good.

**Comment by harrysarson** [comment]
0.61.1 fixes this. Thanks!
