### ISSUE TITLE
/home/linuxbrew/.linuxbrew/bin/nu: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by wangjianpeng** [nushell/nushell#5154]
### Describe the bug

I am using **WSL  in windows 10** , install Ubuntu from Microsoft Store, then install unshell from :

```
brew install nushell
```

I can get the path with 

```
which nu
```
the result is : **/home/linuxbrew/.linuxbrew/bin/nu**

But when I  run nu  ,I get the following error :
**-bash: /home/linuxbrew/.linuxbrew/bin/nu: cannot execute binary file: Exec format error**

I get Ubuntu os info :

**Linux DESKTOP-E6SG3U1 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux**

### How to reproduce

1. install WSL in Windows 10
2. install Ubuntu in Microsoft Store
3. install brew from Ubuntu
4. install nushell from brew
5. run un

### Expected behavior

Hope to solve this problem

**Comment by jntrnr** [comment]
Hi @wangjianpeng - thanks for letting us know.

The homebrew packages are maintained by 3rd party contributors who volunteer work with homebrew. We aren't responsible for them. We just try to help them if they have issues. You may want to reach out to the creator of the homebrew package to see if they can help figure out what is going wrong.

**Comment by jntrnr** [comment]
Probably the most direct way is to use `cargo`. If you install Rust via rustup, you can do:

```
> cargo install nu --all-features
```

And it'll build and install nushell for you.

**Comment by wangjianpeng** [comment]
> Probably the most direct way is to use `cargo`. If you install Rust via rustup, you can do:
> 
> ```
> > cargo install nu --all-features
> ```
> 
> And it'll build and install nushell for you.

👍 I had use cargo to install  yesterday,it works well .but it seems like it will build nushell project .so I try to install nushell executable binary file from other way.
Thank you again,I will choose cargo to use nushell.

**Comment by fdncred** [comment]
seems like this is resolved, if not please reopen.
