### ISSUE TITLE
Some args do not pass properly

### ISSUE THREAD

**Issue by kidandcat** [nushell/nushell#5165]
### Describe the bug

When passing certain arguments to an application, it doesn't recognize them properly, while the same line works perfectly in bash.

### How to reproduce

Using https://github.com/jmk-foofus/medusa

Execute:
`medusa -h example.com -u test -p test -M web-form -m FORM-DATA:"post?j_username=&j_password=&Submit=Sign+in"`

### Expected behavior

Medusa should not warning about:
`WARNING: Invalid FORM-DATA format. Using default format: "post?username=&password="`

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.60.0                                |
| build_os           | macos-aarch64                         |
| rust_version       | rustc 1.59.0                          |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.60.0                                |
| build_time         | 2022-03-22 19:07:11 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

**Comment by fdncred** [comment]
for your arguments that are in double quotes, can you try them in single quotes or with backtick ` quotes?

**Comment by fdncred** [comment]
@jntrnr any ideas why this is failing even with the string literal quotes?

sorry @kidandcat, i know it's aggravating to try a dozen scenarios and nothing work. i hate having to "fish" for syntax like this.

**Comment by uasi** [comment]
@kidandcat try `-m 'FORM-DATA:post?j_username=&j_password=&Submit=Sign+in'` 

In bash, `FORM-DATA:"foo"` is exactly the same as `'FORM-DATA:foo'`. In nushell, however, `FORM-DATA:"foo"` is equal to `'FORM-DATA:"foo"'`. I think the warning is due to the extra double quotes around the argument to FORM-DATA.

**Comment by kidandcat** [comment]
Thanks, it's exactly as you described, I can even ignore outer single quotes, as what the scrip is expecting is KEY:value all together.

**Comment by fdncred** [comment]
@uasi That's a good tip. We should make some documentation out of it so other people with the same type of parameters know how to handle it. If you have time a documentation PR would be great. If you don't have time, that's fine too. Thanks for your help.

**Comment by uasi** [comment]
@fdncred To be honest, the current behavior of nushell is inconsistent/inconvenient compared to bash.

| literal        | bash interpretation      | nushell interpretation    |
| -------------- | --------- | ---------- |
| `'foobar'`     | `foobar`  | `foobar`   |
| `foo'bar'`     | `foobar`  | `foo'bar'` |
| `foo'bar'"baz"`     | `foobarbaz`  | `foo'bar'"baz"` |
| `'foo''bar'`   | `foobar`  | `foo''bar` (huh?) |
| `'foo'\''bar'` | `foo'bar` | N/A (there is no way to put `'` in between single-quoted literal)        |
| `'my files'/*` | `my files/a.txt`, ...| `'my files'/*` (there is no way to use whitespaces in glob) |

IMO adjacent string literals should be concatenated like bash or just syntax error. Once these rough edges are smoothed out, I'm happy to write a documentation.

**Comment by fdncred** [comment]
I despise inconsistent behavior. It would be nice to fix it. You also have to remember we have single quoting, double quoting and text within backticks that all mean something a little different. It would be good to flush this all out and make it work consistently and in a way that people can easily understand.
