### ISSUE TITLE
Rename commands like `source` and `use` to emphasize their different behavior

### ISSUE THREAD

**Issue by jmoore34** [nushell/nushell#5169]
### Related problem

A very common issue is people trying to use string or command interpolation with `source` and `use` and being confused as to why it doesn't work. Renaming these commands to look distinct from normal commands could help emphasize their special behavior.

### Describe the solution you'd like

Possible names: `source!` and `use!`. 

### Describe alternatives you've considered

`@source` and `@use` are also possible, though cmd and pwsh also have special meanings for @. Perhaps others are possible as well.

### Additional context and details

All keywords (incl. e.g. `module`) could be renamed, but perhaps we just want to rename `source` and `use` due to their potentially confusing behavior

**Comment by jntrnr** [comment]
Going ahead and closing, as we haven't seen strong motivation to rename (and taking on breaking changes) for these.
