### ISSUE TITLE
0.61 Winget auto-release failed

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#5170]
### Describe the bug

Some information here: https://github.com/nushell/nushell/actions/runs/2157901052

Seems like we're still hitting issues with the auto-submission.

cc @TechWatching @OfficialEsco 

### How to reproduce

See above

### Expected behavior

With luck, the auto-submission would go through

**Comment by OfficialEsco** [comment]
Ref old issue: https://github.com/nushell/nushell/issues/4894

looping in @denelon and @ryfu-msft and probably @fdncred as he can test it locally

**Comment by fdncred** [comment]
I just reran it and I'm not sure what's going on. It ends with

```
Manifest saved to D:\a\nushell\nushell\manifests\n\Nushell\Nushell\0.61.0

Manifest validation succeeded: True

Submitting pull request for manifest...

Error: Process completed with exit code 1.
```

**Comment by ryfu-msft** [comment]
Looking into this, I just fixed a bug in our exception handling that was blocking error messages from being shown when encountering github errors [here](https://github.com/microsoft/winget-create/pull/261) but that fix hasn't been pushed out yet so it doesn't help us in this case. 

The wingetcreate update was successful so the issue must relate to the GitHub token and the interaction with Github's apis. Who is the owner of the GitHub token (i.e. which fork of winget-pkgs is it pointing to)? 

See if any of the following common errors might be of help to you:
- Update your fork of winget-pkgs by fetching and merging all latest changes.
- Verify that you have authorized your SSO for microsoft (Settings > Developer Settings > Personal Access Tokens)

**Comment by ryfu-msft** [comment]
> I made sure my winget-pkgs was updated I also made a new PAT and assigned it but I have no idea what 'have authorized your SSO for microsoft'
> 
> but the action just went green so I guess it worked finally.

Oops, ignore that, that's something specific for the Microsoft organization. 

Did you simply rerun the build and it worked the second time?

**Comment by fdncred** [comment]
I updated the PAT and made sure my winget-pkgs was updated and then just reran it.
