### ISSUE TITLE
Macos Pre-Built Binary of 0.61 failing

### ISSUE THREAD

**Issue by EjPlatzer** [nushell/nushell#5171]
### Describe the bug

I just downloaded the pre-built binary of 0.61 for Macos (kudos on the quick release after the monumental success of 0.60). When I try to run the unzipped binary, I get the following error:
```
dyld[32375]: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /Users/me/Desktop/nushell-0.61.0/nu
  Reason: tried: '/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/usr/local/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file)
```

Is this an error in my environment (which seems unlikely, I haven't messed with the /usr directories at all)? Or is something wrong with the binary?

### How to reproduce

1. Download https://github.com/nushell/nushell/releases/download/0.61.0/nu_0_61_0_macOS.zip
2. Unzip the folder
3. Try to run `nushell-0.61.0/nu`

### Expected behavior

It seems like the pre-built binary shouldn't depend on system files that could be missing in an average user's environment.

### Configuration

▶ version | transpose key value | to md --pretty
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.0                                   |
| short_commit       | 74af31a4                                 |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315 |
| commit_date        | 2022-03-22 19:07:11 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.60.0                                   |
| build_time         | 2022-03-22 19:23:50 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

(This is my working 0.60 configuration. I can't launch 0.61 to get the config)

**Comment by jntrnr** [comment]
@EjPlatzer I think you may have to `brew install openssl`. We don't ship with openssl, but we do use it.

**Comment by EjPlatzer** [comment]
Hmm, ok. I use nix instead of brew as my package manager, and nix doesn't install to system directories, so I don't think that's an option for me.

Just for reference, I found about 6 applications on my machine that ship libssl internally. Obviously that has larger ramifications especially for bundle size, but just thought I'd point it out. 

I suppose I'll just wait until 0.61 is available through nix. Thanks for your help!
