### ISSUE TITLE
New "default" color does not work when directly referencing the name or short name

### ISSUE THREAD

**Issue by webdesserts** [nushell/nushell#5173]
### Describe the bug

First off, thanks for [implementing the default ansi code](https://github.com/nushell/nushell/issues/4973) in 0.61.0.  I AM able to use it and when it works, it works great. However I'm having to use color objects (e.g. `{ fg: default }`) in my config in order to use it. It seems that right now if. you try to use the **name** or **short name** variant of the color directly in the `color_config` it will ignore that setting and use `white` for most `color_config` settings.

### How to reproduce

Use the following command to set your `shape_string` `color_config` setting to `default`:
```
let $config = ($config | upsert color_config { shape_string: default })
```
Note the color ansi color used

Now use the following command to set your `shape_string` config to `{ fg: default }`

```
let $config = ($config | upsert color_config { shape_string: { fg: default } })
```
Note how the ansi color is different

### Expected behavior

I should be able to use the name & short name directly in `color_config`

### Screenshots

![Screen Shot 2022-04-12 at 11 21 01 PM](https://user-images.githubusercontent.com/916253/163099868-efa233bf-b4c8-48c1-81cb-2f588fede500.png)

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.61.0                              |
| branch             |                                     |
| tag                |                                     |
| build_os           | macos-x86_64                        |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23) |
| rust_channel       | stable-x86_64-apple-darwin          |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10) |
| pkg_version        | 0.61.0                              |
| build_time         | 2022-04-12 21:56:06 -05:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
This would've been great to test _before_ the release. I'll see what I can find out.

**Comment by webdesserts** [comment]
Thanks for the fix! I’ll try to pull this down and play around with it to see if I can catch anything else.
