### ISSUE TITLE
a pipeline with | save at the end does not report errors

### ISSUE THREAD

**Issue by robinvd** [nushell/nushell#5178]
### Describe the bug

without the save the error is correctly reported. While normally i run things without save first, in a script this is not an option.

### How to reproduce

1. save some data `touch a b c d` `ls | save out.csv`
2. have a pipeline a save at the end `open out.csv | insert type test | sort-by size | save out.csv`
3. now the file is silenty corrupted, now it looks like:
```
""
""
""
""
""
""
```

### Expected behavior

- the error is reported
- out.csv is not updated

**Comment by onthebridgetonowhere** [comment]
Thanks for reporting this. It looks like somehow the `save` command is ignoring the previous error. Without piping `save`, the error is thrown as expected.

**Comment by drbrain** [comment]
Here's another reproduction:

```
❯ echo 'my = "toml"' | save --raw my.toml
❯ cat my.toml
my = "toml"
❯ echo garbage | save my.toml
Error: nu::shell::unsupported_input (link)

  × Unsupported input
   ╭─[entry #740:1:1]
 1 │ echo garbage | save my.toml
   ·      ───┬───
   ·         ╰── "garbage" unable to de-serialize string to TOML
   ╰────

❯ cat my.toml
❯ ls my.toml
╭───┬─────────┬──────┬──────┬───────────────╮
│ # │  name   │ type │ size │   modified    │
├───┼─────────┼──────┼──────┼───────────────┤
│ 0 │ my.toml │ file │  0 B │ 2 minutes ago │
╰───┴─────────┴──────┴──────┴───────────────╯
```

The final `cat` and `ls` show the file `my.toml` has been truncated to zero bytes, I expect the old file contents to remain
