### ISSUE TITLE
Available binaries say they're 0.2.0 but build 0.1.3

### ISSUE THREAD

**Issue by ammkrn** [nushell/nushell#518]
The binaries for linux and macOS under the github `releases` tab, as well as the binaries fetched by `cargo install` say they're 0.2.0, but they actually install 0.1.3 (or at least the --version command says so, and they have the ascii tables instead of the box characters).

**Comment by ammkrn** [comment]
I thought fixed meant 'with a new release'. Feel free to re-close this, but I'll keep it open until the next release in case other people look for this in open issues before the next release.

**Comment by wycats** [comment]
It's reasonable to close things when they're fixed on master 😄
