### ISSUE TITLE
`cd` shortcut does not work in Windows since 0.60.0

### ISSUE THREAD

**Issue by Cyborus04** [nushell/nushell#5181]
### Describe the bug

Trying to cd to a directory by entering its name is not working on Windows, and instead gives the default CMD "Command not found message: 

> 'example_dir' is not recognized as an internal or external command,
operable program or batch file.

This did work in 0.4X.X, but broke since moving to 0.6X.X

### How to reproduce

1. Run a Windows (virtual) machine
2. Run Nu
3. Attempt to cd into a directory via the shortcut

### Expected behavior

I expected it to successfully move into the directory

### Screenshots

![image](https://user-images.githubusercontent.com/87248184/163245297-f69f571c-6fc9-40bb-9463-aacae45cec72.png)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.0                                   |
| branch             |                                          |
| tag                |                                          |
| short_commit       | 3783c19d                                 |
| commit_hash        | 3783c19d02f4a3b2f35cd26b79daabcb70b04880 |
| commit_date        | 2022-04-12 20:38:15 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01)      |
| pkg_version        | 0.61.0                                   |
| build_time         | 2022-04-12 21:07:36 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

### Additional context

Using the starship prompt

**Comment by jntrnr** [comment]
For this, you'll need to start by typing `.` or `/` (or `\`) and give the path. I don't think we support auto-cd with just the directory name.

**Comment by Cyborus04** [comment]
I should've tried that 🤦🏻‍♂️ Thanks

Impressive speed, btw

**Comment by Cyborus04** [comment]
The book does show it without the `./` still:
![image](https://user-images.githubusercontent.com/87248184/163247286-5cc0b189-6638-447e-9665-cf1e465f381d.png)

**Comment by jntrnr** [comment]
Sorry for the old stuff still in the book. We did a cleanup recently to try to bring everything up to date, but there are some bits we missed. If you have a second, a PR to the book to fix that would be awesome

**Comment by Cyborus04** [comment]
[PR made!](https://github.com/nushell/nushell.github.io/pull/399)
