### ISSUE TITLE
Environment variable was not captured because of special separator in windows

### ISSUE THREAD

**Issue by wymli** [nushell/nushell#5185]
### Describe the bug

Similar to https://github.com/nushell/nushell/issues/4899
In windows, we can use __`__  (backquote) in env value，which makes nushell misparse.

![图片](https://user-images.githubusercontent.com/49816514/163321820-1b8fc7be-75bf-4333-9b29-f4c02f514090.png)
![图片](https://user-images.githubusercontent.com/49816514/163321881-bad53474-ebe1-41a8-ad70-ec73afc5cc77.png)

### How to reproduce

the above figures show everything.

### Expected behavior

Env should be parsed correctly.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.0                                   |
| branch             |                                          |
| tag                |                                          |
| short_commit       | 3783c19d                                 |
| commit_hash        | 3783c19d02f4a3b2f35cd26b79daabcb70b04880 |
| commit_date        | 2022-04-12 20:38:15 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01)      |
| pkg_version        | 0.61.0                                   |
| build_time         | 2022-04-12 21:07:36 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
oh, wow. backticks are special characters in nushell that mean string literals.

**Comment by wymli** [comment]
Thanks for your reply~  It seems unfortunate that I use environment variables to store password, which sometimes need to contain some special characters.

**Comment by fdncred** [comment]
@jntrnr may have a work-around, but i'm not sure what one would be.

**Comment by uasi** [comment]
We need to escape backticks and some other metacharacters here:

https://github.com/nushell/nushell/blob/2fe14a7a5af978a1525f27859f5cba1a056063b1/crates/nu-cli/src/util.rs#L112-L121

**Comment by fdncred** [comment]
I'm not sure why backticks are used there either. if someone wants to make a pr and a test to fix this, it would be nice. :)
