### ISSUE TITLE
Support optional flags like: `def foo [--bar(-b)?: any] { echo $bar }`

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#5189]
### Related problem

Please visit this issue: https://github.com/nushell/nushell/issues/5103 for more details
Run: `def foo [--bar(-b)?: any] { echo $bar }` and we will get:
```
Error: nu::parser::parse_mismatch (link)

  × Parse mismatch during operation.
   ╭─[entry #363:1:1]
 1 │ def foo [--bar(-b)?: any] { echo $bar }
   ·          ─────┬────
   ·               ╰── expected short flag
   ╰────
```

### Describe the solution you'd like

Support `def foo [--bar(-b)?: any] { echo $bar }` syntax, and then:
```bash
1. git push --force-with-lease
2. git push --force-with-lease=origin-push
3. git push --force-with-lease origin-push
4. git push --force-with-lease=main:base
5. git push --force-with-lease=main:base main:main
```
will work

**Comment by jntrnr** [comment]
@hustcer - I don't quite understand this one. All flags are already optional. What does adding the `?` do?

**Comment by hustcer** [comment]
> @hustcer - I don't quite understand this one. All flags are already optional. What does adding the `?` do?

I mean adding the `?`( or other syntax ) to make the flag value optional so that both `git push --force-with-lease` and `git push --force-with-lease=origin-push` works, but after reading https://github.com/nushell/nushell/issues/5103#issuecomment-1358449874 I'm not insist on this

**Comment by amtoine** [comment]
it looks to me this is about giving a default value to an option, right?
if so, i'd say you can use one of the following 
```nushell
def foo [--bar = "default"] { ... }
```
or
```nushell
def foo [--bar] {
    let bar = $bar | default "default"
    ...
}
```
in case the default value is not a parse time constant :yum: 

in both cases, `foo --bar` and `foo --bar "value"` will work :+1:
