### ISSUE TITLE
Last command executed in a block always thinks it's in the tty mode

### ISSUE THREAD

**Issue by ZetaNumbers** [nushell/nushell#5190]
### Describe the bug

Consider this line:
```
[i ii iii iv v] | reduce -f '5 3 1 2 4' -n { |it, acc| $acc | rg -e ($it.index + 1) -r $it.item --passthrough }
```
It is there to convert arabic decimal literals to roman ones. But when you run it, the rg goes crazy and searches your filesystem. This caused because rg thinks it's in the tty mode, specifying `--color never` doesn't fix the problem. So here's how to fix it:
```
[i ii iii iv v] | reduce -f '5 3 1 2 4' -n { |it, acc| $acc | rg -e ($it.index + 1) -r $it.item --passthrough | echo $in }
# or
[i ii iii iv v] | reduce -f '5 3 1 2 4' -n { |it, acc| $acc | rg -e ($it.index + 1) -r $it.item --passthrough } | echo $in
```
We tell ripgrep it's contents are piped by piping its or the whole reduce output into `echo`.

### How to reproduce

`[i ii iii iv v] | reduce -f '5 3 1 2 4' -n { |it, acc| $acc | rg -e ($it.index + 1) -r $it.item --passthrough }`

### Expected behavior

`rg` should be executed in the tty mode only on the last block call.

### Screenshots

Just imagine ripgrep printing replacements for every file it encounters inside of current directory.

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.61.0                                |
| branch             | main                                  |
| tag                |                                       |
| build_os           | linux-x86_64                          |
| rust_version       | rustc 1.59.0                          |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.61.0                                |
| build_time         | 2022-04-12 20:38:15 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

**Comment by fdncred** [comment]
i created 5 files in a folder named a b c d e and in each file i put `blah <roman_numeral>` and on the next line `blah <number_for_roman_numeral>`. then cd'd into that folder and ran `[i ii iii iv v] | reduce -f '5 3 1 2 4' -n { |it, acc| $acc | rg -e ($it.index + 1) -r $it.item --passthrough }` and it seems to replace the number with the roman numeral through each loop and prints it to the screen. is it supposed to do something different?
![image](https://user-images.githubusercontent.com/343840/163405476-42e3beda-4990-4c1a-a14f-e467b3ace13e.png)
