### ISSUE TITLE
`post` is duplicating the `Content-Type` header

### ISSUE THREAD

**Issue by dantswain** [nushell/nushell#5194]
### Describe the bug

Using the `post` command to debug a web app I'm working on, I noticed that it is duplicating the `content-type` header.

### How to reproduce

Run an http server that prints out the full request (including unprocessed headers) and then from nu execute `post -t application/json 'http://localhost:8000/' { foo: bar }`.

I was able to reproduce using
```
npm install -g http-echo-server
PORT=8000 http-echo-server

[server] event: listening (port: 8000)
[server] event: connection (socket#1)
[socket#1] event: resume
[socket#1] event: data
--> POST / HTTP/1.1
--> content-type: application/json
--> content-type: application/json
--> content-length: 13
--> accept: */*
--> user-agent: nushell
--> host: localhost:8000
--> 
--> {"foo":"bar"}
[socket#1] event: prefinish
[socket#1] event: finish
[socket#1] event: readable
[socket#1] event: end
[socket#1] event: close
```

Note the duplicate `content-type: application/json`.

### Expected behavior

The `content-type` header should not be duplicated.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.0                                   |
| short_commit       | 74af31a4                                 |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315 |
| commit_date        | 2022-03-22 19:07:11 +00:00               |
| build_os           | macos-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.60.0                                   |
| build_time         | 2022-03-22 19:23:50 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by dantswain** [comment]
@fdncred honestly I was just going from an example I found somewhere (which I had to dig for... that's kind of a gap in the docs).  Either way, I don't see how this would be expected behavior.  Maybe it is, but that wasn't obvious to me from the docs?

**Comment by fdncred** [comment]
you could just do `help post` or `post --help` and it has examples how to run it. :)  I agree, it's probably not expected. I was just wondering if there's a gap between the `-t` param and the `-H` param that needs to be closed somehow. I'm sure we'd accept a PR to close that gap.

**Comment by fdncred** [comment]
> FWIW I've been daily driving nu for a couple weeks now and it's great! This is getting off topic but the only "feature" that's been a blocker for me has been the inability to append to a file a la `echo "stuff" >> .gitignore`

have you tried ` pipeline... | save --append filename`
