### ISSUE TITLE
Extending Path not working 

### ISSUE THREAD

**Issue by chtenb** [nushell/nushell#5195]
### Describe the bug

My line

```
  let-env Path = ($env.Path | append 'C:\Program Files\Git\usr\bin')
```

in env.nu or config.nu doesn't seem to work

### How to reproduce

1. On windows add the line above in env.nu 
2. Observe the path does not include this entry by evaluating `$env.Path`

### Expected behavior

Add the entry to the path

### Screenshots

Having this in env.nu 

```
  $env.Path
  let-env Path = ($env.Path | prepend 'C:\Program Files\Git\usr\bin')
  $env.Path
```

yields

```
C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86.......................................
╭───┬─────────
│ 0 │ C:\Program Files\Git\usr\bin                                                                                                                                 
│ 1 │ C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86.................... 
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.0                                   |
| branch             | master                                   |
| tag                |                                          |
| short_commit       | 3783c19d                                 |
| commit_hash        | 3783c19d02f4a3b2f35cd26b79daabcb70b04880 |
| commit_date        | 2022-04-12 20:38:15 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01)      |
| pkg_version        | 0.61.0                                   |
| build_time         | 2022-04-12 21:07:36 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

### Additional context

In the env.nu and config.nu files if I print `$env.Path` I don't see a list but a long string separated by `;` characters.

The odd thing is that it doesn't matter if I append or prepend. Nu seems to pick the longest item in the list or something.

**Comment by fdncred** [comment]
hmmm, i just did this and didn't have any issues `let-env PATH = ($env.PATH | append 'c:\apps\7-zip')`

**Comment by chtenb** [comment]
Could it be a windows specific issue?

**Comment by fdncred** [comment]
> Could it be a windows specific issue?

I don't follow. The example i posted was on windows.

**Comment by chtenb** [comment]
I thought that on windows you had to use `Path` instead of `PATH`.

**Comment by fdncred** [comment]
> I thought that on windows you had to use `Path` instead of `PATH`.

That is not _always_ the case.

**Comment by chtenb** [comment]
> That is not _always_ the case.

I didn't know that. In what situations do you have to use the uppercase variant on windows?
For me (windows 10) it gives

![image](https://user-images.githubusercontent.com/1030961/163565552-6503d7d4-1fc8-4d93-90d7-202fdd9237e5.png)

**Comment by fdncred** [comment]
This is what I found from previous research. There may be other ways too.

From 2/18/2022
In Windows, i just discovered this while looking at a pr that has this command 'PATH' in (env).name 
1. if your parent shell is cmd.exe, it's `Path`
2. if your parent shell is pwsh.exe or powershell.exe, it's `PATH`
3. if you have no parent shell, it's `Path` 
 and to top it off, ci passes with 'PATH' in (env).name  - i'm wondering if people on windows will have build issues with this example.

So, for defensive purposes, on Windows, we should always check if it's `PATH` or `Path`

**Comment by chtenb** [comment]
That's quirky. Anyway, is there any other information that I can provide that might help to troubleshoot this issue?

**Comment by fdncred** [comment]
I don't see any issue here to troubleshoot. You either update the `Path` variable or the `PATH` variable. What am I missing?

**Comment by chtenb** [comment]
> I don't see any issue here to troubleshoot. 

I mean the issue from the OP

**Comment by chtenb** [comment]
I just confirmed that this issue also occurs on WSL Ubuntu.
The following line in env.nu

```
  $env.PATH
  let-env PATH = ($env.PATH | prepend '/mnt/c/Program Files/Microsoft VS Code/bin')
  $env.PATH
```

gives the following output at startup

```
/home/chiel/.nix-profile/bin:/home/chiel/.local/bin:/home/chiel/.cargo/bin:/home/chiel/.nix-profile/bin:/home/chiel/.nvm/versions/node/v16.2.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/snap/bin
╭───┬──────────────────────────────────────────────────────────────────╮
│ 0 │ /mnt/c/Program Files/Microsoft VS Code/bin                       │
│ 1 │ /home/chiel/.nix-profile/bin:/home/chiel/.local/bin:/home/chiel/ │
│   │ .cargo/bin:/home/chiel/.nix-profile/bin:/home/chiel/.nvm/version │
│   │ s/node/v16.2.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr │
│   │ /bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/sn │
│   │ ap/bin                                                           │
╰───┴──────────────────────────────────────────────────────────────────╯
```

**Comment by fdncred** [comment]
It looks like you may not have your `ENV_CONVERSIONS` set. Example:
```
let-env ENV_CONVERSIONS = {
    "PATH": {
        from_string: { |s| $s | split row (char esep) }
        to_string: { |v| $v | str collect (char esep) }
    }
}
```

I wonder if that has anything to do with it.

**Comment by chtenb** [comment]
I took the default config from nu as baseline, so my config file looks like


```
let-env ENV_CONVERSIONS = {
  "PATH": {
    from_string: { |s| $s | split row (char esep) }
    to_string: { |v| $v | str collect (char esep) }
  }
  "Path": {
    from_string: { |s| $s | split row (char esep) }
    to_string: { |v| $v | str collect (char esep) }
  }
}

# Directories to search for scripts when calling source or use
#
# By default, <nushell-config-dir>/scripts is added
let-env NU_LIB_DIRS = [
    ($nu.config-path | path dirname | path join 'scripts')
]

# Directories to search for plugin binaries when calling register
#
# By default, <nushell-config-dir>/plugins is added
let-env NU_PLUGIN_DIRS = [
    ($nu.config-path | path dirname | path join 'plugins')
]

# To add entries to PATH (on Windows you might use Path), you can use the following pattern:
# let-env PATH = ($env.PATH | prepend '/some/path')

###### PATH ######

if (sys).host.name == "Windows" {
  $env.Path
  let-env Path = ($env.Path | prepend 'C:\Program Files\Git\usr\bin')
  $env.Path
} else {
  $env.PATH
  let-env PATH = ($env.PATH | prepend '/mnt/c/Program Files/Microsoft VS Code/bin')
  $env.PATH
}
```

Could it be that the ENV_CONVERSIONS settings are not taken into account yet while the env.nu script is still running? When my shell is started up and I type `$env.Path` manually, it looks normal. But in the env.nu itself it does not and the issue occurs.

**Comment by fdncred** [comment]
Ya, I think everything in env.nu is available in config.nu but not before.

**Comment by chtenb** [comment]
That's what I thought, but when I move the PATH modification part to config.nu while leaving the path conversion in env.nu it still doesn't work. Also, in 0.60 env.nu did not exist and it was working there.

**Comment by fdncred** [comment]
I bet it's because you're making changes inside of a block. you do `if something { make changes } else { make changes }`. changes are scoped in nushell. what happens if you just try your `let-env` outside of the block for one of the operating systems. does it work by itself? if so, you may need a `def-env` custom command.

**Comment by chtenb** [comment]
Good call! Outside of the if block it works. So the fact that the PATH variable isn't split yet was a red herring and does not pose a problem for appends or prepends. But it still looks like a bug that may pose problems in other situations. Do you want me to create a (separate) bug report for that?

I'm a little confused how to modify the PATH from within a if block. The documentation talks about `def-env`, which is also what you suggest, but the following does not work.

```sh
def-env extendPathsWindows [] {
  let-env Path = ($env.Path | prepend 'C:\Program Files\Git\usr\bin')
}

if (sys).host.name == "Windows" {
  extendPathsWindows
}
```

and neither does

```sh
def-env extendPathsWindows [] {
  if (sys).host.name == "Windows" {
    let-env Path = ($env.Path | prepend 'C:\Program Files\Git\usr\bin')
  }
}

extendPathsWindows
```

**Comment by fdncred** [comment]
I haven't tried your def-envs yet but if they're not working, you might want to check the nu_scripts repo. it has some interesting scripts that do work. Most have to do with changing a directory in a block but that's essentially changing and environment variable in a block. You might also want to play with making your script a module and using `export env`. `help export env` will give you some information but there are also examples of that in the nu_scripts repo.

**Comment by filaretov** [comment]
@chtenb 

A workaround would be to define a function that returns the additional paths on a condition and then always set the path. If the condition doesn't hold, then you would be extending the path with an empty list, like this:


```
def additional-paths-windows [] {
    let paths = if (sys).host.name == "Windows" {
        ['C:\Program Files\Git\usr\bin']
    } else {
        []
    }
    $paths
}

let-env Path = ($env.Path | prepend (additional-paths-windows))

```

**Comment by fdncred** [comment]
ya, good point @filaretov. i think the problem with the most recent tries from @chtenb may be having the `let-env` inside of an `if`. so, your solution avoids that.

**Comment by chtenb** [comment]
Thanks for the suggestions! I'll close this issue now.

**Comment by chtenb** [comment]
@filaretov If I deploy my env.nu on a linux machine the line 

```
  let-env Path = ($env.Path | prepend $new-paths)
```

will throw an error because 

```
 42 │   let-env Path = ($env.Path | prepend $new-paths)
    ·                        ──┬─
    ·                          ╰── did you mean 'PATH'?
 43 │ }
    ╰────
```

I would have to set Path in the windows case but PATH in the linux case. Any ideas on how to solve that?

**Comment by chtenb** [comment]
I guess I could just set the both in both cases, but that feels suboptimal.

```
let new_paths = if (sys).host.name == "Windows" {
  ['C:\Program Files\Git\usr\bin']
} else {
  ['~/.cabal/bin', '~/.ghcup/bin']
}

let existing_path = if (sys).host.name == "Windows" {
  $env.Path
} else {
  $env.PATH
}

let-env Path = ($existing_path | prepend $new_paths)
let-env PATH = ($existing_path | prepend $new_paths)
```
