### ISSUE TITLE
Build failures on Apple Silicon

### ISSUE THREAD

**Issue by gvnn3** [nushell/nushell#5198]
### Describe the bug

I'm trying to follow the build instructions in the documentation but am faced with the following errors:

  = note: ld: warning: ignoring file /opt/homebrew/opt/openssl@3/lib/libssl.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
          ld: warning: ignoring file /opt/homebrew/opt/openssl@3/lib/libcrypto.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
          Undefined symbols for architecture x86_64:
            "_ENGINE_load_builtin_engines", referenced from:
                __libssh2_openssl_crypto_init in liblibssh2_sys-1270ba66a70d3996.rlib(openssl.o)
            "_ENGINE_register_all_complete", referenced from:
                __libssh2_openssl_crypto_init in liblibssh2_sys-1270ba66a70d3996.rlib(openssl.o)
            "_OPENSSL_init_ssl", referenced from:
                openssl_sys::init::_$u7b$$u7b$closure$u7d$$u7d$::hdf60701bb885e9e7 in libopenssl_sys-f31ab2562d667dbb.rlib(openssl_sys-f31ab2562d667dbb.openssl_sys.f24daeda-cgu.11.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

### How to reproduce

Checkout the sources on an Apple Silicon Mac (my system is Monterey 12.3.1)

cargo build --workspace  (does not matter if extras are included)

### Expected behavior

Expected the build to complete correctly.

**Comment by jntrnr** [comment]
Going to go ahead and close this, as we've got `openssl` mentioned in the build instructions for macOS. https://www.nushell.sh/book/installation.html#macos
