### ISSUE TITLE
Arrow keys stop working after running dotnet or ssh

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#5220]
### Describe the bug

Running the `dotnet` CLI tool from [the .NET 6 SDK](https://dotnet.microsoft.com/en-us/download/dotnet) breaks arrow keybindings in Nu somehow. I'm on the latest `main`, using GNOME Terminal on Linux.

### How to reproduce

1. Confirm that arrow keybindings still work (for example, by pressing arrow keys while `keybindings listen` is running)
2. Run`dotnet --version` or any `dotnet` subcommand
3. Arrow keys no longer work; can't see them in `keybindings listen` or press  ↑ (up arrow) for command history

```
> keybindings listen
Type any key combination to see key details. Press ESC to abort.
code: Up, modifier: NONE, flags: 0b000000
> dotnet --version
6.0.103
> keybindings listen
Type any key combination to see key details. Press ESC to abort.
......
```

### Expected behavior

I expected arrow keys to keep working.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.1                                   |
| branch             | main                                     |
| tag                |                                          |
| short_commit       | cf65f77b                                 |
| commit_hash        | cf65f77b020dbe8c64187a9b5ab1abcd478a2320 |
| commit_date        | 2022-04-17 19:31:03 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)        |
| pkg_version        | 0.61.1                                   |
| build_time         | 2022-04-17 21:49:02 -07:00               |
| build_rust_channel | debug                                    |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | query, query json, query web, query xml  |

```
> dotnet --info                                                                                 04/17/2022 09:51:27 PM
.NET SDK (reflecting any global.json):
 Version:   6.0.103
 Commit:    2c677ffc1e

Runtime Environment:
 OS Name:     fedora
 OS Version:  36
 OS Platform: Linux
 RID:         fedora.36-x64
 Base Path:   /usr/lib64/dotnet/sdk/6.0.103/

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.103 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
```

GNOME Terminal
Version 3.44.0 for GNOME 42

### Additional context

I'm not sure what it is about `dotnet` that triggers this. I couldn't reproduce it with `cargo`, `node`, or `python`.

**Comment by chen244** [comment]
Same, interesting bug

**Comment by elferherrera** [comment]
If they are not detected then it seems to be something happening with crossterm

**Comment by rgwood** [comment]
@chen244 What OS + terminal are you using?

**Comment by chen244** [comment]
> @chen244 What OS + terminal are you using?

Archlinux, terminals are alacritty and foot. They all reproduce this bug.

**Comment by rgwood** [comment]
Oof, I can reliably reproduce this with `ssh` too:

1. ssh to another computer with `ssh other_computer_name`
2. Exit the ssh session with `ctrl+d`
3. Arrow keys no longer work

**Comment by rgwood** [comment]
I tried to `git bisect` this; I think this behavior started with the engine-q migration but it's a little hard to pinpoint a commit.

**Comment by jntrnr** [comment]
@rgwood ahh, that will make it harder. The engine-q commit is also when we adopted reedline as our line editor, so there's some difference between rustyline and reedline maybe that's causing it?

**Comment by rgwood** [comment]
Closing as this has been fixed by https://github.com/nushell/nushell/pull/5302.
