### ISSUE TITLE
Nu should have a faster way to check the OS

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#5231]
### Related problem

Currently, `(sys).host.name` takes 300+ milliseconds to run on a fast Linux desktop:

```
> benchmark  { (sys).host.name }
348ms 119us 253ns
> benchmark  { sys }
327ms 843us 51ns
```

This makes checking the OS a bit slow in interactive contexts (like prompts) or in hot loops.

### Describe the solution you'd like

Ideally `(sys).host.name` would be a lot faster; perhaps we can make `sys` lazy somehow so it doesn't have to retrieve the other properties?

Alternately, we could add a new way to get just the OS.

### Additional context and details

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.1                                   |
| branch             | master                                   |
| tag                |                                          |
| short_commit       | cf65f77b                                 |
| commit_hash        | cf65f77b020dbe8c64187a9b5ab1abcd478a2320 |
| commit_date        | 2022-04-17 19:31:03 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)        |
| pkg_version        | 0.61.1                                   |
| build_time         | 2022-04-17 21:49:02 -07:00               |
| build_rust_channel | debug                                    |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | query, query json, query web, query xml  |

**Comment by jntrnr** [comment]
and it's not like the OS would change after startup :sweat_smile:

**Comment by jntrnr** [comment]
@rgwood I'm wondering why `sys` is quite so expensive`. Maybe we could split some of it off into a fast version? or maybe only do the slow parts with an optional flag

**Comment by jntrnr** [comment]
It may be specific to certain OSes? Here's linux mint:

```
> benchmark { sys }
31ms 71us 291ns
```

**Comment by rgwood** [comment]
@jntrnr I'm not sure which parts are expensive, but it is gathering an awful lot of data (sessions, temperatures, disk usage, current frequency of each core, network interfaces...). I can try to get more detailed timing later.

That is surprising that it's so much faster on your Linux Mint machine. I'm on Fedora 36 FWIW.

**Comment by herlon214** [comment]
On windows:
```
> benchmark { sys } 
356ms 686us 900ns
```

I can test on Ubuntu in the morning.

**Comment by jmoore34** [comment]
Perhaps the nu script in question could cache the OS e.g. in an environmental variable

**Comment by rgwood** [comment]
@jmoore34 Yes, that's a decent solution for many use cases. But eventually I'd like Nu to be fast enough that users can just check the OS anywhere without worrying about performance.

**Comment by fdncred** [comment]
```
benchmark { sys }
27ms 798us 500n
```

it's interesting that some platforms take a long time and others are fast. this is from my Mac.  I'm wondering if there's something that nushell could capture at launch and store in `$nu.platform` like are there simple things like env vars? I mean if you can find a USER_PROFILE env var, you're most likely on Windows. I'm not sure if there's an equivalent for Linux or Mac.
