### ISSUE TITLE
`describe` should handle CustomValues better

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#5233]
### Related problem

Currently `describe` returns "custom" when piped a [CustomValue](https://github.com/nushell/nushell/blob/565be6aaefc60be154265d8951027c19769b02ae/crates/nu-protocol/src/value/mod.rs#L95):
```
〉reillys-test-command | describe
custom
```

### Describe the solution you'd like

It would be nice if `describe` returned the name of the specific CustomValue implementation.

I can look into this later, mostly creating the issue so I don't forget.

**Comment by elferherrera** [comment]
There is a method in the trait that converts your custom value to native nu. That is used when printing the custom value
