### ISSUE TITLE
Last result ring buffer variables

### ISSUE THREAD

**Issue by Jacobious52** [nushell/nushell#5234]
### Related problem

I do a lot of work with commands like `kubectl` that can take some time to return and often require my next command to do something with the result and build on that until I have what I want.

e.g. In a typical interactive session I might go something like below in succession 
```nu
> kubectl get pod | detect columns
> kubectl get pod | detect columns | find aws-node
> kubectl get pod | detect columns | find aws-node | first
> kubectl get pod | detect columns | find aws-node | first | get NAME
```

It would be quite handy to be able to quickly use the last answer with a shortcut or automatically set a variable

### Describe the solution you'd like

I propose an (optional/configurable perhaps) ring buffer of last results that could be used.

```nu
> kubectl get pod | detect columns
> $1 | find aws-node
> $1 | first
> $1 | get NAME
```

where say `$1`, `$2`, `$3` are the N-1, N-2, N-3 results from the interactive shell.

This would also make follow up compound statements a little more "lightweight"

```nu
# instead of
> let my_pod = (kubectl get pod | detect columns | find aws-node | first | get NAME)
> kubectl describe pod $my_pod

# could be
> kubectl get pod | detect columns | find aws-node | first | get NAME
> kubectl describe pod $1
```

## Just set your own variable with let

Explicitly setting a variable works but is cumbersome `let last_output = (kubectl..)`

## function of a `stash` type command that is a little more ergonomic than an explicit let which forwards through input

```nu
def-env "stash save" [] {
    let-env stashed_var = $in
    $env.stashed_var
}

def-env "stash get" [] {
    $env.stashed_var
}
```

```nu
> ls | stash save
# result of ls
stash get
# result of ls
```

## Define a wrapping command for each command you want this for.

e.g. I currently have a function like
```nu
def-env kn [--output (-o): string, ...args] { 
    let output = ($output | default wide)
    let result = (kubectl -o $output $args | if $output == "wide" { from ssv -a } else { from yaml })
    let-env KUBE_RESULT = $result
    $result
}

alias kk = $env.KUBE_RESULT
```

Where I can use `kk | ...` to use the cached last result and do what I want with it. 
However this is currently inflexible as passing rest flags is not yet supported. https://github.com/nushell/nushell/issues/4781

```nu
> kn -n kube-system get po
Error: nu::parser::unknown_flag (https://docs.rs/nu-parser/0.61.0/nu_parser/enum.ParseError.html#variant.UnknownFlag)

  × The `kn` command doesn't have flag `-n`.
   ╭─[entry #22:1:1]
 1 │ kn -n kube-system get po
   ·     ┬
   ·     ╰── unknown flag
   ╰────
  help: use kn --help for a list of flags
```

This method would also need the user to setup a forward through command for each case they want to use it.

**Comment by herlon214** [comment]
This sounds interesting :thinking: 
I'm just afraid of it making the whole thing slow for storing big results (e.g: https://github.com/nushell/nushell/issues/5236)
Maybe fixing that would make this feature here viable

**Comment by herlon214** [comment]
I'd say that it's better to have https://github.com/nushell/nushell/issues/4781 done rather than storing the the previous command result in the memory for everybody. Specially because there are people working with data frames and the data can be gigabytes.

**Comment by Jacobious52** [comment]
Sounds reasonable. I agree for storing big results I'd imagine we'd want some sort of size limit, but that would lead to inconsistent behaviour if something is stored or not. 

#4781 would enable this for the just commands I want without not forcing the feature on every user. As a bonus it allows us to fully "nu-ify" external commands easier.

**Comment by herlon214** [comment]
@Jacobious52 I'm wondering if making a plugin would be a better option, we can try to work on it together. I'm also using kubectl a lot.

**Comment by Jacobious52** [comment]
@herlon214  Do you mean a kubectl plugin? I have considered it, however it'd be a large undertaking to match all the needed functionality of kubectl unless you forward through ^kubectl and just format things for nu. It also wouldn't be a generic solution for other commands with the same needs.

**Comment by herlon214** [comment]
@Jacobious52 yeah, that's true.
