### ISSUE TITLE
Failed to suppress result message of mv in parameterizing script

### ISSUE THREAD

**Issue by TD-Sky** [nushell/nushell#5235]
### Describe the bug

I wrote zsh functions to call nushell script. But it failed to use the `-q`  option in nushell script. 

## caller

`mov` will move all the files and directories written in system clipboard to specified path.

```zsh
function mov {
	nu $HOME/Scripts/pn/move $1
}
```

## callee

**~/Scripts/pn/move**:

```nushell
#!/usr/bin/nu
 
def main [dest?: path] {
    let dest = if ($dest == null) { './' } else { $dest }

    for item in (xclip -sel c -o | split row (char newline)) {
        mv -q $item $dest
    }
}
```

### Expected behavior

It works fine, but it shouldn't print the result message.

### Error

╭───┬────────────────╮ 
 │ 0     │ [list 0 items]                      │
 │ 1     │ [list 0 items]                      │
 │ 2     │ [list 0 items]                      │
╰───┴────────────────╯

**Comment by hustcer** [comment]
`mv` is quiet by default now on the latest main, and to see the feedback please add `-v` flag
