### ISSUE TITLE
Panic while writing error to the screen in Windows

### ISSUE THREAD

**Issue by shift-d** [nushell/nushell#5240]
### Describe the bug

The title is self-descriptive + I dont know how describe it properly

### How to reproduce

```nu
let-env foo = "foo"
cd ($env.foo + "bar")
```

### Expected behavior

I don't think it should throw arrow errors like this.

### Screenshots

![изображение](https://user-images.githubusercontent.com/53366878/164035233-f9627749-99df-427b-9a0c-9ec24b72c120.png)

### Configuration

~                                                                
❯ version | transpose key value | to md --pretty                 
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.0                                   |
| short_commit       | 74af31a4                                 |
| commit_hash        | 74af31a42ff4feb8d5d9897c0d99c7434678a315 |
| commit_date        | 2022-03-22 19:07:11 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.60.0                                   |
| build_time         | 2022-03-22 19:26:49 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

### Additional context

This happens to any path-dependent command, like cd, open, save.

**Comment by fdncred** [comment]
what happens if you use string interpolation like `cd $"($env.foo)bar"`?

**Comment by jntrnr** [comment]
I'm not sure why it's happening, but there's some issue not with the adding the strings but with drawing the error to the screen. I've seen this before, though not in a while. Did you do anything before trying to run this command that might have caused stdout or stderr to get blocked?

**Comment by filaretov** [comment]
I get the same behavior on `0.60.0`, but not on `0.60.1`. I don't know what fixed it.

```
❯ cd ($env.foo + "bar")
Error: nu::shell::directory_not_found_help (link)

  × Directory not found
   ╭─[entry #33:1:1]
 1 │ cd ($env.foo + "bar")
   ·     ────────┬───────
   ·             ╰── directory not found
   ╰────
  help: IO Error: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
```


| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.60.1                                   |
| branch             | HEAD                                     |
| tag                | 0.60.0
0.61.0                            |
| short_commit       | 8f378ecd                                 |
| commit_hash        | 8f378ecd23194f85174d83e95e359a386a7f2dea |
| commit_date        | 2022-04-08 21:43:43 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.60.1                                   |
| build_time         | 2022-04-09 01:02:19 +02:00               |
| build_rust_channel | release                                  |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

**Comment by jntrnr** [comment]
@shift-d - can you try with a more recent nushell? It may already be fixed

**Comment by onthebridgetonowhere** [comment]
@shift-d - a directory not found error is now thrown, at least on the latest commit (https://github.com/nushell/nushell/commit/e6a70f98467593607c26d248184941391fbf6664)
Can you confirm if it works now?

**Comment by fdncred** [comment]
it works for me on 0.61.1 1c0b27b4

**Comment by hustcer** [comment]
It works now on Windows
