### ISSUE TITLE
Better support for creating and consuming raw streams

### ISSUE THREAD

**Issue by InquisitiveCoder** [nushell/nushell#5245]
I'm new to nushell so apologies if I've missed something. However I did look over the full command list several times and skimmed the source code of various command implementations to no avail.

## Motivating example
I was trying to perform the equivalent of `cat part0 part1 | md5sum` (where *part0* and *part1* are 4 GB pieces of a larger file.) While researching how to do this I realized there's no way to build up a raw stream from multiple commands since:
- Nu only writes the last command in a group/block to stdout, and
- All of the built-in forms of iteration either produce lists (e.g. `each`) or require an accumulator (e.g. `reduce`).

Likewise there don't seem to be low-level commands to consume raw streams (e.g. `read`).

## Suggestions for new commands/options
I'm not sure all of these are feasible to implement but having just one or two could've solved my problem.

### `each --raw`
Output the result of each block execution to stdout instead of to a list. This would allow reducing a list into a raw stream. This can't be done with `reduce` since there doesn't seem to be a byte concatenation command and even if you could do it that way, it'd be very inefficient.

### `save --stdout`
Force the input stream to write to stdout. This would allow building up a raw stream out of ad-hoc groups of commands:
> foo | save --stdout
> bar | save --stdout
> baz

This could also double as `tee` if `save --stdout file` outputs to both.

### `stdout <block>`
Similar to `do` but sends all output to stdout, including output that would've gone to the terminal. This would enable similar functionality to `save --stdout` but could be applied to an existing block after the fact.

### Multi-file `open` or built-in `cat`
A simpler alternative to using `each --raw` with files (c.f.  `ls *.bin | each --raw { |it| open --raw $it.name }`)

### `hash --reduce`
When applied to a list, hash the concatenation of the rows rather than hashing individual row values to a new list. In my opinion commands like `hash` *should* reduce lists by default; it's always possible to map the list using `each` and if the command can't output an accumulator it's not possible to use `reduce`. But I don't want to break backwards compatibility so I'd settle for a flag.

### `read n`
A way to read `n` bytes from a raw stream.

###  `split bytes [n]`
Similar to `split row`, this would split the stream into rows of *n* bytes.

**Comment by fdncred** [comment]
these command seem reasonable to me. regarding `read n`, I believe `first` and `skip` can read binary bits, but not `take` and `last`. I use those with `into binary` in order to sniff the file bits.

example:
```
> open ./install-all.sh | into binary | first 100
Length: 100 (0x64) bytes | printable whitespace ascii_other non_ascii
00000000:   23 21 2f 62  69 6e 2f 73  68 0a 0a 23  20 55 73 61   #!/bin/sh__# Usa
00000010:   67 65 3a 20  4a 75 73 74  20 72 75 6e  20 60 73 68   ge: Just run `sh
00000020:   20 69 6e 73  74 61 6c 6c  2d 61 6c 6c  2e 73 68 60    install-all.sh`
00000030:   20 69 6e 20  6e 75 73 68  65 6c 6c 20  72 6f 6f 74    in nushell root
00000040:   20 64 69 72  65 63 74 6f  72 79 0a 0a  65 63 68 6f    directory__echo
00000050:   20 22 2d 2d  2d 2d 2d 2d  2d 2d 2d 2d  2d 2d 2d 2d    "--------------
00000060:   2d 2d 2d 2d                                          ----
```

```
> open ./install-all.sh | into binary | skip 700
Length: 118 (0x76) bytes | printable whitespace ascii_other non_ascii
00000000:   68 6f 20 22  2d 2d 2d 2d  2d 2d 2d 2d  2d 2d 2d 2d   ho "------------
00000010:   2d 2d 2d 2d  2d 2d 2d 2d  2d 2d 2d 2d  2d 2d 2d 2d   ----------------
00000020:   2d 2d 2d 2d  2d 2d 2d 2d  2d 2d 2d 2d  2d 2d 2d 2d   ----------------
00000030:   2d 2d 22 0a  20 20 20 20  63 64 20 63  72 61 74 65   --"_    cd crate
00000040:   73 2f 24 70  6c 75 67 69  6e 20 26 26  20 63 61 72   s/$plugin && car
00000050:   67 6f 20 69  6e 73 74 61  6c 6c 20 2d  2d 70 61 74   go install --pat
00000060:   68 20 2e 20  26 26 20 63  64 20 2e 2e  2f 2e 2e 2f   h . && cd ../../
00000070:   0a 64 6f 6e  65 0a                                   _done_
```

**Comment by jntrnr** [comment]
I think has gotten better, so that we have both commands for working with binary data and we have the notion of a raw stream coming from externals.

Going ahead and closing, but if you find gaps in what we have in the latest main, please open issues for them.
