### ISSUE TITLE
Dataframe panic when taking a row with a list 

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#5252]
### Describe the bug

Panics when taking a row from a dataframe if the item being taken is a list.

### How to reproduce

```
> let foo = { rc: [ 0 1 2 3 ] }
> $foo | dfr to-df | dfr take (0 | dfr to-df)
thread '<unnamed>' panicked at 'not implemented', /path/to/src/github.com-1ecc6299db9ec823/polars-core-0.20.0/src/series/series_trait.rs:78:13
```

### Expected behavior

Shouldn't panic and I would expect the `[0 1 2 3]` to be converted to a series.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.1                                   |
| branch             |                                          |
| tag                |                                          |
| short_commit       | 7e97be1d                                 |
| commit_hash        | 7e97be1dd44dd82e0688b23b5484b1790c9dcf20 |
| commit_date        | 2022-04-20 04:59:53 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.61.1                                   |
| build_time         | 2022-04-20 10:21:57 +03:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | gstat                                    |

**Comment by elferherrera** [comment]
The problem here is that the list in the record gets stored in the DF as an object. There are few operations that can be done with objects know. You can check that if you do 
```
$foo | dfr to-dfr ! dfr dtypes
```
What we could do to improve is to parse that list as a Series of lists, which is a valid type in polars

**Comment by kubouch** [comment]
Yeah, list -> series would be nice. Also, I remember in one instance, I ended up having a record stored as record, not as a df, in a nested dataframe.

It would also be nice to strengthen against the panics so we don't end up shutting down Nushell in case something like this goes wrong.

**Comment by elferherrera** [comment]
unfortunately, I dont know where those panics will come from

**Comment by sholderbach** [comment]
Can't repro with the newer polars plugin.
