### ISSUE TITLE
`source` fails

### ISSUE THREAD

**Issue by JPBeckner** [nushell/nushell#5255]
### Describe the bug

Using the command `source` to activate a python `virtualenv,` I get an error:
```sh
/home/me/some/path/python-project〉source ./venv/bin/activate                                                      04/20/2022 10:14:31 AM
Error: nu::parser::missing_positional (link)

  × Missing required positional argument.
   ╭─[activate:4:1]
 4 │ 
 5 │ if [ "${BASH_SOURCE-}" = "$0" ]; then
   ·                                ▲
   ·                                ╰── missing cond
 6 │     echo "You must source this script: \$ source $0" >&2
   ╰────
  help: Usage: if <cond> <then_block> (else <else_expression>)
```
Also, on invoking `source --help` it informs that `source` would invoke the `main` as default, but didn't worked for me.
> Runs foo.nu in current context and call the `main` command automatically...
```/home/me/scripts/nu〉cat ./foo.nu                                                                                  04/20/2022 10:22:29 AM
def main [] { echo 'Hi!' }
/home/me/scripts/nu〉source ./foo.nu                                                                               04/20/2022 10:22:34 AM
/home/me/scripts/nu〉source ./foo.nu; main                                                                         04/20/2022 10:22:47 AM
Hi!
```

### How to reproduce

1. Go to an isolated directory
```sh
mkdir nu-report
cd ./nu-report/
```
2. Install the [virtualenv](https://pypi.org/project/virtualenv/)
```sh
pip install virtualenv
```
3. Create a virtualenv with any <venv-name>
```
echo "example: virtualenv <venv-name>"
virtualenv venv
```
4. Activate the virtualenv
```sh
source venv/bin/activate
```

### Expected behavior

Activate the virtualenv through the `source` command:
```sh
source venv/bin/activate
```
![image](https://user-images.githubusercontent.com/43730756/164244079-be0f0ec6-db4c-42d1-a590-6f84ffd44e8d.png)

### Screenshots

![image](https://user-images.githubusercontent.com/43730756/164241167-f4083f00-33c8-4604-9ed5-f54e18079b0d.png)
![image](https://user-images.githubusercontent.com/43730756/164240975-a3ec7c73-2e18-484f-9d37-956c2e12ab17.png)

### Configuration

/home/me〉version | transpose key value | to md --pretty                                                           04/20/2022 10:29:07 AM
| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.61.0                              |
| branch             |                                     |
| tag                |                                     |
| build_os           | linux-x86_64                        |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)   |
| pkg_version        | 0.61.0                              |
| build_time         | 2022-04-20 09:56:20 -03:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |

`neofetch`
![image](https://user-images.githubusercontent.com/43730756/164241568-bd6e5619-c060-4d4b-9395-5f49c92cb6d5.png)

**Comment by JPBeckner** [comment]
@kubouch sure, I can create an issue for the `main`.

About the `activate.nu`, I get this error:
```sh
/home/me/nu-report〉source ./venv/bin/activate.nu                                                                  04/20/2022 11:00:04 AM
Error: nu::parser::parse_mismatch (link)

  × Parse mismatch during operation.
   ╭─[activate.nu:1:1]
 1 │ # Setting all environment variables for the venv
 2 │ let path-name = (if ((sys).host.name == "Windows") { "Path" } { "PATH" })
   ·                                                    ─────┬────
   ·                                                         ╰── expected operator
 3 │ let virtual-env = "/home/joaobeckner/nu-report/venv"
   ╰────
```
![image](https://user-images.githubusercontent.com/43730756/164248123-3d3ab236-9f48-4b54-a056-c092fd4931af.png)

**Comment by kubouch** [comment]
Seems like you're using old version of virtualenv. The error points at syntax that looks like old Nushell. Upgrading virtualenv to the latest version should solve it.

**Comment by JPBeckner** [comment]
@kubouch it worked on the last version of virtualenv, thanks.
