### ISSUE TITLE
how to set up an alias?

### ISSUE THREAD

**Issue by kurokirasama** [nushell/nushell#5258]
Hello, I just testing nushell so please be patient...

Following the book example, `alias ll = ls -l` I tried:

`alias lt = ls | sort-by modified -r | sort-by type`

which gives me 

Error: nu::parser::unexpected_keyword (link)

```
  × Statement used in pipeline.
   ╭─[entry #7:1:1]
 1 │ alias lt = ls | sort-by modified -r | sort-by type
   · ──┬──
   ·   ╰── not allowed in pipeline
   ╰────
  help: 'alias' keyword is not allowed in pipeline. Use 'alias' by itself, outside of a pipeline.
```

Then I tried 
```
alias lt = 'ls | sort-by modified -r | sort-by type'`
```
that when run it gives me:
```
ls | sort-by modified -r | sort-by type
```

So I'm clearly missing something here.

Also, is there a way to make an alias persistent? The book says it should but couldn't find how...
Regards,

**Comment by kubouch** [comment]
You can define alias with pipes like this: `alias foo = (ls | get name)`

To make it persistent, put it in your `config.nu`.

**Comment by stormasm** [comment]
@kurokirasama Thanks for pointing this out to us 😄 

Thanks to you !  Next time you check the docs it hopefully will be much clearer for all of our future users....

https://www.nushell.sh/book/aliases.html#how-to-write-an-alias-with-pipes

**Comment by kurokirasama** [comment]
no problem!! I have an issue with an alias, I tried `alias gg = (ddgr -n 5)` but when used it gives me:
```
Error: nu::shell::external_command (link)

  × External command
   ╭─[entry #6:1:1]
 1 │ gg end of line regex
   · ─┬
   ·  ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)
```
but using `ddgr` directly works just fine.

**Comment by kurokirasama** [comment]
Also, is there a way to use bash `find` instead of nu `find`?

**Comment by kurokirasama** [comment]
@kubouch yes, I did reload the config files, I was testing them and so far the only issue is with `ddgr`. 
Thanks about the `^` tip.

And another issue:  I set up this alias `alias lt = (ls | sort-by modified -r | sort-by type)` that works but the output lost its coloring per file type.

**Comment by kubouch** [comment]
>  yes, I did reload the config file, I was testing them and so far the only issue is with ddgr.
That's strange, I use aliases to externals all the time and they work. Does it work without () -- just `alias gg = ddgr -n 5`? Do other aliases to externals work, like `alias gs = git status`, with and without ()?

> And another issue: I set up this alias alias lt = (ls | sort-by modified -r | sort-by type) that works but the output lost its coloring per file type.
This is a known issue, there are some commands that lose it but should be easy to fix. There is an open issue for that.

**Comment by kurokirasama** [comment]
OK, after some testing, this are the aliases that are not working, with or without `()`:

```
alias gg = ddgr -n 5
alias cpwd = (pwd | tr "\n" " " | sed "s/ //g" | xclip -sel clip)
alias supgrade = (echo "updating...";sudo aptitude update -y;echo "upgrading...";sudo aptitude safe-upgrade -y;echo "autoremoving...";sudo apt autoremove -y)
```
`gg nushell` gives me:
```
Error: nu::shell::external_command (link)

  × External command
   ╭─[entry #24:1:1]
 1 │ gg nushell | copy
   · ─┬
   ·  ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)
```

`cpwd` don't do anything, but it stays thinking... I have to `ctrl+c` it

If i put `supgrade` without `()`, nu start running the commands...

**Comment by kubouch** [comment]
@kurokirasama OK, that sounds weird. Could you take the above message and make it a bug report issue?

And as a side note, if you want to make a procedure, the preferred practice is to define a custom command with `def`, aliases are meant just for little shorthands but not really designed for defining long pipelines.

**Comment by kurokirasama** [comment]
@kubouch OK, I'll do that. With a `def` I could get `cpwd` y `supgrade` to work, so the  only issue is `ddgr`

**Comment by kurokirasama** [comment]
@kubouch could't find the issue for the coloring problem, would you mind to point me there please?
