### ISSUE TITLE
Ctrl C not working as expected

### ISSUE THREAD

**Issue by max-programming** [nushell/nushell#5261]
### Describe the bug

When I press Ctrl C to exit a process or stop a command, it shuts off `nu` completely and no interaction works

### How to reproduce

1. Run any command in my case `npx create-next-app myapp`
2. Hit Ctrl + C to stop the command further

### Expected behavior

I expected nu to stop the process simply like in Powershell or Command Prompt

### Screenshots

Current Behaviour:
![image](https://user-images.githubusercontent.com/51731966/164287700-212f2c55-76bc-4564-a8bd-b96b4016ab40.png)

Expected Behaviour:
![image](https://user-images.githubusercontent.com/51731966/164287678-1e3570c6-459d-4a2e-8310-cd91b3089dfc.png)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.0                                   |
| branch             |                                          |
| tag                |                                          |
| short_commit       | 3783c19d                                 |
| commit_hash        | 3783c19d02f4a3b2f35cd26b79daabcb70b04880 |
| commit_date        | 2022-04-12 20:38:15 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01)      |
| pkg_version        | 0.61.0                                   |
| build_time         | 2022-04-12 21:07:36 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by raboof** [comment]
Does ^C always have this effect or just for certain commands? For example I can abort `sleep 5000ms` or `^sleep 5` just fine.

I wonder if this might be related #4078, where I ran into some trouble aborting a command that uses various terminal features - perhaps nextapp uses those too?

**Comment by max-programming** [comment]
@raboof I'm not sure if it happens on all commands but ut definitely happens on commands that use `node` or `npm` `npx` etc. 

Do you know a different way the process can be stopped? An alternative to Ctrl C

**Comment by binyomen** [comment]
I'm also seeing this on Windows. Ctrl+C during `sleep` kills the shell. Same using the system's `tree` command. Weirdly it doesn't happen with `pause`, but it does seem to happen with most commands I've tried, including for loops.

Also if I run `cmd` from nu and then hit CTRL+C, it exits out of nu but leaves cmd running. 

This is the main blocker from me actually using nushell.

**Comment by elferherrera** [comment]
I found the same issue while integrating the new feature to open a file editor. It only happens in Windows. 
My guess is that it is related to crossterm. We will keep an eye on this one and see how we can fix it

**Comment by rgwood** [comment]
I'm unable to reproduce this on `main` (v70.1). I believe the issue is fixed, but just let me know if you're still experiencing it.

![image](https://user-images.githubusercontent.com/26268125/197375740-c196854f-5833-4b1e-9188-bfe16164b300.png)
