### ISSUE TITLE
drop behaves not as expected -> it removes items from the end instead of the start

### ISSUE THREAD

**Issue by thibran** [nushell/nushell#5262]
### Related problem

The commands `take` and `first` pick elements from the start of the input, but `drop` from the end. I was very surprised when I figured out that `drop` does not drop elements from the start too.

Background:
I wanted to split a file in two parts, the 'header' and the 'body' and therefor take the first line and all except the first two lines. The first command behaved as expected, the second not.

    > let header = (open ./foo.txt | lines | first)
    > let body = (open ./foo.txt | lines | drop 2)
    > $body
    ╭───┬───────────────────╮
    │ 0 │ This is my header │
    │ 1 │                   │
    ╰───┴───────────────────╯

The file structure was like this:
```
> open ./foo.txt
This is my header

Hello [User],
this is some text.
```

### Describe the solution you'd like

- `drop` should remove items from the start of the input by default
- `drop` should be extended with an `-r, --reverse` option

### Describe alternatives you've considered

Rename the command from `drop` to `drop-tail` to communicate more clearly what the command does.

**Comment by kubouch** [comment]
That's as expected. To skip items from the start, you can use `skip`.

**Comment by thibran** [comment]
I see, the Rust std uses the same [naming scheme](https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.skip). Maybe Rust uses `skip` because the name [drop](https://doc.rust-lang.org/std/ops/trait.Drop.html) had already a meaning?

For me, as Scheme (and Rust among others) user, I'm used to the drop-from-the-start behavior. The name `skip` is okay, but a bit hard to remember.

```
> (drop '(1 2 3 4) 2)
> (3 4)
```

Hopes this makes sense...

OT: I really love Nushell and use it quite a lot to manipulate csv and xls files.

**Comment by kubouch** [comment]
It is hard to come up with naming scheme that suits everybody since there is so many languages. For me, the current skip/drop seem natural. 

> OT: I really love Nushell and use it quite a lot to manipulate csv and xls files.

Thanks!

I'll close it for now since there does not seem to be a pressing reason to change the current skip/drop.

**Comment by thibran** [comment]
Now that I have thought about it a bit more, I think I would prefer another, more concise, a [Python slicing like](https://stackoverflow.com/questions/509211/understanding-slicing), solution.

If `get` supported ranges, we could write code like this:

```
# skip the first two items
open ./foo.txt | lines | get 2...
```

```
# all but the last line
open ./foo.txt | lines | get ...-1
```

This behavior could be supplementary to the existing solutions and would, at last for me, replace most of the functionality of `take`, `drop`, `skip`, `first` and `last`.

**Comment by thibran** [comment]
I'm sorry. I clicked the submit button almost at the same time as you closed the ticket.

**Comment by kubouch** [comment]
You can check the `range` command for selecting a range.

**Comment by thibran** [comment]
Ah, `range` is awesome. Strange that I missed it before.
