### ISSUE TITLE
how to output to /dev/null?

### ISSUE THREAD

**Issue by kurokirasama** [nushell/nushell#5269]
I tried for instace:
```
xdg-open file 2>/dev/null
```
But I got:
```
xdg-open: unexpected argument '2>/dev/null'
Try 'xdg-open --help' for more information.
```

**Comment by jntrnr** [comment]
`| ignore` and `do -i {... } | ignore` should ignore output

**Comment by kurokirasama** [comment]
thanks!! what is the equivalent in nu for  & at the end of a command in bash?

**Comment by fdncred** [comment]
my bash is rusty but if the `&` means to launch the process in the background, we don't have job handling like that in nushell yet. there may be some hacks around that but I can't think of them.  you might want to join our discord community to ask questions. there's a link in our readme.

**Comment by flying-sheep** [comment]
I’d use a dedicated tool for running jobs, like tmux/byobu
