### ISSUE TITLE
how to short the path on shell

### ISSUE THREAD

**Issue by kurokirasama** [nushell/nushell#5270]
Is there a way to not show full path in shell, just the current dir. I.e, from
```
/home/current/path>
```
to
```
path>
```

Also, I cloned the repo and I'm using nu executable from `/target/debug/nu`, is that ok? 
And, how to upgrade? clone the repo and recompile?

**Comment by fdncred** [comment]
For questions like this please join discord. There are a few people who watch issues and a few hundred on discord.
