### ISSUE TITLE
Wrong error message when using a script as a module

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#5275]
### Describe the bug

`use`-ing a script as a module gives an unhelpful error.

### How to reproduce

Have a `foo.nu` file:
```
# foo.nu
echo foo
```

Then:
```
use foo.nu *
Error: nu::parser::unexpected_keyword (https://docs.rs/nu-parser/0.61.1/nu_parser/enum.ParseError.html#variant.UnexpectedKeyword)

  × Unexpected keyword.
   ╭─[foo.nu:1:1]
 1 │ echo foo
   · ──┬─
   ·   ╰── unexpected expected def or export keyword
   ╰────
  help: 'expected def or export keyword' keyword is allowed only in a module.
```

### Expected behavior

The error message is confusing. Probably a wrong error type was selected.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.1                                   |
| branch             | main                                     |
| tag                |                                          |
| short_commit       | e97ba9b7                                 |
| commit_hash        | e97ba9b74c607b1b23f4bda84a90303bc66b3bed |
| commit_date        | 2022-04-20 16:48:32 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)        |
| pkg_version        | 0.61.1                                   |
| build_time         | 2022-04-20 23:08:26 +03:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  | gstat                                    |

### Additional context

The solution would be to select the right ParseError.

**Comment by Caedan** [comment]
Hey, new contributor here and eager to get my hands dirty! Could I pick this up?

**Comment by kubouch** [comment]
@Caedan Sure, go ahead! You'll probably want to look at `parse.rs` or `parse_keywords.rs` and grep for "expected def or export keyword" to see where the error is created.

**Comment by theAkito** [comment]
The fixed message is still extremely confusing. It would help, if the message would indicate, that a script must not be used as a module. For users unfamiliar with the concept it might even help to make clear, that certain statements make the file a script rather than a usable module.

The error makes it seem like the user has made a syntax error on a statement/expression level rather than looking at the bigger scope of modules and scripts.

It also does not help, that the following line is missing now.

```
help: 'expected def or export keyword' keyword is allowed only in a module.
```

The new error does not offer any usable information for someone unfamiliar with this problem.

**Comment by BatmanAoD** [comment]
I agree the current error message is still very confusing. I was setting up config for Starship and Carapace; Starship recommends `use`, while Carapace recommends `source`, and I didn't notice they were different so I wrote `use` for both.

**Comment by dougg0k** [comment]
Some very confusing messages are still happening in this regard, but I understood.

There is a few scenarios I have ran into, while building some scripts.

---

Nushell require compile time checks, so if a file that you want to import, by `use` or `source` or `source-env` does not yet exist. You can create an empty module file and do a check before passing into one of the import commands.

```
const PATH = if ($filepath | path expand | path exists) {
	$filepath
} else {
	$EMPTY_SCRIPT
}
use $PATH
```

---

Another one

To use the `use` command, you cannot have straight commands written at the file, it needs to be `def` or `defs` in a `module`.
Using the `source` command would work, but that runs the whole file. So, it could have indesirable results.

What to do?

- Build files with straight commands that you want all to be run, using `source`
- Build module files that you want to specifically import certain things with `use`. Think a bit differently than when used to, while building scripts.
