### ISSUE TITLE
Using open on a file with no trailing new line doesn't print the last line until something else outputs something

### ISSUE THREAD

**Issue by horros** [nushell/nushell#5277]
### Describe the bug

Using open on a text file with one or more lines but without a trailing NL/CRLF causes the last line to not be printed until something else outputs something. Hitting enter does not show it, but running eg. ```ls``` does. The line that wasn't printed is now printed and breaks the output from ```ls```

### How to reproduce

1. Create a text file with a line that doesn't end in CRLF
2. Use open on the file

### Expected behavior

I expected the line to be printed

### Screenshots

![Screenshot 2022-04-21 114705](https://user-images.githubusercontent.com/464166/164417064-f66ec04f-d20f-4696-b340-a21ca4e03d15.png)

### Configuration

```C:\test〉version | transpose key value | to md --pretty```
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.0                                   |
| branch             |                                          |
| tag                |                                          |
| short_commit       | 3783c19d                                 |
| commit_hash        | 3783c19d02f4a3b2f35cd26b79daabcb70b04880 |
| commit_date        | 2022-04-12 20:38:15 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01)      |
| pkg_version        | 0.61.0                                   |
| build_time         | 2022-04-12 21:07:36 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I'm guessing you could probably check for this newline behavior in the source code to the open command and fix this.

**Comment by rgwood** [comment]
I can't reproduce it on Linux. This might be fixed, or it might be a Windows-specific bug.
![image](https://user-images.githubusercontent.com/26268125/165430066-718fe4ae-c5db-4082-a3e0-5036f8a02a34.png)

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.1                                   |
| branch             | fix-open-newline                         |
| tag                |                                          |
| short_commit       | f2a45b3e                                 |
| commit_hash        | f2a45b3eacc69e8f36d2fd49d04aa9ff249d005c |
| commit_date        | 2022-04-24 13:03:21 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)        |
| pkg_version        | 0.61.1                                   |
| build_time         | 2022-04-26 10:04:47 -07:00               |
| build_rust_channel | debug                                    |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I've seen something similar to this with reedline https://github.com/nushell/reedline/issues/398. This is kind of more evidence that it is an issue only present on windows.

<img width="854" alt="Screen Shot 2022-04-27 at 6 21 53 AM" src="https://user-images.githubusercontent.com/343840/165507592-4f41b1df-26eb-4779-92a7-daf82ef5ba63.png">

**Comment by anicetrip** [comment]
I"m totally a green hand and I tried from 0.40 to the newest version, this problem happened after 0.6.0 released, in previous versions it works well. (Maybe not so helpful)

**Comment by anicetrip** [comment]
I guess I found the position of the bug but I can't fix it,  I'm a totally green hand. I step by step printed everything I think related to this bug and found this:
![windows_problem_nu](https://user-images.githubusercontent.com/41963236/167027289-f55702fe-68c9-41e6-9ad1-500de47da06a.png)

The test file is like this with  LF
This is an test
for windows
and you

And `let _ = stdout.lock().write_all(s?.as_binary()?);` seems use the windows IO, which make this problem. The file name is look like `@NtWriteFile`
Im not 100% sure, so following is only my guess.
In open.rs, it is only a pointer with a buffer, and send to eval to do some work, then it is sent to some place to transfer from another type to utf8, maybe we can change \n to \r\n at nu-protocol | src | value | stream.rs | next.

**Comment by ricardoCMonteiro** [comment]
I could not reproduce it on version 0.70.0
