### ISSUE TITLE
filename coloring lost when name uses two rows and it have spaces

### ISSUE THREAD

**Issue by kurokirasama** [nushell/nushell#5288]
### Describe the bug

If the filename is to long and have spaces and it uses more than 1 row, only the first row of the name keep its coloring.

### How to reproduce

Reduce the size of your terminal
Execute:
```
touch "very long filename that doesnt fit in a single row aaaaaaaaaaaaaaaaaaaaaaaaaaaaa.txt"
ls
```

### Expected behavior

the whole filename should be colored

### Screenshots

![nushell](https://user-images.githubusercontent.com/5784951/164589328-1d5d6a84-c2ee-449d-bf17-a34e34f8aa1e.png)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.1                                   |
| branch             | main                                     |
| tag                |                                          |
| short_commit       | f2d47f97                                 |
| commit_hash        | f2d47f97da15e52248dd285c8ba0e1bd37dd4de3 |
| commit_date        | 2022-04-19 19:11:58 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)        |
| pkg_version        | 0.61.1                                   |
| build_time         | 2022-04-20 22:11:45 -04:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by jaeheonji** [comment]
I just checked it out. It looks like we need to check more, but for now, version 0.62 seems to have fixed this issue.

**Comment by kurokirasama** [comment]
I can confirm too, Working for me

**Comment by hustcer** [comment]
Works now
