### ISSUE TITLE
cd with tab auto-fill when there is only one directory match.

### ISSUE THREAD

**Issue by WindSoilder** [nushell/nushell#5289]
### Related problem

![unknown](https://user-images.githubusercontent.com/22256154/164643598-cb2c28e5-0aea-4011-8110-bbdb5574da27.png)

When enter `cd te` and hit `tab`, I see `./test` and `./test2` both prompt out to let user select one.

### Describe the solution you'd like

Just expect `./test` to be auto-filled, because `./test2` is not directory, `./test` is the only choice.   That's how zsh, fish, bash works, and I believe it can make nu more friendly to user.

**Comment by fdncred** [comment]
When discussing this on Discord, this was JT's comment in case anyone wants to try to add this functionality.

JT said, "right now I think the shape is "filepath" but we could add a directory SyntaxShape and make completions work a little differently".

**Comment by herlon214** [comment]
This was fixed by https://github.com/nushell/nushell/issues/5289, can you test with the latest main @WindSoilder?

**Comment by WindSoilder** [comment]
@herlon214 Thanks, it works fine for me, I miss it very much :-D
