### ISSUE TITLE
Using nu for makefiles

### ISSUE THREAD

**Issue by emm312** [nushell/nushell#5313]
### Describe the solution you'd like

When you run makefiles, it runs the commands in nushell. I think this would improve the sanity of windows users so we dont have to switch to wsl.

**Comment by Yethal** [comment]
Make already supports this
https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html

**Comment by hustcer** [comment]
> Make already supports this https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html

Please set the shell by following the above guide.
