### ISSUE TITLE
Config variables are not available in `EngineState` in repl

### ISSUE THREAD

**Issue by Tropid** [nushell/nushell#5314]
### Describe the bug

SInce commit 76079d518354922724ebb775e886d879fb4f7fee the config/EngineState in `evaluate_repl` does not use values specified in the default `config.nu` file.

### How to reproduce

1. Set `use_ansi_coloring` to `false` in the `config.nu` file
2. Run the shell: `cargo run`
3. Execute `ls` or some other command which shows colors

### Expected behavior

The colors should not be visible because the config value was set to `false`. This worked in the parent commit 409f1480f5e8d89d1b1d3dc958d1db49b1bc668f.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.1                                   |
| branch             | HEAD                                     |
| tag                |                                          |
| short_commit       | 76079d51                                 |
| commit_hash        | 76079d518354922724ebb775e886d879fb4f7fee |
| commit_date        | 2022-04-18 22:28:01 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)      |
| pkg_version        | 0.61.1                                   |
| build_time         | 2022-04-24 16:02:39 +02:00               |
| build_rust_channel | debug                                    |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

### Additional context

Debug printing the `engine_state` inside the loop in the `evaluate_repl` function in `repl.rs` right before the creation of the `NuHighlighter`, `NuValidator`, `NuCompleter` shows that the config values are not available there.
`echo $config` shows the correct values, though.

**Comment by fdncred** [comment]
If you change your `let = config` to `let-env config` the config should work.

**Comment by kubouch** [comment]
config is now an environment variable

**Comment by Tropid** [comment]
This explains so much, thank you. I'm gonna close this issue. It would be great if this is announced very prominently with the next release notes.
