### ISSUE TITLE
cp ignores trailing slash

### ISSUE THREAD

**Issue by dvc94ch** [nushell/nushell#5316]
### Describe the bug

```
cp file dir_that_doesnt_exist/
```

### How to reproduce

creates a file called dir_that_doesnt_exist

### Expected behavior

should produce an error

**Comment by onthebridgetonowhere** [comment]
@dvc94ch thanks for reporting this. Could you add info regarding your configuration? (run the `version` command and it will output all the needed stuff). On version 0.61.1 I get an error if I try to copy a file to a non existing directory, so we need to know which version you are running.

**Comment by dvc94ch** [comment]
sorry, my bug report was wrong. it only happens when a `~` is used:

```
❯ ls /tmp/test
Error: nu::shell::directory_not_found (https://docs.rs/nu-protocol/0.61.0/nu_protocol/enum.ShellError.html#variant.DirectoryNotFound)

  × Directory not found
   ╭─[entry #29:1:1]
 1 │ ls /tmp/test
   ·    ────┬────
   ·        ╰── directory not found
   ╰────


/tmp
❯ cp a_file  ~/../../tmp/test/

/tmp
❯ ls /tmp/test
╭───┬───────────┬──────┬──────┬──────────╮
│ # │   name    │ type │ size │ modified │
├───┼───────────┼──────┼──────┼──────────┤
│ 0 │ /tmp/test │ file │  0 B │ now      │
╰───┴───────────┴──────┴──────┴──────────╯

/tmp
```

I'm using version 0.61.0 distributed with arch linux

**Comment by onthebridgetonowhere** [comment]
Thanks! I am able to reproduce this on Windows as well.

**Comment by onthebridgetonowhere** [comment]
This seems to be related to the `strip_prefix` of Path types, which removes the trailing slash. Not clear yet how to distinguish a file from a folder when `~` paths are parsed and expanded.

**Comment by kendfss** [comment]
> This seems to be related to the `strip_prefix` of Path types, which removes the trailing slash. Not clear yet how to distinguish a file from a folder when `~` paths are parsed and expanded. 

sorry if i misunderstood, but it sounds like if there was a version of strip_prefix that only stripped *the prefix*, there would be enough information to make the assumption.
if the `source` arg is a dir, then you can assume that the `destination` should be too. 
if it is a file, then the trailing slash should be enough.

**Comment by onthebridgetonowhere** [comment]
> > This seems to be related to the `strip_prefix` of Path types, which removes the trailing slash. Not clear yet how to distinguish a file from a folder when `~` paths are parsed and expanded.
> 
> sorry if i misunderstood, but it sounds like if there was a version of strip_prefix that only stripped _the prefix_, there would be enough information to make the assumption. if the `source` arg is a dir, then you can assume that the `destination` should be too. if it is a file, then the trailing slash should be enough.

` if the source arg is a dir, then you can assume that the destination should be too.` yes, that should be like that. But the way the paths are parsed and expanded is rather complicated. 

But if you're trying to copy a file to a destination that you think is a directory, and that directory does not exist, nu has to figure out that you're wanting to copy to a directory, right?

**Comment by dvc94ch** [comment]
It's also because it's redundant from a os view point. I think what you want to do is parse and manipulate it as a String. The other problem with using Paths in nu is that they behave different on Linux/windows. How does nu deal with non utf8 paths anyway? Pretty sure you want to write your own abstraction.
