### ISSUE TITLE
Crash when running query web -i

### ISSUE THREAD

**Issue by Yethal** [nushell/nushell#5319]
### Describe the bug

Nushell crashes with following stacktrace when piping into query web -i with no other parameters

`thread 'main' panicked at 'this should never trigger: ParseError { kind: Custom(EmptySelector), location: SourceLocation { line: 0, column: 1 } }', /home/yethal/.cargo/registry/src/github.com-1ecc6299db9ec823/nu_plugin_query-0.61.0/src/query_web.rs:276:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error:
  × Unable to decode call for query web
   ╭─[entry #5:1:1]
 1 │ fetch https://google.com|query web -i
   ·                          ────┬────
   ·                              ╰── Plugin failed to encode: EOF while parsing a value at line 1 column 0
   ╰────`

### How to reproduce

1. `fetch https://google.com|query web -i`

### Expected behavior

I expected nu not to crash

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.61.0                                              |
| branch             |                                                     |
| tag                |                                                     |
| build_os           | linux-x86_64                                        |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)                 |
| rust_channel       | stable-x86_64-unknown-linux-gnu                     |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)                 |
| pkg_version        | 0.61.0                                              |
| build_time         | 2022-04-13 15:59:24 +02:00                          |
| build_rust_channel | release                                             |
| features           | dataframe, default, trash, which, zip               |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by fdncred** [comment]
hmmm... I get something different
```
> fetch https://google.com | query web -i
Error:
  × requires text input
   ╭─[entry #8:1:1]
 1 │ fetch https://google.com | query web -i
   ·                            ────┬────
   ·                                ╰── Expected text from pipeline
   ╰────

```

**Comment by Yethal** [comment]
@fdncred I just checked and it doesn't occur on google's page anymore for some reason but regular websites still trigger this behavior, try this:
`fetch https://example.com | query web -i`

**Comment by fdncred** [comment]
Love the error - 'this should never trigger' LOL

```
> fetch https://example.com | query web -i 
thread 'main' panicked at 'this should never trigger: ParseError { kind: Custom(EmptySelector), location: SourceLocation { line: 0, column: 1 } }', crates/nu_plugin_query/src/query_web.rs:276:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error:
  × Unable to decode call for query web
   ╭─[entry #9:1:1]
 1 │ fetch https://example.com | query web -i
   ·                             ────┬────
   ·                                 ╰── Plugin failed to encode: EOF while parsing a value at line 1 column 0
   ╰────
```
Agreed that this shouldn't happen. We would accept a PR to fix it.

**Comment by fdncred** [comment]
I see what's going on. I think the `--inspect` flag is only appropriate for `--as-table`. It fails because the `selector` string is empty. Maybe I can just hard code some default `selector` like `html`, which hopefully will appear in all web pages.
