### ISSUE TITLE
Make it possible to edit the current command in an editor

### ISSUE THREAD

**Issue by emchristiansen** [nushell/nushell#5329]
### Related problem

I have a workflow where I essentially store lots of small scripts in my ZSH history. For example, I have a script to build and test a set of binaries, and the script is maybe 20 lines. Because I have several projects with similar layouts, it's quick for me to create a new project, reverse search to find a command (script) similar to the one I want, quickly edit it in VIM, and then run it.

### Describe the solution you'd like

Make it possible to edit the current command in an editor (e.g. VIM).
I.e. add support for something like ZSH's `edit-command-line`, bound to a keyboard shortcut.

### Describe alternatives you've considered

I've tried a workflow where I instead write the scripts to files, but it's just much faster for certain kinds of commands to not have to do that. Plus I benefit from having all the versions of the script stored in my history, rather than having to track versions of the script file using git (slow).

### Additional context and details

Unfortunately, Nushell's lack of support for something like `edit-command-line` is a deal-killer for me. Please add support!

**Comment by kubouch** [comment]
You mean opening an editor and typing the command line entry there? That's interesting. This issue is probably better suited for https://github.com/nushell/reedline which is our line editor.

We already have multi-line editing enabled so one way to go is to further improve it.

**Comment by emchristiansen** [comment]
That's right - it's a very useful feature for me.

I couldn't find a great description of it to put here, but here's a GIF that shows the basic idea:
https://dev.to/chhajedji/bash-edit-command-in-your-editor-and-execute-directly-30ef

FYI, I've raised this issue in reedline here:
https://github.com/nushell/reedline/issues/409

**Comment by elferherrera** [comment]
#5381 should do the trick
