### ISSUE TITLE
generating tables from external sources

### ISSUE THREAD

**Issue by jlgerber** [nushell/nushell#5339]
I have a python script which prints data to stdout and it looks exactly like the documented format for tables. However, it does not generate a table. Likewise, when capturing the output to a variable and subsequently echoing the contents of the variable - no luck. Is this supposed to work? I am printing to stdout without a trailing carriage return. Is there something else required?

**Comment by rgwood** [comment]
Hi, it's hard to know exactly what you're trying without seeing an example. But generally the easiest way to create a Nu table from text is by using one of the `from` commands (type `help from` to see them all). For example:

```
python3 my_python_script_that_returns_json.py | from json
```

**Comment by fdncred** [comment]
@jlgerber if you want to generate a table in nushell from an external source there are a few ways to do it.

1. use data that is represented by a table like .csv, .yaml, .toml, .json
2. use data that uses record literals like `{ key: a value: 1 }` and wrap it in brackets like `[{ key: a value: 1}`
3. use data that uses table literals like `[[key value]; [a 1]]`
4. use data that is spatially delimited and then use `from ssv` or `detect columns`

**Comment by jlgerber** [comment]
so for #2 / #3 how does one convert a string into record or table literals?

**Comment by jlgerber** [comment]
as a concrete example, here is what i am printing to stdout
```
[{'type': 'Asset', 'id': 13064, 'code': 'Book Illustration'}]
```
