### ISSUE TITLE
table column alignment issue when providing inconsistent table data

### ISSUE THREAD

**Issue by jlgerber** [nushell/nushell#5340]
### Describe the bug

I am converting a list of objects into a table in json form, and some of the records' fields are missing. Nushell seems to handle this gracefully, inserting a '❎' where the data is missing. However, the justification is messed up a bit; the column lines shift leftward wherever the ''❎'' occupies a field.
 I am using a mono font and have tried switching between various mono fonts but that has no effect. Is there a way of configuring the character used to indicate missing data? I would just as soon insert a blank character, which appears to happen if I explicitly select fields...

### How to reproduce

1. write a script which returns a list of json objects with inconsistent fields
2. pipe the script to ```from json```

### Expected behavior

Missing field data would not cause column justification issues. 

### Configuration

version | transpose key value | to md --pretty                                                                                                                                                                                                 
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.1                                   |
| branch             |                                          |
| tag                |                                          |
| short_commit       | 53195444                                 |
| commit_hash        | 5319544481f93fc5265bab02ff709d7a07f3aded |
| commit_date        | 2022-04-26 19:20:59 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)        |
| pkg_version        | 0.61.1                                   |
| build_time         | 2022-04-26 14:31:03 -07:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |

**Comment by fdncred** [comment]
please join discord for questions.

**Comment by jlgerber** [comment]
This seems like a bug rather than a question. It should maintain alignment regardless, should it not?

**Comment by jntrnr** [comment]
@jlgerber do you have a screenshot of what it looks like?

Also, which terminal do you use? I think some terminals may render it differently.

**Comment by fdncred** [comment]
As discussed on Discord, rendering issues like this are usually on the terminal side as each terminal interprets characters differently. I've tried a half dozen different terminal emulators and they all render things differently. If you want to test this, open the emoji-gh.json file in the nu_scripts repo. Column alignment is all over the places because emojis are difficult for terminals to interpret. Right now I'm using Wezterm and it's character rendering is one of the best that I've seen, but still has issues. So, for those reasons, I don't consider this a bug.
