### ISSUE TITLE
In some circumstances, `.nu` script doesn't print child process' stdout

### ISSUE THREAD

**Issue by 0x009922** [nushell/nushell#5363]
### Describe the bug

With such a script:

```nu
def main [] {
    if false {
    } else if true {
        ./whatever
    }
}
```

You will not see an output of `./whatever` until its exit.

### How to reproduce

[Repo](https://github.com/0x009922/nu-issue-eaten-stdout).

1. Run `nu start.nu`
2. See that you don't see the output of long-running child `nu looper.nu` process
3. <kbd>Ctrl+C</kbd>
4. Now you see all its accumulated output.

### Expected behavior

Expected to see child process' output on-demand.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.61.0                              |
| branch             | master                              |
| tag                |                                     |
| build_os           | linux-x86_64                        |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)   |
| pkg_version        | 0.61.0                              |
| build_time         | 2022-04-29 09:03:02 +03:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |

### Additional context

More about the context you can find in this discussion: #5353

**Comment by fdncred** [comment]
Thanks for the minimal repro. What is odd is that this works.

```
ef main [] {
    if false {
    } else {
        ./whatever
    }
}
```
for me, it's the `else if true` that doesn't work. It appears to be related to the nested if.

**Comment by rgwood** [comment]
I've also noticed odd behavior with `else if`, might be related: https://github.com/nushell/nushell/issues/5088

**Comment by jntrnr** [comment]
@0x009922 @fdncred - can you see if https://github.com/nushell/nushell/pull/5386 fixes the issue for you?

**Comment by fdncred** [comment]
@jntrnr still no output when run like this.

```
> vi foo.nu

def main [] {
    if false {
    } else if true {
        http
    }
}

> nu foo.nu
```

I expect output similar to this.
```
Hosting "." on port 8000 without TLS and no authentication...
Ctrl-C to stop.

[2022-04-30 16:46:04] 127.0.0.1:58384 was served directory listing for /Users/fdncred/src/forks/nushell
[2022-04-30 16:46:04]                           encoded as gzip for 375.7% ratio
```

**Comment by fdncred** [comment]
I just tested the script like this and it works.

```
> source foo.nu
> main
Hosting "." on port 8000 without TLS and no authentication...
Ctrl-C to stop.

[2022-04-30 16:50:38] 127.0.0.1:58391 was served directory listing for /Users/fdncred/src/forks/nushell
[2022-04-30 16:50:38]                           encoded as gzip for 375.7% ratio
[2022-04-30 16:50:40] 127.0.0.1:58391 was served directory listing for /Users/fdncred/src/forks/nushell/foo
[2022-04-30 16:50:40]                           encoded as gzip for 335.1% ratio
[2022-04-30 16:50:41] 127.0.0.1:58391 was served directory listing for /Users/fdncred/src/forks/nushell
[2022-04-30 16:50:41]                           encoded as gzip for 375.7% ratio (cached)
^C
```

So, it must work differently when running it like `nu foo.nu` and implicitly calling main.

**Comment by jntrnr** [comment]
@fdncred - both examples you give work the same for me. Can you confirm the first example is using the latest `nu` from main? Also which OS are you on?

**Comment by fdncred** [comment]
@jntrnr confirmed. I tried again this morning on the latest main and it behaves the same. right now I'm testing on macOS. I do `nu foo.nu` and see nothing, then when I hit ctrl-c, all the log messages appear. if I do `source foo.nu` and run `main`, it works as expected.

**Comment by jntrnr** [comment]
this should now be fixed - spoke to @fdncred offline and he confirmed he was missing a step during testing. Should work now.
