### ISSUE TITLE
Variable Completion Wrong

### ISSUE THREAD

**Issue by gipsyh** [nushell/nushell#5364]
### Describe the bug

after typing `$env.HOME.` and pressing `tab`, the completion prompt is wrong. 

### How to reproduce

1. input `$env.HOME.`
2. press `tab`

### Expected behavior

no completion prompt

### Screenshots

<img width="882" alt="截屏2022-04-29 14 45 51" src="https://user-images.githubusercontent.com/42509521/165896858-a5919e2b-3687-41f1-9d87-7a991c02ad7a.png">

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.1                                   |
| branch             | main                                     |
| tag                |                                          |
| short_commit       | b4f8798a                                 |
| commit_hash        | b4f8798a3adb071d761dbeac9efa3e885c6eeeb2 |
| commit_date        | 2022-04-28 22:57:26 +00:00               |
| build_os           | macos-aarch64                            |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-aarch64-apple-darwin              |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01)      |
| pkg_version        | 0.61.1                                   |
| build_time         | 2022-04-29 09:25:40 +08:00               |
| build_rust_channel | debug                                    |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
@herlon214 any ideas about this?

**Comment by herlon214** [comment]
I was checking the code, looks like we just check if it starts with $env and return the env vars, so it would basically always return.
I will take a look as soon as I have some free time

**Comment by fdncred** [comment]
Thanks. We appreciate your help.
