### ISSUE TITLE
Commands with double quoted arguments not handled properly on Windows

### ISSUE THREAD

**Issue by interob** [nushell/nushell#5366]
### Describe the bug

Calling a Windows batch script from prompt like so...
`.\my_batch.bat "Quoted argument with spaces"`

... yields the following output when the script outputs positional parameters 1 - 5:
```
1: "\"Quoted
2: argument
3: with
4: spaces\""
5:
```
### How to reproduce

1. Create a my_batch.bat script:
```
@echo off
echo 1: %1
echo 2: %2
echo 3: %3
echo 4: %4
echo 5: %5
```

2. Run it: 
`.\my_batch.bat "Quoted argument with spaces"`

### Expected behavior

I expected Nu to parse the full string, without double quotes, into the first positional parameter: `%1`. Output:
```
1: Quoted argument with spaces
2:
3:
4:
5:
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.0                                   |
| branch             |                                          |
| tag                |                                          |
| short_commit       | 3783c19d                                 |
| commit_hash        | 3783c19d02f4a3b2f35cd26b79daabcb70b04880 |
| commit_date        | 2022-04-12 20:38:15 +00:00               |
| build_os           | windows-x86_64                           |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01)      |
| pkg_version        | 0.61.0                                   |
| build_time         | 2022-04-12 21:07:36 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

**Comment by jntrnr** [comment]
This may be coming from how we invoke cmd.exe, which we'll do because this is a .bat file.
