### ISSUE TITLE
Glob doesn't seem to search within nested directories

### ISSUE THREAD

**Issue by JosephTLyons** [nushell/nushell#5376]
### Describe the bug

Glob only seems to search the current directory and does not seem to search within nested ones.  As a note, glob uses uses usize::MAX for the depth limit if the user doesn't supply a depth limit.

### How to reproduce

Perform and glob search in a directory that has things that would match the search in nested directories

### Expected behavior

I expect glob to grab all matches in nested directories

**Comment by jntrnr** [comment]
Can you give an example of what you tried?

**Comment by JosephTLyons** [comment]
> Can you give an example of what you tried?

```shell
/Users/josephlyons/Desktop/rust_temp/nushell〉glob *.rs                              04/29/2022 06:05:13 PM
╭───┬───────────────────────────────────────────────────────╮
│ 0 │ /Users/josephlyons/Desktop/rust_temp/nushell/build.rs │
╰───┴───────────────────────────────────────────────────────╯
/Users/josephlyons/Desktop/rust_temp/nushell〉glob *.rs --depth 10                   04/29/2022 06:26:28 PM
╭───┬───────────────────────────────────────────────────────╮
│ 0 │ /Users/josephlyons/Desktop/rust_temp/nushell/build.rs │
╰───┴───────────────────────────────────────────────────────╯
```

**Comment by JosephTLyons** [comment]
Ah, I think I see what I did wrong
