### ISSUE TITLE
Interrupting (Ctrl+C) a for-loop over a list behaves differently from a for-loop over a range

### ISSUE THREAD

**Issue by exit91** [nushell/nushell#5378]
### Describe the bug

When interrupting a for-loop over a range (e.g. `1..100`), the loop stops executing it's body (as expected).

However, when interrupting a for-loop over a list (e.g. `(seq 1 100)`), the loop continues to execute it's body until the very end while seemingly ignoring any subsequent calls to `sleep` which may be contained in the loop body.

### How to reproduce

With range:

```
〉for $i in 1..10 { echo $i; sleep 1sec }
1
2
^C
〉
```

With list:

```
〉for $i in (seq 1 10) { echo $i; sleep 1sec }
1
2
^C3
4
5
6
7
8
9
10
〉
```

### Expected behavior

The for-loop over the list should behave the same as the for-loop over the range.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.61.0                              |
| branch             | master                              |
| tag                |                                     |
| build_os           | linux-x86_64                        |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)   |
| pkg_version        | 0.61.0                              |
| build_time         | 2022-04-28 10:08:43 +02:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |

### Additional context

This might be related to other `Ctrl+C` related issues, in particular https://github.com/nushell/nushell/issues/5362

**Comment by hustcer** [comment]
Confirm closed by https://github.com/nushell/nushell/pull/5408
