### ISSUE TITLE
`nu -c "echo \"foo bar\""` fails when run inside nushell

### ISSUE THREAD

**Issue by uasi** [nushell/nushell#5383]
### Describe the bug

```
〉nu -c "echo \"foo bar\""
Error: nu::parser::unexpected_eof (https://docs.rs/nu-parser/0.61.0/nu_parser/enum.ParseError.html#variant.UnexpectedEof)

  × Unexpected end of code.
   ╭─[source:1:1]
 1 │ echo \"foo bar\"
   ·                 ▲
   ·                 ╰── expected closing "
   ╰────
```

---

It works outside of nushell:

```
bash-3.2$ nu -c "echo \"foo bar\""
foo bar
```

Other builtin commands parse escaped double quotes without problem:

```
〉echo "echo \"foo bar\""
echo "foo bar"
```

### How to reproduce

Run `nu -c "echo \"foo bar\""` inside nushell.

### Expected behavior

```
〉nu -c "echo \"foo bar\""
foo bar
```

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.61.0                                |
| branch             |                                       |
| tag                |                                       |
| build_os           | macos-x86_64                          |
| rust_version       | rustc 1.59.0                          |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.61.0                                |
| build_time         | 2022-04-12 20:38:15 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

**Comment by jntrnr** [comment]
this should now be fixed
