### ISSUE TITLE
Windows completion of file names with quotes leads to double quoting 

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#5411]
### Describe the bug

You have a file named "this is 123   a long file  name with variable    spacing.pdf". You try to complete it with `command this<tab>` and it doesn't work right.

### How to reproduce

1. Create the file listed above and cd to the folder with that file in nushell
2. type `open -r this<tab>` and it double quotes the filename with backticks then single quotes

### Expected behavior

`ls` just to show what the folder looks like
`open -r this<tab>` and note the double quoting at the beginning and ending (note there's a separate bug with the text file not being highlighted correctly after wrapping)
![image](https://user-images.githubusercontent.com/343840/166246227-bd66de73-c5f2-4799-bab4-949c6b0c3644.png)
^ the first item is a folder named `Reports for Chris`, it is shown because i have `completion_algorithm: "fuzzy"` set in my config.nu and "Reports for Chris" has the string `this` contained in those letters.

after selecting a `this` filename
![image](https://user-images.githubusercontent.com/343840/166246375-5e0b4491-7a8e-4360-ae3b-63a2e1815099.png)

and just to finish the thought add the hash command i hit enter and get. then i remove either of the double quoting and it appears to work.
![image](https://user-images.githubusercontent.com/343840/166246667-9d6b65df-e1de-47f1-bbad-34165e7dabca.png)

### Screenshots

see above

### Configuration

|key|value|
|-|-|
|version|0.61.1|
|branch||
|tag||
|short_commit|e7831d38|
|commit_hash|e7831d38aed5efb7f97ecaa3e6d8265ef0122fb6|
|commit_date|2022-04-27 12:38:36 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.60.0 (7737e0b5c 2022-04-04)|
|rust_channel|stable-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.60.0 (d1fd9fe2c 2022-03-01)|
|pkg_version|0.61.1|
|build_time|2022-04-27 14:23:54 -05:00|
|build_rust_channel|debug|
|features|database, dataframe, default, trash, which, zip|
|installed_plugins|gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml|

**Comment by hustcer** [comment]
Can this issue be closed after : https://github.com/nushell/nushell/pull/5419 ?

**Comment by fdncred** [comment]
Yes. Thanks.
