### ISSUE TITLE
Long file names with wrapping can break coloring

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#5412]
### Describe the bug

A very long text file can break coloring when wrapped. It looks like it has something to do with spaces in the file name.

### How to reproduce

1. Create the filenames in the screenshot below
2. Make sure your terminal window is small enough to wrap
3. do a ls in nushell

### Expected behavior

retain coloring

### Screenshots

![image](https://user-images.githubusercontent.com/343840/166247670-1ea70924-b42d-46d0-978a-7a6a93eb1736.png)

### Configuration

|key|value|
|-|-|
|version|0.61.1|
|branch||
|tag||
|short_commit|e7831d38|
|commit_hash|e7831d38aed5efb7f97ecaa3e6d8265ef0122fb6|
|commit_date|2022-04-27 12:38:36 +00:00|
|build_os|windows-x86_64|
|rust_version|rustc 1.60.0 (7737e0b5c 2022-04-04)|
|rust_channel|stable-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.60.0 (d1fd9fe2c 2022-03-01)|
|pkg_version|0.61.1|
|build_time|2022-04-27 14:23:54 -05:00|
|build_rust_channel|debug|
|features|database, dataframe, default, trash, which, zip|
|installed_plugins|gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml|

**Comment by jntrnr** [comment]
did we stop using ansi cut?

**Comment by sholderbach** [comment]
We still do, I think @zhiburt updated bits of `ansi-cut`'s API and then contributed back adjustements to our wrapping logic. The last change in `/nu-table/src/wrap.rs` was when I improved the performance by only stripping ANSI when there is ANSI. but this should only affect the reference string.

**Comment by zhiburt** [comment]
Hi there I am not sure what the issue is here.

But according to `ansi-cut`.
I've noticed some flaws in it a couple of month ago (hard to remember what it was).

Therefore a https://crates.io/crates/ansi-str was created as a re-visioned version of ansi-cut.

I was thinking to ping you back in the day.
But decided to let it go :disappointed_relieved: 

But do you have a text example where the issue was occured?

**Comment by zhiburt** [comment]
It seems like cutting works?

![Screenshot_2022-05-03_13-42-47](https://user-images.githubusercontent.com/20165848/166440176-5b2acc93-9c77-47c3-b18f-67ce73f19da7.png)

But something on nu-table end?

![Screenshot_2022-05-03_13-43-27](https://user-images.githubusercontent.com/20165848/166440190-7f7a1f28-1578-4322-b71d-48918784a2c1.png)

**Comment by sholderbach** [comment]
According to @fdncred 's screenshot it looks like this only happens when it wraps on word boundaries. Maybe a different logic is employed there?

**Comment by zhiburt** [comment]
So I'd like to point out that `ansi-cut` was never called in this issue.

![Screenshot_2022-05-03_17-18-33](https://user-images.githubusercontent.com/20165848/166472040-e79e8050-4f63-46f4-a07b-c0a0621552cb.png)

Hi @fdncred could you verify that #5425 fixes your issue?
You can do it by cloning https://github.com/zhiburt/nushell/tree/fix-coloring-when-string-has-spaces and then build nushell.
And your flow.

**Comment by fdncred** [comment]
@zhiburt confirmed. thanks for the fix!
