### ISSUE TITLE
`git checkout <branch> <path>` does not work

### ISSUE THREAD

**Issue by BatmanAoD** [nushell/nushell#5418]
### Describe the bug

The default git completion parser fails to recognize `git checkout <branch> <path>` as a valid `git` command. It does permit using the explicit `--` disambiguation.

### How to reproduce

```
$> git checkout main README.md
Error: nu::parser::extra_positional (https://docs.rs/nu-parser/0.61.0/nu_parser/enum.ParseError.html#variant.ExtraPositional)

  × Extra positional argument.
   ╭─[entry #21:1:1]
 1 │ git checkout main README.md
   ·                   ────┬────
   ·                       ╰── extra positional argument
   ╰────
  help: Usage: git checkout {flags} (branch)
```

### Expected behavior

Run `git` with the specified arguments (checking out `README.md` from the `main` branch)

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.61.0                              |
| branch             |                                     |
| tag                |                                     |
| build_os           | linux-x86_64                        |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10) |
| pkg_version        | 0.61.0                              |
| build_time         | 2022-04-15 15:17:03 -06:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |

### Additional context

These both work:

```
git checkout main -- README.md
^git checkout main -- README.md
```

**Comment by hustcer** [comment]
Guess you must use the old `git checkout` extern signature，please try the latest version

**Comment by hustcer** [comment]
The latest `git checkout` config should work:
https://github.com/nushell/nushell/blob/e36649f74b37ee183a2b2999b5b3ee4762cb921a/docs/sample_config/default_config.nu#L66

If not please reopen

**Comment by BatmanAoD** [comment]
I'll try that... is there a way to update the default configuration (or just the `git` bits) without either blowing away my changes or manually copy-and-pasting changes from the nushell source?

**Comment by hustcer** [comment]
Maybe you can follow this guide https://github.com/nushell/nu_scripts/blob/main/custom-completions/git/README.md
after that all you need to do is
updating the repo

**Comment by BatmanAoD** [comment]
Okay, yes, using the `nu_scripts` completion (which I didn't know about before) worked. Perhaps the [configuration documentation](https://www.nushell.sh/book/configuration.html#nushell-configuration-with-env-nu-and-config-nu) and/or the default config file should point users to that repo.

(As a side-note, I was very surprised that it's apparently not possible to import completion files in a "portable" way, i.e., there's no equivalent for something like `source ${HOME}/my/script` in Bash, which makes it easy to bring your configuration from one computer to another and ensure it works regardless of what the working directory is when the config is loaded.)
