### ISSUE TITLE
nushell doesn't recognize directory paths with spaces nor files with filenames with spaces

### ISSUE THREAD

**Issue by kurokirasama** [nushell/nushell#5420]
### Describe the bug

1. Trying to `cd` to a folder with spaces in its name doesn't autocomplete.
2. Trying to remove files with autocompletion with filenames with spaces gives the following error:

```
Error: 
  × No valid paths
   ╭─[entry #12:1:1]
 1 │ rm `'a file'`
   · ─┬
   ·  ╰── no valid paths
   ╰────

```
3. `rm "a file" works`

### How to reproduce

1. Try
```
mkdir "a dir"
cd a (it won't autocomplete)
```
2. Try
```
touch "a file"
rm a (and autocomplete)
```

### Expected behavior

It should `cd` and `rm` correctly with autocompletion

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.61.1                                          |
| branch             |                                                 |
| tag                |                                                 |
| short_commit       | 1a524606                                        |
| commit_hash        | 1a524606957556b982d50001dc01e5e522624ce0        |
| commit_date        | 2022-05-02 18:38:18 +00:00                      |
| build_os           | linux-x86_64                                    |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)               |
| pkg_version        | 0.61.1                                          |
| build_time         | 2022-05-02 15:23:13 -04:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by jntrnr** [comment]
This should hopefully be fixed in the latest main. You can use backticks around filepaths with spaces and it should recognise them okay.

The bug in previous versions wrapped the path in two kinds of quotes, and that was causing issues.

**Comment by fdncred** [comment]
please reopen if you're still seeing issues @kurokirasama
