### ISSUE TITLE
External `mkdir` command completes into internal `mkdir`

### ISSUE THREAD

**Issue by ZetaNumbers** [nushell/nushell#5424]
### Describe the bug

See above

### How to reproduce

`mkdi<tab>` and try complete the external one

### Expected behavior

`mkdi<tab>` should be able to complete into `^mkdir`, if prompted.

### Screenshots

![изображение](https://user-images.githubusercontent.com/53300196/166436517-b8e38c93-d6e6-4bcd-a0ef-a05b87ec5980.png)

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.61.1                                      |
| branch             | main                                        |
| tag                |                                             |
| short_commit       | e36649f7                                    |
| commit_hash        | e36649f74b37ee183a2b2999b5b3ee4762cb921a    |
| commit_date        | 2022-05-03 00:37:38 +00:00                  |
| build_os           | linux-x86_64                                |
| rust_version       | rustc 1.62.0-nightly (18f314e70 2022-04-24) |
| rust_channel       | nightly-x86_64-unknown-linux-gnu            |
| cargo_version      | cargo 1.62.0-nightly (edffc4a 2022-04-19)   |
| pkg_version        | 0.61.1                                      |
| build_time         | 2022-05-03 13:04:26 +03:00                  |
| build_rust_channel | debug                                       |
| features           | default, trash, which, zip                  |
| installed_plugins  |                                             |

**Comment by herlon214** [comment]
good catch.
I'm not sure which one we should show (the built-in or the external).

**Comment by fdncred** [comment]
if we know that it's an external command, and you choose it off the completion menu, it should be smart enough to prepend the external command with a caret.

**Comment by herlon214** [comment]
interesting, so for externals we complete with `^`
but then we would need to show them with `^` as well and it won't look very good IMO, once we don't have the ability to display one thing and complete other (e.g: display `mkdir` and complete `^mkdir`)

**Comment by fdncred** [comment]
i kind of like the `^` differentiating externals from internals. i think it's a good visual flag that what you're about to run is an external command. maybe i'm the only one who feels this way. :)

**Comment by herlon214** [comment]
@fdncred for completions that can be a little bit hard, specially prefixed, once you will type `mkd<tab>` and the completion starts with `^`
not impossible though

**Comment by fdncred** [comment]
@herlon214 i'm just saying it would be neat. let's if others respond before we do anything.
