### ISSUE TITLE
$config.buffer_editor should default to "editor"

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#5429]
### Related problem

Currently, the line buffer editor (#5381):

* Requires `$config.buffer_editor`
* The default/sample `config.nu` sets the value to Emacs, which is not installed on the majority of systems, and almost never by default.

If either the variable is not set or the variable is set to an editor that is not installed, then attempting to use the line buffer editor will result in: 

```
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

This does not provide for a good "out-of-the-box" configuration experience for Nu for a majority of users.

### Describe the solution you'd like

Recommend attempting to use the system default editor when possible.  This can best be done by defaulting to `/usr/bin/editor` (or just `editor`).  This is a standard convention for Linux/Unix systems that use the [Alternatives](https://www.redhat.com/sysadmin/alternatives-command) system (including Debian, Ubuntu, Redhat, Arch, etc. etc.).  It is typically set by default for distributions to an editor which is known to be installed, and it can easily be overridden by the user to their preferred editor.

I would recommend that this *default* be hard-coded, so that it has a relatively high likelihood of working even in the event that `$config.buffer_editor`, `VISUAL`, or `EDITOR` (per #5430) are not set.

### Describe alternatives you've considered

Currently, there's just a single editor option configured via `$config.buffer_editor`. Having a sensical default "fallback" plan might make sense, so the following binaries could be checked in order:

* `editor`
* `emacs`
* `code` (Visual Studio Code, which has a Nushell extension for syntax highlighting/indention/etc.)
* `nano`
* `gvim`
* `vi`
* `notepad.exe`

This isn't based on any preference (mine is `vi`, and it comes last) -- Just the likelihood of the fallback being installed.  E.g. If `vi` were the first fallback, it would typically be found before `nano` or `emacs`.  Notepad and Vi are practically universally installed on their respective OS's, so having them come last means that they'll be the catchall fallback that is practically guaranteed to work.

On the other hand, if someone has installed Emacs or VSCode, then those will get picked up as "preferred" over Vi.

Of course, this doesn't necessarily lend itself to the current implementation, which requires `$config.buffer_editor` to be set to *one* value.  It would require programmatic defaults (which many apps do, so I wouldn't necessarily rule it out).

That said, the "simple" solution, at least, appears to be to use `editor` as the default.

##### Windows

There's really no great way to, with a high level of confidence, get the "default" editor in Windows, but see #5430 for a reasonable alternative to a pre-configured "emacs" default on that platform.

**Comment by sholderbach** [comment]
If unset we now read the `EDITOR` and `VISUAL` variable as well and if I recall also include a fallback on some systems.
