### ISSUE TITLE
Bug: Prefix-based completion is apparently case-insensitive

### ISSUE THREAD

**Issue by lokegustafsson** [nushell/nushell#5438]
EDIT: I misread, this is not intended but a bug.
Original post:

If I've understood correctly, since 0.60.0 (from playing with 0.60 and reading code on current master) it is not possible to have case sensitive completion. I run only Linux, no Windows, and would really really like my command completion to be case sensitive (and prefix based) as well.

I think completion is configured approximately here in the code base:
https://github.com/nushell/nushell/blob/3df03e2e6d070f040efc0971319fe4837b9e46e0/crates/nu-cli/src/completions/completer.rs#L40
And as far as I can see no part of the global config can affect the completion options. A simple near-time fix could be to add global options `completion_case_sensitive` and `completion_positional` (although I have no idea what positional completion is).

I could implement this is if that's appreciated. I don't think the diff should be more than a few lines.

**Comment by fdncred** [comment]
It looks like case_sensitive is set to true when the MatchAlgorithm::Prefix is set. Are you not seeing that?
```rust
#[derive(Clone)]
pub struct CompletionOptions {
    pub case_sensitive: bool,
    pub positional: bool,
    pub sort_by: SortBy,
    pub match_algorithm: MatchAlgorithm,
}

impl Default for CompletionOptions {
    fn default() -> Self {
        Self {
            case_sensitive: true,
            positional: true,
            sort_by: SortBy::Ascending,
            match_algorithm: MatchAlgorithm::Prefix,
        }
    }
}
```

**Comment by lokegustafsson** [comment]
That is true, and looking at the code `case_sensitive: true` should be the default for 0.61.0 as well. I am however not seeing case sensitive completion (`/etc/n` completes to both `/etc/nixos` and `/etc/NIXOS`, I want the former) on my 0.61.0 locally. I am running essentially the default config, and this is particularly weird since case sensitivity does not even appear configurable :confused:

**Comment by herlon214** [comment]
I can see is hardcoded to lower case for file completion:
https://github.com/nushell/nushell/blob/main/crates/nu-cli/src/completions/file_completions.rs#L161-L163

Probably for some others as well
