### ISSUE TITLE
`flatten` is weird

### ISSUE THREAD

**Issue by ZetaNumbers** [nushell/nushell#5443]
### Describe the bug

`flatten` works weird with tables. ~~I expected for it to work something like a Kronecker product.~~ IDK how it should work. Need expected samples to be provided.

### How to reproduce

`let $a = [[a b] ; [0 2] [1 3]] ; $a`

| a | b |
| - | - |
| 0 | 2 |
| 1 | 3 |

`let $b = ($a | insert e { $a | rename c d }) ; $b`

| a | b | e                           |
| - | - | --------------------------- |
| 0 | 2 | [table 2 rows] |
| 1 | 3 | [table 2 rows] |

`let $c = ($b | flatten) ; $c`

| a | b | c | d | e_c | e_d |
| - | - | - | - | --- | --- |
| 0 | 2 | 0 | 2 | 1   | 3   |
| 1 | 3 | 0 | 2 | 1   | 3   |

### Expected behavior

`$c`

| a | b | c | d |
| - | - | - | - |
| 0 | 2 | 0 | 2 |
| 0 | 2 | 1 | 3 |
| 1 | 3 | 0 | 2 |
| 1 | 3 | 1 | 3 |

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.61.0                                |
| branch             |                                       |
| tag                |                                       |
| build_os           | linux-x86_64                          |
| rust_version       | rustc 1.59.0                          |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.61.0                                |
| build_time         | 2022-04-12 20:38:15 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

### Additional context

Maybe we should add `flatten --columns <cols> --rows <rows>` arguments, to specify where to expand like that. Anyway, this actually requires some thought put into the design. Maybe there should be another command, like `expand` for this? Should `flatten` error, when doing ambiguous stuff? Maybe i am stupid?

**Comment by onthebridgetonowhere** [comment]
This might be a bug in `flatten`, but I am not sure -- I remember I worked on porting this I think. My intuition is that if you do `flatten e`, it should flatten out the `e` column to the two columns inside it. Maybe others have other insights? 
@fdncred, @kubouch - what do you think?

**Comment by fdncred** [comment]
Since engine-q I've thought `flatten` nearly worked but not quite.

**Comment by ZetaNumbers** [comment]
Another example of weird flatten behavior: https://github.com/nushell/nushell/issues/5444#issuecomment-1120246295.

**Comment by onthebridgetonowhere** [comment]
I'll try to take a look at `flatten` - we have a few use cases which can guide the proper design.

**Comment by WindSoilder** [comment]
+1 for weird behavior, I think I should run something like [rust std flattern](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.flatten)

**Comment by fdncred** [comment]
these examples work now thanks to @WindSoilder and #5584

**Comment by onthebridgetonowhere** [comment]
Great work @WindSoilder
