### ISSUE TITLE
`transpose --flat`

### ISSUE THREAD

**Issue by ZetaNumbers** [nushell/nushell#5444]
### Related problem

Some json or yaml files use (as i would call) a map structure of data: 

```json
{
  "Nina": {
    "age": 27,
    "hobby": "art"
  },
  "Anna": {
    "age": 21,
    "hobby": "programming"
  }
}
```

It uses field name as a person's name. But when opening in the nushell, these are just nested records:

```
╭──────┬───────────────────╮
│ Nina │ {record 2 fields} │
│ Anna │ {record 2 fields} │
╰──────┴───────────────────╯
```

### Describe the solution you'd like

I propose `transpose --flat`. After piping mentioned above structured data into `transpose name --flat`, we should get:

```
╭───┬──────┬─────┬─────────────╮
│ # │ name │ age │    hobby    │
├───┼──────┼─────┼─────────────┤
│ 0 │ Nina │  27 │ art         │
│ 1 │ Anna │  21 │ programming │
╰───┴──────┴─────┴─────────────╯
```

### Describe alternatives you've considered

`transpose name data | select name data.age data.hobby | rename name age hobby`, but it's verbose and doesn't account for every field.

**Comment by onthebridgetonowhere** [comment]
What do you think about using `transpose | flatten | rename name`? 
That would give you
```
╭───┬──────┬─────┬─────────────╮
│ # │ name │ age │    hobby    │
├───┼──────┼─────┼─────────────┤
│ 0 │ Nina │  27 │ art         │
│ 1 │ Anna │  21 │ programming │
╰───┴──────┴─────┴─────────────╯
```

**Comment by ZetaNumbers** [comment]
Consider this example of two json files:

 - file0.json

```json
{
  "Nina":
  {
    "age": 27,
    "hobby": "art"
  },
  "Anna":
  {
    "age": 21,
    "hobby": "programming"
  }
}
```
 - file1.json

```json
{
  "Tatiana":
  {
    "age": 32,
    "hobby": "literature"
  },
  "Sasha":
  {
    "age": 18,
    "hobby": "sculpture"
  }
}
```

Then the pipeline:

1. `[file0.json file1.json] | each { open $in }`

```
 #         Nina                Anna               Tatiana              Sasha
 0   {record 2 fields}   {record 2 fields}   ❎                  ❎
 1   ❎                  ❎                  {record 2 fields}   {record 2 fields}
```

2. `| transpose name`

```
 #    name          column1             column2
 0   Nina      {record 2 fields}
 1   Anna      {record 2 fields}
 2   Tatiana                       {record 2 fields}
 3   Sasha                         {record 2 fields}
```

3. `| flatten`

```
 #    name     age      hobby      column2   column1 
 0   Nina       27   art                     ❎      
 1   Anna       21   programming             ❎      
 2   Tatiana    32   literature    ❎                
 3   Sasha      18   sculpture     ❎                
```

So yes, i guess flatten should just work for this, but it doesn't. Further discussion about flatten behavior should continue in #5443

**Comment by onthebridgetonowhere** [comment]
Thanks for the use cases. I think `flatten` requires some proper design and implementation. There are a lot of weird and corner cases, so we'd have to take some time to write them down and document the design choices.

**Comment by WindSoilder** [comment]
Hmm....The new fixed behavior still doesn't fit the needs.

For the case working, we have to do `merge` operation for opened json at first step...
```
open files0.json | merge { open files1.json }
```

**Comment by ZetaNumbers** [comment]
> For the case working, we have to do `merge` operation for opened json at first step...

It's a bit complex, when dealing with lists.
