### ISSUE TITLE
can't pass flags into function

### ISSUE THREAD

**Issue by gipsyh** [nushell/nushell#5445]
### Describe the bug

```
# qemu.nu
def main [kernel: string, --version: string, --arch: string] {

}
```
<img width="936" alt="截屏2022-05-05 09 32 07" src="https://user-images.githubusercontent.com/42509521/166852098-e08c77a2-0664-498c-bc74-1e1b961229b0.png">

if I recall correctly, it's ok in 0.61.1

### How to reproduce

described above

### Expected behavior

no error report

### Configuration
| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.62.0                              |
| branch             |                                     |
| tag                |                                     |
| build_os           | macos-aarch64                       |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04) |
| rust_channel       | stable-aarch64-apple-darwin         |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01) |
| pkg_version        | 0.62.0                              |
| build_time         | 2022-05-04 10:04:15 +08:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |

**Comment by uasi** [comment]
We need to either

1. fix https://github.com/nushell/nushell/blob/96f8691c8d656ae92d1cb2ed5b5fdb2dda677cf6/src/main.rs#L85 not to quote arguments that look like flags, or
2. make functions accept quoted strings as flags.

**Comment by gipsyh** [comment]
It still not work in my machine.
https://github.com/nushell/nushell/pull/5447#issuecomment-1121774429

**Comment by merelymyself** [comment]
@gipsyh - my bad, I forgot to factor in cases where the function is defined with multiple flags on the same line. I usually define my functions like 

```
def main [
--flag: string,
--flag2: int,
]
```

which is why I overlooked it. There's an easy fix.

**Comment by hustcer** [comment]
Seems still not work?

**Comment by hustcer** [comment]
It's found that `nu b.nu linux --version v5.2` works but `nu b.nu linux --version=v5.2` not work:
```
@hustcer ➜ tmp git(develop) $> nu b.nu linux --version v5.2
linux
v5.2

@hustcer ➜ tmp git(develop) $> nu b.nu linux --version=v5.2
Error: nu::parser::extra_positional (link)

  × Extra positional argument.
   ╭─[<commandline>:1:1]
 1 │ main "linux" "--version=v5.2"
   ·              ────────┬───────
   ·                      ╰── extra positional argument
   ╰────
  help: Usage: main {flags} <kernel>

```

**Comment by hustcer** [comment]
@gipsyh You are right, the original issue has been fixed, let's close it in favor of this one: https://github.com/nushell/nushell/issues/5532
