### ISSUE TITLE
exec doesn't support forwarding flags

### ISSUE THREAD

**Issue by efugier** [nushell/nushell#5448]
### Describe the bug

Minimal example:
```
❯ exec bash -c "nu"
Error: nu::parser::unknown_flag (https://docs.rs/nu-parser/0.61.0/nu_parser/enum.ParseError.html#variant.UnknownFlag)

  × The `exec` command doesn't have flag `-c`.
   ╭─[entry #1:1:1]
 1 │ exec bash -c "nu"
   ·            ┬
   ·            ╰── unknown flag
   ╰────
  help: use exec --help for a list of flags
```

expected behavior (e.g. in bash):
```
❯ exec bash -c "nu"
❯ $env.SHELL
/home/XXXX/.cargo/bin/nu
```

### How to reproduce

Try to use flags with a command in exec. 

### Expected behavior

Forward the flags after the command to to it. 

### Configuration

.

**Comment by kubouch** [comment]
You need to wrap them in strings, like `exec bash "-c" ...`.

**Comment by kubouch** [comment]
It's a known issue, though, I'll close it in favor of the existing one: #2675

**Comment by efugier** [comment]
oh thanks, sorry for the duplication!
