### ISSUE TITLE
Last Output Capturing Does not Work

### ISSUE THREAD

**Issue by schrieveslaach** [nushell/nushell#5449]
### Describe the bug

I activated shell integration with following config and when I run a command and I want to capture the output with Kitty nothing will be captured.

### How to reproduce

1. Use following config
```
   let-env config = {
      animate_prompt: false,
      shell_integration: true,
   }
```
2. Run a command in Kitty
4. Use ctrl + shift + g to capture the output
5. Nothing will be shown in the pager that has been started by kitty

### Expected behavior

1. Use following config
```
   let-env config = {
      animate_prompt: false,
      shell_integration: true,
   }
```
2. Run a command in Kitty
3. Use ctrl + shift + g to capture the output
4. The output will be shown in the pager that has been started by kitty

### Screenshots

![output](https://user-images.githubusercontent.com/16558417/166911515-1a653802-3776-4343-bbaf-3ce2021c3654.gif)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.62.0                                          |
| branch             |                                                 |
| tag                |                                                 |
| short_commit       | da104050                                        |
| commit_hash        | da104050e6dcf7fbffd41bfd4bdeae1285b7a48c        |
| commit_date        | 2022-05-03 21:50:33 +00:00                      |
| build_os           | linux-x86_64                                    |
| rust_version       | rustc 1.60.0 (Arch Linux rust 1:1.60.0-1)       |
| cargo_version      | cargo 1.60.0                                    |
| pkg_version        | 0.62.0                                          |
| build_time         | 2022-05-04 04:46:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
I see your point. It looks like the markers may not be getting set properly. I get some but it's not right.
<img width="733" alt="Screen Shot 2022-05-05 at 6 51 18 AM" src="https://user-images.githubusercontent.com/343840/166917546-64209562-61ef-4efd-b5c5-45285f5864c4.png">

Do you have the bandwidth to look at this and help us resolve this bug?

**Comment by schrieveslaach** [comment]
I'll look into it.

**Comment by fdncred** [comment]
I don't think this is working anymore.
