### ISSUE TITLE
Autocomplete with `cd` doesn't recognize symlinks 

### ISSUE THREAD

**Issue by danjenson** [nushell/nushell#5451]
### Describe the bug

![image](https://user-images.githubusercontent.com/4793438/166971412-6437ac77-cad7-42e6-b2f9-4f615642c412.png)

### How to reproduce

cd to a directory with symlinked directories, it won't autocomplete any of those directories.

### Expected behavior

It would autocomplete those directories.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.62.0                                          |
| branch             |                                                 |
| tag                |                                                 |
| build_os           | linux-x86_64                                    |
| rust_version       | rustc 1.61.0-nightly (ab0c2e18d 2022-03-27)     |
| rust_channel       | nightly-x86_64-unknown-linux-gnu                |
| cargo_version      | cargo 1.61.0-nightly (109bfbd 2022-03-17)       |
| pkg_version        | 0.62.0                                          |
| build_time         | 2022-05-03 18:02:54 -07:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by herlon214** [comment]
yeah, just upgraded to `0.62.0` and it doesn't work anymore, so it's a regression.
