### ISSUE TITLE
Extra positional argument error when starting nu

### ISSUE THREAD

**Issue by Booteille** [nushell/nushell#5455]
### Describe the bug

I just installed nu 0.62.0 through cargo on Pop_OS! 22.04.

When starting nu, I get the following error:

```console
Error: nu::parser::extra_positional (https://docs.rs/nu-parser/0.62.0/nu_parser/enum.ParseError.html#variant.ExtraPositional)

  × Extra positional argument.
    ╭─[/home/booteille/.config/nushell/config.nu:63:1]
 63 │   def "nu-complete git branches" [] {
 64 │     ^git branch | lines | each { |line| $line | str find-replace '\* ' '' | str trim }
    ·                                                                  ──┬──
    ·                                                                    ╰── extra positional argument
 65 │   }
    ╰────
  help: Usage: str find-replace
```

### How to reproduce

1. Install nu
2. Run `nu` command

### Expected behavior

No error message should be displayed.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.62.0                                          |
| branch             |                                                 |
| tag                |                                                 |
| build_os           | linux-x86_64                                    |
| rust_version       | rustc 1.61.0-nightly (5f3700105 2022-03-22)     |
| rust_channel       | nightly-x86_64-unknown-linux-gnu                |
| cargo_version      | cargo 1.61.0-nightly (109bfbd 2022-03-17)       |
| pkg_version        | 0.62.0                                          |
| build_time         | 2022-05-06 12:39:37 +02:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |

**Comment by Booteille** [comment]
Done and it worked, thanks!

I just get the following warning now:

```console
warning: use `let-env config = ...` instead of `let config = ...`
```

I don't find any `let config ` occurrence in my config.nu file, though.

**Comment by hustcer** [comment]
@Booteille You can also use the latest config instead see https://github.com/nushell/nushell/blob/main/docs/sample_config/default_config.nu

**Comment by Booteille** [comment]
Thanks, I'll try!
