### ISSUE TITLE
line in custom complete for arguments has extra 'a' character appended to it

### ISSUE THREAD

**Issue by vyvl** [nushell/nushell#5457]
### Describe the bug

If we type `xyz <Tab>`, the line variable is populated as `xyz a` instead of `xyz`. Not sure how this `a` char is being added.

### How to reproduce

Save below code to a tmp.nu file
```
export extern xyz [
    query: string@"nu-complete show list"
]

def "nu-complete show list" [line : string, pos: int] {
  let prefix = $"line: ($line) pos: ($pos)"
  [$prefix $prefix $prefix]
}
```
Load it using `use tmp.nu *`

Type `xyz <Tab>` and notice contents of `$line` is `xyz a` instead of `xyz`

### Expected behavior

Expected extra char `a` should not be appended.

### Screenshots

![image](https://user-images.githubusercontent.com/8201617/167178685-b8c690fb-3284-4dba-be18-97b1a41d5168.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.62.0                                          |
| branch             |                                                 |
| tag                |                                                 |
| short_commit       | da104050                                        |
| commit_hash        | da104050e6dcf7fbffd41bfd4bdeae1285b7a48c        |
| commit_date        | 2022-05-03 21:50:33 +00:00                      |
| build_os           | windows-x86_64                                  |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01)             |
| pkg_version        | 0.62.0                                          |
| build_time         | 2022-05-03 22:10:37 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by herlon214** [comment]
This is a good one. If I remember correctly that 'a' is added to the string just in order to trigger the engine for parsing the data, something like that.
I remember that I removed it, but looks like it's back, I will take a look.
