### ISSUE TITLE
$in in each block is not available past the semicolon

### ISSUE THREAD

**Issue by Yethal** [nushell/nushell#5465]
### Describe the bug

When using each without the explicit iterator the $in variable is only available to the first command (and whatever that command was piped into), if we add a second command after a semicolon that command no longer has access to $in.

### How to reproduce

1. Run `ls|where type == dir | each { cd $in.name; pwd }`
1. Run `ls|where type == dir | each {|it| cd $it.name; pwd }`

### Expected behavior

First command prints the starting directory multiple times (pwd refers to initial dir), second command prints the directory we're changing into (pwd refers to changed directory)

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.62.0                                              |
| branch             |                                                     |
| tag                |                                                     |
| build_os           | linux-x86_64                                        |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)                 |
| rust_channel       | stable-x86_64-unknown-linux-gnu                     |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)                   |
| pkg_version        | 0.62.0                                              |
| build_time         | 2022-05-05 08:06:15 +02:00                          |
| build_rust_channel | release                                             |
| features           | database, dataframe, default, trash, which, zip     |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by elferherrera** [comment]
That is expected. $in get consumed in the first expression

**Comment by Yethal** [comment]
@elferherrera I edited the bug to describe the original issue I found, @jntrnr already explained to me that the second behavior (which the original description refered to) is correct

**Comment by rgwood** [comment]
The command output, for anyone trying to understand the issue:

```
〉ls|where type == dir | each { cd $in.name; pwd }
/home/reilly
/home/reilly
/home/reilly
〉ls|where type == dir | each {|it| cd $it.name; pwd }
/home/reilly/bin
/home/reilly/downloads
/home/reilly/source
```

**Comment by Yethal** [comment]
@rgwood I wonder if this is related to this PR:
https://github.com/nushell/nushell/pull/6649

**Comment by merelymyself** [comment]
I don't think the issue still exists on the latest main.
```
~/CodingProjects/nushell〉ls|where type == dir | each { cd $in.name; pwd }
/home/gabriel/CodingProjects/nushell/assets
/home/gabriel/CodingProjects/nushell/crates
/home/gabriel/CodingProjects/nushell/docker
/home/gabriel/CodingProjects/nushell/docs
/home/gabriel/CodingProjects/nushell/images
/home/gabriel/CodingProjects/nushell/pkg_mgrs
/home/gabriel/CodingProjects/nushell/samples
/home/gabriel/CodingProjects/nushell/src
/home/gabriel/CodingProjects/nushell/target
/home/gabriel/CodingProjects/nushell/tests
/home/gabriel/CodingProjects/nushell/wix
~/CodingProjects/nushell〉ls|where type == dir | each {|it| cd $it.name; pwd }
/home/gabriel/CodingProjects/nushell/assets
/home/gabriel/CodingProjects/nushell/crates
/home/gabriel/CodingProjects/nushell/docker
/home/gabriel/CodingProjects/nushell/docs
/home/gabriel/CodingProjects/nushell/images
/home/gabriel/CodingProjects/nushell/pkg_mgrs
/home/gabriel/CodingProjects/nushell/samples
/home/gabriel/CodingProjects/nushell/src
/home/gabriel/CodingProjects/nushell/target
/home/gabriel/CodingProjects/nushell/tests
/home/gabriel/CodingProjects/nushell/wix
```

Possibly because of #6649, funnily enough. Could someone else check on their machine?

**Comment by rgwood** [comment]
Good catch! I'm also unable to reproduce it on `main`.
