### ISSUE TITLE
`into filesize` doesn’t support $nothing or null

### ISSUE THREAD

**Issue by flying-sheep** [nushell/nushell#5469]
### Describe the bug

`into filesize` doesn’t seem to support `null` or `$nothing`.

I came up with this workaround, but this should be fixed!

```nushell
[['a']; ['1'] [null]] | upsert a {|df| if ($df.a | empty?) { null } else { $df.a | into filesize } } 
```

### How to reproduce

```nushell
> [['a']; ['1'] [null]] | into filesize a
Error: nu::shell::unsupported_input (link)

  × Unsupported input
   ╭─[entry #56:1:1]
 1 │ [['a']; ['1'] [null]] | into filesize a
   ·                ──┬─
   ·                  ╰── 'into filesize' for unsupported type
   ╰────
```

### Expected behavior

```nushell
> [['a']; ['1'] [null]] | into filesize a
╭───┬─────╮
│ # │  a  │
├───┼─────┤
│ 0 │ 1 B │
│ 1 │     │
╰───┴─────╯
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.62.0                                          |
| branch             |                                                 |
| tag                |                                                 |
| short_commit       | da104050                                        |
| commit_hash        | da104050e6dcf7fbffd41bfd4bdeae1285b7a48c        |
| commit_date        | 2022-05-03 21:50:33 +00:00                      |
| build_os           | linux-x86_64                                    |
| rust_version       | rustc 1.60.0 (Arch Linux rust 1:1.60.0-1)       |
| cargo_version      | cargo 1.60.0                                    |
| pkg_version        | 0.62.0                                          |
| build_time         | 2022-05-04 04:46:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by hustcer** [comment]
I think this is currently by design

**Comment by flying-sheep** [comment]
can someone confirm this and explain the rationale?

**Comment by fdncred** [comment]
@flying-sheep so `null | into filesize` is supposed to return what exactly? `null`/`$nothing`, `""`, `0 B`? I mean, it would be pretty easy to add. I'm just not sure if we need to support converting null to a filesize.

**Comment by hustcer** [comment]
`""` should be better, IMO

**Comment by flying-sheep** [comment]
Wait a second, why is that better?

I have little experience with nushell so far, but coming from other languages, I’d think that leaving `null`/`$nothing` as itself would make sense, to indicate a missing value in a list or dataframe column:

```nushell
> [0, '0', null] | into filesize | to nuon
[0b, 0b, $nothing]
````

making `into filesize` return a sting instead of a filesize seems very confusing.

**Comment by hustcer** [comment]
After some discussion, we come to a final conclusion that make `$nothing | into filesize` return `0 B`, as both `^ls -l` and `lsd -l` will return 0 or 0 B, and also make resolve this issue: https://github.com/nushell/nushell/issues/4975 possible
Ref: https://github.com/Peltoche/lsd
