### ISSUE TITLE
Why alias is not working?

### ISSUE THREAD

**Issue by danielRi** [nushell/nushell#5481]
### Describe the bug

When Im defining an alias and run it, it doesnt seem to work, I get an error instead

### How to reproduce

1. Navigate to folder with git
2. defining an alias `alias gcd = git checkout develop`
3. Running it by typing `gcd`, pressing `Enter`
4. Getting the error, see screenshot

### Expected behavior

Im expecting the command `git checkout develop` will be executed

### Screenshots

![Bildschirmfoto 2022-05-09 um 05 20 58](https://user-images.githubusercontent.com/3048681/167335908-cbc8bb8e-d48c-4d3d-9cad-ff7ab246bb2e.png)

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.61.0                                |
| branch             |                                       |
| tag                |                                       |
| build_os           | macos-aarch64                         |
| rust_version       | rustc 1.59.0                          |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.61.0                                |
| build_time         | 2022-04-12 20:38:15 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

### Additional context

Im running iTerm2 + starship.

I also tried to add the command `alias gcd = git checkout develop` to the end of $nu.config-path file, but also no luck.

**Comment by WindSoilder** [comment]
I can get the same issue in `0.61.0`, but it seems the issue doesn't exists in the newest version(0.62.0), can you try to update nu to 0.62.0 and try again?

**Comment by danielRi** [comment]
@WindSoilder Sorry, off topic but I need to figure out how to update to `0.62.0` first, as I think it´s not the stable version right now. Sorry.

**Comment by WindSoilder** [comment]
@danielRi Hmm, I think it depends on how you install `nu` firstly.

If you are using `cargo`, you can just execute `cargo install nu` directly.
If you just download prebuild binary, you can just download it in [github release page](https://github.com/nushell/nushell/releases/tag/0.62.0) and replace the binary manually.

**Comment by rgwood** [comment]
Just to add some context: v0.62 is the current stable version of Nu. It looks like you're on macOS; if you're using Homebrew, unfortunately v0.62 is not yet available via Homebrew. More info [here](https://github.com/Homebrew/homebrew-core/pull/100716) but essentially we're blocked on Homebrew being slow to update their version of Rust.

It's probably easiest to [download the release](https://github.com/nushell/nushell/releases/tag/0.62.0) or use Cargo if you already have it installed.

**Comment by danielRi** [comment]
Thanks for the help guys! I indeed installed via Homebrew. I will replace my installation with cargo and check. Thanks.

**Comment by danielRi** [comment]
Hey guys! It works with `0.62.0`. And it also works if I define the `alias`´s in `$nu.config-path`. Sorry for bothering you :)
