### ISSUE TITLE
`ls -l` doesn't show value of setuid, setgid & sticky bit

### ISSUE THREAD

**Issue by CozyPenguin** [nushell/nushell#5499]
### Describe the bug

When listing a file with `ls -l`, the setuid, setgid and sticky bits do not show up in the mode value if set.

### How to reproduce

1. create a file: `touch test`
2. set the setuid, setgid or sticky permission bit for the file: `chmod o+t test`
3. execute `ls -l test`:

| name | mode      |
| ---- | --------- |
| test | rwxr-xr-x |

4. execute the system ls command: `^ls -l`:
`-rwxr-xr-t. 1 carl carl 3787144 May 10 12:57 test`

### Expected behavior

The command should show the correct permissions.

### Screenshots

![image](https://user-images.githubusercontent.com/48564710/167615133-c49074c9-931e-4e52-baa1-4bbbc8e4bba0.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.62.0                                          |
| branch             |                                                 |
| tag                |                                                 |
| build_os           | linux-x86_64                                    |
| rust_version       | rustc 1.60.0 (Fedora 1.60.0-1.fc36)             |
| cargo_version      | cargo 1.60.0                                    |
| pkg_version        | 0.62.0                                          |
| build_time         | 2022-05-04 00:00:00 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
we'd probably accept a PR to support this.

**Comment by CozyPenguin** [comment]
I'd be willing to do it, I just need to find some time to look at the codebase.

**Comment by CozyPenguin** [comment]
This appears to be caused by the umask crate. If my pull request gets accepted, this should be fixed by canop/umask#5
