### ISSUE TITLE
Source bash script

### ISSUE THREAD

**Issue by amirhosseindavoody** [nushell/nushell#5505]
### Describe the bug

We have a bash script at work which provides autocomplete functionality for an internal cli tool. I am trying to use nu shell instead of zsh. Is there a way to source a bash script in nu shell.

I tried `source my_bash_script.sh` but I get an error that `$- variable not found.`

### How to reproduce

In nu shell follow these steps:
1. Enter `echo "echo $-" | save my_bash_script.sh`
2. Enter `source my_bash_script.sh`

You will see the following error:

![image](https://user-images.githubusercontent.com/8355965/167722888-2b535112-5b28-4bd0-92ca-2d6955d05499.png)

### Expected behavior

I expect nu to print something like `569JNRXZghiklms`

### Screenshots

![image](https://user-images.githubusercontent.com/8355965/167722895-8c484800-ae3c-4ed3-8df2-d61127fd9a82.png)

**Comment by fdncred** [comment]
nushell is not backwards compatible with posix or bash. that is a non-goal. so, there is no way to directly source a bash script. depending on what it's doing, you could port it to a .nu script.

**Comment by jmoore34** [comment]
Depending on what the bash script does, you could do `bash my_bash_script.sh`. Though that won't e.g. set environmental variables of the nu process.

**Comment by flying-sheep** [comment]
KDE Plasma has a great approach for this. So simple!

https://invent.kde.org/plasma/plasma-workspace/-/blob/master/startkde/plasma-sourceenv.sh

you just run `bash plasma_sourceenv.sh some_script.sh some_other_script.sh` and parse the result.

**Comment by hustcer** [comment]
Since this is a non-goal, I'm closing it, sorry
