### ISSUE TITLE
Unhelpful error for trying to assign pipeline result to variable

### ISSUE THREAD

**Issue by sholderbach** [nushell/nushell#5509]
### Related problem

For users coming fresh to nushell with experience mostly in regular programming languages this error message may sound confusing.
![image](https://user-images.githubusercontent.com/15833959/167812169-505f10e2-fb73-4f61-a132-6764dd3d67fe.png)

### Describe the solution you'd like

It would be great if we instead mention to wrap the right hand side of the assignment in parentheses
![image](https://user-images.githubusercontent.com/15833959/167812580-e8f475c4-087e-4dda-a07a-0595a6e5e4b4.png)

### Describe alternatives you've considered

Potential issue: 

When pipelines become more lazy in their execution model (i.e. partially applied function in a sense), there could be a semantic difference between assigning a pipeline result and a predefined pipeline not yet evaluated.

Alternative:
RTFM

**Comment by hustcer** [comment]
Related: https://github.com/nushell/nushell/issues/4301

**Comment by hustcer** [comment]
It's much better now:
```
let test = "NuShell" | str snake-case
Error: nu::parser::unexpected_keyword (link)

  × Let statement used in pipeline.
   ╭─[entry #1:1:1]
 1 │ let test = "NuShell" | str snake-case
   · ─┬─
   ·  ╰── let in pipeline
   ╰────
  help: Assigning '"NuShell"' to 'test' does not produce a value to be piped. If the pipeline is meant to apply to '"NuShell"' by itself, use 'let test = ("NuShell" | ...)'.
```
