### ISSUE TITLE
`complete` doesn't work well with `git push` sometimes

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#5519]
### Describe the bug

`complete` doesn't work well with `git push` sometimes

### How to reproduce

Run `git push abc main | complete` in a git repo, will get the following output:

```
 $> git push abc main | complete
fatal: 'abc' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
  stdout
  stderr
  exit_code   128
```
The error message haven't been caught by `stderr`

### Expected behavior

```
fatal: 'abc' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
should be the value of `stderr`

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.62.1                                          |
| branch             | main                                            |
| tag                |                                                 |
| short_commit       | e9826233                                        |
| commit_hash        | e98262330ebd1ef1fa7c85095cc0d887adde9b10        |
| commit_date        | 2022-05-12 02:04:44 +00:00                      |
| build_os           | macos-x86_64                                    |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)             |
| rust_channel       | stable-x86_64-apple-darwin                      |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01)             |
| pkg_version        | 0.62.1                                          |
| build_time         | 2022-05-12 10:14:24 +08:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | gstat, query, query json, query web, query xml  |

**Comment by gipsyh** [comment]
https://github.com/nushell/nushell/issues/5437

**Comment by suimong** [comment]
On nushell v0.97.1 and git v2.46.0 the stderr is properly catched:

![image](https://github.com/user-attachments/assets/560a9259-b646-4c95-8963-51951e25f309)

**Comment by hustcer** [comment]
Thanks
