### ISSUE TITLE
rm can't remove dangling symlinks

### ISSUE THREAD

**Issue by fennewald** [nushell/nushell#5525]
### Describe the bug

Attempts to `rm` a dangling symlink will produce an error, and the symlink will remain undeleted.

Related to another bug I am going to file immediately after this.

### How to reproduce

```
~> touch file.txt
~> ln -s file.txt link.txt
~> rm file.txt
~> rm link.txt                                                                                                                               
Error:
  × No valid paths
   ╭─[entry #20:1:1]
 1 │ rm link
   · ─┬
   ·  ╰── no valid paths
   ╰────
```

### Expected behavior

Be able to delete the dangling symlink.

### Configuration

| key                | valye                                 |
| ------------------ | ------------------------------------- |
| version            | 0.61.0                                |
| branch             |                                       |
| tag                |                                       |
| build_os           | linux-x86_64                          |
| rust_version       | rustc 1.60.0                          |
| cargo_version      | cargo 1.60.0                          |
| pkg_version        | 0.61.0                                |
| build_time         | 1980-01-01 00:00:00 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

**Comment by hustcer** [comment]
Closing in favor of https://github.com/nushell/nushell/issues/3977
