### ISSUE TITLE
cp won't copy folders containing dangling symlinks

### ISSUE THREAD

**Issue by fennewald** [nushell/nushell#5526]
### Describe the bug

If copying a folder that contains a broken symlink, nushell will terminate the cp with an error message, leaving behind an empty directory

### How to reproduce

```
~> mkdir dir
~> cd dir
dir> touch file.txt; ln -s file.txt link.txt; rm file.txt
dir> cd ..
~> cp -r dir new_dir
Error: nu::shell::io_error (https://docs.rs/nu-protocol/0.61.0/nu_protocol/enum.ShellError.html#variant.IOError)

  × I/O error
  help: No such file or directory (os error 2)
```

### Expected behavior

I expected it to copy the broken symlink 'correctly', creating a new, broken symlink in the target directory.

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.61.0                                |
| branch             |                                       |
| tag                |                                       |
| build_os           | linux-x86_64                          |
| rust_version       | rustc 1.60.0                          |
| cargo_version      | cargo 1.60.0                          |
| pkg_version        | 0.61.0                                |
| build_time         | 1980-01-01 00:00:00 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

**Comment by hustcer** [comment]
May related to https://github.com/nushell/nushell/issues/3977

**Comment by WindSoilder** [comment]
> I expected it to copy the broken symlink 'correctly', creating a new, broken symlink in the target directory.

I suggest don't copy the broken symlink by default, this is what `fish` done by default
![图片](https://user-images.githubusercontent.com/22256154/170454280-2c260988-7a38-4a2a-b6b4-97aa4b041499.png)

**Comment by WindSoilder** [comment]
> I expected it to copy the broken symlink 'correctly', creating a new, broken symlink in the target directory.

I suggest not copy the broken symlink by default, like what `fish` shell does.

![图片](https://user-images.githubusercontent.com/22256154/170455374-836adea1-1b27-43d3-8582-ba9fca93fedb.png)

**Comment by fennewald** [comment]
@WindSoilder that seems reasonable, but regardless I don't think it should error out.

> by default

Do you want to add a flag to enable it? Users can get standard behavior by using `^cp` at any point, which seems like enough for me.

I'm a little uncomfortable with the silent fail that fish does though. For context I came across the bug `cp`ing some old backups I had back into their original dirs. The backups had invalid relative symlinks, that would have become valid on successful copy. I know that dangling symlinks aren't kosher, but my use case feels at least somewhat reasonable to expect. `bash`, `sh`, and `zsh` all copy the broken symlink because they're using the coreutils version of `cp`.

Perhaps some logging output, but I understand that adding output to something as core as cp is taboo.

Curious your thoughts.

**Comment by WindSoilder** [comment]
Personally I'm nervers about symbolic link, because copy symbolic link can make the new link file itself broken.  Refer to: https://unix.stackexchange.com/questions/56084/how-do-i-copy-a-symbolic-link

But, your case is also a valid use case:
> Do you want to add a flag to enable it

We can add a flag '-P'(the same flag in zsh or fish), to make `cp` never follow symbolic link, and copy dangling link directly, but I'm not sure if we should make it on by default.

**Comment by WindSoilder** [comment]
@fennewald Hi, can you try the latest main build with -p argument to find out if the issue is resolved?

**Comment by fennewald** [comment]
Everything works! `cp -r` copies without copying over the symlink, and `-p` copies it over. Thank you!
