### ISSUE TITLE
plugin to parse external --help commands into nu completion source

### ISSUE THREAD

**Issue by Jacobious52** [nushell/nushell#5528]
### Related problem

Nu is awesome and gets even better when you start adding completions for your favorite external tools.

I'd like to float the idea of a plugin that can take common forms of `--help` output from external commands, parse as much options and args as possible and output the nu script for the completions.

### Describe the solution you'd like

In the example of `cargo --help | nu-parse-completions | save cargo-completions.nu`

`nu-parse-completions` could try to parse out as much completion information as it reliably can and structure that out as a nu completion extern that can be sourced.

In this case a example of output is similar to
```
❯ cargo --help
Rust's package manager

USAGE:
    cargo [+toolchain] [OPTIONS] [SUBCOMMAND]

OPTIONS:
    -V, --version               Print version info and exit

Some common cargo commands are (see all commands with --list):
    build, b    Compile the current package
```

where the parser outputs nu script like such 

```nu
export extern "cargo" [
   build?            # Compile the current package
   --version(-V)     # Print version info and exit
]
```

Potentially able to parse out more information such as flag descriptions and argument types if available 

A bonus, but potentially dangerous addition could be recurse `<command> <arg> --help` on all arguments it finds.

### Describe alternatives you've considered

This could very easily be a standalone tool that one could use in the Nu ecosystem.

### Additional context and details

This is likely not feasible realistically due to the variations of how commands output help format, but thought I'd float the idea just in case it resonates with anyone

**Comment by fdncred** [comment]
ya, that sounds cool. We'd accept a PR for that.

**Comment by Jacobious52** [comment]
Had a quick go and opened a draft over at nu-scripts https://github.com/nushell/nu_scripts/pull/223 
Seems like it'd be entirely possible with a bit more effort and perhaps smarter parsing technique
