### ISSUE TITLE
Strange Block Output

### ISSUE THREAD

**Issue by gipsyh** [nushell/nushell#5529]
### Describe the bug

`echo abc | {$in}`

<img width="359" alt="截屏2022-05-13 15 18 36" src="https://user-images.githubusercontent.com/42509521/168231838-333f8654-de54-44dc-92ab-e88dc2413555.png">

### How to reproduce

1. echo abc | {$in}

### Expected behavior

abc

### Screenshots

abc

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.62.1                                   |
| branch             | master                                   |
| tag                |                                          |
| short_commit       | 32d1939a                                 |
| commit_hash        | 32d1939a95ef1043679e64968d8817d0acbdb4c0 |
| commit_date        | 2022-05-13 00:25:21 +00:00               |
| build_os           | linux-aarch64                            |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-aarch64-unknown-linux-gnu         |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)        |
| pkg_version        | 0.62.1                                   |
| build_time         | 2022-05-13 01:27:41 +00:00               |
| build_rust_channel | release                                  |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

**Comment by hustcer** [comment]
I don't think it's strange: `echo abc | {$in}` should have the similar output with `echo abc | if true {{$in}}`

**Comment by gipsyh** [comment]
> I don't think it's strange: `echo abc | {$in}` should have the similar output with `echo abc | if true {{$in}}`

Oh, I understand thanks.

And I have a question: How should I write in nushell that I can define a local variable in a pipeline?
just like this:
```
echo abc | {
    let a = ...;
    append $a
}
```

**Comment by gipsyh** [comment]
I think we should separate {| | } and { }

**Comment by hustcer** [comment]
> And I have a question: How should I write in nushell that I can define a local variable in a pipeline?
```
echo abc | {
    let a = ...;
    append $a
}
```

What's your expect ? Can you explain it with more detail?

**Comment by gipsyh** [comment]
How to define local variable in a pipeline?

怎么在管道中定义局部变量?

just like:

echo abc | let tmp = d; append $tmp

**Comment by hustcer** [comment]
Is this what you want?
```
echo abc | do {|x| let a = "d"; echo $"($x)-($a)"} $in
```

**Comment by gipsyh** [comment]
> 

yes, that's what I want.

thanks.
