### ISSUE TITLE
Additional types of sort: numeric sort, date/time sort, case insensitive sort, etc

### ISSUE THREAD

**Issue by igor-petruk** [nushell/nushell#553]
It feels like it needs to be pluggable too

**Comment by igor-petruk** [comment]
I think this also depends if the data is properly types. It may be the case for builtins, but not for loaded tables, e.g. from-csv

**Comment by jonathandturner** [comment]
@igor-petruk are there types of sorting you aren't able to do now? We currently support sorting for almost all built-in types, which includes the value loaded from files. Numeric, date/time are supported for sorting. 

I wonder if the files that you're loading from are giving you the values as strings?

**Comment by rusnasonov** [comment]
What about descending sorting? I didn't find option in sort-by to change ordering.

**Comment by klnusbaum** [comment]
> @jonathandturner What about descending sorting? I didn't find option in sort-by to change ordering.

can't you use `| reverse`? e.g.

```
ls | sort-by size | reverse
```

**Comment by JosephTLyons** [comment]
There hasn't been much activity on this issue.  We just landed case-insensitive sorting (https://github.com/nushell/nushell/pull/2225) and I think there is support for most of the other items being requested here.  i'm going to go ahead and close this, but feel free to open a new issue if there is some sort that is missing.  Thanks.
