### ISSUE TITLE
Can't pass flags with `=` into script's main command

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#5532]
### Describe the bug

Can't pass flags with `=` into script's `main` command

### How to reproduce

```nu
# b.nu
def main [kernel: string, --version: string] {
    echo $kernel;
    echo $version
}
```
It's found that `nu b.nu linux --version v5.2` works but `nu b.nu linux --version=v5.2` does not work:
```
@hustcer ➜ tmp git(develop) $> nu b.nu linux --version v5.2
linux
v5.2

@hustcer ➜ tmp git(develop) $> nu b.nu linux --version=v5.2
Error: nu::parser::extra_positional (link)

  × Extra positional argument.
   ╭─[<commandline>:1:1]
 1 │ main "linux" "--version=v5.2"
   ·              ────────┬───────
   ·                      ╰── extra positional argument
   ╰────
  help: Usage: main {flags} <kernel>

```

### Expected behavior

Both of them should work in the same way with the same output

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.62.1                                          |
| branch             | develop                                         |
| tag                |                                                 |
| short_commit       | e9826233                                        |
| commit_hash        | e98262330ebd1ef1fa7c85095cc0d887adde9b10        |
| commit_date        | 2022-05-12 02:04:44 +00:00                      |
| build_os           | macos-x86_64                                    |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)             |
| rust_channel       | stable-x86_64-apple-darwin                      |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01)             |
| pkg_version        | 0.62.1                                          |
| build_time         | 2022-05-12 10:14:24 +08:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | gstat, query, query json, query web, query xml  |

**Comment by merelymyself** [comment]
@hustcer - this is definitely an issue with `deparse.rs`. There is a simple fix, but I feel the whole system for argument parsing for functions should be overhauled in the future, almost every change to `deparse.rs` has introduced new problems. There was a discussion at #5492.

**Comment by hustcer** [comment]
@merelymyself I see, thanks
