### ISSUE TITLE
Error on Nushell Startup

### ISSUE THREAD

**Issue by Shoehorner** [nushell/nushell#5535]
### Describe the bug

Nushell throws an error when calling `nu` from the terminal (using Zsh/PowerShell/etc). This happens when running Warp or iTerm2.

NuShell was installed on my MacBook Pro via Homebrew. 

### How to reproduce

1. Start Terminal application.
2. Type `nu` at prompt to start NuShell.
3. Error occurs immediately starting NuShell. 

### Expected behavior

Prompt appears without errors.

### Screenshots

<img width="1606" alt="image" src="https://user-images.githubusercontent.com/65178086/168322659-9598175e-08be-4cee-84df-c983729da7cd.png">

### Configuration

/Users/shaun〉version | transpose key value | to md --pretty                                                                                                            05/13/2022 12:03:04 PM
| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.61.0                                |
| branch             |                                       |
| tag                |                                       |
| build_os           | macos-x86_64                          |
| rust_version       | rustc 1.59.0                          |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.61.0                                |
| build_time         | 2022-04-12 20:38:15 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

**Comment by rgwood** [comment]
Try replacing `str find-replace` with `str replace` in your config file, `str find-replace` has been renamed/deprecated.

**Comment by fdncred** [comment]
let us know if you have further issues.

**Comment by Shoehorner** [comment]
Thanks for the quick replies. First, I was just bringing this to your attention because this was a clean install so I figured something might be not quite right on first install via Homebrew?

Second, I did change `find-replace` to `replace` and this is the new output:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/65178086/168327548-12931bd4-cbce-4d00-9c55-fee2e9bb9f3b.png">


Thanks for the help guys.

**Comment by rgwood** [comment]
> this was a clean install

Hmm, that's odd. You're sure this wasn't picking up config from an older version of Nu?

> I did change find-replace to replace and this is the new output:

Might be related to another change we made recently. There's been some churn in the configuration and upgrading is not always as smooth as it could be, sorry about that. I'd recommend starting fresh; back up your config file, delete it, start Nu again to create a new config file, then merge whatever you need from the old file in.
