### ISSUE TITLE
Changing `$config.table_mode` does not appear to work on Windows

### ISSUE THREAD

**Issue by adamkpickering** [nushell/nushell#5538]
### Describe the bug

I set `$config.table_mode` to `none` in `$nu.config-path` on Windows 10. However, when I run `ls`, there are still borders around the table.

### How to reproduce

1. Configure `table_mode = none` in nu config file.
2. Close all instances of nushell and start a fresh instance.
3. Run a command that produces a table, for example `ls`.
4. Note that the table still has borders.

### Expected behavior

I expected that borders wouldn't be there after setting `table_mode = none`.

### Screenshots

```
C:\Users\adamk\dev〉echo $config.table_mode
none
C:\Users\adamk\dev〉ls
╭───┬─────────────────┬──────┬─────────┬────────────────╮
│ # │      name       │ type │  size   │    modified    │
├───┼─────────────────┼──────┼─────────┼────────────────┤
│ 0 │ dotfiles        │ dir  │ 4.0 KiB │ 2 days ago     │
│ 1 │ rancher-desktop │ dir  │ 8.0 KiB │ 34 minutes ago │
│ 2 │ test            │ dir  │     0 B │ a week ago     │
╰───┴─────────────────┴──────┴─────────┴────────────────╯
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.62.0                                          |
| branch             |                                                 |
| tag                |                                                 |
| short_commit       | da104050                                        |
| commit_hash        | da104050e6dcf7fbffd41bfd4bdeae1285b7a48c        |
| commit_date        | 2022-05-03 21:50:33 +00:00                      |
| build_os           | windows-x86_64                                  |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01)             |
| pkg_version        | 0.62.0                                          |
| build_time         | 2022-05-03 22:10:37 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by hustcer** [comment]
The first step is the key point, can you show me the code?

**Comment by fdncred** [comment]
`$config` isn't a thing in nushell anymore. we changed it to `$env.config`. Make sure your `let config = { }` in your config.nu is now `let-env config = { }`

**Comment by hustcer** [comment]
`let-env config = { }` works for me on Windows, closing this issue, feel free to reopen if you still have such issue

**Comment by adamkpickering** [comment]
> $config isn't a thing in nushell anymore. we changed it to $env.config. Make sure your let config = { } in your config.nu is now let-env config = { }

Ah you're right, I had `let $config = ...`. Thanks!
