### ISSUE TITLE
`open --raw` appears to not print entire file on Windows

### ISSUE THREAD

**Issue by adamkpickering** [nushell/nushell#5539]
### Describe the bug

When I run `open --raw <filename>` on Windows 10, sometimes it will not print the file properly. As you can see in the example below, the ending bracket for a JSON file is not printed, and then is printed at the beginning of the output of the next command. This is only one character, but I have (recently) seen it not print an entire file, and then prepend that file's contents to the output of the next command.

### How to reproduce

```
ls | save files.json
open --raw files.json
ls
```

### Expected behavior

Print all characters from a command immediately after the command is run and before the next command prompt appears.

### Screenshots

```
C:\Users\adamk\dev〉ls
╭───┬─────────────────┬──────┬─────────┬─────────────╮
│ # │      name       │ type │  size   │  modified   │
├───┼─────────────────┼──────┼─────────┼─────────────┤
│ 0 │ dotfiles        │ dir  │ 4.0 KiB │ 3 days ago  │
│ 1 │ rancher-desktop │ dir  │ 8.0 KiB │ an hour ago │
│ 2 │ test            │ dir  │     0 B │ a week ago  │
╰───┴─────────────────┴──────┴─────────┴─────────────╯
C:\Users\adamk\dev〉ls | save files.json
C:\Users\adamk\dev〉open --raw files.json
[
  {
    "name": "dotfiles",
    "type": "dir",
    "size": 4096,
    "modified": "2022-05-10 16:48:28.452558100 -07:00"
  },
  {
    "name": "rancher-desktop",
    "type": "dir",
    "size": 8192,
    "modified": "2022-05-13 16:12:27.231940200 -07:00"
  },
  {
    "name": "test",
    "type": "dir",
    "size": 0,
    "modified": "2022-05-06 13:01:56.409698100 -07:00"
  }
C:\Users\adamk\dev〉ls
]╭───┬─────────────────┬──────┬─────────┬─────────────╮
│ # │      name       │ type │  size   │  modified   │
├───┼─────────────────┼──────┼─────────┼─────────────┤
│ 0 │ dotfiles        │ dir  │ 4.0 KiB │ 3 days ago  │
│ 1 │ files.json      │ file │   377 B │ now         │
│ 2 │ rancher-desktop │ dir  │ 8.0 KiB │ an hour ago │
│ 3 │ test            │ dir  │     0 B │ a week ago  │
╰───┴─────────────────┴──────┴─────────┴─────────────╯
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.62.0                                          |
| branch             |                                                 |
| tag                |                                                 |
| short_commit       | da104050                                        |
| commit_hash        | da104050e6dcf7fbffd41bfd4bdeae1285b7a48c        |
| commit_date        | 2022-05-03 21:50:33 +00:00                      |
| build_os           | windows-x86_64                                  |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01)             |
| pkg_version        | 0.62.0                                          |
| build_time         | 2022-05-03 22:10:37 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by hustcer** [comment]
Have you ran it several times? everytime with the same output?
seems to be a latency issue, you input when the output haven't
finished

**Comment by fdncred** [comment]
@jntrnr showed me a screenshot of something like this recently. My speculation was that we're not `flush()`ing the stdout somewhere. We should investigate this further I think.

**Comment by fdncred** [comment]
I believe this is fixed in the latest main. Please re-open if you still experience this problem.
