### ISSUE TITLE
nu formatter

### ISSUE THREAD

**Issue by gipsyh** [nushell/nushell#5540]
### Related problem

in docs/sample_config, there are both 2 spaces tab and 4 spaces tab.

It would be nice if there was  a nu-formatter.

### Describe the solution you'd like

nu-formatter

**Comment by hustcer** [comment]
Thanks for your suggestion, It's a pretty good idea, since just found that there is a similar issue here: https://github.com/nushell/nushell/issues/3938.  I will close this one in favor of that.
