### ISSUE TITLE
nu script doesn't have access to config functions

### ISSUE THREAD

**Issue by danjenson** [nushell/nushell#5544]
### Describe the bug

I have the following script
```
#!/usr/bin/env nu
gdrive sync . class/simulation/lectures/
```
Where `gdrive sync` is defined in my `config.nu`, but if I run this as a linux script, it doesn't find the command.

In bash, you can do `export -f <func>` -- is there anything similar for nushell?

### How to reproduce

Create a UDF in config.nu.
Try to use it in a script.

### Expected behavior

I would be able to use UDFs the same as built-ins.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.62.0                                          |
| branch             |                                                 |
| tag                |                                                 |
| build_os           | linux-x86_64                                    |
| rust_version       | rustc 1.61.0-nightly (ab0c2e18d 2022-03-27)     |
| rust_channel       | nightly-x86_64-unknown-linux-gnu                |
| cargo_version      | cargo 1.61.0-nightly (109bfbd 2022-03-17)       |
| pkg_version        | 0.62.0                                          |
| build_time         | 2022-05-03 18:02:54 -07:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
I'm wondering if nushell is loading the config.nu and env.nu when running a nu script like this.

**Comment by kubouch** [comment]
Yeah, when you run a script like `nu script.nu`, it won't read the config.

**Comment by WindSoilder** [comment]
Is it ok to always load config.nu and env.nu whatever user run nu like `nu script.nu` and `nu -c ls` ?

**Comment by WindSoilder** [comment]
Is it ok to load config whatever using nu like `nu script.nu` and `nu -c ls`?

**Comment by fdncred** [comment]
Technically, there is a config loaded because I used it with the `--table-mode` functionality. You can see it in crates/nu-cli/src/commands.rs in the evaluate_commands() function. It's just that this all happens in a separate part of code where the "real" config doesn't load.

I'm not sure we want to load the config or not.

**Comment by WindSoilder** [comment]
Hmm... It seems that only you provide `--table-mode`, the config will be loaded.

For the issue case, I think it's going to `evaluate_file`, which is not loading config file too.

> I'm not sure we want to load the config or not.
I'm not sure either, If we always load the config, I don't know if there is a potential case we need to handle.

**Comment by danjenson** [comment]
Why not make it an opt-in when running scripts or provide a -l,--library command that loads functions from a given file?

**Comment by kubouch** [comment]
One argument against loading config by default when running scripts is portability. If you rely on implicit loading of your local config and send the script to your friend's machine, the friend won't be able to run it. 

We already have `--config` and `--env-config` flags to `nu` so maybe we could change it that when you specify them, it would load the config but otherwise not?

**Comment by DejayRezme** [comment]
powershell loads the config / profile.ps1 when executing a command. 
What does bash do? 

I suspect if a script depends on specific modules or functions to run then that will be tricky either way, and not loading the config doesn't really help.

**Comment by danjenson** [comment]
I like that idea @kubouch , and it seems natural -- I tried specifying those next to see if they worked

**Comment by fdncred** [comment]
ya, I think `--config` and `--env-config` is a good compromise too.

**Comment by WindSoilder** [comment]
Hmm... Is that means the following?
1. if `--config` is specified without value, load default config 
2. if `--config` is specified with value, like `--config a.nu`, load `a.nu` as config file, but not load default config.
3. if `--config` is not provided, don't load config?

**Comment by kubouch** [comment]
I think the way signature parsing works in Nushell is that either you have a flag `--config` or a `--config file.nu` with a required value. So for a start we could just go for always requiring a value after `--config`.

**Comment by hustcer** [comment]
Thanks @WindSoilder , `nu --config my/config.nu -c 'custom-command'` works on the latest main, I have just tested it on my mac. Feel free to reopen if it doesn't work for you

**Comment by kubouch** [comment]
So the solution here is to pass a `--config` flag manually.
