### ISSUE TITLE
Inconsistent behavior listing files in hidden directories

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#5545]
### Describe the bug

`ls **/*abc*`:

* ... returns files inside a hidden directory if `abc` is **not** in the name of the hidden directory
* ... but ignores files matching `*abc*` if they are in a directory that also matches `*abc*`.

Sorry if this is confusing -- Hopefully the "How to Reproduce" will make it more clear.

### How to reproduce

```
> mkdir tmp
> cd tmp
> mkdir .abcdef
> touch .abcdef/abcdef
> touch .abcdef/ghijkl
> ls **/*e* # no results
> ls **/*g*
╭───┬────────────────┬──────┬──────┬─────────────╮
│ # │      name      │ type │ size │  modified   │
├───┼────────────────┼──────┼──────┼─────────────┤
│ 0 │ .abcdef/ghijkl │ file │  0 B │ 2 hours ago │
╰───┴────────────────┴──────┴──────┴─────────────╯

> ls **/* # also (as expected) no results
```

### Expected behavior

At the least, it should be consistent.  Either both `ls` examples in the "repro" should return results or neither should.

I *think* that:

* `ls **/*g*` should never return files under the hidden directory.
* `ls -a **/*g*` *should* return files where any part of the path/filename contains a `g`

### Configuration

Running under WSL in Windows, but also reproducible on standard Linux.  I have not yet tested with folders with a hidden *attribute* under Windows Nu.

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.61.0                                   |
| branch             |                                          |
| tag                |                                          |
| short_commit       | 3783c19d                                 |
| commit_hash        | 3783c19d02f4a3b2f35cd26b79daabcb70b04880 |
| commit_date        | 2022-04-12 20:38:15 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)        |
| pkg_version        | 0.61.0                                   |
| build_time         | 2022-04-12 20:51:54 +00:00               |
| build_rust_channel | release                                  |
| features           | dataframe, default, trash, which, zip    |
| installed_plugins  |                                          |

### Additional context

Originally found while researching [this Super User question](https://superuser.com/q/1720919/1210833).

**Comment by fdncred** [comment]
Can you try on the latest main and see if the problem still exists?

**Comment by NotTheDr01ds** [comment]
@fdncred Still there in ...

```
╭────────────────────┬──────────────────────────────────────────╮
│ version            │ 0.62.1                                   │
│ branch             │                                          │
│ tag                │                                          │
│ short_commit       │ c047fd47                                 │
│ commit_hash        │ c047fd4778f32f4705295362c40371c83ffcfb9a │
│ commit_date        │ 2022-05-14 20:09:41 +00:00               │
│ build_os           │ linux-x86_64                             │
│ build_os           │ x86_64-unknown-linux-gnu                 │
│ rust_version       │ rustc 1.60.0 (7737e0b5c 2022-04-04)      │
│ rust_channel       │ stable-x86_64-unknown-linux-gnu          │
│ cargo_version      │ cargo 1.60.0 (d1fd9fe 2022-03-01)        │
│ pkg_version        │ 0.62.1                                   │
│ build_time         │ 2022-05-15 13:46:45 -04:00               │
│ build_rust_channel │ release                                  │
│ features           │ default, trash, which, zip               │
│ installed_plugins  │                                          │
╰────────────────────┴──────────────────────────────────────────╯
```

**Comment by fdncred** [comment]
I think this depends on how the `nu-glob` crate works. It seems to me that both `ls **/*g*` and `ls -a **/g*` could both return the same results hidden or not since dot_files and dot_folders could be included in the `*` wildcard.

It's also interesting that if you do `^ls **/*g*` and `^ls **/*e*` they return results but if you're in fish or bash by themselves they don't return results.

Feel free to take a run at it if you want to try and change this behavior.

**Comment by NotTheDr01ds** [comment]
@fdncred I'll take a look, but I don't trust my (nearly non-existent) Rust skills enough at the moment to contribute.  I'm hoping to get there eventually, but not yet.

And yes, I also notice that (the experimental) `glob **/*` returns results in hidden directories, so I'm assuming that means that `ls` has a separate set of globbing rules?

The Fish doc does say:

> Hidden files (where the name begins with a dot) are not considered when wildcarding unless the wildcard string has a dot in that place.

Of course, Fish is a *nix-only shell, so one can always fall back to the `find` binary.  Falling back to `^find` in Nushell means that the solution is no longer Windows-compatible.  Just a thought ...

**Comment by fdncred** [comment]
just fyi - the `glob` command uses a different globbing library that isn't as custom as our `nu-glob` crate.
