### ISSUE TITLE
where returns no results when passed a block stored in a variable (but each/reduce work as expected)

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#5547]
### Describe the bug

`where` returns no results when passed a variable containing a block.  The same block works when passed as a literal.  `reduce` and `each`, however, work as expected when passed a block in a variable.  

### How to reproduce

```
> seq 1 6 | where {|a| $a > 3 }
╭───┬───╮
│ 0 │ 4 │
│ 1 │ 5 │
│ 2 │ 6 │
╰───┴───╯

> let filter = {|a| $a > 3 }
> seq 1 6 | where $filter
# No results

> seq 1 6 | each $filter
╭───┬───────╮
│ 0 │ false │
│ 1 │ false │
│ 2 │ false │
│ 3 │ true  │
│ 4 │ true  │
│ 5 │ true  │
╰───┴───────╯

> let reduction = {|it, acc| $it + $acc }
> seq 1 6 | reduce $reduction
21
```

### Expected behavior

I think I should expect that `where` will function the same regardless of whether it is passed a literal block or a variable block.  If this is a case of parsing vs. evaluation, I can't discern why `reduce` and `each` work differently.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.62.1                                   |
| branch             |                                          |
| tag                |                                          |
| short_commit       | c047fd47                                 |
| commit_hash        | c047fd4778f32f4705295362c40371c83ffcfb9a |
| commit_date        | 2022-05-14 20:09:41 +00:00               |
| build_os           | linux-x86_64                             |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)        |
| pkg_version        | 0.62.1                                   |
| build_time         | 2022-05-15 13:46:45 -04:00               |
| build_rust_channel | release                                  |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I just tried this and it seems to work now.
```
> let filter = {|a| $a > 3 }
> seq 1 6 | where -b $filter
╭───┬───╮
│ 0 │ 4 │
│ 1 │ 5 │
│ 2 │ 6 │
╰───┴───╯
```
