### ISSUE TITLE
Line comments break multiline pipelines (except in subexpressions)

### ISSUE THREAD

**Issue by Benjamin-L** [nushell/nushell#5559]
### Describe the bug

Although this behavior is not mentioned explicitly in the docs that I could find, it is possible to split pipelines across multiple lines without them being embedded in a subexpression. For example:

```nu
echo "test" |
    str capitalize
```

evaluates to `Test`.

Adding a comment at at the end of lines in this kind of multiline pipe seems to break it up into separate expressions, evaluating to a different result.

### How to reproduce

run the following:

```nu
echo "test" | # this comment should not affect semantics
    str capitalize
```

### Expected behavior

This should evaluate to the same result whether or not the comment is present, so the output should be `Test`, just like the example without the comment. Alternatively, if multiline pipelines that aren't enclosed in a subexpression aren't an intended feature, both examples should throw an error. The thing that matters is that it's consistent.

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.61.0                                |
| branch             |                                       |
| tag                |                                       |
| build_os           | macos-x86_64                          |
| rust_version       | rustc 1.60.0                          |
| cargo_version      | cargo 1.60.0                          |
| pkg_version        | 0.61.0                                |
| build_time         | 1980-01-01 00:00:00 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

### Additional context

Notably, this _does not_ occur with multiline pipelines that are embedded in a subexpression. In that case, the comment has no effect, as expected.

**Comment by hustcer** [comment]
Related: https://github.com/nushell/nushell/issues/5517

**Comment by Benjamin-L** [comment]
Oh this seems like it might be a duplicate. I'd be good with closing this one.

**Comment by WindSoilder** [comment]
Thanks for the issue, I'd consider it as different to #5517, so I'll reopen it
