### ISSUE TITLE
Flatten still seems weild

### ISSUE THREAD

**Issue by WindSoilder** [nushell/nushell#5589]
Sorry I don't know if it's a bug, just want to open for discussion.

Follow the discussion in the (https://github.com/nushell/nushell/pull/5584#issuecomment-1131618816) 

when we want to flatten `foo.json` file:
```json
[
    {
        "people": {
            "name": "Andres",
            "meal": "arepa"
        },
        "city": [{"name": "Guayaquil"}, {"name": "Samborondón"}]
    },
    {
        "people": {
    	    "name": "Katz",
            "meal": "nurepa"
        },
        "city": [{"name": "Oregon"}, {"name": "Brooklin"}]
    }
]
```
2. open foo.json | flatten
```
> open foo.json 
╭───────────────────┬────────────────╮
│      people       │      city      │
├───────────────────┼────────────────┤
│ {record 2 fields} │ [table 2 rows] │
│ {record 2 fields} │ [table 2 rows] │
├───────────────────┼────────────────┤
│      people       │      city      │
╰───────────────────┴────────────────╯
> open foo.json | flatten
╭────────┬────────┬─────────────╮
│  name  │  meal  │  city_name  │
├────────┼────────┼─────────────┤
│ Andres │ arepa  │ Guayaquil   │
│ Andres │ arepa  │ Samborondón │
│ Katz   │ nurepa │ Oregon      │
│ Katz   │ nurepa │ Brooklin    │
├────────┼────────┼─────────────┤
│  name  │  meal  │  city_name  │
```

While flatten `people` column, I think the behavior is ok.

But for `city` column, `flatten` is flatten one more level inside table.
Because table itself is a list of records, it may be intuitively to transfer from `table 2 rows` to tow raws of `record`, just like what `0.44 version` does, if user want to get `city_name`, just call `flatten` again.

But this behavior will be conflict with [flatten's example](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/filters/flatten.rs#L64-L68) and example in #5443 

Maybe we should make the decision about what if input is a table?  
1. keep the behavior currently, if input is table, just flatten one more level to flatten inner record out, Or,
2. just flatten one level at a time, in this case, transfer from `table` to `record`
So the output will be something like this:
```
╭───┬────────┬────────┬──────────────────╮
│ # │  name  │  meal  │       city       │
├───┼────────┼────────┼──────────────────┤
│ 0 │ Andres │ arepa  │ {record 1 field} │
│ 1 │ Andres │ arepa  │ {record 1 field} │
│ 2 │ Katz   │ nurepa │ {record 1 field} │
│ 3 │ Katz   │ nurepa │ {record 1 field} │
╰───┴────────┴────────┴──────────────────╯
```

Personally I stand for the second option, because it seems more consistent with [rust std flattern](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.flatten), we flatten at most one level at a time.

But maybe users has different perspective about `table`?  And that's why example #5443 and [flatten's example](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/filters/flatten.rs#L64-L68) exists.

**Comment by WindSoilder** [comment]
Oh, I think I know what user might thing about flatten behavior.

Image we have a json file like this:
```
[
    {
        "people": "hi",
        "city": [{"name": "Guayaquil"}, {"name": "Samborondón"}]
    }
]
```

while open it:
```
╭───┬────────┬────────────────╮
│ # │ people │      city      │
├───┼────────┼────────────────┤
│ 0 │ hi     │ [table 2 rows] │
╰───┴────────┴────────────────╯
```

What user thought about this:
```
╭───┬────────┬────────────────╮
│ # │ people │      city      │
├───┼────────┼────────────────┤
│ 0 │ hi     │  ╭───┬─────────────╮
|   |        |  │ # │    name     │
|   |        |  ├───┼─────────────┤
|   |        |  │ 0 │ Guayaquil   │
|   |        |  │ 1 │ Samborondón │
|   |        |  ╰───┴─────────────╯ │
╰───┴────────┴────────────────╯
```

And then flatten on `city` would make `name` move up to top column and replace `city` column....

**Comment by fdncred** [comment]
We should talk about this in #design-discussion in discord to see what direction we want to go. I kind of like the nested tables thing, up to a point, but I think it would be tricky to add.

**Comment by WindSoilder** [comment]
As discussion result, it's better to provide `--all` flag to control relative behavior

**Comment by fdncred** [comment]
I still like the idea of showing nested tables but we can save that for a later time.
