### ISSUE TITLE
`error make` should have a span by default

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#5591]
### Describe the solution you'd like

Currently, `error make` will produce unspanned error by default. Instead, the error should point at the point where `error make` was called.

Current:
```
> error make { msg: "foo" }
Error:
  × foo
```

Desired:
```
> error make { msg: "foo" }

Error:
  error make { msg: "foo" }
  ────┬─────
      ╰── foo
```

### Additional context and details

Unspanned errors are super hard to debug if you have a larger script. At least pointing at where the error originates from makes a huge difference.

I think it should be possible to change the current error to a spanned error and add `call.head` as the span inside the `error make` command implementation.

**Comment by sholderbach** [comment]
![image](https://user-images.githubusercontent.com/15833959/169599127-9eca8817-a930-41dc-9fbd-22c14655eac4.png)

vs 

![image](https://user-images.githubusercontent.com/15833959/169599283-4e19b21c-fb8d-4318-8c3d-bc8498cbfb73.png)

**Comment by sholderbach** [comment]
@kubouch another option to consider:

![image](https://user-images.githubusercontent.com/15833959/169603341-6a868e9c-fb86-4000-863f-895822ee00a1.png)

**Comment by kubouch** [comment]
@sholderbach I prefer the first option (have some default "originates from here" default label if label is not specified).

**Comment by kubouch** [comment]
And I would point at the `error make`. Just my preferences,

**Comment by sholderbach** [comment]
Yeah that would be my preference as well. Updated the PR. Previously in the PR for the `{msg: "text"}` case:
![image](https://user-images.githubusercontent.com/15833959/169615508-12d34502-c1b5-4e95-869e-a85f576de99f.png)
