### ISSUE TITLE
Investigate a possibly more stream-lined data representation

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#560]
Right now we used Tagged<Value> everywhere. This is very flexible, but it can be a bit cumbersome to debug as well as cumbersome for people writing plugins in other languages.

Here's an example of the underlying content if you open Cargo.toml:

"Tagged { tag: Tag { origin: Some(96453e21-0f41-4d73-83de-7e14e991de8b), span: Span { start: 5, end: 15 } }, item: Object(Dictionary { entries: {"bin": Tagged { tag: Tag { origin: None, span: Span { start: 0, end: 4 } }, item: List([Tagged { tag: Tag { origin: None, span: Span { start: 0, end: 4 } }, item: Object(Dictionary { entries: {"name": Tagged { tag: Tag { origin: None, span: Span { start: 0, end: 4 } }, item: Primitive(String("nu_plugin_inc")) }, "path": Tagged { tag: Tag { origin: None, span: Span { start: 0, end: 4 } }, item: Primitive(String("src/plugins/inc.rs")) }} }) }, Tagged { tag: Tag { origin: None, span: Span { start: 0, end: 4 } }, item: Object(Dictionary { entries: {"name": Tagged { tag: Tag { origin: None, span: Span { start: 0, end: 4 } }, item: Primitive(String("nu_plugin_sum")) }, "path": Tagged { tag: Tag { origin: None, span: Span { start: 0, end: 4 } }, item: Primitive(String("src/plugins/sum.rs")) }} }) }, Tagged { tag: Tag { origin: None, span: Span { start: 0, end: 4 } }, item: Object(Dictionary { entries: {"name": Tagged { tag: Tag { origin: None, span: Span { start: 0, end: 4 } }, item: Primitive(String("nu_plugin_add")) }, "path": Tagged { tag: Tag { origin: None, span: Span { start: 0, end: 4 } }, item: Primitive(String("src/plugins/add.rs")) }} }) }, Tagged { tag: Tag { origin: None, span: Span { start: 0, end: 4 } }, item: Object(Dictionary { entries: {"name": Tagged { tag: Tag { origin: None, span: Span { start: 0, end: 4 } }, item: Primitive(String("nu_plugin_edit")) }, "path": Tagged { tag: Tag { origin: None, span: Span { start: 0, end: 4 } }, item: Primitive(String("src/plugins/edit.rs")) }} }) }, Tagged { tag: Tag { origin: None, span: Span { start: 0, end: 4 } }, item: Object(Dictionary { entries: {"name": Tagged { tag: Tag { origin: None, span: Span { start: 0, end: 4 } }, item: Primitive(String("nu_plugin_str")) },..."

You'll notice the same Tag (origin + span) is repeated over and over again. This is probably fine for small data sets but we should measure what the penalty is for over-the-wire (like communicating with plugins)

**Comment by thegedge** [comment]
@jonathandturner anything to do here?
