### ISSUE TITLE
redundant suggestions

### ISSUE THREAD

**Issue by gipsyh** [nushell/nushell#5623]
### Describe the bug

<img width="750" alt="截屏2022-05-24 19 17 21" src="https://user-images.githubusercontent.com/42509521/170022887-792e042e-240e-4e6a-b72a-e32808a4c55d.png">

### How to reproduce

1. type `$nu.e`
2. press `tab`

### Expected behavior

env-path only

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.62.0                              |
| branch             |                                     |
| tag                |                                     |
| build_os           | linux-aarch64                       |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18) |
| rust_channel       | stable-aarch64-unknown-linux-gnu    |
| cargo_version      | cargo 1.61.0 (a028ae4 2022-04-29)   |
| pkg_version        | 0.62.0                              |
| build_time         | 2022-05-21 08:55:06 +00:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |

**Comment by sholderbach** [comment]
Confirmed on bleeding edge

**Comment by herlon214** [comment]
Yeah, it's a bug once the filter got removed from the `Completer` trait, now I think the filter needs to be done inside each completion. Which in this case the `variable_completion.rs` is probably missing.
