### ISSUE TITLE
Support `--foo=bar`

### ISSUE THREAD

**Issue by Aloso** [nushell/nushell#564]
To download an exercise on [Exercism](https://exercism.io), one needs to copy+paste a shell command, e.g.

```bash
exercism download --exercise=anagram --track=kotlin
```

However, it doesn't work in Nushell:

```bash
error: Parse Error
- shell:1:28
1 | exercism download --exercise=anagram --track=kotlin
  |                             ^^^^^^^^^^^^^^^^^^^^^^^
```

To make it work, the `=` have to be replaced with spaces:

```bash
exercism download --exercise anagram --track kotlin
```

This is quite annoying :(

If you don't intend to support this syntax, at least **a better error message is required**.

**Comment by jonathandturner** [comment]
@Aloso - this is fixed in the last version of Nu in master. Closing this issue as it should be available in the next public release.

**Comment by Aloso** [comment]
@jonathandturner  Thanks! I really appreciate your work, and already use `nushell` as my default shell!
