### ISSUE TITLE
hash base64 decoder does not ignore newlines

### ISSUE THREAD

**Issue by Yethal** [nushell/nushell#5664]
### Describe the bug

base64 decoding fails if input contains newlines

### How to reproduce

1. Run `fetch https://api.github.com/repos/nushell/nushell/contents/build-all.nu | get content | hash base64 -d`
2. Notice error message `invalid base64 input for character set standard`
3. Run `fetch https://api.github.com/repos/nushell/nushell/contents/build-all.nu | get content | lines -s | str collect | hash base64 -d`
4. Notice file contents successfully decoded

### Expected behavior

I expected base64 decoder to ignore newline characters

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.63.0                                              |
| branch             |                                                     |
| commit_hash        |                                                     |
| build_os           | linux-x86_64                                        |
| build_target       | x86_64-unknown-linux-gnu                            |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)                 |
| rust_channel       | stable-x86_64-unknown-linux-gnu                     |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)                   |
| pkg_version        | 0.63.0                                              |
| build_time         | 2022-05-25 07:30:15 +02:00                          |
| build_rust_channel | release                                             |
| features           | database, dataframe, default, trash, which, zip     |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by fdncred** [comment]
Along with fixing this, I'd also like to be able to call `hash base64` on a binary file. So, if I wanted to encode and image. I think it currently fails.
