### ISSUE TITLE
Aliases don't work with subcommand completions

### ISSUE THREAD

**Issue by Dan-Gamin** [nushell/nushell#5666]
### Describe the bug

I'm currently working on custom completions for `cargo` and I wanted to see how they would work with aliases. My alias for `cargo` is `cg`. When typing `cg` it works perfectly as expected, but when I type a subcommand such as `cg help` the highlighting is off:
![image](https://user-images.githubusercontent.com/58695417/170768296-dc3f8536-583f-4296-9b7a-36f1946bc528.png)
That's weird, but it gets worse. If I tried to tabcomplete after typing `cg help `, it would produce a panic:
```
thread 'main' panicked at 'internal error: span missing in file contents cache', crates\nu-protocol\src\engine\engine_state.rs:563:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### How to reproduce

1. In `config.nu` there should be `git` completions.
2. In `config.nu` add `alias test = git`
3. Open up nu.
4. Type `test fetch`,  `test checkout`, or `test push` and try to use the completions.
5. **Panic.**

### Expected behavior

The completions should have worked as expected with the only change from using the actual command is the first part of the command, nu should have had the correct highlighting and nu shouldn't have panicked when trying to use the completions.

### Screenshots

![image](https://user-images.githubusercontent.com/58695417/170768630-c04e1337-506e-4eda-85cc-33aa3fc8b3c8.png)

### Additional context

Possibly has something to do with #4708

**Comment by Kangaxx-0** [comment]
The reason why nu panicked is because -> if the input is an alias, the parser will  find the alias and reparse the expression, e.g - `test checkout` and `alias test = git`, the final **call**'s span start and end will be messed up, and finally, `get_span_contents` method panicked.

**Comment by herlon214** [comment]
Yeah, seems related to https://github.com/nushell/nushell/pull/4707 once it reparses the alias span. If we keep the original span might break the PR's addition (not sure though).

**Comment by Kangaxx-0** [comment]
Take `g = git` -> alias, and input `g checkout` as an example. If I say - Inside [completion_helper](https://github.com/nushell/nushell/blob/main/crates/nu-cli/src/completions/completer.rs#L59) method, if we do extra logic to determine if the input `line` has an **alias**:
1. If it is found, calculate an offset, then substitute `g` with `git`, offset is 2
2. Instead of `g checkout`, parse `git checkout` as what it does now, and `flatten_expression` the output
3. Create a new `Span` by minus the offset at step 1, something like
```
let new_span = Span {
    start: flat.0.start - offset,
    end: flat.0.end - 1 - offset,
 };
```
4. Process custom completion

I was doing a hacking test, and it worked. Should we continue this approach?

**Comment by herlon214** [comment]
@Kangaxx-0 did the tests passed?
As far as we discussed on discord (**#implementation-chat**) looks like it's a bigger change and it has something to do with how we evaluate the alias.

**Comment by Kangaxx-0** [comment]
I did try hardcode it, and it worked, imo, change the parse and eval seems like a big thing, so I could try to submit a pr just use my approach and see how thing goes?

**Comment by herlon214** [comment]
Sure, go for it @Kangaxx-0

**Comment by Kangaxx-0** [comment]
> Sure, go for it @Kangaxx-0

Thanks, will do

**Comment by Kangaxx-0** [comment]
My WSL2 development box gets corrupted for some reason, so I need to set up my dev box again. A few updates:
- I've made the alias working with sub-command. E.g - `g = git`, then `g pull` and `g checkout` work fine
<img width="473" alt="image" src="https://user-images.githubusercontent.com/85712372/172744799-f27fd047-8eea-41e3-8d08-faaca202d8ba.png">
However, duding my test, the concern still failed. E.g - `g=git` and `co=checkout`, then when I type `g co [tab]`, nu still panicked
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/85712372/172744957-9da878ab-4826-485c-b79d-e7e53d2ba9c7.png">
I will have to take care of multiple alias chaining scenario, stay tuned :)

**Comment by herlon214** [comment]
Very cool @Kangaxx-0! Just a few more steps 😄

**Comment by hustcer** [comment]
@Kangaxx-0 So can we close this issue now?

**Comment by Kangaxx-0** [comment]
> @Kangaxx-0 So can we close this issue now?

I would say - yes
