### ISSUE TITLE
Autocomplete fails with apostrophe and space in directory name

### ISSUE THREAD

**Issue by JBanks** [nushell/nushell#5669]
### Describe the bug

Assume the desired directory one wants to move to contains an apostrophe.  When performing tab completion, the string is wrapped with a single quotation mark (commonly used as the apostrophe).  The apostrophe will be treated as a string wrapper and remove the rest of the directory name from the argument.

### How to reproduce

1. Name a directory with an apostrophe
2. Type `cd` along with the first few letters of the directory name
3. Press <tab> and then select the directory using tab completion.

### Expected behavior

The apostrophe could be escaped like zsh's autocomplete, or it could choose a different string wrapper depending on the content of the string.  I think escaping would be the safest and easiest way.

### Screenshots

<img width="650" alt="image" src="https://user-images.githubusercontent.com/453768/170795856-10d1989a-eaef-483e-8d90-4bafc8dd5f40.png">
<img width="650" alt="image" src="https://user-images.githubusercontent.com/453768/170795802-8b94e3a8-c934-4f64-aafe-0260199c4b2c.png">

### Configuration

| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.61.0                                |
| branch             |                                       |
| tag                |                                       |
| build_os           | macos-x86_64                          |
| rust_version       | rustc 1.59.0                          |
| cargo_version      | cargo 1.59.0                          |
| pkg_version        | 0.61.0                                |
| build_time         | 2022-04-12 20:38:15 +00:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

### Additional context

Onedrive names these directories, so renaming the directory is not an option.

**Comment by herlon214** [comment]
Thanks for reporting it @JBanks but iirc that was fixed already. Now we're using backticks to quote the file name.
Check the latest version `0.63.0`, I can see you're using `0.61.0`
