### ISSUE TITLE
Add `--output(-o)` flag to `fetch`

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#5670]
### Related problem

`fetch` command could be used to download files:
```
fetch https://github.com/jftuga/less-Windows/releases/download/less-v590/less.exe
```
But the downloaded contents will be printed to the stdout, we can use `fetch ... | save -r less.exe` but it's not straightforward enough, especially for the new users

### Describe the solution you'd like

Add `--output(-o)` flag to `fetch` to specify the saving location for the downloaded file

**Comment by sholderbach** [comment]
@hustcer I nudged @merelymyself to use `-f`/`--file` instead if thats ok for you as well.

**Comment by hustcer** [comment]
> @hustcer I nudged @merelymyself to use `-f`/`--file` instead if thats ok for you as well.

curl use `--output`, wget use `--output-file`, aria2c use `--out`, I think `--file` is not a good choice here, `--output-file` should be better if we want to have `file` in the flag
