### ISSUE TITLE
Completion definitions for external commands will make all undefined flags invalid

### ISSUE THREAD

**Issue by sholderbach** [nushell/nushell#5672]
### Describe the bug

Initial report: https://github.com/nushell/nushell/issues/5656#issuecomment-1139916185

For commands for which a completion definition exists flags that are not part of the completion definition become hard errors when you invoke them regularly. (not an issue if invoked with `^the-external-command --undocumented`)

I want to put this up for discussion as the behavior might be unexpected/annoying if a program adds flags and the completion definition is out of sync. 

### How to reproduce

1. Remove `--dry-run` completion definition from the `config.nu` example completion definition of `git push`
2. Refresh nu
3. Run `^git push --dry-run`, this will just work
4. Run `git push --dry-run` 
![image](https://user-images.githubusercontent.com/15833959/170820980-f3bf5742-0fb2-48aa-9320-ec48cb7782de.png)

### Expected behavior

We should probably tolerate that we might not know all the flags and allow the underlying program to decide if it wants to report and unknown flag error.

This would also prevent users from omitting spaces between short flags and values like coreutils `sort -k1`

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.63.1                                   |
| branch             | main                                     |
| commit_hash        | d69a4db2e7d3b5dd65be6ee41f42cf1dc695b91d |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.61.0 (a028ae4 2022-04-29)        |
| pkg_version        | 0.63.1                                   |
| build_time         | 2022-05-26 23:22:20 +02:00               |
| build_rust_channel | debug                                    |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

**Comment by CAD97** [comment]
Especially since the `^extern` option exists, it'd be nice for the current strict behavior to still be *available*. (An example case where this would be desirable is if the completions are auto-updated when the tool updates.)

**Comment by poliorcetics** [comment]
This bit me recently when a tool I used added a flag and I couldn't manae to call it because I had previously written completions for it

**Comment by sholderbach** [comment]
Closed by #7527
