### ISSUE TITLE
Operations on records change the shape of value

### ISSUE THREAD

**Issue by Yethal** [nushell/nushell#5674]
### Describe the bug

Operations on records (such as transpose and transpose back or update cells) output a table containing the record and not the record itself
(Provide repro steps are exemplary, issue occurs regardless of what we do with the record other than running simple update 'columnname'

### How to reproduce

1. Run `git status | complete | describe`
2. Notice the output is `record<stdout: string, stderr: string, exit_code: int>`
3. Run `git status | complete | transpose | transpose -i -r | describe`
4. Notice the output is `table<stdout: string, stderr: string, exit_code: int>`
5. Run `git status | complete | transpose | transpose -i -r | get 0 | describe`
6. Notice the output is `record<stdout: string, stderr: string, exit_code: int>` (same as original)

### Expected behavior

I expected operations on record to return the record matching the original input and not a table that contains said record

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.63.0                                              |
| branch             | master                                              |
| commit_hash        |                                                     |
| build_os           | linux-x86_64                                        |
| build_target       | x86_64-unknown-linux-gnu                            |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)                 |
| rust_channel       | stable-x86_64-unknown-linux-gnu                     |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)                   |
| pkg_version        | 0.63.0                                              |
| build_time         | 2022-05-25 07:30:15 +02:00                          |
| build_rust_channel | release                                             |
| features           | database, dataframe, default, trash, which, zip     |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

### Additional context
This is particularly annoying when updating json/yaml files in place because the data structure in the output will not match the input which will cause whatever consumes those files to throw an error unless we add `get 0` at the end of the pipeline which works but is not obvious and should not be necessary

**Comment by fdncred** [comment]
I changed 5 because you had `describe | get 0` and I think you meant `get 0 | describe`.

I see what you're saying and I generally agree with you. I've tried to update deeply nested json files before and it's a massive pain. I wonder if it's a pain because of what you're saying here.

**Comment by Yethal** [comment]
It's one of the reasons together with the fact that we can't iterate over columns and the fact that updating nested fields without changing the data shape require writing a long-ass cell path twice, for example to update a container in k8s deployment object I need to do `update spec.template.spec.containers.0 { get spec.template.spec.containers.0 | reject readinessProbe livenessProbe }`

**Comment by WindSoilder** [comment]
I think it's relatively hard because the following yields to same result:
```
> {a: 3, b: 4} | transpose
╭───┬─────────┬─────────╮
│ # │ column0 │ column1 │
├───┼─────────┼─────────┤
│ 0 │ a       │       3 │
│ 1 │ b       │       4 │
╰───┴─────────┴─────────╯
> [[a,b]; [3 4]] | transpose
╭───┬─────────┬─────────╮
│ # │ column0 │ column1 │
├───┼─────────┼─────────┤
│ 0 │ a       │       3 │
│ 1 │ b       │       4 │
╰───┴─────────┴─────────╯
```

And then the second `transpose -i -r` doesn't know if it should transfer back to a table of a record...

Is it ok to provide a flag like `--as-record`?  In this case, if we transfer to a result is `table<stdout: string, stderr: string, exit_code: int>`, we automatically convert it to  `record<stdout: string, stderr: string, exit_code: int>`?

**Comment by fdncred** [comment]
> Is it ok to provide a flag like --as-record?

Yes, I'm willing to give that a try to see how helpful it is. It kind of makes me think we should have a `to table` and `to record` or something like that.

**Comment by WindSoilder** [comment]
@Yethal Hi, can you please test the latest `main` build to see if `--as-record` flag suited for your need?

**Comment by Yethal** [comment]
@WindSoilder sure, no problem. Regarding the transposition itself, the problem would go away if we could just iterate on columns and pass key and value as separate arguments to the each block. sth like $record|each col {|k,v| #do sth with k and v separately here}

**Comment by Yethal** [comment]
@WindSoilder Unfortunately I just ran into a different repro steps that showcase the same issue. Running `$record|sort|describe` also changes the output into a single row table

**Comment by WindSoilder** [comment]
Thanks for reporting :)  

Different command has different implementation, so other inner commands may have similer issue.  For `sort`, I can try to fix it

**Comment by Yethal** [comment]
I realize that the issue would probably need to be fixed separately in every affected command one by one but the issue is quite broad, if I'm piping a record in I expect to get a record out unless the command explicitly changes the data shape (like get does)

**Comment by WindSoilder** [comment]
I found there is a question, for sort record, do you expect sort record by key?  Or sort record by values?

**Comment by WindSoilder** [comment]
@Yethal Refer to record definition
https://www.nushell.sh/book/types_of_data.html#records

I don't think record should support sorting by internal key or values, is it ok to just return the record itself ?

```
> {a: 3, b: 4, c: 1} | sort 
{a: 3, b: 4, c: 1}
```

**Comment by hustcer** [comment]
> I don't think record should support sorting by internal key or values, is it ok to just return the record itself ?

Agreed

**Comment by Yethal** [comment]
@WindSoilder It's okay to return the record unchanged (although lexical sorting by either key or value would be nice) as long as it's still that same record and not a table containing it

**Comment by fdncred** [comment]
I'd support sorting by keys or values. why wouldn't we allow sorting?

**Comment by WindSoilder** [comment]
Hmm... Ok, but..

Sorry I'm failed to get a argument name to indicate that if we want to sorting record by keys or values :(

**Comment by fdncred** [comment]
> Any suggestions?

how about this?

`--key(-k)` for the key
`--value(-v)` for the value
