### ISSUE TITLE
`source` all files from directory

### ISSUE THREAD

**Issue by jgollenz** [nushell/nushell#5682]
### Related problem

I tend to put custom functions into separate files, as they often don't have much in common and (imo) don't belong into the same file. This means, that I would need to `source` every single one of those files, as I cannot loop through the contents of the directory due to `source` needing to complete at compile time*.

*come to think of it, what actually stops the compiler from checking whether those files exist or not?

### Describe the solution you'd like

What I want is a directory where I can just dump `.nu` files that will all be loaded without `source`ing each one individually. I would achieve this via an env variable `NU_AUTOSOURCE_DIRS`

### Describe alternatives you've considered

1. a new command `sourceall <directory>`. I don't think this is the way to go, adding commands just increases complexity
2. a new flag `source --all <directory>` or `source --directory <directory>`. Still adds some complexity, but better than a new command

**Comment by kubouch** [comment]
We're planning to extend the module system so you'll be able to treat a directory as a module and do something like `use some-dir *`.

Sourcing the whole directory can also be done in principle, though, after we've done this for modules, the value of it might not be so high anymore and running *all* scripts in a directory in the current scope might not be very safe as well.

**Comment by jgollenz** [comment]
Indeed, if modules land and work as you describe, there is no need for the system I had in mind. Is there already an open issue for modules that we can link here?

**Comment by ehawman** [comment]
>as I cannot loop through the contents of the directory due to `source` needing to complete at compile time*.

Wait is this why this doesn't work?

``` nu
for $x in (fd \.nu$ ~/.config/nu/functions) {
    source $x
}
``` 

The error is `Error: nu::parser::sourced_file_not_found`
`help: sourced files need to be available before your script is run`

I can confirm that using `echo $x` results in the full filepath so IDK what's going on under the hood.

**Comment by jgollenz** [comment]
Yep, see [here](https://www.nushell.sh/book/thinking_in_nu.html#think-of-nushell-as-a-compiled-language)

Specifically, `$x` is a runtime variable that is not known when `source` is run during compile time.

**Comment by ehawman** [comment]
@jgollenz 
Crap. That's... really frustrating. Thanks for explaining it!

**Comment by jgollenz** [comment]
It is. @kubouch any news on the module system you mentioned?

**Comment by ehawman** [comment]
Ok so I hacked my way around it. Be warned, this is some temporal insanity.

Inside $nu.config-path:

``` nu
rm ~/.config/nu/functions_list.nu
touch ~/.config/nu/functions_list.nu
for $x in (fd \.nu$ ~/.config/nu/functions | split row "\n") {
    echo $"source ($x)\n" | save ~/.config/nu/functions_list.nu --append --raw
}

source ~/.config/nu/functions_list.nu
```

You must

1. Create functions_list.nu yourself initially
2. Recognize that any changes will require an intermediate launch of $nu.config-path before they take effect. That is, if you add something to ~/.config/nu/functions, the next time you launch nu it'll be updating the list (and your changes won't be in effect), only the *next* time you launch will your new function appear (or your old/renamed one will be dropped off)

Just a workaround for the time being.

**Comment by kubouch** [comment]
Yes, we took a different approach with the module system. You can import modules from within modules but treating the whole directory as one module proved to be an unsuccessful experiment. I don't remember where the problem was exactly but we decided not to do it for now.

We're probably going to revisit this at some point when we take a closer look at packages and decide whether we want to have some standard directory structure or support this "import everything" functionality.

**Comment by jgollenz** [comment]
> this is some temporal insanity

haha, I see what you're doing here :grin: nice hack! Fortunately my need for this feature isn't too pressing yet, so I stick with just sourcing the couple of files explicitly :+1: 

> some standard directory structure

this plz!

**Comment by Kixunil** [comment]
Any news on this? I'd like this too. A nice alternative would be just allowing globs: `source ~/.local/share/nushell/lib/*/entry.nu` or even `source /usr/share/nushell/lib/*/entry.nu` - could be used by packagers to provide their own commands that work well with the OS - something I'm interested in doing.

I don't like blindly importing all files from a directory because they could be unrelated - e.g. `README.md` for published stuff.

**Comment by m5x** [comment]
Allowing globs would also be great for sourcing multiple files from `env.nu` and `config.nu` in the style of `conf.d` directories. IMHO that would make managing configuration both manually or by means of a configuration management tool much more comfortable.

**Comment by kubouch** [comment]
You can now import a whole directory as a module, see https://www.nushell.sh/book/modules.html#modules-from-directories, https://github.com/nushell/nushell/pull/9066.

I think this fulfills the requirement of "source all files in a directory" as in Nushell we tend to lean towards more structured module approach than raw sourcing.
