### ISSUE TITLE
Unable to echo env variables in nushell

### ISSUE THREAD

**Issue by wymli** [nushell/nushell#5684]
### Describe the bug

I can't echo $SHELL in nushell, but I can see that it does exist in env.

### How to reproduce

1. download the pre-built binary from github-release
2. add to $path
3. exec nu 

### Expected behavior

show $SHELL

### Screenshots

![image](https://user-images.githubusercontent.com/49816514/170983422-b83ff7d0-745a-4739-8907-af36388278cb.png)

### Configuration

/home/liweiming〉version | transpose key value | to md --pretty                                   05/30/2022 07:26:06 PM| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.63.0                                          |
| branch             |                                                 |
| commit_hash        | 06cf3fa5ad8c8b1d1351c81ccea59a1f8d588dc9        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.61.0 (a028ae4 2022-04-29)               |
| pkg_version        | 0.63.0                                          |
| build_time         | 2022-05-25 01:07:50 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by sholderbach** [comment]
Environment variables are members of the record in the `$env` variable. So in this case `echo $env.SHELL`
