### ISSUE TITLE
Add ability to check if nushell is running with administrator privileges

### ISSUE THREAD

**Issue by Dan-Gamin** [nushell/nushell#5689]
### Related problem

I'm currently working on improving my custom nushell prompt but I realized there is no way to check if nushell is running with administrator privileges.

### Describe the solution you'd like

An an environment variable (in `$env`) that tells you if nushell is running with administrator privileges.

**Comment by kubouch** [comment]
I'm not sure how you'd check whether you have admin privileges. Do you have any idea? Also this would probably be different on Windows / Linux / Mac.
