### ISSUE TITLE
Argument type in autogenerated help changes after adding completion to argument

### ISSUE THREAD

**Issue by Yethal** [nushell/nushell#5690]
### Describe the bug

When we define a function in a module that accepts a parameter of specified type as an argument, import that module and run `function -h` autogenerated help will show the parameter with the type we specified.
However if we add a completion command to that argument then the type in autogenerated help will be reported as <Custom(<type>, some-number):

### How to reproduce

```
def "nu-complete test" [] {
    [word more-word third-word]
}

export def test [
    arg:string
] {
    echo $arg
}

export def test2 [
    arg:string@"nu-complete test"
] {
    echo $arg
}
```

1. Import attached module
2. Run `test -h`
3. Notice the parameter type for arg is `<String>:`
4. Run `test2 -h`
5. Notice the parameter type is `<Custom(String, some-number)>:`

### Expected behavior

I expected the parameter type in help to stay the same

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.63.0                                              |
| branch             | master                                              |
| commit_hash        |                                                     |
| build_os           | linux-x86_64                                        |
| build_target       | x86_64-unknown-linux-gnu                            |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)                 |
| rust_channel       | stable-x86_64-unknown-linux-gnu                     |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)                   |
| pkg_version        | 0.63.0                                              |
| build_time         | 2022-05-25 07:30:15 +02:00                          |
| build_rust_channel | release                                             |
| features           | database, dataframe, default, trash, which, zip     |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by mjclements** [comment]
I can take a look at this one.

**Comment by herlon214** [comment]
@mjclements are you still taking a look?

**Comment by herlon214** [comment]
Looks like it's related to https://github.com/nushell/nushell/pull/5461
