### ISSUE TITLE
Build failed due to multiple definitions

### ISSUE THREAD

**Issue by geoffdudds** [nushell/nushell#5694]
### Describe the bug

Hello,

I am no longer able to build nushell.
The issue started for me with v0.62.0 (or possibly v0.61.0 - I did not try this version). I successfully built v0.60.0.

As shown in the screenshot, I am getting multiple definitions of "__imp_atan". It looks like one is from an msvc library and the other is from the gcc lib my installation of Rust is configured to use.

Is this maybe due to the static linking of OpenSSL combined with the msvc / gcc mismatch?

### How to reproduce

1. Install Rust (Cargo v1.61.0) on Windows 10 with gcc as the compiler ([MinGW-W64 GCC-8.1.0 -> x86_64-posix-seh](https://sourceforge.net/projects/mingw-w64/files/))
2. Run `cargo install nu --features=extra` from a Windows cmd shell

### Expected behavior

I expected cargo to build and install v063.0.

### Screenshots

![image](https://user-images.githubusercontent.com/69219109/171461102-9bca3358-a046-4e89-afbb-09c97a7c1385.png)

### Configuration

C:\WINDOWS\System32
\>  version | transpose key value | to md --pretty
| key                | value                                 |
| ------------------ | ------------------------------------- |
| version            | 0.60.0                                |
| build_os           | windows-x86_64                        |
| rust_version       | rustc 1.59.0 (9d1b2106e 2022-02-23)   |
| rust_channel       | stable-x86_64-pc-windows-gnu          |
| cargo_version      | cargo 1.59.0 (49d8809dc 2022-02-10)   |
| pkg_version        | 0.60.0                                |
| build_time         | 2022-03-31 11:52:39 -07:00            |
| build_rust_channel | release                               |
| features           | dataframe, default, trash, which, zip |
| installed_plugins  |                                       |

**Comment by fdncred** [comment]
I thought this was because we require a more updated version of rust. I don't think it'll build with 1.59 anymore.

**Comment by rgwood** [comment]
I think @geoffdudds is trying to build using Rust v1.61.0.

If this is related to OpenSSL (very possible), try checking out the latest version of Nu from `main` and building that; we no longer build OpenSSL on Windows.

**Comment by fdncred** [comment]
Ok, why does the version command above say 1.59?

**Comment by fdncred** [comment]
You could use the build scripts in the repo. I think they just do cargo build --features=extra.

**Comment by rgwood** [comment]
Thanks for the build log, that helps. Yep, it should be as simple as cloning this repo then running `cargo build` or the build scripts like @fdncred mentioned.

From the build log, it seems like [the `lz4-sys` crate](https://lib.rs/crates/lz4-sys) is the culprit:
```
error: failed to run custom build command for `lz4-sys v1.9.3`
```
`lz4-sys` is a dependency of [this `arrow2` crate](https://crates.io/crates/arrow2) that we use for dataframes.

I was able to find [this issue](https://github.com/10XGenomics/lz4-rs/issues/12) which suggests that updating to a newer version of GCC might fix things; can you give that a try? 

We generally test+develop on `x86_64-pc-windows-msvc`, FWIW; switching to MSVC is another option if upgrading GCC doesn't work.

**Comment by geoffdudds** [comment]
Ok - that worked. 
I thought I was on top of having the latest of gcc but apparently not. I'll use [winlibs](https://www.winlibs.com/) from now on.
For others who come across this, I installed _"GCC 11.3.0 + LLVM/Clang/LLD/LLDB 14.0.3 + MinGW-w64 10.0.0 (UCRT) - release 3"_

Appreciate everyone's help with this - you guys are great.

There is one other build related error I got post-compile. Its kind of a different issue but I thought maybe was small enough to tag on the end here:

![image](https://user-images.githubusercontent.com/69219109/171710895-98ef1915-462b-420e-bdcc-a53a583c22c9.png)

thanks,

**Comment by danjenson** [comment]
![image](https://user-images.githubusercontent.com/4793438/171731825-0b6380ef-8ca6-47cb-9560-cf3d42feb38f.png)
I'm getting an error from OpenSSL on a server I am attempting to install this on

**Comment by rgwood** [comment]
@danjenson I suspect that’s because you’re on an older version of Rust

**Comment by danjenson** [comment]
whoop sorry, my b. Just downloaded cargo but using an old rustc

**Comment by rgwood** [comment]
Closing this for now; just let us know if you still have issues with Nu.

**Comment by geoffdudds** [comment]
@fdncred thanks for the tip on the default config - I am back to normal now!
