### ISSUE TITLE
Add ability to get a free port number in range

### ISSUE THREAD

**Issue by AriHuttunen** [nushell/nushell#5697]
### Related problem

Some applications require a port number as an argument. An example is Jupyter. You can guess a port number, but if it’s in use, the application will fail to start.

### Describe the solution you'd like

There should be an easy way to get a free port number with minimal external tools being used, preferrably only Nu.

The port should in a range of values. A reason for this would be a firewall that let’s in traffic only to some ports.

One way to implement this would be to be able retrieve port statuses, and filter away the ones we don’t want, and pick one.

### Describe alternatives you've considered

There are many solutions to this problem in StackOverflow using small python or shell scripts.

You can also try one, and if it doesn’t work, try another.

**Comment by elferherrera** [comment]
Is there a port scanner in rust core functionality?
