### ISSUE TITLE
www.nushell.sh doesn't load

### ISSUE THREAD

**Issue by jabbalaci** [nushell/nushell#5707]
### Describe the bug

When I visit the website at https://www.nushell.sh/ , it doesn't always load. There's something wrong with its webserver.

### How to reproduce

visit https://www.nushell.sh in your browser

### Expected behavior

the page should load

**Comment by hustcer** [comment]
I have never encountered this issue，anyone else has this issue？

**Comment by fdncred** [comment]
I've seen the website burp a few times over the years an not load but it always corrects itself. I'm not sure there is much we could do about it.

**Comment by hustcer** [comment]
We have just make a totally deploy today, It may caused by some cache or CDN related strategies, Let's wait for a while

**Comment by jabbalaci** [comment]
I still have this problem but I could overcome by installing Tor. With Tor Browser I can reach the website.

**Comment by merelymyself** [comment]
Maybe it’s just blocked on your connection?

**Comment by jabbalaci** [comment]
@merelymyself : It must be a problem on the side of my internet provider.
