### ISSUE TITLE
Light Theme

### ISSUE THREAD

**Issue by jabbalaci** [nushell/nushell#5711]
### Describe the solution you'd like

I'm new to Nushell and I have just a question: is there a theme available for light background? As I can see, the default theme is made for dark background. However, I prefer light backgrounds.

If the answer is yes, how can I set that? Is it enough to add an extra line in the config file?

**Comment by herlon214** [comment]
I think you can change the theme colors in the config file ($nu.config-path)

**Comment by fdncred** [comment]
https://www.nushell.sh/book/coloring_and_theming.html

**Comment by Dan-Gamin** [comment]
If you have more questions about nushell. Feel free to ask in the [discord server](https://discord.gg/bwWgbtfHs8).

**Comment by herlon214** [comment]
@jabbalaci does that answer your question?

**Comment by jabbalaci** [comment]
@herlon214 : yes, partially. I thought there was a default light theme available but it seems I'll have to put one together myself.

When you install VS Code, for instance, you can select a theme. There are dark and light themes available. Nushell should do the same with themes. The developers think that everybody uses dark background, but this is a false assumption.

On discord I got some help, so thank you @Dan-Gamin .

**Comment by jabbalaci** [comment]
A related question: how to change the coloring of the prompt? I mean the path (default: green) and the arrow (light blue). In `env.nu` we can change the text, but I don't see where to change the colors.

**Comment by Dan-Gamin** [comment]
> A related question: how to change the coloring of the prompt? I mean the path (default: green) and the arrow (light blue). In `env.nu` we can change the text, but I don't see where to change the colors.

Use the `ansi` command to change the color for example:
```sh
def create_left_prompt [] {
    let path_segment = ($env.PWD)

    $'(ansi blue)($path_segment)(ansi reset)'
}
```
The above code makes a blue path. For the arrow? no idea. just set the `PROMPT_INDICATOR` variable to `{ ' ' }` and include the arrow inside the prompt itself.

**Comment by jabbalaci** [comment]
Thanks @Dan-Gamin , it works well.
