### ISSUE TITLE
echo -n

### ISSUE THREAD

**Issue by jabbalaci** [nushell/nushell#5724]
### Related problem

`print` has a switch `-n`, which means: don't add the newline character at the end. However, `echo` doesn't have this switch.

### Describe the solution you'd like

To keep consistency, `echo` should also have the switch `-n`.

Examples:
```
$ print -n "hello"; print world
helloworld

$ echo -n "hello"; print world
Error: nu::parser::unknown_flag (link)

  × The `echo` command doesn't have flag `-n`.
   ╭─[entry #30:1:1]
 1 │ echo -n "hello"; print world
   ·       ┬
   ·       ╰── unknown flag
   ╰────
  help: use echo --help for a list of flags
```

In Bash / ZSH, it works:
```
$ echo -n hello; echo world
helloworld
```

**Comment by jabbalaci** [comment]
BTW, what's the difference between `echo` and `print`. To me, it seems they do the same thing.

**Comment by merelymyself** [comment]
"This will print simple values, structured data, and also errors." - #4535

**Comment by fdncred** [comment]
> BTW, what's the difference between echo and print. To me, it seems they do the same thing.

What i wrote on discord, `print` was meant to take the place of `| autoview` in older versions of nushell, which forces information to be printed immediately. Notes from the PR, `This adds a command explicitly meant to consume a value and print it to the screen. This will print simple values, structured data, and also errors.`

I also wanted to simulate `echo -n` which is why i added `print -n`

**Comment by jabbalaci** [comment]
This is `print`, OK, but how is it compared to `echo`? What's the difference? When should I use `echo`, when should I use `print`? To me, they seem to do the same thing, so I don't know which one to use in various situations.

**Comment by WindSoilder** [comment]
The difference between them is subtle, `print` is print value out to stdout immediately(during command execution), and it returns `nothing`, so the printed value **doesn't support** pipeline printed value to other commands

And echo **returns a actual value**, and it's rendered by other components inside `nu`.  So it **supports pipeline echoed value to other commands**, in general, `echo` is more powerful and suited for most cases.
```
print asdf | save 'a.txt'  # this will gives you error, because print just print something and doesn't return values.
echo asdf | save 'a.txt'   # this works fine

# return value difference
print asdf | describe # it will output `asdf`, and describe gives you nothing
echo asdf | describe  # `asdf` is not outputed, and the value is piped to describe command
```

## When to use print?
One scenario: inside hook, especially if you want to print something during hook execution.
```
  hooks: {
    pre_prompt: [{
      print $"=====\nTime elapsed: ($env.CMD_DURATION_MS) ms\n====="
    }]
    ....
  }
```

echo will not work in this case.

Hope that makes you clearer :)

**Comment by fdncred** [comment]
nice explanation @WindSoilder

**Comment by WindSoilder** [comment]
So I think this can be resolved?

**Comment by WindSoilder** [comment]
Maybe this issue can be treated as resolved.

**Comment by hustcer** [comment]
For more detail see: https://github.com/nushell/nushell/pull/5965
