### ISSUE TITLE
Pass through the whole signature to a function

### ISSUE THREAD

**Issue by Velyks** [nushell/nushell#5727]
### Related problem

There are many programs written for other shells that produce a structured output (usually in SSV or CVS) that I'd like to write wrapper functions for in nushell to make them output in a proper data way, for example:
```
def kc [...args] {
   kubectl $args | from ssv
}
```
Currently this isn't possible as any flags you would use in kubectl get interpreted as flags for the kc function and then error as that named argument doesn't exist.

### Describe the solution you'd like

I'd like a way to either expose the entire signature in the function or allow a way to pass arbitrary flags into the function to allow this.
This could be done by: 
- Having a special variable in the function's scope that contains the signature ( `$@` )
- Having a rests equivalent for flags (`[...args, ...-flags]`)
- Treating undefined flags as regular arguments

**Comment by weirdan** [comment]
There's now `def --wrapped` that allows just that:

```console
$ def --wrapped qq [...args] { ^echo "got args: " ...$args }
$ qq --what --ever --you=want
got args:  --what --ever --you=want
```
