### ISSUE TITLE
Warning in windows terminal 

### ISSUE THREAD

**Issue by bash-sanka1p** [nushell/nushell#5728]
### Describe the bug

I have set nu shell as the default terminal in windows terminal as per the process show in the documentation.
but every time i lauch a terminal im getting a warning which i'm guessing is from nushell only.
ther warning is

warning: use `let-env config = ...` instead of `let config = ...`

### How to reproduce

1. set nushell as default in windows terminal
2.  launch a new windows terminal

### Expected behavior

No warnings.

### Screenshots

![image](https://user-images.githubusercontent.com/70506573/172205641-6ddade5f-0e70-4cd5-9c14-e954916d8107.png)

**Comment by hustcer** [comment]
Please use the latest config file, and `let config` has been changed to `let-env config`: https://github.com/nushell/nushell/blob/64efa30f3e7805ea1cca67943a86d28b11378490/docs/sample_config/default_config.nu#L199
