### ISSUE TITLE
Query conflicts with Windows Query

### ISSUE THREAD

**Issue by SarahGreyWolf** [nushell/nushell#5742]
### Describe the bug

The query commands conflict with the windows [Query](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/query) command.
The page sais it only `Applies to: Windows Server 2022, Windows Server 2019, Windows Server 2016, Windows Server 2012 R2, Windows Server 2012` but I do have it on Windows 10 Pro, version 20H2, Kernel Version 19042.

### How to reproduce

1. Using Windows 10 Pro
2. Open nushell
3. Execute `query`

### Expected behavior

Responds with all the nushell query commands.

### Screenshots

![image](https://user-images.githubusercontent.com/727457/172745546-bc1cab6f-3b79-443a-8868-115276170df5.png)

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.63.0                                      |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | windows-x86_64                              |
| build_target       | x86_64-pc-windows-msvc                      |
| rust_version       | rustc 1.63.0-nightly (cd282d7f7 2022-05-18) |
| rust_channel       | nightly-x86_64-pc-windows-msvc              |
| cargo_version      | cargo 1.63.0-nightly (3f052d8ee 2022-05-12) |
| pkg_version        | 0.63.0                                      |
| build_time         | 2022-06-08 23:40:13 +01:00                  |
| build_rust_channel | release                                     |
| features           | default, trash, which, zip                  |
| installed_plugins  |                                             |

**Comment by fdncred** [comment]
if you're running query and getting the external command, that means you haven't compiled/registered the query plugin properly. I can also see this because in your configuration information above `installed_plugins` is empty and query is a plugin.  This is what mine looks like with plugins registered.
```
╭────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────╮
│        key         │                                             value                                             │
├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ version            │ 0.63.1                                                                                        │
│ branch             │ main                                                                                          │
│ commit_hash        │ f5519e2a0958112ce371fcab57b4bdbbc8f929ef                                                      │
│ build_os           │ macos-aarch64                                                                                 │
│ build_target       │ aarch64-apple-darwin                                                                          │
│ rust_version       │ rustc 1.61.0 (fe5b13d68 2022-05-18)                                                           │
│ rust_channel       │ stable-aarch64-apple-darwin                                                                   │
│ cargo_version      │ cargo 1.61.0 (a028ae42f 2022-04-29)                                                           │
│ pkg_version        │ 0.63.1                                                                                        │
│ build_time         │ 2022-05-30 08:36:14 -05:00                                                                    │
│ build_rust_channel │ debug                                                                                         │
│ features           │ database, dataframe, default, trash, which, zip                                               │
│ installed_plugins  │ gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml │
├────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│        key         │                                             value                                             │
```

**Comment by SarahGreyWolf** [comment]
Yeah I've realised that's probably the case now, the Command Reference in the book could probably use a little indicator to say whether it is something that is default or not, I was initially also confused as to why db was hitting windows and saying that it's an unrecognised command, realised it's because I didn't build with `--feature extra`.

**Comment by SarahGreyWolf** [comment]
Yep totally just a case of not realising about plugins, my apologies.
