### ISSUE TITLE
All Windows nu-tests CI failing

### ISSUE THREAD

**Issue by merelymyself** [nushell/nushell#5746]
### Describe the bug

All CI for windows nu tests are failing. The compilation of some crate fails, with the following error:

`  = note: LINK : fatal error LNK1201: error writing to program database ''; check for insufficient disk space, invalid path, or insufficient privilege`

### How to reproduce

Make PR. GitHub Workflows. CI fails.

### Expected behavior

Not fail due to compile error?

**Comment by fdncred** [comment]
my guess is that the move to building windows static is causing this, but I could be wrong. @rgwood, any ideas?

**Comment by rgwood** [comment]
My first guess is that we're running out of disk space because `rust-cache` is acting up. Might have to disable it. But looking at recent workflows, I don't see the failure:

<img width="667" alt="image" src="https://user-images.githubusercontent.com/26268125/172881124-6a79fa8d-26d2-4273-aecc-5b390ba788ca.png">

**Comment by fdncred** [comment]
@rgwood the `handle SIGQUIT` was failed this morning. i re-ran it and it worked.

**Comment by sholderbach** [comment]
I think someone  was mentioning in the discussion on your blog post that they were using some gh caching functionality directly (which would probably mean we would have to write the cache key ourselves). Maybe that could be an alternative to `rust-cache`. https://www.reddit.com/r/rust/comments/ug4utz/tips_for_speeding_up_rust_builds_times_in_ci_we/i6xqxq9/

**Comment by hustcer** [comment]
This issue seems to be fixed ? The Windows CI works fine now

**Comment by rgwood** [comment]
Yes I fixed this by disabling rust-cache for tests. Not ideal but this is solved for now.
