### ISSUE TITLE
Adding multiple columns to a table

### ISSUE THREAD

**Issue by jackadrianglass** [nushell/nushell#5748]
### Related problem

I'm trying to do pipeline where I can get the committers total line contributions. I've come up with the following pipeline thus far
```
git log --pretty=%h»¦«%aN -n 25 | lines | split column "»¦«" commit name | upsert changes {|c| $"($c.commit)^!" | git diff $in --shortstat | str trim | parse --regex '(?P<files>\d+) files? changed(, (?P<i>\d+) insertions?\(\+\))?(, (?P<d>\d+) deletions?\(\-\))?' }
```
The problem is that `upsert` doesn't let me insert multiple new rows so I end up with a column that is a nested table

### Describe the solution you'd like

Just for ease of use, it'd be awesome if upsert could add multiple columns in the form of
`upsert [name1, name2] {|it| }`

**Comment by Yethal** [comment]
You can un-nest the table by running `flatten` or `flatten -a` (if it's deeply nested). Take a look at this example (done without regex due to personal preferences)
```
#!/usr/bin/env nu
git log '--pretty=%h %aN' -n 25
|lines
|split column ' ' commit name
|upsert changes {|c|
    |git diff $c.commit --shortstat
    |str trim
    |split row ','
    |str trim
    |split column ' '
    |get column1
    |rotate --ccw changes insertions deletions
}
|flatten -a
```

**Comment by jackadrianglass** [comment]
Awesome! Thanks I didn't know about that command. I will continue to experiment with it.

P.S. I'm using nushell as a daily driver at work and I'm having a lovely time with it! Thanks for all the hard work!
