### ISSUE TITLE
alias sudo bug

### ISSUE THREAD

**Issue by Arian-p1** [nushell/nushell#5755]
### Describe the bug

when i use add an alias with sudo i should enter my password when i open my terminal 

### How to reproduce

aliases like 
sudo shutdown now

### Expected behavior

i should enter my password when i open my terminal and its bug its like its running or checking the aliases 
and another funny think it say my password is wrong 

### Screenshots

i open my terminal and it want password 
its checking aliases 
i removed sudo s  
and 1 of my aliases was wrong
see the error 

```
Options error: In [CMD-LINE]:1: Error opening configuration file: nl-free-01.protonvpn.com.udp.ovpn
Use --help for more information.
```
see its checking

**Comment by hegde-atri** [comment]
bump

**Comment by hegde-atri** [comment]
Basically we can't have sudo in our aliases' definition without it prompting for password when we open our shell

**Comment by amtoine** [comment]
i cannot reproduce this behaviour with the very latest revision of Nushell :thinking: 

i've just built and added
```nushell
alias foo = sudo echo "foo"
```
to my `config.nu` and
- i'm not prompted for any password when Nushell starts
- running `foo` prompts me for my password and then prints `foo`

**Comment by hegde-atri** [comment]
Huh, this was a very bad comment on my part, my issue was a bit more complex.
I have multiple sudo aliases which work just fine,
They broke for me when chaining commands using  ";". I had to replace it with "and".

Here is my working snippet now:
```sh
alias syncTime = sudo ntpd -qg and sudo hwclock --systohc
```

My issue was resolved so @Arian-p1 is it still not working for you?

**Comment by amtoine** [comment]
@hegde-atri

not sure what this `and` is in Nushell :thinking: 
i would rather do
```nushell
alias syncTime = do {
    sudo ntpd -qg
    sudo hwclock --systohc
}
```

**Comment by Arian-p1** [comment]
> Huh, this was a very bad comment on my part, my issue was a bit more complex. I have multiple sudo aliases which work just fine, They broke for me when chaining commands using ";". I had to replace it with "and".
> 
> Here is my working snippet now:
> 
> ```shell
> alias syncTime = sudo ntpd -qg and sudo hwclock --systohc
> ```
> 
> My issue was resolved so @Arian-p1 is it still not working for you?

yeah its ok now

**Comment by Arian-p1** [comment]
its working fine after updates

**Comment by hegde-atri** [comment]
> @hegde-atri
> 
> not sure what this `and` is in Nushell 🤔 i would rather do
> 
> ```nushell
> alias syncTime = do {
>     sudo ntpd -qg
>     sudo hwclock --systohc
> }
> ```

I use `and` since I only want to run `sudo hwclock --systohc` if the first command succeeds. The first command corrects my "software clock" and the seconds one sync my hardware clock with my software clock.

**Comment by amtoine** [comment]
@hegde-atri 
to the best of my knowledge, `and` is not a valid Nushell syntax in that case and will probably lead to unexpected results, because `and` will be passed to `sudo` as any other arguments...
look at the output of `echo "foo" and echo "bar"`, it's not `foo` and then `bar`, but rather the list `[foo, and, echo, bar]` :open_mouth:
worse, trying with a command that fails for real, you don't get the correct behaviour i think :thinking:
```bash
^false and echo "should not run"
# no output as expected
^true and echo "should run"
# still no output...
```

here, i still think the correct way to do this is to use a `do` block :yum:
e.g.
```nushell
alias foo = do {
    not-a-command
    echo "should not run"
}
```
will not run the `echo` command because the previous one gives an error
```nushell
> foo
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #7:1:1]
 1 │ alias foo = do {
 2 │     not-a-command
   ·     ──────┬──────
   ·           ╰── executable was not found
 3 │     echo "should not run"
   ╰────
  help: No such file or directory (os error 2)
```

even better with
```nushell
> alias foo = do {^false; echo "should not run"}; foo
# no output
```
and
```nushell
> alias bar = do {^true; echo "should run"}; bar
should run
```
:yum:

**Comment by hegde-atri** [comment]
@amtoine 

Thanks for the feedback. I am very much a beginner in terms of using nushell. Just ported over my zsh config as zsh was too slow for me haha.

I see. I suppose I am wrong, and is not a great command, and even I found using `;` works a lot better.

I did not know that you could make a block using `do`. I am going to update my config to have that now instead.

On another note. If I was writing a one-liner that would execute the seconds command only if the first command was successful, how would I do it.
Ex: `mkdir parent && touch parent/foo`

**Comment by amtoine** [comment]
> Thanks for the feedback. I am very much a beginner in terms of using nushell. Just ported over my zsh config as zsh was too slow for me haha.
> 
ehe no worries, this is why we are here to help as best as we can :pray: 

> I see. I suppose I am wrong, and is not a great command, and even I found using `;` works a lot better.
>
`and` is a boolean command, used to compute complex boolean expressions, such as
```nushell
(which foo | is-empty) and ($a ** 2 + $b ** 2 == $c ** 2)
```
:yum: 
 
> I did not know that you could make a block using `do`. I am going to update my config to have that now instead.
> 
when you have an alias that starts getting quite long / that needs multiple lines and conditional execution like that, it's a good indication that you might want to 
- use the `do` command
- `def`ine a custom command rather than an `alias`
e.g. i have this [`lsg` command](https://github.com/goatfiles/dotfiles/blob/e58577ba922466fa6cab28597e788f4b7e193840/.config/nushell/config.nu#L204-L209) in my config :wink: 

> On another note. If I was writing a one-liner that would execute the seconds command only if the first command was successful, how would I do it. Ex: `mkdir parent && touch parent/foo`
>
simply
```nushell
mkdir parent; touch parent/foo
```
or
```nushell
mkdir parent
touch parent/foo
```

**Comment by hegde-atri** [comment]
Thanks @amtoine. I've just been using `and` wrong thinking it did the same as `;`.

**Comment by amtoine** [comment]
@hegde-atri 
yeah that one's a bit tricky :open_mouth: 
happy to help :blush:
