### ISSUE TITLE
mod exists, but div is missing

### ISSUE THREAD

**Issue by jabbalaci** [nushell/nushell#5758]
### Related problem

`/` is math division, i.e. `5 / 2` is 2.5 . However, what if we want integer division? `mod` exists, but `div` is missing:
```
$ 5 mod 2
1
$ 5 div 2
error
$ 5 // 2    # like in Python
error
```

It can be done, but it's long IMO:
```
$ 5 / 2 | math floor
2
```

### Describe the solution you'd like

If we have `mod`, there should be `div` too, which would perform integer division. Or `//`, just like in Python.

**Comment by onthebridgetonowhere** [comment]
That seems fair. We'd welcome a PR, if you wanna give it a try!
