### ISSUE TITLE
Change the current working directory within a function

### ISSUE THREAD

**Issue by madprops** [nushell/nushell#5762]
### Related problem

This isn't working:

```
export def-env z [arg] {
  let zpath = (python (script_path) jump $arg)
  
  if $zpath != "" {
    cd /home/yo/Downloads

    if $env.LAST_EXIT_CODE == 0 {
      echo "234"
    }
  }
}
```

The purpose of the function is to go to a different location. 

### Describe the solution you'd like

I understand it makes sense to only do it internally for script purposes, but I'm wondering if it's possible to have some way of changing the location, by that I mean the interface prompt & location.

**Comment by madprops** [comment]
Apparently this DOES work

```
export def-env z [arg] {
  cd /home/yo/Downloads
}
```

**Comment by WindSoilder** [comment]
Relative: #5024

**Comment by WindSoilder** [comment]
Hmm, it seems strange to, here is another issue mentioned about this #5024

**Comment by fdncred** [comment]
correct, you cannot cd within an `if` statement. In order to use `if` you'd have to do something like this:
```
def-env z [arg] {
let zp = (if condition {
blah
} else {
bleck
})
cd $zp
}
```

You may want to look at how zoxide works. It cd's great.

**Comment by kubouch** [comment]
Currently, all blocks are scoped, so if you `cd` inside an `if` branch, it will change the directory only inside the branch.
```
if $zpath != "" {
    cd foo/bar
    # PWD is foo/bar
}
# PWD is whatever was before the "if"
```
