### ISSUE TITLE
Nuon does not preserve int and float datatypes correctly

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#5767]
### Describe the bug

When converting round numbers to nuon and back, they will be casted as integers.

### How to reproduce

```
> 1.0 | describe
float

> 1.0 | to nuon | from nuon | describe
int
```

### Expected behavior

Not sure. Maybe floating point numbers should always have `.0`?

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.63.1                                          |
| branch             | main                                            |
| commit_hash        | caafd26deb59b49b93d8a6f4b6c558fc38e83684        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.61.0 (a028ae4 2022-04-29)               |
| pkg_version        | 0.63.1                                          |
| build_time         | 2022-06-13 14:40:43 +03:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | gstat                                           |

### Additional context

This is important when working with dataframes since dataframes panic if you do operation across multiple data types. You can easily end up with a column that has both integer and a float.

**Comment by jntrnr** [comment]
yeah seems it's in `to nuon`:

```
> 1.0 | to nuon
1
```
