### ISSUE TITLE
External completion could cause a significant slowness

### ISSUE THREAD

**Issue by Kangaxx-0** [nushell/nushell#5772]
### Describe the bug

I am currently on WSL2 from Windows 11. In Nushell, if I hit`<tab>`, it takes Nu roughly 8 secs to display the suggestion command, this slowness occurred because Nu might have a chance to look into system `PATH` and scan everything, including Windows system paths.

### How to reproduce

1. In Windows + WSL2, type `nu`(or ignore this if nu is default shell)
2. Hit `TAB`
3. Wait the suggestions shown

### Expected behavior

Nu should give user the opportunity to either enable or disable external completion, if it will introduce slowness. 

### Screenshots

![slow](https://user-images.githubusercontent.com/85712372/173455982-051e83b1-d87a-4938-a293-3ca00c405c10.gif)

After my local fix

![fix](https://user-images.githubusercontent.com/85712372/173456504-81df260a-961d-435a-a5b7-29662f5150b1.gif)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.63.1                                          |
| branch             |                                                 |
| commit_hash        | 0c05dc583a81361d0443d0f4af243e532965c5b7        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.61.0 (a028ae4 2022-04-29)               |
| pkg_version        | 0.63.1                                          |
| build_time         | 2022-06-08 14:49:35 -07:00                      |
| build_rust_channel | debug                                           |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
This is a known WSL issue. It's been there a long time. I wouldn't call this a nushell issue. https://github.com/nushell/nushell/issues/4914

You can fix it with the known WSL work-around.
```
# in /etc/wsl.conf
[interop]
appendWindowsPath=false
# then run: `wsl --shutdown` and restart WSL
```
