### ISSUE TITLE
Weird bug of "Types mismatched for `||` operation"

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#5776]
### Describe the bug

Weird bug of "Types mismatched for `||` operation"

### How to reproduce

```shell
# foo.nu
def 'check' [
  type?: string,
] {
  let cond1 = ($type == $nothing)
  let cond2 = (($type in ['added' 'deleted' 'commits']) == false)
  print ($cond1 | describe) # bool
  print ($cond2 | describe) # bool
  let r = if ($cond1 || $cond2) { 'A' } else { 'B' }
  $r
}

check added
```
Run `nu foo.nu` will get:
```
Error: nu::parser::unsupported_operation (link)

  × Types mismatched for operation.
   ╭─[tmp/foo.nu:7:1]
 7 │   print ($cond2 | describe) # bool
 8 │   let r = if ($cond1 || $cond2) { 'A' } else { 'B' }
   ·               ───┬── ─┬ ───┬──
   ·                  │    │    ╰── string
   ·                  │    ╰── doesn't support these values.
   ·                  ╰── string
 9 │   $r
   ╰────
  help: Change string or string to be the right types and try again.

```

### Expected behavior

Should run without any error and output `B`

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.63.1                                              |
| branch             | feature/summary                                     |
| commit_hash        | 4fd4136d500c55d19c29ad5e89903afc58d43a97            |
| build_os           | macos-x86_64                                        |
| build_target       | x86_64-apple-darwin                                 |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)                 |
| rust_channel       | stable-x86_64-apple-darwin                          |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)                 |
| pkg_version        | 0.63.1                                              |
| build_time         | 2022-06-14 13:43:17 +08:00                          |
| build_rust_channel | release                                             |
| features           | database, dataframe, default, trash, which, zip     |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

### Additional context

If we remove the parenthesis around `cond1` and `cond2` will make it work as expected

```shell
def 'check' [
  type?: string,
] {
  let cond1 = $type == $nothing
  let cond2 = ($type in ['added' 'deleted' 'commits']) == false
  let r = if ($cond1 || $cond2) { 'A' } else { 'B' }
  $r
}

check added
```

Output 
```
B
```

**Comment by hustcer** [comment]
A more simpler case:
```shell
let a = 'b'
# This line works
if $a == 'b' || $a == 'c' { echo 'b or c' } else { echo 'other' }
# This line failed
if ($a == 'b') || ($a == 'c') { echo 'b or c' } else { echo 'other' }
```

**Comment by kubouch** [comment]
I think it's a regression, it used to work before. I ran into this error yesterday as well running code that used to work a few weeks ago.
