### ISSUE TITLE
Broken completion with alias

### ISSUE THREAD

**Issue by alexjp** [nushell/nushell#5780]
### Describe the bug

Hi, first of all, thank you for the awesome shell and shell programming language!

some days ago, trying to use nushell git version, doesn't allow me to autocomplete ?some? alias. (I haven't done an extensive check to say that its all alias)

Example, I have `cat` aliased to: `bat --style header --style rules --style snip --style changes --style header --pager=never`

In previous nushell (the stable release) I can do for example `cat /tm` and tab my way to autocompletion.

In git version, it just says right away "NO RECORDS FOUND".

Also, if I do `/usr/bin/cat /tm` I can again autocomplete.

From my quick findings, functions seem to be working (autocompleting), but not alias.

Also, don't know if it can be in the same bug or not, but seems related:

Doing an alias of an alias seems to crash nushell:

```
│ 0 │ ll  │ Nushell alias: _ls -l --sort=time │ false    │
│ 0 │ _ls │ Nushell alias: exa --color=always --group-directories-first --icons │ false    │
```

So .... `ll` is an alias for `_ls` which is an alias for the command `exa`.

Running `ll` space, then "/" and then tab, results in:
```
 | ll thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', crates/nu-cli/src/completions/completer.rs:76:25
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: <nu_cli::completions::completer::NuCompleter as reedline::completion::base::Completer>::complete
   4: <reedline::menu::columnar_menu::ColumnarMenu as reedline::menu::Menu>::update_values
   5: reedline::engine::Reedline::handle_editor_event
   6: reedline::engine::Reedline::read_line
   7: nu_cli::repl::evaluate_repl
   8: nu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

If you need full backtrace, or if the issue is badly done, just give me a notice and I will try to give more info!

### How to reproduce

1. create an alias
2. use alias and try to autocomplete with tab

### Expected behavior

I expected nu to autocomplete files or folders, but just says right away "NO RECORDS FOUND"

It does work properly in the stable version (0.63), only git version is affected.

**Comment by sholderbach** [comment]
Might this be resolved by https://github.com/nushell/nushell/pull/5749 ?

**Comment by alexjp** [comment]
thanks!

actually just tested: commit d5b99ae316dda0c89456675bd41ee7678b87f813 ( which is the exact commit before the merge of that pull request ) -> works fine! ( both the `cat` alias example and the `ll` alias of alias example.

then I tested commit b6959197bf176d5f38d0dadea0872a4666117507, which is the commit after that previous one and of the merge -> its does not work anymore, and the issues outlined above happen.

So if anything, that commit is what "broke it". ( just saying, no disrespect for the work done )

**Comment by Kangaxx-0** [comment]
I can take a look at this. One question - what is `bat`? Can you point me a link?

**Comment by hustcer** [comment]
https://github.com/sharkdp/bat

**Comment by Kangaxx-0** [comment]
Alias of an alias works for me, same aliases here

![image](https://user-images.githubusercontent.com/85712372/173761828-73f60850-5781-4249-abc8-94809ef1b712.png)

**Comment by alexjp** [comment]
@Kangaxx-0 thanks for testing.

`ll` command works here too. but can you try `ll /t` and then pressing tab (trying to autocomplete with tab `ll`) ?

btw... noticed that nushell 0.64 got released. tested based on it, with clean ~/.config/nushell folder ( moved my configurations and let nushell create the default ones )

**Comment by alexjp** [comment]
is this backtrack helpfull? I installed nushell with `--debug`

![nushell](https://user-images.githubusercontent.com/85806/173805149-602c2163-59dc-4ef6-9c46-7c0559607cc5.jpg)

**Comment by alexjp** [comment]
> I can reproduce it with `/t` and tab, what is `/t` trying to do here, or what would be the expected output :)

/tmp :) its just a random folder/file.

also happens doing `ll` -> tab -> ( while on "NO RECORDS FOUND") press any key.

the important is not to focus on `ll` ... but on tab completion of alias, and alias of alias ( not completing the alias word ... but completing arguments for the alias or alias of alias )

**Comment by herlon214** [comment]
good catch @alexjp!
@Kangaxx-0 could you please add a new test for this command so we can keep track of it? Once the current tests couldn't catch this case.

**Comment by Kangaxx-0** [comment]
> good catch @alexjp! @Kangaxx-0 could you please add a new test for this command so we can keep track of it? Once the current tests couldn't catch this case.

Will do

**Comment by Kangaxx-0** [comment]
I've figured out a fix to the crash
![5780](https://user-images.githubusercontent.com/85712372/173941406-a64e0ab4-8fcb-4d81-9abb-beb83f29f8d8.gif)

However, as you could tell, the auto-completion is still not working.@alexjp could you confirm https://github.com/nushell/nushell/commit/d5b99ae316dda0c89456675bd41ee7678b87f813 would work before?

**Comment by alexjp** [comment]
> However, as you could tell, the auto-completion is still not working.@alexjp could you confirm [d5b99ae](https://github.com/nushell/nushell/commit/d5b99ae316dda0c89456675bd41ee7678b87f813) would work before?

yes.... in commit d5b99ae316dda0c89456675bd41ee7678b87f813 , its working.

Thanks for fixing the crash!

**Comment by Kangaxx-0** [comment]
> > However, as you could tell, the auto-completion is still not working.@alexjp could you confirm [d5b99ae](https://github.com/nushell/nushell/commit/d5b99ae316dda0c89456675bd41ee7678b87f813) would work before?
> 
> yes.... in commit [d5b99ae](https://github.com/nushell/nushell/commit/d5b99ae316dda0c89456675bd41ee7678b87f813) , its working.
> 
> Thanks for fixing the crash!

Thanks for the confirmation! It is odd, because my fix(5749) is the one before [d5b99ae](https://github.com/nushell/nushell/commit/d5b99ae316dda0c89456675bd41ee7678b87f813)... Let me do some checks later

**Comment by alexjp** [comment]
> Thanks for the confirmation! It is odd, because my fix(5749) is the one before [d5b99ae](https://github.com/nushell/nushell/commit/d5b99ae316dda0c89456675bd41ee7678b87f813)... Let me do some checks later

Strange, isn't fix #5749 after d5b99ae ?

**Comment by Kangaxx-0** [comment]
It is the opposite :) Its ok, i can check out a few more commit hash to find out which the correct one is

<img width="782" alt="image" src="https://user-images.githubusercontent.com/85712372/173953082-329ba7ef-b8b4-4552-a711-969f90f76e8d.png">

<img width="844" alt="image" src="https://user-images.githubusercontent.com/85712372/173953534-86ef000c-a8ab-4cb9-9358-b027e286226e.png">

**Comment by alexjp** [comment]
oh my, so weird :)

well, I was looking at the commit history in main!

![imagem](https://user-images.githubusercontent.com/85806/173954633-2e36463f-1b35-4823-966c-a5bcff6a488c.png)

**Comment by Kangaxx-0** [comment]
I downloaded  release 0.63 , and the completion is not working too. E.g: `ls <tab>` will not give you DIRs, you have to type one character like `ls D<tab>` instead

@herlon214 Do you have more context on this?

**Comment by herlon214** [comment]
@Kangaxx-0 I think the `./` was introduced back 🤔
Doing `ls <tab>` doesn't work on latest but `ls ./<tab>` works.

**Comment by Dialga** [comment]
I just ran into the same issue, I aliased rm to rm -iv to interactively and verbosely remove files, I get the same panic.
```
/tmp: rm fthread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', crates/nu-cli/src/completions/completer.rs:76:25
```
Version 0.64.0

**Comment by Kangaxx-0** [comment]
> I just ran into the same issue, I aliased rm to rm -iv to interactively and verbosely remove files, I get the same panic.
> 
> ```
> /tmp: rm fthread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', crates/nu-cli/src/completions/completer.rs:76:25
> ```
> 
> Version 0.64.0

My apology, this panic was introduced one of my previous commit, seemed like I did not have comprehensive coverage. 

I have fixed this locally (Check out GIF below), right now, running one test case failure and I will test as many as scenarios  :)
![5780-rm](https://user-images.githubusercontent.com/85712372/174118328-3d4c7cc7-9ce8-4e6d-a7fd-b25d4b75a658.gif)

**Comment by alexjp** [comment]
@Kangaxx-0

I just tested that pull request/branch ... and ... quick testing, but seems good! `ll` works and `cat` works ( alias and alias of alias ) !

Thanks very much !!! ( i will keep testing, if anything appears, i will post here )

**Comment by Dialga** [comment]
Is this issue now wholly solved?

**Comment by alexjp** [comment]
> Is this issue now wholly solved?

I think so... I haven't done "more complicated aliases" tests, but the ones I opened the issue with are working properly
