### ISSUE TITLE
Interactive commands with fzf, skim, etc.

### ISSUE THREAD

**Issue by zim0369** [nushell/nushell#5785]
### Describe the bug

After a lot of efforts I have failed to configure the keybindings for fzf that would give me results similar to `ctrl+t` and `ctrl+r` in something like "fish" with the "fzf" plugin.

There is a built-in menu in "history menu" in nushell which I can trigger with `ctrl+r` but fzf and skim are much better than that.

The behavior(or binding) I expect is:
1. type `cd` in the command prompt
2. press `ctrl+t` 
3. fzf menu with directory search appears
4. rough type to select the desired directory
5. press "Enter"
6. Now the command prompt looks like: `cd desired/directory`
7. You still have the command prompt to yourself to make any edits
8. Hit "Enter" whenever you wish.

I expect a similar thing to happen with `ctrl+r` but just for command history.
I haven't been able to figure out a binding yet.

### How to reproduce

I'll leave this empty as I believe the *Description* is enough.

### Expected behavior

Interactive commands should work without running the command without users will.

### Configuration

```md
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.63.1                                          |
| branch             |                                                 |
| commit_hash        | 6c07bc10e2cf3445e098089d184b86463c0a330a        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.61.0 (Arch Linux rust 1:1.61.0-1)       |
| cargo_version      | cargo 1.61.0                                    |
| pkg_version        | 0.63.1                                          |
| build_time         | 2022-05-29 02:16:59 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |
```

**Comment by zim0369** [comment]
@fdncred That was very helpful. One last thing I need to configure is a menu similar to `fzf_history_menu_fzf_ui` but for directories:
```nu
    {
      name: fzf_dir_menu_fzf_ui
      only_buffer_difference: false
      marker: "# "
      type: {
          layout: columnar
          columns: 4
          col_width: 20
          col_padding: 2
      }
      style: {
          text: green
          selected_text: green_reverse
          description_text: yellow
      }
      source: { |buffer, position|
          open -r fzf  #What goes here?
      }
    }
```

**Comment by fdncred** [comment]
i'm not sure. i'm no fzf expert.

**Comment by zim0369** [comment]
@fdncred I have figured it out a little but can you help me with the rest of the part other that `fzf`?
```
    {
      name: fzf_dir_menu_fzf_ui
      only_buffer_difference: false
      marker: "# "
      type: {
          layout: columnar
          columns: 4
          col_width: 20
          col_padding: 2
      }
      style: {
          text: green
          selected_text: green_reverse
          description_text: yellow
      }
      source: { |buffer, position|
          fzf +s --tac | str trim
          | where $it =~ $buffer
          | each { |v| {value: ($v | str trim) } }
      }
    }
```
This works but the directory I select doesn't get inserted into the command line.

**Comment by fdncred** [comment]
I have 2 points of advice.
1. Look at the menus that allow you to put things on the command line (i've pasted one below)
2. Look at the documentation https://www.nushell.sh/book/line_editor.html

@elferherrera do you have any tips on this?


this one allows me to put things on the command line with other commands like `cd <ctrl+y>` and it pastes it appropriately.

menu
```
      {
        name: vars_menu
        only_buffer_difference: true
        marker: "V "
        type: {
            layout: list
            page_size: 10
        }
        style: {
            text: green
            selected_text: green_reverse
            description_text: yellow
        }
        source: { |buffer, position|
            $nu.scope.vars
            | where name =~ $buffer
            | sort-by name
            | each { |it| {value: $it.name description: $it.type} }
        }
      }
```
keybinding
```
    {
        name: vars_menu
        modifier: control
        keycode: char_y
        mode: [emacs, vi_normal, vi_insert]
        event: { send: menu name: vars_menu }
    }
```

**Comment by zim0369** [comment]
@fdncred I think I really we need `$nu.directory-path` or something similar. I'm not sure what kind of variables are these but I haven't been able to configure the binding I wished for.

This is the best I have been able to come up with:
```
      {
        name: fzf_dir_menu_nu_ui
        only_buffer_difference: true
        marker: "# "
        type: {
            layout: list
            page_size: 10
        }
        style: {
            text: green
            selected_text: green_reverse
            description_text: yellow
        }
      source: { |buffer, position|
          fd -t d | fzf +s --tac | str trim
          | where $it =~ $buffer
          | each { |v| {value: ($v | str trim) } }
      }
      }
```
But the problem is that I the `fzf` prompt comes up twice. I don't want to sound arrogant but I might not only need this to change directories but and might want to make a few bindings later for which I really need the text I wrote, intact and don't want the command to be registered. Want to keep the prompt to myself to make any edits.

The above binding is able to do just that but the `fzf` prompt comes up twice and `nu`'s prompt comes up once. That's the only thing I need to fix now.

BTW, I'm sorry, I've been annoying you for a binding for too long but I'm recreating my fish's robust setup in nu rn.

**Comment by fdncred** [comment]
`$env.PWD` may be the `$nu.directory-path` you're looking for?

**Comment by fdncred** [comment]
it's accessible for me. I just added this and it seems to work when i hit F3
```
     {
        name: test_fkeys
        modifier: none
        keycode: f3
        mode: emacs
        event: [
            {edit: clear}
            {edit: insertstring value: $"($env.PWD)"}
        ]
     }
```

**Comment by elferherrera** [comment]
To keep what you wrote the trick is to change `only_buffer_difference` to true. The search will start as soon as you start typing

**Comment by elferherrera** [comment]
Also, fzf has the flag `-f` that you can use to populate the menu without calling for prompt

**Comment by zim0369** [comment]
@fdncred & @elferherrera 
I am probably supposed to use `$env.PWD` to populate my menu but when I do I get an error:
```nu
      {
        name: fzf_dir_menu_nu_ui
        only_buffer_difference: true
        marker: "# "
        type: {
            layout: list
            page_size: 10
        }
        style: {
            text: green
            selected_text: green_reverse
            description_text: yellow
        }
        source: { |buffer, position|
            $"($env.PWD)"
            # $"(ls $env.PWD)" didn't work as well
            | where name =~ $buffer
            | sort-by name
            | each { |it| {value: $it.name description: $it.type} }
        }
      }
```
For the above example I took a a look at [User Defined Menu](https://www.nushell.sh/book/line_editor.html#user-defined-menus) section. In which they use the `$nu.scope.vars` variable to populate the menu so I thought I need a variable like `$nu.directory-path` to populate the menu which you said might be `$env.PWD` but I haven't been able to figure it out yet.

I think I'm too bad at stating the problem so the best possible question I could ask is: "Can you try out [this menu I made](https://github.com/nushell/nushell/issues/5785#issuecomment-1156780325)?"

That menu is pretty close to what I want, just that the prompt appears twice and menu appears once. I just want either the prompt or the menu to appear only once.

**Comment by fdncred** [comment]
how about this?
```
        source: { |buffer, position|
            ls $'($env.PWD)' | where type == dir
            | sort-by name | get name | to text
            | fzf -f $buffer
            | each { |v| { value: ($v | str trim) }}
        }

```

**Comment by zim0369** [comment]
@fdncred not really. It is indeed fuzzy matching now but it isn't recursing through the directories. I want the menu to show results like running just `fzf`.

**Comment by fdncred** [comment]
i'm guessing it's because it takes a beat for `fd -t d` to return something. this is really @elferherrera's area of expertise though.

**Comment by zim0369** [comment]
@elferherrera I need help with one more menu:
```nu
    {
      name: fzf_files_menu_fzf_ui
      only_buffer_difference: false
      marker: "# "
      type: {
          layout: columnar
          columns: 4
          col_width: 20
          col_padding: 2
      }
      style: {
          text: green
          selected_text: green_reverse
          description_text: yellow
      }
      source: { |buffer, position|
          fzf --no-sort --tac | str trim
          | where $it =~ $buffer
          | each { |v| {value: ($v | str trim)
          } }
      }
    }
```
I want the above menu to work fine if I already have some text in the prompt like:
`cat`, `vim`, etc.

**Comment by fdncred** [comment]
> I want the above menu to work fine if I already have some text in the prompt like:

I thought you were supposed to do `only_buffer_difference: true`

**Comment by elferherrera** [comment]
You need `only_buffer_difference` to be true

**Comment by zim0369** [comment]
> You need `only_buffer_difference` to be true

But that doesn't work. I get `NO RECORDS` error as mentioned in one of the previous comments.

**Comment by elferherrera** [comment]
This works for me
```
let fzf_menu =  {
    name: fzf_menu
    only_buffer_difference: true
    marker: "# "
    type: {
        layout: columnar
        columns: 1
        col_width: 20
        col_padding: 2
    }
    style: {
        text: green
        selected_text: green_reverse
        description_text: yellow
    }
    source: { |buffer, position|
        fzf --no-sort -f $buffer
        | lines
        | first 100
        | each { |v| {value: ($v | str trim) } }
    }
}
```

**Comment by zim0369** [comment]
@elferherrera It gets hung up

**Comment by elferherrera** [comment]
yeap, it will hung because there is too much data passed to the menu

**Comment by elferherrera** [comment]
Let's think a bit about your menu. You have this as source
```
source: { |buffer, position|
          fzf --no-sort --tac | str trim
          | where $it =~ $buffer
          | each { |v| {value: ($v | str trim) } }
      }
```
you are first asking for fzf to first run using its interface but later you have a `where` that will filter the result from fzf. Since `$buffer` is an empty string when you first call the menu (because `only_buffer_difference` is true) nothing will pass that pipe and therefore return a `NO RECORDS` result

Since you want to retain the fzf interface and you want to see result immediately you need to use the $position so the menu knows where to replace your result in the buffer

I think this menu does what you want
```
let fzf_menu =  {
    name: fzf_menu
    only_buffer_difference: false
    marker: "# "
    type: {
        layout: columnar
        columns: 1
        col_width: 20
        col_padding: 2
    }
    style: {
        text: green
        selected_text: green_reverse
        description_text: yellow
    }
    source: { |buffer, position|
        let input = (fzf --no-sort --tac  | lines)
        let start = ($buffer | str index-of ' ') + 1
                
        $input
        | each { |v| 
            {
                value: ($v | str trim) 
                span: { start: $start end: $position }
            } 
        }
    }
}
```

For more tricks like this one have a look at nushell's book

**Comment by fdncred** [comment]
The new `commandline` command really helps out here. This command works with `fzf` and skim's `sk` (if you replace the command below with the proper external). It may work with broot too, but i have not tried.
```
    {
      name: fuzzy_history
      modifier: CONTROL
      keycode: char_r
      mode: emacs
      event: {
        send: executehostcommand
        cmd: "commandline (history | each { |it| $it.command } | uniq | reverse | str collect (char nl) | fzf --layout=reverse --height=40% -q (commandline) | decode utf-8 | str trim)"
      }
    }
```

**Comment by nnmm** [comment]
@fdncred `commandline` appears to put the `fzf` result onto a new line, as if pressing Enter after running `fzf`. Is there a way to insert it into the current line?

**Comment by fdncred** [comment]
@nnmm have you tried the latest release 0.91.0?

**Comment by nnmm** [comment]
@fdncred I was using 0.90.1, but I downloaded 0.91 (released 19 hours ago) and it works now! Thanks!

**Comment by rwmpelstilzchen** [comment]
@fdncred Thank you for this! ^_^

---

>    mode: emacs

Is there a reason not to add the vi modes?

    mode: [emacs, vi_normal, vi_insert]

---

>    cmd: "commandline edit --replace (fzf --layout=reverse)"

IMHO `--insert` is more useful. IIANM this is how it works on zsh+fzf.

    cmd: "commandline edit --insert (fzf --layout=reverse)"

**Comment by iNecas** [comment]
For anyone coming here when searching for hints on integrating fzf for history in nushell (as I did), I would recommend some changes to the example provided in https://github.com/nushell/nushell/issues/5785#issuecomment-1243733398

```
commandline edit (history | get command | reverse | uniq | to text | fzf --scheme history --layout=reverse --height=40% -q (commandline) | decode utf-8 | str trim)
```

The changes include:

- swap `uniq | reverse` with `reverse | uniq` to prefer most recently used commands (when used repeatedly)
- use `--scheme history` in fzf that also prefers more recent commands + has more suitable search weights

**Comment by fdncred** [comment]
Thanks @iNecas. This is the one I'm currently using. Tweaked similar to yours from the Discord community.
```nushell
  {
    name: fuzzy_history_fzf
    modifier: control
    keycode: char_r
    mode: [emacs , vi_normal, vi_insert]
    event: {
      send: executehostcommand
      cmd: "commandline edit --replace (
        history
          | where exit_status == 0
          | get command
          | reverse
          | uniq
          | str join (char -i 0)
          | fzf --scheme=history --read0 --tiebreak=chunk --layout=reverse --preview='echo {..}' --preview-window='bottom:3:wrap' --bind alt-up:preview-up,alt-down:preview-down --height=70% -q (commandline) --preview='echo -n {} | nu --stdin -c \'nu-highlight\''
          | decode utf-8
          | str trim
      )"
    }
  }
```
![image](https://github.com/user-attachments/assets/88a7b21f-890b-4cb8-9321-a1c941ffaeaa)

**Comment by scubacabra** [comment]
```nu
history  | where exit_status == 0
```

throws an error as `exit_status` is not a column in the table returned

```nu
history | where exit_status  == 0
Error: nu::shell::column_not_found

  × Cannot find column 'exit_status'
   ╭─[entry #96:1:17]
 1 │ history | where exit_status  == 0
   ·                 ─────┬─────┬
   ·                      │     ╰── value originates here
   ·                      ╰── cannot find column 'exit_status'
```

```nu
history | columns
╭───┬─────────╮
│ 0 │ command │
│ 1 │ index   │
╰───┴─────────╯
```

my nu version is `.99.1`
am i using an older version so that i do not have that information in the history command output?

**Comment by fdncred** [comment]
I think it requires the sqlite history setting.
```nushell
❯ history | columns
╭───┬─────────────────╮
│ 0 │ start_timestamp │
│ 1 │ command         │
│ 2 │ cwd             │
│ 3 │ duration        │
│ 4 │ exit_status     │
╰───┴─────────────────╯
❯ history -l | columns
╭───┬─────────────────╮
│ 0 │ item_id         │
│ 1 │ start_timestamp │
│ 2 │ command         │
│ 3 │ session_id      │
│ 4 │ hostname        │
│ 5 │ cwd             │
│ 6 │ duration        │
│ 7 │ exit_status     │
│ 8 │ idx             │
╰───┴─────────────────╯
```

**Comment by fdncred** [comment]
`commandline --edit` changes the current reedline buffer.

**Comment by euglevi** [comment]
From some debugging, it seems the issue is with the starship prompt. Any ideas why it might not like the `commandline --edit` command?

**Comment by euglevi** [comment]
It seems like the issue is not specific to starship, it arises each time the prompt is on two lines. For instance, I had this prompt:

`$env.PROMPT_COMMAND = {$"(pwd | path split | last 2 | prepend ".." | str join "/") \n ❯ " }`

and the issue emerged. This can be easily replicated. Is it because commandline re-executes the command?
