### ISSUE TITLE
Wrong `nu` external signature in default config

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#5789]
### Describe the bug

The `nu` command no longer accepts a script file argument.

### How to reproduce

```
> '"foo"' | save --raw foo.nu

> nu foo.nu
Error: nu::parser::extra_positional (link)

  × Extra positional argument.
   ╭─[entry #21:1:1]
 1 │ nu foo.nu
   ·    ───┬──
   ·       ╰── extra positional argument
   ╰────
  help: Usage: nu {flags}
```

Adding a hashbang and executing the file directly works fine:
```
> open foo.nu
#!/usr/bin/env nu
"foo"

> chmod +x foo.nu

> ./foo.nu
foo
```

### Expected behavior

Should run fine

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.64.0                                          |
| branch             | master                                          |
| commit_hash        | ff73623873bfdaff0d8eccbab527be3212ac2a68        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)               |
| pkg_version        | 0.64.0                                          |
| build_time         | 2022-06-15 13:15:58 +03:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | gstat                                           |

### Additional context

I'm pretty sure this worked in 0.63. Seems like it got broken recently.

**Comment by WindSoilder** [comment]
It's strange that I can't reproduce it...My configuration..
```

╭────────────────────┬─────────────────────────────────────────────╮
│ version            │ 0.64.0                                      │
│ branch             │                                             │
│ commit_hash        │                                             │
│ build_os           │ macos-x86_64                                │
│ build_target       │ x86_64-apple-darwin                         │
│ rust_version       │ rustc 1.63.0-nightly (1fede1753 2022-05-28) │
│ rust_channel       │ nightly-x86_64-apple-darwin                 │
│ cargo_version      │ cargo 1.63.0-nightly (39ad1039d 2022-05-25) │
│ pkg_version        │ 0.64.0                                      │
│ build_time         │ 2022-06-15 15:48:29 +08:00                  │
│ build_rust_channel │ release                                     │
│ features           │ default, trash, which, zip                  │
│ installed_plugins  │                                             │
╰────────────────────┴─────────────────────────────────────────────╯
```

**Comment by Kangaxx-0** [comment]
> Oh, I think it's the extern signatures defined in the completions in the default config -- it doesn't have a positional:
> 
> https://github.com/nushell/nushell/blob/cfe4eff566441de19d635ef30ca35b9b63489b95/docs/sample_config/default_config.nu#L125
> 
> . Without the external signature it works fine.
> I think the `nu` external signature should be removed from the default config because the nu command has an unusual signature that cannot be replicated with basic command signatures (yet!).

Instead of remove `extern nu`, do you think we could simply add one positional arg, maybe even a default completion like 

```
  export extern "nu" [
    ...arg?: string@"xxxx completion,  maybe path completion" 
    --help(-h)                # Display this help message
```

**Comment by kubouch** [comment]
The thing is that with external completion, you couldn't pass flags to the script itself. We can't do that yet with Nushell signatures. So I think the best would be to remove it until we have a way to reproduce the signature precisely.
