### ISSUE TITLE
Repository for common extern completion definitions?

### ISSUE THREAD

**Issue by chtenb** [nushell/nushell#5792]
### Related problem

In bash many common programs have working completion (more or less) out of the box. In nushell the default config only contains definitions for three git commands. Defining all the commands yourself is tedious and unnecessary duplicate effort.

### Describe the solution you'd like

An easy way to share completion definitions with other people.

- Perhaps just a larger default set of completions and actively encouraging people to provide PRs for it
- A separate config repository where people can contribute completion definitions

### Additional context and details

It would also be worthwhile to make it easy to split these completions over different files that can be imported from the users config.nu or from a default directory or something. Copy pasting them into config.nu becomes very unwieldy very quickly.

**Comment by fdncred** [comment]
We keep our contributed custom completions here https://github.com/nushell/nu_scripts/tree/main/custom-completions

**Comment by chtenb** [comment]
> We keep our contributed custom completions here [https://github.com/nushell/nu_scripts/tree/main/custom-completions](https://github.com/nushell/nu_scripts/tree/main/custom-completions?rgh-link-date=2022-06-15T13%3A26%3A14Z)

Thats great! I think I will clone that repository and import git, cargo and npm.

> This may help: [https://github.com/nushell/nu_scripts/tree/main/custom-completions/auto-generate/completions](https://github.com/nushell/nu_scripts/tree/main/custom-completions/auto-generate/completions?rgh-link-date=2022-06-15T13%3A22%3A15Z)

Is there a way to simply import all of those autogenerated completions for the commands that do not have custom completions yet?

**Comment by fdncred** [comment]
> Is there a way to simply import all of those autogenerated completions for the commands that do not have custom completions yet?

it's a common question. there is no way to do it right now that i know of. we plan on adding the ability to source everything in a directory.

**Comment by fdncred** [comment]
closing since the i believe the questoin is answered.

**Comment by ameknite** [comment]
maybe it can help someone:
```nu
# nu_scripts
let scripts_path  = ($env.HOME + /.config/nushell/nu_scripts/custom-completions)

let names = ls $scripts_path | where type == dir | each { |it| $it.name | path basename | $"($in)" }
let names = $names |  where $it != yarn | where $it != bend | where $it != tealdeer | where $it != auto-generate | where $it != pass  

let paths = $names | each {|it| $"source ~/.config/nushell/nu_scripts/custom-completions/($it)/($it)-completions.nu"}


"\n# nu_scripts\n" | save --append ($nu.config-path)
$paths | save --append ($nu.config-path)
```

**Comment by fdncred** [comment]
I landed a PR yesterday that adds a `$nu.cache-dir` and `$nu.data-dir` variable. It also adds a folder to the `$env.NU_LIB_DIRS` list.
```nushell
    ($nu.data-dir | path join 'completions') # default home for nushell completions
```

At some point we plan to add a system-level home for completions but we're not there yet.
