### ISSUE TITLE
Is there a way to use MSVC in nushell

### ISSUE THREAD

**Issue by Neur1n** [nushell/nushell#5803]
### Related problem

I'm trying to replace cmd/pwsh with nushell while compiling C/C++ codes, but couldn't find any instructions to import MSVC environment parameters ([vcvarsall.bat](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170) or [Enter-VsDevShell](https://gist.github.com/ArthurHNL/b29f008cbc7a159a6ae82a7152b1cb2a)).

### Describe the solution you'd like

Some instructions to make MSVC command lines workable in nushell.

**Comment by hustcer** [comment]
Is this what you want？ https://www.nushell.sh/book/installation.html#installing-a-compiler-suite

**Comment by Neur1n** [comment]
> Is this what you want？ https://www.nushell.sh/book/installation.html#installing-a-compiler-suite

Thanks for your response. But the linked web page is about compiling nushell from source. Instead, I need to compile any C/C++ codes by calling command lines in nushell. For instance, in powershell core:

1. Write a hello_world.cpp and corresponding CMakeLists.txt
2. In powershell core:
```ps1
Enter-VsDevShell  # this make MSVC tools available
mkdir build && cd build
cmake .. -G Ninja
ninja  # compile using cl.exe from MSVC
./hello_world.exe  # running the executable
```

**Comment by rgwood** [comment]
Good question. The easiest way is probably to launch Nu from a cmd shell with all the necessary environment variables set. So maybe something like this but for Nu:

![image](https://user-images.githubusercontent.com/26268125/173987508-3f7530ff-065a-4143-bcad-afefca324878.png)

**Comment by Neur1n** [comment]
> Good question. The easiest way is probably to launch Nu from a cmd shell with all the necessary environment variables set. So maybe something like this but for Nu:


Thanks!

**Comment by adrianstaniec** [comment]
I have such a script `nudevcmd.bat` in my `PATH`:

```bat
@echo off
cd "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\"
call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat"
cd "C:\Users\adrian"
"C:\Users\adrian\scoop\shims\nu.exe"
```
and this in my `AppData/Roaming/alacritty/alacritty.toml`:
```toml
[terminal.shell]
program = "nudevcmd.bat"
```

**Comment by AnNingUI** [comment]
see my [solution](https://github.com/AnNingUI/My-Nushell)
