### ISSUE TITLE
problems with the removal of the "dfr" command (specially inside of <Block>)

### ISSUE THREAD

**Issue by ynhame** [nushell/nushell#5810]
### Describe the bug

after the removal of the `dfr` command in the new 0.64 release some data-frame command's do not work inside of a block. For example:

### this works:
```
> let a = ([[a,b];[2,3]] | to-df)
> let b = ([[a,b];[2,3]] | to-df)
> let c = ([[a,b];[2,3]] | to-df)
> let test_list = ([$a, $b, $c])
```

### this works:
```
> $a | shape  # works
```

### this also works:
```
> do { |x, y| $x + $y } $a $b
```

### but this doesn't work:
```
❯ do { |x| $x | shape } $a
Error: nu::shell::external_command (link)

  × External command
   ╭─[entry #80:1:1]
 1 │ do { |x| $x | shape } $a
   ·               ──┬──
   ·                 ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)
```

### neither does this:
```
> $test_list | reduce { | it, acc | $acc | append -c $it }
Error: nu::parser::unknown_flag (link)

  × The `append` command doesn't have flag `-c`.
   ╭─[entry #65:1:1]
 1 │ $test_list | reduce { |it, acc| $acc | append -c $it }
   ·                                                ┬
   ·                                                ╰── unknown flag
   ╰────
  help: use append --help for a list of flags
```

### nor this:
```
> $test_list | each { |element| $element | shape }
Error: nu::shell::external_command (link)

  × External command
   ╭─[entry #69:1:1]
 1 │ $test_list | each { |data| $data | shape }
   ·                                    ──┬──
   ·                                      ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)

```

### this works:
```
echo ( $a | shape )
```

### but this doesn`t:
```
> def echo_shape [x] { echo ( $x | shape ) }
> echo_shape $a
Error: nu::shell::external_command (link)

  × External command
   ╭─[entry #97:1:1]
 1 │ def echo_shape [x] {echo ($x | shape)}
   ·                                ──┬──
   ·                                  ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)
```

### How to reproduce

1. make a data-frame:
```
let a = ( [[a,b]; [0,1]] | to-df )
``` 

2. pipe this object to any command that takes a block as an argument. Like `each`, `reduce`, `do` or `def` (maybe there are others. I just tested those) and inside the block run a `dfr` command.
```
$a | each { |$x| echo ( $x | shape ) }
```

### Expected behavior

I've used some of this in the previous version (0.63) and they worked just fine with the `dfr` keyword.

Another problem that I am having is that without the `dfr` keyword I cannot do `dfr --help` to see all the available `dfr` commands or do `dfr append --help` to know that the `dfr append` supports the `--col` flag.

I know that I can make dummy data-frame and pipe it to `append --help` to see the dfr append flags and examples.

```
> [[]] | to-df | append --help
```

But I think the previous way of doing this was more straightforward.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.64.0                                          |
| branch             |                                                 |
| commit_hash        | d1c719a8cc52b1cb3f60810daa8bf28e69eb6617        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.61.0 (Arch Linux rust 1:1.61.0-1)       |
| cargo_version      | cargo 1.61.0                                    |
| pkg_version        | 0.64.0                                          |
| build_time         | 2022-06-15 07:31:53 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by elferherrera** [comment]
The problem is that the block doesn't know the type of the variable when captured. A quick fix would be to add a `to-df` before the shape command in order to give a type to the value inside the block
