### ISSUE TITLE
Environment variable named WIN32 can sometimes not be found 

### ISSUE THREAD

**Issue by bugabinga** [nushell/nushell#5811]
### Describe the bug

In my `env.nu` there is the following definition: `let-env WIN32? = ( $nu.os-info.name =~ "windows" )`.

When starting `nu` "normally", as a REPL, the value is accessible via `$env.WIN32?`.
When executing commands via `nu -c` or script `nu script.nu`, the value cannot be found.
Other environment variable do not seem to be affected.

### How to reproduce

test-env.nu
```nu
let-env WIN32 = ( $nu.os-info.name =~ "windows" )
let-env WIN32? = ( $nu.os-info.name =~ "windows" )

let-env WORKSPACE = if $env.WIN32? { "W:/" } else { "~/Workspace" | path expand }
let-env WORKSPACE? = if $env.WIN32? { "W:/" } else { "~/Workspace" | path expand }
```

test-config.nu
```
<empty>
```

```sh
💻\nushell   main ▶ cargo run -- --env-config test-env.nu --config test-config.nu                14ms ✓ 16.06 16:08    Finished dev [unoptimized + debuginfo] target(s) in 0.75s
     Running `target\debug\nu.exe --env-config test-env.nu --config test-config.nu`
~\Workspaces\nushell ▶ $env.WIN32?                                                             06/16/2022 04:10:11 PMtrue
~\Workspaces\nushell ▶ $env.WIN32                                                              06/16/2022 04:10:13 PMtrue
~\Workspaces\nushell ▶ $env.WORKSPACE                                                          06/16/2022 04:10:19 PMW:/
~\Workspaces\nushell ▶ $env.WORKSPACE?   

💻\nushell   main ▶ cargo run -- --env-config test-env.nu --config test-config.nu               795ms ✓ 16.06 16:17    Finished dev [unoptimized + debuginfo] target(s) in 0.73s
     Running `target\debug\nu.exe --env-config test-env.nu --config test-config.nu`
~\Workspaces\nushell ▶ cargo run -- -c '$env.WORKSPACE?'                                       06/16/2022 04:17:50 PM    Finished dev [unoptimized + debuginfo] target(s) in 0.71s
     Running `target\debug\nu.exe -c $env.WORKSPACE?`
W:/
~\Workspaces\nushell ▶ cargo run -- -c '$env.WORKSPACE'                                        06/16/2022 04:17:53 PM    Finished dev [unoptimized + debuginfo] target(s) in 0.72s
     Running `target\debug\nu.exe -c $env.WORKSPACE`
W:/
~\Workspaces\nushell ▶ cargo run -- -c '$env.WIN32'                                            06/16/2022 04:18:01 PM    Finished dev [unoptimized + debuginfo] target(s) in 0.71s
     Running `target\debug\nu.exe -c $env.WIN32`
Error: nu::shell::name_not_found (link)

  × Name not found
   ╭─[source:1:1]
 1 │ $env.WIN32
   ·      ──┬──
   ·        ╰── did you mean 'windir'?
   ╰────

error: process didn't exit successfully: `target\debug\nu.exe -c $env.WIN32` (exit code: 1)
~\Workspaces\nushell ▶ cargo run -- -c '$env.WIN32?'                                           06/16/2022 04:18:03 PM
    Finished dev [unoptimized + debuginfo] target(s) in 0.73s
     Running `target\debug\nu.exe -c $env.WIN32?`
Error: nu::shell::name_not_found (link)

  × Name not found
   ╭─[source:1:1]
 1 │ $env.WIN32?
   ·      ───┬──
   ·         ╰── did you mean 'windir'?
   ╰────

error: process didn't exit successfully: `target\debug\nu.exe -c $env.WIN32?` (exit code: 1)
```

To summarize, inside the nested `nu --commands`/`nu <script>` the following values are visible:

| value      | visible |
| ---------- | ------- |
| WIN32?     | false   |
| WIN32      | false   |
| WORKSPACE  | true    |
| WORKSPACE? | true    |

I am unsure as to wether both `WIN32` and `WORKSPACE` should be accessible inside a nested nushell command/script or wether both should _not_ be accessible.

For reference, when repeating the test, but with powershell as the parent shell __all__ values are `false`.

In Nushell version `0.63.0` all values were `true`, I assume, because my scripts did not fail then.

Initially I thought the cause could have been the `?` in the name. But that does seem to be the case.

### Expected behavior

I am quiet unsure as to what is going on, and what should be going on.

Should `--commands` and scripts evaluate `env.nu`?
If not, how come some environment variables seem to be exported to child nu processes and some not? 

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.64.0                                   |
| branch             | main                                     |
| commit_hash        | cfe4eff566441de19d635ef30ca35b9b63489b95 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)      |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)      |
| pkg_version        | 0.64.0                                   |
| build_time         | 2022-06-16 10:49:43 +02:00               |
| build_rust_channel | debug                                    |
| features           | default, trash, which, zip               |
| installed_plugins  | gstat                                    |

**Comment by rgwood** [comment]
Hi, you may want to try the `--env-config` flag. 

When running a script like `nu foo.nu`, the new Nu instance will *not* load your usual env+config files unless you specify them. 

However, I'm not sure why the environment variable would not be inherited from the parent Nu instance. Some more investigation is needed there.

```
〉nu --help
The nushell language and shell.

Usage:
  > nu {flags} (script file) ...(script args)

Flags:
  -h, --help - Display the help message for this command
  --stdin - redirect the stdin
  -l, --login - start as a login shell
  -i, --interactive - start as an interactive shell
  -v, --version - print the version
  --testbin <String> - run internal test binary
  -c, --commands <String> - run the given commands and then exit
  --config <String> - start with an alternate config file
  --env-config <String> - start with an alternate environment config file
```

Alternately you may be able to get by
