### ISSUE TITLE
Improve custom completions docs

### ISSUE THREAD

**Issue by Yethal** [nushell/nushell#5831]
### Related problem

Custom completion commands supposedly take optional arguments that can be used to drive their internal logic, they can also output description and extras next to actual values to be more informative. Unfortunately none of this is documented in the docs.

### Describe the solution you'd like

For someone who understands the custom completions to update the docs or explain to me how this works and I'll do it.

**Comment by sholderbach** [comment]
This is feature is now documented here: https://www.nushell.sh/book/custom_completions.html#custom-descriptions
