### ISSUE TITLE
"cd" command with fzf cannot run

### ISSUE THREAD

**Issue by tourmaline3333** [nushell/nushell#5832]
### Describe the solution you'd like

I can run the command below on powershell.
but I cannot run the command on nushell.

1. fd -H -t d -E .git -E node_modules | fzf | cd 
2. cd $(fd -H -t d -E .git -E node_modules | fzf )

anyone know good idea?
thanks

**Comment by rgwood** [comment]
1. Can you please let us know how exactly Nushell is failing? Is there an error message?
2. What version of Nushell are you on? You can run `version | transpose key value | to md --pretty` to get info that can be pasted into GitHub.

**Comment by tourmaline3333** [comment]
thank you for your reply.

> Can you please let us know how exactly Nushell is failing? Is there an error message?
>
1. fd -H -t d -E .git -E node_modules | fzf | cd
-> no error message.
    open fzf windows but cannot select text (cannot input arrow key), and go home directory automatic


2. cd $(fd -H -t d -E .git -E node_modules | fzf )
->
Error: nu::parser::parse_mismatch (link)

  × Parse mismatch during operation.
   ╭─[entry #5:1:1]
 1 │ cd $( fd -H -t d -E .git -E node_modules | fzf )
   ·    ──────────────────────┬──────────────────────
   ·                          ╰── expected variable
   ╰────

>What version of Nushell are you on? You can run version | transpose key value | to md --pretty to get info that can be pasted into GitHub.
>
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.64.0                                          |
| branch             |                                                 |
| commit_hash        | d1c719a8cc52b1cb3f60810daa8bf28e69eb6617        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)             |
| pkg_version        | 0.64.0                                          |
| build_time         | 2022-06-15 03:08:29 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
take the `$` off and it seems to work for me

`cd (fd -H -t d -E .git -E node_modules | fzf)`

**Comment by tourmaline3333** [comment]
Oh...I success..
thank you for your reply.

**Comment by fdncred** [comment]
no problem
