### ISSUE TITLE
Unexpected `Types mismatched for operation` error for `||` operator

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#5842]
### Describe the bug

Unexpected `Types mismatched for operation` error for `||` operator

### How to reproduce

1. Create foo.nu in a git repo with contents:
```shell
# Check if a git repo has the specified ref: could be a branch or tag, etc.
def 'has-ref' [
  ref: string   # The git ref to check
] {
  let parse = (git rev-parse --verify -q $ref)
  if ($parse | empty?) { false } else { true }
}

let br2 = 'master';
let br1 = 'develop';

if ((has-ref $br1) || (has-ref $br2)) {
    'Branch exists'
} else {
    $'Branch does not exist!'
}
```
2. Run `nu foo.nu` will get:
```
Error: nu::parser::unsupported_operation (link)

  × Types mismatched for operation.
    ╭─[tmp/fo.nu:12:1]
 12 │
 13 │ if ((has-ref $br1) || (has-ref $br2)) {
    ·     ───────┬────── ─┬ ───────┬──────
    ·            │        │        ╰── string
    ·            │        ╰── doesn't support these values.
    ·            ╰── string
 14 │     'Branch exists'
    ╰────
  help: Change string or string to be the right types and try again.

```

### Expected behavior

The output should be the same as running:
```shell

# Check if a git repo has the specified ref: could be a branch or tag, etc.
def 'has-ref' [
  ref: string   # The git ref to check
] {
  let parse = (git rev-parse --verify -q $ref)
  if ($parse | empty?) { false } else { true }
}

if ((has-ref develop) || (has-ref master)) {
    'Branch exists'
} else {
    $'Branch does not exist!'
}
```

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.64.0                                              |
| branch             | develop                                             |
| commit_hash        | dbcfcdae89d06d69fb034ddf0bc2086c566c7e61            |
| build_os           | macos-x86_64                                        |
| build_target       | x86_64-apple-darwin                                 |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)                 |
| rust_channel       | stable-x86_64-apple-darwin                          |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)                 |
| pkg_version        | 0.64.0                                              |
| build_time         | 2022-06-20 19:18:22 +08:00                          |
| build_rust_channel | release                                             |
| features           | database, dataframe, default, trash, which, zip     |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by elferherrera** [comment]
We need a syntax to indicate that the type output for `has-ref` is bool. Meanwhile we can enable bool comparison for types other than bool

**Comment by hustcer** [comment]
Something like this?

```shell
def 'has-ref' : bool [
  ref: string   # The git ref to check
] {
  let parse = (git rev-parse --verify -q $ref)
  if ($parse | empty?) { false } else { true }
}
```

So the default output type is `string`?

**Comment by elferherrera** [comment]
yeap, otherwise the parser is inferring that the output from that function is `string`. The operators AND and OR were only working on booleans that's why that PR should enable (until the syntax is enriched) comparison between non boolean types

**Comment by fdncred** [comment]
fixed with https://github.com/nushell/nushell/pull/5844 - please reopen if I'm mistaken.
