### ISSUE TITLE
Cannot shadow some builtin variables

### ISSUE THREAD

**Issue by Benjamin-L** [nushell/nushell#5848]
### Describe the bug

Generally, it is possible to shadow any variable declaration, with a `let` binding, or by assigning it as a function argument. For some builtin variables (`$env` and `$nu` for example), this silently fails.

### How to reproduce

Attempt to shadow a builtin variable with a let-binding.

```nu
let env = 42
$env
```

### Expected behavior

Either the first line should throw an error, saying that shadowing builtin variable definitions is not valid, or it should complete successfully, and further references to `$env` should reference the shadowed value.

### Screenshots

```nu
> let env = 42
> $env == 42
false
```

### Configuration

> version | transpose key value | to md --pretty

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.63.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | macos-x86_64                                    |
| build_target       | x86_64-apple-darwin                             |
| rust_version       | rustc 1.61.0                                    |
| cargo_version      | cargo 1.61.0                                    |
| pkg_version        | 0.63.0                                          |
| build_time         | 1980-01-01 00:00:00 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
`$env` is a special variable. You probably can't shadow `$nu` either, which is another special variable.

**Comment by Benjamin-L** [comment]
Yeah, that makes sense. I think attempting to do so should throw an error rather than silently doing nothing.

The way I actually encountered this in the wild was writing a script that involved working with "environment" objects, and picked `env` as the name for some function arguments without thinking about it. Took me a bit to untangle what was going wrong.

**Comment by fdncred** [comment]
ya, a warning would be nice.

**Comment by fdncred** [comment]
Here's a list of special variables that probably cannot be shadowed.

- `$nu`
- `$in`
- `$env`
- `$nothing`
