### ISSUE TITLE
All-in-one http command

### ISSUE THREAD

**Issue by obust** [nushell/nushell#585]
There is now 2 commands dedicated to http communication:

- `fetch url`: Fetch contents from a url and retrieve data as a table if possible
- `post url body (--user <user>) (--password <password>)`: Post content to a url and retrieve data as a table if possible

Given the scope of http communication (methods, headers, authentication, etc.), feature requests can only increase.

Previous CLI tools have shown that it is possible to have all-in-one http tool. Here are some cheatsheets:
- [curl](https://devhints.io/curl)
- [HTTPie](https://devhints.io/httpie)
- [request-cli](https://www.npmjs.com/package/request-cli)

In order not to clutter `nu` std lib, it might make more sense to also have a all-in-one http command (or plugin maybe).

**Comment by pmeredit** [comment]
https://github.com/saghm/rural could be useful

**Comment by dead10ck** [comment]
I would find this very useful myself. I keep finding myself writing helpers over a REST API and running into this problem that there's no way to just specify a method generically.
