### ISSUE TITLE
Add a hyperlink awareness

### ISSUE THREAD

**Issue by zhiburt** [nushell/nushell#5857]
Hi there

Just one small thing came to my mind.
There could be set a check if we output url and cover it via some magic sequence so it would be clickable in terminal.

`printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'`\

https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

I do understand that most likely it will bring a performance penalties if done in a straight way.
But maybe some utils could be added or something like it.

I am not sure if it's the duplicate.
I am not neither sure if it's useful.

Thanks.

Take care.

**Comment by fdncred** [comment]
I could see adding something like this to the `url` command or some other command that deals with URLs but I'm not sure we want to parse all the output of every nushell command searching for urls in order to linkify them.

Where would you see using this?

**Comment by kubouch** [comment]
My terminal (Alacritty) makes links clickable by default when running Nushell.

If it's just about adding those markers, I guess it could be added to the final view step where we do the coloring etc. It seems to me, though, it's not a shell thing but rather a job for the terminal emulator.

**Comment by zhiburt** [comment]
> My terminal (Alacritty) makes links clickable by default when running Nushell.

Actually you're right seems like modern terminals do recognize links already out of the box.
`wezterm` also does.

But it's like a hidden link.
Not all of terminals yet support it as far as I understand.

https://github.com/alacritty/alacritty/issues/922

> I could see adding something like this to the url command or some other command that deals with URLs but I'm not sure we want to parse all the output of every nushell command searching for urls in order to linkify them.

After all to be honest I was thinking initially not about hidden links but more about general case.
So I guess it may not be that useful?

 Perhaps it can be closed

**Comment by fdncred** [comment]
thanks for the idea. i'll close for now.
