### ISSUE TITLE
`git fetch origin foo` will failed

### ISSUE THREAD

**Issue by lafirest** [nushell/nushell#5858]
### Describe the bug

In bash , I can run `git fetch origin master`
but in nu, this command will throw a error

### How to reproduce

1. change dir into a git repo
2. touch `git fetch origin master`

### Expected behavior

work correctly

### Screenshots

![image](https://user-images.githubusercontent.com/22971499/175189550-f4d7d760-d11a-4aaa-bd17-1efa85c80643.png)

### Additional context

cat /etc/gentoo-release                                                                                     06/23/2022 09:48:02 AM
Gentoo Base System release 2.8

uname -a                                                                                                    06/23/2022 09:48:20 AMLinux 59e309d4b891 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 12th Gen Intel(R) Core(TM) i7-12700H GenuineIntel GNU/Linux

**Comment by fdncred** [comment]
This is probably because the git custom completions are incomplete. To get around this, one could either help finish the git custom completions in the nu_script repo or do `^git fetch origin master`. I think the `^` will make it bypass the custom completions.
