### ISSUE TITLE
Deprecate `hash base64` in favor of a more accurate command name

### ISSUE THREAD

**Issue by CBenoit** [nushell/nushell#5861]
### Related problem

Nushell is generally good when it comes to naming, however, `hash base64` is not optimal in that aspect.

Indeed, base64 is a lossless binary-to-text encoding strictly representing a binary payload, not a hash digest, it is improper for any (cryptographic) hash application such as signatures and authentication codes.
Furthermore, while hash functions are one-way, an efficient reverse operation is available when it comes to base64 (and other similar encodings such as hexadecimal).
While technically not an issue (code can be, and actually is fully separated from the other hash functions as if it was an unrelated command), putting this command under the `hash` family harms discoverability (I believe most people don’t expect to find base64 there) and might lead some users to misunderstandings.

I believe this issue can inform naming for a future hexadecimal conversion command as well.

### Describe the solution you'd like

The encoding part could be moved to `into base64` and the decoding part to `from base64`. Any better suggestion is welcomed!

#### New `decode` and `encode` families

I actually like this alternative, but the number of command families is increased.

We could have commands such as:
- `encode base64`
- `decode base64`
- `encode hex`
- `decode hex`

One other issue is that the `decode` command already exists.

#### `str base64`

I don’t think it’s the best, especially since all `str to-datetime`, `str to-decimal`, `str to-int` got deprecated recently in favor of `into` alternatives.

#### `to base64`

`to` family is used to translate structured data into an equivalent structured format such as json or xml. base64 is not a structured format, so I don’t think it belongs to this family.

### Additional context and details

This is something I already mentioned [back when we were porting the commands to engine-q](https://github.com/nushell/engine-q/issues/242#issuecomment-989339902). The deprecation didn’t happen at that time in an effort to limit the number of breaking changes at a time. I think now is a good time to revisit the idea.

**Comment by CBenoit** [comment]
By the way, I volunteer to send PRs once the action plan is clear 🙂

**Comment by WindSoilder** [comment]
Hi, @CBenoit Thanks for your detailed idea, I love it very much :-D

Just as a user, I generally agree most of them, but except one:
> decoding part to from base64

I'd suggest using `to base64` instead, I've checked `from` relative command, `from` commands are convert into data to `nu tables`.  But `to` commands output are all text, which is more suited for the case.

**Comment by fdncred** [comment]
this topic has been brought up before and i tend to agree that base64 is not a hashing mechanism. after reading your suggestions, my initial reaction was `into/from` or `to/from` but I'm leaning more toward `encode/decode`. we already have `decode utf-8` (and other encodings) that was ported over during the engine-q migration.

what do others think? oh, this would be a good discussion poll too - let me add that after we settle down on the options.

**Comment by WindSoilder** [comment]
Yeah, I like `encode/decode`, it's clearer to me :)
