### ISSUE TITLE
"expected short flag" when defining completions for commands that use `-longflag` format

### ISSUE THREAD

**Issue by RReverser** [nushell/nushell#5862]
### Describe the bug

Many commands like ffmpeg or every CLI tool written in Go use `command -longflag` format instead of the Unix-like `command --longflag`. Currently it's very difficult (impossible?) to define completions for those in nushell.

### How to reproduce

Define and load example completions for ffmpeg like:

```
export extern "ffmpeg" [
  -L # show license
  -h topic:any # show help
  -help topic:any # show help
  --help topic:any # show help
  -version # show version
  -buildconf # show build configuration
  -formats # show available formats
  -muxers # show available muxers
  -demuxers # show available demuxers
  -devices # show available devices
  -codecs # show available codecs
  -decoders # show available decoders
  -bsfs # show available bit stream filters
  -protocols # show available protocols
  -filters # show available filters
  # ...
]
```

You'll get an error:

```
Error: nu::parser::parse_mismatch (link)

  × Parse mismatch during operation.
   ╭─[entry #3:3:1]
 3 │   -h topic:any # show help
 4 │   -help topic:any # show help
   ·   ──┬──
   ·     ╰── expected short flag
```

### Expected behavior

The completions parse successfully and define the command.

**Comment by RReverser** [comment]
Just to add another usecase - compilers that accepts flags like `-Wall`, `-Weverything` and such.

**Comment by fnuttens** [comment]
I ended up here after trying to configure a completion for `git branch -vv`. The support for these "weird" flags would be a nice to have 🙂

**Comment by RReverser** [comment]
@fnuttens I guess for git usecase you at least have a workaround in form of `git branch -v -v`?

**Comment by fnuttens** [comment]
@RReverser it seems like this isn't supported either. The 'v's are interpreted as two distinct options:

```sh
❯ | git branch -
...
-v
-v print...
```

But in the end that's alright since nushell doesn't raise an error for `git branch -vv`.

**Comment by RReverser** [comment]
> The 'v's are interpreted as two distinct options:

Right, but that should be fine because that's how they're treated by most argument parsers (I assume by Git too) anyway? (as in, `-abcd` should be always equivalent to `-a -b -c -d`, and `-vv` should be equivalent to repeating `-v` couple of times)

**Comment by fnuttens** [comment]
Indeed, but `-vv` (or `-v -v`) isn't the same as mixing together unrelated options, like `-ab`. Adding a second 'v' changes the output of the `git branch` command, so `-vv` is like a single option in its own right.

**Comment by sholderbach** [comment]
We had several duplicate issues of this kind. Continuing tracking on #5959 as we still haven't made progress.
