### ISSUE TITLE
Automatically type enter when the terminal starts

### ISSUE THREAD

**Issue by Learces** [nushell/nushell#5867]
### Describe the bug

Every time I open the terminal, two blank command lines will appear。

### How to reproduce

Every time I open the terminal

### Expected behavior

just like normal

### Screenshots

![图片](https://user-images.githubusercontent.com/94371988/175550780-824f6e2b-b8ed-403d-9cb4-72c40a25752a.png)

**Comment by rgwood** [comment]
@Learces Let us know if you're still experiencing this issue. We'll need your Nu version info (`version | transpose key value | to md --pretty`)` and it would help to know how/whether you've customized your Nu prompt+config.
