### ISSUE TITLE
can't use less command on windows, despite a less.exe executable being present

### ISSUE THREAD

**Issue by mattiamarchesini** [nushell/nushell#5868]
### Describe the bug

Just installed nushell on Windows 10 home.

When I typed `less` for the first time I've noticed a new `less.exe` executable appeared in my `C:\Program Files\nu\bin` folder. However it doesn't seem to work at all. 

In fact, a pop-up shows up telling me that is not possible to run this "app" on my computer.

### How to reproduce

1. install nushell on on Windows 10 home
2. type less

### Expected behavior

If a less exe is installed by nu by default, it should run.

Doesn't make sense to install it if it's not supposed to work right now.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.64.0                                          |
| branch             |                                                 |
| commit_hash        | d1c719a8cc52b1cb3f60810daa8bf28e69eb6617        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)             |
| pkg_version        | 0.64.0                                          |
| build_time         | 2022-06-15 03:10:01 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by mattiamarchesini** [comment]
Forgot to mention this:

The pop-up is not the only error that shows up. The shell prompt shows an error as well (thought it just says "acces denied").

I've achieved the same result when running the executable on cmd, so it's not specific to nu but it's probably specific to the O.S.

**Comment by fdncred** [comment]
sounds like we must be packaging less.exe wrong these days. as a work-around, if you have another one you can just rename/delete the one included with nushell.

**Comment by hustcer** [comment]
It seemed that the `less.exe` download failed by curl, the file size is 0. I will try to fix it later

**Comment by hustcer** [comment]
It will be fixed in the next released v0.65.0
