### ISSUE TITLE
0.64 Mis-types strings as bools in return expression, won't "+" them

### ISSUE THREAD

**Issue by adamshackleford** [nushell/nushell#5869]
### Describe the bug

nushell 0.64.0 is mistaking strings for bools, and is thus blowing up when I try to "+" the "bools" (which are actually strings).

Version 0.61.0 correctly executes env.nu-0.61.0.txt.
Version 0.64.0 mistakes strings for bools when trying to execute env.nu-0.61.0.txt.

```
[~/Library/Application Support/nushell master 1]$ nu
Error: nu::parser::unsupported_operation (link)

  × Types mismatched for operation.
     ╭─[/Users/adam/Library/Application Support/nushell/env.nu:107:1]
 107 │             (
 108 │                 (format_git_status_count $status_record staged $staged_color $compress_count) +
     ·                 ──────────────────────────────────────┬────────────────────────────────────── ┬
     ·                                                       │                                       ╰── doesn't support these values.
     ·                                                       ╰── bool
 109 │                 (format_git_status_count $status_record unstaged $unstaged_color $compress_count) +
     ·                 ────────────────────────────────────────┬────────────────────────────────────────
     ·                                                         ╰── bool
 110 │                 (format_git_status_count $status_record untracked $untracked_color $compress_count)
     ╰────
  help: Change bool or bool to be the right types and try again.

```

Version 0.64.0 correctly executes env.nu-0.64.0.txt (a "corrected" version of env.nu that should not be required, since env.nu-0.61.0.txt is fine.)

[env.nu-0.61.0.txt](https://github.com/nushell/nushell/files/8977350/env.nu-0.61.0.txt)
[env.nu-0.64.0.txt](https://github.com/nushell/nushell/files/8977351/env.nu-0.64.0.txt)

### How to reproduce

1. In nushell 0.64.0, try to execute env.nu-0.61.0.txt
2. Watch it blow up.
3. diff env.nu-0.61.0.txt and env.nu-0.64.0.txt.

### Expected behavior

nushell 0.64.0 should execute env.nu-0.61.0.txt without error, just as nushell 0.61.0 did.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.64.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | macos-aarch64                                   |
| build_target       | aarch64-apple-darwin                            |
| rust_version       | rustc 1.61.0                                    |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)             |
| pkg_version        | 0.64.0                                          |
| build_time         | 2022-06-15 02:39:17 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by adamshackleford** [comment]
I'm on the newbie's friend, `brew install nushell`.

Since this is fixed, maybe I'll just chill and wait for 0.65.0.

Thanks for the update. Going to close with this comment.

**Comment by elferherrera** [comment]
Is $compress_count a book?

**Comment by adamshackleford** [comment]
Yes, it's a bool. In this file, it's always `true` (it's a leftover from when I thought this might vary).

**Comment by elferherrera** [comment]
I tested it with a def like this

```
def test [a: int, b: bool] { if b { a + a } else { a } }
```

and then did this
```
(test 1 true) + (test 2 false) 
```
and works in main. So I assume it should work for your function

**Comment by adamshackleford** [comment]
Sure. Adding ints works. Adding strings should work, but doesn't in my example, running on 0.64.0.
