### ISSUE TITLE
Build nushell on Ubuntu 18.04

### ISSUE THREAD

**Issue by jankoprowski** [nushell/nushell#587]
There is an issue in Azure Pipelines:

https://github.com/Microsoft/azure-pipelines-image-generation/issues/506

holding from building nushell under Ubuntu 18.04:

https://github.com/nushell/nushell/pull/586

**Comment by jankoprowski** [comment]
Ticket related with Ubuntu 18.04 on azure side was closed:
https://github.com/microsoft/azure-pipelines-image-generation/issues/506

**Comment by jonathandturner** [comment]
Since we're using Ubuntu 18.04 as one of our release pipelines now, I think we can close this.
