### ISSUE TITLE
Allow doing `error make` without showing the origin

### ISSUE THREAD

**Issue by skelly37** [nushell/nushell#5872]
### Related problem

It would be useful to disable the error origin in custom errors. For example, sometimes you want to simply raise an error when user has passed invalid args. The origin in code makes the feedback more messy.

It worked that way in some previous versions so enabling the functionality shouldn't be that difficult

### Describe the solution you'd like

boolean `origin` field in `error make` record. By default it should remain true, but when set to false, no error origin should be displayed, e.g.:

`error make {msg: "this issue has no code", origin:false}`

**Comment by fdncred** [comment]
I don't understand, can't you just do like it shows in the help?
```
error make {msg: "this is fishy"}
```

**Comment by skelly37** [comment]
> I don't understand, can't you just do like it shows in the help?
> 
> ```
> error make {msg: "this is fishy"}
> ```

It still shows origin

![error](https://user-images.githubusercontent.com/76530971/175667968-a31022f9-6a7d-4240-b9a5-6beb23417412.png)

**Comment by skelly37** [comment]
I'm talking about a possibility to make it just:

Error:
  × abc

**Comment by fdncred** [comment]
oh, I see what you're saying now. thanks for explaining it to me.

**Comment by skelly37** [comment]
Just to add a few words: The current style of errors is helpful for developers while debugging but it's rather counter-intuitive to display the module's code to a casual user (instead of just a message). Having a flag for this would make both sides happier

**Comment by kubouch** [comment]
I think in your case you could use just a regular `print`?

We could add a flag to disable highlighting the span, but I feel unspanned errors should be discouraged because they are super hard to debug if they are somewhere in a script. So I'd rather use `print` in this case and keep `error make` to always create the spanned message.

**Comment by skelly37** [comment]
> I think in your case you could use just a regular `print`?

Errors are associated with an exit code, so instead of just `error make` I'd have to do print, and then invoke `exit 1`, which splits it into two commands. 

Take for example [this script](https://github.com/nushell/nu_scripts/blob/main/filesystem/cdpath.nu). Users don't care about the code, they should just see that they've provided an invalid path. But when you use it inside some script, you'd like to know whether or not it has executed correctly. 

So my opinion is that squashing `print "error msg"; exit 1` into `error make {msg: "error msg", origin: false}` would be useful.

> I feel unspanned errors should be discouraged because they are super hard to debug if they are somewhere in a script.

I agree on that such errors should be rather discouraged and that's why I suggested to keep them the current way (`origin:true`) by default. I just want a flag that has to be explicitly declared to raise a custom error with a full awareness of what you're actually doing, because I find them useful in some cases like the one mentioned above.

*btw: Of course, the flag might be named differently, `origin` is just a draft name. How about `show-span` or `hide-span`?*
