### ISSUE TITLE
Is there a way to create a multiline prompt without starship

### ISSUE THREAD

**Issue by Neur1n** [nushell/nushell#5897]
### Describe the bug

I'm trying to make a multiline prompt, something like the image shown below (this is what I did in pwsh), but without starship. I've tried to add `(char newline)` after the left prompt, right prompt or prompt indicator, but neither worked.

![image](https://user-images.githubusercontent.com/17579247/175956088-a04bec9b-e107-4aea-81eb-7cca669ea8c8.png)

### How to reproduce

Changed the default `create_left_prompt` to
```nu
def create_left_prompt [] {
    let path_segment = ($env.PWD) + $"(char newline)"
    # or ($env.PWD + (char newline)), or something similar

    $path_segment
}
```

And this is the resulting prompt:
![image](https://user-images.githubusercontent.com/17579247/175957402-8228b04a-5234-4b77-a3ca-018fa4f38c81.png)

### Expected behavior

Make a multiline prompt from scratch, without starship.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.64.0                                          |
| branch             |                                                 |
| commit_hash        | d1c719a8cc52b1cb3f60810daa8bf28e69eb6617        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)             |
| pkg_version        | 0.64.0                                          |
| build_time         | 2022-06-15 03:08:29 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
Is this what you're going for?
```
let-env PROMPT_COMMAND = { $"($env.PWD)\n> " }
```

**Comment by Neur1n** [comment]
> Is this what you're going for?
> 
> ```
> let-env PROMPT_COMMAND = { $"($env.PWD)\n> " }
> ```

Yes! Thank you very much!
But why is it not working if there is no visible character (e.g. `>` in your example) after `\n`?

**Comment by Neur1n** [comment]
Sorry about my description. What I meant "not working" is something like
`let-env PROMPT_COMMAND = { $"( $env.PWD)\n" }`.

**Comment by fdncred** [comment]
oh, weird. I guess we're doing a `trim` at some point removing that "\n"

**Comment by Neur1n** [comment]
Correct: `let-env PROMPT_COMMAND = { $"( $env.PWD)\n " }` (`\n` followed by a white space) works as well.
