### ISSUE TITLE
Embedding nushell into other applications.

### ISSUE THREAD

**Issue by princebett** [nushell/nushell#5902]
## In the current state can nushell (or engine) be embedded in other applications ? 
I can think of the following scenarios: 
- literate programming application that uses nushell to work with data. 
- file manager that can enter (cd) into structured data.

### Describe the solution you'd like

An API wrapper around nushell suitable for embedding.

### Describe alternatives you've considered

Spawning nushell as child process.

**Comment by rgwood** [comment]
Hi, Nushell’s architecture is fairly modular and each crate is published to crates.io. They can be used in any Rust application. Let us know if you have trouble using them.

https://crates.io/crates/nu/0.64.0/dependencies

**Comment by fdncred** [comment]
Yes, you can. Here's an example of someone who embedded nushell in their application http://couchbase.sh

**Comment by stormasm** [comment]
@princebett if you have more questions on how to do this contact me on discord

**Comment by princebett** [comment]
> Yes, you can. Here's an example of someone who embedded nushell in their application http://couchbase.sh

Thank you so much ! I'll definitely use this as a reference. 

> @princebett if you have more questions on how to do this contact me on discord

Thank you for the open invitation. Once I get into the weeds I'll definitely take you up on that offer.
