### ISSUE TITLE
GNU readline compatibility

### ISSUE THREAD

**Issue by IsaacKhor** [nushell/nushell#5912]
Is there a reason the default config isn't compatible with GNU readline?

The most notable example is `C-u`, in GNU readline that's "kill from cursor to beginning of line", but [here](https://github.com/nushell/nushell/blob/a0db4ce747fd2afdd772b97d0625ac0a1bd4355d/docs/sample_config/default_config.nu#L454-L460) it's "commands with description". `C-y` to yank also is so well established that "vars menu" doesn't make any sense.

~~I know nushell uses [rustyline](https://github.com/kkawakam/rustyline), but even there by default `C-u` and `C-y` has GNU readline compatible behaviour.~~ nushell uses `reedline`, not `rustyline`.

I didn't go through each keybind in detail, but having an option for readline-compatible behaviour would be nice.

**Comment by jntrnr** [comment]
Nushell uses [reedline](https://github.com/nushell/reedline)

There may be some user key combinations that are missing. It's pretty easy to add them. If you're seeing some missing, you should send a PR to the reedline repo.

**Comment by IsaacKhor** [comment]
> There may be some user key combinations that are missing. It's pretty easy to add them. If you're seeing some missing, you should send a PR to the reedline repo.

My question is more with *why* `C-u` and `C-y` deviate from GNU readline behaviour in favour of something else in the default config file here in nushell. I'll go through each key combination in detail later in GNU and propose a list.

**Comment by IsaacKhor** [comment]
The [default emacs](https://github.com/nushell/reedline/blob/13ff774bcca79409282ad6a7b6e0cf1d5dedb85d/src/edit_mode/emacs.rs#L15-L90) keybindings in `reedline` look fine to me. So it really is `nushell` overriding them; would the maintainers be amenable to a PR changing default keybindings to be GNU readline compatible?

**Comment by fdncred** [comment]
If you're talking about C-u and C-y then we'd probably accept a change as long as those keybindings for menus were remapped to something else that works on Windows/Linux/MacOS.

**Comment by jntrnr** [comment]
These both work now. Closing.
