### ISSUE TITLE
errexit or similar for exitting functions if a command fails

### ISSUE THREAD

**Issue by harrysarson** [nushell/nushell#5915]
### Related problem

I am trying to run a function like this

```
def err-exit-test [] {
    echo 1
    cat /file/does/not/exist
    echo $"I do not want this to run unless exit code is 0, was ($env.LAST_EXIT_CODE)"
}
```

and have it exit before the last line.

### Describe the solution you'd like

A setting similar to bash `set -e` to make the script exit if a command fails. See https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html.

### Describe alternatives you've considered

I can manually check `$env.LAST_EXIT_CODE` but it would be nice to have unhandled errors propagate by default instead of getting ignored.

### Additional context and details

What I am trying to do is something like

```
def build [] {
    rm -rf build
    mkdir ebuild
    cd build
    let version = "1.6.3"
    let url = $"https://github.com/user/repo/archive/refs/tags/($version).tar.gz"
    curl --silent --location ($url) | save ./repo.tgz
    (echo "8c1afa0a4d5f4909ae864a5d00381b963b4a179364ba591611ceb634c3c9eb99 repo.tgz") | sha256sum -c
    tar -xf repo.tgz --strip-components=1

    ./autogen.sh
    ./configure
    make
}
```

Of course this does not work! If sha256sum does not match the hash it will exit with code 1 but then the function will carry on building the library anyway.

Thanks!

**Comment by WindSoilder** [comment]
Maybe it's something similar to error mentioned in #5878 ?

**Comment by jntrnr** [comment]
This seems to be fixed in the latest main.

**Comment by harrysarson** [comment]
Thanks! I will be excited to upgrade :)
