### ISSUE TITLE
Suggest `get` when erroring on `(<pipeline>).field`

### ISSUE THREAD

**Issue by ErichDonGubler** [nushell/nushell#5924]
### Describe the bug

The diagnostic around `(<pipeline-1> | <pipeline-2>).field` is broken -- the suggested fix doesn't seem to be any different from the offending code.

### How to reproduce

1. Run `ps | where (echo $it.name | path parse).stem) == 'nvim'`. Observe that the diagnostic emitted is of the form:

```
  × Name not found
   ╭─[entry #22:1:1]
 1 │ ps | where (echo $it.name | path parse).stem) == 'nvim'
   ·                                         ──┬──
   ·                                           ╰── did you mean 'stem'?
   ╰────
```

...which does _not_ help a user understand the problem, or find a resolution!

### Expected behavior

The diagnostic offered should help the user to understand why this doesn't work, and ideally, offer a correct version of code to use. Alternatively, `nu` could also accept `<pipeline>.field` syntax.

Indicating that this can be resolved with the `get` command seems like a straightforward and correct suggestion for now:

```
  × Name not found
   ╭─[entry #22:1:1]
 1 │ ps | where (echo $it.name | path parse).stem) == 'nvim'
   ·                                         ──┬──
   ·                                           ╰── did you mean ' | get stem'?
   ╰────
```

### Screenshots

Problem repro in Windows Terminal:

![image](https://user-images.githubusercontent.com/658538/176966704-c3950da0-86d6-4957-80f1-50bd9daa4415.png)

A possible output of the proposed diagnostic's suggested fix in the same environment; shouldn't be anything surprising here:

![image](https://user-images.githubusercontent.com/658538/176966734-2c16ad97-ef35-4e1c-a5d2-cbda19119fa0.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.63.0                                          |
| branch             | erich/more-dep-upgrades-lol                     |
| commit_hash        | 06cf3fa5ad8c8b1d1351c81ccea59a1f8d588dc9        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)             |
| pkg_version        | 0.63.0                                          |
| build_time         | 2022-05-25 01:15:47 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
It looks like your syntax is wrong. You have too many `)`'s.

Try this: `ps | where (echo $it.name | path parse).stem == 'nvim'`. That works for me on the latest main.

**Comment by ErichDonGubler** [comment]
Ahhh, I see my error! 😳

I suppose this would turn my big report into a diagnostics suggestion, then?

**Comment by onthebridgetonowhere** [comment]
The error message should definitely more helpful than it is now :-D. 

Recently we got a `nu-check` command. I haven't tried it yet, so when I used it, it returns `true` with both the correct and the wrong input. Not sure what `true` means. 

I'd suggest to close this now and file an issue for better error support for this particular case.

**Comment by weirdan** [comment]
This now properly reports unbalanced parenthesis:
```console
$ ps | where (echo $it.name | path parse).stem) == 'nvim'
Error: nu::parser::unbalanced_delimiter

  × Unbalanced delimiter.
   ╭─[entry #9:1:45]
 1 │ ps | where (echo $it.name | path parse).stem) == 'nvim'
   ·                                             ┬
   ·                                             ╰── unbalanced ( and )
   ╰────
```
