### ISSUE TITLE
Output of nu script appears to be raw data

### ISSUE THREAD

**Issue by aikow** [nushell/nushell#5929]
### Related problem

I'm currently trying create a script to easily compare two deeply nested tables, with some parameterization (which is why an alias doesn't work). The script is supposed to return a dataframe, which I can then inspect further, select the columns I want and write it to a CSV file.

The main problem currently is that (at least my understanding) the output of the script is passed to nu as raw string, not a dataframe.

I'm currently running the file as an executable with a shebang (`#!/usr/bin/env nu`). I've tried running the script using the `nu script.nu` syntax, but that fails with an error that `nu` received an unexpected positional parameter.

An interesting side-note is that the `help nu` and `nu --help` differ a bit in their supposed functionality.

```sh
aikow@manjaro workspace/test〉nu --help                               
The nushell language and shell.

Usage:
  > nu {flags} (script file) ...(script args)

Flags:
  -h, --help
      Display this help message
  --stdin
      redirect the stdin
  -l, --login
      start as a login shell
  -i, --interactive
      start as an interactive shell
  -v, --version
      print the version
  -p, --perf
      start and print performance metrics during startup
  --testbin <String>
      run internal test binary
  -c, --commands <String>
      run the given commands and then exit
  --config <String>
      start with an alternate config file
  --env-config <String>
      start with an alternate environment config file
  --log-level <String>
      log level for performance logs
  -t, --threads <Int>
      threads to use for parallel commands
  -m, --table-mode <String>
      the table mode to use. rounded is default.

Parameters:
  (optional) script file <Filepath>: name of the optional script file to run
  ...script args <String>: parameters to the script file

Examples:
  Run a script
  > nu myfile.nu

  Run nushell interactively (as a shell or REPL)
  > nu

aikow@manjaro workspace/test〉help nu                                 
Completions for nu itself

Usage:
  > nu {flags}

Flags:
  -h, --help
      Display this help message
  --stdin
      redirect the stdin
  -l, --login
      start as a login shell
  -i, --interactive
      start as an interactive shell
  -v, --version
      print the version
  -p, --perf
      start and print performance metrics during startup
  --testbin <String>
      run internal test binary
  -c, --commands <String>
      run the given commands and then exit
  --config <String>
      start with an alternate config file
  --env-config <String>
      start with an alternate environment config file
  --log-level <String>
      log level for performance logs
  --threads <Int>
      threads to use for parallel commands
  -m, --table-mode <String>
      the table mode to use. rounded is default.


aikow@manjaro workspace/test〉                                        
```

### Describe the solution you'd like

It'd be nice to somehow pass the output of a nushell script as structured data into the next pipeline, rather than having it always passed as raw data.

**Comment by kubouch** [comment]
There was a broken external signature for `nu` in the default config that's now removed. Check if you have `extern nu` -- if yes, it's probably broken so try deleting it from your config.

**Comment by aikow** [comment]
Thanks for the quick response :) I found the broken extern in the config and removed it, but it doesn't fix the issue of nu passing the output of a script as raw data. I'm not sure what a better title should be, but the current title is a bit misleading...

**Comment by fdncred** [comment]
maybe if you show your script and an example csv with your command line parameter we can help. It's kind of hard to troubleshoot based on your description. also, can you paste the output of `version | transpose key value`?

**Comment by aikow** [comment]
Okay, I did some more testing and scanning of the documentation and found what I was looking for. Using a module instead of a script solves the problem.

### Example

```sh
# ./test-module.nu

export def test [] {
  [[key, value]; [a, 1], [b, 2], [c, 3]]
}
```

```sh
# ./test-script.nu

[[key, value]; [a, 1], [b, 2], [c, 3]]
```

Running the module outputs a table that other `nu` commands can interact with, so an actual table.

```sh
> use test-module.nu *
> test | select key
╭───┬─────╮
│ # │ key │
├───┼─────┤
│ 0 │ a   │
│ 1 │ b   │
│ 2 │ c   │
╰───┴─────╯
>
```

Running the script however, outputs raw data

```sh
> nu test-script.nu
╭───┬─────┬───────╮
│ # │ key │ value │
├───┼─────┼───────┤
│ 0 │ a   │     1 │
│ 1 │ b   │     2 │
│ 2 │ c   │     3 │
╰───┴─────┴───────╯
> nu test-script.nu | select key
> 
```

Which I'm assuming to mean that the script doesn't actually pass the output as structured data.

Using modules works, although I'm not entirely sure when using a script instead of a module would even make sense, unless you're writing to a file. I'm also not sure whether having scripts pass structured data is even possible. `source`, also does something very similar, although it's not as structure as using a module.

**Comment by matthewauld** [comment]
I was just coming here to leave the same question after trying to do exactly the same thing! It would be nice to be able to write a script that can be run from another shell (like bash) with the nu command, or run inside another nu script.

I know there are issues around ensuring what type being produced by a script and loading other code at runtime.

**Comment by fdncred** [comment]
I don't see how this could ever work as things are now. When you do `nu script.nu` it's launching another instance of nushell, running the script, and producing the output as text to show on the screen, then exits that additional shell. All the structured data information about the script and it's output existed in that shell that just exited, so it doesn't exist any longer.

The only way I could see this working is this.
1. It has to be ran from within nushell like `nu script.nu`, I'm not sure if we can intercept shebang nushell scripts.
2. When running a script like `nu blah.nu`, nushell has to be changed to be smart enough to not launch another nushell instance but to do something similar to `use` or `source`.
3. Then when the script runs all the structured information about the script is maintained in the parent nushell.

If you want to do something like running a nu script from a bash shell with a shebang and then consuming the output within the bash script again, you need to write your nu script in such a way that permits this by using a serialization format such as json.  So, if your nu script has `| to json` at the very end, then the output will be json, and the external shell like bash could perhaps use something to deal with that.

**Comment by aikow** [comment]
Yes, the linked issue does a much better job of describing what my expected behavior was, feel free to close this ticket.
