### ISSUE TITLE
Plugins to provide --encoding to allow detection of encoding format

### ISSUE THREAD

**Issue by logankaser** [nushell/nushell#5944]
### Related problem

It would be nice to not need to know the details of the format the programmer of a plugin used when registering a plugin as a user.

### Describe the solution you'd like

Plugins could be required to provide a --encoding that prints a string "capnp" or "json" to inform nushell about which encoding they want.

### Describe alternatives you've considered

Alternatively, this could be used as a fallback if the user does not pass --encoding to register

**Comment by Benjamin-L** [comment]
Another alternative might be to have the encoding specified by the plugin in-band. For example, when a plugin starts, it could output a single line with the expected encoding.

**Comment by logankaser** [comment]
> Another alternative might be to have the encoding specified by the plugin in-band. For example, when a plugin starts, it could output a single line with the expected encoding.

I thought about that, but I think it would be nice to maintain compatibility with existing plugins

**Comment by Benjamin-L** [comment]
Longer-term, we probably want some kind of version negotiation for the plugin protocol anyway. Easier to introduce the backwards-incompatible change once early on rather than later.
