### ISSUE TITLE
Env var parsing into string fails

### ISSUE THREAD

**Issue by Noxdor** [nushell/nushell#5947]
### Describe the bug

This might be a bug, this might be me being new to Nushell and -script. I am trying to parse environment variables into a string of the form `--env VAR=VALUE` to then pass it to `wasmtime`.

My script looks like this:

```nu
#!/bin/nu
let wasm_vars = (env  | where name =~ ALACRITTY
                      | each { |it| echo $"--env ($it.name)=($it.value)" })

let x = (^echo $wasm_vars)
echo $"wasmtime run ($x) target/wasm32-wasi/debug/wasm_test.wasm"
wasmtime run $"($x)" target/wasm32-wasi/debug/wasm_test.wasm
```

This results in a command like this: `wasmtime run --env ALACRITTY_LOG=/tmp/Alacritty-54804.log --env ALACRITTY_SOCKET=/run/user/1000/Alacritty-:1-54804.sock` which fails with the error

```
error: Found argument '--env ALACRITTY_LOG' which wasn't expected, or isn't valid in this context
Did you mean '--env'?
```

Instead, if I run the command by hand, the call to `wasmtime` is successful. I am thinking, this is a problem with my parsing or with nushell's parsing in general. So either this is a bug, or maybe someone can tell me what I am doing wrong. 

### How to reproduce

1. Install `wasmtime`
2. Copy my Nuscript
3. Try to run the Nuscript (maybe with different env variables, if you're not running `alacritty`)
4. See it fail
5. Try to run the command manually
6. See it succeed

### Expected behavior

Nushell parses the env vars correctly and lets me parse them to `wasmtime`.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.64.0                                          |
| branch             | main                                            |
| commit_hash        | d1c719a8cc52b1cb3f60810daa8bf28e69eb6617        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.61.0 (Arch Linux rust 1:1.61.0-1)       |
| cargo_version      | cargo 1.61.0                                    |
| pkg_version        | 0.64.0                                          |
| build_time         | 2022-06-15 07:31:53 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by kubouch** [comment]
Seems like the problem is that you're sending the whole `--env ALACRITTY_LOG=... --env ...` as one huge argument. If you want to send multiple args to an external, use a list, something like:
```
let wasm_vars = (env  | where name =~ ALACRITTY
                      | each { |it|  [ --env $"($it.name)=($it.value)" ] }
                      | flatten)

wasmtime run $x target/wasm32-wasi/debug/wasm_test.wasm
```

Before, you ran
```
wasmtime run  "--env ALACRITTY_LOG=/tmp/Alacritty-54804.log --env ALACRITTY_SOCKET=/run/user/1000/Alacritty-:1-54804.sock" target/wasm32-wasi/debug/wasm_test.wasm
```
but you need to run
```
wasmtime run  [ "--env" "ALACRITTY_LOG=/tmp/Alacritty-54804.log" "--env" "ALACRITTY_SOCKET=/run/user/1000/Alacritty-:1-54804.sock" ] target/wasm32-wasi/debug/wasm_test.wasm
```

**Comment by Noxdor** [comment]
Thanks @kubouch, that worked! Awesome, I didn't know that nushell unwraps the list automatically when calling a non-nu binary.

**Comment by kubouch** [comment]
Yeah, it's a relatively new feature and we should document it better.
