### ISSUE TITLE
Piping large outputs seems extremely slow or doesn't work at all.  

### ISSUE THREAD

**Issue by empath75** [nushell/nushell#595]
`kubectl get pods -o yaml | from-yaml` 
is extremely slow -- on the order of 30 seconds to a minute or so to spit out any output, and it only captures part of it.   

`kubectl get pods -o json | from-json`

Never outputs anything at all.  If I hit control-c, I get:

```
- shell:1:28
1 |  kubectl get pods -o json | from-json
  |                             ^^^^^^^^^ input cannot be parsed as JSON
- shell:1:1
1 |  kubectl get pods -o json | from-json
  |  ------- value originates from here
```

Doesn't work piping to jq in nushell either.   Seems like piping might hit a buffer or something and then stop?

```
~/nushell>  kubectl get pods -o json | jq
^Cparse error: Unfinished JSON term at EOF at line 1538, column 20
/Users/uye976/Downloads/nushell>  kubectl get pods -o json | jq
^Cparse error: Unfinished JSON term at EOF at line 1538, column 20
```

Works in less than a second piping to jq in bash.  
the output of that command is 23,000 lines of json, fwiw.  
```
130 ❯ kubectl get pods -o json | wc -l
   23207
```

**Comment by wycats** [comment]
Can you paste the JSON output you're trying to pipe in? Or something synthetic if there's sensitive info in there?

**Comment by empath75** [comment]
`python -c "print([i for i in range(10500)])" | from-json`

works
`python -c "print([i for i in range(11000)])" | from-json`
hangs.


i don't think it's the parser, i think the pipe just dies at a certain point..

even ``python -c "print([i for i in range(11000)])" | head`
hangs

if i hit control-c, it ends here:
 10948, 10

**Comment by jonathandturner** [comment]
@empath75 - that repro is very helpful. I'm using it now to see if I can track down where the limit is happening

**Comment by jonathandturner** [comment]
With #664, I believe I have fixed the underlying cause of the pauses/freezes. If you can, please give a recent checkout from master a try to see if it fixes the issue.

I'll close the issue for now, but please reopen if if you can still repro with the more recent nu.
