### ISSUE TITLE
no indication when process exits with a signal

### ISSUE THREAD

**Issue by toffaletti** [nushell/nushell#5960]
### Describe the bug

I have a process that crashes with SIGTRAP on macOS. Running the executable under nushell gives no indication the process exited because of a fatal signal.

Other shells have more to say when this occurs.
`fish`: terminated by signal SIGTRAP (Trace or breakpoint trap)
`bash`: Trace/BPT trap: 5
`zsh`: zsh: trace trap

### How to reproduce

1. Run a command that exits with SIGTRAP (such as a binary that is not properly code signed on macOS)

### Expected behavior

I expected nushell to give some indication the process exited with a signal.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | macos-x86_64                                    |
| build_target       | x86_64-apple-darwin                             |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | stable-x86_64-apple-darwin                      |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)             |
| pkg_version        | 0.65.0                                          |
| build_time         | 2022-07-05 14:34:47 -07:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by rgwood** [comment]
Thanks for the detailed issue - it's good to know how other shells handle this.

If anyone wants to work on this, I think it would be relatively straightforward to add some code around here: https://github.com/nushell/nushell/blob/5d00ecef562252414a0653538dc35414acf04d9a/crates/nu-command/src/system/run_external.rs#L321

I personally don't have a good understanding of which fatal signals we should log (maybe all of them?).

**Comment by toffaletti** [comment]
This might be helpful: https://github.com/fish-shell/fish-shell/commit/f5be301a2f3eb568fcb712c110aa116452573c73

**Comment by rgwood** [comment]
I was hoping to implement this today, but it's more complex than I thought - the code I linked to before doesn't quite work as expected, and I think we need to overhaul how we pass exit codes/statuses around.

**Comment by rgwood** [comment]
Nice, thanks. I've reverted #5908.

> I tried to add an exit status ListStream property to PipelineData::ExternalStream similar to how exit_code is implemented

I think this is on the right track but I'm not 100% certain what the type of a new `exit_status` property should be. I guess we have 2 options:

1. Keep using `ListStream`, coerce exit status to a `Value::Int` using `into_raw` on Unix and `code()` on Windows
2. Pass around an actual `ExitStatus` struct (or some lazy wrapper around it)

I'll bring this up in the Nu Discord (#design-discussion channel), maybe someone else will have a strong opinion.

**Comment by rgwood** [comment]
(not saying you should wait for an answer btw - if you have an opinion about which of those options to choose and the time to put together a PR, feel free)

**Comment by rgwood** [comment]
A suggestion from @kubouch in Discord:

> We could make it a record and store the record into the `$env.LAST_EXIT_CODE` instead of just the integer. To get the integer code, you'd call `$env.LAST_EXIT_CODE.code` but you could query other info, like `$env.LAST_EXIT_CODE.signal` or whatever. (We should probably rename it to `LAST_EXIT_STATUS` at that point.)

**Comment by flying-sheep** [comment]
A good programming language will throw an error by default if it encounters one and only swallow them if explicitly told (in our case by a `do -i { ... }`). `$env.LAST_EXIT_CODE` is a misfeature, external commands exiting with an exit code != 0 should have a nushell error derived from them.

**Comment by kubouch** [comment]
Non-zero exit code, unfortunately, is not a guarantee a program encountered an error. For example ImageMagick's `compare` will return `1` on success, `2` on error. There is no reliable way to detect errors in an external program because it ultimately depends on the developer of the program how they decide what each error code means. 

We used to have a config option that would throw an error on a non-error exit code, but I think it was removed. I used it for a while but in practice, it was too annoying to have a program throw errors even though it completed successfully.

**Comment by flying-sheep** [comment]
Pretend I said EXIT_SUCCESS, not 0 (the two are equal on POSIXy systems though). ImageMagick’s will return with EXIT_SUCCESS when the images are similar, with EXIT_FAILURE (1 on POSIX) if they’re different and 2 on error.

That’s bad design and using `complete` we give users a way to wrap badly designed external commands like this:

```nushell
def compare [
  ...options  # too bad we can’t express this yet
  image: string
  reconstruct: string
  difference: string = 'null'
] {
  let ret = (/usr/bin/compare ([$options, $image, $reconstruct, $difference] | flatten) | complete)
  if $ret.exit_code in [0, 1] {
    $ret.exit_code == 0
  } else {
    error make { msg: $ret.stderr }
  }
}
```

But the default should be to assume sane behavior and wrap that in a smart way.
