### ISSUE TITLE
nu_plugin_gstat plugin not working with 0.65

### ISSUE THREAD

**Issue by pedoc** [nushell/nushell#5964]
### Describe the bug

```
Error:
  × Signature deserialization error
   ╭─[C:\Users\pedoc\AppData\Roaming\nushell\plugin.nu:1:1]
 1 │ register C:\Users\pedoc\.cargo\bin\nu_plugin_gstat.exe -e json  {
   · ────┬───
   ·     ╰── unable to deserialize signature: missing field `input_type` at line 33 column 1
 2 │   "name": "gstat",
   ╰────
```

### How to reproduce

1. update code to latest
2. cargo build --release --workspace --features=extra
3. put  nu.exe and other plugin exe into ``C:\Users\%USER%\.cargo\bin``
4. run nu.exe

### Expected behavior

nu_plugin_gstat plugin loads normally

### Screenshots

![image](https://user-images.githubusercontent.com/6604230/177459231-c7409a74-1f0b-4d89-af89-c66f1d56472d.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             |                                                 |
| commit_hash        | 390d06d4e7383d9fee814713bda8d1aaca858c5a        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)             |
| pkg_version        | 0.65.0                                          |
| build_time         | 2022-07-06 10:53:33 +08:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by hustcer** [comment]
Please re-register the plugin: `register  -e json C:\Users\pedoc\.cargo\bin\nu_plugin_gstat.exe`

**Comment by pedoc** [comment]
> Please re-register the plugin: `register -e json C:\Users\pedoc\.cargo\bin\nu_plugin_gstat.exe`

Yes, I found that re-registering the plugin solves the problem, but there are several new problems
1. When registering a single plugin (even re-registering) will cause all plugin registrations to be lost, so multiple commands must be executed to register all plugins
2. When upgrading the nu version, if there are major changes in the plugin, can it be automatically re-registered or add a mechanism to automatically discover plugins

Thank you for your great work

**Comment by fdncred** [comment]
We used to automatically discover and re-register plugins on every nushell launch. That made nushell startup slow which is why we switched to the method we use now. The only time you have to re-register plugins is if the signature changes, which it did between 0.64 and 0.65.

I was pretty sure that re-registering a plugin would only update that current plugin and leave the rest of the registrations alone, but maybe that changed.
