### ISSUE TITLE
Access nested columns with subexpressions

### ISSUE THREAD

**Issue by aikow** [nushell/nushell#5966]
### Related problem

I'm trying to get a nested column inside a table with a subexpression.

```nu
> let a = [[key, value]; [a, 1], [b, 2]]
> let b = [[key, value]; [a, $a], [b, $a]]
> $b | select value.value
╭───┬────────────────╮
│ # │  value_value   │
├───┼────────────────┤
│ 0 │ [list 2 items] │
│ 1 │ [list 2 items] │
╰───┴────────────────╯
> $b | select value.(echo "value")
EError: nu::parser::parse_mismatch (link)

   × Parse mismatch during operation.
    ╭─[entry #45:1:1]
  1 │ $b | select value.("value")
    ·             ───────┬───────
    ·                    ╰── expected string
    ╰────
> $b | select $"value.(echo | "key")"
EError: nu::shell::name_not_found (link)

   × Name not found
    ╭─[entry #48:1:1]
  1 │ $b | select $"value.(echo | "key")"
    ·             ───────────┬───────────
    ·                        ╰── did you mean 'value'?
    ╰────
```

### Describe the solution you'd like

I'm not sure what the best way to achieve this is, but the first version I tried above seemed the most intuitive (`select value.(value)`).

### Describe alternatives you've considered

My current workaround is first doing two separate selects:

```
> $b | get value | get (echo "value")
╭───┬────────────────╮
│ 0 │ [list 2 items] │
│ 1 │ [list 2 items] │
╰───┴────────────────╯
```

**Comment by fdncred** [comment]
I'm trying to follow along. Maybe this explanation isn't exactly what you're looking for but it's a good test-bed to review.

```
> $b
╭───┬─────┬────────────────╮
│ # │ key │     value      │
├───┼─────┼────────────────┤
│ 0 │ a   │ [table 2 rows] │
│ 1 │ b   │ [table 2 rows] │
├───┼─────┼────────────────┤
│ # │ key │     value      │
╰───┴─────┴────────────────╯
```
```
> let v = "value"
```
```
> $b | get $v
╭───┬────────────────╮
│ 0 │ [table 2 rows] │
│ 1 │ [table 2 rows] │
╰───┴────────────────╯
```
```
> $b | get $v | get $v
╭───┬────────────────╮
│ 0 │ [list 2 items] │
│ 1 │ [list 2 items] │
╰───┴────────────────╯
```
```
> $b | get $v | get $v | get 0
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 2 │
╰───┴───╯
```
One thing that's important to remember is that `select` tries to maintain the structure. So, if you `select` on a table you should get a table back. However, `get` takes the data out of the structure. So, if you `get` on a table, you could get back a table, or a record, or a list, etc, depending on how the data is held.

You can test this with something like this
```
> $b | describe 
table<key: string, value: table<key: string, value: int>>
> $b | select $v | describe 
table<key: string, value: int>>
> $b | select $v | select $v | describe
table<value: table<key: string, value: int>>
> $b | get $v | describe
list<table<key: string, value: int>>
> $b | get $v | get $v | describe 
list<list<int>>
> $b | get $v | get $v | get 0 | describe
list<int>
```
or maybe more easily understood with `ls`
```
> ls | describe
table<name: string, type: string, size: filesize, modified: date>
> ls | select name | describe
table<name: string>
> ls | get name | describe
list<string>
```

**Comment by aikow** [comment]
Thanks for the detailed answer and suggestions 😀.

I guess I should have made my actual problem/feature a bit more explicit in my original issue. I spent so much trying think of a good example demonstrating the problem, and trying to write a good feature request, that I forgot what I actually wanted 😂 .

I did spend some time reading up and playing around with `get` and `select`. My main wish was to be able to get a nested column in a *single* `get` or `select` clause. Whether it's a `get` or a `select` or any other command that can used column paths, that shouldn't matter.

I'm currently doing multiple `get` and `select` commands, but that is a bit tedious when you have to `flatten` data. My current use case is trying to take a relatively deeply nested JSON structure, and present some of the deep information along with some of high level information.

For example, I want to take something like

```json
{
  "name": "exp1",
  "deep": {
    "nested": {
      "object": {
        "key1": "value1",
        "key2": "value2"
      }
    }
  }
}
```

and create a flat table that looks like this

```json
{
  "name": "exp1",
  "key1": "value1"
}
```

And ideally, I would like to do so with something akin to 

```nu
> open data.json | from json | get name deep.nested.object.key1
```

Now the above command works, it just doesn't work if I try to dynamically replace one of the columns in the path with a subexpression like so

```nu
> let key = "nested"
> open data.json | from json | get name deep.($key).object.key1
```

Sorry for the confusion, and I hope I was able to clear up what exactly I am looking for :).

**Comment by fdncred** [comment]
ok. You can do something like this
```
> let a = ( ... your example json ... )
> { name: ($a.name) key1: ($a.deep.nested.object.key1) } 
╭──────┬────────╮
│ name │ exp1   │
│ key1 │ value1 │
╰──────┴────────╯
```
To do your last statement you may have to break it up into a few separate statements like:
```
> let b = ($a | get name)
> let c = ($a | get deep | get $key | get object.key1)
> { name: $b key1: $c }
╭──────┬────────╮
│ name │ exp1   │
│ key1 │ value1 │
╰──────┴────────╯
```

**Comment by aikow** [comment]
Thank you for your last comment!

I'm so used to bash and zsh having garbage variables that only store drinks that I keep forgetting that nushell can actually store useful variables.

Not trying to accomplish it all in a single continuous pipe makes the problem not quite as frustrating, although I do think allowing that sort of expansion would be cool. I dont think that syntax would cause any confusion either since you rately have parentheses in columns or table keys

**Comment by sholderbach** [comment]
The documentation is not yet super obvious about it but we have the solution to get you there
At the bottom of the [page in the language reference](https://www.nushell.sh/lang-guide/chapters/types/basic_types/cellpath.html#casts) after somewhat boring stuff under the non-descript title casts.

And the main book is not very obvious about with cell paths not appearing in the [overview table of types](https://www.nushell.sh/book/types_of_data.html#types-at-a-glance) and the [basic section](https://www.nushell.sh/book/types_of_data.html#cell-paths) not showing a free standing cell paths or cellpaths on variables but only indexing of directly defined table expressions
