### ISSUE TITLE
git checkout file from commit failed

### ISSUE THREAD

**Issue by lafirest** [nushell/nushell#5968]
### Describe the bug

checkout a single file from a specific commit will throw an error

### How to reproduce

1. git checkout COMMIT FILE

### Expected behavior

work

### Screenshots

<img width="904" alt="image" src="https://user-images.githubusercontent.com/22971499/177531492-fd2cdf59-2358-4ee4-802c-7e597b8e9d45.png">

**Comment by fdncred** [comment]
What happens if you start this git command with `^git checkout <the rest of the params>`? 

I'm guessing that this problem is because the current git custom completions don't support the syntax you're using. My work-around has been to add a caret at the beginning to get around this issue.

**Comment by Kangaxx-0** [comment]
I believe the root cause of this is due to `nu` recognize `git checkout` as external command. If you check nu config by `config nu`, you will probably see lines of code like  

```
export extern "git checkout"
.....
```
As another workaround, you could also remove the `extern` and try it again

**Comment by lafirest** [comment]
> I believe the root cause of this is due to `nu` recognize `git checkout` as external command. If you check nu config by `config nu`, you will probably see lines of code like
> 
> ```
> export extern "git checkout"
> .....
> ```
> 
> As another workaround, you could also remove the `extern` and try it again

This work, thanks
