### ISSUE TITLE
Main branch can't be build by rustc 1.60.0

### ISSUE THREAD

**Issue by zhiburt** [nushell/nushell#5973]
### Describe the bug

`error[E0658]: use of unstable library feature 'bool_to_option'`

I guess you need to update a rust version requirement in `Cargo.toml `

https://github.com/nushell/nushell/blob/8abf28093ae6fd45e322a519c60af7fb734c786d/Cargo.toml#L13

### How to reproduce

..

### Expected behavior

....

**Comment by WindSoilder** [comment]
Sorry, I think it's introduces from #5974 , the feature is landed in rust 1.62, which is the latest version.

I think it's ok to make it compatible with `1.60`, so I create a relative pr to fix it
