### ISSUE TITLE
ls color is unaffected by Windows Terminal color scheme.

### ISSUE THREAD

**Issue by Jason5Lee** [nushell/nushell#5976]
### Describe the bug

The text color of ls is to bright so I tried to change it by using a different Windows Terminal color scheme, but it seems that it has no effect.

### How to reproduce

1. Add the following color scheme in Windows Terminal.

```json
        {
            "background": "#FFFFFF",
            "black": "#000000",
            "blue": "#3971ED",
            "brightBlack": "#B4B7B4",
            "brightBlue": "#3971ED",
            "brightCyan": "#3971ED",
            "brightGreen": "#198844",
            "brightPurple": "#A36AC7",
            "brightRed": "#CC342B",
            "brightWhite": "#1D1F21",
            "brightYellow": "#FBA922",
            "cursorColor": "#373B41",
            "cyan": "#3971ED",
            "foreground": "#373B41",
            "green": "#198844",
            "name": "Google Light",
            "purple": "#A36AC7",
            "red": "#CC342B",
            "selectionBackground": "#373B41",
            "white": "#373B41",
            "yellow": "#FBA922"
        }
```

2. Use this color scheme, then run ls.

### Expected behavior

The text color reflects the color scheme.

### Screenshots

![brighter](https://user-images.githubusercontent.com/25118271/177705127-52421f7a-e274-4db5-a9c5-4706e2acc67d.png)

You can see the ls text color is brighter than ALL text color config entries.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.62.0                                          |
| branch             |                                                 |
| tag                |                                                 |
| short_commit       | da104050                                        |
| commit_hash        | da104050e6dcf7fbffd41bfd4bdeae1285b7a48c        |
| commit_date        | 2022-05-03 21:50:33 +00:00                      |
| build_os           | linux-x86_64                                    |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.60.0 (d1fd9fe 2022-03-01)               |
| pkg_version        | 0.62.0                                          |
| build_time         | 2022-05-03 22:01:03 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

Windows terminal version: 1.14.1861.0

**Comment by Jason5Lee** [comment]
Also exists in

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             |                                                 |
| commit_hash        | 390d06d4e7383d9fee814713bda8d1aaca858c5a        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-musl                       |
| rust_version       | rustc 1.62.0 (a8314ef7d 2022-06-27)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.62.0 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.65.0                                          |
| build_time         | 2022-07-05 17:27:56 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
Terminal themes can definitely influence nushell colors but nushell has no way to understand what terminal it is running under nor what the colors are. The colors you specifically show are controlled by the `LS_COLORS` environment variable or lack thereof. You are welcome to change these colors by setting a new `LS_COLORS` env var or not using it at all with `use_ls_colors: false` in your config. You can also change many color aspects of nushell via the config.nu settings. You can read more about it here https://www.nushell.sh/book/coloring_and_theming.html.

**Comment by fdncred** [comment]
You might put try `vivid`. For a while I was doing this in my env.nu `let-env LS_COLORS = (vivid generate molokai | str trim)`
