### ISSUE TITLE
Unexpected Tab Completion Replacement

### ISSUE THREAD

**Issue by lukexor** [nushell/nushell#5984]
### Describe the bug

I couldn't find any existing issues highlighting this, but I found this behavior odd and unexpected with how some aliases expand to a custom command when <TAB> is pressed in some cases.

### How to reproduce

```
alias cd = fnmcd

def-env fnmcd [path: string] {
  let-env PWD = ($path | path expand)
  # Code here to call `fnm` which is a node package manager to read .npmrc and switches node version
  ^cd $env.PWD
}
```

Then

```
mkdir files
cd f<TAB> # Expands to `cd files`
cd fi<TAB> # Expands to `fnmcd`
cd fil<TAB> # Expands to `cd files`
cd file<TAB> # Expands to `cd files`
```

I tried reproducing with `alias c = fnmcd` and get the following:

```
c f<TAB> # Expands to `cd files`
c fi<TAB> # Expands to `cd files`
c fil<TAB> # Expands to `fnmcd`
c file<TAB> # Expands to `cd files`
```

And with  `alias cdf = fnmcd` and get the following:

```
cdf f<TAB> # Expands to `fnmcd`
cdf fi<TAB> # Expands to `cd files`
cdf fil<TAB> # Expands to `cd files`
cdf file<TAB> # Expands to `cd files`
```

### Expected behavior

Expected to have all <TAB> attempts expand to `cd files`

### Configuration

```
| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.65.0                              |
| branch             | main                                |
| commit_hash        |                                     |
| build_os           | macos-x86_64                        |
| build_target       | x86_64-apple-darwin                 |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18) |
| rust_channel       | stable-x86_64-apple-darwin          |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29) |
| pkg_version        | 0.65.0                              |
| build_time         | 2022-07-05 16:30:34 -07:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |
```

### Additional context

It seems like there is some length checking going on depending on the length of the command before <TAB> combined with the length of the custom command. In call cases the `alias` + space length equals the length of `fnmcd`

**Comment by kubouch** [comment]
How about if you use `path: path` instead of `path: string` for the parameter?

But yeah, the completions currently do not work correctly in many cases, we need to look into them.

**Comment by lukexor** [comment]
That does indeed fix it! Thanks!

**Comment by kubouch** [comment]
OK, I'll close it but please reopen or file another issue if you notice more bugs with completions.
