### ISSUE TITLE
Couldn't fit table into <n> columns

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#5991]
### Describe the bug

I got this error message when trying to run `env`:
```
Couldn't fit table into 254 columns!
```

Running full screen on a widescreen 1920x1080 monitor.

### How to reproduce

1. `env`

### Expected behavior

Should display the table somehow. If a field is too large, it can be wrapped or abbreviated with `...`. This error message is not very helpful or actionable.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.1                                          |
| branch             | main                                            |
| commit_hash        | eac5f62959c99a6ce3576d839f7f9b8a581d8486        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.0 (a8314ef7d 2022-06-27)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.62.0 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.65.1                                          |
| build_time         | 2022-07-07 20:10:14 +03:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | gstat                                           |

**Comment by fdncred** [comment]
I'm not really sure how to reproduce it. I run `env` and it works fine. Then I run `env | transpose` and columns are truncated with `...`.

Looks like another fun one @zhiburt.

**Comment by zhiburt** [comment]
Interesting;

Could you @kubouch paste your `$env` here?

**Comment by zhiburt** [comment]
No I can't .. :(

**Comment by zhiburt** [comment]
Technically it could happen because you're using `str::chars().len()` but the check uses `unicode_width` and we have a mismatch in numbers because of it.

Like for the same string I'm testing in first case length is 13 in second is 21.
Do you @kubouch  use some interesting unicode symbols?

I think it's the cause but I can't quite catch it....

I mean it's the issue in any way but maybe there's something else.

**Comment by zhiburt** [comment]
Hmmmm but you do both....

Interesting;
Then it maybe somewhere in wrap logic.
But I can't believe it.

Was there any accident with not wrapped correctly table before?

**Comment by zhiburt** [comment]
And what's your `table_mode` @kubouch ?

**Comment by zhiburt** [comment]
I caught it; :100: %

```
Couldn't fit table into 59 columns!
```

length of this is `60`

```
╰────┴────────────┴────────────┴─────────────┴─────────────╯
```

To reproduce.

```
export SOME_BI2="Ｈｅｌｌｏ, ｗｏ ｒｌｄＨ\nｅｌｌｏ, ｗｏ ｒｌｄＨｅｌｌｏ, ｗｏ\n ｒｌｄＨｅｌｌｏ, ｗｏCCC ｒｌｄＨｅｌｌｏ, ｗｏ ｒｌｄＨｅ\nｌｌｏ,  ｗｏ ｒｌｄＨｅｌｌｏ, ｗｏ ｒ\nｌｄＨｅｌｌｏ, ｗｏ ｒｌｄ Ｈｅｌｌｏ, ｗｏ ｒｌｄＨｅｌｌｏ, ｗｏ ｒｌｄＨｅｌｌｏ, ｗｏ ｒｌｄ"
export SOME_BI="Ｈｅｌｌｏ, ｗｏ  ｒｌｄＨｅｌｌｏ, ｗｏ ｒｌｄＨｅｌｌｏ, ｗｏ ｒｌｄＨｅｌｌｏ, ｗｏ ｒｌｄＨｅｌｌｏ, ｗｏ ｒｌｄＨｅｌｌｏ, ｗｏ ｒｌ ｄＨｅｌｌｏ, ｗｏ ｒｌｄＨｅｌｌｏ, ｗｏ ｒｌｄＨｅｌｌｏ, ｗｏ ｒｌｄＨｅｌｌｏ, ｗｏ ｒｌｄＨｅｌｌｏ, ｗｏ ｒｌｄ"
export SOME_BIGGGG="VOF NGS rådata og behandling.docx"
```

So it depends on your point of view either wrap doesn't work.
Or you provide a too small terminal_width value.

I would say second.
Like it's it's smaller on 1 point.

It's the case on original `nu-table` as well.

I guess we must reopen it @fdncred

**Comment by zhiburt** [comment]
To clarify;

There's enough space on terminal for 60 chars;
That's why this issue was covered up.

So essentially there's 2 issues;
 1. wrap returns wrong columns (60 chars when needed 59).
 2. terminal_width is 59 when 60 is available.
 
 PS: about 1.
 I didn't investigate it thoroughly to state that it's a wrap;
 it could be that `nu_table` and `tabled` print logic falls to the same issue.
 But it's unlikely.

**Comment by kubouch** [comment]
Interestingly, I can't reproduce it anymore :laughing: . I'm not sure what happened but it was 100% happening.

**Comment by fdncred** [comment]
@zhiburt can we make wrap and terminal_width be consistent somehow?

**Comment by zhiburt** [comment]
About wrap.
It's kind of hard to fix yet;

I mean I see it does quite a list of assumptions;
Like I don't see how it accounts padding?
And these constants ...
Like why `3` means separators?
And why we count it even if the theme doesn't use them....

Meaning investigation of it will take time.

**Comment by fdncred** [comment]
@zhiburt My initial reason for wanting to move to tabled was nu-table, wrap, et. al. were very hard to understand and troubleshoot.

> Like why 3 means separators?

can you point me to the line of code. not sure I know but I can look.

> (My bet there was no such themes before ...

You may be right.

**Comment by zhiburt** [comment]
> @zhiburt My initial reason for wanting to move to tabled was nu-table, wrap, et. al. were very hard to understand and troubleshoot.

Yes it could be great to move this logic out.

But we have discussed this already and you wanted to keep the original logic of nu_table.
Remember it?

I actually can try 1 thing in this regard maybe tommorow.

**Comment by fdncred** [comment]
Well, actually I wanted to keep the output the same without all the convoluted hard to understand code. I'd be happy to replace that code with some tabled-thing but we do kind of like how the nu-table's output looks.
