### ISSUE TITLE
Why is Chocolatey repo behind?

### ISSUE THREAD

**Issue by frederikhors** [nushell/nushell#5995]
### Related problem

Chocolatey repo is always behind the latest release, why?

### Describe the solution you'd like

I would like to automagically update it on each release.

**Comment by fdncred** [comment]
Not sure. We don't create packages for package managers. Those are done by the package manager volunteers.

If you want it automatically updated please submit a PR to do it and we'll look at it.

**Comment by hustcer** [comment]
@frederikhors BTW, we will update `winget` package for each release, you can use `winget` to install or update it on Windows

**Comment by rgwood** [comment]
Closing as the Chocolatey package is not maintained by us. FWIW Chocolatey seems to have updated to the most recent Nu version (v0.72) very quickly.
