### ISSUE TITLE
Improvements to 'open'

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#60]
Open/from/to for each file type should be registered in a central place so that in the future plugins have access to the registry.

**Comment by jonathandturner** [comment]
This is done via the plugin's name

**Comment by jonathandturner** [comment]
Blocked on #180

**Comment by Vurich** [comment]
It would be great if `open some-dir` converted that directory to a table, so `open . | tree` did what you'd expect. Unfortunately, this would almost certainly require tables to be made lazy so as to not immediately use up all your memory so it might be hard to implement.

**Comment by jonathandturner** [comment]
@Vurich you should file this as a separate idea. There's been some thinking around making tables last and it would help start up discussions again. 

Closing this issue as the original issue is now fixed.
