### ISSUE TITLE
Command expansions based on the history like `!!`

### ISSUE THREAD

**Issue by meltinglava** [nushell/nushell#601]
Feature request:
Implement bang bang: `sudo !!`

**Comment by jonathandturner** [comment]
Can you talk a bit more about this feature and how it will work with nu?

**Comment by meltinglava** [comment]
https://stackoverflow.com/questions/15137461/what-is-sudo-bang-bang

Bang bang is a placeholder for the last command typed. Mostly used to prepend sudo in front of the last command.

**Comment by wycats** [comment]
What if we made `sudo` with no arguments have this behavior?

**Comment by meltinglava** [comment]
> What if we made `sudo` with no arguments have this behavior?

Would say that we do bought. Bang bang has been around for a long time.

Although if we add strict aliases (aka aliases that cant be added on to) so you can make an strict alias `sudo` be equal to `sudo !!` If that is a consideration we would only have to implement bang bang. Also bang bang have more than a few use cases where you would not use sudo.

Regardless i say its not an alternative, more an addition.

**Comment by wycats** [comment]
Are there common use-cases for `!!` other than "whoops! forgot sudo!"?

**Comment by meltinglava** [comment]
> Are there common use-cases for `!!` other than "whoops! forgot sudo!"?

Well its just a placeholder for the last command typed. We are humans and make mistakes.

I just found it strange working in a linux shell that does not have the option. bash and zsh have them by default, and fish has an extention for it.

**Comment by zcdunn** [comment]
`!!` is useful for jumping back into an editor or ssh session when I've exited before finishing something. And `!!` is only one of the standard history commands that standard shells have. There are some other useful commands. `!v` runs the last command that starts with _v_. So i might have a session like this:
```
vim -O multiple source files # opens the listed files in vertical splits, side by side
# Do some editing and exit vim
mix build # or `make` or `cargo build`
!v # to reopen vim with the same files and same splits
```
I use this one all the time. There are a few more commands that are explained here: http://craig-russell.co.uk/2011/09/28/bang-bang-command-recall-in-linux.html

I reach for the parameters fetching and substitution regularly.

**Comment by corbinu** [comment]
Just started using nushell a few days ago as my primary driver after playing with it for a few months. I have run into this a couple times. I am fine if the name changes could even be like "lastline" or something but ran into it with sudo and rm when I forgot --recurse

**Comment by bltavares** [comment]
I would like to share some of the experience with bash and using nushell all time recently.

I also often rely much on `!$` due to muscle memory to access the last argument of the last command, such as:

```
cp folder/wrong/file.so ~/repos/my-build/vendor
# Woops, wrong file
cp folder/correct/file.so !$
```

```
git clone git@github.com:nushell/nushell /opt/nushell
cd !$
```

I would love to have some type of shortcut similar to how zsh and bash have, but with a more memorable alias that would fit the nushell philosophy.

**Comment by fdncred** [comment]
Totally agree. I'd love to have all the ! commands implemented in NuShell. The ones I've used most are !!, !$, and !<history_index>. Although, this may be a rustyline thing. Not sure.

https://www.redhat.com/sysadmin/bash-bang-commands

**Comment by brightly-salty** [comment]
I use `!!` in zsh when I want I am developing and want to compile over and over again without typing the command over and over again. I agree that this would be a good feature to implement.

**Comment by corbinu** [comment]
Just saw this went stale. How about a “papercut” label for this so it stays open but keeps in mind it is a small thing.

 I will say I am a daily driver on Nushell at this point. LOVE that it has let me standardize on one shell given I work on Mac, Linux and Windows machines daily (Windows Terminal+nushell is amazing). This feature is the only thing that bites me daily at this point. Thanks for such great work!

**Comment by fdncred** [comment]
I agree. I was thinking there must be some way to do `alias !! = do last command in history` especially with this PR https://github.com/nushell/nushell/pull/3611 but i haven't looked closely enough to try something out.

**Comment by brightly-salty** [comment]
seems like since #3611 has been merged, it could be implemented now 

(also commenting to remove stale label)

**Comment by danjenson** [comment]
hmmm how would this be implemented using #3611 ?

**Comment by fdncred** [comment]
@danjenson i think it only works with externals like how the PR shows. I can't get it to work with your example either.

**Comment by fdncred** [comment]
ya, i agree. it's been way too long. sorry about that. @corbinu what are the specific bang commands you're looking for that you would then feel comfortable recommending nushell.

**Comment by sholderbach** [comment]
There might be two ways to go about the bash last command builtins: 

1. expand them at evaluation time to fill in the history
2. expand them in the line editor (I think this is also the default behavior in zsh)

Apart from `!!` for full last command, bash knows `!$` for the last token (don't know the exact def) of the last command (e.g. `less file.txt` then `vim !$`) and `^search^replace` to muck with the last history entry

**Comment by hustcer** [comment]
@corbinu @meltinglava @elferherrera This issue seems can be closed by this PR: https://github.com/nushell/nushell/pull/4735 on the latest main branch?

**Comment by johnallsup** [comment]
Aside from !!, with e.g. !ls it recalls the last command beginning with ls. If histverify is set, the resulting command is not executed, so you can edit it. You can quickly collect previous commands into a custom function, for example
mkdir -p $DIR/bin $DIR/lib
ls /
myfunc() { !ls ; $mk ; }
will expand to
myfunc() { ls / ; mkdir -p $DIR/bin $DIR/lib ; }

Then e.g. echo !hello
will recall the last command that began with hello, and prepend echo, and with histverify set will allow you to edit the resulting command before execution.

Also each history item is numbered, so if the command you want to recall is 456, then !456 will recall it, and you can e.g. type
!456 ; !458 ; !454
to make a single line executing the three previous commands.

This is very useful once you're used to it. I'm currently trying to find out how to recall lines from the history in nushell.
(e.g. find the last command beginning with nvim).
