### ISSUE TITLE
Opens `~` On Opening New Terminal In VS Code

### ISSUE THREAD

**Issue by udasitharani** [nushell/nushell#6010]
### Describe the bug

When I open a new terminal session in VS Code, the location is `~`, while other shells correctly open at the correct location, ie, the project root.

### How to reproduce

1. Open a project with VS Code.
2. Open a new terminal session.

### Expected behavior

The location should be the project root and not the home directory.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             | fix/orange-bg                                   |
| commit_hash        |                                                 |
| build_os           | macos-x86_64                                    |
| build_target       | x86_64-apple-darwin                             |
| rust_version       | rustc 1.61.0                                    |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)             |
| pkg_version        | 0.65.0                                          |
| build_time         | 2022-07-05 11:42:01 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by WindSoilder** [comment]
Sorry I'm failed to reproduce it in my environment...

Would you please show your `config.nu` or `env.nu` file to confirm that you didn't force `nu` to start with `~` directory?

**Comment by udasitharani** [comment]
And here's the `env.nu` screenshots:
![Screenshot 2022-07-11 at 10 16 28 PM](https://user-images.githubusercontent.com/56196911/178315965-60720193-edc2-44e2-a27d-639fc0e9283b.png)
![Screenshot 2022-07-11 at 10 16 33 PM](https://user-images.githubusercontent.com/56196911/178315982-89b84671-7ad3-4291-84de-8ca475ccccb5.png)

**Comment by udasitharani** [comment]
tried removing it too, didn't make any difference

**Comment by fdncred** [comment]
so much config - lol. what happens if you backup your config files and just use the default ones when nushell starts up? if that works normally, then the next thing I'd do is start commenting out ~10-20 lines at a time and restarting nushell to see where the error show up.

**Comment by WindSoilder** [comment]
@udasitharani I see the line 94 in your `env.nu`, which is `let-env PWD = /Users/udasitharani`, I doubt it it's force you to start with `~`, would you please comment that line and see if it works normally?

**Comment by udasitharani** [comment]
damn that worked! I had tried removing the `let-env OLDPWD` but somehow missed this one. Thanks a lot!

**Comment by udasitharani** [comment]
By the way, I am new to `nu` and had followed this:
https://www.nushell.sh/book/configuration.html#configuring-nu-as-a-login-shell

which generated a list of these env variables for me including this one.

**Comment by WindSoilder** [comment]
Oh, thanks for your information, it helps a lot.  

It seems that we need to update documentation to not include `PWD` during configuration
