### ISSUE TITLE
changing Path environment variable after shell starts have no effect on windows

### ISSUE THREAD

**Issue by rtfcv** [nushell/nushell#6011]
### Describe the bug

Changing path variable using let-env command after shell starts has no effect what-so-ever.
Another nu.exe started from that shell will take the new env into account.

EDIT:
It is only removal of already existing path (when the shell launches) that is problem.
Adding Path works fine

### How to reproduce

1. `let-env Path = []` (doing `let-env PATH = []` does nothing as well)
1. run some command like `explorer.exe` and discover that it runs even though the path should be empty
2. `echo $env.Path` to see that it actually is empty 
3. `enter .` and running some command changes nothing
4. run `nu` `cmd` or any other shell, will give you a shell with empty Path (Path not PATH is used in these)

### Expected behavior

Changing path, command in the new path will run.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             |                                                 |
| commit_hash        | 390d06d4e7383d9fee814713bda8d1aaca858c5a        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.62.0 (a8314ef7d 2022-06-27)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.62.0 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.65.0                                          |
| build_time         | 2022-07-05 17:31:19 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

only on windows.
doing this on linux produce expected behavior

**Comment by fdncred** [comment]
oh, wow. you're right. that's a bug. I just updated my path with this and didn't think to check to see if it "took".  it did not work for me either.
```
let-env PATH = (
    if "Path" in $env {
        $env.Path | split row (char esep) | prepend 'C:\Apps\Just'
    } else {
        $env.PATH | split row (char esep) | prepend 'C:\Apps\Just'
    }
)

```

**Comment by fdncred** [comment]
@kubouch i bet this is related to some of the things you've been seeing too, with ordering env before config and whatnot.

**Comment by kubouch** [comment]
I can't reproduce it on Linux. What if you set both Path and PATH to `[]`?

**Comment by ChrisDenton** [comment]
I don't know if it's relevant but [`CreateProcess`](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa#parameters) will always look in certain paths even if they're not in `PATH`.

> The system searches for the executable file in the following sequence:
>
> 1. The directory from which the application loaded.
> 2. The current directory for the parent process.
> 3. The 32-bit Windows system directory. Use the [GetSystemDirectory](https://docs.microsoft.com/en-us/windows/desktop/api/sysinfoapi/nf-sysinfoapi-getsystemdirectorya) function to get the path of this directory.
> 4. The 16-bit Windows system directory. There is no function that obtains the path of this directory, but it is searched. The name of this directory is System.
> 5. The Windows directory. Use the [GetWindowsDirectory](https://docs.microsoft.com/en-us/windows/desktop/api/sysinfoapi/nf-sysinfoapi-getwindowsdirectorya) function to get the path of this directory.
>6. The directories that are listed in the PATH environment variable.

**Comment by rtfcv** [comment]
Custom paths (like %USERPROFILE%\scoop\shims) is also affected so I don't think the problem is that.
also I found out that it is only the removal of the path that's problematic.
adding new path does what it's supposed to

**Comment by ChrisDenton** [comment]
The only other bit of trivia that may be relevant is that Windows environment variables are case insensitive but case preserving. Or to put it another way `Path` and `PATH` are considered equal (as is `pAtH`) but if the variable was originally set as `Path` then that's what is returned when iterating keys.

So if you set or get `PATH`, `Path` or `pAtH` then they all set or get the same value. But if you iterate keys then there's no canonical case.

**Comment by fdncred** [comment]
Mine is working again. I have no idea why but just is in my path again. I've compiled and worked on several versions/branched/bugfixes today.
![image](https://user-images.githubusercontent.com/343840/178353573-fdc9dd6b-9e86-4707-a6a1-347633570f3a.png)

**Comment by YizhePKU** [comment]
I can still reproduce this even after #12701. I'll look into this.

**Comment by YizhePKU** [comment]
The issue seems to be our usage of `std::process::Command`, which inherits the environment from the actual Nushell process instead of using `$env`. So even if you remove stuff from `$env.Path`, `std::process::Command` won't see it.

**Comment by YizhePKU** [comment]
...maybe that's not the problem. `explorer.exe` is part of the system paths, which are always searched by [CreateProcessW](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw).

**Comment by devyn** [comment]
@YizhePKU I'm pretty sure we are using [`which`](https://docs.rs/which/latest/which/) to find the executable according to the path var from the `EngineState` and `Stack`.

Here's where we do it, in [`run-external`](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/system/run_external.rs#L209-L237).

However, it looks like we do not return an error if that fails. I don't know if that's necessarily a problem. It seems to be reasonably expected that on Windows, if your PATH is empty, you can still find the system executables. So this might just be totally okay.

**Comment by YizhePKU** [comment]
> I'm pretty sure we are using [which](https://docs.rs/which/latest/which/) to find the executable according to the path var from the EngineState and Stack.

That part of the code is on a fallback path. We only use `which` if calling `Process::spawn()` directly doesn't work.

> However, it looks like we do not return an error if that fails.

Currently, if you try to execute a non-existent `foo.cmd` file, Nushell will print the following message:

```
'foo.cmd' is not recognized as an internal or external command,
operable program or batch file.
```

It's not formatted as an error, which is surprising.

> I don't know if that's necessarily a problem. It seems to be reasonably expected that on Windows, if your PATH is empty, you can still find the system executables. So this might just be totally okay.

I don't know either. I listed all our options going forward. But the fact that this issue was posted seems to prove that the current behavior is surprising.

**Comment by ChrisDenton** [comment]
> It's not formatted as an error, which is surprising.

This is because it's coming from `cmd.exe` rather than nushell.

**Comment by fdncred** [comment]
@YizhePKU Correct me if I'm wrong but by "System Path" you mean the Path environment listed with this command, right?
```nushell
registry query --hklm 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
```
If so, I think the least surprising is your number 2 option but de-dupe them so the path doesn't contain duplicate path entries.

Of course, Windows has "User Path" listed with this command.
```nushell
registry query --hkcu environment
```

In Windows, both paths are searched for running executables. 

One problem though, if we're combining paths and someone does `$env.Path = ""` to remove all their path entries (which they shouldn't do), I'm not sure we can support that. Seems to me, to change the system path should require elevation. So, if you do `$env.Path = ""` I'd expect all entries to be removed _except_ system path entries unless they're running as admin, which you can see with the `is-admin` command.

I think the whole idea by the OP of removing the Path entries is a bit suspect. I'm not sure what the real-world use case for that is. However, adding and entry to the $env.path, and then running a command that is in that path should work.

**Comment by YizhePKU** [comment]
> Correct me if I'm wrong but by "System Path" you mean the Path environment listed with this command, right?

That is correct.

> If so, I think the least surprising is your number 2 option but de-dupe them so the path doesn't contain duplicate path entries.

I'm currently inclined to "do nothing". Like you said, the whole idea of removing Path entries seems suspect. Even if we present `$env` in a way that system path can be removed (i.e. option 2), it won't affact any child process that calls `CreateProcessW` directly. Adding entries to `$env.Path` should always work even if we do nothing.

If we agree on the "do nothing" approach, then maybe we just close this as "intended behavior".

**Comment by fdncred** [comment]
The one thing that is maybe highlighted here for me is, if there are HKLM path entries that are not in the HKCU path, I think we should maybe show them as part of `$env.Path`. I think it's a little surprising the things may execute when they're not in your `$env.path`. Does this go back to our initial rust call to gather all env vars? I mean does `std::env::vars()` get only HKCU env vars? If so, I think that could be wrong for nushell.

While we're talking about this, the same thing is also true about all HKLM env vars, not only Path.

I think, in this instance, we might could get some advice from PowerShell. In pwsh, if you do `dir env:` you see all HKLM and HKCU env vars. Also, in pwsh, if you do `$env:Path -split ';'` you will see all Path entries from HKLM and HKCU. Using this as a guide, it seems like we should be unifying the HKLM and HKCU environments into one environment.

**Comment by YizhePKU** [comment]
I tried `$env:Path = ""` in PowerShell, and it actually refuses to run `explorer` now. This means, internally, PowerShell must have been implemented like option 2, resolving paths into absolute paths before calling `CreateProcessW`.

I guess we can follow their footsteps?

By the way, PowerShell lets me do this in an un-elevated terminal, so if we're doing this, we probably shouldn't enforce admin or anything.

**Comment by fdncred** [comment]
I do think we should follow their lead, I'm just not sure how to do all that exactly. I guess it's good news that pwsh is open-source but the last time I dug through that repo to find something it took a while. It would be nice to see their code to understand 1) how they're getting all the env vars 2) how they're setting the path without requiring elevation. I mean, I guess you should be able to set anything in your process, but you'd maybe only need elevation to actually remove entries from a hklm key.

**Comment by YizhePKU** [comment]
> Correct me if I'm wrong but by "System Path" you mean the Path environment listed with this command, right?

@fdncred I think my previous reply was wrong. Like ChrisDenton said, the registry has nothing to do with this. The real culprit is `CreateProcessW`, which searches some hard-coded directories before PATH. From the [documentation](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw):

> If the file name does not contain a directory path, the system searches for the executable file in the following sequence:
> 
> 1. The directory from which the application loaded.
> 2. The current directory for the parent process.
> 3. The 32-bit Windows system directory. Use the GetSystemDirectory function to get the path of this directory.
> 4. The 16-bit Windows system directory. There is no function that obtains the path of this directory, but it is searched. The name of this directory is System.
> 5. The Windows directory. Use the GetWindowsDirectory function to get the path of this directory.
> 6. The directories that are listed in the PATH environment variable. Note that this function does not search the per-application path specified by the App Paths registry key. To include this per-application path in the search sequence, use the ShellExecute function.

This search order is hard-coded and has nothing to do with HKLM path entries. Sorry for the confusion!

**Comment by ChrisDenton** [comment]
The solution here was as suggested earlier: find the executable then use absolute paths when spawning a process. Presumably that's what powershell does.

**Comment by fdncred** [comment]
Number 6 says it searches the PATH env var, those come from the registry. However I agree that they're inherited and I agree that it uses CreateProcess and we supply envs when we're creating a process, iirc. I don't think we always use CreateProcess though. I think sometimes we shell out to cmd /d /c for cmd built-ins.

But I kind of think I'm conflating 2 issues here though.
1. The create process stuff.
2. What shows up in `$env`, which I still think should work like pwsh does.

Both probably need to be fixed. I'm fine with following Chris' suggestion on the process spawning stuff. Not quite sure about $env solution though.

**Comment by YizhePKU** [comment]
> What shows up in $env, which I still think should work like pwsh does.

Actually, it already does! Take a look at `$env` from Nushell, and it should contain entries from HKLM as well.

**Comment by ChrisDenton** [comment]
Sorry, can I backtrack and ask what the actual issue is here? This works, yes?

```
> $env.PATH = []
> echo $env.PATH
╭────────────╮
│ empty list │
╰────────────╯
```

`PATH` itself works just like powershell, etc. The only issue is when other things (outside of nu) use `PATH`, no?

**Comment by YizhePKU** [comment]
The issue is that Nushell finds `explorer.exe` even with an empty `$env.PATH`.

**Comment by ChrisDenton** [comment]
Right so that comes back to how processes are launched. Currently there's a bunch of code where we try spawning the fallback to something else and if that doesn't work we fallback to something else again. It would be good to clean this up and make it more consistent.

So it just searches `$env.PATH` using the file extensions in `$env:PATHEXT` and once found only then figures out how to run it (e.g. maybe using an absolute path).

**Comment by fdncred** [comment]
> > What shows up in $env, which I still think should work like pwsh does.
> 
> Actually, it already does! Take a look at `$env` from Nushell, and it should contain entries from HKLM as well.

Oh! I you're right. I was looking for a specific hklm entry that started with `a` and didn't see it..... until I looked at the bottom of the list. I guess they're sorted case-sensitively. At least they're their. Thanks for pointing this out.

**Comment by fdncred** [comment]
> Right so that comes back to how processes are launched. Currently there's a bunch of code where we try spawning then fallback to something else and if that doesn't work we fallback to something else again. It would be good to clean this up and make it more consistent.
> 
> So it just searches `$env.PATH` using the file extensions in `$env:PATHEXT` and once found only then figures out how to run it (e.g. maybe using an absolute path).

100% I agree with you Chris. A lot of that code has been around a while, and it could definitely be cleaned up. As I recall, the tricky part has always been running cmd.exe built-ins. It would be good to find a good way to make this better.

**Comment by YizhePKU** [comment]
I'll start working on it.

**Comment by YizhePKU** [comment]
Do we really want to support `cmd.exe` built-ins? Like, `ECHO` is already in Nushell, `CLS` should probably be implemented directly as a command, `MKLINK` should probably be `ln`, etc...

**Comment by fdncred** [comment]
> Do we really want to support `cmd.exe` built-ins? Like, `ECHO` is already in Nushell, `CLS` should probably be implemented directly as a command, `MKLINK` should probably be `ln`, etc...

We have changed this list of supported built-ins many times. Yes, some of these absolutely have to be supported but others maybe not. For instance:
- `assoc` and `ftype` need to be there for sure. 
- probably keep `cls` because it's a windows specific clear screen. 
- `mklink` should stay because windows symbolic linking is slightly different. 
- `ver` is helpful sometimes. 
- `vol`, not sure there's another easy way to get that info.
- `start`, we have a start command so maybe remove it? i don't remember how identical our start is to windows start.
- `pause`, is good for batch/cmd files but i'm not sure what else
- `echo` has some special cases like echo off, not sure how useful that is though in nushell
- there are other built-ins too that could be helpful but were removed. not sure. it may be good to look at those old prs because this same conversation happened there too. rgwood did one of the last pr on this area if memory serves.

A key concept of nushell is to support windows, macos, and linux. Removing windows functionality isn't something i'm willing to do right now. Replacing it for something that works 100% identically is an option but we don't need some half-implemented tools that work great on linux and macos and just kind of work on windows because windows is different.

**Comment by YizhePKU** [comment]
@IanManske I have a question about `OutDest`.

According to the comments on `OutDest`, `OutDest::Capture` is similar to `OutDest::Pipe` except that it "will never combine stdout and stderr or place an external command's stderr into stdout". Does this mean that only the combination of `stdout == OutDest::Pipe, stderr == OutDest::Pipe` is meaningful (merge the streams), and every other combination is the same (don't merge the streams)?

In other words, is this table correct?

|`stdout`          |`stderr`          |`stdout` of `PipelineData`|`stderr` of `PipelineData`|
|------------------|------------------|--------------------------|--------------------------|
|`OutDest::Pipe`   |`OutDest::Pipe`   |combined                  |nothing                   |
|`OutDest::Pipe`   |`OutDest::Capture`|stdout                    |stderr                    |
|`OutDest::Capture`|`OutDest::Pipe`   |stdout                    |stderr                    |
|`OutDest::Capture`|`OutDest::Capture`|stdout                    |stderr                    |

This feels a bit weird to me, so I want to make sure I didn't misunderstand anything.

**Comment by IanManske** [comment]
I kind of tacked on `OutDest::Capture` as another option, because we have a few commands (`complete`, `tee`, and `save`) that need to capture both `stdout` and `stderr`. I'm thinking of somehow reworking these commands, but for now the `OutDest::Pipe` and `OutDest::Capture` interaction is definitely weird. Currently, the commands in question set both stdout and stderr to `Capture`, and this will override any `Pipe` in the eval code, so the second and third rows in your table should (hopefully) not be possible.

**Comment by YizhePKU** [comment]
Status report: about half way there. I've finished the "spawning process" part. Now to figure out how to find executables using `PATH` and `PATHEXT`...

Current issues:

* How to deal with `PATHEXT`. I know `.cmd` and `.bat` should shell out to `cmd.exe`, but what about the others?
* What to do with the arguments. Should we remove quotes? Should we expand tilde? Should we perform glob expansion? The current implementation does it very inconsistently. It even tries to transform `--foo="bar"` into `--foo=bar`, which seems crazy to me.

**Comment by fdncred** [comment]
I think `PATHEXT` is meant to allow programs to execute without adding the file extension. I created this how-to about a year ago. It shows how to make a nushell script executable with `assoc` and `ftype` as well as how `PATHEXT` works.

```
def main [arg] {
  print $"Hello ($arg)!"
}

# How to make nushell scripts executable in Windows 11
# run cmd.exe as administrator and run these 2 commands
# it has to be cmd.exe because ftype and assoc are built-ins on cmd.exe
#
# assoc .nu=NushellScript
# ftype NushellScript=c:\some\path\.cargo\bin\nu.exe %1 %*
#
# note - should make this next part scriptable too
# run regedit.exe with administrator privileges
# go to key HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Session Manager\Environment
# add ;.NU to the PATHEXT key
# This allows you to type "im_executable World" without having to add the .nu extension
# restart cmd.exe/terminal/whatever shell hosting nushell
# Now you should be able to type "im_executable World", assuming im_executable.nu is in the current directory, and it should execute it
```

If you want to execute something like a py file you either need to look up the ftype/association in the registry and use it's guidance on how to execute a file with parameters or shell out to cmd/pwsh/powershell that already know about ftypes and associations.

As far as quoting, we should do whatever windows needs. I'm not quite sure what that is though.

**Comment by YizhePKU** [comment]
Is there a good reason for the `which-support` feature flag to exist? The `which` crate is already a non-optional dependency of `nu-cli`, and I can't use it in my implementation if it's an optional dependency.

I traced the decision to add the `which-support` feature flag all the way back to https://github.com/nushell/engine-q/pull/782. At the time it was only used for the `which` command, so it made sense to mark it as optional. But I think at this point, we should probably just remove the feature flag and make it mandatory.

**Comment by fdncred** [comment]
Good detective work. I've wondered the same thing about `which`. I think I've asked about it before but it's hard to find results with such a common word in discord.

I wonder if it's supported in all of the operating systems we build binaries for in releases? That's my only guess.

**Comment by kubouch** [comment]
IIRC there were some platform issues with it, but I don't recall precisely, and it might be obsolete already. We could perhaps try removing it and if there are any issues with it, document them.

**Comment by YizhePKU** [comment]
I have some questions about strings and globs.

Nushell differentiate between **bare strings** (unquoted, or quoted by backticks) and **quoted strings** (quoted by single or double quotes). Is that considered part of the value or mere syntax? In other words, if I store a bare string into a variable, does it remember that it used to be a bare string?

Nushell doesn't actually allow us to assign bare strings to variables (Nushell will interpret it as a command), but we can store it in a list. What should be the expected behavior of the following code?

```nu
let foo = [`*.md`]
ls ...$foo     # Should this trigger glob expansion?
```

---

The rest of the questions are about the `Value` enum. Here's part of its definition (simplified for readability):

```rust
enum Value {
    // ...other variants
    String {
        val: String,
    },
    Glob {
        val: String,
        no_expand: bool,
    },
    // ...other variants
}
```

When does an expression evaluates to a `Value::Glob` instead of `Value::String`?

What does it mean for `Value::Glob` to be `no_expand`? Isn't that just a `Value::String`?

Should evaluating a string literal keep its surrounding quotes? Currently it does, but I don't see why it should. I feel like it defeats the purpose of having seperate `Value::String` and `Value::Glob` variants.

---

These questions are quite impactful. Commands that want to handle glob patterns have to detect whether a string is quoted or not, and that logic is duplicated in every command.

**Comment by WindSoilder** [comment]
> When does an expression evaluates to a Value::Glob instead of Value::String

When a parameter has a syntax shape `SyntaxShape::GlobPattern`, it will evaluate to a `Value::Glob`.

> What does it mean for Value::Glob to be no_expand? Isn't that just a Value::String

It's essentially true.  I think it's good to keep 1 to 1 mapping from one `SyntaxShape` to one Value, it would be wield if `SyntaxShape::GlobPattern` can leads to both `Value::Glob` and `Value::String`.

> Should evaluating a string literal keep its surrounding quotes? Currently it does for external commands (and not for others), but I don't see why it should.

Actually it doesn't keep its surrounding quotes, it's trimmed inside `run_external`.
https://github.com/nushell/nushell/blob/92831d7efcd0586a85966560beb0c538f4a0fc36/crates/nu-command/src/system/run_external.rs#L657
The reason to do trimming logic there is we need to make decision if we need to expand glob before passing it to external commands.  You can see this pr for more information: https://github.com/nushell/nushell/pull/6014

**Comment by YizhePKU** [comment]
Status report: almost done.

Escaping arguments for CMD built-ins is tricky. In CMD, `echo "foo"` will print `"foo"` with the quotes intact, while `mklink "foo" "bar"` will create a link named `foo` without the quotes. This is one of the reasons why `^echo "\"abcd"` still doesn't work in Nushell today (Issue https://github.com/nushell/nushell/issues/6559).

Here are our options:

1. Give `echo` special treatment and quote arguments using a different set rules.
2. Leave it be. `^echo "\"abcd"` will still give wrong output, but maybe that's fine.
3. Remove `echo` from the list of supported built-ins. Maybe it's just not that useful anyways.

**Comment by rgwood** [comment]
> IIRC there were some platform issues with it, but I don't recall precisely, and it might be obsolete already. We could perhaps try removing it and if there are any issues with it, document them.

Apparently I was wondering this 2 years ago: https://discord.com/channels/601130461678272522/615962413203718156/958780855956951050

@fdncred answered:

> i think we disabled which-support on wasm

So yeah, looks like it was a thing for the wasm build (which I believe is no longer used).
