### ISSUE TITLE
Cannot launch most binaries form ~/.local/bin/

### ISSUE THREAD

**Issue by gagero** [nushell/nushell#6015]
### Describe the bug

Trying to launch most binaries located in ~/.local/bin/ gives this error: 
```
Error: nu::shell::external_command (link)

  × External command
   ╭─[entry #7:1:1]
 1 │ pmbootstrap
   · ─────┬─────
   ·      ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)
```

Strangely, some binaries (like rofi-power-menu in my case) work.

### How to reproduce

Try to launch any binary located in ~/.local/bin/

### Expected behavior

Successful launch of the binary

### Screenshots

![image](https://user-images.githubusercontent.com/96359986/178366448-d495a806-241c-4eec-9e09-030e506c6138.png)

I blocked out my username due to privacy reasons.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.64.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.60.0 (gentoo)                           |
| cargo_version      | cargo 1.60.0                                    |
| pkg_version        | 0.64.0                                          |
| build_time         | 2022-07-11 14:04:24 +02:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
if you do `$env.PATH` is ``/.local/bin` in your path?
