### ISSUE TITLE
Feature request: Support for git

### ISSUE THREAD

**Issue by techthumb** [nushell/nushell#602]
Hi,

Is there a plan to add support for tabulating output from the `git status` command?

Something like https://github.com/mroth/scmpuff would be very useful.

Thanks!

**Comment by androbtech** [comment]
@techthumb Can you share some usage examples for your use cases?  From our one-liners channel in Discord, here is an example on deleting branches that have been merged locally.

`git branch --merged | lines | where $it != "* master" | git branch -D $it`

**Comment by lukesutton** [comment]
I think some basic functionality which takes the output of git commands and puts them in a table would be excellent. 

For git status I'm using:
```
git status --porcelain | lines | split-column " " status file
```

Not too bad, but it'd be nice to not have to do that all the time. Something like git log is pure horrors however.

```
echo "$(git log --pretty=format:'%h|%s|%aN|%aE|%aD' -n 10)" | lines | split-column "|" commit subject name email date
```

The echo is a parsing work around, but the rest of it is the only way I figure out something usable.

I think it's arguable that aliases are a better way of handling this, but still it'd be nice to have it built in.

**Comment by androbtech** [comment]
@lukesutton Thanks for the feedback. What are your favorite git subcommands? What are the git subcommands that you think everyone would use all the time?

**Comment by lukesutton** [comment]
@andrasio Apologies fort the late reply. The commands I use heavily are:

- status
- log
- checkout
- branch
- push/pull

So bread and butter commands when doing coding work. My intuition is that most other people would use the same.

**Comment by jzaefferer** [comment]
@techthumb @lukesutton re-reading the discussion here so far, I can't tell what `nu` could actually do here. Putting the output of `git status` into a table doesn't seem particularly useful by itself. And that's completely different from what `scmpuff` does (adding numbers to the output, which can then be used in other commands).

I personally use an alias called `s` all the time, for `git status -sb` and a mostly two variations of `git log`:

* lg = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative
* lp = log -p -M90%

But I don't really see how `nu` can add anything useful to that. Could either of you elaborate?

**Comment by jzaefferer** [comment]
What I'm missing are the bash completions for git. The arrow-right completion at least helps with previous commands, but lots of others are missing.

I guess that's part of #1412 already.

**Comment by jonathandturner** [comment]
@techthumb - I think this is a good idea. I'd like to keep it open so that we can add support in the future.
