### ISSUE TITLE
Wrong tabled rendering of records

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#6024]
### Describe the bug

After https://github.com/nushell/nushell/pull/5999, records no longer render as nicely as they used to. There is some extra whitespace and a line. 

### How to reproduce

Rendering `$env.config.hooks` from the default config, light table mode.

Before:
```
> $env.config.hooks
 pre_prompt      [list 1 item]
 pre_execution   [list 1 item]
 env_change      {record 1 field}
```

After:
```
> $env.config.hooks

──────────────────────────────────
 pre_prompt      [list 1 item]
 pre_execution   [list 1 item]
 env_change      {record 1 field}
```

### Expected behavior

The records should look like before.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.1                                          |
| branch             |                                                 |
| commit_hash        | f3036b8cfd4dd6177125fb1e1d1898009097734e        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.0 (a8314ef7d 2022-06-27)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.62.0 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.65.1                                          |
| build_time         | 2022-07-11 23:59:41 +03:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | gstat                                           |

### Additional context

It appears with `$env.config.table_trim.methodology` set to both "wrapping" and "truncating".

**Comment by zhiburt** [comment]
From a few sec look;
Header is a bug;
The extra whitespace is OK as it's a padding. (maybe I didn't understand what  you meant)

**Comment by zhiburt** [comment]
Hi (forgot to say it...) @kubouch Could you verify it?

![image](https://user-images.githubusercontent.com/20165848/178556929-24405911-4cb3-4b39-90f3-164cb5c6cab7.png)

**Comment by kubouch** [comment]
By extra whitespace I meant the extra line above the `──────────────────────────────────`
