### ISSUE TITLE
VSCode's `code` command does not work in nushell

### ISSUE THREAD

**Issue by mfdorst** [nushell/nushell#6032]
### Describe the bug

VSCode provides a command line tool named `code` which allows you to open vscode in the current directory. It doesn't seem to work in nushell (on linux).

### How to reproduce

1. Install vscode on Manjaro linux (maybe other linuxes too?)
2. (Maybe?) install the `code` cli tool (I don't remember if it's included by default or not)
3. Run nushell and type `code`.

### Expected behavior

VSCode should open (it does not). It does open in other shells (namely `zsh` and `bash`).

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             | master                                          |
| commit_hash        | 390d06d4e7383d9fee814713bda8d1aaca858c5a        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.0 (Arch Linux rust 1:1.62.0-1)       |
| cargo_version      | cargo 1.62.0                                    |
| pkg_version        | 0.65.0                                          |
| build_time         | 2022-07-06 10:00:06 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

+ OS: Manjaro Linux x86_64
+ Kernel: 5.15.50-1-MANJARO
+ DE: Plasma 5.24.6
+ Terminal: Alacritty

**Comment by jntrnr** [comment]
I use a very similar setup and it works okay for me.

Have you checked to see if the path where `code` lives is in your PATH?

**Comment by mfdorst** [comment]
Oh, odd, it started working for me now. I don't know what changed. Never mind!
