### ISSUE TITLE
`(git commit)` does not work when run in parentheses

### ISSUE THREAD

**Issue by mfdorst** [nushell/nushell#6039]
### Describe the bug

I encountered some bizarre behavior:
```
> (git commit)
hint: Waiting for your editor to close the file...
```
It just hangs here until you `Ctl+C`. It seems like the editor is open but somehow not connected to the terminal. It works perfectly fine when run without parentheses.

It might seem odd to use parentheses here, but I originally discovered this when running this alias:
```
alias gca = (git add -A ; git commit)
```

### How to reproduce

1. Be in a git repo
2. Make a change (`git commit` only opens the editor if there are uncommitted changes)
3. Run the command `(git commit)`

### Expected behavior

Your configured terminal editor should run, allowing you to enter a commit message.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             | master                                          |
| commit_hash        | 390d06d4e7383d9fee814713bda8d1aaca858c5a        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.0 (Arch Linux rust 1:1.62.0-1)       |
| cargo_version      | cargo 1.62.0                                    |
| pkg_version        | 0.65.0                                          |
| build_time         | 2022-07-06 10:00:06 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

```
let-env EDITOR = "nvim"
```

**Comment by Kangaxx-0** [comment]
I am not able to repo this bug, when I run `(git commit)` on latest main

<img width="647" alt="image" src="https://user-images.githubusercontent.com/85712372/180350708-e5f1db6c-641e-47d8-ad59-1b916a9ab07c.png">

The parentheses in nu is called [subexpression](https://www.nushell.sh/book/variables_and_subexpressions.html#subexpressions)

**Comment by CAD97** [comment]
`git commit` will exit cleanly if your working tree is clean; it opens the editor if you have staged changes (and will only open a hidden console editor in that case).

**Comment by mfdorst** [comment]
@Kangaxx-0 I updated the steps to repro. You do have to have uncommitted changes for this to happen.

**Comment by mfdorst** [comment]
For anyone trying to do `git commit` in an alias like I was, a simple workaround is to use a function instead.
```nu
def gca [] {
    git add -A
    git commit
}
```

**Comment by CAD97** [comment]
(Also, `git commit` supports `-a`, so you don't need to use `git add`.)

**Comment by mfdorst** [comment]
@CAD97 Not quite. The `-a` flag will commit all files that have been changed or deleted, but not new files. To commit absolutely everything including new files you need to `git add -A` first.

**Comment by ysthakur** [comment]
@mfdorst Are you still able to reproduce this? I am unable to on the latest main ([64afb52](https://github.com/nushell/nushell/commit/64afb52ffaa68ac761b5f5d05d51d3fb1547084b) at the time of writing)

**Comment by mfdorst** [comment]
Yup, looks like it's fixed now.
