### ISSUE TITLE
pwd command.

### ISSUE THREAD

**Issue by androbtech** [nushell/nushell#604]
It'd be nice having our own `pwd` command. At the moment, doing `pwd` we get the expected  behavior but if we enter a file, since the filesystem view becomes an abstraction and we use the current path to keep track where in the file we currently are, doing `pwd` will fail.

Reproducing:

```
> curl https://api.github.com/orgs/nushell | from-json | embed details
━━━━━━━━━━━━━━━━
 details
────────────────
 [table: 1 row]
━━━━━━━━━━━━━━━━

> curl https://api.github.com/orgs/nushell | from-json | embed details | save data.json
> enter data.json
/> ls
━━━━━━━━━━━━━━━━
 details
────────────────
 [table: 1 row]
━━━━━━━━━━━━━━━━

/> cd details
/details> ls | pick public_members_url
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 public_members_url
─────────────────────────────────────────────────────────────
 https://api.github.com/orgs/nushell/public_members{/member}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/details> pwd
error: No such file or directory (os error 2)
```

The expected behavior should be:

```
/details> pwd
/details
```

**Comment by jonathandturner** [comment]
When can extend #612 to work with value shell also. We may want to create a new command in Shell for it.

**Comment by JonnyWalker81** [comment]
I was looking into this a little and thought that the `pwd` command would use the shell manager to get the current path for the current shell.  If you are inside of a file (e.g. json or toml) it would know the correct path, while `env::current_path` would not.  Am I on the right track with my understanding on how nushell works?

**Comment by androbtech** [comment]
@JonnyWalker81 You are on the right track señor. We still need to extend it do ValueShell.

**Comment by JonnyWalker81** [comment]
I will take a look, seems straightforward enough, but I am probably missing something.  @androbtech Thank you for the hint and guidance.

**Comment by androbtech** [comment]
@JonnyWalker81 Full steam ahead, Capitán!

@chhetripradeep @JonnyWalker81 More than welcome to see you guys join the Discord (link in the README)
