### ISSUE TITLE
Switching drives on Windows

### ISSUE THREAD

**Issue by CAD97** [nushell/nushell#6043]
### Related problem

In both pwsh and cmd, you can change between drive volumes (e.g. `C:` and `D:`) just by writing `D:`. In pwsh, `cd D:` also puts you onto `D:`. In cmd, `cd D:` just changes the current directory on the `D:` volume but does not change the pwd to the `D:` volume.

In nushell, the standard way to get around in the interactive shell is just to use `../path/to/dir`. What's surprising is that using a drive-prefix as a path (e.g. `D:`) "succeeds" (`$env.LAST_ERROR_CODE` is `0`). However, the working directory is not changed. Using a drive-prefixed path (e.g. `D:\git\rust-lang\rust`) fails.

What appears to be happening is that `D:` is not recognized by nushell, so is treated as an extern and `^D:` is executed. This runs `cmd /c 'D:'`, which switches the newly started `cmd` to the `D:` drive and then returns back to nushell. (This is also the behavior of running `^cd`.) This is consistent with `D:\git\rust-lang\rust`, which gets translated to `^D:\git\rust-lang\rust` and returns the native shell "is not an operable program" message.

### Describe the solution you'd like

Ideally, nushell should perform steps along the following lines:

- If the command is an internal command, do that.
- Attempt to resolve the path of the command.
  - If it is a valid path,
    - If it is a directory, `cd` to it.
    - If it is not a directory, `exec` it.
- Fall back to running as an extern command in the fallback shell.

### Describe alternatives you've considered

Status quo 🤷

### Additional context and details

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.64.0                                          |
| branch             | main                                            |
| commit_hash        | d1c719a8cc52b1cb3f60810daa8bf28e69eb6617        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)             |
| pkg_version        | 0.64.0                                          |
| build_time         | 2022-06-15 03:10:01 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by rgwood** [comment]
Thanks for the investigation and detailed issue. The relevant code seems to be here: https://github.com/nushell/nushell/blob/89b374cb169bbab6bb2dbb42466cae2265ddcdfa/crates/nu-cli/src/repl.rs#L324-L335

I'm on vacation and my laptop only has one drive, but if we nail down the desired behaviour I can probably work on this later this month.

Say the PWD is currently `D:\foo`. Should typing `D:` change the PWD to `D:\`, or should it leave the PWD as-is? I prefer the former, but I can see an case for the latter.

**Comment by rgwood** [comment]
Instead of overhauling the existing auto-cd logic as proposed in this issue, I wonder if we should just add a special case in the REPL for drive letters (Windows-only, of course). Something like:

1. Check whether the input string looks like a drive (could just use a regex: `^[a-zA-Z]:[/\\]?$`)
2. If so, auto-cd to the root of that drive

**Comment by CAD97** [comment]
> Say the PWD is currently `D:\foo`. Should typing `D:` change the PWD to `D:\`, or should it leave the PWD as-is? I prefer the former, but I can see an case for the latter.

Both pwsh and cmd leave the pwd as-is; `D:` is "switch to the pwd of `D:`" (which may be anywhere, separately managed from cwd of `C:`).

Example pwsh behavior (starship prompt):

```
C:\Users🔒
❯ D:

D:
❯ cd git

D:\git
❯ C:

C:\Users🔒
❯ D:

D:\git
❯ C:\Windows
C:\Windows: The term 'C:\Windows' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

D:\git
❯ cd C:\Windows

C:\Windows🔒
❯
```

Using [`SetCurrentDirectory`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setcurrentdirectory) with just a drive path will replicate this behavior. From [Changing the Current Directory](https://docs.microsoft.com/en-us/windows/win32/fileio/changing-the-current-directory):

> Although each process can have only one current directory, if the application switches volumes by using the [SetCurrentDirectory](https://docs.microsoft.com/en-us/windows/desktop/api/WinBase/nf-winbase-setcurrentdirectory) function, the system remembers the last current path for each volume (drive letter). This behavior will manifest itself only when specifying a drive letter without a fully qualified path when changing the current directory point of reference to a different volume. This applies to either Get or Set operations.

**Comment by CAD97** [comment]
Personally, I think it'd be a reasonable resolution to take the `if` linked above and just add a `|| regex("^[a-zA-Z]:").matches(orig)` case.

**Comment by rgwood** [comment]
> Both pwsh and cmd leave the pwd as-is

I’m a little reluctant to implement this in Nu, mostly for implementation complexity reasons but also because I think it’s somewhat unintuitive. I agree that adding the regex check to the if statement (or the moral equivalent of that) is a good way forward.

**Comment by CAD97** [comment]
Note that if you do `windows::SetCurrentDirectory(lpcstr!("D:"))` you get this behavior automatically from the OS. I agree that implementing the behavior as part of nushell is unnecessary.

If we treat `D:` as a "switch drive volume" command and don't autocd `D:\git`, we should use the OS API for the switch drive volume.

If we recognize `D:` as a path introducer like we do for `.~/\`, then we autocd for `D:\git`, and `D:` cds to the drive root. I think this is the correct behavior for nushell.

Not supporting drive-relative paths (`C:Projects\apilibrary\apilibrary.sln`) is not really an issue in practice, I doubt anyone really uses those :)

(So the "looks like a path" regex would be `^[.~/\\]|[a-zA-Z]:[/\\]?`.)

**Comment by andrasio** [comment]
Amazing catch!
