### ISSUE TITLE
`login.nu` don't work.

### ISSUE THREAD

**Issue by luck07051** [nushell/nushell#6055]
### Describe the bug

I use `chsh -s /bin/nu` to change my login shell to `nu`. After reboot, `login.nu` just don't work whan I login...
But if I run `nu -l` in shell manually, `login.nu` work normally.
I search for a while and still not found solution...

Sorry for my bad English.
And I not familiar with github, if has better place to asking, please tell me!

### How to reproduce

1. `chsh -s /bin/nu`
2. logout and login
3. `login.nu` don't work

### Expected behavior

I expected nu will run `login.nu` when I login.

### Configuration

> version | transpose key value | to md --pretty

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             |                                                 |
| commit_hash        | 390d06d4e7383d9fee814713bda8d1aaca858c5a        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.0 (Arch Linux rust 1:1.62.0-1)       |
| cargo_version      | cargo 1.62.0                                    |
| pkg_version        | 0.65.0                                          |
| build_time         | 2022-07-06 10:00:06 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by sergiomeneses** [comment]
this was marked as closed but the issue is still there, once i setup nushell as my login shell, doesn't load my `login.nu` config, i must to use `nu -l` manually to works, is there any idea about how to fix this?

**Comment by fdncred** [comment]
I have nushell as my login shell and it works fine for me. I went through my login.nu, config.nu, and env.nu and put `print "hello from whichever_config.nu"` in each file as the first line and when I login, I see all 3 printed.

One thing I'm not sure of is what I have in my /etc/shells. I'll look in a few minutes.

**Comment by fdncred** [comment]
This is what my startup looks like
![image](https://github.com/nushell/nushell/assets/343840/3c2228b3-4cd1-4cdb-9b7d-c57426feec86)

This is what's in my /etc/shells
```
❯ cat /etc/shells
# /etc/shells: valid login shells
/bin/sh
/bin/bash
/usr/bin/bash
/bin/rbash
/usr/bin/rbash
/bin/dash
/usr/bin/dash
/usr/bin/tmux
/usr/bin/screen
/usr/bin/sh
/bin/zsh
/usr/bin/zsh
/home/fdncred/.cargo/bin/nu
/usr/bin/fish
/usr/bin/pwsh
/opt/microsoft/powershell/7/pwsh
```

**Comment by sergiomeneses** [comment]
Now it work, i don't know why, i am on ubuntu WSL, maybe it needs to restart wsl `wsl --shutdown`.

**Comment by sergiomeneses** [comment]
I found the error, i doesn't works when i use the terminal on VS Code

**Comment by fdncred** [comment]
I see this too, but I don't see how this is a nushell issue. It may be, but I'm not sure.
![image](https://github.com/nushell/nushell/assets/343840/8662cc12-946b-464b-a163-c46ad4a2cc2a)
There should be "Hello, from login.nu". I think there's a way to pass args to the default shell for vscode.

**Comment by sergiomeneses** [comment]
> I see this too, but I don't see how this is a nushell issue. It may be, but I'm not sure. ![image](https://user-images.githubusercontent.com/343840/267446555-8662cc12-946b-464b-a163-c46ad4a2cc2a.png) There should be "Hello, from login.nu". I think there's a way to pass args to the default shell for vscode.

Yeah I set my VS Code terminal to use the `-l` param, thanks.
