### ISSUE TITLE
Table Splitting

### ISSUE THREAD

**Issue by fennewald** [nushell/nushell#6059]
### Related problem

Given a list of data, it is not easy to turn that into several lists, split by some block.

For example, consider the following input and desired output:
```
# Several zero-terminated sequences, concatenated together
let input = [92 50 38 0 12 23 0 72 0]
let output = [
  [92 50 38]
  [12 23]
  [72]
]
```

`take while` solves this assuming you are reading only the first such group.

### Describe the solution you'd like

The commands `group while` and (optionally, for convenience) `group until`.

They would accept a block which evaluated to true or false. On true, the item is added to the current group. On false, the current group is marked as complete, and a new, empty group is created.

Solving the example above would look like:
```
$input | group while {|it| $it != 0 }
```

### Describe alternatives you've considered

I managed to get the behavior using this snippet:
```
$input | reduce -f [[seed] []] {|it, acc|
  let len = ($acc | length)
  if $it == 0 {
    $acc | append [[]]
  } else {
    $acc | first ($len - 1) | append [($acc | last | append $it)]
  }
} | skip 1
```

I do not fully understand my own code (unsure *why* seed is needed in the `-f` of reduce).

### Additional context and details

`group until` may not be necessary. It would be identical to `group while not`

**Comment by fennewald** [comment]
additional thought: it may be desirable to also capture the final 'sentinel' value for a group. Maybe default behavior should be to include the final item, at the very least it can be a flag to do so

**Comment by fdncred** [comment]
Just documenting here what @jntrnr suggested to me and that is, perhaps we augment the `split` command to allow it to take a list and return lists. So then we could do `$input | split 0` and it would return the proper result.
