### ISSUE TITLE
Short flags aren't triggering completions

### ISSUE THREAD

**Issue by jackos** [nushell/nushell#6060]
### Describe the bug

Short arguments e.g. `docker build -<tab>` aren't triggering completions

### How to reproduce

1. Export a completion with short flags 
```nu
export extern "docker build" [
  --image(-i) #image name
  -h --help #show help for docker
  ...args
]
```

2. Try to get suggestions
```plaintext
docker build -<tab>
```
3. Observe the result:
```bash
NO RECORDS FOUND
```
4. Add another dash
```plaintext
docker build --<tab>
```
5. Observe the result:
```plaintext
--help show help for docker
--image image name 
```

### Expected behavior

Step 3 should result in:
```
-h   --help    show help for docker
-i   --image   image name
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             | main                                            |
| commit_hash        |                                                 |
| build_os           | macos-aarch64                                   |
| build_target       | aarch64-apple-darwin                            |
| rust_version       | rustc 1.61.0                                    |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)             |
| pkg_version        | 0.65.0                                          |
| build_time         | 2022-07-05 11:42:01 +00:00                      |

**Comment by merelymyself** [comment]
Duplicate of #5949?

**Comment by jackos** [comment]
Closing as duplicate of https://github.com/nushell/nushell/issues/5949
