### ISSUE TITLE
swalloed single quote character

### ISSUE THREAD

**Issue by N4tus** [nushell/nushell#6069]
### Describe the bug

I have  a raw string like so ``let pomsky_str =  `:img([s]) ('.jpg' | '.dng') '.pp3'` `` and i have a binary (named echon) that just prints its first argument:
```rust
fn main() {
    println!("{}", std::env::args().nth(1).unwrap());
}
```
When calling `echon $pomsky_str` it prints `:img([s]) (.jpg' | '.dng') '.pp3`. However calling `echo $pomsky_str` prints `:img([s]) ('.jpg' | '.dng') '.pp3'`. This difference, even if intentional, is very confusing.
This is not exclusive to raw strings.

### How to reproduce

(see description)

### Expected behavior

I expected to keep the single quotes like so `:img([s]) ('.jpg' | '.dng') '.pp3'`

### Configuration

| | |
|-|-|
| version            | 0.65.0                                      |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | linux-x86_64                                |
| build_target       | x86_64-unknown-linux-gnu                    |
| rust_version       | rustc 1.64.0-nightly (6dba4ed21 2022-07-09) |
| rust_channel       | nightly-x86_64-unknown-linux-gnu            |
| cargo_version      | cargo 1.64.0-nightly (c0bbd42ce 2022-07-03) |
| pkg_version        | 0.65.0                                      |
| build_time         | 2022-07-10 20:36:01 +02:00                  |
| build_rust_channel | release                                     |
| features           | default, trash, which, zip                  |
| installed_plugins  |                                             |

**Comment by fdncred** [comment]
As you've discovered, quoting for internals is handled differently than quoting for externals. 

It kind of looks like we may have a bug. We have four types of quotes and they're all handled a bit differently. We are making changes to these all the time trying to get it right. 

Types of quotes. 
- Bare words - no quotes 
- Single quotes 
- Double quotes
- Backtick quotes

**Comment by thegedge** [comment]
I think my expectation of `^external $var` would pass `$var` exactly as the first arg to external, properly escaped for the external. This is different than many (most?) other shells, but I always hated having to know how to quote things (I generally always just did `"${var}"` in bash/zsh).

Is that the way we would like this to work?

For now, you can work around the hack dealing of quotes by just adding a space at the end of your variable. What's happening is that nushell sees that `'` at the end of the string and assumes a single quoted value, so it strips away the first `'` on the left too.

**Comment by WindSoilder** [comment]
Currently if you define it as let x = `abc`, it will try to run `abc`.

You can define it with something like this: `let pomsky_str =  ":img([s]) ('.jpg' | '.dng') '.pp3'"`, and it will pass to external commands and show as expected.

So I think it's resolved
