### ISSUE TITLE
`into string --decimals` does not add decimals to integer numbers

### ISSUE THREAD

**Issue by x3rAx** [nushell/nushell#6078]
### Describe the bug

Hi,

I'd like to format a number so that it always has two decimal digits. This should work by using `into string` with the `--decimals` argument. But with integer numbers, the decimals are missing.

### How to reproduce

```nu
10 | into string --decimals 2  #=> 10
```

### Expected behavior

The output should also have the number of decimal digits specified by `--decimals`, even when the input is an integer type.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.61.0 (a028ae4 2022-04-29)               |
| pkg_version        | 0.65.0                                          |
| build_time         | 2022-07-08 22:54:42 +02:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by x3rAx** [comment]
I think this is the part where the conversion happens: https://github.com/nushell/nushell/blob/410f3ef0f02e85312a8a54ae375387fbbf6aea70/crates/nu-command/src/conversions/into/string.rs#L210-L218

What is the `group_digits` variable for? In the current file, the function is called so that `group_digits` is always false. But the function is `pub` so I don't know where it is set to true (I'm currently on my smartphone, bored, so I tried to find the affected code section directly on GitHub).

**Comment by fdncred** [comment]
`group_digits` probably needs to be re-enabled. I suspect that it wasn't ported with the engine-q migration. If you follow `format_int()` you'll see that it's for separating digits by thousands. i.e. 1000000 vs 1,000,000.
