### ISSUE TITLE
Commands using $in don't affect their environment

### ISSUE THREAD

**Issue by Benjamin-L** [nushell/nushell#6081]
### Describe the bug

Found a bizarre inconsistency in how `cd` behaves inside an iterator block. It seems that in one very specific situation, it doesn't actually change the current directory.

### How to reproduce

```nu
mkdir a b c
[ a b c ] | each { cd $in; $env.PWD }
```

Result:
Running this from `/private/tmp`, I get the following:
```
╭───┬──────────────╮
│ 0 │ /private/tmp │
│ 1 │ /private/tmp │
│ 2 │ /private/tmp │
╰───┴──────────────╯
```

### Expected behavior

`cd` should be changing the current directory to each of the three directories I created, so the result should be:

```
╭───┬────────────────╮
│ 0 │ /private/tmp/a │
│ 1 │ /private/tmp/b │
│ 2 │ /private/tmp/c │
╰───┴────────────────╯
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.63.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | macos-x86_64                                    |
| build_target       | x86_64-apple-darwin                             |
| rust_version       | rustc 1.61.0                                    |
| cargo_version      | cargo 1.61.0                                    |
| pkg_version        | 0.63.0                                          |
| build_time         | 1980-01-01 00:00:00 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

Some similar constructs that _do_ work as expected:

```nu
[ a b c ] | each { |dir| cd $dir; $env.PWD }
[ a b c ] | each { let-env PWD = $in; $env.PWD }
```

**Comment by x3rAx** [comment]
I can add that

```nu
[ a b c ] | each { let d = $in; cd $d; $env.PWD }
```

also works.

**Comment by merelymyself** [comment]
It appears `cd $in` just doesn't work at all:

```
~/CodingProjects/nushell〉"./src/" | cd $in                                   07/30/2022 09:49:07 PM
~/CodingProjects/nushell〉                                                    07/30/2022 09:49:10 PM
```

**Comment by Benjamin-L** [comment]
Spent a bit of time poking at this and I think I know what's going on. It looks like the way `$in` is implemented internally is by wrapping expressions that use `$in` in a `collect` statement, and turning `$in` into an explicit variable reference. Looks like this:

``` nu
echo test | some_expr_using $in
// becomes
echo test | collect { |x| some_expr_using $x }
```

or

```
echo test | { some_expr_using $in; something_else }
// becomes
echo test | { collect { |x| some_expr_using $x }; something_else }
```

Problem is, the block passed to `collect` is introducing a new scope, so commands using `$in` will not affect the environment of their scope in the original source.

The wild part is that this transformation is implemented _inside the parser_, and there are two special-case fixes for `let` and `let-env` comamnds _only if they do not occur inside a pipeline_.

The following works:
```nu
$ 〉echo 'test' | each { let-env x = $in; $env.x }
test
```

But this does not:
```nu
$ 〉echo 'test' | let-env x = $in; $env.x
Error: nu::shell::name_not_found (link)

  × Name not found
   ╭─[entry #2:1:1]
 1 │ echo 'test' | let-env x = $in; $env.x
   ·                                     ┬
   ·                                     ╰── did you mean '_'?
   ╰────
```

I'm probably not familiar enough with nushell internals to fix this, but it seems to me like the right approach is to replace the current `collect`-wrapping behavior with something that correctly participates in it's parent's scope in all cases. Extending the existing special cases to cover `cd` and pipelines isn't a good solution, particularly since `def-env` exists and allows arbitrary user-defined commands to participate in the caller environment.

**Comment by Benjamin-L** [comment]
Maybe nushell needs an actual IR transformation pass to do this kind of desugaring :)
