### ISSUE TITLE
Nushell exits when the home partition has "no space left on device"

### ISSUE THREAD

**Issue by x3rAx** [nushell/nushell#6088]
### Describe the bug

I just noticed that nushell exited after I tried to `mv` a file on a disk that has no space left.

It seems like nushell tries to write to the history file and fails because the disk is full.

### How to reproduce

1. Start a `bash` shell (or anything other than nushell)
2. Fill up your home partition using `dd if=/dev/zero of=~/bigfile.bin` until there is no space left on the device.
3. Run `nu`
4. Run `ls`
5. `nu` will list the current directory and then exits with code `1` and the error message:
   ```
   Error:
     × No space left on device (os error 28)
   ```
6. Don't forget to delete the dummy file: `rm ~/bigfile.bin`

### Expected behavior

Nushell should either silently discard the history line (bash does this) or warn the user right before the next prompt (which is where the error is currently shown) that the device has no space left to save the last command to the history file. (I think the second approach is more friendly)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.61.0 (a028ae4 2022-04-29)               |
| pkg_version        | 0.65.0                                          |
| build_time         | 2022-07-08 22:54:42 +02:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

I'm using BTRFS, if that's of any relevance.

**Comment by jntrnr** [comment]
@x3rAx - if you like, we'd be happy to take a PR to warn the user and discard writing to the history file.
