### ISSUE TITLE
`HISTCONTROL` environment variable

### ISSUE THREAD

**Issue by Christopher-S-25** [nushell/nushell#6108]
### Related problem

Setting the `HISTCONTROL` env var does not have any effect in the history list.

### Describe the solution you'd like

Nushell should be able to read the `HISTCONTROL` env var and behave accordingly:
- `let-env HISTCONTROL = "ignorespaces"`: lines which begin with a space character are not saved in the history list.
- `let-env HISTCONTROL = "ignoredups"`: lines matching the previous history entry are not saved in the history list.
- `let-env HISTCONTROL = "ignoreboth"`: alternative to `let-env HISTCONTROL = "ignorespace:ignoredups"`.
- `let-env HISTCONTROL = "erasedups"`: all previous lines matching the current line are removed from the history list before that line is saved in the history list.

### Describe alternatives you've considered

A great alternative would be to include it as an option inside `$nu.config-path`, with pretty much the same values as the `HISTCONTROL` version.

**Comment by fdncred** [comment]
I've never heard of `HISTCONTROL`. Where does it come from? Who uses it? Are these the only options for it?

**Comment by Christopher-S-25** [comment]
Take a look here: https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html

I use `HISTCONTROL = "ignoreboth"` to avoid duplicates in my history, since I tend to run multiple `cargo run --release`, and to run commands that need my password as an argument (I know, bad practice) with a leading space so that they aren't saved in history. It keeps my history nice and clean, and doesn't put me through the hassle of manually removing entries from history.

**Comment by fdncred** [comment]
We don't intend to be bash nor posix compliant. Having said that, we may accept a PR to support something like this. It would need to be implemented for history.txt and history.sqlite3.

**Comment by Christopher-S-25** [comment]
> We don't intend to be bash nor posix compliant.

I'm fully aware of that, and it's the reason why I also suggested the feature as an option inside `$nu.config-path`. I find the feature useful, and I'm willing to implement it myself, but I'm not sure which crate handles the history file.

**Comment by Christopher-S-25** [comment]
After taking a long look at the codebase, it has become obvious that this feature would have to be implemented for `reedline` instead (in `Reedline::handle_editor_event()`), which would take considerably more effort, so I'm closing this issue.

**Comment by benthair** [comment]
**This is the most important option in terms of privacy and security.**

More advanced users don't use a mouse. We don't even use Desktop Environment, but Window Manager (for example, in my case sway. Before the arrival of Wayland, i3wm).

We often work with sensitive data, such as passwords, password generation without key storage, etc. And all this information is omitted from the bash history and other shells by simply inserting a space before the command.

It is essential to implement something similar in nushell.

In bash you can have in-memory history. `HISTFILE=/dev/null`. Every bash instance has its own history. But the mos important feature is the space before command to avoid history.

**Comment by benthair** [comment]
Nushell users must be informed of the security risk involved in using it, as everything is written to disk and will remain there forever (especially nowadays with SSD/NVME disks).

**Comment by weirdan** [comment]
> And all this information is omitted from the bash history and other shells by simply inserting a space before the command.

It works the same way in Nushell.

**Comment by benthair** [comment]
> It works the same way in Nushell.

Yes, I see. Thank you. But still present on the shell history (not history.txt).

To solve it, I'm using: `ln -s /dev/null ~/.config/nushell/history.txt`
