### ISSUE TITLE
in GNOME Console. The directory and currently executing command cannot appear on the title in real time.

### ISSUE THREAD

**Issue by LMFuture-Me** [nushell/nushell#6111]
### Describe the bug

![image](https://user-images.githubusercontent.com/36117602/180647408-309ba206-c1f1-4be2-8cc1-dd18e1223e5c.png)
![image](https://user-images.githubusercontent.com/36117602/180647417-444c868e-0829-4b8d-a36a-3575dbe97389.png)

After I changed the directory. I have to press"Enter" one more time to make current directory appear on the title bar. If I let it execute a command. It won't appear on title bar at all!

( It is GNU version. I just forgot to rename the folder )

I tested FishShell and Zsh. They don't seem to have any problems.

### How to reproduce

1. type "cd TARGET DIRECTORY" on gnome-console

Environment: openSUSE Tumbleweed 20220719
GNOME: 42.3

### Expected behavior

The command that I execute and current directory should be appeared on title bar in real time.

### Configuration

Just the default ( For this. I even reinstalled my system.

**Comment by fdncred** [comment]
I haven't had any problems with it in Mac or Windows. This is where the magic happens if you want to have a look.

https://github.com/nushell/nushell/blob/0812a08bfbccc32a837f88fb7c0f1cb4fc3eca89/crates/nu-cli/src/repl.rs#L326-L331

**Comment by fdncred** [comment]
LOL. It is in the wrong place. I just fixed it. Submitting a PR.
