### ISSUE TITLE
Cannot execute git command to checkout a pull request

### ISSUE THREAD

**Issue by charleschege** [nushell/nushell#6124]
### Describe the bug

Running ` git fetch origin pull/92/head:0.6` on bash shell runs the command successfully, fetching a pull request and storing it in the branch called `0.6` in the command. However, nushell is unable to do this, I have tried adding quotes.

### How to reproduce

Run `git fetch origin pull/92/head:0.6` on nu shell

### Expected behavior

```
❯ git fetch origin pull/92/head:0.6
Error: nu::parser::extra_positional (link)

  × Extra positional argument.
   ╭─[entry #25:1:1]
 1 │ git fetch origin pull/92/head:0.6
   ·                  ────────┬───────
   ·                          ╰── extra positional argument
   ╰────
  help: Usage: git fetch {flags} (repository)
```

**Comment by fdncred** [comment]
I've seen this many times. I wouldn't be surprised if there was another issue. I'm pretty sure it has to do with the custom completions not accommodating all parameters. I typically put a `^` in front when this happens and it fixes the problem. Long term, the git custom completions need to be updated.

**Comment by Kangaxx-0** [comment]
This is because git fetch is being considered as internal command, if you check out `config nu` from terminal, you should see a custom command `extern "git fetch"`, please try to remove it and it should do the magic

**Comment by jansol** [comment]
`git push --force-with-lease` also fails due to the same problem.

**Comment by fdncred** [comment]
Yup, every sub command or parameter that isn't implemented in the nushell custom completions will exhibit this same error.
