### ISSUE TITLE
Environment changes done inside `nu_repl` should not be preserved

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#6144]
### Describe the bug

When calling `cd some-dir` inside the testing `nu_repl()`, it changes the global environment variable in `std::env` which can affect tests relying on current directory (see https://github.com/nushell/nushell/issues/6139).

### How to reproduce

See some hooks and overlay tests that call `cd` and #6139 for an example where it failed some tests.

### Expected behavior

`nu_repl()` should be probably called as a separate process to isolate its environment from the rest of the testing suite.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.1                                          |
| branch             |                                                 |
| commit_hash        | 9695331eed1e50b4170d0389a4ca5a5d39e784cc        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.0 (a8314ef7d 2022-06-27)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.62.0 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.66.1                                          |
| build_time         | 2022-07-27 06:50:49 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | gstat                                           |

**Comment by nibon7** [comment]
I can reproduce this immediately by running `cargo test overlays::add_overlay_from_file_decl_cd`.

```rust
diff --git a/tests/overlays/mod.rs b/tests/overlays/mod.rs
index 91ad5ef66..a0ec343ac 100644
--- a/tests/overlays/mod.rs
+++ b/tests/overlays/mod.rs
@@ -47,7 +47,11 @@ fn add_overlay_from_file_decl() {
 fn add_overlay_from_file_decl_cd() {
     let inp = &[r#"cd samples"#, r#"overlay add spam.nu"#, r#"foo"#];

+    let cwd1 = std::env::current_dir().unwrap();
     let actual_repl = nu_repl("tests/overlays", inp);
+    let cwd2 = std::env::current_dir().unwrap();
+
+    assert_eq!(cwd1, cwd2);

     assert_eq!(actual_repl.out, "foo");
 }
```

**Comment by kubouch** [comment]
Should be fixed by https://github.com/nushell/nushell/pull/6185. nu_repl is now integrated as a testbin and ran as a separate binary.
