### ISSUE TITLE
ls panics when a file or directory not exists

### ISSUE THREAD

**Issue by nibon7** [nushell/nushell#6146]
### Describe the bug

list a file or directory which not exists, ls panics

### How to reproduce

1. ls /a_file_or_directory_not_exists

### Expected behavior

ls should not panic

### Configuration

| key                | val                                      |
| ------------------ | ---------------------------------------- |
| version            | 0.66.1                                   |
| branch             |                                          |
| commit_hash        | 4d6426beab6d57d75c7009c464695f78f49f9d71 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.62.1 (gentoo)                    |
| cargo_version      | cargo 1.62.1                             |
| pkg_version        | 0.66.1                                   |
| build_time         | 2022-07-27 05:42:04 +00:00               |
| build_rust_channel | release                                  |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
what an ugly bug, but it should be pretty easy to fix.
