### ISSUE TITLE
`help` output should be prettier (more colour?)

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#6155]
### Related problem

Compare Nu's `help` command to the help output for the popular [`clap`](https://github.com/clap-rs/clap) library:

<img width="576" alt="image" src="https://user-images.githubusercontent.com/26268125/181345463-3a2f8757-db94-4584-97bd-397a830aca7a.png">
<img width="521" alt="image" src="https://user-images.githubusercontent.com/26268125/181345550-327845b4-2028-4fdf-8022-ded041fcb9ef.png">

`help` is all monochrome, it uses more vertical space, and it's more difficult to visually distinguish sections.

### Describe the solution you'd like

Nu should probably use colour more. And maybe we could condense flag info to a single line (with the aid of colour to help visually distinguish flags from their description).

We're open to other design improvements too, that's just what came to mind.

### Additional context and details

This is probably a good first issue, since it's relatively self-contained. Just reach out here or on Discord if you'd like to work on it!

**Comment by ryand67** [comment]
Hey! I'd be interested in getting involved with the project if this is still available. Thanks!

**Comment by rgwood** [comment]
@ryand67 Yay, thanks! Still available, I'll assign it to you. Just let us know if you have any questions (here or in #implementation-chat on Discord)

**Comment by ryand67** [comment]
Perfect! I'll try and work through it soon. Work is usually pretty light. I'll let you know if I run into any issues!

**Comment by rgwood** [comment]
@ryand67 How's this one going?

**Comment by adam-tokarski** [comment]
@rgwood was it fixed in meantime? 

I've checked that (on main) and seems quite colorful, like
![image](https://user-images.githubusercontent.com/10441317/188123064-5ccd253e-2f7a-4428-aec8-5fcc9c149522.png)

**Comment by rgwood** [comment]
@adam-tokarski Yeah it's looking pretty good now! I think @fdncred was working in this area recently. Let's close this issue.
