### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by lscool66** [nushell/nushell#6160]
### Describe the bug

warning: use `let-env config = ...` instead of `let config = ...`

![image](https://user-images.githubusercontent.com/16486146/181428801-e776895c-6e70-4d98-8961-558760bd78eb.png)

### How to reproduce

Windows打开nu有个警告

### Expected behavior

Windows打开nu有个警告

**Comment by hustcer** [comment]
Edit the config file in `$nu.config-path`, change `let config` to `let-env config`

**Comment by lscool66** [comment]
***@***.*** ***@***.***

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Justin Ma ***@***.***>
发送时间: Thursday, July 28, 2022 1:43:33 PM
收件人: nushell/nushell ***@***.***>
抄送: lscool66 ***@***.***>; Author ***@***.***>
主题: Re: [nushell/nushell] windows (Issue #6160)


Edit the config file in $nu.config-path, change let config to let-env config

―

**Comment by hustcer** [comment]
@lscool66 把 `$nu.config-path` 配置文件里面的 `let config` 改成 `let-env config` 就可以了，通过 `config nu` 命令应该也可以打开这个配置文件的。下次麻烦把版本号带上方便排查问题。谢谢

**Comment by lscool66** [comment]
***@***.***
我按照您的说法修改了配置文件，还是报错

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Justin Ma ***@***.***>
发送时间: Thursday, July 28, 2022 2:40:21 PM
收件人: nushell/nushell ***@***.***>
抄送: lscool66 ***@***.***>; Mention ***@***.***>
主题: Re: [nushell/nushell] windows (Issue #6160)


@lscool66<https://github.com/lscool66> 把 $nu.config-path 配置文件里面的 let config 改成 let-env config 就可以了，通过 config nu 命令应该也可以打开这个配置文件的。下次麻烦把版本号带上方便排查问题。谢谢

―

**Comment by hustcer** [comment]
报的什么错，把错误信息贴出来吧，还有 version 命令结果

**Comment by nibon7** [comment]
这个应该没啥问题，不行就直接把配置文件都删除，重新执行nu会自动创建配置文件 :joy:

**Comment by lscool66** [comment]
有道理，好使了
***@***.***

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年7月28日 19:03
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [nushell/nushell] windows (Issue #6160)


这个应该没啥问题，不行就直接把配置文件都删除，重新执行nu会自动创建配置文件 😂
