### ISSUE TITLE
`mv` usage is different from actual behavior.

### ISSUE THREAD

**Issue by jaeheonji** [nushell/nushell#6164]
### Describe the bug

The basic usage of `mv` is `mv <source> <destination>` 

There is no problem with the command working. However, the options corresponding to the `source` were recently changed from `required` to `rest`.

Basically, for usage, `required` is output first. So the current Usage is output like this:

```
Move files or directories.

Search terms: mv, move

Usage:
  > mv {flags} <destination> ...(source(s))
```

This can be confusing to users.

### How to reproduce

help mv

### Expected behavior

1. `mv {flags} <source(s)> <destination>`
2. Change the order of the actual logic.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.66.2                                   |
| branch             | main                                     |
| commit_hash        | 2ea209bcc02b9faeea0aaec95da61641f18320b8 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.62.1 (e092d0b6b 2022-07-16)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.62.1 (a748cf5a3 2022-06-08)      |
| pkg_version        | 0.66.2                                   |
| build_time         | 2022-07-28 22:32:58 +09:00               |
| build_rust_channel | debug                                    |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

**Comment by nibon7** [comment]
Also `cp` and `mv` :smile:

**Comment by kubouch** [comment]
https://github.com/nushell/nushell/pull/6169 reverted the problematic changes to `cp` and `mv`. Does it work after this PR?

**Comment by jaeheonji** [comment]
@kubouch Yes! It is output normally as intended.
