### ISSUE TITLE
Integration with third party menus

### ISSUE THREAD

**Issue by zim0369** [nushell/nushell#6177]
### Related problem

There is a plugin for the fish shell: https://github.com/PatrickF1/fzf.fish 

That plugin integrates fzf with fish to provide some useful bindings. This is not possible with nushell, at least not comfortably. My many attempts at getting better menus in nushell #5785.

Built-in menus in nushell aren't good enough. They have problems which are discussed in that issue many times.

### Describe the solution you'd like

Integrate fzf or skim in nushell with bindings for better menus such that the menus can be toggled while writing a command and text gets inserted in the prompt where menu was toggled while not tampering the pre-existing text in the prompt. Menu's for directories, files and command history.

The built-in menu for history is bad. It isn't fuzzy. Having fzf or skim there works much better:
```nu
    {
      name: sk_history_menu
      only_buffer_difference: false
      marker: "# "
      type: {
          layout: columnar
          columns: 4
          col_width: 20
          col_padding: 2
      }
      style: {
          text: green
          selected_text: green_reverse
          description_text: yellow
      }
      source: { |buffer, position|
          open -r $nu.history-path | sk -no-sort --tac | str trim
          | where $it =~ $buffer
          | each { |v| {value: ($v | str trim) } }
      }
    }
```

But other menus I made for directories and files don't work well as discussed in #5785

**Comment by fdncred** [comment]
> The built-in menu for history is bad.

That's a little insulting.

**Comment by zim0369** [comment]
> > The built-in menu for history is bad.
> 
> That's a little insulting.

Yea, you could say that but my outrage has some logic to it. I've trying really hard to get menus working really well but I fail miserably everytime. Menus only work fine when used with the built-in one. The built-in menus aren't really cutting it. 

In short I want the exact functionality that this plugin: https://github.com/PatrickF1/fzf.fish
offers for the fish shell.

**Comment by unrelentingtech** [comment]
Looks like #1616 is already an issue about external selectors / fuzzy finders.

The workarounds there use GUI-system-specific things to type the selected history item into the terminal. From a [quick look](https://github.com/PatrickF1/fzf.fish/blob/2bb6f712b0b99fc5cc40ca78b6b3ba8b2529b0f7/functions/_fzf_search_history.fish#L26) at fzf.fish I see that fish has something called `commandline --replace`.

An equivalent of that is what we need to make the history integration smooth and not janky. Trying to use the source of a native menu for the equivalent functionality is also a weird hack. I'm trying to add a `commandline` command now.

**Comment by fdncred** [comment]
@unrelentingtech I've been wanting a commandline type command for a while now. I think it could unlock a new level of cool.

**Comment by zim0369** [comment]
@unrelentingtech #1616 is a similar issue. Not sure why I didn't notice it. I filed this issue after many wasted efforts at #5785 

Honestly, nushell menus aren't good enough except for the part where they match the nushell ui.

**Comment by fdncred** [comment]
The new `commandline` command really helps out here. This command works with `fzf` and skim's `sk` (if you replace the command below with the proper external). It may work with broot too, but i have not tried.
```
    {
      name: fuzzy_history
      modifier: CONTROL
      keycode: char_r
      mode: emacs
      event: {
        send: executehostcommand
        cmd: "commandline (history | each { |it| $it.command } | uniq | reverse | str collect (char nl) | fzf --layout=reverse --height=40% -q (commandline) | decode utf-8 | str trim)"
      }
    }
```

**Comment by zim0369** [comment]
@fdncred Can you please write one similar to the directories menu in fzf which is configured like this:
```fish
fzf_configure_bindings --directory=\cd --history=\ch
```
So hitting `\cd` in nushell would bring up fzf's directory menu?

**Comment by fdncred** [comment]
@zim0369 I'm not sure how that works. Does it list directories in your current pwd only or list them recursively or list them from the / or what?

**Comment by fdncred** [comment]
This is a start
```
    {
        name: fuzzy_dir
        modifier: control
        keycode: char_s
        mode: emacs
        event: {
            send: executehostcommand
            cmd: "commandline -a (ls **/* | where type == dir | get name | to text | fzf -q (commandline) | str trim)"
        }
    }
```

**Comment by zim0369** [comment]
@fdncred I get this error:
```
$config.menus is not a valid list of menus
MissingConfigValue("marker", Span { start: 19044, end: 19400 })
```

**Comment by fdncred** [comment]
@zim0369 It sounds like you may have put it in the `menus:` section instead of the `keybindings:` section of the config.nu?
