### ISSUE TITLE
Pipeline interpolation operator

### ISSUE THREAD

**Issue by wmstack** [nushell/nushell#6179]
### Related problem

Often you want to use the previous command somewhere in a new expression, but it becomes awkward to go back and wrap it in paranthesis. It also does not lend itself to linear shell scripts. For example, appending a string to another string can sometimes be difficult
```nu
(str_producing_command args...) + "text i want to append."
```

is not easy to write if you did not know before reaching the end that there is no prefix operator that can run on this. You can't remove the paranthesis, the `+` operator would instead take the form of an an argument:
```nu
# intending meaning (echo "hello") + " world!"
echo "hello" + " world!"
╭───┬─────────╮
│ 0 │ hello   │
│ 1 │ +       │
│ 2 │  world! │
╰───┴─────────╯
```

### Describe the solution you'd like

While it would be convenient if a command like `str append` was added, and intuitively this would be the method for one to add a string to another string, rather than the infix `+` which is awkward to use in a pipeliny fashion, it doesn't exist and there is a straightforward way to avoid unnecessarily introducing more and more commands:

Introduce a pipeline operator `|>` akin to the one being proposed for javascript ( the hack pipe version, as we already have an F# style pipe for unary functions )

```nu
echo "hello" |> ? + " world!"
```

The `?` assumes the value of the command behind `|>` enabling effective interpolation without paranthesis.

### Describe alternatives you've considered

The alternative is to keep adding commands like `str append` and so on instead of relying on the expression based nature of nushell. This can be useful for the short term, but we need a dedicated syntax to linearize those parantheses. The pipeline operator seems ideal for that use case.

### Additional context and details

This is inspired by the js proposal https://github.com/tc39/proposal-pipeline-operator in particular, about linearizing code and preventing the addition of awkward paranthesis.

**Comment by kubouch** [comment]
We have `$in`. You can do `'hello' | $in + ' world!'`.
