### ISSUE TITLE
Breakage on oh-my-posh due to removal of config setting

### ISSUE THREAD

**Issue by RivenSkaye** [nushell/nushell#6180]
### Describe the bug

Between 0.64 and 0.65, the key `animated_terminal` has been removed from the valid list of options in the Nu config. This causes visual breakage in oh-my-posh (no idea about other terminal decorators) in both mintty with UTF-8 support enabled and in Windows Terminal. This is resolved as soon as a nu receives input, as this seems to force a refresh of both the input line and the powerline above it.
It also happens in a non-MSYS envs, so that's not the problem either

### How to reproduce

Have an oh-my-posh theme.

### Expected behavior

No broken up symbols up top

### Screenshots

![image](https://user-images.githubusercontent.com/14993038/181731071-855edca5-85e0-450e-81d3-98295536adce.png)
![image](https://user-images.githubusercontent.com/14993038/181731122-8b23b185-5e66-4485-9e44-0da9d171b18b.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.0                                          |
| branch             |                                                 |
| commit_hash        | c6cb491e776958696756cd864901810d0ab50ac3        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.62.1 (e092d0b6b 2022-07-16)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.62.1 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.66.0                                          |
| build_time         | 2022-07-26 21:38:44 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
These are the two PRs that removed the animate_prompt and would be a good place to start looking for a fix.

https://github.com/nushell/reedline/pull/451
https://github.com/nushell/nushell/pull/6016

**Comment by zephaniahong** [comment]
Could I claim this issue?

**Comment by fdncred** [comment]
I use oh-my-posh sometimes and can't reproduce this. If it's still an issue, ping me and we can re-open.
