### ISSUE TITLE
Reading nushell history database in v0.65.0 causes error: nu::parser::extra_positional (link)

### ISSUE THREAD

**Issue by devurandom** [nushell/nushell#6182]
### Describe the bug

Following the [example in the v0.65.0 release notes](https://www.nushell.sh/blog/2022-07-05-nushell-0_65.html#unification-continues-elferherrera), I tried to query the nushell SQLite history table:
```
❯ open .config/nushell/history.sqlite3
 history           [table 6871 rows] 
 sqlite_sequence   [table 1 row]     

❯ open .config/nushell/history.sqlite3 | select * | from history
Error: nu::parser::extra_positional (link)

  × Extra positional argument.
   ╭─[entry #20:1:1]
 1 │ open .config/nushell/history.sqlite3 | select * | from history
   ·                                                        ───┬───
   ·                                                           ╰── extra positional argument
   ╰────
  help: Usage: from
```

### How to reproduce

1. Set `config.history_file_format = "sqlite"` in `.config/nushell/config.nu`
2. Start a shell to populate the database
3. Execute `open .config/nushell/history.sqlite3 | select * | from history`

### Expected behavior

All columns and rows of the `history` table should be printed.

### Configuration

❯ version | transpose key value | to md --pretty
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.65.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.0 (gentoo)                           |
| cargo_version      | cargo 1.62.0                                    |
| pkg_version        | 0.65.0                                          |
| build_time         | 2022-07-18 02:03:16 +02:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
@rgwood I think you mentioned this in discord too.

@devurandom For now, I think you need to do `open file | into db | blah`

**Comment by devurandom** [comment]
> @devurandom For now, I think you need to do `open file | into db | blah`

That has unexpected results as well:
```
❯ open .config/nushell/history.sqlite3 | into db | select * | from history
 history           [table 6885 rows] 
 sqlite_sequence   [table 1 row]
 ```

**Comment by fdncred** [comment]
This is working as expected. The sqlite commands are now lazy so in order to materialize results you need to collect.
```
open $nu.history-path | into db | select * | from history | collect
```
Now if you want to see what SQL the pipeline is generating, you can do this:
```
open $nu.history-path | into db | select * | from history | describe
╭────────────┬───────────────────────────────────────────────────────────╮
│ connection │ C:\Users\username\AppData\Roaming\nushell\history.sqlite3 │
│ query      │ SELECT * FROM history                                     │
╰────────────┴───────────────────────────────────────────────────────────╯
```
You could also do it this way:
```
open $nu.history-path | into db | query "select * from history"
```
