### ISSUE TITLE
Support for docker commands

### ISSUE THREAD

**Issue by morilog** [nushell/nushell#619]
Please add plugin for `docker ps` and `docker images` commands

**Comment by waldyrious** [comment]
For the record, `docker ps` and `docker images` (and other similar commands) can now be piped to `from ssv` or `detect columns`, which do a decent job of converting them into native data tables. There are a couple issues with the parsing at the moment (see #4182 and #4183), but those are bugs that should eventually be fixed.

**Comment by melMass** [comment]
Since I landed here from google, I guess others might, you can find a docker module on the [nu_scripts](https://github.com/nushell/nu_scripts/tree/main/modules/docker) repo

**Comment by Marrieto** [comment]
I landed here as well, but I realized I could use `docker ps --format json | from json` for this, create an alias/function for it and you're good to go
