### ISSUE TITLE
Discord invite invalid?

### ISSUE THREAD

**Issue by alxpettit** [nushell/nushell#6192]
Discord invite on mainline README.md takes me to an `invite invalid` page, with no additional information. Not sure if there's something wrong with my account or if it broke at some point recently. :P

**Comment by fdncred** [comment]
https://discord.com/invite/NtAbbGn is the url that is in the readme I believe. it takes me to our server.

**Comment by alxpettit** [comment]
Still doesn't work. 

![image](https://user-images.githubusercontent.com/28266167/181997242-8f0686fb-3948-4430-9f0a-a55d4bfc3453.png)

Looks like the [Discord docs](https://support.discord.com/hc/en-us/articles/360001556852) mention IP banning producing this output. I use a network-wide VPN via Mullvad, with a public IP of `198.54.129.69`. Is it blacklisted? :(

**Comment by fdncred** [comment]
We wouldn't know if a particular VPN has particular IP Addressed denied but it's a good bet that's what's going on.

**Comment by stormasm** [comment]
One other note of interest...

Are you going through the discord client or the web browser ?

I would try them both to see if you get better luck with one of them...

**Comment by alxpettit** [comment]
I was in the 'native' client. Here's the output on the web client:

![image](https://user-images.githubusercontent.com/28266167/182010386-6e21c1b4-dcca-4979-af4d-c85206bfafe1.png)

Unfortunately, not very helpful either :(

**Comment by alxpettit** [comment]
Ooh! It just let me in! :D

**Comment by alxpettit** [comment]
My issue is solved, but I'll leave it open in case it's a special case of some broader configuration issue. Otherwise, feel free to close it. Thankies! ^w^

**Comment by stormasm** [comment]
glad you got it working, I will go ahead and close the issue...  welcome aboard 👍
