### ISSUE TITLE
DB command not found despite building with "--all-features"

### ISSUE THREAD

**Issue by jjpe** [nushell/nushell#6195]
### Describe the bug

I've just built `nu v0.66.2` using `cargo install nu --all-features`.
Despite that, just trying to run the `db` command yields an error:

```
~/〉db -h                                                                                                   07/31/2022 04:37:50 AM
Error: nu::shell::external_command (link)

  × External command
   ╭─[entry #4:1:1]
 1 │ db -h
   · ─┬
   ·  ╰── can't run executable
   ╰────
  help: No such file or directory (os error 2)


```

I also tried the "new way" described [here](https://www.nushell.sh/blog/2022-07-05-nushell-0_65.html#unification-continues-elferherrera), but that errors out equally hard.

What does seem to work is something like this:
``` nu
open /tmp/car.db 
| get Customers 
| where phone_number mod 2 == 0
```
And that's fine by me, but the other ways I described above are extremely confusing.

### How to reproduce

1. Install nushell as above
2. run nushell
3. try to run `db`

### Expected behavior

I didn't expect `db` verbatim to execute successfully, but I did expect the command to be found.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.3                                          |
| branch             | master                                          |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.1 (e092d0b6b 2022-07-16)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.62.1 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.66.3                                          |
| build_time         | 2022-07-31 04:35:07 +02:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by WindSoilder** [comment]
Hi, refer to the pr: https://github.com/nushell/nushell/pull/5838

We no-longer need to execute db commands with `db` prefix

**Comment by fdncred** [comment]
You can also do this to see all the database commands `help commands | where category == database` or `help -f database`

**Comment by rgwood** [comment]
cc @elferherrera 

There have been a lot of changes in database functionality recently and the docs haven't caught up, apologies.

We currently have a lot of different ways to query a SQLite database (too many IMO):

1. Use `open` and regular Nu data commands like: `open foo.db | get table_name | where col == val`
2. Write raw SQL with `query` like `open foo.db | into-db | query "select *..."` or `open-db foo.db | query "select *..."`
    - I am planning to simplify this to `open foo.db | query db "select *..."`
3. Use a special set of Nu commands that map directly to SQL clauses, and build up a SQL query with them: `open-db foo.db | from table_name | where (foo == bar) | select * | collect`
