### ISSUE TITLE
Banner is not displayed on fresh install

### ISSUE THREAD

**Issue by Yethal** [nushell/nushell#6197]
### Describe the bug

On fresh installation using config downloaded from main branch on github nushell displays following error message:
`$config.show_banner is an unknown config setting`

### How to reproduce

1. Install latest nu from github
2. Copy sample config.nu and env.nu to ~/.config/nushell
3. Run nu

### Expected behavior

I expected nu to display banner

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.3                                          |
| branch             |                                                 |
| commit_hash        | 5f11be69ed1bd11bf676345149fdb110271b1181        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-musl                       |
| rust_version       | rustc 1.62.1 (e092d0b6b 2022-07-16)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.62.1 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.66.3                                          |
| build_time         | 2022-07-28 23:16:40 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

Issue can be easily reproduced by runing `docker build -t nushell .; docker run --rm -it nushell` in `docker` dir of this repo

**Comment by fdncred** [comment]
I can't reproduce this. This error message `$config.show_banner is an unknown config setting` happens when an older version of nushell doesn't know about a new config setting. It typically means you're running an old version of nushell, maybe by mistake.

**Comment by Yethal** [comment]
I cloned the entire nushell repo anew, still happens on fresh installation
![image](https://user-images.githubusercontent.com/26117918/182039113-0462e6c2-b95f-4a96-8876-f742292a99c1.png)

**Comment by fdncred** [comment]
That screenshot shows the build time from a few days ago. Is that right? I thought you just built it.

**Comment by Yethal** [comment]
I just downloaded it off of releases page on github

**Comment by Yethal** [comment]
Ok I get it, freshly built 0.66.3 does display the banner properly, it's 0.66.2 (that lies about 0.66.3) that has this problem

**Comment by fdncred** [comment]
This last release had a few problems and then the hot fixes had a few problems.
