### ISSUE TITLE
--suppress-output (-s) of input command filters upper-case letters

### ISSUE THREAD

**Issue by liketechnik** [nushell/nushell#6198]
### Describe the bug

Using the `--suppress-output (-s)` option of the `input` command from #5017 leads to uppercase characters not appearing in the output.

### How to reproduce

```nu
$ echo (input 'Uppercase text: ' -s) # text entered: 'afBG<enter>' or the same text pasted
Uppercase text: af
```

### Expected behavior

The whole text entered appears, i. e. `afBG`.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.62.0                                          |
| branch             |                                                 |
| tag                |                                                 |
| build_os           | linux-x86_64                                    |
| rust_version       | rustc 1.60.0                                    |
| cargo_version      | cargo 1.60.0                                    |
| pkg_version        | 0.62.0                                          |
| build_time         | 1980-01-01 00:00:00 +00:00[^buildTime]          |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

[^buildTime]: This is due to using NixOs's nushell build and obviously not the real build time.

### Additional context

I suspect the problem is how modifier keys are handled https://github.com/nushell/nushell/blob/dd2a0e35f48e36e0648e29438a0b1df13644c2b7/crates/nu-command/src/platform/input.rs#L98-L108 
since usually entering upper-case letters involves the shift key and line 101 filters all characters while a modifier key is pressed.

<hr>

Another observation I made is that even when copy+pasting text containing upper-case letters, those are not included in the output.

**Comment by fdncred** [comment]
Good catch. Thanks for reporting this. I just modified it with this and it seems to work now.
```rust
                            KeyCode::Char(_)
                                if k.modifiers == KeyModifiers::ALT
                                    || k.modifiers == KeyModifiers::CONTROL =>
                            {
                                continue
                            }
```
