### ISSUE TITLE
Starting nushell in some specified directory

### ISSUE THREAD

**Issue by jjpe** [nushell/nushell#6201]
### Related problem

At present It doesn't seem possible to launch nushell with a path argument.

### Describe the solution you'd like

I'd like to be able to do something like `nu -p /some/non/default/path`.
This would have the effect of opening nushell as normal, except it would then `cd` into `/some/non/default/path` before rendering the prompt for the first time.

The use case is that I'd like to set `nu` as the default shell of `zellij` and run it in all tabs, which is already possible.
However, I'd also like each tab to launch at a different FS location. Therefore, the ability to provide that path as an argument when launching nushell would be pretty useful.

### Describe alternatives you've considered

I'm not sure anything else will do - at present there is no solution for what I want to accomplish.
I did try `nu -i -c "cd /some/non/default/path"` but that doesn't work as `-c` exits after executing the nu code.

**Comment by fdncred** [comment]
This is usually a function of the terminal I think. I know I've configured Windows Terminal, kitty, iterm2, etc to start a shell in a specific dir. I'm wondering why zellij doesn't already have that. Having said that, I'm guessing that we'd probably accept a PR for something like this.

**Comment by jjpe** [comment]
> This is usually a function of the terminal I think

The terminal I'm using is alacritty, which doesn't support tabs.
My use of Zellij started out as a way around that, but now I'd like to build that out.
That's also where my desire to start nushell at multiple dirs on my FS comes from.

Zellij does have some [options](https://zellij.dev/documentation/layouts.html#run-plugin-plugin--command-command), but that only provides half the picture. The other half is being able to start the shell from where-ever.

**Comment by jjpe** [comment]
After some reflection it seems best to add a new cli arg, `-e`, which acts a lot like `-c` in that it executes arbitrary code. The main difference would be that nushell doesn't exit after executing that code.

In this case I could just execute `nu - e “cd /some/filesystem/path"` and it would do the expected thing, while also enabling e.g. starting an editor automatically at nushell startup time.

**Comment by CohenAriel** [comment]
If it's OK I'd like to work on that "execute" command.

**Comment by fdncred** [comment]
> If it's OK I'd like to work on that "execute" command.

I asked yesterday if anyone objected to this and no one said they did. So, feel free to try to implement such a thing @CohenAriel.

**Comment by kubouch** [comment]
You can set `PWD` environment variable before running Nushell: `PWD=/foo/bar nu`.

**Comment by jjpe** [comment]
@kubouch That works for setting the current working dir.
It doesn't for executing an arbitrary program on startup, which is what this issue is about.

**Comment by fdncred** [comment]
> You can set `PWD` environment variable before running Nushell: `PWD=/foo/bar nu`.

I can't get this or similar windows-ized things to work in windows

**Comment by kubouch** [comment]
You can do also `with-env { PWD: ... } { nu }`

**Comment by fdncred** [comment]
> You can do also `with-env { PWD: ... } { nu }`

Nice, that works great if you're already running nushell and want a nu in nu experience.

I was trying something like this in pwsh `$env:PWD = "c:\temp"; nu` - maybe there's another way pwsh uses env vars.

**Comment by kubouch** [comment]
`PWD=C:\ nu` works for me from Nushell as well. It doesn't in Powershell but I have no clue how Powershell works.
