### ISSUE TITLE
Suppressing indices per-command

### ISSUE THREAD

**Issue by ehawman** [nushell/nushell#6207]
### Related problem

I want to show certain tables without indices, while keeping them on by default.

Can we pass anything to `tabled` which would allow this?

### Describe the solution you'd like

If we could pass a flag, `-dti` or something, along with our table data, I could do this per-line.

The lowest of the totem pole feature request, as it's 100% cosmetic.

### Describe alternatives you've considered

I've tried:

``` nu
def example_function [param?] {
	let stored = $env.config.disable_table_indexes
	# echo [["disable_table_indexes"]; [$env.config.disable_table_indexes]]
	let-env config = ($env.config | upsert disable_table_indexes true)
	# echo [["disable_table_indexes"]; [$env.config.disable_table_indexes]]
	echo [["Title"]; ["Content"]]
	# echo [["disable_table_indexes"]; [$env.config.disable_table_indexes]]
	let-env config = ($env.config | upsert disable_table_indexes $stored)
	# echo [["disable_table_indexes"]; [$env.config.disable_table_indexes]]
}
```

Those commented-out echoes tell me that disable_table_indexes is being updated properly, but the indices are still showing up.

### Additional context and details

![image](https://user-images.githubusercontent.com/52979227/182199166-7bb356fd-be8f-48de-87b9-2e9ad48f4fd1.png)

**Comment by fdncred** [comment]
I think this has to do with scoping and how the config may not be loaded with each `table` command. I don't think it's related to tabled.

**Comment by weirdan** [comment]
It's now possible with `table -i false`:

```console
$ [[Title]; [Content]] | table -i false
╭─────────╮
│  Title  │
├─────────┤
│ Content │
╰─────────╯
```
