### ISSUE TITLE
`which` capitalizes .exe extension on Windows

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#6208]
### Describe the bug

On Windows, `which` capitalizes path extensions unexpectedly.

### How to reproduce

`which procexp` returns `procexp.EXE`:
```
〉which procexp | get path
╭───┬────────────────────────────────────────────────────────────────╮
│ 0 │ C:\Users\reill\AppData\Local\Microsoft\WindowsApps\procexp.EXE │
╰───┴────────────────────────────────────────────────────────────────╯
```
But the file name is actually `procexp.exe`:
```
〉ls C:\Users\reill\AppData\Local\Microsoft\WindowsApps\proce* | get name
╭───┬────────────────────────────────────────────────────────────────╮
│ 0 │ C:\Users\reill\AppData\Local\Microsoft\WindowsApps\procexp.exe │
╰───┴────────────────────────────────────────────────────────────────╯
```

### Expected behavior

I expect `which` to return file paths with the same casing that exists on disk.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.2                                          |
| branch             | master                                          |
| commit_hash        | 98e199f7b50933104adf42a55eeeec0faeb7f005        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.62.1 (e092d0b6b 2022-07-16)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.62.1 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.66.2                                          |
| build_time         | 2022-07-28 16:07:31 -07:00                      |
| build_rust_channel | debug                                           |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

This is happening in our `which-rs` dependency: https://github.com/harryfei/which-rs/issues/54

This is not a high priority issue but it would be nice to fix it in the underlying crate if they are open to that.

**Comment by PlasmaIntec** [comment]
This behavior is due to dependency `which` using the PATHEXT environment variable to generate path results ([code](https://github.com/harryfei/which-rs/blob/master/src/finder.rs#L161)).

One way to address this is to add a config flag `extension_case` which applies to the result of the `which` calls ([here](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/system/which_.rs#L143) and [here](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/system/which_.rs#L165)).

**Comment by rgwood** [comment]
I do not think we should add a configuration flag for this. Displaying the same case as on the filesystem is the desired behaviour 100% of the time.
