### ISSUE TITLE
Panic when running ls for non-existent directory

### ISSUE THREAD

**Issue by hamza1311** [nushell/nushell#6216]
### Describe the bug

Nushell panics when running ls for non-existent directory.

### How to reproduce

Run 
```nu
ls dir-that-doesnt-exist
```

### Expected behavior

The panic should not occur

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.0                                          |
| branch             | master                                          |
| commit_hash        | c6cb491e776958696756cd864901810d0ab50ac3        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.1 (Arch Linux rust 1:1.62.1-1)       |
| cargo_version      | cargo 1.62.1                                    |
| pkg_version        | 0.66.0                                          |
| build_time         | 2022-07-26 23:09:45 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

Error message:
```
ls dist                                                                                                                02/08 09:32 PM
thread 'main' panicked at 'glob failure: DirectoryNotFound(Span { start: 56987, end: 56991 }, None)', crates/nu-command/src/filesystem/ls.rs:151:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is executed with `RUST_BACKTRACE=1`, I assume the release build doesn't have the symbols to backtrace

**Comment by sholderbach** [comment]
This (#6146) has been patched by the most recent patch releases (`0.66.1` and `0.66.2`). 
The Arch package sources should be up to speed now (https://repology.org/project/nushell/versions)
