### ISSUE TITLE
An operator to execute next command if the previous one exited 0

### ISSUE THREAD

**Issue by skelly37** [nushell/nushell#6218]
### Related problem

Sometimes it is useful to perform a queue of actions, where the commands require a positive result of all the previous ones, e.g. file operations or some permissions stuff.

### Describe the solution you'd like

Basically I'm talking about an equivalent of bash's `\<command1\> && \<command2\>`. 

Introducing `&&` as such operator would be a big plus but not a nessesity.

### Describe alternatives you've considered

Currently it can be handled by 

```nu
<command1>
if $env.LAST_EXIT_CODE == 0 {
  <command2>
}
```

So it is already implemented somehow but like 5 ifs or more make the code harder to read and write. Wrapping this logic around some nice operator like `&&` would greatly enhance the UX, especially in the shell mode.

**Comment by WindSoilder** [comment]
I think it's already implemented, currently, if previous command runs into failed, the following command will never be executed.

I've tried the following nu script as example
```nu
ls soiuffwioqefj
echo done
```

**Comment by fdncred** [comment]
@skelly37 We recently changed to support this behavior with `;`. Such as `command1 ; command2`. Are you saying this doesn't work or you just didn't know about it yet?

**Comment by skelly37** [comment]
> @skelly37 We recently changed to support this behavior with `;`. Such as `command1 ; command2`. Are you saying this doesn't work or you just didn't know about it yet?

Oh, you're both right. Haven't noticed it, my bad, works as you'all say. Closing.
