### ISSUE TITLE
How can I break out of an error-redirected cmd?

### ISSUE THREAD

**Issue by jjpe** [nushell/nushell#6219]
Suppose I have:
```nu
do -c { my-command }
```
A similar story holds for `do -i`.

What I'm noticing is that whenever such a do cmd is executed, nushell just gets stuck.
CTRL-C has no effect either, all I've been able to do so far is restart my entire terminal, or at least nushell.

Assuming that that isn't a bug, how can I break out of this at will?

**Comment by WindSoilder** [comment]
Would you please show what's your `my-command`?  I've tried some commands and can't reproduce your issue

**Comment by jjpe** [comment]
Basically I'm trying to wrap `cargo install <CRATE>+` in it.
The reason for that is that cargo install writes its regular output to stderr rather than stdout, so if I want to incercept its output I don't have much of a choice.

**Comment by WindSoilder** [comment]
I can't reproduce your issue :-(  And I can use CTRL-C to break the operation..

**Comment by jjpe** [comment]
In that case it might be because I'm runningnushell inside of Zellij, which in turn runs in Alacritty. I'm trying to build a stack out of those components, for a superior UX.
It's possible that the signal gets intercepted along the way somewhere. But if that's the case, debugging this will not be so easy.

**Comment by WindSoilder** [comment]
Hi, @jjpe would you please check if it still hold under the latest main?

**Comment by WindSoilder** [comment]
I think this issue can be closed :-)
