### ISSUE TITLE
g without parameter should list like shells command

### ISSUE THREAD

**Issue by yerlaser** [nushell/nushell#6223]
### Related problem

Currently `g` without parameters prints error message.

### Describe the solution you'd like

I think it would be more logical to list shells like `shells` command does.
In that case, `shells` command might not be even needed.

### Additional context and details

As a bonus, would be great if `g -` switches to the shell that was used just before current similar to what `cd -` does.

**Comment by Kangaxx-0** [comment]
Instead of deprecating `shells`, would it be better to merge `g` to `shells` instead? `g` is not an intuitive name for me

**Comment by hustcer** [comment]
I think both g and shells should be kept

**Comment by Kangaxx-0** [comment]
> I think both g and shells should be kept

Then we just change `g` requirement positional to optional and also let it display all shells if nothing specified ?

**Comment by hustcer** [comment]
Yes @Kangaxx-0

**Comment by Kangaxx-0** [comment]
> Yes @Kangaxx-0

Should be straight-forward change, I will work on this during weekend
