### ISSUE TITLE
Shell gets suspended

### ISSUE THREAD

**Issue by herlon214** [nushell/nushell#6240]
### Describe the bug

Bringing the discussion from Discord to here.

I have set some commands on my `PROMPT_COMMAND`:
```
# Prompt
let-env PROMPT_COMMAND = {
    # Zoxide
    # zoxide add -- (shells | where active == true | get path | get 0)

    # Set tmux window title
    # tmux rename-window $"($env.PWD | path basename)"

     # Starship
    ^starship prompt --cmd-duration $env.CMD_DURATION_MS 
}
```
Whenever I run nushell and type some command like `ls` or any command, the shell will get suspended.

@WindSoilder tried to reproduce it, with the 3 commands and the issue didn't happen. Also running 1 command and the issue didn't happen.
Somehow, with two commands there looks like the issue happens. 
On my machine it happens when I run > 1 command.

### How to reproduce

Export `PROMPT_COMMAND` running at two commands on it.

### Expected behavior

Nushell shouldn't get suspended.

### Screenshots

[![asciicast](https://asciinema.org/a/r0eKFP816YJtbdKiWCivHLd4G.svg)](https://asciinema.org/a/r0eKFP816YJtbdKiWCivHLd4G)

### Configuration

```
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.66.3                                   |
| branch             | main                                     |
| commit_hash        | 48f1c3a49efc92f702f5e14b5d7b7e3665bdc804 |
| build_os           | macos-aarch64                            |
| build_target       | aarch64-apple-darwin                     |
| rust_version       | rustc 1.60.0 (7737e0b5c 2022-04-04)      |
| rust_channel       | stable-aarch64-apple-darwin              |
| cargo_version      | cargo 1.60.0 (d1fd9fe2c 2022-03-01)      |
| pkg_version        | 0.66.3                                   |
| build_time         | 2022-08-05 23:22:53 +02:00               |
| build_rust_channel | release                                  |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |
```

### Additional context

The issue doesn't happens if you run on commit 7fc8ff60fdd8ff820e7bcf660355588845eee155.
Looks like it started with 376d22e331630aec4cdd7b3840a7547319afd085.

**Comment by WindSoilder** [comment]
This should be resolved by #6273
