### ISSUE TITLE
Strange `JSON` parsing from `--json` output of the GitHub CLI

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#6248]
### Describe the bug

As discussed briefly in [discussions/6245](https://github.com/nushell/nushell/discussions/6245), i've stumbled upon something when retrieving some `JSON` information from `gh` :open_mouth: 

### Note
`gh repo view amtoine/wallpapers --json nameWithOwner` returns the "_owner/name_" of my _wallpapers_ repo in `JSON` format, i.e.
```json
{ "nameWithOwner": "amtoine/wallpapers"}
```

### The issue
When I run my command and save the result in a `JSON` file, as `gh` gives back valid `JSON`, the result seems to be wrongly parsed...
```rust
$ gh repo view amtoine/wallpapers --json nameWithOwner | save foo.json
$ open foo.json
{"nameWithOwner":"amtoine/wallpapers"}

$ open foo.json --raw
"{\"nameWithOwner\":\"amtoine/wallpapers\"}\n"
```

however, using `| from json |` seems to fix the issue :thinking: 
```rust
$ gh repo view amtoine/wallpapers --json nameWithOwner | from json | save bar.json
$ open bar.json
╭───────────────┬────────────────────╮
│ nameWithOwner │ amtoine/wallpapers │
╰───────────────┴────────────────────╯
$ open bar.json --raw
{
  "nameWithOwner": "amtoine/wallpapers"
}
```

### How to reproduce

1. `gh repo view amtoine/wallpapers --json nameWithOwner | save foo.json`
2. `open foo.json`
3. do not observe a nicely parsed `JSON` table

### Expected behavior

I expected `nu` to give me the same result with either
```rust
 gh repo view amtoine/wallpapers --json nameWithOwner | from json | save bar.json
```
or 
```rust
 gh repo view amtoine/wallpapers --json nameWithOwner | save foo.json
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.3                                          |
| branch             |                                                 |
| commit_hash        | 5f11be69ed1bd11bf676345149fdb110271b1181        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.1 (Arch Linux rust 1:1.62.1-1)       |
| cargo_version      | cargo 1.62.1                                    |
| pkg_version        | 0.66.3                                          |
| build_time         | 2022-07-30 08:08:06 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by amtoine** [comment]
As proposed by @fdncred in [this answer](https://github.com/nushell/nushell/discussions/6245#discussioncomment-3339556), using 
```rust
gh repo view amtoine/wallpapers --json nameWithOwner | save -r foo.json
```
fixes the issue :+1: 

however, is the behaviour without the `save -r` expected? :yum:

**Comment by fdncred** [comment]
What I think is going on is that when you're receiving json from the `gh` command it's already formatted as json. However, nushell sees the `save foo.json` and tries to convert json to json which escapes it.  You can see this if you do `gh repo view amtoine/wallpapers --json nameWithOwner | save foo.txt`. This way the json is saved as it comes from `gh`. The way we get around it is with the `--raw(-r)` parameter to tell nushell not to try and convert json to json.

So, I'm not convinced this is a bug but more of a design choice. Sometimes we want to tell nushell to automagically convert input to json by naming the save file name with .json. Sometimes we just want the preformed json without doing any conversion.

I agree that it's confusing but I'm not sure how to make it better. Ideas welcome.

**Comment by amtoine** [comment]
> What I think is going on is that when you're receiving json from the `gh` command it's already formatted as json. However, nushell sees the `save foo.json` and tries to convert json to json which escapes it. You can see this if you do `gh repo view amtoine/wallpapers --json nameWithOwner | save foo.txt`. This way the json is saved as it comes from `gh`. The way we get around it is with the `--raw(-r)` parameter to tell nushell not to try and convert json to json.
> 
that is crystal clear, thanks a lot :open_mouth: 

> So, I'm not convinced this is a bug but more of a design choice. Sometimes we want to tell nushell to automagically convert input to json by naming the save file name with .json. Sometimes we just want the preformed json without doing any conversion.
> 
that is legit to me no worries, it's just a matter of knowing the feature :wink: 

> I agree that it's confusing but I'm not sure how to make it better. Ideas welcome.
>
me neither for now :confused: 

i'll keep you up to date if something comes to mind in a random moment :muscle:
