### ISSUE TITLE
Unable to echo %"" when using sqlite history_file_format

### ISSUE THREAD

**Issue by Dialga** [nushell/nushell#6251]
### Describe the bug

`echo %""` will cause nushell to panic.

### How to reproduce

1. type `echo ""`
2. backspace twice and type %

`echo %"` also leads to the same panic.

### Expected behavior

No crash.

### Screenshots

```
/tmp: echo thread 'main' panicked at 'byte index 8 is out of bounds of `echo ""`', library/core/src/str/mod.rs:107:9:41:45 AM
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.3                                          |
| branch             |                                                 |
| commit_hash        | 5f11be69ed1bd11bf676345149fdb110271b1181        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.1 (Arch Linux rust 1:1.62.1-1)       |
| cargo_version      | cargo 1.62.1                                    |
| pkg_version        | 0.66.3                                          |
| build_time         | 2022-07-30 08:08:06 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by rgwood** [comment]
Hi, I can't reproduce this. Please include the output of `version | transpose key value | to md --pretty` as requested in the issue template.

**Comment by Dialga** [comment]
Hi, I've updated it.

**Comment by fdncred** [comment]
no issues on Mac. I followed the steps without a panic.

**Comment by rgwood** [comment]
@Dialga Can you try starting Nu with the `RUST_BACKTRACE` environment variable set to 1? That should generate a much more detailed error message that will help us diagnose the issue.

These kinds of completion bugs can be tricky to reproduce because they often depend on specific command history.

**Comment by Dialga** [comment]
> @Dialga Can you try starting Nu with the `RUST_BACKTRACE` environment variable set to 1? That should generate a much more detailed error message that will help us diagnose the issue.
> 
> These kinds of completion bugs can be tricky to reproduce because they often depend on specific command history.

Strangely I'm no longer able to replicate it now..

**Comment by Dialga** [comment]
Actually I can reproduce it again, it's due to my recent config update setting history_file_format to sqlite, % is used in sqlite for wildcard matching.

```
: echo %"thread 'main' panicked at 'byte index 8 is out of bounds of `echo ""`', library/core/src/str/mod.rs:107:9                              08/07/2022 07:06:42 PM
stack backtrace:
   0:     0x56216fbe3a92 - <unknown>
   1:     0x56216ebb7ebc - <unknown>
   2:     0x56216fbdbd61 - <unknown>
   3:     0x56216fbe5705 - <unknown>
   4:     0x56216fbe5439 - <unknown>
   5:     0x56216fbe5d0e - <unknown>
   6:     0x56216fbe5b34 - <unknown>
   7:     0x56216fbe3fa4 - <unknown>
   8:     0x56216fbe589d - <unknown>
   9:     0x56216e73a853 - <unknown>
  10:     0x56216ebbb2a0 - <unknown>
  11:     0x56216ebaeeb7 - <unknown>
  12:     0x56216ebb47f8 - <unknown>
  13:     0x56216e73ab12 - <unknown>
  14:     0x56216fa64cca - <unknown>
  15:     0x56216fa5c8d0 - <unknown>
  16:     0x56216fa598f9 - <unknown>
  17:     0x56216ecde1a4 - <unknown>
  18:     0x56216eca6847 - <unknown>
  19:     0x56216ecae7ed - <unknown>
  20:     0x56216ecab502 - <unknown>
  21:     0x56216fbd41ce - <unknown>
  22:     0x56216eca88c2 - <unknown>
  23:     0x7f9c85085290 - <unknown>
  24:     0x7f9c8508534a - __libc_start_main
  25:     0x56216e78a1b5 - <unknown>
  26:                0x0 - <unknown>
```

**Comment by fdncred** [comment]
I use the sqlite history in nushell and cannot reproduce this behavior. It might be better to compile the latest main in debug mode to get a back trace.
