### ISSUE TITLE
2 quote tests fail on Windows (but not in CI)

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#6252]
### Describe the bug

If I run Nushell tests locally on Windows (Windows 11, v10.0.22000.795), 2 tests fail:

```
failures:
    commands::run_external::double_quote_does_not_expand_path_glob_windows
    commands::run_external::single_quote_does_not_expand_path_glob_windows

test result: FAILED. 631 passed; 2 failed; 18 ignored; 0 measured; 0 filtered out; finished in 3.72s
```

For some reason these tests pass in CI but not on my local machine. ~I'm not sure exactly when this started but it's been happening for months and I'm only getting around to filing an issue now~ (edit: I might have been thinking of another issue)

### How to reproduce

Run `cargo test --workspace --features=extra`, observe tests failing.

### Expected behavior

I expect all tests to pass.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.66.3                                   |
| branch             | main                                     |
| commit_hash        | 34ab4d83600a630b9e7cc89bb25dec1259d5db59 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.62.1 (e092d0b6b 2022-07-16)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.62.1 (a748cf5a3 2022-06-08)      |
| pkg_version        | 0.66.3                                   |
| build_time         | 2022-08-05 21:29:39 -07:00               |
| build_rust_channel | debug                                    |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

### Additional context

```
failures:

---- commands::run_external::double_quote_does_not_expand_path_glob_windows stdout ----
=== stderr
The filename, directory name, or volume label syntax is incorrect.

thread 'commands::run_external::double_quote_does_not_expand_path_glob_windows' panicked at 'assertion failed: actual.out.contains(\"D&D_volume_1.txt\")', crates\nu-command\tests\commands\run_external.rs:226:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library\core\src\panicking.rs:142
   2: core::panicking::panic
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library\core\src\panicking.rs:48
   3: main::commands::run_external::double_quote_does_not_expand_path_glob_windows::closure$0
             at .\tests\commands\run_external.rs:226
   4: nu_test_support::playground::play::Playground::setup<main::commands::run_external::double_quote_does_not_expand_path_glob_windows::closure_env$0>
             at C:\Users\reill\source\nushell\crates\nu-test-support\src\playground\play.rs:128
   5: main::commands::run_external::double_quote_does_not_expand_path_glob_windows
             at .\tests\commands\run_external.rs:213
   6: main::commands::run_external::double_quote_does_not_expand_path_glob_windows::closure$0
             at .\tests\commands\run_external.rs:212
   7: core::ops::function::FnOnce::call_once<main::commands::run_external::double_quote_does_not_expand_path_glob_windows::closure_env$0,tuple$<> >
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3\library\core\src\ops\function.rs:248
   8: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- commands::run_external::single_quote_does_not_expand_path_glob_windows stdout ----
=== stderr
File Not Found

thread 'commands::run_external::single_quote_does_not_expand_path_glob_windows' panicked at 'assertion failed: actual.out.contains(\"D&D_volume_1.txt\")', crates\nu-command\tests\commands\run_external.rs:258:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library\core\src\panicking.rs:142
   2: core::panicking::panic
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library\core\src\panicking.rs:48
   3: main::commands::run_external::single_quote_does_not_expand_path_glob_windows::closure$0
             at .\tests\commands\run_external.rs:258
   4: nu_test_support::playground::play::Playground::setup<main::commands::run_external::single_quote_does_not_expand_path_glob_windows::closure_env$0>
             at C:\Users\reill\source\nushell\crates\nu-test-support\src\playground\play.rs:128
   5: main::commands::run_external::single_quote_does_not_expand_path_glob_windows
             at .\tests\commands\run_external.rs:245
   6: main::commands::run_external::single_quote_does_not_expand_path_glob_windows::closure$0
             at .\tests\commands\run_external.rs:244
   7: core::ops::function::FnOnce::call_once<main::commands::run_external::single_quote_does_not_expand_path_glob_windows::closure_env$0,tuple$<> >
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3\library\core\src\ops\function.rs:248
   8: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ChrisDenton** [comment]
The comments on those tests suggests it fails in cmd but not powershell:

https://github.com/nushell/nushell/blob/c66b97126f71e24a99a2f265b3f5b5420488277d/crates/nu-command/tests/commands/run_external.rs#L201-L212

**Comment by rgwood** [comment]
Thanks, I should have spotted the comments :)

I'm actually running the tests from Nushell, which feels like a use case we should support.

**Comment by rgwood** [comment]
I think that comment might be wrong in some way. I get the same test failures when running `cargo test` from PowerShell (v7 and the old Windows-only version). I'm also not sure I understand how PowerShell would affect this test, given that Nushell should always shell out to `cmd.exe` for `dir` 🤔

**Comment by ChrisDenton** [comment]
Presumably @Kangaxx-0 would have more insight here.

**Comment by rgwood** [comment]
@Kangaxx-0 Are you able to take another look at those tests sometime? I'd like to have the Windows tests running normally again.

**Comment by Kangaxx-0** [comment]
My team is running a big milestone release this month, if this is urgent, I will probably not have time to look at this the rest of this month. 

These two tests does ring a bell to me, I feel like - Some minimal windows SKUs might not use cmd by default, then calling `cmd` , windows will automatically run `ps` for us? Could this be the reason the tests passed from Github CI?

Feel free to disable those two cases if needed

**Comment by rgwood** [comment]
Not urgent but I'd like to get tests passing soon-ish. It looks like the comments were actually written by @vFrankZhang (not sure if that's you).

**Comment by Kangaxx-0** [comment]
> Not urgent but I'd like to get tests passing soon-ish. It looks like the comments were actually written by @vFrankZhang (not sure if that's you).

That's my working account, accidentally set a global setting :)

**Comment by rgwood** [comment]
@Kangaxx-0 I've disabled the tests for now. Can you please take a closer look when you have time? Next month is fine.

If the tests are still useful, we should get them to a point where they pass on a regular Windows install.

**Comment by sholderbach** [comment]
@rgwood I would have to check which tests were affected, but I had local Windows test failures when the developer mode was not activated.

**Comment by rgwood** [comment]
I’ve got developer mode enabled.

**Comment by Kangaxx-0** [comment]
I created a simple test repo on Github, I still do not think the test failure is a code issue, 

```
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        // Try to get version information.
        let mut process = std::process::Command::new("cmd");
        let output1 = process.arg("Get-ComputerInfo").output().expect("Oops!");

        println!("Can I get the version - {:?}",String::from_utf8(output1.stdout));

        // If the shell is `CMD` then command `ls` should return an error
        let mut process = std::process::Command::new("cmd");
        let output2 = process.args(["/D", "/c", "ls"]).output().expect("Should fail to run ls");
        println!("Start to run command ls,stdout - {:?}",String::from_utf8(output2.stdout.clone()));
        println!("Start to run command ls,stderr - {:?}",String::from_utf8(output2.stderr));

        assert!(output2.stdout.is_empty());
    }
}
```

The `ls` should return a stderr, but Github CI returned the result instead.  Rather than these unit tests, I would be more concerned about how the `external` could widely behave differently for local vs Github CI

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/85712372/184511284-f5e147da-6829-4f17-8744-bbc6ecba8535.png">

**Comment by rgwood** [comment]
@Kangaxx-0 Thanks for the investigation! That is very surprising that `cmd /D /c ls` seems to work in GitHub Actions. I agree that this feels like a larger issue than just the unit tests. I'll see if I can find any more info about how GitHub customizes their Windows runners.

FWIW this is what gets printed on one of my Windows 11 machines:

```
Start to run command ls,stdout - Ok("")
Start to run command ls,stderr - Ok("'ls' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n")
```

**Comment by rgwood** [comment]
@Kangaxx-0 Figured it out. Running `where.exe ls` in a GitHub Actions runner returns `C:\Program Files\Git\usr\bin\ls.exe`; it's the Git Bash `ls.exe`

**Comment by Kangaxx-0** [comment]
@rgwood I've done with the release, what can I do for this issue? As you noted, Github windows image is running Git bash instead of `cmd`

**Comment by rgwood** [comment]
> Github windows image is running Git bash instead of `cmd`

I don't think that's quite right; I think it's running `cmd` and the tools from Git Bash just happen to be in the PATH.

I'm not sure whether these tests are still useful; it would be nice if they could be either fixed or deleted.
