### ISSUE TITLE
A way to get current command inside pre_execution hook

### ISSUE THREAD

**Issue by hgigas** [nushell/nushell#6264]
### Related problem

Writting pre_execution hook you haven't access to the command to be executed. History is out dated inside pre_execution hook, then the history command doesn't serve this purpose.

Example:
```
> ls
... ls output ...
> cd directory<RETURN>
```
`pre_execution: [{ print (history | last | get command) }]` shows `ls` not `cd directory` when `<RETURN>`.

### Describe the solution you'd like

Maybe store the current command inside variable `$nu....`. Maybe creating a function that returns current command.

**Comment by kubouch** [comment]
Entries are added to history after the command gets executed, that makes sense to me. What are you trying to achieve?

**Comment by hgigas** [comment]
I don't want change history. Look at the section **Describe the solution you'd like**: Maybe store the current command inside variable $nu..... Maybe creating a function that returns current command.

**Comment by kubouch** [comment]
So when you run a command, like `git status`, before it executes, bash stores "git status" in `BASH_COMMAND` variable?

I wanted to know how you would use this feature. What is the use case?

It seems related to some possible improvements to our external completions. We could store the current line in an environment variable, or pass it to the pre_execution hook as a parameter, as if it were an external completion.

**Comment by hgigas** [comment]
> So when you run a command, like git status, before it executes, bash stores "git status" in BASH_COMMAND variable?
Yes, maybe before or in another thread, I don't known, but don't wait execution.

> I wanted to know how you would use this feature. What is the use case?
For example `trap 'echo -ne "\e]0;"; echo -n "$BASH_COMMAND"; echo -ne "\007"' DEBUG` put current command in terminal title on RETURN press.

**Comment by patricksjackson** [comment]
A common use case for this is in applications that replace the shell history. Because this is a normal feature for most other shells, some of the history replacements require that the command is available before running it.

Basically, they take a `start` signal that contains the cmd about to be run, then an `end` signal so that they collect the exit-code, timings, etc.

atuin, for example: https://github.com/ellie/atuin/issues/487

**Comment by stevenxxiu** [comment]
This would be very useful. I'd like to set the terminal title as the currently running command, but there's currently no way to do that.
