### ISSUE TITLE
input --suppress-output strips uppercase letters from text

### ISSUE THREAD

**Issue by jfmontanaro** [nushell/nushell#6265]
### Describe the bug

If you run `input --suppress-output` and then enter some text including uppercase letters, the returned output will not include those letters.

It only happens with the `--suppress-output` option. Just plain `input` works fine.

### How to reproduce

1. `input --suppress-output`
2. Enter some text including uppercase letters

### Expected behavior

Captured text should match what was typed/pasted in.

### Screenshots

![image](https://user-images.githubusercontent.com/10636404/183471249-6f1194af-a915-4d64-bc2a-e2d17db03926.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.3                                          |
| branch             |                                                 |
| commit_hash        | 5f11be69ed1bd11bf676345149fdb110271b1181        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.1 (e092d0b6b 2022-07-16)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.62.1 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.66.3                                          |
| build_time         | 2022-07-28 23:16:46 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |

Also observed in 0.64.0, which I was running when I discovered the issue. I upgraded to see if that would fix it, but it didn't.

**Comment by fdncred** [comment]
This is fixed in the latest main https://github.com/nushell/nushell/pull/6199
