### ISSUE TITLE
Windows regression: can no longer run batch files without extension

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#6270]
### Describe the bug

This change of mine caused a regression on Windows: https://github.com/nushell/nushell/pull/6253

It's no longer possible to run a batch script named `foo.bat` or `foo.cmd` by typing `foo` without the file extension. Previously this worked because we would always fall back to `cmd.exe` if a command could not be run as a normal executable.

I should be able to fix this up in the next week (hopefully the next few days), using our existing `which` dependency.  I'll also add tests to make sure this doesn't regress again.

### How to reproduce

Try to run `foo` in a directory with a `foo.cmd` batch script:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/26268125/183574141-631c6461-e4e1-41cf-a344-16ff257802fe.png">

### Expected behavior

Running `foo` should run a script named `foo.cmd` or `foo.bat` in the PWD or PATH.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.66.3                                   |
| branch             |                                          |
| commit_hash        | 1ba5b25b29df8c382ed5dad85164bb71f2b64b58 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.62.1 (e092d0b6b 2022-07-16)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.62.1 (a748cf5a3 2022-06-08)      |
| pkg_version        | 0.66.3                                   |
| build_time         | 2022-08-06 11:21:28 -07:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by kubouch** [comment]
I'm pretty sure I was able to run a batch command yesterday without the .bat extension. I can double check later today.
