### ISSUE TITLE
Folder and its contents disappear when using `mv <source> ..` while in a folder with same name as source

### ISSUE THREAD

**Issue by brianloveswords** [nushell/nushell#6275]
### Describe the bug

Hello! I can make a folder and its contents disappear entirely if I try to `mv` it in such a way that it would overwrite the current directory.

### How to reproduce

1. mkdir testdir
2. cd testdir
3. mkdir testdir
4. touch testdir/testfile
5. mv testdir ..

### Expected behavior

Using `/bin/mv`, this would result in `mv: rename testdir/ to ../testdir/: Directory not empty`. 

In nushell, the command completes successfully, but the source *and its contents* goes missing.

### Screenshots

<img width="569" alt="image" src="https://user-images.githubusercontent.com/166258/183725428-f0920f91-fc1e-4ec5-abdf-81adb424c29f.png">

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.3                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | macos-aarch64                                   |
| build_target       | aarch64-apple-darwin                            |
| rust_version       | rustc 1.62.1                                    |
| cargo_version      | cargo 1.62.0 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.66.3                                          |
| build_time         | 2022-07-28 23:07:51 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
isn't this what it's supposed to do?

**Comment by brianloveswords** [comment]
@fdncred I would expect either an error, or for `testfile` to not disappear.

**Comment by brianloveswords** [comment]
I updated the description to hopefully be a bit more clear: in my repro, the problem is not that `testdir/testdir` goes missing, that's expected. The problem is that `testdir/testdir/testfile` goes missing. I'm not sure where it ends up! Does it get deleted?
