### ISSUE TITLE
`split row` and `split column` add regex support

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#6280]
### Related problem

`split row` and `split column` add regex support so they can split multiple chars
We can also add a flag like `-e, --regex                   Use a regular expression as delimiter`

### Describe the solution you'd like

`"a.b-c.d-e-f" | split column '[.-]'` will output:
```
 #     column1
─────────────────
 0   a.b-c.d-e-f
```
The expected output:
```
 #   column1   column2   column3   column4   column5   column6
───────────────────────────────────────────────────────────────
 0   a         b         c         d         e         f
```

### Describe alternatives you've considered

We can use tools like [choose](https://github.com/theryangeary/choose):
```console
"a.b-c.d-e-f" | choose -f '[.-]' 0:
# output: 
a b c d e f
```

### Additional context and details

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.66.3                                              |
| branch             | feature/iter3                                       |
| commit_hash        | 8b55757a0b82fa4fba81feaf70eb0f6e97aaab9c            |
| build_os           | macos-x86_64                                        |
| build_target       | x86_64-apple-darwin                                 |
| rust_version       | rustc 1.62.1 (e092d0b6b 2022-07-16)                 |
| rust_channel       | stable-x86_64-apple-darwin                          |
| cargo_version      | cargo 1.62.1 (a748cf5a3 2022-06-08)                 |
| pkg_version        | 0.66.3                                              |
| build_time         | 2022-08-08 12:50:52 +08:00                          |
| build_rust_channel | release                                             |
| features           | database, dataframe, default, trash, which, zip     |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by fdncred** [comment]
I'd support `--regex (-r)` in these split commands

**Comment by webbedspace** [comment]
What I'm wondering is, shouldn't this command just only take a regex? What benefit is there to having two modes when `str replace` only has the regex mode?
