### ISSUE TITLE
Crash when listing non-existing folder 

### ISSUE THREAD

**Issue by elsaco** [nushell/nushell#6282]
### Describe the bug

- crash when trying to list a non-existent item

### How to reproduce

- run `ls` and some bogus dir name

### Expected behavior

- no crash

### Screenshots

![nu_crash](https://user-images.githubusercontent.com/3933920/183815776-e1911f42-275e-4ee5-90fe-3c9fa76c12a6.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.0                                          |
| branch             |                                                 |
| commit_hash        | c6cb491e776958696756cd864901810d0ab50ac3        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.62.1 (e092d0b6b 2022-07-16)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.62.1 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.66.0                                          |
| build_time         | 2022-07-26 21:38:44 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |

### Additional context

`dir` won't crash:

```
C:\Users\elsaco〉dir c:\Utilities                                                                  08/09/2022 09:16:31 PM
 Volume in drive C is Windows
 Volume Serial Number is A2A2-41FB

 Directory of c:\

File Not Found
```

**Comment by nibon7** [comment]
This issue has been fixed. You can try 0.66.2 or master branch.

**Comment by hustcer** [comment]
Closed by https://github.com/nushell/nushell/pull/6148
