### ISSUE TITLE
`from nuon` cannot parse a table in nuon format

### ISSUE THREAD

**Issue by ixemad** [nushell/nushell#6283]
### Describe the bug

A table in nuon format cannot be parse by `from nuon` command. The nuon parser complains about missing columns.
```
/home/user〉docker images | from ssv | to nuon | from nuon
Error: 
  × error when parsing nuon text
   ╭─[entry #38:1:1]
 1 │ docker images | from ssv | to nuon | from nuon
   ·                                      ────┬────
   ·                                          ╰── could not parse nuon text
   ╰────

Error: 
  × error when parsing
   ╭────
 1 │ [[REPOSITORY, TAG, IMAGE ID, CREATED, SIZE]; ["bitnami/kafka", "latest", "691acc2203ec", "11 months ago", "585MB"], ["bitnami/zookeeper", "latest", "d91e539be199", "11 months ago", "468MB"], ["neo4j", "latest", "539db0bbdf5e", "12 months ago", "571MB"]]
   ·                                              ──────────────────────────────────┬──────────────────────────────────
   ·                                                                                ╰── Missing columns.
   ╰────

```

### How to reproduce

1. Runt he following command
```nu
docker images | from ssv | to nuon | from nuon  
```

### Expected behavior

The same result as in
```nu
docker images | from ssv 
```

### Configuration

〉version | transpose key value | to md --pretty                                                                                                                                                                                                  08/10/2022 10:28:13 AM
| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.66.3                                      |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | linux-x86_64                                |
| build_target       | x86_64-unknown-linux-gnu                    |
| rust_version       | rustc 1.64.0-nightly (1b57946a4 2022-08-03) |
| rust_channel       | nightly-x86_64-unknown-linux-gnu            |
| cargo_version      | cargo 1.64.0-nightly (85b500cca 2022-07-24) |
| pkg_version        | 0.66.3                                      |
| build_time         | 2022-08-04 17:07:04 +02:00                  |
| build_rust_channel | release                                     |
| features           | default, trash, which, zip                  |
| installed_plugins  |                                             |

**Comment by fdncred** [comment]
I think the problem here is that `IMAGE ID` has a space in it and you define columns in Nuon with spaces or commas. You can test this with the error statement above.
This fails
```
[[REPOSITORY, TAG, IMAGE ID, CREATED, SIZE]; ["bitnami/kafka", "latest", "691acc2203ec", "11 months ago", "585MB"]]
```
This passes
```
[[REPOSITORY, TAG, IMAGE_ID, CREATED, SIZE]; ["bitnami/kafka", "latest", "691acc2203ec", "11 months ago", "585MB"]]
```
