### ISSUE TITLE
add http delete option to fetch, or create its own command

### ISSUE THREAD

**Issue by kurokirasama** [nushell/nushell#6300]
### Related problem

it should be equivalente to `curl --request DELETE`

### Describe the solution you'd like

`fetch --delete` or just `delete` equivalent to `curl --request DELETE`

**Comment by ksandvik** [comment]
Recommend a new command for DELETE (and possibly PUT as well) separate from fetch.

**Comment by WindSoilder** [comment]
I'd vote for using them as fetch's arguments

Using as new command `DELETE` and PUT would make user confused, user can think the `delete` command would delete a file rather than http method

**Comment by adamijak** [comment]
@fdncred Can I get assigned? I think I have working sample with `--method` flag.

**Comment by fdncred** [comment]
It's yours @adamijak

**Comment by dandavison** [comment]
I vote for deprecating `fetch`, and introducing a top-level `http` command, with HTTP verbs as sub-commands.

**Comment by sandwoodK** [comment]
> I vote for deprecating `fetch`, and introducing a top-level `http` command, with HTTP verbs as sub-commands.

Might be confusing , when, (I hope), Nushell will supports not only HTTP1.1 but also HTTP2.0, HTTP3.0 (or does it already ? )

**Comment by dandavison** [comment]
@sandwoodK would you suggest adding a `--protocol-version` flag to be explicit about that?

**Comment by Larandar** [comment]
I would also vote for an `http` command that requires a "method" subcommand, but the method SHOULD be arbitrary since the HTTP allow it https://www.rfc-editor.org/rfc/rfc9110.html#name-overviewso `fetch https://example.com` would become `http get https://example.com`.

But reading the RFC I realized that method is case sensitive, so it does complexify the way it should be done...

**Comment by jaudiger** [comment]
This issue has been done with https://github.com/nushell/nushell/pull/8144. I think we can now close it.
