### ISSUE TITLE
Hyperlink files/dirs in ls

### ISSUE THREAD

**Issue by ehawman** [nushell/nushell#6307]
### Related problem

lsd (and I believe exa) provides a config option to add hyperlinks to all `ls` results.

The user may then use whatever their terminal's hyperlink interaction process is to open those links. (Ctrl+Click for Windows Terminal, Cmd+Click for iTerm2, etc) From there you let the OS determine how it wants to handle things.

It's really convenient.

### Describe the solution you'd like

For each file, append `file:///` to the beginning of the file's/dir's full path, URL-encode any wayward characters, and then use that as the URL in the hyperlink.

![image](https://user-images.githubusercontent.com/52979227/184403716-12ccbf46-4565-49c6-8bc1-e067cb1c3d0d.png)

### Describe alternatives you've considered

Just use lsd lol. The problem is that Nushell's tabling is so damn sexy that I don't want to give it up <3

**Comment by fdncred** [comment]
That sounds pretty easy to do, I think but I think it would require ansi escape sequences.

**Comment by fdncred** [comment]
I got this working but I'm not sure we can have colors. That will be something someone would need to check to ensure LS_COLORS still works.
![image](https://user-images.githubusercontent.com/343840/184424136-e6658072-9518-4829-8417-94451a59422e.png)


for a simple test, I just hard coded it in filesystem/ls.rs like this
```rust
    cols.push("name".into());
    vals.push(Value::String {
        val: format!(
            "\x1b]8;;file:///c:/users/username/source/some/path/nushell/{}\x1b\\{}\x1b]8;;\x1b\\",
            display_name.to_string(),
            display_name.to_string()
        ),
        span,
    });
```
