### ISSUE TITLE
Nushell panicked when completion shuffle command 

### ISSUE THREAD

**Issue by eggcaker** [nushell/nushell#6310]
### Describe the bug

try to generate a shuffled a char list, type ``` seq char a z |shuf<press tab here to complete>```  boom

 seq char a z |shufthread 'main' panicked at 'slice index starts at 23 but ends at 18', library/core/src/slice/index.rs:92:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

[code 101 (0x00000065)]

### How to reproduce

typing command ``` seq char a z |shuf<press tab here to complete>```　

### Expected behavior

should be get a shuffled a char list without any issue

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.4                                          |
| branch             |                                                 |
| commit_hash        | 47ef193600f81d99f8125902bd9988d934c9fae7        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | 1.61.0-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.61.0 (a028ae4 2022-04-29)               |
| pkg_version        | 0.66.4                                          |
| build_time         | 2022-08-12 16:48:09 +08:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | query, query json, query web, query xml         |

**Comment by rgwood** [comment]
Hi @eggcaker, I can't reproduce this. I think it might be another bug that's dependent on the user's exact command history.

Can you please run with the `RUST_BACKTRACE` environment variable set to 1 and report the backtrace?

**Comment by fdncred** [comment]
it happens for me every time I try it with my config.nu and env.nu. however, if I try the default config.nu and env.nu there are no issues.

**Comment by fdncred** [comment]
if I comment out `source ~/.zoxide.nu` in my config.nu, I don't have the crash. @eggcaker do you use zoxide and if so can you comment it out to see if it stops crashing for you?

**Comment by eggcaker** [comment]
yes, after comment out zoxide, works now.

**Comment by eggcaker** [comment]
just tested zoxide's configuration
```

# If everything went fine, set a flag that zoxide is initialized to avoid
# recursively calling _OLD_PROMPT_COMMAND
let-env ZOXIDE_INITIALIZED = true # <--- this line crashed 
```

**Comment by fdncred** [comment]
that stuff isn't even in the most recent version of zoxide. that looks like you're running an old version. This is how I changed the current init script. essentially removing the aliases fixed it for me.
```
# Code generated by zoxide. DO NOT EDIT.

# =============================================================================
#
# Hook configuration for zoxide.
#

# Default prompt for Nushell.
let-env __zoxide_oldprompt = (if '__zoxide_oldprompt' in (env).name {
  $env.__zoxide_oldprompt
} else if 'PROMPT_COMMAND' in (env).name {
  $env.PROMPT_COMMAND
} else {
  { $env.PWD }
})

# Hook to add new entries to the database.
def __zoxide_hook [] {
  zoxide add -- $env.PWD
}

# Initialize hook.
let-env PROMPT_COMMAND = {
  __zoxide_hook
  do $env.__zoxide_oldprompt
}

# =============================================================================
#
# When using zoxide with --no-cmd, alias these internal functions as desired.
#

# Jump to a directory using only keywords.
def-env z [...rest:string] {
  # `z -` does not work yet, see https://github.com/nushell/nushell/issues/4769
  let arg0 = ($rest | append '~').0
  let path = if ($rest | length) <= 1 && ($arg0 | path expand | path type) == dir {
    $arg0
  } else {
    (zoxide query --exclude $env.PWD -- $rest | str trim -r -c "\n")
  }
  cd $path
}

# Jump to a directory using interactive search.
def-env zi  [...rest:string] {
  cd $'(zoxide query -i -- $rest | str trim -r -c "\n")'
}

# =============================================================================
#
# Commands for zoxide. Disable these using --no-cmd.
#

# alias z = __zoxide_z
# alias zi = __zoxide_zi

# =============================================================================
#
# Add this to your env file (find it by running `$nu.env-path` in Nushell):
#
#   zoxide init nushell --hook prompt | save ~/.zoxide.nu
#
# Now, add this to the end of your config file (find it by running
# `$nu.config-path` in Nushell):
#
#   source ~/.zoxide.nu
#
# Note: zoxide only supports Nushell v0.61.0 and above.
```

**Comment by eggcaker** [comment]
installed the latest version zoxide (0.8.2) and regenerate configuration for nushell 
```
zoxide  init nushell --hook prompt |save ~/.config/nushell/zoxide.nu
```
source zoxide.nu 
all works.

**Comment by fdncred** [comment]
mine fails with the latest zoxide unless I comment out the aliases
