### ISSUE TITLE
`version` command outputs incorrect version

### ISSUE THREAD

**Issue by skelly37** [nushell/nushell#6318]
### Describe the bug

`version` incorrectly outputs 0.66.3 as nushell's version

### How to reproduce

type `version`

### Expected behavior

I expected `version` to display the actual nu version.

### Screenshots

![Screenshot from 2022-08-13 19-49-40](https://user-images.githubusercontent.com/76530971/184505218-5d31eafe-0866-43d2-be1a-b2c5f137dc34.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.3                                          |
| branch             |                                                 |
| commit_hash        | 5f11be69ed1bd11bf676345149fdb110271b1181        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.1 (Arch Linux rust 1:1.62.1-1)       |
| cargo_version      | cargo 1.62.1                                    |
| pkg_version        | 0.66.3                                          |
| build_time         | 2022-07-30 08:08:06 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by rgwood** [comment]
Thanks for the report! We made a mistake when releasing that hotfix and decided it wasn't worth releasing another hotfix. Version numbers should be consistent in future releases.
