### ISSUE TITLE
``ls`` delimiters are not aligned

### ISSUE THREAD

**Issue by pedoc** [nushell/nushell#6328]
### Describe the bug

``ls`` command, output is not aligned

### How to reproduce

1. Type win+r,run ``nu.exe``
![image](https://user-images.githubusercontent.com/6604230/184566454-5c036810-4a34-43ca-91ef-1e14e7972c73.png)
2. Enter any directory and enter the ``ls`` command,for example ``C:\``
![image](https://user-images.githubusercontent.com/6604230/184566564-69b71af1-b201-4609-a44e-cf8b6d9cd5b1.png)

### Expected behavior

Align correctly

### Screenshots

![image](https://user-images.githubusercontent.com/6604230/184566290-6029f59b-de6e-485b-89cb-b7fd426aecc9.png)

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.66.3                                              |
| branch             |                                                     |
| commit_hash        |                                                     |
| build_os           | windows-x86_64                                      |
| build_target       | x86_64-pc-windows-msvc                              |
| rust_version       | rustc 1.62.0 (a8314ef7d 2022-06-27)                 |
| rust_channel       | stable-x86_64-pc-windows-msvc                       |
| cargo_version      | cargo 1.62.0 (a748cf5a3 2022-06-08)                 |
| pkg_version        | 0.66.3                                              |
| build_time         | 2022-07-29 11:00:49 +08:00                          |
| build_rust_channel | release                                             |
| features           | database, dataframe, default, trash, which, zip     |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by fdncred** [comment]
This looks like a font issue to me but could be something else. I haven't see this issue on Windows but I'll look today again.

**Comment by pedoc** [comment]
Thanks, everything worked fine after I switched to ``Consolas``, it looks like it's a font issue.

This made me have to give up ``Microsoft Yahei Mono`` 😄
