### ISSUE TITLE
Confusing error: `first` on empty inputs

### ISSUE THREAD

**Issue by crides** [nushell/nushell#6330]
### Describe the bug

When using `first` on an empty list, it produces a really confusing error:

```
[] | first
Error: nu::shell::unsupported_input (link)

  × Unsupported input
   ╭─[entry #1:1:1]
 1 │ [] | first
   ·      ──┬──
   ·        ╰── Cannot perform into string on empty input
   ╰────

```

however, nothing is returned when using `last`

### How to reproduce

`[] | first`

### Expected behavior

raise an error like: "can't get the first item from an empty list", or have the same behaviour as `last` (silently return nothing)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.0                                          |
| branch             |                                                 |
| commit_hash        | c6cb491e776958696756cd864901810d0ab50ac3        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.1 (Arch Linux rust 1:1.62.1-1)       |
| cargo_version      | cargo 1.62.1                                    |
| pkg_version        | 0.66.0                                          |
| build_time         | 2022-07-26 23:09:45 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | gstat                                           |

**Comment by fdncred** [comment]
this is probably just a copy and paste error. would be nice to have a better error message.

**Comment by sholderbach** [comment]
I briefly looked into it, the implementations of `first` and `last` also deviate in the handling of `Value::Binary`. But in general we should get consistent behavior in the absence of data.
