### ISSUE TITLE
Quotes passed to programs 

### ISSUE THREAD

**Issue by t-mart** [nushell/nushell#6337]
### Describe the bug

I've encountered a strange bug with argument quoting. I've only been able to observe it when running [`npm run` commands](https://docs.npmjs.com/cli/v8/commands/npm-run-script) for Node/npm, but perhaps other software is effected as well.

The issue is that nushell-quoted arguments passed to `npm run` are being passed to the executable **with those quotations intact**. When quoting things for nushell, my intent is that the quoted content should be passed as a single string argument to the executable, even if it contains whitespace, but importantly, then removing those quotes before passing the string along.

Below, I have provided a reproduction repository. Please try this for yourself.  Here is an example:

```shell
npm run repro "a b c"
# Outputs like:
# [
#   'C:\\Users\\tim\\scoop\\apps\\nodejs\\18.7.0\\node.exe',
#   'C:\\Users\\tim\\code\\nu-quoting\\index.js',
#   '"a b c"'
# ]
```

I would expect the final element of the argument array here to simply be `a b c`.

I have not been able to reproduce this (errant?) behavior with any other programs. For example, with a similar Python script:

```shell
python -c "import sys; print(sys.argv)" "a b c"
# Outputs like
# ['-c', 'a b c']
```

I'm baffled at how this could be happening. I've considered that this was an issue with npm. But, the reason I mostly strongly believe that this is a Nushell problem is that this behavior does not occur under any other shells I've tried, specifically Powershell and bash.

### How to reproduce

1. Clone my [reproduction repository](https://github.com/t-mart/nu-quoting) with `git clone https://github.com/t-mart/nu-quoting.git` and then `cd` into it.
2. Follow the `README.md` provided (i.e. have `node` and `npm` installed, run listed commands).
3. Scruntinize output.

### Expected behavior

I expected the passage of whitespace-containing arguments to programs without quotes (despite them being quoted in the nushell command).

### Screenshots

![nushell](https://user-images.githubusercontent.com/200012/184952806-dc23916d-2d52-4c79-8681-07776d0ad54f.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.3                                          |
| branch             | master                                          |
| commit_hash        | 5f11be69ed1bd11bf676345149fdb110271b1181        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.62.1 (e092d0b6b 2022-07-16)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.62.1 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.66.3                                          |
| build_time         | 2022-07-28 23:20:39 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by t-mart** [comment]
(Sorry for all the edits above -- I accidentally submitted the report before I was ready.)

As another datapoint, here's a similar one-liner for node that **does not** exhibit the behavior:

```shell
node -e "console.log(require('node:process').argv)" "a b c"
```

**Comment by t-mart** [comment]
Was not able to reproduce in an Ubuntu Docker container. Perhaps something Windows specific.

**Comment by ChrisDenton** [comment]
Is npm a bat file on Windows? That might explain why it works for some applications but not others.

**Comment by t-mart** [comment]
> Is npm a bat file on Windows?

Indeed, it is. `which pnpm` yields `C:\Users\tim\scoop\apps\nodejs\18.7.0\pnpm.CMD` which has these contents: <https://github.com/npm/cli/blob/latest/bin/npm.cmd>

I believe these batch files act like shims, which call another executable with specific arguments (e.g. `npm` turns to something like `node npm-cli.js`). I tried cutting out this middle man and simply running:

```shell
node ~\scoop\apps\nodejs\18.7.0\node_modules\npm\bin\npm-cli.js run repro "a b c"
```

and it worked without the extraneous quotes.

The shims seem to be created by [npm's cmd-shim](https://github.com/npm/cmd-shim). I should probably take my issue up there. But it's still curious that only Nushell is producing this problem, while Powershell and cmd.exe do not.

Just to help me file the report there, any ideas why?

**Comment by mediumrarez** [comment]
It's not just `npm`. I've been able to reproduce this with Python as well. It only occurs if you run the script through its file type association rather than `python.exe`.

![demo](https://user-images.githubusercontent.com/59168253/202354246-8311f0e9-7172-4a7e-acbb-7af92d15a092.gif)

**Comment by t-mart** [comment]
I never did get this figured out.

Is this worth re-opening?

**Comment by mediumrarez** [comment]
@t-mart My vote's on re-opening.

**Comment by t-mart** [comment]
This problem still persists in 0.74.0.

**Comment by WindSoilder** [comment]
Maybe it's only happened on windows.
<img width="657" alt="img" src="https://user-images.githubusercontent.com/22256154/212098323-c83d6d4d-ab32-46d0-b1df-cc2bebd9dc57.png">

**Comment by rgwood** [comment]
Yes, it looks like this is a Windows-only bug. For "regular" commands, we remove quotes from arguments:

https://github.com/nushell/nushell/blob/54dd65cfe10ae29b55e6f58368de7802376415c4/crates/nu-command/src/system/run_external.rs#L589

I believe we're (incorrectly) neglecting to do so when we launch things (like batch scripts) via `cmd.exe`. I'll see if I can get this fixed.
