### ISSUE TITLE
Config command ideas.

### ISSUE THREAD

**Issue by andrasio** [nushell/nushell#634]
`config` [coverage](https://github.com/nushell/nushell/pull/633) was quite something and brought some usage questions. To aid in test harness a `--load` flag was introduced. 

At the moment, when running, say `> config --load some_file.toml --set [feature arepa]` Nu will load in memory and use that configuration file and write there instead of the default `config.toml` for that specific pipeline call.

This means that whenever `--load` is used Nu will read and write to that configuration file instead and further calls to `config` without passing the load flag will still use the default `config.toml` for reading/writing configuration data.

Perhaps introducing a `--merge` flag could be used as well. In other shells, users share their dotfiles. Maybe if users share their configuration files we could do something like `> config --load other_user_conf.toml --merge` and Nu could merge the information with the default one.

**Comment by wycats** [comment]
@androbtech I think the approach we use in Cargo, which is to allow a hierarchy of configuration through the directory hierarchy, is a good idea.

We could still fall back to the location in the `dirs` crate, but search the directory hierarchy first.

We should also consider the "shared dotfiles" question directly. It's a very common workflow and it would be great to build something in (imagine if you could point your config at a github repo or gist and nu would just get it for you).

**Comment by andrasio** [comment]
#900
