### ISSUE TITLE
winget creation failed again

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#6341]
### Describe the bug

With the 0.67 release winget creation failed again. I've really about had my fill with winget not working.
https://github.com/nushell/nushell/actions/runs/2872958700

### How to reproduce

run winget ci

### Expected behavior

success

### Configuration

|key|value|
|-|-|
|version|0.67.0|
|branch|main|
|commit_hash|33674d3a98dd7510a4e4784c079dfdaecfd2e0d6|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.61.0 (fe5b13d68 2022-05-18)|
|rust_channel|1.61.0-aarch64-apple-darwin|
|cargo_version|cargo 1.61.0 (a028ae42f 2022-04-29)|
|pkg_version|0.67.0|
|build_time|2022-08-16 13:42:18 -05:00|
|build_rust_channel|release|
|features|database, dataframe, default, trash, which, zip|
|installed_plugins|custom-value generate, custom-value generate2, custom-value update, from parquet, gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml|

### Additional context

/cc @TechWatching @OfficialEsco

**Comment by hustcer** [comment]
https://github.com/nushell/nushell/runs/7866361476?check_suite_focus=true
The binary release action failed for creating windows msi file:
```
C:\agent\_work\66\s\src\ext\UIExtension\wixlib\LicenseAgreementDlg.wxs(27) : error LGHT0311 : A string was provided with characters that are not available in the specified database code page '1252'. Either change these characters to ones that exist in the database's code page, or update the database's code page by modifying one of the following attributes: Product/@Codepage, Module/@Codepage, Patch/@Codepage, PatchCreation/@Codepage, or WixLocalization/@Codepage.
Error[1] (Command): The 'light' application failed with exit code = 311
```
It works well before, but not work after v0.66, what happend?

**Comment by OfficialEsco** [comment]
Naaaah brother this is not caused by WinGet in any way.
It says the url(s) is missing.
0.66.1, 0.66.2 and 0.67.0 does not contain any .msi's

^ hustcer knows 😎

**Comment by hustcer** [comment]
I know it failed due to does not contain any .msi's, but why msi creation failed?

**Comment by fdncred** [comment]
Windows-1252 is a valid code page. Not sure why it seems to be whining about it. The wix file hasn't changed that I know of.

**Comment by fdncred** [comment]
@hustcer I see 3 places 1252 is used in the main.wxs file. we can change these to UTF-8 if you think that would fix it. i'm not sure why it fails now when it's been working all along, unless the cargo-wix binaries have changed?

**Comment by fdncred** [comment]
Thanks @OfficialEsco for the tip. Sorry to bother you. Thanks for your continued support of us. :)

**Comment by hustcer** [comment]
I will try it later in my own release testing repo

**Comment by hustcer** [comment]
> @hustcer I bet it's the language changes to not allow dashes

I don't think so we are using an older version for release

**Comment by fdncred** [comment]
@hustcer i just tested and fixed it on my local machine by changing the release-pkg.nu and changing the License.rtf file.
In line 146 of release-pkg.nu i changed $blank-line to $blank_line
In License.rtf, someone had modified it to not include the code page and a few other things.

Do you want me to PR these changes or wait for you to fix it?

**Comment by hustcer** [comment]
@fdncred Yeah, you can give it a try, and let's see it works or not, BTW: the release pipeline use nu v0.63.0: https://github.com/nushell/nushell/blob/2ef9cc118e7cd98341f93eb8f30a45b4051b3c98/.github/workflows/release.yml#L75

**Comment by fdncred** [comment]
ok, i'll make a PR just for the License.rtf then.

**Comment by fdncred** [comment]
@hustcer Do you have some way to retrigger the wix script in order to create another winget package? I'm not sure how to do it.

**Comment by hustcer** [comment]
> @hustcer Do you have some way to retrigger the wix script in order to create another winget package? I'm not sure how to do it.

There is no shortcut, I think I can find a way to do it in a hack way later
