### ISSUE TITLE
How to set a default value when selecting a value that may not exist?

### ISSUE THREAD

**Issue by janosimas** [nushell/nushell#6342]
### Question

I want to select a value in a json but the value may not exist.
In that case I'm getting the error: `Data cannot be accessed with a cell path`.

How can I set a fallback value if the select fails?

### Additional context and details

Example of an existing value:
```nu
'{ "a": { "b": 2 }  }' | from json | select a.b
```

Example of an non-existing value:
```nu
'{ "a": null  }' | from json | select a.b
```

**Comment by kubouch** [comment]
There is no super ergonomic way to do this yet but you can use `get -i` and `default`. 

Something like `'{ "a": null  }' | from json | select a | get -i b | default foo`.

**Comment by janosimas** [comment]
It's not perfect but will help a lot, thanks!

Is there any reason for not having `-i` in `select`?
