### ISSUE TITLE
Custom `config.nu` location doesn't change `$nu.config-path`

### ISSUE THREAD

**Issue by darwis059** [nushell/nushell#6344]
### Describe the bug

in windows, starting nu with `--config <custom-config-location>`  doesn't change  `$nu.config-path` to custom config path.

### How to reproduce

1. run nu with custom config location `nu.exe --config <custom-config-location> --env-config <custom-env-location>`
2. type `$nu.config-path` in nushell

### Expected behavior

the result of `$nu.config-path` should be the path of custom config.nu

### Screenshots

![image](https://user-images.githubusercontent.com/7157397/185160114-c7f8f5eb-5f50-431c-bf82-6b5bea3ab2a3.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.0                                          |
| branch             |                                                 |
| commit_hash        | 33674d3a98dd7510a4e4784c079dfdaecfd2e0d6        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.67.0                                          |
| build_time         | 2022-08-16 20:28:43 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
sounds like a bug
