### ISSUE TITLE
No effect when executing `carapace _carapace nushell | save '/tmp/carapace.nu'` in config.nu

### ISSUE THREAD

**Issue by flying-sheep** [nushell/nushell#6346]
### Describe the bug

I see

```
Error: nu::parser::sourced_file_not_found (link)

  × File not found
     ╭─[/home/phil/.config/nushell/config.nu:106:1]
 106 │ carapace _carapace nushell | save '/tmp/carapace.nu'
 107 │ source /tmp/carapace.nu
     ·        ────────┬───────
     ·                ╰── File not found: /tmp/carapace.nu
 108 │ 
     ╰────
  help: sourced files need to be available before your script is run
```

### How to reproduce

Added the lines

```nu
carapace _carapace nushell | save '/tmp/carapace.nu'
source /tmp/carapace.nu
```

to <samp>config.nu</samp>.

### Expected behavior

Saves the output of the command.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.0                                          |
| branch             |                                                 |
| commit_hash        | 33674d3a98dd7510a4e4784c079dfdaecfd2e0d6        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.63.0 (Arch Linux rust 1:1.63.0-1)       |
| cargo_version      | cargo 1.63.0                                    |
| pkg_version        | 0.67.0                                          |
| build_time         | 2022-08-16 22:50:03 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | from parquet                                    |

### Additional context

If I execute the command manually, it works.

**Comment by kubouch** [comment]
The `/tmp/carapace.nu` file must exist at parse time, that is, before the `config.nu` is run. One solution would be to put `carapace _carapace nushell | save '/tmp/carapace.nu'` to `env.nu`.

**Comment by flying-sheep** [comment]
Is that documented somewhere?

**Comment by kubouch** [comment]
Yes, here: https://www.nushell.sh/book/thinking_in_nu.html#think-of-nushell-as-a-compiled-language.

Btw, there is a PR that enables external completers which will make carapace integration easy: https://github.com/nushell/nushell/pull/6295

**Comment by flying-sheep** [comment]
Ah, wonderful, thank you!
