### ISSUE TITLE
Unicode characters coming from powershell are being replaced when they go through a nu pipe ( on windows )

### ISSUE THREAD

**Issue by PizzaKirby** [nushell/nushell#6349]
### Describe the bug

Running `pwsh -noprofile -c "Write-Host ©" | debug -r` replaces the unicode character after going through a pipe. `pwsh -noprofile -c "Write-Host ©"` works as you'd expect.

character examples:

  - © -> "c"
  - ☘ -> "?"
  - ¢ -> Binary { val: [155, 13, 10,], span: Span { start: 57102, end: 57106, },}
  - ¥ -> Binary { val: [155, 13, 10,], span: Span { start: 57102, end: 57106, },}

### How to reproduce

1. Have Windows Powershell or Powershell Core installed
2. run `pwsh -noprofile -c "Write-Host ©" | debug -r` ( replace `©` with any unicode character you like )

### Expected behavior

I expected nu to properly preserve unicode characters coming from powershell.

### Screenshots

<details>
  <summary>☘ conversion</summary>

![WindowsTerminal_t1fAlsPtLS](https://user-images.githubusercontent.com/13819824/185239178-460fac81-8dcd-4bae-9b4c-296206ace28b.png)
  </summary>
</details>
<details>
  <summary>© conversion</summary>

![WindowsTerminal_hhnP9e1zQG](https://user-images.githubusercontent.com/13819824/185239415-7401409e-360b-4221-b361-73592677091f.png)

  </summary>
</details>
<details>
  <summary>¥ conversion</summary>

![WindowsTerminal_nRSodC3h5j](https://user-images.githubusercontent.com/13819824/185239756-8780e987-97ae-4178-8765-753d887f9c3b.png)

  </summary>
</details>
<details>
  <summary>expected / without pipe</summary>

![WindowsTerminal_MoVnwQPAun](https://user-images.githubusercontent.com/13819824/185240016-3e23e4ac-5ddd-45cc-9034-bd4f33e953af.png)

  </summary>
</details>

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.0                                          |
| branch             | main                                            |
| commit_hash        | e614970c084dce157d02e065eeaf78b29b5fb210        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | 1.61.0-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)             |
| pkg_version        | 0.67.0                                          |
| build_time         | 2022-08-17 19:44:26 +02:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

I have tested and found this behaviour...

- on Windows 10 / 11 ( win11 in the official Developer VM for VirtualBox )
- using alacritty and Windows Terminal
- using Fira Code NF, Cascadia Code NF and Consolas fonts
- using default configs and my own
- with and without history

I couldn't test if this also occurs on linux.

edit: It also seemed to work correctly with a fresh clone, build and run from within the same terminal session, but not anymore after restarting it.

**Comment by rgwood** [comment]
Thanks 🍕 Kirby for the detailed bug report!

My total guess is that maybe it's a text encoding issue. I can take a closer look at this next week if nobody else gets a chance before then.

**Comment by fdncred** [comment]
This problem doesn't seem to exist on Mac.
<img width="889" alt="Screen Shot 2022-08-17 at 6 36 48 PM" src="https://user-images.githubusercontent.com/343840/185261882-7ca56f5a-1562-4a8a-a965-aa61d72cda12.png">

I agree about decoding. I wonder what happens with that command without the debug but `| decode utf-16le` or `be` based on the processor

**Comment by rgwood** [comment]
Trying a few things (Windows Terminal Preview, Windows 11, Nu v0.67 from the latest `main`):
![image](https://user-images.githubusercontent.com/26268125/185262654-9a3fd80f-a659-4613-81af-8bbb53a87237.png)

**Comment by fdncred** [comment]
It could also be a factor of fonts substituting chars that don't exist. Piping to into binary should show encoding I think. Well, not the encoding per se but if it's a odd multi byte character.

**Comment by fdncred** [comment]
I think I just figured this out. I always seem to forget about this but when I was debugging I noticed that my terminal was set to the wrong code page (437) and was printing `c`. So, I changed it to UTF-8 which is code page 65001. Once I did that, everything worked. You can test this out with `chcp 437` and see it print `c` and then change it to UTF-8 with `chcp 65001` and see it print `©`.

![image](https://user-images.githubusercontent.com/343840/185400849-bf4134a3-28ff-45b8-9d86-93c1a7ff034a.png)

**Comment by fdncred** [comment]
I also [made this change](https://superuser.com/a/1435645) in hopes that I never have to set the code page again.

**Comment by PizzaKirby** [comment]
> I think I just figured this out. I always seem to forget about this but when I was debugging I noticed that my terminal was set to the wrong code page (437) and was printing `c`. So, I changed it to UTF-8 which is code page 65001. Once I did that, everything worked. You can test this out with `chcp 437` and see it print `c` and then change it to UTF-8 with `chcp 65001` and see it print `©`.

This seems to have solved it for me. 👍

**Comment by fdncred** [comment]
yay!

**Comment by rgwood** [comment]
Nice one @fdncred.

As a feature for later, I wonder if we can make this work with the default code page.

**Comment by fdncred** [comment]
> As a feature for later, I wonder if we can make this work with the default code page.

The [default code page](https://en.wikipedia.org/wiki/Code_page_437) has a pretty limited amount of characters. Those may work but I suspect that others won't.

**Comment by rgwood** [comment]
Ah OK. I don't have a complete understanding of this issue; I'm not 100% sure what the code page affects.

Nu is able to output emoji and all kinds of Unicode characters without changing the code page; is the issue that Powershell checks the code page when deciding what to output? Or is the terminal itself changing its behaviour based on the code page?

(don't feel like you need to answer that if you're not sure)

**Comment by fdncred** [comment]
@rgwood I'm not sure how Windows determines exactly what to do.  I've just ran into this problem before and it finally clicked with me that we needed to change the code page. Here's some of Microsoft's documentation on code pages if you want to research it further https://docs.microsoft.com/en-us/windows/win32/intl/code-pages.
