### ISSUE TITLE
Variable not expanding when used with commands with options without spaces (eg. 7zip)

### ISSUE THREAD

**Issue by MichelMunoz** [nushell/nushell#6352]
### Describe the bug

Some commands have option with arguments where the argument value is not separated by a space, ex. the "-o" :
`7z x ($env.SOME_ARCHIVE_PATH) -o($env.DEPLOY_DIR)`

In that case the variable is not "expanded" (substituted with its value).
I suspect it is because of the absence of space between the option and the value of the argument of the option ("-o" here imposes that, no other way around unfortunately). The expansion works for commands where there is a space (eg. tar -C somepath)

### How to reproduce

1. define some archive file path in a env variable SOME_ARCHIVE_PATH
2. define some directory path in an env variable DEPLOY_DIR
3. run `7z x ($env.SOME_ARCHIVE_PATH) -o($env.DEPLOY_DIR)`
4. the first variable is expanded (after "x"), the second is not (after "-o"), leading to 7zip creating a directory named `($env.DEPLOY_DIR)` instead of the variable value.

### Expected behavior

Variable expansion.

### Configuration

tested in linux, nushell 0.67.0

**Comment by kubouch** [comment]
You need to use a string interpolation to expand the -o string: `$"-o($env.DEPLOY_DIR)"`

**Comment by MichelMunoz** [comment]
Thank you for the answer, indeed this is a workaround, sorry for my delay in acknowledging it.

I checked in the documentation (the book) and nowhere there seems to be a description of when a variable (`$somevar`) or subexpression (`(some code)`) are interpreted or not.
Apparently (my use case) not being prefixed by a space character is a case of "not interpreted".
Are there any other cases to be aware of ?

Maybe this ticket should just be a documentation issue, to add the answer to the documentation (hte book) ?

**Comment by weirdan** [comment]
This works now:

```console
$ let a = "bbb"
$ ^echo -o($a)
-obbb
```

**Comment by sholderbach** [comment]
Have to admit I have mixed feelings about this behavior (#13602) but yes we now interpolate pretty liberally for unquoted words. (I can't remember listening in on any discussion that actively endorsed it)
