### ISSUE TITLE
[0.67] [Windows] CMD.exe internal commands no more recognized and throwing errors/breaking scripts

### ISSUE THREAD

**Issue by Stefouch** [nushell/nushell#6359]
### Describe the bug

Hi there!

Since v0.67 and [Windows cmd.exe changes](https://www.nushell.sh/blog/2022-08-16-nushell-0_67.html#windows-cmd-exe-changes-rgwood) and #6253, common Windows CMD commands cannot be run within Nushell anymore.

Although I understand the will to handle errors in a better way, the previous release allowed Windows users to easily merge both shells' commands within their script which was very handy (read: now with the introduced change all my scripts are broken).

I did not find alternatives to `title`, `echo.`, nor `pause` (see below).

IMO, I found `cd..` and `cls` easier to type than `cd ..` and `clear`.

Also, the escape prefix `^` does not work.

### How to reproduce

1. Type one of the following commands in a Nushell under Windows — they return an error;
```cmd
title "My Window"
echo.
cd..
pause
cls
```

2. Escaping with the prefix `^` does not work. 

### Expected behavior

`title "My Window` → Changes window title
`echo.` → Prints a linebreak
`cd..` → Navigates to the upper folder
`pause` → Pauses script execution
`cls` → Clears the window

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.0                                          |
| branch             |                                                 |
| commit_hash        | 91976988f032276ca48faff2d1ac13c079eda836        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.67.0                                          |
| build_time         | 2022-08-17 15:20:56 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

Maybe add more exception in https://github.com/rgwood/nushell/blob/00bace9e82d3f3e3e337c510ce6cef0818ade7aa/crates/nu-command/src/system/run_external.rs#L134

Creating aliases is NOT, imho, the best solution for users who work on multiple workstations and which would require an extra step/third party program to sync config files.

**Comment by fdncred** [comment]
which cmd.exe internal built-in commands are your proposing we reinstate? I'm not sure if this is a complete [list](https://ss64.com/nt/syntax-internal.html) of built-in commands but it's a good start.

**Comment by rgwood** [comment]
Hi, we're open to adding more commands to the list of exceptions. I'd like to avoid reinstating the old behaviour where everything fell back to `cmd.exe`.

#### `title`
When I [tried this from an older version of Nu](https://1drv.ms/x/s!ApnCVOIY9OCytk7MK8PmJoxngdxP?e=epjHF1) it wasn't working properly in Windows Terminal. Was it working for you (maybe in other contexts)?

#### `echo` and `cd`
I would prefer to _not_ add these to the exception list. `echo` and `cd` are fundamental Nushell commands, I think we need a really strong reason to have different behaviour for them on Windows.

#### `pause` and `cls`
I'd be OK adding these to the exception list.

**Comment by rgwood** [comment]
(also, sorry for the breaking change - our lack of telemetry means it's hard to know which features are relied on)

**Comment by kubouch** [comment]
I don't think we should support cmd.exe built-ins because every shell has some built-ins. You can always do `bash -c ...` or `cmd /C ...`. If there is some functionality that would be beneficial to Nushell, we can add it to Nushell, but I'd prefer not having a list of exceptions that would shell out to cmd.exe (or any other shell), unless it's something absolutely fundamental and necessary.

**Comment by CAD97** [comment]
For comparison, in `pwsh`,

| command | result |
| - | - |
| `title` | not recognized |
| `echo.` | not recognized |
| `cd..` | works |
| `pause` | works |
| `cls` | works |

I can second that I use `cls` rather than `clear`. However, I agree with @kubouch that nushell is a different shell. It makes sense to allow *some* to pass through... but these should also be implemented on other OSes. Ideally, the behavior in nushell should be 100% portable between host OSes, and never rely on passthrough to the "host shell."

**Comment by CAD97** [comment]
I just went through the list of cmd builtins and made a translation table like is provided for bash: https://github.com/nushell/nushell.github.io/pull/567

**Comment by Stefouch** [comment]
> #### `title`
> When I [tried this from an older version of Nu](https://1drv.ms/x/s!ApnCVOIY9OCytk7MK8PmJoxngdxP?e=epjHF1) it wasn't working properly in Windows Terminal. Was it working for you (maybe in other contexts)?

I agree that it was not working properly, always showing the new window's name with quotes `"..."`. I did not find a way to remove the quotes.

> #### `echo` and `cd`
> I would prefer to _not_ add these to the exception list. `echo` and `cd` are fundamental Nushell commands, I think we need a really strong reason to have different behaviour for them on Windows.

Totally understandable.
Though, It would be nice to have Nu with a native subcommand like `echo --linebreak` or `echo -ln` to just drop a linebreak.

> #### `pause` and `cls`
> I'd be OK adding these to the exception list.

That would be cool & handy!

//
I looked at the other list of commands in your spreasheet file and I did not identified any additional command (other than the already allowed ones) that could useful except maybe `color` and `path`. At least from my perspective.

## `^`

Also, the escaping prefix `^` was working in v0.66 but not anymore in v0.67 !!

**Comment by CAD97** [comment]
`^command` says to run an external executable `command`, bypassing nu commands, *not* to run `command` in the "host" shell. So `^cmd-builtin` not working isn't a *bug* persay, it's just reflecting that nushell no longer is using cmd as a host.

**Comment by fdncred** [comment]
I could go either way on these. I try my best to use the nushell built-ins for everything. However, nushell doesn't do everything that every shell can do.... yet. :)

One solution is to make custom commands. I tend to do this.
```
def cls [] { clear }
def echo. [] { print "" } # or maybe echo "\n"
def-env cd.. [] { cd .. }
def title [title_str] { $"(ansi title)($title_str)(ansi st)" } # probably have to have shell integration turned off for this to work
def pause [] { ^$"cmd /c pause" } # haven't tried it. may have to tweak.
```

**Comment by Stefouch** [comment]
I tried to make custom commands (`def-env`) in config.nu but I have mixed results:
```bash
> source script.nu # It works, it can use my custom commands.
> nu script.nu     # It cannot use my custom commands :(
```

Also, custom commands need to be synced if the user works on multiple workstations.

PS: Thanks to @CAD97 for the useful alternatives.

> `^command` says to run an external executable `command`, bypassing nu commands, _not_ to run `command` in the "host" shell. So `^cmd-builtin` not working isn't a _bug_ persay, it's just reflecting that nushell no longer is using cmd as a host.

In v0.66 it was very cool to run cmd.exe commands with the `^`. I'm sad to lost this feature (even if it wasn't intended).

**Comment by rgwood** [comment]
@kubouch

> I don't think we should support cmd.exe built-ins because every shell has some built-ins

I generally agree, but... I think it's worth accommodating a few of the more popular `cmd.exe` built-ins. I believe it's mostly a historical accident that they are built-ins and not standalone executables, and working around historical accidents is an unfortunate fact of life on Windows 😅.

I'm guessing most people don't even realize that they are built-ins; PowerShell does a few tricks to make sure that `start`, `pause`, etc. work.

**Comment by fdncred** [comment]
@Stefouch this ` nu script.nu ` is different than `source script.nu` because it's loading another version of nushell and may not be loading any config file. I can't remember because we've changed it a few times and added quite a few parameters to nu.

**Comment by CAD97** [comment]
> I'm guessing most people don't even realize that they are built-ins; PowerShell does a few tricks to make sure that start, pause, etc. work.

This is also I think a good heuristic. If the cmd built-in has a direct equivalent in pwsh, it should have an equivalent (even if not aliased to the same name) in nu.

If it's not available in pwsh, it's probably not all that important in practice (otherwise it would've been added to pwsh by now).

**Comment by rgwood** [comment]
OK, so, current plan is to add `pause` and `cls` to the list.

I'm not sure about `title`; sounds like it doesn't quite work properly and I'm not sure how it interacts with Nu's existing shell integration using ANSI escape sequences. Leaning toward not adding `title` but if someone else has strong feelings just let me know.

**Comment by fdncred** [comment]
in order to use `title`, assuming it works at all these days, you'd have to turn off `shell integration` in nushell via config.nu because nushell sets the title with every prompt draw now.

**Comment by rgwood** [comment]
Added `cls` and `pause` in https://github.com/nushell/nushell/pull/6371.

**Comment by Stefouch** [comment]
> Added `cls` and `pause` in #6371.

This is great, thank you!

> in order to use `title`, assuming it works at all these days, you'd have to turn off `shell integration` in nushell via config.nu because nushell sets the title with every prompt draw now.

Is there a workaround to change the title of the window under Windows with Nu other than using `title` ?
Or a way to force call `title`, e.g. like `^title` ? (I tried `cmd /c title "my window"` but obviously it works only during the quarter of second that the command is running).

**Comment by rgwood** [comment]
@Stefouch 

> in order to use title, assuming it works at all these days, you'd have to turn off shell integration in nushell via config.nu because nushell sets the title with every prompt draw now.

**Comment by rgwood** [comment]
If you want a built-in version of `title` feel free to raise a feature request, that would be pretty easy to implement.

**Comment by Stefouch** [comment]
OK! Will do, thank you!
