### ISSUE TITLE
Tables are composed of wrong characters after chsh

### ISSUE THREAD

**Issue by ghost** [nushell/nushell#636]
This is on Archlinux after installing nushell-git from AUR

![image](https://user-images.githubusercontent.com/44036082/64629608-2eafc000-d3fc-11e9-84cb-40540904f092.png)

This only happens after setting nushell as the default shell, when running regularly it doesn't happen

**Comment by Porges** [comment]
What does `locale` show for you?

**Comment by treeshateorcs** [comment]
first is when I am not running nush

```$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

stay tuned

**Comment by treeshateorcs** [comment]
and this is when nush is the default shell

```
/home/tho> locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

**Comment by Porges** [comment]
Great, that's probably the issue. Does setting `LANG=en_US.UTF-8` inside nushell make any difference? Otherwise it seems like it will need to be set before the shell launches, not sure what the moving parts are here...

**Comment by treeshateorcs** [comment]
![image](https://user-images.githubusercontent.com/44036082/64658393-06e24b80-d440-11e9-8652-a0fd3325d8e9.png)

**Comment by Porges** [comment]
Oh right 😅 nushell can’t yet set or read environment variables #440

**Comment by wycats** [comment]
How do other shells get the right locale when used with `chsh`?

**Comment by andrasio** [comment]
#900

**Comment by jonathandturner** [comment]
@Porges - if you're still using Nu, do you know if this still an issue with more recent Nushell versions?
