### ISSUE TITLE
`to md` breaks lists

### ISSUE THREAD

**Issue by skelly37** [nushell/nushell#6368]
### Describe the bug

I wanted to convert a record with lists to markdown but the separator is simply invalid to paste it on GitHub.

### How to reproduce

Pass some list to the `to md` command

### Expected behavior

basically anything else should be a separator instead of '|', my suggestions are ' ' or ', '

### Screenshots

![image](https://user-images.githubusercontent.com/76530971/185741305-ab0c414c-bf51-4dc5-946e-fbb4dd915ddb.png)
![image](https://user-images.githubusercontent.com/76530971/185741317-ab6f7ccc-1c02-4359-9856-bfd8d62d3f2a.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.0                                          |
| branch             | metadata                                        |
| commit_hash        | 33674d3a98dd7510a4e4784c079dfdaecfd2e0d6        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.63.0 (Arch Linux rust 1:1.63.0-1)       |
| cargo_version      | cargo 1.63.0                                    |
| pkg_version        | 0.67.0                                          |
| build_time         | 2022-08-16 22:50:03 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

See, the lists are broken:

`(metadata) /data/it/nupac〉nupac version | transpose key value | to md --pretty`
| key              | value                                                                                            |
| ---------------- | ------------------------------------------------------------------------------------------------ |
| author           | [skelly37|Yethal]                                                                                |
| checksum         | c50d8e3f81ead7fc0e4f87aab09ed97a36b87ef464d7d70ea13bccd615321d00                                 |
| installer        |                                                                                                  |
| keywords         | [package|packages|management|manager]                                                            |
| long-desc        | Nupac is a package manager written in nu and for nu. Source on https://github.com/skelly37/nupac |
| name             | nupac                                                                                            |
| nu-dependencies  | []                                                                                               |
| os               | [android|linux|macos|windows]                                                                    |
| post-install-msg |                                                                                                  |
| pre-install-msg  |                                                                                                  |
| raw-url          | https://raw.githubusercontent.com/skelly37/nupac/metadata/modules/nupac/nupac.nu                 |
| short-desc       | package manager for nushell                                                                      |
| url              | https://github.com/skelly37/nupac/blob/metadata/modules/nupac/nupac.nu                           |
| version          | 0.1.0                                                                                            |

**Comment by fdncred** [comment]
I'm trying to figure out a way to reproduce this without having to install nupac.

**Comment by skelly37** [comment]
> I'm trying to figure out a way to reproduce this without having to install nupac.

Call `to md` on a record containing some lists as values

**Comment by fdncred** [comment]
I just did this, which I think is what you mean
```
{ "author": [skelly fdncred] } | to md
```

**Comment by skelly37** [comment]
Exactly :)

**Comment by fdncred** [comment]
It looks like we can have pipes if we escape them

|author|
|-|
|[skelly\|fdncred]|

But I think I'm more of a fan of a comma space

|author|
|-|
|[skelly, fdncred]|

**Comment by skelly37** [comment]
Me too, as I've said. Either use commas or nothing (to be consistent with the Nu)

**Comment by fdncred** [comment]
I'll put up a PR in a minute. Would you mind testing it?

**Comment by skelly37** [comment]
> I'll put up a PR in a minute. Would you mind testing it?

I'm fine with that, assuming you can wait ~5h (I'm not at home currently)
