### ISSUE TITLE
Config currently reads file for each read

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#637]
The current version of `config` does not cache the contents of the config file after its been updated, so we're reading from disk for each time we retrieve a config setting.

Ideally, we could keep a live cache of what the current settings are, treat the config file as something only nu maintains, and then we could just read from the cache.

cc @wycats

**Comment by andrasio** [comment]
#900

**Comment by pwnorbitals** [comment]
I agree with the caching, but we may need a way to force a read if the contents are edited from outside nushell
