### ISSUE TITLE
Syntax highlighting fails for aliased command with subcommand

### ISSUE THREAD

**Issue by astral-l** [nushell/nushell#6377]
### Describe the bug

When calling a subcommand using an alias of the top-level command, command-line syntax highlighting is not applied to the command or subcommand, only the arguments.

### How to reproduce

1. Define a command which has at least one subcommand
2. Create an alias for the top-level command
3. Call the subcommand using the alias

e.g.
```
$ def foo-is-a-long-name [i: int] {$i}
$ def "foo-is-a-long-name bar [i: int] {foo-is-a-long-name ($i + 2)}
$ alias foo = foo-is-a-long-name
$ foo 10      # syntax highlighting works as expected
$ foo bar 10  # 'foo bar' is not highlighted, '10' is
```

### Expected behavior

Whichever color is configured for command highlighting should be applied to the alias and subcommand.

### Screenshots

![20220821_124630](https://user-images.githubusercontent.com/111705932/185811056-39e3c432-2bf7-4c77-98c4-0e4b09b0a629.jpg)

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.67.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-aarch64                       |
| build_target       | aarch64-unknown-linux-gnu           |
| rust_version       | rustc 1.62.1 (e092d0b6b 2022-07-16) |
| rust_channel       | stable-aarch64-unknown-linux-gnu    |
| cargo_version      | cargo 1.62.1 (a748cf5a3 2022-06-08) |
| pkg_version        | 0.67.0                              |
| build_time         | 2022-08-21 16:04:21 -04:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |

### Additional context

This is my first issue; I am new to GitHub so if something is missing or further context is needed, please let me know.

**Comment by chdalski** [comment]
I can confirm that Bug. The same happens with piped aliases:
```shell
# executing the command - the output has colors
ls --long --all | select name type mode size modified

# executing an alias - the output has no colors
alias l = (ls --long --all | select name type mode size modified)
l
```

**Comment by weirdan** [comment]
This is probably irrelevant now as you can no longer create aliases for partial commands.
