### ISSUE TITLE
External command `agg` failed; di dyou mean `agg`?

### ISSUE THREAD

**Issue by CAD97** [nushell/nushell#6386]
### Describe the bug

```
〉agg
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #34:1:1]
 1 │ agg
   · ─┬─
   ·  ╰── did you mean 'agg'?
   ╰────
  help: program not found
```

### How to reproduce

1. run `agg`
2. error

### Expected behavior

not fail to find builtin commands, or not suggest nonexistent commands

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.0                                          |
| branch             | main                                            |
| commit_hash        | 91976988f032276ca48faff2d1ac13c079eda836        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.67.0                                          |
| build_time         | 2022-08-17 15:20:56 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by kubouch** [comment]
This is due to the half-implemented overloading. The `agg` exists only for dataframes but you gave it `Any` input type so it didn't find the implementation.

**Comment by sholderbach** [comment]
Closed by the removal of our old command-overloading attempt
