### ISSUE TITLE
`save -r` should allow null

### ISSUE THREAD

**Issue by wmstack** [nushell/nushell#6387]
### Related problem

I want to be able to create an empty file, which is very simple in other shells. However, nushell's `save` commands infers the file type and adds some boilerplate e.g. `save index.html` would add some boilerplate html code. I just want to create an empty file.

So it seems appropriate to use the `-r` option and that it should accept nothing as an argument. However that is not how it currently is. Right now, it fails to accept nothing as an argument preventing us from creating an empty file. I love the Powershell's `ni` command for making a new file , it is concise like `touch`, so I want to have a simple alias like the one below for making new files.

```
alias ni = save -r
```

### Describe the solution you'd like

`save -r index.html` would create an empty html file instead of complaining about `nothing` being supplied.

### Describe alternatives you've considered

The alternative is to have yet another command for creating empty files. However, I think the built in save should support such a common use case.

### Additional context and details

Nushell version `0.66.2`

**Comment by kubouch** [comment]
We have `touch` command, you can use that.

**Comment by fdncred** [comment]
@wmstack are you still wanting save to work like touch or can we close this?

**Comment by wmstack** [comment]
The problem is solved.
