### ISSUE TITLE
No such file or directory (os error 2) scanning home

### ISSUE THREAD

**Issue by bmurphy1976** [nushell/nushell#639]
I'm trying to find the largest files in my workspace directory with the following command:

```
/Users/bmurphy/w> ls **/* | where size > 5mb | sort-by size | reverse | first 35 | pick name size created
```

However after waiting  about a minute with no output, I get the following error message:

```
error: No such file or directory (os error 2)
```

I'm assuming there's an issue with one (or more) of the files in my workspace, but I don't know how to debug it.

OSX, running a build from git head as of 9/10/2019 (f47349c).

**Comment by jonathandturner** [comment]
@bmurphy1976 - do you see the same error if you only do the `ls **/*` step?  If it doesn't, if you build the pipeline up one command at a time, at what point do you see the error?

**Comment by androbtech** [comment]
@bmurphy1976 What OS are you using?

**Comment by bmurphy1976** [comment]
Yes, still fails:

```
/Users/bmurphy/w> ls **/*
error: No such file or directory (os error 2)
```

**Comment by bmurphy1976** [comment]
Did some more digging, found a symlink that points at a file that no longer exists.  Some operations in that directory work, some fail.  Example:

```
/Users/bmurphy/w/PATH_REMOVED> ls
━━━┯━━━━━━━━━━━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━━┯━━━━━━━━┯━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━
 # │ name             │ type    │ readonly │ size   │ created      │ accessed     │ modified
───┼──────────────────┼─────────┼──────────┼────────┼──────────────┼──────────────┼──────────────
 0 │ Rakefile.rb      │ File    │          │ 172 B  │ 8 months ago │ 6 months ago │ 8 months ago
 1 │ config.yml       │ Symlink │          │  83 B  │ 8 months ago │ 8 months ago │ 8 months ago
 2 │ cloudboot-update │ Symlink │          │  34 B  │ 8 months ago │ 8 months ago │ 8 months ago
━━━┷━━━━━━━━━━━━━━━━━━┷━━━━━━━━━┷━━━━━━━━━━┷━━━━━━━━┷━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━

/Users/bmurphy/w/PATH_REMOVED> ls *
error: No such file or directory (os error 2)
```

**Comment by thegedge** [comment]
I think https://github.com/nushell/nushell/pull/814 should probably resolve this issue, @bmurphy1976.

**Comment by bmurphy1976** [comment]
@thegedge I can confirm this is working for me now.  Thanks!
