### ISSUE TITLE
`cp` does not report errors unless `--verbose` is specified

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#6393]
### Describe the bug

I noticed that `cp` does not report errors unless `--verbose` is specified:

![image](https://user-images.githubusercontent.com/26268125/186219155-5884dc89-e5dc-46b6-b270-5d9cf8ed64b4.png)

### How to reproduce

Run a `cp` operation that fails without `--verbose` or `-v`, note that no error is reported

### Expected behavior

I expect errors to be displayed to the user by default. I think it would make sense to change the behaviour of `cp` so that:
- errors are always displayed
- success values are only displayed if `--verbose` is specified

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.67.1                                   |
| branch             | main                                     |
| commit_hash        | 2a310ef187502d92e9d6fb4f0d816e0b7ee2ab4f |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)      |
| rust_channel       | 1.61.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.61.0 (a028ae4 2022-04-29)        |
| pkg_version        | 0.67.1                                   |
| build_time         | 2022-08-23 09:46:23 -07:00               |
| build_rust_channel | debug                                    |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
i noticed this the other day too but forgot to file an issue. or maybe it was with rm? ya, i think mine was with rm. I wonder if mv is affected too. It seems like those 3 had similar internals.

**Comment by nibon7** [comment]
And the error type should not be `FileNotFoundCustom`, since both source and destination exits, it could be `IOError`.

**Comment by rgwood** [comment]
@nibon7 Good catch, addressing that here: https://github.com/nushell/nushell/pull/6396

**Comment by nibon7** [comment]
Filter `Value::Error` seems to work.

```rust
index 33f512dfe..78a8220f1 100644
--- a/crates/nu-command/src/filesystem/cp.rs
+++ b/crates/nu-command/src/filesystem/cp.rs
@@ -285,7 +285,10 @@ impl Command for Cp {
         if verbose {
             Ok(result.into_iter().into_pipeline_data(ctrlc))
         } else {
-            Ok(PipelineData::new(span))
+            Ok(result
+                .into_iter()
+                .filter(|v| matches!(v, Value::Error { error: _ }))
+                .into_pipeline_data(ctrlc))
         }
     }
```

**Comment by rgwood** [comment]
@nibon7 I think that's nearly right but we probably want to do a bit more work to make sure that `$env.LAST_EXIT_CODE` is set to a non-zero value when there are errors. Maybe by putting all the errors in the `#[related] Vec<ShellError>` of a `GenericError`?

I can work on that tomorrow, just let me know if you'd like to work on it instead.

**Comment by nibon7** [comment]
> I can work on that tomorrow, just let me know if you'd like to work on it instead.

I'm not working on this, so please go ahead. :)
