### ISSUE TITLE
Custom completions does not work with 'cat' 

### ISSUE THREAD

**Issue by e2dk4r** [nushell/nushell#6397]
### Describe the bug

I was writing custom completion for `scoop`.
`scoop` is package manager for windows.
`scoop` has `cat` command that prints a `json` file to standard output for an app.

`nushell` does not complete `cat` command.

First I thought I written something wrong but that was not the case.
Second I thought if `nushell` commands is interfering with custom commands but `ls` works.
I tried to produce with simple `nu` file.

### How to reproduce

1. write a `test.nu`
```
def completions [] {
  [ 'a' 'b' 'c', 1, 2, 3 ]
}

# does not work
export extern "app cat" [
  param: string@completions
]

# works
export extern "app ls" [
  param: string@completions
]
```
2. use `test.nu` definitions with `use test.nu *`
3. try `app cat` completion with `app cat <TAB>`

### Expected behavior

I expected nu to complete `app cat` with `a` `b` `c` `1` `2` `3`

## app ls output
![image](https://user-images.githubusercontent.com/43293320/186341997-8226613b-c999-41c3-b2a5-98bcdc285938.png)

## app cat output
![image](https://user-images.githubusercontent.com/43293320/186342218-f4f97467-120f-4f50-9750-97221c82383b.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.0                                          |
| branch             |                                                 |
| commit_hash        | 33674d3a98dd7510a4e4784c079dfdaecfd2e0d6        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.67.0                                          |
| build_time         | 2022-08-16 20:28:43 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by e2dk4r** [comment]
I find the error.
In my config I have defined `cat` as as alias.

**Comment by fdncred** [comment]
LOL - been there done that. I was testing someone else's aliases and custom commands and forgot to remove them one time. my system was working strange to me, until I realized it was these things.
