### ISSUE TITLE
External command parameters get mangled

### ISSUE THREAD

**Issue by panicbit** [nushell/nushell#6399]
### Describe the bug

External command paramaters get stripped of their outmost single quotes when their prefix contains an `=`.

### How to reproduce

- `^echo "= 'hi'"`
- `^echo "foo=bar 'hi'"`

![image](https://user-images.githubusercontent.com/628445/186392515-90e88f48-4d37-4169-8cbc-dc57311ef886.png)

### Expected behavior

I expect the parameters do behave the same as with non-external commands:

- `echo "= 'hi'"`
- `echo "foo=bar 'hi'"`

![image](https://user-images.githubusercontent.com/628445/186391708-fb50e40b-fef9-4527-b0a1-3bc337ff7a17.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.1                                          |
| branch             |                                                 |
| commit_hash        | 0afe1e4e6741c70961739fb7da06b2f4a82800b7        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.67.1                                          |
| build_time         | 2022-08-24 11:35:06 +02:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
I thought there was a PR a few weeks ago that stripped quotes like this on purpose?

**Comment by panicbit** [comment]
I think the idea was to only strip it for flags, which I can understand somewhat, but I don't think stripping all quotes for any arg was the intention.

**Comment by panicbit** [comment]
Maybe it's important to note that this issue affects a real life use case (in fact, one of my scripts at work broke due to the change):
```nu
let dump_command = $"PGPASSWORD='($db_secret)' pg_dump -Fc -h '($db.host)' -p '($db.port)' -U postgres -d '($db.name)' > '/tmp/($dump_name)'"

^kubectl exec -n $bastion.namespace $bastion_pod -- sh -c $dump_command
```

**Comment by fdncred** [comment]
> I think the idea was to only strip it for flags, which I can understand somewhat, but I don't think stripping all quotes for any arg was the intention.

Ya, you're probably right. Your issue just made me think of where we remove quotes and that was the only one I remember.

**Comment by fdncred** [comment]
I'm not sure what changed to break your script. Feel free to look at PRs. Maybe it was a mistake or a bug.

I've started using parameters like this because it seems to work better.
```
^external_command [$arg1 $arg2 $arg3]
```

**Comment by panicbit** [comment]
In what ways does that work better? For the issue at hand it does not seem to matter:

![image](https://user-images.githubusercontent.com/628445/186423301-ff797ddb-66a6-471f-880b-7516bf03ce22.png)

**Comment by WindSoilder** [comment]
@panicbit Would you please verify if the latest main works for you with the following example?

```
let dump_command = $"PGPASSWORD='($db_secret)' pg_dump -Fc -h '($db.host)' -p '($db.port)' -U postgres -d '($db.name)' > '/tmp/($dump_name)'"

^kubectl exec -n $bastion.namespace $bastion_pod -- sh -c $""$dump_command""
```

**Comment by panicbit** [comment]
It does work (although the correct incantation is `$""($dump_command)""`), but I'm not gonna lie, I hope this is not the final solution for this problem, because this feels pretty insane.
Theoretically I would have to do that `$""$dump_command""` with every variable, just to make sure it doesn't get mangled.
I will probably also never complain about having to put quotes around variable uses in other shells anymore…

**Comment by WindSoilder** [comment]
Yeah I agreed.

Sorry for the current situation.  I think it's better to use just `$"($dump_command)"` or `"$dump_command"`

**Comment by WindSoilder** [comment]
@panicbit Hi, sorry for disturb, would you please check the latest main again?

I think `$dump_command` can be used directly for now

```
let dump_command = $"PGPASSWORD='($db_secret)' pg_dump -Fc -h '($db.host)' -p '($db.port)' -U postgres -d '($db.name)' > '/tmp/($dump_name)'"

^kubectl exec -n $bastion.namespace $bastion_pod -- sh -c $dump_command
```

**Comment by panicbit** [comment]
It works 🥳. Thanks for caring about this and putting in all the effort! 😃
