### ISSUE TITLE
Excessive CPU and RAM usage scanning directories

### ISSUE THREAD

**Issue by bmurphy1976** [nushell/nushell#640]
While trying to scan my home directory for the largest files using the following command:

```
/Users/bmurphy> ls **/* | where size > 5mb | sort-by size | reverse | first 35 | pick name size created
```
One of my CPU cores gets pegged at 100% and after a couple minutes I had to kill the nu process as it was chewing up for 7gb of RAM and still growing.

OSX, running a build from git head as of 9/10/2019 (f47349c).

**Comment by jonathandturner** [comment]
Do you know about how many files this is iterating over?

**Comment by bmurphy1976** [comment]
According to jDiskReport there's 825,073 files.  I tried running `find . | wc` and it's been running so long I doubt it's going to complete.

**Comment by bmurphy1976** [comment]
Find finally finished and reported the following:

```
/Users/bmurphy> find . | wc
  939800 2058353 103020554
```

I presume the delta is that jDiskReport wasn't counting directories.

**Comment by jonathandturner** [comment]
Can you see if this has improved with #812, which we recently landed?

**Comment by bmurphy1976** [comment]
I let it run for 40 minutes.  Memory topped out at 500mb (which is significantly improved) before I had to kill it.  RAM usage has improved considerably.

CPU is still an issue although I have an epic amount of files in my home directory so that isn't too surprising.  I'll run again when I have more time and see if I can get it to run to completion.

**Comment by jonathandturner** [comment]
@bmurphy1976 - you're using `reverse` and `sort-by` so perhaps the streaming isn't helping you much.  It's still going to have to consume the whole list to give you any output.

**Comment by bmurphy1976** [comment]
Right.  Anyway, I let this run for 4 hours and it's still not finishing.  My feelings are that the initial issue is resolved.  I don't feel the CPU/RAM is "excessive" anymore, it's just slow (relative to jDiskReport anyway).

**Comment by jonathandturner** [comment]
Sounds good. If you're interested, we'd still like to track the performance of it. Ideally, it would be able to work with the filesystem in a more efficient way (like tools like jDiskReport)
