### ISSUE TITLE
Single quote strings are interpreted as glob patterns

### ISSUE THREAD

**Issue by chtenb** [nushell/nushell#6403]
### Describe the bug

I want to pass literal strings to an external command. I've been told that single quoting the strings is the way to do it, since that seems to work for other people. Howeve, not for me:

```
~
❯ ^echo '**/*.json'
dotfiles/keybindings.json dotfiles/settings.json
```

I'm on windows with git bash installed, so echo is just GNU echo:

```
❯ which ^echo
╭───┬──────┬───────────────────────────────────────┬──────────╮
│ # │ arg  │                 path                  │ built-in │
├───┼──────┼───────────────────────────────────────┼──────────┤
│ 0 │ echo │ C:\Program Files\Git\usr\bin\echo.EXE │ false    │
╰───┴──────┴───────────────────────────────────────┴──────────╯
```

### How to reproduce

Run the command in the description

### Expected behavior

```
~
❯ ^echo '**/*.json'
**/*.json
```

### Configuration

❯ version | transpose key value | to md --pretty
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.0                                          |
| branch             |                                                 |
| commit_hash        | 91976988f032276ca48faff2d1ac13c079eda836        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.67.0                                          |
| build_time         | 2022-08-17 15:20:56 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by ChrisDenton** [comment]
I believe that's git bash's echo doing the expansion. This is caused by two factors:

* By default, `std::process::Command` won't quote arguments unless necessary (e.g. they contain spaces)
* git bash's echo will expand unquoted arguments.

This can be a problem with cygwin/mingw derived applications as they handle arguments differently to regular Windows applications. This is why a [`force_quotes`](https://doc.rust-lang.org/std/os/windows/process/trait.CommandExt.html#tymethod.force_quotes) method was added to `Command` (currently nightly only).

**Comment by fdncred** [comment]
we have 4 types of quotes, each may work differently. have you tried all of these?
- bare words - so like **/*.json
- single quotes
- double quotes
- backtick quotes

**Comment by ChrisDenton** [comment]
They all work the same because nushell isn't the one expanding the glob in this case. A third party command is.

A workaround would be to manually force quotes. E.g.:

    ❯ ^echo '\"**/*.json\"'

**Comment by chtenb** [comment]
To answer @fdncred 👍 

```
❯ ^echo '**/*.json'
dotfiles/keybindings.json dotfiles/settings.json

~
❯ ^echo "**/*.json"
dotfiles/keybindings.json dotfiles/settings.json

~
❯ ^echo `**/*.json`
`**/*.json`

~ took 28s
❯ ^echo **/*.json
**/*.json

~ took 25s
```

Notably, the last two commands take a lot of time and spike the cpu.

**Comment by chtenb** [comment]
The suggestion of @ChrisDenton yields the following output for me:

```
❯ ^echo '\"**/*.json\"'
\\**/*.json\"
```

**Comment by chtenb** [comment]
@ChrisDenton Your assessment sounds highly plausible to me. I often run into this issue with git commands, and I didn't expect echo to do any expansion, hence my initial assumption that nushell did the expansion. But indeed both the git commands and echo are part of msys2. 

The question remains, is there anything that can be done about this? In git bash I always used wildcards prefixed with a `\`, which always seemed to do what I expected.

**Comment by WindSoilder** [comment]
I can't reproduce it on mac

**Comment by fdncred** [comment]
I did this test in Windows too, just for comparison.
```
❯ ^echo '**/*.json'
wix/windows-terminal-profile.json

~
❯ ^echo "**/*.json"
wix/windows-terminal-profile.json

~
❯ ^echo `**/*.json`
.vs\ProjectSettings.json .vs\VSWorkspaceState.json .vscode\launch.json .vscode\settings.json crates\nu-command\assets\228_themes.json samples\wasm\package-lock.json samples\wasm\pason tests\assets\nu_json\empty_result.json tests\assets\nu_json\failJSON02_test.json tests\assets\nu_json\failJSON05_test.json and more json files

~ took 476ms
❯ ^echo **/*.json
.vs\ProjectSettings.json .vs\VSWorkspaceState.json .vscode\launch.json .vscode\settings.json crates\nu-command\assets\228_themes.json samples\wasm\package-lock.json samples\wasm\pason tests\assets\nu_json\empty_result.json tests\assets\nu_json\failJSON02_test.json tests\assets\nu_json\failJSON05_test.json and more json files

~ took 177ms
```

```
❯ which ^echo  
╭───┬──────┬──────────────────────────────┬──────────╮
│ # │ arg  │             path             │ built-in │
├───┼──────┼──────────────────────────────┼──────────┤
│ 0 │ echo │ C:\Apps\Git\usr\bin\echo.EXE │ false    │
├───┼──────┼──────────────────────────────┼──────────┤
│ # │ arg  │             path             │ built-in │
╰───┴──────┴──────────────────────────────┴──────────╯
```

**Comment by fdncred** [comment]
@AceofSpades5757 this is the latest documentation - not real documentation but notes on what works or doesn't work as far as expansion and quoting.
https://hackmd.io/@fdncred/BJqi8MrJj

I doesn't really give any work-arounds though. It just kind of tells you what you may have already figured out. We'd like to make all this quoting and expansion better but it's tricky because different externals respond differently, not to mention doing it cross platform adds to the complexity. We'd be happy to have help.

**Comment by bobhy** [comment]
*nudge* original opener might consider closing this bug, with resolution "by design".  Meaning it's a real problem, but not due to behavior or misbehavior of Nushell.

**Comment by AceofSpades5757** [comment]
@bobhy Instead of using the external command, you can use the built-in `echo`: `echo '**/*.json'`

I don't think this can be fixed with external commands since they're external and out-of-scope for the nushell project.

**Comment by bobhy** [comment]
@chtenb Can you confirm you're still having a problem here?

I think the thread so far has confirmed that the repro scenario you posted looks like nushell is passing the (single) quoted argument unmodified to  Windows Git echo, which then expands the glob, due to a quirk in msys or echo itself.
We think that means this issue is not fixable in nushell, and would like to close this issue.

But if you're still stuck , please post another repro scenario that's closer to your pain point, let's see what we can do.

**Comment by chtenb** [comment]
Nushell is not misbehaving. I left the issue open because I was thinking this use case / issue might be common enough to warrant a proper workaround. But I don't think there is an obvious one. Use cases that involve multiple levels of glob evaluation are inherently tricky. 

Btw I'm encountering these issues mostly with git commands (they are also from msys2), so simply using the builtin echo command is not a fix unfortunately.

But I'm still really confused about how I should pass a literal string into a third party command, especially when that literal gets interpreted and evaulated at multiple levels. I have figured out how to make `^echo` output something like `'**/*.json'`.

Namely:

```
> ^echo "'\\'**/*.json\\''" 
'**/*.json'
```

But I won't go as far as to say that this is intuitive or easy to come up with. It would probably a good idea to have an explanation in the docs or FAQ or something, as this is an issue where people can lose a lot of time.

**Comment by bobhy** [comment]
How would you propose Nushell should decide when to set the `force_quotes`
flag?  Get it wrong and that breaks other external commands.
Would you accept a solution that required you as user to define an `extern`
for each external command you wanted invoked that way?

**Comment by chtenb** [comment]
> Would you accept a solution that required you as user to define an `extern` for each external command you wanted invoked that way?

Something like that actually sounds pretty reasonable. Especially because this really is about dealing with quirks of external commands. I wouldn't want to pollute the regular nushell syntax with workarounds for such situations.

**Comment by weirdan** [comment]
This doesn't happen anymore:

```console
$ glob **/*.toml | length
47

$ ^echo '**/*.toml'
**/*.toml
```

**Comment by sholderbach** [comment]
To add, (although still somewhat in flux) the backtick strings seem to crystalize as the quote type that permits expansion in combination with whitespace in other path components.
