### ISSUE TITLE
File completion supercedes external completion

### ISSUE THREAD

**Issue by rsteube** [nushell/nushell#6407]
### Describe the bug

When currently completed word is either empty or matches a file/folder file completion supercedes the external completion.

### How to reproduce

```sh
# config.nu
let external_completer = {|spans| [ a b p ]}
```

```sh
ls
# prefixmatch/

xx <TAB>
# prefixmatch/

xx a<TAB>
# a b p

xx p<TAB>
# prefixmatch/
```

### Expected behavior

Use the provided completions from the external completer instead of the default file completion.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.67.1                                   |
| branch             |                                          |
| commit_hash        | d97975e9fafa69b5f9974ab1d7ed505c8679b652 |
| build_os           | linux-aarch64                            |
| build_target       | aarch64-unknown-linux-gnu                |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)      |
| rust_channel       | 1.61.0-aarch64-unknown-linux-gnu         |
| cargo_version      | cargo 1.61.0 (a028ae4 2022-04-29)        |
| pkg_version        | 0.67.1                                   |
| build_time         | 2022-08-23 10:57:56 +02:00               |
| build_rust_channel | release                                  |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

**Comment by herlon214** [comment]
I performed the same steps but now my pwd was `/tmp/test` with two files `file.txt` and `fileb.txt`.

```
$ xx p<TAB>
a b p
```
^ using `p<tab>` triggered the external completion

```
xx b<TAB>
# a b p
```
^ using `b<tab>` triggered the file completion because i had a file with `b` in the name (fileb.txt)

So looks like the problem is:
- If there's any file that contains your span, we trigger FileCompletion
- If there are no files with your span, we trigger ExternalCompletion

It's a bit tricky, because how can we know that the user is actually specifying a file to the command or a sub-command?

**Comment by rsteube** [comment]
Nushell shouldn't intervene an external completer at all.
It should only fall back to file completion if no completer is defined for a command.
The current issue is that the external completer function doesn't differenciate between an empty result (nothing to complete at current position) and an external completer not being invoked (file fallback).
Only exception might be nushell internals like environment variables (`$` prefix) where the external completer is skipped.

**Comment by herlon214** [comment]
To add a bit more:

Currently we only check the type for the current span (`src` and `g`, according to my examples). Because of that, the completer doesn't know about the `kubectl` or `ls`, so it can't know the difference between the external and internal.
Probably this is part of the issue in our current completer code ^

**Comment by flying-sheep** [comment]
Can’t we just change the order in which completion engines are tried to

1. internal stuff like env variables
2. external completer (if configured)
3. files

**Comment by flying-sheep** [comment]
I think there’s two issues with the completion logic. Assuming I understand correctly what `FlatShape` is (I think it’s the way an expression looks, and things like `./foo` are interpreted as file or directory paths):

1. we start by matching by `FlatShape`:

   https://github.com/nushell/nushell/blob/12a0fe39f73e88a2be97dce3d9cbe025b10e253d/crates/nu-cli/src/completions/completer.rs#L275-L276

   and dispatch to the file completer if it looks like a file path:

   https://github.com/nushell/nushell/blob/12a0fe39f73e88a2be97dce3d9cbe025b10e253d/crates/nu-cli/src/completions/completer.rs#L306

   Only in the fallback branch we finally try the external completer:

   https://github.com/nushell/nushell/blob/12a0fe39f73e88a2be97dce3d9cbe025b10e253d/crates/nu-cli/src/completions/completer.rs#L318

2. inside of the fallback branch, we first try the file completer and then the external completer:

   https://github.com/nushell/nushell/blob/12a0fe39f73e88a2be97dce3d9cbe025b10e253d/crates/nu-cli/src/completions/completer.rs#L341-L360

Switching out the file completer and the external completer in the fallback branch would already help with the more obvious problems like empty completion, but to really address this, we need to restructure the entire thing.

External completers also need to be able to handle files: When I do `git add ./<TAB>` I don’t want to see all files. I want to be offered a list of files that contains changed files first and then untracked files. The list shouldn’t contain any unchanged files. Only external completers will offer that, not nushell’s.

**Comment by fdncred** [comment]
ugh, carapace is so nice in an empty folder. I wish we could solve this problem somehow.

**Comment by rsteube** [comment]
gave it a try and seems to work so far
