### ISSUE TITLE
Unable create variable with name contains `-`

### ISSUE THREAD

**Issue by Cologler** [nushell/nushell#6419]
### Describe the bug

I was copied `let my-value = 4` from https://www.nushell.sh/book/variables_and_subexpressions.html to nushell, but it won't work.

The nushell version is 0.67.0.

### How to reproduce

1. Install nushell (version 0.67.0)
2. Type `let my-value = 4` and execute.

### Expected behavior

Allow `-` in the variable name, instead of making a breaking change.

### Screenshots

![image](https://user-images.githubusercontent.com/10906962/186836003-a40277b6-2199-4c43-baa4-01919ef0a0d5.png)

### Configuration

〉version | transpose key value | to md --pretty
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.0                                          |
| branch             |                                                 |
| commit_hash        | 33674d3a98dd7510a4e4784c079dfdaecfd2e0d6        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.67.0                                          |
| build_time         | 2022-08-16 20:28:43 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by kubouch** [comment]
Variables with `-` in their name were discontinued: https://www.nushell.sh/blog/2022-08-16-nushell-0_67.html#new-variable-naming-convention-jt

The book needs to be updated.

**Comment by hyiltiz** [comment]
Really hope this could be reverted, adding back support to `-` in variable and command names. While at it, maybe add support for `?!` as variable name characters too.
