### ISSUE TITLE
Documentation and error issue with `order-by`

### ISSUE THREAD

**Issue by robations** [nushell/nushell#6422]
### Describe the bug

Use the `order-by` command as documented here:

https://www.nushell.sh/book/commands/order-by.html

The command doesn't exist, and you also get a confusing error message saying "did you mean `order-by`".

### How to reproduce

1. Latest version of nushell @ 0.67.0
2. Run `ls | order-by name`
3. Seeing the following error:

```
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #12:1:1]
 1 │ ls | order-by name
   ·      ────┬───
   ·          ╰── did you mean 'order-by'?
   ╰────
  help: No such file or directory (os error 2)
```

### Expected behavior

I'm guessing that `order-by` has been renamed to `sort-by`.

Perhaps:

- docs to be updated (perhaps mentioning that this command was been renamed from `order-by` in version x.y.z)
- change error message to read "did you mean 'sort-by'?"
- bonus points for mono-repoing the documentation here so that pull requests can update this in sync with code changes — though I realise a non-trivial project change

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | macos-x86_64                                    |
| build_target       | x86_64-apple-darwin                             |
| rust_version       | rustc 1.63.0                                    |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.67.0                                          |
| build_time         | 2022-08-16 17:47:47 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
`order-by` exists but it's only for `dataframes` at the moment. You can check these type of things by doing `help -f order-by`

**Comment by robations** [comment]
Okay. Still confusing.

**Comment by robations** [comment]
Just saw your update...

I'd suggest adding a "warning/be aware" box to both order-by and sort-by doc pages. But this would be a documentation issue.

**Comment by robations** [comment]
NB I was also confused by this link from Algolia search, but also a docs issue:

https://www.nushell.sh/book%2Fhttps:%2F%2Fwww.nushell.sh%2Fbook%2Fcommands%2Forder-by.html
