### ISSUE TITLE
Nushell does not work well in embed terminal of KDE Dolphin

### ISSUE THREAD

**Issue by Yesterday17** [nushell/nushell#6427]
### Describe the bug

Nu does not work well in the embedded terminal. There're several cases.

## On start
![image](https://user-images.githubusercontent.com/8667822/187014833-fc79fa5f-982a-4d32-9b54-42d1a516d515.png)

Dolphin expects to execute multiple commands in the terminal, but `Nu` did not execute them.

## On chdir
![image](https://user-images.githubusercontent.com/8667822/187014871-5c1fcb0d-7dac-4d0c-8597-7189e27197ce.png)
Nu does not execute the command. And if you try to execute it manually(by pressing <kbd>Enter</kbd>), the command would not be actually executed either. (See `pwd` of the second line in the image below)
But if you use <kbd>↑</kbd> and execute the same command in history, it does work.

![image](https://user-images.githubusercontent.com/8667822/187014895-0741439a-8ce7-459d-935b-b205a11941b8.png)

### How to reproduce

1. Edit profile in dolphin to use `/usr/bin/nu` as the default terminal session
2. Restart Dolphin
3. Enter/leave a directory in dolphin

### Expected behavior

`Nu` should follow cwd of dolphin and change its current dir.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.66.3                                          |
| branch             |                                                 |
| commit_hash        | 5f11be69ed1bd11bf676345149fdb110271b1181        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.1 (Arch Linux rust 1:1.62.1-1)       |
| cargo_version      | cargo 1.62.1                                    |
| pkg_version        | 0.66.3                                          |
| build_time         | 2022-07-30 08:08:06 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by Yesterday17** [comment]
I've found the cause of this problem after further investigation. Dolphin sends the command to its internal terminal directly, ending with`\n`.

https://github.com/KDE/dolphin/blob/4ddc4159ed5d9fb6e7b7c6edc1b04460f87c984b/src/panels/terminal/terminalpanel.cpp#L264
> m_terminal->sendInput(" cd " + KShell::quoteArg(dir) + '\n');

And Nu uses reedline to capture input:
https://github.com/nushell/nushell/blob/df3b6d9d264747bff0e2a81ab6eddb063d11a442/crates/nu-cli/src/repl.rs#L320

Reedline enters raw mode when `read_line` was called, and only accept <kbd>Enter</kbd> as sequence end:
https://github.com/nushell/reedline/blob/174255535dccb0fea5e2d0e055fc5884830df898/src/engine.rs#L401

`\n` would produce an <kbd>Enter</kbd> event only if crossterm is not in raw mode:
https://github.com/crossterm-rs/crossterm/blob/1fee5ff30c47116f81cb822626e8388d554c1cc3/src/event/sys/unix/parse.rs#L99

---

I believe this should be an issue of both Dolphin and Nushell (actually reedline, or crossterm(maybe?)). Dolphin should send <kbd>Return</kbd> instead of `\n`, and Nu should handle these `\n`s correctly just as other shells do.

**Comment by sholderbach** [comment]
Interesting that we didn't come accross this issue earlier! Thanks for catching it and doing a proper and thorough investigation @Yesterday17 

The old [ECMA-48 spec for the ANSI terminal](https://www.ecma-international.org/wp-content/uploads/ECMA-48_5th_edition_june_1991.pdf)  is devoid on information how we should treat that but 
it appears that the `\r`/`0x0D`/`^M` is the convention for the keypress and there is an implied conversion depending on the [tty mode](https://man7.org/linux/man-pages/man1/stty.1.html).

https://unix.stackexchange.com/questions/253271/understanding-return-enter-and-stty-icrlf

So I don't know if the dolphin project will merge your change or if we are compliant with some arcane spec or not.

GNU readline seems to go with using both to `\n`/`0x0A`/`^J` and `\r`/`0x0D`/`^M` to accept by default.

https://www.man7.org/linux/man-pages/man3/readline.3.html

We could add `Ctrl-J` as an equal to the `crossterm` `Enter` in `reedline` but they seem to try to do this to enable the use of `Ctrl-J` for other purposes (https://github.com/crossterm-rs/crossterm/pull/373, https://github.com/crossterm-rs/crossterm/issues/371). But if I recall the implementation in some terminals might be not as consistent and thus this might not always disable the `CRLF` translation.

Now that crossterm supports an extend Keyboard protocol suggested by Kitty and other terminals we might be able to distinguish them in other ways (don't know if we will be able to distinguish proper `Ctrl-J` from `^J` with crossterm 0.25)

**Comment by ErichDonGubler** [comment]
I have also noticed that <kbd>Enter</kbd> keypresses on my M1 Mac in both the Terminal app and Wezterm are read as <kbd>Ctrl + J</kbd> while a command is executing. An easy repro. method:

```sh
$ nu --no-config-file

…> sleep 3sec; input listen

# Press `Enter` before `sleep` finishes…

╭───────────┬───────────────╮
│ type      │ key           │
│ key_type  │ char          │
│ code      │ j             │
│ modifiers │ [list 1 item] │
╰───────────┴───────────────╯
```

This prevents me from typing commands in a pipelined way (i.e., start a command that doesn't take any input, and start typing a new one while the first executes).

**Comment by ErichDonGubler** [comment]
I've been experimenting with configuration, and I'm able to re-map the <kbd>CTRL + J</kbd> to `Enter` with this `keybindings` entry:

```nuon
{
  name: unix_enter
  modifier: control
  keycode: char_j
  mode: [emacs vi_normal vi_insert]
  event: { send: enter }
}
```

So...my own problem is resolved. Yay configuration, I guess!
