### ISSUE TITLE
`miette` does not point out the wrong item when applying a command on a list with `each`

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#6429]
### Question

Hello there :wave: :yum: 

i'm really not sure if that is a bug or a feature, so i choose to make it a question first :wink: 

## The... thing i found
i've got some files in some directory, on which i want to perform some action, an `ls` for the sake of the example
i use the `LIST_OF_ARGUMENTS | each {|it| ACTION $it}` structure of `nushell`, to apply the ` ACTION` on `each` argument in the `LIST_OF_ARGUMENTS` :+1:

now, let us say i misspell some of the arguments, resulting in a wrong list where some files might not exist, i get the following 
```rust
> ls
╭───┬────────────┬──────┬──────┬──────────────╮
│ # │    name    │ type │ size │   modified   │
├───┼────────────┼──────┼──────┼──────────────┤
│ 0 │ does_exist │ file │  0 B │ a minute ago │
╰───┴────────────┴──────┴──────┴──────────────╯
> [does_exist] | each { |it| ls $it } | flatten
╭───┬────────────┬──────┬──────┬────────────────╮
│ # │    name    │ type │ size │    modified    │
├───┼────────────┼──────┼──────┼────────────────┤
│ 0 │ does_exist │ file │  0 B │ 11 seconds ago │
╰───┴────────────┴──────┴──────┴────────────────╯
> [does_not, does_exist, does_not_either | each { |it| ls $it } | flatten
Error: nu::shell::directory_not_found (link)

  × Directory not found
   ╭─[entry #6:1:1]
 1 │ [does_not, does_exist, does_not_either] | each { |it| ls $it } | flatten
   ·                                         ─┬─
   ·                                          ╰── directory not found
   ╰────
```

the first `each` works fine with the `does_exist` file
however, when there are files which do not exist in the list, `miette` does not tell which one of the argument is wrong, i.e. which one of the file does not exist here :thinking: 

**Is that a feature or a bug?** :yum: 

cheers everyone :wave: :tada: 

## `version` of `nushell`
```rust
╭────────────────────┬─────────────────────────────────────────────────╮
│ version            │ 0.67.0                                          │
│ branch             │                                                 │
│ commit_hash        │ 33674d3a98dd7510a4e4784c079dfdaecfd2e0d6        │
│ build_os           │ linux-x86_64                                    │
│ build_target       │ x86_64-unknown-linux-gnu                        │
│ rust_version       │ rustc 1.63.0 (Arch Linux rust 1:1.63.0-1)       │
│ cargo_version      │ cargo 1.63.0                                    │
│ pkg_version        │ 0.67.0                                          │
│ build_time         │ 2022-08-16 22:50:03 +00:00                      │
│ build_rust_channel │ release                                         │
│ features           │ database, dataframe, default, trash, which, zip │
│ installed_plugins  │                                                 │
╰────────────────────┴─────────────────────────────────────────────────╯
```

## `uname -a`
```rust
Linux archasus 5.19.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 17 Aug 2022 13:48:51 +0000 x86_64 GNU/Linux
```

**Comment by WindSoilder** [comment]
Just my personal thought:

Because the block inside `each` may contain multiple commands, and we need to know which command runs into failed, for example:
```
[does_not, does_exist, does_not_either] | each { |it| 
    echo $it
    cd $it
    ls $it
}
```

Currently nu will point out that `cd $it` runs to failed, which is helpful for knowing what happened inside each block, I think it's helpful.

But I think we can add a new flag like `--label-err-on-input` to make nu point out the wrong item.

**Comment by amtoine** [comment]
@WindSoilder 
thanks a lot for taking the time to address this :star_struck: 

i agree with your previous message and the idea of @merelymyself to show both errors by default looks perfect to me :yum: 

looking forward to seing that new feature in the `nushell` `0.68.0` maybe :muscle:
