### ISSUE TITLE
Nushell no longer respects file associations on Windows

### ISSUE THREAD

**Issue by CAD97** [nushell/nushell#6440]
### Describe the bug

e.g. given some `x.py` and a file association of

```cmd
>ASSOC .py
.py=Python.File
>FTYPE Python.File
Python.File="C:\Windows\py.exe" "%L" %*
```

### How to reproduce

```nushell
〉x.py --help
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #4:1:1]
 1 │ x.py --help
   · ──┬─
   ·   ╰── did you mean 'cp'?
   ╰────
  help: program not found

〉./x.py --help
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #5:1:1]
 1 │ ./x.py --help
   · ───┬──
   ·    ╰── can't run executable
   ╰────
  help: %1 is not a valid Win32 application. (os error 193)
```

### Expected behavior

The file should be run using the file association. This is what happened when running via a `cmd /c` host shell for execution.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.0                                          |
| branch             |                                                 |
| commit_hash        | 91976988f032276ca48faff2d1ac13c079eda836        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.67.0                                          |
| build_time         | 2022-08-17 15:20:56 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

The Windows documentation for file types is https://docs.microsoft.com/en-us/windows/win32/shell/fa-file-types. If I'm reading this right, in order to read the file associations you need to read the registry directly.

**Comment by rgwood** [comment]
Hmm. My thinking is that running `foo` in Nushell means "attempt to run a command or executable named `foo`", not "open `foo` as if it was double-clicked in Explorer."  If you need to do the later, `start` (i.e. `start x.py`) works for that.

I'm open to other points of view, but I think the new behaviour is correct.

**Comment by CAD97** [comment]
Counterpoint: pwsh launches scripts in this manner. At the very least, even if nushell doesn't use the Windows filetype associations, it probably should have some functionality to allow running scripts without specifying the interpreter explicitly.

If nushell respects shebang lines on unix, imho it should respect file associations on Windows, which is roughly the equivalent feature.

**Comment by CAD97** [comment]
Also of note; `./x.py` should run the script in the same terminal; `start x.py` opens it as if clicked, thus in a new terminal window.

**Comment by rgwood** [comment]
I think I'm coming around to your point of view. Would be nice if `./x.py` and `.\x.py` worked the way they do in PowerShell - I'll see if I can make that happen.

**Comment by rgwood** [comment]
@CAD97 I might be busy with job stuff for a little while. Are you interested in picking this up (design and/or implementation)?

**Comment by CAD97** [comment]
...huh, I wonder what changed. It's working for me as well now, with

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.68.0                                          |
| branch             |                                                 |
| commit_hash        | b0e5723a68d77b42d756879ab7773fdee81f8924        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.68.0                                          |
| build_time         | 2022-09-06 20:03:51 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

I guess I'll close this, then.

**Comment by CAD97** [comment]
I bet it's https://github.com/nushell/nushell/pull/6278; if `which` is finding the file, then IIUC it'll get run through cmd which will do the dispatch to the associated interpreter.

I'd need to step the procedure to be sure, though.

**Comment by CAD97** [comment]
Confirmed

```
D:\git\rust-lang〉.\rust\x.py --help
'x.py' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by rgwood** [comment]
Interesting. I wouldn't expect #6278 to fix this; you're sure it was that commit?

**Comment by CAD97** [comment]
It's definitely an accidental "fix". What's happening is roughly

```nu
$command = "./x.py"
$path = $command | path canonicalize
if $command != ($path | path file-name) {
    ^cmd /c (path | file-name)
}
```

and the `if` is taken since `./x.py != x.py`

**Comment by rgwood** [comment]
Did you confirm that #6278 is the change that fixed this?

**Comment by CAD97** [comment]
Oh, sorry; I'm drawing conclusions from reading the code that launches the executable and observing behavior; I haven't specifically tested that it was that change, but it's the only one that touched the extern dispatch, so it kind of has to be it.

**Comment by rgwood** [comment]
I did the bisect, and it's not that change. It's the `which-rs` upgrade from v4.2.2 to v4.3.0:

```
commit 11531b76303d8c883f99b4098e678ae0e9ef7bb0
Author: Reilly Wood <26268125+rgwood@users.noreply.github.com>
Date:   Wed Aug 31 09:50:18 2022 -0700

    Upgrade `which` dependency to fix case on Windows (#6453)

 Cargo.lock                   | 6 +++---
 crates/nu-command/Cargo.toml | 2 +-
 2 files changed, 4 insertions(+), 4 deletions(-)
 ```
 
I think this PR is the one that changed it: https://github.com/harryfei/which-rs/pull/57

**Comment by CAD97** [comment]
So we're kindof both right, in that it is the which path executing it, but that the behavior changed after that PR when updating the dependency.

That said, the "proper" behavior is probably to

- Determine the file to execute by checking the given path and the given path with exts from PATHEXT (what which is doing)
- Determine how to run the file (assoc/ftype) similarly to how pwsh/cmd do; this *does* use the [registry file associations](https://docs.microsoft.com/en-us/windows/win32/shell/fa-file-types) (even in cmd!) and not the legacy ones visible through `assoc`/`ftype`. For example, try "running" a `.html` in cmd; `ftype` says `iexplore.exe` but it will be your actual browser choice.

The point is to "act like a shell" in terms of executing files; matching the behavior of cmd and pwsh in launching files is probably better than being "pure" and only launching directly-executables or PATHEXT executables.

**Comment by CAD97** [comment]
Did a bit of research. [pwsh use{s|d}](https://github.com/PowerShell/PowerShell/pull/4523) [`ShellExecuteEx`](https://docs.microsoft.com/en-us/windows/win32/shell/launch) to launch documents (their name for files which aren't directly executable). This means that if you do `./test.py` in pwsh, it'll open in a new window! (I could've sworn it wasn't that way previously...)

I also wrote a [bit of code](https://github.com/CAD97/win-ftype) to read the file type associations, which appears to be working, but it's a huge tail of edge cases. It might be better to just use `ShellExecuteEx` on windows, with the `SEE_MASK_NO_CONSOLE` flag to inherit the parent's console. Using `ShellExecuteEx` also allows us to easily tell the difference between opening the file failing (returns `FALSE`; check `GetLastError`) and the process failing (outptr process handle).

**Comment by rgwood** [comment]
Nice, thanks for the research.

I'm kinda leaning toward leaving things as-is, since the desired Python functionality works as expected. Are there specific cases you'd like to behave differently?

**Comment by PJB3005** [comment]
Sorry if I should open a new issue for this, but this still seems broken if the Python script you're trying to run isn't in the current directory:

![image](https://github.com/nushell/nushell/assets/8107459/583201f2-ba04-45d7-b80c-8bfd6126b096)

**Comment by pfmoore** [comment]
> Did a bit of research. https://github.com/PowerShell/PowerShell/pull/4523 [ShellExecuteEx](https://docs.microsoft.com/en-us/windows/win32/shell/launch) to launch documents (their name for files which aren't directly executable). This means that if you do ./test.py in pwsh, it'll open in a new window! (I could've sworn it wasn't that way previously...)

Sorry to comment on an old and closed issue, but this is not the case for me. If you have `.py` in your `PATHEXT` environment variable, it *does* run the command in the same console window - I've tested this in both Powershell (powershell.exe) and Powershell Core (pwsh.exe). Without the `PATHEXT` setting, it does open a new window as you describe.

**Comment by pfmoore** [comment]
This is a really useful bit of functionality, which I'd like to have available (in some form - it doesn't have to be via the `PATHEXT` mechanism) in nushell.
