### ISSUE TITLE
Support for SSH Key Management by Secretive ( macOS )

### ISSUE THREAD

**Issue by KitAdams** [nushell/nushell#6445]
### Related problem

nushell does not respect / recognise SSH Keys created & managed by Secretive ( macOS SSH Key Manager - https://github.com/maxgoedjen/secretive )

<img width="477" alt="image" src="https://user-images.githubusercontent.com/47960871/187310627-02c4fe94-1786-4523-b965-a214e76d6ea8.png">

### Describe the solution you'd like

For nushell to respect / recognise ssh keys created and managed by Secretive for macOS.

### Describe alternatives you've considered

Creating another ssh key using ssh-keygen and adding this to my GitHub account for when I am using nushell.

Pretty annoying and doesn't provide the benefits that Secretive gives.

**Comment by fdncred** [comment]
I have no clue what this issue is about because I'm pretty sure nushell knows nothing about ssh keys. I wonder if some env vars aren't set or something like that, or the keys/tools are not in the path.

**Comment by fdncred** [comment]
Ah ha! https://github.com/maxgoedjen/secretive/blob/main/FAQ.md#secretive-doesnt-work-with-my-git-clientapp

> Secretive relies on the SSH_AUTH_SOCK environment variable being respected.

sounds like you need to make sure you're setting this env var.

**Comment by KitAdams** [comment]
Ahhh thank you!!

I somehow missed that when attempting to troubleshoot

**Comment by KitAdams** [comment]
FYI

Even though the env is set properly there is extra config needed. 

Add the below to your ``~/.ssh/config`` :
```
Host *
	IdentityAgent /Users/<UserName>/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
```
