### ISSUE TITLE
I/O error when loading SQLite database

### ISSUE THREAD

**Issue by generic-github-user** [nushell/nushell#6451]
### Describe the bug

While attempting to work with an SQLite (3) database on Ubuntu 20.04 LTS with nushell version 0.61.0, I get the following error:

```
Error: nu::shell::io_error (link)

  × I/O error
  help: can't follow stream paths
```

I was able to open the database file and preview its raw content; the issue arose when trying to use `get`, `find`, `schema`, or `metadata` in a pipeline. I tried renaming the target file with a `.db` extension but this did not seem to change the behavior.

### How to reproduce

The command I used was equivalent to `open ./test.db | get table`.

### Expected behavior

I hoped that nu would correctly detect the database format and convert it into a table so that I could manipulate it.

### Configuration

| key                | value                      |
| ------------------ | -------------------------- |
| version            | 0.61.0                     |
| branch             |                            |
| tag                |                            |
| build_os           | linux-x86_64               |
| rust_version       | rustc 1.59.0               |
| cargo_version      | cargo 1.59.0               |
| pkg_version        | 0.61.0                     |
| build_time         | 2022-08-30 21:52:18 -04:00 |
| build_rust_channel | release                    |
| features           | default, trash, which, zip |
| installed_plugins  |                            |

**Comment by fdncred** [comment]
That's odd. I'm using it in WSL without issue.
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```
But i'm also on version 0.67.1. I wonder if something changed since 0.61. You might try upgrading.

**Comment by generic-github-user** [comment]
I did actually try using `cargo install-update`  but encountered an "error: could not find `nu` in registry `crates-io` with version `=0.67.0`"; is there a specific registry I need to add to update to 0.67?

**Comment by fdncred** [comment]
I don't install from cargo. I always clone the repo and use one of the install scripts. However, when i do `cargo search nu` it shows as the first item on the list. I also always install with `--features=extra` so I get dataframes and sqlite.

**Comment by generic-github-user** [comment]
There seems to be something wrong with my `cargo` installation. I was able to get this working using the prebuilt binary for 0.67.0.
