### ISSUE TITLE
High CPU usage when launched from file explorer

### ISSUE THREAD

**Issue by AadamZ5** [nushell/nushell#6452]
### Describe the bug

When the `nu` executable is ran from a GUI file explorer, no terminal is opened (expected) but the `nu` process runs and consumes upwards of 95% of CPU. 

This is observed in Pop OS, a distro based on Ubuntu. 
I've installed `nu` with `cargo install nu --features="extra,static-link-openssl"`

### How to reproduce

1. Open a task-viewer or updating process viewer (like `top` or `htop` or `btop++`)
2. In a comparable distribution, navigate to the binary location using a GUI file explorer
3. Double-click on the `nu` binary
4. Observe the process CPU usage in your process viewer and verify it is high
5. Kill the process
6. Open a terminal prompt
7. Start `nu` in the terminal
8. Observe the process CPU usage is normal

### Expected behavior

I expected `nu` to "run" without consuming high amounts of my CPU when I run it from the file-explorer GUI. I did not expect a terminal to open or the program to be usable without being invoked from a terminal.

I think I can agree that this is an unsupported launch method for the shell, but the high CPU usage is easy to miss if you do not have a process-viewer open.

### Screenshots

I launched `nu` twice from the file-explorer GUI. See the two pegged CPU cores with two rogue `nu` processes.
![image](https://user-images.githubusercontent.com/15809427/187723924-ced7c9e4-9f18-4494-9644-19a7e2201a6e.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.62.0 (a8314ef7d 2022-06-27)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.62.0 (a748cf5a3 2022-06-08)             |
| pkg_version        | 0.67.0                                          |
| build_time         | 2022-08-31 10:55:39 -04:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

This is observed in Pop OS, a distro based on Ubuntu. 
I've installed `nu` with `cargo install nu --features="extra,static-link-openssl"`

**Comment by generic-github-user** [comment]
I also observed this on Ubuntu with KDE Plasma. The process was not readily visible in the system monitor.

**Comment by sholderbach** [comment]
Interesting! Launching on Windows from the GUI is fine for me. It launches an interactive terminal window which should be the behavior without arguments. (I would have thought that might actually be more involved with the whole `conhost.exe` complication on Windows where the terminal is kind of a second class citizen)

Pure speculation: We probably get into a busy loop waiting for terminal events but if no terminal is launched that's a recipe for desaster. So we probably have to detect in what context a new process without arguments is running, before we decide to block on events.

**Comment by sholderbach** [comment]
It is worse than I thought:

I attached myself with `sudo gdb --pid <PID of the spinning process>`

![image](https://user-images.githubusercontent.com/15833959/188210932-01e477ff-ccab-4027-b04e-a806570b855e.png)

By just randomly halting the execution I noticed that I covered a lot of the code for the interactive REPL in `nu_cli::repl::evaluate_repl()`

Setting a breakpoint on the line where we shell out to our `reedline` line editor revealed, that we get an eror that we handle by just printing it into nirvana.

![image](https://user-images.githubusercontent.com/15833959/188213509-21cb3649-1772-4e6e-b568-fe3b5e4e99fe.png)

Hitting `continue` in gdb got me to loop around as if there was a user doing something wrong again and again and again... (see first screenshot)

---

**PS:** starting a process from the GUI is a surprisingly hard thing in GNOME land. Apparently they decided that it is too much of a security risk to even have the GUI option to launch an ELF from `nautilus` (or cinnamon's `nemo` for that matter)... had to quickly install `dolphin` to reproduce that
