### ISSUE TITLE
Nushell print out panic message while register plugin from command line

### ISSUE THREAD

**Issue by WindSoilder** [nushell/nushell#6473]
### Describe the bug

When we have `nu` and `nu_plugin` in the same directory, typing register command will make `nu` output panic message

### How to reproduce

1. make `nu` and one `nu_plugin`(take `nu_plugin_example` as exmple) inside the same directory, `/tmp` as example
2. type: `register -e msgpack /tmp/nu`
3. nushell pop out panic message

### Expected behavior

nushell shoudn't pop out panic message.

### Screenshots

[![asciicast](https://asciinema.org/a/L3wi7dbHtL1ZRb22zJYxOMYKm.svg)](https://asciinema.org/a/L3wi7dbHtL1ZRb22zJYxOMYKm)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.67.1                                   |
| branch             | plugin_protocol                          |
| commit_hash        | b88ace4cde422f7242af68faa1169102259b3a8f |
| build_os           | macos-x86_64                             |
| build_target       | x86_64-apple-darwin                      |
| rust_version       | rustc 1.62.0 (a8314ef7d 2022-06-27)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.62.0 (a748cf5a3 2022-06-08)      |
| pkg_version        | 0.67.1                                   |
| build_time         | 2022-08-28 08:05:16 +08:00               |
| build_rust_channel | release                                  |
| features           | default, trash, which, zip               |
| installed_plugins  | from-binary                              |

Hmm...I reproduce this in latest main, not sure why `version` shows up the branch value to my local branch...
### Additional context

I've checked relative source code, and found that while typing `register -e msgpack `, then a valid executable binary path, it will spawn the process(`nu` as example).

Then nushell fall into trouble to communicate with `spawned` process, finally leads to panic message.

**Comment by fdncred** [comment]
ya, I've seen this many times. it's like nushell is trying to register files while typing instead of when we hit enter. maybe we could change it to where it only works on nu_plugin* instead of trying any valid executable?

**Comment by WindSoilder** [comment]
Thanks for your suggestion, I think that's a good and fast point to start
