### ISSUE TITLE
Package `nu v0.2.0` does not have these features: `raw-key`

### ISSUE THREAD

**Issue by joedborg** [nushell/nushell#648]
Not sure why this is happening, because I can see the options in the cargo.toml.

```bash
➜ cargo +nightly install nu --features raw-key,clipboard
    Updating crates.io index
  Downloaded nu v0.2.0
  Downloaded 1 crate (1.8 MB) in 1.76s
  Installing nu v0.2.0
error: failed to compile `nu v0.2.0`, intermediate artifacts can be found at `/tmp/cargo-installJ3KCk7`

Caused by:
  Package `nu v0.2.0` does not have these features: `raw-key`

~ took 29s 
➜ cargo +nightly install nu --features all              
    Updating crates.io index
  Installing nu v0.2.0
error: failed to compile `nu v0.2.0`, intermediate artifacts can be found at `/tmp/cargo-installPyydEy`

Caused by:
  Package `nu v0.2.0` does not have these features: `all`
```

**Comment by jonathandturner** [comment]
These may have been added after the 0.2.0 release. Are you building the release or from github?

If it's the 0.2.0 release, you can do:

```
cargo +nightly install nu --all-features
```

To get everything (and I think "raw-key" was "rawkey" in the release)

**Comment by joedborg** [comment]
That command works, thanks!

**Comment by ralvessa** [comment]
I tried to install with:

```cargo +nightly install nu --features raw-key```

I got the same error as mentioned in this issue. However, it worked without the hyphen:

```cargo +nightly install nu --features rawkey```

Should the `README.md` be updated to use `--all-features` instead?
