### ISSUE TITLE
`path split` erroneously splits on `C:`

### ISSUE THREAD

**Issue by Lightfire228** [nushell/nushell#6482]
### Describe the bug

```nu
$env.PWD | path split
```
produces
```
╭───┬──────╮
│ 0 │ C:   │
│ 1 │ \    │
│ 2 │ Temp │
╰───┴──────╯
```

### How to reproduce

```nu
$env.PWD | path split
```

### Expected behavior

```nu
╭───┬──────╮
│ 0 │ C:\  │
│ 1 │ Temp │
╰───┴──────╯
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.0                                          |
| branch             |                                                 |
| commit_hash        | 91976988f032276ca48faff2d1ac13c079eda836        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.67.0                                          |
| build_time         | 2022-08-17 15:20:56 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by rgwood** [comment]
Interesting issue. We're basically taking the output of Rust's [`Path.components()`](https://doc.rust-lang.org/std/path/struct.Path.html#method.components) and converting each component to a string.

This Rust code:
```rust
let path = PathBuf::from(r"C:\Temp");
dbg!{path.components()};
```
prints this:
```rust
Components(
    [
        Prefix(
            PrefixComponent {
                raw: "C:",
                parsed: Disk(
                    67,
                ),
            },
        ),
        RootDir,
        Normal(
            "Temp",
        ),
    ],
)
```

Rust might have valid reasons for splitting Prefix and RootDir like that, but it does feel a little unexpected in `path split`. 

## Open Questions

1. Should we fix this (I think the answer is yes)?
    a. If yes, should the first component be `C:` or `C:\`?

**Comment by Lightfire228** [comment]
I think the answer to 1.a. is `C:`, since the other splits don't include the path separator, either

**Comment by rgwood** [comment]
`path split` includes the root directory as `/` on *nix systems:

![image](https://user-images.githubusercontent.com/26268125/188343472-ebee48b0-ea73-4fdc-91c7-5d9f9bd11b38.png)

**Comment by Lightfire228** [comment]
now that i think about it, that does actually make sense, because the folder name is indeed `/` or `C:\` 

as long as someone doesn't naively join on `\` (which they shouldn't since `path join` exists)

(fwiw, `cd C:` doesn't work without the backslash either)

**Comment by rgwood** [comment]
> (fwiw, `cd C:` doesn't work without the backslash either)

It does change the drive to C:, but it doesn't go to the root directory if we're already on the C drive. That _feels_ right to me but I'm not 100% sure we've got it right.

**Comment by rgwood** [comment]
Anyway, for this issue it sounds like the first component should be `C:\` - I think we're in agreement on that but just let me know if I've misunderstood you.
