### ISSUE TITLE
register should auto-detect format

### ISSUE THREAD

**Issue by hyiltiz** [nushell/nushell#6503]
### Related problem

Currently, there are only two formats that `register` can use to load plugins. It should be possible to make `-e` optional, rather than mandatory, by attempting to parse the provided file with the `capnp` and `json` parsers, and pick the successful one. This provides convenience and usability without introducing too much performance penalties. If no other formats are planned to be introduced, then we can even just check if the file is plain text vs. binary.

### Describe the solution you'd like

`register nu_plugin_custom_values` should work, maybe taking twice the time it takes compared to `register -e capnp nu_plugin_custom_values`.

### Describe alternatives you've considered

`register -e capnp nu_plugin_custom_values`

### Additional context and details

Programs should only ask the user to specify input when required; in this case, explicitly specifying the format offers no benefit, as there is no room for confusion/incorrect parsing.

**Comment by fdncred** [comment]
1. There's a PR up with this now https://github.com/nushell/nushell/pull/6486
2. capnp isn't an option any longer
3. there is a register-plugins.nu script that makes it easier.
