### ISSUE TITLE
nushell 0.66.2 no integration git

### ISSUE THREAD

**Issue by Silentdoer** [nushell/nushell#6507]
### Describe the bug

![nushell](https://user-images.githubusercontent.com/30740234/188806040-603416c9-2eef-4a2d-a5b3-bec1432134c9.PNG)

left is nu 0.34.0, right is nu 0.66.2

### How to reproduce

1.just open nu 0.34 and 0.66.2

### Expected behavior

nu 0.66.2 integration git like nu 0.34.0

### Screenshots

![nushell](https://user-images.githubusercontent.com/30740234/188806465-448d70c6-2061-4ede-82e2-c0226ce34048.PNG)

### Configuration

default configuration

**Comment by jntrnr** [comment]
We don't use git by default now, I believe because we had some performance issues with large repos.

You can find some example prompts in the repo, some of which include support for git: https://github.com/nushell/nu_scripts/tree/main/prompt
