### ISSUE TITLE
`source-env` panics

### ISSUE THREAD

**Issue by nibon7** [nushell/nushell#6510]
### Describe the bug

```
nibon7@yoga14s /data/source/nushell % 'let-env PROMPT_INDICATOR = { "| " }' | save panic.nu                                               09/07/2022 09:17:19 PM
nibon7@yoga14s /data/source/nushell % source-env panic.nu                                                                                 09/07/2022 09:18:08 PM
thread 'main' panicked at 'internal error: missing block', crates/nu-protocol/src/engine/engine_state.rs:677:14
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_display
   3: core::panicking::panic_str
   4: core::option::expect_failed
   5: core::option::Option<T>::expect
             at /rustc/1.62.1/library/core/src/option.rs:718:21
   6: nu_protocol::engine::engine_state::EngineState::get_block
             at ./crates/nu-protocol/src/engine/engine_state.rs:675:9
   7: nu_cli::prompt_update::get_prompt_string::{{closure}}
             at ./crates/nu-cli/src/prompt_update.rs:38:29
   8: core::option::Option<T>::and_then
             at /rustc/1.62.1/library/core/src/option.rs:1242:24
   9: nu_cli::prompt_update::get_prompt_string
             at ./crates/nu-cli/src/prompt_update.rs:30:5
  10: nu_cli::prompt_update::update_prompt
             at ./crates/nu-cli/src/prompt_update.rs:127:35
  11: nu_cli::repl::evaluate_repl
             at ./crates/nu-cli/src/repl.rs:317:13
  12: nu::main
             at ./src/main.rs:366:31
  13: core::ops::function::FnOnce::call_once
             at /rustc/1.62.1/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
101 nibon7@yoga14s /data/source/nushell (git)-[main] %
```

PS: Seems `num_blocks < block_id `, and `engine_state.get_block(block_id)` panics

### How to reproduce

1. 'let-env PROMPT_INDICATOR = { "| " }' | save panic.nu
2. source-env panic.nu

### Expected behavior

Nu should not panic

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.68.1                                   |
| branch             | main                                     |
| commit_hash        | 80624267fd0d2ad94346cde7d462ccc05f74e4e0 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.62.1 (gentoo)                    |
| cargo_version      | cargo 1.62.1                             |
| pkg_version        | 0.68.1                                   |
| build_time         | 2022-09-07 21:14:57 +08:00               |
| build_rust_channel | debug                                    |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

**Comment by jntrnr** [comment]
@kubouch - I wonder if we could keep the block around even if the value is going out of scope, so at least if we see a block id later, it's still pointing to something the engine knows about.

**Comment by kubouch** [comment]
> @kubouch - I wonder if we could keep the block around even if the value is going out of scope, so at least if we see a block id later, it's still pointing to something the engine knows about.

How do we keep the block around?

**Comment by kubouch** [comment]
> > @kubouch - I wonder if we could keep the block around even if the value is going out of scope, so at least if we see a block id later, it's still pointing to something the engine knows about.
> 
> How do we keep the block around?

Maybe we could clone it from the temporary engine state, put it to the Stack and merge it into the EngineState in the next REPL cycle during `merge_env()`.

Alternatively, we'd require `source-env` to accept a static path, like the old `source`, but that's a step backwards. Maybe it's better to go with the ugly block hack.

**Comment by kubouch** [comment]
I'm not actually sure if it's possible to keep the block around. The block might call a command with a Decld pointing into the discarded engine state.
