### ISSUE TITLE
pipe broken (fd -> fzf) in 0.68

### ISSUE THREAD

**Issue by danjenson** [nushell/nushell#6516]
### Describe the bug

Try to pipe fd to fzf: `fd . . | fzf +m`, which worked in the previous version and works in bash, but now fails in nushell 0.68.

### How to reproduce

Run `fd . . | fzf +m` -- it stops allowing input to the user as soon as the search completes.

### Expected behavior

You could continue to interact with input.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.68.0                                          |
| branch             | master                                          |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.65.0-nightly (addacb587 2022-08-24)     |
| rust_channel       | nightly-x86_64-unknown-linux-gnu                |
| cargo_version      | cargo 1.65.0-nightly (6da726708 2022-08-23)     |
| pkg_version        | 0.68.0                                          |
| build_time         | 2022-09-07 13:06:51 -07:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by sholderbach** [comment]
Maybe in the same family as #6496 around piping between external commands. #6273 landed in this release.

**Comment by dandavison** [comment]
Hi @danjenson, what OS are you using?

**Comment by danjenson** [comment]
Void LInux

**Comment by jntrnr** [comment]
Fixes with https://github.com/nushell/nushell/pull/6542
