### ISSUE TITLE
`use` with a path to module

### ISSUE THREAD

**Issue by danjenson** [nushell/nushell#6517]
### Describe the bug

Now that we are switching from `source` to `use`, how do we import a module that is in a completely different directory? I.e., none of the following work
```nushell
use ~/.config/eww/eww.nu
use ~/.config/eww/eww
use /home/danj/.config/eww.nu
use /home/danj/.config/eww
```

As a side note, it feels burdensome to provide an explicit `export` for each command, should we instead use `private` to indicate which functions we aren't importing? 

### How to reproduce

Try one of the above use commands.

### Expected behavior

Would be able to import one of the above commands.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.68.0                                          |
| branch             | master                                          |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.65.0-nightly (addacb587 2022-08-24)     |
| rust_channel       | nightly-x86_64-unknown-linux-gnu                |
| cargo_version      | cargo 1.65.0-nightly (6da726708 2022-08-23)     |
| pkg_version        | 0.68.0                                          |
| build_time         | 2022-09-07 13:06:51 -07:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
Have you read the documentation for modules and overlays?
https://www.nushell.sh/book/modules.html
https://www.nushell.sh/book/overlays.html

I thought it explained how this worked.

**Comment by kubouch** [comment]
It is not clear what you're asking. It is possible to call `use` on files from any directory. Please, provide a full minimal working example of what is not working.

**Comment by danjenson** [comment]
Ah, I was missing the '*' -- many of the earlier examples omit it, I assume because they are working from a REPL. Incidentally, will we eventually have to `export` all functions in our `config.nu` in order for them to be available from the shell REPL? Is there any way to declare an entire module public, similar to standard rust, in order to avoid adding `export` to every declaration?

**Comment by kubouch** [comment]
Currently, there is not, you need to use `export` for anything you wish to export.

I'll close this since the issue seems solved.
