### ISSUE TITLE
Save to html without Escaping/Wrapping

### ISSUE THREAD

**Issue by storyfeet** [nushell/nushell#6528]
### Related problem

I have a program that I use to generate html from a markdown file. This outputs the html to stdout.

When I save this output file as "rules" it saves it correctly, but when I save it to "rules.html" it escapes everything, so the html is not what I wanted.

I can work around this by 
```
myprog | save temp
mv temp rules.html
```
But it's really awkward

### Describe the solution you'd like

Option 1:

Change ```save``` so that when writing to ```.html``` simple string data is not wrapped in a table. or escaped. 

People who want html wrapping can use ```to html```

Option 2:

Add a  -```-no-escape``` flag.

Option 3

Or consider turning it off by default and having an ```escape``` command that can ```escape sql``` ```escape html``` etc

**Comment by fdncred** [comment]
does `save -r` help?

**Comment by storyfeet** [comment]
yes, my bad, I swear I looked,
