### ISSUE TITLE
`overlay use 'quoted-module-name'` creates an overlay that cannot be removed

### ISSUE THREAD

**Issue by Lightfire228** [nushell/nushell#6529]
### Describe the bug

if you `overlay use 'test'`, the overlay is created with the name `'test'`, but cannot be removed with `overlay hide` nor `overlay hide 'test'`

### How to reproduce

```nu

> module test {}
> overlay use 'test'
> overlay hide test

Error: nu::shell::overlay_not_found (link)

  × Overlay 'test' not found
   ╭─[entry #5:1:1]
 1 │ overlay hide test
   ·              ──┬─
   ·                ╰── overlay not found
   ╰────

> overlay hide 'test'
Error: nu::parser::active_overlay_not_found (link)

  × Active overlay not found.
   ╭─[entry #6:1:1]
 1 │ overlay hide 'test'
   ·              ───┬──
   ·                 ╰── not an active overlay
   ╰────

> overlay list
╭───┬────────╮
│ 0 │ zero   │
│ 1 │ 'test' │
╰───┴────────╯

```

### Expected behavior

either 
1. Throw an error saying that `'` is an illegal overlay identifier character
2. nu ignores the quotes, and creates the overlay with the name `test`
3. nu creates the overlay with the name `'test'`, and `overlay hide 'test'` succeeds

### Screenshots

![image](https://user-images.githubusercontent.com/15241322/189391272-5d5fd5dc-92e3-48cc-8296-12baf32fecde.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.68.1                                          |
| branch             |                                                 |
| commit_hash        | e76b3d61deef832adce76b0f73f19131de8cbc9e        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.68.1                                          |
| build_time         | 2022-09-08 21:41:56 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by Kangaxx-0** [comment]
I can take a look at this one
