### ISSUE TITLE
`fzf` freezes the shell in version `0.68.1` 

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#6534]
### Describe the bug

i have some `nushell` functions, see the context down below, using `fzf` which are not working anymore...

- `ghq list | fzf` shows me the list of my local repositories but freezes and does not let me choose a repo
- `cfg lf | fzf` (`cfg` and `lf` are aliases for my `git` config. Here, `cfg lf` shows the lists of all my tracked config files) does not show anything and freezes before the `fzf` menu itself
- same with `cat ~/.bashrc | fzf`, no output at all

when this occurs, i have to kill the terminal...

however, a standalone `fzf`, i.e. listing all the files in my HOME, works fine

all the commands above where working in `0.67.0` but stopped when i updated today to `0.68.1`

cheers :wink: :yum: 

### How to reproduce

1. install `nushell`, `ghq` and `fzf`
2. run the commands
  - `ghq list | fzf`
  - `cat .bashrc | fzf`
  - `fzf`
3. note that the first two do not work but the third does

### Expected behavior

i would like `ghq list | fzf` to allow me to seach through the list of local repositories
i would like `cat ~/.bashrc | fzf` not to freeze and show something

## Does not work in
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.68.1                                          |
| branch             |                                                 |
| commit_hash        | e76b3d61deef832adce76b0f73f19131de8cbc9e        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.63.0 (Arch Linux rust 1:1.63.0-1)       |
| cargo_version      | cargo 1.63.0                                    |
| pkg_version        | 0.68.1                                          |
| build_time         | 2022-09-10 09:52:14 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

## Did work in 
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.67.0                                          |
| branch             |                                                 |
| commit_hash        | 2ef9cc118e7cd98341f93eb8f30a45b4051b3c98        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.63.0 (Arch Linux rust 1:1.63.0-1)       |
| cargo_version      | cargo 1.63.0                                    |
| pkg_version        | 0.67.0                                          |
| build_time         | 2022-09-04 11:30:04 +02:00                      |
| build_rust_channel | debug                                           |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

the context for the commands above can be found in my `nushell` scripts:

### `ghq list | fzf`
the [`repo`](https://github.com/amtoine/dotfiles/blob/fix/nushell/scripts/.config/nushell/scripts/functions.nu#L23) function

### `cfg lf | fzf`
the [`vcfg`](https://github.com/amtoine/dotfiles/blob/fix/nushell/scripts/.config/nushell/scripts/functions.nu#L82) function

## NOTES
i've changed `empty?` to `is-empty` but that did not solve the issue

**Comment by fdncred** [comment]
Most of this is too complicated to debug because I have no idea what `ghq` is nor what `cfg` is. However, I can get `open some file | fzf` to work. So, this may have something to do with how externals are handled.

**Comment by amtoine** [comment]
> Most of this is too complicated to debug because I have no idea what `ghq` is nor what `cfg` is.
>
1. [`ghq`](https://github.com/x-motemen/ghq) is a `git` repositories manager -> `ghq list` gives a list of repository paths, one per line, e.g. i have two forks of some `nushell` repos, and thus 
```bash
> ghq list | grep nushell
github.com/amtoine/nushell
github.com/amtoine/nushell.github.io
```

2. `cfg` is an alias for my dotfiles, namely `alias cfg = ^git --git-dir ($env.HOME | path join ".dotfiles") --work-tree $env.HOME` and `git lf` lists all the tracked files inside a repository
in the end, `cfg lf` lists all my dotfiles!
e.g. my `nushell` config 
```bash
cfg lf | grep nushell
.config/nushell/config.nu
.config/nushell/env.nu
.config/nushell/login.nu
.config/nushell/scripts/aliases.nu
.config/nushell/scripts/colors.nu
.config/nushell/scripts/completions.nu
.config/nushell/scripts/final.nu
.config/nushell/scripts/functions.nu
.config/nushell/scripts/hooks.nu
.config/nushell/scripts/keybindings.nu
.config/nushell/scripts/menus.nu
.config/nushell/scripts/themes.nu
```

these are custom commands of course, hope my explainations make sense :relieved: 
in the end, `ghq list` and `cfg lf` only produce lines of raw texts with one path per line :+1: 

> However, I can get `open some file | fzf` to work. So, this may have something to do with how externals are handled.
>
agree, `ghq`, `cfg`, a.k.a. `git`, and `cat` do not work, but `open ~/.bashrc | fzf` does :open_mouth:

**Comment by dandavison** [comment]
Hi @amtoine, thanks for this, I suspect what you're encountering is this issue: https://github.com/nushell/nushell/issues/6496. 

What OS are you using?

**Comment by amtoine** [comment]
> Hi @amtoine, thanks for this,
>
hey :yum: 

> I suspect what you're encountering is this issue: #6496.
>
that's quite similar indeed :open_mouth: 
 
> What OS are you using?
>
i'am on vanilla ArchLinux!

**Comment by fdncred** [comment]
Good catch @dandavison. I reproduced the behavior on my Mac m1 too. I'd love to solve this issue once and for all. I've seen it creep up too many times recently.

**Comment by amtoine** [comment]
second time i have of an M1 chip / MacOs issue but on my asus / ArchLinux machine :sob: 
i might be cursed :shrug: :yum:

**Comment by dandavison** [comment]
Yes, I can also reproduce a hang with `fzf` on MacOS (also reported here: https://github.com/nushell/nushell/issues/6516).

That is interesting that you're _not_ on MacOS @amtoine!

Looks like https://github.com/nushell/nushell/issues/6496 is the place to discuss further.

**Comment by amtoine** [comment]
@dandavison 

> That is interesting that you're not on MacOS @amtoine!
>
it is indeed :open_mouth: 

> Looks like #6496 is the place to discuss further.
>
mm the original issue from #6496 with `yes | head -n 999 | with-env [LESS ""] { less }` does not occur on my machine
but still the same with `ghq`, `cat` and `fzf` :confused:

**Comment by dandavison** [comment]
I wonder if we can simplify the report here: I suspect that it doesn't matter what you are piping into `fzf`. Can you confirm that this shows the bug on your machine:

```
^yes | ^head -n 999 | fzf
```

**Comment by amtoine** [comment]
> I wonder if we can simplify the report here: I suspect that it doesn't matter what you are piping into `fzf`. Can you confirm that this shows the bug on your machine:
>
> ```
> ^yes | ^head -n 999 | fzf
> ```
>
it does work :thinking: 

but `cat README.md | less` and do `cat README.md | fzf` not :confused: 
this is the `README.md` from this very repo :+1: 

and, still from this repo source
`yes | head -n 999 | git -c core.pager=less log` works
`yes | head -n 999 | with-env [LESS ""] { less }` works

**Comment by amtoine** [comment]
thanks a lot guys :star_struck: 

i built `nushell` with `cargo build --workspace --features=extra; cargo run --features=extra` on latest revision, i.e. `4490e97a1`
and all the issues above are gone :+1: 

 :point_down: below is the new working version of `nushell` :point_down: 
 | column0            | column1                                         |
| ------------------ | ----------------------------------------------- |
| version            | 0.68.2                                          |
| branch             | main                                            |
| commit_hash        | 4490e97a13b35ed47b1ee8648f8ec8c169a0ebc3        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.63.0 (Arch Linux rust 1:1.63.0-1)       |
| cargo_version      | cargo 1.63.0                                    |
| pkg_version        | 0.68.2                                          |
| build_time         | 2022-09-12 08:22:14 +02:00                      |
| build_rust_channel | debug                                           |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |
