### ISSUE TITLE
`help` panic on unknown command

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#6536]
### Describe the bug

`help` panic on unknown command with the latest main branch

### How to reproduce

Run `help ddd` will get:

```
Error: nu::shell::command_not_found (link)

  × Command not found
   ╭─[entry #1:1:1]
 1 │ help ddd
   · thread 'main' panicked at 'assertion failed: line_range.contains(&offset)', /Users/hustcer/.cargo/registry/src/github.com-1ecc6299db9ec823/miette-5.3.1/src/handlers/graphical.rs:622:9
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: miette::handlers::graphical::GraphicalReportHandler::visual_offset
   4: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   5: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
   6: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
   7: miette::handlers::graphical::GraphicalReportHandler::render_single_line_highlights
   8: miette::handlers::graphical::GraphicalReportHandler::render_context
   9: miette::handlers::graphical::GraphicalReportHandler::render_snippets
  10: miette::handlers::graphical::GraphicalReportHandler::render_report
  11: <nu_protocol::cli_error::CliError as core::fmt::Debug>::fmt
  12: core::fmt::write
  13: <&std::io::stdio::Stderr as std::io::Write>::write_fmt
  14: std::io::stdio::_eprint
  15: nu_cli::util::eval_source
  16: nu_cli::repl::evaluate_repl
  17: nu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Expected behavior

There should be no panic

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.68.1                                          |
| branch             | develop                                         |
| commit_hash        | 02f92fa5279100c5695da125cf63c2493f953abe        |
| build_os           | macos-x86_64                                    |
| build_target       | x86_64-apple-darwin                             |
| rust_version       | rustc 1.61.0 (fe5b13d68 2022-05-18)             |
| rust_channel       | 1.61.0-x86_64-apple-darwin                      |
| cargo_version      | cargo 1.61.0 (a028ae42f 2022-04-29)             |
| pkg_version        | 0.68.1                                          |
| build_time         | 2022-09-08 09:57:17 +08:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | gstat, query, query json, query web, query xml  |

**Comment by hustcer** [comment]
It seemed that an unknown command will make it panic too, such as `ddd`

**Comment by fdncred** [comment]
miette 5.3.1 has been yanked so rebuilding fixes this problem now. closing.
