### ISSUE TITLE
miette version 5.3.1 may causes crash/panic with certain errors

### ISSUE THREAD

**Issue by jakeswenson** [nushell/nushell#6541]
### Describe the bug

I upgraded from `0.67.0` to `0.68.1` using the command `cargo install nu --force --features=extra`

After the upgrade I'm getting a nushell panic when certain errors happen (not clear specifically which errors trigger this) most notably when a command is not found, like typing `asdf`.

### How to reproduce

1. Install nu `0.68.1` using cargo, unlocked, with `cargo install nu --force --features=extra`
2. Start an observable nushell... (i.e. `RUST_BACKTRACE=1 nu`)
3. type `asdfasdfasdf` (or a command that doesn't exist) and hit enter.
4. Notice crash/panic

```
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #1:1:1]
 1 │ asdf
   · thread 'main' panicked at 'assertion failed: line_range.contains(&offset)', /Users/.../.cargo/registry/src/github.com-1ecc6299db9ec823/miette-5.3.1/src/handlers/graphical.rs:622:9
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: miette::handlers::graphical::GraphicalReportHandler::visual_offset
   4: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   5: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
   6: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
   7: miette::handlers::graphical::GraphicalReportHandler::render_single_line_highlights
   8: miette::handlers::graphical::GraphicalReportHandler::render_context
   9: miette::handlers::graphical::GraphicalReportHandler::render_snippets
  10: miette::handlers::graphical::GraphicalReportHandler::render_report
  11: <nu_protocol::cli_error::CliError as core::fmt::Debug>::fmt
  12: core::fmt::write
  13: <&std::io::stdio::Stderr as std::io::Write>::write_fmt
  14: std::io::stdio::_eprint
  15: nu_cli::util::eval_source
  16: nu_cli::repl::evaluate_repl
  17: nu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Notice `miette` crashed with an assertion failure.
miette version: `miette-5.3.1`

### Expected behavior

Nu shell should not crash/panic.

### Screenshots

error make works fine:
![image](https://user-images.githubusercontent.com/1854799/189539903-f089789b-2d0b-4a20-9470-802a21d95f53.png)

### Configuration

not required

### Additional context

Discord thread discussing this: https://discord.com/channels/601130461678272522/1018540372441444402

Turns out I installed `nu` using the latest version of `miette` and not the locked version.
Using `cargo install nu --force --features=extra --locked` solved the issue.

**Comment by jakeswenson** [comment]
Filed a bug with `miette` as well: zkat/miette#203

**Comment by fdncred** [comment]
miette 5.3.1 has been yanked so rebuilding fixes this problem now. closing.
