### ISSUE TITLE
File not found: 3 when passing argument to script

### ISSUE THREAD

**Issue by cnrmck** [nushell/nushell#6543]
### Describe the bug

Error 
File not found: 3
when calling script with nu

### How to reproduce

Create `test.nu`
```
def main [number: int] {
  echo $number
}
```

Run `nu ./test.nu 3` 

See `File not found: 3` 

### Expected behavior

It executes my script and prints the number 3

### Configuration

| key                                                                                                                                                                     | value              |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------ |
| 0.40.0                                                                                                                                                                  | version            |
| main                                                                                                                                                                    | branch             |
| 79c7b20c                                                                                                                                                                | short_commit       |
| 79c7b20cfdf3eed2dd6beeb684911d6b87d1eae9                                                                                                                                | commit_hash        |
| 2021-12-02 07:05:04 +00:00                                                                                                                                              | commit_date        |
| macos-x86_64                                                                                                                                                            | build_os           |
| rustc 1.56.1 (59eed8a2a 2021-11-01)                                                                                                                                     | rust_version       |
| stable-x86_64-apple-darwin                                                                                                                                              | rust_channel       |
| cargo 1.56.0 (4ed5d137b 2021-10-04)                                                                                                                                     | cargo_version      |
| 0.40.0                                                                                                                                                                  | pkg_version        |
| 2021-12-02 10:51:47 -07:00                                                                                                                                              | build_time         |
| release                                                                                                                                                                 | build_rust_channel |
| ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     | features           |
| binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath | installed_plugins  |

**Comment by fdncred** [comment]
version 0.40.0? does it still happen on the latest version?

**Comment by cnrmck** [comment]
Yeah sorry, same issue as the other one I opened. Was managing my nushell version with rustup, have now switched to brew so that shouldn't happen anymore. 

LOVING v0.68.1 :)
