### ISSUE TITLE
`version | transpose key value | to md --pretty` doesn't work with new versions

### ISSUE THREAD

**Issue by cnrmck** [nushell/nushell#6544]
### Describe the bug

Configuration step of reporting a bug show recommends the formula 
`version | transpose key value | to md --pretty` 
to export the configuration, but that gives error 
```
error: Command not found
   ┌─ shell:12:11
   │
12 │ version | transpose key value | to md --pretty
   │           ^^^^^^^^^ command transpose not found
```

### How to reproduce

Run `version | transpose key value | to md --pretty` 

### Expected behavior

Export the configuration in the way I find when I run: 
`version | rotate key value | to md --pretty`

### Screenshots

<img width="872" alt="image" src="https://user-images.githubusercontent.com/22061955/189551366-27587ec0-0299-43b6-8049-1efaad20b338.png">

### Configuration

| key                                                                                                                                                                     | value              |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------ |
| 0.40.0                                                                                                                                                                  | version            |
| main                                                                                                                                                                    | branch             |
| 79c7b20c                                                                                                                                                                | short_commit       |
| 79c7b20cfdf3eed2dd6beeb684911d6b87d1eae9                                                                                                                                | commit_hash        |
| 2021-12-02 07:05:04 +00:00                                                                                                                                              | commit_date        |
| macos-x86_64                                                                                                                                                            | build_os           |
| rustc 1.56.1 (59eed8a2a 2021-11-01)                                                                                                                                     | rust_version       |
| stable-x86_64-apple-darwin                                                                                                                                              | rust_channel       |
| cargo 1.56.0 (4ed5d137b 2021-10-04)                                                                                                                                     | cargo_version      |
| 0.40.0                                                                                                                                                                  | pkg_version        |
| 2021-12-02 10:51:47 -07:00                                                                                                                                              | build_time         |
| release                                                                                                                                                                 | build_rust_channel |
| ctrlc, dataframe, default, rustyline, term, trash, uuid, which, zip                                                                                                     | features           |
| binaryview, chart bar, chart line, fetch, from bson, from sqlite, inc, match, post, ps, query json, s3, selector, start, sys, textview, to bson, to sqlite, tree, xpath | installed_plugins  |

**Comment by fdncred** [comment]
You're on version 0.40.0. transpose didn't even exist way back then.

**Comment by cnrmck** [comment]
Yep, finally figured that out :/
