### ISSUE TITLE
Expose some commands to external world

### ISSUE THREAD

**Issue by hugosenari** [nushell/nushell#6554]
### Related problem

Nushell actually could replace some other tools like: jo, jq, jy, wget, table ...

Even if people don't download it because of shell or script, they could install as bundle of tools, 

But call `nu -c 'i need to learn nu'` isn't nice.

No I'm not asking to expose all commands, only those super cool

### Describe the solution you'd like

Provide some scripts to help user integrate it with their current shell/workflow without requiring to learn nu.

IE:
```nu
#/usr/bin/nu --stdin
# convert formats --inputFormat|-i format --outputFormat|-o format
def main [
   --inputFormat (-i): string = nuon,
   --outputFormat (-o): string = json] {
    $in |  if $inputFormat in [json]     {
        from json
    } else if $inputFormat in [nu nuon]  {
        from nuon
    } else if $inputFormat in [tml toml] {
        from toml
    } else if $inputFormat in [yml yaml] {
        from yaml
    }|     if $outputFormat in [json]     {
        to json
    } else if $outputFormat in [nuon nu]  {
        to nuon
    } else if $outputFormat in [toml tml] {
        to toml
    } else if $outputFormat in [yaml yml] {
        to yaml
    }
}
```

Now user can call

```bash
curl "http://bla.bla" | nuon -o  toml
```

Instead of 

```bash
curl "http://bla.bla" | nu --stdin -c '$in | from json | to toml'
```

### Describe alternatives you've considered

There are alternatives to that, but all them comes in different packages and installation process.

### Additional context and details

What commands expose and how expose is up to you, the one above is just a suggestion.

I know that nu_scripts have some cool ones, I liked `ymd` and `dmy`

**Comment by hugosenari** [comment]
v2 https://github.com/cruel-intentions/devshell-files/blob/master/examples/nushell/nuon.nu

**Comment by amtoine** [comment]
this is kinda cool :open_mouth: 

i'm not sure what the request here really is @hugosenari :thinking: 
this is just a script that people could download and use without dropping in the Nushell REPL, do you mean it could be somehow bundled with the `nu` binary?

**Comment by sholderbach** [comment]
We want to focus on getting the experience inside nushell right and probably won't be able to dedicate design time to get the interface of native Nu commands with an outside POSIX shell right and stable.

**Comment by hugosenari** [comment]
Closing it for now :wink:
