### ISSUE TITLE
Windows 11 is misidentified as Windows 10.

### ISSUE THREAD

**Issue by k0i** [nushell/nushell#6562]
### Describe the bug

A machine,  whose os is Windows 11 misidentified as Windows 10.

### How to reproduce

```shell
nu
sys | get host
```

### Expected behavior

`sys | get host` should correctly show os_version "Windows 11 Home" .

It seems that the [sysinfo](https://github.com/GuillaumeGomez/sysinfo/blob/master/CHANGELOG.md) crate fixes this issue on version 0.26.0.
Thus after updating the dependency version, it will be fixed.

### Screenshots

<img width="215" alt="Снимок экрана 2022-09-15 184517" src="https://user-images.githubusercontent.com/100127291/190372391-3fedacc8-a1cb-4aa1-8dfd-ceb8b2aa77d9.png">
<img width="743" alt="Снимок экрана 2022-09-15 184710" src="https://user-images.githubusercontent.com/100127291/190372842-ebd68e59-0757-4b82-a261-fdf3c27acfd2.png">

### Configuration

| key                | value                                           |                                                                                                                             | ------------------ | ----------------------------------------------- |                                                                                                                             | version            | 0.68.1                                          |                                                                                                                             | branch             |                                                 |                                                                                                                             | commit_hash        | e76b3d61deef832adce76b0f73f19131de8cbc9e        |                                                                                                                             | build_os           | windows-x86_64                                  |                                                                                                                             | build_target       | x86_64-pc-windows-msvc                          |                                                                                                                             | rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |                                                                                                                             | rust_channel       | stable-x86_64-pc-windows-msvc                   |                                                                                                                             | cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |                                                                                                                             | pkg_version        | 0.68.1                                          |                                                                                                                             | build_time         | 2022-09-08 21:41:56 +00:00                      |                                                                                                                             | build_rust_channel | release                                         |                                                                                                                             | features           | database, dataframe, default, trash, which, zip |                                                                                                                             | installed_plugins  |                                                 |

**Comment by fdncred** [comment]
What does `$nu.os-info` return?

**Comment by pedoc** [comment]
@fdncred 
![image](https://user-images.githubusercontent.com/6604230/190384479-16e0ca37-7127-4660-be64-1f7a34e24de0.png)

**Comment by fdncred** [comment]
ok, that looks better. I have a PR for the sysinfo crate but `$nu.os-info` is determined at compile time so it should be helpful too. Not to mention, it's much faster.
