### ISSUE TITLE
Partial Input Handling Support in Custom Completions

### ISSUE THREAD

**Issue by srilman** [nushell/nushell#6573]
### Related problem

I am working on Nushell support for pytest when I ran into this problem. I would like to use the text that has already been written in the shell to generate the completions. For example, if the user has typed `pytest test_example.py::`, then the extension can analyze the `test_example.py` file to get a list of test cases to complete. However, custom completions current do not take any arguments. Is there a current way to do something like this? If not, could we add support for this kind of situation? Would be glad to contribute.

### Describe the solution you'd like

Allowing custom completion functions to be defined with an optional argument. When completions are requested, the function is called with the currently typed in value. For example, 
```
  def animals [arg?: string]] {
      if $arg == null {
            ["cat", "dog", "eel" ]
      } else {
           ....  # Do something special with $arg
      }
  }

  export def my-command [animal: string@animals] {
      print $animal
  }
```

If the completion function doesn't have the optional argument, then it can do the exact same thing as it does currently.

### Additional context and details

 In pytest, we can pass in a variable number of tests to run. Tests can be specified as
- Directories `pytest path/to/tests`
- Files (that start with `test_`) `pytest path/to/tests/test_example.py` 
- Function names in a test file `pytest path/to/tests/test_example.py::test_an_example` 
- Parameterized test cases `pytest path/to/tests/test_example.py::test_param[param1]` 

In my case, I am working with a large repo where collecting all of the tests via pytest takes a significant amount of time. It would be much more pleasant if the completions could occur at a file level instead of an entire repo level, especially when there are so many. However, this requires some sort of idea of what the user has requested so far to be completed.

**Comment by kubouch** [comment]
A while back we added something similar for external completions where it passes the current line split into words: https://github.com/nushell/nushell/pull/6295

I think we should be able to add something similar for custom completions as well. If you want to work on it, that would be great! There are some other issues with completions, it would be great to get more people working on it. You can drop by our Discord, we have a completions channel where we can chat more easily.

**Comment by srilman** [comment]
Sounds good!

**Comment by antoine-de** [comment]
I tried adding `apt` completion but stopped because without this I did not see how I could complete `apt get <prefix>` with the corresponding `apt-cache search`.

**Comment by weirdan** [comment]
Completion functions now receive the entire command line, and can get the current cursor position with `commandline get-cursor`

**Comment by sholderbach** [comment]
The UX is certainly not perfect but sounds to me like the baisc behavior is there.

Feel free to reopen/open specific gripes to improve that.
