### ISSUE TITLE
Support `jsonl` in `open` and `open-df`

### ISSUE THREAD

**Issue by TehPers** [nushell/nushell#6588]
### Related problem

I have some data files that are formatted as `jsonl` (JSON lines) that would be nice to open using `open` and `open-df` for processing, but it doesn't seem like that format is supported. It would be nice if I could open them into tables and dataframes similar to JSON.

The `jsonl` format is simple. Each line contains a new JSON value. This can be treated similar to an array of JSON values, but comes with the benefit that the file can be read and processed line-by-line rather than needing to be read all at once.

### Describe the solution you'd like

`open-df` and `open` support reading from `jsonl` files.

### Describe alternatives you've considered

It wouldn't be too hard to add brackets around the contents of the file and commas at the end of every line except the last one. It would be nice not to need to do that though.

**Comment by fdncred** [comment]
Have you tried `open -r file.json | from json -o`?

**Comment by TehPers** [comment]
I saw that as well, but I think the bigger use case for me is with `open-df` to directly load it into a dataframe. Some of the files I want to open are tens of thousands of lines long.

**Comment by TehPers** [comment]
I guess another options is to use `open -r file.jsonl | from json -o | into df`, this seems to be working for me. Native support would be nice, but this will work for now. Thanks!
