### ISSUE TITLE
`hide` and `hide-env` sometimes doesn't hide env vars

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#6593]
### Describe the bug

Sometimes `hide` and `hide-env` won't hide environment variables. It seems to work fine on Windows but I can't get it to work on WSL/Ubuntu.

### How to reproduce

1. Create this alias in your config.nu `alias lsg = (ls | sort-by type name -i | grid -c)`
2. Also in your config.nu create this hook.
```
hooks: {
  ...
  env_change: {
    PWD: [{|before, after|
      print (lsg)
    }]
  }
}
```
3. The very last line in your config.nu should be `hide LS_COLORS` or `hide-env LS_COLORS`. I do this so that there is no possibility of a parent shell having a `LS_COLORS` env var and nushell inheriting it.

### Expected behavior

Based on the example above, every time you change directory you should get a `lsg` output with the default nushell `LS_COLORS`. What's happening is there is some `LS_COLORS` being inherited in WSL and therefore the colors are wrong.

### Configuration

|key|value|
|-|-|
|version|0.68.2|
|branch|main|
|commit_hash|0b9dd87ca8c6a60ecac63154a40fe5bf6019f121|
|build_os|linux-x86_64|
|build_target|x86_64-unknown-linux-gnu|
|rust_version|rustc 1.61.0 (fe5b13d68 2022-05-18)|
|rust_channel|1.61.0-x86_64-unknown-linux-gnu|
|cargo_version|cargo 1.61.0 (a028ae4 2022-04-29)|
|pkg_version|0.68.2|
|build_time|2022-09-19 12:58:25 -05:00|
|build_rust_channel|release|
|features|database, dataframe, default, trash, which, zip|
|installed_plugins|custom-value generate, custom-value generate2, custom-value update, from parquet, gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml|

### Additional context

This seems to only happen when you have a parent shell. Also of note is that if you just type `lsg` in the repl, the colors are correct. So, in the repl, the `hide` is working. It's just not working right in the hook.

**Comment by gotounix** [comment]
It's not woking in Windows, too.

https://github.com/starship/starship/issues/4386

**Comment by kubouch** [comment]
@gotounix Just FYI, once this PR lands https://github.com/pypa/virtualenv/pull/2422 the virtualenv activation script will use the overlay system to activate the environment variables, so the `hide` or `hide-env` keywords won't be used anymore.

This `hide-env` stuff still need to be fixed.

**Comment by Decodetalkers** [comment]
You can repreduced it with
```
let-env a = 10
hide-env a
let c = {
$env.a
}
do $c
```
Then you will get 10
and then 
```
let-env a = 11
do $c
```
then you can get 11
Seems the variables are still alive in blocks

**Comment by refl3ction** [comment]
I also noticed this behavior and reported it [here](https://github.com/starship/starship/issues/4894). I'm using nushell on MacOS.
