### ISSUE TITLE
Nu crashes with 4294967295 when ctrl+c'ed in VSCode integrated terminal with certain commands

### ISSUE THREAD

**Issue by Veykril** [nushell/nushell#6639]
### Describe the bug

When invoking `git shortlog -s -n --all --no-merges` such that the command doesn't immediately exit (either by having a small enough terminal or enough commit authors), then invoking `ctrl+c` nushell will crash as soon as the command exits properly (by inserting `q`).

### How to reproduce

1. Open a nushell in the VSCode integrated terminal
2. Invoke `git shortlog -s -n --all --no-merges` on a repo such that the list is not fully displayed at once
3. Invoke `ctrl+c`
4. Press `q`

### Expected behavior

I expected nu not to crash.

### Configuration

❯ version | transpose key value | to md --pretty
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| commit_hash        | e76b3d61deef832adce76b0f73f19131de8cbc9e        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.68.1                                          |
| build_time         | 2022-09-08 21:41:56 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

My nushell is a chocolatey release. No crashes occur if run in a nushell outside of the integrated terminal, although invoking `ctrl+c` there seems to duplicate stdout (or maybe it reruns the command, unsure).

**Comment by fdncred** [comment]
I can't reproduce it on the Mac in the latest main branch.

**Comment by Veykril** [comment]
Just compiled the latest commit and tried it there as well with the same result. I imagine this might be a windows only issue. (I'll happily try to debug this more if anyone got some pointers on how to approach this)

**Comment by fdncred** [comment]
I can't get it to puke on Windows either. I wonder if it's based on the pager being used? I have `less.exe` in my path and I believe it's being used.

**Comment by sholderbach** [comment]
Seems to be the same problem as in #6428

**Comment by Veykril** [comment]
Ye I saw that issue as well, but that issue poster had their problem solved by pointing their PATH to a non-chocolatey release. The issue still persists for me with a self-build nushell unfortunately though.

**Comment by Veykril** [comment]
So after fiddling around with my `Path` it turns out to be in fact the same issue as https://github.com/nushell/nushell/issues/6428, I tried that before with no luck, but I now assume this might've been due to VSCode not properly having restarted. I apologize for the noise.

**Comment by rgwood** [comment]
No problem, thanks for the report. If you have the time/energy it might be good to file this as a Chocolatey bug somehow.
