### ISSUE TITLE
`git push --force-with-lease` fails in nushell

### ISSUE THREAD

**Issue by avkonst** [nushell/nushell#6644]
### Describe the bug

`git push --force-with-lease` is valid command and works in other shells, but fails in nushell
![image](https://user-images.githubusercontent.com/3971413/193220426-e754aec0-f496-4966-910b-dcf266110c3c.png)

### How to reproduce

runl `git push --force-with-lease`

### Expected behavior

git to be invoked, at least

### Screenshots

![image](https://user-images.githubusercontent.com/3971413/193221017-10e576bd-44c0-42ff-b2bb-e76745130892.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-musl                       |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:54:35 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
This is a completion problem. The way to fix these problems is to put a caret in front of the command like `git push --force-with-lease`. I believe this is because `--force-with-lease` must not exist in the completion parameters in the custom completions that are being sourced.
