### ISSUE TITLE
Error with to nuon conversion with backslash

### ISSUE THREAD

**Issue by NotLebedev** [nushell/nushell#6650]
### Describe the bug

Using `to nuon` on structures with strings containing single backslash characters doubles them. This results in doubled backslashes when converted back via `from nuon`.

More specifically this issue appears when string is part of some structure and nuon representation omits `"`  quotations. E.g.:
```
> "qwe\\qwe" | to nuon # works as expected
"qwe\\qwe"
> ["qwe\\qwe"] | to nuon # from nuon returns two slashes
[qwe\\qwe]
> { name: "qwe\\qwe" } | to nuon # from nuon returns two slashes
{name: qwe\\qwe}
> { name: "qwe\\qwe qwe" } | to nuon # works as expected due to whitespace
{name: "qwe\\qwe qwe"}
> [qwe\qwe] | to nuon # same issue even when string is introduced without quotation marks
[qwe\\qwe]
```

This behaviour reproduces both on Windows (where this bug was found when working with paths) and linux.

### How to reproduce

1. Execute ["qwe\\qwe"] | to nuon | from nuon

### Expected behavior

Backslashes should not be doubled when exporting to nuon.

### Configuration
Windows :
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.68.1                                          |
| branch             |                                                 |
| commit_hash        | e76b3d61deef832adce76b0f73f19131de8cbc9e        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.68.1                                          |
| build_time         | 2022-09-08 21:41:56 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

Linux:
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 13:28:59 +03:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by NotLebedev** [comment]
So i seem to found the issue. FIle crates\nu-command\src\formats\to\nuon.rs that implements `to nuon` command has `value_to_string_without_quotes` function to sometimes remove quotes from strings. Because needs_quotes does not think that backslash is a good reason to keep quotes it simply removes them, without removing double backslashes.

I tried changing the function like this:
```rust
fn value_to_string_without_quotes(v: &Value, span: Span) -> Result<String, ShellError> {
    match v {
        Value::String { val, .. } => Ok({
            let mut quoted = escape_quote_string(val);
            if !needs_quotes(val) {
                quoted.remove(0);
                quoted.pop();
                quoted = quoted.replace("\\\\", "\\"); // Removes redundant backslash
            }
            quoted
        }),
        _ => value_to_string(v, span),
    }
}
```

and adding backslash to `needs_quotes` check. Both seem to solve the issue, but it's unclear to me which (if any) solution is better.

**Comment by fdncred** [comment]
One of the differences in quotes is that double quotes allow for/evaluate escapes and single and backtick quotes do not.

**Comment by NotLebedev** [comment]
> One of the differences in quotes is that double quotes allow for/evaluate escapes and single and backtick quotes do not.

But this has no influence on this issue. All types of quotes (and no quotes at all) produce this result:
![image](https://user-images.githubusercontent.com/17511668/193401157-d252acf9-790e-4e46-8f1c-d380f46224df.png)

This seems to be influenced only by content of the string and if it is inside a table or record, as indicated in issue.

**Comment by NotLebedev** [comment]
I cooked up some tests and possible fix to this issue [NotLebedev/nushell:to-nuon-escapes](https://github.com/nushell/nushell/compare/main...NotLebedev:nushell:to-nuon-escapes).
