### ISSUE TITLE
How to run an inline/nested command and concat it with a string?

### ISSUE THREAD

**Issue by SUPERCILEX** [nushell/nushell#6656]
### Question

For example, `/tmp/(random integer)` doesn't work. Is there a better way than this? `(["/tmp/", (random integer)] | str join)`

**Comment by SUPERCILEX** [comment]
Also whatever the solution is it should be added to https://www.nushell.sh/book/coming_from_bash.html

**Comment by fdncred** [comment]
You can probably use string interpolation for that `$'/tmp/(random integer)'`.

**Comment by SUPERCILEX** [comment]
That's much better, thanks.

**Comment by SUPERCILEX** [comment]
@fdncred Actually, this doesn't work in another common bash case: `$ ftzz --num-files=(random integer)`. How would you inline command output into an option (assuming it doesn't support a space instead of an `=`)?

**Comment by SUPERCILEX** [comment]
Actually this works which is super weird coming from bash: `$"--num-files=(random integer)"`

**Comment by fdncred** [comment]
You also need to be careful with using double quotes vs single quotes where there are `\`'s involved. double quotes will escape things, single quotes won't.

**Comment by SUPERCILEX** [comment]
Gotya, thanks.
