### ISSUE TITLE
Windows paths don't work

### ISSUE THREAD

**Issue by Irtiza90** [nushell/nushell#6661]
### Describe the bug

the windows paths(which are seperated by `\`) 
eg: `C:\Users` don't work and give an error
```
Error: nu::parser::parse_mismatch (link)

  × Parse mismatch during operation.
   ╭─[entry #11:1:1]
 1 │ cd "C:\Users"
   ·    ─────┬────
   ·         ╰── expected directory
   ╰────
```
there is also no file in **C** drive, called **Users**

### How to reproduce

this works `cd "C:/Users"`
but this does not `cd "C:\Users"`

### Expected behavior

since nushell is cross platform, i think it should also support the windows specific paths

### Configuration

**Default**

**Comment by fdncred** [comment]
The problem is that you have a path in double quotes, which tells nushell to process escapes so it's seeing `\u`. There's no need for quotes in `C:\Users`. The completions will put in backtick quotes for paths that need it.
