### ISSUE TITLE
Add open support for ndjson

### ISSUE THREAD

**Issue by dhalucario** [nushell/nushell#6664]
### Related problem

I would like to use open `filename.ndjson`.

### Describe the solution you'd like

I would like to have support for ndjson files using open.

### Describe alternatives you've considered

I could split the files by newline but that would remove the ease of just having to use open. 

### Additional context and details

From http://ndjson.org/

NDJSON is a convenient format for storing or streaming structured data that may be processed one record at a time. It works well with unix-style text processing tools and shell pipelines. It's a great format for log files. It's also a flexible format for passing messages between cooperating processes.

**Comment by fdncred** [comment]
I believe that's what `from json -o` does

**Comment by dhalucario** [comment]
That worked. Is there a specific reason I can't use open directly? The file is named `fllename.ndjson`.

**Comment by fdncred** [comment]
Probably because there is probably no code that sees the `.ndjson` extension and infers it to mean `from json -o`. We'd probably accept a PR for that though.

**Comment by dhalucario** [comment]
Hm I will give it a shot and send the PR later.

**Comment by brettcannon** [comment]
FYI the ndjson link in the OP is now an ad page.

**Comment by fdncred** [comment]
This needs to be closed anyway because it's build into the stdlib.
```nushell
❯ use std formats
❯ help to ndjson
Convert structured data to [NDJSON](https://github.com/ndjson/ndjson-spec).

Usage:
  > to ndjson

Flags:
  -h, --help - Display the help message for this command

Input/output types:
  ╭─#─┬input┬─output─╮
  │ 0 │ any │ string │
  ╰───┴─────┴────────╯


❯ help from ndjson
Convert from [NDJSON](https://github.com/ndjson/ndjson-spec) to structured data.

Usage:
  > from ndjson

Flags:
  -h, --help - Display the help message for this command

Input/output types:
  ╭─#─┬─input──┬output╮
  │ 0 │ string │ any  │
  ╰───┴────────┴──────╯
```

**Comment by gerrywastaken** [comment]
@fdncred did this somehow break?

```nushell
~ use std formats
~ help to ndjson
Convert structured data to [NDJSON](https://github.com/ndjson/ndjson-spec).

Usage:
  > to ndjson 

Flags:
  -h, --help: Display the help message for this command

Input/output types:
  ╭───┬───────┬────────╮
  │ # │ input │ output │
  ├───┼───────┼────────┤
  │ 0 │ any   │ string │
  ╰───┴───────┴────────╯

~ help from ndjson
Convert from [NDJSON](https://github.com/ndjson/ndjson-spec) to structured data.

Usage:
  > from ndjson 

Flags:
  -h, --help: Display the help message for this command

Input/output types:
  ╭───┬────────┬────────╮
  │ # │ input  │ output │
  ├───┼────────┼────────┤
  │ 0 │ string │ any    │
  ╰───┴────────┴────────╯

~ cat /tmp/text.ndjson | from ndjson
Error: nu::parser::extra_positional

  × Extra positional argument.
   ╭─[entry #17:1:29]
 1 │ cat /tmp/text.ndjson | from ndjson
   ·                             ───┬──
   ·                                ╰── extra positional argument
   ╰────
  help: Usage: from

~ nu --version
0.100.0
```

`ndjson` doesn't seem to be supported despite showing up under help
