### ISSUE TITLE
`str replace` no error for invalid regular expression

### ISSUE THREAD

**Issue by MichelMunoz** [nushell/nushell#6665]
### Describe the bug
Current state see. https://github.com/nushell/nushell/issues/6665#issuecomment-1267136146
The only remaining problem is that no error seems to be raised for invalid pattern

-----
## old stuff
While working on a workaround for #6647 I stumbled upon the following two problems ( ? )
The goal in the examples is to double the backslashes.

**Nominal cases**, the two following examples work as expected :
nominal double-quote test
```
> 'titi\toto\tutu\' | str replace -s -a "\\" "\\\\"
titi\\toto\\tutu\\
```
equivalent nominal single quote test
```
> 'titi\toto\tutu\' | str replace -s -a '\' '\\'
titi\\toto\\tutu\\
```

The two following sections describe the "bugs" (?) found.

----

**Problem 1** : "**CLI stuck in some mode**" cases, here instead of displaying a result, the cli get stuck :
direct command test (note the "-n" option here, instead of "-s" previously and the double quotes in the input, important)
`> "titi\toto\tutu\" | str replace -n -a "\\" "\\\\"`

leads to the CLI in the following state:
![Capture-1](https://user-images.githubusercontent.com/18261174/193835629-c22e6858-ed70-49e8-afb1-618db5f69a51.png)

changing the quotes of the input to simple quotes does not produce the "stuck" state.
So "\t" being interpreted as tab seems to do something here.

----

**Problem 2** : **Bizarre behavior**
Nominal case, note the 3 options :
```
> 'titi\toto\tutu\' | str replace -a -s -n '\' '\\'
titi\\toto\\tutu\\
```
We remove one option, still correct behavior :
```
> 'titi\toto\tutu\' | str replace -a -s '\' '\\'
titi\\toto\\tutu\\
```
But if instead we remove the other, the answer is not as expected :
```
> 'titi\toto\tutu\' | str replace -a -n '\' '\\'
titi\toto\tutu\
```
stranger still, you can add as much backslashes in the "replace" as you want, the answer is the same (!) 
```
> 'titi\toto\tutu\' | str replace -a -n '\' '\\\\\\\\\'
titi\toto\tutu\
```

 

### How to reproduce

see description, it provides a step by step

### Expected behavior

see description.

### Configuration

```
╭────────────────────┬─────────────────────────────────────────────────╮
│ version            │ 0.69.1                                          │
│ branch             │                                                 │
│ commit_hash        │ 8a5abc7afc28a36908a32f1852127e2a5170b461        │
│ build_os           │ windows-x86_64                                  │
│ build_target       │ x86_64-pc-windows-msvc                          │
│ rust_version       │ rustc 1.64.0 (a55dd71d5 2022-09-19)             │
│ rust_channel       │ stable-x86_64-pc-windows-msvc                   │
│ cargo_version      │ cargo 1.64.0 (387270bc7 2022-09-16)             │
│ pkg_version        │ 0.69.1                                          │
│ build_time         │ 2022-09-28 02:57:59 +00:00                      │
│ build_rust_channel │ release                                         │
│ features           │ database, dataframe, default, trash, which, zip │
│ installed_plugins  │                                                 │
╰────────────────────┴─────────────────────────────────────────────────╯
```

**Comment by fdncred** [comment]
This is probably because of the quotes being used. Double quotes tells nushell to use `\` as escape characters, whereas single quotes and backtick quotes try to use quotes in the normal way. However, there's also a regular expression factor here that may conflate the issue. To eliminate that issue you could use `--string` as a flag.  Doing `string replace --help` explains some of this or in our documentation https://www.nushell.sh/book/commands/str_replace.html.

**Comment by MichelMunoz** [comment]
That explains probably problem 2, that is `'\'` woud be interpreted as "regexp escape character" (with nothing to escape after), which is not a valid pattern I suppose, _maybe there should be some kind of error ("invalid pattern expression" or something)_.

But what about problem 1, double quoted string are valid as per nushel documentation ?
In nushell has no CLI problem with
`'titi\toto\tutu\' | str replace -a -n '\' '\\'`
and no issue with
`'titi\toto\tutu\' | str replace -n -a "\\" "\\\\"`
whats the explanation for the behavior with "\t" (probably interpreted as tabs I guess) :
`"titi\toto\tutu\" | str replace -n -a "\\" "\\\\"`
why is the CLI stuck (or in some edit mode) ?

**Comment by MichelMunoz** [comment]
(as a complement to my answer on problem 2, https://regex101.com/ considers '\' an invalid pattern, whatever the flavor used.)

**Comment by MichelMunoz** [comment]
For problem 1, I found the answer, it's not the `\t` that are the problem, it's the _final_ `\"` of the input string, that prevents the input string to be "closed", and thus, the CLI expects the string to be closed, hence the edit mode displayed.

**Comment by MichelMunoz** [comment]
That leaves only on "issue" for this ticket, the fact that there is not regexp validation (and no error message for that).
Would you agree ? (If so I will rename the ticket)

**Comment by fdncred** [comment]
Well, I'm not sure. I'd have to look at the code. To clarify, double quotes are for escapes, not necessarily regular expression escapes. You can see that here https://github.com/nushell/nushell/blob/79ce13abef1c795e02a0bb6482783f976714ba7f/crates/nu-parser/src/parser.rs#L2415-L2573.

It seems that regular expressions are checked here https://github.com/nushell/nushell/blob/79ce13abef1c795e02a0bb6482783f976714ba7f/crates/nu-command/src/strings/str_/replace.rs#L235. But maybe we're not doing it right or there is some logic error in this "neighborhood".

**Comment by jake-albert** [comment]
Hi all,

Pretty new to Rust, and even newer to Nushell. If now the only concern for this issue is the lack of error on invalid RegEx as @MichelMunoz has mentioned, then I suppose this PR would address the issue in full.

Thanks for any feedback on the code or description for my PR, and have a great day!
