### ISSUE TITLE
macOS: `Ctrl-o` won't open `EDITOR` with just binary name but it does with full path to binary.

### ISSUE THREAD

**Issue by MichaelScofield45** [nushell/nushell#6669]
### Describe the bug

This does **not** occur in Linux, but it does in macOS. 
I know my editor is in my path because I can run it normally from a command and even use the `config nu` and `config env` without issues. When using the binding `Ctrl-o` to open the current line in the `EDITOR` environment variable it delivers the error message:
`Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }`

However, giving `EDITOR` the full path, e.g. `/usr/local/bin/nvim` leads to correct behavior.
Setting the `buffer-editor` variable manually in `config.nu` makes no difference to the outcome.

### How to reproduce

1. In the `env.nu` file, set `EDITOR` to any editor of choice (in my case `nvim` or `hx`) using `let-env EDITOR = "nvim"`
2. Use `Ctrl-o` while using the shell normally. 

### Expected behavior

Open the current line of the shell I am writing in `EDITOR`.

### Configuration

`/Users/ms45: version | transpose key value | to md --pretty `
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | macos-x86_64                                    |
| build_target       | x86_64-apple-darwin                             |
| rust_version       | rustc 1.64.0                                    |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:48:01 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
Looking at the code, this is how it's supposed to work.

1. Look for `$env.config.buffer_editor` and use it, if it's not set
2. Look at `$env.EDITOR` and use it, if it's not set
3. Look at `$env.VISUAL` and use it, if it's not set
4. (we have two implementations that are different here, which could cause a bug) in some cases use `notepad` on Windows and `nano` everywhere else

So, for me, `buffer_editor` is set to `hx` on Windows and i have `EDITOR` and `VISUAL` set to `code`. When i do ctrl-o, it launches `hx`.

**Comment by MichaelScofield45** [comment]
I opened this issue with macOS in the title because I cannot reproduce the error in Linux for example. 

As you suggested, I:
1. Set `$env.config.buffer_editor` to `nvim`
2. Set `$env.EDITOR` to `nvim`
3. Set `$env.VISUAL` to `nvim`

*In macOS* this leads to the error I mentioned. The `$env.PATH` is set up correctly, maybe it is the way in which Rust looks at the `PATH` specifically in macOS?

Solution for me:
1. Set `$env.EDITOR` to `/usr/local/bin/nvim` (this shouldn't be necessary)

**Comment by fdncred** [comment]
That's weird. On MacOS I have my `buffer_editor` and `EDITOR` set to `hx` but don't have a `VISUAL` set. ctrl-o works fine with `hx` for me.

**Comment by MichaelScofield45** [comment]
Changing to  just `hx` for me doesn't fix it. But if it works for you then it means it is not reproducible as I thought that it was a macOS issue. 

I'm fine with writing the whole `/usr/local/bin/<editor_name>` as a workaround. but it was just weird to me that it gave out that specific error. I guess this can be closed then, unless someone else has the same error or something new is found.

**Comment by fdncred** [comment]
It's weird that this works for me and not for you. I was thinking it may be nvim specific but since you tried `hx` that isn't the case. 🤔

**Comment by maxim-uvarov** [comment]
I confirm, that I had the same proble, and that the solution to use the complete path worked for me too. 
```
version | transpose key value | to md --pretty
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.76.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07) (built from a source tarball) |
| cargo_version      | cargo 1.67.0 (8ecd4f20a 2023-01-10)                               |
| pkg_version        | 0.76.0                                                            |
| build_time         | 2023-02-28 15:03:47 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | database, dataframe, default, trash, which, zip                   |
| installed_plugins  | from parquet                                                      |
```
