### ISSUE TITLE
expected supported escape character

### ISSUE THREAD

**Issue by Techoc** [nushell/nushell#6672]
### Describe the bug

When i use rclone in nushell `rclone copy "E:\downloads\1380213802_寂烨不曾来过\Kurumineko" asmr:/写真/Kurumineko -P`.And the nushell say `expected supported escape character`

### How to reproduce

just run code `rclone copy "E:\downloads\1380213802_寂烨不曾来过\Kurumineko" asmr:/写真/Kurumineko -P`

### Expected behavior

rclone should run 

### Screenshots

<img width="747" alt="image" src="https://user-images.githubusercontent.com/48900433/194555967-59908e5e-a32c-4e89-bc7a-4c3b41dced97.png">

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:57:59 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
It's because the use of double quotes means the backslash `\` is an escape character. If you want to use double quotes you should use `\\`, otherwise I think single quotes would work.
