### ISSUE TITLE
Exit code does not persist on an empty command

### ISSUE THREAD

**Issue by lewis-yeung** [nushell/nushell#6673]
### Describe the bug

In Nushell v0.69.1, if we press <kbd>Enter</kbd> on an empty command, a non-zero exit code will not persist for the next spawned prompt as expected, instead it will be always reset to 0.

### How to reproduce

1. Set `PROMPT_COMMAND` in `$nu.config-path`:

	```nu
	export-env {
	  let-env PROMPT_COMMAND = {
	    $env.LAST_EXIT_CODE
	  }
	}
	```

2. Start a new Nushell session.
3. Run a command which exits with a non-zero code, e.g., `gcc` which returns 1, so `$env.LAST_EXIT_CODE` in the prompt will be `1`.
4. Press <kbd>Enter</kbd> without typing anything. The `$env.LAST_EXIT_CODE` in the new prompt will be reset to `0`.

### Expected behavior

A non-zero exit code should not be reset to 0 after an empty command, it should persist until a non-empty command is executed.

### Configuration

```
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0                                    |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:48:01 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |
```

**Comment by fdncred** [comment]
What is the precedence on this behavior? Is this how bash, fish, powershell, etc, behave?

**Comment by merelymyself** [comment]
Both `fish` and `bash` behave in the suggested manner


`bash`:
```
gabriel@coffee-cat-laptop:~$ cd dir_that_does_not_exist
bash: cd: dir_that_does_not_exist: No such file or directory
gabriel@coffee-cat-laptop:~$
gabriel@coffee-cat-laptop:~$ echo $?
1
```
`fish`:
```
gabriel@coffee-cat-laptop:~
➤ cd dir_that_does_not_exist
cd: The directory “dir_that_does_not_exist” does not exist
gabriel@coffee-cat-laptop:~
➤
gabriel@coffee-cat-laptop:~
➤ echo $status
1
```

**Comment by fdncred** [comment]
Maybe https://github.com/nushell/nushell/pull/6674 will fix this.
