### ISSUE TITLE
Slow startup time (not much, just a little bit)

### ISSUE THREAD

**Issue by christianhujer** [nushell/nushell#6677]
### Describe the bug

nushell has a slower startup time compared to other shells (dash, bash, csh, fish, tcsh, ksh, zsh).

### How to reproduce

1. Install nushell
2. Compare startup performance

Startup performance could, for example, be compared like this:

    hyperfine -L shell sh,ash,ksh,bash,zsh,csh,fish,tcsh,nu,pwsh '{shell} -c "echo \"Hello, world!\""'

The output on my system is this:
```
Summary
  'sh -c "echo \"Hello, world!\""' ran
    1.23 ± 0.73 times faster than 'ash -c "echo \"Hello, world!\""'
    1.90 ± 0.45 times faster than 'ksh -c "echo \"Hello, world!\""'
    2.03 ± 1.18 times faster than 'bash -c "echo \"Hello, world!\""'
    2.41 ± 0.55 times faster than 'zsh -c "echo \"Hello, world!\""'
    6.48 ± 1.29 times faster than 'csh -c "echo \"Hello, world!\""'
    7.26 ± 1.62 times faster than 'fish -c "echo \"Hello, world!\""'
    7.93 ± 1.68 times faster than 'tcsh -c "echo \"Hello, world!\""'
   26.55 ± 5.52 times faster than 'nu -c "echo \"Hello, world!\""'
  674.56 ± 131.91 times faster than 'pwsh -c "echo \"Hello, world!\""'
```

* nushell is >~25× faster than PowerShell, and that's great (but also not difficult to achieve).
* nushell is ~26× slower than sh (dash)
* nushell ~13× slower than bash.

Some shell scripts in dash and bash complete faster than nushell takes to launch.

### Expected behavior

I expected nu to launch about as fast as a regular Linux/Unix shell.
But it actuall takes ~13-26 times as long to launch as a typical Linux/Unix shell.

### Configuration

〉version | transpose key value | to md --pretty                                                                                                        10/08/2022 03:48:31 PM
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:53:42 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

* I did not build nushell myself. Maybe nushell would spin up faster if I would build it myself with my own Rust installation.
* I did not yet perform other benchmarks.
* The benchmarks are performed on Linux (Kubuntu 22.04.1 LTS, Kernel 5.15.0-48-generic, x86_64, Intel Core i7-8550U)

**Comment by fdncred** [comment]
We'd welcome startup-performance-enhancing PRs

**Comment by rgwood** [comment]
To put some absolute numbers on this, on the latest `main` I'm seeing `sh`/`bash`/`zsh` taking under 1ms and Nu taking ~80ms on Linux with a lot of variance. On Windows I see about 20ms. This is on a fast desktop (12900K).

Something's weird with those Linux numbers, it shouldn't be slower than Windows; if someone has time to measure and profile that would be great.

I have done a fair bit of profiling Nu's startup path on Windows and haven't found anything obvious to improve there. We spend a bit of time parsing config.nu and env.nu and that's about it.

**Comment by fdncred** [comment]
@rgwood I did some profiling a while back and one thing that I noticed is that the special variables, such as `$nu.scope`, can cause performance issues. Specifically `$nu.scope.commands`. 

If you recall, I originally had `history session` at `$nu.history-session` and the performance was completely terrible and really unusable. So, I had to create a command for it. I'm wondering if our startup performance would be better if we moved all these `$nu.scope` things into a `scope sub_command` set of commands. My guess is that startup would be measurably faster.

**Comment by rgwood** [comment]
I've been looking at this again. It appears that `nu -c` spends most of its startup time evaluating the default env.nu file: https://github.com/nushell/nushell/blob/24153816829a64b7bc427b248cfbbd0688430ae3/src/config_files.rs#L133
![image](https://user-images.githubusercontent.com/26268125/209454122-042c4df7-4f8c-4f90-9a15-a4d8bf48cda3.png)

Unless we can dramatically speed up Nu code evaluation, the most promising approach is to evaluate less code on startup. The [`default_env.nu`](https://github.com/nushell/nushell/blob/main/crates/nu-utils/src/sample_config/default_env.nu) file has a bunch of stuff that is unnecessary in non-interactive contexts; we could maybe load a different file when running in a non-interactive context?

**Comment by rgwood** [comment]
^After further experimentation: the culprit is the 2 calls to `$nu.config-path` in `default_env.nu`. Those are responsible for about 2/3 of Nu's total startup time on Linux. `$nu` has so much info that it's relatively expensive (3+ milliseconds) to call

**Comment by rgwood** [comment]
Things are looking much better after https://github.com/nushell/nushell/pull/7619 which sped up startup by 2-3x.

Still not _quite_ as fast as other shells, but 2.5ms is quick enough that I'm happy with Nu's startup performance for now.

```
〉hyperfine -L shell sh,bash,zsh,/home/reilly/bin/nu '{shell} -c "echo \"Hello, world!\""' --shell=none --warmup=10
Benchmark 1: sh -c "echo \"Hello, world!\""
  Time (mean ± σ):       0.3 ms ±   0.0 ms    [User: 0.0 ms, System: 0.0 ms]
  Range (min … max):     0.3 ms …   1.1 ms    10541 runs

  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

Benchmark 2: bash -c "echo \"Hello, world!\""
  Time (mean ± σ):       0.5 ms ±   0.1 ms    [User: 0.2 ms, System: 0.0 ms]
  Range (min … max):     0.4 ms …   1.7 ms    4436 runs

  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

Benchmark 3: zsh -c "echo \"Hello, world!\""
  Time (mean ± σ):       0.8 ms ±   0.1 ms    [User: 0.5 ms, System: 0.0 ms]
  Range (min … max):     0.7 ms …   1.7 ms    3849 runs

  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

Benchmark 4: /home/reilly/bin/nu -c "echo \"Hello, world!\""
  Time (mean ± σ):       2.5 ms ±   0.2 ms    [User: 1.9 ms, System: 0.2 ms]
  Range (min … max):     2.2 ms …   3.3 ms    1039 runs

Summary
  'sh -c "echo \"Hello, world!\""' ran
    1.75 ± 0.32 times faster than 'bash -c "echo \"Hello, world!\""'
    2.85 ± 0.45 times faster than 'zsh -c "echo \"Hello, world!\""'
    8.68 ± 1.31 times faster than '/home/reilly/bin/nu -c "echo \"Hello, world!\""'
```
