### ISSUE TITLE
Prompt theming: horizontal line (divider)

### ISSUE THREAD

**Issue by fedoranvar** [nushell/nushell#6682]
### Question

good day to you all!

how to output fullwidth horizontal line in prompt?

thank you !

**Comment by fdncred** [comment]
It's not natively supported but you could hack something together by calculating the width of the terminal with `term size` and drawing a character to that width by padding it with `str lpad` or `str rpad` and perhaps drawing that in each prompt with a custom prompt.

**Comment by fedoranvar** [comment]
@fdncred   

thank you!  i've come up with this:

```nu
def create_left_prompt [] {
    let path_segment = if (is-admin) {
        $"(ansi red_bold)($env.PWD)"
    } else {
        $"(ansi green_bold)($env.PWD)"
    }

    let divider =  ("\n" | str lpad -l (term size | get columns) -c '-')

    $"\n(ansi red_bold)($divider)\n|    ($path_segment)\n|    "
}

```

**Comment by fdncred** [comment]
Nice!  I'll have to try this out a little later.

**Comment by fedoranvar** [comment]
but it requires some tweaking for handling right prompt correctly
