### ISSUE TITLE
Script subcommands

### ISSUE THREAD

**Issue by DrSloth** [nushell/nushell#6683]
### Related problem

I am using nushell for a build script. I had some problems using `just` as a command runner, the main feature of `just` with managing multiple commands could be a nice feature for nushell itself

### Describe the solution you'd like

It would be an extremely nice feature to be able to define subcommands of a script directly inside a script. 

We can parameterize a script by using a main function. We can also define subcommands with 
`def "command subcommand" [] {}`. These two features could be combined such that a script can directly define a subcommand with `def "main subcommand" [] {}`.

### Describe alternatives you've considered

This is a nice to have feature, which would offer some more flexibility and ad-hoc usability in some niche cases but isn't really important.

### Additional context and details

I am really enjoying using nushell. This feature doesn't seem all too hard to implement as it seems like most of the parts already exist to some extent. With some guidance i might be able to help in implementing this.

Thanks for your time :)

**Comment by fdncred** [comment]
I don't understand the request. You can define and call as many sub commands as you like in a script already.

**Comment by dandavison** [comment]
@DrSloth, to expand on what @fdncred said, is it the case that you (like me!) did not know that the following works already?

```
def main [] {
    print 'hello'
}

def 'main subcommand-1' [] {
    print 'hello from subcommand-1'
}
```

```
〉nu z.nu
hello
〉nu z.nu subcommand-1
hello from subcommand-1
```

**Comment by DrSloth** [comment]
Oh wow. I didn't know this. I couldn't find anything like this in the documentation and it didn't work as i first tested it. But it does work. This is a great feature, did i just miss it in the docs or should the documentation around this be improved?

**Comment by dandavison** [comment]
I think it's missing: https://www.nushell.sh/book/scripts.html#parameterizing-scripts

I certainly didn't know it was possible after reading that page twice. I suspect that a doc PR would be appreciated by the nu developers.

**Comment by fdncred** [comment]
yup, docs are never up to date because we change so fast atm

**Comment by jakeisnt** [comment]
Looks like the docs are now up-to-date: https://www.nushell.sh/book/custom_commands.html#sub-commands. This can be closed

**Comment by fdncred** [comment]
thanks, always love closing issue. doesn't happen often enough, as you can tell from our issue list. 🤣
