### ISSUE TITLE
`ls`: bizarre values shown for filenames longer than the width of their `name` column

### ISSUE THREAD

**Issue by jake-albert** [nushell/nushell#6704]
### Describe the bug

Rather than displaying the file name, nushell shows an odd string that consists of:
1.  some characters like `39m` or `22m`;
2. a newline;
3. the absolute path to the file, except truncated from the front by a few characters, and with the filename itself repeated twice; then finally
4. the same characters `39m` or `22m`.

So far I have observed this problem only for tables produced by `ls`. A table read in from user input like `[[name number]; [some_long_name 2] [another_long_name 4]]` does not result in any change to the displayed strings on a very narrow terminal, so it seems like the issue is related specifically to `ls` and not to code related to tables themselves.

### How to reproduce

1. Run `ls` in a terminal whose width will be less than the output. 

**Note:** so far have observed strange behavior on iTerm2, VSCode's in-window terminal, and macOS Terminal. Have not yet attempted on other machines/OS.

#### `ls` where the window is just wide enough for the table ... no problem

<img width="481" alt="image" src="https://user-images.githubusercontent.com/16626016/195114424-da960126-feed-452c-93d6-23b903c3a308.png">

#### `ls` where the window is too narrow for the table ... note the bizarre values in `name` column

<img width="421" alt="image" src="https://user-images.githubusercontent.com/16626016/195114657-00e82c2b-56e6-445d-8fe5-fc40f84e9dba.png">

### Expected behavior

I expected nu to print the filename correctly, just with word wrap. (See "additional context" section)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | macos-x86_64                                    |
| build_target       | x86_64-apple-darwin                             |
| rust_version       | rustc 1.64.0                                    |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:48:01 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | inc                                             |

### Additional context

Strangely, I am unable to reproduce the behavior on my local fork of nushell, and yet looking briefly though recent PRs for `0.69.2`, nothing caught my eye that could have been a fix of this issue. Might be tricky to look into the cause of the problem if I cannot reproduce it.

My local fork (in which I ran with `cargo run` and `cargo run --release` and saw no issues):

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.69.2                                   |
| branch             | main                                     |
| commit_hash        | 0bbb3a20df1e517ba737de540bac226c4456aa33 |
| build_os           | macos-x86_64                             |
| build_target       | x86_64-apple-darwin                      |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)      |
| rust_channel       | 1.63.0-x86_64-apple-darwin               |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)      |
| pkg_version        | 0.69.2                                   |
| build_time         | 2022-10-11 22:20:27 +09:00               |
| build_rust_channel | debug                                    |
| features           | default, trash, which, zip               |
| installed_plugins  | inc                                      |

#### `ls` where at least one name needs to be word wrapped ... nothing unusual

<img width="429" alt="image" src="https://user-images.githubusercontent.com/16626016/195114893-d5cc1e7b-8716-421c-8b9a-dd6245373ac7.png">

**Comment by fdncred** [comment]
I believe this PR fixed this problem. https://github.com/nushell/nushell/pull/6286

**Comment by jake-albert** [comment]
Oh, that's good news. If it can't be reproduced anywhere on 0.69.2 then I guess the issue can be closed. Maybe if I have time later I'll look at that PR and see what the actual issue was. Thanks!

**Comment by dandavison** [comment]
Hi @jake-albert 

> Maybe if I have time later I'll look at that PR and see what the actual issue was. 

The problem was that terminal hyperlinks were not supported by the previous version of tabled. It was fixed here: https://github.com/zhiburt/tabled/pull/223

**Comment by jake-albert** [comment]
@dandavison I see, thank you! Will take a look to learn more.
