### ISSUE TITLE
$env.CMD_DURATION_MS format

### ISSUE THREAD

**Issue by zhiburt** [nushell/nushell#6709]
### Question

Running `$env.CMD_DURATION_MS` as a first command right after `nu` launch causes it to be not clear output. (is it nanoseconds?).

I just wondering if it's expected and if it's nanoseconds maybe it's better be formatted differently?

![image](https://user-images.githubusercontent.com/20165848/195325756-90d08a50-01a8-4cac-a670-5be61b46b084.png)

**Comment by fdncred** [comment]
It's expected and it's an Easter egg. August 23 is the month and day of the first nushell release.

**Comment by zhiburt** [comment]
OK then I guess I've found it :)

Thanks for the answer take care.
