### ISSUE TITLE
`cd` after a semicolon does not seem to work in custom command

### ISSUE THREAD

**Issue by gegnew** [nushell/nushell#6711]
### Describe the bug

After https://github.com/nushell/nushell/issues/3641#issue-924190256

This command does not execute `cd`:
```
def r [] { 
  ranger --choosedir=/home/you/rangerdir; cd (cat /home/you/rangerdir)
}
```

If you replace the cd command after the ; with just `cat /path/to/rangerdir`, it prints the dir that ranger wants to drop you into, but the `cd` command doesn't seem to execute

### How to reproduce

see above

### Expected behavior

I expect nu to cd to the directly returned by `cat`

### Configuration

only the `def` above

**Comment by fdncred** [comment]
def-env should fix this, please re-open if it doesn't.
