### ISSUE TITLE
Listing aliases doesn't work

### ISSUE THREAD

**Issue by soderluk** [nushell/nushell#6714]
### Describe the bug

According to the PR #3879 listing all the registered aliases should work by typing `alias` without any arguments. Currently typing `alias` returns an error
```
alias
Error: nu::parser::incorrect_value (link)

  × Incorrect value
   ╭─[entry #7:1:1]
 1 │ alias
   · ──┬──
   ·   ╰── unexpected Incomplete alias
   ╰────
  help: incomplete alias
```
This doesn't work even if I do the same as in the PR description, setting `alias v = vim` etc.

### How to reproduce

1. Define an alias in the config.nu file
2. Define an alias on the command line
3. Run `alias` without arguments

### Expected behavior

Nu should list all my registered aliases and what they are.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.69.1                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01) |
| pkg_version        | 0.69.1                              |
| build_time         | 2022-10-13 09:46:11 +03:00          |
| build_rust_channel | release                             |
| features           | default, trash, which, zip          |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
It seems like that functionality was never ported over after the engine-q merge. As a work-around, you can also list your aliases by typing `$nu.scope.aliases`.

**Comment by soderluk** [comment]
@fdncred : JT mentioned in the PR using `$scope.aliases` which didn't work, and that's why I created this issue. Thanks for pointing out that it has to be `$nu.scope` instead!
