### ISSUE TITLE
Unable to run `unique`

### ISSUE THREAD

**Issue by ssssam** [nushell/nushell#6721]
### Describe the bug

Running `help unique` suggests that there is a command named `unique`, but it's impossible to run this command. It is possible to run `uniq` though.

### How to reproduce

Run `unique` in Nushell 1.69.1

### Expected behavior

Run `unique` :-)

### Screenshots

```
/home/sam/.local/bin〉help unique                         10/14/2022 12:06:37 pm
Returns unique values from a dataframe

Usage:
  > unique {flags} 

Flags:
  -h, --help - Display this help message
  -s, --subset <Any> - Subset of column(s) to use to maintain rows (lazy df)
  -l, --last - Keeps last unique value. Default keeps first value (lazy df)
  -k, --maintain-order - Keep the same order as the original DataFrame (lazy df)

Examples:
  Returns unique values from a series
  > [2 2 2 2 2] | into df | unique

  Creates a is unique expression from a column
  > col a | unique


/home/sam/.local/bin〉unique                              10/14/2022 12:06:41 pm
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #3:1:1]
 1 │ unique
   · ───┬──
   ·    ╰── did you mean 'unique'?
   ╰────
  help: No such file or directory (os error 2)

/home/sam/.local/bin〉uniq                                10/14/2022 12:06:46 pm
/home/sam/.local/bin〉                                    10/14/2022 12:06:48 pm
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:53:42 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
This is because `unique` is a command specifically for dataframes. If you have a single column in a dataframe, it works.
```
[[my_column other_column]; ['hello' 42] ['world' -1] ['hello' 5]] | into df | get my_column | unique
```

**Comment by ssssam** [comment]
Thanks for the advice - I think there's room for improvement in the error message, in that case. 

```
/home/sam/.local/bin〉unique                              10/14/2022 12:06:41 pm
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #3:1:1]
 1 │ unique
   · ───┬──
   ·    ╰── did you mean 'unique'?
   ╰────
  help: No such file or directory (os error 2)
```

None of this is particularly useful information as:

  * the command does exist, the actual problem is incorrect input
  * the suggested 'solution' is to do exactly what I just tried
  * I had to guess at the existence of a corresponding `uniq` command that would do what I want

**Comment by fdncred** [comment]
Yes, there is room for improvement. I think the root cause of this is related to our command overloading. We'd love to make it better. It should be named `uniq` which would be overloaded with the nushell command. However, this will not fix it because the parser (I think) has to be improved so it doesn't need a hint like `into df` to understand which overloaded command to use.

**Comment by ssssam** [comment]
I see, thanks for the explanation ! Makes sense that the ideal fix would be to stop having `uniq` and `unique` mean different things .. :)

**Comment by webbedspace** [comment]
> However, this will not fix it because the parser (I think) has to be improved so it doesn't need a hint like `into df` to understand which overloaded command to use.

Quick question: why does the parser prevent these from being overloaded? `take` is already overloaded for tables and dataframes and seems to work fine.

**Comment by fdncred** [comment]
> What I meant was, why does the parser prevent this being renamed to `uniq` as an overload of the normal-structure `uniq`?

I think we could name them both `uniq`. Are you saying you've tried and it doesn't let you? @elferherrera wrote all this dataframe stuff. Maybe he knows.

**Comment by webbedspace** [comment]
I was asking because you said

>the parser (I think) has to be improved so it doesn't need a hint like `into df` to understand which overloaded command to use.

and I was wondering why this improvement was necessary when `take` doesn't seem to need a hint (?) for Nushell to select the correct overload.

**Comment by fdncred** [comment]
oh, you're saying that `take` for dataframes and `take` for nushell tables work the same without needing a hint for dataframes. ok, i missed that. i'm not sure why it's different. maybe they're implemented differently.
