### ISSUE TITLE
CRLF line endings in docs for custom commands causes buggy autocomplete suggestions

### ISSUE THREAD

**Issue by holly-hacker** [nushell/nushell#6726]
### Describe the bug

Given the following custom command:
```
# This is my command, it does something.
#
# Example: `ls_new /`
def ls_new [
        arg: string # My arg
    ] {
    ls $arg
}
```

If I save this to a file with Windows-style line endings (CRLF) and source it, the CR characters don't seem to get stripped correctly when printing suggestions during tab-completion.

### How to reproduce

1. Create a .nu file with a custom command with multiple lines of description, and save it using Windows-style line endings (CRLF)
2. Source the .nu file to load the command
3. Enter part of the command and use <kbd>TAB</kbd> to auto-complete
4. Observe that the output looks weird:
```
C:\My\Path| ls
ls      List the files in a directory.
ls-df   Lists stored dataframes
 Example: `ls_new /`ommand, it does something.
```

### Expected behavior

The correct behavior can be seen when saving using Linux-style line endings (LF):
```
C:\My\Path| ls
ls      List the files in a directory.
ls-df   Lists stored dataframes
ls_new  This is my command, it does something.  Example: `ls_new /`
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by weirdan** [comment]
This is no longer happening. Only the first line (regardless of the line endings) is now shown in autocomplete:

![image](https://github.com/user-attachments/assets/833b4eb0-d1f2-4031-a834-f3fb5991976f)

**Comment by sholderbach** [comment]
Ah related to #6878
