### ISSUE TITLE
Documentation: environment.html#let-env code sample is wrong

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6733]
### Describe the bug

One of the code samples given at https://www.nushell.sh/book/environment.html#let-env is
```
let-env PATH = ($env.PATH | prepend '/path/you/want/to/add')
```

### How to reproduce

However, running this will produce this error:
```
Error: nu::shell::name_not_found (link)

  × Name not found
   ╭─[entry #1:1:1]
 1 │ let-env PATH = ($env.PATH | prepend '/path/you/want/to/add')
   ·                      ──┬─
   ·                        ╰── did you mean 'Path'?
   ╰────
```

### Expected behavior

Please fix this sample.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by rgwood** [comment]
Yeah, this is a longstanding issue that @fdncred has spent a lot of time on; I believe the short explanation is that sometimes Windows uses PATH and sometimes it uses Path. To work around this for now you should be able to use "Path":

```
let-env Path = ($env.Path | prepend '/path/you/want/to/add')
```

It's come up often enough that maybe we should revisit the behaviour of environment variables on Windows; I think that ideally let-env should be [case-insensitive but case-preserving](https://jmmv.dev/2005/12/case-sensitive-vs-case-preserving.html) on Windows.

I might be able to work on that if the rest of the team thinks it's a good idea.
