### ISSUE TITLE
Using 'as' on a record produces a nonsensical error

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6734]
### Describe the bug

Using 'as' on a record produces a nonsensical error.

### How to reproduce

Run the command `{ foo: '1', bar: '2' } | as 'a'`.
The result is:
```
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #34:1:1]
 1 │ { foo: '1', bar: '2' } | as 'a'
   ·                          ─┬
   ·                           ╰── did you mean 'as'?
   ╰────
  help: program not found
```

### Expected behavior

Ideally, it would explain that the type of data passed to `as` is wrong.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
`as` is only applicable with `dataframes` and `databases` so, if you don't give it the right context, such as a record, you will get a weird error message.  Granted, you're right, it should be a better error message.

**Comment by sholderbach** [comment]
Seems out of date to me as we removed the old command overloading shenanigans for now
