### ISSUE TITLE
rm does not confirm recursive delete

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#674]
If you type `rm <dir name>`, nu will recursively delete without asking for confirmation. This is a pretty dangerous default. We should at least confirm before we delete cursively, or make it easy to undo recursive deletes.

**Comment by jonathandturner** [comment]
Ooops, nevermind, it does require the flag.

**Comment by andrasio** [comment]
@jonathandturner ;)

It deletes it without a flag, if and only if the directory is empty.
