### ISSUE TITLE
Documentation: `replace` and `replace-all` listed even though they A) don't exist, and B) collide with Windows `replace.exe`

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6743]
### Describe the bug

See title.

### How to reproduce

In https://www.nushell.sh/book/command_reference.html, `replace` and `replace-all` are both listed. However, they currently don't exist:
```
C:\〉which replace
╭───┬─────────┬─────────────────────────────────┬──────────╮
│ # │   arg   │              path               │ built-in │
├───┼─────────┼─────────────────────────────────┼──────────┤
│ 0 │ replace │ C:\Windows\system32\replace.exe │ false    │
╰───┴─────────┴─────────────────────────────────┴──────────╯
C:\〉which replace-all
C:\〉
```

### Expected behavior

Please remove these from the documentation if they no longer exist.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
They do exist for dataframes. You can see this by doing `help replace`
