### ISSUE TITLE
Consider making `$a + $b` with records, tables or lists be equivalent to `($a | append $b)`

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6746]
### Describe the solution you'd like

I admit this use of `+` is something of a Python-ism, and you may wish to reserve single-character operators for only primitives as a general rule, but I personally think there isn't much harm in allowing this operator to be used for general concatenation of the common data structures (*especially* since it already concatenates strings). This use-case doesn't really tread on `append`'s functionality, I think.

**Comment by fdncred** [comment]
Thank for the suggestion. We do use `+` for concatenating strings so it probably wouldn't be too hard to extend to other areas.

**Comment by kubouch** [comment]
I'm not sure we want the `+` to mean "append" because it could also mean "add elements from the two records together". The latter one is how our dataframes work. I think it might become confusing what `+` means.

**Comment by fdncred** [comment]
I could live with `++` for concatenating lists, records, tables.

**Comment by WindSoilder** [comment]
I think this can be closed :)

**Comment by webbedspace** [comment]
This doesn't work on records!
```
〉{a:1 b:2} ++ {a:3}
Error: nu::parser::unsupported_operation (link)

  × Types mismatched for operation.
   ╭─[entry #3:1:1]
 1 │ {a:1 b:2} ++ {a:3}
   · ────┬──── ─┬ ──┬──
   ·     │      │   ╰── any
   ·     │      ╰── doesn't support these values.
   ·     ╰── any
   ╰────
  help: Change any or any to be the right types and try again.

```
Also, the error message for heterogenous tables is bad:
```
〉[[a b]; [1 2]] ++ [[a c]; [1 3]] | table -e
Error: nu::parser::unsupported_operation (link)

  × Types mismatched for operation.
   ╭─[entry #7:1:1]
 1 │ [[a b]; [1 2]] ++ [[a c]; [1 3]] | table -e
   · ───────┬────── ─┬ ───────┬──────
   ·        │        │        ╰── table<>
   ·        │        ╰── doesn't support these values.
   ·        ╰── table<>
   ╰────
  help: Change table<> or table<> to be the right types and try again.
```
