### ISSUE TITLE
config `filesize_format`: `auto` variant which can only use "b" units (mb, kb) or "ib" units (mib, kib) even if the system default is the other kind

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6748]
### Describe the solution you'd like

I use an alternative Windows file explorer called OneCommander, which defaults to filesizes in ISO units (mb, kb) rather than Windows units. Hence, I use the ISO units more often even though I am on Windows. I'd like to configure nu to use an "auto" variant which only uses mb, kb, etc. instead of mib, kib. Currently I believe this isn't available. In the interest of symmetry, the converse option would also be nice. You could call one `auto_ib` and the other `auto_b`.

**Comment by fdncred** [comment]
there are two settings that control this `filesize_format` and `filesize_metric`. I think you can do what you're wanting with these two settings.

**Comment by webbedspace** [comment]
OK… `filesize_metric` isn't listed in the default config.nu, and I can't seem to find it in [here](https://www.nushell.sh/book/configuration.html), so I don't actually know what it accepts, but I'll take your word for it.

**Comment by fdncred** [comment]
if `filesize_metric` is true then it returns kib, mib, gib, etc.
