### ISSUE TITLE
`help` page for `ls` says that it "lists all files", even though it doesn't do that unless you provide `--all`

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6753]
### Describe the bug

This seems like an obvious contradiction.

### How to reproduce

![image](https://user-images.githubusercontent.com/83939/195994919-c7982348-0294-4011-8f48-b92004d8ecd4.png)

### Expected behavior

The examples' wording should really say something like "all visible files" so that people who REALLY need it to list all files (because they're going to do something like run them into `mv` or `cp` immediately before running `rmdir`) aren't misled.

(By the way, it should probably also mention that `ls` lists directories, too…)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
I believe that if you're on windows it lists all files. It would be good to clarify.

**Comment by sholderbach** [comment]
Would you mind filing a PR with your suggestion?
https://github.com/nushell/nushell/blob/7d5d53cf85ee75895698a07e6f69c4fb1f55fbff/crates/nu-command/src/filesystem/ls.rs#L25-L65
