### ISSUE TITLE
Documentation: `alias` with brackets doesn't actually work with pipes unless `$in` is inserted at the front

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6758]
### Describe the bug

All of the "alias with pipes" examples on https://www.nushell.sh/book/aliases.html use `ls` in them, which obfuscates a rather unexpected issue with their syntax: you can't actually pipe into an alias that's bracketed unless `$in` is at the front of the bracketed pipeline.

### How to reproduce

Here's an example of what I mean. As you can see, `foo` doesn't work, but `qux` does.
```
〉alias foo = ( lines | each { parse "{filename}:{text}" } )
〉"bar:baz" | lines
╭───┬─────────╮
│ 0 │ bar:baz │
╰───┴─────────╯
〉"bar:baz" | foo
Error: nu::shell::cant_convert (link)

  × Can't convert to string.
   ╭─[entry #37:1:1]
 1 │ "bar:baz" | foo
   ·             ─┬─
   ·              ╰── can't convert nothing to string
   ╰────

〉alias qux = ( $in | lines | each { parse "{filename}:{text}" } )
〉"bar:baz" | qux
╭───┬───────────────╮
│ 0 │ [table 1 row] │
╰───┴───────────────╯
```

### Expected behavior

On the one hand, I understand that this is how bracketing syntax works, and how order-of-operations in Nu works… but I do think it's a little awkward to write, and moreover, it should really be covered by the documentation.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by weirdan** [comment]
This syntax has been removed in 0.80 (it was called `old-alias` at the time). Currently suggested replacement is custom `def` which doesn't suffer from this problem.
