### ISSUE TITLE
`to nuon` (but not `to json`) seems to replace piped-in errors with its own nonsensical error

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6763]
### Describe the bug

When an error is piped into `to json`, the error is properly displayed. However, this is not so for `to nuon`.

### How to reproduce

See examples:
```
〉"Ear" | where "A" | to json
Error: nu::shell::incompatible_path_access (link)

  × Data cannot be accessed with a cell path
   ╭─[entry #569:1:1]
 1 │ "Ear" | where "A" | to json
   ·               ─┬─
   ·                ╰── string doesn't support cell paths
   ╰────

〉"Ear" | where "A" | to nuon
Error: nu::shell::unsupported_input (link)

  × Unsupported input
   ╭─[entry #570:1:1]
 1 │ "Ear" | where "A" | to nuon
   ·                     ───┬───
   ·                        ╰── error not supported
   ╰────
```

### Expected behavior

I expect the error messages to be identical in both cases. (By the way, why exactly does the `json` variant of `to` have different error handling to the `nuon` version??)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by sholderbach** [comment]
This might be touching an unresolved semantic question if we want the nuon format allow to serialize error types (or other runtime state from nushell).
If we decide not to do that, reporting the error is probably more practically useful.

**Comment by webbedspace** [comment]
This is fixed in main currently.
