### ISSUE TITLE
`where` implicitly coerces records to tables instead of returning the record (if condition is true)

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6764]
### Describe the bug

When piped a record, and if the condition is true regarding the record, `where` will NOT return the record, but a table of it.

### How to reproduce

See example:
```
〉{A:1,B:2}
╭───┬───╮
│ A │ 1 │
│ B │ 2 │
╰───┴───╯
〉{A:1,B:2} | where A == 1
╭───┬───┬───╮
│ # │ A │ B │
├───┼───┼───┤
│ 0 │ 1 │ 2 │
╰───┴───┴───╯
```

### Expected behavior

I understand the type signature of `where` is a little dicey at the moment, but there is one principle I think it should uphold: *not type-coercing the data like 90s JavaScript*. As such, I think its current behaviour regarding JSON-style records is rather unpleasant. I expect `where` to filter data, not transform it.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
Thanks. I think this is a good point. One would think this wouldn't be too tricky to change.

**Comment by webbedspace** [comment]
I believe that `where` selects rows, and records are functionally "one-row tables", so I believe `{A:1,B:2} | where A == 1` actually works correctly - i.e. it lets the record pass if it has A:1, and produces an empty something-or-other if it doesn't.

**Comment by rgwood** [comment]
Hmm. I kind of think that this should return an error. IMO a collection/list of values is the only input that makes sense for `where`;
 I'm a little scared by the idea of treating single values like 1-element lists.

**Comment by webbedspace** [comment]
I've decided to continue this in a different issue now that I more fully understand the problem and what the solution should be.
