### ISSUE TITLE
Data values in outputted structures could be syntax-coloured to match their type

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6767]
### Describe the solution you'd like

Here's an example from my hard drive:
![image](https://user-images.githubusercontent.com/83939/196037230-e8962381-a15a-4121-8871-c155a80ba833.png)
I think each data value on the right side could be coloured to match and express its type. For instance, the `{record 2 fields}`, `[list 3 items] and `[table 2 rows]` values could be coloured using the "record" or "list" colours, to make it clear these are not just strings.

Here's another, funnier example:
![image](https://user-images.githubusercontent.com/83939/196037537-e5d39bba-e635-4b24-9ba5-d09569f6ead8.png)
As you can see, some of these are strings mimicking as other types. Colouring could help alleivate this ambiguity. Notice that the input has separate colours for the types used (string, number, record) and these could be used on the output as well.

**Comment by weirdan** [comment]
This can be configured now: 
![image](https://github.com/user-attachments/assets/b6c781d7-e78b-4a22-9bbd-1c544375cb34)
![image](https://github.com/user-attachments/assets/17a1be77-82e1-43ad-b07b-42a0ab23a4bf)
