### ISSUE TITLE
Some JSON arrays-of-objects are interpreted as tables by the output even though they shouldn't

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6768]
### Describe the bug

It seems that JSON arrays-of-objects, where all the objects have the same shape, are interpreted as tables when loaded into Nu. However, there are some cases where arrays-of-objects contain objects *without* the same shape, but are interpreted as tables by the output anyway.

### How to reproduce

Take a gander at this:
```
〉{ foo: [{a:1, b:2},{a:2,b:3}] }
╭─────┬────────────────╮
│ foo │ [table 2 rows] │
╰─────┴────────────────╯
〉{ foo: [{a:1, b:2},{a:2,b:3}] } | $in.foo | describe
table<a: int, b: int>
〉{ foo: [{a:1, b:2},{a:2,b:3},4] }
╭─────┬────────────────╮
│ foo │ [table 3 rows] │
╰─────┴────────────────╯
〉{ foo: [{a:1, b:2},{a:2,b:3},4] } | $in.foo | describe
list<any>
〉
```

### Expected behavior

The mistake here is `[table 3 rows]`. It clearly is not a table (and is interpreted as not-a-table by `describe`) but is listed as such in the output in that position. It should say `[list 3 items]`.

Here is another telling example:
```
〉{ foo: [{a:1, b:2},{e:2,f:3},4] }
╭─────┬────────────────╮
│ foo │ [table 3 rows] │
╰─────┴────────────────╯
〉{ foo: [{a:1, b:2},{e:2,f:3},1,2,3,4] }
╭─────┬────────────────╮
│ foo │ [table 6 rows] │
╰─────┴────────────────╯
〉{ foo: [{a:1, b:2},1,2,3,4] }
╭─────┬────────────────╮
│ foo │ [table 5 rows] │
╰─────┴────────────────╯
〉{ foo: [1,2,3,4] }
╭─────┬────────────────╮
│ foo │ [list 4 items] │
╰─────┴────────────────╯
〉{ foo: [1,{a:1, b:2},2,3,4] }
╭─────┬────────────────╮
│ foo │ [list 5 items] │
╰─────┴────────────────╯
〉
```
As you can see, simply placing an object at the front of an array is enough to get it mis-classified as a table, it seems.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by sholderbach** [comment]
In nu at the moment a table is a list of records and missing keys do not change that. Basically at the moment the table notion is followed on the consumer side. We should probably clarify what the semantics are for lists with non record entries mixed with record entries.

**Comment by webbedspace** [comment]
Aren't the semantics obvious, that a list containing any non-records in any position should be considered "not a table" pretty much without question?
