### ISSUE TITLE
`describe`'s separate behaviour for dataframes and databases should be separate commands

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6770]
### Describe the solution you'd like

In my opinion, there is **no** reason why something as fundamental to the language as `describe` (which at the moment seems to be the *only* reliable type-checking facility in the entire language) should have a completely different type signature and functionality when its input is dataframe-type or database-type. This greatly harms the utility of `describe` and makes it much more difficult to think about or use in scripts. I strongly recommend making the dataframe and database variants into separate commands.

**Comment by rgwood** [comment]
I very much agree with this.

**Comment by rgwood** [comment]
The `describe` command for databases has been removed in #7040.

We've got a tentative plan for dataframes that will resolve this indirectly, by removing dataframe support+commands from the default Nu release. Discussion is happening [in #design-discussion on Discord](https://discord.com/channels/601130461678272522/615329862395101194/1043957210172108850).

> Hi, we're considering removing dataframe support from the default Nu install. If you have feelings about this, please speak up!
> 
> **The Tentative Plan**
> 
> Dataframes would still be available behind a Cargo feature (`cargo install nu --features=dataframe`). However, they would not be included in the release binaries published on GitHub or the default binaries published via package managers (like Homebrew, winget, Scoop). Dataframes would not be tested in CI on every push (although we might consider testing them in CI at a reduced frequency).
> 
> **Why?**
> 
> Nu's dataframe support is extensive, impressive, and very useful to users who rely on it. However, it comes at a high cost:
> 
> - Dataframe support roughly doubles the size of the Nu executable (~20MB -> ~40MB)
> - Dataframe support roughly doubles Nu's compile time (sometimes more)
> - Dataframe support includes a lot of commands (~120) and many of them have the same names as "regular" commands. This sometimes makes learning+finding Nu's fundamental commands harder for newcomers

**Comment by webbedspace** [comment]
I'm going to be reticent and say that the dataframe `describe` should be removed directly as well as indirectly. I think it's much more important for `describe` to produce `dataframe<name:string, value:i64>` or whatever instead of its current output, which should be renamed to `summarize` or something like that.

**Comment by rgwood** [comment]
I agree. We’re a bit short on contributors with an interest in dataframes, but that would be a good change if one comes along.
