### ISSUE TITLE
Would it be too much trouble to make `ls -l` the default `ls` behaviour?

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6774]
### Describe the solution you'd like

I think the `-l` flag is one which `ls` doesn't really need (and kind of muddies the simplicity of Nushell by serving as yet another "mode" for `ls`), insofar as the extra columns added by it (`target`, `readonly`, `created`, and `accessed`) aren't that wide or difficult to ignore. I figure most `ls` calls are passed into a `get`, anyway.

The only problems I can see are A) some of these columns may not be cross-platform safe (for instance, does `created` even exist on POSIX systems?), and B) some other code somewhere may assume that `ls` output only has the type signature `table<name: string, type: string, size: filesize, modified: date>` and type-check based off of it.

**Comment by dandavison** [comment]
Without expressing an opinion for or against, I just want to say that one other possibility would be to remove `size` and `modified` from default `ls` output so the command by default just says "what" is present and for all metadata you use `-l`.

**Comment by webbedspace** [comment]
To be clear, the motivation for this idea is to make `ls` more useful as a pipeline-starter, and in that respect having all of the data on the table means you don't have to go back and add `-l` because you realised you needed to include the creation date in whatever command you're writing. So, I reject the idea of adding *fewer* columns to its default output.

**Comment by rgwood** [comment]
FWIW, `ls -l` output is very wide on Linux (maybe macOS too, I haven't checked):

![image](https://user-images.githubusercontent.com/26268125/197347001-130955f2-5367-4e40-8168-e782efa56b69.png)

**Comment by webbedspace** [comment]
I imagine that the default `table` view would truncate it (similar to how other long tables are truncated) but in a special `ls`-specific way where the `-l` columns are truncated first, prioritising them over the normal columns.

**Comment by rgwood** [comment]
I understand your use case but I'm iffy on this change right now. 13 columns is a lot to show by default, and many users will already have `ls -l` muscle memory.

> I imagine that, as a solution, the default table view would be made to truncate it (similar to how other long tables are truncated) but in a special ls-specific way where the -l columns are truncated first, prioritising them over the normal columns.

I like that idea, could be a nice UX improvement.

**Comment by Kixunil** [comment]
Could it be achieved simply by ordering the most important fields first? If not could it be made universal so that other commands can define importance of the fields? I have some such commands that have shitload of stuff but some fields are much less important than the others so this would be perfect.

**Comment by webbedspace** [comment]
If there's a performance reason for leaving these other columns off by default, then I understand completely.

**Comment by fdncred** [comment]
I was just looking at this again. Wouldn't an alias do this trick? It seems to work for me on my Mac.
```
alias ls = ls -l`
```

**Comment by dandavison** [comment]
@fdncred this issue is a design discussion:

> I think the -l flag is one which ls doesn't really need (and kind of muddies the simplicity of Nushell by serving as yet another "mode" for ls),

Unless I'm misunderstanding your suggestion, an alias would only address the perceived issue for the user who creates the alias. Or are you suggesting installing that alias automatically for all nushell users?

**Comment by fdncred** [comment]
In reading through all the comments again, I was just suggesting to @webbedspace that an alias seems to be a work-around for them. I wouldn't want `ls -l` to be a default in nushell for `ls`.

**Comment by dandavison** [comment]
Ah right, yes I think this was a design proposal -- I don't think the author was looking for a personal solution (I think they know how to do that).
