### ISSUE TITLE
Panic on invalid root in globs

### ISSUE THREAD

**Issue by Dorumin** [nushell/nushell#6776]
### Describe the bug

When walking a glob with the `wax` crate, a panic is thrown when stripping roots, like `/` in Windows. This seems to be the case for any absolute path

### How to reproduce

Run `glob /` in Windows. `glob C\:` also fails, which is possibly more concerning

### Expected behavior

The glob should either not match or return an error, likely the former

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by richardmarklund** [comment]
Hello!
My first comment in this repo. I looked at this a bit, seems to be a problem with the wax dependency (https://github.com/olson-sean-k/wax). Not sure if we should add a check with an error if you do glob / or glob C\:

Sorry if I've misunderstood or if this is not helpful at all :)

**Comment by webbedspace** [comment]
This is still present today… and I think adding a Windows-only check is going to be necessary.

**Comment by sholderbach** [comment]
Doesn't panic anymore since #10574 

```
~\Documents\Coding\nushell> glob C:\ | first 10
Error:   × error with glob pattern
   ╭─[entry #2:1:1]
 1 │ glob C:\ | first 10
   ·      ─┬─
   ·       ╰── failed to parse glob expression
   ╰────


~\Documents\Coding\nushell> glob \ | first 10
Error:   × error with glob pattern
   ╭─[entry #3:1:1]
 1 │ glob \ | first 10
   ·      ┬
   ·      ╰── failed to parse glob expression
   ╰────


~\Documents\Coding\nushell> glob / | first 10
╭───┬─────╮
│ 0 │ C:\ │
╰───┴─────╯
```

The last option takes an astonishingly long time to complete but succeeds.
