### ISSUE TITLE
Unhelper message can happened when input command which is exists in dataframe

### ISSUE THREAD

**Issue by WindSoilder** [nushell/nushell#6780]
### Describe the bug

When dataframe feature is enabled, input dataframe command which input is not dataframe, the error message is misleading

The issue is mentioned many times on discord server, I think it's ok to tracking it here...

### How to reproduce

```
❯ 3 | as-datetime
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #20:1:1]
 1 │ 3 | as-datetime
   ·     ─────┬─────
   ·          ╰── did you mean 'as-datetime'?
   ╰────
  help: No such file or directory (os error 2)
```

### Expected behavior

It should report that command is not found(when dataframe feature is not active, I think the behavior is ok) or just report an invalid input.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.2                                          |
| branch             | main                                            |
| commit_hash        | ec8e57cde975c20dcc1bd84e7bcb0d40b1cd3a58        |
| build_os           | macos-x86_64                                    |
| build_target       | x86_64-apple-darwin                             |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-apple-darwin                      |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.2                                          |
| build_time         | 2022-10-17 09:32:56 +08:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | from-binary                                     |

**Comment by fdncred** [comment]
it has to be in here more than once too

**Comment by WindSoilder** [comment]
Closing this because we append `dfr` prefix again
