### ISSUE TITLE
Nu freezes when running `do -i { python -X importtime -c "import something" }`

### ISSUE THREAD

**Issue by flying-sheep** [nushell/nushell#6783]
### Describe the bug

Running that command freezes the nu process. The Python subprocess can’t be killed using Ctrl-C either, nu has to be killed via process mangager.

Running just the following works without problem, just wrapping it into `do -i {}` is problematic

```
python -X importtime -c "import os"
```

### How to reproduce

```
do -i { python -X importtime -c "import os" }
```

### Expected behavior

exits after a few milliseconds

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             | makepkg                                         |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0 (Arch Linux rust 1:1.64.0-1)       |
| cargo_version      | cargo 1.64.0                                    |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 03:30:35 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
hey @flying-sheep, would you mind trying on the latest main? we've had some changes in this area that hopefully fix this.

**Comment by WindSoilder** [comment]
I've tested it on the latest main, and can't reproduce the issue..

**Comment by nibon7** [comment]
> I've tested it on the latest main, and can't reproduce the issue..

me too.

**Comment by flying-sheep** [comment]
indeed, fixed in main

**Comment by WindSoilder** [comment]
Yeah, it changes the behavior of external command result handling
