### ISSUE TITLE
Scanf equivalent command

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#68]
Rather than only having split-column, it'd be nice to have a scan-column that can do a split but based on a pattern.

Eg) `rg -n None | split-row "\n" | scan "<Filename>: <Line>: <Extra>"`

**Comment by JackFly26** [comment]
Maybe something with regex captures? like `match (.*): (.*) (.*)`?

**Comment by HiruNya** [comment]
How would this differ from the ``read`` command introduced in version 5?

**Comment by jonathandturner** [comment]
@HiruNya - good catch

This should be closed now. The command is now called `parse` for folks who find this later.
