### ISSUE TITLE
Confusing behavior of fetch on 404

### ISSUE THREAD

**Issue by evant** [nushell/nushell#6803]
### Question

When writing a script I was surprised to discover that calling fetch on a url that 404's will not fail but will instead happily download the 404 page. In my case this masked a typo in the url which took me a while to track down. Would it make sense to change this behavior either as default or by adding an additional flag?

**Comment by webbedspace** [comment]
Quick question: does this thing actually return a HTTP error code 404 NOT FOUND, or is it one of those newfangled "404" pages which are actually delivered as 301 MOVED or 200 OK?

**Comment by webbedspace** [comment]
Checked `curl --help`... It has `-f` for "fail" for exactly this case… Following `curl`'s lead isn't a bad idea, I think.
