### ISSUE TITLE
Data access of $in replaces prior error messages with another error

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6805]
### Describe the bug

Similar to #6763, if `$in` has become an error, attempting to access data from it causes a different error to occur (preventing the first error from being presented to the user).

### How to reproduce

```
ls | group-by type | flatten | $in.dir
Error: nu::shell::incompatible_path_access (link)

  × Data cannot be accessed with a cell path
   ╭─[entry #35:1:1]
 1 │ ls | group-by type | flatten | $in.dir
   ·                                    ─┬─
   ·                                     ╰── error doesn't support cell paths
   ╰────
```

### Expected behavior

I expect the original error to still be presented regardless of the occurrence of `$in.dir`.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by merelymyself** [comment]
I looked a bit into this and the problem here seems to be that Value::Error is being passed instead of an Err().

**Comment by sholderbach** [comment]
Now we provide usable error message here:

```
Error: nu::shell::column_not_found

  × Cannot find column 'dir'
   ╭─[entry #1:1:6]
 1 │ ls | group-by type | flatten | $in.dir
   ·      ────┬───                      ─┬─
   ·          │                          ╰── cannot find column 'dir'
   ·          ╰── value originates here
   ╰────
```
