### ISSUE TITLE
[packaging] Test package dependecies using sbuild

### ISSUE THREAD

**Issue by jankoprowski** [nushell/nushell#681]
We need to test package dependencies. The best way is to use the same tools Ubuntu developers use. They are using sbuild. Here is some documentation:

* https://wiki.debian.org/sbuild
* https://wiki.ubuntu.com/SimpleSbuild
* https://wiki.debian.org/HowToPackageForDebian
* http://packaging.ubuntu.com/html/packaging-new-software.html

ADAIK sbuild creates chroot, put some basic packages inside and test our package.

**Comment by andrasio** [comment]
#900
