### ISSUE TITLE
`rm` of nonexistant file produces error message with incorrect arrow

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6810]
### Describe the bug

When using `rm` with a nonexistant filename, the error message's arrow is pointing to `rm` instead of the filename.

### How to reproduce

```
〉rm file.txt
Error:
  × No valid paths
   ╭─[entry #42:1:1]
 1 │ rm file.txt
   · ─┬
   ·  ╰── no valid paths
   ╰────
```

### Expected behavior

Compare this with `mv`:
```
〉mv file.txt file2.txt
Error:
  × Invalid file or pattern
   ╭─[entry #45:1:1]
 1 │ mv file.txt file2.txt
   ·    ────┬───
   ·        ╰── invalid file or pattern
   ╰────
```
I suppose this is because `mv` takes the source filename in the middle of its arguments, whereas `rm` takes any number of filenames.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by naosense** [comment]
Does anyone work on this?

**Comment by nibon7** [comment]
The span is `call.head` which points to `rm`.

https://github.com/nushell/nushell/blob/c731a4e275ab0a0f947fb9254d76dd23f49a0233/crates/nu-command/src/filesystem/rm.rs#L273
