### ISSUE TITLE
Cannot execute external `cd` command on linux

### ISSUE THREAD

**Issue by lukexor** [nushell/nushell#6811]
### Describe the bug

Trying to use the built-in system `cd` instead of either the nushell builtin OR a custom alias fails with an external command error.

I know this topic has been an issue before but I couldn't find the exact issue

### How to reproduce

```
❯ ^cd ~
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #8:1:1]
 1 │ ^cd ~
   ·  ─┬
   ·   ╰── did you mean 'cd'?
   ╰────
  help: No such file or directory (os error 2)
```

### Expected behavior

Expected to be able to use the native or unalias'd `cd` command

### Configuration

```
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-10-11 19:29:28 -07:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |
```

### Additional context

The primary use case here is for me is adding `cd` hook logic that was previously available as the nu exec upon cd feature that used to exist but was removed in engine-q. As-is there is no way to automatically update $env.PATH to correct nodejs versions when cd'ing into multiple projects.

**Comment by merelymyself** [comment]
Does a native `cd` command even exist? `/usr/bin/which cd` offers me nothing.

**Comment by lukexor** [comment]
Well by native I mean the default system. `cd` in nushell is an internal nushell command that handles $env.PWD and other custom nushell logic.

In previous versions executing `^cd` opts into the external system `cd` instead of the nushell command.

**Comment by fdncred** [comment]
I think previously nushell would shell out and do something like `sh -c 'cd ~'`. I didn't think that was a recent change. I want to say it's been in there for a few versions now.

**Comment by lukexor** [comment]
Also need to confirm if this is Linux specific. It works on 0.68.1 on macOS.

**Comment by Decodetalkers** [comment]
As far as I known, cd is always a buildin command of a shell, and no execute program provide cd. 
![image](https://user-images.githubusercontent.com/60290287/196965183-86b1605d-d050-4dde-bb3d-26795af1ecd7.png)
Do you have /usr/bin/cd or a program named `cd` in your `PATH`?

**Comment by lukexor** [comment]
Ah it does appear that macos has a `/usr/bin/cd` available. I've primarily used macos over the years, so this is the first time I tried porting to linux for daily use.

The core requirement I have is to "hook" into `cd` and still call the original `cd` command to be able to execute node version check and update my PATH to the correct version. I may have a possible work-around in mind.

**Comment by rgwood** [comment]
Closing because this doesn't seem like a Nu problem after the investigation above. Let us know if you're still having related issues.
