### ISSUE TITLE
Let 'where' and friends accept the shortest abbreviation possible within a given context

### ISSUE THREAD

**Issue by eugenesvk** [nushell/nushell#6813]
### Related problem

Nushell has this awesome idea of being **context aware**, e.g., in the
`ls | where modified >= (date now) - 3wk` command the shell (and the user) know that it's about **time**!
However, this great idea currently has its wings clipped by the use of rather inefficient and not very intuitive abbreviations
For example, in the context of __time__
  - How would you guess that a week is `wk`, but a month is `month`?
  - And then a year is again `yr`?
  - Why is a second a `sec`, but part of a second a `ms`?

### Describe the solution you'd like

Whenever a __context is known__, you should use the best, i.e. __shortest__, abbreviations as the context already gives the user all the information needed to infer the full name behind such an abbreviation

For example, in the context of __time__, there is absolutely no need to spell out `sec` when `s` is obviously a second, there is no other time unit that starts with an __s__, so there is no ambiguity.
Also, it's very __easy to remember__ — just take the __first letter__ and you're done
Also, it's very __easy to type__ — just __one letter__!
There is only one complicatoin — min vs month and that would need to be remembered unless you have an across-the-context rule that the smaller units get the smaller abbreviation, then this ambiguity could also be resolved more intuitively (or you could let the most frequently used unit get the shortest abbreviation and then require memorization)

| Old   	|	New|
|----   	|----|
|  ns   	|ns|
|  us   	|us|
|  ms   	|ms|
|  sec  	| s|
|  min  	| m |
|  hr   	| h|
|  day  	| d|
|  wk   	| w|
|  month	|mn|
|  yr   	| y|
|  dec  	| d|

Similarly, for the file size units as already discussed in a prematurely [closed issue](https://github.com/nushell/nushell/issues/3023) there is no need for `b` in `Mb`, it's already obvious that they're all bytes!

| Unit    	| Old	| New|
|----     	|----	|----|
|Kilobyte 	|KB  	| k  |
|Megabyte 	|MB  	| m  |
|Gigabyte 	|GB  	| g  |
|Terabyte 	|TB  	| t  |
|Petabyte 	|PB  	| p  |
|Exabyte  	|EB  	| e  |
|Zettabyte	|ZB  	| z  |
|Byte     	|B   	| b  |

And if you insist on an explicit differentiaton between base₁₀ and base₂ (interesting choice)
| Unit   	| Old	| New|
|----    	|----	|----|
|Kibibyte	|KIB 	| ki |
|Mebibyte	|MIB 	| mi |
|Gibibyte	|GIB 	| gi |
|Tebibyte	|TIB 	| ti |
|Pebibyte	|PIB 	| pi |
|Exbibyte	|EIB 	| ei |
|Zebibyte	|ZIB 	| zi |

### Describe alternatives you've considered

The only very bad alternative I could think of at the moment is allowing user customization of the labels, but that would make commands non-portable across nushell installations, so at least for the core units best avoided

### Additional context and details

One argument I've read earlier is that
> As people use additional unit types, it feels like we should make them more readable now rather than more compressed

But readability comes from the context! The way to differentiate between an `m` as a minute and an `m` as a Megabyte is by looking at the `size` part vs the `modified` part of the `where` command
Or at the name of the conversion command
`'2m' | into filesize` is not about minutes!
`'2m' | into datetime` is not about megabytes!

**Comment by webbedspace** [comment]
To be clear, this isn't really about `where` or "friends", and mentioning them is confusing the issue - this is about the builtin time and filesize units, which you can write as literals anywhere applicable:
```
C:\〉3wk | describe
duration
C:\〉3gb | describe
filesize
```
That's why this whole topic is fundamentally unsound. Watch this:
```
〉ls | upsert modified 2kb | upsert size 2wk | where modified > 2b
╭────┬───────────────────────┬──────┬──────┬──────────╮
│  # │         name          │ type │ size │ modified │
├────┼───────────────────────┼──────┼──────┼──────────┤
│  0 │ .cargo                │ dir  │ 2wk  │   2.0 KB │
│  1 │ .git                  │ dir  │ 2wk  │   2.0 KB │
```
`ls` only outputs an ordinary table. Once it hits the pipe, it is nothing more. There is nothing inherent about the `modified` column of a table that states that a `date` is inside. Therefore, **the context cannot be known, ever**. Thus, it's impossible to use contextual abbreviations like `2m`.

Unless you wish to make `ls` output a special "typed table" that loses its typings when it contacts `upsert` and the like, you should rethink what you are asking for.

By the way, I personally think dropping the `b` from filesizes is definitely too saucy, especially since A) you can also express them in mebibyte format (the format used by Windows Explorer) by typing `3mib`, B) the self-acknowledged minute/month/megabyte collision, and C) there are way bigger places to save characters in this language than just the letter `b` in a single literal type.

I will say that `wk` kind of sticks out compared to `day`, `month`, etc, and am wondering whether any other shells/langs have a standard for this. (Any Perl knowers nearby?)

**Comment by sholderbach** [comment]
@webbedspace is making good points that the exact context quickly get's lost. 

As nushell allows expressions instead of just passing strings to each command, the parser would have to carry the possible types around the pipe to deconflict the ambiguous literals before the execution. As we in general try to simplify the parser to make it easier to understand for users (and resolve some issues at the moment that sounds like a tough ask. 
The general nushell philosophy in this case would be to favor the more explicit solution when it comes to the literals. 
I think opening up the conversion commands to a few missed ones on the other hand would be no problem.

**Comment by eugenesvk** [comment]
> There is nothing inherent about the `modified` column of a table that states that a `date` is inside.

You mean nothing except its __name__???

> `ls` only outputs an ordinary table

It's not an ordinary table, `ls` lists file info, `modified` in the context of file info is a date, that's like the whole point of header names to provide context!

> ls | upsert modified 2kb | upsert size 2wk | where modified > 2b

Yes, you can force data into incorrect units, so what? Even with proper "inherent" types you can coerce variables
How does that challenge the idea? Can you come up with __realistic__ __common__ workflows where the whole abbreviation goodness breaks down?


> By the way, I personally think dropping the b from filesizes is definitely too saucy, especially since A) you can also express them in mebibyte format (the format used by Windows Explorer) by typing 3mib, and

Or by typing `mi`?

> B) there are way bigger places to save characters in this language than just the letter b in a single literal type

So? What's your argument against saving characters in __this__ place?

**Comment by webbedspace** [comment]
> It's not an ordinary table

It is, though.
```
〉ls | describe
table<name: string, type: string, size: filesize, modified: date>
```
Its datatype is `table`. A `table` in Nushell is an ordered key-value data structure, analogous to the JSON "array-of-objects" pattern. Nothing about the table data structure assigns any strict semantic meaning to the column name "modified", nor does it forbid sticking `2kb` in a column named "modified".
```
〉ls | upsert modified 2kb | describe
table<name: string, type: string, size: filesize, modified: filesize>
```
This is also a table.

The only way you can get the context guarantees you're looking for is by changing `ls` to output a special "typed table" table where the column name `modified` always means `date`, and `upsert modified 2kb` causes a type error. But, there's no way for Nu to know in advance that the input to `where` is this special ls-type table, so typing `2m` is just not going to work unless `2m` magically means both "minutes" and "megabytes" at runtime.

>Or by typing `mi`?

To me, `2mi` looks like someone typoed `2min`. I also think mebibytes are rare enough that very few people will, lacking further context, immediately associate `mib` with `MiB`, let alone `mi` with `mib`. You really do need the `b` in this case.

**Comment by eugenesvk** [comment]
> table<name: string, type: string, size: filesize, modified: date>
>Nothing about the table data structure assigns any strict semantic meaning to the column name "modified"
>by changing ls to output a special "typed table" table where the column name modified always means date

What do you mean "nothing" when the `:date` type is right there in the table's signature!!! This type is the thing that assigns semantic meaning (aka type) to the column named "modified"! So you don't need to change ls to output a typed table when it's already a typed table.

>nor does it forbid sticking 2kb in a column named "modified".

I've already acknowledged that you can __coerce__ the correct type into a wrong one. What is still not clear is what the huge negative implications of this are? Is type coercion is such a common-but-hidden (or something) operation that has a high chance to confuse users? 

> The only way you can get the context guarantees

Ok, let's call the guarantees I'm looking for "weak context guarantees" so that they work just fine, but if you do type coercion, they fail because the default `:date` type silently changed from under the column's name
What's wrong with this? Would you please show real use cases illustrating issues here?

>To me, 2mi looks like someone typoed 2min.

Why would you think of minutes in the context of file sizes?

>mebibytes are rare enough that very few people will, lacking further context

if that's rare and they don't have any context, why are they typing this unit of measurement instead of `m`? Why would you need to associate anything on the input side?
On the output side you can include additional context in the column header (e.g., `size b₂` for the `-bi-` variants). Still no need for the useless `b` that's always obvious from the `size` context
(also, just noticed that wiki mentions these as real abbreviations `Systems based on powers of 2 ... might use ... their corresponding symbols (Ki, Mi, Gi, ...)`) Would accepting Capitalized symbols like these (in addition to lower-cased) resolve the confusion you mention?

**Comment by rgwood** [comment]
Thanks for the issue.

I generally agree with @webbedspace and @sholderbach on this one, and I don't think we'll be adding that kind of context awareness to the parser anytime soon. Closing for now, but feel free to suggest more specific changes in this issue or a new one.
