### ISSUE TITLE
subshell should trim new line for the last command in the pipeline automatically

### ISSUE THREAD

**Issue by avkonst** [nushell/nushell#6816]
### Describe the bug

```
> echo $"(pwd):/app"
/home/andrey/partly
:/app
```

### How to reproduce

echo $"(pwd):/app"

### Expected behavior

It should print one line output:
```
/home/andrey/partly:/app
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-musl                       |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:54:35 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

bash, fish and zsh do this.

**Comment by WindSoilder** [comment]
Here is the reason for the behavior, currently a workaround is using `str trim`.
https://www.nushell.sh/book/variables_and_subexpressions.html#subexpressions-with-external-commands

**Comment by avkonst** [comment]
And what is the reason? It just repeats the fact and does not explain the
reason for this unintuitive behavior

**Comment by rgwood** [comment]
Related: https://github.com/nushell/nushell/issues/3980

I think this would be good to fix.
