### ISSUE TITLE
`path join` by itself produces a strange error

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6819]
### Describe the bug

Typing `path join` by itself produces a bizarre double-arrowed error message.

### How to reproduce

```
〉path join
Error: nu::shell::pipeline_mismatch (link)

  × Pipeline mismatch.
   ╭─[source:1:1]
 1 │ nu
   · ▲
   · ╰── value originates from here
   ╰────
   ╭─[entry #98:1:1]
 1 │ path join
   · ────┬────
   ·     ╰── expected: string, row or list
   ╰────
```

### Expected behavior

The first `value originates from here` points to something that wasn't in the original command and should not be included.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:58:08 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by rgwood** [comment]
Good issue, thanks! It seems like this affects multiple `path` subcommands, as they share error handling code: https://github.com/nushell/nushell/blob/10aa86272bdcce63506f00f4dc8d0eafb99f7d0f/crates/nu-command/src/path/mod.rs#L92

`path parse` has the same problem:

```
〉path parse
Error: nu::shell::pipeline_mismatch (link)

  × Pipeline mismatch.
   ╭─[source:1:1]
 1 │ nu
   · ▲
   · ╰── value originates from here
   ╰────
   ╭─[entry #8:1:1]
 1 │ path parse
   · ─────┬────
   ·      ╰── expected: string, row or list
   ╰────
```
