### ISSUE TITLE
`table --expand` would look better if labels were aligned to substructures a bit better

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6821]
### Related problem

![image](https://user-images.githubusercontent.com/83939/196996676-8638b307-4809-4f83-8b44-1110d1d5aaf2.png)
So far, this expanded view looks good… except that the labels are currently aligned with the top box-drawing elements of the substructures, which means the labels appear "diagonally" aligned with the data (the top half of the labels is literally above the top half of the tables).

### Describe the solution you'd like

I think it would look better if the labels for substructures dropped down a row, like so:
![image](https://user-images.githubusercontent.com/83939/196997105-d9c0146e-eef9-4317-a96d-3901b31943ab.png)

**Comment by zhiburt** [comment]
Hi @rgwood 

Interesting proposition

What do you think about the case where the inner table is not 1 line.
Do you think it must be centered to overall height available or constantly be on the 2nd line?

**Comment by webbedspace** [comment]
Leaving it on the second line is consistent with how `table` usually works:
![image](https://user-images.githubusercontent.com/83939/197115257-758255a6-a2ed-450b-b877-19938885f63b.png)

**Comment by zhiburt** [comment]
I wonder what do you think about the 'internal' tables.
Should they be aligned too?

(Maybe no?)

![image](https://user-images.githubusercontent.com/20165848/197128881-f36d9b3f-beee-4299-96a4-b128461e13d1.png)

**Comment by webbedspace** [comment]
That case is a little trickier… With the principle that "the topmost text in each column is lined up", I think every entry inside the `host` subtable should be lowered by 1. That may be a little harder to implement, though.
