### ISSUE TITLE
Custom command boolean flag should allow to pass true/false from a command line

### ISSUE THREAD

**Issue by avkonst** [nushell/nushell#6827]
### Related problem

```
def main [--flag: bool] {
    echo $flag
}
```
running it:
```
script.nu --flag=false
```
always prints `true`

### Describe the solution you'd like

boolean flags are parsed from true/false values.
Also it would enable to forward boolean flags to commands in scripts, like:

```
def cmd  [--flag: bool] {
    echo $flag
}
def main [--flag: bool] {
    cmd --flag=$flag
}
```

### Describe alternatives you've considered

ugly scripts with repeatition when a flag needs to be passed to subcommands

**Comment by fdncred** [comment]
answered here https://github.com/nushell/nushell/discussions/6828

**Comment by avkonst** [comment]
unfortunately, it is not answered

**Comment by weirdan** [comment]
You no longer can add type annotations for boolean flags, but flags passed from the command line are now properly recognized as boolean values:

```console
$ open t.nu
def main [--flag] {
  echo [$flag ($flag | describe)]
}

$ nu t.nu --flag=true
╭───┬──────╮
│ 0 │ true │
│ 1 │ bool │
╰───┴──────╯

$ nu t.nu --flag=false
╭───┬───────╮
│ 0 │ false │
│ 1 │ bool  │
╰───┴───────╯

$ nu t.nu --flag
╭───┬──────╮
│ 0 │ true │
│ 1 │ bool │
╰───┴──────╯

$ nu t.nu
╭───┬───────╮
│ 0 │ false │
│ 1 │ bool  │
╰───┴───────╯
```

**Comment by sholderbach** [comment]
Thx for all the backlog clearing @weirdan !
