### ISSUE TITLE
ps emits empty output sometimes

### ISSUE THREAD

**Issue by avkonst** [nushell/nushell#6829]
### Describe the bug

ps utility has empty output. I have trapped it in a script which checks if a special process is running and if yes skips starting it, otherwise starts it. The result was that the process was starting the second time. I have started debugging and observed that the ps emits empty table output sometimes. I was able to reproduce it in a command line running ps --long very frequently manually.
 

### How to reproduce

run `ps --long` in a console frequently

### Expected behavior

ps always emits output

### Screenshots

![image](https://user-images.githubusercontent.com/3971413/197075242-9bcc7253-e752-4642-b268-ad1cf8acbab8.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-musl                       |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:54:35 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by avkonst** [comment]
It happens randomly, about in 1 out of 10 cases.

**Comment by rgwood** [comment]
I'm able to reproduce this on Linux verrrrry rarely. Haven't been able to reproduce it on Windows (yet?).

**Comment by rgwood** [comment]
This is a weird one! The easiest way I've found to reproduce it is to run `ps` in a loop:

```
/home/pi〉1..100 | each { ps | describe }
╭────┬─────────────────────────────────────────────────────────────────────────────────────────────╮
│  0 │ table<pid: int, name: string, status: string, cpu: float, mem: filesize, virtual: filesize> │
│  1 │ table<pid: int, name: string, status: string, cpu: float, mem: filesize, virtual: filesize> │
│  2 │ list<any>                                                                                   │
│  3 │ table<pid: int, name: string, status: string, cpu: float, mem: filesize, virtual: filesize> │
│  4 │ table<pid: int, name: string, status: string, cpu: float, mem: filesize, virtual: filesize> │
│  5 │ table<pid: int, name: string, status: string, cpu: float, mem: filesize, virtual: filesize> │
│
```

Note the `list<any>`; that's an empty table that is returned by 1 of the calls to `ps`.

If I log the length of the vectors returned by [`collect_proc()`](https://github.com/nushell/nushell/blob/5cc6505512bd9b92a1251a14539742441db2d8f3/crates/nu-system/src/linux.rs#L83) and [`run_ps()`](https://github.com/nushell/nushell/blob/c66b97126f71e24a99a2f265b3f5b5420488277d/crates/nu-command/src/system/ps.rs#L72) I see some _very_ curious results:

```
〉1..23 | each { ps | describe }
collect_proc.len: 62
run_ps.len: 62
collect_proc.len: 62
run_ps.len: 62
run_ps.len: 0
collect_proc.len: 59
run_ps.len: 59
...
```

Specifically:
```
collect_proc.len: 62
run_ps.len: 62
run_ps.len: 0
```

`collect_proc()` returns 62 processes from a call to [procfs](https://docs.rs/procfs/latest/procfs/)... and then `run_ps()` returns those 62 processes... but then `run_ps()` is somehow invoked again and it returns 0 results!?!

I don't see anything obvious in `ps` that would cause something like this to happen.

**Comment by rgwood** [comment]
OK, I think this is the culprit: https://github.com/nushell/nushell/blob/5cc6505512bd9b92a1251a14539742441db2d8f3/crates/nu-system/src/linux.rs#L121

I haven't fully wrapped my head around what Nu is doing with previous/current PIDs, but sometimes `Process::new(curr_proc_pid)` fails with a `NotFound` error and that ends up returning 0 results.

**Comment by rgwood** [comment]
Apologies for all the messages, I'm learning quite a bit about our `ps` functionality as I investigate this...

This is looking like a bug in our Linux `collect_proc()` implementation.

On Linux we take 1 snapshot of all processes, then 100ms later we take another snapshot. The delta of CPU time between the 2 snapshots is then used to calculate CPU usage [^1]. It seems like we are handling the edge case where process X is killed between the 2 snapshots very poorly.

The good news is that that should be an easy fix; if a process died between the 2 snapshots, we can just not return it.

[^1]: That seems to be the intent, at least. In practice I think there might be another bug where this code unintentionally overwrites the numbers from the 1st snapshot with a 3rd snapshot: https://github.com/nushell/nushell/blob/5cc6505512bd9b92a1251a14539742441db2d8f3/crates/nu-system/src/linux.rs#L123-L126
