### ISSUE TITLE
shape_directory missing from the default config

### ISSUE THREAD

**Issue by Szwagi** [nushell/nushell#6832]
### Describe the bug

shape_directory is not set or listed in the default config file

### How to reproduce

1. Recreate default config
2. shape_directory is not in dark_theme or light_theme

### Expected behavior

shape_directory should be there

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

It took me a while to figure out why I can't theme some things.

**Comment by fdncred** [comment]
Good catch. Someone should add that.
