### ISSUE TITLE
misleading error report on contains command

### ISSUE THREAD

**Issue by avkonst** [nushell/nushell#6833]
### Describe the bug

![image](https://user-images.githubusercontent.com/3971413/197083017-f67b01ae-2b89-4242-9b79-d59406d42265.png)

### How to reproduce

```
 ["aaa", "bbbb"] | contains "aaa"
```

### Expected behavior

Better error suggesting what is wrong with contains

### Screenshots

above

### Configuration

| ------------------ | ----------------------------------------------- |
| version            | 0.69.1                                          |
| branch             |                                                 |
| commit_hash        | 8a5abc7afc28a36908a32f1852127e2a5170b461        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-musl                       |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.69.1                                          |
| build_time         | 2022-09-28 02:54:35 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by rgwood** [comment]
Thanks for the bug report. Looks like an issue with command overloading (there is a command called "contains" that only works on dataframes, and the error message is not smart enough to know that that command will not work for your input).

**Comment by WindSoilder** [comment]
Relative: #6780, they're the same problem

**Comment by sholderbach** [comment]
Closed by the removal of our old command-overloading system.
