### ISSUE TITLE
`table`: indexes of 1000+ row table wrap around to 0 after every 1000

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6840]
### Describe the bug

When displaying a table with 1000+ rows, the indexes will wrap around back to 0 after index number 999.

### How to reproduce

This is from running `mame -listmedia | from ssv`. `mame -listmedia` returns a 44,308-line SSV file.
![image](https://user-images.githubusercontent.com/83939/197126701-763649a2-bd49-4cc5-abc0-21f2ebc69b62.png)

### Expected behavior

I expect the indexes to increment accurately. Note that the indexes are actually correct in the data structure itself: `mame -listmedia | from ssv | get 19001` works correctly.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
It didn't used to work like that. It would just go to 1000. I wonder when it changed.

**Comment by zhiburt** [comment]
I actually noticed it last week locally but after doing pulling main (or something like it) it was fixed.
Not sure.

```nu
1..100000
``` 

![image](https://user-images.githubusercontent.com/20165848/197187111-053d0ea9-06e2-44b6-ad3d-662676a704ba.png)
