### ISSUE TITLE
`open`: XML parse error message is misleading for newcomers

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6843]
### Describe the bug

The error message for `open` failing to parse XML from a file ending in `.xml` is highly likely to confuse newcomers.

### How to reproduce

Here are two examples of `open` error messages:
```
C:\Users\Leon\AppData\Roaming\Notepad++〉open `C:\Users\Leon\AppData\Roaming\Notepad++\config.xml`
Error: nu::shell::unsupported_input (link)

  × Unsupported input
   ╭─[entry #50:1:1]
 1 │ open `C:\Users\Leon\AppData\Roaming\Notepad++\config.xml`
   ·      ──────────────────────────┬─────────────────────────
   ·                                ╰── Could not parse string as xml
   ╰────

C:\Users\Leon\AppData\Roaming\Notepad++〉open config.xml
Error: nu::shell::unsupported_input (link)

  × Unsupported input
   ╭─[entry #51:1:1]
 1 │ open config.xml
   ·      ─────┬────
   ·           ╰── Could not parse string as xml
   ╰────

```
The phrasing `Could not parse string` combined with the arrow pointing to the filename implies (wrongly) that nu is parsing the *filename* as XML, instead of the error coming from the file itself.

### Expected behavior

It should say something like "Could not parse file contents as XML" in this particular case.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by rgwood** [comment]
Agree that this is worth fixing.

Tiny bit tricky to fix because the error message comes from `from xml`, and `open` is calling `from xml` to do its work.

https://cs.github.com/nushell/nushell/blob/c9fb381d69b0b23a7095c4d97ddf6ee476b65bb1/crates/nu-command/src/formats/from/xml.rs#L187

**Comment by sholderbach** [comment]
I wrapped the `from ...` errors with an additional error that mentions the file. This is probably just a minimal solution. The best case would be that we return a line number for the parse fail or even have local spans in the file.
