### ISSUE TITLE
Some commands that require a subcommand (like `config`) output their `help` when run as-is, but others (like `from`) don't

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6844]
### Describe the bug

See title.

The problematic commands that don't are `from`, `to` and `query`.
`query` doesn't even seem to exist without its subcommand.

### How to reproduce

```
〉config
Usage:
  > config

Subcommands:
  config env - Edit nu environment configurations
  config nu - Edit nu configurations
  config reset - Reset nushell environment configurations to default, and saves old config files in the config location as oldconfig.nu and oldenv.nu

Flags:
  -h, --help - Display this help message


〉from
〉to
〉query
Invalid parameter(s)
QUERY { PROCESS | SESSION | TERMSERVER | USER }
〉which query
╭───┬───────┬───────────────────────────────┬──────────╮
│ # │  arg  │             path              │ built-in │
├───┼───────┼───────────────────────────────┼──────────┤
│ 0 │ query │ C:\Windows\system32\query.exe │ false    │
╰───┴───────┴───────────────────────────────┴──────────╯
```

### Expected behavior

I expect all commands that require subcommands to output their help when run without a subcommand.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by sholderbach** [comment]
I think a subset of those issues might be related to the half baked command overloading for the dataframes/databases but more likely the issue is that we do not have a stub command that emits the available actually performing subcommands.

**Comment by sholderbach** [comment]
I think a subset of those issues might be related to the half baked command overloading for the dataframes/databases but more likely the issue is that we do not have a stub command that emits the available actually performing subcommands.

**Comment by sholderbach** [comment]
It should be relatively straightforward to take a look at how the meta commands are implemented. Follow for example https://github.com/nushell/nushell/pull/5616

**Comment by rgwood** [comment]
`query` is a bit of a weird one. The base `query` command exists in a plugin which is not installed by default. But I think that's mostly a historical accident and we should probably move it into core Nu.

**Comment by sigh-gone** [comment]
Is this still a good first issue?

**Comment by amtoine** [comment]
> ~Is this still a good first issue?~ I went on discord and was told this is still a good first issue. I will take it. I'm new to this code base so info like where i should work and stuff would be helpful
>
thanks for willing to help :pray: 

with the remaining `query`, you might need to create a brand new `query` command, because when looking at `query.rs`, it's not a real Nushell command, which is why it does not print any help and even throws an "unknown external command" error :open_mouth:

**Comment by sigh-gone** [comment]
> > ~Is this still a good first issue?~ I went on discord and was told this is still a good first issue. I will take it. I'm new to this code base so info like where i should work and stuff would be helpful
> 
> >
> 
> thanks for willing to help :pray: 
> 
> 
> 
> with the remaining `query`, you might need to create a brand new `query` command, because when looking at `query.rs`, it's not a real Nushell command, which is why it does not print any help and even throws an "unknown external command" error :open_mouth: 

Awesome, it will take a bit while I get comfortable, I've never made a nutshell command before but im excited. Im getting started on it today

**Comment by amtoine** [comment]
@sigh-gone 
i meant that, afaik, there is no implementation of the `Command` trait for the `Query` struct in `query.rs`, which is why it's not a Nushell command even though `query db` is one!

if you look at any other Nushell command, e.g. `from` and `to` to stay in the topic here, you'll see implementations of the `Command` trait
https://github.com/nushell/nushell/blob/cd0a52cf00a508476574d94f66b0841387df1631/crates/nu-command/src/formats/from/command.rs#L9
https://github.com/nushell/nushell/blob/cd0a52cf00a508476574d94f66b0841387df1631/crates/nu-command/src/formats/to/command.rs#L9

but also things like `ls`
https://github.com/nushell/nushell/blob/cd0a52cf00a508476574d94f66b0841387df1631/crates/nu-command/src/filesystem/ls.rs#L25

**Comment by sigh-gone** [comment]
So quick question, do you want me to change this from the Plugin trait to the Command trait? Both the Plugin trait and the Command trait have signature methods. I apologize if this is obvious, im still trying to figure out what all this does.

**Comment by amtoine** [comment]
> So quick question, do you want me to change this from the Plugin trait to the Command trait? Both the Plugin trait and the Command trait have signature methods. I apologize if this is obvious, im still trying to figure out what all this does.
>
let's try to just add a new command without changing traits :wink: 

> Also, should query.rs be moved from the nu_plugin_query directory if i need to implement command on it?
>
`nu_plugin_query` already has a `query.rs` and ships a `query` command when registered.
so you could try to add a `query.rs` next to `query_db.rs` to `nu-command` and see if it does not conflict with the `nu_plugin_query` plugin once registered

**Comment by sigh-gone** [comment]
> > So quick question, do you want me to change this from the Plugin trait to the Command trait? Both the Plugin trait and the Command trait have signature methods. I apologize if this is obvious, im still trying to figure out what all this does.
> 
> let's try to just add a new command without changing traits 😉
> 
> > Also, should query.rs be moved from the nu_plugin_query directory if i need to implement command on it?
> 
> `nu_plugin_query` already has a `query.rs` and ships a `query` command when registered. so you could try to add a `query.rs` next to `query_db.rs` to `nu-command` and see if it does not conflict with the `nu_plugin_query` plugin once registered

I got most of it done. one thing I'm unsure of is how to get the sub commands, I have query db in the --help flag, but i dont know how it got there. I included a picture to illustrate my point as well as get any feedback on whats wrong
![query_help](https://github.com/nushell/nushell/assets/112661044/04df591c-c2d2-4ebb-b9b7-f0b89078a068)

**Comment by amtoine** [comment]
@sigh-gone 
yeah, i think that's normal :ok_hand: 
`query db` is there by default, the others should appear once they are registered

**Comment by sigh-gone** [comment]
> @sigh-gone yeah, i think that's normal 👌 `query db` is there by default, the others should appear once they are registered

Awesome. This was indeed a good first issue. Just for my personal understanding (sorry if im asking too many questions), what file handles the registering of sub commands? I stepped through the code and still feel a bit confused. Also, is this good to make a pr or should i add to it?

**Comment by amtoine** [comment]
> what file handles the registering of sub commands?
>
not sure, there is `default_context.rs` in `nu-command` to add new commands but, otherwise, subcommands are detected automatically, e.g. if you define a subcommand for `ls`
```nushell
def "ls foo" [] {}
```
running `help ls` will show the `foo` subcommand directly without any extra step :wink: 

> Also, is this good to make a pr or should i add to it?
>
i think it's fine to add `query` in a PR :+1:

**Comment by sigh-gone** [comment]
> > what file handles the registering of sub commands?
> 
> not sure, there is `default_context.rs` in `nu-command` to add new commands but, otherwise, subcommands are detected automatically, e.g. if you define a subcommand for `ls`
> 
> ```nushell
> def "ls foo" [] {}
> ```
> 
> running `help ls` will show the `foo` subcommand directly without any extra step 😉
> 
> > Also, is this good to make a pr or should i add to it?
> 
> i think it's fine to add `query` in a PR 👍

im having a lot of issues squashing commits. im very sorry. im just going to take a break

**Comment by weirdan** [comment]
With 0.96 all of `from`, `to` and `query` show the help page when invoked without a subcommand:
```console
$ from
Parse a string or binary data into structured data.

You must use one of the following subcommands. Using this command as-is will only produce this help message.

Usage:
  > from

Subcommands:
  from csv - Parse text as .csv and create table.
  from eml - Parse text as .eml and create record.
  from ics - Parse text as .ics and create table.
  from ini - Parse text as .ini and create table.
  from json - Convert from json to structured data.
  from msgpack - Convert MessagePack data into Nu values.
  from msgpackz - Convert brotli-compressed MessagePack data into Nu values.
  from nuon - Convert from nuon to structured data.
  from ods - Parse OpenDocument Spreadsheet(.ods) data and create table.
  from ssv - Parse text as space-separated values and create a table. The default minimum number of spaces counted as a separator is 2.
  from toml - Parse text as .toml and create record.
  from tsv - Parse text as .tsv and create table.
  from url - Parse url-encoded string as a record.
  from vcf - Parse text as .vcf and create table.
  from xlsx - Parse binary Excel(.xlsx) data and create table.
  from xml - Parse text as .xml and create record.
  from yaml - Parse text as .yaml/.yml and create table.
  from yml - Parse text as .yaml/.yml and create table.

Flags:
  -h, --help - Display the help message for this command

Input/output types:
  ╭───┬─────────┬────────╮
  │ # │  input  │ output │
  ├───┼─────────┼────────┤
  │ 0 │ nothing │ string │
  ╰───┴─────────┴────────╯


$ to
Translate structured data to a format.

You must use one of the following subcommands. Using this command as-is will only produce this help message.

Usage:
  > to

Subcommands:
  to csv - Convert table into .csv text .
  to html - Convert table into simple HTML.
  to json - Converts table data into JSON text.
  to md - Convert table into simple Markdown.
  to msgpack - Convert Nu values into MessagePack.
  to msgpackz - Convert Nu values into brotli-compressed MessagePack.
  to nuon - Converts table data into Nuon (Nushell Object Notation) text.
  to text - Converts data into simple text.
  to toml - Convert record into .toml text.
  to tsv - Convert table into .tsv text.
  to xml - Convert special record structure into .xml text.
  to yaml - Convert table into .yaml/.yml text.

Flags:
  -h, --help - Display the help message for this command

Input/output types:
  ╭───┬─────────┬────────╮
  │ # │  input  │ output │
  ├───┼─────────┼────────┤
  │ 0 │ nothing │ string │
  ╰───┴─────────┴────────╯


$ query
Show all the query commands

Usage:
  > query

Subcommands:
  query db - Query a database using SQL.
  query json - execute json query on json file (open --raw <file> | query json 'query string')
  query web - execute selector query on html/web
  query webpage-info - uses the webpage crate to extract info from html: title, description, language, links, RSS feeds, Opengraph, Schema.org, and more
  query xml - execute xpath query on xml

Flags:
  -h, --help - Display the help message for this command
```
