### ISSUE TITLE
`drop column` when given a record always produces an empty record instead of either erroring or deleting a column

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6846]
### Describe the bug

As I understand it, records are "1-row data structures", which means every key is a column and every value is an element in that column. However, with that understanding, `drop column` doesn't work with it. It always returns a `{record 0 items}` instead of either erroring or dropping a column (a key).

### How to reproduce

```
〉open package.json
╭─────────────────┬──────────────────────────────────╮
│ name            │ nushell.github.io                │
│ version         │ 0.0.0                            │
│ description     │ The Nushell website (nushell.sh) │
│ repository      │ github:nushell/nushell.github.io │
│ type            │ module                           │
│ scripts         │ {record 4 fields}                │
│ license         │ MIT                              │
│ devDependencies │ {record 11 fields}               │
│ lint-staged     │ {record 1 field}                 │
│ dependencies    │ {record 3 fields}                │
╰─────────────────┴──────────────────────────────────╯
〉open package.json | drop column 1 | describe
record<>
〉open package.json | drop column 1

〉
```

### Expected behavior

I actually think this would make sense if it errored, because records are *technically* not ordered structures ("technically" in the sense that most programming languages, including JavaScript, do have a specification-defined algorithm for what happens when you iterate over a record's items) so referring to record columns by number is arguably invalid, and you should use `reject` instead. However, I can see an argument for permitting it anyway.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by sholderbach** [comment]
Closed by #10903
