### ISSUE TITLE
Highlighting of `find` results in `table` is inconsistent

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6848]
### Describe the bug

I don't really understand how `find`'s highlighting works with `table`, and I've noticed some obvious cases where the value is not highlighted in red, even though other times it is. I imagine I could squint at some `ast` output to get some answers, but anyway……

### How to reproduce

Here's an example:
![image](https://user-images.githubusercontent.com/83939/197189516-3e6efa76-894a-4012-b369-386a17ebf5e9.png)

### Expected behavior

24 should be highlighted red in both outputted tables.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
Just to document what's going on.

Example 1 that doesn't work, is going through the `PipelineData::Value(_,_)` match block and matches on `Value::Record`.
Example 2 that works with transpose, is going through the `PipelineData::ListStream()` match block and matches on `Value::Record`.

The `PipelineData::Value()` match block doesn't have any match highlighting. There are other parts of find that also do not have syntax highlighting.

Someone could probably extract the example 2 highlighting parts into a function and call that function from both match cases, that would probably fix this use case.

**Comment by dmatos2012** [comment]
Hi, 
Thanks for the detailed info on what is possibly the solution already. Im new to rust and also to this repo, but would like to tackle this. Hope its ok :),

**Comment by fdncred** [comment]
@dmatos2012 go for it. i'll assign it to you. thanks for helping out.

**Comment by weirdan** [comment]
@fdncred this appears to have been fixed already (in #6997)
