### ISSUE TITLE
`table -e`: A subvalue, {record 5 fields}, is displayed as completely truncated in `-e` view

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6851]
### Describe the bug

The new `table -e` view has a rather strange phenomenon where, if a record can't fully fit into view, all of the record's columns are truncated to nothing rather than showing them.

### How to reproduce

![image](https://user-images.githubusercontent.com/83939/197195833-927bb2c4-ac56-452f-a0b3-dbe83c1568a8.png)

### Expected behavior
Here's what `scope` looks like, by the way:
```
〉$nu | get scope
╭──────────────┬───────────────────╮
│ vars         │ [table 4 rows]    │
│ commands     │ [table 482 rows]  │
│ aliases      │ [table 66 rows]   │
│ modules      │ [list 2 items]    │
│ engine_state │ {record 7 fields} │
╰──────────────┴───────────────────╯
```
I understand that this is rather a dense structure, but I would at least expect that the scope table's relatively short column names are displayed, and then their *values* are truncated to nothing, rather than just hiding the entire table.

Actually, I don't suppose there's any code for truncating _just_ the values of a column yet, is there…?

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by zhiburt** [comment]
So the idea to do something like it?

![image](https://user-images.githubusercontent.com/20165848/197545750-0bc1e3e7-ee41-41a9-be51-eb1629855790.png)

What you see on a screenshot applies only for `Record`.
Meaning.

We still get this

![image](https://user-images.githubusercontent.com/20165848/197546155-bf6ed13f-0f9d-4581-948d-01bb197e8288.png)

Is there any idea how to do it better?

(it has these columns)

**Comment by webbedspace** [comment]
Isn't there already a method of truncating tables by row?
```
〉ls  | into lazy | collect
╭─────┬─────────────────────┬──────┬────────┬────────────╮
│   # │        name         │ type │  size  │  modified  │
├─────┼─────────────────────┼──────┼────────┼────────────┤
│   0 │ .cargo              │ dir  │      0 │ 5 days ago │
│   1 │ .git                │ dir  │   4096 │ a day ago  │
│   2 │ .github             │ dir  │   4096 │ 5 days ago │
│   3 │ .gitignore          │ file │    437 │ 5 days ago │
│   4 │ CODE_OF_CONDUCT.md  │ file │   3444 │ 5 days ago │
│   5 │ CONTRIBUTING.md     │ file │   1819 │ 5 days ago │
│   6 │ Cargo.lock          │ file │ 143938 │ a day ago  │
│   7 │ Cargo.toml          │ file │   4164 │ 4 days ago │
│   8 │ LICENSE             │ file │   1094 │ 5 days ago │
│   9 │ README.md           │ file │  13070 │ 5 days ago │
│ ... │ ...                 │ ...  │ ...    │ ...        │
│  21 │ install-all.sh      │ file │    848 │ 5 days ago │
│  22 │ pkg_mgrs            │ dir  │      0 │ 5 days ago │
│  23 │ register-plugins.nu │ file │   1003 │ 5 days ago │
│  24 │ rust-toolchain.toml │ file │   1106 │ 5 days ago │
│  25 │ samples             │ dir  │      0 │ 5 days ago │
│  26 │ src                 │ dir  │   4096 │ a day ago  │
│  27 │ target              │ dir  │   4096 │ 4 days ago │
│  28 │ tests               │ dir  │   4096 │ 5 days ago │
│  29 │ uninstall-all.sh    │ file │    374 │ 5 days ago │
│  30 │ wix                 │ dir  │      0 │ 5 days ago │
╰─────┴─────────────────────┴──────┴────────┴────────────╯
```
This truncates the table between 10 and 20. I imagine the same sort of thing could be done to the `temp` table in that example.

**Comment by fdncred** [comment]
I've always been more concerned with column truncation with `...` than with row truncations like 0-9, then 21-30 like dataframes do. At least with rows, you can scroll up or redirect to a file or pipe through less, but when there's the `...` on columns, there's not much you can do about it. I really wish we had horizontal paging built into our table like `csvlens` does.

**Comment by zhiburt** [comment]
>  I imagine the same sort of thing could be done to the temp table in that example.

Not exactly,
As there's space only for columns.
The question how to show that there a number of records which exists.

>  I really wish we had horizontal paging built into our table like csvlens does.

I've checked `csvlens` and it does scrolling correct?
I am not sure whether it's applicable here.

Ultimately if there's a little space they do the same.

![image](https://user-images.githubusercontent.com/20165848/197615675-1250c484-0942-4c46-96aa-f7958a244863.png)

**Comment by fdncred** [comment]
> I've checked csvlens and it does scrolling correct?

Yes, there's a key binding like right and left arrow to scroll, although i don't remember if it's left and right arrow exactly. So, it could be applicable because we could have nothing ever really get truncated. You'd just scroll right and see it.

**Comment by webbedspace** [comment]
What about something along the lines of this?
![image](https://user-images.githubusercontent.com/83939/197789974-2dd64147-1236-4563-abfa-64feb09ae0b1.png)
Though, I don't quite understand (if I get your question correctly) why it's not possible to orient it the proper way up:
![image](https://user-images.githubusercontent.com/83939/197790192-e280fa35-f923-4b1a-8c9b-77f82ce7358e.png)

**Comment by zhiburt** [comment]
> Though, I don't quite understand (if I get your question correctly) why it's not possible to orient it the proper way up:

That's what we do by if there's enough space.
If there's only a little space likely it will be truncated to this.
![image](https://user-images.githubusercontent.com/20165848/197827570-e61d924b-247f-462a-b0dd-4e84f9520f26.png)

Correct me If I am wrong but this issue is addressing this case where we have a little space.
You're saying we could show at least something.

This is we can do for 1 type of data.

<img width="229" alt="image" src="https://user-images.githubusercontent.com/20165848/197828120-11cda881-6467-4435-8e84-2d7584bd8459.png">

But we can't represent a list of data like it.
And what I am saying is how better do it or ignore it.

> Or maybe:
> ![image](https://user-images.githubusercontent.com/83939/197790561-71b54d7a-9636-4c07-8648-d0321ed0315c.png)

This is possible to do but I don't know

**Comment by fdncred** [comment]
I like this change and think we should move forward with it

![](https://user-images.githubusercontent.com/20165848/197828120-11cda881-6467-4435-8e84-2d7584bd8459.png)

My personal opinion is not to use the data frame truncation technique, nor do I like the range truncation like `0..21`. However, I would be ok with it if we could click to expand it on demand, but of course we can't. That's something for a nana like UI to do.

**Comment by zhiburt** [comment]
> However, I would be ok with it if we could click to expand it on demand, but of course we can't. That's something for a nana like UI to do.

Well we can do it like `csvlens` does.
The question only question is whether it's worth it.

And whether it must be exactly 'like' `csvlens` (from what I've seen it doesn't actually build 'tables' it leverages crossterm/tui to make an output be a 'table').
Or something like a combination of current table output and dynamic moves.

So we would have something like it but be spread to width.
And have a different column truncate logic.
To mimic (`csvlens`)

![image](https://user-images.githubusercontent.com/20165848/199125467-aec7b364-f623-4698-96f3-80b3fd9011f5.png)

**Comment by fdncred** [comment]
We've long talked about having a horizontal pager and personally I'd like it to be more like `csvlens` where we have columns and rows in a tui, vs line drawn columns. 

Another tui with paging and filtering is the cross platform powershell module called out-consolegridview or ocgv for short. ocgv is cool because it also allows you do filtering within the tui as well as selection. 
<img width="1056" alt="Screenshot 2022-10-29 at 11 03 06 AM" src="https://user-images.githubusercontent.com/343840/199137227-53ecd8b0-81af-470f-8b57-348fa075af8f.png">

I'm just using ocgv to show a different tui. we'd need to stay in the rust tui/csvlens world I think.

**Comment by zhiburt** [comment]
Sounds cool.

An idea came to me the other day why there's no `less`, `more` for tables?

*or it's already was created?

**Comment by fdncred** [comment]
> An idea came to me the other day why there's no less, more for tables?

You can do `ls | table | less -FRX` and this way it retains the coloring. Or you can do `ls | less` and it strips the color. Paging with less works both ways. Is that what you mean?

**Comment by zhiburt** [comment]
> > An idea came to me the other day why there's no less, more for tables?
> 
> You can do `ls | table | less -FRX` and this way it retains the coloring. Or you can do `ls | less` and it strips the color. Paging with less works both ways. Is that what you mean?

More like this #6984
