### ISSUE TITLE
Piping records into `from nuon` or `from json` produces bizarre errors

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6852]
### Describe the bug

If you create a record (such as by opening a .nuon file), then accidentally pipe it into `from nuon`, a bizarre nonsensical error occurs. The same applies to `from json`.

### How to reproduce

```
〉{a:1 b:2} | from nuon
Error:
  × error when loading nuon text
   ╭─[entry #276:1:1]
 1 │ {a:1 b:2} | from nuon
   ·             ────┬────
   ·                 ╰── could not load nuon text
   ╰────

Error:
  × Error when loading
   ╭────
 1 │ {a: 1b: 2}
   · ─────┬────
   ·      ╰── blocks not supported in nuon
   ╰────

〉{a:1 b:2} | from json
Error:
  × Error while parsing JSON text
   ╭─[entry #277:1:1]
 1 │ {a:1 b:2} | from json
   ·             ────┬────
   ·                 ╰── error parsing JSON text
   ╰────

Error:
  × Error while parsing JSON text
   ╭────
 1 │ {a: 1b: 2}
   ╰────
〉
```

### Expected behavior

I expect `from nuon` and `from json` to produce type errors due to expecting strings (or raw stream input), not… whatever that was.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by sholderbach** [comment]
Sorry I was referencing the wrong issue with the PR above. 

Fixing this is probably not fully trivial as most of the `from ...` commands invoke `PipelineData::collect_string()` that tries to coerce the whole pipeline to text. And that succeeds in most cases but probably doesn't result in what you expect when trying to parse.

**Comment by sholderbach** [comment]
Should be fixed now:

```
/home/stefan: {a:1 b:2} | from nuon
Error: nu::shell::type_mismatch (link)

  × Type mismatch
   ╭─[entry #1:1:1]
 1 │ {a:1 b:2} | from nuon
   · ────┬────
   ·     ╰── needs string
   ╰────

/home/stefan: {a:1 b:2} | from json
Error: nu::shell::type_mismatch (link)

  × Type mismatch
   ╭─[entry #2:1:1]
 1 │ {a:1 b:2} | from json
   · ────┬────
   ·     ╰── needs string
   ╰────

```

**Comment by webbedspace** [comment]
Shouldn't that be a PipelineMismatch? TypeMismatch is for arguments. There was this whole PR recently about the distinction between them.

**Comment by sholderbach** [comment]
I dumped it in my `0.73` stable terminal, so this doesn't fully reflect bleading edge after your cleanup in #7217 but the same for main.

**Comment by sholderbach** [comment]
> Shouldn't that be a PipelineMismatch? TypeMismatch is for arguments. There was this whole PR recently about the distinction between them.

@webbedspace It was a bit of tedious work to get there but https://github.com/nushell/nushell/pull/7637 should move that to `ShellError::PipelineMismatch`
