### ISSUE TITLE
`from url` doesn't seem to work well with absolute URLs

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6854]
### Describe the bug

I notice that `from url` doesn't seem to be very useful at the moment - not only does it only seem to handle search params, but it also can't tell the difference between the first search param's name and the start of the URL.

### How to reproduce

```
〉'https://www.smwcentral.net/?p=section&s=smwmusic&f[name]=vldc&f[author]=&f[tags]=&f[featured]=&f[description]=' | from url
╭───────────────────────────────┬──────────╮
│ https://www.smwcentral.net/?p │ section  │
│ s                             │ smwmusic │
│ f[name]                       │ vldc     │
│ f[author]                     │          │
│ f[tags]                       │          │
│ f[featured]                   │          │
│ f[description]                │          │
╰───────────────────────────────┴──────────╯
```

### Expected behavior

Let's compare this to an interface that's already in production:

![image](https://user-images.githubusercontent.com/83939/197226498-b4379fd0-61b6-42bb-abbf-a1211c67c4d7.png)

It would be nice if the other parts that the DOM's `URL()` recognises (host, href, pathname, etc.) were added to the final record, and searchterms moved to an inner record. However, the fact that this currently can't even properly distinguish the first search term's name feels like a bug to me.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
It looks to me like maybe `serde_urlencoded::from_str` is maybe only meant for parsing things other than the protocol and host. I guess that would mean that `from url` may be named wrong. Or maybe we need to use a different crate for parsing this information?

```rust
    let result = serde_urlencoded::from_str::<Vec<(String, String)>>(&concat_string);
```
This part seems to work right I think
```
'p=section&s=smwmusic&f[name]=vldc&f[author]=&f[tags]=&f[featured]=&f[description]=' | from url 
╭────────────────┬──────────╮
│ p              │ section  │
│ s              │ smwmusic │
│ f[name]        │ vldc     │
│ f[author]      │          │
│ f[tags]        │          │
│ f[featured]    │          │
│ f[description] │          │
╰────────────────┴──────────╯
```

We do have these other url commands - someone suggested recently that we should have a `url parse`.
```
'https://www.smwcentral.net/?p=section&s=smwmusic&f[name]=vldc&f[author]=&f[tags]=&f[featured]=&f[description]=' | url 
hostwww.smwcentral.net

'https://www.smwcentral.net/?p=section&s=smwmusic&f[name]=vldc&f[author]=&f[tags]=&f[featured]=&f[description]=' | url path
/

'https://www.smwcentral.net/?p=section&s=smwmusic&f[name]=vldc&f[author]=&f[tags]=&f[featured]=&f[description]=' | url query 
p=section&s=smwmusic&f[name]=vldc&f[author]=&f[tags]=&f[featured]=&f[description]=

'https://www.smwcentral.net/?p=section&s=smwmusic&f[name]=vldc&f[author]=&f[tags]=&f[featured]=&f[description]=' | url scheme
https
```

**Comment by webbedspace** [comment]
This is a bit off-topic, but why does `url query` return a string, such that it needs `from url` to even be useful, anyway?

**Comment by fdncred** [comment]
I'm not sure. I don't even remember who the author was of that command.

**Comment by raccmonteiro** [comment]
what exactly is expected in this issue? I did not exactly understood. Implement an `url parse` command?

Should have the following output?
```
'https://www.smwcentral.net/?p=section&s=smwmusic&f[name]=vldc&f[author]=&f[tags]=&f[featured]=&f[description]=' | url parse
╭────────────────────┬──────────╮
│ https              │          │
│ www.smwcentral.net │          │
│ /                  │          │
│ p                  │ section  │
│ s                  │ smwmusic │
│ f[name]            │ vldc     │
│ f[author]          │          │
│ f[tags]            │          │
│ f[featured]        │          │
│ f[description]     │          │
╰────────────────────┴──────────╯
```

**Comment by fdncred** [comment]
I think the point is to tie into the other `url` commands and parse a url with the host, path, query, scheme, and any other parts. I kind of see it either being a record that has this information and you can query it with nushell like `some url | url parse | get host`

scheme = https
host = www.smwcentral.net
path = /
query = p=section&s=smwmusic&f[name]=vldc&f[author]=&f[tags]=&f[featured]=&f[description]=
parse = this is all the above plus the parsed query string that `from url` delivers, maybe this is an inner record that could be iterated through.

maybe something like this, which is a record list with an embedded table for the parse item. I just faked this but it's possible to create embedded tables. but i'm just throwing out ideas here. i'm open to whatever looks good. the key is to have all the information so that you can query it all back out if you need to.
```
╭────────┬────────────────────────────────────────────────────────────────────────────────────╮
│ scheme │ https                                                                              │
│ host   │ www.smwcentral.net                                                                 │
│ path   │ /                                                                                  │
│ query  │ p=section&s=smwmusic&f[name]=vldc&f[author]=&f[tags]=&f[featured]=&f[description]= │
│ parse  │╭───┬────────────────┬──────────╮                                                   │
│        ││ # │      key       │  value   │                                                   │
│        │├───┼────────────────┼──────────┤                                                   │
│        ││ 0 │ p              │ section  │                                                   │
│        ││ 1 │ s              │ smwmusic │                                                   │
│        ││ 2 │ f[name]        │ vldc     │                                                   │
│        ││ 3 │ f[author]      │          │                                                   │
│        ││ 4 │ f[tags]        │          │                                                   │
│        ││ 5 │ f[featured]    │          │                                                   │
│        ││ 6 │ f[description] │          │                                                   │
│        │├───┼────────────────┼──────────┤                                                   │
│        ││ # │      key       │  value   │                                                   │
│        │╰───┴────────────────┴──────────╯                                                   │
╰────────┴────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by webbedspace** [comment]
That's basically it, except A) the `parse` inner table should just be an inner record (and there should be commands that can iterate over record key-value pairs 🐧) and B) instead of `parse`, `params` would be a better name (related to DOM URL `searchParams`).

**Comment by raccmonteiro** [comment]
Thanks
I will try to do it

**Comment by raccmonteiro** [comment]
I am working on `url parse` and `record` command.
For `url parse` currently I have the following behavior, like @webbedspace suggested.
![image](https://user-images.githubusercontent.com/3062698/201475233-0c026800-34e5-447f-998d-71d878426a21.png)

With this we can use `get params` to view the params Record:
![image](https://user-images.githubusercontent.com/3062698/201475288-8b853b88-7fa2-498e-b1d9-c944c13e1fdb.png)

 Then we can use the `record` command to get the key value pair by index (like @fdncred suggested):
![image](https://user-images.githubusercontent.com/3062698/201475380-3e5637d9-3a38-4edb-9a68-028a8d787f29.png)

What do you think? Can I continue with this approach? Any change?

**Comment by fdncred** [comment]
I think this looks good, except I'm not sure what the `record` command is?

**Comment by webbedspace** [comment]
The record command doesn't exist because I haven't proposed its addition (as an issue) yet. Hence why there "should be" (as in "ought to be") but there isn't.

**Comment by raccmonteiro** [comment]
@webbedspace so do you think there's no need for the `record` command? Should I abandon it?
What about the `url parse` it's ok like this?

**Comment by webbedspace** [comment]
Yes, forget `record` for now, as it is a bit out-of-scope (and not strictly necessary given that at the present, `transpose` can "turn a record iterable"). The current `url parse` output seems fine.

**Comment by raccmonteiro** [comment]
I have one question, what should be the output when the url is invalid? Should be an error or an empty String? I think it's best to display and error, but `url host`, `url scheme`, and others `url` commands display an empty String:
![image](https://user-images.githubusercontent.com/3062698/201522195-0bdf454a-9391-4eea-8f99-cb91496baa04.png)

Should we open an issue to change these `url` commands to display an error?


I also added an entry for port
![image](https://user-images.githubusercontent.com/3062698/201522295-320110ce-2f45-4bf2-85b0-97e0c1596977.png)

**Comment by fdncred** [comment]
I think error is the proper return for your `"" | blah` examples.

**Comment by dandavison** [comment]
Design questions related to https://github.com/nushell/nushell/pull/7124:

(These are neutral questions; please don't read any opinion or quesiton

- Should the name be `from url` or `url parse`?

- Do you all agree that we should drop `url host`, `url query`, `url path` once we have a fully functioning url parse command?

- Should we group all commands that parse text into structured data under a single prefix. Probably what I have in mind is changing `from xxx` to `parse xxx` and adding `parse url` and `parse path` and `parse tabular` (currently `detect columns`) in there.

**Comment by rgwood** [comment]
> Should the name be `from url` or `url parse`?

I prefer `url parse`

> Do you all agree that we should drop...

Yes

> Should we group all commands that parse text into structured data under a single prefix...

Hmm. I lean toward no. IMO there is a conceptual difference between what `url parse` does and `from json` does. `from` feels more appropriate for general-purpose
