### ISSUE TITLE
Add `table --nocolor` argument

### ISSUE THREAD

**Issue by zhiburt** [nushell/nushell#6855]
### Related problem

Nushell already has ` use_ansi_coloring` in a config.

But it may be not convenient to reset the config when running single commands.

PS: 
I actually not sure if it brings anything to a table.
    - If it is then I guess the issue can be marked `Good First Issue`.
    - If it's not it can be closed (And I am sorry for bothering).

**Comment by webbedspace** [comment]
Can't you just pipe it through [`ansi strip`](https://www.nushell.sh/book/commands/ansi_strip.html)?

**Comment by zhiburt** [comment]
> Can't you just pipe it through [`ansi strip`](https://www.nushell.sh/book/commands/ansi_strip.html)?
> 
> `ls | table | ansi strip`

I guess you can.
But it will be certainly slower. (probably there wont be big difference)

Cause we build table with colors first and then strip them.
Where we could just not use colors.

Probably you're right I don't know.

**Comment by zhiburt** [comment]
PS: I am pretty sure currently we don't recognize the config option when building table.

(it's necessary to add 1 if statement when choosing theme)

**Comment by Euphrasiologist** [comment]
Maybe I can take this one? Unless it's not so useful? Want to dip my toes in the nushell codebase more!

**Comment by zhiburt** [comment]
Sure;

Give you a hint.
Take a look at `/crates/nu-command/src/viewers`

> Unless it's not so useful?

Though I am not sure here,
But it is certainly not implemented.

**Comment by zhiburt** [comment]
I think it's all right; cause there's a configuration option for it.

**Comment by Euphrasiologist** [comment]
Go for it, sorry I've been so busy and forgot!

**Comment by ar-garner** [comment]
Is anyone actively working on this anymore?
I gave it a go and have a PR ready if not.
#14377

**Comment by WindSoilder** [comment]
I think `table | ansi strip` is good enough, and based on my simple benchmark, it seems that `table | ansi strip` have better performance than `table --nocolor` in #14377.
So I'd like to close the issue.

Feel free to reopen it if you think `--nocolor` is better in some other ways :-)
