### ISSUE TITLE
Networks drives and subst'd drives on windows are replaced by canonical paths

### ISSUE THREAD

**Issue by larsch** [nushell/nushell#686]
There are use cases where drive paths on Windows being canonical is not the most ergonomic. Especially since Windows lets drive letters be aliases for other things.

Subst'd drives get replaced by the original path:

```C:\> subst
D:\: => C:\user
C:\>cd d:\
C:\user>
```

Here I expected to be in a `D:\> _` prompt.

Network drives get expanded to their UNC path:

```C:\> net use t: \\host\share
C:\> cd t:\
\\.\UNC\host\share> _
```

Here I expected to be in a `T:\> _` prompt.

This is especially problematic because cmd.exe does not support UNC paths and will not run commands from them, complaining:

```
\\.\UNC\host\share> dir
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
(Proceeds to list %SystemRoot% contents)
```

**Comment by Dimagog** [comment]
subst'ed drives still behave the same as described in the bug.
