### ISSUE TITLE
`help` does not show difference between overloaded commands

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#6866]
### Related problem

When a command `x` is overloaded, the output of `help x` is very long and not very helpful in explaining the difference between different command versions. For example, `help select`:

```
〉help select
Selects columns from lazyframe

Usage:
  > select ...(select expressions)

Flags:
  -h, --help - Display this help message

Parameters:
  ...select expressions <Any>: Expression(s) that define the column selection

Examples:
  Select a column from the dataframe
  > [[a b]; [6 2] [4 2] [2 2]] | into df | select a

======================

Down-select table to only these columns.

Search terms: pick, choose, get

Usage:
  > select {flags} ...(rest)

Flags:
  -h, --help - Display this help message
  -i, --ignore-errors - when a column has empty cells, instead of erroring out, replace them with nothing

Parameters:
  ...rest <CellPath>: the columns to select from the table

Examples:
  Select just the name column
  > ls | select name

  Select the name and size columns
  > ls | select name size

======================

Creates a select statement for a DB

Search terms: database

Usage:
  > select ...(select)

Flags:
  -h, --help - Display this help message

Parameters:
  ...select <Any>: Select expression(s) on the table

Examples:
  selects a column from a database
  > open db.sqlite | into db | select a | describe

  selects columns from a database using alias
  > open db.sqlite
    | into db
    | select (field a | as new_a) b c
    | from table table_1
    | describe
```

### Describe the solution you'd like

I'm not sure what the exact solution should be. Some UX problems with the status quo:

- it's very long, there's a lot to read
- we don't explicitly show the mapping between input types and commands
- we're not conveying any info re: which overload is most commonly used (arguably the one that takes a regular table)
- this applies to a lot of fundamental Nu commands (`where`, `describe`, `select`, `get`); it's become harder for Nu beginners to learn the basics using `help`

**Comment by dandavison** [comment]
Related: https://github.com/nushell/nushell/issues/6754

**Comment by rgwood** [comment]
This is much less of an issue now that we're not shipping dataframes by default and the `sqlparser` database commands have been dropped. The default Nu install no longer includes any overloaded commands, I think.

**Comment by fdncred** [comment]
Should close this now that dataframe commands are renamed?

**Comment by sholderbach** [comment]
Closed by the removal of the overload stuff
