### ISSUE TITLE
Syntax highlighting of 0-arity block is buggy

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6872]
### Describe the bug

When various block-taking commands, such as, `collect` are given a block with no argument (such as `{ $in }`), then the left brace is coloured wrongly.

### How to reproduce

![image](https://user-images.githubusercontent.com/83939/197404349-19194472-1415-43b4-9bae-b962744da5e2.png)

### Expected behavior

I expect the braces to be the same colours.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by sholderbach** [comment]
This appears to be fixed
