### ISSUE TITLE
Bad error for using `| get 0` on a record

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6874]
### Describe the bug

I'm doing some research into row and column manipulation commands, and realised that, since `get 0` selects by row, and records are 1-row data structures, then `get 0` should either return the record, or error.

Unfortunately, the error given seems to be entirely wrong.

### How to reproduce

```
〉{a:1 b:2} | get 0
Error: nu::shell::incompatible_path_access (link)

  × Data cannot be accessed with a cell path
   ╭─[entry #90:1:1]
 1 │ {a:1 b:2} | get 0
   ·                 ┬
   ·                 ╰── record<a: int, b: int> doesn't support cell paths
   ╰────
```

### Expected behavior

As you know, records DO support cell paths - just column paths, not row paths. So, the error message should reflect this.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by rgwood** [comment]
Should be pretty easy to fix. Any suggestions for wording?

![image](https://user-images.githubusercontent.com/26268125/197430022-04becc40-73cc-4443-b155-9a91c121fbe7.png)

**Comment by webbedspace** [comment]
Instead of "integer", maybe say "row index" to specify that `get` with integers gets rows, not columns.

Also, maybe add a special case for something like `{'0': 1} | get 0`, where the string form of the integer exists as a column name, saying something like "To get column names, provide a string to `get`."

**Comment by rgwood** [comment]
![image](https://user-images.githubusercontent.com/26268125/197652505-d330741a-417b-4543-8908-59b7c4309ff2.png)

The special case idea is good, maybe another time.
