### ISSUE TITLE
Tables *cannot* have a column called `index` ??

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6875]
### Describe the bug

One of the examples in `move`'s help is this:
>Move a column before the first column
> `[[name value index]; [foo a 1] [bar b 2] [baz c 3]] | move index --before name`

However, *this example does not work* - the `index` column is not moved, because the `index` column is not added to the table at all!

### How to reproduce

```
〉[[name value index]; [foo a 1] [bar b 2] [baz c 3]] | move index --before name
╭───┬──────┬───────╮
│ # │ name │ value │
├───┼──────┼───────┤
│ 1 │ foo  │ a     │
│ 2 │ bar  │ b     │
│ 3 │ baz  │ c     │
╰───┴──────┴───────╯
〉[[name value index]; [foo a 1] [bar b 2] [baz c 3]]
╭───┬──────┬───────╮
│ # │ name │ value │
├───┼──────┼───────┤
│ 1 │ foo  │ a     │
│ 2 │ bar  │ b     │
│ 3 │ baz  │ c     │
╰───┴──────┴───────╯
〉[[name value index2]; [foo a 1] [bar b 2] [baz c 3]]
╭───┬──────┬───────┬────────╮
│ # │ name │ value │ index2 │
├───┼──────┼───────┼────────┤
│ 0 │ foo  │ a     │      1 │
│ 1 │ bar  │ b     │      2 │
│ 2 │ baz  │ c     │      3 │
╰───┴──────┴───────┴────────╯
〉{index:1 a:2}
╭───────┬───╮
│ index │ 1 │
│ a     │ 2 │
╰───────┴───╯
〉[{index:1 a:2}]
╭───┬───╮
│ # │ a │
├───┼───┤
│ 1 │ 2 │
╰───┴───╯
────────┴───╯
〉[{index:'Mary had a little lamb, little lamb, little lamb' a:2}]
╭──────────────────────────────────────────────────┬───╮
│                                                # │ a │
├──────────────────────────────────────────────────┼───┤
│ Mary had a little lamb, little lamb, little lamb │ 2 │
╰──────────────────────────────────────────────────┴───╯
〉[{index:[1, 2, 3] a:2}]
╭───────┬───╮
│     # │ a │
├───────┼───┤
│ [123] │ 2 │
╰───────┴───╯
```

### Expected behavior

As you can see, the `move` example has the same output as its input. Also, changing the column name to `index2` makes the column appear. Also, records *can* have `index` column names, but lose them as soon as they are promoted to tables (by wrapping in a list). Since an entire command's example no longer works, I assume this is a bug.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
At least part of this is on purpose/by design. That part is that if you have a column named `index` it gets used as the index column `#`. This way you could have something like this. It's probably not well documented.
```
> [[col1 col2 index]; [a b index-1] [c d index-2] [e f index-3]] 
╭─────────┬──────┬──────╮
│       # │ col1 │ col2 │
├─────────┼──────┼──────┤
│ index-1 │ a    │ b    │
│ index-2 │ c    │ d    │
│ index-3 │ e    │ f    │
├─────────┼──────┼──────┤
│       # │ col1 │ col2 │
╰─────────┴──────┴──────╯
```

**Comment by webbedspace** [comment]
Current research:
```
〉[[a b index]; [1 1 0] [3 3 1] [7 8 2]] | to json
[
  {
    "a": 1,
    "b": 1,
    "index": 0
  },
  {
    "a": 3,
    "b": 3,
    "index": 1
  },
  {
    "a": 7,
    "b": 8,
    "index": 2
  }
]
〉[[a b index]; [1 1 0] [3 3 1] [7 8 2]] | roll left | to json
[
  {
    "b": 1,
    "index": 0,
    "a": 1
  },
  {
    "b": 3,
    "index": 1,
    "a": 3
  },
  {
    "b": 8,
    "index": 2,
    "a": 7
  }
]
```
What this says to me is that the "index" column's "true" position is still changed with `roll`, and that this is entirely a special case in `table` - i.e. a display illusion. In that event, I'm closing this because the premise is wrong, but I might make another issue about disabling this "feature" in `table`.
