### ISSUE TITLE
"from csv" does not work on non .txt files (piped from open command)

### ISSUE THREAD

**Issue by jerry-ne** [nushell/nushell#6876]
### Describe the bug

`open csv.csv | from csv --separator ';'` does not work on .csv files, only .txt works.

### How to reproduce

1. simply csv file with .csv file type extension
2. type command: `open csv.csv | from csv --separator ';'`

### Expected behavior

open .csv or another plaintext files piped from open command

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:52:28 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

Ubuntu MATE 22.04.1 LTS x64

**Comment by sholderbach** [comment]
When running `open file.csv` it tries to parse the file with the default options of `from csv`, to avoid that you can run `open --raw file.csv | from csv <flags>`.

**Comment by webbedspace** [comment]
I think the real bug here is that running `from csv` on a non-text pipe gives *literally no error whatsoever*.

**Comment by jerry-ne** [comment]
Thank you guys.
@sholderbach : `--raw` works fine.
Is it possible to expand help section? `help from csv` does not mentions this. Just "parse text" I think it is not clear for begginer. Maybe one example with `--raw` will be better here.

**Comment by sholderbach** [comment]
Yeah that is a good call @jerry-ne 

@webbedspace I was looking into `from csv` for #6877 and felt that it was unclear for me how errors or potential problems are handled there. Might be a good call to look into that.

**Comment by sholderbach** [comment]
Closing as we have now more actionable parse errrors.
