### ISSUE TITLE
Treat the first paragraph of command documentation as summary

### ISSUE THREAD

**Issue by Kixunil** [nushell/nushell#6878]
### Related problem

I have more involved subcommands that I want to document in the style similar to rustdoc:

```
# Short summary of what the subcommand does.
#
# Detailed description of the command.
export def foo [] {
    # ...
}
```

This currently causes two annoyances:

* `parent_command -h` prints out the full description of each command not only causing noise but it's also not properly indented so it's not obvious where the next subcommand ends.
* Tab completion on `parent_command <Tab>` prints paragraphs after the summary looking overwhelming.

### Describe the solution you'd like

The first paragraph should be treated as a summary and printed in the places where full description is not appropriate. The full description should still be printed on `command subcommand -h`. Maybe something like `command subcommand --help-summary` could be added later but not required now.

### Describe alternatives you've considered

* Keep it as is - annoying as described but at least informative.
* Only write the summary and write the full doc somewhere else (where?) - annoying not being able to look at doc from CLI

**Comment by sholderbach** [comment]
This seems to be resolved we parse the parts into the short and long description (currently still named `usage` and `extra_usage` until #13598)
