### ISSUE TITLE
`post` needs to be able to set content-type

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#688]
We need a way to pass in the content-type being posted as part of the `post` command.

Eg) being able to set it to "Content-Type: application/x-www-form-urlencoded"

**Comment by JonnyWalker81** [comment]
I took a quick look, if another named parameter is added `headers` to the command and the value for it would be a comma separated string of key, value pairs for the headers.  For example:

```post https://foo.com --headers "Content-Type=application/x-www-form-urlencoded,Content-Length=123"```

Does that seem reasonable?

**Comment by JonnyWalker81** [comment]
I created a PR for this issue, the PR adds support for a couple headers (e.g. Content-Type and Content-Length).

**Comment by jonathandturner** [comment]
Fixed in #729
