### ISSUE TITLE
Nu freezes while trying run `register ~/.cargo/bin/nu_plugin_from_bencode`

### ISSUE THREAD

**Issue by aj3n** [nushell/nushell#6881]
### Describe the bug

I want to install `nu_plugin_from_bencode` plugin for nushell. At first I followed the instruction from `nu_plugin_from_bencode`, running following command in nushell:
```sh
register --encoding=json ~/.cargo/bin/nu_plugin_from_bencode
```
But the command seemed to be outdated cause I got error from nushell:
```
Error: nu::parser::unknown_flag (link)

  × The `register` command doesn't have flag `encoding`.
   ╭─[entry #1:1:1]
 1 │ register --encoding=json ~/.cargo/bin/nu_plugin_from_bencode
   ·          ───────┬───────
   ·                 ╰── unknown flag
   ╰────
  help: use register --help for a list of flags
```
Later I tried to run previous command without `--encoding` flag , but the nushell froze just 1 charater before I finished the command in the title. If I paste the command into nushell, nushell will freeze immediately.

### How to reproduce

1. `cargo install nu_plugin_from_bencode`
2. start nushell, input `register ~/.cargo/bin/nu_plugin_from_bencode`

### Expected behavior

Anything but this😂

### Configuration

〉version | transpose key value | to md --pretty                                                                                                                                                                                               10/24/2022 05:59:05 PM
| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.70.0                                      |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | macos-aarch64                               |
| build_target       | aarch64-apple-darwin                        |
| rust_version       | rustc 1.66.0-nightly (e7119a030 2022-09-22) |
| rust_channel       | nightly-aarch64-apple-darwin                |
| cargo_version      | cargo 1.66.0-nightly (73ba3f35e 2022-09-18) |
| pkg_version        | 0.70.0                                      |
| build_time         | 2022-10-21 18:41:20 +08:00                  |
| build_rust_channel | release                                     |
| features           | default, trash, which, zip                  |
| installed_plugins  |                                             |

**Comment by WindSoilder** [comment]
I think `nu_plugin_from_bencode` itself need to publish and release with a new nu relative dependencies.
![图片](https://user-images.githubusercontent.com/22256154/197505691-ea92ee79-900e-422b-95ee-fc9421273846.png)

Currently the dependency version will lead nu to freeze if you're using nushell 0.70

**Comment by fdncred** [comment]
It seems like there are 2 problems here.
1. nushell can't be responsible for every 3rd party plugin working, of course
2. but nushell also should not hang the terminal when ran on an invalid plugin

I'm wondering if `register` can be updated to fail with an error message for anything invalid? I'm not really sure if it's possible or not.

**Comment by aj3n** [comment]
> I think `nu_plugin_from_bencode` itself need to publish and release with a new nu relative dependencies. ![图片](https://user-images.githubusercontent.com/22256154/197505691-ea92ee79-900e-422b-95ee-fc9421273846.png)
> 
> Currently the dependency version will lead nu to freeze if you're using nushell 0.70

Thanks for replying. I've fixed the problem by installing corresponding nushell.
