### ISSUE TITLE
Error for using `from table` without `select` (and vice versa) is kind of bad

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6887]
### Describe the bug

I don't know how much you can do to improve this, but I'll mention it anyway: the errors for not making a "complete" SQL select using Nushell commands is kind of below the standards for most Nushell errors. In particular, it references an "offset" which has nothing to do with the inputted command (much).

### How to reproduce

```
〉open C:\places-archive.sqlite | into db | from table moz_places
Error:
  × Failed to query SQLite database
   ╭─[entry #108:1:1]
 1 │ open C:\places-archive.sqlite | into db | from table moz_places
   ·                                                    ─────┬────
   ·                                                         ╰── near "FROM": syntax error in SELECT  FROM moz_places at offset 8
   ╰────

```

### Expected behavior

Nushell should probably have a special error for this case (not providing both `from table` and `select` in a db command pipeline.)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by rgwood** [comment]
Thanks for the report. Think we can close this now that the `sqlparser` database commands are gone (RIP): https://github.com/nushell/nushell/pull/7040
