### ISSUE TITLE
Does `fill-na` actually work?

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6888]
### Describe the bug

`fill-na` has no help examples (?!), and moreover doesn't seem to have any referents in the codebase outside of its file, so I'm not sure how it's supposed to work. Nevertheless, based on what I know about `fill-null`, I'm positive that this behaviour below is a bug.

### How to reproduce

```
〉[1 2 3 NaN NaN null 4] | into df | fill-na 0
╭───┬─────╮
│ # │  0  │
├───┼─────┤
│ 0 │   1 │
│ 1 │   2 │
│ 2 │   3 │
│ 3 │ NaN │
│ 4 │ NaN │
│ 5 │     │
│ 6 │   4 │
╰───┴─────╯
〉[1 2 3 NaN NaN 4] | into lazy | fill-na 0 | collect
╭───┬─────╮
│ # │  0  │
├───┼─────┤
│ 0 │   1 │
│ 1 │   2 │
│ 2 │   3 │
│ 3 │ NaN │
│ 4 │ NaN │
│ 5 │   4 │
╰───┴─────╯
```

### Expected behavior

I expect the NaNs to be replaced with 0. On another note, shouldn't this command be named `fill-nan` ??

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by dmatos2012** [comment]
Hi, 
So recap, 
1. the actual output should look like this right?
```
〉[1 2 3 NaN NaN null 4] | into df | fill-na 0
╭───┬─────╮
│ # │  0  │
├───┼─────┤
│ 0 │   1 │
│ 1 │   2 │
│ 2 │   3 │
│ 3 │   0 │
│ 4 │   0 │
│ 5 │     │
│ 6 │   4 │
╰───┴─────╯
```
2. It should be instead `fill-nan` rather than `fill-na`? I also agree that makes more sense. If thats the case, it looks like something i can give a shot.

**Comment by webbedspace** [comment]
I'd like it if the person who actually originally implemented this command could be brought in to give a statement of intent, just to be sure.

**Comment by ricardoCMonteiro** [comment]
Hi,
I'm new with Rust, but I would like git it a try with this task if it's ok.
