### ISSUE TITLE
Fuzzy search in history not working correctly in Windows

### ISSUE THREAD

**Issue by pka** [nushell/nushell#689]
PR #672 is not work correctly in Windows.

@jonathandturner writes:

> As best as I can tell, it's ignoring that the input is being set to sync mode (possibly because crossterm is interacting with rustyline).

> long-term I think we may may want to have a framework that can drive both line editing on the prompt and interactive text-based UI with the user

> this way we can set the modes all in the same place, in the same way

> this is a non-trivial amount of work, but it's worth talking about if we want to make that time investment

**Comment by jonathandturner** [comment]
This appears to be related to https://github.com/TimonPost/crossterm/issues/250, as best I can tell.  I'm also going to tag this upstream, so we can come back to it later.

**Comment by andrasio** [comment]
#900
