### ISSUE TITLE
Should the `help` page for `echo` explain what it actually does?

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6891]
### Question

`echo`'s help currently opens like this:
```
Echo the arguments back to the user.

Unlike `print`, this command returns an actual value that will be passed to the next command of the pipeline.
```
In reality, though, this isn't what `echo` does, but is only how it is *often used*. In reality, `echo` does the following:
* Ignore the piped-in value
* If given 0 arguments, return `""`
* If given 1 argument, return it
* Otherwise, return a list of the arguments

This paints a picture of a rather different command that isn't exactly lined up with its name. But, the help documentation should state all of this, right?

**Comment by sholderbach** [comment]
Maybe `Send the argument(s) as a value down the pipe`. Yeah the current one sentence summary is actively misleading.
