### ISSUE TITLE
Change keybonding for hint complete

### ISSUE THREAD

**Issue by rakula4** [nushell/nushell#6899]
### Question

Currently the hint completion is done with the `right arrow` key. I want to change that to use `tab`. 

How does one set up this in config.nu file?

**Comment by fdncred** [comment]
if you look at `keybindings default` you will see that right is in an `until` with `historyhintcomplete`, `menuright` and `right`. you may be able to follow one of the other examples that uses `until` in the default_config.nu to try and figure this out.

**Comment by siph** [comment]
Looks like this works:
```nu
  keybindings: [
      {
          name: tab_history_completion
          modifier: none
          keycode: tab
          mode: [ emacs, vi_insert, vi_normal ]
          event: {
              until: [
                  { send: historyhintcomplete }
                  { send: menuright }
                  { send: right }
              ]
          }
      }
  ]
```

**Comment by RicardoRyn** [comment]
I use the `ctrl + j` to accept the hint. And if I want to use `ctrl + k` clear the hint, what should I do?
