### ISSUE TITLE
Add support for archive files (zip, 7z, tar,...) in `open` command

### ISSUE THREAD

**Issue by YuvalNahon2** [nushell/nushell#6901]
### Related problem

The open command doesn't support archive file formats.

### Describe the solution you'd like

The open command should support extracting archive files metadata into a table.
Perhaps even allow to get a specific file from the archive (in an uncompressed form).

**Comment by rgwood** [comment]
Cool idea!

I think we'd welcome this in a plugin but we're unlikely to implement it in the core commands (which we are currently trying to refine and slim down as we approach v1.0).
