### ISSUE TITLE
Show execution time for long running commands

### ISSUE THREAD

**Issue by SUPERCILEX** [nushell/nushell#6906]
### Describe the solution you'd like

My old shell would show command execution time in the prompt if the last command took longer than N seconds (I think N=5). This was useful-ish to know how long updates, not-rust compiles, etc took.

**Comment by nibon7** [comment]
I think you can customize the `PROMPT_COMMAND` environment variable, or use `starship` prompt which has `cmd_duration` by default.

```nu
let-env PROMPT_COMMAND = {
  let duration = ($env.CMD_DURATION_MS | into int) / 1000
  let base_prompt = $"(ansi green)($env.PWD)"
  if $duration >= 5 {
    $"($base_prompt)(ansi yellow) took ($duration)s"
  } else {
    $base_prompt
  }
}
```

**Comment by SUPERCILEX** [comment]
Neat, thanks!
