### ISSUE TITLE
Should documentation, defaults etc. use `null` instead of `$nothing`?

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6908]
### Question

I notice that `$nothing` is a variable whose value is the "nothing" value. However, it seems that a literal `null` also exists in the language that produces the same thing, which I assume was added so that the "Nuon is a superset of JSON" declaration could be true.

Do you think `null` is just better than `$nothing`, and should be used as the idiomatic "nothing value" in the default config and examples? I think there isn't much reason to prefer the other, although I might be missing something.

**Comment by webbedspace** [comment]
No one's replied, but one of the pull requests where I put this into action got accepted, so I guess that's a very tacit approval?

**Comment by rgwood** [comment]
Good question. I think I prefer `null` and I'm not aware of any reasons (other than backwards compatibility) to keep `$nothing` around.

**Comment by fdncred** [comment]
i'm fine with deprecating `$nothing` in favor of `null`

**Comment by rgwood** [comment]
Closing as it seems like this has been done (lmk if I'm wrong)
