### ISSUE TITLE
`color_config`: allow theme colours to be defined as blocks that return color codes on a per-datum basis

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6909]
### Related problem

I want to be able to customise the colouring of data on a datum-to-datum basis.

Use-cases:
* When presented with a huge table of booleans, it's hard to distinguish `false` from `true` at a glance, but providing a block that returns a different colour for `false` and `true` can make this easier.
* Changing the colour of `ls` filesizes that are above or below certain size thresholds (like 1GB) can make it easier to notice huge differences in size.

### Describe the solution you'd like

An example of what I mean:
```
let theme = {
  bool: {|c| if $c { dark_green } else { dark_red } },
  filesize: {|c| if $c >= 1GB { dark_red } else if $c == 0kb { white } else { dark_gray } }
}
```

### Additional context and details

I understand there might be perf issues with this (in the sense that every bool, filesize, int, etc. has to pass into the block every time it's drawn) but I don't believe they would be that huge a deal in ordinary cases.

**Comment by webbedspace** [comment]
@fdncred Here's my detailed plan for this feature.

###config.nu and config.rs

The record given to `color_config`  current looks like this:
```
attribute: string | { fg?:string, bg?:string, attr: n }
```
Both of these are pumped into `lookup_ansi_color_style()` to become a `nu_ansi_term::Style`. This is put into a `HashMap<String, nu_ansi_term::Style>`, which is passed around table.rs a lot under the name `color_hm`.

My proposal is to change this signature to this:
```
attribute: string | { fg?:string, bg?:string, attr: n } | closure (any -> string | { fg?:string, bg?:string, attr: n })
```
Notice that this is **entirely backwards-compatible**. Unlike the others, the closure is not pumped into `lookup_ansi_color_style()`, and the `color_hm` map becomes something like `HashMap<String, Either<nu_ansi_term::Style, Value::Closure>>` (or possibly its own named type).

###table.rs
The nu_ansi_term::Style is ultimately used in `make_styled_string()`.
`make_styled_string()` looks like this:
```
fn make_styled_string(
    text: String,
    text_type: &str,
    col: usize,
    with_index: bool,
    color_hm: &HashMap<String, nu_ansi_term::Style>,
    float_precision: usize,
)
```
`text_type` are keys corresponding to the `color_config` record (and also the `color_hm` map). `text` is the final rendering of the data value, usually the result of `into_abbreviated_string()`. I also propose that another argument is added, the raw Value.
If `make_styled_string` discovers `color_hm` contains a closure hashed at the `text_type`, then it will `eval_block()` the closure, passing in just the raw Value, and then shoves the result of that execution into `lookup_ansi_color_style()`. The output of that then becomes the color to use with `text`.

I understand that the closure *could* output `ansi` command output. But I'd prefer it if it output the same types as in the rest of the `color_config` record.

###Errors...?
As for errors… well, config values reporting errors is already kind of threadbare at the moment (config.rs only has handfuls of sad-looking `eprintln!()`s to call upon when it has a value error), and I don't have a good story for this either - I suppose errors result in another `eprintln!()` being called. Although, errors in `color_config` today are already not reported at all, so this proposal isn't regressing in that area, really.

###Perf
Considering these closures are roughly equivalent to hooks, I don't think perf should be much of an issue unless a user decides to get extra feisty with computation.

###Benefits
Being able to change colors of values in tables on a per-datum basis means that a lot of customisation is suddenly in users' grips: changing filesize colors based on size thresholds, changing the colors of each boolean, changing durations based on day thresholds, changing strings that match HTML color codes to use the colors represented, and various other bespoke options can be added and adjusted by the users.

###Adding extra inputs to the closures
For now I'm not interested in adding more details as inputs to the closures (such as the cell path of the datum) because I don't have a good idea as to how much is too much.

Anyway, all comments appreciated.

**Comment by fdncred** [comment]
Nice writeup @webbedspace. Thanks for the details. Seems like a reasonable plan. Let's wait to see what others say.

**Comment by rgwood** [comment]
I like it, feels very easy to customize. I'd support giving this a try.

**Comment by fdncred** [comment]
ya, @webbedspace, I'd say move forward with this.
