### ISSUE TITLE
Incorrect parsing of unbalanced braces

### ISSUE THREAD

**Issue by dandavison** [nushell/nushell#6914]
### Describe the bug

Some expressions involving unbalanced braces are parsed incorrectly.

### How to reproduce

```
〉{a: {b: {c: {d: 4}}}}} | get a.b.c.d
4}
```

### Expected behavior

It should be a compile-time parse error.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.1                                          |
| branch             | dev                                             |
| commit_hash        | e7c5abf4efa0f5645fc19a3bd777044e8a0f7136        |
| build_os           | macos-x86_64                                    |
| build_target       | x86_64-apple-darwin                             |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | 1.63.0-x86_64-apple-darwin                      |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.70.1                                          |
| build_time         | 2022-10-20 09:10:05 -04:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by kubouch** [comment]
Minimal example: `{ a: b}}`
