### ISSUE TITLE
The new `++` operator doesn't support table/table

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6916]
### Describe the bug

I think you should be able to use `++` (added a few days ago) to add together tables (which are lists of records), with behaviour identical to `append`. It currently supports list/list and list/table, but not table/table.

### How to reproduce

```
〉[[a b]; [1 2]] ++ [null]
╭───┬───────────────────╮
│ 0 │ {record 2 fields} │
│ 1 │                   │
╰───┴───────────────────╯
〉[[a b]; [1 2]] ++ [[a b]; [1 3]]
Error: nu::parser::unsupported_operation (link)

  × Types mismatched for operation.
   ╭─[entry #6:1:1]
 1 │ [[a b]; [1 2]] ++ [[a b]; [1 3]]
   · ───────┬────── ─┬ ───────┬──────
   ·        │        │        ╰── table<>
   ·        │        ╰── doesn't support these values.
   ·        ╰── table<>
   ╰────
  help: Change table<> or table<> to be the right types and try again.
```

### Expected behavior

See above.

### Configuration

I'm using a prerelease version.
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.1                                          |
| branch             | edited-messages                                 |
| commit_hash        | a4edd88425ade5f3fae2bfb3e93700589e45ce61        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | 1.63.0-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.70.1                                          |
| build_time         | 2022-10-23 15:18:10 +10:00                      |
| build_rust_channel | debug                                           |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by dmatos2012** [comment]
Hi, 
It seems this is about just allowing the `table` type to the supported commands, and make it work like append(just like issue description), thus unless im missing something, this looks like something "easy", and therefore would like to give this one a try as well :)
