### ISSUE TITLE
`headers` should error instead of trying to coerce complicated values to string

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6918]
### Related problem

There are a lot of places where Nushell is rightfully strict about type correctness; I consider it a defining strength of the program. However, `headers` is uncharacteristically lax; while it's reasonable for it to coerce basic values to string, it seemingly has no qualms about even complicated, eminently "unprintable" values being given to it.
```
〉[[a b]; [{1} ($nu.scope.modules)] [2 2]] | headers
╭───┬─────────────┬───────────────────────────╮
│ # │ <Block 188> │ [completionssave-manager] │
├───┼─────────────┼───────────────────────────┤
│ 0 │           2 │                         2 │
╰───┴─────────────┴───────────────────────────╯
```

### Describe the solution you'd like

`headers` encountering anything more complicated than a string, number, boolean, null, or whatever should result in an error, not what is essentially a garbage result.

**Comment by ricardoCMonteiro** [comment]
Hi
I am new to Rust and I would like to start contributing to this project. This looks a good first issue, I would like to git it a try if that's ok.
