### ISSUE TITLE
Compile with **features** failed

### ISSUE THREAD

**Issue by lienke** [nushell/nushell#692]
Compiled with:
`cargo build --all-features && cargo run --all-features`
and compile failed with several messages about `ld` not finding several items.

Recompiled with:
`cargo build`
and finished successfully.
Versions used:
```
rustc 1.39.0-nightly (97e58c0d3 2019-09-20)
nushell 0.1.3
```
Noted also at https://github.com/rust-lang/rust/issues/63848
cheers, drl

**Comment by jonathandturner** [comment]
@lienke - can you show the full report of what items weren't found?

**Comment by lienke** [comment]
@jonathandturner: it looks like several items are being built, so from last, backwards (and I ran out of room in my shell output buffer -- if you really need more than this, I can try capturing stderr to a file, etc.):
```
  = note: /usr/bin/ld: cannot find -lxcb-render
          /usr/bin/ld: cannot find -lxcb-shape
          /usr/bin/ld: cannot find -lxcb-xfixes
          collect2: error: ld returned 1 exit status
---
  = note: /usr/bin/ld: cannot find -lxcb-render
          /usr/bin/ld: cannot find -lxcb-shape
          /usr/bin/ld: cannot find -lxcb-xfixes
          collect2: error: ld returned 1 exit status
---
  = note: /usr/bin/ld: cannot find -lxcb-render
          /usr/bin/ld: cannot find -lxcb-shape
          /usr/bin/ld: cannot find -lxcb-xfixes
          collect2: error: ld returned 1 exit status
          
```
Note that this is with the very recent nightly build of rustc ... cheers, drl

**Comment by andrasio** [comment]
@lienke if you are building all features including optional ones please confirm [you've installed](https://book.nushell.sh/en/installation#debian-ubuntu) these packages on your box.

**Comment by lienke** [comment]
@andrasio: thanks -- from looking at the link you gave, these are installed:
```
pkg-config:
  Installed: 0.28-1
  Candidate: 0.28-1
  Version table:
 *** 0.28-1 0
        500 http://ftp.us.debian.org/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
libssl-dev:
  Installed: 1.0.1t-1+deb8u11
  Candidate: 1.0.1t-1+deb8u11
  Version table:
 *** 1.0.1t-1+deb8u11 0
        500 http://security.debian.org/ jessie/updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.1t-1+deb8u8 0
        500 http://ftp.us.debian.org/debian/ jessie/main amd64 Packages
```
cheers, drl

**Comment by andrasio** [comment]
@lienke What about the packages `libx11-dev` and `libxcb-composite0-dev`? Your latest build errors from `ld` are in those packages.

**Comment by lienke** [comment]
@andrasio -- thanks: yes, it looks like I missed _libxcb-composite0-dev_, I'll install it and try again, but library _libx11-dev_ **was** installed:
```
libxcb-composite0-dev:
  Installed: (none)
  Candidate: 1.10-3+b1
  Version table:
     1.10-3+b1 0
        500 http://ftp.us.debian.org/debian/ jessie/main amd64 Packages
  (debian: using apt-get, apt-cache, apt-file.)
libx11-dev:
  Installed: 2:1.6.2-3+deb8u2
  Candidate: 2:1.6.2-3+deb8u2
  Version table:
 *** 2:1.6.2-3+deb8u2 0
        500 http://security.debian.org/ jessie/updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2:1.6.2-3+deb8u1 0
        500 http://ftp.us.debian.org/debian/ jessie/main amd64 Packages
```
I'll recompile and report a bit later ... cheers, drl

**Comment by lienke** [comment]
The re-compile with _libxcb-composite0-dev_ installed  built successfully, but with warnings as noted ... thanks ... cheers, drl
```
$ cargo build --all-features && cargo run --all-features
   Compiling nu v0.2.0 (/home/...)
warning: the feature `async_await` has been stable since 1.39.0 and no longer requires an attribute to enable
 --> src/plugins/sys.rs:1:12
  |
1 | #![feature(async_await)]
  |            ^^^^^^^^^^^
  |
  = note: `#[warn(stable_features)]` on by default

warning: the feature `async_await` has been stable since 1.39.0 and no longer requires an attribute to enable
 --> src/main.rs:3:12
  |
3 | #![feature(async_await)]
  |            ^^^^^^^^^^^
  |
  = note: `#[warn(stable_features)]` on by default

warning: the feature `bind_by_move_pattern_guards` has been stable since 1.39.0 and no longer requires an attribute to enable
 --> src/main.rs:5:12
  |
5 | #![feature(bind_by_move_pattern_guards)]

```

**Comment by jonathandturner** [comment]
Looks like this is from using a nightly that's newer than the one the 0.2.0 was released for. I'll go ahead and close this, as it looks like you're able to build the full-feature release.
