### ISSUE TITLE
given immutability and shadowing, how to conditionally update a variable without boilerplate?

### ISSUE THREAD

**Issue by colemickens** [nushell/nushell#6921]
### Question

Right now I have to do things like:

```
let foo = "bar"
let cond = false;
let foo = if cond {
  "bar2"
} else {
  $foo
}
```

which feels like a bit much, is there no other way to update `foo`, only when needed, without writing the somewhat redudant else branch?

Either way, this pattern should be documented so users know what to do. 

Presumably right after this section:

>Variables in Nushell are immutable, that means that you cannot change its value after declaration. They can be shadowed in nested block, that results in:

**Comment by colemickens** [comment]
Pre-existing discussion: https://github.com/nushell/nushell/discussions/5284

Still I'm sure users get caught up here and a small example in the context of the mentioned page will go a long ways.

**Comment by colemickens** [comment]
This might be resolved: https://github.com/nushell/nushell/pull/7089

but I've more or less already adapted to the usual immutable nature in nushell and it hasn't been painful really.

**Comment by WindSoilder** [comment]
Yeah currently I think you can use `mut a = 3; $a = 4` to achieve this.

I'll close the issue for now, feel free to re-open it if you still have questions
