### ISSUE TITLE
`help commands` and `$nu.scope.commands` should both have `name` columns instead of one being called `command`

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6922]
### Describe the bug

I was trying to do some work with `$nu.scope.commands`, but was repeatedly getting hurled because, even though `$nu.scope.commands` is supposed to be a superset of `help commands`'s output, it uses a completely different name for one of its columns. (See title).

### How to reproduce

```
〉$nu.scope.commands | columns
╭────┬───────────────╮
│  0 │ command       │
│  1 │ module_name   │
│  2 │ category      │
│  3 │ signature     │
│  4 │ usage         │
│  5 │ examples      │
│  6 │ is_builtin    │
│  7 │ is_sub        │
│  8 │ is_plugin     │
│  9 │ is_custom     │
│ 10 │ is_keyword    │
│ 11 │ is_extern     │
│ 12 │ creates_scope │
│ 13 │ extra_usage   │
│ 14 │ search_terms  │
╰────┴───────────────╯
〉help commands | columns
╭───┬──────────────╮
│ 0 │ name         │
│ 1 │ category     │
│ 2 │ is_plugin    │
│ 3 │ is_custom    │
│ 4 │ is_keyword   │
│ 5 │ usage        │
│ 6 │ search_terms │
╰───┴──────────────╯
〉
```

### Expected behavior

Both columns should be called `name`. I understand this may be a compat break for certain tools, so the other name (`command` on `$nu.scope.commands`) can exist in a deprecated state for awhile.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
ya, i'm always typing `$nu.scope.commands | where name = blah`. so, i vote for it to be `name` in both places. :)

**Comment by dmatos2012** [comment]
This looks like some easy renaming, at least from the looks of it. If so, Id like to give it a try :)

**Comment by fdncred** [comment]
please go for it.
