### ISSUE TITLE
Panic when trying to use custom command as argument to an alias

### ISSUE THREAD

**Issue by ericdching** [nushell/nushell#6925]
### Describe the bug

I get a panic (on macOS and Linux - I don't have Windows) when I run an alias and pass in the result of a custom command as an argument. The panic happens when I enter the open paren for the custom command. 

- Does not reproduce with external commands
- Does not reproduce in latest `0.70.0` release - I am on current main

### How to reproduce

 〉alias c = cat
 〉c thread 'main' panicked at 'byte index 18446744073709551613 is out of bounds of `c (`', library/core/src/str/mod.rs:107:9
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::str::slice_error_fail_rt
   3: core::ops::function::FnOnce::call_once
   4: core::intrinsics::const_eval_select
   5: core::str::slice_error_fail
   6: nu_cli::syntax_highlight::find_matching_block_end_in_expr
   7: nu_cli::syntax_highlight::find_matching_block_end_in_block
   8: <nu_cli::syntax_highlight::NuHighlighter as reedline::highlighter::Highlighter>::highlight
   9: reedline::engine::Reedline::repaint
  10: reedline::engine::Reedline::read_line
  11: nu_cli::repl::evaluate_repl
  12: nu::main

### Expected behavior

No crash, result of custom command passed in successfully as argument to the alias.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.1                                          |
| branch             | main                                            |
| commit_hash        | 10aa86272bdcce63506f00f4dc8d0eafb99f7d0f        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)             |
| rust_channel       | 1.63.0-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)             |
| pkg_version        | 0.70.1                                          |
| build_time         | 2022-10-20 18:21:58 -05:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
@paper-lark Do you think this is related to https://github.com/nushell/nushell/pull/6655? If so, would you mind looking into this?

**Comment by melMass** [comment]
I can reproduce this and it was also reported on discord, a little more info, in debug:
<img width="697" alt="image" src="https://user-images.githubusercontent.com/7041726/198672795-5ac59c21-319f-451a-8d7c-1f43857ab5bd.png">

This is the culprit section:
https://github.com/nushell/nushell/blob/66c2a36123451d58a5f6020f7b68021d6f6763d3/crates/nu-cli/src/syntax_highlight.rs#L274

**Comment by paper-lark** [comment]
Yes, that's a bug in https://github.com/nushell/nushell/pull/6655. Will look into it tomorrow
