### ISSUE TITLE
Trying to use `upsert` with a list produces a bad error

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6926]
### Describe the bug

See title.

### How to reproduce

```
〉[1 2 3] | upsert 3 2
Error: nu::shell::not_a_list (link)

  × Not a list value
 1 │ [1 2 3] | upsert 3 2
   ·  ┬               ┬
   ·  │               ╰── value not a list
   ·  ╰── value originates here
   ╰────

```
As you can see, the error arrows are extremely contradictory.

### Expected behavior

Better error message.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
I believe `upsert` requires a cell path as the first argument and a value for the second. We could of course make `upsert`, `update`, and `insert` work on lists but at this point, they're not designed to work that way.

```rust
    fn signature(&self) -> Signature {
        Signature::build("upsert")
            .required(
                "field",
                SyntaxShape::CellPath,
                "the name of the column to update or insert",
            )
            .required(
                "replacement value",
                SyntaxShape::Any,
                "the new value to give the cell(s)",
            )
            .category(Category::Filters)
    }
```

**Comment by webbedspace** [comment]
I was trying this because `update` already works on lists:
```
〉[1 2 3] | update 0 2
╭───┬───╮
│ 0 │ 2 │
│ 1 │ 2 │
│ 2 │ 3 │
╰───┴───╯
```
The issue is that the error message is poor at explaining what's going on.

**Comment by fdncred** [comment]
It's interesting that `update` works because all 3 commands that I mentioned have the same signature. This just shows how different people, when implementing commands, implement them differently. Although I want to say that JT implemented both `update` and `upsert` but I could be misremembering.

Oh ya, there's a `update cells` too, which has a different signature but is related.

Of course, you're right, that it's always helpful to have better error messages.

**Comment by fdncred** [comment]
I also wonder if we can simplify somehow. We have these two syntaxes for these commands.
1. update 0 2
2. update column_name {|b| do_something_with $b}

@webbedspace do you think we should have both forms?  I have no idea how you do number 1 with number 2 syntax.

**Comment by webbedspace** [comment]
>It's interesting that update works because all 3 commands that I mentioned have the same signature. This just shows how different people, when implementing commands, implement them differently.

Something I've found rather frustrating about the codebase's commands is how most of the important type-checking seems to be embedded inside the `run()` functions instead of handled by whatever calls them. I was hoping `signature()` was an important type-checking method, but it seems like it's mostly used for syntax-highlighting and can't be used to type-restrict the piped input at all (which is arguably far more important than any of the flags or positionals).

Back to the topic… the `update { block }` form is kind of confusing: it only properly iterates with tables (because it requires a column name) and moreover doesn't seem to have much advantage over `each` combined with the single-value form of `update` (which can also iterate over tables). For plain records, `update { block }` does no iteration and thus the block can seemingly be replaced with `( $in | expression )` (or, if you have a block stored in a variable, `($in | each $block)`.) I think the only things that really need blocks as arguments are commands that explicitly iterate (and `do`, of course).
