### ISSUE TITLE
` (do { $in })` produces `null` instead of the input

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6928]
### Describe the bug

See title. The examples below lead me to believe this is a bug.

### How to reproduce

```
〉[1 4 5] | ($in) | describe
list<int>
〉[1 4 5] | ($in | $in) | describe
list<int>
〉[1 4 5] | do { $in } | describe
list<int>
〉[1 4 5] | do { $in } | $in | describe
list<int>
〉[1 4 5] | (do { $in }) | describe
nothing
```

### Expected behavior

I expect all the above examples to propagate $in correctly. If this is actually fully functional then I assert that the functionality is confusing.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by devyn** [comment]
Confirmed that this is working now
