### ISSUE TITLE
Crash on Windows

### ISSUE THREAD

**Issue by cHolzberger** [nushell/nushell#693]
nu is crashing on windows wenn entering "ö" and pressing TAB afterwards

**Comment by jonathandturner** [comment]
Are you using the binary or building it?  If you're building it, it'd be helpful to know where it's crashing to see if we can fix it.

**Comment by cHolzberger** [comment]
no, its the binary release from "here"

**Comment by jonathandturner** [comment]
I'm not able to reproduce this error in a recent version of Nu. Can you share the full command you're trying to run? Also, if possible, can you also share the version of Windows you're running?

**Comment by cHolzberger** [comment]
ok fixed with 0.3.0
