### ISSUE TITLE
general metadata on values

### ISSUE THREAD

**Issue by PerBothner** [nushell/nushell#6933]
### Related problem

The manual mentions that Values may have associated [metadata](https://www.nushell.sh/book/metadata.html) but as far as I can tell, the only supported metadata kind is the source-location `Span`.  An actual general metadata facility would be very useful:

* When converting a string to html, it would be useful to have a hint what kind of font is preferred - at least whether monospace or proportional would be more appropriate.

* A type for "rich text" (possibly encoded as HTML) would be nice.

*  It is sometimes useful to annotate a string with a (human) language.

* A String or a Binary could usefully have a mimetype. If the mimetype is an image, the UI could display the image. An enhanced `ls` could display thumbnails.

* It is a good idea to be able to distinguish a string of plain text from one that may have embedded ANSI escapes. The latter is kind of a rich text in a limited arcane format. (The code in `html.rs` to convert ANSI escapes to HTML with styles is very limited and fragile.)

* Consider replacing the Value types `Filesize`, `Duration,` and `Date`, perhaps with `String`+metadata.

* Get rid of the `DataSource` kludge for filenames from the `ls` command.  The problem with the `DataSource` kludge is that it is attached to the `PipelineData` type combined with a hardwired check for the `"name"` field name. So if you rename a column or extract it as a plain string (perhaps with `get 5.name`) it is no longer a filename.

### Describe the solution you'd like

The obvious meta-data representation is a `HashMap` per Value, but I think that would be over-kill.

I suggest `Vec<(MetadataKey,Value)>` where `MetadataKey` is an "interned String" (a "symbol"). That means you can compare `MetadataKey` using a cheap `std::ptr::eq` comparison, so looking for a metadata value with a `MetadataKey` is very fast, assuming a small number of elements in the `Vec`. There is a slight inconvenience in that you have to register each potential `MetadataKey` in a global table.(Un-registering is even worse but hopefully doesn't need to be supported.)

**Comment by rgwood** [comment]
Neat proposal!

When you say that a hash map would be over-kill, in what sense do you mean that? I’d like to understand what downsides you’re thinking of.

**Comment by PerBothner** [comment]
I haven't looked at the HashMap implementation - I watched the video on "SwissTable" at some point, but don't remember how it works.  However, any hash-table will require more space than a vector with the same number of elements, assuming a load-factor below 1.0. There may also be extra book-keeping fields - a Vec just requires a length and optionally a capacity. This may be undesirable if we assume most Values have 0 metadata properties, and having more than 2-3 being extremely rare.
Speedwise, if we make the same assumption, a linear search in a Vec may be as fast or faster than a lookup in a HashMap. However, I'm mainly concerned about space.
I'm assuming a MetadateKey is either an integer or a pointer than can be compared using pointer equality.
Of course, if most values have 0 metadata properties, either way we can optimize for that by using an `Option` - whether we use a HashMap or a Vec.

Either way, I suggest making the implementation private.  The query function would take a `&Value` and a `MetadataKey` and return an `Option<Value>`. Or perhaps some kind of reference to a value. My Rust-ability isn't strong enough to say the best way to do this.

**Comment by PerBothner** [comment]
Associating metadata with table columns seems another idea worth exploring. It is less expensive than associating metadata with each Value - plus being to access "table metadata" seems potentially very useful.

Consider a TableInfo that contains "type information" about a table:

    struct TableInfo {
      col_names: Vec<String>, // column names
      col_metadata: Vec<MetaData>, // per-column metadata ("type" information)
    }

We add an optional TableInfo to PipelineMetadata:

    pub struct PipelineMetadata {
      table_info: Option<TableInfo>,
    }

This information is provided by each command.
The `table_info` field is `None` if the pipeline output is not a table with known columns.

We also add it to Value::List:

    List {
      table_info: Option<TableInfo>,
      vals: Vec<Value>,
      span: Span,
    },

If List's table_info is Some, then each element of vals is a Record that matches the table_info.

If a `PipelineData::ListStream` is converted to a Value using `PipelineData::into_value`, then its `table_info` field is copied (or moved) to the resulting `Value::List`. Conversely, if a PipelineData value is created from a Value::List, the table_info is copied.

Note this  subsumes the need for `PipelineMetadata` to contain a `DataSource` `Ls`. Instead of checking for a column called `"name"` you check for a colum with a `filename` metadatum. This is more robust, since it survives column renaming.

**Comment by webbedspace** [comment]
>Consider replacing the Value types `Filesize`, `Duration`, and `Date`, perhaps with String+metadata.

Do not do this. These have valuable operation support. For instance, you can currently write Date - Duration = Date and it will just work. You can also write `def foo [bar:filesize] { }` and it will correctly force the user to write the argument as a filesize.

**Comment by PerBothner** [comment]
> Do not [replace Filesize/Duration/Date with String+metadata]".

I was talking about changing the internal representation of these types - which does not preclude them from having "valuable operation support". Instead of special-purpose sub-types of `Value` _just_ for these types, a more flexible framework using metadata to indicate type-information has some advantages. Imagine adding a kind of value as a new sub-type of `Value` - there are a lot of places in the code that might have to be changed.

However, I agree the existing way works fine and there is little to be gained by changing the representation of these types.

**Comment by rgwood** [comment]
Copying some of JT's comments from Discord to keep the discussion in 1 place:

> metadata on each Value is a bit too heavyweight. We have metadata on the pipeline that a command can read. Currently, this just talks about the source of the data, but it could be expanded to do more
You can see this in PipelineData and the cases having access to an optional PipelineMetadata

> we did used to have metadata on individual values but in practice found that it caused a lot of duplication, took a lot more memory, and generally ran a bit slower than having smaller Value representation

**Comment by PerBothner** [comment]
Brainstorming a bit further on the `TableInfo` idea, we can actually save a chunk of space in each `Record` by replacing the `cols` vector with a shared pointer to a `TableInfo`:

    Record { // in enum Value
        info: Rc<TableInfo>,
        vals: Vec<Value>,
        span: Span,
    },

In the normal case when creating a "uniform table" each Record would point to the same TableInfo object.

The `List` or the `PipelineMetaData` value would point to the same `TableInfo` object (as shown previously):

    List { // in enum Value
      table_info: Option<Rc<TableInfo>>,  // None if not a uniform table
      vals: Vec<Value>,
      span: Span,
    },

    pub struct PipelineMetadata {
      table_info: Option<Rc<TableInfo>>, // None if not a uniform table
    }

**Comment by rgwood** [comment]
Thanks for the proposal, this was an interesting one. Closing this as we don't have any plans to tackle this in the near future.
