### ISSUE TITLE
How to continue command on failure?

### ISSUE THREAD

**Issue by SUPERCILEX** [nushell/nushell#6956]
### Question

I'd like to have a script that does several things in blocks of failures like this:

```
allow_fail { a; b; c }; allow_fail { d; e; f }
```

So if a fails, neither b nor c will run, but d will start running.

I'm basically just trying to convert this bash script to nu:
```bash
alias update="sudo apt update && sudo apt upgrade && sudo apt autoremove;
  flatpak update && flatpak uninstall --unused;
  ask 'Update Rust?' Y && rustup update; cargo install-update --all"
```

**Comment by hustcer** [comment]
You can try to wrap the command you want to run even on failure with `do -i`, like this: 
```sh
do -i {echo 1; ls abbb}; do -i {echo 2; ls cccx}
```

**Comment by SUPERCILEX** [comment]
Huh, I'm super confused. Your example works, but this one doesn't:
```nu
do -i { nu -c 'exit 1' }; echo true
```

This on the other hand does work:
```nu
do -i { fake }; echo true
```

So maybe if the shell has an error running the command, `do -i` works, but it won't take into account the program's exit code?

**Comment by webbedspace** [comment]
External exit codes work differently from built-in syntax and command errors, because a lot of external programs use `exit 1` to mean stuff like "didn't find anything", "no files changed" or "HTTP 404", which technically isn't a "user error" per se. To get exit codes, use `complete`.

**Comment by SUPERCILEX** [comment]
Sure, I don't mind being able to differentiate between shell errors and program errors, but `complete` is not an acceptable replacement. How would someone apply the exit code information to my original example? I think a reasonable solution is to add another flag to the do command that interprets program exit codes.

**Comment by webbedspace** [comment]
Yes, the current inability to easily "early exit" a pipeline is quite a problem, I admit…

**Comment by SUPERCILEX** [comment]
Yeah, I guess early exit is what I'm asking for, that'd be nice. :)

Looking at the [code](https://github.com/WindSoilder/nushell/blob/457514590dc0812ebc81bfb0929ffeb68c081622/crates/nu-command/src/core_commands/do_.rs#L145), it seems like `do -c` parses the exit code, but I have no idea what it does. A search for `site:https://www.nushell.sh/ "do -c"` returns no results.

**Comment by SUPERCILEX** [comment]
Hmmm, found this: https://github.com/nushell/nushell/issues/6617#issuecomment-1262050374

**Comment by SUPERCILEX** [comment]
That actually makes it sound like early exit. This issue should maybe be thought about in terms of "break." `do -c` is a return whereas the new option would be a break.

**Comment by mb21** [comment]
For those arriving here via a search engine, the [`do`](https://www.nushell.sh/commands/docs/do.html) block has the flags:

- `--ignore-errors, -i`
- `--ignore-shell-errors, -s`
- `--ignore-program-errors, -p`
- `--capture-errors, -c`

**Comment by fdncred** [comment]
Not any longer. The `do` command only has `-i` and `-c` now

**Comment by mb21** [comment]
Ah, perhaps that's not released yet? Or docs not up-to-date? Anyway, I edited my comment above.

**Comment by fdncred** [comment]
ya, maybe it'll be in 0.104.0
