### ISSUE TITLE
Can't seem to pass a string contains a "#" to a nushell script

### ISSUE THREAD

**Issue by colemickens** [nushell/nushell#6957]
### Describe the bug

I can't seem to pass a string containing a pound sign ("#") to a nushell script:

`cat minimal.nu`
```nu
#!/usr/bin/env nu

def main [ f: string ] {
  echo $f
  echo $"($f)"
}
```

```
> /tmp/minimal.nu "hello#world"
hello
hello

> /tmp/minimal.nu "hello\#world"
hello
hello

> /tmp/minimal.nu 'hello\#world'
hello\#world
hello\#world

>/tmp/minimal.nu 'hello#world'
hello
hello

> let f = "hello#world"
/tmp/minimal.nu $f
hello
hello
```

I did try searching for other open issues, however, this one is hard to discover. I even know of #6741 but couldn't find it organically when searching Issues.

This seems more unexpected/bug-like than #6741 so I wanted to go ahead and open it.

### How to reproduce

Try to pass a string containing a '#' to a nushell script, find that it is  very difficult, or maybe impossible to do so without it being truncated.

### Expected behavior

Some sort of workaround/quoting behavior, etc.

### Configuration

`nu --version` says 0.70.0 but I get it from the flake

**Comment by Decodetalkers** [comment]
Try
```
/tmp/minimal.nu '"hello#world"'
```
use signal quotation marks, because quotation marks in nushell, it is turned to string, then the string received by nushell will from
"ss#" -> ss#,   Maybe there will be a good solution for such kind of thing

**Comment by hugosenari** [comment]
I have similar problem but with "a(b)c" it says executable was not found

echolino.nu

```nushell
#!/nushell-0.70.0/bin/nu --stdin
def main [ p: string ] {
    echo $p
}
```
than from bash
```
 echolino "(ls)"
```
It list my files,

Curously if I add an space doesnt work
```
 echolino "(ls )"
```

**Comment by Kangaxx-0** [comment]
To address this issue, please use string literal, something like " \\' xxxxxx \\' ", quotes do not work because [std::env::args()](https://doc.rust-lang.org/std/env/fn.args.html) does not reserve the quotes, the input `"hello#world"` will be converted into raw string `hello#world`, and the tokenization(LEX) will end up with incorrect state

**Comment by colemickens** [comment]
Did this get fixed?

```
╭ zeph  ~/code/nixcfg 4.16s ✘1
╰─▶ nix build -v --rebuild .#pkgs.x86_64-linux.powertop
warning: Git tree '/home/cole/code/nixcfg' is dirty
warning: Git tree '/home/cole/code/nixcfg' is dirty
Using saved setting for 'experimental-features = nix-command flakes recursive-nix' from ~/.local/share/nix/trusted-settings.json.
Using saved setting for 'extra-substituters = https://cache.nixos.org https://colemickens.cachix.org https://nixpkgs-wayland.cachix.org https://unmatched.cachix.org https://nix-community.cachix.org' from ~/.local/share/nix/trusted-settings.json.
Using saved setting for 'extra-trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= colemickens.cachix.org-1:bNrJ6FfMREB4bd4BOjEN85Niu8VcPdQe4F4KxVsb/I4= nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= unmatched.cachix.org-1:F8TWIP/hA2808FDABsayBCFjrmrz296+5CQaysosTTc= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=' from ~/.local/share/nix/trusted-settings.json.
checking outputs of '/nix/store/rhv9m7n1hjh8fh7v0kpz8y8g89n6fqp7-powertop-2.15.drv'..
```

I see the same behavior if I single/double quote it.

**Comment by colemickens** [comment]
And one last note, it also works passing it to a nushell script, which I think was part of my problem:

```
╭ zeph  ~/code/nixcfg 0.88s ✘1
╰─▶ ./main.nu build /home/cole/code/nixcfg#pkgs.x86_64-linux.nushell
▒▒ eval: /home/cole/code/nixcfg#pkgs.x86_64-linux.nushell
```
