### ISSUE TITLE
Should I use nushell instead of bash if...?

### ISSUE THREAD

**Issue by EmilySeville7cfg** [nushell/nushell#6959]
### Question

Should I use Nushell instead of Bash if I need linter for shell scripts and IDE/editor support like intellisence and syntax highlighting? I love Bash but I also think that I need something better that will boost my productivity. I don't want to use PowerShell as it seems too complicated for me.

### Additional context and details

I use Intellij IDEA and VS Code.

**Comment by hustcer** [comment]
As far as I see, There is no linter or intellisence for nushell currently, and syntax highlighting is supported in VS Code. Despite this, I have already rewrote all my bash scripts with nu, I've never regretted doing so

**Comment by hustcer** [comment]
Let's close it now, feel free to post to `Discussions` if you have any other questions.
