### ISSUE TITLE
Consider separating `find -p` option into new `filter` command (overload of dataframe `filter`)

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6964]
### Related problem

The problem I'm having with `find` is that forgetting `-p` when providing a block is a bad failure case: it instead searches for whether the block exists inside the input structure, and usually returns an empty list as a result. I also notice that giving `find` two different "modes" clashes with other programming languages like JS and Python, which use the term `filter` for the `-p` "mode".

Also:
* `find` has several other flags which don't interact with `-p` at all.
* The long form `--predicate` is very awkward, insofar as "predicate" is not really the most common word for that type of argument (notice the Search Terms uses "Condition" instead).
* The existing dataframe `filter` command has roughly the same functionality and semantic meaning as `find -p`, so the word is already part of Nushell jargon.

### Describe the solution you'd like

I want this functionality to instead be on a `filter` command. This would be an overload of the existing dataframe `filter` command. It would have no flags differing from the dataframe `filter`.

The way to distinguish between them at runtime is that dataframe input would require lazy expressions, whereas normal input would require blocks or normal expressions.

**Comment by fdncred** [comment]
I agree that `--predicate` is too programmery. It seems like `filter` is very generic. Is `filter` supposed to take the place of `where`?

**Comment by webbedspace** [comment]
Hmm, good point, I hadn't considered the overlap of `find -p` and `where`. I think I'll withdraw this suggestion in that light.
