### ISSUE TITLE
`help register` freezes

### ISSUE THREAD

**Issue by Jan9103** [nushell/nushell#6978]
### Describe the bug

The command `help register` and `register --help` freeze. after pressing `crtl+c` it prints the help text and continues as expected

### How to reproduce

`help register` or `nu -c 'help register'` (to prevent loading configs)

### Expected behavior

Not freeze before printing the help text

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:52:28 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

i think it worked in the past on my machine (probably nu 0.68)

Terminal: kitty  0.21.2 (in case it has something to do with control-characters)

**Comment by fdncred** [comment]
No issue with `help register` on Windows or WSL on nushell 0.70.1.

**Comment by siph** [comment]
I'm not having any trouble on 0.70.0 with linux and kitty 0.26.2.

**Comment by WindSoilder** [comment]
I can't reproduce it as well..

**Comment by theAkito** [comment]
Works for me in `0.72.0` & `0.71.0`.

**Comment by theAkito** [comment]
If there will be a third weird issue, that only happens on your machine, perhaps something is actually wrong on your machine. 😄

**Comment by fdncred** [comment]
let's close for now. we can reopen if this pops up again.
