### ISSUE TITLE
Case insensitive history search

### ISSUE THREAD

**Issue by qingxiang-jia** [nushell/nushell#6980]
### Question

Is it possible to search history in a case-insentitive fashion? Like, after hit CTRL+R, when I search "syu", "sudo pacman -Syu" also shows up (so "syu" also matches "Syu").

### Additional context and details

I have went through the config.nu and the issues and it seems no one has mentioned this. Thanks!

**Comment by sholderbach** [comment]
To my knowledge that is not implemented yet. Might need additional configuration on `reedline`

**Comment by fdncred** [comment]
I thought the default was case insensitive?
![image](https://user-images.githubusercontent.com/343840/199521261-48a05791-a241-49f5-8638-6e669a7cf033.png)

**Comment by qingxiang-jia** [comment]
> To my knowledge that is not implemented yet. Might need additional configuration on `reedline`

Got it. Thank you. Maybe I will use @fdncred's approach.
