### ISSUE TITLE
Should `find --predicate` be deprecated in favour of `where`?

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6987]
### Question

I was recently informed that `find --predicate` is actually basically the same as `where`, and I've realised that I've been reflexively using `find` and `where` in different places without realising their similarity all this time. I think only having one command that does the very basic thing that `where` does is more than sufficient. Also, `find` has several other flags that do not interact with `--predicate` at all, and deprecating `--predicate` would make its help page a little cleaner and easier to understand.

If there are any actual differences between the two, do tell.

**Comment by rgwood** [comment]
I agree with this. Will put together a PR tonight.
