### ISSUE TITLE
`['4'] | to nuon` produces `[4]` (turns it into a list<int>)

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#6989]
### Describe the bug

See title.

### How to reproduce

```
〉['4'] | to nuon
[4]
〉['4'] | describe
list<string>
〉['4'] | to nuon | from nuon | describe
list<int>
```
See the first example and third example.

### Expected behavior

Same behaviour as this (but without whitespace):
```
〉['4'] | to json
[
  "4"
]
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by jntrnr** [comment]
For this, we could probably just quote all strings. This helps the format be a bit more robust against any changes to barewords in the future. For example, if we added a new unit type, we wouldn't accidentally break anyone's files.

**Comment by webbedspace** [comment]
>For example, if we added a new unit type, we wouldn't accidentally break anyone's files.
In this particular case, the PR I made [#7056](https://github.com/nushell/nushell/pull/7056) makes all strings containing any digit be quoted.

By the way, wasn't there a PR only a few months ago (https://github.com/nushell/nushell/pull/6379) that added these no-quoting rules?
