### ISSUE TITLE
History hint completion in vi-normal-mode.

### ISSUE THREAD

**Issue by siph** [nushell/nushell#6991]
### Related problem

When using vi-mode with both `fish` and `zsh`, pressing the 'l' key while in normal mode will complete the history hint. This doesn't work with `nushell`.

### Describe the solution you'd like

It would be nice if `nushell` had functionality consistent with `zsh` and `fish`. I'm not sure if this should be done in `reedline` instead.

### Describe alternatives you've considered

This is easy to configure:
```nu
  keybindings: [
      {
          name: history_completion_vi_normal
          modifier: none
          keycode: char_l
          mode: vi_normal
          event: {
              until: [
                  { send: historyhintcomplete }
                  { send: menuright }
                  { send: right }
              ]
          }
      }
  ]
```

**Comment by sholderbach** [comment]
Oh yeah that sounds like we missed that on the reedline side. I think setting the binding like this stops `l` from reaching the full vi parser. So stuff like `5l` or `dl` would not work with this change.

**Comment by siph** [comment]
>I think setting the binding like this stops `l` from reaching the full vi parser.

You're right, it does.

**Comment by sholderbach** [comment]
Do you have any particular expectations how the token/wordwise accepting of autosuggestion hints should behave in vi-mode?
Do you press `w` `e` or `W`/`E` for that? Do you want the accepted text to be perfectly matching the regular vi moves or do you find the behavior in `fish` or `zsh` surprising in that regard?

**Comment by siph** [comment]
I like having the option to use word-jump movements to complete smaller chunks of commands, but typically I will just fill the entire command and change what I need. Because of this, the inside(`i`) and around(`a`) blocks are the features I miss most in the `reedline` implementation, which I see mentioned in the other [issue](https://github.com/nushell/nushell/issues/5226#issuecomment-1104720571). My expectations are for things to work like the `zsh` implementation for no reason other than muscle memory, but I assume most users will have similar expectations. My only experience with `fish` is testing this particular feature for this issue so I can't speak on it.

**Comment by sholderbach** [comment]
Yeah `iw` `a(` and friends are definitely the feature I am personally missing the most in reedline's vi mode, but this needs a bigger change to how we do the vi emulation to really work well. Sadly I haven't had  the consecutive time to really get behind that for a while.
The refactor for that should make the partial hint accepting also more straightforward to implement instead of duplicating some code.
