### ISSUE TITLE
nushell expands arguments with `~` depending on filename

### ISSUE THREAD

**Issue by rsteube** [nushell/nushell#6993]
### Describe the bug

Depending on filename nushell expands arguments:
- `example '~/Doc'` gets passed `/home/user/Doc`
- `example.sh '~/Doc'` gets passed `~/Doc`

### How to reproduce

1. create `example` and `example.sh` as executable scripts in `~/.local/bin` (or somewhere else in `$PATH`)
```sh
#!/bin/sh
echo "$@"
```
2. invoke with each with an argument that has `~/` as prefix

### Expected behavior

Consistent behavior unrelated to filename. Expanding it makes sense in a lot of cases but for https://github.com/rsteube/carapace-bin/issues/1396 i need a way to pass it to `carapace` unchanged.

### Screenshots

```sh
~ 
nu ❯ example.sh '~/Doc'
'~/Doc'

~ 
nu ❯ example '~/Doc'
/home/rsteube/Doc
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:52:28 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by WindSoilder** [comment]
Currently `example '~/Doc'` and `example.sh '~/Doc'` will be the same.

But `example.sh ~/Doc` and `example ~/Doc` still different, but it works for quoted string at least
