### ISSUE TITLE
How to find the input type of a command

### ISSUE THREAD

**Issue by hbt** [nushell/nushell#6996]
Issue:

```
ls | get name | [Press-Tab-Key]
```

will list all commands, most are irrelevant because the data type is not an acceptable input (e.g `fmt` which operates on `Value::Int` and `Value::Filesize` only.)

```
ls | get name | describe
```
prints `list<string>`

1. How can I find out a list of a commands that operate on a specific data type as input?
e.g `ls | get name | describe | list-cmds-by-type`

2. Is there a way to find out the accepted data type for `fmt` from the `help` command? find the function exact signature?
e.g `help fmt` or `fmt --input-type`

PS: I'm new to nushell

Thank you.

**Comment by kubouch** [comment]
Welcome to Nushell!

Currently, that's not possible. We're planning to revamp how we do the command typing and integrate it into the language better. Listing/suggesting commands by type would be a great feature.

**Comment by dandavison** [comment]
Hi @hbt, just backing up what @kubouch said -- this will be possible to implement soon, once https://github.com/nushell/nushell/pull/6796 lands.
