### ISSUE TITLE
Nushell doesn't play well with Golang wildcard path syntax: "./..."

### ISSUE THREAD

**Issue by Southclaws** [nushell/nushell#7015]
### Question

I'm wondering if there's a workaround or a way to configure this to work as expected. Golang has this weird construct called wildcard package paths where an ellipsis in the path means "this package and all sub-packages" where a package is a directory with one or more .go files.

Unfortunately, on Nushell v0.61.0 this happens (I'm updating to check latest but it's taking ages for some reason)

<img width="495" alt="image" src="https://user-images.githubusercontent.com/1636971/200127253-5df84dd5-eb64-471e-a01d-57398edf06db.png">

The first command invocation is via powershell, then I exit that and run it in nushell, where it fails as it interprets `./...` as two directory jumps upwards.

### Additional context and details

https://pkg.go.dev/cmd/go#hdr-Package_lists_and_patterns

**Comment by fdncred** [comment]
Does it still happen on the latest version 0.70.0?

**Comment by Southclaws** [comment]
It finally updated and no, it's all working fine now!
