### ISSUE TITLE
Why `RawStream` contains an `Iterator` of `Vec<u8>` instead of `std::io::Read`?

### ISSUE THREAD

**Issue by Kixunil** [nushell/nushell#7017]
### Question

`RawStream` is an iterator of heap-allocated chunks of bytes as opposed to `std::io::Read` which may harm performance in some cases. The only reason that comes to my mind is having a different error type but that could've been implemented by having a custom `Read` trait that's a copy of `std::io::Read` except for error bytes.

Is there any other reason I don' see? If not how hard would it be to refactor it?

### Additional context and details

I started working on optimizing json objects parsing to not collect the whole stream into string as mentioned in https://github.com/nushell/nushell/issues/6979#issuecomment-1304582457 and assumed it implements `Read` which is not the case. I even implemented a bunch of optimizations aiming at significantly reducing heap allocations. :man_facepalming: I'm now wondering how to proceed.

**Comment by rgwood** [comment]
Hi, I looked at this a bit and I'm not sure what the answer is, sorry! If you want to try adding a new custom `Read` trait like that, feel free.

https://github.com/nushell/nushell/blob/cf0a18be51eddbb95dff04172e2a72e9dc7c432f/crates/nu-protocol/src/value/stream.rs#L11
