### ISSUE TITLE
append $env.PATH does not work correctly in config.nu

### ISSUE THREAD

**Issue by iujakchu** [nushell/nushell#7030]
### Describe the bug

when I add 
`let-env PATH = ($env.PATH | prepend "~/.cargo/bin")` to my config.nu
After spawning a new shell,I got:
```
❯ : $env.PATH
 0   ~/.cargo/bin
 1   /run/wrappers/bin:/home/yann/.nix-profile/bin:/etc/profiles/per-user/yann/bin
     :/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
```
but when I remove this line from my config.nu and run it in a new shell.
I got:
```
❯ : $env.PATH
 0   /run/wrappers/bin
 1   /home/yann/.nix-profile/bin
 2   /etc/profiles/per-user/yann/bin
 3   /nix/var/nix/profiles/default/bin
 4   /run/current-system/sw/bin
 5   ~/.cargo/bin/
```
which works.
My nushell version:
```
❯ : version
 version              0.70.0
 branch
 commit_hash
 build_os             linux-x86_64
 build_target         x86_64-unknown-linux-gnu
 rust_version         rustc 1.64.0
 cargo_version        cargo 1.64.0
 pkg_version          0.70.0
 build_time           1980-01-01 00:00:00 +00:00
 build_rust_channel   release
 features             database, dataframe, default, trash, which, zip
 installed_plugins
```

### How to reproduce

1.add `let-env PATH = ($env.PATH | prepend "~/.cargo/bin")` to  config.nu
2.run `$env.PATH` in a new shell

### Expected behavior

paths are expanded correctly

### Configuration

❯ : version | transpose key value | to md --pretty
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0                                    |
| cargo_version      | cargo 1.64.0                                    |
| pkg_version        | 0.70.0                                          |
| build_time         | 1980-01-01 00:00:00 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by kubouch** [comment]
You need to split the the PATH by the separator first

**Comment by iujakchu** [comment]
Thanks.
But another issue occurs here.
I've added `~/.cargo/bin` to $env.PATH,but I can not find executable.
```
~
❯ : $env.PATH
 0   ~/.cargo/bin
 1   /run/wrappers/bin
 2   /home/yann/.nix-profile/bin
 3   /etc/profiles/per-user/yann/bin
 4   /nix/var/nix/profiles/default/bin
 5   /run/current-system/sw/bin

~
❯ : ls .cargo/bin
 #             name             type     size      modified
──────────────────────────────────────────────────────────────
 0   .cargo/bin/joshuto         file    7.9 MiB   a month ago
 1   .cargo/bin/move            file   43.0 MiB   9 hours ago
 2   .cargo/bin/move-analyzer   file   21.3 MiB   9 hours ago

~
❯ : joshuto
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #4:1:1]
 1 │ joshuto
   · ───┬───
   ·    ╰── executable was not found
   ╰────
  help: No such file or directory (os error 2)
```

**Comment by kubouch** [comment]
Maybe try to expand the path. I think PATH should auto-expand so this might be a bug, but expanding manually should work.

**Comment by iujakchu** [comment]
I have expanded the path.But nu cannot find exe as descripted above.

**Comment by Decodetalkers** [comment]
use
```
 prepend $"($env.HOME)/.cargo/bin"
```
Not `~`, `~` is a char, not a variable

**Comment by kubouch** [comment]
`~` should work fine. Can you post exactly how you did the expansion and prepending in the config? `~/.cargo/bin | path expand` should work fine. It should work without the expansion as well IMO.

**Comment by iujakchu** [comment]
I just add `let-env PATH = ($env.PATH |split row ":"| prepend "~/.cargo/bin")` to my config.nu.
Also changing ~ seems no help.

**Comment by Decodetalkers** [comment]
> I just add `let-env PATH = ($env.PATH |split row ":"| prepend "~/.cargo/bin")` to my [config](https://github.com/iujakchu/jak.nix/blob/learn/xdg/nushell/config.nu). Also changing ~ seems no help.

```
let-env PATH = ($env.PATH | prepend $"($env.HOME)/.cargo/bin")
```
this will work , here `$env.HOME` will be convert to the absolute path

Here , I think nu think `~` is the folder name , I do not know if it is a bug

**Comment by iujakchu** [comment]
![s](https://user-images.githubusercontent.com/86193029/200251064-526cffab-8a2c-41be-98a2-1faf57c79e97.png)
It's strange that $env.PATH does not expand automatically in my config file.
So I have to use `let-env PATH = ($env.PATH |split row ":"| prepend $"($env.HOME)/.cargo/bin")`.
But here is another problem:
![a](https://user-images.githubusercontent.com/86193029/200252128-ede05bc0-69ed-4e1d-a56b-7502a8459994.png)
$env.PATH get expand,but I cannot access file in ~/.cargo/bin still.

**Comment by Decodetalkers** [comment]
I am curious about the $env.PATH is read as
```
/run/wrappers/bin:/home/yann/.nix-profile/bin:/etc/profiles/per-user/yann/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
```
It is abnormal, it should be a list, should not parse by yourself.

**Comment by iujakchu** [comment]
> I am curious about the $env.PATH is read as
> 
> ```
> /run/wrappers/bin:/home/yann/.nix-profile/bin:/etc/profiles/per-user/yann/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
> ```
> 
> It is abnormal, it should be a list, should not be parse by yourself.
> 

You are right.All my configs are [here](https://github.com/iujakchu/jak.nix/tree/534a44febddde97b28b7f4c1b6af1ce7432e98ea/xdg/nushell).
- The path gets expand automatically after using the default config.Maybe my incorrect zoxide config leads to this problem.
- I cannot access that file with bash.
![20221110_14h53m04s_grim](https://user-images.githubusercontent.com/86193029/201021233-b121b2b7-7815-4e49-8226-ffc5d118c13f.png)
I now close this issue,since it's nothing to do with nushell.
Thanks for your all help.
