### ISSUE TITLE
Replacing `$env.HOME` with just '~' in the prompt path

### ISSUE THREAD

**Issue by MichaelScofield45** [nushell/nushell#7036]
### Related problem

This is a very small change but in my opinion I think that the current shell path displayed would look better like this:
`~/foo/bar`
instead of the default:
`/home/<user>/foo/bar`

### Describe the solution you'd like

In the `env.nu` file located at `$nu.env-path` when defining `create_left_prompt []` change the line that says:
`$"(ansi green_bold)($env.PWD)"`
with:
`$"(ansi green_bold)($env.PWD | str replace $"($env.HOME)" '~')"`

This approach would still leave the full unaltered path when the user is using the `root` user. It will also omit any future patterns that also match `/home/<user>` since the `-a` flag is not given to `str replace` and thus will only match the first instance and return the string.

If there is any problem or it does not align with what `nushell` is trying to do then I completely understand.

**Comment by sholderbach** [comment]
This has thankfully been implemented for a little while in our default configuration.
