### ISSUE TITLE
Some commands that require a parameter (like open) output their help when run as-is, but others (like mkdir) return an Error

### ISSUE THREAD

**Issue by raccmonteiro** [nushell/nushell#7048]
### Describe the bug

Some commands that require a parameter output their help when run as-is, but others return an Error.

Some commands with Error:
- mkdir
- rm
- which
- touch

### How to reproduce

```
〉open
Usage:
  > open {flags} (filename)

Flags:
  -h, --help - Display this help message
  -r, --raw - open file as raw binary

Parameters:
  (optional) filename <Filepath>: the filename to use

Examples:
  Open a file, with structure (based on file extension or SQLite database header)
  > open myfile.json

  Open a file, as raw bytes
  > open myfile.json --raw

  Open a file, using the input to get filename
  > echo 'myfile.txt' | open

  Open a file, and decode it by the specified encoding
  > open myfile.txt --raw | decode utf-8


〉mkdir
Error: nu::shell::missing_parameter (link)

  × Missing parameter: requires directory paths.
   ╭─[entry #72:1:1]
 1 │ mkdir
   · ──┬──
   ·   ╰── missing parameter: requires directory paths
   ╰────

```
### Expected behavior

I expect all commands that require subcommands to output their help when run without a subcommand.

### Screenshots

![image](https://user-images.githubusercontent.com/3062698/200311265-6267f5b5-c95a-41e8-bb21-df946eb27923.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

Probably this needs more analysis to find which commands are wrong and need a fix, a table with this info and who is working on each command and if there is already fixed.

**Comment by webbedspace** [comment]
Yeah, I know, right??

**Comment by ricardoCMonteiro** [comment]
> Yeah, I know, right??

This is somewhat related to https://github.com/nushell/nushell/issues/6844, but I thought the #6844 addressed only commands that give no results and no Error.
If you think it is the same, this can be closed.

**Comment by webbedspace** [comment]
No, I'm just agreeing with you. I was thinking just earlier that it was kind of weird for only those commands to display help when used improperly.

On the other hand… isn't the help actually just a string? Maybe having them return help at all is a bad idea because of how it changes their return signature.

Thinking about it, maybe those commands should simply have better errors that advise on the usual necessary subcommands instead of returning the `help` messages as-is.

**Comment by ricardoCMonteiro** [comment]
Yes probably that should be the better approach, it should give an error when we invoke a command wrongly.
So it should be the opposite of this Issue, right? It should give an error when there are missing parameters instead of displaying the help message. `open` should give an error.

**Comment by weirdan** [comment]
`open` no longer shows the help message (probably because it doesn't have any subcommands now).

**Comment by sholderbach** [comment]
Did a brief search for `get_full_help` and its only the stub super commands that still use it.
