### ISSUE TITLE
Negative filesize literals like `-120b` cause numeric overflow

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7055]
### Describe the bug

See title.

### How to reproduce

```
〉-120b
340282366920938432.0 ZB
```

### Expected behavior

I expect negative filesizes to work correctly (I can see them being useful for things like file deltas, comparing sizes of two files before and after update, etc.)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        | 9ef65dcd692b502d7476b1787247fae8638c2f0c        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.0                                          |
| build_time         | 2022-10-18 18:55:02 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by dmatos2012** [comment]
This looks like fun, Id like to give it a try :)
