### ISSUE TITLE
Missing test coverage for argument type checking

### ISSUE THREAD

**Issue by dandavison** [nushell/nushell#7057]
### Describe the bug

At https://github.com/nushell/nushell/commit/7400a4ab9bab99548bb18730c0dc8d171e81d7c7 the full test suite passed, but the following was a type mismatch error:

```
def fn [t: table] {}
fn [{a:a}]
```

The full test suite should not have passed with that.

### How to reproduce

```
git checkout 7400a4ab9bab99548bb18730c0dc8d171e81d7c7
cargo build
./target/release/nu
def fn [t: table] {}
fn [{a:a}]
```

You'll see an error

```
Error: nu::parser::type_mismatch (link)

  × Type mismatch.
   ╭─[entry #6:1:1]
 1 │ fn [{a:a}]
   ·    ───┬───
   ·       ╰── expected Table([]), found List(Any)
   ╰────
```

### Expected behavior

The full test suite should not have passed with bug present.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.1                                          |
| branch             | input-output-syntax-shape                       |
| commit_hash        | 15b2e8311002cd30fa6091c7859f2a06ccc0cd96        |
| build_os           | macos-x86_64                                    |
| build_target       | x86_64-apple-darwin                             |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)             |
| rust_channel       | 1.64.0-x86_64-apple-darwin                      |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.70.1                                          |
| build_time         | 2022-11-07 08:50:56 -05:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by webbedspace** [comment]
To be clear, `[{a:a}]` is a valid table, so the error is wrong.

**Comment by sholderbach** [comment]
Can not reproduce anymore after significant work has gone into the typechecking.
