### ISSUE TITLE
Consider disabling `save` with a `.html` extension automatically invoking `to html`

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7078]
### Related problem

```
〉`<!DOCTYPE html><html><body><a href='http://example.org/'>Example</a></body></html>` | save temp.html | open temp.html
<html><style>body { background-color:white;color:black; }</style><body>&lt;!DOCTYPE html&gt;&lt;html&gt;&lt;body&gt;&lt;a href=&#x27;http://example.org/&#x27;&gt;Example&lt;/a&gt;&lt;/body&gt;&lt;/html&gt;</body></html>
〉`<!DOCTYPE html><html><body><a href='http://example.org/'>Example</a></body></html>` | save temp.txt | open temp.txt
<!DOCTYPE html><html><body><a href='http://example.org/'>Example</a></body></html>
〉`<!DOCTYPE html><html><body><a href='http://example.org/'>Example</a></body></html>` | save temp.htm | open temp.htm
<!DOCTYPE html><html><body><a href='http://example.org/'>Example</a></body></html>
```
My grievances:
* Most use-cases of saving with the `.html` extension are likely to involve editing existing HTML files (retrieved via `fetch` or `open`) rather than dumping a table, so having to use `--raw` for each of those feels like a UX sharp pointy edge.
* `to html` is rather bad as an output format anyway, because Nushell cannot read it (contrast `to toml`, `to csv` etc.) and thus it's basically "lossy", so having this as a `save` default doesn't seem to have advantages in the same way that, say, .toml does.
* Does not work with the `.htm` extension (due to the command `to htm` not existing) so this behaviour isn't even entirely reliable.

### Describe the solution you'd like

I think this particular case (for the `html` extension) should be explicitly removed from `save`. The other `to` outputs can remain (although `to md` should get some scrutiny as well.)

**Comment by Decodetalkers** [comment]
Yes, same when save to .json

I think when use "save", it should save as row text, should not to guess what the text is, unless when it is from nushell object and use `from`

**Comment by webbedspace** [comment]
I personally think saving to .json is fine… if you open that .json file, you get the same data back. The same cannot be said of .html.

Actually… here's a proposition: if `save` is given a single string, it should not do any `from` transformations, regardless of file extension. That'd follow most intuitions, right? And when given a structure, it uses `from` to turn it into a string.

**Comment by Decodetalkers** [comment]
> I personally think saving to .json is fine… if you open that .json file, you get the same data back. The same cannot be said of .html.
> 
> Actually… here's a proposition: if `save` is given a single string, it should not do any `from` transformations, regardless of file extension. That'd follow most intuitions, right? And when given a structure, it uses `from` to turn it into a string.

Not fine at all I think :(
![image](https://user-images.githubusercontent.com/60290287/201044978-5aa2105b-93be-4653-b641-84f9448eb72d.png)

**Comment by webbedspace** [comment]
Well, one Nushell principle is that you need to always run `from json` when given output of an external command that's in that format - Nushell doesn't have auto-detection (and can't because various formats are JSON supersets, such as YAML and Nuon). If you insert `from json |` before the `save`, it's fine.

**Comment by fdncred** [comment]
I agree that this is a paper cut, and I *always* get cut with it. I personally really despise having to do `save --raw`. I really wish nushell could be smart enough to not require this except in rare circumstances.

I'd rather your html example and Reilly's json example just work, without extra commands. Maybe others feel different.

**Comment by rgwood** [comment]
I also agree that this is a paper cut. Not totally sure what the best way forward is, it would be nice to have consistent behaviour instead of an exception for HTML.

**Comment by Kixunil** [comment]
TBH I find all automatic conversions to be potential footguns and I'd prefer them not being applied at all. "Explicit is better than implicit" as they say.

**Comment by fdncred** [comment]
I'm kind of starting to lean the same way @Kixunil.

**Comment by webbedspace** [comment]
This got merged, right?
