### ISSUE TITLE
Interactive tree viewer to explore large trees

### ISSUE THREAD

**Issue by dbarnett** [nushell/nushell#708]
It would be really useful to have an interactive tree view to explore large trees where you could collapse/expand subtrees.

**Comment by jonathandturner** [comment]
Agreed, this would be a great viewer to have. Happy to mentor someone if they want to take this on.

**Comment by andrasio** [comment]
#900

**Comment by Delapouite** [comment]
`broot` is a nice CLI program dedicated to fast tree walking/filtering: https://dystroy.org/broot/
It could serve as a source of inspiration for the design of this feature.
