### ISSUE TITLE
`rename` for filters accepts only single specific column

### ISSUE THREAD

**Issue by theAkito** [nushell/nushell#7085]
### Related problem

This works.
```nushell
[[a, b, c]; [1, 2, 3]] | rename -c [a ham]
```

But this does not.

```nushell
[[a, b, c]; [1, 2, 3]] | rename -c [a ham] -c [c chicken]
```

Neither does this.

```nushell
[[a, b, c]; [1, 2, 3]] | rename -c [[a ham] [c chicken]]
```

### Describe the solution you'd like

It'd be great, if the command's flag `-c` would accept a list of pairs (list of lists with exactly two items) as its argument.

Alternatively, let the command accept the flag `-c` multiple times, though I doubt this fits the general design, so I guess the former solution proposal should do it.

### Describe alternatives you've considered

Alternatively, one may chain the `rename` command lots of times, however this is not only un-ergonomic & bloated, but also not programmable. (At least, I did not find a way how to chain the `rename` command programmatically.)

### Additional context and details

This is another step in my effort of finding unprogrammable loop holes in Nu.

[`rename` for filters Documenation](https://www.nushell.sh/book/commands/rename.html#frontmatter-title-for-filters)

**Comment by fdncred** [comment]
alternatively you could just do this
```
[[a, b, c]; [1, 2, 3]] | rename ham b chicken
```

**Comment by theAkito** [comment]
> [[a, b, c]; [1, 2, 3]] | rename ham b chicken

No, [this does not work](https://github.com/nushell/nushell/issues/7033).

> [[a, b, c]; [1, 2, 3]] | rename -c [a ham] | rename -c [c chicken]

Yes, this is the alternative I have described in the issue. As already mentioned, it's not a valid alternative.

**Comment by fdncred** [comment]
> No, this does not work.

I'm not sure what you're saying doesn't work. Clearly, this example below works. I don't see any `rename` in the link you posted.
```
[[a, b, c]; [1, 2, 3]] | rename ham b chicken 
╭───┬─────┬───┬─────────╮
│ # │ ham │ b │ chicken │
├───┼─────┼───┼─────────┤
│ 0 │   1 │ 2 │       3 │
├───┼─────┼───┼─────────┤
│ # │ ham │ b │ chicken │
╰───┴─────┴───┴─────────╯
```

>  it's not a valid alternative.

why is it not valid?

**Comment by theAkito** [comment]
> I'm not sure what you're saying doesn't work. Clearly, this example below works. I don't see any `rename` in the link you posted.

It does not work.

### `test1.nu`
```nu
let b = [ham b chicken]
[[a, b, c]; [1, 2, 3]] | rename ($b | str join (char space))
```

### Shell
```nu
nu test1.nu
╭───┬───────────────┬───┬───╮
│ # │ ham b chicken │ b │ c │
├───┼───────────────┼───┼───┤
│ 0 │             1 │ 2 │ 3 │
╰───┴───────────────┴───┴───╯
```

### `test2.nu`
```nu
let b = [ham b chicken]
[[a, b, c]; [1, 2, 3]] | rename $b
```

### Shell
```nu
nu test2.nu
Error: nu::parser::type_mismatch (link)

  × Type mismatch.
   ╭─[test.nu:5:1]
 5 │ let b = [ham b chicken]
 6 │ [[a, b, c]; [1, 2, 3]] | rename $b
   ·                                 ─┬
   ·                                  ╰── expected String, found List(String)
   ╰────

```

This does not work. As I explained in this issue and in the other issue, there is no fully programmatic way of achieving this.

**Comment by fdncred** [comment]
Correct, there is no way to pass `$b` as a parameter to `rename`. However, it could be changed to support that. 

Your example above said nothing about a programmatic solution like you just described. So, that's why I was confused.

**Comment by theAkito** [comment]
> Your example above said nothing about a programmatic solution like you just described. So, that's why I was confused.

I'm sorry for the confusion. I'll try to rephrase better next time.

```nu
[[a, b, c]; [1, 2, 3]] | rename -c [[a ham] [c chicken]]
```

This is the programmatic way I think would be reasonable in the context of Nu's philosophy. A list of pairs, so a variable table can have variable column names variably changed. 🙂

**Comment by webbedspace** [comment]
To me the issue here is that there's apparently no way to "spread" lists into rest parameters. If an `...` operator like this existed (similar to `...` in JS and `*` in Python and Ruby(?)), this issue would be instantly resolved:
```
〉let b = [ham b chicken]
〉[[a, b, c]; [1, 2, 3]] | rename ...$b
```

**Comment by WindSoilder** [comment]
I'd like to propose the type of `-c` flag to be a record, so we can rename easily by some columns:
```nushell
[[a, b, c]; [1, 2, 3]] | rename -c {a: ham}
# or somethine like this:
[[a, b, c]; [1, 2, 3]] | rename -c {a: ham, c: ber}
```

**Comment by fdncred** [comment]
@WindSoilder I'm ok with that.
