### ISSUE TITLE
Need better parser error for mistyped conditions

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#709]
Eg)

```
/home/jonathan> ls | where name==Public
error: Expected a condition
- shell:1:11
1 | ls | where name==Public
  |            ^^^^^^^^^^^^ where needs a condition
```

To someone not expecting that the spaces are required that will be confusion. Originally reported on [reddit](https://www.reddit.com/r/rust/comments/d8rz5v/nushell_030/f1dwgne/)

**Comment by andrasio** [comment]
#900

**Comment by olamiko** [comment]
@jonathandturner, is this still open or done already?

**Comment by thegedge** [comment]
Hard to say if it's better or not, but it changed:

```
❯ ls | where name==Public
error: Unknown column
- shell:1:23
1 | ls | where name==Public
  |            ^^^^^^^^^^^^ did you mean 'name'?
```

Could probably either a) provide a better suggestion, or b) let that parse.

**Comment by jonathandturner** [comment]
I think we want that to have a better suggestion. Let them know that everything needs spaces (so they don't get used to not using them and then get confused when they're required)

@olamiko - sorry for the long delay, if you're still interested in this I'd be happy to help you with it.

**Comment by olamiko** [comment]
@jonathandturner, I am still interested. I will have a look at the error reporting module. Do you know where it is located?
