### ISSUE TITLE
Have commands signatures types in the same format as describe cmd

### ISSUE THREAD

**Issue by hbt** [nushell/nushell#7090]
### Related problem

`help commands | get signatures`

returns 
```
String => String
List(Any) => Boolean
Table => Boolean
List(Any) => List(Any)
Nothing => Nothing
List(Filesize) => List(Filesize)
```

where as `describe` cmd returns data types in a different format e.g `ls | get size | describe`

```
list<filesize>
```

This also makes automated discovery/search difficult. 

### Describe the solution you'd like

Both `describe` and `help commands | get signatures` should have the same format (regardless of which format we pick) to facilitate searching.

**Comment by rgwood** [comment]
Hi, please include the Nu version you're running in issues, as requested in the issue template.

It looks like you're running a prerelease version of Nu from the `main` branch. The input/output type information is very new and subject to change.

Agreed that we should make the format consistent.

**Comment by hbt** [comment]
@rgwood Thank you. 

Enclosed the version

```
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.71.1                                   |
| branch             | main                                     |
| commit_hash        | b650d1ef7963df3a57c89d0ae849ec8ad7b1d5a3 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)      |
| rust_channel       | 1.63.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)      |
| pkg_version        | 0.71.1                                   |
| build_time         | 2022-11-11 06:18:34 -05:00               |
| build_rust_channel | debug                                    |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |
```

Please note the feature request template doesn't mention version anywhere. 

https://github.com/nushell/nushell/issues/new?assignees=&labels=enhancement&template=feature_request.yml

However, the bug report template does.  https://github.com/nushell/nushell/issues/new?assignees=&labels=&template=bug_report.yml
