### ISSUE TITLE
Improve Error Message

### ISSUE THREAD

**Issue by theAkito** [nushell/nushell#7091]
### Describe the bug

I'm sometimes a bit confused by some terse error messages.

For example, as seen & explained in the following Pull Request, the user gets a `no valid paths` error message, if the path leads to a non-existent file.

https://github.com/nushell/nushell/issues/6810

I just spent half an hour trying to figure out the meaning of that message, until I found out that it just means, the file does not exist.

### How to reproduce

```
rm -v 'some-non-existent-file'
```

### Expected behavior

It would be extremely helpful, if this (and probably other ones from other commands) error message would be improved.
For example, when a file for `rm` does not exist, it should tell the user, that the `file does not exist` or something.
Since `no valid paths` sounds like I am trying to delete `/dev/null` or trying to walk over an ocean by foot...

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.71.0                                          |
| branch             |                                                 |
| commit_hash        | 6cc4ef6c706ebbdc5b995013e0b00f77f7a4dba7        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)             |
| pkg_version        | 0.71.0                                          |
| build_time         | 2022-11-08 18:00:26 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

It probably would be helpful, if error messages would generally be improved. I see confusing & misleading error messages pretty frequently in Nu.

A little bit related to https://github.com/nushell/nushell/issues/7048.

**Comment by rgwood** [comment]
Agreed that that error message should be cleaned up, I've submitted a PR.

> I see confusing & misleading error messages pretty frequently in Nu.

Yes, Nu's error messages could be more clear sometimes. Please file issues for bad error messages as you find them.
