### ISSUE TITLE
Uniq should accept column name

### ISSUE THREAD

**Issue by adamijak** [nushell/nushell#7109]
### Related problem

Right now we are not able to filter on specific column using uniq.

### Describe the solution you'd like

Uniq should accept column name

**Comment by rgwood** [comment]
Can you please provide an example of how you want `uniq` to behave?

**Comment by fdncred** [comment]
@adamijak I saw this the other day in discord and it kind of sounds like what you're looking for.
```
# Returns a filtered table that has distinct values in the specified column
def uniq-by [
  column: string  # The column to scan for duplicate values
] {
  reduce { |item, acc|
    if ($acc | any { |storedItem|
      ($storedItem | get $column) == ($item | get $column)
    }) {
      $acc
    } else {
      $acc | append $item
    }
  }
}
# how to use uniq-by
# let people = [
#   {name: 'A', email: 'a@a.a'},
#   {name: 'a', email: 'a@a.a'},
#   {name: 'b', email: 'b@b.b'}
# ]
# $people | uniq-by email
```

**Comment by raccmonteiro** [comment]
Should this be implemented to a new command? If so, I would like to do it

**Comment by fdncred** [comment]
we have `sort` and `sort-by`, so I'm not sure why we wouldn't have `uniq` and `uniq-by`, although I have no doubt that some will object to it. so, you should probably wait until others give their input.

**Comment by fdncred** [comment]
I'm not sure what @adamijak's use case is but that script I posted above was from discord's #cool-scripts and it seems to work like this.
```
ls | uniq-by type
╭───┬────────────────────────┬─────────┬──────────┬──────────────╮
│ # │          name          │  type   │   size   │   modified   │
├───┼────────────────────────┼─────────┼──────────┼──────────────┤
│ 0 │ Apps                   │ dir     │ 12.0 KiB │ a month ago  │
│ 1 │ Documents and Settings │ symlink │      0 B │ 2 years ago  │
│ 2 │ DumpStack.log          │ file    │ 12.0 KiB │ 7 months ago │
╰───┴────────────────────────┴─────────┴──────────┴──────────────╯
```
and here's the example they posted with it
![image](https://user-images.githubusercontent.com/343840/202227084-9c6012bb-958c-4666-a18b-ebf3fe169eeb.png)

I agree that it would be nice to have real-world use cases and the other information Reilly requested.

**Comment by raccmonteiro** [comment]
what about the reverse, get the rows with duplicated value in some column? Is there any way to do this?
Using the example above, if you have some file with name, email, birthday, address, ... you could want to get all rows with duplicated emails to analyze and merge person data manually.
So having some command to get duplicates, or using `uniq-by` and then filter again to get all results except then ones in `unique-by`.
What do you think?

**Comment by adamijak** [comment]
My use case was already mentioned by @fdncred. A wanted to get records uniquely by email. As I am thinking about it now, maybe getting email rown using `uniqe` would be enough.

PS: Sorry for long response
