### ISSUE TITLE
Documentation for Nu commands (NO programming experience needed)

### ISSUE THREAD

**Issue by andrasio** [nushell/nushell#711]
We need documentation for the following Nu internal commands in any speaking language of your choosing: 

If interest in working on a command, [please read this first](https://github.com/nushell/nushell/blob/master/docs/commands).

Please note: These are **Nu commands**, they may be the same name as commands you might be familiar from other shells but their usage, flags, and functionality might be different. Please make sure you have latest Nu installation `0.4.0` (you can confirm this by running the `version` command under Nu).

You can learn more about how a **Nu command** works by looking at the source code or from Nu itself running `help command` where `command` is the command you are interested in documenting.

VERY IMPORTANT you try and experiment with the command using Nu to get ideas.
(Updated 18th May, 2020)
- [ ] autoview
- [ ] binaryview
- [ ] clear
- [ ] cp
- [ ] describe
- [ ] drop
- [ ] each
- [ ] empty?
- [ ] keep
- [ ] keep-until
- [ ] keep-while
- [ ] kill
- [ ] match
- [ ] merge
- [ ] mkdir
- [ ] mv
- [ ] n
- [ ] p
- [ ] parse
- [ ] post
- [ ] pwd
- [ ] range
- [ ] rm
- [ ] shuffle
- [ ] skip-until
- [ ] split-by
- [ ] table
- [ ] textview
- [ ] touch
- [ ] tree
- [ ] with-env

**Comment by marcelocg** [comment]
I'm picking `date`

**Comment by yahsinhuangtw** [comment]
I'm picking `help`

**Comment by DaGuich** [comment]
I'm picking `echo`

**Comment by notryanb** [comment]
I'll grab `first` if that's okay. What about documenting plugins that are included in `help<command>` like `sum`?

**Comment by jonathandturner** [comment]
@notryanb - those would be good to document, too

**Comment by akramkazmi71** [comment]
I would like to provide document for tree command

**Comment by CDRayn** [comment]
If no one minds. I'd like to work on documenting the `which` command.

**Comment by codingonHP** [comment]
Can I take `clip` command.

**Comment by andrasio** [comment]
@CDRayn go ahead!

**Comment by andrasio** [comment]
@codingonHP no problem!

**Comment by andrasio** [comment]
@akramkazmi71 thanks!

**Comment by gilesv** [comment]
I'm picking `where`.

**Comment by garrettqmartin8** [comment]
I'll pick up `ps`

**Comment by pema99** [comment]
I'll whip up some documentation for the `lines` command.

**Comment by coolshaurya** [comment]
the commands `reverse`, `shells`, `version`, `exit`, `first` and, `where` are not checkmarked on the main issue comment although they [exist in the repo](https://github.com/nushell/nushell/tree/master/docs/commands). 

The commands `clip` and `which` are checkmarked even though they are not yet on the repo.

**Comment by coolshaurya** [comment]
I am doing `edit`

**Comment by Charles-Schleich** [comment]
Cool I will do `env` !

**Comment by mfarberbrodsky** [comment]
I'll take `nth`.

**Comment by sdfnz** [comment]
I'll do `sum`.

**Comment by Charles-Schleich** [comment]
I'm going to do sort-by .

**Comment by roeeyn** [comment]
Hey 👋  I'll pick up Docker 🐳

**Comment by oknozor** [comment]
i am picking `from-csv` !

**Comment by oknozor** [comment]
Sorry it seems I messed up referencing the issue. 
I did `from-toml` to by the way.

**Comment by coderkalyan** [comment]
I'll try from_json!

**Comment by loksonarius** [comment]
Nabbing `tags` real quick

**Comment by andrasio** [comment]
#900

**Comment by cauimsouza** [comment]
I'm picking "size"

**Comment by tchak** [comment]
I am working on `compact` and `default`. It seems they are not in the list.

**Comment by andrasio** [comment]
> I am working on `compact` and `default`. It seems they are not in the list.

Thanks! In the list now.

**Comment by pulpdrew** [comment]
I've got skip and skip-while

**Comment by thegedge** [comment]
❤️ to you all helping us out with documentation

**Comment by jzaefferer** [comment]
comparing `docs/commands/` and `crates/nu-cli/src/commands/`, these 32 commands are still missing docs:

autoview,binaryview,clear,cp,describe,drop,each,empty?,keep,keep-until,keep-while,kill,match,merge,mkdir,mv,n,p,parse,post,pwd,range,rm,run_external,shuffle,skip-until,split-by,table,textview,touch,tree,with-env

Some `to` and `from` subcommands as well as plugins are probably missing, too; haven't checked those.

**Comment by jonathandturner** [comment]
@jzaefferer - thanks! I've updated the main list on the issue with the latest

**Comment by jonathandturner** [comment]
@andrasio - is there a way to get the latest list of commands that need docs?

**Comment by andrasio** [comment]
@jonathandturner Afraid not.

**Comment by jonathandturner** [comment]
Let's go ahead and close this, and we can reopen when we can get a list
