### ISSUE TITLE
cargo install fails with error[E0658] on Ubuntu 22.04

### ISSUE THREAD

**Issue by adrianstaniec** [nushell/nushell#7118]
### Describe the bug

nu doesnt compile with cargo

### How to reproduce

`cargo install nu`

### Expected behavior

nu shell gets installed

### Screenshots

![image](https://user-images.githubusercontent.com/15216366/201486087-93670c88-3a00-42ea-bc47-7121ddfdde75.png)

### Configuration

N/A

**Comment by sholderbach** [comment]
Thanks for the report! Yeah we have currently several issues with how our crate/workspace/toolchain settings interact with `cargo install`

`cargo +stable install --locked` should work for now if you want to experiment right away.

**Comment by sholderbach** [comment]
Ah I assume you are using `apt install cargo`. Depending on the version what is available there `bool::then_some()` might not be stabilized.

**Comment by Decodetalkers** [comment]
You should use rustup to install rust rust-tooolchain over 1.63

**Comment by adrianstaniec** [comment]
Thanks for responding quickly.

I've removed my rust installation.
I installed again via rustup.

 when I've tried
` cargo install nu`
I've got:
![image](https://user-images.githubusercontent.com/15216366/201514388-160eab64-75c2-4237-9a79-5dafe7588b53.png)

when I've tried:
`cargo +stable install nu --locked`
I compiled and installed succesfully :)
