### ISSUE TITLE
nohup and & can not be background process when the command finished

### ISSUE THREAD

**Issue by jhxud** [nushell/nushell#7129]
### Question

I have defined the function:
```
def start-proxy [] {
    nohup /usr/local/bin/ss-local -c /etc/ss-local.conf 1>/dev/null 2>&1 &
    nohup /usr/local/bin/xray -c /etc/xray.json 1>/dev/null 2>&1 &
}
```
In bash, it will be background process when I call start-proxy. But in nushell, the behavior is different, it will not be background process and will wait there. So how can I to keel the behavior in nushell is the same as bash.

### Additional context and details

<img width="857" alt="截屏2022-11-14 14 40 32" src="https://user-images.githubusercontent.com/17818674/201592484-a27751f4-3c49-48e7-8afa-5e51e2916ad6.png">

**Comment by sholderbach** [comment]
As nushell runs it's own runtime to execute the builtins and user defined commands, the bash process level nohup doesn't directly translate to nushell. We currently haven't implemented task backgrounding (nohup, fork with `&`) or pausing (`Ctrl-z`) yet. I think this is a goal to be implemented in the future.

The bash file descriptor redirection syntax for the pipeline streams is probably not coming to nushell as we have additional complexities in the pipe. (currently we have the `do` and `complete` command for some of that but that area is a bit in flux)

**Comment by jhxud** [comment]
Thanks, got it!

**Comment by wangjiawen2013** [comment]
@sholderbach @chroniflux 
Hi,
I met this issue too, is there any progression now ?

<img width="1167" height="165" alt="Image" src="https://github.com/user-attachments/assets/d98bf3ac-ba47-44f6-b656-dd583c09df33" />
