### ISSUE TITLE
Change command help text to a record instead of normal text

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#7131]
### Related problem

Instead of using the tired old bash help text, I thought it may be interesting to update it to use nushell tables or records.

### Describe the solution you'd like

This is an example of the command `help str distance` with the help text as a record. Maybe it should have `command name | str distance` somewhere?, and obviously the upcoming input/output information https://github.com/nushell/nushell/issues/7079.

```
╭──────────────┬─────────────────────────────────────────────────────────────────────────╮
│ Help Text    │ Compare two strings and return the edit distance/Levenshtein distance   │
│ Search Terms │ edit, levenshtein                                                       │
│ Usage        │ str distance <compare-string> ...(rest)                                 │
│ Flags        │ -h, --help - Display the help message for this command                  │
│ Parameters   │ compare-string <String>: the first string to compare                    │
│              │ ...rest <CellPath>: For a data structure input, check strings at the    │
│              │  given cell paths, and replace with result                              │
│ Examples     │ get the edit distance between two strings                               │
│              │ > 'nushell' | str distance 'nutshell'                                   │
│              │ Compute edit distance between strings in record and another string,     │
│              │  using cell paths                                                       │
│              │ > [{a: 'nutshell' b: 'numetal'}] | str distance 'nushell' 'a' 'b'       │ 
╰──────────────┴─────────────────────────────────────────────────────────────────────────╯
```

### Describe alternatives you've considered

We may be able to draw it prettier and maybe it needs spacing between some commands, not sure exactly.

**Comment by theAkito** [comment]
Shouldn't this be a table?

It would also be great, if the examples were actually a list of executable statements or expressions, instead of descriptions wrapping them. This way, one would be able to execute the examples programmatically.

**Comment by WindSoilder** [comment]
There is one more case to consider, what if we have two commands have the same name?  

I'm not sure if it's allowed in nushell, but currently `help command` considered this case

**Comment by webbedspace** [comment]
Thought: Shouldn't the Flags be a record, and the Examples a list?

Concerns about rendering make me wonder if there shouldn't be a new viewer different from `table` for viewing nested records like this, one that outputs something a little closer to the current `help` output. That way, the data is still structured, but the output remains document-like.

I imagine something like this algorithm:

Algorithm Prose(Depth: int)
* When given a record, for each entry:
** Draw the key as a title in a color based on Depth
** Draw the value under it, indented, using Prose(Depth+1)
* When given a list, for each entry:
** Draw each value using Prose(Depth)

**Comment by sholderbach** [comment]
I think this has been resolved as we have the structured information inside `scope commands` for digging deep, @amtoine was also able to implement a pretty faithful help for the std-library based on such information. Furthermore our help output recently leverages an additional "table" visual for the input output type.
