### ISSUE TITLE
`table -e` doesn't always list all entries in nested tables, and sometimes collapses them even if there's some room

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#7145]
### Describe the bug

Assuming you have something like this `default_theme` in your config.nu file
![image](https://user-images.githubusercontent.com/343840/202254487-bd5b4de3-1ef8-4cea-b978-73d3254b6405.png)
Assuming you have this hook (I'm assuming the hook isn't to blame, but I'm also not ruling that out)
```
      display_output: {
        if (term size).columns > 100 { table -e } else { table }
      }
```
Now if your terminal is maximized and I type `$nu`, I get this.
![image](https://user-images.githubusercontent.com/343840/202254725-d2e62580-ef25-44eb-9532-f7e5a17ee477.png)
Notice that there are more items in the default_theme than are rendered in the table.

Now, in Windows Terminal I hit ctrl+- to make my font smaller, to see what happens. Even though I now have more room, I noticed that this entire table is:
1. entirely collapsed
2. has a different row number (this is not a big issue, I just point it out because it surprised me)
![image](https://user-images.githubusercontent.com/343840/202255172-90681d2e-d556-4451-900e-7727652c9de8.png)

I do ctrl+- again and the font gets smaller, there's more room, but $default_theme isn't expanded
![image](https://user-images.githubusercontent.com/343840/202255561-2eebb94e-fdfe-4f0a-9b5d-501f499e1be1.png)

I can also see something similar with `commands` (at normal zoom level)
![image](https://user-images.githubusercontent.com/343840/202255831-97ff9286-0b19-4137-a573-9252ae59e898.png)

Now zoomed out with ctrl+- twice and type `$nu` again. Now there are tables but there are more columns than are being shown.
![image](https://user-images.githubusercontent.com/343840/202256386-01673bbb-877a-4e47-b94b-834fb808a7e7.png)
For comparison, here's just the alias command
![image](https://user-images.githubusercontent.com/343840/202256736-7bac3e70-f54d-4562-b7e0-a585ca8844f8.png)

I believe this is related to #6885

### How to reproduce

See above

### Expected behavior

I definitely understand that parsing and representing all this data in a coherent way is not trivial. However, when I discovered this, my initial thought was that tables should be drawn in such a way that when there is not enough room for columns, the truncation column `...` should be shown.

### Configuration

|key|value|
|-|-|
|version|0.71.1|
|branch|main|
|commit_hash|ef32e1ce1ac68eb99cdbaef49e381d2e9b179f2e|
|build_os|windows-x86_64|
|build_target|x86_64-pc-windows-msvc|
|rust_version|rustc 1.63.0 (4b91a6ea7 2022-08-08)|
|rust_channel|1.63.0-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.63.0 (fd9c4297c 2022-07-01)|
|pkg_version|0.71.1|
|build_time|2022-11-11 15:25:04 -06:00|
|build_rust_channel|release|
|features|database, dataframe, default, trash, which, zip|
|installed_plugins|custom-value generate, custom-value generate2, custom-value update, gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml|

### Additional context

/cc @zhiburt

**Comment by zhiburt** [comment]
> However, when I discovered this, my initial thought was that tables should be drawn in such a way that when there is not enough room for columns, the truncation column ... should be shown. 

Clearly was a bug.
Could you verify the fix?

> Notice that there are more items in the default_theme than are rendered in the table.
> has a different row number (this is not a big issue, I just point it out because it surprised me)

This one is interesting.
I actually doubt it is related.

**Comment by zhiburt** [comment]
45 means a number of columns?

**Comment by fdncred** [comment]
Right, I realize there are a lot of columns. I was just expecting this with an extra `...` column.
![image](https://user-images.githubusercontent.com/343840/202274589-c78849de-4bb9-42f9-ba59-fdde86e82b07.png)

**Comment by fdncred** [comment]
I think this looks better now so I'm going to land it. I do have one question though.

This is the end of the $nu.scope.commands section
![image](https://user-images.githubusercontent.com/343840/202463287-bdb84159-e071-4537-9a2b-9c762a71a1d9.png)
I notice there are signatures and examples that *could* be expanded but we've chosen not to do that and put the `...` at the end. I'm totally good with this behavior. But my question is, what are the expansion rules. I mean, how does it know not to expand signatures and examples here?

**Comment by zhiburt** [comment]
> I notice there are signatures and examples that could be expanded but we've chosen not to do that and put the ... at the end. I'm totally good with this behavior. But my question is, what are the expansion rules. I mean, how does it know not to expand signatures and examples here?

Well as I've told
now in case if all elements in a column can be expanded and fit, we just don't do that.
And make the elements be in not expanded view.

*than actually we go further and in case if we can't even to that we try to wrap the content.
 It works good for general content BUT because of this we MAY wrap the default strings like `{record 15 elements}` etc. (which is not good in my opinion, but someone was lazy to write a check if the content is general or not)

**Comment by fdncred** [comment]
thanks. i'm sure i'll ask again. :)
