### ISSUE TITLE
configure cursor shape

### ISSUE THREAD

**Issue by Zaechus** [nushell/nushell#7151]
### Question

It looks like the new appearance for the cursor in vi_mode is a vertical line for insert mode and a block for normal mode. Is there a configuration option to revert to a block for all modes?

### Additional context and details

```
nu --version
0.71.0
```

**Comment by fdncred** [comment]
There is no config option yet, but it's planned.

**Comment by KSXGitHub** [comment]
At least exiting nu should revert the cursor to normal. But if nu can't know what the original cursor is, then I think this behavior should be disabled by default.

**Comment by fdncred** [comment]
FWIW, a PR has been started to make this configurable. https://github.com/nushell/reedline/pull/515

**Comment by AmionSky** [comment]
The https://github.com/nushell/reedline/pull/515 PR has been merged but I still couldn't find a way to configure it from nushell.
Also I strongly think by default nu shouldn't change the cursor set by the terminal.

**Comment by fdncred** [comment]
If you're on the latest main branch, you can configure it by adding this to your config.nu.
```
  cursor_shape: {
    vi_insert: underscore
    vi_normal: block
    emacs: line
  }
```
IIRC, I believe it will overwrite the terminal setting with or without setting this information. Maybe someone should look at that in the future. I'm just glad to get rid of the friggin block finally.

**Comment by warpdesign** [comment]
Just stumbled upon this issue: I'm not sure where to add the `cursor_shape` config? `config.nu` is huge and there are lots of entries. I tried pasting this at the end of the file but this resulted in an error.

**Comment by warpdesign** [comment]
Btw why doesn't `nu` use the shape defined by the terminal app and overwrites it?

**Comment by fdncred** [comment]
This change, I mentioned above, could go anywhere within the config section of the config.nu. You can identify this part of the config by finding `let-env config = {`. Anywhere before the last `}` would work.

So, you'd want something like, if you wanted it as the first thing in your config.nu.
```
let-env config = {
  cursor_shape: {
    vi_insert: underscore
    vi_normal: block
    emacs: line
  }
... all the rest of your config
}
```

You could also look at the `default_config.nu` in the repo, which shows where it goes.

> But why doesn't ...

It probably should but it doesn't yet.

**Comment by ahirner** [comment]
> Btw why doesn't nu use the shape defined by the terminal app and overwrites it?

[Reedline](https://docs.rs/reedline/latest/reedline/struct.CursorConfig.html) supports not modifying the cursor:

> If any of the fields is None, the cursor won’t get changed by Reedline for that mode.

I guess `nushell` should allow `null` in addition to 'line', 'block', or 'underscore'.

**Comment by amtoine** [comment]
> ```
>   cursor_shape: {
>     emacs: line # block, underscore, line, blink_block, blink_underscore, blink_line (line is the default)
>     vi_insert: block # block, underscore, line , blink_block, blink_underscore, blink_line (block is the default)
>     vi_normal: underscore # block, underscore, line, blink_block, blink_underscore, blink_line (underscore is the default)
>   }
> ```
> 
yes this is available now, i think we can close this issue as the question has been answered with time :relieved: 

> In vim, my cursor is a very fine line, and it's very difficult for me to see. I'm using version 0.81.0, installed with homebrew on MacOS.
>
this might have to do with your font? :thinking: 
my underscore is quite big enough!

**Comment by tomboland** [comment]
Hi,

Should I raise a new issue?  Using the same terminal emulator, but with bash, I see a large, bold, black cursor block, instead of this very thin vertical line.  See my screenshot; can you see the cursor at a glance?  It's on the `vi_insert` line: 
![image](https://github.com/nushell/nushell/assets/8832878/5a7e3ec6-baf9-4ff6-901b-8267a9d4908d)

**Comment by amtoine** [comment]
@tomboland 
mm i'd say this is a Vim issue :thinking: 

when i run Neovim i have a completely different cursor, it's not even switching from large to thin underscore, but rather between a vertical bar in Nushell and a block in NORMAL mode in Neovim :confused:

**Comment by mb21** [comment]
I'm confused. How does `$env.config.cursor_shape.vi_normal` relate to `$env.PROMPT_INDICATOR_VI_NORMAL`? Thanks!

**Comment by mb21** [comment]
@tomboland @amtoine I have the same and opened an issue: https://github.com/nushell/nushell/issues/10169

**Comment by nazmulidris** [comment]
On Windows, w/ `nu` v0.84.0, I had to add the following to my `config.nu` file

```nu
export-env { load-env {

    # https://github.com/nushell/nushell/issues/7151
    config: ($env.config? | default {} | merge {
        render_right_prompt_on_last_line: true,
        cursor_shape: {
            vi_insert: block
            vi_normal: block
            emacs: block
        }
    })

}}
```

**Comment by dedguy21** [comment]
I see that there are the two vi_insert & vi_normal. Is there also an option for vi_visual & vi_replace. I don't see it on the documentation.

**Comment by mb21** [comment]
@dedguy21 the `cursor_shape` `vi_insert` and `vi_normal` configs are not for inside vi/vim. They are for when nushell's prompt itself is set up to be in vim-like-mode (`edit_mode: vi`) – and that doesn't have visual or replace mode AFAIK.

**Comment by dedguy21** [comment]
@mb21  too bad, I was hoping it would be more like zsh/bash where the vi mode has VISUAL and REPLACE modes as well.

**Comment by mb21** [comment]
Yeah, you can like the upstream issue: https://github.com/kkawakam/rustyline/issues/335

**Comment by fdncred** [comment]
We don't use rustyline anymore.

**Comment by arsalanmohseni** [comment]
I want to change it anywhere, how do i do??
