### ISSUE TITLE
Windows prebuild archive structure changed.

### ISSUE THREAD

**Issue by eklmv** [nushell/nushell#716]
In 0.3.0 prebuild archive executables now nested in "nushell_0_3_0" folder, when in 0.2.0 there was just executables. What structure we can expect for future prebuild release archives?
I use [scoop ](https://github.com/lukesampson/scoop) as my "package manager" for windows and changing archive structure just brakes [my app manifest ](https://github.com/eklmv/scoop_bucket/blob/master/bucket/nushell.json) for nushell.

**Comment by jonathandturner** [comment]
That's from me doing it by hand. I'm hoping in the future to have this a bit more automated so it could be consistent. It wasn't my intention to change the structure between releases.

**Comment by eklmv** [comment]
Can you ping me when structure becomes "stable"?
Fixed my manifest to expect folder there. As soon as structure become stable, it will be convenient to add my manifest to [extras](https://github.com/lukesampson/scoop-extras) bucket, where it will be auto updating and available to scoop regular users.

**Comment by tehmantra** [comment]
Hijacking this issue to suggest creating an "official" scoop manifest.
I just spent ~30mins creating [my own app manifest](https://github.com/tehmantra/scoop-bucket/blob/master/bucket/nushell.json) for nushell.
This makes installing nushell super easy:
```sh
$ scoop install https://raw.githubusercontent.com/tehmantra/scoop-bucket/master/bucket/nushell.json
```

Ideally, as the project grows this could be merged to the extras bucket as @eklmv suggests, meaning any user could install it:
```sh
$ scoop bucket add extras
$ scoop install nushell
```

This will probably require the build/pack process to be a bit more stable.

In the mean-time, can I suggest we add a scoop app manifest to the nushell/nushell repo, as well as updating the install instructions for windows to reference this, so we can prevent more people from creating duplicate app manifests, as well as improving the install process for new users.
This is especially beneficial as they don't need to install rust, or manually add binaries to $PATH. 

Would be happy to open a PR for this if you feel it is beneficial.

**Comment by andrasio** [comment]
#900

**Comment by jonathandturner** [comment]
This should be more consistent now, closing.

@tehmantra - if you'd like to see scoop packages, we can start a new thread about that.
