### ISSUE TITLE
Utility commands for records: `values` and `pairs` (counterparts to `columns`)

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7166]
### Related problem

Splitoff from #6854. Various programming languages with key-value data structures (records) have three methods for extracting and iterating over their stored data: one for listing the keys, one the values, and one for listing tuples of each pair. Nushell, however, only has `columns`, which matches the former.

## `values`
`values` takes no arguments and produces the following:
* When piped a record, it produces a list containing, for each column (in order), each value in that column.
* When piped a list of records, it produces the same, but each value is a list (of the contents of that column).
* Errors with all other inputs.

Counterparts in other langs:
* Javascript `Object.values()`
* Python `values()`
* Ruby `Hash#values()`
* Dart `values`
* Rust `into_values()`

## `pairs` (other possible names: `entries`, `items`)
`pairs` takes no arguments and produces the following:
* When piped a record, it produces a {key,value} (or possibly a {column,value}) table. Similar to `transpose`, but with better resulting column names and type-checking.
* When piped a list of records, it produces a {key,value} table where each value is a list (of the contents of that column).
* Errors with all other inputs.

Counterparts in other langs:
* Javascript `Object.entries()`
* Python `items()`
* Lua `pairs()`

### Describe alternatives you've considered

I'm aware that these are rudimentary enough to be implemented as `def`s in config.nu. However, I feel like being able to rely on their presence in the language, independent of user config, is part of their charm.

I also privately think there should be an `each column` variant of `each` to be used with iteration (which would be very convenient with `group-by`'s output of a record of homogenous columns), and that `pairs` isn't actually ideal as the be-all-end-all of record iteration - but `pairs` does have uses outside of that case, which justify its existence.

### Additional context and details

`pairs` could produce a list of two-item lists of [key, value] instead of a table of {key, value} (or {column,value}), and it would be marginally more succinct to use in `each` (by referencing $in.0 and $in.1 instead of $in.key and $in.value) but I think the terseness would hinder readability. Plus, `pairs` output can be presented as a table to the viewer.

**Comment by webbedspace** [comment]
Thinking about `pairs` made me realise it has some striking similarities to the new `enumerate`. Do any of you think that, for consistency, the `{key,value}` records should perhaps be `{column,item}` (changing the second one to "item" instead)?

**Comment by fdncred** [comment]
I can't help but think of `pairs` as `kv` and producing `key` and `value` (probably won't happen), which makes me think `columns` should be named `keys` (probably won't happen). I also can't help thinking that enumerate should return index and item, as it does today. Maybe that is from working with nushell for so long that I can't get over myself to understand what may be more intuitive.

I'm interested in what others think too.

**Comment by zoechi** [comment]
What about `transpose`?

```sh
❯ 'https://www.smwcentral.net/?p=section&s=smwmusic&f[name]=vldc&f[author]=&f[tags]=&f[featured]=&f[description]=' | url parse | transpose 
 #   column0                                            column1                                         
────────────────────────────────────────────────────────────────────────────────────────────────────────
 0   scheme     https                                                                                   
 1   username                                                                                           
 2   password                                                                                           
 3   host       www.smwcentral.net                                                                      
 4   port                                                                                               
 5   path       /                                                                                       
 6   query      p=section&s=smwmusic&f[name]=vldc&f[author]=&f[tags]=&f[featured]=&f[description]=      
 7   fragment                                                                                           
 8   params      #      p         s       f[name]   f[author]   f[tags]   f[featured]   f[description]  
                ─────────────────────────────────────────────────────────────────────────────────────── 
                 0   section   smwmusic   vldc                           
```

**Comment by zoechi** [comment]
@webbedspace I missed, that you mentioned transpose already. I think I understand your request now.

What about adding a parameter to `columns --with-values` to get the columns paired with the values?
I'd prefer a distinct `entries` or `pairs` command though, but I find the names unintuitive for tables.
I also find `columns` unintuitive for records

@fdncred 
> I can't help but think of pairs as kv and producing key and value (probably won't happen)

Why do you think that it won't happen?

What do I need to do to get `enumerate`? It's not recognized by my Nushell
```sh
nu --version
0.75.0
```

**Comment by webbedspace** [comment]
Adding a flag is not recommended. `columns` returns a list, whereas `pairs` returns a table.

**Comment by fdncred** [comment]
> What do I need to do to get enumerate? It's not recognized by my Nushell

`enumerate` is part of 0.75.0

> Why do you think that it won't happen?

I just think there would be objections to the name `kv`

**Comment by sholderbach** [comment]
https://github.com/nushell/nushell/pull/8640 added the command `items` that works around the tuple problem by operating over a closure with two arguments in similar vain to `each`
