### ISSUE TITLE
Unable to run nu binaries on Ubuntu 19.04 w/o libssl1.0.0

### ISSUE THREAD

**Issue by sorrell** [nushell/nushell#717]
Having issues with Ubuntu 18.04 and nu needing different libc versions, I upgraded to 19.04. After upgrading and trying to run nu, I hit this error

`nu: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`

libssl1.0.0 isn't available via apt, so I had to install the deb manually (https://packages.ubuntu.com/cosmic/libssl1.0.0)

After installing the amd64 deb, all is well.

**Comment by jonathandturner** [comment]
There binary notes mention needing the dependencies (https://github.com/nushell/nushell/releases/tag/0.3.0) but they could be more clear. 

Would it be better to not use the "all features" build (which requires the ssl lib)?

**Comment by sorrell** [comment]
I am an admitted nu noob (nuub?), and those dependencies are clear, but as libssl1.0.0 wasn't available in the repos, I just wanted to throw this issue out there with steps on how to get it running on 19.04.  It wasn't a simple `apt install` is all, but no major hurdles.  What other builds exist than the "all features" build, and how do I run it? I didn't see info that, sorry if I missed it.

**Comment by jonathandturner** [comment]
Ah, that makes sense. Thanks for the clarification.

For the next release, we could do the default build, which has a few less features, but also has fewer system requirements.

If you like, I can create an additional linux release that's a default build.

**Comment by jetzerb** [comment]
I ran into this same issue, also on Ubuntu 19.04.  I downloaded the [0.4.0 release](https://github.com/nushell/nushell/releases/tag/0.4.0) of `nu` for [Linux](https://github.com/nushell/nushell/releases/download/0.4.0/nu_0_4_0_linux.tar.gz) and got an error message about not being able to find `libssl.so.1.0.0`.  I noticed that the library file was included in the release, so I updated my system cache via `ldconfig`.  `nu` then complained about not finding `libcrypto.so.1.0.0`.

To expand on @sorrell's comment regarding availability of libssl in Ubuntu:

Nickname | Version | 1.0.0 | 1.1
--- | --- | --- | ---
Xenial | 16.04 | X |
Bionic | 18.04 | X | X
Cosmic | 18.10 | X | X
Disco | 19.04 | | X
Eoan | 19.10 | | X

It would appear that v1.0 has been deprecated in Ubuntu, and that `nu` will have to utilize v1.1 if it is to function on that OS.

**Comment by andrasio** [comment]
#900
