### ISSUE TITLE
Discord link in CONTRIBUTING.md is invalid

### ISSUE THREAD

**Issue by ahgilbert** [nushell/nushell#7173]
### Describe the bug

Step 2 in the Review Process section of the contributing guide contains a link to the Discord. That link leads to a discord invite page showing member / online counts, but "Accept Invite" fails, saying "Whoops, Unable to accept invite"

### How to reproduce

Log out of Discord
Follow invite link in CONTRIBUTING.md
  (https://discordapp.com/invite/NtAbbGn as of `d01ccd5a5`)
Accept link

### Expected behavior

I expect to be able to join the Discord server.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.71.1                                   |
| branch             | main                                     |
| commit_hash        | 58d960d9140a987bc87bba7e069818938a8f9f84 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.63.0 (4b91a6ea7 2022-08-08)      |
| rust_channel       | 1.63.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.63.0 (fd9c4297c 2022-07-01)      |
| pkg_version        | 0.71.1                                   |
| build_time         | 2022-11-10 21:19:05 -06:00               |
| build_rust_channel | debug                                    |
| features           | default, trash, which, zip               |
| installed_plugins  |                                          |

**Comment by sholderbach** [comment]
Does https://discord.gg/NtAbbGn work for you? The shortlink code is still active in the server settings, so this might be a particular issue with discord?

**Comment by ahgilbert** [comment]
That link gives me the same result.

**Comment by sholderbach** [comment]
Mhh don't know what's going on, I saw new people joining the server over the last couple of days. I think our server settings should let anybody join with a Discord account with a verified email address.

**Comment by rgwood** [comment]
We haven't been able to reproduce this, sorry; we've had an influx of new users on Discord and we believe the link is valid. Might be best to try contacting Discord support.

If you've got questions for the team and can't join the Discord server, feel free to create issues or discussions on this repo.
