### ISSUE TITLE
Allow dashes in bare words

### ISSUE THREAD

**Issue by rirze** [nushell/nushell#719]
Hi, I encountered the following error when trying to use the SSH command:

```bash
/home/rirze(master)> ssh a@b-c
error: Parse Error
- shell:1:7
1 | ssh a@b-c
  |        ^^ 
```

Where I am really expecting this error:
```bash
/home/rirze(master)> ssh a@b-c
ssh: Could not resolve hostname a@b-c: Temporary failure in name resolution
```

Escaping with the `^` character doesn't help either. Any clarification would be appreciated!

**Comment by jonathandturner** [comment]
If you write this as `ssh "a@b-c"` does it work correctly?

It looks like we might have a bug in the parser.

**Comment by rirze** [comment]
Yes, `ssh "a@b-c"` works! 

Is this intended normal behavior-- should I be escaping parts of commands with quotes?

Thanks

**Comment by jonathandturner** [comment]
I think this is because Nu doesn't treat `-` as part of the argument. I suspect we should.

**Comment by andrasio** [comment]
#900

**Comment by jonathandturner** [comment]
This should work in the latest master
