### ISSUE TITLE
`ls` config option: default sort order of the table

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7190]
### Related problem

I'd like to change `ls`'s default sort order, for the purposes of casual file management. For instance, I prefer insensitive and natural sorting by name, and would like to have that available in the standard `ls`. Making an alias in `config.nu` like `alias ls = ls | sort-by size -r` doesn't really work for this use-case because you can't provide any further flags or args.

### Describe the solution you'd like

Currently config.nu's `ls` options look like this:
```
 ls: {
    use_ls_colors: true # use the LS_COLORS environment variable to colorize output
    clickable_links: true # enable or disable clickable links. Your terminal has to support links.
  }
```
I propose adding the following:
```
sort_by: ['name -rn', 'type'] # list of sort-by options
```
The above example sorts by name reversed and natural, *then* by type (so that directories and files are both sorted by name reversed, but are separated in the list). This is the equivalent of `ls | sort-by name -rn | sort-by type`.

Note: When config.rs sees this, the list's strings are checked as being valid `sort-by` arguments, including whether the column names are the four basic `ls` columns (name, size, type, modified).

**Comment by fdncred** [comment]
I don't like the default sort order either. This is partially the reason I have this alias.
```
alias lsg = (ls | sort-by type name -i | grid -c)
```
I'm fine with having a configurable option because not everyone is going to like `-rn`, like me. :)

**Comment by deicon** [comment]
wouldn't it be nice to be able to define this as a post_exec hook ? 
Currently you are able to define pre_execution hooks to each command. 
```
  hooks: {
        pre_execution: [
            { print "pre exec hook" }
            { print "pre exec hook2" }
        ]
```
So maybe having a post_execution hook could solve this. Each Post Execution hook basically would be added to the pipeline. 

When defining a post_execution for ls like 
````
hooks: {
        pre_execution: [
            { sort name -rn }
        ]
````
Executing ls like 
```
ls | table | save demo.db
```
would actually become 

```
ls | sort name -rn | table | save demo.db
```

**Comment by fdncred** [comment]
In order for this to work I think we'd have to have a pre_execution_command hook where you could specify the command and how to modify it before it executes. I'm not sure how I feel about it.

**Comment by BobToninho** [comment]
> ```
> alias lsg = (ls | sort-by type name -i | grid -c)
> ```

Does this still work? When trying to set it, I get this error:

![image](https://github.com/nushell/nushell/assets/58312518/e53dd03b-6a5b-487f-a6d9-a0c9130b8f8f)

**Comment by fdncred** [comment]
it has to be a custom command now, such as
```
def lsg [] { ls | sort-by type name -i | grid -c }
```
I actually use this custom command myself every single day.

**Comment by JonnieCache** [comment]
here's my wrapped ls function that allows you to pass args, while still handling the default case:

```
def l [...args] {
  let args = if $args == [] {
    ["."]
  } else {
    $args
  }
  ls -la ...$args | select name size type user mode modified created target
}
```

**Comment by arunoruto** [comment]
> here's my wrapped ls function that allows you to pass args, while still handling the default case:
> 
> ```
> def l [...args] {
>   let args = if $args == [] {
>     ["."]
>   } else {
>     $args
>   }
>   ls -la ...$args | select name size type user mode modified created target
> }
> ```

Thanks for that! Too bad this hasn't been implemented natively yet, but I got a few one-liners for the most common `ls` aliases:
```nu
def lla [...args] { ls -la ...(if $args == [] {["."]} else {$args}) | sort-by type name -i }
def la  [...args] { ls -a  ...(if $args == [] {["."]} else {$args}) | sort-by type name -i }
def ll  [...args] { ls -l  ...(if $args == [] {["."]} else {$args}) | sort-by type name -i }
def l   [...args] { ls     ...(if $args == [] {["."]} else {$args}) | sort-by type name -i }
```

**Comment by RobbingDaHood** [comment]
Is this issue not solved by the above suggestions? Or what is the goal of this issue now?

**Comment by arunoruto** [comment]
> Is this issue not solved by the above suggestions? Or what is the goal of this issue now?

The suggestions are currently only quick and dirty fixes to the problem. As the author stated:

> I propose adding the following:
> ```
> sort_by: ['name -rn', 'type'] # list of sort-by options
> ```

It would be nice to have such an option in the config.

**Comment by RobbingDaHood** [comment]
Could I be assigned to this? 

I have some raw code ready locally, I just need sleep :D  

Then I can make it nice tomorrow.

**Comment by fdncred** [comment]
Go for it @RobbingDaHood. I assigned it to you. No promises. Some people aren't super keen on additional config settings.

**Comment by kubouch** [comment]
We agreed that config changes shouldn't change the semantics of user code. Writing custom commands is the intended way to customize existing ones. A reasonably working solution can be found here https://github.com/nushell/nushell/pull/14331#issuecomment-2489823915.

Rather than cherry-picking favorite commands and giving them special treatment in the config, we should rather think of ways how to make wrapping commands easier, thus benefiting all commands, not just `ls`. One example could be reusing parameters of existing commands, something like `def lss [...(params-of ls)] { ls --all=$all ..etc ...$pattern | sort-by ... }`.

**Comment by jeanlucthumm** [comment]
> Rather than cherry-picking favorite commands and giving them special treatment in the config, we should rather think of ways how to make wrapping commands easier, thus benefiting all commands, not just `ls`. One example could be reusing parameters of existing commands, something like `def lss [...(params-of ls)] { ls --all=$all ..etc ...$pattern | sort-by ... }`.

Is there a tracking issue for this wrapping suggestion?

**Comment by d00astro** [comment]
> here's my wrapped ls function that allows you to pass args, while still handling the default case:
> 
> ```
> def l [...args] {
>   let args = if $args == [] {
>     ["."]
>   } else {
>     $args
>   }
>   ls -la ...$args | select name size type user mode modified created target
> }
> ```

In case anyone else struggled with getting custom `ls` commands to play nicely with tilde (`~`) and glob patterns (`*` and `**/`) in arguments, consider adding `into glob` :

`def l   [...args] { ls     ...(if $args == [] {["."]} else {$args | into glob})  | sort-by type name -i }`

This should resolve paths like `~/foo/**/*.bar` etc...

**Comment by fdncred** [comment]
This is my current way of doing it and it also uses the new `@` attributes in nushell nightly.
```nushell
# alias the built in ls command so we don't shadow it
alias ls-builtin = ls

# List the filenames, sizes, and modification times of items in a directory.
@category filesystem
@search-terms dir
@example "List the files in the current directory" { ls }
@example "List visible files in a subdirectory" { ls subdir }
@example "List visible files with full path in the parent directory" { ls -f .. }
@example "List Rust files" { ls *.rs }
@example "List files and directories whose name do not contain 'bar'" { ls | where name !~ bar }
@example "List the full path of all dirs in your home directory" { ls -a ~ | where type == dir }
@example "List only the names (not paths) of all dirs in your home directory which have not been modified in 7 days" { ls -as ~ | where type == dir and modified < ((date now) - 7day) }
@example "Recursively list all files and subdirectories under the current directory using a glob pattern" { ls -a **/* }
@example "Recursively list *.rs and *.toml files using the glob command" { ls ...(glob **/*.{rs,toml}) }
@example "List given paths and show directories themselves" { ['/path/to/directory' '/path/to/file'] | each {|| ls -D $in } | flatten }
def ls [
    --all (-a),         # Show hidden files
    --long (-l),        # Get all available columns for each entry (slower; columns are platform-dependent)
    --short-names (-s), # Only print the file names, and not the path
    --full-paths (-f),  # display paths as absolute paths
    --du (-d),          # Display the apparent directory size ("disk usage") in place of the directory metadata size
    --directory (-D),   # List the specified directory itself instead of its contents
    --mime-type (-m),   # Show mime-type in type column instead of 'file' (based on filenames only; files' contents are not examined)
    --threads (-t),     # Use multiple threads to list contents. Output will be non-deterministic.
    ...pattern: glob,   # The glob pattern to use.
]: [ nothing -> table ] {
    let pattern = if ($pattern | is-empty) { [ '.' ] } else { $pattern }
    (ls-builtin
        --all=$all
        --long=$long
        --short-names=$short_names
        --full-paths=$full_paths
        --du=$du
        --directory=$directory
        --mime-type=$mime_type
        --threads=$threads
        ...$pattern
    ) | sort-by type name -i
}
```
