### ISSUE TITLE
`uniq -i` turns all input strings lowercase instead of just comparing them.

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7192]
### Describe the bug

See title.

### How to reproduce

```
〉[AAA BBB CCC] | uniq -i
╭───┬─────╮
│ 0 │ aaa │
│ 1 │ bbb │
│ 2 │ ccc │
╰───┴─────╯
```

### Expected behavior

Expected output should use the same case as the first unique value(s) in the input: `[Aa aa Bb BB] | uniq -i` should return `[Aa Bb]`.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.71.0                                          |
| branch             |                                                 |
| commit_hash        | 6cc4ef6c706ebbdc5b995013e0b00f77f7a4dba7        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)             |
| pkg_version        | 0.71.0                                          |
| build_time         | 2022-11-08 18:03:36 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by raccmonteiro** [comment]
I am working with this command, and I have an open PR with some refactoring (https://github.com/nushell/nushell/pull/7188).
I can make this change
