### ISSUE TITLE
Please make nushell available via `cargo binstall`

### ISSUE THREAD

**Issue by michel-slm** [nushell/nushell#7201]
### Related problem

There is currently no straightforward way to install or update `nushell` without manually downloading the latest build - apart from a few platforms (e.g. using brew and winget - using brew likely requires building from source).

### Describe the solution you'd like

`cargo binstall` makes it straightforward to install Rust binaries without doing downloads manually or (worse) blindly copy-pasting some `curl` invocations: https://github.com/cargo-bins/cargo-binstall . Bonus: it keeps the downloads versioned, and symlinks them to an unversioned file, so you can keep several versions in parallel.

Starship and zellij are already available for it. Could nushell be made available too so users can `cargo binstall nushell` ?

Thanks!

### Describe alternatives you've considered

At some point in the future I hope to get nushell in Fedora too, but `binstall` is a solution that is available today, and presumably the binary artifacts that the project is already building just need to be exposed there

**Comment by fdncred** [comment]
Does something like this to work?
```
$ binstall \
  --pkg-url="{ repo }/releases/download/{ version }/{ name }-{ version }-{ target }.{ archive-format }" \
  --pkg-fmt="txz" crate_name
```

What exactly needs to change in order for binstall to work with nushell?

**Comment by michel-slm** [comment]
@fdncred that works (I have to replace `--pkg-fmt="txz"` with `--pkg-fmt="tgz"`). And also of course it should be `cargo binstall`, that example from the `binstall` repo needs updating.

The only thing that needs to change to make this work out of the box is editing Cargo.toml I think - per https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md

I'll cut a PR for this

**Comment by rgwood** [comment]
> using brew likely requires building from source

I'm pretty sure `brew install nushell` downloads binaries instead of building from source. But either way, it would be nice to support binstall.
