### ISSUE TITLE
Setting conditional aliases and environment variables

### ISSUE THREAD

**Issue by mike-lloyd03** [nushell/nushell#7203]
### Describe the bug

I am trying to conditionally define aliases in `config.nu`.

```nu
if (uname | str trim) == "Linux" {
    alias xcopy = xclip -rmlastnl -in -selection clipboard
    alias xpaste = xclip -out -selection clipboard
}
```

This evaluates to true but the aliases aren't set.

Also, when trying to set an environment variable conditionally:

```nu
if (which nvimpager | get arg | ignore; $env.LAST_EXIT_CODE == 0) {
    alias less = nvimpager -p
    let-env PAGER = ~/.dotfiles/scripts/nvimpagerp
}
```

The PAGER variable isn't set but I get some output showing that `~/.dotfiles/scripts/nvimpagerp` was called. I may be misunderstanding how to define environment variables.

### How to reproduce

See above.

### Expected behavior

Able to set aliases and environments variables depending on the results of an if statement.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.71.0                                          |
| branch             | makepkg                                         |
| commit_hash        | 6cc4ef6c706ebbdc5b995013e0b00f77f7a4dba7        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.65.0 (Arch Linux rust 1:1.65.0-1)       |
| cargo_version      | cargo 1.65.0                                    |
| pkg_version        | 0.71.0                                          |
| build_time         | 2022-11-09 06:34:03 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by kubouch** [comment]
Aliases are parser definitions like `def` so you can't set them conditionally at the moment.

Environment is possible to set conditionally either using
```
let-env PAGER = if ... { ... } else { ... }
```
or newly
```
if ... {
    let-env PAGER = ...
}
```
should work as well (it works on my end on latest main).

**Comment by mike-lloyd03** [comment]
Very cool. Thank you.

**Comment by mike-lloyd03** [comment]
So I just tried this and it's setting `PAGER` to `less`.

```nu
let-env PAGER = if (which nvimpager | get arg | null; $env.LAST_EXIT_CODE == 0) {
    "nvimpager"
} else {
    "less"
}
```

Running the conditional in the terminal evaluates to true though.

**Comment by kubouch** [comment]
Your condition seems strange because if the `which` output is empty, `get` will throw an error and there is no point checking the LAST_EXIT_CODE because the evaluation will stop with that error. I would check for empty output of `which` instead.

**Comment by mike-lloyd03** [comment]
Yep that worked. I think we're good to go now.

```nu
let-env PAGER = if (which nvimpager | is-empty) {
    "less"
} else {
    "nvimpager"
}
```

Quick side question, how can I negate the condition? Something like `!(which nvimpager | is-empty)` is what I'd like to do.

Thanks for all your help so far.

**Comment by kubouch** [comment]
You can negate with `not (which ...)`
