### ISSUE TITLE
Open command doesn't work on websites

### ISSUE THREAD

**Issue by sorrell** [nushell/nushell#721]
Ubuntu 19.04

`open` command with website target works in 0.2.0 (0.2.0 was the binary download but the binary indicates version 0.1.3)
![image](https://user-images.githubusercontent.com/763445/65797677-d556c900-e13d-11e9-854a-846916e5c896.png)

`open` command with website target gives `file not found` error in 0.3.0
![image](https://user-images.githubusercontent.com/763445/65797540-75f8b900-e13d-11e9-94cd-c913bf7b9e92.png)

**Comment by jonathandturner** [comment]
We split the `open` command into `open` (for files) and `fetch` (for urls)

**Comment by sorrell** [comment]
Ah, ok, thanks - I'll put in a PR for https://book.nushell.sh/en/loading_data
