### ISSUE TITLE
`flatten --all` does not flatten everything

### ISSUE THREAD

**Issue by raccmonteiro** [nushell/nushell#7210]
### Describe the bug

`flatten --all` does not flatten everything when we have multiple table/record as children

### How to reproduce

```
〉[[origin, people]; [World, ([[name, meal]; ['Afonso', {plate: 'bitoque', carbs: 100}]])]] | flatten --all
╭───┬────────┬────────┬───────────────────╮
│ # │ origin │  name  │       meal        │
├───┼────────┼────────┼───────────────────┤
│ 0 │ World  │ Afonso │ {record 2 fields} │
╰───┴────────┴────────┴───────────────────╯
```

### Expected behavior

```
〉[[origin, people]; [World, ([[name, meal]; ['Afonso', {plate: 'bitoque', carbs: 100}]])]] | flatten --all
╭───┬────────┬────────┬─────────┬───────╮
│ # │ origin │  name  │  plate  │ carbs │
├───┼────────┼────────┼─────────┼───────┤
│ 0 │ World  │ Afonso │ bitoque │   100 │
╰───┴────────┴────────┴─────────┴───────╯
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.71.0                                          |
| branch             |                                                 |
| commit_hash        | 6cc4ef6c706ebbdc5b995013e0b00f77f7a4dba7        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)             |
| pkg_version        | 0.71.0                                          |
| build_time         | 2022-11-08 18:03:10 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by raccmonteiro** [comment]
should this have the behavior I described? If so, I will try to make this change

**Comment by raccmonteiro** [comment]
> should this have the behavior I described? If so, I will try to make this change

I was not successful in making this change, it is more complex than I thought. 
I will leave this for anyone who might want to do it.

**Comment by fdncred** [comment]
no worries @raccmonteiro. thanks for giving it a try.

**Comment by WindSoilder** [comment]
Going to close the issue for now, it's better to flatten only one level at a time in built-in flatten

We can use a custom command to implement `flatten` for many nested levels, feel free to reopen if you still have such issue.

**Comment by WindSoilder** [comment]
Maybe we can give it another name?  Or making it auto flatten one nested level out?

**Comment by fdncred** [comment]
I'm not even sure what `--all` does. In the examples, if you use the `--all` command or without it, they all still work.
