### ISSUE TITLE
Redirecting output error

### ISSUE THREAD

**Issue by ierone** [nushell/nushell#7220]
redirecting standard output using > or >> does not result
echo 'hello world' > foo.txt

**Comment by sholderbach** [comment]
This syntax from bash is not part of nushell to enable us to use more general expressions for math and comparison.

We are working on a similar shorthand syntax for the next release: `out>` `err>` and `out+err>` (#7185)

In the meantime the idiomatic way to do this in nushell is:
```
command | save foo.txt # if you want to save structured data with the proper serialization
command | save --raw foo.txt # if you want to save the raw string stream
```
