### ISSUE TITLE
save file: can't convert record<...> to string

### ISSUE THREAD

**Issue by liigo** [nushell/nushell#7233]
### Describe the bug

```shell
C:\Users\liigo〉ls | save 1.txt                                                                 11/25/2022 11:00:50 上午
Error: nu::shell::cant_convert (link)

  × Can't convert to string.
   ╭─[entry #21:1:1]
 1 │ ls | save 1.txt
   · ─┬
   ·  ╰── can't convert record<name: string, type: string, size: filesize, modified: date> to string
   ╰────
```

### How to reproduce

run `ls | save 1.txt`

### Expected behavior

Works like other shells: `ls > 1.txt`
1.txt was saved with contents that `ls` produces.
Auto convert record<...> to a grid view string (like shows on screen).
No error report.

### Configuration

> C:\Users\liigo〉version | transpose key value | to md --pretty                                  11/25/2022 11:07:24 上午

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.71.0                                          |
| branch             |                                                 |
| commit_hash        | 6cc4ef6c706ebbdc5b995013e0b00f77f7a4dba7        |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)             |
| pkg_version        | 0.71.0                                          |
| build_time         | 2022-11-08 18:03:36 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

> In `Nushell`, `ls` is giving structured data rather than a string. You'll need to convert the structured data to output it to a file. Converters like `to json` will give you json output, or you could convert via `table` to draw the same table in the file output.

**Comment by jntrnr** [comment]
In `Nushell`, `ls` is giving structured data rather than a string. You'll need to convert the structured data to output it to a file. Converters like `to json` will give you json output, or you could convert via `table` to draw the same table in the file output.

**Comment by liigo** [comment]
> In Nushell, ls is giving structured data rather than a string.

sorry but, I don't think so. `ls` do prints *strings* to screen:

```
C:\Users\liigo〉ls                                                                              11/25/2022 11:15:21 上午
╭────┬───────────────────────┬─────────┬───────────┬────────────────╮
│  # │         name          │  type   │   size    │    modified    │
├────┼───────────────────────┼─────────┼───────────┼────────────────┤
│  0 │ .BmGisOffice          │ dir     │       0 B │ 6 months ago   │
│  1 │ .VirtualBox           │ dir     │   8.0 KiB │ a week ago     │
│  2 │ .ash_history          │ file    │   7.7 KiB │ a month ago    │
│  3 │ .bash_history         │ file    │  18.4 KiB │ a year ago     │
│  4 │ .config               │ dir     │       0 B │ 5 months ago   │
│  5 │ .dotnet               │ dir     │  32.0 KiB │ 2 weeks ago    │
│  6 │ .gitconfig            │ file    │     134 B │ 8 months ago   │
│  7 │ .lesshst              │ file    │      20 B │ 5 months ago   │
│  8 │ .local                │ dir     │       0 B │ 6 months ago   │
│  9 │ .mume                 │ dir     │       0 B │ 8 months ago   │
├────┼───────────────────────┼─────────┼───────────┼────────────────┤
│  # │         name          │  type   │   size    │    modified    │
╰────┴───────────────────────┴─────────┴───────────┴────────────────╯
```

**Comment by fdncred** [comment]
@liigo Of course JT is right, but here's a little  more detail. The only way you can get the output into a file like you're trying to do is with `ls | table | save 1.txt`. However, that will encode the ansi escape sequences too. If you don't want these you can do `ls | table | ansi strip | save 1.txt`. This is what JT meant by "convert via table".

**Comment by rgwood** [comment]
@liigo When commands are run interactively, their results are automatically piped to the `table` command to be displayed. When you run `ls`, that's translated to `ls | table` and `table` is what converts the structured data to a string.

```bash
〉ls | describe
table<name: string, type: string, size: filesize, modified: date>
〉ls | table | describe
raw input
```

**Comment by liigo** [comment]
@fdncred Gook job to make a very simple task (`ls > 1.txt`) so much complicated:
`ls | table | ansi strip | save 1.txt`.

**Comment by fdncred** [comment]
If you just want the file names you can also do this `ls | get name out> 2.txt`

**Comment by wangjiawen2013** [comment]
I saved the output to a file using `ls | table | save file.txt`, but when I opened it with excel, it's a messy code:
![image](https://github.com/nushell/nushell/assets/29703450/ba7ba6f7-ef08-4a51-81dd-5061b247931f)
And this is what it looks like in vim editor:
![image](https://github.com/nushell/nushell/assets/29703450/73c795a3-2e6d-4ba8-a781-a20dbdce6a75)

**Comment by bew** [comment]
That's what `ansi strip` is for, to be placed after `table`

**Comment by wangjiawen2013** [comment]
Hi,
Now the file can be edited with vim, but it's still messy in Excel !

**Comment by bew** [comment]
What do you expect to see in excel?

**Comment by fdncred** [comment]
if you want something for excel, you should use `to csv` like `ls | to csv`
