### ISSUE TITLE
Add alternative sugguestion to error for &&

### ISSUE THREAD

**Issue by probablySophie** [nushell/nushell#7237]
`command_A && command_B` is probably going to be a typical attempt people make to run sequential commands, but nushell uses `command_A; command_B`.  As a shell that prides itself on its error messaging I feel the error message should probably suggest using `;` instead of the current `executable was not found`

**Comment by jntrnr** [comment]
Some places we could use this:

* `&&`
* `||`
* the `2>&1` family
* `>` in the command case
* `source`

Probably others too
