### ISSUE TITLE
Make it possible to reference reusable module files from scripts

### ISSUE THREAD

**Issue by Veetaha** [nushell/nushell#7247]
### Related problem

The problem is described in the PR comment https://github.com/nushell/nushell/pull/6150#issuecomment-1312962562. It looks to me that PR was intended to solve this problem, but I can't get this working.

Here is a simple example of having a script file and a module

```nu
# scripts/lib.nu

export def foo [] {}
```

```nu
# scripts/main.nu

use lib.nu foo

foo
```

We can't call the script like this:

```
nu ./scripts/main.nu
Error: nu::parser::module_not_found (link)

  × Module not found.
   ╭─[./scripts/main.nu:2:1]
 2 │ 
 3 │ use lib.nu foo
   ·     ───┬──
   ·        ╰── module not found
 4 │ 
   ╰────
  help: module files and their paths must be available before your script is run as parsing occurs before anything is evaluated
```

### Describe the solution you'd like

I propose to make all `use`, `overlay`, `source` inside any `.nu` file reference paths relative to the script file itself instead of the process CWD. This is necessary to make robust split into multiple files and good shareable modules.

**Comment by WindSoilder** [comment]
Hi, I can't reproduce it on latest main, would you please verify it again?

**Comment by Veetaha** [comment]
I think it was fixed since then, since I've been using this already in my scripts, closing
