### ISSUE TITLE
Nushell fails to open parquet file created by pandas, if it has datetime column

### ISSUE THREAD

**Issue by maxim-uvarov** [nushell/nushell#7257]
### Describe the bug

When I try to open parquet file containing datetime column - nushell panics. 
Without datetime column it opens succesfully. 

![image](https://user-images.githubusercontent.com/4896754/204135148-63348e81-a070-42cf-a733-1486bce8036e.png)

[dt1.parquet.zip](https://github.com/nushell/nushell/files/10098308/dt1.parquet.zip)

### How to reproduce

1. Create parquet file in pandas `pd.DataFrame([datetime.datetime.now()], columns=["datetime"]).to_parquet("~/dt1.parquet")` (or use attached one [attached one](https://github.com/nushell/nushell/files/10098308/dt1.parquet.zip))
2. Open it with command `open-df`
3. See how nushell errors and quits

### Expected behavior

I expect nu to open parquet file for further operations

### Screenshots

![image](https://user-images.githubusercontent.com/4896754/204135357-19a6f733-44bd-4c07-87aa-3d732bbe058b.png)

### Configuration

 key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.71.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | macos-aarch64                                   |
| build_target       | aarch64-apple-darwin                            |
| rust_version       | rustc 1.64.0                                    |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)             |
| pkg_version        | 0.71.0                                          |
| build_time         | 2022-11-08 17:54:00 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by melMass** [comment]
Seems like it's interpreted as binary this is `open dt1.parquet`:


<img width="831" alt="image" src="https://user-images.githubusercontent.com/7041726/204138215-0ac0cbd1-66db-4a19-acc2-6e14579bcda8.png">

**Comment by fdncred** [comment]
I get this in the latest main branch of nushell.

![image](https://user-images.githubusercontent.com/343840/204334575-6658a1ce-ef24-4751-adb9-128ecc55376d.png)

**Comment by fdncred** [comment]
It's failing here if someone wants to submit a fix PR.
https://github.com/nushell/nushell/blob/7d5333db3b39b958866ccdfbf6735b9c0ea6dce7/crates/nu-command/src/dataframe/values/nu_dataframe/conversion.rs#L517-L531

**Comment by fdncred** [comment]
I think I may have this figured out. Working on a quick PR.
