### ISSUE TITLE
I have set the terminal text cursor to beam (|), but entering nu set it to block (█), this behavior is pretty annoying

### ISSUE THREAD

**Issue by KSXGitHub** [nushell/nushell#7271]
I have let `nu` generate `config.nu` for me. But I can't find relevant settings in this file.

So I have 1 question and 1 request:
* Question: How to stop `nu` from doing this.
* Request: This behavior shouldn't be the default behavior, can you guys disable it.

**nu version:** 0.71.0

**Comment by rgwood** [comment]
Cursor configuration is covered by #7151

**Comment by fdncred** [comment]
@KSXGitHub Agreed. It's friggin annoying to me too. It would be nice if someone fixed this already. This is a start but it's not finished yet https://github.com/nushell/reedline/pull/515
