### ISSUE TITLE
Move off of set-output for CI

### ISSUE THREAD

**Issue by sophiajt** [nushell/nushell#7276]
### Describe the bug

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### How to reproduce

1. see above

### Expected behavior

We need to follow the steps in the blog post to move off of `set-output` in our release CI.

### Configuration

<see above>

**Comment by weirdan** [comment]
This has already been done in #7290
