### ISSUE TITLE
`complete` is missing `exit_code`

### ISSUE THREAD

**Issue by theAkito** [nushell/nushell#7283]
### Describe the bug

```nu
(do -i { git rev-parse --git-dir } | complete).exit_code
```
Does not work, anymore.

When issuing the following command:

```nu
do -i { git rev-parse --git-dir } | complete
```

The `exit_code` record is missing.

### How to reproduce

1. Upgrade to [0.72.0](https://github.com/nushell/nushell/releases/tag/0.72.0).
2. Try `(do -i { git rev-parse --git-dir } | complete).exit_code`.
3. Perceive exception.

### Expected behavior

The `exit_code` record should continue to be available.

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.72.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | linux-x86_64                         |
| build_target       | x86_64-unknown-linux-gnu             |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)  |
| rust_channel       | stable-x86_64-unknown-linux-gnu      |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)  |
| pkg_version        | 0.72.0                               |
| build_time         | 2022-11-29 22:10:46 +01:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

### Additional context

**Platform**
Debian GNU/Linux 11 (bullseye) in WSL2 on Windows 10

**Terminal software**
Windows Terminal

Nushell is running "natively" as a login shell.

____

This is a **huge** showstopper in my scenario. Will need to downgrade to `0.71.0`.

**Comment by jntrnr** [comment]
@theAkito if you change it from `(do -i { git rev-parse --git-dir } | complete).exit_code` to `(do -c { git rev-parse --git-dir } | complete).exit_code` does it work?

**Comment by theAkito** [comment]
> @theAkito if you change it from `(do -i { git rev-parse --git-dir } | complete).exit_code` to `(do -c { git rev-parse --git-dir } | complete).exit_code` does it work?

I'm getting a generic `External command failed`, which is also the wrong behaviour.

If this should work, it's not documented, anyway.

**Comment by jntrnr** [comment]
@theAkito I misremembered. It looks like this is now the flag:

```
〉(do -s { git rev-parse --git-dir } | complete).exit_code
128
```

The flags for `do` changed in this release. You'll need to do `do --help`. There is some info towards the bottom of the release notes (which points to this change: https://github.com/nushell/nushell/pull/7122), but looks like we missed listing it in the breaking changes.

**Comment by theAkito** [comment]
> The flags for `do` changed in this release. You'll need to do `do --help`.

Correct me, if I'm wrong.

My command line should still work.

Excerpt from `do --help` follows.

```nu
  Run the block and ignore both shell and program errors
  > do -i { thisisnotarealcommand }

  Run the block and ignore shell errors
  > do -s { thisisnotarealcommand }
```

If `-s` works, then `-i` should work, even more so.

**Comment by theAkito** [comment]
@jntrnr 

And what is that....


```nu
git rev-parse --git-dir | complete
fatal: not a git repository (or any of the parent directories): .git
╭───────────┬─────╮
│ stdout    │     │
│ exit_code │ 128 │
╰───────────┴─────╯
```

**Comment by jntrnr** [comment]
Closing as this was a change in 0.72.

**Comment by theAkito** [comment]
@jntrnr 

```nu
  Run the block and ignore both shell and program errors
  > do -i { thisisnotarealcommand }
```

So, the documentation is wrong?

**Comment by WindSoilder** [comment]
I don't think the issue should be closed, in #7122, `do -i` is setting external stream's exit_code to None, we need to change `complete` command to fit the behavior.

**Comment by mklepaczewski** [comment]
@jntrnr It seems confusing. When running `do { git branch} | complete` the result has `exit_code`, but when I run `do -i { git branch } | complete` the `exit_code` field is gone. Is that expected? What rationale is followed here? I'm fine with this change as `-s` seems to work, but the documentation for `do` does not mention this behavior, and combining `-s -p` strips  the `exit_code`.

**Comment by hustcer** [comment]
@mklepaczewski What's your nushell version？ My output with Nu v0.76:
```
nu -c 'do -i { git branch } | complete'
╭───────────┬──────────────────────────────────────────────────────────────────────╮
│ stdout    │                                                                      │
│ stderr    │ fatal: not a git repository (or any of the parent directories): .git │
│           │                                                                      │
│ exit_code │ 128                                                                  │
╰───────────┴──────────────────────────────────────────────────────────────────────╯
```

**Comment by mklepaczewski** [comment]
@hustcer v0.75, sigh. I'm waiting for winget repo update to install v0.76. Once I do that, I'll check it on the newest version.

**Comment by mklepaczewski** [comment]
@hustcer Just checked on v0.76 - it works, thanks!
