### ISSUE TITLE
Running `into df` raises `extra positional argument` error

### ISSUE THREAD

**Issue by assuncaolfi** [nushell/nushell#7294]
### Describe the bug

Using nu 0.72.0 with MacOS 12.5 and running

```
[[a b]; [1 2] [3 4]] | into df
```

raises the error

```
  × Extra positional argument.
   ╭─[org.nu:2:1]
 2 │ 
 3 │ [[a b];[1 2] [3 4]] | into df
   ·                            ─┬
   ·                             ╰── extra positional argument
   ╰────
  help: Usage: into
```

.

### How to reproduce

Run:

1. `cargo install nu`
2. `nu`
3. `[[a b]; [1 2] [3 4]] | into df`

### Expected behavior

I expected nu to output a dataframe. https://www.nushell.sh/book/commands/into_df.html

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.72.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | macos-x86_64                         |
| build_target       | x86_64-apple-darwin                  |
| rust_version       | rustc 1.64.0                         |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)  |
| pkg_version        | 0.72.0                               |
| build_time         | 2022-11-29 18:33:56 -03:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

**Comment by stormasm** [comment]
```rust
cargo build --features=dataframe
```

and if you want to download the source code from github and build nu on your own....
