### ISSUE TITLE
nushell and PRQL

### ISSUE THREAD

**Issue by jgranduel** [nushell/nushell#7296]
### Related problem

I gave a try to [PRQL](https://prql-lang.org/) through this Rust implementation [prql-query](https://github.com/prql/prql-query).
I found it so close to what I know of Nushell that I dare ask if it would be reasonable to implement a very close or even same syntax?
```
〉open people.csv                                                                                                                      
╭───┬────┬───────┬────────╮
│ # │ id │ name  │  city  │
├───┼────┼───────┼────────┤
│ 0 │ 11 │ Diane │ London │
│ 1 │ 22 │ Grace │ Berlin │
│ 2 │ 33 │ Alice │ Paris  │
╰───┴────┴───────┴────────╯

>open people.csv | get name | sort | take 2
╭───┬───────╮
│ 0 │ Alice │
│ 1 │ Diane │
╰───┴───────╯

> 〉pq --from p=people.csv "from p | select name | sort [name]  | take 2"                                                             
+-------+
| name  |
+-------+
| Alice |
| Diane |
+-------+

### Describe the solution you'd like

have a close syntax, maybe through aliases.

### Describe alternatives you've considered

_No response_

### Additional context and details

_No response_

**Comment by fdncred** [comment]
It's not a foreign question. People have requested it in the past. I've always been intrigued by PRQL myself.

**Comment by stormasm** [comment]
@jgranduel yes !  this is a very cool product as well...
and indeed related to nushell in many ways as well as both

https://github.com/pola-rs/polars

and 

https://github.com/apache/arrow-datafusion

so all of these technologies are coming together...

not sure if you are on discord but a good place to discuss these ideas further
would be on our discord under the dataframes channel...

**Comment by jgranduel** [comment]
@ stormasm Thank you for the 2 links. I have adopted datafusion indeed.

so let's see how Nushell will evolve... Thanks.

**Comment by nileshtrivedi** [comment]
Have there been any developments on this since 2022?

**Comment by stormasm** [comment]
> Have there been any developments on this since 2022?

The best place to get answers about this subject would be in our discord dataframe channel.

https://discord.com/channels/601130461678272522/864228801851949077
