### ISSUE TITLE
New Rust Users

### ISSUE THREAD

**Issue by jolv1** [nushell/nushell#730]
The instructions tell you to install Rust and run the install command but do not mention to ensure the $PATH is correct for Cargo or to ensure the users install the nightly toolchain and instructions for that.

**Comment by jonathandturner** [comment]
Thanks for the report. Were you installing using the README or the book?

We have a section in the book about this (https://book.nushell.sh/en/installation#installing-rust) but we don't make it as clear in the README.

**Comment by JesterOrNot** [comment]
Try the gitpod link in the readme to get up and running quickly
