### ISSUE TITLE
Can't `return` from a script without a `main` definition

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#7301]
### Describe the bug

The following script works:

```
def main [] {
  if true {
    print "returning early"
    return
  }

  print "done"
}
```

```bash
〉nu foo.nu
returning early
```

However, if I leave out the `main` definition it does not work:
```
if true {
  print "returning early"
  return
}

print "done"
```
```bash
〉nu bar.nu
returning early
Error: 
  × Return used outside of function
   ╭─[bar.nu:2:1]
 2 │   print "returning early"
 3 │   return
   ·   ───┬──
   ·      ╰── used outside of function
 4 │ }
   ╰────
```

### How to reproduce

1. Write a Nu script (`foo.nu`) without explicitly defining a `main` function
2. Run it with `nu foo.nu`
3. Observe the "Return used outside of function" error

### Expected behavior

I expect `return` to work even without explicitly defining `main` in a script.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.0                                   |
| branch             | main                                     |
| commit_hash        | fa97e819ebfa6c568101da4cefec1505964b48b7 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.0                                   |
| build_time         | 2022-11-29 22:27:52 -08:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I'm pretty sure this works as designed. When you do `nu script.nu` the `main` custom command is ran. If you don't have a `main` then it's not supposed to work. However, if you `source script.nu`, it should execute the script. I haven't tested your example with `source`, does it work that way?

You can see this here https://github.com/nushell/nushell/blob/6fadc7255393f64048684102837a85292c1e9fa0/crates/nu-cli/src/eval_file.rs#L39-L56

**Comment by sholderbach** [comment]
I think this could be a good enhancement, that bare scripts behave like they had an implicit `main`. Upgrading to a proper `def main [args] {` would be trivial. The only downside would be if we think people should be nudged to use an explicit `main` (thinking about the whole `if __name__ == "__main__":` weirdness in python, to separate "definitions" from execution after the fact)

**Comment by fdncred** [comment]
We have a plan to deprecate and remove `source` I think. I'm not sure what that means for this because it seems like without `source` there will be no way to execute a script outside of having commands inside of `def`/`def-env`.... I think. I could be wrong. I'm not up to speed on `use`, `module`, `overlay`.

**Comment by theAkito** [comment]
Just to give this more context, I'll chime in on how Bash works with this. I am **not** implying that Bash behaviour should be imitated; I'm just providing this as an FYI.

Basically, `return` is for `function` scope & when a script is `source`d.
When a script is just run like `bash run.sh`, a `return` is not tolerated in the top-level scope.

It has the obvious downsides about it, but it also has the upside, that the script author can force the script to be `source`d. It's an easy way to make sure, that a script is used properly, like e.g. when doing a lot of environment changes & generally programming the script in a way, which makes only sense, when it is being `source`d.

I think Rust does something with `rustup`, too. It tells the user to `source` a script for the environment variables.

**Comment by rgwood** [comment]
> When you do `nu script.nu` the `main` custom command is ran. If you don't have a `main` then it's not supposed to work.

@fdncred I think it would be a _huge_ UX/ergonomics loss if we required a `def main []` in every script file. I would strongly object to making that a requirement.

**Comment by fdncred** [comment]
> @fdncred I think it would be a huge UX/ergonomics loss if we required a def main [] { ... in every script file. I would strongly object to making that a requirement.

Maybe we should chat more about this on Discord. It's kind of hard to do it here. But anyway, it's not that every script has to have a `main`. You can source any script and all the custom commands are available to you now. However, if you want to just go `nu script.nu`, then that `script.nu` has to have a `main`, otherwise it wouldn't know which custom command in that script to execute.

Also, talking about the future with deprecating source, right now, in modules, I don't believe you can have `let a = 1` outside of a `def`. Kind of different topic I know, but it's a stepping stone or insight into how source may or may not work in the future. It's been said in core-team that eventually let's won't be able to used outside of defs.

But let's take this to Discord if you're ok with that.

**Comment by fdncred** [comment]
Just a brief update from Discord.
![image](https://user-images.githubusercontent.com/343840/205138116-508f765a-44bf-4c5d-bc5d-3663fe4341e8.png)
