### ISSUE TITLE
`explore`: rendering speed tanks when viewing files with extra long lines

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7322]
### Describe the bug

When using `explore` on a text file that has super long lines, the framerate drops horribly.

### How to reproduce

1. Run `fetch https://twitter.com/nu_shell | explore` (for an example of a long-lined file)
2. Scroll to the bottom
3. Scroll to the right ← this part is where framerate issues are.

### Expected behavior

Fix perf issues.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.1                                   |
| branch             |                             |
| commit_hash        | 212673f65a10b2a7b17967826077cccea29f64ce |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.1                                   |
| build_time         | 2022-12-02 15:39:28 +10:00               |
| build_rust_channel | debug                                    |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by zhiburt** [comment]
Hi @webbedspace

I actually assume the issue is not with left/right, but rather with fast down/up scrolling.

I've tried to fix it.
Though the solution is quite...

It must got better with #7334 could you verify it?

PS: thanks for a reproducable.

**Comment by fdncred** [comment]
i can't reproduce the slowdown after #7334.
