### ISSUE TITLE
`explore` `:try` `open` does not display file content

### ISSUE THREAD

**Issue by raccmonteiro** [nushell/nushell#7327]
### Describe the bug

File content is not loaded inside `explore` when we try `open` command.

### How to reproduce

1. type `explore`
2.  `:try` 
3. `open README.md` 

### Expected behavior

display file content, maybe same behavior as `open README.md | explore`

### Screenshots

![image](https://user-images.githubusercontent.com/3062698/205327259-ccfffbab-b476-4fdd-ad5a-3b30b4ff0cc1.png)

### Configuration

```
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.1                                   |
| branch             | main                                     |
| commit_hash        | bc0c9ab698df2aac5a6373594d43dc663e72c586 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.1                                   |
| build_time         | 2022-12-02 14:55:10 +00:00               |
| build_rust_channel | debug                                    |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |
```

**Comment by fdncred** [comment]
i think, if you hit `down arrow` and then hit `i` it may show it. can you try that?

**Comment by raccmonteiro** [comment]
> i think, if you hit `down arrow` and then hit `i` it may show it. can you try that?

That worked, I had to hit `down arrow`, then `i`, then `Enter`. Where's info about `i` key? 
Do you think that could be some info about how to view the content where is `# Nushell <!-- omit in toc -->…` ?

**Comment by fdncred** [comment]
> Where's info about i key?

It's in `:help`

You can also follow this issue where other requests are being tracked https://github.com/nushell/nushell/issues/7332
