### ISSUE TITLE
`explore` inside `explore` has strange behavior when quitting

### ISSUE THREAD

**Issue by raccmonteiro** [nushell/nushell#7328]
### Describe the bug

When we quit `:q` the cursor is in wrong place, and if we hit ENTER we go to `explore` again. 
The only solution I found to exit `explore` was CTRL + Z when we open `explore` inside `explore`

### How to reproduce

1. `explore`
2. `:try`
3. `explore`
4. `:q`

### Expected behavior

`:q` exits all `explore`, or don't allow to open `explore` inside `explore`

### Screenshots

![image](https://user-images.githubusercontent.com/3062698/205328836-6a1738e0-cf86-454e-8440-2cd4e5a4633d.png)
![image](https://user-images.githubusercontent.com/3062698/205329080-0ef1ba25-c1f0-4e58-bab6-2e0afff105c9.png)

### Configuration

```
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.1                                   |
| branch             | main                                     |
| commit_hash        | bc0c9ab698df2aac5a6373594d43dc663e72c586 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.1                                   |
| build_time         | 2022-12-02 14:55:10 +00:00               |
| build_rust_channel | debug                                    |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |
```

**Comment by fdncred** [comment]
oof, that's a bug. thanks

**Comment by raccmonteiro** [comment]
one more thing, not sure if there should a dedicated issue for this.
If we type 

1. `explore`
2. `:try`
3. `exit` 

the console keeps the `explore` frame.

![image](https://user-images.githubusercontent.com/3062698/205354233-f5a15845-3247-4f63-b73d-9cf0fb1a4ed1.png)

**Comment by zhiburt** [comment]
Hi @raccmonteiro 

Nice catch
