### ISSUE TITLE
the starting index of table is wrongly starts with `1`

### ISSUE THREAD

**Issue by WindSoilder** [nushell/nushell#7338]
### Describe the bug

@kurokirasama spotted this, when viewing a table, the first index is 1 rather than 0.

### How to reproduce

```
❯ [{'a': 1}]
╭───┬───╮
│ # │ a │
├───┼───┤
│ 1 │ 1 │
╰───┴───╯
```

### Expected behavior

The table should starts with index 0

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.1                                   |
| branch             | main                                     |
| commit_hash        | 850ecf648a225eac2ae74846cec2ed47b3399a76 |
| build_os           | macos-x86_64                             |
| build_target       | x86_64-apple-darwin                      |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.1                                   |
| build_time         | 2022-12-03 18:28:27 +08:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  | gstat                                    |

**Comment by kurokirasama** [comment]
I'm on Ubuntu in latest repo build

**Comment by fdncred** [comment]
Some on mac.
<img width="624" alt="Screenshot 2022-12-03 at 10 10 13 AM" src="https://user-images.githubusercontent.com/343840/205450439-c0fc23de-fa6f-4552-94bf-3b4c20b250ff.png">

**Comment by DarkPark** [comment]
Confirm the problem. A very unpleasant one.
Debian 11.
![image](https://user-images.githubusercontent.com/1189578/205459323-e2997eaf-012b-40cb-86f2-3d94a7563578.png)

**Comment by WindSoilder** [comment]
Additionally, I've tried `[{a: 1}] | table`, and the result is fine

**Comment by zhiburt** [comment]
Hmmmmm

on linux on the same comit still OK for me.

Could you run `cargo run -- -c '[{'a': 1}]'`?

**Comment by kurokirasama** [comment]
but `[{a: 1}]``is a table and `[{a: 1}]`| table ` is a raw input (according to `describe`

**Comment by zhiburt** [comment]
Could you try this?

https://github.com/nushell/nushell/pull/7343

**Comment by WindSoilder** [comment]
@zhiburt Thanks, I've check the pr build, it works fine for me

**Comment by fdncred** [comment]
> Could you try this?

That fixes it for me too.
