### ISSUE TITLE
Table paging for ListStreams is missing a line break

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#7342]
### Describe the bug

Table paging for `ListStreams` is missing a line break. This is easiest to explain with a screenshot:

![image](https://user-images.githubusercontent.com/26268125/205463074-3d29b36f-0fc4-4489-bd44-d4d98e868d28.png)

That's from a build of Nu where I changed `STREAM_PAGE_SIZE` in table.rs from 1000 to 10 to make the problem easier to see.

### How to reproduce

Run a command that returns over 1000 rows of streaming data, and observe that the formatting is messed up for pages other than the first one.

### Expected behavior

I expected the formatting to not be messed up.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.1                                   |
| branch             | main                                     |
| commit_hash        | cf0a18be51eddbb95dff04172e2a72e9dc7c432f |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.1                                   |
| build_time         | 2022-12-01 15:34:39 -08:00               |
| build_rust_channel | debug                                    |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by rgwood** [comment]
@zhiburt This _might_ be a `tabled` issue? I'm not 100% sure.

**Comment by zhiburt** [comment]
Hi @rgwood

So `nu-table` doesn't have a trailing new line.
I guess its because of that.

Though it was always the case,
and it appeared only now?

I guess it's some regression?

**Comment by rgwood** [comment]
Gotcha, thanks.

I think it's a regression but I'm not sure; the default value for `STREAM_PAGE_SIZE` is so high that I don't see multiple pages very often :)

**Comment by zhiburt** [comment]
Hmmmm

Works for me

![image](https://user-images.githubusercontent.com/20165848/205464020-518b17c3-208f-4cd0-8856-afddd52354dd.png)

**Comment by rgwood** [comment]
Weird! Maybe this is related to my config somehow. I'll keep investigating, thanks.

**Comment by rgwood** [comment]
I can reproduce this on a new Debian VM with a clean install of Nushell (default config.nu and env.nu files).

**Comment by theAkito** [comment]
Not sure, whether this is part of a bigger issue, but I experienced stuff like this, when scrolling the terminal was involved, through either the terminal doing it automatically or me doing it manually.

Since it was so vague, I didn't create an issue about it.

It ended up like in the initial screenshot or, even worse, parts of tables were entirely gone.

This also was a pretty sporadic issue. So, it is no surprise to me, that some of your do not experience it & others do. It's a matter of terminal size, etc. At least, that's the information I could gather from my observations.

**Comment by rgwood** [comment]
It looks like this is caused by the `display_output` hook, which unfortunately collects all output before displaying it: https://github.com/nushell/nushell/blob/2bacc29d30fc6bb4798c9ef99801267492feb80d/crates/nu-cli/src/repl.rs#L958

Removing the `display_output` hook from config.nu fixes this issue.

`run_hook_block()` in repl.rs may need some tweaks.

**Comment by rgwood** [comment]
It looks like piping to `table` - even outside the context of the `display_output` hook - always removes line breaks between pages:

```bash

〉seq 1 20
╭───┬────╮
│ 0 │  1 │
│ 1 │  2 │
│ 2 │  3 │
│ 3 │  4 │
│ 4 │  5 │
│ 5 │  6 │
│ 6 │  7 │
│ 7 │  8 │
│ 8 │  9 │
│ 9 │ 10 │
╰───┴────╯
╭────┬────╮
│ 10 │ 11 │
│ 11 │ 12 │
│ 12 │ 13 │
│ 13 │ 14 │
│ 14 │ 15 │
│ 15 │ 16 │
│ 16 │ 17 │
│ 17 │ 18 │
│ 18 │ 19 │
│ 19 │ 20 │
╰────┴────╯
〉seq 1 20 | table
╭───┬────╮
│ 0 │  1 │
│ 1 │  2 │
│ 2 │  3 │
│ 3 │  4 │
│ 4 │  5 │
│ 5 │  6 │
│ 6 │  7 │
│ 7 │  8 │
│ 8 │  9 │
│ 9 │ 10 │
╰───┴────╯╭────┬────╮
│ 10 │ 11 │
│ 11 │ 12 │
│ 12 │ 13 │
│ 13 │ 14 │
│ 14 │ 15 │
│ 15 │ 16 │
│ 16 │ 17 │
│ 17 │ 18 │
│ 18 │ 19 │
│ 19 │ 20 │
╰────┴────╯
〉
```

**Comment by rgwood** [comment]
Still working on this. I think I understand the cause of the problem but don't have a solution yet.

## The Cause

REPL lines get evaluated and printed in `nu_cli::util.rs::eval_source()`.

If I run `0..1000 | table`, that evaluates to a `PipelineData::ExternalStream` and is printed here: https://github.com/nushell/nushell/blob/26759c4af2d54c7600e3f09521054ea3d5eca72e/crates/nu-cli/src/util.rs#L242

At this point, `eval_source` has no way to know that it should put newlines in between the pages. From its perspective, the evaluation result is just an external stream of bytes that should be displayed as-is

If I run `0..1000`, that evaluates to a `PipelineData::Value(Value::Range)` and is printed here: https://github.com/nushell/nushell/blob/26759c4af2d54c7600e3f09521054ea3d5eca72e/crates/nu-cli/src/util.rs#L253

The `Value::Range` is automatically piped to `table`, and printed with newlines in between each page.

## Possible Solutions

Maybe `table` should add newlines to each page's output instead of relying on other code to do so? 🤔

## Details

Some notes from a debugging session with the `display_output` hook disabled:

This is where data gets printed from running `0..1000`:
```
#0  nu_protocol::pipeline_data::PipelineData::write_all_and_flush (self=..., engine_state=0x7ffe5b091ac8, config=0x7ffe5b091c50,
    no_newline=false, to_stderr=false) at crates/nu-protocol/src/pipeline_data.rs:537
#1  0x000056339475b4c6 in nu_protocol::pipeline_data::PipelineData::print (self=..., engine_state=0x7ffe5b091ac8,
    stack=0x7ffe5b0936c0, no_newline=false, to_stderr=false) at crates/nu-protocol/src/pipeline_data.rs:519
#2  0x0000563393630f31 in nu_cli::util::eval_source (engine_state=0x7ffe5b091ac8, stack=0x7ffe5b0936c0, source=..., fname=...,
    input=...) at crates/nu-cli/src/util.rs:253
#3  0x00005633936452d5 in nu_cli::repl::evaluate_repl (engine_state=0x7ffe5b091ac8, stack=0x7ffe5b0936c0, nushell_path=...,
    prerun_command=...) at crates/nu-cli/src/repl.rs:420
#4  0x000056339229e2be in nu::main () at src/main.rs:440
```

This is where data gets printed when running `0..1000 | table`:

```
#0  nu_utils::utils::stdout_write_all_and_flush<&[u8]> (output=...) at crates/nu-utils/src/utils.rs:32
#1  0x000055c09fcdfbfb in nu_protocol::pipeline_data::print_if_stream (stream=..., stderr_stream=..., to_stderr=false,
    exit_code=...) at crates/nu-protocol/src/pipeline_data.rs:618
#2  0x000055c09ebb3da3 in nu_cli::util::eval_source (engine_state=0x7ffc56747268, stack=0x7ffc56748e60, source=..., fname=...,
    input=...) at crates/nu-cli/src/util.rs:242
#3  0x000055c09ebc82d5 in nu_cli::repl::evaluate_repl (engine_state=0x7ffc56747268, stack=0x7ffc56748e60, nushell_path=...,
    prerun_command=...) at crates/nu-cli/src/repl.rs:420
#4  0x000055c09d8212be in nu::main () at src/main.rs:440
```

These lines in `utils.rs` are the key: https://github.com/nushell/nushell/blob/26759c4af2d54c7600e3f09521054ea3d5eca72e/crates/nu-cli/src/util.rs#L235-L254
