### ISSUE TITLE
We should return a better error for "illegal" filenames on Windows

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#7345]
### Related problem

A user recently reported the following error when running `ls`:

```
C:\Users\myname〉ls                                                                                12/03/2022 05:49:31 PMError: nu::shell::error_reading_file (link)

  × Error trying to read file
   ╭─[entry #2:1:1]
 1 │ ls
   · ─┬
   ·  ╰── Could not read file metadata
   ╰────
   ```
   
It turns out that they had a file with an illegal name (`output.`) in their home directory, and deleting the file fixed the issue. Apparently they had created the file with MSYS2 and it didn't validate the file name. We've seen similar issues with users who were somehow able to create files named NUL.

### Describe the solution you'd like

The error message should point users in the right direction, by telling them exactly which file caused the problem.

### Additional context and details

Windows file name rules: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file

**Comment by ChrisDenton** [comment]
Alternatively `ls` should be able to list such files. E.g. Both powershell (`Get-ChildItem`) and cmd (`dir`) can list them.

**Comment by rgwood** [comment]
Agreed, if we can figure out a way to display those files that would be nice.
