### ISSUE TITLE
`[] | upsert 1 'foo'` produces bad error

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7347]
### Describe the bug

See title.

### How to reproduce

```
〉[] | upsert 1 'foo'
Error: nu::shell::access_beyond_end (link)

  × Row number too large (max: 18446744073709551615).
   ╭─[entry #10:1:1]
 1 │ [] | upsert 1 'foo'
   ·             ┬
   ·             ╰── index too large (max: 18446744073709551615)
   ╰────

```

### Expected behavior

The error should say that upserting beyond 1 + the list's length doesn't work, instead of giving an overflowed "index too large"

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.0                                   |
| branch             |                                          |
| commit_hash        | 8fa965118c2e5a0beaa528d07eaf9b33d96779cb |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.0                                   |
| build_time         | 2022-11-29 18:11:35 +00:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by Kangaxx-0** [comment]
@webbedspace  Will this be fixed as part of your PR to allow env mutation, or it is a different issue ?
