### ISSUE TITLE
The `exit_code` column appears to be gone from `do { ... } | complete` in 0.72

### ISSUE THREAD

**Issue by adamkpickering** [nushell/nushell#7358]
### Describe the bug

I have a command that runs each time I press enter in the nushell command prompt that checks whether the current directory is a git repo. In 0.71 I used the line `let result = ( do -i { git rev-parse --is-inside-work-tree } | complete )`; I could then get the exit code with `$result.exit_code` and thus determine whether I was in a git repo. However, it seems that after upgrading to 0.72, only the `stderr` and `stdout` columns are available on `$result`.

### How to reproduce

Run `let result = ( do -i { git rev-parse --is-inside-work-tree } | complete )` while in a directory that is a git repo, and also while not in a directory that is a git repo.

### Expected behavior

I expected there to be an `exit_code` column to the result of `do { ... } | complete`.

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.72.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | linux-x86_64                         |
| build_target       | x86_64-unknown-linux-gnu             |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)  |
| rust_channel       | stable-x86_64-unknown-linux-gnu      |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)  |
| pkg_version        | 0.72.0                               |
| build_time         | 2022-12-05 09:53:42 -07:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

**Comment by fdncred** [comment]
How about this?
```
let result = ( do -i { git rev-parse --is-inside-work-tree | complete } )
```

**Comment by fdncred** [comment]
I'm not sure if it's a bug or not. I think our capturing of stdout and stderr will continue to change for a while until we arrive at something we're happy with. I'm not sure `try` can do all the things `do` can do yet.

**Comment by WindSoilder** [comment]
It should be handled by #7204

**Comment by WindSoilder** [comment]
Closing it for now, feel free to reopen if you still run into the issue
