### ISSUE TITLE
watch doesn't work as described

### ISSUE THREAD

**Issue by solodov** [nushell/nushell#7362]
### Describe the bug

Split of closures and blocks in 0.72 might have broken some built-in commands, watch in particular. Either that, or the documentation is out of date. 

### How to reproduce

1.  run `watch . { |op, path, new_path| $"($op) ($path) ($new_path)"}`

### Expected behavior

Should watch for file changes and log

### Screenshots

```
〉watch . { |op, path, new_path| $"($op) ($path) ($new_path)"} 
Error: nu::parser::parse_mismatch (link)

  × Parse mismatch during operation.
   ╭─[entry #21:1:1]
 1 │ watch . { |op, path, new_path| $"($op) ($path) ($new_path)"}
   ·           ┬
   ·           ╰── expected block but found closure
   ╰────
```

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.72.1                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | macos-aarch64                        |
| build_target       | aarch64-apple-darwin                 |
| rust_version       | rustc 1.65.0                         |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)  |
| pkg_version        | 0.72.1                               |
| build_time         | 2022-12-05 17:17:06 +00:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

**Comment by rgwood** [comment]
Thanks for the bug report. I’ll take a look, should be an easy fix.
