### ISSUE TITLE
Extended table (table -e) starts index with 1

### ISSUE THREAD

**Issue by sadilekivan** [nushell/nushell#7363]
### Describe the bug

An extended table starts the # index with a 1 instead of a 0, but just on the output. If you use `get #` then it selects the index correctly.

### How to reproduce

1. `ls` and `ls | table -e` outputs
```nu
/home/ivan/devel/folder〉ls                                                                                                                                                                                               12/06/2022 11:36:43 AM
╭───┬───────┬──────┬──────┬──────────╮
│ # │ name  │ type │ size │ modified │
├───┼───────┼──────┼──────┼──────────┤
│ 1 │ file1 │ file │  0 B │ now      │
│ 2 │ file2 │ file │  0 B │ now      │
╰───┴───────┴──────┴──────┴──────────╯
```
2. `ls | table` outputs
```nu
/home/ivan/devel/folder〉ls | table                                                                                                                                                                                       12/06/2022 11:37:49 AM
╭───┬───────┬──────┬──────┬───────────────╮
│ # │ name  │ type │ size │   modified    │
├───┼───────┼──────┼──────┼───────────────┤
│ 0 │ file1 │ file │  0 B │ 2 minutes ago │
│ 1 │ file2 │ file │  0 B │ 2 minutes ago │
╰───┴───────┴──────┴──────┴───────────────╯
```
3. `ls | get 1` will get file2 as expected in both cases.

### Expected behavior

I expect the tables to start from index 0 no matter the `-e` flag at table rendering, or for the printed index to correspond to the row (so `ls | get 2` would work on `ls | table -e` in the case presented above)

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.72.1                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | linux-x86_64                         |
| build_target       | x86_64-unknown-linux-gnu             |
| rust_version       | rustc 1.65.0 (Fedora 1.65.0-1.fc37)  |
| cargo_version      | cargo 1.65.0                         |
| pkg_version        | 0.72.1                               |
| build_time         | 2022-12-05 00:00:00 +00:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

**Comment by sholderbach** [comment]
Could this be related to #7338 that should be fixed on the latest `main` branch?

**Comment by sadilekivan** [comment]
> Could this be related to #7338 that should be fixed on the latest `main` branch?

I should have ordered the issues by date or something, missed this one when searching. Yes it certainly looks like it!
