### ISSUE TITLE
cannot redirect `err` and `out` to different streams

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#7364]
### Describe the bug

hello there :wave: 

it appears `nushell` can not redirect output streams of a process to different locations, namely `stdout` and `stderr` to different files, at the same time :open_mouth: 

i think this might be a bug? :confused:
if that's a feature not implemented yet, then i think it would be cool to allow the simultaneous redirection :yum: 

i did not find anything related to that in the [issue tracker](https://github.com/nushell/nushell/issues?q=is%3Aissue+redirect) nor in the [discussion feed](https://github.com/nushell/nushell/discussions?discussions_q=redirect) when looking for "redirect" :+1: 

cheers :relieved: :tada:

### How to reproduce

:one: let's take a super simple script
```bash
#!/usr/bin/env bash
# foo.sh

echo "this is stdout" > /dev/stdout
echo "this is stderr" > /dev/stderr
```

:two: make it executable with `chmod +x foo.sh`
:three: run the following
```bash
1> ./foo.sh err> /dev/null
2> ./foo.sh out> /dev/null
3> ./foo.sh out+err> /dev/null

4> ./foo.sh out> foo.out
5> ./foo.sh err> foo.err
6> ./foo.sh err+out> foo.out.err

7> ./foo.sh out> foo.out err> foo.err
```

### Expected behavior

:heavy_check_mark: 1, 2 and 3 give the expected result, i.e. the selected stream does not appear to the command line output
```bash
> ./foo.sh err> /dev/null
this is stdout
> ./foo.sh out> /dev/null
this is stderr
> ./foo.sh out+err> /dev/null
```

:heavy_check_mark: 4, 5 and 6 give also what i expected, i.e. the selected stream goes to the output file
```bash
> ./foo.sh out> foo.out
this is stderr
> ./foo.sh err> foo.err
this is stdout
> ./foo.sh err+out> foo.out.err
```
```bash
> open foo.out
this is stdout
> open foo.err
this is stderr
> open foo.out.err
this is stdout
this is stderr
```

:x: however, i expected 7 to redirect `stdout` to `foo.out` AND `stderr` to `foo.err` at the same time, and thus giving the same output as above
```bash
> ./foo.sh out> foo.out err> foo.err
> open foo.out
this is stdout
> open foo.err
this is stderr
```
, but i get the following error
```bash
./foo.sh out> foo.out err> foo.err
this is stderr
Error: nu::shell::unsupported_input (link)

  × Unsupported input
   ╭─[entry #174:1:1]
 1 │ ./foo.sh out> foo.out err> foo.err
   ·                       ──┬─
   ·                         ╰── Nothing not supported
   ╰────
```

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.72.0                                    |
| branch             |                                           |
| commit_hash        |                                           |
| build_os           | linux-x86_64                              |
| build_target       | x86_64-unknown-linux-gnu                  |
| rust_version       | rustc 1.65.0 (Arch Linux rust 1:1.65.0-1) |
| cargo_version      | cargo 1.65.0                              |
| pkg_version        | 0.72.0                                    |
| build_time         | 2022-12-03 18:27:13 +01:00                |
| build_rust_channel | release                                   |
| features           | database, default, trash, which, zip      |
| installed_plugins  |                                           |

**Comment by webbedspace** [comment]
Urggh… 🐎 I don't use Bash and I don't use these redirects, and this syntax reminds me why 🐝 If one thinks of > as a "pipeline separator" like Nushell does, taking command of everything to the left of it, then placing `err>` after `out>` makes no sense whatsoever. 🦘That being said, I guess if you rethink the redirects as things that change an existing pipeline's output behaviour when it reaches the other end, and not just as syntactic sugar over `| save`, this could be made to work. 🐿

I actually decided to see what happens when you place two stdout `>` redirects in Bash:
```
Leon@PC MINGW64 /c/Users/Leon/
$ echo 'Wow' > deleteme.txt > deleteme2.txt

Leon@PC MINGW64 /c/Users/Leon/
$ tail deleteme.txt

Leon@PC MINGW64 /c/Users/Leon/
$ tail deleteme2.txt
Wow
```
The fact that the second one seemingly overrides the first (but the first is still inexplicably created 🐦) seems vaguely consistent with that idea🦕.

**Comment by amtoine** [comment]
@webbedspace 

i see what you mean :yum: 

the two ways of seeing this look fair to me

the question then is
### should `./foo.sh out> foo.out err> foo.err` be interpreted as
- `(./foo.sh out> foo.out) err> foo.err`, which makes no sense be 'cause `./foo.sh out> foo.out` looks like the end of the pipeline and thus returns `nothing` 
- `(./foo.sh) out> foo.out err> foo.err`, which would behave as i though this command would in the first place, creating both `foo.out` and `foo.err` with the right content, i.e. `this is stdout` and `this is stderr` respectively


maybe the latter is a bit more intuitive to me :thinking: 
not even sure about that as i do not use this structure in `nushell` (reminds me of `bash` too :laughing:)
