### ISSUE TITLE
ps built-in command consist with linux ps, and kill command

### ISSUE THREAD

**Issue by Silentdoer** [nushell/nushell#7366]
### Question

use ps aux or ps -ef replace ps -l

**Comment by fdncred** [comment]
If you wanted to replace the `ps` command with something like the os's `ps` command you could do something like this, from my mac, and put it in an alias.
<img width="1565" alt="Screenshot 2022-12-06 at 7 03 56 AM" src="https://user-images.githubusercontent.com/343840/205920293-64b623cf-ce39-4b5a-bf48-7e8009803664.png">
