### ISSUE TITLE
why not replace($it) with ${it}

### ISSUE THREAD

**Issue by Silentdoer** [nushell/nushell#7376]
### Question

${it} is more general

**Comment by jntrnr** [comment]
Not sure I understand. Can you write some examples of what you'd like to see?

**Comment by Silentdoer** [comment]
such as: "aaa ${it + 1} bb", if it is 8,will prints:aaa 9 bb

**Comment by jntrnr** [comment]
`$it` is a variable. `it + 1` in Nushell would call the `it` command, but I don't think you want that.

**Comment by Silentdoer** [comment]
thanks
