### ISSUE TITLE
how to detect $in type?

### ISSUE THREAD

**Issue by Silentdoer** [nushell/nushell#7379]
### Question

string, list,int...

**Comment by jntrnr** [comment]
@Silentdoer - please include examples with the issues you're filing

**Comment by Silentdoer** [comment]
suchas:
def aaa[] {
  if $in is string {} else if $in is List<string>...
}

**Comment by sholderbach** [comment]
`describe` is probably the command you are looking for. It returns information about the type. 
We do not support direct matching on types yet.
