### ISSUE TITLE
The help command does not help

### ISSUE THREAD

**Issue by alper** [nushell/nushell#738]
When I type `help config` for instance to learn something more about the nu-shell built-ins, I get:

```
sh: line 0: help: no help topics match `config'.  Try `help help' or `man -k config' or `info config'.
```

I think this is the result for all commands.

This is on macOS.

**Comment by jonathandturner** [comment]
What version of Nu are you running? Also, did you build it yourself or use the pre-built binary?

**Comment by alper** [comment]
I `brew install`ed it.

**Comment by jonathandturner** [comment]
@alper - homebrew looks to be out of date:

```
nushell | 0.2.0 | Modern shell for the GitHub era
```

**Comment by jonathandturner** [comment]
Closing this. Please re-open if you can repro with 0.3.0 or later.

**Comment by alper** [comment]
OK. I'll keep an eye out for when somebody updates the Homebrew. (I would learn how to do it but don't have the time right now.)

**Comment by alper** [comment]
I went through the rustup song and dance and with the latest version the help command works. Thanks!
