### ISSUE TITLE
"aa\nbb\n"|split row "\n"|length is 2

### ISSUE THREAD

**Issue by Silentdoer** [nushell/nushell#7389]
### Describe the bug

should not auto trim

### How to reproduce

like title

### Expected behavior

length is 3

### Configuration

nushell 66.2 and 0.72.1 Windows10

**Comment by WindSoilder** [comment]
Can you please try the latest version or latest main branch?  I can't reproduce it

**Comment by Silentdoer** [comment]
i  test it in 0.72.1 version, it is not fix, my system is Windows 10
