### ISSUE TITLE
`math e` has wrong description

### ISSUE THREAD

**Issue by kurokirasama** [nushell/nushell#7401]
### Describe the bug

It says:
```
Returns the mathematical constant π.
```

### How to reproduce

```
help math e
```

### Expected behavior

It should say
```
Returns the mathematical constant e (exp(1)).
```

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.72.2                                          |
| branch             | main                                            |
| commit_hash        | 017a13fa3f465a6a62082fd3da1a373b39055cd8        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)             |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)             |
| pkg_version        | 0.72.2                                          |
| build_time         | 2022-12-06 00:52:44 -03:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | custom-value generate, gstat, inc, pnet, query  |

**Comment by sholderbach** [comment]
Good catch! Totally missed that one.
