### ISSUE TITLE
`while`, `loop`, `for` issues

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#7404]
### Describe the bug

- [ ] ctrl-c issue with `while true { print foo }` - does't work in iterm2 but does work in terminal.app. i'm assuming iterm2 isn't configured right
- [ ] `while true { echo blah }` doesn't print to the screen
- [ ] `while true { echo hello; echo world }` prints only hello

My understanding was that due to allowing mutable variables, `while`, `for`, and `loop` behave differently now and could only print to screen with print and could not return values. So, `let d = (for x in 1..10 { echo 5 }` would not work because it's returning a value. However you can `print` from any of these commands.

Maybe I'm conflating several things in one.

### How to reproduce

see above

### Expected behavior

print to the screen with echo and print but don't return a value to the pipeline, maybe?

### Configuration

|key|value|
|-|-|
|version|0.72.2|
|branch|main|
|commit_hash|017a13fa3f465a6a62082fd3da1a373b39055cd8|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.65.0 (897e37553 2022-11-02)|
|rust_channel|1.65.0-aarch64-apple-darwin|
|cargo_version|cargo 1.65.0 (4bc8f24d3 2022-10-20)|
|pkg_version|0.72.2|
|build_time|2022-12-05 17:02:09 -06:00|
|build_rust_channel|release|
|features|database, dataframe, default, trash, which, zip|
|installed_plugins|custom-value generate, custom-value generate2, custom-value update, dfu, from parquet, gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml|

### Additional context

/cc @jntrnr

**Comment by webbedspace** [comment]
>`while true { echo blah }` doesn't print to the screen

Isn't this a repeat of #6928 ?

**Comment by kubouch** [comment]
I would expect `while true { echo blah }` to create an infinite stream of "blah" strings. For printing, you'd use `print`.

**Comment by webbedspace** [comment]
I believe the point of that line is that the `while` is eating the output of the block altogether.

**Comment by fdncred** [comment]
IIRC, when `for` & friends changed to blocks for the use of `mut`, they stopped being able to output values. So, we can no longer do `let blah = (for x in 1..10 { echo $x })`. My understanding was that was intentional, but I'm not so sure any longer after the discussion that precedes this https://discord.com/channels/601130461678272522/601130461678272524/1050611312209698918.
