### ISSUE TITLE
module constants

### ISSUE THREAD

**Issue by solodov** [nushell/nushell#7416]
### Related problem

module constants (internal or exported) would be a great and natural way to define configuration or constants. Coming from any other shell constants are expected, so it a bit of a surprise that they don't exist. config.nu allows defining constants and functions in one file, so the natural expectation is to be able to do the same in modules.

### Describe the solution you'd like

The solution that seems to fit:

```
# some_module.nu

# plain variable
export let foo = "bar"

def add_two [i: int] {
  $i + 2
}
# a constant that uses previously defined command
export let bar = (seq 10 | each {|it| add_two $it})
```

### Describe alternatives you've considered

It's possible to work around this by wrapping data with custom commands, but that feels cumbersome, and inconsistent with how config file works.

**Comment by webbedspace** [comment]
Yeah, those would be nice, especially inside the `module { }` syntax too.

**Comment by weirdan** [comment]
This is now supported.
