### ISSUE TITLE
`ListStream` pages are not displayed before pressing `ctrl+c`

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#7431]
### Describe the bug

Say you have a command that returns a `ListStream` of values slowly. Nu's `PagingTableIterator` _should_ handle this well; its purpose is to stream values into a buffer until it has reached `STREAM_PAGE_SIZE` (currently 1000) items _or_  a full second has elapsed, and then render that "page" of values as a table. See [here](https://github.com/nushell/nushell/blob/2bacc29d30fc6bb4798c9ef99801267492feb80d/crates/nu-command/src/viewers/table.rs#L1571).

However, I'm noticing that pages are not being displayed until the `ListStream` finishes or I press `ctrl+c`. This is a little tricky to reproduce with a regular Nu install, so [here's a branch where I created a new streaming command and set `STREAM_PAGE_SIZE` to 10.](https://github.com/nushell/nushell/compare/main...rgwood:nushell:liststream-experiments)

![image](https://user-images.githubusercontent.com/26268125/206882461-e62a19d7-c526-425b-ad1c-49dfef886f13.png)

### How to reproduce

1. Check out my `liststream-experiments` branch: https://github.com/rgwood/nushell/tree/liststream-experiments
2. `cargo run`
3. `errmaker 300` (or whatever number you like)
4. Observe that the numbers aren't printed unless you press `ctrl+c`

### Expected behavior

I expected Nu to display pages before pressing `ctrl+c`.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.2                                   |
| branch             | liststream-experiments                   |
| commit_hash        | bd788336a2dd9416141595c700162f73284d1c9b |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.2                                   |
| build_time         | 2022-12-10 17:33:30 -08:00               |
| build_rust_channel | debug                                    |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

### Additional context

I wonder if this is somehow related to https://github.com/nushell/nushell/issues/7342

**Comment by rgwood** [comment]
Managed to track this down to the `display_output` hook. It seems like `display_output` is collecting all output, when `run_hook_block()` in repl.rs does this: https://github.com/nushell/nushell/blob/2bacc29d30fc6bb4798c9ef99801267492feb80d/crates/nu-cli/src/repl.rs#L958

Removing the `display_output` hook fixes streaming and the line breaks from #7342.

**Comment by merelymyself** [comment]
Somewhat irrelevant but I'm pretty sure you can use `seq` to test it out. Same problem, it doesn't show until ctrl+c is pressed.
