### ISSUE TITLE
Remove `--output` and `--append` flags in favour of `save` command

### ISSUE THREAD

**Issue by vwkd** [nushell/nushell#7439]
### Describe the bug

I'm confused when I should use the `output` and `append` flags instead of piping the output into the `save` command.

The `output` and `append` flags are present on the `fetch` command. I'm not sure if they're also present somewhere else.

IIUC, the `save` command can do everything the `output` and `append` flags can. One difference seems the `output` and `append` flags don't preserve the original formatting.

In general, it seems advantageous to prefer commands over flags where appropriate because it works for every command in the pipe and doesn't need a separate implementation.

### How to reproduce

1. `fetch --output test.html https://www.example.com` or `fetch --append test.html https://www.example.com`
2. `fetch https://www.example.com | save test.html` or `fetch https://www.example.com | save --append test.html`

### Expected behavior

A single one preferred way of doing things instead of multiple.

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.72.1                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | macos-x86_64                         |
| build_target       | x86_64-apple-darwin                  |
| rust_version       | rustc 1.65.0                         |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)  |
| pkg_version        | 0.72.1                               |
| build_time         | 2022-12-05 17:17:06 +00:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

**Comment by rgwood** [comment]
Agreed, those flags are unnecessary and we should get rid of them. Thanks for the issue.
