### ISSUE TITLE
Panic when piping Nu config to `from nuon`

### ISSUE THREAD

**Issue by Stonks3141** [nushell/nushell#7441]
### Describe the bug

Running this command caused a panic:

```sh
> cat config.nu | from nuon
thread 'main' panicked at 'internal error: missing module command', crates/nu-parser/src/parse_keywords.rs:1497:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It does not occur with `from json` or with any other file. Here is the config file: [https://paste.rs/s44](https://paste.rs/s44)

I am using Konsole 22.08.3-1 on KDE Manjaro, although the panic also occurred in Alacritty 0.11.0-2.

### How to reproduce

1. Download [this file](https://paste.rs/s44).
2. Run `cat path/to/that/file.nu | from nuon` (you may need to enter a nested shell to see the panic output).

### Expected behavior

I expected `from nuon` to fail with a syntax error.

### Configuration

| key                | value                                     |
| ------------------ | ----------------------------------------- |
| version            | 0.72.0                                    |
| branch             | makepkg                                   |
| commit_hash        | 8fa965118c2e5a0beaa528d07eaf9b33d96779cb  |
| build_os           | linux-x86_64                              |
| build_target       | x86_64-unknown-linux-gnu                  |
| rust_version       | rustc 1.65.0 (Arch Linux rust 1:1.65.0-1) |
| cargo_version      | cargo 1.65.0                              |
| pkg_version        | 0.72.0                                    |
| build_time         | 2022-11-30 06:57:53 +00:00                |
| build_rust_channel | release                                   |
| features           | database, default, trash, which, zip      |
| installed_plugins  |                                           |

**Comment by WindSoilder** [comment]
It's duplicate to #5996
