### ISSUE TITLE
Bettery Display of Empty list

### ISSUE THREAD

**Issue by Decodetalkers** [nushell/nushell#7444]
### Describe the bug

![image](https://user-images.githubusercontent.com/60290287/207020273-24b8978e-e2a0-41f0-94a2-013ad5791d2b.png)

![image](https://user-images.githubusercontent.com/60290287/207020500-685a46db-644d-4a9d-930b-287c8c08ce55.png)

So, the  "empty" here is empty array.. If empty array can be better display

### How to reproduce

1. let a = []
2. echo $a

### Expected behavior

Better display

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.72.1                                          |
| branch             | makepkg                                         |
| commit_hash        | 777f746127806a34ab946e7495755655cac72cec        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.65.0 (Arch Linux rust 1:1.65.0-1)       |
| cargo_version      | cargo 1.65.0                                    |
| pkg_version        | 0.72.1                                          |
| build_time         | 2022-12-12 07:20:37 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by Decodetalkers** [comment]
I think null should also display in another form, else will be mistake as ""

**Comment by fdncred** [comment]
if you do `let a = []` and then `$a | to json` or `$a | to nuon` it looks ok. if you do `$a | is-empty` you get `true`. if you display it differently that probably wouldn't work.

**Comment by weirdan** [comment]
Fixed (in #7925 ?).

```console
$ []
╭────────────╮
│ empty list │
╰────────────╯
```
