### ISSUE TITLE
split column and parse command should return the record type instead of the table type

### ISSUE THREAD

**Issue by Silentdoer** [nushell/nushell#7445]
### Describe the bug

`"aa-bb"|split column "-"|describe`, will return the table type, but I think it would be more natural to return the record type?
similarly, `"aa-bb"|parse "{col1}-{col2}"|describe`, should return record.

By the way, can the separator of the split column support regular expressions

### How to reproduce

see describe

### Expected behavior

return reocrd type

### Configuration

nushell version 0.72.1, windows 10

**Comment by fdncred** [comment]
Thanks for your opinion. The point of `split column` is to split to columns. Parse is also designed to parse into columns.

We may add regular expressions to the split commands someday but it may be better to add a composable `regex` command that can be used everywhere. Will have to think about this.
