### ISSUE TITLE
`register` stuck forever when inconsistent `nu-*` version is used

### ISSUE THREAD

**Issue by zhiburt** [nushell/nushell#7447]
### Describe the bug

Running https://github.com/JosephTLyons/nu_plugin_periodic_table/blob/master/Cargo.toml as discribbed in #7380 with no `Cargo.toml` update to latest version causes `register` command being not able to run.

It stucks right on the last character of a binary name or when you hit `<Tab>` for a binary name.

### How to reproduce

#7380 with no update of Cargo.toml

### Expected behavior

A error message?

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.2                                   |
| branch             | patch-explore-3                          |
| commit_hash        | 3f41773b9256c7ec64c0dd3df9b8ffbd5da50026 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.2                                   |
| build_time         | 2022-12-08 20:58:48 +03:00               |
| build_rust_channel | debug                                    |
| features           | database, default, trash, which, zip     |
| installed_plugins  | periodic-table                           |

**Comment by JosephTLyons** [comment]
Hahaha, I don't have much context here for what broke or changed, but I'll try to add a fix it.  Feel free to open a PR if you know the problem / fix and it's not much work, otherwise, I'll look into it tonight or tomorrow.

**Comment by fdncred** [comment]
@JosephTLyons I think the signatures for plugins changed since you last updated your periodic-table plugin. I believe I just updated the cargo.toml files to 0.72.0 and recompiled and re-registered. I can't remember if your plugin used json or capnp, but we removed capnp in favor of msgpack.

**Comment by JosephTLyons** [comment]
I bumped the versions, recompiled, and tested on my end, and it works for me.  Published version v0.2.4:

- https://github.com/JosephTLyons/nu_plugin_periodic_table

**Comment by zhiburt** [comment]
> it gets hung up. i believe we've fixed it going forward

:+1:
