### ISSUE TITLE
#SHELL command not work

### ISSUE THREAD

**Issue by mindgitrwx** [nushell/nushell#7451]
### Describe the bug

I just entered this command
```
$SHELL
```

And this error produced.
``` 
× Variable not found.
   ╭─[entry #149:1:1]
 1 │ $SHELL
   · ───┬──
   ·    ╰── variable not found
   ╰────
```

### How to reproduce

To run the command, simply enter $SHELL in the terminal

### Expected behavior

Show default shell directory as
```
/bin/bash
```

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.72.1                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | macos-aarch64                        |
| build_target       | aarch64-apple-darwin                 |
| rust_version       | rustc 1.65.0                         |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)  |
| pkg_version        | 0.72.1                               |
| build_time         | 2022-12-05 17:17:06 +00:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

**Comment by hustcer** [comment]
Please    try `$env.SHELL`

**Comment by stellarpower** [comment]
```
[🍍] ~/N/N/Session Recordings> nu -c 'echo $env.SHELL'
/usr/bin/fish
```

Is this a regression? I am on 0.86.0
