### ISSUE TITLE
Possible to disable nushell commands?

### ISSUE THREAD

**Issue by SamKG** [nushell/nushell#7463]
### Question

Hello,
I love nushell, but the nushell commands don't have feature parity to their unix counterparts. This leads to frustrating and confusing situations where I use a command as I always have (e.g. `echo -e` or `ls -h` ), but I instead get an error as nushell does not support the flag `-e` for echo. 

Is there any way to disable all nushell commands? Or atleast rename them (e.g. nushell `ls` renamed to `nuls`) so that I can use nushell variants when I want, and the Unix versions by default?

**Comment by merelymyself** [comment]
You can add a caret (^) in front of the command to run the external (instead of the nushell builtin).

**Comment by SamKG** [comment]
thanks!
Is there any way to invert this behavior? i.e. caret runs the nushell builtin instead of the external?

**Comment by deadbody13** [comment]
A quick workaround I've found is that you can alias the caret, (i.e. `alias echo = ^echo`) in your `config.nu`. I did the same thing for `update` because it conflicted with an in-path script I had that shared the name.

**Comment by LensPlaysGames** [comment]
Coming here to say that it is an absolute hassle to deal with the caret every time I want to use `find`, `ls -A`, or `mkdir -p`

**Comment by weirdan** [comment]
Using `ls` as an example (you can do this in `config.nu`):

```nushell
alias nuls = ls # rename to `nuls`
hide ls # hide internal `ls`, so that nu will run external `ls`
```

Result:

![image](https://github.com/user-attachments/assets/8dfc959d-0bfb-4960-b441-0e9e94a06a28)
