### ISSUE TITLE
Cannot pipe directly from for loop

### ISSUE THREAD

**Issue by hyiltiz** [nushell/nushell#7465]
### Describe the bug

[~/.config/nushell/scripts/spark.nu](https://github.com/nushell/nu_scripts/blob/main/fun/spark.nu) used:
```{nu}
def spark [v: any] {
    let min = ($v | math min)
    let max = ($v | math max)
    let scale = (($max - $min) / 7.)
    for e in $v {
        let i = (($e - $min) / $scale | into int)
        $"($TICKS | get $i)"
    } | str collect
}
```

Now it seems one must wrap the `for {}` closure into parenthesis:
```{nu}
...
    (for e in $v {
        let i = (($e - $min) / $scale | into int)
        $"($TICKS | get $i)"
    }) | str collect
...
```

Is it an intended behavior due to the separation of blocks and closures in 0.72.0, or it is a side effect from the nu parser?

### How to reproduce

1. Attempt to define as first block
2. Fail
3. Attempt to define as second block
4. Succeed

### Expected behavior

First block should still work?

### Configuration

```
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.72.2                                          |
| branch             | main                                            |
| commit_hash        | 26759c4af2d54c7600e3f09521054ea3d5eca72e        |
| build_os           | macos-x86_64                                    |
| build_target       | x86_64-apple-darwin                             |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)             |
| rust_channel       | 1.65.0-x86_64-apple-darwin                      |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)             |
| pkg_version        | 0.72.2                                          |
| build_time         | 2022-12-13 14:15:01 -06:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |
```

**Comment by fdncred** [comment]
Ya, I wrote that script and it needs to be updated to something like this.  We changed the way `for` works and it broke lots of things. My usual habit is to change `for` to `each`.

```
def spark [v: any] {
  let min = ($v | math min)
  let max = ($v | math max)
  let scale = (($max - $min) / 7.)
  $v | each {|e|
    let i = (($e - $min) / $scale | into int)
    $"($TICKS | get $i)"
  } | str collect
}
```

**Comment by hyiltiz** [comment]
No wonder my script got broke and I wasn't sure where/how. What is the semantic difference between `for`, `loop` and `each`? I think loop doesn't take any input for driving the flow (it is just "while true"), but both `for` and `each` takes an iterables and applies a function. Is `each` like `map` where each iteration has no effect to the rest (Functor-like), while `for` can leave an effect (Applicative or Monad-like)

**Comment by hyiltiz** [comment]
Behavior of `for`, `each` changed. Nu works as expected, and scripts that got broken due to backward incompatible changes need to be updated.
