### ISSUE TITLE
External command with nonzero exit code does not break `loop` execution

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#7467]
### Describe the bug

Someone on Discord noticed that external commands don't stop loop execution when they return a nonzero exit code.

### How to reproduce

Run `loop { print "hi"; ^false; }`, watch it loop forever.

### Expected behavior

I expect external command failure to stop the execution of the `loop`, just like failure of an internal command.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.2                                   |
| branch             | main                                     |
| commit_hash        | 5b5f1d1b92f0adf5ca235e850aed0d92c44ce88e |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.2                                   |
| build_time         | 2022-12-12 14:57:49 -08:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by WindSoilder** [comment]
The same issue happened on `for`, `while` too.
## For
```
﻿❯ for _ in 1..4 { echo "b"; ^false;echo "a" }
b
b
b
b
```

## While
```
❯ mut x = 1; while $x < 3 { $x = $x + 1; echo bb; ^false }
bb
bb
```
