### ISSUE TITLE
options not visible on "Solarized" color scheme

### ISSUE THREAD

**Issue by zeenix** [nushell/nushell#747]
`Solarized` is a popular colorscheme and I'm using that in `gnome-terminal`. I was unable to read `--raw` option when and after typing it to `open` command. It's not visible even if i select it using the mouse.

**Comment by zeenix** [comment]
![Screenshot from 2019-10-01 10-04-41](https://user-images.githubusercontent.com/2027/65944858-e9971080-e432-11e9-853e-d627953f4f8c.png)

**Comment by jonathandturner** [comment]
Agreed, we'd like to add support for getting the colors from the config file at some point. Are you interested in working on a PR by chance? I can point out a few places in the code to look at.

**Comment by zeenix** [comment]
> Are you interested in working on a PR by chance?

Interested, yes. :)

> I can point out a few places in the code to look at.

Please do point away. I might be able to get some time for it soon. If not, hopefully it'll help some other person who wants to contribute. :)

**Comment by jonathandturner** [comment]
Sounds good :)

The prompt and input get colored here: https://github.com/nushell/nushell/blob/master/src/shell/helper.rs#L68 using the `paint_token_node` function later in the file.

An example of loading from config is at: https://github.com/nushell/nushell/blob/master/src/format/table.rs#L207-L213

What I'd probably start with is loading some color elements from config before the loop here: https://github.com/nushell/nushell/blob/master/src/shell/helper.rs#L83  and then pass in those color settings to `paint_token_node`. 

For easy reference, here's how to set a config value (this one sets the table type to display):

```
> config --set [table_mode light]
```

I'm not sure how easy it will be to take in a color name, that's something worth looking into. Alternately, your settings could take in RGB colors, and use those instead.

**Comment by jonathandturner** [comment]
It may make sense to make a couple color themes, and let the user choose between one of them, rather than configuring each color by hand. But I'll let you make the call there :)

**Comment by andrasio** [comment]
#900

**Comment by zeenix** [comment]
@andrasio same guestion here: Which PR/patch fixes this?

**Comment by andrasio** [comment]
@zeenix Same answer caballero.

**Comment by coolshaurya** [comment]
I believe this issue was fixed by #1194

**Comment by jonathandturner** [comment]
Closing but please reopen if the issue still occurs with the latest master
