### ISSUE TITLE
`uniq` command is slow and un-interruptible

### ISSUE THREAD

**Issue by mattico** [nushell/nushell#7477]
### Describe the bug

I opened a reasonably large csv file (17MB, 18640 rows) and passed it to `uniq`. One of the columns has a timestamp so every row is unique, oops. The `uniq` command took 4 minutes to execute, and during execution I was not able to interrupt it with `Control-C`.

For comparison `cat data.csv | huniq` completes instantly. (https://github.com/koraa/huniq) Of course, that is operating on raw text, not structured tables.

### How to reproduce

let data = fetch "https://home.treasury.gov/system/files/276/yield-curve-rates-1990-2021.csv"
$data | uniq

### Expected behavior

I expected `uniq` to process this amount of data relatively quickly, or at least let me interrupt it.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.1                                   |
| branch             |                                          |
| commit_hash        | 777f746127806a34ab946e7495755655cac72cec |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.1                                   |
| build_time         | 2022-12-05 17:43:26 +00:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by rgwood** [comment]
I'll take a look at adding ctrl+c support. Thanks for the bug report.

**Comment by rgwood** [comment]
Added ctrl+c support to `uniq` and `uniq-by` in #7478. Leaving this issue open because we should still address the "slow" part.

**Comment by mattico** [comment]
Thanks @rgwood and @raccmonteiro
