### ISSUE TITLE
Support vi keys for scrolling

### ISSUE THREAD

**Issue by zeenix** [nushell/nushell#748]
Most bearded old geeks are very used to vi keys for scrolling everywhere so kindly add them. They are readily supported by all unix/linux commands that has scrolling: less, git, etc

I'm a bit surprised that I couldn't find any open or closed issue for this. :)

**Comment by jonathandturner** [comment]
Is this related?  https://github.com/nushell/nushell/pull/407

**Comment by zeenix** [comment]
> Is this related? #407

I saw that but I'm not sure cause it's already merged (I built this morning) and this is about scrolling view (although i'm not sure what editing mode is).

**Comment by jonathandturner** [comment]
Ahh okay. Vi mode isn't on by default, but it may be only for editing and not for scrolling.

**Comment by jonathandturner** [comment]
For scrolling, you don't mean the prompt but the textview (the scrolling text file viewer)?

If so, that wouldn't be hard to add.

**Comment by zeenix** [comment]
> Vi mode isn't on by default, but it may be only for editing and not for scrolling.

I did enable it as per your blog post but it didn't affect scrolling so yeah.

> For scrolling, you don't mean the prompt but the textview (the scrolling text file viewer)?

Indeed.

> If so, that wouldn't be hard to add.

Cool. Same here, if you can point to the relevant parts of the code that needs changing and any other hints, you might be able to get a PR. :)

**Comment by jonathandturner** [comment]
Sure thing :)

The relevant lines for the scrolling text view are: https://github.com/nushell/nushell/blob/master/src/plugins/textview.rs#L150-L185

In theory, it should be as simple as adding a few more keys we're looking for there.

**Comment by jonathandturner** [comment]
This should be fixed with #775
