### ISSUE TITLE
Cell paths drill into nested tables

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#7494]
### Describe the bug

![image](https://user-images.githubusercontent.com/26268125/207992483-30666e87-5c65-48ca-b82b-1e9eb19b2cfa.png)

Cell paths are able to drill into nested tables in an unexpected way.

### How to reproduce

1. Create a table nested in a list: `[ [{ foo: "bar" }] ]`
2. Use a cell path for a column in the nested table: `[ [{ foo: "bar" }] ] | get foo` or `[ [{ foo: "bar" }] ].foo`
3. Observe that you get a result instead of an error

### Expected behavior

I expected Nu to return a `ShellError`, or maybe `Nothing`. IMO drilling into columns of nested tables automatically is very unexpected behaviour.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.2                                   |
| branch             | main                                     |
| commit_hash        | 5b5f1d1b92f0adf5ca235e850aed0d92c44ce88e |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.2                                   |
| build_time         | 2022-12-12 14:57:49 -08:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by stormasm** [comment]
[ [{ foo: "bar" }] ] | get 0 | to nuon

[[foo]; [bar]]
 
[ [{ foo: "bar" }] ] | get 0.foo | to nuon

[bar]

However this is the correct behavior and is currently working fine...




However I believe this behavior is currently working correctly ?
