### ISSUE TITLE
`to url` needs a new name and help info

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#7495]
### Describe the bug

```bash
〉help to url
Convert table into url-encoded text
```

This is misleading IMO. [The most common definition of URL encoding is percent-encoding](https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding), i.e. `foo bar` -> `foo%20bar`.

`to url` does something completely different, it builds up [a query string](https://en.wikipedia.org/wiki/Query_string):
```
〉[[foo bar]; ["1" "2"]] | to url
foo=1&bar=2
```

### Expected Behavior

I think we need to give `to url` a new name or remove it. I haven't figured out what the new name should be.

### Version

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.2                                   |
| branch             | main                                     |
| commit_hash        | 5b5f1d1b92f0adf5ca235e850aed0d92c44ce88e |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.2                                   |
| build_time         | 2022-12-12 14:57:49 -08:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by webbedspace** [comment]
I mean, technically speaking, it does do percent-encoding…
```
〉{a:"AT&T"} | to url
a=AT%26T
```
…but you're right that it should actually be called something else.

Reminder that `url parse` currently uses the term 'query' (derived from JS's `URL()` API) for this, so I suggest `to url query`
```
〉'https://twitter.com/search?vertical=default&src=sprv&f=live&q=%22nushell%22' | ($in | url parse | get params | to url)
vertical=default&src=sprv&f=live&q=%22nushell%22
```

**Comment by VincenzoCarlino** [comment]
Hi, I would like to contribute to Nu and I think that this issue could be a good starting point.
Could you assign me this issue? Tnx.

**Comment by rgwood** [comment]
@VincenzoCarlino Done. Thanks!
