### ISSUE TITLE
Nu should have a way to do URL encoding

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#7496]
### Related problem

Nu should have a way to do [URL encoding / percent encoding](https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding). This has come up a few times on Discord, and people tend to be surprised that the `to url` command doesn't do this (related issue: #7495).

### Describe the solution you'd like

I would like a simple way to convert `https://example.com/foo bar` to `https://example.com/foo%20bar`.

My first idea is that this could be a subcommand of `encode`:

```bash
> "https://example.com/foo bar" | encode url
https://example.com/foo%20bar
```

I'm open to other ideas though.

**Comment by webbedspace** [comment]
No, the meaning of "encode" used by `encode` is something completely different to what you mean here. `encode` is a string -> bytes operation that takes a string (which has no "inherent" encoding) and turns it into the byte representation for that given Unicode encoding. For instance, `"法" | encode shift-jis` produces 2 bytes but `"法" | encode utf8` produces 3 bytes.

**Comment by rgwood** [comment]
That makes sense. Open to other name ideas.

**Comment by CBenoit** [comment]
What about `str url-encode` and `str url-decode`?

**Comment by MehulG** [comment]
Could you guys assign me this issue? I would love to look at this. My first issue in rust :)

**Comment by khayyamsaleem** [comment]
Looks like this is good to close.
