### ISSUE TITLE
Add debug command for pipelines

### ISSUE THREAD

**Issue by Hofer-Julian** [nushell/nushell#7506]
### Related problem

If I have a pipeline, I often would like to be able to print intermediate results.
Think of something like `map(|x| dbg!(x))` in Rust.
As far as I can tell there is no obvious way to do that in nushell.

### Describe the solution you'd like

Currently I create the following helper function in every script I write:

```nu
def print-debug [] {
  let input = $in
  print $input
  $input
}
```

The following pipeline then prints the intermediate state, while still keeping the pipeline intact.

```nu
$ ["1","2","3"] | each {into int} | print-debug | math sum
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 2 │
│ 2 │ 3 │
╰───┴───╯
6
```

Ideally nushell would provide a similar command.

### Describe alternatives you've considered

Continue to define my own custom command.

**Comment by webbedspace** [comment]
I recall Lodash (JS library) has an intermediate results method called .tap(), which takes a function to run on said results. I think something similar could be added to Nushell fairly easily - how about `aside [thing:closure]`, which can be used like this:
```
command1 | aside { save "inter.txt" } | command2
command1 | aside { print "inter.txt" } | command2
```
Calling it `aside` emphaises that only side-effect commands like `save` and `print` should be used with it.

**Comment by Hofer-Julian** [comment]
I think that one is fixed by https://github.com/nushell/nushell/pull/8028

What do you say @fdncred?

**Comment by fdncred** [comment]
Ya. I think so.
