### ISSUE TITLE
Command menus are broken

### ISSUE THREAD

**Issue by Sygmei** [nushell/nushell#7507]
### Describe the bug

Command menus (that can be opened with `CTRL + T` or `CTRL + S` by default) display only error entries
`$nu.config-path`
```
{
  name: commands_menu
  modifier: control
  keycode: char_t
  mode: [emacs, vi_normal, vi_insert]
  event: { send: menu name: commands_menu }
}
{
  name: commands_with_description
  modifier: control
  keycode: char_s
  mode: [emacs, vi_normal, vi_insert]
  event: { send: menu name: commands_with_description }
}
```
When pressing the CTRL + S shortcut and typing the `ls` command, it will give the following output
```
❯ # ls
Not a record: Error { error: IncompatiblePathAccess("error", Span { start: 14825, end: 14832 }) }
Not a record: Error { error: IncompatiblePathAccess("error", Span { start: 14825, end: 14832 }) }
Not a record: Error { error: IncompatiblePathAccess("error", Span { start: 14825, end: 14832 }) }
Not a record: Error { error: IncompatiblePathAccess("error", Span { start: 14825, end: 14832 }) }
```

### How to reproduce

Press CTRL + S, type `ls`

### Expected behavior

A list of commands and their description

### Screenshots

![image](https://user-images.githubusercontent.com/3835355/208191515-67352361-ff4d-4f3c-b081-f74db6cb7b88.png)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.1                                   |
| branch             |                                          |
| commit_hash        | 777f746127806a34ab946e7495755655cac72cec |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | stable-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.1                                   |
| build_time         | 2022-12-05 17:43:26 +00:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

### Additional context

The terminal I'm using is the Windows Terminal

**Comment by rgwood** [comment]
Did a bisect and it looks like this broke on b90d701f89255af4620d775d1fc13ca1a51bc1a2

**Comment by rgwood** [comment]
Good news, I believe this has already been fixed: https://github.com/nushell/nushell/pull/7352

Looks like you'll need to update your `config.nu`. Sorry for the inconvenience!
