### ISSUE TITLE
Implicit cd in the trivial case

### ISSUE THREAD

**Issue by boxed** [nushell/nushell#751]
```
> ..
error: Permission denied (os error 13)
```

This is a bit silly. Implicit cd like what fish does would be very nice!

**Comment by coolshaurya** [comment]
I wonder if this is a feature needed by a lot of users and whether it is useful.

I personally do not appreciate this feature as I always just type `cd ` .

**Comment by boxed** [comment]
Once you start using it you will never want to go back :P

**Comment by coolshaurya** [comment]
We should let  the maintainers decide on this :) .

**Comment by andrasio** [comment]
#900

**Comment by jonathandturner** [comment]
This is now supported, closing
