### ISSUE TITLE
Some `encode` issues

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7514]
### Describe the bug

1. `utf16`, without the hyphen, is not recognised:
```
〉"A" | encode utf8
Length: 1 (0x1) bytes | printable whitespace ascii_other non_ascii
00000000:   41                                                   A
〉"A" | encode utf-8
Length: 1 (0x1) bytes | printable whitespace ascii_other non_ascii
00000000:   41                                                   A
〉"A" | encode utf16
Error:
  × utf16 is not a valid encoding, refer to https://docs.rs/encoding_rs/0.8.23/encoding_rs/#statics for a valid list of encodings
   ╭─[entry #37:1:1]
 1 │ "A" | encode utf16
   ·              ──┬──
   ·                ╰── invalid encoding
   ╰────


〉"A" | encode utf-16
Length: 1 (0x1) bytes | printable whitespace ascii_other non_ascii
00000000:   41                                                   A
```
2. When encoding a character that doesn't exist in that encoding format, the character is converted to a HTML entity (instead of throwing an error)
```
〉"🎈" | encode shift-jis
Length: 9 (0x9) bytes | printable whitespace ascii_other non_ascii
00000000:   26 23 31 32  37 38 38 30  3b                         &#127880;
```

### How to reproduce

See above

### Expected behavior

See above

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.2                                   |
| branch             | main                                     |
| commit_hash        | 774769a7ada3e5f8433d1ad1e6c12606ece664a4 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.2                                   |
| build_time         | 2022-12-17 23:52:36 +10:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
1. the crate we use doesn't have utf16 as a valid item - see the link it shows you https://docs.rs/encoding_rs/0.8.28/encoding_rs/#statics (probably should change it to latest like https://docs.rs/encoding_rs/latest/encoding_rs/index.html#statics)
2. agreed, that's weird.

**Comment by webbedspace** [comment]
> 1. the crate we use doesn't have utf16 as a valid item

It also doesn't have `utf8` as a valid item………………… and yet, see example.

**Comment by fdncred** [comment]
i wonder if someone added some helpers for utf8 or something?

**Comment by webbedspace** [comment]
This is actually a bug in https://github.com/whatwg/encoding/blob/main/encodings.json , which the encoding crate uses: notice "utf8" is present in that file but not "utf16".
