### ISSUE TITLE
`explore` config deserialization may not be working

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#7518]
### Describe the bug

@zhiburt something is broken somewhere maybe not even with this PR, but I don't see any highlights anymore when in cursor mode, nor do I see the config.cursor_color being respected. I'm using the default config and I'm not sure it's being processed.

If i do `:config-show` I can see that things don't look right and don't match my config.nu explore section. Some of the color records are being treated as strings. This is with the default config in my config.nu.
<img width="946" alt="Screenshot 2022-12-18 at 7 23 47 AM" src="https://user-images.githubusercontent.com/343840/208300803-3ff88310-ea32-4f97-b0e3-34945078dc1f.png">
This is with no config at all for explore in my config.nu
<img width="943" alt="Screenshot 2022-12-18 at 7 31 37 AM" src="https://user-images.githubusercontent.com/343840/208301163-408895f7-c1d3-457e-9782-257cb5c636aa.png">

I'm convinced the config either isn't being read correctly or it is being overwritten somewhere. I put this as my config for explore and it's being ignored. The colors don't show up when using explore and when i do config-show, there are no colors that show up for these two settings.
```
  explore: {
    config: {
        cursor_color: 'red'
    }
    table: {
        selected_cell: { bg: 'blue' }
    }
  }
```

Another thing I noticed while looking at the code is we need to change all `Rgb` colors to named colors. There are a bunch of named colors now as I added another 256 yesterday. Rgb assumes that you have a terminal that supports 24-bit color and we cannot assume that.

`:tweak config.cursor_color red` definitely works.

I'm guessing that this function isn't working right but I could be wrong.
```rust
fn insert_style(map: &mut HashMap<String, Value>, key: &str, value: Style) {
```

### How to reproduce

see above

### Expected behavior

deserialize into nushell colors/styles properly

### Configuration

|key|value|
|-|-|
|version|0.72.2|
|branch|get_ignore_error|
|commit_hash|864e42e290ae4b97c49ea3d35b3388d40b2da275|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.65.0 (897e37553 2022-11-02)|
|rust_channel|1.65.0-aarch64-apple-darwin|
|cargo_version|cargo 1.65.0 (4bc8f24d3 2022-10-20)|
|pkg_version|0.72.2|
|build_time|2022-12-10 07:07:39 -06:00|
|build_rust_channel|debug|
|features|database, default, trash, which, zip|
|installed_plugins|custom-value generate, custom-value generate2, custom-value update, from parquet, gstat, inc, nu-example-1, nu-example-2, nu-example-3, pnet, query, query json, query web, query xml, regex|

### Additional context

/cc @zhiburt

**Comment by zhiburt** [comment]
> I'm convinced the config either isn't being read correctly or it is being overwritten somewhere

Actually it was true.
Must be fixed with #7520 

> If i do :config-show I can see that things don't look right and don't match my config.nu explore section. Some of the color records are being treated as strings. This is with the default config in my config.nu.

As far as I understand nushell doesn't support records nested more then 2 layers and treats it as strings.
(I might be wrong here).

In any way we can change the output to have a better look, BUT we wouldn't able to copy&paste it then.
So I am not sure whether it's right.

**Comment by zhiburt** [comment]
> I'm convinced the config either isn't being read correctly or it is being overwritten somewhere

Actually it was true.
Must be fixed with #7520 

> If i do :config-show I can see that things don't look right and don't match my config.nu explore section. Some of the color records are being treated as strings. This is with the default config in my config.nu.

As far as I understand nushell doesn't support records nested more then 2 layers and treats it as strings.
(I might be wrong here).

In any way I've changed the output to have a better look, but I am not sure whether it's good as it will be harder to copy&paste.

![image](https://user-images.githubusercontent.com/20165848/208309240-b0183501-5c52-44f1-8d30-427db80a23b1.png)

**Comment by zhiburt** [comment]
PS: It would be cool to change a color of a HEX rgb string accordingly

**Comment by fdncred** [comment]
> As far as I understand nushell doesn't support records nested more then 2 levels and treats it as strings.
> (I might be wrong here).

The menus in the config file serialize pretty deeply. I've never really counted how many levels but here's an example of one that works just fine that's pretty deep.
```
  menus: [
  {
    name: fzf_history_menu_fzf_ui
    only_buffer_difference: false
    marker: "# "
    type: {
      layout: columnar
      columns: 4
      col_width: 20
      col_padding: 2
    }
    style: {
      text: green
      selected_text: green_reverse
      description_text: yellow
    }
    source: { |buffer, position|
      open $nu.history-path | get history.command_line
      | to text | fzf +s --tac | str trim
      | where $it =~ $buffer
      | each { |v| {value: ($v | str trim) } }
    }
  }
```

> PS: It would be cool to change a color of a HEX rgb string accordingly

I'm not sure what you mean.

I'll try out your PR in a few minutes. Thanks!
