### ISSUE TITLE
Delay after hitting escape with `edit_mode: vi`

### ISSUE THREAD

**Issue by pnotequalnp** [nushell/nushell#7521]
### Describe the bug

After hitting escape in insert mode, there's a short delay before entering normal mode. During this delay, if I press a key, that keypress is swallowed, entering normal mode is cancelled, and any subsequent normal mode commands are instead entered as gibberish in insert mode.

### How to reproduce

1. Hit escape
2. Hit another key

### Expected behavior

Enter normal mode and perform the typed normal mode commands.

### Screenshots

Here's an [asciinema recording](https://asciinema.org/a/yGViv6MwmdoIausEFLjGzdVbm) of me doing the same thing (`<Esc>kkkkkk`) in nu and bash.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.70.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0                                    |
| cargo_version      | cargo 1.64.0                                    |
| pkg_version        | 0.70.0                                          |
| build_time         | 1980-01-01 00:00:00 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

I figure this may be related to the `timeout` family of Vim settings, i.e. [`:h timeout`](https://vimhelp.org/options.txt.html#%27timeout%27).

**Comment by fdncred** [comment]
Does the problem still exist in 0.72.1? 0.70.0 is > 6 weeks old and we're moving pretty fast.

**Comment by Atemu** [comment]
I can't repro this on 0.92.1.

**Comment by fdncred** [comment]
Thanks
