### ISSUE TITLE
`rename | rename | rename` only has an effect on the last column

### ISSUE THREAD

**Issue by KSXGitHub** [nushell/nushell#7526]
### Describe the bug

I am trying to parse a tab-separated table, but cannot rename the columns.

### How to reproduce

First, create a file named `input.txt` with the following content:

```txt
Tor Browser Launcher	com.github.micahflee.torbrowser-launcher	flathub	stable	current
Flatseal	com.github.tchx84.Flatseal	flathub	stable	current
ProtonPlus	com.vysp3r.ProtonPlus	flathub	stable	current
Komikku	info.febvre.Komikku	flathub	stable	current
Upscaler	io.gitlab.theevilskeleton.Upscaler	flathub	stable	current
Black Fennec	org.blackfennec.app	flathub	stable	current
Tagger	org.nickvision.tagger	flathub	stable	current
```

Run this command:

```nu
open input.txt
  | lines
  | split column "\t"
  | rename column1 name
  | rename column2 application
  | rename column3 origin
  | rename column4 branch
  | rename column5 options
```

### Expected behavior

All the columns are named.

### Screenshots

![screenshot](https://user-images.githubusercontent.com/11488886/208409761-17e4fe3e-051e-4362-9e29-c9a05c3789a1.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.71.0                                          |
| branch             | makepkg                                         |
| commit_hash        | 6cc4ef6c706ebbdc5b995013e0b00f77f7a4dba7        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.65.0 (Arch Linux rust 1:1.65.0-1)       |
| cargo_version      | cargo 1.65.0                                    |
| pkg_version        | 0.71.0                                          |
| build_time         | 2022-11-09 06:34:03 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by sholderbach** [comment]
I had to look up the `help rename` as well to see what's going wrong.

```
Usage:
  > rename {flags} ...(rest)

Flags:
  -h, --help - Display the help message for this command
  -c, --column <List(String)> - column name to be changed

Signatures:
  <record> | rename -> <record>
  <table> | rename -> <table>

Parameters:
  ...rest <string>: the new names for the columns

Examples:
  Rename a column
  > [[a, b]; [1, 2]] | rename my_column

  Rename many columns
  > [[a, b, c]; [1, 2, 3]] | rename eggs ham bacon

  Rename a specific column
  > [[a, b, c]; [1, 2, 3]] | rename -c [a ham]

  Rename the fields of a record
  > {a: 1 b: 2} | rename x y

```

`rename` without a flag will just place the list of names given in order of appearance to the columns. 
Your use resembles the `-c` option (which I find confusing that it uses a list instead of a record).

Question would be if we should raise a warning if you try to rename with a number of columns/keys that is not equal to the number of available columns. My initial assumption based on how the `upsert`/`update` family works would have been the same as yours.

**Comment by fdncred** [comment]
I've seen people stub their toe on this before thinking that rename was some key=value pair, when it's just much simpler than that, like the second example shows.

To rename the columns in this input
```
open input.txt
  | lines
  | split column "\t"
  | rename column1 name
  | rename column2 application
  | rename column3 origin
  | rename column4 branch
  | rename column5 options
```
it would simply be
```
open input.txt
  | lines
  | split column "\t"
  | rename name application origin branch options
```

The other problem with the `-c` flag is that it seems like you can only rename one column so you have to chain a bunch, which seems like a pain to me.
```
[[a, b, c]; [1, 2, 3]] | rename -c [a ham] | rename -c [b eggs] | rename -c [c bacon]
```
The place that the `-c` flag really comes in handy is if you want to rename one column in the middle like
```
[[a, b, c]; [1, 2, 3]] | rename -c [b eggs] 
```

I agree that if it were a record, I think it would be easier, something like:
```
[[a, b, c]; [1, 2, 3]] | rename -c {a: ham, b: eggs c: bacon}
```

**Comment by theAkito** [comment]
Related to https://github.com/nushell/nushell/issues/7085.

**Comment by WindSoilder** [comment]
If #10526 is ok, you can use `[[a, b, c]; [1, 2, 3]] | rename -c {a: ham, b: eggs c: bacon}` to rename columns.
