### ISSUE TITLE
Local test failure induced by compilation order

### ISSUE THREAD

**Issue by sholderbach** [nushell/nushell#7528]
I semi-regularly observe the following test failing when running different subsets of the tests locally.

```
failures:

---- commands::each::each_implicit_it_in_block stdout ----
=== stderr

thread 'commands::each::each_implicit_it_in_block' panicked at 'assertion failed: `(left == right)`
  left: `""`,
 right: `"ace"`', crates/nu-command/tests/commands/each.rs:72:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    commands::each::each_implicit_it_in_block
```

https://github.com/nushell/nushell/blob/dae1b9a996e7670d534df17ff2a6c5788e53a2e9/crates/nu-command/tests/commands/each.rs#L63-L73

## Steps to reproduce

Do not always run `cargo build --all`/`cargo test --all`

e.g. just `cargo build`/`cargo run` that only creates the main `nu` executable
Accidentally the less helpful `cargo test` or `cargo test -p nu-command`  to just test command stuff

or use the rust analyzer generated test commands like (e.g. clicking on a `Run Test` action in VS code or executing the same action in the NeoVim integration of rust analyzer):

`cargo test --package nu-command --test main --features extra -- commands::each::each_no_args_in_block --exact --nocapture`

## Platform

Ubuntu 20.04 WSL2 under Windows 10

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.2                                   |
| branch             | main                                     |
| commit_hash        | 33aea56ccd21238cf510b6683a16cacfc0badf36 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.72.2                                   |
| build_time         | 2022-12-15 18:09:05 +01:00               |
| build_rust_channel | debug                                    |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
Do you think it has anything to do with how the ci works differently? e.g. if I run that command I get a different result in the repl.
```
echo [[foo bar]; [a b] [c d] [e f]] | each { |it| nu --testbin cococo $it.foo } | str join
a
b
c
```
In order to replicate the output in the repl I have to add a str trim like so.
```
echo [[foo bar]; [a b] [c d] [e f]] | each { |it| nu --testbin cococo $it.foo | str trim } | str join
abc
```

**Comment by sholderbach** [comment]
My initial hunch was that the `nu --testbin`s aren't necessarily properly available. But your run shows additional weirdness.
