### ISSUE TITLE
`if` no longer has a separate environment scope

### ISSUE THREAD

**Issue by Benjamin-L** [nushell/nushell#7535]
### Describe the bug

In previous versions of nushell, `if` expressions would have their own scope, so changes to the environment inside an `if` block would not be visible outside the block. This is no longer the case, and environment changes inside `if` blocks now persist in the parent scope.

### How to reproduce

```nu
let-env x = 'y'
if true { let-env x = 'z' }
echo $env.x
```

outputs `z`.

### Expected behavior

I expected the output `y`, since the change inside the `if` block was scoped in previous versions.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.72.2                                   |
| branch             | main                                     |
| commit_hash        | b01f50bd7000389aa22ba3623e1f48ef2fcd4813 |
| build_os           | macos-aarch64                            |
| build_target       | aarch64-apple-darwin                     |
| rust_version       | rustc 1.64.0 (a55dd71d5 2022-09-19)      |
| cargo_version      | cargo 1.64.0 (387270bc7 2022-09-16)      |
| pkg_version        | 0.72.2                                   |
| build_time         | 1980-01-01 00:00:00 +00:00               |
| build_rust_channel | debug                                    |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

### Additional context

I've observed this behavior on 0.27.1 and on the main branch. I mentioned it on the discord, assuming that it was an intentional change, but it sounds like that's not the case.

**Comment by jntrnr** [comment]
Blocks are now able to update the environment. One way to think about it is that each function gets its own environment. With the split of blocks and closures, blocks will update the environment of the function they're inside of. Closures, on the other hand, will create their own environment.

If you want something similar to the previous style, you could use a workaround like:

```
if true { do {|| let-env ... } }
```

**Comment by Benjamin-L** [comment]
Oh, good to know. This is something that might be worth calling out in the release notes for 0.72. I read the release notes, but definitely didn't realize that this behavior had changed intentionally, and it's a pretty significant breaking change.
