### ISSUE TITLE
Add open . command works for opening directory

### ISSUE THREAD

**Issue by mindgitrwx** [nushell/nushell#7546]
### Related problem

Currently, NuShell does not support the ability to open the current directory with the 'open .' command. 

### Describe the solution you'd like

This is a common feature in other shells and can be useful for quickly viewing and manipulating the contents of the current directory. I propose adding this functionality to NuShell by modifying the 'open' command to accept a '.' argument, which would open the current directory in the default file manager.

**Comment by rgwood** [comment]
If you're on MacOS, you can call the system `open` with `^open`: https://www.nushell.sh/book/escaping.html
