### ISSUE TITLE
Portable nu still use history, login.nu and plugin.nu from user filder

### ISSUE THREAD

**Issue by darwis059** [nushell/nushell#7547]
### Describe the bug

running nushell as portable apps still use history, login.nu, and plugin.nu from user directory. the `config nu` command also open config from user directory.
```
config-path        │ E:\SyncThing\totalcmd\App\WezTerm\nushell\config.nu                                                                                                                              
env-path           │ E:\SyncThing\totalcmd\App\WezTerm\nushell\env.nu                                                                                                                                 
history-path       │ C:\Users\darwi\AppData\Roaming\nushell\history.txt                                                                                                                               
loginshell-path    │ C:\Users\darwi\AppData\Roaming\nushell\login.nu                                                                                                                                  
plugin-path        │ C:\Users\darwi\AppData\Roaming\nushell\plugin.nu
```

### How to reproduce

download the portable version, and run it.
then execute command `$nu.history-path` `$nu.loginshell-path` and `$nu.plugin-path` to view the config.

### Expected behavior

the history, login.nu, and plugin.nu path should point to current directory of executable nu.exe location.
`config nu` command should open config from portable directory.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.73.0                                   |
| branch             |                                          |
| commit_hash        | 1291b647aee4a566a69fc5786b5437cff3976d1b |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.73.0                                   |
| build_time         | 2022-12-20 18:21:29 +00:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

### Additional context

test on windows.

**Comment by fdncred** [comment]
nushell is not intended to be used as a portable app because you cannot change these paths.
