### ISSUE TITLE
Want `each` support new-line-brace style.

### ISSUE THREAD

**Issue by yhm-amber** [nushell/nushell#7548]
### Related problem

I try this:

~~~ nu
ls | where type == dir | each { |x| ... }
~~~

it is okay, but while I format it in this style:

~~~~ nu
ls | where type == dir |
    each
    { |x|
        ...
    }
~~~~

the Nu give me err after `each` :

![S21221-10532464](https://user-images.githubusercontent.com/103625580/208809553-d10d0580-1b17-48dc-82c5-defefe3caecf.png)

so I can't format in my style ....

### Describe the solution you'd like

Support new-line brace style.

----

Such as, let this:

~~~
xxx
{ ...
    ...
... }
~~~

be parsed as:

~~~
xxx { ... ... ... }
~~~

at first, for all the `xxx` that need to follow a `{...}` .

**Comment by fdncred** [comment]
You have to do it like this
```
ls | where type == dir |
    each { 
      |x|
      ...
    }
```

**Comment by yhm-amber** [comment]
> You have to do it like this
> 
> ```
> ls | where type == dir |
>     each { 
>       |x|
>       ...
>     }
> ```

I need the next line brace style so there is this issue ...

... But no problem, I just found a way !

**Comment by yhm-amber** [comment]
I FOUND A WAY TO MAKE A SETTLEMENT !

For this:

~~~ nu
ls | where type == dir | each { |x| ... }
~~~

if I want a next-line brace style, I just need to add a `( )` like this:

~~~~ nu
(ls | where type == dir |
    each
    { |x|
        ...
    })
~~~~

then, **it works**. 🙃

-----

ref: https://www.nushell.sh/book/pipelines.html#multi-line-pipelines

> If a pipeline is getting a bit long for one line, you can enclose it within ( and ) to create a subexpression:
> 
> ~~~ nu
> (
>     "01/22/2021" |
>     parse "{month}/{day}/{year}" |
>     get year
> )
> ~~~
>

**Comment by yhm-amber** [comment]
> Same as `if` . this:
> 
> ```nu
> if (...)
> { ... }
> else
> { ... }
> ```
> 
> will err as `missing then_block` , but this:
> 
> ```nu
> (if (...)
> { ... }
> else
> { ... })
> ```
> 
> will be right .
> 
> And for `def` is same too .
> 

**NO**

It dont work on `if` or `def` . Just won't err sometimes.

**Comment by kubouch** [comment]
Having opening brace is something Nushell cannot support because it is not clear whether
```
each
{|x| ... }
```
means calling `each` command and `{|x| ... }` separately, or calling `each {|x| ... }` together. Currently, we have no plans supporting it.
