### ISSUE TITLE
records on color config doesn't work in 0.73

### ISSUE THREAD

**Issue by kurokirasama** [nushell/nushell#7551]
### Describe the bug

For instance, I have defined:
```
$env.config.color_config.shape_internalcall = { fg: "##00b7ff" attr: b}
```
but commands are just white.

### How to reproduce

Already described

### Expected behavior

builtin command should be colorized

### Screenshots

![Screenshot from 2022-12-21 10-43-36](https://user-images.githubusercontent.com/5784951/208919448-cd24811a-afb6-4db6-930f-22849dcd408a.png)

### Configuration

| key                | value                                                                                                                         |
| ------------------ | ----------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.73.0                                                                                                                        |
| branch             | main                                                                                                                          |
| commit_hash        | 1291b647aee4a566a69fc5786b5437cff3976d1b                                                                                      |
| build_os           | linux-x86_64                                                                                                                  |
| build_target       | x86_64-unknown-linux-gnu                                                                                                      |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)                                                                                           |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu                                                                                               |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)                                                                                           |
| pkg_version        | 0.73.0                                                                                                                        |
| build_time         | 2022-12-21 01:37:16 -03:00                                                                                                    |
| build_rust_channel | release                                                                                                                       |
| features           | database, dataframe, default, trash, which, zip                                                                               |
| installed_plugins  | custom-value generate, custom-value generate2, custom-value update, gstat, inc, pnet, query, query json, query web, query xml |

**Comment by sholderbach** [comment]
#7141 is limited to the output values (types without `shape_` prefix) if I understand it correctly. So it won't highlight differently in source code. (Furthermore we discovered yesterday when playing with it for the release notest that singular values that don't get displayed via `nu-table` primitives don't get colored)
