### ISSUE TITLE
Let the closure color config also cover non-table output

### ISSUE THREAD

**Issue by sholderbach** [nushell/nushell#7554]
### Related problem

#7141 introduced conditional coloring by assigning a closure to a type's color config.
It currently only supports values that are displayed as cells in a table.
![grafik](https://user-images.githubusercontent.com/15833959/208945510-c6fb7a03-ba1f-4735-8e9f-a4ffecf3fc40.png)

### Describe the solution you'd like

Also cover single values.

**Comment by fdncred** [comment]
@webbedspace this is kind of related to your PR mentioned above. what are your thoughts on this?

**Comment by webbedspace** [comment]
Honestly I've always been surprised that color_config never affected anything outside of `table` display in the first place… it'd be swell if it did.
