### ISSUE TITLE
whenever i "source" a definitions file it open in my editor

### ISSUE THREAD

**Issue by schmitzli** [nushell/nushell#7571]
### Question

When i use the source command to load a file, it opens in my editor. 
It's also interpreted by the shell as expected.

It's launched with the windows filetype association (the editor).
It's like using the "start" on the file in windows.

Is this intended?
I wonder if this behavior can be configured?

### Additional context and details

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.73.0                                   |
| branch             |                                          |
| commit_hash        | 1291b647aee4a566a69fc5786b5437cff3976d1b |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.73.0                                   |
| build_time         | 2022-12-20 18:21:29 +00:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I can't reproduce this on windows. I wonder if you have your `.nu` extension associated with something and windows is getting confused somehow?

I just did `source register-plugins.nu` and it seems to work as expected.

**Comment by schmitzli** [comment]
yes, of course i have associated .nu with the editor :-)

and when i'm not in the directory of the file (found via library path ) then i get the windows "command not found exception"
even since i added source forg.nu to my config.nu 
```
The "forg.nu" command is either misspelled or
could not be found.
```
![image](https://user-images.githubusercontent.com/22212302/209182281-6cef6d19-092f-45ff-8f44-53b18f551eb8.png)

**source** is only understood by nu, there is nothing like this in my path.
Same behavior when using a reload alias.
Behavior was the same with 0.72.1, before that i used 0.27 which did not had this issue ;-)

**Comment by schmitzli** [comment]
i tested with a simple script in .txt and .js and .nu and none of it showed the effect....

so it was my script that did it with 
```
# startup definitione
let STARTUP_FILE = C:\Users\Stefan\Workspace\nu\forg.nu

# search in startup file
def search-def [hint] { open $STARTUP_FILE | lines | where $it =~ $hint }
```
i guess i do not need this anymore with new nu ;-)
