### ISSUE TITLE
Cache compiled regexes

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#7572]
### Related problem

Nu's `=~` regex evaluation compiles the regex every time: https://github.com/nushell/nushell/blob/046e46b962b6538b3b4b25f846a6dee48f65c1f7/crates/nu-protocol/src/value/mod.rs#L2626-L2628

This is pretty slow when evaluating the same regex repeatedly,and the speed of regex evaluation has recently come up in the context of `color_config` closures: https://github.com/nushell/nushell/pull/7141#issuecomment-1361553554

### Describe the solution you'd like

We could add a global cache for compiled regexes - something like a `HashMap<String, Regex>`. Some care would need to be taken to ensure that the cache does not grow forever (maybe implement it with a limited-capacity FIFO queue?).

**Comment by fdncred** [comment]
I'm wondering if this is something we could add in `engine_state` or `stack` this is passed around everywhere?
