### ISSUE TITLE
Piping a `list<string>` to an external command should "just work"

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#7576]
### Related problem

If you pipe a Nushell list/table to an external command, it gets rendered with the full border and row numbers etc:

```bash
> ls | get name | some-program-that-just-copies-stdin-to-stdout
╭───┬────────────╮
│ 0 │ Cargo.lock │
│ 1 │ Cargo.toml │
│ 2 │ src        │
│ 3 │ target     │
╰───┴────────────╯
```

[This frequently surprises users](https://github.com/nushell/nushell.github.io/pull/713); they expect `list<string>` to be formatted as strings separated by newlines. To get that behaviour, they need to pipe the list to `str join (char nl)` or `to text` before the external:

```bash
> ls | get name | str join (char nl) | some-program-that-just-copies-stdin-to-stdout
Cargo.lock
Cargo.toml
src
target
```

### Describe the solution you'd like

I think that Nu should have smarter defaults when piping a `list<string>` or a `ListStream` of strings to an external command - it should skip formatting with a border, and simply append a newline to each string value.

There are some difficult edge cases that we need to think through - for example, what do we do with lists that contain strings *and* records? What if a `ListStream` starts out returning strings, then starts returning records partway through?

**Comment by Tengs-Penkwe** [comment]
there is another [issue](https://github.com/nushell/nushell/issues/5617) about this topic.

**Comment by rgwood** [comment]
Thanks! I thought I remembered something but couldn't find it...
