### ISSUE TITLE
Azure pipelines currently failing on Linux

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#758]
Judging from the error: 

![image](https://user-images.githubusercontent.com/547158/65983715-ad1eef80-e4da-11e9-8c97-194d87fc188c.png)

It looks like we need to install the optional dependencies in Linux for Azure pipelines to work.

**Comment by vsoch** [comment]
Looks similar to this https://github.com/amethyst/evoli/issues/23

**Comment by jonathandturner** [comment]
Yeah, it seems similar. Since we're building with `--all-features`, it would require a few optional dependencies installed (https://book.nushell.sh/en/installation#dependencies)

I'm just wondering what changed recently (maybe it changed on the Azure Pipelines side?). I don't remember seeing this before in Azure.

**Comment by jonathandturner** [comment]
I think I have this fixed with #768
