### ISSUE TITLE
Users should have more visibility into streaming

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#7581]
### Related problem

Without looking at the Nu code, it's very difficult to tell whether any given command streams its data. `describe` collects any ListStreams passed to it, and ListStreams are indistinguishable from lists:

```
〉# a Value::List of ints
〉[1 2 3] | describe
list<int>

〉# a ListStream of ints
〉[1 2 3] | each {|i| $i} | describe
list<int>
```

### Describe the solution you'd like

I would like some way for users to be able to see whether a list is a stream or not. I expect that most users won't care about this information, but users working with large files and streams care a lot:

- https://github.com/nushell/nushell/issues/6178#issuecomment-1288357024
- https://www.reddit.com/r/rust/comments/tkdct3/comment/i1smsmk/

Some ideas:

1. Add stream info to the existing `describe` output like `list<int> (stream)`
    1. Pro: simple
    2. Con: must collect entire ListStream to report its type. Not always possible for large or slow streams
2. Add a flag to `describe` that skips collecting ListStreams and simply reports them as "ListStream"
    1. Pro: avoids collecting values
    2. Con: adds a flag that will be rarely used

Perhaps we should do both.

**Comment by fdncred** [comment]
+1 for a both adding stream info to `describe` and adding a flag like `describe --do-not-collect` (whatever flag name is applicable)

**Comment by webbedspace** [comment]
Idea tenuously related to this: maybe stream-collecting could be added to commands' help docs? If it collects a stream, it should be mentioned somewhere in its help (and as a boolean on `$nu.scope.commands`).
