### ISSUE TITLE
`save` should stream data whenever possible

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#7590]
### Related problem

`save` collects input data in a few situations where it doesn't always need to:

https://github.com/nushell/nushell/blob/3d682fe95726b960f17c72c2e11fd459ff6572dc/crates/nu-command/src/filesystem/save.rs#L151-L153

https://github.com/nushell/nushell/blob/3d682fe95726b960f17c72c2e11fd459ff6572dc/crates/nu-command/src/filesystem/save.rs#L237

### Describe the solution you'd like

`save` should always stream `ListStream` input into a file instead of attempting to collect it all.

It should be possible to stream to a file slowly:
```bash
1..100 | each { |i| sleep 400ms; $i} | save -f output.txt
```
And watch individual lines (or batches of lines) arrive with `tail --follow` in another shell:
```bash
tail --follow output.txt
```

### Additional context and details

Hat tip to this comment: https://github.com/nushell/nushell/issues/6178#issuecomment-1288357024

**Comment by NotLebedev** [comment]
Could fix this issue after PR https://github.com/nushell/nushell/pull/7608 with refactoring of `save` is reviewed and merged.
