### ISSUE TITLE
`list<string>` values are not shown if a string is too wide

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#7591]
### Describe the bug

If a `list<string>` contains a string that is too long, the string is replaced with `...` instead of being truncated for display purposes

```bash
〉term size
╭─────────┬─────╮
│ columns │ 103 │
│ rows    │ 54  │
╰─────────┴─────╯
〉["foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobar"]
╭───┬─────╮
│ 0 │ ... │
╰───┴─────╯
〉["foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz fooba"]
╭───┬─────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 0 │ foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz foobarbaz fooba │
╰───┴─────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### How to reproduce

1. Figure out your terminal width with `term size`
2. Display a list with a string that is around the same width as your terminal

### Expected behavior

I expected at least part of each string to be shown somehow, perhaps truncated if necessary. And `table -e` should definitely expand each field, but it does not.

### Screenshots

I appreciate that it's not always obvious when to hide information and when to show it, but let's use horizontal space better than this:

![image](https://user-images.githubusercontent.com/26268125/209418345-e972a063-6037-4bf7-9dfe-b674db03c5ec.png)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.73.1                                   |
| branch             | main                                     |
| commit_hash        | a43e66ef9273a0047fcc61184bf82e06152353e3 |
| build_os           | linux-x86_64                             |
| build_target       | aarch64-unknown-linux-musl               |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.73.1                                   |
| build_time         | 2022-12-24 00:07:25 +00:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I wonder if it has something to do with the table settings.  I get this
<img width="1143" alt="Screenshot 2022-12-23 at 9 48 25 PM" src="https://user-images.githubusercontent.com/343840/209420213-1901c64d-5f92-4d4f-8d18-ba1016f1bc81.png">
I'm not sure what the `...` is for because the entire list is shown.

This is my table settings.
```
  table: {
    mode: rounded # basic, compact, compact_double, light, thin, with_love, rounded, reinforced, heavy, none, other
    index_mode: always #  "always" show indexes, "never" show indexes, "auto" = show indexes when a table has "index" column
    trim: {     # A strategy of managing table view in case of limited space.
      methodology: wrapping # truncating or wrapping
      wrapping_try_keep_words: true
      # A suffix which will be used with 'truncating' methodology
      truncating_suffix: "…" # "⋯" "︙"
    }
  }
```

**Comment by rgwood** [comment]
I'm using the default `table` settings: https://github.com/nushell/nushell/blob/3d682fe95726b960f17c72c2e11fd459ff6572dc/crates/nu-utils/src/sample_config/default_config.nu#L311-L319

Nearly the same as yours (your `truncating_suffix` is a little different but I don't think that's the problem).

**Comment by fdncred** [comment]
I can also do the odd truncating thing with `table -e` and `table` adds the extra `...` column.
<img width="1265" alt="Screenshot 2022-12-24 at 6 55 54 AM" src="https://user-images.githubusercontent.com/343840/209437298-033dad17-9d29-4683-836b-df55f48f6075.png">
<img width="815" alt="Screenshot 2022-12-24 at 7 04 51 AM" src="https://user-images.githubusercontent.com/343840/209437511-75717fb6-6707-45d9-9906-52da405cc2f1.png">
