### ISSUE TITLE
`def`: Maybe stop allowing `,` between the long and short forms of flags (like `--foo, (-w)`)

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7604]
### Related problem

```
〉def b [--foo, (-w)] { }
〉help b
Usage:
  > b {flags}

Flags:
  -w, --foo -
  -h, --help - Display the help message for this command

〉def b [--foo (-w)] { }
〉help b
Usage:
  > b {flags}

Flags:
  -w, --foo -
  -h, --help - Display the help message for this command
```
The first form `def b [--foo, (-w)] { }` is the same as the second form `def b [--foo (-w)] { }`, but it confused me for a good long while because it "looks wrong" to me. The comma separating them shouldn't, I feel, be allowed, because it makes the flags feel disconnected, and it also makes it difficult to mentally parse a long list of args.

### Describe the solution you'd like

Consider removing support for the comma between long flags and their short forms. I've reviewed `parse_signature_helper()` and it seems relatively easy. Also, [the comma form isn't listed anywhere in the Nushell docs](https://www.nushell.sh/book/custom_commands.html), so it's not likely to be well-used.

**Comment by fdncred** [comment]
I agree. I even prefer the old way which was `def b [--foo(-w)] {}`
