### ISSUE TITLE
Support for -- (double dash) in extern def

### ISSUE THREAD

**Issue by ggallovalle** [nushell/nushell#7609]
### Related problem

I am trying to describe a CLI like 

1. cargo test
2. cargo run
3. npm run
4. npm exec

All this have in common that they accept a `--` (double dash) with signifies that is the end of the flags and positional arguments of the command and after it you pass args to the underlying cli.

For example see the following help texts:

![image](https://user-images.githubusercontent.com/25666813/209586838-925268f7-2bf0-426a-9e55-9248c499aef2.png)
![image](https://user-images.githubusercontent.com/25666813/209586859-b8ef355f-f77f-4e81-9f22-d071b9a823b3.png)
![image](https://user-images.githubusercontent.com/25666813/209586872-326d5410-323f-4646-83e5-11ea44f57011.png)

### Describe the solution you'd like

That something like this could be valid syntax:

```
# Run arbitrary package scripts 
export extern "npm run" [
  command: string
 # This means that the "varargs" MUST be preceded by a double-dash
  ...--: string@"nu-complete npm run"
  --help 
  # Get help text
]
```

### Describe alternatives you've considered

Even in some cli tooks like cargo there are some times where the --(double-dash) is required and others where it is not so
the following work around would work in `cargo run` but not in `cargo test`

For example in cargo test IS required
```
# Execute all unit and integration tests and build examples of a local package
export extern "cargo test" [
  test_name?: string
  ...args: any
]
```
![image](https://user-images.githubusercontent.com/25666813/209587209-b709ced3-6f4d-4c9b-ad2a-b1db025b42b8.png)
![image](https://user-images.githubusercontent.com/25666813/209587377-368798f4-2c4f-46e7-84d5-e95bfbd095c7.png)
![image](https://user-images.githubusercontent.com/25666813/209587387-cbd7e28a-5160-4073-ba74-8daee0376224.png)

But in cargo run is not
![image](https://user-images.githubusercontent.com/25666813/209587217-2c8aba14-7e3b-4848-af8d-3d9bbf0c379e.png)

**Comment by fdncred** [comment]
We do have a new feature called [fall through signatures](https://github.com/nushell/nushell/pull/7527) that may help with this. You might try the latest main and see if you can make any progress there.

**Comment by ggallovalle** [comment]
I installed it from latest (f5d6672ccf2aada4f06efc8e9cbfe3a9c7d30f5e) and it works perfectly.
![image](https://user-images.githubusercontent.com/25666813/209876936-0b5c0cc3-2118-4376-a6f4-5db67ee10496.png)

Extern definition
![image](https://user-images.githubusercontent.com/25666813/209877017-7f74ef69-de8e-476a-a007-e0b3dad3a618.

**Comment by fdncred** [comment]
can we close this then?

**Comment by ggallovalle** [comment]
sure, thanks again
