### ISSUE TITLE
Lack of Documentation/Warning/Awareness regarding Breaking Changes

### ISSUE THREAD

**Issue by theAkito** [nushell/nushell#7614]
### Describe the bug

I've updated to the latest packages on an Arch Linux system. A short time later, I realised, that all my terminal apps would crash on opening.
I assumed it must've been related to the default shell, i.e. Nushell and here we are.

https://github.com/nushell/nushell/pull/7042

https://www.nushell.sh/book/commands/find.html#frontmatter-title-for-filters

The documentation is once again not updated & this change is already part of the previous Nushell version, so it should've been reflected in the documentation, already, I suppose.

The only way I could find out about it is the official Blog for the most up to date news about Nushell.

https://www.nushell.sh/blog/2022-11-29-nushell-0.72.html

This issue is referring to this specific issue, so the documentation for `find` can be updated, but also to raising awareness about such changes.
For example, one approach would be to mark a feature like that deprecated for one release. Then, on next release, it is actually removed. For the one release, where it is still supported, but deprecated, the user would get clearly visible deprecation warnings on each opening of the shell, as such a change can cause the shell to crash on launch, when the now deprecated feature is still used in `config.nu` or something like that.

This is just one example on how to approach this. There are other methods available, as well.

### How to reproduce

Use a deprecated feature in your `config.nu` and see how another shell launch leads into an instantaneous crash.

### Expected behavior

User should have a chance to react to deprecated changes in a short time frame. 

The release cycle of minor versions for Nushell is currently relatively tight, so I guess having one minor version grace time would be good enough for frequent users, while it would not stifle development effort deployments.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.72.1                                          |
| branch             | makepkg                                         |
| commit_hash        | 777f746127806a34ab946e7495755655cac72cec        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.65.0 (Arch Linux rust 1:1.65.0-1)       |
| cargo_version      | cargo 1.65.0                                    |
| pkg_version        | 0.72.1                                          |
| build_time         | 2022-12-12 07:20:37 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

Arch Linux x86 64-bit

**Comment by sholderbach** [comment]
We have since improved our processes around breaking changes (PRs affecting user-facing behavior in a relevant way should be labelled with [`breaking-change`](https://github.com/nushell/nushell/issues?q=is%3Aopen+label%3Abreaking-change+sort%3Aupdated-desc).
Furthermore we try to use deprecation warnings for one release cycle before removing functionality, if possible.
Failures in the configuration should also safely fall back to a default config.
