### ISSUE TITLE
Erroneous text in `ls` table

### ISSUE THREAD

**Issue by tanj** [nushell/nushell#7617]
## Platform
`sys | get host | reject sessions hostname uptime boot_time | to text`
name: Windows
os_version: 10 (19043)
long_os_version: Windows 10 Pro
kernel_version: 19043

**Terminal software** 
- alacritty 0.11.0 
- nu 0.73.0

When using `ls` in the helix editor source I get an erroneous file path show up in the table. Sometimes the text is partially obscured other times it is fully outside the table

## Steps to reproduce
1. run alacritty
2. cd to helix-core/src directory `cd d:\src\tools\helix\helix-core\src`
3. ls

### Exact steps from reproduce
![image](https://user-images.githubusercontent.com/90219/209703702-f33036a8-bb4f-44fe-bda5-f58907e94655.png)
### Other examples where it is doing other weird things but I can't give exact steps
![image](https://user-images.githubusercontent.com/90219/209704162-3b00c8e4-bb7d-4abe-ba58-fc893effaaca.png)
![image](https://user-images.githubusercontent.com/90219/209704209-1489e9b6-75ef-4aa7-af57-3d8e7bc3ac9b.png)
![image](https://user-images.githubusercontent.com/90219/209704273-ce66d889-ae3b-4bb9-8f30-b586ecab26e2.png)

**Comment by sholderbach** [comment]
Transferred to nushell/nushell for now as this seems to be on the surface related to the table display. (general output lives in nushell, mostly in `nu-table`)

**Comment by tanj** [comment]
built main (db06edc5) it is still somewhat there but automatically fixes itself.

https://youtu.be/NIutmW0Abt0

**Comment by fdncred** [comment]
I'm pretty confident nushell doesn't have code to fix itself like this. This looks like a terminal artifact to me.

**Comment by tanj** [comment]
I don't know what has changed, but I can't get it to make the error at all now either with the `winget` installed version (`0.73.0`) or my own build of main. No reboot has happened.

I don't understand where that bit of text is coming from other than `nu`. Without having dug into the codebase I'd guess there is some sort of debug output causing that string to be output. If it happens again in a repeatable way I'll dig into the code and see if I can find anything.

I'll reopen this if that happens.
