### ISSUE TITLE
list  AUR as an option to install nushell

### ISSUE THREAD

**Issue by coolshaurya** [nushell/nushell#763]
There are currently 3 AUR packages available for nushell. This is more convenient for for Arch Linux users and other AUR-supporting distros like Manjaro. Listing them would greatly help those users.

**Comment by coolshaurya** [comment]
Those 3 AUR packages are -

```
aur/nushell 0.3.0-4 (0, 0.00)
    A shell for the GitHub era
aur/nushell-bin 0.2.0-2 (2, 1.00)
    A shell for the GitHub era
aur/nushell-git r946.4a00887-5 (0, 0.00)
    A shell for the GitHub era
```

**Comment by DrSensor** [comment]
as an Arch user, the main problem with those 3 packages is each of them is maintained by different person which is confusing. Also, `nushell` and `nushell-bin` has different version.

<https://repology.org/project/nushell/versions>

**Comment by jonathandturner** [comment]
Would it be bad to just pick one? Looks like all the ones @DrSensor mentioned are currently up to date, so perhaps the situation has improved.

**Comment by coolshaurya** [comment]
> Would it be bad to just pick one?

No but the others should be mentioned.

If one is being chosen, I'd recommend using the `nushell-bin` package as that doesn't require having Rust installed (and the others require Rust to be installed).
