### ISSUE TITLE
nuon conversion error

### ISSUE THREAD

**Issue by schmitzli** [nushell/nushell#7631]
### Describe the bug

After saving a data table to a nuon file, opening the files throws  `Error while parsing as nuon`

The issue is the empty value that is not given in the nuon file, 
but just implicitly assumed with the leading comma.

I'm not sure if the conversion to nuon or from nuon is the problem.

### How to reproduce

1. tst.json data 
```
[
  {
    "checksum": "",
    "checksum_date": "2022-11-04 19:14:34"
  },
  {
    "checksum": "6ae10ab60a04aaa775c38c1d2ba087d0",
    "checksum_date": "2021-08-31 12:31:29"
  }
]
```
2. transform to tst.nuon
```
[[checksum, checksum_date]; [, "2022-11-04 19:14:34"], ["6ae10ab60a04aaa775c38c1d2ba087d0", "2021-08-31 12:31:29"]]
```
3. open tst.nuon

```
C:\Users\Stefan\Workspace\nu\dt〉open tst.nuon                                                      12/29/2022 05:29:57 Error:
  × Error while parsing as nuon
   ╭─[entry #176:1:1]
 1 │ open tst.nuon
   ·      ────┬───
   ·          ╰── Could not parse 'C:\Users\Stefan\Workspace\nu\dt\tst.nuon' with `from nuon`
   ╰────
  help: Check out `help from nuon` or `help from` for more options or open raw data with `open --raw 'C:
Error:
  × error when parsing nuon text
   ╭─[entry #176:1:1]
 1 │ open tst.nuon
   · ──┬─
   ·   ╰── could not parse nuon text
   ╰────

Error:
  × error when parsing
   ╭────
 1 │ [[checksum, checksum_date]; [, "2022-11-04 19:14:34"], ["6ae10ab60a04aaa775c38c1d2ba087d0", "2021-08-31 12:31:29"]]
   ·                             ────────────┬────────────
   ·                                         ╰── Missing columns.
   ╰────
```

### Expected behavior

the nuon file opens and behaves like the data produces is the same as saved

### Screenshots

![image](https://user-images.githubusercontent.com/22212302/210009307-2d7f0246-2695-4773-89d3-0b0f8b33a2c1.png)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.73.0                                   |
| branch             |                                          |
| commit_hash        | 1291b647aee4a566a69fc5786b5437cff3976d1b |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.73.0                                   |
| build_time         | 2022-12-20 18:21:29 +00:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by sholderbach** [comment]
Thanks for your thorough bug report, it was really easy to track down with your provided information and kind of embarrassing that we didn't catch this particular case through tests earlier.
