### ISSUE TITLE
nushell panics by alias

### ISSUE THREAD

**Issue by TornaxO7** [nushell/nushell#7648]
### Describe the bug

`nushell` panics if I enter `e` and press `tab` afterwards to open up the completion.

### How to reproduce

1. Add the following into your config (put it either in your `config.nu` or `env.nu`:
```nu
alias ea = ^$env.EDITOR /tmp/test.s
```
2. Now open up a new `nushell` and press `e` then `tab` to get the completion.

### Expected behavior

To see the completion menu.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.73.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 1291b647aee4a566a69fc5786b5437cff3976d1b                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12) (Arch Linux rust 1:1.66.0-1) |
| cargo_version      | cargo 1.66.0                                                     |
| pkg_version        | 0.73.0                                                           |
| build_time         | 2022-12-21 00:14:26 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | database, dataframe, default, trash, which, zip                  |
| installed_plugins  |                                                                  |

**Comment by kubouch** [comment]
Error message:
```
thread 'main' panicked at 'Can't create a Span whose end < start, start=18446744073709551598, end=1', C:\Users\kubouch\.cargo\registry\src\github.com-1ecc6299db9ec823\reedline-0.14.0\src\completion\base.rs:18:9
```

**Comment by Xoffio** [comment]
I am currently working on this issue. so far I know where the bug is and kind of know why it is happening 

here the variable `offset` is greater than `span.start` so there is a underflow problem.
https://github.com/nushell/nushell/blob/cef05d35534d36f314cb59d8b703e1ce08ea5939/crates/nu-cli/src/completions/command_completions.rs#L97

There is also a possible problem here:
https://github.com/nushell/nushell/blob/cef05d35534d36f314cb59d8b703e1ce08ea5939/crates/nu-cli/src/completions/variable_completions.rs#L52

I would love to solve this bug. Does anyone knows what the offset variable actually means?

**Comment by kubouch** [comment]
Cool, thanks for digging in! It might be the cursor position but I haven't worked on the completions code, I'm not sure. You might need to backtrack the function and see how it is used.

**Comment by Windforce17** [comment]
Add another reproducible case when I  was learning from book :
```sh
 alias ll = ls -l
 ```
 And type  `ll -a|c` then press tab :`thread 'main' panicked at 'byte index 9 is out of bounds of  ll -a|c ', library/core/src/str/mod.rs:107:9` ,don't know if it's the same reason

**Comment by Xoffio** [comment]
@Windforce17 This is similar problem. I think easier to fix. I am looking into it

**Comment by Xoffio** [comment]
update for those who really need to use this feature while we try to solve the bug
```nu
alias ll = ls -l
```
you can have the alias name match the length of the command. Example in this case:
```nu
alias lalala = ls -l
```
