### ISSUE TITLE
SSL error on 0.3.0 Release: on Debian GNU/Linux 9.9 (stretch)

### ISSUE THREAD

**Issue by avimar** [nushell/nushell#765]
```
wget https://github.com/nushell/nushell/releases/download/0.3.0/nu_0_3_0_linux.tar.gz
tar -zxvf nu_0_3_0_linux.tar.gz
cd nu_0_3_0_linux
./nu
error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

I even have the dependencies: `apt install pkg-config libssl-dev`

Seems related to  https://github.com/nushell/nushell/issues/646
I ran the related debug code: `ldconfig --verbose | grep ssl`:

```
ldconfig: Path `/lib/x86_64-linux-gnu' given more than once
ldconfig: Path `/usr/lib/x86_64-linux-gnu' given more than once
ldconfig: /lib/x86_64-linux-gnu/ld-2.24.so is the dynamic linker, ignoring

        libssl.so.1.1 -> libssl.so.1.1
        libssl.so.1.0.2 -> libssl.so.1.0.2
        libssl3.so -> libssl3.so
ldconfig: /lib32/ld-2.24.so is the dynamic linker, ignoring

ldconfig: /libx32/ld-2.24.so is the dynamic linker, ignoring
```

**Comment by jonathandturner** [comment]
This sounds related to https://github.com/nushell/nushell/issues/717 (and some of the other SSL-related issues)

A similar fix may help for now until we roll out the next set of binaries (which, with luck, won't have this issue)

**Comment by avimar** [comment]
Still same error on 0.4.0

> error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by jonathandturner** [comment]
So you still get this issue, even though libssl is provided as part of the .tar.gz?

Are you on a 32-bit system, by chance?

**Comment by avimar** [comment]
> So you still get this issue, even though libssl is provided as part of the .tar.gz?
> 
> Are you on a 32-bit system, by chance?

Nope, Linode: Linux worker-data 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_**64** GNU/Linux

**Comment by andrasio** [comment]
@avimar Hi! Are you still experiencing issues?

**Comment by avimar** [comment]
> @avimar Hi! Are you still experiencing issues?

Still broken.

```
~/nushell_0_4_0# ./nu
./nu: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

Any further commands to for debugging?

**Comment by avimar** [comment]
/nushell_0_5_0# ./nu
./nu: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by avimar** [comment]
~/nushell_0_6_0# ./nu
./nu: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by avimar** [comment]
New errors:
~/nu_0_7_0_linux/nushell_0_7_0# ./nu

./nu: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./nu)
./nu: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./nu)

**Comment by jonathandturner** [comment]
nevermind, I missed you mentioned that earlier

**Comment by jonathandturner** [comment]
I'm starting to wonder if Linux binaries just aren't portable, even if you build them against minimal requirements (like libc and libm).  We might just need to have someone help us build binaries for multiple Linux flavors.

**Comment by avimar** [comment]
uname -a
Linux worker-data 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux

nu_0_21_0_linux

Now seems to work, just with a warning about glibc or something at the start:

```
root@worker-data:~/nu_0_21_0_linux/nushell-0.21.0# ./nu
/root/nu_0_21_0_linux/nushell-0.21.0/nu_plugin_binaryview: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /root/nu_0_21_0_linux/nushell-0.21.0/nu_plugin_binaryview)
Welcome to Nushell 0.21.0 (type 'help' for more info)
```

Is that cause for concern?
