### ISSUE TITLE
commands gets executed even though separated by a semicolon.

### ISSUE THREAD

**Issue by TornaxO7** [nushell/nushell#7653]
### Describe the bug

If I use my given alias below then it gets completely executed although there's a semicolon between the commands.

### How to reproduce

1. In your REPL run the following:
```
alias test = some_sus_command; print "yes"
```
2. Then you will see first, that it gets executed (for whatever reason)
3. Type `test` and you'll see that `yes` is printed out, although `some_sus_command` hasn't been defined yet.

### Expected behavior

That `print "yes"` does *not* get executed.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.73.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 1291b647aee4a566a69fc5786b5437cff3976d1b                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12) (Arch Linux rust 1:1.66.0-1) |
| cargo_version      | cargo 1.66.0                                                     |
| pkg_version        | 0.73.0                                                           |
| build_time         | 2022-12-21 00:14:26 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | database, dataframe, default, trash, which, zip                  |
| installed_plugins  |                                                                  |

**Comment by rgwood** [comment]
Thanks for the issue! I can reproduce this:

```bash
〉let f = (^false; "foo")
〉$f
foo
```

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.73.1                                   |
| branch             | main                                     |
| commit_hash        | e56c01d0e22149db08ef28efcaaef27839852970 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.73.1                                   |
| build_time         | 2022-12-31 18:09:02 -08:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by Kangaxx-0** [comment]
Regards to ``` alias test = some_sus_command; print "yes" ``` , I was not able to reproduce it against latest `main` branch, I did not see `yes`

![image](https://user-images.githubusercontent.com/85712372/210297058-cf0db302-5ae6-4541-8b65-c778a9ccb2cd.png)

For @rgwood 's code, I believe `subexpression` does not early returns because we do not check if external fails or not inside iteration ?

```
    for pipeline in block.pipelines.iter() {
        for expr in pipeline.elements.iter() {
            input = eval_element_with_input(engine_state, stack, expr, input, true, false)?.0
        }
    }

```

**Comment by TornaxO7** [comment]
I can close this for the time being since I haven't switched to `nushell` yet.
