### ISSUE TITLE
PPA for nushell for Ubuntu

### ISSUE THREAD

**Issue by Flimm** [nushell/nushell#7658]
### Related problem

I'm trying to install nushell on Ubuntu. The only instructions provided on nushell's home page for Linux instructs users to use Homebrew. However, Homebrew is not installed by default on Ubuntu, and it's not the usual way that software like this is installed on Ubuntu.

### Describe the solution you'd like

I request that packages be provided in a [PPA ](https://help.launchpad.net/Packaging/PPA) for Ubuntu. Ubuntu users are used to installing software from PPAs.

### Describe alternatives you've considered

See also: issue #741. This related issue is a feature request, asking for nushell to be packaged for Debian. Debian packages do make their way eventually into Ubuntu repositories. However, Debian's policies for packaging are quite strict. It may be easier to package nushell in a PPA without following all of Debian's policies. You can even package a binary in a PPA, without the source code, which Debian would not allow in their policies.

### Additional context and details

I completely understand that this takes time and effort, and I understand if the project cannot address this issue at the current time. I thought it would be useful to file an issue for users who may be searching for a PPA for nushell. Even the answer "there doesn't exist a PPA for nushell" is more useful than no answer.

**Comment by fdncred** [comment]
There may be more info here https://www.nushell.sh/book/installation.html.

**Comment by rgwood** [comment]
Thanks for the issue. Most of Nushell’s distro packaging is maintained by community members; we (the core team) are probably not going to do this, but someone else is welcome to.

**Comment by dougg0k** [comment]
Pretty sure it can be automated with github actions, build the deb and publish to launchpad or fury.io every time there is a new release.

**Comment by deadcoder0904** [comment]
would love an ubuntu package using `apt-get install nu` :)

**Comment by ZachariasFrings** [comment]
i too would love that as Ubunutu is a large distro with a big userbase

**Comment by marufmax** [comment]
not just ubuntu, debian also uses apt as package manager. I am interested to using nushell on my raspberry pi which runs on dietpi/debian

**Comment by hustcer** [comment]
I have just published nushell to gemfury, try to install with:
```nu

curl -fsSL https://apt.fury.io/nushell/gpg.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/fury-nushell.gpg
echo "deb https://apt.fury.io/nushell/ /" | sudo tee /etc/apt/sources.list.d/fury.list
sudo apt update
sudo apt install nushell
nu --version

```

**Comment by hongquan** [comment]
> You can even package a binary in a PPA, without the source code, which Debian would not allow in their policies.

Launchpad officially don't allow to upload pre-built binaries, though I saw someone (TimescaleDB) used to bypass with some tricks.

The difficulty with publishing Rust-based softwares on PPA is that, PPA requires to build from source and doesn't allow network access during building, meaning that Cargo is not allowed to download dependencies from crates.io. Cargo has to used `librust-xxx` packages from Ubuntu repo or from other PPAs.
So, before Nushell can be built on PPA, all other dependencies must be packaged for Ubuntu or PPA first.

**Comment by esafak** [comment]
In that case, let's compile a list of those deps.

**Comment by hongquan** [comment]
Found other way is to vendor all dependency sources: https://blog.shadura.me/2020/12/22/vendoring-rust-in-debian-derivative/
