### ISSUE TITLE
`save` creates a file even if it can't handle the input format

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#7659]
### Describe the bug

If `save` fails because it doesn't know what to do with the input format, it still creates a file:

![image](https://user-images.githubusercontent.com/26268125/210283476-d5b41464-efaf-4152-8c89-82c5ffb85cc2.png)

### How to reproduce

1. Run `[{ foo: "bar"}] | save foo.txt`
2. Observe that an empty `foo.txt` file was created even though `save` failed

### Expected behavior

I expect `save` to not leave a file behind when it's unable to write any data to the file. It should either clean up after itself or not create the file at all.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.73.1                                   |
| branch             | main                                     |
| commit_hash        | e56c01d0e22149db08ef28efcaaef27839852970 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.73.1                                   |
| build_time         | 2022-12-31 18:09:02 -08:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by WindSoilder** [comment]
I think this issue is properly handled by #7608

**Comment by rgwood** [comment]
You're right! Thanks @NotLebedev
