### ISSUE TITLE
Config parser doesn't support F13-F24 keys

### ISSUE THREAD

**Issue by aniou** [nushell/nushell#7666]
### Describe the bug

Config parser [doesn't support](https://github.com/nushell/nushell/blob/45fe3be83eb803211f55067ccd545bba701ef761/crates/nu-cli/src/reedline_config.rs#L678) keycodes from F13 to F24:

```rust
                .filter(|num| matches!(num, 1..=12))
                .ok_or(ShellError::UnsupportedConfigValue(
                    "(f1|f2|...|f12)".to_string(),
                    format!("unknown function key: {}", c),
                    keybinding.keycode.span()?,
                ))?;
```

### How to reproduce

Put into `config.nu` something like:

```
    {
      name: external_ls
      modifier: none
      keycode: F13
      mode: [emacs vi_normal vi_insert]
      event: {
        until: [
          { send: executehostcommand cmd: "/bin/ls --color" }
        ]
      }
    }
```

### Expected behavior

It should work :)

Under Xorg configuration may be tested with something like:
```
xmodmap -e "clear lock"
xmodmap -e "keycode 66 = F13"
```

Warning: `F13` key may be captured by WM or keycode for CapsLock may be differ, than `66`, but - in general - it should work.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.73.0                                   |
| branch             |                                          |
| commit_hash        | 1291b647aee4a566a69fc5786b5437cff3976d1b |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.73.0                                   |
| build_time         | 2022-12-20 18:17:43 +00:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
This could be more about what `crossterm` supports. Do you know if crossterm supports those keys? Having said that, I know we're also not on the latest version of crossterm either.

**Comment by aniou** [comment]
At this moment looks like `crossterm` [has support](https://github.com/crossterm-rs/crossterm/commit/0b598075b7779f38a12d42ebdc02bf4cbf20018a) for F1-F20 keys from version 0.25, (only to F20, as that range is defined by VT220 standard) - so, extending config to support F1 to F20 (not F24, like I previously wrote) looks as possible.

BTW: there is rather [comprehensive article](https://aperiodic.net/phil/archives/Geekery/term-function-keys/) about variety of encodings of function keys in different environments, and F20 looks like a reasonable maximum at this moment.

**Comment by fdncred** [comment]
@aniou Thanks for doing the research and the extra link. With this information, I think it's safe to accept a PR to go up to F20. Seems like it should be a pretty simple PR. Are you interested in doing it?

**Comment by rgwood** [comment]
@aniou Do you have a keyboard with 24 function keys? That sounds awesome.

**Comment by aniou** [comment]
> Are you interested in doing it?

I'll try.

**Comment by aniou** [comment]
> @aniou Do you have a keyboard with 24 function keys? That sounds awesome.

Unfortunately - no. This is only a creative fiddling with my capslock key. I found convenient mapping them to something like `F13` and using in applications in that way.
