### ISSUE TITLE
Cannot enter backspace, delete, or other commands

### ISSUE THREAD

**Issue by jhough-veritone** [nushell/nushell#7667]
### Describe the bug

When using backspace a different symbol appears. I get a pentagon symbol. This then happens to other keystrokes. Here is an example.

### How to reproduce

1. Go into nushell
2. Type something on the command line
3. Hit backspace

### Expected behavior

I expect the previous character on the command line to be removed and then be able to continue typing

### Screenshots

![nushell_error](https://user-images.githubusercontent.com/107080533/210418840-bdf5b1e4-cdf8-4b35-bb83-863ad249e54e.PNG)

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.73.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | windows-x86_64                       |
| build_target       | x86_64-pc-windows-msvc               |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12)  |
| rust_channel       | stable-x86_64-pc-windows-msvc        |
| cargo_version      | cargo 1.66.0 (d65d197ad 2022-11-15)  |
| pkg_version        | 0.73.0                               |
| build_time         | 2023-01-03 09:31:04 -08:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

**Comment by fdncred** [comment]
Looks like a terminal issue to me. Some of those characters (maybe all) are ansi escape sequences that are not being interpreted correctly.

**Comment by jhough-veritone** [comment]
Okay. It might be useful to know that I am running it on Cygwin64. Thanks

**Comment by fdncred** [comment]
I know what Cygwin64 is but I haven't used it in years. I'm not sure if it uses cmd.exe, console.exe or what for a terminal. Whatever it is, it doesn't seem to work well with ansi escape sequences. But it could also be some weird nushell+cygwin funkiness too.

**Comment by rgwood** [comment]
We're probably not going to be able to put much effort into supporting Cygwin's terminal emulator, sorry. Gonna close this for now but let us know if you have any trouble running Nushell under Windows Terminal/Wezterm/etc.
