### ISSUE TITLE
Ctrl-Z doesn't bring the process into background; cmd & doesn't run cmd in the background

### ISSUE THREAD

**Issue by yurivict** [nushell/nushell#7671]
### Describe the bug

See subject.

```
/tmp〉sleep 10sec                                                                                                                                                                  01/03/2023 03:51:45 PM
^Z^Z


^C
/tmp〉                                                                                                                                                                             01/03/2023 03:51:54 PM
```

```
/tmp〉ls &                                                                                                                                                                         01/03/2023 03:51:15 PM
Error: nu::shell::directory_not_found (link)

  × Directory not found
   ╭─[entry #6:1:1]
 1 │ ls &
   ·    ┬
   ·    ╰── directory not found
   ╰────

/tmp〉                                                                                                                                                                             01/03/2023 03:51:18 PM
```

Version: 0.73.0
FreeBSD 13.1

### How to reproduce

see above

### Expected behavior

n/a

### Configuration

n/a

### Additional context

n/a

**Comment by rgwood** [comment]
Hi, we don't support background jobs / job control yet. It's something we'd like to support eventually. This is covered by several existing issues:

- https://github.com/nushell/nushell/issues/1329
- https://github.com/nushell/nushell/issues/4104
- https://github.com/nushell/nushell/issues/4320

**Comment by yurivict** [comment]
The background job feature is a very common expectation from shell.

**Comment by rgwood** [comment]
Yes, many people have requested background jobs.

It's a lot of work to get right (especially cross-platform), but we want background jobs eventually. PRs and design help would be welcome.
