### ISSUE TITLE
Tilde expansion for external commands is surprising and cannot be opted out of

### ISSUE THREAD

**Issue by panicbit** [nushell/nushell#7673]
### Describe the bug

The encoding of a string can change when passed to an external command:

![grafik](https://user-images.githubusercontent.com/628445/210462555-c36972ca-90b5-4236-9460-f3ac63e66f21.png)

### How to reproduce

1. `^echo "~" | into binary`

### Expected behavior

I expect nushell to not change the encoding of strings when I'm not looking.

### Screenshots

![grafik](https://user-images.githubusercontent.com/628445/210462755-a5663010-0f00-4015-b7f2-19fe369fddb6.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.73.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)             |
| pkg_version        | 0.73.0                                          |
| build_time         | 2023-01-02 18:02:43 +01:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by panicbit** [comment]
Oh, I think I understand now. This is just tilde expansion right? Another footgun to take care of 👍🤪🔫

**Comment by panicbit** [comment]
Or is it? It doesn't actually look like a tilde expansion 😞.

**Comment by rgwood** [comment]
I don't think the first example has anything to do with tilde expansion or encoding. It looks like the call to `^echo` is (probably incorrectly) escaping the string quotes with backslashes, so it echoes `\"~\"` instead of just `~`.

As for your second example, we can't help without knowing what `semver-explain` is.

**Comment by panicbit** [comment]
https://crates.io/crates/semver-explain

The command works fine in other shells

**Comment by panicbit** [comment]
The worst part about this is probably that there's no way to escape this behaviour. I also still hold the opinion that stuff like this should be part of string creation time and not usage time.

**Comment by rgwood** [comment]
Confirmed using strace that we are expanding the tilde when running `semver-explain "~0.5.3"`:
```
[pid 442837] execve("/home/reilly/.cargo/bin/semver-explain", ["semver-explain", "/home/0.5.3"], 0x5598e5835790 /* 44 vars */ <unfinished ...>
```
That is bad and we shouldn't be doing it.

**Comment by panicbit** [comment]
This issue is probably related: https://github.com/nushell/nushell/issues/5456

**Comment by rgwood** [comment]
Also confirmed with procmon on Windows just for fun:
![image](https://user-images.githubusercontent.com/26268125/210467863-454012ec-0eaa-4aba-a0a2-8aca20cc47dd.png)

**Comment by WindSoilder** [comment]
I can reproduce it on MacOS

**Comment by WindSoilder** [comment]
Search for history, found that maybe it's conflict with the engine-q issue: https://github.com/nushell/engine-q/issues/844

**Comment by WindSoilder** [comment]
Just investigate how `bash` and `fish` handles tlide:
python script:
```python
import sys
print(sys.argv[1])
```

fish:
```
>  python test.py ~/abcdefg
/Users/ttt/abcdefg
```

bash:
```
> python test.py ~/abcdefg
/Users/ttt/abcdefg
```

So I think tilde expansion works as expected

**Comment by panicbit** [comment]
Bash, however, doesn't do tilde expansion within quotes. In Nushell I currently can not opt out of tilde expansion.

**Comment by WindSoilder** [comment]
Oh, sorry, I get your point finally :-)

**Comment by gnaaman-dn** [comment]
> It's interesting that it's not even getting the tilde expansion right; it's missing my username in both cases.

Very OT, (sorry) but it's actually the right expansions, as `~NAME != ~/NAME`.
`~NAME == Home of user NAME`
