### ISSUE TITLE
`Unexpected end of code.` error happened on latest main in some case

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#7684]
### Describe the bug

`Unexpected end of code.` error happened on latest main in some case

### How to reproduce

Supposing you have installed `just`( Run `brew install just` on macOS) locally:

1. Create a new dir named `foo`
2. Create a `Justfile` in `foo` with the following content:
```justfile
set shell := ['nu', '-m', 'light', '-c']

NU_DIR := parent_directory(`(which nu).path.0`)

_query_plugin := if os_family() == 'windows' { 'nu_plugin_query.exe' } else { 'nu_plugin_query' }
_gstat_plugin := if os_family() == 'windows' { 'nu_plugin_gstat.exe' } else { 'nu_plugin_gstat' }

# List available commands by default
default: _setup
  @just  --list --list-prefix "··· "

_setup:
  @register {{ join(NU_DIR, _query_plugin) }}; \
    register {{ join(NU_DIR, _gstat_plugin) }}; \
    version; \
    char nl
```
3. Run `just` in `foo` dir and you will get:
```console
Error: nu::parser::unexpected_eof (link)

  × Unexpected end of code.
   ╭─[source:1:1]
 1 │ register /Users/hustcer/.cargo/bin/nu_plugin_query; register /Users/hustcer/.cargo/bin/nu_plugin_gstat; version; char nl
   ╰────

error: Recipe `_setup` failed on line 17 with exit code 1
```

### Expected behavior

It should run without any error and output something like:

```
 version              0.73.1
 branch               main
 commit_hash          7bd07cb3514672e4f43ddec0d266d22c8be8d719
 build_os             macos-x86_64
 build_target         x86_64-apple-darwin
 rust_version         rustc 1.66.0 (69f9c33d7 2022-12-12)
 rust_channel         stable-x86_64-apple-darwin
 cargo_version        cargo 1.66.0 (d65d197ad 2022-11-15)
 pkg_version          0.73.1
 build_time           2023-01-04 09:56:39 +08:00
 build_rust_channel   release
 features             database, dataframe, default, trash, which, zip
 installed_plugins    gstat, inc, query, query json, query web, query xml

Available recipes:
··· default # List available commands by default
```

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.73.1                                              |
| branch             | main                                                |
| commit_hash        | 7bd07cb3514672e4f43ddec0d266d22c8be8d719            |
| build_os           | macos-x86_64                                        |
| build_target       | x86_64-apple-darwin                                 |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12)                 |
| rust_channel       | stable-x86_64-apple-darwin                          |
| cargo_version      | cargo 1.66.0 (d65d197ad 2022-11-15)                 |
| pkg_version        | 0.73.1                                              |
| build_time         | 2023-01-04 09:56:39 +08:00                          |
| build_rust_channel | release                                             |
| features           | database, dataframe, default, trash, which, zip     |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

### Additional context

Related PR: https://github.com/nushell/nushell/pull/7650, If I revert this PR it works fine

**Comment by fdncred** [comment]
This is really weird. I tried a bunch of things to narrow down what was happening and nothing has jumped out. I wonder what's going on.

**Comment by webbedspace** [comment]
No idea. Actually, I can't even get nu_plugin_gstat to compile on my system because I can't successfully install git2, so I don't know if I could even attempt to replicate this…🦔

**Comment by fdncred** [comment]
@webbedspace I don't think it's related to nu_plugin_gstat or git2. I've taken them out of the justfile and it still gives this error. I'm just not sure if the problem lies within `just` or within `nushell`.

**Comment by fdncred** [comment]
I put an `eprintln!()` on every `unexpectedeof` error and I don't see where it's coming from. I'm guessing there must be another way to throw an unexpectedeof error.

**Comment by hustcer** [comment]
This is simple enough to reproduce this issue:
```justfile
set shell := ['nu', '-c']

NU_DIR := parent_directory(`(which nu).path.0`)

_query_plugin := if os_family() == 'windows' { 'nu_plugin_query.exe' } else { 'nu_plugin_query' }

# List available commands by default
default:
  @register {{ join(NU_DIR, _query_plugin) }}; version; char nl
  @just --list
```
And if I change `@register {{ join(NU_DIR, _query_plugin) }}; version; char nl` to `@register ~/.cargo/bin/nu_plugin_query; version; char nl;` everything works fine

**Comment by fdncred** [comment]
@hustcer I just noticed that I get the same problem when running from powershell.
```
> just
Error: nu::parser::unexpected_eof (link)

  × Unexpected end of code.
   ╭─[source:1:1]
 1 │ register C:\Users\dschroeder\.cargo\bin\nu_plugin_query.exe; version; char nl
   ╰────

error: Recipe `default` failed on line 9 with exit code 1
```
So, I guess that means something is happening on the `nu -c` command. I wonder, can we construct the `nu -c` command that fails without `just`?

**Comment by hustcer** [comment]
I can't construct a `nu -c` command that fails without `just` currently, I will try some other way later. but how to explain that If we revert #7650 then everything works?

**Comment by hustcer** [comment]
> Your testing almost sounds like 'register {{ join(NU_DIR, _query_plugin) }} is being passed into nushell without expansion. I wonder if we can runjust` is some debug mode to see what it's doing?

Remove `@` before the commands, or running `just -v` with the following `Justfile`:
```justfile
set shell := ['nu', '-c']

NU_DIR := parent_directory(`(which nu).path.0`)

_query_plugin := if os_family() == 'windows' { 'nu_plugin_query.exe' } else { 'nu_plugin_query' }

default:
  register {{ join(NU_DIR, _query_plugin) }}
```
The commands that been execute will be displayed:
```console
===> Running recipe `default`...
register /Users/hustcer/.cargo/bin/nu_plugin_query
Error: nu::parser::unexpected_eof (link)

  × Unexpected end of code.
   ╭─[source:1:1]
 1 │ register /Users/hustcer/.cargo/bin/nu_plugin_query
   ╰────

error: Recipe `default` failed on line 8 with exit code 1
```
From the output we can see the command expansion works well.

It's really weird. Let's leave it open and see if there is any other feedback.

**Comment by fdncred** [comment]
@hustcer did you see that @rgwood reported that ansi escapes are being passed through to external commands? That could be part of the problem here.

**Comment by hustcer** [comment]
> @hustcer did you see that @rgwood reported that ansi escapes are being passed through to external commands? That could be part of the problem here.

Yeah, I just saw it, thanks

**Comment by hustcer** [comment]
Closed by https://github.com/nushell/nushell/pull/7710
