### ISSUE TITLE
SubExpression with external command failure does not stop command running

### ISSUE THREAD

**Issue by Kangaxx-0** [nushell/nushell#7690]
### Describe the bug

Say we have a SubExpression `(^false;"hello,world!")`, the first part of external command returns 1 which is a failure, but nu still prints `hello, world!`

The issue is in `eval_subexpression` function, it passes `redirect_stdout = true`,  a few actions happens next:

<img width="845" alt="image" src="https://user-images.githubusercontent.com/85712372/210912059-eac17bd4-0d5f-443d-ab13-ff37ad072ab9.png">

- When nu returns `ExternalStream`, the stdout is a `RawStream` instead of `None`

<img width="539" alt="image" src="https://user-images.githubusercontent.com/85712372/210912531-7fb95c8b-8931-45b2-8f82-41e220e3baf2.png">

- Nu tries to catch external stream exit status, but returns failure = false because above `rawstream` output
<img width="657" alt="image" src="https://user-images.githubusercontent.com/85712372/210912708-f878ae35-aa30-4094-87c6-5d56f750105d.png">

Also, inside the `eval_subexpression` function, it does not deal with early return if external command fails. 

I did try to tweak how redirect_stdout works, my change fixes this one but introduces another bug  -> stdout will not be able to redirect anymore, nu choose `Stdio:piped()` and `Stdio::inherit` based on `edirect_stdout`

This seems not a recent regression, I saw the same behavior on 0.68 commit tag

### How to reproduce

Run `(^false;"hello,world!")`

### Expected behavior

Do not print `hello,world!`

### Configuration

Clipboard does not work, so pasting a screenshot

<img width="535" alt="image" src="https://user-images.githubusercontent.com/85712372/210914527-7b562e7d-ec00-4be2-ab32-5d22f451a42a.png">

**Comment by Kangaxx-0** [comment]
Wants some insight to get this addressed in a clean fashion

**Comment by Kangaxx-0** [comment]
> Is this a duplicate of #7653?

I know you mentioned part of this in that issue, however, I could not reproduce the original #7653 . I left some investigations in this one, but feel free to close or associate it.

**Comment by WindSoilder** [comment]
It seems that we can't figure out the difference between the them:
1. (^false; "hello world")
2. (^false | "hello world")
3. ^false | "hello world" 

Because they all return the same `PipelineData::ExternalStream` with `redirect_stdout: true`.

But when we run external command in SubExpression, `redirect_stdout` must be true, so we can catch output and assign result to variable.

This is what I get from insight, but sorry that I'm not sure how to fix them properly.

**Comment by WindSoilder** [comment]
Suddenly I know how to solve the problem....We can check the input value after eval the element..
