### ISSUE TITLE
Confusing error message for cp

### ISSUE THREAD

**Issue by zoechi** [nushell/nushell#7693]
### Describe the bug

```
❯ cp ~/.ssh/config ~/source/ansible-shared/roles/ssh_config/files/config
Error: nu::shell::file_not_found (link)

  × File not found
   ╭─[entry #65:1:1]
 1 │ cp ~/.ssh/config ~/source/ansible-shared/roles/ssh_config/files/config
   · ─┬
   ·  ╰── copy file "/home/user/.ssh/config" failed: No such file or directory (os error 2)
   ╰────
```
It's the target path that was invalid, but the error message makes it look like the issue was with the source path

### How to reproduce

cp source target with target being a non-existent path

### Expected behavior

The error message should indicate that the target path is invalid

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.72.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.67.0-nightly (b28d30e1e 2022-12-06)     |
| rust_channel       | nightly-x86_64-unknown-linux-gnu                |
| cargo_version      | cargo 1.67.0-nightly (f6e737b1e 2022-12-02)     |
| pkg_version        | 0.72.0                                          |
| build_time         | 2022-12-10 17:23:17 +01:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by webbedspace** [comment]
Aren't all the `cp` and `mv` filesystem error messages generated by the underlying OS? On Windows, they produce "The system cannot find the file specified" which is a line from cmd.exe.

**Comment by zoechi** [comment]
@webbedspace Thanks. I missed it was for an external command (new to nu)
I don't see anymore how this could be improved.

**Comment by webbedspace** [comment]
No, that's wrong, `cp` isn't an external command. It just receives error messages from the underlying OS. So, Nushell could wrap the messages to make them better, except that'd require finicky coding specific to each platform.
