### ISSUE TITLE
`++` doesn't work with `glob` output

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7694]
### Describe the bug

See example. 

### How to reproduce

```
〉(glob *.txt) ++ (glob *.mp3)
Error: nu::parser::unsupported_operation (link)

  × Types mismatched for operation.
   ╭─[entry #2:1:1]
 1 │ (glob *.txt) ++ (glob *.mp3)
   · ──────┬───── ─┬ ──────┬─────
   ·       │       │       ╰── any
   ·       │       ╰── doesn't support these values.
   ·       ╰── any
   ╰────
  help: Change any or any to be the right types and try again.
```

### Expected behavior

`glob` only outputs lists, so this should work, but it doesn't.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.73.0                                   |
| branch             | main                                     |
| commit_hash        | 1291b647aee4a566a69fc5786b5437cff3976d1b |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.73.0                                   |
| build_time         | 2022-12-21 16:52:27 +10:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
@webbedspace I wonder if this is because of @rgwood's recent change since these are stream-able? I'm not sure if that makes any difference.

```
glob *.txt | describe
list<string> (stream)
```

**Comment by weirdan** [comment]
This works now:

```console
$ (glob *.toml) ++ (glob *.lock)
╭───┬───────────────────────────────────────────────╮
│ 0 │ /home/weirdan/src/nushell/Cargo.toml          │
│ 1 │ /home/weirdan/src/nushell/Cross.toml          │
│ 2 │ /home/weirdan/src/nushell/rust-toolchain.toml │
│ 3 │ /home/weirdan/src/nushell/typos.toml          │
│ 4 │ /home/weirdan/src/nushell/Cargo.lock          │
╰───┴───────────────────────────────────────────────╯
```
