### ISSUE TITLE
Bad error message in `path exists`?

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7696]
### Describe the bug

![image](https://user-images.githubusercontent.com/83939/211068952-f35c4f0b-3ec8-4d73-84d3-3c1c45ab185d.png)
Something seems wrong with this line in exists.rs. Doesn't `.try_exists()` return a Rust Error in the Err() arm instead of a ShellError?

### How to reproduce

I tried testing it out, and got this:
```
〉'C:\System Volume Information' | path exists
Error: nu::shell::io_error (link)

  × I/O error
  help: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }
```

### Expected behavior

At least, the above example should produce a proper ShellError with arrows and so forth.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.73.0                                   |
| branch             | main                                     |
| commit_hash        | 1291b647aee4a566a69fc5786b5437cff3976d1b |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.73.0                                   |
| build_time         | 2022-12-21 16:52:27 +10:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I think `try_exist()` returns a `Result<bool>` or `Err(_)`, seen here https://doc.rust-lang.org/stable/std/path/struct.Path.html#method.try_exists
