### ISSUE TITLE
`url join` command that takes the output of `url parse` and produces a full URL string

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7725]
I notice that `path parse` and `path join` are two symmetrical commands - they perform the reverse of each other, and produce the other's input. However, `url parse` doesn't have an equivalent `url join` command. There is `to url` (which is being renamed #7702) but not one for a full URL.

This `url join` command would take a `record<scheme: string, username: string, password: string, host: string, port: string, path: string, query: string, fragment: string, params: record>` record and produce a URL from it.

**Comment by VincenzoCarlino** [comment]
@webbedspace can you provide an example of input/output? Tnx.
Also I would like to take this issue, could you assign me this issue? Tnx.

**Comment by webbedspace** [comment]
I'm not a core developer so I can't assign issues.

Example input:
```
{
  "scheme": "http",
  "username": "",
  "password": "",
  "host": "www.pixiv.net",
  "port": "",
  "path": "/member_illust.php",
  "query": "mode=medium&illust_id=99260204",
  "fragment": "",
  "params":
  {
    "mode": "medium",
    "illust_id": "99260204"
  }
}
```
NOTE: if only `query` or `params` are given, the missing one is computed from it. If both are present, produce an error if they conflict.

Examine the implementation of `url parse` to understand how each of these fields relates to the output.

Example output:
```
"http://www.pixiv.net/member_illust.php?mode=medium&illust_id=99260204"
```
