### ISSUE TITLE
ArchLinux: "symbol SSLv3_client_method version OPENSSL_1.0.0 not defined"

### ISSUE THREAD

**Issue by exaos** [nushell/nushell#774]
- OS: ArchLinux, kernel 5.3.1, glibc 2.29
- openssl-1.0 1.0.2.s
- Nu Shell: 0.3.0, binary package

`./nu: relocation error: ./nu: symbol SSLv3_client_method version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference`

**Comment by hong-duc** [comment]
This is because archlinux disabled sslv3, this had reported here #715 you can follow it for more info

**Comment by exaos** [comment]
Thanks. This issue should be closed now.
