### ISSUE TITLE
Can Nushell define non-name function in future (or now already could) ?

### ISSUE THREAD

**Issue by yhm-amber** [nushell/nushell#7744]
### Question

Like `function (s) return s(s) end` in  Lua , or same things in other language .

Will this conform the design for Nushell ?

**Comment by kubouch** [comment]
I'm not sure what you're asking, I'm not familiar with Lua. You mean anonymous, or lambda, functions? You can use closures, for example
```
> 1 | do {|x| $in + $x } 2
3
```

**Comment by yhm-amber** [comment]
> I'm not sure what you're asking, I'm not familiar with Lua. You mean anonymous, or lambda, functions? You can use closures, for example
> 
> ```
> > 1 | do {|x| $in + $x } 2
> 3
> ```

I mean this (pseudocode) : 

~~~ sh
do {|f| f f} (do {|f| f f})
~~~

or this: 

~~~ sh
do {|f| f(1)} (do {|x| x-2})
~~~

namely make a `function` as a `value`.

**Comment by kubouch** [comment]
Yeah, you can do that, you can pass closures around. You just need to use `do` to call them.

**Comment by WindSoilder** [comment]
I think it's answered.  So I'll close the issue for now, feel free to re-open it if you still have questions
