### ISSUE TITLE
Can nu-json be made into a standalone crate?

### ISSUE THREAD

**Issue by lunabunn** [nushell/nushell#7749]
### Question

Can `nu-json` be made into its own (non-internal) crate?

### Additional context and details

It is my understanding that `nu-json` is a nushell-internal fork of `hjson-rust`, which would explain its name and lack of a README.

However, currently, `hjson-rust` is de facto abandoned, and [no one has stepped up take over as a maintainer](https://github.com/hjson/hjson-rust/issues/25) in almost 6 months. It is not in a usable state and still on `serde` pre-1.0, with the [update PR sitting unmerged](https://github.com/hjson/hjson-rust/pull/24) for almost 2 years.

As far as I can tell, that makes `nu-json` the only maintained, fully-featured `hjson` crate currently available. There is `deser-hsjon`, but as its name suggests it only does deserialization. I think it would be immensely valuable for the ecosystem, therefore, if `nu-json` could be promoted into its own crate.

Most ideally, `nu-json` would be moved into its own repo (which doesn't necessary have to be under the `nushell` org) and rebranded. But if there's no one to take on this maintenance burden, even just a README explaining what `nu-json` is would make it much more discoverable.

What are yall's thoughts on this?

**Comment by rgwood** [comment]
Hi, thanks for the well-written issue. Some good news: `nu-json` is already published as its own crate at https://lib.rs/crates/nu-json

We don't have the bandwidth to do much work to support it for uses outside Nushell, but it would be nice if people find it useful anyway.

> even just a README explaining what nu-json is would make it much more discoverable.

I think that's a good idea. We'd welcome PRs to document `nu-json` better.
