### ISSUE TITLE
Cannot change directory on shared drive in Windows

### ISSUE THREAD

**Issue by apraga** [nushell/nushell#7750]
### Describe the bug

I can list the content of some shared drive :

```
〉ls K: | first 3                                                             01/14/2023 09:37:41 
╭───┬─────────────────────┬──────┬──────────┬─────────────╮
│ # │        name         │ type │   size   │  modified   │
├───┼─────────────────────┼──────┼──────────┼─────────────┤
│ 0 │ K:XXXX.txt │ file │ 220.4 MB │ 2 years ago │
│ 1 │ K:XXXX.txt │ file │  62.4 GB │ 2 years ago │
│ 2 │ K:XX.txt       │ file │   2.3 KB │ 2 years ago │

```
But cannot change directory :

```
〉cd K:                                                                      
 01/14/2023 09:37:44 Error: nu::shell::directory_not_found (link)                                                                                                                                                                                × Directory not found                                                    
  ╭─[entry #14:1:1]                                                                                       
1 │ cd K:                                                                    
 ·    ─┬                                                                                                        
 ·     ╰── directory not found                                                                                     
                                                                                  
   help: IO Error: Os { code: 3, kind: NotFound, message: "Le chemin d’accès spécifié est introuvable." }          
```

This works on some shared drives and not others. Maybe a permission issue ? `cd` works in powershell.      

### How to reproduce

1. `cd K:`

### Expected behavior

I expected nu to change directory. 

### Configuration
`
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.73.0                                   |
| branch             |                                          |
| commit_hash        | 1291b647aee4a566a69fc5786b5437cff3976d1b |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.73.0                                   |
| build_time         | 2022-12-20 18:21:29 +00:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |
`

**Comment by rgwood** [comment]
I can't reproduce this.

> This works on some shared drives and not others.

Let us know if you can identify a pattern.

**Comment by apraga** [comment]
Closing it as I can no longer reproduce it. Thanks.
