### ISSUE TITLE
is "'alias' keyword is not allowed in pipeline" a bug or a feature?

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#7753]
### Question

i'm not sure if this is a bug or a feature i'm not a huge fan with :thinking:
so here i am :yum: 

plain `alias` looks like it returns a table
```bash
> alias
╭────┬─────────────┬───────────────────────────────────────────┬─────╮
│  # │    name     │                 expansion                 │ ... │
├────┼─────────────┼───────────────────────────────────────────┼─────┤
│  0 │ menus       │ [                                         │ ... │
│    │             │   # Configuration for default nushell     │     │
│    │             │ menus                                     │     │
│    │             │   # Note the lack of souce parameter      │     │
│    │             │                                           │     │
│    │             │   {                                       │     │
│    │             │     name: completion_menu                 │     │
│    │             │                                           │     │
│    │             │ only_buffer_difference: false             │     │
│    │             │     marker:                               │     │
...
```
but i cannot get a column from it, e.g.
```bash
> alias | get name
Error: nu::parser::unexpected_keyword (link)

  × Statement used in pipeline.
   ╭─[entry #8:1:1]
 1 │ alias | get name
   · ──┬──
   ·   ╰── not allowed in pipeline
   ╰────
  help: 'alias' keyword is not allowed in pipeline. Use 'alias' by itself, outside of a
        pipeline.
```

### Additional context and details

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.74.1                                                           |
| branch             | main                                                             |
| commit_hash        | b004aacd691de4c5c976d430eb3a2387e6aec235                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12) (Arch Linux rust 1:1.66.0-1) |
| cargo_version      | cargo 1.66.0                                                     |
| pkg_version        | 0.74.1                                                           |
| build_time         | 2023-01-14 10:34:36 +01:00                                       |
| build_rust_channel | release                                                          |
| features           | database, default, trash, which, zip                             |
| installed_plugins  | gstat                                                            |

**Comment by kubouch** [comment]
It's due to `alias` being a parser keyword. You can't do `alias spam = foo | bar` for example, it's because of that. It might be possible to allow it but I'm not sure we need to support standalone `alias` when you can call `$nu.scope.aliases`.

**Comment by amtoine** [comment]
yup, thanks for the explaination :relieved: 

i think the command i wanted to use in the first place was `help aliases` :+1:

**Comment by rgwood** [comment]
Agreed that this is a bit of a sharp edge though; it's a bit weird that `alias` returns a table but it can't be used. Maybe it should return an error directing people to `help aliases` or something like that 🤔

**Comment by amtoine** [comment]
> Agreed that this is a bit of a sharp edge though; it's a bit weird that `alias` returns a table but it can't be used. Maybe it should return an error directing people to `help aliases` or something like that thinking
>
i think it should either 
- return an error directing people to `help aliases`
- return a table which can be used in a pipeline

i feel the former is slightly more desirable, to avoid duplicates and have all this handled by `help` and its subcommands, whereas the latter makes it a bit less consistent with `help commands` for instance :thinking:

**Comment by amtoine** [comment]
i can file an issue about that specific point if you'd like :relieved:

**Comment by rgwood** [comment]
Let's just use this issue :)

**Comment by amtoine** [comment]
> I'd vote for redirecting people to `help aliases`
>
agree with that :+1: 

i think it's more coherent with the other `help` subcommands, and that would make `help` even more... helpfull :muscle:

**Comment by mon-jai** [comment]
Please support it.

I would like to alias everything within a Windows folder (from WSL), and currently there is no other way (that I know) to do so.

**Comment by mon-jai** [comment]
Wield enough, the following code runs without errors, but have no effect.

```
ls $"(which "npm.ps1" | get 0.path | parse -r "^(.*)\/[^\/]*$" | get 0.Capture1)/*.ps1" | each {|it| echo $it.name | parse -r "^.*\/([^\/]+).ps1" | get 0.Capture1 } |  each {|command_name| alias $command_name = $"($command_name).ps1" }
```

**Comment by fdncred** [comment]
It looks to me like your parse is failing to return anything.

**Comment by mon-jai** [comment]
> It looks to me like your parse is failing to return anything. At least on Windows where I tried it.

@fdncred I don't think so. `alias` just doesn't work with `each`.

```
~〉["foo", "bar"] | each {|command_name| echo $command_name }
╭───┬─────╮
│ 0 │ foo │
│ 1 │ bar │
╰───┴─────╯
```

```
~〉["foo", "bar"] | each {|command_name| alias $command_name = $"($command_name).ps1" }
~〉$nu.scope.aliases # Outputs nothing
```

---

Neither passing a variable as `<name>` or `<initial_value>` works.

```
~〉["foo", "bar"] | each {|command_name| alias $command_name = "baz" } # Passing command_name as <name>
~〉$nu.scope.aliases # Outputs nothing too
```

```
~〉["foo", "bar"] | each {|command_name| alias baz = $command_name } # Passing command_name as <initial_value>
~〉$nu.scope.aliases # Outputs nothing
```

---

`alias` doesn't work if we do not use any variable too.

```
~〉["foo", "bar"] | each {|it| alias baz = "baz" }
~〉$nu.scope.aliases # Outputs nothing
```

---

Should I open another issue for this?

**Comment by sholderbach** [comment]
This is a separate issue from the problem faced here. (And the reason we have to emit an error message right now.

In nushell's current design, declaring an `alias` is close to writing code / `def`ining a command. And we currently resist with our design to allow programmatic generation of code at runtime. (i.e. no `eval` command to evalutate code dynamically at runtime).

> `alias` just doesn't work with `each`.
> 
> Neither passing a variable as `<name>` or `<initial_value>` works.
> 
> 
> `alias` doesn't work too if we do not use any variable in `each`.
> 


> 
> Should I open another issue for this?

Very likely that some issue is already open for that, so it might be worth looking for that. Else feel free to open an issue and make your voice heard :)

**Comment by zoechi** [comment]
I just run into this with the `activate.nu` file generated by `virtualenv` `20.17.1`
```sh
❯ source .venv/bin/activate.nu
Error: nu::parser::unexpected_keyword (link)

  × Statement used in pipeline.
     ╭─[activate.nu:116:1]
 116 │ export alias pydoc = python -m pydoc
 117 │ export alias deactivate = overlay hide activate
     ·                           ───┬───
     ·                              ╰── not allowed in pipeline
     ╰────
  help: 'overlay' keyword is not allowed in pipeline. Use 'overlay' by itself, outside of a pipeline.
  ```

**Comment by kubouch** [comment]
> I just run into this with the `activate.nu` file generated by `virtualenv` `20.17.1`
> ```sh
> ❯ source .venv/bin/activate.nu
> Error: nu::parser::unexpected_keyword (link)
> 
>   × Statement used in pipeline.
>      ╭─[activate.nu:116:1]
>  116 │ export alias pydoc = python -m pydoc
>  117 │ export alias deactivate = overlay hide activate
>      ·                           ───┬───
>      ·                              ╰── not allowed in pipeline
>      ╰────
>   help: 'overlay' keyword is not allowed in pipeline. Use 'overlay' by itself, outside of a pipeline.
>   ```

You're supposed to use the file as overlay (see the file comments). The error is quite misleading though, not sure what's happening.

**Comment by zoechi** [comment]
@kubouch Thanks. That worked.

**Comment by kubouch** [comment]
The table functionality from standalone `alias` was removed. Use either `help aliases` or `$nu.scope.aliases`, I think that's enough.

If we really need standalone `alias`, the implementation shouldn't be in the parser, but in the command's implementation, like other commands.

**Comment by amtoine** [comment]
perfect :ok_hand:
