### ISSUE TITLE
`str lpad` and `str rpad` miscalculate if input string contains ANSI escape sequences (or other non-printing chars)

### ISSUE THREAD

**Issue by bobhy** [nushell/nushell#7757]
### Describe the bug

`str lpad` and `str rpad` naively count all characters in the string when calculating how much padding to do, even if some of the characters are non-printing.  To get the right amount of visible padding, user must increase the `--count` parameter to account for the non-printing characters.  

### How to reproduce

(see repro below)

1. Create a string variable with 6 visible characters and 14 non-printing characters in ANSI escape sequences
2. Try to print it padded out to 25 total characters with, e.g `str lpad -c 25`

### Expected behavior

###Expect###
to see a string 25 print positions wide

###Observe###
string is much shorter than 25 print positions.  In the sample below, the field has only 11 visible characters, vs 25 specified on the parameter.

### Screenshots

```rust
〉let v = $"(ansi red)abc(ansi green)def(ansi reset)"
-------------------------------------- /home/bobhy/src/nushell/nu_scripts/prompt ---------------- 2023-01-15 12:24:49 AM
〉$v
abcdef
-------------------------------------- /home/bobhy/src/nushell/nu_scripts/prompt ---------------- 2023-01-15 12:25:04 AM
〉$v | str length
20
-------------------------------------- /home/bobhy/src/nushell/nu_scripts/prompt ---------------- 2023-01-15 12:25:10 AM
〉$v | str lpad -l 25 -c '*'
*****abcdef
-------------------------------------- /home/bobhy/src/nushell/nu_scripts/prompt ---------------- 2023-01-15 12:25:15 AM
〉
```

### Configuration

〉version | transpose key value | to md --pretty
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.74.1                                   |
| branch             | main                                     |
| commit_hash        | 3dd21c635a66b4585914432e36d03fc8bba59019 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.74.1                                   |
| build_time         | 2023-01-13 11:20:06 -05:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

### Additional context

I haven't tried with UTF-8 multi-byte chars to see whether `str lpad` is counting bytes or chars.  But it would be nice for it to handle ANSI escape sequences (possibly by adding an option to check for them).

**Comment by fdncred** [comment]
I wonder if these commands need the same treatment as #7752 ?

**Comment by bobhy** [comment]
I was thinking about how to engineer a resolution to this issue, the above
is an interesting approach.
But having a `str` command producing `grapheme` based results is
fundamentally confusing.  Perhaps there ought to be a new `gme` command
that is inherently grapheme focused and has these new behaviors (and the
one I'd propose for lpad/rpad)?

**Comment by fdncred** [comment]
I think I'm in your camp @bobhy and agree with what you're saying. I wonder what others think.

**Comment by fdncred** [comment]
I think we can close this now since fill and #8134
