### ISSUE TITLE
`table -e` should show all columns

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#7763]
### Describe the bug

I noticed when using `help -f` that sometimes `table -e` is producing unhelpful results:

![image](https://user-images.githubusercontent.com/26268125/212561768-ccc318dc-d240-4ac7-b092-6d59554ca8c1.png)

1. There's a lot of wasted horizontal space
2. We're not showing all columns (even though there aren't that many columns)

cc: @zhiburt 

### How to reproduce

Run `help -f arg | table -e` in a terminal around 130 columns wide.

### Expected behavior

I expect Nu to show all columns in the result.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.74.1                                   |
| branch             | main                                     |
| commit_hash        | 5419e8ae9d1ca3b4e22fc4016012eb80ef8f01ff |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.74.1                                   |
| build_time         | 2023-01-11 23:19:39 -08:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
This specific issue has been fixed a couple times. I wonder why it's popping up again.

**Comment by rgwood** [comment]
Total guess which I have not verified: maybe related to the highlighting escape codes in `help -f` output

**Comment by fdncred** [comment]
@rgwood is it only `table -e` or if you do `help -f arg | table` is it also messed up?

**Comment by rgwood** [comment]
It's OK without `-e`:
![image](https://user-images.githubusercontent.com/26268125/212564303-a7211c45-a743-47c4-8764-3ad26bf9c72e.png)
