### ISSUE TITLE
Strange behavior for `open` after been assigned to a variable

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#7774]
### Describe the bug

Strange behavior for `open` after been assigned to a variable, line separators seemed to be removed. I'm not sure it's a bug or a feature.

### How to reproduce

1. Create a file named `resolution.txt` with the following content:
```
width:  1920px
height: 1080px

```
2. Run `open resolution.txt | find width` you will get:
```
╭───┬────────────────╮
│ 0 │ width:  1920px │
╰───┴────────────────╯
```
3. However, if you run `let res = open resolution.txt; $res | find width` you will get:
```
width:  1920px
height: 1080px

```
Looks like the line separators have been removed, as `let res = open resolution.txt; $res | lines | find width` will work as expected

### Expected behavior

`open resolution.txt | find width` and `let res = open resolution.txt; $res | find width` should have the same result

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.74.1                                              |
| branch             | main                                                |
| commit_hash        | 0353eb4a120f6708a6e00c1b2060d978849963db            |
| build_os           | macos-x86_64                                        |
| build_target       | x86_64-apple-darwin                                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)                 |
| rust_channel       | stable-x86_64-apple-darwin                          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)                 |
| pkg_version        | 0.74.1                                              |
| build_time         | 2023-01-16 09:52:28 +08:00                          |
| build_rust_channel | release                                             |
| features           | database, dataframe, default, trash, which, zip     |
| installed_plugins  | gstat, inc, query, query json, query web, query xml |

**Comment by fdncred** [comment]
agreed. that is weird behavior.

**Comment by merelymyself** [comment]
I think there’s a chance that the problem might be with `find` here. In the first example it’s input is a RawStream, but in the second it’s a Value.
