### ISSUE TITLE
Feature to break long command into multi-lines for nu script

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#7780]
### Related problem

Need some feature to break a very long command in nu script(**Not** In **REPL** Mode) into muti-lines for a better readability

```console
call-me --this=$this --command=$command --has=$has --really=$really --very=$very --long=$long --flags=$flags --and=$and --need=$need --some=$some --way=$way --to=$to --improve=$improve --the=$the --readability=$readability
```

### Describe the solution you'd like

I don't care about what the line continuation character is if this feature could be fulfilled

### Describe alternatives you've considered

Maybe like this?
```console
let call = (
  call-me --this=$this --command=$command --has=$has --really=$really 
          --very=$very --long=$long --flags=$flags --and=$and --need=$need 
          --some=$some --way=$way --to=$to --improve=$improve --the=$the 
          --readability=$readability
)
```

### Additional context and details

Relative issue: https://github.com/nushell/nushell/issues/4044

**Comment by NotTheDr01ds** [comment]
Running into this today.  What's even worse is that calling a custom command that accepts a record or list argument starts to look even *more* unwieldy, as breaking the record across multiple lines looks plain weird when you have to continue the other arguments after the closing `}`.  E.g.:

```Nushell
call-me --arg1 foo --params {
        bar: "fly",
        baz: "arghh"
    } --uglify --another-record {
        foo: 5,
        bar: 1day
    }
```

Wondering if there's any way the comma could be optionally used as a line continuation character between arguments in a custom-command.  E.g.:

```Nushell
call-me --arg1 foo, 
    --params {
        bar: "fly",
        baz: "arghh"
    },
    --better-maybe,
    --another-record {
        foo: 5,
        bar: 1day
    }
```

Is there any potential "gotcha" in the parser, I wonder, that could trip that up?

**Comment by bobhy** [comment]
Not sure we need a new feature here, you can already do this with parens ...
Not just on the RHS of a  `let`, as you showed above, but also on a direct invocation (no `let`):
```
 (call-me 
::: --arg1 foo 
::: --params {
:::         bar: "fly",
:::         baz: "arghh"
:::     }
:::  --uglify
:::  --another-record {
:::         foo: 5,
:::         bar: 1day
:::     }
::: )
```
The parse already allows whitespace (including newline) between arguments of internal or external commands, when it sees the open paren, it just keeps reading tokens till it sees the closing parens.

**Comment by jntrnr** [comment]
Agreed, I'd stick with parens to go multiline.

**Comment by hustcer** [comment]
> Agreed, I'd stick with parens to go multiline.

At the time I created this issue this feature was not supported, and it works now, so I will close this issue.
