### ISSUE TITLE
Maybe deprecate `str starts-with`, `str ends-with` and `str contains` in favour of `$in starts-with`, `$in ends-with` etc.

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7793]
### Describe the solution you'd like

`str` is currently littered with a lot of subcommands that compete for attention and maintenance, and I've pinpointed these three as not lending much in the way of functionality compared to the others. If they were proposed today, I'd strongly doubt they would be accepted.

You can rewrite `some-command | str starts-with "A"` as `some-command | $in starts-with "A"` to get identical functionality, you can rewrite `some-list | str starts-with "A"` as `some-list | each { $in starts-with "A" }` (a rare use-case).

The table case (writing `some-table | str starts-with "A" name` to change the table's `name` column to `str starts-with "A"` results) is so exceedingly rare that I strongly doubt anyone ever really needed it (compared to the other `str` subcommands like `trim`) but it can be written as `some-table | update name { $in.name starts-with "A" }`.

**Comment by webbedspace** [comment]
Any remarks on this one? Should I do a quick PR of it and see what happens? (I'd just add them to the rest of the `str` deprecated subcommands.)

**Comment by sholderbach** [comment]
I personally am not a fan of replacing the commands with subexpressions.
Especially if instead of broadcasting we have to resort to "Just use `each {}`" as this has some performance on top of readability downsides.

**Comment by webbedspace** [comment]
People keep talking about `each` readability downsides, in both here and `update`… I don't really get it. `each` always performs a list->list op, whereas with `str starts-with` it's not immediately obvious which type signature is in play. If length is really such an issue, maybe `each` should be made even shorter? What if the `$it` var could be used anywhere, and its presence in a pipeline stage automatically converted it into a list->list op? `| $it contains "foo"` would be the same as `| each { $in contains "foo" }`. (This isn't a serious suggestion, just a stray thought.)

The other thing I want to touch on is inconsistency with other operators. Why do `starts-with` and `ends-with` get these special command versions, but not `not-in`, `in`, or any of the inequality operators? If anything, I'd say the inequality operators are much more likely to be used on lists than string comparison operators.

**Comment by webbedspace** [comment]
Closing because this isn't that big of an issue to warrant further deliberating over.
