### ISSUE TITLE
`to-json` escapes quotation marks in JSON output

### ISSUE THREAD

**Issue by jordelver** [nushell/nushell#780]
I'm not sure if this is desired behaviour or not :)

When I pipe to `to-json` I get the output I expect.

```
/Users/jord> sys | get disks | to-json
[{"device":"/dev/disk1s1","type":"apfs","mount":"/","total":1000345825280,"used":667545300992,"free":327743021056},{"device":"/dev/disk1s4","type":"apfs","mount":"/private/var/vm","total":1000345825280,"used":4294995968,"free":327743021056},{"device":"com.apple.TimeMachine.2019-10-02-143753@/dev/disk1s1","type":"apfs","mount":"/Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/lol/2019-10-02-143753/OSX","total":1000345825280,"used":664176734208,"free":327743021056},{"device":"/dev/disk3s2","type":"hfs","mount":"/Volumes/Clone","total":2000021315584,"used":563390582784,"free":1436630732800},{"device":"/dev/disk2s2","type":"hfs","mount":"/Volumes/Backup","total":2000021315584,"used":1976685240320,"free":23336075264}]
```

But when I then save that to disk, the JSON output is changed to escape quotation marks.

```
/Users/jord> sys | get disks | to-json | save disks.json
/Users/jord> cat disks.json
"{\"device\":\"/dev/disk1s1\",\"type\":\"apfs\",\"mount\":\"/\",\"total\":1000345825280,\"used\":667545300992,\"free\":327743021056},{\"device\":\"/dev/disk1s4\",\"type\":\"apfs\",\"mount\":\"/private/var/vm\",\"total\":1000345825280,\"used\":4294995968,\"free\":327743021056},{\"device\":\"com.apple.TimeMachine.2019-10-02-143753@/dev/disk1s1\",\"type\":\"apfs\",\"mount\":\"/Volumes/com.apple.TimeMachine.localsnapshots/Backups.backupdb/lol/2019-10-02-143753/OSX\",\"total\":1000345825280,\"used\":664176734208,\"free\":327743021056},{\"device\":\"/dev/disk3s2\",\"type\":\"hfs\",\"mount\":\"/Volumes/Clone\",\"total\":2000021315584,\"used\":563390582784,\"free\":1436630732800},{\"device\":\"/dev/disk2s2\",\"type\":\"hfs\",\"mount\":\"/Volumes/Backup\",\"total\":2000021315584,\"used\":1976685240320,\"free\":23336075264}]"
```

I assume this is happening because when you save the output the whole thing is wrapped in quotation marks as it's a string and wouldn't be valid without escaping.

This is valid JSON, I just expected to see exactly the same output as `to-json`.

What do you think?

Thanks for Nu Shell, I think this is a great idea! 👏

**Comment by jonathandturner** [comment]
Ahh, we need a better way of warning what is happening in this situation.  You're actually converting to JSON twice in that pipeline.  The first time is with `t-json` and the second is with `save disks.json`.  `save` and `open` do the conversion for you automatically based on the filename.

In the future, we may want to detect this and warn that it's not necessary.

If you want to keep your pipeline the same you can use `save disks.json --raw` instead of `save disks.json`

**Comment by jordelver** [comment]
Ah, that makes sense. `save` is smarter than I realized :) 

Thank you 👍 Great work!
