### ISSUE TITLE
Incorrect `to csv` conversions

### ISSUE THREAD

**Issue by NotLebedev** [nushell/nushell#7800]
### Describe the bug

The `to csv` command accepts any  data as input, which produces many strange results:
1. Converting primitives to and from csv produces empty result without `--noheaders` flag:
    ![image](https://user-images.githubusercontent.com/17511668/213672298-7888f0ff-927f-4e5e-a442-83915b433d02.png)
2. Converting tables with non-primitive contents does not result in error and leaves some sort of string description in place:
    ![image](https://user-images.githubusercontent.com/17511668/213673066-b71f7de8-909b-4f42-8636-38cce6bb73c2.png)
3. Converting lists that are "not quite tables" results in useless result  with loss of data and no error:
    ![image](https://user-images.githubusercontent.com/17511668/213676169-717a3097-94ac-43c3-a8ff-efe23c241471.png)

### How to reproduce

Try out examples from above in current release or development version of nu

### Expected behavior

Expected behavior is up for debate. I suggest that `to csv` should error if data is not a table filled (maybe with gaps like in second example) with primitives. This would be in line with signature of `from csv` which can only produce tables.

### Configuration

Tested on latest commit in `main` branch and current release

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.74.1                                   |
| branch             | main                                     |
| commit_hash        | ea9ca8b4ed5d0e45be533c541bd5013c69ecf8c1 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.74.1                                   |
| build_time         | 2023-01-20 13:42:37 +03:00               |
| build_rust_channel | debug                                    |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by NotLebedev** [comment]
This issue also affects the `to tsv` command, which uses common [delimited.rs](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/formats/to/delimited.rs) to_delimited_data function.

**Comment by sholderbach** [comment]
Yeah sounds like a place were should typecheck that we get a table as input i.e. `Value::List` or `PipelineData::ListStream` of `Record`s. That should be relatively straight forward.

A bit more contentious is how we should represent complex types like inner records.

Don't know if we have some implicit behavior people depend on.

**Comment by NotLebedev** [comment]
I see one undocumented feature that may be worth keeping. A simple record would be transformed to table with only one row. Only problem is conversion back returns a table:
![image](https://user-images.githubusercontent.com/17511668/213689256-2a044abd-76e1-441c-bf4c-e8017dbdb927.png)
I researched code a bit and think that I could fix this. I would need to  alter what types are matched in `from_value_to_delimited_string` and `to_string_tagged_value`
