### ISSUE TITLE
using index as column name causes weird result

### ISSUE THREAD

**Issue by schmitzli** [nushell/nushell#7816]
### Describe the bug

when i try to rename a column to index or using wrap index the result is broken

### How to reproduce

`[1 2 3] | wrap num | rename index`

or 

`[1 2 3] | wrap index`

### Expected behavior

just the same behavior as if i would use idx or some other name

### Screenshots

![image](https://user-images.githubusercontent.com/22212302/213877097-133c30a7-1d2b-417a-b79a-8f45d9ed8bc8.png)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.74.0                                   |
| branch             |                                          |
| commit_hash        | 9a56665c6beee31e365ce17898056f1ff2db4094 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.74.0                                   |
| build_time         | 2023-01-10 20:35:16 +00:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

### Additional context

the workaround is just to use a different name

**Comment by fdncred** [comment]
This is by design. It allows you to have the `#` column anything you want. I mean, it's not designed to be weird. :) It's designed to allow you to change the index column like this.

```nu
> [index number]; [bob 1] [jane 2] [charlie 3]]
╭─────────┬────────╮
│       # │ number │
├─────────┼────────┤
│     bob │      1 │
│    jane │      2 │
│ charlie │      3 │
╰─────────┴────────╯
```

**Comment by webbedspace** [comment]
Personally I've always disliked this feature, mainly because I don't consider the index number column to be such an eyesore that `table` needs this special case to finagle it. At the very least, I'd like it if that column had `#` changed to `index` so that it's obvious it isn't a bug (hence this report).

**Comment by fdncred** [comment]
There is also a way to configure the table index in the config file.
```
table: {
  index_mode: always #  "always" show indexes, "never" show indexes, "auto" = show indexes when a table has "index" column
...
}
```

**Comment by schmitzli** [comment]
thank you for the explanation, i'll  just use a different name
