### ISSUE TITLE
Subcommands completions do not work

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#7821]
### Describe the bug

Completing subcommand completions does not work

### How to reproduce

1. `help<tab>` lists subcommands (correct)
2. `help <tab>` lists file names (wrong)
3. `help mo<tab>` does not list anything (wrong)

### Expected behavior

All three cases should show `help` subcommands completions.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.74.1                                          |
| branch             | main                                            |
| commit_hash        | be32aeee70a6d004abbab3e2db229d6246f0f0fd        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)             |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)             |
| pkg_version        | 0.74.1                                          |
| build_time         | 2023-01-18 08:32:51 +02:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | gstat, hist, plot, xyplot                       |

### Additional context

I'm pretty sure this is a regression from 0.74 or 0.73, I remember subcommand completions working correctly not so long ago.

**Comment by Xoffio** [comment]
Hi @kubouch are you sure this was broken after #7779? i am currently running `0.73.0` and i am also having those issues... have you tried older versions ?

**Comment by kubouch** [comment]
Yes, that PR breaks it. I found it with `git bisect` and verified now. The commit before the PR has working subcommand completions. It also works on 0.73.0. Note that `help modules`was introduced in 0.74 so you need to try a different subcommand in 0.73.

**Comment by maxim-uvarov** [comment]
I actively use subcommands suggestions produced by `overlay use`. 
I upgrade nushell via brew, and I upgrade brew almost every day.
While I was using 0.74.(0?) I'm sure that subcommds worked well for me. In 0.75.0 they stoped

**Comment by fdncred** [comment]
should this issue be closed since the PR that broke it was rolled back?
