### ISSUE TITLE
the `--help` of the `query` command does not feature a lot of examples

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#7827]
### Related problem

i was having a look at the following script from @fdncred 
```bash
let titles = (http get http://books.toscrape.com/ | query web -q 'h3 > a')
let prices = (http get http://books.toscrape.com/ | query web -q '.price_color')
$titles | zip $prices | each {|r| {title: ($r.0) price: ($r.1)}}
```
to solve [this webscraping problem](https://www.scrapingdog.com/blog/web-scraping-with-rust/) in `nushell` rather than `rust` :ok_hand:

> **Note**  
> see the [original comment](https://discord.com/channels/601130461678272522/601130461678272524/1066461225623502988)

`http get` is clear to me, just a renaming of the old `fetch`.
but i discovered the `query` command and don't really get what it's doing, e.g. how the `-q` option of `query web` works

## the `--help`s right now
```bash
> query --help
Show all the query commands

Usage:
  > query 

Subcommands:
  query db - Query a database using SQL.
  query json - execute json query on json file (open --raw <file> | query json 'query string')
  query web - execute selector query on html/web
  query xml - execute xpath query on xml

Flags:
  -h, --help - Display the help message for this command
```
and
```bash
> query web --help
execute selector query on html/web

Usage:
  > query web {flags} 

Flags:
  -h, --help - Display the help message for this command
  -q, --query <String> - selector query
  -m, --as-html - return the query output as html
  -a, --attribute <String> - downselect based on the given attribute
  -t, --as-table <Table> - find table based on column header list
  -i, --inspect - run in inspect mode to provide more information for determining column headers
```

### Describe the solution you'd like

i think a little more help could be helpfull, especially examples for the `query` subcommands :relieved:

**Comment by fdncred** [comment]
Correct, it's annoying that plugins don't support `Examples` like regular commands. We need to add that because I have to look up how to do things too.

**Comment by amtoine** [comment]
oooooh

`query` is a plugin!?

i think you're right, i remember registering `nu_plugin_query` during my exploration the other day
> **Note**  
> and i've got the culprit, `register ~/.local/share/cargo/bin/nu_plugin_query`, inside my history
> ```bash
> > open $nu.history-path | lines | find register | find query
> ╭───┬───────────────────────────────────────────────────────────────────────────────────────────╮
> │ 0 │ register /home/amtoine/.local/share/ghq/github.com/nushell/nushell/crates/nu_plugin_query │
> │ 1 │ register ~/.local/share/cargo/bin/nu_plugin_query                                         │
> ╰───┴───────────────────────────────────────────────────────────────────────────────────────────╯

so it's not only a missing documentation but something deeper with the plugins system? :open_mouth:

**Comment by fdncred** [comment]
ya, there's other incomplete things as well, although they're not coming to mind right now.

**Comment by amtoine** [comment]
> ya, there's other incomplete things as well, although they're not coming to mind right now.
>
i see this has been marked with _good first issue_, if there's anything i can do to help, please tell me :relieved:

**Comment by fdncred** [comment]
Maybe figure out how to add `Examples`? I'm not sure how hard or easy that is. Maybe @sholderbach has some other ideas?

**Comment by fdncred** [comment]
@amtoine Should this be closed or are you suggesting that some commands still do not have adequate examples? I'm always up for other commands but we may need to "None" the results as to not augment the examples default context too much. Maybe once we get a better ruling of what we can/should be testing we can proceed?

**Comment by amtoine** [comment]
no idea when this has been added, but yeah there are examples for `query web` now it appears, right?

if i'm not crazy, we can close this and wait for more decisions about what should be tested :relieved:
