### ISSUE TITLE
Missing completion for `git branch -D`

### ISSUE THREAD

**Issue by rukai** [nushell/nushell#7832]
### Describe the bug

out of the box nushell has completion for branch names in `git checkout`.
However that some completion does not work for branch names on `git branch -D`/`git branch -d`/`git branch --delete`

### How to reproduce

`git branch -D` then hit tab

### Expected behavior

nushell to offer completions with available branches

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.74.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 9a56665c6beee31e365ce17898056f1ff2db4094                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12) (Arch Linux rust 1:1.66.0-1) |
| cargo_version      | cargo 1.66.0                                                     |
| pkg_version        | 0.74.0                                                           |
| build_time         | 2023-01-10 22:53:04 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | database, dataframe, default, trash, which, zip                  |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment]
There are more completions in our nu_scripts repo. The included ones are just to give people an idea of what nushell completions look like. They aren't meant to be complete or exhaustive.

**Comment by rukai** [comment]
Thats unfortunate and confusing that git completions just work out of the box but only partially.
Maybe your little paragraph there should be checked into config.nu just before the git completions?

FWIW I pasted https://github.com/nushell/nu_scripts/blob/main/git/git.nu into my config.nu and it doesnt give me  completion for `git branch -D`, so I think my best option is to just stick with bash for git usage atm.
Maybe I'll make a PR for `git branch -D` completion once I've learnt some nuscript.

**Comment by fdncred** [comment]
ya, when we wrote these git completions we were hoping that people would finish them.

**Comment by rukai** [comment]
To be clear: do you mean the git completions in config.nu or in nu_scripts?

**Comment by fdncred** [comment]
> To be clear: do you mean the git completions in config.nu or in nu_scripts?

I'd make changes to the git completions in nu_scripts.

**Comment by sholderbach** [comment]
Currently we don't ship any `extern` completions with the default config anymore, so we can't overpromise and underdeliver in this area. For completion definitions we refer to the `nu_scripts` `extern` definitions or standalone external completers like `carapace`
