### ISSUE TITLE
Enable `complete` command to collect errors along with output and exit code.

### ISSUE THREAD

**Issue by chaoticenginerd** [nushell/nushell#7841]
### Describe the solution you'd like

Since the command already collects the output and exit code, I think it would be better to add in standard error stream as nu does not  do any redirection of stderr by default.

Enabling the `complete` command to collect errors along with output and exit code would also allow for easier use when the user wants to just know the exit code of a program and ignore any outputs or errors. This would allow working around issues of redirection (#7828 ) since only the exit code can be obtained by getting the `exit_code` attribute.

**Comment by fdncred** [comment]
`complete` will capture stderr. You have to use it like this
```
do -i { git branch --show-current | complete }
╭───────────┬──────────────────────────────────────────────────────────────────────╮
│ stdout    │                                                                      │
│ stderr    │ fatal: not a git repository (or any of the parent directories): .git │
│           │                                                                      │
│ exit_code │ 128                                                                  │
╰───────────┴──────────────────────────────────────────────────────────────────────╯
```

**Comment by chaoticenginerd** [comment]
The docs for the `complete` command don't mention it so I had no idea. Maybe still it could be integrated for a simpler direct use?

**Comment by WindSoilder** [comment]
> Maybe still it could be integrated for a simpler direct use?

Sorry, it's incompatible to current design about communication between external command and nushell itself, I think the best way we can do to mention `do`  in doc
