### ISSUE TITLE
Repaint prompt on enter

### ISSUE THREAD

**Issue by JanDeDobbeleer** [nushell/nushell#7843]
### Question

I'm trying to implement [transient prompt](https://ohmyposh.dev/docs/configuration/transient) for oh-my-posh and I'm struggling to do so.

What does it need to do? The process is rather simple, on enter (or before executing a command), I want the prompt to be repainted with a more compact prompt. That way the history is more readable than a full blown custom prompt. This is what I tried so far:

```
export-env {
    let-env PROMPT_COMMAND = {
        # We have to do this because the initial value of `$env.CMD_DURATION_MS` is always `0823`,
        # which is an official setting.
        # See https://github.com/nushell/nushell/discussions/6402#discussioncomment-3466687.
        let cmd_duration = if $env.CMD_DURATION_MS == "0823" { 0 } else { $env.CMD_DURATION_MS }
        let width = ((term size).columns | into string)

        if $env.POSH_TRANSIENT {
            let-env POSH_TRANSIENT = false
            ^oh-my-posh print transient $"--config=($env.POSH_THEME)" --shell=nu $"--shell-version=($env.NU_VERSION)" $"--execution-time=($cmd_duration)" $"--error=($env.LAST_EXIT_CODE)" $"--terminal-width=($width)"
        } else {
            ^oh-my-posh print primary $"--config=($env.POSH_THEME)" --shell=nu $"--shell-version=($env.NU_VERSION)" $"--execution-time=($cmd_duration)" $"--error=($env.LAST_EXIT_CODE)" $"--terminal-width=($width)"
        }
    }
}

def-env posh-transient [] {
    let-env POSH_TRANSIENT = true
}
```

And then set up a custom keybinding as such:

```
keybindings: [
    {
        name: posh_transient
        modifier: None
        keycode: enter
        mode: [emacs, vi_normal, vi_insert]
        event:[
            {
                send: executehostcommand,
                cmd: "posh-transient"
            }
            { send: Repaint }
            { send: SubmitOrNewline }
        ]
    }
]
```

`executehostcommand` works, that one sets the variable correctly, and I see the repaint happening, but not the submit. There's also an issue re-assigning `POSH_TRANSIENT` in the `PROMPT_COMMAND` (probably only local there).  It also effectively renders the prompt useless probably because it never really submits (it does go to a new prompt on enter though, but never executes the command).

Am I missing something obvious? Or maybe there's another way using hooks, although I couldn't find how to invoke a repaint other than the event in a keybinding.

**Comment by fdncred** [comment]
I've been playing a little bit but ran out of time. You might be able to figure something out with hooks. I didn't try your example above but since it looked logical to me, I figured you did everything right and it just doesn't work that way.

I did was playing with this when I ran out of time. I changed my hooks in config.nu.
```
  hooks: {
    pre_prompt: [{
      let-env POSH_TRANSIENT = true
    }]
    pre_execution: [{
        let-env PROMPT_COMMAND = {
        let cmd_duration = if $env.CMD_DURATION_MS == "0823" { 0 } else { $env.CMD_DURATION_MS }
        let width = ((term size).columns | into string)

        if $env.POSH_TRANSIENT {
            let-env POSH_TRANSIENT = false
            ^oh-my-posh print transient $"--config=($env.POSH_THEME)" --shell=nu $"--shell-version=($env.NU_VERSION)" $"--execution-time=($cmd_duration)" $"--error=($env.LAST_EXIT_CODE)" $"--terminal-width=($width)"
        } else {
            ^oh-my-posh print primary $"--config=($env.POSH_THEME)" --shell=nu $"--shell-version=($env.NU_VERSION)" $"--execution-time=($cmd_duration)" $"--error=($env.LAST_EXIT_CODE)" $"--terminal-width=($width)"
        }
      }
    }
    ]
    env_change: {
      PWD: [{|before, after|
        $nothing
      }]
    }
  }
```
I did this in env.nu
```
let-env POSH_THEME = $"(brew --prefix oh-my-posh)/themes/jandedobbeleer.omp.json"
let-env NU_VERSION = "0.74.1"
```
I put this in some script file that i'm already sourcing.
```
def-env posh-transient [] {
    let-env POSH_TRANSIENT = true
}
```
It nearly works but I'm not sure what's going on really. It's like it's replacing the prompt all the time and i never see the themed jandedobbeleer.omp.json prompt.

**Comment by JanDeDobbeleer** [comment]
Also found something interesting, for some reason when adding `{ send: SubmitOrNewline }` as the first event, `reedline` works. As soon as I move it down to first repaint the prompt, it doesn't work anymore.

**Comment by fdncred** [comment]
> @fdncred I don't think hooks will work as both are executed before the prompt is rendered ...

I could be wrong but I don't think that's the case. If you change your hooks to this, you can see when they execute.
```
    hooks: {
      pre_prompt: [{
        print -n "pre_p " (date now | date format "%Y-%m-%d %H:%M:%S.%f") (char nl)
      }]
      pre_execution: [{
        print -n "pre_e " (date now | date format "%Y-%m-%d %H:%M:%S.%f") (char nl)
      }]
      env_change: {
        PWD: [{|before, after|
          $nothing
        }]
      }
    }
```
I get the pre_prompt hook right before the prompt is rendered and the pre_execution right after you type a command and hit enter.

> Also found something interesting, for some reason when adding { send: SubmitOrNewline } as the first event, reedline works.

This sounds like a bug to me, perhaps in reedline.

**Comment by JanDeDobbeleer** [comment]
@fdncred yes, but as long as you can't set `let-env POSH_TRANSIENT = false` from within `let-env PROMPT_COMMAND` that solution isn't going work just like mine.

**Comment by fdncred** [comment]
mutation can be used inside blocks but not closures. I believe PROMPT_COMMAND is a closure.
```
> mut a = 5
> if $a == 5 { $a += 1 } else { $a -= 1 }
> $a
6
> if $a == 5 { $a += 1 } else { $a -= 1 }
> $a
5
```

I've been trying something else but not having much luck. Returning both prompts as a record and choosing which one to use at prompt time.
```
def get_prompt_command [] {
    let cmd_duration = (if 'CMD_DURATION_MS' in (env).name { if $env.CMD_DURATION_MS == "0823" { 0 } else { $env.CMD_DURATION_MS } } else { 0 })
    let width = ((term size).columns | into string)

    {
        transient: (^oh-my-posh print transient $"--config=($env.POSH_THEME)" --shell=nu $"--shell-version=($env.NU_VERSION)" $"--execution-time=($cmd_duration)" $"--error=($env.LAST_EXIT_CODE)" $"--terminal-width=($width)")
        primary: (^oh-my-posh print primary $"--config=($env.POSH_THEME)" --shell=nu $"--shell-version=($env.NU_VERSION)" $"--execution-time=($cmd_duration)" $"--error=($env.LAST_EXIT_CODE)" $"--terminal-width=($width)")
    }
}

let-env PROMPT_COMMAND = {if $env.POSH_TRANSIENT { (get_prompt_command).transient } else { (get_prompt_command).primary }}
```
But i can't get the transient prompt to look transient.
![image](https://user-images.githubusercontent.com/343840/214075074-0c37a070-3059-4974-8ad8-bb2a1b9f679d.png)

**Comment by sholderbach** [comment]
Maybe we need to special case something on the reedline side. I think we try to repaint the prompt once upon submission but maybe something is going wrong there.

**Comment by sholderbach** [comment]
To land the cursor after submession on the right sport, we run: 
https://github.com/nushell/reedline/blob/3d83306b2dadd17d065d9d25ea62a36c3a0a76b2/src/engine.rs#L576-L589

https://github.com/nushell/reedline/blob/3d83306b2dadd17d065d9d25ea62a36c3a0a76b2/src/painting/painter.rs#L466-L479

This possibly breaks if the size changes.

Also we don't have an explicit redraw if I read that correctly.

**Comment by JanDeDobbeleer** [comment]
@sholderbach correct, an explicit redraw could also solve the challenge as I could use that with the hooks in a clean way.

**Comment by lewis-yeung** [comment]
I think this may be safely closed? Since the transient prompt (`$env.TRANSIENT_PROMPT_COMMAND`) has been fully supported in Nushell for almost one year now.

**Comment by sholderbach** [comment]
Thanks for bringing this up!

**Comment by valyntyler** [comment]
> I think this may be safely closed? Since the transient prompt (`$env.TRANSIENT_PROMPT_COMMAND`) has been fully supported ([#10391](https://github.com/nushell/nushell/pull/10391)) in Nushell for almost one year now.

So I may be wildly misunderstanding but from what I can tell simply setting `$env.TRANSIENT_PROMPT_COMMAND` doesn't actually make nushell ask for a repaint so arguments like `starship module time` will always display the time at the last `exec nu` and not the time when the prompt is drawn.

**Comment by ysthakur** [comment]
@valyntyler Yeah, I'm afraid the fact that the transient prompt is created with the prompt (rather than after the command finishes executing) is expected behavior that would be very difficult to change (if we even want to change it). This is how it works in other shells too. `@NotTheDr01ds` has an explanation here: https://github.com/nushell/nushell/issues/15235#issuecomment-2696070079.
