### ISSUE TITLE
While starting nu the config.nu doesn't seem to be able to source any relative files.

### ISSUE THREAD

**Issue by TheCodeLamp** [nushell/nushell#7849]
### Describe the bug

I like keeping my config files a bit organized so I tried making a separate completions.nu file where I could source all my external completions. However there is a problem when starting nu fresh; the `config.nu` file cant seem to see it's neighboring files.

![Screenshot from 2023-01-24 10-38-41](https://user-images.githubusercontent.com/12064217/214258467-e0db704a-230d-45ea-8db9-3bed8fcccea4.png)

However when I source the full path name it seems to work fine with no errors.

![Screenshot from 2023-01-24 10-43-05](https://user-images.githubusercontent.com/12064217/214259171-9fb533d2-ba09-4a63-bb33-e5ba8456df88.png)

This seems to only be a problem in the `config.nu` file as the completions.nu can seem to load the other completions files and even source a test file I created to get confirmation of nested sourcing.

```nu
# completions.nu
# Script for gathering all completion files.

export use cargo-completions.nu *
export use git-completions.nu *

source confirm-test-load.nu # Added as a test to see if nested sourcing works.

"Completions Loaded" # Added as a test to see confirmation.
```

### How to reproduce

1. create `config.nu` and `completions.nu` in `~/.config/nushell/`
2. add `source completions.nu` or `use completions.nu` to `config.nu`

### Expected behavior

I expect nu to load the relative files without having to use the full file path.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.74.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.66.0 (d65d197ad 2022-11-15)             |
| pkg_version        | 0.74.0                                          |
| build_time         | 2023-01-23 13:06:35 +01:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

### Additional context

I am using Fedora and I've tried this in semode permissive.

I've tried installing the bin to `/usr/local/bin/` but the problem persists.

Some relevant issues:
#6150
#7247

**Comment by zoechi** [comment]
I updated my `env.nu` to accomplish that
```
let-env NU_LIB_DIRS = [
    ($nu.config-path | path dirname | path join 'lib'),
    ($nu.config-path | path dirname | path join 'lib/commands'),
    ($nu.config-path | path dirname | path join 'lib/completions'),
    ($nu.config-path | path dirname | path join 'lib/themes'),
]
```

**Comment by sholderbach** [comment]
Yeah making it easier to have a modularized config is one of our near term goals. What variables get set when in the background is still a bit of too much special sauce between `env.nu` and `config.nu`.

**Comment by webbedspace** [comment]
Honestly this always annoyed me. That `NU_LIB_DIRS` trick never occurred to me, so thanks.

**Comment by texastoland** [comment]
Root issue identifed in https://github.com/nushell/nushell/issues/11465#issuecomment-1883847806.

**Comment by kubouch** [comment]
For implementation hints, see https://github.com/nushell/nushell/issues/11465

**Comment by melMass** [comment]
I think this can be closed

**Comment by texastoland** [comment]
As a duplicate? Still happening in my current `env.nu` unless fixed in `main` 🤞🏼

**Comment by melMass** [comment]
> As a duplicate? Still happening in my current `env.nu` unless fixed in `main` 🤞🏼

My bad it's about `source` I did not test that

**Comment by texastoland** [comment]
Here's my exact `env.nu`:

```nushell
# workaround: nushell/nushell#7849
use $'($nu.default-config-dir)/scripts/dirs.nu' *
use ($~.nu |/ scripts vars.nu)
use ($~.nu |/ scripts init.nu)
```

Planning to attempt after I fix my VS Code 😅

**Comment by lpnh** [comment]
This could be related to #11918

**Comment by texastoland** [comment]
No. File imports are source relative. There's a function in Rust that isn't being called. Just need to get in and work through it.
