### ISSUE TITLE
add `^cp`'s `-u` flag to builtin `cp`

### ISSUE THREAD

**Issue by kurokirasama** [nushell/nushell#7853]
### Related problem

It would be great if we could have this option from `^cp` and `^mv` (from GNU coreutils cp help):
```
-u, --update                 copy only when the SOURCE file is newer
                                 than the destination file or when the
                                 destination file is missing
```
in builtin `cp` and `mv`

### Describe the solution you'd like

add this flag to update files when copying or moving

**Comment by VincenzoCarlino** [comment]
I'd like to work on this, can someone assigne me the issue?

**Comment by WindSoilder** [comment]
@VincenzoCarlino Sure, just assigned to you :-D  Feel free to ask if you have any problems
