### ISSUE TITLE
iregular table layout crashes the shell

### ISSUE THREAD

**Issue by rnxpyke** [nushell/nushell#786]
The Shell crashes with some irregular data layout.

Opening these test.json files with `open test.json` works as intended:
`[{"name":"first"}]`
`[{"name":"first"}, {"name": "second"}]` 
`[{1:1, 2:2}]`
`[{"name": "first"}, "string"]`

Whereas these crash:
`[{1:1, 2:2}, "string"]`
`[{1:1, 2:2}, 3]`
`[3, {1:1, 2:2}]`
`["string", {"name": "first", "other": "second"}]`

Using one of the failing examples with `open test.json | to-json` doesn't crash and produces the expected output: the original file without unneeded whitespace. Piping one of the failing examples into the table command explicitly like this `open test.json | table` crashes again.

Here is the error message of the last failing example:
`thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2'`

I suspect that nu determines that the table should have to columns in the failing examples.
It then tries to get the second entry of the Primitive Value, which doesn't exist.

**Comment by andrasio** [comment]
@rnxpyke This is fixed. Please reopen if you see issues. Closing for now. Thanks!
