### ISSUE TITLE
if is wrongly capture from `mut` variable which assigned to `$in`

### ISSUE THREAD

**Issue by WindSoilder** [nushell/nushell#7862]
### Describe the bug

As title, please see the reproduce steps below

### How to reproduce

1. given the following code in nushell:
```
def not_working [] {
    mut input = $in
    if $input == 3 {
        print 3
    }
}
```

It gives the following error.
```
∙     if $input == 3 {
Error: nu::parser::expected_keyword (link)
  × Capture of mutable variable.
   ╭─[entry #6:3:1]
 3 │
 4 │     if $input == 3 {
   ·        ───┬──
   ·           ╰── capture of mutable variable
   ╰────
```

Actually I'm not sure why.  Because the following works:
```
def works [arg] {
    mut input = $arg

    if $input == 3 {
        print 3
    }
}
```

### Expected behavior

I expect nu didn't show me error..

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.74.1                                   |
| branch             | main                                     |
| commit_hash        | 625fe8866c5af2d4c5dc56d92d3c75c47f9feef2 |
| build_os           | macos-x86_64                             |
| build_target       | x86_64-apple-darwin                      |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.74.1                                   |
| build_time         | 2023-01-21 16:12:23 +08:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  | from-binary                              |

**Comment by jntrnr** [comment]
Something must be wrong in the expansion when we see `$in`. If I do the expansion by hand that I *think* should be using, it'd look something like:

```
def not-working-for [] {
   mut foo = (collect {|x| $x})
   for i in 1..3 {
     $foo += 1
   }
   $foo
}
10 | not-working-for
```

Which gives
```
13
```

Which looks right. My guess is that we need to expand `$in` into a subexpression that does the call to `collect` possibly?
