### ISSUE TITLE
`where ()` fatal error

### ISSUE THREAD

**Issue by pizzafox** [nushell/nushell#788]
Running the following command will cause `nu` to totally crash (tested on the nightly version):
```nu
where ()
```

This error was printed to the console by the program I used to run `nu`:
```rust
thread 'main' panicked at 'not yet implemented', /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/nu-0.3.0/src/parser/hir/baseline_parse_tokens.rs:288:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by andrasio** [comment]
@pizzafox This is fixed. Please reopen if you still have issues. Thanks!
