### ISSUE TITLE
Automatic column name inconsistency: `parse -r` columns are 1-indexed capitalised when most other commands are 0-indexed uncapitalised

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7886]
### Describe the bug

See below.

### How to reproduce

```
〉'A|B|C' | parse -r '(\w)\|(\w)\|(\w)'
╭───┬──────────┬──────────┬──────────╮
│ # │ Capture1 │ Capture2 │ Capture3 │
├───┼──────────┼──────────┼──────────┤
│ 0 │ A        │ B        │ C        │
╰───┴──────────┴──────────┴──────────╯
〉[A B C] | rotate
╭───┬─────────┬─────────┬─────────╮
│ # │ column0 │ column1 │ column2 │
├───┼─────────┼─────────┼─────────┤
│ 0 │ C       │ B       │ A       │
╰───┴─────────┴─────────┴─────────╯
```

### Expected behavior

I expect automatic column names to follow a consistent numbering format.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.74.0                                   |
| branch             | main                                     |
| commit_hash        | 9a56665c6beee31e365ce17898056f1ff2db4094 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.74.0                                   |
| build_time         | 2023-01-10 16:21:03 -06:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
Thanks. You're right. We should be consistent.
