### ISSUE TITLE
select gives syntax error in nu script

### ISSUE THREAD

**Issue by kiil** [nushell/nushell#7890]
### Describe the bug

This work from the command line:

`fetch https://xxxxxx.xxxxxxx/jsonapi/node/indlaeg?sort=-created | from json | get data | get attributes | select created drupal_internal__nid status field_google_analytics_counter | save folkets-content.csv`

But when I put the line in a folkets-content.nu file and execute it, I get this:

```
./folkets-content.nu: line 1: syntax error near unexpected token `drupal_internal__nid'
./folkets-content.nu: line 1: `fetch https://www.folkets.dk/jsonapi/node/indlaeg?sort=-created | from json | get data | get attributes | select created drupal_internal__nid status field_google_analytics_counter | save folkets-content.csv '
```

### How to reproduce

1. `select` a column from a .nu script

### Expected behavior

I would expect nu scripts to work with select as it does from the command line

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.74.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-x86_64                                                      |
| build_target       | x86_64-apple-darwin                                               |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12) (built from a source tarball) |
| cargo_version      | cargo 1.66.0 (d65d197ad 2022-11-15)                               |
| pkg_version        | 0.74.0                                                            |
| build_time         | 2023-01-10 20:12:41 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | database, default, trash, which, zip                              |
| installed_plugins  |                                                                   |

**Comment by kiil** [comment]
Sorry, I did not put   `#!/usr/bin/env nu`in the file. With that, it works.

**Comment by fdncred** [comment]
Is everything working now? If so, we should probably close this.

**Comment by kiil** [comment]
Yes, it works. I assumed that my system would know to use nushell when the file ending was .nu - taht was not the case.
