### ISSUE TITLE
Consider changing `enumerate` to creating `[index, item]` lists ("tuples") instead of `{index, item}` records

### ISSUE THREAD

**Issue by webbedspace** [nushell/nushell#7900]
### Describe the solution you'd like

My arguments for this:

* Future compatibility with pattern-matching/destructuring syntax that could be added to closures: `enumerate | each {|[ind elem]| $'($ind): ($elem)' }` would be shorter and more flexible than `enumerate | each {|{index:ind item:elem}| $'($ind): ($elem)' }`
* Rust `enumerate()` outputs tuples holding values in the order index->item (language precedent). I believe other enumeration-based iterators in other languages behave likewise.
* Something like `enumerate | each {|e| $'($e.index): ($e.item)' }` is rather verbose, especially for REPL one-liners. The need to append `.item` to every use of the item is especially annoying when the closure needs to use it a lot. Making it `enumerate | each {|e| $'($e.0): ($e.1)' }` would reduce this verbosity significantly.
* When `index_mode: always` is set, `enumerate` output displays misleadingly:
```
〉1..4 | enumerate
╭───┬──────╮
│ # │ item │
├───┼──────┤
│ 0 │    1 │
│ 1 │    2 │
│ 2 │    3 │
│ 3 │    4 │
╰───┴──────╯
```
Because the `index` of enumerate's output is the same as what the actual row index would be, this is displayed as if the table has only 1 row.

Yes, I understand this is a break from how `--numbered` worked, but I do think it's for the better.

**Comment by jntrnr** [comment]
I don't think this would be an improvement. Part of the benefit with using records is that you know which is the index and which is the value.

Take this example:

```
> [4, 5, 6] | enumerate
```

You'll get pairs of two integers, and if you're doing that interactively it won't be clear which is the index and which is the item. If we have a chance to make it clear on inspection, we should.

That said, there are some errors with how tables are currently printed, and we should show the `index` column if table index is set to always, but that's a separate issue.

**Comment by webbedspace** [comment]
Decided to close this because it doesn't seem to have support (+ the requested alternative could be created with a `def`)
