### ISSUE TITLE
`list<string> ++ list<string>` thinks both values are `any`

### ISSUE THREAD

**Issue by YuriGeinishO** [nushell/nushell#7913]
### Describe the bug

`$a | describe` and `$b | describe` say both are `list<string>`, but `$a ++ $b`  says both are `any`:
```
$changes_in_file2 ++ $new_from_file1 | str join "\n"
────────┬──────── ─┬ ───────┬───────
        │          │        ╰── any
        │          ╰── doesn't support these values.
        ╰── any
```

### How to reproduce

Can't get a minimal example, so here's the entire program:

`merge-hocon.nu`:
```
#!/usr/bin/env nu
 
def load_hocon [file: string] {
  let original = open --raw $file
  let kvs = ($original
    | lines
    | str replace '\s*=\s*' ' = '
    | each { |line|
        let kv = ($line | split column ' = ' key value | default '' value | first)
        {
          original: $line,
          key: $kv.key,
          value: $kv.value
        }
      }
  )
  $kvs
}
 
def main [file1: string, file2: string, --keypattern (-k): string] {
  let parsed1 = load_hocon $file1
  let parsed2 = load_hocon $file2
 
  print --stderr ($parsed1 | describe)
  print --stderr ($parsed2 | describe)
 
  let changes_in_file2 = ($parsed2 | each { |kv2|
    if $kv2.value == '' {
      return $kv2.original
    }
 
    if $keypattern != null and $kv2.key !~ $keypattern {
      print --stderr $"- `($kv2.key)` doesn't match --keypattern value, keep it"
      return $kv2.original
    }
 
    if $kv2.key not-in $parsed1.key {
      print --stderr $"- `($kv2.key)` does not exist in file1, delete it to handle renames and legit deletions"
      return null
    }
 
    let kv1 = ($parsed1 | where $it.key == $kv2.key | first)
    if $kv2.value == $kv1.value {
      print --stderr $"- `($kv2.key)` has the same value in file1 and file2, keep it"
      return $kv2.original
    }
 
    print --stderr $"- `($kv2.key)` has different value in file1 and file2, overwrite with file1's value"
    return $kv1.original
  })
 
  let new_from_file1 = ($parsed1 | each { |kv1|
    if $kv1.value == '' {
      return null
    }
 
    if $kv1.key in $parsed2.key {
      return null
    }
 
    print --stderr $"- `($kv1.key)` is new to file2, add it"
    return $kv1.original
  })
 
  print --stderr ($changes_in_file2 | describe) 
  print --stderr ($new_from_file1 | describe) 
 
  $changes_in_file2 ++ $new_from_file1 | str join "\n"
}
```

`file1.conf`:
```
// comment
a = 1
 
b=2
c   =     300
only_in_zone1 = abc
```

`file2.conf`:
```
// comment
a = 1
 
b=2
c   =     3
d = 4
only_in_zone2 = zxc
```

How to run:
```
./merge-hocon.nu file1.conf file2.conf
```

### Expected behavior

Concat two `list<string>` without errors.

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.74.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | linux-x86_64                         |
| build_target       | x86_64-unknown-linux-gnu             |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)  |
| rust_channel       | stable-x86_64-unknown-linux-gnu      |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)  |
| pkg_version        | 0.74.0                               |
| build_time         | 2023-01-25 12:37:46 +01:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

### Additional context

This workaround provided by @WindSoilder works:
```
$a | append $b
```

**Comment by fdncred** [comment]
Very weird that this doesn't work. I was able to hack an additional workaround by changing the last lines to this.
```bash
#   $changes_in_file2 ++ $new_from_file1 | str join "\n"
  mut arr = $changes_in_file2
  $arr ++= $new_from_file1

  $arr
```

**Comment by kamirr** [comment]
Even this will fail:
```
def identity [x] { $x }

def main [] {
  let my_list = identity [0]
  $my_list ++ $my_list
}
```
But if you replace `identity [0]` with just `[0]` it will work fine, it appears passing the list through *any* function makes the type obscured, even if the return type is clearly stated in the signature (see implementation of `lines`).

The error originates from `math_result_type` in `type_check.rs`, because the `lhs` and `rhs` (instances of `Expression`) have `ty == Type::Any`. I do not know what to do with this.

Hope it helps.

**Comment by fdncred** [comment]
The only conclusion I can come to is that the wrong types are being passed into `math_result_type`. It appears to be called from here https://github.com/nushell/nushell/blob/ad14b763f9d2b5516d82cab70a24771c9c5e4b32/crates/nu-parser/src/parser.rs#L4899

**Comment by jntrnr** [comment]
In the case both are `any`, we should allow the `++` to go through and have the types checked at runtime. Once we do that, we should see both are list and then the list concatenation should work.

**Comment by jntrnr** [comment]
Yeah, if you allow it to pass the typecheck, it works okay:

```
> def identity [x] { $x }
> let my_list = (identity [0])
> $my_list ++ $my_list                                                                              02/01/2023 06:35:33 AM
╭───┬───╮
│ 0 │ 0 │
│ 1 │ 0 │
╰───┴───╯
```

All I changed was to add this line at type_check.rs line 87:
```
                (Type::Any, _) | (_, Type::Any) => (Type::Any, None),
```

**Comment by fdncred** [comment]
I'll submit a PR in a few. Thanks JT!
