### ISSUE TITLE
Record mistaken for Closure?

### ISSUE THREAD

**Issue by bobhy** [nushell/nushell#7921]
### Describe the bug

Parse problem with records.

### How to reproduce

```nushell
〉let r = {bar: (date now) - 3day}
〉$r
<Closure 109>
```

### Expected behavior

`$r` should be a `record`, not a `closure`.

### Configuration

-------------------------------------------- /home/bobhy/src/rust/nushell --------------------------------------------
〉version | transpose key value | to md --pretty
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.74.1                                   |
| branch             | unicode_escape                           |
| commit_hash        | 719d4ff32940d0bcb4ac1694e06070522ea4217c |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| pkg_version        | 0.74.1                                   |
| build_time         | 2023-01-28 10:44:52 -05:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
It would be a record if this syntax was used 
```bash
let r = {bar: ((date now) - 3day)}
$r
╭─────┬────────────╮
│ bar │ 3 days ago │
╰─────┴────────────╯
```

**Comment by bobhy** [comment]
Ok, but what should the parser do with the example without the parens?
Error?  What should the error be? Or accept as a valid record?  It should
not silently do the wrong thing.
