### ISSUE TITLE
Rename files / folders

### ISSUE THREAD

**Issue by gsuuon** [nushell/nushell#7931]
### Related problem

The current implementation of `mv` has caught me out enough times that I've aliased it to warn me about using it. It does very frustrating things on erroring, e.g. folders get copied but none of the files yet sources get deleted anyways. It's caused a lot of frustration for me and each time the only thing I wanted to do was rename a folder.

### Describe the solution you'd like

A nu command that just calls https://doc.rust-lang.org/std/fs/fn.rename.html. I know `rename` is taken so I'm not sure what it could be named. Alternatively, use a different library for `mv` or reimplement it in way that it doesn't delete if the copy failed.

### Describe alternatives you've considered

Currently I redefine `mv` to just remind me not to use it.

### Additional context and details

This may be mostly a Windows issue since it seems like it's due to not handling file operation errors.

**Comment by rgwood** [comment]
Hi, can you provide any examples/reproductions? We’d be happy to improve mv but we need some concrete examples of the problems you’re encountering.

**Comment by rgwood** [comment]
(also, really sorry about the data loss; we would like to get this fixed)

**Comment by gsuuon** [comment]
I saw existing issues so I figured I'd try a feature request instead since I think what I'm asking for is slightly different than the bug fix (which would still be great) - I'd like something that explicitly only tries to rename the folder I specify, rather than recursively going through and copy/deleting things. Either it completely works or it doesn't, but won't ever do some of the files/folders but not all.

This issue usually happens when I have a handle open in one of the files in the folder unknowingly, the `mv` fails when it gets to that file but has already moved some things. I then close the process that might have a handle and then try to get it to finish the move/rename with a `mv previousName/* newName/`. 

If I didn't kill the right thing this step will tend to destroy data, as the source folder ends up empty while the target has directories recursively nested (as in, duplicated as a child inside the folder if the folder already existed rather than copying content into the folder) yet missing content. The content that was able to be copied in the first step will still be there, but the globbed files are missing.

I feel the problem is I can't explicitly _just_ try to rename a directory, which should either work or not - but never do partial work.

**Comment by rgwood** [comment]
> This issue usually happens when I have a handle open in one of the files in the folder unknowingly, the mv fails when it gets to that file but has already moved some things.

Thanks, that should give us enough info to reproduce the issue. I might have time to take a look in a week or so.

It's possible it's a bug in [`fs_extra`](https://github.com/webdesus/fs_extra) which we rely on.

**Comment by gsuuon** [comment]
> `mv` should just do the right thing.

Yeah I definitely agree, though I wasn't sure if a partial move is expected behavior on failure. Looking through `fs_extra` it looks like it's not intended. The data loss on `mv a/* b/` I think already has an existing issue. A flag on `mv` to not fall back to `fs_extra` would be really helpful in alleviating this for the time being - but no surprises with `mv` would be ideal.

**Comment by gsuuon** [comment]
I briefly commented out my alias to give `mv` another try and pretty quickly got bit by it again. It can completely mangle a git repository. Quick repro:

1. create git repository
2. open in second terminal
3. move the repository
4. .git files are partially moved
5. old directory `git log` shows not a git repo
6. new directory `git log` shows no commits

https://user-images.githubusercontent.com/6422188/235062418-2447311f-8e31-48f9-96d4-4f17aa539a7a.mp4

https://user-images.githubusercontent.com/6422188/235062447-3f2f9201-a02a-40d6-bb53-cbde53ef666b.mp4

**Comment by gsuuon** [comment]
Closing the suggestion, opened a new issue for the partial move here #9041
