### ISSUE TITLE
Unexpected interpolation in argument for script

### ISSUE THREAD

**Issue by mksinicus** [nushell/nushell#7936]
### Describe the bug

When a non-interpolated string containing `(` or `()` is passed to a nu script file, nu tries to interpolate it, if none of the parentheses are adjacent to or contain a whitespace or a (already escaped) backslash.

### How to reproduce

1. `"#!/usr/bin/env nu\ndef main [str] {echo $str}" | save test; chmod +x test`
2. `./test '(aaaa)'` yields the external command failed error (assuming there is no real command called `aaaa`)
3. `'(aa aa)'`, `'( aaaa)'`, `' (aaaa)'`, `'\(aaaa)'` vel sim. are just printed
4. However, `"(date\tnow)"` will print like `$"(date now)"`

### Expected behavior

I expect nu to treat these strings in accordance with the expected behavior as documented

### Screenshots

![Screenshot_20230201_215732](https://user-images.githubusercontent.com/60370605/216064849-2aaea326-b5d7-4946-a306-c96b9a0d93a6.png)

![Screenshot_20230201_215756](https://user-images.githubusercontent.com/60370605/216064873-a0d2885d-3092-477d-be27-239130428237.png)

Since `($env.config)` didn't print the config record, it probably is a problem in the nu process that runs the script, not the shell

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.75.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)             |
| pkg_version        | 0.75.0                                          |
| build_time         | 2023-02-01 07:12:44 +08:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by weirdan** [comment]
This no longer happens:

![image](https://github.com/user-attachments/assets/1c5ff40c-2473-4bdc-829c-d3d428f7eed5)
