### ISSUE TITLE
Removing the bottom header of `ls` and missing colors in an alias

### ISSUE THREAD

**Issue by xosxos** [nushell/nushell#7943]
### Question

I find the bottom column names header very bothering as I use `ls` hundreds of times per day and know the column names by heart.  Thus these extra rows end up taking quite a bit of useful screen space on a 1920x1080 monitor. I couldn't however find a way to disable the bottom or the top headers, is there a way to do this?

Also, also when putting the following line of code into an alias the `name` column loses color, but the `modified` and `size` columns do not.

```nu
ls -l -m | select type mode uid group size modified name

alias l = (ls -l -m | select type mode uid group size modified name)
```

Am I missing something?

**Comment by fdncred** [comment]
> Am I missing something?

Yes, I think so.  This config setting controls the table footer.
```
footer_mode: 20 # always, never, number_of_rows, auto
```
