### ISSUE TITLE
Calculate test coverage in the CI

### ISSUE THREAD

**Issue by Hofer-Julian** [nushell/nushell#7944]
### Related problem

As described in https://github.com/nushell/nushell/issues/5720 there is interest to estimate the code coverage of Nushell.
Doing this locally takes quite some time and also doesn't help to estimate the coverage change of PRs.

### Describe the solution you'd like

The free service Codecov, and it's corresponding [Action](https://github.com/codecov/codecov-action) can help with that.
Here is an example of the UI with a project I maintain: https://app.codecov.io/gh/Deltares/xmipy
If wanted, a bot also comments on PRs to report the coverage change: https://github.com/Deltares/xmipy/pull/79
They also provide badges which can be added to the README: https://about.codecov.io/product/feature/badges/

### Additional context and details

A script like this one could be used on Github Actions to create `lcov.info` that Codecov expects: https://about.codecov.io/tool/lcov/

```bash
#!/bin/bash
set -euxo pipefail
source <(cargo llvm-cov show-env --export-prefix) # Set the environment variables needed to get coverage.
cargo llvm-cov clean --workspace # Remove artifacts that may affect the coverage results.
cargo build --workspace
cargo test --workspace
cargo llvm-cov report --lcov --output-path lcov.info 
```

**Comment by fdncred** [comment]
There's definitely interest. We'd love to have your help. I know @sholderbach has been especially keen on adding when he gets time. So, any help you can add would be a great win IMO. I think we'd want the bot to comment in the PR like in one of your examples above.

**Comment by Hofer-Julian** [comment]
> There's definitely interest. We'd love to have your help. I know @sholderbach has been especially keen on adding when he gets time. So, any help you can add would be a great win IMO.

Great, let me know if you need help with adding Codecov to this organization.
I can then add the github action and the badge.

**Comment by fdncred** [comment]
We need help with everything, lol. So, please let us know what you need or what is needed to make all this happen. BUT, before you begin, please, let's get @sholderbach's blessing since he has done much research into this.

**Comment by Hofer-Julian** [comment]
Don't worry.
Before Codecov get's access to the Github Organization, nothing can be done anyway :P
https://docs.codecov.com/docs/github-oauth-application-authorization

**Comment by sholderbach** [comment]
> ```shell
> #!/bin/bash
> set -euxo pipefail
> source <(cargo llvm-cov show-env --export-prefix) # Set the environment variables needed to get coverage.
> cargo llvm-cov clean --workspace # Remove artifacts that may affect the coverage results.
> cargo build --workspace
> cargo test --workspace
> cargo llvm-cov report --lcov --output-path lcov.info 
> ```

Yeah that looks very close to what I had back then to make sure we also track coverage when `nu` gets invoked as a binary from the `nu!` tests. 
I converted it to a nu script with some pain: https://github.com/nushell/nu_scripts/blob/main/make_release/get_coverage.nu

Two questions we need to figure out:
- At which level do we want to merge the coverage results from different runners and different feature sets. (codecov tooling (more likely) or using `cargo-llvm-cov`)
- How we best get this to play with our build caching infrastructure (which currently seems to keep our times around 10mins) (i.e. how intrusive is the clean step.)

**Comment by Hofer-Julian** [comment]
> > ```shell
> > #!/bin/bash
> > set -euxo pipefail
> > source <(cargo llvm-cov show-env --export-prefix) # Set the environment variables needed to get coverage.
> > cargo llvm-cov clean --workspace # Remove artifacts that may affect the coverage results.
> > cargo build --workspace
> > cargo test --workspace
> > cargo llvm-cov report --lcov --output-path lcov.info 
> > ```
> 
> Yeah that looks very close to what I had back then to make sure we also track coverage when `nu` gets invoked as a binary from the `nu!` tests. I converted it to a nu script with some pain: https://github.com/nushell/nu_scripts/blob/main/make_release/get_coverage.nu

Yeah, I basically stole that and converted it to bash. 
The load-env part is broken and I couldn't see an obvious way to fix it. 


> Two questions we need to figure out:
> 
>     * At which level do we want to merge the coverage results from different runners and different feature sets. (codecov tooling (more likely) or using `cargo-llvm-cov`)

Yeah, I wondered about that too. In my mind we would get Linux working first and then iterate from that point. 


>     * How we best get this to play with our build caching infrastructure (which currently seems to keep our times around 10mins) (i.e. how intrusive is the clean step.)

The clean step isn't too bad as far as I can tell. The consequence on my machine is that nu itself will be built again, but not its dependencies.

**Comment by jntrnr** [comment]
@Hofer-Julian - I just enabled it for this repo, though it looks like there might be additional steps? Do we have to do these as well? https://app.codecov.io/gh/nushell/nushell/new

**Comment by Hofer-Julian** [comment]
@jntrnr it's also been some time for me :)
How about I add a PR for the Action tomorrow and we see if it works without further steps?

**Comment by fdncred** [comment]
https://github.com/nushell/nushell/pull/7946
