### ISSUE TITLE
Better light theme on Windows

### ISSUE THREAD

**Issue by apraga** [nushell/nushell#7954]
### Describe the bug

Hi,

I’m using nushell on windows, without Windows terminal, by just running nu.exe. The default light theme is not very readable 
![image](https://user-images.githubusercontent.com/914687/216550079-727947ff-db96-427d-8ba4-5847db5b93f0.png)

So I’ve customized colors and LS_COLORS to match the modus operandi theme. It’s much better but I cannot find how to change the prompt color. Here’s the result with starship as a prompt: 
![image](https://user-images.githubusercontent.com/914687/216550537-3422c0bc-a3e7-4b45-8b48-5dbb05864f33.png)

My questions are:
1. Is it possible to improve the default light theme ? Maybe by adding the modus-operandi theme as an example too ?
2. Can the prompt color be changed ?
Thanks in advance

### How to reproduce

1. Start nu.exe on windows.

### Expected behavior

A more readable light theme.

### Configuration

❯ version | transpose key value | to md --pretty
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.74.0                                   |
| branch             |                                          |
| commit_hash        | 9a56665c6beee31e365ce17898056f1ff2db4094 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.74.0                                   |
| build_time         | 2023-01-10 20:35:16 +00:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by WindSoilder** [comment]
Hi, we have a set of theme lays here: https://github.com/nushell/nu_scripts/tree/main/themes
You can check out one for usage, currently I'm using [gruvbox light theme](https://github.com/nushell/nu_scripts/blob/main/themes/themes/gruvbox-light-medium.nu)

For the second question, I think it's just defined by theme, so just activating a proper light theme will give you a good prompt color

**Comment by apraga** [comment]
Thanks for the link. Maybe it should be added to the [documentation](https://www.nushell.sh/book/coloring_and_theming.html#theming) ?
Using the gruvbox-light-hard does change the font and ls output but not the background (which can be expected).
However, the prompt does not change color. Without starship, it looks like this:

![image](https://user-images.githubusercontent.com/914687/216599901-de3a642b-90ab-42e6-a8c0-441f1afdfa85.png)

**Comment by fdncred** [comment]
There are a few things that you can do to change colors. I believe we cover all of them here https://www.nushell.sh/book/coloring_and_theming.html#coloring-and-theming-in-nu, including changing the prompt. 

To summarize:
1. LS_COLORS changes the colors of the `ls` name column.
2. Our themes show how to color shapes and primitives like ints, dates, text, table lines, etc.
3. Prompt configuration shows how to change the prompt entirely, including the color.
4. You can change the borders as well from the list provided in `table --list`

Yes, you are right that the themes repo should be mentioned in this documentation.

You also have the default_env.nu config file that shows how to color the prompt.
```
def create_left_prompt [] {
    let path_segment = if (is-admin) {
        $"(ansi red_bold)($env.PWD)"
    } else {
        $"(ansi green_bold)($env.PWD)"
    }

    $path_segment
}

def create_right_prompt [] {
    let time_segment = ([
        (date now | date format '%m/%d/%Y %r')
    ] | str join)

    $time_segment
}

# Use nushell functions to define your right and left prompt
let-env PROMPT_COMMAND = { create_left_prompt }
let-env PROMPT_COMMAND_RIGHT = { create_right_prompt }
```

Closing this for now. If you'd like to provide a better light theme combination of all this stuff feel free to submit a PR and we'll consider it.
