### ISSUE TITLE
Nu crashes when using TAB completion with environment shorthand

### ISSUE THREAD

**Issue by mksinicus** [nushell/nushell#7966]
### Describe the bug

Nu crashes when I press TAB with an environment shorthand at the beginning of the line. 

### How to reproduce

1. Put `FOO=bar` and a whitespace
2. Put anything (or nothing) after that, then press TAB
3. If Nu is a process inside another shell, it crashes and says 
   ```
   thread 'main' panicked at 'Can't create a Span whose end < start, start=18446744073709506860, end=12', /home/marco/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/reedline-0.15.0/src/completion/base.rs:18:9
   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
   ```

I started a child process of Nu with `RUST_BACKTRACE=1` and got

```
thread 'main' panicked at 'Can't create a Span whose end < start, start=18446744073709506906, end=10', /home/marco/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/reedline-0.15.0/src/completion/base.rs:18:9
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: reedline::completion::base::Span::new
   3: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   4: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::fold
   5: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
   6: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
   7: nu_cli::completions::command_completions::CommandCompletion::complete_commands
   8: <nu_cli::completions::command_completions::CommandCompletion as nu_cli::completions::base::Completer>::fetch
   9: nu_cli::completions::completer::NuCompleter::process_completion
  10: nu_cli::completions::completer::NuCompleter::completion_helper
  11: <nu_cli::completions::completer::NuCompleter as reedline::completion::base::Completer>::complete
  12: <reedline::menu::columnar_menu::ColumnarMenu as reedline::menu::Menu>::update_values
  13: reedline::engine::Reedline::handle_editor_event
  14: reedline::engine::Reedline::handle_editor_event
  15: reedline::engine::Reedline::read_line
  16: nu_cli::repl::evaluate_repl
  17: nu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Expected behavior

I expected TAB completion to work properly here

### Screenshots

![Screenshot_20230205_193007](https://user-images.githubusercontent.com/60370605/216816193-bbbe1679-06af-42d5-90ff-efcd669606fd.png)

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.75.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)             |
| pkg_version        | 0.75.0                                          |
| build_time         | 2023-02-01 07:12:44 +08:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by nabacg** [comment]
I'm happy to take a look at this, unless someone is already on it?

**Comment by nabacg** [comment]
After a bit of debugging today, I found that nu is crashing because we're trying to subtract offset from 0 span in `span.start - offset` when creating Competition suggestions here
https://github.com/nushell/nushell/blob/ec4370069a418447fa148ce043e29adc539e7570/crates/nu-cli/src/completions/command_completions.rs#L97

Defensively adding a filter to only suggest span.start > offset in this line https://github.com/nushell/nushell/blob/ec4370069a418447fa148ce043e29adc539e7570/crates/nu-cli/src/completions/command_completions.rs#L167 seems to prevent it from crashing
```rust
.filter(|x| x.0.start > offset)
```

but I have no idea why what's the root cause here, perhaps it should be solve upstream?

**Comment by nabacg** [comment]
Raised draft PR #7971, since it's probably easier to read the code, than following links in comment above.

**Comment by Banyc** [comment]
With this test case:

```rust
#[rstest]
fn bug_7966_with_commandcompletion(mut completer_strings: NuCompleter) {
    let _suggestions = completer_strings.complete("FOO=bar ", 8);
}
```

`span == {start:0, end:111}` and `offset == 103` at

```rust
    fn complete_commands(
        &self,
        working_set: &StateWorkingSet,
        span: Span,
        offset: usize,
        find_externals: bool,
        match_algorithm: MatchAlgorithm,
    ) -> Vec<Suggestion> {
```

**Comment by sholderbach** [comment]
Thanks for the deep dive @Banyc !

> the `head` is assigned with `Span::unknown()`, which is a `{start:0, end:0}`
> 
> Design-wise, I think `Call::head` type should be `Option<Span>` or something to avoid sentinel values.

One downside to `Option<Span>` is that with the use of two `usize` at the moment this would require significantly more bits in every `Value` as there is no niche left. (changing to `NonZeroUsize` would also require some extra care in all the arithmetic, not that it is bug free at the moment). We need to have those niche/sentinel values not only in select places but also want to tag `Value`s or `PipelineData`s with it as they are the part frequently consumed to generate the error messages which are the raison d'être for all spananigans.

**Comment by kubouch** [comment]
I can't reproduce it anymore. Feel free to reopen if the problem appears again.
