### ISSUE TITLE
cannot open certain ini files

### ISSUE THREAD

**Issue by uncomfyhalomacro** [nushell/nushell#7981]
### Describe the bug

Not sure what the proper format of ini is but I have a configuration file written in ini:

```ini
background=11111Bff
border-color=B4BEFEff
icon-theme=Papirus
max-icon-size=84
title-color=7DC4E4ff
title-font=Ballinger Mono:size=12
summary-color=FAE3B0ff
summary-font=Ballinger Mono:size=10
body-color=eeeeeeff
body-font=Ballinger Mono:size=8
selection-helper=bemenu -p "Notification action: " 
max-timeout=25
default-timeout=20
play-sound=pw-play ${filename}
stacking-order=bottom-up
layer=overlay
anchor=top-right
min-width=450
max-width=820

[normal]
sound-file=/usr/share/sounds/freedesktop/stereo/dialog-information.oga

[critical]
border-color=FAB387ff
default-timeout=20
sound-file=/usr/share/sounds/freedesktop/stereo/dialog-warning.oga
```

However running `open fnott.ini` results in an error

```
Error: nu::shell::unsupported_input (link)

  × Unsupported input
   ╭─[entry #17:1:1]
 1 │ open fnott.ini
   · ──┬─┬
   ·   │ ╰── input type: value originates from here
   ·   ╰── Could not load ini: Custom("invalid type: string \"11111Bff\", expected a map")
   ╰────
```

### How to reproduce

1. Run `open fnott.ini`

Some certain configuration files in ini format won't work

### Expected behavior

I expected nu to open the file just fine.

### Screenshots

![image](https://user-images.githubusercontent.com/66054069/216887085-47d8f50b-7187-4981-858f-79d8dffb9bda.png)

### Configuration

**OS**: openSUSE TumbleWeed

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.75.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12) (built from a source tarball) |
| cargo_version      | cargo 1.66.0                                                      |
| pkg_version        | 0.75.0                                                            |
| build_time         | 2023-02-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | database, default, trash, which, zip                              |
| installed_plugins  |                                                                   |

**Comment by sholderbach** [comment]
Sounds very similar to #7970

**Comment by initinll** [comment]
Hi,

The current ini formatter relies on crate `serde_ini`, based on the crate description this formatter is quite limited and was updated 4 years ago, also does not work for above scenario.

May be nushell should move to new ini crate - `rust-ini ` or some other full fledged ini parser ?

I have tested above ini configurations with `rust-ini`, it parses the file successfully.

**Comment by WindSoilder** [comment]
Hi, feel free to move from `serde_ini` to `rust-ini`.  I think serde_ini is only used in `from ini` command

**Comment by uncomfyhalomacro** [comment]
Thanks @initinll. I was planning to PR but got busy since I forked the project yesterday. Thanks for taking the initiative ❤️❤️❤️
