### ISSUE TITLE
Announcement: Nu shell gained it's page in Command Line Interface Pages project

### ISSUE THREAD

**Issue by EmilySeville7cfg** [nushell/nushell#7985]
![image](https://user-images.githubusercontent.com/42812113/216903162-27eee9d1-6aeb-4ed6-bf59-3f3fedee9acc.png)

[Here](https://github.com/emilyseville7cfg-better-tldr/cli-pages) is a repo with all available pages. And [here](https://github.com/emilyseville7cfg-better-tldr/prototypes/tree/main/clip-view) is a render available for them.

**Comment by rgwood** [comment]
Cool, thanks for the heads up!
