### ISSUE TITLE
Please enable prebuilt workspaces to accelerate Gitpod start-up times

### ISSUE THREAD

**Issue by jankeromnes** [nushell/nushell#799]
Hello 👋

I work on Gitpod, and find Nu Shell super cool, so I was pretty excited to see you have a Gitpod setup! 🚀 (Great work @JesterOrNot! 💯)

While trying it out, I noticed that you could easily improve your Gitpod start-up times by enabling [prebuilt workspaces](https://www.gitpod.io/docs/46_prebuilds/). This will automatically run `cargo build` on every repo push or Pull Request, saving your contributors and maintainers up to **10 minutes** of waiting every time they start a workspace. ✨ 

<img width="477" alt="Screenshot 2019-10-07 at 12 50 07" src="https://user-images.githubusercontent.com/599268/66306067-059e2480-e901-11e9-9ac7-9acd30664b05.png">

Your current prebuild configuration already looks perfect:

https://github.com/nushell/nushell/blob/4467e59122f02bb9839ac249faf448c4213d1fc4/.gitpod.yml#L6-L13

However, for it to work you also need to install the [Gitpod hook](https://github.com/marketplace/gitpod-io), which will trigger new workspace prebuilds in Gitpod's infrastructure on every push (it's 100% free, without ads or evil data collection of any kind).

Please enable prebuilt workspaces by installing the missing hook. 🙂 I'm happy to help if you have any questions or concerns.

**Comment by jonathandturner** [comment]
Installed. Thanks for the heads up :)
