### ISSUE TITLE
Replace `fs_extra` dependency

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#7995]
Related: https://github.com/nushell/nushell/issues/6583

We use [`fs_extra`](https://github.com/webdesus/fs_extra/) in the `mv` command, specifically [the `fs_extra::dir::move_dir()` function](https://docs.rs/fs_extra/latest/fs_extra/dir/fn.move_dir.html).

This function [can cause data loss on case-insensitive filesystems](https://github.com/webdesus/fs_extra/issues/64). We've mostly worked around this, but the underlying bug still has not been fixed in `fs_extra`. It's been long enough without a fix that I think we should move on from `fs_extra`.

Not sure whether we want to write our own version of `move_dir()` or if there are other crates we can use.

**Comment by fdncred** [comment]
I was talking with @jntrnr the other day and was whining about how tired I am of the `cp`, `mv`, `rm` issues and was just wishing we could "borrow" code from [core-utils](https://github.com/GrayJack/coreutils). Not the 1000 parameters, but the underlying worker code. Just looking for a good implementation that we don't have to constantly fix corner cases.
