### ISSUE TITLE
Saving range to json ignores error

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#8002]
### Describe the bug

Try running:

```
> 1..10 | save foo.json
```

and look at the output foo.json

```json
null
```

### How to reproduce

1. see above

### Expected behavior

This should either:

- Expand the range and turn it into an array to save into the json
- OR error that ranges aren't supported

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.75.1                                   |
| branch             | main                                     |
| commit_hash        | 6e6ef862c500345c8bca3c74775b56b8b15d1175 |
| build_os           | macos-aarch64                            |
| build_target       | aarch64-apple-darwin                     |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-aarch64-apple-darwin              |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| pkg_version        | 0.75.1                                   |
| build_time         | 2023-02-08 15:08:12 +13:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by dmatos2012** [comment]
I would lean at maybe expanding the range and saving into the json and have output be, 
```
1..3 | save foo.json
[1,
2,
3,
]
```
but not sure if its just better to error out? Do you have a preference? Then I can try working on this :)

**Comment by fdncred** [comment]
@dmatos2012, I can see 2 options here.
1. Expand the range, either like you listed above or on one line `[1,2,3,]`
2. Store the range as is like `1..3`

This issue also makes me wonder how it should be handled in:
- to nuon
- to toml
- to yaml
- etc

**Comment by dmatos2012** [comment]
Ill go with option 1 then, and we can discuss then in the PR :D
