### ISSUE TITLE
count command

### ISSUE THREAD

**Issue by andrasio** [nushell/nushell#801]
As discussed in our Discord [![Discord](https://img.shields.io/discord/601130461678272522.svg?logo=discord)](https://discord.gg/NtAbbGn) chat:

I'd be nice to be able and print the total number of rows that a command gives. Let's say we call the command `count`. Example:

```
ls | where name == "Cargo.toml"

━━━━━━━━━━━━┯━━━━━━┯━━━━━━━━━━┯━━━━━━━━┯━━━━━━━━━━━━┯━━━━━━━━━━━━┯━━━━━━━━━━━━
 name       │ type │ readonly │ size   │ created    │ accessed   │ modified
────────────┼──────┼──────────┼────────┼────────────┼────────────┼────────────
 Cargo.toml │ File │          │ 4.2 KB │ 3 days ago │ 3 days ago │ 3 days ago
━━━━━━━━━━━━┷━━━━━━┷━━━━━━━━━━┷━━━━━━━━┷━━━━━━━━━━━━┷━━━━━━━━━━━━┷━━━━━━━━━━━━
```

Doing `ls | where name == "Cargo.toml" | count` should print `1`

**Comment by JackFly26** [comment]
I'll see what I can do tomorrow.

**Comment by andrasio** [comment]
Closing this. Implemented recently.

**Comment by waldyrious** [comment]
> Implemented recently.

IIUC, that would be #33, right? If so, and just for reference: the command is currently named `size`, but there's discussion in #408 to rename it to `count`.
