### ISSUE TITLE
`++` operator should concatenate binary values

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#8015]
### Related problem

It would be nice if `+` could concatenate binary values. This came up on Discord, a user was trying to concatenate binary values and `+` was the first thing they tried.

### Describe the solution you'd like

`0x[01 02] + 0x[03 04]` should evaluate to `0x[01 02 03 04]`. Right now, it fails:

![image](https://user-images.githubusercontent.com/26268125/217864909-cb23c30a-6590-4eba-bfb3-2eb3556dd52e.png)

### Additional context and details

`+` can already concatenate strings, so supporting binary values would make things more consistent.

# UPDATE

Let's do `++` instead of `+`, as suggested below

**Comment by fdncred** [comment]
I'd vote for `++` since we already have `++` as an `Append` operator and I think it's less confusing than the `Plus` operator.

**Comment by rgwood** [comment]
Hmm. Feels a little weird if `+` concatenates strings but not binary values. But I guess strings are kinda special, so ¯\\\_(ツ)\_/¯

**Comment by fdncred** [comment]
Maybe we should be consistent and change strings to `++`?

**Comment by rgwood** [comment]
I would vote to keep `+` for strings. `+` works to concatenate strings in lots of languages and it's (IMO) the first thing people will try. For this one, I think consistency with other languages is more important than internal consistency.

Maybe we could allow `+` _or_ `++` for strings?

**Comment by fdncred** [comment]
I think `+` and `++` is a good compromise.
