### ISSUE TITLE
add string scalar multiplication

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8039]
### Related problem

not really a problem, but i see we can do addition on `string`s
```bash
> "a" + "b"
ab
```
but we can not, as in `python`, perform `string` multiplication by an integer constant :thinking: 
```bash
> 2 * "a"
Error: nu::parser::unsupported_operation (link)

  × Types mismatched for operation.
   ╭─[entry #2:1:1]
 1 │ 2 * "a"
   · ┬ ┬ ─┬─
   · │ │  ╰── string
   · │ ╰── doesn't support these values.
   · ╰── int
   ╰────
  help: Change int or string to be the right types and try again.
```

### Describe the solution you'd like

some examples of the feature:
```bash
> 2 * "a"
aa
```
```bash
> let s = 3
> $s * "\nthis is an example"

this is an example
this is an example
this is an example
```
```bash
> let indent = 4 * " "
> print $"($indent)i'm indented"
    i'm indented
```

### Describe alternatives you've considered

we could imagine similar things with `list`s and `byte` sequences, which are very similar to `string`s to some extend :yum: 

- add two lists
```bash
> [1] + [2]  # would give [1, 2]
Error: nu::parser::unsupported_operation (link)

  × Types mismatched for operation.
   ╭─[entry #12:1:1]
 1 │ [1] + [2]
   · ─┬─ ┬ ─┬─
   ·  │  │  ╰── list<int>
   ·  │  ╰── doesn't support these values.
   ·  ╰── list<int>
   ╰────
  help: Change list<int> or list<int> to be the right types and try again.
```
- multiply a list by a scalar integer value
```bash
> 5 * [0]  # would give [0, 0, 0, 0, 0]
Error: nu::parser::unsupported_operation (link)

  × Types mismatched for operation.
   ╭─[entry #13:1:1]
 1 │ 5 * [0]
   · ┬ ┬ ─┬─
   · │ │  ╰── list<int>
   · │ ╰── doesn't support these values.
   · ╰── int
   ╰────
  help: Change int or list<int> to be the right types and try again.
```
- not sure what `2 * 0x[01]` or `0x[02] + 0x[03 04]` should be :thinking: 

> **Note**
> if you fell that should go in another issue, i can move these :relieved:

**Comment by fdncred** [comment]
I thought we just added `0x[02] ++ 0x[03 04]` and `'aa' ++ 'bb'`.

This was recently asked for in discord. I came up with this.
```bash
> def repeat [arg: string, dupe: int] {
  0..<$dupe | reduce -f '' {|i acc| $acc + $arg}
}
> repeat aa 2
aaaa
```

**Comment by amtoine** [comment]
> I thought we just added `0x[02] ++ 0x[03 04]` and `'aa' ++ 'bb'`.
> 
oooh yes you're right :+1:

> This was recently asked for in discord. I came up with this.
> 
> ```shell
> > def repeat [arg: string, dupe: int] {
>   0..<$dupe | reduce -f '' {|i acc| $acc + $arg}
> }
> > repeat aa 2
> aaaa
> ```
>
yup that works, but it's not a built-in `<string> * <int>` or `<int> * <string>` :wink: 

and it does not take the binary and list mutliplication by a scalar value :thinking: 

**maybe that could start by going in a new `stdlib.nu`? :smirk:**

**Comment by amtoine** [comment]
thanks a lot, that's amazing :relieved:

**Comment by amtoine** [comment]
works like a charm :ok_hand:
