### ISSUE TITLE
EDITOR cannot contain arguments

### ISSUE THREAD

**Issue by hut8** [nushell/nushell#8051]
### Describe the bug

I would like to set my `$env.EDITOR` so that it will cause this command to be run: `code --wait`. That's one command where `argv` is `['code', '--wait']`. I tried these two things:

```
let-env EDITOR = [ "code", "--wait" ]
# and
let-env EDITOR = "code --wait"
```

The first one says it wants a string, and got a `list<string>`, which makes sense. The second one says there's no command called `code --wait`. So I think it's trying to find a binary literally named `code --wait` in the path. Is there some way to do this, that I'm missing?

### How to reproduce

1. Run `let-env EDITOR = [ "code", "--wait" ]` or `let-env EDITOR = "code --wait"`
2. Run `config nu`
3. See error

### Expected behavior

Open `code` and pass in an argument `--wait`. Lots of editors need some sort of switch (I used to use `emacsclient -t`, because `emacsclient` by itself would fail if the emacs daemon isn't running).

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.74.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 9a56665c6beee31e365ce17898056f1ff2db4094                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12) (Arch Linux rust 1:1.66.0-1) |
| cargo_version      | cargo 1.66.0                                                     |
| pkg_version        | 0.74.0                                                           |
| build_time         | 2023-01-10 22:53:04 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | database, dataframe, default, trash, which, zip                  |
| installed_plugins  |                                                                  |

**Comment by bobhy** [comment]
The question is which tool is going to execute the contents of that EDITOR environment variable? If it's an external command, e.g , `git`, then the value must be visible in the OS (process) environment, and must therefore be a simple string.  Nushell allows environment variables to have other types (such as turning PATH into a list of directories), but that's only for use within Nushell.

You could create a shell script (bash, sh or, ps1) to invoke your editor with arguments, such as `code --wait $*`, put it in your path and point the environment variable at that. ( `$*` pulls any extra arguments the tool provides, such as file names, into shell script. Powershell syntax might differ....)

**Comment by bobhy** [comment]
I tried defining a Nushell alias, e.g, `alias xyz = code --wait`, and `let-env EDITOR = "xyz"`, but got this error when I tried to invoke it.
```
〉config env
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #5:1:1]
 1 │ config env
   · ─────┬────
   ·      ╰── executable 'xyz' was not found
   ╰────
  help: No such file or directory (os error 2)

```
So I think the external shell script hack is the only workaround currently available.

If there is an enhancement to allow EDITOR to be an array, I'd prefer a string value also be supported, the convention of environment variables as strings is pretty well ingrained.

**Comment by sholderbach** [comment]
I think the problem lies in the places where we read `EDITOR` and `VISUAL` to decide what to launch. I think it is easier to make that tolerant than to include an extra env conversion (which could effectively also only either pass a list or a string to that call site)
