### ISSUE TITLE
I want to be able to handle index like $it when dealing with arrays.

### ISSUE THREAD

**Issue by TwentyXX** [nushell/nushell#8067]
### Related problem

I am trying to do pick out the odd-numbered element of the array.
Example: `[a b c d e f g h i j]`  => `[a c e g i]`

I am using remainder as an example here, but would like to use other complex operations as well.

### Describe the solution you'd like

Add `$index`.

current:
`[a b c d e f g h i j] | where { |_, b| $b mod 2 == 0 }`

ideal for:
`[a b c d e f g h i j] | where $index mod 2 == 0`

### Additional context and details

I am new to making issues and am using a translator, so there may be points that are difficult to understand or rude.
Thank you in advance.

**Comment by hustcer** [comment]
You can use `enumerate` command:
```
[a b c d e f g h i j] | enumerate | where {|x| $x.index mod 2 == 0} | each { get item } | to nuon
```

**Comment by TwentyXX** [comment]
Thanks for the fairly quick reply.
I guess I can use the `enumerate`. I will use that method instead.
Thank you very much.
