### ISSUE TITLE
How to check if a command failed?

### ISSUE THREAD

**Issue by ClementNerma** [nushell/nushell#8068]
### Question

I'd like to do the following Bash thing in Nushell:

```bash
if ! command; then
  echo "Failed!"
fi
```

I can do it with:

```nushell
if command {} else {
  echo "Failed!"
}
```

Which is not very readable.

Doing `if not command { echo "Failed!" }` will not work as `command` does not evaluate to a boolean expression.

**Comment by WindSoilder** [comment]
A `try` block would be helpful.
```
try {
   adsfa
} catch {
   print 'failed'
}
```

**Comment by ClementNerma** [comment]
Nice! I didn't see that in the docs, thanks for pointing it out :)

Do you know how can I make a function fail by itself, e.g.:

```nushell
def test [] {
    if <condition not met> {
      throw "error message"
   }
}
```

?

**Comment by WindSoilder** [comment]
There is an command called `error make`, you can check the help message.

Yeah it contains eexamples :)

**Comment by ClementNerma** [comment]
I tried it with an empty `catch { }` and the error got displayed, didn't think I had to fill this block in order for this to work.
Thanks for your help!
