### ISSUE TITLE
File not found errors when Nu is inside folder which gets deleted after entering

### ISSUE THREAD

**Issue by theAkito** [nushell/nushell#8072]
### Describe the bug

Every command you issue in Nu, while Nu is in a folder, which gets deleted outside of Nu, after entering, outputs a couple of generic Nu Rust based "File not found" I/O errors.

### How to reproduce

1. Enter folder `Downloads` inside a Nu shell.
2. Delete this `Downloads` folder from outside Nu.
3. Every following command in Nu outputs several "File not found" I/O errors.

### Expected behavior

Nu should do something different, than outputting several generic "File not found" I/O errors.
Either change the error to being specific and being only output a single time or make something even smarter, if it isn't too costly, performance-wise.

For example, output only a single error saying, that the current folder does not exist, anymore.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.74.0                                   |
| branch             |                                          |
| commit_hash        | 9a56665c6beee31e365ce17898056f1ff2db4094 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | 1.65.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.74.0                                   |
| build_time         | 2023-01-10 20:32:31 +00:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by mikeyoung3k** [comment]
For reference, all commands, even if unrelated to the CWD, fail with confusing output. I think this is down to the loop starting with `get_guaranteed_cwd`

Not sure what the ethos behind this is, but I would assume that being in a pwd that doesn't exist is Ok when doing unrelated commands. 

I also don't know why it's printing to screen 3 times.

![image](https://user-images.githubusercontent.com/49405153/220162235-c35ff867-e3e7-412b-9b25-5ae4d6e4c2f6.png)

**Comment by WindSoilder** [comment]
It's fixed in #12779, so I will close the issue.
Feel free to reopen it if issue still happened
