### ISSUE TITLE
`input` is non-interruptible

### ISSUE THREAD

**Issue by ineu** [nushell/nushell#8074]
### Describe the bug

Hello and thanks for the great product! Playing with nu for a few days now and enjoying it a lot.

Found an issue: when `input` is interrupted via `C-c`, it won't stop.`^C` is emited, the command keeps running

As a workaround I can use C-d, but it is meant to mean EOF, not interrupt.

### How to reproduce

1. Run `input`
2. Hit `C-c`

### Expected behavior

The command is stopped, the execution is back to the shell

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.74.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 9a56665c6beee31e365ce17898056f1ff2db4094                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12) (Arch Linux rust 1:1.66.0-1) |
| cargo_version      | cargo 1.66.0                                                     |
| pkg_version        | 0.74.0                                                           |
| build_time         | 2023-01-10 22:53:04 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | database, dataframe, default, trash, which, zip                  |
| installed_plugins  |                                                                  |

**Comment by ryand67** [comment]
I can take this one!

**Comment by sholderbach** [comment]
Thanks @ryand67, have fun!

**Comment by ryand67** [comment]
Hey @sholderbach, had a quick question, in the input.rs file it's easy enough to get ctrl-c working when the terminal is in raw mode and we can loop over KeyEvents as they come in, but for the command with no flags we just use a basic read_line(). Is there a particular reason that an optionless call for input can't take from the other parts of the command and use the raw mode to constantly loop over the input? Thanks!

**Comment by sholderbach** [comment]
Closed by #8159

**Comment by ineu** [comment]
Is it really fixed? I see it marked as v0.77.0 milestone, but for me in 0.82.0 the issue still exist

**Comment by sholderbach** [comment]
Ah right in the PR @ryand67 mentioned that it doesn't cover all options equally.
