### ISSUE TITLE
Previous command's last argument

### ISSUE THREAD

**Issue by ineu** [nushell/nushell#8081]
### Related problem

In bash/zsh there's a keybinding `alt+.` which inserts the last argument of the previous command. I find it very handy and use all the time. Missing it in nu.

### Describe the solution you'd like

Add the described feature to nushell either by default or configurable.

Not sure if this request belongs to nushell or reedline, please let me know if I sure open the issue in the reedline's repo.

Thank you.

**Comment by fdncred** [comment]
Here are 2 keybindings that will do it but work in different ways. One of them is commented out.
```
  {
    name: insert_last_token
    modifier: alt
    keycode: char_.
    mode: emacs
    event: [
      { edit: InsertString, value: " !$" }
      { send: Enter }
    ]
  }
#   {
#     mode: vi_insert
#     modifier: alt
#     keycode: char_.
#     event: {
#         send: executeHostCommand
#         cmd: "commandline --insert (history | last | get command | parse --regex '(?P<arg>[^ ]+)$' | get arg | first)"
#     }
#   }
```

**Comment by ineu** [comment]
Thanks a lot, the first one is exactly what I needed!

Where do I find a list of expansions like `!!` or `!$`?

**Comment by fdncred** [comment]
They both do the same thing, just in different ways.

I'm not sure it's documented anywhere but the code for it is in reedline. You can find them if you search for bashisms. These are the ones I know. There may be more that I've forgotton.

`!!`
`!?`
`!number`
`!-number`

**Comment by ineu** [comment]
Yeah, that's what I found: https://github.com/nushell/reedline/blob/main/src/menu/menu_functions.rs#L24

Thank you!

**Comment by Muttsuri** [comment]
Why isn't this documented anywhere ?

**Comment by rifazn** [comment]
I think it should come built-in to readline's shortcuts instead of the config workaround.

Consider reopening the issue until a we get an official statement?

**Comment by fdncred** [comment]
!$ is built into reedline already

**Comment by rifazn** [comment]
But you still need to add configs to make it work with the Alt-. shortcut. Just like for all the other readline shortcuts (c-a, c-e, c-b, c-f, c-u, c-k, etc.) this also needs to be there right off the bat.

Nushell also boasts 'sensible defaults' in its factory config file, and this shortcut begs to be a part of that.

**Comment by T3sT3ro** [comment]
> Here are 2 keybindings that will do it but work in different ways. One of them is commented out.
> 
> ```
>   {
>     name: insert_last_token
>     modifier: alt
>     keycode: char_.
>     mode: emacs
>     event: [
>       { edit: InsertString, value: " !$" }
>       { send: Enter }
>     ]
>   }
> ```

this workaround doesn't work the same way as bash/zsh ones — the latter cycle and replace last argument, this one simply inserts it.
