### ISSUE TITLE
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0'

### ISSUE THREAD

**Issue by ArekMiszcz** [nushell/nushell#809]
**This is what i did**

sudo find | where size > 4kb

**This is what i get**

thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/20cc75272619cc452e3ae6c131e61974f6aa9929/src/libcore/slice/mod.rs:2716:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**This is what i expect**
Table of files paths which are size greater than 4kb

**Comment by jonathandturner** [comment]
It shouldn't panic, but I think what you're trying to do will need a different command. `sudo fibd` doesn't return a table. Overall, it will return strings you will need to parse to use (using something like `split-column`

You can do something similar to what you're trying using the built-in `ls` command. 

Someone like `ls ** | where size > 4kb`. 

(I'm on my phone, apologies if this is inaccurate)

**Comment by ArekMiszcz** [comment]
It's ok but ls ** freezing shell. It looks like ls trying at first put everything into memory and after that print it to the output.

**Comment by jonathandturner** [comment]
Indeed. The current version of `ls **` will put everything into memory.  With luck, that will get fixed this weekend, as we're currently changing it to output results as it finds them rather than trying to do them all at once.

**Comment by jonathandturner** [comment]
With #812, you should be able to use `ls **` 

That said, I'd still like to fix the issue you found, also
