### ISSUE TITLE
Cannot provide default values for list arguments

### ISSUE THREAD

**Issue by aidalgol** [nushell/nushell#8092]
### Describe the bug

It is impossible to define a command with an argument of type `list` and a default value.

### How to reproduce

Evaluate the following in a `nu` shell:
```swift
def my-cmd [
  foo: list = ["junk"]
] {
  echo ($foo | str join ,)
}
```
Which will produce the following error
```console
Error: nu::parser::assignment_mismatch (link)

  × Default value wrong type
   ╭─[entry #7:1:1]
 1 │ def my-cmd [
 2 │   foo: list = ["junk"]
   ·               ────┬───
   ·                   ╰── default value not list<any>
 3 │ ] {
   ╰────
```

### Expected behavior

The command `my-cmd` would be defined and take an optional list argument that defaults to the list value `["junk"]`.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.75.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10) (built from a source tarball) |
| cargo_version      | cargo 1.66.1                                                      |
| pkg_version        | 0.75.0                                                            |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | database, default, trash, which, zip                              |
| installed_plugins  |                                                                   |

**Comment by amtoine** [comment]
this looks related to #8109, isn't it? 

i've tested #8096 and it looks it's working fine now :relieved:

**Comment by amtoine** [comment]
it works indeed :ok_hand:
