### ISSUE TITLE
`rm` trash flags should just be ignored on Android

### ISSUE THREAD

**Issue by dead10ck** [nushell/nushell#8104]
### Describe the bug

Currently there is a bunch of conditional code in the `rm` command such as:

https://github.com/nushell/nushell/blob/66398fbf77d03a6c7fd231da157f410d0446132e/crates/nu-command/src/filesystem/rm.rs#L54-L85

This is problematic, as any script that makes use of these flags is not portable to iOS or Android. For example, `broot`'s launcher script throws an error in Termux:

```
Error: nu::parser::unknown_flag (link)

  × The `rm` command doesn't have flag `-p`.
    ╭─[3:17:1]
 17 │     let $cmd = (open $cmd_file)
 18 │     rm -p -f $cmd_file
    ·         ┬
    ·         ╰── unknown flag
 19 │
    ╰────
  help: Available flags: --help(-h), --recursive(-r),
        --force(-f), --verbose(-v), --interactive(-i),
        --interactive-once(-I). Use `--help` for more
        information.
```

Rather than have the flags be completely absent, they should instead be ignored so that scripts will be portable across platforms without crazy hacky workarounds like having to check your platform first, or trying to parse the help message to figure out if this platform has the `-p` flag.

### How to reproduce

1. Install nu on Termux / Android
2. Run `rm -p somefile`

### Expected behavior

The flag is just ignored, and perhaps a warning message could be printed.

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.75.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | linux-x86_64                         |
| build_target       | aarch64-linux-android                |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)  |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu      |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)  |
| pkg_version        | 0.75.0                               |
| build_time         | 2023-02-01 00:37:05 +00:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

**Comment by rgwood** [comment]
This is an interesting one. I can see both sides of the issue; the current approach makes cross-platform scripting harder, but it's also not great to have flags that are silently ignored. I can see people being quite angry when they explicitly tell `rm` to put something in the trash and it's deleted forever!

Honestly not sure what the right approach is here, but I _think_ I lean toward keeping the existing behaviour. Curious what other people think.

**Comment by dead10ck** [comment]
>I can see people being quite angry when they explicitly tell rm to put something in the trash and it's deleted forever!

For that it's worth, with `-p`, this would do exactly what the user asked for. The only "surprise" might be from using `-t` or setting the `always_trash` config to true. And in my opinion, the current behavior around these settings is very inconsistent and kludgy right now. Currently it does not ignore `always_trash`—it will do nothing when it's false, and when it's true, `rm` will just flat out refuse to do anything. The user can't even work around it by adding `-p` because it's not even compiled in!

In my opinion, the trash feature is pretty niche for a command line tool to begin with. Most standard tools for deleting files on the command line don't have any integration with the trash at all; permanent deletion is pretty standard behavior on the command line that I think most people will be used to.

In my opinion, making the core tools and scripts cross platform compatible should take a higher priority than concern over a feature that doesn't exist on the platforms concerned to begin with.

**Comment by rgwood** [comment]
> For that it's worth, with -p, this would do exactly what the user asked for. 

True, I think adding that flag on Android would be OK. I'm less enthusiastic about `-t`.

**Comment by dead10ck** [comment]
That seems like a fair compromise. I would venture a guess that `-t` will be less common than `-p` in scripts. This code looks fairly self contained and straightforward, so if no one gets to this before me, I could take a crack at it when I get some spare time.
