### ISSUE TITLE
Make "rename" accept a closure

### ISSUE THREAD

**Issue by ineu** [nushell/nushell#8108]
### Related problem

I have a table with columns coming from an external api (the result of `kubectl` command). The columns are all upcased, so I want to downcase them before working with the table. So the exact same operation must be performed on each column name. `rename` in this case is not consistent because it requires me to:
1. Know all column names in advance
2. Explicitly specify all column names in the command

### Describe the solution you'd like

Make `rename` accept a closure to apply to each column, accepting a column name and returning a new name, like this:
```
kubectl get pv | from ssv | rename { |name| $name | str downcase | str trim }
# or
kubectl get pv | from ssv | rename { $in | str downcase | str trim }
```

### Describe alternatives you've considered

The workaround I'm using at the moment:
```
    kubectl get pv
        | from ssv
        | transpose | update column0 { |it| $it.column0 | str downcase } | transpose -r # downcase names
```

**Comment by fdncred** [comment]
I wrote this the other day in discord which passes a closure.
```
> def transform [fn: closure] {
  $in | transpose | update column0 {|r| $r.column0 | do $fn} | transpose -r
}
> ls | transform {str upcase}
╭────┬─────────────────────────────┬──────┬──────────┬───────────────╮
│  # │            NAME             │ TYPE │   SIZE   │   MODIFIED    │
├────┼─────────────────────────────┼──────┼──────────┼───────────────┤
│  0 │ .cargo                      │ dir  │      0 B │ 3 months ago  │
│  1 │ .github                     │ dir  │   4.1 KB │ a month ago   │
│  2 │ .gitignore                  │ file │    579 B │ 3 months ago  │
```

And Yethal posted this one.

```
ls|transpose|update column0 {get column0|str upcase}|transpose -r
```

But a closure may be helpful too on rename. I can see the value in it. We'd probably accept a PR for it.
