### ISSUE TITLE
`table -c` should follow nushell table alignment rules

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#8112]
### Describe the bug

I'm really starting to warm up to this new `table` output. I just really wish it would follow the regular nushell table alignment rules (and colors, mentioned in another issue #8110).
```
> open Cargo.toml | get workspace | table -c
╭─────────┬────────────────────────────────╮
│ members │         crates/nu-cli          │
│         ├────────────────────────────────┤
│         │        crates/nu-engine        │
│         ├────────────────────────────────┤
│         │        crates/nu-parser        │
│         ├────────────────────────────────┤
│         │        crates/nu-system        │
│         ├────────────────────────────────┤
│         │       crates/nu-command        │
│         ├────────────────────────────────┤
│         │       crates/nu-protocol       │
│         ├────────────────────────────────┤
│         │        crates/nu-plugin        │
│         ├────────────────────────────────┤
│         │      crates/nu_plugin_inc      │
│         ├────────────────────────────────┤
│         │     crates/nu_plugin_gstat     │
│         ├────────────────────────────────┤
│         │    crates/nu_plugin_example    │
│         ├────────────────────────────────┤
│         │     crates/nu_plugin_query     │
│         ├────────────────────────────────┤
│         │ crates/nu_plugin_custom_values │
│         ├────────────────────────────────┤
│         │    crates/nu_plugin_formats    │
│         ├────────────────────────────────┤
│         │        crates/nu-utils         │
╰─────────┴────────────────────────────────╯
```

### How to reproduce

See above

### Expected behavior

Alignment matches the same rules as if `| table` was used as in `open Cargo.toml | get workspace.members` but without the index column.

### Configuration

|key|value|
|-|-|
|version|0.75.1|
|branch|main|
|commit_hash|68ad854b0d1736d6b656dcf53800c7f3eb32d7e1|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.66.1 (90743e729 2023-01-10)|
|rust_channel|1.66.1-aarch64-apple-darwin|
|cargo_version|cargo 1.66.1 (ad779e08b 2023-01-10)|
|pkg_version|0.75.1|
|build_time|2023-02-18 07:43:21 -06:00|
|build_rust_channel|release|
|features|database, dataframe, default, trash, which, zip|
|installed_plugins|custom-value generate, custom-value generate2, custom-value update, from eml, from ics, from ini, from parquet, from plist, from vcf, gstat, hist, inc, nu-example-1, nu-example-2, nu-example-3, periodic-table, plot, pnet, query, query json, query web, query xml, regex, xyplot|

### Additional context

/cc @zhiburt

**Comment by zhiburt** [comment]
It'll take a bit of time;

**Comment by fdncred** [comment]
> But it could be made to be left/right aligned all the time instead of center. (I think left aligned is better)

Nushell aligned by data type. So, numbers & file size units get right aligned and text gets left aligned. There may be more cases in the code (can't remember) but those are the ones that stand out as "normal" alignment.

**Comment by dschrempf** [comment]
Hi! I also suggest aligning text to the right, if it is the last column! Alignment should probably also affect headers, which are all centered at the moment, as far as I can see.

**Comment by zhiburt** [comment]
Yet I am not sure about the best way to do it.
Specifically I am tend to believe it must be done somehow via settings to `tabled::tables::PoolTable`, but I do not know what the best way how to target a cell, eg. index (row, col), or some trait.

So yes I yet don't about it.

We could make 2 more pathes over `nu_protocol::Value` but it's certainly a resource waste.

___________________

Just noticed that we probably shall keep `rows` having the same height.
Which actually a related issue, either we need so settings interface or a new set of pathes.

`ps` output

![image](https://github.com/nushell/nushell/assets/20165848/591da454-6ac8-4b3d-88fb-5dcd0db255b0)

**Comment by zhiburt** [comment]
Hi @dschrempf 

> Hi! I also suggest aligning text to the right, if it is the last column!

As I remember it's not how it's done in general table views?

**Comment by dschrempf** [comment]
I do not know, I am just arguing from an estetical perspective. The column on the right looks a bit messy if it is not right-aligned:
![image](https://github.com/nushell/nushell/assets/5596239/025cade4-7891-4d36-bbe2-6a431a5e0046)

**Comment by fdncred** [comment]
As my original issue is solved (i think), I'm going to close this. The other alignment topics should exist in their own ticket.
```
open Cargo.toml | get workspace | table -c
╭─────────┬────────────────────────────────╮
│ members │ crates/nu-cli                  │
│         ├────────────────────────────────┤
│         │ crates/nu-engine               │
│         ├────────────────────────────────┤
│         │ crates/nu-parser               │
│         ├────────────────────────────────┤
│         │ crates/nu-system               │
│         ├────────────────────────────────┤
│         │ crates/nu-cmd-lang             │
│         ├────────────────────────────────┤
│         │ crates/nu-command              │
│         ├────────────────────────────────┤
│         │ crates/nu-protocol             │
│         ├────────────────────────────────┤
│         │ crates/nu-plugin               │
│         ├────────────────────────────────┤
│         │ crates/nu_plugin_inc           │
│         ├────────────────────────────────┤
│         │ crates/nu_plugin_gstat         │
│         ├────────────────────────────────┤
│         │ crates/nu_plugin_example       │
│         ├────────────────────────────────┤
│         │ crates/nu_plugin_query         │
│         ├────────────────────────────────┤
│         │ crates/nu_plugin_custom_values │
│         ├────────────────────────────────┤
│         │ crates/nu_plugin_formats       │
│         ├────────────────────────────────┤
│         │ crates/nu-std                  │
│         ├────────────────────────────────┤
│         │ crates/nu-utils                │
╰─────────┴────────────────────────────────╯
```
