### ISSUE TITLE
strange pasting behavior

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#8113]
### Describe the bug

I was working another issue and copied this information from https://github.com/nushell/nushell.github.io/issues/788.

```
let places = {
	usa: [ut, ca, co],
	canada: [bc, on, qc],
}
```
When I paste it in wezterm or iterm2 on my mac, it pastes like this. `note the extra src/ strings`
![image](https://user-images.githubusercontent.com/343840/219869688-ce345725-8e96-4819-8914-a0412cfc5399.png)

I thought it was `reedline` but I ran the reedline demo and pasted it in there and, while not perfect, it's not as messed up.
![image](https://user-images.githubusercontent.com/343840/219869746-733d12de-4f94-4037-85be-f0d6ce92f975.png)

### How to reproduce

See above

### Expected behavior

Paste properly

### Configuration

|key|value|
|-|-|
|version|0.75.1|
|branch|main|
|commit_hash|68ad854b0d1736d6b656dcf53800c7f3eb32d7e1|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.66.1 (90743e729 2023-01-10)|
|rust_channel|1.66.1-aarch64-apple-darwin|
|cargo_version|cargo 1.66.1 (ad779e08b 2023-01-10)|
|pkg_version|0.75.1|
|build_time|2023-02-18 07:43:21 -06:00|
|build_rust_channel|release|
|features|database, dataframe, default, trash, which, zip|
|installed_plugins|custom-value generate, custom-value generate2, custom-value update, from eml, from ics, from ini, from parquet, from plist, from vcf, gstat, hist, inc, nu-example-1, nu-example-2, nu-example-3, periodic-table, plot, pnet, query, query json, query web, query xml, regex, xyplot|

**Comment by weirdan** [comment]
@fdncred does it still happen?

**Comment by fdncred** [comment]
Thanks @weirdan. I tested on ghostty, wezterm, and iterm2 and none of them exhibit the problem any longer.
