### ISSUE TITLE
`completions.external.enable` is not working

### ISSUE THREAD

**Issue by honnip** [nushell/nushell#8118]
### Describe the bug

External completer continues to work despite setting `completions.external.enable` to false in config.nu.

### How to reproduce

1. setup carapace as external completer
2. set `completions.external.enable` to false.
3. type `git a<TAB>`

### Expected behavior

![스크린샷 2023-02-19 14-16-25](https://user-images.githubusercontent.com/108175486/219925558-028e0601-ad29-44ec-8dee-b1ac7ea8fec5.png)
*`git a<tab>`*

The file path should be suggested as completion

### Screenshots

![스크린샷 2023-02-19 14-13-20](https://user-images.githubusercontent.com/108175486/219923567-4641922b-a3c4-4815-ba9f-1d98e7780179.png)
*`git a<tab>`*

but it suggests completions by external completer (carapace)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.75.1                                   |
| branch             | main                                     |
| commit_hash        | f3ee8b50e3da9548fe39cfb104a20d6da10a6458 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| pkg_version        | 0.75.1                                   |
| build_time         | 2023-02-19 14:11:07 +09:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by WindSoilder** [comment]
I think it works as expected, it should suggest sub command rather than file path.   In your case, `git assets` have no meaning

**Comment by honnip** [comment]
Is this expected even when `completions.external.enable` is false?  If so, I'm not sure what `completions.external.enable` is for..

**Comment by fdncred** [comment]
I don't believe `completions.external.enable` is about turning off the external completer. See the comments in the default_config.nu.
```
  completions: {
    case_sensitive: false # set to true to enable case-sensitive completions
    quick: true  # set this to false to prevent auto-selecting completions when only one remains
    partial: true  # set this to false to prevent partial filling of the prompt
    algorithm: "prefix"  # prefix or fuzzy
    external: {
      enable: true # set to false to prevent nushell looking into $env.PATH to find more suggestions, `false` recommended for WSL users as this look up my be very slow
      max_results: 100 # setting it lower can improve completion performance at the cost of omitting some options
      completer: null # check 'carapace_completer' above as an example
    }
  }
```
