### ISSUE TITLE
Make `source` file-relative in `env.nu` and `config.nu`

### ISSUE THREAD

**Issue by x3rAx** [nushell/nushell#8127]
### Related problem

As described in https://github.com/nushell/nushell/issues/5853, the `source` keyword should be file-relative, which seems to work now for scripts that are run from the cli. But it does not seem to work for `env.nu` and `config.nu` (or more generally `$nu.env-path` and `$nu.config-path`).

I tried to split my config into multiple files and put them in a `user` folder next to `$nu.config-path`. But when I try to source a file using `source ./user/my-config.nu` I get `File not found`.

From within `my-config.nu` I can use `source` with a relative path. So it seems like it's only `$nu.env-path` and `$nu.config-path` that do not comply.

### Describe the solution you'd like

Obviously I'd like `source` to be file-relative in `$nu.env-path` and `$nu.config-path` too.

### Additional context and details

|key|value|
|-|-|
|version|0.75.0|
|branch||
|commit_hash||
|build_os|linux-x86_64|
|build_target|x86_64-unknown-linux-gnu|
|rust_version|rustc 1.67.0 (fc594f156 2023-01-24) (built from a source tarball)|
|cargo_version|cargo 1.67.0|
|pkg_version|0.75.0|
|build_time|1980-01-01 00:00:00 +00:00|
|build_rust_channel|release|
|features|database, default, trash, which, zip|
|installed_plugins||

`/etc/lsb-release`:
|key|val|
|-|-|
|DISTRIB_CODENAME|raccoon|
|DISTRIB_DESCRIPTION|"NixOS 22.11 (Raccoon)"|
|DISTRIB_ID|nixos|
|DISTRIB_RELEASE|"22.11"|
|LSB_VERSION|"22.11 (Raccoon)"|

`/etc/os-release`:
|key|val|
|-|-|
|BUG_REPORT_URL|"https://github.com/NixOS/nixpkgs/issues"|
|BUILD_ID|"22.11.2606.2fb7d749c08"|
|DOCUMENTATION_URL|"https://nixos.org/learn.html"|
|HOME_URL|"https://nixos.org/"|
|ID|nixos|
|LOGO|"nix-snowflake"|
|NAME|NixOS|
|PRETTY_NAME|"NixOS 22.11 (Raccoon)"|
|SUPPORT_END|"2023-06-30"|
|SUPPORT_URL|"https://nixos.org/community.html"|
|VERSION|"22.11 (Raccoon)"|
|VERSION_CODENAME|raccoon|
|VERSION_ID|"22.11"|

**Comment by Abdillah** [comment]
Do you successfully overcome the split problem, @x3rAx ? Is that by using full path?

I tried to use variable `source $"($nu.config-path)/completions/git.nu"` but get "value not constant" error.

**Comment by amtoine** [comment]
> I tried to use variable `source $"($nu.config-path)/completions/git.nu"` but get "value not constant" error.
>
this is because `source` is a parse-time command :smirk: 

what i would do is the following
- add `$nu.config-path | path dirname` to your `NU_LIB_DIRS` in `env.nu`
- run `source completions/git.nu` in `config.nu` or in the REPL

:yum:

**Comment by Abdillah** [comment]
Good things, thanks!

**Comment by amtoine** [comment]
> Good things, thanks!
>
anytime :blush:

**Comment by amtoine** [comment]
@star-szr 
very good catch :clap: :clap: 

the two issues look the same so
# closing in favor of #7849

**Comment by x3rAx** [comment]
Yes, https://github.com/nushell/nushell/issues/7849 describes the same issue but it doesn't mention that the same issue applies to `env.nu`.

**Comment by amtoine** [comment]
@x3rAx 
thanks for adding this to the other issue :pray:
