### ISSUE TITLE
`from toml` works differently on Windows than Linux

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#8139]
## Linux
```
cargo llvm-cov show-env | from toml  
╭───────────────────────────┬────────────────────────────────────────────────────────────────╮
│ CARGO_INCREMENTAL         │ 0                                                              │
│ CARGO_LLVM_COV_TARGET_DIR │ /home/fdncred/src/forks/nushell/target                         │
│ LLVM_PROFILE_FILE         │ /home/fdncred/src/forks/nushell/target/nushell-%p-%m.profraw   │
│ NEXTEST_TEST_THREADS      │ 1                                                              │
│ RUSTFLAGS                 │ -C instrument-coverage --cfg=coverage --cfg=trybuild_no_target │
│ RUST_TEST_THREADS         │ 1                                                              │
╰───────────────────────────┴────────────────────────────────────────────────────────────────╯
```

## Windows

```
cargo llvm-cov show-env | from toml
Error: nu::shell::cant_convert (link)

  × Can't convert to structured toml data.
   ╭─[entry #3:1:1]
 1 │ cargo llvm-cov show-env | from toml
   · ──┬──
   ·   ╰── can't convert string to structured toml data
   ╰────
```
I believe this is because Windows is returning double quoted variables, which enables string escape interpreting, with the traditional Windows path back slashes which are being interpreted as escapes.

```
RUSTFLAGS="-C link-args=-stack:10000000 -C target-feature=+crt-static -C instrument-coverage --cfg=coverage --cfg=trybuild_no_target"
LLVM_PROFILE_FILE="C:\CarTar\nushell-%p-%m.profraw"
CARGO_INCREMENTAL="0"
RUST_TEST_THREADS="1"
NEXTEST_TEST_THREADS="1"
CARGO_LLVM_COV_TARGET_DIR="C:\CarTar"
```

This works fine (although the syntax for str replace is just odd, perhaps another bug)
```
cargo llvm-cov show-env | str replace '\\' '\\' -a | from toml
╭───────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ CARGO_INCREMENTAL         │ 0                                                                                                                         │
│ CARGO_LLVM_COV_TARGET_DIR │ C:\CarTar                                                                                                                 │
│ LLVM_PROFILE_FILE         │ C:\CarTar\nushell-%p-%m.profraw                                                                                           │
│ NEXTEST_TEST_THREADS      │ 1                                                                                                                         │
│ RUSTFLAGS                 │ -C link-args=-stack:10000000 -C target-feature=+crt-static -C instrument-coverage --cfg=coverage --cfg=trybuild_no_target │
│ RUST_TEST_THREADS         │ 1                                                                                                                         │
╰───────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

I'm not sure what the correct fix is.
1. Should double quotes passed in behave like escapes?
2. Should from toml somehow accommodate windows paths somehow?
3. Should we just change our behavior here because this is how it's supposed to work? https://github.com/nushell/nushell/blob/b9be416937074fdeb5b337fc2dfda165e84be5a9/coverage-local.nu#L25

### How to reproduce

See above

### Expected behavior

Just work

### Configuration

|key|value|
|-|-|
|version|0.75.1|
|branch|main|
|commit_hash|daeb3e51874ce92c5ad552d1ec287894c32a4c4b|
|build_os|windows-x86_64|
|build_target|x86_64-pc-windows-msvc|
|rust_version|rustc 1.66.1 (90743e729 2023-01-10)|
|rust_channel|1.66.1-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.66.1 (ad779e08b 2023-01-10)|
|pkg_version|0.75.1|
|build_time|2023-02-17 07:26:04 -06:00|
|build_rust_channel|release|
|features|database, dataframe, default, trash, which, zip|
|installed_plugins|custom-value generate, custom-value generate2, custom-value update, from eml, from ics, from ini, from parquet, from plist, from vcf, gstat, hist, inc, nu-example-1, nu-example-2, nu-example-3, periodic-table, plot, pnet, query, query json, query web, query xml, regex, xyplot|

**Comment by ChrisDenton** [comment]
Per the toml spec, single quotes should be used in this case. Indeed a Windows path is the first example for literal strings on their website https://toml.io

Personally I think it'd be surprising if nushell deviated from the toml spec.

**Comment by fdncred** [comment]
So, if I understand you right @ChrisDenton, you're saying that the toml crate is working as it should, and our nushell code is working like it should, but we should change the double quotes to single quotes to account for this unwanted escaping like this, correct? It seems to work better.

```
cargo llvm-cov show-env | str replace '"' "'" -a | from toml 
╭───────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ CARGO_INCREMENTAL         │ 0                                                                                                                         │
│ CARGO_LLVM_COV_TARGET_DIR │ C:\CarTar                                                                                                                 │
│ LLVM_PROFILE_FILE         │ C:\CarTar\nushell-%p-%m.profraw                                                                                           │
│ NEXTEST_TEST_THREADS      │ 1                                                                                                                         │
│ RUSTFLAGS                 │ -C link-args=-stack:10000000 -C target-feature=+crt-static -C instrument-coverage --cfg=coverage --cfg=trybuild_no_target │
│ RUST_TEST_THREADS         │ 1                                                                                                                         │
╰───────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
or maybe more readable as this below, replacing double quotes (dq) with single quotes (sq)
```
cargo llvm-cov show-env | str replace (char dq) (char sq) -a | from toml
```

**Comment by ChrisDenton** [comment]
For sure, that works. Perhaps a more principled way would be to have a proper format reader for what's being output by `cargo llvm-cov show-env`, as it's not actually toml. But that might be overkill for this. I don't know.
