### ISSUE TITLE
Ranges work differently in Nushell than Rust and other 0-index languages  

### ISSUE THREAD

**Issue by bobhy** [nushell/nushell#8162]
### Related problem

Nushell default range is closed (includes both start and end values), those in Rust are half open (\>= start but \< end).

```rust
〉[0,1,2,3] | range ..2
╭───┬───╮
│ 0 │ 0 │
│ 1 │ 1 │
│ 2 │ 2 │
╰───┴───╯

〉[0,1,2,3] | range ..<2
╭───┬───╮
│ 0 │ 0 │
│ 1 │ 1 │
╰───┴───╯
```
This was a nasty suprise to me (as a newish user in both languages. I want to think of Nushell as interactive Rust with some other good stuff, not as something that's subtly different from Rust, way down in my muscle memory that I will have to be eternally vigilant about, but still with a bunch of good stuff.  

First, forget your extensive experience with Nushell and just just eyeball the examples.  With `..2`, why should a range that ends with a 2 return 3 elements?    With `..<2` I'm not getting less than 2 elements.
  
Rust,  [C++](https://learn.microsoft.com/en-us/cpp/standard-library/subrange-class?view=msvc-170), [Python](https://www.w3schools.com/python/ref_func_range.asp), [C#](https://learn.microsoft.com/en-us/dotnet/api/system.range?view=net-7.0) all have explicit range operators with the half-open semantics.  I think the reason is to play well with 0-origin indexing (which is a gift from heaven).  You see a range that ends with value '4' and think to your self, "that's elements 0, 1, 2 and 3; 4 elements". It's consistent with the "n-1" double think that is baked into the first element being 0.  

I get it that Nushell is logically correct here: you specify the desired first and last index you want the range to have.  
PHP [agrees](https://www.php.net/manual/en/function.range.php).  

### Describe the solution you'd like

I would like Nushell to match Rust syntax and semantics.

(the language I wish I had)
```rust
〉[0,1,2,3] | range ..=2
╭───┬───╮
│ 0 │ 0 │
│ 1 │ 1 │
│ 2 │ 2 │
╰───┴───╯

〉[0,1,2,3] | range ..2
╭───┬───╮
│ 0 │ 0 │
│ 1 │ 1 │
╰───┴───╯
```

### Describe alternatives you've considered

I bet there was lots of discussion about this before, and I don't want to reopen all the old arguments, but I note that other users are tripping over related issues (#7761) and I really think Rust has it right here.

### Additional context and details

This is a very big breaking change.  Now or never!  Do you want to be more like Rust or more like PHP?

But if you can't stand the gaff, consider providing a "RUST-alike" mode setting via environment variable to change the syntax.   There's precedent: the venerable APL is, by default, a one-origin language,  But it offers a [mode setting](https://en.wikipedia.org/wiki/APL_syntax_and_symbols#:~:text=X%E2%86%90%E2%8D%B312%0A%20%20%20%20%20%20%20%20X%0A1%202%203%204%205%206%207%208%209%2010%2011%2012%0A%20%20%20%20%20%20%20%20%E2%8E%95IO%0A1%0A%20%20%20%20%20%20%20%20X%5B1%5D%0A1)  that switches the whole language into 0-origin.  It has a unary \<iota\> operator which is basically a `..`.  By default \<iota\>10 is 1..=10, ten elements but also last value is 10.  Which of these does the 10 fundamentally denote?  When you run APL in 0 origin mode, \<iota\>10 generates 0..=9.  So A) you can implement a mode setting that changes fundamental things about the language and survive, and B) even back then, a significant minority of people were looking at range operators and wanting to interpret its argument as a count, even though the range concept, by definition, is generating a list of values.

**Comment by fdncred** [comment]
I'd be ok with nushell's ranges working the same way as rust's ranges. Not sure how others feel.

**Comment by WindSoilder** [comment]
I'd vote for this, left close and right open is normal behavior across many languages

**Comment by rgwood** [comment]
Thanks for the thoughtful issue with lots of context. @kubouch said this on Discord:

> We had a debate about it when we were implementing the ranges and the consensus was that they should be inclusive by default because they are more user-friendly to non-programmers. Maybe we can bring it up on a meeting again.

Personally I could go either way. With my programmer hat on, I think consistency with most other programming languages is desirable. But tbh I've always thought it's _weird_ that most languages are open on 1 side and closed on the other.

**Comment by bobhy** [comment]
Agree the programming world has adopted some strange conventions over time
and if you could go back in time you could right some egregious wrongs.But
the moving hand has writ, and having writ, moves on...

So here, you support `..` syntax for a range.  For the users who recognize
it, it's going to create a strong expectation about how it works. (Which I
belabored above).  You could justify doing something better, but it would
only be convincing to users who think they won't be going back and forth
between Nushell and the place they first learned about `..` (i.e, few).

But you could also support `range()` and claim the freedom to do it right.
Python is a counter-example but PHP offers support.   Nushell having 2
range capabilities with different defaults is just being "pragmatic", which
is a shell's highest calling.

Regards,
Bob

**Comment by jntrnr** [comment]
I personally like inclusive, but I can see the point that this can be confusion. Perhaps we could put this up in a survey question.

**Comment by bobhy** [comment]
Current users and team members have already demonstrated unusual mental
flexibility and, dare I say, tolerance for pain that won't be
representative of the potential future user population.  A survey should
ask them to put that new user hat on when they respond.  Vox populi, vox
dei!

**Comment by bobhy** [comment]
How about this as a compromise?  allow `..=N` as a way to explicitly specify the current behavior?  Doesn't break any existing scripts and, when I have my Rust head on, I can specify `..<N` or `..=N` and it won't hurt too much.
