### ISSUE TITLE
Dead link to documentation from error-message

### ISSUE THREAD

**Issue by senden9** [nushell/nushell#8167]
### Describe the bug

The links to error codes are dead. Here on the example of `unbalanced_delimiter`. The same happens to `nu::parser::unknown_flag` for example.

### How to reproduce

1. Generate `nu::parser::unbalanced_delimiter` error by executing `ls | get name}` in nu.
2. Click on the link in the error message. For me that is https://docs.rs/nu-parser/0.76.0/nu_parser/enum.ParseError.html#variant.Unbalanced
3. Observe the error "The requested version does not exist no such version for this crate " in you browser

### Expected behavior

See no link at all OR get a working link with some info to that specific error.

### Screenshots

![image](https://user-images.githubusercontent.com/905857/220643531-3e032513-dfe6-4c31-9c89-c49ce2c49fbc.png)
![image](https://user-images.githubusercontent.com/905857/220643615-7df891f1-7960-41c1-94ac-c4378f3890fb.png)

### Configuration

version | transpose key value | to md --pretty
| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.76.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | linux-x86_64                         |
| build_target       | x86_64-unknown-linux-gnu             |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)  |
| rust_channel       | stable-x86_64-unknown-linux-gnu      |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)  |
| pkg_version        | 0.76.0                               |
| build_time         | 2023-02-22 14:55:34 +01:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

**Comment by rgwood** [comment]
Good catch, thanks.

IMO the links haven't been very useful even when they did work. I think I would lean toward removing them.

**Comment by ryand67** [comment]
@rgwood I could look into getting this fixed or removing the link. Would it be for all errors that include links? Let me know, thanks!

**Comment by sholderbach** [comment]
OK super weird. I was having a brief moment of horror if we didn't upgrade/upload `nu-parser` to crates.io.
 But... crates.io/crates/nu-parser returns the current version `0.76` but docs.rs/nu-parser is still living on `0.75`. Don't know what is going on here.

In there some of the doc comments include some further resolution advice, but it exposes pure nu users to rust internals they don't necessarily need to see. Also if we use it that we can not put too much developer focussed info in the variant infos.

**Comment by sholderbach** [comment]
@ryand67 I think this concerns the errors that `derive(Diagnostic)` and thus implement fancy formatting through `miette`. I remember `ParseError` and `ShellError`. Don't know if there are more out there that have this link support.

**Comment by sholderbach** [comment]
I have started some work to cut down on some messiness of `ShellError` but I will probably hold of on going through with that until @stormasm has gone through the cratification process.

When that is done we might want to emit narkdown pages about the errors for our vuepress at github.com/nushell/nushell.github.io

**Comment by rgwood** [comment]
@sholderbach think it's worth attempting to remove the links for now? If so I'll assign this to @ryand67

**Comment by ryand67** [comment]
Perfect, I'll get right on this!

**Comment by rgwood** [comment]
Closed by #8193
