### ISSUE TITLE
Tilde expansion for variables

### ISSUE THREAD

**Issue by StevenDoesStuffs** [nushell/nushell#8170]
### Related problem

I'd like to source a file whose path is stored in a const, but I can't use the home directory in the path if I put it in a const variable. 

### Describe the solution you'd like

The only solution I can think of would be to expand tilde's when using variables as well as when typing the value literally. I.e the following should be the same:
```
let x = '~/file.nu'
source $x
```
```
source ~/file.nu
```

It should probably work for any commands that take a path and not just `source`.

**Comment by fdncred** [comment]
Thanks for your input.

We've been round and round about this. Sometimes it's good to expand the tilde and sometimes it isn't. We need to be able to do both but I'm not quite sure what that looks like.

**Comment by StevenDoesStuffs** [comment]
I'm sure you've already gotten plenty of ideas about tilde expansion, but I'll give one more in case this idea hasn't been brought up yet.

Expand `~` by default everywhere except in plain quoted strings (like in other shells), but expand `~` in interpolated quoted strings. Also, only expand `~` if it's the first character of a string and the second character (if exists) is `/` (this appears to be the behavior in bash). 

Unfortunately this doesn't actually solve my problem, as interpolated strings aren't parse-time constant, but maybe we could work around that by making it so that they're only not parse-time constant if they actually contain a `()` expansion somewhere. 

Examples:
```
let x = '~'         # ~
let x = '~/hello'   # ~/hello
let x = '~hello'    # ~hello

let x = $'~'        # /home/user
let x = $'~/hello'  # /home/user/hello
let x = $'~hello'   # ~hello

# not so sure about this one
let x = $"\~"       # ~
```

**Comment by StevenDoesStuffs** [comment]
If the maintainers can reach consensus on whether this is a good idea, I'd be happy to look into implementing it.

**Comment by WindSoilder** [comment]
Sorry, I'm afraid it's conflict with following issue:

https://github.com/nushell/nushell/issues/7673
https://github.com/nushell/nushell/issues/4205
https://github.com/nushell/nushell/issues/6993

We need to have a method to opt out of tilde expansion, I think variable is a good way to opt out

**Comment by kubouch** [comment]
Can you add example what didn't work for you? Do you mean
```
const p = '~/file.nu'
source $p
```
?

I'm not a fan of auto-expanding tildes in strings by default because it adds some implicit magic. I think all the `let x = ...` examples you posted shouldn't expand the tilde. Rather, the commands themselves should interpret what `~` means to them. We're admittedly not very consistent in it, but I think adding variable tilde auto-expansion would just add another layer of confusion.

Also, we might allow running some commands like `path expand` at parse time at some point.

**Comment by bobhy** [comment]
This is a job for `glob`.
Then you could do `source (glob ~/file.nu)` and that wouldn't be too verbose.

Sadly, today, it does not expand `~`, but I think users would not be too suprised to see it act on file system metacharacters other than wildcards.

```rust
〉glob ~/.bashrc
╭────────────╮
│ empty list │
╰────────────╯
```

**Comment by bobhy** [comment]
This might be a job for `glob`.
Then you could do `source ( glob ~/file.nu )`.  I don't think users would be too suprised to see glob acting on other file system metacharacters.

I was worried that Nushell wouldn't have evaluated the expression before invoking `source`, but I see it works for `ls`, at least.
```rust
〉ll ("~" + "//.bashrc")
╭───┬─────────────────────┬──────┬────────┬──────────────╮
│ # │        name         │ type │  size  │   modified   │
├───┼─────────────────────┼──────┼────────┼──────────────┤
│ 0 │ /home/bobhy/.bashrc │ file │ 4.5 KB │ 2 months ago │
╰───┴─────────────────────┴──────┴────────┴──────────────╯

```

**Comment by StevenDoesStuffs** [comment]
> We need to have a method to opt out of tilde expansion, I think variable is a good way to opt out. And we can always use path expand to expand tilde

As someone who's used to the convenience of `~` in shells like bash, zsh, or fish, `| path expand` seems pretty verbose for something very common. 
I think doing ~ expansion in interpolated strings only allows users to both opt in or opt out of ~ expansion in a non-verbose way. 
Plus, in the system I'm proposing, using a regular quoted string (or escaping the tilde in a double quoted interpolated string) still allows you to opt out of tilde expansion, and this behavior is consistent with other shells (like how '~' doesn't expand in bash). 

> Can you add example what didn't work for you? Do you mean
> ```
> const p = '~/file.nu'
> source $p
> ```

Yeah.

> I'm not a fan of auto-expanding tildes in strings by default because it adds some implicit magic. I think all the let x = ... examples you posted shouldn't expand the tilde. Rather, the commands themselves should interpret what ~ means to them. We're admittedly not very consistent in it, but I think adding variable tilde auto-expansion would just add another layer of confusion.

The problem with this is that you can't really get external commands to interpret ~, and having external and internal commands have different behavior in this way is really confusing and even more magical. Like this example I gave earlier exhibits some rather counterintuitive behavior: 
> `echo ~` doesn't expand, but `^echo ~` and `ls ~` do.

I think what's happening in this case is that `echo` takes a non-path argument, `^echo` is external and thus always needs `~` expansion since we don't know what type it wants, and `ls` takes a path argument so it does ~ expansion. 
However, this is all rather complicated to keep track of for an end user. Personally, I tried `echo ~` to see whether there was tilde expansion, and when it didn't expand I just assumed there wasn't. 

Even if doing `~` expansion is a little bit magical, people are familiar with it from other shells, so it's not that bad since the behavior is expected. Doing `~` expansion in interpolated quoted strings would also not be so magical if we highlighted it with a different color to indicate something is happening. 

> This might be a job for glob.
Then you could do source ( glob ~/file.nu ). I don't think users would be too suprised to see glob acting on other file system metacharacters.

This doesn't work since `( glob ~/file.nu )` isn't a parse time constant.

**Comment by StevenDoesStuffs** [comment]
Oh one more pathology:
```
let x = '~'
ls $x
```
will expand `~`, so currently variables aren't even a way of opting out of tilde expansion anyways.

**Comment by StevenDoesStuffs** [comment]
Apparently using ~ in a const var and then sourcing with that var now works.

**Comment by BatmanAoD** [comment]
@StevenDoesStuffs Sorry, I can't get this to work in `$nu.env-path`; what is the approach that you've found works?

I tried `$env.<var> = ~/<path>`, `$env.<var> = $HOME/<path>`, and `$env.<var> = $env.HOME/<path>`, but the only thing that actually worked was `$env.<var> = ('~/<path>' | path expand)`.

**Comment by StevenDoesStuffs** [comment]
Ah looking at original issue I believe I closed it a bit early. However, something like this does work: `$env.<var> = $'($env.HOME)/<path>'`

**Comment by BatmanAoD** [comment]
Thanks!
