### ISSUE TITLE
Error:'did you mean 'dfr as'?

### ISSUE THREAD

**Issue by bobhy** [nushell/nushell#8180]
### Describe the bug

I can't get this command to work, and can't figure out why.

### How to reproduce

```rust
〉$x | describe
dataframe
-------------------------------------------------- /home/bobhy/work --------------------------------------------------
〉$timestamps | describe
list<date>
-------------------------------------------------- /home/bobhy/work --------------------------------------------------
〉$x | dfr with-column  [ ($timestamps | dfr into-df | (dfr as 'c') ) ]
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #143:1:1]
 1 │ $x | dfr with-column  [ ($timestamps | dfr into-df | (dfr as 'c') ) ]
   ·                                                       ─┬─
   ·                                                        ╰── did you mean 'dfr as'?
   ╰────
  help: No such file or directory (os error 2)
```

This works:

```rust
〉$x | dfr with-column  ($timestamps | dfr into-df ) --name 'c'
╭─────┬────────────┬─────────────╮
│   # │     0      │      c      │
├─────┼────────────┼─────────────┤
│   0 │ 1676200007 │ 2 weeks ago │
│   1 │ 1676246548 │ 2 weeks ago │
│   2 │ 1676238548 │ 2 weeks ago │

```

### Expected behavior

I was basing my expression on this example from `help dfr with-column` (which *does* work!)

```rust
Examples:
  Adds a series to the dataframe
  > [[a b]; [1 2] [3 4]]
    | dfr into-df
    | dfr with-column ([5 6] | dfr into-df) --name c
```

### Configuration

〉version | transpose key value | to md --pretty
| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.76.1                                          |
| branch             | main                                            |
| commit_hash        | aba0fb0000d1a92585c76bbd2f3b387686c32201        |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)             |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu                 |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)             |
| pkg_version        | 0.76.1                                          |
| build_time         | 2023-02-22 23:07:04 -05:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by fdncred** [comment]
I'm just guessing but I think what's going on is that `with-column` wants a series or expression and for some reason the failing syntax above isn't generating that. If you look at `help with-column` you'll see that it wants to use `dfr col` which creates column expressions. So, I guess the $timestamps part isn't creating an expression or series and therefore failing.

But I'm just stabbing in the dark. I don't really know how it's supposed to work. If you know python, I bet you can find a polars example there of how it works and maybe port that backwards to nushell. Either way, calling "dfr as" and having help say, "did you mean dfr as" is friggin maddening, I know.

**Comment by bobhy** [comment]
Problem no longer repros in 0.79
