### ISSUE TITLE
Boolean environment variables

### ISSUE THREAD

**Issue by StevenDoesStuffs** [nushell/nushell#8187]
### Related problem

I'd like to store an environment variable such as `MOZ_ENABLE_WAYLAND`, which takes values of either 0 or 1, as a boolean. However, booleans don't get exported. 

### Describe the solution you'd like

Export boolean environment variables as either 0 or 1. This matches convention since typically environment variables which a program will interpret as a boolean will be represented as 0 or 1. 

For example:
```
let-env x = true
some-command
```
should be equivalent to
```
let-env x = 1
some-command
```

**Comment by kubouch** [comment]
You can set a manual conversion rule with ENV_CONVERSIONS environment variable: https://www.nushell.sh/book/environment.html#environment-variable-conversions.

We generally try to be conservative with implicit type conversions as they can lead to footgun situations.

**Comment by StevenDoesStuffs** [comment]
Honestly, after some thought, I realized that this is probably not a good idea since it's it's impossible to tell when an environment variable coming in should be interpreted as a boolean, so it's probably a bit more consistent to use integers for boolean environment variables explicitly.
