### ISSUE TITLE
Binaries without .exe not being executed on Windows

### ISSUE THREAD

**Issue by dgrr** [nushell/nushell#8197]
### Describe the bug

I am migrating from bash to nushell on Windows but commands like gunzip do not work. Mainly because the binary is `gunzip` not `gunzip.exe`. Other binaries in the same directory DO work, only if they end with `.exe`.

### How to reproduce

1. Install Git Bash
2. Install nushell
3. Try to execute gunzip inside nushell

### Expected behavior

I expect to run gunzip with no problem.

### Screenshots

![image](https://user-images.githubusercontent.com/10146748/221272450-7805cad7-7862-4692-8f2d-4ba0eb14c593.png)

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.76.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | windows-x86_64                       |
| build_target       | x86_64-pc-windows-msvc               |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)  |
| rust_channel       | stable-x86_64-pc-windows-msvc        |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)  |
| pkg_version        | 0.76.0                               |
| build_time         | 2023-02-24 18:23:14 +01:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

**Comment by rgwood** [comment]
Hi, I think this is by design. As I understand it, on Windows executables need a file extension that matches one in the `PATHEXT` environment variable.

I tested just now and running an executable without a file extension does not work in PowerShell or cmd.exe either.

**Comment by dgrr** [comment]
Umh... it does work with Git Bash... but ok

**Comment by rgwood** [comment]
Git Bash does a lot of Weird Stuff™️ on Windows and is generally designed more for compatibility with *nix Bash than as an idiomatic Windows shell.

**Comment by dgrr** [comment]
Oke, it's fine. Thanks anyways, nice project btw
