### ISSUE TITLE
Why differs the Windows version and the Linux version so much?

### ISSUE THREAD

**Issue by theuserbl** [nushell/nushell#8199]
### Question

The Linux-Version and the Windows-version of NuShell are differs a lot.
They have a different coloring. The "ls" command calling the file size in different names and showing the size in different numbers.
But why are they so different?

### Additional context and details

Windows Version of NuShell
<img width="865" alt="nu1" src="https://user-images.githubusercontent.com/8337032/221298892-f1329574-e5a6-4f15-b136-cedd26a14c36.PNG">

And the Linux Version of NuShell
<img width="866" alt="nu2" src="https://user-images.githubusercontent.com/8337032/221298922-df7e9b07-098c-4be0-86e2-27b76a5cd004.PNG">

**Comment by fdncred** [comment]
The coloring of the `ls` command is based on the `LS_COLORS` environment variable. If nushell does not find a `LS_COLORS` env var then it uses the default which is what you see in the top screenshot. The bottom screenshot is in WSL it appears and is using some bash level `LS_COLORS` default that is not nushell's. If nushell sees a previously defined `LS_COLORS` env var, it assumes you did this on purpose and it uses it.

**Comment by sholderbach** [comment]
Does this answer your question @theuserbl ?

**Comment by rgwood** [comment]
Closing as the question seems to be answered, can reopen if needed.
