### ISSUE TITLE
`register` does not accept true `const`ant arguments

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8208]
### Related problem

i've got the `nu_plugin_query` from `nushell` installed in my `$env.CARGO_HOME/bin/` which is `~/.local/share/cargo/bin/`

i can not define a constant with the full absolute path and `register` from the constant
```bash
>_ const foo = "/home/amtoine/.local/share/cargo/bin/nu_plugin_query"
>_ register $foo
Error: nu::parser::registered_file_not_found

  × File not found
   ╭─[entry #14:1:1]
 1 │ register $foo
   ·          ──┬─
   ·            ╰── File not found: $foo
   ╰────
  help: registered files need to be available before your script is run
``` 

> **Note**
> see the [original discussion](https://discord.com/channels/601130461678272522/615329862395101194/1078985174202724442) over on Discord

### Describe the solution you'd like

i would like
```bash
>_ const foo = "/home/amtoine/.local/share/cargo/bin/nu_plugin_query"
>_ register $foo
```
to register the plugin as just as `register ~/.local/share/cargo/bin/nu_plugin_query` already does :yum:

**Comment by fdncred** [comment]
After researching this and Kubouch's wisdom, it appears that `eval_constant` needs to be used in `parse_register()` in `parse_keywords.rs` similar to the way it's used in other parsing functions in that file.
