### ISSUE TITLE
Add how to remove Welcome Message in Welcome Message

### ISSUE THREAD

**Issue by gustavopmaia** [nushell/nushell#8216]
Add a link to the part of the documentation where shows how to remove the welcome message like:
```
     __  ,
 .--()°'.' Welcome to Nushell,
'|, . ,'   based on the nu language,
 !_-(_\    where all data is structured!

Please join our Discord community at https://discord.gg/NtAbbGn
Our GitHub repository is at https://github.com/nushell/nushell
Our Documentation is located at http://nushell.sh
Tweet us at @nu_shell
+ To remove this welcome message go to: <link to documentation>

It's been this long since Nushell's first commit:
3yr 9month 3wk 1day 5hr 58min 47sec 90ms 219µs 866ns

Startup Time: 28ms 22µs 793ns

**Comment by dmatos2012** [comment]
You can remove it in by doing `config.nu` and then changing `show_banner = false` from the default of true. 

In the PR you linked, you added a dead link. If you want to add that as part of the documentation, you need to submit that in the website [repo](https://github.com/nushell/nushell.github.io/). 

You can probably add how to if the devs agree somewhere on this page maybe https://www.nushell.sh/book/configuration.html#environment

**Comment by gustavopmaia** [comment]
> You can remove it in by doing `config.nu` and then changing `show_banner = false` from the default of true.
> 
> In the PR you linked, you added a dead link. If you want to add that as part of the documentation, you need to submit that in the website [repo](https://github.com/nushell/nushell.github.io/).
> 
> You can probably add how to if the devs agree somewhere on this page maybe https://www.nushell.sh/book/configuration.html#environment

It's a dead link actually, but I already did a PR in the website repo
