### ISSUE TITLE
Long file names don't list file permissions columns with `ls -l` 

### ISSUE THREAD

**Issue by adhadse** [nushell/nushell#8218]
### Describe the bug

So if you `ls` on a dir that has a file with very long name, it doesn't wrap the file name or truncate it's ending and silently drops columns like file permissions(mode), num links etc.

### How to reproduce

1. switch to 2/3 width of screen size for your terminal emulator (this is important, don't use fullscreen window/ultrawide monitors)
2. `cd` into a directory 
3. create a long file name `touch longggggggggggggggggggggggggggggggggggggggfilenammmmmmmmmmmmmmmmmmmmmme.txt`
4. run `ls -l`
5. `rm longggggggggggggggggggggggggggggggggggggggfilenammmmmmmmmmmmmmmmmmmmmme.txt`
6. run `ls -l`

### Expected behavior

Of course, we can't give a warning but either text wrapping or truncating the end should be the default, 
- so as to not give a false impression of something wrong with nushell that it can't display those columns, or these columns are by default shown when running `ls -l` on nushell, i.e., no mode/readonly/num links columns are displayed. 
- Which may lead to bugs issues that don't really exist.

By the way here is what `ls -l` does on BASH (noticing the wrapping of text for long file name):
![image](https://user-images.githubusercontent.com/56764399/221386649-483f68b5-6701-4d0c-8188-f0af36eb64e3.png)

### Screenshots

Before removing the file:
![image](https://user-images.githubusercontent.com/56764399/221386674-341e9cab-0221-463c-a321-a6b57acd7295.png)
After removing the file with long name:
![image](https://user-images.githubusercontent.com/56764399/221386687-b3e6830f-12d7-437a-96e7-5d22ae6780c1.png)

### Configuration

| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.76.0                                                     |
| branch             |                                                            |
| commit_hash        |                                                            |
| build_os           | linux-x86_64                                               |
| build_target       | x86_64-unknown-linux-gnu                                   |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07) (Fedora 1.67.1-1.fc37) |
| cargo_version      | cargo 1.67.1                                               |
| pkg_version        | 0.76.0                                                     |
| build_time         | 2023-02-21 00:00:00 +00:00                                 |
| build_rust_channel | release                                                    |
| features           | database, default, trash, which, zip                       |
| installed_plugins  |                                                            |

### Additional context

Not

**Comment by rgwood** [comment]
Thanks for the issue.

Both of your screenshots are missing some columns from the result table. You can tell from the `...` column at the right; it indicates that there are additional columns in the result set which could not be displayed.

Let us know if you have suggestions for how to address this / make that more clear.

**Comment by adhadse** [comment]
@rgwood I get the point. 
**Long file names don't really make a lot of sense to be shown for a single file while discarding useful information for other files in other columns.** 

- Additionally, **a user will be using `ls -l` for descriptive information about files which he/she might not have found by simply running `ls`, which should default to showing whole file name. We are not showing it.** 
- Plus tab completion of file names solve most of the other UX issue.

We can choose:
- a median length of strings to  truncate the long file name
- or dynamically adjust the length of strings to truncate, or wrap depending on the emulator width

while showing some essential columns that are by default shown by `ls` on bash.

**Comment by adhadse** [comment]
@rgwood Can we reopen this issue?

**Comment by rgwood** [comment]
I don't think this issue currently has a clear way forward.

Nushell's table rendering code curently doesn't know where the table came from; it can't distinguish between `ls` and `ls -l`. Even if it could distinguish between `ls` and `ls -l`, it's not clear which columns are important and which can be hidden when there isn't enough space.

This is a fundamental and difficult question that is much broader than `ls`: **what do we do when there isn't enough space to display every column?**

There is no 1 right answer to that question, but we're open to suggestions and PRs to improve Nushell's behaviour.

**Comment by Lindenk** [comment]
Why not just have a few more flags for `ls` that give an output similar to bash? In most cases columns like "target", "readonly', and "num_lines" aren't wanted, whereas user and group permissions are very common
