### ISSUE TITLE
correct way to start multiplexer on nushell start

### ISSUE THREAD

**Issue by JF002-Gelinas** [nushell/nushell#8226]
### Question

when running`pgrep zellij | is-empty` in the shell it returns as expected (true/false),
However when i try this check in the config file, on launch i get `can't convert list<string> to bool`

Whats the correct way to launch a multiplexer example zellij when nu starts?

**Comment by fdncred** [comment]
This error `can't convert list<string> to bool` indicates there are multiple items in a list. Typically you want to iterate items in a list like `your previous pipeline | each {|r| $r | is-empty}`. I don't run zellij so it's hard to tell what's going on.

**Comment by JF002-Gelinas** [comment]
> This error `can't convert list<string> to bool` indicates there are multiple items in a list. Typically you want to iterate items in a list like `your previous pipeline | each {|r| $r | is-empty}`. I don't run zellij so it's hard to tell what's going on.

its not so much about zellij, Im just trying to figure out how to launch a multiplexer on start of Nu, 

I was considering to check for the process, if the process isnt detected then start it, the above mentioned command works perfectly as long as it is not used within the config file.

**Comment by JF002-Gelinas** [comment]
Alright, the primary mistake i made is using [ ] instead of ( )
working config line is `if (pgrep zellij | is-empty) { zellij }` this allows zellij to start without going into infinite loop when nushell starts, whether this is the correct way.. idk
