### ISSUE TITLE
tilde "~" completion

### ISSUE THREAD

**Issue by Escapingbug** [nushell/nushell#823]
Right now "~" can correct expand to home, but it does not understand when doing completion. This means when we do things like:
```
> cd ~/<TAB>
```
We get nothing.

**Comment by jonathandturner** [comment]
@Escapingbug - what OS are you on? I wonder if the behavior is platform-dependent

**Comment by Escapingbug** [comment]
I'm using windows.

**Comment by jonathandturner** [comment]
@Escapingbug - plans to improve it, though I don't know if anyone is actively working on it. Right now we're using the rustyline file completion, but we may want to either improve theirs or add our own that can do more.

**Comment by Nate-Watts** [comment]
cd ~ isn't working for me either right now. I'm on OSX mojave version 10.14.6

**Comment by jonathandturner** [comment]
@Nate-Watts - can you confirm that other types of file completion work for you? @Escapingbug mentions that other types, like completing "../" don't seem to work either.

**Comment by Nate-Watts** [comment]
As far as I've noticed ../ works fine, tab completion works fine

**Comment by jonathandturner** [comment]
@Nate-Watts - also, what kind of tilde completion are you doing?  Something like "~<tab>" or "~/<tab>"?

**Comment by Nate-Watts** [comment]
```/Users/nwatts/.cargo> cd ~
error: Parse Error
- shell:1:3
1 | cd ~
  |    ^
/Users/nwatts/.cargo> cd ~/
error: Parse Error
- shell:1:3
1 | cd ~/
  |    ^^
/Users/nwatts/.cargo> ```

**Comment by jonathandturner** [comment]
Oh so it's even just completion, it's any support for tilde at all?

**Comment by jonathandturner** [comment]
@Nate-Watts - can you run the `version` command while in Nu and see what version you're running?

**Comment by Nate-Watts** [comment]
Yeah, unless I need to hard restart my machine for the cargo update to take place.
nushell 0.4.0

**Comment by jonathandturner** [comment]
It should "just work".  I'll try to dig into a bit to see what is happening on macOS that's making ~ not work.

**Comment by jonathandturner** [comment]
@Nate-Watts - I'm definitely confused. Tilde works for me for completions and as a path in macOS. I'm on Catalina (10.15)

Other thoughts are that it's a different tilde than it's expecting. That doesn't sound very likely but something to look into.

**Comment by Nate-Watts** [comment]
@jonathandturner Will do. I'll let you know.

**Comment by cormacrelf** [comment]
I get that parse error on 10.14.6, but only inside `tmux`. Executed without tmux, tilde works as expected, including completion.

**Comment by andrasio** [comment]
Related #853

**Comment by andrasio** [comment]
@cormacrelf `ls ~` fixed now. Thanks for reporting it. Closing this. If problem still persists feel free to reopen the issue.

Thank you again.
