### ISSUE TITLE
when running nu as default shell, can't run cargo and other external commands

### ISSUE THREAD

**Issue by ej-uses-git** [nushell/nushell#8230]
### Describe the bug

I installed nu using cargo onto my laptop (which is running Ubuntu). When I run a terminal that's using bash and then just run nu, everything works as expected. 

But when I set nu as my default shell (both on my regular terminal and on Terminator), tons of the commands I tried to run just ran into an `Error: nu::shell::external_command` - this happened when running `nu` and when running `cargo`. Other commands (bash, ls, which) work just fine.

Running `which nu` and `which cargo` does nothing and just leaves a blank line. It's also just happening when nu is loaded as the default shell - I ran bash from inside of nu and then re-ran nu from inside of bash and everything worked fine again...

### How to reproduce

1. Install nu
2. Set it as default shell for a Linux terminal emulator
3. Try running `cargo` 

### Expected behavior

I expected nu to be able to run commands the exact same way when loaded as the default shell.

### Screenshots

![image](https://user-images.githubusercontent.com/103414353/221438968-bbb5f607-4773-40e6-a47a-f9a69cf47d98.png)

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.76.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | linux-x86_64                         |
| build_target       | x86_64-unknown-linux-gnu             |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)  |
| rust_channel       | stable-x86_64-unknown-linux-gnu      |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)  |
| pkg_version        | 0.76.0                               |
| build_time         | 2023-02-26 22:57:53 +02:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

**Comment by mz2212** [comment]
I'm pretty sure this is because `nu` doesn't run the scripts like `.bashrc` and `.bash_profile`. 
It'd be worth editing your `$env.PATH` to include the paths that get set up with bash as described here: https://www.nushell.sh/book/configuration.html#path-configuration

**Comment by sholderbach** [comment]
I hope this answered your question about the setup as a primary shell.
Let us know if we can improve the documentation further in the future.
