### ISSUE TITLE
Custom command parameter ignored

### ISSUE THREAD

**Issue by 0rca** [nushell/nushell#8242]
### Describe the bug

In some cases, a parameter for custom command is ignored, e.g.
```nushell
def leak-env [env] {
  echo $env
}
```

Although one would expect that `leak-env foobar` displays "foobar", instead, it displays the entire environment!

This has security implications as well: if environment contains sensitive tokens, and somebody decides to name a parameter "env", their secrets will leak to the Internet, e.g.

```
def leak-secrets [env] {
  http post https://httpbin.org/post { env: $env }
}
```
WARNING! Do not actually try this unless you know what you are doing.

### How to reproduce

1. define a custom command:
```nushell
def leak-env [env] {
  echo $env
}
```

2. run `leak-env foobar`

3. observe the contents of your environment

### Expected behavior

I expected nu to display "foobar"

### Screenshots

<img width="253" alt="Screenshot of Alacritty (27-2-23, 14-50-40)" src="https://user-images.githubusercontent.com/103869/221494377-8f4e3bb4-5686-49c5-9e4d-1a67649fee2b.png">
<img width="365" alt="Screenshot of Alacritty (27-2-23, 14-51-10)" src="https://user-images.githubusercontent.com/103869/221494384-fa80444d-cd1a-462c-a3b8-f7163906a66b.png">

Expected:
<img width="179" alt="Screenshot of Alacritty (27-2-23, 14-51-41)" src="https://user-images.githubusercontent.com/103869/221494410-2a9967c7-8e4b-439d-a7ce-64b135a3c4fa.png">
<img width="166" alt="Screenshot of Alacritty (27-2-23, 14-52-18)" src="https://user-images.githubusercontent.com/103869/221494424-2f13f97e-c4b5-444d-a600-cb92401c5358.png">

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.76.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | macos-aarch64                        |
| build_target       | aarch64-apple-darwin                 |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)  |
| rust_channel       | stable-aarch64-apple-darwin          |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)  |
| pkg_version        | 0.76.0                               |
| build_time         | 2023-02-22 16:38:07 +08:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

**Comment by sholderbach** [comment]
We should probably either block you from shadowing the special variable `$env` (`$nu` etc. as well) or allow it. Do we need an escape hatch that you can not do that on the global scope?

**Comment by fdncred** [comment]
We've had issues like this before where someone was trying to re-use `$in`. A general purpose function to error on special variable assignment would be great.
