### ISSUE TITLE
cannot alias to the same command anymore 

### ISSUE THREAD

**Issue by MangoIV** [nushell/nushell#8246]
> **Note** 
> There is an easy workaround, namely using `old-alias` instead of `alias` 

### Describe the bug

since #8123 we cannot alias a command to the same name anymore; I think this is a common use-case so I thought I'd file it as a bug. 

### How to reproduce

try to create `alias nix = nix -Lv` 

### Expected behavior

every time I call `nix`, this gets substituted by `nix -Lv` 

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.76.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.67.0 (fc594f156 2023-01-24) (built from a source tarball) |
| cargo_version      | cargo 1.67.0                                                      |
| pkg_version        | 0.76.1                                                            |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
As a work-around, does it help to create a custom command?
```
def nix [] { nix -Lv }
```

**Comment by MangoIV** [comment]
no, it tells me "unknown flags `-Lv`"

**Comment by fdncred** [comment]
oh, it's redefining the same name. You might be able to get away with changing `nix -Lv` to `^$"nix -Lv"` or `^$"(nix -Lv)"` but I'm not sure.

**Comment by MangoIV** [comment]
btw; the error message is also (slightly) misleading: 

> Alias does not point to internal call

At least for me it wasn't immediately obvious before reading the actual code that this means that I used the same name twice...

(I don't think you should change the error message if this behavior will get fixed anyway but perhaps if it doesn't, this should be changed...)

**Comment by fdncred** [comment]
I kind of wonder what would happen if we had a `run_internal` command and then did something like 
```
def cp [...args] {
  run_internal cp --verbose $args
}
```

**Comment by amtoine** [comment]
> I kind of wonder what would happen if we had a `run_internal` command and then did something like
>
mm why not :thinking:

but the former `alias cmd = cmd --some-option-you-want-as-the-default` looks really clear and neat to me :open_mouth:

**Comment by amtoine** [comment]
> For now we can use old_alias though.
>
oh wow, how did you find that? :open_mouth:

**Comment by MangoIV** [comment]
See the mentioned PR :3

**Comment by amtoine** [comment]
> See the mentioned PR :3
>
jeez i searched _old_alias_...
really did not want to read anything yesterday, terrific :laughing: 

thanks :+1:

**Comment by bobhy** [comment]
It would be nice if the same extension syntax worked for external as well as internal commands, so, for example, I could do this:
```rust
alias ls = SomeMagic(ls -a)
alias grep = SomeMagic(grep -i)
```
It has always bugged me that (most) shells allow the old_alias syntax: how do they know to stop recursion?  Putting some explicit syntax in the expansion would be a good thing, I think.

I do think we need some solution here, otherwise Nushell will never be able to deprecate `old_alias`.

**Comment by Miuler** [comment]
My script in nushell has a error:


```scala
Error: nu::parser::unknown_state

  × Unknown state.
    ╭─[zoxide.nu:32:1]
 32 │   }
 33 │   cd $path
    ·   ─┬
    ·    ╰── Alias does not point to internal call.
 34 │ }
    ╰────
```


This error is in follow functions:
```python
# Jump to a directory using only keywords.
def-env __zoxide_z [...rest:string] {
  # `z -` does not work yet, see https://github.com/nushell/nushell/issues/4769
  let arg0 = ($rest | append '~').0
  let path = if (($rest | length) <= 1) and ($arg0 == '-' or ($arg0 | path expand | path type) == dir) {
    $arg0
  } else {
    (zoxide query --exclude $env.PWD -- $rest | str trim -r -c "\n")
  }
  cd $path
  #^^^^^^^
}

# Jump to a directory using interactive search.
def-env __zoxide_zi  [...rest:string] {
  cd $'(zoxide query -i -- $rest | str trim -r -c "\n")'
  #^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
}

...

alias cd = __zoxide_z
alias cdi = __zoxide_zi


```


```
nu version:      v0.77.0
zoxide version:  v0.9.0
```

https://github.com/ajeetdsouza/zoxide/issues/542
