### ISSUE TITLE
allow the use of `const` in a module

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8248]
### Related problem

i have some modules where i use preview strings for `fzf` that i want to define at the top level
> **Note**
> such a preview is just a string, containing some code, here `bash`, and that gets executed on each line of the `fzf` fuzzy finder to show some preview, e.g. if the entries are file paths, the preview might show the content of the files in a panel to the side

before the recent `alias` rewrite, i used to define them as `alias`es, e.g.
```bash
alias FZF_PREVIEW = "..."
```
and used as
```bash
fzf {options} --preview (FZF_LOG_PREVIEW)
```

now, with the new change, i can not do that anymore and am, afaik, forced to do that as
```bash
def FZF_PREVIEW [] {"
   ...
"}
```

### Describe the solution you'd like

i think it could be cool to just be able to define `const`ants in `nushell` modules

for instance,
```bash
const FZF_PREVIEW = "..."
```
and then
```bash
fzf {options} --preview $FZF_PREVIEW
```

**Comment by amtoine** [comment]
i also feel the following should work
```bash
>_ def foo [] { const bar = "this is foo::bar"; $bar }
>_ foo
Error: nu::shel
l::nushell_failed_spanned

  × Nushell failed: Missing Constant.
   ╭─[entry #5:1:1]
 1 │ def foo [] { const bar = "this is foo::bar"; $bar }
   ·              ──┬──
   ·                ╰── constant not added by the parser
   ╰────
```
> **Note**
> the error does not occur during parsetime on the `def` by during runtime :thinking:

**Comment by kubouch** [comment]
`const` in module can be added. The latter issue showcases https://github.com/nushell/nushell/issues/7810 which is an embarrassing mistake in the const implementation that haven't been fixed yet.

**Comment by kubouch** [comment]
One way it could work would be the following. Imagine a module 
```nushell
module spam {
    export const foo = 'foo'
}
```

Then:
* `use spam` would produce a `$spam` record with the module's constants, i.e., `$spam.foo` would have `'foo'`.
* `use spam foo` (`use spam *`, etc.) would directly create a `$foo` constant.

**Comment by amtoine** [comment]
@kubouch
this sounds great to me :ok_hand:
