### ISSUE TITLE
string (and other type) aliases are allowed but then not found

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8249]
### Describe the bug

when i define an `alias` with a `string`, `nushell` does not complain but later gives an error when running the `alias` :thinking: 

> **Note**
> this does not only work on `string`s, it appears to give the same behaviour on any variable that you could pass to `alias`

### How to reproduce

run
```bash
> alias FOO = "foo"
> FOO
```
get the error
```bash
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #3:1:1]
 1 │ FOO
   · ─┬─
   ·  ╰── executable was not found
   ╰────
  help: No such file or directory (os error 2)
```

### Expected behavior

i'd say either one of the following
- as before: allow the `alias` definition AND print the string when calling `FOO`
- new: give an error when trying to define an `alias` with something other than a real command

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.76.1                                   |
| branch             | main                                     |
| commit_hash        | ba5258d7165423b360edf1747d0ffec00052db13 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| pkg_version        | 0.76.1                                   |
| build_time         | 2023-02-27 19:24:27 +01:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  | gstat                                    |

**Comment by kubouch** [comment]
Yeah, these should not be allowed and throw an error because `"foo"` is not a command call. You need to use `print foo` or `echo foo`.

**Comment by amtoine** [comment]
> Yeah, these should not be allowed and throw an error because `"foo"` is not a command call. You need to use `print foo` or `echo foo`.
>
that makes total sense :+1: 
thanks :yum:
