### ISSUE TITLE
Config file in deeply unexpected location on MacOS

### ISSUE THREAD

**Issue by varon** [nushell/nushell#8256]
### Describe the bug

Why is the config file located in some totally unexpected and seemingly arbitrary location?

Literally every other unixy-tool places them in sane locations, and it took at least 10-15 minutes reading through documentation to find out information on this.

`/Users/varon/Library/Application Support/nushell/env.nu`

I've read there issues where you go on about Application Support Standards, but the _de facto_ standard is precisely to place configuration in ~/.config for shells and tools. This is what fish, zsh (the default shell even!) does.

Please can you resolve this for my own sanity and everyone else who wants to put their dotfiles into version control.

### How to reproduce

1. Install nutshell on MacOS
2. Try to configure it
3. Get confused as to why the config paths make no sense.

### Expected behavior

Config file should be located in `~/.config/nushell`.

### Configuration

N/A.

**Comment by fdncred** [comment]
The location comes from the [dirs-next](https://crates.io/crates/dirs-next) crate and are set to the operating system standard locations. Sorry if this is not an expected location for you. Thanks for your opinion.

I would also say that we would consider a pr that uses the XDG_CONFIG folder if it were specified by an environment variable.

**Comment by varon** [comment]
Yes, I'm familiar with the discussion surrounding this.

I'm arguing exactly the opposite. Your tool ignores standard unix convention, no matter what Apple arbitrarily decides on.

What will it take to get this change implemented ***as the default***?

**Comment by fdncred** [comment]
There are people who agree with you. I figure it'll take a PR to convince the core-team to change it.

**Comment by varon** [comment]
Thank you.

**Comment by utkarshgupta137** [comment]
Can we reopen this or #893?
Also, is anyone working on this, otherwise I'd like to create a fix for this.

**Comment by fdncred** [comment]
> Can we reopen this or #893? Also, is anyone working on this, otherwise I'd like to create a fix for this.

Feel free to submit a PR or better yet, discuss it on Discord first.

**Comment by despiegk** [comment]
we should indeed do this, I don't get it, this seems so obvious why do we need so much words over it?

**Comment by fdncred** [comment]
Because people are passionate about their opinions and aren't as worried about supporting other platforms other than what their own system is on.

Each OS we support has its pre-defined config directory system, which we try to comply with. https://docs.rs/dirs-next/2.0.0/dirs_next/fn.config_dir.html

We may change this someday and ignore what the OS thinks, but we haven't done that yet.
