### ISSUE TITLE
Time cannot be added as record value without putting it into parenthesis

### ISSUE THREAD

**Issue by Hofer-Julian** [nushell/nushell#8257]
### Describe the bug

Time cannot be added as record value without putting it into parenthesis.

### How to reproduce

This gives a closure
```
nu ❯ {x: 2021-10-22T14:30:00, y: "b"}
<Closure 81>
```

### Expected behavior

If I put the time into parenthesis, it works as expected:

```
nu ❯ {x: (2021-10-22T14:30:00), y: "b"}
╭───┬────────────╮
│ x │ a year ago │
│ y │ b          │
╰───┴────────────╯
```

Dates without time work too:

```
nu ❯ {x: 2021-10-22, y: b}
╭───┬────────────╮
│ x │ a year ago │
│ y │ b          │
╰───┴────────────╯
```

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.75.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07) (built from a source tarball) |
| cargo_version      | cargo 1.67.0                                                      |
| pkg_version        | 0.75.0                                                            |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | database, default, trash, which, zip                              |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
I wonder why that is?  It looks like the datetime isn't being parsed as datetime. Oh, it's the colons that are throwing it off.

Seems like we should fix this.

**Comment by ryand67** [comment]
I'll take this one!

**Comment by fdncred** [comment]
Thanks @ryand67. It's yours. good luck!

**Comment by sholderbach** [comment]
This currently breaks NUON roundtripping of datetime values in records: 

Report by @KAAtheWiseGit :
It is currently impossible to store datetime in Nuon.  The `to nuon` command incorrectly serializes the format:

```Nushell
~> let datetime = 2023-10-10T16:00:00
~> {val: $datetime} | to nuon
{val: 2023-10-10T16:00:00+00:00}
~> {val: $datetime} | to nuon | from nuon 
Error:   × error when parsing nuon text
   ╭─[entry #11:1:1]
 1 │ {val: $datetime} | to nuon | from nuon 
   ·                              ────┬────
   ·                                  ╰── could not parse nuon text
   ╰────

Error:   × error when parsing
```

**Comment by fdncred** [comment]
8601 time and timezone can be stored without colons https://en.wikipedia.org/wiki/ISO_8601#Times, so one solution maybe we should support that in the parser and allow nuon to use it.

**Comment by cyradotpink** [comment]
Hi! I came across this bug today. @ryand67, how far did you get with this? I drafted up a fix that I'm not sure is perfect (as I'm not too experienced with parsers and with nushell's codebase), but I'd be happy to open a draft PR with it to move this forward, unless you'd like to pick it back up :)

**Comment by fdncred** [comment]
go for it @cyradotpink
