### ISSUE TITLE
Type signatures of `math floor` and `math ceil` are wrong.

### ISSUE THREAD

**Issue by baehyunsol** [nushell/nushell#8258]
### Describe the bug

Type signatures of `math floor` and `math ceil` are wrong. Below are the type signatures, according to the help message.

```
<number> | math floor -> <int>
<number> | math ceil -> <int>
```

But if I actually run the commands and check the types of the results, they're wrong!

### How to reproduce

run below

```
[
  (3.14 | math floor | describe),
  (3 | math floor | describe),
  (3.14 | math ceil | describe),
  (3 | math ceil | describe),
]
```

### Expected behavior

The result should be like below

```
╭───┬───────╮
│ 0 │ int   │
│ 1 │ int   │
│ 2 │ int   │
│ 3 │ int   │
╰───┴───────╯
```

### Screenshots

Below is the actual result.

```
╭───┬───────╮
│ 0 │ float │
│ 1 │ int   │
│ 2 │ float │
│ 3 │ int   │
╰───┴───────╯
```

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.76.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | linux-x86_64                         |
| build_target       | x86_64-unknown-linux-gnu             |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)  |
| rust_channel       | stable-x86_64-unknown-linux-gnu      |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)  |
| pkg_version        | 0.76.0                               |
| build_time         | 2023-02-22 16:29:45 +09:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

**Comment by baehyunsol** [comment]
Implementations: [ceil](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/math/ceil.rs#L61), [floor](https://github.com/nushell/nushell/blob/main/crates/nu-command/src/math/floor.rs#L61)

I guess we should make them return `Value::Int`, rather than `Value::Float`.

**Comment by ryand67** [comment]
I can take a look at this :)

**Comment by sholderbach** [comment]
From a sanity perspective and what we advertised in the type signature I would agree on integer output, although it is not unreasonable to run into situations with floats where they would overflow an int on the operation (although probably a much less common use case in the nu context)

**Comment by ryand67** [comment]
Would it make any sense to split it into two commands? Like ‘math ceil’ and ‘math ceil-coerce’ or something? Or is that too overkill?

**Comment by sholderbach** [comment]
Sounds a bit much to me at least at the moment as no one has yet complained in the direction of wanting a float output :P . 

The alternative of adding a flag would be frowned upon as we try to avoid affecting the type signature through flags as much as possible. `Signature.input_output_types()` can not represent that accurately.

**Comment by ryand67** [comment]
Yeah I was thinking it was overkill but figured I’d offer it up! I’ll get this changed when I get home!

**Comment by sholderbach** [comment]
Sounds good! Thanks for being so proactive!
