### ISSUE TITLE
built-in inc command is missing in my Nushell installation

### ISSUE THREAD

**Issue by PhilVince96** [nushell/nushell#8259]
### Describe the bug

As I tried some commands from the [Cookbook](https://www.nushell.sh/cookbook/http.html#fetch-from-multiple-urls) (last one here) I got the error message that the inc executable was not found. After that I looked up the commands list with help command and inc is missing.

Prompt & Error Message:
open urls.json | get urls | first | http get $in | upsert id {|item| $item.id | inc} | to json | http post https://jsonplaceholder.typicode.com/posts $in

Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #58:1:1]
 1 │ open urls.json | get urls | first | http get $in | upsert id {|item| $item.id | inc} | to json | http post https://jsonplaceholder.typicode.com/posts $in
   ·                                                                                 ─┬─
   ·                                                                                  ╰── executable was not found
   ╰────
  help: No such file or directory (os error 2)

### How to reproduce

call inc command

### Expected behavior

I expected Nushell to have the inc command built-in.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.76.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07) (built from a source tarball) |
| cargo_version      | cargo 1.67.0 (8ecd4f20a 2023-01-10)                               |
| pkg_version        | 0.76.0                                                            |
| build_time         | 2023-02-21 20:46:29 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | database, default, trash, which, zip                              |
| installed_plugins  |                                                                   |

**Comment by dmatos2012** [comment]
Hi! The `inc command` is a plugin, and does not come by default when installing nushell. Some of the curated plugins are in this repo https://github.com/nushell/awesome-nu.  The instructions are there on that repo itself or on the docs https://www.nushell.sh/book/plugins.html

We will make sure to correct the documentation to mention that its  a plugin or remove it, but that will be up to the devs.

**Comment by huguesalary** [comment]
I ran into this issue as well. The fact that `inc` is a plugin would benefit from being documented. 

In the nu documentation https://www.nushell.sh/commands/docs/inc.html it looks as though it is a command available by default

**Comment by davidwalschots** [comment]
@dmatos2012 @fdncred  I'd like to note that I also ran into this issue. The [Nu Fundamentals documentation on Pipelines](https://www.nushell.sh/book/pipelines.html) uses it in one of its examples and links to the command's documentation. Neither the pipelines documentation nor the `inc` command documentation notes a plugin is required.

**Comment by fdncred** [comment]
Thanks. We accept PRs to help make our docs more clear.
