### ISSUE TITLE
equivalent to `CDPATH` environment variable?

### ISSUE THREAD

**Issue by benreyn** [nushell/nushell#826]
Does Nu have an equivalent environment variable to a typical bash shell's `CDPATH` variable? So many things about Nu just worked out of the box from my bashrc I was surprised when my `CDPATH`  did not.

**Comment by andrasio** [comment]
@benreyn Sorry about that! We are working on environment variables at the moment. You can explore what we currently provide by running the `env` command. 

`config` command is also interesting to look at.

**Comment by trajano** [comment]
There is https://github.com/nushell/nu_scripts/blob/main/sourced/filesystem/cdpath.nu 
but that uses `c` rather than `cd`

I think for this to work correctly there needs a way to force nu to use the builtin cd  like `builtin cd` in bash
