### ISSUE TITLE
CPU usage is always reported as 0 in sys

### ISSUE THREAD

**Issue by AntoniosBarotsis** [nushell/nushell#8264]
### Describe the bug

CPU usage is always reported as 0 on windows.

### How to reproduce

Run 

```nu
sys | get cpu | get cpu_usage
```

### Expected behavior

The output should reflect the actual CPU usage (as reported by task manager for instance).

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.76.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | windows-x86_64                                  |
| build_target       | x86_64-pc-windows-msvc                          |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)             |
| rust_channel       | stable-x86_64-pc-windows-msvc                   |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)             |
| pkg_version        | 0.76.0                                          |
| build_time         | 2023-02-24 17:17:11 +01:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  | gstat                                           |

**Comment by AntoniosBarotsis** [comment]
The relevant code seems to be [here](https://github.com/nushell/nushell/blob/76292ef10c6eb4c3eaaba7cf1ee39348580bc55f/crates/nu-system/src/windows.rs#L1033-L1040), I'm wondering if there's too many zeroes [here](https://github.com/nushell/nushell/blob/76292ef10c6eb4c3eaaba7cf1ee39348580bc55f/crates/nu-system/src/windows.rs#L1037)? You seem to be dividing by 1 less zero on [Mac](https://github.com/nushell/nushell/blob/9d0e52b94d1e9df079308e7c9ea32cd76b7ac0ea/crates/nu-system/src/macos.rs#L378) for instance (that might be completely unrelated, my brain is foggy at the moment, just the first thing I noticed).

**Comment by AntoniosBarotsis** [comment]
Edit: People are apparently also experiencing this on Linux so my previous reply is most likely irrelevant :)

**Comment by fdncred** [comment]
I'm betting this is because our underlying crate that gets cpu usage has changed. Need to see if there's a fix upstream first.

**Comment by fdncred** [comment]
For testing I did this and started a `cargo build` of nushell.
```
mut counter = 0
while $counter < 25 {
 sys | get cpu | where cpu_usage > 0.00
 $counter += 1
 sleep 1sec
}
```
All it did was print 25 [empty list]'s

**Comment by rgwood** [comment]
It looks like we're using the `sysinfo` crate incorrectly. From [the `refresh_cpu()` docs](https://docs.rs/sysinfo/latest/sysinfo/trait.SystemExt.html#method.refresh_cpu):

> Please note that the result will very likely be inaccurate at the first call. You need to call this method at least twice (with a bit of time between each call, like 200 ms, take a look at [SystemExt::MINIMUM_CPU_UPDATE_INTERVAL](https://docs.rs/sysinfo/latest/sysinfo/trait.SystemExt.html#associatedconstant.MINIMUM_CPU_UPDATE_INTERVAL) for more information) to get accurate value as it uses previous results to compute the next value.

We only call it once: https://github.com/nushell/nushell/blob/27d798270b2051e850f1b2ee3fa118d9992b8ea4/crates/nu-command/src/system/sys.rs#L201-L202

**Comment by fdncred** [comment]
I still have cpu_usage always 0 in Windows https://github.com/nushell/nushell/pull/8275#issuecomment-1450153887

**Comment by rgwood** [comment]
I've got a PR ready to fix this, but... the `cpu_usage` numbers still look pretty weird on my machine, there's something going on with our `sysinfo` dependency: https://github.com/GuillaumeGomez/sysinfo/issues/945

🤞 that that can be fixed upstream
