### ISSUE TITLE
Consider restrict closure syntax to be something like `{ ||`

### ISSUE THREAD

**Issue by WindSoilder** [nushell/nushell#8273]
### Related problem

We have the concept about closure and block, but currently closure syntax can be the same to block, which leads to confusing behavior.

Like: `{ a a }`, should it be a closure or block?

### Describe the solution you'd like

I'd like to restrict closure syntax to be something like `{|| 3 * 3}`, or `{|arg| arg * arg}`

### Additional context and details

Actually I think it's relative to issue: https://github.com/nushell/nushell/issues/7575

I have a easy solution for it(check https://github.com/nushell/nushell/pull/8274), but it required closure to have more unique syntax.. or else the ut is broken

**Comment by WindSoilder** [comment]
It breaks the following `mut` usage:
```
stderr: Error: nu::parser::expected_keyword

  × Capture of mutable variable.
   ╭─[/tmp/.tmpaaj31c:1:1]
 1 │ mut x = 100; if 2 > 3 { $x = 200 } else { $x = 300 }; $x 
   ·                                           ─┬
   ·                                            ╰── capture of mutable variable
   ╰────
```

Because `{ $x = 300 }` is parsed as a closure, and it doesn't allowed to capture mutable variable, a solution would be restrict closure syntax to not mess up with block syntax

**Comment by fdncred** [comment]
Ya, I'd support that clarification too.
