### ISSUE TITLE
Redirect `stderr`

### ISSUE THREAD

**Issue by MangoIV** [nushell/nushell#8277]
### Related problem

At the moment it is not possible to redirect `stderr` with a pipe, similar to `bash`'s `|&`

### Describe the solution you'd like

I would like to be able to have something like `|&` in nushell, perhaps we can even use the same thing as `bash` does to make it intuitive. 

### Describe alternatives you've considered

There are no real alternatives besides using a different shell

### Additional context and details

[The Bash reference manual, see chapter `3.2.3 - Pipelines`](https://www.gnu.org/software/bash/manual/bash.html)

**Comment by fdncred** [comment]
@MangoIV in case you haven't seen this I'm posting it here for you https://github.com/nushell/nushell/issues/8539#issuecomment-1485823390

**Comment by MangoIV** [comment]
Thank you, I will try to look into it later.
