### ISSUE TITLE
Compiling nu 0.76 triggers Bitdefender

### ISSUE THREAD

**Issue by ryan-preble** [nushell/nushell#8283]
While attempting to compile nu 0.76.0 with dataframes included, my antivirus (Bitdefender on Win11 22H2) started flagging intermediate files as being infected with known viruses. Messages are as follows:
`The file nushell-main\target\release\build\memchr-b556aaf1005dd2d2\build-script-build.exe has been detected as infected with Gen:Variant.Cerbu.162812 and Bitdefender could not clean this item. A device restart is required to finalize the cleaning process.`

`The file nushell-main\target\release\build\crossbeam-utils-2c46f89771c80ef0\build_script_build-2c46f89771c80ef0.exe is infected with Gen:Variant.Cerbu.162812 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.`

`The file nushell-main\target\release\build\windows_x86_64_msvc-5bd9e270ad5b31f6\build-script-build.exe has been detected as infected with Gen:Variant.Cerbu.162812 and Bitdefender could not clean this item. A device restart is required to finalize the cleaning process.`

`The file nushell-main\target\release\build\windows_x86_64_msvc-5bd9e270ad5b31f6\build-script-build.exe is infected with Gen:Variant.Cerbu.162812 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.`

`The file nushell-main\target\release\build\memchr-b556aaf1005dd2d2\build-script-build.exe is infected with Gen:Variant.Cerbu.162812 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.`

`The file nushell-main\target\release\build\libm-50fff0b2315cbc2c\build-script-build.exe is infected with Gen:Variant.Cerbu.162812 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean`

I suspect the issue is with Bitdefender, but I wanted to leave this here in case anyone knew what to do about it.

**Comment by rgwood** [comment]
Thanks for the heads up. Looks like a false positive with some of our dependencies, probably similar to this: https://github.com/BurntSushi/memchr/issues/113

I don't think there's much we can do here, you'll probably want to tweak your Bitdefender settings.
