### ISSUE TITLE
how can I load command from text file and then execute it

### ISSUE THREAD

**Issue by lafirest** [nushell/nushell#8287]
### Question

I like to put frequency commands into a text file, now I hope that I can find a command by index or name and then execute it, like this `cat -p history|split row  "\n"|get 4|eval`. 
But there is no `eval` in nushell, I also tried the `source` but it will refuse the dynamic temp file name, so I have to use another shell to execute this command.

**Comment by kubouch** [comment]
This is not possible currently, we don't have eval. We might or might not be able to support some form of limited eval in the future, it's not completely ruled out but for now it is not possible.
