### ISSUE TITLE
Plugin tests are running slow lately

### ISSUE THREAD

**Issue by rgwood** [nushell/nushell#8291]
In the past month or so, I've noticed that the plugin tests are really slow on Linux when running `cargo nextest run --workspace`:

![image](https://user-images.githubusercontent.com/26268125/222527594-45780275-6a52-490d-8dbf-a9fb6a3ee8f9.png)

![image](https://user-images.githubusercontent.com/26268125/222527672-22ffb7e1-6c5d-47b7-b22f-559eb27997d1.png)

The variance is quite high; I've seen the plugin tests take anywhere from 1s to 70s. If I run `cargo nextest run --workspace` twice in a row, the second time is much faster. This wasn't happening a few months ago, so I suspect a recent change is to blame.

FWIW this is happening on a 24-logical-core machine. Given that all the plugin tests take roughly the same amount of time, I'm guessing parallel tests are running into some kind of resource contention.

**Comment by fdncred** [comment]
Just shooting in the dark, have you tried running the plugin encoding benchmarks? I wonder if they're faster / slower / the same as previous. It's probably unrelated but your post made me think of those benchmarks. I'm not sure what the original values were but I think @WindSoilder posted results in the original PR when comparing json to msgpack.

**Comment by rgwood** [comment]
I have not tried the plugin encoding benchmarks. Don't think those are related.

I dug into this a little today, and it seems like the time is mostly being spent in `ensure_binary_present()`: https://github.com/nushell/nushell/blob/f6ca62384e6140c32894ba94a3d703c7b08ae67f/crates/nu-test-support/src/commands.rs#L6

That function is a little crazy! It's invoking `cargo build` for every plugin test, which is not likely to play nicely with tests running in parallel. I suspect this might also be the cause of our intermittent macOS CI failures.

**Comment by fdncred** [comment]
My only concern with the benchmarks was that if msgpack and json both slowed down then the plugins themselves would slow down. But it sounds like you may have figured out where the problem was. Thanks!

**Comment by rgwood** [comment]
https://github.com/nushell/nushell/pull/8333 should improve things a bit. But I think there's not much we can do about this without a big overhaul of the plugin tests; running `cargo build` as part of the tests is always going to be a little slow.
