### ISSUE TITLE
membership test for records

### ISSUE THREAD

**Issue by baehyunsol** [nushell/nushell#8294]
### Question

How do I do a membership test for record types?

- For example: `{a: b, c: d} | contains c` is `true`.

It seems like `in` and `not-in` work on lists and tables, but not on records.

### Additional context and details

If there isn't one, I want the shell to have one.

**Comment by fdncred** [comment]
I think this works doesn't it?
```
'c' in {a: b, c: d} 
```

**Comment by baehyunsol** [comment]
Oh it works. Thanks!
