### ISSUE TITLE
are `modules` and `aliases` duplicated between `help` and `$nu.scope`?

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8300]
### Question

i have
```bash
>_ (help commands) == $nu.scope.commands
false
```
but, with modules and aliases, `help` and `$nu.scope` look duplicate :thinking: 
```bash
>_ (help aliases) == $nu.scope.aliases
true
>_ (help modules) == $nu.scope.modules
true
```

**is that a feature?**
i don't mind having two ways to do things, just wanted to point that out in case that is too redundant to keep both :yum: 

### Additional context and details

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.76.1                                   |
| branch             | main                                     |
| commit_hash        | e01eb42e74f6a5cf7cc0408a2688a6741f2597e2 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| pkg_version        | 0.76.1                                   |
| build_time         | 2023-03-03 13:11:03 +01:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by kubouch** [comment]
Yes, currently the output is the same. The `$nu.scope...` can contain more detailed info in a form of structured data, `help xxx` is supposed to be simpler and more user facing. For aliases and modules, I made them the same to start with, but if there is a need to diverge them, we can.

**Comment by amtoine** [comment]
> Yes, currently the output is the same. The `$nu.scope...` can contain more detailed info in a form of structured data, `help xxx` is supposed to be simpler and more user facing. For aliases and modules, I made them the same to start with, but if there is a need to diverge them, we can.
>
thanks, that is fine :yum:
