### ISSUE TITLE
aliases should be listed in `help alias` or `$nu.scope.aliases` and externals in `help externals`

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8301]
EDIT / TL;DR: we've identified two points here
- [x] `help alias` should list aliases as before
  - #8372 
- [ ] `help externals` should list externals
  - #8403 

### Describe the bug

i have a bunch of aliases in my `nushell` config, but none of them appear in `help aliases`

> **Note**
> in all that follows, `help aliases` can be replaced by `$nu.scope.aliases` and the same behaviour occurs

to be more precise, only the ones defined with `old-alias` appear

```bash
>_ help aliases
╭───┬──────┬──────────────┬─────────────────╮
│ # │ name │  expansion   │      usage      │
├───┼──────┼──────────────┼─────────────────┤
│ 0 │ cp   │ cp --verbose │ be more verbose │
│ 1 │ mv   │ mv --verbose │                 │
│ 2 │ rm   │ rm --verbose │                 │
│ 3 │ sl   │ sl -aw -20   │                 │
╰───┴──────┴──────────────┴─────────────────╯
```

> **Note**
> the aliases: https://github.com/amtoine/goatfiles-dotfiles/blob/bleeding/.config/nushell/lib/personal/aliases.nu

### How to reproduce

1. `help aliases | where name == bar`
```bash
╭────────────╮
│ empty list │
╰────────────╯
```
2. `alias bar = echo "this is bar"`
3. `bar`
```bash
this is bar
```
4. `help aliases | where name == bar`
```bash
╭────────────╮
│ empty list │
╰────────────╯
```
and with the `old-alias`
5. `old-alias bar = echo "this is bar"`
6. `bar`
```bash
this is bar
```
7. `help aliases | where name =~ bar`
```bash
╭───┬──────┬────────────────────┬───────╮
│ # │ name │     expansion      │ usage │
├───┼──────┼────────────────────┼───────┤
│ 0 │ bar  │ echo "this is bar" │       │
╰───┴──────┴────────────────────┴───────╯
```

### Expected behavior

i expected to see
```bash
>_ help aliases | where name == bar
╭───┬──────┬────────────────────┬───────╮
│ # │ name │     expansion      │ usage │
├───┼──────┼────────────────────┼───────┤
│ 0 │ bar  │ echo "this is bar" │       │
╰───┴──────┴────────────────────┴───────╯
```
after a single
```bash
alias bar = echo "this is bar"
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.76.1                                   |
| branch             | main                                     |
| commit_hash        | a7b5bd18ba6a068893f5aa8be68883ee0a3d9342 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| pkg_version        | 0.76.1                                   |
| build_time         | 2023-03-03 19:26:08 +01:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  | gstat                                    |

**Comment by kubouch** [comment]
Yes, the new aliases are basically commands, so they're listed under commands.

We could change `help aliases` to filter through commands to list only aliases. Similarly, we might want to add `help externals` as well since the externals are implemented in a similar way as aliases.

**Comment by amtoine** [comment]
> Yes, the new aliases are basically commands, so they're listed under commands.
> 
oooh i understand!!
```bash
help commands | where command_type == alias
```
is the command!

that is a bit confusing :thinking: 

> We could change `help aliases` to filter through commands to list only aliases. Similarly, we might want to add `help externals` as well since the externals are implemented in a similar way as aliases.
>
i think that would be very great to have that back :relieved: 

something like
```bash
def "help aliases" [] {
    help commands
    | where command_type == alias
    | select name usage
}
```
and
```bash
def "help externals" [] {
    help commands
    | where command_type == external
    | reject command_type
}
```

**Comment by kubouch** [comment]
The general `help aliases/commands/externals` would probably be quite similar, it's mostly the individual help messages (e.g., `help aliases ll`) that would look different because the three categories each do very different things. The alias help could list the expansion as before, for example. The help for externals could reflect custom completions in more detail since that's what the known externals are often used for.

**Comment by amtoine** [comment]
> The general `help aliases/commands/externals` would probably be quite similar, it's mostly the individual help messages (e.g., `help aliases ll`) that would look different because the three categories each do very different things. The alias help could list the expansion as before, for example. The help for externals could reflect custom completions in more detail since that's what the known externals are often used for.
>
yup these would completely solve this issue! :yum: 

**should i change the title of the issue to better reflect what the true goals are?**

**Comment by kubouch** [comment]
Yeah, you can

**Comment by amtoine** [comment]
> I [reworked](https://github.com/nushell/nushell/compare/main...klementievdmitry:nushell:main) the `help alias` command a bit. It now collects old aliases and commands (if command_type == alias). Can I do a pull request or not and why?
>
well, it looks the exact same as before!
i'm not in the core team, but i'd say you definitely should open a PR for this :yum: 

there might be some rewrites to do and defails to fix, but that looks promising to me![

**Comment by kubouch** [comment]
Aliases done in https://github.com/nushell/nushell/pull/8372

**Comment by amtoine** [comment]
> Aliases done in #8372
>
nice :yum: 

i've added a TODO at the top of this issue to keep track of that :wink:

**Comment by amtoine** [comment]
thanks :muscle:
