### ISSUE TITLE
install on alpine with docker 

### ISSUE THREAD

**Issue by cirolosapio** [nushell/nushell#8307]
### Question

what is the best way to install nushell on alpine linux with docker?

### Additional context and details

i see alpine packages https://repology.org/project/nushell/versions
but apk add nushell fails with `unable to select packages`

**Comment by fdncred** [comment]
Doesn't our docker file do that? https://github.com/nushell/nushell/blob/main/docker/Dockerfile

**Comment by cirolosapio** [comment]
maybe we can add this dockerfile to the docs
however my question is why on alpine apk is unable to select the package

**Comment by cirolosapio** [comment]
i've found a solution `apk --no-cache add nushell --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing`
according the [alpine docs](https://wiki.alpinelinux.org/wiki/Repositories) the testing repositories are not enableds by default

**Comment by AfterThunk** [comment]
Just figured I'd throw this here. I also hit issues when trying to run the Dockerifle as is in github.
I was able to get it to work by making a few modifications:

```
# Git: git version 2.30.2
# /etc/os-release: Alpine Linux v3.16
# Kernel: Linux ca3abedc4fb1 5.17.15-76051715-generic #202206141358~1655919116~22.04~1db9e34 SMP PREEMPT Wed Jun 22 19 x86_64 Linux
# Build cmd: docker build --no-cache . -t nushell-latest
# Other tags: nushell/alpine-nu:latest, nushell
FROM alpine

LABEL maintainer=nushell

RUN echo '/usr/bin/nu' >> /etc/shells
RUN adduser -D -s /usr/bin/nu nushell
RUN mkdir -p /home/nushell/.config/nushell/
RUN wget -q https://raw.githubusercontent.com/nushell/nushell/main/crates/nu-utils/src/sample_config/default_config.nu -O /home/nushell/.config/nushell/config.nu
RUN wget -q https://raw.githubusercontent.com/nushell/nushell/main/crates/nu-utils/src/sample_config/default_env.nu -O /home/nushell/.config/nushell/env.nu
RUN cd /tmp
RUN wget -qO - https://api.github.com/repos/nushell/nushell/releases/latest \
    |grep browser_download_url \
    |grep musl.tar.gz \
    |cut -f4 -d '"' \
    |xargs -I{} wget {}
		
RUN tar -xzf nu*-musl.tar.gz
RUN cp nu*-musl/* /usr/bin/
RUN chmod +x /usr/bin/nu
RUN chown -R nushell:nushell /home/nushell/.config/nushell
RUN ls /usr/bin/nu_plugin* \
    |xargs -I{} su -c 'register {}' nushell

RUN rm -rf /tmp/*

USER nushell
```

First, I chopped everything into different RUN commands to make it figure out where things were broken.

The call to `RUN wget -qO - https://api.github.com/repos/nushell/nushell/releases/latest` actually returns 2 different entries for musl: musl and musl-full. This can cause the subsequent extraction to fail.

Next, the Dockerfile was doing a cd into the extracted directory so it could copy the binaries. This wasn't necessary, you can just do a cp directly from the tmp directory. You end up copying a few extra things, but at least it works.

**Comment by fdncred** [comment]
Thanks @AfterThunk. We recently added the `-full` binaries. Feel free to submit a PR to fix this issue.
