### ISSUE TITLE
hare program crashes on nushell

### ISSUE THREAD

**Issue by uncomfyhalomacro** [nushell/nushell#8334]
### Describe the bug

I am currently learning https://harelang.org for my language-hopping endeavors. Followed the tutorial where I have to write a prompt to ask a name, and print it to stdout.

The sample program is as follows:

```rust
use bufio;
use fmt;
use os;
use strings;

export fn main() void = {
	const user = askname();
	greet(user);
};

// Asks the user to provide their name.
fn askname() str = {
	fmt::println("Hello!, Please enter your name:")!;
	const name = bufio::scanline(os::stdin)! as []u8;
	return strings::fromutf8(name)!;
};

// Greets a user by name.
fn greet(user: str) void = {
	fmt::printfln("Hello, {}!", user)!;
};
```

I compiled the program with `hare build -v -o hare-basics hare-basics.ha`

I then ran the program with `./hare-basics`

Got an error:

```
⬢ [distrobox:latest] > ./hare-basics
Hello!, Please enter your name:
Abort: Assertion failed: error occured at /home/uncomfy/Projects/learning-hare/hare-basics.ha:14:4
Aborted: oops, process './hare-basics' core dumped
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[entry #47:1:1]
 1 │ ./hare-basics
   · ──────┬──────
   ·       ╰── core dumped
   ╰────
  help: Aborted: child process './hare-basics' core dumped
```

Zsh and other POSIX shells run it just fine:

```
$ ./hare-basics
Hello!, Please enter your name:
uncomfyhalomacro
Hello, uncomfyhalomacro!
```

### How to reproduce

1. Build hare program
2. Run hare-basics program inside nushell

### Expected behavior

I expected nu to run the program just fine without a core dump

### Screenshots

![image](https://user-images.githubusercontent.com/66054069/223015666-d86a3878-4b0b-4ea0-826f-e623a30eeb5a.png)

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.76.0                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07) (built from a source tarball)               |
| cargo_version      | cargo 1.67.1                                                                    |
| pkg_version        | 0.76.0                                                                          |
| build_time         | 2023-02-22 00:00:00 +00:00                                                      |
| build_rust_channel | release                                                                         |
| features           | database, default, trash, which, zip                                            |
| installed_plugins  | from eml, from ics, from ini, from vcf, query, query json, query web, query xml |

### Additional context

I am not sure if this bug is nushell related. So I will file a bug report to harelang if proven that this is not a nushell issue

**Comment by rgwood** [comment]
Thanks for the bug report. It looks like the Hare program is hitting an assertion:

```
Abort: Assertion failed: error occured at /home/uncomfy/Projects/learning-hare/hare-basics.ha:14:4
```

I don't think anyone on the Nushell core team has experience with Hare. Someone who knows Hare will need to take a closer look at what that assertion is and why it's being hit.

**Comment by sholderbach** [comment]
Closing as it is unclear where nushell might behave unexpectedly and where assumptions of hare may be violated.

Feel free to reopen if you got feedback from Hare experts, what we might do wrong in a grave way.
