### ISSUE TITLE
`to json` returns null for SQLite databases

### ISSUE THREAD

**Issue by melMass** [nushell/nushell#8341]
### Describe the bug

It was hard to find a proper title but here is the issue with an example:

### How to reproduce

Download this db for instance ---> [test.db.zip](https://github.com/nushell/nushell/files/10901819/test.db.zip)

```zsh

╰─ $> open test.db                                                   ─╯
╭───────┬────────────────╮
│ todos │ [table 3 rows] │
╰───────┴────────────────╯

╰─ $> open test.db | to json                                         ─╯

null # <-------- This is not expected

# ⬇︎ this of course work

╰─ $> open test.db | table -e                                        ─╯

╭───────────┬────────────────────────────────────────────────────────────╮
│           │ ╭────┬────────────────────────────────────────┬──────╮     │
│ todos     │ │ id │              description               │ done │     │
│           │ ├────┼────────────────────────────────────────┼──────┤     │
│           │ │  1 │ Check that nu is awesome               │    1 │     │
│           │ │  2 │ Replace our default shell with nushell │    1 │     │
│           │ │  3 │ Call mom                               │    0 │     │
│           │ ╰────┴────────────────────────────────────────┴──────╯     │
╰───────────┴────────────────────────────────────────────────────────────╯
```

### Expected behavior

Should not need to be expanded first

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.75.1                                          |
| branch             | main                                            |
| commit_hash        | 023e244958428877953b7c2ff816532541f9f1d7        |
| build_os           | macos-aarch64                                   |
| build_target       | aarch64-apple-darwin                            |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)             |
| rust_channel       | 1.66.1-aarch64-apple-darwin                     |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)             |
| pkg_version        | 0.75.1                                          |
| build_time         | 2023-02-09 18:49:29 +01:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by rgwood** [comment]
Fixed for v0.77. Thanks for the bug report!
