### ISSUE TITLE
Error: nu::parser::shell_andand (link)

### ISSUE THREAD

**Issue by liuzonglin1** [nushell/nushell#8345]
### Question

![image](https://user-images.githubusercontent.com/87891147/223357735-7190fb6b-63f9-4d5f-92e8-ab4b5806e64d.png)

**Comment by sholderbach** [comment]
You are trying to `source` non-nushell code. That is explicitly not supported. Nushell is not a POSIX shell in the bash sense. Either you translate the script at `/etc/profile` or run that with `sh` or `bash` as required and then launch `nu` with the environment variables set by that. See https://www.nushell.sh/book/thinking_in_nu.html some motivation why nushell decides to behave very differently.
