### ISSUE TITLE
`cd` doesn't work in a custom command

### ISSUE THREAD

**Issue by vincent-uden** [nushell/nushell#8347]
### Describe the bug

It's impossible to change directories using `cd` in a custom command. I defined my command as follows (in config.nu):
```
def my-cd [] {
    cd /
}
```
When running the command, nothing happens
![image](https://user-images.githubusercontent.com/28573826/223381378-65774b6a-3ff2-475c-a03d-d7ea3131dbdc.png)

It seems to be only related to `cd` as a custom command with `ls` works just fine.
```
def my-cd [] {
    ls /
}
```
Produces
![image](https://user-images.githubusercontent.com/28573826/223381815-3d2c08f9-33a8-4721-ae2d-624482a8a92c.png)

Please do let me know if I'm doing anything wrong. If I am doing something wrong, I'm horribly confused by the configuration syntax.

### How to reproduce

1. Define a custom command using `cd`
```
def my-cd [] {
    cd /
}
```
2. Restart `nu` and run the command

### Expected behavior

I expect nu to change the directory

### Screenshots

![image](https://user-images.githubusercontent.com/28573826/223381378-65774b6a-3ff2-475c-a03d-d7ea3131dbdc.png)

![image](https://user-images.githubusercontent.com/28573826/223381815-3d2c08f9-33a8-4721-ae2d-624482a8a92c.png)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.76.1                                   |
| branch             | main                                     |
| commit_hash        | ba5258d7165423b360edf1747d0ffec00052db13 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.65.0 (897e37553 2022-11-02)      |
| rust_channel       | stable-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.65.0 (4bc8f24d3 2022-10-20)      |
| pkg_version        | 0.76.1                                   |
| build_time         | 2023-02-27 10:53:46 +00:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by kubouch** [comment]
That's because Nushell's environment is scoped in closures and commands https://www.nushell.sh/book/thinking_in_nu.html#nushell-s-environment-is-scoped

You need to use `def-env` instead of `def`.
