### ISSUE TITLE
Tee alternative (--passthru option for save command)

### ISSUE THREAD

**Issue by presidento** [nushell/nushell#8348]
### Related problem

I have a long oneliner, and want to debug it, so I'd like to save a state somewhere. In Bash I can use `tee` command. 

### Describe the solution you'd like

Add `--passhtru` parameter to `save` command, so I can inject it into a oneliner without changing it:

```nu
ls | where size > 2kb
#  ^------- I want to know the state here.

ls | save -f state.json --passthru | where size > 2kb
#    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Describe alternatives you've considered

Save the first part of the long oneliner into a variable:

```
let first_part = (ls)
$first_part | save -f state.json
$first_part | where size > 2kb
```

**Comment by fdncred** [comment]
You also may be able to use one of the debug category commands `help commands | where category == debug`. I'm thinking of `inspect` that you could inject liberally into the pipeline to see what's going on. It's a new command so there may be some rough edges.

**Comment by presidento** [comment]
The `inspect` is something similar to `tee`, although it cannot save the date to file. This ticket can be closed from my side.

**Comment by fdncred** [comment]
> .. although it cannot save the date to file.

Ya, we had to do some `unnatural` things to get it to even work like it does now. I'm not surprised saving it isn't do-able right now.

![emperor-palpatine-the-dark-side-of-the-force](https://user-images.githubusercontent.com/343840/223563816-b8413f16-9eaa-4b18-b639-b0f15f6945b0.gif)
