### ISSUE TITLE
Equivalent of bash "${array[@]}" for command args

### ISSUE THREAD

**Issue by harrysarson** [nushell/nushell#8349]
### Question

In bash I often write 

```
args=(
    --arg
    --this "has a value"
)

command "${args[@]}"
```

to break up commands with lots of args. Is there a way to write this in nushell?

### Additional context and details

I have looked at https://www.nushell.sh/book/coming_from_bash.html but couldn't find anything.

I have also tried `command  ($args | str join ' ')` but that puts all the args into one arg.

**Comment by fdncred** [comment]
For externals, I think you may be able to put them into a list like
```
let args = [
--arg
--this
"has a value"
]
command $args
```

**Comment by harrysarson** [comment]
yeah thanks 

```
command $args
```

works.

I had been trying

```
command ($args)
```

which didn't. 

cheers
