### ISSUE TITLE
`parse` behaves unexpectedly with `Makefile`-like data

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8352]
### Describe the bug

i was trying to parse a `Makefile` and could not do it.

i think it is a bug :thinking: 
at least an unexpected behaviour :yum: 

### How to reproduce

- :heavy_check_mark: the following works
```bash
"foo: this is foo
bar: this is bar"
| lines
| parse "{key}:{rest}"
| str trim
```
and gives
```bash
╭───┬─────┬─────────────╮
│ # │ key │    rest     │
├───┼─────┼─────────────┤
│ 0 │ foo │ this is foo │
│ 1 │ bar │ this is bar │
╰───┴─────┴─────────────╯
```

- :x: the following does not
```bash
"foo:
    this is foo
bar:
    this is bar"
| lines
| parse "{key}:{value}"
| str trim
```
and gives
```bash
╭───┬─────┬───────╮
│ # │ key │ value │
├───┼─────┼───────┤
│ 0 │ foo │       │
╰───┴─────┴───────╯
╭───┬─────┬───────╮
│ # │ key │ value │
├───┼─────┼───────┤
│ 1 │ bar │       │
╰───┴─────┴───────╯
```
- :x: and the following does not work either
```bash
let res = (
"foo:
    this is foo
bar:
    this is bar"
    | lines
    | parse "{key}:{value}"
    | str trim
)
$res
```
and gives
```bash
╭───┬─────┬───────╮
│ # │ key │ value │
├───┼─────┼───────┤
│ 0 │ foo │       │
╰───┴─────┴───────╯
```

### Expected behavior

i expected all the three above to give to lines in the output, either
```bash
╭───┬─────┬─────────────╮
│ # │ key │    rest     │
├───┼─────┼─────────────┤
│ 0 │ foo │ this is foo │
│ 1 │ bar │ this is bar │
╰───┴─────┴─────────────╯
```
for the first one or
```bash
╭───┬─────┬───────╮
│ # │ key │ value │
├───┼─────┼───────┤
│ 0 │ foo │       │
│ 1 │ bar │       │
╰───┴─────┴───────╯
```
for the two others

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.76.1                                              |
| branch             | main                                                |
| commit_hash        | 0e2167884d6a1f602ac6240581a3dfd3369b6e1e            |
| build_os           | linux-x86_64                                        |
| build_target       | x86_64-unknown-linux-gnu                            |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)                 |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu                     |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)                 |
| build_time         | 2023-03-07 18:57:18 +01:00                          |
| build_rust_channel | release                                             |
| features           | default, zip                                        |
| installed_plugins  | gstat, len, query, query json, query web, query xml |

**Comment by amtoine** [comment]
i cannot reproduce the behaviour with
```bash
"foo:
bar:
"
```
nor
```bash
"foo:
bar:"
```
maybe that has to do with the newlines because
```bash
"foo:

bar:"
```
and
```bash
"foo:

bar:
"
```
have the bug

**Comment by fdncred** [comment]
I'm guessing you need to str trim in your example that doesn't work. I could be wrong. On my phone or I'd try it myself.

**Comment by fdncred** [comment]
I'm not really sure how `parse` is supposed to be smart enough to infer more complicated regex expressions from just "{key}:{value}".
This works though and demonstrates what it would have to construct under the hood to get your desired output.
```
❯ "foo:
    this is foo
bar:
    this is bar"
| parse -r '(?m)(?<key>\bfoo\b|\bbar\b):\r\s+(?<value>.*)'
| str trim
╭───┬─────┬─────────────╮
│ # │ key │    value    │
├───┼─────┼─────────────┤
│ 0 │ foo │ this is foo │
│ 1 │ bar │ this is bar │
╰───┴─────┴─────────────╯
```

At the end of the day, parse is just turning `"{key}:{value}"` into a regex, iirc. I'm sure we could make it smarter but we need to be careful about what we assume.

**Comment by sholderbach** [comment]
I think here adding a multiline mode flag as with #9508 could help to make this a bit more intuitive (so you don't have to remember the exact regex extensions)

**Comment by amtoine** [comment]
@fdncred 
iirc, the issue from past self was mostly that 
```nushell
"foo:
    this is foo
bar:
    this is bar"
| lines
| parse "{key}:{value}"
| str trim
```
and 
```nushell
let res = (
"foo:
    this is foo
bar:
    this is bar"
    | lines
    | parse "{key}:{value}"
    | str trim
)
$res
```
give different result and that the tables are broken into two parts :open_mouth: 

however i agree with you and disagree with my past self, i'm not sure anymore
```nushell
"foo:
    this is foo
bar:
    this is bar"
| lines
| parse "{key}:{value}"
| str trim
```
should return
```nushell
╭───┬─────┬─────────────╮
│ # │ key │    rest     │
├───┼─────┼─────────────┤
│ 0 │ foo │ this is foo │
│ 1 │ bar │ this is bar │
╰───┴─────┴─────────────╯
```
:wink:

**Comment by fdncred** [comment]
Coming back to this again. this works.
```
❯ "foo:
    this is foo
bar:
    this is bar"
| parse -r '(?<key>\w+):\r\n\s+(?<value>.+)'
╭───┬─────┬─────────────╮
│ # │ key │    value    │
├───┼─────┼─────────────┤
│ 0 │ foo │ this is foo │
│ 1 │ bar │ this is bar │
╰───┴─────┴─────────────╯
```
 I'm not sure how using `lines` would ever make this work because `foo:` would be on a line and `    this is foo` would be on a separate line. so, this output looks proper to me, although not what you were going for.
```
❯ "foo:
    this is foo
bar:
    this is bar"
| lines
| parse "{key}:{value}"
| str trim
╭───┬─────┬───────╮
│ # │ key │ value │
├───┼─────┼───────┤
│ 0 │ foo │       │
╰───┴─────┴───────╯
╭───┬─────┬───────╮
│ # │ key │ value │
├───┼─────┼───────┤
│ 1 │ bar │       │
╰───┴─────┴───────╯
```
or I could maybe see this, but it's wrong too.
```
╭───┬─────┬─────────────╮
│ # │ key │    value    │
├───┼─────┼─────────────┤
│ 0 │ foo │             │
│ 1 │     │ this is foo │
│ 2 │ bar │             │
│ 3 │     │ this is bar │
╰───┴─────┴─────────────╯
```

**Comment by amtoine** [comment]
@fdncred 
the use of `lines` is, afaik, the easiest way to work with `parse` when trying to match on single lines, e.g.
```nushell
"foo:
    this is foo
bar:
    this is bar"
| parse "{key}:{value}"
| str trim
```
gives me
```
╭───┬─────┬─────────────────╮
│ # │ key │      value      │
├───┼─────┼─────────────────┤
│ 0 │ foo │ this is foo     │
│   │     │ bar:            │
│   │     │     this is bar │
╰───┴─────┴─────────────────╯
```
which is not the result i want :yum: 

my real issue here is the inconsistency between 
```nushell
"foo:
    this is foo
bar:
    this is bar"
| lines
| parse "{key}:{value}"
| str trim
```
and
```nushell
let res = (
"foo:
    this is foo
bar:
    this is bar"
    | lines
    | parse "{key}:{value}"
    | str trim
)
$res
```
which i do not understand :thinking:

**Comment by fdncred** [comment]
regarding your comment about running the command and assigning the pipeline, i get the same result.
![image](https://github.com/nushell/nushell/assets/343840/ae7d8e18-c2c7-4cb0-b339-e4851634ed2f)

regarding this output, i'm not even sure how it happens.
```
╭───┬─────┬─────────────────╮
│ # │ key │      value      │
├───┼─────┼─────────────────┤
│ 0 │ foo │ this is foo     │
│   │     │ bar:            │
│   │     │     this is bar │
╰───┴─────┴─────────────────╯
```
but you can see the regex that is being run, which is just wrong for your use case
![image](https://github.com/nushell/nushell/assets/343840/d942826d-2e34-498f-ac65-50c1ff34b8b4)
you can see how it's wrong here at regex101.com
![image](https://github.com/nushell/nushell/assets/343840/7b718d0e-8564-4107-a4bb-8d3391d2fa5e)

The hard part is trying to come up with a regex that works in all situations, which is exceedingly difficult. so, i'm not sure what to do here. we could change the regex to work better with your scenario, but i'd bet others would break.

**Comment by fdncred** [comment]
This one is pretty close. We might could do a change with it
![image](https://github.com/nushell/nushell/assets/343840/62303c41-bcc3-4db5-bf51-625182410c06)


Changes
This
```
(?s)\A(?P<key>.*?):(?P<value>.*?)\z
```
to this
```
(?P<key>.*)?:\s*(?P<value>.*)?
```

The key differences are:
- we're not using anchors `\A` and `\z`
- we're allowing anything after `:`
- we're making the key optional with `?`
- we're making the value optional with `?`

**Comment by amtoine** [comment]
yeah maybe it's very specific to the problem i have here... :cry:

## in the end
i agree my original issue in there was too specific about a particular regex and we probably do not want to fix such a thing :ok_hand: 

HOWEVER, i still get an inconsistent behaviour between
```nushell
> "foo:
∙     this is foo
∙ bar:
∙     this is bar"
∙ | lines
∙ | parse "{key}:{value}"
∙ | str trim
╭───┬─────┬───────╮
│ # │ key │ value │
├───┼─────┼───────┤
│ 0 │ foo │       │
╰───┴─────┴───────╯
╭───┬─────┬───────╮
│ # │ key │ value │
├───┼─────┼───────┤
│ 1 │ bar │       │
╰───┴─────┴───────╯
```
and
```nushell
> let res = (
∙ "foo:
∙     this is foo
∙ bar:
∙     this is bar"
∙     | lines
∙     | parse "{key}:{value}"
∙     | str trim
∙ )
> $res
╭───┬─────┬───────╮
│ # │ key │ value │
├───┼─────┼───────┤
│ 0 │ foo │       │
╰───┴─────┴───────╯
```

it looks like a bug to me having two tables in the first example and a single one in the second :sweat_smile:

> **Note**
> this does not happen with the data below
> ```
> "foo:this is foo
> bar:this is bar"
> ```
> this is why i mention "*`Makefile`-like data*" in the title of the issue

**Comment by fdncred** [comment]
I think what might solve this delima is if we had a dozen or so tests that run parse through it's paces. Right now, I'm leaning towards changing the regex internally to be more forgiving. We have a few [here](https://github.com/nushell/nushell/blob/4af24363c239532453968d877e549d777fb1e4fa/crates/nu-command/tests/commands/parse.rs#L1) that we could build on. At least it would give us a starting point to say what it **should** do versus what it **should not** do.

I understand your point above, but I still put that into the category that `lines` is making it puke. However, it should puke the same way in both scenarios. I'm not sure what to do about that. Maybe my new regex would fix it?

**Comment by amtoine** [comment]
> I think what might solve this delima is if we had a dozen or so tests that run parse through it's paces. Right now, I'm leaning towards changing the regex internally to be more forgiving. We have a few [here](https://github.com/nushell/nushell/blob/4af24363c239532453968d877e549d777fb1e4fa/crates/nu-command/tests/commands/parse.rs#L1) that we could build on. At least it would give us a starting point to say what it **should** do versus what it **should not** do.
> 
adding more tests to guide the behaviour we want could be a great idea :+1: 

> I understand your point above, but I still put that into the category that `lines` is making it puke. However, it should puke the same way in both scenarios. I'm not sure what to do about that. Maybe my new regex would fix it?
>
yeah appears the behaviour becomes more consistent with `parse --regex '(?P<key>.*)?:\s*(?P<value>.*)?'` :ok_hand:
