### ISSUE TITLE
`Enter` command: *multiple* directories

### ISSUE THREAD

**Issue by bobhy** [nushell/nushell#8357]
### Related problem

If I have a set of directories that I typically cycle between, it would be convenient if I could preload the list of directories all in one go. 

### Describe the solution you'd like

```
〉enter src/rust/nushell src/rust/nushell.github.io/
〉shells
╭───┬────────┬────────────────────────────────────────╮
│ # │ active │                  path                  │
├───┼────────┼────────────────────────────────────────┤
│ 0 │ false  │ /home/bobhy                            │
│ 1 │ false  │ /home/bobhy/src/rust/nushell           │
│ 2 │ true   │ /home/bobhy/src/rust/nushell.github.io │
╰───┴────────┴────────────────────────────────────────╯
```

### Describe alternatives you've considered

 Currently I have to do a sequence of `enter` commands, not that that is the end of the world.

```
〉enter src/rust/nushell
-------------------------------------------- /home/bobhy/src/rust/nushell --------------------------------------------
〉enter src/rust/nushell.github.io/
Error: nu::shell::io_error

  × I/O error
  help: Os { code: 2, kind: NotFound, message: "No such file or directory" }

-------------------------------------------- /home/bobhy/src/rust/nushell --------------------------------------------
〉enter ../nushell.github.io/
--------------------------------------- /home/bobhy/src/rust/nushell.github.io ---------------------------------------
〉
```
Although, note that the list of directories had to be amended because each `enter` command changes the current working directory.

### Additional context and details

If the idea has legs, I bet it would be a good first feature for someone to tackle.

**Comment by fdncred** [comment]
I think this is a good idea. However, we're leaning toward moving this entire functionality to script form in the stdlib. Join us in Discord on #standard_library if you want to talk more about it.

**Comment by bobhy** [comment]
To ask the question is to answer it.  See #8368

**Comment by bobhy** [comment]
...which has now been merged.
