### ISSUE TITLE
Tab completion select match by default

### ISSUE THREAD

**Issue by dmatos2012** [nushell/nushell#8362]
### Related problem

Hi, 
Basically, same as #7640, but only for the first request. Basically, now, if you do `cd ~/Doc<tab` , in order to complete to ~/Documents, you have to hit `enter` to enter the suggestion. I think this is ok but a bit unnecessary.  Just check video on other issue for more info. 

### Describe the solution you'd like

Autocompleting to `~/Documents`(if only match) without hitting enter. Basically, matching the behavior of zsh, and I believe fish as well. It would for sure help ergonomics. 

### Additional context and details

I would give it a shot myself, but not sure if this has been tried before, or there are some specific behaviors that prevent this feature from happening. Not sure how hard it would be to make this work.

**Comment by fdncred** [comment]
We have `quick`. Does it do what you're looking for?
```
    completions: {
        quick: true # set this to false to prevent auto-selecting completions when only one remains
    }
```

**Comment by dmatos2012** [comment]
Yeah, I realized i wasnt too clear on my comment. By default, its already `true`, but problem is that its rarely the only match. Lets say:
cd ~/Doc - > matches `Documents` and  `docker_data` for me, so I end up in the same predicament as before. 

And pressing tab on the first one, doesnt auto complete it until i press enter.

**Comment by fdncred** [comment]
If you have `case_sensitive: true` it'll work like you're saying I think.
