### ISSUE TITLE
os error 13

### ISSUE THREAD

**Issue by danimesq** [nushell/nushell#8363]
When I run "nu" (which resides in my /usr/bin), or even when I remove it and run locally with "./nu", it displays this error:

> Error: 
>   × Permission denied (os error 13)

The nu version is the latest, and same for Ubuntu (23.04 Lunar Lobster).

Any clue about what may be interfering/causing this and possible fixes?

**Comment by fdncred** [comment]
I'm guessing that it's one of these things
- permissions to the folder where nu resides
- permissions to nu itself
- permissions to login.nu
- permissions to config.nu
- permissions to env.nu

I'm not sure what else it could be

**Comment by danimesq** [comment]
Gotcha!

The issue wasn't on /usr/bin, in nu itself nor in login.nu, but in `~/.config/nushell`!

Sorry for involving nushell in a particular issue; anyway, for conscience cleanse, I hope this issue may be useful for any user or dev playing with Nu.

In my case I'm playing with nu to be the default shell in my Linux distro, and when installing it I had some mistake with `sudo` which will now be fixed thanks to your clues.

Again, I ask sorry and hope this issue be useful for anyone coming.

**Comment by danimesq** [comment]
BTW @fdncred why does it have a "nushell" plus a "nu" folder?

It contains a config.toml file containing:

> 
> startup = [
>  "mkdir ~/.cache/starship",
>  "starship init nu | save ~/.cache/starship/init.nu",
>  "source ~/.cache/starship/init.nu"
> ]
> prompt = "starship_prompt"

Are this some outdated folder structure by Starship?

**Comment by fdncred** [comment]
it's probably from a very old version of nushell when we had a config.toml, which we don't have nor support anymore.

**Comment by rudra-code-creator** [comment]
> When I run "nu" (which resides in my /usr/bin), or even when I remove it and run locally with "./nu", it displays this error:
> 
> > Error:
> > × Permission denied (os error 13)
> 
> The nu version is the latest, and same for Ubuntu (23.04 Lunar Lobster).
> 
> Any clue about what may be interfering/causing this and possible fixes?

I'm on nixos 24.11 vicuna and facing the same issue, does anyone no the solution to this isssue on nixOS

**Comment by rudra-code-creator** [comment]
> I'm guessing that it's one of these things
> 
> * permissions to the folder where nu resides
> * permissions to nu itself
> * permissions to login.nu
> * permissions to config.nu
> * permissions to env.nu
> 
> I'm not sure what else it could be

Oh no then I guess I'm ducked 🤣. bcos on nixOS the first three are stored in nix store which is immutable and read-only and the second two ive checked permissions on. I guess all I can do is wait till they fix the permission for first three in nixpkgs and then update (#sigh).

**Comment by rudra-code-creator** [comment]
Nevermind I am not ducked, I fixed the issue. If anyone else is having this issue on nixOS this thread shows solution:

https://discourse.nixos.org/t/on-my-system-bash-and-fish-work-perfectly-but-zsh-and-nushell-have-issues-i-cant-figure-out-how-to-fix/56289
