### ISSUE TITLE
`bspc node -t ~fullscreen` gets converted to `bspc node -t /home/fullscreen`

### ISSUE THREAD

**Issue by krinistof** [nushell/nushell#8369]
### Describe the bug

I have my sxhkd setup, which has a mapping for toggling fullscreen, but I cannot make it work with nushell. I've tried it surrounding with `"` and ` '`, but I wasn't able to fix it. :/ 

### How to reproduce

execute any command with '~something'" as parameter

### Expected behavior

the ~ doesnt get replaced by `/home/`, and if it does, it would be better to be able to escape it with `\`.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.74.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 9a56665c6beee31e365ce17898056f1ff2db4094                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12) (Arch Linux rust 1:1.66.0-1) |
| cargo_version      | cargo 1.66.0                                                     |
| pkg_version        | 0.74.0                                                           |
| build_time         | 2023-01-10 22:53:04 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | database, dataframe, default, trash, which, zip                  |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment]
Love this. We have people talk about not liking that `~` is not expanded and others talk about not liking that `~` is expanded. I agree we should have an opt-in version somehow and maybe we do now, I'm not sure.

Does this still happen in the latest version? 0.74 is about 2 months old now.

**Comment by WindSoilder** [comment]
> Does this still happen in the latest version? 0.74 is about 2 months old now.

Yeah would you please try the latest version?  I remember you can opt out with `"` in latest version

**Comment by krinistof** [comment]
I've built 0.74.1, and it has fixed it. Thank you for your quick responses and everything!
