### ISSUE TITLE
Extra artifacts around Starship prompt

### ISSUE THREAD

**Issue by d249u7** [nushell/nushell#8377]
### Describe the bug

When the promp is set to Starship's Nerd Font Symbols Preset, there are extra symbols around it inserted by Nu.

See in screenshot that `starship explain` does not include the filled arrow on top and the second arrow on bottom.

I tried setting the starship prompt by following both their and Nu's recommended way. The results were the same.

### How to reproduce

1- Add the following to the end of your Nushell env file:

```
mkdir ~/.cache/starship
starship init nu | save -f ~/.cache/starship/init.nu
```

2- And add the following to the end of your Nushell configuration:

```
source ~/.cache/starship/init.nu
```

3- Run 
```
starship preset nerd-font-symbols > ~/.config/starship.toml
```

4- Run Nu in ITerm2

### Expected behavior

To show the starship prompt only

### Screenshots

![image](https://user-images.githubusercontent.com/60433637/224201484-dd191c0a-6cb8-4136-89b7-96016d41d52f.png)

### Configuration

| key                | value                                |
| ------------------ | ------------------------------------ |
| version            | 0.76.0                               |
| branch             |                                      |
| commit_hash        |                                      |
| build_os           | macos-x86_64                         |
| build_target       | x86_64-apple-darwin                  |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)  |
| rust_channel       | stable-x86_64-apple-darwin           |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)  |
| pkg_version        | 0.76.0                               |
| build_time         | 2023-03-09 18:37:10 +00:00           |
| build_rust_channel | release                              |
| features           | database, default, trash, which, zip |
| installed_plugins  |                                      |

**Comment by sholderbach** [comment]
This is probably the `PROMPT_INDICATOR*` family of variables that are still set to contain the arrow for the prompt (the line editor `reedline` currently uses them to indicate mode changes like when interacting with menus or the vi emulation).

Try to unset them in `env.nu` to an empty string via `config env`.

**Comment by d249u7** [comment]
I've just discovered those and unset them, problem solved.

**Comment by amtoine** [comment]
@oluceps 
i'm not sure `starship` support `vi` mode for Nushell, does it?

i have a `>` in my `starship` prompt but it does not respond to mode changes in `vi` mode :thinking:
