### ISSUE TITLE
Piping from any command into a specific alias panics.

### ISSUE THREAD

**Issue by InfinityShell1337** [nushell/nushell#8378]
### Describe the bug

When I have this written down at the prompt:
`ls | nv`
(and `nv` is an alias to `nvim`)
pressing tab right at the end of `ls`:
----v
`ls | nv`
causes nushell to panic with this error (with RUST_BACKTRACE=full):
```
thread 'main' panicked at 'begin <= end (4 <= 2) when slicing `ls | nv`', library/core/src/str/mod.rs:111:5
stack backtrace:
   0:     0x55c6b9f37868 - <unknown>
   1:     0x55c6b8a1466c - <unknown>
   2:     0x55c6b9f2f365 - <unknown>
   3:     0x55c6b9f394a8 - <unknown>
   4:     0x55c6b9f391a8 - <unknown>
   5:     0x55c6b9f39b56 - <unknown>
   6:     0x55c6b9f399c4 - <unknown>
   7:     0x55c6b9f37dc4 - <unknown>
   8:     0x55c6b9f3971d - <unknown>
   9:     0x55c6b86306a3 - <unknown>
  10:     0x55c6b8a18a9f - <unknown>
  11:     0x55c6b8a0ab57 - <unknown>
  12:     0x55c6b8a10c88 - <unknown>
  13:     0x55c6b86309c2 - <unknown>
  14:     0x55c6b9d7b980 - <unknown>
  15:     0x55c6b9d766b8 - <unknown>
  16:     0x55c6b9d75e03 - <unknown>
  17:     0x55c6b9d74b0f - <unknown>
  18:     0x55c6b8b4e22c - <unknown>
  19:     0x55c6b8b2f6bf - <unknown>
  20:     0x55c6b8b3348d - <unknown>
  21:     0x55c6b8b35134 - <unknown>
  22:     0x55c6b9f266fb - <unknown>
  23:     0x55c6b8b31f12 - <unknown>
  24:     0x7f0069b5f20c - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  25:     0x7f0069b5f2bc - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:381:3
  26:     0x55c6b868244a - <unknown>
  27:                0x0 - <unknown>
```

### How to reproduce

1. Have `alias nv = nvim` in your configuration.
2. Type `ls | nv` at the prompt. (as far as I checked `ls` can be replaced with any other cmd)
3. Move cursor to the end of the ls: `ls`{cursor}` | nv`
4. Press Tab

### Expected behavior

I expected nu to not error, and show the completion menu.

### Configuration

| key                | value                                           |
| ------------------ | ----------------------------------------------- |
| version            | 0.71.0                                          |
| branch             |                                                 |
| commit_hash        |                                                 |
| build_os           | linux-x86_64                                    |
| build_target       | x86_64-unknown-linux-gnu                        |
| rust_version       | rustc 1.64.0 (Void Linux)                       |
| cargo_version      | cargo 1.64.0                                    |
| pkg_version        | 0.71.0                                          |
| build_time         | 2022-11-14 16:54:12 +00:00                      |
| build_rust_channel | release                                         |
| features           | database, dataframe, default, trash, which, zip |
| installed_plugins  |                                                 |

**Comment by kubouch** [comment]
This should be fixed in the upcoming release and latest main branch.

**Comment by sholderbach** [comment]
Closing as this is referring to an out of date version of nushell.
We can not reproduce it with the latest stable version and the main development branch.
