### ISSUE TITLE
Unit test, assert command

### ISSUE THREAD

**Issue by presidento** [nushell/nushell#8384]
### Related problem

As soon as we consider Nushell a programming language, the need for unit testing emerges. While it is preferable to have a complete unit testing framework, I think an `assert` command should exist as a first step at least.

### Describe the solution you'd like

Something like this

```
def assert [assertion: bool, message?: string] {
    if $assertion { return }
    let msg_text = (if ($message != null) { $message } else { "No message" })
    let span = (metadata $assertion).span;
    error make {
        msg: $"Assertion failed: ($msg_text)",
        label: {
            text: "It is not true.",
            start: $span.start,
            end: $span.end
        }
    }
}

assert (1 * 1 == 1) "Addition is easy."
assert (2 * (1 + 1) == 5) "I can do simple calculations"
assert (6 / 3 == 2)
```

### Describe alternatives you've considered

I haven't found any alternative here, or in the documentation. If we already have a preferred unit framework, I am willing to update the Nushell book. Although it is a typical pattern to have a built-in `assert` element in the language.

**Comment by sholderbach** [comment]
@amtoine already started adding corresponding assertion commands to the standard library parts written in nu itself.

The technical work necessary to fully benefit from that would be devising a test discovery mechanism. (and maybe some hot-reloading of definitions for the ultimate TDD experience)

**Comment by fdncred** [comment]
@presidento Feel free to check out and contribute here https://github.com/nushell/nushell/blob/878e08cfa4c8ad83ea42e6a99c809cbbccc7574d/crates/nu-utils/standard_library/std.nu#L10-L25

**Comment by presidento** [comment]
I continue there, thank you.
