### ISSUE TITLE
Variable assignment fails due to piping no values in an empty directory

### ISSUE THREAD

**Issue by guilt** [nushell/nushell#8393]
### Question

How do I assign variables when I'm in an empty directory?

```nushell
let x = (ls | where size >= 2kB)
```
```nushell
Error: nu::shell::only_supports_this_input_type (link)

  × Input type not supported.
   ╭─[entry #12:1:1]
 1 │ let x = (ls | where size >= 2kB)
   ·          ─┬   ──┬──
   ·           │     ╰── only list, binary, raw data or range input data is supported
   ·           ╰── input type: nothing
   ╰────
```

I guess, returning an empty list may still be okay?

**Comment by ahkrr** [comment]
You can ignore errors with the `do` command. You can read `help do` 
`let x = do -i {ls | where size >= 2kB }`
You can use the newer `try catch` construct. `help try`
`let x = try {  ls | where size >= 2kB  } catch { [] }`

**Comment by amtoine** [comment]
i cannot reproduce this with the latest revision of Nushell :thinking:
