### ISSUE TITLE
strange behavior of "where size >"

### ISSUE THREAD

**Issue by tshepang** [nushell/nushell#840]
I was puzzled by this (from current master... d91b735):
```
/home/tshepang> ls ** | where size > 500mb
/home/tshepang> ls ** | where size > 1gb
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┯━━━━━━━━━━━┯━━━━━━━━━━┯━━━━━━━━┯━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━
 name                                                           │ type      │ readonly │ size   │ accessed       │ modified 
────────────────────────────────────────────────────────────────┼───────────┼──────────┼────────┼────────────────┼────────────────
 .cache/mozilla/firefox/nm1vhrhl.default-release/cache2/entries │ Directory │          │ 2.5 MB │ 13 seconds ago │ 37 seconds ago 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┷━━━━━━━━━━━┷━━━━━━━━━━┷━━━━━━━━┷━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━━━
```
So, it says the dir is > 1gb, but not > 500mb.

**Comment by jonathandturner** [comment]
@tshepang - can you tell us about what OS and version you're running Nu in?

I haven't seen this but it's possible it's only on some OSes.

**Comment by tshepang** [comment]
This is Debian 10

**Comment by idanarye** [comment]
I'm on ArchLinux (`5.2.14-arch1-1-ARCH`) and I experience a similar problem. I experimented a bit and it looks like `where` is treating `GB` the same as `MB`.

**Comment by tshepang** [comment]
In my case, that directory actually turns out to be > 1gb indded

**Comment by jonathandturner** [comment]
This looks suspicious: 

https://github.com/nushell/nushell/blob/193b00764b0cf5ad0335446c55f6c8d3aeb388a9/src/parser/hir/syntax_shape/expression/unit.rs#L80-L83

Anyone want to send in a PR to fix? Should be pretty easy by the look of it
