### ISSUE TITLE
`}` gives strange error

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#8400]
### Describe the bug

```
~/Source/nushell〉 }
Error: nu::parser::unbalanced_delimiter

  × Unbalanced delimiter.
   ╭─[entry #3:1:1]
 1 │ )
   ╰────
```

note: that error line is the previous thing I typed into the repl.

### How to reproduce

1. Either start by typing `}` and hit enter. Or...

Type a few lines first, then:
2. Type `}` and hit enter

### Expected behavior

I'd expect to underline the actual `}`. Right now it seems like it's trying to underline the point *before* it, which is going to be whatever the last buffer in the REPL was.

This doesn't seem to be a `Span::new(0, 0)` related issue, but one that has to do with not having a correct span when lexing a `}` by itself.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.76.1                                   |
| branch             | main                                     |
| commit_hash        | 0e2167884d6a1f602ac6240581a3dfd3369b6e1e |
| build_os           | macos-aarch64                            |
| build_target       | aarch64-apple-darwin                     |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-aarch64-apple-darwin              |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-03-08 06:56:59 +13:00               |
| build_rust_channel | debug                                    |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by jafriyie1** [comment]
I can take this one if that is ok!

**Comment by rgwood** [comment]
@jafriyie1 Sounds good! Let us know if you need any help (#implementation-chat on the Nushell Discord is probably the easiest place)

**Comment by vaishaag** [comment]
Hey @jafriyie1, are you working on this? If not, I can give it a try.

**Comment by jafriyie1** [comment]
Hello, please go ahead and work on this! I sadly haven't had time to take a crack at this.
