### ISSUE TITLE
std assert: 2 potential improvements

### ISSUE THREAD

**Issue by bobhy** [nushell/nushell#8401]
### Related problem

It's nice to get a standard NU error message when an assertion fails, but it would be even nicer if the error could point to the line in the script where `assert` was called.

And it would also be nice if caller could specify the text of the failure message.

Current invocation.

```nushell
〉std assert false 
Error: 
  × condition given to `assert` does not hold
    ╭─[~/src/rust/nushell/crates/nu-utils/standard_library/std.nu:25:1]
 25 │     if not $cond {
 26 │         error make {msg: $msg}
    ·         ─────┬────
    ·              ╰── originates from here
 27 │     }
    ╰────
```
1. Error points to line number in std.nu, regardless of where assert is called.
2. Constant error message.

### Describe the solution you'd like

Something like:
```nushell
def "myassert eq" [
        left:any 
        right:any 
        msg?:string = "..."
        --verbose (-v)     # enable to see successful tests and values of unequal tests
    ] {
        if $left != $right {
            let start_span = (metadata $left).span.start
            let end_span = (metadata $right).span.end
            let fail_msg = (if $verbose {
                                $"\n    left: ($left|debug)\nnot equal to\n   right: ($right|debug)"
                            } else {""})
            error make {msg: $"Assertion failed checking ($msg)($fail_msg)", label: {text: "Values not equal" start: $start_span end: $end_span}}
        } else {
            if $verbose {
                echo $"check succeeded: ($msg)"
            }
        }
    }
```

Then:
```nushell
〉myassert eq 1 42
Error: 
  × Assertion failed checking ...
   ╭─[entry #5:1:1]
 1 │ myassert eq 1 42
   ·             ──┬─
   ·               ╰── Values not equal
   ╰────

〉myassert eq 1 42 "the answer"
Error: 
  × Assertion failed checking the answer
   ╭─[entry #6:1:1]
 1 │ myassert eq 1 42 "the answer"
   ·             ──┬─
   ·               ╰── Values not equal
   ╰────
```

The above includes a `--verbose` flag to:
* show *successful* tests (which is handy if the tests all succeed, and so quickly you want to verify they all actually ran)
* show the unequal values when the assertion fails
```nushell
〉myassert eq -v 1 1 "the answer"
check succeeded: the answer

〉myassert eq -v 1 42 "the answer"
Error: 
  × Assertion failed checking the answer
  │     left: 1
  │ not equal to
  │    right: 42
   ╭─[entry #14:1:1]
 1 │ myassert eq -v 1 42 "the answer"
   ·                ──┬─
   ·                  ╰── Values not equal
   ╰────
```

### Additional context and details

I came up with this function in the course of developing unit tests for my own library module.  I'm offering these ideas for enhancing the assert functions in the standard library, for what it's worth.

**Comment by amtoine** [comment]
@bobhy 

would that issue be closed by #8405? :yum:

**Comment by amtoine** [comment]
mm reading this again, #8405 does not address the `--verbose` flag which would be a great addition to the `assert` familly imo :yum:

**Comment by bobhy** [comment]
Don't need `--verbose`.  `assert`, as of 0.79, is plenty good enough.  Though it doesn't directly display the *values* that failed the check,  it does display the span in the source which initialized the values.  This might work out useful enough in real world testing scenarios, time will tell.  Other use of --verbose to trace sequence of passing checks not really a good feature.  Maybe Nu needs a `--trace` switch (like `bash -x`) to show statements as they execute.

Either way, ship it!

**Comment by amtoine** [comment]
out of curiosity, what addressed this @bobhy? :blush:

**Comment by bobhy** [comment]
See above: I kind of changed my mind on needing --verbose to trace the sequence of *successful* tests.  Now, with `std log`,you could add logging to `assert`, but what I'm really looking for is the equivalent of `bash -x` to trace the whole sequence of commands when debugging.
