### ISSUE TITLE
link to full release notes is broken

### ISSUE THREAD

**Issue by wayneashleyberry** [nushell/nushell#841]
The link to full release notes in the [`0.4.0`](https://github.com/nushell/nushell/releases/tag/0.4.0) release is broken.

```diff
- http://www.jonathanturner.org/2019/10/nushell_0_4_0.html
+ http://www.jonathanturner.org/2019/10/nushell-0_4_0.html
```

**Comment by jonathandturner** [comment]
Tried to update this but github is giving us errors. Will try to update once github fixes the issue.

Thanks for the report :)

**Comment by zbeekman** [comment]
I came here to report the same thing.

**Comment by andrasio** [comment]
@jonathandturner Maybe it'd be easier [to change](https://github.com/jonathandturner/jonathandturner.github.io/blob/master/_posts/2019-10-15-nushell-0_4_0.md) filename to the same as [release 0.3.0](https://github.com/jonathandturner/jonathandturner.github.io/blob/master/_posts/2019-09-24-nushell_0_3_0.md)?

Editing still not possible.
