### ISSUE TITLE
Skip ZWJ like rustc

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#8411]
### Related problem

I'd like to prototype something like this in our tabled code but I'm not quite sure where to do it now days. @zhiburt Thoughts on how to implement this so we can see if it makes my table torture test any better?

https://github.com/rust-lang/rust/blob/8a73f50d875840b8077b8ec080fa41881d7ce40d/compiler/rustc_errors/src/emitter.rs#L2477-L2497

> **Warning** Torture Test
```
http get https://raw.githubusercontent.com/nushell/nu_scripts/main/before_v0.60/assets/gh-emoji.json 
```

### Describe the solution you'd like

Better column alignment

**Comment by bobhy** [comment]
Please take a look at the recent enhancement to `fill` command (#8134: it's not in nushell 0.76, you'll have to build nushell from current main branch to get it).  
It should correctly pad Unicode strings based on the number of 'print positions' the string occupies when rendered (e.g 1 extended unicode grapheme == 1 print position, even if it includes ZWJ.)  `fill` now also discounts the length of ANSI escape sequences! 

```
echo "This output should be 3 print positions wide, with leading and trailing `+`"
$"\u{1F9D1}\u{200D}\u{1F3EB}" | fill -c "+" -w 3 -a "c"
```

One caveat: I have found that the gnome-terminal (and xfce-terminal) do not handle ZWJ correctly, so will render these graphemes as multiple glyphs (even though `fill` pads with the correct number of padding characters).  Things render better on the web: github  pages and rust playground.  If you know the magic config to fix this in gnome, please share!

**Comment by zhiburt** [comment]
@bobhy 

We could experiment with this;
But it'd require some changes under the hood.
Specifically it would need to wait a bit (before next release of `tabled`)

**Comment by fdncred** [comment]
After testing #8421, I'm not sure how this can work. I wrote more there with examples. Thanks @zhiburt!!

@bobhy I'm up for anything that can align the columns better but I'm just not sure how that's going to be accomplished since different terminals render characters differently. If you want to play around and see if you can make it better. Please feel free. We'd love to have better table rendering.

**Comment by zhiburt** [comment]
I guess the best we can do,
Is to check `$TERM` env variable and peek different strategies depend on the value.

But to be honest I am not sure whether even each terminal is consistent in its logic :)

**Comment by fdncred** [comment]
JT suggested some fancy drawing stuff at one point that would draw, see that the columns aren't lined up, redraw, etc, but it would be so slow that it probably wouldn't be worth it.

**Comment by fdncred** [comment]
> Interesting; how we would "see" it,

I think we'd have to "see" it by knowing what column we draw the `│` in and then when a column is too wide we'd have to recalculate the entire table. The thought was to cache the first 1000 rows and adjust the sizes but you can't do that in memory, you have to do that in a terminal buffer or something because it's not just about the width of the characters, it's about how the terminal renders them.

**Comment by zhiburt** [comment]
> I think we'd have to "see" it by knowing what column we draw the │

Yes but as far as I understand we can't at least on linux/bsd*?
I guess we could somehow via sdk; x11 or whatever but it's probably not the way to go.

On windows we potentially could by `ReadConsoleOutputW`.

That's actually why I've asked, interesting to hear how we could do it :)

**Comment by fdncred** [comment]
ya, i was thinking crossterm all along. if it's not possible then bummer. :(
