### ISSUE TITLE
Crash upon entering a sequence containing non-asciii characters

### ISSUE THREAD

**Issue by CoolElectronics** [nushell/nushell#8412]
### Describe the bug

Entering any non-ascii character followed by 2 exclamation points crashes nushell

### How to reproduce

1. Open nushell
2. Paste in the characters `は!!`
3. Press enter

### Expected behavior

I expected nu to be able to handle strings containing non-ascii characters

### Screenshots

```
/home/ce/Documents/clamide〉は!!thread 'main' panicked at 'byte index 1 is not a char boundary; it is inside 'は' (bytes 0..3) of `は!!`', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/reedline-0.14.0/src/menu/menu_functions.rs:74:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.74.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 9a56665c6beee31e365ce17898056f1ff2db4094                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.66.0 (69f9c33d7 2022-12-12) (Arch Linux rust 1:1.66.0-1) |
| cargo_version      | cargo 1.66.0                                                     |
| pkg_version        | 0.74.0                                                           |
| build_time         | 2023-01-10 22:53:04 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | database, dataframe, default, trash, which, zip                  |
| installed_plugins  |                                                                  |

### Additional context

This doesn't only affect the "last command" expansion, strings containing this sequence (example: `echo "〉!!"`) also crash

**Comment by sholderbach** [comment]
Yeah that sounds like indexing ignoring multibyte chars in the reedline bashism feature...
