### ISSUE TITLE
stdlib assert consistency

### ISSUE THREAD

**Issue by presidento** [nushell/nushell#8418]
### Describe the bug

The type checking causes confusion:
```
❯ assert ( 1 == 1.0) # passes
❯ assert eq 1 1.0    # makes an error
```
And:
```
❯ assert ( 1 != "a string" ) # passes
❯ assert ne 1 "a string"     # makes an error
```

### How to reproduce

```nushell
from std.nu use *
assert ( 1 == 1.0)         # passes
assert eq 1 1.0            # makes an error
assert ( 1 != "a string" ) # passes
assert ne 1 "a string"     # makes an error
```

### Expected behavior

I think
- `assert ( $a == $b )` should have exactly the same behaviour as `assert eq $a $b`, similarly
- `assert ( $a != $b )` should have exactly the same behaviour as `assert ne $a $b`.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.76.0                                   |
| branch             |                                          |
| commit_hash        | bc38a6a795f438ab1465dd987adf92efd9530529 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)      |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)      |
| pkg_version        | 0.76.0                                   |
| build_time         | 2023-02-23 08:03:29 -06:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

### Additional context

This is a follow-up issue from #8405. Involve @kubouch @fdncred @amtoine @bobhy.

**Comment by amtoine** [comment]
@presidento 

that makes perfect sense put that way :open_mouth: 
this is inconsistent!

i agree on the "expected behaviour" you put propose :+1: 

thanks for tracking this :relieved:

**Comment by amtoine** [comment]
maybe this should wait for #8405 before working on it? :thinking:

**Comment by presidento** [comment]
Yes. If I am allowed to do this change, I will do it after the existing PRs have a stabile state. (Merged or postponed.)

**Comment by amtoine** [comment]
> Yes. If I am allowed to do this change, I will do it after the existing PRs have a stabile state. (Merged or postponed.)
>
ehe, you know what, #8405 has just been merged, i think that's a good time to work on this!

please go ahead :star_struck:
