### ISSUE TITLE
Naming conventions for assert commands

### ISSUE THREAD

**Issue by presidento** [nushell/nushell#8419]
### Related problem

I like the Nushell naming convetion, I mean here we do not use abbreviations too much. For example we have `str substring`, not `str substr`. And so on.

### Describe the solution you'd like

Follow the existing naming convention for `assert` commands in `std.nu`, while keep the Rust-like abbeviations as aliases. For example have (with alias):
- `assert equal` (alias `assert eq`)
- `assert not equal` (alias `assert neq`)
- `assert less-or-equal` (alias `assert lte`)
- etc.

### Describe alternatives you've considered

Some languages use the abbreviated names for assertions, some use full names. I think with Nushell the full name is more natural.

### Additional context and details

This is a follow-up issue from https://github.com/nushell/nushell/pull/8405#issuecomment-1464949292. Involve @amtoine.

I'll send a PR if we can agree on this.

**Comment by amtoine** [comment]
> Some languages use the abbreviated names for assertions, some use full names. I think with Nushell the full name is more natural.
> 
i agree with this :+1: 
`nushell` might be a bit verbose sometimes, but gains with its completion and in readability :muscle: 

and as it's a simple change, i think there's no harm in seing how it works with people :wink:

**Comment by presidento** [comment]
Thank you, I'll do it soon, when it is appropriate.

**Comment by presidento** [comment]
@amtoine Can we even have an alias for a command in a module?

Let's have a `mymodule.nu` file with:
```
export def mycommand [] { "Hello" }
export alias myalias1 = mymodule mycommand
export alias myalias2 = mycommand
```

None of these alias can be used universally:

```
❯ nu -c 'use mymodule.nu *; mycommand; myalias2; myalias1'
Hello
Hello
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[source:1:1]
 1 │ use mymodule.nu *; mycommand; myalias2; myalias1
   ·                                         ────┬───
   ·                                             ╰── did you mean 'module'?
   ╰────
  help: program not found
```

And

```
❯ nu -c 'use mymodule.nu; mymodule mycommand; mymodule myalias1; mymodule myalias2'
Hello
Hello
Error: nu::shell::external_command (link)

  × External command failed
   ╭─[source:1:1]
 1 │ use mymodule.nu; mymodule mycommand; mymodule myalias1; mymodule myalias2
   ·                                                         ────────┬────────
   ·                                                                 ╰── command 'mycommand' was not found but it was imported from module 'mymodule'; try using `mymodule mycommand`
   ╰────
  help: program not found
```

**Comment by amtoine** [comment]
it appears not :thinking: 
i'm having the same kind of errors!

**Comment by amtoine** [comment]
i'd drop the `alias` idea for now and let the user do it.

in the meantime, that might give a nice improvement in a feature request :wink:
