### ISSUE TITLE
`use` command not picking up current environment definition?

### ISSUE THREAD

**Issue by bobhy** [nushell/nushell#8422]
### Describe the bug

I'm trying to enhance my prompt, using functions I'm trying to import from `dirs.nu`.  But I'm finding the `use` command being not picking up on environment variable changes done within the same script..

### How to reproduce

I'm making small changes to the default `env.nu`.
```nushell
# ---------vvv----- define environment variable needed to locate modules, here.
let-env NU_LIB_DIRS = [ ($nu.config-path | path dirname | path join 'scripts') ]
use dirs.nu    # <-- use new module which is located in NU_LIB_DIRS path

def create_center_prompt [] {
    ...
    # this depends on `use dirs.nu` above to have defined `$env.DIRS_LIST`
    # ------------vvv------ depend on newly-loaded module here ---- 
    $" |($env.DIRS_LIST | reduce --fold '' {|it, acc| $acc + (if $it == $env.PWD {'V'} else {'.'})})| "
   ...
}

let-env PROMPT_COMMAND = { let t = create_center_prompt []; print $t; '' }
```

When I start a new shell, I get this error:
```
 Error: nu::parser::module_not_found

  × Module not found.
    ╭─[/home/bobhy/.config/nushell/env.nu:23:1]
 23 │ 
 24 │ use dirs.nu
    ·     ───┬───
    ·        ╰── module not found
 25 │ 
    ╰────
  help: module files and their paths must be available before your script is run as parsing occurs before anything
        is evaluated
```

### Expected behavior

This doesn't seem to be the usual case that you cannot compute the use path from a variable in the script, e.g you cannot do:
```
let t = "/path/to/module.nu"
use $t
```

In my case, I execute a `let-env NU_DIRS_LIB`, which I expect to take effect as soon as it is executed.
Then later in the same script, I execute `use foo.nu`, which I expect will do a path search along the list of directories defined in `$env.NU_DIRS_LIB`.  

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.76.1                                   |
| branch             | main                                     |
| commit_hash        | e435196956b7f464c7d4cd18b73211471a89d907 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-03-11 00:04:44 -05:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

### Additional context

If I move the `use dirs.nu` to `config.nu`, it then loads the module correctly, and I can immediately invoke its functions in that same script.  

But I'd rather have the `let-env` / `use` pattern work within one script, I don't see a logical reason that it shouldn't work.

**Comment by kubouch** [comment]
That's because `use` requires the path to be in place during parsing, the NU_LIB_DIRS is modified only after parsing during eval. You need to move `use dirs.nu` to a next parse-eval cycle, e.g., if NU_LIB_DIRS is defined in env.nu, move it to config.nu.

After https://github.com/nushell/nushell/pull/8310 lands, you'll be able to define NU_LIB_DIRS as a parse-time constant which will resolve your issue.

**Comment by bobhy** [comment]
It sounds like that will work, assuming:
1. I can use what I'd normally consider a run-time expression like: ` ($nu.config-path | path dirname | path join 'scripts') ` to compute the value for `const NU_LIB_DIRS`.
2. I can also *export* the const environment variable.
I'll give this a try when the feature lands.
