### ISSUE TITLE
Precedence of `=` vs '|'

### ISSUE THREAD

**Issue by bobhy** [nushell/nushell#8429]
### Related problem

I bet this is a FAQ, but it's a frustratingly common mistake this n00b makes, so maybe it's worth raising yet again?
You can't assign the value of a pipeline to a variable without adding a seemingly redundant pair of parens.
```nushell
Error: nu::parser::unexpected_keyword

  × let statement used in pipeline.
     ╭─[/home/bobhy/.config/nushell/config.nu:675:1]
 675 │   if $git_run.exit_code != 0 {return ""}
 676 │   let git_status = $git_run.stdout | lines
     ·   ─┬─
     ·    ╰── 'let' in pipeline
     ╰────
  help: Assigning '$git_run.stdout' to 'git_status' does not produce a value to be piped. If the pipeline result is meant to be
        assigned to 'git_status', use 'let git_status = ($git_run.stdout | ...)'.
```
It appears that the assignment operator `=` binds more tightly than the pipeline operator `|`.  

### Describe the solution you'd like

I'd like the assignment operator '=' to evaluate its whole right-hand side and assign the result to the variable on the lhs.  It should not need parenthesis to force the order of evaluation.

### Describe alternatives you've considered

If the precedence of operators can't be changed, could we at least change this uncharacteristically pedantic error message?  Maybe it could be shortened to: "no value to pipeline operator.  Did you mean ...?"

**Comment by bobhy** [comment]
Closing due to no traction.

**Comment by ThinkChaos** [comment]
I would like to see this :)

**Comment by ThinkChaos** [comment]
Turns out it's happened since the last release!  
See #13385
