### ISSUE TITLE
Re-evaluate design of multiplication on strings and lists

### ISSUE THREAD

**Issue by jmoore34** [nushell/nushell#8436]
### Related problem

I've been playing around with #8061 since it was released and I think it's really convenient to use. In particular, I like how it gives a common interface to multiply across both strings and lists (rather than separate commands for each).

Recently, though, I've found that sometimes I will be working with data in which numbers can be encoded as strings, in which case this can become a bit of a footgun when writing scripts. This is especially the case given numbers and string-encoded numbers appear the same in tables, external command outputs, and so on.

```sh
~
❯  let input = {a: 5, b: "4"}

~
❯  $input
╭───┬───╮
│ a │ 5 │
│ b │ 4 │
╰───┴───╯

~
❯  $input.a * 2; $input.b * 2
10
44
```

There are ways to deal with this, but I'd prefer the typechecker to proactively call me out on this so I don't end up surprised.

### Describe the solution you'd like

1. Add a `duplicate` command (another possible name: `repeat`) which provides the same semantics as the feature introduced in #8061 -- i.e., so that there is still a convenient way to duplicate values for both strings and lists. E.g., `"a" | duplicate 3`, `[1 2 3] | duplicate ($in | length)`
2. When used on a string or list, make the `*` operator instead error and give a hint telling the user to use `duplicate`. That way, people coming from Python can easily discover it.

### Describe alternatives you've considered

We could make tables indicate whether a value is a number or a string-encoded number, but I think this could be easy to miss if you're working fast or are new to nushell. I think having to keep in mind extra rules of what not to accidentally do increases cognitive load to some extent, and I'd rather offload worrying about whether I made a mistake to the type checker.

**Comment by sholderbach** [comment]
I think the list behavior is even more surprising as scalar multiplication of a vector/list is something well defined.

**Comment by weirdan** [comment]
Multiplication doesn't work on strings anymore. There's `repeat` in `std` with a slightly different semantics - it always produces lists.

**Comment by sholderbach** [comment]
Oops that was me in https://github.com/nushell/nushell/pull/10292 and https://github.com/nushell/nushell/pull/10293, forgot to close
