### ISSUE TITLE
nu::parser::extra_positional on a clean v0.76 install + startup

### ISSUE THREAD

**Issue by nyurik** [nushell/nushell#8442]
### Describe the bug

Unable to get nu started

### How to reproduce

1. `cargo install nu`
2. nu

### Expected behavior

i expected nu to start, possibly after describing a lot of errors

### Screenshots

```
❯ nu
No environment config file found at /home/nyurik/.config/nushell/env.nu
Would you like to create one with defaults (Y/n):
y
Environment config file created at: /home/nyurik/.config/nushell/env.nu
Error: nu::parser::extra_positional (link)

  × Extra positional argument.
    ╭─[/home/nyurik/.config/nushell/config.nu:63:1]
 63 │   def "nu-complete git branches" [] {
 64 │     ^git branch | lines | each { |line| $line | str find-replace '\* ' '' | str trim }
    ·                                                                  ──┬──
    ·                                                                    ╰── extra positional argument
 65 │   }
    ╰────
  help: Usage: str find-replace

Error:
  × No such file or directory (os error 2)
```

-----
after commenting out line 64 above

```
warning: use `let-env config = ...` instead of `let config = ...`
Error:
  × No such file or directory (os error 2)
```

### Configuration

unable to start nu, quits right away

**Comment by fdncred** [comment]
str find-replace hasn't been a thing for several releases now. So, it looks to me like and old config is being loaded.

**Comment by nyurik** [comment]
@fdncred I never used nu before - notice that it was creating a new config file:

```
❯ nu
No environment config file found at /home/nyurik/.config/nushell/env.nu
Would you like to create one with defaults (Y/n):
y
```

**Comment by nyurik** [comment]
hmm, that did give me an idea - i renamed the ~/.config/nushell - and re-ran, and it did regenerate both files this time, not just env.nu... i wonder why i had the old config around. thx!
