### ISSUE TITLE
standard library tests does not run

### ISSUE THREAD

**Issue by presidento** [nushell/nushell#8444]
### Describe the bug

The readme of the standard library states:

### :test_tube: run the tests
the following call should return nothing
```bash
nu ($env.STD_LIB | path join "tests.nu")
```

And there is no `$env.STD_LIB` by default.

### How to reproduce

```
❯ nu ($env.STD_LIB | path join "tests.nu")
Error: nu::shell::column_not_found (link)

  × Cannot find column
   ╭─[entry #44:1:1]
 1 │ nu ($env.STD_LIB | path join "tests.nu")
   ·     ──┬─ ───┬───
   ·       │     ╰── cannot find column 'STD_LIB'
   ·       ╰── value originates here
   ╰────
```

### Expected behavior

Change the documentation or set `$env.STD_LIB` automatically.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.76.0                                   |
| branch             |                                          |
| commit_hash        | bc38a6a795f438ab1465dd987adf92efd9530529 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)      |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)      |
| pkg_version        | 0.76.0                                   |
| build_time         | 2023-02-23 08:03:29 -06:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

**Comment by amtoine** [comment]
the `README` was designed to be read from start to end as it's quite small for now :yum: 

would adding something like "with the `STD_LIB` environment variable defined above" and then the actual command be easier to understand and less error prone?

**Comment by amtoine** [comment]
@presidento 

> set `$env.STD_LIB` automatically
>
for now we can not set this automatically because, in my example, `STD_LIB` is just a shorthand of the full path to the `std.nu` file, which won't be at the same place from one machine to another :confused: 

i think the best, at least for now, is to mention `STD_LIB` has being defined "above in the document", maybe with a clickable link, because this section of the document is meant for developers, i.e. people who will have the source locally and who will be able to define `STD_LIB` safely :yum:

**Comment by presidento** [comment]
I think it would be useful to show the development status of this codebase. I think to be a _standard_ library it needs to be shipped with Nushell and be as easy to use as `use std.nu` without any further configuration. So I think at the moment it is in _alpha_ stage.

It can be _beta_ when it has an installation guide in the readme with at least a step-by-step guide, including at least semi-automated upgrade instructions.

At current state I suggest using `nu /path/to/standard_library/tests.nu`.

I do not know why it is needed to have `STD_LIB` environment variable to _use_ standard library. This folder just can included in `NU_LIB_DIRS` variable somehow, so we can just `use std.nu`. (I haven't tested it, just read the documentation.) For developing standard library it is enough to cd into the folder.

But they are just my preferences. Thank you for letting me explain my thoughts. 😊
