### ISSUE TITLE
tilde expansion when running via function stopped working

### ISSUE THREAD

**Issue by harrysarson** [nushell/nushell#8451]
### Describe the bug

Tilde expansion no longer happens when running an external command inside a nushell function.

Running the external command directly works fine but not when I wrap it in a function.

Git bisect thinks that the guilty commit is 5419e8ae9d1ca3b4e22fc4016012eb80ef8f01ff. Which certainly looks relevant.

Practially this causes an error for me because I have a bash script I run within a nushell function that tries to open a file specified on the command line. I get an error along the lines of `file ~/hello not found`.

### How to reproduce

Run 

```
# 1
nu -c "def s [f] { bash -c 'echo $0' $f }; s ~/hello"

# 2
nu -c "def s [f] { ^cat $f }; s ~/hello"
```

#### 1

I expect nu to print `/home/user/hello` (as it did in 0.74.0) but instead it prints `~/hello`.

#### 2

I expect nu to read the file `/home/user/hello` instead it fails with

```
cat: '~/hello': No such file or directory
```

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.76.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | bc38a6a795f438ab1465dd987adf92efd9530529                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07) (Arch Linux rust 1:1.67.1-1) |
| cargo_version      | cargo 1.67.1                                                     |
| pkg_version        | 0.76.0                                                           |
| build_time         | 2023-03-11 12:33:03 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | database, dataframe, default, trash, which, zip                  |
| installed_plugins  |                                                                  |

**Comment by WindSoilder** [comment]
Hi, sorry for late reply.  I think for the case, you need to use `path expand` to expand variable explicitly, it's consistent with `glob` rules today, and it's the same to `zsh`/`fish` behavior

```nushell
# 1
nu -c "def s [f] { bash -c 'echo $0' ($f | path expand) }; s ~/hello"

# 2
nu -c "def s [f] { ^cat ($f | path expand) }; s ~/hello"
```
I'll close the issue for now, feel free to re-open it if
