### ISSUE TITLE
Cursor style is overridden when exiting nushell

### ISSUE THREAD

**Issue by scallaway** [nushell/nushell#8452]
### Describe the bug

For all my terminals, I have the cursor set to the block-style at all times.

When I enter nushell, the default is to have the cursor in line-style.

However, when I exit nushell, the terminal continues to use the line-style for the cursor in the current session.

I have confirmed this is both the case with Kitty terminal on linux and Windows terminal (with WSL) on Windows 11.

### How to reproduce

This is easiest to see when you have a `tmux` instance open (so you can compare).

1. Update the config for your terminal to use block-style cursors
2. Open a session of nushell
3. Verify that the cursor is line-style (by default)
4. Exit the session
5. See that the cursor remains in the line-style

It's worth noting at this point that if you open another tmux session, then the cursor style is as you originally configured (block-style in my case).

### Expected behavior

I'd expect the cursor style to _not_ be overridden once you've exited a nushell session.

### Screenshots

![image](https://user-images.githubusercontent.com/16577635/225121388-b4653384-c208-4bab-9278-8a9e3234781c.png)
> Before booting into a shell

![image](https://user-images.githubusercontent.com/16577635/225121459-3381def8-9609-455f-a629-144e665063bf.png)
> inside the shell session

![image](https://user-images.githubusercontent.com/16577635/225121526-37c12343-7c3b-4cdf-a2d8-1a1a4e5d83de.png)
> outside the session after exit

### Configuration

```
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.77.0                                   |
| branch             | main                                     |
| commit_hash        | fd09609b44b53d41ac7929e90708cdeba7bfb571 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-03-14 19:46:05 +00:00               |
| build_rust_channel | debug                                    |
| features           | default, zip                             |
| installed_plugins  |                                          |
```

**Comment by fdncred** [comment]
You can change your cursor shape in the config file like this
```
let-env config = {
... other stuff
    cursor_shape: {
        emacs: line # block, underscore, line (line is the default)
        vi_insert: block # block, underscore, line (block is the default)
        vi_normal: underscore # block, underscore, line  (underscore is the default)
    }
}
```

**Comment by aetherplex** [comment]
Is it possible to change the default cursor to block?

**Comment by fdncred** [comment]
> Is it possible to change the default cursor to block?

I don't understand @aetherplex, I explained how to change it in the comment above yours. Am I misunderstanding your question?

**Comment by aerique** [comment]
I have something similar which may or may not have the same cause: I'm playing around with nushell, trying it out, changing some config options, launching it and exiting it again. This is all from Fish shell. In Fish my cursor is a solid block, in nushell I configured it to be a solid block as well but:

When I exit nushell to Fish my cursor is a blinking solid block so I run it like this now `nu ; echo -en '\e[2 q'`.

I do not have this issue with any other programs I launch from Fish, including my own shell I'm developing.

**Comment by mb21** [comment]
Seems [crossterm has now a function to get cursor shape](https://github.com/crossterm-rs/crossterm/issues/646) so nushell could use that to restore the cursor before exit?

**Comment by fdncred** [comment]
I don't see the function. Is it in crossterm or just in someone's fork?

**Comment by fdncred** [comment]
closing since #10289 landed. let's open a new issue if there are still problems.
