### ISSUE TITLE
"Error: Io(Kind(InvalidData))" raised if press and hold Enter key.

### ISSUE THREAD

**Issue by Cykooz** [nushell/nushell#846]
[![asciicast](https://asciinema.org/a/chkcbVBLCzQZGx80eLsRbE1ix.svg)](https://asciinema.org/a/chkcbVBLCzQZGx80eLsRbE1ix)

**Comment by jonathandturner** [comment]
Thanks for the report. After some investigation, it looks like the problem is in the crate we use to read the line.

I've filed this on the dependency. Once they fix it, we'll pull in their update: https://github.com/kkawakam/rustyline/issues/291
