### ISSUE TITLE
move multiple files across directories

### ISSUE THREAD

**Issue by 0323pin** [nushell/nushell#8461]
### Related problem

I've used `nu` from 0.34.0 through to 0.44.0 and I really enjoyed it.
To me there's one single annoyance that disturbs my work-flow and the sole reason for not using `nu` as my default shell.

I often need to move multiple files across directories, moving them one-by-one is not an option as it disrupts flow. This works on other shells but it doesn't seem to be possible in `nu`. Am I missing something?

Just an example to illustrate what I mean,

```
~> mkdir Test1                                                                                                                                                         03/15/2023 09:58:00 AM
~> mkdir Test2                                                                                                                                                         03/15/2023 09:58:21 AM
~> cd Test1/                                                                                                                                                           03/15/2023 09:58:25 AM
~/Test1> touch testA                                                                                                                                                   03/15/2023 09:58:28 AM
~/Test1> touch testB                                                                                                                                                   03/15/2023 09:58:34 AM
~/Test1> touch testC                                                                                                                                                   03/15/2023 09:58:38 AM
~/Test1> mv testA testB testC /home/pin/Test2                                                                                                                          03/15/2023 10:01:03 AM
Error: nu::parser::extra_positional

  × Extra positional argument.
   ╭─[entry #13:1:1]
 1 │ mv testA testB testC /home/pin/Test2
   ·                ──┬──
   ·                  ╰── extra positional argument
   ╰────
  help: Usage: mv {flags} <source> <destination>

~/Test1>                                                                                                                                                               03/15/2023 10:01:22 AM
```

Any thoughts? 

### Describe the solution you'd like

Be able to move multiple files across directories.

### Describe alternatives you've considered

Move them one-by-one, not ideal and disruptive.

**Comment by WindSoilder** [comment]
Currently the workaround is `[testA testB testC] | each {|$it| mv $it /home/pin/Test2/}`

It's a little bit verbosing, but I think it's more clear

**Comment by 0323pin** [comment]
Thank you for your workaround, appreciated.

Unfortunately, this is too verbose. I'm a package maintainer and need to move a large number of files from my test environment on my machine to the main branch on our servers.
Doing this is ok for sporadic use, not in my use case.

Thanks anyway.

**Comment by colemickens** [comment]
I agree this is a bit verbose. I pop back to zsh to move files around. :frowning_face:

**Comment by 0323pin** [comment]
Yeah, that works. Did this for sometime in the past using `ksh`.
The ultimate solution though, would be for this to work without workaround.

**Comment by mati865** [comment]
The best workaround is probably to use system's `mv` command:
```sh
^mv a b c/
```

**Comment by berkgercek** [comment]
Is there any movement on this? Fitting `mv`, `cp`, `rm`, etc into nu pipelines seems like a big necessity for the language to work "as expected" to new users. This was an immediate pain point for me as I'm just starting to use the shell.

**Comment by weirdan** [comment]
This works now:

```console
$ mkdir Test1

$ mkdir Test2

$ cd Test1

$ touch testA testB testC

$ mv testA testB testC ../Test2/

$ ls
╭────────────╮
│ empty list │
╰────────────╯

$ ls ../Test2
╭───┬────────────────┬──────┬──────┬────────────────╮
│ # │      name      │ type │ size │    modified    │
├───┼────────────────┼──────┼──────┼────────────────┤
│ 0 │ ../Test2/testB │ file │  0 B │ 25 seconds ago │
│ 1 │ ../Test2/testA │ file │  0 B │ 25 seconds ago │
│ 2 │ ../Test2/testC │ file │  0 B │ 25 seconds ago │
╰───┴────────────────┴──────┴──────┴────────────────╯
```
