### ISSUE TITLE
`http` subcommands should return headers and status codes

### ISSUE THREAD

**Issue by JakeUrban** [nushell/nushell#8468]
### Related problem

I'm a big fan of the `http` commands because it lets me access & visualize the response body as structured data. However, there have been several occasions where I'm forced to use `curl` which is frustrating.

Unsuccessful requests (4XX, 5XX) return a nushell error instead of the typical structured response body. The response body often includes the reason for which the request failed, but nushell hides this info. It even prevents me from bypassing this behavior using `--raw`, which is seems to ignore on 4XX or 5XX statuses. 

If I need access to a response header,  I can't use `http`. This just eliminates a whole set of use cases (checking content type, grabbing a session cookie, respecting rate-limit `Retry-After` headers, etc.)

### Describe the solution you'd like

Provide a way to access the whole response (headers included) even on 4XX and 5XX.

#### Option 1: Make a breaking change to the structured data returned by default

Before:

```nu
❯ http post http://localhost:8080/echo '{"foo": {"bar": "foobar"}}'
╭─────┬──────────────────╮
│     │ ╭─────┬────────╮ │
│ foo │ │ bar │ foobar │ │
│     │ ╰─────┴────────╯ │
╰─────┴──────────────────╯
```

After:

```nu
❯ http post http://localhost:8080/echo '{"foo": {"bar": "foobar"}}'
╭─────────────┬─────────────────────────────────────╮
│ status_code │ 200                                 │
│             │ ╭──────────────┬──────────────────╮ │
│ headers     │ │ Content-Type │ application/json │ │
│             │ ╰──────────────┴──────────────────╯ │
│             │ ╭─────┬──────────────────╮          │
│ body        │ │     │ ╭─────┬────────╮ │          │
│             │ │ foo │ │ bar │ foobar │ │          │
│             │ │     │ ╰─────┴────────╯ │          │
│             │ ╰─────┴──────────────────╯          │
╰─────────────┴─────────────────────────────────────╯
```

#### Option 2: Add an option for the "full" response (or another name)

```nu
❯ http post --full http://localhost:8080/echo '{"foo": {"bar": "foobar"}}'
╭─────────────┬─────────────────────────────────────╮
│ status_code │ 200                                 │
│             │ ╭──────────────┬──────────────────╮ │
│ headers     │ │ Content-Type │ application/json │ │
│             │ ╰──────────────┴──────────────────╯ │
│             │ ╭─────┬──────────────────╮          │
│ body        │ │     │ ╭─────┬────────╮ │          │
│             │ │ foo │ │ bar │ foobar │ │          │
│             │ │     │ ╰─────┴────────╯ │          │
│             │ ╰─────┴──────────────────╯          │
╰─────────────┴─────────────────────────────────────╯
```

Failed request example:

```nu
❯ http post --full http://localhost:8080/echo '{"foo": {"bar": "foobar"}}'
╭─────────────┬─────────────────────────────────────╮
│ status_code │ 403                                 │
│             │ ╭──────────────┬──────────────────╮ │
│ headers     │ │ Content-Type │ application/json │ │
│             │ ╰──────────────┴──────────────────╯ │
│             │ ╭───────┬───────────────────╮       │
│ body        │ │ error │ permission denied │       │
│             │ ╰───────┴───────────────────╯       │
╰─────────────┴─────────────────────────────────────╯
```

**Comment by ryand67** [comment]
I'd love to give this a shot :)

**Comment by fdncred** [comment]
I assigned it to you @ryand67. have fun!

**Comment by ryand67** [comment]
Sorry for the delay, had surgery recently, but it seems that this feature might've been covered by this pr here? Unless I'm missing something. https://github.com/nushell/nushell/pull/8571

**Comment by fdncred** [comment]
ya, it's similar. we can close this for now.

**Comment by JakeUrban** [comment]
Amazing! Looking forward to the next release.
