### ISSUE TITLE
Case sensitivity in 'where'

### ISSUE THREAD

**Issue by thomasheartman** [nushell/nushell#849]
Hey,

The `where` command is case sensitive both for column names and values. Could there be a way to make it ignore case, especially in column names? I find that when working with generated data, column names often come out in all caps, so the filtering needs to use all caps too, which, while no big deal, is a little annoying. 

Would it be an idea to have a flag to make the command case insensitive? I'm thinking primarily about the column names, though the values could also be matched case insensitively.

This might cause issues if you have two columns names that only differ in casing, though, so I don't know whether that's doable or desirable.

**Comment by jonathandturner** [comment]
I have mixed feelings. Mostly because data sources, with the exception of something like Windows filenames, are all going to be case sensitive for fields. 

That said, it might make sense to have a relaxed mode, or to at least have a forgiving autocomplete, when we add that.

**Comment by t-hart** [comment]
Yeah, I can see your point about data sources often being case sensitive. That said, SQL tends to be insensitive, doesn't it? I don't think it should be the default, but a relaxed mode / ignore-case flag could be a good idea. 

The forgiving auto-complete might also be enough. Fish shell does this for paths on case sensitive file systems and that works great.

**Comment by cig0** [comment]
Hi all,

I believe that Nu really needs to allow the user to query for an insensitive case, similar as we can do with `grep -i`.

A typical example would be to look for some file or process id, when you don't know exactly how that process is called or spelled (is it written in uppercase, lowercase, camelCase?), i.e.:

![image](https://user-images.githubusercontent.com/394089/80835537-5e991700-8bc9-11ea-9050-53b806c7ad3a.png)

Thanks

**Comment by thegedge** [comment]
We'll need to think about the syntax for a simplified version of this, but here's an example of what you can do for now:

```
ps | str --downcase name | where name =~ ...
```

Of course, if you care about the case for the end result, there's not really an option right now (or nothing I can think of).

**Comment by onsamyj** [comment]
Can we have something like `{some data} | ignore-case | where name like cat` that would return `cat`, `Cat`, `CAT`, etc?

Nushell is about data. Nushell is about pipes. That makes sense to me.

**Comment by tim-mccarthy** [comment]
`where name =~ "(?i)^cat$"` would get the desired effect.

**Comment by onsamyj** [comment]
It, will, you’re not wrong, but, and you can argue it’s a silly argument, it doesn’t feel like the Nushell way. Some other programs would probably have a `--flag`, which also feels weird here.

I was trying to come up with something that would feel natural here. Just a suggestion though.
