### ISSUE TITLE
new alias prevents to define git checkout -b

### ISSUE THREAD

**Issue by aserowy** [nushell/nushell#8494]
### Describe the bug

Before the new update shipped i could define

```nu
alias gcob = git checkout -b
```

after the update i'll get the following message registering my aliases

```sh
Error: nu::parser::missing_flag_param

  × Missing flag argument.
   ╭─[git-aliases.nu:3:1]
 3 │ alias gco = git checkout
 4 │ alias gcob = git checkout -b
   ·                           ─┬
   ·                            ╰── flag missing string argument
 5 │ alias gb = git branch
   ╰────
```

### How to reproduce

1. add alias to config.nu
2. restart terminal

### Expected behavior

The alias should not be affected by the alias changes.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.77.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07) (built from a source tarball) |
| cargo_version      | cargo 1.67.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

### Additional context

No context, but a place to thank you for this awesome shell! nushell is <3

**Comment by kubouch** [comment]
This currently work as designed, and is one limitation that we forgot to mention. The aliased call needs to be a valid call, except that only missing positional arguments are allowed. But flags that take an argument must either be defined fully inside the alias or left outside the alias, you can't "chop" the flag and it's value like you attempted to.

It might be possible to allow this in the future but it might be quite complex to get right and I'm unsure the benefit is that high.

**Comment by aserowy** [comment]
ty for the response. 

```nu
alias gcmsm = git commit -s -m
```

is working on the other hand.

Why should nushell validate if an alias is a valid call on its own?

**Comment by GregCornis** [comment]
I had the same issue, and resolved by using a custom function rather than an alias. It looses the completion though
```nu
def gcob [ref: string] { git checkout -b $ref }
```
