### ISSUE TITLE
Strings won't be printed in some cases

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#8495]
### Describe the bug

Strings won't be printed in some cases

### How to reproduce

```bash
# a.nu

'Line 1'
$'Line 2'
$'Line 3'
$'(char nl)Line 5!(char nl)'

```
run `nu a.nu` will get:
```console

Line 5!
```

### Expected behavior

Expected output:
```
Line 1
Line 2
Line 3

Line 5!

```
just the same as running the following script:
```bash
print 'Line 1'
print $'Line 2'
print $'Line 3'
print $'(char nl)Line 5!(char nl)'

```

### Configuration

| key                | value                                                                                       |
| ------------------ | ------------------------------------------------------------------------------------------- |
| version            | 0.77.1                                                                                      |
| branch             | main                                                                                        |
| commit_hash        | 1552eb921ab2f54a570523d3c7167bbc6ccc7cd6                                                    |
| build_os           | macos-x86_64                                                                                |
| build_target       | x86_64-apple-darwin                                                                         |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)                                                         |
| rust_channel       | stable-x86_64-apple-darwin                                                                  |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)                                                         |
| build_time         | 2023-03-17 14:54:28 +08:00                                                                  |
| build_rust_channel | release                                                                                     |
| features           | default, zip                                                                                |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, inc, query, query json, query web, query xml |

### Additional context

I have just build from the latest main branch with commit hash: 1552eb921

**Comment by WindSoilder** [comment]
I think it works as expected because of https://github.com/nushell/nushell/pull/8292/

**Comment by hustcer** [comment]
@WindSoilder even `echo` doesn't work either:
```bash
echo 'Line 1'
echo $'Line 2'
echo $'Line 3'
echo $'(char nl)Line 5!(char nl)'
```
Is that by design too?

**Comment by WindSoilder** [comment]
Yup, here is status update message from discord:

> To force a pipeline to print to the screen, use the print command. The echo command retains its job to send values into the pipeline but will not print values in a way that shells like bash do.
