### ISSUE TITLE
add a command/flag to quickly cd to git root

### ISSUE THREAD

**Issue by adsick** [nushell/nushell#8498]
### Related problem

I want a built-in command that allows to quickly cd to my current git root directory. 

### Describe the solution you'd like

It can be a flag of the existing and well known `cd` command.

for example
```nu
cd -r
```

### Describe alternatives you've considered

Separate command to do this sorts of stuff/not implementing it at all.

Another option is to allow overriding what `/`, `-` or `~` does in cd context (I don't use them that much)

**Comment by amtoine** [comment]
> This is what custom commands and/or aliases are for, right?
> 
agree :yum: 

i've written that independently as well for my needs
```rust
def-env "git root" [] {
    cd (git rev-parse --show-toplevel | str trim)
}
```

**Comment by sholderbach** [comment]
Following the same reasoning as in #8508 we shouldn't tie nushell directly to a VCS. Although `git` is quite ubiquituous, there is also Mercurial and a few other systems. Furthermore adding a direct dependency would bloat `nu` and expecting an installation of `git`, `hg` etc. is not great as well. So this should be addressed by either a small script as shown above or a VCS plugin that allows for tight coupling to e.g. git. (an example is `nu_plugin_gstat`)
