### ISSUE TITLE
add more flexibility to custom errors in `error make`

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8507]
### Related problem

i'm writing quite a lot of custom errors these days and i know we can construct one with

```bash
{
    msg: ...
    label: {
        text: ...
        start: ...
        end: ...
    }
}
```
giving something that looks like
```bash
Error:
  × <msg>
   ╭─[entry #1:1:1]
 1 │ something fishy
   ·           ──┬──
   ·             ╰── <label.text> from <label.start> to <label.end>
   ╰────
```

however, i see some built-in errors show more information, e.g.
- a true error, see the `nu::shell::directory_not_found` in
```bash
>_ ls jedklqwje
Error: nu::shell::directory_not_found

  × Directory not found
   ╭─[entry #81:1:1]
 1 │ ls jedklqwje
   ·    ────┬────
   ·        ╰── directory not found
   ╰────
```
- some help at the bottom, see the `no matches found` in 
```bash
>_ ls jed*
Error:
  × No matches found for jed*
   ╭─[entry #85:1:1]
 1 │ ls jed*
   ·    ──┬─
   ·      ╰── Pattern, file or folder not found
   ╰────
  help: no matches found
```

### Describe the solution you'd like

i think it would really push the `error make`ing one step forward to add a few extra possibilities to the error format

:one:
```bash
error make {
    error: "my_error"
    msg: "my_message"  # mandatory
    label: {
        text: "my label"  # mandatory
        start: ...  # not mandatory, unless label.end is given
        end: ...  # not mandatory, unless label.start is given
    }
    help: "my help"
}
```
would show
```bash
Error: my_error
  × my message
   ╭─[entry #1:1:1]
 1 │ something fishy
   ·           ──┬──
   ·             ╰── my label
   ╰────
  help: my help
```

:two:
```bash
error make {
    error: "my_error"
    msg: "my_message"
    label: {
        text: "my label"
    }
}
```
would not show the help at the bottom at all

:three: 
```bash
error make {
    msg: "my_message"
    label: {
        text: "my label"
    }
    help: "my help"
}
```
would not show the error at the top at all

:four: 
```bash
error make {
    msg: "my_message"
    label: {
        text: "my label"
    }
}
```
would behave as normal

**Comment by amtoine** [comment]
i had a look at `miette` and the `Diagnostic in `shell_error.rs`!

i tried to add a new `CustomError` to the `ShellError` enum in `shell_error.rs`
```rust
    /// This is a custom error type used for user-defined errors.
    #[error("{1}")]
    CustomError(
        #[diagnostic()] Option<String>,
        String,
        String,
        #[label("{2}")] Option<Span>,
        #[help] Option<String>,
        #[related] Vec<ShellError>,
    ),
```
to have it called as
```rust
ShellError::CustomError(
    Some("custom::my_error".to_string()),
    "my message".to_string(),
    "my label".to_string(),
    Some(Span::new(123, 456)),
    Some("my help".to_string()),
    Vec::new(),
)
```
and print
```bash
Error: custom::my_error
  × my message
   ╭─[source:1:1]
 1 │ something fishy
   ·           ──┬──
   ·             ╰── my label.text
   ╰────
  help: my help
```

:x: however the first argument, `"custom::my_error"` here, does not show up at all in the output
:heavy_check_mark: the rest shows up as expected

## :question: i have trouble understanding how `miette` works, any pointer on this? :yum:

**Comment by rgwood** [comment]
Good issue, thanks!

I'm not very familiar with Miette but the author ([Kat](https://github.com/zkat)) is in our Discord, might be worth asking her a question in #external-collab

**Comment by amtoine** [comment]
> I'm not very familiar with Miette but the author ([Kat](https://github.com/zkat)) is in our Discord, might be worth asking her a question in #external-collab
>
oooh that's a super idea! :ok_hand:

**Comment by zkat** [comment]
miette doesn't support providing error codes (the `custom::my_error`) part directly through the derive macro right now, so there's two alternatives:

1. Someone patches that into miette directly, to make it look in a particular field for an error code (or even allow for format strings like other declarations do), which I would be happy to merge
2. Make the CustomError variant a NewType that takes a separate CustomError struct that you manually implement Diagnostic on.

2 would look like this:

```rust
pub enum ShellError {
  ...
  #[error(transparent)]
  #[diagnostic(transparent)]
  CustomError(CustomError),
}

#[derive(Error)]
#[error("{message}")]
pub struct CustomError {
  pub code: Option<String>,
  pub message: String,
  pub severity: Option<miette::Severity>,
  pub help: Option<String>,
  pub url: Option<String>,
  pub source: Option<String>,
  pub labels: Option<Vec<LabeledSpan>>,
}

impl miette::Diagnostic for CustomError {
  fn code<'a>(&'a self) -> Option<Box<dyn Display + 'a>> {
    self.code.as_ref().map(Box::new)
  }
  ... etc
}
```

You'll want to implement all/most of the methods in [miette::Diagnostic](https://docs.rs/miette/latest/miette/trait.Diagnostic.html), and then you should be good to go!

**Comment by amtoine** [comment]
**can i be assigned to this?** :innocent: 
it's to keep track of the issues i really want to work on :relieved:

**Comment by amtoine** [comment]
looks to me like this is also addressed by https://github.com/nushell/nushell/pull/10923 :ok_hand:
