### ISSUE TITLE
ls in a vcs directory should use git changed date not file system date

### ISSUE THREAD

**Issue by hholst80** [nushell/nushell#8508]
### Related problem

I think it makes much more sense to see a files vcs change date rather than when it was cloned locally.

### Describe the solution you'd like

i'd like to see the vcs change date instead of the file system modified date.

**Comment by fdncred** [comment]
Seems like this would drag on the performance of `ls` so I probably wouldn't support that, but I could see a plugin with a functionality that would interrogate git for each file like `ls | gstat` and use that to output the date time you're looking for. Then you could perhaps setup an alias or custom command for that usage.

**Comment by rgwood** [comment]
This is a cool idea (thanks!) but I agree with @fdncred about the performance concerns and getting this right without embedding Git in Nushell would be tricky. Would be a nice plugin but we're probably not going to implement this in Nu itself.
