### ISSUE TITLE
Issue with find Command: Retaining Encoding When Piping Results

### ISSUE THREAD

**Issue by Phreno** [nushell/nushell#8512]
### Describe the bug

I recently discovered an issue with the find command in nushell where the output retains its encoding when piped through other functions. I'd like to report this issue and provide an example to illustrate the problem.

When running the following command:

`ls | find Bureau | get 0 | get name | to text | save data`

The content of da

### How to reproduce

ls | find <pattern> | get 0 | get name | to text | save data
hx data
# [1;34m[0m[41;37mpattern[0m[1;34m[0m

### Expected behavior

Release highlight when retrieving the value

### Screenshots

![issue find](https://user-images.githubusercontent.com/1321367/226109738-93151fa7-9ae2-4063-8e1e-d0788031e8f5.png)

![Capture d’écran du 2023-03-18 14-42-29](https://user-images.githubusercontent.com/1321367/226109791-a301662b-57d4-48e0-a097-ca76173fb03c.png)

### Configuration

| key                | value                                                                                  |
| ------------------ | -------------------------------------------------------------------------------------- |
| version            | 0.77.2                                                                                 |
| branch             | main                                                                                   |
| commit_hash        | 3f224db990f01b485695cd12dcd46d0db6276e5c                                               |
| build_os           | linux-x86_64                                                                           |
| build_target       | x86_64-unknown-linux-gnu                                                               |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)                                                    |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu                                                        || key                | value                                                                                  |
| ------------------ | -------------------------------------------------------------------------------------- |
| version            | 0.77.2                                                                                 |
| branch             | main                                                                                   |
| commit_hash        | 3f224db990f01b485695cd12dcd46d0db6276e5c                                               |
| build_os           | linux-x86_64                                                                           |
| build_target       | x86_64-unknown-linux-gnu                                                               |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)                                                    |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu                                                        |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)                                                    |
| build_time         | 2023-03-17 21:38:43 +01:00                                                             |
| build_rust_channel | release                                                                                |
| features           | default, zip                                                                           |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, query, query json, query web, query xml |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)                                                    |
| build_time         | 2023-03-17 21:38:43 +01:00                                                             |
| build_rust_channel | release                                                                                |
| features           | default, zip                                                                           |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, query, query json, query web, query xml |

**Comment by fdncred** [comment]
That "encoding" is the ansi escape sequences to color the hits. If you want to remove them you can use `ansi strip` like `ls | find Car | get 0.name | ansi strip | save blah`

**Comment by Phreno** [comment]
> That "encoding" is the ansi escape sequences to color the hits. If you want to remove them you can use `ansi strip` like
> 
> ```
> ls | find Car | get 0.name | ansi strip | save blah
> ```
> 
> or strip all the colors from that column like
> 
> ```
> ls | find Car | ansi strip name | get 0.name | save blah
> ```

Nice, works like a charm. 
Maybe add a line of doc about this in the documentation will be great.

**Comment by fdncred** [comment]
> Maybe add a line of doc about this in the documentation will be great.

We'd probably accept a PR in our docs repo for something like that.

Closing now.

**Comment by fdncred** [comment]
Agreed @zephraph, it's a papercut. However, I don't think we should arbitrarily decide that you everything after a pipe should be auto-stripped. For instance, maybe I want things highlighted with the `each` command like `git branch -r | find origin/HEAD main master | each {|r| $"Hit: ($r)"} | to text`. That seems valid to me.

I see a few things we could do.
1. You're 100% right that documentation is a good start.
2. We could have opt-in highlighting in find with a new flag like `-H` (we can't use `-h` because that's for help).
3. We could have opt-out highlighting in find with a new flag.
4. We could run `ansi strip` automatically when you pipe into a list of commands like `save`, but I probably wouldn't vote for that.
5. Another strategy?

I'd probably vote for 2 right now. I think we'd accept a PR for 1 & 2.

**Comment by Phreno** [comment]
I've done some pr about 1, adding an example, but maybe it not that great, and not as explicit as wanted (https://github.com/nushell/nushell/pull/8519).

6?. Maybe just an alias, leaving `find` with his highlight magic, and allowing to target results without fancy stuff.

**Comment by bgmort** [comment]
I got bit by this today too. I'd vote for having a flag to opt in or out. If it's possible to know whether the result is being piped when color is added, perhaps the default could depend on that, and only color by default when the result doesn't get piped.

**Comment by dead10ck** [comment]
Personally I don't think ANSI escape sequences should ever be piped. Most Linux programs that do any coloring at all will only do so when the output device is a tty, and if you really want to do this anyway, you have to opt into it, e.g. `cat foo | grep --color=always bar | less -R`. The reason is pretty obvious. If you pipe your output to a file , e.g. `cat foo | grep bar > out`, you probably don't want the escape sequences in there. But that's precisely what's happening in nushell.
