### ISSUE TITLE
`to json` cause the second to last element missing in lists

### ISSUE THREAD

**Issue by stephanoskomnenos** [nushell/nushell#8513]
### Describe the bug

```json
{
    "foo": [
        {
            "a": "1",
            "b": "1"
        },
        {
            "a": "2",
            "b": "2"
        },
        {
            "a": "3",
            "b": "3"
        }
    ]
}
```

```nu
let json = (open example.json | to json)
$json
```

Here is the output:
```
{
  "foo":
  [
    {
      "a": "1",
      "b": "1"
    },
    {
    },
    {
      "a": "3",
      "b": "3"
    }
  ]
}
```
In `$json.foo`, the `{"a": "2", "b": "2"}` is missing.
After several tests,  it seems that the missing element is always at the second-to-last position.

### How to reproduce

As described above.

### Expected behavior

As described above.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.77.1                                   |
| branch             |                                          |
| commit_hash        | 0120e4040d09f3bdffb945fa5fe450b72df7837a |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-03-17 05:17:52 +00:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I can't reproduce this.

With a minimized json
```
> open foo.json | to json -r
{"foo":[{"a": "1","b": "1"},{"a": "2","b": "2"},{"a": "3","b": "3"}]}
> open foo.json -r
{"foo":[{"a": "1","b": "1"},{"a": "2","b": "2"},{"a": "3","b": "3"}]}
> cat foo.json
{"foo":[{"a": "1","b": "1"},{"a": "2","b": "2"},{"a": "3","b": "3"}]}
> let f = (open foo.json | to json)
> $f
{
  "foo":
  [
    {
      "a": "1",
      "b": "1"
    },
    {
      "a": "2",
      "b": "2"
    },
    {
      "a": "3",
      "b": "3"
    }
  ]
}
```
With the json above
```
> let f = (open foo.json | to json)
> $f
{
  "foo":
  [
    {
      "a": "1",
      "b": "1"
    },
    {
      "a": "2",
      "b": "2"
    },
    {
      "a": "3",
      "b": "3"
    }
  ]
}
> cat foo.json
{
    "foo": [
        {
            "a": "1",
            "b": "1"
        },
        {
            "a": "2",
            "b": "2"
        },
        {
            "a": "3",
            "b": "3"
        }
    ]
}
> open foo.json -r
{
    "foo": [
        {
            "a": "1",
            "b": "1"
        },
        {
            "a": "2",
            "b": "2"
        },
        {
            "a": "3",
            "b": "3"
        }
    ]
}
> open foo.json | to json -r
{"foo":[{"a": "1","b": "1"},{"a": "2","b": "2"},{"a": "3","b": "3"}]}
```

**Comment by jntrnr** [comment]
I also can't repro. @stephanoskomnenos are you able to share the example file you're using?
