### ISSUE TITLE
Ability to use variables in std pipes

### ISSUE THREAD

**Issue by YummyOreo** [nushell/nushell#8517]
### Related problem

I'm trying to put something in my temp folder on windows using the `$env.TEMP` var. But this wont work using std pipes.

If I do something like this:
```bash
cat ./e.txt err> $"($env.TEMP)/e.txt"
```
I'll get this error
```bash
  × Command not found
   ╭─[entry #3:1:1]
 1 │ cat ./e.txt err> $"($env.TEMP)/e.txt"
   ·             ──┬─
   ·               ╰── command not found
   ╰────
```
But if I use a var:
```bash
let err_out = $"($env.TEMP)/e.txt"
cat ./e.txt err> $err_out
```

It will just make a file in the current dir called `$err_out`

### Describe the solution you'd like

Ability to use variables std pipes

### Describe alternatives you've considered

I could just make a temp folder in `~`.

**Comment by jntrnr** [comment]
@YummyOreo - what version of Nushell are you using?

**Comment by jntrnr** [comment]
Oh I think I see what might be happening. Redirection is meant for filenames. We could change it so that it runs the command and gives you a string to write to. String interpolation is converted into a command, which is what I think might be causing the issue.

**Comment by YummyOreo** [comment]
> @YummyOreo - what version of Nushell are you using?

Main

**Comment by YummyOreo** [comment]
> Oh I think I see what might be happening. Redirection is meant for filenames. We could change it so that it runs the command and gives you a string to write to. String interpolation is converted into a command, which is what I think might be causing the issue.

Yeah that would be awesome
