### ISSUE TITLE
Python virtualenv support?

### ISSUE THREAD

**Issue by lighth7015** [nushell/nushell#852]
Is there a way to enter a python *virtualenv* from nushell?

**Comment by jonathandturner** [comment]
I don't believe so. We're currently working on adding environment support, and this is a good test case for the kind of thing we should support.

**Comment by estysdesu** [comment]
So the wait is until `nu` supports temporary environments? Is this on the roadmap (is there a roadmap)?

**Comment by thegedge** [comment]
>  Is this on the roadmap (is there a roadmap)?

Not yet. For now, just some pinned issues in the repo. I'll chat with the team to see if we can better present what is priority for reaching 1.0 🙂

**Comment by mburszley** [comment]
I imagine this will need to tie into #291 and require engagement from pypa to integrate a nushell script into virtualenv.

**Comment by cjwyett** [comment]
Is this fixed? I still can't activate a python venv with `source myenv/bin/activate' like in other shells

**Comment by igitur** [comment]
It's not fixed. Overzealos github bots at it again. Please reopen, @jonathandturner .

**Comment by Tehada** [comment]
Also this seems like some kind support should be implemented from the virtualenv side, currently the first lines of `activate` file contain this message:
```
# This file must be used with "source bin/activate" *from bash*
# you cannot run it directly
```
which kinda implies that it is not compatible with nushell.

**Comment by jokeyrhyme** [comment]
Some comments from other issues:

> I've just read through this issue, https://www.nushell.sh/blog/2020-06-09-nushell_0_15_0.html#per-directory-environment-variables-samhedin , #2083 , #2117 , and #2130, #3872
>
> Figured it was worth linking these all together so others can keep up with related conversations

> There's also the work for python virtual environments going on here: https://github.com/nushell/nu_scripts/tree/main/virtual_environments

**Comment by ngmisl** [comment]
any news?

**Comment by flying-sheep** [comment]
The standalone [`virtualenv`](https://virtualenv.pypa.io/en/latest/) module (superset of the builtin `venv`) will by default create a `<venv>/bin/activate.nu`

(For Arch users: the arch package is outdated and won’t create a working nushell activation script)

**Comment by phiresky** [comment]
The script generated by `virtualenv` seems to be broken with nushell 0.67.0:

```
Error: nu::parser::parse_mismatch (link)

  × Parse mismatch during operation.
    ╭─[activate.nu:10:1]
 10 │ 
 11 │     let is-windows = ((sys).host.name | str downcase) == 'windows'
    ·         ─────┬────
    ·              ╰── expected valid variable name
 12 │     let virtual-env = '.../.venv'
    ╰────
```

**Comment by phiresky** [comment]
virtualenv version 20.16.3, python version 3.10.6

**Comment by igitur** [comment]
What is your output when you execute these commands? 

```
C:\> cd C:\temp\testvenv
C:\temp\testvenv〉virtualenv .venv                                                                                                                       
created virtual environment CPython3.9.6.final.0-64 in 6122ms
  creator CPython3Windows(dest=C:\temp\testvenv\.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\asdf\AppData\Local\pypa\virtualenv)
    added seed packages: pip==22.1.2, setuptools==63.2.0, wheel==0.37.1
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
C:\temp\testvenv〉source .\.venv\Scripts\activate.nu                                                                                                     
(.venv) C:\temp\testvenv〉                                                                              
```

**Comment by phiresky** [comment]
```
❯ virtualenv .env
created virtual environment CPython3.10.6.final.0-64 in 187ms
  creator CPython3Posix(dest=/tmp/16.12/.env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/tehdog/.local/share/virtualenv)
    added seed packages: pip==22.2.2, setuptools==63.2.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
/tmp/16.12
❯ source .env/bin/activate.nu
Error: nu::parser::parse_mismatch (link)

  × Parse mismatch during operation.
    ╭─[activate.nu:10:1]
 10 │
 11 │     let is-windows = ((sys).host.name | str downcase) == 'windows'
    ·         ─────┬────
    ·              ╰── expected valid variable name
 12 │     let virtual-env = '/tmp/16.12/.env'
    ╰────

```

**Comment by phiresky** [comment]
Ah, I guess I have 20.16.3 in my virtualenv but 20.15.1 in my system, and it seems to not overwrite the script when it already exists (but is broken)

**Comment by flying-sheep** [comment]
If anyone uses Arch’s `python-virtualenv` package: Friendly ping for @felixonmars to update it.

**Comment by FrancescoSaverioZuppichini** [comment]
news?

**Comment by whyboris** [comment]
When I run my command `source ~/.popo/venv/bin/activate` I get this:
```
  × Missing required positional argument.
   ╭─[activate:4:1]
 4 │ 
 5 │ if [ "${BASH_SOURCE-}" = "$0" ]; then
   ·                                ▲
   ·                                ╰── missing cond
 6 │     echo "You must source this script: \$ source $0" >&2
   ╰────
  help: Usage: if <cond> <then_block> (else <else_expression>)
```
🤷

**Comment by jokeyrhyme** [comment]
@whyboris `nu` does not support the same syntax that is understood by `sh` / `bash` / `zsh` / etc

So, the script that is generated by `virtualenv` for Python will not work in nushell

**Comment by whyboris** [comment]
Thank you @jokeyrhyme for the explanation. I don't mind -- I can use `zsh` for my work 👌 

Just wanted to report in on this issue -- since it seemed like there was intent to make `virtualenv` work with `nu` initially. 

Is the new verdict that `nu` will not likely support `virtualenv` until at least after 2023? 🤔

**Comment by flying-sheep** [comment]
> So, the script that is generated by virtualenv for Python will not work in nushell

Not quite. The script `<venv>/bin/activate` is for POSIXy shells, yes, but `virtualenv` also creates <code>&lt;venv>/bin/activate<strong>.nu</strong></code>

So just run this instead:

```bash
source ~/.popo/venv/bin/activate.nu
```

**Comment by whyboris** [comment]
Thank you @flying-sheep -- I see the `activate.nu` file, but I can't activate it 😓 
`source ~/.popo/venv/bin/activate.nu` doesn't seem to work:
```
/Users/byakubchik/.popo/venv/bin〉source ~/.popo/venv/bin/activate.nu                                                                                                                     11/03/2022 10:20:46 AM
Error: nu::parser::parse_mismatch (link)

  × Parse mismatch during operation.
   ╭─[activate.nu:1:1]
 1 │ # Setting all environment variables for the venv
 2 │ let path-name = (if ((sys).host.name == "Windows") { "Path" } { "PATH" })
   ·                                                    ─────┬────
   ·                                                         ╰── expected operator
 3 │ let virtual-env = "/Users/byakubchik/.popo/venv"
   ╰────
```

**Comment by flying-sheep** [comment]
nu changes fast, so old syntax isn’t necessarily supported anymore. You probably need to recreate the scripts with an updated `virtualenv` version, sth. like:

```bash
# move env away and create it anew
mv ~/.popo ~/.popo.bak
pip install -U virtualenv
python -m virtualenv ~/.popo
# move scripts from new, empty env into old one
mv ~/.popo/bin/activate.nu ~/.popo/bin/deactivate.nu ~/.popo.bak/bin/
# move old one back
rm -rf ~/.popo
mv ~/.popo.bak ~/.popo
```

**Comment by harrysarson** [comment]
I had to update to virtualenv v20.21.0 to support nushell 0.77.0

**Comment by alex-way** [comment]
For those wondering the command you need is `overlay use <path_to_venv>\Scripts\activate.nu`

**Comment by jokeyrhyme** [comment]
I dearly wish virtualenv had been opinionated about destination directory names

It makes it very hard to detect when a virtualenv exists if you have to search every directory just in case

Really wish it was just .virtualenv and that's it :S

**Comment by theoparis** [comment]
> 

I'm getting this:
```
➜ overlay use ./venv/bin/activate.nu
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
    ╭─[./venv/bin/activate.nu:21:1]
 21 │         # Try to parse 'true', '0', '1', and fail if not convertible
 22 │         let parsed = do -i { $env | get $name | into bool }
    ·                         ─┬
    ·                          ╰── expected operator
 23 │         if ($parsed | describe) == 'bool' {
    ╰────
```

I'm using nu v0.78.0 if that helps.

**Comment by flying-sheep** [comment]
the virtualenv version with the newest nushell syntax changes hasn’t been released yet, you can use  it like this:

```bash
# install dev version of virtualenv
pip install --user git+https://github.com/pypa/virtualenv.git
# update virtualenv with new script
python -m virtualenv /path/to/venv/
```

**Comment by glennDittmann** [comment]
> For those wondering the command you need is `overlay use <path_to_venv>\Scripts\activate.nu`

For me it was `overlay use <path_to_venv>\bin\activate.nu`, on _pop!\_os_.

**Comment by Heidar-An** [comment]
not sure if I'm doing something wrong, but when I get the dev version of `virtualenv` (and also when I don't), installing in my "virtualenv" still installs the package globally.

**Comment by detrin** [comment]
Seems like venv doesn't have the nu support yet. However this worked for me

```nushell
python3.11 -m pip install virtualenv
python3.11 -m virtualenv env_nu 
overlay use env_nu/bin/activate.nu
pip install -r requirements.txt 
```

**Comment by amtoine** [comment]
> Seems like venv doesn't have the nu support yet. However this worked for me
> 
> ```nushell
> python3.11 -m pip install virtualenv
> python3.11 -m virtualenv env_nu 
> overlay use env_nu/bin/activate.nu
> pip install -r requirements.txt 
> ```
>
yeah i think we have integration with `virtualenv` but not `python -m venv` :+1:

**Comment by detrin** [comment]
> > Seems like venv doesn't have the nu support yet. However this worked for me
> > ```nushell
> > python3.11 -m pip install virtualenv
> > python3.11 -m virtualenv env_nu 
> > overlay use env_nu/bin/activate.nu
> > pip install -r requirements.txt 
> > ```
> 
> yeah i think we have integration with `virtualenv` but not `python -m venv` 👍

Yes, I know https://github.com/python/cpython/issues/108852#issuecomment-1705124851

**Comment by MatrixManAtYrService** [comment]
As a workaround I've been using `zsh -i -c 'source venv/bin/activate ; nu'`

You just have to remember that you're now in a subsubshell (zsh is your parent, and your original nu is its parent), so instead of invoking `deactivate` you need to to type `exit` or press Ctrl+D.  When you exit, the zsh command finishes, so it takes you all the way back out to your original nu shell (no need to exit twice).

```
❯ python -m venv venv
❯ zsh -i -c 'source venv/bin/activate ; nu'
venv ❯ echo $env.VIRTUAL_ENV
    /home/matt/venv

venv ❯ exit  # instead of deactivate
❯ echo $env.VIRTUAL_ENV
    Error: nu::shell::column_not_found

  × Cannot find column
   ╭─[entry #12:1:1]
 1 │ echo $env.VIRTUAL_ENV
   ·      ──┬─ ─────┬─────
   ·        │       ╰── cannot find column 'VIRTUAL_ENV'
   ·        ╰── value originates here
   ╰────
```

**Comment by mb21** [comment]
For `venv`, I simply added `./venv/bin` (which is relative to the current working directory) to `$env.PATH` by putting the following in `config env`:

```
$env.PATH = ($env.PATH | split row (char esep)
  | prepend './venv/bin'
```

That way, seems I don't need to activate it. Still need to create a new venv with `python3 -m venv venv` once per project.

**Comment by Psypher1** [comment]
Has there been any updates to this?

I use venv and when I try to run `source venv\Scripts\activate` I get this

```
Error: nu::parser::shell_err

  × The '2>' shell operation is 'err>' in Nushell.
    ╭─[D:\python\finance-tracker\env\Scripts\activate:70:9]
 69 │ # past commands the $PATH changes we made may not be respected
 70 │ hash -r 2> /dev/null
    ·         ─┬
    ·          ╰── use 'err>' instead of '2>' in Nushell
    ╰────


```

**Comment by flying-sheep** [comment]
please read the comments, e.g. https://github.com/nushell/nushell/issues/852#issuecomment-1704380160

**Comment by theoparis** [comment]
After running `pip3 install git+https://github.com/pypa/virtualenv.git` and recreating my .venv folder there is no activate.nu file in .venv/bin/ 😕

**Comment by theoparis** [comment]
Having to use `-m virtualenv` over `-m venv` breaks pipx 😕

**Comment by L0verde** [comment]
For arch users you need [python-virtualenv](https://archlinux.org/packages/extra/any/python-virtualenv/) as mentioned by [flying-sheep](https://github.com/flying-sheep)
```bash
pacman -S python-virtualenv
python -m virtualenv .venv
overlay use .venv/bin/activate.nu # You won't get auto-completion but don't worry
```
Now you should see `(.venv) ~/YourProject` like normal :)

**Comment by jeanlucthumm** [comment]
@L0verde 

Looks broken again:

```sh
$ source .venv/bin/activate.nu                                                         
Error: nu::parser::unexpected_keyword

  × Statement used in pipeline.
    ╭─[/Users/jeanluc/Code/brainhub/backend/.venv/bin/activate.nu:96:27]
 95 │ export alias pydoc = python -m pydoc
 96 │ export alias deactivate = overlay hide activate
    ·                           ───┬───
    ·                              ╰── not allowed in pipeline
    ╰────
  help: 'overlay' keyword is not allowed in pipeline. Use 'overlay' by itself, outside of a pipeline.
 ```

```sh
$ nu --version
0.96.1

$ python --version
Python 3.12.4

$ python -m virtualenv --version
virtualenv 20.26.2
```

**Comment by eliax1996** [comment]
@jeanlucthumm seems you need to use `overlay use .venv/bin/activate.nu`

**Comment by eSkry** [comment]
@lighth7015 I'am write [simple commands for config.nu for activating python environment](https://gist.github.com/eSkry/119fbebcc72cefdb585f909f98d68540)  (github gist)

**Comment by MagnusOffermanns** [comment]
Hy Everybody,

I am also encountering the error that @L0verde encountered.

```nu
⋈┈○ overlay use ~/python_virtual_environments/frida_2_9_5/bin/activate.nu
Error: nu::parser::extra_positional

  × Extra positional argument.
    ╭─[/home/username/python_virtual_environments/frida_2_9_5/bin/activate.nu:65:58]
 64 │     let venv_path = ([$virtual_env $bin] | path join)
 65 │     let new_path = ($old_path | prepend $venv_path | str collect $path_sep)
    ·                                                          ───┬───
    ·                                                             ╰── extra positional argument
 66 │
    ╰────
  help: Usage: str
```

```shell
nu -v
0.102.0

python --version
Python 3.11.2

python -m virtualenv --version
virtualenv 20.17.1+ds from /usr/lib/python3/dist-packages/virtualenv/__init__.py
```

**Comment by techmanwalker** [comment]
I've hit this one.

```
~/.local/build/LTX-2> source .venv/bin/activate
Error: nu::parser::shell_andand

  × The '&&' operator is not supported in Nushell
    ╭─[/home/lito/.local/build/LTX-2/.venv/bin/activate:82:57]
 81 │ VIRTUAL_ENV='/home/lito/.local/build/LTX-2/.venv'
 82 │ if ([ "$OSTYPE" = "cygwin" ] || [ "$OSTYPE" = "msys" ]) && $(command -v cygpath &> /dev/null) ; then
    ·                                                         ─┬
    ·                                                          ╰── instead of '&&', use ';' or 'and'
 83 │     VIRTUAL_ENV=$(cygpath -u "$VIRTUAL_ENV")
    ╰────
  help: use ';' instead of the shell '&&', or 'and' instead of the boolean '&&'
```

**Comment by flying-sheep** [comment]
@techmanwalker you (or whatever inserted that into your shell) used the wrong script. It's `activate.nu`
