### ISSUE TITLE
[Question] Different `ls` output for nushell and bash

### ISSUE THREAD

**Issue by jdvr** [nushell/nushell#853]
I am testing Nu and I have notice a different  output for `ls` when listing some directories for example:

```sh
➜  nushell git:(master) ls ~/.local 
share
➜  nushell git:(master) cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.45s
     Running `target/debug/nu`
/home/juan/nushell(master)> ls ~/.local/
/home/juan/nushell(master)>
```

Why inside null `ls ~/.local/` returns an empty list?

**Comment by jonathandturner** [comment]
Can you say more about the contents of that directory? Is the file/directory there but hidden by default, by chance?

**Comment by jonathandturner** [comment]
I agree that it is probably wrong, just trying to figure out what is going wrong

**Comment by jdvr** [comment]
It is a _dotted_ directory so is hidden by default on system file explorer and normal `ls` command at least you add `-a` flag. 

The weird behavior here for me is that I am listing it manually so if it is hidden or not shouldn't be taken into account.

**Comment by jdvr** [comment]
I have tested and it seems something related to tilde and `std::path::Path`

```rust
use std::path::Path;

fn main() {
    let tilde = Path::new("~");
    let point = Path::new(".");
    println!("tilde is dir: {:?}", tilde.is_dir());
    println!("point is dir: {:?}", point.is_dir());
}
``` 

output:

>tilde is dir: false
point is dir: true

**Comment by andrasio** [comment]
@jdvr Thanks! Nu is not expanding the `~` to your home directory and that's the reason it's not listing the contents. This is a bug.

**Comment by jdvr** [comment]
Yes. 

`cd ~ ` and then `ls .local` works fine.

I can work on path expand if you want.

**Comment by andrasio** [comment]
@jdvr That would require a change down to the parser level of Nu. If you are interested, dig down to the parser and find how the current `~` expansion is done. By the time a command (see `cd`) gets the data from Nu internals the path will be already expanded by the parser.

You'd need to do this expansion rule for a pattern as well since that's what `ls` asks Nu to get.

**Comment by andrasio** [comment]
@jdvr Fixed on master. Thanks for bringing it up!
