### ISSUE TITLE
Unquoted path results in "executable was not found"

### ISSUE THREAD

**Issue by melMass** [nushell/nushell#8530]
### Describe the bug

I hit this in a few different scenarios.

### How to reproduce

```console
> ./path_that_exists_or_not | path exists
 1 ./path_that_exists_or_not | path exists
   · ──┬─
   ·   ╰── executable was not found
   ╰────
  help: The system cannot find the file specified. (os error 2)
```

### Expected behavior

Paths should not need quotes 

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.77.2                                   |
| branch             | main                                     |
| commit_hash        | 64f50a179e023b4a6a810a1a923381b8e3f99608 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-03-19 16:19:07 +01:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by WindSoilder** [comment]
Not really sure, isn't it work as expected?  When type something as bare word, if it's not an internal command, nushell will run it as an external command.

**Comment by melMass** [comment]
Maybe that's intentional but that's definitely a regression and not something you expect.

For instance I type path manually all the time in REPL and find it strange that it can interpolate bare strings `{hello:moto}` but not a path

**Comment by melMass** [comment]
@WindSoilder I think you are right! Tab completion is actually quoting paths. I'm not sure if it's an error on my side or a change, I really think bare strings like that used to work as these were picked up from my history but I could be wrong.

In any case, in practice I don't think it's an issue.

Closing it
