### ISSUE TITLE
The `complete` command doesn't work with interactive commands

### ISSUE THREAD

**Issue by stevenxxiu** [nushell/nushell#8539]
### Describe the bug

`complete` doesn't wait until interactive command finishes.

It shows nothing at first. After pressing `Ctrl + C`, the interactive command's output shows up.

In the test case below, the goal is to capture `stderr` of the command, via `do { atuin search --interactive } | complete`.

### How to reproduce

Run `atuin search --interactive | complete`.

### Expected behavior

I expect `complete` to wait until the interactive command finishes.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.77.2                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 2d416130395675f32512241b16b601409a46e5f7                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.68.0 (2c8cc3432 2023-03-06) (Arch Linux rust 1:1.68.0-1) |
| cargo_version      | cargo 1.68.0                                                     |
| build_time         | 2023-03-18 00:10:14 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | default, zip                                                     |
| installed_plugins  |                                                                  |

**Comment by jntrnr** [comment]
Does `do -i { atuin search --interactive } | complete` work? `do` by default doesn't redirect stderr

**Comment by stevenxxiu** [comment]
Nope this has the same behavior as described above. No output shows at first, then once `Ctrl + C` is pressed, the interactive output shows up.

**Comment by jntrnr** [comment]
Makes me wonder if it doesn't want `stdout` redirected?

`vim` and similar editors have this behaviour. If so, we'd have to redirect only `stderr` and not `stdout`.

**Comment by stevenxxiu** [comment]
Related to [Redirect `stderr` · Issue #8277 · nushell/nushell](https://github.com/nushell/nushell/issues/8277).

**Comment by jntrnr** [comment]
I tried this on the latest main, and this variation seems to work for me: `run-external --redirect-stderr atuin search "--interactive" | complete | $in.stderr`

**Comment by jntrnr** [comment]
The reason the original one isn't working is because `complete` is getting, by default, `stdout` rather than `stderr`. So you need to go through the helper command to turn off the `stdout` and turn on the `stderr`.

**Comment by stevenxxiu** [comment]
Thanks, that works indeed. I suppose for `complete` to work with interactive commands I can just use `run-external`.

**Comment by fdncred** [comment]
Seems like we need to document the reason for why/how `run-external` works. Maybe on the bash to nushell page? It's a little odd. 

On the other hand, this bash syntax is A LOT odd ` -i -- "$0" 3>&1 1>&2 2>&3' (commandline))` 🤣

**Comment by zhiburt** [comment]
Hi there;

Just a note that run-external works only with binaries but not builtin commands;

```nu
~/bin/nushell> run-external --redirect-stderr inspect                                                                          03/31/2023 02:22:15 AM
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #22:1:1]
 1 │ run-external --redirect-stderr inspect
   ·                                ───┬───
   ·                                   ╰── did you mean 'inspect'?
   ╰────
  help: No such file or directory (os error 2)
```

**Comment by fdncred** [comment]
Related to this issue and with atuin, we found out this worked `run-external --redirect-stderr atuin search "--interactive" | complete | $in.stderr`.

Good point @zhiburt. `run-external` is not meant for internal commands. The error message could be more helpful though.
