### ISSUE TITLE
Provide better error output when file doesn't exist

### ISSUE THREAD

**Issue by lucperkins** [nushell/nushell#8546]
### Describe the bug

If you use `mv` with a path that doesn't exist, you get this error:

```
Error:
  × Invalid file or pattern
   ╭─[entry #1:1:1]
 1 │ mv foo.txt bar.txt
   ·    ───┬───
   ·       ╰── invalid file or pattern
   ╰────
```

But it's not clear what "invalid" means in this case. It could mean, for example, that the filename itself is somehow invalid. I think something like this would be preferable:

```
Error:
  × Invalid move operation
   ╭─[entry #1:1:1]
 1 │ mv foo.txt bar.txt
   ·    ───┬───
   ·       ╰── file or directory does not exist
   ╰────
```

### How to reproduce

```shell
nu -c "mv definitely-does-not-exist.txt some-other-filename.txt"
```

### Expected behavior

I'd expect something at least as helpful as what you get from Bash et al:

```
mv: cannot stat 'foo.txt': No such file or directory
```

### Configuration

In principle, any Nushell config

**Comment by rgwood** [comment]
Good issue, thanks. How's this for alternate wording?

```
Error:
  × File(s) not found
   ╭─[entry #3:1:1]
 1 │ mv foo.txt bar.txt
   ·    ───┬───
   ·       ╰── could not find any files matching this glob pattern
   ╰────
```

**Comment by lucperkins** [comment]
@rgwood Yup, seems like an improvement to me! Should it be "files or directories," though? (I'm honestly not sure...not a rhetorical question!)
