### ISSUE TITLE
`sys` command should report the host architecture

### ISSUE THREAD

**Issue by acidghost** [nushell/nushell#8563]
### Related problem

It would be nice to have the host architecture (akin to `uname -m`) as part of the `sys` command so we can easily interact with it (e.g. compose a string out of parts of `(sys).host`). 

### Describe the solution you'd like

Add a new key-value pair for the architecture to the `(sys).host` record. A good key would be `arch` or `machine`.

**Comment by acidghost** [comment]
Yeah, that's easy to integrate with other nushell stuff, e.g.:

`(sys).host | select name os_version | insert arch $nu.os-info.arch`
is much better than
`(sys).host | select name os_version | insert arch (^uname -m | str trim | str downcase)`

Doing `(sys).host | select name os_version arch` is even better, but I'm happy with `$nu.os-info.arch` for the use cases I have ATM.

**Comment by fdncred** [comment]
The point I was trying to make is that `sys` may not be suitable for performance critical scripts. I've seen it take 50ms-100ms and sometimes longer, whereas `$nu.os-info` runs regularly in under than 3ms.

Another thing is that the `sys` command uses the `sysinfo` crate and I didn't see architecture as one of the supported cross-platform functions.

Closing for now since `$nu.os-info.arch` supplies this functionality.

**Comment by rgwood** [comment]
> The point I was trying to make is that `sys` may not be suitable for performance critical scripts. I've seen it take 50ms-100ms and sometimes longer, whereas `$nu.os-info` runs regularly in under than 3ms.

If you're just consuming `sys.host` info (i.e. with `sys | get host`) the performance issue should be resolved by https://github.com/nushell/nushell/pull/8321

I kind of think that we should consolidate `$nu.os-info` and `sys.host` somehow, I don't think we need both anymore.

**Comment by fdncred** [comment]
> If you're just consuming sys.host info (i.e. with sys | get host) the performance issue should be resolved by https://github.com/nushell/nushell/pull/8321

@rgwood - I saw `(sys).host` this morning take ~30ms on Windows on the latest main. It's possible that it is resolved and Windows just sucks, but `$nu.os-info` on Windows took 3ms.

**Comment by acidghost** [comment]
Another thing that makes for ugly code is that the two places also have non-uniform values:
```
❯ (sys).host | select name os_version long_os_version kernel_version
╭─────────────────┬───────────────╮
│ name            │ Darwin        │
│ os_version      │ 13.2.1        │
│ long_os_version │ MacOS 13.2.1  │
│ kernel_version  │ 22.3.0        │
╰─────────────────┴───────────────╯
❯ $nu.os-info
╭────────────────┬─────────╮
│ name           │ macos   │
│ arch           │ aarch64 │
│ family         │ unix    │
│ kernel_version │ 22.3.0  │
╰────────────────┴─────────╯
❯ ^uname -a
Darwin acidghost-MBP.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64
❯ ^uname -s
Darwin
```

I would expect `$nu.os-info.name.name == 'Darwin'`.

**Comment by fdncred** [comment]
> I would expect $nu.os-info.name.name == 'Darwin'.

You can take that up with the rust team. LOL. It's using rust consts like this:
```rust
Value::string(std::env::consts::OS, self.span()),
Value::string(std::env::consts::ARCH, self.span()),
Value::string(std::env::consts::FAMILY, self.span()),
```
So, it's sysinfo crate versus rust consts, who is right?

I wouldn't be opposed to sunsetting and combining $nu.os-info if we can get the performance impact licked.

**Comment by rgwood** [comment]
> @rgwood - I saw `(sys).host` this morning take ~30ms on Windows on the latest main.

Strange. I'm consistently seeing around 5ms on Windows and 1ms on Linux for `timeit {|| (sys).host}`

**Comment by fdncred** [comment]
> Strange.

It was the first time I ran it. I wonder if there is caching going on somewhere?

**Comment by rgwood** [comment]
I don't believe there is any caching for that info (but maybe there should be)

**Comment by fdncred** [comment]
Sorry, I wasn't clear. I wonder if the OS or sysinfo is doing any?
