### ISSUE TITLE
Is there a canonical way to prompt for user input in a script?

### ISSUE THREAD

**Issue by acidghost** [nushell/nushell#8566]
### Question

I want to prompt the user for confirmation in a script; in Python I would use something like `input()` (https://docs.python.org/3/library/functions.html#input). I can achieve this in Nu with something like:
```
def prompt [t: string] {
  print -n $t; ^head -1 | str trim
}
```

Is there a Nushell mechanism or command that I can use instead of invoking an external program?

**Comment by fdncred** [comment]
We have an `input` command you can play around with. `help input`

**Comment by acidghost** [comment]
Yeah, that's exactly it. I don't know how I missed it.. Thanks!
