### ISSUE TITLE
Misleading OK error code if there is an error in a for loop

### ISSUE THREAD

**Issue by presidento** [nushell/nushell#8569]
### Describe the bug

If there is an (unhandled) error in a `for` loop, the exit code is 0.

### How to reproduce

Let's have a `exitcode.nu` file with the contents:

```
for i in 1..10 {
    echo $"Calculating #($i)"
    nu -c '1 / 0'
}
```

Run it:

```
❯ nu exitcode.nu
Calculating #1
Error: nu::shell::division_by_zero (link)

  × Division by zero.
   ╭─[source:1:1]
 1 │ 1 / 0
   ·   ┬
   ·   ╰── division by zero
   ╰────


❯ echo $env.LAST_EXIT_CODE
0
```

### Expected behavior

I expected nu to have a non-zero exit code, like when the error is outside a for loop.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.76.0                                   |
| branch             |                                          |
| commit_hash        | bc38a6a795f438ab1465dd987adf92efd9530529 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)      |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)      |
| pkg_version        | 0.76.0                                   |
| build_time         | 2023-02-23 08:03:29 -06:00               |
| build_rust_channel | release                                  |
| features           | database, default, trash, which, zip     |
| installed_plugins  |                                          |

### Additional context

@amtoine please note that because of this bug, now `tests.nu` will pass, even if one of the tests fails.

**Comment by rgwood** [comment]
If anyone wants to take a look at this, the relevant code is here: https://github.com/nushell/nushell/blob/66ad83c15ce0289a9901b5f618e9ea95ea763974/crates/nu-cmd-lang/src/core_commands/for_.rs#L124-L126

And here: https://github.com/nushell/nushell/blob/66ad83c15ce0289a9901b5f618e9ea95ea763974/crates/nu-cmd-lang/src/core_commands/for_.rs#L166-L168

`for` probably needs to return an error instead of just calling `break`.
