### ISSUE TITLE
`http` exceptions should be supressible

### ISSUE THREAD

**Issue by ineu** [nushell/nushell#8573]
### Related problem

The current implementation of `http` is opinionated. It throws exceptions on certain http codes: https://github.com/nushell/nushell/blob/main/crates/nu-command/src/network/http/client.rs#L282. This makes it impossible to use it instead of `curl` because:
1. Different services have different semantics in regards to codes
2. Non-200 does not mean that there's no response

A good example is Cloudflare API. When you don't supply proper headers, it responds with code 4xx AND a body, like this:
```
> curl https://api.cloudflare.com/client/v4/zones
{"success":false,"errors":[{"code":9106,"message":"Missing X-Auth-Email header"},{"code":9107,"message":"Missing X-Auth-Key header"}],"messages":[],"result":null}
```
and the code returned by the API is 403.

When the same request is done via `http get`, you get only an exception, while the body is lost:
```
http get https://api.cloudflare.com/client/v4/zones
Error: nu::shell::network_failure

  × Network failure
   ╭─[entry #42:1:1]
 1 │ http get https://api.cloudflare.com/client/v4/zones
   ·          ─────────────────────┬────────────────────
   ·                               ╰── Access forbidden (403) to "https://api.cloudflare.com/client/v4/zones"
   ╰────
```
and you see no response body and thus can only guess what went wrong.

### Describe the solution you'd like

Add an option that changes the response handling behavior. If the option is given, only real errors should be thrown (like dns resolution failures, network failures and so on). Any response from the target url should be considered success and the body should be printed.

### Describe alternatives you've considered

curl, an external command

**Comment by Sygmei** [comment]
I just added the required `--allow-errors `option, it should cover this case

**Comment by sholderbach** [comment]
Super-quick turnaround! Thx!

**Comment by ineu** [comment]
Awesome, thank you!
