### ISSUE TITLE
http command should respond to Ctrl-C

### ISSUE THREAD

**Issue by DominicAnelloSonos** [nushell/nushell#8585]
### Describe the bug

I forgot to turn on my VPN before attempting to fetch some data from a private server with nu's `http` command this morning, and I was unable to interrupt the command when I realized my mistake.  

Here's the command I executed with the identifying information blacked out.
```
➜ http get -H ['Authorization' '*****'] https://private-server/v1/users/1234567 | get identity.firstName
^C^C

# 30s later...
Error: nu::shell::network_failure

  × Network failure
   ╭─[entry #5:1:1]
 1 │ http get -H ['Authorization' '*****'] https://private-server/v1/users/1234567 | get identity.firstName
   ·                                       ───────────────────┬───────────────────
   ·                                                          ╰── https://private-server/v1/users/1234567: Network Error: timed out reading response
   ╰────

⏱ 30s
```

### How to reproduce

1. Try to fetch data using `http` from an unroutable IP address.  e.g. `http get https://10.255.255.1.1/foo`
2. Attempt to interrupt with `Ctrl-C` before the connection times out.
3. You will not be able to and must wait 30s for the connection to timeout

Example:
```
➜ http get https://10.255.255.1/foo
^C^C^C^CError: nu::shell::network_failure

  × Network failure
   ╭─[entry #6:1:1]
 1 │ http get https://10.255.255.1/foo
   ·          ────────────┬───────────
   ·                      ╰── Cannot make request to https://10.255.255.1/foo, there was an error establishing a connection.

⏱ 30s
```

### Expected behavior

The behavior I expected was for the `http` command to respect the interrupt from `Ctrl-C` and terminate.

### Screenshots

![Screenshot 2023-03-23 at 10 09 26](https://user-images.githubusercontent.com/57644528/227233518-108b0b9c-aa46-4501-bc8c-a3aa02224128.png)

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.77.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.68.0 (2c8cc3432 2023-03-06) (built from a source tarball) |
| cargo_version      | cargo 1.68.0 (115f34552 2023-02-26)                               |
| build_time         | 2023-03-17 05:10:56 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

**Comment by rgwood** [comment]
Thanks for the well-written issue! This should definitely be cancellable. 

We use the [`ureq`](https://github.com/algesten/ureq) library under the hood. From a quick look at the docs+repo, it doesn't seem like it's possible to cancel in-flight requests :/

Worth further investigation, and maybe we should lower the timeout to make things a little better until we have proper cancellation support.

**Comment by rgwood** [comment]
Seems like proper cancellation isn't possible for `ureq` (and fair enough, it is explicitly advertised as a blocking HTTP library). 

I wonder if we could just run the HTTP request in a background thread and abandon it if the user presses `ctrl+c`.

**Comment by rgwood** [comment]
It looks like the `http` commands are able to be cancelled when streaming data from the server _after_ a connection is made: https://github.com/nushell/nushell/blob/05ff7a992592d31b48019e53a5bc691a45550a6a/crates/nu-command/src/network/http/client.rs#L90

But yeah, if the initial connection takes a long time we don't yet have a mechanism for cancelling it. I think we'll want to take the following approach to fix that:

1. Spin up a background thread to perform the initial [`call()`](https://docs.rs/ureq/2.6.2/ureq/struct.Request.html#method.call) and send the `Response` struct over a channel
2. In the primary thread, spin a loop that checks whether `ctrl+c` has been pressed _or_ a `Response` is available
    1. If `ctrl+c` has been pressed, give up and abandon the background thread. It will either time out or the connection will be automatically dropped when the channel is.
    1. If a `Response` is available, great; break out of the loop and handle the `Response` the same way we normally would

**Comment by DominicAnelloSonos** [comment]
Thanks for the quick response.  Really love this project so far!
