### ISSUE TITLE
Cargo install nu --features=dataframe won't install dataframe

### ISSUE THREAD

**Issue by cojmeister** [nushell/nushell#8587]
### Describe the bug

Upon running:
`cargo install nu --features=dataframe` after the full running and build there is not dataframes.
When running the `version` command I get:

### How to reproduce

1.  run `cargo install nu --features=dataframe`
2. try using functions like open-df
3. miserably fail

### Expected behavior

I expected nu to install the dataframe features.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.77.1                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | macos-aarch64                       |
| build_target       | aarch64-apple-darwin                |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10) |
| rust_channel       | stable-aarch64-apple-darwin         |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10) |
| build_time         | 2023-03-23 20:23:02 +02:00          |
| build_rust_channel | release                             |
| features           | default, zip                        |
| installed_plugins  |                                     |

### Additional context

Running on MacOS Ventura 13.2.1 on M1 Processor

**Comment by fdncred** [comment]
I'm guessing this is because `open-df` isn't a command. All dataframe commands now start with `dfr <blah>`. You can see them with `help -f dfr`.

**Comment by cojmeister** [comment]
Oh silly me...
Then a change in the documentation is needed I guess

**Comment by fdncred** [comment]
> Oh silly me... Then a change in the documentation is needed I guess

Yup, docs are probably out of date. Would love to have a PR for that.
