### ISSUE TITLE
Unclear error message when trying to set var to command value

### ISSUE THREAD

**Issue by YummyOreo** [nushell/nushell#8589]
### Related problem

Im trying to set a variable to a open command:

```shell
let list = open ~/AppData/Roaming/nushell/list.toml
```
But I get a error:
```cmd
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[youtube.nu:7:1]
 7 │
 8 │ let list = open ~/AppData/Roaming/nushell/list.toml
   ·                 ──────────────────┬──────────────────
   ·                                   ╰── expected operator
```
This is very misleading as:
- The underlined section does not point you in the right direction
- What is a operator?

### Describe the solution you'd like

The error message to underline the correct area and be overall more helpful

### Describe alternatives you've considered

The fix is to add `()` around the whole command:
```shell
let list = (open ~/AppData/Roaming/nushell/list.toml)
```

**Comment by weirdan** [comment]
This now just works without any errors.
