### ISSUE TITLE
Feature: Add the ability to clear the terminal.

### ISSUE THREAD

**Issue by bgianfo** [nushell/nushell#859]
Maybe I'm missing something, but I'm not able to find any way to clear the  command prompt besides control-l (so that the terminal emulator will clear it self). It would be nice if something like clear / cls was exposed in nushell. 

```
F:\nushell\src\commands(master)> clear
error: Command not found
- shell:1:0
1 | clear
  | ^^^ command not found

F:\nushell\src\commands(master)> cls
error: Command not found
- shell:1:0
1 | cls
  | ^^^ command not found
```

**Comment by terakilobyte** [comment]
I was looking at diving into this. Is the intention to have a command in addition to CTRL+L ?

**Comment by jonathandturner** [comment]
@terakilobyte - I don't think clear works across platforms. Here's what I see on Windows:

```
C:\Users\joturner\.cargo\bin> clear
error: Command not found
- shell:1:0
1 | clear
  | ^^^^^ command not found
```

I wonder if you're actually picking up the clear command on your system.

**Comment by bgianfo** [comment]
@jonathandturner  I believe you are correct, on windows (in cmd/psh) cls is a internal shell command, On Linux clear is a an actual program (/usr/bin/clear).

**Comment by terakilobyte** [comment]
Ah, got it.

**Comment by oigi333** [comment]
Should that be a plugin or an internal command?

**Comment by jonathandturner** [comment]
@oigi333 - I'd go with internal

**Comment by sandorex** [comment]
`clear` works for me on windows.

**Comment by jonathandturner** [comment]
Yup, this is done now. Closing.
