### ISSUE TITLE
Per directory $env

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#86]
Might be interesting to explore what it would be like to be able to craft your environment specific to a given directory, effectively letting directories have their own env

**Comment by dbarnett** [comment]
Would this be the default $env behavior, or how would you use it?

**Comment by wycats** [comment]
The basic idea is that a directory could have something like a `.nu` file in it that could supplement the environment and possibly the path.

**Comment by jedahan** [comment]
whats the difference between this being built-in, versus having a `.nurc` that just does `test -f $PWD/.env && grep ^export $PWD/.env | source -` or something along those lines.

**Comment by mlh758** [comment]
In other shells I use [direnv](https://direnv.net/) to put a `.envrc` file in some of my dev projects where the app is normally configured via environment variables. When deployed they would already be setup with Kubernetes or Chef or something but in development it saves me some typing.

**Comment by dysinger** [comment]
I use direnv with fish shell and I need a replacement.

**Comment by thegedge** [comment]
Yeah, we definitely want to make this work, and believe it's such a useful feature it should be part of the core.

**Comment by samhedin** [comment]
I would like to give this a try, if it's alright!

**Comment by jonathandturner** [comment]
@samhedin - please do! Feel free to reach out on discord if you have questions or want to brainstorm.

**Comment by arashout** [comment]
This can probably be closed with @samhedin PRs
