### ISSUE TITLE
Add an archieve command to nushell

### ISSUE THREAD

**Issue by adhadse** [nushell/nushell#8608]
### Related problem

The feature proposal is to add archive command that can achieve a command for future reference or for repetitive tasks. 
Currently, history does a similar thing but finding the exact command you typed in from different variations of command can be difficult to find from history. 

Looking forward for your ideas. 

### Describe the solution you'd like

The `archieve` command can let user archive the current command typed in or archive the previous one or from history.

### Describe alternatives you've considered

N/A

**Comment by fdncred** [comment]
Never heard of this concept. Where does it archive an archived command? How are those archived commands used in the future?

**Comment by adhadse** [comment]
Yes, I just had an idea, open for discussion. The idea is to achieve a command on demand of user to an archieve.txt similar text file the history command generates.

**Comment by honnip** [comment]
It feels like a note app 😅  
You can have a command that stores or finds a command (and its description) in an external text file or database,. or just use history and grep
