### ISSUE TITLE
remove `match` from std.nu

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#8616]
### Describe the bug

We need to update std.nu to remove the `match` command since now it's a built-in.

### How to reproduce

N/A

### Expected behavior

Use the built-in match command.

### Configuration

|key|value|
|-|-|
|version|0.77.2|
|branch|main|
|commit_hash|744a28b31dde95ff0aea7e7190f5b8f39427ead3|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.66.1 (90743e729 2023-01-10)|
|rust_channel|1.66.1-aarch64-apple-darwin|
|cargo_version|cargo 1.66.1 (ad779e08b 2023-01-10)|
|build_time|2023-03-24 16:45:49 -05:00|
|build_rust_channel|release|
|features|default, zip|
|installed_plugins|custom-value generate, custom-value generate2, custom-value update, from eml, from ics, from ini, from parquet, from plist, from vcf, gstat, hist, inc, json path, len, nu-example-1, nu-example-2, nu-example-3, periodic-table, plot, pnet, query, query json, query web, query xml, regex, xyplot|

### Additional context

/cc @amtoine

**Comment by amtoine** [comment]
yup :+1: 

i did originally put it in the [roadmap](https://github.com/nushell/nushell/issues/8450), under the "things to do" section of my comment.
but thanks for this clearer one, i'll do that asap :wink:
