### ISSUE TITLE
numbers are parsed as strings

### ISSUE THREAD

**Issue by 1Kinoti** [nushell/nushell#8621]
### Describe the bug

```nu
def foo [num: string] { $num }
```

`foo 69` parses okay but i think it shouldn't

`foo 69 | describe` gives us `string`

### How to reproduce

as illustrated above

### Expected behavior

i expect nu to raised the error
```nu
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[entry #21:1:1]
 1 │ foo 69
   ·     ─┬─
   ·      ╰── expected string
   ╰────
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.77.2                                   |
| branch             | main                                     |
| commit_hash        | d409171ba830111658c8ee3eb2321d8b676ce9c6 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-03-26 04:35:03 +03:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
Related:
https://github.com/nushell/nushell/pull/8600#issuecomment-1483365442

**Comment by fdncred** [comment]
I talked with @jntrnr earlier today about this. JT has a solution in mind already. It's part of another thing JT was working on that isn't fully implemented yet.

**Comment by jntrnr** [comment]
Just put up https://github.com/nushell/nushell/pull/8635 to fix this
