### ISSUE TITLE
Default config should not require a fancy font

### ISSUE THREAD

**Issue by getreu** [nushell/nushell#8622]
### Describe the bug

When I installed Nushell on Debian the prompt looks like like this:

```nu
/home/getreu〉
```

The last character is [Right Angle Bracket: U+3009](https://unicode-table.com/en/3009/) which is not availble in the default font on my Debian system.

In order not to scare away new users, I suggest replacing U+3009 with '>' in the code that generates the config file `.config/nushell/env.nu`:

```nu
# the state of the prompt
let-env PROMPT_INDICATOR = { ">" }
let-env PROMPT_INDICATOR_VI_NORMAL = { ">" }
```

This changes the prompt to:

```nu
/home/getreu>
```

For new users, the decision to explore `nushell` more in detail, is taken within some minutes. Therefor, the prompt should look Ok for everyone whatever font he uses. Experienced users can change it anyway.

### How to reproduce

Install `nu` on a Debian system.

### Expected behavior

I expected the prompt can render properly.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.77.0                                   |
| branch             |                                          |
| commit_hash        | fd09609b44b53d41ac7929e90708cdeba7bfb571 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-03-14 20:50:08 +00:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

### Additional context

Debian, with _Deja Vue Sans Mono Book_ font.

**Comment by WindSoilder** [comment]
I think it's already handle by this: https://github.com/nushell/nushell/pull/8080
