### ISSUE TITLE
nu-plugin: query for xml does not work on YT RSS Feed links

### ISSUE THREAD

**Issue by uncomfyhalomacro** [nushell/nushell#8624]
### Describe the bug

Running the following command:

```shell
http get -r "http://www.youtube.com/feeds/videos.xml?channel_id=UCrWkRTo9J2vHAC2C0BSwfPg" | query xml "//feed/entry"

```

It does not give me an output (No output at all). It should at least get the xpaths I want like how https://xpath.com does it in the next screenshot:
![image](https://user-images.githubusercontent.com/66054069/227759980-8f39c662-2d80-452a-ac17-90dad5c80a6d.png)

### How to reproduce

1. Run any YouTube RSS Feed link e.g. `http get "https://www.youtube.com/feeds/videos.xml?channel_id=UCrWkRTo9J2vHAC2C0BSwfPg" --raw | query xml //feed/entry`
2. No output.

### Expected behavior

I expected nu plugin query to get the xpaths I want.

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.77.1                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.68.0 (2c8cc3432 2023-03-06) (built from a source tarball)               |
| cargo_version      | cargo 1.68.0                                                                    |
| build_time         | 2023-03-18 00:00:00 +00:00                                                      |
| build_rust_channel | release                                                                         |
| features           | default, zip                                                                    |
| installed_plugins  | from eml, from ics, from ini, from vcf, query, query json, query web, query xml |

**Comment by fdncred** [comment]
Thanks. Agreed. 

I'm not sure if it's a bug in our code or a bug in the crate we use for xpath but it appears that `xpath::evaluate()` isn't returning anything here.
https://github.com/nushell/nushell/blob/944cad35bf846adbbe69556a1a7e92fe74c44dd5/crates/nu_plugin_query/src/query_xml.rs#L43

Some quick printf debugging reveals that it returns this:
```
res: Ok(Nodeset(Nodeset { nodes: {} }))
```

It looks like someone needs to drill down deeper and see what is going on.

**Comment by uncomfyhalomacro** [comment]
I will try experimenting with the new crate and see if it fixes it.

**Comment by uncomfyhalomacro** [comment]
Going to fix this over the weekend if my sched allows me :D

**Comment by fdncred** [comment]
@uncomfyhalomacro any update on this?

**Comment by uncomfyhalomacro** [comment]
> @uncomfyhalomacro any update on this?

Sorry for the delay. I have two more weeks to finish something in the uni and it's pretty hectic. I will be back once I am done with them.

**Comment by fdncred** [comment]
>  I will be back once I am done with them.

Sounds good. Thanks for responding.

**Comment by uncomfyhalomacro** [comment]
I found out the cause of the issue. It was because of namespaces.

## MWE

```rust
use sxd_document::parser;
use sxd_xpath::{Context, Factory};
use std::fs;
use std::env;


fn main() {
    let mut file = fs::read_to_string(&std::env::args().nth(1).unwrap()).unwrap();
    let document = parser::parse(&file).unwrap();
    let document = document.as_document();
    let factory = Factory::new();
    let xpath = factory.build(&std::env::args().nth(2).unwrap()).unwrap().unwrap();
    let mut context = Context::new();
    context.set_namespace("ns", "http://www.w3.org/2005/Atom");
    let value = xpath.evaluate(&context, document.root()).unwrap();
    println!("Found: {}({:?})", value.string(), value);

```
Running `cargo run --release -- videos.xml '//feed'` will give me
```Found: (Nodeset(Nodeset { nodes: {} }))```

Running `cargo run --release -- videos.xml '//ns:feed' will give me the output I need.

`videos.xml` can be any `http://www.youtube.com/feeds/videos.xml?channel_id=<N>` where N is channel ID.


I am not sure if this is your bug or an xpath bug but I also found https://github.com/shepmaster/sxd-xpath/issues/133. This and that might be related.

**Comment by fdncred** [comment]
Nice @uncomfyhalomacro. Glad you figured it out. I'd love to have a better supported xpath crate, but there just aren't any that I can find. I've also seen some specifically for html too, which is separate but related.

That's not my bug. I think the biggest bug is it just seems like these crates aren't well supported.

**Comment by uncomfyhalomacro** [comment]
Yeah. Sorry it took some time. I should have made an MWE first hand before thinking of fixing this. I will close this then as **NOT YOUR BUG**.
