### ISSUE TITLE
`$env.HOME` not expanding properly in an alias

### ISSUE THREAD

**Issue by bindsdev** [nushell/nushell#8634]
### Describe the bug

I am setting up my dotfiles repository, which is a bare Git repository. I added an alias, for a long command, to my `config.nu` which allows me to do normal Git operations on the bare repository. The command is the following: `git --git-dir=PATH/TO/BARE/REPO --work-tree=PATH/TO/WORK/TREE`. My bare repository is located in my `HOME` directory. The working tree is also my `HOME` directory. If I attempted to do `--git-dir=$env.HOME/DOTFILES_REPO --work-tree=$env.HOME`, `git` would return `fatal: not a git repository: '$env.HOME/.dotfiles'`. If I used the full path (`/home/USER/`), it worked fine.

### How to reproduce

1. Initialize a bare Git repository
2. Create an alias, with the same format as I did
3. Restart your shell
4. Run the alias

### Expected behavior

I expected the alias to work since I thought `$env.HOME` would properly expand to `/home/USER/`.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.77.1                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 0120e4040d09f3bdffb945fa5fe450b72df7837a                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.68.0 (2c8cc3432 2023-03-06) (Arch Linux rust 1:1.68.0-1) |
| cargo_version      | cargo 1.68.0                                                     |
| build_time         | 2023-03-17 15:57:58 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | default, zip                                                     |
| installed_plugins  |

### Additional context

I am new to Nushell, so I am still getting used to it and learning how to use it (I love it so far). I searched the docs for an indicator of if I did anything wrong, but I couldn't find anything. If I missed something, please let me know!

**Comment by kubouch** [comment]
`--git-dir=$env.HOME/DOTFILES_REPO` is a string from Nushell's point of view. We don't auto-expand variables in strings like Bash. You'll need to do something like `$"--git-dir=($env.HOME)/DOTFILES_REPO"`.

**Comment by bindsdev** [comment]
> 

That worked perfectly. Thank you.

**Comment by bindsdev** [comment]
> `--git-dir=$env.HOME/DOTFILES_REPO` is a string from Nushell's point of view. We don't auto-expand variables in strings like Bash. You'll need to do something like `$"--git-dir=($env.HOME)/DOTFILES_REPO"`.

That worked perfectly. Thank you.
