### ISSUE TITLE
Parsing a list of environment variables

### ISSUE THREAD

**Issue by francoisthire** [nushell/nushell#8637]
### Question

Using the programming language OCaml, the workflow to get the correct dependencies for a project is to run the bash command `eval $(opam env)` when entering the project's directory.  On my computer, `opam env` gives the following output:

```bash
OPAM_SWITCH_PREFIX='/home/saroupille/Git/foo/_opam'; export OPAM_SWITCH_PREFIX;
CAML_LD_LIBRARY_PATH='/home/saroupille/Git/foo/_opam/lib/stublibs:/home/saroupille/Git/foo/_opam/lib/ocaml/stublibs:/home/saroupille/Git/foo/_opam/lib/ocaml'; export CAML_LD_LIBRARY_PATH;
OCAML_TOPLEVEL_PATH='/home/saroupille/Git/foo/_opam/lib/toplevel'; export OCAML_TOPLEVEL_PATH;
PKG_CONFIG_PATH='/home/saroupille/Git/foo/_opam/lib/pkgconfig'; export PKG_CONFIG_PATH;
MANPATH=':/home/saroupille/Git/foo/_opam/man'; export MANPATH;
PATH='/home/saroupille/Git/foo_opam/bin:/home/saroupille/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/saroupille/.pyenv/bin:/home/saroupille/.bin'; export PATH;
```

I want to add those variables to my environment with `nu`. I have crafted something a bit ad-hoc, and I wonder if there is an easier way to do add those environment variables into my environment:

```nu
opam env | split row "\n" | where {|$it| $it != ""} | split column "=" name value | each {|$it| let-env $it.name = $it.value}
```

**Comment by francoisthire** [comment]
Taking into consideration your points, my new solution is:
```nu
 opam env | lines | where $it != is-empty | split column "=" name value | reduce -f {} {|it, acc| $acc | insert $it.name $it.value} | load-env
```

Is there no conversion function that directly allows going from the table representation to a record representation?

**Comment by fdncred** [comment]
I believe you need to have a record for `load-env`, but I think you can create a record in your reduce with something like `{$it.name: $it.value}`.

**Comment by francoisthire** [comment]
So actually, the working solution ended up being more complicated since the content of the environment variables contained `export` commands:

```nu
opam env | lines | where $it != is-empty | split column "=" name value | update value { get value | split column ";" path | get path.0 | str trim -c "'"} | reduce -f {} {|it acc| $acc | insert $it.name $it.value} | load-env
```

For the value column, I had to:
1. Split around ";"
2. Select the first column
3. Remove the simple quotes

At first, I made a mistake and forgot to remove the simple quotes. The PATH did not work as expected (it was a single string). I am curious to know whether this was expected. Could a warning be generated? (I doubt having a simple quote in the value of the PATH is desired).

Also, I would have preferred to write
```nu
update value { |it| $it | split column ";" path | get path.0 | str trim -c "'"} 
```

I wonder why the `update` command did not take a closure as second argument?

**Comment by fdncred** [comment]
I put your envs in a file called test.txt. Here's another potential way to create a record of these env vars.
```

**Comment by francoisthire** [comment]
`transpose` is what I was looking for. I was not aware of those options. Many thanks!

**Comment by rhz** [comment]
For anyone that arrives here from ddg, here's a simpler, shorter command sequence that works on nushell version `0.103.0` and can be added to `env.nu`.
```nu
opam env | lines | split column ';' vars | get vars | parse "{var}='{value}'" | transpose --header-row --as-record | load-env
```
