### ISSUE TITLE
Io_error: Can't follow stream path

### ISSUE THREAD

**Issue by francoisthire** [nushell/nushell#8639]
### Describe the bug

The error seems internal to `nu` . At some point, I also got a `Broken pipe` error, but I did not manage to reproduce the issue.

```nu
> update value (get value)                                                                                               
Error: nu::shell::io_error

  × I/O error
  help: can't follow stream paths
```

### How to reproduce

Just run the snippet given above.

### Expected behavior

A better error message. Probably the correct syntax is to use curly brackets, and the error message could make such a suggestion.

### Configuration

> version | transpose key value | to md --pretty

| key                | value                                      |
| ------------------ | ------------------------------------------ |
| version            | 0.77.1                                     |
| branch             |                                            |
| commit_hash        |                                            |
| build_os           | linux-x86_64                               |
| build_target       | x86_64-unknown-linux-gnu                   |
| rust_version       | rustc 1.69.0-beta.2 (2602aa81a 2023-03-17) |
| rust_channel       | beta-x86_64-unknown-linux-gnu              |
| cargo_version      | cargo 1.69.0-beta.2 (9880b408a 2023-02-28) |
| build_time         | 2023-03-26 19:39:11 +02:00                 |
| build_rust_channel | release                                    |
| features           | default, zip                               |
| installed_plugins  |                                            |

**Comment by fdncred** [comment]
I believe update/insert/upsert need an input like `$table | update column {|r| $r.column | do_something}`. However, the error message isn't helpful.

**Comment by fdncred** [comment]
Oh, I see what you mean. I don't think it's supposed to work with parenthesis anymore. It's a closure like `ls | update name {|| get name}`

**Comment by hamza1311** [comment]
I've also encountered this error while trying to use the `not` operator:
```nushell
ls | where (get name | str starts-with aaa) | where (not (get name | str contains xxx))
Error: nu::shell::io_error

  × I/O error
  help: can't follow stream paths
```
