### ISSUE TITLE
Running 'rm' requires flag at the end

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#865]
From a recent install from master, I noticed that you have to pass the `--recursive` flag at the end. I believe the intent was to allow it to come in the middle also.

![image](https://user-images.githubusercontent.com/547158/67345295-0b4d6880-f597-11e9-9e23-85ef0ab4f113.png)

**Comment by AlexDikelsky** [comment]
Just to add to this, when you type `help rm`, it tells you to put the flag between the command name and the filenames, but throws an error when you do.

![nu_documentation](https://user-images.githubusercontent.com/52082790/67613849-f11eb080-f777-11e9-9c7c-5ec2bbeac887.png)
