### ISSUE TITLE
Attempting to open binary files returns an error

### ISSUE THREAD

**Issue by warpdesign** [nushell/nushell#8652]
### Describe the bug

Running this command is supposed to show binary file as hexa decimal:
```
> open test.png | first 100
```
But it returns an error instead:
```
> Error: nu::shell::only_supports_this_input_type
> 
>   × Input type not supported.
```
### How to reproduce

1. type `open test.png | first 100` (test.png being a valid binary file)

### Expected behavior

The first 100 bytes should be displayed as hexa decimal.

### Screenshots

<img width="664" alt="Capture d’écran 2023-03-28 à 22 57 53" src="https://user-images.githubusercontent.com/199648/228365184-7a5f7613-9fe2-4c81-bd3e-69a6c6901edd.png">

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.77.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.68.0 (2c8cc3432 2023-03-06) (built from a source tarball) |
| cargo_version      | cargo 1.68.0 (115f34552 2023-02-26)                               |
| build_time         | 2023-03-17 05:10:56 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |

**Comment by fdncred** [comment]
I'd try these 2 things.
1. open -r test.png | first 100
2. open -r test.png | into binary | first 100

I bet one of these works. I can't remember which right now.

**Comment by warpdesign** [comment]
Thanks!

The first one shows the same error (had tried it already), the second one works.

Why is that needed? In this video this works without having to pipe into binary: https://www.youtube.com/watch?v=6i4FRJ-3kkY

**Comment by fdncred** [comment]
We've changed a ton of stuff in the last 8 months. We move so fast around here. It's why I couldn't remember which one worked.

**Comment by sholderbach** [comment]
OK that sounds to me like a regression when the first alternative also fails.

**Comment by fdncred** [comment]
I believe that this PR broke it https://github.com/nushell/nushell/pull/8058
And this one was related https://github.com/nushell/nushell/pull/8399

I wanted to revert #8058, others disagreed.

**Comment by weirdan** [comment]
This now works as expected:

```console
$ open ~/Downloads/1.jpg | first 100
Length: unknown (stream) | printable whitespace ascii_other non_ascii
00000000:   ff d8 ff e0  00 10 4a 46  49 46 00 01  01 00 00 48   ××××0•JFIF0••00H
00000010:   00 48 00 00  ff e1 00 a4  45 78 69 66  00 00 4d 4d   0H00××0×Exif00MM
00000020:   00 2a 00 00  00 08 00 05  01 12 00 03  00 00 00 01   0*000•0•••0•000•
00000030:   00 01 00 00  01 1a 00 05  00 00 00 01  00 00 00 4a   0•00••0•000•000J
00000040:   01 1b 00 05  00 00 00 01  00 00 00 52  01 28 00 03   ••0•000•000R•(0•
00000050:   00 00 00 01  00 02 00 00  87 69 00 04  00 00 00 01   000•0•00×i0•000•
00000060:   00 00 00 5a                                          000Z
```
