### ISSUE TITLE
Default nushell configuration should show LAST_EXIT_CODE in the prompt

### ISSUE THREAD

**Issue by colemickens** [nushell/nushell#8655]
~~### Describe the bug~~

### Feature Request

I'm suggesting that the default prompt be changed to include `$env.LAST_EXIT_CODE` if it is non-zero.

I was testing #8646 in a pure nix shell (so not using my nushell configuration) and thought it was maybe not working. Instead, I was just getting tripped up by becoming accustomed to my own default configuration.

However, I think this is a wise default configuration change. 

### How to reproduce

Open nushell

Type `^false`

Observe that the prompt does not indicate that the last command failed.

### Expected behavior

The user can quickly, automatically know that the previous command failed.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.77.2                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07) (built from a source tarball) |
| cargo_version      | cargo 1.67.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
sounds like more than a feature request than a bug.

**Comment by colemickens** [comment]
It definitely is, that's my mistake, I powered through the issues screen too fast.

**Comment by ito-hiroki** [comment]
I'm a beginner at nushell and rust, but interested in this issue.
The goal of the issue is to display a last command failure like this image?
![image](https://user-images.githubusercontent.com/37319612/229541421-1882ca8e-e245-4548-ad58-cf088c0e1b14.png)
And it will be probably achieved by editing [here](https://github.com/nushell/nushell/blob/a256f6d0d15c9fed69365be36b3484c4c8418d21/crates/nu-utils/src/sample_config/default_env.nu#L27).
If my understanding is correct, I would like to work on it.

**Comment by fdncred** [comment]
> If my understanding is correct, I would like to work on it.

I think your screenshot is close but I'm not sure "failed" is the right indicator. I was thinking that a red exit code would be better. You can find the exit code in `$nu.LAST_EXIT_CODE` and you can check that for non-zero and display it if it is non-zero.
