### ISSUE TITLE
`math exp` missing even though referenced in documentation

### ISSUE THREAD

**Issue by lesves** [nushell/nushell#8661]
### Describe the bug

`math e` usage documentation contains a reference to `math exp`, which does not exist.

### How to reproduce

When you run `math e -h`, it says `Returns the mathematical constant e (exp(1)/'1 | math exp').`, which suggests the existence of `math exp`.

### Expected behavior

I expected `math exp` to work and `1 | math exp` to return the same thing as `math e`

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.77.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-x86_64                                                      |
| build_target       | x86_64-apple-darwin                                               |
| rust_version       | rustc 1.68.0 (2c8cc3432 2023-03-06) (built from a source tarball) |
| cargo_version      | cargo 1.68.0 (115f34552 2023-02-26)                               |
| build_time         | 2023-03-17 05:10:56 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

### Additional context

This is the first issue like this I'm submitting to an open-source project, so I'm sorry if I did a mistake. Also, I am interested in the nu shell project (it looks really cool) and I would like to try to implement `math exp` myself if you agree. I think it could be a good way for me to get started with contributing to this project.

**Comment by lesves** [comment]
So I implemented it in PR #8700.

**Comment by lesves** [comment]
Since the PR is merged, I'm closing this issue. Thank you all:)

**Comment by sholderbach** [comment]
Thanks you for managing that so expediently!
