### ISSUE TITLE
Command redirection doesn't respect `$env.PWD`/previous `cd` s in the block

### ISSUE THREAD

**Issue by Z-snails** [nushell/nushell#8664]
### Describe the bug

Command redirection using `out>` doesn't respect previous `cd`s in the block, or changes to `$env.PWD`.
Instead it always works relative to the "outer" pwd (I'm totally sure what pwd, but not the one I'd expect)

### How to reproduce

1. Create a folder `folder`
2. In the parent directory of `folder` run
```
cd folder; echo "oh no" out> output
```

### Expected behavior

File `folder/output` is created, containing the test "oh no"

Instead a file `output` is created not in `folder`

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.77.1                                   |
| branch             |                                          |
| commit_hash        | 0120e4040d09f3bdffb945fa5fe450b72df7837a |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-03-17 05:17:52 +00:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by weirdan** [comment]
This doesn't happen anymore

```console
$ rm /tmp/output

$ cd /tmp; echo "oh no" out> output

$ pwd
/tmp

$ ls -l output
╭───┬────────┬──────┬────────┬──────────┬───────────┬───────────┬───────┬─────────┬─────────┬──────┬─────────┬──────────┬──────────╮
│ # │  name  │ type │ target │ readonly │   mode    │ num_links │ inode │  user   │  group  │ size │ created │ accessed │ modified │
├───┼────────┼──────┼────────┼──────────┼───────────┼───────────┼───────┼─────────┼─────────┼──────┼─────────┼──────────┼──────────┤
│ 0 │ output │ file │        │ false    │ rw-rw-r-- │         1 │ 74098 │ weirdan │ weirdan │  5 B │ now     │ now      │ now      │
╰───┴────────┴──────┴────────┴──────────┴───────────┴───────────┴───────┴─────────┴─────────┴──────┴─────────┴──────────┴──────────╯

$ rm output
```
