### ISSUE TITLE
Panic in inspect 

### ISSUE THREAD

**Issue by bgeron** [nushell/nushell#8671]
### Describe the bug

Panic in `inspect`.

```
thread 'main' panicked at 'assertion failed: min <= max', /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/cmp.rs:867:9
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: nu_command::debug::inspect_table::build_table
   4: <nu_command::debug::inspect::Inspect as nu_protocol::engine::command::Command>::run
   5: nu_engine::eval::eval_call
   6: nu_engine::eval::eval_expression_with_input
   7: nu_engine::eval::eval_element_with_input
   8: nu_engine::eval::eval_block
   9: nu_cli::commands::evaluate_commands
  10: nu::run::run_commands
  11: nu::main
```

### How to reproduce

nu 0.77

`{a: [], ab: [], abc: [], abcdefg: [], abcdefgh: [], abcdefghijklm: [], abcdefghijklmno: []} | inspect`

### Expected behavior

No panic.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.77.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10) |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10) |
| build_time         | 2023-03-16 12:23:56 +01:00          |
| build_rust_channel | release                             |
| features           | default, zip                        |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
Debugging this on 0.77.2 I get
```
{a: [], ab: [], abc: [], abcdefg: [], abcdefgh: [], abcdefghijklm: [], abcdefghijklmno: []} | inspect
╭─────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ description │ record<a: list<any>, ab: list<any>, abc: list<any>, abcdefg: list<any>, abcdefgh: list<any>, abcdefghijklm: list<any>, abcdefghijklmno: list<any>> │
├─────────────┴────┬─────────────────┬──────────────────┬──────────────────────┬───────────────────────┬────────────────────────────┬──────────────────────────────┤
│ a                │ ab              │ abc              │ abcdefg              │ abcdefgh              │ abcdefghijklm              │ abcdefghijklmno              │
├──────────────────┼─────────────────┼──────────────────┼──────────────────────┼───────────────────────┼────────────────────────────┼──────────────────────────────┤
│ []               │ []              │ []               │ []                   │ []                    │ []                         │ []                           │
╰──────────────────┴─────────────────┴──────────────────┴──────────────────────┴───────────────────────┴────────────────────────────┴──────────────────────────────╯

╭─────────────────┬────────────────╮
│ a               │ [list 0 items] │
│ ab              │ [list 0 items] │
│ abc             │ [list 0 items] │
│ abcdefg         │ [list 0 items] │
│ abcdefgh        │ [list 0 items] │
│ abcdefghijklm   │ [list 0 items] │
│ abcdefghijklmno │ [list 0 items] │
╰─────────────────┴────────────────╯
```

I just compiled in release mode off the latest main and it seems to work on Windows just fine.

**Comment by fdncred** [comment]
@zhiburt Any ideas what's going on here in `nu_command::debug::inspect_table::build_table`. It's working on Windows but panicing in Linux/MacOS.

**Comment by bgeron** [comment]
I can confirm that this does not panic with a large terminal. But with a small terminal it breaks.

**Comment by fdncred** [comment]
I changed that line to this and it seems to work now
```rust
    let width = if desc_table_width > termsize {
        val_table_width.clamp(termsize, desc_table_width)
    } else {
        val_table_width.clamp(desc_table_width, termsize)
    };
```

**Comment by bgeron** [comment]
Even more minimal example: `nu -c '[] | inspect' | cat`. @fdncred , I guess that's covered by your fix too?

**Comment by fdncred** [comment]
> Even more minimal example: nu -c '[] | inspect' | cat. @fdncred , I guess that's covered by your fix too?

I'm not sure. Let me try it out.

**Comment by bgeron** [comment]
It's covered by #8673 + #8674 .

**Comment by bgeron** [comment]
But the output is very strange.

`nu -c '[] | inspect'`: 

```
╭─────────────┬───────────╮
│ description │ list<any> │


╭────────────╮
│ empty list │
╰────────────╯
```

`nu -c '[] | inspect' | cat`:

```
╭──┬──╮
│  │  │


```

Anyway, it's not so related.

**Comment by fdncred** [comment]
It still fails. I'm not quite sure what the right fix for `[] | inspect` should be.
