### ISSUE TITLE
Autoload functions from a given folder

### ISSUE THREAD

**Issue by oyarsa** [nushell/nushell#8676]
### Related problem

The fish shell allows users to add files in the `functions` directory that are loaded at startup, and the functions become available to the user in the shell. 

I've found a few related issues, and I understand I can use `NU_LIBS_DIR` to `use` or `source` a script without using the full path, but that's not the same.

### Describe the solution you'd like

It should be possible to have `nu` automatically source scripts and make the commands available in the shell. Adding new commands shouldn't require changing a configuration file.

### Describe alternatives you've considered

I've tried using `NU_LIBS_DIR`, but it's necessary to `source` the files before using the commands.

### Additional context and details

Fish's autoload: https://fishshell.com/docs/current/language.html#syntax-function-autoloading

**Comment by amtoine** [comment]
@oyarsa, as proposed by @dedebenui, you can put your scripts and modules inside one of the path in `NU_LIB_DIRS`.

in https://github.com/nushell/nushell/issues/9597, i suspect the documentation is incorrect and thus won't work if you follow it step by step :thinking:

**Comment by weirdan** [comment]
As of 0.96 there's a mechanism (intended for third-party package managers) that does just that: https://www.nushell.sh/blog/2024-07-23-nushell_0_96_0.html#autoload-directories-for-package-managers-toc
