### ISSUE TITLE
Create a GitHub issue template

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#868]
Things we probably want in an issue template:

* Version of Nu they're running
* Platform they're running Nu on
* What plugins are installed (if applicable)
* Where they installed Nu from

**Comment by wycats** [comment]
If we do this, I'd like to add a command to nu that fills in the template for you.

**Comment by jonathandturner** [comment]
Sounds good. We have issue templates now, so we could look at creating a command
