### ISSUE TITLE
Tests fail on main branch

### ISSUE THREAD

**Issue by lesves** [nushell/nushell#8687]
### Describe the bug

When I cloned the repo and ran tests, one of them failed.
```
---- conversions::into::string::test::test_examples stdout ----
thread 'conversions::into::string::test::test_examples' panicked at 'assertion failed: `(left == right)`
  left: `String { val: "5,000", span: Span { start: 0, end: 0 } }`,
 right: `String { val: "5.000", span: Span { start: 0, end: 0 } }`: The example result differs from the expected value', crates/nu-cmd-lang/src/example_support.rs:180:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I think this may be related to some locale settings

### How to reproduce

```nu
git clone git@github.com:nushell/nushell.git
cd nushell
cargo test --workspace
```

### Expected behavior

I expected the tests to pass.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.77.2                                   |
| branch             | main                                     |
| commit_hash        | 3db0aed9f739fd929f8dff287fafd60883649c07 |
| build_os           | macos-x86_64                             |
| build_target       | x86_64-apple-darwin                      |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-apple-darwin               |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-03-31 11:14:16 +02:00               |
| build_rust_channel | debug                                    |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I've seen this before. It's because your locale is not what nushell is expecting which is why one says 5,000 and the other says 5.000

**Comment by sholderbach** [comment]
This is the same issue as #10018, as the other issue contains mentions the underlying localization issue, I will close this one.
