### ISSUE TITLE
Different params with sink vs. filter plugin

### ISSUE THREAD

**Issue by vsoch** [nushell/nushell#869]
I'm not sure if this is a bug, but the "params" that are passed from nushell to the plugin seems to vary based on having a filter or a sink. 

## Sink

Specifically, for a sink we get a list, where the first entry (index 0) is the args dict we are looking for:

```python
[{'args': {'positional': None,
         'named': {'switch': {'tag': {'anchor': None,
            'span': {'start': 58, 'end': 64}},
           'item': {'Primitive': {'Boolean': True}}},
          'mandatory': {'tag': {'anchor': None, 'span': {'start': 20, 'end': 32}},
           'item': {'Primitive': {'String': 'MANDATORYARG'}}},
          'optional': {'tag': {'anchor': None, 'span': {'start': 44, 'end': 55}},
           'item': {'Primitive': {'String': 'OPTIONALARG'}}}}},
        'name_tag': {'anchor': None, 'span': {'start': 0, 'end': 7}}},
       []]
```
And notice the index 1 (second entry) is an empty list.

## Filter
And for the filter, we get just the dictionary (this would be what I would generally expect).

```python
{"args":{"positional":null,"named":{"help":{"tag":{"anchor":null,"span":{"start":6,"end":10}}
```
I'm going to mark this as a bug, and please edit/change if this is not correct!

**Comment by andrasio** [comment]
@vsoch Hi!

How are we doing on this issue? All questions answered?

**Comment by vsoch** [comment]
hey @andrasio ! Apologies for not closing this, you answered it almost immediately on Discord! For future readers, the difference is that a filter is just passing a lookup with args, but for a sink we need to pass this same lookup (first index) and then the second index is the output if the sink is used as a pipe. E.g.,:

```
echo "This content will appear at index 1" | mysink
```
And this is the reason for the different structures. Thanks @andrasio
