### ISSUE TITLE
invalid `help` pages with examples that do not use `{|| ... }` on closures

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8694]
### Describe the bug

related to #8273.

with the introduction of the mandatory `||` in closures, even with anonymous arguments, some of the `help` pages are not valid anymore and give invalid `nushell`...

the list of all the invalid commands i found
```
ansi gradient
date to-timezone
dfr expr-not
explain
explore
ls
par-each
path parse
profile
rm
shuffle
view source
watch
where
zip
```

### examples
```bash
>_ explain { ls | sort-by name type -i | get name } | table -e
Error: nu::parser::closure_missing_pipe

  × Missing || inside closure
   ╭─[entry #5:1:1]
 1 │ explain { ls | sort-by name type -i | get name } | table -e
   ·         ────────────────────┬───────────────────
   ·                             ╰── Parsing as a closure, but || is missing
   ╰────
  help: Try add || to the beginning of closure
```
or
```bash
>_ def spam [] { "spam" }; profile { spam | str length } -d 2 --source
Error: nu::parser::closure_missing_pipe

  × Missing || inside closure
   ╭─[entry #6:1:1]
 1 │ def spam [] { "spam" }; profile { spam | str length } -d 2 --source
   ·                                 ──────────┬──────────
   ·                                           ╰── Parsing as a closure, but || is missing
   ╰────
  help: Try add || to the beginning of closure
```

### How to reproduce

run the following and see some red highlights in all the pages
```bash
[
    "ansi gradient"
    "date to-timezone"
    "dfr expr-not"
    "explain"
    "explore"
    "ls"
    "par-each"
    "path parse"
    "profile"
    "rm"
    "shuffle"
    "view source"
    "watch"
    "where"
    "zip"
] | each {|| help $in}
```

### Expected behavior

these examples should be valid `nushell`.
that's also a good opportunity to give these tests result outputs => the test would probably not have passed with defined outputs :yum: 

### Configuration

| key                | value                                               |
| ------------------ | --------------------------------------------------- |
| version            | 0.77.2                                              |
| branch             | feature/implement-help-commands-in-standard-library |
| commit_hash        | 6f7c7a18d1e5128d8c3ab6d7a7054f6268c598c5            |
| build_os           | linux-x86_64                                        |
| build_target       | x86_64-unknown-linux-gnu                            |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)                 |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu                     |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)                 |
| build_time         | 2023-03-29 19:32:23 +02:00                          |
| build_rust_channel | release                                             |
| features           | default, zip                                        |
| installed_plugins  | gstat                                               |

**Comment by amtoine** [comment]
@Tlntin 
yup that's a recent breaking change :+1: 

the documentation is not fully updated now :thinking: 
especially on example like this that do not run during the tests.

**Comment by MariaSolOs** [comment]
I think this is no longer needed because of #8846 (?) @amtoine

**Comment by amtoine** [comment]
> I think this is no longer needed because of #8846 (?) @amtoine
>
absolutely not needed anymore, nice catch :sparkles:
