### ISSUE TITLE
Cannot disable banner

### ISSUE THREAD

**Issue by zlaus** [nushell/nushell#8698]
### Describe the bug

Hi, sorry for this being the first thing i bring up ;) 

When adding show_banner: false to the default config, the banner is not disabled.

documentation says to disable the welcome banner you need to add

let-env config = {
  ...
  show_banner: false,
  ...
}

but it doesnt work?

I searched but didnt find similar problems and also tinkered with the config file, skipping the comma at the end or entering pure garbage to make sure the file is actually read, but to no avail. Still think i am missing something?

### How to reproduce

1. cargo install nu
2. edit .config/nushell/config.nu like this

![Bildschirmfoto vom 2023-04-01 07-23-50](https://user-images.githubusercontent.com/7562487/229267218-5b56f6ae-12d9-4603-aa3f-362e1c741b22.png)

3. Open a fresh nushell to see the banner present

### Expected behavior

I expected the banner to disappear

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.77.1                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.65.0 (Fedora 1.65.0-1.fc37) |
| cargo_version      | cargo 1.65.0                        |
| build_time         | 2023-03-31 23:31:35 +02:00          |
| build_rust_channel | release                             |
| features           | default, zip                        |
| installed_plugins  |                                     |

**Comment by amtoine** [comment]
hey @zlaus :wave: 

this is something that might need to be changed as discussed in the discord server :thinking: 

the default config file already has a `show_banner` line at the bottom, so when you write `show_banner: false` at the top of the config, it gets overwritten by the `show_banner: true` at the bottom :eyes: 

could you check that it's the issue you have indeed? :yum:

**Comment by amtoine** [comment]
i hope the two PRs above will clarify this (very common) situation, sorry for the confusing "bug" you get :relieved:

**Comment by zlaus** [comment]
m) should have seen it.  thanks for clarifying!
