### ISSUE TITLE
Using the same field twice in a record should not silently overwrite previous value

### ISSUE THREAD

**Issue by jntrnr** [nushell/nushell#8699]
### Describe the bug

If we use the same field name twice, we currently overwrite the first value with the second, silently. For example:
```
> {a: true, a: false }
╭───┬───────╮
│ a │ false │
╰───┴───────╯
```

### How to reproduce

1. See above

### Expected behavior

I believe we should give an error if we try to use the same field/column name twice, as this likely points towards a mistyping.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.77.2                                   |
| branch             | main                                     |
| commit_hash        | 97e7d550c81fa3a131fb362a7a29d860625dacc0 |
| build_os           | macos-aarch64                            |
| build_target       | aarch64-apple-darwin                     |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-aarch64-apple-darwin              |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-03-29 21:04:38 +13:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by arnfaldur** [comment]
I was trying to do this to replace `a`:
```nu
let dic = { a: 1, b: 2 };
{ ...$dic, a: 2 }
```
but that caused an error due to this PR.
It can be solved like this:
```nu
let dic = { a: 1, b: 2 };
{ ...($dic | reject a), a: 2 }
```

I'm commenting this in case anyone finds this for the same reason I did.
