### ISSUE TITLE
`post` command is not parsing arguments correctly

### ISSUE THREAD

**Issue by notryanb** [nushell/nushell#872]
I am receiving errors when trying to use the `post` command to send a request with `Content-Type: application/json`.

I would love to help out and fix this issue. 

Documentation from `post help` states this as the signature
`> post {flags} <path> <body>`

Some examples:
`post --content-type="application/json" http://localhost:50212/api/v1/test 'ryan'`
=> Parse Error: highlights entire line from the first `"`

`post --content-type='application/json' http://localhost:50212/api/v1/test  'ryan'`
=> Parse Error: highlights entire line from the first `'`

`post --content-type 'application/json' http://localhost:50212/api/v1/test  'ryan'`
=> Syntax Error: unexpected whitespace right after the `application/json'`

As an aside, I've verified the payload and endpoint work using Postman and curl.

**Comment by jonathandturner** [comment]
@notryanb I think this is fixed with the recent parser update, as best as I can tell. Closing, but please re-open if you can still repro it in master.
