### ISSUE TITLE
There is no `-d` flag for `touch` command

### ISSUE THREAD

**Issue by presidento** [nushell/nushell#8723]
### Describe the bug

Copy-pasted from `help touch` or from the [online documentation](https://www.nushell.sh/commands/docs/touch.html):

```
❯  touch -m -d "yesterday" a b c
Error: nu::parser::unknown_flag

  × The `touch` command doesn't have flag `-d`.
   ╭─[entry #1:1:1]
 1 │  touch -m -d "yesterday" a b c
   ·            ┬
   ·            ╰── unknown flag
   ╰────
  help: Available flags: --help(-h), --reference(-r), --modified(-m), --access(-a), --no-create(-c). Use `--help` for more information.
```

### How to reproduce

```
❯  touch -m -d "yesterday" a b c
```

### Expected behavior

Adding the `-d` flag to the `touch` command would be preferable. Or remove it from the documentation and the help message.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.77.1                                   |
| branch             |                                          |
| commit_hash        | 0120e4040d09f3bdffb945fa5fe450b72df7837a |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-03-17 05:15:37 +00:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I believe @jntrnr's #6629 removed the `-d` argument.

**Comment by onthebridgetonowhere** [comment]
The docs need to be fixed or someone could take a stab at bringing back in the `-d` argument.

**Comment by fdncred** [comment]
> The docs need to be fixed or someone could take a stab at bringing back in the `-d` argument.

I'd vote for bringing it back and either manually reverting that PR *AND* fixing whatever bugs it has or start it over again.

**Comment by onthebridgetonowhere** [comment]
I'm tempted to take a stab at it these days, but for now how about we update the docs? 
nushell/nushell.github.io#858

**Comment by onthebridgetonowhere** [comment]
Working on this in #8858
