### ISSUE TITLE
Nu semicolon is not like bash and is broken

### ISSUE THREAD

**Issue by Alex-EEE** [nushell/nushell#8726]
### Describe the bug

In bash, cmd ; cmd2, cmd2 should ALWAYS run.  If you want cmd2 to not run, you want to use &&

### How to reproduce

True ; echo 'should run'
False ; echo 'should run, but doesn't!!!!'

### Expected behavior

'should run, but doesnt'

### Configuration

└ $ version | transpose key value | to md --pretty
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.77.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-x86_64                                                      |
| rust_version       | rustc 1.68.0 (2c8cc3432 2023-03-06) (built from a source tarball) |
| cargo_version      | cargo 1.68.0 (115f34552 2023-02-26)                               |
| build_time         | 2023-03-17 05:10:56 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

**Comment by Alex-EEE** [comment]
similar to https://github.com/nushell/nushell/issues/3858, but that issue is completely wrong in its description of bash behavior

**Comment by peterallin** [comment]
#3858 refers to the Nushell documentation and does not try to describe Bash behavior.

**Comment by Alex-EEE** [comment]
well in that case, is there a way to run a command in bash regardless of the exit code of the first command??

**Comment by sholderbach** [comment]
nushell doesn't strive to follow bash's general POSIX-related semantics.

We arrived for error handling at a design that favors failing early similar to `set -ex -o pipefail` (but with a different richer model for nushell internal errors).

Depending on your needs there are the [flags on `do`](https://www.nushell.sh/commands/docs/do.html) and the [`try`(-`catch`) block](https://www.nushell.sh/commands/docs/try.html) to explicitly ignore or handle the error case.
