### ISSUE TITLE
Space required before beginning a comment after a command used for completion on an `extern`

### ISSUE THREAD

**Issue by lily-mara** [nushell/nushell#8731]
### Describe the bug

After upgrading to nu 0.77 (was previously using 0.76 with no issue), I found that my `config.nu` file was failing to parse with a "this command not found" error. Eventually I realized that one of my `extern` blocks provided a function to be used for completion on one of the arguments that had no space between the end of the command name and the beginning of an explanatory comment. This block was lifted straight from the [docs](https://github.com/nushell/nushell.github.io/blob/9cd7e165d360264b6e3b2ec6bb77ca4f18ba2793/book/externs.md?plain=1#L10), so either the functionality is broken or the docs need to be updated.

### How to reproduce

Add the following to a file

```
def "funk" [] {
}

extern "x" [
    arg?: string@"funk" # has a space
]

extern "y" [
    arg?: string@"funk"# has no space
]
```

Execute the file

```
/Users/lily〉nu test.nu                                                                                                   
Error: nu::parser::unknown_command

  × Unknown command.
    ╭─[/Users/lily/test.nu:8:1]
  8 │ extern "y" [
  9 │     arg?: string@"funk"#
    ·                  ───┬───
    ·                     ╰── unknown command
 10 │ ]
    ╰────
```

Notice that the first `extern` block that has a space between the command name and the comment parses just fine, but the second errors.

### Expected behavior

Treat the comment and the string before the comment as separate tokens

### Configuration

```
| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.77.1                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | macos-aarch64                       |
| build_target       | aarch64-apple-darwin                |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07) |
| rust_channel       | stable-aarch64-apple-darwin         |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10) |
| build_time         | 2023-03-31 16:14:49 -07:00          |
| build_rust_channel | release                             |
| features           | default, zip                        |
| installed_plugins  |                                     |
```

**Comment by sholderbach** [comment]
We changed the comment lexing in https://github.com/nushell/nushell/pull/8151 demanding a space or new line to support bare word strings containing `foo#bar` as frequently found in nix related scripts.

So this is indeed a breaking change and requires an update to our documentation. Thanks for pointing to the problematic examples!

**Comment by lily-mara** [comment]
Thanks! I think I also was not able to find things related to "comment" in the changelog, so it took me a bit to track this down. Should it have been reported in the 0.77 release?

**Comment by sholderbach** [comment]
Ah right! That slipped through the cracks.

**Comment by MangoIV** [comment]
Please excuse me @lily-mara @sholderbach, this was my fault.

**Comment by weirdan** [comment]
I think this issue can be closed since it's by design and already documented.
