### ISSUE TITLE
Name conflict with macports.

### ISSUE THREAD

**Issue by ShikiSuen** [nushell/nushell#8733]
### Describe the bug

Command name conflict with MacPorts.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/3164826/229705506-817f0521-7f8e-4bbb-8423-5c06d6e464d4.png">

### How to reproduce

Install NUShell 0.72 with MacPorts together.

Run `port select --list clang`.

### Expected behavior

```
port select --list clang
Available versions for clang:
	mp-clang-13
	mp-clang-14 (active)
	none
```

### Screenshots

```
/Users/shikisuen/Repos: port select --list clang
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[entry #6:1:1]
 1 │ port select --list clang
   ·      ───┬──
   ·         ╰── expected int
   ╰────
```

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.77.1                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-x86_64                                                      |
| build_target       | x86_64-apple-darwin                                               |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07) (built from a source tarball) |
| cargo_version      | cargo 1.67.0                                                      |
| build_time         | 2023-03-17 11:21:48 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

**Comment by kubouch** [comment]
There are several cases when our commands overlap with some installed programs. We can re-evaluate the need for a `port` command, or its name, but in general, it's impossible to completely avoid name collisions. You can use `^` to force-run the external program, for example, `^port`.
