### ISSUE TITLE
mut ref parameters support  for function?

### ISSUE THREAD

**Issue by lost22git** [nushell/nushell#8739]
### Related problem

I don't know if mut ref parameter for function is supported now. (At least not from the docs)

### Describe the solution you'd like

support mut ref parameter def

**Comment by fdncred** [comment]
Can you provide an example of how you'd like this to look and work?

**Comment by lost22git** [comment]
```nu
def test-mut-ref [a:mut record ] {
  $a.name = "bar"
}

mut a = { name:"foo" }
test-mut-ref $a

print $a // { name:"bar" }
```

**Comment by fdncred** [comment]
I see what you mean. We'll have to get @jntrnr to chime in.

In the mean time, you can try something like this.
```
> mut a = {name: 'foo'}
> def test [name] { 
  { name: ($name) }
}
> test 'foo'
╭──────┬─────╮
│ name │ foo │
╰──────┴─────╯
> $a = (test 'bar')
> $a
╭──────┬─────╮
│ name │ bar │
╰──────┴─────╯
```
