### ISSUE TITLE
Publish 0.78 version to Homebrew

### ISSUE THREAD

**Issue by whiteand** [nushell/nushell#8742]
### Related problem

I cannot install 0.78 using homebrew

### Describe the solution you'd like

To publish 0.78 to homebrew

**Comment by fdncred** [comment]
Thanks for the note.
The nushell homebrew is already maintained by someone else. You can see it here https://formulae.brew.sh/formula/nushell#default

Last I looked, they need to change their build features too. They're pretty quick to follow our release, iirc.
