### ISSUE TITLE
doubt: why is the access API of record designed in this way?

### ISSUE THREAD

**Issue by lost22git** [nushell/nushell#8746]
### Question

```shell

╰─❯ mut a = {x:1}

╰─❯ $a.y = 2 // we can insert a not_exist column

╰─❯ $a
╭───┬───╮
│ x │ 1 │
│ y │ 2 │
╰───┴───╯

╰─❯ $a.z  // we can not access not_exist column (convenient but no usage scenario)
Error: nu::shell::column_not_found

  × Cannot find column
   ╭─[entry #129:1:1]
 1 │ $a.z
   · ─┬ ┬
   ·  │ ╰── cannot find column 'z'
   ·  ╰── value originates here
   ╰────


╰─❯ $a | get z -i  //  only way to access not_exist column
```

**Comment by fdncred** [comment]
> $a | get z -i  //  only way to access not_exist column

That's not the only way. You can also do `$a | get z?`

**Comment by lost22git** [comment]
Don’t you think that operators like $a.z become meaningless?

**Comment by fdncred** [comment]
It's hard to have discussions here. If you want to discuss why things are implemented a certain way, the best place to do it is in our Discord.

**Comment by mon-jai** [comment]
> ```
> ╰─❯ $a.z  // we can not access not_exist column (convenient but no usage scenario)
Error: nu::shell::column_not_found
> ```

Maybe you are looking for optional chaining.

> Don’t you think that operators like $a.z become meaningless?

That makes it easier to access nested property I think.

**Comment by lost22git** [comment]
@mon-jai  

Almost, I just think it's not good to use two sets of APIs in the code
we write use $a.z = 1
we read use $a | get z -i
As you said optional chaning, maybe `$a?.z?` would be better for scripting languages

**Comment by mon-jai** [comment]
> @mon-jai
> 
> Almost, I just think it's not good to use two sets of APIs in the code we write use $a.z = 1 we read use $a | get z -i As you said optional chaning, maybe `$a?.z?` would be better for scripting languages

Optional chaining is already a feature in Nushell: #8379

`get` is designed to be useful in other scenarios, like:

```
~ > [{ foo: 1 }, { foo: 2 }] | get foo
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 2 │
╰───┴───╯
```
