### ISSUE TITLE
how to use mutable variable in catch closure

### ISSUE THREAD

**Issue by lost22git** [nushell/nushell#8747]
```nushell
╰─❯ open test.nu
mut a = 1
try {
  1 / 0
} catch { |e|
  $a = 2
}

$a

╰─❯ nu test.nu
Error: nu::parser::expected_keyword

  × Capture of mutable variable.
   ╭─[E:\_case\test.nu:4:1]
 4 │ } catch { |e|
 5 │   $a = 2
   ·   ─┬
   ·    ╰── capture of mutable variable
 6 │ }
   ╰────
```

**Comment by fdncred** [comment]
I believe, at this time, mutation is not available in any closures, which is why you're getting that error.

**Comment by lost22git** [comment]
@fdncred 
Is there any improvement in this regard in the future, or think that this is meaningless or the design is originally designed like this

**Comment by fdncred** [comment]
@lost22git For the longest time, more than 2 years, there was no mutability whatsoever as the original design for nushell was zero-mutability. Now, at least we have some. It remains to be seen whether mutability will increase in nushell in the future. We'll have to wait and see.
