### ISSUE TITLE
0.78 closures?

### ISSUE THREAD

**Issue by ngmisl** [nushell/nushell#8749]
### Question

  × Missing || inside closure
    ╭─[/home/x/.config/nushell/env.nu:21:1]
 21 │ # Use nushell functions to define your right and left prompt
 22 │ let-env PROMPT_COMMAND = { create_left_prompt ||}
    ·                          ────────────┬───────────
    ·                                      ╰── Parsing as a closure, but || is missing
 23 │ let-env PROMPT_COMMAND_RIGHT = { create_right_prompt ||}
    ╰────
  help: Try add || to the beginning of closure

Error: nu::parser::closure_missing_pipe

  × Missing || inside closure
     ╭─[/home/x/.config/nushell/config.nu:139:1]
 139 │     # The value (in this case, a bool) is piped into the closure.
 140 │     bool: { if $in { 'light_cyan' } else { 'light_gray' } }
     ·           ────────────────────────┬────────────────────────
     ·                                   ╰── Parsing as a closure, but || is missing
 141 │     int: white
     ╰────
  help: Try add || to the beginning of closure

Tried fixing this, but it just won't pass. can anyone help please?

**Comment by WindSoilder** [comment]
Yeah, you can add `||` as suggested, like:
`bool: { if $in { 'light_cyan' } else { 'light_gray' } }` to `bool: {|| if $in { 'light_cyan' } else { 'light_gray' } }`
and `let-env PROMPT_COMMAND = { create_left_prompt }` to `let-env PROMPT_COMMAND = {|| create_left_prompt }`

**Comment by ngmisl** [comment]
thanks... it's breaking a lot now
