### ISSUE TITLE
Deprecate “in” variable

### ISSUE THREAD

**Issue by Hofer-Julian** [nushell/nushell#8753]
It seems like some (all?) closures define an `in` variable.

`[foo bar 2 baz] | all {|| ($in | describe) == 'string' }`

That probably made sense a couple of nushell versions ago. However, nowadays all closures require `||`.
Personally, I would find a program less surprising if `in` would only be a parameter of the closure.

**Comment by fdncred** [comment]
I'm not sure we'll deprecate it but I think it's confusing in examples like this. I think it should be rewritten like this.
```
[foo bar 2 baz] | all {|r| ($r | describe) == 'string' }
```

**Comment by sholderbach** [comment]
`$in` as the input stream in theory has some slightly different semantics compared to closure/command arguments. It is the variable manifestation of a `PipelineData` compared to a `Value` in theory (not sure if it makes a `Value` step in practice).

**Comment by Hofer-Julian** [comment]
Thanks for the explanation. I guess I also should have been more precise with my issue. I wondered if it makes sense that commands like `all` set input parameters and also stream to the closure. I feel like only setting the input parameter would make more sense. Or am I missing something?

**Comment by Hofer-Julian** [comment]
This can be closed, now that https://github.com/nushell/nushell/pull/8846 has been merged
