### ISSUE TITLE
`config env`/`config nu` opens the default file

### ISSUE THREAD

**Issue by JadoJodo** [nushell/nushell#8755]
## System Details
Nu Version: 0.77.1
Platform: macOS 12.6.3

## Steps To Recreate

1. Launch nu with config/env values defined with the `--config` and `--env` flags.
2. Run `config nu` or `config env`

## Expected Behavior
Nu opens the file defined in `$nu.config-path` or `$nu.env-path`: `/Users/myuser/.config/nushell/config.nu` or `/Users/myuser/.config/nushell/env.nu`.

## Actual Behavior
Nu opens the file defined in the default location:  `/Users/myuser/Library/Application Support/nushell/env.nu` or `/Users/myuser/Library/Application Support/nushell/config.nu`

**Comment by fdncred** [comment]
Seems like a bug. Thanks for letting us know.

**Comment by ito-hiroki** [comment]
I'm interested in contributing to this issue.
Can I work on it?

**Comment by fdncred** [comment]
> I'm interested in contributing to this issue.
> 
> Can I work on it?

Sure. I've assigned it to you.
