### ISSUE TITLE
completion of int seems to be broken

### ISSUE THREAD

**Issue by fj0r** [nushell/nushell#8756]
### Describe the bug

completion of int seems to be broken

### How to reproduce

```
def some_int [] {
    [1 2 3]
}

export def test_int [a: int@some_int] {
    echo $a
}
```
run `test_int 123` would get 
```
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[entry #2:1:1]
 1 │ test_int 123
   ·          ─┬─
   ·           ╰── expected number-like value (int, float, date, etc)
   ╰────
```

### Expected behavior

`test_int 123` should print 123

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.78.0                                   |
| branch             |                                          |
| commit_hash        | 2ec20286371f1d90a77fdd5d82818c6c5851f090 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-musl                |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-04-04 19:10:32 +00:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by weirdan** [comment]
It works now.
