### ISSUE TITLE
Suggestion: rename `add` to `insert`

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#876]
Thinking about our command terms a bit, I feel like `add` is too overloaded. We have some math operations, and it's easy to see `add` and to think that it's one of the math operations.

I think we may want to rename it to `insert` to avoid confusion.

**Comment by vsaurabh04** [comment]
Hi, I would like to work on it.

**Comment by jonathandturner** [comment]
@vsaurabh04 - sounds good!

**Comment by andrasio** [comment]
Closing. Change already done in master.
