### ISSUE TITLE
How do aliases work?

### ISSUE THREAD

**Issue by chocological00** [nushell/nushell#8760]
### Question

From the [nushell book](https://www.nushell.sh/book/aliases.html), I see that you can make aliases to have pipes, like:

```nu
alias lt = (ls | sort-by modified -r | sort-by type)
```

However, when I attempt to run this alias, I get:
```
~> alias lt = (ls | sort-by modified -r | sort-by type)
~> lt 
Error: nu::shell::cant_convert

  × Can't convert to string.
   ╭─[entry #34:1:1]
 1 │ alias lt = (ls | sort-by modified -r | sort-by type)
   ·            ────────────────────┬────────────────────
   ·                                ╰── can't convert table<name: string, type: string, size: filesize, modified: date> to string
   ╰────
```

Am I misunderstanding something?

### Additional context and details

`nu --version` gives 0.78.0.

Arch, Kernel 6.2.9

**Comment by mon-jai** [comment]
alias is a parser keyword.

Therefore your alias statement will be interpreted as setting `lt` to be the shortcut for an executable with the name `(ls | sort-by modified -r | sort-by type)`, which doesn't exist in your system.

See https://github.com/nushell/nushell/issues/7753#issuecomment-1382874524 for previous discussions.

**Comment by kubouch** [comment]
The book apparently needs updating. We recently switched to a new alias implementation where aliases need to wrap a command call. See https://www.nushell.sh/blog/2023-03-14-nushell_0_77.html#reworked-aliases-breaking-changes-kubouch and the related PR linked from there.

**Comment by kubouch** [comment]
Forgot to mention, instead of subexpression, it's better to define a custom command.
