### ISSUE TITLE
Parse mismatch during operation ？why

### ISSUE THREAD

**Issue by lost22git** [nushell/nushell#8761]
### Describe the bug

```nushell

╰─❯ open test.nu
def test [
    value:record
] {
    mut a = $value
    $a.z = 3
    $a
}

mut a  = {x:1}
$a.y = 2
$a = test $a
$a

╰─❯ nu test.nu
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
    ╭─[E:\_case\test.nu:10:1]
 10 │ $a.y = 2
 11 │ $a = test $a
    ·           ─┬
    ·            ╰── expected operator
 12 │ $a
    ╰────
```

### How to reproduce

```nushell

╰─❯ open test.nu
def test [
    value:record
] {
    mut a = $value
    $a.z = 3
    $a
}

mut a  = {x:1}
$a.y = 2
$a = test $a
$a

╰─❯ nu test.nu
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
    ╭─[E:\_case\test.nu:10:1]
 10 │ $a.y = 2
 11 │ $a = test $a
    ·           ─┬
    ·            ╰── expected operator
 12 │ $a
    ╰────
```

### Expected behavior

print {x:1 y:2 z:3}

### Configuration

 key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.77.1                                      |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | windows-x86_64                              |
| build_target       | x86_64-pc-windows-msvc                      |
| rust_version       | rustc 1.69.0-nightly (f77bfb733 2023-03-01) |
| rust_channel       | nightly-x86_64-pc-windows-msvc              |
| cargo_version      | cargo 1.69.0-nightly (9880b408a 2023-02-28) |
| build_time         | 2023-03-20 03:10:33 +08:00                  |
| build_rust_channel | release                                     |
| features           | default, zip                                |
| installed_plugins  |                                             |

**Comment by lost22git** [comment]
after some modification, it works

every day amazed by nushell philosophy ；-）

![Screenshot 2023-04-06 094352](https://user-images.githubusercontent.com/65008815/230251616-28fdb575-7915-4331-904c-5e5c32316c5b.png)

**Comment by WindSoilder** [comment]
I think you need to use `$a = (test $a)`, because when assign/modify variable's value from command, you need to wrap with `()`

**Comment by lost22git** [comment]
it works now, thanks
