### ISSUE TITLE
else if expected block, closure or record, why?

### ISSUE THREAD

**Issue by lost22git** [nushell/nushell#8763]
### Describe the bug

# error
```
╰─❯ nu pikpak.nu caosini@uuf.me
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
     ╭─[E:\_case\pikpak.nu:412:1]
 412 │         save-config $config
 413 │       } else if $err == 'captcha_invalid' {
     ·              ─┬
     ·               ╰── expected block, closure or record
 414 │         let action = get-fileplayinfo-action
     ╰────
```

# code
```powershell
# PlayList
  mut play_list = []
  for file_id in $file_ids {
    while true {
      let play_info = get-fileplayinfo $file_id $headers $proxy
      let err = ($play_info | get 'error' -i)
      if $err == null {
        let link = ($play_info.medias.link.url | first 1)
        $play_list = ($play_list | append $link)
        break
      }
      print $'err => ($err)'
      if $err == 'unauthenticated' {
        let v = handle-autherr $user_config $headers $proxy
        $user_config = $v
        $headers.'Authorization' = $'Bearer ($user_config.access_token)'
        $config = ($config | upsert $user_config.username $user_config)
        save-config $config
      } else if $err == 'captcha_invalid' {   # ----------------------------------- compile error here :-(
        let action = get-fileplayinfo-action
        let new_captcha_token = handle-captchaerr $action $headers $proxy $user_config.user_id
        $headers.'x-captcha-token' = $new_captcha_token
      } else {
        error make {msg:$err}
      }
    }
  }
```

### How to reproduce

as above

### Expected behavior

compile pass

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.77.1                                      |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | windows-x86_64                              |
| build_target       | x86_64-pc-windows-msvc                      |
| rust_version       | rustc 1.69.0-nightly (f77bfb733 2023-03-01) |
| rust_channel       | nightly-x86_64-pc-windows-msvc              |
| cargo_version      | cargo 1.69.0-nightly (9880b408a 2023-02-28) |
| build_time         | 2023-03-20 03:10:33 +08:00                  |
| build_rust_channel | release                                     |
| features           | default, zip                                |
| installed_plugins  |                                             |

**Comment by WindSoilder** [comment]
Can you please try the latest version?  It should be fixed on the latest version
