### ISSUE TITLE
Command `find` has weird behavior

### ISSUE THREAD

**Issue by francoisthire** [nushell/nushell#8778]
### Describe the bug

Opening a file in raw mode and then using `find` produces weird behaviors.

### How to reproduce

1. Run `open foo.txt --raw | find 'AFTER WRITE'`
2. Notice something weird between line 4999 and 5000 (maybe it is expected, but why?)
3. Notice something weird at index 4856 (this is not the only one)
4. Open the file in an editor and see that there is nothing special for this line
[foo.txt](https://github.com/nushell/nushell/files/11174245/foo.txt)

### Expected behavior

Every line should be printed normally.

### Configuration

| key                | value                                      |
| ------------------ | ------------------------------------------ |
| version            | 0.77.1                                     |
| branch             |                                            |
| commit_hash        |                                            |
| build_os           | linux-x86_64                               |
| build_target       | x86_64-unknown-linux-gnu                   |
| rust_version       | rustc 1.69.0-beta.2 (2602aa81a 2023-03-17) |
| rust_channel       | beta-x86_64-unknown-linux-gnu              |
| cargo_version      | cargo 1.69.0-beta.2 (9880b408a 2023-02-28) |
| build_time         | 2023-03-26 19:39:11 +02:00                 |
| build_rust_channel | release                                    |
| features           | default, zip                               |
| installed_plugins  |                                            |

**Comment by fdncred** [comment]
Thanks for the comment. The `find` command was never really meant for a grep/rg replacement. It was meant to search nushell tables, so it doesn't surprise me that odd things happen with raw streams of data. Having said that, maybe someone will pick this up and fix it?

**Comment by francoisthire** [comment]
To be honest, I have tried many things but I was not able to grep easily the last column (the duration) as duration with `nushell`. I guess the command to use is `parse` but I was not able to find the correct syntax. I also tried to use `split row` or `split column` but I get also weird results.

**Comment by sholderbach** [comment]
With `0.96.1` all lines seem to be found by `find`. (the chunking by `table` after 1000 entries for performance is expected).

The artifact you observed may be down to a gnarly bug in the raw stream chunking.
