### ISSUE TITLE
Internal error while using variables in `use`

### ISSUE THREAD

**Issue by pepega007xd** [nushell/nushell#8781]
### Describe the bug

When I try to import a module using the `use` keyword using a variable instead of spelling the literal filename, i get an internal parser error:
```nu
❯ use $file
Error: nu::parser::unknown_state

  × Unknown state.
   ╭─[entry #28:1:1]
 1 │ use $file
   ·     ──┬──
   ·       ╰── internal error: Import pattern positional is not import pattern
   ╰────
```

### How to reproduce

```nu
touch new.nu
let file = "new.nu"
use $file
```

### Expected behavior

I would expect a more readable and understandable error, like "Variables not allowed in `use`". It would be best to actually allow the use of variables, but I understand that might be hard to do.

### Screenshots

![Screenshot_20230407-001749_Termux](https://user-images.githubusercontent.com/101605812/230503968-bd1580a3-3c27-434c-8aa2-628f7d668e42.png)

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.77.1                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.68.0 (2c8cc3432 2023-03-06) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.68.0 (115f34552 2023-02-26) |
| build_time         | 2023-03-28 19:05:31 +02:00          |
| build_rust_channel | release                             |
| features           | default, zip                        |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
It's by design. See this documentation for more information.
https://www.nushell.sh/book/thinking_in_nu.html
https://www.nushell.sh/book/how_nushell_code_gets_run.html

Agreed that the error could probably be better.

**Comment by sholderbach** [comment]
The error message is poetically unhelpful.

**Comment by kubouch** [comment]
Lol, yeah, that's some confusing error message.

You need to use `const` instead of `let` for it to work.

**Comment by weirdan** [comment]
The error message has been improved:

```console
$ touch new.nu
$ let file = "new.nu"
$ use $file
Error:   × Error: nu::shell::not_a_constant
  │
  │   × Not a constant.
  │    ╭─[entry #27:3:5]
  │  2 │ let file = "new.nu"
  │  3 │ use $file
  │    ·     ──┬──
  │    ·       ╰── Value is not a parse-time constant
  │    ╰────
  │   help: Only a subset of expressions are allowed constants during parsing. Try using the 'const' command or typing the value literally.
  │
   ╭─[entry #27:3:5]
 2 │ let file = "new.nu"
 3 │ use $file
   ·     ──┬──
   ·       ╰── Encountered error during parse-time evaluation
   ╰────
```
