### ISSUE TITLE
`((^echo "" | complete).stdout | str trim | length) == 1` is true...?

### ISSUE THREAD

**Issue by colemickens** [nushell/nushell#8782]
### Describe the bug

This doesn't seem right :smile: 

```
╭ zeph  ~/code/nixcfg 0.01s
╰─▶ ((^echo "" | complete).stdout | str trim | length) == 1
true
```

If `str trim`'s whitespace doesn't include new lines, I think it might be worth mentioning it explicitly.

But then again... 

```
╭ zeph  ~/code/nixcfg 0.01s
╰─▶ ((^echo -n "" | complete).stdout | str trim | length) == 1
true
```

Even in the case that echo doesn't output a newline, it's still wrong...

### How to reproduce

Trim an empty string, check it's length

### Expected behavior

the length would be zero

### Configuration

n/a this is tip of tree: e54b867 with default config

**Comment by fdncred** [comment]
I think you need to do this
```
((^echo "" | complete).stdout | str trim | str length) == 1
```
Although, I'm not sure why element length is 1

**Comment by colemickens** [comment]
Ooof. That makes some sense, but leaves a bigger question about whether `length` should have complained about being given a string, or if some (too much?) type coercion is happening. Thanks for the quick reply.

**Comment by fdncred** [comment]
In my mind, the question is, is `"" | length` really equivalent to 1 element? I can agree that `"one" | length` is 1 element, but `""` seems a bit weird I think, especially when `null | length` is 0. Why would empty string be 1? Sounds like a bug to me. What do other languages say?

**Comment by colemickens** [comment]
Ah, I was sort of not thinking about the pipeline nature of things. In this case, I actually think that ("" | length) should be 1...

I'll probably close this out unless you think it's worth more consideration.
