### ISSUE TITLE
Starship Prompt Error

### ISSUE THREAD

**Issue by dedguy21** [nushell/nushell#8804]
### Describe the bug

Error: nu::parser::closure_missing_pipe

  × Missing || inside closure
    ╭─[init.nu:8:1]
  8 │     
  9 │ ╭─▶ let-env PROMPT_COMMAND = {
 10 │ │       # jobs are not supported
 11 │ │       let width = (term size).columns
 12 │ │       ^/usr/bin/starship prompt $"--cmd-duration=($env.CMD_DURATION_MS)" $"--status=($env.LAST_EXIT_CODE)" $"--terminal-width=($width)"
 13 │ ├─▶ }
    · ╰──── Parsing as a closure, but || is missing
 14 │     
    ╰────
  help: Try add || to the beginning of closure

### How to reproduce

1. Arch linux, kernel 6.2
2. nushell 0.78.0
3. starship 1.13.1
4. Follow starship guide on how to enable nushell starship, save files in ~/.cache/starship/init.nu and write  source statement at the end of config.nu, close nushell
5. open nushell and get the above error and no starship prompt

### Expected behavior

I execpect the starship prompt to be enabled

### Screenshots

![2023-04-07T15:29:01,314587212-07:00](https://user-images.githubusercontent.com/49103740/230686687-3630afb5-7033-4abf-a76b-25703d51f2cb.png)

### Configuration

~> version | transpose key value | to md --pretty                04/07/2023 03:25:19 PM
| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.78.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 2ec20286371f1d90a77fdd5d82818c6c5851f090                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27) (Arch Linux rust 1:1.68.2-1) |
| cargo_version      | cargo 1.68.2                                                     |
| build_time         | 2023-04-05 02:09:35 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | default, zip                                                     |
| installed_plugins  |                                                                  |
~>                                                               04/07/2023 03:31:13 PM

**Comment by dedguy21** [comment]
Also leaving an issue with Starship.

**Comment by lost22git** [comment]
# Temporary solution
it works for me

## fix env.nu

```shell
## comment the startship generate init.nu code
# mkdir ~/.cache/starship
# starship init nu | save -f ~/.cache/starship/init.nu

```

## fix ~/.cache/starship/init.nu

```shell
let-env PROMPT_COMMAND = { || #------------------------- add || here
    # jobs are not supported
    let width = (term size).columns
   ...
}
...

let-env PROMPT_COMMAND_RIGHT = { || #------------------------- add || here
    let width = (term size).columns
   ...
}
```

**Comment by dedguy21** [comment]
thanks that did work

**Comment by presidento** [comment]
It's already fixed in Starship, just not released yet.
