### ISSUE TITLE
can't convert table<name: string, type: string, target: nothing, readonly: bool, size: filesize, created: date, accessed: date, modified: date> to string

### ISSUE THREAD

**Issue by lost22git** [nushell/nushell#8806]
### Describe the bug

Feedback to nushell for the last time, hope to get an answer, thanks

I'll go back and write powershell.

```shell
╰─❯ lld
Error: nu::shell::cant_convert

  × Can't convert to string.
   ╭─[alias.nu:5:1]
 5 │ alias ld = (ls | where type == 'dir')
 6 │ alias lld = (ls -l | where type == 'dir')
   ·             ──────────────┬──────────────
   ·                           ╰── can't convert table<name: string, type: string, target: nothing, readonly: bool, size: filesize, created: date, accessed: date, modified: date> to string
```

### How to reproduce

as above

### Expected behavior

works

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.78.0                                      |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | windows-x86_64                              |
| build_target       | x86_64-pc-windows-msvc                      |
| rust_version       | rustc 1.69.0-nightly (f77bfb733 2023-03-01) |
| rust_channel       | nightly-x86_64-pc-windows-msvc              |
| cargo_version      | cargo 1.69.0-nightly (9880b408a 2023-02-28) |
| build_time         | 2023-04-06 11:19:15 +08:00                  |
| build_rust_channel | release                                     |
| features           | default, zip                                |
| installed_plugins  |                                             |

**Comment by fdncred** [comment]
This is what the error looks like in the latest dev version of nushell.
```
alias lld = (ls -l | where type == 'dir')
Error: nu::parser::cant_alias_expression

  × Can't create alias to expression.
   ╭─[entry #1:1:1]
 1 │ alias lld = (ls -l | where type == 'dir')
   ·             ──────────────┬──────────────
   ·                           ╰── aliasing FullCellPath is not supported
   ╰────
  help: Only command calls can be aliased.
```

I believe this means that a custom command is needed for pipelines like this. e.g.
```
def lld [] {
  ls -l | where type == 'dir'
}
```

**Comment by lost22git** [comment]
thanks a lot
