### ISSUE TITLE
stdlib: write a CONTRIBUTING.md guidelines for developers

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8810]
### Related problem

as already partially tracked in #8450, we need a `CONTRIBUTING.md` file for developers :yum: 

cc/ @bobhy 
would you like to work on this?

### Describe the solution you'd like

there are some scattered parts in the `README` maybe?

a few things that we might want in the document (not exhaustive at all):
- add a command
- add tests
- use modules (this will come soon with upcoming refactoring)
- use the library to test locally
- run the tests (soon with `cargo run -- crates/nu-std/tests.nu` as mentionned in #8809)

**Comment by bobhy** [comment]
Yes, I'm on it.

**Comment by amtoine** [comment]
> Yes, I'm on it.
>
amazing thanks :relieved:
