### ISSUE TITLE
Closure error in config files when starting nushell

### ISSUE THREAD

**Issue by mystique09** [nushell/nushell#8827]
### Describe the bug

So uhh, I just updated my nushell to latest version and after I restart my termux there is an error in config about closure.

### How to reproduce

I use termux so I just did some update.
1. Update to latest version.
2. restart termux
3. open termux
4. weird error occurs here

### Expected behavior

There should be no error, I don't even know nu scripting lmao.

### Screenshots

![Screenshot_20230409-185139](https://user-images.githubusercontent.com/50514928/230768401-711ee4ca-5ca1-42db-a509-c15de1943619.jpg)

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.78.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | aarch64-linux-android               |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10) |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10) |
| build_time         | 2023-04-05 00:38:02 +00:00          |
| build_rust_channel | release                             |
| features           | default, zip                        |
| installed_plugins  |                                     |

### Additional context

I did `pkg upgrade` to update all upgradable in termux.

**Comment by fdncred** [comment]
Thanks for the report. This is a breaking change with our latest version as documented in the changelog. https://www.nushell.sh/blog/2023-04-04-nushell_0_78.html#now-required-in-closures

**Comment by mystique09** [comment]
> Thanks for the report. This is a breaking change with our latest version as documented in the changelog. https://www.nushell.sh/blog/2023-04-04-nushell_0_78.html#now-required-in-closures

Ohh, ok thanks.

**Comment by mystique09** [comment]
fixed
