### ISSUE TITLE
$nu does not scale well in some scenarios

### ISSUE THREAD

**Issue by ghost** [nushell/nushell#8862]
### Related problem

i wanted to find nushells parent process and had to wait 7mins for the following:
```nu
let a = (ps)
$a | where pid == ($a | where pid == $nu.pid | get ppid.0)
```

after testing i determined the subshell and $nu to be the problem:

. | use `$nu.pid` | cache `$nu.pid`
--- | --- | ---
use subshell |  `timeit {\|\| $a \| where pid == ($a \| where pid == $nu.pid \| get ppid.0) }` 7min 12sec 418ms 972µs 892ns | `timeit {\|\| let pid = $nu.pid; $a \| where pid == ($a \| where pid == $pid \| get ppid.0) }` 2sec 14ms 107µs 608ns
use variable | `timeit {\|\| let ppid = ($a \| where pid == $nu.pid \| get ppid.0); $a \| where pid == $ppid}` 1sec 952ms 331µs 872ns | `timeit {\|\| let pid = $nu.pid; let ppid = ($a \| where pid == $pid \| get ppid.0); $a \| where pid == $ppid}` 25ms 745µs 591ns

#### cache `$nu` results

This should be possible for most of the values, since `PID`, `config-path`, etc should never change.  
this however almost exclusively fixes this specific usecase, but considdering the extreme speed gain it might be worth it looking into.

#### cache subshell results

this might be more complicated, since subshells within for loops, etc should not be cached.  

a solution would be to scope the cache similar to the variables they contain  
or keep a size-limited result hash-map based on the values of the variables used in the subshell.  
but this would still create issues with mutable variables, which therefore should exclude it from caching i guess.

### Describe alternatives you've considered

as a user i might notice it being slow after 30sec, figure out the problem and run it with a manual cache, but i think this is a weird quirk, which might be improvable.

### Additional context and details

im was using d0a83fec693e50fbe38780aaec932f6b8cc8ed0a (`>0.78.0`) for the benchmarks

**Comment by fdncred** [comment]
7min seems crazy. Does this not do it? `ps | where pid == $nu.pid | get ppid`

**Comment by jntrnr** [comment]
if for whatever reason `$nu.pid` is slow (it should return almost immediately, but if it isn't...) you can put it into a variable and then refer to that variable.

```
let my_pid = $nu.pid
ps | where pid == $my_pid | get ppid
```

The example above around 150ms for me.

**Comment by rgwood** [comment]
@Jan9103 What OS are you using?

**Comment by rgwood** [comment]
Spent a bit of time profiling this with Superluminal. We definitely have a performance issue but the solution won't be as simple as caching some values.

I profiled Nu running `timeit {|| 1..1000 | each {|| $nu.config-path } }`. About 1/3 of the time is spent in the cell path helper, and 2/3 is in `eval_expression()`:
![image](https://user-images.githubusercontent.com/26268125/231618265-ca009376-9898-48c2-96b7-77579cb13b1f.png)

If we dig into the cell path helper, most of its time is spent in `core::ptr::drop_in_place()`. Probably related to a known issue where we use a few unnecessary clones when following cell paths, we should fix that up eventually:
https://github.com/nushell/nushell/blob/36036d9308896ac678911065093ddda04419c7ce/crates/nu-protocol/src/value/mod.rs#L740-L741

If we dig into `eval_expression()`, almost all the time is spent cloning the engine state for `$nu` here:

https://github.com/nushell/nushell/blob/36036d9308896ac678911065093ddda04419c7ce/crates/nu-engine/src/eval.rs#L1193-L1198

Not sure what the best way to fix this is. When I was working on the `LazyRecord` implementation for `$nu`, we decided that the `LazyRecord` needs a copy of the engine state so it has a snapshot of all the info necessary for `$nu.scope`.

However... if that's a performance bottleneck, maybe we should move scope info elsewhere (like into a dedicated command)? I don't think it *needs* to be in `$nu`.

**Comment by rgwood** [comment]
btw, to give a rough order of magnitude accessing `$nu.pid` takes something like 1.5ms on my desktop. Slow when done many times but often negligible.

**Comment by fdncred** [comment]
From my testing, it's fast now. @Jan9103 ready to close this?

**Comment by fdncred** [comment]
Thanks @Jan9103. I still have no idea why this takes 13 seconds on my mbp.
![image](https://github.com/nushell/nushell/assets/343840/c5862282-88af-4fed-a253-dc69e655273f)
