### ISSUE TITLE
completion on `$nu` uses `$nu | columns` at all depth

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8863]
### Describe the bug

could not find a similar in the issue tracker so here i go :smirk: 

when we try to auto-complete on the `$nu` variable, no matter the depth in the data, we get results from `$nu | columns` :open_mouth: 

### How to reproduce

see [this recording](https://asciinema.org/a/577132), which has the commands and the wrong completion menus :yum: 

### Expected behavior

the completion
- on `$nu` should use `config-path env-path history-path loginshell-path plugin-path scope home-path temp-path pid os-info startup-time is-interactive is-login current-exe`, i.e. `$nu | columns`
- on `$nu.scope` should use `vars commands aliases modules engine_state`, i.e. `$nu.scope | columns`
- etc, etc, ...

### Configuration

`version` is broken, i'm on latest `main` (8ee52b6ee1cebfbb265d68efcffed97254a7c252) :wink: 

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.78.1                                   |
| branch             | main                                     |
| commit_hash        | f2b977b9c59931ad2b5e55174e63ebbec50b8cbe |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-04-08 12:34:28 +02:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  | len                                      |

**Comment by ito-hiroki** [comment]
I would like to work on this issue if no one is working.

**Comment by sholderbach** [comment]
> I would like to address this issue if no one is in charge.

Thanks for giving it a shot! Have fun :)
