### ISSUE TITLE
moving multiple files into a folder gives the wrong error message and unexpected behavior

### ISSUE THREAD

**Issue by AucaCoyan** [nushell/nushell#8865]
### Describe the bug

I have to move 3 files from one folder, to another folder that doesn't exist yet
so, if I type
```
mv Downloads\files-starting-with-this* ~\Folder-that-doesnt-exist-yet\
```
gives me the error
```
  × Can only move multiple sources if destination is a directory
   ╭─[entry #8:1:1]
 1 │ mv Downloads\files-starting-with-this* ~\Folder-that-doesnt-exist-yet\
   ·                                         ─────────────────┬───────────
   ·                                                          ╰── destination must be a directory when moving multiple sources
   ╰────
```

BUT
if I move 1 file, like this:

```
mv Downloads\files-starting-with-this-file-number-1 ~\Folder-that-doesnt-exist-yet
bat ~\Folder-that-doesnt-exist-yet
```
It moves the file and rename it to the non-existent folder

> files-starting-with-this-file-number-1 contents
> 1
> 2
> 3

so, if I select 1 file, `mv` works but gives unexpected results (move the file with the name as non existing folder)
and if I select more than one file it doesn't work, it throws an unexpected exception:
`Can only move multiple sources if destination is a directory`
It is a directory, it just doesn't exist yet

### How to reproduce

1. create 2 files
2. move them to an non-existent folder
3. the error message appears on screen

### Expected behavior

I would expect to correctly inform the error (for example, `this folder doesnt exist, would you like to create it?`

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.78.0                                   |
| branch             |                                          |
| commit_hash        | 2ec20286371f1d90a77fdd5d82818c6c5851f090 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-04-04 19:13:32 +00:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

### Additional context

submitted on discord, on channel [#feedback](https://discord.gg/xwK64Tbpm9)

**Comment by AucaCoyan** [comment]
> Looks to be similar to the issue I've reported, #8461

Yes, I would comment that it is needed to write better the exception, and the rest is covered in that issue.

`Can only move multiple sources if destination is a directory`

Is is ok to close this issue and mark that continues in #8461 ? @onthebridgetonowhere

**Comment by onthebridgetonowhere** [comment]
> > Looks to be similar to the issue I've reported, #8461
> 
> Yes, I would comment that it is needed to write better the exception, and the rest is covered in that issue.
> 
> `Can only move multiple sources if destination is a directory`
> 
> Is is ok to close this issue and mark that continues in #8461 ? @onthebridgetonowhere

Sure thing! Thanks!
