### ISSUE TITLE
NU_LIB_DIRS environment variable no longer working

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#8870]
### Describe the bug

Setting `let-env NU_LIB_DIRS` inside `env.nu` has no effect. Only `const NU_LIB_DIRS` works.

### How to reproduce

1. Inside `env.nu`: Set `let-env NU_LIB_DIRS = [  ($nu.config-path | path dirname | path join 'scripts') ]`
2. `const NU_LIB_DIRS` is not set anywhere
3. Put a file (`script.nu`) to the scripts folder
4. `source script.nu` inside `config.nu`
5. Error: File not found

### Expected behavior

Should work the same as before.

### Configuration

| key                | value                                                                                       |
| ------------------ | ------------------------------------------------------------------------------------------- |
| version            | 0.78.1                                                                                      |
| branch             | main                                                                                        |
| commit_hash        | 99c0a2575f22c754cc4e2ee14aa7e539dcc364b9                                                    |
| build_os           | linux-x86_64                                                                                |
| build_target       | x86_64-unknown-linux-gnu                                                                    |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)                                                         |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu                                                             |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)                                                         |
| build_time         | 2023-04-13 00:14:22 +03:00                                                                  |
| build_rust_channel | release                                                                                     |
| features           | default, zip                                                                                |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, inc, query, query json, query web, query xml |

### Additional context

**Comment by kubouch** [comment]
Update: It's not related to the NU_LIB_DIRS PRs but at some point the way `$nu.config-path` is set changed. Now, it doesn't point at the default location anymore, but instead is set based on the `--config` flag and also resolves a symlink which is what caused my problem. Therefore, setting 
```
let-env NU_LIB_DIRS = [
    ($nu.config-path | path dirname | path join 'scripts')
]
```
([as set in default env.nu](https://github.com/nushell/nushell/blob/b9808c859836cdafb8d14d71079e0bcd90e7ac18/crates/nu-utils/src/sample_config/default_env.nu#L74-L76)) is not reliable anymore. We should probably have `$nu.default-config-dir` or something like that for this to keep working.

**Comment by fdncred** [comment]
Maybe it was this PR https://github.com/nushell/nushell/pull/8792

**Comment by kubouch** [comment]
Yeah, I think that PR is a good change, now we just need some way to refer to the default config location.

**Comment by ito-hiroki** [comment]
If no one is addressing this issue, I would like to.
But I am just a little confused and want to make sure my understanding.
I think the problem is that a user using a custom config directory (not default config dir `/home/<username>/.config/nushell/`) can't load scripts, which are placed in the default config dir, by using NU_LIB_DIRS now.
Is it correct?

**Comment by kubouch** [comment]
Yeah, if you look at the default env.nu lines I linked above, you see the NU_LIB_DIRS is derived from `$nu.config-path` which can change depending on multiple factors. So, we need some way to refer to the default config directory so that the NU_LIB_DIRS would always be pointing at `/home/<username>/.config/nushell/scripts`.

The implementation should be quite easy: The `$nu` contents are defined during evaluation [here](https://github.com/nushell/nushell/blob/b2d7427d2def7aed26ba8b179f0d67b52406995f/crates/nu-engine/src/eval.rs#L1193) and the implementation of the NuVariable is [here](https://github.com/nushell/nushell/blob/main/crates/nu-engine/src/nu_variable.rs).
