### ISSUE TITLE
use .netrc and .netrc.gpg for http auth

### ISSUE THREAD

**Issue by thasos** [nushell/nushell#8874]
### Related problem

`http get <url>` is a great feature ! is it possible to use a `.netrc` file instead of `--user` and `--password` ?

a `.netrc.gpg` support would be really great too, like with git for example (see https://grahamlopez.org/git/git_credentials.html)

### Describe the solution you'd like

my creds are stored in a `.netrc.gpg` file, I would be able to do a authenticated `http get <url>` without `--user` and `--password`

**Comment by rgwood** [comment]
Thanks for the issue!

I think we're _probably_ not going to implement this. One of our design goals with the `http` commands is to keep them relatively simple and keep the number of flags down; unfortunately that means we'll have to skip some useful features.

I'll let other devs who have worked on `http` weigh in though, it's possible I've misunderstood how popular such a feature would be.

**Comment by sholderbach** [comment]
*screams into a pillow* https://daniel.haxx.se/blog/2022/05/31/netrc-pains/

**Comment by rgwood** [comment]
Oof. OK, that looks unpleasant enough that I think we will probably not implement netrc support. Gonna close this for now but feel free to keep discussing.
