### ISSUE TITLE
Nu doesn't recognise string characters as string

### ISSUE THREAD

**Issue by YuriGeinishO** [nushell/nushell#8879]
### Describe the bug

```
$ cat a
def main [version: string] {
  print $version
}
$ nu a 1
Error: nu::parser::type_mismatch

  × Type mismatch during operation.
   ╭─[<commandline>:1:1]
 1 │ main 1
   ·      ┬
   ·      ╰── expected string, found number-like value (hint: use quotes or backticks)
   ╰────

$
```

### How to reproduce

See above

### Expected behavior

`1` is a valid string character. It's also a valid integer character, but that doesn't exclude it from being a valid string character. And even if quoting strings is a requirement for Nu scripts, having this requirement in command line parameters isn't very sensible, because you can't assume Nu scripts are only called from Nu. In fact, I bet most of the time they're called from Bash :), and this turns into `nu a "'1'"` which isn't optimal.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.78.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.68.0 (2c8cc3432 2023-03-06) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.68.0 (115f34552 2023-02-26) |
| build_time         | 2023-04-13 17:17:32 +02:00          |
| build_rust_channel | release                             |
| features           | default, zip                        |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
this was a known breaking change. You can read about it here https://www.nushell.sh/blog/2023-04-04-nushell_0_78.html#breaking-changes. Also, please try the latest main. we've made changes to this recently.

**Comment by YuriGeinishO** [comment]
Thanks, confirming this is fixed in `main`.
