### ISSUE TITLE
Nu's type inference expects CLI string to be number-like

### ISSUE THREAD

**Issue by YuriGeinishO** [nushell/nushell#8880]
### Describe the bug

Related to #8879, I think.

```
$ cat a
def main [version] {
  print $version
}
$ nu a 1
1
$ nu a 1.2
1.2
$ nu a 1.2.3
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[<commandline>:1:1]
 1 │ main 1.2.3
   ·      ──┬──
   ·        ╰── expected number-like value (int, float, date, etc)
   ╰────

$
```

### How to reproduce

See above

### Expected behavior

To treat `1.2.3` as a string (because it can't be anything else, and there's no strict type requirement on the cli arg).

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.78.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.68.0 (2c8cc3432 2023-03-06) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.68.0 (115f34552 2023-02-26) |
| build_time         | 2023-04-13 17:17:32 +02:00          |
| build_rust_channel | release                             |
| features           | default, zip                        |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
this was a known breaking change. You can read about it here https://www.nushell.sh/blog/2023-04-04-nushell_0_78.html#breaking-changes. Also, please try the latest main. we've made changes to this recently.

**Comment by YuriGeinishO** [comment]
Thanks, confirming this is fixed in `main`.
