### ISSUE TITLE
Make history auto-complete aware of the current directory

### ISSUE THREAD

**Issue by chtenb** [nushell/nushell#8883]
### Related problem

Hey everyone! I've noticed that when using the shell, running certain commands is closely tied to the current working directory. But, the history completions (I access them with Alt-Right) are global, so sometimes they don't make sense for the current directory.

### Describe the solution you'd like

I'm suggesting we track the working directory for each history entry, which will help us know where commands were executed. This way, we can enhance the history completion by prioritizing items from the same directory first and displaying others only if there's no match. This would make our workflow smoother!

**Comment by fdncred** [comment]
If you use the sqlite history db, the current directory is already tracked. This can be used to do what you're suggesting.

**Comment by p00f** [comment]
@fdncred I want to implement this, can you tell me what to look at? `fd complet` in the repo root shows files related to tab-completion

**Comment by last-partizan** [comment]
Is this released and working? Does not seem to be cwd-aware at the moment. (version 0.100.0)

![image](https://github.com/user-attachments/assets/28a0810e-9ada-47d5-bb00-53ac6051fa75)

**Comment by fdncred** [comment]
it is and it works but i believe it requires the sqlite history, iirc.

**Comment by last-partizan** [comment]
Hmm. Maybe it's working, but not as I expected.

I'm used to `zsh` per-directory-history, and it's completely isolated.

Here it looks like in only prefers history from current dir, while still having access to all history?

**Comment by fdncred** [comment]
ya, it will work per-directory until you have nothing that matches in that directory, then it pulls from the rest of the history.
