### ISSUE TITLE
`view source` not working properly

### ISSUE THREAD

**Issue by theAkito** [nushell/nushell#8896]
## Actual Source
```nu
def file [ ...files: string ] {
  ^file -iLF (char space) $files
  | detect columns -n
  | rename name mime charset
  | update cells -c [ mime ] { |value| $value | str trim -r -c ';' }
  | update cells -c [ charset ] { |value| $value | str substring 8.. }
}
```

## Output of `view source file`
```nu
def file [ --help (-h) ] {
    ^file -iLF (char space) $files
    | detect columns -n
    | rename name mime charset
    | update cells -c [ mime ] { |value| $value | str trim -r -c ';' }
    | update cells -c [ charset ] { |value| $value | str substring 8.. }
  }
```

### How to reproduce

Save file with actual source, source the file, then run `view source file`.

### Expected behavior

`view source` should show actual source, as is.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.78.0                                   |
| branch             |                                          |
| commit_hash        | 2ec20286371f1d90a77fdd5d82818c6c5851f090 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-04-04 19:10:23 +00:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
I think this is as expected. The only part, I think, that's stored is
```
  {
    ^file -iLF (char space) $files
    | detect columns -n
    | rename name mime charset
    | update cells -c [ mime ] { |value| $value | str trim -r -c ';' }
    | update cells -c [ charset ] { |value| $value | str substring 8.. }
  }
```
The rest is just constructed. You'll also notice this with custom commands that are `def-env` because they'll just say `def`.

**Comment by theAkito** [comment]
> I think this is as expected.

I expect, that a command which name is `view source` is more accurate than that. I expect, that the output can just be pasted into a new file & work right away. The command is especially pointless with lots of arguments, because then you cannot even comprehend the source, as you don't know which arguments are what.

Therefore, I am convinced, this needs to be fixed/changed either way. Whether this means, `view source` is extended by the expectation I mentioned or there will be different commands with different source viewing abilities is a different story.
As it is now, I do not see the point of the command. I want to see the whole signature, block, etc. If I need to look that up in the actual source file anyway, why use `view source` to begin with, with `def`s that have at least one argument?

**Comment by fdncred** [comment]
The great thing about open source is that people can submit PRs to address their expectations.
