### ISSUE TITLE
Option to not follow HTTP redirects

### ISSUE THREAD

**Issue by profinoob** [nushell/nushell#8920]
### Related problem

I would like to debug a HTTP redirect response like `303 See Other` using nushell but the `http get` command follows the redirect and only displays the response it is redirected to.

### Describe the solution you'd like

A flag for the `http` commands to not follow redirects would be great.

### Describe alternatives you've considered

Fetch API of Javascript has the `redirect` option with values `manual`, `follow`, and `error`:
https://developer.mozilla.org/en-US/docs/Web/API/Request/redirect

curl has a `-L` or `--location` flag for following redirects. This means that by default redirects are not followed:
https://curl.se/docs/manpage.html#-L

**Comment by cyradotpink** [comment]
This would be very useful to me, too. I would be happy to contribute a PR here; what do others think the right approach is? I think I would like to keep the default as it is right now, with redirect following being enabled, and then borrow the "redirect" option from the Fetch API as suggested (with "follow" being the default value, "error" causing a network failure on redirects, and "manual" simply returning the 3xx response to the initial request). If we don't want the "error" option (although I personally think it might be useful) we could just have a flag like "--no-follow" instead, which would enable the returning of 3xx responses

**Comment by cyradotpink** [comment]
> could you give a concrete example that i could try with `http get` and see that it does not work as expected? 😇

Sure :) consider for example `http get https://nushell.sh`. For this URL, nushell.sh responds with a 301 permanent redirect. When `http get` encounters this 301 response, it immediately and invisibly makes a second request, this time to the URL given in the 301 response's `Location` header (`https://www.nushell.sh`). This request results in a 200 OK response, which is what `http get` then returns to the user.

This behaviour is identical to what the Javascript's `fetch` API does by default (`fetch('https://nushell.sh')` follows the 301 and returns the 200 from `https://www.nushell.sh`). But there are situations where this isn't the desired behaviour; One might intend to inspect the headers present in the 301 response, frequently for example the `Location` header. To allow for this, with JS `fetch`, one might do `fetch('https://nushell.sh', { redirect: 'manual' })`. This call (at least in Deno, web browsers seem to be a bit different) will simply return the initial 301 response. An equivalent option does not currently exist in nu's `http` commands.

**Comment by sholderbach** [comment]
Should be a relatively straightforward addition as [`ureq` supports varying the number of followed redirects](https://docs.rs/ureq/latest/ureq/struct.AgentBuilder.html#method.redirects).

Although chasing after the flexibility of `curl` is a non-goal, I think we can consider an added flag here, to allow "safer" explict behavior as well.

**Comment by amtoine** [comment]
thanks for the clear example @cyradotpink, very helpful :pray: 

is it possible to see the 301 instead of 200 with `http get https://nushell.sh`?
i tried with the `-f` and `-e` options but still don't see the redirection, just directly the correct response :open_mouth:

**Comment by sholderbach** [comment]
> is it possible to see the 301 instead of 200 with `http get https://nushell.sh`?

That is the goal of this issue and what #11329 tries to expose with a new flag
