### ISSUE TITLE
Reduce does not work (correctly? sometimes?)

### ISSUE THREAD

**Issue by Fishrock123** [nushell/nushell#8923]
### Describe the bug

`reduce` seems to not work with some kinds of inputs, even when it should, even when it did in the past (circa 0.74).

RThis issue is present at least on 0.78 and also `main` at  `29256b161` (0.78.1 as of today).

### How to reproduce

The following produces an empty record (or `nothing`)
```nu
"export A='x';\nexport B='z';\n" | lines | parse "export {name}='{value}';" | reduce -f {} { |it, acc| upsert $it.name $it.value }
```

Yet that `parse` produces valid input:
```nu
"export A='x';\nexport B='z';\n" | lines | parse "export {name}='{value}';"
╭───┬──────┬───────╮
│ # │ name │ value │
├───┼──────┼───────┤
│ 0 │ A    │ x     │
│ 1 │ B    │ z     │
╰───┴──────┴───────╯
```

And this example answer from a related issue works just fine: https://github.com/nushell/nushell/issues/8744#issuecomment-1496717185

### Expected behavior

It should produce a record like:
```nu
╭───┬──────╮
│ A │ x    │
│ B │ z    │
╰───┴──────╯
```

### Configuration

```
❯ version | transpose key value | to md --pretty
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.78.1                                   |
| branch             | main                                     |
| commit_hash        | 29256b161ca118b4b26b4763fad796e2334bb3f9 |
| build_os           | macos-aarch64                            |
| build_target       | aarch64-apple-darwin                     |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-aarch64-apple-darwin              |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-04-18 13:52:34 -07:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |
```

### Additional context

As additional context in case there is a better way: I am trying to transcribe the bash env var output of a third party tool into nushell env vars. Again this worked circa 0.74.

```nu
alias tool_to_nu = (third_party_tool | lines | parse "export {name}='{value}';" | reduce -f {} { |it, acc| upsert $it.name $it.value } | load-env)
```

**Comment by Fishrock123** [comment]
@fdncred Those do work, thank you.

It is very strange though that the one example works but mine does not even though they look identical (and that it makes sense)...

**Comment by Fishrock123** [comment]
Actually both of those work on the example but not on the real data. Very strange.

My real data includes dates as strings e.g. `export key='2023-04-18T21:39:50Z';` and pseudo-random keys that include characters such as `:` `/` and `=`.

`parse` works fine, but reducing or transposing it causes an empty record or empty list, respectively...

**Comment by Fishrock123** [comment]
The solution was to add `-s` to `lines`. The third party tool outputs an empty first line.

This output that i had missed led me to be suspicious of `lines`:
```
╭────────────╮
│ empty list │
╰────────────╯╭───┬───────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ # │         name          │                                                value                                                │
├───┼───────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────┤
```

Which is, I think saying that two separate lists were output, the first of which had no entries.

`describe` does not acknowledge or detect that, which I think is an issue.

**Comment by fdncred** [comment]
If you want to see more details you should do some thing like `tool | lines | debug --raw`. I'm closing this for now since we seemed to have solved the problem.
