### ISSUE TITLE
`help` command should include default parameter values

### ISSUE THREAD

**Issue by MariaSolOs** [nushell/nushell#8928]
### Related problem

Say I have the following:
```nu
# A fancy function that does something.
export def foo [
    bar: string = "bar" # Some parameter description.
] {
    print $bar
}
```

If I run `help foo`, the following is displayed:
```
➜ help foo
A fancy function that does something.

Usage:
  > foo (bar) 

Flags:
  -h, --help - Display the help message for this command

Parameters:
  (optional) bar <string>: Some parameter description.
```

### Describe the solution you'd like

It would be very useful for default parameter values to also be mentioned when using `help`, since then I know when I can safely omit the parameter :)

**Comment by MariaSolOs** [comment]
If this sounds like a reasonable request, I would be happy to work on it :)

**Comment by fdncred** [comment]
Seems reasonable to me but I'd like to know where you plan on putting the default value first.

**Comment by amtoine** [comment]
> It would also be nice if default values showed up here, in the signatures
>
especially if we continue moving the `help` commands to the standard library, because they use `$nu.scope.commands` only to build the help pages, so we'd need this information there :+1:

**Comment by fdncred** [comment]
> by putting do you mean how the default value will be displayed?

I mean, I think you should be able to see the default value when you do `command_name --help` but it should also be viewable in the $nu.scope.commands signatures.

**Comment by MariaSolOs** [comment]
> I mean, I think you should be able to see the default value when you do `command_name --help` but it should also be viewable in the $nu.scope.commands signatures.

@fdncred I understand, but when you said "I'd like to know where you plan on putting the default value first.", where you referring to where I plan to put the value when running `command_name --help` or when using `$nu.scope.commands`?

Also, any thoughts about my previous question? :)
> I have a question though: default_value is [an Expression](https://github.com/nushell/nushell/blob/91c01bf6b3bc58fc1510ba0caa3da414b76fac36/crates/nu-protocol/src/signature.rs#L38), and from what I see neither Expression nor Expr implement fmt::Display or have some direct .to_string() functionality. Could I get some hints on how to obtain the "raw" value to be displayed?

**Comment by fdncred** [comment]
> where you referring to where I ...

both

> I have a question though: default_value is an Expression, a ...

I'm not sure. It's best to ask this on discord in #design-discussion.

**Comment by MariaSolOs** [comment]
> I'm not sure. It's best to ask this on discord in #design-discussion.

Will do, thanks!

**Comment by MariaSolOs** [comment]
@bobhy Given the overlap of this with #8983, are you okay if I assign this to you?

**Comment by bobhy** [comment]
Yep!

**Comment by MariaSolOs** [comment]
Oh it seems like I don't have permissions to assign people 😅 @fdncred or @amtoine, could you please help me with that? 😸

**Comment by bobhy** [comment]
@MariaSolOs Did you end up storing the (now constant, now Option<Value>) default value somewhere in `$nu.scope`?   I was kind of expecting to see it in a new
```
〉$nu.scope.commands | where name == "first" | get signatures.0 | values | first 
╭───┬────────────────┬────────────────┬──────────────┬─────────────┬────────────┬───────────────────────────────────────────────────────┬───────────────────╮
│ # │ parameter_name │ parameter_type │ syntax_shape │ is_optional │ short_flag │                      description                      │ custom_completion │
├───┼────────────────┼────────────────┼──────────────┼─────────────┼────────────┼───────────────────────────────────────────────────────┼───────────────────┤
│ 0 │                │ input          │ binary       │ false       │            │                                                       │                   │
│ 1 │ rows           │ positional     │ int          │ true        │            │ starting from the front, the number of rows to return │                   │
│ 2 │                │ output         │ binary       │ false       │            │                                                       │                   │
╰───┴────────────────┴────────────────┴──────────────┴─────────────┴────────────┴───────────────────────────────────────────────────────┴───────────────────╯
```
If not, I'll take a longer look at your recent change and see if I can extend `.signatures` to accommodate it.

**Comment by MariaSolOs** [comment]
@bobhy I didn't modify `$nu.scope` in #8940 😞

**Comment by fdncred** [comment]
Let's not reuse is_optional if possible @bobhy. Thanks!

**Comment by amtoine** [comment]
hey @MariaSolOs, has this been addressed? :yum: 

with your `foo` command above, i see the default value in both `help foo` and `std help foo` now :+1:

**Comment by amtoine** [comment]
> @amtoine
>
:wave: 

> The fixes haven't been released yet right?
>
no they're not, they'll be tomorrow :smirk: 

> But if the changes are in `main`, I'm fine with closing this issue!
>
cool :sparkles: 
issues do not need to wait for the release, we're in the realm of `main` in here :innocent: 

> I would also like to see what the current help looks like. Could you please remind me how to test `main`? see_no_evil
>
no worries, of course :yum: 
the easiest, assuming least amount of knowledge about your local copy of your `nushell` repo...
```bash
# go to the repo
cd /path/to/nushell

# get the latest revision of nushell
git remote add nushell https://github.com/nushell/nushell
git fetch nushell
git checkout nushell/main

# try it out
cargo run -- --no-config-file

## inside `cargo run` define your command
# A fancy function that does something.
export def foo [
    bar: string = "bar" # Some parameter description.
] {
    print $bar
}

help foo
std help foo
```

feel free to reopen this issue if it's not been addressed in the end :blush:

**Comment by MariaSolOs** [comment]
@amtoine Thanks for the instructions! `help foo` looks great to me, but `std help foo` looks like this, which I believe isn't the intended behaviour...?
<img width="624" alt="image" src="https://github.com/nushell/nushell/assets/62502207/7c63476a-fff2-437b-9474-4edefa70eeb6">

**Comment by amtoine** [comment]
noishe :muscle: :yum:
