### ISSUE TITLE
Serialize the entire current state of nushell

### ISSUE THREAD

**Issue by yshui** [nushell/nushell#8933]
### Related problem

It could be useful to replicate the exact environment of a nushell somewhere else. e.g. copy all my local defined variables, function to a remote nushell over ssh.

### Describe the solution you'd like

Have a command that dumps all nushell state, in a form that can be loaded into another nushell. This could just be a nushell script that I can `source` from another shell.

### Describe alternatives you've considered

N/A

**Comment by rgwood** [comment]
Thanks for the issue!

I don't think we're going to implement this as built-in functionality. Not all of Nushell’s state can be serialized (closures for example) and this functionality would be very fragile at best.  You may be able to hack something together with a custom command though.
