### ISSUE TITLE
An npm package for installing/running nushell

### ISSUE THREAD

**Issue by evelant** [nushell/nushell#8936]
### Related problem

I'd like to run nu scripts in environments that only have access to `npm` for installing dependencies. Specifically https://expo.dev which I use to build my react-native app.

### Describe the solution you'd like

An npm package to install nushell. Since npm is ubiquitous being able to `npm install -g nu && nu some_script.nu` or `pnpm pnpx nu my_script.nu` would be quite useful.

### Describe alternatives you've considered

It depends on the case, but for any JS/TS CI environment it would be handy.

**Comment by hustcer** [comment]
It's a very interesting issue, I found that I have the same need, I am going to do some research and try to fix it

**Comment by hustcer** [comment]
Closed by https://github.com/hustcer/nu-to-npm
To install nu by npm, simply run: `npm i -g nushell`, then you can run `nu` to start a new session.

**Comment by evelant** [comment]
Looks amazing, thank you for creating this!
