### ISSUE TITLE
Default parameters should be `Values`, not `Expressions`

### ISSUE THREAD

**Issue by MariaSolOs** [nushell/nushell#8939]
### Describe the bug

The type of `default_value` in `PositionalArg` is an [optional expression](https://github.com/nushell/nushell/blob/91c01bf6b3bc58fc1510ba0caa3da414b76fac36/crates/nu-protocol/src/signature.rs#L38), but this is overly flexible. It would make more sense for it to be a constant value.

### How to reproduce

N/A

### Expected behavior

N/A

### Configuration

N/A

### Additional context

This was discovered by my primary investigation for #8928, and should be tackled first.

**Comment by MariaSolOs** [comment]
I don't mind working on this BTW 😺

**Comment by fdncred** [comment]
I assigned it to you @MariaSolOs. Have at it. Thanks for helping out!
