### ISSUE TITLE
How to load a .nu custom text script after startup, and then don’t have to source xxx.nu every time you use it

### ISSUE THREAD

**Issue by 107295472** [nushell/nushell#8942]
### Question

Want to call the function in xxx.nu directly

**Comment by 107295472** [comment]
` let $s = (ls | select name)
  for xx in $s { 
   let n = $"($xx.name)"
	 mklink  D:\go\pkg\mod\github.com\paddlepaddle\paddle\paddle\fluid\inference\goapi@v0.0.0-20230420053226-2395cbe50667\$"($n)" E:\ai\paddle_inference_c\paddle\include\$"($n)"
  }`
how to join here

**Comment by fdncred** [comment]
Typically you're create a custom command for things like this and then put that custom command in your config.nu so you can use it every time nushell starts up.

Example
```
def my_command_name [my_args] {
# my_command_body here
}
```

for your stuff above it seems like this may work
```
def mklinks [] {
  let $s = (ls | select name)
  for xx in $s {  
    mklink $"D:\that\long\path\($xx)" $"E:\that\path\($xx)"
  }
}
```

**Comment by 107295472** [comment]
Thanks
