### ISSUE TITLE
commandline --insert not inserting at cursor position any more

### ISSUE THREAD

**Issue by bartlibert** [nushell/nushell#8943]
### Describe the bug

I'm using `commandline --insert` in some of my keybindings and this worked, but since the upgrade to version 0.78.0, this does not work anymore and the insertion is always done at the front of the commandline. 

In 0.77.1 this worked fine.

### How to reproduce

1. Create a default nushell configuration
2. Add the following keybing:

```
{
                name: bar_test
                modifier: control
                keycode: char_t
                mode: [emacs, vi_insert, vi_normal]
                event: {
                  send: executehostcommand             
                  cmd: `commandline --insert bar`
                }
    }
```
3. (Re)start nushell to load the new config
4. Type `foo`
5. Press `CTRL-T`
6. Result: `barfoo`

### Expected behavior

I expected 'commandline --insert' to insert the string at the cursor position, not the start of the line.
So in the example above, I expected to see `foobar` instead of `barfoo`

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.78.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 2ec20286371f1d90a77fdd5d82818c6c5851f090                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27) (Arch Linux rust 1:1.68.2-1) |
| cargo_version      | cargo 1.68.2                                                     |
| build_time         | 2023-04-05 02:09:35 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | default, zip                                                     |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment]
`commandline` changed recently https://github.com/nushell/nushell/pull/8207 maybe @stevenxxiu broke something on accident?

**Comment by amtoine** [comment]
i could reproduce this on latest `main` :+1: :open_mouth:
