### ISSUE TITLE
nushell panics when running a specific custom command from `cargo run`

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#8945]
### Describe the bug

i made `nushell` panic in a very strange way :laughing: 
```nushell
thread 'main' panicked at 'Can't create a Span whose end < start, start=76121, end=76116', crates/nu-protocol/src/span.rs:32:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### How to reproduce

1. checkout on 393f424f1cccb5b228ec438df7307d6d2010af9a
2. `cargo run -- --no-config-file`
3. define the following commands
```
def "from ns" [] {
    [$in "ns"] | str join | into duration
}
```
and
```
def benchmark [
    code: closure
    -n: int = 50
    --verbose (-v): bool
] {
    let times = (
        seq 1 $n
        | each {|i|
            if $verbose { print -n $"($i) / ($n)\r" }
            timeit { do $code } | into int | into decimal
        }
    )

    if $verbose { print $"($n) / ($n)" }

    {
        mean: ($times | math avg | from ns)
        std: ($times | math stddev | from ns)
        data: ($times | each { from ns })
    }
}
```
4. :heavy_check_mark: run `benchmark { 1 + 2 } -n 2`
5. :x: run `benchmark { 1 + 2 } -n 10`

> **Note**
> i fails with `-n >3`

### Expected behavior

i think it should not panic, especially as i cannot reproduce this after a `cargo install --path . --features dataframe`

### Configuration

`cargo run` from 393f424f1cccb5b228ec438df7307d6d2010af9a

**Comment by fdncred** [comment]
I've seen this once today. I'm not sure how to repro it.
![image](https://user-images.githubusercontent.com/343840/233437030-00035739-9e76-47bd-b10c-c04f53cb05c6.png)

**Comment by amtoine** [comment]
:open_mouth: 

i mean, the span check is working fine :laughing: 
but the question is, why here :thinking:

**Comment by fdncred** [comment]
I have no idea. I compiled in release and it ran fine with 20 iterations (on the latest main with my find changes)

**Comment by amtoine** [comment]
at least it works once installed :relieved:

**Comment by amtoine** [comment]
and i'm not able to reproduce this with `cargo run --release` either :thinking: 
could that be a debug issue, 'cause `cargo run --release` and `cargo install` have that in common :open_mouth:

**Comment by tesla232** [comment]
I have looked into this issue and the reason this only happened is because this is using a debug_assert. 
https://github.com/nushell/nushell/blob/2a484a3e7e169e699766e1883ccb1286b2383212/crates/nu-protocol/src/span.rs#L31-L38
The issue seems to be that span.end shouldn't be used when determining the span of the duration, 
https://github.com/nushell/nushell/blob/2a484a3e7e169e699766e1883ccb1286b2383212/crates/nu-parser/src/parser.rs#L2306-L2307
Instead of this, we should use the length of num_with_unit + span.start

**Comment by bobhy** [comment]
It feels like we're fixing the symptom, not the problem here.
Maybe better to find the underlying problem and fix that (probably only in one place) rather than have to patch this kind of workaround into an unknown number of downstream places it might be needed?

**Comment by amtoine** [comment]
agree with @bobhy 
what i'm not happy with this is that i'm not able to simplify the example above and find where the true issue comes from :thinking:
so i do not know if https://github.com/nushell/nushell/pull/9143 is the way to go...

**Comment by tesla232** [comment]
Is there a way to access the values at a span? I have a feeling it has to do with the mu being too large, but I want to check what's being stored in the location span represents.

**Comment by amtoine** [comment]
> Is there a way to access the values at a span? I have a feeling it has to do with the mu being too large, but I want to check what's being stored in the location span represents.
>
you can try the `metadata` command :yum: 
otherwise, you can unpack a `Value` from the Rust side and have access to its `span` i think :+1:

**Comment by tesla232** [comment]
I was able to simplify the example. The below code will produce the same panic in debug:
`"88799828.753234ns" | into duration`
The issue is that for some reason the input span of
https://github.com/nushell/nushell/blob/2a484a3e7e169e699766e1883ccb1286b2383212/crates/nu-parser/src/parser.rs#L2250 
always has a length of 14. Therefore when you put in a sufficiently large number into "into duration", the span is unable to contain the value inputted. I am still unable to determine where the number 14 comes from but will keep looking into it.

**Comment by fdncred** [comment]
I can't seem to get it to panic on the latest main branch. It looks like it's discarding everything after the decimal.
![image](https://github.com/nushell/nushell/assets/343840/3b4c618a-d512-4ac3-bdbe-9029bbc6e8b2)

**Comment by amtoine** [comment]
@tesla232 @fdncred 
i was able to reproduce this with the `"88799828.753234ns" | into duration` command on 43a3983d3624dae6ad4fd3e6f7a9cac031ea8865 after a `cargo run -- -n` :+1:

**Comment by amtoine** [comment]
> not sure why it fails sometimes and not others.
>
i'm able to reproduce this quite consistently :open_mouth: 
```
cargo run -- -n -c '"88799828.753234ns" | into duration'
```
always fails
```
thread 'main' panicked at 'Can't create a Span whose end < start, start=92494, end=92492', crates/nu-protocol/src/span.rs:32:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
