### ISSUE TITLE
Add date parsing command

### ISSUE THREAD

**Issue by pingiun** [nushell/nushell#8950]
### Related problem

We have a date format command, but not the opposite. It's useful to be able to parse dates from emails (MIME), web pages, APIs, anything that isn't formatted as ISO8601.

### Describe the solution you'd like

A `date parse` command that parses a date using a format string. I think it would also be useful to support MIME dates (`Thu, 20 Apr 2023 22:02:39 -0700 (PDT)`), as they can be found in a lot of protocols (HTTP, email).

### Describe alternatives you've considered

This functionality might also be possible to implement using a combination of `parse` and lots of scripting. So it could be added to the stdlib

### Additional context and details

This was briefly discussed on discord: https://discord.com/channels/601130461678272522/614593951969574961/1098674641297473616

**Comment by pingiun** [comment]
Yes that fits my thoughts. I was thinking we could also add options like --mime --rfc3999, which would allow you to omit the format string because it uses the predefined format

**Comment by pingiun** [comment]
I see now that '%+' exists in `date format` for iso8601 and it defaults to rfc 2822 (mime), so it would make sense for `date parse` to do the same thing. Although I kinda dislike defaulting to rfc 2822 and would rather see rfc3999

**Comment by pingiun** [comment]
@fdncred 'into date' already has a format option, I don't know why you suggested adding an additional command

**Comment by fdncred** [comment]
ya, i forgot about `into datetime -f`. Sorry. Sometimes it's hard to remember every feature that nushell supports. 😄 

I wonder if it should maybe be moved to `date parse` because that seems more intuitive? or maybe the same code called from two different places?

**Comment by bobhy** [comment]
I think `| into datetime` parses mime format datetime strings, and resolves the feature request in OP?
```
〉"Thu, 20 Apr 2023 22:02:39 -0700 (PDT)" | into datetime
Thu, 20 Apr 2023 22:02:39 -0700 (a day ago)
〉"Thu, 20 Apr 2023 22:02:39 -0700 (PDT)" | into datetime | describe
date
```

As for whether we should also have a `parse datetime`, I'd say no.  
You could create aliases for all those conversions as `parse <type>`, but what does that gain?  
All the functionality is already handled by the various `into <type>` commands.  
I'd say nushell should keep its command namespace lean(er) and mean(er), not grow more redundant.

And I think "Parse" as a term in nushell should retain its current, more specialized, connotation: "to parse" means to extract (and maybe deserialize) types from a longer string, not (primarily) to convert a string into some other type one for one.

**Comment by fdncred** [comment]
ok, let's close this. `path parse` and `url parse` are a little different than `date parse` would've been. We can live with `into datetime -f` for now.
