### ISSUE TITLE
Mapping keys without modifiers

### ISSUE THREAD

**Issue by ShinyZero0** [nushell/nushell#8977]
### Related problem

So i tried to make autopairs like this:
```php
{
    name: autoparen
    modifier: none
    keycode: 'char_('
    mode: [emacs,  vi_insert]
    event: [ 
        { edit: InsertChar value: ")" }
        { edit: MoveLeft }
    ]
}
```
but it just doesn't work and doesn't throw any errors. I tried changing `char_(` to some ordinary letters and to 9 with modifier shift and it didn't work too. What worked was remapping to e.g. char b with mod control but that's useless in this case.

### Describe the solution you'd like

To allow users to redefine insert mode keymaps so that we will be able to make scripts for that (see how much autopairs plugins there are for vim)

### Describe alternatives you've considered

include autopairs into reedline, but some users may not like how devs'd implement that feature

**Comment by amtoine** [comment]
i'm wondering if that could be `char_lparen` instead of `char_(` :thinking:

**Comment by fdncred** [comment]
I'm thinking that quotes doesn't work for character names
https://github.com/nushell/nushell/blob/7413ef28243d7586037b8b0b9133e6e7c7d44255/crates/nu-cli/src/reedline_config.rs#L651

**Comment by ShinyZero0** [comment]
It didn't work with `char_b` nor `'char_b'` when typing `b` anyway

**Comment by fdncred** [comment]
ya, i confirmed that `'char_('` is being parsed correctly and it's being assigned the appropriate `KeyCode::Char()`. This is my debug text.
```
char: "char_("
keycode: Char(
    '(',
)
```
There could be something in reedline or crossterm not understanding it?

**Comment by sholderbach** [comment]
We "special-case" the printable characters that should regularly be inserted into your buffer in `emacs` or `vi-insert` mode in reedline so we can directly insert them into the buffer if I recall. (and have the vi-normal statemachine separately hardcoded).

(I remember having a similar discussion previously around matching parens etc. but couldn't find the issue/discussion)

**Comment by fdncred** [comment]
This works now, a derivative to the OP.
```
 {
    name: autoparen
    modifier: none
    keycode: 'char_('
    mode: [emacs vi_normal vi_insert]
    event: [ 
        { edit: InsertChar value: "(" }
        { edit: InsertChar value: ")" }
        { edit: MoveLeft }
    ]
  }
```
