### ISSUE TITLE
Add character number flag to input

### ISSUE THREAD

**Issue by ShinyZero0** [nushell/nushell#8978]
### Related problem

It would be nice if we could do some keymap layers and menus with nu. Bash can do it with its `read -n 1` which just reads exactly one keycode and outputs it. There is an example of how it can be used with a simple loop and power of NUON:
```nu
let keydefs = [ 
    {
        lhs: "f"
        rhs: {|| _focus }
        exit: true
    },
    {
        lhs: "s"
        rhs: {|| _select }
        exit: true
    },
    {
        lhs: "q"
        rhs: {|| }
        exit: true
    }
]
def-env hydra [] {
    while true {
        let key = ( readkey -b )
        let matchedKeys = ( $keydefs | where lhs == $key )
        mut matchedKey = {}
        if ( $matchedKeys | is-empty ) {
            print "Undefined key: " $key
        } else {
            $matchedKey = $matchedKeys.0
            do $matchedKey.rhs
            if $matchedKey.exit { break }
        }

    } 
}
```
it is a keymap layer which can call user commands like in Emacs/neovim hydra. The more simple example would be confirmation prompt with `y` mapped to confirmation and `n` mapped to declination, how it is done in [gum](https://github.com/charmbracelet/gum) which would be very nice to have in shell. What is not nice is that i had to dig out some 4 y.o. C project with 5 stars on gh and compile it in order to get this basic functionality

### Describe the solution you'd like

Add `-n` flag like in bash 

### Describe alternatives you've considered

something like `--single-char` idk

**Comment by amtoine** [comment]
i'm not sure i see where the `readkey` command comes from :yum:

**Comment by ShinyZero0** [comment]
> i'm not sure i see where the `readkey` command comes from

https://github.com/michael105/readkey
i already sent that in discord

**Comment by fdncred** [comment]
seems like we could have a subcommand like `input key` or `input -n #` to do something like this.

**Comment by weirdan** [comment]
`input -n 1` is now available
