### ISSUE TITLE
How to set marker color?

### ISSUE THREAD

**Issue by Slushee-a** [nushell/nushell#8979]
### Question

I can't find anywhere how to set the prompt marker color. It's stuck being cyan_bold and I'd like it to be purple_bold.

**Comment by fdncred** [comment]
If you look [here](https://www.nushell.sh/book/coloring_and_theming.html#prompt-configuration-and-coloring), you'll see that the prompt is controlled by environment variables.

You can do something like this to change the `>` to purple_bold.
```
let-env PROMPT_INDICATOR = $"(ansi purple_bold)> (ansi reset)"
```

**Comment by Slushee-a** [comment]
Thank you so much! 

I did try adding `(ansi purple_bold)` inside the quotation marks, but it would just interpret it as plaintext. I didn't know I had to add the `$` in front. It works now! Thanks again.

If you think it's appropriate, I could make a PR adding a note on that on the customization page of the documentation.

**Comment by fdncred** [comment]
We call this string interpolation. It's used quite frequently in our nu_scripts repo and there's probably some documentation on it. If you want to be more verbose about how to change these settings, feel free.

**Comment by Slushee-a** [comment]
String interpolation! Somehow I've completely missed that section of the `working with strings` chapter on the book. Unless it's relatively new, I read it a good while back. But I doubt that, so it's completely on me.

Considering that string interpolation is already documented, I think this issue will be enough for those who come searching for the same question (there's another issue with this question unanswered)
