### ISSUE TITLE
Using winresource instead of winres

### ISSUE THREAD

**Issue by WindSoilder** [nushell/nushell#8986]
### Describe the solution you'd like

Refer to the pr:
https://github.com/mxre/winres/pull/45
I found winres is not active, so I'd propose use [winresource](https://crates.io/crates/winresource) instead, one benefit is that we can update `toml` dependency to 0.7

I want to finish it bymyself, but sadly I don't have a windows machine :-(

**Comment by rgwood** [comment]
Thanks for looking into this @WindSoilder! I should be able to do this.
