### ISSUE TITLE
`std help` -- Missing error for `std help <noSuchName>`; Missing output for `std help --find <singleMatch>`

### ISSUE THREAD

**Issue by bobhy** [nushell/nushell#8992]
### Describe the bug

(I'm overloading this bug report with multiple issues because I propose to fix all with one PR)

## Missing error for `std help <noSuchName>`
`std help` doesn't produce *any* error message when invoked with a non-existant item name.
```
〉std help bogon
〉
```
c.f. helpful error from built-in help:
```〉help bogon
Error: nu::parser::not_found

  × Not found.
   ╭─[entry #5:1:1]
 1 │ help bogon
   ·      ──┬──
   ·        ╰── did not find anything under this name
   ╰────
```
If you specify type of item, then you do get a command-not-found error, though slightly garbled:
```
〉std help commands bogon
Error: 
  × std::help::command_not_found
     ╭─[help:665:1]
 665 │ 
 666 │     let command = ($command | str join " ")
     ·     ─┬─
     ·      ╰── command not found
 667 │     if not ($find | is-empty) {
     ╰────
```
and similarly for other explicit types, modules, externs, aliases:
```
〉std help modules bogon
Error: nu::shell::external_command

  × External command failed
     ╭─[help:265:1]
 265 │         if ($found_module | is-empty) {
 266 │             module_not_found_error (metadata $module | get span)
     ·                                    ──────────────┬──────────────
     ·                                                  ╰── Cannot convert record<start: int, end: int> to a string
 267 │         }
     ╰────
  help: All arguments to an external command need to be string-compatible

```
## Missing output for `std help --find <singleMatch>`
If `--find` invoked with a string that only matches a single item, no output is produced.
```
〉std help --find "std assert skip"
〉
```
vs expected output when string matches more than one:
```
〉std help --find "std assert" | select name category usage
╭──────────┬──────────────────────────────────┬───────────────┬────────────────────────────────────────────────────────╮
│        # │               name               │   category    │                         usage                          │
├──────────┼──────────────────────────────────┼───────────────┼────────────────────────────────────────────────────────┤
│        0 │ std assert                       │ default       │ Universal assert command                               │
│        1 │ std assert equal                 │ default       │ Assert $left == $right                                 │
│        2 │ std assert error                 │ default       │ Assert that executing the code generates an error      │
│        3 │ std assert greater               │ default       │ Assert $left > $right                                  │
│        4 │ std assert greater or equal      │ default       │ Assert $left >= $right                                 │
│        5 │ std assert length                │ default       │ Assert length of $left is $right                       │
│        6 │ std assert less                  │ default       │ Assert $left < $right                                  │
│        7 │ std assert less or equal         │ default       │ Assert $left <= $right                                 │
│        8 │ std assert not equal             │ default       │ Assert $left != $right                                 │
│        9 │ std assert skip                  │ default       │ Skip the current test case                             │
│       10 │ std assert str contains          │ default       │ Assert that ($left | str contains $right)              │
╰──────────┴──────────────────────────────────┴───────────────┴────────────────────────────────────────────────────────╯
```

### How to reproduce

as above...

### Expected behavior

When invoked simply as `std help bogon`, I'd like to see a `nothing found` error (but not `command-not-found` or `module-not-found`, because we don't know what type the name might actually be.)

Fix the referred span in the error when invoked with the more specific `std help command` or `std help modules`.  I think we can have a single `item-not-found` rather than multiple distinct errors.  There's at least one context we need the generic one.

Fix the `--find` so it returns a table with one or more rows, or a `match-not-found` error if none.  (currently, the built-in `help --find bogon` returns an empty table, which is better than nothing.  But an explicit error would make help more scriptable.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.78.1                                   |
| branch             | help_help                                |
| commit_hash        | 80358bad29c826340e76640df76f35886061e20b |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-04-24 18:21:27 -04:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by amtoine** [comment]
> (I'm overloading this bug report with multiple issues because I propose to fix all with one PR)
>
if the changes are not directly related, multiple PRs would be great :+1: 

1. agree with the first point.
2. as for the second, `std help --find "std assert skip"` and `std help "std assert skip"` don't return anything: is it the right example? are there other commands to run before?
3. you mention "multiple issues", are there more than these two above? :open_mouth:

**Comment by bobhy** [comment]
I retract the issue, I can no longer repro it on latest `main`.  I've got lots of other concerns about `help`, but will raise (more carefully researched) separate issues for them.
