### ISSUE TITLE
Nu prints empty lines after first keyboard press when started automatically. 

### ISSUE THREAD

**Issue by TomLebeda** [nushell/nushell#8993]
### Describe the bug

When I open terminal with bash and run "nu", everything works fine. 
But when I start terminal with nu already running (via exec or chsh), after the first keyboard press, the first line jumps into the middle of the screen (as if printing empty lines). After that, it works fine as well. 

### How to reproduce

1. start terminal with nushell by adding "exec nu" at the end of .bashrc
2. start terminal (nu should now be running)
3. press anything on keyboard

### Expected behavior

Don't jump/print empty lines after the first keypress. 

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.78.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 2ec20286371f1d90a77fdd5d82818c6c5851f090                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27) (Arch Linux rust 1:1.68.2-1) |
| cargo_version      | cargo 1.68.2                                                     |
| build_time         | 2023-04-05 02:09:35 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | default, zip                                                     |
| installed_plugins  |                                                                  |

**Comment by TomLebeda** [comment]
Just found out that it does it in WezTerm, but in Alacritty, it works just fine.

**Comment by TomLebeda** [comment]
Well I tried to search for it, but didn't find anything. But since I found out it is working fine in Alacritty, I don't really care (I use Alacritty for terminal work and WezTerm for Neovim because of ligatures). Thanks anyway!

**Comment by fdncred** [comment]
Here's a few similar issues for people who stumble upon this issue in the future.
https://github.com/nushell/nushell/issues/8213
https://github.com/nushell/nushell/issues/5025
https://github.com/nushell/nushell/issues/8935
