### ISSUE TITLE
Can't override table style temporarily?

### ISSUE THREAD

**Issue by bobhy** [nushell/nushell#8997]
### Describe the bug

Trying to run a `table` command in a closure or a `def` using a non-default style (e.g, `with_love` instead of `rounded`), can't seem to find the magic formula to allow me to temporarily override the mode that `table` will use.  

### How to reproduce

```
〉$env.config.table.mode
rounded
〉do { || $env.config.table.mode = light; print $env.config.table.mode ; ls | take 4 | table }
light
╭───┬────────────────────┬──────┬──────────┬──────────────╮
│ # │        name        │ type │   size   │   modified   │
├───┼────────────────────┼──────┼──────────┼──────────────┤
│ 0 │ CODE_OF_CONDUCT.md │ file │   3.4 KB │ 2 months ago │
│ 1 │ CONTRIBUTING.md    │ file │  10.2 KB │ a week ago   │
│ 2 │ Cargo.lock         │ file │ 149.6 KB │ 5 days ago   │
│ 3 │ Cargo.toml         │ file │   5.1 KB │ 5 days ago   │
╰───┴────────────────────┴──────┴──────────┴──────────────╯
〉$env.config.table.mode
rounded
```

Thinking maybe you can't update an environment variable in same scope as you want to use it, though that doesn't really make sense, i tried setting the env var in an outer closure, but it also fails.

```
〉do { || $env.config.table.mode = light; do { || print $env.config.table.mode ; ls | take 4 | table }}
light
╭───┬────────────────────┬──────┬──────────┬──────────────╮
│ # │        name        │ type │   size   │   modified   │
├───┼────────────────────┼──────┼──────────┼──────────────┤
│ 0 │ CODE_OF_CONDUCT.md │ file │   3.4 KB │ 2 months ago │
│ 1 │ CONTRIBUTING.md    │ file │  10.2 KB │ a week ago   │
│ 2 │ Cargo.lock         │ file │ 149.6 KB │ 5 days ago   │
│ 3 │ Cargo.toml         │ file │   5.1 KB │ 5 days ago   │
╰───┴────────────────────┴──────┴──────────┴──────────────╯
```

(In addition to the repros above, I tried using `with-env [config.table.mode light] { . . . }`, but that didn't seem to even change the value of the environment variable within the closure.  I don't care so much about using that if `with-env` is about to be deprecated.)

### Expected behavior

I expected the above to render as:

```
〉$env.config.table.mode = light
〉ls | take 4 | table
 #          name          type     size       modified   
─────────────────────────────────────────────────────────
 0   CODE_OF_CONDUCT.md   file     3.4 KB   2 months ago 
 1   CONTRIBUTING.md      file    10.2 KB   a week ago   
 2   Cargo.lock           file   149.6 KB   5 days ago   
 3   Cargo.toml           file     5.1 KB   5 days ago   
```

BTW, this confirms that `table` responds to the current value of `$env.config.table.mode` in *some* scope.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.78.1                                   |
| branch             | help_help                                |
| commit_hash        | 80358bad29c826340e76640df76f35886061e20b |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-04-24 18:21:27 -04:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

### Additional context

One way to accomplish this pretty directly would be to add a `--mode` flag to `table`.

**Comment by bobhy** [comment]
FWIW, same problem repros on the newly-released 0.79:
```
〉do { || $env.config.table.mode = light; do { || print $env.config.table.mode ; ls | take 4 | table }}
light
╭───┬────────────────────────────┬──────┬────────┬───────────────╮
│ # │            name            │ type │  size  │   modified    │
├───┼────────────────────────────┼──────┼────────┼───────────────┤
│ 0 │ 2023-01-31-nushell_0_75.md │ file │ 5.8 KB │ 2 months ago  │
│ 1 │ Android                    │ dir  │    4 B │ 8 months ago  │
│ 2 │ Charts                     │ dir  │    5 B │ 10 months ago │
│ 3 │ Desktop                    │ dir  │    3 B │ 8 months ago  │
╰───┴────────────────────────────┴──────┴────────┴───────────────╯
```
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.79.0                                   |
| branch             | help_help                                |
| commit_hash        | ee9b7f0431e031a33721a8e8c265972ee02df152 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-04-25 16:26:06 -04:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
This has never been a capability that worked the way you describe. So, this is more of a feature request in my mind.

**Comment by bobhy** [comment]
Based on the comments in `config.nu`, I reasoned that the fields in
`$env.config.table` influenced the behavior of `table`.   And so they
do, but only after certain kinds of changes!  What am I missing about
the cases where it doesn't work?

As a feature request, I'd be asking for *both* `table --mode` *and*
the fix that would make the environment override work as "expected".

**Comment by fdncred** [comment]
I'm not disagreeing with you. It's logical to assume it would work, but it never has. I don't remember why. It's going to take some research.

**Comment by bobhy** [comment]
still repros in 0.79.1.  
Maybe not too tricky, a good first feature?

**Comment by amtoine** [comment]
> Maybe not too tricky, a good first feature?
>
from my experience, the config part of the source of Nushell is not easy at all to work with :thinking: 
not sure that's a *good first issue* :confused:

**Comment by fdncred** [comment]
there's also some deprecated parts of the config that need to be removed. the parts before we started using the structured config file.

**Comment by melMass** [comment]
Isn't that just because this is scoped by the closure? if you do a `let-env` and `upsert` it should work

**Comment by CAD97** [comment]
This seems to function as desired as of 0.86.0:

```shell
~> do { || $env.config.table.mode = light; print $env.config.table.mode ; ls | take 4 | table }
light
 #     name     type    size     modified
────────────────────────────────────────────
 0   .android   dir       0 B   a year ago
 1   .cache     dir       0 B   a year ago
 2   .cisco     dir       0 B   a year ago
 3   .dotnet    dir    8.2 KB   a month ago
~> do { || $env.config.table.mode = rounded; print $env.config.table.mode ; ls | take 4 | table }
rounded
╭───┬──────────┬──────┬────────┬─────────────╮
│ # │   name   │ type │  size  │  modified   │
├───┼──────────┼──────┼────────┼─────────────┤
│ 0 │ .android │ dir  │    0 B │ a year ago  │
│ 1 │ .cache   │ dir  │    0 B │ a year ago  │
│ 2 │ .cisco   │ dir  │    0 B │ a year ago  │
│ 3 │ .dotnet  │ dir  │ 8.2 KB │ a month ago │
╰───┴──────────┴──────┴────────┴─────────────╯
```

**Comment by fdncred** [comment]
Agreed. I think this was fixed a while back because I wrote a script to dynamically change themes and do automatic screenshots. All that is related to this. Let's close this. If someone finds that it's still a problem, we can reopen it.
