### ISSUE TITLE
`overlay {use,new,hide} --help` return an internal error

### ISSUE THREAD

**Issue by epbuennig** [nushell/nushell#9005]
### Describe the bug

Running `overlay {use,new}` with a help flag does not show the help expected message.

```
~
❯ overlay use --help
Error: nu::parser::unknown_state

  × Unknown state.
   ╭─[entry #5:1:1]
 1 │ overlay use --help
   · ─────────┬────────
   ·          ╰── internal error: Missing required positional after call parsing
   ╰────
```

### How to reproduce

1. start nu
2. invoke `overlay use --help` or `overlay new --help`
3. observe the error

### Expected behavior

Return the same message as if `help overlay {use,new}` was invoked.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.78.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 2ec20286371f1d90a77fdd5d82818c6c5851f090                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27) (Arch Linux rust 1:1.68.2-1) |
| cargo_version      | cargo 1.68.2                                                     |
| build_time         | 2023-04-05 02:09:35 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | default, zip                                                     |
| installed_plugins  |                                                                  |

### Additional context

A slightly different but surely related error:
```
~
❯ overlay hide --help
Error: nu::parser::cant_hide_default_overlay

  × Cannot hide default overlay.
   ╭─[entry #13:1:1]
 1 │ overlay hide --help
   · ─────────┬─────────
   ·          ╰── can't hide overlay
   ╰────
  help: 'zero' is a default overlay. Default overlays cannot be hidden.

```
`help overlay hide` works as expected.

Running `overlay list --help` works, presumably because it has no required positional argument.

**Comment by fdncred** [comment]
I have no issues on the latest version. Must have been fixed already?
```
overlay list --help 
List all active overlays.

The overlays are listed in the order they were activated.

Usage:
  > overlay list

Flags:
  -h, --help - Display the help message for this command

Signatures:
  <nothing> | overlay list -> list<string>

Examples:
  Get the last activated overlay
  > module spam { export def foo [] { "foo" } }
    overlay use spam
    overlay list | last
  spam
```

**Comment by fdncred** [comment]
oh, ya. i see the same error now. sorry for my earlier comment. :)
