### ISSUE TITLE
Non-existent cell path causes an error if it's not first and --ignore-errors passed

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [nushell/nushell#9008]
### Describe the bug

Non-existent cell path causes an error if it's not first and --ignore-errors passed like `sys | get --ignore-errors bla bla2`.

### How to reproduce

1. `sys | get --ignore-errors bla bla2`
2. get error:

```
Error: nu::shell::column_not_found

  × Cannot find column
   ╭─[entry #125:1:1]
 1 │ sys | get --ignore-errors bla bla2
   · ─┬─                           ──┬─
   ·  │                              ╰── cannot find column 'bla2'
   ·  ╰── value originates here
   ╰────

```

### Expected behavior

No error as documentation [states](https://www.nushell.sh/commands/docs/get.html#parameters):

> --ignore-errors (-i): ignore missing data (make **all** cell path members optional)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.79.0                                   |
| branch             |                                          |
| commit_hash        | a1b72611215dbfca257351003204a80c83859e05 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-04-25 20:26:29 +00:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

### Additional context

Using --ignore-error twice before each cell path doesn't help.

**Comment by weirdan** [comment]
This appears to be fixed:
```console
$ sys mem | get -i blah blah2
╭───┬──╮
│ 0 │  │
│ 1 │  │
╰───┴──╯
```

**Comment by sholderbach** [comment]
(Probably time for a separate issue)

Ok the naming of the resulting record from `get` is a bit weird to me.

With
```nushell
sys mem | get -i bla
```

it simply returns `null`

When the keys are found it creates a record with those keys
```nushell
sys mem | select -i total free
╭───────┬─────────╮
│ total │ 14.6 GB │
│ free  │ 13.6 GB │
╰───────┴─────────╯
```

But for the unknown keys if more than one are given it invents new column names.

And to top it of if one of the keys is found:
```nushell
sys mem | select -i total bla
╭───────┬─────────╮
│ total │ 14.6 GB │
│ bla   │         │
╰───────┴─────────╯
```
