### ISSUE TITLE
Windows cmd.exe

### ISSUE THREAD

**Issue by ghost** [nushell/nushell#901]
Launching this program with Windows, you get:

~~~
[32mC:\nushell_0_4_0 [m>
~~~

Where I assume the garbage is supposed to be color output. Further, the program
cannot be closed by any of Ctrl+C, Ctrl+D, Ctrl+Z.

**Comment by jonathandturner** [comment]
Thanks for the report @cup. What version of Windows are you running in? (if Windows 10, do you know what date of Windows 10 you're running?)

**Comment by cup** [comment]
Windows 7

**Comment by jonathandturner** [comment]
Sorry to say, but we don't currently have plans for directly supporting Windows 7. 

That's not to say it won't work with a bit of creativity. You may be able to run it through programs other than cmd.exe. Any of the true color terminals listed here should work for running Nu: https://gist.github.com/XVilka/8346728 

To your other question, you exit the terminal by running `exit`.

**Comment by cup** [comment]
@jonathandturner is the fact that Windows 7 is not supported documented?

**Comment by jonathandturner** [comment]
I'll update the README to mention it.

**Comment by cup** [comment]
You should probably just go ahead and say that only Windows 10 is supported, as Windows 8.1 doesnt work either.

**Comment by kud1ing** [comment]
Not entirely sure whether this applies to this, but maybe it is helpful to anyone: `py-spy` needed [this adjustment](https://github.com/benfred/py-spy/commit/b32c4942e8db22883096f85e489039a41096d5b0) for Windows 7 which is based on https://docs.rs/console which seems to support colors.

**Comment by jonathandturner** [comment]
Made it more clear that Windows 10 is the supported Windows version.  In the future, we may extend to earlier Windows versions, and we can revisit then.
