### ISSUE TITLE
Print Aliases

### ISSUE THREAD

**Issue by Ktoks** [nushell/nushell#9011]
### Related problem

The problem is not being able to print off and view my aliases - this is a feature bash provides.
Simply by inputting in `alias` - bash outputs all aliases for the current environment/session.

### Describe the solution you'd like

I would like to have similar output to `alias` from bash, but perhaps like nu's `ls` command- it could separate the output into 2 columns split column by ` = `. This would be an upgrade on the bash `alias` functionality - and could greatly improve productivity for those who repeatedly use complicated commands.

### Describe alternatives you've considered

I've considered writing my own `nu` function, but discarded the idea because - currently that would not work in my environment as an aliased command or script.

### Additional context and details

I'm unable to run nu scripts that call other scripts or functions because I don't have root access on said environment. Administrators and governance are currently deliberating over installing it.

**Comment by pingiun** [comment]
try `$nu.scope.aliases`

**Comment by Ktoks** [comment]
That's great, kind of long, but it does have all the functionality I was looking for. How hard would it be to implement an empty alias call to output the same?

**Comment by fdncred** [comment]
How about `help aliases`?

**Comment by Ktoks** [comment]
I can remember that.
Thank you.
Sorry, I should have brought this up on Discord.
