### ISSUE TITLE
second last line overlapping

### ISSUE THREAD

**Issue by Banyc** [nushell/nushell#9015]
### Describe the bug

Background:

- terminal: vscode terminal
- os: macos

The second last line gets overwritten by the input prompt.

<img width="347" alt="Screenshot" src="https://user-images.githubusercontent.com/36535895/234649258-6629786f-fbfa-434c-8abf-df71024ed5a2.png">

- The line "Startup Time: ..." is been overwritten by the input prompt
- It does not just happen visually but actually rewrites the line

### How to reproduce

1. Reduce the size of the terminal window by shrinking it down a bit
2. Type something
3. The input prompt goes up a line so that the second last line will be overwrited by the input prompt

### Expected behavior

The input prompt should not overwrite the previous line.

### Screenshots

<img width="384" alt="Screenshot" src="https://user-images.githubusercontent.com/36535895/234650654-2631733b-7696-4daa-8ef7-cbdd3078cb93.png">

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.79.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-x86_64                                                      |
| build_target       | x86_64-apple-darwin                                               |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27) (built from a source tarball) |
| cargo_version      | cargo 1.68.1 (6feb7c9cf 2023-03-26)                               |
| build_time         | 2023-04-25 20:06:17 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

### Additional context

- I have tried the same steps on the Terminal app and the bug does not reproduce on it.
- The bug might not be reproduced sparsely.

**Comment by fdncred** [comment]
hmmm, i use wezterm, iterm2, terminal.app, vscode term and haven't see this on my mac. i'll test later on this afternoon again to see if i can repro it. it could also be some odd bug in the vscode terminal code.

**Comment by Banyc** [comment]
It even happens to wezterm

**Comment by fdncred** [comment]
I'm still not sure how to reproduce this. I use wezterm all the time on macos. I have a custom prompt and when i resize the windows, it gets messed up. It's been that way for a long time. If that's what we're talking about, I'm not sure what can be done to fix it. Redrawing the prompt based on resizing is non-trivial. We had some code in reedline to do that but took it out because it was more of a mess than just living with how it works now.

**Comment by Banyc** [comment]
I recorded the behavior here:

![Kapture](https://user-images.githubusercontent.com/36535895/235311182-3c097cbd-bfeb-4657-83d6-80f340db650a.gif)

The gif is 4mb big. It might takes some time to load.

**Comment by fdncred** [comment]
right. good video. I think this is a reedline thing. contributions welcome there to try and fix this when resizing.

**Comment by Banyc** [comment]
https://github.com/nushell/reedline/blob/ec002a7ce8b0776ebcd87890570e802c5294a256/src/painting/painter.rs#L416

I think this line should be fixed into the following line instead:

```rust
self.prompt_start_row = height - 1;
```

There might be a reason for subtracting 2 currently so I'm not so sure about this change.

**Comment by fdncred** [comment]
maybe so. have you tested it in reedline to see if it fixes the problem? or in reedline and nushell?

**Comment by Banyc** [comment]
I have pulled out a PR and it fixed the problem! But I haven't do the checks/tests yet...

**Comment by sholderbach** [comment]
Thanks for giving this a shot @Banyc 

Related issues that are worth checking to see if they are resolved:

https://github.com/nushell/reedline/issues/408 (sounds very similar to this one)
https://github.com/nushell/reedline/issues/528 (Might be a separate one)
https://github.com/nushell/reedline/issues/157 (vertical resize focussed)
https://github.com/nushell/reedline/issues/42 (the OG story of painter pain points)
