### ISSUE TITLE
nushell shouldn't do anything job control-y when not in interactive mode

### ISSUE THREAD

**Issue by yshui** [nushell/nushell#9026]
### Describe the bug

Even when nushell is started in non-interactive mode (i.e. `nu -c command`), it still does job control stuff (e.g. blocking SIGTSTP, set tty foreground process group, etc.). 

Most shells (e.g. bash, zsh, dash) will disable job control when not in interactive mode, unless explicitly turned on by options. nushell should do this same.

### How to reproduce

1. `nu -c command`

### Expected behavior

nu doesn't block TSTP, and doesn't create new process groups.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.78.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 2ec20286371f1d90a77fdd5d82818c6c5851f090                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27) (Arch Linux rust 1:1.68.2-1) |
| cargo_version      | cargo 1.68.2                                                     |
| build_time         | 2023-04-05 02:09:35 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | default, zip                                                     |
| installed_plugins  |                                                                  |

**Comment by yshui** [comment]
as a more concrete example, the expected result of pressing Ctrl-Z while running `nu -c nvim`, is `nu` being suspended along with `nvim`.

**Comment by amtoine** [comment]
> as a more concrete example, the expected result of pressing Ctrl-Z while running `nu -c nvim`, is `nu` being suspended along with `nvim`.
>
how would you un-suspend `nvim` and `nu` after pressing `<C-z>`?

i'm not sure i see the use case of this, not super familiar with SIG control signals :yum:

**Comment by yshui** [comment]
so if I run `nu` in non-interactive mode, job control would be the responsibility of whatever I ran `nu` from. If I ran `nu -c nvim` from another nushell instance, then it will inherit the blocked signals and I won't be able to suspend it. If I ran `nu -c nvim` from a `zsh` instance, then I will be able to un-suspend it by running `fg` in zsh.

**Comment by IanManske** [comment]
@fdncred  I think this should still be open. Although #9693 fixes nushell setting the foreground process group, it doesn't fix anything regarding signals.
