### ISSUE TITLE
Type inference for `if`

### ISSUE THREAD

**Issue by epbuennig** [nushell/nushell#9036]
### Describe the bug

An if that evaluates to an `int` in every branch is mistakenly inferred to evaluate to a `bool`.

This does not compile but would always succeed at runtime:
```nu
def fail-comp [var: bool] {
  3 + (if $var { -1 } else { +1 })
}
```
Likewise, this compiles but always fails at runtime:
```nu
def fail-run [var: bool] {
  true and (if $var { -1 } else { +1 })
}
```

### How to reproduce

1. define or try to define the given functions above
2. observe the contradictory behavior seen in the attached screenshots

### Expected behavior

The `if` expression is inferred to be an `int` on every branch.

### Screenshots

![image](https://user-images.githubusercontent.com/103939966/235148138-e55078a4-66f8-46fb-83da-c88cc1e2734e.png)
![image](https://user-images.githubusercontent.com/103939966/235148187-265b0247-d49b-4237-b0ff-dcb80784e0a3.png)
![image](https://user-images.githubusercontent.com/103939966/235148168-ad24c38a-77b1-4982-a74d-0ce821424da2.png)

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.79.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | a1b72611215dbfca257351003204a80c83859e05                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) (Arch Linux rust 1:1.69.0-2) |
| cargo_version      | cargo 1.69.0                                                     |
| build_time         | 2023-04-27 07:32:56 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | default, zip                                                     |
| installed_plugins  |                                                                  |

**Comment by epbuennig** [comment]
A current workaround is using `expr | into int` where `expr` is the `if` expression.

**Comment by KAAtheWiseGit** [comment]
This is no longer reproducible with Nushell `0.86.0`.

**Comment by amtoine** [comment]
thanks again @KAAtheWiseGit, this indeed looks like its working now :pray:
