### ISSUE TITLE
table drawing regression

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#9038]
### Describe the bug

@zhiburt It looks like we have a table drawing regression in the latest main. I haven't tracked down when it started. It could be with your latest PR but not positive. Would you mind looking at it please? Here's what it looks like. I think we've seen this before.
![image](https://user-images.githubusercontent.com/343840/235162166-bd7416da-f822-40f1-a421-97e2e0c3364a.png)

### How to reproduce

`help modules`

### Expected behavior

table border lines lined up accordingly

### Configuration

|key|value|
|-|-|
|version|0.79.1|
|branch|pr/amtoine/9034|
|commit_hash|2d6be47c7ff424f70327c7f918fa2c85aaa1d113|
|build_os|windows-x86_64|
|build_target|x86_64-pc-windows-msvc|
|rust_version|rustc 1.67.1 (d5a82bbd2 2023-02-07)|
|rust_channel|1.67.1-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.67.1 (8ecd4f20a 2023-01-10)|
|build_time|2023-04-28 08:31:26 -05:00|
|build_rust_channel|debug|
|features|default, zip|
|installed_plugins|from eml, from ics, from ini, from parquet, from plist, from vcf, gstat, hist, inc, json path, periodic-table, plot, pnet, query, query json, query web, query xml, regex, xyplot|

**Comment by fdncred** [comment]
For all I know, it could be windows related, maybe line ending issues?

**Comment by zhiburt** [comment]
> I think we've seen this before.

Yes 

> 
For all I know, it could be windows related, maybe line ending issues?

Yes
