### ISSUE TITLE
find -v returns nothing

### ISSUE THREAD

**Issue by kurokirasama** [nushell/nushell#9043]
### Describe the bug

For instance, executing
```
ls | find -v something
```
returns
```
╭───┬──────┬──────┬──────┬──────────╮
│ # │ name │ type │ size │ modified │
├───┼──────┼──────┼──────┼──────────┤
│ 0 │   ❎ │   ❎ │   ❎ │       ❎ │
│ 1 │   ❎ │   ❎ │   ❎ │       ❎ │
│ 2 │   ❎ │   ❎ │   ❎ │       ❎ │
│ 3 │   ❎ │   ❎ │   ❎ │       ❎ │
│ 4 │   ❎ │   ❎ │   ❎ │       ❎ │
│ 5 │   ❎ │   ❎ │   ❎ │       ❎ │
│ 6 │   ❎ │   ❎ │   ❎ │       ❎ │
│ 7 │   ❎ │   ❎ │   ❎ │       ❎ │
│ 8 │   ❎ │   ❎ │   ❎ │       ❎ │
│ 9 │   ❎ │   ❎ │   ❎ │       ❎ │
╰───┴──────┴──────┴──────┴──────────╯
```

### How to reproduce

Already explained

### Expected behavior

A filtered table

### Configuration

| key                | value                                                                                                                                                           |
| ------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.79.1                                                                                                                                                          |
| branch             | main                                                                                                                                                            |
| commit_hash        | 6047b04208c5b41154453edd4a0e020b4eb7cd25                                                                                                                        |
| build_os           | linux-x86_64                                                                                                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                                                                                                        |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)                                                                                                                             |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu                                                                                                                                 |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)                                                                                                                             |
| build_time         | 2023-04-26 17:25:38 -04:00                                                                                                                                      |
| build_rust_channel | release                                                                                                                                                         |
| features           | default, zip                                                                                                                                                    |
| installed_plugins  | custom-value generate, custom-value generate2, custom-value update, from eml, from ics, from ini, from vcf, gstat, inc, query, query json, query web, query xml |

**Comment by fdncred** [comment]
You want a filtered table when there are no hits or should it return the [empty list] type thing?

**Comment by kurokirasama** [comment]
the filter is with the invert option, so it should return the original table in case there is no mach to filter out.
In case of an empty output, because you filtered out everything, I get correctly an empty list

**Comment by juanPabloMiceli** [comment]
![image](https://user-images.githubusercontent.com/48705702/235834899-4b1df8d6-fca7-4332-8204-c3e9346c936d.png)
I think this is also undesired behaviour right? If so, should I open a new issue or shall this one cover both cases?

**Comment by juanPabloMiceli** [comment]
I don't know if I understand the issue correctly. What would be the expected behaviour for this?

Given this folder structure:
```
foo/
├── file1
└── file2
```
Would this be correct? (Ignore the missing columns)
```
/foo> ls | find 1 -v
╭───┬──────┬──────╮
│ # │ name │ type │
├───┼──────┼──────┤
│ 0 │   ❎ │   ❎ │
╰───┴──────┴──────╯
```
Or this one?
```
/foo> ls | find 1 -v
╭───┬──────┬──────╮
│ # │ name │ type │
├───┼──────┼──────┤
│ 1 │ file2│ file │
╰───┴──────┴──────╯
```
In my opinion the first one is not really helpful, but maybe there is a reason about that decision.

**Comment by fdncred** [comment]
If we use grep as a model, you can do `grep plugin register_plugins.nu` in the root of the nushell repo, and it shows you all of the lines with `plugin` in that file. Now if you do `grep -v plugin register_plugins.nu`, it shows you all of the lines that do not have `plugin` in that file.

So, with your two scenarios above, I'd expect it to show all the files that do not contain 1, which in your case is
```
/foo> ls | find 1 -v
╭───┬──────┬──────╮
│ # │ name │ type │
├───┼──────┼──────┤
│ 1 │ file2│ file │
╰───┴──────┴──────╯
```
however, you have to keep in mind that `find` searches all columns unless you tell it which columns to search. so, i get this in the nushell repo root. it returns all columns in the table if it found a hit in any column in a row.
![image](https://user-images.githubusercontent.com/343840/235912392-50a16504-4a62-4b9d-9ffb-c949fafe20d1.png)

**Comment by amtoine** [comment]
trying to settle this :thinking: 

do you think **`find` and `find -v` should give complementary results?**

that is, with some table `foo`, `foo | find pat` and `foo | find pat --invert` should give, once combined, the original `foo`? *modulo some reordering and sorting*

**Comment by juanPabloMiceli** [comment]
Ok, I can take this. Just to be clear the expected behaviour we discussed is as following right?
1. When using `table | find <pattern>`, we will display a row (all it's columns) if at least one of it's cells matches the pattern. This would also highlight the pattern occurrence.
2. When using `table | find <pattern> -v`, we will display a row (all it's columns) if none of it's cells matches the pattern. This would highlight nothing, but only show the original content of the selected rows.

**Comment by fdncred** [comment]
That's my understanding and I think that's right.

**Comment by fdncred** [comment]
closed by https://github.com/nushell/nushell/pull/9159
