### ISSUE TITLE
Was mkdir "parents" flag removed on purpose?

### ISSUE THREAD

**Issue by juanPabloMiceli** [nushell/nushell#9044]
### Question

mkdir default behaviour is to create parents directories as needed as if the "parents" flag is enable. Is this a design decision or a bug?

**Comment by amtoine** [comment]
@juanPabloMiceli :wave: 

i've never seen a `--parent` / `-p` option for `mkdir`, i'd say it's a feature :yum:

**Comment by sholderbach** [comment]
As far as I can tell the nushell internal `mkdir` which is distinct from the coreutils `mkdir` never had the `-p` flag. 

But the behavior of nu `mkdir bla/blub` is to create the nested directories and also to not fail on preexisting directories. which is similar to coreutils `mkdir -p`
