### ISSUE TITLE
`math round --precision -1` : incorrect results if input is an int

### ISSUE THREAD

**Issue by bobhy** [nushell/nushell#9049]
### Describe the bug

See example

### How to reproduce

```
〉123.45 | math round --precision -1
120
〉123. | math round --precision -1
120
```
Both correct, but
```
〉123 | math round --precision -1
123
```
Should also be `120`.

Even when a float and int input have the same value, I only get correct results from float.
```
〉let vf = 123.0
〉$vf | describe
float
〉$vf | math round --precision -1
120
```
Right!
```
〉let v = 123
〉$v | describe
int
〉$v | math round --precision -1
123
```
Wrong!

### Expected behavior

Since signature says input is  `<number>`, I'd expect the function to handle ints and floats of the same value consistently.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.79.1                                   |
| branch             | help_help                                |
| commit_hash        | 0e07c2c70909df961fc4fa30238d2218a4b14238 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)      |
| rust_channel       | 1.67.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)      |
| build_time         | 2023-04-27 17:50:13 -04:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by juanPabloMiceli** [comment]
I can take it!
