### ISSUE TITLE
Nushell doesn't play nicely with Kitty

### ISSUE THREAD

**Issue by darkwater4213** [nushell/nushell#9052]
### Describe the bug

On occasion, especially with line breaks, Kitty prints the lowest line Nushell has printed in the second- and fourth-lowest rows. What makes it stranger is that the fourth row winds up as a sort of persistent artifact--on both rows.

Stranger still, complicated tables more or less generate semi-recognizable nonsense and simple tables just don't print right.

### How to reproduce

1. Open kitty. This doesn't seem to happen with the Xfce terminal. Everything renders perfectly fine.
2. Create a custom table. Or use `sys`, though it's a little less... uh, noticeable.
3. Run it.
4. Try not to cry at what your kitty has done.

Kitty outputs:
```txt
╭─────┬─────────────┬────────────────────┬────────┬──────────┬─────────┬──────────┬──────────┬───────┬────────────────────────────────────────────────╮
│   # │  Interface  │       Flags        │  mtu   │  qdisc   │  state  │   mode   │  group   │ qlen  │                      MAC                       │
╭─────┬─────────────┬────────────────────┬────────┬──────────┬─────────┬──────────┬──────────┬───────┬────────────────────────────────────────────────╮
│   # │  Interface  │       Flags        │  mtu   │  qdisc   │  state  │   mode   │  group   │ qlen  │                      MAC                       │
├─────┼─────────────┼────────────────────┼────────┼──────────┼─────────┼──────────┼──────────┼───────┼────────────────────────────────────────────────┤
│   0 │ lo          │ ╭───┬──────────╮   │  65536 │ noqueue  │ UNKNOW  │ DEFAULT  │ default  │  1000 │ ╭───┬───────────────────┬───────────────────╮  │
│     │             │ │ 0 │ LOOPBACK │   │        │          │         │          │          │       │ │ # │   link/loopback   │        brd        │  │
│     │             │ │ 1 │ UP       │   │        │          │         │          │          │       │ ├───┼───────────────────┼───────────────────┤  │
│   1 │ wlp2s0      │ ╭───┬───────────╮  │   1500 │ mq       │ UP      │ DORMANT  │ default  │  1000 │ ╭───┬───────────────────┬───────────────────╮  │
│     │             │ │ 0 │ BROADCAST │  │        │          │         │          │          │       │ │ # │    link/ether     │        brd        │  │
│   1 │ wlp2s0      │ ╭───┬───────────╮  │   1500 │ mq       │ UP      │ DORMANT  │ default  │  1000 │ ╭───┬───────────────────┬───────────────────╮  │
│     │             │ │ 0 │ BROADCAST │  │        │          │         │          │          │       │ │ # │    link/ether     │        brd        │  │
│     │             │ │ 1 │ MULTICAST │  │        │          │         │          │          │       │ ├───┼───────────────────┼───────────────────┤  │
│     │             │ │ 2 │ UP        │  │        │          │         │          │          │       │ │ 0 │ --:--:--:--:--:-- │ ff:ff:ff:ff:ff:ff │  │
│     │             │ │ 3 │ LOWER_UP  │  │        │          │         │          │          │       │ ╰───┴───────────────────┴───────────────────╯  │
│     │             │ ╰───┴───────────╯  │        │          │         │          │          │       │                                                │
```

No, I don't get it either.

1. Open kitty. Again, this doesn't seem to work in others.
2. Make a line break in your command.
3. Enjoy the reflections.

Kitty:
```txt
❯ [


∙   [Interface Flags mtu qdisc state mode group qlen MAC];
∙   [lo [LOOPBACK UP LOWER_UP] 65536 noqueue UNKNOW DEFAULT default 1000 [
∙     [link/loopback brd]; [00:00:00:00:00:00 00:00:00:00:00:00]]] [wlp2s0 [BROADCAST MULTICAST UP LOWER_UP] 1500 mq UP DORMANT default 1000 [[link/ether brd]; [--:--:--:--:--:-- ff:ff:ff:ff:ff:ff]]]
❯

```

### Expected behavior

The Xfce Terminal analogs to the two previous examples:
```txt
╭───┬───────────┬───────────────────┬───────┬─────────┬────────┬─────────┬─────────┬──────┬───────────────────────────────────────────╮
│ # │ Interface │       Flags       │  mtu  │  qdisc  │ state  │  mode   │  group  │ qlen │                    MAC                    │
├───┼───────────┼───────────────────┼───────┼─────────┼────────┼─────────┼─────────┼──────┼───────────────────────────────────────────┤
│ 0 │ lo        │ ╭───┬──────────╮  │ ----- │ noqueue │ UNKNOW │ DEFAULT │ default │ 1000 │ ╭───┬───────────────────┬───────────────╮ │
│   │           │ │ 0 │ LOOPBACK │  │       │         │        │         │         │      │ │ # │   link/loopback   │      brd      │ │
│   │           │ │ 1 │ UP       │  │       │         │        │         │         │      │ ├───┼───────────────────┼───────────────┤ │
│   │           │ │ 2 │ LOWER_UP │  │       │         │        │         │         │      │ │ 0 │ 00:00:00:00:00:00 │ 00:00:00:00:0 │ │
│   │           │ ╰───┴──────────╯  │       │         │        │         │         │      │ │   │                   │ 0:00          │ │
│   │           │                   │       │         │        │         │         │      │ ╰───┴───────────────────┴───────────────╯ │
│ 1 │ wlp2s0    │ ╭───┬───────────╮ │ ----  │ mq      │ UP     │ DORMANT │ default │ 1000 │ ╭───┬───────────────────┬───────────────╮ │
│   │           │ │ 0 │ BROADCAST │ │       │         │        │         │         │      │ │ # │    link/ether     │      brd      │ │
│   │           │ │ 1 │ MULTICAST │ │       │         │        │         │         │      │ ├───┼───────────────────┼───────────────┤ │
│   │           │ │ 2 │ UP        │ │       │         │        │         │         │      │ │ 0 │ --:--:--:--:--:-- │ ff:ff:ff:ff:f │ │
│   │           │ │ 3 │ LOWER_UP  │ │       │         │        │         │         │      │ │   │                   │ f:ff          │ │
│   │           │ ╰───┴───────────╯ │       │         │        │         │         │      │ ╰───┴───────────────────┴───────────────╯ │
╰───┴───────────┴───────────────────┴───────┴─────────┴────────┴─────────┴─────────┴──────┴───────────────────────────────────────────╯
```

```txt
❯ [
∙   [Interface Flags mtu qdisc state mode group qlen MAC];
∙   [lo [LOOPBACK UP LOWER_UP] 65536 noqueue UNKNOW DEFAULT default 1000 [[link/loopback brd]; [00:00:00:00:00:00 00:00:00:00:00:00]]]]
```

### Configuration

`version | transpose key value | to md --pretty`
| key                | value                               |
| --- | --- |
| branch             |                                     |
| commit_hash        |                                     |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| build_rust_channel | release                             |
| features           | default, zip                        |
| build_rust_channel | release                             |
| features           | default, zip                        |
| installed_plugins  |                                     |

**Comment by amtoine** [comment]
i'm not able to reproduce this in `kitty` when i run the `sys` command :open_mouth: 

i have almost latest `nushell`
| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.79.1                                         |
| branch             | main                                           |
| commit_hash        | 35c84854428f4c2771bb6570cf806e7c09214bbc       |
| build_os           | linux-x86_64                                   |
| build_target       | x86_64-unknown-linux-gnu                       |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)            |
| rust_channel       | 1.67.1-x86_64-unknown-linux-gnu                |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)            |
| build_time         | 2023-04-28 09:22:51 +02:00                     |
| build_rust_channel | release                                        |
| features           | default, zip                                   |
| installed_plugins  | gstat, query, query json, query web, query xml |

and i have `kitty 0.27.1 created by Kovid Goyal` installed, maybe it's too old?

**Comment by darkwater4213** [comment]
I updated Kitty a few days ago and used `cargo` to install `nu`, so neither are out of date.

I do have more information, though: I was using `nvim` inside Kitty and the same “mirroring” behavior occurred in AstroNVim’s terminal. My best guess now is that it is a bug with Kitty and how it interacts with programs that refresh the whole terminal each frame. I was using Bash, not Nu, so this likely isn’t a problem with nushell.

I’m closing this for now.
