### ISSUE TITLE
nushell infers wrong type for variadic parameters during parse/verification phase

### ISSUE THREAD

**Issue by kai-tub** [nushell/nushell#9058]
### Describe the bug

I think nushell infers the wrong type for variadic parameters and fails to parse if type-hints are used.

### How to reproduce

```
# If list<string> is used, it doesn't work
# if any is used, it works and shows output: list<any>
def buggy_callee [
	inp_strings: any
	# inp_strings: list<string>
	# inp_strings: list<any>

] {
	$inp_strings | describe
}

export def "trigger-bug" [
	...inp_strings: string
] {
	buggy_callee $inp_strings
}
```

### Expected behavior

To successfully parse the above code either when `list<string>` or `list<any>` is used.

### Screenshots

![image](https://user-images.githubusercontent.com/46302524/235320178-a0069a67-b963-4a61-a5c2-077752349e17.png)

### Configuration

NixOS unstable:

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.79.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27) (built from a source tarball) |
| cargo_version      | cargo 1.68.1                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

### Additional context

If this turns out to be a 'good-first-issue' I would also like to take a stab at it, if somebody has the patience for me to get up and running with the code :)

**Comment by amtoine** [comment]
> If this turns out to be a 'good-first-issue' I would also like to take a stab at it, if somebody has the patience for me to get up and running with the code :)
>
i do not know if that is a `good-first-issue` as it touches the type system :thinking: 
but you can sure have a try at it :yum:

**Comment by sholderbach** [comment]
With the stricter typechecking by default this seems to have resurfaced as #9809 #9720
