### ISSUE TITLE
Unhelpful error: variable not found

### ISSUE THREAD

**Issue by bobhy** [nushell/nushell#9067]
### Describe the bug

Seems error is pointing at the wrong problem (and not clear about that, either).

### How to reproduce

```
〉77 | do {|x| 100 + $in }
177
〉77 | do {|x| 100 + $in + $x }
Error: nu::shell::variable_not_found

  × Variable not found
   ╭─[entry #21:1:1]
 1 │ 77 | do {|x| 100 + $in + $x }
   ·              ───────┬──────
   ·                     ╰── variable not found
   ╰────

〉77 | do {|x| 100 + $in + $x } 22
199
```

### Expected behavior

I think a better error would be "missing positional argument"
```
〉77 | do {|x| 100 + $in + $x }

  × Missing positional argument
   ╭─[entry #21:1:1]
 1 │ 77 | do {|x| 100 + $in + $x }
   ·          ─┬─
   ·           ╰── parameter defined here
   ╰────
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.79.1                                   |
| branch             | help_help                                |
| commit_hash        | 0e07c2c70909df961fc4fa30238d2218a4b14238 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)      |
| rust_channel       | 1.67.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)      |
| build_time         | 2023-04-27 17:50:13 -04:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by amtoine** [comment]
that sounds like a bug :open_mouth: 

also the error is better with
```
> 77 | do {|x| 100 + $x }
Error: nu::shell::variable_not_found

  × Variable not found
   ╭─[entry #4:1:1]
 1 │ 77 | do {|x| 100 + $x }
   ·                    ─┬
   ·                     ╰── variable not found
   ╰────
```

**Comment by weirdan** [comment]
It now reports 

```console
$ 77 | do {|x| 100 + $in + $x }
Error: nu::shell::missing_parameter

  × Missing parameter: x.
   ╭─[entry #51:1:6]
 1 │ 77 | do {|x| 100 + $in + $x }
   ·      ─┬
   ·       ╰── missing parameter: x
   ╰────
```

which looks sufficient.

**Comment by bobhy** [comment]
Agree, error is now reasonable, closing.
