### ISSUE TITLE
Trailing colon is shown for arguments in auto generated help when there is no documenting comment provided

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [nushell/nushell#9076]
### Describe the bug

Reproduced for required arguments, optional arguments, arguments with default value, optional arguments with default value.

### How to reproduce

1. Create `test.nu` with the following content:

```nu
# Create a new 2D point.
def new-point [
    x: int = 0,
    y: int = 0
] {
    {x: $x, y: $y}
}

new-point -h
```

2. Run `nu test.nu` and obtain:

```
Create a new 2D point.

Usage:
  > new-point (x) (y) 

Flags:
  -h, --help - Display the help message for this command

Parameters:
  (optional) x <int>: 
  (optional) y <int>:
```

### Expected behavior

One of two possible cases expected:

- No trailing colon for parameters without documentation

```Create a new 2D point.

Usage:
  > new-point (x) (y) 

Flags:
  -h, --help - Display the help message for this command

Parameters:
  (optional) x <int>
  (optional) y <int>
```

- Default documentation string like `undocumented` shown for such parameters

```Create a new 2D point.

Usage:
  > new-point (x) (y) 

Flags:
  -h, --help - Display the help message for this command

Parameters:
  (optional) x <int>: undocumented
  (optional) y <int>: undocumented
```

As more than one solution exist, there are two suggestions I can provide:

- allow user to customize this behavior via some variable or config file
- stick to the preferred case without customization allowed

### Screenshots

![image](https://user-images.githubusercontent.com/42812113/235452109-5192df33-b8c4-4122-8d01-e9e16a435d3c.png)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.79.0                                   |
| branch             |                                          |
| commit_hash        | a1b72611215dbfca257351003204a80c83859e05 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-04-25 20:26:29 +00:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by amtoine** [comment]
@EmilySeville7cfg :wave: 

i've seen this on all empty documentation, that's 100% true :+1: 

i'd opt for either no `:` or something like undocumented as you propose.
i'm just wondering if that's a bug or just an empty documentation and a missing feature :thinking:

**Comment by sholderbach** [comment]
I am not sure when this has been changed but now you get for your example:
```
Create a new 2D point.

Usage:
  > new-point (x) (y)

Flags:
  -h, --help - Display the help message for this command

Parameters:
  x <int>:  (optional, default: 0)
  y <int>:  (optional, default: 0)

Input/output types:
  ╭───┬───────┬────────╮
  │ # │ input │ output │
  ├───┼───────┼────────┤
  │ 0 │ any   │ any    │
  ╰───┴───────┴────────╯
```

But without the default values it still generates the trailing colon:

```
Create a new 2D point.

Usage:
  > new-point <x> <y>

Flags:
  -h, --help - Display the help message for this command

Parameters:
  x <int>:
  y <int>: 

Input/output types:
  ╭───┬───────┬────────╮
  │ # │ input │ output │
  ├───┼───────┼────────┤
  │ 0 │ any   │ any    │
  ╰───┴───────┴────────╯

```
