### ISSUE TITLE
$in is nothing and null (and apparently not nothing) at the same time when not piping in any data

### ISSUE THREAD

**Issue by D3V1LC0D3R** [nushell/nushell#9092]
### Describe the bug

As described in the title $in behaves unexpectedly when not piping in data. `describe` says its "nothing", yet $in == nothing is false and $in == null is true.

### How to reproduce

1. define a function, lets call it "weird"
```
def weird [] {
  print $"In is: ($in |describe)" $"In is nothing: ($in == nothing)" $"In is null: ($in == null)"
}
```

2. call weird

### Expected behavior

I expect $in == nothing and $in != null (or $in == null depending how null and nothing correlate).

### Configuration

| key                | value                                   |
| ------------------ | --------------------------------------- |
| version            | 0.78.0                                  |
| branch             |                                         |
| commit_hash        |                                         |
| build_os           | linux-x86_64                            |
| build_target       | x86_64-unknown-linux-gnu                |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)     |
| rust_channel       | stable-x86_64-unknown-linux-gnu         |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)     |
| build_time         | 2023-04-17 20:38:33 +02:00              |
| build_rust_channel | release                                 |
| features           | default, zip                            |
| installed_plugins  | query, query json, query web, query xml |

**Comment by fdncred** [comment]
"nothing" is not a thing. it's `$nothing`, but "null" is a thing and they are equivalent.
![image](https://user-images.githubusercontent.com/343840/236012435-2c97ef27-93aa-40d7-9482-c9cb7a745bc6.png)

**Comment by D3V1LC0D3R** [comment]
> "nothing" is not a thing. it's `$nothing`, but "null" is a thing and they are equivalent. ![image](https://user-images.githubusercontent.com/343840/236012435-2c97ef27-93aa-40d7-9482-c9cb7a745bc6.png)

have you tried calling weird without piping anything into it?

**Comment by D3V1LC0D3R** [comment]
![Screenshot](https://user-images.githubusercontent.com/84460014/236013093-9fa38b2e-c9cd-4163-908e-21d101183db5.png)

**Comment by fdncred** [comment]
it returns the same results. `$in` is apparently always being set.

**Comment by D3V1LC0D3R** [comment]
wait why do we have different results?

**Comment by D3V1LC0D3R** [comment]
I just updated:
| key                | value                                   |
| ------------------ | --------------------------------------- |
| version            | 0.79.0                                  |
| branch             |                                         |
| commit_hash        |                                         |
| build_os           | linux-x86_64                            |
| build_target       | x86_64-unknown-linux-gnu                |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)     |
| rust_channel       | stable-x86_64-unknown-linux-gnu         |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)     |
| build_time         | 2023-05-03 20:31:14 +02:00              |
| build_rust_channel | release                                 |
| features           | default, zip                            |
| installed_plugins  | query, query json, query web, query xml |

**Comment by D3V1LC0D3R** [comment]
is this a linux bug (something with /dev/stdin or something)?

**Comment by D3V1LC0D3R** [comment]
![image](https://user-images.githubusercontent.com/84460014/236014340-41546828-16ea-4ba7-9aaf-b651af87c4dc.png)

**Comment by D3V1LC0D3R** [comment]
or do i just not understand what nothing, $nothing and null are here?

**Comment by fdncred** [comment]
I tried to say this before, `nothing` is invalid. you need to change your script to `$in == $nothing`. that's the difference.

**Comment by D3V1LC0D3R** [comment]
> I tried to say this before, `nothing` is invalid. you need to change your script to `$in == $nothing`. that's the difference.

why does `nothing` not throw me an error here if that is invalid?

**Comment by D3V1LC0D3R** [comment]
I'm sorry i misunderstood how nushell works. I thought it throws an error when something is undefined, how ever you can do stuff like `null == DoesNotExist`

**Comment by fdncred** [comment]
> why does nothing not throw me an error here if that is invalid?

what you had is a valid statement, but invalid in the sense of what you were trying to do.

`$in == nothing` is saying `$in equal to the bare word/string nothing` - which a person may want to do that but what you were really trying to do is check to see if `$in is equal to the nushell Value::Nothing` which is what `$nothing` and `null` are.
