### ISSUE TITLE
Issue compiling nu

### ISSUE THREAD

**Issue by Minemobs** [nushell/nushell#9096]
### Describe the bug

When I try to install nushell using cargo install it crashes when it tries to compile `nu-cli`.
[Logs](https://paste.gg/p/anonymous/03fb2b3f974f4fbdb6da88df95270646)
I'm running the command as root.

### How to reproduce

1. run `cargo install nu --features=dataframe`
2. wait until you see `Compiling nu-cli 0.79.0`
3. It should crash with an error saying that `cc` got SIGKILL

### Expected behavior

I expected nu to compile.

### Configuration

I can't run nushell so I'll be using neofetch's output.
| OS | Kernel | CPU | Memory | Cargo version |
|--------|--------|--------|--------|--------|
| Ubuntu 22.04.2 LTS x86_64 | 3.10.0-1160.53.1.vz7.185.3 | Intel Xeon E5-2620 v4 (8) @ 1.727GHz | 16GiB | 1.69.0 | 

### Additional context

Somehow I was able to compile it on another ubuntu installation but I can't remember which package allowed me to compile it as I have more than 2 thousands packages, and installing it on Arch also worked so I don't really know what's happening here.

**Comment by Minemobs** [comment]
I got it to compile by cloning the repo and running `cargo build --release --workspace; cargo run --release`

**Comment by fdncred** [comment]
if you want dataframes you can also do what I do, which is, `cargo install --path . --features=dataframe` from the cloned repo.
