### ISSUE TITLE
Highlights `find` matches not just in records

### ISSUE THREAD

**Issue by juanPabloMiceli** [nushell/nushell#9105]
### Related problem

When using `find`, the match is only highlighted if the result comes from a record.
![image](https://user-images.githubusercontent.com/48705702/236399018-b84e05f3-7293-4d32-b4d6-b884947e6663.png)

### Describe the solution you'd like

I think we should highlight at least strings and lists (maybe I am missing another Value), I gave a quick look at the code and believe it shouldn't be to hard to add this feature (citation needed).

**Comment by fdncred** [comment]
ya, i really wrote it for tables only. it would be nice if someone picked it up and added it to --regex, lists, etc.

**Comment by avthakore** [comment]
Hi! 

I would love to take it up as a first issue. I have just graduated and would love to start with open source. I would also appreciate some guidance! I will give this an honest effort though.

**Comment by amtoine** [comment]
@avthakore 
that's amazing :partying_face: 
thanks for considering Nushell for your first try :blush:
