### ISSUE TITLE
let-env EDITOR on Windows

### ISSUE THREAD

**Issue by KDGundermann** [nushell/nushell#9106]
### Describe the bug

setting `let-env EDITOR` with a full path on Windows fails to open the editor

### How to reproduce

```
c:\Program Files\nu\bin> let-env EDITOR = "C:\Program Files (x86)\Notepad++\notepad++.exe"        
Error:
  × Invalid literal
   ╭─[entry #28:1:1]
 1 │ let-env EDITOR = "C:\Program Files (x86)\Notepad++\notepad++.exe"
   ·                     ──────────────────────┬──────────────────────
   ·                                           ╰── unrecognized escape after '\' in string
   ╰────
```
```
c:\Program Files\nu\bin> let-env EDITOR = "C:\\\Program Files (x86)\\\Notepad++\\\notepad++.exe"     
```
```
c:\Program Files\nu\bin> config env                                                                  
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #30:1:1]
 1 │ config env
   · ─────┬────
   ·      ╰── executable 'C:\Program' was not found
   ╰────
  help: Das System kann die angegebene Datei nicht finden. (os error 2)
```

### Expected behavior

setting the `EDITOR` environment var should allow to use paths with blanks on Windows

### Configuration

| key                | value                                          |
| ------------------ | ---------------------------------------------- |
| version            | 0.79.0                                         |
| branch             |                                                |
| commit_hash        | a1b72611215dbfca257351003204a80c83859e05       |
| build_os           | windows-x86_64                                 |
| build_target       | x86_64-pc-windows-msvc                         |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)            |
| rust_channel       | 1.66.1-x86_64-pc-windows-msvc                  |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)            |
| build_time         | 2023-04-25 20:27:05 +00:00                     |
| build_rust_channel | release                                        |
| features           | default, zip                                   |
| installed_plugins  | gstat, query, query json, query web, query xml |
c:\Program Files\nu\bin>

**Comment by amtoine** [comment]
@KDGundermann, this reminds me of something on windows :smirk: 

could you please try with backticks instead?
e.g.
```
let-env EDITOR = `C:\Program Files (x86)\Notepad++\notepad++.exe`
```

and also, quite naive but might be worth checking, is this `.exe` there and executable without `EDITOR`, as a standalone call to it? :yum:

**Comment by KDGundermann** [comment]
> could you please try with backticks instead? e.g.

No, neither with backticks, single-ticks oder doublequotes

>  but might be worth checking, is this .exe there and executable without EDITOR, as a standalone call to it?

Yes, I can start notepadd++ using backticks (and even single backslashes)

**Comment by amtoine** [comment]
mm that reminds me of another issue about the same problem we had in the discord :thinking: 

there is a workaround with a "short form" of Windows paths, what is it again @fdncred? :yum:

**Comment by fdncred** [comment]
You can do `dir /x` on windows to see the short path. It's like PROGRA~2

**Comment by sholderbach** [comment]
This is a duplicate of #8714 and not platform specific (only obvious under Windows)

With #8105 and https://github.com/nushell/reedline/pull/544 we regressed here in the attempt to support flags as part of the `EDITOR` variable.

We need to square spaces in the filename of the `EDITOR` variable with the desire for flags as opined in #8051

**Comment by fdncred** [comment]
For anyone looking for a work-around, you can do this to figure out what your short path is.
```
cmd /c dir /x c:\
 Volume in drive C is Windows
 Volume Serial Number is 0000-0000

 Directory of c:\

10/19/2022  07:52 PM           112,104 APPVER~1.DLL appverifUI.dll
04/27/2023  04:29 PM    <DIR>                       CarTar
01/21/2022  03:31 PM    <DIR>                       Data
04/08/2022  01:19 PM            12,288 DUMPST~1.LOG DumpStack.log
05/01/2023  07:24 AM    <DIR>          PROGRA~1     Program Files
02/27/2023  04:52 PM    <DIR>          PROGRA~2     Program Files (x86)
07/14/2020  01:52 PM    <DIR>                       Py
08/16/2021  07:18 AM    <DIR>          QUARAN~1     QUARANTINE
10/07/2020  03:18 PM    <DIR>                       src
01/24/2023  02:57 PM    <DIR>          SYMBOL~1     SymbolCache
05/10/2023  08:20 AM    <DIR>                       Temp
03/09/2023  04:25 PM    <DIR>                       tmp
10/05/2022  09:46 AM    <DIR>                       Users
10/19/2022  07:52 PM            66,176              vfcompat.dll
05/04/2023  01:50 PM    <DIR>                       Windows
01/06/2022  06:49 PM    <DIR>          WSLDIS~1     wslDistros
```
Then you can do something like this for your editor.
```
let-env EDITOR = C:\PROGRA~1\Notepad2\Notepad2.exe
```
and then this command works with that editor
```
config nu
```

**Comment by sholderbach** [comment]
I think we should revert the changes and go for the alternative route proposed in #8051 and accept a list for the rarer occasion that you want to pass flag to the editor. The downside would be that this is not directly compatible with the POSIX `EDITOR` and `VISUAL` variables. We could restrict those that want to use a list for flags to use `$config.buffer_editor`.

**Comment by fdncred** [comment]
> I think we should revert the changes ...

If we're going to do that, which I support, we should probably do it before the next release in 6 days. But I'd rather have it work the same way on all platforms, just so we don't have to say, "you people do it this way. you other people do it that way". I'm not familiar with how EDITOR and VISUAL work on POSIX systems, I'm assuming they use `eval` or some such thing to provide arguments to the editor.

It may be that the least common denominator is to only allow executables and paths to executables and no parameters?

**Comment by KDGundermann** [comment]
> You can do `dir /x` on windows to see the short path. It's like PROGRA~2

Short 8.3 filenames is an old reminisence of days before WIndows 95 [see Wikipedia](https://en.wikipedia.org/wiki/8.3_filename) and they are disabled on our computers ...

**Comment by KDGundermann** [comment]
> if that's a duplicate of #8714, should we close this one? 😋

Yes, it is a duplicate. Sorry about that.

**Comment by fdncred** [comment]
> Short 8.3 filenames is an old reminisence of days before WIndows 95 [see Wikipedia](https://en.wikipedia.org/wiki/8.3_filename)  ...

clearly.

it's too bad it's disabled on your computer because it's a good work-around for now.
