### ISSUE TITLE
`--help` won't work for alias defined before function in a module

### ISSUE THREAD

**Issue by mksinicus** [nushell/nushell#9114]
### Describe the bug

In a module file, I put shorthand aliases before definitions of the functions they point to. It works, but the `--help (-h)` flag won't work, yielding a "nu::parser::unknown_flag" error.

### How to reproduce

```sh
> cat mod.nu
export alias f = foo

export def foo [] {
  echo bar
}
> use mod.nu
> mod f
bar
> mod f --help
Error: nu::parser::unknown_flag

  × The `foo` command doesn't have flag `help`.
   ╭─[entry #26:1:1]
 1 │ mod f --help
   ·       ───┬──
   ·          ╰── unknown flag
   ╰────
  help: Available flags. Use `--help` for more information.
```

`-h` would give the same error.

### Expected behavior

I wonder if it is intended behavior, but since the error message tells me to use `--help`, I suppose it isn't. 

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.79.0                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.68.1 (8460ca823 2023-03-20)                                             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                                                 |
| cargo_version      | cargo 1.68.1 (115f34552 2023-02-26)                                             |
| build_time         | 2023-04-27 06:27:42 +08:00                                                      |
| build_rust_channel | release                                                                         |
| features           | default, zip                                                                    |
| installed_plugins  | from eml, from ics, from ini, from vcf, query, query json, query web, query xml |

### Additional context

In REPL, an alias defined before its target simply doesn't work.

**Comment by amtoine** [comment]
reproduced with
```bash
module mod {
    export alias f = foo

    export def foo [] {
        echo bar
    }
}
```
and fixed with, as implied by OP
```bash
module mod {
    export def foo [] {
        echo bar
    }

    export alias f = foo
}
```

**Comment by mksinicus** [comment]
Not a problem any more with <https://github.com/nushell/nushell/pull/9244>. Thanks!

**Comment by amtoine** [comment]
coool :yum:
