### ISSUE TITLE
Recursive `ls` in script results in `nu::parser::extra_positional` error.

### ISSUE THREAD

**Issue by siph** [nushell/nushell#9124]
### Describe the bug

Recursive `ls` in script results in `nu::parser::extra_positional` error.

### How to reproduce

With the given file/folder structure:
```shell
─ foo
├── ─ bar
│   ├── five
│   └── four
├── ─ baz
│   ├── seven
│   └── six
├── one
├── three
└── two
```

Running the command `ls /foo/**/*` prints out the structure:
```shell
╭───┬────────────────┬──────┬────────┬───────────────╮
│ # │     name       │ type │  size  │   modified    │
├───┼────────────────┼──────┼────────┼───────────────┤
│ 0 │ /foo/bar       │ dir  │ 4.1 KB │ 5 minutes ago │
│ 1 │ /foo/bar/five  │ file │    0 B │ 5 minutes ago │
│ 2 │ /foo/bar/four  │ file │    0 B │ 5 minutes ago │
│ 3 │ /foo/baz       │ dir  │ 4.1 KB │ 5 minutes ago │
│ 4 │ /foo/baz/seven │ file │    0 B │ 5 minutes ago │
│ 5 │ /foo/baz/six   │ file │    0 B │ 5 minutes ago │
│ 6 │ /foo/one       │ file │    0 B │ 5 minutes ago │
│ 7 │ /foo/three     │ file │    0 B │ 5 minutes ago │
│ 8 │ /foo/two       │ file │    0 B │ 5 minutes ago │
├───┼────────────────┼──────┼────────┼───────────────┤
│ # │     name       │ type │  size  │   modified    │
╰───┴────────────────┴──────┴────────┴───────────────╯
```

However, using this in a script:
```nu
# test.nu

#!/usr/bin/env nu

def main [dir] {
    ls $dir
}
```

And running `nu test.nu /foo/**/*` (and other variants) results in an error:
```shell
Error: nu::parser::extra_positional

  × Extra positional argument.
   ╭─[<commandline>:1:1]
 1 │ main bar bar/five bar/four baz baz/seven baz/six one three two
   ·          ────┬───
   ·              ╰── extra positional argument
   ╰────
  help: Usage: main <dir>
```

### Expected behavior

Behavior should probably be consistent between the command line and a script.

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.79.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) (built from a source tarball) |
| cargo_version      | cargo 1.69.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

**Comment by jntrnr** [comment]
Calling nu add an external will automatically expand the glob for you.

**Comment by siph** [comment]
I don't totally understand. I'm trying to make a script optionally recursive by passing in the pattern. Is this not intended to be possible?

**Comment by WindSoilder** [comment]
Yeah, when you run the script, nu is run as external command, so it automatically expand the glob, to opt-out the auto expand, you can wrap `/foo/**/*` with quote, like `'/foo/**/*'`

**Comment by WindSoilder** [comment]
Since it's work as expected, I'd close the issue, feel free to re-open it if you still have issue
