### ISSUE TITLE
Path completion should use forward slashes on Windows

### ISSUE THREAD

**Issue by melMass** [nushell/nushell#9127]
### Related problem

Currently, on Windows, tab completion for paths uses the backslash (`\`) as the path separator. However, nowadays, forward slashes (`/`) are more widely supported on Windows, and it would be great if nushell could update its tab completion feature to use forward slashes instead.

Using forward slashes as the path separator makes working with paths in a cross-platform environment much easier. Many tools and libraries already use forward slashes as the path separator and from experience / is always supported, not \

While Windows traditionally used the backslash as the path separator, many modern Windows APIs and tools support forward slashes, and it is becoming increasingly common to see forward slashes used in paths in Windows-based applications.

### Describe the solution you'd like

Tab complete with forward slash, or, but the effort might not worth it, complete using the currently used flavor:
- `./path/to` **press tab** `./path/to/a`
- `.\path\to` **press tab** `.\path\to\a`

### Describe alternatives you've considered

Ignoring this completely. While it's been an annoyance I'm used to `str replace -a '\' '/'` in most of my scripts

### Additional context and details

💌

**Comment by fdncred** [comment]
I think we could try this although I'm not sure if it's a reedline change or a nushell change. Also, IIRC, the reason Windows went with `\` as the path separator was so they could use `/` as flags like `cmd /d`. So, if we do change to use `/` as the windows path separator, we'll need to make sure it's always quoted so it doesn't get confused with parameters.

One other thing this will fix is the double quote on windows seeing `c:\blah` as an escape.

**Comment by melMass** [comment]
Duplicate of #7044
Closing in favor

**Comment by eevleevs** [comment]
#7044 does not help when the first slash is inserted by autocompletion, please reconsider.
