### ISSUE TITLE
duplicated input in explore

### ISSUE THREAD

**Issue by PizzaKirby** [nushell/nushell#9128]
### Describe the bug

Whenever I press a key in explore the character is inserted twice. (see attachment)

### How to reproduce

1. `explore`
2. type anything

### Expected behavior

I expected there to only be one character per keypress.

### Screenshots

[explore.webm](https://user-images.githubusercontent.com/13819824/236684406-7d3933cf-90ef-41b5-8317-2e89f7bc01c5.webm)

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.79.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | windows-x86_64                      |
| build_target       | x86_64-pc-windows-msvc              |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) |
| rust_channel       | stable-x86_64-pc-windows-msvc       |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12) |
| build_time         | 2023-04-26 18:18:07 +02:00          |
| build_rust_channel | release                             |
| features           | default, zip                        |
| installed_plugins  |                                     |

### Additional context

I am using Windows Terminal 1.16.10261.0

**Comment by fdncred** [comment]
I can't reproduce this. Although I've seen the exact problem with the latest crossterm somewhere else.

**Comment by fdncred** [comment]
@zhiburt Yup, this is a problem only on windows. Can you please help us fix it? I found this issue in the crossterm repo https://github.com/crossterm-rs/crossterm/issues/772
