### ISSUE TITLE
The order of fields loaded via `from yaml` should be stable

### ISSUE THREAD

**Issue by fj0r** [nushell/nushell#9148]
### Related problem

The order of fields loaded via `from yaml` is unstable,Repeat the following commands, the results may vary
```
$'a: 1(char newline)b: 2(char newline)c: 3' | from yaml
```
This is not friendly to version control systems or `diff`.

I can use `yq -o=json | from json` to solve, but this solution introduces an external tool `yq`.

### Describe the solution you'd like

The order of fields loaded via `from yaml` should be stable

### Describe alternatives you've considered

```
yq -o=json | from json
```

**Comment by fdncred** [comment]
I'd guess this is because of the yaml crate we're using but I'm not sure. Feel free to look into it.

**Comment by fdncred** [comment]
By my reading, it looks like we'd need to deserialize into an indexmap or btreemap

https://github.com/dtolnay/serde-yaml/issues/232
https://www.reddit.com/r/rust/comments/rrizq5/is_serdejson_serialization_deterministic/
https://github.com/dtolnay/serde-yaml/issues/221
https://github.com/dtolnay/serde-yaml/pull/222#pullrequestreview-1033573084

**Comment by WindSoilder** [comment]
It's already fixed by https://github.com/nushell/nushell/pull/9155
Feel free to reoepn it if you still meet the issue
