### ISSUE TITLE
Issue with `into binary`

### ISSUE THREAD

**Issue by herobs** [nushell/nushell#9156]
### Describe the bug

The `into binary` fill the high bits first, leaving low bits with zeros. Is this behavior intended?

### How to reproduce

```bash
1 | into binary | into int
```
Output
```
72057594037927936
```

### Expected behavior

1

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.79.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-x86_64                                                      |
| build_target       | x86_64-apple-darwin                                               |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27) (built from a source tarball) |
| cargo_version      | cargo 1.68.1 (6feb7c9cf 2023-03-26)                               |
| build_time         | 2023-04-25 20:06:17 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
This is because when 1 is converted to binary there are 8 bytes. One way around this is to do something like this.
```
1 | into binary | bytes at 0..1 | into int
```

We'd probably be open to `into binary` working differently.

**Comment by herobs** [comment]
It should be the same when converted back, in my opinion.

**Comment by amtoine** [comment]
@herobs 
i think the issue here is the endianness of the `into binary` conversion :open_mouth: 

if you do
```
use std "assert equal"
```
```
assert equal (1 | into binary | into int) 1
```
gives an error but
```
assert equal (1 | into binary | bytes reverse | into int) 1
```
does not :yum:

**Comment by herobs** [comment]
There is an inconsistent endianness behavior between the `into binary` and `into int`.

`into binary` outputs in big-endian, but `into int` expects the input in little-endian.

**Comment by herobs** [comment]
A flag should be added to specify the endianness. The default value of the flag should keep the behavior consistent.

**Comment by fdncred** [comment]
I believe `into binary` detects endianness and uses it
https://github.com/nushell/nushell/blob/39e51f1953fd3f4bd39158af92c2fd8d74bd9673/crates/nu-command/src/conversions/into/binary.rs#L141-L156
It looks like `into int` has a switch for byte order.
We also use `to_ne_bytes()` in a couple other places. I think `to_ne_bytes()` is equivalent to what we're doing in `into binary` so maybe `into int` should switch so we're consistent? Either that or `into int` and `into binary` should have a toggle switch to toggle to the opposite of their native endianness.

**Comment by herobs** [comment]
Indeed there is a toggle for `into int`. We can get the correct result back with `--little-endian`. And using the network endian should be a good idea.

BTW, there is another nuance problem with `into binary`: the result will be padded with zeros if the length of the bytes is less than 8. This is ok in common circumstances but not expected in encoding.

For example,
```bash
0x[ab cd ef] | encode base64
```
Output `q83v`
```base
0xabcdef | into binary | bytes reverse | encode base64
```
Output `AAAAAACrze8=` because of the leading zeros.

**Comment by herobs** [comment]
@fdncred The toggle flag should belong to `into binary` to decide output endianness.

**Comment by fdncred** [comment]
feel free to submit a PR to straighten out this stuff

**Comment by herobs** [comment]
It's a challenge for a newcomer in Rust. I'll try to fix the followings:
- Move the toggle flag from `into int` to `into binary`
- Fix the length problem when the output is less than 8 bytes.
