### ISSUE TITLE
Add support for Command Processor 

### ISSUE THREAD

**Issue by guilt** [nushell/nushell#9157]
### Related problem

This is a Windows Specific request.

For Windows, I make use of the *Command Processor* feature to literally add a ton of stuff I need, without polluting the Environment Variables Tab. Example in [guilt/CMD](https://github.com/guilt/CMD). Most modern people may use **PowerShell** with `Microsoft.PowerShell_profile.ps1` or something similar.

Until I transition completely into **nu** I'd prefer to launch as a sub-shell. 

How serious is it? `config env` doesn't even work for me because the `EDITOR` variable isn't set by default. But when launched as a sub-process, I'm able to change everything quickly and retain my existing setup.

### Describe the solution you'd like

I wish to launch nu from Windows Terminal as a subshell of CMD (Or PowerShell) so that all my environment configuration (fairly large) can be inherited, allowing me to use a variety of command line tools. Is there a way to make that happen?

So, it's simple as executing as `cmd /C nu`, but the configuration comes from `$nu.config-path`. That way, settings like `VISUAL`, `PAGER` and `EDITOR` work as the user has configured it.

So, if there's a Nu-Shell configuration like: `launch-subshell-of`, I'd like the profile to honor it and exec within another shell.

### Describe alternatives you've considered

I've considered adding this as a custom Windows Profile (like Git CMD/Git Bash) but the idea is to make it easy defaults, out of the box. I can also manually run `nu` in `cmd` so that it inherits the variable. This is a request to figure out how to make it easy for existing users so they can start adopting it more. Perhaps documenting this in itself could be helpful.

![Windows Terminal Changes](https://github.com/nushell/nushell/assets/195178/0e12f5db-f3d9-4771-ab03-a540951505d7)

Git, for instance allows one to create a shortcut for 'Git Bash' or 'Git CMD' to alleviate this problem. Something similar could be helpful in the installer.

### Additional context and details

-N/A-

**Comment by fdncred** [comment]
I'm not sure we'd be open to your autoexec.cmd and registry changes solution. I develop in nushell nearly every day and my windows terminal launches into pwsh and i type nu. Seems like you've got something figured out with your `cmd /c nu.exe` that is working for you.

**Comment by guilt** [comment]
To clarify, I am not asking anyone to adopt my setup.

 The idea to run as a subshell is to enable nushell to re-use system configured defaults. Having an option to integrate with existing shells was the ask here. If this sounds like it's unnecessary (it may), let this ticket remain as documentation.

**Comment by sholderbach** [comment]
I also struggle to understand from your description where the limitation on nushell's side should be to use the external environment.

I can invoke `nu` from `cmd.exe`'s repl and get the `PATH`/`Path` set from the outside windows environment.
![grafik](https://github.com/nushell/nushell/assets/15833959/4634ddb2-c71e-4c51-8736-2eedb16c4620)
Also the rest of the environment also seems to be populated
![grafik](https://github.com/nushell/nushell/assets/15833959/7be9f0ab-254c-46b3-89b9-c21180831d36)

**Comment by guilt** [comment]
This is just from Windows Terminal. When you click on open new session > select nu, it is a vanilla nu shell. 

If someone were using the command processor like me, or a PowerShell profile, they manually have to launch nu, like you did. The feature request is to make this seamless, eliminate the extra step.

This usually comes to asking if the user wants to launch a new profile as standalone, or to integrate with the environment variables from existing shells such as CMD/PowerShell.

One way to install these profiles is how Git for Windows does it:
![IMG_3255](https://github.com/nushell/nushell/assets/195178/1c154f9e-20d2-4f22-a94f-e0552ff91a85)

**Comment by guilt** [comment]
I set up nushell on a new Windows box today and this happened:

![image](https://github.com/nushell/nushell/assets/195178/a5e97de4-1301-470f-a9d7-3de17f88d5a9)

**Comment by fdncred** [comment]
> I set up nushell on a new Windows box today and this happened:

I'm not getting your point. This is what is supposed to happen when neither EDITOR, or VISUAL is set, right?

**Comment by guilt** [comment]
Yes. Apparently I did set it in my command processor. Which is one of the reasons why I opened the ticket.

On Windows, step #4 didn't happen either:
![Screenshot_20230513_103153_Firefox](https://github.com/nushell/nushell/assets/195178/3f4c9e99-d180-4eba-b37e-e2d5c96d72f3)

**Comment by fdncred** [comment]
I don't think it defaults to notepad any longer in windows. What does $env.EDITOR and $env.VISUAL say after running through your command processor?

**Comment by guilt** [comment]
After my command processor `$env.EDITOR` is set to `notepad` and `$env.VISUAL` is unset.

**Comment by fdncred** [comment]
I'm not sure how to reproduce what you're seeing. If editor is set to notepad and notepad is in your path, it should start.

**Comment by rgwood** [comment]
> For Windows, I make use of the Command Processor feature

I don't know what that is, and Googling doesn't turn up much useful info.

**Comment by rgwood** [comment]
I've read through this issue a few times and as I understand it, you want the Nushell installer to automatically create a Windows Terminal profile that launches Nu inside `cmd.exe`.

I don't think this is a common use case and it's easy for people who want this behaviour to create their own Windows Terminal profile. I don't think we should implement this.
