### ISSUE TITLE
sys | update doesn't work

### ISSUE THREAD

**Issue by ShinyZero0** [nushell/nushell#9165]
### Describe the bug

I can update e.g. config record
```cs
$env.config | update cursor_shape {$in}
```
But i can't do that with `sys` output record, see screenshot
```cs
sys | update host {$in}
```
`describe` and `columns` work as intended so it's not that thing with raw output from subshell

### How to reproduce

Try to `update` a `sys` output

### Expected behavior

To output an updated record

### Screenshots

![Screenshot_2023-05-11-08-11-28-56](https://github.com/nushell/nushell/assets/105050391/b5090a82-ad87-48fc-bcea-e166b5970714)

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.79.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | aarch64-linux-android               |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10) |
| rust_channel       | 1.66.1-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10) |
| build_time         | 2023-04-26 00:33:56 +00:00          |
| build_rust_channel | release                             |
| features           | default, zip                        |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
What is this supposed to do? `$env.config | update cursor_shape {$in}`. I agree that `nu` shouldn't be part of the error here `sys | update host {$in}` but I'm not sure what that command is supposed to accomplish either.

**Comment by ShinyZero0** [comment]
Actually i was editing the part of a record as nuon with `vipe` from moreutils when noticed that. `{$in}` there should just update the value with itself i.e. do nothing and it does with `$env.config`
