### ISSUE TITLE
Wrong case of history completion

### ISSUE THREAD

**Issue by ShinyZero0** [nushell/nushell#9174]
### Describe the bug

When you accept a history completion with right arrow it doesn't replace text already written in wrong case while it suggests completion case insensitively

### How to reproduce

1. Execute `$env.XDG_DATA_DIRS`
2. Type `$env.xd`
3. Accept completion with right arrow
4. `$env.xdG_DATA_DIRS`

### Expected behavior

Complete `$env.XDG_DATA_DIRS`

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.79.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) (built from a source tarball) |
| cargo_version      | cargo 1.69.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

**Comment by amtoine** [comment]
very good catch @ShinyZero0 :ok_hand:

**Comment by juanPabloMiceli** [comment]
Tried to reproduce but I don't get any completion suggestion if I use a different case :thinking: Maybe I need to enable some flag somewhere?

**Comment by amtoine** [comment]
@juanPabloMiceli
appears it's only with the SQL history :open_mouth: 

i can not reproduce with `nu -n` or `config.history.file_format = "plaintext"`, but can with `config.history.file_format = "sqlite"` :+1:

**Comment by sholderbach** [comment]
Closing as a duplicate as we have a more detailed investigation in the more recent version of this issue: https://github.com/nushell/nushell/issues/10131
