### ISSUE TITLE
Link to blog in release 0.4.0 is broken/incorrect 

### ISSUE THREAD

**Issue by jChapman** [nushell/nushell#918]
**Describe the bug**
The github release (https://github.com/nushell/nushell/releases/tag/0.4.0) contains a link which returns a 404

The bad link: http://www.jonathanturner.org/2019/10/nushell_0_4_0.html
The correct link: http://www.jonathanturner.org/2019/10/nushell-0_4_0.html

**Comment by jonathandturner** [comment]
We've fixed this with more recent releases
