### ISSUE TITLE
Some output lines are missing when scrolling up in Windows Terminal

### ISSUE THREAD

**Issue by lodezo** [nushell/nushell#9182]
### Describe the bug

When some ranges are created some values are missing and their indices as well. 

Examples:
Values 4,5,6 are missing:
❯ 2..30
╭────┬────╮
│  0 │  2 │
**│  1 │  3 │
│  5 │  7 │**
│  6 │  8 │
│  7 │  9 │
│  8 │ 10 │
│  9 │ 11 │
│ 10 │ 12 │
│ 11 │ 13 │
│ 12 │ 14 │
│ 13 │ 15 │
│ 14 │ 16 │
│ 15 │ 17 │
│ 16 │ 18 │
│ 17 │ 19 │
│ 18 │ 20 │
│ 19 │ 21 │
│ 20 │ 22 │
│ 21 │ 23 │
│ 22 │ 24 │
│ 23 │ 25 │
│ 24 │ 26 │
│ 25 │ 27 │
╰────┴────╯

Values 14,15 are missing
❯ 1..40
╭────┬────╮
│  0 │  1 │
│  1 │  2 │
│  2 │  3 │
│  3 │  4 │
│  4 │  5 │
│  5 │  6 │
│  6 │  7 │
│  7 │  8 │
│  8 │  9 │
│  9 │ 10 │
│ 10 │ 11 │
│ 11 │ 12 │
**│ 12 │ 13 │
│ 15 │ 16 │**
etc.

### How to reproduce

Execute 2..30 or 1..40 in an interactive nu shell

### Expected behavior

A range with all values between the start and end number. 

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.79.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12) |
| build_time         | 2023-05-04 00:20:19 +03:00          |
| build_rust_channel | release                             |
| features           | default, zip                        |
| installed_plugins  |                                     |

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.79.0                                   |
| branch             |                                          |
| commit_hash        | a1b72611215dbfca257351003204a80c83859e05 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.66.1 (90743e729 2023-01-10)      |
| rust_channel       | 1.66.1-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.66.1 (ad779e08b 2023-01-10)      |
| build_time         | 2023-04-25 20:27:05 +00:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by amtoine** [comment]
could this issue be related to https://github.com/nushell/nushell/issues/9166 a few hours before? :open_mouth:

**Comment by lodezo** [comment]
Thanks amtoine. Yes, I think it's related. 

Just for information: I tried some possibly related terminal settings, which didn’t have any effect on this issue:
- Changed the font 
- Use the new text renderer (“AtlasAngine”) - switch to on
- Redraw entire screen when display updates - switch to on

#6046 also seems to be related. 

I close this issue to circumvent duplicates.

**Comment by amtoine** [comment]
noice, thanks for the quick response :star_struck:
