### ISSUE TITLE
Config Editing fails on Windows 

### ISSUE THREAD

**Issue by guilt** [nushell/nushell#9189]
### Describe the bug

Per Documentation on Windows:

![Screenshot_20230513_103153_Firefox](https://github.com/nushell/nushell/assets/195178/b459452b-76bb-43a1-84ee-34367f2f00a6)

If neither VISUAL nor EDITOR is set, it should launch `notepad`. However, on a new machine, this happened.

![238106336-a5e97de4-1301-470f-a9d7-3de17f88d5a9](https://github.com/nushell/nushell/assets/195178/687933dd-d3ca-437e-9fcd-c7b5d438afe9)

### How to reproduce

1. Brand new Windows installation.
2. Use `winget install nushell`
3. Launch `nushell` and accept the suggestions to create default configuration. 
4. Type `config env`

### Expected behavior

The configuration opens in `notepad`

### Screenshots

Added inline, see above. 

### Configuration

WIP

**Comment by fdncred** [comment]
As I already mentioned in your other issue, `notepad` isn't the default any longer. See https://github.com/nushell/nushell/pull/8282. So, the documentation is out of date.

**Comment by guilt** [comment]
> As I already mentioned in your other issue, `notepad` isn't the default any longer. See #8282. So, the documentation is out of date. Feel free to submit a documentation PR on our docs repo.

https://github.com/nushell/nushell.github.io/pull/938
