### ISSUE TITLE
Change the LS_COLOUR for the type column

### ISSUE THREAD

**Issue by Adoni5** [nushell/nushell#9194]
### Question

How do I alter the colour of the type column for the `ls` command? I'm using `vivid`s lava theme.

Thanks guys!

### Additional context and details

![image](https://github.com/nushell/nushell/assets/18659347/61be074d-f0db-431c-bd6f-ea754f3cd795)

The type column is unreadable, and I can't find the corresponding LS_COLOR to set it. Is it set by some other variable?

**Comment by fdncred** [comment]
You need to adjust the theme in your config.nu. I believe type is just a shape_string. There could be a bug too. Let us know how it goes.

**Comment by Adoni5** [comment]
Thanks for the very fast reply, that's done it! Was getting a bit rabbit holed 👍🏼
