### ISSUE TITLE
starship, why is it showing 0% 

### ISSUE THREAD

**Issue by peedans** [nushell/nushell#9205]
### Question

I installed starship, why is it showing 0% on it? I don't know. I installed nerd font.
![Screenshot from 2023-05-16 10-19-39](https://github.com/nushell/nushell/assets/98443682/eca5b3cd-7902-4279-8774-2f2c9f6f5544)

**Comment by fdncred** [comment]
looks like a problem with your starship prompt

**Comment by hardfau18** [comment]
check if you have enabled battery module
