### ISSUE TITLE
Introduce a way to read user's input, similar to "read" in Bash

### ISSUE THREAD

**Issue by mrkkrp** [nushell/nushell#9208]
### Related problem

There doesn't seem to be a way to read user's input right now. My particular use case is that I want to write a menu (by "menu" I don't necessarily mean a Nushell menu, I could print it myself) where selection is performed by pressing a single character. In bash one could do:

```
$ read -n1 my_variable
```

`read` is not available in Nushell.

### Describe the solution you'd like

Several possibilities:

* Introduce a built-in command `read` analogous to `read` in other shells.
* Augment the menu system by allowing to specify a custom action to be run upon selection of an entry. This would greatly enhance what can be done with menus.

### Describe alternatives you've considered

There doesn't seem to be any reading functionality present in Nushell, or, perhaps I'm missing something.

**Comment by mrkkrp** [comment]
Thanks, `input` comes close to what I need, but it lacks a way to specify how many characters should be read (`-n1` in bash and other shells).

**Comment by fdncred** [comment]
Yup, it does not have that functionality. It's been asked for before. It wouldn't surprise me to find another issue about this here.
