### ISSUE TITLE
Pivot like Google Sheets Pivot Tables

### ISSUE THREAD

**Issue by lewisdiamond** [nushell/nushell#921]
When dealing with data sets that have many columns, one may be interested in grouping them.

Take `ls` for example
```
━━━━━┯━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┯━━━━━━━━━━━┯━━━━━━━━━━┯━━━━━━━━━━┯━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━
 #   │ name                                    │ type      │ readonly │ size     │ accessed     │ modified
─────┼─────────────────────────────────────────┼───────────┼──────────┼──────────┼──────────────┼───────────────
 1   │ a                                       │ Directory │          │   4.1 KB │ 14 hours ago │ 3 months ago
 2   │ b                                       │ Directory │          │   4.1 KB │ 14 hours ago │ a year ago
 3   │ c                                       │ File      │          │     1 KB │ 2 months ago │ 4 months ago
```

Suppose you want the sum of size by type
```
━━━━━┯━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
     │ Directory     │ File │ Total     │
─────┼─────────────────────────────────────────
 size│ 8.2 KB        │ 1 KB   │  9.2 KB      
 
``` 
Checkout Pivot tables in Google Sheet or MS Excel.

**Describe the solution you'd like**
`ls | pivot --on type --sum size --total`

**Describe alternatives you've considered**
I currently use Google Sheet for that (not for ls obviously, but various datasets)

**Comment by andrasio** [comment]
@lewisdiamond There are many ways to accomplish it. Please let me know what you are thinking.

Few examples that come up my mind:

`ls | where type == File | get size | sum` 
`ls | group-by type | get File | get size | sum`

There is a bug and doing `ls | group-by type | get File.size | sum`  that we are working on fixing.

**Comment by lewisdiamond** [comment]
I had 0.4.0 when I opened the issue, 0.5.0 released right after includes `group-by`. I'll first see what can be done with group-by (once the bug is resolved) and then I can update if there's a legitimate need for more.

One thing that, at first glance, would be missing is the ability to group in multiple levels and aggregate  multiple fields.
