### ISSUE TITLE
Function input can't assign default closure/duration/filesize/range anymore

### ISSUE THREAD

**Issue by wdv4758h** [nushell/nushell#9217]
### Describe the bug

Function input can have default closure in version 0.79. But this becomes not available in 0.80.

### How to reproduce

```nu
def f [ g = { $in } ] {}
```

Also:

```nu
def f1 [ g = 1sec ] {}
def f2 [ g = 1mb ] {}
def f3 [ g = 1..2 ] {}
```

### Expected behavior

Should be able to define a closure as default.

### Screenshots

![image](https://github.com/nushell/nushell/assets/2716047/d5114e21-3a33-40b6-af20-c71beddb7c40)

### Configuration

| key                | value                                                                                       |
| ------------------ | ------------------------------------------------------------------------------------------- |
| version            | 0.80.0                                                                                      |
| branch             | makepkg                                                                                     |
| commit_hash        | 8695b575848d5eb4d688087aa9e906b4d9e7c8d8                                                    |
| build_os           | linux-x86_64                                                                                |
| build_target       | x86_64-unknown-linux-gnu                                                                    |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) (Arch Linux rust 1:1.69.0-3)                            |
| cargo_version      | cargo 1.69.0                                                                                |
| build_time         | 2023-05-17 05:13:57 +00:00                                                                  |
| build_rust_channel | release                                                                                     |
| features           | default, zip                                                                                |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, inc, query, query json, query web, query xml |

**Comment by wdv4758h** [comment]
Here is a working screenshot with 0.79.

![image](https://github.com/nushell/nushell/assets/2716047/353e69ce-8cc5-4a47-b6e7-b68db1e497ae)

**Comment by wdv4758h** [comment]
Not sure this ability is by accident or feature. But I think it's really handy in some cases.

**Comment by amtoine** [comment]
i think the *culprit* is #8940, and it's by design that variables can not be used as default values now :+1: 

so `def f [ g = { $in } ] {}` is expected to fail, because `{ $in }` is not a constant.

however, and i've seen this today too in an unrelated context, `1sec`, `1mb` and `1..2` look like constants to me and thus should work imo :yum:

**Comment by fdncred** [comment]
good point @amtoine. @MariaSolOs any ideas how to have better defaults now that expressions are gone? It kind of stinks that we can't have defaults like 
```
def f1 [ g = 1sec ] {}
def f2 [ g = 1mb ] {}
```
in my perfect world, I'd like to be able have a default of any nushell value. Maybe there's something minor that we're missing? https://github.com/nushell/nushell/blob/057de0661315e0b4e6f38aafca13179a4d9e8369/crates/nu-protocol/src/value/mod.rs#L41-L121

**Comment by MariaSolOs** [comment]
@fdncred agreed, I believe that the perfect scenario is to accept default parameter expressions but that evaluate to a constant. Unfortunately that's not really doable today at parse time because we don't have the evaluation stack.

**Comment by MariaSolOs** [comment]
Addressing your question, I think that the culprit isn't `Value` but in [`eval_constant`](https://github.com/nushell/nushell/blob/1de57eb2b6d1f04d28ccf19b92525cce0bf04829/crates/nu-parser/src/eval.rs#L10). We could make it more flexible so that it can evaluate a richer set of expressions.
