### ISSUE TITLE
Pasting into Terminal entirely broken since 0.80.0 (Example: GPG Passphrase Paste)

### ISSUE THREAD

**Issue by theAkito** [nushell/nushell#9218]
### Describe the bug

Since upgrading to version 0.80.0 pasting a GPG passphrase always yields `gpg: signing failed: Bad passphrase`. Pasting it into terminal, as plain text, seems to work fine. _Something_ is pasted, but I don't know what. Probably some signs are just misinterpreted internally by Nu.

Needless to say, it continues to work in Bash. So, it is 100% a Nu issue & not something with my GPG setup.

### How to reproduce

1. gpg --yes -s s.txt
2. Paste passphrase & Enter.
3. Bad Passphrase error appears.

### Expected behavior

Should work as before 0.80.0.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.80.0                                   |
| branch             |                                          |
| commit_hash        | 8695b575848d5eb4d688087aa9e906b4d9e7c8d8 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)      |
| rust_channel       | 1.67.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)      |
| build_time         | 2023-05-16 22:25:05 +00:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

### Additional context

**Platform**
Debian GNU/Linux 11 (bullseye) in WSL2 on Windows 10

**Terminal software**
Windows Terminal

**Comment by fdncred** [comment]
I suspect this is the new bracketed paste that was enabled with this release. @WindSoilder I think you enabled that feature. Is there a config option for it so we can turn it off to see what's going on?

**Comment by WindSoilder** [comment]
Hi, can you please try to disable bracketed_paste in config?
let-env config = {
    ....
    bracketed_paste: false # enable bracketed paste, currently useless on windows
    ....
}

**Comment by theAkito** [comment]
@WindSoilder 👋🏻

Thanks, it helps. However, I found out that the issue is more complicated.

After working around the issue with GPG input inside Bash, it did not matter whether the setting was enabled or disabled in Nushell, anymore.
After rebooting the entire computer, the issue re-appeared. Then, I disabled this setting & yes, it worked.
I do not understand why it starts working temporarily, until the next reboot, though. Possibly some Nu environment changes permanently, until the next reboot.

**Comment by WindSoilder** [comment]
>  Then, I disabled this setting 

I wonder how do you disable this setting?  I don't think you need to re-disable after rebooting, did you disable by modifying config file?

**Comment by theAkito** [comment]
> I wonder how do you disable this setting? I don't think you need to re-disable after rebooting, did you disable by modifying config file?

Tried all kinds of things, because I couldn't believe, that it started working now, just to see it not work again, past the next reboot.

Mainly, I first disabled it inside `config.nu`, then obviously always re-opened a new shell instance & also modified `$env.config` inside an interactive shell. Did not make any difference anymore, until reboot.

**Comment by WindSoilder** [comment]
sigh...I can't reproduce it on my mac...I tried to use `abc123` Passphrase..

**Comment by WindSoilder** [comment]
I can't reproduce it on Mac, using alacritty, wezterm and iterm2...It seems that it's a platform specific issue

**Comment by hustcer** [comment]
@WindSoilder I'm on a mac with iterm2 terminal, I think I have this issue too. When I try ssh to a remote server and paste my password it kept on response with “Permission denied, please try again.”.   it works well when I quit `nu` and use `zsh`

**Comment by WindSoilder** [comment]
@huster I have tried with ssh, with `bracketed_paste: false` configuration, and still can't reproduce it..
Have you made it to false?

**Comment by hustcer** [comment]
> Have you made it to false?

No，I haven't, I'm using the default config: https://github.com/nushell/nushell/blob/77aee7e54366e78ca2041b4eb321787557e8ad9c/crates/nu-utils/src/sample_config/default_config.nu#L297
I think it should work by default. Maybe we should change the default config?

**Comment by hustcer** [comment]
It's weird that it works for me now, even if `bracketed_paste: true`...

**Comment by WindSoilder** [comment]
@theAkito Hi, would you please have a test for it?

**Comment by theAkito** [comment]
> @theAkito Hi, would you please have a test for it?

Sure, though I experienced, that I recently couldn't always reproduce it reliably, but I'll still test it soon, when I get to compile a development version of Nu, containing the new implementation. :)

**Comment by theAkito** [comment]
Toggling `$env.config.bracketed_paste = true` & `$env.config.bracketed_paste = false` in the current shell does not yield a reproducible example.
I can only reproduce the example, when I put this statement into one of the configuration files, which are read upon shell instantiation. Then, obviously, to try it out, I have to restart the shell after each configuration change.

I now can reproduce the problem with the previous version.
After compiling from master, I could confirm, that the error successfully was fixed. Double checked.

Thanks to everyone! Great job, @WindSoilder!
