### ISSUE TITLE
`incompatible_path_access` Error on block when adding a seemingly unrelated line

### ISSUE THREAD

**Issue by cmidkiff87** [nushell/nushell#9219]
### Describe the bug

Running this script throws `Error: nu::shell::eval_block_with_input` and `Error: nu::shell::incompatible_path_access` errors.

Oddly, if you comment out that last line, the script succeeds as expected.

```nu
#!/bin/env nu

let files = [
    "1 2 3",
    "4 5 6"
]

let files = (
    $files | each {|$it|
        $it | split row -r '\s+' | each {|x|
            { perms: $x.0, name: $x.2 }
        }
    }
)

$files
($files | each {|x2| print $x2} )
```

### How to reproduce

1. run the script

### Expected behavior

Nushell's behavior (for that specific block) shouldn't change with the addition of the final line

### Screenshots

<details>

![image](https://github.com/nushell/nushell/assets/39914727/7e68037e-ab95-4e0b-a8f3-317bc49143ae)

</details>

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.80.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 8695b575848d5eb4d688087aa9e906b4d9e7c8d8                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) (Arch Linux rust 1:1.69.0-3) |
| cargo_version      | cargo 1.69.0                                                     |
| build_time         | 2023-05-17 05:13:57 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | default, zip                                                     |
| installed_plugins  |                                                                  |

### Additional context

The script is parsing some `ls` output from adb shell, but I tried to provide a minimal example.  The goal of the script is to parse the ls output into a table of records containing `{ perms: 'drwxrwxrwx', name: 'foo'  }`

In my testing, it seemed that the nested loop (`$it | split row -r '\s+' | each {|x|`) is important for triggering this bug

**Comment by fdncred** [comment]
What do you expect the output to look like? I get this but I'm not sure it has the output you're looking for
```
$files | each {|r| $r | split row -r '\s+'} | each {|i| {perms: $i.0 name: $i.2}}
╭───┬───────┬──────╮
│ # │ perms │ name │
├───┼───────┼──────┤
│ 0 │ 1     │ 3    │
│ 1 │ 4     │ 6    │
╰───┴───────┴──────╯
```
I think this is what you're looking for given this
```
$files | each {|r| $r | split row -r '\s+'} | each {|i| print $i}
╭───┬───╮
│ 0 │ 1 │
│ 1 │ 2 │
│ 2 │ 3 │
╰───┴───╯

╭───┬───╮
│ 0 │ 4 │
│ 1 │ 5 │
│ 2 │ 6 │
╰───┴───╯
```

**Comment by cmidkiff87** [comment]
@fdncred the first option is what I was expecting.  I wanted to parse the stdout of `adb shell 'ls /sdcard/'`, grabbing the folder/file names, and whether or not the record was a directory or not (`'drwx------'` | str starts-with 'd'`)

**Comment by fdncred** [comment]
ok, closing this then.

**Comment by cmidkiff87** [comment]
The issue was about the changing behavior of prior code when you include the final line.  That smells like a bug.

It looks like it's because I was trying to use nested `each` loops.  Regardless, is nushell supposed to behave like that?
