### ISSUE TITLE
How do I use both shell built-in open and macOS open functionality?

### ISSUE THREAD

**Issue by guilt** [nushell/nushell#9220]
### Question

I was able to use macOS's `open` functionality in Nu by setting `alias open = /usr/bin/open`. I typically need this to open any file in a graphical application (such as a HTML / PDF file etc.)

Alas, this meant that the shell's builtin was overwritten. How do I get this back? Is there a way to temporarily assign another variable to the shell builtin and use it later? Like:

```
alias openfile = open
alias open = /usr/bin/open
```

**Comment by fdncred** [comment]
Hopefull this still works. I haven't tried it in a while. https://www.nushell.sh/book/configuration.html#macos-keeping-usr-bin-open-as-open

**Comment by liam-ngy** [comment]
> Hopefull this still works. I haven't tried it in a while. https://www.nushell.sh/book/configuration.html#macos-keeping-usr-bin-open-as-open

It doesn't work for me :(. Whatever I type ^open, open, nuopen it always uses the mac version

**Comment by fdncred** [comment]
That's weird. It works ok on my mac.
![image](https://github.com/nushell/nushell/assets/343840/8f36108d-16ea-4d45-81a4-fce3da59afe7)

**Comment by liam-ngy** [comment]
That's weird.  I just ran these two command in my terminal and tried to open a file with nuopen and it just uses the operating system `open`

**Comment by fdncred** [comment]
I'm not understanding how that's possible. If you're inside of a running nushell `open` will be the builtin command. The only way to call the macos open is to prefix it with a caret. What version of nushell are you running?

🤔 I wonder if it makes a difference what order you define them in? Like maybe nuopen needs to be first and then the alias for ^open.

**Comment by liam-ngy** [comment]
Yeah not sure how can that happy, quite frustrating when you see in all the videos that's working on the macOS.
I'm using `0.80.0`

**Comment by fdncred** [comment]
Let me say it another way. I cannot reproduce what you're seeing. If I use `open` within nushell, it calls nushell's built-in `open` command. If I use `^open` it calls the MacOS command. If I define it like I described above, it works as expected. If we cannot reproduce the problem, we may not be able to help much further.

**Comment by liam-ngy** [comment]
Not sure if that helps.
I found out when I type `nuopen -h` it uses the nu open version but as soon as I try to use `nuopen -r test.json` it uses again the macOS version of it. Something must be going on there.

```
Flags:
  -r, --raw -
  -h, --help - Display the help message for this command

Parameters:
  arg <any>:
```

<img width="1448" alt="image" src="https://github.com/nushell/nushell/assets/8395044/d5063c31-4713-4e19-b5d4-4699b23d7602">
This is part of my config

```
def nuopen [arg, --raw (-r)] { if $raw { open -r $arg } else { open $arg } }
alias open = ^open

# let-env PATH = ($env.PATH | split row (char esep) | prepend '/opt/homebrew/bin')
source ~/.zoxide.nu
source ~/.cache/starship/init.nu

```

**Comment by fdncred** [comment]
This is just so weird. What happens if you type it into the repl. This is what I get.
![image](https://github.com/nushell/nushell/assets/343840/4d463193-20c6-4fcb-abe7-b01ece391c29)

**Comment by fdncred** [comment]
Just for testing, I put

```
def nuopen [arg, --raw (-r)] { if $raw { open -r $arg } else { open $arg } }
alias open = ^open
```
right before the # let-env PATH, just like your example and it works fine for me.

**Comment by liam-ngy** [comment]
<img width="730" alt="image" src="https://github.com/nushell/nushell/assets/8395044/8627f577-7ece-46b4-871c-14ee1506869f">

I tried to put the code into the prompt but got the same result. Used brew and changed to cargo seems to give me the same result. 😅
Is there no other way to try to use nu's open?
Thanks for your help though, appreciate your quick response!

**Comment by fdncred** [comment]
It's hard for me to tell that you're actually running nushell. I guess it's your starship prompt maybe. For all I know, nu is running and failing silently. If you type `version` what does it say?

**Comment by guilt** [comment]
I tested the `nuopen` business. It seems to work for me. Need to understand if there are other problems faced by @liam-ngy

**Comment by liam-ngy** [comment]
<img width="483" alt="image" src="https://github.com/nushell/nushell/assets/8395044/e49b3b43-6140-41db-979c-b9c5da46853c">

**Comment by guilt** [comment]
Why is `open` still showing as a builtin for you? Did the alias line `alias open=^open` even work?

**Comment by guilt** [comment]
Feel free to re-open if you can reproduce this consistently.
