### ISSUE TITLE
how do I disable history suggestion?

### ISSUE THREAD

**Issue by NgoHuy** [nushell/nushell#9228]
### Question

I want to disable history sugguestion when typing command but I need history completions. I saw that they are different feature like zsh or fish.

**Comment by fdncred** [comment]
By `history suggestion` I think you might mean hinting. There is no way to turn off hinting but what I've recommended others do is to change the color of the hints to the color of your terminal background color which makes them invisible.

To do this, you need to edit the config.nu and look at the color_config. It should point to a theme. In that theme, you can change the color of "hints" to the appropriate color.

**Comment by NgoHuy** [comment]
Thank you for your answer
