### ISSUE TITLE
cd does not update std dirs

### ISSUE THREAD

**Issue by YummyOreo** [nushell/nushell#9229]
### Describe the bug

If you `cd` after entering a dir with std dirs it foes not update. Same with shells

### How to reproduce

1. Open a nushell instance
2. Run `shells`
3. Cd into another dir
4. Run shells again

### Expected behavior

The last shells call should show the current dir, but it shows the last

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.80.1                                   |
| branch             | main                                     |
| commit_hash        | 6a0c88d516faf9fd1165fddbd7ef69ba47f97cc6 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)      |
| rust_channel       | 1.67.1-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)      |
| build_time         | 2023-05-17 18:54:25 -05:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  | periodic-table                           |

**Comment by fdncred** [comment]
Just copying this info from our discord chat on this subject.

the `active` shell path updates as you `cd`, but it doesn't add items to the list
when you start you have 1 shell in shells and it's active. if you cd, the path gets updated for that active shell
if you enter a folder, you have 2 shells, 1 active and 1 not active, as you cd, the path for the active one gets updated 
`p`, `n`, `g` switch which shell that is active and cds to the active folder
so, ya, we either need to revert that PR or fix the stdlib, or decide not to have this functionality

**Comment by bobhy** [comment]
I'll take a look today.
