### ISSUE TITLE
Broken pipe (os error 32) X 8

### ISSUE THREAD

**Issue by Dialga** [nushell/nushell#9239]
### Describe the bug

When piping fselect into nushell from csv then piping out to an external command, an 'Broken pipe' error displays 8 times.

### How to reproduce

1. in a folder with 1000s of files, run `nu -c 'fselect name,size from . into csv | from csv'|head`
2. you get output followed by:
```
Broken pipe (os error 32)
Broken pipe (os error 32)
Broken pipe (os error 32)
Broken pipe (os error 32)
Broken pipe (os error 32)
Broken pipe (os error 32)
Broken pipe (os error 32)
Broken pipe (os error 32)
```

### Expected behavior

No broken pipe error message.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.80.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 8695b575848d5eb4d688087aa9e906b4d9e7c8d8                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) (Arch Linux rust 1:1.69.0-3) |
| cargo_version      | cargo 1.69.0                                                     |
| build_time         | 2023-05-17 05:13:57 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | default, zip                                                     |
| installed_plugins  |                                                                  |

**Comment by melMass** [comment]
Not sure to understand. In what shell are you executing this bash?

This works fine in nu alone

```bash
fselect name,size from . into csv | from csv -n | rename name size
```

**Comment by Dialga** [comment]
Hi yes I'm using bash with alacritty.

**Comment by melMass** [comment]
> Hi yes I'm using bash with alacritty.

Maybe come on the discord to explain your workflow as I'm not sure of the use case. Nu is type and use many value type (string, lists, records, tables, dates, duration etc etc...) so sending that raw like that don't really work.

You could use any of the `to` converters:
![image](https://github.com/nushell/nushell/assets/7041726/ce5c4f41-7fb0-401b-bc9c-30b17864bdcd)


and try `| to text | ansi strip` at the end of the pipe, so this for instance:

```bash
nu -c "fselect name,size from . into csv | from csv -n | rename name size | to text | ansi strip" | head
```

But again there is probably a better way depending on your goal
