### ISSUE TITLE
Cursor style is changed after exit

### ISSUE THREAD

**Issue by alimkoca** [nushell/nushell#9243]
### Describe the bug

The cursor type changes from block to line, and I have a doubtful thought about the graphics library that's used in nushell.

### How to reproduce

1. Run nushell in bash
2. Exit from nushell

### Expected behavior

I didn't expect to see the cursor as line cursor.

### Screenshots

This is the tab where nushell is executed and exited:

![Bildschirmfoto vom 2023-05-19 21-16-11](https://github.com/nushell/nushell/assets/66552942/2980a35f-cb88-4990-8e02-d2453aeff29d)

This is another tab where nushell isn't executed:

![Bildschirmfoto vom 2023-05-19 21-16-32](https://github.com/nushell/nushell/assets/66552942/8b602cf9-1a17-4bf2-9c8c-123eba394d65)

### Configuration
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.80.1                                   |
| branch             | main                                     |
| commit_hash        | ca275f59dacceb24a0d2bcd98f8191b313316bb3 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)      |
| rust_channel       | 1.67.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)      |
| build_time         | 2023-05-19 20:41:31 +03:00               |
| build_rust_channel | debug                                    |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by wickles** [comment]
I have the same problem when exiting nushell on iTerm2 (macos).

**Comment by nibon7** [comment]
I think you can set `cursor_shape.emacs` to `block` in `$HOME/.config/config.nu`

https://github.com/nushell/nushell/blob/3e55addbdd8f74841590ea935f839027b6d50b50/crates/nu-utils/src/sample_config/default_config.nu#L287

**Comment by alimkoca** [comment]
Alright, thanks. But something that requires a specific configuration seems annoying a bit.
