### ISSUE TITLE
Calling inspect causes Nu to crash

### ISSUE THREAD

**Issue by Tiggax** [nushell/nushell#9255]
### Describe the bug

Calling inspect with no prior input causes Nu to panic and crash

Panic: `thread 'main' panicked at 'attempt to divide by zero', crates\nu-command\src\debug\inspect_table.rs:88:15`

### How to reproduce

1. Open Nu
2.  Call inspect eg: `inspect` with no input data
3. Nu crashes

### Expected behavior

Calling `inspect` with no input data should error and warn user to pass data prior to calling `inspect`.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.80.0                                   |
| branch             |                                          |
| commit_hash        | 8695b575848d5eb4d688087aa9e906b4d9e7c8d8 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)      |
| rust_channel       | 1.67.1-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)      |
| build_time         | 2023-05-16 22:27:13 +00:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |

**Comment by fdncred** [comment]
Thanks for the issue. You're right that it shouldn't do this and we should definitely fix it. However, there is no purpose to calling `inspect` with no pipeline input. The whole goal of `inspect` is to show you info from the preceding pipe.
