### ISSUE TITLE
change style of search results

### ISSUE THREAD

**Issue by solodov** [nushell/nushell#9275]
### Question

There doesn't seem to be a way to change style of search results highlighting. It's always red background with the default foreground. 

Digging through the code I found find calls style computer with "search result" style name at https://github.com/nushell/nushell/blob/74724dee809c039440ce299db65ee5ad5aa321ea/crates/nu-command/src/filters/find.rs#L403, but attempts to add "search result" to color config did nothing. 

Is there a way to style search result?

**Comment by fdncred** [comment]
Short answer is, No, I don't believe there is any way to change the highlight color right now.

I'm not really sure what that line is doing. I'm guessing it has nothing to do with "search result" and it's just making a particular style for the string type.

If we were to allow the highlight to be customized, we'd need to define it here https://github.com/nushell/nushell/blob/74724dee809c039440ce299db65ee5ad5aa321ea/crates/nu-color-config/src/style_computer.rs#L145-L167, use it in the config here https://github.com/nushell/nushell/blob/74724dee809c039440ce299db65ee5ad5aa321ea/crates/nu-protocol/src/config.rs#L69-L111, and use it here https://github.com/nushell/nushell/blob/74724dee809c039440ce299db65ee5ad5aa321ea/crates/nu-cmd-lang/src/core_commands/help.rs#L220-L221
and perhaps update other places. The config and coloring is pretty complicated these days. Would love to simplify it.

**Comment by solodov** [comment]
thanks for confirming what I already suspected. I'd like to take a stab at implementing it.
