### ISSUE TITLE
Feature request: additional options for the ls command

### ISSUE THREAD

**Issue by Mirage10** [nushell/nushell#9284]
it would be very useful to have the -e parameter for  file extension in the ls command. This would make the  path parse command in many pipes superfluous

```
ls -e | where extension = 'txt'
```
`-e` would add the extension column. for directories extension could be `dir`

also very useful the `-p` parse parameter
```
ls -p | sort-by stem
```
`-p` means add the parse  columns like parent basename, stem, full-name

**Comment by Mirage10** [comment]
thats  brilliant!  for the directories the artifical extension 'dir' would be nice

**Comment by amtoine** [comment]
> for the directories the artifical extension 'dir' would be nice
>
the *artificial extension* is `null` with `if $file.type == file { get name | path parse | get extension }` and it's the empty string for files that do not have an extension :muscle: 

> thats brilliant!
>
the remaining question is, **does that justify adding new options to built-in `ls`?**
not saying it should not :wink:

**Comment by Mirage10** [comment]
the anser is: pure intuition. But you are right. The standard commands should be left unchanged as much as possible. I will close the issue with a big thank you for this discussion.

**Comment by amtoine** [comment]
> the answer is: pure intuition. But you are right. The standard commands should be left unchanged as much as possible. I will close the issue
>
gotcha, and we can always come back to it later, the commands won't go anywhere :wink: 

> a big thank you for this discussion.
>
anytime :blush:
