### ISSUE TITLE
parameter for displaying complete dataframe

### ISSUE THREAD

**Issue by Mirage10** [nushell/nushell#9306]
the default behaviour of dataframe display is a shortened list, when the size exceeds a certain amount:
```
~> 1..200 | dfr into-df                                                                                                                                             
╭─────┬─────╮
│   # │  0  │
├─────┼─────┤
│   0 │   1 │
│   1 │   2 │
│   2 │   3 │
│   3 │   4 │
│   4 │   5 │
│   5 │   6 │
│   6 │   7 │
│   7 │   8 │
│   8 │   9 │
│   9 │  10 │
│ ... │ ... │
│ 190 │ 191 │
│ 191 │ 192 │
│ 192 │ 193 │
│ 193 │ 194 │
│ 194 │ 195 │
│ 195 │ 196 │
│ 196 │ 197 │
│ 197 │ 198 │
│ 198 │ 199 │
│ 199 │ 200 │
╰─────┴─────╯
```
"..." indicates, that the list is shortened.

my question is: how can I display the complete list? Is this a parameter in the config?  Would it make sense to have a parameter in the command like  show rows max =200 or show rows all  ?

when having all rows available, the terminal scroll can be used.

**Comment by fdncred** [comment]
One way is to convert the output back into a nushell table like
```
1..200 | dfr into-df | dfr into-nu
```
I do not believe there is any config param that controls how dfrs are abbreviated.

You can also pipe this to our `explore` tui for scrolling like
```
1..200 | dfr into-df | dfr into-nu | explore
```

**Comment by Mirage10** [comment]
wow! Option 1 i really prefer.

**Comment by johnalotoski** [comment]
I spent way too much time trying to answer this question in looking through the docs and cmd help.  Glad I finally found an answer here.
