### ISSUE TITLE
Weird installation with macOS Catalina

### ISSUE THREAD

**Issue by jwoertink** [nushell/nushell#931]
**Describe the bug**
I just saw a tweet saying 0.5.0 was released, so I decided to give this a shot. I installed from brew (`brew install nushell`), but it installed a lower version. It says it installed version 0.2.0, but when I ran `nu -h`, it shows version 0.1.3. 

**To Reproduce**
1. `brew install nushell`

**Expected behavior**
I expected to have version 0.5.0 installed

**Screenshots**
<img width="1035" alt="Screen Shot 2019-11-06 at 9 38 55 AM" src="https://user-images.githubusercontent.com/2391/68323026-67c18500-0079-11ea-9e32-5d762d0d3dd6.png">

**Configuration (please complete the following information):**
 - OS: macOS Catalina

**Comment by jonathandturner** [comment]
This comes from a bug in the 0.2.0 release. We've fixed it in master, so the version should align with the release now.

Going ahead and closing as this should go away naturally once homebrew updates to the latest version.

**Comment by jwoertink** [comment]
Ok cool. I guess I'll just keep checking for a homebrew update.
