### ISSUE TITLE
"from ini" doesn't exist

### ISSUE THREAD

**Issue by bennett-sh** [nushell/nushell#9311]
### Describe the bug

When I try to use a command like `open test.ini | from ini` it gives me an error that ini is not a valid argument (help also doesn't show it).

### How to reproduce

1. Use "from ini"
2. See it

### Expected behavior

I expected it to put the ini into a structure.

### Screenshots

```console
~/dev/Rust> open desktop.ini | from ini
Error: nu::parser::extra_positional

  × Extra positional argument.
   ╭─[entry #3:1:1]
 1 │ open desktop.ini | from ini
   ·                         ─┬─
   ·                          ╰── extra positional argument
   ╰────
  help: Usage: from

```

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.80.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | windows-x86_64                      |
| build_target       | x86_64-pc-windows-msvc              |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) |
| rust_channel       | stable-x86_64-pc-windows-msvc       |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12) |
| build_time         | 2023-05-28 16:58:20 +02:00          |
| build_rust_channel | release                             |
| features           | default, zip                        |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
It's a plugin now in nu_plugin_formats. It was moved a few releases ago.

**Comment by bennett-sh** [comment]
oh, thanks
