### ISSUE TITLE
converting a list to a record for fast access

### ISSUE THREAD

**Issue by happysalada** [nushell/nushell#9313]
### Question

I have a long list of numbers [0, 18, 768, 1565447, ...]
and I would like to transform it into a record for fast access (actually just verify if the values are included), so the output I would like is {"0": true, "18": true, ...}
What I came up with was 
```
list | reduce -f {} { |it, acc| $acc | insert ($it | into string) true}
```
I know that this is horrible for 2 reasons, converting a number to a string allocates, then growing a record key by key has got to be the worst strategy for allocation.
I just want to check if a value is included in a set, but I haven't found any other way.
With a list that is 500,000 numbers, this takes north of 30 minutes unfortunately, I'm sure there is a better way, I just haven't found it.

**Comment by happysalada** [comment]
I saw into record, i tried working with transpose to get the values as keys, but never figured out how to do it.


The second example you have looks promising. How can you check if a value is in the set though ? I tried using select or get, but couldnt figure out the syntax. Using the previous example i want to be able to have a command that takes an input and tells me true or false based on if the element is in the list or not. Do you see how to use get or select to achieve that ?

**Comment by fdncred** [comment]
I think by "set" maybe you mean a list. This is a list `[0, 18, 768, 1565447, 7]` or without commands `[0 18 768 1565447 7]`. To check if a value is in a list you can use `in` or `not-in` like `18 in [0, 18, 768, 1565447, 7]`

**Comment by happysalada** [comment]
Im afraid going through the whole list everytime is going to be increadibly time consuming (o(n)) and the base case is that the number is not in the list and so you have to go through the whole list. Thats why i wanted to convert it into a record to get fast access.
Im happy to use a table, i just dont know how to know if a row exists from a number, the 'nth' function is deprecated and couldnt figure out how to use select to make it happen.

By set i mean it in the sense of a collection of unique numbers. I would like to know if a number is part of this or not in a very quick manner as the set can grow quite large .

**Comment by fdncred** [comment]
> I would like to know if a number is part of this or not in a very quick manne

and `number in list` isn't fast enough?

**Comment by lodezo** [comment]
You're question is about converting a list of numbers to a record for easy access.

I just want to note that sometimes it is easier to import data in the right form, instead of converting it afterwards. Just to give another angle at the problem: You can ask yourself, what is the origin of the data? E.g. using the nushell `open` command on a JSON file gives a record.

**Comment by fdncred** [comment]
Ahh, we're talking about large-ish numbers. We have our dataframe (dfr) features that are good with millions of rows, although I would say that dfrs are not as intuitive to use. If you're after performance with this size of data, you should really explore dfrs because they're incredibly fast thanks to polars.

**Comment by happysalada** [comment]
I'm looking at dataframes now, I'm missing one key part.
How do you convert a column into the dataframe from strings to datetime.
I haven't found a way.
```
 > dfr open data/rooms/00/104871455/message1.csv | dfr dtypes
╭───┬────────────────┬───────╮
│ # │     column     │ dtype │
├───┼────────────────┼───────┤
│ 0 │ 発言日時       │ str   │
│ 1 │ 編集・削除時間 │ str   │
│ 2 │ ルームID       │ i64   │
│ 3 │ ルーム名       │ str   │
│ 4 │ アカウントID   │ i64   │
│ 5 │ アカウント名   │ str   │
│ 6 │ 発言内容       │ str   │
│ 7 │ 編集履歴       │ str   │
╰───┴────────────────┴───────╯
```

but if I try
```
dfr open data/rooms/00/104871455/message1.csv | dfr with-column [ ((dfr col "発言日時") | dfr as-datet
ime) | dfr as "id")]
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #64:1:1]
 1 │ dfr open data/rooms/00/104871455/message1.csv | dfr with-column [ ((dfr col "発言日時") | dfr as-datetime) | dfr as "id")]
   ·                                                                                           ─┬─
   ·                                                                                            ╰── did you mean 'dfr as'?
   ╰────
  help: No such file or directory (os error 2)
```

Should I open a separate issue ?

**Comment by fdncred** [comment]
It may be good to ask on our Discord #dataframes channel. I found this there which may be helpful.
```
❯ let $t1_df1 = ([[ts const]; [(date now) 1] [((date now) + 50.5sec) 2]]); $t1_df1
┏━━━━━━━━━━━━━┳━━━━━━━┓
┃     ts      ┃ const ┃
┣━━━━━━━━━━━━━╋━━━━━━━┫
┃ now         ┃     1 ┃
┃ in a minute ┃     2 ┃
┗━━━━━━━━━━━━━┻━━━━━━━┛

❯ $t1_df1 | dfr into-df | dfr with-column ($t1_df1 | dfr into-df | dfr select ts | dfr get-nanosecond | dfr rename ts ts_n)
┏━━━┳━━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━━━━┓
┃ # ┃      ts       ┃ const ┃   ts_n    ┃
┣━━━╋━━━━━━━━━━━━━━━╋━━━━━━━╋━━━━━━━━━━━┫
┃ 0 ┃ now           ┃     1 ┃ 434000000 ┃
┃ 1 ┃ in 45 seconds ┃     2 ┃ 934000000 ┃
┗━━━┻━━━━━━━━━━━━━━━┻━━━━━━━┻━━━━━━━━━━━┛
```

**Comment by bobhy** [comment]
If all you want is a set of distinct numbers (and the whole list is already in memory), how about:
```
〉[0, 18, 768, 0, 1565447] | uniq
╭───┬─────────╮
│ 0 │       0 │
│ 1 │      18 │
│ 2 │     768 │
│ 3 │ 1565447 │
╰───┴─────────╯

```

If you need counts of each, there's this:

```
〉[0, 18, 768, 0, 1565447] | histogram
╭───┬─────────┬───────┬──────────┬────────────┬──────────────────────────────────────────╮
│ # │  value  │ count │ quantile │ percentage │                frequency                 │
├───┼─────────┼───────┼──────────┼────────────┼──────────────────────────────────────────┤
│ 0 │       0 │     2 │     0.40 │ 40.00%     │ **************************************** │
│ 1 │      18 │     1 │     0.20 │ 20.00%     │ ********************                     │
│ 2 │     768 │     1 │     0.20 │ 20.00%     │ ********************                     │
│ 3 │ 1565447 │     1 │     0.20 │ 20.00%     │ ********************                     │
╰───┴─────────┴───────┴──────────┴────────────┴──────────────────────────────────────────╯
|v| ----------------------------/home/bobhy/src/rust/nushell [git: duration origin/duration]----------------------------
〉[0, 18, 768, 0, 1565447] | histogram | select value count
╭───┬─────────┬───────╮
│ # │  value  │ count │
├───┼─────────┼───────┤
│ 0 │       0 │     2 │
│ 1 │      18 │     1 │
│ 2 │     768 │     1 │
│ 3 │ 1565447 │     1 │
╰───┴─────────┴───────╯
```

**Comment by happysalada** [comment]
Thanks for coming by !

I already have the uniq values and need to know if a certain value is included in the list. Unfortunately dealing with a large list makes the "in" operator prohibitively expensive .
The dataframe is the proper way to go here, using masks, but there are still some operations that i dont know how to do, like converting a column of datetime strings to datetime.

**Comment by fdncred** [comment]
I was playing around and came up with this @happysalada. I just think it's a little strange that the column name changes from date to datetime.
```
[[date]; ["2023-12-01"] ["2022-12-01"]] | dfr into-df | dfr as-datetime "%Y-%m-%d"
╭───┬──────────────╮
│ # │   datetime   │
├───┼──────────────┤
│ 0 │ in 5 months  │
│ 1 │ 6 months ago │
╰───┴──────────────╯
```

**Comment by happysalada** [comment]
You can do this because its a dataframe with a single column, so a series. Try to do this with a dataframe with two column and changing one of the two columns. Thats what i couldnt figure how to do.

**Comment by weirdan** [comment]
> I have a long list of numbers [...] and I would like to transform it into a record for fast access 

Note that there's little (if any) performance benefit in doing so. Record is stored internally as a list of key/value pairs, so big records are just as slow as big lists.

**Comment by sholderbach** [comment]
> Record is stored internally as a list of key/value pairs

This implementation detail may be subject to future change, but at least for now the premise of the question title does not work.

Closing the thread, as it seems that there was some resolution.
