### ISSUE TITLE
durations and filesizes can no longer be parameter defaults 

### ISSUE THREAD

**Issue by bgeron** [nushell/nushell#9317]
### Describe the bug

The following code no longer works:

```nu
def f [x=1day] {}
```

Error: `Default values should be constant expressions`.

This no longer works in v0.80, but it worked in v0.79.

### How to reproduce

1. Run `def f [x=1day] {}`

2. Run `def f [x=1kB] {}`

### Expected behavior

I expect duration and filesize parameter defaults to be possible.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.80.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | macos-x86_64                        |
| build_target       | x86_64-apple-darwin                 |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) |
| rust_channel       | stable-x86_64-apple-darwin          |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12) |
| build_time         | 2023-05-30 11:04:27 +02:00          |
| build_rust_channel | release                             |
| features           | default, zip                        |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
This functionality was re-added back a few weeks ago. If you compile the latest main, which is 0.80.1, it should work again.

**Comment by bgeron** [comment]
Great, thanks!
