### ISSUE TITLE
explore replaces missing values with the whole row

### ISSUE THREAD

**Issue by bgeron** [nushell/nushell#9318]
### Describe the bug

When I explore `[{a: a, b: b}, {a: a}]`, then the second row seems to contain a value for `b`, namely `{a: a}` itself.

### How to reproduce

`[{a: a, b: b}, {a: a}] | explore`

### Expected behavior

The second row should have nothing in column `b`. But it does.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.79.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12) |
| build_time         | 2023-05-16 18:27:33 +02:00          |
| build_rust_channel | release                             |
| features           | default, zip                        |
| installed_plugins  |                                     |

Still exists in 0.80.

**Comment by fdncred** [comment]
@zhiburt any ideas about this? I don't get the exact screenshots with explore, but it's close in v0.80.1
