### ISSUE TITLE
csv - support setting the separator character or auto-detect it

### ISSUE THREAD

**Issue by thibran** [nushell/nushell#932]
**Is your feature request related to a problem? Please describe.**
Microsoft Exel saves .csv files in the german editon with `;` as separator character (don't ask me why).

**Describe the solution you'd like**
Auto-detect the csv separator. Also add an `--separator` flag to the csv command.

**Describe alternatives you've considered**
It is certainly possible to convert csv files into the right format using external tools like `libreoffice --headless`.

**Comment by jonathandturner** [comment]
This is now available with #943
