### ISSUE TITLE
Please port notify-dependent code to at least v5

### ISSUE THREAD

**Issue by michel-slm** [nushell/nushell#9324]
### Related problem

I'm getting close to getting Nushell packaged in Fedora - many crates are in, and right now I am going through the dependencies of `nu-command`. One of them is `notify`, and `nu-command` currently needs v4.

Fedora now has v5 packaged, which is dual-licensed under CC0-1.0 or Artistic-2.0. Unfortunately v4 is CC0-1.0 only, and that is no longer consider permissible for code in Fedora. So the packaging is currently blocked until this is resolved.

### Describe the solution you'd like

Port the code that needs notify to v5. Porting guide: Porting guide: https://github.com/notify-rs/notify/blob/main/UPGRADING_V4_TO_V5.md

**Comment by fdncred** [comment]
We would accept a PR to update to notify v5. The problem is that it's not a trivial upgrade where everything is backward compatible.

**Comment by rgwood** [comment]
Yeah, some context:
https://github.com/nushell/nushell/pull/8114
https://github.com/nushell/nushell/pull/8367

v5 is a huge pain to upgrade to; it drops useful functionality like debouncing. We'll probably need to either write our own debouncing functionality or drop the `watch` command which uses `notify` (I think that would be a shame, but I also don't have time to upgrade `notify` so I would understand if we decide to go that route).

**Comment by michel-slm** [comment]
@rgwood looks like there's a new `debouncing-full` in addition to `debouncing-mini` - would that solve the edge cases that `mini` does not cover?

https://github.com/notify-rs/notify/blob/main/CHANGELOG.md

**Comment by rgwood** [comment]
Oh nice! Looks like the `notify` people made some good improvements since last I checked. Yeah, that might help.

cc: @WindSoilder who was previously working on upgrading to v5

**Comment by WindSoilder** [comment]
Oh, that's cool!

Thanks for your investigation @michel-slm I can take a look into it again

**Comment by sholderbach** [comment]
@michel-slm we now depend on `notify` v6 with #9606. I hope this version is compatible with the requirements for your packaging ports.
