### ISSUE TITLE
Recursive fibonacci - how to write?

### ISSUE THREAD

**Issue by SebastianMpl** [nushell/nushell#9328]
### Question

I am quite new to nushell and when playing with it I wanted to try the recursion thing. I found some examples but not all.
Could someone write a fibonacci function like in rust:
```
fn fib(n: u64) -> u64 {
    if n <= 1 {
        return n;
    }
    fib(n - 1) + fib(n - 2)
}
```

### Additional context and details

My effort went here:
```
def fib [number: int] {
  if $number <= 1 {return 1}  
  else { fib ($number - 1) + fib ($number - 2)}
}
```

when I invoke it like fib 10 the error asks did you mean 'ls'?

BTW: Is tail recursion also supported?

Thank you,

**Comment by WindSoilder** [comment]
It's a little bit weild, but you need to put `else` and `}` in the same line..
```
def fib [number: int] {
  if $number <= 1 {return 1} else { 
      (fib ($number - 1)) + (fib ($number - 2))
  }
}
```
Or nushell will failed to parse else as a part of `if`

**Comment by SebastianMpl** [comment]
> It's a little bit weild, but you need to put `else` and previous `}` in the same line..
> 
> ```
> def fib [number: int] {
>   if $number <= 1 {return 1} else { 
>       (fib ($number - 1)) + (fib ($number - 2))
>   }
> }
> ```
> 
> Or nushell will failed to parse else as a part of `if`

It works now.
Thank you very much for your answer.
