### ISSUE TITLE
query command not found on Nu 0.80

### ISSUE THREAD

**Issue by Mayeu** [nushell/nushell#9330]
### Describe the bug

Hello,

Today I tried to use the `query web` command but it is failing with the following error:
```
➜ nu --version
0.80.0

➜ uname -a
Darwin xxxx.yyyyy.zzzz 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:19 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6020 arm64 arm Darwin

➜ nu
~> query web                                                                                    06/01/2023 12:16:17 pm
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #4:1:1]
 1 │ query web
   · ──┬──
   ·   ╰── did you mean 'url join'?
   ╰────
  help: No such file or directory (os error 2)
```

The only working query command seems to be `query db`:
```
~> query db                                                                                     06/01/2023 12:15:58 pm
Error: nu::parser::missing_positional

  × Missing required positional argument.
   ╭─[entry #2:1:1]
 1 │ query db
   ╰────
  help: Usage: query db <SQL>

~> query                                                                                        06/01/2023 12:15:55 pm
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #1:1:1]
 1 │ query
   · ──┬──
   ·   ╰── did you mean 'url join'?
   ╰────
  help: No such file or directory (os error 2)

~> query json                                                                                   06/01/2023 12:16:13 pm
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #3:1:1]
 1 │ query json
   · ──┬──
   ·   ╰── did you mean 'url join'?
   ╰────
  help: No such file or directory (os error 2)
```

### How to reproduce

1. Start nushell 0.80
2. try to launch `query`

### Expected behavior

As described in the documentation, the whole set of query command should be available in 0.80

### Configuration

~> version | transpose key value | to md --pretty                                               06/01/2023 12:23:43 pm
| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.80.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) (built from a source tarball) |
| cargo_version      | cargo 1.69.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

### Additional context

Nushell has been installed via the nix package manager (thus the weird build_time).

**Comment by happysalada** [comment]
query is a plugin, it's not available by default. you need to add the plugin before being able to use it.

**Comment by fdncred** [comment]
From the nushell repo root, you can do the following.
1. Run one of the install scripts like `scripts/install-all.sh` or `scripts/install-all.ps1`
2. Then you need to register the plugins like `source scripts/register-plugins.nu`

You can also use the toolkit to register plugins after you've installed them.
1. use toolkit.nu
2. toolkit register plugins
