### ISSUE TITLE
colors change when wrapping text

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#9335]
### Describe the bug

Found here https://github.com/nushell/nushell/pull/9326#issuecomment-1572693766

In the linked issue, if you change the search_result color to blue_reverse or any color reverse, and your terminal is shrunk small enough, you can see that wrapping is causing issues with colors.

I did this on the main branch in help.rs and it shows the problem too.
```rust
    // let style = Style::new().fg(White).on(Red);
    let style = Style {
        foreground: Some(nu_ansi_term::Color::Blue),
        is_reverse: true,
        ..Default::default()
    };
```

No wrapping
![image](https://github.com/nushell/nushell/assets/343840/8bb703f1-62c1-4a89-9b30-677d3d60c421)

Wrapping
![image](https://github.com/nushell/nushell/assets/343840/ae435949-97b6-4424-9312-1384bebb80e9)

## Here's more research form the linked issue

Nice research. Here's a different test with mine set to blue_reverse
![image](https://github.com/nushell/nushell/assets/343840/00d9643b-d8f7-474e-a70e-ab611c162fbf)
Then you can do this
```
help -f arg | last 2 | debug -r
```
and scroll down a bit and find this
```
val: "\u{1b}[37mReturns the floor of a number (l\u{1b}[0m\u{1b}[7;34marg\u{1b}[0m\u{1b}[37mest integer less than or equal to that number).\u{1b}[0m",
```

\e37m = white
Returns the floor of a number (l
\e0m = reset
\e7;34m = reverse blue
arg
\e0m = reset
\e37m = white
est integer less than or equal to that number).
\e0m = reset

We have a reset right before changing to white, so, that should reset the reverse bit. I'm not sure what's going on.

When you get a chance @zhiburt, we'd really appreciate you looking at the coloring during wrapping.

### How to reproduce

See above

### Expected behavior

color correctly

### Configuration

|key|value|
|-|-|
|version|0.80.1|
|branch|main|
|commit_hash|6481bf272c8a407aacddf91c171ebf78c0531889|
|build_os|windows-x86_64|
|build_target|x86_64-pc-windows-msvc|
|rust_version|rustc 1.67.1 (d5a82bbd2 2023-02-07)|
|rust_channel|1.67.1-x86_64-pc-windows-msvc|
|cargo_version|cargo 1.67.1 (8ecd4f20a 2023-01-10)|
|build_time|2023-05-26 09:15:25 -05:00|
|build_rust_channel|debug|
|features|default, sqlite, trash, which, zip|
|installed_plugins|from eml, from ics, from ini, from parquet, from plist, from vcf, gstat, hist, inc, json path, periodic-table, plot, pnet, query, query json, query web, query xml, regex, xyplot|

**Comment by zhiburt** [comment]
Hi there;

I very much believed I've found the cause;

https://github.com/zhiburt/ansi-str/commit/cdf902f055674d34079a620d8352142e66d01ea3#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R1821

Not yet released.

PS: (generally) does this requires a MINOR bump?

**Comment by fdncred** [comment]
glad you tracked it down! yay!
