### ISSUE TITLE
Wrong type for file sizes ZIB

### ISSUE THREAD

**Issue by DarkPark** [nushell/nushell#9337]
### Describe the bug

As described here https://www.nushell.sh/book/types_of_data.html#file-sizes `zib` is a valid type zebibyte.
But command `$ 1zib` gives `0`.

### How to reproduce

execute `1zib`

### Expected behavior

It should print `1,180,591,620,717,411,303,424`.

### Configuration

```
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.80.0                                   |
| branch             |                                          |
| commit_hash        | 8695b575848d5eb4d688087aa9e906b4d9e7c8d8 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)      |
| rust_channel       | 1.67.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)      |
| build_time         | 2023-05-16 22:25:05 +00:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |
```

**Comment by DarkPark** [comment]
And one more related bug:

`1zb` evaluates to `3,875,820,019,684,212,736` but should be `1,000,000,000,000,000,000,000`.

**Comment by fdncred** [comment]
we'd accept a PR to fix these inconsistencies

**Comment by DarkPark** [comment]
@fdncred unfortunately I'm not a Rust developer

**Comment by fdncred** [comment]
There's no better time to start. 🤣 

I tagged it with the `good first issue` label so someone will probably pick it up.

**Comment by DarkPark** [comment]
thanks

**Comment by x-dune** [comment]
Looks like 1zib would overflow 64bits. Not sure how to solve for it, changing the type to i128 is an option.

```
thread 'main' panicked at 'attempt to multiply with overflow', crates\nu-protocol\src\value\unit.rs:90:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\nu.exe` (exit code: 101)
````

**Comment by fdncred** [comment]
I wonder if the "easy" solution is just to remove it and put a comment about it overflowing? I'm not sure of the implications to making it an i128.

**Comment by x-dune** [comment]
@fdncred Agreed. It feels better than the current state. 

Changing to `i128` bleeds into a lot of other stuff.
