### ISSUE TITLE
How to read the ping xxx.com

### ISSUE THREAD

**Issue by 107295472** [nushell/nushell#9338]
### Question

but back is not the ANSI code, want to take the milliseconds inside

**Comment by fdncred** [comment]
without text example it's hard to tell. there are many flavors of ping output across platforms.

**Comment by 107295472** [comment]
It is on windows

**Comment by amtoine** [comment]
i'm still not sure i understand the question here :yum: 

do you want to extract the `88ms` and `89ms` from the output of `ping bing.com`?

**Comment by amtoine** [comment]
if so you might be able to have what you seek with something like
```bash
def ping [
    host: string
    --count (-c): int = 0
] {
    let responses = (
        if $count >= 1 {
            ^ping -c $count $host
        } else {
            ^ping $host
        }
    )

    $responses
    | lines
    | parse "{packets} bytes from {from} ({addr}): icmp_seq={icmp_seq} ttl={ttl} time={time} ms"
    | update packets { into filesize }
    | update icmp_seq { into int }
    | update ttl { into int }
    | update time {|it| $"($it.time)ms" | into duration }
}
```
:wink:

**Comment by fdncred** [comment]
>  parse "{packets} bytes from {from} ({addr}): icmp_seq={icmp_seq} ttl={ttl} time={time} ms"

This won't work as is, but it's a good reference on how they can capture the output. You can see from the screenshot that Windows' ping output is different than Linux. So, maybe they can change the parse statement a bit and still get to what they need. It'll take some playing.

**Comment by amtoine** [comment]
> This won't work as is, but it's a good reference on how they can capture the output. You can see from the screenshot that Windows' ping output is different than Linux. So, maybe they can change the parse statement a bit and still get to what they need. It'll take some playing.
>
oooh yeah, you are absolutely right :open_mouth: 

hopefully there are not too many changes to make to the script :crossed_fingers:

**Comment by 107295472** [comment]
Thanks, I can't figure it out
