### ISSUE TITLE
Add support for HTTP OPTIONS method

### ISSUE THREAD

**Issue by bgmort** [nushell/nushell#9344]
### Related problem

There is no `http options` command, and no way to specify a custom HTTP verb. OPTIONS is useful for testing CORS implementations.

### Describe the solution you'd like

A new `http options` command that is implemented the same way as the other http commands

**Comment by fdncred** [comment]
No clue what this means, please excuse my ignorance. Do you have examples and or pseudo code of how that would work in nushell?

**Comment by bgmort** [comment]
I'm not familiar with Rust or the nushell codebase, but it's just like any other HTTP method/verb. For example, with `curl` you can use `-X` to supply the method, so a POST looks like this: `curl -X POST url`. An OPTIONS request looks like this: `curl -X OPTIONS url`.

**Comment by fdncred** [comment]
oh, interesting. i wonder if we could combine all our http subcommand and make it work like that?

**Comment by WindSoilder** [comment]
>  i wonder if we could combine all our http subcommand and make it work like that?

We can support that, but TBH I don't think it's a good idea, take `http post` as an example, it requires data to post, so it has an extra required arg.  But `http get` don't need that arg.

**Comment by amtoine** [comment]
> TBH I don't think it's a good idea
>
with that in mind, i do not feel comfortable approving https://github.com/nushell/nushell/pull/9365 :thinking: 

and on the other hand, if it's just another supported HTTP method, why not?

i've never seen all these methods, so i do not have a strong opinion at all on this :relieved:

**Comment by bgmort** [comment]
Thanks for the quick turnaround on this! I have submitted a PR to improve the documented usage and examples: #9576
