### ISSUE TITLE
`url parse | url join` doesn't roundtrip when there is no query string

### ISSUE THREAD

**Issue by cumber** [nushell/nushell#9347]
### Describe the bug

When `url join` is fed the output of `url parse`, it doesn't reproduce the original URL in the (common) case when there is no query string. Instead it adds a `?`, denoting an empty query string rather than an absent query string.

The root of the issue seems to be that when `url parse` processes a URL with no query string, it produces a record with an empty string for the `query` field, and an empty record for the `params` field:

```
❯ "https://example.com/foo" | url parse
╭──────────┬───────────────────╮
│ scheme   │ https             │
│ username │                   │
│ password │                   │
│ host     │ example.com       │
│ port     │                   │
│ path     │ /foo              │
│ query    │                   │
│ fragment │                   │
│ params   │ {record 0 fields} │
╰──────────┴───────────────────╯
```

In the docs for `url join`, the only examples where it isn't intended for a query string to appear in the output use input records that simply don't have the `query` or `params` fields. And indeed removing the `params` field makes `url join`:

```
❯ "https://example.com/foo" | url parse | reject params | url join
https://example.com/foo
```

Fundamentally, the problem is that representing the query string as a record of parameters isn't capable of representing the distinction between an empty query string and an absent query string. According to [RFC3986](https://www.rfc-editor.org/rfc/rfc3986#section-6.2.3) these are not the same:

> Normalization should not remove delimiters when their associated component is empty unless licensed to do so by the scheme specification.  For example, the URI `http://example.com/?` cannot be assumed to be equivalent to any of the examples above.

This doesn't seem to be possible to solve perfectly without making the type of the output of `url parse` less predictable. Either it needs to omit the `params` and `query` fields when the query string isn't present, or they need to be set to a value that can be distinguished from an empty string/record (such as `null`).

Similar considerations probably apply to some of the other fields (all of the fields corresponding to absent parts of the URL come out as empty strings in my testing, which isn't information-preserving if it's valid to set the part to an empty string explicitly), though I'm not sure whether all of them are valid to be explicitly-empty. The query-string case is particularly unfortunate though as we end up preferring the interpretation that is less likely to be what was actually meant.

### How to reproduce

```
❯ "https://example.com/foo" | url parse | url join
https://example.com/foo?
```

### Expected behavior

I expect `url parse` to output sufficient information for `url join` to recreate common URLs. I should see:

```
❯ "https://example.com/foo" | url parse | url join
https://example.com/foo
```

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.80.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) (built from a source tarball) |
| cargo_version      | cargo 1.69.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, zip                                                      |
| installed_plugins  |                                                                   |

**Comment by amtoine** [comment]
sounds fair to me that `url parse | url join` should be the *identity* :+1:

**Comment by cumber** [comment]
After a little bit more testing, there are some more infelicities.

1. `url join` seems to treat all of the parts as missing if their field in the record consists only of whitespace; I'm pretty sure all-whitespace is valid for at least the query and fragment parts (though unusual for both).

3. `url parse` percent-encodes some things in its input but not others:

   ```
   ❯ "https://example.com/foo bar" | url parse | get path
   /foo%20bar

   ❯ "https://example.com/foo%bar" | url parse | get path
   /foo%bar
   ```

   `url join` just passes these straight through. (I suppose it's good that `url join` is inconsistent and only encodes some things, otherwise we'd risk parsing already percent-encoded things like `%20` to `%2520`, which is totally different). I'd expect that either they *both* leave percent encoding alone, or that `url parse` *decodes* and `url join` encodes (and do both consistently either to all reserved characters, or even to all non-non-reserved characters).

4. Even worse, `url parse` seems to then *decode* percent-encoding (including the spaces it just encoded) in the `params` record but not the `query` string; `url join` then fails because it checks that they match:

   ```
   ❯ "https://example.com?foo= %28" | url parse | url join
   Error: nu::shell::incompatible_parameters
   
     × Incompatible parameters.
      ╭─[entry #184:1:1]
    1 │ "https://example.com?foo= %28" | url parse | url join
      ·                                  ────┬────┬
      ·                                      │    ╰── instead query is: ?foo=%20%28
      ·                                      ╰── Mismatch, qs from params is: ?foo= (
      ╰────
   ```

5. `url join` also doesn't put the user part into the URL unless *both* a username and password is present. So the roundtrip just silently drops a username without password:

   ```
   ❯ "https://user@example.com" | url parse | url join
   https://example.com/?
   ```

   [RFC3986](https://www.rfc-editor.org/rfc/rfc3986#section-3.2.1) actually says that the `user:password@` form is deprecated to stop people storing plaintext passwords in URLs, so we definitely shouldn't be *requiring* it!

5. `url parse` trims trailing whitespace on its input. Probably not a huge problem really, but it does make do things like treat query strings ending in whitespace differently depending on whether they're followed by a 

It looks like `url join` already treats most of these fields as being missing if their value is `null` (the only exception seems to be `port` and `params`). My vote for how to fix this would be:

1. Make `url parse` emit nulls for missing parts
2. Make `url parse` treat empty or all-whitespace strings as values (failing only if those are invalid values), not as missing (and handle `null` where it doesn't already).
3. Stop `url parse` percent-encoding spaces (and anything else?) in its input
4. If `url parse` continues to percent-decode in the `params` record for convenience, `url join` should re-encode it. This might need some flags though; "encode then decode" is always a safe roundtrip, but "decode then encode" isn't unless you have specific knowledge of the input, so being able to opt-out of it is probably needed.

It'd be really easy to fix *just* the issue in the title by simply flipping `url join` to not emit a `?` when the `params` record is empty, but it would be nicer to be more careful with how everything is handled so that weird-but-valid cases (and not-so-weird like username only or no query string!) don't cause problems.

**Comment by amtoine** [comment]
@cumber
thanks for the additional research :relieved: 

@gdhuper 
would you like to work on this issue? :yum:

**Comment by gdhuper** [comment]
@amtoine yes please! Thanks

**Comment by amtoine** [comment]
> yes please! Thanks
>
oh yeah :muscle: 
for sure, please go ahead :blush:

**Comment by gdhuper** [comment]
@cumber  @amtoine  I have a quick fix for handling empty query / params: https://github.com/nushell/nushell/pull/9356
However, I want to clarify a couple of things:

- In the example, the space is automatically replaced with `%20`. But is `https://example.com/foo bar` is this even a valid URL? 
```bash
❯ "https://example.com/foo bar" | url parse | get path
/foo%20bar
```
- For the `username` and `password` scenario, do we want to remove the functionality altogether since it has been deprecated?

**Comment by cumber** [comment]
You're quite right @gdhuper, I was mistaken; a proper URL actually shouldn't have characters that are neither reserved nor unreserved in it at all; they should all be percent-encoded.

So we could be hardline and say the only acceptable input for `url parse` is a fully encoded URL, and either throw an error when it isn't or declare that it's simply "undefined behaviour" and so whatever we do doesn't matter.

A lot of applications accept and display URLs with unallowed characters in them, however. Which means *people* can see and enter URLs with spaces and other characters in them. So we have to decide; what is `url parse` supposed to handle? Is it URLs "on-the-wire", or URLs as people enter them? Either is a reasonable choice.

1. If we're handling URLs strictly by the book, then `url parse` should be assuming that its input is *already* percent-encoded (it would in fact probably be most convenient to *decode* its input so that the record returned allows inspection of the "real" contents of the URL parts, not their encoding).
2. If we're assuming that `url parse` is given unencoded "human friendly" URLs (which are not well specified), then we do need to accept things like spaces and non-ASCII characters. But in that case why are we encoding them? Encoding is what is done to guarantee that URL parts can be faithfully transmitted as an unstructured string; when we're parsing it into *structured* data we don't need the encoding.

Either behaviour is fine. What `url parse` accepts currently looks like it's trying to do both, in that it accepts non-allowed characters and percent-encodes some of them (spaces, non-ASCII, `{` and `}`; but not `%` or some ASCII non-allowed characters like `^`), but doesn't percent-encode `%` itself because that would totally destroy the ability to accept "real" URLs that are already percent encoded. But then `url join` assumes that none of its input needs percent-encoding, which means that things like this happen:

```
❯ "https://example.com/foo% bar" | url parse | url join
https://example.com/foo%%20bar?
```

If we're helpfully accepting a technically-invalid human-friendly URL, it should either end up as its original `https://example.com/foo% bar` or it should end up as the encoded form `https://example.com/foo%25%20bar`. `https://example.com/foo%%20bar` is neither human-readable nor technically-correct. It's justifiable only by saying "parsing that was undefined behaviour in the first place, so garbage in garbage out".

So I think `url parse` is the wrong place for any percent-encoding to happen. It makes sense to percent-*decode* there (as we already do for the `params` sub-record). If we want to percent-encode things so that we guarantee we produce valid URLs, the right place to do that is in `url join` (and we need to at least do that for the `params` sub-record before checking it matches the `query` string field; we currently barf on roundtripping something as simple as `https://example.com/?say=hello+world`). (The spec even says "Under normal circumstances, the only time when octets within a URI are percent-encoded is during the process of producing the URI from its component parts.")

I think if `url parse` *decoded* (but also accepted non-allowed characters as representing themselves, as well as reserved characters used in positions where they match a reserved purpose like a `%` not followed by two hex digits) and `url join` *encoded*, then we would have:

1. `url parse | url join` is an identity for by-the-book URLs
2. `url parse | url join` produces a by-the-book encoding of the original URL, even if it used invalid characters (so long as it wasn't so invalid that the parsing was ambiguous)
3. `url join | url parse` would also be an identity, for records containing all the fields produced by `url parse` (and when `query` was consistent with `params)
4. `url parse | do-some-transformation-on-URL-pieces | url join` would mean the inner transformation could reliably work with the "real" decoded data, and not have to have any special handling for percent-encoding or non-allowed or reserved characters

Does that sound right? I think these would all be nice properties to have. I can also imagine *wanting* to access the components in percent-encoded form though, so flags to disable the default encoding would be ideal.

(Sorry this got so long; it turned out to be a way more complicated topic than I had realised once I started thinking it through in depth!)

**Comment by cumber** [comment]
@gdhuper The quick fix is probably fine for most practical cases. It's technically still "wrong", as now `"https://example.com?" | url parse | url join` will produce `"https://example.com"`, and the spec says they are different URLs. I'm not aware of any case where it would actually matter in practice, though.

Continuing to use an empty string to represent a missing query string means that these cases can't actually be distinguished, so it's impossible to get completely right. So my preference would be to use null. But probably it would be reasonable to just release the quick fix, and then do a more thorough overhaul as an enhancement later.

Re the username and password thing, yeah probably the best thing to do would be to treat the user-information part as a monolithic string (just return everything up to the `@` in one field). I'd maybe consider having the single field be something new (`user`? `userinfo`?) rather than the existing `username`, so that any scripts that *were* relying on the previous behaviour noisily break and get updated?

**Comment by gdhuper** [comment]
@cumber I agree that "https://example.com?" and "https://example.com" are two different URLs but the if you execute `"https://example.com?" | url parse` you get 
<img width="148" alt="image" src="https://github.com/nushell/nushell/assets/11465335/57f88c9d-8a26-4705-a185-1de79856cf6e">

As you mentioned, this isn't probably a practical scenario and isn't worth changing the functionality of `parse` and `join` commands. However, I will add the null checks to differentiate between whitespace and null values.

For the username and password, I will open a separate issue as it might require more participation and input from the community.

**Comment by cumber** [comment]
@gdhuper Separate issue for the username/password is a good idea. I should make a separate one for my ideas for a general encoding/decoding overhaul too.

The only real practical issues I've had are:

1. `https://example.com` getting an extra `?`
2. Silently dropping the username when there isn't a password
3. `url join` just outright failing when it thinks `params` doesn't match `query` but both were produced by `url parse`

You've fixed the first, new issue for the second, should the third be in scope here or make a new issue?

**Comment by cumber** [comment]
@gdhuper I'm not sure I followed your `"https://example.com/?" | url parse` example. Was your image of just the `params` part? Empty record has the same problem as empty string; there's no way to distinguish between the URL part being absent and it being empty.

`url join` currently does not accept `null` as a value for `params` (it does for `query`); in its input language the way to represent a URL without a query string is to just not have the `query` or `params` fields in the record. That's okay, but it's not the format that `url parse` produces since it always provides a value for all fields. If we want to preserve the distinction between `https://example.com?` and `https://example.com`, then either there needs to be possible values for `query` and `params` that allow us to tell the difference (so the types of those fields become looser; "null or string" and "null or arbitrary record"), or `url parse` needs to not always emit every field. I assume that we'd rather keep the output fields of `url parse` predictable.

**Comment by gdhuper** [comment]
@cumber yes it was just the params part. I fixed the command in my previous comment.

**Comment by cumber** [comment]
@gdhuper Yeah, it depends on what we want `url parse` and `url join` to do.

I assumed it was giving us the `query` string "as-is", while `params` represents a for-convenience decoding into key-value pairs (which after all is actually *not* part of the spec for URLs; query strings have no mandated structure, it's just a very common structure that is used). In the for-convenience `params` field, it doesn't make a lot of sense to me to decode the `=` and `&` structure and *not* decode the percent-encoding. So my interpretation was this was reasonable behaviour for `url parse` and it's `url join` that is incorrectly reporting they don't match (it's re-encoding the `=` and `&` structure, so why not also re-encode the percent-encoding?).

**Comment by cumber** [comment]
Thanks @gdhuper for getting this fix so quickly!
