### ISSUE TITLE
Built-in command is-admin does not work

### ISSUE THREAD

**Issue by DarkPark** [nushell/nushell#9348]
### Describe the bug

There is a command `is-admin`
https://www.nushell.sh/commands/docs/is-admin.html
but the provided example fails:

```
Error: nu::shell::cant_convert

  × Can't convert to bool.
   ╭─[entry #1:1:1]
 1 │ if is-admin { "iamroot" } else { "iamnotroot" }
   ·    ────┬───
   ·        ╰── can't convert string to bool
   ╰────
```

### How to reproduce

exec `if is-admin { "iamroot" } else { "iamnotroot" }`

### Expected behavior

`iamroot` or `iamnotroot`

### Screenshots

![image](https://github.com/nushell/nushell/assets/1189578/0c005db4-ed85-4ae8-91d3-558ad804264b)

### Configuration

```
| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.80.0                                   |
| branch             |                                          |
| commit_hash        | 8695b575848d5eb4d688087aa9e906b4d9e7c8d8 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.67.1 (d5a82bbd2 2023-02-07)      |
| rust_channel       | 1.67.1-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.67.1 (8ecd4f20a 2023-01-10)      |
| build_time         | 2023-05-16 22:25:05 +00:00               |
| build_rust_channel | release                                  |
| features           | default, zip                             |
| installed_plugins  |                                          |
```

**Comment by DarkPark** [comment]
`if ( is-admin ) { "iamroot" } else { "iamnotroot" }`
seems it works

**Comment by fdncred** [comment]
yes, this is by design, you have to have `is-admin` in parens here to tell nushell to evaluate what's between them. it's not a variable, it's a command, so any command, used in this manner, would need parens as well.

**Comment by DarkPark** [comment]
This issue shouldn't be just closed.
You clearly have wrong documentation.
Sure you can left it as it is but no wonder when in a year half of your documentation will be invalid.

**Comment by fdncred** [comment]
there's a PR up to fix the example and the docs will be fixed when we regenerate them. welcome to pre-1.0 code.
