### ISSUE TITLE
Docker $(pwd) support

### ISSUE THREAD

**Issue by ulvido** [nushell/nushell#9351]
### Related problem

cant write $(pwd) for docker commands. got `expected valid variable name`
it works in zsh as seen below.

![image](https://github.com/nushell/nushell/assets/27722274/df975bca-b97a-4f59-8c19-50a0258981db)

### Describe the solution you'd like

able to write `$(pwd)` or `$(id -u)`, `$(id -g)` etc.

### Describe alternatives you've considered

N/A

### Additional context and details

N/A

**Comment by fdncred** [comment]
Nushell is not posix/bash/zsh compatible so you cannot use that syntax as nushell considers it invalid. 

I don't use docker so can't suggest a lot of options but `$(pwd):/data` is invalid nushell syntax. Maybe something like `$"($env.PWD):/data"`?

**Comment by ulvido** [comment]
`$"($env.PWD):/data"` this worked. typed `$(id -u)` part manually. thank you.
