### ISSUE TITLE
`to nuon` and `to json` won't serialize deeply-structured data, e.g `$nu`

### ISSUE THREAD

**Issue by bobhy** [nushell/nushell#9354]
### Describe the bug

Seems like `to nuon` and `to json` can't handle  too large or too complex data structures.  The error I'm getting (from `to nuon` at least) is about  `list<any>`, but it *can* handle shorter lists.

I think the core issue is lack of *scalability* of these commands, compounded by some not-quite-right error messages.

### How to reproduce

```
〉$nu.scope.commands | to nuon
Error: nu::shell::cant_convert

  × Can't convert to NUON.
   ╭─[entry #58:1:1]
 1 │ $nu.scope.commands | to nuon
   ·                      ───┬───
   ·                         ╰── can't convert list<any> to NUON
   ╰────


〉$nu.scope.commands | take 3|  to nuon
[[name, module_name, category, signatures, usage, examples, is_builtin, is_sub, is_plugin, is_custom, is_keyword, is_extern, creates_scope, extra_usage, search_terms]; [admin_segment, "", default, {any: [[parameter_name, parameter_type, syntax_shape, is_optional, short_flag, description, custom_completion, parameter_default]; [null, input, any, false, null, null, null, null], [null, output, any, false, null, null, null, null]]}, "The prompt indicators are environmental variables that represent
the state of the prompt
color prompt with admin status", [], false, false, false, true, false, false, false, "", ""], [alias, "", core, {nothing: [[parameter_name, parameter_type, syntax_shape, is_optional, short_flag, description, custom_completion, parameter_default]; [null, input, nothing, false, null, null, null, null], [name, positional, string, false, null, "name of the alias", "", null], [initial_value, positional, "\"=\" expression", false, null, "equals sign followed by value", "", null], [null, output, nothing, false, null, null, null, null]]}, "Alias a command (with optional flags) to a new name.", [[description, example, result]; ["Alias ll to ls -l", "alias ll = ls -l", null]], true, false, false, false, true, false, false, "This command is a parser keyword. For details, check:
  https://www.nushell.sh/book/thinking_in_nu.html", "abbr, aka, fn, func, function"], [all, "", filters, {list<any>: [[parameter_name, parameter_type, syntax_shape, is_optional, short_flag, description, custom_completion, parameter_default]; [null, input, list<any>, false, null, null, null, null], [predicate, positional, "closure(any, int)", false, null, "a closure that must evaluate to a boolean", "", null], [null, output, bool, false, null, null, null, null]], table: [[parameter_name, parameter_type, syntax_shape, is_optional, short_flag, description, custom_completion, parameter_default]; [null, input, table, false, null, null, null, null], [predicate, positional, "closure(any, int)", false, null, "a closure that must evaluate to a boolean", "", null], [null, output, bool, false, null, null, null, null]]}, "Test if every element of the input fulfills a predicate expression.", [[description, example, result]; ["Check if each row's status is the string 'UP'", "[[status]; [UP] [UP]] | all {|el| $el.status == UP }", true], ["Check that each item is a string", "[foo bar 2 baz] | all {|| ($in | describe) == 'string' }", false], ["Check that all values are equal to twice their index", "[0 2 4 6] | enumerate | all {|i| $i.item == $i.index * 2 }", true], ["Check that all of the values are even, using a stored closure", "let cond = {|el| ($el mod 2) == 0 }; [2 4 6 8] | all $cond", true]], true, false, false, false, false, false, false, "", "every, and"]]
```

`to json` shows same behavior, but seems to have an additional problem in producing a good error message:
```
〉$nu.scope.commands | to json
Error:   × my custom error message


```

### Expected behavior

I'd like both commands to scale better!  They both seem to be able to handle the interesting datatypes.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.80.1                                   |
| branch             | duration                                 |
| commit_hash        | 699d648dc548dc76aba44adf6b4020865ba00eb4 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)      |
| rust_channel       | 1.68.2-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)      |
| build_time         | 2023-06-04 03:18:56 -04:00               |
| build_rust_channel | debug                                    |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

### Additional context

I'm looking for a universal object serde solution for  nushell, like "pickle" in python.
`to json` and `to nuon` are a good starting places.  Once these scalability issues are fixed, we'd have to think about an extended output format to serialize the variable name and type along with the data.

**Comment by weirdan** [comment]
Neither `to json` nor `to nuon` fail anymore with `scope commands | to ...`

**Comment by sholderbach** [comment]
Really curious which change unlocked that (0.93.0 still failed with it)
