### ISSUE TITLE
Add Simpler Way to Convert List of Keys and Values into Record

### ISSUE THREAD

**Issue by stellarpower** [nushell/nushell#9380]
### Related problem

I'm trying to append a list of values onto a table I opened from a CSV file. It seems I can't append it easily as the data is a list and not a record.

I have a list of headers, and thus I want to convert a (possibly zipped) list of header names and values into a record.
```nushell
let headers = [ name age size species ] 
let values  = [ Sid  17  big  cat     ] 
```

I've spent a couple of hours looking this up online and asked on the Discord server, and whilst I finally got a workable solution:
```nushell
$headers | zip $values |  each { |pair| {$pair.0: $pair.1} } | into record | flatten  
```

I feel there should probably be an easier way to perform this (or I don't see it documented if there already is one, so it perhaps should be added to the section [Working with Lists](https://www.nushell.sh/book/working_with_lists.html) or [Working with Tables](https://www.nushell.sh/book/working_with_tables.html)), especially as it took a long time to find it and make it workable. I have managed to rework the original suggestion I was given from discord into the above, which is a bit more terse, but without flattening the default behaviour of making a table with empty values can be a bit confusing for newcomers and made it difficult to find a workable solution:
```nushell
$headers | zip $values |  each { |pair| {$pair.0: $pair.1} }                                 
╭───┬──────┬─────┬──────┬─────────╮
│ # │ name │ age │ size │ species │
├───┼──────┼─────┼──────┼─────────┤
│ 0 │ Sid  │ ❎  │  ❎  │   ❎    │
│ 1 │  ❎  │  17 │  ❎  │   ❎    │
│ 2 │  ❎  │ ❎  │ big  │   ❎    │
│ 3 │  ❎  │ ❎  │  ❎  │ cat     │
╰───┴──────┴─────┴──────┴─────────╯
```

### Describe the solution you'd like

I think turning a list of Key-Value pairs into a hash/object/record/etc. is a pretty common task for data wrangling tasks. In order to make things easy for newcomers to nushell, I'd like to suggest first-class support for it in the language. For example, Ruby has `[headers, values].transpose.to_h`

 So I therefore think something simple like 
`[ $headers , $values ] | into record `
or
`[ $headers , $values ] | zip --to-record `

would make this common task easy and support beginners in the language.

I understand the first already performs something different and would break existing code, so is not a feasible suggestion, but I'm not sure what would be the most appropriate and idiomatic name for the command, and wanted to emphasise the simplicity. This is a pretty common task, and as a newcomer, when relatively straightforward tasks are difficult to find a solution for, it makes it harder to justify spending time on a new language/tool, which is a shame as nushell has lots of great features I would really like to use.

### Describe alternatives you've considered

None other than those above, I leave it open to those more experienced to suggest options.

**Comment by stellarpower** [comment]
Thanks, I think that works. I am sure there are many ways to achieve it, but, for me nushell at times has been quite a steep learning curve, with many aspects not immediately transferring from other shells or other programming languages. I wouldn't have got this myself, or the one from Discord, without having plenty of experience already, so I still think either adding a new command somewhere that achieves this (or similar things like it) a bit more simply, or if not adding some more one-liners like this and an explanation of what they're doing to the documentation, would be a help.

**Comment by amtoine** [comment]
@stellarpower 
these are good points :+1: 

what about adding this to the standard library as a subcommands of [`std iter`](https://github.com/nushell/nushell/blob/main/crates/nu-std/std/iter.nu)?

**Comment by stellarpower** [comment]
Thanks!

I have not ventured far enough to use the stdlib yet, but that sounds like it would be an appropriate place to put this, so anything like that would get my vote of support.

**Comment by amtoine** [comment]
> Thanks!
> 
> I have not ventured far enough to use the stdlib yet, but that sounds like it would be an appropriate place to put this, so anything like that would get my vote of support.
>
amazing, i'll mark this with https://github.com/nushell/nushell/labels/std-library then and probably as a https://github.com/nushell/nushell/labels/good%20first%20issue as there are already a few ideas here about how to solve this :wink:

**Comment by AstrickHarren** [comment]
I think a way to make it more user friendly will be to allow 
```nu
let headers = [name age] 
let values = [Sid 17]
[$headers; $values]
```
just like how we will make a normal table with `[[name age]; [Sid 17]]`. 

For 
> I think turning a list of Key-Value pairs into a hash/object/record/etc. is a pretty common task for data wrangling tasks. In order to make things easy for newcomers to nushell

I think a key value pair already behave like a record: 
```nu
> let key_value_pair1 = {name: Sid, age: 17}
> let key_value_pair2 = {name: Cat, age: 19}
> $key_value_pair1 | append $key_value_pair2

╭───┬──────┬─────╮
│ # │ name │ age │
├───┼──────┼─────┤
│ 0 │ Sid  │  17 │
│ 1 │ Cat  │  19 │
╰───┴──────┴─────╯

**Comment by stellarpower** [comment]
That's a good point thanks; I do remember trying that and so assume it wasn't parseable. That would be a nice simple, and consistent, way to achieve this.
