### ISSUE TITLE
`armv7` and `riscv64gc` targets release failed

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#9383]
### Describe the bug

The `riscv64gc-unknown-linux-gnu` and `armv7-unknown-linux-gnueabihf` release target build failed for Nu v0.81, detailed output could be found here: https://github.com/hustcer/nu-release/actions/runs/5206601207/jobs/9393333135 and https://github.com/hustcer/nu-release/actions/runs/5206601207/jobs/9393333205. They worked fine for Nu v0.80 and before.

### How to reproduce

Described as above

### Expected behavior

`riscv64gc-unknown-linux-gnu` and `armv7-unknown-linux-gnueabihf` release targets should be built successfully

### Configuration

| key                | value                                                                                       |
| ------------------ | ------------------------------------------------------------------------------------------- |
| version            | 0.81.0                                                                                      |
| branch             | main                                                                                        |
| commit_hash        | 5c81bcef1a3c1667468c81ef8c06cf56a0962133                                                    |
| build_os           | macos-x86_64                                                                                |
| build_target       | x86_64-apple-darwin                                                                         |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)                                                         |
| rust_channel       | 1.68.2-x86_64-apple-darwin                                                                  |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)                                                         |
| build_time         | 2023-06-07 10:49:51 +08:00                                                                  |
| build_rust_channel | release                                                                                     |
| features           | dataframe, default, sqlite, trash, which, zip                                               |
| installed_plugins  | from eml, from ics, from ini, from vcf, gstat, inc, query, query json, query web, query xml |

### Additional context

Maybe related: https://github.com/simd-lite/value-trait/pull/33

**Comment by fdncred** [comment]
it would be nice to build all targets in a nightly release build. i've seen some ci's that have nightlies that use 1 nightly release and continually update the same release with different build assets each night, so there isn't like a new nightly release. all the old ones get overwritten.

**Comment by hustcer** [comment]
dupe of https://github.com/nushell/nushell/issues/9388
