### ISSUE TITLE
help: No such file or directory (os error 2) while launched as default on Mac OS

### ISSUE THREAD

**Issue by lexa2hk** [nushell/nushell#9384]
## Problems if I run nu as default shell in Terminal apps
![image](https://github.com/nushell/nushell/assets/32361833/fc0774e7-a6c2-4dc8-ad79-ab483a2b8dc8)

While launched like default terminal in ITerm2 and Terminal.app:
![image](https://github.com/nushell/nushell/assets/32361833/243ede54-2e12-446d-bb0e-6799cf903042)

And if I run Nushell as `nu` or `/usr/local/bin/nu` everything works as planned. What should I do?

**Comment by fdncred** [comment]
Like most other shells, you need to setup your PATH so that the commands that you want to run are in your PATH. https://www.nushell.sh/book/configuration.html#path-configuration.

When you run nu from another shell, like zsh, it inherits how you've setup your path in zsh.

**Comment by amtoine** [comment]
agree with @fdncred :+1: 

@lexa2hk 
please let us know if adding the path to the `brew` executable to `$env.PATH` in your `env.nu` was enough :relieved:

**Comment by WindSoilder** [comment]
I think it's answered. So I'll close the issue for now, feel free to re-open it if you still have questions
