### ISSUE TITLE
Files in directories with opening bracket cant be interacted with

### ISSUE THREAD

**Issue by ghost** [nushell/nushell#9386]
### Describe the bug

inside a directory containg a opening bracket (`[`) a bunch of commands fail: `cp`, `ls`, `rm`, etc

Examples:
`[]/1.flac`:
```
Error:
  × Error extracting glob pattern
   ╭─[entry #72:1:1]
 1 │ ls
   · ─┬
   ·  ╰── Pattern syntax error near position 22: invalid range pattern
   ╰────
```
`[a]/1.flac`, `[1-2]/1.flac`, `[1B-1.1]`
```
Error:
  × No matches found for *
   ╭─[entry #95:1:1]
 1 │ ls
   · ─┬
   ·  ╰── Pattern, file or folder not found
   ╰────
  help: no matches found
```
`[/1.flac`
```
Error:
  × Error extracting glob pattern
   ╭─[entry #130:1:1]
 1 │ ls
   · ─┬
   ·  ╰── Pattern syntax error near position 22: invalid range pattern
   ╰────
```

no problems: `{}`, `()`, `a b`, `]`

### How to reproduce

```nu
mkdir '[]'
cd '[]'
ls  # works
touch 1.flac
ls # fails
rm '1.flac'  # fails
```

### Expected behavior

It should run the command

### Configuration

| key                | value                                                   |
| ------------------ | ------------------------------------------------------- |
| version            | 0.81.0                                                  |
| branch             |                                                         |
| commit_hash        | 5c81bcef1a3c1667468c81ef8c06cf56a0962133                |
| build_os           | linux-x86_64                                            |
| build_target       | x86_64-unknown-linux-gnu                                |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)                     |
| rust_channel       | 1.68.2-x86_64-unknown-linux-gnu                         |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)                     |
| build_time         | 2023-06-06 22:55:22 +00:00                              |
| build_rust_channel | release                                                 |
| features           | default, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  |                                                         |

(fresh ubuntu vm with empty config and env)

**Comment by fdncred** [comment]
If you're interested in a fix for this, could you please test https://github.com/nushell/nushell/pull/9416 and let me know how it goes?
