### ISSUE TITLE
Add something like `HIST_IGNORE_SPACE`

### ISSUE THREAD

**Issue by wucke13** [nushell/nushell#9387]
### Related problem

I'd like to not put dangerous commands (`rm ...`, `dd` etc.) into my history, as to not accidentally recall them later. In `zsh`, there is a new option which simply exempts commands prefixed with a space from being added to the history/history file. So wile `rm -rf *` goes to the history, ` rm -rf *` does not.

I would really like having this in nushell as well!

### Describe the solution you'd like

Add a configuration parameter to enable the same behavior as `HIST_IGNORE_SPACE`

**Comment by amtoine** [comment]
looks like a duplicate of #6886 which is addressed in #9371 :ok_hand: [

**Comment by sholderbach** [comment]
@wucke13 would you be satisfied by the configless behavior we landed with #9371

**Comment by wucke13** [comment]
Yeah, that is exactly what I wanted. Thank you all!
