### ISSUE TITLE
Examining alternative hashing algorithms

### ISSUE THREAD

**Issue by FilipAndersson245** [nushell/nushell#9390]
### Question

Hello, thought we could improve performance somewhat by using a faster hashing algorithm for nushell, i did some initial testing by using `aHash` instead of the default and running `cargo bench` gave some nice improvements in the parser, upwards of 15% faster when running `parse_default_config_file`
i submit some images and await response if this is something we should maybe consider using.

![image](https://github.com/nushell/nushell/assets/17986183/da555657-1051-4eb4-b43a-d538795a7fc8)
![image](https://github.com/nushell/nushell/assets/17986183/fb5ffe96-731a-4725-ba61-5cc047ead8b4)
![image](https://github.com/nushell/nushell/assets/17986183/d52eecb8-d911-480f-ac7c-67d8760dc14d)
![image](https://github.com/nushell/nushell/assets/17986183/cfaa29f3-3e5b-4cdb-bd5b-3d044177c0e7)

The json and msgpack tests was quite noisy so i did not include those here.

**Comment by fdncred** [comment]
I'm up for faster!
