### ISSUE TITLE
Regression in find command

### ISSUE THREAD

**Issue by VlkrS** [nushell/nushell#9394]
### Describe the bug

With nushell 0.81 the find command seems to generate puzzling results - please see "How to reproduce" for a simple example.

### How to reproduce

Setup:

```
$ mkdir test
$ cd test
$ touch file_a
$ touch file_b
$ touch file_c
```

This works as expected:

```
$ ls | find file_a

╭───┬────────┬──────┬──────┬──────────────╮
│ # │  name  │ type │ size │   modified   │
├───┼────────┼──────┼──────┼──────────────┤
│ 0 │ file_a │ file │  0 B │ a minute ago │
╰───┴────────┴──────┴──────┴──────────────╯
```

This messes up columns, and highlights file_a in column name, and file_b in column type:

```
$ ls | find file_a file_b

╭───┬────────┬────────┬──────┬──────────╮
│ # │  name  │  type  │ size │ modified │
├───┼────────┼────────┼──────┼──────────┤
│ 0 │ file_a │ file_a │ file │ file     │
│ 1 │ file_b │ file_b │ file │ file     │
╰───┴────────┴────────┴──────┴──────────╯
```

Same here, only the highlights are switched:

```
$ ls | find file_b file_a                                                                                                         
╭───┬────────┬────────┬──────┬──────────╮
│ # │  name  │  type  │ size │ modified │
├───┼────────┼────────┼──────┼──────────┤
│ 0 │ file_a │ file_a │ file │ file     │
│ 1 │ file_b │ file_b │ file │ file     │
╰───┴────────┴────────┴──────┴──────────╯
```

This messes up columns even more, and does not even highlight file_f:

```
$ touch file_d file_f
$ ls | find file_b file_a file_c file_d file_f                                                                                    
╭───┬────────┬────────┬────────┬──────────╮
│ # │  name  │  type  │  size  │ modified │
├───┼────────┼────────┼────────┼──────────┤
│ 0 │ file_a │ file_a │ file_a │ file_a   │
│ 1 │ file_b │ file_b │ file_b │ file_b   │
│ 2 │ file_c │ file_c │ file_c │ file_c   │
│ 3 │ file_d │ file_d │ file_d │ file_d   │
│ 4 │ file_f │ file_f │ file_f │ file_f   │
╰───┴────────┴────────┴────────┴──────────╯
```

### Expected behavior

Same example run in nushell 0.76.0:

```
$ ls | find file_b file_a file_c file_d file_f                                                                                    
╭───┬────────┬──────┬──────┬────────────────╮
│ # │  name  │ type │ size │    modified    │
├───┼────────┼──────┼──────┼────────────────┤
│ 0 │ file_a │ file │  0 B │ 10 minutes ago │
│ 1 │ file_b │ file │  0 B │ 10 minutes ago │
│ 2 │ file_c │ file │  0 B │ 10 minutes ago │
│ 3 │ file_d │ file │  0 B │ 4 minutes ago  │
│ 4 │ file_f │ file │  0 B │ 4 minutes ago  │
╰───┴────────┴──────┴──────┴────────────────╯
```

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.81.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | openbsd-x86_64                                                    |
| build_target       | x86_64-unknown-openbsd                                            |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16) (built from a source tarball) |
| cargo_version      | cargo 1.69.0                                                      |
| build_time         | 2023-06-09 11:36:29 +00:00                                        |
| build_rust_channel | release                                                           |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by fdncred** [comment]
Yup, you're right. Something recently messed this up. One of the examples is this `ls | find toml md sh` and it doesn't work right anymore either.
