### ISSUE TITLE
Should ps in nushell be renamed nups, after all, ps commands on Linux are too common

### ISSUE THREAD

**Issue by Silentdoer** [nushell/nushell#9400]
### Related problem

like title

### Describe the solution you'd like

rename ps in nushell with nups by default

**Comment by fdncred** [comment]
Nushell is cross-platform so we have to keep all platforms we support in mind.

**Comment by amtoine** [comment]
also, we have the `^cmd` which calls `cmd` as an external, such that
- `ps` is the Nushell implementation
- `^ps` is always the system `ps` command

:thumbsup:

**Comment by jntrnr** [comment]
Right, we wouldn't rename `ls`, `cp`, etc. So it doesn't really make sense to do so for `ps` since its intention is to be the nushell crossplatform equivalent. Using `^ps` is the suggested change, and I believe you can do `alias ps = ^ps` to only use the local one.

**Comment by amtoine** [comment]
so i think we should close this for now :relieved:

**Comment by amtoine** [comment]
so i think we should close this for now :relieved:
