### ISSUE TITLE
Migration to sqlite history

### ISSUE THREAD

**Issue by DarkPark** [nushell/nushell#9403]
### Question

I've started to use nushell and moving my aliases and history to it.
Everything seems went well but I've discovered that saving history in sqlite format gives more opportunities and switched to it.
And lost all my history entries. Yes I know the file `history.txt` is still there but in nushell I started with a clean slate.
Ideally it would be nice to migrate my txt history to sqlite db on switching.
Alternatively to have a one-line command in documentation to do it manually.
You have `query db` command but I can't find a way to pipe my history to it.
Something like this:
`open history.txt | lines | each { [prepare sql inserts here] } | str join "\n" | open $nu.history-path | query db`

**Comment by fdncred** [comment]
I've definitely seen such things in discord.

This is not what you're looking for but this shows how one can update the history db.
```
open $nu.history-path | query db "delete from history where exit_status is not 0"
```

If you come up with a sql command, feel free to add it to docs.

**Comment by DarkPark** [comment]
Here is my solution:
1. Prepare migration sql in a file `~/.config/nushell/history.sql` with
`open ~/.config/nushell/history.txt | lines | each { |line| "INSERT INTO history (command_line, start_timestamp, session_id, hostname, cwd, duration_ms, exit_status) VALUES ('" + ($line | str replace --all "'" "''") + "', 0, 0, '" + (hostname) + "', '/', 0, 0" + ");" } | str join "\n" | save -f ~/.config/nushell/history.sql`
2. Execute generated sql with external binary `sqlite3` preferably not inside nushell (db may be locked):
`cat ~/.config/nushell/history.sql | sqlite3 ~/.config/nushell/history.sqlite3`

**Comment by amtoine** [comment]
@DarkPark 
does your message above solve the migration issue? :yum:

**Comment by DarkPark** [comment]
@amtoine yes, you can say that
just had to finish the job without nushell which is rather disappointing
nushell in general can work with sqlite db but not good enough

**Comment by fdncred** [comment]
seems like you could've iterated through your history.sql in nushell and used the `query db` command to insert each row instead of using sqlite3. i'm guessing that the sqlite3 method would be more efficient though. 

we used to have a lot of db commands that were more nushell-y, but they got removed because someone didn't like them.

**Comment by DarkPark** [comment]
@fdncred can you please scribble down some example?

**Comment by fdncred** [comment]
Here's a few PRs that show what/how Fernando did.

https://github.com/nushell/nushell/pull/6217
https://github.com/nushell/nushell/pull/5466
https://github.com/nushell/nushell/pull/5417
https://github.com/nushell/nushell/pull/5343
https://github.com/nushell/nushell/pull/5307

**Comment by DarkPark** [comment]
@fdncred thank you, these are interesting features but they don't illustrate what I need
they are all about workflow inside db but I'm interested in mixing in some other data source (another file content)

**Comment by fdncred** [comment]
Theoretically you could do things like `open some.sqlitedb` and `open some.csv` and use things like the `join` command to work together.

Those PRs were just trying to show how we use to have db-type commands specifically for sqlite so you didn't really need to use sql syntax, that's all. I kind of wish we still had it.

**Comment by DarkPark** [comment]
Seems join can do simple merging two sources or I can't see the way it can help.
Anyway my not so simple approach works.
Maybe it would help somebody else an it worth to put it somewhere in docs?

**Comment by ofek** [comment]
FYI for those who might benefit: the command above to create the SQL file takes at least 20 minutes (I stopped at that point) on a good machine for approximately 50,000 lines. I instead used the following Python script (on Windows) which completes almost instantly:

```python
HISTORY_FILE = r'C:\Users\ofek\AppData\Roaming\nushell\history.txt'
SQL_FILE = r'C:\Users\ofek\AppData\Roaming\nushell\history.sql'

def main():
    with open(HISTORY_FILE, 'r', encoding='utf-8') as fi, open(SQL_FILE, 'w', encoding='utf-8') as fo:
        for command in fi:
            command = command.strip().replace("'", "''")
            if command:
                fo.write(f"INSERT INTO history (command_line, start_timestamp, session_id, hostname, cwd, duration_ms, exit_status) VALUES ('{command}', 0, 0, 'ozone', 'C:\\Users\\ofek\\Desktop', 0, 0);\n")

if __name__ == '__main__':
    main()
```

**Comment by NotTheDr01ds** [comment]
Was looking for a good spot to document my process, and this looks like it.  The addition of `stor` makes this easier.  I just imported the (pretty empty, for me) `history.sqlite3` into memory using `stor import`, added each `history.txt` item to it with `stor insert`, renamed the on-disk `history.sqlite3` and related files, and `stor export`'d.

About 22,000 lines converted almost instantaneously.

```Nushell
> cd $nu.default-config-dir
> stor import --file-name history.sqlite3
> for line in (open history.txt | lines) {
        let command_line = ($line | str replace --all "'" "''" | str replace --all '<\n>' "\n")
        stor insert --table-name history --data-record { command_line: $command_line }
  }
> let dateStr = (date now | format date "%F-%H-%M-%S")
> for f in (ls history.* | get name) {
        let ext = ($f | path parse | get extension)
        let newName = $"history-($dateStr).($ext)"
        mv $f $newName
        print $"($f): renamed to ($newName)"
  }
> stor export --file-name history.sqlite3
```

**Comment by fdncred** [comment]
@NotTheDr01ds That's great! However, you will probably need to create some indexes too so that the sqlite history db doesn't slow down.
This is what the schema looks like. You can see the indexes we have by default. Also, the sequence.
![image](https://github.com/nushell/nushell/assets/343840/2a948117-439b-4637-98dd-c414418a7c9c)

**Comment by NotTheDr01ds** [comment]
@fdncred  Ah dang - I saw those, but didn't realize I'd lost them on `export`

**Comment by fdncred** [comment]
This is the table creation and indexes from reedline. 
```rust
        db.execute_batch(
            "
        create table if not exists history (
            id integer primary key autoincrement,
            command_line text not null,
            start_timestamp integer,
            session_id integer,
            hostname text,
            cwd text,
            duration_ms integer,
            exit_status integer,
            more_info text
        ) strict;
        create index if not exists idx_history_time on history(start_timestamp);
        create index if not exists idx_history_cwd on history(cwd); -- suboptimal for many hosts
        create index if not exists idx_history_exit_status on history(exit_status);
        create index if not exists idx_history_cmd on history(command_line);
        create index if not exists idx_history_cmd on history(session_id);
        -- todo: better indexes
        ",
        )
```

**Comment by NotTheDr01ds** [comment]
@fdncred Hmm - They are still there for me.  It seems your `stor import` and `stor export` handle importing and exporting the indexes?

**Comment by fdncred** [comment]
whoop! whoop! that would be great if it did!

**Comment by danyx23** [comment]
On windows doing this from within Nushell didn't work for me as the file was locked. I ended up modifying @ofek's solution a bit to deal with multiline commands:

```python
# This migration script is used to convert the history.txt file to a history.sql file that can be imported into the sqlite3 database.
# It is done in python instead of nushell as on windows the history file can be locked while a nushell shell is active.

# Run this script with `python migrate-history.py <config_dir> <hostname>`

import sys
from pathlib import Path

def multiline_command_generator(fi):
    current_command = ""
    for line in fi:
        line = line.strip()
        if not line:
            continue

        line = line.replace("'", "''")
        line = line.replace(" && ", "; ")

        if line.startswith("<\\n>"):
            current_command += "\n" + line[4:]
        else:
            if current_command:
                yield current_command
            current_command = line

    if current_command:
        yield current_command

def main(config_dir: str, hostname):
    text_file = config_dir / "history.txt"
    sql_file = config_dir / "history.sql"
    commandnumber = 0
    with open(text_file, encoding="utf-8") as fi, open(sql_file, "w", encoding="utf-8") as fo:
        for command in multiline_command_generator(fi):
            # I abuse the start_timestamp as a sequence number so the order is preserved
            fo.write(f"INSERT INTO history (command_line, start_timestamp, session_id, hostname, cwd, duration_ms, exit_status) VALUES ('{command}', {commandnumber}, 0, '{hostname}', '/', 0, 0);\n")
            commandnumber += 1

    print(f"Created the sql file at {sql_file} - you can now run it with `open {sql_file.name} | sqlite3 history.sqlite3` in your {config_dir} directory.")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        raise ValueError("Config directory is required as the first argument, hostname as the second.")

    config_dir = Path(sys.argv[1])

    if not config_dir.is_dir():
        raise ValueError(f"{config_dir} is not a valid directory.")

    main(config_dir, sys.argv[2])
```

**Comment by NotTheDr01ds** [comment]
Implemented in #13450 - Thanks @qfel!

**Comment by DKnoto** [comment]
Would it be possible to add two more fields: cpu and memory utilization?

**Comment by fdncred** [comment]
@DKnoto what do you mean? You're wanting to add cpu and memory to each history storage?

**Comment by DKnoto** [comment]
@fdncred I am thinking about something like this, to add a module that implements psrecord functionality. If I were to include it, I would get information in the history about how much cpu and memory a given command consumed during its run. Ideally it would be a definite integral, not a maximum or average.

**Comment by fdncred** [comment]
@DKnoto Our history sqlite db has a column in it called `more_info` which a kind of "reserved for future use" column that I believe would take some type of json. You'd have to look into how it's handled in reedline. You may be able to play around with adding something there, but I doubt we'd allow changing the history database schema for your psrecord idea.

You can see the schema like this
```nushell
open $nu.history-path | schema | get tables | table -e
```

**Comment by DKnoto** [comment]
@fdncred  I understand. In that case, I'll make myself a psrecord command that uses this field.

**Comment by fdncred** [comment]
@DKnoto I'll be interested to see what you come up with. Please share when you're finished.

**Comment by jerrygreen** [comment]
Now that history isolation has become unique feature of `file_format = "sqlite"`, having to choose sqlite just for isolation, – meeh... That's actually fine, but one thing I noticed is that sqlite doesn't import all current history from txt file, which is a little bit unfortunate.

Also, I'd like to know if there's a way in Nushell to edit the history after switching to sqlite. Because previously I sometimes used this possibility, I was clearing history file manually from some unwanted commands sometimes, with simply nano command, sometimes with vscode. I don't know how to do it when sqlite is involved... It will probably require some complex programs for viewing sqlite database etc, which I will definitely won't have on my paspberrypi for example.

I'd love to have some easier option where `sqlite` is synced with `history.txt` if that's possible.

**Comment by weirdan** [comment]
> one thing I noticed is that sqlite doesn't import all current history from txt file,

See `help history import`

> Also, I'd like to know if there's a way in Nushell to edit the history after switching to sqlite [...] It will probably require some complex programs for viewing sqlite database

You can use nushell itself to modify any sqlite database, including nushell's own history:

```nushell
# find the command you want to delete
history -l | where command line '^alias.*' | last 3
# note ids from the `item_id` column
open $nu.history-path | query db "delete from history where id in (123,234,345)"
# restart nushell
exec $nu.current-exe
```

**Comment by ofek** [comment]
Does that final command work on Windows or would that spawn a new, nested subprocess?

**Comment by weirdan** [comment]
I believe on Windows `exec` starts a new nested process but upon return the parent process exits. On MacOS (?) and Linux the new process replaces the old one.

**Comment by jerrygreen** [comment]
> history import

It worked quite nicely, thanks. What if I export my sqlite to txt, then edit txt, then import it again, will it actually replace the old data, or just add it on top? I would setup automatic importing-and-export to keep happening sometimes, and just edit the text file and be happy.

Because I don't quite feel like querying db, not to mention I will clutter my history with kajillion db queries, I would prefer to just edit text file. But I do love that history isolation feature, which only works with the sqlite.

**Comment by weirdan** [comment]
> not to mention I will clutter my history with kajillion db queries

You can avoid this by prefixing the command line with one or more spaces.

> will it actually replace the old data, or just add it on top?

Looking at the code 

https://github.com/weirdan/nushell/blob/e56879e5884e52d6bad717437602fd03072290b1/crates/nu-cli/src/commands/history/history_import.rs#L152-L153

it would appear the entries are added, not replaced. But since there's `history --clear` you should be able to delete everything and import the updated history.
