### ISSUE TITLE
fd command to be added to nushell commands

### ISSUE THREAD

**Issue by Mirage10** [nushell/nushell#9410]
it would be very useful to have the fd (pattern based find/search in dictionary hierarchy) command to nushell commands.
 fd is written in Rust and extremely fast in comparison to ls

it would be nice that fd produces a table with a single column 'name'

examples:
fd -i 'nuhero' /uuu  
fd -i 'nuhero' /uuu | length  
all fd parameters should be accessible as well

for sure, ls / glob is quite general. Nevertheless fd is a ergonomic approach

**Comment by rgwood** [comment]
I think all of the following are true:
1. [fd](https://github.com/sharkdp/fd) is excellent software 
2. `ls` could be faster
3. We're probably not going to bring fd into Nushell. That would add significantly to Nushell's compile times and binary size

We'd welcome issues and PRs for specific improvements to `ls`.

**Comment by fdncred** [comment]
@Mirage10 another option is to submit a PR to `fd` that enables it to output to json. Then nushell could consume that json easily.

**Comment by amtoine** [comment]
> @Mirage10 another option is to submit a PR to `fd` that enables it to output to json. Then nushell could consume that json easily.
>
this is a very good middle-ground idea :ok_hand: :+1:
