### ISSUE TITLE
Expand All PATHs in $env

### ISSUE THREAD

**Issue by guilt** [nushell/nushell#9428]
### Related problem

When I view environment variables with `$env`, only `PATH` is expanded and formatted nicely.

<img width="1239" alt="image" src="https://github.com/nushell/nushell/assets/195178/38102b9a-c43d-4bfb-8c96-182e81e61b5f">

However, other important variables such as `MANPATH` `INFOPATH` `LIB` `LIBRARY_PATH` `LD_LIBRARY_PATH` `DYLD_LIBRARY_PATH` `C_INCLUDE_PATH` `CPLUS_INCLUDE_PATH` `INCLUDE` `PERL5LIB` `PYTHONPATH` could all use the same love.

<img width="1722" alt="image" src="https://github.com/nushell/nushell/assets/195178/d0cbd7e4-a3bd-4dae-be8f-a838de38ad50">

### Describe the solution you'd like

Have a way to expand all these variables, preferable if configured in `config nu` or something. It makes life so much easier to check if a given variable had a certain directory to it or not. Since it is hard to figure out what needs expanding (thousands of toolchains etc.) would prefer a way to configure it like:

`let-env EXPANDED_PATH_VARS = "MANPATH;INFOPATH;SOME_COOL_PATH;EXPANDED_PATH_VARS"`

and that way the shell can interpret them nicely.

**Comment by fdncred** [comment]
If you want C_INCLUDE_PATH or any other path expanded like this, you need to add it to env.nu ENV_CONVERSIONS

**Comment by guilt** [comment]
Perfect! Found this in `config env`

**Comment by fdncred** [comment]
> Is there a way to shrink it?

Only add the things you need. It's repetitive because I only have it do one thing over and over again but you can have the from_string and to_string do anything you can imagine. Someone the other day was asking for a way to transform certain env vars into json when externals are called. This section in env.nu is the solution to that too.

**Comment by guilt** [comment]
The problem is that there are many things and it's like 4 lines per item now. It's harder to maintain this kinda' modularity in a large single file when one is beginning with the shell. But yeah, this conversation has been helpful!
