### ISSUE TITLE
Underscore `_` breaks capture groups references in `str replace` command

### ISSUE THREAD

**Issue by Sygmei** [nushell/nushell#9437]
### Describe the bug

When using an underscore (`_`)  just after a capture group reference in the `replace` parameter of the `str replace` command, nushell becomes unable to reference the capture group properly.

### How to reproduce

```bash
"abc-def" | str replace "(.+)-(.+)" "$1_$2"
```

returns
```
def
```

### Expected behavior

```bash
"abc-def" | str replace "(.+)-(.+)" "$1_$2"
```

should return

```
abc_def
```

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.81.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 5c81bcef1a3c1667468c81ef8c06cf56a0962133                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31) (Arch Linux rust 1:1.70.0-1) |
| cargo_version      | cargo 1.70.0                                                     |
| build_time         | 2023-06-07 08:13:21 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment]
iirc, there's some special syntax for this, like `($1)_($2)` or something similar. It's known and supposed to be this way. You may have to look it up on the regex crate.

**Comment by Sygmei** [comment]
Great, thanks for the explanation :) Didn't see the example before

**Comment by amtoine** [comment]
> Great, thanks for the explanation :) Didn't see the example before
>
i think the doc is lacking on this front, so i've added an example about that precise notion of *captures* :ok_hand:

**Comment by fdncred** [comment]
Thanks for fishing this out of the help @amtoine. I should've looked their first too.
