### ISSUE TITLE
Crash when using ansi escape command starting with '\'

### ISSUE THREAD

**Issue by VoidField101** [nushell/nushell#9448]
### Describe the bug

Using ``ansi -e`` with an parameter starting with ``\`` crashes nu with the following error message:
```
thread 'main' panicked at 'Unexpected missing argument', /home/mfield/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-command-0.80.0/src/platform/ansi/ansi_.rs:704:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Link to the panicking code: https://github.com/nushell/nushell/blob/b14bdd865fc362aca106cac9172799134aeaafd4/crates/nu-command/src/platform/ansi/ansi_.rs#L704

In double quotes passing `ansi -e "\\"` also crashes similar to `ansi -e \b` or or `ansi -e '\b'`. Which could happen for example if a user accidentally swapped single and double quotes. 

### How to reproduce

1. Start nu
2. Run `ansi -e \`, `ansi -e \b` etc. (anything that passes `\` as the first character)
3. Nu crashes 

### Expected behavior

A "normal" error message with a new nu prompt afterwards.

### Configuration

| key                | value                                       |
| ------------------ | ------------------------------------------- |
| version            | 0.80.0                                      |
| branch             |                                             |
| commit_hash        |                                             |
| build_os           | linux-x86_64                                |
| build_target       | x86_64-unknown-linux-gnu                    |
| rust_version       | rustc 1.72.0-nightly (d59363ad0 2023-06-01) |
| rust_channel       | nightly-x86_64-unknown-linux-gnu            |
| cargo_version      | cargo 1.72.0-nightly (f7b95e316 2023-05-30) |
| build_time         | 2023-06-06 10:55:22 +02:00                  |
| build_rust_channel | release                                     |
| features           | default, zip                                |
| installed_plugins  |                                             |

**Comment by fdncred** [comment]
thanks. agreed. invalid things should throw errors, not crash.
