### ISSUE TITLE
Allow input via selection

### ISSUE THREAD

**Issue by robaca** [nushell/nushell#9457]
### Related problem

In bash there is the `select` statement to allow a selection out of a list of entries. Please provide something similar in nushell.

### Describe the solution you'd like

It should be possible to pass lists, records or tables (maybe in multiple development increments) and return a list value, key or column value, maybe even multiple ones 

### Describe alternatives you've considered

Use another cli tool, but that would most probably not be cross-platform, and would have to be installed separately.

**Comment by amtoine** [comment]
@robaca :wave: 

could you pass an example of input / output you'd want?

i do not know what `select` does in Bash :thinking: 

maybe it's our `input list` command? :open_mouth:

**Comment by robaca** [comment]
Hi @amtoine I have overseen the `input list` - only looked at `input` (It would be nice to have the subcommands also listed on the details page of the main commands).

`input list` is exactly what I was searching for.

**Comment by fdncred** [comment]
I think `input list` is on the help page when you type `help input`, isn't it?

**Comment by amtoine** [comment]
> `input list` is exactly what I was searching for.
>
niiice :yum: 
glad Nushell already has what you were looking for out of the box :relieved:
