### ISSUE TITLE
Hide implementation details from nu-plugin public interface

### ISSUE THREAD

**Issue by BrianLondon** [nushell/nushell#9469]
## Background

The `nu-plugin` currently serves multiple purposes. Internal to Nushell it serves as the interface between plugins and Nushell and is used in `nu-parser`. Additionally it provides an API for plugin authors to use for their plugin to communicate with Nushell. Because of this there are some implementation details of Nushell that are leaked to the public interface. Currently this is addressed by hiding those public members from the documentation (See discussion on https://github.com/nushell/nushell/pull/9452).

Additionally the `PluginEncoder`s `MsgPackSerializer` and `JsonSerializer` are used to select the encoding mechanism of a plugin, but these structs are the serializers themselves and none of that serialization functionality needs to exist on the public interface. All that's needed is a flag.

Therefore I propose the following interface changes.

### Remove serializers from `serve_plugin`

I propose to remove `MsgPackSerializer` and `JsonSerializer` from the `nu-plugin` public interface entirely. We can replace `EncodingType` with a simple flag `enum` that resembles the following:

```rust
pub enum EncodingType {
    Json,
    MsgPack,
}
```

Then `serve_plugin` can be called in plugin `main` methods like so:

```rust
fn main() {
   serve_plugin(&mut MyPlugin{}, EncodingType::MsgPack)
}
```

Then in the _internal_ implementation we can select the appropriate serialization functions without exposing the serializers themselves to plugin authors or even to other crates in Nushell. Many of those usages can, in fact, be replaced by static dispatch, which I'd propose to replace as well. This change will effectively ensure that all serialization logic is self-contained to the `nu-plugin` crate.

### Create a separate Nushell internal mod and feature

Some items need to be public because they are used across crate boundaries within Nushell but will never be used by plugin authors. Specifically these items are `get_signature`, `PluginDeclaration`, `PluginResponse`, and `EncodingType`. I propose to move three of these into a separate `nu_internal` mod and hide that behind a `nu-internal` cargo feature -- I suggested repurposing `EncodingType` above.  Then, `lib.rs` will look something like:

```rust
pub use plugin::{serve_plugin, Plugin};
pub use protocol::{EvaluatedCall, LabeledError};
pub use serializers::EncodingType;

#[cfg(feature = "nu-internal")]
pub mod nu_internal {
    pub use crate::plugin::{get_signature, PluginDeclaration};
    pub use crate::protocol::PluginResponse;
}

```

**Comment by sholderbach** [comment]
Thank you very much for the writeup!

Making the interface for plugin authors simpler and more robust (avoiding breaking changes while iterating on the internals) sounds good, and I think your general direction in that aspect sounds reasonable to me.

I am not yet sure if I like the feature flag based approach for the `nu` side of things due to complexity and what feature unification can do for you.

Pinging the core team for folks with more expertise around the `nu-plugin` internals.

(moved over to the main repo as a development focussed issue)

**Comment by BrianLondon** [comment]
Oops, I wrote it in `nushell/nushell.github.io`? Sorry about that and thank you for moving it.

**Comment by sholderbach** [comment]
@devyn your call how far ahead we are on this goal but now we have several somewhat purpose tailored plugin crates to make the distinction between the things we need internally and the plugin authors need externally.

**Comment by devyn** [comment]
I think we can reasonably call this done now.
