### ISSUE TITLE
有没有方法把http 请求json结果转换为record

### ISSUE THREAD

**Issue by lscool66** [nushell/nushell#9478]
### Question

有没有方法把http 请求json结果转换为record
![image](https://github.com/nushell/nushell/assets/16486146/ebf97d2b-535e-4133-8468-8ed6b505532c)

**Comment by aa1ss2** [comment]
命令后面加上   | from json

**Comment by lscool66** [comment]
if ($e.name) =~ "odcbs-auth" {"授权服务进程"} else if ($e.name) =~ "odcbs-portal" {"手麻应用进程"} else if ($e.name) =~ "odbip-portal" {"平台应用进程"} else if ($e.name) =~ "odbip-batch" {"平台批处理进程"} else {"未知服务"}

请问多个if else 请问推荐如何处理

**Comment by hustcer** [comment]
You can use `match` command, see `help match`

**Comment by lscool66** [comment]
> help match

这个是全词匹配，可以模糊匹配吗

**Comment by hustcer** [comment]
Some `match` examples:
```nushell
match $x {
  1..10 => { print "Value is between 1 and 10" }
  { foo: $bar } => { print $"Value has a 'foo' field with value ($bar)" }
  [$a, $b] => { print $"Value is a list with two items: ($a) and ($b)" }
  _ => { print "Value is none of the above" }
}

match {b: 1} { {a: $b} | {b: $b} => { print $b } }
```
Related PR: 
https://github.com/nushell/nushell/pull/8590
https://github.com/nushell/nushell/pull/8633

You can file a separate issue If you want more feature beyond these.
