### ISSUE TITLE
Allow convenient casting of table columns and record fields

### ISSUE THREAD

**Issue by aikow** [nushell/nushell#9480]
### Related problem

I often find myself parsing some sort of text file or json file which does not support the same set of types as nushell does. For example, numbers are often parsed as a string, which I then have to manually convert to an integer using something like

```nu
open file.txt | lines | split column : idx text another_number | update idx { |it| $it.idx | into int } | update another_number { |it| $it.another_number | into decimal }
```

contents of file.txt
```txt
```

This is quite a common pattern, and quite annoying when a table contains a lot of fields that are falsely parsed as strings.

### Describe the solution you'd like

Either add a `cast` command that can convert an entire table column at once, or let `into` take an optional column name..

**Comment by sholderbach** [comment]
The `into` family of commands already accepts column names (more generally "cell path"s) as optional parameters.

```bash
> ls | into string size modified | describe
table<name: string, type: string, size: string, modified: string> (stream)
> ls | describe
table<name: string, type: string, size: filesize, modified: date> (stream)
``` 

https://www.nushell.sh/commands/docs/into_string.html#signature
