### ISSUE TITLE
`exit` always exits nushell, even when not in the last shell.

### ISSUE THREAD

**Issue by Taywee** [nushell/nushell#9486]
### Describe the bug

["Shells in shells"](https://www.nushell.sh/book/shells_in_shells.html) says

> You can leave a shell you have [enter](https://www.nushell.sh/commands/docs/enter.html)ed using the [exit](https://www.nushell.sh/commands/docs/exit.html) command. If this is the last open shell, Nu will quit.

But when I type `exit`, the nushell process always exits.

I've also done a `config reset` and tried again to be sure it wasn't config related, and it still happens.

### How to reproduce

```shell
> enter /tmp
> shells
╭───┬────────┬────────────╮
│ # │ active │    path    │
├───┼────────┼────────────┤
│ 0 │ false  │ /home/home │
│ 1 │ true   │ /tmp       │
╰───┴────────┴────────────╯
>exit
# My terminal closes here
```

### Expected behavior

I expect only the active shell to exit, and nushell to only exit if no active shells are left afterward.

### Configuration

| key                | value                                                      |
| ------------------ | ---------------------------------------------------------- |
| version            | 0.81.0                                                     |
| branch             |                                                            |
| commit_hash        |                                                            |
| build_os           | linux-x86_64                                               |
| build_target       | x86_64-unknown-linux-gnu                                   |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31) (Fedora 1.70.0-1.fc38) |
| cargo_version      | cargo 1.70.0                                               |
| build_time         | 2023-06-19 15:57:54 -06:00                                 |
| build_rust_channel | release                                                    |
| features           | default, sqlite, trash, which, zip                         |
| installed_plugins  |                                                            |

**Comment by fdncred** [comment]
You're right, of course. The docs are out of date again. `dexit` would exit shells now I believe.

**Comment by Taywee** [comment]
Ah, thanks!  That's what I was looking for.  Unfortunately, it looks like `dexit` has a bug, [but the latest commit from 4 days ago](https://github.com/nushell/nushell/commit/86f12ffe619ba8ff6f64a9dc2c9db19a01c2b802) appears to fix it.

**Comment by sholderbach** [comment]
With the updated docs and the fix on main we can close this, right?

**Comment by alexjp** [comment]
btw can this page also include info on `dexit`: https://www.nushell.sh/commands/categories/shells.html#shells ?

it only mentions `exit`

Thanks!!!

**Comment by fdncred** [comment]
that page needs to be updated.
