### ISSUE TITLE
请问有没有格式化代码的vscode插件

### ISSUE THREAD

**Issue by lscool66** [nushell/nushell#9489]
### Question

请问有没有格式化代码的vscode插件
![image](https://github.com/nushell/nushell/assets/16486146/f43f068d-a8ed-4d37-b58d-402cf9b008d4)

我这边都是手动格式化的，看起来不太舒服

**Comment by fdncred** [comment]
There is no formatting yet but the community is working on [nufmt](https://github.com/nushell/nufmt)
