### ISSUE TITLE
Have no history size by default

### ISSUE THREAD

**Issue by efugier** [nushell/nushell#9493]
### Related problem

Slightly related to https://github.com/nushell/nushell/issues/5586, sometimes when upgrading my configs I find myself with opening a shell with the default ones with only 10k entries which deletes part of my nushell history.

### Describe the solution you'd like

No default (or at least way bigger) maximum size for the nushell history.

**Comment by fdncred** [comment]
I don't understand the problem. This PR already sets it to i64::MAX if not specified https://github.com/nushell/nushell/pull/5587/files. And today it's still set that way https://github.com/nushell/nushell/blob/88fdf45a24ccbc982e57eaece3042f1712d3ed02/crates/nu-protocol/src/config.rs#L131-L132

If you use the default_config.nu, it will be set to 10000. Is that what you're saying?

**Comment by efugier** [comment]
Oh I see you got it even before I had time to explain :grin: thanks a lot!
