### ISSUE TITLE
nushell cannot cd to unowned directory

### ISSUE THREAD

**Issue by JakeSiFive** [nushell/nushell#9498]
### Describe the bug

I work on a shared machine. It is often required that I work from directories that I did not create or own. In bash/zsh changing my directory to one of these folders works perfectly fine.

### How to reproduce

On Linux, have a folder owned by a system administrator. Other equally privileged folders do not appear to reproduce this. Some folders that I do not own I do seem to be able to CD into so I'm not too sure what the issue is. Here's the cases I've tried

1. Folder with uid of unprivileged user and that user's group as the gid: able to CD
2. Folder with my uid (unprivileged) and gid: able to CD
3. Folder with root uid, and a group that I DO belong to: NOT able to CD
4. Folder with uid of an sysadmin controled user, and a gid of a group I belong to: NOT able to CD
5. Folder with uid of root, and gid of root: able to CD (this is very surprising to me)

In all of these cases I'm able to CD to these directories with zsh. When I try to CD in cases 3 and 4 I get the following error

```
Error: nu::shell::io_error

  × I/O error
  help: Cannot change directory to /sifive: You are neither the owner, in the
        group, nor the super user and do not have permission
```

Note that in those cases I *do* belong to the group for that folder. Additionally note that even when I'm not the owner, or in the group, nor have system permissions I can still CD into those directories with a traditional shell.

Please let me know if you need more information. I'm somewhat limited in what I can share because this is a company machine but I'll try my best to give you what info you need if I can.

### Expected behavior

I should be able to CD to almost any directory, regardless of ownership/group membership

### Configuration

| key                | value                                                   |
| ------------------ | ------------------------------------------------------- |
| version            | 0.81.0                                                  |
| branch             |                                                         |
| commit_hash        | 5c81bcef1a3c1667468c81ef8c06cf56a0962133                |
| build_os           | linux-x86_64                                            |
| build_target       | x86_64-unknown-linux-musl                               |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)                     |
| rust_channel       | 1.68.2-x86_64-unknown-linux-gnu                         |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)                     |
| build_time         | 2023-06-06 22:54:17 +00:00                              |
| build_rust_channel | release                                                 |
| features           | default, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  |                                                         |

### Additional context

Note that this is a shared machine which is a bit unorthodox nowdays but is still a real use case.

**Comment by WindSoilder** [comment]
I remember there is a pr might be relative: #7775

And for this one:
> 5. Folder with uid of root, and gid of root: able to CD (this is very surprising to me)

I believe it's relative to the issue too: https://github.com/ogham/rust-users/issues/44
