### ISSUE TITLE
Aliases set inside if statements do not persist

### ISSUE THREAD

**Issue by Luis-Licea** [nushell/nushell#9517]
### Describe the bug

I tried to conditionally set an alias inside my `config.nu` file using an `if` statement, but the alias was removed after leaving the `if` block scope.

### How to reproduce

1. Conditionally set an alias in `config.nu`:
```nu
if not  (which bat | is-empty) {
    # Add syntax highlighting to printed files.
    alias cat = bat --style=plain --paging=never;
    # Print some file with syntax highlighting to show that the alias works.
    cat /etc/fstab
}
```
2. Open a new `nu` session. You should see the `/etc/fstab` file was printed with syntax highligting, meaning that the alias worked inside the `if` statement.
3. Execute `which cat` to see that the `cat` program points to `/usr/bin/cat` rather than an alias.

### Expected behavior

I would expect the alias to persist outside of the `if` block. In other words, `which cat` should not point to `/usr/bin/cat` anymore.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.81.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | 5c81bcef1a3c1667468c81ef8c06cf56a0962133                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31) (Arch Linux rust 1:1.70.0-1) |
| cargo_version      | cargo 1.70.0                                                     |
| build_time         | 2023-06-07 08:13:21 +00:00                                       |
| build_rust_channel | release                                                          |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

### Additional context

Mybe related: https://github.com/nushell/nushell/issues/4837

**Comment by Luis-Licea** [comment]
I just realized this issue may be a duplicate of https://github.com/nushell/nushell/issues/5068, so it can be closed.

**Comment by amtoine** [comment]
good catch @Luis-Licea, let's close this one in favor of #5068 :yum:

**Comment by sholderbach** [comment]
Thanks for the link @Luis-Licea
