### ISSUE TITLE
Check if stdin ($in) is provided without hanging

### ISSUE THREAD

**Issue by kraftnix** [nushell/nushell#9523]
### Question

I am trying to write a shebang script which can optionally use data piped in from stdin.

If I try use `$in` in a shebang script without actually piping in anything to the script, the execution hangs.

### Additional context and details

As in I would like to be able to call this script with either:
```sh
# hangs with nothing piped in
./script.nu

# runs as expected
cat ./test.json | ./script.nu
```

Where `script.nu`
```nu
#! /usr/bin/env -S nu --stdin
echo "Your Input" $in
```

If I try to access `$in` in any way (like checking for `null` or empty string) without piping anything into the script call, I get a hang.

Is there a way around this?

**Comment by kraftnix** [comment]
I think it is related, but I don't have an issue piping data into a shebang script.

I don't have a problem utilising `stdin` if I use `#!/usr/bin/env -S nu --stdin` as a shebang, the problem only appears if I attempt to use `$in` within the script _and_ I don't pipe anything into the script via `stdin`.

**Comment by devyn** [comment]
Hi, just seeing this now, going through `$in` issues.

This is not a bug, this is how input works with stdin in general (for all programs) - if you read from stdin without piping something in, it's going to wait for you to type stuff at the terminal and then press the end of file key (Ctrl-D on unixes)

If you want to run with no input, pipe null into it (at least in nushell): `null | ./script.nu`

From bash, you can do `./script.nu </dev/null`
