### ISSUE TITLE
Aliasing do-closure with `$in` panics in REPL, but works as a script

### ISSUE THREAD

**Issue by mksinicus** [nushell/nushell#9545]
### Describe the bug

`alias foo = do $closure`, when `$closure` contains `$in`, will cause the REPL to crash (panic) when its name (`foo` here) is typed.

With `RUST_BACKTRACE=1`, it prints

```
thread 'main' panicked at 'Attempt to mutate a block that is in the permanent (immutable) state', /home/marco/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/nu-protocol-0.82.0/src/engine/engine_state.rs:1809:13
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: nu_protocol::engine::engine_state::StateWorkingSet::get_block_mut
   3: nu_protocol::ast::expression::Expression::replace_in_variable
   4: nu_protocol::ast::expression::Expression::replace_in_variable
   5: nu_protocol::ast::expression::Expression::replace_in_variable
   6: nu_protocol::ast::expression::Expression::replace_in_variable
   7: nu_parser::parser::wrap_expr_with_collect
   8: nu_parser::parser::wrap_element_with_collect
   9: nu_parser::parser::parse_block
  10: nu_parser::parser::parse
  11: <nu_cli::syntax_highlight::NuHighlighter as reedline::highlighter::Highlighter>::highlight
  12: reedline::engine::Reedline::repaint
  13: reedline::engine::Reedline::read_line
  14: nu_cli::repl::evaluate_repl
  15: nu::run::run_repl
  16: nu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

However, in a script it works fine (both when run as a script and used as a module)

```nushell
> cat test-do.nu
alias negate = do {not $in}
alias plus = do {|x| $in + $x}
alias foo = do {$in | 'foo'}

export def main [] {
  print (true | negate)
  print (2 | plus 2)
  print ('bar' | foo)
}
> nu test-do.nu
false
4
foo
> use test-do.nu; test-do
false
4
foo
```

### How to reproduce

In REPL,

```nushell
> alias negate = do {not $in}
> negate # crashes when the final letter is typed
```

I think it's because `$in` has a different semantics in REPL.

### Expected behavior

Works in REPL just as in scripts

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.82.0                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.68.1 (8460ca823 2023-03-20)                                             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                                                 |
| cargo_version      | cargo 1.68.1 (115f34552 2023-02-26)                                             |
| build_time         | 2023-06-28 13:58:54 +08:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | standard                                                                        |
| features           | dataframe, default, extra, sqlite, trash, which, zip                            |
| installed_plugins  | from eml, from ics, from ini, from vcf, query, query json, query web, query xml |

**Comment by jntrnr** [comment]
This looks like it's happening because when the `alias negate = do {not $in}` is first written, we are creating a block and placing it in the permanent state.

The problem is, once we try to call negate later, we want to expand the macro and finish processing it. For `$in`, this means that we'll expand to `collect {|in| ... $in ... }` and to do that, we replace the `$in` the user typed with this new `$in` variable we create for the `collect` call.

There's definitely an ordering issue here. Will need a bit of research to figure out what the correct ordering is.

**Comment by amtoine** [comment]
i was hit by this issue pretty hard on the following version :open_mouth: 
| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.87.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.73.0 (cc66ad468 2023-10-03) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.73.0 (9c4383fb5 2023-08-26) |
| build_time         | 2023-11-15 18:45:43 +01:00          |
| build_rust_channel | release                             |
| allocator          | mimalloc                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  | jwalk, nu_plugin_explore            |

**Comment by devyn** [comment]
It seems to be working now, feel free to reopen it if that's not the case
