### ISSUE TITLE
From ini adds additional empty record to structured output

### ISSUE THREAD

**Issue by Yethal** [nushell/nushell#9556]
### Describe the bug

Opening an ini-formatted file and parsing it via `from ini` adds another empty key/value pair to the record

### How to reproduce

1. Save attached ini file as whatever
2. Run `open whatever|from ini`
3. Notice additional record key

### Expected behavior

I expected nu to output a record matching the record structure

### Screenshots

![image](https://github.com/nushell/nushell/assets/26117918/7cb452a2-4531-4477-9734-a52248ae46d5)

### Configuration

| key                | value                                                                                                 |
| ------------------ | ----------------------------------------------------------------------------------------------------- |
| version            | 0.82.0                                                                                                |
| branch             |                                                                                                       |
| commit_hash        |                                                                                                       |
| build_os           | linux-x86_64                                                                                          |
| build_target       | x86_64-unknown-linux-gnu                                                                              |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)                                                                   |
| rust_channel       | stable-x86_64-unknown-linux-gnu                                                                       |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)                                                                   |
| build_time         | 2023-06-28 10:30:35 +02:00                                                                            |
| build_rust_channel | release                                                                                               |
| allocator          | standard                                                                                              |
| features           | dataframe, default, extra, sqlite, trash, which, zip                                                  |
| installed_plugins  | from eml, from hcl, from ics, from ini, from vcf, gstat, inc, query, query json, query web, query xml |

### Additional context

Example file:

[placeholder]
aws_access_key_id=AAAAAAAAAAAAAAAAAAAAA
aws_secret_access_key=BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
[default]
aws_access_key_id=AAAAAAAAAAAAAAAAAA
aws_secret_access_key=AAAAAAAAAAAAAAAAAAAAAAA
aws_session_token=BBBBBBBBBBBBBBBBBBBBBBBB
region=us-east-1
output=json

**Comment by fdncred** [comment]
i wonder if this is a problem with the ini crate or with our code?
