### ISSUE TITLE
uniq / distinct / duplicate filtering

### ISSUE THREAD

**Issue by evanjs** [nushell/nushell#956]
**Is your feature request related to a problem? Please describe.**
Currently, we have no way to easily deduplicate data.

**Describe the solution you'd like**
I'd like to see an equivalent of bash's [uniq](https://en.wikipedia.org/wiki/Uniq), or `sort -u` [[1](https://unix.stackexchange.com/a/76050/226782)]

**Describe alternatives you've considered**
Super complex filters, while impractical, should be able to "work around" this issue for the time being...

**Comment by notryanb** [comment]
Is anyone currently working on this issue?

**Comment by jonathandturner** [comment]
@notryanb I don't know of anyone

**Comment by notryanb** [comment]
@jonathandturner I'd like to work on this one if no one has any objections.

**Comment by evanjs** [comment]
Thanks, @notryanb!

Can this be closed with #1132, or is there anything else that needs to be done?

**Comment by jonathandturner** [comment]
@evanjs - yes, I think this is done now.
