### ISSUE TITLE
Add ulimit

### ISSUE THREAD

**Issue by JakeSiFive** [nushell/nushell#9563]
### Related problem

Posix shells all have to have something like `ulimit` built in somehow in order to change their limits from the shell in a way that persists. It does me no good to use the system ulimit (typicall at /usr/bin/ulimit) from nushell as that does not change nushell's limits nor any of its child process limits.

### Describe the solution you'd like

On posix systems there should be a built in for getrlimit and setrlimit libc functions. This would allow me to at least write my own ulimit

### Describe alternatives you've considered

Ideally, nushell would maintain its own ulimit implementation that worked something like bash's ulimit rather than just providing raw primitives.

### Additional context and details

Right now if I have to change my ulimits I have to go into bash first, and then change it, and then if I still want to use nushell I have to invoke nushell form there.

**Comment by amtoine** [comment]
@JakeSiFive 

i'm not familiar with this *ulimit* notion, could you explain a bit more with maybe a concrete use case, so that i can understand what the request is better? :innocent:

**Comment by JakeSiFive** [comment]
On posix systems, each process has some state. By and large the way you create a process with a particular state is by forking, changing the child fork's state to whatever you want it to be, and then exec-ing to the actual payload. fork creates a child process with near identical process state, and exec by replaces the current process with a process that has near identical state to that.

One of these bits of inherited process state are the limits of a process. These govern things like how many file handles can be open at once, how large of a core dump do you want to allow, how many sockets can a process have, how many psuedoterminals can a process have etc...

Each limit has a soft and a hard limit. If a process tries to do something that would make it go over the soft limit, it receives an error of some sort instead. The process can however change its soft limit to anything less than the hard limit and can also decrease its own hard limit. So for instance its common to fork, decrease your hard limit, and then exec to reduce the resources that a process can use. It's also common for init systems to have their default soft limits set to something much lower than the hard limit so that a process has to explicitly increase their soft limit if they want to consume extra of some kind of resource.

In a shell it can be required that you lower one of these limits for testing, or increase them to make something work (like getting core dumps at all for instance). The typical command that does this in most shells is called [ulimit](https://man7.org/linux/man-pages/man1/ulimit.1p.html), named after the old syscall [ulimit](https://man7.org/linux/man-pages/man3/ulimit.3.html). There is a `/usr/bin/ulimit` binary on most systems but its really only good for *reading* the limits because if you create a child process and the child process changes its limits, this does not affect the parent process (e.g. the shell in this case) in anyway. Consequently shells have to implement the `ulimit` command as a built in. This is exactly the same situation as "cd" for changing the current working directory which is another example of inherited process state.

Nowadays, on modern systems we don't use the old `ulimit` syscall but instead use [getrlimit and setrlimit](https://man7.org/linux/man-pages/man2/setrlimit.2.html) but the shell command is still called `ulimit`.

Use cases are quite broad but the one that's currently hurting me is needing to increase the soft limit on RLIMIT_CORE to something larger than 0 so that I can get coredumps at all. I also sometimes have to increase the soft limit to something high in order to run programs that open many thousands of files at once.

**Comment by amtoine** [comment]
i see, thanks @JakeSiFive for the clear explaination :relieved:
