### ISSUE TITLE
Add better support for env-preserving commands/closures

### ISSUE THREAD

**Issue by kubouch** [nushell/nushell#9564]
### Related problem

Currently, we have `def-env` as a way for commands to preserve the environment:
```nushell
def-env foo [x: path] {
    cd $x
}
```

We lack a way to do the same for
* `extern` commands
* arbitrary closures

### Describe the solution you'd like

A simple solution would be to remove `def-env` and use `--env` flag for the following commands:
* `def --env`
* `extern --env`
* `do --env`

This should cover the majority of the cases this functionality is needed.

**Comment by fdncred** [comment]
Just being a completist here. These are all the env commands I see. I'm not sure all these commands would need `--env` but it's something to think about.

- def-env
- export def-env
- export-env
- hide-env
- let-env
- load-env
- source-env
- with-env

**Comment by hyiltiz** [comment]
We probably do *not* want closures to mutate the env? (Currently, they can mutate, e.g. `do {cd /; pwd}` does not get you back to your original `pwd`).

**Comment by amtoine** [comment]
@hyiltiz 
with your `do` example, you mean they *can't* mutate the environment, right?

**Comment by hyiltiz** [comment]
@amtoine Yes, thanks for the correction!

**Comment by kubouch** [comment]
I think the current state is sufficient.
