### ISSUE TITLE
Inconsistent behavior of `first` and `last`

### ISSUE THREAD

**Issue by baehyunsol** [nushell/nushell#9567]
### Related problem

`first` on a binary data returns a binary data, but `last` does not. Look at the code below.

```nu
[
  (0x[01 02 03 04] | first),
  (0x[01 02 03 04] | first 2),
  (0x[01 02 03 04] | last),
  (0x[01 02 03 04] | last 2),
]
```

The output of the code is like below

```
╭───┬────────────────╮
│ 0 │ [1]            │
│ 1 │ [1, 2]         │
│ 2 │              4 │
│ 3 │ [list 2 items] │
╰───┴────────────────╯
```

### Describe the solution you'd like

I want both `last` and `first` return a binary, so that the result of the above code is like this:

```
╭───┬────────╮
│ 0 │ [1]    │
│ 1 │ [1, 2] │
│ 2 │ [4]    │
│ 3 │ [3, 4] │
╰───┴────────╯
```

---

There's another subtle one: the help message of `first` mentions that it works on binary data, but `last` does not. It seems like both of them should mention that.

**Comment by baehyunsol** [comment]
There's another one: `[] | first` is an error, but `[] | last` returns `null`. They should be consistent.

**Comment by fdncred** [comment]
I think you're right. You might also try out `skip` and `take`
```
[
  (0x[01 02 03 04] | first),
  (0x[01 02 03 04] | first 2),
  (0x[01 02 03 04] | last),
  (0x[01 02 03 04] | last 2),
  (0x[01 02 03 04] | take 1),
  (0x[01 02 03 04] | skip 3)
  (0x[01 02 03 04] | skip 1 | take 1)
]
╭───┬────────────────╮
│ 0 │ [1]            │
│ 1 │ [1, 2]         │
│ 2 │              4 │
│ 3 │ [list 2 items] │
│ 4 │ [1]            │
│ 5 │ [4]            │
│ 6 │ [2]            │
╰───┴────────────────╯
```

**Comment by baehyunsol** [comment]
@fdncred 

I expected the implementation of [first](https://github.com/nushell/nushell/blob/cd56b975872ba2e5059e2dd69fc2b5fc0d9d128c/crates/nu-command/src/filters/first.rs#L86) and [last](https://github.com/nushell/nushell/blob/cd56b975872ba2e5059e2dd69fc2b5fc0d9d128c/crates/nu-command/src/filters/last.rs#L69) to be very similar, but they were not. They were very different.

I think it would be better to copy&paste either of them, and modify necessary stuffs. For example, copy&paste the implementation of [first](https://github.com/nushell/nushell/blob/cd56b975872ba2e5059e2dd69fc2b5fc0d9d128c/crates/nu-command/src/filters/first.rs#L86) and replacing `.take()` with `rev().take()`, `[0]` with `[vals.len() - 1]` and etc would be an implementation of `last`.

How about that?

**Comment by baehyunsol** [comment]
It wouldn't work for streams, though. I should find a workaround for that.

**Comment by sholderbach** [comment]
Related issues and discussions in the past:

https://github.com/nushell/nushell/issues/6611 and its linked https://github.com/nushell/nushell/pull/6616

And a big one which we discussed back and forth in several meetings: 

https://github.com/nushell/nushell/issues/7128 regarding the behavior of `first` and `last` without a count and their relationship to `take` (also part of https://github.com/nushell/nushell/pull/6893)
