### ISSUE TITLE
How do I cast a `range` into `list<int>`?

### ISSUE THREAD

**Issue by baehyunsol** [nushell/nushell#9569]
### Question

It seems like `0..10 | into list` doesn't work because `into list` doesn't exist.

Even though `range` is casted to `list<int>` implicitly in most cases, I sometimes want to cast it explicitly. For example, `0..10 ++ []` is `[0..10]` and `0..2 | append 2..3` is `[0, 1, 2, 2..3]` and `0..2 ++ 2..3` is an error. None of them seems intuitive.

**Comment by fdncred** [comment]
probably not intuitive either but i think this works
```
0..5 | each {||}
```

**Comment by fdncred** [comment]
if you want to give a use case or example of how `into list` should work for all datatypes, we can consider adding it.

**Comment by fdncred** [comment]
I'm wondering if it may just be easier to make `range` work with a range. Seems like a weird statement but consider this.
```nushell
0..5 | range 0..
```

**Comment by amtoine** [comment]
@KAAtheWiseGit 
such a command would look like this, right?
```nushell
def "into list" []: any -> list<any> {
    each {}
}
```

**Comment by fdncred** [comment]
tucking that `into list` custom command away for safe keeping. thanks @amtoine!

**Comment by KAAtheWiseGit** [comment]
@amtoine I had something like this in mind, yeah.  I think it could either be restricted to range input, or infer type somehow to wrap single ints/strings/etc into lists.  I can't figure out how to do that in Nushell, though.

**Comment by amtoine** [comment]
@KAAtheWiseGit 
for now, maybe the easiest would be to restrict the command to
```nushell
def "into list" []: range -> list<int> {
    each {}
}
```

**Comment by KAAtheWiseGit** [comment]
@amtoine, agreed!  I'll move the question about types to another issue.

**Comment by WindSoilder** [comment]
I think the question is answered, closing the issue for now. 

Feel free to re-open it if you still have question
