### ISSUE TITLE
Binaries in help messages are not seen.

### ISSUE THREAD

**Issue by baehyunsol** [nushell/nushell#9570]
### Related problem

Help messages for commands provide examples. For example, when I type `into binary --help`, it gives me examples of `into binary` in `Examples` section. The first example is `1 | into binary`, but it doesn't show me what the result is, because 1 in utf-8 is not a valid character.

If I change `1` in [this line](https://github.com/nushell/nushell/blob/cd56b975872ba2e5059e2dd69fc2b5fc0d9d128c/crates/nu-command/src/conversions/into/binary.rs#L83) to `97`, it tells me that the result of `97 | into binary` is `a`. Though it does show me a result, but it doesn't quite make sense. It sounds like `into binary` returns a character, not a binary.

### Describe the solution you'd like

It seems like the shell calls `.as_string()` to the binary before printing the help message. [here](https://github.com/nushell/nushell/blob/cd56b975872ba2e5059e2dd69fc2b5fc0d9d128c/crates/nu-engine/src/documentation.rs#L238)

The output of `.as_string()` of a binary data doesn't look like a binary data at all. We need other method for this context, for example: `.as_debug_string()`, which distinguishes binary and string.

**Comment by sholderbach** [comment]
Good call we should probably provide good debug output here.

**Comment by amtoine** [comment]
the example from the `input binary` help page should probably just print
```
Length: 8 (0x8) bytes | printable whitespace ascii_other non_ascii
00000000:   01 00 00 00  00 00 00 00                             •0000000
```
as in the REPL :open_mouth: 

and the first example should probably give
```
Length: 52 (0x34) bytes | printable whitespace ascii_other non_ascii
00000000:   54 68 69 73  20 69 73 20  61 20 73 74  72 69 6e 67   This is a string
00000010:   20 74 68 61  74 20 69 73  20 65 78 61  63 74 6c 79    that is exactly
00000020:   20 35 32 20  63 68 61 72  61 63 74 65  72 73 20 6c    52 characters l
00000030:   6f 6e 67 2e                                          ong.
```

**Comment by Heidar-An** [comment]
I'd be interested in getting started on this. Just want to clarify the spec, you'd like another method called as_debug_string that checks if the input is a binary and if so, leaves it in binary form otherwise converts it into a string?

**Comment by amtoine** [comment]
thanks @Heidar-An for willing to work on this :blush: 

> I'd be interested in getting started on this. Just want to clarify the spec, you'd like another method called `as_debug_string` that checks if the input is a binary and if so, leaves it in binary form otherwise converts it into a string?
> 
i think the end product would be the following, if i remember the issue correctly :yum: 

currently `help into binary` gives the following examples:
```nushell
Examples:
  convert string to a nushell binary primitive
  > 'This is a string that is exactly 52 characters long.' | into binary
  This is a string that is exactly 52 characters long.

  convert a number to a nushell binary primitive
  > 1 | into binary


  convert a boolean to a nushell binary primitive
  > true | into binary
```
but to be more accurate when looking at the REPL output, it should probably be
```nushell
Examples:
  convert string to a nushell binary primitive
  > 'This is a string that is exactly 52 characters long.' | into binary
  Length: 52 (0x34) bytes | printable whitespace ascii_other non_ascii
  00000000:   54 68 69 73  20 69 73 20  61 20 73 74  72 69 6e 67   This is a string
  00000010:   20 74 68 61  74 20 69 73  20 65 78 61  63 74 6c 79    that is exactly
  00000020:   20 35 32 20  63 68 61 72  61 63 74 65  72 73 20 6c    52 characters l
  00000030:   6f 6e 67 2e                                          ong.

  convert a number to a nushell binary primitive
  > 1 | into binary
  Length: 8 (0x8) bytes | printable whitespace ascii_other non_ascii
  00000000:   01 00 00 00  00 00 00 00                             •0000000

  convert a boolean to a nushell binary primitive
  > true | into binary
  Length: 8 (0x8) bytes | printable whitespace ascii_other non_ascii
  00000000:   01 00 00 00  00 00 00 00                             •0000000
```

> (_can I also be assigned to the issue_)
>
yup you can :wink:

**Comment by Heidar-An** [comment]
cool, thanks, will get started on this now :)

**Comment by amtoine** [comment]
> cool, thanks, will get started on this now :)
amazing, really appreciate it :blush:

**Comment by weirdan** [comment]
Both `std help` and core `help` now correctly show binary examples in `into binary --help`
