### ISSUE TITLE
`env` assignment doesn't work well with `if`

### ISSUE THREAD

**Issue by WindSoilder** [nushell/nushell#9595]
### Describe the bug

As title, when use `env` with `if`, it's easy to meet error..

### How to reproduce

1. `$env.y = if $a == 3 { 10 }`
Then nushell shows the following error:
```
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[entry #12:1:1]
 1 │ $env.y = if $a == 3 { 10 }
   ·             ─┬
   ·              ╰── expected operator
   ╰────

```

I spot the issue when I want to active `conda.nu` in `nu_script`, but that code seems to updated.

### Expected behavior

I expect nu to work properly

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.81.1                                   |
| branch             | main                                     |
| commit_hash        | a0dafcb0f89eb6161ac98fbf388040744f0a5947 |
| build_os           | macos-x86_64                             |
| build_target       | x86_64-apple-darwin                      |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31)      |
| rust_channel       | stable-x86_64-apple-darwin               |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)      |
| build_time         | 2023-06-23 18:19:13 +08:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | from eml                                 |

### Additional context

Additionally, if I wrap `if` with `()`, it works fine:
```nushell
$env.y = (if $a == 3 { 10 })
```

**Comment by amtoine** [comment]
i can reproduce this, in quite a lot of places actually :open_mouth: 
> see https://github.com/goatfiles/scripts/commit/44b0dba550210687a562ab3d28dc5a54c6e1ca7e
