### ISSUE TITLE
"Dumping files into directory" results in "module not found"

### ISSUE THREAD

**Issue by dedebenui** [nushell/nushell#9597]
### Describe the bug

I'm trying to setup a folder with a bunch of completion scripts, just like [the documentation](http://www.nushell.sh/book/modules.html#dumping-files-into-directory) advertises you can do, but the module is not found when opening a new shell.

### How to reproduce

as per the [the documentation](http://www.nushell.sh/book/modules.html#dumping-files-into-directory):
1. create a `completions` folder at the root of my config folder:
2. create an empty `mod.nu` file in it
3. write my completion scripts (e.g. `git.nu`). At this point I have the following structure:
```
nushell
├── env.nu
├── config.nu
├── completions
│   ├── git.nu
│   └── mod.nu
```
4. add `use completions *` to `config.nu` 
5. add the `completions` folder to `$env.NU_LIB_DIRS` inside `env.nu`

### Expected behavior

I expect the `completions` module to be found and my completions to work.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.82.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | macos-x86_64                        |
| build_target       | x86_64-apple-darwin                 |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31) |
| rust_channel       | stable-x86_64-apple-darwin          |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25) |
| build_time         | 2023-06-28 08:26:28 +02:00          |
| build_rust_channel | release                             |
| allocator          | standard                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  |                                     |

### Additional context

Suppose I also have `nushell/scripts` in my `env.NU_LIB_DIRS` and I move the `completions` folder there:
```
nushell
├── env.nu
├── config.nu
├── scripts
│   ├── completions
│   │   ├── git.nu
│   │   └── mod.nu
```

Now I get no error, but the completions are still not working (writing `git fetch <tab>` in a repository doesn't invoke the completion). I think that might be because in that context, the setup is equivalent to writing `use git.nu` instead of `use git.nu *`, but I don't know how this difference affects completions.

Of course, replacing `use completions *` with `use git.nu *` works, but it kind of defeats the "auto-sourcing files from a directory" idea.

**Comment by amtoine** [comment]
@dedebenui 
i think this is the expected behaviour :+1: 

when you add a path to `NU_LIB_DIRS` it means that Nushell will look *inside* the directories from `NU_LIB_DIRS`, not at the same level.
this is exactly how the `PATH` works!

so when you add `~/.config/nushell/completions/` you either want to
- add `~/.config/nushell/` instead and `use completions *`
- `use completions git`

i think the documentation is just wrong here, i've never seen `NU_LIB_DIRS` working as advertised in the link you give above :open_mouth:

typically what i'd do is
- create `~/.config/nushell/scripts/completions/...`
- add `~/.config/nushell/scripts/` to `NU_LIB_DIRS` in `env.nu`
- run `use completions *` in `config.nu`

:yum:

**Comment by amtoine** [comment]
could this issue be a duplicate of https://github.com/nushell/nushell/issues/8676?
at least it's related :yum:

**Comment by dedebenui** [comment]
Thank you for the explanation, now it makes sense that my initial case doesn’t work 👍 Yes it's definitely similar to #8676

However, I also tried putting the `completions` folder into `scripts` and adding `scripts` to `NU_LIB_DIRS`. I get no error but still no completion. I suspect that in that case, `use completions *` brings all the submodules from the `completions` folder in scope, but not their functions directly, which is why typing `git <tab>` doesn't work. If my completion script is named `git-completions.nu`, then I can invoke it by first typing the name of the script:

<img width="658" alt="completions work when preceded by the completion module name" src="https://github.com/nushell/nushell/assets/41047847/e730a046-12c9-44cf-86b8-f434d20ea4f6">

In other words, I think there might be a problem where for this approach to work, one has to be able to bring a function into scope from 2 levels deep (`completions` ← `git-completions.nu`). I can get it to work by adding `export use git-completions *` to `completions/mod.nu`, but I still get the `git-completions`-scoped versions as well:

<img width="647" alt="every function appears twice now" src="https://github.com/nushell/nushell/assets/41047847/6ecd0aeb-8812-49fd-a2f6-94f468107e7e">

I don't find it particularly elegant to have every function appear twice. Moreover, I still need to edit `mod.nu`, which defeats the purpose since in that case, I might as well do it directly in `config.nu` and not use the "folder-as-a-module" approach.

In the end I actually found a pretty good approach, but it requires to modify the completion scripts: by naming each completion script with the exact name of the function (e.g. `git.nu` instead of `git-completions.nu`) and naming each `export extern` function with the name of the subcommand only (e.g. `fetch` instead of `git fetch`, don't forget to rename the base command, if present, to `main` also), I can get the `use completions *` to work with an empty `mod.nu`.

Pros:
- simply adding a file to `completions` works as expected.
- completion scripts are a bit "lighter on the eye" since they don't repeat the command name everywhere anymore.

Cons:
- If you're using completion scripts from the `nu_scripts` repo, you need to edit them.

I think this approach is more elegant than the current one used in the `nu_scripts` repo. If we changed all the completion scripts in there to that format, people can then simply grab them, put them in a folder and call it a day, without changing anything in their config. I might start a discussion there. For now, my issue here is solved 😊

**Comment by amtoine** [comment]
let me try to sum up: your issue now is that `use completions *` does not bring the actual completions but rather the modules that contain the completions, e.g. `git-completions`, right?

the rule for completions to work is that you need, in the end, after all the `use ...` unwraps, to have the exact command into scope.
e.g. for `git fetch`, if you have `fetch` defined in some `completions vcs git` module, you do not want to `use completions *` which would only bring `vcs git fetch` into scope :thinking: 
you want `use completions vcs git` or `use completions vcs *` :+1: 

one real world example:
i have a `nu-git-manager` Nushell package which defines a `sugar` submodule with a whole bunch of Git-related stuff, e.g. Git completions like `git fetch` inside a `git` module.
in my `config.nu`, i do [the following](https://github.com/goatfiles/dotfiles/blob/main/.config/nushell/config.nu#L157) to bring the completions into scope :+1: 

i hope this all makes sense :eyes:

**Comment by amtoine** [comment]
this is very true @dedebenui and i kinda like what you're saying here :yum: 
i might borrow this for my `nu-git-manager` actually :smirk: 
and you can still import completions selectively with `use completions git` :ok_hand:
