### ISSUE TITLE
`$env` assignment silently runs wrong command

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#9599]
### Describe the bug

related to https://github.com/nushell/nushell/pull/9589

i was playing with variable assignment with the new https://github.com/nushell/nushell/pull/9589 feature and i think i noticed a pretty bad silent bug :thinking: 

1. this is fine because https://github.com/nushell/nushell/pull/9589 did not address assignment
```nushell
> $env.foo = ls | where type == file
```
```nushell
Error: nu::shell::only_supports_this_input_type

  × Input type not supported.
   ╭─[entry #29:1:1]
 1 │ $env.foo = ls | where type == file
   · ──┬─            ──┬──
   ·   │               ╰── only list, binary, raw data or range input data is supported
   ·   ╰── input type: nothing
   ╰────
```
the error is a bit unhelpful but it's easily fixed by adding parentheses: `$env.foo = (ls | where type == file)`

2. this fails because we do not support the syntax as it might be ambiguous inside a record
```nushell
> export-env { load-env { $env.FOO: ls | where type == file } }
```
```nushell
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[entry #31:1:1]
 1 │ export-env { load-env { $env.FOO: ls | where type == file } }
   ·                       ──────────────────┬──────────────────
   ·                                         ╰── expected record
   ╰────
```

3. however, the following does *work* in the sense in does not throw an error... but i think it does not make any sense here to have `$env.FOO` being equal to the `"ls"` string, without any error
```nushell
> export-env { $env.FOO = ls | where type == file }; $env.FOO
```
```nushell
ls
```

### How to reproduce

1. run `export-env { $env.FOO = ls | where type == file }; $env.FOO`
2. see that it gives `ls`

### Expected behavior

i expected `export-env { $env.FOO = ls | where type == file }` to either
- give an error just as `$env.FOO = ls | where type == file` does
- give the result of `ls | where type == file` inside `$env.FOO`

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.82.1                                   |
| branch             | main                                     |
| commit_hash        | 2bb0c1c618f961843b49432fb7a21304b41493af |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)      |
| rust_channel       | 1.68.2-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)      |
| build_time         | 2023-07-03 18:32:11 +02:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | hist, plot                               |

**Comment by WindSoilder** [comment]
Actually I think it's better to wrap the `ls | where type == file` with `()` to make it more readable.

**Comment by amtoine** [comment]
> Actually I think it's better to wrap the `ls | where type == file` with `()` to make it more readable.
>
mm i dunno.
the syntax has been relaxed in #9589 and i think it's great not being forced to use parentheses for such simple pipes :yum: 

and because the syntax has been relaxed in that area, i think this behaviour above is a bug and a pretty nasty one :thinking:

**Comment by sholderbach** [comment]
This is basically #9698 rearing its head by returning nothing.

**Comment by sholderbach** [comment]
Closing in favor of #12956 as we collected more cases there.
