### ISSUE TITLE
Add `pwd` command to standard library

### ISSUE THREAD

**Issue by Hofer-Julian** [nushell/nushell#9601]
If I introduce people coming from powershell they are often confused how to access the current working directory.
`pwd` is a powershell built-in and not an exectuable on Windows, so simply running `pwd` doesn't work.

According to an old blog post, `pwd` used to be a supported command: https://www.nushell.sh/blog/2019-09-24-nushell_0_3_0.html#new-commands-incrop-ramonsnir-ijt-jonathandturner-andrasio-jonnywalker81-chhetripradeep-pka.
I don't know the reason for removing this command, but I think it is worth reconsidering now that the standard library is a thing. The implementation could be as simple as:
```nushell
def pwd [] {
    $env.PWD
}
```

Advantages:
- muscle memory
- faster to type than `$env.PWD`
- avoid that people use `pwd`, without knowing that it doesn't work on Windows at the moment

Disadvantages:
- adds a command that is not strictly necessary

**Comment by fdncred** [comment]
I'd be ok with this somewhere in the stdlib. I agree with your reasoning.

**Comment by Hofer-Julian** [comment]
Nice, I will see if I have time to open a PR this week

**Comment by Hofer-Julian** [comment]
Oh, I just saw that you have to explicitly run `use std` to bring standard library symbols into scope, I somehow missed that.
Are there plans to import a subset of stdlib into the global scope (similar to `std::prelude` in Rust)?

**Comment by fdncred** [comment]
There is a prelude already. I think this is it https://github.com/nushell/nushell/blob/7e39179b7f981ba8e5de231cd14c28e6c962e83a/crates/nu-std/src/lib.rs#L48-L64

**Comment by Hofer-Julian** [comment]
Awesome, thanks 🤩

**Comment by fdncred** [comment]
I was removing my `pwd` function out of my custom command script, since it's build in now (tyvm!), but i stumbled upon this one. not sure we need to add it but some people may find value in it.
```nushell
# Easy way to get a short working directory
def pwd-short [] {
  $env.PWD | str replace $nu.home-path '~' -s
}
```
