### ISSUE TITLE
rm: delete symlinks on windows

### ISSUE THREAD

**Issue by Dorumin** [nushell/nushell#9624]
### Describe the bug

`rm` throws an OS error when trying to delete a symlink. I dunno if the same happens on Linux, I'd assume not since it would've been found earlier as they're far more common there.

The command does work when using the -t flag, which means this isn't a problem of capability, just a bug. The error says "The directory name is invalid". Probably has something to do with [this](https://github.com/nushell/nushell/blob/f38657e6f352d8bacfdb984bc4d4dcf6307d99f3/crates/nu-command/src/filesystem/rm.rs#L399) fallback to remove_dir_all, as an earlier if checks for is_symlink but it's not checked in the if let..else chain.

### How to reproduce
0. `touch somefile.txt` (this doesn't need admin)
1. `mklink link.txt somefile.txt` (you need admin for this)
2. `rm link.txt` (you don't need admin for this one)

### Expected behavior

I expect the symlink to be deleted. I also expect the original file to not be deleted oh god no please not that, I prefer it to throw an error. You can add a --follow-symlinks flag, but never let it be the default

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.81.0                                   |
| branch             |                                          |
| commit_hash        | 5c81bcef1a3c1667468c81ef8c06cf56a0962133 |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)      |
| rust_channel       | 1.68.2-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)      |
| build_time         | 2023-06-06 22:55:37 +00:00               |
| build_rust_channel | release                                  |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by ChrisDenton** [comment]
Your diagnosis looks correct to me. [`std::fs::FileType`](https://doc.rust-lang.org/std/fs/struct.FileType.html) has three types of files that are mutually exclusive: file, directory or symlink. In the [code you linked](https://github.com/nushell/nushell/blob/f38657e6f352d8bacfdb984bc4d4dcf6307d99f3/crates/nu-command/src/filesystem/rm.rs#L399) the branch assumes that anything that's not a file (or socket or fifo) must be a directory.

 This was probably just an oversight.

**Comment by amtoine** [comment]
i do not see any issue on linux with the following commands
- create a file
```nushell
mkdir /tmp/9704/
touch /tmp/9704/file
```
- create the link
```nushell
ln -s /tmp/9704/file /tmp/9704/symlink
```
- delete the link
```nushell
rm /tmp/9704/symlink
```
- see the result
```nushell
> ls /tmp/9704/
╭───┬────────────────┬──────┬──────┬─────────────────────╮
│ # │      name      │ type │ size │      modified       │
├───┼────────────────┼──────┼──────┼─────────────────────┤
│ 0 │ /tmp/9704/file │ file │  0 B │ 2023/07/15 22:28:30 │
╰───┴────────────────┴──────┴──────┴─────────────────────╯
```

**Comment by ChrisDenton** [comment]
The issue is on Windows 

```text
〉(version).version
0.82.0
〉touch file
〉mklink symlink file
symbolic link created for symlink <<===>> file
〉rm symlink
Error: nu::shell::remove_not_possible

  × Remove not possible
   ╭─[entry #30:1:1]
 1 │ rm symlink
   ·    ───┬───
   ·       ╰── Could not delete Z:\9704\symlink: The directory name is invalid. (os error 267)
   ╰────
```
