### ISSUE TITLE
Panic when trying to do anything after inserting something from the help menu on a non-empty line

### ISSUE THREAD

**Issue by kik4444** [nushell/nushell#9627]
### Describe the bug

When you insert some text from the help menu (F1) with a non-empty line or buffer, Nu panics if you try to modify the buffer in any way. For example deleting a char, moving with the arrow keys or inserting something else from a menu. But if the buffer is empty there's no problem.

### How to reproduce

1. Start with an empty line.
2. Type anything such that the buffer is not empty. For example a single char `a` or space ` `
3. Open the help menu with F1 and insert anything
4. Press backspace or any of the arrow keys.
5. Nu panics with `thread 'main' panicked at 'byte index N is out of bounds ...`

Alternatively press tab or F1 again to open another menu after step 3. Then you get `thread 'main' panicked at 'assertion failed: self.is_char_boundary(idx)'`

### Expected behavior

Nu should take into account the existing buffer when you insert something from the help menu and not panic.

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.82.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | ecdb023e2f6cb17445ae799206e464b2daef3d71                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31) (Arch Linux rust 1:1.70.0-1) |
| cargo_version      | cargo 1.70.0                                                     |
| build_time         | 2023-06-28 05:27:55 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

### Additional context

This happens even without my config if I launch Nu with `nu --no-config-file`

**Comment by fdncred** [comment]
Good catch. I reproduced it on MacOS.

**Comment by amtoine** [comment]
on linux, i followed the steps and could not reproduce the crash :confused: 

@kik4444, could you try these steps again on latest main and then with the patch from https://github.com/nushell/nushell/pull/9784 to see if the issue is still there and if the patch fixes it? :innocent: 
that'd be sweet :yum:

**Comment by fdncred** [comment]
I can't reproduce on macos any longer.

**Comment by kik4444** [comment]
Still happens to me in the same way with version
| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.83.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | a33b5fe6ce97b5e9fe8a774c13e783ed65c1b591                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12) (Arch Linux rust 1:1.71.0-1) |
| cargo_version      | cargo 1.71.0                                                     |
| build_time         | 2023-07-26 01:10:19 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by kik4444** [comment]
> on linux, i followed the steps and could not reproduce the crash confused
> 
> @kik4444, could you try these steps again on latest main and then with the patch from #9784 to see if the issue is still there and if the patch fixes it? innocent that'd be sweet 😋

This does seem to fix it. I git cloned the repo, applied that PR and compiled it like so
| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.83.2                                               |
| branch             | main                                                 |
| commit_hash        | 9d7a1097f2b72c8cdd0d178fb2e780ff6ab09ac7             |
| build_os           | linux-x86_64                                         |
| build_target       | x86_64-unknown-linux-gnu                             |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)                  |
| rust_channel       | 1.69.0-x86_64-unknown-linux-gnu                      |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)                  |
| build_time         | 2023-08-04 21:08:11 +03:00                           |
| build_rust_channel | release                                              |
| allocator          | standard                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by amtoine** [comment]
> I can still reproduce it on linux with the latest main `f61503893835f777c1ade71ec76a6b07fcf818f2`.
> 
> ![Screenshot from 2023-08-05 10-48-24](https://github.com/nushell/nushell/assets/15247421/605ff8ff-a245-44fc-b823-e69ec4831f47)
> 
> reproduce steps:
> 1. enter `a` or anything else
> 2. press <kbd>F1</kbd> to activate the help menu
> 3. accept a suggestion(e.g. `echo`)
> 4. press the arrow keys
> 
> key sequence: <kbd>a</kbd> -> <kbd>F1</kbd> -> <kbd>echo</kbd> -> <kbd>enter</kbd> -> <kbd>left arrow</kbd>
> 
> _Originally posted by @nibon7 in https://github.com/nushell/nushell/issues/9784#issuecomment-1666362391_

i can repro this on latest `main` as well :+1:

**Comment by amtoine** [comment]
and #9784 appears to fix the issue :+1:
