### ISSUE TITLE
Cell path literal syntax inconsistent behavior

### ISSUE THREAD

**Issue by ammkrn** [nushell/nushell#9630]
### Describe the bug

When I open an excel sheet and pipe it into `table`, I get the output
```
╭────────┬────────────────╮
│ Sheet1 │ [table 4 rows] │
╰────────┴────────────────╯
```

Trying to index into the table using the `$.Sheet1` path notation gives me the error I would get if I tried to index using a string: `string doesn't support cell paths`. This is unexpected because:

1. The example code in PR #8493 implementing the cell path literal syntax works fine for me (`{a: {b: 3}} | get $.a.b` produces `3`)
2. Piping the `$.Sheet1` variable into `describe` produces `cell path`
3. The nu vscode plugin describe `let p = $.Sheet1` within the script to reproduce the issue below as a `cell path`

fdncred was very kind to help me find a workaround (using `open <file>.xlsx | get <thing>` directly), but I still find this behavior confusing since it works in the demo, but not for the excel example.

### How to reproduce

Execute the following script, where `mySheet.xlsx` is an excel file with a sheet called `Sheet1`.

```
def openExcel [] {
  let p = $.Sheet1
  open mySheet.xlsx | table | get p
}

openExcel
```

### Expected behavior

In light of the mwe in #8493, I would expect `$.Sheet1` to act as a cell path and index into the table.

### Configuration

| key                | value                                                   |
| ------------------ | ------------------------------------------------------- |
| version            | 0.82.0                                                  |
| branch             |                                                         |
| commit_hash        | ecdb023e2f6cb17445ae799206e464b2daef3d71                |
| build_os           | macos-x86_64                                            |
| build_target       | x86_64-apple-darwin                                     |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)                     |
| rust_channel       | 1.68.2-x86_64-apple-darwin                              |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)                     |
| build_time         | 2023-06-27 17:41:47 +00:00                              |
| build_rust_channel | release                                                 |
| allocator          | standard                                                |
| features           | default, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  | nu-example-1, nu-example-2, nu-example-3                |

**Comment by amtoine** [comment]
@ammkrn 
```nushell
def openExcel [] {
  let p = $.Sheet1
  open mySheet.xlsx | table | get p
}
```
i think the issue comes from this command. `table` is used for rendering only and transforms *stream*able data into *raw input*, i.e. raw text that cannot be used other than raw text.

see
```nushell
> ls | describe
table<name: string, type: string, size: filesize, modified: date> (stream)
> ls | table | describe
raw input
```

this is the reason you get the `string doesn't support cell paths` error :yum: 

now the question is: *is the behaviour of `table` confusing?* and *is the documentation unclear about the fact that `table` will output raw unstructured data?* :thinking:

**Comment by ammkrn** [comment]
> @ammkrn
> 
> ```nushell
> def openExcel [] {
>   let p = $.Sheet1
>   open mySheet.xlsx | table | get p
> }
> ```
> 
> i think the issue comes from this command. `table` is used for rendering only and transforms _stream_able data into _raw input_, i.e. raw text that cannot be used other than raw text.
> 
> see
> 
> ```nushell
> > ls | describe
> table<name: string, type: string, size: filesize, modified: date> (stream)
> > ls | table | describe
> raw input
> ```
> 
> this is the reason you get the `string doesn't support cell paths` error 😋
> 
> now the question is: _is the behaviour of `table` confusing?_ and _is the documentation unclear about the fact that `table` will output raw unstructured data?_ 🤔

I see. The section of the book that sent me down this road is the first example in [opening files](https://www.nushell.sh/book/loading_data.html#opening-files), where the open command is piped into the table command, and the pipelines section of the book states that `ls` and `ls | table` "Are one and the same."

The example in the opening files section might be out of date; the raw output of `open <file>.json` is rendered as a table showing the data, but `open <file>.json | table` produces a more opaque output where the column is just a substituted `[table 3 rows]` type.

**Comment by amtoine** [comment]
@ammkrn 
yeah i see what you mean regarding the doc :thinking: 

maybe there is a confusion here :relieved: 

:point_right: `...` and `... | table` are NOT the same *a priori*!

the thing is, by default, Nushell comes with a `display_output` hook that changes the output of pipelines: see the [`default_config.nu`](https://github.com/nushell/nushell/blob/main/crates/nu-utils/src/sample_config/default_config.nu#L325-L327) file.

e.g. if you have a terminal wide enough and run `sys`, you probably see the output of `sys | table -e`, not *regular* `sys`, which should be the same as `sys | table` without any configuration, i.e. collapsed.

the issue when showing output of commands to users is that we do not know the size of their terminal and thus whether the `display_output` hook will kick in or not :thinking: 
piping big tables into `table` makes sure the output will be the same for everyone :+1: 


but with your story, it makes sense that it can be confusing :thinking: 
maybe we should change the default config file :eyes:

**Comment by ammkrn** [comment]
Thanks for taking a look, I appreciate it.
