### ISSUE TITLE
detect columns crashes nushell

### ISSUE THREAD

**Issue by bsott** [nushell/nushell#9653]
### Describe the bug

nu shell crashes when range is out of bounds in detect columns

fe. 

```
> echo "1 2 3 4 5\n1 2 3 4 5" | detect columns -c 1..5
thread 'main' panicked at 'range end index 6 out of range for slice of length 5', crates/nu-command/src/strings/detect_columns.rs:215:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

but also when I tried "open" range

```
> echo "1 2 3 4 5\n1 2 3 4 5" | detect columns -c 4..
thread 'main' panicked at 'range end index 6 out of range for slice of length 5', crates/nu-command/src/strings/detect_columns.rs:215:33
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::index::slice_end_index_len_fail_rt
   3: core::slice::index::slice_end_index_len_fail
   4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   5: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
   6: <nu_command::viewers::table::PagingTableCreator as core::iter::traits::iterator::Iterator>::next
   7: <nu_protocol::value::stream::RawStream as core::iter::traits::iterator::Iterator>::next
   8: nu_protocol::pipeline_data::print_if_stream
   9: nu_protocol::pipeline_data::PipelineData::print
  10: nu_cli::util::eval_source
  11: nu_cli::repl::evaluate_repl
  12: nu::run::run_repl
  13: nu::main
```

### How to reproduce

1. run `echo "1 2 3 4 5\n1 2 3 4 5" | detect columns -c 4..`

### Expected behavior

should show some error message but shell should not die

### Screenshots

```
project> echo "1 2 3 4 5\n1 2 3 4 5" | detect columns -c 4..                                                           07/11/2023 09:54:20 AM
thread 'main' panicked at 'range end index 6 out of range for slice of length 5', crates/nu-command/src/strings/detect_columns.rs:215:33
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::index::slice_end_index_len_fail_rt
   3: core::slice::index::slice_end_index_len_fail
   4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   5: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
   6: <nu_command::viewers::table::PagingTableCreator as core::iter::traits::iterator::Iterator>::next
   7: <nu_protocol::value::stream::RawStream as core::iter::traits::iterator::Iterator>::next
   8: nu_protocol::pipeline_data::print_if_stream
   9: nu_protocol::pipeline_data::PipelineData::print
  10: nu_cli::util::eval_source
  11: nu_cli::repl::evaluate_repl
  12: nu::run::run_repl
  13: nu::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
root@b913c261a5c5:/project# 
```

### Configuration

```
/project> version | transpose key value | to md --pretty
```

| key                | value                                                   |
| ------------------ | ------------------------------------------------------- |
| version            | 0.82.0                                                  |
| branch             |                                                         |
| commit_hash        | ecdb023e2f6cb17445ae799206e464b2daef3d71                |
| build_os           | linux-x86_64                                            |
| build_target       | x86_64-unknown-linux-gnu                                |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)                     |
| rust_channel       | 1.68.2-x86_64-unknown-linux-gnu                         |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)                     |
| build_time         | 2023-06-27 17:34:21 +00:00                              |
| build_rust_channel | release                                                 |
| allocator          | standard                                                |
| features           | default, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  |                                                         |

**Comment by sholderbach** [comment]
Thanks for including an easy minimal reproducible example and a helpful backtrace!

**Comment by fdncred** [comment]
That's my bug, sorry. But I bet it's pretty easily fixed if someone wants to add a PR.
