### ISSUE TITLE
Table literals not compatible with table types

### ISSUE THREAD

**Issue by sophiajt** [nushell/nushell#9659]
### Describe the bug

Here's an example of where the type checker isn't flexible enough with the table literals:

```
> def foo [x: table<y: int>] { }
> foo [{y: 123}]
Error: nu::parser::type_mismatch

  × Type mismatch.
   ╭─[entry #3:1:1]
 1 │ foo [{y: 123}]
   ·     ─────┬────
   ·          ╰── expected table<y: int>, found list<record<y: int>>
   ╰────
```

cc @1Kinoti - who worked on table types

### How to reproduce

1. Follow the example above

### Expected behavior

The above should allow a `list<record<y: int>>` to be compatible with `table<y: int>` as these two things are compatible.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.82.1                                   |
| branch             | main                                     |
| commit_hash        | e10d84b72fedf1f5d44baeeb353fe27b48633c00 |
| build_os           | macos-aarch64                            |
| build_target       | aarch64-apple-darwin                     |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)      |
| rust_channel       | 1.68.2-aarch64-apple-darwin              |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)      |
| build_time         | 2023-07-12 06:06:20 +12:00               |
| build_rust_channel | debug                                    |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by 1Kinoti** [comment]
@jntrnr wouldn't this need some 'casting'? 

yeah, `list<record>` is a basically a `table`, but do we want this behavior?

**Comment by jntrnr** [comment]
@1Kinoti - Yes, `table` and `list<record>` are compatible if their fields are compatible. That's without any casting.

**Comment by weirdan** [comment]
This works now:

```console
$ def foo [x: table<y: int>] { $x | first }
$ foo [{y: 123}]
╭───┬─────╮
│ y │ 123 │
╰───┴─────╯
```
