### ISSUE TITLE
`cp a b c /tmp/` is invalid syntax

### ISSUE THREAD

**Issue by hyiltiz** [nushell/nushell#9661]
### Describe the bug

Should `cp a b c /tmp/` be valid syntax?

Currently, all of the following are valid syntax:
```
cp a /tmp/
cp a b
cp *.a /tmp/
cp -r a/ /tmp/
```

But `cp a b c /tmp/` is invalid syntax. This is quite useful since selectively copying (or moving, for that matter) is quite a common operation to do. The simplest workaround I can think of is `[a b c] | each {|x| cp $x /tmp/}`. `rsync`, `scp` and `cp` are all not confused by multiple `sources` being copied into a single `destination`. The `cp` build-in from nushell should probably behave similarly.

Maybe (burrowing from Haskell) considering these types of operations are quite common, we introduce a special type of ~~pipe~~ operator  (like `<$>`) that treats whatever comes after as a closure and defines a special variable. Basically, a syntax sugar that allows writing `[a b c] | each {|x| cp $x /tmp/}` as `[a b c] <$> cp $x /tmp/`? The syntax sugar feels different from Nushell flavor; not only the cryptic characters but also the fact of binding the iterator variable implicitly to a special name. We are trying to maybe make the special variable name `$in` not so special (in another issue), so I would prefer against this direction. 

### How to reproduce

1. type `cp a b c /tmp/`
2. get surprised by seeing syntax error `Error: nu::parser::extra_positional`

### Expected behavior

Each of `a b c` are copied inside `/tmp/`.

### Configuration

| key                | value                                                                                                                                                                                                     |
| ------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.82.1                                                                                                                                                                                                    |
| branch             | main                                                                                                                                                                                                      |
| commit_hash        | 7e39179b7f981ba8e5de231cd14c28e6c962e83a                                                                                                                                                                  |
| build_os           | macos-aarch64                                                                                                                                                                                             |
| build_target       | aarch64-apple-darwin                                                                                                                                                                                      |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)                                                                                                                                                                       |
| rust_channel       | 1.68.2-aarch64-apple-darwin                                                                                                                                                                               |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)                                                                                                                                                                       |
| build_time         | 2023-07-03 14:01:08 -05:00                                                                                                                                                                                |
| build_rust_channel | release                                                                                                                                                                                                   |
| allocator          | standard                                                                                                                                                                                                  |
| features           | dataframe, default, extra, sqlite, trash, which, zip                                                                                                                                                      |
| installed_plugins  | custom-value generate, custom-value generate2, custom-value update, from eml, from ics, from ini, from vcf, gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml |

**Comment by sholderbach** [comment]
Effectively a duplicate of the issue for `mv` #8461

**Comment by hyiltiz** [comment]
Closing in preference of #8461.
