### ISSUE TITLE
Hwo to invoke a custom command when using `nu -c`?

### ISSUE THREAD

**Issue by robrecord** [nushell/nushell#9672]
### Question

I have a custom command created in my nushell's `env.nu` that does something, whch works normally when logged in to nushell.

I want to open a new terminal pane with this command. I have tried using the command directly with the command to open a new pane, in this case `zellij run -- <commands>` but it doesn't work (as below).

Then I tried invoking a new nushell instance with `nu` to see if the command works this way, and I get the same issue. I am doing `nu -c <my-custom-command>` and the error is "executable was not found". This suggests the command definition in env.nu has not been parsed before attempting to run my command. I believe I have tried passing --login and --interactive to `nu` but neither seem to make a difference in this case.

How would one get this to work? Or is it a bug?

Many thanks.

### Additional context and details

My custom command in env.nu:

```nu
def trellis-sync [
  environment: string = "staging"
  --type (-t): string = "all"
  --dir (-d): string = "pull"
  ] {
  let verb = 'from'
  if ($type == 'push') { verb = 'to' }
  let site = ( trellis info | lines | parse "{site_env} => {site}" | first | get site )

  [$site $dir $type $verb $environment]

  trellis exec bin/sync.sh $environment $site $type $dir
}
```

My command to invoke it all:

`nu -c trellis-sync`

The error I get:

```
Error: nu::shell::external_command

  × External command failed
   ╭─[source:1:1]
 1 │ trellis-sync
   · ──────┬─────
   ·       ╰── executable was not found
   ╰────
  help: No such file or directory (os error 2)
```

**Comment by fdncred** [comment]
I think you'll have more success doing it like this, assuming you're starting from within nushell. If it's in your env.nu, you need to ensure it's sourced.
```
nu --env-config $nu.env-path -c 'your_command_name'
```
The way I figured this out is doing this.

Show what custom commands are available without any parameters.
```
nu -c 'scope commands | where is_custom == true'
```
Show what custom commands are available by passing the env.nu
```
nu --env-config $nu.env-path -c 'scope commands | where is_custom == true'
```
Show what custom commands are available by passing the config.nu and env.nu
```
nu --env-config $nu.env-path --config $nu.config-path -c 'scope commands | where is_custom == true'
```

**Comment by fdncred** [comment]
>  I just found I could do it with nu -e but ...

Ya, I believe `nu -e` is really meant to do something like set a starting directory like `nu -e 'cd /some/path/to/start/in'` and stay in nushell so you can keep working.

> Can I just say  ...

You're welcome. So glad you're enjoying nushell.
