### ISSUE TITLE
`return` does not check the type correctly

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#9697]
related to
- https://github.com/nushell/nushell/pull/9690

### Describe the bug

i was trying to play with the new input / output annotations and type checking and found that `return` does not appear to work well with them :thinking: 

### How to reproduce

1. define the following command
```nushell
def f [x: int]: any -> int { return (2 * $x) }
```
2. see the error
```
Error: nu::parser::output_type_mismatch

  × Command output doesn't match int.
   ╭─[entry #13:1:1]
 1 │ def f [x: int]: any -> int { return (2 * $x) }
   ·                              ───────┬───────
   ·                                     ╰── command doesn't output int
   ╰────
```

### Expected behavior

i expected this to work as the few following workaround
- no `return`
```nushell
def f [x: int]: any -> int { 2 * $x }
```
- annotate the output type with `any`
```nushell
def f [x: int]: any -> any { return (2 * $x) }
```
- remove the type annotation
```nushell
def f [x: int] { return (2 * $x) }
```

none of these give an error and they all double the input :ok_hand: 

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.82.1                                   |
| branch             | main                                     |
| commit_hash        | 57d96c09fa78f6231093cb241da4ddbd545f84bf |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)      |
| rust_channel       | 1.69.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)      |
| build_time         | 2023-07-15 12:59:41 +02:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | hist, plot                               |

**Comment by fdncred** [comment]
Will adding a new input_output_type in `return` fix the problem?
```nushell
            .input_output_types(vec![
                (Type::Nothing, Type::Nothing),
                (Type::Nothing, Type::Any),
            ])
```

**Comment by amtoine** [comment]
@fdncred 
as you can see in #9701, it appears to fix the issue :wink:

**Comment by amtoine** [comment]
completed in https://github.com/nushell/nushell/pull/10067
