### ISSUE TITLE
allow assignement without parentheses

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#9698]
related to 
- #9658
- #9589 

> **Note**  
> this is mainly a note for myself not to forget about this :relieved: 

### Related problem

with #9658 and #9589, we can now *not* use the parentheses around pipelines to declare constants with `let` and varibles with `mut` :partying_face: 

i think it would make sense to have the same feature for variable assignment.

### Describe the solution you'd like

allow to write things like
## mutable variables
```nushell
mut a = ls | get name
$a = ls | where type == file | get name
```
and get the output of the `ls | where type == file | get name` inside the `$a` variable.

now we get the following parser error
```
Error: nu::parser::input_type_mismatch

  × Command does not support nothing input.
   ╭─[entry #2:1:1]
 1 │ $a = ls | where type == file | get name
   ·           ──┬──
   ·             ╰── command doesn't support nothing input
   ╰────
```

## `$env` mutation
allow
```nushell
$env.PATH = $env.PATH
    | split row (char esep)
    | prepend ($env.HOME | path join ".local" "bin")
    | prepend ($env.CARGO_HOME | path join "bin")
    | uniq
```
instead of
```nushell
$env.PATH = (
    $env.PATH
        | split row (char esep)
        | prepend ($env.HOME | path join ".local" "bin")
        | prepend ($env.CARGO_HOME | path join "bin")
        | uniq
)
```

**Comment by amtoine** [comment]
i also think allowing the same with `const` would make sense :+1:

**Comment by agirardeau** [comment]
The docs at https://www.nushell.sh/book/configuration.html#path-configuration actually say to set $env.PATH without parentheses:

```nu
$env.PATH = $env.PATH | split row (char esep)
  | append /usr/local/bin
  | append ($env.CARGO_HOME | path join bin)
  | append ($env.HOME | path join .local bin)
  | uniq # filter so the paths are unique
```

But adding this to my env.nu produces the same `command doesn't support nothing input` error as reported above. I'm on 0.93.0.

It seems like the docs need to be fixed.

**Comment by sholderbach** [comment]
Closing this in favor of the more general #12956
