### ISSUE TITLE
`unknown mime-type` error when using hat symbol/run-external for internal command

### ISSUE THREAD

**Issue by EmilySeville7cfg** [nushell/nushell#9708]
### Describe the bug

`unknown mime-type` error when using hat symbol/`run-external` for internal command. Error is not beautifully shown like when performing some wrong math `4 + "a"`, just as plain text.

### How to reproduce

1. `^print 1`
2. Get:

```
Warning: unknown mime-type for "1" -- using "application/octet-stream"
Error: no such file "1"
```

### Expected behavior

More user-friendly error, explaining that ^ should be used just for external commands.

### Screenshots

![image](https://github.com/nushell/nushell/assets/42812113/04aa49cc-8182-4490-a208-b2a014c0e72f)

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.82.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25) |
| build_time         | 2023-07-05 21:30:32 +10:00          |
| build_rust_channel | release                             |
| allocator          | standard                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
So, `^` means run the external command, and you're getting the error from the external command, right? It looks like you have an external `print` command in your path somewhere.

**Comment by amtoine** [comment]
@EmilySeville7cfg 
i think you are seeing an error from the external `print` command, not from Nushell :open_mouth: 

i think it's platform specific, here's what i see without a `print` command  on my system
```nushell
> ^print 1
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #1:1:1]
 1 │ ^print 1
   ·  ──┬──
   ·    ╰── 'print' was not found
   ╰────
  help: No such file or directory (os error 2)
```
