### ISSUE TITLE
Output redirection fail to work inside `each`

### ISSUE THREAD

**Issue by EmilySeville7cfg** [nushell/nushell#9709]
### Describe the bug

Output redirection fail to work inside `each`:

```nushell
1..5 | each {|$el|
    echo $el out> $'($el).txt'
}
```

### How to reproduce

1. Run:

```nushell
1..5 | each {|$el|
    echo $el out> $'($el).txt'
}
```

2. Get:

```
Error: nu::shell::eval_block_with_input

  × Eval block failed with pipeline input
    ╭─[/home/emilyseville7cfg/Documents/open-source/nu/warp-doc-parser/parser.nu:14:1]
 14 │ 
 15 │ 1..5 | each {|$el|
    · ┬
    · ╰── source value
 16 │     echo $el out> $'($el).txt'
    ╰────

Error: nu::shell::command_not_found

  × Command not found
    ╭─[/home/emilyseville7cfg/Documents/open-source/nu/warp-doc-parser/parser.nu:15:1]
 15 │ 1..5 | each {|$el|
 16 │     echo $el out> $'($el).txt'
    ·              ──┬─
    ·                ╰── command not found
 17 │ }
    ╰────
```

### Expected behavior

No error, just 1.txt, 2.txt, ..., 5.txt created.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.82.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25) |
| build_time         | 2023-07-05 21:30:32 +10:00          |
| build_rust_channel | release                             |
| allocator          | standard                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  |                                     |

### Additional context

As a result I can't run this code without an error:

```nushell
# Convert XPath to CSS path
def "to css-path"  [number: int] {
    let prefix = '/html/body/div[1]/div/div/div[2]/div/div[2]/div/div/main/div[2]/div[1]/div/'
    let suffix = '/div/div/div/div/div/div/div/div/div/div/div/div/div/table'
    $"($prefix)div[($number)]($suffix)" |
        str replace '^/html/body/' '' |
        str replace --all '/' ' > ' |
        str replace --all '\[(..?)\]' ':nth-of-type($1)'
}

9..17 | filter {|el| $el mod 2 != 0} | each {|$el|
    ^pup --file doc.html (to css-path $el) out> $'($el).txt'
}
```

Goal: extract all tables by CSS paths separately with [pup](https://github.com/ericchiang/pup) CLI tool.

**Comment by fdncred** [comment]
nice catch. no idea why `out>` gives command not found here. so odd.

**Comment by hardfau18** [comment]
What i experienced is that ` out> file` file should be plain string, ~, $ () won't work

**Comment by fdncred** [comment]
oh ya, that sounds vaguely familiar. This works, although not the way we want it to.
```nushell
1..5 | each {|$el|
    echo $el out> 1.txt
}
```
