### ISSUE TITLE
`load-env` does not accept "table" input

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#9710]
### Describe the bug

according to the [cookbook](https://www.nushell.sh/cookbook/misc.html#manage-ssh-passphrases) and this is what i use in my [config](https://github.com/goatfiles/dotfiles/blob/8105a43/.config/nushell/env.nu#L167-L172
), `load-env` can be used to start an `ssh-agent` with
```nushell
ssh-agent -c
    | lines
    | first 2
    | parse "setenv {name} {value};"
    | transpose -i -r -d
    | load-env
```

however, i get the following error :thinking: 

```nushell
Error: nu::parser::input_type_mismatch

  × Command does not support table input.
   ╭─[entry #1:5:1]
 5 │     | transpose -i -r -d
 6 │     | load-env
   ·       ────┬───
   ·           ╰── command doesn't support table input
   ╰────
```

### How to reproduce

1. run the `ssh-agent` pipeline above
2. see the error

### Expected behavior

i expected this to work as before, because when we have a look at the types...

```nushell
ssh-agent -c
    | lines
    | first 2
    | parse "setenv {name} {value};"
    | transpose -i -r -d
    | describe
```
gives
```
record<SSH_AUTH_SOCK: string, SSH_AGENT_PID: string>
```
but the output is
```
╭───────────────┬───────────────────────────────────╮
│ SSH_AUTH_SOCK │ /tmp/ssh-XXXXXXjnY3Gw/agent.13242 │
│ SSH_AGENT_PID │ 13244                             │
╰───────────────┴───────────────────────────────────╯
```
which is a record, not a table, right?

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.82.1                                   |
| branch             | main                                     |
| commit_hash        | 5bfec2024425f4a0cfb8400ed3d25b83cd6d1fe2 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)      |
| rust_channel       | 1.69.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)      |
| build_time         | 2023-07-16 09:56:57 +02:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | hist                                     |

### Additional context

a workaround i've found is to run the following instead
```nushell
ssh-agent -c
    | lines
    | first 2
    | parse "setenv {name} {value};"
    | transpose -i -r -d
    | to nuon
    | from nuon
    | load-env
```

> **Note**
> the `to nuon` and `from nuon` trick should not be there imo

**Comment by amtoine** [comment]
the fun thing is that the `to nuon` / `from nuon` trick does not even change the type of the record :laughing: 
```nushell
> let ssh_env = ssh-agent -c
     | lines
     | first 2
     | parse "setenv {name} {value};"
     | transpose -i -r -d
> ($ssh_env | describe) == ($ssh_env | to nuon | from nuon | describe)
true
```

**Comment by fdncred** [comment]
I think this is another error with input_output_types. I added this and it seems to work.
```rust
    fn signature(&self) -> nu_protocol::Signature {
        Signature::build("load-env")
            .input_output_types(vec![
                (Type::Record(vec![]), Type::Nothing),
                (Type::Nothing, Type::Nothing),
                (Type::Table(vec![]), Type::Nothing), // <-- i added this line
            ])
            .allow_variants_without_examples(true)
            .optional(
                "update",
                SyntaxShape::Record(vec![]),
                "the record to use for updates",
            )
            .category(Category::FileSystem)
    }
```

**Comment by amtoine** [comment]
funny enough
```nushell
ssh-agent -c
    | lines
    | first 2
    | parse "setenv {name} {value};"
    | transpose -r
    | into record
    | load-env
```
also works and all these objects are the same :eyes:

this looks more and more like a parser / type system issue, not an input / output missing in `load-env` :thinking:

**Comment by amtoine** [comment]
for instance, why does this script only fail in the last line??
```nushell
let raw = ssh-agent -c | lines | first 2 | parse "setenv {name} {value};"

# three methods
let a = $raw | transpose -r | into record
let b = $raw | transpose -rid | to nuon | from nuon
let c = $raw | transpose -rid

use std assert

# a == b == c
assert equal $a $b
assert equal $b $c

# a, b and c have the same type
assert equal ($a | describe) ($b | describe)
assert equal ($b | describe) ($c | describe)

# load-env works with all of them when coming from a variable
$a | load-env
$b | load-env
$c | load-env

$raw | transpose -r | into record | load-env
$raw | transpose -rid | to nuon | from nuon | load-env
$raw | transpose -rid | load-env  # only this last one fails when not from a variable
```
gives
```
Error: nu::parser::input_type_mismatch

  × Command does not support table input.
    ╭─[entry #17:24:1]
 24 │ $raw | transpose -rid | to nuon | from nuon | load-env
 25 │ $raw | transpose -rid | load-env  # only this last one fails when not from a variable
    ·                         ────┬───
    ·                             ╰── command doesn't support table input
    ╰────
```
at parse-time :eyes:

**Comment by cig0** [comment]
> funny enough
> 
> ```nushell
> ssh-agent -c
>     | lines
>     | first 2
>     | parse "setenv {name} {value};"
>     | transpose -r
>     | into record
>     | load-env
> ```
> 
> also works and all these objects are the same eyes
> 
> this looks more and more like a parser / type system issue, not an input / output missing in `load-env` thinking

Hi all. This is *so weird*.

I came across this issue as well. After playing for a while with the stuff @amtoine shared here and getting the very same errors, Nu is now able to process the original `transpose` line correctly! :exploding_head:

![image](https://github.com/nushell/nushell/assets/394089/10c305b3-4aff-4b44-a5b5-4f8c17f637e7)

**Comment by fdncred** [comment]
Just to simplify a little.
```nushell
let raw = ssh-agent -c | lines | first 2 | parse "setenv {name} {value};"
$raw | transpose -ird | load-env
```
gives this error
```
Error: nu::parser::input_type_mismatch

  × Command does not support table input.
   ╭─[entry #2:1:1]
 1 │ $raw | transpose -ird | load-env
   ·                         ────┬───
   ·                             ╰── command doesn't support table input
   ╰────
```
if I add `(Type::Table(vec![]), Type::Nothing),` to the input_output_types() it works.

The puzzling part is that transpose returns a record. If it's returning a record, why does it fail since load-env supports record inputs.
```nushell
❯ $raw | transpose -ird | describe
record<SSH_AUTH_SOCK: string, SSH_AGENT_PID: string>
```
