### ISSUE TITLE
Expand ~ when given to external commands

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#972]
**Describe the bug**
If ~ is used as part of a path to an external command, it's given as-is without any expansion.

**To Reproduce**
1. `vi ~/.config/starship.toml`
2. Notice it tries to create a new directory instead of going to the correct directory
3. sadness

**Expected behavior**
Expand ~ as a special symbol given to external

**Configuration (please complete the following information):**
 - OS: Linux
 - Version: 0.5.1 (master)
 - Optional features: all

**Comment by naufraghi** [comment]
But do not expand always, for example in `nushell 0.6.0` running this:
```
git diff HEAD~3 --numstat
```
results in an incorrect expansion:
```
fatal: ambiguous argument 'HEAD/home/matteo3': unknown revision or path not in the working tree.
```

**Comment by naufraghi** [comment]
With a fast check with `echo ~` variations in bash, only these two patterns are expanded:

- `^~$`
- `^~/.*`

**Comment by naufraghi** [comment]
This test fails (modelled as `command_cd_tests.rs`, but just because I was searching for some `~`):

```rust
#[test]
fn spawn_external_process_with_tilde_in_arguments() {
    Playground::setup("do_not_expand_tilde", |dirs, _| {
        let actual = nu!(
            cwd: dirs.test(),
            r#"
                sh -c "echo 1~1"
            "#
        );

        assert_eq!(actual, "1~1");
    })
}
```

**Comment by jonathandturner** [comment]
@naufraghi - I just saw your comment today. Yes, that sounds good. If we follow Bash's logic, that sounds good to me.

**Comment by naufraghi** [comment]
I can hardly follow the parsing code, do you have some hints where to start digging @jonathandturner ?

**Comment by jonathandturner** [comment]
I believe `~` is handled in a couple places.

For external commands, it's in: src/commands/classified/external.rs.  eg) lines 111, 113, 129, 131 (there may be others, but those are the ones I saw)

For internal commands I'm not exactly sure. @wycats - do you know where ~ is handled in the current parser?

**Comment by naufraghi** [comment]
Ok, half way done, Linux passes the test (the parser seems to be OK and not splitting around `~`), but windows fails:

```
---- spawn_external_process_with_home_in_arguments stdout ----
thread 'spawn_external_process_with_home_in_arguments' panicked at 'assertion failed: `(left == right)`
  left: `"/c/Users/VssAdministrator"`,
 right: `"C:\\Users\\VssAdministrator"`', tests\external_tests.rs:26:9
```

Here I have no idea of what is the expected result for a windows user.

**Comment by jonathandturner** [comment]
@naufraghi - we're currently using https://crates.io/crates/dirs to help us with things like "what is the home directory?"  You can see some examples at that link for home_dirs for different OSes.

**Comment by naufraghi** [comment]
At the and I modified the test to be less precise @jonathandturner . The correct expansion is delegated to `shellexpand` and, as annotated in the commit message, there is an open issue to move to `dirs` netvl/shellexpand#3. That should fix the windows compatibility problem just bumping the version used here.
