### ISSUE TITLE
tilde "~" is not consistenly interpreted

### ISSUE THREAD

**Issue by JakeEhrlich** [nushell/nushell#9723]
### Describe the bug

if I run `ls ~` nu will list the contents of my home directory. However if I run the following:

`./zellij/zellij setup --dump-config out> ~/.config/zellij/config.kdl`

...then I get an error saying "no such file or directory", this is fairly confusing but I eventually figured out that it was because of the tilde being interpreted literally rather than expanded as home. I think nu should do one of the following

1) be consistent everywhere you can be and this case should be a "can be"
2) Provide a better error message that just briefly explains the issue and offered a better way to solve the problem.

### How to reproduce

run `./zellij/zellij setup --dump-config out> ~/.config/zellij/config.kdl`

### Expected behavior

Either an error message or for ~ to be substituted with $env.HOME

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.82.1                                   |
| branch             | main                                     |
| commit_hash        | b2043135ed956ead0d3b5d5df49ea9d929dc7120 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)      |
| rust_channel       | 1.68.2-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)      |
| build_time         | 2023-07-12 23:26:13 -05:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by hardfau18** [comment]
Same issue #9709

**Comment by hardfau18** [comment]
I thought both are similar because both lacks string expansion,

**Comment by sholderbach** [comment]
Ah right yeah in #8517 it also affects the `out>`/`err>` syntax sugar. Yeah it probably should consistently support both file path and string expansion as it only expects paths.

I was thinking about more general file path expansion which is a bit more tricky to be not surprising.

**Comment by WindSoilder** [comment]
Hi, normally we don't want to auto interpreted `~`, because it causes too much issues. see: #7673 #4205  #6993

But after the pr #9747, I hope you can have a workaround for it like the following:

```nushell
./zellij/zellij setup --dump-config out> ("~/.config/zellij/config.kdl" | path expand)
```

**Comment by BatmanAoD** [comment]
@WindSoilder Are you saying that `ls ~` should behave the same as `ls '~'`? If not, what are the expected rules for when `~` _should_ be expanded?

**Comment by WindSoilder** [comment]
@BatmanAoD Sorry it's not.
For nushell builtin command, you can expected it to auto-expanded if the type of parameter is `<path>` or `<glob>`, take `open/ls` as example:
```nushell
❯ open -h
Load a file into a cell, converting to table if possible (avoid by appending '--raw').
...
Parameters:
  filename <path>: the filename to use (optional)
❯ du -h
Find disk usage sizes of specified items.
...
Parameters:
  path <glob>: starting directory (optional)
```
`ls`, `glob` are a little bit special, it takes a string, but we'll auto-expanded it too.

-------------
The importand parts are cases for external commands(anything not builtin command), this is where all these issue happened:
If you pass a bare word, it will auto-expand, if pass a quoted string, it won't auto-expand, take the following as example:
```nushell
^ls ~/a     # auto expanded
^ls `~/a` # auto expanded too, because backquoted word are treated as bare word.
^ls "~/a"  # not auto expanded
^ls '~/a'   # not auto expanded
```

**Comment by BatmanAoD** [comment]
So the remaining issue for this thread is that `~` expansion doesn't happen by default after `e>`, `o>`, etc.? Would it be reasonable to always treat the value after `o>` as a path?

**Comment by WindSoilder** [comment]
Oh, I just found that it'll always be expanded.
So we don't need `path expand` in the following code:
```nushell
`./zellij/zellij setup --dump-config out> ("~/.config/zellij/config.kdl" | path expand)`
```
Instead we just need to `./zellij/zellij setup --dump-config out> ~/.config/zellij/config.kdl`

**Comment by WindSoilder** [comment]
So I'll close the issue, feel free to re-open it if you have different idea.

Currently in redirection context, we'll always do `~` expansion.

**Comment by BatmanAoD** [comment]
The use-case in the original comment does work; thanks!

However, the behavior still seems weird to me. https://github.com/nushell/nushell/issues/4205 is closed, but it seems that the approach chosen is to make it only possible to prevent expansion with _external_ commands. Why the inconsistency? I.e. why not just let quotes suppress tilde-expansion _always_?
