### ISSUE TITLE
function body can't uses variable which out of scope

### ISSUE THREAD

**Issue by WindSoilder** [nushell/nushell#9724]
### Describe the bug

It's a little hard to express, please see the following reproduce steps.

### How to reproduce

Run the following code:
```nushell
 do { 
    let b = 3
    def c [] { echo $b }
    c 
 }
```
It gives me an error: `variable not found`, it seems that `$b` is not found in the function body.

### Expected behavior

I expected nu to return 3.

### Configuration

| key                | value                                                   |
| ------------------ | ------------------------------------------------------- |
| version            | 0.82.1                                                  |
| branch             | nightly                                                 |
| commit_hash        | bd0032898fe4697f8f1f9e48b3bb904f87608fcb                |
| build_os           | linux-x86_64                                            |
| build_target       | x86_64-unknown-linux-gnu                                |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)                     |
| rust_channel       | 1.68.2-x86_64-unknown-linux-gnu                         |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)                     |
| build_time         | 2023-07-12 02:15:14 +00:00                              |
| build_rust_channel | release                                                 |
| allocator          | mimalloc                                                |
| features           | default, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  |                                                         |

### Additional context

If I run these command in repl directly, it works fine:
```nushell    
let b = 3
def c [] { echo $b }
c
``` 

It's relative to: #5994

**Comment by fdncred** [comment]
same result for `const b = 3`, fwiw.

**Comment by 1Kinoti** [comment]
isn't this the expected behavior?

comparing with rust
```rs
fn a() {
   let x = 0;
   fn b() { x }
   ^^^^^^^^^^^^
         |
          errors with something like, cannot capture variable,
          what you need here is a closure
}
```

imo, this should be the behavior, it's the error message that needs some work

**Comment by 1Kinoti** [comment]
unfortunately, unlike in rust, `const` is not a top level item in nu. so i still think that this is the expected behavior (unless `const` is made a top level item)

**Comment by WindSoilder** [comment]
So, the issue becomes to...
```
let b = 3
def c [] { echo $b }
c
```
works in repl and in a script

**Comment by WindSoilder** [comment]
Closing this in favor of #9746
