### ISSUE TITLE
`Signature::vectorizes_over_list` not useful at runtime only relevant to test.

### ISSUE THREAD

**Issue by sholderbach** [nushell/nushell#9734]
When defining the input and output types https://github.com/nushell/nushell/pull/6796 already added the capability to declare that a command operates on a single scalar of a type AND a whole list/vector of this type. This can be indicated by the `Signature::vectorizes_over_list` method and field. But this only affects the rough testing done for the `Example`s. Here this field is checked to see if the `Example`s are member of the set of declared `input_output_types`.

The runtime type checker that is much more effective since #9680 does not take this into account at all. Thus several commands that support both scalar as well as list/stream values currently need to be updated in their type signature (see for example https://github.com/nushell/nushell/pull/9683)

Either we support the `vectorizes_over_list` field in the type check as well or we remove it and update all necessary signatures manually.

**Comment by fdncred** [comment]
I think I'd vote to remove it as I'd rather have the supported types listed in input_output_types(), otherwise some types will be hidden and less obvious.
