### ISSUE TITLE
Accept records for http subcommand headers (-H)

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#9743]
### Related problem

Today, `http <subcommand> -H` takes a list in the form:

```nushell
[my-header-key-A my-header-value-A my-header-key-B my-header-value-B]
```

### Describe the solution you'd like

It seems to me that a more readable (and idiomatic) approach would be that any structure of key/value pairs should be a  list of records:

```nushell
> let reqHeaders = {
    Cookie:  "acc=barfoo",
    User-Agent: "Mozilla/7.0 (Windows NT 33.0; Win64; x64) AppleWebKit/1038.90 (KHTML, like Gecko)"
}
> http get -H $reqHeaders https://example.com
```

This would also be easier to manipulate using standard Nushell constructs.  E.g.:

```nushell
> $reqHeaders | insert Authorization "Bearer foobar"
╭───────────────┬───────────────────────────────────────────────────────────────────────────────────╮
│ Cookie        │ acc=barfoo                                                                        │
│ User-Agent    │ Mozilla/7.0 (Windows NT 33.0; Win64; x64) AppleWebKit/1038.90 (KHTML, like Gecko) │
│ Authorization │ Bearer foobar                                                                     │
╰───────────────┴───────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by fdncred** [comment]
Seems like a reasonable request to me. I think records are more intuitive for this type of thing.

**Comment by jflics6460** [comment]
Hi! I'm new to NuShell. Since this ticket was marked as a good first issue, I would like to try picking it up. How do I assign it to myself?

**Comment by fdncred** [comment]
we're not too big on assignments but when people ask to be assigned we try to do it, as i just did for you.
