### ISSUE TITLE
How to remove existing sqlite history entries with a leading space?

### ISSUE THREAD

**Issue by mksinicus** [nushell/nushell#9744]
### Question

Nushell 0.82 allows excluding lines from the history by marking it with a leading space. The problem is, I already have multiple entries with a leading space in my history file. How do I delete them, so that they don't pop up every time I type a leading space? (I am not familiar with SQL stuffs)

1. Can I do it with Nushell? `into sqlite` doesn't seem to work with multiple tables.
    ````nushell
    > open $nu.history-path | into sqlite history.bak.sqlite3
    Error: nu::shell::only_supports_this_input_type

      × Input type not supported.
       ╭─[entry #25:1:1]
     1 │ open $nu.history-path | into sqlite history.bak.sqlite3
       ·                         ─────┬─────┬
       ·                              │     ╰── input type: SQLiteDatabase
       ·                              ╰── only list input data is supported
       ╰────
      ````
2. Or must I use some external applications?

Thanks!

**Comment by mksinicus** [comment]
After a bit of research I adapted a solution from <https://github.com/nushell/nushell/issues/9403>, using `query db`:

```nushell
open $nu.history-path | query db "DELETE FROM history WHERE command_line LIKE ' %'"
```

I am a bit confused though, so maybe I will leave this issue open for one more question:

I thought `open` reads something into the memory without being able to modify it, since normally it would require an explicit command like `save` to write to disk. And `query` does not look like it can write something to the disk. Was it intentional, that `query db` may directly modify the database *file* piped to it?

**Comment by fdncred** [comment]
It's intentional that `query db` can modify sqlite databases. The key to understanding this here is that your one-liner above is two using two different languages, nushell and sql. `query db` supports the sql language which allows you to modify things. So, (mostly) anything that sqlite allows in it's sql dialect should be possible using `query db`.

**Comment by mksinicus** [comment]
I see! Thanks for clarifying.
