### ISSUE TITLE
Par-each no longer supports range input as of nu 0.82.1

### ISSUE THREAD

**Issue by RickCogley** [nushell/nushell#9748]
### Describe the bug

As of nu 0.82.1 compiled today, I'm getting an error that "command doesn't support range input" on this: 

https://github.com/RickCogley/dotfiles/blob/main/nushell/Library/Application%20Support/nushell/scripts/nupass.nu#L40

Please see: 

https://discord.com/channels/601130461678272522/1131400430820270110/1131400430820270110

### How to reproduce

With nu 0.82.1, @amtoine did some testing to reproduce (thanks!), copying from the discord: 

the following commands do not parse

```
1..2 | par-each {|it| print $it}
1..2 | par-each {|it| $it}
1..2 | par-each {}
```

same with 2 being a variable, e.g. let n = 2

```
1..$n | par-each {|it| print $it}
1..$n | par-each {|it| $it}
1..$n | par-each {}
```

the error is like

```
Error: nu::parser::input_type_mismatch

  × Command does not support range input.
   ╭─[entry #6:1:1]
 1 │ 1..2 | par-each {|it| print $it }
   ·        ────┬───
   ·            ╰── command doesn't support range input
   ╰────
```

the following work fine

```
1..2 | par-each { print $in }
1..2 | par-each { $in }
1..$n | par-each { print $in }
1..$n | par-each { $in }
```

all the commands above parse correctly with each instead of par-each

### Expected behavior

I expect nu to be able to accept a range input on par-each.

### Screenshots

![image](https://github.com/nushell/nushell/assets/512328/98eead24-84a3-4e87-ac96-ca9ee6851aa6)

### Configuration

❯ > version | transpose key value | to md --pretty
| key                | value                                                                                                   |
| ------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.82.1                                                                                                   |
| branch             | main                                                                                                   |
| commit_hash        | 2d557bce5d7ca34ca77ef5a1ce97da6943f9699f                                                                                                   |
| build_os           | macos-x86_64                                                                                                   |
| build_target       | x86_64-apple-darwin                                                                                                   |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31) (built from a source tarball)                                                                                                   |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)                                                                                                   |
| build_time         | 2023-07-20 04:40:01 +09:00                                                                                                   |
| build_rust_channel | release                                                                                                   |
| allocator          | standard                                                                                                   |
| features           | dataframe, default, sqlite, trash, which, zip                                                                                                   |
| installed_plugins  | custom-value generate, custom-value generate2, custom-value update, from eml, from ics, from ini, fromvcf, gstat, inc, nu-example-1, nu-example-2, nu-example-3, query, query json, query web, query xml |

**Comment by fdncred** [comment]
I'm guessing this is because `par-each` doesn't have Type::Range as an input_output_type. Should be an easy fix.

In the mean time, it supports lists so you should be able to do `[1 $n] | par-each`. `[1 $n]` vs `1..$n`.

**Comment by RickCogley** [comment]
Hi, I recompiled again this AM and now this works again. Thanks :)
