### ISSUE TITLE
result of external command is not assigned with `let foo = ...`

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#9767]
### Describe the bug

when not using parentheses in a `let` assignment with external commands, it appears the value is not captured by the variable.

### How to reproduce

1. run `let output = "yes\nno" | fzf; print $"output: ($output)"` and observe
```
yes
output:
```
2. run `let output = git branch --show-current; print $"output: ($output)"` from a Git repo and observe
```
main
output:
```

### Expected behavior

i expected the return values of the external commands to be captured in the variables, i.e.
```nushell
> let output = "yes\nno" | fzf; print $"output: ($output)"
output: yes
```
```nushell
> let output = git branch --show-current; print $"output: ($output)"
output: main
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.82.1                                   |
| branch             | main                                     |
| commit_hash        | 656f707a0be48d04c356cc307450213ef1a39619 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)      |
| rust_channel       | 1.69.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)      |
| build_time         | 2023-07-17 19:32:26 +02:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | hist, plot                               |

### Additional context

the commands above work by either
- wrapping the pipeline in parentheses
- adding `str trim` (any internal command?) after the call to the external command

**Comment by mengsuenyan** [comment]
In the nushell document, the external command need to use `complete` to capture `stdout, stderr, exit_code`, like this following:
```nushell
let output = ("yes\nno" | fzf | complete); print $"output: ($output.stdout)"
```

**Comment by amtoine** [comment]
@mengsuenyan 
this does not have to do with `complete` :thinking: 

it used to work and now it does not, e.g. on `0.82.0`
```nushell
let output = ("yes\nno" | fzf); print $"output: ($output)"
```
gives `output: yes` as expected :+1: 

:bulb: to be more precise, adding parentheses around the right-hand-side expression solves the issue in `0.83.1`.
but `let ... = (...)` and `let ... = ...` should be the same :confused:

**Comment by amtoine** [comment]
and we can see this is an issue with external commands only because
```nushell
let output = [yes no] | input list; print $"output: ($output)"
```
works perfectly :ok_hand:

**Comment by fdncred** [comment]
I have no idea why this doesn't work right with external commands. @jntrnr any ideas?

**Comment by amtoine** [comment]
@jntrnr 
just pinging you so that you see this on GitHub :wink:

**Comment by amtoine** [comment]
amazing, works like a charm, thanks a lot @jntrnr :pray:
