### ISSUE TITLE
`into datetime` does not accept tables as input

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#9774]
### Describe the bug

as in the title.

### How to reproduce

1. run `ls | into datetime modified`
2. see the following error
```
Error: nu::parser::input_type_mismatch

  × Command does not support table input.
   ╭─[entry #9:1:1]
 1 │ ls | into datetime modified
   ·      ──────┬──────
   ·            ╰── command doesn't support table input
   ╰────
```

### Expected behavior

i expected `ls | into datetime modified` to basically return the same output as `ls` because `$.modified` is already a `datetime`

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.82.1                                   |
| branch             | main                                     |
| commit_hash        | 656f707a0be48d04c356cc307450213ef1a39619 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)      |
| rust_channel       | 1.69.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)      |
| build_time         | 2023-07-17 19:32:26 +02:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | hist, plot                               |

### original context
this is related to https://github.com/nushell/nu_scripts/issues/559 and my attempt to write a `who` wrapper around the linux `who` command:
```nushell
def who []: nothing -> table {
    ^who --users | str replace ' \s+' ',' --all | str trim | split column "," user tty datetime pid | into datetime datetime
}
```
but this gives me
```
Error: nu::parser::input_type_mismatch

  × Command does not support table input.
   ╭─[entry #11:1:1]
 1 │ def who []: nothing -> table {
 2 │     ^who -u | str replace ' \s+' ',' --all | str trim | split column "," user tty datetime pid | into datetime datetime
   ·                                                                                                  ──────┬──────
   ·                                                                                                        ╰── command doesn't support table input
 3 │ }
   ╰────
```

### attempt to solve this
i tried to patch Nushell with
```diff
diff --git a/crates/nu-command/src/conversions/into/datetime.rs b/crates/nu-command/src/conversions/into/datetime.rs
index 1a524cd81..98a0be5f6 100644
--- a/crates/nu-command/src/conversions/into/datetime.rs
+++ b/crates/nu-command/src/conversions/into/datetime.rs
@@ -68,6 +68,7 @@ impl Command for SubCommand {
             (Type::Int, Type::Date),
             (Type::String, Type::Date),
             (Type::List(Box::new(Type::String)), Type::List(Box::new(Type::Date))),
+            (Type::Table(vec![]), Type::Table(vec![])),
         ])
         .named(
                 "timezone",
```
the `who` command now parses but i get the following error at runtime
```
Error: nu::shell::only_supports_this_input_type

  × Input type not supported.
   ╭─[entry #1:1:1]
 1 │ def who []: nothing -> table {
 2 │     ^who -u | str replace ' \s+' ',' --all | str trim | split column "," user tty datetime pid | into datetime datetime
   ·                                                         ──────┬─────                             ──────┬──────
   ·                                                               │                                        ╰── only string and integer input data is supported
   ·                                                               ╰── input type: record<user: string, tty: string, datetime: string, pid: string>
 3 │ }
   ╰────
```

**Comment by fdncred** [comment]
With your change, this works:
```nushell
❯ who -u | str replace ' \s+' ',' --all | str trim | split column "," user tty datetime pid | into datetime datetime
╭───┬─────────┬─────────┬─────────────┬─────╮
│ # │  user   │   tty   │  datetime   │ pid │
├───┼─────────┼─────────┼─────────────┼─────┤
│ 0 │ fdncred │ console │ 2 weeks ago │ old │
╰───┴─────────┴─────────┴─────────────┴─────╯
```
You have to tell `into datetime` which column to act on.
This also works after your change.
```nushell
❯ ls | to json | from json | into datetime modified
```

**Comment by amtoine** [comment]
> You have to tell `into datetime` which column to act on.
> 
my bad, this was a bad copy-paste, i've updated the PR description and added `datetime` as the column name to `into datetime` :blush: 

> With your change, this works:
> 
> ```nushell
> ❯ who -u | str replace ' \s+' ',' --all | str trim | split column "," user tty datetime pid | into datetime datetime
> ╭───┬─────────┬─────────┬─────────────┬─────╮
> │ # │  user   │   tty   │  datetime   │ pid │
> ├───┼─────────┼─────────┼─────────────┼─────┤
> │ 0 │ fdncred │ console │ 2 weeks ago │ old │
> ╰───┴─────────┴─────────┴─────────────┴─────╯
> ```
> 
ooh you might be right, wait a sec :thinking: 
i'm having inconsistent output from `who -u` so i've tried with the following synthetic data to avoid issues with parsing
```nushell
let data = [
    [name tty datetime pid];

    [amtoine tty1 "2023-07-23 15:18 00:06" 627]
    [fdncred console "2023-07-01 00:00 00:00" old]
]
```

## without the patch
```nushell
> $data | into datetime datetime
Error: nu::parser::input_type_mismatch

  × Command does not support table<name: string, tty: string, datetime: string, pid: any> input.
   ╭─[entry #16:1:1]
 1 │ $data | into datetime datetime
   ·         ──────┬──────
   ·               ╰── command doesn't support table<name: string, tty: string, datetime: string, pid: any> input
   ╰────
```

### with the patch
```nushell
> $data | into datetime datetime
╭───┬─────────┬─────────┬──────────────┬─────╮
│ # │  name   │   tty   │   datetime   │ pid │
├───┼─────────┼─────────┼──────────────┼─────┤
│ 0 │ amtoine │ tty1    │ 15 hours ago │ 627 │
│ 1 │ fdncred │ console │ 3 weeks ago  │ old │
╰───┴─────────┴─────────┴──────────────┴─────╯
```

> This also works after your change.
> ```nushell
> ❯ ls | to json | from json | into datetime modified
> ```
>
it looks like this was working before the patch :yum:
also i'm not sure we should consider this kind of trick something to check when we have a bug, right? :open_mouth: 

## without the patch
```nushell
> ls | into datetime modified
Error: nu::parser::input_type_mismatch

  × Command does not support table input.
   ╭─[entry #20:1:1]
 1 │ ls | into datetime modified
   ·      ──────┬──────
   ·            ╰── command doesn't support table input
   ╰────
```

## with the patch
```nushell
> ls | into datetime modified
Error: nu::shell::only_supports_this_input_type

  × Input type not supported.
   ╭─[entry #4:1:1]
 1 │ ls | into datetime modified
   · ─┬   ──────┬──────
   ·  │         ╰── only string and integer input data is supported
   ·  ╰── input type: date
   ╰────
```

**Comment by fdncred** [comment]
`ls | into datetime modified` isn't supposed to work because you're trying to change a datetime into a datetime. As the error says, it needs a string or int to make a datetime.

**Comment by amtoine** [comment]
> `ls | into datetime modified` isn't supposed to work because you're trying to change a datetime into a datetime. As the error says, it needs a string or int to make a datetime.
>
ooh right, this makes sense :+1: 

then the patch appears to fix this issue :ok_hand: 
i'll go ahead nad open a PR with the fix :relieved:
