### ISSUE TITLE
windows installer: upgrade "ended prematurely because of an error"

### ISSUE THREAD

**Issue by colemickens** [nushell/nushell#9799]
### Describe the bug

I have nushell `0.77.1.0` installed in Windows via MSI.

I am trying to install the latest release `0.82.0`.

The installer runs until the core installation parts, proceeds, then rolls back and emits this *unactionable* error:

![Screenshot (695)](https://github.com/nushell/nushell/assets/327028/c05f2766-ec76-4c1f-8fad-51c9608794a5)

### How to reproduce

(See above)

### Expected behavior

A successful normal upgrade.

### Configuration

n/a

**Comment by fdncred** [comment]
I've ran the 82 win installer a few times without issue. I wonder if it needs admin access? we have a new release today, so you can check that one when it's released.

**Comment by colemickens** [comment]
It prompted for admin access, which I granted, but still resulted in this. I'll check the new release later when I reboot to Windows too.

**Comment by fdncred** [comment]
i wonder if it was wanting the old one to be uninstalled firts? i can't really think of a lot more things that make these msi's puke.

**Comment by nblumhardt** [comment]
Just hit this with nushell 0.83, AMD64/msvc/Windows 10. Tried uninstalling the earlier 0.78 version first but no difference as far as I can tell. Hope this helps - I'll try some older installers now.

**Comment by nblumhardt** [comment]
Odd! I'd accidentally downloaded the ARM installer. Using the correct MSI worked fine.

**Comment by fdncred** [comment]
Thanks for the insight @nblumhardt. @colemickens did you happen to download the wrong windows MSI too?

**Comment by colemickens** [comment]
Yes, I checked last reboot into windows and saw the wrong arch in the filename. My bad. I'm very surprised the installer doesn't internally just know that its the wrong arch until the end "install" process...

Anyway, obvious user error, I'll close this. Sorry for the noise.
