### ISSUE TITLE
Parse boolean values

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#98]
Would be nice to be able to do pass commands like `where yanked != true` though it currently seems that true is being parsed as a string.

**Comment by wycats** [comment]
PowerShell makes this work by reserving `$true` and `$false`. Earlier on, I was thinking `$yes` and `$no`. I'm open to other options.

**Comment by rrichardson** [comment]
are there any characters/symbols already reserved in nushell?  I am disinclined to use `$` because it might be misleading to newcomers from  bash|zsh|csh|etc 
I kind of like `:true` `:false`   but am not set on it

**Comment by COLAMAroro** [comment]
Using `$true` and `$false` doesn't seems that bad, considering the use of `$it` when piping and the inspiration from PowerShell

**Comment by alexxbb** [comment]
What if we distinct a comparison with literals versus logical operation on values? i.e:  
`ls | where type is File`    - _literal_ 
`ls | where size > 10kb`  - _logical_
`read something | where yanked != true ` -  _logical_

**Comment by olamiko** [comment]
I will like to handle this but which mode should I work with? $true or :true?

**Comment by rrichardson** [comment]
@olamiko  - I think this feature was just released.

**Comment by thegedge** [comment]
Yep, @jonathandturner added `$true` and `$false`:

```
❯ ls --full | where readonly
❯ ls --full | where readonly == $false
```

There's currently no shorthand for boolean negation, so this doesn't work:

```
❯ ls --full | where !readonly
```
