### ISSUE TITLE
length command not work with rest parameters with type

### ISSUE THREAD

**Issue by congve1** [nushell/nushell#9803]
### Describe the bug

when I update nushell to 0.83, zoxide init script comile error when startup 
here is the error message screenshot
![image](https://github.com/nushell/nushell/assets/7427587/5b27d69a-4dfc-43ac-90ab-f4b2acd47b24)

### How to reproduce

1. ` def a [...rest: string] {
 echo ($a | length)
}`
compile error
2. `def a [...rest] {
 echo ($a | length)
}` 
works fun

### Expected behavior

length command  should work fine with typed rest paramters

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.83.0                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | macos-x86_64                                                                    |
| build_target       | x86_64-apple-darwin                                                             |
| rust_version       | rustc 1.73.0-nightly (993deaa0b 2023-07-11)                                     |
| rust_channel       | nightly-x86_64-apple-darwin                                                     |
| cargo_version      | cargo 1.73.0-nightly (45782b6b8 2023-07-05)                                     |
| build_time         | 2023-07-26 11:24:42 +08:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | mimalloc                                                                        |
| features           | dataframe, default, extra, sqlite, static-link-openssl, trash, wasi, which, zip |
| installed_plugins  |                                                                                 |

**Comment by fdncred** [comment]
Your option 2 is how I fixed mine too.

**Comment by amtoine** [comment]
the two examples above should use `$rest` rather than `$a`, right? :thinking: 
```nushell
def a [...rest: string] { $rest | length }
```
gives a compile error but
```nushell
def a [...rest] { $rest | length }
```
works fine :yum: 

i don't think this issue should be closed because the second command, without the type annotation, works :confused: 
however, i do think it can be closed in favor of either one of the two following issues that reports the same issue!
- https://github.com/nushell/nushell/issues/9809
- https://github.com/nushell/nushell/issues/9720
