### ISSUE TITLE
`dfr into-nu` stoped working in 0.83.0

### ISSUE THREAD

**Issue by maxim-uvarov** [nushell/nushell#9806]
### Describe the bug

dfr into-nu doesn't work anymore:(

### How to reproduce
```
ls | dfr into-df | dfr into-nu

Error: nu::parser::input_type_mismatch

  × Command does not support dataframe input.
   ╭─[entry #6:1:1]
 1 │ ls | dfr into-df | dfr into-nu
   ·                    ─────┬─────
   ·                         ╰── command doesn't support dataframe input
   ╰────
```
### Expected behavior

I expect it to work

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.83.0                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | macos-aarch64                                        |
| build_target       | aarch64-apple-darwin                                 |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)                  |
| rust_channel       | 1.69.0-aarch64-apple-darwin                          |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)                  |
| build_time         | 2023-07-26 06:55:18 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | standard                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by eggcaker** [comment]
Not sure it's right command to convert df to nu table, but with `dfr col a | dfr into-nu` still working with 0.83.0
