### ISSUE TITLE
`dfr min` stoped working with  `dfr col` in 0.83.0

### ISSUE THREAD

**Issue by maxim-uvarov** [nushell/nushell#9807]
### Describe the bug

subj

### How to reproduce

```
 ls | dfr into-df | dfr agg [(dfr col modified | dfr min | dfr as 'm_min')]
Error: nu::parser::input_type_mismatch

  × Command does not support expression input.
   ╭─[entry #3:1:1]
 1 │ ls | dfr into-df | dfr agg [(dfr col modified | dfr min | dfr as 'm_min')]
   ·                                                 ───┬───
   ·                                                    ╰── command doesn't support expression input
   ╰────
```

### Expected behavior

I expected nu to work

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.83.0                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | macos-aarch64                                        |
| build_target       | aarch64-apple-darwin                                 |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)                  |
| rust_channel       | 1.69.0-aarch64-apple-darwin                          |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)                  |
| build_time         | 2023-07-26 06:55:18 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | standard                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by WindSoilder** [comment]
Adding a note: the example code can't work on 0.82 as well..
```nushell
❯  ls | dfr into-df | dfr agg [(dfr col modified | dfr min | dfr as 'm_min')]
Error: nu::shell::cant_convert

  × Can't convert to lazy groupby.
   ╭─[entry #2:1:1]
 1 │  ls | dfr into-df | dfr agg [(dfr col modified | dfr min | dfr as 'm_min')]
   ·                     ───┬───
   ·                        ╰── can't convert custom value to lazy groupby
   ╰────

```

**Comment by maxim-uvarov** [comment]
Sorry, my bad. It should be 
`ls | dfr into-df | dfr group-by type | dfr agg [(dfr col modified | dfr min | dfr as 'm_min')]`

**Comment by fdncred** [comment]
@maxim-uvarov just FYI -  with this PR https://github.com/nushell/nushell/pull/9860, the command above works again.
```nushell
❯ ls | dfr into-df | dfr group-by type | dfr agg [(dfr col modified | dfr min | dfr as 'm_min')]
╭───┬──────┬──────────────╮
│ # │ type │    m_min     │
├───┼──────┼──────────────┤
│ 0 │ dir  │ 3 months ago │
│ 1 │ file │ 4 months ago │
╰───┴──────┴──────────────╯
```

**Comment by maxim-uvarov** [comment]
@fdncred Thank you for the info! Just merged that pr, builed nu. I tested all my dataframe scripts and they work again! 🕺
