### ISSUE TITLE
`ansi --list | columns` won't work in 0.83.0

### ISSUE THREAD

**Issue by maxim-uvarov** [nushell/nushell#9808]
### Describe the bug

previously it worked

### How to reproduce

```
ansi --list | columns
Error: nu::parser::input_type_mismatch

  × Command does not support string input.
   ╭─[entry #3:1:1]
 1 │ ansi --list | columns
   ·               ───┬───
   ·                  ╰── command doesn't support string input
```

### Expected behavior

to work

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.83.0                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | macos-aarch64                                        |
| build_target       | aarch64-apple-darwin                                 |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)                  |
| rust_channel       | 1.69.0-aarch64-apple-darwin                          |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)                  |
| build_time         | 2023-07-26 06:55:18 +00:00                           |
| build_rust_channel | release                                              |
| allocator          | standard                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by fdncred** [comment]
Submitted a PR to fix this #9817
