### ISSUE TITLE
`...rest: string` triggers type mismatch when piped to `length`

### ISSUE THREAD

**Issue by mksinicus** [nushell/nushell#9809]
### Describe the bug

After upgrading to 0.83, zoxide's init script can't be loaded,

```nushell
Error: nu::parser::input_type_mismatch

  × Command does not support string input.
    ╭─[/home/marco/nu/.zoxide.nu:27:1]
 27 │   let arg0 = ($rest | append '~').0
 28 │   let path = if (($rest | length) <= 1) and ($arg0 == '-' or ($arg0 | path expand | path type) == dir) {
    ·                           ───┬──
    ·                              ╰── command doesn't support string input
 29 │     $arg0
    ╰────
```

Related source:

```nushell
def-env __zoxide_z [...rest:string] {
  let arg0 = ($rest | append '~').0
  let path = if (($rest | length) <= 1) and ($arg0 == '-' or ($arg0 | path expand | path type) == dir) {
    $arg0
  } else {
    (zoxide query --exclude $env.PWD -- $rest | str trim -r -c "\n")
  }
  cd $path
}
```

Removing that `:string` annotation or changing it to `:any` works

### How to reproduce

In REPL,

```nushell
> def foo [...rest: string] { $rest | length }
Error: nu::parser::input_type_mismatch

  × Command does not support string input.
   ╭─[entry #1:1:1]
 1 │ def foo [...rest: string] { $rest | length }
   ·                                     ───┬──
   ·                                        ╰── command doesn't support string input
   ╰────
```

```nushell
> def foo [...rest: string] { $rest | describe }
> foo a b c
list<string>
```

### Expected behavior

Works

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.83.0                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.68.1 (8460ca823 2023-03-20)                                             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                                                 |
| cargo_version      | cargo 1.68.1 (115f34552 2023-02-26)                                             |
| build_time         | 2023-07-26 15:51:56 +08:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | standard                                                                        |
| features           | dataframe, default, extra, sqlite, trash, which, zip                            |
| installed_plugins  | from eml, from ics, from ini, from vcf, query, query json, query web, query xml |

### Additional context

Duplicate of <https://github.com/nushell/nushell/issues/9803>, don't know why its closed

Possibly related to <https://github.com/nushell/nushell/issues/9720>

Strangely, `def foo [...rest: string] { $rest | $in | length }` works

**Comment by maxim-uvarov** [comment]
@mksinicus 

it's a problem of zoxide. 

First: comment line in your `env.nu` or `config.nu`
`zoxide init nushell | save -f ~/.zoxide.nu`

Then: use the version of zoxide.nu that I monkeypatched below. 
`nano ~/.zoxide.nu`:

```
# Code generated by zoxide. DO NOT EDIT.

# =============================================================================
#
# Hook configuration for zoxide.
#

# Initialize hook to add new entries to the database.
if (not ($env | default false __zoxide_hooked | get __zoxide_hooked)) {
  $env.__zoxide_hooked = true
  $env.config = ($env | default {} config).config
  $env.config = ($env.config | default {} hooks)
  $env.config = ($env.config | update hooks ($env.config.hooks | default {} env_change))
  $env.config = ($env.config | update hooks.env_change ($env.config.hooks.env_change | default [] PWD))
  $env.config = ($env.config | update hooks.env_change.PWD ($env.config.hooks.env_change.PWD | append {|_, dir|
    zoxide add -- $dir
  }))
}

# =============================================================================
#
# When using zoxide with --no-cmd, alias these internal functions as desired.
#

# Jump to a directory using only keywords.
def-env __zoxide_z [...rest] {
  let arg0 = ($rest | last)
  let path = if (($rest | length) <= 1) and ($arg0 == '-' or ($arg0 | path expand | path type) == dir) {
    $arg0
  } else {
    (zoxide query --exclude $env.PWD -- $rest | str trim -r -c "\n")
  }
  cd $path
}

# Jump to a directory using interactive search.
def-env __zoxide_zi  [...rest:string] {
  cd $'(zoxide query --interactive -- $rest | str trim -r -c "\n")'
}

# =============================================================================
#
# Commands for zoxide. Disable these using --no-cmd.
#

alias z = __zoxide_z
alias zi = __zoxide_zi

# =============================================================================
#
# Add this to your env file (find it by running `$nu.env-path` in Nushell):
#
#   zoxide init nushell | save -f ~/.zoxide.nu
#
# Now, add this to the end of your config file (find it by running
# `$nu.config-path` in Nushell):
#
#   source ~/.zoxide.nu
#
# Note: zoxide only supports Nushell v0.73.0 and above.
```

**Comment by mksinicus** [comment]
@maxim-uvarov Yeah I did find the quick fix (and others to the late `let-env`), but this is really a bug IMO.

`...rest: string` produces `list<string>` but is recognized by `length` as a string (which spawns a type mismatch error). I think it's due to a misplaced type annotation somewhere.

**Comment by maxim-uvarov** [comment]
@mksinicus now I see, thank you!

**Comment by fdncred** [comment]
One hack for this is to change `...rest: string` to `...rest` and that fixes the problem, but there should be a proper fix for this I think.

**Comment by sholderbach** [comment]
This is the more succinct description of the main problem @amtoine observed in https://github.com/nushell/nushell/issues/9720
