### ISSUE TITLE
`math` commands stopped working with `duration` in 0.83.0

### ISSUE THREAD

**Issue by Veetaha** [nushell/nushell#9813]
### Describe the bug

Earlier it was possible to write this:
```py
[1ms, 2ms] | math min  
```

Now this code doesn't compile:
```
Error: nu::parser::input_type_mismatch

  × Command does not support list<duration> input.
   ╭─[entry #1:1:1]
 1 │ [1ms, 2ms] | math min
   ·              ────┬───
   ·                  ╰── command doesn't support list<duration> input
   ╰────
```

### Use case

Implementing an exponential backoff with max retry duration.

### Expected behavior

`math` commands should be able to accept durations as well.

### Configuration

| key                | value                                                   |
| ------------------ | ------------------------------------------------------- |
| version            | 0.83.0                                                  |
| branch             |                                                         |
| commit_hash        | a33b5fe6ce97b5e9fe8a774c13e783ed65c1b591                |
| build_os           | linux-x86_64                                            |
| build_target       | x86_64-unknown-linux-musl                               |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)                     |
| rust_channel       | 1.69.0-x86_64-unknown-linux-gnu                         |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)                     |
| build_time         | 2023-07-25 19:46:50 +00:00                              |
| build_rust_channel | release                                                 |
| allocator          | standard                                                |
| features           | default, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  | from eml, from ics, from ini, from vcf                  |

**Comment by sholderbach** [comment]
Ah this should be an relatively easy fix. We would need to expand the input/output signature to include duration on top of number/int/float.

**Comment by hexavik** [comment]
Can I take this? I might ask for some information.

**Comment by sholderbach** [comment]
Feel free to look into it. You would need to check the `Signature::input_output_types()` calls of our `math` commands. For tests you can either look into the examples or the general `nu-command` tests

**Comment by hexavik** [comment]
Thanks, I shall start with it in the morning.

**Comment by hexavik** [comment]
Should I change the type mentioned in the above-linked issue for all `math`?
