### ISSUE TITLE
Source broke?

### ISSUE THREAD

**Issue by SUPERCILEX** [nushell/nushell#9818]
### Describe the bug

Had to change `source asaveau.nu` to `source ~/.config/nushell/scripts/asaveau.nu`. Might be intentional.

**Comment by fdncred** [comment]
`source file.nu` should work if it happens after env.nu is loaded and you have file.nu in a folder defined in NU_LIB_DIRS.

**Comment by SUPERCILEX** [comment]
Ah, ok I had it in config.nu. Will check tomorrow to make sure that it works if I move it to env.nu.

**Comment by fdncred** [comment]
the `source file.nu` would need to be in config.nu. The folder containing `file.nu` needs to be in a folder defined in `NU_LIB_DIRS` which should be defined in the env.nu.

**Comment by SUPERCILEX** [comment]
Ohhhh yup that explains why things changed. My env.nu broke so I had nu recreate the file from scratch and I see that `env.NU_LIB_DIRS` is commented it out. Thanks!
