### ISSUE TITLE
Autocomplete of path with spaces is buggy

### ISSUE THREAD

**Issue by Aloso** [nushell/nushell#983]
**Describe the bug:**
When autocompleting a path containing spaces with <kbd>TAB</kbd>, the path is added in quotes, without removing the part before the last space:

```bash
> cd The<|>
> cd "The Flash/"             # works :)

> cd The\ Good<|>
> cd The\ "The Good Place/"   # bug!

> cd "The Good<|>"
> cd "The "The Good Place/""  # bug!
```

(`<|>` is the position of the cursor before pressing <kbd>TAB</kbd>)

**Expected behavior:**
Either spaces are escaped with `\ `, or quotes are inserted at the correct places, if necessary.

**Configuration:**
 - OS: Manjaro (Linux 5.3.11-1), desktop: KDE Plasma
 - Version: 0.5.0
 - all features

**Comment by SafariMonkey** [comment]
I spent some time trying to fix this some months ago. The `nu` tries to use `readline` to do the completion, but the syntax of completion results in `nu` vs `readline` are so different that it was basically impossible to reconcile the two without reverse engineering chunks of `readline`'s approach and inverting them.

My branch [here](https://github.com/nushell/nushell/compare/master...SafariMonkey:fix-completion) improves on it in some aspects but fails in others. I ended up with a significant diff that still didn't catch all the cases, which was accidentally dropped when I moved machine. IIRC it involves the actual escaping in readline [happening differently between Windows and Unix-like](https://github.com/kkawakam/rustyline/blob/master/src/completion.rs#L126-L150), among other things.

My recommendation would be to either talk to the rustyline devs about exposing what you need to make it match your requirements, adopt `readline` escaping semantics, implement completion manually, or try the above approach of manually patching all the different possible ways the two can differ.

Personally, I would have a hard time picking up a shell as a daily driver if completion broke in such simple cases.

**Comment by thegedge** [comment]
We're consolidating the completions effort in #290 for now. After we close off that issue, we can open (or reopen) specific issues related to completions.
