### ISSUE TITLE
Tab completion for external commands not working

### ISSUE THREAD

**Issue by VicMCA** [nushell/nushell#9831]
### Describe the bug

In the current release (0.83.0), trying to auto-complete subcommands for external commands (e.g. git, dnf, apt) doesn't work. Instead of listing subcommands, it only lists the contents of the current directory.

### How to reproduce

1. Type any common application's name, e.g. `git` and a space
2. Press <TAB>
3. Suggestions show files and directories in your current location instead of subcommands

### Expected behavior

Show subcommand options after typing <TAB>

### Screenshots

![completion-bash](https://github.com/nushell/nushell/assets/87677160/15431703-fd4d-45d8-9893-0669185d9e17)  
Above, how bash works  
Below, how nu is working  
![completion-nu](https://github.com/nushell/nushell/assets/87677160/fc68e135-f4a8-4d58-b3a7-6d91d3c52190)

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.83.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31) (built from a source tarball) |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25)                               |
| build_time         | 2023-07-25 19:36:36 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | dataframe, default, sqlite, trash, which, zip                     |
| installed_plugins  |                                                                   |

### Additional context

Aside from using oh-my-posh and having a path added for asdf, I'm using default config.nu and env.nu files.
Nu installed via Homebrew.

**Comment by amtoine** [comment]
@VicMCA 
i think this is normal behaviour :yum: 

as any other shell, Nushell does not know *a priori* what and how external commands work :thinking: 
Bash has a long history and thus a lot of contributions in the field of command completion.
on the other hand, Nushell has a [community-driven set of completion files](https://github.com/nushell/nu_scripts/tree/main/custom-completions) that need to be installed and `use`d when the shell starts!

maybe you had an older version of the config file of Nushell where some completion snippets were there by default?
this has been moved to the link above :relieved:

**Comment by amtoine** [comment]
the [README](https://github.com/nushell/nu_scripts/blob/main/custom-completions/README.md) of the completion files explains how to use them :wink:

**Comment by VicMCA** [comment]
I see, I just found it weird that completion was working before I updated it from 0.79 and thought it to be a regression. Was there some integrated support for external completions that is now deprecated?

Anyway, I'll mark it as "Close as not planned" since as I understood it now, it isn't supposed to belong to nushell's base. Thank you for the information 😃

**Comment by VicMCA** [comment]
I see, I just found it weird that completion was working before I updated it from 0.79 and thought it to be a regression. Was there some integrated support for external completions that is now deprecated?

Anyway, I'll mark it as "Close as not planned" since as I understood it now, it isn't supposed to belong to nushell's base. Thank you for the information 😃

**Comment by amtoine** [comment]
> I see, I just found it weird that completion was working before I updated it from 0.79 and thought it to be a regression. Was there some integrated support for external completions that is now deprecated?
> 
i'm not sure, i do not even see any completion on 0.79 :thinking: 
at some point, there was a bit of Git completion in `default_config.nu` but it's been removed quite some time ago :+1: 

> Anyway, I'll mark it as "Close as not planned" since as I understood it now, it isn't supposed to belong to nushell's base.
>
yup. i mean it *could* be in the source of Nushell but it should be first implemented to work with Nushell in the first place :thinking: 
there are a lot of completion scripts from Bash of course, some scripts to convert them to Fish and Zsh, but for Nushell, for now, it's mostly manual :confused: 
we definitely need to develop that part before 1.0 :+1: 

> Thank you for the information smiley
>
anytime :blush:
