### ISSUE TITLE
nu -c doesn't use env.nu in 0.83.0

### ISSUE THREAD

**Issue by jwillikers** [nushell/nushell#9833]
### Describe the bug

Attempting to use a module in the `scripts` directory, even after updating new default `env.nu` to include the `scripts` directory, results in a `module not found` error.

```sh
nu -c "use module.nu; ..."
```

When running `use module.nu` interactively, there is no error.

### How to reproduce

Edit `env.nu` to incorporate the scripts directory.

```sh
$env.NU_LIB_DIRS = [
    ($nu.default-config-dir | path join 'scripts') # add <nushell-config-dir>/scripts
]
```

Add a module to the scripts directory.

Attempt to import the module when using the `nu -c` command, i.e. `nu -c 'module.nu; ...'`.

### Expected behavior

I expect the `env.nu` file to be loaded when using `nu -c` to run commands, since I use modules with these commands. There is no indication this should not be the case and this is how it worked prior to version 0.83.0.

### Configuration

| key                | value                                                   |
| ------------------ | ------------------------------------------------------- |
| version            | 0.83.0                                                  |
| branch             |                                                         |
| commit_hash        | a33b5fe6ce97b5e9fe8a774c13e783ed65c1b591                |
| build_os           | linux-x86_64                                            |
| build_target       | x86_64-unknown-linux-gnu                                |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)                     |
| rust_channel       | 1.69.0-x86_64-unknown-linux-gnu                         |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)                     |
| build_time         | 2023-07-25 19:48:46 +00:00                              |
| build_rust_channel | release                                                 |
| allocator          | standard                                                |
| features           | default, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  |    

### Additional context

```sh
cat ~/.config/nushell/env.nu 
# Nushell Environment Config File
#
# version = 0.82.1

def create_left_prompt [] {
    mut home = ""
    try {
        if $nu.os-info.name == "windows" {
            $home = $env.USERPROFILE
        } else {
            $home = $env.HOME
        }
    }

    let dir = ([
        ($env.PWD | str substring 0..($home | str length) | str replace --string $home "~"),
        ($env.PWD | str substring ($home | str length)..)
    ] | str join)

    let path_color = (if (is-admin) { ansi red_bold } else { ansi green_bold })
    let separator_color = (if (is-admin) { ansi light_red_bold } else { ansi light_green_bold })
    let path_segment = $"($path_color)($dir)"

    $path_segment | str replace --all --string (char path_sep) $"($separator_color)/($path_color)"
}

def create_right_prompt [] {
    # create a right prompt in magenta with green separators and am/pm underlined
    let time_segment = ([
        (ansi reset)
        (ansi magenta)
        (date now | date format '%Y/%m/%d %r')
    ] | str join | str replace --all "([/:])" $"(ansi green)${1}(ansi magenta)" |
        str replace --all "([AP]M)" $"(ansi magenta_underline)${1}")

    let last_exit_code = if ($env.LAST_EXIT_CODE != 0) {([
        (ansi rb)
        ($env.LAST_EXIT_CODE)
    ] | str join)
    } else { "" }

    ([$last_exit_code, (char space), $time_segment] | str join)
}

# Use nushell functions to define your right and left prompt
$env.PROMPT_COMMAND = {|| create_left_prompt }
# $env.PROMPT_COMMAND_RIGHT = {|| create_right_prompt }

# The prompt indicators are environmental variables that represent
# the state of the prompt
$env.PROMPT_INDICATOR = {|| " > " }
$env.PROMPT_INDICATOR_VI_INSERT = {|| " : " }
$env.PROMPT_INDICATOR_VI_NORMAL = {|| " > " }
$env.PROMPT_MULTILINE_INDICATOR = {|| "::: " }

# Specifies how environment variables are:
# - converted from a string to a value on Nushell startup (from_string)
# - converted from a value back to a string when running external commands (to_string)
# Note: The conversions happen *after* config.nu is loaded
$env.ENV_CONVERSIONS = {
    "PATH": {
        from_string: { |s| $s | split row (char esep) | path expand --no-symlink }
        to_string: { |v| $v | path expand --no-symlink | str join (char esep) }
    }
    "Path": {
        from_string: { |s| $s | split row (char esep) | path expand --no-symlink }
        to_string: { |v| $v | path expand --no-symlink | str join (char esep) }
    }
}

# Directories to search for scripts when calling source or use
$env.NU_LIB_DIRS = [
    ($nu.default-config-dir | path join 'scripts') # add <nushell-config-dir>/scripts
]

# Directories to search for plugin binaries when calling register
$env.NU_PLUGIN_DIRS = [
    # ($nu.default-config-dir | path join 'plugins') # add <nushell-config-dir>/plugins
]

# To add entries to PATH (on Windows you might use Path), you can use the following pattern:
# $env.PATH = ($env.PATH | split row (char esep) | prepend '/some/path')
```

**Comment by amtoine** [comment]
@jwillikers 
can you try the same with the following command instead?
```nushell
nu --config $nu.config-path --env-config $nu.env-path --commands "use module.nu; ..."
```

**Comment by jwillikers** [comment]
> @jwillikers can you try the same with the following command instead?
> 
> ```nushell
> nu --config $nu.config-path --env-config $nu.env-path --commands "use module.nu; ..."
> ```

@amtoine I was able to get this working by adding the `--env-config` option.

**Comment by amtoine** [comment]
> I was able to get this working by adding the `--env-config` option.
>
yeah that's what i thougth :+1: 

`nu` does not load the config and the environment by default when running commands with `--commands` or scripts by filename to save parsing time :yum:

**Comment by jwillikers** [comment]
> > I was able to get this working by adding the `--env-config` option.
> 
> yeah that's what i thougth 👍
> 
> `nu` does not load the config and the environment by default when running commands with `--commands` or scripts by filename to save parsing time yum

That totally makes sense, I just wasn't aware of the change in behavior from previous versions.

**Comment by amtoine** [comment]
> That totally makes sense, I just wasn't aware of the change in behavior from previous versions.
>
what was your previous version? :yum:

**Comment by fdncred** [comment]
I did some testing this morning by adding some log events with the `warn!()` macro to `run.rs`. From what I can tell, it seems like the env.nu file is being loaded. 

Here's a couple results.
```
cargo r -- --log-level warn -c "ls"
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
     Running `target/debug/nu --log-level warn -c ls`
run_commands
2023-07-29 12:03:56.678 PM [WARN ] nu::run: starting run_commands
2023-07-29 12:03:56.679 PM [WARN ] nu::run: parsed_nu_cli_args.no_config_file.is_none() == true
2023-07-29 12:03:56.679 PM [WARN ] nu::run: calling read_plugin_file
2023-07-29 12:03:56.718 PM [WARN ] nu::run: parsed_nu_cli_args.env_file.is_some() == false
2023-07-29 12:03:56.718 PM [WARN ] nu::run: calling read_default_env_file <-- This means it's loading the default_env.nu
2023-07-29 12:03:56.724 PM [WARN ] nu::run: just called set_startup_time
2023-07-29 12:03:56.724 PM [WARN ] nu::run: calling evaluate_commands
╭────┬─────────────────────┬──────┬───────────┬──────────────╮
│  # │        name         │ type │   size    │   modified   │
├────┼─────────────────────┼──────┼───────────┼──────────────┤
│  0 │ CODE_OF_CONDUCT.md  │ file │   3.4 KiB │ 4 months ago │
│  1 │ CONTRIBUTING.md     │ file │  10.4 KiB │ 3 weeks ago  │
│  2 │ Cargo.lock          │ file │ 139.1 KiB │ 2 days ago   │
│  3 │ Cargo.toml          │ file │   5.6 KiB │ 2 days ago   │
│  4 │ Cross.toml          │ file │     363 B │ 4 months ago │
```

Here I am passing the `--config` and `--env-config` parameters, and it seems to load them.
```
cargo r -- --log-level warn -c "ls" --config "/Users/username/Library/Application Support/nushell/config.nu" --env-config "/Users/username/Library/Application Support/nushell/env.nu"
   Compiling nu v0.83.1 (/Users/username/src/nushell)
    Finished dev [unoptimized + debuginfo] target(s) in 1.32s
     Running `target/debug/nu --log-level warn -c ls --config '/Users/username/Library/Application Support/nushell/config.nu' --env-config '/Users/username/Library/Application Support/nushell/env.nu'`
2023-07-29 12:07:03.560 PM [WARN ] nu::run: starting run_commands
2023-07-29 12:07:03.560 PM [WARN ] nu::run: parsed_nu_cli_args.no_config_file.is_none() == true
2023-07-29 12:07:03.560 PM [WARN ] nu::run: calling read_plugin_file
2023-07-29 12:07:03.598 PM [WARN ] nu::run: parsed_nu_cli_args.env_file.is_some() == true
2023-07-29 12:07:03.598 PM [WARN ] nu::run: calling read_config_file with: Some(Spanned { item: "/Users/username/Library/Application Support/nushell/env.nu", span: Span { start: 113, end: 172 } })
2023-07-29 12:07:03.607 PM [WARN ] nu::run: parsed_nu_cli_args.config_file.is_some() == true
2023-07-29 12:07:03.607 PM [WARN ] nu::run: calling read_config_file with: Some(Spanned { item: "/Users/username/Library/Application Support/nushell/config.nu", span: Span { start: 37, end: 99 } })
2023-07-29 12:07:03.934 PM [WARN ] nu::run: just called set_startup_time
2023-07-29 12:07:03.934 PM [WARN ] nu::run: calling evaluate_commands
╭────┬─────────────────────┬──────┬──────────┬──────────────╮
│  # │        name         │ type │   size   │   modified   │
├────┼─────────────────────┼──────┼──────────┼──────────────┤
│  0 │ CODE_OF_CONDUCT.md  │ file │   3.4 KB │ 4 months ago │
│  1 │ CONTRIBUTING.md     │ file │  10.6 KB │ 3 weeks ago  │
│  2 │ Cargo.lock          │ file │ 142.5 KB │ 2 days ago   │
│  3 │ Cargo.toml          │ file │   5.7 KB │ 2 days ago   │
│  4 │ Cross.toml          │ file │    363 B │ 4 months ago │
```

So, the moral of the story is, if you want to load your personal `env.nu` file, I believe you have to list it as a command line parameter with `--env-config`. Otherwise, it will load the `default_env.nu` file.

**Comment by jwillikers** [comment]
> > That totally makes sense, I just wasn't aware of the change in behavior from previous versions.
> 
> what was your previous version? 😋

I've been using this feature since at least 0.79.0 and each new version since as part of our CI process.

**Comment by amtoine** [comment]
@jwillikers 
with what @fdncred shared above, i think Nushell is working as expected too :+1: 

when running a script or commands, not a module, one does not know in advance what the environment of the user will be. thus `nu` does not load the users environment and config by default and you'd have to add `--config ...` and `--env-config ...` to the `nu` call.

i think this has been like this for a few releases so it might not be a bug :relieved:

**Comment by fdncred** [comment]
After reading this issue https://github.com/nushell/nushell/issues/9863 it occurred to me that this probably is a bug because we changed the default_env.nu which previously had a path in it for NU_LIB_DIRS. I think we need to revert the line in the NU_LIB_DIRS so we have something people can count on for a known path for scripts. We may also need to add it to the rust code.

**Comment by tminich** [comment]
To me this sounds like `-c` implicitly includes `-n`. If a separate parameter exists to prevent parsing user config files, this behavior seems very unexpected to me, especially as there is no way to turn it off. Explicitly stating config files adds an (imo) unnecessary level of complexity and potential source of errors if you want to share scripts/recipes...

**Comment by fdncred** [comment]
This is why I said it's a bug and we need to fix it in the rust code.

**Comment by tminich** [comment]
Ah ok, sorry, to me that sounded like a tangential thing and the gist I had gotten from the other comments was that this was intended behavior.

**Comment by fdncred** [comment]
I looked at it yesterday and didn't see an easy way to fix it, other than changing the env.nu file. So, I'm not sure where this will land. I agree that it's a significant regression that shouldn't be allowed to continue.

**Comment by balupton** [comment]
Same also applies to `nu -l {0}` and `nu -l -c {0}` as reported at:
https://discord.com/channels/601130461678272522/1147584426121896067

locally and on ci:

```
bash -i
echo 'print "Config"' > "$(nu -c 'echo $nu.config-path')"
echo 'print "Env"' > "$(nu -c 'echo $nu.env-path')"
echo 'print "Login"' > "$(nu -c 'echo $nu.loginshell-path')"
nu -l <(echo print '"Hello"')
Hello
```

we can see that -e does load the config files:

```
bash -i
echo 'echo "File"' > test.nu
chmod +x ./test.nu
nu -l -e ./test.nu
Env
Config
Login
File
     __  ,
 .--()°'.' Welcome to Nushell,
'|, . ,'   based on the nu language,
 !_-(_\    where all data is structured!

Please join our Discord community at https://discord.gg/NtAbbGn
Our GitHub repository is at https://github.com/nushell/nushell
Our Documentation is located at https://nushell.sh
Tweet us at @nu_shell
Learn how to remove this at: https://nushell.sh/book/configuration.html#remove-welcome-message

It's been this long since Nushell's first commit:
4yrs 3months 24days 1hr 56mins 52secs 736ms 642µs 

Startup Time: 44ms 248µs 750ns
~/Downloads >       
```

**Comment by fdncred** [comment]
I added these debug statements to my config files. Here are my results.
1. Set as my login shell in ubuntu
![image](https://github.com/nushell/nushell/assets/343840/03b3b880-085d-4832-b6ee-73d7cd2988d8)
2. Run `nu -e 'cd /home/fdncred'`
![image](https://github.com/nushell/nushell/assets/343840/cdc5e8bd-a05b-4433-8efd-a4d70af90902)
3. nu -c "print $env.ENV_CONVERSIONS" (this is loaded from the default_env.nu in the binary)
![image](https://github.com/nushell/nushell/assets/343840/c0b350df-b28a-46b5-aa1e-b5012404b1f2)
4. Run `nu -c "let a = 5" --config $nu.config-path --env-config $nu.env-path`
![image](https://github.com/nushell/nushell/assets/343840/68490a29-c3dd-442d-bd9d-236a121b6f54)
5. Run `nu -l`
![image](https://github.com/nushell/nushell/assets/343840/bfb29685-7522-4e03-ba10-0ab6553e2733)


These two things are the only things that I don't see working correctly. This is a known issue that we just haven't fixed yet.
![image](https://github.com/nushell/nushell/assets/343840/fc661f54-90b4-42a2-983b-b177348d2256)
![image](https://github.com/nushell/nushell/assets/343840/d135699c-e868-4592-9010-b62176434d64)

I'm not sure what this should do since `-l` and `-c` have contradictory implementations. It currently appears to be ignoring the `-l` part since no local configs are loaded.
![image](https://github.com/nushell/nushell/assets/343840/9bdf90bc-b387-45cf-b9de-5aebcb8583ce)
