### ISSUE TITLE
`'~' | path type` should return 'dir'

### ISSUE THREAD

**Issue by mengsuenyan** [nushell/nushell#9849]
### Describe the bug

`'~' | path type` or `mkdir ~/test; '~/test' | path type` should return 'dir', but now it's return empty string.

### How to reproduce

1. 
```nu
use std;
std assert (('~' | path type) == dir) $"'~' is the diretory: ('~' | path expand)"
```

2. 
```nu
use std;
mkdir ~/test; std assert (('~/test' | path type) == dir) $"'~' is the diretory: ('~/test' | path expand)"
```

3.
```nu
use std;
std assert (('~' | path type) == ('~' | path expand | path type) ) 
```

4.
```nu
use std;
 mkdir ~/test; std assert (('~/test' | path type) == ('~/test' | path expand | path type) )
```

### Expected behavior

Test examples 1/2/3/4 should be tested successfully;

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.83.1                                   |
| branch             | main                                     |
| commit_hash        | 6ac3351fd13e317aacebaa8203ed01fc94cc4025 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)      |
| rust_channel       | 1.69.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)      |
| build_time         | 2023-07-29 09:40:28 +08:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  |                                          |

**Comment by amtoine** [comment]
this makes sense to me because `'.' | path type` and `'..' | path type` give `dir` :+1:

**Comment by atahabaki** [comment]
```rust
let path = std::path::Path::new("~");
let meta = std::fs::symlink_metadata(path).unwrap();
```

This should panic, 'cause `~` is not a valid path.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:3:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
It needs to be expanded.
