### ISSUE TITLE
How to create an external command function that needs ^ execution

### ISSUE THREAD

**Issue by Silentdoer** [nushell/nushell#9852]
### Related problem

For example, I want to adapt a ^ps command through tasklist in the Windows platform, but it seems that I can't do it at the moment?

### Describe the solution you'd like

none

**Comment by amtoine** [comment]
@Silentdoer 
what do you mean by "*adapt[ing] a `^ps` command through tasklist*"?

you can write something like
```nushell
def ps [] {
    ^ps
}
```
and there is a builtin `ps` command in Nushell as well :yum:

**Comment by Silentdoer** [comment]
> @Silentdoer what do you mean by "_adapt[ing] a `^ps` command through tasklist_"?
> 
> you can write something like
> 
> ```nushell
> def ps [] {
>     ^ps
> }
> ```
> 
> and there is a builtin `ps` command in Nushell as well 😋

No, that's not what I meant, My idea is that executing ps is executing commands inside nushell, But to execute ^ps is to execute the tasklist command

**Comment by WindSoilder** [comment]
I don't think it's possible, you need to create a custom command to run different command based on os version, like:
```nushell
def sys_ps [] {
    # if windows {
        ^tasklist
    } else {
        ^ps
    }
}
```

**Comment by WindSoilder** [comment]
I think it's answered, so I'll close the issue for now

Feel free to re-open it if you still have questions
