### ISSUE TITLE
Conflicting keybinds for Ctrl+r in default sample config, history_menu and search_history

### ISSUE THREAD

**Issue by gondolyr** [nushell/nushell#9867]
### Describe the bug

The sample config in the `nu-utils` crate has a conflicting keybinding with the `Ctrl r` key combination. The two entries that have this are [`history_menu`](https://github.com/nushell/nushell/blob/main/crates/nu-utils/src/sample_config/default_config.nu#L365-L371) and [`search_history`](https://github.com/nushell/nushell/blob/main/crates/nu-utils/src/sample_config/default_config.nu#L433-L439). Because `search_history` appears later in the list, it takes precedence.

### How to reproduce

1. Download the `default_config.nu` file from the `nu-utils` crate: https://github.com/nushell/nushell/blob/main/crates/nu-utils/src/sample_config/default_config.nu
2. Move and rename the file to `~/.config/nushell/config.nu`.

### Expected behavior

I expect the history menu to be used as before when I was using 0.82.0.

### Screenshots

The actual behaviour looks like the following:

![01_conflicting_keybindings_both](https://github.com/nushell/nushell/assets/57526088/c11530cb-ebb4-4c09-a4ca-ef6f48825b00)

The expected result is the following (this is with the `search_history` entry commented-out):

![02_conflicting_keybindings_search_history_removed](https://github.com/nushell/nushell/assets/57526088/5738b4a8-2697-4163-8792-950fd5484b88)

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.83.0                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.71.0 (cfd3bbd8f 2023-06-08) |
| build_time         | 2023-07-29 09:56:13 -04:00          |
| build_rust_channel | release                             |
| allocator          | standard                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  |                                     |

**Comment by fdncred** [comment]
related https://github.com/nushell/nushell/pull/9862

**Comment by amtoine** [comment]
@fdncred 
i'd even say #9862 would close this issue :open_mouth:

**Comment by fdncred** [comment]
> @fdncred i'd even say #9862 would close this issue 😮

Agreed. It would but 9862 needs help right now. We don't just need to change the config file but the rust code too.

**Comment by fdncred** [comment]
good catch. you're right @star-szr. thanks!
