### ISSUE TITLE
Detected：Trojan:Win32/Bearfoos.A!ml

### ISSUE THREAD

**Issue by zonglin-hub** [nushell/nushell#9872]
### Describe the bug

Detected：Trojan:Win32/Bearfoos.A!ml

### How to reproduce

```powershell
PS ~> nu
```

### Expected behavior

Command line execution `nu.exe`

### Screenshots

![image](https://github.com/nushell/nushell/assets/87891147/ee119f41-2fb9-48c5-8322-c52c6033be9c)

![image](https://github.com/nushell/nushell/assets/87891147/b73636e3-c3c8-40fc-8aa1-5cd645a515e5)

### Configuration

win 11 
nushell version：ba0f069c319638f562248476cea51c00cd2c1456

### Additional context

[Trojan:Win32/Bearfoos.A!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FBearfoos.A!ml&threatid=2147731250)

**Comment by fdncred** [comment]
I don't see a release matching that hash. I'm not sure where you get the hash if you can't run nushell though.

**Comment by zonglin-hub** [comment]
The release version is not used. The latest version was manually built, and then re-built according to the official file. This problem has not occurred yet.

**Comment by fdncred** [comment]
If you're not using our built binary, and you're building your own binary, I'm not sure how this is an issue for the nushell repo?

**Comment by LeoniePhiline** [comment]
See also https://answers.microsoft.com/en-us/windows/forum/all/bearfoosaml-false-alarm/37707c6a-8222-44ad-a604-d75918dfb519

**Comment by jntrnr** [comment]
Agreed with @fdncred that if you're building your own binary rather than using our binaries, you should investigate the tools you're using to build the binary.

Going ahead and closing, as this doesn't seem related to Nushell.
