### ISSUE TITLE
Unusual parsing of equal signs followed by a char as part of strings in a dictionary without spaces

### ISSUE THREAD

**Issue by Jan9103** [nushell/nushell#9879]
### Describe the bug

The ast parsing somehow often thinks that a `=` followed by a char in a string of a dictionary, which dosnt contain spaces, makes the entire dictionary a command.

### How to reproduce

These examples produce `Error: nu::parser::unknown_command`:
- `{"":"=a"}`
- `{"=a":""}`
- `{"foo":"=foo"}`
- `{"":"=a","":""}`

These similar examples parse correctly:
- `{"":""}`
- `{"":"="}`
- `{"": "="}`
- `{"foo":"foo"}`
- `{"":" ="}`
- `{"":"=a", "":""}`
- `{"":"=a","": ""}`
- `{"":"=a","":" "}`
- `{"":"foobar="}`

### Expected behavior

all of those should be dictionaries

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.83.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | linux-x86_64                                                      |
| build_target       | x86_64-unknown-linux-gnu                                          |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31) (built from a source tarball) |
| cargo_version      | cargo 1.70.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

(from nupkgs)  
(nu0.82.0 is also affected)

**Comment by jntrnr** [comment]
Updated the description.

**Comment by hugosenari** [comment]
Tested with 0.94.1
Still failing

And `["=a"]` fails but `["= a"]` and `"=a"` don't


Maybe this is a duplacation of #5806 #6401 and related to #4890 #6853
