### ISSUE TITLE
`describe` command still outputs "float" rather than "decimal"

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#9886]
### Describe the bug

`describe` outputs `float` for `decimal` input

### How to reproduce

```
> 1.5 | describe
float
> "1.5" | into decimal | describe
float
```

### Expected behavior

It seems that these were just missed in the renaming several years ago?  I'd expect the output to be `decimal`, right?

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.83.1                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | linux-x86_64                                         |
| build_target       | x86_64-unknown-linux-gnu                             |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12)                  |
| rust_channel       | stable-x86_64-unknown-linux-gnu                      |
| cargo_version      | cargo 1.71.0 (cfd3bbd8f 2023-06-08)                  |
| build_time         | 2023-07-31 18:55:46 -04:00                           |
| build_rust_channel | release                                              |
| allocator          | standard                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

**Comment by fdncred** [comment]
I think that's because we don't have a nushell `Value::Decimal` value, but we do have a `Value::Float` value. Maybe it should be renamed to `into float` since all the paths are returning Value::Float.

https://github.com/nushell/nushell/blob/f6033ac5af75073dddce2400304448dbbadd0318/crates/nu-command/src/conversions/into/decimal.rs#L92-L129

**Comment by sholderbach** [comment]
Yeah I would say `Decimal` is a misnomer as this is typically reserved for true decimal values that are safe for currency operations.

**Comment by KAAtheWiseGit** [comment]
I think this can be closed, since `into decimal` is now `into float`.

**Comment by fdncred** [comment]
yup, thanks for the reminder!
