### ISSUE TITLE
doc tests for command example snippets

### ISSUE THREAD

**Issue by drmason13** [nushell/nushell#989]
I've noticed there are some really good test features that let you describe a nushell "playground" or sandbox to run commands in. It's really nice to use even though I don't fully understand it.

It's also good that we're getting some documentation together of the commands complete with examples of usage and output. Some of these snippets seem to use files and examples taken from the playground used in tests, others don't.

Would it be possible to have these tied together somehow using docs tests.?

We might need to leverage the functionality of mdbook - I think we can write more preparation code (creating the sandbox, describing the files, ...) in the markdown or in nearby files and hide it from the end user.

I'm fairly sure cargo test isn't able to understand \`\`\`shell snippets, so we might have to add \`\`\`rust snippets that are entirely hidden - having these side by side in the doc md files might help keep them in sync.

I'm also unsure there is even a problem to start with, so I guess this is more defense against what will probably happen with more and more commands being added :)

**Comment by jonathandturner** [comment]
This is a wonderful idea. Our plans with the snippets in documentation is also to turn them into templates you can find from inside of Nu's help. It'd be great to know that we're keeping these working as Nu matures.

**Comment by andrasio** [comment]
@drmason13 Yes sir! That's among the goals regarding examples and documentation. Feel free to try out things and report back here or the Discord.

**Comment by thegedge** [comment]
We have examples built into the commands these days. I wonder if we should find a way to integrate these examples into the docs, or just drop examples completely and recommend running `help <command>`?

I think generating documentation from code is the best way to ensure it stays in sync.
