### ISSUE TITLE
Nitpick:  `date format`, but `format duration`?

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#9891]
### Describe the bug

Just noticing that the new `format duration` command has the opposite structure as the existing `date format` command.

### How to reproduce

Honestly, I can't at the moment since I don't have the `date format` command yet.  I'm using a nightly, but since it's in nu-cmd-extra and it doesn't seem like nightlies include that.

But that's beside the point ;-)

### Expected behavior

*Probably* should have consistent naming here?  If `format duration` is the first of the `format` subcommands, then perhaps `date format` should be renamed to `format date`?

Alternatively, `duration format`?

### Configuration

N/A

**Comment by sholderbach** [comment]
Agreed this should be one accessible family of commands. After adding `format duration` we also discussed that the command and its `format filesize` sibling should probably be available in the standard distro of nushell.

**Comment by NotTheDr01ds** [comment]
Ah yes, I missed `format filesize`.

**Comment by fdncred** [comment]
I agree too. Seems like we may need a few `format blah` commands.
