### ISSUE TITLE
Use `register` to add plugin failed with the error `Error getting signatures`

### ISSUE THREAD

**Issue by mengsuenyan** [nushell/nushell#9903]
### Describe the bug

Use `register` to add plugin failed, and report the error as follows:

```
Error:   × Error getting signatures
   ╭─[entry #15:1:1]
 1 │ register ./nu_plugin_example
   · ────┬───
   ·     ╰── Plugin failed to decode: invalid type: boolean `false`, expected a sequence
   ╰────
```

### How to reproduce

```nushell
cd nushell
cargo build --release --features dataframe
cd target/release
```

1. `register ./nu_plugin_example`
```
Error:   × Error getting signatures
   ╭─[entry #15:1:1]
 1 │ register ./nu_plugin_example
   · ────┬───
   ·     ╰── Plugin failed to decode: invalid type: boolean `false`, expected a sequence
   ╰────
```

2. `register ./nu_plugin_custom_values`
```
Error:   × Error getting signatures
   ╭─[entry #16:1:1]
 1 │ register ./nu_plugin_custom_values
   · ────┬───
   ·     ╰── Plugin failed to decode: invalid type: boolean `false`, expected a sequence
   ╰────
```

3. `register ./nu_plugin_formats`
```
Error:   × Error getting signatures
   ╭─[entry #17:1:1]
 1 │ register ./nu_plugin_formats
   · ────┬───
   ·     ╰── Plugin failed to decode: invalid type: boolean `false`, expected a sequence
   ╰────
```

4. `register ./nu_plugin_gstat `
```
Error:   × Error getting signatures
   ╭─[entry #18:1:1]
 1 │ register ./nu_plugin_gstat
   · ────┬───
   ·     ╰── Plugin failed to decode: invalid type: boolean `false`, expected a sequence
   ╰────

```

### Expected behavior

The command `register` can work normal.

### Configuration

| key                | value                                         |
| ------------------ | --------------------------------------------- |
| version            | 0.83.2                                        |
| branch             | main                                          |
| commit_hash        | dd86f14a5a0f9b10918a65f8f18519e6ab7a0c45      |
| build_os           | linux-x86_64                                  |
| build_target       | x86_64-unknown-linux-gnu                      |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)           |
| rust_channel       | 1.69.0-x86_64-unknown-linux-gnu               |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)           |
| build_time         | 2023-08-02 23:33:41 +08:00                    |
| build_rust_channel | release                                       |
| allocator          | standard                                      |
| features           | dataframe, default, sqlite, trash, which, zip |
| installed_plugins  | inc, nu-example-1, nu-example-2, nu-example-3 |

**Comment by fdncred** [comment]
This looks like you have an old version of plugin with a new version of nushell. This usually happens when we change the plugin signature, which we did recently. This is the fix I use.

1. cargo clean
2. remove the plugin file with something like rm $nu.plugin-path
3. rebuild nushell
4. rebuild plugins
5. register plugins
6. restart nushell

I believe this error is because `vectorizes_over_list` was removed from the signature.

**Comment by mengsuenyan** [comment]
> This looks like you have an old version of plugin with a new version of nushell. This usually happens when we change the plugin signature, which we did recently. This is the fix I use.
> 
>     1. cargo clean
> 
>     2. remove the plugin file with something like rm $nu.plugin-path
> 
>     3. rebuild nushell
> 
>     4. rebuild plugins
> 
>     5. register plugins
> 
>     6. restart nushell
> 
> 
> I believe this error is because `vectorizes_over_list` was removed from the signature.

Thanks! Rebuild the nullshell plugin, it's working success.
