### ISSUE TITLE
`parse` can truncate streams

### ISSUE THREAD

**Issue by mdfinvia** [nushell/nushell#9906]
### Describe the bug

When running `parse` on a `stream` input, the output will be truncated after the first non-matching record.
In the demo below I use `--regex`, but the issue can be reproduced without it as well.

### How to reproduce

1. `[a b c] | str join "\n" | save -f demo`
2. `open demo | lines | parse -r '([ac])'`

### Expected behavior

I expected nu to not truncate streams on the first non-match :smiley_cat: 

### Screenshots

![image](https://github.com/nushell/nushell/assets/95413291/74140d8f-2ec3-447f-8fa3-cc773fe4a72b)

### Configuration

| key                | value                                                                           |
| ------------------ | ------------------------------------------------------------------------------- |
| version            | 0.83.1                                                                          |
| branch             |                                                                                 |
| commit_hash        |                                                                                 |
| build_os           | linux-x86_64                                                                    |
| build_target       | x86_64-unknown-linux-gnu                                                        |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12)                                             |
| rust_channel       | stable-x86_64-unknown-linux-gnu                                                 |
| cargo_version      | cargo 1.71.0 (cfd3bbd8f 2023-06-08)                                             |
| build_time         | 2023-08-02 12:40:14 +02:00                                                      |
| build_rust_channel | release                                                                         |
| allocator          | mimalloc                                                                        |
| features           | dataframe, default, extra, sqlite, static-link-openssl, trash, wasi, which, zip |
| installed_plugins  |                                                                                 |

**Comment by fdncred** [comment]
This may be related to https://github.com/nushell/nushell/issues/9795 as well.

**Comment by amtoine** [comment]
i can add that the following does not work either, just as the last example in the issue description
```nushell
> let foo = open /tmp/foo.txt | lines | parse -r '([ac])'; $foo
╭───┬──────────╮
│ # │ capture0 │
├───┼──────────┤
│ 0 │ a        │
╰───┴──────────╯
```

**Comment by panicbit** [comment]
> This may be related to #9795 as well?
> 
> Maybe not since my issue requires > 8192 bytes.

That issue is unrelated. This ticket is about missing entire rows of a ListStream, but #9795 is about missing bytes from an ExternalStream.

**Comment by fdncred** [comment]
Now if we could just get someone to fix it, hint hint @panicbit. 😆
