### ISSUE TITLE
Using nushell consumming commands with snap search breaks the table layout

### ISSUE THREAD

**Issue by mosic** [nushell/nushell#991]
**Describe the bug**
Running `snap search` returns a table-like output, which I thought would be a nice input for the nushell's table functions, but it seems like it's actually worse.

**To Reproduce**

Run: `snap search anki | autoview`

**Expected behavior**
I expected to be able to see the nicely formatted table, and use the table helper functions with it.

**Screenshots**
![Screenshot_20191119_162021](https://user-images.githubusercontent.com/1229422/69165076-e6420c00-0ae8-11ea-88b7-346c8f928df3.png)

**Configuration (please complete the following information):**
 - OS: Ubuntu 19.10
 - Version 0.5.0

**Comment by jonathandturner** [comment]
This should now work with:

```
snap search anki | from-ssv
```
