### ISSUE TITLE
str-expand bug: bracoxide ignores single dots.

### ISSUE THREAD

**Issue by atahabaki** [nushell/nushell#9913]
### Describe the bug
```
╭───┬─────────────────────────────────────────────╮
│ 0 │ ~/Downloads/archlinux-..20230801-x86_64.iso │
│ 1 │ ~/Downloads/Win10_22H2_French_x64v1.iso     │
╰───┴─────────────────────────────────────────────╯
```
### How to reproduce

1. `'~/Downloads/{archlinux-2023.08.01-x86_64,Win10_22H2_French_x64v1}.iso' | str expand`

### Expected behavior

```
╭───┬─────────────────────────────────────────────╮
│ 0 │ ~/Downloads/archlinux-2023.08.01-x86_64.iso │
│ 1 │ ~/Downloads/Win10_22H2_French_x64v1.iso     │
╰───┴─────────────────────────────────────────────╯
```

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.83.0                                                           |
| branch             | makepkg                                                          |
| commit_hash        | a33b5fe6ce97b5e9fe8a774c13e783ed65c1b591                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12) (Arch Linux rust 1:1.71.0-1) |
| cargo_version      | cargo 1.71.0                                                     |
| build_time         | 2023-07-26 01:10:19 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

### Additional context

The problem is pretty basic. Should not take long. I'm working on it now.

**Comment by amtoine** [comment]
i was able to reproduce this behaviour with simpler examples :thumbsup:
```nushell
> '{a-1.2.3,b}' | str expand
╭───┬─────────╮
│ 0 │ a-..123 │
│ 1 │ b       │
╰───┴─────────╯
```
```nushell
> '{a-1.2.3}' | str expand
╭───┬─────────╮
│ 0 │ a-..123 │
╰───┴─────────╯
```
```nushell
> '{a-1.2}' | str expand
╭───┬───────╮
│ 0 │ a-.12 │
╰───┴───────╯
```
```nushell
> '{a-1.}' | str expand
╭───┬──────╮
│ 0 │ a-.1 │
╰───┴──────╯
```

**Comment by amtoine** [comment]
@atahabaki 
i see you've opened an issue on `bracoxide`, if there is nothing to be done in Nushell, we might want to close this very issue in favor of https://github.com/atahabaki/bracoxide/issues/2 :yum:

**Comment by amtoine** [comment]
ok, so it's buggy on latest `main` when running `cargo run` but in the REPL after installing latest `main` :shrug: 
anyways :sweat_smile:
