### ISSUE TITLE
Parsing issue with ! in

### ISSUE THREAD

**Issue by ineu** [nushell/nushell#9915]
### Describe the bug

I have two lists.
```
let first = [1 2 3]
let second = [3 4 5]
```
I want to get values from the first list that are not present in the second. So the result would be
```
[1, 2]
```

### How to reproduce

The most obvious solution is to use `filter`. To check if a value is present in a list, I use `in`. So, if I wanted to get values that ARE present in the second list (i.e. get the intersection), I would use
```
$first | filter { $in in $second }
```
So to get the values that ARE NOT present in the second list, I tried
```
$first | filter { !($in in $second) }
```
But this treats parens as a subshell rather than a group, and tries to call $in as an external command.

Of course, `filter { $in not in $second }` or `filter { $in ! in $second }` also don't work.

### Expected behavior

Ideally it would be great to get Ruby-like operators on lists, but it definitely is a huge feature to implement. So in the scope of the current issue: **There should be some way to express the "not in" semantics**. 

For now I've found two possible workarounds:
```
filter { if $in in $second { false } else { true } }
```
or, as I'm further using the results for a loop:
```
$first | each { 
  if $in in $second { continue }
  ...
}
```

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.83.1                                                           |
| branch             | makepkg                                                          |
| commit_hash        | bf5bd3ff102689a3cae78ea5dfe2e67dfa92f4cd                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12) (Arch Linux rust 1:1.71.0-1) |
| cargo_version      | cargo 1.71.0                                                     |
| build_time         | 2023-07-31 15:45:24 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by amtoine** [comment]
@ineu :wave: :yum: 

i do not think this is a bug, just a parser feature :wink: 

the way to do it right now is the following
```nushell
def "iter intersection" [other: list<any>]: list<any> -> list<any> {
    filter { $in in $other }
}

def "iter difference" [other: list<any>]: list<any> -> list<any> {
    filter { not ($in in $other) }
}
```
```nushell
use std assert

assert equal ([1 2 3] | iter intersection [3 4 5]) [3]
assert equal ([1 2 3] | iter difference [3 4 5]) [1 2]
```
> **Note**
> the use of command definition is just sugar on top, the meat is the use of `not (... in ...)`

**Comment by ineu** [comment]
Thank you! I took a look at the documentation once again, and there is the "not-in" operator for this specific purpose. I don't believe it was there when I started using Nu and read the docs for the first time :)

Could it be possible to make `not-in` a bit more prominent in the docs? It's mentioned in one tiny snippet here, so this time I just missed it: https://www.nushell.sh/book/working_with_lists.html#accessing-the-list

**Comment by amtoine** [comment]
> Thank you! I took a look at the documentation once again, and there is the "not-in" operator for this specific purpose. I don't believe it was there when I started using Nu and read the docs for the first time :)
> 
> Could it be possible to make `not-in` a bit more prominent in the docs? It's mentioned in one tiny snippet here, so this time I just missed it: https://www.nushell.sh/book/working_with_lists.html#accessing-the-list
>
i did even forget about the `not-in` operator :laughing:
