### ISSUE TITLE
Loosen extension requirements for executable-like files

### ISSUE THREAD

**Issue by Voltra** [nushell/nushell#992]
**Is your feature request related to a problem? Please describe.**
Let's say we're on windows, in any terminal we can use `npm` to run it, not `npm.CMD`, just plain `npm`. In NuShell, `which npm` will find the correct file, however running `npm` will result in an error : `file not found. (os error 2)`. Using `npm.cmd` will run the program just fine.

**Describe the solution you'd like**
I'd like to be able to run programs (such as npm) that are available in `PATH` that have fairly executable-like extensions (e.g. `.cmd` on windows).

**Describe alternatives you've considered**
I can't think of any alternative solution.

**Additional context**
This is a problem encountered mostly with installed binaries (or executable scripts) from any package manager.
 Note that on Windows the `PATHEXT` environment variable lists the extensive list of file extensions in search order.

**Comment by steveklabnik** [comment]
Ran into this with Visual Studio: Code today. 👍

**Comment by jonathandturner** [comment]
This should be better now. If you still find cases that don't work with the latest master please re-open
