### ISSUE TITLE
New command "pwd"

### ISSUE THREAD

**Issue by micmine** [nushell/nushell#9921]
### Related problem

On widows, it is not straight forward to get the current directory inside nushell. Or no as easy as on Linux.

### Describe the solution you'd like

Print the full filename of the current working directory.

### Describe alternatives you've considered

Creating an own script that returns me the directory. But since this is not a huge effort. I think it would also bring other users of nushell on Windows.

### Additional context and details

I am interested in implementing this small feature. I have created this issue after reading the CONTRIBUTING.md

**Comment by fdncred** [comment]
we have `pwd` already in our stdlib, so if you have a recent nushell and start it normally, you should be able to use the `pwd` command which is just something like
```nushell
def pwd [] {
  $env.PWD
}
```

**Comment by micmine** [comment]
Oh, my bad, sorry. Thanks for the fast response.
