### ISSUE TITLE
Right-prompt improvements from #9581 and #9585 not taking effect

### ISSUE THREAD

**Issue by NotTheDr01ds** [nushell/nushell#9924]
### Describe the bug

@fdncred added some improvements to the right-prompt formatting in #9581 and #9585, but they are not taking effect for many users since:

* The default `env.nu` has the right-prompt variable creation commented out:

   ```Nushell
   # $env.PROMPT_COMMAND_RIGHT = {|| create_right_prompt }
   ```

* As a result, the hard-coded default from either Nushell or Reedline (I'm not sure which) takes over.  This default is still, apparently, the old, previous version of the right prompt.

Related #9923, where I mention other reasons why hard-coding this doesn't seem like a good idea ;-)

### How to reproduce

1. Back up and Delete `~/.config/nushell/env.nu`
2. Restart Nushell
3. Choose *Yes* when prompted to create default `env.nu`

Result:

Old right-prompt

### Expected behavior

New and improved right prompt!™️

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.83.1                                               |
| branch             |                                                      |
| commit_hash        |                                                      |
| build_os           | linux-x86_64                                         |
| build_target       | x86_64-unknown-linux-gnu                             |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12)                  |
| rust_channel       | stable-x86_64-unknown-linux-gnu                      |
| cargo_version      | cargo 1.71.0 (cfd3bbd8f 2023-06-08)                  |
| build_time         | 2023-07-31 18:55:46 -04:00                           |
| build_rust_channel | release                                              |
| allocator          | standard                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  |                                                      |

### Additional context

As mentioned in #9923, I'm still personally anti-right-prompt as a general rule ;-)

**Comment by fdncred** [comment]
I think the problem was the PR https://github.com/nushell/nushell/pull/9676 that was trying to sync the config.nu to match the rust code. If the prompt is commented out, it reverts to the reedline prompt, iirc. So, we may need a PR to reedline to fix this.

/cc @amtoine

**Comment by NotTheDr01ds** [comment]
@fdncred Ah, that PR definitely makes #9923 "as designed".

I personally think that's the *inverse* of the desired behavior - Most configurations that I can think of ship with *all* default values commented out of (or simply not present in) the "example" config.  You typically uncomment and change a configuration value to *override* the default/hard-coded behavior.

And as per my #9923 comments, I think that only behaviors crucial to smooth operation of the shell should be hard-coded in.  Otherwise it becomes incredibly non-obvious where things are defined in some cases (like the two mentioned there).

**Comment by NotTheDr01ds** [comment]
Ah, looks like what I'm saying is the behavior of #9633 that was specifically superseded by #9676.

**Comment by NotTheDr01ds** [comment]
@fdncred Yeah, I get that, and I agree that *is* normal operation for other shells.  It just means it's always going to be more difficult than it should be for users to override the default right-prompt and multi-line indicator (and other) behavior as described in #9923.

**Comment by NotTheDr01ds** [comment]
And yes, I skimmed around in both the Nu and Reedline source to try to find exactly where the right-prompt was defined, but I couldn't nail it down, so I just went ahead and opened this issue.  I agree that, if the "config matches Rust" behavior is what you want, then *any* change to the configuration (like your right-prompt improvements) is going to need to be implemented twice -- The default config (commented out or not) and hard-coded.

**Comment by fdncred** [comment]
I think this is where the default right prompt is coded in reedline.

https://github.com/nushell/reedline/blob/ed5e48e5374942c5a15ed026bb0ffaf973e47964/src/prompt/default.rs#L58-L61

https://github.com/nushell/reedline/blob/ed5e48e5374942c5a15ed026bb0ffaf973e47964/src/prompt/default.rs#L98-L99

https://github.com/nushell/reedline/blob/ed5e48e5374942c5a15ed026bb0ffaf973e47964/src/prompt/default.rs#L48-L49

**Comment by amtoine** [comment]
yup, it's probably commented out because changes should occur on the Rust side, otherwise the prompt in `nu -n` won't be the same as with the default config :+1:

**Comment by Jiehong** [comment]
I can confirm this is still occurring as of 0.84.0, with a fresh install: right prompt date/time is unexpected (https://github.com/nushell/nushell/pull/9585).

Also, time is not 24h, which is not respectful of the settings on my OS (Mac OS) for my country.

**Comment by fdncred** [comment]
I just updated the right prompt to be enabled again in the default_env.nu. Hopefully this works for everyone.
```nushell
def create_right_prompt [] {
    # create a right prompt in magenta with green separators and am/pm underlined
    let time_segment = ([
        (ansi reset)
        (ansi magenta)
        (date now | format date '%x %X %p') # try to respect user's locale
    ] | str join | str replace --regex --all "([/:])" $"(ansi green)${1}(ansi magenta)" |
        str replace --regex --all "([AP]M)" $"(ansi magenta_underline)${1}")

    let last_exit_code = if ($env.LAST_EXIT_CODE != 0) {([
        (ansi rb)
        ($env.LAST_EXIT_CODE)
    ] | str join)
    } else { "" }

    ([$last_exit_code, (char space), $time_segment] | str join)
}
```
For me, in the US, it looks like this
![image](https://github.com/nushell/nushell/assets/343840/9250c24f-4780-4ca0-b95c-a24850503bbd)
but `%x` is supposed to be `Locale's date representation (e.g., 12/31/99).`
and `%X` is supposed to be `Locale's time representation (e.g., 23:13:48).`
and I left in `%p` for AM/PM so the str replace would work. Not sure if it should stay or go really.

**Comment by Jiehong** [comment]
@fdncred : thank you, I'll give it a try when the next release appears!

For `%p`, it doesn't really make sense in 24h format, since any number greater than 12 is `PM`, by definition, and `AM` otherwise.

**Comment by fdncred** [comment]
> For %p, it doesn't really make sense in 24h format

Ya, I figured people might complain about that. It's hard to please everyone. This is why we give you the ability to change it yourself.

**Comment by Jiehong** [comment]
@fdncred : it's fine this way :)

**Comment by fdncred** [comment]
I wonder if there's a way to know if `%X` is going to be 24hr or 12hr time? If so, we could check for it and add %p only when necessary.

**Comment by Curious-r** [comment]
> ```nushell
> (date now | format date '%x %X %p'
> ```

If `%x` is a 12hr time, `date now | format date '%x %X'` will output a string containing `AM\PM`.
So in my machine, the currently default right prompt looks like:
![image](https://github.com/nushell/nushell/assets/19733878/ba35b7a6-817d-4e6a-9638-be217507c013)

It's kind of weird.

**Comment by Curious-r** [comment]
> I wonder if there's a way to know if `%X` is going to be 24hr or 12hr time? If so, we could check for it and add %p only when necessary.

If %x is a 12hr time, date now | format date '%x %X' will output a string containing AM\PM.
So in my machine, the currently default right prompt looks like:
![image](https://github.com/nushell/nushell/assets/19733878/986e36da-70ca-4252-9418-3f689afa1288)

It's kind of weird.

**Comment by fdncred** [comment]
I don't have any issues with the default prompt in the latest main. It looks fine on my mac.
![image](https://github.com/nushell/nushell/assets/343840/fbd23885-422a-4e9b-95d0-550010f1544d)

**Comment by Curious-r** [comment]
@fdncred Does your locale using 12hr time？

**Comment by fdncred** [comment]
yes, i'm in the US

**Comment by Curious-r** [comment]
Intresting..
I am in China. It seems that `%X` have complex behavior related to location. 
Do you think this need to be fixed?

**Comment by fdncred** [comment]
> Do you think this need to be fixed?

It would be nice if it "just worked" for everyone.

**Comment by Curious-r** [comment]
> It would be nice if it "just worked" for everyone.

Unfortunately, it doesn't seem to work for everyone. I just found that some other locale (not in English), `%x %X %p` will use their own language to show the date, they don't have `AM\PM` and `\:`. For example, `2024年6月25日 13时47分10秒 下午`.
So, "try to respect user's locale" and coloring specific symbols will not take effect at the same time. 
Based on the principle that the default settings should work for everyone, we should try to provide a single coloring as concisely as possible, and more complex rules should be added by the user according to their own locale. Or we can continue with the current coloring scheme, but the date format should be written in a fixed form, like `%m/%d/%Y %l:%M:%S %p`. In addition %p cannot be fixed to `AM\PM`, in Chinese, it will be "上午\下午".

**Comment by fdncred** [comment]
`%x %X` should work in any locale, right? It's just the replace of AMPM that messes things up. We could just remove that part.

**Comment by Curious-r** [comment]
Yes, `%X %X` work in all locale, but the replace of `AMPM` `\:` assumes something that doesn't necessarily exist.

**Comment by fdncred** [comment]
Right, maybe we should remove that part that replaces AMPM and :? Or maybe just make it locale specific. I hate to change everything just so it works in one locale.

**Comment by Curious-r** [comment]
My sentiments align with yours, maybe a region-agnostic "nushell format" would be more appropriate as the default.
