### ISSUE TITLE
`nothing` is incorrectly shown as "any" in custom command help

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#9928]
### Describe the bug

as in the title

### How to reproduce

1. define
```nushell
def foo []: [nothing -> nothing, int -> nothing, nothing -> int] { 123 }
```
2. run `help foo`
3. see
```
Usage:
  > foo

Flags:
  -h, --help - Display the help message for this command

Input/output types:
  ╭───┬───────┬────────╮
  │ # │ input │ output │
  ├───┼───────┼────────┤
  │ 0 │ any   │ any    │
  │ 1 │ int   │ any    │
  │ 2 │ any   │ int    │
  ╰───┴───────┴────────╯
```

### Expected behavior

i expected to see `nothing` instead of `any`
```
Usage:
  > foo

Flags:
  -h, --help - Display the help message for this command

Input/output types:
  ╭───┬─────────┬─────────╮
  │ # │ input   │ output  │
  ├───┼─────────┼─────────┤
  │ 0 │ nothing │ nothing │
  │ 1 │ int     │ nothing │
  │ 2 │ nothing │ int     │
  ╰───┴─────────┴─────────╯
```

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.83.2                                   |
| branch             | main                                     |
| commit_hash        | f61503893835f777c1ade71ec76a6b07fcf818f2 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)      |
| rust_channel       | 1.69.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)      |
| build_time         | 2023-08-05 10:06:24 +02:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | hist                                     |

**Comment by NotLebedev** [comment]
Did some digging around. This seems to have some meaning behind it. More specific in [parse_input_output_types](https://github.com/nushell/nushell/blob/f6033ac5af75073dddce2400304448dbbadd0318/crates/nu-parser/src/parser.rs#L3211) type is acquired via [parse_type](https://github.com/nushell/nushell/blob/f6033ac5af75073dddce2400304448dbbadd0318/crates/nu-parser/src/parser.rs#L2943C19-L2943C19) which performs a `to_type` conversion after `parse_shape_name`. This conversion does indeed change `nothing` to `any` [here](https://github.com/nushell/nushell/blob/6b4d06d8a7ab02501433acfa21cc10a58177607c/crates/nu-protocol/src/syntax_shape.rs#L155C29-L155C29)

Considering that `to_type` method has 18 usages this might or might not be a problem in other usecases
