### ISSUE TITLE
Sink plugin's stdout is not outputted to shell

### ISSUE THREAD

**Issue by oigi333** [nushell/nushell#993]
**Describe the bug**
Sink plugin's stdout is not outputed to shell.

**To Reproduce**
1.  Try using any sink plugin (eg. binaryview) on windows

**Expected behavior**
Sink plugins should be able to write directly to stdout

**Configuration:**
 - OS: Windows
 - Version 0.5.0
 - Optional features (if any)
binaryview

**Comment by thegedge** [comment]
I think this may be specific to `binaryview`:

```
nushell on  HEAD (f43ed23) is  v0.14.1 via  v1.43.0
❯ echo "t" | binaryview
```
