### ISSUE TITLE
bracketed paste partially broken

### ISSUE THREAD

**Issue by amtoine** [nushell/nushell#9944]
cc/ @WindSoilder 

### Describe the bug

lately, the "*bracketed paste*" feature of Nushell has been partially broken :cry: 

### How to reproduce

1. copy the command below
```nushell
ls
| get name
```
2. open Nushell
3. paste the two-line command and press enter => :heavy_check_mark: it works fine and gives a list of filenames
4. repeat step 3. as many times as you want and it will work just as fine each time
5. press `ctrl+c` => a new prompt will appear
6. press enter to print new prompts as many times as you want, including 0 times
7. try step 3. again => :x: the command break in halp and gives the following output (the actual `ls` table have been replaced with `...` for brevity)
```nushell
> ls
╭───┬──────────┬──────┬──────────┬───────────╮
│ # │   name   │ type │   size   │ modified  │
├───┼──────────┼──────┼──────────┼───────────┤
│ 0 │ ...      │ ...  │ ...      │ ...       │
╰───┴──────────┴──────┴──────────┴───────────╯
> | get name
Error: nu::shell::io_error

  × I/O error
  help: can't follow stream paths
```
> **Note**
> depending on whether or not your clipboard has a newline just after the command from step 1., you might or might not see the error => `| get name` might be pasted to your prompt, waiting for you to press enter just after the `ls` output
8. try step 3. or 4. again and it will work... until the next `ctrl+c`

### Expected behavior

i expected the command to be pasted without breaking in half every time.

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.83.2                                   |
| branch             | main                                     |
| commit_hash        | f61503893835f777c1ade71ec76a6b07fcf818f2 |
| build_os           | linux-x86_64                             |
| build_target       | x86_64-unknown-linux-gnu                 |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)      |
| rust_channel       | 1.69.0-x86_64-unknown-linux-gnu          |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)      |
| build_time         | 2023-08-05 10:06:24 +02:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | gstat, hist                              |

### Additional context

can reproduce both in `alacritty` and `rio`

**Comment by LevitatingBusinessMan** [comment]
Fixed in https://github.com/nushell/reedline/pull/657

**Comment by amtoine** [comment]
i'll close this PR then, we can reopen in the future if need be :relieved:
