### ISSUE TITLE
Starting ZSH inside Nu and exiting breaks

### ISSUE THREAD

**Issue by phdcybersec** [nushell/nushell#9954]
### Describe the bug

I ran into an issue trying to set up a "backup" shell for when Nu would not for me in some way, as I aim to use Nu as my main shell for the foreseeable future. 

However, if I start `zsh` from inside a Nu session, I cannot go back to Nu after exiting. I tried with `bash`, and it does not seem to have the same issue.

### How to reproduce

On MacOS:
1. Open a Terminal configured to run Nu at startup
2. Run `zsh`
3. Do stuff
4. Exit ZSH

### Expected behavior

I expected the Nu prompt to reappear. I'm currently unsure if the Nu process hangs and the prompt just does not appear, or if it dies somehow.

### Screenshots

![nu_zsh_no_exit](https://github.com/nushell/nushell/assets/82591009/b035d91e-0e87-4d90-954d-d3a6d7b60451)

### Configuration

| key                | value                                                             |
| ------------------ | ----------------------------------------------------------------- |
| version            | 0.82.0                                                            |
| branch             |                                                                   |
| commit_hash        |                                                                   |
| build_os           | macos-aarch64                                                     |
| build_target       | aarch64-apple-darwin                                              |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31) (built from a source tarball) |
| cargo_version      | cargo 1.70.0                                                      |
| build_time         | 1980-01-01 00:00:00 +00:00                                        |
| build_rust_channel | release                                                           |
| allocator          | standard                                                          |
| features           | default, sqlite, trash, which, zip                                |
| installed_plugins  |                                                                   |

**Comment by jntrnr** [comment]
I can't repro this with 0.83.2

Can you try with a more recent version?

**Comment by phdcybersec** [comment]
Thank you for responding this quick!
I've upgraded to 0.83.1 (the last version available on nixpkgs apparently) and the issue remains. I originally stayed behind due to some issues with the `let-env` to `$env` transition.

**Comment by amtoine** [comment]
i cannot repro with `0.83.2` either :+1:

**Comment by amtoine** [comment]
> I've upgraded to 0.83.1 (the last version available on nixpkgs apparently) and the issue remains
>
do you have the possibility to build Nushell from the latest `main` revision and see if the issue persists there? :yum:

**Comment by phdcybersec** [comment]
I'll try to build it as soon as I get back. 

In the meantime, I've tried to remove my `.zshrc`, and it has solved the issue. I don't see any configuration that would cause such issues. Furthermore, other shells do not seem to cause the same behavior and work as expected:
* `bash -> zsh -> exit -> bash`
* `zsh -> zsh -> exit -> zsh`
* `nu -> zsh -> exit -> nothing `

**Comment by phdcybersec** [comment]
I cloned the repository, built the binary, and it works, to my surprise. Is there any significant change in the way `nu` start processes that changed between 0.83.1 and 0.83.2?

Moreover, while `bash` does not seem to be impacted by this problem, I have the same issue when staring `nu` in `nu`:
* `nu (83.1) -> nu (83.1) -> exit -> nothing`
* whereas `nu (83.1) -> bash -> exit -> nu`

**Comment by amtoine** [comment]
the only thing i can think of is https://github.com/nushell/nushell/pull/9893 which reverts https://github.com/nushell/nushell/pull/9693 which apparently introduced CPU hangs :open_mouth: 

and guess what, 0.83.1 has been released just between the two :smirk: 
that might explain why it works in 0.83.2 :yum:

**Comment by IanManske** [comment]
This one was my bad! #9909 fixes this, but it was caught/merged after the 0.83.1 release.

**Comment by amtoine** [comment]
> When can I expect 0.83.2 to be released in this case?
>
the 0.83.2 version is the development version of Nushell, i.e. it just means you build the code from source, i.e. it's always released :wink: 

however, the next *true* version will be released on 22nd August, in 2 weeks :yum:
