### ISSUE TITLE
Compilation from source broken in nu-utils

### ISSUE THREAD

**Issue by cgranade** [nushell/nushell#9957]
### Describe the bug

When compiling `nu` from source with `cargo install nu --features dataframe`, a type error is returned as shown in snippet below.

### How to reproduce

1. Run `cargo install nu --features dataframe`.

### Expected behavior

Successful compilation of `nu.exe`.

### Screenshots

```
error[E0308]: mismatched types
  --> ...\.cargo\registry\src\github.com-1ecc6299db9ec823\nu-utils-0.83.1\src\deansi.rs:16:16
   |
16 |         if let Ok(stripped) = strip_ansi_escapes::strip(string) {
   |                ^^^^^^^^^^^^   --------------------------------- this expression has type `Vec<u8>`
   |                |
   |                expected `Vec<u8>`, found `Result<_, _>`
   |
   = note: expected struct `Vec<u8>`
                found enum `Result<_, _>`

error[E0308]: mismatched types
  --> ...\.cargo\registry\src\github.com-1ecc6299db9ec823\nu-utils-0.83.1\src\deansi.rs:37:12
   |
37 |     if let Ok(stripped) = strip_ansi_escapes::strip(string) {
   |            ^^^^^^^^^^^^   --------------------------------- this expression has type `Vec<u8>`
   |            |
   |            expected `Vec<u8>`, found `Result<_, _>`
   |
   = note: expected struct `Vec<u8>`
                found enum `Result<_, _>`

error[E0308]: mismatched types
  --> ...\.cargo\registry\src\github.com-1ecc6299db9ec823\nu-utils-0.83.1\src\deansi.rs:63:16
   |
63 |         if let Ok(stripped) = strip_ansi_escapes::strip(&string) {
   |                ^^^^^^^^^^^^   ---------------------------------- this expression has type `Vec<u8>`
   |                |
   |                expected `Vec<u8>`, found `Result<_, _>`
   |
   = note: expected struct `Vec<u8>`
                found enum `Result<_, _>`

error[E0308]: mismatched types
  --> ...\.cargo\registry\src\github.com-1ecc6299db9ec823\nu-utils-0.83.1\src\deansi.rs:84:12
   |
84 |     if let Ok(stripped) = strip_ansi_escapes::strip(&string) {
   |            ^^^^^^^^^^^^   ---------------------------------- this expression has type `Vec<u8>`
   |            |
   |            expected `Vec<u8>`, found `Result<_, _>`
   |
   = note: expected struct `Vec<u8>`
                found enum `Result<_, _>`
```

### Configuration

| key                | value                                                                                                                                                           |
| ------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| version            | 0.81.0                                                                                                                                                          |
| branch             |                                                                                                                                                                 |
| commit_hash        |                                                                                                                                                                 |
| build_os           | windows-x86_64                                                                                                                                                  |
| build_target       | x86_64-pc-windows-msvc                                                                                                                                          |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)                                                                                                                             |
| rust_channel       | stable-x86_64-pc-windows-msvc                                                                                                                                   |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)                                                                                                                             |
| build_time         | 2023-06-18 10:34:38 -07:00                                                                                                                                      |
| build_rust_channel | release                                                                                                                                                         |
| features           | dataframe, default, sqlite, trash, which, zip                                                                                                                   |
| installed_plugins  | [[redacted]] |

### Additional context

Root cause appears to be https://github.com/luser/strip-ansi-escapes/issues/17.

**Comment by cgranade** [comment]
I recognize this is an upstream bug, but wanted to report here as it affects nushell, and to provide context in the upstream bug as to what other crates were broken by this change. Apologies for the additional triage load as a result.

**Comment by sholderbach** [comment]
Thanks for referencing the issue! We hope there is a resolution soon. With https://github.com/nushell/reedline/pull/617 we patched it for reedline, we could do the same for nushell if this takes a bit longer.

You can run with `--locked` for now.

**Comment by fdncred** [comment]
Hopefully #9958 fixes this problem here too.
