### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by jonathandturner** [nushell/nushell#996]
**Describe the bug**
We need an easy guide for contribute on the main repo

**To Reproduce**
1. Notice it's not there
2. Get sad
3. Want more

**Expected behavior**
Contributors have an easy way to find out what is available

**Comment by JesterOrNot** [comment]
Created template PR to get things started!
#998

**Comment by jonathandturner** [comment]
We have an initial CONTRIBUTING.md now we can extend
