### ISSUE TITLE
`open` with a directory followed by `lines` panics

### ISSUE THREAD

**Issue by EmilySeville7cfg** [nushell/nushell#9965]
### Describe the bug

`open` with a directory followed by `lines` panics:

```
thread 'main' panicked at 'not yet implemented', /home/emilyseville7cfg/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nu-command-0.83.1/src/filters/lines.rs:248:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### How to reproduce

1. Create directory `test`
2. Run `open test/ | lines`
3. Get panic

### Expected behavior

No crash, just normal error that this type of input is not accepted.

### Configuration

| key                | value                               |
| ------------------ | ----------------------------------- |
| version            | 0.83.1                              |
| branch             |                                     |
| commit_hash        |                                     |
| build_os           | linux-x86_64                        |
| build_target       | x86_64-unknown-linux-gnu            |
| rust_version       | rustc 1.70.0 (90c541806 2023-05-31) |
| rust_channel       | stable-x86_64-unknown-linux-gnu     |
| cargo_version      | cargo 1.70.0 (ec8a8a0ca 2023-04-25) |
| build_time         | 2023-08-03 22:34:34 +10:00          |
| build_rust_channel | release                             |
| allocator          | standard                            |
| features           | default, sqlite, trash, which, zip  |
| installed_plugins  |                                     |

**Comment by amtoine** [comment]
if the CI passes with the new test, should be good to go in https://github.com/nushell/nushell/pull/9967 :yum:
