### ISSUE TITLE
`overlay use` when trying to use overlay in another directory

### ISSUE THREAD

**Issue by WindSoilder** [nushell/nushell#9980]
### Describe the bug

It's a little hard to express, please see reproduce steps

### How to reproduce

1. create a `test.nu` module with the following content: `export def foo [] { "bar" }`
2. create a directory `tmp`, and create a file inside `tmp`, let's call `test2.nu`, with the following content:
```nushell
cd ..
source test.nu
```
3. run `source test2.nu`, and it returns the following error:
```nushell
  × Module not found.
 2 │ overlay use test.nu
   ·             ───┬───
   ·                ╰── module not found
   ╰────
  help: module files and their paths must be available before your script is run as parsing occurs before anything is evaluated
```

### Expected behavior

I expected nu to run success, or there is a way to do this

### Configuration

| key                | value                                                   |
| ------------------ | ------------------------------------------------------- |
| version            | 0.82.1                                                  |
| branch             | nightly                                                 |
| commit_hash        | bd0032898fe4697f8f1f9e48b3bb904f87608fcb                |
| build_os           | linux-x86_64                                            |
| build_target       | x86_64-unknown-linux-gnu                                |
| rust_version       | rustc 1.68.2 (9eb3afe9e 2023-03-27)                     |
| rust_channel       | 1.68.2-x86_64-unknown-linux-gnu                         |
| cargo_version      | cargo 1.68.2 (6feb7c9cf 2023-03-26)                     |
| build_time         | 2023-07-12 02:15:14 +00:00                              |
| build_rust_channel | release                                                 |
| allocator          | mimalloc                                                |
| features           | default, sqlite, static-link-openssl, trash, which, zip |
| installed_plugins  |                                                         |

### Additional context

I think it's because `overlay use` is a parser keyword, so it runs into failed because `test.nu` doesn't exist, but I still expect we can have a way to do this.

It's relative to python auto-venv script: https://github.com/nushell/nu_scripts/blob/main/modules/virtual_environments/auto-venv/auto-venv.nu#L41
When I setup a auto-venv.nu, and go to a folder inside that project, it raises an error like the this, and I think this issue contains minimum reproduce steps.

**Comment by amtoine** [comment]
i think doing
```nushell
cd ..
source test.nu
```
would work because
- `cd ..` will bring you in the directory with `test.nu`
- `source test.nu` will work fine

however, in a script containing
```nushell
cd ..
source test.nu
```
at parse time, `test.nu` is not available and thus you get an error :open_mouth: 

this looks expected to me, right?

**Comment by WindSoilder** [comment]
Yeah, it works as expected, I've found out a way to solve venv issue
