### ISSUE TITLE
Missing math commands

### ISSUE THREAD

**Issue by janek515** [nushell/nushell#9981]
### Describe the bug

I seem to be missing some math commands in nushell. Just installed it yesterday and I have no idea what's going on,

### How to reproduce

1. open nu shell
2. run math 

### Expected behavior

all math commands are listed

### Screenshots

![image](https://github.com/nushell/nushell/assets/37900649/e02ce4de-f801-4d63-a2cb-f41c1fd0e2ba)

### Configuration

| key                | value                                    |
| ------------------ | ---------------------------------------- |
| version            | 0.83.1                                   |
| branch             |                                          |
| commit_hash        | bf5bd3ff102689a3cae78ea5dfe2e67dfa92f4cd |
| build_os           | windows-x86_64                           |
| build_target       | x86_64-pc-windows-msvc                   |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)      |
| rust_channel       | 1.69.0-x86_64-pc-windows-msvc            |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)      |
| build_time         | 2023-07-30 18:18:41 +00:00               |
| build_rust_channel | release                                  |
| allocator          | standard                                 |
| features           | default, sqlite, trash, which, zip       |
| installed_plugins  | gstat, hist, plot, xyplot                |

**Comment by fdncred** [comment]
I believe a bunch of `math` commands were moved to the `extra` feature. In order to use all of them, you'll have to install with `--features=extra`.

**Comment by janek515** [comment]
Would there be a way to do that while installing from winget?

**Comment by fdncred** [comment]
I don't think so. Winget just pulls our msi that was created during the release.

**Comment by janek515** [comment]
Ok, so the only thing that's wrong is that there's no indication in the docs about these not being in the default release

**Comment by fdncred** [comment]
It's a recent change but I have no doubt that the docs aren't updated.

**Comment by chtenb** [comment]
Some of my commands broke due to missing math commands, and I'm using the windows msi installer. Does the above mean that the only way to install nu fully is using cargo? Seem like it

**Comment by fdncred** [comment]
> Does the above mean that the only way to install nu fully is using cargo? 

I think these are the two options right now
1. `cargo install nu --features=extra,dataframe,mimalloc`
2. clone the repo and do `cargo install --path . --features=extra,dataframe,mimalloc`
