### ISSUE TITLE
How to take input from fzf to open files in their default applications ?

### ISSUE THREAD

**Issue by debajyoti1990** [nushell/nushell#9982]
### Question

Currently I have written a function in config.nu file like

```
def fo [ ] {

fzf --height 60% --layout reverse --border | explorer $in

}
```

The problem with this is if I don't select any file then explorer opens my pc showing the hard drives. Is there any better way to do this, possibly like invoke-item in powershell ?

### Additional context and details

OS: Windows 10.
Terminal: Windows Terminal.

**Comment by fdncred** [comment]
You could try something like this
```nushell
❯ def fo [] {
  let fzfoutput = fzf --height 60% --layout reverse --border | str trim
  if (not ($fzfoutput | is-empty)) {
    ^explorer $fzfoutput
  }
}
```

**Comment by debajyoti1990** [comment]
Thanks, this helped.

**Comment by amtoine** [comment]
yeah i think the thing here is to either
- wrap `fzf` in parentheses
- pipe the output of `fzf` to something like `str trim`

without one or the other, i've seen the output of `fzf` not being captured :thinking: 

isn't this still a nasty bug @fdncred? :confused:

**Comment by fdncred** [comment]
> isn't this still a nasty bug @fdncred? 😕

i'm not sure. i didn't have problem with that one when i wrote it and the other fzf things i have seem to work. i guess i may have forgotten about this bug you mention.

**Comment by amtoine** [comment]
> i'm not sure. i didn't have problem with that one when i wrote it and the other fzf things i have seem to work. i guess i may have forgotten about this bug you mention.
>
that issue: https://github.com/nushell/nushell/issues/9767 :wink:
