### ISSUE TITLE
Paging/scrolling lists and tables

### ISSUE THREAD

**Issue by jzaefferer** [nushell/nushell#999]
**Is your feature request related to a problem? Please describe.**
Currently `open` supports scrolling large-enough files, similar to `less`, yet any output as tables will be printed in full. There's [table filters](https://github.com/nushell/nushell#filters-on-tables-structured-data) like `first`, `last` and `skip` to deal with that (is `skip-while` an inverted `where`?), but for exploration of larger number of rows its rather clunky.

**Describe the solution you'd like**
I think whatever `open` uses to scroll through larger files would be handy to have in `table` or `autoview`. Maybe automatically, maybe opt-in with a flag.

**Describe alternatives you've considered**
I tried piping to native commands like less (and head/tail, before I found first/last), but that didn't work:
```
ps | less $it
error: External $it needs string data
- shell:1:10
1 | ps | less $it
  |           ^^^ given row instead of string data
```
I couldn't find any other way for passing the output of `ps` to a native (on OSX) `less`.

**Additional context**
Not context, but praise: I really really like how all these basic commands like ps, ls have no options, and yet I can already do lots of things with them. Sooo much better than bash with POSIX commands. You should advertise that more!

PS: Aw, almost #1000 😄

**Comment by coolshaurya** [comment]
I think it'd be nice to have _horizontal_ as well as vertical paging for stuff that has a lot of columns like `ls -l` or `echo $nu.env` without autopivot

**Comment by pwnorbitals** [comment]
Would be awesome !

**Comment by mrshu** [comment]
Any chance this might get revisited at some point? I found this issue while trying to figure out how to pass a table into something like `less` in Bash. Would be indeed quite a cool addition!

**Comment by jntrnr** [comment]
@mrshu - we're working on a new engine for Nushell (nicknamed engine-q). In it, tables are output as strings which should make it easier to use things like `less` to page through them.

**Comment by mrshu** [comment]
That's very cool to hear @jntrnr, thank you for letting me know!

What would you say is the best way to keep updated on the effort, or better yet, to perhaps help out with it a bit?

**Comment by Mart-Bogdan** [comment]
In case anybody find this issue from google, like I did. `|table | less` do the job:

```nu
$demo.Units | table --expand | less
```
