### ISSUE TITLE
Aliases do not work if placed inside if statements

### ISSUE THREAD

**Issue by mfdorst** [nushell/nushell#9991]
### Describe the bug

In the following code, none of the aliases work.
```nushell
if (which exa | length) > 0 {
    alias l = exa --git -l
    alias la = exa --git -la
    alias lst = exa --git -lTL2
    alias lsta = exa --git -laTL2
} else {
    alias l = ls
    alias la = ls -a
}
```

### How to reproduce

1. In your config file, add an if statement.
2. Put an alias in that if statement.
3. Reload your config and then try to use that alias.

### Expected behavior

I expect the alias to work.

### Screenshots

![nushell-broken-alias](https://github.com/nushell/nushell/assets/2002883/4b99f90c-3f27-425f-8731-915e8afbef09)

### Configuration

| key                | value                                                            |
| ------------------ | ---------------------------------------------------------------- |
| version            | 0.83.1                                                           |
| branch             | makepkg                                                          |
| commit_hash        | bf5bd3ff102689a3cae78ea5dfe2e67dfa92f4cd                         |
| build_os           | linux-x86_64                                                     |
| build_target       | x86_64-unknown-linux-gnu                                         |
| rust_version       | rustc 1.71.0 (8ede3aae2 2023-07-12) (Arch Linux rust 1:1.71.0-1) |
| cargo_version      | cargo 1.71.0                                                     |
| build_time         | 2023-07-31 15:45:24 +00:00                                       |
| build_rust_channel | release                                                          |
| allocator          | standard                                                         |
| features           | dataframe, default, extra, sqlite, trash, which, zip             |
| installed_plugins  |                                                                  |

**Comment by fdncred** [comment]
I think we have to do it like this right now
```nushell
alias l = if (which exa | length) > 0 { exa --git -l } else { ls }
```

**Comment by mfdorst** [comment]
Interesting. What's the reason for this limitation?

**Comment by fdncred** [comment]
The aliases work, they're just scoped. So, when you leave the scope they're gone. I'm not sure why or if we intend that behavior.

**Comment by mfdorst** [comment]
Ohh okay that does make sense from a language point of view. However yeah, from a usability point of view that's kinda silly. Not sure there's a use case for scoping aliases. Maybe I'll make a feature request that aliases aren't scoped to if statements.
