### ISSUE TITLE
`header_on_separator` isn't taking all available terminal width

### ISSUE THREAD

**Issue by fdncred** [nushell/nushell#9993]
### Describe the bug

@zhiburt 
This is with `$env.config.table.header_on_separator = false`
![image](https://github.com/nushell/nushell/assets/343840/08726e63-e1ca-465f-94c0-236434efb289)
This is with `$env.config.table.header_on_separator = true`
![image](https://github.com/nushell/nushell/assets/343840/a7f7c027-ec34-4e8a-a35a-395263783a93)
Notice how it doesn't use the full width of the terminal.

Could you please look into this?

### How to reproduce

see above

### Expected behavior

take the full width of the terminal

### Configuration

|key|value|
|-|-|
|version|0.83.2|
|branch|main|
|commit_hash|e77a0a48aacb1ed41da0d48ad7b2eefa5b3336b3|
|build_os|macos-aarch64|
|build_target|aarch64-apple-darwin|
|rust_version|rustc 1.69.0 (84c898d65 2023-04-16)|
|rust_channel|1.69.0-aarch64-apple-darwin|
|cargo_version|cargo 1.69.0 (6e9a83356 2023-04-12)|
|build_time|2023-08-11 16:07:23 -05:00|
|build_rust_channel|release|
|allocator|mimalloc|
|features|dataframe, default, extra, sqlite, trash, which, zip|
|installed_plugins|emoji, from eml, from ics, from ini, from parquet, from plist, from vcf, gstat, highlight, hist, inc, json path, periodic-table, plot, pnet, query, query json, query web, query xml, regex, str bexpand, xyplot|

**Comment by fdncred** [comment]
@zhiburt Also, notice in the second screenshot above, the column `exit_status` is truncated to `e`. I've notice that columns get truncated at interesting times.

**Comment by amtoine** [comment]
@fdncred 
what is the size of your terminal and what is the command you are running?
i'm not sure i'm able to reproduce this issue :open_mouth:

**Comment by fdncred** [comment]
@amtoine it was `history | last 100`. it's fixed now.
