### ISSUE TITLE
Raw string can't be assigned to a variable

### ISSUE THREAD

**Issue by hustcer** [nushell/nushell#9995]
### Describe the bug

Raw string( wrapped by ``` `` ```) can't be assigned to a variable

### How to reproduce

```nushell
 λ $> echo `abc\n@v(ansi p)xyz(ansi reset)`
# Will get the following output as expected:
> abc\n@v(ansi p)xyz(ansi reset)
# However, assign the raw string to a var doesn't work:
 λ $> let var = `abc`
Error: nu::shell::external_command

  × External command failed
   ╭─[entry #98:1:1]
 1 │ let var = `abc`
   ·           ──┬──
   ·             ╰── executable was not found
   ╰────
  help: program not found
```

### Expected behavior

The assignment should work without any error, just the same as `let var = 'abc'`

### Configuration

| key                | value                                                |
| ------------------ | ---------------------------------------------------- |
| version            | 0.83.2                                               |
| branch             | main                                                 |
| commit_hash        | e77a0a48aacb1ed41da0d48ad7b2eefa5b3336b3             |
| build_os           | windows-x86_64                                       |
| build_target       | x86_64-pc-windows-msvc                               |
| rust_version       | rustc 1.69.0 (84c898d65 2023-04-16)                  |
| rust_channel       | 1.69.0-x86_64-pc-windows-msvc                        |
| cargo_version      | cargo 1.69.0 (6e9a83356 2023-04-12)                  |
| build_time         | 2023-08-12 07:53:30 +08:00                           |
| build_rust_channel | release                                              |
| allocator          | standard                                             |
| features           | dataframe, default, extra, sqlite, trash, which, zip |
| installed_plugins  | gstat, query, query json, query web, query xml       |

**Comment by WindSoilder** [comment]
I think it's expected, because a string wrapped with `` are treated as a bare word.

**Comment by amtoine** [comment]
related to 
- https://github.com/nushell/nushell/discussions/10552
- https://github.com/nushell/nushell/pull/9956

**Comment by sholderbach** [comment]
Closing this one as we now have the raw string support. This still leaves backtick strings in a bit of a weird place but at least its role in command position is pretty unambiguous.
