### ISSUE TITLE
How to disable autocomplete via tabbing

### ISSUE THREAD

**Issue by jeeeem** [nushell/nushell#9997]
### Question

How to disable the autocompletion on specific commands? When I type specific comamand then space then I tab, these are the commands that autocompleted

`z` then tab - > `lazy make`
`git` then tab  -> `register query`

And I must do this to show what I wanted to see
`z l `  then tab -> fuzzy search recent files with "l" character
`git a ` then tab  -> show available commands with "a" chacter

 I wanted to get all the available commands and all available recent files, but I can't do that as I will get the `lazy make` and `register query` on that particular commands

### Additional context and details

At my previous setup, I always do this to show the available commands like in `git` and `z` to fuzzy search all available directory that I previously went to, but I can't do that unless I specifically type a character before tabbing. 

I am Windows 11 and using `carapace-bin` for external completer.

**Comment by fdncred** [comment]
If you're using `carapace` for completions, I don't think this fits as a nushell repo question. It's a carapace question. I don't believe nushell alone support disallowing completions for certain commands.

**Comment by jeeeem** [comment]
I may need to clarify the term on what I am talking about, it's not completion per se, although it is still kinda a completion but on different way, it's like [abbr](https://fishshell.com/docs/current/cmds/abbr.html) in fish if you are familiar with that. 

So it autocomplete a certain command to a whole text like `gi` to `register query`.  While writing this, I do actually find the reason why it behaves like that, I disable the `quick` completion to `false` , so it now behaves like this
![image](https://github.com/nushell/nushell/assets/51053482/5449d4c6-86c4-44bb-8e3c-a7bcfced4c19)

With `true`, it behave like abbr in fish shell. I don't actually get the quick option before this, now I know I don't like this to be set to true.
