### ISSUE TITLE
RISCV support

### ISSUE THREAD

**Issue by balupton** [nushell/nushell#9999]
### Related problem

Would be cool if Nushell supported RISCV. I'm not sure what is involved at this point, as posting this issue to start the discussion as none existed yet.

if there aren't any cloud providers, you can get developer boards to borrow from https://riscv.org/risc-v-developer-boards/

i got vision five and vision five 2 dev boards to get https://github.com/bevry/dorothy going on riscv, which currently it does, however I'm considering adopting nushell instead of bash going forward for Dorothy. So RISCV support would be good for that.

### Describe the solution you'd like

Precompiled binaries for riscv

### Describe alternatives you've considered

Compling myself; haven't tried it yet

### Additional context and details

https://github.com/ClementTsang/bottom is a rust project that does support riscv, so perhaps their build pipeline could help with this

**Comment by sholderbach** [comment]
Among the nightly builds you can find a RISCV64 build. 
https://github.com/nushell/nightly/tags

See the associated [build matrix for that](https://github.com/nushell/nightly/blob/e180ea20c1954aa1a968c2dda2d44297577c80fe/.github/workflows/nightly-build.yml#L121-L148)

We had some problems with dependencies in the past that did not support RISC-V so we removed the attempt to build our regular releases. https://github.com/nushell/nushell/pull/9375

**Comment by balupton** [comment]
Perfect, thank you
